### PR TITLE
Fix the TS used for the GB-Mobile project.

### PR DESCRIPTION
**Pull request by SergioEstevao**
## Description

Make sure only types inside node_modules/@types are used.

This avoids TS to find the ../node_modules/@types inside the gb-mobile
repo that lives one path level up of gutenberg root.

@sirreal does this have impact on the Gutenberg TS checks?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by aduth** [comment]
I don't think this is what we'd want, since it would prevent TypeScript from being able to use types which are shipped with a package. With these changes, only community-maintained types from [DefinitelyTyped](https://definitelytyped.org/) would be used. The original package should always be the _preferred_ source of types, with DefinitelyTyped serving as a fallback, often in cases where the upstream package does not ship with their own (like was the case with every `@wordpress/` package prior to #18942).

**Comment by aduth** [comment]
Oh! I see what you're referring to as far as finding types in parent directories. While my previous point does still stand, and we don't want to be just finding types from `@types/` scope, there may still be some solution which still accounts for types from `node_modules/` root packages.

I seem to recall having a similar conversation about types or modules being found in parent directories, and something about it "working as intended", so it would be worth finding some clarity on this point.

**Comment by SergioEstevao** [comment]
@aduth I'm open to any suggestions...

**Comment by SergioEstevao** [comment]
@aduth so the documentation says by default: 
`
By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.`

So this will limit it to one level instead of going up the folder no?

**Comment by aduth** [comment]
My initial thinking is that something like this would work:

```json
{
    "typeRoots": [
        "./node_modules",
        "./node_modules/@types"
    ]
}
```

I'm still a bit unclear:

1. Order of priority here (`@types` should be fallback)
2. Whether this is the behavior we want.

**Comment by SergioEstevao** [comment]
We can also do this
```
"typeRoots": [./node_modules/**]
```

**Comment by SergioEstevao** [comment]
@aduth tested your suggested options and it doesn't work, it fails with TS errors. My second suggestion also do not work.

Do we have another `@type`s folder inside subfolders of `node_modules`?

**Comment by sirreal** [comment]
This part of config always leaves me confused, but in general I'd expect this PR to be fine.

> I don't think this is what we'd want, since it would prevent TypeScript from being able to use types which are shipped with a package.

I don't believe that's the case. When importing a package, TypeScript will still find its types if they're included. This has to do more with automatically included types.

It would be good to verify this one way or another. Redux is an example of a package that includes its types, we could test that out with this PR.

I did mention to @SergioEstevao via another channel that we might reconsider the setup for Gutenberg Mobile, which I'm completely unfamiliar with.

I left some relevant thoughts in a similar situation here: https://github.com/WordPress/gutenberg/pull/18531#discussion_r374611291

**Comment by SergioEstevao** [comment]
@aduth the documentation also says:
`Keep in mind that automatic inclusion is only important if you’re using files with global declarations (as opposed to files declared as modules). If you use an import "foo" statement, for instance, TypeScript may still look through node_modules & node_modules/@types folders to find the foo package.`

So is this configuration only limit were to find @types package but still allow the types defined on files?

**Comment by aduth** [comment]
@SergioEstevao I'm not sure, but based on what you've quoted there, my interpretation would be that it may even be supported to specify a `typeRoots` of an empty array, if TypeScript is going to dive into the local `node_modules` folders anyways?

**Comment by sirreal** [comment]
An alternative is to set `types: []`. This disables automatic type inclusion. Types will continue to be pulled in when associated packages are imported.

Any types that aren't part of the `lib` or included via imports (`webpack-env`, which modifies globals to include webpack globals is a common one) need to be added manually.

I'm sure there are pitfalls to any of these approaches but I'm not familiar with them. As long as we're not adding anything strange to the `types` array and the `build:package-types` script continues to work without error, I think these changes are pretty safe.

**Comment by SergioEstevao** [comment]
> An alternative is to set types: []. This disables automatic type inclusion. Types will continue to be pulled in when associated packages are imported.

I tried this but then the script `build:package-types` fails.

Up until now the configuration I have in this PR is the one that makes the script build and work
inside the GB-mobile project.

@aduth and @sirreal can we approve it as it is?

**Review by aduth — APPROVED** [review]
I can't say that I really understand why it works, but at least in a brief test, this seems to be fine, including when a package ships with their own types.

Tested with the following diff:

```diff
diff --git a/packages/i18n/src/create-i18n.js b/packages/i18n/src/create-i18n.js
index 0b0b4cd182..f8c395073c 100644
--- a/packages/i18n/src/create-i18n.js
+++ b/packages/i18n/src/create-i18n.js
@@ -50,7 +50,7 @@ export const createI18n = ( initialData, initialDomain ) => {
 	 *
 	 * @type {Tannin}
 	 */
-	const tannin = new Tannin( {} );
+	const tannin = new Tannin( 10 );
 
 	/**
 	 * Merges locale data into the Tannin instance by domain. Accepts data in a
```

Error (expected):

```
packages/i18n/src/create-i18n.js:53:29 - error TS2345: Argument of type '10' is not assignable to parameter of type '{ [domain: string]: { [key: string]: TanninDomainMetadata | [string, string]; '': TanninDomainMetadata | [string, string]; }; }'.

53  const tannin = new Tannin( 10 );
                               ~~


Found 1 error.
```

**Comment by sirreal** [comment]
> > An alternative is to set types: []. This disables automatic type inclusion. Types will continue to be pulled in when associated packages are imported.
> 
> I tried this but then the script `build:package-types` fails.

I'm not opposed to this as-is. `"types": [ "node" ]` works fine in a quick test. It would be nice to narrow this down because using `node` types in all packages (which I believe we're doing now) doesn't seem quite right.

**Comment by SergioEstevao** [comment]
> "types": [ "node" ] works fine in a quick test

This worked fine for GB-mobile too. @sirreal do you prefer to have it like that?

**Comment by sirreal** [comment]
> > "types": [ "node" ] works fine in a quick test
> 
> This worked fine for GB-mobile too. @sirreal do you prefer to have it like that?

With this approved, I'd say go ahead and merge as it is now. It's something that should be revisited either way.

**Pull request merged**
