### PR TITLE
Chrome: Adding the post external link component

### LINKED ISSUE #969: UI: Add external link button
Once you've published your post, you want the link to that post. You can get that link through the permalink interface in #577, and you can get it in the notice you get when you publish in #967. 

But outside of that, should there be another affordance for getting the link? 

Here's a design that we mocked up for this editor, and have since been testing in Calypso:

external link

external link hover

### PR DESCRIPTION
**Pull request by youknowriad**
closes #969 

I'm using a "title" instead of a tooltip (There's a current PR for tooltips).

### CODE REVIEW

**Comment by iseulde** [comment]
How do I test? I'm not seeing any added UI.

**Comment by youknowriad** [comment]
@iseulde did you save the post. (Sorry it's not clear, but yeah the link is showing only for saved posts)

**Comment by youknowriad** [comment]
@jasmussen What's the status of this, should we close for now?

**Comment by jasmussen** [comment]
Let's keep it around, but unmerged. I still have a hunch we might need it, but it'd be good to blog with this thing for a bit to know for sure. Thanks for working on it.

**Comment by youknowriad** [comment]
Closing as the issue was closed too.

**Pull request closed without merging**
