### PR TITLE
Term sorting is incorrect in flat term selector

### PR DESCRIPTION
**Pull request by mauteri**
## What?
The current search for term selection component is to search by most popular rather than a name search. With a limit of 20 terms to show up, this could mean the tag you are looking for does not show up on the list. This does not scale for sites with lots of terms of a taxonomy. We discovered it on one of our sites that has 13K tags.

## Why?
For sites with lots of tags, especially similarly spelled tags, it could result in the term not appearing in the autocomplete.

## How?
Since this is a search by name, it should have an orderby `name` and order `asc` to ensure the term you are searching for appears in the list.

## Testing Instructions
1. Add a bunch of tags with similar name (test, test1, test2, etc)
2. Assign one of those tags to a post (say `test3`)
3. When searching for tag and you type `test`, the first item will be `test3` with current code
4. In pull request the search will go by name / asc so it will be `test` as the first item (which is what someone would expect)

Current
Screen Shot 2023-02-06 at 11 40 36 AM

Fix
Screen Shot 2023-02-06 at 11 41 52 AM

### CODE REVIEW

**Review by Mamaduka — COMMENTED** [review]
Thank you, @mauteri!

I think query changes make sense here. The `order: asc`  and `orderby: name` are [default arguments for the request](https://developer.wordpress.org/rest-api/reference/tags/#arguments), so I think we can even omit those.

P.S. Rebasing on the top of the  trunk, should fix the failing React Native tests.

**Comment by mauteri** [comment]
> 

Thanks @Mamaduka! Just committed those changes. :-)

**Review by Mamaduka — APPROVED** [review]
Thank you, @mauteri!

**Comment by msaari** [comment]
Is it possible to adjust this to get back the original behaviour? On a site with 10k tags, this change was a huge step backwards in usability. Having the most common tags show up first was very important to make the users use the most common tags. Can I use a filter somewhere to get the count rank back?

**Comment by mauteri** [comment]
One of the main issues was tags not even showing up in the search when you have many similarly named as it caps the number to choose from to 20. You could type the whole tag name and it wouldn't appear in the list (like it didn't exist). I think that's a bigger issue.

**Comment by msaari** [comment]
For me, it's definitely the smaller problem here by a wide margin, but yeah, I can see that may not be the majority view (in our case, similar but more common would be preferable to exact but rare). But I wasn't asking to roll this back; I was asking for a method to adjust this locally. But as this comes from JS, looks like there isn't a filter I can use to adjust this. Having some way to control this locally would be great.

**Comment by mauteri** [comment]
I think a filter would make sense for your needs, but yeah, I think majority of sites would expect the order to match what is being searched for.

**Comment by mauteri** [comment]
I'll try to put in a PR for a filter here sometime in the next week.

**Comment by mauteri** [comment]
Follow up PR to this one https://github.com/WordPress/gutenberg/pull/58941 (cc @msaari)

**Pull request merged**
