### PR TITLE
wp-env: add mu-plugins support

### PR DESCRIPTION
**Pull request by noahtallen**
## Description
Adds support to .wp-env.json for mu-plugins. (Accepted sources work the same as themes & plugins.)

## How has this been tested?
Locally and with unit tests

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by epiqueras** [comment]
Doesn't #22256 remove the need for this? MU Plugins can just go in mappings, and we can keep the schema simple.

**Comment by noahtallen** [comment]
Sure. but why wouldn't we remove plugins and themes in that scenario? If the plugins/themes API is being kept because it's an easy-to-use API and not just for back-compat, then why wouldn't we support mu-plugins in that easy-to-use API as well? Unless we consider mu-plugins more of an advanced use case, I guess.

**Comment by epiqueras** [comment]
MU Plugins are an advanced use case, and they **don't need activation**.

**Comment by noahtallen** [comment]
> don't need activation

Right, how does that relate though? wp-env isn't trying to activate them. I'm definitely fine just using #22256 instead. 🤷 We can always reopen this if people really want mu-plugins as a more simple API.

**Comment by epiqueras** [comment]
Because the main benefit of having explicit `plugins` and `themes` fields is that we can activate them for the user, if `mu-plugins` don't need that, there is little value in adding it as a new field.

**Comment by noahtallen** [comment]
Ah, I see the argument.

**Pull request closed without merging**
