### PR TITLE
Add Utils package for Component System

### PR DESCRIPTION
**Pull request by ItsJonQ**
This update adds the core utilities package for the next [Component System](https://github.com/WordPress/gutenberg/issues/27484).

These utilities are shared and used liberally throughout the core Systems as well as the UI within the Component System.

Some utils are duplicates of the ones found in `@wordpress/components` 's `utils` directory:
https://github.com/WordPress/gutenberg/tree/master/packages/components/src/utils

They actually originated from there.
After this is merged, I can create a PR to consolidate them.

As @youknowriad has pointed out, there are utils that are similar to the ones found in `@wordpress/compose`, notably the hooks.

Those can also be consolidated in a later time.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
Thank goodness! Got the packages all happy now

**Comment by gziolo** [comment]
I left a quite long comment under the parent issue https://github.com/WordPress/gutenberg/issues/27484#issuecomment-739003356 where I propose we postpone work on this PR for now and use the npm package for the time being. Instead, we could focus initially on "Bringing over the Components". I will expand on that on Monday, have a great weekend 👋

**Comment by gziolo** [comment]
In the past, we had `@wordpress/utils` module. Long before WordPress packages were a thing. As you can see in https://github.com/WordPress/gutenberg/issues/3955, we decided to break it down into smaller packages that are built around functionality rather than a catch-all for everything that is hard to classify. I think here we should also seek for repeating the same process and adding those utilities to other existing packages or grouping them based on the functionality.

Based on my previous comment, I would also leave it as a very last task when moving code from the external repository/packages to the Gutenberg repository as switching the strategy from top-bottom integration might help us using more of the existing APIs (as pointed out by @youknowriad in his comments). It all can be discussed individually on PRs.

**Comment by ItsJonQ** [comment]
@gziolo Thank you for your thoughts and insights!

> I propose we postpone work on this PR for now and use the npm package for the time being

I'm 💯 down with this plan. I had originally proposed that we add things to Gutenberg because I felt like that was the only option.

**Comment by ItsJonQ** [comment]
Update: May pause on this as we attempt to use the `@wp-g2` packages directly:
https://github.com/WordPress/gutenberg/pull/27594

This PR was helpful though, as it helped highlight some parts of the `utils` package that could be optimized.

**Comment by ItsJonQ** [comment]
Closing this up! We'll revisit how we can best do this in the future.

**Pull request closed without merging**
