### PR TITLE
Iterations on the welcome guide

### LINKED ISSUE #19209: Iteration on the Welcome Guide
In the context of [19195](https://github.com/WordPress/gutenberg/pull/19195) trying to evolve the Welcome Guide as a critical moment for new users (potentially returning if switching back or after a while), here a new pass with a few considerations in mind:

1. Evolving the copy to be more direct, concise, and accurate. 
2. Adjusting the layout to be vertical, reduced (312x480), more adaptive to translations and screens.
3. Unifying visual elements.
4. Refreshing the look with more contrasted colors and sizes. 
5. Relating this to a potential evolution towards [18667](https://github.com/WordPress/gutenberg/issues/18667)

**Proposal**

welcome-guide1024x768

_Three steps_

welcome-guide1152x700

_Marks_

marks1152x700

_Localized_ (excuse the translations)

translations

In G2 styles [18667](https://github.com/WordPress/gutenberg/issues/18667)

g21152x700

**Copies**

_Step 1_
Welcome to the block editor
Create and edit rich content with images, paragraphs, or videos in the form of blocks. 

_Step 2_
Adapt each block as needed
All blocks come with controls for things like color, size, or alignment. 

_Step 3_
Find the right  ones for you
Browse or search among many blocks available in the block library.

**Current**

image

**Next steps**

- Feedback and iteration cycles.
- Test motion, trying to add some life to the illustrations.
- Clean and adjust the [figma file](https://www.figma.com/file/ctlWVC9KjYCLQlxTMAm81OT2/Tips-Iteration?node-id=563%3A64)

### PR DESCRIPTION
**Pull request by enriquesanchez**
Closes #19209, still WIP.

This PR updates the Welcome Guide following the iterations proposed on #19209. It updates the layout.

This PR can be tested on [gutenberg.run/21847](http://gutenberg.run/21847)

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Here's the current state of this PR:



There are some issues that I'm still working through:

1. [The proposed mockups](https://github.com/WordPress/gutenberg/issues/19209) display the pagination dots just below the image. This apparently is not that simple to do, since it'll require a bit of a refactor of the component, and doing so could cause those pagination dots to disappear for any third-party developers who are using the component.

2. If we were to keep the pagination dots at the bottom in the same row as the Prev/Next buttons, there's not enough space once you reach the last slide and the 'Get Started' button appears. I've already made the dots smaller and placed them closer together, but the available space is still not enough. And again, this will probably get worse once we introduce internationalization into the mix.

3. Moving from slide to slide, you'll notice a change in the modal's height. This is caused because the amount of text varies from slide to slide. Realistically, we should be OK with the fact that we don't have control over this, particularly if we consider internationalization and other uses of the component, and should look at alternatives.

**Comment by enriquesanchez** [comment]
@mapk @pablohoneyhoney @mtias I'd appreciate it if you could please give this PR a test and let me know what you think about the issues I mentioned in the comment above.

**Comment by noisysocks** [comment]
> 1. [The proposed mockups](https://github.com/WordPress/gutenberg/issues/19209) display the pagination dots just below the image. This apparently is not that simple to do, since it'll require a bit of a refactor of the component, and doing so could cause those pagination dots to disappear for any third-party developers who are using the component. @noisysocks is currently helping me digure out the viability of such change.

Hey @enriquesanchez, I created 9e6d4e87033867a09f6561e71058267384b5cbce which deprecates the Guide component's `children` prop in lieu of a less flexible but more structured `pages` prop. This lets us change Guide to  render the pagination dots in between the _image_ and the _content_.

My commit just modifies the markup and does not implement any of the necessary CSS changes. (I'll leave that up to you! 😛) If you'd like to add my commit to your branch and play with it, you can run:

```
git checkout try/evolve-the-welcome-guide
git cherry-pick 9e6d4e87033867a09f6561e71058267384b5cbce
```

**Comment by enriquesanchez** [comment]
Thank you @noisysocks!

**Comment by enriquesanchez** [comment]
Here's an update after the lastest round of changes:

**Comment by enriquesanchez** [comment]
Here's how it looks on a small viewport. I have the footer absolutely positioned to the bottom of the modal:

**Comment by pablohoneyhoney** [comment]
Nice! Becoming real : )
Here a few questions and notes. 

- Are we removing any animation or ease between steps? 
- It seems strange to me that it jumps between steps on [this one. ](https://github.com/WordPress/gutenberg/pull/21847#issuecomment-620229056)
- Maybe worth thinking of a hover state, being underline? Or use underline for the preferred path. 
- The little triangle corner is moving away for now, so it's better to not have it. 
- It could use a bit more space above the headline. 
- When introducing the + within, the line height gets uneven. 
- Would we be able to reduce copy, and have links to relevant content?
- It also seems to be triggered too often even for power users, maybe good to nail that intelligence.

**Comment by enriquesanchez** [comment]
Thanks for the feedback @pablohoneyhoney:

- [x] Maybe worth thinking of a hover state, being underline? Or use underline for the preferred path.
- [x] The little triangle corner is moving away for now, so it's better to not have it.
- [x] It could use a bit more space above the headline.
- [x] When introducing the + within, the line height gets uneven.

>Are we removing any animation or ease between steps? 
>It seems strange to me that it jumps between steps on this one. 

This is caused because the amount of text varies from slide to slide. I think that we should be OK with the fact that we don't have control over this, particularly if we consider internationalization and other uses of the component, and should look at alternatives. Do you have any thoughts here? The jump can definitively be made less jarring by adding animation between steps.

**Comment by enriquesanchez** [comment]
Some feedback [collected from today's design share](https://wordpress.slack.com/archives/C02S78ZAL/p1588183284371700) in the Making WordPress Slack:

- The close button (the 'X') looks like its part of the illustration. Maybe add more separation between them?
- The blue color used in the illustration is the same as the 'action' blue used for links and buttons. Should we make a distinction?
- Try setting the modal to a fixed height (and allow content overflow) to avoid the unwanted 'jump' between steps when the amount of text varies.

**Comment by enriquesanchez** [comment]
Made some tweaks to avoid the jump between steps due to varied amounts of text:

**Comment by enriquesanchez** [comment]
Updated the background color of illustrations:

**Comment by mtias** [comment]
@enriquesanchez nice work, love the iteration. Did you consider included the gifs from the issue? I think it could be a nice touch (fall back to static images if reduced-motion is set).

**Comment by enriquesanchez** [comment]
@mtias Yes, @ballio2000 will be helping us update the animated GIFs

**Comment by ballio2000** [comment]
Hello all. Please find the first pass of the animated welcome guide attached. The goal here is to keep the animation simple and smooth, while using motion to convey the user experiences within each frame. Feedback welcome. I will export the individual non-looping GIFs once we're good with them. Thanks! cc: @mtias @enriquesanchez 
g2-intro-2-01

**Comment by enriquesanchez** [comment]
These are looking great, @ballio2000! Thank you!

One tiny piece of feedback from me: The first one feels a bit different from the rest, and I think it's the animation of the white background as it appears. Because it expands angled, it doesn't feel a smooth as the other ones. Does that make sense?

@mtias do you have any comments before we move forward?

**Comment by mtias** [comment]
Good point, I agree.

**Comment by ballio2000** [comment]
@enriquesanchez @mtias Revised. :) I was going for a more 3D look to reveal the page. Notes makes sense though. Simplified it a bit here, let me know!
g2-intro-2-02

**Comment by enriquesanchez** [comment]
@ballio2000 These look great!

I think we can move forward and generate the gif files.

**Comment by ballio2000** [comment]
@enriquesanchez @mtias Please find the optimized GIFs attached. They're all set to play once and stop. Let me know if you all need anything else.
-g2-intro-01
-g2-intro-02
-g2-intro-03
-g2-intro-04

**Comment by enriquesanchez** [comment]
I've been trying to implement the `prefers-reduced-motion` query for these animated gifs, but because the static SVGs are set as inline images...

```
export const EditorImage = ( props ) => (
  <img
    alt=""
    src="data:image/svg+xml,%3Csvg fill='none' height='240' viewBox='0 0 312 240' width='312' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m0 0h312v240h-312z' fill='%2300a0d2'/%3E%3Crect fill='%23fff' height='108' rx='2' width='216' x='48' y='80'/%3E%3Cg stroke='%23000' stroke-width='1.5'%3E%3Cpath d='m158.917 142v-15.111'/%3E%3Cpath d='m154.472 142v-15.111'/%3E%3Cpath d='m162.333 126.75h-8.889'/%3E%3Cpath d='m153.139 130.889v4.071c-1.928-.353-3.389-2.041-3.389-4.071s1.461-3.718 3.389-4.071z' fill='%23000'/%3E%3C/g%3E%3Crect fill='%23fff' height='21' rx='1.5' stroke='%231e1e1e' width='117' x='48.5' y='53.5'/%3E%3Cpath d='m70.592 53v22' stroke='%231e1e1e'/%3E%3Cpath d='m144.432 53v22' stroke='%231e1e1e'/%3E%3Crect fill='%23333' height='8' rx='1' width='9' x='55' y='60'/%3E%3Cpath d='m150 63h2v2h-2z' fill='%23333'/%3E%3Cpath d='m154 63h2v2h-2z' fill='%23333'/%3E%3Cpath d='m158 63h2v2h-2z' fill='%23333'/%3E%3C/svg%3E"
    { ...props }
  />
);
```
... we can't make use of the [`prefers-reduced-motion` media query in the CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

I found [this other technique that uses the `<picture>` element and it's very cool](https://bradfrost.com/blog/post/reducing-motion-with-the-picture-element/). The idea is to do something like...

```
<picture>
  <source srcset="no-motion.jpg" media="(prefers-reduced-motion: reduce)"></source> 
  <img srcset="motion.gif" />
</picture>
```
The above includes both media elements, and the `<source>` element has the `prefers-reduced-motion: reduce` media query as an attribute. This led me to try...

```
export const CanvasImage = ( props ) => (
  <picture>
     <source 
      srcset="data:image/svg+xml,%3Csvg fill='none' height='240' viewBox='0 0 312 240' width='312' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m0 0h312v240h-312z' fill='%2300a0d2'/%3E%3Cpath d='m48 32c0-1.1046.8954-2 2-2h212c1.105 0 2 .8954 2 2v208h-216z' fill='%23fff'/%3E%3Cpath d='m60 38h191.455v34h-191.455z' fill='%23ddd'/%3E%3Cpath d='m151 49v11l5-4.125 5 4.125v-11h-5z' fill='%23000' stroke='%23000' stroke-width='1.5'/%3E%3Cpath d='m48 80h216v74h-216z' fill='%23e3e3e3'/%3E%3Crect height='16.5' rx='1.53571' stroke='%23000' stroke-width='1.5' width='16.5' x='147.75' y='108.75'/%3E%3Cpath d='m154 120v-6l5 3z' fill='%23000'/%3E%3Cpath d='m60 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cpath d='m159.982 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cg stroke='%23000' stroke-width='1.5'%3E%3Crect height='16.5' rx='1.25' width='16.5' x='97.75' y='179.75'/%3E%3Cpath d='m98 192 4.571-3.333 3.429 2.222 4-3.889 4 3.889' stroke-linejoin='round'/%3E%3Cpath d='m208.917 196v-15.111'/%3E%3Cpath d='m204.472 196v-15.111'/%3E%3Cpath d='m212.333 180.75h-8.889'/%3E%3Cpath d='m203.139 184.889v4.071c-1.928-.353-3.389-2.041-3.389-4.071s1.461-3.718 3.389-4.071z' fill='%23000'/%3E%3C/g%3E%3Cpath d='m60 220h191v20h-191z' fill='%23ddd'/%3E%3C/svg%3E"
      media="(prefers-reduced-motion: reduce)">
     { ...props }
    </source>
    <img
      alt=""
      srcset="my-animated.gif"
      { ...props }
    />
  </picture> 
);
```
... but that won't work. As far as I can tell, this is not going to work because `<source>` does not accept data URIs.

I was[ able to get this technique to work on a Codepen](https://codepen.io/enriquesanchez/pen/MWarxYY?editors=1000), but only if I use a URL of the SVG. It's actually really cool:



-------

@noisysocks What do you think of this technique? Would we be able to use the URL of the SVG instead? If so, where would we store the images? We'd also need a place to store the animated GIFs.

**Comment by mapk** [comment]
cc @jasmussen and @kjellr for some `prefer-reduced-motion` help here as well.

**Comment by jasmussen** [comment]
To include the prefers-reduced-motion mix-in you can simply do this:

```
	transition: 100ms transform ease;
	@include reduce-motion("transition");
```

☝️ that's just a code sample, the mixin is the key bit. Include that after the animation you add, and it should work. If it is to reduce an animation instead, include that:

```
	@include reduce-motion("animation");
```

**Comment by enriquesanchez** [comment]
Thanks for the feedback @jasmussen!

I'm still a bit confused, how is the mixin supposed to swap the image file? We have an animated GIF and want to change it for a static SVG. The tricky part is that these images are not declared as CSS background properties, they are declared inline. This is why I was lookit at using the motion query in the `<picture>` element.

**Comment by jasmussen** [comment]
Oh my mistake, the mixin won't help you there. Apologies.

You'll want to go straight to the prefers-reduced-motion query and write conditional css that hides the gif and shows the svg inside the query. There's some code here: 

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

Let me know if that helps. I'm afk for the rest of the day but if you don't get it working you can leave a note and I'll whip something up tomorrow.

**Comment by enriquesanchez** [comment]
>You'll want to go straight to the prefers-reduced-motion query and write conditional css that hides the gif and shows the svg inside the query.

Thank you @jasmussen,  that's a great idea.

---

@noisysocks I don't suppose we can do something like:

```
export const CanvasImage = ( props ) => (
	<img
		class="edit-post-welcome-guide__image__01"
		alt=""
		src="https://enriquesanchez.mx/illustration.gif"
		{ ...props }
	/>
	<img
		class="edit-post-welcome-guide__image__01alt"
		alt=""
		src="data:image/svg+xml,%3Csvg fill='none' height='240' viewBox='0 0 312 240' width='312' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m0 0h312v240h-312z' fill='%2300a0d2'/%3E%3Cpath d='m48 32c0-1.1046.8954-2 2-2h212c1.105 0 2 .8954 2 2v208h-216z' fill='%23fff'/%3E%3Cpath d='m60 38h191.455v34h-191.455z' fill='%23ddd'/%3E%3Cpath d='m151 49v11l5-4.125 5 4.125v-11h-5z' fill='%23000' stroke='%23000' stroke-width='1.5'/%3E%3Cpath d='m48 80h216v74h-216z' fill='%23e3e3e3'/%3E%3Crect height='16.5' rx='1.53571' stroke='%23000' stroke-width='1.5' width='16.5' x='147.75' y='108.75'/%3E%3Cpath d='m154 120v-6l5 3z' fill='%23000'/%3E%3Cpath d='m60 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cpath d='m159.982 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cg stroke='%23000' stroke-width='1.5'%3E%3Crect height='16.5' rx='1.25' width='16.5' x='97.75' y='179.75'/%3E%3Cpath d='m98 192 4.571-3.333 3.429 2.222 4-3.889 4 3.889' stroke-linejoin='round'/%3E%3Cpath d='m208.917 196v-15.111'/%3E%3Cpath d='m204.472 196v-15.111'/%3E%3Cpath d='m212.333 180.75h-8.889'/%3E%3Cpath d='m203.139 184.889v4.071c-1.928-.353-3.389-2.041-3.389-4.071s1.461-3.718 3.389-4.071z' fill='%23000'/%3E%3C/g%3E%3Cpath d='m60 220h191v20h-191z' fill='%23ddd'/%3E%3C/svg%3E"
		{ ...props }
	/>
);
```

...and then conditionally hide/show either of those images based on the motion query? 

I'm assuming because I just tried it and got some BABEL failures.

Is there any other way we could accomplish this?

**Comment by noisysocks** [comment]
Your snippet looks good except that you need to wrap the two images with [`<>...</>`](https://reactjs.org/docs/fragments.html) and use [`className`](https://reactjs.org/docs/faq-styling.html#how-do-i-add-css-classes-to-components) instead of `class`.

```js
export const CanvasImage = ( props ) => (
	<>
		<img
			className="edit-post-welcome-guide__image__01"
			alt=""
			src="https://enriquesanchez.mx/illustration.gif"
			{ ...props }
		/>
		<img
			className="edit-post-welcome-guide__image__01alt"
			alt=""
			src="data:image/svg+xml,%3Csvg fill='none' height='240' viewBox='0 0 312 240' width='312' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='m0 0h312v240h-312z' fill='%2300a0d2'/%3E%3Cpath d='m48 32c0-1.1046.8954-2 2-2h212c1.105 0 2 .8954 2 2v208h-216z' fill='%23fff'/%3E%3Cpath d='m60 38h191.455v34h-191.455z' fill='%23ddd'/%3E%3Cpath d='m151 49v11l5-4.125 5 4.125v-11h-5z' fill='%23000' stroke='%23000' stroke-width='1.5'/%3E%3Cpath d='m48 80h216v74h-216z' fill='%23e3e3e3'/%3E%3Crect height='16.5' rx='1.53571' stroke='%23000' stroke-width='1.5' width='16.5' x='147.75' y='108.75'/%3E%3Cpath d='m154 120v-6l5 3z' fill='%23000'/%3E%3Cpath d='m60 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cpath d='m159.982 163h91.4727v49h-91.4727z' fill='%23ddd'/%3E%3Cg stroke='%23000' stroke-width='1.5'%3E%3Crect height='16.5' rx='1.25' width='16.5' x='97.75' y='179.75'/%3E%3Cpath d='m98 192 4.571-3.333 3.429 2.222 4-3.889 4 3.889' stroke-linejoin='round'/%3E%3Cpath d='m208.917 196v-15.111'/%3E%3Cpath d='m204.472 196v-15.111'/%3E%3Cpath d='m212.333 180.75h-8.889'/%3E%3Cpath d='m203.139 184.889v4.071c-1.928-.353-3.389-2.041-3.389-4.071s1.461-3.718 3.389-4.071z' fill='%23000'/%3E%3C/g%3E%3Cpath d='m60 220h191v20h-191z' fill='%23ddd'/%3E%3C/svg%3E"
			{ ...props }
		/>
	</>
);
```

We shouldn't use `https://enriquesanchez.mx/illustration.gif` as the `src` because it will mean that WP Admin is reliant on a third party server. Instead, let's [generate a `data:` URL](https://dopiaza.org/tools/datauri/index.php) for the GIF.

I suspect that all of these inline `data:` images are starting to make the JS bundle size too large. We should follow up on this work with a separate PR which moves the images out of `data:` URLs and into e.g. `/wp-admin/images`.

**Comment by enriquesanchez** [comment]
Thanks for the feedback @noisysocks!

>We shouldn't use https://enriquesanchez.mx/illustration.gif as the src because it will mean that WP Admin is reliant on a third party server.

Correct, I was just using that external URL temporarily to test, will make sure I update it.

>I suspect that all of these inline data: images are starting to make the JS bundle size too large. We should follow up on this work with a separate PR which moves the images out of data: URLs and into e.g. /wp-admin/images.

Right, I was assuming I'll put the animated GIF files in  `/wp-admin/images`, should I also do that for the SVGs then?

**Comment by enriquesanchez** [comment]
I added the animated GIFs as data URI and all seems to work 👍

This is ready to be tested. If you're on a Mac, you can test the `prefers-reduced–motion` setting by going to System Preferences, select the Accessibility category, select the Display tab, and enable the Reduce Motion option.

On Windows 10, go to  Settings, select Ease of Access, select Display, select Show animations in Windows.

When no preference has been set, you should see the animated GIFs play once (no loop). If you set your display to reduced motion, then you should not see the animated GIF's and a static illustration should appear instead.

**Comment by noisysocks** [comment]
> Right, I was assuming I'll put the animated GIF files in `/wp-admin/images`, should I also do that for the SVGs then?

Yes, I think moving every SVG and GIF image to `/wp-admin/images` makes sense. But don't have to do it in this PR 🙂

**Review by mapk — APPROVED** [review]
I just tested this and it worked well from a design perspective. I haven't tried with reduced motion yet though. 

welcome

**Review by noisysocks — APPROVED** [review]
The code LGTM!

Let's definitely follow-up with a PR to move those image files elsewhere instead of using `data:` URLs as they're quite large! 🙂

**Pull request merged**
