### PR TITLE
Move Link Control action buttons into lower settings area

### PR DESCRIPTION
**Pull request by getdave**
## What?

Implements part of the design in [this Issue](https://github.com/WordPress/gutenberg/issues/47310) by moving the action buttons into the lower "settings" area.

Part of https://github.com/WordPress/gutenberg/issues/47310

## Why?

It helps to clean up the amount of space utilised by the buttons. It implements the design.

## How?

Moves buttons into the lower portion of the control.

## Testing Instructions

- Add text
- Add a link to that text
- Check that you can submit and cancel the link
- Check that action buttons only appear when editing a link.
- Also check link interface on:
    - buttons block
    - nav block

### Testing Instructions for Keyboard

As above but use a keyboard only. Ensure you can reach all of the controls within the link ui using the keyboard only.

## Screenshots or screencast 

Screenshot 2023-01-21 at 09 59 39
Screenshot 2023-01-21 at 09 59 46

### CODE REVIEW

**Comment by getdave** [comment]
@richtabor Question: shoudl the tab order still be maintained? I.e. when you tab out of the search input the 1st tab stop is the `Apply` button. So to access the toggle controls you need to tab a few more times.

I think that's pretty important to maintain from a UX POV but it does make the tab order not follow the visual order 😟

**Comment by richtabor** [comment]
> @richtabor Question: shoudl the tab order still be maintained? I.e. when you tab out of the search input the 1st tab stop is the Apply button. So to access the toggle controls you need to tab a few more times.

Typically tab order should have a logical reading order, usually from left to right and top to bottom in LTR. Do you know of other UI where we've parted from that logic? 

Current visual for reference: 

https://user-images.githubusercontent.com/1813435/213654796-72c1bc84-95d9-4ab6-85a2-b1546a0a0cb1.mp4

**Comment by getdave** [comment]
Yeh that's true and that's what's motivating my concern here. 

The issue I have is that a typical keyboard-based UX is:

- open link UI
- add URL to input
- hit TAB to move to Apply
- hit ENTER

With this change the new order would not allow that as the next tab stop after input would be the settings controls.

That said power users can still simply hit ENTER immediately on the input to submit without having to tab to `Apply`.

**Comment by jasmussen** [comment]
Per #47310 you can make the outline button into a text button.

**Comment by getdave** [comment]
> Per #47310 you can make the outline button into a text button.

Tackling that in https://github.com/WordPress/gutenberg/pull/47313

**Comment by getdave** [comment]
@richtabor I reverted to the logical tab order. If folks don't like it then we can review in follow ups.

As I mentioned earlier, we can still hit `ENTER` to submit so that's probably ok.

**Comment by getdave** [comment]
I've fixed both tests. Now awaiting a ✅ from someone 🙏

**Review by richtabor — APPROVED** [review]
LGTM

**Pull request merged**
