### PR TITLE
Persist alignment when transforming a gallery to an image.

### PR DESCRIPTION
**Pull request by andreilupu**
This is a small fix for #11374

## Description
I've added the `align` attribute when a gallery is transformed into an image.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by youknowriad** [comment]
What about the other way around, should we keep the alignments as well? Image => Gallery?

**Comment by andreilupu** [comment]
hey @youknowriad 
I shared my thoughts about the other way around in this [comment](https://github.com/WordPress/gutenberg/issues/11374#issuecomment-437205321)

I will do it, if it gets positive feedback.

**Comment by andreilupu** [comment]
@youknowriad I've pushed a conversion for the other way around and rebased it for when you have time.

**Comment by youknowriad** [comment]
Looks like something went wrong with the rebase/merge there's too many commits/diffs in this PR now

**Comment by andreilupu** [comment]
Yep, `git rebase` went horribly wrong.

I created a new one here https://github.com/WordPress/gutenberg/pull/12242

**Pull request closed without merging**
