### PR TITLE
Components: SelectControl - Add isLoading prop

### LINKED ISSUE #16026: No visual feedback when Parent Page dropdown is loading.
**Is your feature request related to a problem? Please describe.**

There's no visual feedback when the Parent Page dropdown in the Page Attributes inspector control is being populated via a REST API endpoint.

I open the Page Attributes panel, and then find myself thinking, "Wait, where's the Parent Page dropdown? I thought it was under this panel." And then, depending on how long the request takes to finish, I either go off in search of it by looking in other panels (and possibly closing Page Attributes in the process), or it appears just in time, and I realize that it was simply loading all along.

**Describe the solution you'd like**

Is there a compelling reason why this data needs to be fetched from the API, instead of just being passed from PHP to JS during the initial page request (i.e., with `wp_add_inline_script()`). The latter would make it available immediately, rather than introducing all of the overhead and latency of an HTTP request.

Although, I guess in some cases the number of pages could be so large that it would significantly slow down the initial page request. So maybe instead it'd be better to pre-fetch the data once the page has loaded, rather than waiting until the user has opened the panel?

**Describe alternatives you've considered**

If those options aren't good, then we should at least add immediately show the `Parent Page` label with a disabled dropdown, and a spinner, so that the user knows the application is loading data. When the data returns, the dropdown can be populated and enabled.

**Related issues (which won't solve the underlying problem)**

https://github.com/WordPress/gutenberg/issues/13618
https://github.com/WordPress/gutenberg/issues/15115

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description
This update adds the ability to render a loading state for the `SelectControl` (and `TreeSelect`) components.

This can be done by passing a `isLoading` prop, like:

```jsx
<SelectControl isLoading />
```

Screen Capture on 2020-04-06 at 14-06-16

GIF shows the `SelectControl` switching from loading to loaded.

When `isLoading` is set, the `select` HTML element will be disabled.

I've added more context re: design **[in this comment](https://github.com/WordPress/gutenberg/issues/16026#issuecomment-609971128)**

## How has this been tested?

In Storybook and in Jest (unit tests)

## Types of changes

* Add `isLoading` prop to `SelectControl`
* Render the inner `option` elements to account for loading
* Add unit tests for SelectControll

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves: https://github.com/WordPress/gutenberg/issues/16026#issuecomment-609924254

### CODE REVIEW

**Comment by MichaelArestad** [comment]
What is a good way to test this?

**Comment by ItsJonQ** [comment]
heya @MichaelArestad ! Oh dear, my apologies! I should have included testing instructions.

* Pull down the branch
* Run `npm install`
* Once that's done, run `npm run storybook:dev` to fire up Storybook
* Once that's loaded, search for the SelectControl
* At the bottom, there's a knob for `isLoading`, that you can flip

Screen Shot 2020-04-07 at 14 21 26

That will toggle the state and the UI

**Comment by MichaelArestad** [comment]
This looks good and works well. I added the "Needs Accessibility Feedback" label just to have someone take a look at that aspect of it.

**Comment by ndiego** [comment]
@ItsJonQ circling back on this PR as it came up in the weekly Editor Bug Scrub. Is there any reason that progress on this PR stopped?

**Comment by mirka** [comment]
@ciampo and I discussed how to proceed with this PR, and we decided to close this out since the original problem that needed to be fixed (Parent Page selector) is no longer a `select` but now a combobox.

It would be nice to have somewhat consistent loading states across the component library, but currently there is not enough product need to prioritize it.

We'll close this for now and refer back to it when implementing a loading state for the ComboboxControl. Thanks!

**Pull request closed without merging**
