### PR TITLE
Allow editing existing footnote from RichText formats toolbar

### LINKED ISSUE #52176: Footnotes block not removing formatting after block is deleted from the editor
### Description

Adding one or more footnotes in a page content the `fn` links format are not removed from the text if the footnotes block is deleted from the editor.

As additional note I see a strange behavior when I add a new note before an existing one, the block does not seems to reorder the internal list correctly.

### For the block removing issue

1. Create a new post or page and introduce a paragraph
2. Select a portion of the paragraph and add a footnote
3. Delete the Footnotes block

*Result* 
1. The `fn` elements are not removed from the paragraph
2. The Front-end is not rendering the `fn`
3. The Front-end is rendering asterisk 

### For the incorrect internal block list

1. Create a new post or page and introduce a paragraph
4. Select a portion of the paragraph and add a footnote
7. Select another portion of the paragraph which exists before the already added footnote

*Result*
1. The `fn` order looks correct but the block list order is incorrect and missing the new item

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/1917784/a82c6d47-bab9-4d83-8b51-d755786dacab

And here how's look like on FrontOffice when the Footnotes block is not available.

image

### Environment info

- Gutenberg `trunk` up to date to `dec307cff1` commit
- Wordpress 6.3-beta2-56116
- TwentyTwentyThree Theme (it's part of the wp-env)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by mcsf**
Alternative to #52504
Fixes #52176

## What?

Previously, clicking on the Footnote inline format in the RichText toolbar would always insert a new footnote, even if a footnote was already selected. With this pull request, clicking on the _Footnote_ item when a footnote is already selected (in RichText parlance: when the footnote object is active) focuses the corresponding entry in the Footnotes block.

**If no Footnotes block is present, one will be automatically added.** This is the existing behaviour when inserting a new footnote.

## Why?

I am leaning more towards this pull request than #52504. In particularly, I think it provides an adequate solution to #52176.

## How?

This pull request is best read with [whitespace changes hidden](https://github.com/WordPress/gutenberg/pull/52506/files?diff=unified&w=1).

If the footnote object is active, extract the ID of its corresponding entry in the footnotes block. Otherwise, proceed with creating a new object. The logic then proceeds as normally: insert a Footnotes block if none was found, then select its target entry.

## Testing Instructions
1. Start a post, add some text, then add some footnotes.
1. Verify that there is no change in behaviour when inserting footnotes by accessing the formats toolbar.
1. Select an existing footnote by clicking on its superscript element.
1. Verify that clicking on the now highlighted Footnote toolbar item moves focus to the Footnotes block at the appropriate entry.
1. Now delete the Footnotes **block**.
2. Once again, select an existing footnote by clicking on its superscript element.
3. Verify that clicking on the now highlighted Footnote toolbar items causes a fresh Footnotes block to be inserted, after which the corresponding entry receives focus.

## Screenshots or screencast 

**Before**

https://github.com/WordPress/gutenberg/assets/150562/0926b019-fcc6-4810-9164-f2b765428666

**After**

https://github.com/WordPress/gutenberg/assets/150562/f40d2c7e-627b-438a-9e83-5011def1635b

### CODE REVIEW

**Comment by youknowriad** [comment]
I think that's a decent behavior for now, but as people start to render footnotes in their block themes in templates: auto-inserting the footnotes block wouldn't be the right approach anymore.

So I think ultimately, I'd remove auto-insertion entirely (both initially and on update like done in this PR) and allow editing the footnotes elsewhere (popover for instance).

**Review by youknowriad — APPROVED** [review]

**Review by priethor — APPROVED** [review]
This fixes a current pain point and clearly improves the experience for 6.3.

I agree with Riad; we should rethink the editing interface for footnotes later.

**Comment by mcsf** [comment]
Thanks for the quick review, both of you. I agree with the next steps after this interim solution.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-batch-pre-RC1 branch to get it included in the next release: 70fb0f910b

**Comment by ockham** [comment]
I just cherry-picked this PR to the release/16.2 branch to get it included in the next release: 66e2fffad4

**Pull request merged**
