### PR TITLE
[RNMobile] Change ripple effect n BottomSheet settings

### PR DESCRIPTION
**Pull request by jbinda**
## Description

Prevent the Slider in BottomSheet settings to have ripple effect after press on its title.

Please also refer to:
[Related gutenberg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2023)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2022)

## How has this been tested?

1. Add Stepper block (it has Slider in settings to control its height)
2. Open settings to see Slider
3. Press on Slider title to see if it has ripple effect
4. Check if you can check Slider value

- check if a11y works after proposed changes

## Screenshots 

**AFTER:**

**BEFORE:**

## Types of changes

Refactor: prevent ripple effect on Slider cell in BottomSheet settings (iOS and Android)
Refactor: disable ripple effect for BottomSheet rows on iOS

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jbinda** [comment]
please also refer to (this commnet](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2022#issuecomment-600783538) for more details

**Review by etoledom — COMMENTED** [review]
Thanks for this PR @jbinda !

It works as expected with the common flow, but testing with VoiceOver I had troubles. It seems that the slider is not accessible through VoiceOver anymore.

Independent from this PR, I also noticed that when the Spacer Block is selected, there's no feedback from VoiceOver on its body.

**Comment by jbinda** [comment]
@etoledom @iamthomasbishop 

Here is the build with VoiceOver fix on iOS:
iOS: [IPA 25805](https://github.com/wordpress-mobile/WordPress-iOS/pull/13691)

>Independent from this PR, I also noticed that when the Spacer Block is selected, there's no feedback from VoiceOver on its body.

There was some refactor on Spacer [here](https://github.com/WordPress/gutenberg/pull/20746) and I didn't check how it works before that. However in my last build its still not working. After we deal with the current PR I think I will raise an issue for that and address in separate PR

**Review by etoledom — APPROVED** [review]
Tested on iOS and Android and its working great!

Feel free to merge after @iamthomasbishop approval.
I'm also happy to test again if we decide to change Android behaviour before merging.

> There was some refactor on Spacer here and I didn't check how it works before that. However in my last build it still not working. After we deal with the current PR I think I will raise an issue for that and address in separate PR

Sounds good 👍

**Comment by iamthomasbishop** [comment]
Tested the latest builds on Android + iOS and it feels solid 👍. 

Side note: As I mentioned earlier, I would prefer the native ripple effect on Android but this works fine for now, we can always iterate on it.

**Comment by jbinda** [comment]
Thanks for checking. I have adjust title of the PR because its more refactor than a BUG specially if we also affect ripple effect for all cells in BottomSheet on iOS

@pinarol wdyt, can we merge this ?

**Comment by pinarol** [comment]
Yes please, thank you @jbinda !

**Comment by jbinda** [comment]
As spoke with @pinarol os Slack I decided to defer merging this to release 1.25. Release is merged so I also merge.

**Pull request merged**
