### PR TITLE
data-basics/4-building-a-create-page-form is ready now

### PR DESCRIPTION
**Pull request by leemyongpakva**
## What?

data-basics/4-building-a-create-page-form/ is ready now. So **Next part** at the bottom of data-basics/3-building-an-edit-form/
need to be updated.
## Why?

When a part came, it is not _Coming soon_ any more :)

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! 

We also need to update the meta file. Could you commit & push it after running `npm run docs:build`?

**Comment by leemyongpakva** [comment]
@t-hamano I could not because I don't have a clone of gutenberg on my PC and don't intend to have one in the near future. :). Be free to close this PR, and create another with the meta file update youself.

**Review by t-hamano — APPROVED** [review]
I've run `docs:build` on your branch and pushed it to this PR.

We should now be ready to merge 👍

**Comment by leemyongpakva** [comment]
Thanks for the manifest update. By the way, I still see **Part 4:** on the left sidebar .

**Comment by t-hamano** [comment]
@leemyongpakva Thanks for noticing. It certainly seems like the title isn't getting updated on the handbook page.

### Handbook page

https://developer.wordpress.org/block-editor/how-to-guides/data-basics/4-building-a-create-page-form/

handbook

### GitHub Readme

https://github.com/WordPress/gutenberg/blob/0ee8ce4536a2fc57ddeef10b9ada4bf9ceb07cdd/docs/how-to-guides/data-basics/4-building-a-create-page-form.md

github


@ndiego @juanmaguitar 

My understanding was that both the title and content would be synced to the handbook page, but does the title have to be updated manually?

**Pull request merged**
