### PR TITLE
Try: Fix gallery item clicking.

### LINKED ISSUE #29835: Actions unavailable after selecting an image within a gallery block
## Description
In WordPress 5.7, it is impossible to select any editing options for a gallery image immediately after clicking the pencil icon in the top right of the image.

## Step-by-step reproduction instructions
1. Create a new post
2. Drag the Gallery pattern (two images side by side)
3. Select one of the images
4. Click the pencil in the top right of that image.
5. Try to click Upload, Media Library, or Insert from URL and notice they cannot be selected.

In order to select these options, you have to remove focus from the gallery block and then re-select the block.

## Expected behaviour
You should be able to click those items immediately after clicking the pencil icon on an image.

## Actual behaviour
You cannot click any of the options for editing a gallery image.

**Note:** This does not just happen when gallery blocks are inserted using the pattern, it also happens when using the block inserter. It also happens when following these steps to edit when an actual site specific image is in the gallery.

No console warnings were present.

## WordPress information
This seems to happen in:
- WordPress 5.7
- WordPress `trunk`
- Regardless of which theme is active
- With no plugins active.
- Having the Gutenberg plugin active does not solve the issue.

## Device information
- Device: Desktop
- Operating system: MacOS Catalina
- Browser: Firefox nightly

Discovered researching a separate issue [reported on Trac](https://core.trac.wordpress.org/ticket/52789) by @mikelittle.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #29835.

I have not had time to test this thoroughly, so I'd appreciate sanity checks and tests of edgecases this might introduce.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ajitbohra** [comment]
Editing options are now usable 👍 

But how to cancel the editing mode? the first impression was clicking again on the pencil icon might toggle the edit mode

**Comment by jasmussen** [comment]
Thanks for testing!

> But how to cancel the editing mode? the first impression was clicking again on the pencil icon might toggle the edit mode

I think that's a separate issue, and it might not be worth fixing since the gallery is being refactored to use innerblocks soon.

**Comment by paaljoachim** [comment]
Hey Joen

I just tested the PR. Upload, Media Library and Insert from URL now works.

https://user-images.githubusercontent.com/5323259/111176049-48116980-85a9-11eb-82ce-fbd14de722ab.mp4

**Review by youknowriad — APPROVED** [review]
This makes sense to me, that "before" style is just used to show the outline so it's not something that should be clickable anyway.

**Pull request merged**
