### PR TITLE
API: Stabilize localAutosave() as autosave( { local: true } )

### PR DESCRIPTION
**Pull request by mcsf**
## Description
Part of #20116. See https://github.com/WordPress/gutenberg/issues/20116#issuecomment-584244847.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
As an imperative verb (as conventional for action creators), "local autosave" is perhaps a bit awkward/forced, but I think it can work.

**Comment by mcsf** [comment]
> As an imperative verb (as conventional for action creators), "local autosave" is perhaps a bit awkward/forced, but I think it can work.

I had the same feeling. :) I wondered about `doLocalAutosave`, `locallyAutosave`. Thoughts?

**Comment by aduth** [comment]
Had there been any prior consideration to make this an _option_ of the existing `autosave` action creator?

e.g.

```js
autosave( { local: true } );
```

**Comment by mcsf** [comment]
> Had there been any prior consideration to make this an _option_ of the existing `autosave` action creator?

I don't recall, but I don't dislike it.

**Comment by mtias** [comment]
I like it.

**Comment by ellatrix** [comment]
Can this be merged?

**Comment by youknowriad** [comment]
What's remaining here?

**Comment by mcsf** [comment]
> Can this be merged?

> What's remaining here?

I can refresh the branch and switch `localAutosave` to `autosave( { local: true } )`, [as Andrew suggested](https://github.com/WordPress/gutenberg/pull/20149#issuecomment-584355020). Anyone opposed?

**Comment by mcsf** [comment]
@ellatrix or @youknowriad: can you give it a last review, for good measure? 🙏

**Review by youknowriad — APPROVED** [review]
:shipit:

**Pull request merged**
