### PR TITLE
[Mobile]: Fix broken imports on native rich-text.

### PR DESCRIPTION
**Pull request by etoledom**
This is a small PR to fix broken imports due to the addition of `__unstable` prefix.

To test:
- Check out the related [`gutenberg-mobile` PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/863).
- Check that lists doesn't crash when adding a new list item (pressing Enter).

### CODE REVIEW

**Comment by hypest** [comment]
👋 @etoledom , I think `insertLineBreak` have been removed (replaced by plain use of `insert`). Can you check and remove it from mobile too?

**Comment by etoledom** [comment]
@hypest - Updated `insertLineBreak()` with `insert()`.

I tested it by removing the `split` prop from the Heading block and having a multiline heading block.

Also works pressing `shift` in the simulator (with the computer's keyboard) and having multiline paragraph block.

**Review by hypest — APPROVED** [review]
LGTM!

**Comment by etoledom** [comment]
Thank you!

**Comment by hypest** [comment]
Headsup. Found this after we merged this PR: There is another breakage. Line https://github.com/WordPress/gutenberg/commit/e6e5d852425837a3f887723ef6498c50737818e0#diff-046b96483a89756efe39ddabba55d748R11 breaks the list type switching on native mobile. cc @ellatrix

**Comment by ellatrix** [comment]
@hypest has everything been fixed now? Thanks!

**Comment by hypest** [comment]
All good by now Ella, thanks! For reference: https://github.com/WordPress/gutenberg/pull/15010

**Pull request merged**
