### PR TITLE
Fix issue with gradient swatches stacking badly with scrollbar.

### PR DESCRIPTION
**Pull request by jasmussen**
A small regression landed with gradient swatches recently. It looks fine with no scrollbar:

Screenshot 2020-09-02 at 10 27 46

But it wraps badly when there is one:

Screenshot 2020-09-02 at 10 27 56

This PR fixes that:

Screenshot 2020-09-02 at 10 59 12
Screenshot 2020-09-02 at 10 59 17

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@jasmussen Thanks for this! Will review shortly + fix up that failing JS Unit test (it looks like it's just the snapshots)

**Comment by ItsJonQ** [comment]
There's something funky going on with my local dev I think... (trying to update snapshot tests)

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Tested locally and is working as expected. Thanks @jasmussen !

**Comment by ItsJonQ** [comment]
@jasmussen Will merge this once tests are green 🟢 !

**Comment by jasmussen** [comment]
Thank you for all the help! I'll merge when the checks pass.

**Pull request merged**
