### PR TITLE
Migrate paragraph test to Playwright

### PR DESCRIPTION
**Pull request by miminari**
## What?
Migrate [paragraph.test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/blocks/paragraph.test.js) to its Playwright version.

## Why?
See https://github.com/WordPress/gutenberg/pull/38570 for its background and rationale. 

## How?
See [MIGRATION.md](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md) for migration steps.

## Testing Instructions
Run npm run test-e2e:playwright -- /test/e2e/specs/editor/blocks/paragraph.spec.js.

related #38851

### CODE REVIEW

**Comment by kevin940726** [comment]
Hi, thanks for the PR! Note that the new test should be placed in the `test/e2e/specs` folder though :) (and the old test should be deleted)

**Comment by miminari** [comment]
> Hi, thanks for the PR! Note that the new test should be placed in the `test/e2e/specs` folder though :) (and the old test should be deleted)

@kevin940726 
Thank you for your reply. 

I am seeing this for the first time, but the GitHub display is seemingly showing the same file as changed... However, I have deleted the file in question and placed it in the appropriate directory.

Plz see this file.
https://github.com/WordPress/gutenberg/blob/243723701023673cd2fe49f1ae849357feb3155f/test/e2e/specs/editor/blocks/paragraph.spec.js

**Comment by kevin940726** [comment]
Oh my bad! I misread it in the GitHub UI. You did it right 👍.

**Review by kevin940726 — APPROVED** [review]
Looks good to me 💯

Thanks for the PR! 🧡 I'll merge it after CI passes.

**Pull request merged**
