### PR TITLE
Code quality: Remove old templates list code

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
This PR removes the old template and template parts list code since we have stabilized the ones with DataViews.

## Testing Instructions
1. Everything should work as before
2. Template and template parts list work as before

### CODE REVIEW

**Comment by jameskoster** [comment]
I didn't spot any issues 👍

**Review by jorgefilipecosta — APPROVED** [review]
The changes look good I did not spotted any issue, and things tested well 👍

**Comment by peterwilsoncc** [comment]
I can see a few references to these files in WordPress-Develop's copy of `src/wp-includes/js/dist/edit-site.js`.

Were these all private APIs or do they need to go through a deprecation process?

**Comment by ntsekouras** [comment]
>I can see a few references to these files in WordPress-Develop's copy of src/wp-includes/js/dist/edit-site.js.

What do you mean by references? This was not used - not exported code.

**Comment by peterwilsoncc** [comment]
> This was not used - not exported code.

Thanks Nik, this is what I was asking. I couldn't figure out if they were being exported for internal use vs exported from the package. It looks like it was the former.

**Pull request merged**
