### PR TITLE
Add nested blocks inside cover block

### LINKED ISSUE #10746: Cover image block - Allow text element choice
**Is your feature request related to a problem? Please describe.**
The cover image block specifies in the description _"Add a full-width image, and layer text over it — great for headers."_ However, the text outputs in a paragraph tag and not a header.

**Describe the solution you'd like**
The option for the text to be treated as a heading instead of a paragraph. When the text should be a heading the user should be able to select which heading they would like to use.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Closes #10746.

Previous attempt: https://github.com/WordPress/gutenberg/pull/10639, #12405
This PR adds nesting to cover image block.
This allows the user to use a heading instead of a paragraph, choose the heading level, and even add buttons making it possible to use the cover block as a call to action.

## How has this been tested?
I verified the block worked as expected.
I created cover blocks using Gutenberg master and I verified the blocks are correctly migrated to this version, without validation errors.

## Screenshots
screenshot 2019-02-11 at 20 14 57
screenshot 2019-02-11 at 20 16 10

### CODE REVIEW

**Comment by gziolo** [comment]
Technically this PR allows to nested multiple blocks, which is an enhancement in comparison to the previous version which allows using only text which would translate to a single block. It might be a good idea to allow multiple blocks but at the same time, this might be very close to how Section block is going to be shaped. We should decide whether we should leave it limited to only one block on top of the image or video. Fun fact is that implementation-wise it might be easier to allow multiple blocks to be inserted :)

**Review by mapk — CHANGES_REQUESTED** [review]
The functionality works as I expected. The nested block limitations for the Heading, Paragraph, and Button blocks made sense.

The only problem I saw was the Heading block isn't centered vertically.

cover

You can see this difference when I switch back from the Heading to the Paragraph. Can we get this aligned better?

**Comment by kjellr** [comment]
> The only problem I saw was the Heading block isn't centered vertically.

@mapk, I _think_ that's because there's an invisible default appender there. 

screen shot 2019-02-12 at 12 44 25 pm

If that's the case, we should probably clarify that. Maybe it requires the grayed-out "Start typing or..." text. Or perhaps some variation of the appender @jasmussen created for #10136 would make sense in this context?  

46478283-9d32d980-c7ba-11e8-99b8-d5aaea30c044

**Comment by kjellr** [comment]
For reference, the current appender is there, but the + only appears on hover:

appender

(It's also hard to see against the dark background, which should be fixed either way we handle this)

**Comment by jorgefilipecosta** [comment]
Hi @mapk and @kjellr thank you for reviewing this PR.
@kjellr is right the reason why the heading block appears vertically uncentered is because of the default appender being rendered.
So we should address this problem together with the problem of the appender not being noticeable.
Using the appender used when default block is not supported we get this result:
screenshot 2019-02-13 at 16 12 35

But we may use custom styles and try to mimic the hover styles that look like this:
screenshot 2019-02-13 at 16 12 42

If we want to keep the normal appender when default blocks are supported (paragraphs) we may also try to customize its styles in a similar way to how the inserter looks on hoover:
screenshot 2019-02-13 at 16 13 27

Regarding the option of showing some text on the appender to inform the user it is possible to start typing, we already do this:
screenshot 2019-02-13 at 16 15 47

But this message only appears if the user clicked and then did not wrote anything we can change to show the message all the time. 


Independently of the path we choose we need to make sure we have different colors borders, backgrounds and text/icon colors with high contrast so if the user chooses a cover image/video with colors similar to one of our choices the user still notices the design element because of the other colors. Similar to what @jasmussen did on the block movers that now are always noticeable independently of the background.

I'm not sure about what is the best option to follow, and I would love some thoughts on this.

**Comment by mapk** [comment]
Part of what makes this block really shine is the ability to see it all together right in the editor. If the block appender is a part of that causing the heading shift too far upwards, then it causes a visual problem. But if there's a way to show the appender when the block is focused, and hide the appender when the block is not focused, that sounds like a plan!

In the case of which appender to show? I like the text "Start writing or type..." to be visible when the block has focus. Is the text have enough contrast?

The option of an outlined appender doesn't seem visible enough.
The option of a filled grey block appender seems too visible and takes away from the overall cohesiveness of the design.
The option of a subtle + icon seems visually awkward, unless we think about inverting the color of the icon so that a background isn't needed?

Any other thoughts, @kjellr ?

**Comment by ZebulanStanphill** [comment]
>Part of what makes this block really shine is the ability to see it all together right in the editor. If the block appender is a part of that causing the heading shift too far upwards, then it causes a visual problem. But if there's a way to show the appender when the block is focused, and hide the appender when the block is not focused, that sounds like a plan!

I think this is important to tackle in general as it affects all blocks with nesting, e.g. the Columns or eventual Container block.

I made #13571 suggesting some changes to the sibling inserter that could solve this problem.

**Comment by jasmussen** [comment]
> But if there's a way to show the appender when the block is focused, and hide the appender when the block is not focused, that sounds like a plan!

This makes sense insofar as the selected block is okay to show additional UI. However it might be worth discussing this over a GIF, because there's a little more to it:

cover

The cover title really is only offset if the text appender is there. And it isn't unless you actually press Enter first to _create one_. So I would argue that if the cover title is offset, it's because the user added a linebreak. Which they should be allowed to.

---

Going into review this, I was completely ready to suggest that nested blocks inside the Cover block might make less sense given [we will have a Section block, as Gzregorz suggested](https://github.com/WordPress/gutenberg/pull/13822#issuecomment-462686782). However, after trying this PR out, I'm not of a different mind again.

This is a cool block, it's a cool PR, and I love it for the same reason I love the Media & Text block. It's a highly specific block that's intended to be decorative. While the Section block might have overlapping features, that's _okay_, because the section block is likely going to be more advanced and complex to configure in other ways — for example the Section Block is not likely to have a placeholder/setup state, it's likely to just be a _box_ that you configure from the sidebar. But the cover block starts with a setup state, it won't work at all unless you add a background image. We can consider it a "section block with opinionated defaults" — hey if we convert it to be that technically too, that would be fine. But the point I'm trying to make here is that it's helpful for a casual user to have this block, because it's a really easy way to create a decorative post. Let a thousand blocks bloom, it's okay that you might be able to accomplish the same with the section block. This one just makes it easier.

---

Going to the specifics of this PR, it feels really solid. The block even expands if you add enough linebreaks. I love it. 

As far as I'm concerned, the challenge we have to solve here is that when the background is dark, it's impossible to see the block inserter. 

Gutenberg already supports dark backgrounds on a global level: https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#dark-backgrounds — does it make sense to leverage those styles to invert the UI inside the Cover Block if a dark image is used? To keep this implementation relatively simple, it might be a matter of figuring out whether the overlay color is darker than `rgb(127,127,127)` or not. I.e. if the overlay color averages lower than that, go dark, higher than that, go light. For example `rgb(100,80,126)` would invoke dark mode for the cover block UI. This is sort of an example of how that would look:

dark mode

It fixes most of the contrast issues. Even if we can't guarantee contrast always — a user could choose a really sub-optimal contrast ratio themselves — this would be a vast improvement.

**Comment by jasmussen** [comment]
@jorgefilipecosta see also #13869 as it fixes a dark theme issue.

**Comment by kjellr** [comment]
> The cover title really is only offset if the text appender is there. And it isn't unless you actually press Enter first to _create one_. So I would argue that if the cover title is offset, it's because the user added a linebreak. Which they should be allowed to.

This is totally correct. After testing again, the appender didn't show up until I hit return. And when it did show up, I was able to hit delete in there to remove it. This seems reasonable to me. As long as the appender is visible (so that you know it's not just a weird empty space), I think we're all set. 

> Gutenberg already supports dark backgrounds on a global level: https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#dark-backgrounds — does it make sense to leverage those styles to invert the UI inside the Cover Block if a dark image is used? To keep this implementation relatively simple, it might be a matter of figuring out whether the overlay color is darker than `rgb(127,127,127)` or not. I.e. if the overlay color averages lower than that, go dark, higher than that, go light.

This seems like a solid direction to me. 👍

**Comment by SchneiderSam** [comment]
With the whole thing I wonder if it doesn't make more sense to work on Add Block: Section #4900. I have the feeling that a lite-section is being worked on here, even though the section issue that we've been wanting for such a long time has been left unfinished. 

I don't understand why this is being given so much priority.

The other issue (#4900) would also solve this problem or make the cover block completely unnecessary.

And if I translate that into the Lego language: why don't we build the **basic building blocks** before we get to the trees, cars and bicycles?

**Comment by jorgefilipecosta** [comment]
Thank you all for the inputs 👍 

> Gutenberg already supports dark backgrounds on a global level: [wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#dark-backgrounds](https://wordpress.org/gutenberg/handbook/designers-developers/developers/themes/theme-support/#dark-backgrounds) — does it make sense to leverage those styles to invert the UI inside the Cover Block if a dark image is used? To keep this implementation relatively simple, it might be a matter of figuring out whether the overlay color is darker than `rgb(127,127,127)` or not. I.e. if the overlay color averages lower than that, go dark, higher than that, go light.

Hi, I will try to give a try to this solution proposed by @jasmussen. But there are some cases where I expect this solution to not work correctly, namely an image that is dark in some parts and very light in other parts e.g. some flags, and in videos that have frames that are dark and other frames that are white.
I guess in most practical cases the solution will work.

Hi @SchneiderSam,

> With the whole thing I wonder if it doesn't make more sense to work on Add Block: Section #4900. I have the feeling that a lite-section is being worked on here, even though the section issue that we've been wanting for such a long time has been left unfinished.
> I don't understand why this is being given so much priority.

@jasmussen shared some thoughts around this subject:

> for example the Section Block is not likely to have a placeholder/setup state, it's likely to just be a _box_ that you configure from the sidebar. But the cover block starts with a setup state, it won't work at all unless you add a background image. We can consider it a "section block with opinionated defaults" — hey if we convert it to be that technically too, that would be fine. But the point I'm trying to make here is that it's helpful for a casual user to have this block, because it's a really easy way to create a decorative post. Let a thousand blocks bloom, it's okay that you might be able to accomplish the same with the section block. This one just makes it easier.

I think the cover block has very specific functionality that the section may not have like the focal point selector.
It is also important to note that the adjustments we make here to way nesting works will also benefit a future section. This also allows us to test nesting a little bit more, before going to the section block. I expect the section block to be widely used in the community and will probably serve as a basis for many things being built in the future so it is important that we get it right. Exploring in cover will contribute to that.

**Comment by jasmussen** [comment]
> there are some cases where I expect this solution to not work correctly, namely an image that is dark in some parts and very light in other parts e.g. some flags, and in videos that have frames that are dark and other frames that are white.

Yes, I do expect there will be challenges, but arguably these are unavoidable with anything that involves text over an image. We can help guide the user towards best practices through strong defaults, but even then a user can turn down the opacity and make text illegible, we can't enforce that.

The reason this might work, though, is that it works on the _overlay color_. If you have a dark image, your overlay is likely to be dark. If you are working with a light image (and dark text), your overlay is likely to be light. It's an assumption that this will work, and if it's a ton of work maybe not worth it? But if it's relatively easy, it seems like it could work for us. As you mention yourself though, we will encounter this issue again with the section block, so these things might benefit us regardless.

**Comment by SchneiderSam** [comment]
@jorgefilipecosta Well, I don't quite understand that yet. That sounds like the motto: Let's build a roof before we make the foundation. You said yourself that the Block section is used by a larger audience, so it makes sense to work on it first.

I think it's really great you're working on this, but that's the point of giving #4900 more weight:

Section Block so that I can do everything I want to do with the cover block and then set it as a reusable block. Two flies with one claw.

I just want to pick up again what @aduth [wrote](https://github.com/WordPress/gutenberg/pull/9416#issuecomment-422853484). So i am not alone:

screenshot_1

Before I have Lego-trees, Lego-cars and Lego-ships, it would be great to get the **normal Lego blocks** first. Otherwise I can play Playmobil and move the blocks for a while...

Sorry, that's not criticism, just a thought push. As I said: you're doing a great job, but maybe my comment will help!

**Comment by paaljoachim** [comment]
I am very excited that the existing Cover Block becomes the first major Core block that will add a built in nesting. It blazes the way for other blocks to follow. Existing blocks and new blocks such as the Section Block.

It creates a greater flexibility in which container to use in a layout. Use the Cover Block with a specific setup, or use other container type of blocks. Each have their own setup and options. Options that will greatly overlap each other giving a really nice flexibility for the user.

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen,
I added a mechanism that applies the dark theme styles depending on the colors of image/video if the opacity is equal or lower than 50 or depending on the overlay color if opacity is greater than 50.
For now, we are just adding a class we may customize the styles further let me know your thoughts on this approach.

> @jorgefilipecosta Well, I don't quite understand that yet. That sounds like the motto: Let's build a roof before we make the foundation. You said yourself that the Block section is used by a larger audience, so it makes sense to work on it first.

> I think it's really great you're working on this, but that's the point of giving #4900 more weight:

> Section Block so that I can do everything I want to do with the cover block and then set it as a reusable block. Two flies with one claw.

> I just want to pick up again what @aduth [wrote](https://github.com/WordPress/gutenberg/pull/9416#issuecomment-422853484). So i am not alone:

Hi @SchneiderSam,
You are for sure not alone, and your thoughts are entirely valid and welcome, thank you for sharing them!
The quote is part of some discussions about how to reuse functionality between different blocks one approach was to reuse the blocks them selfs using InnerBlocks other approach was to reuse the components and the blocks wanting a given feature would use the same component. At the time the path followed was the component reusability.

To decide which are the components and their ideal API, we need to prototype and test first that's what we are doing here.
This PR does not block the section block they are not mutually exclusive, and we may even decide to port the artifacts being tested here to the section block, everything is opened we are in an exploratory phase.
Both blocks are being iterated in parallel with different assignees that makes testing different features easier.
Probably the features added here (if we find them valuable) will then be abstracted and reused in the section block and any other block in the community.

**Comment by SchneiderSam** [comment]
Okay, thanks for your comment. I speak from the point of view of a special target group (designers and small entrepreneurs). And that's a feature (#4900) that many people are longing for at the moment. With this feature we could design and build so many things. It wouldn't even have to work perfectly (like many other blocks aren't perfect, by the way, but at least they're already there).

To the topic: the focal point would also be a great thing in the Section Block. If I wanted to use a picture there, it would be a super thing.

Ok again: great work and please keep up the good work. It's also nice that you listen to my "voice".

**Comment by getdave** [comment]
I've been made aware of this PR by @paaljoachim. Thought I'd mention that I'm aiming to land a vertical alignment feature for Core Columns. I've created a reusable toolbar component for that feature and I wonder whether this would be useful in this PR?

VAlign PR is https://github.com/WordPress/gutenberg/pull/13899

**Comment by gziolo** [comment]
> I've created a reusable toolbar component for that feature and I wonder whether this would be useful in this PR?

It is out of the scope of this PR but it should be discussed separately for sure.

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen, @kjellr what are your thoughts on the current state of this PR?
(We are adding a new dependency in order to test we need to run "npm install")

**Comment by jasmussen** [comment]
Nice work. 

Honestly I think this is very very close to be done. It's not _perfect_, as shown in the following GIF you can enter situations where the borders are invisible. But this doesn't break the utility of the block, and we can't prevent the user from ending up in completely crazy situations, we can just ensure things still function.

nice

As you can see, the hover color is off. You can probably add a small rule her: https://github.com/WordPress/gutenberg/blob/0f18024e477bafec475ec3785bb2209562a961c4/packages/editor/src/components/block-mover/style.scss#L45 _— and it should work.

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen, thank you for the review 👍 I applied a fix to the problem.

**Comment by kjellr** [comment]
Agreed with @jasmussen — this works well. I think there are minor refinements we can make, for instance, fine-tuning the appearance of the insertion point inserter on dark backgrounds: 

screen shot 2019-03-06 at 10 28 32 am

Right now, the white background seems a little jarring to me. But that's really minor, and can be iterated on separately. 

---

I did notice that on some screen widths, the inner block toolbars get cut off, but I'm not sure if that issue is specific to this PR or not: 

screen shot 2019-03-06 at 10 32 11 am

---

Also worth noting: I think Twenty Nineteen may need a small patch to ensure front end text colors are working correctly with these new changes. I can get a patch going to fix that though. 

Editor: 
screen shot 2019-03-06 at 10 25 41 am

Front End: 
screen shot 2019-03-06 at 10 25 49 am

**Comment by kjellr** [comment]
> Also worth noting: I think Twenty Nineteen may need a small patch to ensure front end text colors are working correctly with these new changes. I can get a patch going to fix that though.

Update: Turns out this Twenty Nineteen issue effected _all_ nested blocks. 😄 I've submitted a patch here: 

https://core.trac.wordpress.org/ticket/46432

**Review by mapk — APPROVED** [review]

**Comment by jorgefilipecosta** [comment]
Thank you for the reviews 👍  This is a risky PR I merged it so we have more time to test. If someone notices a please comment so I can open a follow-up PR or in the worst case revert this PR before the next release.

**Comment by irishetcher** [comment]
Some odd alignment behaviour. Title text is indented by about 5 or six letters. Text in paragraph underneath aligned left. Looks odd.

**Comment by melchoyce** [comment]
Hey @irishetcher, could you create a new issue for the problem you're experiencing, with a screenshot?

**Comment by NewJenk** [comment]
Could you add the spacer as one of the available blocks? The cover works really nicely as a parallax background, as shown here: https://apollo13.campaignpro.net, and the spacer would negate the need for a load of br's.

**Comment by youknowriad** [comment]
@NewJenk Would you be able to open an issue for this? Sounds like a "Good First Issue" :)

**Comment by irishetcher** [comment]
@melchoyce Sorry it took a while to get back with the screenshot. Here is what I am seeing. The title is a full "Lorem" indented from the left:

cover-block

**Comment by theodend** [comment]
How to add the possiblity to add a search block inside cover ? Would make a nice attractive bloc.

**Pull request merged**
