### PR TITLE
[RN-MOBILE] fix line height crash

### LINKED ISSUE #12211: JSApplicationIllegalArgumentException: Error while updating property 'lineHeight' in shadow node of type: RCTAztecView
**Sentry Url**: https://sentry.io/share/issue/0244926c0adf4aeda025bc36bae98d3e/
**User Count**: 936
**Count**: 4073
**First Release**: org.wordpress.android-14.9-rc-1
**First Seen**: 2020-05-21T22:24:51Z
**Last Seen**: 2020-06-16T22:57:57Z
**24 Hours**: 224
**30 Days**: 4030

```
JSApplicationIllegalArgumentException: Error while updating property 'lineHeight' in shadow node of type: RCTAztecView
     at com.facebook.react.uimanager.ViewManagersPropertyCache$FloatPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:223)
     at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:106)
     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:159)
     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:63)
     at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:318)
     at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:249)
     at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:465)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by marecar3**
Fixes: https://github.com/wordpress-mobile/WordPress-Android/issues/12211

## Description
Current Gutenberg implementation is supporting line-height without unit e.g. 'line-height':1.5
and library which we are using to [convert css to react-native](https://github.com/kristerkari/css-to-react-native-transform/blob/945866e84a505fdfb1a43b03ebe4bd32784a7f22/src/index.spec.js#L1234) requires unit to be included with dimension and that scenario is leading to crash _of the Aztec wrapper on Android_.

However, we didn't choose to fix (patch) the library as native AztevView doesn't support lineHeight at this moment so focus on this fix was to remove lineHeight from style.

## How has this been tested?
Run the Demo app and app shouldn't crash

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by hypest — APPROVED** [review]
LGTM!

Verified the fix and the crash if I just remove the `delete style.lineHeight`, nice fix!

Also, thanks for the inline comments explaining the removal, and the added demo html!

**Comment by hypest** [comment]
Rerunning jobs as the mobile E2E job suffered from the known `Assertion failed: (!uv__is_closing(handle)), function uv_close, file ../deps/uv/src/unix/core.c, line 113` issue and it's not related to this PR.

**Comment by marecar3** [comment]
> LGTM!
> 
> Verified the fix and the crash if I just remove the `delete style.lineHeight`, nice fix!
> 
> Also, thanks for the inline comments explaining the removal, and the added demo html!

Thanks for the approval!

**Comment by hypest** [comment]
The CI job failed again but, since we know for sure that it's not an issue with this PR and there's already [another PR to address the issue](https://github.com/WordPress/gutenberg/pull/23452), I'll go ahead and merge.

**Pull request merged**
