### PR TITLE
Give props to contributors

### PR DESCRIPTION
**Pull request by jasmussen**
This is a first stab at making a separate file containing contributors. It is a lot of manual work, but we can update it in bulk, and it's worth it to ensure people get virtual compliments for their hard work, even if that hard work might not be code specific.

This starts work at fixing #1223

CC: @ntwb, @karmatosed

### CODE REVIEW

**Comment by karmatosed** [comment]
This seems a great first pass to me. ❤️

**Comment by jasmussen** [comment]
Awesome! Merging.

**Comment by nylen** [comment]
How did you generate this file?  Let's automate it.

**Comment by jasmussen** [comment]
> How did you generate this file? Let's automate it.

Manual work. I started with the contributors listed in this repo, and then went through tickets where I knew people had contributed, like in the gutenberg testing tickets. This is admittedly somewhat prone to human error, but it's the only way I can think of that incluces people who didn't commit code, and isn't just a 1:1 inclusion of everyone who commented on tickets here.

**Comment by ntwb** [comment]
> _"This list is manually curated to include valuable contributions by volunteers *that do not include code*, such as user testing, providing feedback, or mockups. Please edit this list to include new contributors as they come in. There is no particular order to this list. If you or someone else were omitted from this list, we assure you that was not intentional. Please let us know and we'll add you."_

I think `that do not include code` should be removed and the file expanded to include code contributions also as when it comes time to add a "Props" commit to WordPress Core this list will be required, would also will be required are w.org usernames of the contributors, for example I'm @ntwb here on GitHub but `@netweb` on w.org, see #1350 as a first pass for this (A follow up to #1350 would be a _good-first-issue_ for someone)

**Comment by nylen** [comment]
> Let's automate it.

If we need it, generating a list of *code* contributors could be automated, and we could probably write something to help manage the list a bit too.  This part I agree is a list that we need to add to manually:

> Manual work. I started with the contributors listed in this repo, and then went through tickets where I knew people had contributed, like in the gutenberg testing tickets.

**Pull request merged**
