### PR TITLE
Scripts: Upgrade puppeteer dependency

### PR DESCRIPTION
**Pull request by gziolo**
## Description
I have some trouble with upgrading Puppeteer in #20215 so I want to do it in smaller steps.

The bundled `puppeteer` dependency has been updated from requiring `^2.0.0` to requiring `^2.1.1`. It uses Chromium v80 instead of Chromium v79. See the [full list of changes](https://github.com/GoogleChrome/puppeteer/releases/tag/v2.1.0).

### CODE REVIEW

**Comment by gziolo** [comment]
There are the same errors reported as in #20215 

```
 adding inline tokens › should insert inline image
1025
1026    TimeoutError: waiting for selector ".media-modal li[aria-label="44d63e16-126e-4a32-8fe2-4e153365622e"]" failed: timeout 30000ms exceeded
1027
1028      44 | 		const filename = uuid();
1029      45 | 		const tmpFileName = path.join( os.tmpdir(), filename + '.png' );
1030    > 46 | 		fs.copyFileSync( testImagePath, tmpFileName );
1031         | 		             ^
1032      47 | 		await inputElement.uploadFile( tmpFileName );
1033      48 | 
1034      49 | 		// Wait for upload.
```

```
FAIL packages/e2e-tests/specs/editor/blocks/classic.test.js (38.322s)
1016  Classic
1017    ✓ should be inserted (3942ms)
1018    ✕ should insert media, convert to blocks, and undo in one step (33686ms)
1019
1020  ● Classic › should insert media, convert to blocks, and undo in one step
1021
1022    TimeoutError: waiting for selector ".media-modal li[aria-label="2a200fd2-818c-4545-b2c0-67a8dc03da8d"]" failed: timeout 30000ms exceeded
1023
1024      60 | 			'assets',
1025      61 | 			'10x10_e2e_test_image_z9T8jK.png'
1026    > 62 | 		);
1027         | 		  ^
1028      63 | 		const filename = uuid();
1029      64 | 		const tmpFileName = path.join( os.tmpdir(), filename + '.png' );
1030      65 | 		fs.copyFileSync( testImagePath, tmpFileName );
```

```
FAIL packages/e2e-tests/specs/editor/various/manage-reusable-blocks.test.js (30.795s)
1038  Managing reusable blocks
1039    ✕ Should import reusable blocks (30064ms)
1040
1041  ● Managing reusable blocks › Should import reusable blocks
1042
1043    TimeoutError: waiting for selector ".notice-success" failed: timeout 30000ms exceeded
1044
1045      43 | 			'..',
1046      44 | 			'assets',
1047    > 45 | 			'greeting-reusable-block.json'
1048         | 			            ^
1049      46 | 		);
1050      47 | 		const input = await page.$( '.list-reusable-blocks-import-form input' );
1051      48 | 		await input.uploadFile( testReusableBlockFile );
```

**Comment by gziolo** [comment]
It's a known issue in Puppeteer, related issues: https://github.com/puppeteer/puppeteer/issues/5363, https://github.com/puppeteer/puppeteer/issues/5420. We will have to wait for `2.1.2` to be rolled out.

**Comment by aduth** [comment]
Feel free to request my review once the fixed version of Puppeteer is released and this pull request is updated.

**Comment by aduth** [comment]
Looking at the install script code, if the issue is caused by newer version of Chromium, I wonder if we could pin it to a revision from an earlier version (e.g. the version we're currently on).

```
PUPPETEER_CHROMIUM_REVISION= 722234 node install.js
```

**Comment by gziolo** [comment]
> Looking at the install script code, if the issue is caused by newer version of Chromium, I wonder if we could pin it to a revision from an earlier version (e.g. the version we're currently on).
> 
> ```
> PUPPETEER_CHROMIUM_REVISION=722234 node install.js
> ```

Interesting idea. Trying with 3e7f08cbe80a43a6efb8be3d6edb4785c835b5ac.

**Comment by gziolo** [comment]
Unfortunately, it still fails even though it downloads Chromium pinned to Puppeteer 2.0:

https://travis-ci.com/github/WordPress/gutenberg/jobs/297678868#L327

```
Chromium downloaded to /home/travis/build/WordPress/gutenberg/node_modules/puppeteer/.local-chromium/linux-722234
```

**Pull request closed without merging**
