### PR TITLE
Docs: tweak organization for getting-started docs

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Issue #33429 highlighted an issue with too many nesting levels of the
tutorials, they do not show properly in the sidebar.

This PR will start to address, by removing the tutorials layer and
moving the two getting started guides up a level.

- Remove a nesting level for getting-started

- Move FAQ, Glossary, and History to explanations section, they add a
  bit of noise to the getting started section and fit well in
  explanations since the content is more historical reference for the
  project

- Fix link references to new locations across the docs

## How has this been tested?

Documentation - confirm updates make sense and links are correct.

## Types of changes

Documentation.

**NOTE:**

TRAC Ticket with redirects: https://meta.trac.wordpress.org/ticket/5912

### CODE REVIEW

**Comment by gwwar** [comment]
🤔 Is it a problem with nesting? One of the child pages that is even more nested shows up correctly:

| dev environment (sidebar wrong) | ubuntu env (sidebar correct) |
|-----|-----|
| devenv | ubuntu |

How can we test this with the sidebar on WP.org? (Maybe we can cc folks who can test it?)

**Comment by mkaz** [comment]
@gwwar Nesting is not necessarily the problem with it showing up in the sidebar, but it not showing up highlighted to me that we are needlessly nesting two sections. The tutorials section that is there only contains the two getting started tutorials with the rest of them in the "How to Guides" section. So having an extra nesting for Tutorials is not really necessarily and makes sense to just move them up to "getting-started"

I believe they are not showing up due to the way it is trying to match pages to items in the sidebar. The sidebar is created by the [Handbook widget here](https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/plugins/handbook/inc/handbook.php#L715).

My thought is to clean up the organization of the files, and then troubleshoot with the items in their proper place.

**Comment by gziolo** [comment]
We will have also to update occurrences in the codebase like here:

https://github.com/WordPress/gutenberg/blob/0ebe9b3a9183a907d6eaf26c3f9f1860bd29dd2e/packages/create-block/lib/templates/esnext/%24slug.php.mustache#L29

**Comment by mkaz** [comment]
Thanks @gziolo - I had searched the repo but somehow missed a few links. Updated :+1: 

There were several links already broken to other areas not even changed here, I fixed those up too. :grin:

**Review by gziolo — COMMENTED** [review]
Nice, thank you 💯

**Comment by mkaz** [comment]
NOTE: I added the TRAC ticket with redirects here: https://meta.trac.wordpress.org/ticket/5912

Once approved, we'll want to coordinate the merge of this ticket with the redirects.

**Comment by mkaz** [comment]
@gziolo I rebased and I think this is ready.

**Review by gziolo — APPROVED** [review]
It looks good, let's give it a go and see how it plays out.

**Pull request merged**
