### PR TITLE
Icons: add new "send" icon

### PR DESCRIPTION
**Pull request by simison**
## What?
Adds a new "send" icon to be used by WordPress plugins that might be doing anything "sending" related, such as chats, emails, newsletters, CRM, comments, form submissions, debug messages, etc.

Screenshot 2024-07-31 at 12 32 57

~Pulling from [WordPress Figma design library's icon explorations](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=62310-15562&t=ugMqZ2nHf89bO50G-4).~ Update: [redesigned below](https://github.com/WordPress/gutenberg/pull/64130#issuecomment-2260201259).

## Why?

"Send" is a fairly typical action in different admin and frontend UIs, and a paper plane has become a common symbol for the action. E.g. Apple Mail uses the symbol:

Screenshot 2024-07-31 at 11 16 24

So does Google Gmail:

Screenshot 2024-07-31 at 11 17 27<br/>

Screenshot 2024-07-31 at 11 16 48

Various chat apps also use paperplane:

Telegram
telegram input

WhatsApp
whatsapp input

FB Messenger
FB messenger input

Example usage in the plugin's feature to send blog posts as emails to yourself:

Screenshot 2024-07-31 at 11 28 45

## Testing Instructions

- Run Storybook locally `npm run storybook:dev`
- Open the icon library http://localhost:50240/?path=/story/icons-icon--library
- See "send" icon
image

### CODE REVIEW

**Comment by simison** [comment]
If merged, Figma needs updating the icon from "Explored" to the "Generic" section.

Who should I attribute as the designer?

**Comment by simison** [comment]
As far as design goes, the horizontal version in chat examples seems to work well in small size, even in outlined variation as seen with Gmail .

**Comment by jasmussen** [comment]
Nice one, we definitely need this icon.

However we don't often use that particular angle, which is not quite 45 degrees. There's also something about the curve on the tail end of the plane, and the stroke widths, that doesn't feel quite right. Here's a remix:

Screenshot 2024-07-31 at 10 42 10

What do you think? If you're into it, here are the vectors:

```
<svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.7 3.59 22.322 12 3.7 20.41 6.704 12 3.7 3.59Zm4.329 9.16L6.3 17.59l10.717-4.84H8.03Zm8.988-1.5H8.03L6.3 6.41l10.717 4.84Z" fill="#000"/></svg>
```

Separate note, ideally the SVGs are flattened to have a single `path` rather than two. The reasoning is the anticipation of a build system (#38850) that works best when this is the case. When we get to that, the reason may become moot, but for now we're still flattening.

**Comment by simison** [comment]
Excellent!

Any difference using `viewBox="0 0 24 24"` or `width="24" height="24"` or both? I see `viewbox` used a bunch in other icons. I went with `viewBox` for now.

I'll update screenshots in the description, for the history:

Old:
Screenshot 2024-07-31 at 11 23 49

New:
image

**Comment by javierarce** [comment]
> What do you think? If you're into it, here are the vectors:

I think we could use the 45º angle. As @jasmussen said, it's not very common, but it's definitely something we could consider if it makes sense. To me, it does, because the direction implies we are sending something up to the sky.

But more important than the angle, I think we should add some border radius to the edges to match the roundness of other icons.

Here's a quick mockup:

image

And I added my proposals [here](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=95869-4665&t=VCJpnsu7OMkXGtEm-4):

image
image

**Comment by jasmussen** [comment]
I don't feel strongly about the angle, even if I prefer it straight. Happy to defer. 

I'm not convinced about the roundness, though. If you look at the other examples you cite, the roundness is applied sparingly, e.g. not to the "Edit" icon at all. So the comparison doesn't work too great to me. However in comparison with my quick sketch, your is definitely less "sharp", so that makes sense. I'm not sold on this curve though:

Screenshot 2024-07-31 at 12 29 06

When viewed at 24x24 it's too small to notice, really. Not sure if the following is any better, but it's [a quick test](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=95879-4746&t=hqde0QT2KvbFPOeW-1).
Screenshot 2024-07-31 at 12 32 57

**Comment by t-hamano** [comment]
Once the icon is finalized, we will need to remove the hardcoded `#000` color. The icon is expected to automatically change color depending on the context.

For example, given the current SVG, the following SVG should also display correctly:

```html
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<path
		fill-rule="evenodd"
		clip-rule="evenodd"
		d="M3.7 3.59 22.322 12 3.7 20.41 6.704 12 3.7 3.59Zm4.329 9.16L6.3 17.59l10.717-4.84H8.03Zm8.988-1.5H8.03L6.3 6.41l10.717 4.84Z"
	/>
</svg>
```

Update: Since this is actually a React element, `fill-rule` and `clip-rule` will cause a browser warning. We'll need to replace them with `fillRule` and `clipRule`, like so:

```html
<SVG viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
	<Path
		fillRule="evenodd"
		clipRule="evenodd"
		d="M3.7 3.59 22.322 12 3.7 20.41 6.704 12 3.7 3.59Zm4.329 9.16L6.3 17.59l10.717-4.84H8.03Zm8.988-1.5H8.03L6.3 6.41l10.717 4.84Z"
	/>
</SVG>
```

**Comment by jasmussen** [comment]
These icons are easy to update, and will be even easier in the future, so let's not overthink this. Based on Javi and Aki's feedback, I pushed [this version](https://github.com/WordPress/gutenberg/pull/64130#issuecomment-2260201259).

**Comment by simison** [comment]
@t-hamano @jasmussen thanks! I addressed the [feedback](https://github.com/WordPress/gutenberg/pull/64130#issuecomment-2260485071), and I think this is ready now.

Confirmed colour still works in the storybook:

image

**Review by jasmussen — APPROVED** [review]
I'd appreciate a gut-check from Aki and/or Javi before landing this. Thank you firo contributing!

**Review by t-hamano — APPROVED** [review]
LGTM! I've also tested applying a temporary different color, and it seems to change color correctly just like the other icons 👍


image

**Comment by simison** [comment]
Merged but if we'd like to tweak designs, happy to open follow-up PR. Just lemme know.

**Comment by t-hamano** [comment]
@simison, Next time you merge, it's a good idea to add props to the description. See the comments [here](https://github.com/WordPress/gutenberg/pull/64130#issuecomment-2259959173).

**Comment by simison** [comment]
@t-hamano yep! I did add them to the commit message (https://github.com/WordPress/gutenberg/commit/6581dfb8f1c605119db776f023a83d655209bfa8), but did you mean some other description than the commit message?

**Comment by t-hamano** [comment]
You'll probably need to use strict formatting, which means you'll need to paste the props code exactly as it appears in [this comment](https://github.com/WordPress/gutenberg/pull/64130#issuecomment-2259959173) in order for co-author avatars to appear in [the commits](https://github.com/WordPress/gutenberg/commits/trunk/).

commit

**Pull request merged**
