### PR TITLE
Removes the inspector controls for the navigation block

### PR DESCRIPTION
**Pull request by draganescu**
## Description
There currently are no sidebar options for the Navigation Block but there is one option who just remained there from the initial testing: automatically add new pages to the menu. This option does nothing if set.

## How has this been tested?
The option is gone.

### CODE REVIEW

**Review by getdave — APPROVED** [review]
I tested this and I can confirm the controls have been removed.

I agree that they are not required as they don't really do anything.

**Comment by talldan** [comment]
Looks good to me too. Tests are failing due to some linting errors though, but I can't actually see those errors when I check out the code 🤔

**Comment by talldan** [comment]
Lemme try a rebase

**Comment by talldan** [comment]
Rebased and the new alignments code in the nav block uses `attributes` and `setAttributes`, so had to add those back to solve the linting errors.

**Review by talldan — APPROVED** [review]

**Pull request merged**
