### PR TITLE
Plugin: Move files from `lib` to the `compat` subfolder

### PR DESCRIPTION
**Pull request by gziolo**
## What?

Part of #39889. It only moved the files to the proper subfolders so they can be matched with the corresponding WordPress major release.

## Why?

To follow the best practices for PHP code in the Gutenberg plugin as documented in https://github.com/WordPress/gutenberg/tree/trunk/lib#file-structure.

## How?

I was going through the files that need to be backported to WordPress core for the upcoming 6.0 release. I noticed a few files in the `lib` folder that should live elsewhere.

I also moved all files from `lib/compat/experimental` to `lib/experimental` based on the feedback from @hellofromtonya.

### Experimental features

- `WP_REST_Block_Editor_Settings_Controller`
- `WP_REST_Block_Navigation_Areas_Controller`
- `WP_Rest_Customizer_Nonces`

### Shipped in WordPress 5.9

I located the same code in WP core:

- `WP_REST_Menu_Items_Controller`
- `WP_REST_Menu_Locations_Controller`
- `WP_REST_Menus_Controller`
- `WP_REST_URL_Details_Controller`

### To ship in WordPress 6.0

- `gutenberg_register_gutenberg_patterns`

## Testing Instructions

There should be no change in how the Gutenberg plugin works.

### CODE REVIEW

**Comment by gziolo** [comment]
@ntsekouras - it looks like `gutenberg_register_gutenberg_patterns` targeted WordPress 5.9, are there any follow-up changes that should get included in WordPress 6.0?

**Comment by hellofromtonya** [comment]
>Experimental features
>- `WP_REST_Block_Editor_Settings_Controller`
>- `WP_REST_Block_Navigation_Areas_Controller`
>- `WP_Rest_Customizer_Nonces`

Why move these experimental features to `lib/compat/experiment`.  Should they live in `lib/experimental` per https://github.com/WordPress/gutenberg/tree/trunk/lib#file-structure as they are still experimental and not ready to be merged into WordPress Core? 

>`lib/experimental` - Experimental features that exist only in the plugin. They are not ready to be merged to Core.

**Comment by gziolo** [comment]
> > Experimental features
> > 
> > * `WP_REST_Block_Editor_Settings_Controller`
> > * `WP_REST_Block_Navigation_Areas_Controller`
> > * `WP_Rest_Customizer_Nonces`
> 
> Why move these experimental features to `lib/compat/experiment`. Should they live in `lib/experimental` per https://github.com/WordPress/gutenberg/tree/trunk/lib#file-structure as they are still experimental and not ready to be merged into WordPress Core?
> 
> > `lib/experimental` - Experimental features that exist only in the plugin. They are not ready to be merged to Core.

The reality is a bit different than the documentation because there is no `lib/experimental` folder in the project.Anyway,  I will move everything from `lib/compat/experiment` to the the documented location. 👍

**Comment by ntsekouras** [comment]
>@ntsekouras - it looks like gutenberg_register_gutenberg_patterns targeted WordPress 5.9, are there any follow-up changes that should get included in WordPress 6.0?

Actually it seems that the specific file might not be needed. Let me check a bit better. It seems to have changes six months ago, but it was for another feature that later on, I moved it to the `compat/5.9` [here](https://github.com/WordPress/gutenberg/pull/37451).

**Comment by gziolo** [comment]
> > @ntsekouras - it looks like gutenberg_register_gutenberg_patterns targeted WordPress 5.9, are there any follow-up changes that should get included in WordPress 6.0?
> 
> Actually it seems that the specific file might not be needed. Let me check a bit better. It seems to have changes six months ago, but it was for another feature that later on, I moved it to the `compat/5.9` [here](https://github.com/WordPress/gutenberg/pull/37451).

Great, I'm waiting for the confirmation 👍🏻

**Comment by ntsekouras** [comment]
Hm.. I just checked and this was the last PR updating the patterns there: https://github.com/WordPress/gutenberg/pull/38063, which is for `6.0`. So it should be moved to `6.0`.

**Comment by gziolo** [comment]
I moved all files from `lib/compat/experimental` to `lib/experimental` based on the feedback from @hellofromtonya.

> Hm.. I just checked and this was the last PR updating the patterns there: https://github.com/WordPress/gutenberg/pull/38063, which is for 6.0. So it should be moved to 6.0.

`gutenberg_register_gutenberg_patterns` it's now clustered correctly for inclusion in WP 6.0.

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍 

What's up with the failed e2e tests?

**Comment by gziolo** [comment]
> What's up with the failed e2e tests?

I see the same issue in other open PRs. It fails randomly in `trunk`, too.

**Comment by hellofromtonya** [comment]
>I see the same issue in other open PRs. It fails randomly in trunk, too.

Hmm, good to know it's unrelated to this PR.

**Pull request merged**
