### PR TITLE
[Mobile] Create endpoint to post notices from host apps

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2453

**Related PRs:** 
`gutenberg-mobile` https://github.com/wordpress-mobile/gutenberg-mobile/pull/2613
`WordPress-iOS` https://github.com/wordpress-mobile/WordPress-iOS/pull/14886

## Description
Adds an api that the host apps can use to present the info notice. This is being used as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/2453 to show the page created messages. 
🗒️ The linked PRs cover the iOS version of this feature. @antonis will be working on the Android side in a later PR.

## How has this been tested?
🗒️ Test cases here are taken from https://github.com/wordpress-mobile/WordPress-iOS/pull/14886
<details>
<summary><strong>To disable or enable the development version of Modal Layout Picker</strong></summary>

- Open the app from the build that allows FeatureFlags such as a PR build or a local development build
    - By default, the modal layout picker will be disabled.
    - From the site page:
        - Click on your Gravatar.
        - Click on App Settings.
        - Click on Debug.
        - Toggle "Gutenberg Modal Layout Picker" to enable or disable the picker
            
</details>

When enabled, the Layout Picker should show when creating a new page from My Site and from the Page list.

Start by navigating to the Modal Layout Picker

### Page Created (with content)
1. Select a Layout from the options in Modal Layout Picker
1. Select "Create Page"
**Expect** to see the info notice banner appear under the navigation bar with the text "Page created"
- 🗒️ This is different than the mocks in the linked issue but aligns with the direction that was determined. 

### Blank Page Created
1. Select "Create Blank Page"
**Expect** to see the info notice banner appear under the navigation bar with the text "Blank page created"
- 🗒️ This is different than the mocks in the linked issue but aligns with the direction that was determined. 

### Blog Post Created
1. Create a new blog post
- This should not display the notice bar

### Open existing Page Created
1. Open an existing page (either published or draft)
- This should not display the notice bar

### Disable Modal Layout Picker
1. Create a new page
- This should not display the notice bar

## Screenshots 

| Create Page | Create Blank Page | Clip |
| --- | --- | --- |
|  |  |   |

## Types of changes

Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Tug — COMMENTED** [review]
Code LGTM, I have not product reviewed the whole PR chain.

Could you open an issue in gutenberg mobile to have feature parity for android related to this change?

**Comment by chipsnyder** [comment]
>Could you open an issue in gutenberg mobile to have feature parity for android related to this change?

For the Mobile Layout Picker work, we've just left a single issue open until both the iOS and Android side gets implemented.

**Comment by Tug** [comment]
> For the Mobile Layout Picker work, we've just left a single issue open until both the iOS and Android side gets implemented.

Perfect then!

**Review by geriux — APPROVED** [review]
LGTM! Tested all cases on an iPhone 11 Pro Max and iPad 7.

Nice work @chipsnyder!

**Pull request merged**
