### PR TITLE
[RNMobile]: Refine block settings' separator margin

### LINKED ISSUE #1796: Video block settings: Refine separators on table rows
Separators on Video block settings don't span the width of each row. They should go from the left edge of the left label to the right edge of the right label, 16px margins on each side. Also, there shouldn't be a separator on the last row. I tested on iPhone, but I am assuming this is also the case on Android.

Note: I think this wider inset is the "default" for new rows. We might want to change the default to 16 left and 16 right (I believe it's 56 on iOS and 72 on Android to account for icons, but we aren't using icons as much as non-icon rows).

Screenshot:
image

**To Reproduce**
1. Add video block, upload video
2. Tap on settings cog icon to show block settings sheet
3. See issues described above

// cc @SergioEstevao @etoledom

### PR DESCRIPTION
**Pull request by ceyhun**
## Description

Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1796

Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2008

## How has this been tested?

See the issue for steps to reproduce

## Screenshots 

iOS | Android
-- | --
ios-fixed|android-fixed

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Looks great! Thank you @ceyhun for this improvement 🎉

**Comment by etoledom** [comment]
@ceyhun - Could you please add the link to the `gutenberg-mobile` PR on the description of this PR? Thanks!

**Comment by ceyhun** [comment]
> Could you please add the link to the `gutenberg-mobile` PR on the description of this PR?

@etoledom Sure! Feel free to merge if everything looks good.

**Comment by hypest** [comment]
The PR looks OK and approved so, will admin-merge.

**Pull request merged**
