### PR TITLE
Bug fix "Cannot read property 'end' of undefined" on babel-plugin-makepot #21466

### LINKED ISSUE #21466: babel-plugin-makepot: Cannot read property 'end' of undefined
**Describe the bug**
When creating a build, `babel-plugin-makepot` fails it with this error
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /src/index.js: Cannot read property 'end' of undefined
    at /mnt/d/test/node_modules/@wordpress/babel-plugin-makepot/build/index.js:145:32
    at arrayEach (/mnt/d/test/node_modules/lodash/lodash.js:516:11)
    at forEach (/mnt/d/test/node_modules/lodash/lodash.js:9342:14)
    at getExtractedComment (/mnt/d/test/node_modules/@wordpress/babel-plugin-makepot/build/index.js:144:3)
    at getExtractedComment (/mnt/d/test/node_modules/@wordpress/babel-plugin-makepot/build/index.js:175:12)
    at PluginPass.CallExpression (/mnt/d/test/node_modules/@wordpress/babel-plugin-makepot/build/index.js:290:26)
```

### PR DESCRIPTION
**Pull request by miya0001**
## Description

Bug fix for #21466

## How has this been tested?

* I ran `babel.js ./src -x '.tsx' -x '.ts' --config-file ./.babelrc.i18n` and I saw `*.pot` was generated as expected.
* My environment is Node v12.16.2.

## Screenshots

Nothing

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by torounit** [comment]
@miya0001 

Is `languages/gutenberg.pot` generated by babel ?

**Comment by miya0001** [comment]
I haven't tried it with this project, but I saw it works as expected on my project with following command.

```
node_modules/@babel/cli/bin/babel.js ./src -x '.tsx' -x '.ts' --config-file ./.babelrc.i18n
```

`.babelrc.i18n`:
```
{
  "presets": ["@babel/preset-react", "@babel/preset-typescript"],
  "plugins": [["@wordpress/babel-plugin-makepot",{"output":"src/lang/lang.pot"}]]
}
```

**Comment by torounit** [comment]
@miya0001 
It seems to me that the pot file should not be a commit.

**Comment by miya0001** [comment]
@torounit Removed. 😊

**Review by torounit — APPROVED** [review]

**Pull request merged**
