### PR TITLE
Post editor: Fix the style settings from core/post-content block in theme.json that are not applied in the editor.

### LINKED ISSUE #42267: theme.json: Elements API styles dosn't work in the editor for settings inside core/post-content block
### Description

If you add style settings to theme.json using the elements API inside a core/post-content block the resulting styles are not applied in the editor. 

### Step-by-step reproduction instructions

1. Enable `emptytheme` to discard theme style conflicts.
2. Create a new post with a link, a button, and a heading and publish that post.
3. In the theme's `theme.json` file add these settings:
```
	"styles": {
		"blocks": {
			"core/post-content": {
				"color": {
					"text": "gray"
				},
				"elements": {
					"link": {
						"color": {
							"text": "red"
						}
					},
					"button": {
						"color": {
							"text": "blue",
							"background": "orange"
						},
						"border": {
							"color": "red",
							"width": "5px",
							"style": "solid"
						}
					},
					"h3": {
						"color": {
							"text": "cyan"
						}
					}
				}
			}
		}
	}
```

4. Check the public version of the post you just published. You will see the theme.json styles applied.
5. Check your post in the editor. You won't be able to see the styles defined in `theme.json` applied.

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress 6.0
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?

Fix the style settings for core/post-content block from `theme.json` that are not applied in the editor.
Issue: https://github.com/WordPress/gutenberg/issues/42267

## Why?

If you add style settings to theme.json using the elements API inside a core/post-content block the resulting styles are not applied in the editor.

## How?

Adding a class to apply the styles defined in theme.json for elements inside core/post-content in the editor.

## Testing Instructions

1. Enable `emptytheme` to discard theme style conflicts.
2. Create a new post with a link, a button, and a heading and publish that post.
3. In the theme's `theme.json` file add these settings:
```
	"styles": {
		"blocks": {
			"core/post-content": {
				"color": {
					"text": "gray"
				},
				"elements": {
					"link": {
						"color": {
							"text": "red"
						}
					},
					"button": {
						"color": {
							"text": "blue",
							"background": "orange"
						},
						"border": {
							"color": "red",
							"width": "5px",
							"style": "solid"
						}
					},
					"h3": {
						"color": {
							"text": "cyan"
						}
					}
				}
			}
		}
	}
```

4. Check the public version of the post you just published. You will see the theme.json styles applied.
5. Check your post in the editor. The editor styles should match the frontend view.

## Screenshots or screencast 

Before:
image

After:
image

### CODE REVIEW

**Comment by pbking** [comment]
I can confirm that this fixes the issue.  Looks like the right place to add this necessary class.

Re-running the tests as the failures don't look to be related to the change.

**Review by vcanales — APPROVED** [review]
Checks passing now, this LGTM

**Comment by matiasbenedetto** [comment]
This change can make this [TT3 change](https://github.com/WordPress/twentytwentythree/pull/13) look good in the editor so I'm merging it.

**Comment by jasmussen** [comment]
@matiasbenedetto I'm seeing a regression as a result of this PR. Specifically that the top margin for block gap is missing now:
Screenshot 2022-09-06 at 10 00 50

Which results in this:

Screenshot 2022-09-06 at 09 48 14

Here's what it should look like:

Screenshot 2022-09-06 at 09 58 17

I'm seeing this only in TT3, not TT2 or other themes.

I was initially running a recent but not totally up to date version of TT3, but even pulling the latest has not fixed this for me. Is there a pending TT3 change to go with this, or do you have any insights what might be causing the start margin to not be output?

**Comment by matiasbenedetto** [comment]
Hi @jasmussen thanks for your ping! The change introduced in this PR doesn't seem to be the cause of the problem you are pointing out. As visible in this screenshot, the same problem can be reproduced in the frontend where the class added by this PR was already present before this PR. Apart from that, adding a class to an element should not be a reason to render invalid CSS as is happening now.

image


The root cause seems to be a problem related to the rendering of the default block gap styles. I may have a fix for that I will submit shortly.

**Comment by jasmussen** [comment]
Thank you for following up! I can't be entirely certain when the issue happened, but the way I found this PR was to go to to the commits list and check out the full SHA for various commits until I found an old enough commit that didn't have the problem. Specifically, the commit before this branch was did not have this issue:

Screenshot 2022-09-06 at 19 59 42

If you can reproduce in the editor, you can test using `git checkout d6161001bdb90fdbcafbf3e88b39b38dc3c9117d`

**Comment by matiasbenedetto** [comment]
> Specifically, the commit before this branch was did not have this issue.

Yep, I see what are you saying but this problem you are pointing out is just a symptom of a deeper problem not related to the use of the class added in this PR. I described the problem more extensively here: https://github.com/WordPress/gutenberg/issues/43924 and submitted a potential fix for that:  https://github.com/WordPress/gutenberg/pull/43925

**Comment by jasmussen** [comment]
Ah thank you for the context 🙏

**Pull request merged**
