### PR TITLE
Move CONTRIBUTING.md into .github/ metadata files folder.

### PR DESCRIPTION
**Pull request by tfrommen**
## Description
GitHub reads metadata files such as the issue and pull request templates both from the repository root and a dedicated `.github` folder. The `CONTRIBUTING.md` is also one of these files.

This pull request moves the `CONTRIBUTING.md` file into the `.github` folder to have one file less in the root; GitHub shows it perfectly fine.

## How Has This Been Tested?
It cannot be tested unless merged, but here is just one out of numerous repositories where [it works just fine](https://github.com/inpsyde/MultilingualPress/issues/new) (see the link to the guidelines).

## Types of changes
* Move a metadata file.
* Adapt two explicit links to it.

### CODE REVIEW

**Comment by karmatosed** [comment]
I don't see a need for this to be honest. If people want to go for it, then sure but it feels like moving something just because. We have a build process for the repo, so it's not really a huge issue.

**Comment by tfrommen** [comment]
Reasons for moving the file:

* it is specific to **GitHub**, not the project;
* it doesn't have to be in the root (so moving it where there is a dedicated place for it just makes sense);
* 99 out of 100 times, no one will manually open the file to read it (it is linked from where this makes sense).

Regarding the second reason, also, `CONTRIBUTING.md` files work in the root just because they **had** to be there. Then, GitHub introduced the dedicated folder for these metadata files, and it actually has a higher priority than the root.

**Comment by aduth** [comment]
While GitHub does apply special treatment for this file, I don't necessarily agree that it's GitHub-specific. There are many project-relevant workflow tips included in the document.

**Comment by aduth** [comment]
Admittedly I'd overlooked that we already have the `.github` folder for issue and pull request templates, so there could be a point of consistency here. To my previous comment, I still think the document stands well on its own, so I'd be content with it remaining where it is. All the same, thanks for the pull request @tfrommen and for starting the discussion.

**Comment by tfrommen** [comment]
No harm done, @aduth.
It's just that I'm not here to convice anyone of anything.
You don't like the file to get moved, so I'm fine with that and move on.

**Pull request closed without merging**
