### PR TITLE
Apply hover styles to filter chip while being configured

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Apply hover styles to filter chip while the filter is being configured.

## Why?
Further helps connect the popover with the associated chip. This will become more important as more filters are added.

## How?
Target the `aria-expanded` attribute and style accordingly.

## Testing Instructions
1. Open a data view in the site editor e.g. "Manage all pages"
2. Add filters
3. Notice that while configuring a filter, the associated chip has a different appearance (darker background) to any other chips.

| Before | After |
| --- | --- |
| Screenshot 2024-02-21 at 11 41 09 | Screenshot 2024-02-21 at 11 37 10 |

We might try a stronger visual indicator than the hover state, but this felt a reasonable place to start.

### CODE REVIEW

**Comment by jasmussen** [comment]
I may be missing important details, but the before and after images look identical to me.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!

>I may be missing important details, but the before and after images look identical to me.

It's the subtle changes on the chip(that preserve the hover styles). For example the background color.
Screenshot 2024-02-21 at 5 22 56 PM

**Comment by jameskoster** [comment]
@jasmussen to clarify; currently when a filter configuration popover is open the chip has the default appearance, IE it looks identical to all other chips. On this PR the hover style is retained while the popover is open, to create further visual connection between the chip and the popover. 

The hover style may need to be stronger, but that's probably a detail to finesse in a dedicated PR.

**Comment by jasmussen** [comment]
Oh I see it now, the blue hover color is _slightly_ darker. 

I'm fine with moving forward, but I do think the change is barely perceptible, which usually means we shouldn't do it, or increase the differential a little bit.

**Comment by jameskoster** [comment]
Happy to try a stronger hover / active treatment. This is about as strong as we can get without running into contrast issues:

Screenshot 2024-02-22 at 14 44 30

**Comment by jasmussen** [comment]
Nice.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-wp-6-5-beta-3 branch to get it included in the next release: 3bf151417c

**Pull request merged**
