### PR TITLE
Avoid using inline RichText element for navigation link

### PR DESCRIPTION
**Pull request by talldan**
## Description
This switches the Navigation Link block's label to the default `div` instead of a `span` in the editor.

This change is to avoid a console warning triggered by RichText when an inline element is used:
```
RichText cannot be used with an inline container. Please use a different tagName.
```

This label element is a flex item, so the layout shouldn't be affected. This may also improve some elements of editing the labels that are the reason that warning exists, but it's hard to say what.

## How has this been tested?
1. Add a navigation block with several navigation links
2. Observe the layout is still the same

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by tellthemachines — APPROVED** [review]
Works well, warnings are gone!

**Comment by ellatrix** [comment]
What is it on the front end?

**Comment by ellatrix** [comment]
Also, if it's displayed as a flex item, why does RichText warn? RichText will only warn if it's displayed as an inline element. Tag name does not matter.

**Comment by talldan** [comment]
@ellatrix I'm guessing because there's no explicit `display` for a flex-item, perhaps that's something that the logic for the warning can't pick up on. That logic could check that the parent element is `display: flex;`, but then there's also no issue making this a `<div>` if it's a flex item.

It's an `<a>` in the post, but that can't be matched in the editor as the element isn't a link there.

A `<div>` seems fine to me given these constraints.

**Comment by simison** [comment]
`dangerouslySuppressWarning: true` might come handy some day. 😀

**Pull request merged**
