### PR TITLE
Update Edit icon to be more consistent with other icons

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Tweaks the dimensions of the Edit icon to bring it inline with others in the set.

## Why?
Most icons are designed to fit inside a 16x16px square. This isn't a hard rule, but the way the Edit icon currently breaks out of that square makes it appear unbalanced in isolation, and inconsistent with other icons:

Screenshot 2023-03-31 at 14 54 13

Screenshot 2023-03-31 at 15 13 54

As you can see above it's fully 3px outside the 16px boundaries on the top side, and half a pixel outside on the bottom side. In the Details panel of the site editor this sizing makes things feel _off_:

Screenshot 2023-03-31 at 15 09 25

This PR adjusts it to fit full inside the 16x16px square:

Screenshot 2023-03-31 at 15 02 30

Screenshot 2023-03-31 at 15 09 48

Screenshot 2023-03-31 at 15 13 59

This can serve as a starting point to refine. It may need to be slightly larger.

## Testing Instructions

Compare the Edit icon on this branch with the one in trunk.

### CODE REVIEW

**Comment by richtabor** [comment]
Love it. This has been on my list of "tiny details" for some time. 

I've included a couple more screenshots of where this icon is used. I think this works well.  

CleanShot 2023-03-31 at 12 15 51
CleanShot 2023-03-31 at 12 20 05
CleanShot 2023-03-31 at 13 03 03

**Review by richtabor — APPROVED** [review]
Looks good to me. Curious on @jasmussen's thoughts.

**Comment by jameskoster** [comment]
Thanks for including those screenshots.

The tricky thing about balancing this one is the horizontal line at the bottom of the icon. I think that's always going to make things feel a little off because the eye is drawn the pencil primarily, and the line feels like a secondary element.

Is it worth exploring options without the line? E.g.:

Screenshot 2023-04-03 at 11 32 06

I suppose it depends on whether we feel the line is crucial to the design.

**Review by aristath — APPROVED** [review]

**Comment by richtabor** [comment]
> The tricky thing about balancing this one is the horizontal line at the bottom of the icon. I think that's always going to make things feel a little off because the eye is drawn the pencil primarily, and the line feels like a secondary element.

Sure, as a follow-up probably. 

> I suppose it depends on whether we feel the line is crucial to the design.

I don't think the line is crucial, though the pencil itself may need to stay relative to the existing filled implementation.

**Comment by jameskoster** [comment]
Okay. I'll merge this and update Figma (thanks @javierarce xD).

It's easy to revert is @jasmussen objects.

**Pull request merged**
