### PR TITLE
Changelog Automation: create top-level section for Accessibility PRs.

### PR DESCRIPTION
**Pull request by priethor**
## What?

This PR updates the changelog generation script to create a top-level `Accessibility` section in the changelog for Accessibility PRs.

## Why?
So far, A11y PRs are miscatalogued in subsections, requiring release leads to manually move a11y items to their own top-level section.

## How?
Mapping the existing a11y-related labels to a new `Accessibility` top-level section.

## Testing Instructions
1. Run `npm run other:changelog -- --milestone="Gutenberg 15.4"`
2. Verify that a11y-related PRs appear in an `Accessibility` top-level section.

### CODE REVIEW

**Comment by bph** [comment]
Thank you for the PR @priethor - Not sure if it's necessary, but it might be helpful to also update the test json file. `bin/plugin/commands/test/fixtures/pull-requests.json`

**Comment by priethor** [comment]
Thanks, @bph; I always forget we have unit tests for the changelog, too 🙂 

While fixing the test fixtures, I noticed a bug in the sorting function, which misclassifies some PRs. I'll spin a second PR to fix the sorting before finishing this one.

**Comment by getdave** [comment]
Nice 👍 Seems like a good improvement.

FYI, to run the tests it's:

```
npm run test:unit bin/plugin/commands/test/changelog.js
```

The fixture data doesn't seem to contain many a11y related PRs so I'd recommend updating the data with several PRs that have the labels you've just marked to be under the `Accessibility` group and ensuring they are classified accordingly. 

Also I can't remember how the sorting works, but I think this change will mean that any PR that has these labels will be placed within `Accessibility` over and above any of the other labels. This is because we don't have an explicit "weighting" system and instead rely on the ordering of the `LABEL_TYPE_MAPPING` to determine the priority. To test you could label a PR as both:

- [Type] Security
- [a11y] Color Contrast

...and see which Group it ends up under.

Once happy you can then update the snapshot. 

Happy to review again when you're ready.

**Comment by priethor** [comment]
Closing this PR as I made a mistake rebasing; sorry for the noise!

**Pull request closed without merging**
