### PR TITLE
withSpokenMessages: Change js files to typescript

### PR DESCRIPTION
**Pull request by bhavz-10**
## What?

Converting Javascript files to Typescript

## Why?

As mentioned in https://github.com/WordPress/gutenberg/issues/35744, we want all javascript files to be converted to typescript

## How?

Change to tsx files and run build to make sure it does not throw an error.
There is a change in test added runtime as `any` was implicitly declared as the value type.

### CODE REVIEW

**Review by mirka — COMMENTED** [review]
Looks good, thank you! 🎉 

If you can add a line to the "Internal" section of the [changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md), we're good to merge 👍

**Comment by ciampo** [comment]
Hey @bhavz-10 , do you still have capacity to work on this PR?

Otherwise we're happy to take over and merge the PR for you 🚀

**Comment by bhavz-10** [comment]
Hello @ciampo 

I will work and push the change requested today. 

Thank You

**Comment by bhavz-10** [comment]
Hello @mirka , @ciampo 

I have addressed the change requested.

Thank You :raised_hands:

**Review by mirka — APPROVED** [review]
Looks good! I just went ahead and tweaked the positioning of the changelog so it isn't misplaced in current trunk 👍

Thanks again for your contribution!

**Comment by bhavz-10** [comment]
Hello @mirka 

Thank you for making the tweak.
I have noted that down and I will take care of that.

**Pull request merged**
