### PR TITLE
[Widgets editor] Global inserter open by default

### PR DESCRIPTION
**Pull request by adamziel**
## Description

**Before:**
Zrzut ekranu 2020-08-26 o 16 09 31

**After:**
Zrzut ekranu 2020-08-26 o 16 09 24

Related to @mapk explorations in https://github.com/WordPress/gutenberg/issues/24561.

This is the first stab at this feature. The code is partially copied from the post editor - to avoid repetition we could extract at least one reusable components here: BlockLibrary sidebar. It's not obvious to me where would it live though - ideas appreciated.

## How has this been tested?
1. Go to the experimental widgets management screen
1. Confirm the global inserter is open by default

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mtias** [comment]
I think in order to have it open by default we should not allow it to be closed — it should become a region that is always accessible.

**Comment by youknowriad** [comment]
In terms of a11y, I think we need to bring the "popover" behavior of the "inserter" to edit-widgets screen. 
Unfortunately, if we do so, it means we won't be able to make the inserter open by default.

**Comment by mtias** [comment]
What I mean is having it open all the time in the same way the current widgets screen has widgets available on the page always visible.

**Comment by mapk** [comment]
>What I mean is having it open all the time in the same way the current widgets screen has widgets available on the page always visible. And remove the [+] toggle entirely.

I'm hesitant on this, @mtias. Users will still be able to access the Settings sidebar for blocks too. Keeping the Inserter panel always open takes up a lot of space. Here's a quick mockup to visually convey what I'm talking about. And this is on a fairly wide screen (1278 x 800).

Design notes
- Added a "Widgets" heading in topbar.
- Removed the `+` Inserter

panels

**Comment by mtias** [comment]
I don't think that's much of a problem but might be worth trying both. If it's not always open we should not have an "open by default" since it would also absorb focus and we don't want that on loading the page.

**Comment by mapk** [comment]
I think we're fine showing the Inserter by default. It mimics the behavior of the original widgets screen. I've put this flow together here: https://github.com/WordPress/gutenberg/issues/24561#issuecomment-681167207

It appears to work fine. The Inserter can collapse if needed to save space when opening the Inspector, or simply by clicking the `+` button in the topbar.

**Comment by mtias** [comment]
@mapk there are different implications here since the inserter has popover / modal behaviours. Meaning focus is transferred and contained, which cannot happen on first load of the page as it'd be confusing.

**Comment by adamziel** [comment]
Could we just not capture focus on the first load?

**Comment by youknowriad** [comment]
I don't think so because as soon as you insert a single widget/block, it will close itself which is confusing IMO.

**Comment by mtias** [comment]
As @youknowriad mentions, the interaction model of the inserter as a toggle doesn't lend itself to open by default. The only way I can think of to make it open by default is to remove the toggle behaviour entirely.

**Comment by youknowriad** [comment]
Potentially it could be a setting "inserter always visible or not" in an "options" modal if there's a big need for it.

**Comment by adamziel** [comment]
I updated this PR to:

1. Keep the inserter open by default.
1. Remove autoFocus on this specific screen only while ensuring the inserter won't close after a block is added.
1. Make sure that either inserter or sidebar are visible, but not both at the same time.

I didn't update it to use `<PopoverWrapper>` like it does in post editor, otherwise it works exactly the same. Does using it feel right?

**Comment by mapk** [comment]
Thanks, @adamziel !

>Make sure that either inserter or sidebar are visible, but not both at the same time.

This interaction should work as it does in the Post Editor now. Opening the Inspector should not close the Inserter unless there's not enough space to show both. I believe there are settings established there that can be adopted here.

**Post Editor**

sidebars


>Does using it feel right?

It started out right to me. I can tab "skip to content" to jump into the topbar. BUT I can't seem to keyboard my way into the Inserter blocks. If I hit `Enter` it closes the Inserter, and if I click any arrows or tabs, it jumps me to the next topbar icon.

**Comment by adamziel** [comment]
> This interaction should work as it does in the Post Editor now. Opening the Inspector should not close the Inserter unless there's not enough space to show both.

That makes sense, thank you! Fortunately it sounds like an easy change.

> It started out right to me. I can tab "skip to content" to jump into the topbar. BUT I can't seem to keyboard my way into the Inserter blocks. If I hit Enter it closes the Inserter, and if I click any arrows or tabs, it jumps me to the next topbar icon.

Good notes, thank you! I wonder if that's part of what @youknowriad meant by the popover behavior.

**Comment by adamziel** [comment]
I talked to @mapk, we compared this interaction to the post editor and the keyboard interaction is actually not trivial to solve with the inserter that doesn't act like a popover - what key should even transfer the focus to the inserter? Enter is for opening/closing. Tab is for navigating the toolbar. Down arrow wouldn't be consistent with other components. Ultimately that's a UX problem to solve, not a bug in the code. I'll defer to @mapk on what should we explore next here.

**Comment by mapk** [comment]
Because of the complexity, I'd rather we hold off creating a new Inserter interaction that differs from the post editor and move to not include it by default. As your other PR is improving, let's just get the Inserter to mimic the Inserter in the post editor. This way rather than going down a rabbit hole on the Inserter, we can focus on completing the Widget Editor.

**Comment by youknowriad** [comment]
This is how it used to work on the post editor screen but unfortunately, that's not acceptable as it's an a11y bug. See https://github.com/WordPress/gutenberg/pull/24429 and https://github.com/WordPress/gutenberg/issues/22858 for more details.

**Comment by afercia** [comment]
> Because of the complexity, I'd rather we hold off creating a new Inserter interaction that differs from the post editor and move to not include it by default. As your other PR is improving, let's just get the Inserter to mimic the Inserter in the post editor. 

I'd definitely agree the inserter interaction should be consistent everywhere. Our primary goal should be providing users with a predictable, expected, interaction across the WordPress UI. 

Also, keeping the inserter open by default _and_ removing the toggle entirely would force keyboard users to tab through the whole inserter to get to the content each time the use this page. This would make keyboard navigation inefficient. It would also be an assumption that the users flow is always "add" while they might just want to "edit" or "delete" an existing widget (and thus there's no need for the inserter at all).

> Potentially it could be a setting "inserter always visible or not" in an "options" modal if there's a big need for it.

Interesting idea. What we're constantly learning with Gutenberg is that users have different needs or even just different preferences. Maybe it's worth reconsidering a bit the WordPress mantra "decisions not options" because a complex user interface needs to cover many different needs. To some extent, options can help. If in the future the need for some users to keep the inserter open will be clear, I wouldn't be opposed to a setting. It could also be a button within the inserter itself, something like "make the inserter sticky" (always open). Such a setting might be useful also in the block editor, for example with very large screens.

**Comment by adamziel** [comment]
It seems like we're pivoting - let's close this PR.

**Pull request closed without merging**
