### PR TITLE
Fix typo in Autocomplete component README.md

### PR DESCRIPTION
**Pull request by barryceelen**

### CODE REVIEW

**Review by shail-mehta — COMMENTED** [review]
Good Catch👍

**Review by t-hamano — COMMENTED** [review]
@barryceelen Thanks for the PR. How about changing the following line as well?

https://github.com/WordPress/gutenberg/blob/4e21760ac3a6306d9221099b52d9c4bc52133ed9/packages/components/src/autocomplete/types.ts#L203

**Review by Mamaduka — APPROVED** [review]
Thanks for catching this, @barryceelen!

**Comment by barryceelen** [comment]
> How about changing the following line as well?

@t-hamano fixed!

**Review by t-hamano — APPROVED** [review]
LGTM!

**Pull request merged**
