### PR TITLE
Build tooling: Remove support for IE11

### PR DESCRIPTION
**Pull request by desrosj**
## Description
For context, see:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/

### CODE REVIEW

**Comment by talldan** [comment]
> Note: This change will only affect WordPress and it’s built-in features. For your site visitors, any plugin or theme you may be using, which was made with support for IE11 in mind, should still look and feel as if nothing changed.

I'm just wondering whether this statement includes the default front-end block styles that Gutenberg/Core provides?

If a theme is using those styles this change may affect a site's appearance for visitors.

**Comment by youknowriad** [comment]
Apparently the issues here seem to be related to webpack not understanding some ESnext syntax (since now it's not being transpiled). By looking on the internet, it seems to be something that is generally fixed by upgrading webpack. Any news about webpack 5 upgrade cc @gziolo @jsnajdr 

Also, if you have any idea about how we could solve this without upgrade :)

**Comment by gziolo** [comment]
It looks like webpack doesn't understand `??` operator.

**Comment by gziolo** [comment]
> Any news about webpack 5 upgrade

The challenge is that we will have to upgrade webpack from v4 to v5 in both Gutenberg and WordPress core because they both use the same code from `build-module`.

**Comment by gziolo** [comment]
I'm testing whether enforcing transpilation of `??` could help by passing the flag to `@babel/preset-env` configuration:
```js
include: [ 'proposal-nullish-coalescing-operator' ],
```

**Comment by jsnajdr** [comment]
The issue is that webpack uses the `acorn` parser, which is very conservative about supporting syntax that's not 100% stable and standardized.

I'm afraid we'll need to transpile optional chaining until the webpack 5 upgrade is done. @scinos Do you have any interesting knowledge to share here? I think you have direct on-hands experience from solving exactly the same issue in Calypso.

**Comment by gziolo** [comment]
> I'm testing whether enforcing transpilation of `??` could help by passing the flag to `@babel/preset-env` configuration:
> 
> ```js
> include: [ 'proposal-nullish-coalescing-operator' ],
> ```

It looks like this is the way to go. There is one failing unit test but it's expected since Babel generates now a bit different output. We only need to regenerate the snapshot produced.

**Comment by gziolo** [comment]
Another issue to resolve, but an expected one:
https://github.com/WordPress/gutenberg/pull/31110/checks?check_run_id=2418311313

Screen Shot 2021-04-23 at 11 33 40

There are two ways we can approach it:
1. We remove the check as we don't care anymore.
2. We enforce IE11 for the code but only in `build` folders for individual packages and validate there. The question is what `build` really is in this world. Maye we can stop publishing it from now on. If we set Node 12 as the minimal version, it should work with Node out of the box with import statements. We can start using `exports` in `package.json` as detailed in https://nodejs.org/api/packages.html#packages_package_entry_points.

**Comment by gziolo** [comment]
E2e tests also fail, so there are most likely more features missing in Chromium that's used there. We have fairly outdated version of Chromium, so we can try to upgrade `puppeteer-core` to the latest version v9.0.0 from v5.5.0 and see if that helps.

**Comment by youknowriad** [comment]
@gziolo we should remove that check.

**Comment by youknowriad** [comment]
@gziolo I went ahead and opened this PR to upgrade puppeteer to see what impacts it has on its own https://github.com/WordPress/gutenberg/pull/31138

**Comment by youknowriad** [comment]
There are 3 or 4 failing tests with the puppeteer upgrade (without the browserlist change), I could use some help debugging these.

**Comment by desrosj** [comment]
Thanks everyone for working through this!

> I'm just wondering whether this statement includes the default front-end block styles that Gutenberg/Core provides?
> 
> If a theme is using those styles this change may affect a site's appearance for visitors.

@talldan When @Clorith reviewed the post, he did flag this. It is a good question that we need to discuss. I think there are a few paths we could take here:

- Over-communicate this through dev notes and Make Core posts so that site owners can make the adjustments they need to if supporting IE11 is important to their user base.
- Create a plugin that includes IE11 styles for the blocks in Core as of 5.7. New blocks will not receive styles.
- Continue bundling front end styles only for IE11.

I think proceeding with the first option for now is best, and we can explore the others if there is enough of a need that presents itself. But if anyone has other ideas or thoughts, please do share!

**Comment by desrosj** [comment]
I merged `trunk` into the branch and pushed to get the workflows to run. For some reason, they did not run correctly after the previous push and were stuck.

**Comment by youknowriad** [comment]
Puppeteer is now updated and uses a recent chromium, let's see how this goes :)

**Comment by gziolo** [comment]
There are still test failures:

> ["ReferenceError: Cannot access 'v' before initialization
> 3161
>     at Object.axis (http://localhost:8889/wp-content/plugins/gutenberg/build/components/index.js?ver=e3b9da069e5f62ac7f1c03c61682c261:661:20741)
> 3162
>     at http://localhost:8889/wp-content/plugins/gutenberg/build/components/index.js?ver=e3b9da069e5f62ac7f1c03c61682c261:661:21511

There is no such thing as `Object.axis` in the codebase so this is some sort of bug that gets introduced during Babel transpilation. It needs further debugging.

**Comment by youknowriad** [comment]
I've fixed the issue, it was actually a valid bug that was "fixed"/"hidden" by the transpiration of let/const

**Comment by youknowriad** [comment]
It seems like we're good to do, e2e tests are passing.

**Comment by youknowriad** [comment]
Should we document this change somewhere? The changelog of the presets package maybe?

**Review by youknowriad — APPROVED** [review]

**Review by aristath — APPROVED** [review]
Confirmed it all looks good here :+1:

**Comment by gziolo** [comment]
> Should we document this change somewhere? The changelog of the presets package maybe?

In most of the packages we have the following note:

> _This package assumes that your code will run in an **ES2015+** environment. If you're using an environment that has limited or no support for ES2015+ such as lower versions of IE then using [core-js](https://github.com/zloirock/core-js) or [@babel/polyfill](https://babeljs.io/docs/en/next/babel-polyfill) will add support for these methods. Learn more about it in [Babel docs](https://babeljs.io/docs/en/next/caveats)._

It's no longer valid with the changes introduced. I don't think we should consider it a blocker, but we should discuss a path moving forward separately. We still have nearly two weeks before all these changes get published to npm. I only mentioned it earlier, but we need also to think if we want to keep both `build-module` and `build`, because we could as well set the minimum version required of Node to v12 and it should all work with a single build target `build-module`. Unless we want to keep `build` that contains ES5 code as before this PR.

**Review by gziolo — APPROVED** [review]

**Comment by desrosj** [comment]
Thanks everyone!

**Comment by desrosj** [comment]
For cross referencing, here are some relevant Trac tickets:
- Ticket to discuss when Core should stop loading IE11 polyfills by default: [Trac-53078](https://core.trac.wordpress.org/ticket/53078).
- Ticket dropping IE11 support in Core SVN: [Trac-53077](https://core.trac.wordpress.org/ticket/53077).

**Comment by gziolo** [comment]
I opened a follow-up https://github.com/WordPress/gutenberg/pull/31270 that documents the changes applied for the consumers of WordPress packages.

**Pull request merged**
