### PR TITLE
[RNMobile] Replace Slider

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

I added within `gutenberg-mobile` new library `react-native-slider` which is going to replace `Slider` from `react-native` which will be deprecated soon and what's more have a bug on ios ~13.

Ref to gb-mobile:https://github.com/wordpress-mobile/gutenberg-mobile/pull/1620
Ref to WordPress-Android:https://github.com/wordpress-mobile/WordPress-Android/pull/10871
Ref to WordPress-iOS:https://github.com/wordpress-mobile/WordPress-iOS/pull/13019

## How has this been tested?

I was testing it in WordPress-Android, WordPress-iOS and also within a playground.

1. Add `Spacer` block on mobile
2. Play with `Slider`
  * I suggest you also to set small range eg. minValue=0, maxValue=20 in [RangeCell](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/mobile/bottom-sheet/range-cell.native.js#L181-L182) to check if Slider is not jumping

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by pinarol** [comment]
> I suggest you also to set small range eg. minValue=0, maxValue=20 in RangeCell to check if Slider is not jumping

Actually this is a pretty important test case since that jumpiness on iOS 13.x is the main reason we wanted to make this change.

**Comment by pinarol** [comment]
Could you also add the gif that demonstrate the odd behavior @lukewalczak ? It is not clear for reviewers what we are fixing.

**Comment by lukewalczak** [comment]
Sure! Weird behavior:
odd

**Review by etoledom — APPROVED** [review]
Approved **iOS** side via https://github.com/wordpress-mobile/gutenberg-mobile/pull/1620#pullrequestreview-326711590

**Review by marecar3 — APPROVED** [review]
Tested on Android and it's working good!
LGTM!

**Pull request merged**
