### PR TITLE
[RNMobile] Fix pasting text on Post Title

### LINKED ISSUE #1099: Paste into Title may result in empty text
Noticed that pasting a simple 1-line text on Android may result in empty title.

Steps to repro:
- Start the demo app
- Tap on the Title block
- Paste some simple text (better 1 line text)
- Notice that the text is not added to the title
Video: https://cloudup.com/cnMErcD-Ese

Tested on current develop `909ddae3b707a569f78286996239461cbf97fa4d` on Android 7.1

### PR DESCRIPTION
**Pull request by etoledom**
fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1099

This PR fixes an issue where pasting text on post title was behaving as pressing Enter key when the title field is empty.
Pasting send an event to `onReplace`, that was wired directly to `onEnterPress`.

This PR fixes the issue by adding an `onEnter` prop to `RichText`, adding the ability to handle custom onEnter handling when needed.

This PR does **NOT** fix pasting multi-paragraph text. I investigated multi-paragraph pasting and it will take some effort and discussion. I think the best would be to not use RichText on PostTitle, but let's have this discussion on another ticket.

`gutenberg-mobile` side PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1123

To test:
- Run the demo app.
- Select the Post Title field.
- Delete its current content.
- Paste some text inside the empty Post Title.
- Check that paste works as expected.
- Press Enter.
- Check that it creates a new block and it gets focused as expected.

### CODE REVIEW

**Review by SergioEstevao — APPROVED** [review]
Good catch!

**Comment by etoledom** [comment]
Thank you!

**Comment by designsimply** [comment]
<blockquote>I think the best would be to not use RichText on PostTitle, but let's have this discussion on another ticket.</blockquote>

Eventually, the title should become a block (in case that impacts your thinking here).

https://github.com/WordPress/gutenberg/issues/11553

**Comment by designsimply** [comment]
Tested all sorts of pasting of single-line content into the title field in the mobile block editor using WPAndroid alpha-177 (12.8 alpha) on Pixel 3 Android 9 and it worked as expected. Also checked that I could undo changes and undo worked well (which I found helpful!).

**Pull request merged**
