### PR TITLE
Fix overwriting of published post meta when previewing footnote changes

### PR DESCRIPTION
**Pull request by adamsilverstein**
Fixes bug discovered in https://github.com/WordPress/gutenberg/pull/52988

### CODE REVIEW

**Review by Mamaduka — COMMENTED** [review]
@adamsilverstein, just to clarify: this is a different bug discovered while working on #52988 and can be tested/merged separately + recommended to be backported into a minor release. 

Are the above statements correct?

P.S. Can you also provide quick testing instructions?

**Comment by jorgefilipecosta** [comment]
I think we can merge this PR, update_post_meta is just an update_metadata call, with additional logic to in case of revisions update the original post instead of the revision.
```
	$the_post = wp_is_post_revision( $post_id );
	if ( $the_post ) {
		$post_id = $the_post;
	}
```
Here it seems we want to avoid that logic to have the possibility of having revisions for the footnones.

**Review by jorgefilipecosta — APPROVED** [review]
The change looks good to me 👍

**Comment by Mamaduka** [comment]
If the e2e fails again, it might require rebasing due to core changes. See #54452.

**Comment by adamsilverstein** [comment]
Rebased against trunk

**Pull request merged**
