### PR TITLE
Show shadow tool by default under global styles

### LINKED ISSUE #61952: Show shadow tool by default under global styles
### Description

In Global Styles, all tools should show up by default in tools panels, including the shadow tool. 
Enable it by default in global styles, but not in block styles.

### Step-by-step reproduction instructions

* Navigate to global styles -> block -> styles
* Observe that under Border & Shadow, only border tools are shown by default.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #61952

## What?
This PR shows the shadow tool by default under global styles.

image

## Why?

I think available tools should be displayed by default in the global styles, like the Typography panel and color panel.

## How?
Changed the value of the `shadow` property from false to true in the `DEFAULT_CONTROLS` variable. This should not affect the block sidebar shadow panel.

## Testing Instructions

- Go to the Site Editor > Global Styles > Blocks > Button
- The shadow panel should be visible by default.
- Open the block sidebar for the Button block. Shadow panels should not be visible by default.
- (Additional testing) In the Button block, make the following changes to display the shadow panel by default:
  ```diff
  diff --git a/packages/block-library/src/button/block.json b/packages/block-library/src/button/block.json
  index 740f3e50f8..8d378344c3 100644
  --- a/packages/block-library/src/button/block.json
  +++ b/packages/block-library/src/button/block.json
  @@ -99,7 +99,10 @@
                  },
                  "reusable": false,
                  "shadow": {
  -                       "__experimentalSkipSerialization": true
  +                       "__experimentalSkipSerialization": true,
  +                       "__experimentalDefaultControls": {
  +                               "shadow": true
  +                       }
                  },
                  "spacing": {
                          "__experimentalSkipSerialization": true,
  ```

- In the Button block's sidebar, the shadow panel should be visible by default.

### CODE REVIEW

**Comment by vcanales** [comment]
There was [reasoning behind not displaying it by default](https://github.com/WordPress/gutenberg/pull/58466#issuecomment-1927867656); I don't think that has changed since then.

**Review by vcanales — APPROVED** [review]
LGTM

I had left a comment about the reasoning behind hiding the Shadows panel from view in the Block Styles panel, but I hadn't realized that this PR was specifically about Global Styles, so it was not relevant to the proposed changes.

**Review by madhusudhand — APPROVED** [review]
LGTM! Thank you.

**Comment by t-hamano** [comment]
Thanks for the review!

**Pull request merged**
