### PR TITLE
Cover: Customizing Alignment with Reakit Composite

### PR DESCRIPTION
**Pull request by ItsJonQ**
This PR attempts to implement the [Composite](https://next.reakit.io/docs/composite/) component from Reakit into the new `AlignmentMatrixControl`.

For the initial integration attempt, it seemed to work as expected in Storybook (yay).

However, there appears to be issues within Gutenberg.

### (Not) Playing Nicely with Toolbar

When expanding the Position dropdown in the Toolbar, the `AlignmentMatrixControl` appears to have issues rendering (see below):

Screen Capture on 2020-04-01 at 16-07-02

It flashes and closes immediately. I'm not too sure why.

Seeing `unstable_virtual: false` seems to allow it to render okay. Although, the interactions and keyboard navigation seems to be off.

CC'ing @diegohaz for expertise 😊 

Thoughts/feedback welcome! We can change anything in this branch / draft PR

### CODE REVIEW

**Comment by diegohaz** [comment]
How can I test it? Is there a way to check it with the toolbar on Storybook?

**Comment by diegohaz** [comment]
I cleaned up the code a little bit and fixed some issues I found, including the one you mentioned about it closing right away.

Apr-01-2020 22-26-14

Styles need some work and probably we will want to close the popover when the user clicks on an option.

I'm not sure what was causing the problem, but I think it has something to do with this `queueBlurCheck` on the `with-focus-outside` high order component:
https://github.com/WordPress/gutenberg/blob/963998e09e9cd9a1ac35e824c6312d9c93779305/packages/components/src/higher-order/with-focus-outside/index.js#L67-L90

When `unstable_virtual` is activated, [items receive focus and return it to the composite container in the same tick](https://github.com/reakit/reakit/blob/49db6c007ea82fddf959448328b5f5d572defa40/packages/reakit/src/Composite/CompositeItem.ts#L166-L177) so, visually, it looks like the container never lost focus. This is so we can provide the same API for both `aria-activedescendant` and `roving tabindex` methods. That is, you can do `<CompositeItem onFocus={...} />` regardless of the approach you're using.

This sequence of blurring the container, focusing the item, blurring the item and focusing the container might be conflicting with the `queueBlurCheck` method or some other thing in that module.

One option is to `stopPropagation` on the container's `onBlur` event when `event.relatedTarget` is some of the composite items:
```jsx
<Composite
	onBlur={ ( event ) => {
		if (
			composite.items.some(
				( item ) => item.ref.current === event.relatedTarget
			)
		) {
			event.stopPropagation();
		}
	} }
/>
```

But, it's safer to just use roving tabindex instead as this is a valid approach for grids.

**Comment by ItsJonQ** [comment]
@diegohaz Wowow! Thank you so much! Your explanation makes sense. Beautiful refactors :D.
I can fix up the styles, no worries!

Could not have done this without you 🤘

**Comment by ItsJonQ** [comment]
@diegohaz Haiii!! I made some refactors and pushed it up!

One thing I'm noticing (that I'm not sure how to resolve, yet). I believe it touches upon the focus/blur logic you pointed out.

This has to do with keyboard navigation when `AlignmentMatrixControl` renders within the `Toolbar`.

---

If we use `<Dropdown />` (like what you suggested)...

Keyboard navigation (up, down, left, right), works as expected.

But... Toolbar navigation is funky. When the AlignmentMatrix icon is focused, pressing `DOWN` on the keyboard doesn't open the dropdown.

---

If we use `<Toolbar />` (like what I had previously)...

Keyboard navigation  (up, down, left, right), **does not work** as expected. The movements are weird...

However, Toolbar navigation works.

---

🤔

**Comment by diegohaz** [comment]
[Collapsed `Toolbar`/`ToolbarGroup`](https://github.com/WordPress/gutenberg/blob/4b8d1f88a3c5868462c152e09a8a5f2dbce9f6c7/packages/components/src/toolbar-group/toolbar-group-collapsed.js#L19-L23) uses [`DropdownMenu`](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/dropdown-menu/index.js), which uses [NavigableMenu](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/navigable-container/menu.js), which implements its own keyboard navigation expecting a vertical one-dimensional list. So I guess using it is not an option?

I don't know if there's a `Dropdown` component that reproduces the same behaviors as `DropdownMenu` without `NavigableMenu`. I just took the block switcher dropdown as a reference. It implements the arrow down key here: https://github.com/WordPress/gutenberg/blob/4b8d1f88a3c5868462c152e09a8a5f2dbce9f6c7/packages/block-editor/src/components/block-switcher/index.js#L106-L112

**Comment by ItsJonQ** [comment]
@diegohaz Thank you so much! That clue helped me a lot.

I was able to fix it up. I had to swap `ToolbarButton` with a regular `Button` to make it work.
Going through this exercise has helped me understand how... tricky... it is to work with all of these various parts (`Toolbar`, `Dropdown`, `DropdownMenu`, etc...).

Let's work on making these components seamless and better, together! 💪

**Comment by diegohaz** [comment]
Yep! I’ll eventually need to update it to ToolbarButton later as part of the toolbar work I’m doing. 😅

**Comment by ItsJonQ** [comment]
@diegohaz You're the best <3

**Comment by gziolo** [comment]
Nice team work 😍🔥

**Pull request merged**
