### PR TITLE
Menu Items: Lower the specificity of the fallback background color 

### PR DESCRIPTION
**Pull request by yashitamittal11**
## What?

This PR is lowering the specificity of the fallback background color for the menu items, so the color selected in the block settings is honored.

## Why?

This PR solves the background color issue in the submenu items in the navigation block. 
The issue exists on the Varia and its child themes.

## How?

When using the Navigation block with the Varia and its child themes, the background color selected from the block settings is not honored. It is because the specificity of the fallback menu background color is higher than the CSS specificity of the selected block color.

This PR lowers the specificity of the fallback background color for the menu items to honor the user-selected settings.

## Testing Instructions

1. Activate Hever or any other Varia child theme on a site.
2. Open a post or page and add the Navigation block.
3. Add menu items and submenu items.
4. Choose a background color(primary, secondary, foreground) for the navigation block.
5. View the page. The background color should be visible on clocking the submenu.  

## Screenshots or screencast 
| Before |

menu navigation-issue

| After |
Menu navigation - fixed

### CODE REVIEW

**Comment by tellthemachines** [comment]
Thanks for your contribution @yashitamittal11 ! Are you able to reproduce this on a default theme such as Twenty Twenty Two or Twenty Twenty One? I notice the issue you linked to is not from a [WordPress repo](https://github.com/WordPress).

If it can't be reproduced in any of the default themes, we can still consider a request for lowering the specificity of a CSS rule (this is an area we are continuously trying to improve!) but it would be better in that case to open an issue so we can discuss this further, rather than directly submitting a PR.

I'd also add that this particular part of the code - background colors for the Navigation block - has already caused us much pain in the past, so any change we make will need extensive testing first 😅

**Comment by yashitamittal11** [comment]
I checked this issue on the default theme Twenty Twenty Two and Twenty Twenty One, and the navigation block colors are working fine on those themes. 

Should I open a new issue in the [Gutenberg repo](https://github.com/WordPress/gutenberg/issues) for further discussion?

**Comment by carolinan** [comment]
Hi!
This issue needs specific testing. With the Emptytheme, I am getting different results depending on if the submenu is in a page list or is a submenu link item. For page list, the submenu background color option does not work at all in the editor, where the submenu background is always white (not transparent).

**Comment by carolinan** [comment]
"Emptytheme" which has no theme styles for the navigation block that can conflict, can be found in the Gutenberg repo, in the test folder.

**Comment by tellthemachines** [comment]
> Should I open a new issue in the [Gutenberg repo](https://github.com/WordPress/gutenberg/issues) for further discussion?

That would be ideal, thanks @yashitamittal11 !

**Comment by yashitamittal11** [comment]
Thanks, everyone! I have created a new issue here: https://github.com/WordPress/gutenberg/issues/42256
I am not able to add labels or reviewers to the issue. Maybe I don't have permission.
Can someone please help me add the labels? 🙏

**Comment by andreszs** [comment]
This is a theme-specific design flaw, not a general Wordpress issue IMO.

**Comment by scruffian** [comment]
This seems to be theme specific.

**Pull request closed without merging**
