### PR TITLE
Changelog tool: update Automated Testing label

### PR DESCRIPTION
**Pull request by vcanales**
## What?
Updates the label type mapping to match the one being used currently so that PRs labeled `[Type] Automated Testing` are correctly categorized under Tools

## Testing Instructions
- Run `npm run other:changelog -- --milestone="Gutenberg 16.6"` — PRs such as [this one](https://github.com/WordPress/gutenberg/pull/53856) should be correctly categorized under Tools.

### CODE REVIEW

**Review by alexstine — APPROVED** [review]
Works as expected.

**Comment by alexstine** [comment]
Working on getting the last few tests passing. Failures are unrelated at this point.

**Comment by vcanales** [comment]
Yeah, indeed. 

This is the failure that is persisting: https://github.com/WordPress/gutenberg/actions/runs/6043729250/job/16402381845?pr=54070#step:14:36 — Not sure what to make of it, but it doesn't seem to be happening in trunk. I've enabled auto-merge in case the tests decide to pass; otherwise, I'll merge with a note.

**Comment by priethor** [comment]
Thanks for catching this, @vcanales! My bad!

Context in this [other PR](https://github.com/WordPress/gutenberg/pull/53116)

**Pull request merged**
