### PR TITLE
Upgrade React to v18.3

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
PR updates React to 18.3.1. in preparation for the React 19 release.

See the full changelog - https://github.com/facebook/react/blob/main/CHANGELOG.md#1831-april-26-2024.

## Testing Instructions
Smoke test the editors. CI checks should be green.

### CODE REVIEW

**Comment by Mamaduka** [comment]
It looks like `user` events now need to be wrapped in `act`. Could be issue with RTL, investigating now.

The following changes allow `withSelect` unit tests to pass.

```diff
diff --git packages/data/src/components/with-select/test/index.js packages/data/src/components/with-select/test/index.js
index fe798354cba..03ddbec67ba 100644
--- packages/data/src/components/with-select/test/index.js
+++ packages/data/src/components/with-select/test/index.js
@@ -110,7 +110,8 @@ describe( 'withSelect', () => {
 		// Simulate a click on the button.
 		const button = screen.getByRole( 'button' );
 
-		await user.click( button );
+		// await user.click( button );
+		await act( async () => user.click( button ) );
 
 		expect( button ).toHaveTextContent( '1' );
 		// 1. Initial mount

```

**Comment by youknowriad** [comment]
@Mamaduka that change in the test makes sense. I think we were supposed to do in previous versions as well. Maybe it's more consistent now.

**Comment by Mamaduka** [comment]
There's no warning when a test uses `fireEvent` directly, which, based on the docs, [is wrapped in `act`](https://testing-library.com/docs/preact-testing-library/api/#fireevent).

The issue seems to affect the [user-event](https://github.com/testing-library/user-event) library, which I thought was a wrapper around `fireEvent`.

**Update:** Fixed the issue by downgrading RTL to v14.3; this version made it compatible with the new `act` export. It seems there's a dependency conflict; let's wait for the `use-event` update before we upgrade these libraries.

**Comment by Mamaduka** [comment]
I noticed that some of the [React Native code still uses](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+defaultProps+path%3A*.native.js&type=code) the now deprecated `Component.defaultProps`. I've fixed one case that was failing the mobile unit tests. Should I update others in this PR or handle them in a quick follow-up?

cc @WordPress/native-mobile

**Comment by derekblank** [comment]
> Should I update others in this PR or handle them in a quick follow-up?

@Mamaduka Yes, if you want to handle replacing the remaining `Component.defaultProps` in this PR, that's great. If not, we can also help address them in a follow-up PR. 

If addressing in this PR, for function components we can continue to add the `defaultProps` to the function signature, like you already have done in the [focal-point-picker tooltip](https://github.com/WordPress/gutenberg/pull/61202/files#diff-54824617da4ee663124619ea34fe5301dc1d7d57d74ec7bbd1f2b4c748396d5a). For the class components, we should be good to just replace `Component.defaultProps { ... } ` with `static defaultProps { ... }`.  

Opening it up to the rest of the native-mobile team if they have further thoughts/feedback. (We are not planning to cut a Gutenberg Mobile release until May 9, so we should have plenty of time to test.)

**Comment by Mamaduka** [comment]
Sounds good, @derekblank!

FYI, the `defaultProps` is only deprecated for [function components](https://github.com/facebook/react/pull/25699).

Let's handle the `.native.js` update in a quick follow-up, as it doesn't seem to be a blocker. Warning shouldn't break mobile apps and are probably less visible there.

**Comment by derekblank** [comment]
> FYI, the `defaultProps` is only deprecated for [function components](https://github.com/facebook/react/pull/25699).

TIL. 👍 

> Let's handle the .native.js update in a quick follow-up, as it doesn't seem to be a blocker. 

Sounds good. I created an issue to keep track: https://github.com/wordpress-mobile/gutenberg-mobile/issues/6840

**Comment by Mamaduka** [comment]
Can I get an ✅ to land this upgrade?

**Review by tyxla — APPROVED** [review]
With the native ones [tracked and addressed separately](https://github.com/wordpress-mobile/gutenberg-mobile/issues/6840), this looks good! 

I took a look at the release notes and didn't spot any concerning bits that we need to account for. Also, smoke testing went well. Let's go for it!

Thanks for working on it @Mamaduka 🚀

**Comment by youknowriad** [comment]
I think this one needs a manual backport to WP Core.

**Comment by Mamaduka** [comment]
@youknowriad, do you remember when we last did the manual update in core? I assume I can base the new branch on that.

**Comment by youknowriad** [comment]
@Mamaduka I don't, It may have been done at the same time as the package update but I believe it involves updating the package.json and potentially some version numbers in script-loader.php and nothing more.

**Comment by Mamaduka** [comment]
@youknowriad, I found the [commit](https://github.com/WordPress/wordpress-develop/commit/07fc9b2d7449314ee658d764ce162e99cef6783b) for React 18.2 and will use it as a template.

**Pull request merged**
