### PR TITLE
Simplify template reset language

### PR DESCRIPTION
**Pull request by jameskoster**
Screenshot 2024-03-27 at 17 57 56

This has come up a couple of times – notably in https://github.com/WordPress/gutenberg/issues/46859 – and with the long runway to 6.6 now feels like a potentially good time to try adjusting the language around clearing template customizations.

## What?
* All instances of label "Clear customizations" now simply read: "Reset".
* Help text (e.g. "Use the template as supplied by the theme.") is removed.
* All instances of copy "Are you sure you want to clear these customizations?" now reads: "Reset and clear all customizations?".
* "Clear" `Button` labels in `ConfirmDialog`s now read: "Reset" 

## Why?
* "Clear customiations" is a long-winded way of saying "Reset", which is a reasonably familiar concept. The `ConfirmDialog` should eliminate any potential confusion.
* Align with the Command Palette where this action is already labelled "Reset".
* Improve consistency across other actions e.g. "Reset styles" (see #46859 for more).

## Testing Instructions
Reset a theme template from any of the locations in which it is possible to do so:

* Actions menu in data views
* Bulk actions menu in data views
* Document inspector while editing a template

Observe the updated language.

### CODE REVIEW

**Comment by SaxonF** [comment]
I like "Reset" more than "clear customizations" . Could maybe extend to "Reset to default" if needed.

**Comment by jameskoster** [comment]
Not a strong opinion, but now feels like the moment to be bold, and potentially row back based on feedback if needed. We could add the 'to default' language to the confirmdialog? 

> Reset **to default** and clear all customizations?

**Comment by annezazu** [comment]
😭 Thank you for working on this! This inconsistency has been frustrating and confusing, particularly for destructive actions. Here's some feedback for you:

**Considering adding a heading to the modal**

Should we add a "Be careful" style heading similar to this approach with removing query loop blocks?  https://github.com/WordPress/gutenberg/pull/58138  I'm not sold on this but, again, am thinking about consistency across the experience. 

**Resetting styles has no modal**
Quick note that resetting styles with this PR doesn't pop up this confirmation modal (not sure if that's intentional). It just resets it.

**Update the snackbar notice to say reset**

For resetting from Data Views for templates, I also think we should match the snackbar notice to say "reset" rather than "reverted":
Screenshot 2024-03-28 at 10 42 50 AM

**Consider making reset red**

Another minor note but should "reset" be red, similar to "trash" on Posts > All Posts:

Screenshot 2024-03-28 at 10 44 11 AM

Screenshot 2024-03-28 at 10 44 26 AM

**Comment by jameskoster** [comment]
> Considering adding a heading to the modal

I believe maintaining consistency in the flow is most important. Minor differences in modal composition, such as the presence or absence of a title, seem acceptable to me. A "Be careful" warning seems excessive in this particular scenario. Additionally, a generic "Reset template" heading might be redundant, considering the accompanying copy directly below.

> Resetting styles has no modal

This PR focusses on resetting templates, we can follow-up to address styles 👍 

> Update the snackbar notice to say reset

Good catch! I'll push a fix.

> Consider making reset red

I quite like using color to highlight 'danger zone' actions – generally those that cannot be undone. So in this case I would consider making the 'Reset' button in the modal red.

That said, we may need to revisit how we apply destructive colors at the component level before committing to this change. Colors can have different meanings in different cultures, and red doesn't always represent 'Danger'. It's also a detail to apply holistically to all such flows.

**Comment by annezazu** [comment]
Sounds good across the board. Excited about this!

**Comment by ntsekouras** [comment]
Is the copy agreed upon for this one, so we can code review?

**Comment by jasmussen** [comment]
Yep, I'd echo a simple "Reset" for the button to echo Jay's comments.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks!

**Comment by jameskoster** [comment]
Thanks Nik.

**Review by richtabor — COMMENTED** [review]
LGTM. 

The only addition I think worth considering is to use "Reset template" rather than "Reset" alone. 

That's the case for Global Styles, which adds just enough context:
 
CleanShot 2024-04-02 at 09 33 59

The same for the command palette: 

CleanShot 2024-04-02 at 09 34 29

**Comment by jameskoster** [comment]
I'm not sure we need to be quite so explicit here as there is plenty of context, plus the confirmation modal (which is not present for styles).

**Pull request merged**
