### PR TITLE
Fix/ie11 interface bugs

### LINKED ISSUE #26932: IE11: block editor interface goes beyond window boundaries
**Describe the bug**
1. Block editor is wider than window, so some interface elements (like gear button and elipsis button) become unreachable.
2. Breadcrumbs do not show up
3. Max width rule is not applied to the content

**To reproduce**
Steps to reproduce the behavior ( Block editor is wider than window ):
1. Open any page
2. Add full-width block (e.g. pullquote) with long text (long enough to cause line wrap).

Steps to reproduce the behavior ( Breadcrumbs do not show up ):
Always.

Steps to reproduce the behavior ( Max width rule is not applied to the content ):
Always with Twenty Twenty One theme

**Expected behavior**
1. Block editor should not be wider than window.
2. Breadcrumbs should show up in the footer
3. The content should not be wider than max width 

**Screenshots**
Screenshot_5

**Editor version (please complete the following information):**
- WordPress version: 5.6-beta3-49557 (dev version)
- Gutenberg plugin 9.3.0 (dev version)
- Twenty Twenty One theme

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IE 11

### PR DESCRIPTION
**Pull request by ambienthack**
## Description
Fixes #26932 IE11 bugs:
- first commit: made breadcrumbs show up in footer 
- second commit: made block editor fit into browser window

## How has this been tested?
Tested on Windows 10: IE11, Chrome 86, Opera (latest), Firefox (latest)
IOS 14: Chrome, Safari

## Screenshots 
Screenshot_6

## Types of changes
Footer CSS (.interface-interface-skeleton__footer):
1. Made footer absolutely positioned istead if fixed positioned. Beacuse it is inside fixed positioned container, this shouldn't break anything. 
2. Added _left:0_ to the footer because in non-IE browsers the footer was positioned correctly in horizontal direction during static positioning stage. IE static positioning stage doesn't bring the footer to _left:0_.

Editor CSS (.interface-interface-skeleton__editor):
max-width: 100% => width: 100%;
max-width doesn't work with IE flexbox in some cases.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for the PR! And thank you for tackling this specific issue.

The PR touches very sensitive CSS code that carries the interface. So furthermore I appreciate that your PR is very small with just two small code changes. The thing that's tricky here is that your changes affect every browser, not just IE11, so it's important to test this not just in IE11 but in all browsers. (We have at times overridden IE11 hacks with `@supports (position: sticky) {}`.

And in my testing, this PR appears to not have any adverse effects at all. I did test thoroughly in Chrome on Mac, I haven't yet had an opportunity to test in IE11, my virtual machine is acting up. 

So in early review, 👍 👍! But it would be nice if someone else could test in IE11 before this lands. Thanks again.

**Comment by ambienthack** [comment]
Made another commit to improve a little bit.
The original code logic (before PR) was to let .interface-interface-skeleton__editor grow ap to 100%:
```scss
flex-grow: 1;
max-width: 100%; //doesn't work for nested flexbox in IE
```

New logic is to set .interface-interface-skeleton__editor width to 100% and let it shrink if needed:
```scss
flex: 0 1 100%;
```

This is more expressive and removes potientially harmful _flex-grow: 1;_

Shrinking may happen if drawer is visible. BTW what is drawer? Haven't found it in the UI. Only the sidebar & the secondary sidebar.

**Comment by jasmussen** [comment]
Cool work. Especially with structural CSS, it's good to keep the changes tiny.

> BTW what is drawer? Haven't found it in the UI. Only the sidebar & the secondary sidebar.

This is the drawer:

Screenshot 2020-11-13 at 11 31 59

It's a new UI element that only is used in the "Site Editor". The Site Editor menu item becomes available if you activate a block-based theme. There are some here: https://github.com/WordPress/theme-experiments

**Review by tellthemachines — APPROVED** [review]
Thanks for spotting and fixing this issue @ambienthack!

Tested on IE11 and both the post and the site editor are looking fine ✅ 

This should be backported to 5.6 as the issue is reproducible on 5.6 Beta 4 as well.

**Comment by ambienthack** [comment]
Thank you guys! Looks like I'm gonna become a contributor with my three lines of code. Time to celebrate 🎉

**Comment by sirreal** [comment]
It looks like this introduced a regression: https://github.com/WordPress/gutenberg/issues/27622

Any help finding an IE11 compatible solution would be greatly appreciated 🙇‍♂️

**Comment by jasmussen** [comment]
One thing we can look at as a hotfix of sorts, is to go back to the old CSS but wrapped in a `supports`. I.e. something like

```
// new code from this PR

@supports (position: sticky) {
	// old code from before this PR
}
```

This is usually the best way to handle the discrepancies between IE11 and modern browsers. Implicit in that is also an acceptance, potentially, of infinitely wide blocks in IE, but perhaps that can serve as a temporary fix until a better one lands?

**Comment by ambienthack** [comment]
I think max-width:100% can be added back without a problem for ie11. I removed it in favour of   ```scss
flex: 0 1 100%;
```
because it seemed enough to limit the width to 100%

**Comment by jasmussen** [comment]
Cool let's maybe try that. I can test in IE11 on my other machine here. Want to make a PR? Otherwise I can, and feel free to CC me on anything, happy to help.

**Comment by ambienthack** [comment]
Yes, i'll make a PR

**Pull request merged**
