### PR TITLE
Update full screen modal dimensions, and pattern grids

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
This PR does a couple of things.

* Updates the dimensions of 'full screen' modals to match the recent update https://github.com/WordPress/gutenberg/pull/49859#issuecomment-1511761362. This ensures consistency across the app.
* Applies the full screen property to modals that can make use of it:
  * Choosing a template part
  * Choosing a query pattern
  * Choosing a full-page pattern
  * Choosing a template pattern
  * Preferences modal
* Updates the pattern grids in the now-larger modals.

## Why?
1. We currently have a mixture of 'larger' modal sizes, notably in the use cases above. It'd be nice for these to exhibit more consistent behavior.
2. Pattern selection interfaces can really make use of the 'full screen' modal experience rather than cramming multiple previews into a narrow modal.

## How?
* Apply `isFullScreen` prop to several `Modal` instances.
* Adjust `isFullScreen` css.
* Adjust some grid styles for patterns.

## Testing Instructions
Open any full screen modal:

* Pattern Directory
* Choose Query pattern
* Choose template part
* Choose pattern template
* Choose full-page pattern
* Preferences modal

### Pattern directory
| Before | After |
| --- | --- |
| Screenshot 2023-04-18 at 14 04 36 | Screenshot 2023-04-18 at 14 04 03 |

Note the equal spacing around the entire modal.

### Choose a template part
| Before | After |
| --- | --- |
| Screenshot 2023-04-18 at 13 49 57 | Screenshot 2023-04-18 at 13 49 05 |

### Choose a query pattern
| Before | After |
| --- | --- |
| Screenshot 2023-04-18 at 13 46 47 | Screenshot 2023-04-18 at 13 46 59 |

### Preferences
| Before | After |
| --- | --- |
| Screenshot 2023-04-18 at 14 16 53 | Screenshot 2023-04-18 at 14 16 25 |

### CODE REVIEW

**Comment by jasmussen** [comment]
The new radius coming well into its own here 👍 👍

Thanks for the detailed before/after's.

I'm with you all the way until the preferences modal. Indeed I think that's an opportunity to discuss defaults here. In general, _modal_ is definitely meant to grab your attention, so I personally think it's okay to go really huge by default.

But I also think that it's useful to override that modal width/height on a per-modal basis. The commandbar comes to mind as one example, it should definitely not be fullscreen. The preferences dialog as well. For me, that dialog is mostly about ensuring legibility, so I would keep the existing width/height combo there, or at least something like it.

**Comment by jameskoster** [comment]
Yes I thought that one might be contentious. I'll revert.

**Review by apeatling — APPROVED** [review]
✅ Confirmed all of these changes work correctly. The extra size is definitely appreciated in the pattern and template selection modals since you're selecting visual elements. I agree in preferences where it's text/settings it seems less important.

**Comment by SaxonF** [comment]
Lovely work @jameskoster !

**Pull request merged**
