### PR TITLE
Global Syles: Apply fallback background color to typography elements

### LINKED ISSUE #59338: Style icon for link, heading and caption needs improvement when Maelstrom style is applied from editor
### Description

When the Maelstrom style is applied there seems an issue with bg style for Link, heading and caption. However, when I inspect it using DevTools, I see it has a white colour to it and hence they are not visible. It should be made in such a way that it does not seem that they are missed.

### Step-by-step reproduction instructions

1. Go to **Themes > Editor**
2. Click on any **heading or paragraph**
3. Now, open a **style**
4. Click on **Browse Style**
5. Select **Maelstrom style**
6. Now, go back
7. Click on **Typography**
8. Observe that style for the link, heading and caption

### Screenshots, screen recording, code snippet

| Screenscap | Screenshot|
|----- |----|
| https://github.com/WordPress/gutenberg/assets/15173772/36d55565-00cf-4987-bb7a-25cae4b41517 | Links, heading and caption (1) |

### Environment info

- WordPress: 6.4.3
- PHP: 8.0.30-dev
- Server: PHP.wasm
- Database: WP_SQLite_Translator (Server: 5.5 / Client: 3.40.1)
- Browser: Chrome 121.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Four 1.0
- MU Plugins:
       - 0-playground.php
       - 0-sqlite.php
      - WordPress WXZ Exporter 0.1
- Plugins:
     - Create Block Theme 1.13.8
    - Debug Bar 1.1.4
    - Health Check & Troubleshooting 1.7.0
    - Test Reports 1.1.0
    - User Switching 1.7.3
    - WordPress Importer Git loader 0.8.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #59338

## What?

This PR applies a fallback background color to icons and previews in the Global Styles Elements panel.

## Why?

The current logic uses the background color of each element. For example, if it is a link element, `elements.link.color.background` is referenced. However, if the text is close to white and does not have an explicit background color, it will be difficult to see the text.

## How?

Use `color.background` as a fallback background color in case no explicit background color is defined for that element. This behavior should actually be close to what you see visually in the frontend or editor canvas.

## Testing Instructions

- Open the Site Editor and access Global Styles > Typography.
- All elements should now have a background color applied to them.
- When you click on any element, the background color should also be applied in the preview.
- Repeat the above steps for several styles.

### Icon

| Style | Before | After |
|--------|--------|--------|
| Default | image| image |
| Maelstrom | image | image |
| Onyx | image | image | 

### Preview

| Style | Before | After |
|--------|--------|--------|
| Default | image| image |
| Maelstrom | image | image |
| Onyx | image | image |

### CODE REVIEW

**Review by huzaifaalmesbah — COMMENTED** [review]
I have tested this PR, and it appears to be satisfactory to me.

**Comment by t-hamano** [comment]
Added this PR to the WP6.5 project board. Because the issue this PR solves has already been added to the project board.

**Comment by youknowriad** [comment]
Given that RC1 is today, I'm removing this from 6.5 as non essential.

**Review by youknowriad — APPROVED** [review]
LTGM 👍

**Pull request merged**
