### PR TITLE
Improve consistency of block names

### PR DESCRIPTION
**Pull request by nylen**
There are a few blocks that have sub-optimal names due to our server-side parsing not handling dashes properly:

- `core/latestposts` should be `core/latest-posts`
- `core/embedcollegehumor` (and other embed blocks) should be `core/embed-collegehumor` or `core-embed/collegehumor`.  Per Slack discussion with @mtias, and because there are enough of these blocks that it makes sense for them to live in their own "namespace", I've gone with the latter.

With the new PHP parser in #1152 we can resolve this ambiguity, with plenty of test cases, and set good standards for other block implementers.

### CODE REVIEW

**Comment by nylen** [comment]
#882 is the related issue I was looking for earlier.

It's probably easiest to review this PR without the fixture file changes and without #1152 in the mix, as follows:

```sh
git diff 2f8f07b...114512c blocks/library/ blocks/test/full-content.js
```

**Comment by notnownikki** [comment]
As far as the renaming goes this is :+1: from me, this makes much more sense than the smooshed together names.

I'm not familiar yet with how pegjs works, so I wont mark this as approved, just because I don't yet know enough to properly review that part.

**Comment by nylen** [comment]
That's fine, that's a separate PR anyway (#1152).

**Comment by nylen** [comment]
Merging to get this breaking change in sooner rather than later.

**Pull request merged**
