### PR TITLE
Patterns: Add renaming, duplication, and deletion options

### LINKED ISSUE #51919: Custom Patterns: Allow renaming and duplication within the Site Editor
## What problem does this address?

In the Library menu of the site editor, you can create custom patterns.

create-pattern

However, in the site editor, you can only delete a pattern you have created.

delete

To rename, the following operation is required.

- Click "Manage all custom patterns"
- Edit a post(pattern)
- Change the post title(pattern name)
- Save the post(pattern)
- Back to the Site Editor

## What is your proposed solution?
It would be nice to be able to rename and even duplicate pattern names in the site editor, as in the navigation menu.

navigation

rename

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/51919

Related:
- https://github.com/WordPress/gutenberg/issues/52107

**NOTE: This PR still needs some polishing and updates to ensure better a11y**

## What?

This PR allows for:
- renaming or deleting custom user patterns & custom template parts
- duplicating all patterns or template parts (custom, theme, or core)

### Known Issues / Follow Ups

- The stacking of snackbar notices is being worked on in a separate PR
- The flow when creating a pattern that returns via the "manage all" list view pages could be improved in a follow-up
- We likely need some keyboard shortcuts similar to the delete option for the renaming and duplication
    - If the patterns list is changed to a simple list the need for the keyboard event handling/shortcuts might be alleviated

> However, I'd reconsider the listbox / options implementation as it introduces unnecessary complex interaction for screen reader users. This i sjust a list of objects, visually presented in a grid. I'd recommend to use a standard list.

See: https://github.com/WordPress/gutenberg/issues/52253

## Why?

This improves management options for patterns and template parts and avoids convoluted flows to affect relatively minor changes such as renaming.

## How?

- Adds new options to each pattern's dropdown menu
- All patterns or template parts, have a "Duplicate" option now
- Custom user-created patterns or template parts have both "Rename" and "Delete" options

## Testing Instructions

1. Create some synced and unsynced patterns via the Site Editor > Patterns page
2. Test renaming your created patterns
3. Try out duplicating your patterns
4. Ensure you can delete your patterns
5. Navigate to one of the theme pattern categories e.g. Featured for TT3 theme
6. Confirm that you only have the "duplicate" option for a theme pattern and it works as expected
7. Navigate to one of the template part categories and find a core template part e.g. Header or Footer
8. Duplicate the core template part
9. Check that you can now also rename and delete this newly created custom template part

### Testing Instructions for Keyboard

TBA

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/60436221/41cdc2c8-f683-4db7-a19f-3298832fd4a1

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
@kevin940726 you might have some insight around the keyboard delete functionality. Do you think we need to replicate something similar for the rename and duplicate options, or should we explore the change suggested in https://github.com/WordPress/gutenberg/issues/52253 to switch the listbox/options approach with a simple list?

**Comment by aaronrobertshaw** [comment]
The addition of further options to the pattern dropdowns was raised in https://github.com/WordPress/gutenberg/issues/52009. 

If I'm understanding that discussion correctly, the [solution proposed](https://github.com/WordPress/gutenberg/issues/52009#issuecomment-1610703751) there is to replace the "delete" shortcut with a shortcut that opens the actions menu.

Perhaps we could implement that as a follow-up to this PR, in the interests of making the deadline for the next beta?

**Comment by jameskoster** [comment]
This is a very exciting PR that significantly enhances the pattern management experience, nice work so far!

Renaming seems to work well ✅

### Deleting

* Theme template parts that have been customised should have a "Clear customizations" action instead of "Delete". The reason being that they can be customized by the user, but will always exist in the file system so cannot be truly deleted in the UI.
* In the confirmation dialog let's make the primary button label "Delete" to match other deletion flows:

Screenshot 2023-07-04 at 12 10 39

### Duplicating

* Asking the user to supply a name immediately adds some friction to the flow. Especially for template parts where you also need to specify the area. If it's not a lot of work, I think it would be interesting to try an iteration where the name is automatically set so the duplication feels more instantaneous. We could add a `(copy)` suffix to the new pattern. For template parts the area can match the source.
* Being sent immediately to edit the duplicated pattern was a bit unexpected for me. Could we try remaining in the management view?
* Duplicating theme patterns is powerful because it effectively makes them editable, but it's a bit confusing that they get recategorized as 'My patterns'. I understand there's a technical limitation that makes this a requirement for now, but in the short term I wonder if the 'Duplicate' action for theme patterns should be more explicit: 'Copy to My patterns'? That way there's no confusion about where the new pattern will end up.

**Comment by aaronrobertshaw** [comment]
Thank you for the great feedback @jameskoster 👍 

I've pushed a range of changes that include:

- Labelling the delete action for customized template parts that have theme files with "Clear customization"
- Updating the "delete" prompt when it is clearing customizations
- Removing the rename action for customized template parts with theme files
- Fixing keyboard deletion for customized template parts
- Directly creating patterns or template parts so we don't get the modals or navigate away to the edit mode
- Updating the duplicate label for theme patterns to "Copy to My patterns"

Here's the current state of the PR now:

https://github.com/WordPress/gutenberg/assets/60436221/c952fdf4-c667-4fd7-a66b-400aa90ce90a

A few things to note:
1. If a user has lots of patterns, staying on the same page might make it hard to initially spot the new pattern.
2. If a user repeatedly duplicates the same pattern we end up with multiple patterns with the `${title} (Copy)` title.
3. If we’re happy with the general direction of this PR, we’ll need to update the aria descriptions for the keyboard delete shortcuts to reflect the “clear customizations” change rather than delete.
4. The flash when the patterns list is updating needs improvement if we continue with directly creating patterns and template parts.
5. We don’t have any sorting options at this stage for the patterns list so I believe it might be in order of last updated. This could change as we implement pagination.
6. Do we need to make the delete confirmation for template parts to avoid the mention of patterns e.g. “Are you sure you want to delete this template part?” instead of “Are you sure you want to delete this pattern?”

If you're happy with the new direction, I can polish up this PR tomorrow and aim to get it merged this week.

**Comment by jameskoster** [comment]
> Labelling the delete action for customized template parts that have theme files with "Clear customization"
> Updating the "delete" prompt when it is clearing customizations
> Removing the rename action for customized template parts with theme files
> Updating the duplicate label for theme patterns to "Copy to My patterns"

✅ 🎉

> Fixing keyboard deletion for customized template parts
How does this work? I don't seem to be able to focus the ellipsis using the keyboard.

> Directly creating patterns or template parts so we don't get the modals or navigate away to the edit mode
Nice, this generally feels much better to me. 

When duplicating a theme pattern, being redirected to "My patterns" is perhaps a little heavy-handed. Could try displaying a confirmation Snackbar saying something like "'Pattern name (copy)' added to my patterns", potentially with an action to "View my patterns"?

A confirmation snackbar would probably make sense for all duplications. It could include an "Edit pattern" action.

> If a user repeatedly duplicates the same pattern we end up with multiple patterns with the ${title} (Copy) title.

Duplicate names seems like something to avoid generally. But I noticed you can reuse existing names when creating a pattern manually too, so perhaps it's something to address separately?

> Do we need to make the delete confirmation for template parts to avoid the mention of patterns

Yes probably. Perhaps instead of "Are you sure you want to delete this pattern/template part" we could say "Are you sure you want to delete 'pattern name'?"

> If you're happy with the new direction, I can polish up this PR tomorrow and aim to get it merged this week.

It needs more reviewers, but I'm pretty happy with the overall direction here.

**Comment by aaronrobertshaw** [comment]
Appreciate the continued feedback @jameskoster 🙇 

I've made the suggested tweaks, which include:

- Snackbar success notices when duplicating patterns or template parts
- A "View my pattern" action in the success notice when duplicating theme patterns
- An "Edit pattern" action in the success notice when duplicating non-theme patterns
- "Edit template part" action to success notices when duplicating template parts
- Updated delete confirmation which now references the entity name rather than its type (pattern/template part)
- Pattern deletion success notice now references pattern name so it matches delete confirmation prompt and template part deletion success message


> Duplicate names seems like something to avoid generally. But I noticed you can reuse existing names when creating a pattern manually too, so perhaps it's something to address separately?

These patterns leverage the `wp_block` CPT and to date, there haven't been any restrictions on the uniqueness of the name, I assume given they rely on a dedicated id field. 

Given existing reusable blocks can potentially have duplicate names, retroactively enforcing uniqueness might lead to some issues. We might be able to enforce this constraint on new patterns however we'd also have to update the REST API as well. 

I'm not sure we can address this for 6.3, unfortunately. I'll create an issue and add it to the [Patterns tracking issue](https://github.com/WordPress/gutenberg/issues/51948).

Let me know what you think of the current state. I'll get some extra reviews on this tomorrow.

**Comment by jameskoster** [comment]
Thanks for the updates, I think this is working pretty well now. Just a couple of minor points:

> An "Edit pattern" action in the success notice when duplicating non-theme patterns
> "Edit template part" action to success notices when duplicating template parts

If you'd like to simplify, the action could probably just be "Edit".

Where names appear in Snackbars I think they should be wrapped in double quotes instead of single.

Snackbar position seems to be broken when there are many patterns:


https://github.com/WordPress/gutenberg/assets/846565/1bb49d4d-2e9d-4e57-b961-47a581ada6a0

**Comment by aaronrobertshaw** [comment]
> If you'd like to simplify, the action could probably just be "Edit".
>
> Where names appear in Snackbars I think they should be wrapped in double quotes instead of single.

Done (https://github.com/WordPress/gutenberg/pull/52270/commits/efd762b83eabc7deac87ba3275f3dc5d509e08ad). Thank you 👍 

> Snackbar position seems to be broken when there are many patterns:

This appears to be an issue with how the patterns get rendered asynchronously, changing the dimensions of the page content container. 

As it's an existing issue, not introduced by this PR, I'd like to follow this up separately. I've also discussed it with @glendaviesnz who might look into it if I can't.

**Comment by glendaviesnz** [comment]
@aaronrobertshaw The only issue I have noticed so far is that duplicating an unsynced pattern creates a synced pattern - do you see that?

**Comment by aaronrobertshaw** [comment]
> The only issue I have noticed so far is that duplicating an unsynced pattern creates a synced pattern - do you see that?

Good catch 👍 

I missed updating the [sync_status property](https://github.com/WordPress/gutenberg/pull/52270/files#diff-13661740a1ed20ad8d3f651bdf0ca353641c65760f18aaef738bb41d80a7ba55R121-R123) after rebasing. I'll push a fix shortly.

**Review by glendaviesnz — APPROVED** [review]
Tested well for me:

✅  Could create some synced and unsynced patterns via the Site Editor > Patterns page
✅  Could rename my patterns
✅  Could  duplicate my patterns
✅  Could delete mypatterns
✅  Only hadthe "duplicate" option for a theme pattern and it worked as expected
✅  Could duplicate a core template part
✅  Could rename and delete this newly created custom template part

**Comment by aaronrobertshaw** [comment]
Thanks for the quick fixes @glendaviesnz, I've just pushed a minor tweak to improve readability. Once the tests are green I'll get this merged so we can iterate further on the a11y side.

**Comment by afercia** [comment]
> We likely need some keyboard shortcuts similar to the delete option for the renaming and duplication
> If the patterns list is changed to a simple list the need for the keyboard event handling/shortcuts might be alleviated

Thank you for keeping keyboard operability into consideration. Yes, I'd say this is one more reason to reconsider the grit/roving tabindex implementation and just use a simple list instead.
Showing in the UI a control that can't be focused and operated with a keyboard is less than ideal for sighted keyboard users. Not to mention the amount of keyboard shortcuts would become a bit too large.

**Comment by aaronrobertshaw** [comment]
> Yes, I'd say this is one more reason to reconsider the grit/roving tabindex implementation and just use a simple list instead.

Thanks for the sanity check @afercia 👍 

@glendaviesnz is currently working on those accessibility improvements to the patterns list in https://github.com/WordPress/gutenberg/pull/52357 and we discussed landing this PR so https://github.com/WordPress/gutenberg/pull/52357 could be rebased and take into account the full scope of interactions intended for 6.3.

Unfortunately, I'll be unavailable next week, but if you do foresee any problems please create issues and Glen, among others, will be able to take a look. There's also a [Patterns tracking issue](https://github.com/WordPress/gutenberg/issues/51948) that they could be added to, to raise awareness.

**Comment by afercia** [comment]
Thanks for pointing me at https://github.com/WordPress/gutenberg/pull/52357, will follow up there. 🌴

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/beta-4-second-round branch to get it included in the next release: 3e5bc99820

**Pull request merged**
