### PR TITLE
Update Block Styles Preview Pane Title

### LINKED ISSUE #40463: Block Styles preview name: Character limit is not working correctly for some languages.
### Description

Block Styles preview name is not working properly with character limit depending on language.
Please see the following screenshots.

style

https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/text#limit

### Step-by-step reproduction instructions

1. Refer to the following code to add a block style.

```PHP

function twenty_twenty_two_register_block_styles() {
	// Hello,Hello,…
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-1',
			'label' => esc_html__( 'Hello,Hello,Hello', 'twentytwentyone' ),
		)
	);

	// Hola,Hola,Ho…
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-2',
			'label' => esc_html__( 'Hola,Hola,Hola', 'twentytwentyone' ),
		)
	);

	// こんにちは,こんにちは
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-3',
			'label' => esc_html__( 'こんにちは,こんにちは', 'twentytwentyone' ),
		)
	);

	// 你好,你好,你好,你好
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-4',
			'label' => esc_html__( '你好,你好,你好,你好', 'twentytwentyone' ),
		)
	);
}
add_action( 'init', 'twenty_twenty_two_register_block_styles' );
```

2. Go to the block editor and place the image block.

3. Open the side panel and look at the style preview.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 5.9.4
- Gutenberg 13.0.0
- Twenty Twenty-Two

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by shimotmk**
Resolves #40463

## What?

Block Styles preview title character limit is removed to improve the look and feel of the title.

### Before
block-styles-title-before

### After
block-styles-title-after

## Testing Instructions

1. Refer to the following code to add a block style.
```PHP
function twenty_twenty_two_register_block_styles() {
	// Hello,Hello,…
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-1',
			'label' => esc_html__( 'Hello,Hello,Hello', 'twentytwentytwo' ),
		)
	);

	// Hola,Hola,Ho…
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-2',
			'label' => esc_html__( 'Hola,Hola,Hola', 'twentytwentytwo' ),
		)
	);

	// こんにちは,こんにちは
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-3',
			'label' => esc_html__( 'こんにちは,こんにちは', 'twentytwentytwo' ),
		)
	);

	// 你好,你好,你好,你好
	register_block_style(
		'core/image',
		array(
			'name'  => 'twentytwentytwo-image-4',
			'label' => esc_html__( '你好,你好,你好,你好', 'twentytwentytwo' ),
		)
	);
}
add_action( 'init', 'twenty_twenty_two_register_block_styles' );
```
2. Go to the block editor and place the image block.

3. Open the side panel and look at the style preview.

### CODE REVIEW

**Comment by shaunandrews** [comment]
With long style names and text wrapping its very easy to end up with an unbalanced list of buttons, putting emphasis (via size) on some styles randomly. Here's a few examples:

image

image

This also leads to a rather tall list of of buttons, pushing down other (arguably more important) controls within the Inspector sidebar.

The existing design encourages the use of short style names, and truncating longer labels to keep a consistent interface.

**Comment by shimotmk** [comment]
I made an adjustment to change the width of the button when the style is odd.
block-style


First of all, we found that [this issue](40463) had a bug in the character limit of the title of the block style depending on the language in which it is displayed.

At that time, we thought it was not appropriate to limit the number of characters in the title before adjusting the character limit.
This is because there was no example of a block or block pattern that also had a character limit on the title.
https://github.com/WordPress/gutenberg/issues/40463#issuecomment-1116981075

**Comment by ramonjd** [comment]
I understand the reason why we want to wrap titles to accommodate CJK character widths, but removing the limit will impact all locales. 

Also, what if the title wraps over three lines?

I'm not convinced the solution lies in adjusting the design, but rather, finding a way to deal with truncation of wide character centrally (in the truncate component) thereby spreading the benefit to all places in the app and to as many locales as we can.

**Comment by shimotmk** [comment]
> Also, what if the title wraps over three lines?

I do not know what is better for me.
 
I thought the title should not be restricted, but if there is another way, I am willing to close this pull request.

**Comment by shaunandrews** [comment]
> I'm not convinced the solution lies in adjusting the design, but rather, finding a way to deal with truncation of wide character centrally (in the truncate component) thereby spreading the benefit to all places in the app and to as many locales as we can.

Agreed with this. We can definitely consider updating the design — maybe using a single column display when necessary to accommodate long titles. But we should first resolve the underlying issue with the truncation to make the existing design work as intended.

**Comment by ramonjd** [comment]
Would it hurt to add an `overflow: hidden` to the button as a band aid measure?

**Comment by ndiego** [comment]
Simply allowing text wrapping seems like the easiest and most direct way to address this issue. While multiline descriptions do not look great, this is a choice made by theme authors and extenders. Truncating descriptions punishes people who want more verbose descriptions and also those that are using CJK characters.

**Comment by ramonjd** [comment]
> Truncating descriptions punishes people who want more verbose descriptions and also those that are using CJK characters.

That's a fair point. Truncation tries to "solve" a difficult problem (or rather sweeps it under the mat) of variable lengths across locales. Would be keen to see some alternative designs. A dropdown? There I said it 😄

**Comment by mtias** [comment]
The consistent vertical weight is an important aspect of the usability of this design. I'm in favor of trying the truncation with ellipsis first. Style names are not meant to be complicated or verbose given they are fairly opaque.

**Comment by ramonjd** [comment]
> The consistent vertical weight is an important aspect of the usability of this design. I'm in favor of trying the truncation with ellipsis first. Style names are not meant to be complicated or verbose given they are fairly opaque

Thanks @mtias !

Would using CSS `text-overflow: ellipsis;` be acceptable for now to make the UI "behave" until we can decide a neat approach via the `<Text />` component?



<details>

<summary>Example diff</summary>

```diff
diff --git a/packages/block-editor/src/components/block-styles/index.js b/packages/block-editor/src/components/block-styles/index.js
index 0a86433096..5ac0bec2cc 100644
--- a/packages/block-editor/src/components/block-styles/index.js
+++ b/packages/block-editor/src/components/block-styles/index.js
@@ -115,15 +115,7 @@ function BlockStyles( {
 							onClick={ () => onSelectStylePreview( style ) }
 							aria-current={ activeStyle.name === style.name }
 						>
-							<Text
-								as="span"
-								limit={ 12 }
-								ellipsizeMode="tail"
-								className="block-editor-block-styles__item-text"
-								truncate
-							>
-								{ buttonText }
-							</Text>
+							{ buttonText }
 						</Button>
 					);
 				} ) }
diff --git a/packages/block-editor/src/components/block-styles/style.scss b/packages/block-editor/src/components/block-styles/style.scss
index bed73bfedf..e4840b03cd 100644
--- a/packages/block-editor/src/components/block-styles/style.scss
+++ b/packages/block-editor/src/components/block-styles/style.scss
@@ -42,6 +42,9 @@
 		box-shadow: inset 0 0 0 1px $gray-400;
 		display: inline-block;
 		width: calc(50% - #{$grid-unit-05});
+		text-overflow: ellipsis;
+		overflow: hidden;
+		white-space: nowrap;
 
 		&:focus,
 		&:hover {
@@ -53,10 +56,6 @@
 		&.is-active:hover {
 			background-color: $gray-800;
 			box-shadow: none;
-		}
-
-		&.is-active .block-editor-block-styles__item-text,
-		&.is-active:hover .block-editor-block-styles__item-text {
 			color: $white;
 		}
```

</details>

**Comment by mtias** [comment]
What is the current problem with `Text`?

**Comment by ramonjd** [comment]
> What is the current problem with Text?

Ah, sorry. I forgot to add context. There was discussion about this over at the [issue](https://github.com/WordPress/gutenberg/issues/40463#issuecomment-1116900354), which boils down to the following:

Chinese, Korean and Japanese (CJK) characters are about twice the width of latin characters. 

When specifying `limit={ 12 }` for CJK via `<Text />`, we'll get 12 characters, but the combined width of those characters will be about the same as 24 latin characters. 

I proposed a string width checker in the Text/Truncate component, but I haven't tested it and am not yet convinced it's a fabulous idea.

**Comment by shimotmk** [comment]
cosed at #42975

**Pull request closed without merging**
