### PR TITLE
Add duotone and dimensions to the block level for translation

### PR DESCRIPTION
**Pull request by oandregal**
Follow-up to https://github.com/WordPress/gutenberg/pull/66675
Core backport at https://github.com/WordPress/wordpress-develop/pull/8031/files

## What?

Make duotone and aspect ratios translatable to the block level ([details](https://github.com/WordPress/wordpress-develop/pull/8031/files#r1895617293)).

## Why?

Without this, the strings are not translatable.

## How?

Adds duotone & aspect ratios under `settings/blocks/*`, so strings defined at these places are extracted for translation.

## Testing Instructions

None. This will be picked by the wp-cli/i18n-command when merged in wordpress-develop.

### CODE REVIEW

**Comment by swissspidy** [comment]
@oandregal I wonder, how can we prevent this (forgetting to make these strings translatable) from happening in the future? A CI workflow or lint script would be useful IMO.

**Review by ntsekouras — APPROVED** [review]

**Comment by oandregal** [comment]
> I wonder, how can we prevent this (forgetting to make these strings translatable) from happening in the future? A CI workflow or lint script would be useful IMO.

Yeah, judging by the number of misses, I agree this is an area that needs to raise more awareness.

I'm happy to help with this, but I'm not sure how the lint would work, though. There are heuristics, but they are a bit weak: arrays present in `settings` within `lib/theme.json`? But there false positives. Or perhaps properties named `name`? But you can really name it anything you want. 🤔

**Comment by swissspidy** [comment]
Or maybe just some bot telling you to maybe update the schema file, just like it does for changelog files?

**Comment by oandregal** [comment]
> Or maybe just some bot telling you to maybe update the schema file, just like it does for changelog files?

Oh, nice.

Could it work this way? Every change in `theme.json` will trigger the CI job and will fail if the new property added in `theme.json` is not in `theme-i18n.json` unless it has been added to a list of properties not to translate. We could bootstrap the initial list. It'd be even better if this was just part of the theme.json schema. cc @ajlende as it sounds something right up your alley :)

I'm not sure I'll have time to look at this before end of year given holidays, etc. but it sounds interesting!

**Pull request merged**
