### PR TITLE
chore: remove `eslines`

### PR DESCRIPTION
**Pull request by ntwb**
## Description

Reverts the ESLines addition from #4245 

See also https://github.com/WordPress/gutenberg/pull/4245#issuecomment-358567699

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
I was about to comment about `npm run lint` :)

**Comment by gziolo** [comment]
Yes, `"lint": "eslint .",` is the way to go. I double checked the commits history.

**Review by gziolo — APPROVED** [review]
LGTM, thanks for removing it. It only slows down linting when there are no warnings :)

**Comment by aduth** [comment]
Do we plan to reintroduce `eslines` at some point? I would strongly support flagging errors on modified code, as warnings are non-enforceable and -- frankly, ignored more often than not.

**Comment by gziolo** [comment]
We shouldn’t have any warnings at the moment.

**Comment by aduth** [comment]
I guess I'm thinking if we reintroduce documentation rules, e.g. #4506, which would also seem advisable, assuming exceptions can be added for common/inherited functions.

**Comment by gziolo** [comment]
Right, if there are still warnings we can add eslines back until they are fixed.

**Pull request merged**
