### PR TITLE
Image Block: Use the figure wrapper for images with wide/full alignment

### LINKED ISSUE #1665: Images with `alignfull` and `alignwide` shouldn't be enclosed by `p`
A full width image with no caption is rendered like:

```HTML
<p>
  <img src="..." alt="..." class="alignfull wp-block-image">
</p>
```

Most themes will have a full width `p` element, so it is nearly impossible to make the image full width, without JS or some `position: *` hacks.

Some possible solutions:

* always use the `figure` element for `alignfull` and `alignwide`
* use a `div` element with `alignfull` and `alignwide` instead of the `p`
* add the `alignfull` and `alignwide` classes also to the `p` element.

Similar to https://github.com/WordPress/gutenberg/issues/1305

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1665

### CODE REVIEW

**Comment by jasmussen** [comment]
Looks like it's working for me 👍 👍

screen shot 2017-07-03 at 16 16 25

**Comment by iseulde** [comment]
How about always adding the figure tag? I'm not sure why the alignment should cause different semantic tags.

**Comment by pfefferle** [comment]
@iseulde this might be problematic with alignleft and alignright

**Comment by iseulde** [comment]
Why?

**Comment by pfefferle** [comment]
because they should be inside the normal text float and should not break the paragraph

**Comment by iseulde** [comment]
It will still be floated correctly? I'm not sure if I understand the concern. Also, these cannot be inserted inside a paragraph, they're blocks.

**Comment by mtias** [comment]
@iseulde I agree with always using figure, it should simplify the logic in `save`.

**Pull request merged**
