### PR TITLE
Chrome: Adding the discussion panel to configure comments and trackbacks

### LINKED ISSUE #858: Sidebar: Add Discussion Panel
Design:

screen shot 2017-05-22 at 12 23 23

This subsumes the trackbacks panel. The blue link for trackbacks simply shows a textfield below itself, where you can paste trackback URLs. 

Context:

post settings

### PR DESCRIPTION
**Pull request by youknowriad**
closes #858

### CODE REVIEW

**Comment by jasmussen** [comment]
I cannot BELIEVE how fast you're working. Thank you!

Looks good, works well. 

The "Trackbacks" link should ideally have the same margin that the panel rows have, so it looks like 3 even lines.

The link, though, should not take you to the support document. This is my bad —  I haven't mocked it up. Essentially what I'm imagining a click on that link doing, is opening up a replacement for this old panel:

screen shot 2017-05-25 at 12 25 43

So the link is essentially a "show/hide" panel, which when clicked shows a version of the above. Maybe this?

screen shot 2017-05-25 at 12 33 45

**Comment by youknowriad** [comment]
> I cannot BELIEVE how fast you're working.

I have to admit these tickets are straightforward :)

> The link, though, should not take you to the support document.

Yes, I was wondering what was the link for :). Thanks for the mockups

**Comment by youknowriad** [comment]
@jasmussen I'm not familiar with the "send trackbacks" feature and I couldn't find where this attribute is saved, it's not in the post object at first glance. @nylen do you have hint here?

I'm thinking we could delay the "send trackback" panel to another PR.

**Comment by jasmussen** [comment]
> I'm thinking we could delay the "send trackback" panel to another PR.

Totally fine. In fact, I wish we didn't have to implement it at all —  it's a vestigial feature that probably noone uses anymore.

**Comment by pento** [comment]
Per [this discussion](https://core.trac.wordpress.org/ticket/38207), trackbacks are likely to be disabled by default in the future. I wouldn't bother implementing it here.

**Comment by youknowriad** [comment]
Any technical :eyes: on this before merging?

**Review by ellatrix — APPROVED** [review]
Works great here.

**Comment by swissspidy** [comment]
I had a client asking where the "Send Trackbacks" section went and this comment is the only thing I could find.

> Per this discussion, trackbacks are likely to be disabled by default in the future. I wouldn't bother implementing it here.

@pento Is this decision documented somewhere? Otherwise I'd consider it a missing feature.

I'm totally fine with disabling this section by default, but there hasn't been any progress at https://core.trac.wordpress.org/ticket/38207 for over a year.

**Comment by pento** [comment]
@swissspidy: Only here and on WP38207.

What's the use case for Trackbacks that isn't solve by Pingbacks?

**Comment by swissspidy** [comment]
I'm still waiting to hear back from the client to hear about their use case. I personally don't use Trackbacks so I can't think of anything else except trackback spam right now.

Again, I don't mind not implementing trackbacks in Gutenberg, but it probably should be written down somewhere. Or at least the core ticket should be moved forward.

**Pull request merged**
