### PR TITLE
Allow developing Gutenberg with NPM v7 and v8

### PR DESCRIPTION
**Pull request by simison**
## What?

Part of [Upgrade node and npm to latest LTS versions](https://github.com/WordPress/gutenberg/issues/34801).

Remove old restriction to use only NPM 6, thus allowing use of NPM 7 and 8.

NPM 6 came with Node.js 14 which is a bit older at this point already: https://github.com/nodejs/release#release-schedule

I'd expect to be able to use at least Node.js 16 or 18 for developing Gutenberg, and thoes come with newer NPM.

It's of course possible to keep using older NPM with newer Node.js, but that's not very convenient. 

## Why?
Restriction [was added 2 years](https://github.com/WordPress/gutenberg/pull/29204) ago because of a [bug in NPM](https://github.com/npm/cli/issues/2610). Issue with NPM seems to persist, but:

- I don't know if the problem affects Gutenberg anymore; not quite sure how to test either! [There's only one `git+https` dependency](https://github.com/WordPress/gutenberg/search?q=%22git%2Bhttps%22) but it's for [react native editor](https://github.com/WordPress/gutenberg/blob/705ab44f2c2797d75740533a85030c194b4fb040/packages/react-native-editor/package.json) and I don't know how to test that.

- [Issue commenter noticed](https://github.com/npm/cli/issues/2610#issuecomment-1297494582) the bug doesn't affect NPM 6 when using older Lockfile v1 versions (which Gutenberg currently uses). This could be the case with newer NPM versions, too?

    > Running NPM 6.14.x, this is only an issue with lockfile v2. Reverting back to a v1 lockfile fixes it.

- [Issue commented offered](https://github.com/npm/cli/issues/2610#issuecomment-1295371753) a solution that seemed to help:

   > I just had success by changing from `git+https://github.com/` to `git+https://git@github.com/` —it then resolved to HTTPS in my lock file.

## How?
So far I've only removed the restriction and didn't apply the suggested `git+https://git` solution.

## Testing Instructions
`npm ci`

### CODE REVIEW

**Comment by talldan** [comment]
@simison https://github.com/WordPress/gutenberg/issues/40540 sounds like it's progressing in terms of solving some of the issues with mobile dependencies.

**Comment by simison** [comment]
FYI @fluiddot @geriux above `git+https://git@github.com/` solution, in case it helps!

**Comment by fluiddot** [comment]
Heads up that https://github.com/WordPress/gutenberg/issues/40540 has been addressed 🎊 . However, when installing the dependencies using npm 8, I encountered a different error. More info at https://github.com/WordPress/gutenberg/issues/46443.

**Comment by ockham** [comment]
> However, when installing the dependencies using npm 8, I encountered a different error. More info at #46443.

If that's a blocker for this PR, we might consider restricting to npm < v8 until we've sorted out #46443.

**Comment by kevin940726** [comment]
Note that I believe there's a temporary workaround for https://github.com/WordPress/gutenberg/issues/46443#issuecomment-1346134716. We can try that in this PR and see if it works?

**Comment by simison** [comment]
@kevin940726 @fluiddot feel free to modify this PR meanwhile, I can help depending on how I find time from other work.

**Comment by aristath** [comment]
An update for anyone watching this ticket:

Today, @carolinan, @SergeyBiryukov. @afercia and I, had a coding session where we tried to upgrade to the latest LTS versions for node/npm.
There were a lot of hickups and we came up with these changes: https://github.com/WordPress/gutenberg/pull/46576/files
These are the bare minimum changes required to make `npm install` and `npm run build` to work.
Of course all tests fail because there are conflicts with packages that run on the CI - however, it's enough to start working locally.
We had a lot of issues with react-native and emotion-native.. Those 2 seem to be holding back a lot of other things.
Additionally, the scripts we have in [`/bin/plugin`](https://github.com/WordPress/gutenberg/tree/trunk/bin/plugin) use old versions of the oktokit packages - which causes a lot of failures too. It looks like the API in newer oktokit packages versions has changed a bit - which means some of those scripts should be rewritten.
There are a few packages that have been deprecated, and there are plenty of warnings in the terminal that should be fixed by updating packages.
We ended up having to add `legacy-peer-deps = true` inside the `.npmrc` config file. It's less than ideal, but will allow us to get a head start and have something functional while we work out all the kinks.

**Comment by ockham** [comment]
@aristath As for octokit, I tried [upgrading](https://github.com/WordPress/gutenberg/pull/29043) that to a newer version a while ago but unfortunately [got stuck](https://github.com/WordPress/gutenberg/pull/29043#discussion_r588572822) because of a bug in some type definitions. But maybe that PR can help as a starting point.

**Comment by simison** [comment]
This is actively worked on at https://github.com/WordPress/gutenberg/pull/48950 by @kevin940726, so closing this PR.

**Pull request closed without merging**
