### PR TITLE
Navigation: formatting the allowed styles

### LINKED ISSUE #19473: Navigation Block outputs raw HTML on Frontend Site
**Describe the bug**
Navigation Block outputs raw HTML on the frontend of the site. 

**To reproduce**
1. Add a navigation block to a page
2. Add bold text, italics, an image etc to a navigation item.
3. Publish the page
4. Visit the page on the live site
5. See the raw HTML instead of formatted text, so `<strong>My Link</strong>` instead of **My Link**

**Expected behavior**
HTML should be rendered as HTML instead of output as plain text.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: MacOS Catalina - 10.15.2
 - Browser: Chrome
 - Version: 79.0.3945.88

**Additional context**
Tested on WordPress.com, Gutenberg 7.1, and `master` build.

### PR DESCRIPTION
**Pull request by retrofox**
## Description
This PR handles rightly applying HTML format to menu items, avoiding escape HTML characters for those ones which are allowed.

Fixes https://github.com/WordPress/gutenberg/issues/19473

## How has this been tested?
You can format the menu items using the toolbar of the navigation menu. So far, it's possible to set up bold, italic, code, underline, strikethrough, span text, and inline-image.

image

In order to test it, just apply some format to the navigation item and confirm that the format s applied as expected in the front-end.

## Screenshots 

image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by WunderBart — APPROVED** [review]
Tested by applying a bunch of formatting options - looks good on both front & back-end!

Screenshot 2020-01-07 17 09 57

**Review by getdave — APPROVED** [review]
Nice work. 

I tested this and all the formats appeared to apply correctly in Editor and on front end.

#### Frontend
Screenshot 2020-01-08 at 09 42 53

#### Editor
Screenshot 2020-01-08 at 09 42 41

**Comment by retrofox** [comment]
Thanks for reviewing, folks!

**Comment by draganescu** [comment]
@retrofox be careful with that planet destroyer!

**Comment by retrofox** [comment]
> @retrofox be careful with that planet destroyer!

No kidding, he's so cute as destructive! 😱

**Comment by maheshwaghmare** [comment]
Nice work!

I was also thinking to create a PR but @retrofox did nice work.

---

Below are my findings.

Backend: https://share.getcloudapp.com/xQu0zkwJ

Before Code: 
```
$html .= esc_html( $block['attrs']['label'] );
```
Before Front End : https://share.getcloudapp.com/ApuOxoe5

After Code:
```
$html .= wp_kses_post( $block['attrs']['label'] );
```

After Front End: https://share.getcloudapp.com/p9u5X4Z1

**Comment by retrofox** [comment]
Thanks, @maheshwaghmare for your comment.

> After Code:
> 
> ```
> $html .= wp_kses_post( $block['attrs']['label'] );
> ```

I did a quick research about how to tackle this issue and found `wp_kses_post()` as well. The thing is if I'm not wrong `wp_kses()` fits better on this solution since it allows us to define the allowed tags and, since they are just a few, the performance will be better than using the wp_kses_post().

**Comment by obenland** [comment]
I wouldn't be too concerned about performance with strings as short as we can expect in a label

**Comment by retrofox** [comment]
> I wouldn't be too concerned about performance with strings as short as we can expect in a label

So we could consider switching to `wp_kses_post()` since if we add a new HTML tag then we will need to update the list of `wp_kses()`.

**Comment by obenland** [comment]
oh, my bad, yes absolutely, I think I'd prefer `wp_kses_post()` here as well

**Pull request merged**
