### PR TITLE
Fix typo: Remove extra 'the'

### PR DESCRIPTION
**Pull request by burhandodhy**
## Description

Fix typo : Remove extra 'the' in core-edit-post.md

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by Soean** [comment]
Hey @burhandodhy 
nice catch. The docs are generated from the source code. So you have to edit the source file: https://github.com/WordPress/gutenberg/blob/master/edit-post/store/selectors.js

**Comment by burhandodhy** [comment]
Thanks, Soean

It is fixed now.

**Comment by Soean** [comment]
@burhandodhy To remove the space after `## Selectors` you also have to change the source code: https://github.com/WordPress/gutenberg/blob/master/docs/tool/generator.js#L68
 
I think you can regenerate the docs from the source code with `npm run docs:build`?

**Comment by burhandodhy** [comment]
Done

**Review by Soean — APPROVED** [review]
Thanks, I think the PR is fine now.

**Comment by gziolo** [comment]
It needs another rebase because we had to change the way generated files are named. Sorry about that. Once it is done, we can merge it. Thanks for working on it 🎉

**Comment by Soean** [comment]
@burhandodhy Can you do a rebase or open a new PR?

**Comment by danielbachhuber** [comment]
Landing with #9238

Thanks again for your work on this, @burhandodhy.

**Pull request closed without merging**
