### PR TITLE
Hide Preview menu on small viewports and fix regression for FSE preview

### LINKED ISSUE #24385: Preview menu: dropdown still available on mobile when changing device orientation
**Describe the bug**

In WordPress 5.5, the Preview is now a menu with preview options for desktop, tablet, mobile, and traditional preview in a new browser tab. On small screens, this menu is meant to be hidden and replaced with a simple Preview link (no menu). The switch between the two Preview (menu and simple link) happens at a viewport width of 600 pixels.

However, when on a mobile device, changing device orientation may lead to a unexpected behavior.

**To reproduce**

- using Chrome, emulate a device with a landscape viewport width larger than 600 pixels and a portrait viewport width smaller than 600 pixels, e.g.: iPhone 6/7/8 Plus
- start in landscape orientation
- click the Preview button
- the Preview menu opens and displays the preview types
- keep the menu open
- change device orientation to portrait
- the Preview button is now hidden and replaced by the simple Preview link
- however, the Preview menu is still open and now its position is partially off-screen
- more importantly: it is still possible to click the various options in the Preview menu, which I guess is not desired

Animated GIF:

preview menu and device orientation

**Expected behavior**
The menu to automatically close when the Preview button gets hidden.

**Editor version (please complete the following information):**
- WordPress version: 5.5 RC 2
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default.

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Resolves: https://github.com/WordPress/gutenberg/issues/24385

Also fixes a small regression from this PR: https://github.com/WordPress/gutenberg/pull/24487, that hid the `Preview` component in `FSE`.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice.

Before:

fix

After:

after

From this testing shown above, though, you can see that the preview dropdown is only _hidden_ when the mobile breakpoint is invoked. I wonder if it should be closed? I know that's a tougher thing to fix, and this improves the situation. But when the preview is open, focus is captured there, when it then gets hidden you can set focus elsewhere, and focus is no longer trapped inside when you go back.

**Comment by ntsekouras** [comment]
> But when the preview is open, focus is captured there, when it then gets hidden you can set focus elsewhere, and focus is no longer trapped inside when you go back.

Good point @jasmussen! I'm investigating about a React based solution :)

**Comment by ntsekouras** [comment]
@jasmussen when you have time you cat take this again for a spin? :)

**Comment by jasmussen** [comment]
This is working well for me! 

Focus is put on the body element when the menu is open and you resize the viewport. I'm not sure what the best practice for responsive design and focus management on disappearing elements is. Seems like it would be nice to set focus on the preview button, but that might also be overdoing it? Happy to defer to someone else. But as is, this seems to work better than it did a moment ago, and is an overall net improvement!

**Review by enriquesanchez — CHANGES_REQUESTED** [review]
Just tested and worked as expected:



>Seems like it would be nice to set focus on the preview button, but that might also be overdoing it?

Agreed, I think focus should be retained on the Preview button, otherwise, it's disorienting.

**Comment by ntsekouras** [comment]
Thanks for reviewing @enriquesanchez !

> Agreed, I think focus should be retained on the Preview button, otherwise, it's disorienting.

Open the `Preview menu` -> change orientation -> change orientation immediately back:

is just one scenario of the many. In most cases the user might keep on doing things, and probably try to click the same button again, which now is just a link. 

Should we keep track of this change ( orientation ) and then track any new `focus` and if no `focus` occurs and orientation changes again to focus the `Preview` button? Also this is implemented technically with just `width` check and no `change orientation` event, so I'm not really sure how easy/effective would be to track..

-cc @mcsf @youknowriad

**Comment by jasmussen** [comment]
I think it's an open question. Focus lands on `body` when you size down the browser and focus is removed from the popover. That lets you tab through the document again. So I don't know that you could call that focus being _lost_ — it's very literally an edgecase where you resize a window when a popover is open and has focus.

While it might be be luxurious to handle focus in the way outlined, it might also be shooting birds with cannons. Unless there's a use case I'm missing, in order to invoke this use case, you have to first click the preview dialog on a big window. Then you have to actively click outside the editing canvas to resize the window to close the popover. While resizing a window does not remove focus inside an active webpage, it does involve clicking elsewhere and then clicking back, at which point there's a great chance you'll set focus in a new place, or at least remove focus from where it was.

My question is legitimate: is there a best practice for handling focus in responsive situations where an element gets removed from the DOM?

Microsoft Word is not the best parallel or example or even representative necessarily of a best practice. But just as a quick test: no, they don't do anything to handle focus in responsive cases:

word online

**Comment by enriquesanchez** [comment]
Definitively an edge case, but I see this being a possible occurrence for someone using a hand-held device, like a phone, and also using a screen reader.

In that scenario, the user doesn't need to click elsewhere (in which case I agree the focus has been intentionally moved by the user) but only tilt or rotate their device. The feeling of disorientation would probably be worse if you're using a screen-reader and don't perceive the layout changes on screen due to the device's orientation change. All of the sudden you find your focus somewhere else without knowing why.

**Comment by ntsekouras** [comment]
I don't believe there is a `focus tracking` system right now and to build one would be definitely a bigger job. I'm also a bit concerned about the complexity and if it would be better to find another way to handle the specific case of `Preview menu`, as no other similar cases like these come in my mind now and that would mean building a system only for this case. As @jasmussen summarises my concern:

> While it might be be luxurious to handle focus in the way outlined, it might also be shooting birds with cannons.

I believe this could be discussed and addressed in a follow up PR, taking into account the current behaviour in `master`. Would this PR be at least a step forward or would make things worse? :) 

Do you think this is a blocker for now @enriquesanchez? If yes, I should create a separate PR to fix a small `regression` that hides `Preview menu` in `FSE`, as I had it in here because I thought it would have no other concerns ( focus ).

**Comment by enriquesanchez** [comment]
@ntsekouras I don't think it's a blocker and this is definitively an improvement that addresses the initial issue.

**Review by enriquesanchez — APPROVED** [review]

**Pull request merged**
