### PR TITLE
Try: Improved tabbed sidebar styles

### PR DESCRIPTION
**Pull request by DaniGuardiola**
I've removed the "balanced" tabs styles, as it overrides the built-in Tabs styles - we're trying to avoid and remove style overrides in the components package for many reasons. @afercia discussed tabs styles here: https://github.com/WordPress/gutenberg/issues/62025

If we want these styles to be an option for Tabs, then it should be proposed, discussed and implemented in the Tabs component directly. These styles, though, present some problems beyond aesthetic concerns, notably it could behave badly in other languages since the length of the labels is unpredictable (see @afercia's comment: https://github.com/WordPress/gutenberg/pull/61974#issuecomment-2149719264)

Before:

https://github.com/WordPress/gutenberg/assets/8862967/6756cd14-05fb-4b59-8486-6860f42cc3dd

After:

image

image

---

Note that this PR also removes a few styles that were completely redundant (basically all but the negative bottom margin).

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
To be fair, I prefer how it was before. 

From what I understand, we try to keep the tabs occupying all the horizontal space, which made even more visual sense when the X button wasn't there. Even with the X button though, it's OK for them to be wider and occupying more space, there's not much else to do with that space and folks are likely used to have larger inserter category tabs.

This is something @WordPress/gutenberg-design should have a good sense about.

**Comment by jasmussen** [comment]
Thanks for your attention to detail. There's an ongoing conversation about these changes, maybe @richtabor has more info.

**Comment by richtabor** [comment]
There is a discrepancy between the tabs in the Inserter and the Inspector, but I am cautious to reduce the surface area of the Inserter tabs. 

Here's the state of the tabs: 

### Current:

| Inserter  | Inspector |
| ------------- | ------------- |
|CleanShot 2024-05-30 at 16 47 38|CleanShot 2024-05-30 at 16 47 45|

CleanShot 2024-05-30 at 17 03 38


### Proposed:

| Inserter  | Inspector |
| ------------- | ------------- |
|CleanShot 2024-05-30 at 17 00 23|CleanShot 2024-05-30 at 17 00 38|

CleanShot 2024-05-30 at 17 01 37

**Comment by richtabor** [comment]
And here's a counter, if we applied the same positioning logic that exists in the Inserter to the Inspector tabs: 

CleanShot 2024-05-30 at 17 04 51

Not a formal proposal; an exploration.

**Comment by DaniGuardiola** [comment]
Thanks for the visuals, very helpful @richtabor. I think I strongly prefer the first option, personally.

**Comment by afercia** [comment]
> There is a discrepancy between the tabs in the Inserter and the Inspector,

Yes, and I reported the inconsistencies in https://github.com/WordPress/gutenberg/issues/62025

To me, tabs should have the same alignment / layout everywhere.

Worth reminding the X close button is candidate to be removed from there, as it breaks the ARIA tabs pattern. See https://github.com/WordPress/gutenberg/issues/59013 / https://github.com/WordPress/gutenberg/issues/58940

As per @DaniGuardiola proposal in this PR, I support the left alignment option. To me, it doesn't make much sense attempting to have a balanced equal width because the length of the tabs content is not predictable. It may look nice in English, which usually has shorter strings, but it's a bit pointless with longer / uneven strings in other languages.

**Comment by tyxla** [comment]
If the consensus is in favor of the left-aligned instead of balanced-width tabs, I'm fine with that 👍

**Comment by scruffian** [comment]
> To me, tabs should have the same alignment / layout everywhere.

This is the aim of the component I am proposing in https://github.com/WordPress/gutenberg/pull/62343

**Comment by DaniGuardiola** [comment]
I've updated the PR after @scruffian's work to unify sidebar, and also edited the description to more clearly state the issues and how this PR addresses it. I'd like to seek some consensus around this to hopefully make a decision.

cc @WordPress/gutenberg-design @WordPress/gutenberg-components @richtabor @tyxla @afercia

**Comment by jameskoster** [comment]
There are also these tabs in the Inspector:

Screenshot 2024-07-25 at 09 46 48

I agree the behavior should be consistent across. The example above would look quite strange if the icons were aligned left.

Looking at the component objectively, centrally aligning the label seems simplest, likely with a prop to specify when the row should fill the container or not.

| Fill | Do not fill |
| --- | --- |
| Screenshot 2024-07-25 at 09 45 11 | Screenshot 2024-07-25 at 09 45 24 |
| Used by: Block settings/styles | Used by: Inserter, Document/Block tabs in the Inspector |

There could also be a prop to left-align the label/icon, but I'm not entirely convinced it's worth the added complexity.

**Comment by afercia** [comment]
> There are also these tabs in the Inspector:

Screenshot 2024-07-25 at 09 46 48

Yes, and the Navigation block shows 3 icon-tabs:

Screenshot 2024-07-25 at 14 15 21

I have a solution for that: use text instead of icons by default 🥳
That would be better for accessibility and would also be consistent with the tabs at the top of the panel.

Worth reminding that enabling the 'Show button text labels' preference already switches those tab icons to text, and the alignment is still inconsistent:

Screenshot 2024-07-25 at 14 18 51

**Comment by DaniGuardiola** [comment]
I think those tabs are a different (but definitely related) issue. This PR focuses on the tabbed sidebar layout, currently only present in inserter and list view, but planned for other similar sidebars across the app (see https://github.com/WordPress/gutenberg/pull/62343 for full context). I personally feel like what needs to be consistent is this component (tabbed sidebar), and it doesn't feel weird if other tabs like that example have a different layout (especially since it is already quite different by having icon labels instead of text).

With that in mind, and if we agree on that, I'm happy to discuss more about those tabs. My hunch is that it might justify a "balanced" variant for icon-based tabs, some notes:

> centrally aligning the label seems simplest

I agree. I think for this "balanced" variant, labels (in this case icons) should indeed be centered.

> Worth reminding that enabling the 'Show button text labels' preference already switches those tab icons to text

Agreed. I think the variant should probably revert to the default "left-aligned" layout when the preference is enabled. Feels like it should be implemented at the usage/product level though, and not at the component level, since the preference is a product-level feature.

**Comment by afercia** [comment]
>  I personally feel like what needs to be consistent is this component (tabbed sidebar), and it doesn't feel weird if other tabs like that example have a different layout

I'd agree the inconsistent layout with other tabs isn't a blocker for this PR, which is an improvement. I'd encourage to moev on with this PR as long as there is a follow-up to better consider consistent alignment for _all_ tabs across the entire editor UI.

**Review by tyxla — COMMENTED** [review]
I'm generally in favor of the approach here, since it contributes to a more consistent tabs behavior across the editor and less custom styles and overrides. 

However, before we move forward, it would be nice to have a consensus on the design approach, especially as far as those icon-only tabs.

**Comment by ciampo** [comment]
> likely with a prop to specify when the row should fill the container or not.

@jameskoster  Probably something to add to a hypothetical issue on whether `Tabs` should allow for tabs overflowing its layout. We need to find the right balance between using props, and just empowering users of the components to apply their layout preferences via CSS to the individual compound components.

**Comment by jameskoster** [comment]
In terms of design, the question to answer is whether to apply the 'fill' prop in these contexts or not. In other words which is preferred between:

| Fill | No fill |
| --- | --- |
| Screenshot 2024-08-06 at 11 13 22 | Screenshot 2024-08-06 at 11 13 51 |

Personally I wouldn't consider that decision a blocker to this PR.

**Comment by jasmussen** [comment]
Although for icon-only tabs, they should be centered, the centered text in the fullwide tabs feels awkward. That's either an argument for no fill, or for left-aligned in the tabs by default, with the centered option an exception, or a combination of both.

**Comment by jameskoster** [comment]
Ideally we should figure out which options the component should offer and go from there.

We know we want fill-with-centered contents for the block settings toolbar so this should be built into the component.

The fill-with-left-aligned-contents is dubious imo. It only really seems to exist to align the tab first label with the contents below in the Inserter / Inspector. This is an exception, which is fine, but doesn't really make sense as a component option.

To unlock this work I'd propose;

- Update the tab component so consumers are able to use a 'fill' layout. 
  - In this layout the tab contents are centrally aligned.
- By default tabs will 'hug' their contents.
- Update the Inserter tab instance to either:
  - Use the 'fill' layout with an override to left-align the text.
  - Use the default 'hug' layout.

**Comment by DaniGuardiola** [comment]
Thank you for your comments. I like your proposal @jameskoster, though practically speaking if we go for "Update the Inserter tab instance to > Use the default 'hug' layout" then implementing the "fill" variant is not a blocker for this specific PR. I strongly prefer this resolution personally, and it's also the simplest:

image

**Comment by jameskoster** [comment]
The issue with merging this first is that there will be an interim where the inserter tabs are narrower, which could be seen as a visual regression. Personally I think it's okay, so long as we address the other issues reasonably quickly, but I'd welcome more thoughts from @WordPress/gutenberg-design.

**Comment by DaniGuardiola** [comment]
@jameskoster yes, to be clear I'm proposing that we go with that option ("Update the Inserter tab instance to > Use the default 'hug' layout"), not just temporarily. If so, "fill" is not a blocker here, and tabs being narrower is not a regression but just a "permanent" update. I hope that clarifies what I meant?

**Comment by jameskoster** [comment]
> not just temporarily

Right, that's the part we need design consensus on. Is the following acceptable:

Screenshot 2024-08-07 at 12 41 07

It's fine with me, to be honest, but I don't have a full history around the design of this UI. Hopefully @jasmussen can help make this decision.

**Comment by jasmussen** [comment]
Sure let's try it. 

In general we should avoid _centered text_, so I think that does need followups. But all these pieces need followup, so that wouldn't be a blocker.

**Review by jameskoster — APPROVED** [review]

**Review by tyxla — APPROVED** [review]
Glad to see some consensus on the design side 👍 

Just confirming, while the text tabs are no longer balanced, the tabs with icons remain balanced, which makes sense and looks good IMHO:

Screenshot 2024-08-07 at 16 26 45

Thanks for the cleanup @DaniGuardiola, looks great 🚀

**Comment by DaniGuardiola** [comment]
@WordPress/gutenberg-design "fill" implementation https://github.com/WordPress/gutenberg/pull/64371

cc @jameskoster @jasmussen

**Pull request merged**
