### PR TITLE
[Mobile] - Global styles - Add support to render font sizes and line height

### PR DESCRIPTION
**Pull request by geriux**
`Gutenberg Mobile PR` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/3924

## Description
This PR is a follow-up of https://github.com/WordPress/gutenberg/pull/33605 and adds the functionality to render custom font sizes and line height in the editor. 

This is under the `DEV` flag.

## How has this been tested?

**Notes to test in a dev build**:
- For iOS make sure to clear the build folder and on Android to build Gutenberg Mobile locally.
- To test the line-height feature you need a theme that has this enabled, like the Quadrat theme.

### Test case 1 (font size)

- Open the app
- Add a Paragraph block with a few lines of text
- Open the block settings
- **Expect** to see the Font size selector
- Select a font size
- **Expect** the value to change accordingly

### Test case 2 (line-height)

- Open the app
- Add a Paragraph block with a few lines of text
- Open the block settings
- **Expect** to see the line-height selector
- Change the line-height value
- **Expect** the value to change accordingly in the block

## Screenshots 

Test case 1 iOS|Test case 1 Android
-|-
<kbd></kbd> | <kbd></kbd>

Test case 2 iOS|Test case 2 Android
-|-
<kbd></kbd> | <kbd></kbd>

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by enejb** [comment]
I tested this on iOS and I wasn't able to get the line-height settings to work. 
Eventhough I see your changes in https://github.com/WordPress/gutenberg/pull/34144/files#diff-3523b4a5a519e3975d67f8a202df9e8f91b3e3aff0168c86598c9e2abcbdf890R671-R681 

I cleared the cache and restarted Xcode to get it running as expected. :( 

Any ideas why its not working as expected in my testing?

**Comment by geriux** [comment]
> Any ideas why its not working as expected in my testing?

Interesting! Sorry that it didn't work by clearing the cache :(

Could you try to run this on WordPress iOS and build again to see if it works?
`LOCAL_GUTENBERG=true bundle exec pod install`

After you finish testing remember to change it back 
`LOCAL_GUTENBERG=false bundle exec pod install`

Let me know, thanks!

**Comment by antonis** [comment]
Hey Gerardo 👋 
Tested this on Android with a composite build with AS running metro but I cannot get the *line height* to work. The test instructions state that I need the `Quadrat` theme. I guess I misread that as `Quadra` and this explains why I cannot see that working. I'll retest and get pack to you on this.

Regarding the font size I noticed an issue (using the Quadra theme) with the text scrolling inside the paragraph after a certain text size. I only got to reproduce this once. I tried again with the same and other themes and it works as expected (resizing the block accordingly). I guess this may have to do with a glitch in Metro. Just noting this here in case it comes up again.
<details>
 <summary>Screenshot</summary>
 
device-2021-09-08-163022
</details>

**Comment by geriux** [comment]
Thanks for testing @antonis!

> Tested this on Android with a composite build with AS running metro but I cannot get the _line height_ to work.

What was the issue exactly? Did you see the line-height setting there? Or was it missing? If it was missing, it is because the theme you have activated doesn't have support for it. (It might be related to the confusion with Quadra and Quadrat)

If you saw the line-height selector setting and changing the value didn't work it might be related to the native changes not being included in the build. Let me know what you find once you test again with Quadrat.

> I guess this may have to do with a glitch in Metro. Just noting this here in case it comes up again.

It might be, I'll keep an eye if I encounter this. I tried to reproduce now but I couldn't.

Thanks!

**Review by antonis — APPROVED** [review]
Great work @geriux 👍 
I retested this with a JN site using the **Guadrat** theme. Everything worked as expected both on Android (Pixel 5, Android 12) and iOS (iPhone SE 2020, iOS 14.7.1) 🎉 
The code changes also LGTM 👍 

I was also not able to reproduce the [issue](https://github.com/WordPress/gutenberg/pull/34144#issuecomment-915251050) I reported earlier again 🤷

**Review by enejb — APPROVED** [review]
This worked well for me. Let's shit it!

**Comment by geriux** [comment]
> This worked well for me. Let's shit it!

Yay! Thank you for testing @enejb and for collaborating with these changes and adding Android support 👏

**Pull request merged**
