### PR TITLE
Group Block: Add support for custom border settings

### PR DESCRIPTION
**Pull request by scruffian**
## Description
This makes it possible to customize the border settings of the group block. This is necessary for TT1-Blocks, which has a border-style for the group block

## How has this been tested?
- Switch to TT1 Blocks
- Add a group block and give it a background
- Add these lines to the `styles` section of theme.json:
```
		"core/group": {
			"border": {
				"color": "var(--wp--preset--color--gray)",
				"radius": "20px",
				"style": "solid",
				"width": "3px"
			}
		}
```

## Screenshots
Now TT1 Blocks ground blocks look like this:
Screenshot 2021-03-05 at 16 48 31

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [-] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aaronrobertshaw — APPROVED** [review]
This tests well for me 👍 

Do we need to add this via block supports as well, just without exposing the controls by default until the UI can go through the design process?

**Comment by nosolosw** [comment]
> Do we need to add this via block supports as well, just without exposing the controls by default until the UI can go through the design process?

I've asked [here](https://github.com/WordPress/gutenberg/issues/27331#issuecomment-792618660) about how we should address the UI part of borders.

As for adding this to the block level, we could do this one by one, to reduce review time and accelerate landing. I'd like to clarify some things about each of them. For example, I think border-radius and border-width are fine being inline styles. However, it seems to me that border-style can be expressed through classes and border-color can be expressed through classes (user chooses one of the preset colors) & inline styles (user chooses a custom color).

**Comment by nosolosw** [comment]
@aaronrobertshaw I haven't found an issue for adding support for border, so I've created one at https://github.com/WordPress/gutenberg/issues/29616 to track progress.

**Comment by aaronrobertshaw** [comment]
Thanks for creating that issue @nosolosw, I think the closest we had previously was https://github.com/WordPress/gutenberg/issues/21540. I'll pick it up as soon as I have a little extra bandwidth.

**Pull request merged**
