### PR TITLE
Block Editor: Remove block inserter shortcuts

### PR DESCRIPTION
**Pull request by aduth**
Related: #10519, #4951
Partially addresses #5055

This pull request seeks to remove the block inserter "shortcuts" which would previously appear when hovering the "appender" area below the list of blocks in the block editor.

**Needs Design/Accessibility Feedback:** It is proposed that they be removed due to:

- Confusion around how they appear (#5055) and the expected options they include (#18251)
- Accessibility issues including expected tab grouping order (https://github.com/WordPress/gutenberg/issues/10519#issuecomment-447649419)
- Design concerns around the allotment of available space in narrow viewports (https://github.com/WordPress/gutenberg/issues/19033#issuecomment-564095717)
- Anecdotal assessments that these shortcut options do not provide meaningful benefit to the user experience ([related Slack discussion](https://wordpress.slack.com/archives/C02QB2JS7/p1573065172059200)).

Their removal yields a simplification, both in the technical implementation and to the benefit of users in reducing the surface area of block insertion options.

Before|After
---|---
Before|After

**Testing Instructions:**

Verify there are no regressions in the insertion of blocks, specifically in using the "default" appender, which is expected to show either when:

1. The post is empty
2. The last block is a selected, empty paragraph
3. The last block is a non-paragraph

_(It's acknowledged that the above logic flow is still prone to confusion, which could be addressed in subsequent improvements surrounding #10519)_

The "+" button should still be shown where the "shortcuts" would have previously been expected to appear, to the left of the block list.

### CODE REVIEW

**Comment by youknowriad** [comment]
I've considered this as well for some time now. I agree that they don't bring much value. Any perspective here @ZebulanStanphill @jasmussen @mapk

**Comment by jasmussen** [comment]
Remove them! I've not used them once.

**Comment by chrisvanpatten** [comment]
Goodbye inserter shortcuts, you will not be missed :wave:

**Comment by ellatrix** [comment]
Yes please!

**Comment by ZebulanStanphill** [comment]
I never use the inserter shortcut buttons. The slash inserter is faster and more useful.

I'd go a step further and change the inserter to look the same as it does for nested blocks, since having the icon to the left and outside of the block border is kind of confusing.

**Comment by karmatosed** [comment]
+1 to remove :)

**Comment by aduth** [comment]
> I'd go a step further and change the empty Paragraph inserter to look the same as it does for nested blocks, since having the icon to the left and outside of the block border is kind of confusing.

Do you think this would be fine for a follow-up pull request, or is the need for this directly impacted by the removal of the shortcuts? Given the likelihood that discussions surrounding #10519 can stagnate, I'm inclined to push for more incremental steps.

I sense what you're suggesting is similar to what was explored in #11329, which was closed in part due to lingering questions around (intentional?) differences between top-level and nested block inserters (https://github.com/WordPress/gutenberg/pull/11329#issuecomment-460255583).

**Comment by mapk** [comment]
I've also found they cause confusion for users who hover over them wondering what they are and if they're what they need. 

I'm for removing them.

**Comment by ZebulanStanphill** [comment]
@aduth I'm fine with just removing the block inserter shortcuts for now. However, I do think that with them gone, there is little reason to have the inserter look different at the top level vs. nested contexts.

**Review by youknowriad — APPROVED** [review]
Let's do it.

**Comment by shaunandrews** [comment]
Do it!

**Pull request merged**
