### PR TITLE
Pullquote Block: Add padding and margin support

### LINKED ISSUE #44129: Unable to remove margin in Pullquote
The Pullquote block outputs a `blockquote` inside a `figure`. The issue is that the `blockquote` inherits a default margin, and since the editor does not allow you to target it specifically, it's not possible to remove that margin. Here's the result:

Screenshot 2022-09-13 at 16 32 52

Ideally it should be possible to make the text of the pullquote align with the paragraph before and after it.

### PR DESCRIPTION
**Pull request by t-hamano**
## What?
Add padding and margin support to the Pullquote block.
Fix #44129 at the same time.

## Why?
To create consistency across blocks.

## How?
Added the relevant block supports in block.json. Furthermore, now that the margins can be controlled, I think the default margins for a `blockquote` inside a `figure` should be reset.

## Testing Instructions

AS for `margin` support, this can't be tested on Twenty Twenty Three. This is because [the top / bottom margins are defined as `important` in theme.json](https://github.com/WordPress/twentytwentythree/blob/11440a5b38bae6882fc2c00b703d4bb95420a0f5/theme.json#L507-L510). If this PR is merged, theme.json of Twenty Twenty Three might need to be updated.

## Screenshots or screencast

https://user-images.githubusercontent.com/54422211/201465109-d1075af3-f519-4a7e-8fdd-ece8d34194e2.mp4

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for putting this PR together @t-hamano 👍 

It generally tests well for me. However, there are a few issues that we need to address.

✅ Padding support works
✅ Margin support works in non-TT3 themes tested
❓ Blockquote element margin reset

Resetting the blockquote margin looks like it would be a breaking change for existing pullquote blocks. It also doesn't remove the top margin for the blockquote element's immediate child `p` element.

<details>
<summary>See screenshot of top margin on `p` not being removed</summary>

Screenshot 2022-11-14 at 11 13 09 am
</details>

Off the top of my head, I think our best option might just be to set a default padding on the pullquote block to replace the margin removed from the `blockquote`. 

This should be easily overridden by the block support you've added, not break existing blocks' layout, and avoid the need for us to write a block deprecation or add to core's theme.json. It would still require fixing up the top margin of the blockquote's inner `p` element though.

What do you think?

**Comment by t-hamano** [comment]
Thank you for the review, @aaronrobertshaw !

> Off the top of my head, I think our best option might just be to set a default padding on the pullquote block to replace the margin removed from the blockquote.

Do you mean to add one padding as follows?

```css
.wp-block-pullquote {
	// padding: 3em 0;
	padding: 4em 0;
}
```

> It would still require fixing up the top margin of the blockquote's inner p element though.

This is a difficult problem. I have noticed that if I change the blockquote margins to zero, the content is no longer centered at the top and bottom of the block. This is because the `p` element has a default top margin.

<details>
<summary>Screenshot</summary>

quote

</details>

I have considered the following two approaches, what do you think?

#### Don't change `blockquote` margins to zero

The top margin of the `p` element overlaps the top margin of the `blockquote`, so it will be centered at the top and bottom.
However, even if the padding is set to zero in the block support, the space inside cannot be completely eliminated.

<details>
<summary>Screenshot</summary>

quote-margin-revert

</details>

#### Set the top margin of the `p` element to zero

The padding works perfectly, but would be a more breaking change.

<details>
<summary>Screenshot</summary>

quote-p-margin-top

</details>

**Comment by jameskoster** [comment]
@t-hamano would it be possible to make the Pullquote block have a padding value in design tools as a default, IE:

Screenshot 2022-11-14 at 10 22 07

That would maintain backwards compatibility while giving users control to customise.

**Comment by aaronrobertshaw** [comment]
Thanks for iterating on this PR @t-hamano 👍 

> Do you mean to add one padding as follows?

Yes, adjusting the padding to accommodate the margin that is removed in this PR allows us to keep the block visually the same.

> Set the top margin of the p element to zero

I raised this in my review; however, I didn't get the chance to test it then. As you noted, it works fine.

> The padding works perfectly, but would be a more breaking change.

Removing the top margin for the inner `p` keeps things positioned as they should be and are currently on trunk. I'm missing how this is more of a breaking change, sorry. 🤔 

Here's a diff that works for me and keeps the block's spacing and dimensions the same as on trunk. With these changes, we avoid the clunky inner margins, allow padding overrides and have the ability to remove padding entirely if so desired etc.

<details>
<summary>Example diff fixing inner spacing</summary>

```diff
diff --git a/packages/block-library/src/pullquote/block.json b/packages/block-library/src/pullquote/block.json
index 2cad2d2c03..e669955a4a 100644
--- a/packages/block-library/src/pullquote/block.json
+++ b/packages/block-library/src/pullquote/block.json
@@ -70,6 +70,14 @@
 			"typography": {
 				"fontSize": "1.5em",
 				"lineHeight": "1.6"
+			},
+			"spacing": {
+				"padding": {
+					"top": "4em",
+					"right": "0",
+					"bottom": "4em",
+					"left": "0"
+				}
 			}
 		}
 	},
diff --git a/packages/block-library/src/pullquote/style.scss b/packages/block-library/src/pullquote/style.scss
index 3100f595bf..f64e831a68 100644
--- a/packages/block-library/src/pullquote/style.scss
+++ b/packages/block-library/src/pullquote/style.scss
@@ -1,6 +1,5 @@
 .wp-block-pullquote {
 	margin: 0 0 1em 0;
-	padding: 3em 0;
 	text-align: center; // Default text-alignment where the `textAlign` attribute value isn't specified.
 	overflow-wrap: break-word; // Break long strings of text without spaces so they don't overflow the block.
 	box-sizing: border-box;
@@ -15,6 +14,14 @@
 		margin: 0;
 	}
 
+	p {
+		margin-top: 0;
+
+		&:last-child {
+			margin-bottom: 0;
+		}
+	}
+
 	&.alignleft,
 	&.alignright {
 		max-width: $content-width * 0.5;

```
</details>

| Before | After |
|---|---|
| Screenshot 2022-11-15 at 7 23 17 pm | Screenshot 2022-11-15 at 7 22 39 pm |

If I've missed something, let me know. 

---

> would it be possible to make the Pullquote block have a padding value in design tools as a default

@jameskoster we can define the default block padding via the block.json's `__experimentalStyle` prop as per the diff above. This gets merged with theme.json and global styles, so will appear as the "default" in global styles if nothing has already been set to override it. 

<details>
<summary>Screenshot of Global Styles > Blocks > Pullquote > Layout</summary>

Screenshot 2022-11-15 at 7 31 29 pm

</details>

It is worth noting, though, that it will _not_ show in the padding controls in the block editor. Unfortunately, we don't have access to the merged global styles there yet as we've discussed on other PRs. The PR to keep an eye on for that functionality is https://github.com/WordPress/gutenberg/pull/34178.

**Comment by t-hamano** [comment]
Thank you for your detailed suggestions, @aaronrobertshaw !

> Removing the top margin for the inner p keeps things positioned as they should be and are currently on trunk. I'm missing how this is more of a breaking change, sorry. 🤔

This may have been my unnecessary concern 😅 I have applied your suggestion and it seems to work generally well with some default themes.

On the left is `trunk` and on the right is this PR.

<details>
<summary>Twenty Twenty Three</summary>

The default margins for block quotes have been reset, so the left and right spaces are no longer present.

tt3

</details>

<details>
<summary>Twenty Twenty Two</summary>

The default margins for block quotes have been reset, so the left and right spaces are no longer present.

tt2

</details>

<details>
<summary>Twenty Twenty One</summary>

No change because the theme's padding and margins take precedence.

tt1

</details>

<details>
<summary>Twenty Twenty</summary>

No change because the theme's padding and margins take precedence.

tt0

</details>

For the classic themes **Twenty Twenty One** and **Twenty Twenty**, this change would not affect them because the themes have padding and margins.

For the block themes **Twenty Twenty Three** and **Twenty Twenty Two**, the default margins on the left and right side of the `blockquote` will disappear, but since we have the freedom to change the padding of the block support, we do not see a problem.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for iterating on this one @t-hamano and apologies for the slow reply.

The addition of padding and margin support is generally testing well for me.

> For the block themes Twenty Twenty Three and Twenty Twenty Two, the default margins on the left and right side of the blockquote will disappear, but since we have the freedom to change the padding of the block support, we do not see a problem.

I'm not sure what the best option is here. As you describe, removing the default left/right margins on the blockquote will make that quote text etc go right up to the very edge of the block. This might be undesirable if the block has a background color.

The alternative might be to add a default left/right padding but depending on theme styles etc that might introduce a touch extra space.

Perhaps we should get some design feedback or themes team input here before proceeding?

There have also been some cases lately where we've put PRs adopting spacing supports on ice as layout support breaks margin support under some conditions, e.g. nesting within a Row block.

**Comment by t-hamano** [comment]
Thanks for the feedback, @aaronrobertshaw!

> I'm not sure what the best option is here. As you describe, removing the default left/right margins on the blockquote will make that quote text etc go right up to the very edge of the block. This might be undesirable if the block has a background color.
> 
> The alternative might be to add a default left/right padding but depending on theme styles etc that might introduce a touch extra space.
> 
> Perhaps we should get some design feedback or themes team input here before proceeding?

Yes, I think you are right about this.

@WordPress/gutenberg-design 

Could anyone give us their opinion on this issue? 🙏 The key points of this PR are as follows:

- This PR adds padding/margin support to the pullquote block and at the same time changes the margin of the `blockquote` element inside to zero.
- In order to maintain the default top and bottom margin (`1em`) of the `blockquote` element, the top and bottom padding of the block is instead increased by `1em`.
- The left and right margins of the blockquote are also reset, so the left and right spaces disappear in the block theme, as mentioned in this comment.
- The focus is on whether to have default padding (perhaps `1em`) on the left and right. What is the best approach to maintain compatibility across many themes?

**Comment by jasmussen** [comment]
Great PR, thank you. Also a tricky one. Pullquote is a bit of an opinionated block, and in being out there, naturally has some back compat concerns to think about. 

In general I don't personally have a strong opinion about the left/right padding by default. From what I can telll, the padding doesn't exist today, but this PR adds it? Weirdly I'm seeing what appears to be the opposite effect testing in TT3. Before:
before

After:

after

On a separate note, when migrating towards theme.json configurable values, in general it's nice to see _fewer_ values in style.scss as a result, as those are always highly opinionated. In this case, the opposite happens, with more values. It may be fine since pullquote is by design an opinionated block, but nevertheless — a goal ideally is to make those rigid hardcoded values into user configurable ones.

So designwise, my opinion is this: the visual changes are fine, and the more we can make user configurable, the better. But ideally this comes at the reduction of hardcoded values.

But technically, I think the more tricky conversation here is on back compat. I'll refer to others on how to best handle that. 

Can the above thoughts help inspire a way to thread the needle?

**Comment by t-hamano** [comment]
@jasmussen 
Thanks for your comment, and sorry for the delay in responding.

> In general I don't personally have a strong opinion about the left/right padding by default. From what I can telll, the padding doesn't exist today, but this PR adds it? Weirdly I'm seeing what appears to be the opposite effect testing in TT3. Before:

The reason there is space on the left and right in trunk is that the `blockquote` inside has _margins_ instead of _padding_ on the left and right.

<details>
<summary>Blockquote has 1em margins on the left and right in the trunk post editor</summary>

post-editor

</details>

<details>
<summary>Blockquote has 40px margins on the left and right in the trunk site editor</summary>

site-editor

</details>

In this PR, the blockquote margins are all changed to zero, and as a result the left and right spaces disappear.

**Comment by t-hamano** [comment]
@aaronrobertshaw

In my search for a solution, I discovered a problem in the classic theme.

If the theme doesn't apply any styles regarding spaces to the Pullquote block, this PR causes the top and bottom spaces to completely disappear.

<details>
<summary>Trunk</summary>

trunk_classic

</details>

<details>
<summary>This PR</summary>

pr_classic

</details>

I expect the reason for this problem is that `__experimentalStyle` isn't applied to classic themes without `theme.json`. Am I understanding correctly?

If so, what about updating the CSS as before, without using using `__experimentalStyle`, in order to maintain backward compatibility as much as possible?

<details>
<summary>Suggested diff</summary>

```diff
diff --git a/packages/block-library/src/pullquote/block.json b/packages/block-library/src/pullquote/block.json
index e669955a4a..2cad2d2c03 100644
--- a/packages/block-library/src/pullquote/block.json
+++ b/packages/block-library/src/pullquote/block.json
@@ -70,14 +70,6 @@
                        "typography": {
                                "fontSize": "1.5em",
                                "lineHeight": "1.6"
-                       },
-                       "spacing": {
-                               "padding": {
-                                       "top": "4em",
-                                       "right": "0",
-                                       "bottom": "4em",
-                                       "left": "0"
-                               }
                        }
                }
        },
diff --git a/packages/block-library/src/pullquote/style.scss b/packages/block-library/src/pullquote/style.scss
index f64e831a68..fa3c741bff 100644
--- a/packages/block-library/src/pullquote/style.scss
+++ b/packages/block-library/src/pullquote/style.scss
@@ -1,5 +1,6 @@
 .wp-block-pullquote {
        margin: 0 0 1em 0;
+       padding: 4em 1em;
        text-align: center; // Default text-alignment where the `textAlign` attribute value isn't specified.
        overflow-wrap: break-word; // Break long strings of text without spaces so they don't overflow the block.
        box-sizing: border-box;
```

</details>

**Comment by jasmussen** [comment]
> Blockquote has 1em margins on the left and right in the trunk post editor
> Blockquote has 40px margins on the left and right in the trunk site editor
> In this PR, the blockquote margins are all changed to zero, and as a result the left and right spaces disappear.

Oh that's useful, thank you! Looks like those 1em margins come from common.css, which means it's wp-admin CSS bleed, i.e. not something we should design for. What are the margins on the frontend? Whatever that is, should probably inform the new default. Nice!

**Comment by aaronrobertshaw** [comment]
> I expect the reason for this problem is that __experimentalStyle isn't applied to classic themes without theme.json. Am I understanding correctly?

That's my understanding as well although it looks like [there is talk](https://github.com/WordPress/gutenberg/pull/43981#issuecomment-1254832676) about making sure these block styles are loaded for classic themes like presets and CSS vars are.  

There is also an open issue tracking the efforts to [absorb block CSS into the global styles mechanism](https://github.com/WordPress/gutenberg/issues/45198). However, looking at that issue it appears that in several cases, the `__experimentalStyle` additions in block.json ended up being removed.

I'm really not sure what direction we are supposed to be moving in here. Perhaps @oandregal and @scruffian might be able to share their wisdom?

**Comment by t-hamano** [comment]
Sorry for the delay in replying.

I checked #43981 and the issue of `__experimentalStyles` in the pullquote block was mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/43981#issuecomment-1253846432).

> This issue is wider than the button. Any block that uses __experimentalStyles won't have its styles shipped for classic themes. So far, they are the navigation and pullquote blocks. We need to make this API work for classic themes or revert it.

It might be better to hold off on the case of adding `__experimentalStyles` at the same time as padding/margin support, as is the case in this PR.

Or should we not use `__experimentalStyles` and add support first, leaving the styles in the CSS file once?

**Comment by jasmussen** [comment]
> It might be better to hold off on the case of adding __experimentalStyles at the same time as padding/margin support, as is the case in this PR.

Since the margins are coming from `common.css` and thus wp-admin, they were never intentional. Which means, sure, margin support _can_ come to this block, but that it should not be part of a solution, because it means the margins were the bug in the first place. Whatever margins are on the frontend, should nform the new default.

**Comment by oandregal** [comment]
> I expect the reason for this problem is that __experimentalStyle isn't applied to classic themes without theme.json. Am I understanding correctly?

I tested this PR and this is what I see:

- TwentyTwentyThree: the styles defined via `__experimentalStyle` are part of the `wp-block-pullquote-inline-css` stylesheet in the front.
- TwentyTwenty: the styles defined via `__experimentalStyle` are part of the `global-styles-inline-css` styles in the front.

It sounds like everything is working as expected on that front?

**Comment by t-hamano** [comment]
@oandregal 
Thanks for the test.

`__experimentalStyle` is output as part of `global-styles-inline-css` on the front, but not in the post editor.

tt0

Many default themes have padding applied to this block on the editor. Therefore, it does not matter if `__experimentalStyle` is not output to the editor. But in themes that rely on the core style, there will be a difference between the front end and the editor in terms of whether padding is applied or not.

Is this the intended behavior?

**Comment by oandregal** [comment]
@t-hamano Thanks for sharing. I've tested in the post editor and this also happens in `trunk` for the existing styles defined via `__experimentalStyle`. It needs to be looked at separately, and I've created an issue to track it https://github.com/WordPress/gutenberg/issues/46818

**Comment by t-hamano** [comment]
@oandregal 
Thank you for submitting the issue. If that issue is resolved, I believe it will remove our concerns about this PR. If there is anything I can do to help, please ping me.

**Review by aaronrobertshaw — COMMENTED** [review]
@t-hamano what's the plan for this PR? 

I believe the issue with `__experimentalStyle` hasn't been resolved yet (https://github.com/WordPress/gutenberg/issues/46818). Can we get away with removing the spacing changes to `__experimentalStyle` and adding the updated `padding` back to the block's stylesheet?

Giving that a quick test using `emptytheme` seemed ok. It still doesn't seem to be a perfect fit though.

**Comment by t-hamano** [comment]
@aaronrobertshaw Sorry for replying so late.

> Can we get away with removing the spacing changes to `__experimentalStyle` and adding the updated `padding` back to the block's stylesheet?

I think this approach makes sense. In the next few days, I'll be testing with different themes, including Emptytheme within several days, and will update this PR if necessary.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for chipping away on this one @t-hamano 👍 

I've given this another test and it's looking good.

🚢

**Comment by t-hamano** [comment]
@aaronrobertshaw Thanks for the review!

I tested it again and it seems to be working as expected with the main themes, so I would like to merge it.

**Comment by carolinan** [comment]
On a block theme with no custom spacing and no custom settings or styles on the pullquote block, the padding change is a visible change when the block is aligned.
Do we consider this acceptable or is the visual change too big?

6.4.3:
pullquote- in 6.4.3


6.5 / Gutenberg trunk
pullquote in 6.5

I know it looks a bit strange because the aligned blocks do not clear the alignment, but that is a separate issue.
Test content available at https://github.com/WordPress/theme-test-data/blob/master/64-block-test-data.xml

**Comment by t-hamano** [comment]
The visual change is due to overriding the browser's default margin applied to the blockquote element inside the block with zero.

It is possible to add about 1em of padding to the left and right of the block in place of the disappeared margin, but I think it would be difficult to maintain the appearance of all themes whether we add it or not. This is because the theme may already add padding to the left and right sides of the block, or change the margin of the blockquote element.

If we add padding to the left and right:

- ✅ If themes haven't applied any styles to this block: The visual changes will be reduced by the newly added left and right padding.
- ⚠️ If themes were only changing the margin of the blockquote element: The visual changes will occur as new padding is added to the existing margin.
- ⚠️ If themes applied only padding to the block: The visual changes will occur as the default margin of the blockquote element changes to zero.
- ✅ If themes were changing the padding of the block and the margins of the blockquote element: there will be no visual changes.

If we _don't_ add padding to the left and right:

- ⚠️ If themes haven't applied any styles to this block: The visual changes will occur as the default margin of the blockquote element changes to zero.
- ✅ If themes were only changing the margin of the blockquote element: there will be no visual change.
- ⚠️ If themes applied only padding to the block: The visual changes will occur as the default margin of the blockquote element changes to zero.
- ✅ If themes were changing the padding of the block and the margins of the blockquote element: there will be no visual changes.

I personally think the visual changes made by this PR are acceptable, what do you think?

**Comment by t-hamano** [comment]
Regarding this PR, it might be better to have a Dev Note. I suggest notes like below as part of the miscellaneous dev note, what do you think?

---

Pullquote block now supports padding and margin. At the same time, the browser default margin applied to the `blockquote` element inside the block has been reset to zero to ensure that padding values are applied accurately inside the block. Depending on themes, this effect may result in visual changes and the need to adjust padding or margin.

**Comment by carolinan** [comment]
Yeah I think that is the best alternative.

**Pull request merged**
