### PR TITLE
Shortcode Design Review

### LINKED ISSUE #1810: Update Shortcode design elements from design review
**Describe the bug**
From the design review with @iamthomasbishop:

- Top Label:
    - Use system font "sans-serif" for ios
    - Set font color to be `$gray` in light mode and `$gray-50` in dark mode
    - Increase margin between the label and input field

**Screenshots**
#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| Placeholder-iOS | iOS Dark - Placeholder |

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| iPad - Placeholder | iPad Dark - Placeholder |

#### Android
| Default |
|  :---:  | 
| Android - Placeholder |

#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| Static-iOS | iOS Dark - Static |

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| iPad - Static | iPad Dark - Static |

#### Android
| Default |
|  :---: |
| Android - Static |

#### iOS
| Default | Dark mode |
|  :---: | :---:  | 
| Selected-iOS | iOS Dark - Selected|

| iPad Default | iPad Dark mode |
|  :---: | :---:  | 
| iPad - Selected | iPad Dark - Selected |

#### Android
| Default |
|  :---: |
| Android - Selected |

**Additional context**
This is to make up for not performing design review before https://github.com/WordPress/gutenberg/pull/19534 was merged

### PR DESCRIPTION
**Pull request by chipsnyder**
## Description

Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1810

Updates the Shortcode block based on design review feedback:
- Modifies padding between block title and edit field
- Font of the block title
- Font color of block title in light and dark mode
- Font color of placeholder in light mode

## How has this been tested?

Done in Gutenberg Mobile Demo Android and iOS apps

1. Add a Shortcode block
2. Compare design with similar blocks. 

## Screenshots 

| Platform | Original | Updated |
| --- | --- | --- |
| iOS - Light | Screen Shot 2020-01-23 at 3 52 17 PM | Screen Shot 2020-01-23 at 4 26 21 PM |
| iOS - Dark | Screen Shot 2020-01-23 at 3 52 53 PM | Screen Shot 2020-01-23 at 4 25 50 PM |
| Android | Screenshot_1579815786 | Screenshot_1579815747 |

## Types of changes

Fixes style issues

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by chipsnyder** [comment]
@iamthomasbishop Here are the design updates we discussed.

**Comment by iamthomasbishop** [comment]
Changes are all looking good! Feel free to ship it! 🚢

**Review by koke — APPROVED** [review]

**Review by koke — COMMENTED** [review]
I noticed this after approving, but the block title is barely visible:

Simulator Screen Shot - iPhone 11 - 2020-01-27 at 12 57 30
Simulator Screen Shot - iPhone 11 - 2020-01-27 at 12 57 40

**Comment by chipsnyder** [comment]
Oh weird. I’ll double check this maybe something changed from when I did my screenshots and pulled mater

**Comment by koke** [comment]
🤔 That reminds me, git was complaining when trying to checkout your gutenberg-mobile branch, so I was using gutenberg-mobile develop with this branch. Maybe that's why I'm seeing something different

**Comment by chipsnyder** [comment]
@koke the problem was with me 😞. I had a commit that I didn't push. Will you check it again for me on your end?

**Comment by koke** [comment]
Looking good 👌

**Review by koke — APPROVED** [review]

**Pull request merged**
