### PR TITLE
added index to glossary

### PR DESCRIPTION
**Pull request by juanmaguitar**
## What?
Adding an index to the Glossary to provide easy access to an overview of all the terms covered in the Glossary

## Why?
To improve the usefulness of this page and convert it in a real source of truth for terms used in the Handbook

### CODE REVIEW

**Comment by apeatling** [comment]
If there more to follow up on here? When I render the markdown file here: https://github.com/WordPress/gutenberg/blob/960ba44a63ef9f89f7e2ee0f4ed4bc560e60db7f/docs/getting-started/glossary.md

the links all fail and don't point anywhere. I wonder if it could also be formatted in a better way?

**Review by apeatling — COMMENTED** [review]
If there more to follow up on here? When I render the markdown file here: https://github.com/WordPress/gutenberg/blob/960ba44a63ef9f89f7e2ee0f4ed4bc560e60db7f/docs/getting-started/glossary.md

the links all fail and don't point anywhere. I wonder if it could also be formatted in a better way?

**Comment by ndiego** [comment]
With the work being done on the [Developer Resources redesign](https://github.com/orgs/WordPress/projects/94/views/3), this page will get a Table of Contents, so perhaps this is not needed? It will look similar to the current Documentation pages: 

image

**Comment by juanmaguitar** [comment]
Closing this PR as per the comments above.

**Pull request closed without merging**
