### PR TITLE
Framework: Using the wordpress a11y package instead of the global

### PR DESCRIPTION
**Pull request by youknowriad**

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
Should we remove the dependency here?

https://github.com/WordPress/gutenberg/blob/acde984d7927b01e0d99809981ae7512a984fce3/lib/client-assets.php#L129-L134

Additionally / alternatively, we might consider how we plan to reconcile the `wp-a11y` script included in core currently with the now-packaged variant, and whether the two can be merged. Might be a topic for a JavaScript Office Hours discussion (cc @omarreiss)

**Comment by youknowriad** [comment]
@aduth Good catch and right, maybe this is the first package to be used from the packages repo in Core.

**Comment by youknowriad** [comment]
@aduth Do you think we should merge this since the core integration won't be resolved today?

**Review by aduth — APPROVED** [review]
Yes, especially since we're not clobbering the global at the moment anyways, just pulling direct from NPM.

**Pull request merged**
