### PR TITLE
Add anchor support to static blocks

### PR DESCRIPTION
**Pull request by youknowriad**
Related #21023

This PR adds anchor support to several blocks and updates the transforms to retain the attribute when transforming blocks.

the reasoning is:

 - id is supported by all DOM elements
 - it's an advanced config in the "advanced" section"
 - Several persons tweak the html to add these ids manually causing invalidation, this will prevent this kind of block invalidation.

**Notes**

I'd like to do the same for dynamic blocks too. Work around support flags for dynamic blocks is being done here #23007 We should circle back to the anchor support too once it lands.

**Testing instructions**

 - Test that you can set IDs to: paragraph, audio, video, button, buttons, column columns, code, preformatted, verse, image, galleries, cover, list, media and text, pullquote, quote, separator, spacer and table.
 - Converting between these blocks should retain the id.
 - Pasting HTML or converting to blocks should retain ids for these blocks.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@youknowriad This is great! Tested it locally, and it works as expected! 👍 

The only observation/suggestion I have is to maybe add `autoComplete="off"` to the `<TextControl />` for the anchor ID field:

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/hooks/anchor.js#L75

It would avoid interactions like this: (Chrome)

Screen Shot 2020-06-16 at 10 01 27 AM

**Comment by youknowriad** [comment]
Good suggestion @ItsJonQ Fixed.

**Review by mtias — APPROVED** [review]

**Comment by mtias** [comment]
Thanks for looking at this one. It makes sense to extend this support since people are already attempting to do it by hand and running into validation issues.

**Comment by paaljoachim** [comment]
This is very helpful! Thank you.

**Comment by bobeaston** [comment]
THANKS to all who helped get it this far!

**Pull request merged**
