### PR TITLE
# Paste **MarkDown**

### PR DESCRIPTION
**Pull request by ellatrix**
This adds MarkDown parsing to the paste handling if the posted content is plain text. It won't parse anything if you don't paste from a plain text editor.

~~This is a WIP... Still need to have a look how to handle inline text better and at the parsers available. Any suggestions? Showdown is is used by Ghost so I picked that for now.~~

### CODE REVIEW

**Comment by aduth** [comment]
What's the impact on bundle size by pulling in `showdown` ? Also curious if this is something best left for plugin territory...

**Comment by iseulde** [comment]
10.7 kb gzipped... I'm fine either way, I think this is a nice surprise enhancement. I mainly want to show here that it's easily possible to add, and that not everything would run through the parser, only plain text.

**Comment by dmsnell** [comment]
For cross-reference: https://github.com/Automattic/simplenote-electron/blob/77b4c41d6eea1e8200e2eb8de8b8bef7d90203e1/lib/note-detail.jsx#L15

**Comment by iseulde** [comment]
Okay, so this will now do *two* things.

1. We're going to look at the plain text the clipboard API is giving us if the HTML is plain. If the source (editor) is plain text, this will be more reliable than any HTML made up by the browser.
2. If we have some reliable plain text, then we convert any markdown in it. If the user pastes HTML, this will never run.

The PR uses showdown, but we can easily use anything else later of course.

**Comment by iseulde** [comment]
Merged after 👍 form @mtias and @dmsnell.

**Comment by aduth** [comment]
We should have updated `package-lock.json` here from the added dependency. `npm install` while running npm 5+ will introduce changes.

**Comment by aduth** [comment]
Updated in ff1ef2bda952208cac642bb3a73a1542cff81ce2

**Comment by iseulde** [comment]
Thanks @aduth! Sorry about that, wasn't aware of package-lock.

**Comment by aduth** [comment]
No worries, since we don't explicitly target the version of Node that comes bundled with npm5+ (until LTS release in October), we maybe shouldn't have the `package-lock.json` at all, but the niceties of 5+ are enough for me to want to run it anyways 😄

**Comment by youknowriad** [comment]
@aduth The `package-lock.json` locks only the dependencies of the dependencies since `5.1.0` which makes it useless IMO. (it's not the same as shrinkwrap or yarn.lock)

**Comment by aduth** [comment]
>`package-lock.json` locks only the dependencies of the dependencies since `5.1.0` which makes it useless IMO

That still seems like a pretty good benefit on its own, if you ask me. 

Part of it is that it's automatic, so it becomes a nuisance to be merely running `npm install` and having changes introduced. If we really didn't care, I'd want to find a way to turn that off.

But then, I saw what you'd referred to come past, but I'd have to think it still provides some benefit; surely they wouldn't make the thing useless? 😄 I'll have to do some reading over the weekend.

**Pull request merged**
