### PR TITLE
Migrate custom taxonomies test to Playwright

### PR DESCRIPTION
**Pull request by alvitazwar**
## What?
Based on https://github.com/WordPress/gutenberg/pull/38570, part of https://github.com/WordPress/gutenberg/issues/38851. Migrate [custom-taxonomies.test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/plugins/custom-taxonomies.test.js)
## Why?
See https://github.com/WordPress/gutenberg/pull/38570 for its background and rationale.

This is split into a new PR for easier review.

## How?
See https://github.com/WordPress/gutenberg/pull/38570 for the proposed migration steps.
## Testing Instructions
npm run test:e2e:playwright /test/e2e/specs/editor/plugins/custom-taxonomies.spec.js

## Screenshots or screencast 

https://user-images.githubusercontent.com/55917380/197025989-f329e438-7244-4ec2-ac61-2ada92d0d8cd.mov

### CODE REVIEW

**Comment by alvitazwar** [comment]
@Mamaduka  Can you please help me to review this PR?

**Review by Mamaduka — COMMENTED** [review]
@alvitazwar, let's do a similar refactoring for this test case as we did in #43964.

* Inline helper utility.
* Try to use role selectors whenever possible.

**Comment by alvitazwar** [comment]
@Mamaduka I addressed the feedback regarding the inline approach and use of role selectors. Can you please check?

**Comment by alvitazwar** [comment]
@Mamaduka  Can you please check again?

**Comment by Mamaduka** [comment]
@alvitazwar, can you [rebase this branch on top of the latest](https://developer.wordpress.org/block-editor/contributors/code/git-workflow/#keeping-your-branch-up-to-date) trunk? It should resolve the issue with CI.

**Pull request closed without merging**
