### PR TITLE
PR template: add before/after table

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Adds a Before/After table to the PR template in the screenshot section.

## Why?

* I'm a bit tired of having to write out the table structure all the time.
* People may not be aware that it's possible to use tables to display screenshots side-by-side.

## How?

Adds a Markdown table skeleton.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
If we go ahead with this PR, I feel a comment description may be necessary. One example is as follows. What do you think?

```
## Screenshots or screencast
<!-- If you would like to upload screenshots, please paste them in the table cells below, showing before and after this PR was applied. -->

|Before|After|
|-|-|
||| 
```

**Comment by ellatrix** [comment]
Or:

```
|Before|After|
|-|-|
|<!-- Before screenshot here -->|<!-- After screenshot here -->|
```

**Comment by t-hamano** [comment]
Personally, I think it would be easier to understand if there were both comments suggested by you and mine.

**Review by t-hamano — APPROVED** [review]
I've updated this PR according to [this comment](https://github.com/WordPress/gutenberg/pull/62739#issuecomment-2183305132), and as I believe this PR still makes sense, I would like to approve it.

**Comment by ellatrix** [comment]
Thanks @t-hamano, I've added a comment, also indicating that it's merely a suggestion and not a requirement when adding screenshots.

**Pull request merged**
