### PR TITLE
Don't break Visual Editor on undoing multi-delete

### LINKED ISSUE #3257: Can't undo multi-block deletion
## Issue Overview
Attempting to undo the deletion of a group of blocks will result in a breaking TypeError.

## Steps to Reproduce (for bugs)

1. Open the demo.
2. Multi-select a couple of blocks, whether with the cursor or shift+arrows.
3. Delete the selection, e.g. via BlockSettingsMenu. The blocks should disappear.
4. Request an undo, whether via the icon in Header or the keyboard shortcut.

## Expected Behavior

The deleted blocks should reappear.

## Current Behavior

Gutenberg crashes, a TypeError trace is found in the console.

screen shot 2017-10-31 at 12 07 18

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by mcsf**
## Description
Fixes #3257 

## How Has This Been Tested?

Tried reproducing parent issue.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Review by aduth — COMMENTED** [review]
Should we not be concerned that extent is falsey (i.e. that we're expecting a node reference to exist that doesn't?). I'm wondering if based on the lifecycle of mounting nodes that this ought to be changed to a `componentDidUpdate`; might be that we're expecting new nodes to mount, but they don't until after `componentWillReceiveProps` is called?

**Comment by mcsf** [comment]
> Should we not be concerned that extent is falsey (i.e. that we're expecting a node reference to exist that doesn't?). I'm wondering if based on the lifecycle of mounting nodes that this ought to be changed to a `componentDidUpdate`; might be that we're expecting new nodes to mount, but they don't until after `componentWillReceiveProps` is called?

I agree, and considered the same. My top priority was a quick fix that we could get in the impending 1.6; my bad for not making that clear. We could and should think of a deeper fix afterwards. Do you think that's a fair trade-off?

**Comment by aduth** [comment]
Okay, I suggest creating an issue so that it's not lost.

**Review by ellatrix — APPROVED** [review]

**Comment by mcsf** [comment]
> Okay, I suggest creating an issue so that it's not lost.

→ #3289

**Pull request merged**
