### PR TITLE
File Block: Add a deprecation for the button element class name

### PR DESCRIPTION
**Pull request by scruffian**
## What?
Adds a deprecation for the file block button element class name. I should have done this in https://github.com/WordPress/gutenberg/pull/41239.

## Why?
When we change the save function of a block we need to add a deprecation so that the new code knows how to interpret the old markup.

## How?
This just adds a copy of the save function and attributes of the block in the state they were in before https://github.com/WordPress/gutenberg/pull/41239.

## Testing Instructions
- Using WordPress 6.0, add a file block to a post
- Activate Gutenberg
- Reload the post editor
- Confirm that you see a block validation error:
Screenshot 2022-10-20 at 13 34 55
- Checkout this branch
- Confirm that the error is gone: 
Screenshot 2022-10-20 at 13 35 47

### CODE REVIEW

**Comment by ockham** [comment]
Thanks a lot @scruffian!

Would you mind maybe adding [test fixtures](https://github.com/WordPress/gutenberg/blob/3a227817b79f2d377a6114d546871a5fe1d3223a/test/integration/fixtures/blocks/README.md) to cover the deprecation? 😊

**Comment by t-hamano** [comment]
Thanks for the response!
I think the v2 migration was originally intended to take place after the v3 added by this PR.
Therefore, what about swapping v2 and v3?

**Comment by scruffian** [comment]
> Therefore, what about swapping v2 and v3?

Good idea, Done.

**Comment by glendaviesnz** [comment]
Tested well for me, have added a fixture to cover the new deprecation.

**Comment by ramonjd** [comment]
I created a file block using WordPress 6.0.1 (Gutenberg NOT activated).

Then I activated Gutenberg trunk and refreshed the editor.

A validation error occurred:

<details>

<summary>Validation error</summary>

```

Content generated by `save` function:

<div class="wp-block-file"><object class="wp-block-file__embed" data="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf" type="application/pdf" style="width:100%;height:600px" aria-label="Ethics go digital"></object><a id="wp-block-file--media-463819cf-9242-47dc-a7c8-00386f9d52b0" href="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf">Ethics go digital</a><a href="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf" class="wp-block-file__button wp-element-button" download aria-describedby="wp-block-file--media-463819cf-9242-47dc-a7c8-00386f9d52b0">Download</a></div>

Content retrieved from post body:

<div class="wp-block-file"><object class="wp-block-file__embed" data="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf" type="application/pdf" style="width:100%;height:600px" aria-label="Embed of Ethics go digital."></object><a id="wp-block-file--media-463819cf-9242-47dc-a7c8-00386f9d52b0" href="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf">Ethics go digital</a><a href="http://localhost:8888/wp-content/uploads/2022/10/Ethics-go-digital.pdf" class="wp-block-file__button" download aria-describedby="wp-block-file--media-463819cf-9242-47dc-a7c8-00386f9d52b0">Download</a></div>
```

</details>

Screen Shot 2022-10-21 at 1 07 00 pm

Switched to this branch and refreshed the editor:

Screen Shot 2022-10-21 at 1 08 33 pm

Looks good!


There is one [PHP failure](https://github.com/WordPress/gutenberg/actions/runs/3293920665/jobs/5430911565) that appears related to [this change:](https://github.com/WordPress/gutenberg/pull/45159/files#diff-9b5277b04530d6771d3442eb2b11aab6b668cb6a2ffa9dd4ab791299e4cad269)

```bash
1) Block_Fixture_Test::test_kses_doesnt_change_fixtures with data set #67 ('<!-- wp:file {"href":"http://... -->\n', 'core__file__no-text-link__dep...d.html')
Failed to match core__file__no-text-link__deprecated-2.serialized.html
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '<!-- wp:file {"href":"http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf","displayPreview":true} -->
-<div class="wp-block-file"><object class="wp-block-file__embed" data="http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf" type="application/pdf" style="width:100%;height:600px" aria-label="yolo"></object><a id="wp-block-file--media-dfca18cf-e92a-4954-878e-304512ad721f" href="http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf">yolo</a><a href="http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf" class="wp-block-file__button wp-element-button" download aria-describedby="wp-block-file--media-dfca18cf-e92a-4954-878e-304512ad721f">Download</a></div>
+<div class="wp-block-file"><object></object><a id="wp-block-file--media-dfca18cf-e92a-4954-878e-304512ad721f" href="http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf">yolo</a><a href="http://localhost:4759/wp-content/uploads/2022/10/yolo.pdf" class="wp-block-file__button wp-element-button" download aria-describedby="wp-block-file--media-dfca18cf-e92a-4954-878e-304512ad721f">Download</a></div>
 <!-- /wp:file -->
 '
```

The `<object />` is empty for some reason?

**Comment by glendaviesnz** [comment]
@ramon I can't work out why that unit test is failing so have removed the new fixture as more important to get the deprecation merged so it can go into 6.1. I have [added an issue to follow up and add the fixture separately](https://github.com/WordPress/gutenberg/issues/45185).

**Review by ramonjd — APPROVED** [review]
Works as advertised with the PHP unit test removed.

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: 307bfbaaa9

**Pull request merged**
