### PR TITLE
Post Comments block: Merge Comments Query Loop block

### LINKED ISSUE #40521: Post Comments block: Merge Comments Query Loop block
As per discussion with @mtias [here](https://github.com/WordPress/gutenberg/issues/34994#issuecomment-1103299112) and via DM, we should merge the Comments Query Loop block into the existing Post Comments block, with the following behavior:

- If it doesn’t have any child blocks: Use the current Post Comments behavior, i.e. render the “monolithic” WP `comment_form()`. In the editor, we’ll display [the placeholder](https://github.com/WordPress/gutenberg/pull/40484).
- If it has children: Use the Comments Query Loop behavior (i.e. render those child blocks).

If it’s newly inserted: insert child blocks as specified in its default template (as Comments Query Loop does already).

This means that the block will provide backward-compat for Post Comments (where it’s been used for existing themes); OTOH, it will provide the new functionality by default when newly inserted.

Quoting Matías:
> The important things:
> - Replacing the block not creating a new one so we keep the namespace.
> - That existing uses of the PHP comments don’t break.
> - That inserting the block for the first time in a template uses the new set of blocks.

Note that there will be some edge cases that can lead to slightly awkward user experience, e.g. trying to edit a previously inserted empty Post Comments block (will show a placeholder in the editor). Matías said not to worry about these for 6.0.

> The rest can be improved through iterations [after WP 6.0]
> Including a “convert to blocks” and the addition of some nicely designed patterns

cc/ @WordPress/frontend-dx @priethor @gziolo

### PR DESCRIPTION
**Pull request by ockham**
## What?
Merge the Comments Query Loop block into the Post Comments block.

## Why?
See #40521 for details.

## How?
TBD

## Testing Instructions
TBD

## Screenshots or screencast
TBD

### CODE REVIEW

**Comment by DAreRodz** [comment]
Some minor updates:

- @ockham added some code in https://github.com/WordPress/gutenberg/pull/40522/commits/e33997e8fabedefcf6c7d9f8f61303316300ae4c to render inner blocks from PHP.
- @luisherranz and I pushed https://github.com/WordPress/gutenberg/pull/40522/commits/570437dd94c29e87a12d7da132141d63deb94a3b and  https://github.com/WordPress/gutenberg/pull/40522/commits/8ace6c64c513e8e9d4d6db69abc00566d15fe41e to render inner blocks on the editor.
 
These two changes would solve all problems with the static-dynamic behavior.

I'll update the list of next steps that @ockham posted in the issue.

**Comment by luisherranz** [comment]
Added variation to inject the inner block template on block insertion.

https://github.com/WordPress/gutenberg/pull/40522/files#diff-c3f8b5a86aa52698e50024403d5f4e7a50206b840b45770262194ca30c72d686R21-R28

We are using this method because it was impossible to know when `innerBlocks.length === 0` was due to a new block, or due to a legacy block. _Props to @gziolo for the suggestion!_

**Comment by ockham** [comment]
If I create a (childless) Post Comments block (`<-- wp:post-comments /-->`) on `trunk` (i.e. with the block.json’s `"inserter": false` flag removed), save that, and then try to reload the editor on this PR’s branch, I get a warning message about invalid block content:

image (2)

The console shows

image (3)

I believe that this is because the merged block’s `save()` would generate the `<div />` with className `wp-block-post-comments`, but that’s not what’s stored in the post body (from when the block was first created on trunk).

I think the problem is that we’re unconditionally rendering the wrapping `<Tag />`: https://github.com/WordPress/gutenberg/pull/40522/files#diff-3a8f25d555bb48cf812311952459528f8dabbff12f35f07baf926d19e288ca32R8

I've tried to fix this with some logic as follows:

```diff
diff --git a/packages/block-library/src/post-comments/save.js b/packages/block-library/src/post-comments/save.js
index 94b8adfadc..d556d66621 100644
--- a/packages/block-library/src/post-comments/save.js
+++ b/packages/block-library/src/post-comments/save.js
@@ -1,12 +1,16 @@
 /**
  * WordPress dependencies
  */
-import { InnerBlocks, useBlockProps } from '@wordpress/block-editor';
+import { useInnerBlocksProps, useBlockProps } from '@wordpress/block-editor';
+import { Children } from '@wordpress/element';
 
 export default function save( { attributes: { tagName: Tag } } ) {
-	return (
-		<Tag { ...useBlockProps.save() }>
-			<InnerBlocks.Content />
-		</Tag>
-	);
+	const blockProps = useBlockProps.save();
+	const innerBlocksProps = useInnerBlocksProps.save( blockProps );
+
+	if ( Children.count( innerBlocksProps.children ) === 0 ) {
+		return;
+	}
+
+	return <Tag { ...innerBlocksProps } />;
 }
```

Notes:
- `InnerBlocks.Content` is basically just a wrapper around `useInnerBlocksProps.save()`, so those two are more or less equivalent (AFAICT).
- `{ Children } from '@wordpress/element'` is an alias for `React.Children`.

My patch isn't quite working yet: It seems that even with the childless Post Comments block, `Children.count( innerBlocksProps.children )` is always `1` -- there seems to be a `RawHTML` component inside 😕 

To be continued.

**Comment by ockham** [comment]
Per [discussion](https://github.com/WordPress/gutenberg/issues/40521#issuecomment-1109589648) on the issue, and due to the [problems](https://github.com/WordPress/gutenberg/pull/40522#issuecomment-1109046302) we've encountered, we've decided to stop working on this for now. We'll revisit after WP 6.0.

**Pull request closed without merging**
