### PR TITLE
Set Default state to media library for library button in image block

### LINKED ISSUE #41473: Add Image block, Initial state on popup incorrect.
### Description

Using the Image Block in Gutenberg, when selecting the Media Library option, the pop up starts on the Upload tab, not the Media Library tab. And also stays on the selected option, when closing and re-opening the pop up.

Screen Shot 2022-06-01 at 12 39 01 PM

### Step-by-step reproduction instructions

1. Create new post.
2. Add Image block.
3. Select Media Library to find image.
Screen Shot 2022-06-01 at 12 40 00 PM
4. Pop up dialog shows the Upload Files tab first.
Screen Shot 2022-06-01 at 12 41 03 PM
5. If Media Library tab is selected, on closing the pop up modal, on reopening, it stays on Media Library.. though the same happens if Upload Files tab is selected. Eg: It stays on selected state.
 

### Screenshots, screen recording, code snippet

gutenberg-image-upload-bug

### Environment info

WordPress 6.0 without Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by akasunil**
In Gutenberg Image Block, on click of 'Media Library' button it should open Media Library tab in Media Popup. Instead, it open last opened tab. It confusing for user when they specifically click Media Library button and end up on upload tab in media Popup.
## What?

Fixes #41473

## Testing Instructions
Please follow step by step instructions to test this PR.
1. Create new post.
2. Add Image block.
3. Click `Media Library` button.
4. Click on `Upload` Tab
5. Close Popup and click `Media Library` button.
6. Make sure it open `Media Library` tab in Dialog.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This tested well for me. Should we document the `mode` prop [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/media-upload/README.md).

**Review by glendaviesnz — APPROVED** [review]
Tested on Image, Gallery and Cover block and worked correctly on all. Thanks for this fix 🎉

**Comment by akasunil** [comment]
Thank you. [glendaviesnz](https://github.com/glendaviesnz).

**Comment by akasunil** [comment]
@Mamaduka Can you please review the PR. Thank you.

**Review by Mamaduka — COMMENTED** [review]
@sunil25393, it looks like this was already reviewed by @glendaviesnz. So I'm going to merge the PR.

**Comment by mburridge** [comment]
Added the Needs Dev Note label in case this needs a dev note (either individual or as part of a "misc" dev note) for WP 6.1 release.

**Pull request merged**
