### PR TITLE
List all dependencies when checking licenses in NPM 7

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

NPM 7 by default only prints the first level of dependencies but we need all of them for the `check-licenses` script. 

_Extracted from ["Changes in npm v7"](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major):_
> npm ls
>
> Extraneous dependencies are listed based on their location in the node_modules tree.
**npm ls only prints the first level of dependencies by default. You can make it print more of the tree by using --depth=<n> to set a specific depth, or --all to print all of them.**

## How has this been tested?

- `npm i -g npm@latest`
- `npm run check-licenses` (this command should show some warnings)

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
It looks correct.

Can you include a note in the CHANGELOG of the package updated?

**Comment by gziolo** [comment]
This file:
https://github.com/WordPress/gutenberg/blob/master/packages/scripts/CHANGELOG.md

Something like this should be enough:

```diff
## Unreleased
+
+ ### Enhancements
+
+ -   Make `check-licenses` compatible with npm v7 ([#28909](https://github.com/WordPress/gutenberg/pull/28909)).

## 13.0.0 (2021-01-21)
```

**Comment by fluiddot** [comment]
Thanks @gziolo for the reminder! I've just updated the `CHANGELOG` file.

**Comment by gziolo** [comment]
I added another commit, it needs a section to recognize this change as a minor version bump 😄

**Comment by fluiddot** [comment]
> I added another commit, it needs a section to recognize this change as a minor version bump 😄

Oops sorry, I forgot to add the the section, thanks for the fix 😊 !

**Comment by gziolo** [comment]
Thank you for the actual fix 😄

**Pull request merged**
