### PR TITLE
Move the insert dashicon to the icons package

### PR DESCRIPTION
**Pull request by youknowriad**
Moved the insert dashicon to the icons package, named it "plusCircle" and replaced all its usage (inserter essentially)

### CODE REVIEW

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Tested locally. The (+) icon is rendering and working as expected in the Block Editor inserter

**Comment by jasmussen** [comment]
Same as my comment in the other branch, is there a better name than plus circle? I'm leaning towards that name being good, because it's descriptive, but just making sure. What does material call their plus icons?

**Comment by youknowriad** [comment]
The material one is plus-circle-outline

**Comment by jasmussen** [comment]
Let's go with "plus-circle" for now, and if we get a need to have two styles we can redesign the plus circle and add another one when the time comes. Which I think is never.

**Pull request merged**
