### PR TITLE
Fix: Always use the latest version of NVM

### PR DESCRIPTION
**Pull request by aaronjorbin**
Currently the local dev enviornment pins to a 10 month old version of NVM, which means that when we say we are "updating NVM", it can easily be downgrading NVM. This adds a one line to get the latest version and use that.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
I didn't write or review this code so I'm not sure why we are using that version of NVM. A consistent environment is nice but in the case of NVM I'm fine with just using the latest version.

This gets 👍 from me, but @pento wrote that line and could perhaps explain the reasoning behind it? 🤷‍♂️

**Review by pento — APPROVED** [review]
I originally wrote it as a "here's a version that works" thing, but realistically, I don't expect our basic usage of NVM to cause back compat problems.

**Comment by shivapoudel** [comment]
@pento In windows environment, `rev` command won't exist. Can this utilize `grep` command?

**Comment by pento** [comment]
@shivapoudel: This script will likely become obsolete when #17004 is merged, so I don't think it'll be changed.

**Pull request merged**
