### PR TITLE
Components: ColorPicker: replace global shortcut event handlers with local ones

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

[Remove whitespace to review more easily.](https://github.com/WordPress/gutenberg/pull/34508/files?diff=split&w=1)

Related: #34498, #34500, #34503, #34505.

KeyboardShortcuts adds event handles globally, while these handlers could simply be added locally instead.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jorgefilipecosta** [comment]
Hi @ellatrix,

I noticed a regression previously I could move the color circle using arrow keys and now it does not seems to work:
Sep-02-2021 16-27-31


We have a redesign of the color picker in progress and the roadmap involves basically removing all the current component code https://github.com/WordPress/gutenberg/issues/34284 and using a third-party component. So if you prefer we can wait a little bit for the component update.

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @ellatrix,

I noticed a regression previously I could move the color circle using arrow keys and now it does not seems to work:
Sep-02-2021 16-27-31


We have a redesign of the color picker in progress and the roadmap involves basically removing all the current component code https://github.com/WordPress/gutenberg/issues/34284 and using a third-party component. So if you prefer we can wait a little bit for the component update.

**Comment by ellatrix** [comment]
@jorgefilipecosta It seems to work fine if I move focus to the slider with TAB, but clicking on the slider does not move focus to the slider for some reason.

**Comment by ellatrix** [comment]
> using a third-party component

Why are we replacing it with a third party component? What's wrong with the current one?

**Review by jorgefilipecosta — APPROVED** [review]
> @jorgefilipecosta It seems to work fine if I move focus to the slider with TAB, but clicking on the slider does not move focus to the slider for some reason.

Yes I retested and it seems to move it arrows so I guess we can merge 👍

**Comment by jorgefilipecosta** [comment]
> > using a third-party component
> 
> Why are we replacing it with a third party component? What's wrong with the current one?

Good question. I'm not inside of the reasons; I know that a redesign is planned, maybe using the third-party component makes the new design simpler to implement? 
The PR that added the new third-party component is https://github.com/WordPress/gutenberg/pull/33714, and the tracking issue for the task of replacing the component is here https://github.com/WordPress/gutenberg/issues/34284. I'm going to cc @ciampo in case @ciampo has some insights on why we are replacing the component.

**Comment by ciampo** [comment]
Thank you for the ping, @jorgefilipecosta !

We are not replacing the current ColorPicker with a third-party component; we are replacing it with a new, first-party version that aligns more closely with the design and the needs that were mostly outlined in the context of the Global Styles sidebar (see https://github.com/WordPress/gutenberg/issues/27331 for more context)

The new version of the `ColorPicker` already exists in https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/ui/color-picker, and the plan is to soon swap the version that is currently in production with this newer version (see the tracking issue for more details: https://github.com/WordPress/gutenberg/issues/34284)

Hope this clarifies your doubts! (cc'ing @mtias in case he wanted to add on top of my explanation)

I wonder if, since the current version of the ColorPicker should soon be replaced by the new one and then deleted, we should make any changes to it.

**Comment by ellatrix** [comment]
Let's merge this. I plan to deprecate the KeyboardShortcuts component. Even if this component will be removed eventually, I assume at some point the new color picker component will also need keyboard shortcuts, so this will help with showing how to do it.

**Comment by ciampo** [comment]
Makes sense — thank you for the explanation, @ellatrix!

**Pull request merged**
