### PR TITLE
Add boolean contentStyle and clientId check to Column Edit InnerBlocks

### PR DESCRIPTION
**Pull request by derekblank**
## What?
This PR adds a boolean check to values passed to the `<InnerBlocks />` component of [block-library/src/column/edit.native.js](https://github.com/WordPress/gutenberg/blob/33d84b036592a5bf31af05b7710f3b2b14163dc4/packages/block-library/src/column/edit.native.js).

Related items:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/5403
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/5387

## Why?
This is an attempt to provide a fix for https://github.com/wordpress-mobile/gutenberg-mobile/issues/5387, which investigates an issue reported via Sentry: `RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'b[W].width')`.

Currently, we have not found a way to replicate this issue in production. Based on the nature of the stack trace, it's possible that a width value may be `null` or `undefined` when being passed to `<InnerBlocks />`, and is possibly an unintended side-effect of internal React Native changes made in the [upgrade](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5193) between 0.66.2 and 0.69.4. Until a more specific resolution can be found, this fix is proposed as the user impact rate of this crash is currently 0.098%. The intent is that the boolean checks may prevent `null` or `undefined` values from being passed to other components, and if that is true, we would see the user impact threshold decrease in Sentry as evidence. 

## How?
Checks for both the value of `contentStyle` and `contentStyle[ clientId ]` before passing the `parentWidth` value to the component:

```
<InnerBlocks
    ...
	parentWidth={
		contentStyle &&
		contentStyle[ clientId ] &&
		contentStyle[ clientId ].width
	}    ...
/>
```

## Testing Instructions
1. Create a post
2. Add a Column block
3. Adjust the base settings of the Column layout in any way you prefer
4. Tap the gear icon to further edit Column settings as you prefer
5. App should not crash

### CODE REVIEW

**Review by geriux — APPROVED** [review]
LGTM! I agree including this change seems like the best option until we find out how to reproduce it or if there are other side effects from the React Native upgrade.

I tested this on both iOS and Android, I tried nesting Columns blocks and other blocks to check if there were no regressions, I also tested passing `undefined` as `parentWidth` and added some inner blocks and I found no issues. I also tested changing the alignments of the block.

**Comment by derekblank** [comment]
@fluiddot @dcalhoun Given that this change was cherry-picked into the [1.87.2 release](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5404) of Gutenberg Mobile, can this PR now be closed, or should we await the E2E test fixes?

**Comment by fluiddot** [comment]
> @fluiddot @dcalhoun Given that this change was cherry-picked into the [1.87.2 release](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5404) of Gutenberg Mobile, can this PR now be closed, or should we await the E2E test fixes?

@derekblank Yes, we can close this PR as this change was merged via https://github.com/WordPress/gutenberg/pull/47257.

**Comment by fluiddot** [comment]
> > @fluiddot @dcalhoun Given that this change was cherry-picked into the [1.87.2 release](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5404) of Gutenberg Mobile, can this PR now be closed, or should we await the E2E test fixes?
> 
> @derekblank Yes, we can close this PR as this change was merged via #47257.

@derekblank I've just noticed that [the commit that was cherry-picked in `1.87.2`](https://github.com/WordPress/gutenberg/pull/47257/commits/d142c7dcad039d6c3ecc089fc129e4e025d4acb3) didn't include the last change @geriux made in https://github.com/WordPress/gutenberg/pull/47234/commits/d36e05f54e33c0f8784d36e839400bcda4d22fec. The change didn't modify the logic as it was simply moving the code, so no further action is needed. However, it would be great to land this in `trunk`. I re-opened the PR so we can proceed with the merge.

**Comment by dcalhoun** [comment]
> @derekblank I've just noticed that [the commit that was cherry-picked in `1.87.2`](https://github.com/WordPress/gutenberg/pull/47257/commits/d142c7dcad039d6c3ecc089fc129e4e025d4acb3) didn't include the last change @geriux made in [d36e05f](https://github.com/WordPress/gutenberg/commit/d36e05f54e33c0f8784d36e839400bcda4d22fec). The change didn't modify the logic as it was simply moving the code, so no further action is needed. However, it would be great to land this in `trunk`. I re-opened the PR so we can proceed with the merge.

If I am not mistaken, the `1.87.2` release branch did include the referenced change in https://github.com/WordPress/gutenberg/pull/47257/commits/ade951a0fcd0b9ea0dd1fe21b308cc4ec4a4b9c9. It is also present in `trunk` in https://github.com/WordPress/gutenberg/commit/64c69123ea57a3c342475c8a72d274d4cf9764a3.

Closing this PR as it is no longer necessary. Feel free to reopen if needed. 🙇🏻

**Comment by fluiddot** [comment]
Oh, I overlooked that commit 🤦 , my bad. Yep, let's keep this PR closed, sorry for the noise 🙏 .

**Pull request closed without merging**
