### PR TITLE
Developer Docs: Add section on `useInnerBlocksProps` hooks

### LINKED ISSUE #46087: Docs: Rewrite nested blocks documentation with hooks
## What problem does this address?
Currently, the `useInnerBlocksProps` hook is used for blocks with nested blocks, such as group and column blocks. However, the Block Editor Handbook provides examples using `InnerBlocks`.

[Nested Blocks: Using InnerBlocks | Block Editor Handbook | WordPress Developer Resources](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/)

As far as I know, the only examples of using hooks are presented in the following article:

[Take more control over Inner Block Areas (as a block developer) – Make WordPress Core](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/)

## What is your proposed solution?
I believe that it would be better to update the documentation with the implementation using hooks as the standard.

### PR DESCRIPTION
**Pull request by t-hamano**
Closes #46087

## What?
~This PR rewrites the description of the `InnerBlocks` component in the Block Editing Handbook with a hook.~

This PR adds a section on the `useInnerBlocksProps` hook to the Nested Blocks page.

- [Nested Blocks: Using InnerBlocks | Block Editor Handbook | WordPress Developer Resources](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/nested-blocks-inner-blocks/)

## Why?
As noted in [this article](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/), WordPress 5.9 introduced `useInnerBlocksProps`, a new hook for implementing inner blocks.

The Block Editor Handbook explains how to use the `InnerBlocks` component, but in the core block, the hook is used for all inner block rendering, except for uses that control inserters such as `InnerBlocks.ButtonBlockAppender`.

Given that we have had two major releases since the hooks were introduced, we think it is a good time to explain the use of hooks as the default for developers.

## How?
~I searched the `docs/` directory with `InnerBlocks` (match case) and updated documents that I found. In particular, I explicitly added a space like "Inner Blocks" so that it would not be misidentified as a component.~

Changed to just adding examples of hook usage to the Nested Blocks documentation.

## Testing Instructions
To see the complete document as updated by this PR, please follow [this link](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md) to the markdown files.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think we should keep some documentation or reference for the `<InnerBlocks />` component but promote the `useInnerBlocksProps` hook. Maybe in [docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md) docs.

**Comment by t-hamano** [comment]
@Mamaduka 
Thanks for checking out this PR 🙂
Does this mean that only [nested-blocks-inner-blocks.md](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md) should be updated?

**Comment by Mamaduka** [comment]
Sorry for the late reply, @t-hamano.

Let's keep documentation for both `InnerBlocks` and `useInnerBlocksProps ` in [nested-blocks-inner-blocks.md](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md). We can use `useInnerBlocksProps` everywhere else.

**Comment by t-hamano** [comment]
Sorry for the delay, @Mamaduka.

I have added a _Using a react hook_ section to the Nested Blocks document and shown some example code based on the [Make WordPress Core article](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/). The markdown file is [here](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md#using-a-react-hook).

Would these changes be ok? If I have misunderstood, please let me know.

**Review by fabiankaegy — APPROVED** [review]
Thanks for adding this :)

**Comment by t-hamano** [comment]
@Mamaduka 
I would be glad if you could check to see if the sections I have added are what you expected.
The section I added is [here](https://github.com/WordPress/gutenberg/blob/doc/nested-blocks-with-hooks/docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md#using-a-react-hook) and [the original article](https://make.wordpress.org/core/2021/12/28/take-more-control-over-inner-block-areas-as-a-block-developer/) from which it was derived.

**Review by Mamaduka — APPROVED** [review]
Thank you, @t-hamano! The update looks good.

**Comment by t-hamano** [comment]
@fabiankaegy @Mamaduka 
Thank you for the review 👍

**Pull request merged**
