### PR TITLE
WIP: Try new api for in toolbar editing (and fix image block toolbar focus loss issue).

### LINKED ISSUE #23721: Improve UX of image crop/edit tools
**Is your feature request related to a problem? Please describe.**
The current flow of image edit tools within the Image block are great, though the experience using the controls could be improved to better indicate the available tools, as well as clean up the interactions.

**Current flow:** 
before

Notice how the "Insert Link" and "Crop" icon (the one pressed to trigger this edit flow) both disappear when the "Crop" icon is toggled. I almost think we should view the "Crop" icon as a toggle, instead of a "click it, it's gone" action step. 

It's also unclear what new set of relative image editing tools are available, now that we're editing the image. 

--- 
**Describe the solution you'd like:**
ScreenFlow

1. We switch the placement of the "Insert Link" and "Crop" icons, so that when the "Crop" icon is clicked and the "Insert Link" icon disappears (which again, is proper), the "Crop" toggle does not move from its current position. 

2. The "Crop" icon is switched to a toggle functionality, much like a number of other patterns used throughout the editor (i.e. the new + inserter at the top left, the settings sidebar toggle). 

3. Consider making the new icons/editing tools a "drawer" that slides out to reveal the additional tooling for editing the images. The styling in my prototype here resembles the new "dragging" indicator style, and makes it clear that these have been added to the toolbar for cropping/editing the image.

4. Update the "Aspect ratio" icon to be a bit more clear. 

5.  Bonus points: Move the "Zoom" RangeControl to live within the bounds of the editing experience, to not bounce/interfere with content below the currently manipulated image.

6. More bonus points: Currently we require pressing the "Apply" button to save any edits, but if you accidentally click outside of the block - any edits are reverted without any indication of what occurred. Perhaps we should consider auto-applying the image edits when the block is deselected. Potential flow would be to open the edit tools, configure however, then move on to the next. If that's the case, maybe we don't need the "Apply" button (though we'd need to test that UX).

### LINKED ISSUE #24676: Accessing image block's crop tools with keyboard results in focus loss
**Describe the bug**
If a user tries to access the image block's crop tools using only a keyboard, focus is lost making it hard/impossible to get to the tools.

**To reproduce**
1. Add an image block and upload an image to it
2. Shift tab to the image block's toolbar
3. Use right-arrow key to focus the 'Crop' tool and hit enter
4. Focus is lost, try getting back to the image block toolbar using the keyboard
5. When focus is back on image block toolbar, crop mode is no longer active

**Expected behavior**
When selecting 'Crop' focus is moved to the nearest place (probably the 'Zoom' button, but open to feedback from the accessibility team on this).

**Editor version (please complete the following information):**
- Tested with Gutenberg 8.8
- Mac OS Firefox

### PR DESCRIPTION
**Pull request by talldan**
Note: this PR currently includes the reversion changes from #25854. Ideally that will be merged first before this is code reviewed.

## Description

Fixes #24676, Fixes #23721, related #23375

Using the image block's crop tool from the keyboard resulted in a focus loss.

This PR fixes the issue, introducing a new in-toolbar editing system.

The system works like this:
- A new slot/fill is introduced `__experimentalBlockToolbarInlineEdit`.
- This slot is rendered in the `BlockPopover` as a sibling to the `BlockContextualToolbar`
- When a fill is rendered in this slot, an action is triggered that visually hides the block contextual toolbar (applying a classname to it) and the fill is displayed in a `PopoverWrapper`.

The advantage of this system compared to #23613 is that it doesn't require as many changes to the toolbar, the only change is an additional classname that hides the toolbar.

It also follows the advice provided by the @enriquesanchez and @afercia in using a popover for the content that 'replaces' the toolbar.

TODO: 
- [x] Improve styling
- [ ] Come up with a way to get the top toolbar working
- [ ] Improve DevEx, hide some of the implementation, possibly wrap this up in a component similar to `<Dropdown>`
- [ ] Ensure any new APIs are experimental
- [ ] Documentation

## How has this been tested?
Prerequisite: Ensure top toolbar is not active (this doesn't work yet for the top toolbar).
1. Add an image block and upload or choose an image from the media library
2. Shift tab to the toolbar and use the right arrow key to move to the crop button
3. Use space/enter to select the crop button, observe that crop tools are shown with focus moved to the first button
4. Press escape, observe that the crop tools are hidden and focus moves back to the crop button

Other things to test
- Cancel and Apply buttons work correctly
- Moving focus outside the crop tools should close them

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
@enriquesanchez Top toolbar mode for the in-toolbar editing idea is a bit problematic. The trouble is that all of this is considered one toolbar:
Screenshot 2020-10-07 at 2 02 00 pm

So we'd be proposing to hide everything shown in the screenshot above when the user enables crop tools.

A possible interim solution might be to use a normal popover for the crop tools when the top toolbar is active, it'd look a bit similar to the Heading block's options:
Screenshot 2020-10-07 at 2 07 33 pm

Though I think this would mean you end up with multiple popovers if you Crop and then change the Aspect Ratio or Zoom.

**Review by enriquesanchez — CHANGES_REQUESTED** [review]
This is looking good, @talldan! 🎉 Thank you!

I found a couple of issues during my testing.

1. The 'Apply'/'Cancel' buttons are not aligned with the rest of the image editing popover. A few pixels up should fix it.
 
Screen Shot 2020-10-08 at 15 54 37

2. I found it a bit disorienting that, coming from the block toolbar that uses the roving tabindex pattern, I can't move focus through the image editing options with my <kbd>Left</kbd> and <kbd>Right</kbd> keys. I assume this is happening because I'm technically no longer inside a toolbar and instead this is a popover, but I wonder if something can be done to match the behavior?

---

Other than that, this feels pretty good to my focus was preserved and predictable at all times 👍

**Comment by enriquesanchez** [comment]
>A possible interim solution might be to use a normal popover for the crop tools when the top toolbar is active

Ah, this is a tricky one. If it's not too much trouble, I'd love to give your suggestion a try and test to see how it feels and behaves. 

On the other hand, I wonder how much of an issue it'll really be if we hide the whole toolbar area. After all, the user is in the middle of an image editing operation and contextually they only need the image editing tools in that specific moment. I'm trying to think of a scenario where doing so will have a negative repercussion and I can't come up with anything. What do you think?

**Comment by tellthemachines** [comment]
What's the status of this? It would be good to get a fix for  #24676 into 5.6, but this PR is looking a bit feature-heavy for a backport, especially this close to RC1 😅 

Is there any simpler fix we could try?

**Comment by talldan** [comment]
@tellthemachines Sorry, I thought I wrote a response to this, but just re-checking and there's nothing here.

My feeling was/is that we should bump this to 5.7 because of the complexity (I don't think there's a simple fix). It is unfortunate that the bug will have been in both 5.5 and 5.6. I started working on a refactor of the image editing tools that should make any solution easier (https://github.com/WordPress/gutenberg/pull/27089), but even that is a fairly sizeable code change.

There are quite a lot of pieces that need to come together for this 'in-toolbar' editing thing to work. You're right, it's a big change and affects some important pieces in the editor:

1. Revert the previous attempt at this (https://github.com/WordPress/gutenberg/pull/25854)
2. Come up with a solution for how in-toolbar editing might work in top toolbar mode (https://github.com/WordPress/gutenberg/pull/25890#issuecomment-704719339).
3. Refactor the image editing tools to make the range of solutions wider (https://github.com/WordPress/gutenberg/pull/27089), this one is blocking my idea for the top toolbar.
4. Refine the API proposed in this PR. Finalise an implementation and ship it.

**Comment by tellthemachines** [comment]
Definitely let's push this to 5.7; we're in RC stage now so we should only be fixing regressions in 5.6.

**Comment by paaljoachim** [comment]
Can we get a status update?
Thanks.

**Comment by talldan** [comment]
I don't really have time to work on this at the moment. I've unassigned myself from the associated issues. The PR can be kept open as a draft in case anyone wants to reference it or take it over.

**Comment by Mamaduka** [comment]
Hi, @talldan 

Did the top toolbar problem get resolved via #31134?

P.S. How can I help to move things forward for this feature?

**Comment by talldan** [comment]
@Mamaduka Yep, I think that's resolved now. The top toolbar could now potentially behave the same way as the normal block toolbar.

I don't plan on picking this up again any time soon, so happy for someone else to take over or start fresh, and can assist with reviews or advice.

**Comment by Mamaduka** [comment]
Thanks for the reply, @talldan.

I can take over/start fresh in a week or two.

Reviews/advice would be much appreciated.

**Pull request closed without merging**
