### PR TITLE
Add a prop to RichText native to allow configuration of selection/caret color

### PR DESCRIPTION
**Pull request by SergioEstevao**
## Description

Allow the passing of the selectionColor downstream to the native rich text component.

## How has this been tested?

This can be tested using this PR in GB-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1776

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by mtias** [comment]
Is this meant to be a public API for rich-text?

**Comment by chipsnyder** [comment]
@mtias There was an open request to expose a mechanism to support changing the highlight and caret color in mobile: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1773

**Comment by mtias** [comment]
But wouldn't that be handled by a theme context rather than direct prop setting — which I don't expect block authors to do —?

**Comment by lukewalczak** [comment]
`this.props.selectionColor` is an additional, not required color (if not passed `selectionColor` is specified by a system). In most cases, it should have the same color as text within `RichText`, so imo it doesn't have to be handled by a theme context.

**Comment by lukewalczak** [comment]
I don't have a strong opinion about it, but since on web caret color is the same as text color, maybe `selectionColor` should be

`selectionColor={ this.props.selectionColor || (style && style.color) }`

**Comment by SergioEstevao** [comment]
> But wouldn't that be handled by a theme context rather than direct prop setting — which I don't expect block authors to do —?

@mtias At the moment because we still don't a have a proper way to style the components in mobile using themes (css on the web) we have a lot of properties like this that are set directly in the blocks: textColor, placeholderColor, etc. 
So this selectionColor prop is just like the above, and probably in the future can be remove from the wordpress RichText component and we can use a style/theme to set it.

**Comment by SergioEstevao** [comment]
> I don't have a strong opinion about it, but since on web caret color is the same as text color, maybe selectionColor should be
> selectionColor={ this.props.selectionColor || (style && style.color) }

If we do this change we will change the selectionColor on all the blocks we already have implemented to be black/gray instead of the current default light blue. I don't think this is something we want.

**Review by pinarol — APPROVED** [review]
LGTM!

**Pull request merged**
