### PR TITLE
Embed widget type.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Description
Embed widget type in widget controller to add extra context data on a widget. 

I thought about removing description and widget class, as this data in widget type controller, but I will leave this up to @TimothyBJacobs 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
The link relation should be `about` to match posts and post types.

**Comment by spacedmonkey** [comment]
> The link relation should be about to match posts and post types.

@TimothyBJacobs Done

**Comment by TimothyBJacobs** [comment]
Thanks! We also need to fallback to id if the is base is empty to account for reference widgets.

**Comment by spacedmonkey** [comment]
So we need to add?
``` 
$id = ( empty( $prepared['id_base'] ) ) ? $prepared['id_base'] : $prepared['id'];
```

**Comment by TimothyBJacobs** [comment]
That looks right to me.

**Comment by spacedmonkey** [comment]
Thoughts on this 
> I thought about removing description and widget class, as this data in widget type controller

@TimothyBJacobs

**Comment by TimothyBJacobs** [comment]
The client needs to be updated first to use the new endpoints #26086.

**Review by TimothyBJacobs — APPROVED** [review]

**Pull request merged**
