### PR TITLE
attempt to fix php unit tests (variations api change)

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

~~I don't know anything about this, maybe it works, maybe more adjustments are needed.~~

It works, PHP unit tests are passing.

### CODE REVIEW

**Review by joemcgill — APPROVED** [review]
This looks like the same approach @kt-12 was suggesting in #58072. If it unblocks tests, I think this approach is fine for now.

Long term, I think we should rethink the way this block is handling modifying variations when post or taxonomy types are modified, since it doesn't really make sense for variations on the server to be modified after the property is accessed, which really only happens once per request in order to provide data to the editor.

**Comment by ellatrix** [comment]
Oh, somehow I missed that PR

**Comment by kt-12** [comment]
@joemcgill @ellatrix  I have cross-checked. This does fix the issue, we can merge anyone of the PRs as both are the same.

On a side note - https://github.com/WordPress/gutenberg/pull/56100/files has changed the names of a couple of public functions. Doesn't Gutenberg depreciate the old function while adding a new one?

**Comment by joemcgill** [comment]
@kt-12 let's keep the discussion in this PR focused on fixing the unit tests for now. FWIW, I don't see any changed names in the PR you referenced but if there are concerns, we should discuss them in a separate issue, or in the original PR instead.

**Comment by kt-12** [comment]
> @kt-12 let's keep the discussion in this PR focused on fixing the unit tests for now. FWIW, I don't see any changed names in the PR you referenced but if there are concerns, we should discuss them in a separate issue, or in the original PR instead.

My bad - wanted to reference https://github.com/WordPress/gutenberg/pull/56100/files. Yes, let's discuss this separately.

**Comment by ellatrix** [comment]
@kt-12 Sorry, I enabled merge for this PR because the other had test failures at the time

**Comment by kt-12** [comment]
@ellatrix That's fine, in fact, you saved my time. I thought there was still some reference problem with the variable and was behind it. 
The real issue  was not converting `$variations` to a single array before merging which you did.

**Pull request merged**
