### PR TITLE
Latest post block iteration: featured image add.

### LINKED ISSUE #1594: Iterations on "Latest Posts" Block
_This description has been edited — please see issue history for older mockups!_

## Next steps

- Featured image support, in its own sidebar section.
	- [ ] Include core image size controls.
	- [ ] Include core alignment controls.
- Post content support, in its own sidebar section.
	- [x] Toggle on/off post content.
	- [x] When post content is toggled on, choose between excerpt or full post. (Am I missing a default core option? If it's just the two, maybe this should be a radio button instead).
	- [x] Slider to control excerpt length when the excerpt is selected.
- Post meta support, in its own sidebar section.
	- [x] Move "Display post date" into here. #13698 
	- [x] Add toggle to show/hide post author. #13698
- Organize settings
	- [x] Move "Order by" and "Category" into its own sidebar section, "Sorting and Filtering." #13698 
	- [x] Group "Number of posts" and "Columns" (when grid is selected) into their own sidebar section, "Display Settings." #13698 

## Why

In preparation for working on page templates in Gutenberg, we'll want a robust set of dynamic blocks that can be dropped into any post or page. Expanding this block will put us in a better position to tackle more complex dynamic or global blocks in the future.

Users shouldn't have to know how to write custom queries or understand the loop to add some posts to their homepage. The Recent Posts block is a great start, but to be a fully functioning solution, it needs to support more than titles and post dates.

### Before

image

image

### After

recent posts list all

recent posts grid all

- Added support for featured images, post content and excerpts, and post meta.
- Reorganized the sidebar settings into groups.
- Used the new Toolbar grouping design (unsure if this has been implemented yet).
- Updated the icons, but this is optional, we can continue using the existing Dashicons for now.

[View the complete prototype](https://wp.invisionapp.com/share/BNPZUYGYMZ8#/341120336_Recent_Posts-_List).

## Future iterations

h/t @paaljoachim for a couple of these suggestions:

- Expand on taxonomy offerings, like tags.
- CPT support.
- A way to update the "read more" text.
- A way to rearrange all the elements inside of the block — move up meta, move featured image below title, etc.
- Potentially display comment information (like # of comments).

## Note to new contributors

This issue itself is big but can be divided into smaller tasks which should be a great way to start contributing to Gutenberg with code. If you want to help please leave a comment and we will discuss what would be the best next step.

### PR DESCRIPTION
**Pull request by v9ai**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/1594

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by nicolad** [comment]
Have reused some logic as [suggested](https://github.com/WordPress/gutenberg/issues/1594#issuecomment-501677095) by @gziolo from @ajitbohra's [PR](https://github.com/WordPress/gutenberg/pull/13698/files).

**Review by Soean — CHANGES_REQUESTED** [review]
Thanks for the PR. You also have to add this feature to the PHP file, otherwise the image will not be rendered on the frontend.

**Comment by nicolad** [comment]
> Thanks for the PR. You also have to add this feature to the PHP file, otherwise the image will not be rendered on the frontend.

Sure, this will be the next focus, now this PR is still a WIP.

**Comment by paaljoachim** [comment]
Hi @nicolad 

Can we get a status update on where this PR is at the moment?
Thanks.

**Comment by nicolad** [comment]
> Hi @nicolad
> 
> Can we get a status update on where this PR is at the moment?
> Thanks.

Hey @paaljoachim 
It's ready for review now.
Thanks for chiming in  :+1:

**Comment by melchoyce** [comment]
Hey, have y'all also seen https://github.com/WordPress/gutenberg/pull/17151?

**Comment by paaljoachim** [comment]
I noticed that Riad checked out the other Latest Post Block: featured image feature. So I believe what is important here is just comparing both and figuring out where to take it from there.

**Comment by mapk** [comment]
I was able to test this briefly, but after making a couple settings changes in the block's settings like number of posts... I am now continually getting this error.

Screen Shot 2019-11-20 at 5 36 46 PM

I delete the block and try readding it, but keep getting the same error. I've even tried on different posts, etc., but same error.

**Comment by mapk** [comment]
Because this appears to be stale, I've removed it from the 5.4 project board and going with https://github.com/WordPress/gutenberg/pull/17151 instead. Because there is active work on the other one, let's close this as well.

**Pull request closed without merging**
