### PR TITLE
Increase WordPress minimum to 5.2.0

### PR DESCRIPTION
**Pull request by Soean**
## Description
In WordPress 5.2 the [PHP minimum was updated](https://wordpress.org/news/2019/04/minimum-php-version-update/) to PHP 5.6.20.

Gutenberg is a feature Plugin for WordPress development. We should set WordPress 5.2 as minimum, so we can remove old PHP compatibility code and tests for old versions.

Related #15796 and #15806

### CODE REVIEW

**Comment by youknowriad** [comment]
We discussed this a little bit here https://github.com/WordPress/gutenberg/issues/15565 and there seemed to be an agreement to use `5.1` as a minimum for the moment. What do everyone thinks about moving directly to `5.2`. It probably doesn't hurt to wait a few more weeks.

cc @jeremyfelt @aduth @WordPress/gutenberg-core

**Comment by nerrad** [comment]
Having usage stats on what wp versions people are using would be helpful here.

With that said, I think its a reasonable assumption that most folks using the plugin understand what it is and are more _likely_ to be on the latest WordPress (or wouldn't have to much issue with getting on the latest WordPress).

**Comment by Soean** [comment]
Thanks for your feedback.

I understand that we should not increase the minimum too early. But it should also be a goal that users update their WordPress version promptly and don't remain on the same version. If users update their plugins, they are also able to update their WordPress Core.

Yoast recently released a [blog post](https://yoast.com/supporting-older-versions-of-wordpress/) about this topic, in the future they only support the current and the previous major WP version.

This is a feature plugin, so I think we can update the minimum supported version maybe even faster.

Gutenberg 5.9 would be June 12th. (More than a month after WordPress 5.2) or we wait for Gutenberg 6.0 after WordCamp Europe?

**Comment by aduth** [comment]
> Yoast recently released a [blog post](https://yoast.com/supporting-older-versions-of-wordpress/) about this topic, in the future they only support the current and the previous major WP version.

A takeaway I like from this is to have a policy about it, so it's known and predictable.

It's unclear what benefit there is in waiting? Or in supporting older versions at all? Conversely, there is some benefit in not waiting, as noted by referenced issues of the original comment (removing "baggage").

**Comment by youknowriad** [comment]
Yes, documenting this process would be great. It's not the first time we have a discussion about this. Let's have it once and make it a no brainer for the future.

**Comment by gziolo** [comment]
In #18414, I also see a change in the config file for PHPUnit:
https://github.com/WordPress/gutenberg/blob/1e359a8d467b23c33c664f6c277c2549866be2dd/phpcs.xml.dist#L6

I think Travis file doesn't run PHP 5.2 and 5.3 anymore:
https://github.com/WordPress/gutenberg/blob/master/.travis.yml

**Comment by Soean** [comment]
@gziolo Thanks, I added the change to this PR.

**Review by youknowriad — APPROVED** [review]
Let's do that in the next plugin release and maybe even consider 5.3 soon.

**Pull request merged**
