### PR TITLE
[WP 6.2] Rename experiments package to private-apis 

### PR DESCRIPTION
**Pull request by adamziel**
## What?

This PR targets the wp/6.2 branch

Renames the @wordpress/experiments package to @wordpress/private-apis to avoid confusion between internal APIs and experimental APIs. See https://github.com/WordPress/gutenberg/issues/47785

## Testing Instructions
Confirm the checks pass

cc @youknowriad @mcsf @peterwilsoncc @ntsekouras

### CODE REVIEW

**Comment by adamziel** [comment]
@Mamaduka @ntsekouras @gziolo Any idea why this fails? The failures say:

> npm ERR! path /home/runner/work/gutenberg/gutenberg/node_modules/@wordpress/private-apis/package.json
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open 
> '/home/runner/work/gutenberg/gutenberg/node_modules/@wordpress/private-apis/package.json'

The PR targeted for Trunk works (except for mobile tests): https://github.com/WordPress/gutenberg/pull/47839

Is the CI pipeline for the 6.2 branch special in any way?

**Comment by Mamaduka** [comment]
@adamziel, CI pipelines should be the same. Are there any prerequisites for the change? Those will need to be backported.

**Comment by adamziel** [comment]
@Mamaduka thanks! There should be no pre-requisites, this PR only renames the `experimental` package to `private-apis`. I'll continue to debug tomorrow.

**Comment by Mamaduka** [comment]
I get the same error when running `npm ci` locally.

**Comment by youknowriad** [comment]
All PRs should target the regular trunk branch and with the "backport label", we have workflow in places to backport this when doing the package releases... (Unless there's a very specific reason for this PR that I'm missing)

**Comment by youknowriad** [comment]
Oh I just saw that there's already a PR that targets trunk. I'm not understanding why we need two PRs then? What am I missing?

**Comment by peterwilsoncc** [comment]
> Oh I just saw that there's already a PR that targets trunk. I'm not understanding why we need two PRs then? What am I missing?

I think the plan in trunk is to add the gutenberg conditional mentioned in https://github.com/WordPress/gutenberg/issues/47785#issuecomment-1420608384 

My suggestion was to limit 6.2 to renaming, and add the Gutenberg conditional in trunk. Fewer changes to the published packages during beta, etc, etc.

If you're happy to the rename in one PR for trunk, and add the gutenberg conditionals in another then that works too. I'm not sure how possible that is though as I rarely publish NPM packages.

**Comment by youknowriad** [comment]
Understood, what ever make sense for you. Personally I'd have done the addition of conditions in its own dedicated PR.

**Comment by ntsekouras** [comment]
I also believe we should have on PR on trunk only to rename. And handle the other changes in different PR.

**Comment by gziolo** [comment]
Something went wrong in this PR:

Screenshot 2023-02-08 at 08 58 22

I see a few README files with content removed.

I'm afraid that it won't work without additional changes if you move `packages/experiments` to `packages/private-apis/experiments`:

Screenshot 2023-02-08 at 09 02 58

In a few places, we assume that all WordPress packages are located directly in the packages folder, not its subfolders.

**Comment by adamziel** [comment]
> All PRs should target the regular trunk branch and with the "backport label", we have workflow in places to backport this when doing the package releases... (Unless there's a very specific reason for this PR that I'm missing)

@youknowriad I prepared a dedicated PR mostly to save @ntsekouras and @Mamaduka the effort of resolving merge conflicts – I tried cherry-picking the branch targeting `trunk` and there were a lot of conflicts.

> Something went wrong in this PR:

@gziolo yup, I'm looking into this now.

**Comment by adamziel** [comment]
@ntsekouras @Mamaduka this is ready for merging 🎉  There's also [a trunk-based version](https://github.com/WordPress/gutenberg/pull/47839) – feel free to choose whether you'd prefer to merge both PRs separately, or close this one and cherry-pick the other one.

**Comment by adamziel** [comment]
> Understood, what ever make sense for you. Personally I'd have done the addition of conditions in its own dedicated PR.

This PR doesn't add the conditions @youknowriad. It only renames the package. Actually, I wasn't planning on spinning a PR to add the conditions – they're already supported and don't need any additional pull requests. Now it's up to API authors to use them. I will only start a Pull Request to update the coding guidelines accordingly.

**Comment by peterwilsoncc** [comment]
> Understood, what ever make sense for you. Personally I'd have done the addition of conditions in its own dedicated PR.

I'm really happy either way. To be 100% honest, I had a really dumb moment when I first asked for separate PRs and didn't even think of doing the rename and exports in trunk across two tickets.

@adamziel Sorry if that dumb moment ends up wasting your time.

**Comment by ntsekouras** [comment]
Let's close this one and back port https://github.com/WordPress/gutenberg/pull/47839 instead :)

**Pull request closed without merging**
