### PR TITLE
Lodash: Remove completely

### LINKED ISSUE #52545: Handbook: Update Block Hooks reference examples to not use lodash
## What is your proposed solution?

Remove lodash as a requirement for these examples:
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/

### PR DESCRIPTION
**Pull request by tyxla**
## What?

This PR removes the last Lodash usage from Gutenberg. 🎉 

Fixes #52545.

## Why?
Lodash is known to unnecessarily inflate the bundle size of packages, and in most cases, it can be replaced with native language functionality. See these for more information and rationale:

* https://github.com/WordPress/gutenberg/issues/16938#issuecomment-602837246
* https://github.com/WordPress/gutenberg/issues/17025
* https://github.com/WordPress/gutenberg/issues/39495 

## How?
We're doing some ESLint cleanup, updating some docs, and removing the Lodash dependency.

## Testing Instructions
Verify all checks are green.

### Testing Instructions for Keyboard
None

## Screenshots or screencast 
None.

### CODE REVIEW

**Comment by t-hamano** [comment]
Thanks for your great job 🎉 I just wanted to ask, am I correct that when this PR is merged, it will remove `lodash` from all Gutenberg package dependencies?

If so, for example, if a developer developing a custom block uses `lodash`, does he need to replace it with a native function or explicitly install `lodash` in his project?

**Comment by tyxla** [comment]
> I just wanted to ask, am I correct that when this PR is merged, it will remove `lodash` from all Gutenberg package dependencies?

Well, to be precise, #52561 removed `lodash` as a dependency from the last package that was utilizing it. This PR removes it from the entire repo, including the root dependency, developer documentation, and ESLint configuration.

> If so, for example, if a developer developing a custom block uses `lodash`, does he need to replace it with a native function or explicitly install `lodash` in his project?

FWIW, a developer working on a custom block outside of Gutenberg always needed to either:

* **Add `lodash` as a dependency** to their project and import it to use it - but then, it would be added to the vendor chunk or the project bundle, increasing the total bundle size
* **Enqueue `lodash` in WordPress and use the `wp.lodash` global variable** - since blocks are intended to work in a WordPress context, Lodash can be enqueued and utilized in more than 1 block. By using the global variable, a developer can share the same Lodash instance with the rest of the blocks and the administration.

Removing Lodash as a dependency from Gutenberg doesn't change any of that, and the above 2 still remain. The change matters for Gutenberg and its core blocks and features, and is best experienced by apps and external parties that utilize the `@wordpress` packages directly. Provided that they don't require `lodash`, they'll benefit from a bundle size improvement, since they won't need to load Lodash anymore. This is explained in more detail [in this comment](https://github.com/WordPress/gutenberg/issues/16938#issuecomment-602837246).

But then it's worth noting that most of the Lodash functions no longer need to be used - modern JavaScript can natively support most of what Lodash provides. So I'd strongly question any custom block that actually needs to use Lodash.  

Hope that helps, but please let me know if I can further clarify any of the nuances above.

**Comment by t-hamano** [comment]
@tyxla 

Thank you for the detailed explanation! I have personally developed custom blocks that use Lodash functions and will try to remove them.

**Comment by tyxla** [comment]
In the meantime, this PR is ready for a review 👀

**Comment by tyxla** [comment]
> I have personally developed custom blocks that use Lodash functions and will try to remove them.

Nice - let me know if I can help with any of that - feel free to start a [discussion](https://github.com/WordPress/gutenberg/discussions) and don't hesitate to ping me there! 

The migration took some time but now at its end, I'm fully convinced that in 2023 Lodash is an unnecessary burden.

**Review by t-hamano — APPROVED** [review]
This PR looks good to me 🎉

- ✅ The code example in the reference guide seems to be correct
- ✅ Unit tests for the `dependency-extraction-webpack-plugin` package also pass successfully.
- ✅ If I add the import of a `lodash` function to your code, eslint will output an error as before

My concern is that `lodash` and `@types/lodash` are still in the project's package-lock.json. I'm not familiar with npm package dependency management in Gutenberg projects, but These depend on external libraries (not Gutenberg packages) so they cannot be removed, is it correct?

**Comment by tyxla** [comment]
> My concern is that lodash and @types/lodash are still in the project's package-lock.json. I'm not familiar with npm package dependency management in Gutenberg projects, but These depend on external libraries (not Gutenberg packages) so they cannot be removed, is it correct?

That's a valid observation, but from what I've seen before, these usages are in Storybook, or other tooling that's not directly exposed to the end user, so those shouldn't be significant concerns. In the following weeks, I'll be keeping an eye on what else in the wp-admin uses lodash and finding opportunities for cleaning up. 

Thanks for taking a look, @t-hamano 🙌

**Pull request merged**
