### PR TITLE
Do not provide a default value for the link color property

### PR DESCRIPTION
**Pull request by oandregal**
In https://github.com/WordPress/gutenberg/pull/30541 we moved from providing a fallback to the link color such as:

```css
a {
  color:var(--wp--style--color--link, #00e);
}
```

to directly set the CSS Custom Property:

```css
body {
  --wp--style--color--link: #00e;
}
a {
  color:var(--wp--style--color--link);
}
```

This is: `--wp--style--color--link` moved from being undefined unless the theme or the user set it to always being defined. While this works fine for themes with theme.json support, some themes without theme.json may use the `--wp--style--color--link` in this way:

```css
a {
  var(--wp--style--color--link, <theme_value>);
}
```

It'll be used if it has a value and fallbacks to the theme color if it doesn't. This is what TwentyTwentyOne does.

## What this PR does

It reverts back that change so the link color CSS Custom Property is undefined if the theme or user didn't set it. It provides the fallback value as before.

```css
a {
  color:var(--wp--style--color--link, #00e);
}
```

## How to reproduce the bug

- Install TwentyTwentyOne.
- Activate Gutenberg 10.6
- Visit a post that contains links

The expected behavior is that the link color is `#28303d`, which is the value `--global--color--primary` resolves to. Instead, it is the default link color.

## How to test

Follow the instructions above and verify that it works as expected.

Test with a theme with theme.json and verify that link color still works (set the link color via `styles.elements.link.text` or as a user via the global styles sidebar in edit site).

### CODE REVIEW

**Comment by vdwijngaert** [comment]
Can confirm this fixes the issue. I can't do a review, because I'm not sure what other things might be affected by this change.

## release/10.6.0
image

## fix/link-color-no-default
image

**Comment by carolinan** [comment]
Tested without problems using emptytheme (both theme.json and experimental-theme.json version 1) by adding
```
"styles": {
		"elements": {
			"link": {
				"color": {
					"text": "red"
				}
			}
		}
	}
```

settings.color.link is also set to true.

**Comment by oandregal** [comment]
I've pushed a change https://github.com/WordPress/gutenberg/pull/31755/commits/e9a643e066dc79d107c45f3b03a317380eead5a0 so that the default value is available, just not as the default value for the property. It makes this PR essentially a revert of that change in the PR that introduced the bug. Updated the issue description.

**Comment by oandregal** [comment]
Ok, tested this with a variety of themes (with and without theme.json) and it's working as expected. Going to go ahead and merge it so we can release a patch version.

**Pull request merged**
