### PR TITLE
Backport "pull request automation use regular npm install"

### PR DESCRIPTION
**Pull request by getdave**
## What?

Backport of https://github.com/WordPress/gutenberg/pull/66314/.

## Why?

Because CI is failing `npm install` on the `wp/6.7` branch. 

See discussion in WP Slack https://wordpress.slack.com/archives/C02QB2JS7/p1729680379803689.

## How?

Manual backport. 

## Testing Instructions

Deferring to @sirreal to double check this makes sense.

### CODE REVIEW

**Review by sirreal — APPROVED** [review]
This looks correct to me 👍 

Other release branches may experience the same issue.

This workflow was fragile because it was effectively configured on one commit in a way that relied on the state of the repo in another commit. This change should make it less fragile.

**Comment by sirreal** [comment]
Strange. That error on CI is exactly what was observed previously that was fixed by the same change in #66314.

I'll investigate soon…

**Comment by kevin940726** [comment]
The failing workflow is running on the `pull_request_target` event.

> This event runs in the context of the base of the pull request, rather than in the context of the merge commit, as the pull_request event does.

That is, the workflow is still the old one on `wp/6.7`, not the updated one in this PR. I think the failure is expected. We might just have to merge this to see if it works.

**Comment by sirreal** [comment]
Good spot @kevin940726, that would explain why this fix didn't work on the branch 🙂 

I maintain that this change should be merged to `wp/6.7` to fix the issue 👍

**Comment by sirreal** [comment]
This was tested with https://github.com/WordPress/gutenberg/pull/66457 and it seemed to work correctly.

**Pull request merged**
