### PR TITLE
test: Fix editor history link test

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?

Repair the failing editor history link test that logged errors.

## Why?

Cover regression-prone features with automated tests.

## How?

**test: Fix React prop typo**
The `testID` typo was the root cause for test failures.

**test: Simplify test queries**
The targeted elements do not require asynchronous queries. Using
synchronous queries is more concise and easier to comprehend.

**test: Increase editor history link test accuracy**
The targeted bug occurs when:

1. Changing a link to "Open in a new tab."
2. Performing additional changes, e.g. typing.
3. Undoing both actions.
4. Redoing both actions.

Thus, this changes the initial HTML, adds additional undo/redo
invocations, and updates inline snapshots to match the expected
outcomes.

## Testing Instructions

n/a

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 
n/a

### CODE REVIEW

**Comment by dcalhoun** [comment]
👋🏻 @derekblank. These changes result in a passing test without errors; the PR description and individual commits explain the nuance changes to achieve this. 

Unfortunately, I do not believe it accurately tests the spirit of the bug fix: editor history actions after redoing changes to a link's `target` are not lost. If you revert the [fix itself](https://github.com/WordPress/gutenberg/pull/50460/commits/c908c06a950b0a402e72704bba82f58986c333e5), you can observe that the test fails due to the relocation of the `rel` property. This is expected, however, I also anticipated the second sentence to be missing entirely in the final snapshot, i.e. the "lost" editor history. 

It is unclear to me if the test needs a different structure or this test subject is not achievable via integration test because it originates from a mocked module, more specifically, Aztec. My thought is that it is the latter, as I am able to manually reproduce the bug with the steps in the automated test. This bug may require an e2e test until we replace Aztec entirely. 

WDYT?

**Comment by dcalhoun** [comment]
The failing Unit Tests task appears to be due to the log of a warning message: `Browserslist: caniuse-lite is outdated.` This also occurs in `test/fix-editor-history-link-test`, but not in the latest `trunk` branch. So, I anticipate this failure will be resolved once the latest from `trunk` is merged into `test/fix-editor-history-link-test`.

**Comment by derekblank** [comment]
> These changes result in a passing test without errors; the PR description and individual commits explain the nuance changes to achieve this.

@dcalhoun Thank you very much for taking a look and applying the fixes. 🙇 

> Unfortunately, I do not believe it accurately tests the spirit of the bug fix: editor history actions after redoing changes to a link's target are not lost.

I agree that the test does not fully capture the full bug behavior on its own due to limitations with integration test capability, and would likely be better captured with an E2E test. 

> If you revert the [fix itself](https://github.com/WordPress/gutenberg/pull/50460/commits/c908c06a950b0a402e72704bba82f58986c333e5), you can observe that the test fails due to the relocation of the rel property. This is expected, however, I also anticipated the second sentence to be missing entirely in the final snapshot, i.e. the "lost" editor history.

Precisely -- within the app, the relocation of the rel attribute appears to be the cause that fires the extra state event, as mentioned [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2091#issuecomment-662212872). The mechanics of this extra state event are not yet understood without deeper investigation, but the root cause is possibly within Aztec, as you mentioned. The [fix itself](https://github.com/WordPress/gutenberg/pull/50460/commits/c908c06a950b0a402e72704bba82f58986c333e5) does appear to rectify the issue for the end user. While the integration test can capture that the rel attribute does not shift, the observation that the "lost" editor history is not lost in the integration test reinforces that an E2E test would be better suited.

**Comment by derekblank** [comment]
> The failing Unit Tests task appears to be due to the log of a warning message: Browserslist: caniuse-lite is outdated. This also occurs in test/fix-editor-history-link-test, but not in the latest trunk branch. So, I anticipate this failure will be resolved once the latest from trunk is merged into test/fix-editor-history-link-test.

I merged the latest from trunk into this branch. I believe it caused the commit history mess due to not having merged the latest from trunk into the target branch, [rnmobile/fix/undo-redo-history](https://github.com/WordPress/gutenberg/tree/rnmobile/fix/undo-redo-history) -- apologies. I think cherry-picking the three original commits you added to the target branch and closing this PR may be the best approach, and then the discussion/work for the remaining E2E testing approach and utility of the integration test can continue on the target PR. WDYT?

**Pull request closed without merging**
