### PR TITLE
Add block variations page to Block API summary

### PR DESCRIPTION
**Pull request by JustinyAhin**
Fixes https://github.com/WordPress/gutenberg/pull/29663#issuecomment-795204088

### CODE REVIEW

**Comment by JustinyAhin** [comment]
Hi @ntsekouras.

This PR fixes the issue you mentioned here https://github.com/WordPress/gutenberg/pull/29663#issuecomment-795204088.

**Review by ntsekouras — APPROVED** [review]
Thanks for the fix 👍 - I pushed an addition to the Reference Guides as well.

**Comment by JustinyAhin** [comment]
> Thanks for the fix 👍 - I pushed an addition to the Reference Guides as well.

I'm seeing two "Block Patterns" there

**Comment by ntsekouras** [comment]
Oops :) - sorry about that and thanks for updating 💯

**Pull request merged**
