### PR TITLE
Colors: Remove unused color panel files

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related: 
- https://github.com/WordPress/gutenberg/pull/31438

## What?

Removes unused files.

## Why?

The only use of these color panel files was removed in #31438.

There is a `ColorPanel` used within Gutenberg however this is separate and defined alongside the color block support hooks.

## How?

- Searched for imports and use of the component
- Deleted files.

## Testing Instructions

1. Search for any use of the deleted files
2. Bonus points for ensuring all color controls work e.g. block supports, Cover overlay, Social Links icon colors etc.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Thanks for removing the unreached code @aaronrobertshaw!

✅ Double-checked that the files aren't being imported from anywhere
✅ Double-checked that the `components/index.js` file isn't exporting them via its `*` export, by using the following snippet in that file:

```js
/*
 * Block Creation Components
 */

export * from './colors';

import * as myColors from './colors';
console.log( 'myColors', myColors );
```

image

I suppose an argument could be made that now that there are no comonents inside `components/colors`, we could potentially looks at moving the files in this directory down to the `utils` directory. But that could happily be in another PR, I think.

LGTM!

**Comment by aaronrobertshaw** [comment]
> I suppose an argument could be made that now that there are no comonents inside components/colors, we could potentially looks at moving the files in this directory down to the utils directory.

Good idea. I was clearly blinded by the opportunity to submit a PR that only removed code 🙈 

> But that could happily be in another PR, I think.

Sounds good. I'll put together a follow-up.

**Comment by andrewserong** [comment]
> I was clearly blinded by the opportunity to submit a PR that only removed code

Always great when we you can find places to trim down the repo! 🎉

**Comment by aaronrobertshaw** [comment]
> I suppose an argument could be made that now that there are no comonents inside components/colors, we could potentially looks at moving the files in this directory down to the utils directory.

@andrewserong I'm cleaning up some loose ends here and I think we could make an argument that the HoCs still under `components/colors` constitute components so I'm not sure about moving the related utils. What do you think?

**Comment by andrewserong** [comment]
Oh, that's a good point @aaronrobertshaw, sounds good to leave it there, then!

**Pull request merged**
