### PR TITLE
Add panel button props

### PR DESCRIPTION
**Pull request by joshuatf**
## Description
Adds `buttonProps` to `PanelBody` to allow modifying the button state/props for panel toggles.

## How has this been tested?
Verified manually via storybook and added tests for addition of props.

1. Run `npm run storybook:dev`
2. Check that the final section of Panels->Multiple bodies is disbled.
3. Make sure additional tests are passing.

## Screenshots 
Screen Shot 2021-01-12 at 4 04 34 PM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ntsekouras — COMMENTED** [review]
Hey @joshuatf - thanks for working on this.

What is the reason for wanting this? Because your example is about `disabled` which isn't so common I think. For example I think we wouldn't render a Panel at all instead of disabling it.

Having said that, if there are use cases, I think we shouldn't name it `buttonProps` and at the end of destructure in `PanelBody` we should gather all the rest properties like this: `...props` and then pass them on to `PanelBodyTitle` that applies them in the `Button`.

**Comment by joshuatf** [comment]
Thanks for the review @ntsekouras.

We’re using these props in the linked PR above ( https://github.com/woocommerce/woocommerce-admin/pull/5970 ) to disable a toggle that has no content. This is both an accessibility issue and UI issue for us.

I can't speak to how common this is, but preventing an empty panel from being toggled is better in our case than simply removing the panel body.  I can see other use cases for this as well, such as passing custom `onClick` handlers or adding accessibility labels to the button. 

I’m not sure renaming this to `props` is the best move. This is not a very accurate name as it implies props to the parent component  (`PanelBody`) and opens the door for prop conflicts in the child component (`PanelBodyTitle`), which already exist with `icon`, `className`, and `children`.

**Comment by ntsekouras** [comment]
Hey @joshuatf - we can go with `buttonProps` but it needs to be added to `readme` file.

**Comment by joshuatf** [comment]
Good call @ntsekouras, added in https://github.com/WordPress/gutenberg/pull/28147/commits/f8070422302e56a0f8ff499c33a985c07c3207c8.

**Review by ntsekouras — APPROVED** [review]
Thanks! 👍

**Pull request merged**
