### PR TITLE
Fix global styles updating in style book.

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes a regression introduced in the style book by  #67811, where changing styles in the global styles UI doesn't update the style book styles.

## Testing Instructions

1. With a block theme enabled, navigate to "Styles" in the site editor.
2. Click "Style book" in the content area to show the style book.
3. Change some styles in global styles (e.g. global background color), and check that they update correctly in the style book.

## Screenshots or screencast 

|Before|After|
|-|-|
|||

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Thanks for the quick fix!

**Comment by ramonjd** [comment]
Sorry, I just found an anomaly in this branch with the background panel:

Screenshot 2024-12-19 at 4 15 00 pm

Let me have a quick look. It might be some logic problem with the background panel component itself 🤔

**Review by ramonjd — APPROVED** [review]
> Sorry, I just found an anomaly in this branch with the background panel:

I'm seeing things, sorry. Retested and LGTM

**Comment by jasmussen** [comment]
Thank you for this 🙏

**Pull request merged**
