### PR TITLE
Adds links to REST-API reference

### LINKED ISSUE #36846: Improve docs around getEntityRecord query filters
## What problem does this address?

`getEntityRecord` is a very important method. However it does not have much documentation.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-core-data/#getentityrecord

The main area I'd like to clear up is that, unlike it's pluralised cousin `getEntityRecords`, the `query` parameter of `getEntityRecord` does not actually allow you to filter the query by things such as `status = publish`. This is because it's querying a specific record by ID.

We should clear that up by improving the documentation.

### PR DESCRIPTION
**Pull request by mburridge**
## What?

Adds links to the REST API reference to find query parameters available for `getAuthors`, `getEntityRecord`, `getEntityRecords`, and `hasEntityRecords`.

## Why?

Closes https://github.com/WordPress/gutenberg/issues/36846

### CODE REVIEW

**Review by ryanwelcher — CHANGES_REQUESTED** [review]
Changes look good to me, however, I believe you'll need to make these changes in the doc blocks themselves and then re-generate the docs using the `docs:build` command.

This is why the static analysis failed in the checks.

**Comment by mburridge** [comment]
🤦‍♂️

**Review by ryanwelcher — CHANGES_REQUESTED** [review]
The changes look good. However, I don't know if there should be a package-lock.json in the changeset. Perhaps revert that file?

**Comment by mburridge** [comment]
> The changes look good. However, I don't know if there should be a package-lock.json in the changeset. Perhaps revert that file?

It appeared in the changed files after running `npm run docs:build` so I assumed the build process had made a change to package-lock.json so I included it. Are you sure I should revert that?

**Comment by ryanwelcher** [comment]
> It appeared in the changed files after running npm run docs:build so I assumed the build process had made a change to package-lock.json so I included it.

Did you run an `npm install` at some point before doing the build? Typically, this file isn't modified by running a script. 

> Are you sure I should revert that?

I always revert it locally before pushing changes,. If you're not making changes to the packages, etc so there shouldn't be any reason this fill needs to be committed.

**Review by ryanwelcher — APPROVED** [review]
LGTM!

**Pull request merged**
