### PR TITLE
[Navigation link block][Try] Show a URL next to the link icon

### PR DESCRIPTION
**Pull request by adamziel**
## Description

As in the title. Solves #22836.

**Before:**

Zrzut ekranu 2020-06-9 o 13 28 21

**After:**

## How has this been tested?
1. Enable the navigation experiment in Gutenberg > Experiments
1. Go to Gutenberg > Navigation (beta)
1. Add a menu item with no link, confirm there is no text next to the link icon in the toolbar
1. Attach a link to that menu item, confirm there link shows up next to the link icon in the toolbar

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by adamziel** [comment]
@shaunandrews I updated this PR to reflect your suggestions. I wasn't entirely sure about the icon part so at the moment it's in a sort of intermediary state where the icon is there for new links:

Zrzut ekranu 2020-06-12 o 17 29 27

But as soon as you assign a URL, it's replaced by that URL:

Zrzut ekranu 2020-06-12 o 17 27 35

What do you think would be a proper way to address it?

> This brings up a lot of questions around the connection between this button in the toolbar, and the Link UI. Part of me wonders if I should be able to edit the URL directly within the Toolbar and not need to open the Link UI.

I'm totally up for exploring that - a mockup would be more than enough to get me started. It seems like figuring out the icon would be the key here - clicking on an icon just to have it replaced by an input would be weird.

**Comment by adamziel** [comment]
A lot more work is required, but an initial attempt is functional:

Zrzut ekranu 2020-06-23 o 14 04 36

**Comment by shaunandrews** [comment]
Taking a closer look at the design for this over in #23375.

**Comment by adamziel** [comment]
I took the latest design from https://github.com/WordPress/gutenberg/issues/23375 and got an early prototype of interactions working:

85568280-d61b7d80-b631-11ea-8986-fc8842862970

There are still some visual glitches and keyboard navigation needs a closer look, but I'd like to get some early broad strokes feedback on the direction @shaunandrews @noisysocks @talldan @draganescu.

**Comment by adamziel** [comment]
I will put this PR on hold for now - the design discussion is still going

**Pull request closed without merging**
