### PR TITLE
Post Featured Image: Add border support applied to inner img

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related: 
- https://github.com/WordPress/gutenberg/pull/42765

## What?

Adopts border block support for the Post Featured Image block and applies those classes/styles to the inner `img` element.

## Why?

This is a step towards reducing the gap between what you can control with the Image block and the Post Featured Image block. In terms of the bigger picture, it is part of providing more consistent design tools across blocks.

## How?

- Opts into border block support
- Skips serialization of the border block support so classes and styles can be applied on the inner `img` instead of the block wrapper
- Uses new "feature-level" selector flag to allow Global Styles and Theme.json to generate their styles targeting the inner image
- Leverages the style engine to generate the border classes and styles to be applied to the block during server-side rendering.
- Borders are also applied to the block's placeholder

## Testing Instructions

1. Edit a post, add a Post Featured Image block, and select it.
2. Trial configuring various combinations of borders on the block. The borders should display correctly.
3. Save and confirm the borders display on the frontend.
4. Back in the block editor, clear your block's border styles and save.
5. Switch to the site editor and navigate to Global Styles > Blocks > Post Featured Image > Layouts.
6. Try configuring the border options there and check they are reflected in the preview. 
7. Save the global styles and confirm they are applied in both the block editor and frontend.
8. Reset your global styles and add a default border for the Post Featured Image block in your theme.json
9. Confirm the theme.json border works appropriately.

##### Example snippet

```json
	"styles": {
		"blocks": {
			"core/post-featured-image": {
				"border": {
					"color": "fuchsia",
					"width": "0.5em",
					"style": "solid",
					"radius": "50px"
				}
			}
		},
	},
```

## Screenshots or screencast 

<details>
<summary><strong>Post Editor - With Image</strong></summary>

<video src="https://user-images.githubusercontent.com/60436221/182126495-d8198ebe-7db9-4788-8125-f078bc8c7fe2.mp4" />
</details>

<details>
<summary><strong>Post Editor - Placeholders</strong></summary>

<video src="https://user-images.githubusercontent.com/60436221/183343439-d0045dd4-872d-4f40-8256-f3b1426972d0.mp4" />
</details>

<details>
<summary><strong>Site / Template Editor</strong></summary>

<video src="https://user-images.githubusercontent.com/60436221/183343449-da1b348c-8410-4e75-b93b-00e580be49e1.mp4" />
</details>

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
This should be pretty close to reviewable, I've run out of time today to test fully but will do that later this week.

**Comment by jameskoster** [comment]
Nice! This is working well for me. 

Would it be possible to also apply the styles to the placeholder you find in the template editor when a featured image isn't set, or when no context is passed?

Screenshot 2022-08-01 at 11 41 52

**Comment by aaronrobertshaw** [comment]
> Would it be possible to also apply the styles to the placeholder you find in the template editor when a featured image isn't set, or when no context is passed?

It should be possible. I'll take a run at it later this week.

**Comment by aaronrobertshaw** [comment]
> Would it be possible to also apply the styles to the placeholder you find in the template editor when a featured image isn't set, or when no context is passed?

I've explored applying borders to the Post Featured Image's placeholder and run into a few issues that make it a bit of a clunky fit.

#### Theme.json / Global Styles
To display any borders set via theme.json or global styles on the placeholder, we'd need to add an editor-specific selector to the block.json config, which would also result in that selector being included in the CSS generated for the frontend. This is minor, but it might add up if we intend to do this for every image-related block or any block supporting borders but using a placeholder.

#### Block specific borders
For borders set via block support, we can manually apply these to the placeholder. The downside is that the application of the border can really detract from it appearing as a placeholder. 

To achieve this cleanly, we'd need to update the way `MediaPlaceholder` calls its `renderPlaceholder` callback also to pass wrapper props in addition to the placeholder content. This might be better done in a follow-up PR. A short-term alternative is to slightly duplicate the placeholder markup in the feature image block's `edit.js` so it can access the required block attributes and generated border styles.

Another UX issue here is the default placeholder styles define `border-style: none`, which forces a user to have to select a border style to see a visual border on the placeholder. This makes the experience of configuring a border a little different between when there's a placeholder displayed and an actual image. Some extra editor-only CSS leveraging `:where` might help smooth this out though.

<details>
<summary>Example of borders detracting from placeholder</summary>

https://user-images.githubusercontent.com/60436221/182775238-116786ca-1182-4b36-97ee-2ceaa3d8d1c2.mp4

</details>

#### Image Block
The Image block does not apply borders to its placeholder state. I appreciate that the use cases here are a little different but given the similarities between the blocks, should they be consistent?

---

Before investing too much time here, I'd like to double-check how desirable applying borders to the placeholder actually is. I'd also be happy to continue exploring this in a follow-up.

**Comment by jameskoster** [comment]
> I'd like to double-check how desirable applying borders to the placeholder actually is

I think it's pretty important. Not so much in the post editor, but in the template editor – where this block is going to see more use – definitely. If I'm designing my Single template and would like to add a border to the featured image, I'm going to want to see a preview of that border on the canvas. 

I don't find the border detracting from the placeholder to be a big deal. The diagonal dashed line is the key visual indicator so as long as that's partially visible most of the time then we should be ok. 

> Another UX issue here is the default placeholder styles define border-style: none

It's probably not out of the question to update the placeholder design a bit to better accommodate the border controls. Since this could be a bit tricky to get right, a follow-up may make more sense.

**Comment by aaronrobertshaw** [comment]
@jameskoster I've updated this PR to apply the border styles to the block's placeholder. 

It's mostly there except for a small issue around the border radius for the placeholder's SVG. If I make the SVG inherit the placeholder's border radius (current state of this PR), depending upon that value and the width of the border, we get a small gap between the placeholder border and the SVG's.

Screen Shot 2022-08-08 at 2 57 11 pm

An alternative was to clip the SVG by setting `overflow: hidden` on the placeholder's wrapper. This looked a bit worse. Another option might be to look into calculating an adjusted border radius for that similar to how the search block's border radius works when the button is positioned inside. I think that would be better suited to a follow-up to this PR.

**Comment by jameskoster** [comment]
@aaronrobertshaw could we remove the placeholder border together if one is added via the border control? 🤔

**Comment by aaronrobertshaw** [comment]
> could we remove the placeholder border together if one is added via the border control? 🤔

So I'm on the same page, the "placeholder border" to me is the blue border in the screenshot in my [earlier comment](https://github.com/WordPress/gutenberg/pull/42847#issuecomment-1207678135). The dotted border is on the placeholder's inner SVG. Am I correct in assuming it is that dotted border you are asking if we can remove if a border is set?

We could if the border is added at the individual block level however that is more problematic when the borders are added via Global Styles or theme.json. In those cases, the border styles are applied via a generated stylesheet. In the block editor, for example, we don't have access to this data short of getting computed styles.

**Comment by jameskoster** [comment]
>  Am I correct in assuming it is that dotted border you are asking if we can remove if a border is set?

Yes.

> We could if the border is added at the individual block level however that is more problematic when the borders are added via Global Styles or theme.json. In those cases, the border styles are applied via a generated stylesheet. In the block editor, for example, we don't have access to this data short of getting computed styles.

That sounds like it won't be possible? 

Making the radii match would be acceptable I think (in a follow-up like you mentioned). Alternatively we could explore different design approaches to the placeholder that do not use a border.

**Comment by jasmussen** [comment]
This is damn sweet. Let's for sure land this for 6.1. Here's a status with the border radius issue as discussed above:
status

I tried a trick that I think solves it:

trick

What do you think? It feels solid to me. This is the trick:

```
		// Inherit border radius for dashed placeholder.
		> svg {
			border-radius: inherit;
		}

		// Hide dashed border entirely when a border is set.
		&:where([style*="border-width"]:not([style*="border-style: none"])) {
			overflow: hidden;
			> svg {
				border-style: none;
				border-radius: 0;
			}
		}
```

You can paste that on line 108 in editor.scss. Let me know what you think.

**Comment by jasmussen** [comment]
Inspired by excellent work here, I've started #43143 to do the same for the Image block. 

I would be grateful for some help in porting over some of the inheriting features from this PR. The opportunity to refactor the placeholder component, or just componentize the dashed-line variant, is also increasingly becoming clear. Probably doesn't have to happen now, but it'd be a nice optimization at some point now that we're using this style across both Featured Image, Image, and Site Logo.

**Comment by aaronrobertshaw** [comment]
Thanks for the enthusiastic reception as well as taking a look at this one @jasmussen, appreciate it 👍 

> What do you think? It feels solid to me. This is the trick:

Unfortunately, there are a few issues with the suggested CSS. Which is actually a subset of what I had in mind with my https://github.com/WordPress/gutenberg/pull/42847#issuecomment-1208762531.


> We could if the border is added at the individual block level however that is more problematic when the borders are added via Global Styles or theme.json. In those cases, the border styles are applied via a generated stylesheet. In the block editor, for example, we don't have access to this data short of getting computed styles.

The main issue is that when border styles are generated via theme.json or global styles, we'll end up with something like the following in the generated stylesheet:

```css
.wp-block-image img,
.wp-block-image .block-editor-media-placeholder {
    border-style: solid;
    border-color: #00000;
    border-width: 5px;
}
```

The border isn't applied by a custom CSS class or style attribute so I'm unaware of any means to conditionally style the inner SVG based upon that. A primary use case raised earlier was setting a global style so featured image blocks within the query block in the site editor would display with a border. In such a scenario we'd still get the misaligned borders.

The second, easily solvable issue, with the proposed CSS is that it only covers flat borders as opposed to those applied to individual sides e.g. top and bottom borders only etc (`border-top-width`).

---

I'm hoping to have a little time to experiment further with the placeholder today. One thing I'll try is to perhaps absolutely position the SVG and give it the same border, to essentially overlay it on the placeholder wrapper.

**Comment by jasmussen** [comment]
Ah, thanks for the clarity, I had a feeling. 

Another option is to draw the dashed border on the placeholder component instead of the SVG, so it will naturally get overridden. The main problem there is that the border is intentionally set to be `currentColor` so that it will always inherit colors from adjacent text — but it's also semi-transparent, which requires it to be a separate element with opacity applied. I'm going to tinker a bit with this when I get a moment, see what we can do.

**Comment by jasmussen** [comment]
Alright, I tinkered with this enough to get a headache. Trying clever inheritance tricks, I got _really_ close while maintaining the semi-transparent currentColor stroke:
close

But unfortunately, I couldn't thread the needle. There was always some tradeoff, and the complexity was getting out there. 

So I tried a different approach: ditching the opacity entirely:

Screenshot 2022-08-12 at 10 57 52

That's with the following code diff:

```
diff --git a/packages/components/src/placeholder/style.scss b/packages/components/src/placeholder/style.scss
index d74fd7cdde..ac1d3cb51c 100644
--- a/packages/components/src/placeholder/style.scss
+++ b/packages/components/src/placeholder/style.scss
@@ -33,7 +33,6 @@
 
 	&.has-illustration {
 		background: none;
-		border: none;
 		box-shadow: none;
 		min-width: 100px;
 	}
@@ -180,17 +179,21 @@
 }
 
 // Style the placeholder illustration.
-.components-placeholder__illustration {
+.has-illustration {
 	border: $border-width dashed currentColor;
-	box-sizing: border-box;
+	overflow: hidden;
+}
+
+.components-placeholder__illustration {
+	box-sizing: content-box;
 	position: absolute;
-	top: 0;
-	right: 0;
-	bottom: 0;
-	left: 0;
+	top: 50%;
+	left: 50%;
+	transform: translate(-50%, -50%);
 	width: 100%;
 	height: 100%;
 	stroke: currentColor;
 	stroke-dasharray: 3;
-	opacity: 0.4;
+	border-width: inherit;
+	border-style: inherit;
 }
```

Or, you can manually integrate it with this chunk:

```

// Style the placeholder illustration.
.has-illustration {
	border: $border-width dashed currentColor;
	overflow: hidden;
}

.components-placeholder__illustration {
	box-sizing: content-box;
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	width: 100%;
	height: 100%;
	stroke: currentColor;
	stroke-dasharray: 3;
	border-width: inherit;
	border-style: inherit;
}
```

— but you have to remove the `border: none;` from `.has-illustration` longer up in the hierarchy.

So the question is: is that text-color dark outline good enough? I think yes, but I'd love input from @WordPress/gutenberg-design. Keep in mind, this should also affect Site Logo and soon Image in #43143. What do you think?

**Comment by jameskoster** [comment]
> So the question is: is that text-color dark outline good enough?

Do you mean on the 'No color, but width and radius defined' config?

That's a tricky one. It feels a _bit_ strange to see a color applied when one isn't explicitly set. But I appreciate that's an accurate representation of how `border-color` behaves. It's probably an acceptable trade-off.

Perhaps as a follow-up we can consider making the Border color control behave like the spec, IE the default border color is inherited from the text color of the selected element (when we're able to detect it 😅).

**Comment by jasmussen** [comment]
There's some nuance. Right now the placeholder is drawn using `currentColor` (and transparency) to ensure that its appearance works in any context. I.e. white text on dark background you'll have white dashed line on a black background placeholder. Or in other styles, like this one:

Screenshot 2022-08-12 at 12 16 37

What I'm saying is that we can have either of these two, but not both at the same time:

1. Inherit radius, keep the text-color dashed borders, but they have to be full opacity.
2. Don't inherit radius (or inherit in that buggy way we found), keep the text-color dashed borders, and keep the partial (0,4) opacity.

Is 1 fine? I suppose that's the main question.

**Comment by jameskoster** [comment]
I think it's fine. In fact, I think I prefer it 😆

**Comment by jasmussen** [comment]
Cool. We should probably try it. The thing is, we can always come back to these (especially if we can clean up the code and componentize it a bit) and try a different style if we like.

**Comment by jasmussen** [comment]
I've gone ahead and created #43228 which deduplicates and simplifies the code for these dashed placeholders. Part of that PR is also a fix that should enable border inheritance in this PR.

Edit: now merged. This PR should hopefully just work if rebased. Let me know if you need any help!

**Comment by priethor** [comment]
Let's add this issue to the 6.1 Editor Tasks board and prioritize it as it's a [requirement for the new default theme](https://github.com/WordPress/twentytwentythree/issues/30). cc @michalczaplinski @ockham @mikachan @beafialho

**Comment by aaronrobertshaw** [comment]
> Let's add this issue to the 6.1 Editor Tasks board and prioritize it

This is on my list to rebase and polish up now the placeholder changes are in place. Should be ready for a final review in the next couple of days.

**Comment by aaronrobertshaw** [comment]
This PR has been rebased. The video below demos the current state of borders on the Post Featured Image block. 

There are still several issues with applying borders to the block's placeholder. The end of the video includes a demonstration of one that occurs when opposite sides get differing width borders. Another is when the block sets a zero-width border, a `border-style: none` rule is applied, and the placeholder will then only consist of a diagonal line.

It feels to me that the styling of the placeholder has regressed now rather than been improved after recent efforts to inherit the border on the SVG.

I'd like to propose that we give this a final review to merge and address the placeholder problems in a separate follow-up.


https://user-images.githubusercontent.com/60436221/185296723-49dabfc5-e557-4665-b2d4-ae158306cc4d.mp4

**Comment by paaljoachim** [comment]
I have not yet tested it, but from looking at the video Aaron this looks really nice! I want it!

**Comment by jasmussen** [comment]
This is great, my GIF also shows border and radius working well in the setup state:
border

> There are still several issues with applying borders to the block's placeholder. The end of the video includes a demonstration of one that occurs when opposite sides get differing width borders. 

I'll take a quick look and if I think up a fix I'll push! Hope that's okay.

> Another is when the block sets a zero-width border, a border-style: none rule is applied, and the placeholder will then only consist of a diagonal line.

I think this is acceptable. It's first and foremost in edgecase territory, and secondly it's technically accurate.

**Comment by jasmussen** [comment]
@aaronrobertshaw I pushed a fix for the inner color:
Screenshot 2022-08-18 at 08 26 17

What do you think? If you're cool with it, looks like this one needs updated snapshots.

**Review by jasmussen — APPROVED** [review]
Experience wise, this is a step forward for letting placeholders inherit the styles of their surroundings. Across the board this effort can improve patterns and placeholders, so things like dimensions and even duotone can be visualized and preset, without media being added first. In that line, this is a solid win.

I would appreciate a quick code sanity check, but otherwise this one seems good to try!

**Comment by jameskoster** [comment]
> I think this is acceptable.

I agree. Still, it might be good to (separate to this PR) explore adding a background to the placeholder so that it is still visible when placed on a noisy background, or when placeholders overlap, e.g. putting featured image inside a cover:

Screenshot 2022-08-18 at 10 03 50

**Comment by jasmussen** [comment]
> I agree. Still, it might be good to (separate to this PR) explore adding a background to the placeholder so that it is still visible when placed on a noisy background, or when placeholders overlap, e.g. putting featured image inside a cover:

Ack, yes indeed.

**Comment by aaronrobertshaw** [comment]
Thanks for tweaking the placeholder styles @jasmussen 👍 

> What do you think? If you're cool with it, looks like this one needs updated snapshots.

It might just be me, but I still think the placeholder with borders has problems however, if we remove the styles inheriting `border-width` and `border-style` on the placeholder's SVG along with removing the `border-color: transparent`, I think we get a better result.

The following videos show what I see with and without the abovementioned styles.

| With  | Without |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/185554442-514cb6fa-64d5-4897-91bf-7d798fc4aee2.mp4"/> | <video src="https://user-images.githubusercontent.com/60436221/185554971-0cffd8a8-63e1-4327-a7b4-7ff92f8dca2e.mp4" /> |

Given the previous commit adjusting these styles, I'll hold off merging this until we decide whether to strip them or not. 

My vote is if they don't impact other block's placeholders, we should remove them. Any other issues with the placeholder, like [applying a background color](https://github.com/WordPress/gutenberg/pull/42847#issuecomment-1219225671) are out of scope for this PR and will be addressed via follow-ups.

**Comment by jasmussen** [comment]
Excellent sleuthing. As far as I can tell, the major difference is the positioning of the diagonal, which is off when those styles are inherited:
Screenshot 2022-08-19 at 09 08 40

It is not off when they are gone:

Screenshot 2022-08-19 at 09 08 46

I could swear I added those for a reason, but testing with a rebase the new Image, as well as Site Logo and various combinations of borders and no borders, this change seems solid! In other words, they don't seem needed. Definitely remove those, then land this. Thank you! 🙏

(Besides, if they turn out to become necessary again, we'll just add them back.)

**Comment by aaronrobertshaw** [comment]
Thanks for the continued testing @jasmussen 👍

I've pushed a commit to remove those styles as discussed. Once the e2es are green, I'll get this merged.

**Comment by jasmussen** [comment]
💥

**Comment by ntsekouras** [comment]
I'm debugging in a PR of mine with Query Loop work and I have noticed these:

```


Notice: Undefined index: classnames in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/post-featured-image.php on line 106
--
Notice: Undefined index: css in /var/www/html/wp-content/plugins/gutenberg/build/block-library/blocks/post-featured-image.php on line 107

```
Does it ring any bell? It might be me though... still looking 😄 

--edit

It seems to be on trunk by this PR..

**Pull request merged**
