### PR TITLE
Add media & text grid pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a media & text grid block pattern for #20345.

⚠️ Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.

75584599-ef664180-5a24-11ea-9a3d-9e12c2eb7d74

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><div class="wp-block-group__inner-container"><!-- wp:media-text {"align":"full","mediaId":682,"mediaLink":"https://wpuxtesting.com/?attachment_id=682","mediaType":"image"} -->
<div class="wp-block-media-text alignfull is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://wpuxtesting.com/wp-content/uploads/2020/02/E5FDB9E9-A370-4738-B59C-948C80B83954-1024x768.jpeg" alt="" class="wp-image-682"/></figure><div class="wp-block-media-text__content"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":10} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":60} -->
<div class="wp-block-column" style="flex-basis:60%"><!-- wp:paragraph {"customFontSize":52} -->
<p style="font-size:52px">Deserts</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The canyons are vast and memorable. The air is dry and hot. It is the desert and rarely inviting.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":10} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:media-text -->

<!-- wp:media-text {"align":"full","mediaPosition":"right","mediaId":473,"mediaType":"image"} -->
<div class="wp-block-media-text alignfull has-media-on-the-right is-stacked-on-mobile"><figure class="wp-block-media-text__media"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/F88EC5E3-2C7C-41F5-87F6-2C79BCCC62AC-1024x768.jpeg" alt="" class="wp-image-473"/></figure><div class="wp-block-media-text__content"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":10} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":60} -->
<div class="wp-block-column" style="flex-basis:60%"><!-- wp:paragraph {"customFontSize":52} -->
<p style="font-size:52px">Forest</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The canyons are vast and memorable. The air is dry and hot. It is the desert and rarely inviting.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":10} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:media-text --></div></div>
<!-- /wp:group -->
```

### CODE REVIEW

**Comment by youknowriad** [comment]
Nice one, let's replace the images with some from these list and ship

https://s.w.org/images/core/5.3/Biologia_Centrali-Americana_-_Cantorchilus_semibadius_1902.jpg
https://s.w.org/images/core/5.3/Glacial_lakes,_Bhutan.jpg
https://s.w.org/images/core/5.3/MtBlanc1.jpg
https://s.w.org/images/core/5.3/Sediment_off_the_Yucatan_Peninsula.jpg
https://s.w.org/images/core/5.3/Windbuchencom.jpg

**Comment by youknowriad** [comment]
Actually, I just noticed that the "Media & Text" block don't support external URLs properly for images. if we remove the mediaId attribute, the block becomes invalid, if we keep it, this could be another existing media causing issues.

@jorgefilipecosta do you think we can quickly support external media URLs in this block?

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta do you think we can quickly support external media URLs in this block?


I think the reason why media & text does not support external URL is that with just a URL there is no easy way of knowing if the URL is a an image or a video. I think @draganescu made some research around that.

**Comment by jorgefilipecosta** [comment]
An easy option would be to provide a UI where the user selects if the external URL is an image or a video, any thoughts on this option @mapk?

**Comment by draganescu** [comment]
Yes, just and URL won't let us know _reliably_ what type of media the user selected. I also think that we could use a "media" block that simply allows the user to select the type of media they want from the first screen: image or video.

I also think it is easier for users to think of images or videos rather than "media", so the media block would be just an internal functionality.

**Comment by draganescu** [comment]
I tested this and I don't understand why in the media+text block in the pattern contains four columns instead of two. Actually why does it contain columns at all, as the normal media+text block does not build it's layout based on the columns block?

**Comment by enriquesanchez** [comment]
Hey @draganescu! I believe @mapk built this one, but if I'm not mistaken, the use of columns is for greater layout control, is that right @mpak?

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. I know we decided to go without images for now but I would like to know if you think we can somehow revisit this one or if we should close this PR instead.

**Comment by mapk** [comment]
The reason for the columns was to force a narrower width for the text. This took the design of the layout a bit farther and didn't just conform to the basic width of the Media+Text block. 

As this patterns also includes images, let's drop it from our list currently.

**Pull request closed without merging**
