### PR TITLE
List all the font families and font sizes from all the theme.json origins in the font picker

### LINKED ISSUE #51487: Typography panel only displays a subset of all the available fonts in theme.json
### Description

Currently, if the user has font families defined in the custom theme.json the theme fonts are not listed in the typography picker.
The custom origin does not overwrite the other origins of the theme.json, it is just another category, so having custom font families should not hide the font families defined in the theme origin of the theme.json.

### Step-by-step reproduction instructions

1. Add font families definitions to your custom theme.json (global styles) `settings.typography.fontFamilies`
2. Observe that the font families defined in your theme are not longer listed in the font picker component.

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress 6.2
- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
List all the font families from all the theme.json origins in the font picker

## Why?

Currently, the font family picker is listing only font families from custom theme.json origin (global styles) if it's defined.

## How?
Concat all the font families available from all the origins.

## Testing Instructions
1. Add font families definitions to `settings.typography.fontFamilies` in the custom global styles. (The theme.json is stored in the database)
2. Check that in the typography panel the font picker includes the font families from custom and from theme origins.

Fixes: https://github.com/WordPress/gutenberg/issues/51487

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
This makes sense to me 👍

**Review by andrewserong — COMMENTED** [review]
This sounds good to me, too. I take it it's okay that a user wouldn't be able to remove a font family set by the theme?

A couple of other quick thoughts:

* In [`useHasFontFamilyControl`](https://github.com/WordPress/gutenberg/blob/38bebabfe0adac15df6fc772fab7bb8c546441ff/packages/block-editor/src/components/global-styles/typography-panel.js#L60) it currently checks if the first found font family by origin is empty. If the `custom` array is empty, and the theme array isn't, then with this PR, it sounds like it should return `true`. Would it be worth updating that function to use the same `.concat()` logic?
* When concatenated, should the lists of fonts be sorted in any particular way? Currently it looks like they'll be sorted by origin, which might be unexpected depending on the circumstances.

Code-wise this approach otherwise looks good to me, but I didn't manage to get it working for me locally with a `custom` key added to the `fontFamilies` in the revisions entry in the database. It's highly likely that I made a mistake in my testing... do you have a set of steps to follow for testing that this is working as expected?

Since Riad has already approved, don't feel like you need to wait for me before merging, though! 🙂

**Comment by matiasbenedetto** [comment]
> This sounds good to me, too. I take it it's okay that a user wouldn't be able to remove a font family set by the theme?

Yes, the user will be able to remove a font family defined by the theme by removing it from the array. We don't have the UI for that yet but it will be available in the [font library](https://github.com/WordPress/gutenberg/pull/50927).

> In [useHasFontFamilyControl](https://github.com/WordPress/gutenberg/blob/38bebabfe0adac15df6fc772fab7bb8c546441ff/packages/block-editor/src/components/global-styles/typography-panel.js#L60) it currently checks if the first found font family by origin is empty. If the custom array is empty, and the theme array isn't, then with this PR, it sounds like it should return true. Would it be worth updating that function to use the same .concat() logic?

Good catch! I added the same logic to `useHasFontFamilyControl` and also to `useHasFontSizeControl` and in the font sizes selector.

> When concatenated, should the lists of fonts be sorted in any particular way? Currently it looks like they'll be sorted by origin, which might be unexpected depending on the circumstances.

Yes! Thanks for pointing this out. I added sorting base on the font family name if it's defined or the slug in case the name is missing.

> Code-wise this approach otherwise looks good to me, but I didn't manage to get it working for me locally with a custom key added to the fontFamilies in the revisions entry in the database. It's highly likely that I made a mistake in my testing... do you have a set of steps to follow for testing that this is working as expected?

You should just add some valid theme.json containing font families to the global styles post in the database.
Example:

```
{
	"settings": {
		"typography": {
			"fontFamilies": {
				"theme": [{
						"fontFace": [{
							"fontFamily": "Crimson Pro",
							"fontStyle": "normal",
							"fontWeight": "200",
							"src": ["file:./assets/fonts/crimson-pro_normal_200.ttf"]
						}],
						"fontFamily": "Crimson Pro",
						"slug": "crimson-pro",
						"name": "Crimson Pro"
					},
					{
						"fontFace": [{
								"fontDisplay": "block",
								"fontFamily": "IBM Plex Mono",
								"fontStretch": "normal",
								"fontStyle": "italic",
								"fontWeight": "400",
								"src": [
									"file:./assets/fonts/ibm-plex-mono/IBMPlexMono-Italic.woff2"
								]
							},
							{
								"fontDisplay": "block",
								"fontFamily": "IBM Plex Mono",
								"fontStretch": "normal",
								"fontStyle": "normal",
								"fontWeight": "700",
								"src": [
									"file:./assets/fonts/ibm-plex-mono/IBMPlexMono-Bold.woff2"
								]
							}
						],
						"fontFamily": "'IBM Plex Mono', monospace",
						"name": "IBM Plex Mono",
						"slug": "ibm-plex-mono"
					},
					{
						"fontFamily": "-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,Oxygen-Sans,Ubuntu,Cantarell,\"Helvetica Neue\",sans-serif",
						"name": "System Font",
						"slug": "system-font"
					},
					{
						"fontFace": [{
							"fontFamily": "Work Sans",
							"fontStyle": "normal",
							"fontWeight": "100 900",
							"src": ["file:./assets/fonts/work-sans_normal_100%20900.ttf"]
						}],
						"fontFamily": "Work Sans",
						"slug": "work-sans",
						"name": "Work Sans"
					}
				],
				"custom": [{
						"name": "Advent Pro",
						"fontFamily": "Advent Pro, sans-serif",
						"slug": "wp-font-lib-advent-pro",
						"category": "sans-serif",
						"fontFace": [{
							"src": "/wp1/wp-content/fonts/advent-pro_normal_100.ttf",
							"fontWeight": "100",
							"fontStyle": "normal",
							"fontFamily": "Advent Pro"
						}]
					},
					{
						"name": "Amiko",
						"fontFamily": "Amiko, sans-serif",
						"slug": "wp-font-lib-amiko",
						"category": "sans-serif",
						"fontFace": [{
							"src": "/wp1/wp-content/fonts/amiko_normal_400.ttf",
							"fontWeight": "400",
							"fontStyle": "normal",
							"fontFamily": "Amiko"
						}]
					}
				]
			}
		}
	},
	"isGlobalStylesUserThemeJSON": true,
	"version": 2
}
```

**Comment by matiasbenedetto** [comment]
Ooops... auto-merge was activated, and when tests passed, it merged. Please report if you find something weird.

**Comment by andrewserong** [comment]
> Ooops... auto-merge was activated, and when tests passed, it merged. Please report if you find something weird.

No worries! Thanks for the extra info and updates, the code change looks good to me 🙂

**Pull request merged**
