### PR TITLE
Remove unnecessary space in HTML tags

### PR DESCRIPTION
**Pull request by guarani**
## Description

The rich-text component was adding a space to the opening root tag of HTML before passing it to Aztec. I don't think this resulted in any bugs, so this change is more of a code clean-up.

Related: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3367

## How has this been tested?
With the mobile editor empty and the debugger attached, I put a breakpoint in `AztecView.js` on [this line](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-aztec/src/AztecView.js#L215) and typed a single "R" character into an empty Paragraph block. Logging `this.props.text` gave:
```
{text: "<p>R</p>", eventCount: 1, selection: null, linkTextColor: "#016087"}
```
Before this change, I would see this (note the space in the opening `<p>` tag:
```
{text: "<p >R</p>", eventCount: 1, selection: null, linkTextColor: "#016087"}
```

## Types of changes
Code clean-up.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by guarani** [comment]
The snapshot tests [failed](https://github.com/WordPress/gutenberg/pull/30585/checks?check_run_id=2291764272) because some of them expected a space in opening tags, e.g.:
```
    -             "text": "<p >Search</p>",
    +             "text": "<p>Search</p>",
```
I updated the failing tests using:

```
npm run test-unit:native -- --updateSnapshot --testPathPattern packages/block-library/src/search/test/edit.native.js
npm run test-unit:native -- --updateSnapshot --testPathPattern packages/block-library/src/file/test/edit.native.js
```

**Review by geriux — APPROVED** [review]
LGTM! I checked this `extraAttributes` is only used for `ol` elements and those are adding their own space when concatenating 👍 

Tested it a bit and all looks good. Thanks for cleaning this up!

**Comment by guarani** [comment]
> LGTM! I checked this `extraAttributes` is only used for `ol` elements and those are adding their own space when concatenating 👍

@geriux I'd forgotten to check ordered lists (`ol`) so thanks for bringing that up!

I went to test the "Ordered list settings" now and noticed they are not working 🤔 Setting the start value or "reverse list numbering" isn't working. I tested the current WPiOS 17.0 and they don't seem to be working their either. (It does work when I preview the post–since the right HTML is produced by the editor–it's just that the editor itself doesn't reflect these changes.

I'm thinking that it's a separate issue though and I can merge this and create a separate issue for that, what do you think?

**Comment by geriux** [comment]
> I went to test the "Ordered list settings" now and noticed they are not working 🤔 Setting the start value or "reverse list numbering" isn't working. I tested the current WPiOS 17.0 and they don't seem to be working their either. (It does work when I preview the post–since the right HTML is produced by the editor–it's just that the editor itself doesn't reflect these changes.

Oh! I missed that 😓 

> I'm thinking that it's a separate issue though and I can merge this and create a separate issue for that, what do you think?

Yeah, I think this one is unrelated and we can work on that bug on another issue. Thanks!

**Comment by guarani** [comment]
> Yeah, I think this one is unrelated and we can work on that bug on another issue. Thanks!

Sounds good! I created an issue here: https://github.com/WordPress/gutenberg/issues/30623

**Pull request merged**
