### PR TITLE
Make the tag and category labels in the prepublish panel compatible w…

### LINKED ISSUE #22588: Maybe tags panel using hardcoded "tags" string instead of tags taxonomy name label
**Describe the bug**
If I'd like to change the name of tags to for example "keywords" in the admin area/editor it's quite easy to do using the [taxonomy_labels_post_tag](https://developer.wordpress.org/reference/hooks/taxonomy_labels_taxonomy/) filter. This works everywhere in both Gutenberg (in the sidebar it say "Keywords" and "Add new keyword") and the admin area except for in the [maybe tags panel](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-publish-panel/maybe-tags-panel.js) in the post publish panel where "tags" are hardcoded in [two](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-publish-panel/maybe-tags-panel.js#L24) [strings](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-publish-panel/maybe-tags-panel.js#L32).

**To reproduce**
1. Add something like the following to a plugin or your themes `functions.php` file.
```PHP
add_filter(
	'taxonomy_labels_post_tag',
	function( object $labels ): object {
		$singular_name = 'Keyword';
		$plural_name   = 'Keywords';
		return (object) [
			'name'                  => $plural_name,
			'singular_name'         => $singular_name,
			'menu_name'             => $plural_name,
			'all_items'             => "All {$plural_name}",
			'new_item_name'         => "New {$singular_name} Name",
			'add_new_item'          => "Add New {$singular_name}",
			'edit_item'             => "Edit {$singular_name}",
			'update_item'           => "Update {$singular_name}",
			'view_item'             => "View {$singular_name}",
			'add_or_remove_items'   => "Add or remove {$plural_name}",
			'search_items'          => "Search {$plural_name}",
			'not_found'             => "No {$plural_name} found",
			'no_terms'              => "No {$plural_name}",
			'items_list'            => "{$plural_name} list",
			'items_list_navigation' => "{$plural_name} list navigation",
		];
	}
);
```
2. Create a new post using Gutenberg.
3. See that "tags" are changed to "keywords" in the sidebar.
4. Don't add any tags/keywords before clicking on publish (and make sure to have the post publish panel activated). See that it says "Add tags" and "Tags help users and search engines..." instead of "Add keywords" etc.

**Expected behavior**
I'd except the maybe tags panel to use the name of the tags taxonomy from the label called "name".

I realise that this is probably very edge-casey, but happy to try and make a PR if y'all deem it worthwhile. :)

**Screenshots**
Screenshot 2020-05-24 at 18 38 54
"Keywords" in the sidebar.
Screenshot 2020-05-24 at 19 35 26
"Tags" in the post publish panel (but it says keywords in the input field since that uses the label)

**Editor version (please complete the following information):**
- WordPress version: 5.5-alpha-47853
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? Master

### PR DESCRIPTION
**Pull request by danieldudzic**
…ith filters. Closes #22588

## What?
This PR makes the pre-publish panel taxonomy terms inputs and descriptions compatible with filters ('that for example change the taxonomy name').

## Why?
This change has been requested in #22588

## How?
This PR changes the hardcoded taxonomy names and instead loads them via taxonomy data

## Testing Instructions

1. Add something like the following to a plugin or your themes functions.php file.

```
add_filter(
	'taxonomy_labels_post_tag',
	function( object $labels ): object {
		$singular_name = 'Keyword';
		$plural_name   = 'Keywords';
		return (object) [
			'name'                  => $plural_name,
			'singular_name'         => $singular_name,
			'menu_name'             => $plural_name,
			'all_items'             => "All {$plural_name}",
			'new_item_name'         => "New {$singular_name} Name",
			'add_new_item'          => "Add New {$singular_name}",
			'edit_item'             => "Edit {$singular_name}",
			'update_item'           => "Update {$singular_name}",
			'view_item'             => "View {$singular_name}",
			'add_or_remove_items'   => "Add or remove {$plural_name}",
			'search_items'          => "Search {$plural_name}",
			'not_found'             => "No {$plural_name} found",
			'no_terms'              => "No {$plural_name}",
			'items_list'            => "{$plural_name} list",
			'items_list_navigation' => "{$plural_name} list navigation",
		];
	}
);
```

and

```
/**
 * Rename Category to Theme
 *
 */
function be_rename_category_theme() {

	$singular_name = 'Theme';
	$plural_name = 'Themes';

	$labels = array(
		  'name'					=> $plural_name,
		  'menu_name'				=> $plural_name,
		  'singular_name'			=> $singular_name,
		  'search_items'			=> 'Search ' . $plural_name,
		  'popular_items'			=> 'Popular ' . $plural_name,
		  'all_items'				=> 'All ' . $plural_name,
		  'parent_item'				=> 'Parent ' . $singular_name,
		  'parent_item_colon'		=> 'Parent ' . $singular_name . ':',
		  'edit_item'				=> 'Edit ' . $singular_name,
		  'view_item'				=> 'View ' . $singular_name,
		  'update_item'				=> 'Update ' . $singular_name,
		  'add_new_item'			=> 'Add New ' . $singular_name,
		  'new_item_name'			=> 'New ' . $singular_name . ' Name',
		  'separate_items_with_commas' => 'Separate ' . $plural_name . ' with commas',
		  'add_or_remove_items'		=> 'Add or remove ' . $plural_name,
		  'back_to_items'			=> '← Back to ' . $plural_name,
		  'items_list_navigation' 	=> $plural_name . ' list navigation',
		  'items_list'				=> $plural_name . ' list',
	  );

	  global $wp_taxonomies;
	  $wp_taxonomies['category']->labels = (object) array_merge( (array) $wp_taxonomies['category']->labels, $labels );
}
add_action( 'init', 'be_rename_category_theme' );
```
2. Create a new post using Gutenberg.
3. See that "tags" are changed to "keywords" in the sidebar and categories to "themes".
4. Don't add any tags/keywords & categories/themes before clicking on publish (and make sure to have the post publish panel activated).
5. Verify that it says "Add keywords" and "Keywords help users and search engines..." instead of "Add tags" etc.
6. Verify that it says "Assign a theme" and "Themes provide a helpful way to group..." instead of "Assign a category" etc.

## Screenshots or screencast 
|Before|After|
|-|-|
|Edit_Post_“Lol”_‹_taruns-site_—_WordPress|after-3|

### CODE REVIEW

**Comment by grappler** [comment]
From the translation perspective, it is not ideal to use variables like this. The way that WordPress has solved this is to change the labels using `taxonomy_labels_post_tag`. I would suggest extending `get_taxonomy_labels()` with new labels for `prepublish_suggestion` and `prepublish_desctiption`. 

A possible code example for this in Gutenberg can be found here: https://github.com/WordPress/gutenberg/blob/6f31d725f725f10d10204e165d5dfcd0785a5bd4/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L378-L409

**Comment by ndiego** [comment]
@danieldudzic have you had a chance to look at @grappler's latest comment? This PR is looking good, pending the accessibility updates. The linked issue came up in today's Editor Bug Scrub and this would be great to get merged. 🙌

**Comment by ndiego** [comment]
Hi @danieldudzic, just checking in again on this PR as it came up again during the weekly Editor big scrub. Thanks!

**Comment by danieldudzic** [comment]
Hi @ndiego,

Sorry, didn't have time to work on this recently :(

I'm going on vacation for the next two weeks. If anyone wants to handle this in the meanwhile, please do so.

I'll have a look when I'm back, and if no one resolved it yet, I'll give it a spin.

**Pull request closed without merging**
