### PR TITLE
Update layout toggle label

### PR DESCRIPTION
**Pull request by richtabor**
## Description

As originally brought up [here](https://github.com/WordPress/gutenberg/issues/34558), I wanted to iterate on the label we're currently using for the layout control's "Inherit default layout". The current label of "Inherit default layout" does not provide enough context to what's actually happening when that control is enabled. 

When active, the blocks within the Group block have their own alignment controls available (essentially how Group blocks functioned before introducing this control). 

When inactive, the user cannot set wide/full width alignments for those child blocks. 

I don't know that I'm sold on the label I'm suggesting entirely, but does anyone else have another idea that could work better?

## Screenshots 

**Previous:**
Screen Shot 2021-11-19 at 12 14 57 PM

**This PR:** 
Screen Shot 2021-11-19 at 12 02 01 PM

## Types of changes
Copy change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by carolinan** [comment]
So to summarize the current text is "Inherit default layout". The proposed text is "Use inner block alignment".

**Comment by mtias** [comment]
This setting is one of most confusing things we are shipping. I don't think a label alone can capture what it does properly. Can we look at expanding what it does in a help paragraph, at least when it's toggled on?

**Comment by kjellr** [comment]
There's some prior discussion and iteration on this label over in this issue: https://github.com/WordPress/gutenberg/issues/31950

My initial explorations at the top were just simple re-labeling (including a paragraph explainer). But @jameskoster, @shaunandrews, and I expanded into more UI explorations later down the thread.

**Comment by clucasrowlands** [comment]
Hi! Editorial here -- got the Needs Copy Review notification. I followed/read through the convo at [#31950](https://github.com/WordPress/gutenberg/issues/31950) but I'm not totally clear of the copy that needs to be reviewed — or if there's still discussion happening over this label and the text/descriptions.

Personally, as a general user I attribute "layout" with theme/template/overall design; I also don't know what an "inner block" is, though that comment is coming from someone who's never used a group block before.

Anyway, if you need our input on specific copy for polishing, just ping us/me again and I can try to help. Thanks!

**Comment by carolinan** [comment]
Regarding #31950 I don't think there is time for the UI changes, but we can still add a help text?

"Blocks placed inside `%blockname` take up the full-width.
Use the setting to center the blocks and enable wide and full-width alignment options."

**Comment by jameskoster** [comment]
I find this control so confusing 🙈 One of the elements I struggle with most is that I have no context for "default". It's not clear:

1. What "inheriting default" actually means – where does this "default" come from?
2. What happens when I use the defaults – what are the default values?

This is compounded by the fact that it's not obvious (to me at least) that these width settings are applied to the blocks _inside_ this one.

A quick sketch that might help:




I've replaced references to "default" with "theme", which hopefully clarifies that the values – if not customised – come from the active theme. I used a segmented control but if more words are needed a toggle or even radios could work instead.

When theme values are used the inputs remain visible, but disabled. This way you can at least see what those values are and loosely interpret how they might manifest on the canvas.

**Comment by carolinan** [comment]
I proposed the string change only, for now, short term, because the 5.9 string freeze happens at 20:00 UTC today.

**Comment by annezazu** [comment]
Can this be closed considering the recent changes in this PR? https://github.com/WordPress/gutenberg/pull/41893

**Pull request closed without merging**
