### PR TITLE
Revert popover change to see if e2e test results change

### PR DESCRIPTION
**Pull request by ellatrix**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
1st run passes. I'll rerun the whole thing again.

Screenshot 2020-06-18 at 10 51 27

**Comment by ellatrix** [comment]
Second run passes too

**Comment by ellatrix** [comment]
Screenshot 2020-06-18 at 11 32 50

Rerunning it a third time

**Comment by ellatrix** [comment]
Third run also passes

**Review by youknowriad — APPROVED** [review]
Let's land this to unblock folks, discover what e2e tests are unrelated to popover and give it more time.

**Comment by ellatrix** [comment]
Let's close since the e2e tests seems to be ok now.

**Pull request closed without merging**
