### PR TITLE
TreeGrid: Add Home/End keys to jump to start/end of grid

### PR DESCRIPTION
**Pull request by alexstine**
## Description

According to the ARIA spec, Home/End keys must jump to the beginning/end of the TreeGrid.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

## Testing Instructions

1. Open Gutenberg.
2. Insert a Columns Block and select a variation.
3. Insert other Blocks.
4. Open the List View.
5. Press End to go to the end and Home to go to the beginning. Focus should change to the respective positions.

## Types of changes

New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by alexstine** [comment]
@MarcoZehe I always thought it would be better UX if the Home/End key jumped to the beginning/end item of an expanded `<tr>` but the above spec example just has it jumping to the beginning/end of the whole tree view regardless of the state. Do you think this PR is good as is?

**Review by MarcoZehe — APPROVED** [review]
Yeah, for non-tree grids I would agree that home and end should move to the beginning/first or end/last data column of a row, but for tree grids, the behavior you implemented here is actually appropriate and will allow for quick navigation. AKA the first objective in a tree grid is to get to a particular row, and only then interact with its columns. So LGTM.

**Comment by talldan** [comment]
Looks good to me too. Thanks for another great improvement 🎉

**Comment by ciampo** [comment]
Hey folks, I noticed a few great accessibility fixes / improvements on `TreeGrid` recently!

It would be great if we could also add a few unit tests to make sure we don't introduce any regressions around these areas in the future— would that be possible?

**Comment by alexstine** [comment]
@ciampo Is there a needs-tests label or something? Problem is, I am not a sponsored contributor so what I have time for is what I have time for. I would like to get more involved with writing and extending tests but between working out code structure and fixing accessibility bugs, that's about all the time I have ATM.

Is there anyone who likes writing tests floating around the community right now?

Thanks.

**Comment by ciampo** [comment]
Hey @alexstine , I get your point and I continue to _really_ appreciate your contributions!

The reason why I'm pointing out the lack of tests, is that without a test, all of the work that you put in has the change to be reverted in the future. Unit tests would help us avoid any potential regressions, and in my personal opinion in this scenario can be as important as the fix itself.

I'd personally almost prefer to have, given the same span of time, one PR with a bug fix a corresponding unit tests, than two PRs with two bug fixes and no unit tests associated.

> Is there anyone who likes writing tests floating around the community right now?

I don't think that there's anyone around who specifically writes unit tests. @mirka and I try our best to support folks working on `@wordpress/components`, while also maintaining and improving the package on the side.

For now I've opened #38735 to track this task.

> Is there a needs-tests label or something? 

There is one similar label, but it seems to be used for issues that need to be triaged.

**Comment by alexstine** [comment]
@ciampo Thanks for the tracking issue. I'll try to work on it but no promises right now.

**Comment by talldan** [comment]
Similarly, there should really be more e2e tests for the List View feature. 😅 

I've created an issue for that - https://github.com/WordPress/gutenberg/issues/38774.

**Comment by ciampo** [comment]
Thank you @alexstine and @talldan for your replies and your continued effort!

**Pull request merged**
