### PR TITLE
Polish sidebar controls

### PR DESCRIPTION
**Pull request by jasmussen**
This PR polishes controls in the sidebar.

- It enhances the base control to have a minimum height that fits a button size.
- It changes the status & visibility buttons to be more harmoniously placed.
- It changes the "Move to Trash" button to use sentence case, and be a tertiary button.

Screenshot 2020-06-30 at 10 29 39

It styles the checkbox control to better match the styles outlined in https://github.com/WordPress/gutenberg/issues/18667:

Screenshot 2020-06-30 at 11 09 29

It styles the toggle control the same way:

Screenshot 2020-06-30 at 11 13 52

... And the radio control:

Screenshot 2020-06-30 at 11 25 01

It fixes a bug where the post-publish sidebar was 1px off. Before:

Screenshot 2020-06-30 at 11 24 47

After:

Screenshot 2020-06-30 at 11 26 13

### CODE REVIEW

**Review by mapk — APPROVED** [review]
🎉  These little polishes go a long way! Thanks for catching them. It all looked and worked as you mentioned and feels really sharp.

**Comment by enriquesanchez** [comment]
Amazing attention to detail! Tested it and it all worked as expected 👍

**Review by tellthemachines — APPROVED** [review]
Great improvements! A couple of small things I noticed testing in Windows in high contrast mode:

* The "move to trash" button now doesn't look like a button or link at all:

button-hi-c

 I guess this is a problem for all tertiary buttons. Could we give them an outline of some kind that would be distinguishable from the focus outline? Or perhaps a transparent bottom border or something?

* There's no way of telling which radio button is selected when they are not focused:
(this was an existing issue, not sure what the best solution might be)

radio-hi-contrast

**Comment by jasmussen** [comment]
Thank you Isabel, those are wonderful observations. I'll get right on those and we'll ship this after.

**Comment by jasmussen** [comment]
I added a dotted transparent outline around tertiary buttons, which shows up in high contrast mode:

Screenshot 2020-07-02 at 11 25 00

Note that the above screenshot is scaled down so it gets fuzzy, but the outline is plenty visible. 

I can't reproduce the radio button issue, to me they look correct regardless of focus:

Screenshot 2020-07-02 at 11 26 08

Where did you see this issue?

Thanks again.

**Comment by jasmussen** [comment]
I'm going to merge this one with the reviews, and I will be happy to address any followups.

**Comment by tellthemachines** [comment]
> Where did you see this issue?

On both Firefox and IE11, Windows 10, in high contrast mode. The only browser that seems to be showing them correctly is Edge (both the legacy and the new Chromium-based version)

**Comment by jasmussen** [comment]
> The only browser that seems to be showing them correctly is Edge (both the legacy and the new Chromium-based version)

Ah, yes, both Firefox and Chrome have historically not leveraged the high contrast mode very well. I believe Chrome didn't support it for the longest time virtually at all, though perhaps with chromium based edge that might have changed recently.

I'm going to take a look at a followup next week. Thanks for the clarification!

**Comment by jasmussen** [comment]
#23706 fixes the checkbox control issue.

If you know of any existing tickets that closes, would appreciate if you add it as a "fixes" comment.

**Pull request merged**
