### PR TITLE
WIP: Unify publish flow between post and site editors

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Part of: https://github.com/WordPress/gutenberg/issues/59878

Current state of this PR:
1. Move specific parts of `Publish` button/panel/actions/slots/preferences in editor package(ex PluginPostPublishPanel). Noting that some of them were already there.
2. Port the `Publish` and `save draft` button in site editor where **they are rendered only if** we have a page in `draft` status and we don't have any changes in other entities. If the above conditions are not met, the current `save` button is rendered. The direction should be to have a single `publish/save` button for both editors.

The extra nuances here are:
1. Already too much changes in this PR(and will be a few more) and not sure if I should try to unify to the single `publish/save` button or if we should do it iteratively. Additionally I'm not sure I can I split this PR in smaller PRs - maybe moving some stuff in editor package without adding it in site editor? 🤔 
2. When we'll unify the `publish/save` button we need to unify the status change flow, because they are different right now between editors. In post editor we have less statuses available and we infer some of them based on the coupled fields(ex Scheduled status and future publish date). In site editor right now we have all the statuses available but not baked in the publish flow.

### CODE REVIEW

**Comment by jasmussen** [comment]
Phew. Big PR! 

What are some of the main things to look out for? In a bit of quick testing of the site editor and post editor, the behavior felt reasonably solid. Here's a GIF showing that testing session, which involved publishing a page, editing a page after the fact, then bundling up some changes, style variations, etc.

test

**Comment by ntsekouras** [comment]
>What are some of the main things to look out for?

@jasmussen I think that since we want to unify the publishing flow, we need to decide is what to do with the `post status` panel in site editor and `visibility` in post editor(which also involves the switch to draft button and the save draft button).

This PR makes it easier to see the differences and inconsistencies and will hopefully help us make informed decisions about the end result. 

So:
1. Should we preserve what we do in site editor and update post editor(add post status - remove visibility)?
2. Should we do the opposite and update site editor with visibility panel and remove the status one?
3. Do we want to try and preserve the differences publishing flow(like it's in this PR)?

**Comment by youknowriad** [comment]
I'm personally leaning towards "1" (aka the site editor behavior) because it feels more simple. Everything works in a unique way (save button) except when the the post is draft (you have a publish button).

The post editor behavior is a bit more involved but also more confusing (some options actually trigger a publish right away, like making things private...)

**Comment by jasmussen** [comment]
I would also lean towards 1, as the post editor panel has its own share of problems. I think that's also the plan @jameskoster is working off of, and ultimately I'll defer to him on this.

**Comment by jameskoster** [comment]
> I would also lean towards 1

Yup, that's what we've been working towards. Designs for reference:

Panels

**Comment by ntsekouras** [comment]
Thanks for sharing the designs @jameskoster. What would be the text of the Modal's trigger when in other post statuses (like draft, scheduled, etc..)?

**Comment by jameskoster** [comment]
Minor visual details may need tweaking but this is what I've been exploring for the different status chip configurations:

status

**Comment by jasmussen** [comment]
Nice designs, thank you for including the full editor context. Seeing it like that, I wonder if the same visual treatment should be used for status and visibility as we use for the color flyouts, like these:

Screenshot 2024-04-03 at 09 27 26

**Comment by jameskoster** [comment]
Ideally all popovers use the same [component](https://wordpress.github.io/gutenberg/?path=/docs/components-popover--docs) and inherit the styles/metrics accordingly. 

The main difference seems to be the exclusion of the title / close button, happy to try that 👍

**Comment by annezazu** [comment]
I agree with option 1 and seeing how that feels. Some quick feedback and notes as I know we're working through how best to unify. 

I'd say "successfully drafted" as upon creation it's not live:

Screenshot 2024-04-03 at 6 08 10 PM

After updating a page, "site updated" feels a bit extreme as it's just a page that's been updated. I think we should change that to "page updated" unless there are additional changes to the broader site:

Screenshot 2024-04-03 at 6 15 28 PM

I found myself missing both the pattern picker from the Site Editor > Add page flow (a known issue) and this post publish screen where you can copy the link: 

Screenshot 2024-04-03 at 6 17 08 PM

**Pull request closed without merging**
