### PR TITLE
Remove more Dashicon component usage

### PR DESCRIPTION
**Pull request by youknowriad**
I'm not 100% certain but I think this removes all the remaining production code usage of the Dashicon component in Gutenberg.

New Icons:

 - appearance (admin-appearance)
 - listIndent (editor-indent)
 - listOutdent (editor-outdent)
 - listUl (editor-ul)
 - listOl (editor-ol)
 - ltr (editor-ltr)
 - plugins (admin-plugins)
 - pullLeft (align-pull-left)
 - pullRight (align-pull-right)
 - tableColAfter
 - tableColBefore
 - tableColDelete
 - tableRowAfter
 - tableRowBefore
 - tableRowDelete
 - wordpress (wordpress-alt)

After this PR, I'm planning to revisit #20003 to reduce the components package bundle size.

### CODE REVIEW

**Comment by youknowriad** [comment]
@jasmussen any thoughts here?

**Comment by jasmussen** [comment]
Nice work!

Could "appearance" be "brush"? I seem to recall we already have one of those, can we combine those two? 

Plugins is similarly hard. It's a power plug, that we use for the plugins menu item. But this one feels a little more appropriate since it's always going to be a power plug. So probably fine to keep.

> listIndent (editor-indent)
listOutdent (editor-outdent)
listUl (editor-ul)
listOl (editor-ol)

I like the material naming here:

format_indent_increase
format_indent_decrease
format_list_bullets
format_list_numbered

The format prefix helps make it explicitly about formatting, which it is, just like we have align and position. 

format_indent and format_outdent could also work.

should we use the same format prefix for "ltr"? There's also an "rtl" dashicon, even if we haven't used it yet. 

> tableColAfter
tableColBefore
tableColDelete
tableRowAfter
tableRowBefore
tableRowDelete

Structure and prefix seems fine. I have a personal preference for spelling out the full "column" instead of just "col", mostly because we don't really have an established pattern for when we abbreviate and when we don't.

> wordpress (wordpress-alt)

This is a tricky one, I personally feel like we should have no logos at all, keep them inline SVGs. However given the context, this is perhaps the one logo we can add. @mtias any thoughts?

**Comment by youknowriad** [comment]
Thanks @jasmussen I applied the changes

**Review by jasmussen — APPROVED** [review]
Ship it!

**Pull request merged**
