### PR TITLE
Fix document title alignment in command palette button

### LINKED ISSUE #53216: Template title not centrally aligned
Screenshot 2023-08-01 at 09 36 44

* Edit a page in the site editor.
* Edit the template for that page.
* Notice the template name in the title bar is mis-aligned.

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/53216.

## Why?
The current alignment looks unintentional.

## How?
1. Absolutely positioning the back button allows the command palette button to fill the container so that the elements within are truly centrally aligned.
2. Add a min-width to the `⌘K` label.
3. Offset left padding on document title based on the width of the `⌘K` label. 

## Before / After
Screenshot 2023-08-01 at 11 02 57

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for sweating this detail. Looks great centered:

Screenshot 2023-08-01 at 13 50 46

I faked this following one, clearly, but it seems like it needs to handle text-eliding better:
Screenshot 2023-08-01 at 13 51 52

**Comment by jameskoster** [comment]
Good spot. That should be fixed.

There are other issues on small screens, but they're beyond the scope of this PR.

**Review by jasmussen — APPROVED** [review]
Screenshot 2023-08-02 at 10 01 24

Yep.

**Comment by jameskoster** [comment]
Made a small adjustment to the back button interaction as suggested by @richtabor in https://github.com/WordPress/gutenberg/pull/53221.


https://github.com/WordPress/gutenberg/assets/846565/fba5e1a9-b429-4994-9340-9725511991cc

**Comment by richtabor** [comment]
Solid.

**Pull request merged**
