### PR TITLE
Add lots of blocks

### LINKED ISSUE #99: Add more blocks to the insertion menu
We should list a high number of blocks to test interactions, search behaviour, and categories.

### PR DESCRIPTION
**Pull request by jasmussen**
This PR intends to add all blocks on https://github.com/WordPress/gutenberg/issues/16 to the inserter, so we can get a feel for how the UI works when it has lots of blocks.

It isn't yet functional. @youknowriad do you have any idea why? Thanks

The intent is to fix #99

### CODE REVIEW

**Comment by youknowriad** [comment]
👀

**Comment by youknowriad** [comment]
you used `categories:` instead of `category:`. Fixed in 6092250.

But the SVGs for the new blocks are broken.

**Comment by jasmussen** [comment]
Thanks @youknowriad, I'll fix up the SVGs.

**Comment by youknowriad** [comment]
@jasmussen I updated the default SVG Height/Width and it looks like it fixed the issues

**Comment by jasmussen** [comment]
HAH, was just trying to push the same :D, you beat me to it.

**Comment by jasmussen** [comment]
@mtias Good to merge, or any other thoughts?

Note, the inserter overall needs much love still, but just want to get this in as a small one.

**Review by youknowriad — APPROVED** [review]
LGTM 🚢

**Pull request merged**
