### PR TITLE
Improve button block appender.

### PR DESCRIPTION
**Pull request by jasmussen**
This is a followup to a previous PR that improved the focus style of the button block appender.

The button block appender is the appender used in horizontal button blocks, such as Social Links, Navigation, Buttons.

This PR does three things:

1. It refactors and cleans up the CSS, so there's less CSS that's unique to each of those.
2. It improves the focus style for the navigation appender yet again.
3. It improves the vertical positioning of the appender button inside the Buttons block.

Before:

Screenshot 2021-01-25 at 15 05 21

Screenshot 2021-01-25 at 15 06 54

After:

Screenshot 2021-01-25 at 15 03 57

Screenshot 2021-01-25 at 15 04 01

Screenshot 2021-01-25 at 15 04 04

Screenshot 2021-01-25 at 15 04 10

Screenshot 2021-01-25 at 15 04 13

Screenshot 2021-01-25 at 15 04 23

Screenshot 2021-01-25 at 15 04 19

When you test this PR, please test every appender. Things should be scoped to touching just the button block appender, but test wider than that regardless.

Also focus specifically on Buttons, Navigation and Social Links blocks. Test both setup states, and fully set up.

### CODE REVIEW

**Comment by jasmussen** [comment]
Note that the very widely spaced out buttons blocks is a pre-existing issue.

**Review by ntsekouras — COMMENTED** [review]
Thanks Joen!

Things seem to work well here. The only thing that I noticed and I'm not sure we want is this change of position in vertical`buttons`:

Before:
Screenshot 2021-01-26 at 9 55 59 AM


After:
Screenshot 2021-01-26 at 9 51 10 AM

>Note that the very widely spaced out buttons blocks is a pre-existing issue.

This is something we need to solve as well. Do you think you can come up with an easy fix?

**Comment by jasmussen** [comment]
Great thoughts, I pushed some fixes:

Screenshot 2021-01-26 at 10 15 27

The issue with buttons is that it's a flex container. There _should_ be a fix, because I believe flex is the right thing to use. But I'll need to look at that separately.

**Review by ntsekouras — APPROVED** [review]
Thanks Joen 🚢

**Review by mkaz — APPROVED** [review]
Looks good, tests well :+1: 
It's good to get the consistency throughout all these similar pieces

**Comment by shaunandrews** [comment]
When I add a vertical Navigation block, I see the following strangeness when focusing on the + button:

image

**Comment by jasmussen** [comment]
Excellent catch, Shaun, of course I should've seen that one coming. Fixing now.

**Comment by jasmussen** [comment]
Alright, should be addressed:

Screenshot 2021-01-27 at 09 54 35

**Review by aristath — APPROVED** [review]

**Review by shaunandrews — APPROVED** [review]

**Comment by jasmussen** [comment]
Thank you for the reviews. I've rebased and discovered a couple of small things that I need to address.

**Comment by jasmussen** [comment]
Alright, after the rebase I noticed a few minor issues in testing:

- The appender by having a height, now caused a shift when selected, because the appender appeared even if it should be empty
- The left margin added to address cases where flexbox would center the button caused issues with the empty group block
- There was some CSS bleed from themes that obscured a similar issue with columns

All of these are fixed now, and it should be good:

<img width="406" alt="Screenshot 2021-02-02 at 09 33 33" src="https://user-images.githubusercontent.com/1204802/106573578-1c2aaf00-653a-11eb-914f-b1dd4d3dae86.png">

<img width="473" alt="Screenshot 2021-02-02 at 09 33 38" src="https://user-images.githubusercontent.com/1204802/106573581-1d5bdc00-653a-11eb-922d-8991ea2aee07.png">

<img width="221" alt="Screenshot 2021-02-02 at 09 33 45" src="https://user-images.githubusercontent.com/1204802/106573590-1f259f80-653a-11eb-92da-acc815663c96.png">

<img width="282" alt="Screenshot 2021-02-02 at 09 33 49" src="https://user-images.githubusercontent.com/1204802/106573594-2056cc80-653a-11eb-9628-577cb507b680.png">

<img width="328" alt="Screenshot 2021-02-02 at 09 33 55" src="https://user-images.githubusercontent.com/1204802/106573598-2187f980-653a-11eb-9cee-6b7e414196cd.png">

<img width="399" alt="Screenshot 2021-02-02 at 09 34 01" src="https://user-images.githubusercontent.com/1204802/106573603-22b92680-653a-11eb-9007-b17e16a8347e.png">

<img width="1051" alt="Screenshot 2021-02-02 at 09 34 06" src="https://user-images.githubusercontent.com/1204802/106573608-23ea5380-653a-11eb-94b5-2f4efb833400.png">

<img width="1069" alt="Screenshot 2021-02-02 at 09 34 10" src="https://user-images.githubusercontent.com/1204802/106573613-251b8080-653a-11eb-8e3c-d09c389bdd65.png">

Here's some demo content if you'd like to test again:

```
<!-- wp:cover {"url":"https://cldup.com/Fz-ASbo2s3.jpg","className":"alignwide"} -->
<div class="wp-block-cover has-background-dim alignwide"><img class="wp-block-cover__image-background" alt="" src="https://cldup.com/Fz-ASbo2s3.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size">Cover</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:navigation {"orientation":"horizontal"} -->
<!-- wp:navigation-link {"label":"Contact","type":"page","id":136,"url":"http://localhost:8888/?page_id=136"} /-->

<!-- wp:navigation-link {"label":"Blog","type":"page","id":138,"url":"http://localhost:8888/?page_id=138"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":139,"url":"http://localhost:8888/?page_id=139"} /-->

<!-- wp:navigation-link {"label":"Work","type":"page","id":140,"url":"http://localhost:8888/?page_id=140"} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":145,"url":"http://localhost:8888/?page_id=145"} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":451,"url":"http://localhost:8888/?page_id=451"} /-->
<!-- /wp:navigation -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 1</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 2</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 3</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 4</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 5</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 6</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">button 7</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:navigation {"orientation":"vertical"} -->
<!-- wp:navigation-link {"label":"Contact","type":"page","id":136,"url":"http://localhost:8888/?page_id=136"} /-->

<!-- wp:navigation-link {"label":"Blog","type":"page","id":138,"url":"http://localhost:8888/?page_id=138"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":139,"url":"http://localhost:8888/?page_id=139"} /-->

<!-- wp:navigation-link {"label":"Work","type":"page","id":140,"url":"http://localhost:8888/?page_id=140"} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":145,"url":"http://localhost:8888/?page_id=145"} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":451,"url":"http://localhost:8888/?page_id=451"} /-->
<!-- /wp:navigation -->

<!-- wp:buttons {"orientation":"vertical"} -->
<div class="wp-block-buttons is-vertical"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Button 1</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Button 2</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:heading -->
<h2>empty group</h2>
<!-- /wp:heading --></div></div>
<!-- /wp:group -->

<!-- wp:social-links -->
<ul class="wp-block-social-links"></ul>
<!-- /wp:social-links -->

<!-- wp:navigation {"orientation":"horizontal"} /-->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"></div></div>
<!-- /wp:group -->
```

Because of the new changes, I'm going to let this one sit for a day or so, and be open to additional testing if deemed necessary. Otherwise I'll merge it tomorrow. Thanks again!

**Pull request merged**
