### PR TITLE
test: E2E test setup script creates Android emulator

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?

Expand the E2E test setup script to ensure the required iOS simulators are
available.

## Why?

Relates to https://github.com/WordPress/gutenberg/issues/55251. Simplify setting
up the E2E test environment by automating the process for creating the required
Android emulators.

## How?

Update the E2E test setup script to leverage `avdmanager` to create the required
Android emulators. Remove now unneeded documentation of manual steps.

## Testing Instructions

**With required emulator unavailable**
1. Delete the Pixel 3 XL via `avdmanager delete avd -n <device-id>`.
2. Run `npm run native test:e2e:setup`
3. Verify the correct Android emulators are created. 

**With required emulator available**
1. Verify the Pixel 3XL emulator is available via `emulator -list-avds`. 
2. Run `npm run native test:e2e:setup`
3. Verify duplicative emulators are not created. 

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 
n/a

### CODE REVIEW

**Comment by dcalhoun** [comment]
👋🏻 @geriux. I believe we once discussed the following error when running `avdmanager` commands. 

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
```

I was able to resolve this error on my local machine by adding the following to my path _before_ my existing `/tools` addition, [sourced from SO](https://askubuntu.com/a/1388761). 

```diff
diff --git a/zshrc b/zshrc
index be83a92..d1ebb77 100644
--- a/zshrc.local
+++ b/zshrc.local
@@ -36,6 +36,7 @@ export TERM="xterm-256color-italic"
 # Set Android SDK for React Native development
 export ANDROID_HOME=$HOME/Library/Android/sdk
 export PATH=$PATH:$ANDROID_HOME/emulator
+export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
 export PATH=$PATH:$ANDROID_HOME/tools
 export PATH=$PATH:$ANDROID_HOME/tools/bin
 export PATH=$PATH:$ANDROID_HOME/platform-tools
```

**Comment by dcalhoun** [comment]
Sorry for the late commits. This should _actually_ be ready for review now. 😅

**Comment by geriux** [comment]
> I was able to resolve this error on my local machine by adding the following to my path _before_ my existing `/tools` addition, [sourced from SO](https://askubuntu.com/a/1388761).

Thank you! Now I'm able to run `avdmanager` 🚀

**Review by geriux — APPROVED** [review]
LGTM! Nice work with the script updates! ⭐ 

- ✅ Created the simulator correctly when it didn't exist.
- ✅ Skipped creating the simulator correctly when it existed.
- ✅ Android tests ran as expected after creating the simulator using the script.

**Pull request merged**
