### PR TITLE
Merge e2e test relying on order into one

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes the intermittent template part e2e test "axe-core" failure.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
Ran the e2e tests two times and the template part test no longer fails.

**Comment by ellatrix** [comment]
Merging. The package lock failure is an existing failure, which will be fixed in #26888.

**Comment by ellatrix** [comment]
My theory:
One of the tests was ending with an open popover, which no other tests do afaik, probably causing axe to try to inject in those frames. Could be something else, but the open popover at the end is something that was unique about that test case, and the axe tests are running _at the end_ of each _test case_.

**Comment by Addison-Stavlo** [comment]
> the open popover at the end is something that was unique about that test case, and the axe tests are running at the end of each test case.

Oh, that could be!  I was a bit thrown off since the error causes the test directly after to fail, as opposed to the test that leaves the popover up itself.  Im hoping that is the issue 🤞 , although: 

> Ran the e2e tests two times and the template part test no longer fails.

The failure has been so intermittent this may not be a great indicator, but it seems like a logical fix and these tests needed to be consolidated either way since they are dependent on each other.

Thanks for checking this out!

**Comment by noahtallen** [comment]
> The failure has been so intermittent this may not be a great indicator

Looking back at the commits on master, it looks like it's not failing anymore! 🎉

**Pull request merged**
