### PR TITLE
URL: Implement custom getQueryArgs, buildQueryString

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to refactor the `@wordpress/url` module to use a custom implementation of parsing and serializing query strings, removing the [`qs`](https://www.npmjs.com/package/qs) dependency in the process. The intent with these changes is to have a stronger contractual guarantee of alignment of behavior between `@wordpress/url` and corresponding PHP functions ([`build_query`](https://developer.wordpress.org/reference/functions/build_query/), [`parse_str`](https://www.php.net/manual/en/function.parse-str.php)). It's expected this may also result in a smaller overall bundle size, as we are not using the full extent of the feature set of `qs`.

**Implementation Notes:**

I had some early hopes to be able to use `URLSearchParams` for what's implemented here, but it behaves quite differently than we expect from these functions, largely in two ways:

- Spaces as `+` vs. as `%20`. `URLSearchParams` uses `%20` (per URL Living Standard). PHP uses `+` (per [RFC1866 form encoding](https://tools.ietf.org/html/rfc1866#section-8.2.1)).
- Object and array values. `URLSearchParams` has limited support for "multiple" values ([`getAll`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/getAll), [`append`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append)), but these are formatted differently than they are in PHP (i.e. neither square brackets nor indices in the argument name). There's also no built-in support for "keyed" arguments.

**Testing Instructions:**

Verify unit tests continue to pass:

```
npm run test-unit
```

### CODE REVIEW

**Comment by aduth** [comment]
>It's expected this may also result in a smaller overall bundle size, as we are not using the full extent of the feature set of qs.

Also seen in the above https://github.com/WordPress/gutenberg/pull/20693#issuecomment-595968856, there is a pretty nice drop. The results of `npm run build` before and after these changes are a difference of `11.1kb` -> `5.5kb` for the `url` bundle.

**Comment by aduth** [comment]
Relevant comment at https://github.com/WordPress/gutenberg/pull/20738#issuecomment-598900899 about the commit 8dfe648a7c2e9ae56152434a7900c35dd6423c34 here.

> > As seen with the changes in [0a6046a](https://github.com/WordPress/gutenberg/commit/0a6046a9013c5bef0456dd15cf0f0f693f747f5e), the new implementation is slightly more strict in regards to assuming the input argument to be a proper URL, not merely any string which happens to contain `?`. While this could limit flexibility, I believe it's an appropriate change given:
> 
> Note that I had to scale this back a bit in #20693. Specifically, there's at least a few occurrences where we rely on an implementation like this:
> 
> ```js
> addQueryArgs( '/wp-json/wp/v2/posts`, { type: 'post' } );
> ```
> 
> And if `@wordpress/url` only supports full URLs, it loses a lot of its usefulness.
> 
> The solution ([8dfe648](https://github.com/WordPress/gutenberg/commit/8dfe648a7c2e9ae56152434a7900c35dd6423c34)) is a bit hacky, effectively treating the input URL as the _path_ of a throwaway base ([second argument of URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)).

It's something I think we should want a consistent approach for in this module. Certain functions, we clearly want to expect a full URL (like `isValidURL`). Others, like `getQueryString`, `addQueryArgs`, `removeQueryArgs`, etc, we might want to be more tolerant about what's received, notably to support use-cases like in the quoted text above where we might want to be able to trigger `fetch` requests using an root-relative path.

Maybe the compromise is that for such functions, we _specifically detect_ if the input is a root-relative URL and, if it is, construct `URL` with a fake base.

e.g.

```js
let base;
if ( url.startsWith( '/' ) ) {
    base = 'https://example.com';
}

const urlInstance = new URL( url, base );
```

**Comment by sirreal** [comment]
> Maybe the compromise is that for such functions, we _specifically detect_ if the input is a root-relative URL and, if it is, construct `URL` with a fake base.
> 
> e.g.
> 
> ```js
> let base;
> if ( url.startsWith( '/' ) ) {
>     base = 'https://example.com';
> }
> 
> const urlInstance = new URL( url, base );
> ```

There's some prior art for this approach by @sgomes. See https://github.com/Automattic/wp-calypso/blob/397d7592efea16154218b424602b15db64063361/client/lib/url/format.ts#L49 for an example.

**Comment by sgomes** [comment]
> There's some prior art for this approach by @sgomes. See https://github.com/Automattic/wp-calypso/blob/397d7592efea16154218b424602b15db64063361/client/lib/url/format.ts#L49 for an example.

Calypso's `lib/url` will likely become an independent package at some point. I expect it to have no dependencies but require a `URL`/`URLSearchParams` implementation present, either natively or through a polyfill.

I'm happy to accelerate any efforts in packaging it up if anyone's planning to reuse it!

**Comment by aduth** [comment]
@sirreal @sgomes That's interesting, thanks for sharing! I could definitely see some value in some of this, such as [detecting the "type" of a URL](https://github.com/Automattic/wp-calypso/blob/397d7592efea16154218b424602b15db64063361/client/lib/url/url-type.ts). I think at least for the immediate purposes here, the [current implementation proposed here](https://github.com/WordPress/gutenberg/pull/20693/files#diff-cd98ace054f64f8608d622942df0fb5bL16-R16) more-or-less matches [how it's implemented in Calypso's `lib/url`](https://github.com/Automattic/wp-calypso/blob/397d7592efea16154218b424602b15db64063361/client/lib/url/format.ts#L49), though perhaps relying a little too much on the `URL` constructor to do the heavy lifting.

For me, it's largely a question of documentation. Some of the functions of this module _demand_ to operate only with a full URL (`isValidURL`, `getQueryString` as of #20738 and then reverted here). In the case of `isValidURL`, it makes sense. So the uncertainty I have now is around (a) determining whether `isValidURL` is the sole exception, (b) documenting these expectations, and (c) implementing those expectations consistently.

**Comment by aduth** [comment]
I just realized this pull request was left with the "In Progress" label. As far as I can recall, this is complete and ready for review.

**Review by gziolo — APPROVED** [review]
I rebased this PR to make it mergeable again. I plan to land it as soon as CI turns green.

**Comment by gziolo** [comment]
@sirreal, any idea why TypeScript errors:

> Error: packages/url/src/add-query-args.js(5,34): error TS6307: File ‘/home/runner/work/gutenberg/gutenberg/packages/url/src/build-query-string.js’ is not listed within the file list of project ‘/home/runner/work/gutenberg/gutenberg/packages/url/tsconfig.json’. Projects must list all files or use an ‘include’ pattern.

**Comment by sirreal** [comment]
FYI @sgomes - removing `qs` dependency when working with URLs.

**Comment by gziolo** [comment]
There is one failing e2e test but I saw it before in other PRs and it doesn't seem to be relevant.

**Pull request merged**
