### PR TITLE
Site Editor: remove default page slug

### LINKED ISSUE #67539: Post title: if a name isn't set in the creation process, the page title isn't visible in the editor
Titling this for the Post Title block since it's the same as for the Page Title. Using Gutenberg nightly (Version 19.9.20241203) with WP 6.7.1 and TT5, I found that if I don't name a page when creating one, a post title block is not rendered in the template for me to then edit:

https://github.com/user-attachments/assets/2bae7bdb-1fba-4d89-8d71-1e33d0b8fb7f

**Replication steps**

1. Open Appearance > Editor
2. Head to Pages
3. Add a new page and don't give it a title
4. Notice there's no post title block to edit and name the page.

### PR DESCRIPTION
**Pull request by ramonjd**
## What?
 Resolves https://github.com/WordPress/gutenberg/issues/67539

Removes the default slug assignment when creating an untitled page in the site editor.

## Why?

WordPress will try to create a slug from the title. WordPress will also look for a corresponding `page-` template that [matches the slug name](https://github.com/wordpress/wordpress-develop/blob/8eb8d634095e9b6716e977abd1085bab8d703e6f/src/wp-includes/template.php#L460-L460). 

Therefore if a page template exists with the name page-no-title, WordPress will apply that template to any page with that unique slug. 

This causes unexpected template assignment. TT4 and TT5 most notably, both of which have `page-no-title` templates! 

It's also inconsistent since subsequent untitled pages created in the site editor will use the default template, slugs being unique. 

## How?

Anyway, let's just use WordPress's default behavior, which is to create a unique slug using [wp_unique_post_slug](https://developer.wordpress.org/reference/functions/wp_unique_post_slug/)  if none exists.

This is what happens in the post editor. Why should the site editor get special treatment?

It shouldn't! That's why.

I have spoken.

## Testing Instructions

Head to the Site Editor and create page.

Don't give it a title!!

Once created, check out the slug in the page settings in the right hand side panel. It should be something like `"$page_id-$suffix"`, e.g., `12-2`

That's it!

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM 👍

**Review by youknowriad — APPROVED** [review]
It works well in my tests:

 - I confirmed that the template picked is the default one for empty pages
 - I confirmed that if you type a title, a correct slug is assigned.

**Review by tyxla — APPROVED** [review]
Thanks @ramonjd 🙌 

Makes sense and works well in my testing ✅ 

:shipit:

**Review by carolinan — APPROVED** [review]

**Comment by ramonjd** [comment]
Thanks for testing, folks!!

The [E2E fails](https://github.com/WordPress/gutenberg/actions/runs/12195898765?pr=67673) are real but I can also see the tests failing on trunk locally. 

The issue seems to be that after creating a page and adding some groups and paragraphs, the post-content block and all its children are disabled. They have a class of `.is-editing-disabled` and are inert so nothing can be selected. 

It does not occur in manual testing under the same test conditions 🤔 

I'll leave this PR to simmer until I can work out what's happening on Monday.

**Comment by ramonjd** [comment]
> The [E2E fails](https://github.com/WordPress/gutenberg/actions/runs/12195898765?pr=67673) are real but I can also see the tests failing on trunk locally.

Untrue. I was tripping.

> The issue seems to be that after creating a page and adding some groups and paragraphs, the post-content block and all its children are disabled. They have a class of .is-editing-disabled and are inert so nothing can be selected.

True, on this branch. I don't know why it only affected specific tests, but I tracked it down to the absence of a `slug` key for new pages. The key must be there, even when the value is `undefined`. But only for the tests. Manual testing works fine. 

I don't know yet why. I've checked core data actions and reducers, and places where the slug is fetched.

Anyway, I've kept the slug key, but removed 'No title' and replaced with `undefined`.

The effect is the same and the tests pass.

I checked:

- Pages with no title are assigned a generated slug
- Pages with titles are assigned slugs based on the titles as expected

**Pull request merged**
