### PR TITLE
Add: Sidebar/widget block

### PR DESCRIPTION
**Pull request by scruffian**
## Description
This is an idea to work with this PR: https://href.li/?https://github.com/Automattic/themes/pull/4369

This is just a light wrapper around the WordPress function `dynamic_sidebar` so that we can display widget areas in block themes. I noticed that there's already similar code inside the `edit-widgets` package but I couldn't work out how to implement it.

This doesn't yet work in the editor - the purpose of the PR is really just to get feedback on the idea and see if there's a better way to achieve the same thing.

## How has this been tested?
- Add this to a post: `<!-- wp:sidebar-widget-area {"id":"sidebar-1"} /-->`
- Switch to a theme that supports sidebars (e.g. Seedlet)
- Add some content to the sidebar in the Widgets section
- Confirm that the content shows on the front end.

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by draganescu** [comment]
Do we expect widget areas to move as they are to universal themes?

**Comment by scruffian** [comment]
> Do we expect widget areas to move as they are to universal themes?

I'm not sure. What would be useful is to be able to define a portion of a block theme that can contain widgets, so that it can be modified by users without using the site editor.

**Comment by carolinan** [comment]
Please help me understand, is this only about backwards compatibility?

You wrote that, this is about not having to use the site editor -but for block themes, the widget screen is not present, so there is no natural way to edit and move the widgets without changing the block in any of the multiple editors.
What are the benefits of keep using old widget areas over template parts or patterns?
What are the benefits over adding a "sidebar" template part?

**Comment by carolinan** [comment]
Also, one of the problems with the current widget area functions is the naming, widget areas are not only sidebars, so I would suggest removing that part of the naming.

**Comment by scruffian** [comment]
This is part of the work we are doing on Universal Themes. The benefit of this approach is that it would allow users who are using the old wp-admin interfaces to keep customizing their theme using the same tools as before, even if its a block theme.

The benefit of this is that we can start building block themes now before the site editor is ready, and then when the Site Editor (and users) are ready, they can transition to the new tool without switching themes.

**Comment by carolinan** [comment]
Thank you for explaining.
I think it would be easier for those who are interested to find the PR and provide feedback if there was a (clearly described) issue attached, as there are past discussions related to this.

Is there an overview issue for "the work we are doing on Universal Themes"?

**Pull request closed without merging**
