### PR TITLE
Add more menu to customize widgets

### LINKED ISSUE #30886: Customizer Widgets: Add missing ellipses Options menu in top bar
Opening this issue to discuss adding the ellipses menu that's available in the top bar of the post editor to the Customizer Widgets screen. This is a companion issue to #27564, which is focused on the standalone Widgets screen.

The ellipses menu contains several accessibility/usability additions to the editor experience (like the ability to access Keyboard shortcuts and the Welcome Guide) so it would be great to add some of these options, even if in a condensed format for now.

Taking a look at the existing options (left), the "Tools" section is the one that feels most high priority:

Tool Options: Block Manager, Manage Reusable blocks, Keyboard shortcuts, Welcome Guide, Copy all content, Help

### PR DESCRIPTION
**Pull request by talldan**
## Description
Closes #30886

Adds the editor 'more menu' to the customize editor.

I haven't added 'Copy all content' yet, as the post editor version copies post content. I think this should be possible (would need to serialize blocks), but I'd like to address it in a follow-up.

## How has this been tested?
1. Test that the preferences work (except for the welcome guide, which is being implemented in a separate PR).

## Screenshots 
Screenshot 2021-05-19 at 1 21 50 pm

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by noisysocks** [comment]
Looks nice! The only issue I noticed is that pressing <kbd>Esc</kbd> when the menu is open causes the Customizer to navigate back.

**Comment by talldan** [comment]
> Looks nice! The only issue I noticed is that pressing Esc when the menu is open causes the Customizer to navigate back.

Yeah, I'm not sure how to fix that. The popover component does already call `stopPropagation` when Escape is pressed, but the customizer has already switched screens at that point. I'll look into it.

**Review by noisysocks — APPROVED** [review]
We can fix the <kbd>Esc</kbd> thing in a follow-up if you want. This is good 👍

**Comment by talldan** [comment]
There's also the same issue with the escape key in the customizer when trying to use:
- Navigation mode
- Block settings menu

So I think we need to treat this as a separate issue and disable escape for the entire panel 😬 

I've reported it in https://github.com/WordPress/gutenberg/issues/31972.

**Comment by ellatrix** [comment]
Why was this merged with failing tests? It's not because trunk is failing that that's ok?

**Comment by critterverse** [comment]
Awesome 😁  Only notes here are that I think the menu should appear in the top Customizer bar next to the Publish button (even though it's related to the editor, it's getting a little lost where it is currently). 

Minor note but it would be nice to have the "Preferences" subheading (same style as "View" or "Tools") above the last option.

>I've reported it in #31972.

Related to Esc key functionality: #31730

**Pull request merged**
