### PR TITLE
Align rename modals

### PR DESCRIPTION
**Pull request by jameskoster**
Follow-up to #62788.

The vast majority of rename modals appear in the following format:

Screenshot 2024-06-26 at 12 08 04

* Succinct title
* Visible "Name" label
* "Save" button
* 40px buttons

This PR brings a couple of outliers into alignment with this convention.

### Navigation menus

| Before | After |
| --- | --- |
| Screenshot 2024-06-26 at 12 10 18 | Screenshot 2024-06-26 at 14 04 27 |

Note the visible label. 

### Renaming blocks

| Before | After |
| --- | --- |
| Screenshot 2024-06-26 at 12 09 19 | Screenshot 2024-06-26 at 14 06 10 |
| Screenshot 2024-06-26 at 12 09 30 | Screenshot 2024-06-27 at 11 11 58 |

### Renaming custom views
| Before | After |
| --- | --- |
| Screenshot 2024-06-26 at 12 58 28 |  Screenshot 2024-06-26 at 14 14 39 |

* Changed modal heading
* Button size = 40px
* Changed button label

## Testing Instructions
1. Rename a navigation menu
2. Observe the modal matches the 'After' screenshot above.
3. Rename a block without overrides
4. Observe the modal matches the 'After' screenshot above.
5. Rename a block with overrides
6. Observe the modal matches the 'After' screenshot above (the one with the notice).
7. Enable the custom data views experiment and rename a custom view
8. Observe the modal matches the 'After' screenshot above.

## Additional alignment considerations

* Is the 'Name' label worth displaying above the input, or should it be visually hidden? I can see arguments both ways.
* Should the primary button read "Save" or "Rename". In most confirmation dialogs the primary button repeats the action, so I lean towards the latter, but keen to hear thoughts.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice work.

The only one I don't agree with is the notice change, this one:

> In this case the warning is moved out of the help text into a Notice which seems appropriate given the potential consequences.

I can see sense in using the basic "Name" label for the input field, but I'd keep the help text below, and keep it as plain body text. The consequences are important to understand, but it doesn't need further elevation since you're already in a modal context.

This is also mostly about that particular notice style being generally out of place in the block editor, it doesn't share any DNA with the snackbar, for instance.

**Review by t-hamano — COMMENTED** [review]
I submitted a commit to fix the e2e tests.

Regarding the notice message, I also feel it's a bit too noticeable.

**Comment by jameskoster** [comment]
Good feedback, I'll change the notice 👍 

How do y'all feel about these questions?

> * Is the 'Name' label worth displaying above the input, or should it be visually hidden? I can see arguments both ways.
> * Should the primary button read "Save" or "Rename". In most confirmation dialogs the primary button repeats the action, so I lean towards the latter, but keen to hear thoughts.

**Comment by jasmussen** [comment]
> Is the 'Name' label worth displaying above the input, or should it be visually hidden? I can see arguments both ways.

No strong opinion.

> Should the primary button read "Save" or "Rename". In most confirmation dialogs the primary button repeats the action, so I lean towards the latter, but keen to hear thoughts.

Save read well to me. It's active language just like Rename, but benefits from the reduced duplication, while still being the action taken.

**Comment by t-hamano** [comment]
> Good feedback, I'll change the notice 👍
> 
> How do y'all feel about these questions?
> 
> > * Is the 'Name' label worth displaying above the input, or should it be visually hidden? I can see arguments both ways.
> > * Should the primary button read "Save" or "Rename". In most confirmation dialogs the primary button repeats the action, so I lean towards the latter, but keen to hear thoughts.

I think accessibility feedback is needed on this.

I remember that @afercia submitted some issues on this point to improve the consistency/accessibility of modals/dialogs. He might have some advice.

**Comment by afercia** [comment]
Generally, visible labels are always better especially with complex forms with several input fields. 
In this case, the form is very simple and there's no ambiguity as the context is clearly about changing the name. However, a visible label doesn't harm and ideally it should be the default pattern for all inputs unless there's a very, very, good reason to make it visually hidden.

Re: the buttons text, I provided some previous feedback but that was specifically about the `ConfirmDialog` component as one of the purposes of its introduction was to be able to provide a more descriptive label than 'Ok'. See https://github.com/WordPress/gutenberg/issues/60360. The `ConfirmDialog` doesn't have a title so it makes sense to use the action for the button label. Instead, these modal dialogs do have a title: 'Rename'. I don't have a strong opinion but probably avoiding duplication is best?

**Comment by jameskoster** [comment]
I lean towards avoiding duplication too. But I am also slightly bothered by the inconsistency here:

Screenshot 2024-06-27 at 15 51 46

Screenshot 2024-06-27 at 15 51 32

**Comment by t-hamano** [comment]
> I lean towards avoiding duplication too. But I am also slightly bothered by the inconsistency here:

These inconsistencies will need to be fixed in the future.

Considering avoiding the "OK" label and avoiding duplicate labels, my options for this PR are "Save", "Update", and "Apply".

Of these, I prefer "Save", which means we'll ship this PR as is.

**Comment by afercia** [comment]
> I lean towards avoiding duplication too. But I am also slightly bothered by the inconsistency here:

Eheh yes that's a good case. I'd love to see some established guidelines added to the documentation of these components. Maybe it is worth creating a follow-up issue?.

For reference, regarding the `ConfirmDialog` component, the desire to have a more descriptive label for the 'OK' button was outlined in the original PR https://github.com/WordPress/gutenberg/issues/16583. That's mentioned in the readme file under the [Best practices](https://github.com/WordPress/gutenberg/blob/82598f94a50d5b34df56b40db770c86f50989b1d/packages/components/src/confirm-dialog/README.md#best-practices) section. It could be improved though.
In the same way, maybe worth considering adding guide lines for the buttons in the Modal readme as well?

**Comment by jameskoster** [comment]
I'm going to flip-flop on this and lean towards repetition 🙊 for two main reasons:

1. Creates consistency (in terms of button labels) with confirmdialog instances/guidance.
2. Functions as a clear convention to follow for actions that don't have an obvious confirmatory action label. 
 
I could be swayed back again, but I'm curious... if not "Duplicate", what would the primary button label be in the `duplicate` modal? "Save", "Apply", "Update" don't quite work for me. The repetition could arguably be seen as useful here because it removes any ambiguity. 

In any case, it's a broader topic, so I'm happy to ship this PR as is, and discuss the labels further in a separate issue/pr.

**Review by t-hamano — APPROVED** [review]
> In any case, it's a broader topic, so I'm happy to ship this PR as is, and discuss the labels further in a separate issue/pr.

I agree with this. This PR only includes one button text change, and by unifying everything to "Save", we have improved consistency.

I think the other issues can be addressed by following up.

**Pull request merged**
