### PR TITLE
[NRMobile] Style separator block to extend until the edges

### LINKED ISSUE #2018: Separator block line isn't wide enough
A minor thing, but noticeable when you start adding similar-looking blocks like `Read More` and `Page Break` — the separator line doesn't quite span the whole width. It looks like ~8px from reaching each side of the container. Screenshot for reference:

<a href="https://user-images.githubusercontent.com/1200432/76650508-c7043a00-6530-11ea-9817-27dae2e24931.png"></a>

### PR DESCRIPTION
**Pull request by etoledom**
fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2018

## Description

This PR styles the Separator block to extend the HR line until the edges:

Simulator Screen Shot - iPhone 11 - 2020-11-05 at 12 55 32

cc @iamthomasbishop 

## How has this been tested?

- Run the project.
- Add a Separator block.
- Check that the line extends to the edges.
  - Can compare with `More` block.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by guarani — APPROVED** [review]
LGTM! 🎉

**Comment by etoledom** [comment]
Fixed the line color as requested by @iamthomasbishop 

Screenshot 2020-11-18 at 10 33 04

**Comment by iamthomasbishop** [comment]
Thank you, @etoledom ! Do the colors also match in dark mode?

**Comment by jd-alexander** [comment]
@iamthomasbishop this is how it looks in dark mode on Android. I will let @etoledom chime in to answer your question. 

<kbd></kbd>

**Comment by etoledom** [comment]
> Do the colors also match in dark mode?
Yes 😁 - as @jd-alexander showed (thank you!)

**Comment by iamthomasbishop** [comment]
@etoledom @jd-alexander  Awesomeness, looks great!

**Pull request merged**
