### PR TITLE
Site Editor: style resets for top level page

### PR DESCRIPTION
**Pull request by vindl**
## Description

Allow Site Editor to be loaded as a top level page. So far the style resets only worked when this page has been added as submenu item of Gutenberg menu.

## How has this been tested?

There are no functional or visual changes. Smoke tested the affected experimental sections to make sure they still work as before.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — APPROVED** [review]
It seems this is necessary to get the styles properly set up when setting the Site Editor up as a toplevel item as opposed to the gutenberg submenu which we may want to support from core sometime in the future anyways.

However, maybe we should consider adding this hook as one of the defaults here as well then: https://github.com/WordPress/gutenberg/blob/ae44d9099d895dcf1078e255ece4fcb0301646bb/lib/edit-site-page.php#L38

**Comment by vindl** [comment]
> However, maybe we should consider adding this hook as one of the defaults here as well then:

@Addison-Stavlo I updated the PR to account for this and also refactored some checks where this page string was hardcoded.

**Review by Addison-Stavlo — APPROVED** [review]
I like the additions!  Tested and this works as expected.

**Comment by youknowriad** [comment]
I'm not sure I understand the changes here. This seems like something that is targetted for a use-case where edit-site is used in a context where it's not meant to be used. It's not clear why these styles exists. And this will most likely cause breakage since if we don't use them, we can remove them without notice.

**Comment by vindl** [comment]
> I'm not sure I understand the changes here. This seems like something that is targetted for a use-case where edit-site is used in a context where it's not meant to be used. It's not clear why these styles exists. And this will most likely cause breakage since if we don't use them, we can remove them without notice.

We would like to open a possibility of exposing Site Editor as a top level item in wp-admin menu. Prior to this, if it wasn't a subitem of Gutenberg menu it would bail early in the initialize function which would prevent it from working as a top level page. My hope was that this would be useful in the future too, since once it stops being an experimental feature we'll probably want to expose it as a top-level item, or place it next to Customizer.

**Comment by youknowriad** [comment]
Got it, what about these two options:

 - Consider making it a top level page in Gutenberg directly. cc @mtias 
 - Add the generated sub page class to your top level page integration.

**Comment by Addison-Stavlo** [comment]
I think the `gutenberg_is_edit_site_page` function cleans up the readability of the multiple condition checks it is used in, as well as extracts the 'magic number'-y string to be defined in 1 place.

> Consider making it a top level page in Gutenberg directly. 

This should definitely be considered.  As hiding as a subpage to Gutenberg seems like a temporary location to have for development of the experiment, while having it at the top level seems to fit in more for how it will be used in the end (comparatively with Pages and Posts).

If we don't want to do this here and are worried about adding the toplevel hook in explicitly to the list, we could alternatively add an `apply_filters` to the list in this function and add it externally from there.  As well as adding the subpage class on our end for the css styles.

**Comment by vindl** [comment]
> Add the generated sub page class to your top level page integration.

This would resolve the styling issue but we'd still be left with overriding the hook, so I'm leaning towards making it a top level page in Gutenberg.

**Pull request merged**
