### PR TITLE
Update trash icon

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Update the Trash icon

## Why?
The current icon has a couple of issues:

Screenshot 2023-11-27 at 17 28 31

1. It breaks out of the internal 16x16 frame. This isn't a hard rule, but is generally reserved for addressing optical balance issues which don't really exist with this icon.
2. The strokes are too large (1.71 compared to 1.5 of other icons).

These issues feel very clear when you see the icon next to others in the set, like in the new page management view:

Screenshot 2023-11-27 at 17 25 55

## A new icon
Let's design a new icon. Here are a few concepts I put together. 

Trash

The one in the PR looks like this but I am by no means married to it:

trash2

Screenshot 2023-11-27 at 18 22 08

Screenshot 2023-11-27 at 17 25 47

Let's explore and discuss options :)

### CODE REVIEW

**Comment by richtabor** [comment]
I like it fine; other than the 0.25 placement on the "handle" of the can. We have to use .5 increments. 
CleanShot 2023-11-28 at 00 30 22

**Comment by jasmussen** [comment]
Thanks for updating this icon, the existing icon has a big footprint and the wrong stroke width. 

That said, the silhouette feels a little bit busy with all the lines, I wonder if we can reduce. Do we need the "folds" to indicate bent metal in the center, or would it read as trash still if it did not have the vertical lines?

Also, I wonder if the handle actually has to have a hole in it. Could the handle be flush with the lid? Like so:

Screenshot 2023-11-28 at 10 07 54

Screenshot 2023-11-28 at 10 10 24

_These are just random icons I found on the web and only the handle is a suggestion here_.

No blockers on my end, but from my angle what's important to balance is this view here (thank you for testing and sharing that context):

Screenshot 2023-11-28 at 10 10 59

If you squint, ideally the external link and trash can should be the same shade of gray blobs. Right now trash is a bit darker in that case.

**Comment by jameskoster** [comment]
Here's a version that passes the squint test a bit better, and fixes the placement:

Screenshot 2023-11-28 at 13 24 03

@jasmussen imo the icon looks a bit top-heavy with a filled handle – that's one of my gripes with the current version.

Please feel free to push any alternatives!

**Comment by jasmussen** [comment]
I like that one, happy to try it! The handle may be too rounded now, perhaps a straight one with rounded edges instead of an oval? But otherwise, nice!

**Comment by jameskoster** [comment]
It starts to verge a bit into 'battery' territory with the flat handle, at least to my eye:

Screenshot 2023-11-28 at 13 57 26

Top is flat handle, bottom is current as of this PR.

**Comment by jasmussen** [comment]
Ah right. Sorry about the detours, and thanks for the iterations. Unless Rich objects, I think you can merge the rounded one.

**Review by jasmussen — APPROVED** [review]

**Comment by jameskoster** [comment]
I'll merge. Happy to tweak in a follow-up if needed!

**Pull request merged**
