### PR TITLE
Fix scroll jitter in Customize Widgets

### PR DESCRIPTION
**Pull request by stokesman**
Follow up of #32140 which has left the editor with some scroll jitter. No separate issue is made so including reproduction steps here for confirmation of the issue.

UPDATE: So far I can only reproduce this with the Twenty Twenty theme active. It's not clear why other themes seem to prevent the sticky behavior of the Customizer header only in the widgets editor.

## Steps to reproduce
1. With Twenty Twenty theme active, navigate to a widget area in the Customizer
2. If there's not enough content to cause overflow, either add enough content or shorten the window.
3. Scroll down and then scroll up just a bit
4. Observe the jitter or repeat step 3 several times as it does not always cause the jitter
5. Alternatively, scroll back to the top while looking out for the jump of the header as seen a the beginning of the video below

## Screen recording
The video first shows how the jump can be spotted when returning to the top of the scroll. A bit later, it is shown how the jitter may be triggered.

https://user-images.githubusercontent.com/9000376/120966046-85097a00-c71a-11eb-8924-ae5e73322d5c.mp4

## About the apparent cause and changes in the PR
The negative `margin-top` of the sticky header is cleared during upward scrolling as part of the customizer’s js-controlled “sticky” positioning. Overriding that to keep the margin constantly applied avoids the issue.

## How has this been tested?
In the customizer trying and failing to recreate the problems shown in the screen recording.

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
Tried giving this a test today, but I'm struggling to reproduce it. I've noticed sometimes the customizer doesn't enable the sticky header area, and I don't know what determines that, but today `customize-section-title` doesn't have the `is-sticky` class at all 🤔

**Comment by stokesman** [comment]
Thanks for testing. How odd! I tested today with gutenberg.run and saw the same as you, the lack of any sticky related classes being applied when in the widgets editor. Then I tried the latest trunk on my local setup and found it still has this issue. Turns out that the theme somehow has something to do with it. Using Twenty Twenty in either gutenberg.run or locally the issue is present. All the other themes I tried aren't sticking the header. 🤔  I don't think that means it's an issue for Twenty Twenty because the sticky header is expected. It was apparently the reason for these overrides/#32140.

I've not figured out why this can vary between themes but I still think this PR is FTW. It also fixes one other tiny thing that's present no matter the theme:
image
Notice the element is two pixels outside of it's parent boundary at the top of the scroll area.
https://github.com/WordPress/gutenberg/blob/1074fb3219fcf5f257b9bdeec1a0eb31a6b1ed19/packages/customize-widgets/src/controls/style.scss#L17
Should be `12px`.

**Review by adamziel — APPROVED** [review]
I managed to reproduce the problem and this PR, in fact, fixes it. The test failures are likely unrelated – I bet everything will work if you rebase.

**Comment by stokesman** [comment]
Thanks Adam!

This is rebased and now the only failure is the same android e2e that seems broken in trunk.

**Comment by talldan** [comment]
This PR is purely customizer screen scss, so can't be affecting react native. Given that I'll merge the PR. Thanks for fixing this @stokesman!

**Pull request merged**
