### PR TITLE
Autocomplete: Fix unexpected block insertion during IME composition

### LINKED ISSUE #45496: AutocompleteUI: Forward slash inserter doesn't work in Japanese
### Description

At least in the Japanese input system, the block list are not properly filtered when using the forward slash inserter.

Because of the vast number of characters in the Japanese language ( including Kanji), it is not possible to input characters directly on a standard keyboard. Therefore, after entering "**hiragana**" characters, we choose which character to convert to and confirm with the `Enter` key.

In WordPress 6.0, the autocomplete popover is retained after we press Enter to "submit" a candidate, allowing me to select the block that matches the keyword.

In WordPress 6.1, the forward slash inserter no longer works because the block at the beginning of the candidate is inserted the moment I press the `enter` key. However, autocomplete works correctly when **pasting** a string containing forward slashes.

I believe this problem also occurs in languages where character output must be confirmed with the Enter key, for example Chinese.

### Step-by-step reproduction instructions

Since this test requires the use of Japanese input for keyboard input, I expect users to test the Japanese keyboard.

- Change the site language to Japanese (`日本語`).
- On the block editor, type `/みだし`. `みだし` is a hiragana character used to convert the Japanese translation of "heading" into `見出し`.
- Confirm that the autocomplete popover disappears and the block at the top of the list is inserted unintentionally when the Enter key is pressed to convert it to `見出し`

### WordPress 6.0

1. Autocomplete works correctly when pasting a string containing forward slashes
2. Autocomplete works correctly when the block name "heading" is entered
3. Autocomplete works correctly even if the enter key is pressed to convert the Japanese name of a block in Japanese input

https://user-images.githubusercontent.com/54422211/199558019-c8aa5a99-6536-41b7-9762-bb53ab49ce1b.mp4

### WordPress 6.1 (with / without Gutenberg Plugin)

1. Autocomplete works correctly when pasting a string containing forward slashes
2. Autocomplete works correctly when the block name "heading" is entered
3. Autocomplete **DOESN'T** work correctly when the Enter key is pressed to convert to the Japanese name of a block in Japanese input

https://user-images.githubusercontent.com/54422211/199557994-43d1a607-df1c-4283-9341-3c3848fc8d47.mp4

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix: #45496
Please refer to the issue for details and causes of this problem.

## What?
This PR fixes a problem in inserting a block using the slash key, where the Enter key to confirm input causes an unexpected block to be inserted.

## Why?
Details are given in [the issue comments](https://github.com/WordPress/gutenberg/issues/45496#issuecomment-1301891971), but for example, in Japanese, we press the Enter key after selecting a character from the candidates to confirm the input.

candidates

 In #43432, `event.keyCode` was replaced by `event.code`. But I confirmed `event.code` detects the Enter key to confirm the input, resulting in the unintended insertion of a block.

## How?
I found that `event.key` is valid: any keystroke before the input is confirmed, including the Enter key, returns the string `Process`.

process

## Testing Instructions

This PR may be difficult to test because it requires Japanese input, see "Step-by-step reproduction instructions" in #45496.

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]
Looks good

**Comment by t-hamano** [comment]
@ellatrix 
Thanks for the quick review!

@ciampo, @mirka 

I think this issue should also be checked for other components refactored into `event.code`.
I'm concerned about `FormTokenFiled` and `ComboBoxControl`, as indicated by [this](https://github.com/WordPress/gutenberg/pull/43432#issuecomment-1224050363) and [this comment](https://github.com/WordPress/gutenberg/pull/43432#issuecomment-1224068518).

**Comment by ciampo** [comment]
Thank you @t-hamano for investigating and working on a fix!

> I think this issue should also be checked for other components refactored into event.code.
> I'm concerned about FormTokenFiled and ComboBoxControl, as indicated by https://github.com/WordPress/gutenberg/pull/43432#issuecomment-1224050363 and https://github.com/WordPress/gutenberg/pull/43432#issuecomment-1224068518.

That's definitely a possibility — would you actually have time to investigate those components, since you are very familiar with the issue and how to reproduce it? Thank you! 🙏

**Comment by t-hamano** [comment]
@ciampo 
I see, I will look into it and submit a PR if necessary 👍

**Comment by mirka** [comment]
@t-hamano Thank you so much for flagging! I'll also add Modal to the list of confirmed affected components — if there's some kind of text input in the modal and somebody hits <kbd>Esc</kbd> to escape out of IME composition, the modal will close. Could you fix that too, if you're addressing them all together? 🙏

I fear that this will become a common pitfall as people start switching from `event.keyCode`. The [MDN article](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) literally suggests `event.code` as an alternative 😬 Unfortunately this kind of thing is hard to set up a lint rule for in a non-noisy way. We'll probably have to keep an eye out for this in code reviews.

📌 In short: When listening to key events that potentially fire from text inputs, `event.key` is the way to go.

**Comment by t-hamano** [comment]
> if there's some kind of text input in the modal and somebody hits Esc to escape out of IME composition, the modal will close. Could you fix that too, if you're addressing them all together? 🙏

Oh, it wasn't just the Enter key that should be considered. I would like to address them as well 👍

**Pull request merged**
