### PR TITLE
Polish block manager search.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Polish the block manager, per feedback in https://github.com/WordPress/gutenberg/pull/32166#issuecomment-866777351. Notably:

- Rephrasing title
- Addition of description
- Simplification of search

Current status:

now

To Riad's feedback in [this comment](https://github.com/WordPress/gutenberg/pull/32166#issuecomment-866778380):

> I think a SearchControl component extracted from the inserter one would be a good addition to the UI components we have.

It would be nice to use this PR to do that, and leverage that new component both for this block manager, and the inserter.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
@stokesman or @gwwar if any of you have time or inclination, I'd love your help with the second part of this one, extracting a generic search component. I have an idea of the basics of doing so, but my experiene with regards to handling the state of things is still early. If you have time, please feel free to push directly to the branch.

**Comment by mtias** [comment]
Wonderful!

> I'd love your help with the second part of this one, extracting a generic search component.

We don't need to do this now for this pass.

**Comment by youknowriad** [comment]
The code changes here look good, there's a snapshot to update for the unit tests.
The SearchControl component can be added separately.

**Comment by jasmussen** [comment]
Thank you, should be updated!

**Comment by youknowriad** [comment]
The design of the search is a bit different than the inserter (Icons on the right) but I think introducing the shared component should fix that if we think the placeholder as a sufficient change now.

**Review by youknowriad — APPROVED** [review]

**Comment by jasmussen** [comment]
I'm perpetually on deck to push CSS tweaks and polish to anyone who will work with me on such things. Always happy to follow up.

**Comment by youknowriad** [comment]
Let's get this in and I'll try to create that component.

**Comment by youknowriad** [comment]
@jasmussen I opened https://github.com/WordPress/gutenberg/pull/32935 to explore that component.

**Comment by stokesman** [comment]
I like the changes here. The only thing I'd like to note is all the other section titles in the preferences modal have a suggestive phrasing and now this one is the odd one out. If that inconsistency is at all a concern, maybe later we could look at changing the others. I've never liked the suggestive ones.

**Comment by jasmussen** [comment]
That's a great point @stokesman. It's not something I feel super strongly about, but we could do some verbiage polish here and there, for example we might be able to change the "Choose how you interact with blocks" to "Block interactions". I'm not sure if it needs further help text than that, frankly, since there's helptext for both toggles.

**Comment by mtias** [comment]
Yes, I'd prefer titles to be more direct and adding longer descriptions with more context below.

**Comment by jasmussen** [comment]
Since this one is approved, and has a pending sub-PR to be merged in, I think it'd be good to land this one as an interim step. Then I'll follow up with a separate PR to rephrase the other headings to be more direct and with help text.

**Pull request merged**
