### PR TITLE
Plugin: Update package-lock.json

### PR DESCRIPTION
**Pull request by aduth**
Previously: https://github.com/WordPress/gutenberg/pull/14664/files#r271885310

This pull request seeks to update `package-lock.json` file per dependency changes in #14664.

Separately, we should explore why the `check-local-changes` npm script is not correctly identifying local changes in Travis.

### CODE REVIEW

**Comment by aduth** [comment]
> Separately, we should explore why the `check-local-changes` npm script is not correctly identifying local changes in Travis.

Ah, this is probably why:

https://github.com/WordPress/gutenberg/blob/b3961d06a3862fb04967b776f2f246dc1f642f0a/.travis.yml#L35

`npm ci` doesn't update `package-lock.json`

**Review by ellatrix — APPROVED** [review]
Thanks! Sorry about that. Would be good to make Travis return an error. :)

**Comment by aduth** [comment]
Yeah, I'm not really sure what's going on there, even after digging further into how Travis handles errors. Based on how some other projects explicitly incorporate `npm ci` for the very purpose of validating `package-lock.json` (https://github.com/google/clasp/pull/118), it seems like it should be fine as-is. I'm wondering if it has something to do with Lerna and our dependencies being defined as local file paths.

**Comment by ellatrix** [comment]
Hm, but that still wouldn't explain `memize`? Or do you mean something else?

**Comment by aduth** [comment]
> Hm, but that still wouldn't explain `memize`? Or do you mean something else?

It could, since `memize` is a transitive dependency (it's a dependency of `@wordpress/annotations`; annotations is a file-path dependency in the root `package.json`).

**Pull request merged**
