### PR TITLE
Global Styles: Add border radius controls to global styles sidebar

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## Description
Adds border radius controls to the global styles sidebar.

_Note: Border radius support is turned off by default._

## How has this been tested?
Manually.

#### Testing Instructions
1. Checkout this PR, open the Site Editor and Global Styles sidebar.
2. Confirm there are no border controls under the Global tab or the "By Block Type" tab and Group panel.
3. Opt in to border radius support via `global.settings.border.customRadius` in `experimental-default-theme.json`
  ```
			"border": {
				"customRadius": true
			}
  ```
4. Reload the editor, open the global styles sidebar again and confirm no border controls under global tab.
5. Switch to "By Block Type" tab, expand the Group panel and confirm border controls now show here.
6. Edit your theme.json file (or `experimental-default-theme.json` and copy into your active theme) adding a border radius style for `core/group` block context.
  ```
	"core/group": {
		"styles": {
			"border": {
				"radius": 20
			}
		}
	}
  ```
7. Reload the editor, navigate back to the Group panel and confirm the border controls now default to the value supplied in the previous step.

## Types of changes
New Feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This worked as advertised for me, except for setting the default radius of 20 for the group block - at what level in the .json file should this setting be added?

**Comment by aaronrobertshaw** [comment]
Thanks for testing this.

> This worked as advertised for me, except for setting the default radius of 20 for the group block - at what level in the .json file should this setting be added?

It should be added at the top level, i.e. the same as the `global` context. In the last couple of days the theme.json has been restructured on master. For this PR though it still has the old structure. Shouldn't impact the control though.

I've updated the testing instructions and created an [example gist](https://gist.github.com/aaronrobertshaw/81be5858a156ebb5345eea41901a17e7).

**Review by glendaviesnz — APPROVED** [review]
This all worked as expected for me

**Comment by aaronrobertshaw** [comment]
A wider set of border block support features have been added in https://github.com/WordPress/gutenberg/pull/30124. This includes a border panel for the Global Styles sidebar. Closing this in favour of that PR as it's absorbed these changes.

**Pull request closed without merging**
