### PR TITLE
Add Slot to render block settings in the inspector.

### PR DESCRIPTION
**Pull request by mtias**
image

### CODE REVIEW

**Comment by youknowriad** [comment]
With #714 It should be easier to extract the attributes, their types and any relative information about the attribute to show in the inspector.

**Comment by mtias** [comment]
Yes, I'm trying to think what would be the best way to declare whether something appears in the regular toolbar, on the inspector, or on both.

**Comment by youknowriad** [comment]
I think the "chaining API" might be a good solution.

```js
attributes: {
  align: metadata().isString().choices( [ 'left', 'right', 'center', 'none' ] ).description( 'Text alignment' )
  content: children().hideFromInspector()
}
```

We could automatically generate the form based on this

**Comment by mtias** [comment]
Perhaps, but maybe the opposite is better: `showOnInspector` and defaulting to hide? We also need to figure out the simplest way to provide controls for these (inputs, toggles, segmented controls, etc).

**Comment by jasmussen** [comment]
> Yes, I'm trying to think what would be the best way to declare whether something appears in the regular toolbar, on the inspector, or on both.

What if we always show a copy of the Quick Toolbar at the top of the inspector, like @folletto proposed, and then show advanced settings below that. There should be room. Would that make life simpler?

**Comment by aduth** [comment]
Would a chainable API provide much benefit over a function which returns either an element or an array of field descriptions? I worry whether it'd be flexible enough, and if it's truly any more developer-friendly.

**Comment by youknowriad** [comment]
Let's move the discussion about the API here https://github.com/WordPress/gutenberg/pull/714#issuecomment-300297316

**Comment by mtias** [comment]
Going to merge this as a placeholder for the functionality as we figure out how to present it.

**Pull request merged**
