### PR TITLE
Social Icons: update Patreon icon

### LINKED ISSUE #56925: Social Links Block: update Patreon Logo
## What problem does this address?
Patreon recently updated their logo. We may want to update the Patreon logo or add a new one in the Social Links block to match the new branding.

This issue is near identical to the recent Twitter/X logo update by @jeherve: https://github.com/WordPress/gutenberg/issues/53223

## What is your proposed solution?

The solution would likely be very similar to this merged PR, which addresses the recent issue for Twitter/X: https://github.com/WordPress/gutenberg/pull/54092/files

The above PR adds a new icon, rather than replacing the old one. For this issue, I would propose a similar solution, so users can decide which to use, since brand recognition for the new logo may not be widespread yet.

Patreon provides SVGs for download in their [Brand assets and guidelines](https://www.patreon.com/brand).

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #56925

## What?

Let's update the Patreon logo.

## Why?

Patreon's logo is changing: https://news.patreon.com/articles/patreon-reimagined
Our Social Icons logo should change too.

## How?

This uses the new logo provided in the branding guidelines here:
https://www.patreon.com/brand

## Testing Instructions

1. Go to Posts > Add New
2. Add a new Social Icons block
3. Add a new Patreon block.

### Testing Instructions for Keyboard

Similar as above

## Screenshots or screencast

**On the frontend**

Screenshot 2023-12-11 at 15 45 00

**In the editor**

Screenshot 2023-12-11 at 15 44 36
Screenshot 2023-12-11 at 15 44 32

### CODE REVIEW

**Comment by t-hamano** [comment]
Sorry for the delay in confirming this PR. In order to move this PR forward, could you do the following?

- Just to be safe, rebase on the latest trunk branch
- I noticed that this icon variation does not have a fixture file. We might want to generate a fixture file for this variation, like when you added the Gravatar icon in #56544.
- Is it possible to center the icons perfectly? I checked the SVG updated by this PR and it looks like it's positioned a little above.

When checking SVG data in Illustrator:

image

**Comment by jeherve** [comment]
👍 I've just done all that. Thanks for the feedback.

**Review by t-hamano — APPROVED** [review]
LGTM! The icon is perfectly centered and the fixture files look fine too.

I would like to merge this PR, but unfortunately it seems that one GitHub Action (React Native E2E Tests) always fails on the latest trunk. So you will probably need to merge the latest trunk into this PR one last time after that issue is resolved.

We will notify you as soon as the issue is resolved.

**Comment by t-hamano** [comment]
It seems that the issue with GitHub actions in trunk has been resolved. Could you merge the latest trunk one more time? I would like to merge this PR as soon as all GitHub Actions pass 🙇

**Comment by jeherve** [comment]
👍 Done

**Comment by t-hamano** [comment]
Thank you, merged 🚀

**Comment by evalarumbe** [comment]
Hooray, thanks all :D Where should I watch to see which version this is released in?

**Comment by t-hamano** [comment]
>Where should I watch to see which version this is released in?

This PR will be shipped as part of Gutenberg plugin version 17.7. This version will also be included in the upcoming WordPress 6.5.

**Pull request merged**
