### PR TITLE
Add: Selection and bulk actions to grid view.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This pull request introduces the ability to perform bulk actions and make selections using the grid view.

Currently, the only way to select items is by clicking them while holding down the command or ctrl key, or by using the bulk edit select all option. I plan to add support for other standard selection methods, such as using shift-click to select a range of items. Additionally, I will explore the possibility of adding a checkbox to the grid view. I am unsure if it should be visible by default or only appear when hovering over an item.

## Screenshots
Screenshot 2024-01-23 at 18 37 08
Screenshot 2024-01-23 at 18 36 39

### CODE REVIEW

**Comment by jameskoster** [comment]
@jorgefilipecosta I've pushed some style adjustments. 

I think we probably need to include a checkbox otherwise it's not possible to perform a partial selection using the keyboard. 

I don't have a strong opinion about whether it appears next to the title (first row in screenshot below), or overlays the preview on hover (second row). It's probably one of those details that needs to be felt out. If you can add the checkbox I'm happy to work on those options.

Screenshot 2024-01-24 at 14 14 10

**Comment by ntsekouras** [comment]
Just quickly tested this and if the are clickable fields(like the title and preview), the `click` event is propagated.

Regarding the designs for the checkbox, I'd go with the one before the `primaryField`, because while in our grid views right now we have `mediaField`, a grid view doesn't necessarily need one. This also needs some changes in code, because we render the media field wrapper even if it might not exist, and we apply styles to that wrapper.

**Comment by jorgefilipecosta** [comment]
Hi @ntsekouras, @jameskoster,

I updated the PR, it now includes a checkbox to select, and addressed the bug of clickable fields nested inside the grid item executing their action like navigating.

**Review by jameskoster — COMMENTED** [review]
Thanks @jorgefilipecosta.

I pushed some styles for selected items.

For me the checkbox appearance is a bit prominent and would benefit from a reduction in size, but that's a detail to look at separately. 

In terms of design the last piece missing is a click-to-select behavior on the card. I don't think we need that in this PR though so I'm happy to approve :)

**Review by jameskoster — APPROVED** [review]

**Pull request merged**
