### PR TITLE
Shared block form: add missing label.

### LINKED ISSUE #6199: Shared block: the Edit field is unlabelled
Any UI controls and form fields must have a properly associated label. Visible text labels are always preferable, alternatively a visually hidden `<label>` element or an `aria-bale` can be used.

Rationale:
- all users need to clearly understand what a form field is about
- screen reader users  need to know what the form field is about when they land on it
- speech recognition software need the label to be visible so they're able to voice a proper command "Click {field name}" to move to the field

When changing a block to a Shared block, an UI appears to give the new Shared block a name:

screen shot 2018-04-15 at 17 11 39

This field misses a label.

Strongly recommended: tests to check the presence of labels, see #6098

### PR DESCRIPTION
**Pull request by afercia**
This PR adds a missing `<label>` element to the Shared block form. It does it in the simpler way, just adding a visible `<label>` so there's also a minor visual change:

screen shot 2018-04-16 at 13 17 19

Rationale:
- all users need to clearly understand what a form field is about
- screen reader users need to know what the form field is about when they land on it
- speech recognition software need the label to be visible so they're able to voice a proper command "Click {field name}" to move to the field

Fixes #6199

### CODE REVIEW

**Review by karmatosed — DISMISSED** [review]
Visually I think having on 2 lines is an issue. Is it an issue to have this as the placeholder as we have in other areas? I am asking just incase that's an option. It it is not an option, can we consider other options here? What are our options?

**Comment by afercia** [comment]
@karmatosed I've explained why the labels must be preferably visible 🙂 that's of fundamental importance for speech recognition software users, and benefits all users. Have you checked the video by Eric Wright @ewaccess published on https://make.wordpress.org/accessibility/2018/03/28/accessibility-of-gutenberg-the-state-of-play/ ? That's very enlightening.

Also, you're probably already aware that placeholders shouldn't be used as replacement for labels. As accessibility team, we're trying to communicate this since a looong time. See the related Trac ticket https://core.trac.wordpress.org/ticket/40331

I'd greatly prefer to keep it visible and avoid hacks. When you have a chance, could you please argument a bit why this is a design issue in your opinion? I've given a few important a11y argumentations here but from a design perspective I've heard just `Visually I think having on 2 lines is an issue.` without further detailed explanation.

I'd also like to encourage everyone to make an effort to go beyond what are our personal perceived visual taste and gut impressions. That's very subjective, while a11y is not: there are rules to meet.

**Comment by youknowriad** [comment]
The a11y rule is to have a label, it can be hidden as a tradeoff. We can add an `aria-labelled-by` to a hidden label. which would solve both issues: having a label and meeting the a11y rules.

**Comment by afercia** [comment]
Sure, can be aligned on the left. Would you like to make it bold for consistency with the shortcode block label for example? See below. Also, I guess in the responsive view, label, field, and buttons should be stacked vertically?

Examples:

screen shot 2018-04-18 at 16 42 51

screen shot 2018-04-18 at 16 48 48

**Comment by afercia** [comment]
Moved label on the left (see screenshot above) and rebased to solve conflict.

**Comment by afercia** [comment]
Just noticed the switch to the responsive view needs to happen way before 782px:

screen shot 2018-04-19 at 14 37 43

**Comment by afercia** [comment]
Rebased to solve conflict.

I'd greatly appreciate a quick check, the label is now placed on the left as in the screenshot above. At the 960px media query it switches to a vertically stacked layout. @karmatosed

**Comment by afercia** [comment]
Final screenshots:

screen shot 2018-04-20 at 11 09 09

screen shot 2018-04-20 at 11 10 54

**Comment by afercia** [comment]
Thinking at translations that could have a longer label text and produce layout issues, what about to use a shorter label and change the default field value:

current:


screen shot 2018-04-20 at 11 28 22

proposed:

screen shot 2018-04-20 at 11 29 01

**Pull request merged**
