### PR TITLE
Archives block: use align supports flag + add wide/full align support

### LINKED ISSUE #11416: Archives block: add wide and full alignment support
## Description
The Latest Comments and Latest Posts blocks support the `wide` and `full` alignment options. The Categories block also supports the `full` alignment option (but not the `wide` option; see #11415). So why doesn't the Archives block support the `wide` and `full` alignment options?

## Related issues and PRs
- #10706 would fix this issue
- related issue for Latest Posts block: #8777
- related issue for Categories block: #11415

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
Closes #11416.

This PR updates the Archives block to use `supports: { align }` to add most of its alignment support, and it adds support for the `wide` and `full` alignments to the Archives block.

Notably, the `align` attribute is still defined in PHP since the `enum` property prevents invalid alignment classes from appearing on the front-end. (You can test this by using the Code Editor to modify an existing `align` attribute on the block to have an invalid value and then checking the markup of the resulting post.

## Types of changes
- Using `supports: { align }` to add block alignment support to the block.
- Added `enum` to the `align` attribute defined in `index.php` to fix an issue in `master` where you could set invalid values for the attribute, which would result in invalid classes (e.g. "alignbob") on the front-end.
- Some imports in `edit.js` were incorrectly listed as "Internal dependencies" (which they may have been prior to some stuff being moved into packages). This has been fixed, and the imports are now in alphabetical order.

## Related PRs
- #10707
- #10758
- #11411
- #13215

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Rebased PR and updated it based on feedback on #10758.

**Comment by gziolo** [comment]
@melchoyce or @jasmussen - is it expected to add align wide and full for the Archives block? In #9469 	@nfmohit-wpmudev proposed the opposite for Category block.

**Comment by gziolo** [comment]
Now, I see #9413 opened by @kjellr where it's suggested the opposite:

> Since these blocks are similar in function and appearance, we should sync up these alignment options. To do so, I suggest we remove the "Full" alignment from the Categories block — it doesn't seem like it'd be a frequently used setting for a list.

It looks like we should proceed with #9469 instead.

**Comment by ZebulanStanphill** [comment]
@gziolo But my previous PR, #13215, was already merged by @aduth, adding wide align support to the Categories block. That PR runs counter to #9413, since my PR actually _added_ an alignment to the Categories block. Perhaps some kind of official decision needs to be made on all this? It doesn't make sense to go halfway in one direction and then halfway in the other.

**Comment by kjellr** [comment]
@ZebulanStanphill 

> But my previous PR, #13215, was already merged by @aduth, adding wide align support to the Categories block.

Yes, my ticket there is now out of date. I just updated the description there to reflect that.

@gziolo 

> Now, I see #9413 opened by @kjellr where it's suggested the opposite:

My gut still says that text or list-based blocks like these shouldn't ship with wide/full alignments. They don't clearly benefit from the additional space: in fact, they become less readable with longer line length.

**Comment by melchoyce** [comment]
> My gut still says that text or list-based blocks like these shouldn't ship with wide/full alignments. They don't clearly benefit from the additional space: in fact, they become less readable with longer line length.

+1

**Comment by gziolo** [comment]
In that case, I'm closing this PR :(

Let's make sure we remove full and wide from other blocks where it doesn't make sense.

@ZebulanStanphill sorry about that. Thank you for your work, hopefully, it pays off with more consistent UI as an effect of your contribution. 🙇

**Pull request closed without merging**
