### PR TITLE
Implement multi-theme system

### LINKED ISSUE #26546: Full Site Editing: Templates and Template Parts Duplicates
_Note: I'll only mention "templates" for brevity, but this applies to both templates and template parts._

Templates used in Full Site Editing can have different origins (or, as I've called them in #26394, "sources").

- Themes can provide them as HTML files in the `block-templates` folder; likely plugins will be able to provide their owns as well. Whenever the template loader runs (for example, when opening the Site Editor), these files are converted into `wp_template` posts.
- Users can create their own templates in the Site Editor, or from Appearance -> Templates.
- Users can update templates provided by themes and plugins, practically making them their own.

The original WP template hierarchy relies on file names to determine which template is used for any given content.

FSE templates aim to recreate the same experience (if anything, for backward compatibility reasons), relying on slugs instead.

This means that it's extremely easy to end up with multiple `wp_template` posts with the same slug, which can each be used for their corresponding content.

For example, if I activate an FSE-ready theme containing the `index` template, and then I activate another FSE-ready theme with its own `index` template, my site will contain 2 different `index` templates, without a clear way to determine which one will be used.

In #26394 I've added a `theme` post meta to `wp_template`, which stores the theme that originally provided that template (`wp_template_part` already has the same post meta).
This is not enough to address potential conflicts, but it's at least a start.

## Automatically Choosing the Appropriate Template

At first we should probably figure out a way to automatize the template choice, on a per-slug basis.

- If there is only 1 template with the slug matching the current content, and it was either provided by the current theme, or it's customized by the user, the site will use that.

- If the only relevant template was provided by an inactive theme, should the site still use it, even if it might not match the current theme design?

- Given the choice, templates customized by the user will have the priority over "siblings".

- What about plugin-provided templates? Should they be prioritized over theme-provided ones?

- What happens if, for example, a site has a user-customized `index`, and afterwards the user activates a theme which includes its own `index`? Should we also favour the creation (in this case "conversion from file") date of the `wp_template` post?

## Manually Choosing the Appropriate Template

We don't really have a way to do this right now, but it might be useful, especially as an escape hatch when the automatic choice is not picking the expected template (note: "expected" != "correct").

We could approach this from the template side, or from the content side.

### Setting Default Templates

Similarly to how we handle the page order, we could add a new custom field to `wp_template`.

It could be a number field, working like the page order but on a per-slug basis (e.g. `index` templates will have their own order, separate from `singular` templates order), but it will probably become messy when new templates are created.

Another way could be to simply have a "Make template default for its corresponding content" checkbox.
Checking it on a template would automatically uncheck it on other templates with the same slug that had been previously set as default.
Should creating new templates (either manually or via file conversion) affect this value?

### Assigning Templates to Content

Similarly to how we handle custom templates for pages, we could create an interface that visually recreates the template hierarchy with the available templates, letting the user pick their preferred template when there's a possible choice.

Such interface could be also handy to let users "toggle" templates for a content.
E.g. the site has a `front-page` template, but the user would rather use `index` for the Front Page. Currently the only way would be to remove `front-page` from the site.
A toggle could switch the template between draft and published (for example), "opening and closing" the hierarchy fallback flows.

---

I'm sure there are other possibilities, but I think these might be the most likely to happen.

If some of these proposal seems too far out, it's because they are mostly supposed to be a way to kickstart a discussion about duplicate templates.

### LINKED ISSUE #26950: Simplify template part block attributes
**Is your feature request related to a problem? Please describe.**
Currently, the template part block supports four attributes: `postId`, `slug`, `tagName` and `theme`. In light of #26650 being merged, there is now no longer a need for the `postId` and `theme` attributes.

The purpose of the `theme` attribute was to preserve the rendering of user-edited templates that survived a theme switch. Now that all templates are retired from use upon theme switch, there is no longer a need for this attribute.

As for the `postId` attribute, I think its purpose was to locate template parts that the user created independently of the theme. This idea of theme-less templates/parts is no longer being supported for the time being.

**Describe the solution you'd like**
Simplify the supported attributes of the template part block to just `slug` and `tagName`, as these are now the only ones needed.

The block would then render the template part from the current theme with the specified slug, if it exists. It shouldn't need to look through an inactive theme.

Also related: #25845, #22717

### LINKED ISSUE #48145: Site Editor: template parts not loading on Horizon
After latest Gutenberg plugin updates the template parts are no longer loading on FSE Horizon test flow.

1. Go to https://horizon.wordpress.com/new?flags=gutenboarding/site-editor
2. Follow up steps to create a new site.
3. Notice the infinite spinners at the end when you get redirected to site editor. The header section is missing.

Screenshot 2020-12-08 at 23 57 51

### PR DESCRIPTION
**Pull request by carlomanf**
## Description

Closes #26950
Closes #26546
Closes Automattic/wp-calypso#48145

In recent months, there have been whispers around the future possibility of multiple themes being active, templates being "themeless," etc. This branch is an implementation of that.

The idea behind this implementation is there can only be one active theme at a time, but the `wp_theme` taxonomy can be used to link up individual templates / template parts with one or more themes at a time.

This branch does a few things:

* Removes the theme name from the REST API endpoint, solving duplicates and meaning that only one template / template part can be requested per slug. Templates / template parts not linked with the active theme are not accessible. (That's why it's called the "active" theme.)

* Removes the theme attribute from the template part block.

* When switching theme, users are given one chance to link any old templates / template parts to their new theme. (After the new theme is activated, anything they didn't link will become inaccessible until the old theme is re-activated.)

* If the user elects to link a template to the new theme, any of its template parts are automatically linked too.

Planned additions to this branch:

* Linked templates / template parts need to be stored in the database even if they previously were not. (This could be considered a down-side of the approach, since the user may not have made any changes.)

* If the user tries to re-activate a previously active theme, plus link a template / template part that would create a slug conflict, they are shown an error message and can't activate the theme until they de-select the one that is creating the conflict. (Don't know if this is the best solution.)

* When an inactive theme is deleted, its taxonomy term is deleted as well. Any templates / template parts that only belonged to that theme alone, are deleted.

Maybe will attempt:

* Link templates / template parts from inactive themes into the active theme, without switching.

* Unlink a template / template part from the current theme but leave it linked with its other themes.

Not planned for this branch to attempt, but maybe should still be handled:

* Handle stylesheets, global styles, etc.

* Warn the user when deleting a template / template part that is linked to multiple themes.

* Let the user clone a template / template part from their old theme, and link the clone to the new theme rather than the original. (This would give the user more control but might create a lot of slug conflicts.)

* Unit tests.

* Make the UI nicer.

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
> Removes the theme name from the REST API endpoint, solving duplicates and meaning that only one template / template part can be requested per slug.

> When switching theme, users are given one chance to link any old templates / template parts to their new theme. (After the new theme is activated, anything they didn't link will become inaccessible until the old theme is re-activated.)

Would the combination of this mean that if I linked the `header` template part over to the new theme I am switching to, that I would not be able to access the `header` that theme provides?  If so it seems a bit unfriendly as users may want to carry over template parts but still have the option to preview/use what is provided by the newly activated theme (as opposed to being forced to decide between the two at the time of theme switch).

**Comment by carlomanf** [comment]
> Would the combination of this mean that if I linked the `header` template part over to the new theme I am switching to, that I would not be able to access the `header` that theme provides? If so it seems a bit unfriendly as users may want to carry over template parts but still have the option to preview/use what is provided by the newly activated theme (as opposed to being forced to decide between the two at the time of theme switch).

@Addison-Stavlo Thanks for your interest. This scenario would be handled by the following point, which is not yet implemented at the time of writing:

> * If the user tries to re-activate a previously active theme, plus link a template / template part that would create a slug conflict, they are shown an error message and can't activate the theme until they de-select the one that is creating the conflict. (Don't know if this is the best solution.)

In your scenario, the theme switch would be impeded because the new theme already includes its own "header."

It's certainly conceivable that a user might want to use one "header" on their front-page for example, and another "header" on their other pages, but I'm not sure there is an easy solution to that.

The problem with reinstating the theme reference into the endpoint is it would make it extremely difficult to list out the "active" template-parts (in the site editor, for example) without listing out every template-part from every theme.

I'm open to suggestions if you have any.

**Comment by carlomanf** [comment]
> The problem with reinstating the theme reference into the endpoint is it would make it extremely difficult to list out the "active" template-parts (in the site editor, for example) without listing out every template-part from every theme.

Just want to be clear, this point applies to the master branch as well, and shouldn't be considered a limitation of this branch.

**Comment by aristath** [comment]
Is this something we still want to pursue? If yes, then this needs rebasing :+1:

**Comment by youknowriad** [comment]
IMO we need to make choices, I don't think we should implement this for FSE v1 to avoid extra complexity and potential new  issues/confusion but I think it's definitely something to pursue for later.

**Comment by carlomanf** [comment]
I agree that it's a "later" feature, and always have, but I submitted this branch more for the purpose of illustrating a point.

The trunk implementation of the template endpoint has the format `themename//templatename`. This branch requires it to be just `templatename`, because in a multi-theme environment, the client-side will not know which theme to fetch from and requires the endpoint to determine it.

If this feature is planned for later on, then a required change in the endpoint format should be setting off alarm bells right now. The endpoint is already available for use in its current format, and it could cause headaches for plugin developers if it needs to be changed later. In other words, I agree that now is not the time to ship this feature, but I do think that now is the time to discuss whether the template endpoint format is appropriate and forward compatible.

**Comment by carlomanf** [comment]
Closing, because I don't plan to add any more commits and I think the prototype has served its purpose.

**Pull request closed without merging**
