### PR TITLE
Polish tabs

### PR DESCRIPTION
**Pull request by jasmussen**
This is one attempt at reducing the visual weight of tabs, and is based on a design by @shaunandrews and @pablohoneyhoney:

image

This PR is an alternative to #23605, with better code. It does not require tabs to be fixed-width, and does not need to know how many tabs are present in total, but it does not horizontally slide the tab indicator. 

tab-indication

I believe that with a prettier spot color (see also #23558 ), and with additional reduction of borders in the sidebar overall, this might be a net win.

Right now the indicator is 3px tall, to follow the design. I wonder if we should try 2px?

### CODE REVIEW

**Comment by jasmussen** [comment]
@ItsJonQ I was wondering, can you think of a way to bring the horizontally sliding tabs from #23605 to this design, but in a way that is better/cleaner code?

**Comment by shaunandrews** [comment]
I'm not sure how I feel about the `:focus` style, with the single pixel border; Like, I get what you're trying to do, but it comes off as a rendering bug to me. I _think_ its because the active border animates from the top-down, and the whole thing just feels weird:

tabs

> the indicator is 3px tall, to follow the design. I wonder if we should try 2px?

Is it 3px? I think with the addition of the `:focus` state (which you see immediately when you interact with the tabs) makes it look more like 4.5px tall:

image

In either case, I think the border is too large and clunky.

**Comment by jasmussen** [comment]
Yep. I'm not feeling either of my two branches either. I'm going to try something else.

**Comment by ItsJonQ** [comment]
@jasmussen OoOoo. Moving tab bar animations. I dig it 👍 . It will require JS **MATH**. Should be doable though. Let me know if/when you'd like some help with that 🙏

**Comment by jasmussen** [comment]
> OoOoo. Moving tab bar animations. I dig it 👍 . It will require JS MATH. Should be doable though. Let me know if/when you'd like some help with that 🙏

Thank you. As noted above, I'm not quite feeling the specific design here, but I'll definitely get back to you if I find the perfect balance.

**Comment by jasmussen** [comment]
Closing this one to revisit with a different appraoch.

**Pull request closed without merging**
