### PR TITLE
AligmentMatrixControl: update center cell label to 'Center'

### PR DESCRIPTION
**Pull request by chad1008**
## What?
Updates the label of the center cell of an `AlignmentMatrixControl` from `Center Center` to just `Center`

## Why?
Internally, we refer to the center cell as `center center`. [When `center` is passed, it gets converted to `center center`](https://github.com/WordPress/gutenberg/blob/02562313b414ba202b0604b9e394ee4cf0dee1bd/packages/components/src/alignment-matrix-control/utils.tsx#L40), but that level of specificity isn't as relevant from an end-user's point of view.

For the label, `Center` is more concise, and better matches how a user would likely describe that cell.

## How?
Updating the strings for both `center` and `center center` alignments in the `AlignmentLabel` record.

## Testing Instructions

- Test the component in Storybook, confirm the center cell is now labelled as `Center`.
- Test the same in the editor on a block like Cover
- Confirm tests still pass

### Testing Instructions for Keyboard
In Storybook, focus on the canvas and press `Tab` once to focus on the control. This should display the current label in a tooltip. Use the arrow keys to change the currently selected cell, navigating away from and then back to `Center`.

### CODE REVIEW

**Review by ciampo — APPROVED** [review]
New year, same CHANGELOG ! Let's not forget to add an entry for this :)

Otherwise, it looks good to me 🚀  (Just pinging @jasmussen in case he has any objections to this change)

**Comment by chad1008** [comment]
> New year, same CHANGELOG ! Let's not forget to add an entry for this :)

Yep! I was... um... just checking to make sure YOU remembered to check that during a review. Um... yeah. Good job. 😆

**Comment by jasmussen** [comment]
Seems like a great change!

**Comment by chad1008** [comment]
Thanks @jasmussen!

**Pull request merged**
