### PR TITLE
Reset the page between every performance test

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

In trunk, some performance tests start from an empty post while others just use what was already loaded in the editor (previous test). This is problematic if you want to run metrics in isolation and also can result in a metric impacting others. For more consistency and stability, this PR updates the test to always start fresh between metrics.

I don't expect any meaningful impact on the results as I tried to kept the same content in the post editor for each metric compared to trunk but surprises are possible.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
The changes look good to me 👍

**Comment by dmsnell** [comment]
Any indication why perf tests started failing recently, if this is supposed to be the fix for them?

**Comment by dmsnell** [comment]
Looking at the changes they seem fine; it'd be nice to have more in the commit message indicating what exactly was wrong and what this solves? Which metrics were thrown off by this? What is the proposed impact?

I can get started measuring the impact on the Performance Tests runtime; guessing they'll be minimal.

**Comment by youknowriad** [comment]
> Any indication why perf tests started failing recently, if this is supposed to be the fix for them?

I saw these in a couple PRs, I don't know the cause of these yet.

The current PR is as the description suggests just a small change to always start fresh in the editor between each metric. In trunk, some metrics like "inserter open", "list view open" relied on what was present on the editor before the test runs which is defined by the previous test in the file.

**Comment by dmsnell** [comment]
> some metrics like "inserter open", "list view open" relied on what was present on the editor before the test runs which is defined by the previous test in the file.

this would have been gold in the commit message, which is why I asked 😉

**Pull request merged**
