### PR TITLE
Try/windows high contrast support

### LINKED ISSUE #4297: Support for Windows high contrast mode
Follow up to https://github.com/WordPress/gutenberg/issues/1562#issuecomment-313476750 and complementing a similar ticket open on the core Trac, see https://core.trac.wordpress.org/ticket/41286

Also mentioned in the (now closed) issue with initial accessibility recommendations, see #297 point 5:
> You will have to support Windows High Contrast Mode in your controls, including the SVGs for the buttons. Luckily, this may not be very hard for single-color SVGs as the fill can be defined via a media query.

Windows high contrast mode removes, among other things, any background and box-shadow. Here's an example on Windows 10 and IE 11 with some text selected:

screenshot 24

Overall, the interface is visible but the biggest issue is the focus style. All the ones based on box-shadow are not visible, including, for example, some important controls in the toolbar and all the sidebar panels.

For many other controls, the focus indication is actually given only by the text of the tooltip:

screenshot 25

As mentioned in the Trac ticket, and as a long term goal, it would be great to switch to a new focus style not exclusively built with box-shadow. Note: borders and outlines are visible in high contrast mode.

### PR DESCRIPTION
**Pull request by jasmussen**
Add support for Windows High Contrast Mode, by changing focus styles from using box-shadow to using borders and outlines. Fixes #4297. 

Visually there _shouldn't_ be any difference between this branch and master. But because borders take up space and change metrics, a lot of gymnastics had to be done so buttons kept their same footprint as before. As such, it is not unlikely I missed some buttons/styles in the process of doing this. As such, this PR needs a fair bit of testing. 

Things to look for include buttons or elements that are suddenly smaller than before, or indeed _bigger_ than before. 

Some screenshots:

screen shot 2018-02-02 at 13 43 12

screen shot 2018-02-02 at 13 43 17

screen shot 2018-02-02 at 13 43 27

screen shot 2018-02-02 at 13 43 31

screen shot 2018-02-02 at 13 43 39

### CODE REVIEW

**Comment by jasmussen** [comment]
Pushed another tweak to these, to make the focus style dotted in menu items:

menu focus

This starts to address parts of #4871.

**Comment by mtias** [comment]
I like the treatment within menus as it seems clearer it's not an active / off state.

**Comment by afercia** [comment]
@jasmussen thanks for trying this. I've just tested on Windows High Contrast mode with IE 11 and Edge, and unfortunately the transparent border is always visible, so everything appears "bordered" both in a normal and focused state with no apparent difference. See also the original comment by the Simply Accessible team on https://github.com/WordPress/gutenberg/issues/1562#issuecomment-313476750

screenshot 31

**Comment by jasmussen** [comment]
Okay, I believe I handled the issue by using paddings instead of transparent borders. Not quite as clean, but let's start by testing if this solves the issue.

**Review by karmatosed — APPROVED** [review]

**Comment by jasmussen** [comment]
@afercia any thoughts? I would appreciate if you could test this again for me, see if it addresses the issue. Thank you.

**Comment by afercia** [comment]
@jasmussen seems a good improvement 🙂 with some edge cases.

Initial state: borders are correctly not visible (there are no transparent borders now, right?):

screenshot 33

Focus on the top bar controls works nicely (the tooltip arrow is a bit weird though):

screenshot 34

On other Gutenberg UI controls, focus is sometimes barely visible. For example, the focused sidebar panel can be distinguished just because it gets a dotted border (I guess it's the default outline?):

screenshot 35

Instead, on other controls focus is still not visible, and that's the case of controls that inherit the focus stye from the core CSS, which uses only box-shadow. For example:
- Publish button: focus not visible
- Some "links" like visibility "Public" or the publish date: focus not visible

Last thing I've noticed: the "Move to trash" button "jumps" on focus.

**Comment by jasmussen** [comment]
Thank you all for the feedback, especially the screenshots, Andrea. 

I was on vacation last week, and before that I didn't merge this in because I never felt comfortable with the hacks I had to perform to get this to work. I had hoped I could offset some of the complexity with SCSS math and mixins, but it just remains too complex. So I've thought about alternate approaches during this week, and came up with [quite](https://codepen.io/joen/pen/WMxwwa) a [few](https://codepen.io/joen/pen/MQrNdX). In particular, this approach I think would work for us:

https://codepen.io/joen/pen/mXXbOR

The benefit to that approach is that it allows us to continue using box-shadow for the visual styling of the button. We then leverage the fact that even transparent outlines show up in high contrast mode, allowing us to not only create extra thick focus outlines for that use case, but it maps out an approach that lets us tailor the visual styles for high contrast modes without affecting the buttom markup, yet lets us address your subsequent points in a better way.

Here's stock focus:

normal focus

Here's high contrast focus:

high contrast

This seems like the best approach because it allows us extra thick and very visually distinct focus outlines, like the rest of the system has in this mode, all the while working in both Edge and Firefox.

As such I'm going to take a new stab at this one. Thanks again for the help.

**Comment by jasmussen** [comment]
Closing this in favor of #5138.

**Pull request closed without merging**
