### PR TITLE
Fix: typos inside /docs

### PR DESCRIPTION
**Pull request by parikshit-adhikari**
## What?
This PR fixes multiple typos inside the /docs directory.

## Why?
This PR is necessary as it contributes towards making the documentation free of typos.

### CODE REVIEW

**Review by ndiego — APPROVED** [review]
Fantastic PR! LGTM

**Comment by parikshit-adhikari** [comment]
thanks!

**Comment by fabiankaegy** [comment]
@parikshit-adhikari Thank you for your contribution :) 

One of the failing tests actually is related to the change here.

https://github.com/WordPress/gutenberg/actions/runs/6570083788/job/17860048576?pr=55472#step:7:33

In order to resolve this please pull down the repository locally and run `npm install` and then `npm run docs:build` and make sure to commit any changed files :)

**Comment by parikshit-adhikari** [comment]
Please check now @fabiankaegy

**Comment by ndiego** [comment]
Thanks for fixing that @parikshit-adhikari, looks good now. All checks have passed.

**Comment by jeffpaul** [comment]
@parikshit-adhikari note that we're compiling credits for the WordPress 6.5 release and would like to confirm your WordPress.org username so that you're properly included in the credits.  Mind responding / linking your GH.com and WP.org accounts as noted by the bot comment above?

**Pull request merged**
