### PR TITLE
[RNMobile] Upgrade Gradle to 7.4 & AGP to 7.1.1

### PR DESCRIPTION
**Pull request by ParaskP7**
Related PR: #39097 (outdated)

## Description

This PR upgrades all react-native Android libraries to `Gradle 7.4 & AGP 7.1.1`.

It includes the following:
- `Gradle` version upgraded to `7.3.3` with the `./gradlew wrapper --gradle-version=7.3.3 --distribution-type=all` command.
- `AGP` version upgrade to `7.0.4` (see `android/settings.gradle.kts` change).
- Build output diff:
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- Lint output diff
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- The above 4 steps were redone with a follow-up update to `Gradle 7.4` & `AGP 7.1.1`.
- The above `Gradle 7.4 & AGP 7.1.1` upgrade was done for the main 3 react-native libraries:
  - [x] `react-native-aztec`
  - [x] `react-native-bridge`
  - [x] `react-native-editor`

Related [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) PR: [Upgrade Gradle to 7.4 & AGP to 7.1.1 #4662](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4662)
Related [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) PR: [Upgrade Gradle to 7.4 & AGP to 7.1.1 #15865](https://github.com/wordpress-mobile/WordPress-Android/pull/15865) (for manual testing purposes)

## Testing Instructions

Manual testing of the react-native demo `Editor` and main `WPAndroid` app that include these changes.

## Screenshots 

N/A

## Types of changes

Android build file changes for react-native projects & react-native library updates for Android projects.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by fluiddot — COMMENTED** [review]
@ParaskP7 I tested these changes with the demo app and, as far as I tested, everything is working as expected 🎊. Let me know if you plan to introduce any further changes and whether the PR is ready to be reviewed, thanks 🙇 .

**UPDATE:** All PR checks including the ones from https://github.com/wordpress-mobile/gutenberg-mobile/pull/4662 are 🟢 🎊 .

**Comment by fluiddot** [comment]
@ParaskP7 as the last check, it would be great if you could update the Gutenberg Mobile reference [here](https://github.com/wordpress-mobile/WordPress-Android/blob/d34112952511bdc1a5f156527b43452618514fb6/build.gradle#L4) in https://github.com/wordpress-mobile/WordPress-Android/pull/15865, this way we could assure that WordPress-Android project is built without issues. We can reference a commit SHA of GB-mobile PR, in this case, you could use: [`4662-822b36f4ae74c0a68ac37a0db442f7253889cc6b`](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4662/commits/822b36f4ae74c0a68ac37a0db442f7253889cc6b).

**Comment by ParaskP7** [comment]
👋 @fluiddot !

Thank you for the review and testing! 🎉 ❤️ 🚀 

> @ParaskP7 I tested these changes with the demo app and, as far as I tested, everything is working as expected 🎊.

This is great! 🥇

> Let me know if you plan to introduce any further changes and whether the PR is ready to be reviewed, thanks 🙇 .

No, I don't plan to introduce any further changes, this PR is ready to be reviewed, I just flipped the PR to `Ready for review`! 💯 

> UPDATE: All PR checks including the ones from https://github.com/wordpress-mobile/gutenberg-mobile/pull/4662 are 🟢 🎊 .

Awesome! 🥇 

> @ParaskP7 as the last check, it would be great if you could update the Gutenberg Mobile reference [here](https://github.com/wordpress-mobile/WordPress-Android/blob/d34112952511bdc1a5f156527b43452618514fb6/build.gradle#L4) in https://github.com/wordpress-mobile/WordPress-Android/pull/15865, this way we could assure that WordPress-Android project is built without issues.

Let me do that and then test it. I'll let you know when that is done! 👍 

> We can reference a commit SHA of GB-mobile PR, in this case, you could use: [4662-822b36f4ae74c0a68ac37a0db442f7253889cc6b](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4662/commits/822b36f4ae74c0a68ac37a0db442f7253889cc6b).

Great, got it, will do! 👍

**Review by fluiddot — APPROVED** [review]
LGTM! Awesome work @ParaskP7 🎊.

**UPDATE:** Before merging the PR, it would be great to check with https://github.com/wordpress-mobile/WordPress-Android/pull/15865 PR that these changes work as expected in WordPress-Android.

**Comment by ParaskP7** [comment]
> LGTM! Awesome work @ParaskP7 🎊.

Awesome, back to you @fluiddot ! 🥇 

> UPDATE: Before merging the PR, it would be great to check with https://github.com/wordpress-mobile/WordPress-Android/pull/15865 PR that these changes work as expected in WordPress-Android.

As per your recommendation, I just update `Gutenberg` on the corresponding [WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15865).

Then, I tested that WPAndroid can be build and that everything works as expected. I tried to create a [new Post](https://petrosatwork.blog/2022/03/18/test-gutenberg-gradle-agp-update-%f0%9f%8d%80/), add a couple of blocks and then publish it. I am not sure if this basic smoke testing of mine if all that is needed, so do feel free to let me know what else I should be testing or pull the [latest changes on this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15865/commits/46cb24f02228ec7ed5d87ec17cd49ea4d441b64a) and try to test it yourself as well.

THANK YOU!!! 🎉 ❤️ 🚀

**Comment by fluiddot** [comment]
> Then, I tested that WPAndroid can be build and that everything works as expected. I tried to create a [new Post](https://petrosatwork.blog/2022/03/18/test-gutenberg-gradle-agp-update-%f0%9f%8d%80/), add a couple of blocks and then publish it. I am not sure if this basic smoke testing of mine if all that is needed, so do feel free to let me know what else I should be testing or pull the [latest changes on this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15865/commits/46cb24f02228ec7ed5d87ec17cd49ea4d441b64a) and try to test it yourself as well.

Awesome, I think the tests you performed are enough for smoke testing. AFAIK the parts that could have been affected due to these changes are the build process and maybe the editor initialization. If you already covered that, I think we're safe to merge the PR.

However, I'd like to note that since we've just cut the GB-mobile version `1.72.0`, we have to hold any change that we might want to include into the main apps (i.e. `WordPress-Android` and `WordPress-iOS`) until the release `19.5` of the main apps is done next Monday. This is a limitation we have in GB-mobile due to the release process, but as an alternative, if we need to merge native changes, we could merge them into the temporal `gutenberg/after_1.72.0` on the main apps, which will be merged back to trunk after the release `19.5` is completed. In. case of [your PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15865), probably it would make more sense to wait for next Monday/Tuesday to prevent potential conflicts, would it be possible?

**Pull request merged**
