### PR TITLE
Block Editor: Change default URLInput autoFocus to `false`

### LINKED ISSUE #22440: Block Editor: URLInput: Remove autoFocus as a default prop of URLInput
Previously: https://github.com/WordPress/gutenberg/issues/18061#issuecomment-580480464

Currently, `URLInput` assigns auto-focus to its rendered input. Auto-focus is largely discouraged ([we even enforce a rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md)) and it should not be the default behavior for such a basic component, as it limits (complicates) reusability and makes unnecessary assumptions about its rendering context. It's assumed that this was the default largely based on the assumption that the input is typically rendered within a Popover, which is not something we should be assuming.

**Task:** Avoid assigning `autoFocus` in `URLInput`. It should still be supported as an optional (opt-in) prop in cases where it is appropriate. This usage and associated cautions should be sufficiently documented.

### PR DESCRIPTION
**Pull request by aduth**
Related #18061
Closes #22440
~Blocked by: #19462~

This pull request seeks to change the default behavior of `URLInput` to avoid assigning auto-focus to its rendered input. Auto-focus is largely discouraged ([we even enforce a rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-autofocus.md)) and it should not be the default behavior for such a basic component, as it limits (complicates) reusability and makes unnecessary assumptions about its rendering context. It's assumed that this was the default largely based on the assumption that the input is typically rendered within a Popover, which is not something we should be assuming.

**Note:** Technically this can be considered a breaking change. That being said, if the component is used within a Popover (as was often assumed), the behavior should be unimpacted, since the default behavior of `Popover`'s `focusOnMount` prop is to focus the first focusable element, which would be the URLInput if one is present. 

~**Status:** This pull request is considered to be blocked by #19462, mostly because the interactions involved with Cmd+K are such that Popover's default `focusOnMount` isn't strictly enough to work with the specific rendering behavior of the current inline link dialog.~

**Testing Instructions:**

Verify that URL inputs are auto-focused as you would expect them to be in popovers:

1. Navigate to Posts > Add New
2. Insert a paragraph block
3. Add some text
4. (Optional) Highlight some text
5. Click "Add Link" in the block toolbar
6. Note that link popover is shown and the input is focused

**Follow-up tasks:**

Should `URLInputButton` be deprecated? Or at least undocumented. I don't believe that it's used in any core blocks, and I question whether we should want to encourage it as a pattern.

### CODE REVIEW

**Comment by aduth** [comment]
Rebased to resolve conflicts. Removed "In Progress" label. This is awaiting review.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by aduth** [comment]
There are (probably legitimate) test errors now. I'll take a look on Monday.

**Comment by aduth** [comment]
I gave a quick manual test to this branch. I see that the issue which is likely causing the test failures is related to the fact that when clicking "Edit" when previewing a link, the input field isn't automatically focused.

It's been some time since I originally put the changes together here, but based on the [changes applied to URLInputButton](https://github.com/WordPress/gutenberg/pull/19973/files#diff-29752fd99b1a5b7eede854429787e8f1) in toggling a button to trigger focus to shift into the input, I expect the same treatment could/should be applied to the LinkControl toggle as well.

**Comment by aduth** [comment]
> I gave a quick manual test to this branch. I see that the issue which is likely causing the test failures is related to the fact that when clicking "Edit" when previewing a link, the input field isn't automatically focused.

This should hopefully be fixed now as of the changes in 9045b67 . This was able to lean on some of the component's own prior art, where focus is retained when _completing_ the selection of a link. The revised implementation essentially applies this behavior for any toggle, either the start or completion of an edit state.

Note that this required a few extra considerations:

1. Retaining focus in response to clicking the "Edit" button to [this very commonly-encountered browser inconsistency of button clicks and focus](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus). This was worked around by creating separate handling specific to changes in state from button clicks, where it is assumed that it should be treated as effectively the same as if focus was within the element.
   - Related: There was some recent discussion at https://github.com/WordPress/gutenberg/pull/21031#discussion_r395544409 about baking this in to the implementation of the `Button` component, which would likely make this implementation unnecessary.
2. `@wordpress/dom` focusable utilities do not work correctly in our JSDOM unit test environment, because they rely on layout dimensions of an element to determine if an element is a focus candidate. These dimensions are not implemented by JSDOM, and it's quite likely they never will be. This has come up on a few occasions in the past. Ideally we solve this globally with some global mock or revised implementation of the utilities. In the meantime, I've resolved this by overriding the Element prototype within the test to simulate as if the element would have some non-zero dimensions.

**Comment by aduth** [comment]
I added the "Needs Dev Note" label since this is technically a breaking change for existing usage of the `URLInput` component. The included CHANGELOG.md entry could serve well as the note text:

>The default `URLInput` `autoFocus` prop value has changed from `true` to `false`. If you relied on the auto-focus behavior of the input, you must explicitly assign an `autoFocus={ true }` prop. Note that (in accordance with the purpose of this change) it is usually inadvisable to auto-focus an input. Refer to the [component README](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/url-input/README.md) for more information.

**Comment by aduth** [comment]
The stubs appear to be taking effect in other tests unintentionally. I'll have to take another look. It might just need to be complemented by an `afterAll` tear-down, but given how the setup is mutating the prototype directly, not sure how feasible this is without other changes.

Or it might just be worth looking at something on the `@wordpress/dom` side of things. I had _some_ luck getting a global mock earlier, but it wasn't working completely. Might be easier / better to try to sort out those remaining issues instead.

**Comment by youknowriad** [comment]
This has been implemented in a separate PR.  Thanks Andrew

**Pull request closed without merging**
