### PR TITLE
Stan: run some micro-benchmarks for state reading

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR branch contains a micro-benchmark script (called "stan-chmark") for Stan state reading.

The benchmark creates a map of items with 100k entries, and runs two kinds of selectors on it:
- Redux-style selectors that does a simple `state[ id ][ property ]` lookup. Nothing can be faster than this 🙂 
- Stan-style atom selectors that create an intermediate atom state structure during the read operation

Some results I got running the benchmark:
- reading all the 100k entries with a Redux-style selector takes approx 1ms. That's the ideal that's hard to beat and we can only aspire to get close.
- reading all the 100k entries with a Stan selector takes 1700ms. That's almost 2000x slowdown.

Then I tried to replace the `EquivalentKeyMap` with a simpler nested `Map` tree. That makes the benchmark run in just 980ms, almost doubling the speed.

Another little optimization -- not creating subscriptions to parent atoms in the selector-created derived atoms -- speeds up the benchmark to 770ms.

The last experiment was to reduce the Stan library to the absolute bare bones version that's needed to perform the `get` operations. The same data structure with atom states and selector lookup maps is still created, but there is no code for tracking dependencies, managing subscriptions or making updates. The atoms have just the `get` methods and resolvers, nothing else.

This shows the limits of the Stan approach: if we want to represent all values as atoms and maintain the atom and selector registry with states, then without changing the basic data structures, we can get a 6.3x speedup from the current state, but not more.

**How to use the benchmark:**
1. Build the Gutenberg packages with `node ./bin/packages/build.js`. The regular `npm run build:packages` task won't work, because Stan types are not correct.
2. `cd packages/stan` and run `node stan-chmark.js`

The branch has two commits, one with the benchmark script and one with the bare-bonized version I used. You can checkout only the first commit, make your own changes and run the benchmark on them.
With this version, the benchmark runs in 270ms. I wasn't able to make it any faster, even with the help of Chrome profiler.

### CODE REVIEW

**Comment by youknowriad** [comment]
This is cool :) Thanks for doing it

What's not counted here is that in stan's approach. A selector that is already resolved, returns its value directly (which is arguably faster than redux selectors) and also we only run the selector when they actually change in useSelect calls. There's still a lot of cases where we run these outside of useSelect calls (especially with the `@wordpress/blocks` package) which what makes any conclusion on the best approach harder :).

> This shows the limits of the Stan approach: if we want to represent all values as atoms and maintain the atom and selector registry with states, then without changing the basic data structures, we can get a 6.3x speedup from the current state, but not more.

At least what this shows for me, is that we may not really need to have every "selector" written as "atom selectors". It seems working with atoms is different in a lot of ways from Redux:

 - We tend to write selectors for everything in Redux.
 - With atoms, we can probably stop at the "item" level, (for instance no need to have getBlockName, or getBlockAttribute.;. getBlock should be enough) + add functions that return things from selectors like redux selectors do.

This also makes it harder to make refactorings for existing things.

**Comment by youknowriad** [comment]
Maybe at the data module binding level, we can support both cases: atom selectors and just regular function that may use atom selectors. The problem is how to discover the dependencies for the `useSelect` call.

**Comment by adamziel** [comment]
> This shows the limits of the Stan approach: if we want to represent all values as atoms and maintain the atom and selector registry with states, then without changing the basic data structures, we can get a 6.3x speedup from the current state, but not more.

Hypothetically, each store could be split into many atoms. For example, entity records of each kind/type could be represented by a different atom. That's not an MVP idea for sure, but something we could try down the road to reduce the number of calls even further.

**Comment by jsnajdr** [comment]
> What's not counted here is that in stan's approach. A selector that is already resolved, returns its value directly (which is arguably faster than redux selectors)

I have some numbers for that, too 🙂 

First, let's repeat the Redux read benchmark, i.e., 100k reads of different entries from map with a simple object property access, 10 times:
```
redux-0: 1.892ms
redux-1: 1.219ms
redux-2: 0.885ms
redux-3: 0.192ms
redux-4: 0.161ms
redux-5: 0.190ms
redux-6: 0.208ms
redux-7: 0.147ms
redux-8: 0.143ms
redux-9: 0.200ms
```
Even though it's always the same code reading from the same data structure, it gets 10 times faster after the 3rd run. Possible reasons I can think of:
- the code gets JITted only after the 3rd run and a less optimized version is running before
- the data gets cached in some fast L2 CPU cache
- the object is switched from a less efficient implementation (fixed-offset fields) to a more efficient one (hash map) after several runs

Original `stan` (with `equivalent-key-maps` and without optimization) spends a lot of time in the 1st run by building the data structures, and then gets 10x faster in all subsequent runs. Still 1000x slower than Redux though.
```
stan-0: 1767.101ms
stan-1: 196.478ms
stan-2: 178.233ms
stan-3: 168.542ms
stan-4: 166.729ms
stan-5: 158.000ms
stan-6: 169.520ms
stan-7: 168.642ms
stan-8: 158.058ms
stan-9: 169.207ms
```

Optimized `stan` (with nested `Map` and code cut down to mere getters) is 6x faster on all runs, including the first one:
```
stan-0: 256.404ms
stan-1: 43.677ms
stan-2: 39.509ms
stan-3: 27.351ms
stan-4: 28.317ms
stan-5: 28.104ms
stan-6: 26.697ms
stan-7: 26.001ms
stan-8: 26.229ms
stan-9: 25.033ms
```

I also tried to run Redux-style selectors not on an object with shape
```
{
  '0': { title: '00000' },
  '1': { title: '00001' },
}
```
but on two nested `Maps`. The result is that the first run is 2x slower than selecting from object, but subsequent runs are 10x slower:
```
redux-map-0: 5.660ms
redux-map-1: 4.331ms
redux-map-2: 3.155ms
redux-map-3: 2.102ms
redux-map-4: 1.999ms
redux-map-5: 2.027ms
redux-map-6: 2.017ms
redux-map-7: 2.007ms
redux-map-8: 2.008ms
redux-map-9: 1.984ms
```
I think that shows that representing an object with one property (title) as `Map` is inefficient. If the engine represents it as a hidden class instance and accesses properties by a fixed address offset, the lookup gets much faster.

**Comment by jsnajdr** [comment]
> A selector that is already resolved, returns its value directly (which is arguably faster than redux selectors)

This is true only for derived atoms, but not for selectors. To read from a selector, you need to first create the intermediate object `{ type: 'selector', config, args }`, then look up the value atom by `args` in a nested map, and only then you can read the already resolved value from the (derived) value atom for that particular selector and `args` combination. That's still way slower than a Redux selector even in best case.

**Comment by jsnajdr** [comment]
> With atoms, we can probably stop at the "item" level, (for instance no need to have getBlockName, or getBlockAttribute.;. getBlock should be enough) + add functions that return things from selectors like redux selectors do.

That looks good. The only downside is that the developer needs to be aware of two kinds of selectors. One kind of selectors work with atoms, the second kind is nothing but a regular function that calculates output from input.

One way to address this confusion is to not call atom selectors as selectors, but, e.g., "parametrized atoms". They are close relatives of "derived atoms".

**Comment by jsnajdr** [comment]
> Hypothetically, each store could be split into many atoms. For example, entity records of each kind/type could be represented by a different atom.

@adamziel This is what's already happening with atom selectors. Internally, there is a separate atom for each value that can be ever returned from the selector. The selector maintains a map from `args` to value atoms.

**Comment by adamziel** [comment]
@jsnajdr It makes sense that a bare-bones lookup is going to be faster than pretty much any more complex alternative. I wonder how these times would compare with subscriptions, or perhaps even `useSelect` in the mix.

**Comment by youknowriad** [comment]
I've abandoned Stan/Atom approach some time ago. This benchmark helped show the issues. I think the PR is not relevant anymore. Let me know if I'm missing anything.

**Comment by adamziel** [comment]
@youknowriad this measures reading the values, but is that where the most time is spent in Gutenberg? I remember reading-running useSelect to do dirty checking took a significant portion of the runtime. I'm still curious about a more real-world scenario that would compare typing speed with these targeted update chains instead of re-running all the useSelect callbacks on each keystroke

**Comment by youknowriad** [comment]
reading values is where the most time is spent on long posts if we remove "AsyncModeProvider". But given its existence and all the improvements we've made over time to reduce the subscriptions... It's not the bottleneck anymore I'd say.

Real word scenarios are tracked in codevitals.run (typing, loading, opening inserter...) but where this PR was helpful is that we were not able to actually test (Stan) the real world scenarios without huge refactoring of all the block-editor store, so we had to kind of simulate.

**Pull request closed without merging**
