### PR TITLE
BlockGap: Add axial gap option to global styles where available

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Add the ability to adjust axial (vertical and horizontal) block spacing / gap in global styles for those blocks that opt into it. For blocks that do not, default to a simple `UnitControl` for adjusting a single gap value.

## Why?

Some blocks already allow control over separate horizontal and vertical gap (notably Social Icons), so let's make it possible to control that in global styles where available.

## How?

Conditionally render a `BoxControl` component for adjusting axial gap if the block allows it. Otherwise, default to a simple `UnitControl`.

Note: this PR currently uses the `BoxControl` component, but I imagine we'll likely eventually swap it out for the presets-based spacing controls proposed in https://github.com/WordPress/gutenberg/pull/42173.

## Testing Instructions

* In the site editor, add a Social Icons block and enough individual Social Icons to form multiple rows of icons
* At the block level in global styles, adjust the block spacing for the Social Icons block, and check that the spacing is updated correctly in the site editor and once saved, on the front end of the site.
* Test adjusting block spacing for a block that does not opt in to axial gap, e.g. Buttons or Columns, and that the single `UnitControl` still works for adjusting spacing.
* Check that updating root spacing still works correctly (e.g. what was introduced in: https://github.com/WordPress/gutenberg/pull/42797)

### CODE REVIEW

**Comment by scruffian** [comment]
I think this would be great to add.

**Comment by andrewserong** [comment]
> I think this would be great to add.

Thanks for the reminder @scruffian! I was tweaking a couple of bugs over the past couple of weeks and this WIP slipped off my to do list. I'll give it a rebase this week and let's see if we can get it in.

**Comment by andrewserong** [comment]
I've given this a rebase, and I believe it's ready for review now 🙂

**Review by glendaviesnz — APPROVED** [review]
This tested well for me. I was able to:

✅ Adjust row and column gap for Social icons block in global styles, both individually and using the single control
✅ Still use non-axial block control for likes of Column block

**Comment by andrewserong** [comment]
Thanks @glendaviesnz! I'll merge this in, but 🤞 we can swap over to using the new spacing controls you've merged before too long.

**Pull request merged**
