### PR TITLE
Add @wordpress/navigation package

### PR DESCRIPTION
**Pull request by scruffian**
## What?
This adds a new navigation package, so that we can share code between the block library and the site editor.

## Why?
To be able to achieve things like https://github.com/WordPress/gutenberg/issues/51805, without duplicating loads of code.

## How?
For now this just moves a few useful things to the package, but going forward we should migrate more things there as they become shared.

## Testing Instructions
1. Add a navigation block to a post
2. Check that you can still switch navigations using the navigation selector in the inspector controls.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I think the CHANGELOG.md file didn't get commited

**Comment by scruffian** [comment]
> I think the CHANGELOG.md file didn't get commited

I didn't make one yet!

**Comment by getdave** [comment]
In many ways I like this idea of DRYing up the Navigation code. This becomes more pressing as we now have `Navigation` outside of the Nav block itself.

My concern is that whatever we export here becomes a public API whereas as things stand a lot of this is kept private within packages. This makes things _a lot_ less flexible so I would be hesitant given that

- Navigation requirements evolve quickly
- Everything in the package would be public by default and thus require backwards compat.

@youknowriad and I discussed this a while back when I first proposed a similar package a couple of years ago.

However I appreciate the landscape has changed and we now have the private API tooling to lean on.

**Comment by scruffian** [comment]
> My concern is that whatever we export here becomes a public API 

I think we can avoid this by using the private API tools

**Comment by youknowriad** [comment]
Thanks for opening the PR. I think creating packages to share internal utilities is not necessary a good thing, so my question would be, what is the actual purpose of this package? if I'm a third-party developer, what can I use this package for? Also what are the dependencies of this package? Is this a generic package any npm consumer can use? Is it a WP specific package? If it's a WP specific or internal package to reuse code, is there another place where we can put this code without creating a package.

**Comment by scruffian** [comment]
The purpose of the package is code reuse. We need the same code in both the edit-site and block-library packages. Are there other places we could put the code to share it between those packages?

**Comment by getdave** [comment]
I will also refer folks to [this previous PR](https://github.com/WordPress/gutenberg/pull/31586) where I suggested doing pretty much the same thing to share logic between the `edit/navigation` and `block-library` packages.

@youknowriad It might be useful to have some mechanism by which we can share code without it becoming a public package. Like "internal packages"?

I'd be the first one to say "let's avoid hasty abstractions" which is why I'm nervous about creating a public package full of abstractions that are useful now but may become superfluous in the future.

The counter argument is that Navigation has now become a defacto part of the Editor UI by way of it existing

1. As a block
2. As part of Site View

...therefore a package dedicated to this concept seems logical. This is similar to the way we have packages for Media, for example. Some ideas of things that we might want to expose might be:

- a way to get a fallback navigation via the new (currently private) API we introduced in 6.3
- a means to convert a classic navigation to a block navigation
- standard queries for navigation

**Update:** it's useful to note the APIs that have stayed consistent since I proposed @wordpress/menus and consider making them the first public APIs in this newly proposed package.

**Comment by MaggieCabrera** [comment]
> The purpose of the package is code reuse. We need the same code in both the edit-site and block-library packages. Are there other places we could put the code to share it between those packages?

Could we do what we are doing with the icons and interface packages [here](https://github.com/WordPress/gutenberg/blob/d27c43fda419995a80b1cbdeafe2b24d9a0e2164/tools/webpack/packages.js#L24), @youknowriad ?

**Comment by scruffian** [comment]
Another idea:

Can we start with a private API in block-library to be consumed by site editor? (It's also not ideal because block-library is supposed to almost be autonomous, just registers blocks, but it's still a private API, so maybe fine to start like that

**Pull request closed without merging**
