### PR TITLE
Persist focus when tabbing back to the block toolbar

### LINKED ISSUE #24469: Improve the toolbars roving tabindex
**Describe the bug**

One of the most remarkable accessibility features in the block editor shipped with WordPress 5.5 is the ARIA toolbar pattern, accompanied with the "roving tabindex" implementation. See https://github.com/WordPress/gutenberg/issues/3383 and the various related PRs https://github.com/WordPress/gutenberg/pulls?q=is%3Apr+roving+tabindex+is%3Aclosed

I'd like to propose to further improve the "roving tabindex" behavior to make it persist after a toolbar disappears and then reappears. Typically this applies to the block toolbars, which appear and disappear based on various conditions. It may apply to other implementations as well where the behavior should be considered on a case by case basis.

**What happens now:**
The "roving tabindex" does not persist after a block toolbar disappears and then reappears (potentially happens on other implementations as well). 

**Why it matters**
I'd tend to think there are two different cases of "disappearing / reappearing" behavior of the block toolbars:
1. the "disappearing" is triggered by an explicit user action meant to stop editing: for example the user press Escape to switch to "navigation mode"
2. the "disappearing" is triggered by a behavior of the block itself, not a user action meant to dismiss the toolbar, for example: the user starts typing into the block content

I'd tend to think that at least in the second case the "roving tabindex" should persist.

**To reproduce**

To reproduce a typical scenario:
- edit a paragraph block
- using the keyboard, move the caret at some point in the middle of the content or make a selection
- press Shift + Tab to jump back to the block toolbar
- press the Right arrow key a few times to focus the "Bold" button
- press Tab to jump to the content
- type something: as soon as you type, the toolbar disappears
- press Shift + Tab: the toolbar reappears
- however, focus is on the block switcher button: the roving tabindex didn't persist
- as a user, I'd expect focus to be on the "Bold" button, that is: where it was when I left the toolbar

Animated GIF to clarify the current behavior:

roving tabindex does not persist

Worth noting in the ARIA authoring practices the roving tabindex example on the toolbar at https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html assumes the toolbar is always visible. I don't think there's a specific recommended behavior for the case when a toolbar disappears and then reappears.

However, to me it make sense to make the roving tabindex work also in these scenarios where the user didn't explicitly dismissed the toolbar, as it seems the most expected behavior.

/Cc @diegohaz

### PR DESCRIPTION
**Pull request by diegohaz**
Fixes #24469

This PR adds a new experimental feature to the block toolbar so it "remembers" the last focused toolbar item when the user <kbd>Tab</kbd>s back to the toolbar after it is unmounted.

Tabbing in and out the block toolbar with focus persistence

## How to test

1. Create any block
2. Press <kbd>Shift+Tab</kbd> to move focus to the block toolbar
3. Press arrow keys to move focus to a different toolbar button
4. Press <kbd>Tab</kbd> to move focus to the block contents
5. Do some action so as to hide the toolbar (eg. typing on the Paragraph block)
6. Press <kbd>Shift+Tab</kbd> to move focus back to the block toolbar
7. Check if the focus is persisted

Also, see the added e2e test.

## What's not covered by this PR

- The alternative discussed in https://github.com/WordPress/gutenberg/issues/24469#issuecomment-700931142 to make the toolbar only visually hidden isn't implemented in this PR. This would require a lot of changes as the app as a whole seems to rely on this mounting behavior.
- <kbd>Alt+F10</kbd> behavior is unchanged.

### CODE REVIEW

**Comment by gziolo** [comment]
I found one edge case when testing:

toolbar-focus

The issue is that the index is persisted even when you move to another block. It wouldn't be a bad idea if those blocks would have the same set of toolbar items, but they differ a lot.

Would it be feasible to use at least the block type name to ensure that it doesn't produce unexpected behaviors? Well, it might be even necessary to use the block client id as a way to determine if the persisted initial index should be used.

**Comment by diegohaz** [comment]
Thanks, @gziolo! I confirmed the issue and it should be fixed now (hopefully, if e2e tests pass).

I think we have some options to persist the active toolbar item index:

- Persist only for the currently active block and reset when `clientId` changes (current solution).
- Persist per `clientId` (using a map) and don't reset.
- Persist only while navigating through blocks of the same type. The problem here is that same-type blocks may also have different toolbars, which I guess would make this much more complicated.
- Persist per block type (using a map) and don't reset. The same problem above.

For now, I think the first one is the simplest option, but we can explore the others if it's not enough.

**Comment by gziolo** [comment]
I see some failing e2e tests on node 1 but they exists in `master` branch as well.

I'm fine with the simplest solution proposed. In fact, it might be the most expected behavior if you think about it from the user's perspective. When you edit a block then you are in the "Edit mode", so going back and forth between the toolbar and content is simplified when the last position is persisted. As soon as you move focus to another block you start fresh and might be easier to navigate starting from the beginning of the toolbar, especially if the number and type of items differ between blocks. Again, when you move back to the block you edited previously, you probably won't remember what was your action, so having the focus on the start of the block is the most reasonable in my opinion.

**Review by gziolo — APPROVED** [review]
It works as advertised with the last changes applied. Nice work on this improvement 👍

**Pull request merged**
