### PR TITLE
Cover Block: Fix block deprecation when fixed background is enabled

### LINKED ISSUE #51473: Cover Blocks with legacy markup lose their content after block recovery if hasParallax was true
### Description

The Cover Block used to use an inline style attribute on the main div for the background image but now uses a nested img tag for regular backgrounds or nested div tag for fixed backgrounds. The new markup means any content saved by a previous version of WordPress will fail block validation when the editor loads. "Attempt Block Recovery" should fix the block but if hasParallex was true in the legacy markup the recovery process removes all the previously nested content / blocks.

### Step-by-step reproduction instructions

1. Paste the legacy Cover Block markup (below) into a Page
2. Save the Page and Reload
3. You'll see a broken block with "Attempt Block Recovery"
4. Click "Attempt Block Recovery"
5. Cover Block is fixed but the nested "My Cover Block Text" content is now missing

### Workaround
Removing the `"hasParallax":true` block attribute from the  comment fixes the issue. The block will still fail validation but recovering the block will work and any nested content will be retained.

### Legacy Cover Block markup for testing
```html
<!-- wp:cover {"url":"https://placehold.co/1200x800","hasParallax":true,"dimRatio":90} -->
<div class="wp-block-cover has-parallax" style="background-image:url(https://placehold.co/1200x800)"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-90 has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size">My Cover Block Text</p>
<!-- /wp:paragraph --></div></div>
```

### Environment info

- WordPress 6.2.2
- Safari Version 16.5 (18615.2.9.11.4)
- MacOS Venture 13.4 (22F66)
- All plugins disabled
- Twenty Twenty-Two theme active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #51473 

## What?
This PR fixes a problem where the block deprecation fails in cover blocks where "Fixed Background" is enabled.

https://github.com/WordPress/gutenberg/assets/54422211/33c9493c-9873-4450-83f3-d7345c8225b4

## Why?
#46969 adds `tagName` attributes to change the default `<div>` of the cover block to other elements. Because all but the newest markup has no default `tagName` attributes, the deprecation from `v1` to `v9` has an additional `migrate` property that defines a default `tagName` attributes. 

However, `v10` and `v11` deprecation appear to be missing that process. As a result, if the old markup matches a deprecation after `v10`, the save function will fail to process it because the `tagName` attribute is `undefined`.

## How?
I have added a similar migrate process to `v10` and `v11` deprecation.

## Testing Instructions

Insert a cover block using the following markup:

```html
<!-- wp:cover {"url":"https://live.staticflickr.com/2328/2061718046_64bbbc0a04_b.jpg","hasParallax":true,"dimRatio":70} -->
<div class="wp-block-cover has-parallax" style="background-image:url(https://live.staticflickr.com/2328/2061718046_64bbbc0a04_b.jpg)">
	<span aria-hidden="true" class="wp-block-cover__background has-background-dim-70 has-background-dim"></span>
	<div class="wp-block-cover__inner-container">
		<!-- wp:paragraph {"placeholder":"Write title…"} -->
		<p>Fixed background</p>
		<!-- /wp:paragraph -->
	</div>
</div>
<!-- /wp:cover -->
```

When the focus is removed from the code editor, confirm that a migration is performed to ensure that the block is updated with the latest markup.

### Another test instructions

- In WordPress 6.0 where the cover block has this markup, insert the cover block and activate "Fixed Background". Please disable the Gutenberg plugin.
- Update WordPress to the latest version and activate the Gutenberg plugin.
- Confirm that the migration is properly executed when the block editor is opened.

### CODE REVIEW

**Review by mikachan — APPROVED** [review]
This works well for me 👍

Tested using WP 6.3-beta4, Gutenberg trunk, I can replicate the save function failing to process and I see the console errors.

With this PR and again using WP 6.3-beta4, I can see there are no console errors and the save function works successfully ✅

**Comment by t-hamano** [comment]
Thanks for the review, @mikachan!

I have merged the latest trunk into this PR and I have tested it again too. It is working as expected and I would like to merge it 👍

**Comment by mikachan** [comment]
Does this need the `Backport to WP Beta/RC` label to ensure it's included in WP 6.3?

**Comment by t-hamano** [comment]
> Does this need the `Backport to WP Beta/RC` label to ensure it's included in WP 6.3?

Yes, I think that would be good 👍

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-batch-pre-RC1 branch to get it included in the next release: 521b573b4a

**Pull request merged**
