### PR TITLE
Update InputControl and SelectControl default heights

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Make the default `height` / `min-height` for `InputControl` and `SelectControl` `32px` rather than `30px`.

## Why?
Interactive elements like buttons and inputs are trending towards a 24px, 32px, and 40px sizing scale. The current 30px default applied to InputControl and SelectControl violates this convention resulting in awkward sizing mismatches, for example in the data view pagination UI:

Screenshot 2023-10-19 at 15 00 38

The icon button(s) are 32px tall while the page number input is only 30px. This issue will likely become more apparent as we proceed with the admin redesign project.

## Testing Instructions
1. `npm run storybook:dev`
2. Open Storybook (should happen automatically when the previous command completes)
3. Observe that `InputControl` and `SelectControl` (and any components that utilise them e.g. `UnitControl`) are 32px tall when `size` is `default` and `__next40pxDefaultSize` is `false`.
4. Check instances of these components in the Editor

| Before | After |
| --- | --- |
| Screenshot 2023-10-19 at 15 04 21 | Screenshot 2023-10-19 at 15 04 12 |

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Likely needs a changelog entry? But yes, we should not use base10 anywhere.

**Comment by ciampo** [comment]
Relevant conversation about introducing these size changes: https://github.com/WordPress/gutenberg/issues/55401

**Comment by jameskoster** [comment]
@ciampo how do you think we should proceed here? I don't think an increase of 2px warrants a temporary prop or other affordance due to the minimal impact.

**Comment by ciampo** [comment]
I personally agree with you — I just wanted to flag it and add more context for any future readers.

I believe this PR is good to go once unit tests are fixed

**Review by ciampo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
