### PR TITLE
BoxControl: Add custom units

### LINKED ISSUE #27615: Global Styles: Add custom units to BoxControl
**Is your feature request related to a problem? Please describe.**
The BoxControl component doesn't support custom units.

**Describe the solution you'd like**
I think the BoxControl component should support custom units so that it can work with Themes that want to use other units.

### PR DESCRIPTION
**Pull request by scruffian**
## Description
Adds support for custom units to the box control component when the theme declares support for it.

Fixes #27615

## How has this been tested?
In TwentyTwentyOne Blocks

## Screenshots 
Screenshot 2020-12-09 at 21 29 12

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice small PR, welcome feature. I'll defer a code review to the others, but happy to see this land!

**Comment by kjellr** [comment]
I'm seeing the Cover block throw an error when I try to test this PR. 🤔 

Screen Shot 2020-12-10 at 10 08 18 AM

**Review by oandregal — APPROVED** [review]
This works as expected and themes can filter the values by adding fewer units in the `customUnits` property of its theme.json.

Note that TT1-blocks needs updating to work with this, I've prepared a PR at https://github.com/WordPress/theme-experiments/pull/139

This can go in as soon as tests are green. The two that were failing seemed unrelated so I've restarted them.

**Comment by nosolosw** [comment]
FWIW, I've tested this with cover and group and works fine for me.

**Review by aristath — APPROVED** [review]
LGTM :+1:

**Pull request merged**
