### PR TITLE
Add plugins styles customization support

### PR DESCRIPTION
**Pull request by Lucisu**
## Description
This pull request adds three filters that allow plugins to customize Global Styles and theme.json files.

It solves #37206

## How has this been tested?
Just added filters, so my tests were just loading everything, pretty straightforward.

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Lucisu** [comment]
I just noticed I added the commit to the 12.0.2, I'll try to fix it later

**Comment by aristath** [comment]
Hey there @Lucisu, thank you for this PR!
I'm not sure what this is trying to accomplish though. It looks like you're trying to allow changing the path of the `theme.json` file? If so, for what purpose? 
We can already load alternative data by using the WP_Query filters when the parser tries to get the user-data 🤔

**Comment by Lucisu** [comment]
Hello, @skorasaurus! I'm sorry for the delay.

So, I remember that when I sent this pull request, I was developing a custom plugin that would inject some content out of the user data in the theme.json in runtime.

I didn't find any filters to accomplish this, so I had to create a workaround, and not very beautiful.

Please, let me know if it makes sense.

Thank you!

**Comment by Mamaduka** [comment]
Hi, @Lucisu

The #44015 introduced a few hooks that might serve the same purpose.

Handbook: https://developer.wordpress.org/block-editor/reference-guides/filters/global-styles-filters/.

Let me know if we can close this PR.

Thanks,

George

**Comment by Lucisu** [comment]
Hey there! Yep, that will solve the problem!

Thanks ;)

**Pull request closed without merging**
