### PR TITLE
Block Bindings: Add styles for attribute panel read only state

### LINKED ISSUE #65093: Block Bindings: Improve styling for read only state in attributes panel
## What problem does this address?

As of https://github.com/WordPress/gutenberg/pull/64570, only admins can create and modify block bindings using the attributes panel. While users with the editor role can see the panel, for them it is non-interactive.

We currently do not distinguish between these two states, so when it is read only, this may be perceived as unintentional and a bug.

Since we just removed the experimental flag, we should remedy this to ensure block bindings has a good user experience.

363805080-2feb5406-7968-4d1e-95af-718b94d6efe9

## What is your proposed solution?

We should change the styling for the read only state, perhaps setting the text to gray.

### PR DESCRIPTION
**Pull request by artemiomorales**
## What?

Currently, only admins can create and modify bindings using the attributes panel, whereas for editors the panel is in a read only state. We do not distinguish between these two modes, so this PR adds styling to distinguish when the attributes panel is non-interactive.

## Why?

Addresses https://github.com/WordPress/gutenberg/issues/65093

We want to signal when the attributes panel is read only so users don't perceive that as a bug.

## How?

It sets the attribute name to gray in the panel.

## Testing Instructions

1. In the post editor, using an admin account, add a paragraph and create a connection. Save the post.
2. Using a non-admin user with editor privileges, access the same post.
3. See that the attribute name in the attributes panel has been set to gray.

### Before

Screenshot 2024-09-05 at 5 49 04 PM

### After

Screenshot 2024-09-05 at 5 47 03 PM

### CODE REVIEW

**Comment by artemiomorales** [comment]
@jasmussen Just changing the text color may be too subtle. Do you think there's anything else we should do to signal when the attributes panel is read only?

**Comment by jasmussen** [comment]
This is the difference I see. Admin:

Screenshot 2024-09-06 at 09 19 40

Editor:

Screenshot 2024-09-06 at 09 21 01

* No ellipsis
* Content isn't clickable
* "content" text is gray instead of black

Removing the interactivity and ellipsis helps. I agree just changing the color doesn't add much. Do we need it?

If we need to _disable the button_, it should actually look disabled. And for disabled buttons, there are no contrast requirements, so in principle you could add something like `opacity: 0.3` to the disabled text.

Another option would be to apply the $gray-100 color as a background color on the item.

**Comment by gziolo** [comment]
> If we need to disable the button, it should actually look disabled. And for disabled buttons, there are no contrast requirements, so in principle you could add something like opacity: 0.3 to the disabled text.

I was thinking about that as well. Putting the `disabled` attribute on the `button` HTML element would also simplify the code as we won't need two different visual representations for exactly the same data. So, in general, one attribute should automatically resolve the issue and provide a consistent experience.

**Comment by SantosGuillamot** [comment]
> Removing the interactivity and ellipsis helps. I agree just changing the color doesn't add much. Do we need it?

I agree that changing the color doesn't add too much value. I would personally lean towards:
* Not doing anything: We are already removing the interactivity and ellipsis.
* Adding a "disabled" state to the whole box: We need to consider that, when there is no interactivity, it is not a BUTTON element anymore. They are just normal DIV with SPAN. I am not sure if this "disabled" state in the `ToolsPanel` is something we are doing in other parts of the editor or if it would be a unique use case.

**Comment by jasmussen** [comment]
Not doing anything can always serve as a starting point.

Here's what the gray background would do:

Screenshot 2024-09-06 at 10 07 17

Not helping either, and there's still a white border glitch at the bottom of the itemgroup component.

**Comment by gziolo** [comment]
> I was thinking about that as well. Putting the disabled attribute on the button HTML element would also simplify the code as we won't need two different visual representations for exactly the same data. So, in general, one attribute should automatically resolve the issue and provide a consistent experience.

I don't know how viable it is to tap into the `ToolsPanelItem` and find the right place to disable the button. There are too many levels of components to check it quickly for me.

**Comment by artemiomorales** [comment]
> Not doing anything can always serve as a starting point.

> Adding a "disabled" state to the whole box: We need to consider that, when there is no interactivity, it is not a BUTTON element anymore. They are just normal DIV with SPAN. I am not sure if this "disabled" state in the ToolsPanel is something we are doing in other parts of the editor or if it would be a unique use case.

Ok, I'm hearing that...
1.) We can start by doing nothing, and
2.) Since the box is not technically a button in the read only state, then perhaps there's no further action necessary

Am I getting that right? If so, we can close this PR and issue for now and see what the feedback is.

**Pull request closed without merging**
