### PR TITLE
Fix Ubuntu setup documentation

### LINKED ISSUE #20260: Error in Ubuntu local development troubleshooting doc.
**Describe the bug**
If you follow [the local development troubleshooting doc for Ubuntu](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/env-ubuntu.md), it doesn't work. 

**To reproduce**
1. Do everything on [the page](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/env-ubuntu.md). 
2. Open http://localhost:8889
3. You can see the page below:

Screenshot from 2020-02-17 14-51-21

**Expected behavior**
Local development should set up successfully.

**Screenshots**

Check above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version 80.0.3987.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
- Gutenberg version: master branch [currently 7.5.0]

### PR DESCRIPTION
**Pull request by sainthkh**
Closes #20260

## Description
Added specific steps after installing and setting up docker to finish the WordPress installation. 

## How has this been tested?

N/A

## Screenshots 

N/A

## Types of changes
Bug fix (document fix)

## Checklist:
- [N/A] My code is tested.
- [N/A] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [N/A] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ockham — CHANGES_REQUESTED** [review]
Hi, I'm also on Ubuntu. I wasn't aware of the `env-ubuntu` doc, but recently ran into the same issue when following the "Getting Started" doc. People pointed me to the new `wp-env` based setup, and I updated that doc accordingly (#20044).

(The gist is that instead of using `npm run env start`, you now run `npx wp-env start`.)

I think that the `env-ubuntu` doc should be aligned with the Getting Started doc -- both should suggest _either_ `npm run env start`, _or_ `npx wp-env start` -- and from what people have told me, it's the latter that we're going to commit to.

**Comment by sainthkh** [comment]
@ockham I'll follow the new doc and check if it works.

**Comment by sainthkh** [comment]
As you raised this issue in #20180, it seems that `npx wp-env start` doesn't work for now in Ubuntu. 

It seems that the problem was that easy as fixing this document.

**Comment by talldan** [comment]
> it seems that npx wp-env start doesn't work for now in Ubuntu.

Hey @sainthkh, in what way doesn't it work?

**Comment by mkaz** [comment]
I updated the docs in PR #25060 based on the latest Ubuntu version 20.04.1

Can you confirm the updated documentation works as expected, you can view directly here:
https://developer.wordpress.org/block-editor/tutorials/devenv/docker-ubuntu/

If so, I think we can close this PR.

**Comment by sainthkh** [comment]
@mkaz It works. Close this PR.

**Pull request closed without merging**
