### PR TITLE
Components: Update dependencies shared with G2 components

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Related: https://github.com/ItsJonQ/g2/pull/233.

This PR tries to update dependencies shared with G2 components to their latest versions.

```json
{
	"@emotion/core": "10.1.1",
	"downshift": "6.0.15",
	"react-resize-aware": "3.1.0",
	"react-use-gesture": "9.0.0",
	"rtlcss": "2.6.2",
	"tinycolor2": "1.4.2",
}
```

The idea is that we use the same versions in `@wp-g2/*` packages so we don't use 2 copies of the same packages in Gutenberg.

## How has this been tested?

I'm waiting for CI to verify if there are any breaking changes. I hope there none :)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
It looks liek `@emotion/core` has quite fundamental changes, I will downgrade to the previous version.

**Comment by gziolo** [comment]
`rtlcss` v3 has too many breaking changes, it requires PostCSS 8. Downgrading to the previous major version.

**Comment by gziolo** [comment]
I still some unit tests failing:

```
  ● PanelBody › toggling › should toggle when clicking header
9155

9156
    TypeError: Cannot add property current, object is not extensible
9157

9158
      115 | 
9159
      116 | 		it( 'should toggle when clicking header', () => {
9160
    > 117 | 			const { container } = render(
9161
          | 			                      ^
9162
      118 | 				<PanelBody title="Panel" initialOpen={ false }>
9163
      119 | 					<div>Content</div>
9164
      120 | 				</PanelBody>
9165

9166
      at forEach (node_modules/react-merge-refs/src/index.tsx:11:10)
9167
          at Array.forEach (<anonymous>)
9168
      at node_modules/react-merge-refs/src/index.tsx:7:10
9169
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
```

It looks like an issue with `react-merge-refs` or tests need to be updated.

**Comment by ItsJonQ** [comment]
@gziolo Haii! Just a heads up, I merged in your G2 Component dependency update and made a release:
https://github.com/ItsJonQ/g2/releases/tag/v0.0.136

**Comment by gziolo** [comment]
I also downgraded `react-merge-refs` as it was failing with unit tests for `<PanelBody />` component. I couldn't figure out while it suddenly started to throw errors. I found out also that @ellatrix is working on a `useMergeRefs` hook that is eventually going to replace this tiny library so it doesn't make sense to waste time on debugging.

**Comment by gziolo** [comment]
@ItsJonQ, I'm afraid that drag gestures no longer work on `InputField`.

It works differently at:
https://wordpress.github.io/gutenberg/?path=/story/components-numbercontrol--default

and in the local instance. They had two major version bumps:
- https://github.com/pmndrs/react-use-gesture/blob/main/documentation/pages/docs/changelog.mdx#800
- https://github.com/pmndrs/react-use-gesture/blob/main/documentation/pages/docs/changelog.mdx#900-release

Let me know if you have an idea how to fix it. Otherwise, this PR is good to go.

**Comment by ItsJonQ** [comment]
@gziolo Thanks for the heads up!

I'll take a look at the drag gestures.

**Comment by ItsJonQ** [comment]
@gziolo I just made an update for the drag gestures 🤞

**Comment by gziolo** [comment]
This PR removed 17kB from the bundle size

Screen Shot 2021-01-21 at 13 31 57

It looks like we are using two copies of Reakit. I opened https://github.com/ItsJonQ/g2/pull/237 to address it on the `@wp-g2` side first.

**Pull request merged**
