### PR TITLE
Removed block transforms from the toolbars.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
This PR removes the block transforms from the toolbar.
Fixes: https://github.com/WordPress/gutenberg/issues/6449

## How has this been tested?
Select multiple paragraphs, verify no multi-select transform button appears at the side of Content Structure button (top of the editor).
Select a single paragraph and verify the transforms button does not appear in the toolbar.
Verify both multi-block transforms, and single block ones, work correctly when pressing the "More options" button (three points at the side of the block).

### CODE REVIEW

**Review by karmatosed — APPROVED** [review]
Looks great, thanks!

**Comment by jasmussen** [comment]
Great to see polish and enhancements, and I do agree with the main purpose of #6449, reducing the number of transform tools. 

However in this case I can't help but feel like we should've removed the transformations in the block's More menu, as opposed to the button in the toolbar:

- Removing it from the toolbar means we need a different approach to solving https://github.com/WordPress/gutenberg/issues/3785
- Although perhaps rarely used, they are more discoverable in the toolbar than in the More menu
- If we are to convert the two quote blocks into three separate quote blocks as part of https://github.com/WordPress/gutenberg/issues/5947, it further reduces discoverability.

Right now the heading block looks like this (don't mind the bg color):

screen shot 2018-05-01 at 10 45 07

While we can certainly improve that, it does make it harder to unify toolbars across the basic text blocks.

**Comment by mtias** [comment]
I agree, I think we need a better design for the top level transforms before removing them from the toolbar. Too many interactions are going to depend on it.

**Comment by karmatosed** [comment]
Whilst I stand by it should be removed from one place and not be in two, I am also in agreement that moving back to just under toolbar area makes sense. That said it should be either not done and some better solution done soon or done as an interim.

**Comment by jasmussen** [comment]
There are challenges with the switcher as it stands. After discussing with Matías and Tammie in a chat, there are a few challenges with the switcher in the toolbar, one being that it feels like one giant toolbar, when the switcher is perhaps important enough to be grouped separately. 

So the toolbar needs a little love, in other words, around these principles:

- #6449 is still valid — probably best to have a single interface for transformations
- block transforms is primary action
- block variation UI needs work (heading sizes, quote types)
- toolbars should probably only have either block alignments, or text alignments, not both
- text alignments good to have on h1-6 and p
- consider better way to group functions in toolbar, so it’s not just one giant toolbar

Those are improvements that are worth looking at as soon as we can, both so we can address #3785, and #5947. 

---

In the mean time, perhaps we should revert or _invert_ this PR. Either simply revert this and bring back the toolbar switcher, or bring back the toolbar switcher _and_ remove the More menu transformations. CC: @jorgefilipecosta

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen thank you for your inputs. A PR that reverts this changes was created https://github.com/WordPress/gutenberg/pull/6566.

**Pull request merged**
