### PR TITLE
Place "Write mode" functionality behind a Gutenberg experiment

### LINKED ISSUE #66881: Place "Write mode" functionality behind a Gutenberg experiment
In light of user testing and current known limitations outlined in https://github.com/WordPress/gutenberg/issues/60021, let's change Write mode to an experiment for now to better contain the experience and give time for the feature to evolve before rolling it out more broadly again. In the referenced issue, I put together a list of proposed Tasks to stabilize Write mode that can be discussed further there. 

cc @ntsekouras  @youknowriad @mcsf  for help!

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Resolves: https://github.com/WordPress/gutenberg/issues/66881

>In light of user testing and current known limitations outlined in https://github.com/WordPress/gutenberg/issues/60021, let's change Write mode to an experiment for now to better contain the experience and give time for the feature to evolve before rolling it out more broadly again. In the referenced issue, I put together a list of proposed Tasks to stabilize Write mode that can be discussed further there.

### CODE REVIEW

**Comment by carolinan** [comment]
I want to ask if we are sure this is what we want to do, since it does not restore the previous modes.

**Comment by ntsekouras** [comment]
>I want to ask if we are sure this is what we want to do, since it does not restore the previous modes.

@carolinan it's being discussed in the issue and it seems that's the case, yes.

**Comment by mcsf** [comment]
Do we need to use `setGutenbergExperiments` to set up the E2E testing environment? Or are all the failures spurious?

**Comment by ntsekouras** [comment]
>Do we need to use setGutenbergExperiments to set up the E2E testing environment? Or are all the failures spurious?

For start I'm seeking some feedback about the changes, whether I'm missing something. I'll look at the tests later and we should probably update some flags for tests in `write` mode.

**Review by mcsf — COMMENTED** [review]
Looks good, except for the phrasing (and possibly experiment ID). It currently sounds like the experiment activates Write mode, whereas what it does is enable a Write/Design mode switcher. But maybe that's just me.

**Comment by ntsekouras** [comment]
In [this line](https://github.com/WordPress/gutenberg/pull/67008/files#diff-aa92c48095c35f17feb834dd919baf52274a73c7b1180ff5acce7b6087b126cfR2777) we always set the mode to `design` if the experiment is not enabled. So it's not just about the switcher, but also enforcing the mode, since it's a preference.

**Comment by mcsf** [comment]
> In [this line](https://github.com/WordPress/gutenberg/pull/67008/files#diff-aa92c48095c35f17feb834dd919baf52274a73c7b1180ff5acce7b6087b126cfR2777) we always set the mode to `design` if the experiment is not enabled. So it's not just about the switcher, but also enforcing the mode, since it's a preference.

Yes, I was thinking about that, and the best way to phrase both things.

**Comment by ntsekouras** [comment]
>Yes, I was thinking about that, and the best way to phrase both things.

Any suggestions are welcome. I wouldn't worry much for the php flag though - just the experiment label.

**Comment by mcsf** [comment]
> > Yes, I was thinking about that, and the best way to phrase both things.
> 
> Any suggestions are welcome. I wouldn't worry much for the php flag though - just the experiment label.

I have no better ideas and I'd rather just have this PR merged. This is fine.

**Review by mcsf — APPROVED** [review]

**Pull request merged**
