### PR TITLE
Allow sharp gradients.

### LINKED ISSUE #23816: Gradient Tool: Color stops should be allowed to overlap or even switch places.
The color stops in the gradient control currently can't overlap:

gradients

That means you can only ever create a _gradient_:

Screenshot 2020-07-09 at 10 07 26

However if we did allow them to overlap, you could create perfectly sharp color stops like this:

Screenshot 2020-07-09 at 10 08 47

That's a wonderful aspect of gradients that we should allow. 

[This online tool](https://www.colorzilla.com/gradient-editor/) to generate gradients allows color stops to overlap, and to even go to the other side. That feels powerful, and lets you create cool things easily:

example

### PR DESCRIPTION
**Pull request by jasmussen**
This extracts a small change from https://github.com/WordPress/gutenberg/pull/23802#issuecomment-672659623 to allow sharp gradients. Before, only this was possible:

Screenshot 2020-09-01 at 12 24 58

With this PR, this is possible:

Screenshot 2020-09-01 at 12 26 13

Fixes #23816. That's the good news.

The bad news is that the variable this PR changes allows the "plus" to be created on top of an existing handle:

plus

It would be such a nice feature to have, is there an easy fix to address that? CC: @jorgefilipecosta

### CODE REVIEW

**Comment by jorgefilipecosta** [comment]
Hi @jasmussen, thank you for this fix 👍 It seems the variable  MINIMUM_DISTANCE_BETWEEN_POINTS was also used for the distance between inserter and existing points and the movement that is applied to a point on using keyboard arrows. I created additional variables to fix the issue and it seems the inserter is working well now. Unfortunately, the keyboard movements are still broken but that is another issue not from this PR and I will try to fix it separately. Let me know if things are working well in your tests :)

**Comment by jasmussen** [comment]
YES JORGE! That is solid! So good!

gradients

We can't ship this fast enough!

**Review by ntsekouras — APPROVED** [review]
These gradients definitely looks great! 💯  - Thanks!

Green CI and let's land this!

**Comment by mtias** [comment]
Nice little improvement everyone :)

**Pull request merged**
