### PR TITLE
fix: Fix inserter misalignment regression

### LINKED ISSUE #10453: Inserter triangle is misaligned
**Describe the bug**
The triangle that connects the block inserter selection to the "Add Block +" button is disconnected from the block.

**To Reproduce**
1. Go to "Add New Post"
2. Click on "Add block (+)" on the left of the empty block
3. Observe the disconnect!

**Expected behavior**
It's connected.

**Screenshots**
screenshot 2018-10-09 21 13 22
screenshot 2018-10-09 20 52 41

**Additional context**
Tested in Chrome and Firefox on `master`; probably happens elsewhere too.

### PR DESCRIPTION
**Pull request by tofumatt**
Fix #10453

## Description
Fixed the visual regression caused in #10295 by moving the margin fix to target the NUX tooltips specifically.

## How has this been tested?
Tested in RTL and LTR, in Firefox, mobile and larger viewports.

### Before
screenshot 2018-10-09 20 52 41

### After
screenshot 2018-10-10 01 30 52

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Looks good! The only thing I spotted is that prior to #10295 the margin for the popver used to be -24px, and we might want to restore it to it's original value:
https://github.com/WordPress/gutenberg/pull/10295/files#diff-dcb8eefee4aaf82c9ddb042494547527L174

**Review by jasmussen — CHANGES_REQUESTED** [review]
This needs slightly more time in the oven. Just noting here so you don't merge, will follow up with a comment shortly.

**Comment by tofumatt** [comment]
> Looks good! The only thing I spotted is that prior to #10295 the margin for the popver used to be -24px, and we might want to restore it to it's original value:
https://github.com/WordPress/gutenberg/pull/10295/files#diff-dcb8eefee4aaf82c9ddb042494547527L174

I saw that but didn't notice a difference when setting it… but maybe I set the wrong one and in general I found that CSS to be a bit hard to keep track of. 🤷‍♂️ I'll try again, after @jasmussen tells me what I undercooked! 😉

**Comment by jasmussen** [comment]
Thanks so much for working on this, nice work. 

I'm happy to see that this also appears to fix a regression with tooltips that's currently present in master:

screenshot 2018-10-10 at 09 55 46

This branch:

screenshot 2018-10-10 at 10 06 37

3.9:

screenshot 2018-10-10 at 10 07 38

But sadly there is a little more work to be done.

This branch:

screenshot 2018-10-10 at 10 08 32

3.9:

screenshot 2018-10-10 at 10 04 40

Notice how in this branch, the triangle is way on the edge, whereas in 3.9 it's indented a bit. To be perfectly precise the _triangle_ is right, but the popout is not.

This also manifests in other usage of the popout component. This branch:

screenshot 2018-10-10 at 10 04 54

3.9:

screenshot 2018-10-10 at 10 04 48

This branch:

screenshot 2018-10-10 at 10 05 02

3.9:

screenshot 2018-10-10 at 10 05 08

HOPEFULLY the fix is as simple as using a negative margin to position the content, rather than a zero margin. But let me know if you need any help and I can jump in.

**Comment by tofumatt** [comment]
❤️ for all the info. I'll get on this after espresso.

**Comment by jasmussen** [comment]
No worries, and like I said if the CSS gives you headaches, reach out and we'll work on it together.

**Comment by tofumatt** [comment]
Unfortunately not, it introduces a new issue:



The popover on the edge of the screen gets pushed out-of-bounds so there's no border.

Using `$large-grid-size` looks okay by me and stays on the screen. It's `16px`. How about that?

**Comment by talldan** [comment]
Good catch! That looks good to me. @jasmussen?

Also, since #10430 was merged earlier, it might be worth rebasing if you haven't already. I don't know if it'll effect this PR, but it does change the padding in those menus.

**Comment by jasmussen** [comment]
Looking now.

**Comment by tofumatt** [comment]
Rebased and did not notice any issues.

On very small screens the issue above (the "…" menu's edge being pushed off-screen) still happens, but that seems to be an existing thing and this is at least better for most screen sizes.

**Comment by jasmussen** [comment]
I have to admit, I vastly prefer the negative margin of 24px to $grid-size-large, even if it means the ellipsis menu is cut off on the right. Here's 24px:

screenshot 2018-10-10 at 12 55 43

screenshot 2018-10-10 at 12 55 50

screenshot 2018-10-10 at 12 55 53

screenshot 2018-10-10 at 12 56 04

In this, everything seems more balanced and attached. 

While it would be nice for everything to be on a base8 grid, given that we're _not_ at the time, perhaps we can compromise and land on 20px? Here's 20:

screenshot 2018-10-10 at 12 59 40

(flush against the edge there!)

screenshot 2018-10-10 at 12 59 45

screenshot 2018-10-10 at 12 59 50

screenshot 2018-10-10 at 12 59 54

**Comment by tofumatt** [comment]
That 20px is so far against the edge of the page that it’s perceptibly the same as 24px to me.

If you prefer 24px I say we make it look nice there and treat the overflow off the page as a separate issue. The 20px seems a perfect compromise in that no one is happy ;-)

I’ve set it back to 24px; if you’re cool with that let me know.

**Review by jasmussen — APPROVED** [review]
With 24px it looks to me the same as it did before the regression. This is a good baseline to get back to. I'm sure separate iterations will look at popovers.

**Pull request merged**
