### PR TITLE
Fix improper e2e assertion in template-part.test

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

There are two problems here.
1. The test adds text "Header Template Part 123" but checks for text "Header Template Part123".
2. This `expect` checks whether or not the item destructured from the array results are not `null`.   An item destructured from an empty array is `undefined` (which indeed is not `null` and is why this test never failed previously due to item 1.)

I think the check part 1 was originally correct when this was used long in the past and we only added "123" to the existing demo template part at the time.  However, it seems problem 2 has existed since this test was originally implemented months ago.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
makes sense to me!

**Comment by noahtallen** [comment]
The lint check failed because the package.lock file is not up to date on `master`. Working on a fix for that now

**Comment by talldan** [comment]
I've just merged a PR to fix the package lock file, so will merge this 👍

**Comment by Addison-Stavlo** [comment]
Thanks for taking care of that 😄

**Pull request merged**
