### PR TITLE
Remove deprecated `behaviors` syntax

### PR DESCRIPTION
**Pull request by michalczaplinski**
## What?
Removes the deprecated `behaviors` syntax. 

Behaviors UI was originally introduced in https://github.com/WordPress/gutenberg/pull/49972. It was meant to be a way to add reusable pieces of interactivity to the frontend of sites. 

That implementation was removed in https://github.com/WordPress/gutenberg/pull/53851 and https://github.com/WordPress/gutenberg/pull/54509 and never merged into Core. Backwards-compatibility layer was added for users of the GB plugin.

## Why?
It should have already been deprecated in 17.0 because we only offer backwards-compatibility for 2 releases 🙂.

## How?
Removing 2 files and references to `behaviors` and `legacyLightboxSettings`.

## Testing Instructions

1. Open a post or page.
2. Insert an image block.
3. The "Expand on click" functionality should continue to work fine.
4. Try to insert the block that contains the removed syntax and it should NOT work anymore: 
   ```
   <!-- wp:image {"behaviors":{"lightbox":{"enabled":true}},"id":157,"sizeSlug":"large","linkDestination":"none"} -->
   <figure class="wp-block-image size-large"><img src="http://gutenberg.local/wp-content/uploads/2023/11/alan-hardman-SU1LFoeEUkk-unsplash-1024x678.jpg" alt="" class="wp-image-157"/></figure>
   <!-- /wp:image -->
   ```

### CODE REVIEW

**Comment by michalczaplinski** [comment]
> Please confirm whether these changes need to be synced to WordPress Core, and therefore featured in the next release of WordPress.

There is no need to sync anything to WordPress Core. The removed/ updated files were never part of Core in the first place because Behaviors didn't ship in 6.4.

**Comment by artemiomorales** [comment]
For reference, the backwards compatibility was added in https://github.com/WordPress/gutenberg/pull/54071

**Review by artemiomorales — APPROVED** [review]
This looks good to me and appears to get rid of the backwards compatibility that should be removed.

However, I'll note that the following testing instructions are incorrect:

> 4. Try to insert the block that contains the removed syntax and it should NOT work anymore: 
>   ```
>   
>   <figure class="wp-block-image size-large"></figure>
>   
>   ```

At the block level, the `behaviors` syntax is still supported and migrated via the image's [deprecated.js](https://github.com/WordPress/gutenberg/blob/16bc9a08e361c23c90a592898785725431e73cfd/packages/block-library/src/image/deprecated.js#L1057), logic which I believe should still remain intact.

Rather than handling that scenario, this PR removes the support for any custom block that had added the `behaviors` block support. It also removes the backwards compatibility for anyone who had enabled the lightbox using the prior version of the UI in the Site Editor.

With that caveat in mind, I think this PR is good to go @michalczaplinski 👍

**Comment by michalczaplinski** [comment]
Thanks for the review, @artemiomorales 

As far as I can tell, the `behaviors` syntax will not be supported for the Image block when we remove the compat layer [here](https://github.com/WordPress/gutenberg/pull/57165/files#diff-4167605a44440d5cfb787398fed6a2c0e85f2d83d358d57b9d9dba29ecb50734L442-L468) and [here](https://github.com/WordPress/gutenberg/pull/57165/files#diff-1e4aa29ea183efda9c795271dc1acf6e8049355db104d0dca5b0ea5caf7f619cL100-L105).


https://github.com/WordPress/gutenberg/assets/5417266/397b2945-1599-48a3-9598-56e68b3f437c

So, the block migration does not really do anything useful at the moment. It probably could just be removed as well. What do you think?

**Comment by artemiomorales** [comment]
> So, the block migration does not really do anything useful at the moment. It probably could just be removed as well. What do you think?

@michalczaplinski Hmm, so I believe the migration code doesn't actually run until you make a modification to the post before pressing Update. If you do that, you'll see that the `behavior` attribute get migrated to the new syntax:

https://github.com/WordPress/gutenberg/assets/5360536/3e642a27-64e5-4a87-9948-363cfbb319f2

With that in mind, the code in `deprecated.js` serves to move users to v8 of the of the block attributes.

That being said, I initially thought we would need to keep this to prevent breakage and inconsistencies in folks' block versions; as I'm looking at the [deprecation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) section of the handbook though, I think you're right and we may be able to remove the v8 code from `deprecated.js` since it appears the block versions are just migrated and determined at runtime.

What do you think? I could look at this more closely tomorrow.

**Comment by michalczaplinski** [comment]
> the migration code doesn't actually run until you make a modification to the post

That's weird! I didn't realize that the migration does not run until the post **Update**. I thought it should have been running on the initial publish as well.

I think that If we're removing the compat layer, then we can also remove the deprecations but I don't know if there's a precedent for that.

@ajlende Does that sound fine for you?

**Comment by artemiomorales** [comment]
> I think that If we're removing the compat layer, then we can also remove the deprecations but I don't know if there's a precedent for that.

Ok pinging @youknowriad @oandregal for feedback. Should we remove the [v8 version in the image's `deprecated.js`](https://github.com/WordPress/gutenberg/blob/79cca7e6a4b223bfbdefcd5df5937c6cf5274d00/packages/block-library/src/image/deprecated.js#L952) if we're no longer supporting `behaviors` and no longer have a need for the deprecation?

**Comment by ajlende** [comment]
> Hmm, so I believe the migration code doesn't actually run until you make a modification to the post before pressing Update.

It runs on `parse`, but I'm a bit surprised that `parse` never gets called on the initial save. I thought it used to be called even when you switched out of code mode, but I could also be misremembering.

> I think that If we're removing the compat layer, then we can also remove the deprecations but I don't know if there's a precedent for that.
>
> @ajlende Does that sound fine for you?

If there's a scenario where old attributes/markup could have been saved and those old attributes/markup are no longer valid, then you need a deprecation.

**Comment by oandregal** [comment]
> Hmm, so I believe the migration code doesn't actually run until you make a modification to the post before pressing Update.

Hi, I haven't worked much with deprecations, but this is my understanding:

- [Deprecations](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/) run when the block is invalid.
- An existing block having an unknown attribute does not make a block invalid. You can try by adding one attribute to the block using the code editor and switch to the visual editor (this also triggers the parse).

If we remove the deprecation, what would happen is that old blocks that used the `behaviors` attribute would maintain the attribute. It's block comment's pollution – no big deal, also not ideal.

What's important is that changing implementations should keep things working for the user. Ideally, we should maintain the deprecation and use it to migrate the block attributes to the new implementation.

An example of the ideal scenario:

- I set the lightbox for an image using the first behaviors' implementation. And I haven't touched the post since.
- After this PR (and all before), the image still has the lightbox enabled – using the new implementation.

Sorry I cannot provide more a more concrete answer. Hope this helps!

**Comment by artemiomorales** [comment]
Ok got it! Looks like the deprecation stays @michalczaplinski 👍

**Comment by michalczaplinski** [comment]
Thanks for your input folks! 

I'm merging it as is in that case (keeping the [deprecation](https://github.com/WordPress/gutenberg/blob/e1feedd6b5d9d9f454b56d44ef22b985a3b2133a/packages/block-library/src/image/deprecated.js#L944-L945)).

**Comment by getdave** [comment]
✅ I updated the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959) to note this PR does not require a backport for WP 6.5.

This is due to this comment (in the PR description):

> That implementation was removed in https://github.com/WordPress/gutenberg/pull/53851 and https://github.com/WordPress/gutenberg/pull/54509 and never merged into Core

**Pull request merged**
