### PR TITLE
Updating `eslint-plugin-jsdoc` for Node 18 support

### LINKED ISSUE #45696: `@wordpress/eslint-plugin` package does not support node.js 18
### Description

Node.js 18 is LTS now.
But `@wordpress/eslint-plugin` dependency `eslint-plugin-jsdoc` version is too old.

Error:
```
error eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.12.1"
```

Command `yarn why eslint-plugin-jsdoc` output:
```
=> Found "eslint-plugin-jsdoc@37.9.7"
info Reasons this module exists
   - "@wordpress#scripts#@wordpress#eslint-plugin" depends on it
   - Hoisted from "@wordpress#scripts#@wordpress#eslint-plugin#eslint-plugin-jsdoc"
```

### Step-by-step reproduction instructions

1. Install Node.js 18
2. `yarn add @wordpress/scripts`

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Node version: 18.12.1
@wordpress/scripts version: 24.5.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by Antonio-Laguna**
## What?

This updates `eslint-plugin-jsdoc` which is part of `eslint-plugin` to a version that allows Node 18. 

## Why?

Right now installing these packages on Node 18 results in errors due to that plugin requiring a previous version of Node.

## How?

The package has been updated.

Supersedes #42656
Fixes #45696

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
I'm unsure how to fix this issue. First, the `npm` version that's set by `nvmrc` is `6.14.15` which should not have workspaces support as far as I know.

Also, the issue is actually that `eslint-plugin-jsdoc` gets installed at the package level and not at the root level. This is not something we can control as far as I know

**Comment by ntwb** [comment]
> Also, the issue is actually that eslint-plugin-jsdoc gets installed at the package level and not at the root level. This is not something we can control as far as I know

This is primarily I think because of this, package updates need to be updated using Lerna and the process outlined here:
- https://github.com/WordPress/gutenberg/tree/trunk/packages#managing-dependencies

Changelog also needs to be updated
- https://github.com/WordPress/gutenberg/blob/trunk/packages/eslint-plugin/CHANGELOG.md

**Comment by Antonio-Laguna** [comment]
@ntwb I did use `lerna` as was hinted on that doc but I tuned the version down manually and rerun `npm i`. I've redone this to just use what `lerna` gives and no manual version touching. In my local testing, the effect is the same, I still got the package in the local `node_modules` but let's see what the runner does.

EDIT: The runner seems to find the same issue 😞

<details><summary>Bash output</summary>

The `npm i` is after deleting the package so it gets removed from `package-lock.json`.

```bash
➜  gutenberg git:(feature/update-eslint-jsdoc-node-18) ✗ npm i

> gutenberg@14.5.0 postinstall /Users/alaguna/Projects/gutenberg
> patch-package && node ./patches/patch-xcode.js

patch-package 6.2.2
Applying patches...
@react-navigation/native@5.7.0 ✔
dom-scroll-into-view@1.2.1 ✔
react-native-keyboard-aware-scroll-view@0.8.8-wp-1 ✔
react-native-modal@11.10.0 ✔

> gutenberg@14.5.0 prepare /Users/alaguna/Projects/gutenberg
> husky install

husky - Git hooks installed
npm WARN @axe-core/puppeteer@4.0.0 requires a peer of puppeteer@^1.10.0 || ^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @octokit/plugin-paginate-rest@4.3.1 requires a peer of @octokit/core@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @react-navigation/stack@5.6.2 requires a peer of @react-native-community/masked-view@>= 0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-navigation/stack@5.6.2 requires a peer of react-native-gesture-handler@>= 1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN create-react-context@0.3.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN puppeteer-testing-library@0.5.0 requires a peer of puppeteer@* but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@7.1.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@7.1.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-sass-transformer@1.4.0 requires a peer of node-sass@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@11.6.2 requires a peer of react-native@>=0.60 <=0.64 but none is installed. You must install peer dependencies yourself.
npm WARN use-memo-one@1.1.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 24.845s

426 packages are looking for funding
  run `npm fund` for details

➜  gutenberg git:(feature/update-eslint-jsdoc-node-18) ✗ npx lerna add eslint-plugin-jsdoc packages/eslint-plugin
lerna notice cli v5.5.2
lerna info versioning independent
lerna info Adding eslint-plugin-jsdoc in 1 package
lerna info bootstrap root only

> gutenberg@14.5.0 postinstall /Users/alaguna/Projects/gutenberg
> patch-package && node ./patches/patch-xcode.js

patch-package 6.2.2
Applying patches...
@react-navigation/native@5.7.0 ✔
dom-scroll-into-view@1.2.1 ✔
react-native-keyboard-aware-scroll-view@0.8.8-wp-1 ✔
react-native-modal@11.10.0 ✔

> gutenberg@14.5.0 prepare /Users/alaguna/Projects/gutenberg
> husky install

husky - Git hooks installed
npm WARN @axe-core/puppeteer@4.0.0 requires a peer of puppeteer@^1.10.0 || ^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @octokit/plugin-paginate-rest@4.3.1 requires a peer of @octokit/core@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @reach/router@1.3.4 requires a peer of react-dom@15.x || 16.x || 16.4.0-alpha.0911da3 but none is installed. You must install peer dependencies yourself.
npm WARN @react-navigation/stack@5.6.2 requires a peer of @react-native-community/masked-view@>= 0.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-navigation/stack@5.6.2 requires a peer of react-native-gesture-handler@>= 1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN create-react-context@0.3.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN puppeteer-testing-library@0.5.0 requires a peer of puppeteer@* but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@7.1.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-autosize-textarea@7.1.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-sass-transformer@1.4.0 requires a peer of node-sass@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@11.6.2 requires a peer of react-native@>=0.60 <=0.64 but none is installed. You must install peer dependencies yourself.
npm WARN use-memo-one@1.1.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-filter-warnings-plugin@1.2.1 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 21.585s

426 packages are looking for funding
  run `npm fund` for details
```
</details>

**Comment by herndlm** [comment]
it looks like it worked fine for me following the docs you linked regarding lerna. at least the root lockfile looks better. I'd open another MR if you don't mind, ok?

**Pull request closed without merging**
