### PR TITLE
[TypeScript] Improve type definitions in @wordpress/core-data

### PR DESCRIPTION
**Pull request by adamziel**
## What problem does this PR solve

Exporting TypeScript type from `@wordpress/core-data` requires adding a tsconfig.json to the package. This PR prepares the type definitions so that one can be added without experiencing errors.

## Test plan

Confirm all checks are green – there are no runtime changes in this PR, only the type annotations are affected.

@noisysocks @sirreal @dmsnell @sarayourfriend

### CODE REVIEW

**Comment by dmsnell** [comment]
Can we separate the type fixes in a distinct PR and then look at adding the `tsconfig.json` in isolation?

**Comment by adamziel** [comment]
@dmsnell done!

**Comment by adamziel** [comment]
After removing tsconfig.json this is just a small PR cleaning up more-or-less obvious typing mistakes without any runtime changes so I'll just go ahead and merge.

**Comment by mburridge** [comment]
Added the Needs Dev Note label in case this needs a dev note (either individual or as part of a "misc" dev note) for WP 6.1 release.

**Pull request merged**
