### PR TITLE
Update README screenshot

### PR DESCRIPTION
**Pull request by mapk**
Updating the screenshot of Gutenberg to reflect the latest version – 6.8.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by mapk** [comment]
I'm looking to update the gif screenshot as well. Depending on how fast this gets merged, I can either include it in this PR, or create a new one.

**New Screenshot Proposed:**

gutenberg-6 8-border

**Review by gziolo — APPROVED** [review]
Nice, keep in mind that I'm not a designer 😂

**Comment by mapk** [comment]
@gziolo I'm hosting the gif on cloudup as well. Do you think that's a problem?

**Comment by mapk** [comment]
Let's see if we experience a problem hosting them on cloudup for now. If so, I can work on creating a ticket in Trac to get them hosted on w.org's CDN.

**Comment by mapk** [comment]
Oh yep, content length exceeded on that gif. I'll look for a way to optimize it.

**Pull request merged**
