### PR TITLE
[Fix] Make sure Latest Posts alignment class behaviour

### LINKED ISSUE #7911: Alignment: latest posts block reapplies `aligncenter` on save even if it was deselected
Moved from #4010 h/t @bradyvercher.

Steps to reproduce:

1. Insert a latest posts block.
1. Select the center alignment option in the block toolbar.
1. Deselect the center alignment option in the block toolbar.
1. Publish the post.

<strong>Result:</strong> the class is `aligncenter` even though alignment was deselected.

screen shot 2018-07-11 at wed jul 11 6 07 28 pm<sup>Seen at http://alittletestblog.com/2018/07/11/latest-posts-block/ running WordPress 4.9.7 and Gutenberg 3.2.0 using Firefox 61.0.1 on macOS 10.13.5.</sup>

### PR DESCRIPTION
**Pull request by nfmohit**
## Description
This PR closes #7911 which reports the incorrect behavior of the alignment classes in the Latest Posts block, where it applies alignment classes even if no alignment was selected. It also gets rids of the behavior where the center alignment is selected by default.

## How has this been tested?
This PR has been tested by going through the following steps:

1. Started a new post using the Gutenberg editor.
2. Added the Latest Post block.
3. Selected the center alignment option in the block toolbar.
4. Deselected the center alignment option in the block toolbar.
5. Published the post and made sure no alignment classes are added to the block, as the alignment was deselected.

This was tested in WP 4.9.8, Gutenberg 3.5.0, Apache server with PHP 7.2.0 and MySQL 5.6.34. According to initial tests, the code doesn’t seem to affect any other areas.

## Screenshots 
pull-7911-min

## Types of changes
This PR introduces a conditional before applying the alignment classes to make sure an alignment is selected in the first place. It also removes the `default` property from the `align` attribute, so that the center alignment isn't selected and applied by default.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Thinking about the original issue, if it was really intentional for center to be default, and how we'd support "unsetting" that value, I think if that was something we'd want to support, we could do so by setting the alignment to `null` instead of `undefined`. As `undefined`, I think it's sensible that the default value take effect.

This, of course, is a non-issue after these changes.

**Comment by aduth** [comment]
Totally unrelated to the changes here, but the alignment implementation doesn't work so well on lots of themes, where `margin: 0 auto;` on an element which is full-width already doesn't do anything (i.e. doesn't appear to be centered). But the class is there.

**Review by aduth — APPROVED** [review]
Looks good 👍

**Comment by aduth** [comment]
Failing test was legitimate. `=>` assignment alignment needed to be updated. Pushed change in c1fabd2.

**Comment by nfmohit-wpmudev** [comment]
@aduth Any idea why we don't use `flex` to center the list items instead of `margin: 0 auto;` which mostly doesn't work.



That would, of course, require us to wrap the list up with a `div` wrapper. Let me know if you want me to submit PRs with that. Thanks ❤️

**Comment by aduth** [comment]
@nfmohit-wpmudev 

A few things:

- Apparently we don't add anything in the editor to reflect center alignment? That might be a good first step 😄 
- There's already a fair bit of inconsistency in alignment options across blocks, observed at #3785 . The first point and this issue could be jointly remedied by using the [`align` supports](https://wordpress.org/gutenberg/handbook/block-api/#supports-optional)
- The `margin: 0 auto;` is the implementation of `.aligncenter`, which predates Gutenberg. I imagine the reasoning for this may be broader browser support: While `wp-admin` supports only IE11 and newer, we need to be more careful about the content we produce. I realize there's some hypocrisy here in that the Columns block uses Flex. Mentioning less as a reason to "not do it", but more as context for why it may not have been used.

**Comment by nfmohit-wpmudev** [comment]
Got it, thank you so much for the explanation @aduth ❤️

**Pull request merged**
