### PR TITLE
Global styles: Fix `array_merge` issue with empty values in sub-arrays for user settings

### PR DESCRIPTION
**Pull request by aristath**
## Description
Currently we're merging core, theme and user values for global styles like this:
```php
$result[ $block_name ]['presets'] = array_merge(
	$core[ $block_name ]['presets'],
	$theme[ $block_name ]['presets'],
	$user[ $block_name ]['presets']
);
```

When the user hasn't changed their defaults, the value of `$user[ $block_name ]['presets']` looks something like this:
```
[ 
	'color'     => [],
	'font-size' => [],
	'gradient'  => [],
]
```
The problem is that even if empty, the array keys still exist so `array_merge` will replace the previously existing - and valid - values with an empty array.
This causes issues because the font-sizes and colors for example from `experimental-theme.json` don't print their CSS variables.

## How has this been tested?
Tested by using the [`gutenberg-starter-theme-blocks`](https://github.com/WordPress/theme-experiments/tree/master/gutenberg-starter-theme-blocks) theme. Before the commit it wasn't printing css-variables for font-sizes defined in the JSON file.
After the commit these variables get properly printed.

Note: While checking this issue you may find that user-selected styles don't always get printed, it depends on the property. There is a separate PR for that, see https://github.com/WordPress/gutenberg/pull/25250

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by joyously** [comment]
Did you consider using `array_replace` instead? It was never used in core because it originated in PHP 5.3 and core had PHP 5.24 as a minimum for so long.

**Comment by aristath** [comment]
> Did you consider using `array_replace` instead?

If I'm not mistaken it would have the same issue... If the keys exist in the 2nd array the values will be replaced and it won't check whether it's replacing a "real" value with an empty array or not.

**Comment by joyously** [comment]
Can't you simply `array_filter` first then?

**Comment by aristath** [comment]
> Can't you simply array_filter first then?

Brilliant. Changed it to array_filter and confirmed everything works as expected. Does the same thing with far less code :+1:

**Comment by aristath** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/25286 which is a the correct solution to this issue.

**Pull request closed without merging**
