### PR TITLE
Update layout and text of 'Text two columns' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Moves the heading out of the text block and places it above. Also edited the text to have balanced columns.

Before:

Screen Shot 2020-07-09 at 19 12 52

After:

Screen Shot 2020-07-09 at 19 00 54

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
When exactly would someone actually create a layout like this? The proper way to handle multi-column text would be the [CSS `columns` property](https://developer.mozilla.org/en-US/docs/Web/CSS/columns). Manually splitting stuff up into separate `div`s like in this pattern isn't really the right way to accomplish a newspaper-style multi-column layout.

What would make more sense is adding a new kind of "Content Columns" (no idea what to call it) block that lets you define a number of columns and a wrapping height, which would make use of the aforementioned CSS property.

Also, why even include a font size or line height style on the Heading block? I think that should be removed.

**Comment by kjellr** [comment]
> What would make more sense is adding a new kind of "Content Columns" (no idea what to call it) block that lets you define a number of columns and a wrapping height, which would make use of the aforementioned CSS property.

I agree that a block like that is preferable, but in general I think this pattern serves the purpose of letting people know they can put text into multiple columns today (even with the faults you mention). 

The larger font size is subtle, but from a purely visual perspective I kind of like it: 

Custom Size|Default Size
---|---
Screen Shot 2020-07-10 at 8 41 20 AM|Screen Shot 2020-07-10 at 8 41 02 AM

Making the headline a little bigger increases the visual contrast between the paragraphs and the title. And the 1.5 line height is a better fit for this slightly larger text. I tried this in a couple other themes and these settings translate to a nice ratio too. 

From a systematic perspective I'm a little less into it — if the user inserts this alongside other `h2` blocks, they may be confused about why it is a different size by default. I'm a bit torn, so I'll defer to others for guidance here. 

I do have one additional note though. In my testing, Gutenberg's default styles create two em dashes in a row in that left column at the default content width on desktop: 

Screen Shot 2020-07-10 at 8 41 02 AM

This is not a _huge_ deal obviously, but since we're choosing this text, it would be great to avoid that. Same goes for the particularly short line caused by the word "involuntarily" not breaking over in the right column. 

(If we keep em dashes, I should also note that stylistically, I'm also big proponent of the AP style recommendation of adding spaces before and after em dashes).

**Comment by enriquesanchez** [comment]
Thanks for the feedback.

I've removed the custom font size from the heading and edited the text for visual balance:

Screen Shot 2020-07-10 at 13 08 26

**Review by mapk — APPROVED** [review]
Those last few edits work really well. LGTM

**Pull request merged**
