### PR TITLE
Update color button style

### PR DESCRIPTION
**Pull request by jameskoster**
This PR updates the color button styling. Some of the adjustments are cosmetic, while others address issues with the current implementation.

### Remove the fixed height

Currently the button has a static height value of 46px. This causes issues if you ever create a color with a very long name:

Screenshot 2022-06-21 at 14 13 59

The 46px value is a little arbitrary, and it doesn't seem too harmful to allow the button to grow in height as required. Here's the after:

Screenshot 2022-06-21 at 14 55 49

An alternative approach would be to truncate the label so that it is never more than a single line of text:

Screenshot 2022-06-21 at 14 58 57

If this is preferable it's easy to achieve by adding the following properties to the label.

```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```

### Adjust button padding
I bumped the button padding up from 6px to 10px, the result of which is a default button height of 40px, which is aligned with the original design concepts.

| Before | After |
| --- | --- |
| Screenshot 2022-06-21 at 15 02 28 | Screenshot 2022-06-21 at 16 45 16 |

### CODE REVIEW

**Comment by javierarce** [comment]
> An alternative approach would be to truncate the label so that it is never more than a single line of text

This is my favorite solution but I think that we should need to provide a way to read the full text that is also accessible.

**Comment by jameskoster** [comment]
I pushed an update that applies the truncation. 

I also added the `title` attribute to ensure it's always possible to determine the full name, but since the truncation is purely cosmetic I'm not 100% certain we need this 🤔 

Screenshot 2022-06-22 at 11 05 42

Edit: I suppose it's a good idea to include the title regardless, just in case you have two colors with very similar, very long names :D

**Comment by javierarce** [comment]
This works well in Chrome, but I see this on Firefox:

Screenshot 2022-07-13 at 13 21 33

**Comment by jameskoster** [comment]
Oh good spot! I noticed the truncation wasn't working in global styles either because apparently that's a different implementation 🙈 

Both should be fixed now.

**Comment by javierarce** [comment]
Nice! I tested it again and it works perfectly 🚀

**Review by noisysocks — APPROVED** [review]
Code looks good 👍

**Comment by oandregal** [comment]
Added label for changelog.

**Comment by mtias** [comment]
@ciampo @mirka shouldn't the component system handle this on its own?

**Comment by ciampo** [comment]
Yes, we should always aim at updating the components when possible — style overrides like the ones introduced in this PR should be avoided as much as possible, as they make the code fragmented, much harder to maintain and definitely more prone to breakage over time.

@jameskoster , could you please open an issue highlighting the discrepancies between the components and the spec? That way we can try to work on the components directly and remove these style overrides 🙏

**Comment by jameskoster** [comment]
@ciampo forgive my ignorance, but isn't the issue here that the color swatch + label button isn't actually a component yet?

**Comment by jasmussen** [comment]
Whether a component or not, one visual discrepancy is that Items in the ItemGroup should always be 40px tall exactly. Right now they are 56.something in a few places.

**Comment by ciampo** [comment]
From my point of view, there's a few things to keep into account:

 - The pattern "`ItemGroup` containing, as its children, a color swatch + label button" doesn't _not_ exist as a component, as we saw that as a high-level pattern that shouldn't be part of the components package (see [this conversation](https://github.com/WordPress/gutenberg/issues/36653) for more context). Instead, we provide [a way to implement such layout](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-itemgroup--complex-layouts) as part of the component's Storybook examples
 - If that's a pattern that is going to be used more and more in the future, we could discuss making a component for it, maybe in the `@wordpress/interface` package (or any other app-specific package)
 - Nonetheless, overriding components styles (i.e. `> button { // css here }`) should be be avoided for the reasons highlighted abeove
 - Finally, we should assess any discrepancies with the designs and determine what changes (and where in code) should be made to align out UIs to the design specs (for example, the height of each `Item` in `ItemGroup`)

**Comment by jameskoster** [comment]
> as part of the component's Storybook examples

So is this pattern the thing we need to update? 

Screenshot 2022-09-12 at 14 42 37

I believe we should be able to create this layout using our grid-unit vars, so a dedicated component probably isn't required.

**Pull request merged**
