### PR TITLE
Update Post Link block variation icon to match the one used in the Link UI results.

### LINKED ISSUE #50181: Update Post Link block variation icon to match the one used in the Link UI search results
We should use the same block icon that the Link control uses when displaying a post (which is the latest posts icon). 

CleanShot 2023-04-28 at 16 23 07

CleanShot 2023-04-28 at 16 24 37

CleanShot 2023-04-28 at 16 21 59

### PR DESCRIPTION
**Pull request by juanfra**
## What?

Update Post Link block variation icon to match the one used in the Link UI results.

Fixes https://github.com/WordPress/gutenberg/issues/50181

## Testing Instructions

1. Go to the site editor.
2. Edit the header, and select the navigation block.
3. Add a new post link.
4. Confirm that the icon is the same as the one used in the link UI results.

## Screenshots or screencast 

https://user-images.githubusercontent.com/252415/235202801-36f76f0e-e228-43e8-960d-39552251adcd.mov

### CODE REVIEW

**Comment by getdave** [comment]
Thank you! On my review list for this week.

**Comment by jameskoster** [comment]
Since we're using the `page` icon for Page Link, we should probably use the `post` icon for Post Link?

**Comment by juanfra** [comment]
Thank you! To add more context for the design review, this is how it'd look with the `post` icon, and the `postList`

#### `postList` icon.
Screenshot 2023-05-25 at 12 23 15

#### `post` icon.
Screenshot 2023-05-25 at 12 27 00

**Comment by jameskoster** [comment]
`post` makes more sense to me, seeing as the link is to a single post rather than a list/archive. I don't love the `post` icon itself, but that's not something to address here.

**Review by richtabor — APPROVED** [review]
LGTM

**Pull request merged**
