### PR TITLE
HTML API: Backport updates from Core

### PR DESCRIPTION
**Pull request by dmsnell**
This is a backport PR to bring updates from changes in WordPress/WordPress-develop at [54a09a7e](https://github.com/wordpress/wordpress-develop/tree/54a09a7ec99c59b8e640bd5aacebfdbf03bb02cc/src/wp-includes/html-api) into this repository into a compatibility layer.

 - WordPress/WordPress-develop#5535
 - WordPress/WordPress-develop#5725
 - WordPress/WordPress-develop#5762
 - WordPress/WordPress-develop#5539

### CODE REVIEW

**Comment by dmsnell** [comment]
@SergeyBiryukov when the WPCS ignore statements were removed in https://core.trac.wordpress.org/changeset/56753 it started preventing updates in this repo to the file where it was removed. I couldn't find a Trac ticket or any code review for that change before it was merged.

@hellofromtonya @anton-vlasenko I don't like merging over failing CI steps so I would appreciate your guidance. the WPCS rules which are preventing this PR from maintaining code harmony between the projects are the same rules that forced the change that created the obstacle; this seems silly.

**Comment by anton-vlasenko** [comment]
> I don't like merging over failing CI steps so I would appreciate your guidance. the WPCS rules which are preventing this PR from maintaining code harmony between the projects are the same rules that forced the change that created the obstacle; this seems silly.

I'm sorry to hear that misalignment in coding standards is still causing issues, @dmsnell. Hopefully, one day, coding standards can be fully aligned.

In my opinion , `VariableAnalysis.CodeAnalysis.VariableAnalysis` should be removed from Gutenberg since it is not enabled in Core. However, it is essential to analyze why it was added in the first place. Until this analysis takes place, I'd suggest adding the `<exclude-pattern />` statement for that folder:
I.e. replacing 
```xml
<rule ref="VariableAnalysis.CodeAnalysis.VariableAnalysis">
    <properties>
        <property name="allowUnusedParametersBeforeUsed" value="true"/>
    </properties>
</rule>
```

with
```xml
<rule ref="VariableAnalysis.CodeAnalysis.VariableAnalysis">
    <properties>
        <property name="allowUnusedParametersBeforeUsed" value="true"/>
    </properties>
    <!-- Exclude the html-api folder to prevent linter errors until coding standards are aligned. -->
    <exclude-pattern>./lib/compat/wordpress-*/html-api/*.php</exclude-pattern>
</rule>
```
What is your opinion on this?

**Comment by dmsnell** [comment]
> What is your opinion on this?

Sounds great @anton-vlasenko - I appreciate making the adjustment to the rules, and avoiding the need to add more IGNORE statements. I'll add that change in this backport PR. For some reason I often forget that I can modify the WPCS rules _in_ one of these backport PRs.

Thanks as always for your help.

> Hopefully, one day, coding standards can be fully aligned.

We'll get there. Things have been getting better. I think in this case the problem happened because someone changed Core in a way that broke Gutenberg but that change was never run through any review process or preview in Gutenberg, so the error didn't appear until it was too late.

**Review by ockham — COMMENTED** [review]
My personal preference aside, I'm afraid we can't merge this as-is: The problem is that the Dynamic Block PHP code (i.e. everything in `packages/block-library/src/**/*.php`) will be carried over into Core via npm package sync. But in Core, none of the back-compat `Gutenberg_HTML_Tag_Processor_6_x` classes exist, so it would fatal there 😕 

(The same _might_ apply to `lib/block-supports/*.php`, but I'm not sure about that.)

**Comment by dmsnell** [comment]
> carried over into Core via npm package sync. But in Core, none of the back-compat Gutenberg_HTML_Tag_Processor_6_x classes exist, so it would fatal there 😕

is there not a way we can replace those classes during the packaging? and doesn't this same problem exist in other shared code?

I can pull these out if we need to; still trying to find a more reliable method to avoid breakages.

**Comment by ockham** [comment]
> > carried over into Core via npm package sync. But in Core, none of the back-compat Gutenberg_HTML_Tag_Processor_6_x classes exist, so it would fatal there 😕
> 
> is there not a way we can replace those classes during the packaging?

We have sort of the reverse mechanism in place for some function names in Dynamic Blocks' PHP (that are changed from `wp_` to `gutenberg_`) at build time:

https://github.com/WordPress/gutenberg/blob/1275d2f0d02961a8cc109bcc3f3ab76a8609bdd6/tools/webpack/blocks.js#L25-L36

To avoid confusion, we'd need to align with that and also transform from `WP_` to `Gutenberg_` (rather than the other way round).

> and doesn't this same problem exist in other shared code?

I think we have a recommendation somewhere that Dynamic Blocks generally use functions rather than classes (and class methods); although upon some further research, there seems to be some precedent in the guise of some Style Engine related class names which are indeed transformed:

https://github.com/WordPress/gutenberg/blob/1275d2f0d02961a8cc109bcc3f3ab76a8609bdd6/tools/webpack/packages.js#L40-L46

...although the transformed names seem to look a bit different than the "usual" `Gutenberg_*_x_y` scheme:

https://github.com/WordPress/gutenberg/blob/1275d2f0d02961a8cc109bcc3f3ab76a8609bdd6/tools/webpack/packages.js#L57-L64

> I can pull these out if we need to; still trying to find a more reliable method to avoid breakages.

Thank you. How about we land the backport of https://github.com/WordPress/wordpress-develop/pull/5535 and https://github.com/WordPress/wordpress-develop/pull/5725 separately first (to unblock further work), and file a separate PR for the other changes (since they might need some more tweaking)?

---

TBH I'm still not 100% convinced we should really duplicate all classes from Core in GB's back-compat layer and update all code to use the latter, given that it'll add a ton more code that will need syncing and require that extra magic at build time, which will likely mean another list of classes tucked away in a webpack config that we'll need to keep updated.

**Comment by dmsnell** [comment]
@ockham this has been pared back to only include the changes to the existing classes.

**Review by ockham — APPROVED** [review]
LGTM!

I've compared all files to their counterparts in the https://github.com/WordPress/wordpress-develop repo. They are all exact matches, except for the different class names (as expected).

**Pull request merged**
