### PR TITLE
Use @wordpress/stylelint-config in @wordpress/scripts

### LINKED ISSUE #27775: Scripts: Deprecation warning when running wp-scripts lint-style
**Describe the bug**

The following warning is printed when running `wp-scripts lint-style`:

> Deprecation Warning: 'declaration-property-unit-whitelist' has been deprecated. Instead use 'declaration-property-unit-allowed-list'. See: https://github.com/stylelint/stylelint/blob/13.7.0/lib/rules/declaration-property-unit-whitelist/README.md

**To reproduce**
1. `npm init @wordpress/block` esnext-example
2. `cd esnext-example`
3. `npm run lint:css`
4. See the error

**Expected behavior**
No warnings.

### PR DESCRIPTION
**Pull request by ocean90**
## Description
Follow-up to #22777.
Fixes #27775.

I have trouble with updating stylelint in the `package-lock.json`. I tried the steps in https://github.com/WordPress/gutenberg/tree/master/packages#updating-existing-dependencies but it only updates the version. `npm update stylelint` did nothing either. @gziolo Can you help?

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
@ocean90, I'll have a look at the issue you described Monday at the latest 👍🏻

**Comment by ocean90** [comment]
@gziolo Sorry, read the docs again and I was missing the `npm install` step after removing the dependency. Should be good now.

**Review by gziolo — COMMENTED** [review]
Amazing work, thank you for wrangling it ❤️ 

I'm wondering if we want to batch more changes for the next major version of `@wordpress/scripts`. There is also PR (https://github.com/WordPress/gutenberg/pull/26382) from @jsnajdr that upgrades webpack from v4 to v5 waiting to be merged.

There is also approved PR (https://github.com/WordPress/gutenberg/pull/27327) from @sirreal that enabled new ESLint rules.

Some other items that we should consider:
- Update @wordpress/scripts to use PostCSS 8 https://github.com/WordPress/gutenberg/issues/27028
- Upgrade Jest to the new major version (26.x) https://github.com/WordPress/gutenberg/issues/22395

**Review by gziolo — APPROVED** [review]

**Comment by gziolo** [comment]
I created a milestone to make it easier to track what could go in the next major release of `@wordpress/scripts` (v13): https://github.com/WordPress/gutenberg/milestone/139. We could open a feature branch but it might be highly inconvenient to keep it up to date. Well, the same issue applies when keeping PRs opened for longer. @ocean90, @jsnajdr and @sirreal what do you think? I hope we can merge everything into `master` branch at the beginning of January.

**Comment by gziolo** [comment]
I rebased this PR with the latest changes in the main branch. If CI checks pass it should be fine to merge it. I started merging a number of PRs that introduce breaking changes to `@wordpress/scripts` so this one should be included in the same npm release as commented earlier.

**Comment by gziolo** [comment]
There is one e2e test failing that can't be related to those changes because we introduce changes only for style linting 🤷🏻 Let's proceed.

**Comment by ocean90** [comment]
Thanks @gziolo!

**Pull request merged**
