### PR TITLE
[Build Tooling]: Fix pre commit hook to build block docs

### PR DESCRIPTION
**Pull request by ntsekouras**
I don't know if it's just me and is specific to some environment params but I can't commit anything. The error is something like that:

```
npm-run-all api-docs:* found some errors. Please fix them and try committing again.
ERROR: Task not found: "/....../block-library/src/post-featured-image/block.json"
```

What happens here is that we have a pre commit hook that runs [npm-run-all api-docs:*](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L313) but `lint-staged` passes full paths to staged changes so in combination with the `npm-run-all`,  we end up trying to match a `task` from each `staged file`.

In this PR I removed the `npm-run-all` command to avoid the above issue and also changed the `TOKEN` for core blocks documentation in order to be notified by the `are-api-docs-unstaged.js` [here](https://github.com/WordPress/gutenberg/blob/trunk/bin/api-docs/are-api-docs-unstaged.js#L17), which is run right afterwards.

## Testing instructions
1. Commit anything and you will be able to 😄 
2. commit a change in `block.json` - let's say add an attribute and observe that it will not let you because of the updated docs

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
I can’t test it right now but the changes proposed look reasonable based on the explanation provided 👍

**Review by Mamaduka — APPROVED** [review]
I was able to reproduce the issue on the trunk, and the fix works as expected 👍

**Review by mcsf — APPROVED** [review]
Have I mentioned how much I hate tooling in the Node ecosystem? 😬 

Anyway, looks good, makes sense, and fixes it for me. :shipit:

**Comment by mkaz** [comment]
Thanks @ntsekouras for fixing, looks good. I thought I had it tested and working but 🤷‍♂️ 
I agree with @mcsf npm and node tooling definitely leaves something to be desired.

**Pull request merged**
