### PR TITLE
Make selected post-title unselect when another block selected

### PR DESCRIPTION
**Pull request by kamataryo**
Fix for #1390

### CODE REVIEW

**Comment by kamataryo** [comment]
Previous:
pre

This patch:
post

**Comment by youknowriad** [comment]
This is more complex than it seems, try saving you'll notice the permalink modal, and the title should remain selected (with borders) when we hit the "copy" button from the permalink modal.

**Comment by kamataryo** [comment]
@youknowriad Thanks for the comment. I fixed this PR and make the `post-title` check whether blocks selected or not and not attach `is-selected` class if so.

**Comment by mtias** [comment]
So here's a thought. What if we convert this to a real block again, with the restrictions that:
- it's already inserted by default.
- you cannot move it.
- it doesn't show in the inserter.
- (bonus) you can hide it in the inspector to get an "aside".

This should give us the interactions for free, as well as pave the way for cusotmization where you will be able to do more stuff with these non-content pieces (meta data, title, date, categories, etc).

**Comment by gziolo** [comment]
#1390 was fixed in other PR. I'm closing this one. Thanks for spending your time on this PR :)

**Pull request closed without merging**
