### PR TITLE
Enqueue registered block assets and resolve iframe styles e2e failure

### PR DESCRIPTION
**Pull request by oandregal**
## What

Temporary fix for iframe compat layer.

https://github.com/WordPress/wordpress-develop/pull/4356 was merged into core at https://github.com/WordPress/wordpress-develop/commit/5c247f75f37dce1ef2b416ef19ccdca1c69faf70 recently. Since then, the `packages/e2e-tests/specs/editor/plugins/iframed-inline-styles.test.js` e2e test is failing because it uses the Wordpress `trunk`.

## Why

The compat-layer of the iframe loads certain stylesheets based on whether they have a `.wp-block-`.

Before the change above, the stylesheets follow this order:

```
wp-block-library-css
wp-block-editor-content-css
wp-edit-blocks-css
iframed-inline-styles-style-css
test-iframed-inline-styles-editor-style-css
iframed-inline-styles-compat-style-css
```

After the change above, the stylesheets follow this order:

```
wp-block-library-css
wp-block-editor-content-css
wp-edit-blocks-css
iframed-inline-styles-compat-style-css
iframed-inline-styles-style-css
test-iframed-inline-styles-editor-style-css
```

Note how `test-iframed-inline-styles-editor-style-css` loads AFTER `iframed-inline-styles-compat-style-css`, which is the reason for the e2e to fail.

## How

The core commit expose a bug in the iframe that we should address. This PR is a temporary fix to "revert" the core commit from Gutenberg.

An alternative would be to skip the test for now.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Thanks for putting up this quick fix @oandregal! I just pushed a tiny commit to fix some PHP linting complaints, but otherwise this looks good and the priority of `1` matches the order in which callbacks were enqueued in `trunk` prior to the removal in https://github.com/WordPress/wordpress-develop/pull/4356. I suppose it's still technically quite a bit higher priority being set to `1` rather than the first position in default `10`, but I don't see that being an issue, and it sounds like it'd be a quick change to fix it up if it winds up causing problems.

LGTM! ✨

**Comment by andrewserong** [comment]
This PR doesn't appear to cause any issues, gets the e2es passing again, and would be easy to revert if it does cause any problems. Since this will help unblock merging new PRs, I'll merge this in now. Thanks again for putting this PR up @oandregal!

**Comment by oandregal** [comment]
Created https://github.com/WordPress/gutenberg/issues/50246 to track this, so we don't forget to remove it soon. cc @ellatrix

**Comment by ellatrix** [comment]
It seems that the change in core did not only break the order in the iframe, but also the order outside the iframe. One could argue that the test plugin is not properly declaring dependencies, but I tried adding `array( 'test-iframed-inline-styles-editor-style-css' )` to the compat stylesheet, and the dependency resolver is just removing the stylesheet completely.

So I'm now wondering if we should investigate the trunk change and somehow change the ordering back or revert that change.

**Comment by oandregal** [comment]
Follow-up: https://github.com/WordPress/wordpress-develop/pull/4498 is reverting the core change.

**Pull request merged**
