### PR TITLE
FormTokenField: handle disabled in Token; add storybook stories

### PR DESCRIPTION
**Pull request by adekbadek**
## Description

In `FormTokenField` component, the `disabled` prop was not passed to the `Button`, which made the delete button clickable. The click would not be handled, but the DOM element was focusable. This PR fixes that by passing the `disabled` prop to the `Button`.

## How has this been tested?

Locally. Storybook stories were added for the `FormTokenField` component for ease of testing.

## Screenshots 

Focusing on the token when the component is disabled:

image

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by t-hamano** [comment]
I checked the latest trunk and it appears that Storybook has already been added in #25439. However, the problem of the focus outline appearing on the button still seems to exist.

https://user-images.githubusercontent.com/54422211/208431855-7c9c31c1-bd88-474b-9eae-86cd9c71d2e9.mp4

**Comment by mirka** [comment]
@adekbadek Are you still available to resolve the conflict and remove the Storybook bit? If not, let us know and we'll find someone to take over 🙂

**Comment by adekbadek** [comment]
Hi @mirka – I don't have bandwidth to do that currently, if it's possible please take over.

**Comment by chad1008** [comment]
I've just taken a look and with the existing Storybook setup, it does look like all we need is to pass that `disabled` prop. Rebasing and taking over this PR from a fork isn't ideal so I'm spinning up a new one real quick.

**Pull request closed without merging**
