### PR TITLE
Try a block per media type (prototype)

### PR DESCRIPTION
**Pull request by notnownikki**

### CODE REVIEW

**Comment by annaephox** [comment]
Hi @notnownikki - I'm looking through all the things tagged "Needs Design Feedback", and not sure how I can help on this ticket? Is there a specific issue (maybe you have a screenshot). Thanks heaps

**Comment by karmatosed** [comment]
I would +1 any organisation we can do. I really like this in the embed. There seem some merging issues, so I assume a refresh is needed @notnownikki ?

**Comment by aduth** [comment]
Is this still relevant, or should this pull request be closed?

**Comment by notnownikki** [comment]
Let's close. I think we decided that a block per site was better for the user to discover what they could embed.

**Pull request closed without merging**
