### PR TITLE
Backports fixes for 5.8 beta1 (batch 2)

### PR DESCRIPTION
**Pull request by youknowriad**
WP 5.8 beta 1 is due to release today, in this PR, I'll be back porting the last minute fixes.

It includes:

 - Fix inspector opening when clicking outside the widget areas #32450
 - Assume light theme when a transparent background is used #32477
 - Make Post blocks non editable inside Query block #32505
 - Allow themes to add inline styles for all blocks when using lazy styles loading #32275 
 - Rename QueryLoop to PostTemplate block #32514

### CODE REVIEW

**Comment by aristath** [comment]
Can we also add #32275 ?

**Comment by youknowriad** [comment]
@aristath Sure, feel free to start working on its core patch, It seems independent of any JS package.

**Comment by youknowriad** [comment]
There are some php failures here in the widgets API controller (these are errors not on trunk so maybe there's something to be backported to `wp/trunk` for these. cc @noisysocks

**Comment by noisysocks** [comment]
Ah, thanks. Cherry-picking https://github.com/WordPress/gutenberg/pull/32298 into `wp/trunk` ought to do the trick. I'll do that now. It won't require a republish of npm packages since it's entirely PHP changes.

**Pull request merged**
