### PR TITLE
Release: Cherry-pick bug fixes from Gutenberg 6.7 into WordPress 5.3 release

### PR DESCRIPTION
**Pull request by gziolo**
Travis should be green and @youknowriad should review all commits applied.

There were some issues applying https://github.com/WordPress/gutenberg/pull/17696. We need to retest:
- color pallette and `z-index`
- RichText and `z-index` – test by checking that the toolbar of the image caption shows properly

Pinned plugins should be re-tested as well with the DropIt plugin. Check more in https://github.com/WordPress/gutenberg/pull/17752.

### CODE REVIEW

**Comment by gziolo** [comment]
Travis looks really bad. I will investigate.

**Review by youknowriad — APPROVED** [review]

**Comment by gziolo** [comment]
The color palette is broken:

Screen Shot 2019-10-15 at 13 34 09

@jorgefilipecosta - can you help investigate?

**Comment by gziolo** [comment]
It looks like Image block preview should have the image size provided:

Screen Shot 2019-10-15 at 13 36 52

**Comment by youknowriad** [comment]
@gziolo The image preview is a known bug, basically once the image is loaded, next time you hover, it's fixed.

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta - can you help investigate?

I added a commit that fixes the issue, we were removing color pallete styles in a commit but in this branch, the styles are still needed.

**Pull request merged**
