### PR TITLE
Generates excerpt using core get_the_excerpt

### LINKED ISSUE #19418: If a tweet is in excerpt it shows the link url not content
Potentially I would argue this should just output the tweet or skip it as what we have right now can cause issues for example in latest posts:

excerpt-twitter-bug

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Closes #19418 

## How has this been tested?
Tested locally in browser by making some posts with embedded tweets and then another using the latest posts block.

The way to test:
- make a post or more with some tweet embeds and some text.
- mare sure the embed is close to the start of the post.
- make a post and use the latest posts block
- set the block to show excerpt
- there should be no tweet links in the excerpt

## Types of changes
The latest posts block does, I believe, two wrong things about the excerpt:

- in the server side renderer it uses a custom way to get the excerpt which bypasses the core function that among other things renders only allowed blocks, strips shortcodes and a lot more.
- in the client side renderer it gets the rendered excerpt and then wrongfully checks for the raw excerpt, which may be empty if post has no manual excerpt, resetting the rendered excerpt with the raw post content.

This is what this PR fixes.

### CODE REVIEW

**Comment by talldan** [comment]
@draganescu Would you be able to provide some testing instructions, what should I look out for when testing?

**Comment by draganescu** [comment]
hey @talldan thanks for trying this out:

The way to test:
- make a post or more with some tweet embeds and some text.
- mare sure the embed is close to the start of the post.
- make a post and use the latest posts block
- set the block to show excerpt
- there should be no tweet links in the excerpt

Do not use the full content option, that is a different issue I think.

**Comment by draganescu** [comment]
So @talldan the problem you encountered is that in the Latest Posts block there was a fallback which used the full post in case there was an empty excerpt. Now, I am not sure this fallback is the best option.

If I select excerpt, and the excerpt: 

- either shows the excerpt
- or makes one from the post itself

... then there is no reason for the fallback.

The filtering of blocks from content does not apply (and shouldn't) for full post content.

Can you retest? Should be OK now.

**Review by ajitbohra — APPROVED** [review]
Works as expected, code-wise LGTM 👍

**Pull request merged**
