### PR TITLE
Try: Ignore stylelint "selector-class-pattern" rule on mobile SCSS files

### PR DESCRIPTION
**Pull request by rafaelgallani**
## Description

Adds a `stylelint` plugin to ignore the `selector-class-pattern` rule on mobile SCSS files (`.(native|ios|android).scss`).

When editing `.(native|ios|android).scss` files, if your code editor is compatible with `stylelint`, it will warn you to add a [commented line](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/ignore-code.md#within-files) to ignore the `selector-class-pattern` rule, as this rule must not be applied to these files.

The plugin's `fix` option was implemented, so I also ran `npx stylelint "**/*.(native|ios|android).scss" --fix`, which already added the comment to ignore the rule.

## How has this been tested?
`npm run test`.

### Before applying the plugin suggested fix
before_plugin_fix

### After applying the suggested fix
after_plugin_fix

## Types of changes
New feature.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] I've tested my changes with keyboard and screen readers. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
This is a very interesting idea. Nice work with the `stylelint` API 💯 

Yes, it sounds like a good idea to add all those comments that disable the rule in React Native files. I would appreciate a sanity check from the mobile team though, so they could decide how do they like this rule and what do they plan to do moving forward.

If we were to land these changes, I think we should only add code comments and remove the logic used because we don't want to promote disabling this rule and I'm afraid that the auto fixing feature would make it too tempting 😄

**Comment by hypest** [comment]
👋 all!

From a native mobile perspective, it's not clear to me yet whether we should fix the styling error or we should altogether disable the rule like this PR introduces. Is there a ticket that describes the situation? Can someone elaborate here in the PR perhaps? Thanks!

Also, pinging @dcalhoun to have a closer look, thanks!

**Comment by gziolo** [comment]
Yes, there is an issue: https://github.com/WordPress/gutenberg/issues/28616. The rule that enforces BEM convention for class names fails with mobile code as discussed in:

**Comment by dcalhoun** [comment]
@hypest 👍🏻 I'll check it out and report back.

**Comment by dcalhoun** [comment]
Hey @rafaelgalani! 👋🏻 Thanks for taking the time to open this PR to start this discussion.

From researching the history of `stylelint` and React Native in the project, I found a few things of note. Some of which the rest of you may already be aware of, but I figured I'd provide them for context.

* When [`stylelint` was added](https://github.com/WordPress/gutenberg/pull/8647), the `selector-class-pattern` rule was intentionally disabled for the entire project — both web and mobile — to avoid spending time on non-trivial violation fixes at that time.
* I was unable to find any native-specific `scss` files to review or discussions from around the time [`scss` file parsing was added to `gutenberg-mobile`](https://github.com/wordpress-mobile/gutenberg-mobile/commit/01d7317c791dbf544df306a46016f4b188d66df2) to determine why BEM was forgone for native-specific stylesheets.
* Considering using kebab class names with [`react-native-sass-transformer` requires bracket notation](https://github.com/kristerkari/react-native-sass-transformer#how-does-it-work), my best guess is that BEM was forgone to (1) avoid the more verbose bracket notation syntax and (2) some of the value propositions of BEM (e.g. avoiding complexities in class name collisions/cascading styles) are addressed in other ways in React Native.

>From a native mobile perspective, it's not clear to me yet whether we should fix the styling error or we should altogether disable the rule like this PR introduces.

So, to answer the question @hypest posed above, attempting to fix the `selector-class-pattern` violations for the React Native stylesheets is probably not the approach I would propose. I agree with @rafaelgalani's thinking that we should disable/replace this stylelint rule for React Native stylesheets.

The lingering questions I have would be:

1. Are there benefits to aligning React Native stylesheets to BEM that I am overlooking (e.g. a code sharing pattern)?
2. Is adding inline comments to each file the best/only solution for disabling the `selector-class-pattern` rule? From https://github.com/WordPress/gutenberg/pull/28954#issuecomment-778037114, it sounds like it is the only successful approach we have identified so far. Is there additional room to explore alternatives that doesn't require a comment in each file or do we feel we've exhausted the available `stylelint` APIs?
3. Is there a different rule we should apply to React Native class names? I.e. is there a pattern we attempt to follow in React Native stylesheets?

Would love to hear everyone's thoughts. Thanks!

**Comment by hypest** [comment]
Thanks for looking deeper into this @dcalhoun!

I feel like maintaining the inline comments (disabling the check for even new file or similar) would be an ongoing effort with no benefit. Instead, I feel I'd like it if we opt for a code-sharing solution.

In that respect, I wonder if we can come up with a clever approach for adding BEM to the .native.scss files without harming the JS/RN side access too much by relying on bracket notation. For example, what if we explore extending the SCSS transformer to replace the dashes with underscores or something? Trusted, that would actually be a departure from BEM for the (native mobile) JS files but we would at least keep the .scss files cross platform and maintenable. Note: I don't have huge experience on the topic so, take my proposal with a big grain of salt. 😄

**Comment by dcalhoun** [comment]
Apologies for a delayed response. I was occupied with other projects for a few weeks.

From reviewing this further, I identified three code sharing patterns (potentially) used in Gutenberg. I felt understanding how we share (or might share) code is likely the best way to look at this topic.

Gutenberg Code Sharing Patterns

**A. Share Everything:** We share logic between platforms frequently in Gutenberg. However, I have not found an instance where we have a single component _with styles_ shared between web and native.
**B. Share Nothing:** We frequently split entire components for platform-specific implementation for web and native.
**C. Share Styles:** I found one example where a shared stylesheet was _imported by platform-specific stylesheets_ (C1). I did not find an example of JavaScript components _sharing a stylesheet directly_ (C2).

Because of these patterns, I think the potential benefit of applying BEM to both platforms is quite small.

| Option | Pros | Cons |
| --- | --- | --- |
| Adhere  to BEM for native | 1. Consistent naming patterns in stylesheets across web and native. (Relevant to B and C patterns.) <br/><br/>2. Ability to apply a single stylesheet to either platform without one-off adaptation to conflicting naming patterns. (Relevant to C2 pattern.) | Friction in referencing native stylesheet selectors. We would be forced to use [bracket notation](https://github.com/kristerkari/react-native-sass-transformer#how-does-it-work) or reference selectors renamed by SCSS transformer (i.e. `.my-element__child--modified` in stylesheet would be `myElementChildModified` or `my_element__child__modified` in JavaScript). |
| Disable BEM linting for native | Remove need to adhere to BEM, which provides little value to native. | Lack of alignment with web project. |

Personally, I question if applying BEM to native stylesheets is all that valuable for this project based on the pros and cons list above. However, if we do decide to it is worth the effort, I would choose using bracket notation over transforming selector names using a SCSS transformer. I believe the latter would cause a lot of confusion. The challenge with bracket notation is it will require a lot of manual work to change all the existing native selectors.

Ultimately, if we decide to have native stylesheets adhere to BEM, I think that would likely be a big enough change to seek out approval from several team members on the native side first. @hypest would you agree?

One important note is that I was able to identify an alternative to inline comments for disabling BEM linting for native stylesheets. I believe this is likely the best path forward. IMO the approach in #29881 is more straightforward and will create less noise for native developers. @rafaelgalani will you please review #29881 and provide your thoughts? Thanks!

**Comment by hypest** [comment]
> Personally, I question if applying BEM to native stylesheets is all that valuable for this project based on the pros and cons list above.

Anecdotal but my gut tells me that it would be best to stay as close as possible to the web format, anticipating more overlap and cross-platform-ness down the road. Like, avoiding duplication effort if we just need to copy over styles to native. And looks like [you have a solution brewing](https://github.com/WordPress/gutenberg/pull/29881) that can help minimize the effort vanilla BEM would incur to the native development.

> However, if we do decide to it is worth the effort, I would choose using bracket notation over transforming selector names using a SCSS transformer. I believe the latter would cause a lot of confusion. The challenge with bracket notation is it will require a lot of manual work to change all the existing native selectors.

and

> Ultimately, if we decide to have native stylesheets adhere to BEM, I think that would likely be a big enough change to seek out approval from several team members on the native side first. @hypest would you agree?

Perhaps we can leave that up to actual usage to judge. Like, we could have both in place and we can check afterwards which one works best for the native dev flow. Can we have both the transformed names and the bracket notation in place in parallel? wdyt @dcalhoun ?

**Comment by dcalhoun** [comment]
> Anecdotal but my gut tells me that it would be best to stay as close as possible to the web format, anticipating more overlap and cross-platform-ness down the road. 

@hypest understandable. As much alignment as possible make total sense when cross-platform code sharing is a goal. It just feels a bit odd to apply "best practices" to a platform that doesn't benefit from the practice itself. I.e. BEM's modularity and reusability are addressed by React Native in a different manner. That said, there is still benefit gained from BEM in regards to consistency from its structure.

> And looks like [you have a solution brewing](https://github.com/WordPress/gutenberg/pull/29881) that can help minimize the effort vanilla BEM would incur to the native development.

My intention with #29881 was to unblock #28954 without disrupting native developers. Merging that work would mean the linter would _never_ throw errors for BEM violations in native stylesheets.

It seems like the question is no longer "should we adhere to BEM?" but "what approach should use to adhere to BEM?" If we definitively want native stylesheets to adhere to BEM, merging this PR (#28988) likely makes more sense as it would force native developers to make a conscious decision when they create a new stylesheet: do I adhere to BEM or add a stylelint comment do disable the linter?

> Perhaps we can leave that up to actual usage to judge. Like, we could have both in place and we can check afterwards which one works best for the native dev flow.

Fair. Exploring BEM in actual practice would yield the best insight. I support that exploration.

> Can we have both the transformed names and the bracket notation in place in parallel?

Probably. No work is/merges are necessary to explore bracket notation today. In order to explore transformed names there is additional task of update the [Sass transformer](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/sass-transformer.js). We would likely need a way of flagging a native stylesheet to have its selectors transformed (e.g. a special comment atop the file).

## Moving Forward

It _seems_ like there is a consensus to have native stylesheets eventually adhere to BEM to match web. The open question is how do we accomplish it? With that, these are the tasks I see.

- Have we definitely decided to adhere to BEM for native stylesheets?
  - No => move to merge #29881.
  - Yes: Do we want linter feedback while exploring BEM for native stylesheets?
    - No => move to merge #29881.
    - Yes => move to merge #28988.
- Update [Sass transformer](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/sass-transformer.js) to transform BEM selectors within flagged native stylesheets to avoid dashes.
- Begin adhering to BEM selectors in native stylesheets. Reference the selectors in JS via bracket notation or transformed name to understand which approach is better.

@hypest am I interpreting the state of things correctly? Would you like me to create an issue for the Sass transformer and begin exploring that?

**Comment by hypest** [comment]
> It just feels a bit odd to apply "best practices" to a platform that doesn't benefit from the practice itself. I.e. BEM's modularity and reusability are addressed by React Native in a different manner.

Fair point @dcalhoun !
Unless I'm understanding something different though, what we have in gutenberg-mobile is already in "fringe territory" since React Native doesn't actually support SASS natively. It's us that we've glued those together so we could reuse style definitions from the web directly. In that sense, adhering to BEM feels more natural as that's what the web side adheres to, making reusing web styles more maintainable to me.

As far as deciding to go withe BEM, I'm +1 for BEM in native SASS stylesheets but please don't take this as veto-level, happy to be outvoted.

In terms of what to do next:
* We should refactor the native SASS stylesheets to conform to BEM
* We would need to either refactor the JS code to use bracket notation (since the styles won't be available as camelCase as currently), or
* we'll need to land a transformer to transform from BEM to [say, camelCase](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/audio/style.native.scss#L1) so the native JS code stays as is.
* We'll need time for all of the above so, I feel we should go ahead with https://github.com/WordPress/gutenberg/pull/29881 that will buy us time without having to modify native styles/code for now.

Does that make sense actually?

**Comment by dcalhoun** [comment]
> Unless I'm understanding something different though, what we have in gutenberg-mobile is already in "fringe territory" since React Native doesn't actually support SASS natively. It's us that we've glued those together so we could reuse style definitions from the web directly. In that sense, adhering to BEM feels more natural as that's what the web side adheres to, making reusing web styles more maintainable to me.

@hypest agreed. I think we should move forward to identify the best approach to have the native stylesheets adhere to BEM.

> * We'll need time for all of the above so, I feel we should go ahead with #29881 that will buy us time without having to modify native styles/code for now.

Makes sense to me. #29881 is now merged, so I will close this PR. If anyone disagrees, please feel free to reopen it.
 
> In terms of what to do next:
> 
> * We should refactor the native SASS stylesheets to conform to BEM
> * We would need to either refactor the JS code to use bracket notation (since the styles won't be available as camelCase as currently), or
> * we'll need to land a transformer to transform from BEM to [say, camelCase](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/audio/style.native.scss#L1) so the native JS code stays as is.
>
> [...]
>
> Does that make sense actually?

Yes. I will seek out the best approach for capturing and completing this work. Thanks!

**Pull request closed without merging**
