### PR TITLE
Fix rounded corners in block icons

### PR DESCRIPTION
**Pull request by kjellr**
Currently, a number of block icons have clipped corners, likely due to an over-zealous SVG compression script. This PR restores rounded corners for the following block icons: 

- Gallery
- File
- Video
- Table
- Button
- Archives
- Latest Comments
- Audio Embed (Used for SoundCloud, MixCloud, and ReverbNation)

**Screenshot**

artboard copy

### CODE REVIEW

**Review by melchoyce — CHANGES_REQUESTED** [review]
Looks good 👍 

Still seeing a bit of clippage on columns: 
image

Less ridiculous image:
image

It looks like it's clipped by 1-2px

**Comment by jasmussen** [comment]
Thanks so much for this, Kjell!

**Comment by kjellr** [comment]
Good catch, @melchoyce. 682e269 should take care of that one. 

_Before (left), After (right)_

screen shot 2019-02-05 at 8 36 35 am

**Comment by gziolo** [comment]
@kjellr - feel free to land as soon as you get ✅ from one of designers. There is nothing to review code wise :)

**Comment by jasmussen** [comment]
👍

**Comment by kjellr** [comment]
This should be good to go, but could use just one more check since I brought it up to date with `master`. @melchoyce or @jasmussen, would you mind giving this one more quick look? 

Thanks!

**Comment by Soean** [comment]
@kjellr The Video and the Gallery block have snapshot tests, which include the old SVG, they also need to be updated.

**Comment by gziolo** [comment]
npm run test-unit — -u
should do the trick then

See also https://wordpress.org/gutenberg/handbook/contributors/develop/testing-overview/#tldr-broken-snapshots

**Comment by Soean** [comment]
Thanke @gziolo 
I refreshed the tests with:
`npm run test-unit -- --updateSnapshot --testPathPattern packages/block-library/src/video/test`
`npm run test-unit -- --updateSnapshot --testPathPattern packages/block-library/src/gallery/test`

**Review by gziolo — APPROVED** [review]
Tests pass now 👍

**Comment by jasmussen** [comment]
> This should be good to go, but could use just one more check since I brought it up to date with `master`. @melchoyce or @jasmussen, would you mind giving this one more quick look?

Yep! This looks good. Ship it! 👍 👍

**Comment by kjellr** [comment]
Thank you, everyone!

**Pull request merged**
