### PR TITLE
Patterns: Display all custom template part areas in sidebar nav

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related:
- https://github.com/WordPress/gutenberg/pull/52354

## What?

- Renames Uncategorized template part area in Patterns sidebar nav to General
- Displays all custom template part areas within the Patterns sidebar nav

**Note: We might opt for only a simple renaming of the existing Uncategorized category to General for 6.3 (https://github.com/WordPress/gutenberg/pull/52354) and explore this more fully in 6.4**

## Why?

This is a more accurate categorization of template parts and will then reflect the create template part modal 1:1.

## How?

- Updates the hook to retrieve the template part areas and their counts to handle custom registered areas
- Updates the hook used to display template parts in a category/area to match

## Testing Instructions

1. You'll need to register some custom template part areas, you can do this via the snippet below
2. Navigate to Site Editor > Patterns
3. Initially, you won't see the custom areas unless they have a template part already assigned to them. Create template parts for each of your custom areas
4. Confirm these custom areas now show in the sidebar navigation
5. Navigate to these custom areas and the General area to ensure the correct patterns are shown

```php
<?php

function my_default_wp_template_part_areas( $default_area_definitions ) {
	return array_merge(
		$default_area_definitions,
		array(
			array(
				'area'        => 'my-area',
				'label'       => 'My Area',
				'icon'        => 'layout',
				'description' => 'A custom template part area',
			),
			array(
				'area'        => 'custom-area',
				'label'       => 'Custom Area',
				'icon'        => 'layout',
				'description' => 'Another custom template part area',
			),
		)
	);
}
add_filter( 'default_wp_template_part_areas', 'my_default_wp_template_part_areas' );

```

## Screenshots or screencast 
Screenshot 2023-07-06 at 1 03 37 pm

### CODE REVIEW

**Comment by carolinan** [comment]
I would just like one confirmation, are these default categories Header, Footer and General still translatable? I am asking because I saw the translation functions being removed in the PR, and when I turn on the Swedish language, the strings are not translated, though the translations are in the language files for 6.3.

In [wp-includes/block-template-utils.php.](https://github.com/WordPress/WordPress/blob/master/wp-includes/block-template-utils.php#L64)

For the custom categories/ areas, I would expect the developer to need to add the translation functions when registering them, and in my case, also add the translation to the mo/po files: so I did not test that :)

**Review by jameskoster — APPROVED** [review]
I don't suppose custom template part areas are all that common, but given it's possible this seems like the correct approach compared to https://github.com/WordPress/gutenberg/pull/52354.

It's working for me so I'll approve from the design side.

**Comment by aaronrobertshaw** [comment]
> I would just like one confirmation, are these default categories Header, Footer and General still translatable?

Good question @carolinan 👍 

My understanding was they were translated. I followed the template part areas [added to the editor settings](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/site-editor.php#L59) for the Site Editor in core through to [`get_allowed_block_template_part_areas`](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/block-template-utils.php#L64-L93) where I saw they were via `_x()`.

I tested this by switching my dev site to Spanish and confirming the default areas were in fact translated. I've done that again and captured the screenshot below.

Screenshot 2023-07-06 at 8 29 42 pm

Testing further using German and I see only General is translated for that language. Of course, the "My patterns" category is brand new so hasn't been translated at all yet.

Screenshot 2023-07-06 at 8 33 19 pm

> For the custom categories/ areas, I would expect the developer to need to add the translation functions when registering them, and in my case, also add the translation to the mo/po files: so I did not test that :)

Correct. Custom areas would require the developer to wrap the labels in the appropriate translation function. I didn't do this in the example snippet for testing though, sorry.

Is there something else I'm missing?

**Comment by carolinan** [comment]
When I test on 6.2.2 not 6.3 beta, the text is translated. Let's consider that answered 👍

**Review by kevin940726 — APPROVED** [review]
Code LGTM 👍

**Review by glendaviesnz — APPROVED** [review]
Tested well for me:

✅  Custom areas showed in sidebar once template part assigned to them.
✅  Correct templates showed when navigating to the the different areas

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-pre-beta-4 branch to get it included in the next release: 9a99dd0cb3

**Pull request merged**
