### PR TITLE
Added unit test for Tag Cloud Block render function

### PR DESCRIPTION
**Pull request by akasunil**
## What?

Added unit test for `Tag Cloud` block render function.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I don't think this is necessary.

## Why?
* The render function is simple wrapper around [`wp_tag_cloud`](https://developer.wordpress.org/reference/functions/wp_tag_cloud/).
* Not every render function needs unit tests. In my opinion, if the block just passes arguments to a core function and echoes it, unit test coverage isn't needed.

**Comment by akasunil** [comment]
@Mamaduka Sorry, i didn't see your comment before last commit

**Comment by akasunil** [comment]
> * Not every render function needs unit tests. In my opinion, if the block just passes arguments to a core function and echoes it, unit test coverage isn't needed.

I see, in that case I'll close this PR then.

**Comment by Mamaduka** [comment]
Thanks for the effort, @akasunil!

**Pull request closed without merging**
