### PR TITLE
Increase tap-target of primary action on unsupported blocks

### PR DESCRIPTION
**Pull request by marecar3**
## Description
Based on the issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2567#
this PR introduces an increase of tap-target of primary action on unsupported blocks

`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2608

## How has this been tested?
1. Open Gutenberg mobile editor
2. Add unsupported block
3. Try to click on unsupported block surface
4. The options sheet should be presented

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by etoledom — COMMENTED** [review]
Thank you for this PR @marecar3 !

Code looks perfect. Nice job! ✨ 

About the behaviour, I think we are missing something. From the original ticket, @iamthomasbishop mentions this:

> With this change, I think we will want to change the logic so that you first have to select the block before the tap target becomes "active", which follows some other similar blocks like the Latest Posts block, and most importantly, the select-first interaction gives the user the other block controls such as movers and the overflow (•••) menu.

What I see on the tests, is that pressing over the target area will open the bottom sheet directly, even if the block is not selected. What we would want instead is:

- When the block is not selected, pressing in the target area (or anywhere over the block) Will select the block.
- When the block is already selected, pressing in the target area will open the Bottom Sheet.

**Comment by marecar3** [comment]
> Thank you for this PR @marecar3 !
> 
> Code looks perfect. Nice job! ✨
> 
> About the behaviour, I think we are missing something. From the original ticket, @iamthomasbishop mentions this:
> 
> > With this change, I think we will want to change the logic so that you first have to select the block before the tap target becomes "active", which follows some other similar blocks like the Latest Posts block, and most importantly, the select-first interaction gives the user the other block controls such as movers and the overflow (•••) menu.
> 
> What I see on the tests, is that pressing over the target area will open the bottom sheet directly, even if the block is not selected. What we would want instead is:
> 
> * When the block is not selected, pressing in the target area (or anywhere over the block) Will select the block.
> * When the block is already selected, pressing in the target area will open the Bottom Sheet.

Ok, it's clear. Thanks for bringing this up. I will fix it.

**Comment by marecar3** [comment]
Hey @etoledom 👋 
Could you do another round of testing? thanks.

cc @guarani if you want to also give a try.

**Review by etoledom — APPROVED** [review]
Thank you for the update @marecar3 . Working great now! 🎉

**Comment by marecar3** [comment]
> Thank you for the update @marecar3 . Working great now! 🎉

Thanks for review!

**Pull request merged**
