### PR TITLE
Card: Enhance CardHeader and CardFooter with Flex

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screen Shot 2020-06-04 at 2 04 53 PM

(Screenshot of CardHeader with content + `<Button />` aligned)

This update enhances the CardHeader and CardFooter sub-components of Card with the new layout-based Flex component. This improves the alignment of child content for common header/footer use-cases.

The various Card `README.md` files were updated to reflect the changes.

Lastly, a new `space()` style utility was added to help generate `px` values that follow the [`8px` grid system](https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_variables.scss#L27)

https://make.wordpress.org/design/2019/10/31/proposal-a-consistent-spacing-system-for-wordpress/

This update was originally inspired from https://github.com/WordPress/gutenberg/pull/22827#pullrequestreview-424631581

cc'ing @adamziel for sanity check!

## How has this been tested?

Tested locally on Storybook.

* `npm run storybook:dev`
* Search for `cardheader`
* View the `Alignment` example

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by adamziel** [comment]
@ItsJonQ I tested and indeed it works perfectly. My only concern is that this would break at least some existing uses of the `CardHeader` and `CardFooter` components (either in this repo or out in the wild). What do you think?

**Comment by ItsJonQ** [comment]
@adamziel Thank you for testing! 🙏 

> My only concern is that this would break at least some places where CardHeader and CardFooter components are currently use (either in this repo or out in the wild). What do you think?

I feel like it should be okay. Although of course, I cannot confirm 100%.
From what I can tell, we currently only use `<Card />` within `packages/edit-navigation/src/components/menus-editor/`. I believe some folks at WooCommerce may be using `<Card />`

cc'ing @nerrad + @jameskoster to double check 😊

**Review by adamziel — APPROVED** [review]

**Comment by jameskoster** [comment]
@psealock @jeffstieler @mattsherman y'all have been using this component in the Woo Home Screen work I believe.

**Comment by ItsJonQ** [comment]
@psealock @jeffstieler @mattsherman

👋 Hallo!! Just a quick follow up 😊 

Thanks!

**Comment by psealock** [comment]
>I believe some folks at WooCommerce may be using <Card />

We are, but I don't think that should be a blocker to progress. Thanks for the heads up.

**Comment by ItsJonQ** [comment]
@psealock Awesome! I'll merge it up

**Pull request merged**
