### PR TITLE
Tools: Removes IDE specific configuration for VS Code

### PR DESCRIPTION
**Pull request by creativecoder**
## Description

Removes the `launch.json` debugging configuration specific to VS Code.

I use VS Code, and find it cumbersome to have this configuration in version control: any customizations I add must be stashed and reapplied before and after fetching updates from origin.

Generally, I think we should keep IDE specific configuration out of version control, but document examples. The configuration for Xdebug that's being removed is [already documented in `@wordpress/env`](https://github.com/WordPress/gutenberg/blob/b9232527214cd3d523badc4a66b529b7efe615ca/packages/env/README.md#xdebug-ide-support), so can be referenced there by anyone who needs it.

## How has this been tested?

n/a

## Types of changes

Remove IDE specific configuration

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by david-szabo97** [comment]
Interesting. VS Code is widely used and I bet most of the Gutenberg contributors are using VS Code. In my opinion, it makes sense to provide some built-in IDE specific configurations. Better developer experience.

After all, I've never used this launch task, so I have no strong opinions here.

**Comment by creativecoder** [comment]
> In my opinion, it makes sense to provide some built-in IDE specific configurations. Better developer experience.

I see that initially, but the issue for me is what happens when I want to customize the configuration. Because it modifies a file that's tracked in version control, I have to either propose that configuration for everyone, maintain my own fork with the change, or frequently stash and reapply the changes. I've not convinced my changes should be committed for everyone, and the last 2 are not such a good developer experience 🙂

For example, I have these two configurations I currently keep in a stash:

```
		{
			"name": "Xdebug with Valet",
			"type": "php",
			"request": "launch",
			"port": 9003,
			"pathMappings": {
				"{path to project}/web/wp-content/plugins/gutenberg": "${workspaceRoot}/"
			}
		},
		{
			"name": "Debug jest tests",
			"type": "node",
			"request": "attach",
			"port": 9229
		}
```

**Comment by creativecoder** [comment]
Alternatively, we could rename `.vscode/launch.json` to `.vscode/launch-example.json`, so it's still present, but doesn't mandate what launch configuration you use.

**Comment by david-szabo97** [comment]
> I see that initially, but the issue for me is what happens when I want to customize the configuration. Because it modifies a file that's tracked in version control, I have to either propose that configuration for everyone, maintain my own fork with the change, or frequently stash and reapply the changes. I've not convinced my changes should be committed for everyone, and the last 2 are not such a good developer experience 🙂

I never thought about that! Totally makes sense.

> Alternatively, we could rename .vscode/launch.json to .vscode/launch-example.json, so it's still present, but doesn't mandate what launch configuration you use.

This sounds like a good alternative. Easier to rename the file than copy-pasting it from the documentation.

**Comment by creativecoder** [comment]
I've updated this PR to move `launch.json` to `launch-example.json`

**Review by gziolo — APPROVED** [review]
Sounds good 👍🏻  I knew that there is a good reason why they don't keep any IDE/editor specific files (even don't list them as part of ignore list) in WordPress core.

**Review by david-szabo97 — APPROVED** [review]
Renaming the file is much better! Thanks! 🚢 🚢

**Pull request merged**
