### PR TITLE
InputControl: Add padding wrapper for prefix/suffix

### PR DESCRIPTION
**Pull request by mirka**
Follow-up to #42166

## What?

Adds a convenience wrapper component `InputControlPrefix`/`InputControlSuffix` that can be used by a consumer to add standard padding that matches the size variant.

### Wrapped prefix when InputControl is at default size

```jsx
<InputControl
  label="Value"
  placeholder="Placeholder"
  prefix={<InputControlPrefix>@</InputControlPrefix>}
  size="default"
/>
```

Wrapped prefix when InputControl is at default size

### Wrapped prefix when InputControl is at large size

```jsx
<InputControl
  label="Value"
  placeholder="Placeholder"
  prefix={<InputControlPrefix>@</InputControlPrefix>}
  size="__unstable-large"
/>
```

Wrapped prefix when InputControl is at large size

(The padding between the prefix and the placeholder here is too wide — this will be addressed in #42166)

## Why?

Currently, whenever a consumer wants to add padding before their `prefix` element, they need to add it themselves. This is not sustainable because they need to know the padding value of the underlying `InputControl`, and that value also changes depending on the size variant.

Here are the alternative approaches I considered, but decided against:

1. Adding the padding by default, and providing a convenience wrapper that breaks out of that padding. This is similar to the `<CardMedia>` approach taken in the [Card component](https://wordpress.github.io/gutenberg/?path=/docs/components-card--default), and the [approach considered](https://github.com/WordPress/gutenberg/pull/41937#discussion_r914804341) for `Dropdown`. Although it would be nice to have a similar construct for `InputControl`, the current implementation is already no padding by default. Also, it's arguably more natural in this case for the wrapper to _add_ padding instead of break out of it, since we're only dealing with one side of the box. (A padding breakout wrapper deals with all four sides of the box.)
2. Checking if the `prefix` is a function, and if it is, call it with a `{ paddingInlineStart }` argument so the consumer can use that value to style their own margin. This seems simple on the surface, but it's just more work for the consumer, and forces them to use an inline style or a CSS-in-JS solution. Also, I think the general direction we're headed toward for these solutions is to use subcomponents like `CardMedia`.

## How?

Provide a thin wrapper component that applies responsive padding through the Context System. This can be used with any InputControl-based component that inherits the `prefix`/`suffix` props.

## Testing Instructions

1. `npm run storybook:dev`
2. Check out the prefix/suffix stories for `InputControl`.

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
I'm not sure if naming props like exact CSS properties (i.e. `paddingLeft` and `paddingRight`) is a good idea — I usually prefer prop names that hide the implementation details.

Also, I'm not sure if there's a point in allowing consumers of the component to define a custom padding; I can imagine that 99.9% of the time, the requirements are either to have the default spacing, or to have no spacing at all.

With this in mind, I propose an alternative approach:

- the `InputControlPrefix` and `InputControlSuffix` have a `hasSpacing` boolean prop (an alternative name could be `hasInlineEndSpacing` for the prefix and `hasInlineStartSpacing` for the suffix)
- prop's default value TBD
- when the prop is `false`, no padding is added
- when the prop is `true`, the padding corresponding to the `InputControl`'s size is added (via internal styles)

WDYT?

**Comment by mirka** [comment]
> I propose an alternative approach

That makes sense. However, when I tried to implement it, I [realized](https://github.com/WordPress/gutenberg/commit/b887ff166599620435d3c7bfa7192bba34d34683) that we can't accomplish what we want here using the Context System if we don't expose the `paddingLeft` prop as well 🙁 

But that prompted me to think of an alternative, simpler way, which is to remove `paddingLeft` from the explicit types, and not define any additional props 8842de0. This has the same effect of:

- not exposing implementation details
- not encouraging consumers to override the padding (although you can technically pass through any `Spacer` prop, it isn't documented and TS will throw an error)
- only adding the standard padding in a boolean way (use the component if you want padding, don't use it if you don't)

Sound good?

**Comment by ciampo** [comment]
> That makes sense. However, when I tried to implement it, I [realized](https://github.com/WordPress/gutenberg/commit/b887ff166599620435d3c7bfa7192bba34d34683) that we can't accomplish what we want here using the Context System if we don't expose the paddingLeft prop as well 🙁

An alternative way to the context system, maybe could have been to:
- use `View` instead of `Spacer`
- wrap `View` in a Emotion's `styled` component
- use that component as a selector to apply the padding styles directly in emotion, rather than via context system

Out of curiosity, do you think that would work?


> But that prompted me to think of an alternative, simpler way, which is to remove paddingLeft from the explicit types, and not define any additional props https://github.com/WordPress/gutenberg/commit/8842de0da236d13a27d26e8a79c0907325d9d7a2. This has the same effect of:
>
> - not exposing implementation details
> - not encouraging consumers to override the padding (although you can technically pass through any Spacer prop, it isn't documented and TS will throw an error)
> - only adding the standard padding in a boolean way (use the component if you want padding, don't use it if you don't)
>
> Sound good?

Sounds like a good solution, yes. Maybe we should call the components `InputControlPrefixWrapper` and `InputControlSuffixWrapper`, in order to make it clear what their role is?

**Comment by mirka** [comment]
> An alternative way to the context system, maybe could have been to:
> 
> * use `View` instead of `Spacer`
> * wrap `View` in a Emotion's `styled` component
> * use that component as a selector to apply the padding styles directly in emotion, rather than via context system
> 
> Out of curiosity, do you think that would work?

Without the context system, we'd need the consumer to explicitly pass a `size` prop to the wrapper component. Which is not necessarily a blocker, but not ideal either.

> Maybe we should call the components `InputControlPrefixWrapper` and `InputControlSuffixWrapper`, in order to make it clear what their role is?

Makes sense. Done in c697074 👍

**Comment by ciampo** [comment]
Tests well in Storybook, although I noticed that we're using `paddingLeft` and `paddingRight`, while in the recent changes in #42166 we used `paddingInlineStart` and `paddingInlineEnd`:

Screenshot 2022-07-20 at 10 36 58

Should we use logic CSS properties in this PR too?

**Comment by mirka** [comment]
> Should we use logic CSS properties in this PR too?

This PR uses the `Spacer` component which doesn't have logical props and does it's own RTL handling. But in general I think new code should use logical properties if that can avoid making an `rtl()` call.

**Review by ciampo — APPROVED** [review]

**Pull request merged**
