### PR TITLE
Remove empty space before `Discard unsaved changes` string

### PR DESCRIPTION
**Pull request by Rahmon**
## What?

While I was translating WordPress 6.3, I noticed that there is an empty space before the `Discard unsaved changes` string. This PR removes this empty space.

image

### CODE REVIEW

**Comment by swissspidy** [comment]
Weird that the `@wordpress/i18n-no-flanking-whitespace` ESLint rule is not catching this 🤔

**Comment by jorgefilipecosta** [comment]
I agree it is strange that the lint rule did not catch this. But I guess the PR could be merged. @Rahmon would you be able to rebase this PR so that we can merge it? Thank you in advance.

**Comment by Rahmon** [comment]
Hi @jorgefilipecosta 

I've updated the PR but I think this PR is not necessary anymore since the string `Discard unsaved changes` was removed in the commit [3ec5015](https://github.com/WordPress/gutenberg/commit/3ec5015e7911507e59f96dfeeb3d8e47127be829).

**Comment by jorgefilipecosta** [comment]
> Hi @jorgefilipecosta
> 
> I've updated the PR but I think this PR is not necessary anymore since the string `Discard unsaved changes` was removed in the commit [3ec5015](https://github.com/WordPress/gutenberg/commit/3ec5015e7911507e59f96dfeeb3d8e47127be829).

Yes, it seems the Pr now has no changes, I'm going to close it.

**Pull request closed without merging**
