### PR TITLE
[RNMobile] Refactor UIManager native module mock

### LINKED ISSUE #29653: Mobile App: Issues reported in the development environment
## Description 

I run the command:

```bash
npm run native start:reset
```

I saw the following issues reported:

```
Setting RN platform to: default (android)
● Validation Warning:

  Unknown option "haste.providesModuleNodeModules" with value ["react-native", "react-native-svg"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

● Validation Warning:

  Unknown option "haste.providesModuleNodeModules" with value ["react-native", "react-native-svg"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html
```

```
> @wordpress/react-native-editor@1.47.0 clean:watchman /Users/gziolo/Projects/gutenberg/packages/react-native-editor
> command -v watchman >/dev/null 2>&1 && watchman watch-del-all; true

dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/watchman/4.9.0_2/libexec/bin/watchman
  Reason: image not found
sh: line 1: 96132 Abort trap: 6           watchman watch-del-all
```
## Device information
- Operating system: macOS Big Sur 11.2.2

### PR DESCRIPTION
**Pull request by dcalhoun**
## Description
Further exploration of #29375.

* Refactor react-native module mock
* Refactor to avoid inconsistent import pattern
* Remove deprecated Jest config 

## How has this been tested?
None of the current unit tests are calling the focus or blur on native components so for testing this, an extra modification is required.

The following steps will force the `RichText` component of the `Verse`  block to be selected, this will make the `RichText` component to call the focus function on the `AztecView` native component when it's mounted:
1. Add `isSelected` prop to `RichText` component in [`verse/edit.js`](https://github.com/WordPress/gutenberg/blob/8ff4df3518a357f8c61589f5a4d30dcb828c4083/packages/block-library/src/verse/edit.js#L54).
2. Run `npm run native test verse`.

## Screenshots
n/a

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by fluiddot** [comment]
The following comments are related to the different commits of this PR:

https://github.com/WordPress/gutenberg/pull/29390/commits/f3b8aee055e90704bc726ebcb1d901331be0adf9
>We currently reference TextStateInput (a private module) within
react-native-aztec/src/AztecView. Doing so requires that we mock it via
its internal path to avoid "TypeError: Cannot read property 'Commands'
of undefined." The private module referenced could possibly be replaced
with a React ref instead. We could then remove this internal mock.

I agree. By the way, I found out that the required function `blurTextInput` and `focusTextInput` can be also accessed from `TextInput` component through the static reference `State`:
- `TextInput.State.blurTextInput`
- `TextInput.State.focusTextInput`

So initially we could remove the `react-native/Libraries/Components/TextInput/TextInputState` mock if we access them from that property and mock `TextInput` instead.

I tried this option but I found complex to mock `TextInput` as it's explained in this [article](https://git.io/JtNmU). The main problem I faced is how to mock the `TextInput` functional component to prevent other unit tests to break while only mocking the functions from `TextInputState` in the `State` property. For now I think it's easier to mock it as you did unless we figure out a way to address this problem.

Additionally, in the current used version of `react-native` types, these function are deprecated so it would be better to replace it with a React ref instead as you commented. However I saw that the deprecation was removed months ago in this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46926/files) although it was published with version `0.63.9` so maybe they were deprecated until that version 🤷‍♂️ .

https://github.com/WordPress/gutenberg/pull/29390/commits/3f411ef2f3d4adbc7efa8b669e4c4c3789b66c68
>This mock appears to be unnecessary for our current test suite. It also
leveraged an internal module path, which is brittle. It would break if
React Native decided to alter its path.

Yeah, it looks like unnecessary but as per the [React navigation documentation](https://reactnavigation.org/docs/testing/#mocking-native-modules) related to mocking native modules, they include that mock to silence a warning. I didn't see the mentioned warning but maybe it's because we don't have any test that runs animations. We could remove it but keeping in mind that in the future we might revert this change if we spot the warning.

https://github.com/WordPress/gutenberg/pull/29390/commits/a68bb961d361a978a4bc9ccbd1623eed3497aa1a
>Generally, named exports are used when importing React Native modules.
This changes the one exception in our source were we imported a default
import of `ReactNative`.
>Importing this default also caused issues when attempting to mock
`react-native` for Jest. This change will make future mocking in Jest
easier.

Totally agree!

https://github.com/WordPress/gutenberg/pull/29390/commits/fc9ca5c742fc5de4d935f8d8df3c803aa5071fea
> The `providesModuleNodeModules` option was removed from Jest. Including
it in the Jest configuration displayed a warning on each run.

Good catch! Let's remove it.

**Comment by dcalhoun** [comment]
> I tried this option but I found complex to mock `TextInput` as it's explained in this [article](https://git.io/JtNmU). The main problem I faced is how to mock the `TextInput` functional component to prevent other unit tests to break while only mocking the functions from `TextInputState` in the `State` property. For now I think it's easier to mock it as you did unless we figure out a way to address this problem.
> 
> Additionally, in the current used version of `react-native` types, these function are deprecated so it would be better to replace it with a React ref instead as you commented. However I saw that the deprecation was removed months ago in this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46926/files) although it was published with version `0.63.9` so maybe they were deprecated until that version 🤷‍♂️ .

@fluiddot agreed, we can likely postpone making these changes if you'd rather not attempt to figure them out now.
 
> Yeah, it looks like unnecessary but as per the [React navigation documentation](https://reactnavigation.org/docs/testing/#mocking-native-modules) related to mocking native modules, they include that mock to silence a warning. I didn't see the mentioned warning but maybe it's because we don't have any test that runs animations. We could remove it but keeping in mind that in the future we might revert this change if we spot the warning.

Ah, good find. I think leaving the mock in place likely makes more sense. Let's just add an inline comment explaining why it's there and potentially include a URL to the relevant documentation. What do you think?

Feel free to make whatever changes you would like to this branch/PR or cherry-pick anything onto your own branch. Let me know if you need any help.

**Comment by gziolo** [comment]
I hear this PR will resolve warnings reported in #29653. Can you link this issue in the description so it gets closed when this PR gets merged? 😄

**Comment by dcalhoun** [comment]
@fluiddot I finished the work in this PR based upon our last conversation. Will you please review again? If you believe this work is ready, we can merge this into `trunk` and close #29375. Thanks!

**Comment by fluiddot** [comment]
> @fluiddot I finished the work in this PR based upon our last conversation. Will you please review again? If you believe this work is ready, we can merge this into `trunk` and close #29375. Thanks!

Sure! I'll review it today and if it's ready I'll merge it into `trunk` 🎊 .

Thank you very much for finish the work on this PR, I had it in my TODO list but I couldn't tackle it sooner 🙇 .

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

I tested the following:
- Run verse unit test (`npm run native test verse`) with `isSelected` prop in `RichText`, the test passed 🟢 
- Run all unit tests (`npm run native test`), the tests passed 🟢 
- Verify that the `blur` and `focus` behaviours work as expected, tested on iPhone 8 simulator and Pixel 4 emulator 🟢

**Pull request merged**
