### PR TITLE
Scripts: Use fork of `rtlcss-webpack-plugin` to fix issues with deps

### LINKED ISSUE #62007: [@wordpress/scripts][rtlcss-webpack-plugin] Some internal modules are deprecated.
### Description

npm warn deprecated core-js@2.6.12:
core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

### Step-by-step reproduction instructions

1. After deleting the folder 'node_modules' and file 'package-lock.json', run 'ncu', 'ncu -u' and 'npm install -force' in turn.
2. Run 'npm ls <module names>' for each of the module names listed in the warn warning presented by npm.

### Screenshots, screen recording, code snippet

Pasted Graphic

## System:
 - OS: macOS 14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 24.13 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.2.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.0 - ~/.nodebrew/current/bin/npm

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### LINKED ISSUE #67866: wp-scripts: Build fails when using pnpm with hoisting disabled.
### Description

While reproducing #67864, I noticed that if I don't install `@bable/runtime` as a dependency, I see an error when using pnpm with hoisting disabled.

`Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'`

The fix the probably to have `@bable/runtime` as a dependency for the scripts package.

<details>
<summary> ⚠  Click to expand the full error reported ⚠ </summary>
<code>
> wp-scripts build

[webpack-cli] Failed to load '/node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js' config
[webpack-cli] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js
- /node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/webpack-cli.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/bootstrap.js
- /node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/bin/cli.js
- /node_modules/.pnpm/webpack@5.97.1_webpack-cli@5.1.4/node_modules/webpack/bin/webpack.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js:3:30)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/.pnpm/rtlcss-webpack-plugin@4.0.7/node_modules/rtlcss-webpack-plugin/dist/src/index.js',
    '/node_modules/.pnpm/@wordpress+scripts@30.7.0_@playwright+test@1.49.1_@types+eslint@9.6.1_@types+node@22.10.2_@ty_wroepmchm5g4fgh3o3zlqgqj4a/node_modules/@wordpress/scripts/config/webpack.config.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/webpack-cli.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/lib/bootstrap.js',
    '/node_modules/.pnpm/webpack-cli@5.1.4_webpack-bundle-analyzer@4.10.2_webpack-dev-server@4.15.2_webpack@5.97.1/node_modules/webpack-cli/bin/cli.js',
    '/node_modules/.pnpm/webpack@5.97.1_webpack-cli@5.1.4/node_modules/webpack/bin/webpack.js'
  ]
}
 ELIFECYCLE  Command failed with exit code 2.

</code>
</details>

### Step-by-step reproduction instructions

- Checkout https://github.com/wptrainingteam/devblog-dataviews-plugin/pull/4
- Run `pnpm remove @babel/runtime`
- Run `pnpm install`
- Run `pnpm build`
- See the build failure

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by gziolo**
## What?

Fixes #62007.
Fixes #67866.

The `@babel/runtime` dependency is limited to v6.25.x for `rtclcss-webpack-plugin` which causes issues.

As noted by @mamzoorwanjik in https://github.com/WordPress/gutenberg/issues/67866#issuecomment-2556927916:

> It's something related to the import of `rtlcss-webpack-plugin` which interestingly [defines `@babel/runtime` as a dependency](https://github.com/wix-incubator/rtlcss-webpack-plugin/blob/6d73d89250f10e13e16f353cadaf1469771aeea2/package.json#L40)

The same dependency was reported as problematic by @stein2nd in #62007. 

## Why?

No new version has been published for `rtlcss-webpack-plugin` for the last 3 years. There are open PRs for both dependencies with no activity. 

## How?

Fork and simplify the plugin so integrates seamlessly with the default webpack config for `wp-scripts build` and `wp-scripts start`.

## Testing Instructions

It definitely can be tested manually by running the build for the scaffolded block:

```sh
npx wp-create-block my-block --no-wp-scripts
cd my-block
vim src/editor.scss // Add "text-align: left;" to the existing CSS style
../node_modules/.bin/wp-scripts build
```

Screenshot 2024-12-20 at 16 45 06

Screenshot 2024-12-20 at 16 47 20

### CODE REVIEW

**Comment by gziolo** [comment]
This is ready for review. As a follow-up, it would be a perfect time to introduce some integration tests for the default webpack config shipped with `@wordpress/scripts`. I will work on it in parallel as it can be added directly to `trunk` because the result should be exactly the same. There is no new functionality introduced with this PR.

**Review by manzoorwanijk — APPROVED** [review]
This works well.

Do we want to use it internally, or do we want to release it for the community to use?

**Comment by gziolo** [comment]
> Do we want to use it internally, or do we want to release it for the community to use?

I would prefer internally only, hoping that upstream version gets updated in the future. Other projects can always use `overrides ` in `package.json` to enforce the proper dependencies in the original plugin. In the case of `@wordpress/scripts` we want to streamline the experience so that’s why I went the harder way.

**Comment by SmushyTaco** [comment]
I actually made a fork of this plugin [here](https://www.npmjs.com/package/@smushytaco/rtlcss-webpack-plugin) where all dependencies are updated and it's rewritten in TypeScript. I think this would be better to use rather than internally bundling a modified version of the plugin.

**Pull request merged**
