### PR TITLE
Image block: refactor and remove `data-wp-body`

### PR DESCRIPTION
**Pull request by luisherranz**
## What?

This PR removes the use of `data-wp-body` directive in the Image block. It also refactors the logic a bit to clean up the code, and reduce the size of the JavaScript file.

## Why?

Because the Interactivity API won't include the `data-wp-body` directive in the WP 6.5 version.

## How?

By replacing the `data-wp-body` with a `wp_footer` filter that prints only one lightbox overlay for all the images.

## Testing Instructions

- Add an image and enable the "Expand on click" functionality.
- Check that it works great in all situations. There should not be any variation in the lightbox behavior:
  - Zoom animation in and out.
  - No animation on reduced motion.
  - Tab/Esc keys.
  - Focus on the different elements.
  - Styles and classes applied, like custom borders or duotones.

### CODE REVIEW

**Comment by luisherranz** [comment]
The e2e tests don't pass yet, but this is ready for a preliminary review.

**Comment by luisherranz** [comment]
It looks like this PR refactoring reduced the size of the JS code of the lightbox by 25% 🙂

**Comment by luisherranz** [comment]
This is ready. We saw a couple of bugs in Safari that are already present in `trunk` and will need further investigation to fix, so I did not address them in this refactoring:

- The first animation is not triggered.
- The animation is not triggered on images with duotone.

**Review by SantosGuillamot — APPROVED** [review]
Great refactoring! 👏 Glad to see that we are sending less JS and HTML to the browser 🙂 

I've been testing it on Chrome, Safari, iPhone, and Android, and everything seems to be working as previously.

**Pull request merged**
