### PR TITLE
Consolidate sequential multi-entity-saving tests.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Discussions in core slack with @talldan and @youknowriad pointed out sequential tests can be problematic.  This PR consolidates multi-entity-saving tests that are dependent on each others steps into the same test blocks.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
Link to core editor thread for context https://wordpress.slack.com/archives/C02QB2JS7/p1603273692298300

**Comment by noahtallen** [comment]
what if we also added `expect.assertions( numAssertions );`? (https://jestjs.io/docs/en/expect.html#expectassertionsnumber)

**Comment by Addison-Stavlo** [comment]
> what if we also added expect.assertions( numAssertions );?

Interesting.  I wonder if that makes sense here?  In the example it is used to ensure assertions within passed callbacks actually happen, but here we aren't passing any assertions as callbacks but are just calling the assertions themselves?

**Comment by noahtallen** [comment]
good point! I don't really mind; I've just seen it in a few places and thought it might fit

**Pull request merged**
