### PR TITLE
Cover Block: Use the description in the placeholder

### LINKED ISSUE #34707: Expand the placeholder description to describe the different things that are possible.
Screen Shot 2021-09-09 at 9 52 27 AM

### PR DESCRIPTION
**Pull request by apeatling**
Fixes https://github.com/WordPress/gutenberg/issues/34707
Part of https://github.com/WordPress/gutenberg/issues/28385

## Description

Update the placeholder instruction text to describe what the block does, rather than just stating the obvious next steps. This has been updated to match the description text already present for the block.

## How has this been tested?

Local testing.

## Screenshots 

**Before:**
132729101-643551bb-739d-4ca9-9058-73db6dacf17e

**After:**
Screen Shot 2021-09-20 at 10 42 55 AM

## Types of changes
Non-breaking change.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by apeatling** [comment]
@mtias & @jasmussen Interested in your feedback on wording here, and if we should keep some sort of instruction on uploading/grabbing from media library.

**Comment by mtias** [comment]
We have neglected these a bit, but the idea was that they would include _some_ guiding on how to get started — in this case, it should also mention something about dragging media into the block. In that sense, I think _really good_ placeholders would tend to diverge from the block description rather than become one, or the block description would need to expand to include some of this guidance, which might feel out of place in sidebar inspector / previews.

**Comment by apeatling** [comment]
How about we use the description because it is succinct and clear, then add some instructions on the end, so:

> "Add an image or video with a text overlay -- great for headers. To get started, drag and drop an image or video on this block or select and upload it from your device. If you have an existing image or video, you can select it from your media library."

**Comment by ramonjd** [comment]
> "Add an image or video with a text overlay -- great for headers. To get started, drag and drop an image or video on this block or select and upload it from your device. If you have an existing image or video, you can select it from your media library."

The first sentence, aside from a hint in relation to headers, given the subsequent explanation and the UI controls themselves I think isn't required.

So I think the instructional text you have would stand well on its own. Tweaks are my own and optional :)

_"Drag and drop an image or video onto this block or upload one from your device. If you have an existing image or video, you can select it from your media library."_

**Comment by glendaviesnz** [comment]
This works as advertised for me, except for other languages:

Screen Shot 2021-09-22 at 4 57 02 PM

The info card in the right panel gets the description from the store via the [useBlockDisplayInformation](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/use-block-display-information/index.js#L39) hook, which must be handling the translation.

**Comment by apeatling** [comment]
Updated with custom instructions based on what Ramon wrote:

> "Drag and drop an image or video onto this block or upload one from your device. If you have an existing image or video, you can select it from your media library."

**Comment by stacimc** [comment]
> If you have an existing image or video, you can select it from your media library.

Maybe overthinking it, but I wonder if something like `You can also select an existing image or video from your media library` would be more clear? Specifically that "existing image or video" means "already uploaded/existing _in your media library_".

**Comment by glendaviesnz** [comment]
> I wonder if something like `You can also select an existing image or video from your media library` would be more clear

I think it is worth this change just to really clarify what 'existing' means.

**Comment by jasmussen** [comment]
One aspect to consider is that this text will be very useful the first time you see the cover block, and likely not that helpful the third, tenth, or 100th time you see it, so it feels worthwhile to temper the amount of text with that notion. In that light, I'd lean towards reducing the text to as little as can convey what it needs to.

Even reducing the text discussed, and setting it to `font-size: $helptext-font-size`, it becomes a lot:
cover

For the PR, be sure to test narrow contexts. The `Placeholder` comes with built-in CSS classes that appear, such as `is-small`, `is-medium` and `is-large`.

**Comment by apeatling** [comment]
Trying to shorten it without losing information. How about:

> Drag and drop onto this block, upload, or select an existing image or video from your media library to get started.

**Review by ramonjd — APPROVED** [review]
I think this is an improvement on the existing copy and a safe change to merge. 

As the Cover Block evolves we'll inevitably have to update it later anyway in my estimation. 

👍

**Comment by jasmussen** [comment]
Nice work. I think in absence of a redesign, we might want to try and shorten the text ever so sligtly more, because in most context it now wraps when before it didn't. Before:
Screenshot 2021-10-06 at 11 11 24

After:

Screenshot 2021-10-06 at 11 11 55

The problem remains primarily that so much is going on in the placeholder already, and with two lines it actually grows a bit in height.

Here it is with a different phrasing which I inspected in (I forgot the period at the end):

Screenshot 2021-10-06 at 11 13 15

I also tried with 12px font size, but that looks off:

Screenshot 2021-10-06 at 11 13 32

I think we need a holistic redesign of the base ingredients of the placeholder, separately from this PR. But it'd be nice if we could land on a phrasing that improves the description but still keeps it to one line.

**Comment by apeatling** [comment]
Thanks @jasmussen -- we can even drop the extra "a" in your reduction above, so with the period that will stay on one line:

"Drag and drop onto this block, upload, or select existing media from your library."

I think we can go ahead and merge this and then look at the wording further with the design updates coming. :+1:

**Pull request merged**
