### PR TITLE
Don't redirect to Gutenberg from the classic editor.

### LINKED ISSUE #3137: Saving Classic Posts magically switches to Gutenberg
## Issue Overview
When saving a new classic post as draft, the page saved and then became Gutenberg.

## Steps to Reproduce (for bugs)
1. Open a new post in classic editor (I used a CPT)
2. Make some changes
3. Click save as DRAFT
4. Gutenberg

Using:
* Safari on MacOS High Sierra
* WP 4.9-beta3-41983

## Expected Behavior
Let classic be classic 😄 

## Current Behavior
Got Gutenberg 😢

### PR DESCRIPTION
**Pull request by pento**
When saving a post in the classic editor, it redirects to Gutenberg. As much as I enjoy this bug, it's a somewhat surprising user experience.

Fixes #3137.

### CODE REVIEW

**Comment by pento** [comment]
Note: I noticed the same bug in Revisions - restoring a revision, or clicking the links in the header, take you to Gutenberg.

**Review by gziolo — APPROVED** [review]
Code looks good and it works as expected for the `Save draft` part. 

I can confirm that the same issue exists for Revisions.

**Comment by buzztone** [comment]
Is this planned to be included in a minor release? Bug makes working on a site with a mixture of Classic & Gutenberg Posts & Pages rather challenging.

**Comment by gziolo** [comment]
It works properly for all links I could find on the Revisions page. 🚢

**Comment by pento** [comment]
@buzztone: There are a couple of other bugs I've run into, so I think a minor release is a good idea.

**Pull request merged**
