### PR TITLE
Removed unwanted space from the string

### PR DESCRIPTION
**Pull request by mujuonly**
## What?
Removed unwanted space in the string

## Why?
Unwanted space at the end of the string shows warning at translation.

## How?
Removed unwanted space in the string

## Testing Instructions
Text correction only

### Testing Instructions for Keyboard
Text correction only

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @mujuonly. Changes look good to me.

**Review by getdave — APPROVED** [review]
Thanks for the PR 👍

**Comment by talldan** [comment]
I'm not sure if this was manually tested, but it makes the message appear like this:
Screenshot 2023-10-04 at 4 27 16 pm

(with no space between the 'Navigation menu has been deleted or is unavailable.' and the following 'Create a new menu?' button)

Not sure if this code should use `createInterpolateElement`, as I think the way it concatenates text right now is generally considered hard to internationalize.

**Comment by getdave** [comment]
Good catch Dan. Thank you.

 I could have sworn that when I tested this I didn't see that happening. Perhaps I made some error in testing?

Either way we should fix this.

**Comment by getdave** [comment]
I have a PR incoming

**Comment by talldan** [comment]
Thanks Dave!

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: d11de6728c

**Pull request merged**
