### PR TITLE
Bump version to 1.0.0

### PR DESCRIPTION
**Pull request by karmatosed**
## Changelog

* Restored keyboard navigation with more robust implementation, addressing previous browser issues.
* Added drag and drop for media with pointer to create new blocks.
* Merged paragraph and cover text blocks (includes the colors and font size options).
* Reworked color palette picker with a "clear" and a "custom color" option.
* Further improvements to inline pasting and fixing errant empty blocks.
* Added thumbnail size selector to image blocks.
* Added support for url input and align and edit buttons to audio block.
* Persist the state of the sidebar across page refresh.
* Persist state of sidebar panels on page refresh.
* Persist editor mode on page refresh.
* New withAPIData higher-order component for making it easier to manage data needs.
* Preserve unknown block and remove "freeform" comment delimiters (unrecognized HTML is handled without comment delimiters).
* Show "add new term" in hierarchical taxonomies (including categories).
* Show tooltip only after mouseover delay.
* Show post formats only if the post type supports them.
* Added align and edit buttons to video block.
* Preload data in withApiData to improve perceived performance.
* Improve accessibility of sidebar modes.
* Allow changing cover-image settings before uploading an image.
* Improve validation leniency around non-meaningful differences.
* Take into account capabilities for publishing action.
* Update author selector to show only users capable of authoring posts.
* Normalize pasted blockquote contents.
* Refactored featured image, page attributes to use withApiData
* Added a fix to avoid cloning nodes by passing pasted HTML string.
* Added a fix to avoid re-encoding on encoded posts.
* Fixed resetting the focus config when block already selected.
* Allowing adding of plain text after insert link at the end of a paragraph.
* Update to latest TinyMCE version.
* Show only users capable of authoring posts.
* Add submit for review to publish for contributor.
* Delete or backspace in an empty "classic text" block now removes it.
* Check for type in block transformations logic.
* Fixed drop-down menu issue on classic text.
* Added filter to allow post types to disable "edit in gutenberg" links.
* Made UrlInput and UrlInputButton available as reusable components.
* Use wordpress/a11y package instead of global.
* Added npm5 package-lock.
* We welcome all your feedback and contributions on the project repository, or ping us in #core-editor. Follow the "gutenberg" tag for past updates.

### CODE REVIEW

**Comment by ntwb** [comment]
Why not `0.10.0` ?

There was a versioning discussion in #core-editor not long ago, it kicks off round about here: 
> https://wordpress.slack.com/archives/C02QB2JS7/p1501693681966490

And finishes up round about here:
> https://wordpress.slack.com/archives/C02QB2JS7/p1501695746169570
> `0.10.0` is a thing too

The tl;dr take away is that version `1.0.0` leads to a lot of assumptions...

**Comment by youknowriad** [comment]
> The tl;dr take away is that version 1.0.0 leads to a lot of assumptions...

That's the best reason to do `1.0.0` sooner rather than later and continue with `1.1` .... People won't have any assumptions from `1.1` which should be next week. If we keep waiting, moving to `1.0.0` will be harder and harder. Let's make the version meaningless. (Also we could do `10.0` directly, like React did

**Comment by mtias** [comment]
I wouldn't mind calling the next version 11.0. :)

**Comment by jb510** [comment]
@youknowriad 
> Let's make the version meaningless

Why does the Gutenberg team hate outside developers so much? Maybe because we've been so vicious criticizing Gutenberg and have it coming but still...  

You want us to build blocks and make use of Gutenberg, but won't adopt semantic versioning so we know what's stable API, like the majority of the software world and worse seem to have decided this should be the policy forever...  So, who knows if breaking changes come between 52.2.0 and 52.3.0 or not. Fun!

If you're going to do this, drop the x.x.x notation and just go by build numbers. Build 10, Build 11, Build 12...  Week 10, Week 11... 

It's confusing as heck...

**Comment by youknowriad** [comment]
> Why does the Gutenberg team hate outside developers so much? 

We do not, we appreciate the feedback and we welcome any contribution from outside developers.

> You want us to build blocks and make use of Gutenberg, but won't adopt semantic versioning so we know what's stable API

WordPress Core doesn't follow semver, same for Gutenberg. We never claimed the API to be stable. I think it won't be stable until Gutenberg is accepted for merge in WordPress, I may be wrong though, I speak only for myself.

> If you're going to do this, drop the x.x.x notation and just go by build numbers. Build 10, Build 11, Build 12... Week 10, Week 11...

What the difference, just consider it like this.

We want to make the version meaningless, take Chrome as an example.

**Comment by jb510** [comment]
When I said "outside developers" I meant developers not building Gutenberg itself, but rather than 1000s of developers building themes and plugins that will hopefully interface with Gutenberg at some point. People like me.

Note please that the version number of Chrome is not meaningless.  https://www.chromium.org/developers/version-It's just different, but it's absolutely meaningful and _well documented_.

The version number in Gutenberg is not meaningless either, it's just confusing and undocumented. 

Based on this release and need to keep ticking upward we'd infer that it follows Deca-weeks.weeks.0 that's insane. 

You want us to infer that it's "meaningless" but same time you want to follow a bad pattern that is _meaningful_.  Someday the weekly release cycle will end...  are you then going to jump from 4.2.0 to 5.1.0 because there were 9 weeks between releases?  

Gutenberg is getting better,  that makes me happy, but this versioning numbering is lazy and hostile to outside developers when it doesn't need to be.

**Comment by aduth** [comment]
Noting that with the addition of `package-lock.json` in 0b37d6feed8f3ea762ba742e952db015b5f3efa6 we should also bump version in this file. This would be automated in `npm version minor  --no-git-tag-version`. I updated for 1.0.0 in 28adfcd.

**Pull request merged**
