### PR TITLE
Social Links: Update Placeholder experience when first inserting Social Links

### LINKED ISSUE #19020: Iterate on social block placeholder
Currently, the starting point of social links is a lot visually:

image

Considering what the other placeholders have, it might be nice to reduce the options and have a starting step. Here, for example, are the columns and navigation ones:

image

### LINKED ISSUE #21700: Remove WordPress icon from default icons list in Social Icons block
**Describe the bug**
The Social Icons block defaults with several default icons, including the WordPress icon. Not only that, it even defaults the url to `wordpress.org` so even if you don't add a URL to it, it automatically displays on the rendered page. What happened to the 80/20 rule? The majority of users wont want a WordPress icon so it forces an extra step upon them to have to remove it.

The Social Icons block should only default with the (current) most common platforms (Facebook, Twitter, Instagram, LinkedIn & YouTube).

WordPress icon displays even though I never entered a URL for it
screenshot_77

**To reproduce**
Steps to reproduce the behaviour:
1. Insert Social Icons block
2. Click on the Twitter URL and enter `twitter.com`
3. Save the page and preview it in the browser
4. View that the WordPress icon also displays even though you never entered any URL for it

**Expected behavior**
The WordPress icon should not be displayed by default, either in the Editor or on the front-end.

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
- Browser: Firefox 75.0

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Adds a new placeholder prop to InnerBlocks and BlockList to render in front of the appender if specified and no blocks.

An example component is passed in with the Social Links to display when no links have been added. The template of default links is also removed. Combined this is intended to provide a better experience than the appearing/disappearing links that require to be removed, while still be clearing what is happening.

@jasmussen Can you try this out, I have a temp placeholder there that can use some better style and improvement.

Fixes: #19020 
Fixes: #21700

## How has this been tested?

1. Create a block with social links
2. Apply the change and confirm nothing breaks with existing block.

1. When adding new social confirm the placeholder shows and not the old default list.
2. Confirm the placeholder is removed when a new link is added
3. Confirm the placeholder does not break or effect other InnerBlocks (columns is a good test)

## Screenshots

social-link-placeholder

## Types of changes

- Adds placeholder prop to BlockList component, and renders if no blocks
- Adds placeholder prop to InnerBlock passing forward to BlockList
- Add example placeholder to Social Links block
- Remove template constant passed to InnerBlocks so no default icons inserted
- Do not hide the icons when the block is not selected, this matches the image placeholder experience

## Checklist:

- [ ] API documentation update still required.

### CODE REVIEW

**Comment by jasmussen** [comment]
This is what I see:

social

This is a good feature! It can benefit the navigation menu and buttons blocks also.

It definitely needs a different design :D — ideally something that looks like social links. I'll help you with that. But in principle this seems to work well for me.

**Comment by jasmussen** [comment]
I've had a moment to reflect on this PR, and I think we have to zoom out for a bit.

Right now, when we refer to "Placeholders" in block editor parlance, we think mostly of this:

Screenshot 2020-10-09 at 09 47 50

It's a big white box with text and buttons inside, always 200px tall. But in most cases, this placeholder looks nothing like the end result. The navigation menu is an excellent example of this — if you squint, there's no way to distinguish a nav menu placeholder from an image placeholder, even though they're vastly different. More importantly, the navigation placeholder looks _nothing_ like its own end result. 

That's the driving force behind this good rethink by @shaunandrews in https://github.com/WordPress/gutenberg/issues/23207#issuecomment-681033138: 

91338938-b3c5ed80-e7a3-11ea-80d5-7aabba57a33c

Instead of using a big box, it provides some handy links to quickly complete the setup state for the block, while at the same time looking just a little bit like the end result. We might be able to get even closer, but this is a good step in the right direction.

All of the above was also the driving force behind preinserting a number of icons when you insert it the first time. And in addition to that, to give a feeling of what the end result might look like. 

Putting that all together — squint and it looks right, keep it simple, don't be a giant white box — perhaps we could do with something as simple as this?

placeholder

Those colored dots look like the classic social link blobs, but blurred out to indicate they aren't set up. As son as you add a single button, they disappear.

Speaking of, the "add" menu looks like this:

Screenshot 2020-10-09 at 09 54 43

I do love how it shows 6 icons and has a search feature. But we need to update the search icon to be this one:

Screenshot 2020-10-09 at 10 10 34

and is there _any_ way we can customize the defaults showing up there? I think there's some frecency going on here, but amazon and behance really don't deserve to be at the top, they are just riding on alphabetization here.

**Comment by jasmussen** [comment]
By the way, if you dig the above, I can push the code to make the setup state look like the mockup.

**Comment by mkaz** [comment]
@jasmussen I do like the above 👍 

As far as the inserter and the icon, it is still using the common InnerBlocks inserter, so it will require further modifications to allow customizing the icon and other aspects (sort order). We can push those forward in other PRs if think it it is the right approach.

**Comment by jasmussen** [comment]
Let's feel it, and if the blur doesn't work I'll try one where I recreate 4 dummy icons and make them semi transparent.

**Comment by mkaz** [comment]
@jasmussen I just pushed up a change using blurred placeholder. Take a look and let me know if that is what you are thinking. Here's it in action:

social-link-placeholder

**Comment by shaunandrews** [comment]
I have a very strong (negative) reaction to the blurred blobs, but its likely just personal preference.

That said, I also have a concern that the blur would look really strange on some site designs with image/color backgrounds; Its also not very representative of the actual output of the rendered block.

**Comment by mkaz** [comment]
@shaunandrews Thanks for the thoughts, I'm fine with altering the blur if it doesn't work.

As far as design, this would only ever show in the editor, are you still thinking of design conflicts in that context?

As far as end result, comparing it to other placeholders like image, shortcodes, etc... none of those look like the end published result when they have not been filled with content. The goal with the Social Link placeholder is just to fill the space with something, so it's not just the [+] inserter in that space when no icons have been picked.  The current solution uses actual icons that requires removing and confuses people, so trying for something.

Do you think none blurred circles of color/gray would work better?

**Comment by jasmussen** [comment]
Yep, from the blur in https://github.com/WordPress/gutenberg/pull/25941#issuecomment-706038788 I thought it was worth trying, because I had this idea that blur might be a way to make skeleton indicators more "real", and potentially use it for placeholders also:

Screenshot 2020-10-14 at 20 10 07

Screenshot 2020-10-14 at 20 10 29

But it isn't working here as I had hoped. I'll push some tweaks to this.

**Comment by shaunandrews** [comment]
> ...are you still thinking of design conflicts in that context?

Yes, specifically in the context of the site editor as well as within patterns with background colors or images.

I bet just the plain circle shapes (not blurred) would work just as well, and be more representative of the intended result.

**Comment by jasmussen** [comment]
> I bet just the plain circle shapes (not blurred) would work just as well, and be more representative of the intended result.

Yep, that's the alternative I was going for, possibly semi transparent. I'll also use fb/twitter/insta colors.

**Comment by jasmussen** [comment]
I pushed some polish. Here's how it looks now:

status

I think this is worth trying! What do you think?

**Comment by mkaz** [comment]
This works well for me, definitely an improvement to the overall placeholder experience. 
@shaunandrews thoughts?

**Comment by shaunandrews** [comment]
image

I like it better than the blurring. It's a little strange that clicking on the empty shapes doesn't _do_ anything, but I realize that starts to creep back towards the current behavior.

--

The empty shapes only makes sense if the block is using the pill or circle style; If you set the default to "Logos Only" this'll break:

image

(The placeholder shapes don't change when I choose the "Pill Shape" style, but I figured that's just an implementation detail that hasn't been sorted yet.)

--

Perhaps unrelated to this PR, the focus shapes are really strange and clicking on the "Browse All" button at the bottom of the inserter unselects the block.

**Comment by jasmussen** [comment]
Solid feedback as usual. I tweaked the setup state based on variations. Default:

icons_circles

Icon only:

icons_only

Pills:

icons_pills

**Comment by shaunandrews** [comment]
👍

**Review by jasmussen — APPROVED** [review]
Let's try it.

**Pull request merged**
