### PR TITLE
Only consider legal block types for the block list when transforming files to blocks

### LINKED ISSUE #26815: Improve block transforms to better handle allowed blocks
**Is your feature request related to a problem? Please describe.**
#25940 exposed an interesting issue. That PR proposes to change the gallery block so that it uses inner image blocks. Image blocks are the only allowed block type within a gallery on that PR.

Currently when dropping multiple image files into the block editor, a gallery block is created. But in #25940, if a user tries dragging multiple image files into a gallery block, that won't work as a gallery cannot be inserted within a gallery.

This creates a situation where:
- When dragging multiple image files into a gallery block, multiple image blocks should be created via a transform.
- When dragging multiple image files outside of a gallery block, a single gallery block should be created.

As far as I can tell, the raw handling/transforms system doesn't support this.

**Describe the solution you'd like**
A separate lower priority transform for images could be registered in the image block

Additionally, the `onFilesDrop` code is modified. This code already searches for valid transforms:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/use-on-block-drop/index.js#L145

It could changed to ignore transforms for block types that aren't allowed within the current block list. For example, it would disallow transforms from `core/gallery` given this block type is not an allowed block within itself.

**Describe alternatives you've considered**
The alternative also involves a separate lower priority transform for images in the image block.

Instead, the transform `isMatch` function could be more context aware. For example it could receive an extra argument that can be used to determine whether the transform is correct for the context, like the `rootClientId`.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Proposal to fix #26815

When dropping files, the `onFilesDrop` handler searches for a matching transform.

There's a chance currently that the matching transform will fail to insert if the block list we're inserting into doesn't accept the block type—`allowedBlocks` might be specified.

This PR changes the code to only find transforms that can be inserted.

## How has this been tested?
This is hard to test right now without checking it works on #25940.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This worked form me in conjunction with https://github.com/WordPress/gutenberg/pull/25940/commits/a868f58a08a87919b8a2ef92ad9590334b2c22b0

**Review by hc0503 — APPROVED** [review]

**Comment by glendaviesnz** [comment]
@talldan what other testing do you think we need to do on this to get it merged besides running against #25940 ? I think we are getting towards the end of the work on that PR so we be good to have this one in master once we get to the point of rebasing it again.

**Comment by talldan** [comment]
Open to reviews on this. I've looked into writing tests but it's tricky to validate with tests. 

The logic itself is in a nested callback, with a dependency on `canInsertBlocks`, so hard to unit test, but I can look into extracting it if a reviewer feels that's worthwhile.

I think the best thing would be to see whether an e2e test can be written against #25940. I imagine Puppeteer can only simulate file drop events by manually triggering the event, so that will also be quite contrived, but still a better real world test.

**Comment by glendaviesnz** [comment]
ok, I will take a look at the tests side of it tomorrow and see what I can figure out

**Comment by glendaviesnz** [comment]
@talldan do you think it would be possible to get this merged in to master, and then we can rebase it into #25940 which will make the final testing/approval of that PR a little easier?

**Comment by talldan** [comment]
@glendaviesnz Yep, I'm happy to merge it if I can get an approving review. I also don't know an effective way of testing without considerable setup code in a test. After #25940 is merged I could have a look at writing an e2e test for the gallery block.

**Review by draganescu — APPROVED** [review]
I think this makes perfect sense and it appears to break nothing,

**Comment by talldan** [comment]
Thanks Andrei!

**Comment by glendaviesnz** [comment]
👍 Thanks Dan!

**Pull request merged**
