### PR TITLE
Cover block: Refactor controls

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Extracts the Cover block Block Control and Inspector Control components into separate files, along with a couple of other components and utils. 

## Why?
The Edit component file is currently large and hard to work with and almost impossible to test. This structure should hopefully make it easier to work with long term as well as make it possible to write unit/integration level tests for some of the block control functionality.

## How?
Mostly as straight move of code into separate files and a couple of variable/method renames, should be no change to functionality

## Testing Instructions

- Check that all aspects of the Cover block work as expected
- Check that `npm run test-unit packages/block-library/src/cover/test/block-controls.js` sample unit test runs

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@youknowriad, @jorgefilipecosta, @aristath, @gziolo, @andrewserong, @ramonjd   - just pinging a few people that have worked on the Cover block in past to see what the general thoughts are on splitting this now reasonably complex block's edit method up to try and make future refactoring/enhancement/testing easier.

This PR splits the block and inspector controls out to separate files, and while this does reduce the size and complexity of the `edit.js` file, the main advantage I think is that it allows much easier unit testing of the block and block controls. There is a [very simple sample test here](https://github.com/WordPress/gutenberg/pull/40832/files#diff-ce78c260311bdef488f2a1f9f8c2c0e62d7c4bec6a688d92dab10e0d308664dc) as an example of this.

We found this approach of splitting out the controls useful in the Jetpack blocks for adding better test coverage, but it isn't currently a common pattern in the core blocks, so just checking if there are any reasons why we wouldn't/shouldn't take this approach?

Personally, I would see this as a '_do it as and when it seems to make sense due to size and complexity of a block'_, rather than a '_This is best practice so let's insist that every block is set up like this from now on_' 😃

**Comment by ramonjd** [comment]
> I would see this as a 'do it as and when it seems to make sense due to size and complexity of a block', rather than a 'This is best practice so let's insist that every block is set up like this from now o

I haven't tested it yet, but it makes sense to me. And having worked on the Jetpack blocks, event split between edit logic and controls was helpful. Thanks for working on this @glendaviesnz 

I can't help but wonder about the half-life of this particular block. As others have said, maybe once we get background block supports in order this block might become redundant 🤷

**Comment by gziolo** [comment]
@glendaviesnz, this is always a great idea to split monolithic files into smaller chunks. In particular, for React components, it often brings additional benefits when you can decrease the reasons for the component to re-render. The only thing I would suggest is to group all those newly introduced files in the `edit` subfolder so they are grouped together in one place and the `cover` folder contains files that directly translate to block API parts like variations, transforms, save, etc.

I wouldn't mind if that would be the codified standard for all core blocks in the https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library#contributing-to-this-package section.

**Comment by glendaviesnz** [comment]
> he only thing I would suggest is to group all those newly introduced files in the `edit` subfolder so they are grouped together in one place

Good idea, have done that. Will sort out the conflict tomorrow, and will see if the root dir can be tidied up any more re native edit files.

**Comment by ntsekouras** [comment]
`Cover` desperately needed that 😄, thanks for doing this Glen!

**Comment by gziolo** [comment]
There are some merge conflicts to resolve but otherwise we should plan to land it as soon as possible 👍

**Comment by glendaviesnz** [comment]
@fluiddot just copying you into this as you recently made some changes to the mobile side of the Cover block. I have moved the web side of the edit method into a subfolder, and split it out into separate files. I don't think this will affect the mobile side, but can you have a quick look and just double check that please?

It probably makes sense to move the mobile edit related files into the same edit/ subfolder, but I am thinking that maybe we should do that as a separate PR, what do you think?

**Review by andrewserong — APPROVED** [review]
This is such a nice improvement @glendaviesnz! I'm finding the refactored files much easier to navigate and browse, and putting them together in the `edit` directory makes good sense.

✅ The cover block behaves just as it did before in the editor (I manually tested all the block and inspector controls).
✅ The cover block still behaves as expected in the iOS simulator (refactoring the native side in a separate PR sounds good to me)
✅ Sample tests pass.

LGTM! 🎉

**Review by ramonjd — APPROVED** [review]
All Cover Block functionality works for me. Tests pass.

After arm wrestling with getting native ios to run, it also LGTM 😅 

Screen Shot 2022-05-11 at 11 15 33 am

**Comment by fluiddot** [comment]
> @fluiddot just copying you into this as you recently made some changes to the mobile side of the Cover block. I have moved the web side of the edit method into a subfolder, and split it out into separate files. I don't think this will affect the mobile side, but can you have a quick look and just double check that please?

Thanks for the ping @glendaviesnz 🙇 ! I've done a quick check on the code, as well as tested it locally, and can confirm that the changes didn't affect the native version of the block 🎊 .

> It probably makes sense to move the mobile edit related files into the same edit/ subfolder, but I am thinking that maybe we should do that as a separate PR, what do you think?

I totally agree, now that we have the edit-related files in that subfolder, it would be great to have the native version files there too 👍 . I'll add a reminder to myself to do this in the next few days.

**Pull request merged**
