### PR TITLE
Fix Paragraph appender layout shift (building on 66061)

### LINKED ISSUE #65969: Paragraph appender: layout shift when Content block fills the container
When the Content block is set to "Inner blocks use content width", the Paragraph appender is replaced with a Paragraph block without a layout shift. When the Content blokc is set to _not_ use content width, there's a big visible layout shift when the Paragraph block replaces the appender:

Image

Steps shown in the GIF:

* Site editor, set Content block to "Inner blocks use content width", save. 
* Go to post editor, click the Paragraph block, notice no layout shift.
* Site editor, unset Content block from "Inner blocks use content width", save.
* Go to post editor, click the Paragraph block, notice a big layout shift.

This shift happens because the paragraph inside the appender has top/bottom margins, and this margin is unset by the content width rules, these:

Image

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes: #65969 

This PR is forked from #66061 (kudos @Vrishabhsk for the work here!)

Set the default block appender to have top and bottom margins of `0`.

## Why?

As discussed in #66061 and #65969, the layout rules used in the post content block means that the first and last child of the post content area will have a `0` margin at the top and bottom. The (fake) default paragraph appender therefore needs to have similar rules applied to it in order to override user agent styles that cause a layout shift when a user interacts with the default appender and creates the first block in a post or page.

## How?

Always apply `0` top and bottom margins on the default appender, rather than only for particular layouts.

A question for reviewers: does this rule seem safe enough to always be applied? So far in testing, it _seems_ to feel safer to me to apply this reset-like style than not.

## Testing Instructions

Note: in order to test the original issue in #65969 you might need to update the single post template's post content block to use the flow/default layout by switching off "Inner blocks use content width" on that block:

image

1. While running TT5 theme go to create a new post or page
2. Click on the default appender to create the first paragraph block
3. Notice that there shouldn't be any layout shift when the paragraph block is inserted
4. Test across a range of themes that this doesn't cause any issues (it's working well for me so far in all the Twenty-something core themes)

## Screenshots or screencast 

https://github.com/user-attachments/assets/545729c0-965a-400f-a9b5-85ed8d224047

### CODE REVIEW

**Comment by andrewserong** [comment]
I've just added this to the 6.7 board in case there's still time to get it in. I'm not sure if it's possible at this stage, but @jasmussen flagged it as a good one for inclusion if it's possible, so thought I'd flag it there.

**Review by ramonjd — APPROVED** [review]
I can't reproduce the original issue on any browser for any post type. 

But since it reduces the CSS and I can't find any regressions, here's a ✅ 

Trunk

```css
:where(.wp-site-blocks) .block-editor-default-block-appender>:first-child, :where(body .is-layout-constrained) .block-editor-default-block-appender>:first-child {
    margin-block-end: 0;
    margin-block-start: 0;
}
```


This PR:

```css
.block-editor-default-block-appender .block-editor-default-block-appender__content {
    margin-block-end: 0;
    margin-block-start: 0;
    opacity: .62;
}
```

**Comment by andrewserong** [comment]
Thanks for the review @ramonjd! 🙇 

> I can't reproduce the original issue on any browser for any post type.

Ah, I assume to reproduce we might need a template that sets the post content block to use default/flow layout instead of constrained 🤔

I'll update the test instructions.

**Comment by ramonjd** [comment]
> Ah, I assume to reproduce we might need a template that sets the post content block to use default/flow layout instead of constrained 🤔

That was it! Thank you!

### Before



https://github.com/user-attachments/assets/de981e3d-6069-4ae0-a568-16b5db4f646d

### After

https://github.com/user-attachments/assets/af45ad2c-6bd1-4c40-88d7-894d5cfb11ba


LGTM

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for spinning up this PR @andrewserong and for the original work @Vrishabhsk 👍

✅ Could replicate original issue
✅ Code changes look good
✅ Logic to reset for all appenders makes sense
✅ Fixes the issue
✅ Couldn't spot any regressions

| Before | After |
|---|---|
| <video src="https://github.com/user-attachments/assets/25fb02b5-a4bc-44e3-87c6-ab33526171cc" /> | <video src="https://github.com/user-attachments/assets/7b83b88e-143c-4159-ab4c-ac97bcab073a" /> |

**Comment by jasmussen** [comment]
Thanks for this one 🙏

**Comment by getdave** [comment]
Noting that this missed the final RC3 so it is not certain to be included in 6.7. 

I'm seeing that the WP 6.7 Design Lead @jasmussen sees this as an important PR. It will be under consideration for inclusion _if_ possible.

**Comment by jasmussen** [comment]
I consider this a pretty critical bug, so would definitely like to see this included.

**Pull request merged**
