### PR TITLE
Try: use `ariakit` for DropdownMenu v2, test it in block editor settings

### PR DESCRIPTION
**Pull request by ciampo**
## What?

This PR aims at investigating if [`ariakit`'s `Menu`](https://ariakit.org/reference/menu) can handle all edge cases that were flagged while working on the `radix-ui` version (see #51400)

## Why?

We want to provide a new version of `DropdownMenu`, supporting (among other things) nested submenus.

## How?

Things to look for:

- [x] when not modal, it aligns correctly with the toolbar even on iframed editor, both when resizing and scrolling the window
- [x] when modal:
    - [x] it doesn't interfere with other modal pieces of UI (ie. our own `Modal` component, command palette, any browser extensions like GTranslate)
    - [x] it doesn't break the copy-paste functionality
- [x] works correctly across slotfills, including nested submenus (ie. forwards context correctly)
- [x] supports links (ie. `<a />`) as menu items

### CODE REVIEW

**Comment by ciampo** [comment]
Good news! After [the latest `0.3.3` release](https://github.com/ariakit/ariakit/releases/tag/%40ariakit%2Freact%400.3.3) and some fiddling around with custom contexts and slotfills, all of the edge cases that I was testing for seem to be working fine, both in the editor and in Storybook.

Here's a quick video highlighting a nested dropdown menu across slotfills. Clicking on the nested items correctly opens our first-party modal. Focus is handled correctly too.


https://github.com/WordPress/gutenberg/assets/1083581/f3daa218-0fbe-460d-8436-eaaebdea0b25

**Comment by ciampo** [comment]
I'll start pulling out some updates from this PR and land them individually, starting from updating `ariakit` to the latest version: https://github.com/WordPress/gutenberg/pull/54818

**Comment by ciampo** [comment]
@diegohaz it would be great to have your eyes on the code in this PR, to make sure that the overall approach is correct (especially around using a custom react context to pass the store around the components, so that we can leverage it also in slot fills)

**Comment by andrewhayward** [comment]
> Clicking on the nested items correctly opens our first-party modal. Focus is handled correctly too.

Where does focus return to when the modal is closed? It looks like the submenu collapses when you click on "Create pattern", so I'm guessing not there!

Not a big thing right now, but something to think about as we progress.

**Comment by ciampo** [comment]
Good point! The video is outdated though, the problem should have been solved by [this commit](https://github.com/WordPress/gutenberg/pull/54612/commits/967bb1314059e37ab57b4873c06e0140de8452a0)

**Comment by ciampo** [comment]
Closing this PR as it only served as a quick way to check ariakit's compatibility with some aspects of the editor. Please follow #50459 for updates related to the next version of `DropdownMenu`.

**Pull request closed without merging**
