### PR TITLE
Preformatted block: Add color controls.

### LINKED ISSUE #28098: Preformatted block: Missing color controls
**We are adding typography and color controls to the text blocks that still do not have these features.**

This issue is focused on the Preformatted block that still needs color controls.

Screen Shot 2021-01-11 at 13 49 33

Associated issue:
**Consider adding color and text size customizations to all text-based blocks.**
#8171

### PR DESCRIPTION
**Pull request by juanfra**
## Description
Add color controls for the preformatted block. When the block is using background, I'm adding some padding. Fixes https://github.com/WordPress/gutenberg/issues/28098

## How has this been tested?
Tested using the block and changing colors while using twentytwentyone. 

## Types of changes

New feature (non-breaking change which adds functionality).

## Checklist:
- [ ] My code is tested.
- [ x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by paaljoachim** [comment]
Hi @juanfra Juan

Let us know how we can help.

**Comment by juanfra** [comment]
Hi @paaljoachim! 

Thanks for looking into this, I fixed the merge conflict. This is ready to be reviewed.

**Comment by paaljoachim** [comment]
Hi @juanfra Juan

Perhaps after this PR has been merged that you can continue with: 
File Block: Add background/text color support
https://github.com/WordPress/gutenberg/issues/18989

Thank you for your help in adding these controls!

**Comment by juanfra** [comment]
@paaljoachim sure! will try to find some time for that in the upcoming days.

**Review by gwwar — APPROVED** [review]
This tests well for me. Thanks for the contribution @juanfra !

**Comment by paaljoachim** [comment]
Hi @juanfra Juan

We need to make a correction to the File block I linked to. It needs Color and Typography controls (not only color controls). Just like the Buttons block here needs Color and Typography controls. https://github.com/WordPress/gutenberg/issues/29112

Thank you!

**Pull request merged**
