### PR TITLE
Add arrow-parens rule to eslint config

### LINKED ISSUE #611: Add eslint rule for lambda parameters
Which should we prefer?

```js
const func = param => value;
```

or

```js
const func = ( param ) => value;
```

I personally prefer the first style, but either way I think we should codify this into a lint rule.

### PR DESCRIPTION
**Pull request by noisysocks**
Closes #611.

Require that there are parens around the arguments of an arrow function. This option got the most :+1: reactions in https://github.com/WordPress/gutenberg/issues/611#issuecomment-298784132.

(I'm not that phased by this to be honest—it's just that I was in the neighbourhood while fixing https://github.com/WordPress/gutenberg/pull/6263.)

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Quickly! Merge it while nobody is looking! The bikeshed is coming!

**Comment by noisysocks** [comment]
mods are asleep, add parens!

**Comment by gziolo** [comment]
Nooooo 😱 I can no longer do my magic:
```js
param => ( { param } )
```
😃 
By the way, we can also disallow this shortcut for returning inline objects for readability:
```js
( param ) => {
    return { param };
}
```

This is something we try to encourage anyways.

**Comment by youknowriad** [comment]
@aduth 😆

**Comment by mtias** [comment]
First @pento sneaks a fundamental change to our ASCII art and now this...

**Pull request merged**
