### PR TITLE
Add aria-label to describe action of featured image update button

### LINKED ISSUE #10867: Provide proper label for featured image button
**Describe the bug**
The featured image button doesn't have a proper label for screen readers. It currently announces the alt tag of the image which is "Featured Image" by default.

**To Reproduce**
1. Activate screen reader
2. Set a featured image
3. Focus the button/image

**Expected behavior**
A clear description of what the button does should be announced.

**Additional context**
https://core.trac.wordpress.org/changeset/36000

### PR DESCRIPTION
**Pull request by ocean90**
## Description
Fixes #10867.

## How has this been tested?
Activate screen reader text and verify that the label "Click to edit or update the image" is announced.

Currently unsure if "Click to" is necessary or "Edit or update the image" would be enough.

### CODE REVIEW

**Comment by ocean90** [comment]
After looking at some of the other label, I removed the prefix in 68ae546 so it's consistent with other labels.

**Comment by youknowriad** [comment]
In case you didn't know about it and something we forget often (me included) is to add an entry in the CHANGELOG of the modified packages each time we do a change. This helps the person releasing the npm packages later. Thanks :)

**Comment by afercia** [comment]
Nice improvement @ocean90 👍 

See also the related #1520 / #10482 for further improvements. Rationale: in an editing context like an editor, users need to know _which_ is the image actually set. This is different from the purpose the image has in the front-end. #10482 tries to add a reference to the image alt (if set) or the image file with a wording along the lines of `This image has an empty alt attribute; its file name is %s`. Details still to refine.
In this case, I'd tend to think the same thing should be done for the button aria-label but it I guess it can be addressed in #10482 in a next iteration.

**Comment by ocean90** [comment]
@afercia Thanks for the feedback and the links to the issues!

Just to get it right, the label should mention the alt/name of the current selected image? I have set the actual `alt` attribute of the image to an empty since it was ignored by the screen reader (testing with macOS). If that's right, what about using `sprintf( __( 'Edit or update the image "%s"' ), alt || filename );` for the label?

**Comment by afercia** [comment]
> it was ignored by the screen reader 

Yes because the aria-label on the wrapping button _overrides_ the button content (which is the image alt)

> what about using sprintf( __( 'Edit or update the image "%s"' ), alt || filename ); for the label?

If the image has an alt empty attribute (which is perfectly OK in most of the cases) I'd rather consider to inform users explicitly, using some wording similar to the one proposed in #10482. Maybe consider some coordination between the two PRs?

**Comment by ocean90** [comment]
I'm just worried that the button's primary action gets lost when the string is too long.

**Comment by youknowriad** [comment]
What do we need to unblock this as it's state for 4.2. It's not technically API freeze, we can move for later but if It can be unblocked quickly, I'm fine keeping it.

**Comment by ocean90** [comment]
I think this can go in. Once #10960 is done I'm happy to improve the string if necessary.

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Code wise

**Pull request merged**
