### PR TITLE
Add --glob argument to rimraf cli scripts

### PR DESCRIPTION
**Pull request by sirreal**
## What?

rimraf now requires the --glob option, add it.
Use single quotes to avoid shell glob handling. It seems likely that some shells were handling the glob, but previously the glob was handled by rimraf. Single quotes should ensure that the glob is handled by rimraf everywhere.

https://github.com/isaacs/rimraf?tab=readme-ov-file#v3-to-v4

Follow-up to https://github.com/WordPress/gutenberg/pull/67708

[Windows builds started to fail, for example](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735):

```
> gutenberg@19.9.0-rc.1 clean:packages
> rimraf "./packages/*/@(build|build-module|build-wp|build-style)"

Error: Illegal characters in path.
    at pathArg (file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/path-arg.js:38:33)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/index.js:17:54
    at Array.map (<anonymous>)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/index.js:17:42
    at main (file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/bin.mjs:[24](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735#step:8:25)3:15)
    at file:///D:/a/wordpress-develop/wordpress-develop/src/wp-content/plugins/gutenberg/node_modules/rimraf/dist/esm/bin.mjs:[25](https://github.com/WordPress/wordpress-develop/actions/runs/12273327100/job/34243904735#step:8:26)1:5 {
  path: 'D:\\a\\wordpress-develop\\wordpress-develop\\src\\wp-content\\plugins\\gutenberg\\packages\\*\\@(build|build-module|build-wp|build-style)',
  code: 'EINVAL'
```

## Why?

This should work, the `--glob` option is now required.

## Testing Instructions

```sh
npm run build:packages
ls packages/interactivity
```

prints

```
build
build-module
build-types
src
CHANGELOG.md
README.md
package.json
tsconfig.json
tsconfig.test.json
tsconfig.test.tsbuildinfo
tsconfig.tsbuildinfo
```

```sh
npm run clean:packages
npm run clean:package-types
ls packages/interactivity
```

prints

```
src
CHANGELOG.md
README.md
package.json
tsconfig.json
tsconfig.test.json
```

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM! Thanks for the quick fix.

**Comment by gziolo** [comment]
Thank you for the follow-up. That's the risk of bumping dependencies to fix reported vulnerabilities ...

**Comment by sirreal** [comment]
There was progress, but this [still didn't fix the windows issue](https://github.com/WordPress/wordpress-develop/actions/runs/12277835641/job/34258166878?pr=7990) 😩 


```
> gutenberg@19.9.0-rc.1 clean:packages
> rimraf --glob './packages/*/@(build|build-module|build-wp|build-style)'

'build-module' is not recognized as an internal or external command,
operable program or batch file.
```

I'm not sure what the problem is with that… maybe we can use braces instead of the `@` pattern, although I think both should be supported.

@t-hamano are you able to reproduce the issue?

**Comment by sirreal** [comment]
https://github.com/WordPress/gutenberg/pull/67833 tries this with braces.

**Pull request merged**
