### PR TITLE
Testing: add e2e test for the HTML block

### PR DESCRIPTION
**Pull request by designsimply**
## Description
This PR adds a basic test for the Custom HTML block.

## How has this been tested?
`npm run test-e2e`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Looks great, thanks!

**Review by gziolo — APPROVED** [review]
🎉 

As far as I remember Pythagorean theorem looks legit 😄

**Comment by gziolo** [comment]
@designsimply, you should also open a follow-up PR and add yourself to https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTORS.md :)

**Comment by tofumatt** [comment]
Since this is just a test change I'm going to merge it in now as there's no harm in extra tests and it'll lighten the PR count 😅

**Pull request merged**
