### PR TITLE
Inserter: Autofocus the Search input

### PR DESCRIPTION
**Pull request by oskosk**
Makes the inserter menu autofocus on the input search. We can autofocus if the search input is on the top as the first focusable item. 

Related to #1064

#### Testing instructions

1. Run this branch
1. Click the "Insert" button
1. Expect the focus to be set on the search input.

### CODE REVIEW

**Comment by oskosk** [comment]
cc @mtias for review

**Comment by youknowriad** [comment]
This works great for me but I wondering if there're accessibility issues with this.

Not totally related: We should select the first block automatically and allow "type type + enter" to add the first selected block.

**Comment by nb** [comment]
We chatted with @afercia again today and we can autofocus if we move the search input to the top. If you think that will be a better experience, feel free to change to that, otherwise 👍 from me.

**Comment by aduth** [comment]
With the search input moved, we may also need to update this logic, which assumed that the search input would appear at the end of the inserter when keyboarding through the set:

https://github.com/WordPress/gutenberg/blob/19ecc2c/editor/inserter/menu.js#L92-L93

**Comment by youknowriad** [comment]
> We chatted with @afercia again today and we can autofocus

Should we change the logic here and just use the `autoFocus` prop instead of detecting alpha keys?

**Comment by oskosk** [comment]
@aduth indeed. Will update this. Thanks!

@youknowriad I think you're right. Autofocus was accepted if we moved the search input to the top

**Comment by mtias** [comment]
@oskosk can you rebase this so there are no conflicts?

**Comment by oskosk** [comment]
I've updated this PR (code, description and title) to just introduce the autoFocus prop on the search input and move it to the top of the inserter. 

Also removed the onKeydown behaviour for focusing the search input when a letter key is pressed. This turned out to be an unexpected behaviour in terms of accessible menu navigation. If pressing letter keys is to be implemented as a control for navigation it's expected that pressing the key, will focus the first item with text starting with that letter as detailed by [@afercia's research on menu navigation](https://github.com/WordPress/gutenberg/issues/1064#issuecomment-306906702).

**Review by youknowriad — APPROVED** [review]
Such a nice improvement. Ship it 👍

**Comment by afercia** [comment]
@youknowriad not sure if this is still needed `onClick={ this.setSearchFocus }` ?

**Comment by oskosk** [comment]
@afercia calling `setSearchFocus` updates a `currentFocus` var in the component's state which is used for later sequential navigation among blocks and the search input.

**Comment by oskosk** [comment]
@afercia thanks to your comment I ended up realizing that this state variable was being initialized as `null` instead of `"search"` which probably makes more sense since we're autofocusing it now. I've updated this PR to do this

**Comment by afercia** [comment]
Thanks @oskosk I see now `changeMenuSelection()` not only sets the focus but also updates the state.

**Comment by oskosk** [comment]
@afercia are you OK with merging this and handling the observations in #1378 afterwards ?

**Comment by afercia** [comment]
@oskosk Sure, I was just asking a question, not arguing anything.

**Comment by oskosk** [comment]
Oh, didn't parse it as arguing. I just wanted to bring the observations #1378 into this convo so you knew I'm aware of those :P

**Pull request merged**
