### PR TITLE
Use for...of loops more often.

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
JavaScript [`for...of` loops](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) are a lot easier to comprehend than classic `for` loops. ~And when we eventually drop IE11 support and stop transpiling them, they should also be a bit faster.~ This PR replaces classic `for` loops with `for...of` loops in every situation where it makes sense.

Side note: maybe we should consider adding a recommendation in the docs to prefer `for...of` loops where it makes sense to use them?

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Thanks for asking. :+1: I thought I'd tested this already in my own performance tests using jsbench.me, but I went ahead and checked again, and apparently the difference is within the tenths of a percentage (within or close to the margin of error), with `for...of` actually performing ever so slightly _slower_. (I tested in both Chromium and Firefox.)

Also, apparently `[].forEach` is actually faster than both in Chromium or just as good as either in Firefox.

**Comment by aduth** [comment]
I think it's probably a fine change. The value is a bit hard to determine:

- Pro: I could agree that these are easier to decipher once you have familiarity with both basic `for` loops and `for ... of` to be able to compare them.
- Con: That said, consider that the basic structure of a `for` loop is almost universally present across most programming languages, whereas something equivalent to `for ... of` isn't. It may be an unfamiliar construct to some new contributors.
- Pro: Performance-wise, it should be roughly equivalent, and maybe at some point in the future the runtimes can optimize for some advantage here?
- Con: Practically speaking, the Babel output can produce [some monstrous code](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAQzgMyhEcDkA6A9AzAbgChlo4AKOAYwgDsBneAKzgmUTgEo4BvAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=) which may very well be a huge regression in some performance-critical applications.

**Comment by ZebulanStanphill** [comment]
@aduth
> * Con: That said, consider that the basic structure of a `for` loop is almost universally present across most programming languages, whereas something equivalent to `for ... of` isn't. It may be an unfamiliar construct to some new contributors.

I think `for...of` equivalents are actually pretty common these days:

- C++: `for (auto item : list)`
- C#: `foreach (var item in list)`
- Java: `for (var item : list)`
- PHP: `foreach ($list as $item)`
- Python: `for item in list`
- Rust: `for item in list`

> * Con: Practically speaking, the Babel output can produce [some monstrous code](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAQzgMyhEcDkA6A9AzAbgChlo4AKOAYwgDsBneAKzgmUTgEo4BvAXyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=) which may very well be a huge regression in some performance-critical applications.

That monstrous Babel output is happening because `a` is not known to be an array. I wonder if that still happens when JSDoc type info is available?

If you try that example with a non-imported array, the output is much more reasonable:

```js
"use strict";

var a = [];

for (var _i = 0, _a = a; _i < _a.length; _i++) {
  var j = _a[_i];
}
```
But yeah, clunky Babel output is a good thing to keep in mind.

**Comment by aduth** [comment]
> I think `for...of` equivalents are actually pretty common these days:

Fair enough 😄 

> That monstrous Babel output is happening because `a` is not known to be an array. I wonder if that still happens when JSDoc type info is available?

I don't know off the top of my head, but I kind of doubt it. I also know that Babel operates on single files as a time, so it can't resolve or infer anything about the type of an array imported like this. It seems like it [struggles](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMOAnAogQwgCwBSKaqqYCeANIhJgDY0BG2A1ogJSIDeAUIsmogQgIAzlEQwoAUwC2iOMELEybTj15VaDZgQky2AbjUBfLia4oM2fIgDaiAIyUATJQDMiALqUCYENPqSqCoAvAB8VCJwNJIAdDRwAOY-fgFB7Kz6QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ces2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.9.6&externalPlugins=) even in simple cases of passing an array around as an argument.

I guess as it relates to changes here, we could do some balance of:

- Check the actual output
- Avoid `for ... of` in performance critical code if we care enough
   - Possible candidates:
      - `packages/block-editor/src/components/inserter/use-async-list.js`
      - `packages/blocks/src/api/children.js`
      - `packages/blocks/src/api/parser.js`
      - `packages/blocks/src/api/validation/index.js`
      - `packages/core-data/src/queried-data/get-query-parts.js`
      - `packages/element/src/serialize.js`
      - `packages/rich-text/src/create.js`
      - `packages/rich-text/src/is-format-equal.js`
      - `packages/rich-text/src/to-dom.js`
- Check the source to see if the array it's operating on would obviously be inferred as an array

Or we could just ignore this detail and eat any associated cost 🤷 

Aside: The reason I dwell here is that I feel that for this not to be [refactoring for refactoring's sake](https://make.wordpress.org/core/handbook/contribute/code-refactoring/), it becomes more important to sell the value of the changes. If this code were part of some other feature pull request, I probably wouldn't spend more than a passing moment contemplating `for ... of` vs. `for`, except in instances of highly performant code.

**Comment by ZebulanStanphill** [comment]
Given the messy Babel output, I no longer think this PR is worth pursuing. :disappointed: I'll probably still keep using `for...of` loops in refactor PRs for the sake of better readability, but at the moment, this PR mostly falls under "refactoring for the sake of it". Eventually, when we stop transpiling `for...of` loops, I think a bulk swap to `for...of` loops will be worth it. But for now, I'm closing this PR. Thanks for your feedback, @aduth.

**Comment by aduth** [comment]
It was a good exploration, definitely not wasted effort. Especially thinking in the future we can give more consideration here:

> Eventually, when we stop transpiling `for...of` loops, I think a bulk swap to `for...of` loops will be worth it.

Could even be something to pursue in the short/mid-term, via a double-bundle pattern using `@babel/preset-modules`.

https://github.com/babel/preset-modules

**Pull request closed without merging**
