### PR TITLE
Add comment-form and comment-list to default html5 theme support

### LINKED ISSUE #37464: Add `comment-form` and `comment-list` to default `html5` theme support (backport from WordPress Core for parity)
### Description

Follow-up to PR #35593.

 In WordPress Core's [changeset 52369](https://core.trac.wordpress.org/changeset/52369), two additional `html5` theme supports were added: `'comment-form'` and `'comment-list'`. This issue seeks to backport the changeset from Core to Gutenberg to resync for parity.

The difference between Gutenberg and Core causes differences in Twenty Twenty-Two's comm ents markup output and visual styling. See Core Trac ticket https://core.trac.wordpress.org/ticket/54625 for more details.

To resync with Core by adding the 2 additional supports in the `lib/compat/wordpress-5.9/default-theme-support.php file https://github.com/WordPress/gutenberg/blob/7cbba2646a522738fd95894db8240e4d3d5ac1d3/lib/compat/wordpress-5.9/default-theme-supports.php#L12-L18

### Step-by-step reproduction instructions

NA

### Screenshots, screen recording, code snippet

NA

### Environment info

NA

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Adds comment-form and comment-list to default html5 theme support for compatibility with core 5.9 and fixes comment layout issue caused by this change.

Fixes: #37464

## How has this been tested?
Ran 5.9 beta 3 without Gutenberg plugin and checked comment markup
Ran Gutenberg plugin on 5.8 with this PR applied and checked that comment markup matched 5.9 beta 3, and that comment layout was correct

## Screenshots

Before:
Screen Shot 2021-12-21 at 10 38 18 AM

After:
Screen Shot 2021-12-21 at 10 37 00 AM

Without the CSS change in this PR the comment avatar alignment is incorrect:
comment-bad

so check that these are in alignment with parent post width.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Thanks for adding this one in @glendaviesnz! This is testing nicely for me in blocks based themes (TwentyTwentyTwo and TT1-Blocks) and also tested to make sure there's no issues in a few classic themes (TwentyTwenty, TwentyNineteen, Maywood).

LGTM!

**Comment by glendaviesnz** [comment]
@hellofromtonya If this looks ok to you, do we just merge and add the backport tag to get the CSS change into 5.9?

**Comment by hellofromtonya** [comment]
Thanks for ping @glendaviesnz. The changes look good. Let me pull it down and see how TT2 renders. If all is good, then I'll approve in a couple of minutes.

**Review by hellofromtonya — APPROVED** [review]
Tested on Core's current `trunk`.  Removing the `margin-left` shifts the comments back into alignment. Ready for merge 👍 and backport

**Comment by hellofromtonya** [comment]
@glendaviesnz The PHP change resyncs with Core. The CSS change shifts the comments back into alignment. The package update will need to happen to backport the CSS to Core.

**Pull request merged**
