### PR TITLE
components: Remove duplicated compose dependencies

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
Because `compose` was untyped, we had originally duplicated the `useIsomorphicLayoutEffect` and `useInstanceId` hooks into the `components` package. This PR removes that duplication. It also upgrades the lodash type definitions used so we can use the `DebouncedFunc` utility type.

I also had to change the way that `flowRight` is imported because otherwise I was getting this error:

> Module '"../../node_modules/@types/lodash/common/util"' has no exported member 'flowRight'.

I have no idea how to solve this, it seems to be some kind of issue with the lodash type definitions. I don't know exactly what the implications are of how I changed it but it fixes that warning.

Maybe @jsnajdr @sirreal or @diegohaz one of y'all have any experience with the lodash definitions and why we can't import the `flowRight` from there to get a proper definition from it? To be clear, it seems that flowRight has a definition it's just not exported in the way we're using it. Maybe this is because we're not using `lodash-es`? 🤷 

## How has this been tested?
Type checks pass. No runtime changes save the changed lodash import.

## Types of changes
Janitorial clean up.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@gziolo The compressed size check is failing in this PR for the same reason. It is not properly cleaning the lodash version being used when checking out trunk so it ends up comparing trunk using the lodash version that is incompatible with trunk.

**Comment by sirreal** [comment]
> I also had to change the way that `flowRight` is imported because otherwise I was getting this error:
> 
> > Module '"../../node_modules/@types/lodash/common/util"' has no exported member 'flowRight'.
> 
> I have no idea how to solve this, it seems to be some kind of issue with the lodash type definitions. I don't know exactly what the implications are of how I changed it but it fixes that warning.
> 
> Maybe @jsnajdr @sirreal or @diegohaz one of y'all have any experience with the lodash definitions and why we can't import the `flowRight` from there to get a proper definition from it? To be clear, it seems that flowRight has a definition it's just not exported in the way we're using it. Maybe this is because we're not using `lodash-es`? 🤷

I've been looking into this a little bit and it seems to be a bug, I'm not yet sure where 🙂  I do have a few workarounds to propose.

## Analysis

The issue is with the generated declarations. Our `compose` package compiles just fine. It produces a declaration like this:

```d.ts
export default compose;
import { flowRight as compose } from "lodash/common/util";
```

It's when `components` parses `compose` types that it encounters this import and fails with the error message. It can be reproduced in Gutenberg by building the components types: `npm run build:package-types packages/components`.

Even better, a [minimal reproduction is trivial in the TypeScript playground](https://www.typescriptlang.org/play?filetype=js#code/PTAEBUAsEsGdQMYHsAmBTAUNAtgByQE4AuoA3qAGYA2SA7gErQDmkJAhvMnkrGqAL6UCSbKADkNFB0hiMaAB75iodBTYBXKiS75eGDCFD00sTUXjQAdqDbWcSkldBFIfNNmhEiaFCrQIqNgI2Imgka1gcaECCZyRnGFgALixuZXJqOkYWdk4RXTQAUQ8vHwEhEVAAIklpYC5scOB1UKoqgG4gA)!

Interestingly, this only happens when compiling JavaScript source, _not TypeScript_. [The same playground with TypeScript source emits a correct declaration](https://www.typescriptlang.org/play?ssl=6&ssc=53&pln=6&pc=54&filetype=ts#code/PTAEBUAsEsGdQMYHsAmBTAUNAtgByQE4AuoA3qAGYA2SA7gErQDmkJAhvMnkrGqAL6UCSbKADkNFB0hiMaAB75iodBTYBXKiS75eGDCFD00sTUXjQAdqDbWcSkldBFIfNNmhEiaFCrQIqNgI2Imgka1gcaECCZyRnGFgALixuZXJqOkYWdk4RXTQAUQ8vHwEhEVAAIklpKoBuIA):

```d.ts
import { flowRight as compose } from 'lodash';
export default compose;
```

## Workarounds

Given that the bug only manifests in JavaScript sources, a trivial workaround should be to rename this file to end in `.ts` and the problem should be solved.

Alternatively, with a true [ECMAScript modules re-export the problem does not seem to manifest](https://www.typescriptlang.org/play?filetype=js#code/KYDwDg9gTgLgBAbzgMwDYQO4CUCWBzAC3gEMBnOAE2GWIFdV4BfFKCAWzgHJ0KyDOgA). We should check how this impacts generated docs, but this can be rewritten as `export { flowRight as default } from 'lodash'`.

## Further analysis

It's not entirely clear why this happens. [`flowRight` _is_ defined in `lodash/common/util`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/698efc50d7eb92c0152e4459cec9c909a7068ebd/types/lodash/common/util.d.ts#L282), but it isn't exported. It's just attached to the LoDashStatic interface. [This is "included" in lodash types via declaration triple-slash reference.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/698efc50d7eb92c0152e4459cec9c909a7068ebd/types/lodash/index.d.ts#L25)

The fact that only JavaScript compilation causes this to manifest suggests it may be a bug in the TypeScript compiler.

**Comment by jsnajdr** [comment]
A possible solution would be to reimplement `compose` from scratch instead of re-exporting from Lodash. I tried that in #32734.

**Comment by sarayourfriend** [comment]
@jsnajdr while I like the idea of not just re-exporting something from lodash, the types are a huge pain to write for these functions. We could just copy and paste them from the lodash declarations though 🤷 I have no strong preference other than that re-writing compose seems like a lot of work and extra maintenance cost when we're already successfully building upon this re-export just fine.

@sirreal Thanks for the thorough investigation. It seems like it basically amounts to "I don't know why this is happening _exactly_ but..." Does the workaround I used not work? Or is the workaround you're proposing a better one for one reason or another?

Actually, scratch that. If we can just rename the file to `.ts` and fix this without having to make changes to how the import is declared then I'll try that.

**Review by ciampo — APPROVED** [review]
Tests well as per instructions 🚀  (also, thank you @sirreal and @jsnajdr for helping out!)

> It also upgrades the `lodash` type definitions used so we can use the `DebouncedFunc` utility type.

Just noting that this is not the case anymore after https://github.com/WordPress/gutenberg/pull/32709/commits/65749a46b4652a2252ec93ba91ba45008853cfc4

**Comment by jsnajdr** [comment]
> while I like the idea of not just re-exporting something from lodash, the types are a huge pain to write for these functions.

I writing many overrides for 1..N number of arguments still the only option? Or can some recent TypeScript define types recursively, like:

```ts
type compose( f: ( a: A ) => B, ...rest ) = ( b: Param< compose( ...rest ) > ) => B
type compose( f: ( a: A ) => B ) = ( a: A ) => B
```
? That would be awesome 🙂 

An advantage of home-grown `compose` is that for our use-case, i.e., composing one-parameter HOCs, it's literally an one-liner:
```js
( ...fns ) => ( a ) => fns.reduceRight( ( r, fn ) => fn( r ), a );
```

On the other hand, the Lodash implemenation is a bit of a monster. It supports multiple arguments for the first function in the chain, and also Lodash lazy wrappers (https://lodash.com/docs/4.17.15#lodash). We don't use that at all.

**Comment by sarayourfriend** [comment]
> Param< compose( ...rest ) >

This isn't valid TypeScript I don't think. There's no way to apply a function in the types as far as I know, even just to get the types out 🤔 

But I agree it would be awesome of it was possible.

**Comment by jsnajdr** [comment]
My intent was to write some TypeScript-ish pseudocode that illustrates the point 🙂 @sirreal shared privately some attempts to really write it down correctly.

**Comment by sirreal** [comment]
I left a typing submission over on the PR implementing a `compose` replacement: https://github.com/WordPress/gutenberg/pull/32734#issuecomment-865110451

**Pull request merged**
