### PR TITLE
List: add spacing block supports

### PR DESCRIPTION
**Pull request by ramonjd**
Related:
- https://github.com/WordPress/gutenberg/issues/43241
- https://github.com/WordPress/gutenberg/issues/43243

## What?

Enabling spacing support for the list block.

## Why?

To create consistency across blocks.

## How?

Adding the relevant block supports in block.json

## Testing Instructions

1. Load the block editor and add a list block. Add some list items or use the example block code below.
2. Confirm that the dimensions control panel is there.
3. Add padding and margin values to the list block.
4. Save and confirm the styles appear on the frontend. 
5. Test the new support works for the block via theme.json and global styles. See example JSON below.

<details>

<summary>Example blockcode</summary>

```html
<!-- wp:list {"style":{"spacing":{"padding":{"top":"var:preset|spacing|80","right":"var:preset|spacing|80","bottom":"var:preset|spacing|80","left":"var:preset|spacing|80"},"margin":{"top":"8.94rem","right":"var:preset|spacing|80","bottom":"var:preset|spacing|80","left":"var:preset|spacing|80"}}},"backgroundColor":"vivid-green-cyan"} -->
<ul class="has-vivid-green-cyan-background-color has-background" style="margin-top:8.94rem;margin-right:var(--wp--preset--spacing--80);margin-bottom:var(--wp--preset--spacing--80);margin-left:var(--wp--preset--spacing--80);padding-top:var(--wp--preset--spacing--80);padding-right:var(--wp--preset--spacing--80);padding-bottom:var(--wp--preset--spacing--80);padding-left:var(--wp--preset--spacing--80)"><li>Account</li><li>Agenda</li><li>Archive</li><li>Ballot</li><li>Bill</li><li>Calendar</li><li>Catalog</li><li>Checklist</li><li>Dictionary</li><li>Directory</li></ul>
<!-- /wp:list -->

```

</details>

```json
	"styles": {
		"blocks": {
			"core/list": {
				"spacing": {
					"margin": "66px",
					"padding": "122px",
				}
			}
		}
	}
```

Screen Shot 2022-08-19 at 2 19 44 pm

### CODE REVIEW

**Comment by glendaviesnz** [comment]
Not sure if it is an issue or not, but in TT2 the left and right margins applied in the editor get overridden in the frontend:
Screen Shot 2022-08-19 at 4 55 01 PM

**Comment by glendaviesnz** [comment]
Also, padding applied in global styles doesn't show in the editor, but does in frontend ... just going to check if that is an issue in general or just with this block

**Comment by glendaviesnz** [comment]
> Also, padding applied in global styles doesn't show in the editor, but does in frontend

ignore that, couldn't replicate after a page refresh.

**Comment by ramonjd** [comment]
> Not sure if it is an issue or not, but in TT2 the left and right margins applied in the editor get overridden in the frontend:


Thanks, I saw that too. 

It's being overwritten by `!important` layout styles where there is a layout content size: https://github.com/WordPress/gutenberg/blob/7f0a211da6603b336b75b75d8235a50bf547e6f3/lib/block-supports/layout.php#L60

I figured that it's still possible to do this: 

https://user-images.githubusercontent.com/6458278/185548933-ff07bb68-348d-4724-b5b9-dc6ec486d46d.mp4

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for putting this together @ramonjd 👍 

✅ Works as advertised in the editor
✅ Padding and margin are applied on the frontend
✅ Spacing can be set via theme.json and Global Styles 

As you [pointed out](https://github.com/WordPress/gutenberg/pull/43402#issuecomment-1220266813), there is a use case still for left/right margins. This is also consistent with other blocks that have recently added spacing support. So I think this should be ok to proceed with.

**Pull request merged**
