### PR TITLE
Support adding a human-readable deprecation hint

### PR DESCRIPTION
**Pull request by brandonpayton**
## Description
There are situations where it can be useful to add a helpful hint to deprecation warnings.

For example, in #6753, we deprecate `getFrecentInserterItems` and recommend  `getInserterItems` instead, but `getInserterItems` doesn't naturally sort items by frecency. The caller has to do that. It might be good to offer a clue for those transitioning away from `getFrecentInserterItems`.

Today, the deprecation warning would be:
> getFrecentInserterItems is deprecated and will be removed from Gutenberg in 3.1. Please use getInserterItems instead.

But we can provide additional useful information with a message like:
> getFrecentInserterItems is deprecated and will be removed from Gutenberg in 3.1. Please use getInserterItems instead. Note: For an equivalent list, you may sort inserter items by their \`frecency\` property.

This PR adds support for an optional `hint` argument to our `deprecation` util to include additional information in the deprecation warning.

## How has this been tested?
Added a unit test and ran the test suite successfully.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
I find it as a good addition to the API. In some cases `link` plays this role, but we don't always have a link to share.

**Comment by brandonpayton** [comment]
Thanks for the review and the fix to JSDoc formatting, @gziolo!

**Comment by noisysocks** [comment]
Is it OK that the hint won't be translated? (I think so, but just checking.)

**Comment by SuperGeniusZeb** [comment]
Should this be moved to the 2.9 milestone since it has been merged before the 2.9 release?

**Comment by brandonpayton** [comment]
> Is it OK that the hint won't be translated? (I think so, but just checking.)

Based on #6807, it is OK.

**Comment by noisysocks** [comment]
Oh! My mistake! I thought we were using `__` in `deprecated` but looks like that's been changed 😄

**Pull request merged**
