### PR TITLE
Block Editor Component: Fix function call in justify toolbar

### PR DESCRIPTION
**Pull request by mkaz**
## Description

The onChange function in the Justify Toolbar was calling the function on render instead of registering the function onClick, it needed to be wrapped in a function call. This added complexity was missed in the consumers of the component since they were wrapped in an extra function call. This PR fixes the issue and corrects the downstream consumers, simplifying the implementation.

This will likely also fix the issue in #28893 

## How has this been tested?

There should no visible change when using.

1. Test by adding Navigation links and changing items justification (align left, right, center, space-between)
2. Test by adding Buttons and changing items justification (align left, right, center) 

## Types of changes

Fix function call in component

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for keeping on this. The behavior is subtle and a bit gnarly, so let me start with a couple of GIFs. Master branch:

master

Notice how when you start out fresh, the navigation block **has no justification**. No choice has been made. It looks left aligned, because that's what the block (but it could've been the theme) provides out of the box.

You can then **explicitly** set justifications left, center, right, or space between. 

Here's this branch:

this branch

In comparison, here you cannot unset a justification. Once you've set a justification, it's locked to that justification.

The subtle question here is: if it's left aligned by default, why not just have that property be toggled by default? Two answers:

1. So the theme can provide a default justification. For example the theme might want to justify the navigation block right.
2. So the user can explicitly set a justification of their choice. Maybe the user doesn't like that the _theme_ justifies the navigation right, so they can explicitly justify it left. 

So it speaks to the style hierarchy:

- Block defaults to justifying left.
- - Theme defaults to justifying right.
- - - User can explicitly set it to justify left again. 

Make sense?

This brings us a matrix where each block that has justification controls actually has 5 options — "unset" in addition to the 4 others.

**Comment by mkaz** [comment]
Thanks @jasmussen that explanation makes sense.
I just pushed up a fix that handles the deselect it in the control itself, it'll make it easier for each consumer to not have to implement, which simplifies the implementation @ntsekouras pointed out in another PR.

**Comment by jasmussen** [comment]
Having pulled the latest, here's what I see:

latest

To me this looks like correct / desired behavior. I'll defer to a code review, but behavior wise this seems 👍 👍 to me!

**Review by ntsekouras — APPROVED** [review]
Thanks @mkaz - looks good 👍

**Pull request merged**
