### PR TITLE
Cover block: update Dimensions panel label to avoid duplicate

### PR DESCRIPTION
**Pull request by ramonjd**
## Description

The [dimensions panel](https://github.com/WordPress/gutenberg/pull/32392/files) is merged. 🎉 

It includes controls such as padding, margin and, soon, height, width and minimum width. 

The Cover block currently has padding support, so it now has a dimensions panel. 

But it also features an existing dimensions block, under which it has a minimum height control. 

All this means is that there are now two "Dimensions" blocks.

A couple of initiatives that address this issue are underway:

- https://github.com/WordPress/gutenberg/pull/34008 (which adds [min-height block supports](https://github.com/WordPress/gutenberg/pull/33970 ))
-  https://github.com/WordPress/gutenberg/pull/34065

These are still in progress.

So until we can come up with a definitive approach to replace the Cover block's existing Dimensions block, either by activating minimum heights block supports or via SlotFills or otherwise, let's update the copy to remove the duplicate labels before the next release.

**Dimensions** has become... wait for it... **Minimum height**. I'm open to ideas :) We don't need to fret about finding an overarching term since the minimum height control will be shifted to the dimensions ToolsPanel.

❗ I've also included screenshots for an optional change to the mobile copy (but not the changes in code). The duplication does not affect mobile for now, but it's an open question as to whether we change it everywhere to remain consistent or to leave out mobile copy changes.

## How has this been tested?
Eyeballing.

## Screenshots 

Desktop!

Before | After
------------ | -------------
Screen Shot 2021-08-17 at 2 23 54 pm | Screen Shot 2021-08-17 at 2 13 57 pm

Mobile!

Before | After
------------ | -------------
Screen Shot 2021-08-17 at 2 19 33 pm | Screen Shot 2021-08-17 at 1 58 37 pm

## Types of changes
Copy changes.

### CODE REVIEW

**Comment by ramonjd** [comment]
In the interests of avoiding duplicate labels before the release, here's a copy update to the existing Cover block dimensions panel label

#34102

**Comment by jasmussen** [comment]
Thanks for tackling the challenge, definitely something we'll want to solve. 

@mtias came with [a suggestion yesterday](https://github.com/WordPress/gutenberg/issues/28356#issuecomment-899587151) which might be relevant to this conversation, which is that spacing related tools like margin and padding might not be a good fit for a "Dimensions" panel after all. That in fact, maybe they should be part of another panel, either Layout or just keep Spacing.

So that could be one part of the solution, move the margins and padding controls to a Layout panel. 

The other part is that the minimum height really _is_ related to the dimensions panel so ideally we move it to that panel and make it on by default for the cover block. I can't think of a situation where a block would have both _height_ and _minimum height_, so blocks would have to opt into one or the other as part of the dimensions panel. But both feel valid and are related to the block dimensions.

What do you think?

**Comment by aaronrobertshaw** [comment]
Thanks for highlighting the potential change in direction @jasmussen 👍 

> That in fact, maybe they should be part of another panel, either Layout or just keep Spacing.

Given I made the recent changes to rebrand spacing support to dimensions, I'd be happy to take care of this. I'll comment to that effect on the linked issue. 

If we can make that change before the next release it will take the pressure off needing either to add `min-height` block support or complete a SlotFill solution for injecting controls into the Dimensions panel.

**Comment by ramonjd** [comment]
> So that could be one part of the solution, move the margins and padding controls to a Layout panel.

Yes! That could also be alternative. Thanks also for alerting us. 🙇 

> If we can make that change before the next release it will take the pressure off needing either to add min-height block support or complete a SlotFill solution for injecting controls into the Dimensions panel.

Let us know where we can jump in to help with reviews. One of our four (?) approaches probably needs to land before release day. 

After that we'd hopefully have a bit of time to switch the Cover block over to the Dimensions ToolsPanel. 

Cheers! 👍

**Comment by kristastevens** [comment]
Hi @ramonjd — thanks for the the copy review ping. Removing copy duplication looks good to me.

**Comment by ramonjd** [comment]
We can close this if https://github.com/WordPress/gutenberg/pull/34065 gets off the ground.

**Comment by ramonjd** [comment]
https://github.com/WordPress/gutenberg/pull/34065 has been merged.

**Pull request closed without merging**
