### PR TITLE
Try clickthrough to edit template part children.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Explores ideas suggested in #29337 to require a 'clickthrough' flow to edit the contents of a template part.  Currently this is only set up for template parts, but the idea would be to expand this to reusable blocks as well.

click-through-test

At this point what do we think of the interaction and styles?  What can we refine about this or what else do we want to try?  Do we want to keep the highlight color idea, and what different colors would we actually want to use for template parts vs. reusable blocks? etc. 

Note - one of the challenges with this flow is the behavior of the popover inserter.  To get around this I have added selectors to disable/enable the popover inserter and used them such that when we are hovering a template part that is not selected/child-selected the popover inserter becomes disabled and does not appear and break the hover/click-through interactions.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by lweathermon — APPROVED** [review]

**Comment by jameskoster** [comment]
One (hopefully) small change – the green overlay should appear when the template part is selected rather than on hover, and it should be 10% opaque. It should disappear when an innerblock is selected (this part is working fine :))

**Comment by Addison-Stavlo** [comment]
>  the green overlay should appear when the template part is selected rather than on hover, and it should be 10% opaque. 

Updated, how does that feel now?

**Comment by paaljoachim** [comment]
This is what I see:

https://user-images.githubusercontent.com/5323259/112545189-35244380-8db8-11eb-8140-0c44afe8a30f.mp4

1. User clicks a template area/reusable block/Group/Column actually any container that contains inner blocks. Ok that might be taking it too far...user clicks template area or a reusable block.
Top container/block (parent is selected).

Screen Shot 2021-03-25 at 22 22 21

2. User clicks into the area they want to edit.

Screen Shot 2021-03-25 at 22 23 03

What is comforting with the above method is that the user first gets to see the Template area. What it contains, and is then able to see the boundary of what is inside this container. Gaining an overview.
The user can easier click into the container knowing it is the header template and that they want to modify a block inside of it.

**Comment by paaljoachim** [comment]
Btw

@Addison-Stavlo Addison. Thanks for working on this feature. This will likely be backported to WP 5.7.1 in relation to this trac ticket: https://core.trac.wordpress.org/ticket/52873

Here is what Dan mentioned in the above ticket:
"Since 5.7 though, a reusable block can be directly edited. There's no separate edit mode. It might be that you were accidentally removing the block inside the reusable block if you had the wrong block selected, and then saving that change would update the reusable block everywhere."

By merging this PR. Clicking the reusable block and then clicking the delete or backspace key will delete the reusable block from the page, and not the block inside the reusable block.

We will then be taking care of 1 of the 2 issues that are now up in relation to reusable blocks.

@talldan @peterwilsoncc

**Comment by talldan** [comment]
@paaljoachim This PR is for template parts, but I guess you mean if a similar PR were made for reusable blocks. I don't know that backporting to 5.7.1 will be possible, as such a change would be an enhancement and not a small one. Generally only bug fixes end up in patch releases.

**Comment by Addison-Stavlo** [comment]
> This PR is for template parts, but I guess you mean if a similar PR were made for reusable blocks. 

@talldan I would be happy to extend this to reusable blocks as well if it ends up being the behavior we want.  The two behave very similarly in the editor and the original design issue requests this flow for both.  Although, I will note that @jameskoster mentioned wanting to explore an alternative to this by leveraging 'select' mode in some way.  So Im holding back on this a bit as that is explored and design decides the best way to proceed.

**Review by jameskoster — CHANGES_REQUESTED** [review]
I made a couple of adjustments

- Rebase to pull in latest outline styles
- Added an overlay on hover with color matching the outline
- Made the selected overlay blue to match the outline (I need some help to opacify the theme color) :D 

I still think the green treatments for template parts makes sense, but we should probably do all of that work together as there are several considerations outside the scope of this particular PR.

One strange bug I noticed – it is possible to bypass the click-through entirely with the Site Title block:


https://user-images.githubusercontent.com/846565/113998901-69d0da00-9851-11eb-88b7-ef70231ebcab.mp4

A couple of additional thoughts:

- We can probably eliminate some noise in the UI by removing the spotlight effect on template part selection. The overlay + dotted outline essentially does the same job so I don't think we need it any more.
- Is there any way we can make the overlay behave like an actual overlay? It currently sits _behind_ the block contents and the illusion of an overlay is lost when something like an image is present. I thought about making the innerblocks semi-opaque when the template part is selected but perhaps there is a better way?

**Comment by paaljoachim** [comment]
~~I am wondering if we should create a new PR for the click through for Reusable blocks?
The reasoning is if we can make a "tiny" fix to Reusable blocks to create a click-through which could be added to WP 5.7.2.
See this question: https://wordpress.slack.com/archives/C02RQBWTW/p1617828736045000
Is this possible @talldan and @peterwilsoncc?~~

~~EDIT:
My reasoning is that it will make it just a little harder making accidental changes to the Reusable block when there is a clickthrough for Reusable blocks.~~

The most important part is just getting this into the Gutenberg plugin so we can test it out.

**Comment by Addison-Stavlo** [comment]
> One strange bug I noticed – it is possible to bypass the click-through entirely with the Site Title block:

I think I noticed it with any text element.  A standard 'click' doesn't seem to bypass it, but if you 'click' over an editable piece of text AND move the mouse while it is clicked (even so slightly as to not notice) it selects the block containing the editable text - so the initial 'click' unlocks the clickthrough, and the mouse move then triggers text selection which in turn selects the block the text is a part of.

> Is there any way we can make the overlay behave like an actual overlay?

Yeah I think we could create an actual overlay element and fix its position over the entire content of the template part (as opposed to leveraging the CSS for the elements that already exist as is done here).  It'l be a little less simplistic but I think it should fix the bug you pointed out regarding clicking on text inputs.

**Comment by paaljoachim** [comment]
From @Addison-Stavlo comment it seems like the next step is to create an overlay. Call it the lid on the box. So one clicks the overlay (opens the lid) and then has access to the contents inside. 

Btw lets also get this in for Reusable blocks, as it would be very helpful for users. It would make accidental changes just a bit harder to do. 
https://wordpress.slack.com/archives/C02QB2JS7/p1618936564028400

**Comment by Addison-Stavlo** [comment]
> Call it the lid on the box. So one clicks the overlay (opens the lid) and then has access to the contents inside.

That sounds about right!

> Btw lets also get this in for Reusable blocks, as it would be very helpful for users. 

Il aim for that case as well.  I hope to get back to this PR shortly.

**Comment by Addison-Stavlo** [comment]
Trying that element overlay approach here - https://github.com/WordPress/gutenberg/pull/31109 - it should be working pretty well in terms of selection and overlay style, but im still battling against some resizing issues.  (pardon splitting the PR, but I was running into a handful of difficulties and figured I would leave this one in its current state in case it made more sense to try to polish this approach instead.)

**Comment by Addison-Stavlo** [comment]
Closing this PR in favor of  #31109  - we can keep iterating over there.

**Pull request closed without merging**
