### PR TITLE
[Mobile] Removes Preview editor mode

### LINKED ISSUE #3217: Remove Preview mode from Gutenberg editor
## Description
The [editor preview mode introduced for the layout picker preview functionality]( https://github.com/wordpress-mobile/gutenberg-mobile/issues/2452) should be removed since it is being [replaced with a webview implementation](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2980).

### Solution
The changes introduced with the following PRs should be reverted
* https://github.com/WordPress/gutenberg/pull/25661
* https://github.com/WordPress/gutenberg/pull/25930
* https://github.com/WordPress/gutenberg/pull/25200

Note that some changes have been refactored with https://github.com/WordPress/gutenberg/pull/27640

### PR DESCRIPTION
**Pull request by antonis**
This should be merged after https://github.com/wordpress-mobile/gutenberg-mobile/issues/2980 is complete on both platforms

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/3217

**`gutenberg-mobile` PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3268
**`WordPress-Android` PR:** https://github.com/wordpress-mobile/WordPress-Android/pull/14270
**`WordPress-iOS` PR:** https://github.com/wordpress-mobile/WordPress-iOS/pull/16155

## Description
This PR removes the [editor preview mode introduced for the layout picker preview functionality]( https://github.com/wordpress-mobile/gutenberg-mobile/issues/2452) that is being [replaced with a webview implementation](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2980).

The changes introduced with the following PRs should are reverted
* https://github.com/WordPress/gutenberg/pull/25661
* https://github.com/WordPress/gutenberg/pull/25930
* https://github.com/WordPress/gutenberg/pull/25200
 
Note that the refactoring introduced with https://github.com/WordPress/gutenberg/pull/27640 has been considered

## How has this been tested?
Quick sanity of the editor to validate that no functionality is unintentionally broken
You can use the build from https://github.com/wordpress-mobile/WordPress-Android/pull/14270

## Types of changes
Code cleanup

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by antonis** [comment]
Leaving this in draft state till we test that nothing breaks on both platforms

**Comment by mkevins** [comment]
I think we can also remove these:

https://github.com/WordPress/gutenberg/blob/3cc64c0e5325fca8b037f1518c23bbadac681640/packages/react-native-bridge/ios/GutenbergBridgeDelegate.swift#L127

https://github.com/WordPress/gutenberg/blob/3cc64c0e5325fca8b037f1518c23bbadac681640/packages/react-native-bridge/ios/GutenbergBridgeDelegate.swift#L134-L136

https://github.com/WordPress/gutenberg/blob/da8555d258edbe676fa079fb51252f918ae032e1/packages/react-native-bridge/index.js#L24

**Comment by antonis** [comment]
Thank you for reviewing this @mkevins 🙇 

> I think we can also remove these:

I completely missed this part both on iOS and Android. I removed this with 971694d8d5bc2336c5245f806dfe460dbfaaf0c8

**Comment by mkevins** [comment]
Hi Antonis! :wave: :smile: 

I've reviewed and tested this, and everything is working as expected (I found no regressions). The code changes look good. I also began the same removal on the iOS side (WordPress-iOS) and explored a bit further. I think we can remove a few more things, since after removing the template preview event logging code, the only remaining part is the template apply. I investigated that, and I believe it is also ripe for removal. This also allows us to also remove the interface methods that are only in being utilized for this purpose, as well as a few switch cases.

Since these changes are a bit larger, I decided not to push them directly, in case you had some thoughts about it, so instead I've opened some PRs with these respective PRs as a base (the WordPress-iOS PR is the only one I opened that targets `develop` directly). I've tested the aggregate changeset on both WordPress apps as well as both demo apps, so feel free to merge those directly to these branches if you approve them.

**Comment by antonis** [comment]
Hey @mkevins 👋 

Thank you for stepping forward and helping with the code cleanup 🙇 

> Since these changes are a bit larger, I decided not to push them directly, in case you had some thoughts about it, so instead I've opened some PRs with these respective PRs as a base (the WordPress-iOS PR is the only one I opened that targets `develop` directly). I've tested the aggregate changeset on both WordPress apps as well as both demo apps, so feel free to merge those directly to these branches if you approve them.

I reviewed and merged the PRs that targeted my branches. I also reviews the IOS PR and everything looks good 🎉 
I think we can proceed with the merge domino :)

**Review by chipsnyder — APPROVED** [review]
This looks good to me 👍 Thanks for taking care of cleaning up the old interface :shipit:

**Pull request merged**
