### PR TITLE
Iframe tablet and mobile device previews

### LINKED ISSUE #21193: Mobile/Tablet/Desktop Previews do not work with externally loaded CSS
**Describe the bug**
On wordpress.com we use stylesheets loaded from `s0.wp.com`, `s1.wp.com` for various plugins such as full-site-editing.
When we install the gutenberg plugin and use the mobile preview, some of the css still behaves as if in desktop mode, so we see columns on mobile preview etc.

image

**To reproduce**
1. Install a plugin that loads styles from an external domain with mobile breakpoints (tested with the `full-site-editing` plugin)
2. Open the gutenberg editor and attempt to mobile preview

**Expected behavior**
The columns should be stacked for mobile display. Preview should render as if in a mobile device.

**Additional context**
From our initial investigation, here is what appears to be happening: 
Our current understanding of what's happening:

Mobile/tablet preview uses the `use-simulated-media-query` function which works by modifying the loaded stylesheets to simulate being viewed on mobile/tablet breakpoints.

This works for stylesheets loaded from the same domain. However, on `wordpress.com`, the static domains `s0.wp.com` and `s1.wp.com` are used to serve many stylesheets such as those from the `full-site-editing-plugin`.

These stylesheets are therefore rendered in desktop mode even when using mobile/tablet preview.

calypso issue: https://github.com/Automattic/wp-calypso/issues/40401

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #21193.

* Fixes the long standing issue of font-sizes (among other things) not adjusting based on the preview viewport dimensions.
* Removes the no longer needed media query simulation.

|Before: incorrect font size|After: correct font size|
|-|-|
|Screenshot 2021-07-10 at 21 17 25|Screenshot 2021-07-10 at 21 17 42|

|Before: incorrect padding|After: correct padding|
|-|-|
|Screenshot 2021-07-10 at 21 24 31|Screenshot 2021-07-10 at 21 24 18|

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
This is great, do you think there's a way to detect block failures and have a nice message like: "This block doesn't support rendering in frame, meaning it's not possible to render them in device previews".

Would that even be desirable?

**Comment by youknowriad** [comment]
I guess it's not easy to know if it's an iframe issue or not

**Comment by ellatrix** [comment]
Right, it's hard to tell. I think in most cases, they block will render, but it could look strange (due to something not initialising for example). We'll have to see what kind of problems we get with the release of the template editor in 5.8.

**Comment by gwwar** [comment]
Should we move this to the 11.2 milestone?

**Comment by youknowriad** [comment]
yeah ideally, we should leave milestone empty on PRs and let the auto-assign bot do its work post merge.

**Comment by ellatrix** [comment]
Let's merge this. This is necessary to push forward with the iframe and increase visibility to get more testing. I'll be on the lookout for any issues introduced. The device previews are not a super essential feature, so it's fine if a block has problems previewing so that we or plugin authors can identify the issues and fix them.

**Comment by niklasp** [comment]
I have an issue with the new iframe previews and my block. Is there any guide on how to make sure blocks work? My styles are broken in the iframe as well as the js initialization i guess.

**Comment by niklasp** [comment]
@ellatrix it seems all the `#start-resizable-editor-section` markers were removed, how do I now style the block in the preview?

**Pull request merged**
