### PR TITLE
Input Control: Set a color

### PR DESCRIPTION
**Pull request by scruffian**
## Description
When a theme sets a color for form elements, this gets inherited by text control. If the theme uses a dark background and white text for form elements, then it becomes unreadable:

Screenshot 2021-10-08 at 21 05 18

This PR sets a dark color for text inside input controls, so it looks like this:
Screenshot 2021-10-08 at 21 05 32

I have used `!important` to make sure that the theme styles do get overridden. I'm not super keen on this solution as it feels very heavy handed. My preference would be [this fix](https://github.com/WordPress/gutenberg/pull/33494), but maybe a quick fix is worth it?

## How has this been tested?
Checkout the videomaker theme and add a table block.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by mirka** [comment]
> I'm not super keen on this solution as it feels very heavy handed.

I'm afraid I agree, this would be a breaking change on a rather widely-used mixin.

I don't know what the "videomaker theme" is so I can't talk about it specifically, but would it be unreasonable to expect theme authors to not add such broad rules (e.g. `input { color: white; }`) to their style-editor.css if they don't mean it? And what if they _do_ mean it, and want to change the input styles even inside block placeholders?

I kind of think the responsibility/flexibility is in the hands of the theme author. They can scope the `input` rule appropriately, or reset the color inside the `.components-placeholder` scope.

**Comment by scruffian** [comment]
What scope should theme authors to target `input` elements if they want consistent styling across form elements in their theme?

**Comment by mirka** [comment]
> What scope should theme authors to target `input` elements if they want consistent styling across form elements in their theme?

Until there is a [clear contract](https://github.com/WordPress/gutenberg/issues/29167#issuecomment-953005663) between block authors and theme authors, I don't think there's a foolproof way that will work as expected for every block. Especially when third-party blocks are involved, there's no way to tell programmatically whether a given `input` is safe to be themed in a certain way. (Not just color, but size, borders, etc.)

Under the current circumstances, I would scope it under specific `wp-block-*` classes that I have manually verified to work. Not saying that is ideal, but personally that is how I've been approaching it. I think that's the only way to ensure that your theming is appropriate/sufficient.

In your input color case specifically, another option might be for the theme to set `input { color: inherit; }`.

**Comment by scruffian** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/33494

**Pull request closed without merging**
