### PR TITLE
Remove `gutenberg-mobile` submodule while issues are sorted out

### PR DESCRIPTION
**Pull request by danielbachhuber**
See conversation in https://wordpress.slack.com/archives/C02QB2JS7/p1540991140262200

See also #11144

### CODE REVIEW

**Comment by youknowriad** [comment]
The issues are not happening consistently. I'd be fine with removing but I prefer if we give the mobile team some time to figure it out and see if it can be improved.

**Comment by danielbachhuber** [comment]
>  prefer if we give the mobile team some time to figure it out and see if it can be improved.

Can we please remove for now, and then restore when it's improved? As it stands, it's blocking the development workflow for multiple people.

**Comment by danielbachhuber** [comment]
I sorted my more immediate problem by including `npm run mobile-submodule-update` in my build script.

**Comment by earnjam** [comment]
`Gutenberg` includes `gutenberg-mobile`, which includes `gutenberg`, which includes `gutenberg-mobile`, which includes `gutenberg`

image

Seems like there has to be a better way

**Comment by youknowriad** [comment]
I know it's not great but my point is that we should try to be inclusive with the mobile team. Including their tests mean we don't break mobile inadvertently. We're all on the same boat, we should try to merge the repositories I think. 

That doesn't mean we can't do quick wins for now.

**Comment by youknowriad** [comment]
I personally prefer this approach for now https://github.com/WordPress/gutenberg/pull/11304

**Comment by danielbachhuber** [comment]
> I personally prefer this approach for now

Yep, seems fine.

**Pull request closed without merging**
