### PR TITLE
Color Palette: Fix the active color using the value prop

### PR DESCRIPTION
**Pull request by youknowriad**
This fixes the first part of #2324

Also fixes some React Warnings when the color was unset.

### CODE REVIEW

**Comment by aduth** [comment]
When creating a Cover Text block, adding text, selecting colors, and refreshing, the block shows as externally modified.

**Comment by youknowriad** [comment]
weird @codecov this doesn't affect the coverage in theory (probably related to #2354)

**Comment by aduth** [comment]
Oh, I see the issue, though dunno if we want to address here. This is causing the cover block to be saved with `<p class="false">` in some cases?

https://github.com/WordPress/gutenberg/blob/a0714e2d85e9c985a9059b45e7f984d3fc780e63/blocks/library/cover-text/index.js#L134

**Comment by youknowriad** [comment]
@aduth Yeah, unrelated to this PR, I can fix it separately

**Review by aduth — APPROVED** [review]

**Pull request merged**
