### PR TITLE
[RNMobile] Add navigation to link settings and add link picker screen to block settings

### PR DESCRIPTION
**Pull request by dratwas**
GB mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2742

In this PR i added a link picker screen to the link settings. It is used in Button and Social Icons.
I also added the navigation inside the BottomSheet for LinkSettings with `withBottomSheet` set to true.

There is also a prop  in LinkSettingsNavigaiton `hasPicker` to determine if we would like to use link picker or regular text input

## How has this been tested?
Case 1:
- select Button block
- open block settings and click on the link URL
- the new screen should be pushed
- test it the same as regular link picker

Case 2:
- select Social Icon block
- open link settings
- the default text input should be used instead of pushing a new screen

## Screenshots 
link-picker

## Types of changes
New Feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by lukewalczak** [comment]
Tested on both platforms and looks properly, didn't notice anything odd. It's a nice feature :tada:

**Review by mkevins — COMMENTED** [review]
Reviewed and tested, and this is looking good. One thing that came to mind while testing for social icons.. do we _want_ to use the link picker for that? At the moment, the link picker suggestions are for the selected site, and so perhaps may not be appropriate for the various social links. Wdyt?

Also, I tried with the image block link settings, but the link picker does not seem to be wired up to the block settings for that block. Is this expected and/or something we will address in a later PR?

**Comment by dratwas** [comment]
> One thing that came to mind while testing for social icons.. do we want to use the link picker for that? At the moment, the link picker suggestions are for the selected site, and so perhaps may not be appropriate for the various social links. Wdyt?

Hmmm, good question. I agree with you that maybe I should create 2 kinds of link-settings - with link picker and w/o link picker. Then we could determine by one prop if we would like to use settings with picker or settings with text input.

> Also, I tried with the image block link settings, but the link picker does not seem to be wired up to the block settings for that block. Is this expected and/or something we will address in a later PR?

The image block has its own picker in edit.native.js file so it doesn't use the same component like a button and social links. I believe it should be changed but in a separate PR.

**Comment by mkevins** [comment]
> Hmmm, good question. I agree with you that maybe I should create 2 kinds of link-settings - with link picker and w/o link picker. Then we could determine by one prop if we would like to use settings with picker or settings with text input.

This sounds like a good solution.

> The image block has its own picker in edit.native.js file so it doesn't use the same component like a button and social links. I believe it should be changed but in a separate PR.

Ok, thanks for confirming that. :+1:

**Comment by dratwas** [comment]
Hey @mkevins

>This sounds like a good solution.

I already added a prop called `hasPicker` and set it to true for button block. The social icon link settings should work as before.

I also created an issue to remember that it should be used for the Image block as well and assigned myself.

**Comment by mkevins** [comment]
Hi @dratwas :wave: :smile: 

I tested again with the changes, and it's working as expected with regard to the button and social blocks. Nice work!

One thing I noticed, not sure if it's related to this PR, is that the block inserter had some overflow:

**Comment by dratwas** [comment]
Thanks, @mkevins for the review.

>One thing I noticed, not sure if it's related to this PR, is that the block inserter had some overflow:

Oh yeah, I created a fix for this here: https://github.com/WordPress/gutenberg/pull/26722

Basically, it was the latest change in the previous PR but I didn't notice that the `safeAreaBottomInset` is set to 0 and the default value doesn't overwrite it. I reverted that change and it should work fine :)

**Review by mkevins — APPROVED** [review]
Tested again with the lastest change and confirmed it's fixed. Nice work! LGTM!

**Pull request merged**
