### PR TITLE
Update: scrollable component popover

### PR DESCRIPTION
**Pull request by senadir**
closes following issues:
#10905
#16028

closes following PR:
#16113

it builds upon & fixes problems & review points in  #16113
fixes some issues with the component popover not having overflow scrolling when the list is long

it's basically a simple code refactor to factor in some review problems, it also adds flexbox support to the component to remove the need for `overflow: visible` and having problems with long lists of preview options.

better-previews

### CODE REVIEW

**Comment by senadir** [comment]
@mtias @jasmussen @getdave 
this should close the other PR, I wanted to push directly to that PR but I couldn't, not sure, a permission problem. anyway I guess opening a new PR was needed because this solves another problem

**Comment by youknowriad** [comment]
Can't we extract the popover changes to their own PR and target master? Why does it need the #16113 branch?

**Comment by senadir** [comment]
this PR was built on top of the changes that @jasmussen & @getdave did in #16113, so they relay on that PR but they introduce other changes that are parallel to it like the scroll fix

**Comment by senadir** [comment]
closing this in favor of #16824 
a minimal version that doesn't include the changes from #16113 so it can be merged

**Pull request closed without merging**
