### PR TITLE
Button: Try improving padding for icon + text buttons.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

Primary and secondary Buttons have an awkward padding when both an icon and text is provided. You can see this in [Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=icon:more;iconPosition:right;variant:primary), or in this PR: #46014:

before

By default, the button has 6px top/bottom padding, 12px left/right padding. But when a button `has-icon`, that padding becomes a blanket 6px:

padding

This PR fixes it, by providing a 12px _right_ padding, baked in:

after

Adding this padding, at a glance, seems safe enough since the code a few lines down applies the following:

```
		&.has-text svg {
			margin-right: $grid-unit-10;
		}

		&.has-text .dashicon {
			margin-right: $grid-unit-10 + 2px;
		}
```

That is, the component already assumes a left to right reading direction, with the icon on the left. 

I haven't been able to test, however it seems like this would break in RTL contexts. Furthermore, the button component appears to have an `iconPosition` prop, which at the moment seems to do nothing — even if set to right, the icon still shows up on the left: https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=icon:more;iconPosition:right;variant:primary

As is, this PR will improve things for primary and secondary buttons, and does not tackle the problem of RTL or iconPosition being broken. However it would be good to follow up on those.

## Testing Instructions

Perhaps easiest to test in storybook.
https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=icon:more;iconPosition:right;variant:primary

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
I tried to use Gutenberg with this PR applied and did not noticed any regression 👍

**Comment by jameskoster** [comment]
Nice PR. 

Appreciate it's not directly part of this work, but does the Dashicon affordance really need a custom off-grid margin value? Should we make that 8px too?

```
&.has-text {
	svg,
	.dashicon {
		margin-right: $grid-unit-10;
	}
}
```

**Review by mirka — APPROVED** [review]
> I haven't been able to test, however it seems like this would break in RTL contexts.

FYI, we have an RTL switcher tool right inside Storybook for testing this 🙂

https://user-images.githubusercontent.com/555336/210633425-eeb6b9e8-2efc-43b9-89ce-5235fa5d6cd3.mp4

> Furthermore, the button component appears to have an iconPosition prop, which at the moment seems to do nothing — even if set to right, the icon still shows up on the left

The `iconPosition` prop currently only works when the text is provided via the `text` prop and not as `children`, like [this](https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=children:;icon:wordpress;iconPosition:right;text:My+button;variant:primary).

The Button component is a mess right now to begin with (#44042) so I'm ok with merging incremental fixes (i.e. half-measures) as long as it doesn't mess things up further. This PR doesn't fix the `icon`+`text` case, but it fixes the `icon`+`children` case and doesn't break anything else. So I think we're good to go once we have a [changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) entry 👍

**Comment by jasmussen** [comment]
> Appreciate it's not directly part of this work, but does the Dashicon affordance really need a custom off-grid margin value Should we make that 8px too?

The footprint of dashicons are 20x20 vs 24x24, so the margin has to be plus the extra pixels to vertically align if you mix and match. I do think there's a place where we retire the dashicons support here, but that's separate.

**Comment by jasmussen** [comment]
Thanks for the reviews, and thank you @mirka for testing and showing me the RTL button 👌 

> So I think we're good to go once we have a [changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) entry 👍

I rebased to make sure I had the newest changelog, and addd an item. Let me know if that looks good.

**Comment by jasmussen** [comment]
I'll land this for now, but will happily follow up with any edits in case something was off. Thanks again folks!

**Pull request merged**
