### PR TITLE
@wordpress/api-fetch use remove window dependency.

### PR DESCRIPTION
**Pull request by torounit**
## Description

related: issue #17551 , PR #17574

* globalThis instead of window.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by aduth** [comment]
I'm curious, would this cause the polyfill to be bundled with `@wordpress/api-fetch` in browser environments where we would want to rely on the browser native `window.fetch` instead? Could you compare the size difference of `npm run build` for this package before and after the changes?

Ideally it's something where it's only imported in a Node environment where `global.fetch` (`globalThis.fetch`) is not available. I think it would be good also to avoid polluting the global namespace, which `isomorphic-fetch` does.

One approach may be to use `main` and `browser` fields in `package.json` to disambiguate between Node and the browser, where some common script would expect to receive the fetch function as an argument. Alternatively, it could be possible to use the Webpack-supported `.web.js` file extension:

`fetch.js`

```js
import fetch from 'whatwg-fetch';
export default fetch;
```

`fetch.web.js`

```
const fetch = window.fetch;
export default fetch;
```

`index.js`

```
import fetch from './fetch.js';
```

**Comment by aduth** [comment]
The build is failing, likely because there may be additional `package-lock.json` changes which need to be committed after running `npm install`.

**Comment by torounit** [comment]
@aduth 

Removed polyfills.
If need it, may want to install it separately.

**Comment by iamandrewluca** [comment]
One more aproach is to create a factory function and totally detach `fetch` function

```tsx
import { createApiFetch } from '@wordpress/api-fetch'

// Browser
const apiFetch = createApiFetch({ fetch: window.fetch })

// Node
const apiFetch = createApiFetch({ fetch: require('node-fetch') })
```

**Pull request closed without merging**
