### PR TITLE
Duotone Tracking & History

### PR DESCRIPTION
**Pull request by ajlende**
## #26751 Add duotone to image block<br>#26752 Add duotone block supports

⚠️ Do not merge this PR—the ones linked above should be be the ones merged. ⚠️

Since this is a rather large PR with a long history, I've simplified it down into two smaller PRs, #26751 and #26752, that can be run and reviewed independently of one another.

Both PRs share a few commits for the duotone component, toolbar, and theme.json code. I'll continue to add code to this PR which has all the history and apply those changes to the individual commits on the respective smaller PR.

#26751, the image block PR, is a bit more straightforward, so I recommend reviewing that first. #26752 requires some additional changes to core in WordPress/wordpress-develop#984, and it involves more blocks.

## Description

Adds duotone filters as a block-supports feature—originally prototyped on [Automattic/block-experiments](https://github.com/Automattic/block-experiments/tree/master/blocks/duotone-filter). With the SVG approach, there is [wide browser support](https://caniuse.com/mdn-svg_elements_fecomponenttransfer), so it'll also be supported on IE11.

The duotone feature comes with its own default palette. And a new option for `duotone` has been added to `theme.json`. See [theme-json.md](https://github.com/ajlende/gutenberg/blob/add/duotone-filter/docs/designers-developers/developers/themes/theme-json.md#settings) for details.

Adding it to a block is done with the `supports.duotone` option in the `block.json`. See [block-supports.md](https://github.com/ajlende/gutenberg/blob/add/duotone-filter/docs/designers-developers/developers/block-api/block-supports.md#duotone) for details.

In the future this can be expanded to more than two colors. That's mostly a UI problem right now, the feature supports arrays with more than two colors on the backend.

Support for the image block is added in this PR. ~Adding it to the cover block is blocked by #25171.~ Additionally the video block, cover block, and media & text block have support added via block supports which depends on WordPress/wordpress-develop#984.

## How has this been tested?

1. Create an image block, video block, cover block, and media & text block
2. Apply duotone filter from presets, the bar, and the palette selectors
3. Save and preview the duotone blocks
4. Convert between the supported blocks to see that duotone is maintained across the transformation
5. Test that you can add duotone with keyboard only

## Screenshots 

<details>
<summary>Old screenshots</summary>
<p>

duotone toolbar and picker

duotone in the cover block

duotone in the image block

duotone in the media & text block

duotone in the video block

media-text-duotone-2020-11-05

image-duotone-2020-11-05

duotone

</p>
</details>

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
If this `supports.duotone` feature could support 3 or more tones in the future, shouldn't it be called `supports.multitone` or something similar instead?

**Comment by ajlende** [comment]
> If this supports.duotone feature could support 3 or more tones in the future, shouldn't it be called supports.multitone or something similar instead?

@ZebulanStanphill I thought about that—technically "gradient map" is the most accurate term but I decided to leave "duotone" because [it's a more popular search term](https://trends.google.com/trends/explore?date=today%205-y&q=duotone,gradient%20map,multitone). I figured leaving it as "duotone" would improve discoverability even though it can do more than just two colors. I'm still open to changing it, though. Thanks for bringing that up!

**Comment by jasmussen** [comment]
I like "Duotone" for exactly the reason Alex mentions, it feels descriptive even if in some situations it isn't accurate. It's like the Bold button/icon that technically applies the _strong_ tag, not the _b_ tag. 

Besides, I suspect the majority of the presets we end up providing in this package are going to be duotones, as it very quickly gets muddy if you add additional stops. It also simplifies the UI rather drastically, which is important for the first version. It's cool that it's possible, though, and that the feature can grow if need be!

**Comment by jasmussen** [comment]
I think with this PR we can potentially revisit some of the structure of the Image block toolbar, which landed a little complexity with the image tools work. 

For starters, I'd love to see us grouping together block level tools in a single toolbar group. This frees up space, reduces borders, and cleans up the room:

Screenshot 2020-10-22 at 12 50 36

In the above, I'm picturing the Duotone filter button living inside the "Edit" menu. On one hand that feels appropriate as the filter is contextually related to the edit tools. But at the same time it buries them one level deep. If we want to go with them directly available (could always put them there for starters), the button should live before the "Replace" button:

Screenshot 2020-10-22 at 12 50 53

Since the duotone is technically a gradient, we could take inspiration from how the gradient tools work to configure gradients:

Screenshot 2020-10-22 at 12 53 56

I don't love how that would open another color popover within the popover, when you need to customize the colors:

Screenshot 2020-10-22 at 12 54 56

so I hope to figure out a way to show the color picker inline (which has its own sets of problems). 

But the popover route may be a good way to start, as I would expect us to provide a range of excellent presets, making that the primary interaction.

**Comment by ajlende** [comment]
> For starters, I'd love to see us grouping together block level tools in a single toolbar group. This frees up space, reduces borders, and cleans up the room

Seems out of scope for this PR, since it would probably require refactoring the align, link, and image tools toolbars too. But I agree that would look nicer.

> In the above, I'm picturing the Duotone filter button living inside the "Edit" menu...[otherwise] the button should live before the "Replace" button

Looking at how the alignment toolbar is done in the image block, I can export the components separately and allow the block to use them manually with some refactoring.

I think having it outside of the edit/crop menu will be better because it may be confusing that saving the crop with a filter doesn't upload the filtered image and because it's nice to change the filters without the crop overlay.

Currently, the toolbar appears in both places. If I'm refactoring it to be manually added by the image block I can hide it in the edit/crop menu.

<p align=center>
duotone in cropper
</p>

<p align=center>
duotone after block
</p>

As a block filter, there isn't a whole lot of control over placement—it gets added to the toolbar either before or after all the existing toolbar items. In that case (for blocks that are don't manually add the duotone toolbar), do you think before or after would be better?

<p align=center>
duotone after block
</p>

<p align=center>
duotone before block
</p>

> Since the duotone is technically a gradient, we could take inspiration from how the gradient tools work to configure gradients

In an earlier iteration, I tried reusing the gradient picker and parsing out the colors. I converted calculations into sRGB space instead of linearRGB space to match how CSS gradients are calculated ([even if it's not the "correct" way to blend colors](https://www.youtube.com/watch?v=LKnqECcg6Gw)). This means that we could show the full gradient transition rather than the hard break if you wanted and it would still be color-accurate.

The SVG `feComponentTransfer` doesn't have explicitly defined stops for the colors—instead equidistantly spacing them—so we'd probably want to lock the stops in place. Between that and storing the duotone data differently, we're not going to get much reuse out of the existing gradient picker as far as code, unfortunately.

> I don't love how that would open another color popover within the popover...so I hope to figure out a way to show the color picker inline

The inline color picker would be nice in all places the popover is currently used, so a design for that could supersede #26115. For now I'll continue working on #26115 since that'll fix the major accessibility concerns I have with doing the popover. I don't want this to ship before the accessibility issues have been resolved.

**Comment by jasmussen** [comment]
Great thoughts. I'll look into a separate PR or issue about potentially grouping the block level stuff together.

Ugh the edit tools menu definitely is a bit of a mess. I don't actually know what I like better — the duotone button after "Replace", or inside the "Edit" menu. Are you sure there's no way we could put it before "Replace" in this PR?

**Comment by jasmussen** [comment]
Toolbar improvements ticketed in https://github.com/WordPress/gutenberg/issues/26411.

**Comment by mtias** [comment]
"Replace" to me should be at the end. 100% agree on removing all those spurious borders.

**Comment by ajlende** [comment]
> Are you sure there's no way we could put it before "Replace" in this PR?

Sorry about the confusion. For the image block, I'm working on getting that to work. It just won't be using the `supports` feature that's available for other blocks, similar to how the alignment toolbar is added.

> I can export the components separately and allow the block to use them manually with some refactoring.

**Comment by ajlende** [comment]
This is blocked by #26612 which will fix the keyboard accessibility of the custom color popover

**Comment by ajlende** [comment]
> Since the duotone is technically a gradient, we could take inspiration from how the gradient tools work to configure gradients:
> 
> Screenshot 2020-10-22 at 12 53 56

@jasmussen Now that this is unblocked again, I'm working on the color/gradient bar.

With the bar interface, I kinda miss the auto color pairing by finding contrasting colors in the palette and not being able to choose from the color palette (also a critique of the existing gradient picker). Probably not worth changing for the initial release, but it's something to think about for the next revision. Or maybe we stick with the old interface for now?

Since the existing gradient toolbar works directly with CSS strings, it doesn't work as-is for duotone which uses a custom RGB object to store the information. I've started refactoring out the code relating to CSS gradient strings so I can at least reuse the CSS and HTML structure from the existing picker. (Can probably be done as separate PR that I'll link when ready.)

In the meantime, I still need a nice set of defaults—the ones right now are just pulled from the screenshot. At the very least, I think the red/blue one should be updated. Things should still run at 787faa2 with the older interface if you want to test out a new set of defaults by changing [lib/experimental-theme.json](https://github.com/WordPress/gutenberg/pull/26361/files#diff-3849555cc94abaf87253af372c86778e6df6cc11b9c29d818d815fbf87128c1f). Otherwise just testing out colors in Photoshop and sending over the hex strings would also be enough.

**Comment by jasmussen** [comment]
Excited for this one. I trust you'll let me know if you need me to help with any work here?

**Comment by ajlende** [comment]
@jasmussen I'm getting pretty close to the testing and code cleanup stage, so you're welcome to take a look. If you want run it locally, there's a core patch that you'll need: WordPress/wordpress-develop#984

This PR has support for the image block, cover block (block supports), and media & text block (block supports). For final review, I'm going to split those changes for easier review, but this is the place to test them all at once.

The main two things that you could look at now are deciding on the default swatches and hearing your opinion on selecting colors from the theme's color palette (plus auto-select based on brightness) with the part under the bar.

**Comment by jasmussen** [comment]
This is what I see:

duotone

Getting really close! It's also pretty clear that https://github.com/WordPress/gutenberg/issues/25983 is becoming increasingly something we need to fix for all blocks, so we can reduce some of those borders!

This is generally working pretty well for me, the toolbar looks pretty good. There are some nitpicks that I'd like to try and push some CSS changes for:

- The positioning of the popover is off to the left, not sure that's easily fixable
- I'd just change the popover title to Duotone, and I'd massage the heading a bit
- I'd make the thing a bit wider, it's slightly cramped as is, especially as the individual color selectors expand
- Some margins, alignments, little polish here and there

But all that is definitely feasible, so that's good! Nice work.

**Comment by ajlende** [comment]
> The positioning of the popover is off to the left, not sure that's easily fixable

Yeah, the `Replace` button also had issues with positioning before this change. I think it has something to do with the popover code, not anything in this PR right now.

image replace posisitioning

**Comment by ajlende** [comment]
Added support for `core/video`. It mostly works, but controls get styled too because they're part of the `<video>` tag. Not sure if that's a dealbreaker for the video block.

video duotone controls

**Comment by ajlende** [comment]
I've also been following @glendaviesnz's work on the [gallery block refactor](https://github.com/WordPress/gutenberg/pull/25940) since there was an opportunity for inconpatibilities on these two long-running branches. But duotone looks like it will work perfectly with that too when it gets merged, which I think is super cool!

Screen Shot 2021-02-12 at 10 16 38

**Comment by jasmussen** [comment]
I pushed a change to the filter icon, and the swatch size. Before:

Screenshot 2021-02-15 at 09 44 06

After:

Screenshot 2021-02-15 at 10 00 43

Screenshot 2021-02-15 at 10 05 53

That's optically sized with the other icons:

Screenshot 2021-02-15 at 09 58 50

We really need to look at #26411 (or more high level, #25983) after this PR lands. That's still on deck.

**Comment by jasmussen** [comment]
I renamed the icon from "no-filter" to "swatch", because we can use it also for gradients or solid colors as the "unset" stage.

I also changed the tooltip to be simpler.

**Comment by jasmussen** [comment]
Tried using menugroup for the label:

Screenshot 2021-02-15 at 10 32 12

I genuinely prefer the bold normal-size label, but I think we should change that label separately, and by using the same component here, once we do, they will all be changed at the same time.

**Comment by jasmussen** [comment]
Pushed more polish:

Screenshot 2021-02-15 at 10 45 06

- Sentence case text
- Massaging width
- Gray help text
- Better horizontal positioning of dropdown

**Comment by jasmussen** [comment]
Note, this one:

Screenshot 2021-02-15 at 10 47 59

It's in a sorry state as it is there. But I cannot change that as part of this PR, because it would affect every other instance of the same button, such as here:

Screenshot 2021-02-15 at 10 48 07

So that's another thing we have to fix separately.

**Comment by jasmussen** [comment]
@ajlende I pushed some tweaks, let me know if it all looks good. The only one that might be problematic is the menugroup change, but from what I can tell it should be fine?

This looks good for a final review to me.

**Comment by ajlende** [comment]
Nice! I just gave it a check over, and I'll get these changes pushed to the other two reviews soon.

For the clear button, I can make a custom one for the outer duotone swatches that you can style differently since it looks like the `actions` section is just appended with a wrapper next to the other children.

**Comment by jasmussen** [comment]
> For the clear button, I can make a custom one for the outer duotone swatches that you can style differently since it looks like the actions section is just appended with a wrapper next to the other children.

No no, this is just a "note to self". It just bugs my eye that it remains subpar. It's _good_ that it's the same button used everywhere else, that means once I have a chance to fix it elsewhere, it will be fixed here as well, automatically.

**Comment by jasmussen** [comment]
I updated the presets:

presets

I'm going to mull on these a bit more, but I think we're closer to something solid, in that the dark colors are darker, the light colors are lighter, and the end result has more contrast.

**Comment by mtias** [comment]
I kind of liked some of the fluorescent ones :)

**Comment by jasmussen** [comment]
Made them slightly more flourescent again :) 

flourescent

Any one in particular you were missing or dislike about the new? One thing I noticed when testing on a bunch of images is that it's kind of important to have the dark colors be pretty dark.

**Comment by jasmussen** [comment]
Removed the description at the bottom, I recently got feedback it wasn't necessary:

Screenshot 2021-02-25 at 07 34 52

I was also suggested we could call these "Filters" rather than duotone. While it's technically duotone underneath and that's an impressive feat, maybe that's not important for people to know? They can just grayscale or colorize their images here. It might also help us if/when we add tritone features.

**Comment by jasmussen** [comment]
Two more questions:

- The terms "Dark color" and  "Light color" confused, in a round of feedback. While they are meant to let you avoid creating color inversions (like using a light color for the dark one and vice versa), should we simply call them "Color 1" and "Color 2"?

**Comment by ajlende** [comment]
> I was also suggested we could call these "Filters" rather than duotone. While it's technically duotone underneath and that's an impressive feat, maybe that's not important for people to know? They can just grayscale or colorize their images here. It might also help us if/when we add tritone features.

Technically the generic term would be "gradient map" which we deemed harder for people to discover or understand. The only thing I'm worried about with "Filters" is that people might expect to be able to do Instagram's idea of filters, and duotone doesn't do color adjustments and vignettes like that.

> The terms "Dark color" and "Light color" confused, in a round of feedback. While they are meant to let you avoid creating color inversions (like using a light color for the dark one and vice versa), should we simply call them "Color 1" and "Color 2"?

What do you think about "Shadows" and "Highlights" for the terminology? I still think the context for dark and light is useful. "Dark color" and "Light color" were supposed to indicate that you should choose a dark or light color, but I guess what's really happening is that the color you apply to the "Dark color" will change the shadows of the image to that color and the color you apply to the "Light color" will change the highlights of the image to that color.

**Comment by jasmussen** [comment]
> What do you think about "Shadows" and "Highlights" for the terminology? 

Love it, added it.

I tweaked the colors, yet again. It seems that a particular type of photo — with larger "flat" areas of darkness and light — work best for duotone, and should therefore be what we create the presets based on. I'm pretty happy with the balance of usefulness and vibrancy of these:

preset tweaks

Note the above is a highly compressed GIF, naturally the colors will be slightly more muted.

**Comment by ajlende** [comment]
> The only thing I'm worried about with "Filters" is that people might expect to be able to do Instagram's idea of filters, and duotone doesn't do color adjustments and vignettes like that.

To be clear, I can still update the name—I don't think this is that big of a problem. Just thinking about what people will think when they hear "filter".

**Comment by jasmussen** [comment]
No, it's an excellent point, and we can always do that depending on reactions.

I removed the description, per feedback. I think it works without it:

Screenshot 2021-02-26 at 09 28 48

**Comment by mtias** [comment]
I like "Duotone", it has more character. We might in the future rename the grouping as "filters" where Duotone is just one category, and we split "black and white" into its own set.

**Comment by jasmussen** [comment]
Super excited about this one.

**Pull request closed without merging**
