### PR TITLE
Rename "Options" modal to "Preferences".

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
This PR renames the "Options" modal to "Preferences". This helps get rid of the confusion of having an "Options" option located under the "Options" menu. (See, it even sounds confusing! :stuck_out_tongue:) This also helps narrow down the purpose of the modal a bit, and makes it clear what kind of options belong in it.

There are no functional changes in this PR. Only name changes.

### Before
image
image

### After
image
image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by carolynannewells** [comment]
Hello, Carolyn from editorial. I agree that "preferences" works better than "options". Is there anything else you would like me to look at?

**Comment by ZebulanStanphill** [comment]
> Hello, Carolyn from editorial. I agree that "preferences" works better than "options". Is there anything else you would like me to look at?

There's no other copy changes in this PR besides the renaming, so that's all. Thank you for your quick review! :smile:

**Review by afercia — COMMENTED** [review]
25 changed files just to change a string. There must be something wrong! 😆 

Jokes apart, makes sense to me. Quick question:

Should the "Keyboard options" section within the modal be renamed to "Keyboard preferences"? Or maybe just remove the word "options" as it seems to me this is the only section name with the term "options", not sure why.

From a technical perspective, I don't have the knowledge to determine whether these changes need deprecations/aliases or whatever, given fome files and components are renamed.

**Comment by ZebulanStanphill** [comment]
@afercia To be fair, I'm changing the CSS class names and function names, which isn't strictly necessary, but the confusion between the "More options" button and "Options" modal applies to the internal names as well, so I figured I ought to change them too. And of course, I had to update all the unit tests and end-to-end tests that check for specific classes and strings.

I'm pretty sure most of the internal name changes should be fine. The only thing I'm not sure about is changing `MODAL_NAME` from `edit-post/options` to `edit-post/preferences`. Is `openModal` exposed publicly? Hypothetically, if a plugin were to try using `openModal( 'edit-post/options' )`, it would now do nothing. I'm not sure why a 3rd-party plugin would do that, though, or if it's even possible. I'll wait for a technical review on that bit. It's easy enough to revert.

And yeah, "Keyboard options" should probably just be "Keyboard", though I figure that should be its own PR.

**Comment by afercia** [comment]
@ZebulanStanphill sure, I was joking on the changed files number, mostly because I'm surprised that in "modern development" one has to change 25 files to rename a string to "do it right". Old-school guy here, missing the old good days when changing a string was just... changing a string 🙂 

> And yeah, "Keyboard options" should probably just be "Keyboard", though I figure that should be its own PR.

I'd say: throw that change in and pretend others don't see it :trollface:

**Comment by ZebulanStanphill** [comment]
Now that I think about it, the Preferences modal probably shouldn't even have its own CSS class. I see it uses it for section margins... but I think that kind of styling should probably be made generic to all modals. Of course, the Preferences modal is likely to be [completely redesigned soon](https://github.com/WordPress/gutenberg/issues/24965), so I guess we can probably remove the class along the way when we implement that.

**Comment by mtias** [comment]
I'm fine with this change, don't have a strong opinion but seems "Preferences" can be a better fit. Also happy with sneaking in "Keyboard options" → "Keyboard" :)

**Comment by karmatosed** [comment]
I'm going to remove the design feedback as for me I'm also keen on not having options > options. I'd +1 the change @mtias suggests of using this as an option to remove other 'options'. I do think it could do with a little code check as that feels like quite a lot of spots it's in, as has been noted this could be a great opportunity for iteration there and streaming of process.

**Comment by ZebulanStanphill** [comment]
Applied the "Keyboard options" to "Keyboard" change.

**Review by mtias — APPROVED** [review]

**Comment by ZebulanStanphill** [comment]
I'm going to go ahead and merge this.

**Pull request merged**
