### PR TITLE
Docs: Fix text in readme.

### PR DESCRIPTION
**Pull request by wayheming**
## What?

After reading your readme I noticed some mistakes so I corrected them.

## Why?

To make your readme better

### CODE REVIEW

**Review by cbravobernal — APPROVED** [review]
LGTM

**Comment by wayheming** [comment]
Thank you @c4rl0sbr4v0

**Comment by sabernhardt** [comment]
@wayheming If you have a moment, could you connect your GitHub account to your wordpress.org one? It would be great if we could give you attribution by mentioning you on the credits screen in the upcoming WordPress 6.3 release. You can find more details on how contributions are tracked and how connecting GitHub accounts helps in [this post on the Make WordPress Core blog](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/).

**Comment by wayheming** [comment]
Hello, @sabernhardt thank you and [done](https://profiles.wordpress.org/ernest35/).

**Pull request merged**
