### PR TITLE
Remove Deprecated Features planned for removal in 2.4

### PR DESCRIPTION
**Pull request by youknowriad**
Everything is in the title:

 - `wp.blocks.BlockDescription` component removed
 - `wp.blocks.InspectorControls.*` components removed
 - `wp.blocks.source.*` matchers removed
 - `wp.data.select( 'selector', ...args )` removed
 - `wp.blocks.MediaUploadButton` component removed

### CODE REVIEW

**Comment by mtias** [comment]
Are we using these in any docs? Might be good to have a "deprecated" doc where we enumerate these for easier browsing by people.

**Review by aduth — APPROVED** [review]
Code-wise 👍 Agree deprecated document could be useful.

**Comment by gziolo** [comment]
By the way, with the recent changes introduced by @aduth we have now linting errors before this PR lands:
screen shot 2018-03-08 at 11 44 36

🥇

**Review by gziolo — APPROVED** [review]
Awesome 💯  It needs rebase :)

**Comment by gziolo** [comment]
Added the changelog as suggested. See: https://github.com/WordPress/gutenberg/blob/ccb3e8297fa00549e4b25ac2579359c08a3712f3/CHANGELOG.md.

We might want to start updating the changelog as we merge PRs to offload the work needed to prepare the release. This is how they approach things in Jest repository. I learned it when contributing recently.

@mtias - we might want to add links to all previous release posts.

**Comment by gziolo** [comment]
Should we merge it now or wait until we start 2.4 release process?

**Comment by aduth** [comment]
Should we want to maintain a full changelog in this repository? Vs. in the plugin repository? Vs. in the Make/Core posts?

Or just a reference to the deprecations only?

**Comment by aduth** [comment]
Changed to a `DEPRECATED.md` file, with full list of deprecations (including future versions), and a small blurb about the deprecation "policy".

**Comment by mtias** [comment]
A DEPRECATED.md sounds good. We might want to include it in the handbook as it is.

**Comment by aduth** [comment]
I'll move it into `docs` so it gets picked up for the handbook.

**Pull request merged**
