### PR TITLE
Block Styles: Switch block style selection to select dropdown with color swatches

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related:
- https://github.com/WordPress/gutenberg/pull/56540
- https://github.com/WordPress/gutenberg/pull/57703

🚧 **Warning - Do not merge** 🚧 

This PR requires updates to the experimental V2 `CustomSelectControl`. The changes for that have been split out into a separate PR (https://github.com/WordPress/gutenberg/pull/57703) for review and must land before this can be rebased, reviewed, and merged.

## What?

Updates the controls for selecting a block style variation to a custom select with color swatches pulled from the variation's theme.json styles if available.

## Why?

https://github.com/WordPress/gutenberg/pull/56540#issuecomment-1861963145

As the block styles feature is leveraged further for section-related styling, individual buttons for each block style will take up too much real estate in the inspector. The color swatches will also help ease style selection for users.

## How?

- Adds `__experimentalStyles` to the block editor store for access to global styles data.
- Adds `CustomSelect` (v2 CustomSelectControl) to the components package's private APIs
- Extends `CustomSelect` to allow visually hiding the label and controlling popover props
- Switch the `BlockStyles` component to use the new custom select control
- Fix group block example attributes so they don't interfere with block style previews

## Testing Instructions

1. Add some block style variations using theme.json style data following [56540](https://github.com/WordPress/gutenberg/pull/56540)
2. Edit a post and add a group block (or whatever block you added variations for)
3. Select the block with block style variations
4. Switch to the Styles tab in the block inspector and confirm that the control displays as a select with color swatches
5. Check that the block style previews work as expected
6. Ensure that block style selections are applied correctly

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/60436221/981e3d3c-7fda-4889-890c-6ed3d4516604

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
I've split out the component related updates from this into a new PR available for review in https://github.com/WordPress/gutenberg/pull/57703.

**Comment by ciampo** [comment]
Hey @aaronrobertshaw 👋  At this point in time, the new version of `CustomSelectControl` should be still considered a WIP and we don't recommend using it yet. We're still tweaking the APIs and we'd actually like to replace the legacy `CustomSelectControl`'s implementation with the new one. We're treating the `v2` as a temporary step of the process (and that's why we haven't exported it from the package).

Having said that, your usecase is definitely helpful in gathering more information about what consumers of the component may require — I'll continue the conversation directly in #57703

**Comment by aaronrobertshaw** [comment]
> At this point in time, the new version of CustomSelectControl should be still considered a WIP and we don't recommend using it yet.

Thanks for the additional context @ciampo, appreciate it. 

Unfortunately, the existing `CustomSelectControl` doesn't allow custom rendering of its options/children. The desire is to be able to render color indicator swatches for each option. 

Screenshot 2024-01-11 at 8 40 59 am

Am I correct in thinking there wouldn't be any appetite to make this major change to the existing `CustomSelectControl` at this time? Do you see any options other than creating a bespoke control within the block editor package to use until the v2 `CustomSelectControl` is ready?

I'll respond to specifics over on the [other PR](https://github.com/WordPress/gutenberg/pull/57703).

cc/ @SaxonF this might be a bit of a blocker to improving the UI for block style varaitions.

**Comment by brookewp** [comment]
It's exciting to see a use case and interest in the new version of CustomSelectControl that we've been working on! 😄 

>Unfortunately, the existing CustomSelectControl doesn't allow custom rendering of its options/children. The desire is to be able to render color indicator swatches for each option.
Am I correct in thinking there wouldn't be any appetite to make this major change to the existing CustomSelectControl at this time?

This is something we are exploring now, here: https://github.com/WordPress/gutenberg/pull/57000. With the goal of being able to use the new component, while keeping the backward compatibility for existing usages of CustomSelectControl.

**Comment by ciampo** [comment]
As @brookewp says, our goal is to rewrite `CustomSelectControl` with a new implementation that will support rendering custom items (as you already noticed in the temporary v2 component), as well as supporting the API layer of the legacy version of the component. We're actively working on it and we're hoping to wrap it up relatively soon

**Comment by aaronrobertshaw** [comment]
I'm closing this PR given the v2 custom select control isn't quite ready yet. There's an alternative approach using a dropdown in https://github.com/WordPress/gutenberg/pull/57780.

When the time comes to make the switch to a select control, this PR may or may not still be relevant but it can at least provide some direction.

**Pull request closed without merging**
