### PR TITLE
Wrap panel content to polish padding

### PR DESCRIPTION
**Pull request by mikaelz**
I'm not a designer, but I think it looks a bit better :) Feel free to polish the CSS.
gutenber-panel-body

### CODE REVIEW

**Comment by paulwilde** [comment]
I prefer the before version padding-wise as otherwise things are too spread out, however the after version is better for the blue focus.

**Comment by annaephox** [comment]
On the after:
- Blue focus looks good!
- Spacing between items still needs a bit of massaging: I'm not sure what the current values are, but suggest adjusting these slightly as follows

screen shot 2017-08-24 at 11 17 20 am

1. Space between input field and next box: make them consistent (+1-2px to the space after "Featured Image")
2. Space before section break: make them consistent (-1px from space after "Set Featured Image")
3. Space after section break: make them consistent (-1px from space before "Excerpt") 
4. Space after heading: make them consistent (-2-3px from space after "Excerpt") 

@mikaelz : If you post another screenshot I can have a quick look and we can make any other adjustments

**Comment by karmatosed** [comment]
I think it would be good to get a fix for all areas. For example even with the fix I see this on categories:

2017-08-25 at 21 52

@annaephox whilst I agree we can iterate on the padding, this PR as far as I can see only impacts the blue focus, so that's the default padding. I may be wrong though, it doesn't seem changed.

**Comment by karmatosed** [comment]
Can we have some browser testing feedback on this please with my suggestions?

**Comment by karmatosed** [comment]
We have had some changes here so closing this particular issue.

**Pull request closed without merging**
