### PR TITLE
Return focus in Calendar UI.

### LINKED ISSUE #15329: Keyboard focus is not managed when dynamic content disappears
Keyboard focus is not managed when dynamic content disappears

-   **Severity:** Medium
-   **Affected Populations:**
    -   Blind
    -   Low-Vision
    -   Motor Impaired
    -   Cognitively Impaired
-   **Platform(s):**
    -   All / Universal
-   **Components affected:**
    -   Publish and Unpublish

#### Issue description

When the "Calendar Help" link or the "Close" button on its popup is
clicked, the focus is reset to the top of the page, in all tested
browsers except Chrome and chromium.

Keyboard and screen reader users rely on predictable and consistent
focus control to navigate the page. When this is absent, users may find
it much more difficult or even impossible to navigate using the
keyboard.

##### Issue Code

```
    <!-- when Calendar help is clicked... -->


    <button type="button" class="components-button components-datetime__date-help-button is-link">Calendar Help</button>





    <!-- ...focus should be brought to the popup -->


    <div class="components-popover__content" tabindex="-1" style="max-height: 187.361px;">


        ...<button type="button" class="...">Close</button>...


    </div>





    <!-- when the Close button is clicked, focus should move to Month control -->


    <div class="components-datetime__time-field components-datetime__time-field-month">


        <select aria-label="Month" class="...">...</select>


    </div>
```

#### Remediation Guidance

When the "Calendar Help" link is clicked, focus should move to the
popup which is opened (which has `tabindex="-1"`).

When the "Close" button is clicked, focus should move back to the
Calendar Help's first focusable element (the month control).

#### Relevant standards

-   [2.1.1 Keyboard
    (Level A)](https://www.w3.org/TR/WCAG20/#keyboard-operation-keyboard-operable)

**Note:** This issue may be a duplicate with other existing accessibility-related bugs in this project. This issue comes from the Gutenberg accessibility audit, performed by [Tenon](https://www.tenon.io) and funded by [WP Campus](https://wpcampus.org/). This issue is GUT-15 in Tenon's report

### PR DESCRIPTION
**Pull request by v9ai**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/15329

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by nicolad** [comment]
hello @aduth I was following this [suggestion](https://github.com/WordPress/gutenberg/issues/15329#issuecomment-489441067) and had used `FocusReturnProvider` to recover lost focus, but as might see in screencast for some reasons it isn't working as expected in FF.
Any thoughts on why focus is lost here ?
Peek 2019-06-22 18-17

**Comment by aduth** [comment]
At a glance: It could be related to browser-specific handling of button events which differ in Firefox.

See also: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus

There is similar handling in `withFocusOutside` to normalize these differences: https://github.com/WordPress/gutenberg/blob/master/packages/components/src/higher-order/with-focus-outside/index.js

**Comment by tellthemachines** [comment]
Hi @nicolad , thanks for working on this! Are you planning to pick it up again in the near future? 

I've been testing this issue across browsers, on the latest master branch, and can no longer reproduce it on Firefox. I can still reproduce it on IE though, and the changes from this PR are not fixing the issue for IE 😞 . Not sure why yet, but I think we'll have to consider a different approach. 

Are you still keen to work on it, and, if not, would you be happy for me to close this PR for now?

**Comment by nicolad** [comment]
Hi @tellthemachines 
Thanks for looping back on this.
I am happy to make this closed.
Also, since you mentioned a different approach, I've unassigned me from the original issue and moved that in todo column.

**Pull request closed without merging**
