### PR TITLE
Codeowners changes for @chrisvanpatten

### PR DESCRIPTION
**Pull request by chrisvanpatten**
## Description
+ Removing myself from codeowners in `/packages` for everything except `@wordpress/components`
+ Adding myself to `*.scss` as an experiment

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
I removed obsolete @ghost placeholder for no longer unowned styles with 8d17d43 :)

Otherwise, everything looks great. We can always revert back to @ghost if you aren't happy about the number of notifications.

**Comment by chrisvanpatten** [comment]
Thanks @gziolo 🎉

**Comment by aduth** [comment]
> * Adding myself to `*.scss` as an experiment

Curious how this is working out? The nature of CODEOWNERS in "last match wins" means that for pull requests consisting only of changes to `.scss` files, you are the only person notified. To me, it seems this runs the risk of (a) overburdening you and (b) not notifying those who perhaps ought to be notified (as otherwise being code owner of the package in which the file is changed).

**Comment by chrisvanpatten** [comment]
@aduth I actually didn't realize codeowners was "last match wins". Definitely not the intention to prevent notifying anyone else. Happy to have this change reverted.

**Comment by aduth** [comment]
> @aduth I actually didn't realize codeowners was "last match wins". Definitely not the intention to prevent notifying anyone else. Happy to have this change reverted.

Thanks for clarifying!

For posterity, the related pull request to have had this removed is at #15216.

**Pull request merged**
