### PR TITLE
Remove Navigation Area block

### PR DESCRIPTION
**Pull request by getdave**
## What?
Removes the deprecated Navigation Area block introduced in https://github.com/WordPress/gutenberg/pull/36178 and formally deprecated in https://github.com/WordPress/gutenberg/pull/36727.

## Why?

Navigation Areas were deprecated in https://github.com/WordPress/gutenberg/pull/36727 and should now be removed entirely in line with best practices and also to clean up the Nav block code.

## How?

Removes all references to the Nav Areas block from Gutenberg.

**Question**: some of this code may have made it into Gutenberg Core. What should we do here @adamziel?

## Testing Instructions
Check for errors when loading Gutenberg and inserting a Nav block.

### CODE REVIEW

**Comment by adamziel** [comment]
> Question: some of this code may have made it into Gutenberg Core. What should we do here @adamziel?

Practically none of it made it. This block made it to one Gutenberg release, and in another it was marked as experimental. Experimental blocks are not backported to core. The deprecation grace period for Gutenberg passed long ago. We're good to go here.

...that is, once the unit tests pass 😄

**Comment by adamziel** [comment]
This looks pretty close @getdave! Just one more test: `Error: Call to undefined function gutenberg_render_block_core_navigation_link()`

**Comment by getdave** [comment]
> This looks pretty close @getdave! Just one more test: `Error: Call to undefined function gutenberg_render_block_core_navigation_link()`

Yeh that is weird. I can't see it happening elsewhere but I raised [this as a potential fix](https://github.com/WordPress/gutenberg/pull/40657). What do you think?

**Review by spacedmonkey — APPROVED** [review]

**Comment by getdave** [comment]
@adamziel I've rebased to pick up fixes in https://github.com/WordPress/gutenberg/pull/40657. Let's see if this is now 🍏

**Comment by adamziel** [comment]
I cherry picked this change into `wp/6.0` branch to be included in WordPress 6.0 RC1: 1d142dc503

**Pull request merged**
