### PR TITLE
Add new option to dependency-group ESLint rule

### LINKED ISSUE #16789: @wordpress/scripts treats aliased modules as external dependencies
**Describe the bug**
When running `wp-scripts lint-js`, I get
```
error  Expected preceding "External dependencies" comment block  @wordpress/dependency-group
```
and the code that causes this is
```js
import { someModule } from 'myalias/utils';
...
```
The problem is `someModule` is not an external dependency.

**To reproduce**
1. Create a module
2. Add an alias to webpack.config.js pointing to that module
3. Import the module using the alias
4. Run `wp-scripts lint-js`

**Expected behavior**
The error should be 
```
error  Expected preceding "Internal dependencies" comment block  @wordpress/dependency-group
```
and when running `--fix` it should use `Internal`.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - Browser: Chrome
 - Version 75.0.3770.142 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by swissspidy**
## Description

Allows passing regex to mark specific dependencies as internal ones. Example:

```
{ isInternalDependencyPatterns: [ '^my-project' ] }
```

Fixes #16789.

## How has this been tested?

Added new tests

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by swissspidy** [comment]
BTW, naming suggestions are more than welcome.

**Comment by aduth** [comment]
I am conflicted on the goal of this pull request, since the use-case described in #16789 is one I think could be classified as unsupported. 

But in considering further what this rule is intended to do, I see some generic pattern of "import path pattern" -> "expected grouping comment". 

Today, we have:

- `^./` -> "Internal"
- `^@wordpress/` -> "WordPress"
- _Else_ -> "External"

If we were to make this extensible, I wonder if we could model the option as not being so specific to what is categorized as one of these (specifically, "Internal") but something more generic about how those patterns can be overridden.

So maybe to support something like #16789, it could be configured in an `overrides` option:

```
{ "overrides": { "^my-project": "Internal" } }
```

Taken to an extreme, we could even consider removing some of our own defaults like "WordPress dependencies", and instead push those to be injected by the consuming project (Gutenberg, in our case).

**Comment by swissspidy** [comment]
Very interesting thoughts.

I was considering something similar too, but thought that it wasn't worth it as there's likely no demand for it and it would likely require a big rewrite. At the moment the grouping is quite buggy, and this kind of option would only surface that more.

While working on this PR, this rule actually reminded me more of the [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) ESLint rule. It might be more valuable contributing to that rule to support custom groups and comment blocks for groups. Two features that would make this entire rule and this enhancement obsolete.

**Comment by aduth** [comment]
> it would likely require a big rewrite.

Would it? Without digging into it too deeply, it seems like something where the logic would be contained in the existing `getPackageLocality`, and the only thing necessary would be to provide a configuration argument to that function to override the default pattern logic.

**Comment by swissspidy** [comment]
The change itself wouldn't require a big rewrite, but it would definitely surface the current shortcomings of the rule. Fixing those would require a bigger rewrite.

**Comment by aduth** [comment]
It's not immediately clear to me the specific shortcomings you're referencing. I guess the broader question I have is: How would you like to proceed here? Close the pull request and pursue an upstream improvement to `import/order` instead? Close the associated issue as unsupported? Try an alternative approach like previously discussed (with or without extra refactoring)?

**Comment by chrisvanpatten** [comment]
I really like the idea of an `overrides` which allows a pattern to target a group more generically. I may see if I can scrounge up some time to try implementing that.

**Pull request closed without merging**
