### PR TITLE
[RNMobile] Reduce spacing in slider

### LINKED ISSUE #2126: Refine spacing on cells that contain Slider controls
Cells that contain the Slider control feel a bit too spacious in most cases — particularly on block settings bottom sheets. For example:

## Current

| iOS  | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78714560-b94c9500-78e1-11ea-9595-1ec4b6746373.png"></a> | <a href="https://user-images.githubusercontent.com/1200432/78714600-c9647480-78e1-11ea-9772-37fa4ddfd07f.png"></a> |

Note: Android appears to have even _more_ spacing than iOS (about ~10px more), so we could also tighten that spacing up to the same values as iOS unless we want to provide more spacing on Android. **Edit: I just realized this 10px disparity might be because of the drag handle size difference between platforms.**

## Proposal

While it was designed this way in an effort to align with some of the native patterns, over time it has become clear that spacing feels a bit too much in practice, esp on Android. What I'm proposing is to essentially remove about ~14px of spacing between cell title and slider on iOS and ~24px on Android, like this:

| iOS  | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78714684-e731d980-78e1-11ea-995a-44edb81d2e17.png"></a>  | <a href="https://user-images.githubusercontent.com/1200432/78714723-f9ac1300-78e1-11ea-99ab-4a6366462e58.png"></a> |

## Before/After

| iOS | Android |
| ------------- | ------------- |
| <a href="https://user-images.githubusercontent.com/1200432/78715212-b0a88e80-78e2-11ea-9557-5d25c0c69abf.png"></a> | <a href="https://user-images.githubusercontent.com/1200432/78715294-d3d33e00-78e2-11ea-9d81-0c0935cf496c.png"></a> |

cc'ing for feedback: @SylvesterWilmott @mattmiklic  — do you think this feels _too_ condensed? Should we worry about matching the native component _exactly_ or is it okay to refine these based on how they've felt in context?

### LINKED ISSUE #2501: Slider spacing don't look right
Slider spacing don't look right initially on some cases. It starts to look normal when I move the Slider button.

**To Reproduce**
1. Add Latest Posts block
2. Open block settings
3. Scroll down to 'Number of items'
4. See that the spacing is too tight between the title and the Slider.

**Expected behavior**
The spacing should be corrected.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: iOS 13

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2126

Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2501

## Screenshots 

* ios

Cover | Latest post | Button
--- | --- | ---
Screenshot 2020-07-23 at 17 04 52 | Screenshot 2020-07-23 at 17 04 46 | Screenshot 2020-07-23 at 17 04 38

* android 

Cover | Latest post | Button
--- | --- | ---
Screenshot 2020-07-23 at 17 25 02 | Screenshot 2020-07-23 at 17 24 16 | Screenshot 2020-07-23 at 17 24 32

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
This looks good, and lines up with what I've got in Figma as far as I can tell. Thanks for taking care of it, Luke!

**Review by iamthomasbishop — APPROVED** [review]
This looks good, and lines up with what I've got in Figma as far as I can tell. Thanks for taking care of it, Luke!

**Comment by dratwas** [comment]
Hmmm, i'm wondering what is the difference between this PR and https://github.com/WordPress/gutenberg/pull/23580/files 

It seems like this should work the same as the reverted one

**Comment by lukewalczak** [comment]
Hmm that's interesting 🤔 are we sure then these changes introduced the regression? Do we have a specific case to test to confirm it current changes works properly?

**Comment by lukewalczak** [comment]
red_space

**Review by antonis — APPROVED** [review]
LGTM! Nice work @lukewalczak !! 🎉 Tested it on both iOS and Android.

**Review by dratwas — APPROVED** [review]

**Pull request merged**
