### PR TITLE
Updates 'Three buttons' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Updates contents and style of the 'Three buttons' pattern. Also adds a description.

**Before:**
Screen Shot 2020-07-22 at 16 57 00

**After:**
Screen Shot 2020-07-22 at 16 57 14

### CODE REVIEW

**Comment by mapk** [comment]
The pattern preview looks like this. Can we get the three buttons to be on the same line for the Preview?

Screen Shot 2020-07-22 at 3 07 56 PM

**Comment by enriquesanchez** [comment]
Thanks @mapk! I increased the `viewportWidth` and that should make it better.

**Review by mapk — APPROVED** [review]
Perfect. Much better now. Thanks.

Screen Shot 2020-07-22 at 3 36 17 PM

**Comment by mapk** [comment]
Looking at this again, 600 seems like too much. I recommend just getting as close to 500 as possible so that they a close to the same size as the Two Button Pattern.

**Pull request merged**
