### PR TITLE
Block Placeholders: Changed placeholder borders to be dashed lines

### PR DESCRIPTION
**Pull request by mapk**
## Description
Updated the Placeholder state to try dashed borders instead of solid. See #23124 

## How has this been tested?
Tested locally.

## Screenshots

Screen Shot 2020-07-27 at 4 18 02 PM

## Types of changes
CSS only. Non-breaking changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@mapk Perhaps this could be applied to only the placeholders than can have content dragged into them like the image block? I think applying it to every block is a bit much.

**Comment by mapk** [comment]
So rather than helping indicate a temporary placeholder, the dashed border should instead indicate a drop zone for draggable items?

I wonder if that's getting too specific? 

It would end up looking like below, and I'm not sure it communicates that well.

Screen Shot 2020-08-12 at 10 42 21 AM

**Comment by MichaelArestad** [comment]
@mapk yeah. I'm not sure the dotted outline works well in either. I think it's slightly better to only apply it to blocks that are drop zones.

**Comment by mapk** [comment]
Let's close this PR as a, "tried it, didn't like it." 😄

**Pull request closed without merging**
