### PR TITLE
Device preview: center the dropdown menu

### PR DESCRIPTION
**Pull request by vindl**
## Description

A small tweak to the Device Preview dropdown menu position. Previously it was positioned `bottom left` and it wasn't clear what its parent component was. I'm switching it to `bottom center` here to better align it with the parent button.

## How has this been tested?

Open the post editor or the site editor and verify the device preview dropdown position.

## Screenshots 

| Before | After |
|-|-|
|Screenshot 2020-05-07 at 19 24 17|Screenshot 2020-05-07 at 19 23 13|
|Screenshot 2020-05-07 at 19 24 07|Screenshot 2020-05-07 at 19 23 25|

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by epiqueras** [comment]
Now it looks like it's under "Publish".

We need to align it bottom-left against the chevron instead.

**Review by MichaelArestad — APPROVED** [review]
I dig. This looks good and works as expected.

**Edit:** I hadn't seen the comment from @epiqueras before I posted. Bottom left would work as well. My concern there is proximity to the edge of the screen, but I _think_ it should be okay.

**Comment by vindl** [comment]
> Edit: I hadn't seen the comment from @epiqueras before I posted. Bottom left would work as well. My concern there is proximity to the edge of the screen, but I think it should be okay.

Bottom left is what it's using now, was this referring to mean bottom right perhaps? 🤔

**Comment by MichaelArestad** [comment]
> Bottom left is what it's using now, was this referring to bottom right perhaps?

That's what I would expect. The naming is a little confusing, but an alternative to center alignment would be for the left side of the menu to align with the left side of the parent.

**Comment by shaunandrews** [comment]
So this is just a guess, but the logic I see is:

- Menus that open from a button on the left side of the toolbar should be left-aligned to that button.
- Menus that open from a button on the right side of the toolbar should be right-aligned to that button.

Now, again, this is just a guess, but the logic tracks to my mind. I have no strong opinion other than we should be consistent and base our decisions on logic.

**Comment by epiqueras** [comment]
I agree with @shaunandrews here.

The "Before" in this PR was on the right track, but it was incorrectly aligned with the edge of the text instead of the entire button, including the icon.

**Comment by vindl** [comment]
> The "Before" in this PR was on the right track, but it was incorrectly aligned with the edge of the text instead of the entire button, including the icon.

It doesn't look like this is something tied to this specific case since both the toggle and content are passed as props to Dropdown component. It will likely require Popover positioning modifications in general to achieve the above.

**Comment by noahtallen** [comment]
convenient plug: #21275

**Comment by epiqueras** [comment]
Yeah, we should fix the popover.

**Comment by vindl** [comment]
> Yeah, we should fix the popover.

I'll close this out then in favor of https://github.com/WordPress/gutenberg/issues/21275.

**Comment by vindl** [comment]
> Yeah, we should fix the popover.

I'll close this out then in favor of #21275.

**Pull request closed without merging**
