### PR TITLE
Add editorial pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds an Editorial section block pattern for #20345.

**⚠️ Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.**

Screen Shot 2020-03-04 at 19 18 06

```
<!-- wp:cover {"url":"https://nrqsnchztest.blog/wp-content/uploads/2020/02/96AC3A3B-C0EB-43D6-B8CD-9E6EF3082E41.jpeg","id":436,"dimRatio":70,"customOverlayColor":"#000000","align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim-70 has-background-dim" style="background-image:url(https://nrqsnchztest.blog/wp-content/uploads/2020/02/96AC3A3B-C0EB-43D6-B8CD-9E6EF3082E41.jpeg);background-color:#000000"><div class="wp-block-cover__inner-container"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"align":"left","customFontSize":72} -->
<p style="font-size:72px" class="has-text-align-left">He was still sleeping</p>
<!-- /wp:paragraph -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>He was still sleeping; so the curate asked the niece for the keys of the room where the books, the authors of all the mischief, were, and right willingly she gave them. They all went in, the housekeeper with them, and found more than a hundred volumes of big books very well bound, and some other small ones. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>The moment the housekeeper saw them she turned about and ran out of the room, and came back immediately with a saucer of holy water and a sprinkler, saying, “Here, your worship, señor licentiate, sprinkle this room; don’t leave any magician of the many there are in these books to bewitch us in revenge for our design of banishing them from the world.”</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>The moment the housekeeper saw them she turned about and ran out of the room, and came back immediately with a saucer of holy water and a sprinkler, saying, “Here, your worship, señor licentiate, sprinkle this room; don’t leave any magician of the many there are in these books to bewitch us in revenge for our design of banishing them from the world.”</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"align":"wide","id":437,"sizeSlug":"large","className":"is-style-default"} -->
<figure class="wp-block-image alignwide size-large is-style-default"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/FECD794E-5784-4B97-9AD1-B2748A76AD11-1024x768.jpeg" alt="" class="wp-image-437"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>The simplicity of the housekeeper made the licentiate laugh, and he directed the barber to give him the books one by one to see what they were about, as there might be some to be found among them that did not deserve the penalty of fire.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":469,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://i2.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/96AC3A3B-C0EB-43D6-B8CD-9E6EF3082E41-2.jpeg?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-469"/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":473,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://i0.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/F88EC5E3-2C7C-41F5-87F6-2C79BCCC62AC.jpeg?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-473"/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":471,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://i2.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/FECD794E-5784-4B97-9AD1-B2748A76AD11-3.jpeg?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-471"/></figure></div>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:cover -->
```

### CODE REVIEW

**Comment by mtias** [comment]
This looks like a cool combination. I think it could use some more refinement on the typography scale (balance title with body text). Maybe less words on the title; slightly larger body text. The text below the right image that looks like a caption could use some more separation from the image (at least as much as the gap between the bottom images).

**Comment by enriquesanchez** [comment]
@mtias does this feel better?

Screen Shot 2020-03-09 at 16 50 52

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. I know we decided to go without images for now but I would like to know if you think we can somehow revisit this one or if we should close this PR instead.

**Comment by mapk** [comment]
My next suggestion here would be to align the items to a stronger grid. Currently, there appears to be 3 columns on top and 3 on the bottom but none of them align to the same grid.

I recommend keeping the title, the two columns of text and the 3 photos below, all on top of a single image. This might work better.

**Comment by mapk** [comment]
I realized this pattern really relies on images right now. Let's close this since we aren't settling on images quite yet.

**Pull request closed without merging**
