### PR TITLE
Add order/order by support in Query block

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
This is a part of https://github.com/WordPress/gutenberg/issues/24521 whose ultimate goal is to make `Latest posts` block a block variation of `Query` block.

This PR adds `order` and `orderby` (date + title) support for the `Query` block. This functionality is imported from `QueryControls` which is a component tightly coupled with query filters and seems to be a good place to build upon.

There will also be follow up PRs that will enhance the `Query` block and `QueryControls` component so as to support more options from the API.

Although the previous options for `Query` block where in the block toolbar, I placed the new sorting addition is in the block inspector controls. This seemed to be a better place for adding a lot more options ( to me :) ) as it would be really crowded to add so many things in the toolbar. Of course this could be decided and kept or changed later by just moving these components.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by draganescu — COMMENTED** [review]
Great work @ntsekouras ! I tested this and it works. I found it to be a bit slow to update locally, plus the transitions are a bit jarring when the query is changed. This is out of the scope of this PR, but I wanted to mention b/c I added two design labels.

I added "Needs design" because the whole query block could use more direction, but particulaly, and why I added "Needs design feedback" I wonder this:

- does the toolbar filtering provide a better experience (with a closed inspector) in the context of the site editor where any screen real estate allows content to display better (e.g. sidebars not to collapse because of the inspector)?

If this is the case perhaps we could keep the filtering in the toolbar and polish that interaction more?

**Comment by jasmussen** [comment]
I took a quick look, and alas I've been out of the query loop (if you'll forgive the pun) — how do I best test this? ([Here's my failed GIF exploration](https://user-images.githubusercontent.com/1204802/91291863-f7b1f600-e795-11ea-97d6-35e5bddae0f8.gif)).

High level I do think I agree that we need some high level design work on the query block. I wonder if it could be a good candidate for @ItsJonQ's component work? But I also wonder: shouldn't that be a separate issue to discuss on, rather than hold up this PR?

**Comment by mtias** [comment]
> But I also wonder: shouldn't that be a separate issue to discuss on, rather than hold up this PR?

Yes, there's a tracking issue in #24762 to organize the query block work. It'd be good to start by identifying the parameters to support from WP_Query and map it to a UI. Then we can ran that through @ItsJonQ explorations and ensure we are covering all that is needed.

**Comment by ntsekouras** [comment]
> But I also wonder: shouldn't that be a separate issue to discuss on, rather than hold up this PR?

> It'd be good to start by identifying the parameters to support from WP_Query and map it to a UI.

I agree that we should identify the parameters to support from WP_Query, but this is definitely going to be included (order/orderby title and date). 

The implemented functionality can be easily moved later with the design decisions, but I think this is a small improvement from what is shipped now, no?

What do you think? @mtias @draganescu

**Comment by mtias** [comment]
Yes, deifnitely!

**Review by draganescu — APPROVED** [review]
I tested this and while it still requires some decision on where to place all the filters and other new settings it works all right and it is a step forward. Code-wise it follows the structure of the rest of the block so 🚢  it!

**Pull request merged**
