### PR TITLE
Performance: Limit Categories search instead of fetching all results

### LINKED ISSUE #10169: Performance: Slow loading of tags and categories on sites with large amounts
Crowded blog with 100 categories and thousands of tags  (750.000 articles).

Trying to add a category gets a delay so big that the showing up of categories can take up to 30 seconds !!.  The same thing is happening on tags.

We are using Yoast SEO and we already tried to disable it and it is not the cause.   Even when categories and tags are set,  trying to "show" the current settings is painful as opening a post could take 30 seconds or more for current categories and tags show up.  This lead to many of my writers incorrectly adding repeated tags as they won't show up on time.  The VERY AGGRESIVE autosave feature is also something that affects the delay.

### PR DESCRIPTION
**Pull request by gwwar**
Instead of fetching all categories, or other hierarchical term selectors, let's fetch some default number, then allow users to search for other results. This should fix: https://github.com/WordPress/gutenberg/issues/10169

### Problem

The current behavior we see in master, is that when a site has many categories, it can take the categories panel a long time to be interactive. This is because we currently fetch all categories in a number of API requests. To reproduce this, use wp-cli to generate a number of categories on a **test site** using a command like:

`wp term generate category --count=10000`

https://user-images.githubusercontent.com/1270189/109360619-656dd600-783c-11eb-924c-f450b79371c1.mp4

🙈 wait a long time, then we should eventually see the categories panel be populated.

| Finally After 262 Requests |
|--------|
| Screen Shot 2021-02-26 at 12 53 42 PM |

### Confidence Check on Requirements

The current PR is just a quick sketch. I'd like to verify with folks on requirements here before I get too deep.

#### Proposed changes
- Let's always show the search input so we can see search result values
- Limit results to ~20 (we might need to fetch parents)

#### Requirements
- In order to render an item in the tree, we need to also fetch all parent terms.
- Assigned categories should remain visible in the tree. 
- If I untoggle a category and then search, should the untoggled category remain in the tree?

cc @jasmussen @shaunandrews on design
cc @ockham if you happen to know who'd be a good reviewer for this component.

https://user-images.githubusercontent.com/1270189/109362482-eed2d780-783f-11eb-8a8e-ae8cacd9a4ac.mp4

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for tackling this one. It seems like it could remove a really bad headache for some sites.

To understand this correctly, it simply puts a "max visible categories" to 20, and lets you search if you need any category beyond those visible, is that right? If yes, that sounds great, though I'd probably default to 30 instead of 20.

A bigger question is: does it sort alphabetically or by "frecency" or something else? It seems like the most used categories should be among the 20 or 30 to show up by default.

**Comment by gwwar** [comment]
> A bigger question is: does it sort alphabetically or by "frecency" or something else? It seems like the most used categories should be among the 20 or 30 to show up by default.

Thanks for taking a look @jasmussen. In trunk it displays all categories alphabetically. 

One of the challenges here is that we're rendering results in a tree list view. This works out fine when we fetch all results, but if we want to display a subset of items, what do we choose to render? For example, if I search for the category four, should I also display all of its parents? (I'm not sure if we limit the depth of categories).

Screen Shot 2021-03-01 at 8 03 20 AM

One option might be to show flattened results in a list vs a tree. (This has some challenges displaying visually that this is a child category).

Another might be smartly picking what parts of the tree to render, which can also be tricky.

**Comment by jasmussen** [comment]
> One of the challenges here is that we're rendering results in a tree list view. This works out fine when we fetch all results, but if we want to display a subset of items, what do we choose to render? For example, if I search for the category four, should I also display all of its parents? (I'm not sure if we limit the depth of categories).

Makes sense. It does seem like there's an opportunity to be smarter about what we show than just alphabetical. But I also wouldn't want to block an improvement that profoundly benefits sites with a lot of categories, so it could be a separate thing to explore.

Question: could we be lenient with subcategories, and fetch say 20 top level categories and _all of their child categories regardless of how many there are_, and then revisit if even that is too many? I'd think search should always show the direct result regardless of depth.

**Comment by gwwar** [comment]
> could we be lenient with subcategories, and fetch say 20 top level categories and all of their child categories regardless of how many there are, and then revisit if even that is too many? I'd think search should always show the direct result regardless of depth.

It sounds reasonable to try this ✅

**Comment by gwwar** [comment]
Hmm one other hiccup is that we allow the creation of categories in this panel. Selecting a parent also requires the full category list, so this would end up being a search box too. 🤔 I might check first to see if preloading is possible.

Screen Shot 2021-03-01 at 2 13 43 PM

**Comment by jasmussen** [comment]
> Selecting a parent also requires the full category list, so this would end up being a search box too.

Well that's a doozy.

If we can find a threshold for this performance optimization, so it literally happens only if a site has _a ton_ of categories, I would potentially think it an acceptable compromise to replace the inline category creator with a link to the wp-admin category section, so they can create the category there.

The question is what constitutes a "ton" of categories. 20 seems slightly low. Do you know when the performance issues start to get noticable?

**Comment by gwwar** [comment]
We can certainly tune the minimum here so that this acts the same for small sites. 🤔 I think I might try to avoid rendering in tree form for the I have too many categories case.

**Comment by gwwar** [comment]
Closing this for now. I'd like to return to this after focusing on a few more Navigation Block issues. This problem is up for grabs if folks are eager to try some approaches.

**Comment by bozzmedia** [comment]
Any chance this could be revisited? We are having issues in a similar manner, and it's also impacting Quick Edit functions. Please see: https://github.com/WordPress/gutenberg/issues/10169

**Comment by pixluser** [comment]
I've got the same problem on a brand new website, nice cloud hosting, and around 3000 categories.
The tree is so slow to load, because it also load the empty categories…
This new design can fix my problem too.

**Pull request closed without merging**
