### PR TITLE
Post Comments Block - add block alignment hook support.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

A minor follow-up to #24080 (now that #24122 has landed) to give the Post Comments block the `align` hook support as part of the requested feature parity.

## How has this been tested?

Tested on local docker environment.

Verify the Post Comments block has the options to set 'wide' and 'full' alignments in the editor.  
Similarly, verify that when saved these alignments are added on the front-end:
Screen Shot 2020-07-27 at 2 23 44 PM

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
:shipit:

**Review by jeyip — APPROVED** [review]
I can confirm that alignments are correct in the editor and the "alignwide" and "alignfull" classnames are applied to the post comments wrapper `div` in the frontend. 🌟

**Note:** I did see one issue. For me, on Firefox and Safari, selecting wide and full alignment doesn't seem to update anything in the block editor. The issue, however, seems unrelated to your PR because all blocks seem to be affected by this problem in those browsers.

**Review by jeyip — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
> Note: I did see one issue. For me, on Firefox and Safari, selecting wide and full alignment doesn't seem to update anything in the block editor. The issue, however, seems unrelated to your PR because all blocks seem to be affected by this problem in those browsers.

I see the same for Chrome.  It seems to work in the post-editor but not in the site editor.  I believe it is because it is the child of another block that is not set to have width set (or support).  In my specific case it is a Query Loop block that is being restricting (and I believe the post-content block inside that would need to be set to full as well).

**Comment by jeyip** [comment]
> In my specific case it is a Query Loop block that is being restricting (and that creates a post-content block that would need to be set to wide or full as well?

That makes total sense. Thanks for looking into it. Either way, it looks very unrelated to this PR. Nice job on setting us up for success with https://github.com/WordPress/gutenberg/pull/24122 It made CR easy-breezy 🙂

+1 from me!

**Pull request merged**
