### PR TITLE
Code quality: name store exports

### PR DESCRIPTION
**Pull request by adamziel**
## Description

#27088 introduced a new recommended way of referencing stores:

**Before**

```js
select( 'core/viewport' ).isViewportMatch( 'large' ),
```

**After**

```js
import { store as viewportStore } from '@wordpress/viewport';
select( viewportStore ).isViewportMatch( 'large' ),
```

This is great and solves multiple issues we've had. However, I don't like the part that says `import { store as viewportStore }`. It does not play well with IDE features such as auto importing. Over time, it will likely introduce inconsistencies across the codebase - different files will refer to the same stores using different names. Why not export the preferred name and enjoy "searchability", consistency, and autocompletion? This PR does exactly that:

```js
import { viewportStore } from '@wordpress/viewport';
select( viewportStore ).isViewportMatch( 'large' ),
```

cc @gziolo @youknowriad @ellatrix 

## How has this been tested?
Just confirm the units tests passed.

## Types of changes
Non-breaking change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
I'm open to the idea. This is actually how I approached the naming convention in the first place when working on  https://github.com/WordPress/gutenberg/pull/26655, see https://github.com/WordPress/gutenberg/pull/26655/commits/a107bb82471197b6f13815bb29328ce2300ad8f5 :)

I'm fine with what the majority decides.

**Comment by youknowriad** [comment]
I'm on the fence :) I  l ike the consistency of "store" personally but I can see its drawbacks. Waiting to hear more.

**Comment by gziolo** [comment]
I merged 3 PRs that reference `store` exposed from packages and all of them use aliases when importing. By the way, this PR will need a rebase and some updates to the import statements if we decide to end up using the proposed approach.

**Comment by kevin940726** [comment]
I have no strong preference either. I found `store` consistent, but I can also see that having auto-importing supported in IDE is a great advantage as well.

**Comment by draganescu** [comment]
I like this as well for reasons of simplicity, as having one preferred name doesn't only result in auto-importing working but also the ease in searching for other places using that particular store (although the same "searchability" is achieved with the string of the package name, this is easier).

**Comment by dmsnell** [comment]
my preference is to keep the aliases for consistency in the modules themselves and for other approaches such as when importing all names from a module

```ts
import * as editPost from '@wordpress/edit-post';
import * as viewport from '@wordpress/viewport';

doSomethignWith( editPost.store, viewport.store );
```

I'm frequently frustrated when working with packages that share a common concept and name but each one makes its own unique version and then I have to try and guess what it is, plus I find that these unique names tend to breakdown anyway and then we deal with the same problem of clashing import names.

**Comment by gziolo** [comment]
It'll be soon 2 years since this proposal 😅 We didn't take any action so it's rather impossible to change it now because of the backward compatibility concerns. Should we close this PR?

**Pull request closed without merging**
