### PR TITLE
Try pnpm

### PR DESCRIPTION
**Pull request by youknowriad**
Related to #36142 and #37318. Alternative to #36041.

### CODE REVIEW

**Comment by youknowriad** [comment]
There's a weird typescript issue here that is causing most CI jobs to fail. 

> Error: packages/components/src/flyout/styles.ts(15,14): error TS2742: The inferred type of 'FlyoutContentView' cannot be named without a reference to '.pnpm/reakit-utils@0.15.2_react-dom@17.0.1+react@17.0.1/node_modules/reakit-utils/ts/types'. This is likely not portable. A type annotation is necessary.

@sirreal @gziolo any idea why this happens and if there's a workaround.

**Comment by gziolo** [comment]
I'm looking into addressing some of the issues I encountered when trying to switch to npm 8 that might also pop up in this branch. See https://github.com/WordPress/gutenberg/pull/37364 (React types) and https://github.com/WordPress/gutenberg/pull/37365 (Redux). I have a longer list of tweaks to explore and I hope it will unblock our efforts so we can pick between npm 8 and pnpm.

**Comment by sirreal** [comment]
I'm not really sure what the issue is, I'm not familiar with pnpm or Reakit. It seems to be related to this issue https://github.com/microsoft/TypeScript/issues/42873

The message says "A type annotation is necessary," providing one seems to fix the problem:

```patch
diff --git a/packages/components/src/flyout/styles.ts b/packages/components/src/flyout/styles.ts
index b18cf6524d..3ac211d808 100644
--- a/packages/components/src/flyout/styles.ts
+++ b/packages/components/src/flyout/styles.ts
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import styled from '@emotion/styled';
+import styled, { StyledComponent } from '@emotion/styled';
 // eslint-disable-next-line no-restricted-imports
 import { Popover as ReakitPopover } from 'reakit';
 
@@ -12,7 +12,9 @@ import { Card, CardBody } from '../card';
 import * as ZIndex from '../utils/z-index';
 import CONFIG from '../utils/config-values';
 
-export const FlyoutContentView = styled( ReakitPopover )`
+export const FlyoutContentView: StyledComponent<
+	React.ComponentPropsWithoutRef< typeof ReakitPopover >
+> = styled( ReakitPopover )`
 	z-index: ${ ZIndex.Flyout };
 	box-sizing: border-box;
 	opacity: 0;
```

(I think that's correct, but I'm not familiar with emotion or Reakit 🙂 )

cc: @ciampo who may be able to check my work

**Comment by ciampo** [comment]
> cc: @ciampo who may be able to check my work

Thank you for the ping Jon! I am not entirely sure if we need to exclude `ref` (cc @sarayourfriend ) and/or if `reakit` already exports the type for the `Popover` pros, which could potentially avoid calling `ComponentPropsWithoutRef` in the first place (cc @diegohaz )

**Comment by gziolo** [comment]
Let's make sure it isn't related to the fact that `@wordpress/components` has outdated types for React. See more in https://github.com/WordPress/gutenberg/pull/37365. There is also some sort of issue with types to resolve.

**Comment by youknowriad** [comment]
The types are now fixed per @sirreal's suggestion, the e2e test are passing 🎉 still have some issues to solve for unit and mobile tests (probably missing dependencies)

**Comment by gziolo** [comment]
I opened also https://github.com/WordPress/gutenberg/pull/37396 to address some more issues discovered in this branch.

**Comment by diegohaz** [comment]
> > cc: @ciampo who may be able to check my work
> 
> Thank you for the ping Jon! I am not entirely sure if we need to exclude `ref` (cc @sarayourfriend ) and/or if `reakit` already exports the type for the `Popover` pros, which could potentially avoid calling `ComponentPropsWithoutRef` in the first place (cc @diegohaz )

Yeah! Reakit exports `PopoverProps`. But using `ComponentProps` or `ComponentPropsWithoutRef` should also be fine.

**Comment by sirreal** [comment]
> Let's make sure it isn't related to the fact that `@wordpress/components` has outdated types for React. See more in #37365. There is also some sort of issue with types to resolve.

👍  Agreed, it's worth seeing if the `@types/react` upgrade helps. I recall reaching v17 React types through Reakit, so it may indeed be related to those versions being out of sync. It's worth trying to revert the change I suggested after https://github.com/WordPress/gutenberg/pull/37365 lands.

**Comment by kevin940726** [comment]
I just discovered this and I just want to say that I would very much like this to happen. Could we share a before&after of the installation time and disk size comparison in the PR description?

One thing that might be worth doing is to [only allow pnpm](https://pnpm.io/only-allow-pnpm), so that people won't accidentally install a package using `npm install` and wait for several minutes just to find out that it's the wrong command.

**Comment by youknowriad** [comment]
Just wanted to share that I'm not working on this anymore, anyone can feel free to take it over. I think it's valuable to update to use pnpm (or else npm latest)

**Comment by sarayourfriend** [comment]
I'll take a look at this today and see if I can make any extra headway. We've benefitted a lot from using `pnpm` with Openverse.

**Comment by gziolo** [comment]
> I'll take a look at this today and see if I can make any extra headway. We've benefitted a lot from using pnpm with Openverse.

Can you elaborate on the benefits? How does it compare to npm 8? Do you hoist all packages to the top of the project?

**Comment by sarayourfriend** [comment]
> Can you elaborate on the benefits? How does it compare to npm 8? Do you hoist all packages to the top of the project?

We were on npm 8 before pnpm. The main benefit is super fast installs locally when dependencies change. The first time I installed the Gutenberg dependencies with `pnpm` today only a few hundred new dependecies were downloaded, the rest already existed in my local cache, and symlinking is super fast. This also makes debugging different setups (like hoisting) much faster. This benefit is also translated to CI when using a dependency cache.

Switching to `pnpm` also fixed a whole host of dependency resolution issues we were having with Storybook (something I know Gutenberg has also struggled with in the past).

The PR where Openverse switched to pnpm is here: https://github.com/WordPress/openverse-frontend/pull/525

We do hoist. Vue requires this for now (I believe Vue 3 and the latest Nuxt versions might fix this but we're stuck on Nuxt 2 and Vue 2 for now until the Nuxt upgrade path is more sensible and stable).

We also had to enable [`enable-pre-post-scripts`](https://pnpm.io/cli/run#differences-with-npm-run), also for Vue support. Gutenberg also requires this option to be enabled as far as I can tell.

A significant difference for Openverse is that our repository is not a monorepo with workspaces. The [openverse-frontend](https://github.com/WordPress/openverse-frontend) repository follows the normal Nuxt structure of a monolith app with no `packages` folder (or any equivalent). We don't currently have any reason to do this (maybe in the future we will if our components become more general purpose or something). We've explored moving to a monorepo briefly but the rest of our stack is Python and there are significant issues with managing Python monorepos (even our [openverse-api](https://github.com/WordPress/openverse-api) repository is something of a Python monorepo and it's a pain to get editors to pick up the correct dependencies for each project in the repository due to how Pipenv functions).

I'll need to do some reading into how pnpm wants to manage workspaces and make sure that there's nothing specifically different that needs to be done.

Meanwhile, enabling pre and post scripts fixes a lot of the errors seen in the CI on the latest commit of this branch as of writing this comment.

**Comment by gziolo** [comment]
@sarayourfriend, thank you for a detailed response. I will process it early next week 👍🏻

I had a branch ready #36041 with changes for npm 8, but it doesn't seem to install correctly with GitHub Actions. It worked locally without any issues. So you can't compare install times using CI, for now. 😅 We could still be able to run some comparisons locally.

**Comment by gziolo** [comment]
> The PR where Openverse switched to pnpm is here: WordPress/openverse-frontend#525

It feels like the biggest challenge would be to update all commands from `npm run` to `pnpm` alternatives in the Gutenberg codebase. In particular, it's tricky with WordPress packages where we want to keep `npm run` for simplicity. The same applies to documentation targeting folks developing on top of WordPress. So this all boils down to identifying those places where we should teach Gutenberg contributors how to use pnpm. It's also important to figure out how to integrate a good check that ensures that all contributors start using pnpm and more importantly they see warnings on the terminal that they should switch to pnpm from npm.

I took a look at CI jobs like https://github.com/WordPress/gutenberg/runs/4898743594?check_suite_focus=true that run `pnpm install` and it doesn't seem to be significantly faster than `npm ci` with npm 6. I can't compare it with npm 8 because it doesn't install correctly as I mentioned in my previous comment.

**Comment by sarayourfriend** [comment]
> I took a look at CI jobs like https://github.com/WordPress/gutenberg/runs/4898743594?check_suite_focus=true that run pnpm install and it doesn't seem to be significantly faster than npm ci with npm 6. I can't compare it with npm 8 because it doesn't install correctly as I mentioned in my previous comment.

To be fair, the CI action you're looking at there is running cachelessly as there's a brand new `pnpm-lock.yaml`. I also think the cache strategy used by Gutenberg might not work for pnpm, but I'm not sure. We use a different approach in Openverse to use cached node_modules between installs.

I think that a "raw, from-zero" install using pnpm isn't going to be faster than npm as the main bottle neck is the network, not putting the files into node_modules. `pnpm` definitely shines for local installs where your local cache of packages is going to be significant if you've done development on any other moderately sized JavaScript projects. I think it could also speed up CI if the correct caching is used.

For the record, this is the caching we use for Openverse: https://github.com/marketplace/actions/setup-pnpm#use-cache-to-reduce-installation-time. We just follow the official recommendation for pnpm.

**Comment by sarayourfriend** [comment]
Taking another look at this PR today. Going to try to start from fresh and make more incremental changes. Obviously some of the changes I made broke things more than helped! I've also learned since that React Native doesn't play well necessarily with `pnpm` and requires some manual steps, which I was getting tripped up on.

Most likely I will start a new branch and run a fresh `pnpm import` and then take things step by step.

**Comment by gziolo** [comment]
> I've also learned since that React Native doesn't play well necessarily with pnpm and requires some manual steps, which I was getting tripped up on.

There are also issues with React Native forked dependencies and npm 8 on CI. It works correctly locally.

**Comment by sarayourfriend** [comment]
I made a lot of progress today in https://github.com/WordPress/gutenberg/pull/38624.

It's far from perfect and there are blockers (compressed-size-check doesn't support `pnpm` yet) but I got a lot closer today in that branch than I did on this PR. I am hopeful that there is a way to get everything passing except the compressed size check and the PR automation.

**Pull request closed without merging**
