### PR TITLE
Update theme.json reference docs to include more sections

### LINKED ISSUE #38620: Reference docs for `theme.json`: pull data from keys other than `settings` and `styles`
See https://github.com/WordPress/gutenberg/pull/38323/files#r801524958

The [reference docs for `theme.json`](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/) only contains data coming from the `settings` and `styles` keys. There are some missing sections, such as `customTemplates`, `templateParts`, or the `patterns` key being added https://github.com/WordPress/gutenberg/pull/38323

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Adds customTemplates, templateParts and patterns to the [theme.json living reference](https://developer.wordpress.org/block-editor/reference-guides/theme-json-reference/theme-json-living/).

Closes https://github.com/WordPress/gutenberg/issues/38620

## Why?

The reference only included theme.json Styles and Settings.

## How?

Adds customTemplates, templateParts and patterns to the document generator.

## Testing Instructions
I am not sure how to best preview the MD file.
I have built the docs with npm run docs:build and submitted the updated document as part of the PR.

### CODE REVIEW

**Comment by oandregal** [comment]
> I am not sure how to best preview the MD file.

You can preview it by going to the "Files changed" tab, then find the `.md` file and click the "View file" in the three dot menu:

Captura de ecrã de 2023-02-21 10-13-12

This is how it looks like at the moment:

Captura de ecrã de 2023-02-21 10-13-28

It'd be great to show the `customTemplates` and `templateParts` fields as a list or table.

**Comment by carolinan** [comment]
Yeah it is intended to atleast have a line break.

**Comment by carolinan** [comment]
@oandregal Do you have time to review this again?

**Comment by oandregal** [comment]
This is how it looks like now:

image

**Review by oandregal — APPROVED** [review]

**Comment by carolinan** [comment]
Thank you.

**Pull request merged**
