### PR TITLE
Docs: use markdown headings instead of links for API declarations

### LINKED ISSUE #33361: Docs: Generate proper markdown heading for API docs (enabling automatic "Table of Contents" for API pages)
## What problem does this address?

In the automatic generated DOCS for API details ( for example: https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/data/data-core.md ) the elements being documented (such as methods, selectors, action creators and so)  are being generated as links and not as headings (with proper level)

```
# WordPress Core Data
Namespace: `core`.
## Selectors
<!-- START TOKEN(Autogenerated selectors|../../../../packages/core-data/src/selectors.js) -->
<a name="canUser" href="#canUser">#</a> **canUser**
Returns whether the current user can perform the given action on the given
REST resource.
Calling this may trigger an OPTIONS request to the REST API via the
`canUser()` resolver.
```

This final markup doesn't allow to generate automatic Table of Contents for each page (with tools such as [`markdown-toc`](https://github.com/jonschlinkert/markdown-toc))

## What is your proposed solution?

In general, I think having Table of Contents sections in these API’s pages would help people to process and access the information in

I think having these links generated as proper headings levels for each item being documented (each selector in this case) would result in a more correct markdown while also enabling automatically generated Table of Contents for each API page

### PR DESCRIPTION
**Pull request by juanmaguitar**
Fixes https://github.com/WordPress/gutenberg/issues/33361

## Description
As per https://github.com/WordPress/gutenberg/issues/33361 this PR generates proper headings with _Symbol names_ (method names, selectors names, actions names, ...)

## How has this been tested?
Locally, by testing the output of commands such as 

```
npx docgen packages/core-data/src/selectors.js --output data-core-dummy.md && cat data-core-dummy.md
```

## Types of changes

Change in the Tool used to generated Documentation (API documentation markdown from JSDOC code comments)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by juanmaguitar** [comment]
BTW I couldn't find a way to test LOCALLY the final HTML of the docs (like in https://developer.wordpress.org/block-editor/ ) from the markdown files.

Is there any way to generate the final HTML (the one that will be served from https://developer.wordpress.org for example) in the development environment from the markdown files to test changes like the ones in this PR?

**Comment by oandregal** [comment]
:wave: @juanmaguitar you may want to do two things for this to be ready:

- rebase from `trunk` (I've just landed a related PR https://github.com/WordPress/gutenberg/pull/33384 )
- execute `npm run docs:build` to update all the auto-generated documentation for packages and reference guides

> Is there any way to generate the final HTML (the one that will be served from https://developer.wordpress.org for example) in the development environment from the markdown files to test changes like the ones in this PR?

You'd need to replicate a meta environment. I don't know how to do that, but the above command is enough to update the affected markdown files in this repo.

**Comment by juanmaguitar** [comment]
Thanks for the response @nosolosw

> you may want to do two things for this to be ready:
> - rebase from trunk (I've just landed a related PR Fix API docs for data reference guides #33384 )
> - execute npm run docs:build to update all the auto-generated documentation for packages and reference guides

both things done 👍

**Comment by juanmaguitar** [comment]
BTW I'm not sure I added so many people as reviewers. If I did, it wasn't on purpose. 

Captura de pantalla 2021-07-13 a las 15 40 33

@nosolosw is this some automatic action? shall I remove these reviewers added?

**Comment by oandregal** [comment]
> is this some automatic action? shall I remove these reviewers added?

Yeah, it's automatic. It's fine. Those are people that opted-in to become a reviewer for particular code paths using the [codeowners](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) feature (see [this file](https://github.com/WordPress/gutenberg/blob/trunk/.github/CODEOWNERS) in our repo).

**Comment by oandregal** [comment]
@juanmaguitar I see that the CI actions report some failing tests: `packages/docgen/test/formatter-markdown.js`. They need to be updated to account for the changes here as well. You can run the `docgen` tests locally by using the command `npm run test-unit -- packages/docgen/`.

**Comment by juanmaguitar** [comment]
> I see that the CI actions report some failing tests: packages/docgen/test/formatter-markdown.js. They need to be updated to account for the changes here as well. You can run the docgen tests locally by using the command npm run test-unit -- packages/docgen/.

Thanks for the explanation @nosolosw 
Tests updated to reflect changes in the code 👍

**Review by oandregal — APPROVED** [review]
Thanks for the contribution, @juanmaguitar ! I'm going to let the tests end and tomorrow will merge.

For context: once it's merged in `trunk`, the block editor handbook typically takes 15 to 30 minutes to be updated with the new contents.

**Comment by oandregal** [comment]
Juanma, I've also updated the title of the PR and assigned it some labels, as that's used in the changelog of the releases: the more informative the PR titles are the more informative the changelog for consumers.

**Comment by juanmaguitar** [comment]
>  I'm going to let the tests end and tomorrow will merge.

> I've also updated the title of the PR and assigned it some labels, as that's used in the changelog of the releases: the more informative the PR titles are the more informative the changelog for consumers.

Awesome. Thanks! 🙌

**Comment by oandregal** [comment]
For reference, this is the before/after in a couple of pages in the block editor:

[WordPress Core Data](https://developer.wordpress.org/block-editor/reference-guides/data/data-core/)

| Before | After|
|---|---|
| Screenshot 2021-07-14 at 10-29-29 WordPress Core Data Block Editor Handbook WordPress Developer Resources | Screenshot 2021-07-14 at 10-54-02 WordPress Core Data Block Editor Handbook WordPress Developer Resources |

[a11y package](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-a11y/)

| Before | After|
|---|---|
| Screenshot 2021-07-14 at 10-30-03  wordpress a11y Block Editor Handbook WordPress Developer Resources | Screenshot 2021-07-14 at 10-54-16  wordpress a11y Block Editor Handbook WordPress Developer Resources |

**Pull request merged**
