### PR TITLE
JSX Tag Name undefined

### PR DESCRIPTION
**Pull request by BenjaminZekavica**
Correction of JSX (JS Next) Code.

### CODE REVIEW

**Comment by Soean** [comment]
Thanks for you contribution. Can you explain why we need this div with the class `edit-post-header__custom-sidebar`?

**Comment by BenjaminZekavica** [comment]
@Soean Hi :) I saw in HTML Code of others CSS class properties and I think users can change it for Symantec code. What you can recommend? I try delete the DIV Wrapper but React want one Element to wrap this elements.

**Comment by talldan** [comment]
Hi @BenjaminZekavica - In the example code the tags `<>` and `</>` are react fragments:
https://reactjs.org/docs/fragments.html#short-syntax

It should be legal JSX. Are you using an up-to-date compiler (e.g. babel)?

**Comment by youknowriad** [comment]
@BenjaminZekavica This code is not false but it uses a recent JSX syntax for Fragments. You need to configure your babel config to support Fragments. https://github.com/WordPress/gutenberg/blob/master/packages/babel-preset-default/index.js#L69

**Comment by BenjaminZekavica** [comment]
@youknowriad @talldan Thanks :D :) Actually the problem was an false configuration.

**Pull request closed without merging**
