### PR TITLE
Add additional embed icons

### PR DESCRIPTION
**Pull request by chrisvanpatten**
## Description
This PR adds additional embed icons. Goes part of the way to addressing #9124.

Here's the full list of missing icons, with the ones this PR provides checked off:

- [ ] Animoto
- [ ] Cloudup
- [ ] CollegeHumor
- [x] DailyMotion
- [ ] Funny Or Die
- [x] Hulu
- [ ] Imgur
- [ ] Issuu
- [x] Kickstarter
- [x] Meetup
- [x] Mixcloud
- [ ] Photobucket
- [ ] Polldaddy
- [X] ReverbNation
- [ ] Screencast
- [x] Scribd
- [ ] Slideshare
- [ ] SmugMug
- [ ] SoundCloud
- [x] SpeakerDeck
- [x] TED
- [ ] VideoPress
- [ ] WordPress.TV

## How has this been tested?
Visual testing

## Screenshots
(I blurred out existing icons)

44410342-2e632f00-a532-11e8-8555-db5f19f7e5c9

edit_post_ _mindful_ _wordpress

edit_post_ _mindful_ _wordpress

~(I don't love the TED icon but the 20x20 grid is tough to work with for something like that.)~

## Types of changes
New icons

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I really wasn't happy with the TED icon, so I replaced it with a version based on their website's favicon, which is just a T.

edit_post_ _mindful_ _wordpress

**Comment by chrisvanpatten** [comment]
Travis failure looks unrelated!

**Comment by chrisvanpatten** [comment]
Pinging @jasmussen for a review on this too since I know you've been working on icons, and also I know @mtias is super busy :)

Would love to get this one in and open a separate PR for the other icons. These were all the easiest ones to find and I don't want the PR to get stale while I go hunting for the other icons.

**Comment by jasmussen** [comment]
Thank you for working on this. Your PRs are super welcome. 

I've perhaps noted this in the past, I have a personal aversion to _us_ (the open source community) becoming the maintainers of brand guidelines for third party blocks that are included. However given the user experience does make more sense without generic icons, and given those embeds are already on a whitelist, we might as well lean into it. 

Also, I appreciate the fact that we can include these as inline SVGs instead of having to canonize them into an icon set which automatically makes them more unmaintainable. 

Some questions:

- Now that we are adding logos, what do we do about sizing them? Do we size them optically next to icons, or do we lean towards them being crisp?
- What do we do in cases where the service doesn't have an obvious icon to use, like Ted for example?
- What do we do about brand guidelines, [where in the case of Facebook we're technically not allowed to use their logo at all](https://en.facebookbrand.com/guidelines/brand)? In the case of social sharing plugins this has probably been ignored. It might stay ignored with WordPress, though our size is a fair bit larger.

Overall, since we are essentially holding 3rd parties in our hands here, I personally think we should use minimal creativity. But I also recognize that I'm biased and I'm noting non-issues here. For that reason, I've widened the review range a bit :D 

I think this PR will slide right in despite my thoughts, and I wouldn't object to that, to be clear!

**Comment by chrisvanpatten** [comment]
Also FWIW this is no longer merge-ready because it needs the a11y attributes added (and I don't know that it would cleanly merge anymore because a few other PRs touching this file have been merged in). I will address that this week!

**Comment by chrisvanpatten** [comment]
I'm happy to revisit this but I could use a bit of clarity on whether this is still a problem we want to solve, or would rather get the third parties involved to maintain their own icons somehow…

**Comment by tofumatt** [comment]
I don't think it's realistic to demand/expect third-parties to maintain their icons. It'd be great, and it's an open-source project where they certainly *can* submit fixes should they care to, but that's no excuse for not being proactive about it.

I think we should solve this problem 👍

We should add the icons; if someone notices one is wrong they'll correct us, hopefully 😄

**Comment by chrisvanpatten** [comment]
@tofumatt I tend to agree. I think the only potential concern is the legal aspect but we already do it for a handful of brands and I assume there's no formal agreement in those cases anyway.

In any case I'll give this a refresh this week 🎉

**Comment by chrisvanpatten** [comment]
I'm going to close this out — it would take a fair amount of manual labor to rebase this and also my icons weren't too great tbh. Someone else who's better at SVG prep (looking at you, @field2) could probably do a better job of this.

**Pull request closed without merging**
