### PR TITLE
Navigation block: Remove browser default padding from the two submenu buttons

### PR DESCRIPTION
**Pull request by carolinan**
## What?

When the Navigation Block: "Open on click" setting is used, the submenu button has some extra padding from browser styles. This padding means that in vertical menus, the button text on the submenu **parent** item does not align with the other links.

This PR sets the padding to 0.

Closes 
https://github.com/WordPress/gutenberg/issues/50722

## Why?

To make the menu items align better.

## How?

The implementation of the sub menu toggle button is a little bit different in the page list block and in the "regular" sub menu of navigation links. So there are two style changes, one for each button.

## Testing Instructions
1. Add a vertical navigation block with a page list that has a submenu, and a regular submenu built with links.
2. Enable the "Submenus, open on click" option.
3.  Confirm that all parent menu items and their arrow buttons are aligned correctly.
4. Confirm that both buttons are clickable.

## Screenshots or screencast 
I am using a classic theme that does not add any extra CSS.
To clarify, the "Sample page" text is the page list submenu parent item, and
"preformatted" is a post title, it is the regular submenu parent item.

Before:
The submenu parent item is missaligned.

After:
With the PR applied, all menu items align.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Thanks for catching this detail. Giving a tentative green light because the code looks good and the issue seems real. 

But it's really sensitive code, I wonder, what's a good way to test this beyond more reviews?

**Comment by carolinan** [comment]
Like visual regression tests?

**Review by mikachan — APPROVED** [review]
This fixes the mismatch in spacing for me 🎉

I'm still seeing a slight difference in positioning between the buttons and the anchor tags when toggling the "Open on click" option, which would be nice to fix too, but I don't think it should hold up this PR:

https://github.com/WordPress/gutenberg/assets/1645628/d54f7180-ed43-42c6-abc3-6fdaebcdce3c

**Review by mikachan — APPROVED** [review]
LGTM! I'm not seeing the slight spacing difference when toggling the "Open on click" option anymore 🎉

**Pull request merged**
