### PR TITLE
Editor: Polish the style of some of the post summary rows.

### PR DESCRIPTION
**Pull request by youknowriad**
Related to #59689 

## What?

This PR iterates towards the designs shared in #59689 
It addresses the following points.

 - Makes the PostStatus design similar to all the other rows for consistency.
 - Makes the "Add post excerpt" button more visible for better usability.
 - Align the popover of the "post publish date" with the rest of the popovers.

## Testing Instructions

Screenshot 2024-05-14 at 10 05 49 AM

### CODE REVIEW

**Comment by jameskoster** [comment]
> Makes the PostStatus design similar to all the other rows for consistency.

I still think Status is worth highlighting visually somehow, compared with other data points. But we can revisit that, so I'm happy to go with this.

> Makes the "Add post excerpt" button more visible for better usability.

Excerpt UX needs fine-tuning, which I appreciate may need to happen separately:

* To satisfy a11y requirements I believe it will need to use the `link` Button variant to add the underline. 
* Ideally the excerpt value in the inspector is only updated when you close the dialog. This should probably be the case for the slug too.
* Also for a11y, could we add an inline 'Edit' button when the excerpt is set?

Screenshot 2024-05-14 at 11 34 43

**Comment by youknowriad** [comment]
@jameskoster the excerpt is truncated to maximum 4 lines, that said, the truncate like that only works if the text is within a "block" element which means the "Edit" link can't be on the same line as the excerpt unless we remove the truncate.

**Comment by jameskoster** [comment]
It can work if we truncate by character count and display inline-block. I had a draft PR [here](https://github.com/WordPress/gutenberg/pull/61208) to achieve it, but perhaps that's not the best approach.

Worst case scenario the 'Edit' button will need to live on it's own line beneath the excerpt, but my understanding is the dedicated button will be necessary.

**Comment by youknowriad** [comment]
If I remember properly, truncating using characters like that is not something that we can do for i18n reasons.

**Comment by youknowriad** [comment]
What's wrong with removing the truncate entirely? Why do we really need it?

**Comment by jameskoster** [comment]
> What's wrong with removing the truncate entirely? Why do we really need it?

It's a guardrail against extremely long (manually added) excerpts dominating the sidebar. An edge case perhaps, but something to consider don't you think?

If the inline button isn't feasible, it wouldn't be the end of the world to place the button immediately below the text:

Screenshot 2024-05-15 at 13 54 33

**Comment by youknowriad** [comment]
I applied the latest suggestion, let me know how it feels.

**Review by jameskoster — APPROVED** [review]
I think there may be other options to explore for the 'Edit excerpt' button, but this improves on trunk and shouldn't hold up the other enhancements.

**Pull request merged**
