### PR TITLE
Block Theme Previews: Remove "Looking for Template Parts?" hint.

### LINKED ISSUE #56668: Block Theme Previews: Hide the "Looking for Template Parts?" warning banner
## What problem does this address?

When previewing a theme using the Block Theme Previews feature, a user can be "distracted" by the "Looking for template parts?" banner, when they are actually supposed to do more important things, like trying out Styles. This might be confusing for first-time users.

## What is your proposed solution?

Hide this banner from the Site Editor when BTP is in use, resulting in a "cleaner" experience:

|Before|After|
|-|-|
|image|image|

cc: @scruffian

### PR DESCRIPTION
**Pull request by juanfra**
## What?

Remove "Looking for Template Parts?" hint.

Fixes https://github.com/WordPress/gutenberg/issues/56668

## Why?

The hint has been there for two releases and it might be confusing for first-time users.

## How?

Removing the template part hint file and call.

## Testing Instructions

1. Go to Appearance > Themes
2. Preview a theme (TT3)
3. Confirm that the hint is not there.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/252415/6b955032-000e-47e3-90d6-2a62773b8848

### CODE REVIEW

**Comment by richtabor** [comment]
> We could probably remove the notice for 6.5 even, as it’s been there for two releases.

What about just removing it entirely? I think we're good to do that.

**Comment by juanfra** [comment]
Absolutely, sounds good 👍

**Review by carolinan — APPROVED** [review]

**Comment by juanfra** [comment]
Thanks, Carolina!

Adding the `Backport to WP Beta/RC` label as per Rich's comment [here](https://github.com/WordPress/gutenberg/issues/56668#issuecomment-1837846508) about removing the hint for 6.5

**Comment by youknowriad** [comment]
Given that RC1 is today I'm removing this one from 6.5 as non essential.

**Pull request merged**
