### PR TITLE
[RNMobile] Cover block: Support `isDark` attribute

### LINKED ISSUE #18024: Styling broken when previewing Home page of new WP.com site
When previewing the Home page of a newly created site running the Alves theme, some styling is broken.

### Expected behavior
Styling is consistent with block editor and web browser previews.

### Actual behavior
Some styling is broken when previewing the page within the app.

### Steps to reproduce the behavior
1. Create a new WP.com site
2. Choose the "Alves" theme under Business
3. Complete the site creation by choosing a domain, etc.
4. From the "My Site" view choose "Pages"
5. Choose "Home"
6. Observe that the heading "Raise Your Helping Hand" is white
7. Tap the ellipses at the top right and choose "Preview" in the bottom sheet
8. Observe that "Raise Your Helping Hand" is black
9. Tap the globe icon to preview in a browser
10. Observe that "Raise Your Helping Hand" is white

https://user-images.githubusercontent.com/2092798/155572530-28025312-5ddd-4cdd-aa46-b45f1bea5058.MP4

### Other context

This only seems to affect the Home page. When creating a new page on the site with the same design, the previews look correct.

### PR DESCRIPTION
**Pull request by fluiddot**
## What?

Add support for the `isDark` attribute in the native version of the editor. This attribute improves the color contrast between the background and text, by changing the text color to white/black depending on the overlay color and opacity. As a side note, this only applies to text elements that don't have a color set.

## Why?

This PR aims to fix https://github.com/wordpress-mobile/WordPress-iOS/issues/18024 and add support for the `isDark` attribute introduced in https://github.com/WordPress/gutenberg/pull/33541.

### Extract `useCoverIsDark` hook to a file
Since this hook holds logic that can be used on both platforms, I decided to extract it to a new file.

I'd like to note that In the web version, when the opacity of the block is lower than or equal to 50%, it calculates the average color of the content (i.e. image or video) and uses it for determining the `isDark` value. However, the library for that purpose only works on web, so until we provide a workaround for this calculation in native, this case won't be handled.

**NOTE:** This might introduce discrepancies when displaying a Cover block, especially on the native version when the `isDark` attribute changes by modifying the opacity.

Web|Native
--|--
<video src=https://user-images.githubusercontent.com/14905380/165773989-34656220-3ab0-4c8a-92ed-9ab363af8eb7.mp4>|<video src=https://user-images.githubusercontent.com/14905380/165774027-270aa6fb-f1f7-4974-a6dc-dc24d33aad1d.mp4>

### Handle`isDark` attribute in native
Similar to how it's handled in the web version, the hook is called and uses the value returned to set dark or light color to the content via the `childrenStyles` attribute.

Additionally, these changes cover the case spotted in https://github.com/wordpress-mobile/WordPress-iOS/issues/18024#issuecomment-1110839936 where the `is-light` class is set when upgrading the block from an older version. The workaround for this is basically to ensure that, if `isDark` attribute is `true`, the `is-light` class is removed.

### Check light/dark modes when `isDark` attribute changes

**NOTE:** As outlined in https://github.com/WordPress/gutenberg/pull/40691#issuecomment-1113115074, this functionality is not working when using themes that provide global styles. In order to test the changes, consider using a theme without global styles like `Twenty Twenty-One` or `Alves`.

1. Open a post/page.
2. Add a Cover block and set an image.
3. Observe that the text color is black, as the default dark mode value is `false`.
4. Open the block settings by tapping on the ⚙️ button.
5. Scroll down to the "Overlay" section and modify the opacity.
6. Observe that when opacity is greater than 50%, the text color is white.
7. Observe that text color doesn't change when opacity is less than or equal to 50%.
8. Set opacity greater than 50%.
9. Change the overlay color to a dark one.
10. Observe that the text color is black.

### Check potential regressions in the web version
1. Open a post/page.
2. Add a Cover block and set an image.
3. Observe that the text color is black, as the default dark mode value is `false`.
4. Open the block settings.
5. Scroll down to the "Overlay" section and modify the opacity.
6. Observe that when opacity is greater than 50%, the text color is white.
7. Observe that when opacity is less than or equal to 50%, the text color is black if the image is light, and white if the image is dark.
**NOTE:** There's [a known bug](https://github.com/WordPress/gutenberg/issues/37031) related to setting the black color even for images that are dark. So, expect that for most images the color will be black.
8. Set opacity greater than 50%.
9. Change the overlay color to a dark one.
10. Observe that the text color is black.

### Native and web versions should produce the same HTML
1. Open a post/page in the web version.
2. Add a Cover block and set an image.
3. Open the block settings and set the opacity of the block to be greater than 50%.
4. Save the post/page.
5. Open the same post in the app.
6. Observe that the Cover block looks equal to the web version.
7. Observe that the HTML of the post/page remains unmodified by comparing the HTML of both versions.
8. Go to the web version of the editor.
9. Change the opacity of the block to less than 50%.
10. Repeat steps 4 - 7.

### Check starter page templates
1. Open the app.
1. Create a new WP.com site.
1. Choose the "Alves" theme under Business.
1. Complete the site creation by choosing a domain, etc.
1. From the "My Site" view choose "Pages".
1. Choose "Home".
1. Observe that the heading "Raise Your Helping Hand" is white.
1. Tap the ellipses at the top right and choose "Preview" in the bottom sheet.
1. Observe that "Raise Your Helping Hand" is white.
1. Tap the globe icon to preview in a browser.
1. Observe that "Raise Your Helping Hand" is white.

## Screenshots or screencast 

https://user-images.githubusercontent.com/14905380/165783113-77435b9e-63e8-44f9-b9ff-2075da37f778.mp4

### CODE REVIEW

**Comment by jhnstn** [comment]
@fluiddot I'm unable to get the mobile test steps to pass. I've tried on iPhone 11/ iOS 14.8 and Pixel 6/ Android 12.
I'm using the "twenty twenty two" theme if that might have some impact.

**Comment by fluiddot** [comment]
> @fluiddot I'm unable to get the mobile test steps to pass. I've tried on iPhone 11/ iOS 14.8 and Pixel 6/ Android 12.
> I'm using the "twenty twenty two" theme if that might have some impact.

@jhnstn Good catch! Looks like this is expected for dark themes, as it's outlined in [this PR's description](https://github.com/WordPress/gutenberg/pull/33541):

> One issue to be aware of is that in a dark theme (for example Quadrat), when the cover block is set to a light background, the default text color for the theme will still be used. Perhaps in a dark theme we should default the block to have a white background and dark text, but that is a much larger change, and this PR doesn't make that problem worse so we can dealt with it in the future.

Could you try using a different theme and check if the issue persists? Thanks 🙇 !

**Comment by jhnstn** [comment]
> Could you try using a different theme and check if the issue persists? Thanks 🙇 !

I switched to "Quadrat Black" and the text is still not changing:

https://user-images.githubusercontent.com/744755/165834024-3b2c8519-435b-4adf-9f34-e59a2d754455.MP4

Also forgot to note previously that with "twenty twenty two", the cover text was changing colors on production web.

**Comment by fluiddot** [comment]
> > Could you try using a different theme and check if the issue persists? Thanks 🙇 !
> 
> I switched to "Quadrat Black" and the text is still not changing:
> 
>  RPReplay_Final1651175218.MP4 
> Also forgot to note previously that with "twenty twenty two", the cover text was changing colors on production web.

That's interesting, looks like depending on the theme these changes behave differently 🤔. I'm afraid this is related to how we calculate the final color to be applied in the `RichText` component:

https://github.com/WordPress/gutenberg/blob/d68091590f99a7c019d312929fab5f7f6722241b/packages/block-library/src/cover/edit.native.js#L271-L273

https://github.com/WordPress/gutenberg/blob/4ccdee3b0004ca9aa464151b93dfdced8502dcac/packages/rich-text/src/component/index.native.js#L1268-L1271

https://github.com/WordPress/gutenberg/blob/4ccdee3b0004ca9aa464151b93dfdced8502dcac/packages/rich-text/src/component/index.native.js#L1204-L1209

When using `Alves` or `Twenty Twenty-One` themes, it uses the color from `parentBlockStyles` that was set by the Cover block because the style color, which has higher preference, is not defined:

**Using `Twenty Twenty-One` theme - Colors ordered by preference to be used by the `RichText` component:**
tt1-color

However, when using a theme that defines global styles like `Quadrat black` or `Twenty Twenty-Two`, the `RichText` component uses the color from the global styles instead of the one defined by the Cover block:

**Using `Quadrat black` theme - Colors ordered by preference to be used by the `RichText` component:**
quadrat-black-color

**NOTE:** An easy way to identify themes that define global styles is by checking if the menu item `Editor` is displayed under the `Themes` section in the site dashboard on the web version.

Screenshot 2022-04-29 at 11 19 08

<hr>

As far as I checked, this behavior differs from the web version where the global styles have less preference than the parent styles, in this case, defined by the Cover block:

Screenshot 2022-04-29 at 11 30 50

@jhnstn Not sure if we'd like to address the style preference issue in this PR, as it might be a bit complex, so I'm wondering if we could tackle it in a different PR and create an issue as a follow-up for that, wdyt?

**Comment by jhnstn** [comment]
> @jhnstn Not sure if we'd like to address the style preference issue in this PR, as it might be a bit complex, so I'm wondering if we could tackle it in a different PR and create an issue as a follow-up for that, wdyt?

💯  I wouldn't want to attempt those changes here. I'll test again with the a theme that lets me try out these specific changes.

**Comment by fluiddot** [comment]
> > @jhnstn Not sure if we'd like to address the style preference issue in this PR, as it might be a bit complex, so I'm wondering if we could tackle it in a different PR and create an issue as a follow-up for that, wdyt?
> 
> 💯 I wouldn't want to attempt those changes here. I'll test again with the a theme that lets me try out these specific changes.

Agreed, I'll create a new issue as a follow-up on this 👍.

**Review by jhnstn — APPROVED** [review]
@fluiddot I was able to test out the changes on mobile and web. Everything worked as expected. I was unable to test the starter page templates however. I was running into issues creating a new site on mobile with my Automattic account. Overall the changes look good, nice work!

**Comment by fluiddot** [comment]
Thanks for the review @jhnstn 🙇 !

> I was unable to test the starter page templates however. I was running into issues creating a new site on mobile with my Automattic account. Overall the changes look good, nice work!

It would be great to test the starter page templates as it's the issue that originated these changes ([reference](https://github.com/wordpress-mobile/WordPress-iOS/issues/18024)). Regarding the issues creating a new site, I'm wondering if they are related to actual bugs, could you share what you encountered? Thanks!

@SiobhyB as I also assigned you as a reviewer, I'm wondering if you could take a quick look at the "Check starter page templates" test case. Thanks for the help 🙇 !

**Comment by fluiddot** [comment]
> > > @jhnstn Not sure if we'd like to address the style preference issue in this PR, as it might be a bit complex, so I'm wondering if we could tackle it in a different PR and create an issue as a follow-up for that, wdyt?
> > 
> > 
> > 💯 I wouldn't want to attempt those changes here. I'll test again with the a theme that lets me try out these specific changes.
> 
> Agreed, I'll create a new issue as a follow-up on this 👍.

**FYI** I've just created [this issue](https://github.com/WordPress/gutenberg/issues/40786) as a follow-up.

**Review by SiobhyB — COMMENTED** [review]
Interestingly, I wasn't able to reproduce the original issue on an iOS simulator. I noticed Tanner mentioned there were times when the issue wasn't reproducible for him at https://github.com/wordpress-mobile/WordPress-iOS/issues/18024#issuecomment-1051237525, too. 🤔 

I _was_ able to reproduce the original issue on both a physical Android and iOS device, however.

I wanted to double-check that everything worked as expected on my physical devices, given my difficulty reproducing on an emulator, so created installable builds at https://github.com/wordpress-mobile/WordPress-Android/pull/16466 and https://github.com/wordpress-mobile/WordPress-iOS/pull/18495. 

Everything seemed good on my Android device, but I'm still seeing the issue with the text appearing black in the preview on my iOS device. I see the issue when previewing pages for existing sites and after creating a brand new site from scratch. 

I noticed the WordPress.com toolbar in the top of the second Android screenshot, so not sure if that may be relevant to the issue appearing fixed there.   

@fluiddot, let me know if I'm perhaps missing something here or if I can help with any further testing. 

### iOS

| `trunk` on physical iPhone XR | Changes on physical iPhone XR |
| ------------- | ------------- |
|  |  

### Android

| `trunk` on physical Pixel 6 | Changes on physical Pixel 6 |
| ------------- | ------------- |
|  |

**Comment by fluiddot** [comment]
> Interestingly, I wasn't able to reproduce the original issue on an iOS simulator. I noticed Tanner mentioned there were times when the issue wasn't reproducible for him at [wordpress-mobile/WordPress-iOS#18024 (comment)](https://github.com/wordpress-mobile/WordPress-iOS/issues/18024#issuecomment-1051237525), too. 🤔

That's interesting, in my case, I was able to reproduce it on both simulators and physical devices 🤔.

> I _was_ able to reproduce the original issue on both a physical Android and iOS device, however.

👍 

> I wanted to double-check that everything worked as expected on my physical devices, given my difficulty reproducing on an emulator, so created installable builds at [wordpress-mobile/WordPress-Android#16466](https://github.com/wordpress-mobile/WordPress-Android/pull/16466) and [wordpress-mobile/WordPress-iOS#18495](https://github.com/wordpress-mobile/WordPress-iOS/pull/18495).

Great, thanks for generating the installable builds 🙇.

> Everything seemed good on my Android device, but I'm still seeing the issue with the text appearing black in the preview on my iOS device. I see the issue when previewing pages for existing sites and after creating a brand new site from scratch.

Oh, when I tested locally using my devices I checked that the fix worked on both platforms 🤔. I noticed that the WP-iOS PR is pointing to the latest commit of https://github.com/wordpress-mobile/gutenberg-mobile/pull/4808, but the JS bundle for iOS wasn't updated. I think that explains why you can reproduce it on iOS and not on Android. I'm going to update the bundle and update both GB-mobile and WP-iOS PRs so the iOS installable build reflects the changes from this PR 💨.

> I noticed the WordPress.com toolbar in the top of the second Android screenshot, so not sure if that may be relevant to the issue appearing fixed there.

I'd say that is not related to these changes, or at least it's not expected.

**Comment by fluiddot** [comment]
> @fluiddot, let me know if I'm perhaps missing something here or if I can help with any further testing.

@SiobhyB As I commented [here](https://github.com/WordPress/gutenberg/pull/40691#issuecomment-1116120466), I'm going to update the JS bundle in the [GB-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4808) and generate a new iOS installable build. I'll let you know when it's ready to double-check that the issue was caused by the out-to-date bundle and not the changes 🤞 .

**Comment by jhnstn** [comment]
> Regarding the issues creating a new site, I'm wondering if they are related to actual bugs, could you share what you encountered? Thanks!

The issues were unrelated to the app for sure. There might have been an issue with the WP.com API but I'm fairly certain the issue is with my Automattic account and the WP.com store code. 

I can spin up the installable builds and try again with my test accounts.

**Comment by fluiddot** [comment]
> > Regarding the issues creating a new site, I'm wondering if they are related to actual bugs, could you share what you encountered? Thanks!
> 
> The issues were unrelated to the app for sure. There might have been an issue with the WP.com API but I'm fairly certain the issue is with my Automattic account and the WP.com store code.

Great, thanks for clarifying it 👍.

> I can spin up the installable builds and try again with my test accounts.

That would be great, thanks @jhnstn ! I already triggered a new build, I'll post a comment in the PR once they're ready to use.

**Review by SiobhyB — APPROVED** [review]
@fluiddot, aha, you're right, sorry for not spotting the out-of-date bundle! I saw the new build you generated is available now and confirmed the issue is fixed there:



All looks good from my side, thanks for fixing this 🙇‍♀️

**Comment by fluiddot** [comment]
Thanks @SiobhyB for checking it 🙇  ! 

I was about to comment that the installable build is ready but you beat me 😅:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/18495#issuecomment-1116011952

**Comment by fluiddot** [comment]
@jhnstn @SiobhyB I'd also appreciate it if you could also review the [GB-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4808). Note that the `Check Correctness` job is failing but, as it's happening on other PRs in the Gutenberg Mobile repository, we can omit it until it's fixed in `trunk`.

**Pull request merged**
