### PR TITLE
Add Hide teaser help text in More block

### PR DESCRIPTION
**Pull request by samikeijonen**
## Description
Adds Hide teaser help text in More block as mentioned in #2146.

## How has this been tested?
- Run `npm test` without errors.
- Tested toggling the Hide teaser help in More block.

## Types of changes
Adds Hide teaser help text in More block.

### Toggle off

hide-teaser-toggle-off

### Toggle on

hide-teaser-toggle-on

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by samikeijonen** [comment]
Couple of notes.

Label text and help text are now both pretty long. What if we have a short label text. For example *Hide the teaser*.

I'm not sure where to put `getHideTeaserHelp ` function. I just added that in the last now.

**Comment by michelleweber** [comment]
How about "_Use the "More" tag_" for the main label or "_Hide content with the "More" tag_" -- there's already a term for it, so using "teaser" adds some confusion, I think -- and then for the status labels, something like:
- Toggle to display partial post content on the home and index pages
- Displaying partial post content on the home and index pages

I will think on this some more; I think we can be clearer still.

**Comment by samikeijonen** [comment]
Agreed that teaser is adds some confusion. At least it did for me.

> "Use the "More" tag"

This would be little incorrect. The More tag block has already been added. So this setting is only for hiding the content before the more tag.

> "Hide content with the "More" tag"

I like this more (heh :)).

**Comment by samikeijonen** [comment]
hide teaser setting: new text is still pretty long

^ With other languages  that would probably in two lines. Can we still think something shorter?

**Comment by michelleweber** [comment]
Okay! Thanks very much for the explanations. So! I don't know that there's much of a way to shorten this without making the labels pretty useless or really rough-sounding; some things just need explanation. Some options...

Hide content before the "More" tag
- Toggle this on to hide this content on single posts
- Hiding content before the "More" tag on single posts

Hide intro content
- Toggle this on to hide the content before the "More" tag on the individual post
- Hiding content before the "More" tag on the individual post

**Comment by samikeijonen** [comment]
I updated wording a little bit. How does this sound.

Hide intro content

- Toggle to hide content before the "More" tag on single post.
- Hiding the content before the "More" tag on single post.

I left _Toggle to hide_ because that would be more inline with other help texts. I left _single post_ because I think it's more common word that individual.

**Comment by jasmussen** [comment]
This feature is very confusing, and as such the help text is very confusing to author as well. 

In general I would suggest, the less text, the better, but if it's hard to understand what this toggle does in the first place, it's definitely in need of good help text. 

CC: @karmatosed — with your vast backlog, do you recall what this does? What would a post with a more tag look like in an archive view, if you had this enabled?

**Comment by samikeijonen** [comment]
> What would a post with a more tag look like in an archive view, if you had this enabled?

In archive views it would look the same as disabled. It doesn't affect archive views at all, only single views.

**Comment by jasmussen** [comment]
The "confused" emoji Github reaction looks disapproving, which I'm not, so instead I'm just going to note that this just makes it even more confusing to me :D 

So I hope Tammie or other gutenbergers will chime in and help elaborate.

**Comment by samikeijonen** [comment]
Any tips how to proceed with this? The feature itself is pretty confusing and hard to understand so it needs different label text or label with help text.

**Comment by karmatosed** [comment]
Panning out, if it's so confusing should we have it as a feature? I know it's there to add a way to read more of the post, but maybe it just doesn't have optional behaviour? I just feel we're spiralling in complexity here.

**Comment by jasmussen** [comment]
+1 I'm still not sure what it does. Is there a way we can find out how many people use this?

**Comment by samikeijonen** [comment]
The More block itself should naturally stay.

**Comment by jasmussen** [comment]
Oh, I see! 

So to summarize what's going on: There's a "stream" view (when you view the post on the blog homepage, or in archives), and there's the "full" view (when you're looking at the permalink). The More tag allows you to choose what shows up on the stream view, and what is then shown on the archive view. The additional toggle allows you to _hide_ the text that comes before the More tag, on the archive view. 

I feel like the fact that it's so hard to explain and so hard to understand suggests we should remove this feature.

**Comment by jasmussen** [comment]
> On the single view :)

┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻

**Review by tofumatt — CHANGES_REQUESTED** [review]
To chime in here: this feature seems very confusing and complex; I think we should just remove it rather than try to clarify it.

**Comment by gziolo** [comment]
Can we use something like:

> Hide the teaser on the single view page.

**Comment by afercia** [comment]
I'd like to suggest to review the term used here. "Teaser" doesn't make much sense for users and it's also difficult to translate. More details: https://github.com/WordPress/gutenberg/issues/8974#issuecomment-435575054

**Comment by youknowriad** [comment]
Related #12785

We need a decision on this PR. Remove or update the wording.

**Comment by afercia** [comment]
See also https://github.com/WordPress/gutenberg/issues/8974#issuecomment-435575054

**Comment by afercia** [comment]
I'd like to propose something along the lines of the screenshot below:

screenshot 2018-12-28 at 14 44 09

As discussed at length during the implementation of the switch toggle, for better accessibility:
- an UI control accessible name (the label) should not change dynamically
- the state should indicated separately: a textual representation of the state is the only guarantee this information can be perceived by everyone

**Comment by gziolo** [comment]
There is also this comment from @afercia https://github.com/WordPress/gutenberg/issues/8974#issuecomment-450347737:

> The help text has been changed in #11587, but still not so clear:
> 
> ```
> More
> Mark the excerpt of this content.
> Content before this block will be
> shown in the excerpt on your
> archives page.
> 
> 
> Hide the teaser before the "More" tag
> ```
> I'd like to suggest to change it into:
> 
> ```
> More
> Content before this block will be
> shown in the excerpt on your
> archive pages.
> 
> 
> Hide the excerpt on the full content page
> ```

I think it makes a lot of sense. Can this PR be updated to reflect this proposal?

**Comment by gziolo** [comment]
I'm merging this PR into my own branch to apply changes.

**Comment by gziolo** [comment]
Moved to #13630 and updated with the recent version of master together with changes applied based on feedback from @afercia.

**Pull request closed without merging**
