### PR TITLE
Post Editor: Force iframe editor when zoom-out mode

### LINKED ISSUE #64259: Zoom Out: "Desktop (50%)" view hides breadcrumbs and doesn't work in non-iframe editor
### Description

There seem to be two issues with the "Desktop (50%)" view introduced in #63870:

- ~~The block breadcrumbs is hidden~~ This appears to be the expected behavior, see [this comment](https://github.com/WordPress/gutenberg/pull/63870#issuecomment-2269181015).
- Doesn't work in non-iframe editor

### Step-by-step reproduction instructions

- Open the post editor.
- Click the View button and Select "Desktop (50%)"
- The block breadcrumbs should be hidden.
- Enalbe Custom fields.
- Click the View button and Select "Desktop (50%)"
- Nothing should happen.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/6e889f10-1b75-416f-aab4-35c6ef523563

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #64259, #62943
Alternative to #64264

## What?

This PR forces the iframe editor when in zoom-out mode to ensure the zoom-out functionality works properly.

## Why?

Currently, the `useShouldIframe` hook will prevent the editor from being an iframe if all blocks are not all v3 or have meta boxes. If it is not an iframe, the new view "Desktop (50%)" and the zoom-out mode for experimental pattern inserters will not work.

## How?

Update the `useShouldIframe` hook to force the iframe editor when in zoom-out mode.

## Testing Instructions

- Enable "Enable zoomed out view when patterns are browsed in the inserter" from the experimental page beforehand.
- Enable custom fields in the post editor. This will make the editor not an iframe.
- If you select "Desktpp (50%)" from the view options, the editor will be an iframe, and zoom out should work.
- If you select the pattern category from the main inserter, the editor will be an iframe, and zoom out should work.

## Screenshots or screencast 

https://github.com/user-attachments/assets/451c3679-fcf0-492f-be9c-ebfd3ea7ef9a

### CODE REVIEW

**Review by stokesman — APPROVED** [review]
Nice that this turned out so simple. It seems like a more complete solution than #64264. Though if #64247 or #64351 get merged then it will remove the need for this, right? Regardless this LGTM.

**Comment by t-hamano** [comment]
Thanks for the review!

> Though if https://github.com/WordPress/gutenberg/pull/64247 or https://github.com/WordPress/gutenberg/pull/64351 get merged then it will remove the need for this, right?

I think this PR is needed anyway. Even if the meta box is not present, if a block below v2 is registered, the editor is not an iframe. So I think we should always check if we are in zoom-out mode.

**Comment by t-hamano** [comment]
Just to be on the safe side, I'll wait a day or so before merging this PR. Let me know if you have any other concerns.

**Comment by stokesman** [comment]
> Even if the meta box is not present, if a block below v2 is registered, the editor is not an iframe.

Right. I would have realized that with a little more thought 😄.

**Pull request merged**
