### PR TITLE
Block editor: pass assets through block_editor_settings_all

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

See #35018 and #33212 for discussions.

This PR attempts to solve two problems:

* Currently it is very hard for themes to add styles to the editor through the WP dependency system. `add_editor_style` only accepts URLs, not WP dependency handles for styles. This makes it impossible to use `wp_add_inline_style`. We need a way for themes to be able to add WP dependency handles to the block editor's content (iframe) just like blocks can through registration.
* Currently we hackily load styles and scripts in the iframe through a global. This should be done with block editor settings instead.

The idea: allow anyone (including themes) to add style and script dependencies for the block editor content through the block editor settings.

```php
add_filter(
	'block_editor_settings_all',
	function( $settings ) {
		wp_register_style( 'my-theme-stylesheet', get_stylesheet_uri() );
		$settings['assets']['styles'][] = 'my-theme-stylesheet';
		return $settings;
	}
);
```

And if in the future we make themes that are just CSS and JSON, the use case of inline styles for dynamic styling should disappear.

~~To do: add test with the above example code.~~
To do: load the styles outside iframed editors and prefix the rules.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for working on this. How can I best help test this?

**Comment by oandregal** [comment]
Hey, took a look at this and read through a bit of related context (iframe). I see how this PR is replacing `__editorAssets` by passing the data to the iframe via `settings.assets`. This change looks fine to me.

I'm struggling to see how this changes the status quo for the second item mentioned in the description ("Currently it is very hard for themes to add styles to the editor through the WP dependency system."). Is this perhaps something you plan to add in a follow-up?

**Comment by ellatrix** [comment]
> I'm struggling to see how this changes the status quo for the second item mentioned in the description ("Currently it is very hard for themes to add styles to the editor through the WP dependency system."). Is this perhaps something you plan to add in a follow-up?

No, this is done in this PR. The following is now possible:

```php
add_filter(
	'block_editor_settings_all',
	function( $settings ) {
		wp_register_style( 'my-theme-stylesheet', get_stylesheet_uri() );
		$settings['assets']['styles'][] = 'my-theme-stylesheet';
		return $settings;
	}
);
```

**Comment by gwwar** [comment]
I tried the branch paired with wordpress-develop master and am seeing the following error in logs when loading the post-editor:
CleanShot 2021-10-26 at 12 13 08@2x

https://github.com/WordPress/wordpress-develop/blob/98bf67e02b0a4b4aa3848f4e8266c4fd66cdaad0/src/wp-includes/script-loader.php#L2451

Are there extra testing instructions that we should follow?

**Comment by carolinan** [comment]
Still testing but I am seeing:
`Notice: Undefined index: assets in /var/www/html/wp-content/plugins/gutenberg-git/lib/client-assets.php on line 797`

**Comment by carolinan** [comment]
Tested in emptytheme:
I added a style to the themes style.css file and then added the filter above to functions.php without changes.
The style is visible in the block editor, template editor, site editor.

Tested in Twenty Twenty-One where I made the change on top of [this PR](https://github.com/WordPress/wordpress-develop/pull/1455). 
In this theme, the new filter worked for the custom colors in the template editor.
For the block editor I needed to use` enqueue_block_editor_assets` with an inline style.
(The dark mode works in the block editor but not in the template editor but that is an unrelated JS issue.)

**Comment by ellatrix** [comment]
It's not worth it to test yet, I'm still working on this PR. I'm more wondering if you all agree with the proposal.

**Comment by fabiankaegy** [comment]
I think the functionality is great and very much needed :) This will make adding styles correctly in the editor much easier. 

I wonder though whether we can use the ability of what you added here to create a nicer API for it. Something like

```php
wp_register_style( 'my-theme-stylesheet', get_stylesheet_uri() );
add_block_editor_style( 'my-theme-stylesheet' );
``` 

Which could intern do something like

```php
function add_block_editor_style( $handle ) {
      add_filter(
	      'block_editor_settings_all',
	      function( $settings ) {
		      $settings['assets']['styles'][] = $handle;
		      return $settings;
	      }
      );
}
```

I know there are many issues with the example that I provided above and I would also 100% ship this without that syntactical sugar to see how it will actually get used. But I think that in comparison to how enqueueing assets works in the rest of WordPress this manual manipulation of the settings array feels rather crude/low level where you can more easily screw something up.

So again I think this is a great and very valuable addition that is much needed :) 

Thank you for working on it! 🚀

**Comment by jasmussen** [comment]
I'm excited to see the opportunities this opens both for leveraging the full benefits of the iframe, and to give control to themes and plugins. I'd be happy to land even an early version of this so that we can get things on the right track, even if it means a few bugfix followups.

I'm seeing one issue, though: some of the block and block UI styles weren't loaded for me. The new Site Logo placeholder looks like this:
Screenshot 2021-11-03 at 08 55 11
but the CSS to create a rounded dashed line wasn't loaded, so it looked like this:
Screenshot 2021-11-03 at 08 53 09

Also seeing an issue with the trailing inserter being unstyled:

Screenshot 2021-11-03 at 08 53 05

Here's trunk:
Screenshot 2021-11-03 at 08 55 15

**Comment by priethor** [comment]
>  I'd be happy to land even an early version of this so that we can get things on the right track, even if it means a few bugfix followups.

I agree with @jasmussen, we should have an early version ready for 5.9 to avoid the warnings mentioned in #33212, as there are plugins heavily impacted by these.

**Pull request closed without merging**
