### PR TITLE
Add a UI to allow saving patterns

### PR DESCRIPTION
**Pull request by aristath**
Props @mykola @janw-me @hdvos @rolf-yoast @enricobattocchi @aristath @carolinan @SergeyBiryukov @mhkuu @afercia during a Yoast contributor day on April 5, 2023

## What?
This PR adds a UI to allow users to save and edit patterns in the editor.
The UI is identical to that of reusable-blocks.

## Why?
Right now patterns can only be created programmatically, and there have been numerous requests to allow users to create and edit their own patterns.

## How?
Duplicating the functionality of reusable blocks.

### CODE REVIEW

**Comment by gziolo** [comment]
I was trying to decipher what this PR is all about, and then I found this comment from @carolinan in #33094:

> Creating and classifying your own pattern library alongside reusable blocks.


This is very interesting when it eventually combines with the planned work on `wp:pattern`: https://github.com/WordPress/gutenberg/issues/48458.

This is going to be interesting to see how the concept of Reusable blocks morphs into Synced Patterns managed by sites, making them capable of fulfilling many of the needs that lead today creating custom blocks.

**Comment by aristath** [comment]
> I was trying to decipher what this PR is all about

Yeah, it's basically trying to allow users to create and save patterns - just like they do for reusable blocks... 
I'm planning to write a description for this PR, record a screencast and open it for reviews later this week 👍

**Comment by ndiego** [comment]
I know this PR is not ready for testing yet, but I couldn't help myself 😅 Excellent work so far. I'm looking forward to seeing how this evolves!

**Comment by mtias** [comment]
Awesome exploration! The main implementation aspect that I'd like to revise is that of using a separate post type. This is a great opportunity to coalesce on how we are storing user reusable content (see #34352 and #41717).

So I'd love to see if we can incorporate into the exploration the idea of using `wp_block` and discriminate behavior based on "sync" status:

- **Full sync** — current reusable block implementation
- **Partial sync** — the wp:pattern idea #48458, orthogonally related to "locking"
- **Unsynced** — how patterns work today, essentially once inserted it's a copy

Sync status can either be a meta value of the post type or an aspect of the insertion (full sync and partial sync would exist as `wp:block` or `wp:pattern` containers).

**Comment by bph** [comment]
should this be closed as it was implemented here: #51144?

**Pull request closed without merging**
