### PR TITLE
Remove /wordpress from test/linting ignore paths

### LINKED ISSUE #20255: Jest tests don't run when `/wordpress/` is somewhere in project path
**Describe the bug**

The [Jest config includes `/wordpress/` in the `testPathIgnorePatterns` array](https://github.com/WordPress/gutenberg/blob/3a86ce1c436c53a3ec86cab88ea5673bb6346cb6/test/unit/jest.config.js#L29). As a result, when your project directory contains `/wordpress/` anywhere in its path, no tests are detected. I use [wp-local-docker](https://github.com/10up/wp-local-docker-v2), which installs sites into a `wordpress` directory. This is what I see in the terminal when running `npm run test-unit`:

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/my-user/wp-local-docker-sites/jw-test/wordpress/wp-content/plugins/gutenberg
  5977 files checked.
  testMatch: **/__tests__/**/*.[jt]s, **/test/*.[jt]s, **/?(*.)test.[jt]s - 459 matches
  testPathIgnorePatterns: /.git/, /node_modules/, /packages/e2e-tests, /wordpress/, /Users/my-user/wp-local-docker-sites/jw-test/wordpress/wp-content/plugins/gutenberg/.*/build/, /Users/my-user/wp-local-docker-sites/jw-test/wordpress/wp-content/plugins/gutenberg/.*/build-module/, /Users/my-user/wp-local-docker-sites/jw-test/wordpress/wp-content/plugins/gutenberg/.+.native.js$ - 0 matches
  testRegex:  - 0 matches
```

Tests run when I comment out the `/wordpress/` line.

I'm pretty sure that changing the line to `<rootDir>/wordpress/` would fix it, but I'm not submitting a PR because I'm not sure of the rationale for having `/wordpress/` in the ignore patterns in the first place. I've tried `npm env install` and related commands and haven't seen that they add `/wordpress/` in the plugin root, but I might be missing something.

This PR diff shows the several places where `/wordpress/` is in a Jest ignore patterns array: https://github.com/WordPress/gutenberg/pull/17296/files

**To reproduce**
1. Put this plugin in any location that has `/wordpress/` somewhere in the path.
2. Run `npm run test-unit`. 
3. No tests run.

**Expected behavior**

Tests should be detected even if the project lives where `/wordpress/` is in the path.

**Desktop (please complete the following information):**
 - OS: Mac OS

### PR DESCRIPTION
**Pull request by johnwatkins0**
## Description

This resolves #20255 by removing `/wordpress` where it appears among linting/testing ignore patterns, essentially undoing everything in https://github.com/WordPress/gutenberg/pull/17296/files.

Having `/wordpress/` in the ignore patterns was preventing Jest tests from being recognized when the project has `/wordpress/` somewhere in the system directory path.  According to @talldan 
 in https://github.com/WordPress/gutenberg/issues/20255#issuecomment-586876100, the original reason for ignoring the directory no longer applies, so it can be removed.

## How has this been tested?

Ran linting and tests locally after the change. Everything worked.

## Types of changes

Change to test and linting configurations.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — COMMENTED** [review]
Thanks for following up on this @johnwatkins0.

Perhaps the wordpress folder should also be removed from the .gitignore file now that it's not expected to be there. What do you think?

**Comment by johnwatkins0** [comment]
Thanks, @talldan. I agree -- if there's no longer anything in plugin development process that creates a `/wordpress` directory, it doesn't need to be in `.gitignore`. I've updated.

**Comment by gziolo** [comment]
Thank you for working on it. We should deprecate wp-scripts env first, before we land this PR. It is still referenced in some places in the root package.json of Gutenberg . In addition, if someone uses @wordpress/scripts and they run env script, they will see unexpected errors.

**Comment by talldan** [comment]
> We should deprecate wp-scripts env first

@gziolo Ah, does that still install wordpress into a local folder? I didn't realise that.

It looks like `env` is still used for travis, so that'd be one of the first places to replace with `wp-env`:
https://github.com/WordPress/gutenberg/blob/c76137bec81a79ee9d838619f13cdf62e69f61ce/.travis.yml#L83-L99

**Comment by gziolo** [comment]
> @gziolo Ah, does that still install wordpress into a local folder? I didn't realise that.

It probably does. At least, it's what happens locally :)

**Comment by gziolo** [comment]
@johnwatkins0, we can land this changes now tfst `@wordpress/env` is widely used. Would you mind bringing this PR up to date?

There is also a note about ignored `wordpress` folder in README file of `@wordpress/scripts` package.

**Comment by johnwatkins0** [comment]
> There is also a note about ignored `wordpress` folder in README file of `@wordpress/scripts` package.

@gziolo This PR has been updated, and the README file was modified in 0fdb93a05ad990767698c0fbe3f835298323b66a

**Review by gziolo — APPROVED** [review]
Thank you 👍

**Pull request merged**
