### PR TITLE
[RNMobile] Fix cover issues related to custom color picker

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

PR is fixing 3 different bugs related to custom color picker in Cover placeholder block:

1. Custom color picker indicator (button) wasn't pressable until the Cover block was selected (other regular colors were pressable)

2. After setting custom background color `undo` button didn't restore the block to the default shape

3. After setting custom background color, the bottom sheet picker was hiding in the meantime the selected paragraph appeared, but the keyboard hid after a second.
 

## How has this been tested?

1. Do sanity tests for Cover block.

2. Follow the steps:

* Add Cover block
* Add any other block outside Cover and keep it selected
* Press color picker (multicolor circle button) on Cover placeholder

**Expect bottom sheet picker appeared**

* Choose any color and press `Apply/ V`

**Expect `Paragraph` block appeared on `Cover` and keyboard is visible**

* Close the keyboard
* Press `undo` button couple times

**Expect the default Cover block shape with the placeholder**

## #BEFORE
 
First bug | Second bug | Third bug
--- | --- | ---
bugg_1 | bug_2 | bug_3

## Types of changes

Bug fixes.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by geriux** [comment]
Hey Luke 👋 

While testing these changes I found this issue:

<kbd></kbd>

The color that was set gets removed when dismissing the settings bottom sheet.

Can you check it out? Thanks!

**Comment by lukewalczak** [comment]
> Can you check it out? Thanks!

Sure will check that, thanks for review!

**Comment by lukewalczak** [comment]
### UPDATES

* Fourth bug reproducible on master as well


Testing steps:

1. Add a cover block
2. Tap on the color picker
3. Close it
4. Select one of the colors in the place holder
5. Open the settings
6. Close the bottom sheet 

**Expect color doesnt change** 
before | after
--- | ---
 |

**Review by geriux — APPROVED** [review]
LGTM! Nice work Luke, tested it on both iOS and Android

**Pull request merged**
