### PR TITLE
Separator Block: Add top and bottom margins without resizable box

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## Description
This adds the ability to set top and bottom margins on the separator block.

- This is an alternate approach to https://github.com/WordPress/gutenberg/pull/28409 & https://github.com/WordPress/gutenberg/pull/28688
- Does not include a resizable box for manual drag resizing
- Stores the top/bottom margins within a style attribute to match spacing margin block support that is in progress
- Also updates native components for the separator block as well as `HorizontalRule` to allow margin styles.

## How has this been tested?
Manually.

##### Web
1. Checkout this PR
2. Add a separator block to a post and select it
3. Adjust the top and bottom margins including units via the sidebar controls
4. Ensure block updates visually in editor and frontend

##### Native
1. Start up native simulator
2. Add a separator block, select it and open its controls
3. Adjust top and bottom margins including units
4. Confirm block updates visually as expected

## Screenshots 
| Web | Native |
|-----|--------|
| Separator-Web | Separator-Native |

## Types of changes
New Feature

## Next Steps
Update controls for Native.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by apeatling** [comment]
Tested and this works for me. I think this approach makes the most sense in terms of a first iteration. However I think we'd need to follow up and replace this custom margin UI with the margins component (and allow it to disable certain margins so only top and bottom margins are editable).

**Comment by apeatling** [comment]
@aaronrobertshaw Could this seamlessly switch to using the margins component in a future PR? My other thought is we spend the time on the margins component now to allow disabling of specific margins, so we can use it here before merging this.

**Comment by aaronrobertshaw** [comment]
> Could this seamlessly switch to using the margins component in a future PR? 

Thanks for taking a look at this @apeatling. 

Yes, I believe it will be a simple switch in the future to use the margins component. Especially if it used via the block support spacing feature which would store the margin values in the same `style.spacing.margins.top` and `style.spacing.margins.bottom` properties. It should only be a matter of replacing the controls, no migration of the block's attributes or markup.

> My other thought is we spend the time on the margins component now to allow disabling of specific margins, so we can use it here before merging this.

I'm happy to take a look at the BoxControl and see how we might approach allowing opting out of particular sides. It would definitely be the cleanest approach for the UI. 

Perhaps being able to opt out of particular sides would also help to offer margins via the spacing block support feature. It could then have left/right margin support disabled by default so they wouldn't interfere with block alignments.

**Comment by aaronrobertshaw** [comment]
Created [issue](https://github.com/WordPress/gutenberg/issues/30073) for errors thrown when mouse drag gesture is used on BoxControl's unit control fields. In the meantime, I've added the possible fix to this PR as an example. https://github.com/WordPress/gutenberg/issues/30073

**Comment by aaronrobertshaw** [comment]
Added box visualizer to web controls. Native still uses individual fields for top and bottom margins.

**Comment by andrewserong** [comment]
Nice work @aaronrobertshaw, this is testing well for me manually in the web editor (I need to fix some thing on my laptop before I can get the iOS simulator running properly to test RN).

One thing I noticed in the UI for the BoxControl is that the `BoxControlIcon` currently highlights all four sides by default, but the control here is for just for the vertical margin. If we select the button to Unlink Sides, the icon will highlight just the selected side (e.g. either the top or the bottom side). Is it possible for us to have the default for this control highlight the top and bottom margins in the icon here, but leave the left and right sides greyed-out? Possibly by adding the `isSideDisabled` logic you've included in the input controls, to the icon component? Of course, it is pretty subtle!

#### All four sides are highlighted

image

#### One side is highlighted after selecting "Unlink sides"

image

**Comment by aaronrobertshaw** [comment]
> One thing I noticed in the UI for the BoxControl is that the BoxControlIcon currently highlights all four sides by default, but the control here is for just for the vertical margin.

Thanks @andrewserong, that would definitely be an improvement. I'll take a look at making it happen 👍

**Comment by aaronrobertshaw** [comment]
The `BoxControlIcon` has been updated to reflect the enabled sides for the `BoxControl`

Screen Shot 2021-03-23 at 5 11 10 pm

**Comment by andrewserong** [comment]
That's looking really good, thanks for updating the `BoxControlIcon` @aaronrobertshaw. I also tested the change in the React Native edit in the iOS simulator, and it's testing well for me.

I noticed one slight issue with the `onChange` behaviour for me in manual testing. While in the code it looks like the styling should update whenever we change a value within the input field, in practice it seems like when I update the field via keyboard entry, the styling only updates when I focus outside of the field. Here's an example:

separator-margin-sml
 
I couldn't quite work out why it wouldn't be updating `onChange` though, because it looks like that's what it _should_ be doing 🤔

Other than that, this is looking good to me (though I must admit this is the first time I've looked at any of the React Native code!)

**Comment by aaronrobertshaw** [comment]
Thanks @andrewserong for the thorough testing.

> I couldn't quite work out why it wouldn't be updating onChange though, because it looks like that's what it should be doing 🤔

The `onChange` isn't actually being triggered on the `BoxControl`'s `UnitControl` when typing within its input field. The `BoxControl` wraps the standard `UnitControl` to provide tooltips, hover gestures etc. It also sets the `isPressEnterToChange` prop for the `UnitControl` [here](https://github.com/WordPress/gutenberg/blob/add/separator-margins-without-resizable-box/packages/components/src/box-control/unit-control.js#L41).

If the `isPressEnterToChange` prop is removed then the input behaves as you expected. I'm not sure if we should change that as well or if there was a specific UX reason for it.

It's worth noting that pressing the up/down arrows on your keyboard to increment/decrement the value will immediately trigger the `onChange`.

**Comment by andrewserong** [comment]
Thanks for getting to the bottom of that @aaronrobertshaw! It sounds like it's by design, then. I couldn't see if we've used the `BoxControl` component directly in any other blocks yet? I see the Cover block uses the `BoxControlVisualizer` from `BoxControl`, but then for the minimum height of the cover, it uses the `UnitControl` directly so it uses the onChange behaviour the same way as the custom font size on the paragraph or heading blocks.

I can see the value of preventing `onChange` until someone hits enter, so that the settings aren't flying around in the editor canvas until someone commits to it. But on the other hand, it's different behaviour to other similar input fields in the editor, which I think is why it felt like it wasn't working properly to me.

My personal preference would be to go for consistency with keyboard input behaviour across these sorts of inputs, but I think I'd lean toward leaving the discussion about the best UX for the BoxControl component itself to another PR, and leave it as-is in this one, if it doesn't seem like an issue for anyone else.

**Review by andrewserong — APPROVED** [review]
Nice work @aaronrobertshaw, this is testing nicely for me in web and in the iOS simulator, and I think we can defer the BoxControl `onChange` UX to a separate issue / discussion.

It'd be good to get another pair of eyes from someone with more React Native experience than I have, but otherwise LGTM!

**Review by apeatling — APPROVED** [review]
This is working great on web and native for me, and I appreciate the time you've put in to use and update the BoxControl component. It feels really good.

**Comment by aaronrobertshaw** [comment]
The changes within this PR and based off it have been split up into smaller chunks that are now already under review/feedback.

Closing this in favour of the collection of new PRs below:

https://github.com/WordPress/gutenberg/pull/30606
https://github.com/WordPress/gutenberg/pull/30607
https://github.com/WordPress/gutenberg/pull/30608
https://github.com/WordPress/gutenberg/pull/30609

**Pull request closed without merging**
