### PR TITLE
FIX missing images of Gutenberg Data Apps document

### PR DESCRIPTION
**Pull request by atachibana**
All images in "Create your first app with Gutenberg Data" are shown on GitHub preview, but not in the Block Editor Handbook. For example, the following page contains the image after "app will look like this:" but does not show:
https://developer.wordpress.org/block-editor/how-to-guides/data-basics/

This is because the image is specified as below:

```
! [](/docs/how-to-guides/data-basics/media/list-of-pages/part1-finished.jpg)
```

It must be

```
!  [](https://raw.githubusercontent.com/WordPress/gutenberg/HEAD/docs/how-to-guides/data-basics/media/list-of-pages/part1-finished.jpg)
```

As like as other images on doc page.
Refer https://github.com/atachibana/gutenberg/blob/master/docs/how-to-guides/plugin-sidebar-0.md.

At the same time, I also modified two minor typos.

### CODE REVIEW

**Comment by gziolo** [comment]
Thank you for starting this PR. @adamziel should be interested to help you to bring it to the finish line.

**Comment by atachibana** [comment]
@gziolo @adamziel 
Hi, I noticed @adamziel fixed 2 files of not showing images at commit https://github.com/WordPress/gutenberg/commit/cb92180a2323393eb45b7abbfcd9f4e2fe2f3dc9 , but still 1 file remains.

I also included some typo or old link fixes in this chapter.

**Comment by gziolo** [comment]
> Hi, I noticed @adamziel fixed 2 files of not showing images at commit https://github.com/WordPress/gutenberg/commit/cb92180a2323393eb45b7abbfcd9f4e2fe2f3dc9 , but still 1 file remains.

What's still missing? Should we land all the changes applied so far?

**Review by gziolo — APPROVED** [review]

**Comment by atachibana** [comment]
@gziolo 
Though you've already approved, I'll add comments for clarity.

Missing are in the 3-building-an-edit-form.md.
Please see the below generated page in the handbook that does not have any images:
https://developer.wordpress.org/block-editor/how-to-guides/data-basics/3-building-an-edit-form/

> Should we land all the changes applied so far?

Yes. I believe this PR resolves all.

**Comment by gziolo** [comment]
Thank you @atachibana 💯

**Comment by adamziel** [comment]
@atachibana Thank you so much! 💯 ❤️

**Comment by atachibana** [comment]
@adamziel Hi, Thank you for the educational and fun tutorial.

By the way, did you know the Japanese guy Aki Hamano (@t-hamano ) is doing the live-demo based on your tutorial? (Ah, sorry it is Japanese... )
https://www.youtube.com/watch?v=X2KiGkPcPYY
He is also famous with [Piano Block](https://wptavern.com/play-the-piano-and-other-instruments-via-the-wordpress-block-editor).

**Comment by adamziel** [comment]
I had no idea, thank you so much for sharing that @atachibana ❤️ 

@t-hamano I would love to learn more about your experience with that tutorial! Was it smooth? Confusing? Anything that was missing in your opinion, or any specific direction that you'd like to see it expanded in? I certainly have blind spots for things and your feedback would help me notice and pay attention to them.

As a side note, you might be interested in the upcoming [Part 4](https://github.com/WordPress/gutenberg/pull/39261) that explains how to build a form that enables creating new pages. 

And by the way, the Piano Block is amazing!

**Comment by t-hamano** [comment]
@adamziel Thank you for making a great tutorial.
And thanks to @atachibana  for translating it into Japanese!

I'm just now putting that tutorial into practice, but I would like to send the issue or PR if there is any concern 👍

**Pull request merged**
