### PR TITLE
Table of contents block: add color block supports 

### PR DESCRIPTION
**Pull request by ramonjd**
Related:
- https://github.com/WordPress/gutenberg/issues/43241
- https://github.com/WordPress/gutenberg/issues/43245

## What?

Enabling full color block supports for the Table of contents block

## Why?

To create consistency across blocks.

## How?

Adding the relevant block supports in block.json

## Testing Instructions

1. Load the block editor with a Table of contents block. Add some content or use the example block code below.
2. Confirm the colors control panel is there
3. Add background color or gradient, link text and text colors
4. Save and confirm the styles appear on the frontend.
5. Test the new support works for the block via theme.json and global styles. See example JSON below.

<details>

<summary>Example block code</summary>

```html
<!-- wp:table-of-contents {"headings":[{"content":"Did you hear about the two thieves who stole a calendar?","level":2,"link":"http://localhost:8888/?p=27#did-you-hear-about-the-two-thieves-who-stole-a-calendar"},{"content":"They each got six months.","level":3,"link":"http://localhost:8888/?p=27#they-each-got-six-months"},{"content":"Ever wondered why bees hum?","level":2,"link":"http://localhost:8888/?p=27#ever-wondered-why-bees-hum"},{"content":"It's because they don't know the words.","level":3,"link":"http://localhost:8888/?p=27#it-s-because-they-don-t-know-the-words"},{"content":"What did the big flower say to the littler flower?","level":2,"link":"http://localhost:8888/?p=27#what-did-the-big-flower-say-to-the-littler-flower"},{"content":"Hi, bud!","level":3,"link":"http://localhost:8888/?p=27#hi-bud"},{"content":"Where do bees go to the bathroom?","level":2,"link":"http://localhost:8888/?p=27#where-do-bees-go-to-the-bathroom"},{"content":"The BP station.","level":3,"link":"http://localhost:8888/?p=27#the-bp-station"}],"style":{"elements":{"link":{"color":{"text":"var:preset|color|pale-cyan-blue"}}}},"backgroundColor":"vivid-purple","textColor":"luminous-vivid-orange"} -->
<nav class="wp-block-table-of-contents has-luminous-vivid-orange-color has-vivid-purple-background-color has-text-color has-background has-link-color"><ol><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#did-you-hear-about-the-two-thieves-who-stole-a-calendar">Did you hear about the two thieves who stole a calendar?</a><ol><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#they-each-got-six-months">They each got six months.</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#ever-wondered-why-bees-hum">Ever wondered why bees hum?</a><ol><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#it-s-because-they-don-t-know-the-words">It's because they don't know the words.</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#what-did-the-big-flower-say-to-the-littler-flower">What did the big flower say to the littler flower?</a><ol><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#hi-bud">Hi, bud!</a></li></ol></li><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#where-do-bees-go-to-the-bathroom">Where do bees go to the bathroom?</a><ol><li><a class="wp-block-table-of-contents__entry" href="http://localhost:8888/?p=27#the-bp-station">The BP station.</a></li></ol></li></ol></nav>
<!-- /wp:table-of-contents -->

<!-- wp:heading -->
<h2 id="did-you-hear-about-the-two-thieves-who-stole-a-calendar">Did you hear about the two thieves who stole a calendar?</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 id="they-each-got-six-months">They each got six months.</h3>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 id="ever-wondered-why-bees-hum">Ever wondered why bees hum?</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 id="it-s-because-they-don-t-know-the-words">It's because they don't know the words.</h3>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 id="what-did-the-big-flower-say-to-the-littler-flower">What did the big flower say to the littler flower?</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 id="hi-bud">Hi, bud!</h3>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 id="where-do-bees-go-to-the-bathroom">Where do bees go to the bathroom?</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 id="the-bp-station">The BP station.<a href="https://icanhazdadjoke.com/j/AI6hiGtzAd"></a><a href="https://icanhazdadjoke.com/j/IJYvcFIBAlb"></a><a href="https://icanhazdadjoke.com/j/ZDAIRn39prc"></a><a href="https://icanhazdadjoke.com/j/FYobM71o4ob"></a></h3>
<!-- /wp:heading -->

```

</details>

```json
	"styles": {
		"blocks": {
			"core/table-of-contents": {
				"color": {
					"background": "green"
				}
			}
		}
	}
```

Screen Shot 2022-08-18 at 7 15 00 pm

### CODE REVIEW

**Comment by ramonjd** [comment]
Fixing the failing e2e test in this commit: 3ba738875c953c3381d5022ccd809ab9e537e5e2

**Comment by glendaviesnz** [comment]
This works for me, except setting the link color in theme.json:
Screen Shot 2022-08-19 at 4 13 37 PM

the linter complains that link is not allowed, but I see it used elsewhere in the blockbase theme.json

**Comment by ramonjd** [comment]
> This works for me, except setting the link color in theme.json:


Interesting, looks like the schema doesn't support it. Perhaps it's intentional?


https://github.com/WordPress/gutenberg/blob/a9ae1b70be556b4f31974932eb91e05e7059d162/schemas/json/theme.json#L956-L955

**Comment by glendaviesnz** [comment]
> Interesting, looks like the schema doesn't support it. Perhaps it's intentional?

ok, I guess that is another can we can kick down the road, it works in the UI so lets run with it

**Review by glendaviesnz — APPROVED** [review]
Works in the UI, but setting `link` doesn't currently work in theme.json so that may need to be followed up at some point if that is an expectation.

**Comment by ramonjd** [comment]
Looks like the theme json class doesn't even look for it. There's no path in https://github.com/WordPress/gutenberg/blob/a9ae1b70be556b4f31974932eb91e05e7059d162/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php#L34

My assumption is that is needs to be handled as an "element", similar to the way we're doing it for block supports in `elements.php` but on the global styles level.

It doesn't work for any text block that I'm testing (para, heading)...

**Comment by ramonjd** [comment]
> ok, I guess that is another can we can kick down the road, it works in the UI so lets run with it

I've added it as a follow up in https://github.com/WordPress/gutenberg/issues/43245

**Comment by ZebulanStanphill** [comment]
Thanks for these PRs. :+1:

**Comment by ZebulanStanphill** [comment]
I just remembered that most (if not all) text blocks with background color controls have additional styles to add padding when a background color is present... [including the List block](https://github.com/WordPress/gutenberg/blob/c4ce1a16325d35ed5e2a57d000ab533156cc1aae/packages/block-library/src/list/style.scss#L6).

I guess the same thing should happen here, though I imagine the exact styles couldn't just be copied over from the List block since in this case, the padding would be applied to the wrapping `<nav>` rather than the contained `<ol>`.

In the List block, this auto-padding would override any padding already set on the `<ol>`, but in the Table of Contents block, the `<ol>` padding would be kept, and the `<nav>` padding would add to the overall spacing.

I actually considered making a PR to add color controls to the Table of Contents some months ago, but I got stuck trying to figure out what to do here.

**Comment by ramonjd** [comment]
Thanks for raising this!

> I just remembered that most (if not all) text blocks with background color controls have additional styles to add padding when a background color is present

What if we didn't adding padding here? Using padding values one can achieve the same effect and have greater control:

Screen Shot 2022-08-22 at 10 22 06 am

There's a related discussion about the extra padding given to blocks with background color (and whether it's a good thing at all)

- https://github.com/WordPress/gutenberg/issues/43110

There is the question of classic themes. The above issue considers the use of classic-only stylesheet.

**Pull request merged**
