### PR TITLE
[6.7] Activate zoom out only on large viewport

### PR DESCRIPTION
**Pull request by t-hamano**
Apply the same fix as #66308 to the `wp/6.7` branch

## What?

This PR resets the zoom out mode so that the inserter doesn't get narrower on smaller viewports.

## Why?

I don't think the zoomed out mode is intended for use on small viewports.

## How?

There is a difference in the implementation of the `useZoomOut` hook between `trunk` and the `wp/6.7` branch. Since we cannot backport #66308 directly, we need to manually apply the same change to the `wp/6.7` branch.

## Testing Instructions

- Open the post editor.
- Open the main inserter.
- Click the Patterns tab.

## Screenshots or screencast 

| Before | After |
|--------|--------|
| image| image |

### CODE REVIEW

**Comment by t-hamano** [comment]
I made a similar change to #66308, but somehow this PR doesn't seem to dynamically reset the zoom out mode when the viewport width changes:

https://github.com/user-attachments/assets/ee325627-b1c8-44d2-a154-0c0a4a5e2873

Maybe it's because the zoom out mode implementation is different between `wp/6.7` branch and `trunk`. If you know how to solve this, please let me know.

**Review by getdave — APPROVED** [review]
Tests well for me. Thank you for following up 👍

**Review by jeryj — CHANGES_REQUESTED** [review]
I don't think this is the change we want. I think this should be passed in [via the inserter menu boolean](https://github.com/WordPress/gutenberg/blob/wp/6.7/packages/block-editor/src/components/inserter/menu.js#L85), not added within the `useZoomOut` hook.

**Comment by getdave** [comment]
> I don't think this is the change we want. I think this should be passed in [via the inserter menu boolean](https://github.com/WordPress/gutenberg/blob/wp/6.7/packages/block-editor/src/components/inserter/menu.js#L85), not added within the `useZoomOut` hook.

I'm in no rush to merge if we want to explore the alternative. RC2 won't be cut until next Monday. Thanks Jerry 🙇

**Comment by t-hamano** [comment]
Based on #66341, I've updated this PR. I removed the viewport check from the useZoomOut hook and added it to the inserter menu instead.

**Comment by kevin940726** [comment]
I rebased the branch to fix the missing `isZoomOut` error addressed in #66420.

**Comment by getdave** [comment]
@jeryj Can we get another review here please? 🙏

**Review by getdave — COMMENTED** [review]
I retested and Zoom Out does not activate on small viewports when switching to the Patterns tab.

**Review by jeryj — APPROVED** [review]
Looks great - thank you for the update @t-hamano!

**Comment by getdave** [comment]
Probably just needs a rebase to get these tests passing. I'll try that if no one gets there first

**Pull request merged**
