### PR TITLE
Refactor LinkControl component to support React 17

### PR DESCRIPTION
**Pull request by youknowriad**
In React 17, nesting forms inside forms doesn't work as expected and this is materialized by an e2e test failure in #26847 
This PR tries to solve this by avoiding a form in a reusable component like LinkControl which is itself supposed to be embedded in a form.

It also fixes a small bug where clicking the "edit" button was not moving the focus to the LinkControl input.

What do you think @getdave

### CODE REVIEW

**Comment by youknowriad** [comment]
That component got a bit messy after all the iterations, it feels like it needs to be rewritten entirely at some point.

**Comment by getdave** [comment]
It's a big component and a rewrite would be...challenging. 

Breaking it down a little, doing some refactoring and tidying would be a great first step though.

Where did your main concerns lie at this point?

**Comment by getdave** [comment]
> What do you think @getdave

I was literally about to start work on this one. Thanks for picking it up 🙇

**Review by getdave — APPROVED** [review]
I tested the changes and I was able to use the control via keyboard exactly as I was able to do previously. 

I also tested the focus loss change and that worked as well.

As things stand I can't see a reason why this won't work. My only minor reservation would be whether removing a `<form>` around input elements and such makes this control any less accessible. I'm not really qualified to provide a good opinion on this however.

Thanks again for picking this up Riad 🙇

**Comment by getdave** [comment]
Wow that's a lot of e2e test failures. I'm not sure they are related. I see a lot of PRs with  a lot of failures all of a sudden...

**Comment by youknowriad** [comment]
I think the failures are related. I'll try to debug tomorrow.

**Comment by youknowriad** [comment]
For the component itself, it's based on a number of components including the oldish URLInput, it's not really clear what the responsibility of each component is and how they interact with each other. Basically at this point, it's just hacks on top of hacks in these components :P (kind of like I did in this PR by adding the onSubmit prop)

**Pull request merged**
