### PR TITLE
Site Editor: Fix obsolete `getLocationWithParams` usage

### LINKED ISSUE #68367: Pattern json import and export has stopped working on Wordpress.COM
### Description

Hi All,
I'm just a random user of Wordpress.COM but considering this is the last commit to this file and the pattern json import and export was working up until two weeks ago I think this commit may have broken it. On Wordpress.COM I can no longer import pattern json files because I now get the following error "e.getLocationWithParams is not a function". I've tried contacting support over on Wordpress.COM as I have a paid hosting with them but their support is AWOL so I'm dropping this here. I may be wrong and if I am I apologize.

### Step-by-step reproduction instructions

On Wordpress.COM export a pattern json
Then on Wordpress.COM import a pattern json
Now you get the following error "e.getLocationWithParams is not a function".

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by tyxla**
## What?
Fixing two instances of `history.getLocationWithParams()` that were causing errors.

Reported in https://github.com/WordPress/gutenberg/pull/67199#issuecomment-2564397118 and #68367.

Fixes #68367.

## Why?
In #67199 we got rid of `useHistory()`'s `getLocationWithParams()` method. However, we forgot to update a couple of instances.

## How?
We're using `useLocation()` to retrieve query arguments.

## Testing Instructions
* Go to Site Editor > Patterns
* Import a pattern from a json file
* Verify it works well and you no longer get an error. 
* Verify you can still delete custom DataViews views.

### Testing Instructions for Keyboard
Same

## Screenshots or screencast 
The error that was appearing in the snackbar notice:
399210539-2bc82b09-1dba-43ce-8f43-e3595976440e

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
| Before | After |
|--------|--------|
| Screenshot 2024-12-31 at 10 44 54 am | Screenshot 2024-12-31 at 10 45 48 am |

👍🏻 

Thanks for the fix!

**Comment by ramonjd** [comment]
I think Gutenberg 20 has been delayed a week, but an RC will be cut this week (?) If that's not the case, maybe worth a point release?

**Comment by JungleGenius** [comment]
Hi Folks @ramonjd @tyxla @himanshupathak95,

Thanks you for the swift response and bug fix.  I was trying to get a landing/order page up over the Holliday when I ran headlong into this bug.

I am really impressed with your team's actions once I got the bug got on your radar.  (The front line Wordpress.COM user support was lacking, but it look like the dev team is really on the ball response wise). 

Normally I would just create a pull request for the bug fix like I did for the [Groundhog](https://github.com/groundhoggwp/groundhogg) plug-in over [here](https://github.com/groundhoggwp/groundhogg/pull/65), but I'm not currently setup for WordPress core development (I mostly do Laravel and CodeIgniter).  

The theme/plug-in editor won't let me view or debug the core files so I was kind of stuck.  I ended up pasting the JSON into the pages manually to work around this, but it was buggy because the block editor needs to "resolve" the pasted json code.

I think you are going to need a dot release to get this into Wordpress.COM in the short term.

Thanks everyone.  Great work.

-Daniel

**Comment by tyxla** [comment]
Thank you @JungleGenius!

Once a new version of Gutenberg is released (which I believe should be in a week from now), folks have historically tried to quickly release it to WP.com, at which point the fix should be in place there.

**Pull request merged**
