### PR TITLE
Mobile - Highlight words

### PR DESCRIPTION
**Pull request by geriux**
- Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4175
- WordPress iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/17381
- WordPress Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15504
- Aztec Android PR: https://github.com/wordpress-mobile/AztecEditor-Android/pull/943
- Aztec iOS PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1339

## Description
This PR adds the functionality to be able to customize colors for selected words. For now, users will only be able to change the text color, the functionality to customize the background color will not be supported on mobile for now.

<kbd></kbd>

## Test case 1 - Using a color from a theme's color palette

**Precondition**: Site with a universal theme e.g Geologist, Quadrat, Zoologist.

- Open the app and start a new post
- Type in some text
- Select a word or some words
- In the formating toolbar look for the `Highlight` option and select it
- **Expect** to see the bottom sheet open with the color palette of the theme
- Select one of the theme colors (not a custom one)
- Close the bottom sheet and expect to see the selected color applied
- Preview the post
- **Expect** to see the colors correctly
- Save the post and close it
- Open the created post
- **Expect** to see the color you added before

## Test case 2 - Using a custom color

**Precondition**: Site with a universal theme e.g Geologist, Quadrat, Zoologist.

- Open the app and start a new post
- Type in some text
- Select a word or some words
- In the formating toolbar look for the `Highlight` option and select it
- **Expect** to see the bottom sheet open with the color palette of the theme
- Select the `CUSTOM` option
- Choose any color and apply the changes
- Close the bottom sheet and expect to see the selected color applied
- Preview the post
- **Expect** to see the colors correctly
- Save the post and close it
- Open the created post
- **Expect** to see the color you added before

## Test case 3 - Using a color from the default color palette

**Precondition**: Site without any custom theme colors e.g Blank Canvas

- Open the app and start a new post
- Type in some text
- Select a word or some words
- In the formating toolbar look for the `Highlight` option and select it
- **Expect** to see the bottom sheet open with the **default** color palette
- Select one of the colors from the palette
- Close the bottom sheet and expect to see the selected color applied
- Preview the post
- **Expect** to see the colors correctly
- Save the post and close it
- Open the created post
- **Expect** to see the color you added before

## Screenshots 

Test case 1 | Test case 2 | Test case 3
-|-|-
<kbd></kbd> | <kbd></kbd> | <kbd></kbd>

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by geriux** [comment]
Hey @iamthomasbishop 👋 this feature is ready to be reviewed, would you mind checking it out when you have some time?

- [iOS build](https://github.com/wordpress-mobile/WordPress-iOS/pull/17381#issuecomment-953617027)
- [Android build](https://github.com/wordpress-mobile/WordPress-Android/pull/15504#issuecomment-953636219)

Thank you so much!

**Comment by iamthomasbishop** [comment]
@geriux Thanks for the ping, this is looking and working great! I only have a few concerns, none of which are huge deals. I also noticed one semi-related thing, which isn't specific to this work but wanted to document in case we can tackle it soon. And then the last thing is a suggestion for future iterations, to have "on the record" 🙂 Let me know if you have any questions or if any of the requests will be especially challenging.

## Contrast with button background

On the selected text color button, the icon can get lost in cases where the selected color is close to the background color of the button. Are we able to dynamically set the button background (behind the "A" icon) to the color of the actual block background behind it in the same way the web editor handles this? If not, we might want to consider a different treatment when a custom color is active.

<a href="https://user-images.githubusercontent.com/1200432/140195263-2e23a8e5-d54c-4f6c-91e3-0102a51e9561.jpeg"></a>

(Note: I understand that this exact same problem will arise if the user manually sets the text color to something close to the background color, but at least in that case the colors are accurate to the output and represented on the canvas itself; as well as in the preview.)

## Toolbar position

I'm curious, would it be difficult for us to move the colors button to a separate group on the block toolbar? As far as I know, we're simply following the order from the web, but I'm not sure if that is hard-coded or if we have flexibility in how we're organizing buttons/groups. If we have flexibility, I'd like to separate color out into its own group and place it either immediately after (preferred) or before the formatting group (bold, italic, etc), as demonstrated in these examples:

<a href="https://user-images.githubusercontent.com/1200432/140195467-869804e2-ebcf-4eec-8a8f-a7f39bbe1c1c.png"></a>

## Semi-related

I'm not able to reproduce this on every tap so I'm unsure what the dimensions are on the "reset" tap target, but I noticed that tapping on or around the hex color label on the footer row of the top level sheet resets the value to its default. I'm assuming this is because most of our standard cell components act in a similar way, where the primary action's tap target spans the entire width of the cell. Ideally, the tap target for the "reset" button should only be as wide as the label (and perhaps slight bit of padding if there is any).

<a href="https://user-images.githubusercontent.com/1200432/140195961-d705408a-0f39-400d-983c-2d4f63ad42d2.png"></a>

## For future consideration

I noticed that if I have a custom color applied to a narrow selection — for example, a word or two in a sentence — then widen that selection to _include_ the original (or go to the block-level color settings), then choose a new color for the wider selection, the previously-customized colors are essentially overridden. This might be expected behavior (I'm 100% sure it matches the behavior of web) but I can imagine a case where I'd like to "lock" certain color on part.

<a href="https://user-images.githubusercontent.com/1200432/140195855-6a1bdb94-43fe-4355-a35f-7ec1525ca1ce.png"></a>

**Comment by geriux** [comment]
Hey @iamthomasbishop 👋  first of all thank you so much for the thorough design review ⭐ 

> Contrast with button background

For this, I was able to set the background color in a few scenarios:

- **Scenario 1**: Paragraph block with a custom background color set.
- **Scenario 2**: Group block with a custom background color set and a Paragraph block as an inner block.
- **Scenario 3**: Paragraph block without any background color set, it should use the editor background color for block-based themes.

Scenario 1 | Scenario 2 | Scenario 3
-|-|-
<kbd></kbd> | <kbd></kbd> | <kbd></kbd>

Do you think that works for now?

> Toolbar position

I was able to move it to its own group:

Text color
-|
<kbd></kbd>

> Semi-related

Thank you for catching that bug with the `Reset` button touchable area! I've fixed it in the latest build.

> For future consideration

That's correct, it does match the web behavior. I could open a ticket to investigate this in a future iteration, what do you think?

All of the above will be available in the newest builds:

- [WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/17381#issuecomment-953617027)
- [WordPress Android](https://github.com/wordpress-mobile/WordPress-Android/pull/15504#issuecomment-953636219)

Thanks again!

**Review by antonis — COMMENTED** [review]
Great work Gerardo 🤩  
I tested the latest changes of the PR using metro and everything works as expected for me.
The code also looks great 👍 

I have a small comment on the behaviour when there is no word selected. In that case the button is active but it does not affect the selected color when you continue typing after that. Probably we can disable or hide the button in that case. I don't consider this blocking but @iamthomasbishop may have feedback on this.

<details>
<summary>Recording</summary>

https://user-images.githubusercontent.com/304044/140381294-9f267f18-041d-40d6-afd9-3690f27af493.mp4
</details>

**Comment by geriux** [comment]
Thank you for reviewing/testing Antonis! 🙇 

> I have a small comment on the behaviour when there is no word selected. In that case the button is active but it does not affect the selected color when you continue typing after that. Probably we can disable or hide the button in that case. I don't consider this blocking but @iamthomasbishop may have feedback on this.

I'm currently investigating this issue, thanks for reporting it! 👍

**Comment by iamthomasbishop** [comment]
> For this, I was able to set the background color in a few scenarios:

Those use cases should cover a lot of ground, so I think this is a great starting point! As far as I can tell, what we have here aligns well with what exists on the web, so I'm happy to defer this to a future iteration but I wonder if it'd be possible to show a contrast warning similar to what the web shows if a block's background and text colors are too close to one another (https://cloudup.com/cEoupH9h5uk). Again, probably a future iteration, but I would like to start thinking about how we can replicate that contrast mechanism for block styles and even potentially editor UI chrome.

> I was able to move it to its own group:

Awesome! That should work for now. I have some ideas for how we could improve the clarity of color-picker toolbar buttons but for the sake of shipping something that aligns with web, this is a great start.

> Thank you for catching that bug with the Reset button touchable area! I've fixed it in the latest build.

NICE! Thank you!

> That's correct, it does match the web behavior. I could open a ticket to investigate this in a future iteration, what do you think?

That would be great, if you don't mind!

I just saw @antonis comment about the "no-selection" interaction and I'm on the fence regarding whether or not this is a blocker. It would be nice to solve because I'm guessing it'll be a fairly common means of setting the color, although I don't have any concrete data to back that up.

---

Ignore the below comment, colors are actually being transferred as expected. I was either seeing things or inadvertently bumped the `reset` button before transforming 😬 .

~One new thing I just discovered — the colors aren't retained when you transform to a different block. Is that something that would be possible? I'm on the fence re: whether or not this is a blocker, but it would be nice to have, or at very least display a Dialog that warns the user that they may lose some styles when transforming. What do you think @geriux ?~

**Comment by geriux** [comment]
Hey there @antonis @iamthomasbishop 👋 this is ready for another review =)

Could you please check it when you have some time? These builds include the fixes to be able to set a text color when there's no text selected.

- [WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/17381#issuecomment-953617027)
- [WordPress Android](https://github.com/wordpress-mobile/WordPress-Android/pull/15504#issuecomment-953636219)

Let me know if you find any issues while testing. Thank you!

**Review by antonis — COMMENTED** [review]
Thank you for your hard work on this @geriux 🙇 
 
> These builds include the fixes to be able to set a text color when there's no text selected.

I tested the provided builds and and the issue is resolved. On a 1st pass the code changes also look good 👍 

I noticed another issue when a text is not selected and you change the color with the caret at the end of the word (without a whitespace before).

<details>
<summary>On iOS the last character before the caret changes color</summary>

https://user-images.githubusercontent.com/304044/144228737-531b3634-1656-402a-8282-f37aabec95da.mov
</details>

<details>
<summary>On Android the last character before the caret changes color and returns to the original color when you add a whitespace</summary>

https://user-images.githubusercontent.com/304044/144229010-dcd3b5d4-83e8-4b10-a40a-9735e9291852.mp4
</details>

<details>
<summary>Adding this extra observation in case it provides a hint in the source of the issue: On Android  when you perform the same steps on a 2nd word the last letter f the 1st word changes color again and remains that way</summary>

https://user-images.githubusercontent.com/304044/144229186-7b164cb1-173a-4146-9e90-77dfda4b7d32.mp4
</details>

**Comment by geriux** [comment]
Hey @antonis 👋 

Thank you for the feedback!

I created new builds with a fix for the cases where the previous last character would change its color, can you please check it again and let me know?

There's one edge case though when you want to change the color right after a character that already has a color set. If you don't add a space to change into a new color, it doesn't work. This also happens in core, since this feature is more focused to "Highlight" a selected text.

**Comment by iamthomasbishop** [comment]
@geriux I'm taking the latest build for a spin, it's looking great! I just have a couple of questions/bits of feedback, but I wouldn't necessarily consider them strictly blockers.

#### Non-block based theme initial state

For _non-block-based_ themes — where we aren't able to display the site background-color and a block doesn't have an overridden background-color setting — can we set the default button background color on the ToolbarButton to the base surface color (white in light mode, black in dark mode) instead of the dark gray that the ToolbarButton currently is? I think this is the missing piece beyond the 3 edge cases you solved for in your [previous round](https://github.com/WordPress/gutenberg/pull/36028#issuecomment-961207861). Is something like this proposal possible?

<a href="https://user-images.githubusercontent.com/1200432/144329221-2bc99ec8-e4d6-4db8-b59e-81a76827ea05.png"></a>

#### With background, no text colors

Another thing, but this may be out of scope and may have already been discussed. When trying out different flows, I wondered if we should display the background color + default text color on the Toolbar in the case where I've first applied a custom BG color to a block _but not adjusted any text colors_. Example:

<a href="https://user-images.githubusercontent.com/1200432/144330991-49f08a30-a0ec-4621-a39a-1c22c74b10ae.png"></a>

#### Various states

Here's a quick matrix of the various states, current vs. proposed:

<a href="https://user-images.githubusercontent.com/1200432/144334675-331b90b6-83c2-491c-8c3b-3d1a5de66711.png"></a>

## For future consideration

I've also got some ideas for how we might refine the styling on the toolbar button itself to be a bit more flexible, but we can leave that for a future iteration. For the sake of future consideration, here is a quick sketch of what I'm imagining:

<a href="https://user-images.githubusercontent.com/1200432/144334797-35b3f00a-bb7a-4f62-8b9f-b43f2e77a5fa.png"></a>

**Review by antonis — APPROVED** [review]
Thank you for making these change @geriux 🙇 

> I created new builds with a fix for the cases where the previous last character would change its color, can you please check it again and let me know?

I retested the new builds and everything works as expected in my test. The code also LGTM 🎉 

> There's one edge case though when you want to change the color right after a character that already has a color set. If you don't add a space to change into a new color, it doesn't work. This also happens in core, since this feature is more focused to "Highlight" a selected text.

I was able to reproduce that and I agree that this is not blocking at this point. It would be nice if we could align the color written with the color of the button at the toolbar in this case but this can be handled as a separated issue.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/304044/144406671-54059219-6d6b-477d-869c-778a76375fd8.mov
</details>

**Comment by geriux** [comment]
Hey @iamthomasbishop 👋 

Thank you for the feedback! After our internal discussions in regards to the UI, I pushed the latest changes and you can check them once the builds are ready 🙇

**Comment by iamthomasbishop** [comment]
@geriux Just tested the new build on iOS (iPhone 13 Pro and iPad Pro) and the changes we discussed yesterday are looking great. I'm not seeing any other issues on iOS but haven't had a chance to test on Android yet. I wouldn't expect any Android-specific issues, so if we can confirm that is the case then I think we can go ahead and ship this!

**Comment by geriux** [comment]
> @geriux Just tested the new build on iOS (iPhone 13 Pro and iPad Pro) and the changes we discussed yesterday are looking great. I'm not seeing any other issues on iOS but haven't had a chance to test on Android yet. I wouldn't expect any Android-specific issues, so if we can confirm that is the case then I think we can go ahead and ship this!

Awesome!! 🚀  I checked the Android build and it was working as it was on iOS. Thank you so much for all the feedback and testing! 👏

**Pull request merged**
