### PR TITLE
Revert refactoring hierarchical term selector using the data module

### LINKED ISSUE #11335: Taxonomy terms are gone in 4.2 rc-1
**Describe the bug**
For non admin users all taxonomies are now empty in the editor. It throws one (403) Forbidden error per taxonomy.

This is an issue with this specific version of GB, reverting back to 4.1.1 and everything is back to normal

**To Reproduce**
1. Open or create a new post
2. Try to expand the taxonomy tabs (I have only tried custom Taxonomies)
3. Nothing happens (except errors in console)

If these steps to reproduce doesn’t work I’ll add the console log tomorrow as I don’t have a computer available right now.

**Desktop (please complete the following information):**
 Chrome

**Additional context**
GB 4.2 rc-1

### PR DESCRIPTION
**Pull request by youknowriad**
closes #11335 and #11279

Reverts partially #10089

Unfortunately, we can't use the data module for taxonomies at the moment because the contributor's role can't access the edit context.

**Testing instructions**

 - Repeat instructions from #11335 
 - Repeat instructions from #11279

### CODE REVIEW

**Comment by notnownikki** [comment]
The new test in https://github.com/WordPress/gutenberg/pull/11359 catches this. Adding myself to the conversation here so I can keep track of when this is resolved :)

**Review by danielbachhuber — APPROVED** [review]
👍 I've manually tested as an author and verified that categories can be managed.

**Comment by slimmilkduds** [comment]
I just installed the nightly build from https://builds.danielbachhuber.com/gutenberg-nightly.zip and I still can't see taxonomies terms for non-administrators (I only use custom wp-roles). What specific capability is needed for this to work?

**Comment by slimmilkduds** [comment]
Never mind, I found that 4.1 rc 2 has been released and that works fine

**Pull request merged**
