### PR TITLE
Fix docs manifest

### PR DESCRIPTION
**Pull request by ajitbohra**
Moves scripts doc to proper manifest file & fixes page slug.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
Egg on my face. Sorry about this, I should have caught it!

**Review by aduth — APPROVED** [review]
Thanks 👍

**Comment by aduth** [comment]
Raised at: https://github.com/WordPress/gutenberg/pull/10510#discussion_r224774673

**Comment by aduth** [comment]
See: #10234

**Pull request merged**
