### PR TITLE
Try: Update Tertiary Button appearance

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Try some updates to the Tertiary Button appearance.

## Why?
There are a couple of issues I'm seeking to address:

* Tertiary Buttons currently have a unique padding value which looks a bit sloppy / unintentional when they appear next to other buttons.
* The hover effect features an outline, which overlaps a bit with the Secondary button style.
* The `active` state features a blue-on-grey appearance which looks a little muddy.

## How?
Taking inspiration from the updated Block Inserter, a solid background is applied instead of an outline on hover. Additionally the padding override is removed so that Tertiary buttons share padding with all other text buttons.

It's worth noting that the padding override was originally added to improve the optics when Tertiary buttons appear consecutively, e.g. here:

Screenshot 2023-03-07 at 13 20 46

But this feels like something that should be addressed at the 'organism' level rather than the component level. 

## Testing Instructions
* Open the Post or Site Editor
* Observe and interact with any Tertiary buttons

### Testing Instructions for Keyboard
* Focus a Tertiary button
* Ensure it is visually obvious that the button has focus

## Screenshots or screencast 

| Before | After |
| --- | --- |
| before | after |

### CODE REVIEW

**Comment by richtabor** [comment]
The save disabled draft and preview buttons are acting differently, I suspect from `disabled` applied to one and `aria-disabled` to the other. Not particularly related, just noting. 

https://user-images.githubusercontent.com/1813435/223473077-f7f21c57-812d-4284-a802-eca70fe328bb.mp4

Also noting how metrics will change in other areas we have double tertiary buttons: 

Before: 

CleanShot 2023-03-07 at 10 47 31

After: 

CleanShot 2023-03-07 at 10 46 16

**Comment by jameskoster** [comment]
> Also noting how metrics will change in other areas we have double tertiary buttons

Do you think this should be addressed at the component level, or contextually? I don't find the space between a Primary and Tertiary to be problematic:

Screenshot 2023-03-07 at 16 17 49

It's only consecutive instances of Tertiary buttons that feel too spaced out.

Sidenote: It's interesting that we use Tertiary buttons in some placeholder and Secondary ones in others 🙈 

Screenshot 2023-03-07 at 16 12 04

**Comment by richtabor** [comment]
> Do you think this should be addressed at the component level, or contextually? I don't find the space between a Primary and Tertiary to be problematic:

Maybe at the component level, if there's two tertiary buttons side-by-side. The oddity with the draft/preview buttons is that when they're disabled, they will show very close together (as there's a background color). 

> Sidenote: It's interesting that we use Tertiary buttons in some placeholder and Secondary ones in others 🙈

Yea I noticed that as well...

**Comment by jameskoster** [comment]
> Maybe at the component level, if there's two tertiary buttons side-by-side

I just noticed that we have a `ButtonGroup` [component](https://wordpress.github.io/gutenberg/?path=/story/components-buttongroup--default). I don't know how frequently it's used, but that would seem like an ideal place to add rules for things like consecutive Tertiary buttons. That can fix some inconsistencies we have atm, for example the buttons in the top bar have `gap: 8px` while the ones in placeholder have `margin: 12px`.

**Comment by jasmussen** [comment]
Thanks for taking a stab. Here's a before:

Screenshot 2023-03-08 at 08 33 15
Screenshot 2023-03-08 at 08 33 22

Screenshot 2023-03-08 at 08 34 16

Here's after:

Screenshot 2023-03-08 at 08 33 47

Screenshot 2023-03-08 at 08 33 54
Screenshot 2023-03-08 at 08 33 59

Overall, the new hover style is a vast improvement, I love it, let's at least land that. It will tie well into the hover styles in the inserter as well.

But the padding change really isn't working for me. 90% of the time, the tertiary/text buttons will be in their resting state, and without the adjusted padding, the spacing will look wrong. To be clear, I also think we need to update the disabled state. We already have a disabled state for the "✅ Saved" button, I don't see a reason the default button can't use the same visual appearance:

Screenshot 2023-03-08 at 08 41 12

Having reduced padding on the text only button is also going to be important for modals and dialogs where the confirm/apply button a text only. The larger the padding, the more it will misalign with the X.

Google Material is not a template for the work we do here, but it's useful to share how [they are also applying a smaller padding for text-only buttons](https://m3.material.io/components/buttons/specs#76b30881-a688-46c5-9a75-2872830879fc):
Screenshot 2023-03-08 at 08 38 51

Screenshot 2023-03-08 at 08 39 09

Screenshot 2023-03-08 at 08 40 36

**Comment by jameskoster** [comment]
> Having reduced padding on the text only button is also going to be important for modals and dialogs where the confirm/apply button a text only

Is this a convention we want to install? Iirc all our modals currently have a Primary / Tertiary combo. Indeed the unequal padding there was part of the inspiration for this PR (Cancel button is hovered):

Screenshot 2023-03-08 at 10 30 56

I suppose it's subjective, but that doesn't look right to me.

That said, I'm happy to make this PR purely about the hover state, and tackle the dimensions / active states separately.

**Comment by jasmussen** [comment]
> Is this a convention we want to install? Iirc all our modals currently have a Primary / Tertiary combo. Indeed the unequal padding there was part of the inspiration for this PR (Cancel button is hovered):

To me what stands out there is really the hover style, not the padding.

As for whether we'll ever have a text only "confirm" action in a modal? Probably not, but in the material documentation it seemed like a valid use case to consider:

Screenshot 2023-03-08 at 11 38 27

In any case, this to me just affirms that text buttons just work well when their padding are balanced towards their optical footprint. I would avoid any padding-changing mechanics of adjusting it only when they are shown as sequences. A text only button on its own still feels like it should have its padding adjusted.

**Comment by jameskoster** [comment]
That's the tricky thing in my mind, the optical footprint can change based on the situation, and there's no way for the atomic component to inherently interpret that. In your example above the text button either needs 0 padding, or a negative offset to align nicely with the preceding text. That detail would be the responsibility of a CardActions (or similar) component.

In any case, I reduce the padding 😁 It's 8px now rather than the original 6px, to better align with our baseline grid. It seems ok, but we can go back to 6px if necessary:


https://user-images.githubusercontent.com/846565/223693323-867ea078-3293-4d3e-8bdd-9bb801bdb95b.mp4

**Comment by jasmussen** [comment]
_I still prefer 6px 🙈_

I think we are missing an opportunity to look at the padding in a different way. If focus and hover styles were pseudo elements, they could have almost whatever padding we liked, without changing the base metrics (and consequently spacing) of the text button. I know that goes beyond your effort here.

**Comment by jameskoster** [comment]
> I still prefer 6px

Okay, I'll bite xD How come? 

If we're concerned with holistic alignment, and are committed to a 4px baseline, then 8px padding increases the likelihood that text will align naturally in certain scenarios? 6px is almost guaranteed to align with _nothing_.

**Comment by jasmussen** [comment]
> Okay, I'll bite xD How come?

The minimal spacing differential doesn't fix the original concern, but blurs the lines a little bit more. Further, the 6px padding was also chosen to account for mobile, and I'd be worried about a seemingly innocuous PR addressing that. 

The original issue is valid, but I think we can unbundle the padding change and discuss it separately, letting the excellent hover change land. The 2px differential in this PR is not enough to address the original issue, but just blurs the boundaries more. A better solution, I really believe and want to try in a PR, is to adjust the disabled, active, and focus states to explore pseudo elements that keep the full padding of the button, even if the reduced _footprint_ of the text button stays the same.

**Comment by jameskoster** [comment]
Fair enough, I've reverted to 6px. We can now treat this PR as solely changing the hover state.

**Comment by jasmussen** [comment]
Nice one! I was about to approve it, but then I realized that you are unsetting a box shadow rather than removing it at the source. I think we can probably remove it? 
Screenshot 2023-03-09 at 08 49 32

As far as the footprint, active/focus/disabled states, let's definitely follow up separately, but agree it would be nice to just land this hover state.

**Comment by jameskoster** [comment]
> rather than removing it at the source

Good catch, there's probably a better way to do that. It's currently applied to both secondary and tertiary 'at source', but we can move that to the secondary style only.

**Review by jasmussen — APPROVED** [review]

**Pull request merged**
