### PR TITLE
Change Verse icon from Carrot to Edit

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Changed Verse block icon from Carrot to Edit. We can have a quill then that's great, else the Pencil looks great.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Fixes: https://github.com/WordPress/gutenberg/issues/1913

**Review by timmyc — APPROVED** [review]
Yeah I'm kind of unsure what a carrot has to do with a verse, and the original PR called for future iterations so I think we should merge this in until the Quill icon lands.

**Comment by mtias** [comment]
We use the pencil for "editing" in various places, this will be confusing.

**Comment by timmyc** [comment]
Sorry just trying to clear out PR's, shall I revert @mtias ?

**Comment by mtias** [comment]
@timmyc no, it's ok :)

**Pull request merged**
