### PR TITLE
Font Library: Typo fixes

### PR DESCRIPTION
**Pull request by mikachan**
## What?

Small PR to tidy up some typos.

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
Lgtm!

**Comment by getdave** [comment]
I noticed this PR was merged after I raised the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959) and has changed PHP files that _may_ need backporting to WP Core.

I assume it will be covered in the effort to merge the Fonts API in a single backport commit?

**Comment by mikachan** [comment]
> I assume it will be covered in the effort to merge the Fonts API in a single backport commit?

Yes, this will be included in the single backport PR for the font library.

**Comment by cbravobernal** [comment]
I just cherry-picked this PR to the release/17.6 branch to get it included in the next release: f73908046f

**Pull request merged**
