### PR TITLE
[edit-widgets] Make global inserter usable by passing correct rootClientId to it

### PR DESCRIPTION
**Pull request by adamziel**
## Description

Global inserter is always inactive because it's receiving an incorrect `rootClientId`. That's related to the somewhat novel way in which blocks in the widgets editor are set up. This PR ensures the correct value is passed.

**Before**

Zrzut ekranu 2020-08-28 o 22 21 26

**After**

Zrzut ekranu 2020-08-28 o 22 21 31

## How has this been tested?
1. Go to the widgets editor.
1. Confirm the global inserter works.

## Types of changes
Non-breaking change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mapk** [comment]
It appears it's not positioned correctly. It should be flush to the left of the Editor/screen? Adjacent to the black admin menu.  I also noticed the tabs are missing. Is that intentional?

Screen Shot 2020-08-28 at 1 27 48 PM

**Review by youknowriad — APPROVED** [review]
Makes sense. I think the design is a separate issue as this was never refactored to use the "Panel" instead of the regular dropdown inserter.

**Comment by adamziel** [comment]
One more change here would be inserting the widget to the most recently selected widget area instead of the first one as it happens ATM.

**Comment by paaljoachim** [comment]
I see this has been merged.
Did the full regular Inserter panel with tabs for Block and Patterns get merged?

**Comment by adamziel** [comment]
I don't think it was merged just yet @paaljoachim

**Pull request merged**
