### PR TITLE
Remove the classic widgets panel only if the theme did not opt out of the new editor

### LINKED ISSUE #24949: Customizer: Error in console after opening a widget area when a theme opts-out of the new block-based “Widgets” screen
**Describe the bug**
Since Gutenberg 8.9.0 RC1 (#24087) it is possible to opt-out of the new block-based “Widgets” screen adding `remove_theme_support( 'widgets-block-editor' );` to any theme.

This keeps the legacy “Widgets” screen and prevent the new block-based “Widgets” screen to appear. 

But doing so does not bring back the legacy “Widgets” section on the customizer.

It's crucial to maintain this section for backward compatibility reasons, specially for themes that heavily use widgets for layout purposes or widgets that have many visual controls, like color pickers.

**To reproduce**
1. Using any theme, add `remove_theme_support( 'widgets-block-editor' );` in the `functions.php` file to opt-out of the new block-based “Widgets” screen.
2. Install and activate the Gutenberg 8.9.0 RC1 plugin in “Plugins → Add new”.
3. Click “Appearance → Customize”.
4. See that the legacy “Widgets” section is missing.

**Expected behavior**
When a theme opts-out of the new block-based “Widgets” screen, the legacy “Widgets” section should appear on the customizer.

**Screenshots**
missing-widgets-section-customizer

**Editor version:**
- WordPress version: 5.5.0
- Gutenberg [8.9.0 RC1](https://github.com/WordPress/gutenberg/releases/tag/v8.9.0-rc.1)
- TwentyTwenty 1.5

**Desktop:**
 - macOS 10.14.6
 - Chrome 85

### PR DESCRIPTION
**Pull request by adamziel**
## Description
Solves #24949 in a very non-elegant way. Let's talk.

The problem is that:
* The preferred way of removing customizer panels is via the `customize_loaded_components` hook. 
* The widgets panel should only be removed if the theme does call `remove_theme_support( 'widgets-block-editor' )` in response to `after_setup_theme` action.
* `customize_loaded_components` is fired before the theme's `functions.php` is even loaded!

This PR calls `$wp_customize->remove_panel( 'widgets' );` instead, the problem is that it's discouraged and generates a warning since WP 4.5:

"Removing widgets manually will cause PHP warnings. Use the customize_loaded_components filter instead."

https://core.trac.wordpress.org/ticket/35242

It makes sense - the design seems to assume that all the panels not removed via `customize_loaded_components` are assumed to stay, there may be some core, plugin, or theme code relying on that behavior.

It seems like relying theme support is not going to work for removing the `widgets` panel. We could either not rely on theme support and figure out a different solution, or remove the panel after the fact and suppress the warning.

CC @draganescu @noisysocks @kevin940726 @talldan @youknowriad

### CODE REVIEW

**Comment by draganescu** [comment]
I think this theme support flag is a temporary step, the real solution is via the Classic Editor plugin which can work using the standard panel removal procedure

https://github.com/WordPress/classic-editor/pull/137

**Comment by adamziel** [comment]
@draganescu do you meant that the "widgets" panel should be removed when the classic editor plugin is not installed?

**Comment by draganescu** [comment]
I am not sure of this, but my initial understanding of this was that the optimal way to opt out was to make it an option in the Classic Editor plugin. [This pr](https://github.com/WordPress/classic-editor/pull/137) makes it so that when you enable the Classic Editor you end up with the classic widgets editor as well.

The problem is it still uses the theme supports. If the theme supports is too late for the customiser we should make it so that feature of the Classic Editor ALSO calls customize_loaded_components. 

IMO, there is no real reason to have a theme supports flag. "Supports" is by definition meant fo opt-in! Opting out of the widgets editor should be via plugin - how the plugin does it is a separate subject. We ended up having one simply because the Classic editor was not ready with the opting out feature and we should deprecate it ;)

**Review by draganescu — COMMENTED** [review]
Edit: Wrong PR

**Comment by adamziel** [comment]
Blocked by https://github.com/WordPress/gutenberg/issues/25625

**Comment by draganescu** [comment]
This is not blocked anymore, as the work on the embedded block editor progresses we need to disable it when the block widgets editor is disabled.

**Comment by noisysocks** [comment]
We're moving the old panel using `remove_control` now.

https://github.com/WordPress/gutenberg/blob/c62ccd80c7c6abb85740cf8745439029bf0f4d35/lib/widgets-customize.php#L29-L36

**Pull request closed without merging**
