### PR TITLE
Add text color support to Columns block

### PR DESCRIPTION
**Pull request by AnthonyLedesma**
## Description
With the merge of #17813 columns block now supports Background color controls. This PR will add text color support to the core Columns block and is related to #16660. This uses the same method employed by the core Group block.

## How has this been tested?
Tested in supported browsers and ensured color classes and custom colors are applied to the columns block within the editor and the front-end.

## Screenshots 
columnsTextColor

## Types of changes
**New feature:** A new Text Color control for the Columns block, allowing folks to add a text color to their Column blocks.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by paaljoachim** [comment]
Thanks for working on this PR Anthony!

**Comment by AnthonyLedesma** [comment]
I have this tested and working locally. Please advise if there are any suggested changes.

**Comment by paaljoachim** [comment]
It sounds like the PR is almost ready for a code review.
It will fit perfectly in with the column block Background color.

**Comment by AnthonyLedesma** [comment]
Hi @paaljoachim,

I would love to see this included in the columns block. I got a look at Travis and I am not sure exactly the cause of the error. Would you mind getting a look for me and possibly providing more content?

Here is the error from Travis.
```bash
There are local uncommitted changes after one or both of 'npm install' or 'npm run docs:build'!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@7.4.0 check-local-changes: `( git diff -U0 | xargs -0 node bin/process-git-diff ) || ( echo "There are local uncommitted changes after one or both of 'npm install' or 'npm run docs:build'!" && exit 1 );`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gutenberg@7.4.0 check-local-changes script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-02-06T20_09_25_305Z-debug.log
The command "npm run check-local-changes" exited with 1.
```

**Comment by paaljoachim** [comment]
Hey Anthony.

I asked if @epiqueras could take a look.

**Comment by epiqueras** [comment]
You have uncommitted lock-file changes and/or documentation changes (`npm run docs:build`).

**Comment by epiqueras** [comment]
None of your changes should be changing the lock-file. Try removing the lock-file changes from the PR.

**Comment by AnthonyLedesma** [comment]
@epiqueras Thank you. Was getting some strange behavior. That is all sorted now. :)

**Comment by paaljoachim** [comment]
Regarding Design: It looks like Text color setting uses the default standard used also in other blocks.

What is left to do in this PR? Is it ready for a code review?

**Comment by AnthonyLedesma** [comment]
> What is left to do in this PR? Is it ready for a code review?

Ready for a code review from my end.  👍

**Review by getdave — COMMENTED** [review]
This is looking good to me.

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍 Thank you for submitting this PR!

As a follow-up, I think we should add some fixtures to try this attribute during the tests.

I'm also noticing a bug with contrast checking where the warning may appear multiple times:
image
cc: @epiqueras 

cc: @mapk to be aware of this addition and have a look on the design side.

**Comment by paaljoachim** [comment]
It is great to get this merged! 
Thank you Jorge!

**Comment by epiqueras** [comment]
>I'm also noticing a bug with contrast checking where the warning may appear multiple times:

There is one for each managed color. This needs to use the array form of contrast checkers:

```diff
- contrastCheckers: { backgroundColor: true, textColor: true },
+ contrastCheckers: [ { backgroundColor: true, textColor: true } ],
```

**Comment by karmatosed** [comment]
As far as design goes, that message really needs to only show once for the color checking, otherwise, it's really a lot visually.

From an iteration view, I want to move away from the double sidebar, we should explore like other blocks bringing this into the toolbar for color selection. I am almost thinking we could hold this off and bring in over rush it in. That said, I wouldn't stand in way of it being merged as-is. @mapk cc'ing you in for final decision there. I do feel we should move away from this pattern and into how cover and navigation are going for color, with it 'by the block'.

**Comment by epiqueras** [comment]
This is already merged, but I agree, we should move towards having these in the toolbar.

**Comment by karmatosed** [comment]
Oh my goodness, I didn't refresh the page so didn't see merged! Thanks for that. Let's iterate then.

**Comment by jorgefilipecosta** [comment]
> Oh my goodness, I didn't refresh the page so didn't see merged! Thanks for that. Let's iterate then.


@karmatosed, I'm sorry as the deadline for features was approaching I needed to merge this PR. It follows exactly what the group block did and that one was already merged, so I preferred to make sure both blocks are consistent.
I guess the visual bugs common for both blocks can be addressed during the beta period.

**Comment by jorgefilipecosta** [comment]
A fix for the repetition of messages in group and columns is available at https://github.com/WordPress/gutenberg/pull/20143. Thank you for providing the fix @epiqueras!

**Comment by ZebulanStanphill** [comment]
@karmatosed
> From an iteration view, I want to move away from the double sidebar, we should explore like other blocks bringing this into the toolbar for color selection.

See #20070.

**Pull request merged**
