### PR TITLE
Edit site: remove empty preview border and redirect to editor in global styles navigation

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Some quality of life improvements for Edit Site styles navigation in mobile view.

1. Ensure that the empty frame border does not appear in mobile view.
2. Ensure that viewport changes while in edit mode **and** on the styles route `p=/styles` don't result in the user being stuck in the styles view without a WP logo or any way to exit.

## Why?

1. Removes a weird and useless grey border
2. `/wp-admin/site-editor.php?p=/styles&canvas=edit` never opens the editor. That means, if I change from landscape to portrait in my mobile while viewing global styles in edit mode, I'm stuck on the styles screen with no way out.

## How?

1. Applies the border to the internal element, the iframe wrapper. It was the best and easiest thing to do for now, other than fiddle with the iframe style props.
2. Shows the editor in edit more rather than the global styles UI.

## Testing Instructions

1. Reduce the width of your browser to mimic mobile mode. The order is important here. 
2. Go to Appearance > Editor to visit the Site Editor.
3. Click on "Styles"
4. See now that there is no empty border 😮 
5. Now edit a page or enter edit mode somehow to visit the editor. Or just head to `/wp-admin/site-editor.php?p=/styles&canvas=edit`.
6. Open global styles from the settings menu
7. Change to "landscape" view by widening the viewport width. O
8. See that you are not stuck in the style panel.

#### The border 👎🏻 

https://github.com/user-attachments/assets/64ee288d-2fc8-43f4-a385-c75c4f2155a9

#### The editor 👎🏻 

https://github.com/user-attachments/assets/5035402a-8a1d-4082-a49e-b98300c5bbe1

#### The border 👍🏻 

https://github.com/user-attachments/assets/5583906d-0fdb-42b1-83c1-1e87186a751b

#### The editor 👍🏻 

https://github.com/user-attachments/assets/26bd7390-134f-42ec-b1c0-5aa5becce9f6

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
> Removes a weird and useless grey border

I'm wondering why the mobile layout doesn't show the iframe preview in the first place.

For example, if I switch from desktop to mobile layout, this preview shows up, but if I reload the browser this preview disappears:

https://github.com/user-attachments/assets/c8666a18-72c0-4fe1-b86f-60600efb4ccd


Perhaps [this part](https://github.com/WordPress/gutenberg/blob/fa636dc125301270d7ea28c1b90ac00ef612be75/packages/edit-site/src/components/global-styles/preview-iframe.js#L118-L148) is related, but I don't understand why the preview doesn't show up 🤔

**Comment by ramonjd** [comment]
Thanks for looking into this @t-hamano 

> Perhaps [this part](https://github.com/WordPress/gutenberg/blob/fa636dc125301270d7ea28c1b90ac00ef612be75/packages/edit-site/src/components/global-styles/preview-iframe.js#L118-L148) is related, but I don't understand why the preview doesn't show up

I was going to just remove that [width check](https://github.com/WordPress/gutenberg/blob/fa636dc125301270d7ea28c1b90ac00ef612be75/packages/edit-site/src/components/global-styles/preview-iframe.js#L110), but the [comments](https://github.com/WordPress/gutenberg/blame/fa636dc125301270d7ea28c1b90ac00ef612be75/packages/edit-site/src/components/global-styles/preview-iframe.js#L71) seem to point to larger issue so I did it the CSS hacky way.

Maybe we can disable that width check for the global styles panel 🤷🏻 cc @scruffian 

Removing the check would mean that the preview always shows I'm assuming

**Comment by t-hamano** [comment]
I've figured out a bit what's going on. It doesn't seem to be due to the width check. In the Styles screen for mobile layout, the editor doesn't get rendered. That means the iframe itself doesn't get rendered because `isInitialised` is `false` here:

https://github.com/WordPress/gutenberg/blob/d0177839747f999fff5f3d67761d4f5ee90c9ee3/packages/block-editor/src/components/iframe/index.js#L376-L391

It works fine if we wrap it in `BlockEditorProvider` like so, but I'm not sure if this is the right approach.

<details><summary>Diff</summary>

```diff
diff --git a/packages/edit-site/src/components/global-styles/preview-iframe.js b/packages/edit-site/src/components/global-styles/preview-iframe.js
index e830accf6d..c40518d906 100644
--- a/packages/edit-site/src/components/global-styles/preview-iframe.js
+++ b/packages/edit-site/src/components/global-styles/preview-iframe.js
@@ -19,9 +19,11 @@ import { useLayoutEffect, useState, useMemo } from '@wordpress/element';
  */
 import { unlock } from '../../lock-unlock';
 
-const { useGlobalStyle, useGlobalStylesOutput } = unlock(
-       blockEditorPrivateApis
-);
+const {
+       ExperimentalBlockEditorProvider,
+       useGlobalStyle,
+       useGlobalStylesOutput,
+} = unlock( blockEditorPrivateApis );
 
 const normalizedWidth = 248;
 const normalizedHeight = 152;
@@ -115,37 +117,41 @@ export default function PreviewIframe( {
                                { containerResizeListener }
                        </div>
                        { isReady && (
-                               <Iframe
-                                       className="edit-site-global-styles-preview__iframe"
-                                       style={ {
-                                               height: normalizedHeight * ratio,
-                                       } }
-                                       onMouseEnter={ () => setIsHovered( true ) }
-                                       onMouseLeave={ () => setIsHovered( false ) }
-                                       tabIndex={ -1 }
-                               >
-                                       <EditorStyles styles={ editorStyles } />
-                                       <motion.div
+                               <ExperimentalBlockEditorProvider>
+                                       <Iframe
+                                               className="edit-site-global-styles-preview__iframe"
                                                style={ {
                                                        height: normalizedHeight * ratio,
-                                                       width: '100%',
-                                                       .concat( children ) // This makes sure children is always an array.
-                                                       .map( ( child, key ) => child( { ratio, key } ) ) }
-                                       </motion.div>
-                               </Iframe>
+                                               <EditorStyles styles={ editorStyles } />
+                                               <motion.div
+                                                       style={ {
+                                                               height: normalizedHeight * ratio,
+                                                               width: '100%',
+                                                               background: gradientValue ?? backgroundColor,
+                                                               cursor: withHoverView ? 'pointer' : undefined,
+                                                       } }
+                                                       initial="start"
+                                                       animate={
+                                                               ( isHovered || isFocused ) &&
+                                                               ! disableMotion &&
+                                                               label
+                                                                       ? 'hover'
+                                                                       : 'start'
+                                                       }
+                                               >
+                                                       { []
+                                                               .concat( children ) // This makes sure children is always an array.
+                                                               .map( ( child, key ) =>
+                                                                       child( { ratio, key } )
+                                                               ) }
+                                               </motion.div>
+                                       </Iframe>
+                               </ExperimentalBlockEditorProvider>
                        ) }
                </>
        );
```

</details>

**Comment by ramonjd** [comment]
Thanks for digging in @t-hamano!

What do you think, should I revert my CSS hack here and leave open a proper fix for another PR? I'm not sure I can get to it.

**Comment by talldan** [comment]
> It works fine if we wrap it in BlockEditorProvider like so, but I'm not sure if this is the right approach.

I think I remember having a similar issue to this with the Patterns page, and that had to be wrapped with a `ExperimentalBlockEditorProvider`. It's still there today:
https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-site/src/components/page-patterns/index.js#L166

That makes me wonder if it's better to wrap the whole 'view' rather than a specific component.

**Review by t-hamano — APPROVED** [review]
I think it's okay to ship this PR with the CSS hack for now.

> That makes me wonder if it's better to wrap the whole 'view' rather than a specific component.

This is a good idea. As for the global styles preview for mobile layouts, it might be safer to address that in a follow-up.

Another thought: I don't understand why we need [the `Iframe` component as a wrapper](https://github.com/WordPress/gutenberg/blob/0c2442ee7b49139a7d3bb0256e5f8743255ce580/packages/edit-site/src/components/global-styles/preview-iframe.js#L118-L126) for the global styles preview in the first place.

The `Iframe` component doesn't render anything unless `__internalIsInitialized` in the block editor store is `true`, so we need the `BlockEditorProvider` provider, as shown [here](https://github.com/WordPress/gutenberg/blob/0c2442ee7b49139a7d3bb0256e5f8743255ce580/packages/edit-site/src/components/sidebar-navigation-screen-global-styles/content.js#L31-L37). But the global styles preview doesn't contain any blocks. All the data and styles needed for the preview should be available via the `GlobalStylesProvider` or the global styles context.

As a test, I made the following changes to not use the `Iframe` component, but the visual change is small, and I think it can be refactored with minor adjustments:

<details><summary>Diff</summary>

```diff
diff --git a/packages/edit-site/src/components/global-styles/preview-iframe.js b/packages/edit-site/src/components/global-styles/preview-iframe.js
index e830accf6d..4024cd19ae 100644
--- a/packages/edit-site/src/components/global-styles/preview-iframe.js
+++ b/packages/edit-site/src/components/global-styles/preview-iframe.js
@@ -115,7 +115,7 @@ export default function PreviewIframe( {
                                { containerResizeListener }
                        </div>
                        { isReady && (
-                               <Iframe
+                               <div
                                        className="edit-site-global-styles-preview__iframe"
                                        style={ {
                                                height: normalizedHeight * ratio,
@@ -124,7 +124,6 @@ export default function PreviewIframe( {
                                        onMouseLeave={ () => setIsHovered( false ) }
                                        tabIndex={ -1 }
                                >
-                                       <EditorStyles styles={ editorStyles } />
                                        <motion.div
                                                style={ {
                                                        height: normalizedHeight * ratio,
@@ -145,7 +144,7 @@ export default function PreviewIframe( {
                                                        .concat( children ) // This makes sure children is always an array.
                                                        .map( ( child, key ) => child( { ratio, key } ) ) }
                                        </motion.div>
-                               </Iframe>
+                               </div>
                        ) }
                </>
        );
```

</details>

**Comment by ramonjd** [comment]
Thanks for the investigation and help, folks 🙇🏻

**Pull request merged**
