### PR TITLE
Try: cover text block with color options

### PR DESCRIPTION
**Pull request by mtias**
image

### CODE REVIEW

**Comment by jasmussen** [comment]
I love this feature. I love it so much that I think this shouldn't be a separate block, but indeed _the text block_. This would require there was a "no swatch" option, though, to remove a color if you've already set one. We'd probably also want to add the block padding only if a swatch is selected, and longer term we'd want themes to be able to provide the swatches. 

However, I can understand that it would also be good to get some testing for this feature before deciding that the text block needs it. Especially when we're this close to 1.0. We might also find that this isn't a text feature at all, but instead the first block that is intended for other blocks to be nested inside. (Matías idea in a chat discussion)

As such, in the name of testing, 👍 👍  for merging from me.

**Comment by jasmussen** [comment]
I just realize that this block breaks a little bit with the design patterns laid forth in https://github.com/WordPress/gutenberg/blob/master/docs/design.md, which suggest that any basic actions you need to be able to take on the block should be doable without having the sidebar open. Since the primary purpose of this block is to change the background color and this is done in the inspector, it's arguably crossing that line.

This isn't important right now, because the primary purpose of this block is to "explore what's possible" in Gutenberg, and it does that super well. 

This can be fixed in a ton of ways, though:

1. Make this a feature of the text block. This is the obvious one. The purpose of the text block is text, and if you explore the advanced controls, _hey, there's the color!_

2. Move the swatch picker to be a button on the quick toolbar. Probably somewhat more tricky.

3. Tweak the defaults of the block to be about _highlighting a snippet of text_ or something in that vein, so it comes with a default color and look (preferrably a default supplied by the theme). This would make the block "useful" even in its non-color-configured state, and again, supply further customizations in the inspector.

**Comment by StaggerLeee** [comment]
I like this block, much.
News portals, but not only them, use it often.

Some options that could be added, so it could be more versatile.

- To filter easy what background and text colors are visible.
- To be able to align whole block (as Post image) left of text, right of text.

**Comment by mtias** [comment]
> To filter easy what background and text colors are visible.

Yes! This needs to exist for themes to supply a palette, and could be easily configurable by plugins as well.

> To be able to align whole block (as Post image) left of text, right of text.

I disabled floated left/right from this block, but we can easily enable it back if we think it'd be useful.

**Comment by melchoyce** [comment]
I'd love to eventually see this idea merged with Cover Image to create a... nestable "Banner" or "Section" block, maybe? Wording on it will be hard. I'm thinking:
- You can change the background to display an image, video, or a background color (or even gradient!)
- You can drop all text blocks (header, paragraph, lists, etc.) and the button block into it

**Pull request merged**
