### PR TITLE
Comment pagination blocks: Add spacing support

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Adds spacing block support to
Comments pagination, comments pagination next, previous and numbers.

## Why?

So that users can adjust the spacing, and for consistency.
Related: https://github.com/WordPress/gutenberg/issues/43243

## How?

Adds spacing block support in block.json.

## Testing Instructions

The testing steps are the same for the four blocks, test both individual blocks, global style settings, and theme.json style settings.

1. First make sure that your test installation has some comments, and that comment pagination is enabled in the WordPress admin area under Settings, Discussion, "Break comments into pages"
2. Create or open a post or page template in the site editor and add a comments block.
3. In the comments block, locate the nested comment pagination block.
4. Confirm if the comment pagination block and the inner blocks have a dimension panel with the margin and padding available, but hidden by default.
5. Make adjustments to the spacing. Confirm that the spacing is applied correctly in the editor.
6. Save and view the front, confirm if the spacing is applied correctly on the front.

Continue to test the block's layout (spacing) settings in the global styles sidebar in the site editor.
_Note that the comment pagination next/previous and numbers have the same names in the styles sidebar as the query pagination blocks. So if at first you fail, try the other._

Theme.json example code:
```
"styles": {
		"blocks": {
			"core/comments-pagination": {
				"spacing": {
					"padding" : {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						},
						"margin": {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						}
					}
			},
			"core/comments-pagination-next": {
				"spacing": {
					"padding": {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
					},
					"margin": {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						}
					}
			},
			"core/comments-pagination-previous": {
				"spacing": {
					"padding" : {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						},
						"margin": {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						}
					}
			},
			"core/comments-pagination-numbers": {
				"spacing": {
					"padding" : {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						},
						"margin": {
							"top": "100px",
							"right": "100px",
							"bottom": "100px",
							"left": "100px"
						}
					}
			}
		}
	}
```

### CODE REVIEW

**Comment by carolinan** [comment]
There are some problems with the styling on trunk and I am trying to work out what CSS changes that needs to be done.

In 6.1, in the editor, the CSS is output in this order:
```
.editor-styles-wrapper .is-layout-flex > * {
    margin: 0;
}

.wp-block-comments-pagination>.wp-block-comments-pagination-next, .wp-block-comments-pagination>.wp-block-comments-pagination-numbers, .wp-block-comments-pagination>.wp-block-comments-pagination-previous {
    margin: 0.5em 0.5em 0.5em 0; // This is not applied because it is overridden by the flex style above.
}
```

While on the front, the CSS output is:

```
.wp-block-comments-pagination>.wp-block-comments-pagination-next, .wp-block-comments-pagination>.wp-block-comments-pagination-numbers, .wp-block-comments-pagination>.wp-block-comments-pagination-previous {
    margin-right: 0.5em;
    margin-bottom: 0.5em;
}

body .is-layout-flex > * {
    margin: 0;  // This is only partially applied because it is overridden by the margins above.
}
```

So the distance between the inner blocks as well as the spacing between the pagination and the block after is different in the editor and the front.

**Comment by carolinan** [comment]
@c4rl0sbr4v0 I consider this to be low priority, but do you remember why the spacing between the comments pagination inner blocks where handled with both margins and block gap? Could this spacing be handled with block gap only?

**Comment by cbravobernal** [comment]
@carolinan I guess there is no specific reason for using both margins and the gap if this last one was enough. It could be our lack of knowledge about theming in this case.

Feel free to update, as you are quite more experienced in themes!

Also, we can ping @MaggieCabrera or @mikachan as Theme experts too.

**Comment by mikachan** [comment]
> Could this spacing be handled with block gap only?

Looking at the styles that are output for the comments pagination elements, it looks like we can just use block gap here 👍

**Comment by carolinan** [comment]
I can confirm that this is still blocked. The margins added through theme.json or global styles work in the site editor and block editor, but on the front they are overridden by the layout styles as described in this comment: https://github.com/WordPress/gutenberg/pull/45107#pullrequestreview-1178530518


```
body .is-layout-flex > * {
	margin: 0;
}
.wp-block-comments-pagination-previous {
	margin-top: 100px; //this is overridden by the margin 0 above.
	margin-right: 100px; //this is overridden by the margin 0 above.
	margin-bottom: 100px; //this is overridden by the margin 0 above.
	margin-left: 100px; //this is overridden by the margin 0 above.
	padding-top: 100px;
	padding-right: 100px;
	padding-bottom: 100px;
	padding-left: 100px;
}
```

**Comment by carolinan** [comment]
When adding margin and padding to the comment pagination block via the global styles sidebar, I am now seeing the following:

Site Editor, margin is not applied:
```
.editor-styles-wrapper .wp-block-comments-pagination.block-editor-block-list__layout {
	margin: 0;
}
<style>
.editor-styles-wrapper .wp-block-comments-pagination {
	margin-top: var(--wp--preset--spacing--60); //this is overwritten
	margin-right: var(--wp--preset--spacing--60); //this is overwritten
	margin-bottom: var(--wp--preset--spacing--60); //this is overwritten
	margin-left: var(--wp--preset--spacing--60); //this is overwritten
	padding-top: var(--wp--preset--spacing--40);
	padding-right: var(--wp--preset--spacing--40);
	padding-bottom: var(--wp--preset--spacing--40);
	padding-left: var(--wp--preset--spacing--40);
}
```

Front, no issues:
```
.wp-block-comments-pagination {
	margin-top: var(--wp--preset--spacing--60);
	margin-right: var(--wp--preset--spacing--60);
	margin-bottom: var(--wp--preset--spacing--60);
	margin-left: var(--wp--preset--spacing--60);
	padding-top: var(--wp--preset--spacing--40);
	padding-right: var(--wp--preset--spacing--40);
	padding-bottom: var(--wp--preset--spacing--40);
	padding-left: var(--wp--preset--spacing--40);
}
```

**Comment by carolinan** [comment]
In classic themes that does not enable spacing settings, the following  CSS is output on the front:
```
body .is-layout-flex > * {
	margin: 0;
}

.wp-block-comments-pagination-numbers {
	margin-right: 0.5em; //this is overwritten
	margin-bottom: 0.5em; //this is overwritten
}
```
and

```
body .is-layout-flex > * {
	margin: 0;
}

.wp-block-comments-pagination-previous {
	margin-right: 0.5em;  //this is overwritten
	margin-bottom: 0.5em;  //this is overwritten
}
```

**Comment by carolinan** [comment]
But this is the CSS output on the front in the same classic theme, Twenty Ten,  when Gutenberg is deactivated.
This is the correct spacing.

```
.wp-block-comments-pagination>.wp-block-comments-pagination-next:last-child, .wp-block-comments-pagination>.wp-block-comments-pagination-numbers:last-child, .wp-block-comments-pagination>.wp-block-comments-pagination-previous:last-child {
	margin-right: 0;
}
.wp-block-comments-pagination>.wp-block-comments-pagination-next, .wp-block-comments-pagination>.wp-block-comments-pagination-numbers, .wp-block-comments-pagination>.wp-block-comments-pagination-previous {
	margin-bottom: 0.5em;
	margin-right: 0.5em;
}
body .is-layout-flex > * {
	margin: 0;
}
```

**Comment by carolinan** [comment]
I give up for today 😆 
Removing the editor CSS does not seem to have a negative impact when using a theme that has a theme.json file and spacing support enabled.

But I don't think the issues in the classic theme that does not have a theme.json are introduced by this PR. The loading order of the CSS is different when Gutenberg is active.

**Comment by cbravobernal** [comment]
Hi @carolinan !

I've been away on paternity leave for a few time. How can I help you here?

**Comment by carolinan** [comment]
@c4rl0sbr4v0 I am not sure. The remaining issue is the CSS specificity, so it is bigger than this single PR... The block styles are being overwritten, and the CSS is different depending on what the theme type is, classic or block.
So it might be a bit much to catch up with!

**Pull request closed without merging**
