### PR TITLE
Enforce curly braces in eslint config

### PR DESCRIPTION
**Pull request by talldan**
## Description
On a few PRs recently I've noticed the eslint 'curly' rule that requires curly braces for if, else, for, while, or do statements isn't resulting in errors.

The cause is prettier's eslint config which purposely disabled some rules that could cause a conflict with prettier's formatting. 

However, the docs mention that some of these rules can be re-enabled when configured in a particular way:
https://github.com/prettier/eslint-config-prettier#curly

Curly is one of those rules if configured using the 'all' option, which just happens to be what WordPress also requires.

## How has this been tested?
1. Checkout this PR
2. Write an if statement in your editor without curly braces
3. There should be a linting error (some editors may need to be restarted for the rule to take effect)

## Screenshots 
Screenshot 2020-11-11 at 6 37 17 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
Looks like a few to fix in the codebase as well. I can sort those out tomorrow.

**Comment by gziolo** [comment]
I think we decided to get rid of all overrides to let Prettier do all formatting work. How is Prettier behaving in the setup proposed, will it reformat code to omit curly braces for short lines?

**Comment by talldan** [comment]
@gziolo Thanks for the context, I wasn't aware that we had some overrides previously.

It worked fine in my testing with a long line, no issues with the automated fix.

**Comment by gziolo** [comment]
It's a bit inconvenient for me as a developer that when I have a line like:

```js
if ( ! onIndexChange ) return;
```

ESLint errors complaining about the stylistic issue, but running Prettier doesn't fix it. We can discuss it with a wider group of folks on WordPress Slack in `#core-js` channel. I'm personally against this proposal.

**Comment by talldan** [comment]
@gziolo Is that using a prettier plugin for your editor? I use the eslint one and it handles both linting fixes and prettier fixes, including the curly braces.

**Comment by talldan** [comment]
fmt

**Comment by gziolo** [comment]
> Is that using a prettier plugin for your editor? I use the eslint one and it handles both linting fixes and prettier fixes, including the curly braces.

I see what you did. I have the regular Prettier integrated with VSC. I also tried `npm run format-js`. In both cases, it doesn't format the code as intended. This is also what people using `@wordpress/scripts` will use by default. This is why I'm hesitant to introduce this change.

**Comment by talldan** [comment]
I looked into this further, as an option could be to contribute upstream to `wp-prettier` or `prettierx`, but I wanted to double-check if this is in prettier's scope. According to prettier's docs (https://prettier.io/docs/en/rationale.html), this isn't something that should be formatted:

> Prettier only prints code. It does not transform it.
> Here are a few examples of things that are out of scope for Prettier:

With an item in that list being:
> Adding/removing {} and return where they are optional.

As this is a WordPress project, I do think we should be doing our best to enforce WordPress coding standards, which is why I think we should improve this.

Is the issue that you feel this is too strict for users of `wp-scripts`? Should we have a way of optionally declaring a stricter ruleset, which we could use for gutenberg? I'm just trying to understand the context behind your comments @gziolo.

**Comment by gziolo** [comment]
For the full context, let's include the link to the current coding standards:
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#blocks-and-curly-braces

I raised this issue for discussion during the next weekly WordPress Core JS chat. 

I doubt that the Prettier project would accept any new flags. We tried several times with WordPress spacing rules and were forced to use `wp-prettier` fork because of their rejection. Again, I think that we should update Coding Standards to align with what Prettier does rather than adding exceptions. In fact, we removed many exceptions when introducing Prettier, so we might miss this case because we didn't have any occurrences of shorter notation in the codebase at that time.

**Comment by gziolo** [comment]
We discussed this PR during in the [`#core-js`](https://wordpress.slack.com/archives/C5UNMSU4R/p1605627429440300) channel on WordPress Slack (link requires registration at https://make.wordpress.org/chat/.

This PR reports 55 violations that are fixable with the ESLint rule propose:
> 55 errors and 2 warnings potentially fixable with the `--fix` option.

We didn't come up with any conclusion yet but people expressed that they are fine deferring the formatting to the tool - Prettier. It would be great to stay aligned with PHP coding standards but it feels like they are diverging anyway.

**Comment by talldan** [comment]
Closing based on feedback.

**Pull request closed without merging**
