### PR TITLE
Color palette: make the Clear link consistent with buttons in other settings

### PR DESCRIPTION
**Pull request by eliorivero**
This PR updates the Clear link in the color palette to make it consistent with similar actionable elements found in other panels like the Reset buttons in Text Settings:

captura de pantalla 2018-08-11 a la s 13 38 17

or the Image Settings panel:

captura de pantalla 2018-08-11 a la s 13 38 10

## Description
This PR converts the link into a small default button.

## How has this been tested?
Tested manually

### Before

captura de pantalla 2018-08-11 a la s 13 40 20

### After

captura de pantalla 2018-08-11 a la s 13 40 04

## Types of changes
Several attributes are set for the Button component so it's rendered as a small button.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Review by karmatosed — APPROVED** [review]
I don't mind this although I do still feel it could be a text link. With not minding it in mind let's add and see if people benefit from it.

**Comment by eliorivero** [comment]
Thanks for the approval Tammie. I've updated the snapshot to reflect the changes introduced and now tests pass.

**Review by tofumatt — APPROVED** [review]
Yaaaay this has always bothered me so much, thanks for making it a button ❤️

**Comment by mtias** [comment]
Nice, thanks for the update!

**Pull request merged**
