### PR TITLE
Update @wordpress/a11y README.md

### PR DESCRIPTION
**Pull request by scheinercc**
## What?

Update browser support link. 

## Why?

The current link ends in a 404.

## Testing Instructions

1. Open a https://developer.wordpress.org/block-editor/reference-guides/packages/packages-a11y/#browser-support
2. Click on the link
3. Make sure it does not end in a 404, but on a page with browser support info

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
Nice catch 👍

**Comment by scheinercc** [comment]
@t-hamano - I am now getting hundreds of emails for pull/push notifications from https://github.com/UserAdminD3us/gutenberg. Any way to unsubscribe from all of them?

**Comment by t-hamano** [comment]
@scheinercc I've never experienced that, but do you have all notifications enabled for this repository or for your forked repository?

image

**Comment by scheinercc** [comment]
Mine was on "Participating and @mentions". Changed to ignore. Thanks!

image

**Pull request merged**
