### PR TITLE
Monitor store deps in useSelect

### PR DESCRIPTION
**Pull request by adamziel**
🚧 TBD

### CODE REVIEW

**Comment by gziolo** [comment]
@youknowriad, what was the reason `createRegistrySelector` was introduced in the first place? Is it possible that it is used too often these days?

**Comment by youknowriad** [comment]
I don't remember exactly the original reasons but I do know we use it for at least two things:

- we did several refactorings: moving from core/editor to core/block-editor for blocks, moving from core/editor to core/data for entities and with these core/editor selectors need to call selectors from other stores.
- Initiall isResolving calls were not store specific, we had a common store that tracked resolution state for all the other stores and isResolving from a high-level store were calling the lower level store selectors.

**Comment by gziolo** [comment]
> I don't remember exactly the original reasons but I do know we use it for at least two things:
> 
> * we did several refactorings: moving from core/editor to core/block-editor for blocks, moving from core/editor to core/data for entities and with these core/editor selectors need to call selectors from other stores.
> * Initiall isResolving calls were not store specific, we had a common store that tracked resolution state for all the other stores and isResolving from a high-level store were calling the lower level store selectors.

Yes, it all makes sense to use `createRegistrySelector` for backward compatibility. Do you think, we should refactor all usage of selectors that use this helper as a way to proxy other selectors? My assumption is that if we use `createRegistrySelector` as a way to proxy deprecations then we don't use them in Gutenberg which makes it possible to find a way to make store specific `useStoreSelectors` react only to updates scoped to its own store. In fact, we could update the implementation of `createRegistrySelector` to make it possible for `useStoreSelectors` to behave like an isolated store until a first call of the selector wrapped with this helper happens. When the `createRegistrySelector` wrapped selector is called, it would enable backward compatibility mode that listens to updates in all stores.

**Comment by youknowriad** [comment]
> Do you think, we should refactor all usage of selectors that use this helper as a way to proxy other selectors?

What do you mean? these are already proxy selectors.

I also think we have use-cases where we want to combine results from several stores in a single selector.

**Comment by adamziel** [comment]
> I also think we have use-cases where we want to combine results from several stores in a single selector.

Couldn't those be replaced with react hooks?

**Comment by gziolo** [comment]
> > Do you think, we should refactor all usage of selectors that use this helper as a way to proxy other selectors?
> 
> What do you mean? these are already proxy selectors.

There are more selectors like the following:

https://github.com/WordPress/gutenberg/blob/cdd9b9efd41e5acc534a60cc79877c96afb32b10/packages/edit-site/src/store/selectors.js#L43-L45

**Comment by adamziel** [comment]
I added some relevant considerations in https://github.com/WordPress/gutenberg/pull/26692#issuecomment-724003463 - let's move the discussion there?

**Comment by adamziel** [comment]
Closing for now (see https://github.com/WordPress/gutenberg/pull/26692#issuecomment-724003463).

**Pull request closed without merging**
