### PR TITLE
[RNmobile] Upgrade to RN 0.61.5

### PR DESCRIPTION
**Pull request by hypest**
## Description
Gutenberg side PR to support the React Native version upgrade to 0.61.5.

## How has this been tested?
Using the gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1450

## Types of changes
* RN bumped to `0.61.5`
* A test snapshot file updated to account for the `clickable` -> `focusable` change
* Bump Jest to `^24.9.0`, and removal of `hasteImplModulePath` from its config
* A fix in the check-licenses.js script to better handle dual license cases ('ORing' of licenses)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by hypest** [comment]
The "License compatibility" job fails on 57b233d because the `xmldom` package has `(LGPL-2.0 or MIT)`. I wonder, does the "or" cover us here, considering that the MIT license is compatible? @pento , maybe you have a clue on this one?

**Comment by pento** [comment]
@hypest This is failing because the license has `or` instead of `OR`. 🙃

https://github.com/WordPress/gutenberg/blob/7a0e48c9158c4d7193a0274aa99ab039552fb1a2/packages/scripts/scripts/check-licenses.js#L152-L153

Changing that check to `formattedLicenseType.includes( 'or' )` should fix it.

**Comment by hypest** [comment]
> Changing that check to formattedLicenseType.includes( 'or' ) should fix it.

Thanks for the pointer @pento ! Can I bother you to review the additional [changes I made to the check-licenses script](https://github.com/WordPress/gutenberg/pull/19369/files?file-filters%5B%5D=.js#diff-8649d6528dc502fdb8a7ec230013920a)? I had to modify the 'or' pattern to check, to avoid an unbound recursion when the `GPL-2.0-or-later` string is tested. Thanks!

**Comment by pento** [comment]
`check-licenses` change looks good to me! 👍🏻

**Review by gziolo — APPROVED** [review]
You will have to resolve `package-lock.json` conflicts before proceeding. There is RN 0.62.x :)

I guess it would require a React version upgrade. You can tackle next once this change lands.

**Comment by hypest** [comment]
> You will have to resolve package-lock.json conflicts before proceeding. There is RN 0.62.x :)
>
> I guess it would require a React version upgrade. You can tackle next once this change lands.

Yeap, in the process of looking into resolving the conflict now.

RN 0.62 will be tackled in a different upgrade attempt. Does Gutenberg (web) requires that update _now_?

**Comment by gziolo** [comment]
> RN 0.62 will be tackled in a different upgrade attempt. Does Gutenberg (web) requires that update _now_?

Not really, as far as I can tell. It would be nice to update before WP 5.4 though, which is in 2-3 weeks. @youknowriad and @jorgefilipecosta what do you think?

**Comment by hypest** [comment]
FWIW @gziolo , I opted to resolve the merge conflict in favor of keeping the `dependencies` section inside the `@wordpress/scripts` entry in the lock file. You think that's OK? I'm not sure if it matters or not.

**Comment by gziolo** [comment]
I would say if Travis is happy let's move forward. I can fix the lock file later if it introduces too much package duplication. Maintaining all those packages ain't easy :)

**Comment by hypest** [comment]
Force-pushed to undo the previous merge-from-master and redo it.

**Comment by hypest** [comment]
With https://github.com/WordPress/gutenberg/pull/19369/commits/fcb5fefb8079db1a273762b6a1453e61a1661dfe, I _manually_ resolved conflicts and noticed that in some cases I opted for the change from master and in others opted for the changes in this PR. That feels weird to me. I wonder what's the proper/recommded way of doing the package-lock.json update @gziolo . I also assume that deleting the final altogether and running `npm install` might also not be the right way since that seems to introduce too many changes?

**Comment by jorgefilipecosta** [comment]
> > RN 0.62 will be tackled in a different upgrade attempt. Does Gutenberg (web) requires that update _now_?
> 
> Not really, as far as I can tell. It would be nice to update before WP 5.4 though, which is in 2-3 weeks. @youknowriad and @jorgefilipecosta what do you think?

Yes, I think it would be nice to upgrade. But upgrading RN does not change anything on the JavaScript production build core uses right?

**Comment by gziolo** [comment]
I see that it upgrades React version to `16.11.0`:

https://github.com/facebook/react-native/blob/2bf7f1046d135ec3c46e8cc497898f4f57c1b4d5/package.json#L84-L86

See https://github.com/facebook/react-native/tree/v0.62.0-rc.1 for more details.

**Comment by jorgefilipecosta** [comment]
I guess in this case we should upgrade React in Gutenberg ASAP as it is currently in 16.9.0, so the new version is tested for sometime before the beta release.
Should I add a note upgrade react to 16.11.0 on the must-have board?

**Comment by hypest** [comment]
RN 0.62 is still in RC stage at the time of writing. I'd recommend waiting for a bit to fully release and stabilize after that. What usually happens is that there are some important issues found and fixed right after a major RN version bump.

**Pull request merged**
