### PR TITLE
Move selection to end of link after insertion.

### PR DESCRIPTION
**Pull request by SergioEstevao**
## Description

This PR updates the caret position to be at the end of the link, after insertion or change. This follows the same approach that was implemented on the web here: https://github.com/WordPress/gutenberg/pull/17126

It also fixes the issue described here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2319

## How has this been tested?

This can be tested using the PR on GB-Mobile here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2323

## Types of changes

Bugfix and enhancement.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by guarani** [comment]
Hey @SergioEstevao haven't tested it myself yet but I see a test is failing – not sure if flaky tests so I reran the tests so we can check back tomorrow.

**Comment by guarani** [comment]
I'm holding off testing because of the bug that @Tug [reported here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2323#issuecomment-634618953).

**Review by guarani — APPROVED** [review]
Working great, tested here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2323#pullrequestreview-419429736

**Review by Tug — APPROVED** [review]
👍

**Pull request merged**
