### PR TITLE
Update lodash

### PR DESCRIPTION
**Pull request by youknowriad**
Nothing fancy here, just want to silence some audit messages.

### CODE REVIEW

**Review by ajitbohra — APPROVED** [review]
LGTM 👍

**Comment by youknowriad** [comment]
the e2e test failure here is consistent but I'm not able to find why it's failing.

**Comment by ItsJonQ** [comment]
I'm poking at the E2E test now. So far, no luck!

Other folks are more than welcome to give it a shot! 🙏

**Comment by ItsJonQ** [comment]
@youknowriad Not sure if this is helpful! If I remove the following PHP code from `client-assets.php`, the `console` error (which appears to be causing issues) goes away:

```php
gutenberg_register_vendor_script(
	$scripts,
	'lodash',
	'https://unpkg.com/lodash@4.17.19/lodash.js',
	array(),
	'4.17.19'
);
```

I'm unsure how the vendor_script code helps in regards to `lodash` `4.17.19`. By unsure, I just mean that I'm inexperienced with this particular vendor asset workflow within Gutenberg.

(I'm not saying we remove. It looks like it's important in regards to the lodash versioning. Maybe? 😛 )

**Comment by youknowriad** [comment]
Looks like loading on the footer did the trick. Awesome @ntsekouras thanks.

**Pull request merged**
