### PR TITLE
Replace "Add new post" link text with more meaningful Label (v2)

### PR DESCRIPTION
**Pull request by carstingaxion**
I messed up my [first PR](https://github.com/WordPress/gutenberg/pull/59743) on the same thing, this is my 2nd try in which I followed all [suggestions from the review](https://github.com/WordPress/gutenberg/pull/59743#pullrequestreview-1957790126) by @t-hamano review. :pray: _Thank you for your kindness!_

---

## What?

This PR replaces the static "*Add new post*" link text inside the the query block, with a more meaningful label from the currently selected post type.

## Why?

This PR is [polishing the existing UI](https://github.com/WordPress/gutenberg/pull/27732) with data, that is already available, without introducing any new elements. 

## How?

Removes a static text string, with the `add_new_item` label from the currently selected post type.

## Testing Instructions

1. Open a post or page.
2. Insert a query block.
3. Open the inspector controls
4. Switch the queried post type
5. And see the link text change, depending on the selected post type, within the `CreateNewPostLink` element.

### Testing Instructions for Keyboard

*Test can be done by keyboard as well, without any additions to my **Testing Instruction**.*

### Before

https://github.com/WordPress/gutenberg/assets/198883/a2bdb869-305a-448d-b47c-7a201db8dfdb

### After

https://github.com/WordPress/gutenberg/assets/198883/593ee111-2674-400c-9bac-420b68fa4578

### CODE REVIEW

**Comment by carstingaxion** [comment]
Dear @t-hamano , please could you take a look, once more?

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR! This PR seems to work as expected.

Post:

image

Page:

image

In order to ship this PR, we need to merge the latest trunk into it (See [this Slack comment](https://wordpress.slack.com/archives/C02QB2JS7/p1717680505976509)). Would you be willing to try this?

The following steps should do the trick:

1. Check out the trunk branch: `git checkout trunk`
2. Fetch the latest changes from upstream: `git fetch upstream`
3. Incorporate the upstream changes into the trunk branch of your local repo: `git merge upstream/trunk`
4. Check out the branch this PR was submitted in: `git checkout feature/better-create-new-post-link-v2`
5. Merge trunk branch: `git merge trunk`
6. Push to the remote branch: `git push origin feature/better-create-new-post-link-v2`

**Comment by carstingaxion** [comment]
> In order to ship this PR, we need to merge the latest trunk into it (See [this Slack comment](https://wordpress.slack.com/archives/C02QB2JS7/p1717680505976509)). Would you be willing to try this?

I tried. And with your detailed & friendly explanation, things went surprisingly well on my side. Thank you very much @t-hamano !!!

Now, let's see what happens over here.

**Review by t-hamano — APPROVED** [review]
Thanks for the update! The merge is done correctly 👍

**Comment by carstingaxion** [comment]
Thank you for not giving up and helping me to reach the finish line! Thank you very much @t-hamano .

**Pull request merged**
