### PR TITLE
List View: Remove unused selector from the 'useBlockSelection' hook

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
PR removes the unused `getBlockSelectionEnd` selector from the 'useBlockSelection' hook.

## Why?
I don't believe this selector was ever used (introduced in #38314), so it doesn't affect the `updateBlockSelection` callback.

## Testing Instructions
CI tests are passing.

### CODE REVIEW

**Comment by alexstine** [comment]
@Mamaduka Please see this related PR: https://github.com/WordPress/gutenberg/pull/48708

Work is happening around the list view right now, just want to make sure no one would be unintentionally blocking efforts.

Thanks.

**Comment by Mamaduka** [comment]
@alexstine, this shouldn't affect any work done that PR.

**Review by alexstine — APPROVED** [review]
With the above confirmed, LGTM. 👍

**Review by andrewserong — APPROVED** [review]
Thanks for spotting this one @Mamaduka — from memory, I was originally playing around with using `getBlockSelectionEnd` and eventually realised that the end of the selection would always be using `clientId` or `destinationClientId` instead, so this looks like a stray leftover from that exploration.

Thanks for the caution @alexstine! From testing this PR out with each of the keyboard and mouse combinations for multi selection within the list view, this change appears safe to me, and doesn't seem to impact the other in progress work.

LGTM!

**Comment by Mamaduka** [comment]
Thanks for the reviews and additional context 🙇

**Pull request merged**
