### PR TITLE
Block editor: move content styles to avoid triggering iframe compat mode

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Currently there's some new styles in the block-editor stylesheet that target blocks (content). These should be added to a separate content stylesheet so they can be properly added inside the iframe without using compat mode.

## Why?

We shouldn't use compat mode in core, it's meant for plugin compat.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by andrewserong** [comment]
I just noticed on `trunk` that some of the block appender styles aren't rendering correctly, and from a git bisect it looks like it's since this PR was merged. The two issues I found were:

| When no block is selected (button block appender has the wrong colors) | When a group block is selected (button block appender has wrong width) |
| --- | --- |
| image | image |

I wasn't sure if this is an issue with the order in which the CSS is loaded, or something more particular to how the styles are loaded in the iframe?

**Comment by aaronrobertshaw** [comment]
I found today that the Query Loop block and its inner block's inspector controls are out of whack. The git bisect points to the commit for this PR. At first glance it didn't appear this PR should cause any dramas there so I re-ran the bisect again with the same results. Manually checking out the commit prior to this one works as expected.

I've created an issue for this https://github.com/WordPress/gutenberg/issues/47101. Would you have any ideas on what the issue is @ellatrix?

**Comment by ellatrix** [comment]
@andrewserong It looks like there's a rule `.components-button.has-icon { min-width: 36px; }` that shouldn't be applied there. @jasmussen Would it be possible to have a look at this? 😄 You've also recently worked on the button+icon component width. Thank you!

**Comment by jasmussen** [comment]
I saw the naked plus and actually liked it 😄 

That said, it doesn't seem like an issue anymore, do you know if it was fixed separately? 
Screenshot 2023-01-23 at 11 11 41

Screenshot 2023-01-23 at 11 11 37

**Pull request merged**
