### PR TITLE
InnerBlocks: move wrapper classes to BlockList

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This PR moves the class `is-overlay` currently added to inner blocks wrapper to the block list wrapper. This will make it easier to allow a block to have its own inner blocks wrapper as all necessary props are already on the same wrapper.

It's unfortunate that this wrapper div was added in the past as it seems unnecessary. Quite a few blocks now have selectors for it, so it avoid breakage, it's better to make removing opt-in together with the block list wrapper.

The `is-capturing-toolbar` is currently not used by anything.

The columns blocks renders a bit strange for small screens, but that's the case in `master` as well.

## How has this been tested?

Test the click overlays for nested blocks.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
>The columns blocks renders a bit strange for small screens, but that's the case in `master` as well.

Are you referring to #18416?

**Comment by jasmussen** [comment]
> The is-capturing-toolbar is currently not used by anything.

This is likely a feature that is there to enable some blocks where the parent toolbar absorbs the child block toolbar, which makes sense for child blocks that can be rotated, and other situations. It was created in part for 3rd party blocks, so I'd be careful in removing it. CC: @getdave — is this correct? Should we add a note in the code so it's not refactored away?

**Comment by youknowriad** [comment]
Seems like something is off in this PR? (see commits)

**Comment by ellatrix** [comment]
Yeah, I think a bad rebase. I added it to #19910.

**Pull request closed without merging**
