### PR TITLE
A margin option is added to the Embeded preview block

### PR DESCRIPTION
**Pull request by HILAYTRIVEDI**
## What?
This PR will add the option to set margins to the embeds.

## Why?
This PR will allow the user to add the margins to the embeds preview.

## How?
The option is added to the inspector control to add the margins to the block.

## Testing Instructions
Here are some steps to check the implementation ;
1.  Add the embedded block to posts or pages.
2.  Add the link to the embed.
3. After adding the link you will notice the additional option to set the margin to the preview.

## Screenshots or screencast 
https://www.loom.com/share/6dbca6117ec6416aad995319736db226

### CODE REVIEW

**Comment by carolinan** [comment]
Thank you for the pull request @HILAYTRIVEDI.

Gutenberg already has a Dimensions panel with a margin option.
Instead of a new attribute and a new default margin (which would change the design of the block), we should reuse the existing panel.

Please add block support for spacing and margin in block.json instead.
Example: At the bottom of block.json of the embed block, you will find a section for **supports**:
```
	"supports": {
		"align": true
	},

```
You can add the block support for spacing and margin there:

```
	"supports": {
		"align": true,
		"spacing": {
			"margin": true
		}
	},

```
This is a much smaller change, and you do need to regenerate the documentation, but you don't need to make the changes to edit.js, save.js, the controls or the preview.

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan, Thanks for this. I reverted my changes and added the margin support to the block.json file as per your instructions.

**Comment by carolinan** [comment]
Hi @HILAYTRIVEDI Are you able to continue working on this pull request? (to rebase it and solve the conflict).

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan yes sure I will do that.

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan, I can't see any conflicts here, all good to go from my end.

**Review by carolinan — APPROVED** [review]
I have tested the pull request with Twenty Twenty-Three, which has support for spacing enabled in theme.json.
I tested a youtube embed and an embedded link to a WordPress.org support article and the margin worked well in the editor and front.

(In post content, the margin is less visible because of the ` layout` constraints)

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan, can we merge this if all looks good?

**Comment by carolinan** [comment]
The PR needs to be rebased so that all tests are run.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for iterating on this one @HILAYTRIVEDI 👍 

The change looks good to me and tests as advertised. 

In terms of the padding block support it makes sense to omit it. It's arguable as to whether it would provide any benefit, even if we opted into background color support. Adding the ability to set a border on the embed might be more desirable in a follow-up.

So given that, I think this should be right to go after it gets a rebase and the tests pass.

**Comment by HILAYTRIVEDI** [comment]
Okay I will rebase it by EOD (IST).

**Comment by HILAYTRIVEDI** [comment]
Hi @carolinan  and @aaronrobertshaw  Can we merge this? As it passed all the checks.

**Pull request merged**
