### PR TITLE
Improve RTL rendering

### LINKED ISSUE #1565: Meta boxes arrow icons in RTL
Many things still need to fully support RTL languages in the UI. One small detail is about the meta boxes icons. 

They're currently using a right-arrow icon when collapsed and a down-arrow icon when expanded:

screen shot 2017-06-28 at 17 29 55

See also related discussion on Slack https://wordpress.slack.com/archives/C02QB2JS7/p1498468801241441?thread_ts=1498209002.818056&cid=C02QB2JS7

If the right-arrow icon is going to stay, I guess it should be swapped to left-icon for RTL languages. I think this is something WordPress does during the build process with a custom grunt plugin `swap-dashicons-left-right-arrows`. Instead, Gutenberg sets these icons in the component, depending on the meta box opened state:
`icon={ this.state.opened ? 'arrow-down' : 'arrow-right' }`

/cc @ocean90

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This PR improves the RTL appearance of Gutenberg:

screen shot 2017-12-06 at 13 09 05

Additionally, it might fix #1565, as it also flips horizontally the arrow icon.

## How Has This Been Tested?

Chrome on Mac.

## Steps to test

- Set your admin language to an RTL language, like Arabic
- Edit or write a post in Gutenberg

### CODE REVIEW

**Review by afercia — COMMENTED** [review]
Not familiar with the filter property, seems it looks ok.

However, I'm getting a PHP warning when I switch to RTL.
```
<b>Warning</b>:  strpos() expects parameter 1 to be string, array given in
<b>/srv/www/wordpress-develop/public_html/build/wp-includes/functions.php</b> on line <b>3451</b><br />
``` 

Seems when Gutenberg is activated, `$mce_init['plugins']` in the core `_mce_set_direction()` is no longer a string but an array. When Gutenberg is deactivated, it's a string, as expected.

**Comment by youknowriad** [comment]
I haven't tested yet, but by looking at the screenshot, I think we should switch the "undo/redo" icons in RTL

**Comment by jasmussen** [comment]
Great feedback, both — I'll look at how to best flip around undo/redo, though I think I'll need help fixing that PHP error. I assumed it was an issue with my local docker.

**Comment by youknowriad** [comment]
I pushed a fix for the php error.

About the styling in RTL. I saw a lot of places where we need to change padding/marging from left to right etc...

screen shot 2017-12-07 at 09 25 31

screen shot 2017-12-07 at 09 25 23

screen shot 2017-12-07 at 09 25 07

screen shot 2017-12-07 at 09 25 02

screen shot 2017-12-07 at 09 24 53


I'm probably missing some other places as well, I wonder if it's not better to just use something like https://www.npmjs.com/package/postcss-rtl

**Comment by jasmussen** [comment]
Thanks so much Riad.

> I'm probably missing some other places as well, I wonder if it's not better to just use something like https://www.npmjs.com/package/postcss-rtl

I think we absolutely should! Do you have time to help me out with this? It's not super urgent.

**Comment by youknowriad** [comment]
@jasmussen Sure let me try it :)

**Comment by jasmussen** [comment]
🏅

**Comment by youknowriad** [comment]
Update with the postcss plugin, it looks like it works properly. We still have some issues (popovers) because these are JS generated styles but most of the issues are solved.

What do you think?

**Comment by jasmussen** [comment]
I think this is incredibly impressive, and thanks so much for doing this. I think it's a solid update, and brings us to a point where we can have individual highly specific tickets for each remaining RTL item, instead of one big mammoth umbrella "fix RTL" ticket. 👍 👍  and thanks again

**Comment by youknowriad** [comment]
@jasmussen It looks like I broke non-rtl languages :) looking

**Comment by youknowriad** [comment]
WP adds a `dir=rtl` to the `html` tag when using an `rtl` language, the postcss plugin rely on it but also on a `dir=ltr` on `ltr` languages. I added a small "hack" to fix this but this should be moved to WP Core on merge.

**Comment by youknowriad** [comment]
#3844 is merged, let's close this one. Good job everyone

**Comment by jasmussen** [comment]
🎉🎉

**Pull request closed without merging**
