### PR TITLE
Add optional icon to snackbar

### PR DESCRIPTION
**Pull request by becdetat**
## Description

- added option icon property to the snackbar component
- added a corresponding icon property to the `core/notices` data store actions

## How has this been tested?

- snackbar component has been tested in storybook
- We've forked the component in WooCommerce Admin to iterate and test locally faster, and this feature has been tested in https://github.com/woocommerce/woocommerce-admin/pull/5563

## Screenshots 
image

## Types of changes
- new feature - this should not affect existing code. This just adds a new, optional property to the snackbar component.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
This looks good, thanks for contributing the change upstream.

I've added the 'Needs design feedback' label, as the gap between the icon and text looks a bit big to me. Not a designer so would appreciate a second opinion. (cc @mapk @karmatosed).

As it doesn't affect anything in Gutenberg, I've approved the PR, so we can always merge first and adjust that later if needed.

**Comment by mapk** [comment]
I agree with @talldan. Maybe we can adjust the spacing between the icon and the text to something closer to 12px?

Snackbar Wrapper

**Comment by becdetat** [comment]
Thanks @mapk , I think this looks much better:

image

I'll merge this and open another PR if it needs refining.

Thanks for the review @talldan

**Comment by talldan** [comment]
Thanks @mapk!

@becdetat, I've merged this one, congrats on your first merged PR to the project 🎉 

Feel free to ping me on the followup PR for a review.

**Pull request merged**
