### PR TITLE
WIP: Missing Blocks: Allow extracting contents as blocks

### LINKED ISSUE #13391: Inner Blocks are lost if Parent Container Block is removed.
There are many plugins available that create a Container ( Section or Row ) block that allow Inner Blocks to be added. Examples: Atomic Blocks, CoBlocks, Ultimate Addons for Gutenberg etc. Deactivating any of the plugins tested results in the following warning within the Editor.

screenshot 2019-01-20 at 18 47 58

If the user chooses to **Keep as HTML** or switches to the Code Editor then all of the Inner Block content is lost. There is no ability to extract the Inner Blocks as a Common Block or as HTML.

**Replicate this issue**

NOTE: I have chosen the Atomic Block plugin for this example, but as mentioned it effects all of these types of plugin.

WordPress 5.0.3
Gutenberg 4.8
Atomic Blocks  1.4.23

1. Install Atomic Blocks plugin from WordPress repository
2. Add a AB Container Block.
3. Populate the AB Container Block with a single Title Block.
4. Switch to Code Editor and this is the resulting output:

screenshot 2019-01-20 at 19 19 29

5. Deactivate Atomic Blocks Plugin.
6. Check Page Preview to see that Inner Block Content remains intact.
7. Within Editor switch to Code Editor and this is the resulting output:

screenshot 2019-01-20 at 19 19 40

This ultimately leads to 'Block Lock'. The only way the user can retain the content added to a Container Block is to extract them before the plugin is deleted. This could lead to loss of user content within the Editor. 

Proposed solution: Option to extract all blocks as separate HTML or Common Blocks

### PR DESCRIPTION
**Pull request by dmsnell**
**DO NOT MERGE**

Resolves part of #13391
Alternate approach to #14443

When the editor encounters a block without a registered block type
it transforms that unknown block into a generic "missing block."

A post's author is free to convert that unknown block into a kind
of static view from the original saved HTML of the block.

Unfortunately this model breaks down when the original block
includes nested blocks. Up until this point the editor has failed
to account for those inner blocks.

---

In this patch we're adding a new option to the missing plugin to
allow "extracting" the inner contents. That is, instead of simply
converting to static HTML the extract option splits the inner
contents into a new list of blocks as if simply removing the
outer wrapper.

This approach doesn't completely solve the editor's problem because
parts of the extracted contents may be wrong, but it provides a
reasonable fallback behavior to recover what is possible in the
situation where the editor can't understand a block.

---

 - extracts inner blocks and content when a block is unsupported
 - creates `core/html` blocks out of non-block content inside
   unsupported blocks

 - solve the issue of missing inner block HTML when converting
   to static HTML. this should be resolved in another patch.
 - improve the messaging for unsupported blocks during an edit session
 - fully resolve issues surrounding unsupported blocks

ExtracingBlocks mov

### CODE REVIEW

**Comment by diggeddy** [comment]
@dmsnell thanks for the update. Looks like we're getting somewhere. Really appreciate the effort going into this.

**Comment by brandonpayton** [comment]
I spoke with @dmsnell outside this issue, and it is known that this PR doesn't resolve the problem of lost content on save. That may be addressed as part of this PR or in another PR.

**Comment by diggeddy** [comment]
@brandonpayton is this is a related issue? we look to be struggling to achieve a resolution on this issue alone. Be concerning if it is inter-linked with another.

**Comment by brandonpayton** [comment]
Thanks for saying something, @diggeddy. I misinterpreted the title of #13391 "Inner Blocks are lost if Parent Container Block is removed".

What I mentioned is not the same issue but is related. Not only is it difficult to extract inner blocks from missing parent blocks, the inner blocks are also lost when the post is next saved.

**Comment by brandonpayton** [comment]
I created #15202 to track lost inner blocks on save.

**Comment by dmsnell** [comment]
@diggeddy I'm afraid this is highly-connected to a number of related issues throughout core relating to block invalidation and unsupported blocks. it's part of why I've been so slow on it. what you initially saw is what I'm tossing out there as a symptom of a deeper problem and one that I want to be careful that we address without grinding to a full halt. that is, when we solve this specific problem I want to make sure we have opened a path towards resolving the deeper problem and this is why I object to an approach that starting mixing structures blocks in memory with reserialized HTML as block attributes.

**Comment by diggeddy** [comment]
The only workaround i found regarding locked and lost inner blocks  when a block is missing is to open the page in Classic Editor - its not pretty but at least the HTML is salvageable.  I know the ideal solution would be to eject the inner blocks but as a temporary fix would converting to the Classic Block be viable?

**Comment by dmsnell** [comment]
> I know the ideal solution would be to eject the inner blocks but as a temporary fix would converting to the Classic Block be viable?

The next step that I want to do is actually update the `save()` function on the default missing block so we don't lose content. I overlooked it here because I was focussed on the specific task at-hand which was extracting, not preserving.

Ideally I'd love to see some kind of indicator like spell-checkers have that says "ignore this one" - a form of telling the editor to stop bugging me about the fact that this block is invalid and just show a read-only view of the block.

If we convert to HTML or into a classic block or extract the components we're _changing_ the content and I don't see why we have to give up a valid static fallback render if we don't need to. In fact, WordPress _preserves_ blocks on render just fine this way and right now it's only when opening the editor that the editor obliterates those blocks - again, this isn't by intention but rather I think it just got passed over in the rush to release the project in 5.0

Let me see what I can do with the `save()` here because I think it can get us pretty far.

I may want to change `originalInnerContent` and `originalInnerBlocks` and friends to a single `originalBlock` property on the block itself rather than changing the block attributes, or just replacing those attributes. We'll see what happens but regardless I think we have more complexity we can actually remove while making the edit flow better.

**Comment by dmsnell** [comment]
@diggeddy and @brandonpayton I've updated this to cover the cases of _Convert to HTML_ and also of preserving content on save. it's…somewhat working…working to the point where I think it helps expose the complexity in `createBlockWithFallback()` that needs to be ripped out before this works _well_.

I suspect that before we can really get this through we'll need to refactor `createBlockWithFallback()` to preserve more of the original stage-1 parse of each missing block. Further, we need to audit and eliminate uses of `innerHTML` and `originalContent` since those are scattered around and _will_ result in broken output. I need to `@deprecate` `innerHTML`

**Comment by tomusborne** [comment]
Great to see some progress here - thanks for all your hard work @dmsnell!

I have a pretty basic container block I've developed that I want to release to the public, but I'm worried about potential breaking changes when a concrete solution to this issue is merged. Do you foresee any issues like that, or am I safe to go ahead and release it?

Thanks again!

**Comment by dmsnell** [comment]
@tomusborne there shouldn't be any conflict unless you are replacing the missing-block-block

with a container this should give us the ability to extract all the inner blocks from it, but shouldn't rely on anything you write

as a general rule, please avoid `innerHTML` though because that's an old artifact from before nested blocks were in use

**Comment by mcsf** [comment]
I was on leave when @dmsnell started this PR so I missed it. Meanwhile, #14443 has been merged. Can we close this one?

**Pull request closed without merging**
