### PR TITLE
chore: Rename `phpcs.xml` to `phpcs.xml.dist`

### PR DESCRIPTION
**Pull request by ntwb**
This change allows users to define a local `phpcs.xml` configuration for their own use. For example a user may want to use the `colors` option for CLI output as that was requested in #1685.

See https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

### CODE REVIEW

**Review by westonruter — APPROVED** [review]

**Comment by youknowriad** [comment]
This is confusing to me, why do we want this to be a dist, we want everyone to use the same codestyle don't we?

**Comment by youknowriad** [comment]
yeah I know but do we have this for `eslint`? I don't think this is valuable, I think we should enforce the same thing without any change for everyone. If we want it to be stricter we should add it for everyone.

**Comment by ntwb** [comment]
It doesn't have to be about rules, here's an example `phpcs.xml` file to make _my_ terminal output a little prettier:

```xml
<?xml version="1.0"?>
<ruleset name="@netweb's custom `phpcs.xml` for Gutenberg Plugin">

	<rule ref="phpcs.xml.dist"/>

	<!-- Use colors in output -->
	<arg value="-colors"/>

	<!-- Show Progress -->
	<arg value="p"/>

</ruleset>
<!-- https://gist.github.com/ntwb/2df0042c9a50466a20eb41a8070f5fe5 -->
```

Another example, with PHPUnit this same approach is possible (even here in Gutenberg), with bbPress I've a custom `phpunit.xml` file that I use to add a _listener_ for `@covers` annotations in test files, it adds extra overhead and shouldn't be in the main repo's `phpunit.xml.dist` file but is a great addition for myself locally for a bbPress side project.

**Comment by youknowriad** [comment]
> here's an example phpcs.xml file to make my terminal output a little prettier:

If it's make it prettier, let's add it for everyone

>  I use to add a listener for @covers annotations in test files, it adds extra overhead and shouldn't be in the main repo's phpunit.xml.dist file but is a great addition for myself locally for a bbPress side project.

Shouldn't this be for the `bbPress` project, why do we need it for gutenberg.

**Comment by ntwb** [comment]
> If it's make it prettier, let's add it for everyone

It wasn't added because of this https://github.com/WordPress/gutenberg/pull/1685#issuecomment-312780011

> Shouldn't this be for the bbPress project, why do we need it for gutenberg.
It was just an example use case

**Pull request merged**
