### PR TITLE
Add 40px size lint rule for Block Editor typography components

### PR DESCRIPTION
**Pull request by mirka**
Part of #63871

## What?

Adds lint rules for `__next40pxDefaultSize` prop adherence on the following `@wordpress/block-editor` components:

- FontAppearanceControl
- FontFamilyControl
- LineHeightControl

### Testing Instructions

The lint error should trigger for violations [as expected](https://github.com/WordPress/gutenberg/pull/64410#discussion_r1712431913).

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
Looks like ESLint is finding a missing `__next40pxDefaultSize` for `FontFamilyControl`  — which means that the lint rule is working 😁

**Comment by mirka** [comment]
> Looks like ESLint is finding a missing `__next40pxDefaultSize` for `FontFamilyControl` — which means that the lint rule is working 😁

Tweaked the rule to exclude all test and story files (1c541c7). In my experience up to this point, there's no need to check these statically with Eslint, because once we start logging deprecation warnings we'll need to adhere in runtime.

**Review by ciampo — APPROVED** [review]
Sounds good 🚀

**Review by tyxla — APPROVED** [review]
Nice, thanks 👍 🚀

**Pull request merged**
