### PR TITLE
Paste: reuse file transforms for file pasting

### LINKED ISSUE #45408: Paste handler: No way to support non-image file types
### Description

We have some custom media blocks over on Day One and I'm attempting to support uploads via paste and drag and drop.

Adding a raw handler transform works fine for the image block, since the paste handler finds the transform and passes it through. However, I can't generalize this code to support video/audio/pdf, because it turns out the file paste handler [only allows image files through](https://github.com/WordPress/gutenberg/blob/3c9a0207f51d731ff4d8cfbfa69daa16f797639f/packages/block-editor/src/components/rich-text/file-paste-handler.js#L9).

This seems to be at odds with how the raw handler works, since the raw handler [looks at block transforms](https://github.com/WordPress/gutenberg/blob/626cb0d15aa7423f9713dd88c7d791ae35329ef0/packages/blocks/src/api/raw-handling/html-to-blocks.js#L26) to see if anything matches.

It seems like there's no way to filter the supported files here and I need to basically re-implement the entire paste handler (though the rich text component included by the standalone editor will still include the default one). Is that correct or is there another way to tackle this?

### Step-by-step reproduction instructions

Add a raw transform to any block with a file type other than image. Paste that file into the editor and note that the paste handler does not call the transform.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

`@wordpress/block-editor` @ 9.3.0 (standalone)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/45408.

Don't know why this hasn't come up before. Guess no one tried to paste videos or audio before?! 😄 

My only concern with this (and for dropping files) is that it assumes all the files will be off the same block type. That should be fixed...

Requesting some reviews here of people that have previously worked on adding the transforms for dropping files.

## Why?

Currently it's not possible to paste anything but image files.

## How?

This PR reuses the `files` transforms that we already have on blocks for file _pasting_ also, instead of creating some HTML with blob URLs to run through the raw handler.

## Testing Instructions

Copy a video and paste it in Gutenberg.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
I just gave it a quick test from the angle of the Gallery/Image paste side and this change doesn't affect anything there at all - the Gallery block ignores pastes as it does in trunk at the moment, only drag and drop works (would be nice to enable paste at some point), and the Image block only accepts image file pastes ... but pasting elsewhere in canvas works for video file as advertised.

**Comment by ellatrix** [comment]
> the Gallery block ignores pastes as it does in trunk at the moment, only drag and drop works (would be nice to enable paste at some point), and the Image block only accepts image file pastes ... 

Ah nice, I didn't know that. Yes, let's enable that in a separate PR. I don't want to overcomplicate this one right now.

**Comment by ellatrix** [comment]
@glendaviesnz Could you test again with Gallery and review the changes to the gallery block? We made some changes.

**Review by glendaviesnz — APPROVED** [review]
Nice! Pasting images with the gallery block placeholder selected now adds those images to the gallery, and all other gallery functions seem to work as expected.

Pasting non-image files onto the gallery placeholder replaces the gallery block with the relevant block type, eg. video or file block. This is different to the behaviour when dragging and dropping invalid file types onto the placeholder, in which case they are rejected with a message about invalid file type. It would be good if the behaviour was the same in both cases, but I don't have an opinion about which would be preferred, and I don't think it should hold up this PR.

All the other pasting worked as expected for me with these changes, ie. single and multiple image, video or pdf files pasted in the canvas created the relevant blocks.

**Pull request merged**
