### PR TITLE
Writing Flow: Fixing Show + Arrow multi selection across Spacer

### LINKED ISSUE #53674: Writing Flow: Shift + down-arrow key to select across spacer block selects one too many blocks
When I press shift+down arrow across a spacer block, I select 3 blocks instead of two.

Steps to reproduce

* Insert a paragraph, a spacer, then a paragraph
* Set the caret in the middle of the first paragraph
* Press Shift + Down arrow

Observe that three blocks get selected. As is shown in this GIF:

3 blocks selected

Test content:

```
<!-- wp:paragraph -->
<p>Paragraph 1 (spacer block below)</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"20px"} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>(spacer block above) Paragraph 2</p>
<!-- /wp:paragraph -->
```

### PR DESCRIPTION
**Pull request by bangank36**
## What?

Fix issue happens on https://github.com/WordPress/gutenberg/issues/53674

## Why?

- Shift + down-arrow key to select across spacer block are selecting too many blocks
260688744-ebacc902-7343-4824-a748-e83474302d91

## How?

- Spacer is skipped by browser because of its empty content and its children are hidden from the DOM
   - More on [multi-selection based on the native selection across blocks](https://github.com/WordPress/gutenberg/blob/77453a104d5c438ecf2aa21bc7bceef59b0f0d78/packages/block-editor/src/components/writing-flow/use-selection-observer.js#L87)
- 1st attempt is to update Spacer handle visibility instead of setting `display: none` https://github.com/WordPress/gutenberg/issues/53674#issuecomment-1689594974
- 2nd attempt insert BR inside Spacer block

## Testing Instructions

- Run `npm run dev`
- Edit a post
- Add a Text Block - Spacer - Text Block
- Select first text block then press Shift + Arrow down
- Expect to select the first Text Block + Spacer as 2 selected items instead of all 3 blocks

## Screenshots or screencast 
- Check 1st attempt recordings on https://github.com/WordPress/gutenberg/issues/53674#issuecomment-1689594974
- BR approach fix https://github.com/WordPress/gutenberg/issues/53674#issuecomment-1694643333

cc: @jasmussen

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, thanks for working on this. 

I'm having some trouble, I can only press shift+down once, which correctly selects the spacer and nothing more. But I can't press shift+down after that to continue into the next paragraph. Same with up:

selecting

Am I doing something wrong? Thanks

**Comment by bangank36** [comment]
>  I can only press shift+down once, which correctly selects the spacer and nothing more

@jasmussen I think this is expected? As I tested on trunk with other other non-spacer blocks and it not allow to select the next block neither
The attached video demostration Shift+ArrowUp and Shift+ArrowDown on Editor and Sidebar showed the same behavior

https://github.com/WordPress/gutenberg/assets/10071857/0e8a9f8f-4ebc-4474-b6f6-8be17e7a361c

**Comment by jasmussen** [comment]
Oh it's definitely not expected, but it looks like you're right, this appears to be a bug in trunk as wel! Meaning, it will likely be fixed in this branch if we get it fixed in trunk as well.

CC: @ellatrix do you recall if someone worked on shift+arrow selection recently?

**Comment by bangank36** [comment]
> this appears to be a bug in trunk as well

I figured this is responsible for the cross selection issue https://github.com/WordPress/gutenberg/blob/12c60c785c2a34dce782b5f674b58ed54a8eaca1/packages/block-editor/src/components/writing-flow/use-multi-selection.js#L82


https://github.com/WordPress/gutenberg/assets/10071857/3c87ca6e-0fd3-452f-875f-c601d78575b5

**Comment by bangank36** [comment]
I made some other tests and it appears to me that multi-select with Shift+Arrow across non-text blocks is blocked in [useMultiSelection](https://github.com/WordPress/gutenberg/blob/12c60c785c2a34dce782b5f674b58ed54a8eaca1/packages/block-editor/src/components/writing-flow/use-multi-selection.js#L82), while Shift+Arrow is not blocked. 
Shift+Arrow across text blocks is allowed because it not [a full selection](https://github.com/WordPress/gutenberg/blame/12c60c785c2a34dce782b5f674b58ed54a8eaca1/packages/block-editor/src/components/writing-flow/use-multi-selection.js#L68C11-L68C26)

These recordings show the current behavior on Editor and List View

| Shift Click (list) ✅ | Shift Click (editor) ✅ | Shift Arrow (list) ❌ |  Shift Arrow (editor) ❌ |
|---|---|---|---|
|  <video src="https://github.com/WordPress/gutenberg/assets/10071857/d8c1224e-ff0f-4eb4-9782-d6b4bbee5a60"/> |  <video src="https://github.com/WordPress/gutenberg/assets/10071857/8228cc8a-3527-457d-acf9-16dda26e92e7"/> |  <video src="https://github.com/WordPress/gutenberg/assets/10071857/bb88758a-dcae-4ecc-9da6-3557d7d1238d"/> |  <video src="https://github.com/WordPress/gutenberg/assets/10071857/4d58c08c-aff9-4d0e-8326-c8ad95e92ee0"/> |

I can't find the clue for [resetting the selection](https://github.com/WordPress/gutenberg/blob/12c60c785c2a34dce782b5f674b58ed54a8eaca1/packages/block-editor/src/components/writing-flow/use-multi-selection.js#L82) on Shift+Arrow, maybe you have some insights? cc: @youknowriad @andrewserong

**Comment by andrewserong** [comment]
Thanks for the ping @bangank36. I'm not sure if this helps at all, but as far as I can tell this issue doesn't affect the list view when focus is within the list view prior to using shift+up/down arrow. In the screengrab you shared, it looks like the list view is open, but focus is currently within the editor canvas.

When I try to reproduce, if I have the Image block selected in the editor canvas and then attempt to shift+down arrow to select adjacent paragraph blocks, I can't. However if I shift focus to the list view (click twice on the Image block in the list view), then shift+up/down works correctly:

https://github.com/WordPress/gutenberg/assets/14988353/968696d8-f00a-4c85-8ee7-e75a5885ad03

Hope that helps narrow things down slightly!

**Comment by bangank36** [comment]
> Hope that helps narrow things down slightly!

Thanks for pointing out the focus of the editor vs. list view! Though I am still not sure if the reset selection is expected or not

**Comment by bangank36** [comment]
Closed as there is no reviewer

**Comment by ellatrix** [comment]
@bangank36 Sorry that no one came to review. I'll think a bit on the solution you presented and if there's an alternative way. I don't like that we have to modify blocks for multi selection to work properly. It's not a general fix, for example the separator blocks suffers from the same issue and we can't simply insert a BR node in there.

**Pull request closed without merging**
