### PR TITLE
Alternative approach to adding a close icon for navigation sidebar 

### PR DESCRIPTION
**Pull request by getdave**
## Description
Alternative approach to https://github.com/WordPress/gutenberg/pull/30964 in order to address https://github.com/WordPress/gutenberg/issues/29529.

This approach uses a _single_ `NavigationToggle` component. It has two states:

1. When the panel is _closed_ it is positioned absolutely **over the top** of the site icon and the "Close" icon is _hidden_.
2. When the panel is _open_ it is positioned over to the right hand side and the "Close" icon is _shown_.

The site icon (the `W` logo) is extracted to its own `NavigationIcon` component and now has **no interactivity**. It's purely a visual element. You now have to click the `X` icon to close the panel but that's far more intuitive and is an established pattern in the editor (eg: the `List View` sidebar has this).

This approach is better because 

1. There is now a single tab stop for toggling the panel (as opposed to x2 in the other PR).
2. The code duplication has been removed making for easier maintenance.
3. It is more intuitive and consistent UX to have the `X` icon as the way to toggle the panel.

See that PR for all details.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
Noting that we could also pursue @jameskoster's approach

> A more traditional hamburger icon which transforms into a close icon when clicked would be a less noisy solution. But then we'd have to think about how the site icon interacts, and the consequences of losing the (W) branding. I don't know if y'all think that is worth trying in a separate branch as a comparison?

In this approach, the `W` icon would simply transform into a `Close` icon when clicked. But we've have to be ok with losing the `W` when the panel is open.

**Comment by jasmussen** [comment]
Thanks so much for exploring these. Out of the two, I have a preference for the existing toggle, even if we add an extra close button affordance to it. Mostly because that lets focus on the W menu "stay in place" rather than shift around when opening closing. 

If we do go with this alternate approach, we need to consider sites that have a logo defined:

now

**Comment by getdave** [comment]
> Thanks so much for exploring these. 

You're welcome 👍 

> Out of the two, I have a preference for the existing toggle, even if we add an extra close button affordance to it. Mostly because that lets focus on the W menu "stay in place" rather than shift around when opening closing.

I understand this to mean you'd like to retain the toggle interaction in and around the site icon and avoid having a 2nd `X` off to the right? 

I see the logic because that would allow the interaction to remain "under" the cursor whether toggling open/closed.

In that case we're heading towards simply replacing the site icon with an `X` when the panel is open. 

Shall I do one final exploration of that route?

**Comment by getdave** [comment]
I'm closing this one based on 

https://github.com/WordPress/gutenberg/issues/29529#issuecomment-823987563 and https://github.com/WordPress/gutenberg/pull/30964#issuecomment-824033048

**Pull request closed without merging**
