### PR TITLE
[RNMobile] add RangeControl mobile implementation (slider)

### PR DESCRIPTION
**Pull request by jbinda**
## Description
Add RangeCell component wich is mobile implementation of RangeControl web component (according to #1300 in gutenberg-mobile)

[Related gutenberg-mobile PR #1342](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1364)

## How has this been tested?
- Add below range cell implementation inside `InspectorControls` in `edit.native.js` 
<details>
<summary>Usage of BottomSheet.RangeCell </summary>

```
<BottomSheet.RangeCell
icon={ 'admin-settings' }
label={ __( 'Slider' ) }
value={ sliderVal }
defaultValue={ 25 }
minimumValue={ 20 }
maximumValue={ 100 }
separatorType={ 'fullWidth' }
onChangeValue={ this.updateSlider }
/>
```
</details>

- add handler to change slider value
<details>
<summary>Handler to change slider value</summary>

```
updateSlider( newVal ) {
    this.props.setAttributes( { sliderVal: newVal } );
}
```
</details>

- reset `sliderVal` to `null` in `onClearSettings()` function

## Screenshots 
<image  src="https://user-images.githubusercontent.com/21242757/64769036-d6d39f00-d54a-11e9-8cb9-f027a165f02b.png" width="300" />

RangeCell temporally attached to Image block settings
<image  src="https://user-images.githubusercontent.com/21242757/64769277-4f3a6000-d54b-11e9-9b77-e4b521506194.gif" width="300" />

## Types of changes
Add new component (`BottomSheet.RangeCell`) under `BottomSheet` component which is replacement for `RangeControl` component on the web

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@jbinda Looking pretty solid, I've got a few notes that I'll drop here, but in the meantime would you mind also attaching some screenshots of Android to this ticket?

Feedback:

* In general, I think we might want to force this Range (slider) component to a second line on the table row. If the label is anything longer than ~7-10 characters, we're going to run into space issues (example mockup: https://cloudup.com/csjq5WFjBW4)

* Is there a way to match the native/vanilla iOS slider styles as [shown here](https://developer.apple.com/documentation/uikit/uislider) (example: https://cloudup.com/ccHls-K-t_Q)?

* Can we apply the styling I've [mocked up here](https://cloudup.com/cSCBuT64oSm) to the text input? In short, Android has a 1px border-bottom and iOS doesn't have a border (although we could display the same active border-bottom on focus)

That's all I've got for now, thanks for working on this – it'll be so great to have the component!

**Comment by iamthomasbishop** [comment]
An additional note regarding the Text Input styling mentioned above (**word of warning**: I'm not sure if I love this idea, but it's worth considering if we're using a purely native Slider component here.):

The [Slider component](https://developer.apple.com/design/human-interface-guidelines/ios/controls/sliders/) on iOS typically doesn't attach a text input, so we could also consider not displaying the Text Input currently attached to Sliders on iOS.

**Comment by jbinda** [comment]
@iamthomasbishop thanks for the review, appreciate it a lot !

According to your notes:

- I think we can quite easily force the sidebar to take 2 lines
- slider takes props that change the tint colour so I think we can set up it by default as you shown ( including left/right icon ? )
- ok I will change the textinput and paste the GIF how it looks like

**Comment by iamthomasbishop** [comment]
> I think we can quite easily force the sidebar to take 2 lines

Assuming you mean "easily force the **slider** to take 2 lines"? If so, sounds good 👍

> slider takes props that change the tint colour so I think we can set up it by default as you shown ( including left/right icon ? )

Awesome. The reason I asked if we can use a 100% native component is that if it's possible, we would inherit all of the baked-in variations for dark mode, etc. Can we get that for free? Or do we have to implement light/dark mode separately with custom tints?

It would certainly be nice to have the option to include icons, so that also sounds great.

> ok I will change the textinput and paste the GIF how it looks like

Sounds good! 👍

**Comment by jbinda** [comment]
Hi @iamthomasbishop  @mkevins 

I have update `RangeCell` because I need it to implement [this featue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1430). I have also fix issue spotted by @mkevins [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342#issuecomment-537799325)

Below I post GIFs with current behaviour:
<image src="https://user-images.githubusercontent.com/21242757/66748606-e155c100-ee87-11e9-8940-2d01ec91f244.gif" width="300" />

<image src="https://user-images.githubusercontent.com/21242757/66748607-e3b81b00-ee87-11e9-87c9-c5b7733a39c2.gif" width="300" />

According to design change @iamthomasbishop mentioned above we will cover it after implement column block.

**Comment by iamthomasbishop** [comment]
@jbinda The slider itself looks nice on both platforms, nice work! I have a few thoughts/questions regarding styling of the text inputs:

* **Text Alignment**: Is there a way we can center the text input label? ([example](https://user-images.githubusercontent.com/1200432/66759587-27019200-ee66-11e9-9f49-2d047a0ca8bb.png) from MD guidelines)

* **Android border style**: Can we use the underline style on Android, which displays only a border-bottom? ([example](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1568406561463%2Fassets%2F12CeqlOc7Jq30i39Ifjopf4dnCdqMi7np%2Fsliders-value-entry-v01.mp4))

* **Border color**: Can we use a dimmer `border-color` on both platforms for the un-focused state? Perhaps we can use the same color as the existing row separators. Let's also double-check in dark mode that we apply the same logic.

Here is a visual example of border style differences in Android/iOS (ignore the specific `border-color` in this example – use whatever the code provides us for separator color in RN):

image

Side question: I think I asked previously, which I think you mentioned that we **can** drop the slider component to a second line in the table row, but I want to confirm – can we decide that on a case-by-case basis, or do we have to do one or the other globally? For example, if we have a long row title ("Slider" label above) does it automatically bump the Slider to a second row, or do we have to decide on a case-by-case basis? If the latter, it might make sense to force a second line for all Slider components.

**Comment by pinarol** [comment]
@jbinda Could you open a separate issue for @iamthomasbishop 's [comments](https://github.com/WordPress/gutenberg/pull/17282#issuecomment-541754123)?

Let's just test the functionality in this PR and unblock the other PRs(Gallery, Column, Spacer) waiting for Slider, and then let's do another PR for design items. @iamthomasbishop we won't be shipping this before fixing the design.

@mkevins would you mind testing this once again in terms of functionality?

**Comment by jbinda** [comment]
@pinarol as you said I will open another issue to 
1. Change the style of `RangeCell`
2. Apply `RangeControl` layer to fit web markup ( the same was done for other `BottomSheet` controls)

@iamthomasbishop I did not forgot about the styling you mention but temporally defer it according to conversation with @pinarol on Slack. However already have something to present - but as @pinarol mention we can discuss it in separate issue to avoid blocking work on other blocks.

**Comment by mkevins** [comment]
Hi @pinarol :wave: 

> @mkevins would you mind testing this once again in terms of functionality?

Certainly :smiley: 

So far, I've been cherry-picking from this branch and testing with Gallery, and things seem to be working pretty well so far:



I'll do some more thorough testing, but it's good to see the progress here. The padding issue on Android seems to be resolved. Nice work @jbinda :+1:

**Comment by jbinda** [comment]
Thanks ! @lukewalczak also helps to make this work :)

Please let us know after you finish all tests

**Comment by pinarol** [comment]
@iamthomasbishop if you think we should be using stepper in Column then we should update this PR. Because both Column and Gallery is using RangeControl to adjust column count, in that case RangeControl should be rendering Stepper instead of a Slider. And this PR is basically for introducing RangeControl to mobile.

**Comment by pinarol** [comment]
ok I had a convo about @iamthomasbishop about RangeControl and we came to an agreement about how to move fwd about this.

1. Merge this RangeControl PR as is (rendering Slider)
2. Start implementing a StepperControl for small ranges which will render a Stepper
3. Add platform checks and use StepperControl where needed(on small ranges like number of columns on Column, Gallery)

However, we won't be blocking Gallery, Column blocks for 2nd item. We'll be iterating on those after completing StepperControl.

**Comment by mkevins** [comment]
I've tested everything listed in the description, as well as a few other scenarios:

* Typing a hyphen in the numerical input: the change is "rejected"
* Typing a space in the numerical input: the space is permitted in the string, as long as the string can be converted to a number via `Number` constructor
* Placing the caret at various positions in a number and moving the slider to change the number of digits: caret moves to with order of magnitude of the number (i.e. there is no index out of bounds error)

In all of these scenarios, the component works as expected :tada: 

One minor (not a blocker) issue I observed is that if I move the slider over a wide range of values, there appears to be some "jumpy" behavior:

**Comment by pinarol** [comment]
> there appears to be some "jumpy" behavior

Can we try to find out why this is happening? @lukewalczak @jbinda

**Comment by jbinda** [comment]
@mkevins @pinarol @lukewalczak 

I have fix that. Setting attribute in `onValueChange` handler was too much time consuming and it was the cause of jumpy behaviour. I switch logic and change external state only on `onSlideComplete` event so now it works fine

<image src="https://user-images.githubusercontent.com/21242757/66919986-b6ec3b00-f022-11e9-9eb5-6072e53d5c38.gif" width="300"/>

**Comment by mkevins** [comment]
Hi @jbinda :wave: 

I tested with your latest changes, and it's sliding very smoothly now :tada: Nice work!

**Review by mkevins — APPROVED** [review]
This looks good. Nice work @jbinda :+1: . As wrapping with `RangeControl` will be in another PR, LGTM!

**Comment by pinarol** [comment]
@jbinda @lukewalczak we can merge this, but please don't forget to open issues for [these items](https://github.com/WordPress/gutenberg/pull/17282#issuecomment-542122478) beforehand, thank you so much for all the effort!

**Pull request merged**
