### PR TITLE
Data views: Align 'Bulk edit' menu trigger with 'View options' menu trigger

### PR DESCRIPTION
**Pull request by jameskoster**
There's something uncanny about the 'View options' menu being triggered by an icon button while the 'Bulk edit' menu is triggered by a text button. The contrast in prominence between them is not altogether helpful.

Screenshot 2024-02-07 at 14 37 39

This PR seeks to align their prominence and the general UX by updating the bulk actions menu trigger to use an icon button:

Screenshot 2024-02-07 at 14 39 07

On the surface this seems a simple enough change, however there are a couple of challenges:

1. Coming up with an icon that _clearly_ represents 'bulk actions'.
2. Indicating the selection. The text button label adapts dynamically to read, for example; "Edit 20 items".

The icon is something we can explore in this PR. 

For indicating the selection the `Button` is populated by text: "Edit items: _X_", where 'Edit items' is visually hidden and _X_ = the selection count displayed as a small pill at the top-right corner of the button. A similar `label` is present and appears as a tooltip.

### To test
* Go to a dataview that supports bulk actions like Templates
* Play around with the menu

### Video demo

https://github.com/WordPress/gutenberg/assets/846565/7f9d3735-ad37-4a57-a7a4-30d6bb700688

cc @andrewhayward

### CODE REVIEW

**Comment by jasmussen** [comment]
This is a tricky one. I agree the footprint is better on this one, but there's something about that icon that isn't working too well. Not a 1:1 but here's what Dropbox does:

dropbox

There's a better balance of emphasis there. I wonder if there's some inspiration we can take.

**Comment by jameskoster** [comment]
Thanks for sharing.

Showing the selection inline works well, and the increased footprint is probably warranted _after_ a selection is made. I'll give that a try. 

Less sure about the checkbox icon. Normally checkbox detached from a table row like that is a 'select all' shortcut (which we already have). Our affordance is a little different (a menu with options relation both to selection and action). Perhaps a checkbox with a `down` chevron next to it could work... it's a bit tricky to capture _selection_ and _action_ in one icon. 

Another option would be to separate the menus, one for selection, one for bulk actions:

Screenshot 2024-02-08 at 10 33 28

The order is kind of backwards, but perhaps it could work? cc @andrewhayward

**Comment by andrewhayward** [comment]
> This PR seeks to align their prominence and the general UX by updating the bulk actions menu trigger to use an icon button...

I do like the intent, but as you mention yourself, _coming up with an icon that clearly represents 'bulk actions'_ is always going to be tricky! Once the purpose of the control is clear though, the numerical badge works well.

> Less sure about the checkbox icon. Normally checkbox detached from a table row like that is a 'select all' shortcut (which we already have). Our affordance is a little different (a menu with options relation both to selection and action).

As long as the icon only visually resembles a checkbox, and doesn't try to behave as one, we'd probably get away with it. It might be initially confusing to have something that looks like a checkbox not behave like one, but given that it would open a menu with relevant and appropriate actions, it could be worth trying.

Only tangentially related, but it might be worth exploring separate _"Select all"_ and _"Select visible/page/whatever"_ options to allow for acting on an entire set of filtered items, even if you can't see them all at once. Similar to how GMail and others prompt for things like _"All `x` conversations on this page are selected. Select all `y` conversations in &laquo;view&raquo;."_

> Another option would be to separate the menus, one for selection, one for bulk actions

The separation feels kind of... disconnected! I'm not sure what reason you'd have for selecting multiple items other than to take some sort of bulk action. At which point, having the two parts of that workflow divided and on opposite sides of the workspace just seems cumbersome.

Equally, how would it work in non-table layouts? Where does the selection control go in grid layouts, for example? Not saying they should necessarily therefore be the same control, just that it's not adding up in my head!

**Comment by jasmussen** [comment]
> I do like the intent

To be clear, the intent is less about moving to an icon, it's to manage the prominence. For a feature that is critical _when you need it_, but arguably not always, it would be good if the button is findable, bit _gains prominence_ when you start using it. Consider: there are checkboxes to select individual posts in a list, and there's even a "select all" as the table header. Clicking any of those checkboxes starts you on the bulk editing journey, and _that's_ when the bulk button could gain prominence, for example by literally showing the text label, "3 selected". 

I understand the button needs to be permanently there so that focus has somewhere to land, for example, if you choose deselect all from that menu. But in its resting state when you are not selecting posts, it only has a single action, "Select all":

Screenshot 2024-02-09 at 09 38 38

And since that select all action is also present by clicking the checkbox in the table heading, the bulk action button in its resting state becomes secondary.

Screenshot 2024-02-09 at 09 40 10

That's why it is worth matching its footprint to the flow.

**Comment by jameskoster** [comment]
@andrewhayward good points, keeping the actions together in the same menu seems reasonable, and doesn't preclude adding 'select' actions to the main checkbox at some point in the future.

I'm still not convinced about the checkbox-as-an-icon though. You mention it shouldn't behave like one, but in practise I suspect it would be a little strange to an 'unselected' icon when a selection has been made:

Screenshot 2024-02-12 at 17 28 02

Outside of the conventional placement it also doesn't resemble a checkbox so much. We'd probably need to add the checkmark, but that doesn't work so well either...

Screenshot 2024-02-12 at 17 32 05

**Comment by andrewhayward** [comment]
> You mention it shouldn't behave like one, but in practise I suspect it would be a little strange to an 'unselected' icon when a selection has been made

Sorry, I wasn't clear. I meant that we shouldn't try to combine an actual checkbox with a dropdown menu, as the functionality would just get super confusing. Updating the visuals to match the state of the selection (unchecked, checked, indeterminate) would be less of an issue.

**Comment by jameskoster** [comment]
Thanks for clarifying. But that just brings me back to [this comment](https://github.com/WordPress/gutenberg/pull/58783#issuecomment-1933791839).

Having the main bulk select checkbox (the one in the table) visually match the bulk actions button is going to lead to confusion around these UI that have the same appearance but behave differently. A checkbox arguably over-emphasises selection as well.

How about if the icon changed based on whether a selection has been made? E.g. no selection = empty checkbox, selection = cog (or ideally some new icon that communicates 'apply bulk actions').

bulk

**Comment by jasmussen** [comment]
I think it's important we unstick this. To echo the previous feedback, since text is added to the button as soon as you bulk select, a great deal of prominence is _contextually added_ as soon as you start the user journey towards bulk editing. Keeping it a cog implies the advanced nature in its non-bulk state, and manages the prominence at the same time. We can explore other icons too, Google Keep has this icon for it:
Screenshot 2024-02-18 at 09 29 26

**Comment by andrewhayward** [comment]
> How about if the icon changed based on whether a selection has been made? E.g. no selection = empty checkbox, selection = cog (or ideally some new icon that communicates 'apply bulk actions').

I wonder if two quite distinct icons would get confusing. Perhaps the same icon, with a "deactivated" variant, might be better? _(Not these, but I didn't want to spend more than a couple of minutes trawling for examples!)_

<p align="center">
  Stylised cog
  Stylised cog with a line through
</p>

**Comment by jameskoster** [comment]
Just to see how it feels I pushed an update that displays the selection more prominently, and switches icon upon selection. 

@andrewhayward I tried an icon where a cog sits inside a checkbox, but it's tricky to get right at such a small size. So I'm using the regular cog for now.

https://github.com/WordPress/gutenberg/assets/846565/21c03a4d-9b86-4c4e-bbad-5ae70094a7a9

We can continue exploring icons if y'all feel this is the right direction.

**Comment by andrewhayward** [comment]
> I tried an icon where a cog sits inside a checkbox, but it's tricky to get right at such a small size. So I'm using the regular cog for now.

Kind of works if you impose the cog, rather than try to squeeze it inside...

<p align="center">
  An action bar, with a square box icon.
  An action bar, with the text '2 items selected' next to a settings icon represented by a square box with a small cog overlapping the bottom right corner.
</p>

I'm just not sure as the empty box actually affords much, given the lack of context. Maybe the default state could have some other sort of imposed action?

<p align="center">
  An action bar, illustrating a settings icon represented by a square box with a small encircled plus overlapping the bottom right corner.
  An action bar, with the text '2 items selected' next to a settings icon represented by a square box with a small cog overlapping the bottom right corner.
</p>

<p align="center">
  An action bar, illustrating a settings icon represented by a square box with a small plus overlapping the bottom right corner.
  An action bar, with the text '2 items selected' next to a settings icon represented by a square box with a small cog overlapping the bottom right corner.
</p>

Honestly though, at that point, it makes me wonder if we even need two different icons! If we can get the right one, it might not need to change, particularly if we're adding additional context.

<p align="center">
  An action bar, illustrating a settings icon represented by a square box with a small cog overlapping the bottom right corner.
  An action bar, with the text '2 items selected' next to a settings icon represented by a square box with a small cog overlapping the bottom right corner.
</p>

Do we have the option of knocking the imposed bit out a bit? Dunno, that kind of looks like it's disabled, but maybe that's the point?

<p align="center">
  An action bar, illustrating a settings icon represented by a square box with a small pale cog overlapping the bottom right corner.
  An action bar, with the text '2 items selected' next to a settings icon represented by a square box with a small cog overlapping the bottom right corner.
</p>

**Comment by jameskoster** [comment]
> I'm just not sure as the empty box actually affords much

I agree, and I would say that's still the case with the imposed icon. In fact it then probably looks _less_ like a checkbox.

Knocking out is possible, but probably not a precedent we want to set without 100% confidence. 

Using the exact same icon in both contexts would be best, but I still don't see an appropriate icon. Perhaps we could use the same _shape_ with different fill rules based on selection?

bulk

This looks less like a regular checkbox so reduces confusion with the main 'select all' affordance. But it still resembles bulk selection, and the change in state hopefully indicates that different actions are available. 🤔

**Comment by andrewhayward** [comment]
> This looks less like a regular checkbox so reduces confusion with the main 'select all' affordance. But it still resembles bulk selection, and the change in state hopefully indicates that different actions are available. 🤔

My concern is that we stray so far away from common iconography that that it's no longer visually discoverable as a button, and just appears as some sort of status indicator.

A table with rows of page data.

A table with rows of page data, one selected with a checkbox. A label above reads "1 item selected".

I ran a super scientific user study _(cohort size: 1)_, and the audience had no idea what the initial state meant, felt a bit more oriented with the change, but didn't locate it as an actionable button in either. All of the respondents reported that they liked the way GMail does it, with the menu close to the context.

A dropdown menu, showing various selection options.

That's not quite the same, as it's only selection options, rather than selection actions, but something to think about. When items are selected in GMail, the actions appear next to the selection control, and we don't really have that option!

**Comment by jameskoster** [comment]
> and we don't really have that option

Perhaps we could?

bulk

Though I'm not sure this is still in the spirit of reducing the visual prominence :D

**Comment by jameskoster** [comment]
Figured I'd give the split menus approach a go. Obviously lots of rough edges to polish, but wanted to get y'alls thoughts on the approach:


https://github.com/WordPress/gutenberg/assets/846565/de03a66e-eb38-4c84-90ef-263ac70ed8ab

**Comment by jasmussen** [comment]
Thanks for keeping at it. With this split menu, would the "bulk select" portion be any different than clicking the table-header checkbox all the way to the left?

**Comment by jameskoster** [comment]
Behaviourally it's the same, though in the future the menu could include an affordance to select **all** rather than just the current page. Beyond that it has two purposes:

1. Enables quick bulk selection on layouts like Grid (where there's no checkbox _column_).
2. Groups bulk selection and actions together in the DOM which is most useful for users of assistive technology.

**Comment by andrewhayward** [comment]
It's perhaps worth giving that dropdown a little more affordance, with a chevron or similar. Cognitively I can't see anything other than a checkbox, and it's surprising when it doesn't behave like one.

Data views table header, showing a title and various controls.

We should probably make sure the visual state mirrors that of the table checkbox too.

Data views table header, showing a title and various controls, including a mixed checkbox labelled "1 selected".

The original intent of having the actions menu available all the time was to give an idea of which actions were available, even if they couldn't be used. If we're going to disable that menu, does it still need to be there at all when nothing's selected? It might, if we need it to be focusable after an action, but then it probably should be focusable all the time (even if disabled).

Data views table header, showing a title and various controls, but not including an actions menu button.

Which, while I'm hesitant to suggest adding more unlabelled buttons to the UI, makes me wonder if, when we've got the screen real-estate, we don't even bother with the second menu and just put the actions right there...

Data views table header, showing a title and various controls, including separate buttons for various bulk actions.

Or do we just go full-circle and put everything in the same menu?!

Dropdown menu, showing options for "Select all – 2", "Deselect", "Move to trash – 1", "Restore" (disabled) and "Permanently delete" (disabled).

**Comment by jasmussen** [comment]
This is an important one to get right, so let's not rush this. It does increasingly feel like, if the checkbox metaphor is to be used, then the checkbox in the top left column table head that _already_ selects all, becomes a competitor. To that end, it might be good to lean into something that doesn't use that metaphor after all. That said, I would avoid a chevron to indicate the dropdown aspect — these icon buttons often open dropdowns, and if we add the chevron to some but not all, then it'll be a bit messy.

**Comment by jameskoster** [comment]
We haven't found a path forward here so I'm going to close this for now. I'm optimistic that the ongoing Inspector work could unlock things, specifically once it is able to entertain multi-selection, and can be invoked from data views. A rough visual:


List

**Pull request closed without merging**
