### PR TITLE
Deactivate plugin if WordPress 5.0 Beta detected

### PR DESCRIPTION
**Pull request by mcsf**
## Description

This PR is currently the most basic working implementation possible to illustrate the concept.

- Looks for tentative constant `GUTENBERG_STABLE_LOADED`, assumed to be defined in 5.0 branch.
- If constant found, deactivates plugin and shows admin notice explaining deactivation.

### Rationale

WordPress 5.0 Beta 1 is fast approaching. Gutenberg 4.1 RC is expected shortly before that, and the plugin should prepare for the beta by — for now — simply deactivating itself in order to avoid fatal conflicts between core and plugin.

Note that the plan, once 5.0 is released, is for the plugin to fully support 5.0+. When that time comes, the Gutenberg plugin will be a channel for incremental development of Gutenberg, in particular for so-called [Phase 2](https://make.wordpress.org/core/2018/10/05/gutenberg-phase-2-leads/) of the project.

### Questions

- [ ] I haven't fully weighed the merits of a constant vs. checking for `function_exists( 'register_block_type' )`. My concern w.r.t the latter is the timing of function definition in core vs. plugins, and the likelihood of certain setups out there breaking our assumptions. In contrast, the primacy of `wp-config.php` is much more likely to be honored.

## How has this been tested?

In your `wp-config.php`, add

```php
define( 'GUTENBERG_STABLE_LOADED', true );
```

make sure to define this constant _before_ `wp-config.php` requires any other file.

## Screenshots

gutenberg-wordpress-conflict-notice

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@mcsf How will those working on Gutenberg _and_ 5.0 continue to do so? If this is documented elsewhere, feel free to point me to it.

**Comment by mcsf** [comment]
@danielbachhuber: I'm not sure it's documented. My immediate concern is not surprising users running the plugin who may choose to try the beta. Realistically, I could see 4.1 being kept incompatible<sup>1</sup> with the 5.0 branch, and compatibility being resumed _n_ plugin releases later, once the different focuses (Beta, Upgrading, Packages) can align themselves into refactoring<sup>2</sup> the plugin so as to be able to "enhance" core Gutenberg.

<sup>1</sup> The main purpose of 4.1 is serving as UI freeze for Beta 1, so I don't think we're "missing out" by making them incompatible.
<sup>2</sup> Any upcoming plugin version that aims to be 5.0-ready will most likely have to _require_ 5.0 or higher, so it's going to be a clear break in the plugin's history from pre- and post-merge.

**Comment by danielbachhuber** [comment]
> Realistically, I could see 4.1 being kept incompatible1 with the 5.0 branch, and compatibility being resumed _n_ plugin releases later, once the different focuses (Beta, Upgrading, Packages) can align themselves into refactoring2 the plugin so as to be able to "enhance" core Gutenberg.

Hm, is this documented somewhere? My assumption was that:

1. Gutenberg the plugin could always be run alongside the WordPress 5.0 branch.
2. If installed, Gutenberg the plugin would override Gutenberg in WordPress 5.0.

Is this assumption incorrect?

**Comment by youknowriad** [comment]
@danielbachhuber These assumption are correct except for the "always" mainly because we have different moving parts at the moment.

I see this PR as a temporary solution to avoid broken websites for the moment. We need to follow-up to this PR with a PR overriding the scripts registered by WP 5.0 if existing and removing this auto-disable mechanism from the plugin.

But regarding the current PR, I think I'd prefer if it's inverted. By this I mean:

 - Move the code looking for a constant and disabling the plugin into the 5.0 Branch instead of this PR.
 - Rename the constant something like `GUTENBERG_PLUGIN_5_0_READY`
 - Once the plugin is compatible with 5.0, define the constant in the plugin (could be in 4.1 or 4.2)

The main advantage is that this would disable all versions of Gutenberg prior to the version compatible with 5.0.

**Comment by mcsf** [comment]
> These assumption are correct except for the "always" mainly because we have different moving parts at the moment.
> I see this PR as a temporary solution to avoid broken websites for the moment. We need to follow-up to this PR with a PR overriding the scripts registered by WP 5.0 if existing and removing this auto-disable mechanism from the plugin.

Riad put it more clearly than I. :) 

> But regarding the current PR, I think I'd prefer if it's inverted. [.…]

Yeah, I agree with this. I can go for that.

**Comment by mtias** [comment]
Let's also plan ahead around how we'd handle enabling "Phase 2" alongside ongoing 5.* work.

**Comment by danielbachhuber** [comment]
> I see this PR as a temporary solution to avoid broken websites for the moment. We need to follow-up to this PR with a PR overriding the scripts registered by WP 5.0 if existing and removing this auto-disable mechanism from the plugin.

What's the level of effort for making the Gutenberg plugin compatible with both WP 4.9 and 5.0, without the deactivation step? If it's not too much additional effort, is it possible to do this instead of deactivating?

**Comment by mcsf** [comment]
Attaching [Slack convo from #core-editor](https://wordpress.slack.com/archives/C02QB2JS7/p1539693405000200). Takeaway:

> So thinking a bit more broadly:
> - 5.0 trunk should probably be the one handling old versions of gutenberg as we cannot retrofit that.
> - 4.1 should make itself compatible with 5.0.

**Comment by danielbachhuber** [comment]
Chatted with @mcsf in Slack today to sort this out. The deactivation logic will happen in core, similar to how MP6 was deactivated.

**Pull request closed without merging**
