### PR TITLE
Docs: Add example for registerBlockType hook

### PR DESCRIPTION
**Pull request by mcsf**
## Description

Add the example provided in https://github.com/WordPress/gutenberg/pull/5651#issuecomment-403438653 to the Extensibility documentation.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
Nice addition 👍 

We should perform general cleanup of this documentation, it can be another PR.

**Comment by mcsf** [comment]
D'oh, you're totally right about ES5/globals. Pushed anew.

**Review by gziolo — APPROVED** [review]
Thanks for pushing new commit with ES5 example 👍

**Comment by mcsf** [comment]
Thanks for reviewing!

**Pull request merged**
