### PR TITLE
Use `classnames` consistently for importing the classnames module

### LINKED ISSUE #613: Standardize usage of `classnames` vs `classNames`
```js
// This appears 2 times in our codebase
import classNames from 'classnames';

// This appears 5 times in our codebase
import classnames from 'classnames';
```

Let's standardize on this one way or the other.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #613 

It was suggested to write a custom eslint rule for this. I'm not sure it's worth it but it could be done separately anyway.

### CODE REVIEW

**Comment by iseulde** [comment]
Just a genuine question: Why `classnames` in favour of `classNames`?

Docs: https://www.npmjs.com/package/classnames

**Comment by iseulde** [comment]
Sorry, should have read the linked ticket.

**Comment by youknowriad** [comment]
No problem, worth repeating here https://github.com/WordPress/gutenberg/issues/613#issuecomment-299108630

**Review by swissspidy — APPROVED** [review]

**Comment by nylen** [comment]
The reason I suggested a lint rule was that this inconsistency could easily come back in the future.

**Pull request merged**
