### PR TITLE
Fix Pullquote text color after unsetting main color 

### LINKED ISSUE #24440: Pullquote: when we change the main colour then the text of Pullquote is not visible
**Describe the bug**
in Pullquote when we select the solid colour style and we set the main colour as black then text colour automatically set to cream colour and we unset the main colour then the text colour is not getting changed to default colour, because of that we are not able to view the text of Pullquote.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to 'Editor'
2. Add new page
3. Click on 'add block'
4. Select the block 'Pullquote'
5. Select the Style 'Solid color'
6 Set the main colour 'black'
7. Unset the main colour
8. See error

**Expected behaviour**
when we unset the main colour then the text colour should be the default colour so we can view the text of Pullquote.

**Screenshots**
https://prnt.sc/tvn4la
https://prnt.sc/tvn53e

**Video**
for more detail please view the attached video
https://www.loom.com/share/165a6ddfde9b4322be055068a57d6549

**Editor version (please complete the following information):**
- WordPress version: 5.5-beta1
- default

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 84.0.4147.105 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/24440

Currently in a `Solid color` `Pullquote` if you change the main color and a text color is automatically computed ( for example main color black ), and then you unset the main color, the text color remains set and that can lead to `invisible` text (same color with background).

In this PR if we unset the main color and the text color was previously automatically computed, we unset the text color as well.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for the PR!

I have a question regarding the best practice here, because I see a discrepancy in how 2020 and 2019 themes do this. 2020:



Note how selecting the black background color _also_ sets the cream foreground color, resulting in the bug as reported.

2019:



Note how selecting the background color _does not_ set the foreground color, meaning there is no issue.

I tend to think that when you choose _one_ color, that one action should not also affect adjacent controls. Maybe I wanted black text on a black background (homemade spoiler block?) — and we'd also have a color contrast warning indicating that what you're doing is a bad idea. However by making a choice for the user, it feels both unnecessarily prescriptive, but also prone to adding a lot of complexity where none should be needed.

The 2019 approach seems much better: when a blue background is set, the _theme_ defines the foreground color to be white. But the color remains unset in the editor, and a user can then explicitly choose a different than white foreground color if that's what they want.

The 2020 approach, to set an inline color style when the pullquote has a black background, feels like the bug to fix at the theme level, and if it's using block editor APIs, in the block editor as well.

What do you think, @kjellr?

**Comment by ntsekouras** [comment]
Hey @jasmussen ! Thanks for looking at this!

The change of text color has to do with themes' `colors`. That's why you're not seeing it in the other theme. It happens to have more `compatible` colors. There is currently logic in there that if the user have `NOT` selected text color and changes background, tries to auto compute a better color (`colorUtils.getMostReadableColor( colorValue )`.

If the user has chosen a text color it remains as is. My change now is specific to the case that we (GB) had previously computed a text color and now we unset it. So it's like taking back our recommendation/change.

**Comment by ntsekouras** [comment]
> Although I noticed in your gif that color does change in white background. I'll check it now.

Actually the text color changes to black when selecting white background, but it isn't selected. If you unset the white background you'll see that the color remains to black.

**Comment by jasmussen** [comment]
Thank you for the context.

> There is currently logic in there that if the user have NOT selected text color and changes background, tries to auto compute a better color (colorUtils.getMostReadableColor( colorValue ).

I guess what I'm suggesting is that this may be undesirable behavior (prescriptive, unpredictable), and that better default theme behaviors (the theme providing white text if the background is set to blue) feels like the better overall practice, when combined with the contrast checker.

**Comment by kjellr** [comment]
> I guess what I'm suggesting is that this may be undesirable behavior (prescriptive, unpredictable), and that better default theme behaviors (the theme providing white text if the background is set to blue) feels like the better overall practice, when combined with the contrast checker.

I agree for now — if a user makes one color choice, and then clears it, they shouldn't have to clear a second setting. 

That said, the practice of themes changing the text color css in circumstances like this has always felt a little bit of a hack though. I think there's a ticket somewhere for handling this via `theme.json`, and I hope that helps enforce a more shared process around this.

**Comment by jasmussen** [comment]
Thanks for looking, good thoughts. I think I'll dare a ping to @nosolosw to see if he has any thoughts here.

**Review by oandregal — APPROVED** [review]
:wave: I think this can go in, the code fixes the issue. :ship: 

There are a few related layers to this that I'd like to comment on! Let me unbundle them:

1. This behavior is exclusive of the pullquote block and is the same in every theme => we need to fix it, and this PR does :heavy_check_mark:

2. The pullquote doesn't use the new implicit style attributes => we need to migrate it, see https://github.com/WordPress/gutenberg/issues/22700 @ntsekouras is this something you're interested in helping with?

3. Do we want this behavior (changing background also changes text)?

If we look at the different approaches that people have tried (pullquote code, but also in theme territory) this looks like something people want. There's this issue to look at this from the context of theme.json https://github.com/WordPress/gutenberg/issues/24166 Perhaps a good first step and a follow-up to this PR would be to look into migrating the pullquote block to the implicit style attribute system.

I do have questions about the expectations about this, though: is the existing pullquote a good enough approach (selecting a text color whose lightness is opposite from the background's)? or should be the theme responsibility to provide some kind of color pairing, so to speak?

**Comment by ntsekouras** [comment]
Thanks for looking @nosolosw! 

> The pullquote doesn't use the new implicit style attributes => we need to migrate it, see #22700 @ntsekouras is this something you're interested in helping with?

Yes for sure :) !

> I do have questions about the expectations about this, though: is the existing pullquote a good enough approach (selecting a text color whose lightness is opposite from the background's)? or should be the theme responsibility to provide some kind of color pairing, so to speak?

Great questions! Maybe both are needed and color pairing/grouping ( not necessarily 1:1 )  by themes might be a nice option.
Another approach of course is just showing warning about this and do changes.

**Pull request merged**
