### PR TITLE
ButtonBlock: add color options in the inspector.

### PR DESCRIPTION
**Pull request by mtias**
button-color

(Also fixes some front end display issues and theme conflicts.)

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I like it. 

Should we add a way to enter an alternative hex value?

**Comment by mtias** [comment]
Probably, and @jasmussen wanted to provide a way for the theme to specify preferred colors.

**Comment by mtias** [comment]
Added Hex input, will merge as a first pass unless other objections.

**Review by aduth — COMMENTED** [review]
Should we make an effort to integrate the existing color pickers used elsewhere, such as the customizer, instead of introducing a new one?

picker

Maybe naming the component `ColorPicker` (`ColourPicker`) to give us the option to more easily switch it out?

**Comment by iseulde** [comment]
Related: #1955.

Shouldn't this be defined by the theme from the beginning? Or some variables that the theme can adjust?

**Comment by iseulde** [comment]
For the reason above, I would disagree with using the current colour picker.

**Comment by mtias** [comment]
> Should we make an effort to integrate the existing color pickers used elsewhere, such as the customizer, instead of introducing a new one?

It pains me to see that one around (I say that having helped build it). ;) Consider this more of a playing field for adding color interactions without a full color picker yet. I know Mel has been thinking about pickers for a while for the customization focus.

> Shouldn't this be defined by the theme from the beginning? Or some variables that the theme can adjust?

Sure, but we don't have a system yet for themes to declare information for gutenberg. This is in part to accelerate that happening, as we need it for various things. :)

**Comment by jasmussen** [comment]
I think Matías says something important. We've spent so much time building the key ingredients of Gutenberg, reimplementing existing features. We've spent less time on more exciting stuff, showcasing the full potential of the blocks. Even if this is not fully baked (I agree generally with the feedback), I think it's worth shipping so long as we can remember to ticket further improvements so they don't fall off the map. 

With regards to the specific feedback, I see two components rather than one. I see a _Color Swatches_ component, which would be nice to integrate with a theme array of colors, perhaps with other sources like ColourLovers or something. Pluggable in any case. And I see a _Color Picker_ component. The latter could, for example, pop up as soon as you set focus on the HEX code input field, or if you click a swatch. So the color picker could be more of a black box, and work as a subset of the swatch, and in places where it's good alone.

**Comment by mtias** [comment]
Going to merge and we can see how things turn out. Let's consider that the blocks we are producing now don't have to be part of core when merge time comes, and we'll probably do a review of which make sense and which don't.

**Comment by cedon** [comment]
One thing I've run across in playing with this color picker thing is there is no option to remove the color and go back to whatever the enqueued CSS files would produce.

This could be done obviously in the text editor but the problem there is that it first assumes the end-user will know to look there and know what to change and, even if they did, the block becomes frozen and uneditable with this message...

image

As a result, I have one of two options - to either delete the block and recreate it from scratch or I have to surrender my ability to edit the block visually.

My suggestion would be to add a link next to ***Text Color*** and ***Background Color*** that simply says **Remove Color** that will remove the `color:#xxxxxx` and `background-color:#xxxxxx` from the `style` attribute of the `<div>` element. Something along the lines of this:

image

It would also need to check and see if removing the style would result in an empty style attribute and just remove it completely.

**Pull request merged**
