### PR TITLE
[Enhancement] Allow transformation of image block to file block and vice-versa

### PR DESCRIPTION
**Pull request by nfmohit**
## Description
This PR addresses #7774 which requests the inclusion of the transformation feature of the image block to the file block and vice-versa.

## How has this been tested?
This has been tested by making sure the image to file transformation and vice-versa options show up in the respective blocks and the transformation works as expected, including file URLs and caption.

This was tested in WP 4.9.7, Gutenberg 3.2.0, Apache server with PHP 7.2.0 and MySQL 5.6.34. According to initial tests, the code doesn’t seem to affect any other areas.

## Screenshots 
pull-7774-min

## Types of changes
This PR adapts the block transformation code regarding audio and video blocks inside the file block and copies over the correct attributes in the transformation from the image block. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by talldan** [comment]
Thanks for working on this @nfmohit-wpmudev.

I've actually just merged an improvement for file block transforms to audio and video in #7737.

You can now use an `isMatch` function to check that the type of file uploaded to the file block is an image. Here's an example for the audio block:
https://github.com/WordPress/gutenberg/blob/master/core-blocks/file/index.js#L121

Would you be able to add an `isMatch` function for your image transform? It should be very similar to the example in the link above.

**Comment by nfmohit-wpmudev** [comment]
Hey @talldan!

`isMatch` looks so cool! I'm sorry about the delay, was having some issues with my dev setup. Pushed a new commit which adds isMatch to my image transform.

Thank you for the review! ❤️

**Review by talldan — APPROVED** [review]
Thanks for making that change, this looks good to go :)

**Comment by mtias** [comment]
Thanks for the contribution!

**Pull request merged**
