### PR TITLE
Mobile - Fix line-height issue on Android

### LINKED ISSUE #37168: Wrapping Heading block text overlaps previous lines for block-based themes
## Description

When adding a Heading block in the native mobile editor, the line height is incorrect and results in overlapping lines of text. It would appear an incorrect line height is set for the Heading block. 

**This issue only occurs in [development environments](https://github.com/WordPress/gutenberg/blob/88cb6a632b8d4a1505a25c63637358f6de4a7916/packages/rich-text/src/component/index.native.js#L900-L902) at the time of writing.** This issue occurs in the latest v1.67.0 release and first occurred in v1.64.0. It only occurs on Android, not iOS. It is likely related to https://github.com/WordPress/gutenberg/pull/35314. 

## Step-by-step reproduction instructions
1. Set the current theme to _Geologist_. 
2. Add a Heading block to the editor. 
3. Type enough words to wrap the text to a second line. 

## Expected behaviour
The wrapped second line of text does overlaps the first line of text. 

## Actual behaviour
The wrapped second line of text does _not_ overlap the first line of text. 

## Screenshots or screen recording (optional)

Too small of line hight for the Heading block causes wrapped text to overlap previous lines of text on Android

## WordPress information
- WordPress version: WordPress.com
- Gutenberg version: v12.0.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? No, Geologist

## Device information
- Device: Samsung Galaxy S20
- Operating system: Android 11
- WordPress app version: Gutenberg Mobile v1.67.0

### PR DESCRIPTION
**Pull request by geriux**
- Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4398

Fixes https://github.com/WordPress/gutenberg/issues/37168

## Description
This PR fixes an issue where the line-height value wouldn't be set after a font-size value was changed. Now it'll store the current line-height value and it'll be refreshed after any font size change.

**Note**: This feature is still under the `__DEV__` flag only available running metro.

## How has this been tested?

**Precondition**: Have a block-based theme activated.

- Open the WordPress Android app with metro running and setting the `localGutenbergMobilePath` path.
- Add a `Heading` block
- Type some text, with enough characters to fill in at least two lines
- **Expect** the line height to be shown correctly

## Screenshots 
Before | After
-|-
<kbd></kbd> | <kbd></kbd>

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
👋 @geriux ! Antonis is AFK until a few more days so I thought of giving this a look from my side, hope that's OK.

I'm wondering, wdyt about perhaps using [View.getLineSpacingExtra()](https://developer.android.com/reference/android/widget/TextView#getLineSpacingExtra()) or [View.getLineSpacingMultiplier()](https://developer.android.com/reference/android/widget/TextView#getLineSpacingMultiplier()) (and [View.getTextSize()](https://developer.android.com/reference/android/widget/TextView#getTextSize())) to work back from [the setLineSpacing calculations](https://github.com/WordPress/gutenberg/blob/fba492d66369c9d2f7e4fac1c8440dc27946bc95/packages/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java#L301) to recover the current line height used, instead of maintaining a member variable for it? Not a big problem using a member variable, just wondering if we'd prefer to not have to maintain one (and need to make sure it is kept n sync in all the proper places)?

**Comment by geriux** [comment]
> I thought of giving this a look from my side, hope that's OK.

Of course! Any feedback is more than welcome 🙇 

When I started debugging this issue I tried getting the current values with those methods but I couldn't get the exact initial line-height value, I'll try those again to see what results I get 👍

**Comment by hypest** [comment]
> When I started debugging this issue I tried getting the current values with those methods but I couldn't get the exact initial line-height value, I'll try those again to see what results I get 👍

Oh, I see. I didn't see a mention in the PR description so wasn't sure if you tried. FWIW, I haven't tried it myself so, your testing is already more complete apparently 😃

**Review by antonis — APPROVED** [review]
Thank you for wrangling this @geriux 🙇‍♂️ 
I tested the implementation on a Pixel 5 (Android 12) running metro and setting the `localGutenbergMobilePath` path with the head of `WordPress-Android` `develop` and everything works as expected. The code changes also look consistent to me 🎉

**Comment by geriux** [comment]
> I'm wondering, wdyt about perhaps using [View.getLineSpacingExtra()](https://developer.android.com/reference/android/widget/TextView#getLineSpacingExtra()) or [View.getLineSpacingMultiplier()](https://developer.android.com/reference/android/widget/TextView#getLineSpacingMultiplier()) (and [View.getTextSize()](https://developer.android.com/reference/android/widget/TextView#getTextSize())) to work back from [the setLineSpacing calculations](https://github.com/WordPress/gutenberg/blob/fba492d66369c9d2f7e4fac1c8440dc27946bc95/packages/react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecManager.java#L301) to recover the current line height used, instead of maintaining a member variable for it? Not a big problem using a member variable, just wondering if we'd prefer to not have to maintain one (and need to make sure it is kept n sync in all the proper places)?

While checking this I also remembered why I ended up with this approach, the line-height needs to be refreshed after a font size change has happened and only when there's a current line-height set. I tried to see if there's a way to get the react-native props that were set but I couldn't so I used the variable instead. I'll merge this change for now, thanks for the feedback and review! 🙇

**Pull request merged**
