### PR TITLE
Navigation: Enable all non-interactive formats

### LINKED ISSUE #67559: Navigation block: Added a hook to add allowFormat
## What problem does this address?

Hello👋

I would like a hook for the navigation block allowedFormats.

Adding a hook here makes it easier to customize from plugins.

For example, adding inline icon markup.

In the classic theme, you could add HTML tags to the menu label.

(Although this may not have been very good security practice.)

`<span class="dashicons dashicons-admin-home"></span>WordPress`

### This is how it looks in Twenty Twenty-One

Image

Image

### Twenty Twenty-Five example

In block themes, you can only add formats allowed by allowedFormats.

Image

Adding a hook to allowedFormats will allow customization from plugins, allowing for a variety of design expressions.

Thank you for your consideration.

## What is your proposed solution?

Add a hook to add `allowedFormats`.

https://github.com/WordPress/gutenberg/blob/968131a2f6c5256e237d513ff919ba47944a6d9a/packages/block-library/src/navigation-link/edit.js#L529-L534

https://github.com/WordPress/gutenberg/blob/82d7ad7b27d891e9e31c4a1dfd9802e882edc0d3/packages/block-library/src/navigation-submenu/edit.js#L576-L581

label

[Block] Navigation

[Block] Navigation Link

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Closes #67559.

PR removes hardcoded allowlist for RichText formats in the Navigation link and submenu blocks. Now, all non-interactive formats are allowed within these blocks.

This matches behavior of Button block

## Why?
Allows consumers to register custom formats that can be used with navigation blocks.

## Testing Instructions
1. Open a post or page.
2. Insert a navigation block.
3. Confirm that all non-interactive formats are visible for the navigation link and submenu.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 
CleanShot 2024-12-04 at 19 23 40

### CODE REVIEW

**Comment by carolinan** [comment]
Wait does this mean this has been fixed then? https://github.com/WordPress/gutenberg/issues/57788

**Comment by Mamaduka** [comment]
@carolinan, not sure. I think you can add HTML via RichText, but the label field in document settings removes HTML.

**Review by getdave — COMMENTED** [review]
To me this seems reasonable but I can't help thinking there must have been a _reason_ these were limited.

I've pinged @talldan and @draganescu as other folks who have a long term experience working on the block for a confidence check.

**Comment by Mamaduka** [comment]
Here's the original issue/PR for Navigation Link block - #18318/#19507. As far as I can tell, the reason was to reduce the noise, and nothing technical.

**Review by talldan — APPROVED** [review]
This looks like a good change to me.

**Pull request merged**
