### PR TITLE
Enable Previews for Navigation Link Blocks

### LINKED ISSUE #32555: Enable rich previews for custom links in the Navigation Block and Editor
## What problem does this address?

The introduction of rich previews for remote URLs in https://github.com/WordPress/gutenberg/pull/31464 only applies to the post editor and only then to usage within `core/paragraph` (strictly anything that utilises the `@wordpress/format` library package).

We should enable this feature in the Nav Block and Editor to provide a rich user experience.

## What is your proposed solution?

1. Set the `hasRichPreviews` prop on `<LinkControl>` within the `core/navigation-link` component.
2. Wire up the `__experimentalFetchRemoteUrlData` API to be available within the Nav Editor.

### PR DESCRIPTION
**Pull request by georgeh**
Closes #32555

## Description
Adds rich previews for Navigation Links

## How has this been tested?
Tested in post editor and navigation editor.

1. Create a navigation link inside a navigation
2. Set the URL to something publicly accessible
3. Edit the link and confirm that an image preview of the page appears

## Screenshots 

https://user-images.githubusercontent.com/128240/141331968-54a769b2-7510-4e62-ba9f-a8b253a6e673.mov

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by vcanales** [comment]
In order to address 2. — enabling rich previews on the navigation editor — from #32555, we have to import `__experimentalFetchUrlData` and pass it to the editor settings for the Block Provider:

packages/edit-navigation/src/index.js
```js
import {
	__experimentalFetchUrlData, // import this
	__experimentalFetchLinkSuggestions as fetchLinkSuggestions,
	store as coreStore,
} from '@wordpress/core-data';
// ...
const editorSettings = useMemo(() => {
		return {
			...settings,
			__experimentalFetchLinkSuggestions,
			__experimentalSetIsInserterOpened,
			__experimentalFetchRichUrlData: __experimentalFetchUrlData // pass it to the settings
		};
	}, [
		settings,
		__experimentalFetchLinkSuggestions,
		__experimentalSetIsInserterOpened,
	]);
```

Kapture 2021-11-11 at 14 30 39

**Comment by georgeh** [comment]
Ahh, thanks @vcanales - I was checking the editor in FSE not in the navigation editor itself.

**Review by vcanales — APPROVED** [review]
👍

**Comment by vcanales** [comment]
@georgeh as of af21db1ff4a617a9ff8399bca98e8151b249b9d2, the flaky image test is being skipped; everything should pass after a rebase.

**Pull request merged**
