### PR TITLE
Try: Make appender fixed position.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This PR is a followup to #31886, to see if it would be possible in using only CSS to take the in-canvas appender out of the flow. The key problem to solve is to prevent the current layout shift that happens when you select a block:

before

This happens because the appender shows up in the DOM and is therefore treated as if it were another block. In the case of flexed containers that space-between, that means there's another item to make room for. This PR makes that a fair bit less jarring by positioning the buttons on the focus border:

Screenshot 2021-10-28 at 13 33 34

fixed appender

That's also a bit of the challenge at the moment, as the border is present only on focus, which means as soon as focus moves inside the inserter, the button sits there, disconnected:

fixed appender

It feels like this should be solvalbe, whether through more liberal use of the `is-highlighted`.

An additional challenge is the abs-positioned nature of it. It looks good in the use cases shown above, but when things start to wrap on multiple lines, it's a bit less optimal:

buttons

I feel like all of this is solvable with design, but curious of your thoughts.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
With the appender appearing on the border of the container, it feels like it's intended to insert next to the container, rather than into it like it actually does.

I think that the appender should instead be attached to the last child block of the container. That would work a whole lot better in the wrapping buttons scenario, for example. Perhaps also shift the button down (for vertical flow) or to the right (for horizontal flow) to avoid overlapping the content of the block it appears after.

**Comment by jasmussen** [comment]
I don't necessarily disagree, but a key part of avoiding a layout shift is the need to remove the item from the DOM. That can either be done by positioning it entirely via JS, or use position absolute which then limits our options for positioning relative to anything other than the container. 

I could put it in the bottom right corner, but it remains tricky:

Screenshot 2021-10-29 at 08 20 42

**Comment by mtias** [comment]
Let's try the sitting on top of the line. It might not work, but we have been postponing improvements here for so long it's degrading the experience with all the layout shifts.

**Comment by ZebulanStanphill** [comment]
I think the design currently used by this PR is very confusing. It looks like it inserts a sibling of the selected block (compare with the current sibling inserters that appear on hover), but it actually inserts a child. I think it would be clearer to just add a toolbar button for inserting into the current block:

image

A nice benefit of this design is that it's more obvious which block you're inserting into, since the insert button is clearly associated with the current block. Additionally, the button is also always visible, whereas currently you tend to have to scroll down to find the appender. I assume it would also be a lot less complicated to handle, CSS-wise.

With some block-specific icon tweaks, we could also make it more obvious when this button would insert a specific block (e.g. a Button into a Buttons) versus opening the library (e.g. inserting stuff into a Group).

Fixed position appenders like the ones in this PR could be repurposed for inserting siblings, which would fit their design a lot better, in my opinion.

**Comment by jasmussen** [comment]
Alright, I've taken a stab at refactoring this one to hopefully bring it to a state where it might land. I agree with the feedback that this needs better solutions, for example replacing it entirely in favor of the sibling inserter or possibly the block toolbar solution. And so I don't consider this PR to be the end-all solution, but rather a step on the way. 

The problem is the layout shifts it's causing in the site editor are so disruptive that it's reducing the entire experience. 

Here's where I've landed:

![fixed appender](https://user-images.githubusercontent.com/1204802/142200325-5c33850f-b891-4850-8697-c0c1df54509c.gif)

Take-aways:

- The elimination of the layout shifts is really, _really_ nice, honestly nice enough to accept a few tradeoffs as we hash this out.
- The positioning I feel, generally works okay, especially if we see it as an interim thing.
- The smaller size feels plenty clickable, especially since this is additive to all the other plusses.
- But the smaller size, and the blue color, does stand out compared to the other plusses on the page. It seems like we could unify, and at least make the sibling inserter plus which is also blue, the same smaller size.

It really comes into its own in the site editor, however in doing so it surfaces a different issue:
![site editor](https://user-images.githubusercontent.com/1204802/142201228-e965c801-9956-439f-b49e-bde1fe89866f.gif)

The current behavior is for the in-canvas appender to show up **both when the parent is selected, and when a child is selected**. That's why in the GIF above you can sometimes see the plus seemingly "hanging there". One quick fix I can make here is to show the plus only when the actual container is selected, not when a child is selected. 

Let me know what you think.

Just for regression testing, here's some test content you can use:

```
<!-- wp:paragraph -->
<p>Empty group, should show the big white plus:</p>
<!-- /wp:paragraph -->

<!-- wp:group -->
<div class="wp-block-group"></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with content:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:paragraph -->
<p>Paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Paragraph 2</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with empty paragraph inside, should show plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with single image inside, should show abs positioned blue plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>A few buttons:</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button /--></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Many buttons:</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /--></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Empty cover with empty paragraph inside, paragraph should have the black plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:cover {"overlayColor":"secondary","minHeight":262,"minHeightUnit":"px","isDark":false} -->
<div class="wp-block-cover is-light" style="min-height:262px"><span aria-hidden="true" class="has-secondary-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Another cover:</p>
<!-- /wp:paragraph -->

<!-- wp:cover {"overlayColor":"primary"} -->
<div class="wp-block-cover"><span aria-hidden="true" class="has-primary-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Cover with Image inside, should have the blue plus abs positioned:</p>
<!-- /wp:paragraph -->

<!-- wp:cover {"overlayColor":"secondary","minHeight":262,"minHeightUnit":"px","isDark":false} -->
<div class="wp-block-cover is-light" style="min-height:262px"><span aria-hidden="true" class="has-secondary-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:cover -->
```

but I do recommend testing primarily in the site editor.

**Comment by jasmussen** [comment]
@jameskoster I'd love your thoughts on this one.

**Comment by jameskoster** [comment]
> The elimination of the layout shifts is really, really nice

💯 

> One quick fix I can make here is to show the plus only when the actual container is selected, not when a child is selected.

I think this may be worth trying. The "hanging" inserters can really be quite awkward.

Screenshot 2021-11-17 at 12 36 10

> The positioning I feel, generally works okay, especially if we see it as an interim thing.

I think it works ok on row orientations, but on columnar layouts it feels a bit misleading. Consider this example:

Screenshot 2021-11-17 at 12 40 28

My expectation here is that a block added via this inserter would appear _adjacent_ to the selected group, which isn't the case – it appears _beneath_ it. I'm not sure how big of a deal this really is in practical terms, but I wanted to note it regardless. Perhaps we can adjust the position based on whether the block is a row or not?

One other issue I spotted: on blocks that span the full width of the canvas, the inserter is now only accessible via horizontal scroll:

https://user-images.githubusercontent.com/846565/142202846-8f24a15c-4329-4824-9e2d-20c74f42dad1.mp4

---

I appreciate this is an unpopular opinion, but I would be in favor of removing this inserter altogether, perhaps only in the Site Editor to begin with, but probably in the post editor too :) 

There are _many_ ways to insert blocks, and I'm just not seeing the value of this one based on the annoying layout shifts, and difficulties in circumventing that.

The sibling inserter allows you to inject blocks between others. The primary inserter in the top bar will insert the block in to the selected container. What purpose does the appender provide that is not covered by those other two inserters?

**Comment by jasmussen** [comment]
Great thoughts, thank you for looking.

> My expectation here is that a block added via this inserter would appear adjacent to the selected group, which isn't the case – it appears beneath it. I'm not sure how big of a deal this really is in practical terms, but I wanted to note it regardless. Perhaps we can adjust the position based on whether the block is a row or not?

There's really no way for me to tell using just CSS, so that's not really something I can do as a small interim iteration. And perhaps that's worth reiterating: this PR is an experiment to see if we can ship 5.9 without layout shifts on select. I would hope we have something better for 6.0. That's also a good way to frame the feedback: what fixes can we make to land this for 5.9?

> I appreciate this is an unpopular opinion, but I would be in favor of removing this inserter altogether, perhaps only in the Site Editor to begin with, but probably in the post editor too :)

Oh I am too! And I do think the sibling inserter, especially if we address #35536, can replace this one and be a good experience.

> What purpose does the appender provide that is not covered by those other two inserters?

The sibling inserter lets us do this:

inbetween

But it doesn't allow us to do either of these; insert after the last block in a container:

after

after-block

Insert before the first block in a container:

before-block

Notably for the "Buttons" use case, it really seems like there needs to at least be an "insert after the last block in a container" behavior in place [horizontally], no?

---

Depending on additional feedback, the todo-items (note to self):

- Fix issues with full wide container blocks
- Hide the appender on the parent

**Comment by jameskoster** [comment]
> Notably for the "Buttons" use case, it really seems like there needs to at least be an "insert after the last block in a container" behavior in place [horizontally], no?

What if the sibling inserter was updated to also appear before the first block in a container, and after the last block? 🤔

**Comment by jasmussen** [comment]
Yep, I'm saying I think that would work. I just also assume that's non trivial to do.

**Comment by jasmussen** [comment]
Alright, for folks subscribed to this one, here's a small status update.

The problem to solve remains to avoid the layout shifts that happen when you select a nesting container and the "Plus" button appears. It's important to keep this in mind, because the experience that's shipping is definitely compromised by those shifts, especially in the site editor, and it's the primary reason why we should consider an interim solution to the problem, and then come back with a better long term solution to replace it.

I have three different PRs that aim to solve this:

**1. What you see in this branch (36037). It affixes the plus to the top right of the container, makes it small and blue.**



**2. #36602. This one entirely hides the plus, but only in the site editor.**



**3. #36605. Based on 36037, but doesn't visually change the plus, and places it in the bottom right corner of the container.**



---

Of the three, I personally prefer 2 or 3 as they feel like smaller changes. Let me know your thoughts.

**Comment by jameskoster** [comment]
Nice! For 3 did you try making the appender only appear for the closest container? I noticed that when you select the buttons block, the appender for the containing column still popped up in addition to the one for the buttons block. I'm also wondering how the [+] interacts with right-justified content, the overlap seems like it could be a little awkward?

Overall I like 2 and 3 the most as well, with a slight preference for 2 as I feel we've over-indexed on inserters and the appender seems to be the least useful on balance.

**Comment by jasmussen** [comment]
I tried that just now, and it's easy enough to get to work for the inner containers:
direct ancestors

However it appears there's an issue attached to that which relates to this same component being used for an empty group block which shows the white plus. I'll see if I can get it working there as well.

**Comment by jasmussen** [comment]
@jameskoster okay I have a fix working that I can push to #36605 if we like it. It works like the GIF I just shared, but it does come with this downside:
button

That is, you now have to select the exact container in order to get the inserter to appear. In the case of the buttons block, that means the inserter disappears when you select a button (singular). We could consider that a boon, but wanted to just sanity check before I push it. What do you think?

**Comment by jameskoster** [comment]
I'm inclined to say that's probably ok. Once again it feels like the lesser of two evils. 

But ultimately I feel this just adds more weight to the idea of getting rid of it altogether. There are just so many quirks and compromises around this thing 😅

**Comment by jasmussen** [comment]
Thanks, I pushed the fix.

> But ultimately I feel this just adds more weight to the idea of getting rid of it altogether. There are just so many quirks and compromises around this thing 😅

Actually I think the fact that we are seriously looking at these temporary fixes acknowledges how bad the situation is, and that it needs a developer. That isn't me advocating for one solution over the other (though 3 is growing on me), just that I have full confidence this will finally get the attention it needs.

**Comment by jasmussen** [comment]
Closing in favor of #36605.

**Pull request closed without merging**
