### PR TITLE
[RNMobile] - Layout picker - Update emoji

### PR DESCRIPTION
**Pull request by geriux**
`Gutenberg Mobile PR` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/2103

## Description
While testing on Android, an [issue was spotted](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2093) on devices with [API 21 and 22](https://developer.android.com/guide/topics/resources/internationalization#versioning-prenougat) where the emoji wouldn't render properly because we were using some from a newer Unicode version. So we need to update it to make it compatible with those. While we give support to that range of OS versions we need to pick emojis from the [Unicode 6.0 definition](https://emojipedia.org/unicode-6.0/)

## How has this been tested?
- Create an Android Emulator with API 21 and 22
- Open the app with metro running
- Create a page
- Expect to see the Layout picker buttons visible and all emojis should render properly

## Screenshots
| Before Services emoji | After Services emoji |
|     :---:      |     :---:      |
|  |   |

| iOS Contact emoji | Android Contact emoji |
|     :---:      |     :---:      |
|  |   |

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by geriux** [comment]
While testing I spotted the "Envelope" -> ✉️ emoji wasn't working correctly for API Level >= 21 <=23 as well.

Screenshot_1585757038

I tested going to the [Unicode Version 1.0](https://emojipedia.org/unicode-1.1/) from the emulator's browser and barely some rendered correctly from that list, then I checked [the 6.0 version](https://emojipedia.org/unicode-6.0/) and almost all of them rendered correctly. @iamthomasbishop is there another emoji we could use as a replacement for the "Envelope" (✉️) emoji?

**Comment by iamthomasbishop** [comment]
@geriux For the contact one, I think we could use either “https://emojipedia.org/e-mail/”, “[closed mailbox with raised flag](https://emojipedia.org/closed-mailbox-with-raised-flag/)”, or “[memo](https://emojipedia.org/memo/)” from the 6.0 spec.

**Comment by geriux** [comment]
Thanks for the options @iamthomasbishop here's how they'd look:

###  E-Mail
| iOS | Android |
|     :---:      |     :---:      |
|  |   |

### Closed Mailbox with Raised Flag
| iOS | Android |
|     :---:      |     :---:      |
|  |   |

### Memo
| iOS | Android |
|     :---:      |     :---:      |
|  |   |

Which one do you prefer? All three render correctly 😃

**Comment by iamthomasbishop** [comment]
> Which one do you prefer?

I think I prefer the mailbox one, but all 3 of them work just fine.

**Review by chipsnyder — APPROVED** [review]
Tested on API 24 and 27 the 🔧(fix) still looks good on those. Once Matt checks I say 📫(Ship it)

I also did a spot check on iOS 11.0.1 and everything looks good there too

**Review by mkevins — APPROVED** [review]
Fyi: I had to merge with latest develop on gutenberg-mobile to resolve an interface mismatch with WordPress-Android develop.

After that:

Looks good, tested via emulator on API 21 and 23 :+1: . Nice work, LGTM!

**Pull request merged**
