### PR TITLE
Table Block: Limit the max number of row/column fields when creating the table

### LINKED ISSUE #44808: Set up the limit for the max number of column field & max number of row field can be added to table block of gutenberg
### Description

During QA of beta version I found below issue, can you please have a look if possible

Right now there is no maximum number limit set up for the table block of Gutenberg.

User can add any number of rows & columns to the table block which is breaking the backend of WordPress.

I believe, nobody will add that kind of inputs there but we can add those validations for better usability.

I have checked above issue over the WordPress Version 6.0.2, Version 6.1 (Beta 3)

### Step-by-step reproduction instructions

1. Go to WordPress Guttenberg editor for any existing page
2. Add an element for the **Table**
3. You will find an option to add **Column Count** & **Row Count**
4. If you add more than 100 number for any of "Column count / Row count" , it will accept it and break the backend page

### Screenshots, screen recording, code snippet

Screenshot 2022-10-10 112848

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix #44808

## What?
This PR limits the max number of row/column fields to **30** when creating tables.

This limitation is only valid when creating a table, and once the table is created, the number of rows and columns can be increased beyond the limit.

## Why?
Currently, there is no limit when creating rows/columns, which causes the block editor to freeze or causes out-of-memory errors in the browser when huge values are specified.

## How?
The upper limit would depend on the environment, but I specified 30. I felt that this was an acceptable number for the time it takes for the table to be rendered and the response to entering cell text is just barely acceptable.

Examples of a block that limits the maximum number of:

- The columns block can be specified up to 6 columns in the sidebar, but more columns can be inserted by the block inserter.
- The tag cloud block limits the maximum number of tags to 100.
- The page list block within the navigation block allows being converted to a page link only if the number of pages is within 100.

## Testing Instructions

- Insert a table block.
- Enter a number greater than 30 in the row or column field.
- Confirm that the value is converted to 30.

### CODE REVIEW

**Review by Mamaduka — COMMENTED** [review]
Thank you, @t-hamano!

The updated behavior feels like a bug since a user does not know the new limitations - they specify a 100x100 Table block and only get 30x30.

P.S. Ideally, it would be nice to look into this perf bottleneck - #30091

**Comment by t-hamano** [comment]
Thanks for the feedback, @Mamaduka!

>The updated behavior feels like a bug since a user does not know the new limitations - they specify a 100x100 Table block and only get 30x30.

Admittedly, the 30 x 30 limit may seem like a bug. However, when we try to create a huge table such as 1000 x 1000, the browser seems to freeze. It is difficult to determine an appropriate threshold, but I think some kind of limit is necessary. What do you think?

> P.S. Ideally, it would be nice to look into this perf bottleneck - #30091

Thank you for the information. I would like to check this issue as well 👍

**Comment by Mamaduka** [comment]
I think any visual indication that there's a limit will be helpful. Maybe the design team can help us out here.

**Comment by t-hamano** [comment]
I thought about this PR again, and it may not be ideal to introduce the new limitation. Looking back, I have also created tables with over 100 rows 😅 Therefore, I would like to close this PR and look into #30091.

**Pull request closed without merging**
