### PR TITLE
Uniform Focal point labels

### LINKED ISSUE #62408: Uniform Focal point labels
Since version 6.5, it is possible to define the focus point of the background image for a Group block.
But the label of this option is "Position", and not "Focal point" as for the Banner block.
As this is the same function (defining the focus point), it would be desirable for the labels of this option to be identical for both blocks.
image
image

As Position can refer to the location of the background image within the Group block (e.g., right, left, center), the Focal point label is much more appropriate.
Please change the "Position" label to "Focal point" for the blocks: Group, Row and Stack.

### PR DESCRIPTION
**Pull request by akasunil**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/62408
 
## Testing Instructions
- Add group block
- Open style setting
- Add background image
- look for focal point control
 
## Screenshots or screencast 
image

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

In my feeling, the term "Focal Point" itself seems to be a bit confusing. The background panel controls four things: `background-image`, `background-position`, `background-repeat`, and `background-size`, but since the `FocalPointPicker` component controls background-**position**, it feels easier to understand as it is now.

Therefore, I would lean towards changing the label "Focal Point" to something that better matches the context.

Currently, the label "Focal Point" is used in the Cover block and Media & Text block. In these two cases, I would prefer to change the label as follows:

### Media & Text Block

`Focal point` to `Media position`

media-text

### Cover Block

`Focal point` to `Image position`

cover

cc @WordPress/gutenberg-design @ramonjd Please let us know your thoughts.

**Comment by jasmussen** [comment]
I could go either way on this one. On the one hand, I appreciate how focal point seems to work well for the visual below with the drag handle. On the other hand, I'm leaning towards position, since top/left position values are shown right below.

**Comment by jameskoster** [comment]
'Position' feels more universally recognisable to me. 

The prefix '**Media** position' is mostly useful in the Media & Text block since 'Position' would be an ambiguous option in the tools panel. But I don't know that we need that prefix elsewhere.

**Comment by ramonjd** [comment]
Thanks for the PR. I agree the labels should be the same, or similar. 

I think "Position" is valid and universal label for instances of the control. I'd argue even terser and more straight forward than "focal point".

It also relates directly to the CSS property it updates (in the case of the cover block `object-position`) - though the tool does give the impression of setting the image origin.

**Comment by richtabor** [comment]
Why not update the background image control to use the existing focal point term? Has there been feedback that "Focal point" is not clear? It's certainly clearer than "Position", in my opinion.

**Comment by akasunil** [comment]
Thank you for the input, everyone. I appreciate the different perspectives on this. I agree that consistency across labels is important for user understanding and ease of use.

"Focal Point" is visually descriptive, it seems to cause some confusion about what it controls. "Position" might simplify user understanding, especially for those who are familiar with CSS properties ( as @ramonjd mentioned ). I agree with @t-hamano suggestions.

let me know your thoughts.

**Comment by richtabor** [comment]
I don't prefer "Position" for these two reasons:

1. Position is used elsewhere in the UI for setting CSS position, like absolute positioning. 

2. Position is less clear than focal point. The ideal behind "focal point" is that you're deciding where the focus is on this image. The "Position" label is indicative of you deciding the position of the focal point. Why abstract further from the actual intent?

**Comment by t-hamano** [comment]
I noticed that the background image UI is a popover in the latest Gutenberg. In this case, which is better, "Position" or "Focal point"?

image

**Comment by ramonjd** [comment]
> I noticed that the background image UI is a popover in the latest Gutenberg. In this case, which is better, "Position" or "Focal point"?

I think it should be consistent, whether one or the other. As this PR stands, changing it to Focal point is 👍🏻 

Just needs a rebase after https://github.com/WordPress/gutenberg/pull/60151 as mentioned [above](https://github.com/WordPress/gutenberg/pull/62438#issuecomment-2210535297)

**Review by t-hamano — APPROVED** [review]
Ok, let's ship this PR 👍

**Pull request merged**
