### PR TITLE
docgen: Support object destructured arguments

### LINKED ISSUE #29944: docgen: Does not support array expressions, object expressions or assignment patterns for TypeScript
## What problem does this address?
`docgen` currently only supports very simple parameters for TypeScript. It can parse the following successfully:

```ts
/**
 * @param foo The foo thing.
 * @param rest The rest of bar.
 * @return A better foo
 */
function fn(foo: string, ...rest: number[]): string {}
```

However it cannot parse the following examples:

```ts
/**
 * @param foo An array of any size.
 * @return The first element of the array
 */
function head<T>([head]: T[]): T { return head; }
```

```ts
/**
 * @param foo An object with a `bar` key to get.
 * @return The value of `bar`
 */
function getBar({ bar }: { bar: any }): any { return bar; }
```

```ts
/**
 * @param foo Defaults to null.
 * @return The value of foo
 */
function getArgument(foo: any = null): any { return foo; }
```

```ts
/**
 * @param foo Defaults to an array of undefineds.
 * @return The value of foo's first element.
 */
function head([first]: any[] = [undefined]): any { return first; }
```

```ts
type Props = {
  bar: string
}

/**
 * @param props
 * @return Rendered component
 */
function Component({ bar }: Props) {
  return <div>{bar}</div>;
}
```

`docgen` will fail on these because it is unable to match up the documented parameter name from the JSDoc to the actual parameter when it searches the parameters: https://github.com/WordPress/gutenberg/blob/1b337c9275bafba2bd8d9bc46fff7c037145f7e3/packages/docgen/lib/get-type-annotation.js#L399-L406

## What is your proposed solution?
Currently we search for the parameter by name... however this has a fatal flaw because some parameter's names as documented in the JSDoc may not correspond to any declared parameter in function signature. For example, when an array pattern us used (array destructuring) the documented parameter means nothing because we have to assume it corresponds to the array itself rather than the elements of the array. Otherwise there's no way to disambiguate things.

So, I think my proposed solution is that instead of searching for the parameter by name, we instead pass the `index` of the parameter we need the type annotation for and then find it that way. 

This would change the signature of `getTypeAnnotation` to include the `index`. To do this however I think we need to map out the parameter annotations because currently we naïvely call `getTypeAnnotation` for every JSDoc tag and just return `''` if it's not a `param` or `return` tag.

Something like the following might do the trick:

```js
let paramCount = 0;
jsdoc.tags = jsdoc.tags.map( ( tag ) => {
	const index = tag.tag === 'param' ? paramCount++ : null;
	return {
		...tag,
		type: getTypeAnnotation( tag, token, index ),
		description:
			tag.description === '\n'
				? tag.description.trim()
				: tag.description,
	};
} );
```

Then in `getTypeAnnotation` we forward along the `index` parameter when `tag` is `param`. Then in `getParamTypeAnnotation` instead of the `reduce` finder function above, we simply index the `params` argument and retrieve the `typeAnnotation` from it.

Again, I think this will work fine but I wanted input from @nosolosw and others to see if there was any other way folks could think of to solve this problem.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
Fixes #29944
Depends on #29945 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by grzim** [comment]
The current level of nesting and repetitive, very long path to properties, makes it very difficult to read and maintain. I would suggest taking advantage of destructing in order to reduce the complexity of props paths. Something like: 

```js
const {
  isIdentifier,
  isRestElement,
  isArrayPattern,
  isTSArrayType,
  isTSTypeReference,
  isTSTupleType,
  isObjectPattern,
  isTSTypeLiteral,
} = babelTypes;

const {
  typeAnnotation: {
    typeAnnotation,
    typeAnnotation: {
      elementType,
      elementType: {
        typeName: {
          name: elementTypeName,
          typeAnnotation: elementTypeAnnotation,
        } {},
      } = {},
      elementTypes = [],
      members: anotationMembers = [],
    } = {},
  } = {},
} = paramToken;
```
the code after reducing props paths: 

```js

if ( isIdentifier( paramToken ) ) {
	return getTypeAnnotation( typeAnnotation );
} else if ( isRestElement( paramToken ) ) {
	return getTypeAnnotation( typeAnnotation );
} else if ( isArrayPattern( paramToken ) ) {
	if ( ! tag.name.includes( '.' ) ) {
		// 1 unqualified name
		return getTypeAnnotation( typeAnnotation );
	}
	// 2 qualified name i.e., an element of the array being destructured
	const position = parseInt( tag.name.split( '.' ).slice( -1 )[ 0 ], 0 );
	if ( isTSArrayType( typeAnnotation ) ) {
		if ( isTSTypeReference( elementType ) ) {
			return elementTypeName;
		}
		return getTypeAnnotation( elementTypeAnnotation );
	} else if ( isTSTupleType( typeAnnotation ) ) {
		return getTypeAnnotation( elementTypes[ position ] );
	}
	return getTypeAnnotation( typeAnnotation );
} else if ( isObjectPattern( paramToken ) ) {
	if ( ! tag.name.includes( '.' ) ) {
		// 1 unqualified name
		return getTypeAnnotation( typeAnnotation );
	}
	// 2 qualified name i.e., an element of the array being destructured
	const memberName = tag.name.split( '.' ).slice( -1 )[ 0 ];
	if ( isTSTypeLiteral( typeAnnotation ) ) {
		// if it's a type literal we can try to find the member on the type
		const member = anotationMembers.find(
			( m ) => m.key.name === memberName
		);
		if ( member !== undefined ) {
			return getTypeAnnotation( typeAnnotation );
		}
	}
	// If we couldn't find a specific member for the type then we'll just return something like `Type[ memberName ]` to indicate the parameter is a member of that type
	const _typeAnnotation = getTypeAnnotation( typeAnnotation );
	return `${ _typeAnnotation }[ '${ memberName }' ]`;
}
```

When it comes to nested if-else statements, we can simplify them if we introduce some predicates: 

```js
const isWithSeparators = ( f ) => ( paramToken ) =>
  f( paramToken ) && tag.name.includes( '.' );
const isWithoutSeparators = ( f ) => ( paramToken ) =>
  f( paramToken ) && ! tag.name.includes( '.' );

const isArrayPatternWithNoSeparators = isWithoutSeparators(isArrayPattern);
const isArrayPatternWithSeparators = isWithSeparators( isArrayPattern );
const isObjectPatterWithSeparators = isWithSeparators( isObjectPattern );
const isObjectPatternWithNoSeparators = isWithoutSeparators(isObjectPattern);

const typeAnnotationPredicates = [
  isIdentifier,
  isRestElement,
  isArrayPatternWithNoSeparators,
  isObjectPatternWithNoSeparators,
];

if ( typeAnnotationPredicates.some( paramToken ) ) {
  return getTypeAnnotation( typeAnnotation );
}

if ( isArrayPatternWithSeparators( paramToken ) ) {
  const position = parseInt( tag.name.split( '.' ).slice( -1 )[ 0 ], 0 );
  if ( isTSArrayType( typeAnnotation ) ) {
    if ( isTSTypeReference( elementType ) ) {
      return elementTypeName;
    }
    typeAnnotation = elementTypeAnnotation;
  } else if ( isTSTupleType( typeAnnotation ) ) {
    return getTypeAnnotation( elementTypes[ position ] );
  } else {
    return getTypeAnnotation( typeAnnotation );
  }
}

if ( isObjectPatterWithSeparators( paramToken ) ) {
  // 2 qualified name i.e., an element of the array being destructured
  const memberName = tag.name.split( '.' ).slice( -1 )[ 0 ];
  if ( isTSTypeLiteral( typeAnnotation ) ) {
    // if it's a type literal we can try to find the member on the type
    const member = anotationMembers.find(
      ( m ) => m.key.name === memberName
    );
    if ( member !== undefined ) {
      return getTypeAnnotation( typeAnnotation );
    }
  }
  // If we couldn't find a specific member for the type then we'll just return something like `Type[ memberName ]` to indicate the parameter is a member of that type
  //const typeAnnotation = getTypeAnnotation( _typeAnnotation );
  return `${ typeAnnotation }[ '${ memberName }' ]`;
}
```

**Comment by sarayourfriend** [comment]
I don't think it's possible to do the destructuring you're suggesting as there are multiple different shapes the `paramToken` object could take, that's why we need all the nested if/else's in the first place.

I do like the idea for introducing some new predicates to flatten things a bit, that should help considerably, thanks 🙂

**Comment by grzim** [comment]
I understand that there are different shapes of `paramToken` this is why to every destructured property I have added a default value. It will work even if a `paramToken` an empty object. Is there any case where this kind of destructuring will fail?

**Comment by sarayourfriend** [comment]
I'm not sure. FWIW doing it that way is not going to play nicely with types, which will eventually be added to this package. Each type predicate is a useful call here also in that it refines the types each time... destructuring from the `paramToken` object will not be possible if the type is `Identifier | Pattern` for example, at least I don't think so.

I'd love for someone else to weigh in here, I don't necessarily see a problem with the current approach to be honest, I think it's a good first approach that is clear what is happening each step of the way rather than trying to group a bunch of actions together that may or may not be related (like the different structures of each type of pattern).

**Comment by sarayourfriend** [comment]
Closing in favor of #30675

**Pull request closed without merging**
