### PR TITLE
Prefixes all php filters with wpdocs_

### LINKED ISSUE #53567: Documentation: Use consistent prefixes in code examples
## What problem does this address?

Looking at this code  example,
https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/
```
function filter_metadata_registration( $metadata ) {
    $metadata['apiVersion'] = 1;
    return $metadata;
};
```
The PHP function is not prefixed. If someone copy-pastes this and doesn't change the function name, there is a small risk of naming conflicts.

## What is your proposed solution?

Use `wpdocs` as the prefix in all code examples where one is needed.

### PR DESCRIPTION
**Pull request by bacoords**
## What?

Closes #53567 by modifying the prefix for PHP filter examples

### CODE REVIEW

**Review by ryanwelcher — APPROVED** [review]
Changes look great.

**Review by juanmaguitar — APPROVED** [review]

**Comment by t-hamano** [comment]
Hi @bacoords,

Could you resolve the conflict by rebasing to merge this PR?

**Comment by bacoords** [comment]
@t-hamano 

I've updated my branch. From what I can tell, the old `docs/getting-started/create-block` tutorial is basically gone and replaced with https://github.com/WordPress/gutenberg/blob/trunk/docs/getting-started/devenv/get-started-with-create-block.md which doesn't have the same code snippets so this PR should be ready.

**Review by t-hamano — APPROVED** [review]
Thanks for the update. It looks to me that all prefixes are updated properly 👍

**Pull request merged**
