### PR TITLE
EditorConfig: Relax 2 space indentation rule to only the `package.json

### PR DESCRIPTION
**Pull request by ntwb**
This is a partial revert of https://github.com/WordPress/gutenberg/commit/7c9cfe4e2c25865c43326a72a31030c9e55671e1, originally it was added so that it was in sync with WordPress' `.editorconfig`, rather WordPress should follow suit of how it's done here.

Follow up to #1029 / #1022

### CODE REVIEW

**Comment by ntwb** [comment]
Upstream core ticket https://core.trac.wordpress.org/ticket/40946

**Review by aduth — COMMENTED** [review]
Should we restore tabs to [`composer.json`](https://github.com/WordPress/gutenberg/blob/master/composer.json) here as well?

Do `.yml` files need two-spaces generally, or is it just Travis being picky?

**Comment by nylen** [comment]
The `composer.json` default is 4 spaces (and `composer.lock`, which still uses 4 spaces in `master`), but it looks like `composer` is [pretty good](https://github.com/composer/composer/issues/1788) about preserving existing indentation.

**Comment by nylen** [comment]
http://www.yaml.org/faq.html

> **Why does YAML forbid tabs?**
>
> Tabs have been outlawed since they are treated differently by different editors and tools. And since indentation is so critical to proper interpretation of YAML, this issue is just too tricky to even attempt. Indeed Guido van Rossum of Python has acknowledged that allowing TABs in Python source is a headache for many people and that were he to design Python again, he would forbid them.

:popcorn: :popcorn: :popcorn:

**Comment by ntwb** [comment]
I added commit https://github.com/WordPress/gutenberg/pull/1067/commits/09b849bac97b84694423b94858c75ea3abcef875 that switches `composer.json` to tabs 🤖

**Review by aduth — APPROVED** [review]

**Pull request merged**
