### PR TITLE
Use ClipboardJS latest version and clean up focus loss workaround.

### LINKED ISSUE #57154: Use ClipboardJS latest version
### Description

ClipboardJS latest version is 2.0.11 see https://github.com/zenorocha/clipboard.js/releases/tag/v2.0.11 released 1 year and a half ago.
It includes a fix for a focus loss issue that was reported upstream at https://github.com/zenorocha/clipboard.js/issues/680

In https://github.com/WordPress/gutenberg/issues/23994 / https://github.com/WordPress/gutenberg/pull/24022 we introduced a workaround that is no longer necessary. Worth noting `packages/compose/src/hooks/use-copy-on-click/index.js` is now deprecated. The same workaround was ported to the new hook `useCopyToClipboard`.

WordPress Core already uses ClipboardJS 2.0.11.

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/57154

## What?

Upgrades ClipboardJS to 2.0.11.
Removes a focus loss workaround.

## Why?

ClipboardJS 2.0.11 includes a fix for a focus loss that makes our workaround no longer necessary.
WordPress Core already uses 2.0.11.

## How?

Upgrades ClipboardJS.
Removes focus loss fix from `useCopyToClipboard`.

## Testing Instructions

- Test the original issue where we introduced our foucs loss workaround https://github.com/WordPress/gutenberg/issues/23994
- Select a paragraph block.
- Use the keyboard to move focus to the block toolbar, open the 'more' Options menu and activate the 'Copy' button with the Enter or Spacebar key.
- Observe the dropdown menu stays open.
- Observe focus stays on the 'Copy' button.
- Press the Tab key and observe focus moves to the next item in the dropdown menu.
- Paste your clipboard content into a text editor and observe the block content has been copied correctly.
- Open the Color picker by clicking 'Text' in the settings panel.
- Click the color preview to set a custom color. The custom color picker opens.
- Set a color.
- Click the Copy icon.
- Observe the color picker stays open and focus stays on the Copy button.
- Paste your clipboard content into a text editor and observe the color code has been copied correctly.

### CODE REVIEW

**Comment by t-hamano** [comment]
I found that in #37810 an attempt was made to replace ClipboardJS with a native clipboard API.

@ciampo It looks like some issues need to be resolved in order to replace it with a native API. Is it okay to update this library for now?

**Comment by ciampo** [comment]
> Is it okay to update this library for now?

Yeah, sounds good. I'm not actively working on that PR at the moment.

**Review by carolinan — APPROVED** [review]
I followed the testing instructions and both copy buttons remain focused and the copied content is correct.

**Comment by afercia** [comment]
Thank you all for the review and feedback.

**Pull request merged**
