### PR TITLE
Post settings: Featured Image preview is too small

### LINKED ISSUE #33837: Post settings: Featured Image preview is too small
## What problem does this address?
By default, the featured image preview uses the `post-thumbnail` version of an image. In Gutenberg, the featured image component first tries to use that value and otherwise uses the fallback value of the `thumbnail`. So, if `post-thumbnail` is not available the featured post thumbnail looks small and doesn't cover the full available area. 

Before Screenshot: 

## What is your proposed solution?

 The `thumbnail ` image is too small to cover the area and set bad expectations. So using the `full` version image instead of using the `thumbnail` version of the featured post image as a fallback.
 
To resolve this issue changing default fallback size from `thumbnail` to `full` can be done: https://github.com/WordPress/gutenberg/blob/6e308bf38f997f229379ea57fce82461a5bba084/packages/editor/src/components/post-featured-image/index.js#L75-L80

After Screenshot:

### PR DESCRIPTION
**Pull request by gavande1**
## Description

By default, the featured image preview uses the post-thumbnail version of an image. In Gutenberg, the featured image component first tries to use that value and otherwise uses the fallback value of the thumbnail. This PR aims to use the full version image instead of using the thumbnail version of the featured post image as a fallback.

Fixes: https://github.com/WordPress/gutenberg/issues/33837

## How has this been tested?
1. On the dev site create a new post
2. Open the settings sidebar (by clicking the cog icon in the top right of the editor)
3. Select the "Post" tab and scroll to the "Featured Image" section
4. Add a Featured Image and see if the featured image covers the available area.

## Screenshots 
Before / After

## Types of changes
Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by cpapazoglou** [comment]
@ntsekouras, can you advise us whether this change seems good? In my POV, `post-thumbnail` is set by themes to better reflect the quality and the aspect-ratio of the featured image. If `post-thumbnail` doesn't exist, it doesn't make sense falling back to `thumbnail` since this is not what users will get in the frontend, quality & aspect-ratio wise. `full` is our best bet I think.

**Comment by ntsekouras** [comment]
Thanks for your contribution @gavande1 and for the ping @cpapazoglou ! IMO featured image preview shouldn't create any expectations to a user, as the final display(front-end) is handled by the theme and could be of any size/aspect-ratio etc... For example we could apply a change to show full image, but the theme displays only thumbnails 😄 .

By seeing the current code in trunk, this feels okay to me, but would like another opinion from @mcsf or @gziolo maybe 😄 ?

**Comment by Mamaduka** [comment]
Maybe we should use `large` instead of the `full` as a fallback image size value? It is also the current default image size for the editor.

Featured Image will use the full-size image if the first two options aren't available.
https://github.com/WordPress/gutenberg/blob/9763378e70d2e3a693a4fa83bb6c985d8fbccf88/packages/editor/src/components/post-featured-image/index.js#L91-L96

**Comment by gavande1** [comment]
We could use the `large` or `medium` but they can be configured by the user within media options. So if the user changes the size of `large` to 150 then we're back to square one. That's why the size `full` is proposed which is not configurable by the user.

**Comment by ntsekouras** [comment]
>By seeing the current code in trunk, this feels okay to me, 

I wanted to clarify that with the above I meant that I think the code in `trunk` is good as is and we don't need to change it - I read it and felt a bit confusing to me, thus the explaining here 😄 

>We could use the large or medium but they can be configured by the user within media options. So if the user changes the size of large to 150 then we're back to square one. That's why the size full is proposed which is not configurable by the user.

Letting users have control in these sizes is the purpose of the existence and appliance of these filters, no? Why override them with something opinionated?  As I said the preview is not representative to the end result, the theme is and the way I see it is better to load a smaller image, which is just a preview of the image to help a user recognize what image they have set.

**Pull request closed without merging**
