### PR TITLE
Trying move to trash as a link

### PR DESCRIPTION
**Pull request by karmatosed**
I like the look of this even better than the button when smaller. However, I am going to loop in @enriquesanchez to make sure I haven't made this have accessibility issues by changing it, or I am missing something to add to a link.

image

### CODE REVIEW

**Comment by melchoyce** [comment]
Without the button styling, this might benefit from adding a trash icon to the link text.

**Comment by karmatosed** [comment]
@melchoyce it might, but does it need one is my wonder. I often found that icon weird as trash doesn't mean that in all languages. I also wonder if there's a feeling it needs it when doesn't. My 'pro icon' thoughts are that the styling right now relies on color to denote 'don't click here' or what it is, which feels not great.

**Comment by enriquesanchez** [comment]
Thanks for the ping @karmatosed! Happy to help.

In VoiceOver, the "link" is properly announced and operated as a button, because it still is a button. I don't have an issue with this, because we use the same pattern of buttons-that-look-like-links elsewhere in the editor.

I personally prefer the link styling for this option. Feels much more balanced. I also agree with you on resisting the urge to add an icon to it. A part of me wants it, but I think it's really not needed. The button's label itself is more than enough to communicate what this button does.

**Comment by joedolson** [comment]
Since the 'Move to Trash' action actually sends the user to a new screen, moving from the post editor to the post list, I think this might be a good opportunity to change it to a link. I'm open to arguments, since there are actually two actions happening (deletion event and a redirect event), but I think that the end result is more link-like than button-like.

**Comment by jasmussen** [comment]
Designwise, this seems fine. Whether it's a button that looks like a link or an actual link, I'll defer to folks like Enrique or Joe; the action itself seems descriptive enough to me to make me as a user know what happens. 

Also, I think there are some larger sidebar text rhythm and balancing heuristics that could polish the sidebar as a whole, but this change prevent that from happening, and it seems line-height balanced with the other items in this panel.

So at the end of this, the main thing to figure out, it seems, is whether it's actually a link or a button. If we're fine with a button that looks like a link, 👍 👍 from me.

**Pull request merged**
