### PR TITLE
Update published packages changelogs

### PR DESCRIPTION
**Pull request by gziolo**
We missed this for the last 2 releases of packages. They contained only small bug fixes so it isn't a big deal but I added them for the record.

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
👍🏻

**Comment by noisysocks** [comment]
`@wordpress/list-reusable-blocks` is a good example. Check it out—the last 11 releases have been completely unnecessary 😛

https://github.com/WordPress/gutenberg/commits/master/packages/list-reusable-blocks

**Review by noisysocks — APPROVED** [review]

**Comment by ntwb** [comment]
@noisysocks Changes to any `CHANGELOG.md` should be ignored by Lerna: ([docs](https://github.com/lerna/lerna#lernajson))

https://github.com/WordPress/gutenberg/blob/b5a709fc63a11f042c53f67f80a2eaf50713e00a/lerna.json#L7-L11

**Comment by noisysocks** [comment]
Interesting—there must be some other problem with our configuration. Right now if I run `npm run publish:check`, I get:

```
@wordpress/block-library
@wordpress/blocks
@wordpress/components
@wordpress/edit-post
@wordpress/editor
@wordpress/format-library
@wordpress/html-entities
@wordpress/list-reusable-blocks
@wordpress/nux
```

Of those, `@wordpress/list-reusable-blocks` and `@wordpress/nux` have not been recently changed, which you can see by looking in the GitHub history:

https://github.com/WordPress/gutenberg/commits/master/packages/list-reusable-blocks
https://github.com/WordPress/gutenberg/commits/master/packages/nux

**Comment by ntwb** [comment]
Indeed they have not changed recently, but the `package.json` dependancies:
https://github.com/WordPress/gutenberg/blob/b5a709fc63a11f042c53f67f80a2eaf50713e00a/packages/nux/package.json#L24-L28

Which are currently:
> https://unpkg.com/@wordpress/nux@3.0.3/package.json
```json

@wordpress/components | "^7.0.2"
@wordpress/compose | "^3.0.0"
@wordpress/data | "^4.0.1"
@wordpress/element | "^2.1.8"
@wordpress/i18n | "^3.1.0"
```

And as `@wordpress/components` does include recent changes, the `@wordpress/components | "^7.0.2"` will get bumped to `7.0.3`, `7.1.0`, or `8.0.0` depending on semver bump of that package

**Pull request merged**
