### PR TITLE
Fix: Add ability to opt out of Core color palette

### LINKED ISSUE #36407: Missing ability to remove/override "Core" color palette
### Description

In the original tracking issue from Matias (#29568) it was outlined that

> Of course, it still needs to be possible to fully disable the default palette since sites that have stricter branding guidelines might prefer to remove it entirely, the same way the custom colors interface can be disabled, but it should not be the default behaviour that a theme palette overwrites the color palette.

Looking at the implementation now that does not seem to be the case. 

This is a big problem for custom builds with strict design systems where the litigation to certain brand colors is a very important need that is no longer met without the ability to remove / override that "Core" palette. 

I do understand and agree that the default behavior should be having both paletes. But like @mtias mentioned initially then this was proposed themes should be able to override / remove that. 

### Step-by-step reproduction instructions

There are no steps to reproduce as there is no API to remove the Core palette. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by fabiankaegy**
## Description

Add the ability for themes using `theme.json` to opt out of showing the "Core" color Palette and Core Gradients.

```json
{
	"version": 1,
	"settings": {
		"color": {
			"corePalette": false,
			"coreGradients": false
		}
	}
}
```

Closing #36407 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by fabiankaegy** [comment]
@oandregal Hey 👋 

Would love to get some feedback on this initial approach. In my testing, it does what we talked about in #36407 but I am not sure where the best place to execute this is. 

Would love to get some feedback on it :) 

Thanks in advance!

**Comment by oandregal** [comment]
Nice! Thanks for the quick turnaround.

Can we do it in a way that the changes are scoped to `WP_Theme_JSON` but not the resolver?

**Comment by fabiankaegy** [comment]
@oandregal I looked into it for a while and currently don't know how exactly we can get there. The issue I am running into is that there is no hook or anything that executes after the different `theme.json` files are merged. 

I'll continue to look into it though :) 

If anyone has any suggestions or ideas I'm all open for input :)

**Comment by oandregal** [comment]
Would you be able to add some tests for this new behavior? It'd help us to identify/clarify that this works.

My thinking is as follows: we can inline the current `maybe_remove_core_color_palette_and_gradients` logic into the `WP_Theme_JSON.merge` method: if the setting exists, we empty the core palette. We need to merge theme's settings on top of core's settings, hence, the core palette is going to be present when the incoming data is the theme's.

**Comment by fabiankaegy** [comment]
@oandregal I moved the function call into the `merge` function so it is now contained within the `WP_Theme_JSON_Gutenberg` class. 

I also added some test cases for it :)

**Comment by fabiankaegy** [comment]
One edge case that is currently not being accounted for is you opting out on the global level but then opting-in on the block level. 

```
{
    "version": 1,
    "settings": {
      "color": {
        "corePalette": false,
        "coreGradiens": false
      },
      "blocks": {
        "core/heading": {
          "color": {
            "corePalette": true,
            "coreGradients": true
          }
        }
      }
    }
  }
```
 
Since the original `theme.json` from Gutenberg doesn't contain an explicit core palette for each block they by default would use the global one. But that doesn't exist anymore when you have opted out.

**Comment by oandregal** [comment]
@fabiankaegy that's a good point, thanks for bringing it up. We want to retain the cascade behavior. The other thing this approach makes harder to do is that we still want the classes and CSS custom properties for the core palette to be enqueued everywhere: even if the user does not use them, patterns still can.

So, I was thinking we need to approach it from a different direction. It sounds like we can still have the `corePalette` flag, but use it in the client instead. The `PanelColorGradientSettingsMultipleSelect` component ([see](https://github.com/WordPress/gutenberg/blob/fb476b0eb15463d580e7166a273d2e6d5b817583/packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js#L173)) would use the flag to pass an empty array for the core color flags.

Would you think you'd have the time to explore that approach instead?

**Comment by fabiankaegy** [comment]
@oandregal Yeah I think that approach makes more sense. I have created a follow up PR here: #36492

**Comment by oandregal** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/pull/36492

**Pull request closed without merging**
