### PR TITLE
Make Spacedmonkey a maintainer of PHP

### PR DESCRIPTION
**Pull request by spacedmonkey**
I wish to become a code maintainer of the PHP on the gutenberg plugin.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aduth — APPROVED** [review]

**Comment by TimothyBJacobs** [comment]
@aduth unless GitHub has changed something since when we added me, I think @spacedmonkey also needs to be added to the @WordPress/gutenberg team for it to work.

**Comment by aduth** [comment]
> @aduth unless GitHub has changed something since when we added me, I think @spacedmonkey also needs to be added to the @WordPress/gutenberg team for it to work.

Ah, right you are. @youknowriad , could you add @spacedmonkey as a member?

**Comment by aduth** [comment]
For posterity, the relevant reference:

>The people you choose as code owners must have write permissions for the repository.

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

**Comment by youknowriad** [comment]
Added ✅ welcome to the repo

**Pull request merged**
