### PR TITLE
Columns: Remove empty html render for columns block

### PR DESCRIPTION
**Pull request by Infinite-Null**
Part of : #63332

## What?
Prevents empty HTML markup generation for columns blocks that have no inner blocks.

## Why?
This PR addresses an edge case where columns block wrappers continue to render empty HTML markup on the website even after there is no inner block content.

## Testing Instructions
1. Create a new post.
2. Add a columns block.
3. Add an empty column block, and save.

View the post on the front, and view the source.

### Before patch

https://github.com/user-attachments/assets/b16f00fa-dbf5-4da8-87d2-c06b43fb05b9

### After patch

https://github.com/user-attachments/assets/eb54ecc9-394f-4ac0-946a-adf4e6a0f17a

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks for working on this, @Infinite-Null!

I left a [comment](https://github.com/WordPress/gutenberg/issues/63332#issuecomment-2488285206) on the issue. The main point is that storing the `isEmpty` flag in attributes isn't the "right" solution here. I think it should be resolved at the API level first.

Let's continue the discussion on the issue.

**Comment by Infinite-Null** [comment]
> Thanks for working on this, @Infinite-Null!
> 
> I left a [comment](https://github.com/WordPress/gutenberg/issues/63332#issuecomment-2488285206) on the issue. The main point is that storing the `isEmpty` flag in attributes isn't the "right" solution here. I think it should be resolved at the API level first.
> 
> Let's continue the discussion on the issue.

Hi @Mamaduka,
Thank you for pointing this out. The primary intention behind this approach was to pass a flag using an attribute, as I believed it would effectively indicate whether the blocks were empty. However, I’ll explore alternative methods to achieve this functionality. In the meantime, I will monitor and contribute to the discussions on the issue.

**Comment by Mamaduka** [comment]
@Infinite-Null, I think we can close this PR since we'll have to pursue a more general approach. See the issue for details.

**Comment by Infinite-Null** [comment]
> @Infinite-Null, I think we can close this PR since we'll have to pursue a more general approach. See the issue for details.

Sure @Mamaduka

**Pull request closed without merging**
