### PR TITLE
substate: Add package

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
This package is a fork of zustand plus one `useSubState` hook that is a dependency of G2.

Question is, should this just go into `compose`? Or can it stay as it's own package?

## How has this been tested?
Unused so build just has to pass.

## Types of changes
New feature/package

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! This fork was merged and released as part of `@wp-g2/*` v0.0.133
https://github.com/ItsJonQ/g2/releases/tag/v0.0.133

The `zustand` port was something @saramarcondes and I worked on together (mostly Sara. I just flailed around with TypeScript, haha)

---

> Question is, should this just go into compose? Or can it stay as it's own package?

That's a good question. I'm unsure. I'm okay with either, whichever one folks feel more comfortable.

**Review by youknowriad — COMMENTED** [review]
Ii believe the idea was to add this to the components package temporarily before refactoring to @wordpress/data wasn't it?

**Comment by ItsJonQ** [comment]
> Ii believe the idea was to add this to the components package temporarily before refactoring to @wordpress/data wasn't it?

(Context for others folks: There was a lot of discussion in the [original PR](https://github.com/WordPress/gutenberg/pull/27594))

---

@youknowriad Hmm! I'm unsure. Taking a step back, we used zustand for because...

1. Need state to exist as a singleton, which could be accessed without a Provider
2. Need state to be easily accessed/updated (rapidly) within component's sub-components
3. Need state to easily sync/resolve incoming prop state with internal state

These features aren't unique to `zustand`. They can be accomplished using `useState`, `useReducer`, and `useContext` (perhaps with the exception of 1. working without a Provider). However, the library certainly made it easier to write (at least for me).

The discussions swayed towards using something `useState`/`useReducer` or perhaps `@wordpress/stan`.

**I'm 100% open to refactoring towards a better solution + cleaner convention, but this will take time.**

---

> Ii believe the idea was to add this to the components package temporarily

This package is used across all of the other packages in the `@wp-g2` library. Because of that, it needs to be sharable.

If it were moved into `@wordpress/components`, it won't be accessible to other packages - unless all of the `@wp-g2/*` packages move into `@wordpress/components`.

---

> refactoring to @wordpress/data

Forgive my ignorance! I'm not sure how this relates to `@wordpress/data`. My understanding is that `@wordpress/data` is the primary data hub for all the things. The state management solution we need for the components need to be independent and instance based (more similar to `useReducer` than a global `Redux`).

---

☝️ That's my understanding of things. Hopefully this context helps on your side.

I'd love to know your thoughts on the best approaches for organization and dependencies to integrate the `@wp-g2` components (and all of their systems)

**Comment by youknowriad** [comment]
Hey thanks for the details @ItsJonQ I think the place where we are misaligned is the "packages". To put it clearly, I don't think we should be creating packages for G2 in Gutenberg, at least not in the beginning, I think we should just add everything in folders in the "components" package.

The reasons are simple:

 - A lot of these packages have duplicates spread across Gutenberg packages
 - Adding a packages involves a lot of maintenance cost, so we should do it carefully and use it consistently across the code base when possible. To detail on the maintenance cost: If we do like this PR does, the package becomes a public API and becomes an official NPM package, I believe at this point you know how hard it is to touch public APIs in the future.. It is possible to bundle packages by adding "exceptions" to the config of wp-scripts but it's not a great experience for WP users and plugins wanting to use these packages. So I'd prefer if we delay the decisions as much as we can.
 - Our main goal with the G2 projects is to introduce a components library, while having a modular architecture is awesome, I don't think we'd  be losing a lot by saying its modules are actually folders in the package to start with. Once G2 is well integrated in Gutenberg, we could make better decisions on the packages to extract.

Now for @wordpress/data and zustand, I was basing that on @jsnajdr's analyze on the previous PR. I'm fine keeping zustand if it doesn't duplicate what we already have but it's not what the comment suggested. And I believe we can start with it in "components" even if it's a duplication until we have more time to refactor or do something else.

**Comment by jsnajdr** [comment]
> The state management solution we need for the components need to be independent and instance based

I was envisioning usage of `@wordpress/data` that looks like this:
```js
import { createStore, useSelect, useDispatch } from "@wordpress/data";

const counterStore = createStore({
  reducer: (counter = 0, action) => action.type === "inc" ? counter + 1 : counter,
  selectors: { get: (state) => state },
  actions: { increment: () => ({ type: "inc" }) },
});

function Counter() {
  const counter = useSelect((select) => select(counterStore).get());
  const { increment } = useDispatch(counterStore);

  return <button onClick={increment}>{counter}++</button>;
}

ReactDOM.render(<Counter />, document.getElementById("root"));
```

Here we create a data store that's not registered in any global registry, doesn't have any unique string name, and doesn't need a global provider component. It's completely local to the module.

We are not there yet, and won't be there tomorrow or next week, but we already took some steps in that direction in the last 2 months. And the fact that the components package has a clear need for this should only accelerate that development.

With such a data store, the overlap with `zustand` is almost 100% and the performance tradeoffs are also almost the same.

For implementing lightweight stores like this, I think that finishing @adamziel's "async actions" proposal from https://github.com/WordPress/gutenberg/pull/27276 would be also very useful. It would make writing actions much more powerful, without having to learn the entire DSL of `redux-routine` controls.

**Comment by gziolo** [comment]
@saramarcondes, thank you for all the work put into G2 components so far. I wanted to echo what @youknowriad shared. We discussed it before and I had the feeling that we are focusing on moving the implementation of individual components for now and keep all lower-level packages as external dependencies of `@wordpress/components`.

> Hey thanks for the details @ItsJonQ I think the place where we are misaligned is the "packages". To put it clearly, I don't think we should be creating packages for G2 in Gutenberg, at least not in the beginning, I think we should just add everything in folders in the "components" package.

For some time it should be perfectly fine to keep those packages external. We are comfortable doing it for several well-established low-level libraries like `react`, `reakit`, `redux`, `emotion` but we also have some more higher-level libraries like `downshift`, `react-dates` or `react-spring`. I don't think why we should rush to moving those packages to Gutenberg. @youknowriad listed quite an extensive list of reasons why it's challenging at this stage of the project.

Regarding `zustand`, it should be fine as a temporary solution to fork it and make it friendly with Gutenberg's build process. In the long term, I would follow what @jsnajdr proposes. The idea is really compelling and plays along with how other state libraries shape their APIs these days.

**Comment by saramarcondes** [comment]
Sounds good to me y'all. I'll close this PR and open a PR for `Truncate`, depending on G2 as external libraries? @gziolo and @youknowriad just want to be clear about whether that's the correct next step for the `Text` component (`Truncate` is a dependency of it). Let me know if it's incorrect/if I'm still misunderstanding.

FWIW, @ItsJonQ and I have been working on removing zustand as a dependency. It seems to be possible using a combination of `useReducer` and `@wordpress/data` depending on the context. 

https://github.com/ItsJonQ/g2/pull/222
https://github.com/ItsJonQ/g2/pull/221
https://github.com/ItsJonQ/g2/pull/220

**Comment by gziolo** [comment]
Yes, we need to move UI components first. Let’s postpone work on dependant G2 packages until we have several UI components integrated into `@wordpress/components` and working as replacement for existing UI components.

**Pull request closed without merging**
