### PR TITLE
components: Remove wp-g2 fontsize control

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
Removes the wp-g2 font size control and reverts back to the previous implementation. This isn't permanent but gets us a step closer towards removing the wp-g2 dependencies in favor of vanilla emotion. See #30503 for the full plan and how this PR fits into it.

## How has this been tested?
Run Gutenberg and ensure that the font size controls work (for example on the Paragraph block).

## Screenshots 
Captura de Tela 2021-04-28 às 07 30 04

## Types of changes
Non-breaking change/wp-g2 removal.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
Nice 30% gain in the components package :)

**Review by youknowriad — APPROVED** [review]
I guess this is the last thing that was importing external `g2` components and that we could remove them now from package.json?

**Comment by sarayourfriend** [comment]
> components and that we could remove them now from package.json?

I was going to do it in a separate follow up PR 😁

**Comment by gziolo** [comment]
> Nice 30% gain in the components package :)

With -82.7 kB, we should be back to where we were before 😄 

From https://github.com/WordPress/gutenberg/pull/27594#issuecomment-742365468:

**Pull request merged**
