### PR TITLE
Nav offcanvas restore click to edit

### PR DESCRIPTION
**Pull request by getdave**
## What?

Removes the "edit" button for each node and allows clicking on a node to trigger "edit mode" for that block.

## Why?

See rationale in https://github.com/WordPress/gutenberg/issues/47023#issuecomment-1410148005.

Kudos to @talldan who [suggested this originally](https://github.com/WordPress/gutenberg/issues/47023#issuecomment-1378150821) and received push back 🙇‍♂️ 

## How?

- Remove dedicated edit button
- Reinstate click to edit behaviour
- Transfer a11y affordances to node
- ~Ensure only valid blocks are editable~ We decided it's better to allow all blocks to be editable and simply _imply_/hint that certain blocks are not editable via UI affordances. Ultimately if a user wants to check controls on Page List Items they should be able to. It's also better for a11y as it's more consistent to retain same behaviour across all nodes.

## Testing Instructions

- Nav block with menu that includes standard links _and_ a Page List.
- Hover over items and check there is no longer an "edit" button
- See that clicking on a node triggers edit mode.
- Test with screen reader that appropriate label is read out "Edit X".
- Test possible to edit via keyboard.
- Test possible to expand/collapse nodes without triggering edit.
- ~Test not possible to edit Page List Item blocks.~ No longer needed. See above.

## Screenshots or screencast 

https://user-images.githubusercontent.com/444434/215750185-a6c293cc-9864-4cf8-b79c-3fbc0b151e7c.mp4

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
I've tested this and now with the animation and the back button all my initial concerns are solved. The UI in the inspector predictably gets replaced with the details of the selected block, there is a small delay that does not flash the new UI in. All good.

The drag and drop functionality works perfectly unaffected by this change. And the code removes a lot of cruft for that edit button.

Great work @getdave and @talldan 👏🏻

**Comment by getdave** [comment]
Thanks @draganescu!

I'll wait to hear from @SaxonF and @talldan just in case there are any UX or other issues they foresaw (as the originators of the two approaches). Then we can merge.

**Comment by MaggieCabrera** [comment]
Sadly this isn't working for me :( this is a fresh install with just some dummy content

Screen Capture on 2023-01-31 at 13-11-08

**Review by scruffian — APPROVED** [review]
This looks great. My only concern is that focus should stay in the inspector, but that's nothing to do with this PR. 🚢

**Comment by draganescu** [comment]
@MaggieCabrera this is known. There used to be a check removed in [421f7ca](https://github.com/WordPress/gutenberg/pull/47608/commits/421f7ca95e212b8aa00a0897e1f77c573861cf78) as hardcoding that block name to avoid this behavior is likely not the way to go about it.

At the same time, the normal left hand list view also has this problem. In a page list selecting page list items in the canvas does not work, but it works using the list view.

So I think we should treat this as a bug of how locked blocks are handled by list view not a problem of this PR. What do you think?

**Comment by MaggieCabrera** [comment]
> So I think we should treat this as a bug of how locked blocks are handled by list view not a problem of this PR. What do you think?

yeah, I don't think that should block this PR

**Comment by draganescu** [comment]
@getdave could this PR get rid of the `selectBlockInCanvas` prop too? If we don't need the button we don't need this prop either (and the places where it is checked).

**Comment by scruffian** [comment]
Looks good, let's bring this in.

**Comment by SaxonF** [comment]
:shipit:

**Pull request merged**
