### PR TITLE
Consider more approachable copy for "Transform to"

### LINKED ISSUE #42202: Consider more approachable copy for "Transform to"
## What problem does this address?
"Transform" is a more technical/less approachable term. I know technically they're called block transforms, but perhaps we should make the copy more approachable, say something like "Turn into". 

It's a very small adaptation, but "Turn a paragraph into a heading" is much friendlier/approachable that "Transform a paragraph...". 

## What is your proposed solution?
Change "Transform to" to "Turn into":

CleanShot 2022-07-06 at 16 35 42@2x

### PR DESCRIPTION
**Pull request by jrtashjian**
Fixes #42202

## Screenshots or screencast 

Screenshot 2023-09-13 at 10 53 21 AM

### CODE REVIEW

**Comment by jasmussen** [comment]
I appreciate the attention to detail here. In principle I like the shorter "turn into", but it's also not a strong opinion on my part, I think the main question is whether the fact that it's been called "transform" for so long means the change will be disorienting. I don't think it will, and I'm happy to defer to a second sanity check.

**Comment by jameskoster** [comment]
+1 attention to detail, and thanks for the submission!

I wonder if 'turn' is a little ambiguous due to the definition overlap with 'rotate'. Obviously it's subjective but I associate 'turn' with _changing direction_, so it feels slightly out of place in this context. Especially if you think "`$label`: Block"... "Turn: Paragraph" doesn't really capture the behavior.

I like how explicit 'transform' is.

Other options could be:

* Swap
* Switch
* Convert
* Replace

But I'm not really convinced that any of those are better than 'Transform' to be honest.

**Comment by richtabor** [comment]
I'm 50/50 on this as well. 😅

**Comment by apeatling** [comment]
Transform seems pretty clear. I would personally have a slight preference for "Change into".

**Comment by jrtashjian** [comment]
We can close this if there is a consensus that no changes should be made.

I didn’t even notice the “needs copy review” label on the original issue, so I shouldn’t have submitted a PR for this. But hey, at least we have one less issue now! 😄

**Comment by apeatling** [comment]
Closing this one since I think consensus is that Transform is fine.

**Comment by jrtashjian** [comment]
I don't have the ability to, but we should close the associated issue (https://github.com/WordPress/gutenberg/issues/42202) as well.

**Pull request closed without merging**
