### PR TITLE
I18n: Strings that need context

### PR DESCRIPTION
**Pull request by dimadin**
## Description
Some strings (adjectives, imperatives, used in two places as different things...) need context to properly translate and avoid future conflicts.

In this PR, I list those strings that I've found, as well as my proposal for context text.

### CODE REVIEW

**Review by ctrlaltvikas — APPROVED** [review]

**Comment by Soean** [comment]
Thanks, this is really helpful for translation. 
We merged #10615 already. Can you solve this conflict, then we can merge this one too.

**Review by ajitbohra — APPROVED** [review]
LGTM :+1:

**Review by ocean90 — APPROVED** [review]

**Comment by ocean90** [comment]
Branch needs a rebase.

**Comment by gziolo** [comment]
@dimadin  can you merge this branch with changes from `master` so we could land this PR?

**Comment by dimadin** [comment]
@gziolo Done.

**Comment by gziolo** [comment]
Awesome, thanks! 🥇

**Comment by mtias** [comment]
Thanks for these!

**Pull request merged**
