### PR TITLE
Adjust the name of the custom field button labels

### LINKED ISSUE #47406: Consider renaming the Custom Fields Enable/Disable button labels
### Description

In Preferences > Panels > Custom Fields we have the option to toggle the custom fields so they are enabled or disabled.

disable and reload

But the label is misleading, because the custom fields values are always enabled and retrievable, whether or not they are visible from the page editor. See the below unit test to confirm this:

Adding a small php script to display the post id and value in the custom field, I have disabled (and reloaded) followed by refreshing the page again. 

[custom-fields-button-label.webm](https://user-images.githubusercontent.com/38789408/214501066-fd77b98d-9347-4ade-bd82-e54805c3905c.webm)

As you can see the custom field is always enabled, but what actually happens is that it is visible or not within the editor.

I have added a PR to rename Enable & Disable to Show and Hide, which accurately describes the behaviour.

hide and reload page

### Step-by-step reproduction instructions

1.  Add a small php script which includes some meta data for the unit test, enable the custom field and add a value
2. Go to Preferences > Panels > Custom Fields in the page editor
3. Disable and Reload the Custom Fields
4. Reload the page and see the meta data from the php snippet or template is still visible.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Wordpress 6.1.1 
Twenty Twenty Theme.
[custom-fields-button-label.webm](https://user-images.githubusercontent.com/38789408/214501066-fd77b98d-9347-4ade-bd82-e54805c3905c.webm)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by SavPhill**
The current button labels do not accurately describe the behaviour of the button, because the value of the custom fields are still retrievable whether or not the button is 'enabled' or 'disabled'.

Fixes #47406.

### CODE REVIEW

**Comment by Mamaduka** [comment]
@SavPhill, it looks like unit test snapshot needs an update. You can run following command in the Gutenberg plugin directory:

```
npm run test:unit -- packages/edit-post/src/components/preferences-modal/options/test/enable-custom-fields.js --updateSnapshot
```

**Comment by kristastevens** [comment]
Hello! Answering the copy review bat signal. 

Label renaming looks good to me. 👍

**Comment by SavPhill** [comment]
> @SavPhill, it looks like unit test snapshot needs an update. You can run following command in the Gutenberg plugin directory:
> 
> ```
> npm run test:unit -- packages/edit-post/src/components/preferences-modal/options/test/enable-custom-fields.js --updateSnapshot
> ```

Thank you. I received `sh: wp-scripts: command not found` when I ran this in the directory. Can you provide any documentation to help me to fix this PR?

**Review by Mamaduka — CHANGES_REQUESTED** [review]
@SavPhill, the unit tests are still failing. We'll need to fix any test failures before merging the code.

**Comment by SavPhill** [comment]
> @SavPhill, the unit tests are still failing. We'll need to fix any test failures before merging the code.

I have updated the Snapshot to match.

**Review by Mamaduka — APPROVED** [review]
Thank you, @SavPhill!

**Pull request merged**
