### PR TITLE
Revert "Fix/media library collections #4612 (#10843)"

### PR DESCRIPTION
**Pull request by youknowriad**
We noticed an e2e test failure on travis (master) after this PR #10843 got merged. I'm trying to revert here to see if it's any better.

### CODE REVIEW

**Comment by youknowriad** [comment]
@gziolo Inline images uses the media library, It's certainly related.

**Comment by youknowriad** [comment]
So the tests are passing here, I'm going to merge the revert to unblock the other PRs for now.

**Comment by gziolo** [comment]
It was passing in #10843, too 🤷‍♂️

**Comment by youknowriad** [comment]
@gziolo Yes, I know probably but the build was old so probably a mix with the PR and another recent change.

**Pull request merged**
