### PR TITLE
Block edit: avoid memoized block context in favour of useSelect

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Ideally the only piece of context is the block client ID and everything else is derived from that. Unfortunately `useBlockEditContext` is exported at the package level (not sure why because it's only used within the package), but it can be rewritten with `useSelect`.

After this we should create a new hook to only return the client ID, but I ran into some errors there which I'm trying to pinpoint. Doing this step by step instead.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
I run into this PR when investigating failing tests in #28456. I have some concerns regarding the changes proposed in this PR. It feels like the `useSelect` call isn't necessary because all the necessary data can be passed down from the `BlockEdit` component because everything is already available there. It also looks like performance tests confirm my assumption as you can notice some negative impact on the results:

Screen Shot 2021-03-05 at 18 17 15

**Comment by ellatrix** [comment]
Cc @youknowriad

I'll investigate the performance problem. Generally we should avoid passing data down that can be derived from something else like the client ID. Where do we draw the line? You could pass lots of data like the block type, other selection info... through memoized context. Our data API should be a superior way to retrieve and memoize data only in places where it's needed.

**Comment by ellatrix** [comment]
Worth noting that #29309 deprecates the hook in favour of a new one, which restores performance to previous levels. The PR is blocked by mobile though, which is why it was done it multiple pieces.

**Comment by ellatrix** [comment]
I believe the temporary performance hit is due to some extra `useSelect` and selector calls while waiting for #29309, which reduces to select calls to only the places where it's needed.

**Comment by talldan** [comment]
This is also breaking the navigation editor. The block inspector is now not showing any of the UI we're adding through filters:
Screenshot 2021-03-08 at 3 25 12 pm

Please can we stop merging these unreviewed PRs? By my count that's the third major regression in a week caused by these kind of PRs.

**Comment by youknowriad** [comment]
I agree that the performance gap here is too big to ignore. While I agree on the principle that the selectors should  only be called when needed, I  think the `BlockListBlock` is the special case in our application since it's the bottleneck, it's the only component that should be over optimized in which I prefer performance over devx considerations.

**Comment by talldan** [comment]
Looking into it some more, this isn't an issue with filters, but the `InspectorControls` component doesn't seem to be rendering anything. This is the affected component:
https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-navigation/src/components/inspector-additions/index.js#L13-L29

Can we revert this? The regression is currently blocking a few PRs.

**Comment by youknowriad** [comment]
> Can we revert this? The regression is currently blocking a few PRs.

This makes sense too me, it's a small PR that we can bring back if we figure out the issues.

**Comment by gziolo** [comment]
> I'll investigate the performance problem. Generally we should avoid passing data down that can be derived from something else like the client ID. Where do we draw the line? You could pass lots of data like the block type, other selection info... through memoized context. Our data API should be a superior way to retrieve and memoize data only in places where it's needed.

I contemplated a bit more about this proposal. If you look at it only from the performance perspective, it can’t be more performant than keeping `isSelected` or `name` in the context. While using the `clientId` to source everything else makes a lot of sense, in this case, it always needs to do another read to get those values from the store. In addition to that, whenever the store changes it will have to recompute those values. At the same time, the context changes only when the block gets selected/unselected or removed/added/replaced. It's a huge challenge to find the most optimal solution here.

**Pull request merged**
