### PR TITLE
Update the document title in the template mode of the post editor

### PR DESCRIPTION
**Pull request by youknowriad**
Related #50378 

## What?

This PR updates the design of the "title bar" in the "template mode" of the post editor to match the new design in the site editor. 

I considered whether I should be showing the title bar in the "regular mode" of the post editor too with the current post/page but because of the implications on the "top toolbar", I decided to leave this for a separate PR. Let me know what you think here?

## Testing Instructions

1- Open the post editor
2- Click on the "template -> edit" from the document sidebar.
3- Notice the new design of the "title bar".

### CODE REVIEW

**Comment by jameskoster** [comment]
It's working for me 👍 

Would now be a good time to consider adding the `< Back` affordance to the document title? Probably fine to handle separately, I only bring it up as the current title element includes one, and this PR will eliminate that.

Edit: Noticed a styling issue in the site editor – the background has disappeared:

Screenshot 2023-05-23 at 10 44 08

**Comment by youknowriad** [comment]
Fixed the small issues and I added the back button.

**Comment by jameskoster** [comment]
The issue in the Site Editor is fixed, thanks.

The back button... :)

* Could the label be the post/page title rather than "Back"? We'll need to truncate, but if we can include the first few characters it should be ok.
* The back button and keyboard hint need to have the save width to keep the title centrally aligned.
* The interaction feels a bit off... It might work a bit better with a background change on hover:

back2


If you prefer to add this button in a dedicated PR it's probably fine xD

**Comment by youknowriad** [comment]
Some e2e tests are failing and it looks like this PR removes the possibility to edit the "template title" from the post editor, are we ok with that?

**Comment by jameskoster** [comment]
> removes the possibility to edit the "template title" from the post editor, are we ok with that?

I think it's okay. We can probably surface renaming as a suggestion in the command palette (https://github.com/WordPress/gutenberg/issues/50407).

**Comment by youknowriad** [comment]
Ok this is ready for a final review. It removes two features from the "template mode" of the site editor:

 - No possibility to delete custom templates from there.
 - No possibility to "revert template customizations" from there.

**Comment by jasmussen** [comment]
Quick GIF:

test

Nice work, looks close! One thing, only templates or template parts should have the purple color for the text. Pages and content should be gray-700.

Probably related to the command bar itself, but the "delete template" suggested action feels way too prominent. Probably discussed separately, but it being surfaced here, even focused by default, makes it feel too easy to press ⌘K + Enter and have the template deleted.

We can probably be a bit smarter on the mobile breakpoints than just taking up the available space:

Screenshot 2023-05-30 at 10 29 52

Screenshot 2023-05-30 at 10 29 57

But that's working reasonably well at the moment, so I don't think it should block anything. We can also adjust the designs if need be.

**Comment by youknowriad** [comment]
@jasmussen this PR doesn't touch the site editor, it's about the "template mode" in the post editor instead.

**Comment by jasmussen** [comment]
Ah, my mistake. Looks good:

edit template

A few small things, which are potentially also unrelated to this PR:

Screenshot 2023-05-30 at 11 07 55

The active state for the button has a black icon.

Screenshot 2023-05-30 at 11 08 02

Screenshot 2023-05-30 at 11 08 07

It would be a nice polish enhancements to ensure that the button focus for these two go to the edge of the gray box. Potentially remove the inner left/right padding and rely just on the buttons themselves.

Screenshot 2023-05-30 at 11 08 13

The spacing between chevron and "Back" could be smaller. I wonder if this is a result of the icon button default spacing, in which case we might want to discuss this in a more systematic way.

Screenshot 2023-05-30 at 11 09 02

Probably the best thing about this PR, we can remove the "Back" button in the canvas! Can we?

**Comment by youknowriad** [comment]
Thanks for the review. I've updated the spacing metrics and removed the old "back" button.

**Review by jasmussen — APPROVED** [review]
Tentative approval, could use a code sanity check. Nice PR, big improvement.

One thing to still fix, the page icon is still black when you're clicking the command bar. In case it's separate, okay to fix separately, just like applying the purple only to templates and tps.

**Pull request merged**
