### PR TITLE
Modules API: Script Modules add deregister option.

### PR DESCRIPTION
**Pull request by cbravobernal**
## What?

Syncs https://github.com/WordPress/wordpress-develop/pull/6061 in Gutenberg, to be compatible with WordPress < 6.5
Updates the patch for loading Gutenberg Interactivity API script module instead of Core one.

## Why?

Consistency with `wp_deregister_style` or `wp_deregister_script`. To be able to override script modules.

## Testing Instructions

Gutenberg version of Interactivity API should be loaded in WP 6.4, 6.5 with this PR merged.

### CODE REVIEW

**Review by westonruter — APPROVED** [review]
LGTM

**Comment by SantosGuillamot** [comment]
Do we need a backport label for this PR?

**Comment by swissspidy** [comment]
> Do we need a backport label for this PR?

No, because this brings a change from core to Gutenberg.

**Comment by youknowriad** [comment]
I've added the backport label to make sure this code is also in wp/6.5 branch.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-beta-2 branch to get it included in the next release: 1605148151

**Pull request merged**
