### PR TITLE
Update the position of the patterns tab in the inserter menu

### LINKED ISSUE #47113: Accessibility: WCAG violation by different order of Blocks & Patterns in block inserter in Post- and Site-Editor
### Description

As reported in core https://core.trac.wordpress.org/ticket/57431 and advised to report it here.
(And please don't play "not right located here" tennis!)

### Step-by-step reproduction instructions

In the block inserter of the post-editor are tabs ordered: Blocks - Patterns
In the block inserter of the site-editor are tabs ordered: Patterns - Blocks

It is confusing (and very bad UI design) for ALL users, when parts in the - expectable - same user interface change places.

And it is a direct violation of the "Web Content Accessibility Guidelines"
=> "Make Web pages appear and operate in predictable ways"
https://www.w3.org/TR/WCAG21/#consistent-navigation

### Screenshots, screen recording, code snippet

_No response_

### Environment info

WP 6.1.1
with and without Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

In the block inserter menu, which can be opened from the "Toggle block inserter" button in the toolbar in the editors,
blocks, patterns and media are displayed as tabs. The order of the tabs were different on different screens; the first tab would show blocks on some screens, and patterns when editing templates.

This PR aims to change the order so that the order is the same in the editors:
1 ) Blocks 2) Patterns 3) Media.

Closes https://github.com/WordPress/gutenberg/issues/47113

## Why?

The inconsistent order may be confusing. Please see more details in the issue.

## How?

The PR removes the "prioritizePatterns" prop and the condition that was used to place the patterns tab before the blocks.
The condition is no longer needed since the order of the tabs should be the same.

## Testing Instructions

**Classic theme:**
Please open the block inserter menu and confirm the order of the tabs on the following screens:
WordPress admin > Posts /Pages > Add new
WordPress admin > Widgets: Confirm that this screen is unchanged and does not show patterns in the tab.
Create or select a user-created block pattern. Test the inserter menu on the pattern creation screen.

**After activating a block theme:**
Please open the block inserter menu and confirm the order of the tabs on the following screens:

1. WordPress admin > Posts /Pages > Add new
2. WordPress admin > Appearance > Editor  > Pages > Open any page which is not also a template
3. WordPress admin > Appearance > Editor > Templates > Open any template
4. WordPress admin > Appearance > Editor + **Click on the main preview window** Select a template part. Select edit in the template part toolbar, to open the "template part editor".
5. WordPress admin > Appearance > Editor > Patterns: Create or select a user-created pattern and test the pattern creation screen.

### Testing Instructions for Keyboard
With a block theme active, create a new post or page.
Inside the Editor top bar region, navigate past the "View posts" link.
Inside the document tools toolbar, activate the button with the aria-label "Toggle block inserter" (The plus icon).
Navigate past the search input field.

With a screen reader, 
"Blocks" should be announced as tab 1 of 3.  Use the right arrow key to select the next tab.
"Patterns" should be announced as tab 2 of 3. Use the right arrow key to select the next tab.
"Media" should tab 3 of 3.

Next please do the same test when editing a block template.
Go to WordPress admin, open the Appearance menu, select Editor, and next, select Templates.
Chose any template in the list, press the Enter key to open that template in the editor.
With the template open, navigate to the tabs in the block inserter menu again and confirm that the tab order is the same:
Blocks, patterns media.

### CODE REVIEW

**Comment by talldan** [comment]
Not sure if this one is ready for review, but I still see a few places where `prioritizePatterns` is passed to `InserterMenu`. (`InserterLibrary` (`packages/block-editor/src/components/inserter/library.js`), and `PrivateInserter` (`packages/block-editor/src/components/inserter/index.js`)).

I guess they won't do anything now so can be removed.

I'm not really sure what should be done about the quick inserter, which also has a similar prop. In testing I struggled to get it to trigger, as the sibling inserter doesn't seem to be visible (is that a bug or a feature?).

**Comment by carolinan** [comment]
> Not sure if this one is ready for review, but I still see a few places where `prioritizePatterns` is passed to `InserterMenu`. (`InserterLibrary` (`packages/block-editor/src/components/inserter/library.js`), and `PrivateInserter` (`packages/block-editor/src/components/inserter/index.js`)).
> 
> I guess they won't do anything now so can be removed.

Thank you, I have removed them.

> I'm not really sure what should be done about the quick inserter, which also has a similar prop. In testing I struggled to get it to trigger, as the sibling inserter doesn't seem to be visible (is that a bug or a feature?).

I did not understand. What does not trigger in the quick inserter?

**Comment by talldan** [comment]
> I did not understand. What does not trigger in the quick inserter?

I struggled to get the root level quick or sibling inserter to show at all in some templates because there's no gap between the blocks.

It's easier if you're in a blank template though. I did a screen capture of what I was concerned about below. If you trigger the quick inserter at root level in the site editor, it shows patterns by default, but 'Browse All' still takes you to blocks (and I think it should possibly open the patterns tab). This experience is a bit disjointed, so maybe it needs more design feedback (cc @richtabor):

https://github.com/WordPress/gutenberg/assets/677833/9ae378cb-c403-4c13-af27-fc388e86ab01

**Comment by carolinan** [comment]
I actually find it annoying that only patterns show in the quick inserter 😅 I still haven't developed a habit to use `/`

**Comment by richtabor** [comment]
> This experience is a bit disjointed

As we continue consolidating the site and post editor experiences, I'm in favor of having block and pattern insertion flows 1:1 across both experiences. I'd say the same for the quick inserter on both editors as well, having both surface blocks. 

Surfacing patterns is important, but not by simply replacing blocks with patterns. Rather by exploring pattern-specific flows, such as a top-level dedicated inserter that indicates pattern insertion, which opens the patterns tab. 

Something dedicated along these lines perhaps (a separate exploration):

https://github.com/WordPress/gutenberg/assets/1813435/27e8752a-b7d3-4cd2-99ef-9a1d8fcb3d06

I'd like input from others as well @WordPress/gutenberg-design.

**Comment by carolinan** [comment]
Hi @talldan @richtabor What is the status of this PR? :)
Should I remove the patterns from the quick inserter, or can that be a separate PR?

**Comment by richtabor** [comment]
> Should I remove the patterns from the quick inserter, or can that be a separate PR?

I would say a separate PR.

**Comment by richtabor** [comment]
@WordPress/gutenberg-design what do you think here?

**Comment by SaxonF** [comment]
Looks good to me. I like the consistency and agree the quick inserter can be treated as a separate issue. :shipit:

**Review by talldan — APPROVED** [review]
Code looks good and the change is testing well 🎉

**Pull request merged**
