### PR TITLE
Experimental PR for running an Android emulator

### PR DESCRIPTION
**Pull request by hypest**
## Description
Draft PR to try out some options for running an Android emulator to host the native mobile UI tests.

## Types of changes
1. Using https://github.com/marketplace/actions/android-emulator-runner that sets up an Android Emulator on a macOS VM on GitHub's infra
2. Added a custom method for taking screenshots at the end of each test and keeping only the ones for failed tests

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by hypest** [comment]
🎉 Looks like all but 3 of the Appium tests pass successfully inside the headless Android emulator. See log for 1517059 starting here: https://github.com/WordPress/gutenberg/runs/561119264?check_suite_focus=true#step:3:719
This at least shows that the setup is workable, to have Android UI tests run on the Gutenberg repo without any external services.

It also looks like the Appium tests run 2.5x slower than on SauceLabs (the service used from the gutenberg-mobile repo). Took ~16mins here while the same tests take ~6mins [in gutenberg-mobile](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/30898#build-timing/containers/0).

**Comment by hypest** [comment]
Only [1 test failing](https://github.com/WordPress/gutenberg/runs/561242212?check_suite_focus=true#step:3:333) on API 28.

**Comment by gziolo** [comment]
@hypest do you plan to play more with this branch or can it be closed? It’s quite old.

**Comment by hypest** [comment]
Ah, we actually incorporated most of the good parts of this PR so, it's fine to close, thanks for the nudge @gziolo!

**Pull request closed without merging**
