### PR TITLE
Automated Testing: Try composer non-interactive flag for Travis

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to attempt to resolve rate-limit errors which have become increasingly common in Travis builds lately:

- https://travis-ci.com/github/WordPress/gutenberg/jobs/301962702
- https://travis-ci.com/github/WordPress/gutenberg/jobs/301931757
- https://travis-ci.com/github/WordPress/gutenberg/jobs/301903064
- https://travis-ci.com/github/WordPress/gutenberg/jobs/301838013
- https://travis-ci.com/github/WordPress/gutenberg/jobs/301837884

>GitHub API limit (0 calls/hr) is exhausted, could not fetch https://api.github.com/repos/composer/installers/zipball/cfcca6b1b60bc4974324efb5783c13dca6932b5b. Create a GitHub OAuth token to go over the API rate limit. You can also wait until ? for the rate limit to reset.

It's unclear what is causing this to suddenly become an issue. There are related discussions which seem to imply that there should be no rate limit ([example](https://github.com/composer/composer/issues/4884#issuecomment-195229989)). The messaging in the error itself is also rather nonsensical ("0 calls/hr" limit, "wait until ? for the rate limit to reset"). It may in-fact be an issue of either Travis and/or GitHub.

The proposed changes are based upon the advice at https://github.com/composer/composer/issues/1314#issuecomment-10266196 . Notably, this changes the behavior to fall back on a clone fallback if unable to fetch the composer dependencies ([source](https://github.com/composer/composer/blob/7e679656a4a847f49b06a5ca3117e67223591063/src/Composer/Repository/Vcs/GitHubDriver.php#L429-L431)). As implemented here, this can also be provided as an environment variable `COMPOSER_NO_INTERACTION` (https://github.com/composer/composer/commit/83ea90296e001c3df6f1eb9933db65c1d45a1b37). Generally speaking, it is sensible that we would configure Travis builds to run commands in a non-interactive mode when available.

**Testing Instructions:**

If build history is any indication, the changes here can be assumed to be effective if the build merely passes.

### CODE REVIEW

**Comment by aduth** [comment]
Well, that didn't seem to help...

**Comment by aduth** [comment]
Not sure if the environment variable wasn't being picked up for one reason or another. The result is a bit different when passing the flag (`--no-interaction`) directly, although still failing:

```
  - Installing composer/installers (v1.6.0): Downloading (0%)    Failed to download composer/installers from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing composer/installers (v1.6.0): Cloning cfcca6b1b6
                                                                                                                                   
  [RuntimeException]                                                                                                               
  Failed to clone https://github.com/composer/installers.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                                   
  sh: 1: git: not found                                                                                                            
```

It seems clearer by this that it's falling back to source as expected, but presumably because the Docker image doesn't have `git` installed, it can't clone the source. 

I'm not entirely sure, but since this setup process still [uses the WordPress-based `env` setup](https://github.com/WordPress/gutenberg/blob/0bea8edff62bed3daa94e7fc5a65793a9a3d262b/.travis.yml#L94) and that [`docker-compose.yml` configuration](https://github.com/WordPress/wordpress-develop/blob/master/docker-compose.yml) resides outside the repository, it might be a little less direct to try to make Git available.

**Comment by noisysocks** [comment]
Thanks for starting to investigate this @aduth!

I think passing `--no-interactive` is the right thing to do here since, regardless of whether it fixes the issue, composer is operating in an environment where terminal input is not possible.

It definitely looks like we're exceeding the GitHub API rate limit which, according to [their docs](https://developer.github.com/v3/#rate-limiting), is a very paltry 60 requests per hour for unauthenticated requests. 

I tried creating a GitHub API token and having composer use it by setting the [`COMPOSER_AUTH` environment variable](https://getcomposer.org/doc/03-cli.md#composer-auth) in Gutenberg's Travis CI settings. This made the 'PHP unit tests' job succeed but for some reason it did not help with the 'PHP unit tests (PHP 5.6)' job. I tried a few different ways of passing this token but eventually gave up. 

Instead I went with your suggestion to simply provide `--no-interactive` and rely on composer building packages from source when it is unable to make requests to GitHub. As you noted, this was failing because `git` is not installed in the image that we're using to run `composer`. Fortunately, we're using `wordpressdevelop:latest` for this which is an image that WordPress controls, so I was able to fix this by adding git to the relevant images in https://github.com/WordPress/wpdev-docker-images/pull/23.

After merging https://github.com/WordPress/wpdev-docker-images/pull/23 and waiting for the new images to be published, I re-ran the jobs on this PR and everytihng looks ✅  again.

**Review by noisysocks — APPROVED** [review]

**Comment by aduth** [comment]
Thanks for the work in seeing this through, @noisysocks ! The outcome seems quite sensible to me, and regardless [whether we should be expecting to be hitting a rate limit](https://github.com/composer/composer/issues/4884#issuecomment-195229989), having the additional redundancy in our build should prove valuable.

**Pull request merged**
