### PR TITLE
Fix focus rectangle regression

### PR DESCRIPTION
**Pull request by jasmussen**
This PR fixes a focus rectangle regression I introduced in a previous commit. In doing so, it's also starting work on #904. More work will need to be done, I suspect, and designs tuned, but this PR improves things.

### CODE REVIEW

**Comment by aduth** [comment]
What are testing instructions?

**Comment by iseulde** [comment]
@joen Looks great. I'm getting two rectangles for toolbar buttons:

screenshot 2017-06-01 15 00 35

**Comment by jasmussen** [comment]
I've updated this PR and now it should be good to review:

- Tab through toolbar and sidebar items, verify there's a focus outline.

**Comment by iseulde** [comment]
@jasmussen I'm still seeing two lines. Is this intended?

screenshot 2017-06-02 20 31 54

**Review by ellatrix — APPROVED** [review]
Looks great!

**Pull request merged**
