### PR TITLE
Update shortcut docs with new block navigation menu shortcut

### PR DESCRIPTION
**Pull request by talldan**
## Description
Updates the docs with the shortcut added in #10545

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Thanks! 🚢

**Comment by mtias** [comment]
Are we including this in the modal too?

**Comment by youknowriad** [comment]
@mtias yes, I was not aware of the existence of these docs :)

**Comment by talldan** [comment]
Yep, the modal was updated in #10545. This replicates it in the docs too.

**Pull request merged**
