### PR TITLE
Rename blocks.query as blocks.source

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to rename the blocks export containing sources from `query` to `source`. Previously these were referred to as matchers in documentation. The `query` name has caused trouble since the export is commonly destructured and contains `query` as an available matcher (`wp.blocks.query.query`), i.e.

```js
// Before:
import { query as hpq } from 'blocks';
const { query } = hpq;

// After:
import { source } from 'blocks';
const { query } = source;
```

Alternative name considered was `source`. Open for discussion.

See also: http://gutenberg-devdoc.surge.sh/reference/attribute-sources/

__Testing instructions:__

There should be no functional changes with this branch.

Verify that tests pass:

```
npm test
```

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]
Much better. :)

**Comment by jasmussen** [comment]
Should we merge? ;)

**Comment by aduth** [comment]
@jasmussen It might need a rebase in case there are new additions of the old `query` property, but I'm okay to merge this whenever. The issue is that this is a breaking change particularly affecting any developers who have in-progress blocks, so might be worth highlighting in change notes for the release it's included within.

**Comment by jasmussen** [comment]
> It might need a rebase in case there are new additions of the old query property, but I'm okay to merge this whenever. The issue is that this is a breaking change particularly affecting any developers who have in-progress blocks, so might be worth highlighting in change notes for the release it's included within.

I trust you completely, I didn't mean to hurry you or anything. I just saw an approved but unmerged branch with a green button, and wanted to make sure it hadn't been forgotten. My apologies, as you were!

**Comment by mtias** [comment]
@aduth I've been sitting on this one, and I am having a slightly bigger inclination for using `source` instead of `matchers`. What do you think?

**Comment by aduth** [comment]
I don't have a particularly strong preference either way. "source" is a little ambiguous as to whether it's as a noun or a verb (the source, to source).

Also has an impact on #1905, e.g.

```
// Before
{ attributes: { number: { matcher: attr( 'div', 'data-number' ) } } }

// After
{ attributes: { number: { source: attr( 'div', 'data-number' ) } } }
```

In that light, `source` is a fair bit nicer, and could potentially extend better to server-provided values.

**Comment by westonruter** [comment]
I like `source` much more than `matcher`. It makes more sense to me.

**Comment by aduth** [comment]
Rebased to resolve conflicts, update new blocks, change to `source`.

Previously: bab0067fa0d62b9a7ebcc9349f299cbfdbba4db0

**Comment by iseulde** [comment]
Hm, this broke paste. :/

**Pull request merged**
