### PR TITLE
E2E Test Utils: Don't use hardcoded login credentials

### LINKED ISSUE #42761: SetNonce defaulting to admin and password as credential.
### Description

The setNonce function in rest-api.js, is making a login fetch request with defaulted credentials. Because of which we wish to run test on an environment where we don't have such user, the tests are failing.

### Step-by-step reproduction instructions

run the command in the following sequence.
1. Run a wordpress environment, serving on the hostname 'localhost:8080'
2. Make sure there is no user with name admin and password in the above environment.
3. run wp-scripts test-e2e command with login credentials passed as environment variable.
`WP_BASE_URL=http://localhost:80  WP_USERNAME=admin_1  WP_PASSWORD=password_1 wp-scripts test-e2e`

### Screenshots, screen recording, code snippet

image

### Environment info

- Wordpress v6.01
- e2e-test-utils v7.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #42761.

PR updates the `login` method for the REST API utils to use username and password from config.

## Testing Instructions
E2E tests are passing on CI

Locally tested by using widget tests, the helper method in this test uses the `rest` util function.

```
npm run test:e2e -- packages/e2e-tests/specs/widgets/editing-widgets.test.js
```

### CODE REVIEW

**Review by kevin940726 — COMMENTED** [review]
Note that many of our tests actually need this admin user to get the maximum permissions (see `switchUserToAdmin`). We probably also want Rest APIs to have the admin permission in order to make some requests too. I thought it's a requirement for our e2e tests? I'm not sure 🤔

**Comment by Mamaduka** [comment]
You're correct, and this doesn't change the default behavior. We do the same in `loginUser` helper - https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-test-utils/src/login-user.js.

The change will allow developers to use different usernames or passwords [from their setups](https://developer.wordpress.org/block-editor/contributors/code/getting-started-with-code-contribution/#using-local-or-mamp).

**Comment by Mamaduka** [comment]
@kevin940726, let me know if this PR needs any follow-ups.

**Review by kevin940726 — APPROVED** [review]
Thanks!

**Comment by kevin940726** [comment]
Not sure if it needs an entry in the changelog?

**Comment by Mamaduka** [comment]
I will add the changelog entry, just in case 👍

**Pull request merged**
