### PR TITLE
Fix Site Tagline block's text alignment

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
This PR fixes `Site Tagline` block's text alignment. It also adds a small description to the block.

Captura de ecrã 2020-10-20, às 16 57 56

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]

**Review by obi2020 — COMMENTED** [review]
Copy appears unchanged from current. I wouldn't recommend changes without more context or review at all copy on the screen (or in Site profile section) as a whole

**Comment by mcsf** [comment]
> Copy appears unchanged from current.

Hi. Can you further explain? Which copy, and unchanged from which current?

**Comment by obi2020** [comment]
Below is what I see in production. The description copy for Site tagline is the same as what is up for review here, as far as I can tell.

site tagline desc

Forgive me if I'm missing something. I'm responding to the "needs copy review" tag and dropping into this without much context. The copy is fine for the goal of this PR, but if you want to focus on improving it I would suggest looking at all copy in that section as a whole.

**Comment by ntsekouras** [comment]
>The description copy for Site tagline is the same as what is up for review here, as far as I can tell.

Exactly.

>The copy is fine for the goal of this PR, but if you want to focus on improving it I would suggest looking at all copy in that section as a whole.

It wasn't the goal to create a new one, but wanted to be sure that it's okay. Thanks for taking the time looking at this @obi2020 !

**Comment by mcsf** [comment]
Thanks for clarifying, @obi2020. That screenshot, however, is from Calypso (the project name for the dashboard used specifically in WordPress.com) and not Gutenberg (the block editor available as a plugin, used in WordPress core and WordPress.com alike). 

What this pull request did was adding a description for the Site Tagline **block**, which will be displayed inside Gutenberg, and not the Site Tagline **setting field** in Calypso. Indeed, we reused the description that you were already familiar with in a different interface.

**Comment by obi2020** [comment]
@mcsf thanks for the notes. I think in this case it's okay to proceed with the copy as is. If you want to prioritize improving it, it would be great to have more context, like screenshots. Ideally, impactful copy decisions happen in the design phase

**Comment by mcsf** [comment]
Agreed, and duly noted. Thanks for that!

**Comment by mcsf** [comment]
> would be great to have more context, like screenshots

I've attached a screenshot to the PR description, for future reference.

**Pull request merged**
