### PR TITLE
Block card: Fix typographic widow.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

Fix a typographic widow — a terrible typographical term for a word that stands alone on a line — in the block card.

## Why?

This balances the text to be harmonious, while working across translations. It is already applied by default to the `Text` component.

## How?

By applying `text-wrap: pretty;`.

## Testing Instructions

* Use english locale.
* Insert an image, select it.
* Observe the block card in the top of the inspector. The last line should read: "visual statement."

## Screenshots or screencast 

Before:

before

After:

after

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
If we need to apply `text-wrap: pretty` to this part, doesn't that mean we need to follow Gutenberg's typography system, which means replacing it with a `Text` component?

```javascript
<Text className="block-editor-block-card__description">
	{ description }
</Text>
```

For example, the site editor template description already uses this component.

template-sidebar

However, this component has a zero margin applied, so it will override the 4px (`$grid-unit-05`) top margin.

To solve this, how about using padding instead of margin, or changing the card content itself to a stacked layout and applying gap?

**Comment by jameskoster** [comment]
While we're at it we should fix this 🙈 

Screenshot 2024-05-07 at 14 28 52

Seems to be caused by `word-break: break-all` which is applied when `numberOfLines` + `truncate` is used. Not sure why, potentially an oversight. 

Edit: Nevermind, this seems to be fixed by https://github.com/WordPress/gutenberg/pull/61137.

**Comment by jasmussen** [comment]
Good feedback. Uses Text and VStack now, and looks good:

Screenshot 2024-05-08 at 09 30 40

**Review by t-hamano — APPROVED** [review]
LGTM 👍

**Comment by jasmussen** [comment]
Looks like I need to fix some tests. I'll do that when I get a moment! Thanks for the advice and reviews.

**Comment by t-hamano** [comment]
Sorry, we should have left the class name. It should now pass the E2E test.

**Comment by jasmussen** [comment]
Looks like there's a new failing test. I can look again at a different time, but have to move on to other things. If any of you want to, feel free to push changes, otherwise I'll get back to it when I can!

**Comment by t-hamano** [comment]
@jasmussen I've fixed the code so that it passes the e2e tests, and I updated this branch with the latest trunk just to be sure. Once GitHub Actions passes, I should be able to merge this PR.

**Comment by jasmussen** [comment]
Want to merge or should I press the button? Thanks again.

**Pull request merged**
