### PR TITLE
Print all variables - fix #28581

### LINKED ISSUE #28581: Global styles CSS-variables don't apply to the iframe in site-editor
## Description
When in the site-editor using an FSE theme, I can see that the CSS-variables get generated properly but they are applied to the main `:root` element. The problem is that they don't get applied to the root element inside the `iframe`, and as a result themes appear broken/unstyled.

## Step-by-step reproduction instructions
1. Install and activate the Q theme from its github repo: https://github.com/aristath/q - The theme.json file has already been updated to accommodate the latest structural changes.
2. Visit the site-editor.

## Expected behaviour
CSS-variables should be applied to the `iframe` and not the root element.

## Actual behaviour
CSS-variables get applied to the root element and the `iframe` does not inherit them.

## WordPress information
- WordPress version: **5.6**
- Gutenberg version: **Master branch** (currently https://github.com/WordPress/gutenberg/tree/502f79a6e0aa65c68562efade58aadc7ab334d4b)
- Are all plugins except Gutenberg deactivated? **Yes**
- Are you using a default theme (e.g. Twenty Twenty-One)? **No**

## Device information
- Device: Desktop
- Operating system: Pop!_OS (basically Ubuntu)
- Browser: Firefox & Chrome

### PR DESCRIPTION
**Pull request by aristath**
## Description
Fixes #28581 - global styles not getting added in the site editor.

## How has this been tested?
See instructions in #28581 

## Types of changes

Removed the conditions so css-variables are always printed.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] ~~My code follows the accessibility standards.~~ 
- [ ] ~~My code has proper inline documentation.~~ 
- [ ] ~~I've included developer documentation if appropriate.~~ 
- [ ] ~~I've updated all React Native files affected by any refactorings/renamings in this PR.~~

### CODE REVIEW

**Comment by aristath** [comment]
cc @gziolo @carolinan @jasmussen

**Comment by gziolo** [comment]
I think @nosolosw and @ellatrix would be the best people to validate this change 😄

**Comment by jasmussen** [comment]
Thanks for working on this! Am I correct in understanding that this is aimed to fix the recent regression that virtually nothing gets loaded into the site editor? Like so:

Screenshot 2021-02-01 at 11 00 28

If yes, then I'm afraid this PR didn't fix it for me alas. Let me know if what I'm experiencing is something else.

**Comment by aristath** [comment]
> Am I correct in understanding that this is aimed to fix the recent regression that virtually nothing gets loaded into the site editor?

Correct. Note that this assumes that the `theme.json` file has also been updated according to the latest structure changes. AFAIK the TT1-blocks has not been updated yet. You can test with the [master branch of the Q theme](https://github.com/aristath/q) where I've already applied all the changes.

| Before | After |
|-------|--------|
|Screenshot_2021-02-01 Site Editor (beta) ‹ local — WordPress|Screenshot_2021-02-01 Site Editor (beta) ‹ local — WordPress(1)|

**Comment by jasmussen** [comment]
Awesome, I was wondering what had regressed. And it's very possible that I broke most of this myself, as I tried updating my experimental-theme.json to the new structure. It [looks like this](https://cloudup.com/c2q_sSxtOWb), and as noted, this PR doesn't fix the issue for me. Can you spot any obvious errors in my syntax? Thank you Ari!

**Comment by aristath** [comment]
The JSON file you posted appears to be correct... I couldn't spot any obvious errors there :thinking:

**Comment by kjellr** [comment]
I tested just now with the latest version of TT1 Blocks, and I'm still not seeing any styles loaded in the full-site editor. 🤔

**Comment by aristath** [comment]
@kjellr I just tested it with TT1-blocks too and it didn't work, but then I tried it by moving the TT1-Blocks theme from `wp-themes/theme-experiments/tt1-blocks` to `wp-themes/tt1-blocks`. Subfolder themes have lots of issues lately, and it seems to be working fine when the theme is not in a subfolder. I think I saw another PR a few days ago that was supposed to fix subfolder-based themes :thinking: 
Can you please confirm if that is the issue?

**Comment by kjellr** [comment]
Yeah, I'd originally tried it in a subfolder, but the template parts didn't load in the front end. Now I'm running it directly in `wp-content/themes` but still seeing the issue.

**Comment by jasmussen** [comment]
It sounds like what I'm experiencing also.

Is there a particular additional step to take in addition to restarting npm run dev?

**Comment by aristath** [comment]
> Is there a particular additional step to take in addition to restarting npm run dev?

No extra steps... I have `WP_DEBUG` and `SCRIPT_DEBUG` enabled in my `wp-config.php` but I don't think that makes a difference.
I just tested this again and it works for me using the Q theme (master branch) and also TT1-blocks (master branch, not in a subfolder). Tested with Firefox & Chrome, I noticed that on Chrome there was some sort of delay and it only worked after a couple of minutes and a hard refresh to reset the caches :thinking: 

The screenshots below are using the TT1-blocks theme:

| Before | After |
|--------|--------|
|Site editor with no styles loaded|Site editor with styles properly loaded|

**Comment by aristath** [comment]
cc @carolinan for testing since you're working on the TT1-blocks theme :pray:

**Comment by jasmussen** [comment]
It's still not working for me.

I can inspect the iframe and see what CSS is output, what should I be looking for here?

Screenshot 2021-02-02 at 11 18 45

**Comment by aristath** [comment]
Update: On Firefox the PR works fine, Chrome is where the issue can be consistently replicated. 
I must have had some weird cache get in the way earlier when testing Chrome.

**Comment by aristath** [comment]
In Firefox after all the `<style>` elements inside `<head>` there are a few `<style>` elements and that's where all the variables get added. In Chrome however the `<iframe><head>` doesn't contain any `<style>` elements, so there's obviously something different in the way browsers behave...

**Comment by aristath** [comment]
OK, I'm officially stuck and can't understand what goes on here... cc @nosolosw, do you have any idea what goes on here and why Chrome loads `<style>` in the parent while Firefox adds them in the `<iframe>`?

**Comment by jasmussen** [comment]
I can confirm that it works in Firefox, and also that it doesn't work in Chrome, Safari, or Microsoft Edge on MacOS.

CC: @ellatrix as I know you worked on the iframe.

**Comment by nosolosw** [comment]
:wave: just saw the pings and found https://github.com/WordPress/gutenberg/issues/28581

I've taken a quick look at the different pieces at play (iframe, editor styles hook, global styles hook, server styles) and this is what I see:

- the global styles hook is working fine: `settings.styles` in `core/block-editor` are updated properly
- the editor styles hook is working fine: it takes the updated data in `settings.styles` and wraps it accordingly
- the iframe is not being updated upon user style changes (or client-side style changes for that matter)

It seems the root issue is that iframe takes its stylesheet from the global variable `window.__editorStyles` (passed down from the server) and it doesn't use the client-side editor styles? Need to investigate this more but it sounds like the fix needs to be at the point in which we pass the styles to the iframe. Going to take a look at this.

**Comment by david-szabo97** [comment]
Looks like the styles are not available when the iframe loads. Adding a `setTimeout(... ,0)` around 
https://github.com/WordPress/gutenberg/blob/541141d49bd48da25b22f568506cca1f24ab5b5b/packages/block-editor/src/components/iframe/index.js#L155-L161

makes chrome work.

To be more specific, `styleSheetsCompat` function does the work to make the styles available in the iframe. Adding a timeout to this function makes it work in chrome.

**Comment by david-szabo97** [comment]
Just opened a companion PR. That should take care of the problem that I described above.

**Comment by nosolosw** [comment]
I've pushed what I had locally (a work in progress fix) at https://github.com/WordPress/gutenberg/pull/28731 We need a different fix than what's proposed here.

**Comment by aristath** [comment]
> I've pushed what I had locally (a work in progress fix) at #28731 We need a different fix than what's proposed here.

I completely agree, this is a bad PR. Closing it now that we have a better solution :+1:

**Comment by nosolosw** [comment]
> I completely agree, this is a bad PR

This is a PR that has brought attention to an important issue and pushed us to discover the root cause we need to fix. So, I'd say it's a good PR that doesn't get the opportunity of landing in `master`. As Marie Kondo says: we should thank this PR and wish it goodbye. 🙂

**Pull request closed without merging**
