### PR TITLE
[RNMobile] Extend current Button settings with automatically pasting link

### LINKED ISSUE #1957: Button Block: links copied to clipboard are auto-filled to URL field in the link settings but not in the block settings
Links copied to clipboard were automatically added to the URL field when tapping the link settings (link icon in toolbar) but the same thing does not happen for links copied to the clipboard when tapping the block settings (gear icon on block). This confused me. 

Auto-filling the URL field with the link from the clipboard should work the same way for both the link settings and the block settings.
 
Video: [1m3s](https://cloudup.com/cD1iTISMTRP)
<sup>Tested with WPiOS 14.3.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

Screen Shot 2020-02-26 at Feb 26 1 56 35 AM

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1957#event-3072715893
Ref to gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1958
 
* Extend current Button setting to get automatically link pasting into button settings.
* Add autofocus on Button Link URL field like in other examples

## How has this been tested?

1. Copy link into clipboard, e.g: `http://apple.com`
2. Open mobile app
3. Add Button block
4. Open Button settings
5. Notice if link is automatically pasted into Button Link URL field

## Types of changes

Enhancements:
* Extend current Button setting to get automatically link pasting into button settings.
* Add autofocus on Button Link URL field like in other examples

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by chipsnyder** [comment]
@lukewalczak Testing through some of this now and just wanted to confirm a finding. For a string like `apple.com` should I expect that to appear in the link text field?

**Comment by lukewalczak** [comment]
👋 @chipsnyder , I assumed that according to [logic](https://github.com/WordPress/gutenberg/blob/master/packages/url/src/is-url.native.js#L10) for checking a copied string into the clipboard, you should expect that `http://apple.com` will appear in link text field.

**Comment by chipsnyder** [comment]
> http://apple.com will appear if exactly that string was copied into the clipboard. If you copied just apple.com it shouldn't appear.

👍 That's what I was seeing. Tested the use cases above with block settings and the link attributes. LGTM!

**Review by chipsnyder — APPROVED** [review]

**Comment by lukewalczak** [comment]
I've updated also Button test case according to changes: https://github.com/wordpress-mobile/test-cases/pull/9

**Pull request merged**
