### PR TITLE
Default link to image_default_link_type for gallery

### LINKED ISSUE #10173: image_default_link_type is ignored by Gutenberg
The setting image_default_link_type  from options.php is not used by Gutenberg: mine is set to "file", yet the editor defaults every image or gallery to the "none" link type. I have to set them all manually instead.

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Fixes #10173 for galleries

Related to #25578 which fixes it for images

- [x] Remove block default `linkTo` value
- [x] Use the `image_default_link_type` option from `options.php` to set default link for galleries
- [x] Adjust `linkTo` attribute to match `link` values in PHP: `'media'`→`'file'` and `'attachment'`→`'post'`
- [x] Fix shortcode `'post'` `link` transformation (before `'post'` wasn't getting transformed to `'attachment'` in `transforms.js`, but now with the block using the same values as the shortcode it doesn't need to be transformed)
- [x] Update `deprecated.js` with the attribute change
- [x] Update `transforms.js` with the attribute change

### New gallery block

1. Change the `image_default_link_type` setting in `options.php` to `'post'`, `'file'`, or `'none'`
2. Create a gallery block
3. See that the `Link to` option is correct: **Attachment page** for `'post'`, **Media file** for `'file'` or **None** for `'none'`

### Migrate gallery block

1. Create gallery block off of master branch with various link options
2. Switch to this branch
3. See that old gallery block is updated with the new attributes

### Transform from shortcode

1. Create a Classic Editor block
2. Add gallery in the Classic Editor
3. Click 'Convert to blocks'
4. See that the link option in the shortcode goes to the linkTo option in the gallery

## Screenshots 

image_default_link_type-gallery

## Types of changes

New feature? Bug fix?

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by mkaz — APPROVED** [review]
Looks good Alex, nice working with you on these! :+1:

**Comment by nicolasbrouard** [comment]
Is this feature integrated in Wordpress 5.5.3?
Do I need to install the Gutenberg plugin?

**Comment by talldan** [comment]
@nicolasbrouard This won't be in WordPress 5.5.3, but it will be in the upcoming WordPress 5.6 due on 8th December (https://make.wordpress.org/core/5-6/).

**Comment by nicolasbrouard** [comment]
Awesome. Thanks a lot for the reply.

**Comment by cxlxin** [comment]
Please review: As of WP 5.9 the `image_default_link_type` option doesn't work for the new galleries. Images do still work.

**Pull request merged**
