### PR TITLE
Make media & text block placeholder translatable

### PR DESCRIPTION
**Pull request by swissspidy**
## Description
This PR makes the placeholder text in the media & text block translatable.

Props @fernandotellado for reporting this.

Not sure if the context is needed or should be changed/removed.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by IreneStr** [comment]
Looks good to me :) I think you'll need to rebase to let the test pass.

**Review by IreneStr — APPROVED** [review]
Looks good to me 😄 I think this can be merged after Travis is done.

**Comment by IreneStr** [comment]
@swissspidy I restarted one of the builds for you because of an inconsistently failing test. I'll merge it/get it merged when Travis is happy.

**Comment by swissspidy** [comment]
Thanks @IreneStr @youknowriad!

**Pull request merged**
