### PR TITLE
Show Link UI in Nav Offcanvas for submenus inserted via block options ("3 dots") menu

### PR DESCRIPTION
**Pull request by getdave**
## What?

Displays the Link UI for submenus inserted via the block options ("3 dots") menu in the Nav Offcanvas experiment.

⚠️ Note: this does _not_ currently work for the case where the given block is _not_ currently a submenu (i.e. it's a "Custom Link"). Why? Because the relevant code calls `replaceBlock` which (unlike `insertBlock`) does not currently have an argument to disable the select of the "replaced" block in the canvas 🤦 

https://github.com/WordPress/gutenberg/blob/aa9b1d665a10f32182797e0d7e7a559362d1ec1c/packages/block-editor/src/components/off-canvas-editor/block.js#L384-L397

## Why?

Because when a new link is inserted the Link UI should be displayed to afford the ability to configure the link in the same way in which the UI is displayed when adding a link via the block appender `+`.

## How?

This PR:

- lifts state up to the offcanvas root.
- passes `onInsertBlock` callback down to appender and individual block components
- components call `onInsertBlock` anytime a block is inserted to trigger the Link UI
- handling of information about the "inserted block" is now extracted to a hook for utility

## Testing Instructions

- Test everything behaves as per `trunk` for normal link insertion via appender
- Now with a Custom Link click on the options menu ("3 dots menu") and click `Add submenu item`.
- See that the item is inserted by the Link UI does _not_ show (this is due to the bug described under `What` above which we will address in a follow up to target the missing APIs on `replaceBlock`.
- Now you have a Submenu item click on the options menu ("3 dots menu") and click `Add submenu item`.
- This time you should see the Link UI appear.

Also run the unit tests for the custom hook:

```
npm run test:unit packages/block-editor/src/components/off-canvas-editor/test/use-inserted-block.js
```

## Screenshots or screencast 

https://user-images.githubusercontent.com/444434/207874046-30efed05-0fef-42a8-87cc-0099df2c161c.mp4

### CODE REVIEW

**Comment by draganescu** [comment]
While super awesome, I think this to be pretty undiscoverable to land. I mean, let's fix `replaceBlocs` and then do the proper UX. There is nothing that will make this PR be harder if done later. As it is here it'll be like one of the gazillion gestures people discover on touchscreens by accident, then forget :)

**Comment by getdave** [comment]
> While super awesome, I think this to be pretty undiscoverable to land. I mean, let's fix replaceBlocs and then do the proper UX. There is nothing that will make this PR be harder if done later. As it is here it'll be like one of the gazillion gestures people discover on touchscreens by accident, then forget :)

This does make an incremental improvement which is to allow the Link UI to show when yuo _already_ have a submenu. Therefore I think it has merit.

Moreover, it improves the code via better SRP and tests for things that currently are not tested.

I take your point but I think it's worth landing and _then_ following up to enhance it. To delay it only to do it the other way around seems 🤷‍♂️ 😄

**Comment by scruffian** [comment]
The other problem with this is that the inserter appears at the bottom of the list:

Screenshot 2022-12-15 at 15 19 23

In some cases this makes it impossible to see, because it's off the screen. Is there a way to land some of the code improvements here without changing the UX for now?

**Comment by getdave** [comment]
> Is there a way to land some of the code improvements here without changing the UX for now?

Yes but why not just fix the bug you've uncovered? 🤷‍♂️

**Comment by scruffian** [comment]
> Yes but why not just fix the bug you've uncovered? 🤷‍♂️

If that's relatively simple then sure, I just didn't want to hold up the other fixes in the PR if it was going to be involved.

**Comment by getdave** [comment]
## Update

I now no longer think `replaceBlock` is the problem as the reducer for that action will not update the selection in the canvas if the currently selected block is not one of the block's being selected. In our case the Navigation block is the currently selected block and so when we replace the Nav Link with a Nav Submenu it should have no effect on the block selection.

What I suspect might be happening is some kind of race condition whereby the `onInsertBlock` callback is called and updates the state in the root `index.js` component. This is supposed to trigger the hook `useInsertedBlock` which should fetch the name of the inserted block but I think some updates are happening out of sync.

This results in the check failing when we test whether the blockName is in the allowed blocks for the Link UI to show.

**Comment by getdave** [comment]
## Next Steps

I'll be away until after New Year now. So leaving notes for myself or whoever picks this up.

~Let's cherry pick from this PR to extract the hook with the tests.~ [I extracted a hook here](https://github.com/WordPress/gutenberg/pull/46618).

Then we can rebase and update this PR.

Following that we can try and discern [what's going on with the race condition as described here](https://github.com/WordPress/gutenberg/pull/46582#issuecomment-1354728389).

**Comment by scruffian** [comment]
To solve the issue with the position of the Link UI, I think we need to do this: https://github.com/WordPress/gutenberg/pull/46744

**Comment by getdave** [comment]
Looking at this again now

**Comment by getdave** [comment]
I've been looking into this again.

With the refactor in https://github.com/WordPress/gutenberg/pull/46744 we can remove much of the code in this PR and instead rely on the `getLastInsertedBlockClientId` selector to access the block inserted when clicking on "Add submenu".

Everything should "just work". However...

- If the block is already a submenu block then `INSERT_BLOCKS` is called to add a new Custom Link to the _existing_ submenu block.
- If the block is a standard custom link however
    - a new submenu block is created (but not inserted)
    - a new custom link block is created (but not inserted)
    - REPLACE_BLOCKS` is called replacing the existing custom link with the new submenu which has the _new_ custom link as one of it's inner blocks

The issue with the `REPLACE_BLOCKS` flow is twofold in that that
- the `getLastInsertedBlockClientId` doesn't track `REPLACE_BLOCKS`, only `INSERTED_BLOCKS` so the selector doesn't get run when the new submenu is created.
- the `getLastInsertedBlockClientId` doesn't "know" about the newly added custom link which we added as an inner block of the newly created submenu

The desired UX is 
- existing custom link is transformed into submenu
- new custom link is added as child of said submenu
- Link UI is displayed for the newly added custom link (not the submenu)

So far I have tried to work around this by calling `replaceBlocks` to create the submenu and then separately calling `insertBlocks` to add the new custom link. However this doesn't seem to work either!

Going to circle back to this tomorrow as I'm sure I'm missing something obvious in the flow.

**Comment by getdave** [comment]
I now have an alternative proposal in https://github.com/WordPress/gutenberg/pull/46857 which I think we should consider.

This PR has fallen behind progress elsewhere and will be time consuming to refactor for little benefit. I suggest we close it out.

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/46857

**Pull request closed without merging**
