### PR TITLE
Removing Reakit as a dependency

### LINKED ISSUE #53278: Components: Remove usage of Reakit
## What problem does this address?

[Reakit](https://reakit.io/) does not explicitly support React 18, so it is causing peer dependency warnings.

Reakit has already been succeeded by [Ariakit](https://ariakit.org/), so it will not receive any more updates.

## What is your proposed solution?

Replace Reakit usage with Ariakit, or possibly other libraries like Radix UI.

### Components remaining

Make sure we have sufficient test coverage of the existing components before we start a migration.

- [x] Composite @andrewhayward
  - [x] https://github.com/WordPress/gutenberg/pull/54225
  - [x] https://github.com/WordPress/gutenberg/issues/55224
  - [x] https://github.com/WordPress/gutenberg/issues/56548
- [x] Disclosure @flootr #55639
- [x] Divider @flootr #55622
- [x] RadioGroup (already deprecated — need to decide how to proceed) #55580
- [x] ToggleGroupControl https://github.com/WordPress/gutenberg/pull/50278
- [x] Tooltip #48440

### PR DESCRIPTION
**Pull request by andrewhayward**
## What?

This PR removes [Reakit](https://reakit.io/) as a dependency. Closes #53278.

## Why?

See #53278.

## How?

`reakit` is removed as a dependency from `package.json` (and by extension `package-lock.json`). Additionally, the ESLint import rule is removed from `.eslintrc.js`.

## Testing Instructions

Everything should build as expected, including Storybook.

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
Should we also make sure that there are no more references to `reakit` in the code?

I could spot a few across these files: 
 - https://github.com/WordPress/gutenberg/blob/7946a0de0bd9b36f435a6913624fcaf626fecd3b/packages/edit-site/src/components/page-patterns/grid-item.js
 - https://github.com/WordPress/gutenberg/blob/773f4d3dcfb9ae9d1608f436f9b5cf8c7db622e9/packages/components/src/utils/hooks/use-update-effect.js
 - https://github.com/WordPress/gutenberg/blob/c777886d29c77da45f003e081a2691fecf2f37c2/packages/components/src/divider/README.md
 -   https://github.com/WordPress/gutenberg/blob/1ba116b01f986c5945b40d5eecd77c3bd1159df5/packages/components/src/context/wordpress-component.ts

**Review by mirka — APPROVED** [review]
Reakit is dead, long live Ariakit! 🚀 

> Should we also make sure that there are no more references to `reakit` in the code?

Good catch! I'm fine with the code comment URL stuff since they're references to things in the Reakit codebase that possibly don't apply in the current Ariakit code. Maybe there's value in preserving the original intent there. But the `Divider` readme, we should definitely update!

**Comment by andrewhayward** [comment]
> Should we also make sure that there are no more references to `reakit` in the code?

I did check, and as @mirka points out, they're all in comments, so I didn't think it appropriate or necessary to remove them. But happy to do so if we collectively think otherwise.

> But the `Divider` readme, we should definitely update!

Probably should have happened as part of #55622, but yes, that's long outdated at this point.

**Comment by ciampo** [comment]
Some of those links are 404ing though, so probably there is still value in either updating them to the right URL (or the ariakit version of it), or removing them

**Comment by andrewhayward** [comment]
> Some of those links are 404ing though, so probably there is still value in either updating them to the right URL (or the ariakit version of it), or removing them

I've updated the Reakit-related Github links, so that they at least work. The only link I didn't update is in [`page-patterns/grid-item`](https://github.com/WordPress/gutenberg/blob/474f6b0f339aff858311a980bd91cc27cf80648a/packages/edit-site/src/components/page-patterns/grid-item.js#L174-L175), which points to some Reakit documentation I couldn't find an equivalent for.

**Comment by diegohaz** [comment]
> > Some of those links are 404ing though, so probably there is still value in either updating them to the right URL (or the ariakit version of it), or removing them
> 
> I've updated the Reakit-related Github links, so that they at least work. The only link I didn't update is in [`page-patterns/grid-item`](https://github.com/WordPress/gutenberg/blob/474f6b0f339aff858311a980bd91cc27cf80648a/packages/edit-site/src/components/page-patterns/grid-item.js#L174-L175), which points to some Reakit documentation I couldn't find an equivalent for.

I don't know if Gutenberg uses that `id` for another purpose, but that comment can be removed. Performance enhancements previously activated in Reakit by passing the `id` prop to composite items are now standard in Ariakit.

**Comment by andrewhayward** [comment]
> I don't know if Gutenberg uses that `id` for another purpose, but that comment can be removed.

Thanks @diegohaz – I've removed the comment, but left the `id` prop in place.

**Pull request merged**
