### PR TITLE
Video Block: add raw transformation from `video` html

### LINKED ISSUE #42768: There is no raw transformation available for copy and pasting video element into the editor
### Description

There is no "raw" transformation available for `video` elements.

### Step-by-step reproduction instructions

Attempting to copy and paste the following HTML into the editor should create equivalent Video blocks, however it pastes them into a Paragraph block and stops the user from editting them:

```html
<video controls src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></video>
<video controls>
  <source src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></source>
</video>
```

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Closes: #42768

## What?
This PR adds a transformation that generates a video block from HTML containing a `video` element.

## Why?
Since `core/image` and `core/embed` support transformation from raw HTML, it would make sense to add similar support for the video block.

## How?

Inherits as many attributes supported by the Video block as possible, including the `src` attribute of the `video` element. However, the `src` attribute is assumed to be attached to the `video` tag, and the `source` tag inside the `video` tag is not considered.

This is because the Clipboard API itself doesn't seem to pick up elements inside the `video` tag. The screencast below shows that when you copy HTML containing a `video` element with a `source` element, the clipboard does not contain the `source` element.

https://github.com/WordPress/gutenberg/assets/54422211/dbf5efc3-c231-44cd-822a-f54069747104

## Testing Instructions

- Open the Codepen sample page prepared [here](https://codepen.io/Tetsuaki-Hamno/pen/NWJqZKR).
- Copy the entire page and paste it onto the block editor.
- It should inherit the attributes and be converted to a video block.

## Screencast

https://github.com/WordPress/gutenberg/assets/54422211/4782fa67-88d5-4e90-88b9-3181345a7fa7

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thank you, @t-hamano!

**Comment by t-hamano** [comment]
Thanks for the review, @Mamaduka!

Just to be sure, I would like to merge the latest trunk into this PR, test it again, and if there are no problems, I would like to merge it.

**Comment by codebymikey** [comment]
Thanks for implementing a fix for this!

I had a local transformation in place which achieved similar, but also added `tracks` and basic `caption` support.
I've quickly cleaned up the code a bit (I had extra code in place for handling weird content edge-cases) and attached here for reference in case it's relevant and `tracks` support needs to be added for completeness sake: https://gist.github.com/codebymikey/db24ca7ef8ea21cb2602f432d0868c6d

**Comment by t-hamano** [comment]
@codebymikey Thank you for your great exploration!

I created [a test page](https://codepen.io/Tetsuaki-Hamno/pen/bGZgMxG) and tried your code, but it didn't work. From what I've researched, the Clipboard API doesn't seem to recognize either `source` or `track` elements. That's why I didn't support those tags in this PR. Does it work well in your environment?

https://github.com/WordPress/gutenberg/assets/54422211/f4e99970-74d9-4481-9a8b-6638946be2f5

**Comment by codebymikey** [comment]
On further investigation, it seems to be because of the way the transform works, the `video` phrasing content schema needs to be updated to support the child `track` and `source` elements: https://github.com/WordPress/gutenberg/blob/23c3a67638901517df76dced33c73e6392171952/packages/dom/src/phrasing-content.js#L113-L125

to be similar to [this](https://gist.github.com/codebymikey/db24ca7ef8ea21cb2602f432d0868c6d/06575bcd8432f69c90489762d87bfb64b96b0af6#file-videos-transform-js-L9-L22)

And re the Clipboard API: it's more for if you copy the actual HTML source (with sources and tracks) into the editor rather than for rendered videos. You ideally shouldn't lose that information on paste.

**Comment by t-hamano** [comment]
Thank you for your explanation. It seems that other blocks can correctly convert HTML _strings_. Regarding the Video block, we may be able to deal with it through follow-up.

https://github.com/WordPress/gutenberg/assets/54422211/2b1fe10a-9168-48f5-b2fd-7f83ec60e8c8

**Pull request merged**
