### PR TITLE
Add a rotating list of tips to the inserter help panel

### PR DESCRIPTION
**Pull request by youknowriad**
This PR updates the inserter help panel to show a different tip on each render (mount).
This is a static list of tips but we could potentially make it extensible in the future.

**Testing instructions**

 - Open the inserter
 - Notice that the tip changes each time you open/close the inserter.

### CODE REVIEW

**Comment by michelleweber** [comment]
I'm assuming the copy is what's [here](https://github.com/WordPress/gutenberg/pull/20163/commits/15d6604e473aee1b2cd684d681d74f63ab581493)? 

For the media files, I'd say "automatically insert" rather than "quickly."

For "transform blocks," I think the update doesn't include enough information, because the word "transform" begs the questions "into what?" Suggestion: "Change a block's type by pressing the block icon on the toolbar."

**Comment by mtias** [comment]
Thanks @michelleweber for the suggestions!

**Comment by youknowriad** [comment]
Applied the suggestions above, thanks.

**Comment by youknowriad** [comment]
Should we land this first batch of tips?

**Review by mtias — APPROVED** [review]

**Pull request merged**
