### PR TITLE
Social Links: Add text placeholder next to appender

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Create a SelectedPlaceholder to show text next to the appender when selected.

This helps the guide the initial empty state and adding the first links.

Related to #29756 

## How has this been tested?

- Add Social Links block
- Confirm "Add a link" text shows next to appender
- Clicking away shows placeholder icons not text

## Screenshots

social-links-placeholder

## Types of changes

Adds new SelectedPlaceholder components and switches what gets passed to InnerBlocks based on selected state

### CODE REVIEW

**Comment by jasmussen** [comment]
Don't think I didn't see what you did here!

That said, thanks for the PR. I rebased and pushed some polish:

prompt

The only thing here is that the text isn't clickable. I could potentially _hack_ that to work, but I'm not sure. So I'm going to think more about what to do here, and I'd welcome input as well.

**Comment by jasmussen** [comment]
@mkaz I'd love to land this one! Any thoughts on clickable text? Or should we rephrase to sound less clickable and point to the plus?

**Comment by mkaz** [comment]
@jasmussen So I think if we want the text to be clickable, we'll want to alter the `renderAppender`

The way the placeholder works is it gets passed forward to the block list and gets rendered as an element in at the same level of the appender, ie. it is not a part of the appender. You can [see that code here](https://github.com/WordPress/gutenberg/blob/6ede89a1152a65988791c4cf9ca9cea914dbc227/packages/block-editor/src/components/block-list/index.js#L143)

Let me test out a way to alter the appender and add the text in front which I believe will work. Though I feel we went down this path a year or two ago, but can't find the reference or why we didn't go forward with it. 🤷‍♂️

**Comment by mkaz** [comment]
I don't think it is as straight-forward as I hoped. A way to solve would be to create a `CustomAppender` and then can use the onClick event on the text an button, but this requires replacing the default inserter.

I think a better solution is to create a label or prop that can be passed down to the Inserter and placed alongside the button with both being the same click action. This would allow other InnerBlocks consumers, such as Navigation, to use and not have to also create their own `CustomAppender`

I created ticket #30688 that can address the larger issue, for this one maybe we just alter the text for now and 🚢 

Looking back at the original ticket for placeholder here https://github.com/WordPress/gutenberg/pull/25941 I had stubbed out the text `Use [+] to add links` 🤷‍♂️

**Comment by jasmussen** [comment]
Okay, rebased and tweaked. Let's try this:

Screenshot 2021-04-12 at 10 04 26

**Comment by mkaz** [comment]
Approved 👍  (It is my own PR, so that can't be the official one)

**Review by jasmussen — APPROVED** [review]
Let's try it. Current state in trunk is not great.

**Pull request merged**
