### PR TITLE
Try/fix pasting links

### PR DESCRIPTION
**Pull request by diegoreymendez**
## Description

Gutenberg-mobile fix for pasting links in iOS.

Fixes pasting links. The content was being updated properly, but the native component was not being refreshed right in iOS, and the change was being lost.

The format bar was showing the existence of a link but the text was just not showing it.

## How has this been tested?

Tested through: https://github.com/wordpress-mobile/gutenberg-mobile/pull/644

## Types of changes

This PR simply makes sure the event count is eliminated to force an update in the native component.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Ping @mkevins - Please review and add comments if necessary. Thanks!

**Comment by mkevins** [comment]
I tested this on Android, and it fixes a similar issue where the selection context menu was not going away after clicking paste.

**Comment by hypest** [comment]
Will update this branch.

**Review by hypest — APPROVED** [review]
LGTM!

**Comment by hypest** [comment]
The basic tests pass on Travis, except for the outage of the e2e tests currently in effect. This PR doesn't touch any web-side code so it is good to merge. Will merge it.

**Pull request merged**
