### PR TITLE
Accessibility: Force an ARIA override for multiline plain text blocks.

### LINKED ISSUE #19124: Screen reader can't edit typed text in blocks
**Describe the bug**
When using the latest NVDA screen reader, and the latest version of FireFox, text can't be edited after it is typed in any text block. Markdown, paragraph, and similar. After composing a markdown block using NVDA in focus mode, the screen reader will only read the first character or the last character but it will not read any other characters when trying to arrow through.

**To reproduce**
The below requires NVDA:
1. Create a markdown block with NVDA in focus mode. Forms mode. '...'
2. After you have written more than one character, press the left and right keys to try to navigate within the text you just typed.
3. don't navigate away from the block after typing.

**Expected behavior**
I expected the blocks to let me edit and review the text as if it were a notepad document.

- OS: Windows 10, 1903.
 - Browser [Firefox 71.0 (32-bit) 71.0 (32-bit)

**Additional context**
I am using the latest version of the editor used on wordpress.com. Not wordpress.org. This problem does not happen when using HTML view.

### PR DESCRIPTION
**Pull request by MarcoZehe**
Sometimes, when a textarea gets un-hidden and focus at the same time, Firefox won't properly expose the full text interface to screen readers. Screen readers such as NVDA then won't be able to read the full line of text, behave weirdly when navigating by line or character, etc. This override will force Firefox to take a different code path which is also used for rich text contentEditables, which don't suffer from this problem. Fixes #19124.

## Description

Added role="textbox" and aria-multiline="true" to the plaintext component renderer.
## How has this been tested?

Tested this using http://gutenberg.run and using a code block. Inserted the code block, typed some text, switched back to the title and back to the code block. Initial text is sometimes still problematic, but at least when traversing blocks, this patch makes it so that navigation is then always possible.
## Types of changes

Bug fix
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by gziolo** [comment]
Thanks for opening this PR. Is there any reason it’s still marked as draft?? There are 2 e2e tests failing which is caused by the changes introduced but it can be fixed by updating the existing snapshots. I’m afraid we don’t have it explicitly covered in [e2e tests doc](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#end-to-end-testing). There is a section about [working with snapshots](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/testing-overview.md#working-with-snapshots) related to unit tests which is the same for e2e tests.

**Comment by MarcoZehe** [comment]
Yes, I wanted to test it first, and try to fix those failing tests, It‘s my first PR.  I am also not yet sure whether this is all that‘s needed. Don‘t want to waste anyone‘s time with a premature review request.

**Review by ellatrix — APPROVED** [review]
Looks good to me!

**Comment by MarcoZehe** [comment]
After extensive testing, it turns out that this PR does not fix the problem. It would only add superfluous attributes that do not fix the [underlying Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1604096). I am therefore closing this one and won't ask for review and merge.

**Pull request closed without merging**
