### PR TITLE
Add a way to change template parts.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

This PR adds a button in the toolbar that will allow a user to 'Choose another' template part.  This uses the same search/preview selection component as the Template Part Placeholder block (as well as refactors this for reuse outside of the placeholder itself.)

This should be a good starting point being able to switch template parts, and reusing the same search and preview component as the placeholder will allow us to maintain consistency and improve this in both places at the same time in future iterations.

The Icon is currently "update", and can obviously be changed if something more fitting is suggested (I looked at "search" and "tool" as well, but am open to other suggestions.)

## How has this been tested?

On local environment.  Tested both flows from existing template part as well as from the placeholder block.

## Screenshots 
change-template-part

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jameskoster** [comment]
As discussed in #19259, in the interest of keeping the toolbar lean, is it worth considering the idea of grouping template part actions here? I appreciate it's beyond the scope of this PR specifically, but aiming for something like this makes some sense to me and is perhaps worthy of discussion here:

tp

To bring things back in scope, maybe something like this could work as an interim:

scope

**Review by noahtallen — COMMENTED** [review]
Noting that the code looks good to me. I think it makes sense to move the button beside the input field as suggested, especially if we are going to iterate to use a different dropdown menu there in the future

**Comment by noahtallen** [comment]
I also think it would be nice to have an option to "create new" (or even "duplicate") from this dropdown, but that doesn't have to block this :)

**Comment by Addison-Stavlo** [comment]
@jameskoster 

>  is it worth considering the idea of grouping template part actions here? I appreciate it's beyond the scope of this PR specifically, but aiming for something like this makes some sense to me and is perhaps worthy of discussion here:

Yes, I think that will definitely make sense especially as we expand on this to add the "create new" and "duplicate" type options.  Having these related options in the same dropdown will definitely help keep things organized and the toolbar lean.

> To bring things back in scope, maybe something like this could work as an interim:

While it may be worth putting the current picker under this dropdown style, I don't think it makes sense to use a different component/design for sorting through, previewing, and selecting template parts between the placeholder and the instantiated block.  Theoretically, picking template parts in either of these places should have the same requirements and using the same component also allows us to keep things more consistent, maintainable, and updatable in the future as well.  The design of the picker itself can definitely be iterated upon in the future, but here I think it is best to make the current picker accessible from this flow as opposed to implementing a separate system.

I would also be wary of a design for selecting template parts that lists them without a means of filtering.  As a users library of template parts grows, the ability to search/filter them by name/theme/type increases.  Without this the list can become long and hard to manage, and if we only show 'related' template parts without the ability to change that filter then we are forcing a restriction on what template parts the user is allowed to switch to, which seems unreasonable.

<hr/>

@noahtallen 

> I think it makes sense to move the button beside the input field as suggested, especially if we are going to iterate to use a different dropdown menu there in the future
> I also think it would be nice to have an option to "create new" (or even "duplicate") from this dropdown, but that doesn't have to block this :)

I think moving it into the dropdown might be a bit weird before we have other options like create/duplicate.  Id say we either:
* Merge this with the current button in the toolbar, and follow-up soon after with adding create/duplicate functionality and moving them all into a dropdown.
* Or just keep this open for a bit while we add create/duplicate functionality and the grouped option dropdown system.

Either way seems fine to me.

**Comment by noahtallen** [comment]
>  I don't think it makes sense to use a different component/design for sorting through, previewing, and selecting template parts between the placeholder and the instantiated block

I agree with this. I will say that the options like "duplicate" or "create" would be nice to have for existing blocks and might not be useful for new blocks, so that could be one difference in the ultimate design.

> Merge this with the current button in the toolbar

I was thinking that we could use this design for where the button lives

> scope

Perhaps changing the icon, and then the actual content of the dropdown is the same as what exists? That way we can reuse the existing component for now.

Then we're in a spot where we can change template parts without much effort, and the interaction is very similar to what it will ultimately be (without having to immediately implement the new designs which are being worked on)

**Comment by Addison-Stavlo** [comment]
>  I will say that the options like "duplicate" or "create" would be nice to have for existing blocks and might not be useful for new blocks, so that could be one difference in the ultimate design.

Definitely, the "create" option for the placeholder is separate from the picker there as well.  I would imagine that dropdown as noted could have three buttons "Choose another", "Duplicate", and "Create new".  Where the "Choose another" button would open the existing picker that would be shared between the two flows for consistency.

> Perhaps changing the icon, and then the actual content of the dropdown is the same as what exists?

Yeah I think that makes sense here.  Get rid of the separate new button in the toolbar, move it into the name panel with the dropdown icon, and have it open similarly from there.  Then in the future we can update that dropdown to have three separate options as we add those functionalities instead of just opening the picker.

**Comment by Addison-Stavlo** [comment]
e86552a updates to using the dropdown icon and compressing that into the same section as the name panel:

Screen Shot 2020-09-04 at 1 19 43 PM

Screen Shot 2020-09-04 at 1 19 53 PM

**Comment by Addison-Stavlo** [comment]
and rebased.

**Review by jeyip — COMMENTED** [review]
The template part switching experience looks good and it sets a solid foundation for future work, given what @jameskoster and @noahtallen have mentioned earlier 🚀 

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

**Notes:**
- Do we have a stance on unit tests for site editing blocks?
- IE11 is looking wonky, but from my understanding, that's not something we're actively supporting for site editing?

Screen Shot 2020-09-08 at 11 17 19 AM

**Comment by jeyip** [comment]
+1 from me if we're not supporting ie11

**Comment by Addison-Stavlo** [comment]
> IE11 is looking wonky, but from my understanding, that's not something we're actively supporting for site editing?

Im not 100% sure on that, it would be nice to fix it for that as well though if able.  Im assuming this funkyness isn't present in current master?

> Do we have a stance on unit tests for site editing blocks?

I haven't seen much regarding this.  Currently for Template Parts we have some e2e tests in https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/experiments/template-part.test.js

**Comment by jeyip** [comment]
> Im assuming this funkyness isn't present in current master?

Oh that's a great callout. 🤦  I assumed it had to do with the new dropdown icon because of the look of the bug, but I didn't cross-check check master. I'll do it now.

**Comment by jeyip** [comment]
This is what's currently on master. It looks like it's the template part name input interrupts the block toolbar layout, and not the icon in this PR. I think it's fair to tackle the bug in a follow-up 👍 

Screen Shot 2020-09-08 at 12 04 33 PM

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
> I haven't seen much regarding this. Currently for Template Parts we have some e2e tests in https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/experiments/template-part.test.js

Thanks for the heads up. I'll think I'll raise the question about unit testing more broadly in #cylon

**Comment by noahtallen** [comment]
> IE11 is looking wonky, but from my understanding, that's not something we're actively supporting for site editing?

I don't think it's worth worrying about right now

**Comment by Addison-Stavlo** [comment]
> This is what's currently on master. It looks like it's the template part name input interrupts the block toolbar layout, and not the icon in this PR.

Oh yeah, it looks like its beyond the name input as well and there are a handful of issues with the toolbar on ie11:

Screen Shot 2020-09-08 at 3 22 09 PM

Noticing that the move block up/down icons are overlaid on top of the text align button in the example above with the paragraph block, as well as in your screenshot they are over the block alignment button:

Screen Shot 2020-09-08 at 3 24 39 PM

This might be a separate can of worms.

>I don't think it's worth worrying about right now

👍

**Review by noahtallen — CHANGES_REQUESTED** [review]
found a little bug, but other than this, it works great!

1. open the changer dropdown menu
2. click the "^" icon
3. It does not close the menu, but it kind of reopens again

**Comment by Addison-Stavlo** [comment]
>open the changer dropdown menu
click the "^" icon
It does not close the menu, but it kind of reopens again

🤔  I am not able to reproduce:

close-icon-bug-not

Any more info?  Its running on the supplied `onToggle` function for the dropdown component.

**Comment by noahtallen** [comment]
interesting! I'm in Firefox testing this by the way. Here is a gif:



Based on my testing, it looks like the dropdown closes on mousedown, but then opens once more on mouseup. Since the click does both down and up, it closes and then opens again. If I click and hold, and then move the mouse away from the dropdown while still holding the click, it stays closed.

**Comment by Addison-Stavlo** [comment]
Yeah I see this on firefox and not chrome.. lol this is a bit annoying 🤔

**Comment by Addison-Stavlo** [comment]
It has something to do with using the `SearchForm` in the dropdown (or even just a general input).  If I remove the input it works fine.  And also oddly only finding this odd behavior on FireFox. 🤔 

This wasn't an issue in the placeholder since there was no real 'close' button to use there as selecting outside of the popover triggers a close anyways.  I'm not sure what to do about this...

**Comment by Addison-Stavlo** [comment]
a5bd923 fixes the issue.  It is odd that its only an issue on firefox and only when an input is present in the dropdown... but disabling the toggle when open works to prevent this as even clicking it while disabled will trigger closing the dropdown by its default behavior.

**Comment by noahtallen** [comment]
>  If I remove the input it works fine

hmmmmmmmmmm

Maybe it's a firefox bug? Is there a way to change the dropdown to only close on click rather than on mousedown?

**Review by noahtallen — APPROVED** [review]
It's definitely a bit hacky, but so is the bug, so I'll take it 😅 

Let's ship it!

**Comment by Addison-Stavlo** [comment]
> It's definitely a bit hacky, but so is the bug,

Yeah, it's so weird.  The "^" doesn't generally trigger until mouseUp... but when the input is present, the mouseDown causes the focus change to close the dropdown first, and by the time mouseUp happens the toggle function is set to open the dropdown instead of close it.  Without the input, mouseDown on "^" doesn't close the dropdown.  

The only other thing I can think of atm is to re-implement the popover used for the dropdown with a customized `closeIfFocusOutside` function, but that seems like it would be hacky and cumbersome as well.  Since this design will be iterated upon and the hierarchy may change a bit, its probably best to hold off on that kind of thing and go with just disabling the button when open for now. 🤷‍♀️

**Comment by noahtallen** [comment]
> its probably best to hold off on that kind of thing and go with just disabling the button when open for now

👍

**Comment by noahtallen** [comment]
> the mouseDown causes the focus change to close the dropdown first, and by the time mouseUp happens the toggle function is set to open the dropdown instead of close it

So weird... It sounds like the input is incorrectly capturing the focus sometimes, then?

**Comment by Addison-Stavlo** [comment]
> So weird... It sounds like the input is incorrectly capturing the focus sometimes, then?

Im not entirely sure, as even when I move focus away from the input and try closing.. the same thing happens with the defocused input.

**Comment by ZebulanStanphill** [comment]
Pinging @afercia to check this out. (Sorry for so many pings lately.) I think this needs some accessibility feedback. A chevron doesn't seem like the best way to indicate a button to switch the template part. Why not a pencil "Edit" icon? Also, I'm not sure if the chosen control labels are good enough. "Choose another" should probably be "Choose another template part", shouldn't it?

**Comment by afercia** [comment]
Can anyone be so kind to please update, or better add, test instructions?

- is there the need to install a specific theme to test this UI?
- if so, where this theme is available?
- what are the specific steps to follow to make this UI appear?

I'd like to remind everyone that this is an open source project, where any contributor is supposed to have all the necessary information be able to test a pull request, get familiar with it, and bring in their contributions if they like. Thank you 🙂

**Comment by Addison-Stavlo** [comment]
> Pinging @afercia to check this out. (Sorry for so many pings lately.) I think this needs some accessibility feedback. A chevron doesn't seem like the best way to indicate a button to switch the template part. Why not a pencil "Edit" icon? Also, I'm not sure if the chosen control labels are good enough. "Choose another" should probably be "Choose another template part", shouldn't it?

Agreed.  At this point we are adding the functionality with the assumption that the design and accessibility will be reiterated.  This is definitely not an end-state for this interaction, and it will need to be reorganized as support for other interactions are added.  Given that this is in a more temporary state and that this is still an experiment under constant iteration, we have not stalled to polish a perfect design and interaction at this point in time but aim to reiterate in that direction as we continue to move forward.


<hr/>

> Can anyone be so kind to please update, or better add, test instructions?

Id be glad to help!  My apologies for the test instructions being very short, the scope of this change is very small within the experiment, but if you are coming into the Site Editor experiment as a whole there are quite a bit of missing pre-existing context.

1. You will need to enable the "Full Site Editing" experiment under `Gutenberg -> Experiments` in wp-admin.  (We recommend NOT enabling "Full Site Editing Demo Templates" as having done this may interfere with other Site Editor testing in other areas, and may require a cleaning the environment if it had been enabled)

> is there the need to install a specific theme to test this UI?

2.  Install and activate a block based theme that includes template parts.  There are a few available https://github.com/WordPress/theme-experiments such as `twentynineteen-blocks`.

> what are the specific steps to follow to make this UI appear?

3.  Load the "Site Editor" (there should be a button in wp-admin just under Gutenberg once the experiment is enabled).  The top section of the template in the editor will be a header template part.  Selecting this Template Part block will allow the toolbar to appear as shown.

or

4. Loading in either the Post Editor, you can insert a block called "Template Part" that becomes available with the experiment enabled.  This block is added as a placeholder with the options to select an existing template part or to create a new blank one.  Once one of these steps is done, you can access the toolbar from there as well.

Please let me know if you have any other questions or need further assistance.

**Comment by noahtallen** [comment]
> Why not a pencil "Edit" icon?

You would editing be editing the template part at the time, so switching it is a different interaction from editing. But I totally agree that the chevron might not be ideal.

And as always, we are happy to let others choose the icons and copy for these things! I will totally recognize that my strengths as a developer are not in choosing the text which best describes an interaction.

> Can anyone be so kind to please update, or better add, test instructions?

I think an action item here is to create a documentation page which we can link to on FSE-related PRs. That way, it's easy for anyone to get started with it! :)

**Comment by afercia** [comment]
@Addison-Stavlo thank you. That helped.

My main difficulty in testing this UI was finding a way to actually select the template part. That's really difficult to understand. At the end, I used the Breadcrumbs bad at the bottom.

My main concern with this UI is that inserting an input field within the toolbar breaks the ARIA toolbar pattern, which amongst other things implements arrows navigation and the "roving tabindex" pattern. This has been noted also in other issues and PRs as there are already other UIs designed to use unexpected elements within the toolbar. One of them, already in production, is the Image block "editing tools" UI, which breaks interaction with the toolbar. See for example: #24766, #24676, , #24021, #23375, #24805. This pattern needs to be avoided. The accessibility team already discussed this topic in the latest weekly meeting and it will probably discuss it again in the next one to explore alternative options.

**Comment by noahtallen** [comment]
> My main difficulty in testing this UI was finding a way to actually select the template part. That's really difficult to understand. At the end, I used the Breadcrumbs bad at the bottom.

Totally agree! We did some investigation into this issue in #22064, but are still iterating on the best way to do so.

**Comment by ZebulanStanphill** [comment]
Come to think of it, why is this dropdown even a thing in the first place? Wouldn't it make more sense to insert template parts from the inserter, similar to reusable blocks? I know there's no room for another tab, but to me that just says we shouldn't have used tabs in the first place. It seems weird to me that we're switching template parts from the toolbar.

**Comment by Addison-Stavlo** [comment]
> Wouldn't it make more sense to insert template parts from the inserter

Yes, this has been discussed as well (I think I even had a draft PR to add a tab for template parts to the inserter that way, and was prompted to add previews to the placeholder block instead).  Currently, we can use the inserter to insert the 'Template Part' placeholder block, which has a button to trigger the preview/selection interface.

> why is this dropdown even a thing in the first place? 

So template parts can be changed once the block has already been initiated from the placeholder.  Instead of inserting an entirely different template part block and deleting the unwanted one, we have an option to switch which one the block references.

> I know there's no room for another tab, but to me that just says we shouldn't have used tabs in the first place. It seems weird to me that we're switching template parts from the toolbar.

Yeah, I cant verify if the toolbar will be the final resting place or not.  Discussion may move this interaction to the top bar, sidebar, or elsewhere.  For now, we just need it 'somewhere' to aid in development and testing.  Having it here for a day has already helped point out a silly bug in renaming that was otherwise unnoticed.

**Pull request merged**
