### PR TITLE
Call tinyMCE save before sending metabox data

### PR DESCRIPTION
**Pull request by davisshaver**
## Description
Updates https://github.com/WordPress/gutenberg/pull/3840 to include `window.tinyMCE.triggerSave()` prior to metabox serialization.

## How has this been tested?
Locally.

### CODE REVIEW

**Comment by aduth** [comment]
What is the context for this?

**Comment by davisshaver** [comment]
@aduth Follows up https://github.com/WordPress/gutenberg/pull/3840 to update the input field controlled by WP editor instances on the page before sending metadata params. There was a discussion on there that I didn't totally follow but I wanted to share my patch for making the TinyMCE fields work as expected.

**Comment by danielbachhuber** [comment]
@davisshaver Is this supposed to be changing the TinyMCE version too?

**Comment by davisshaver** [comment]
@danielbachhuber Yes, it is – I originally approached as continuation of https://github.com/WordPress/gutenberg/pull/3840, but as you'll see in https://github.com/WordPress/gutenberg/pull/3840#issuecomment-383093982 @youknowriad ultimately suggested we fix another way in Core.

**Comment by danielbachhuber** [comment]
This PR is a bit garbled, so I've opened a new issue to track this to resolution #7176

**Pull request closed without merging**
