### PR TITLE
Blocks: remove deprecated node and children matchers

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

These have been deprecated 4 years ago with #7890.

Turns out the deprecation messages have been [removed](https://github.com/WordPress/gutenberg/pull/10439#issuecomment-428505090) though, and they've never been restored...

### CODE REVIEW

**Comment by youknowriad** [comment]
I saw some folks still using these, maybe we should add a message first that these will be removed in say WP 6.3 or something.

**Comment by ellatrix** [comment]
Where did you find this? Sure, we can log a message first. It's a bit unfortunate that we forgot to add it back. :)

**Comment by youknowriad** [comment]
> Where did you find this?

To be honest I don't remember, some folks were discussing it in a slack or something and I was surprised they were still using it.

**Comment by ellatrix** [comment]
I saw we even have some documentation with them, so it's not surprising if people are still using it... I created #44265 to officially deprecated it.

**Pull request closed without merging**
