### PR TITLE
Try: Add header & footer patterns

### PR DESCRIPTION
**Pull request by kjellr**
A PR to add the patterns from https://github.com/WordPress/gutenberg/issues/31231#issuecomment-832041557. 

## Todo

- [x] Use responsive menus
- [ ] Tidy up mobile views

## Screenshots

Headers:

Screen Shot 2021-05-15 at 12 04 45

Footers: 

Screen Shot 2021-05-15 at 12 07 26|

### CODE REVIEW

**Comment by kjellr** [comment]
> Use responsive menus

Just noting that I gave this a try but was hindered by the bug described in https://github.com/WordPress/gutenberg/issues/31845.

**Comment by kjellr** [comment]
I've added in some responsive menus. These patterns are generally looking ok, though they fall apart quiet a bit on mobile still. The responsive menus help, but these will be in a much better place if we can land https://github.com/WordPress/gutenberg/pull/31816. For example, for this pattern: 

Screen Shot 2021-05-18 at 11 13 19 AM

... the responsive menu kicks in just fine, but the column its in wraps on mobile: 

Screen Shot 2021-05-18 at 11 13 03 AM

This is an issue for many of the header patterns. 

---

Other patterns will need some additional changes: 

- https://github.com/WordPress/gutenberg/issues/19909#issuecomment-833575572 continues to be an issue for many of these patterns. 
- I filed https://github.com/WordPress/gutenberg/issues/31942 to see if we can figure out a way to get nav items to still appear horizontally on mobile. 

---

By the way, @ntsekouras, do you know if there is something I can do get these patterns to appear here? Or is that just not ready yet?

Screen Shot 2021-05-18 at 11 17 41 AM

**Comment by kjellr** [comment]
Here's a quick visual snapshot of the status of these across breakpoints. You'll notice that they really start to fall apart pretty quick.

## Headers

Desktop|Tablet|Mobile
---|---|---
Screen Shot 2021-05-21 at 12 52 56|Screen Shot 2021-05-21 at 12 46 44|Screen Shot 2021-05-21 at 12 47 25



## Footers

Desktop|Tablet|Mobile
---|---|---
Screen Shot 2021-05-21 at 12 56 01|Screen Shot 2021-05-21 at 12 56 24|Screen Shot 2021-05-21 at 12 56 41

**Comment by ntsekouras** [comment]
>By the way, @ntsekouras, do you know if there is something I can do get these patterns to appear here? Or is that just not ready yet?

It's not implemented yet.

**Comment by kjellr** [comment]
This PR is still blocked until we have a solution to https://github.com/WordPress/gutenberg/issues/31248#issuecomment-833568210. I have an idea in https://github.com/WordPress/gutenberg/pull/32778 that might provide an easy fix for this, but not sure yet. 

https://github.com/WordPress/gutenberg/issues/19909#issuecomment-833575572 is also still an issue, but it's a slightly more acceptable bug in my opinion. 

But in the meantime, I polished these a little bit more and also tried them out in a variety of block themes. From that testing, I decided it would make sense to provide a few more variations of the simplest headers. Here's the full set that's in here today: 

## Headers

Screen Shot 2021-06-17 at 11 29 27 AM
Screen Shot 2021-06-17 at 11 29 36 AM
Screen Shot 2021-06-17 at 11 29 44 AM
Screen Shot 2021-06-17 at 11 29 53 AM
Screen Shot 2021-06-17 at 11 30 01 AM
Screen Shot 2021-06-17 at 11 30 08 AM
Screen Shot 2021-06-17 at 11 30 44 AM
Screen Shot 2021-06-17 at 11 30 57 AM


## Footers

Screen Shot 2021-06-17 at 11 31 15 AM
Screen Shot 2021-06-17 at 11 31 23 AM
Screen Shot 2021-06-17 at 11 31 38 AM
Screen Shot 2021-06-17 at 11 34 13 AM

**Comment by kjellr** [comment]
Another update: I've adjusted these patterns to use the new "do not stack on mobile" setting for the columns block. It generally works as expected, but the results still aren't great.

To get it to work nicely, I think we'd need: 

- The ability to adjust the gaps for the columns block. (https://github.com/WordPress/gutenberg/issues/24874)
- The ability to change the width values for columns at the breakpoint at which the mobile menu kicks in. (Generally #19909 or #13363). 

Really though, a better solution might be to _not_ use columns here in the first place. These items (Site Title and Menu) should just behave like flexbox children, taking up the space they need at any breakpoint, while still staying in a horizontal row. @jasmussen I know you've talked with me about maybe expanding the Navigation block to house other standard header elements to achieve this, but is there an issue for it already?

_Update: Looks like there's an issue exploring this sort of thing for the Group block: https://github.com/WordPress/gutenberg/issues/24473_

Anyway, here's a snapshot of the current state on mobile for some of these header patterns: 

Screen Shot 2021-07-07 at 13 31 56

**Comment by jasmussen** [comment]
> Really though, a better solution might be to not use columns here in the first place. These items (Site Title and Menu) should just behave like flexbox children, taking up the space they need at any breakpoint, while still staying in a horizontal row. @jasmussen I know you've talked with me about maybe expanding the Navigation block to house other standard header elements to achieve this, but is there an issue for it already?

There wasn't an issue, but there should be, so I created it here: https://github.com/WordPress/gutenberg/issues/33278 — please add to it if I missed anything, you can feel free to edit it.

I want to suggest that in addition to allowing more blocks inside navigation, the Group/flex feature you linked will be a big help. I also still want to explore grid-based no-query responsiveness, as shown at the bottom of this codepen: https://codepen.io/joen/pen/wvJMdGr

**Comment by codetipi** [comment]
This all looks really great, but for a lot of sites, responsive header/footer patterns won't be nearly enough. Has there been any discussion regarding "mobile-specific templates" instead?

As a very basic example, many sites have white background headers with a black logo on desktop (similar to the patterns shown above) but on mobile, they want a dark header with a white logo.

Responsiveness can't do that properly, it has to be done via different HTML markup and blocks/images.

I imagine a system where you can create separate "desktop header patterns" and "mobile header patterns", and that they appear on the site depending on theme specified breakpoints would unlock all the current limitations.

**Comment by kjellr** [comment]
Closing due to inactivity. 🕐

**Pull request closed without merging**
