### PR TITLE
Update 'with-colors' to work with #7319

### PR DESCRIPTION
**Pull request by Luehrsen**
## Description
This is a supporting PR to work on a newer codebase for issues raised in #7319 

See: https://github.com/WordPress/gutenberg/pull/7319#issuecomment-398528520

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tofumatt** [comment]
I'm a bit confused, is this PR dependant on another one to merge/work? If so it's best not to open new ones until the original one is merged... just to reduce the noise; someone might think this is good to review right now but I'm not sure it is. 😄

**Comment by Luehrsen** [comment]
It's the other way around. This PR is needed for another, finshed, merge-ready PR to work. 

See: #7319 (comment)

**Comment by tofumatt** [comment]
Oh, sorry for misunderstanding! 😄

Does it make sense to just add it to that PR? I'm not sure how to test/review this from the PR description. If you can expand it/let me know how to test this out I can review it 😄

**Comment by Luehrsen** [comment]
I think the culprit is, that there is a change that was added after #7319 was opened, so the code to be changed is not in the codebase of #7319. This PR is addressing this change without mingling in endless rebasing and merging-headaches. 

I think @jorgefilipecosta is probably best equipped to review this PR.

**Comment by jorgefilipecosta** [comment]
Hi @Luehrsen thank you for addressing the issue. I think the best approach here is to rebase https://github.com/WordPress/gutenberg/pull/7319 with master, and then add this changes in https://github.com/WordPress/gutenberg/pull/7319.
The problem right now is that this PR alone cannot be merged (because we still don't have slugs) and https://github.com/WordPress/gutenberg/pull/7319 alone cannot be merged because if we merge it is impossible to edit colors until this one is merged. Even if we merge in sequence there is a commit in master where things don't work and we should avoid that when possible to allow bisects and similar approaches in the future.

**Comment by Luehrsen** [comment]
I had feared that you would say something like that. I will try to rebase #7319 without breaking everything. :D

**Comment by tofumatt** [comment]
Since this can't be merged as-is I'll close it for now just to increase signal-to-noise in the PR queue, but don't take that as meaning the code's no good–as @jorgefilipecosta said: it just needs to be in the other PR. 😄

**Pull request closed without merging**
