### PR TITLE
Table block: use hooks + API v2

### PR DESCRIPTION
**Pull request by ellatrix**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Seems to work properly for me.

@talldan might want to take a look here?

**Comment by ellatrix** [comment]
Table has e2e tests and everything should still be the same. The interesting thing to rewrite here was having a method as a component, which could be avoided by just having the children in a map on render.

**Comment by talldan** [comment]
Looks good, some nice improvements to the code! I did some fairly thorough testing and couldn't spot any issues.

**Comment by ellatrix** [comment]
Thanks!

**Pull request merged**
