### PR TITLE
Expose WordPress installation and persist mysql databases

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

To give developers a better default experience, this exposes the Wordpress installation by default, and persists mysql database in a volume.

## How has this been tested?

`./bin/setup-local-env.sh` locally, then reboot, and `docker-compose up` brings us back to where we were.

CI should still pass, as the environments the tests run in are ephemeral.

### CODE REVIEW

**Comment by jasmussen** [comment]
Yaaay, confirmed! Did the steps and both the plugin is workable and my themes directory accessible post-reboot, post docker-compose up.

Before the reboot, the plugin directory was gone, but since you explicitly noted the reboot of course I followed the instructions and yes, it works great!

I would suggest a quick code review as I can't verify that, but this is working! Very cool.

**Comment by gziolo** [comment]
@notnownikki can you bring it up to date? I would love to see `docker-compose up` supported by default after reboot :)

**Comment by notnownikki** [comment]
Exposing WordPress by default has some issues, mostly with the linters. I think we should do the simplest most helpful thing first, which is persisting mysql and making sure everything survives after a reboot. I'll start rejigging things :)

**Comment by gziolo** [comment]
As discussed with @notnownikki privately, let's close this one as it's not going to be resolved soon and it's mostly nice to have.

**Pull request closed without merging**
