### PR TITLE
Site Editor: Remove unused PHP code

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Now that we have a custom Templates and Template Parts list page (#36379), there's no need to modify the default WP List Table.

PR removes unused filters and their callbacks.

## How has this been tested?
* PHP Unit tests should be passing.
* There aren't any PHP notices in `debug.log`

## Types of changes
Code Quality

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by noisysocks** [comment]
Did this code ever make it to Core? Just checking we don't need to backport these changes.

**Comment by Mamaduka** [comment]
@noisysocks,

I did search core and couldn't find these filters/callbacks.

**Review by youknowriad — APPROVED** [review]
This code was useful when the "templates" and "template parts" menu were visible in WP Admin. It's not the case anymore so yeah it's dead code.

**Comment by noisysocks** [comment]
I rebased this to (hopefully) fix failing tests.

**Pull request merged**
