### PR TITLE
Specify use of 5.7 branch for wp/5.7.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
## Description

Specifies the WP 5.7 branch be used as the WordPress install for the `wp/5.7` Gutenberg branch.

## How has this been tested?

Untested, seeing if the test suite runs successfully to find out if it works.

## Types of changes

Build tools: Changes for accuracy in testing WP version.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
PHP Unit test are passing as expected.

JavaScript tests are failing but the cause appears to be `caniuse-lite` warnings.

**Comment by peterwilsoncc** [comment]
@desrosj @gziolo

Looking at the commit history I've decided you two own tests, lucky you :) 

Using the correct version of WP on this branch is resulting in fewer failures but I'm still getting a few:

* JS Unit tests look like they might be caused by the caniuse warning. If that's correct, is there any way I can supress it? 
* No idea why some of the E2E tests are failing

Is there anything else I should take a look at while attempting to use the correct WP on each WP/* branch?

**Comment by gziolo** [comment]
`caniuse-lite` gets outdated after 6 months (or something like that) with no updates to the package. The simplest way to resolve the issue is to bring the package up to date, probably updating it together with `browserslist`.

```
["Browserslist: caniuse-lite is outdated. Please run:
    npx browserslist@latest --update-db·
    Why you should do it regularly:
    https://github.com/browserslist/browserslist#browsers-data-updating"]
```

E2E test failures are concerning, but it's also worth noting that it'd be a very unusual configuration to use the Gutenberg plugin to override the same set of features that are already in WordPress core. In practice, `wp/5.7` branch in Gutenberg contains the last plugin version used with WP 5.7  release (including all experimental features present at that time in the plugin) and all bug fixes included in the WP major release. Most of the test failures seem to be related to experimental features present in the plugin so in theory they could be ignored.

@youknowriad, @noisysocks and @ockham, can you help with reasoning about the best approach for enabling automated testing for WP major release branches?

One more thing. In practice, we can skip all React Native related GitHub workflows for this branch because they don't need to work since this branch will never be used to build a mobile app.

**Comment by youknowriad** [comment]
Ideally, in these branches we'd run unit tests and e2e tests essentially and ideally the docker image used should be `n-1` IMO. For instance in wp/5.7 it should be 5.6. (I wonder if this could be done automatically somehow instead of us doing a commit every time we create the branches)

For the caniuse, we should probably add a way to ignore these warnings in the tests because we don't want to update the browserlist in these old branches to avoid having different JS output.

**Comment by peterwilsoncc** [comment]
> Ideally, in these branches we'd run unit tests and e2e tests essentially and ideally the docker image used should be `n-1` IMO. For instance in wp/5.7 it should be 5.6. (I wonder if this could be done automatically somehow instead of us doing a commit every time we create the branches)

For the `wp/*` branches, I'd rather use the named version of WP as the most likely use of any updates is for use in the named version of WordPress core. If older versions of Gutenberg are to be updated, the `n-1` method could be applied to the `release/*` branches. 

> For the caniuse, we should probably add a way to ignore these warnings in the tests because we don't want to update the browserlist in these old branches to avoid having different JS output.

Agreed. Would that require writing a custom exception handler for the older branches or is there a configuration option to ignore specific errors?

**Comment by desrosj** [comment]
> For the `wp/*` branches, I'd rather use the named version of WP as the most likely use of any updates is for use in the named version of WordPress core. If older versions of Gutenberg are to be updated, the `n-1` method could be applied to the `release/*` branches.

I tend to agree with this stance.

**Comment by ghost** [comment]
@peterwilsoncc Hi Peter! Are you still working on this PR? What still needs to be done to close/merge this?

**Comment by peterwilsoncc** [comment]
It looks like core was pinned in 09683c1f5fc183103542181c1eaade9c0894510f so I think the main purpose of this PR is obsolete.

I'm not sure why the tests are failing but the same thing happens on the `wp/5.7` branch so that can be fixed in another pr.

**Pull request closed without merging**
