### PR TITLE
Try: Always show movers on selected blocks (except during typing)

### LINKED ISSUE #6272: Reconsider the left/right block hover areas, at least for the selected block
Looking a bit into the details of the new UI behaviors introduced in #6101 / #6141.

I understand the intent of lighten up the UI, however I'm not fully convinced about some assumptions that were made with these recent changes. First, the accessibility issue:

This is what the UI shows now when a block is selected:

screen shot 2018-04-19 at 10 18 35

The block "movers" on the left and the ellipsis/remove buttons on the right are not shown by default. I appreciate keyboard accessibility has been taken into consideration and these controls appear when tabbing through the interface. However, I think the assumptions made here have gone a bit too far. There are a lot of different workflows users will adopt, lots of different abilities, different level of expertise, and so on, that the best thing an UI can do is to not make so broad assumptions. Why the UI should assume users need to see these controls only when hovering on the left/right areas or tabbing into them? Here's just one example where this pattern would be an a11y barrier:
- I'm a user with motor impairments
- I don't use the keyboard, or using the keyboard is extremely difficult and painful for me
- I use a speech recognition software to voice commands and control my computer
- in the scenario above, with a block selected, I see just the toolbar
- instead, I need to see all the UI controls to understand what the available actions are
- aside: I'd need to know also the accessible name of the controls: unfortunately there are no visible labels but at least there are tooltips
- when all the UI controls are visible, I'm able to voice commands to my speech recognition software, e.g. "Click move down"
- but, if I don't see the UI controls, I don't even know what the available controls are

I'd strongly recommend to not hide the side controls on the selected block. As far as I see, in #6101 the new behavior was first implemented only for the unselected blocks and then extended to the selected block. Can we please reconsider this and make all controls visible for the selected block?

== Other considerations

I'd kindly suggest everyone to consider that many considerations about things like "reducing the UI weight" or "reducing the cognitive load" tend to be highly subjective and risk to be assumptions. To me, cognitive load is not about _how many_ things are displayed in the UI, unless there are literally dozens and dozens of controls. It’s more about the continuous appearing and disappearing. As I see it, now the UI controls continuously appear and disappear in a more frequent way than the previous implementation (which was already confusing for some users). So I wonder: does having “things” that continuously appear and disappear really lightens the cognitive load or increases it? 

You may argue I'm making assumptions too 🙂and that's true, so  I'd really like to see this new behavior A/B tested from users, including assistive technology users.

Note: 
maybe a small bug, as far as I see when a block can't be moved because it's the only block or its the first or last one, the mover buttons should look "disabled" also when hovered or focused. /Cc @jasmussen

### PR DESCRIPTION
**Pull request by chrisvanpatten**
This tries to fix #6272 by always showing movers on selected blocks, unless `isTypingWithinBlock` is true. This solves some accessibility issues as detailed in the original ticket, but also brings greater consistency between all block tools and less "flickeryness" (new word) for fast-paced mouse users.

It also partially impacts #10090 (but doesn't solve the underlying problem, just makes it less apparent).

Here's a visual:

kapture 2018-09-21 at 8 35 22

Now that the block mover is taller, this exposes an overlap issue when hovering a block immediately following a selected short block. I don't have a great answer for that unfortunately, but I think in this case the benefits outweigh that cost (at least for now).

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
@jasmussen @afercia @nosolosw could you take a look at this (sorry for the tags, just trying to think through who would be most affected)?

I don't think it's merge-ready because of the overlapping issue with adjacent blocks, but I'd like to see if this is a viable solution for the accessibility team and brainstorm some ideas to alleviate the overlapping.

❤️ 🚀

**Comment by jasmussen** [comment]
So, recently we added the drag handle to the side UI. Because we intended to have the hit area be mostly the same as it was before, 28x28px minimum for touchability, the up arrow was moved upwards. The test here is to use this side UI on a single line paragraph, which is the minimum height block we have at 56px height. 
So if you try this branch, and place two single line paragraphs after each other, then select the first and hover the second, you can sort of see the problem with the overlap that then happens. 

In that vein, although I appreciate this branch — thanks so much for trying — I'm not really sold on it as a benefit. 

It's all a balancing act — the movers and drag handle are very useful and helpful _when you need them_, but they are clutter when you don't. I actually feel the autohiding of them, with tabbability, is a good compromise. If we added on top of that some lovely keyboard shortcut like ctrl+shift+alt+↑ for move up, etc, I think we'd have a good overall balancing.

**Comment by chrisvanpatten** [comment]
@jasmussen I'm totally sympathetic to that but I know @afercia has made it pretty explicitly clear that keeping them visible while a block is selected is a basic requirement for the a11y team.

I'll let him comment though because perhaps with the recent changes to the block controls and drag handle and such, we can come up with another alternative!

**Comment by chrisvanpatten** [comment]
I think this is unlikely to change before 5.0, and truthfully I think they made need some bigger re-thinking to solve other issues (such as #7646). As such, I'm going to close this, albeit with a very heavy heart :(

**Pull request closed without merging**
