### PR TITLE
Rename the "Preview" button label to "View"

### PR DESCRIPTION
**Pull request by jameskoster**
| Before | After |
| --- | --- |
| Screenshot 2021-02-19 at 16 10 22 | Screenshot 2021-02-19 at 16 09 09 |

In several recent discussions the idea of placing access to new features in the "Preview" menu has arisen:

* Toggle the visibility of the template when editing a post. (#27847)
* Controlling the entity that is visible in the current template. (#28466)
* List and provide access to edit template _parts_ within the current template. (https://github.com/WordPress/gutenberg/issues/29147)

In each of these situations – plus the existing toggles for mobile, tablet, and desktop – "Preview" is perhaps not the most appropriate label. Historically, "Preview" in WordPress editor terms would open a non-editable, live version of the current document. But after taking any of these actions in the editor, one retains full edit-ability of all elements on the canvas. It is less a preview and more of a simple view option. Hence this PR to see how switching "Preview" to "View" feels.

### CODE REVIEW

**Comment by simison** [comment]
An issue for extending preview menu is related: https://github.com/WordPress/gutenberg/issues/25309

**Comment by MichaelArestad** [comment]
Long overdue. Ship it!

**Comment by paaljoachim** [comment]
I think it is a good idea to change from "Preview" to "View". 

We need to get some perspectives on this.
@bph @jasmussen

**Comment by jasmussen** [comment]
Well, it makes a ton of sense for a site editor which already _is_ a preview.

I do in the future see the post editor converging with the site editor, to the point that while a separate site editor item might still exist, you will commonly enter the site editor _from_ the post editor. In light of that, it bear thinking: does it make sense to rename the same element from Preview to View in the post editor? In absence of the two being the same, it would have to switch when shifting context.

**Comment by joyously** [comment]
To me, Preview designates that the changes are not published yet, and is showing front end instead of back end. View sounds more like the only difference is front end versus back end.

**Comment by jameskoster** [comment]
To Joen's point, everything you do in the editor is effectively both a preview and an edit, until published (assuming good editor styles). Hence switching from desktop to tablet is simply an exercise in changing the perspective of the current edit/preview session. "Preview" feels too prescriptive to me, and is more problematic when you consider that historically "preview" links in WordPress have sent you to the frontend, which isn't what happens here.

To carry on that train of thought, a _live_ preview is definitely something we need. "Browse mode" has been suggested in the past (https://github.com/WordPress/gutenberg/issues/23328), and more recently a basic "Preview site" feature was discussed briefly in https://github.com/WordPress/gutenberg/issues/29398. 

I would suggest that both live preview _and_ edit modes should offer users an affordance to switch the view between desktop, tablet, and mobile orientations. Having a "Preview" menu _within_ a "Live preview" feature seems a little nebulous to me.

**Comment by bobbingwide** [comment]
-100

In my opinion "View" should be reserved for displaying the content in the front end.

**Comment by simison** [comment]
Would showing an icon (maybe with a label) work?

An example from Wix:

Screenshot 2021-03-23 at 18 51 19

Google Sites:

Screenshot 2021-03-23 at 18 51 19

Although I'm a big fan of text-based UI, I bet these icons would be more clear than many of the other icons in the header currently. 😅 Any custom modes could show up as text or with their own custom icon.

**Comment by jameskoster** [comment]
As I touched on in the OP, the view/preview menu could potentially house many options beyond device simulations, so I'm not sure the icon would be a scalable solution.

**Comment by simison** [comment]
@jameskoster I think the key is having each mode add icon in addition to label but still show only active mode as icon in the header:

Image of Preview dropdown with icons

That way user learns what each icon means by just opening the dropdown.

Though I agree it's unclear how the ideas you listed would fit that format even as icons. In all those cases you suggest having "toggles" rather than the whole menu function as "select" input which has just one active _selection_, if I understood right? In that case the whole dropdown concept might not work.

**Pull request closed without merging**
