### PR TITLE
Updating some native mobile UI tests

### PR DESCRIPTION
**Pull request by hypest**
## Description
PR to update some native mobile UI tests that fail locally.

## How has this been tested?
Locally on an Android 10 device (Pixel 2 XL) via issuing `npm run test:e2e:android:local` and on an iOS v14.1 simulator via `npm run test:e2e:ios:local`.

## Types of changes
* swipeUp not needed; performed via removeBlockAtPosition on Android
* **Dismissing** Android 10's clipboard paste auto-suggestion popup so the test can continue as it was. Here's a screenshot of how that popup looks:

The updated code is dismissing the popup by looking for the `Dismiss Smart Suggestion` content-description and tapping on it.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jd-alexander — COMMENTED** [review]
Thanks for these changes @hypest The code looks good! The tests have been successful on Android so far but I haven't been able to reproduce the auto-suggestions pop up on my emulator. Is there a setting I might need to enable?

**Comment by hypest** [comment]
>  I haven't been able to reproduce the auto-suggestions pop up on my emulator. Is there a setting I might need to enable?

**Comment by hypest** [comment]
Also, let me know what you think about optimistically merging this since it doesn't seem to break the existing tests, and it's not a functional change anyway.

**Comment by jd-alexander** [comment]
> Also, let me know what you think about optimistically merging this since it doesn't seem to break the existing tests, and it's not a functional change anyway.

I'm totally fine with this 🙏🏾

**Review by jd-alexander — APPROVED** [review]
All tests pass on Android and iOS. LGTM 🚢

**Pull request merged**
