### PR TITLE
Travis: Only run deploy stage on master.

### PR DESCRIPTION
**Pull request by epiqueras**

### CODE REVIEW

**Review by Soean — APPROVED** [review]

**Comment by aduth** [comment]
Is this actually doing what it's intending to do?

I still see that the job occupies 1m30s+, runs `nvm install`, `npm ci`, before finally stopping, seemingly because of the GitHub Pages deploy provider's built-in behavior:

>Skipping a deployment with the pages provider because the current build is a pull request.

Example: https://travis-ci.com/WordPress/gutenberg/jobs/260838338

**Comment by epiqueras** [comment]
Yes, we still want to verify the stage succeeds before merging a PR to `master` right?

Otherwise, we can do: `if: (NOT type IN (pull_request)) AND (branch = master)`.

**Comment by aduth** [comment]
I'm not sure I understand. What are we verifying in the build? That NPM dependencies can be installed?

Or are you referring to the deploy command, `npm run storybook:build` ? As far as I can tell, that's not being run, because the build ends itself before running the deploy tasks. I don't really see why we would care to run it, either.

**Comment by epiqueras** [comment]
>Or are you referring to the deploy command, npm run storybook:build ? As far as I can tell, that's not being run, because the build ends itself before running the deploy tasks.

Yes, we should move it to `script` then.

>I don't really see why we would care to run it, either.

To avoid merging PRs that break the storybook.

**Comment by aduth** [comment]
Do we have some prior history of breakage? In its current form, the only thing the build could tell us is whether the command exits with a non-zero exit code.

I'm interested in keeping the build times as short as possible (#15159). If the stage is run only once all of the previous tests have completed, and the `npm run storybook:build` is not very efficient (1m20s+ on my local machine, I expect much longer in a Travis container), then I question whether the benefit outweighs the cost.

**Comment by epiqueras** [comment]
Not that I know of, but now that this builds the entire storybook, there is a lot of potential for breakage in stories.

Also, this is just a dry-run now, but we want to have deploy previews for PRs so we will definitely have to run it.

I assume you are thinking that most PRs don't touch stories and if they do they will be verified manually. So, yeah it can make sense to disable it for now. Even if it breaks, it wont break what's already deployed and it can be fixed with a following PR.

Are you working on a PR where you'll add `if: (NOT type IN (pull_request)) AND (branch = master)`? Or should I open a new one?

**Comment by aduth** [comment]
No, I haven't started working on any branch yet.

Maybe there's a potential for breakage. Then again, it hasn't been running this command since it was first introduced almost two months ago ([reference](https://travis-ci.com/WordPress/gutenberg/jobs/242226831)), so it clearly hasn't been much of an issue thus far 🤷‍♂ 

I think we'll want the playground in branch previews, sure, but I'm also not sure whether that will be deployed from Travis, vs. something integrating into something like [gutenberg.run](https://github.com/aduth/gutenberg.run).

**Comment by epiqueras** [comment]
I would rather see it as part of `gutenberg.run` as well.

I'll open a PR then.

**Pull request merged**
