### PR TITLE
ItemGroup: add story showcasing more complex layouts

### PR DESCRIPTION
**Pull request by ciampo**
## Description

Adds a new Storybook story for the `ItemGroup` component that helps showcasing how to use this component to create more complex UIs.

This example is also going to help to investigate the current limitations on `ItemGroup` when integrating it with other components.

## How has this been tested?

- [ ] project builds
- [ ] storybook story behaves as expected

## Screenshots 

Screenshot 2021-09-09 at 18 56 35

## Types of changes

New feature (new story)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Nice to see how all those component compose together 👍🏻

**Review by mtias — APPROVED** [review]
Awesome!

**Comment by pablohoneyhoney** [comment]
Nice!

When possible, let's try the borders as 20% of 000000. 

Screen Shot 2021-09-10 at 9 22 28 AM

Here's the original reference:

Screen Shot 2021-09-10 at 9 24 07 AM

**Comment by ciampo** [comment]
> When possible, let's try the borders as 20% of 000000.

Thank you for the feedback, @pablohoneyhoney. I've [updated](https://github.com/WordPress/gutenberg/pull/34708/commits/10d56360cf544815472fae29c75ec8751fbc3207) this specific Storybook example to be 20% of `000000`.

Out of curiosity, should this be the border color for all component's borders (e.g. the `ItemGroup` itself, `Card`, ...)? Currently, it is [set to be 10% of `#000000`](https://github.com/WordPress/gutenberg/blob/9af3ae765d5d6cd7e7688ff791e5170710386d79/packages/components/src/utils/config-values.js#L75)

**Review by diegohaz — APPROVED** [review]
This looks really cool!

**Comment by pablohoneyhoney** [comment]
> Out of curiosity, should this be the border color for all component's borders (e.g. the ItemGroup itself, Card, ...)? Currently, it is set to be 10% of #000000

We'd need to see them in context to value if the difference matters, but let's try it. @ciampo

**Pull request merged**
