### PR TITLE
Fix inline block styles minification issues with calc()

### LINKED ISSUE #29518: FSE: inline block styles minification issues with calc()
## Description

In 10.1 the loading method of block styles on the frontend was changed, see https://github.com/WordPress/gutenberg/pull/28358

There is an issue with the minified inline styles, specifically the removal of spacing in `calc()` functions.
e.g. the columns stylesheet contains `flex-basis:calc(50% - 1em)`
whereas the minified inline style now renders the same as `flex-basis:calc(50%-1em)` with the required spacing stripped out, resulting in an invalid value.

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes - TT1Blocks

### PR DESCRIPTION
**Pull request by aristath**
## Description
Fixes #29518 

## How has this been tested?
* Automatic testing: Added a phpunit test for `calc`.
* Manual testing: Tested using an FSE theme and remaining the source of a rendered page before and after this PR. Before this PR, inlined styles had things like `width:calc(50%-.625em)`. After the PR, the spaces inside `calc()` are not stripped so the result is `width:calc(50% - .625em)`

## Types of changes

Used the regex from https://stackoverflow.com/a/44350195 instead of a previous buggy one that didn't take calc into account.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
I would appreciate a check from someone else because my approval is based mostly on the unit test added 😄 

It would be practical to have more test data to cover some more complex CSS syntax, maybe something for animations, colors or fonts.

**Comment by aristath** [comment]
Fair point @gziolo 
I added some more tests now for media-supports, media-queries, animations, gradients. I think these are the most css-complicated things. Any other use-cases you think we should add tests for?

**Comment by gziolo** [comment]
> I added some more tests now for media-supports, media-queries, animations, gradients. I think these are the most css-complicated things. Any other use-cases you think we should add tests for?

A test case with CSS variables might be a good candidate. @jasmussen, you are the expert, any ideas?

**Comment by jasmussen** [comment]
I appreciate your kind words, but I have a sense that Ari is stronger in custom properties than I am :)

**Comment by aristath** [comment]
I added a test for a css-var & calc() combo 😺

**Review by gziolo — APPROVED** [review]

**Pull request merged**
