### PR TITLE
Fix off center post-publish button

### LINKED ISSUE #17691: Publish button is off-center
**Describe the bug**
When publishing a new post, the 'Publish' button on the confirmation/settings screen is not properly centered in its containing space.

**To reproduce**
1. Create a new post
2. Click on 'Publish'
3. See error

**Expected behavior**
The 'Publish' button should be horizontally centered.

**Screenshots**
Screen Shot 2019-10-01 at 5 21 39 PM

**Desktop (please complete the following information):**
 - OS: MacOS Mojave v10.14.15
 - Browser Firefox 69.0.1

### PR DESCRIPTION
**Pull request by richtabor**
## Description
Fixes #17691, by centering the Post Publish button and applying a bit of padding to keep the close button off the edge of the panel header. 

## How has this been tested?
Tested in supported browsers.

## Screenshots
ScreenFlow

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by enriquesanchez — COMMENTED** [review]
Left some comments on packages/edit-post/src/components/layout/style.scss

**Comment by mapk** [comment]
I've removed the spacer, adjusted the height of the button and centered it. While it's not perfect, it should work nicely with translations. Check it.

publish

**Comment by enriquesanchez** [comment]
Just tested this and looks 👍

**Review by mapk — APPROVED** [review]
I think we're good on this now. Thanks for testing @enriquesanchez!

**Comment by richtabor** [comment]
Yup, looks great!

**Comment by mapk** [comment]
@richtabor I'm not sure why we're having failed tests. Can you try rebasing?

**Comment by richtabor** [comment]
> @richtabor I'm not sure why we're having failed tests. Can you try rebasing?

I did, though it's still failing - I'm not entirely sure why?

**Comment by mmtr** [comment]
> > @richtabor I'm not sure why we're having failed tests. Can you try rebasing?
> 
> I did, though it's still failing - I'm not entirely sure why?

They seem to be unrelated to changes on this PR.

Failing E2E:
```
 Embedding content › should switch to the WordPress block correctly
    expect(jest.fn()).not.toHaveWarned(expected)
    Expected mock function not to be called but it was called wit
```

Mobile unit tests:
```
Cannot find module 'Platform' from 'react-native-implementation.js'
    However, Jest was able to find:
    	'./platform.android.js'
    	'./platform.ios.js'
    	'./platform.js'
```

I see this PR was merged recently with the same errors: https://github.com/WordPress/gutenberg/pull/18247 So, maybe builds are not currently stable? cc @gziolo

You can also try rebasing instead of merging, although I don't think that'd have any effect.

**Comment by aduth** [comment]
I think there's some intermittent failures in the E2E test with the "SameSite" cookie warning. The mobile tests are allowed to fail, so they shouldn't be considered as a blocker.

I restarted the build to try to clear up the failure.

**Comment by richtabor** [comment]
Here's a gif with the latest commit, with a slight tweak to make the Publish button centered across the entire panel header:

button

**Comment by mapk** [comment]
Looks great, @richtabor! Let's get this merged!

**Pull request merged**
