### PR TITLE
DataViews Fields API: default getValueFromId supports nested objects

### PR DESCRIPTION
**Pull request by oandregal**
## What?

The Fields API provides a default implementation for the `getValue` function when the field doesn't provide one. It simply uses the field id as the property of the data:

```js
const item = { user: 'value' };
const field = { id: 'user' };
```

While this field doesn't provide a `getValue` function, after normalization, it'll get one such as rendering `field.getValue({ item })` would return `value`.

This PR extends what the default getValue can do by adding support for nested properties. This means `getValue` will return 'value' in this scenario:

```js
const item = { user: { name: 'value' } };
const field = { id: 'user.name' };
```

## Why?

In a recent [workshop we ran about DataViews](https://oandre.gal/talks/dataviews-core-days-roma/), three different groups of people independently thought this would work. This is a strong signal that it'd be a useful feature.

This also enables us to absorb more cases where people won't need to provide a `getValue` function, meaning that in more situations, the Fields API could be declarative (e.g.: ready to be used in the server).

## How?

- Implement tests 63571e8d82bdf7126b1f4106cc51a5bc0a202abb
- Support nested properties 82d32a2c31d23f4de9d29ec212dc115ad4b84b22
- ~Support arrays~ 962684c76759d2622859ee9323743167e7f949b1 (reverted at https://github.com/WordPress/gutenberg/pull/66890/commits/7de6e3e2fa5faa37991adc3b6683b5cd04b20864)

## Testing Instructions

Verify unit tests pass. Smoke test the site editor pages that use dataviews (pages, templates, patterns) as well as the storybook.

### CODE REVIEW

**Comment by oandregal** [comment]
I think this is a nice approach and has its benefits.

For the cons, I can only think that it's a bit weird to use `users.name` or `users[0].name` in the form or view config. Note this is just weird for humans, machines don't make any difference between `user` or `users[0].name` — they just care that they are indeed unique values.

**Comment by oandregal** [comment]
> For the cons, I can only think that it's a bit weird to use users.name or users[0].name in the form or view config. Note this is just weird for humans, machines don't make any difference between user or users[0].name — they just care that they are indeed unique values.

An alternative to keep `id` human-friendly would be implementing this new behavior for `getValue`:

```js
// Single prop: keeps the current behavior.
const item = { user: 'value' };
const field = { id: 'user' };

// Nested prop.
const item = { user: { name: 'value' } };
const field = { id: 'user', getValue: 'user.name' };

// Array.
const item = { users: [ 'value' ] };
const field = { id: 'user', getValue: 'users[0]' };

// Array with nested prop.
const item = { users: [ { name: 'value' } ] };
const field = { id: 'user', getValue: 'users[0].name' };
```

**Comment by ntsekouras** [comment]
Thanks for the PR! Since we feed the data in DataViews component, how common do you think is having records fetched without the `id` being top level property? Can you provide some examples about the cases that are to be supported with this PR? Especially the `array` ones, as I couldn't think of how this could work in practice.

**Review by youknowriad — APPROVED** [review]
This is good to me.

**Comment by cbravobernal** [comment]
That was fast!

**Comment by oandregal** [comment]
> Thanks for the PR! Since we feed the data in DataViews component, how common do you think is having records fetched without the id being top level property? Can you provide some examples about the cases that are to be supported with this PR? Especially the array ones, as I couldn't think of how this could work in practice.

The important part is having nested property access: that's common, yes.

The array syntax is a nice to have that I only implemented to support the mental model people had about this (how [lodash get](https://lodash.com/docs/4.17.15#get) works): I'm fine removing it if that's a blocker for you @ntsekouras

**Comment by ntsekouras** [comment]
>I'm fine removing it if that's a blocker for you @ntsekouras

Not a blocker. I just cannot see a good reason for supporting this. I mean, the consumer would also be responsible to have let's say the first item of an array always with the same item to have a unique id, etc.. It seems that if consumers had something like that, could just provide their own function.

**Comment by oandregal** [comment]
> Not a blocker. I just cannot see a good reason for supporting this. I mean, the consumer would also be responsible to have let's say the first item of an array always with the same item to have a unique id, etc.. It seems that if consumers had something like that, could just provide their own function.

I'm not sure I fully understand this 🤔 This PR is about extracting data from the item without providing a `getValue` function (more declarative use cases), not about unique IDs. 

Anyhow, I feel strongly about the nested syntax so I'll go ahead with that part. Seeing that you have concerns about the array syntax (and it's a nice to have for me) I've reverted it at https://github.com/WordPress/gutenberg/pull/66890/commits/7003f7bf0a7cd2174e3f599e0811f170455e86c5 It's always good to start minimal, and easier to add more stuff later than to remove it.

**Pull request merged**
