### PR TITLE
Update pagination icons, add new query title and post terms icons

### LINKED ISSUE #37541: Global styles sidebar: Post terms, post navigation, and query title are missing icons
### Description

In the global styles sidebar in the site editor, these blocks are missing their custom icons. Instead, the "lego brick" is shown:
Post terms, post navigation, and query title.

### Step-by-step reproduction instructions

1. Activate a theme with support for full site editing
2. Go to Appearance > Editor
3. Open styles
4. Select Blocks
5. In the list of blocks, see the icons.

### Screenshots, screen recording, code snippet

list of block names and icons

### Environment info

WordPress 5.9-beta3-52379-src
With and without Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #37541. 

This adds a couple of new icons:

- Query Title
- Post Terms

And updates from the latest in Figma a few existing ones:

- Pagination
- Pagination Next
- Pagination Previous
- Pagination Numbers

37541 also details "Post Navigation Link", but I wasn't sure exaclty what that was. Can we just use "Post Navigation" for that? 

Note also that the "numbers" icon appears to be unused, but is still in the package.

Pagination before and after:
pagination before

pagination after

Next/prev before and after:
nextprevbefore

nextprevafter

Numbers after:

numbersafter

New Query icon shown in context of Post title in Figma:

post title after

Post terms in Figma:

post terms after

Query title and post terms shown in "all blocks" context:

Screenshot 2022-02-04 at 13 07 33

Screenshot 2022-02-04 at 13 08 15

## Testing Instructions

Open global styles, select "All blocks" and observe new icons for pagination, pagination next, pagination previous, query title, post terms.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Looks good! Thanks Joen!

**Comment by ntsekouras** [comment]
>Took a stab in https://github.com/WordPress/gutenberg/pull/38521. Note I wasn't able to find the "Post Navigation Link" to insert, and it's unclear to me what it does. Can we just use the existing Pagination icon for it?

Regarding your comment in the issue the `Post Navigation Link` has two variations which are the `Next/Previous` Post links that can be put in a post and we have a way to navigate to the `next or previous` post (repeating myself 😄 ). It can be done in a follow up of course.

**Comment by jasmussen** [comment]
> Regarding your comment in the issue the Post Navigation Link has two variations which are the Next/Previous Post links that can be put in a post and we have a way to navigate to the next or previous post (repeating myself 😄 ). It can be done in a follow up of course.

I blame that it's monday, but I can't for the life of me figure out how to get to this block. All I see are these:
Screenshot 2022-02-07 at 09 52 48

But with that beautiful green button glowing, I'm going to land this one as is, but I'm happy to follow up if you can share a screenshot or something.

**Comment by ntsekouras** [comment]
>I blame that it's monday, but I can't for the life of me figure out how to get to this block. All I see are these:

The `Post Navigation Link` is not used inside `Query Loop` or `Query Pagination` and has two variations: `Next post and Previous post`.

https://user-images.githubusercontent.com/16275880/152763631-228fb437-5d4b-46b5-936e-77da73155b1a.mov

**Comment by jasmussen** [comment]
Oh interesting, so it's more of a "meta"-block, in that it only ever shows up in global styles?

In that case I wonder if we shouldn't just use one of the existing next/prev icons for that 🤔

**Pull request merged**
