### PR TITLE
Add block-editor class to site editor.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Q - Should we have the `.block-editor` class in the site editor?  It is an implementation of the block editor, although distinct from the post editor which also relies on this class.  cc @youknowriad any thoughts?

Plugins and 3rd party blocks may often end up requiring the `.block-editor` class for their css styles to be applied.  This class was never added in the site editor causing these blocks to not function as expected and potentially break the layout when loaded in the site editor.  This PR adds this class to the site editor, on the same element corresponding to where it would be present in other editors.

## How has this been tested?

Smoke test the site editor and verify styles aren't broken.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
nevermind, seeing other conversation #26958 I don't think we need this.

**Comment by youknowriad** [comment]
My question here would be why blocks are using this class? It seems block styles should be context agnostic instead of adding more boilerplate to editors.

**Comment by david-szabo97** [comment]
It makes sense to me. Since `site-editor` is a `block-editor` as well.

**Comment by Addison-Stavlo** [comment]
> My question here would be why blocks are using this class? It seems block styles should be context agnostic instead of adding more boilerplate to editors.

1000% agree.  And the ones I have seen that are problematic are fixing this on their end.

It did however make me wonder if we should be adding this class to the site editor anyways.

**Comment by youknowriad** [comment]
hah  :)  For me, I was wondering whether we should remove it from the post editor instead :P

**Comment by david-szabo97** [comment]
I'm not familiar how third-parties are targeting the block editor in CSS. But using `.edit-site` and `.edit-post` seems uncomfortable. Having a class that's applied on both editor makes sense to me. Makes selectors in CSS less verbose.

**Comment by youknowriad** [comment]
> Having a class that's applied on both editor makes sense to me. Makes selectors in CSS less verbose.

My question would be why? I'm not suggesting to target edit-post and edit-site, I'm suggesting that blocks shouldn't need any  global classname.

**Comment by Copons** [comment]
I don't have any example handy, but I do recall some blocks having issues in the Site Editor for the lack of the `.block-editor` class. Might have been Jetpack or internal Automattic blocks, can't say for sure, but I'm pretty certain I investigated this at some point, most likely removing that class from the blocks' CSS.

I don't have a strong opinion on whether we should add the class to the Site Editor or remove it from the Post Editor, as long as we keep them consistent. IMHO, parity is more important than one redundant class.

This said, we don't have control over existing third-party blocks.
If some of these blocks rely on `.block-editor`, right now they'll behave incorrectly in the Site Editor.
If we remove the class from the Post Editor, they'll break there as well.

If we decide to remove the class from the Post Editor, we'll need to do it gradually, with a deprecation path or some sort, to allow for plugin developers to update their blocks.
In this interim period, we'd still kinda need the class on the Site Editor, though. 🤔

**Comment by youknowriad** [comment]
> If we decide to remove the class from the Post Editor, we'll need to do it gradually, with a deprecation path or some sort, to allow for plugin developers to update their blocks.

Yes, My opinion is that we should do a dev note about that and potentially a deprecation message on the console.

> In this interim period, we'd still kinda need the class on the Site Editor, though.

I disagree with that, the site editor is experimental and it's actually a good way to encourage people to remove that requirement from their blocks.  It's also not the only class that is present in edit-post and not in edit-site, there are a lot of them (all edit-post-* classes) so consistency is not possible and it just means more boilerplate for folks that want to use custom block editors. (Think edit-site, edit-widgets, edit-post, p2, asblocks, drupal Gutenberg...)

**Comment by Copons** [comment]
> > If we decide to remove the class from the Post Editor, we'll need to do it gradually, with a deprecation path or some sort, to allow for plugin developers to update their blocks.
> 
> Yes, My opinion is that we should do a dev note about that and potentially a deprecation message on the console.
> 
> > In this interim period, we'd still kinda need the class on the Site Editor, though.
> 
> I disagree with that, the site editor is experimental and it's actually a good way to encourage people to remove that requirement from their blocks. It's also not the only class that is present in edit-post and not in edit-site, there are a lot of them (all edit-post-* classes) so consistency is not possible and it just means more boilerplate for folks that want to use custom block editors. (Think edit-site, edit-widgets, edit-post, p2, asblocks, drupal Gutenberg...)

Right, it makes sense.
I guess then we should keep this PR on hold, pending decision about the `.block-editor` class. 🤔

**Pull request closed without merging**
