### PR TITLE
Add 'Three features' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a block pattern for #20345.

Screen Shot 2020-03-24 at 11 43 22

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. Let me know if you think it can be improved or if we should close this PR instead.

**Comment by mapk** [comment]
This one feels pretty good to me. 

Rather than a button, what about trying a simple link under the paragraph?

**Comment by mtias** [comment]
My only concern with this one is that it's not clear to me, as a user, what I could do with the leading covers. Maybe if we remove the numbers and only keep solid colors or gradients it could be better?

**Comment by carolinan** [comment]
They don't make me think of a service section, because I would expect an icon representing the service, not a number. I think most users would place an image first, not a cover block.

**Comment by mapk** [comment]
Or we could just try moving the feature title into the Cover block instead? How would that look?

**Comment by enriquesanchez** [comment]
Closing this PR in favor of #20898.

**Pull request closed without merging**
