### PR TITLE
Remove "Advanced" toggle from LinkControl

### PR DESCRIPTION
**Pull request by richtabor**
## What?
Try removing the "Advanced" toggle and associated preference to simplify a bit. 

## Testing Instructions

1. Open a post or page.
2. Insert a heading block.
3. Add a link. 
4. Select "Edit" to further edit the link.
5. See changes. 

## Screenshots or screencast 

| Before  | After |
| ------------- | ------------- |
|CleanShot 2024-04-03 at 16 29 24|CleanShot 2024-04-03 at 16 24 10|

### CODE REVIEW

**Comment by richtabor** [comment]
I noticed that Yoast takes over the Link Control anyhow. 

This is what you see when Yoast is active (sans the "Advanced" toggle):  

CleanShot 2024-04-03 at 16 19 12

**Comment by t-hamano** [comment]
I don't know where the discussion behind this PR is, but I agree with removing the Advanced toggle. I'd love to hear other people's opinions.

If we are to move forward with this PR, I think the following points need to be changed.

- Update [README](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/link-control/README.md#persistent-advanced-settings-toggle-state)
- Delete (or update) [unit tests](https://github.com/WordPress/gutenberg/blob/98ccfecae0fe03246cbe92dc74d5953d09819bec/packages/block-editor/src/components/link-control/test/index.js#L1819-L1868)
- Delete (or update) [E2E tests](https://github.com/WordPress/gutenberg/blob/98ccfecae0fe03246cbe92dc74d5953d09819bec/test/e2e/specs/editor/blocks/links.spec.js#L703-L795)

> I noticed that Yoast takes over the Link Control anyhow.

Yes, Yoast SEO plugin has its own inline functionality and implements `LinkControl` individually here:

https://github.com/Yoast/wordpress-seo/blob/a574e0d8d36df5fbae41a69f55711297a3517f2c/packages/js/src/inline-links/inline.js#L339-L354

**Comment by SaxonF** [comment]
Yes to removing. If we get to a point where more settings are needed we can reconsider but with just two items it's not as useful

**Comment by carolinan** [comment]
Another yes to removing. If there are future plans to add many more options, it can be revisited then.

**Comment by draganescu** [comment]
I would rather move it back to the top of the popover and keep the advanced toggle 🤷🏻 because these are advanced options for links and because the folks annoyed by the recent changes want it as it were.

**Comment by richtabor** [comment]
> I would rather move it back to the top of the popover and keep the advanced toggle 🤷🏻 because these are advanced options for links

I don't this this works, bringing the whole toggle to the preview. But we could do something like this potentially, respecting the same user preference that the advanced toggle has, where it says open if you've toggled it open. 

https://github.com/WordPress/gutenberg/assets/1813435/fc5e7adb-7379-4c9e-8a0d-096fbc4f539b

Here's bringing the whole toggle: 


https://github.com/WordPress/gutenberg/assets/1813435/90a13fb5-d06c-4ca1-b205-ef616705075f

**Comment by draganescu** [comment]
i like the integrated toggle next to the actions in the preview, makes more sense to me. I just don't know if it's worth losing the copy link button.

**Comment by richtabor** [comment]
> I just don't know if it's worth losing the copy link button.

Agreed.

**Comment by richtabor** [comment]
Here it is with the copy icon as well: 

CleanShot 2024-04-24 at 16 10 50

**Comment by t-hamano** [comment]
In #61056, it was suggested to add custom CSS. If this were implemented, the layout would look like this: If there is a possibility that custom CSS will be added in the future, we may want to leave the Advanced toggle as is.

image

**Comment by richtabor** [comment]
Closing as we don't have consensus on the direction yet.

**Pull request closed without merging**
