### PR TITLE
Add support for TikTok video Embeds

### LINKED ISSUE #19342: Add support for TikTok videos
PR to add the support: [https://github.com/WordPress/wordpress-develop/pull/126](https://github.com/WordPress/wordpress-develop/pull/126)

### PR DESCRIPTION
**Pull request by audrasjb**
## Description
Fixes #19342

This Pull Request adds TikTok oEmbed support.
For reference, see the related Trac ticket for WP 5.4: https://core.trac.wordpress.org/ticket/49083

## How has this been tested?
Copy this test URL into the editor: https://www.tiktok.com/@scout2015/video/6718335390845095173

For reference: 
TikTok oEmbed developer documentation: https://developers.tiktok.com/doc/Embed

## Screenshots 
screencapture-localhost-8888-testing-features-test4-wp-admin-post-php-2019-12-27-11_48_18

## Types of changes
**New feature (non-breaking change which adds functionality)**
Introduce a oEmbed block support for a new resource: TikTok.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards.

### CODE REVIEW

**Comment by audrasjb** [comment]
Fixes: #19345

**Comment by mkaz** [comment]
Did not work for me. 

Steps:
1. Applied the patch, built Gutenberg
2. Confirmed TikTok embed shows in block library
3. Insert TikTok block and paste link: https://www.tiktok.com/@scout2015/video/6718335390845095173

Screenshot from 2020-01-01 08-21-17

In console:
```
Received HTML:

 index.js:287:17
Received plain text:

 https://www.tiktok.com/@scout2015/video/6718335390845095173 index.js:288:17
Processed HTML piece:

 <p>https://www.tiktok.com/@scout2015/video/6718335390845095173</p>
```

I confirmed other embeds work by embedding a YouTube video with no problems.

**Comment by jblz** [comment]
@mkaz -- I think this needs the core patch in https://core.trac.wordpress.org/ticket/49083 to work since it leverages the core embed block functionality.

**Comment by audrasjb** [comment]
Ah yes sorry @mkaz I forgot to mention it has to be tested with the core patch. Thanks @jblz !

**Comment by peterwilsoncc** [comment]
I’m happy for the core ticket to go in to the WordPress 5.4 or 5.5 release. 

If committed to 5.4 does that leave enough time for the editor changes to be committed too or do you need a little more time?

**Comment by audrasjb** [comment]
Hi there,
For information, my patch was merged in WordPress Core for 5.4: https://core.trac.wordpress.org/ticket/49083.

**Review by jorgefilipecosta — APPROVED** [review]
Works well in my tests after the patch was committed 👍

**Pull request merged**
