### PR TITLE
Docs: add tutorial for creating a custom block editor instance 

### PR DESCRIPTION
**Pull request by getdave**
## Description

I wrote a "tutorial" (more a "walkthrough guide") on creating a custom instance of the block editor within WP Admin.

This is highly relevant as the Full Site Editing project editor starts to expand the editor beyond Post content.

This tutorial was originally published on [a standalone repo](https://github.com/getdave/standalone-block-editor), but having spoken with @youknowriad he's suggested it might be useful as a public tutorial within the Gutenberg docs.

This PR:

* ports over the content.
* rewords as required to make suitable for Gutenberg project docs.

Note that the code for the tutorial still lives in the original repo. I wonder whether this should be moved within the Gutenberg project somehow to ensure it is preserved.

## How has this been tested?

This tutorial has been reviewed by members of the Core team including @epiqueras and @youknowriad.

To test you can:

* Read through the tutorial.
* Check it has been worded in a way that is suitable for inclusion in public-facing docs.
* Check for spelling/grammar errors.
* Ensure appropriate links are in place.

## Types of changes
New feature (non-breaking change which adds functionality).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by getdave** [comment]
Question - as it's quite long, should we split this tutorial up over multiple (interlinked) files with one per "section"? This might make it easier to consume.

**Comment by gziolo** [comment]
Wow, this is an awesome tutorial to include 🥇 

> Question - as it's quite long, should we split this tutorial up over multiple (interlinked) files with one per "section"? This might make it easier to consume.

@mkaz or @nosolosw - might have the best answer here as they authored several existing tutorials.

**Comment by gziolo** [comment]
@getdave – it would be nice to optimize the size of media included because it's something all contributors will have to download. Ideally, all those assets are hosted outside of git so we don't keep all versions in its history.

**Comment by getdave** [comment]
> Wow, this is an awesome tutorial to include 🥇

Thanks 🙇 

> it would be nice to optimize the size of media included because it's something all contributors will have to download.

I've resized to 800px in width and run through an image optimizer. Now slimmed down.

> Ideally, all those assets are hosted outside of git so we don't keep all versions in its history.

Do we have a preference for where?

**Comment by mkaz** [comment]
@getdave @gziolo I've split between one long post, or multiple pages. I think my preference now is a single long post with anchor links on the headings that make them bookmarkable so you can link/jump to any section.

As far as assets, we don't have a great solution. Previously we've attached them to Github tickets and then referred to the absolute URL being served from Github. If you have author writes, you can also upload to the developer.wordpress.org blog media library and use the absolute URL from there.

**Comment by gziolo** [comment]
> >  it would be nice to optimize the size of media included because it's something all contributors will have to download. Ideally, all those assets are hosted outside of git so we don't keep all versions in its history.

> As far as assets, we don't have a great solution. Previously we've attached them to Github tickets and then referred to the absolute URL being served from Github. If you have author writes, you can also upload to the developer.wordpress.org blog media library and use the absolute URL from there.

@mapk or @karmatosed – what's the preferred approach for design-related assets? We should follow the same approach.

**Comment by aduth** [comment]
Regardless of precedent, I would strongly advocate against including image assets in the repository, since this adds significant _non-recoverable_, _non-diffable_ growth to the downloaded clone size of the repository, which already exceeds 300MB. At least in the context of GitHub, it's fairly straight-forward and consistent to use GitHub's image uploading (via comment box or issue form). It's maybe questionable in how we sync this content to WordPress.org. It should still work, I expect. Alternatives like [Cloudup](https://cloudup.com/), WordPress.com, or WordPress.org (for those with access) could be possible as well.

**Comment by chrisvanpatten** [comment]
@getdave could your sample repo be a candidate to move into the `gutenberg-examples` repo?

**Comment by mkaz** [comment]
I think this would be a good candidate to move to a new section I just created in the developer documents ( PR #20666 ) for Gutenberg as a Platform.

I believe @youknowriad discussed it previously with me about needing a spot for documents on developers using Gutenberg Packages, not just for extending within WordPress but for any app development. I feel your tutorial fits this nicely.

Your tutorial is great, and provides a ton of knowledge to learn the platform, but better in an advanced section. The tutorials section feels like it should focus more on things a WordPress developer would do for creating a plugin to extend the editor or other parts of WP. 

Thoughts?

**Comment by getdave** [comment]
>  I've split between one long post, or multiple pages. I think my preference now is a single long post with anchor links on the headings that make them bookmarkable so you can link/jump to any section.

@mkaz All done. Please could you 👍 if you're happy?

> I think this would be a good candidate to move to a new section I just created in the developer documents ( PR #20666 ) for Gutenberg as a Platform.

@mkaz Agreed. Could you let me know the anticipated timeline for when your PR might land? 

I'm keen to get this tutorial merged as soon as I can so things don't change underneath me 😄

**Comment by mkaz** [comment]
I think the PR #20666 is ready to go now, its more of a stub page for things to be added to as we go. If you can give me a 👍 there I'll merge it in. Then you can adjust this PR to move into that new directory and we'll be good to ship.

Does that work?

**Comment by getdave** [comment]
About to sort out media files

**Comment by mkaz** [comment]
@getdave :+1: thanks for the approval #20666 is merged. Ready for you to move into that new dir.

**Comment by getdave** [comment]
@mkaz Shall I just create `platform/tutorials/custom-block-editor` and link to that from the main `README.md` in `/platform`?

**Review by mkaz — APPROVED** [review]
This is looking good, thanks! :shipit:

**Comment by Soean** [comment]
@getdave Great tutorial! 

I can't find it in the block editor handbook: https://developer.wordpress.org/block-editor/ 
I think we need to add it to the manifest and toc json file in the docs folder, right?

**Comment by mkaz** [comment]
@Soean Added in: https://github.com/WordPress/gutenberg/pull/20749

It is also listed on the bottom of this page: https://developer.wordpress.org/block-editor/developers/platform/

But the link doesn't work and everything looks right, is that because it's not in the Table of Contents?

**Pull request merged**
