### PR TITLE
Toolbar Arrow Navigation (just adding ESC behaviour)

### PR DESCRIPTION
**Pull request by ephox-mogran**
## Description

*NOTE: Only merging to an existing branch, not master*

Building on #2960, just adding the ability for pressing ESC to refocus the block (in whatever way the particular block receives focus)

## How Has This Been Tested?

Just manually.

## Types of changes

Bug fix for ESC to focus editable areas

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation. (no documentation was there)

### CODE REVIEW

**Comment by ephox-mogran** [comment]
@youknowriad I've noticed that pressing ESC in the toolbar for image blocks has no effect. Is that intended?

**Comment by youknowriad** [comment]
Like discussed in DM, this approach doesn't work seamlessly in all the blocks because we're not making a strong difference between the "selected" and the "focused" state in the store. I think we should keep the current approach for now, and try to bring this focused/selected state in a separate PR.

**Comment by ephox-mogran** [comment]
@youknowriad has 

>  we're not making a strong difference between the "selected" and the "focused" state in the store

started to be resolved anywhere?

**Comment by youknowriad** [comment]
I know @mcsf had thoughts about this. I don't know if he started something or not. Also, the vertical navigation PR might be related.

**Comment by mcsf** [comment]
Nothing yet, no. Just loose thoughts in my head. Selection vs. focus is a thing to address after vertical nav (#2988), I believe.

**Pull request closed without merging**
