### PR TITLE
Add basic tsconfig.json validation

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Adds a very basic script to validate that each package's `tsconfig.json` contains references for any `@wordpress/` dependency that has typings. 

For example if `deprecated` appears in `block-editor`'s `package.json`, and both `block-editor` and `deprecated` have a `tsconfig.json`, then `deprecated` must appear in `block-editor`'s `tsconfig.json`.

## Why?
I was working on https://github.com/WordPress/gutenberg/pull/47229 and it took me a billion years to figure out that a "Missing type declaration" error was to do with a missing reference in a completely unrelated package. 

## How?
Adds a new `bin` script similar in nature to the existing `validate-package-lock.js` script. It is ran as part of `npm run lint`. I think this means it's ran in CI but not on `git commit`. Maybe that's something we can improve. I figure anything is better than nothing, though.

I also fixed all missing references in the project.

## Testing Instructions

`npm run lint:tsconfig`

### CODE REVIEW

**Review by ciampo — APPROVED** [review]
Looks like a good improvement to me!

Although I'd prefer if someone else, more experienced with the repo's overall structure and scripts strategy, also took a look before merging.

**Comment by noisysocks** [comment]
Thanks @ciampo!

> I think this means it's ran in CI but not on `git commit`. Maybe that's something we can improve. I figure anything is better than nothing, though.

Realised that this is really easy to configure via the `lint-staged` array in `package.json`, so did that. I then tested by attempting to delete some `tsconfig.json` references and running `git commit`. It didn't let me! 🎉

**Comment by kevin940726** [comment]
Just a thought: I wonder if this is achievable with eslint? 😅

**Comment by noisysocks** [comment]
Please elaborate! I thought it only checked JavaScript?

**Comment by noisysocks** [comment]
> Although I'd prefer if someone else, more experienced with the repo's overall structure and scripts strategy, also took a look before merging.

Let's cc. @gziolo who is my go-to for such things 😀 but to be honest I'm pretty confident in this so will just merge. If something breaks can fix or revert.

**Review by adamziel — COMMENTED** [review]
This is great, thank you @noisysocks

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.

**Pull request merged**
