### PR TITLE
Upgrade Storybook to V7

### LINKED ISSUE #53502: Storybook regressions after TypeScript 5.1 update
The recent update to TypeScript 5.1 (#52621, #53445) has caused some breakage in our Storybook:

- The components props tables do not show information sourced from TypeScript data anymore. We are missing a huge chunk of props documentation and controls.
- Event handlers such as `onChange` are not showing up as expected in the Actions panel. It seems like everything with configured with `actions: { argTypesRegex: '^on.*' }` is broken. In some cases, when the handlers are called in component story code without an optional (`onChange()` vs. `onChange?.()`), the story will crash on the first change event.

## How to address

We'll first try to update Storybook to v7 to see if these issues might be resolved naturally. This upgrade was planned from before and we are now unblocked due to the Node upgrade in #53426.

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

While doing the node/npm migration, I've noticed a few messages when installing packages. Among them, the fact that we're using a few deprecated packages. I'm trying to clean these out a little bit.

I noticed that our Storybook dependency was responsible for like 5 of these warnings, so in this PR I'm trying to upgrade it to the latest version. Also upgrading reduces the vulnerabilities number that npm highlights.

## How?

- I've used the "upgrade" script storybook ships but I also had to make some edits to the "types" mainly. 
- I also had to add the `.story` suffix to the stories files to avoid having to recreate the Webpack config entirely.

## Todo

- [x] mdx based stories are still not working.

### CODE REVIEW

**Comment by mirka** [comment]
There are also a few regressions #53502 I'm hoping this might resolve.

**Comment by youknowriad** [comment]
Ok I've fixed most of the stories, last blocker I've seen is the mdx stories.

**Comment by youknowriad** [comment]
Tried several things, I'm kind of stuck, I'm not sure what's preventing the mdx stories from rendering.

**Comment by youknowriad** [comment]
Ok, in the last commit, I'm making progress. I managed to make the "introduction" mdx file work (had to change file names to drop the .story suffix) but now importing other markdown files seems broken (as seen in the contributing page)

**Comment by youknowriad** [comment]
This should be ready I think. Worth noting that:

 - I removed the description loader (from comments) because it's seems that it works like that by default now in Storybook 7.
 - I removed the source link loader because I was not able to make it work with the updated Webpack config. I think it's a nice little thing but I don't see it as crucial. Thoughts @mirka. I actually wonder if it's better to do this manually (like Storybook docs suggests).

**Review by mirka — APPROVED** [review]
Thank you so much for getting this sorted!

I can confirm that the regressions in #53502 are fixed, and I tweaked `source-link-loader` to work again.

There are a a few smaller things that I'm noticing, but I'll address those later. I'd like to get this PR merged ASAP because the Storybook is very unusable right now 😄

**Comment by youknowriad** [comment]
Cool, thanks for the fix.

**Comment by bangank36** [comment]
Since Storybook 7.1 there is an option to enable Story's Table of content (to compensate the removing of Docs tab), do you think it worth enabling this option globally by default @youknowriad 
[More info ](https://storybook.js.org/docs/angular/writing-docs/autodocs?ref=storybookblog.ghost.io#generate-a-table-of-contents)
image
cc @mirka

**Comment by mirka** [comment]
> Since Storybook 7.1 there is an option to enable Story's Table of content (to compensate the removing of Docs tab), do you think it worth enabling this option globally by default

I didn't know about this, thanks for letting us know!

I just tried it out, but personally I don't think it's worth the screen space that it takes up, at least in most scenarios right now. And the TOC generation doesn't seem super reliable, as can be seen in the Contributing Guidelines.

**Comment by bangank36** [comment]
> I don't think it's worth the screen space that it takes up, at least in most scenarios right now.

I see 👍 

> TOC generation doesn't seem super reliable

Are you mentioning about the Heading 1 and Heading 2 are skipped? It is because the default value of `headingSelector` is `h3`, we can change it to `h1,h2,h3`

```
docs: {
		toc: {
			headingSelector: 'h1, h2, h3'
		}, // 👈 Enables the table of contents
	},
```

image

**Comment by mirka** [comment]
> > TOC generation doesn't seem super reliable
> 
> Are you mentioning about the Heading 1 and Heading 2 are skipped? It is because the default value of `headingSelector` is `h3`, we can change it to `h1,h2,h3`

Ah, good to know, thanks!

**Pull request merged**
