### PR TITLE
Fix footer icon

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
By testing this PR: https://github.com/WordPress/gutenberg/pull/29195, I saw that `footer` icon did not provide some props properly.

### CODE REVIEW

**Review by aristath — APPROVED** [review]
Nice catch! :+1:

**Comment by jasmussen** [comment]
Awesome!

Did you try removing both the fill rule and clip rules? Sometimes they are needed, most times they are not.

**Comment by ntsekouras** [comment]
>Did you try removing both the fill rule and clip rules? Sometimes they are needed, most times they are not.

@jasmussen I did not. How can I check if they are needed? I think I might miss some small detail that a designer would catch :)

**Comment by jasmussen** [comment]
The easiest way is to remove the rule, compile, and see if the icon still looks right. Might need to restart npm run dev.

**Comment by ntsekouras** [comment]
Seems that `clipRule` could be omitted, but `fillRule` is needed.

**Review by jameskoster — APPROVED** [review]
🙇‍♂️

**Pull request merged**
