### PR TITLE
Eriktdesign add/tags in latest posts block

### PR DESCRIPTION
**Pull request by draganescu**
WORK IN PROGRESS!

## Description
Props @eriktdesign, this is a refresh of #19755 
Moves #13027 forward by adding filtering by tags.

## How has this been tested?
Tested locally.

1. Make sure you have some posts with tags
2. Make a new post/page
3. Add a `LatestPosts` block 
4. Use the tag filter in the inspector

## Screenshots 

Screenshot 2020-03-11 at 12 19 31

## Types of changes
Non breaking addition to `LatestPosts` and `QuerySelector`

## Checklist:
- [ ] Make the tag list a multiple selection

### CODE REVIEW

**Comment by draganescu** [comment]
I updated this but currently have some glitching behavior when tags are added:

image

**Comment by draganescu** [comment]
There are also a design issue that should be solved for this PR:

- The token field for adding tags supports adding tags when the tags don't exist. However in this context I don't expect that a non-existent tag should work. So when I type some text for which there are no suggestions:

a) nothing happens and ENTER key makes my text disappear (current behavior)
b) some warning message is shown that there is no such tag

I will implement b) but a sort of mock-up as to where should I display that message would be good.

**Comment by pbrocks** [comment]
Using Gutenberg.run, I added some posts via XML, then added the Latest Posts block to another post. The block showed the latest 5 posts by default and when a tag is added to the input element in the inspector controls, the block refreshes with newly polled data according to the new criteria.

latest-posts-polls-4-tags-gutenberg-run

**Comment by draganescu** [comment]
Closed b/c of lack of traction and the upcoming Query block's replacing the LP block.

**Pull request closed without merging**
