### PR TITLE
fix: block selection if block is aligned left or right

### LINKED ISSUE #24653: Dynamic blocks become unselectable when aligned left or right
When a dynamic block is aligned to the left or right, it is almost impossible to select it. This is only possible by clicking on a very narrow section right above the block. In that case the border which normal would wrap around the block, becomes a thin line above the block. Also the little toolbar is aligned all the way to the left.

I did a bit of digging and it seems like dynamic blocks add a `<div class="wp-block" data-align="right">` inside of the main `<div class="block-editor-block-list__block">`. While the other blocks wrap that same `<div class="wp-block" data-align="right">` around (outside) of the main `.block-editor-block-list__block`.

After changing this around for the dynamic block, it becomes selectable again and it now also shows the correct blue border/outline again.

**To reproduce**
1. Add the Latest Posts block to a post
2. Align it to the right.
3. Click somewhere else, and try to select the Latest Posts block again

**Expected behavior** 
After clicking on the block which is aligned to the right, the item becomes selected.

**Current behavior** 
A block which is aligned right/left can only be selected by clicking on a thing invisible area above the block. When selected it shows a blue border above and the toolbar is all the way to the left.

**Screenshots**
Screenshot 2020-08-19 at 13 46 46

**Editor version:**
- WordPress version: 5.5
- Bug is present with or without latest Gutenberg installed

**Desktop:**
 - OSX 10.15.6
 - Firefox 79

### PR DESCRIPTION
**Pull request by devfle**
## Description

Fixes: #24653 
Currently there is the problem with many blocks, as soon as they are positioned left or right, that you can no longer select them in gutenberg. This is caused by a floating that is written to the block (data attribute) when the block is positioned with the GUI. I have now added a "clearfix" to the whole thing. This is the most common and modern way to solve the float problem.

## How has this been tested?

I inserted several blocks in Gutenberg and then positioned them. I repeated this in several browsers.

## Screenshots 
Bildschirmfoto 2020-08-20 um 23 30 49

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by maartenhunink** [comment]
Hey @devfle, tnx for working on this. 

This does fix the selectability of the block, and adds the border around the block again. But the content doesn't flow around the block anymore, since the entire block isn't aligned to the right. 

Screenshot 2020-08-21 at 08 46 46

As mentioned in the bug report, this issue only appears with dynamic blocks and it seems to have something to do with the html markup, and not specifically with the css. If you compare the html markup of a 'normal' block which is aligned to the right, and a dynamic block (for instance the Recent Posts) you will see that the `<div class="wp-block" data-align="right">` is in a different place. I believe this is unintentional and that the bug might be fixed if this is corrected with the dynamic blocks.

**Comment by broken8** [comment]
I can confirm that **Gutenberg v8.3.0** does **not** have this issue. I am using this version with WP 5.5 for development with no issues so far. All versions after 8.3.0 possess this issue. I have also been able to fix by adjusting in-browser and believe @maartenhunink's fix is what is required.  This is a markup issue. It should look like this:

```html
<div class="wp-block" data-align="left">
  <div aria-label="Block: Pullquote" role="group" data-align="left" id="block-07fbf7e1-5313-etc-etc>
    <figure class="wp-block-pullquote"></figure>
  </div>
</div>
```
... but for some reason the parent `wp-block` class appears after the `block-editor-block-list__block` class and before the `wp-block-xxxxxxxxxxx` class in versions after 8.3.0.

**Comment by maartenhunink** [comment]
Hey @devfle, did you manage to find out where this could be changed?

**Comment by devfle** [comment]
Hi, sorry for the late answer. I'm currently super busy and didn't make it. I'll have another look tonight and if I find anything I'll get in touch with you. If not, I need support. I was hoping it would be easier.

**Comment by broken8** [comment]
@maartenhunink, @devfle: I got this to work with CSS:
```css
[data-type="core/pullquote"][data-align="left"] {
    position: relative;
    z-index: 99;
}
```
The block becomes clickable and editable, but now my styles need a complete redesign! If the markup is changed again... !! ??

**Comment by devfle** [comment]
Hmm.. sounds weird. I dont have an idea 🙁 Which file is generating the DOM from the Block ?

**Comment by maartenhunink** [comment]
I have no idea, I was hoping somebody else has more experience with this.

**Comment by annezazu** [comment]
Closing this PR out in light of the initial issue it solves being closed too: https://github.com/WordPress/gutenberg/issues/24653  Feel free to reopen if needed!

**Pull request closed without merging**
