### PR TITLE
[RNMobile] Search block: Add button position UI support

### PR DESCRIPTION
**Pull request by AmandaRiu**
## Description
This PR builds on the branch for #29045 and as such, that PR must be merged before this one can be taken out of draft. This PR is a continuation in the Saga to port the Search Block to mobile. It adds the UI elements for the "button position" options:
- `button-inside`: search button is inside the borders of the search text input box. 
- `button-outside`: search button is outside the borders of the search text input box.
- `no-button`: search button is completely removed. 

This PR also removes the temporary alert messages used for testing in #29045, as well as cleans up some of the styling. 

Special note:
- The styles for this component are not yet finalized so the styling done here is just to get the overall layout of the button position UI implemented. The final version may have some variations. There will be another PR that focuses strictly on implementing styles and themes.

### Gutenberg Mobile PR
https://github.com/wordpress-mobile/gutenberg-mobile/pull/3196

## How has this been tested?

Tested inside the demo and WordPress apps for Android and iOS (emulator and simulator). Below are the testing instructions:

1. Add the search block to a post. The default button position setting will be `button-outside`. Verify the layout matches the default option.
2. Change the button position to **Button inside**. Verify button placement. 
3. Toggle the **icon only** option - verify **Button inside** is still valid. 
4. Change the button position to **Button outside**. Verify button placement. 
5. Change the button position option to **No button**. Verify the button disappears and the text input box expands to fill the horizontal space. 

### Button Outside

button-pos-outside-text

button-pos-outside-icon

### Button Inside

button-pos-inside-text

button-pos-inside-icon

### No Button

no-button

## Types of changes

This is a new feature for the mobile platform that will be spread across multiple PRs. The main issue for this project can be found [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3073). 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards.  **(will be handled in later PRs)**
- [x] I've tested my changes with keyboard and screen readers.  **(will be handled in later PRs)**
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
cc: @iamthomasbishop

**Comment by cameronvoell** [comment]
UI Updates look fantastic. I think I found an issue where selecting the the placeholder in the search text entry UI does not select the block. See steps below:

1. Add a search block and one other block (I tested with image block)
2. Select the image block
3. Now click in the text placeholder in the text entry portion of the search block
4. Note that the block is not selected, and the toolbar does not update. 
*Note that if you click on the Search label text, or the Button text in a search block it does select the block properly, it's only the placeholder that is not making the block selected when gaining focus.

Expected:
Clicking on the placholder text in the sentry entry UI of the search block should main that block gain focus in the editor.

**Comment by AmandaRiu** [comment]
@cameronvoell I've updated the branch with changes from trunk so the demo app runs properly again. AFA:

> I think I found an issue where selecting the the placeholder in the search text entry UI does not select the block. See steps below:

I'm going to fix that in a separate PR to keep the changes specific to the feature implemented. Thank you for the review and ready for another round!

**Review by cameronvoell — APPROVED** [review]
Since the button positioning changes all look good here, this PR is ready to go. We'll tackle issues around text field focus in a follow up PR as we discussed in another thread.

**Pull request merged**
