### PR TITLE
Add documentation for mobile components directory

### PR DESCRIPTION
**Pull request by dcalhoun**
## Description
Provides a high-level description of the intent of the `packages/components/src/mobile` directory, which houses mobile-specific components.

## How has this been tested?
Reviewed documentation file on GitHub.com.

## Screenshots 
n/a

## Types of changes
Documentation

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
Have you considered extracting this folder as its own component? `@wordpress/components` is already big and the `mobile` folder gets published to npm but it's rather difficult to consume those native components as is. Is there anything that you think which might be a good reason to keep it as is?

**Comment by dcalhoun** [comment]
> Have you considered extracting this folder as its own component? `@wordpress/components` is already big and the `mobile` folder gets published to npm but it's rather difficult to consume those native components as is. Is there anything that you think which might be a good reason to keep it as is?

@gziolo no, I had not considered that option. This small change was done in hopes of providing some clarity as to the origin and purpose of the directory. 

However, in the spirit of keeping web and native initiatives closer, I wonder if it makes more sense to collapse this directory rather than retain or relocate it. I.e. move its files up a directory to align with all other components. Additionally, some the components within the `mobile` directory now have web counterparts, e.g. `SegmentedControl`. 

WDYT?

**Comment by gziolo** [comment]
> However, in the spirit of keeping web and native initiatives closer, I wonder if it makes more sense to collapse this directory rather than retain or relocate it. I.e. move its files up a directory to align with all other components.

My primary concern is related to documentation. How to make it clear which component can be used in which context: web, mobile, or both. Now, we ignore README files from the mobile subfolder when generating the handbook section for components. Thanks to that folks no longer get confused about mobile only components that can’t be used with WordPress.

> Additionally, some the components within the mobile directory now have web counterparts, e.g. SegmentedControl.

It would be great to combine together web and mobile implementations and share API.

**Comment by dcalhoun** [comment]
> My primary concern is related to documentation. How to make it clear which component can be used in which context: web, mobile, or both. Now, we ignore README files from the mobile subfolder when generating the handbook section for components. Thanks to that folks no longer get confused about mobile only components that can’t be used with WordPress.
 
> It would be great to combine together web and mobile implementations and share API.

Aligning implementations where possible and communicating divergences makes total sense. Communicating when a component or particular facet of the API is platform-specific could be done through documentation; similar to how React Native documentation tags [a given prop as iOS-only](https://reactnative.dev/docs/text#minimumfontscale-ios). 

<details><summary>React Native Example</summary>

react-native-platform-specific-prop

</details>

In fact, there is already an instance in `Tooltip` where [the `visible` prop is platform-specific](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tooltip/README.md#visible-native-only). Of course, a perfectly aligned API across all platforms is more desirable and may be possible in the `Tooltip` example, but I do not believe it will always be achievable. 

Because there will likely be instances where components are cross-platform but diverge slightly in very unique circumstances, I feel placing mobile-specific components to a separate package may be counterproductive. WDYT about having documentation that is explicit about platform-specific components/APIs rather than placing mobile components to a separate package?

**Comment by gziolo** [comment]
It's really up to you and it all depends on a good strategy to flatten the folder structure and ensure that mobile-only components aren't exposed to the Block Editor Handbook:
https://developer.wordpress.org/block-editor/reference-guides/components/

At the moment we explicitly ignore README files in the `packages/components/src/mobile` directories:

https://github.com/WordPress/gutenberg/blob/4a6d0068bb8171518dafe702b6b2a725a5cb47f4/docs/tool/manifest.js#L12-L13

It would stop working when all components would be located in the top folder, but if you have an alternative then feel free to change the structure as it fits you.

**Review by AmandaRiu — APPROVED** [review]
@dcalhoun The text looks good to me. Regarding the conversation above, I'll support wherever you choose to put it 👍

**Pull request merged**
