### PR TITLE
Post title: remove class from old div to fix alignment

### LINKED ISSUE #34479: Broken editor style in some themes (Twenty Twenty and Twenty Nineteen)
### Description

I've stumbled upon a few styling oddities when trying Gutenberg v11.4.0 with some themes, namely `Twenty Twenty` and `Twenty Nineteen`. I assume this issue _could_ be more widespread and affect other themes in unexpected ways, too (?)

WIth `Twenty Twenty`, the page title input has shifted way to the left of the page, not aligning with the block list area horizontally:

TwentyTwenty

_Left is v10.3.0, right is v11.4.0._

In the case of `Twenty Ninteteen`, the same problem exists (though it looks like it was already present in previous versions of Gutenberg), but there's one minor issue thing that seems to have been introduced by v11.4.0:

twentynineteen

_Left is v10.3.0, right is v11.4.0._

I've bisected and it seems to have been introduced by this changeset: https://github.com/WordPress/gutenberg/pull/34167.

### Step-by-step reproduction instructions

1. Using `trunk` or `v11.4.0`, set the theme to `Twenty Twenty` or `Twenty Nineteen`;
2. Start a new page or post;
3. Verify how the alignment between the title and the block list area looks odd. In the case of `Twenty Nineteen`, there's another minor alignment issue (see screenshot above);
4. If you built from source, try reverting `e30d875` and rebuild Gutenberg;
5. Verify that `Twenty Twenty` looks fine now. `Twenty Nineteen` still looks odd, though one of the alignment issues is gone (refer to the screenshots above for a visual reference).

### Environment info

- Wordpress `5.8-beta4-51266`;
- Gutenberg `v11.4.0` (or built from `trunk`);
- Ubuntu Linux 18.04;
- Firefox 92.0b9 (64-bit)

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #34479.

A div was removed in #34167. Instead of moving the class name to another div, we should just remove it as well. Also adds `block-editor-block-list__block` so some theme styles apply properly.

Note that the post title refactors prepare it for switching over to the post title _block_ eventually.

## Screenshots 

Screenshot 2021-09-02 at 12 24 47
Screenshot 2021-09-02 at 12 33 56

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by chad1008** [comment]
This helps, thanks @ellatrix!

It does look like some of the styles (specifically in Twenty Twenty, I haven't tested other themes yet) are still missing their targets. In the case of Twenty Twenty this impacts the size of the title and the alignment. While this PR currently centers the title element in the editor, the text within the element is still left aligned. Three screenshots for comparison:

11.3.0 (the goal)
Screen Shot 2021-09-02 at 11 30 41

11.4.0 (unpatched)
Screen Shot 2021-09-02 at 11 27 44

This PR
Screen Shot 2021-09-02 at 11 25 10

When comparing the first and last screenshots, it looks like the text is still smaller and not centered as it was pre-11.4

**Comment by ellatrix** [comment]
That's because the theme styling is no longer applying. What you see is the same as a h1 element. If you insert a post title block, you'll see that the styling is the same for that block. Eventually the post title will be replaced with a post title _block_.

I think the small change in style is fine. There's no breakage and themes can adjust the selectors if they wish.

**Comment by fullofcaffeine** [comment]
> That's because the theme styling is no longer applying. What you see is the same as a h1 element. If you insert a post title block, you'll see that the styling is the same for that block. Eventually the post title will be replaced with a post title block.

> I think the small change in style is fine. There's no breakage and themes can adjust the selectors if they wish

@ellatrix Am I correct assuming those are then expected style changes in v11.4+ and that theme developers should be already aware of them and will fix them soon?

**Comment by fullofcaffeine** [comment]
There's also this z-index (?) glitch that @talldan reported: https://github.com/WordPress/gutenberg/issues/34479#issuecomment-911133409, though it appears to be an older bug.

**Review by fullofcaffeine — APPROVED** [review]
Thanks for the quick fix, Ella! I'm accepting this knowing that there might be other adjustments we might need to do as follow ups, and being aware that theme folks also need to either patch themes or wait for the `Post Title` block.

**Comment by ellatrix** [comment]
> @ellatrix Am I correct assuming those are then expected style changes in v11.4+ and that theme developers should be already aware of them and will fix them soon?

They are not aware, so maybe we should do a dev note when the WP release comes. To me it's no big deal since the title is still styled as heading level 1, and themes can choose to modify the styling if they wish.

**Comment by ellatrix** [comment]
Added the dev note label. Dev not should be something like: A div wrapper element around the post title in the post editor has been removed to align it better with the post title _block_. Some theme styles targeting the post title (that include the removed div's class name) may no longer apply. Please use the `wp-block-post-title` class to style the post title, which will also style the post title block.

**Pull request merged**
