### PR TITLE
Try extra wrapping element around floated images

### PR DESCRIPTION
**Pull request by jasmussen**
This adds a wrapping DIV around a floated image. This makes it easier for themers to float images with captions in wide and fullwide layouts. 

This description has been edited for clarity.

### CODE REVIEW

**Comment by jasmussen** [comment]
This fixes #5292.

**Comment by jasmussen** [comment]
Would this PR be more digestible if the wrapping element was only added if a theme opted in to wide and fullwide styles? The wrapping element is only really necessary in that environment in the first case.

**Comment by aduth** [comment]
>The reason being — the `figure` element cannot be a child of a `p`

Can you explain in what context it would be a child of `p`?

**Comment by jasmussen** [comment]
> Can you explain in what context it would be a child of p?

Any child of the p element can be considered an "inline" element, and it was suggested at one point that floats could be inline elements. But then they can't have the figure element.

**Comment by aduth** [comment]
But I don't understand when the image block would be a descendent of `p`.

**Comment by jasmussen** [comment]
> But I don't understand when the image block would be a descendent of p.

Well in this PR, that wouldn't be the case as I'm wrapping it in a DIV instead.

The reason for using a P, would be to make layouts like suggested in https://codepen.io/joen/pen/oEYVXB somewhat more simple, as we can presume that the P element has a centering & max width style on it. I recognize this would not be ideally semantic.

**Comment by jasmussen** [comment]
Adding back the "In Progress" label, as I realized that this PR will become moot if https://github.com/WordPress/gutenberg/pull/5973 gets merged in without big changes. So it should sort of be one or the other.

**Comment by jasmussen** [comment]
Closing, as #5973 which is the other approach, has been merged.

**Pull request closed without merging**
