### PR TITLE
Navigation: Explore default frontend styles

### PR DESCRIPTION
**Pull request by frontdevde**
## Description
This is an exploratory (!) draft PR to see what the default styling for the navigation menu block could look like on the Frontend. As outlined in the related issue https://github.com/WordPress/gutenberg/issues/17542 the styling is supposed to be minimal as the styling should mostly be handled by themes.

~~In https://github.com/WordPress/gutenberg/issues/17542#issuecomment-544584741 it was suggested to try the _s main navigation default styles. The styles in this PR are a copy of the relevant parts of _s's [navigation menu styles](https://github.com/Automattic/_s/blob/master/sass/navigation/_menus.scss). If this is the design route we want to go down we'd probably want to modernize these styles, one can tell they are seven years old.~~

Update: Based on https://github.com/WordPress/gutenberg/pull/18094#issuecomment-546079515 this exploration is inspired by the Varia theme styles.

## How has this been tested?
- Activate "Menu Block" in the experimental Gutenberg settings
- Create a menu via the Menu Block
- Preview on the Frontend

## Screenshots 

Using the Twenty Nineteen theme:

**Before** 

Screen Shot 2019-10-28 at 16 50 56

**After** 

Screen Shot 2019-10-28 at 18 10 48

**After :hover** 

Screen Shot 2019-10-28 at 18 11 04

## Types of changes
New feature (non-breaking change which adds functionality)

## TODOs:
Should we want to go down the route of using default styles inspired by the Varia theme, we'd need to make sure to
- [x] ensure the menu indicator is shown only on items with child menus
- [x] make adjustments for small viewport screens i.e. mobile

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by obenland** [comment]
Nice! I think this is going in a really good direction.

As a next step we might also want to consider [the navigation enhancements](https://github.com/Automattic/_s/blob/master/js/navigation.js) that are bundled with many themes, to improve a11y and ux on small screens.

**Comment by ZebulanStanphill** [comment]
What if someone just wants to have a standard list-style navigation menu? Shouldn't a horizontal menu style use the Block Styles API, rather than be the default style for this block? Adding a bunch of styles to the default styling makes it hard for themes to override the styles.

**Comment by obenland** [comment]
Yeah, we could add a second style, similar to Quote blocks, etc.

**Comment by shaunandrews** [comment]
From what I understand the styles from _s are not meant to be "production ready." Instead they're really a bare-bones foundation to build from.

That said, its unclear to me if we want a more prescriptive set of styles which can still be overridden, but are "production ready" — or if we do actually want a very bare-bone set of styles.

In the mockups I've been creating for the Navigation block I've been using this minimal styling:

image

This feels like an improvement in comparison to the _s's styles, but again, its unclear if we'd want to rely on the theme to handle the styles.

**Comment by ZebulanStanphill** [comment]
I think we should be relying on theme styles as much as possible. The more core styles there are, the harder it is for themes to style stuff the way they want to style stuff. I think at the very least there should be an easy way for a theme to completely disable default core-provided front-end styles so theme authors can keep their CSS clean and lightweight (and also not have to worry about future WP updates breaking their styling).

**Comment by shaunandrews** [comment]
Also worth considering adopting some styles from Varia: https://github.com/Automattic/themes/blob/master/varia/sass/components/header/_site-main-navigation.scss

Its a little more polished than _s's and adds an indicator and background color for dropdown menus.

**Comment by frontdevde** [comment]
I've updated the styles in this exploration to be heavily inspired by the Varia theme as per @shaunandrews' suggestion. I updated the screenshots above accordingly.

> What if someone just wants to have a standard list-style navigation menu?
> Shouldn't a horizontal menu style use the Block Styles API

We could definitely explore the route of providing basic style variations for the navigation. Providing a basic vertical and horizontal option could be valuable to the user. If we want the Frontend default to look similar to the editor, we'd probably want to have horizontal as the default.

**Review by obenland — APPROVED** [review]
If @shaunandrews is happy with the styles, I think we should get this in and create a new issue to add a secondary list style.

**Comment by ZebulanStanphill** [comment]
Don't most of these styles (especially things like box shadows and transitions) belong in `theme.scss` rather than `style.scss`, so that themes can opt-in to them, rather than having them provided by default? It seems wrong to me for core to include so much front-end styling with no easy way to disable it except by overriding it with more specific CSS rules in the theme.

https://developer.wordpress.org/block-editor/developers/themes/theme-support/#default-block-styles

**Comment by ZebulanStanphill** [comment]
@shaunandrews Could you give an example? As far as I can tell, the only difference between a vertical and a horizontal menu is the styling. Semantically they should be equivalent, right?

**Comment by obenland** [comment]
> Don't most of these styles (especially things like box shadows and transitions) belong in theme.scss rather than style.scss, so that themes can opt-in to them, rather than having them provided by default?

I'd agree if themes contained styles for it. Since these will be menus living out side of theme-registered locations, no theme will have styles for it. Making them pretty much unusable without default styles (hence this PR).

**Comment by obenland** [comment]
@shaunandrews Is this style iteration good to go from your end?

**Comment by ZebulanStanphill** [comment]
@obenland Long-term, though, wouldn't page templates in themes be built using these blocks?

**Comment by obenland** [comment]
I'd expect that, yes. In which case I'd also expect themes to style them as appropriate. For any other use, like page templates supplied by plugins, or simply within posts/pages, we still need default styles.

**Review by shaunandrews — APPROVED** [review]

**Comment by frontdevde** [comment]
Merging based on the two  ✅ on the PR. Given that this block is still at an experimental stage we can continue to discuss the direction in related issues like e.g. https://github.com/WordPress/gutenberg/issues/17542.

**Pull request merged**
