### PR TITLE
Icons: tweak people icon

### PR DESCRIPTION
**Pull request by keoshi**
## Description

This PR makes a slight tweak to the `people` icon which has human representations, replacing the solid dot (generally reserved for interface elements) for a more open, outlined shape. This aims at humanizing the icon while making it distinct, and makes them much more consistent with the rest of the library.

Read the [official proposal on Make Design](https://make.wordpress.org/design/2021/05/27/proposal-to-tweak-existing-icons-and-add-new-ones/).

## Screenshot

image

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for this one! I just reviewed your other PR, https://github.com/WordPress/gutenberg/pull/32371 — which appears to include this change. Do we need to land both?

**Comment by keoshi** [comment]
Hey @jasmussen — My bad for including this change on #32371. I'd rather land this one first and rebase the other one, as intended.

**Comment by jasmussen** [comment]
Oh it wasn't a critique, honestly I'd be fine just landing the other one which includes this, and that that can land pretty quickly. Just wanted to be sure I didn't miss anything. If this is to land separately, we'd need to include here the changes suggested in https://github.com/WordPress/gutenberg/pull/32371#discussion_r643746249, about removing the duplicate icons from the post author and post comment author blocks, to point those blocks to leverage the icon library variant.

**Comment by keoshi** [comment]
I'm needlessly harsh on myself, Joen — don't worry about it. 😅 

> removing the duplicate icons from the post author and post comment author blocks

This PR only changes the `people` icon and I was under the impression that both those icons use another icon (`postAuthor`) that is introduced by https://github.com/WordPress/gutenberg/pull/32371 and not this particular PR. Is that not the case?

**Review by jasmussen — APPROVED** [review]
Oh of course, sorry I missed that! Yes, if we land the updated post author with hollow heads, we should do it here as well.

**Comment by jasmussen** [comment]
Hmm, speaking of fill rules, I'm actually seeing this for this icon:

Screenshot 2021-06-03 at 09 01 41

**Comment by keoshi** [comment]
Ah yes, I shall add the `fillRule` attribute today.

**Comment by keoshi** [comment]
Alright, `fillRule` attribute added in https://github.com/WordPress/gutenberg/pull/32354/commits/33d3e81896be779a61fd08799581f986706f2420.

Pending your review, this one should be ready to go.

**Pull request merged**
