### PR TITLE
Try WebPack RamDisk

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
I'm actually not sure that both package.json needed editing, but it seemed to fail when only the one for `wordpress/scripts` was edited.

It looks broken, in that everything is a dev dependency, but is listed as a dependency. I may need to come away and come back after reading a lot more about WebPack, and why things are the way they are here.

If some Mac users with the problem could test this out and notify if it is having any impact that would be great. In CI I have seen a 10s longer time when I glanced, but that could be the network + shared environment exaggerating latencies.

**Comment by gziolo** [comment]
What's the outcome of this exploration? What are the metrics it tries to optimize?

**Comment by Lewiscowles1986** [comment]
It didn't make it any faster, which is odd. I never got to dig too deep into it.

**Comment by Lewiscowles1986** [comment]
Interestingly I'm not able to replicate the original issue this was about in a 2012 or a 2020 mac mini

**Pull request closed without merging**
