### PR TITLE
[WIP] Move plugin registration data to store

### LINKED ISSUE #5759: Plugin API Sidebar empty when refreshing page.
## Issue Overview

When refreshing the editor when a plugin sidebar is open, the sidebar will be empty. This happens because the plugin hasn't been registered when the editor is rendered.

## Steps to Reproduce (for bugs)

1. Add a plugin sidebar. [You can use this plugin](https://github.com/Xyfi/gutenberg-api-test) or:
```
const {
	registerPlugin,
} = wp.plugins;
const {
	PluginSidebar,
} = wp.editPost.__experimental;
const {
	Fragment
} = wp.element;
const {
	dispatch,
} = wp.data;

const SidebarContents = ( props ) => {
	const onClose = dispatch( "core/edit-post" ).closeGeneralSidebar;
	return (
		<div>
			<p>Here is the sidebar content!</p>
			<button onClick={ onClose }>Close</button>
		</div>
	);
};
const Component = () => {
	return (
		<Fragment>
			<PluginSidebar name="my-sidebar" title="My sidebar">
				<SidebarContents />
			</PluginSidebar>
		</Fragment>
	);
};
registerPlugin( "my-plugin", {
	render: Component,
} );
```
2. Open the sidebar using the `wp.data.dispatch` api.
```
wp.data.dispatch( "core/edit-post" ).openGeneralSidebar( "my-plugin/my-sidebar );
```
3. Refresh the page with the sidebar open.
4. Notice that the sidebar is empty.
5. Any action that triggers a dispatch on the store will make the sidebar show up, like clicking a block.

## Expected Behavior

I expect the plugin sidebar to show up as soon as it is registered.

## Current Behavior

The sidebar is empty until an action is dispatched on the store.

## Possible Solution

Register plugins in the store.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by abotteram**
## Description

In an attempt to fix https://github.com/WordPress/gutenberg/issues/5759, I've moved the plugin registration to a new store `core/plugins`.

I have yet to accomplish that the store update actually triggers a rerender of the `PluginSidebar` slot.

The question is whether this is desirable since this allows people to circumvent the plugin validation in `registerPlugin`.

Fixes #5759 

## Types of changes

New feature.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
> In an attempt to fix #5759, I've moved the plugin registration to a new store core/plugins.

I don't think it solves the root cause of the #5759 issue. It makes it work because the changes can now be observed and sidebar can be re-rendered each time new plugin gets registered. I think we should make sure that those plugins are registered before the first render happens in the first place.

I'm also not convinced that storing `render` in the state is a great fit. I understand the reasoning behind it, but having a function or class definition inside the data layer might cause issues. You can't serialize it to persist to give an example. 

I'm not totally against the solution, but I think we should be aware of all that I mentioned when looking for a final solution.

**Comment by Xyfi** [comment]
@gziolo I wonder if rendering the editor after all plugins have been registered can really be enforced? Also, this approach does have some performance benefits because the editor can start rendering while plugins are still being loaded.

I do agree with render not being stored in the state, I just put the settings in there without thinking it through.

**Comment by aduth** [comment]
I'm not sure that it does, but I'm curious if this could be related at all to the short-cutting logic here:

https://github.com/WordPress/gutenberg/blob/f41bf3044d7248479c4ad1b9303260c184587e70/edit-post/components/plugin-more-menu-group/index.js#L14-L17

The current React context API has significant (and non-obvious) shortcomings, notably in re-renders to consuming components.

https://reactjs.org/docs/context.html

I expect this may be resolved in the [_New™_ Context API](https://github.com/reactjs/rfcs/blob/master/text/0002-new-version-of-context.md) slated for React 16.3.0.

In the meantime, I don't trust that these components will update automatically when new fills are registered.

**Comment by aduth** [comment]
I believe this is in-fact the issue, at least on some preliminary debugging. The registration of the menu fill occurs immediately after the rendering of the menu group, thus the item is not shown. Provider has built-in mechanisms to force update any rendered slot, but since the group is the parent of the slot and bypasses rendering of the slot, it will not be rerendered. We need to ensure that any component which seeks to hook into `getFills` would be rerendered when fills are updated.

I think we could emulate a "New Context"-like API, even without upgrading. I'll try to explore this.

**Comment by aduth** [comment]
Superseded by #5850

**Pull request closed without merging**
