### PR TITLE
[RNMobile] Fix ungroup functionality in `WarningMaxDepthExceeded` component

### LINKED ISSUE #55738: Ungroup option displayed in deeply nested block warning doesn't work properly
## Description

Related to https://github.com/WordPress/gutenberg/pull/54382, depending on the block types deeply nested, the ungroup option doesn't work.

## Step-by-step reproduction instructions

1. Create/open a post in the app.
2. Copy the following HTML code with a deeply nested structure.
<details><summary>Click here to display the HTML code</summary>

    <ul>
        <li>1
            <ul>
                <li>2
                    <ul>
                        <li>3<ul>
                                <li>4<ul>
                                        <li>5<ul>
                                                <li>6<ul>
                                                        <li>7<ul>
                                                                <li>8<ul>
                                                                        <li>9</li>
                                                                    </ul>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>

</details>

3. Paste the content in a Paragraph block.
4. Observe that a List block is created and that the "Block cannot be rendered ..." warning is displayed.
5. Tap on the warning message two times until a bottom sheet is displayed.
6. Tap on the "Ungroup block" option.
7. Observe that no action is performed and that the bottom sheet remains open.

## Expected behaviour

The ungroup block option should work, or if ungrouping is unavailable, remove the option from the bottom sheet.

## Actual behaviour

The ungroup block option is always displayed and doesn't work on specific cases.

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 15 (simulator)
- Operating system: iOS 17.0
- WordPress app version: 23.5

### PR DESCRIPTION
**Pull request by fluiddot**
<!-- Thanks for contributing to Gutenberg! Please follow the Gutenberg Contributing Guidelines:
https://github.com/WordPress/gutenberg/blob/trunk/CONTRIBUTING.md -->

## What?
<!-- In a few words, what is the PR actually doing? -->

When rendering content with deeply nested structures, prevent presenting the option to ungroup the block in cases where it can't be applied.

## Why?
<!-- Why is this PR necessary? What problem is it solving? Reference any existing previous issue(s) or PR(s), but please add a short summary here, too -->

Fixes https://github.com/WordPress/gutenberg/issues/55738.

## How?
<!-- How is your PR addressing the issue at hand? What are the implementation details? -->

Update the `WarningMaxDepthExceeded` component by incorporating the logic related to the Group/Ungroup buttons (used in the block options) to determine whether to use the Ungroup action and update the message displayed within the warning.

## Testing Instructions
<!-- Please include step by step instructions on how to test this PR. -->
<!-- 1. Open a post or page. -->
<!-- 2. Insert a heading block. -->
<!-- 3. etc. -->
### Can be ungrouped and edited with UBE
1. Use a WPCOM Simple site.
2. Create/open a post in the app.
3. Switch to HTML mode and copy the following HTML code with a deeply nested structure.

<details><summary>Click here to display the HTML code</summary>

```
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#cb6767"}}} -->
<p class="has-background" style="background-color:#cb6767">Level 1 </p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#b89759"}}} -->
<p class="has-background" style="background-color:#b89759">Level 2</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#816531"}}} -->
<p class="has-background" style="background-color:#816531">Level 3</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#86c64d"}}} -->
<p class="has-background" style="background-color:#86c64d">Level 4</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#58b873"}}} -->
<p class="has-background" style="background-color:#58b873">Level 5</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#58b8b8"}}} -->
<p class="has-background" style="background-color:#58b8b8">Level 6</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5880b8"}}} -->
<p class="has-background" style="background-color:#5880b8">Level 7</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5870b8"}}} -->
<p class="has-background" style="background-color:#5870b8">Level 8</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5877b8"}}} -->
<p class="has-background" style="background-color:#5877b8">Level 9</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 10</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 11</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 12</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 13</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 14</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 15</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 16</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 17</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 18</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 19</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 20</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

</details>

4. Switch back to Visual mode.
5. Observe that blocks are created and that the "Block cannot be rendered ..." warning is displayed at the bottom of the content (after level 10).
6. Tap on the warning message two times until a bottom sheet is displayed.
7. Observe that options "Edit using web editor" and "Ungroup block" are displayed.
8. Observe that the warning message references editing with the web editor and the alternative to ungroup the block.
9. Tap on the "Ungroup block" option.
10. Observe that one of the inner block levels is ungrouped (Level 11).

### Can only be edited with UBE
1. Use a WPCOM Simple site.
2. Create/open a post in the app.
3. Copy the following HTML code with a deeply nested structure.

<details><summary>Click here to display the HTML code</summary>

<ul>
    <li>1
        <ul>
            <li>2
                <ul>
                    <li>3<ul>
                            <li>4<ul>
                                    <li>5<ul>
                                            <li>6<ul>
                                                    <li>7<ul>
                                                            <li>8<ul>
                                                                    <li>9</li>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

</details>

4. Paste the content in a Paragraph block.
5. Observe that a List block is created and that the "Block cannot be rendered ..." warning is displayed.
6. Tap on the warning message two times until a bottom sheet is displayed.
7. Observe that the only option displayed is "Edit using web editor".
8. Observe that the warning message references editing with the web editor and not the option to ungroup the block.

### Can only be ungrouped
1. Use a self-hosted site without Jetpack.
2. Create/open a post in the app.
3. Switch to HTML mode and copy the following HTML code with a deeply nested structure.

<details><summary>Click here to display the HTML code</summary>

```
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#cb6767"}}} -->
<p class="has-background" style="background-color:#cb6767">Level 1 </p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#b89759"}}} -->
<p class="has-background" style="background-color:#b89759">Level 2</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#816531"}}} -->
<p class="has-background" style="background-color:#816531">Level 3</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#86c64d"}}} -->
<p class="has-background" style="background-color:#86c64d">Level 4</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#58b873"}}} -->
<p class="has-background" style="background-color:#58b873">Level 5</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#58b8b8"}}} -->
<p class="has-background" style="background-color:#58b8b8">Level 6</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5880b8"}}} -->
<p class="has-background" style="background-color:#5880b8">Level 7</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5870b8"}}} -->
<p class="has-background" style="background-color:#5870b8">Level 8</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5877b8"}}} -->
<p class="has-background" style="background-color:#5877b8">Level 9</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 10</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 11</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 12</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 13</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 14</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 15</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 16</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 17</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 18</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 19</p>
<!-- /wp:paragraph -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"color":{"background":"#5873b8"}}} -->
<p class="has-background" style="background-color:#5873b8">Level 20</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

</details>

4. Switch back to Visual mode.
5. Observe that a List block is created and that the "Block cannot be rendered ..." warning is displayed.
6. Tap on the warning message two times until a bottom sheet is displayed.
7. Observe that the only option displayed is "Ungroup block".
8. Observe that the warning message only references the alternative of ungrouping the block.
9. Tap on the "Ungroup block" option.
10. Observe that one of the inner block levels is ungrouped (Level 11).

### Can only be edited via browser (no options offered)
1. Use a self-hosted site without Jetpack.
2. Create/open a post in the app.
3. Copy the following HTML code with a deeply nested structure.

<details><summary>Click here to display the HTML code</summary>

<ul>
    <li>1
        <ul>
            <li>2
                <ul>
                    <li>3<ul>
                            <li>4<ul>
                                    <li>5<ul>
                                            <li>6<ul>
                                                    <li>7<ul>
                                                            <li>8<ul>
                                                                    <li>9</li>
                                                                </ul>
                                                            </li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

</details>

4. Paste the content in a Paragraph block.
5. Observe that a List block is created and that the "Block cannot be rendered ..." warning is displayed.
6. Tap on the warning message two times until a bottom sheet is displayed.
7. Observe that the no options are displayed.
8. Observe that the warning message doesn't reference either editing with the web editor or the option to ungroup the block.

### Testing Instructions for Keyboard
<!-- How can you test the changes by using the keyboard only? Please note, this is required for PRs that change the user interface (UI). This ensures the PR can be tested for any possible accessibility regressions. -->
N/A

## Screenshots or screencast <!-- if applicable -->

| Display all options | Only "Edit using web editor" option | Only "Ungroup block" option | No options |
|--------|--------|--------|--------|
| <img src=https://github.com/WordPress/gutenberg/assets/14905380/16974cb8-0e4e-4b1b-881a-94788f1c9374 width=300> | <img src=https://github.com/WordPress/gutenberg/assets/14905380/43c4b23f-e5b7-496f-9721-7f032b3c3a82 width=300> | <img src=https://github.com/WordPress/gutenberg/assets/14905380/8d23bd09-f7b5-453b-9afa-b7323be474da width=300> | <img src=https://github.com/WordPress/gutenberg/assets/14905380/cb1402f7-9402-493a-bb69-89604df137e7 width=300> |

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
I was able to follow the testing instructions successfully for all scenarios. Thanks for addressing this! 🚀

**Comment by dcalhoun** [comment]
Thanks for addressing this. 👏🏻 

Given the PR was approved and merged, I only briefly reviewed. One question: Are we able to cover this bug fix with an automated test? In general, I think it is a good practice to always include a test alongside a production bug fix.

**Comment by fluiddot** [comment]
> Given the PR was approved and merged, I only briefly reviewed. One question: Are we able to cover this bug fix with an automated test? In general, I think it is a good practice to always include a test alongside a production bug fix.

I completely agree, I thought of adding tests but prioritized addressing the issue to have it on time for the release. I'll work on adding integration tests for the mentioned cases, thanks for the reminder 🙇 !

**Comment by dcalhoun** [comment]
> I completely agree, I thought of adding tests but prioritized addressing the issue to have it on time for the release. I'll work on adding integration tests for the mentioned cases, thanks for the reminder 🙇 !

Prioritizing shipping the fix quickly makes total sense. Thank you for intending to follow up.

**Pull request merged**
