### PR TITLE
Editor: Unify the names of the sidebars between edit post and edit site.

### PR DESCRIPTION
**Pull request by youknowriad**
Related #52632

## What?

This PR unifies the name of the sidebars between the post and site editors. This allows us to share the same keyboard shortcut and will allow us to merge the components entirely lateR.

## Testing Instructions

1- You can test the keyboard shortcut to open/close the sidebar: `cmd + shift + ,`

### CODE REVIEW

**Comment by youknowriad** [comment]
There's a potential for a small breaking change here and it seems there's no way to avoid it entirely.
One possibility would be to keep the names used in the post editor (as it's the one that is extended more).
Obviously there's a need for a dev note here. WDYT

**Comment by fabiankaegy** [comment]
@youknowriad I think for this one we will have to worry about backward compatibility shimms sadly... I'm aware of a few instances just myself where I've used these names to add buttons in blocks to open the sidebar panel....

**Comment by fabiankaegy** [comment]
I see 119 usages in the plugin directory: https://wpdirectory.net/search/01HVRHSSHKGCZE0JXV2RPJXCQC

**Comment by youknowriad** [comment]
So what do you suggest @fabiankaegy use the names from the post editor?

**Comment by fabiankaegy** [comment]
@youknowriad what if we use the approach you outlined but add remapping for the old name?

At least for a little while. 

The main issue here is that plugins need to support multiple WP versions at the same time. So we can only adopt the new name if using it on old instances doesn't break functionality

If using the old name here gets remapped to the new name with a deprecated warning I think that would be the safer route

**Comment by youknowriad** [comment]
I thought about remapping but it doesn't work, because we can remap "actions" but we can't remap the return value of the selectors.

I think the least disruptive approach is to use the edit post names and a dev note for folks using the edit-site names.

**Comment by youknowriad** [comment]
Any thoughts on the latest approach?

**Review by fabiankaegy — APPROVED** [review]
Hmmm yeah that is too bad. 

Besides that I sadly don't have any other ideas how this could be solved. 

I don't really like having to still use the `edit-post` namespace because we want to reinforce for new things that the shared `editor` namespace is the correct approach. 

But I don't see how we can make that change without some kind of backwards compatibility handling. So this approach seems less disruptive 👍

**Comment by youknowriad** [comment]
Actually, to make this even more breakage free, I added mapping for actions and some selectors (the ones that can be remapped) 

I looked at all the usage of edit-site/template and edit-site/block-inspector in wpdirectory and the changes here should cover all of them. (Only three plugins are using these: woo, jetpack and woo blocks). The remaining one is bundling Gutenberg code.

**Pull request merged**
