### PR TITLE
Allow paste of multilines on the title.

### LINKED ISSUE #1124: Paste multi-paragraph text in Post Title does nothing
Pasting a multi-paragraph text into the Post Title currently does nothing.

This happens because PostTitle is based on RichText, and PostTitle doesn't have proper support for `onSplit` and `onReplace`.

The behavior on WEB is to paste all text as a single line in the Post Title, even if the copied text had multiple paragraphs.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1124

## Description

Updated the paste code for the title component in RN to be able to support multiline pastes.
The first line is pasted to the title and the follow up lines are added as blocks in the content.
This matches the current behavior on the web.

## How has this been tested?

This can be tested using the native demo app by running `npm run native ios` and do the following steps:

 - Start the demo app
 - Copy from another app multiple lines of text
 - Paste on the title
 - Check if the first line is added to the title and the following ones added as blocks in the content.

## Types of changes

Matches functionality between the web and native versions.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
Tested on iOS and new block creations works great! 
Although I'm not sure if this is expected but the multiline text I copied had bold, italic, etc. inside it and that was not reflected in the created paragraphs.
Also I couldn't test the Android demo app, because I think a merge from master is needed.

**Comment by SergioEstevao** [comment]
> Although I'm not sure if this is expected but the multiline text I copied had bold, italic, etc. inside it and that was not reflected in the created paragraphs.

@ceyhun I checked the code and it looks was a mistake on the way the HTML parameter was sent to the pasteHandler.

I updated the code and now it all formatting should be pasted correctly, do you mind give it another look?

**Comment by ceyhun** [comment]
Works great on iOS, also with formatting 🎉 
I was able to test on Android as well but it didn't work and title was multiline instead.

**Comment by SergioEstevao** [comment]
@mchowning any idea why it should be different  in Android? My understanding is that the paste code is the same, are doing something different for the title in Android?

**Comment by SergioEstevao** [comment]
@ceyhun I just tested this again, and I'm not seeing it do multiline in the title. Can you repeat the test?

The only thing I see is that in general it looks that in Android the paste from other apps doesn't bring the styles inside a paragraph, like bold and italic, but I can reproduce that on current master.

**Comment by ceyhun** [comment]
@SergioEstevao I just tested again and it's the same. I tested on an Android 10 emulator and an Android 9 device with the demo app. Do you maybe test on an older OS or use WPAndroid?

**Comment by mchowning** [comment]
I'm not sure what I'm doing wrong but I'm getting multiple lines pasted directly into the title field on both platforms (i.e., no new blocks are getting added). 🤔  I am using the demo apps. I also tried bringing in the latest from `master` with no difference.

**Comment by SergioEstevao** [comment]
@mchowning can you give another look on this one? I'm almost 100 sure it works fine in iOS.
And I'm baffled why it doesn't work in Android, if the paste event sends the HTML info it should work fine in Android too.

**Comment by SergioEstevao** [comment]
@mchowning are we still interested on getting this one sorted out?

**Comment by mchowning** [comment]
> @mchowning are we still interested on getting this one sorted out?

Thank you for the ping @SergioEstevao , and sorry for letting this fall (completely) off of my radar. I would like to get this in, and I just tested again. Here's a screen recording of what I did. Maybe I'm doing the wrong test steps?

multiline-paste mov

This change isn't causing any regressions that I can see, so I'm not opposed to merging this, but I am curious why I'm seeing different behavior.

**Comment by mchowning** [comment]
> Here's a screen recording of what I did. Maybe I'm doing the wrong test steps?

:wave: @ceyhun ! Since this project isn't @SergioEstevao 's focus anymore, do you have any thoughts here?

**Comment by ceyhun** [comment]
I'm getting the same result as you on iOS 14 now @mchowning after including the changes from master. Which iOS version did you try with? 
Also on web, pasting on the title results in it showing `First line<br>Second line<br>Third line` instead of creating new blocks. It's been a while since this PRs is open, so maybe some things have changed in web parts as well as mobile. We might need to rework this.

**Comment by mchowning** [comment]
> I'm getting the same result as you on iOS 14 now @mchowning after including the changes from master. Which iOS version did you try with?

I tested on iOS 14 as well (14.2 to be specific)

> on web, pasting on the title results in it showing `First line<br>Second line<br>Third line` instead of creating new blocks. It's been a while since this PRs is open, so maybe some things have changed in web parts as well as mobile. We might need to rework this.

It does look like we need to do some more work here. I hate to do it, but I feel like we should close this PR unless someone is planning on picking this up in the immediate future. 😞 We still have the [open issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1124) to track that this is unfixed.  Any opposition to closing this @SergioEstevao ?

**Pull request closed without merging**
