### PR TITLE
Inserter: use pointer cursor for tabs

### LINKED ISSUE #1643: Change mouse cursor from default to pointer
Right now the mouse cursor in the insert modal tab area is the default mouse cursor. This should be changed to the pointer cursor so that it's more obvious these are clickable areas.

screenshot

### PR DESCRIPTION
**Pull request by swissspidy**
A cursor pointer feels more natural to communicate something is clickable. But that needs some hover style as well. I just added some color for the latter:

screen shot 2017-07-02 at 19 54 11

Fixes #1643.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for the PR! 

The pointer style makes for a more _app-like_ experience. Which I have a slight preference for. 
Same, when combined with the gray text for the tabs. To me it makes it feel more "instant", where as the hand pointer makes it feel like "oh, damn, I have to wait when I click this one". 

But that's just my opinion, and though I'd _prefer_ not changing this, I'm not _against_ it :)

Though I do think we want to make sure the contrast of the blue link is sufficient against the gray background. Perhaps a compromise is having the pointer hand but not change the text color?

**Comment by swissspidy** [comment]
> The pointer style makes for a more _app-like_ experience.

Interesting, I never thought of it like that. I don't think many users feel this way though. Given that we use the pointer basically everywhere else, adding it here makes the UI more consistent.

> Though I do think we want to make sure the contrast of the blue link is sufficient against the gray background. Perhaps a compromise is having the pointer hand but not change the text color?

Right, the contrast is rather low. It's like that in other places as well, but that's something for another issue/PR. I'll revert for now.

**Comment by jasmussen** [comment]
👍 👍  ship it!

**Comment by jwold** [comment]
Great work! :)

**Pull request merged**
