### PR TITLE
Components: Enforce consistent usage of Button and ToolbarGroup components

### PR DESCRIPTION
**Pull request by gziolo**
## Description
It also extracts some changes from #17847, cc @diegohaz:

- converts all `button` tag elements to `Button` components for consistency
- replaces all usages of `Toolbar` components with `ToolbarGroup` in core blocks

In addition, this PR introduced ESLint change which discourages usage on `button` tag element in all production files. The only exception is `save` method implementation for the block definition.

## How has this been tested?
`npm run test-unit`
`npm run lint-js`

## Types of changes
Refactoring

### Before

Screen Shot 2019-12-02 at 10 47 03
Screen Shot 2019-11-29 at 12 57 32
Screen Shot 2019-11-29 at 12 55 20
Screen Shot 2019-11-29 at 12 59 56

### After

No visual changes 😃 

Screen Shot 2019-12-02 at 12 17 43
Screen Shot 2019-12-02 at 10 44 58
Screen Shot 2019-11-29 at 12 55 31
Screen Shot 2019-11-29 at 12 55 54

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by gziolo** [comment]
There are two issues with CSS specificity which I couldn't resolve myself:

Tabs in the sidebar still need a fix for the outline when focused:
Screen Shot 2019-11-29 at 12 54 46

Inserter item still needs a fix for the background color when focused and hovered:
Screen Shot 2019-11-29 at 12 54 59 

I would appreciate some help.

**Comment by jasmussen** [comment]
Pushed a fix for the two things you mentioned.

**Comment by gziolo** [comment]
I can confirm that the inserter item was fixed. The focused tab item which isn't the selected one still looks different than in `master`:

This branch:
Screen Shot 2019-12-02 at 10 46 27

master:
Screen Shot 2019-12-02 at 10 47 03

the outline should be dotted.

**Comment by jasmussen** [comment]
Fixed 👍 👍

**Comment by gziolo** [comment]
Thanks @jasmussen, everything looks good now. You are my CSS superhero 🥇

**Comment by gziolo** [comment]
After rebasing with the  `master I noticed one unexpected change in the UI:

Screen Shot 2019-12-02 at 16 00 59

**Comment by jasmussen** [comment]
I see this: 

html

The focus rectangle is missing from the toggled state, and it could use a border radius like the others. Let me know if you need help with that.

**Comment by gziolo** [comment]
This is what I see in this branch:
html-block

Should we update the hover state?

**Review by jasmussen — APPROVED** [review]
This is a solid step forward, and one that will enable further enhancements through code simplification. The HTML/Preview isn't perfect, but that "toolbar tab" pattern deserves some thought separately. As such and from a design POV, this looks good to me.

**Comment by youknowriad** [comment]
Nice work here

**Pull request merged**
