### PR TITLE
Enable registering hooks in `registerPlugin`

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Description
This is an experimental API exploring enable registering of action and filter hooks as part of the settings object passed to `registerPlugin`

* Enables plugins to easily add all of their hooks in one place.
* Uses the namespace from `registerPlugin` as the hook namespace.

## How has this been tested?
Added the following code to my theme based on the example from the [registerPlugin README](https://github.com/WordPress/gutenberg/blob/master/plugins/README.md):
```
function addBackgroundColorStyle( props ) {
	return Object.assign( props, { style: { backgroundColor: 'red' } } );
}
wp.plugins.registerPlugin( 'my-plugin',
	{
		render: renderFunction,
		hooks: {
			filters: [
				{
					name: 'blocks.getSaveContent.extraProps',
					callback: addBackgroundColorStyle
				}
			]
		}
	}
);
```
## Types of changes
* When handling `registerPlugin` look for a `hooks` settings object
* Inside `hooks` object, look for `actions` and `filters`arrays
* for each action/filter provided, perform addAction/addFilter with the passed name, callback and priority
* use a default priority of 10 if no priority is passed

## Todo
* Add some tests
* consider supporting an optional namespace for each hook in settings array that would be used instead of the plugin namespace.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
What would be the plan for all hooks that are registered by core? How would you deal with the fact that core registers multiple hooks for the same `name`? How would plugin developers unregister hooks registered by core and plugins? I think we need to come up with a coherent vision how to deal with all types of hooks first, before introducing the second API for the same thing. I'm afraid it would be very confusing to have 2 different ways to register and unregister hooks.

**Comment by adamsilverstein** [comment]
@gziolo great questions! I agree we need to settle on the API before adding a new one and did envision this as a thin wrapper around the existing api in any case. 

> What would be the plan for all hooks that are registered by core? 

The regular API would still be available, this would be specifically for plugins.

>How would you deal with the fact that core registers multiple hooks for the same name? 

For plugins wanting different namespaces per hook, we could enable that as part of the data structure.

>How would plugin developers unregister hooks registered by core and plugins?

separately, not in their initialization.

**Comment by aduth** [comment]
Is it likely this will be resumed, or can it be closed?

**Comment by adamsilverstein** [comment]
Closing for now.

**Pull request closed without merging**
