### PR TITLE
Avoid `tail`-ing the PHP 5.2/3 build logs

### PR DESCRIPTION
**Pull request by danielbachhuber**
Doing so produces tremendous log output, which makes Travis angry.

From #6676

### CODE REVIEW

**Comment by notnownikki** [comment]
So I agree that we shouldn't be tailing that any more, it was useful when we were first building them, but not so much now.

A couple of things though:

1) looking at https://travis-ci.org/WordPress/gutenberg/jobs/377252314 the job still terminated with the error that the log is too big, even when the build log isn't there. Perhaps there's something else going on here? Is the build log in .phpbrew counting towards this limit, even though it's not displayed? Seems very strange to me.

This is what I see at the end of the log...

```
Congratulations! Now you have PHP with 5.2.17 as php-5.2.17
* We found that you enabled 'mysql' variant, you might need to setup your
  'pdo_mysql.default_socket' or 'mysqli.default_socket' in your php.ini file.
* WARNING:
  You haven't setup your .bashrc file to load phpbrew shell script yet!
  Please run 'phpbrew init' to see the steps!
To use the newly built PHP, try the line(s) below:
    $ phpbrew use php-5.2.17
Or you can use switch command to switch your default php to php-5.2.17:
    $ phpbrew switch php-5.2.17
Enjoy!
===> phpbrew will now build 5.3.29
PHP 5.3 requires +intl, enabled by default.
===> Loading and resolving variants...
Downloading http://museum.php.net/php5/php-5.3.29.tar.bz2 via curl extension
[==========
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```

2) What happened to the cache? These builds used to be cached, and so the build wouldn't happen at all, but looking at this PR, it's missing the cache.

**Comment by danielbachhuber** [comment]
> looking at https://travis-ci.org/WordPress/gutenberg/jobs/377252314 the job still terminated with the error that the log is too big, even when the build log isn't there. Perhaps there's something else going on here? Is the build log in .phpbrew counting towards this limit, even though it's not displayed? Seems very strange to me.

Yes, I see this now. I'm not sure what the deal is.

**Comment by notnownikki** [comment]
Ah, I think I might have an idea...

https://api.travis-ci.org/v3/job/377252314/log.txt

In the raw log, every time the download progress bar updates, it's a new line in the log. But when you watch it live, it just looks like one line... Looks like we need to turn off the output while that's going on.

**Comment by danielbachhuber** [comment]
Landing this, to unblock other PRs

**Pull request merged**
