### PR TITLE
Fix wp-env WordPress and phpunit version mismatch when no core version is set

### PR DESCRIPTION
**Pull request by alecgeatches**
## What?

This adds a check in `wp-env` to query for the latest release version of WordPress before pulling `tests/phpunit` test files. This replaces the previous default of pulling the `trunk` version of phpunit files when no `core` version is specified in `.wp-env.json`.

## Why?

See investigation of the problem in https://github.com/Automattic/vip-decoupled-bundle/pull/57#issuecomment-1202067748, and related issue https://github.com/WordPress/gutenberg/pull/41780 where phpunit changes were made.

Currently, when no `core` config is specified in `.wp-env.json`, `wp-env` uses WordPress source from the `wordpress` docker image which is the latest WordPress release code. [`phpunit` code is pulled from `trunk`](https://github.com/WordPress/gutenberg/pull/41780/files#diff-15b519f59d0313c6bec164e39edb3c8387a6902765ac5a2ba6f182460ca440c5R126-R127). This can cause test failures when breaking changes are made in `trunk` that are not yet present in WordPress' latest release.

In this case in the current trunk version of WordPress, [`wp-db.php` has been renamed](https://github.com/WordPress/wordpress-develop/commit/fdb6e13fedc46fc19852479bad2488c9eab1ed9f) to `class-wpdb.php`. During installation of WordPress for testing, [phpunit includes `class-wpdb.php`](https://github.com/WordPress/wordpress-develop/blob/d91b7744f12cc00788114d78e8f9494861ba60e8/tests/phpunit/includes/install.php#L43). However, `class-wpdb.php` does not exist on the latest release version of WordPress used by `wp-env`. This causes [an ugly failure](https://github.com/Automattic/vip-decoupled-bundle/pull/57#issuecomment-1200742563) during bootstrapping which is tricky to track down.

This can be solved by specifying a `core` WordPress version, but for config files without a version there is always a possibility for a desync. The root problem is that WordPress' code is running from the `wordpress` docker container and the WordPress version being used isn't yet known during phpunit file downloading.

## How?

These changes use the [WordPress version check API](https://codex.wordpress.org/WordPress.org_API#Version_Check) before `tests/phpunit` cloning to determine the latest WordPress release version when no pinned version is specified. This makes a few assumptions:

1. The latest WordPress version returned by the API (e.g. `6.0.1`) corresponds with a tagged branch in https://github.com/WordPress/wordpress-develop.
2. The docker image for WordPress used internally by `wp-env` will match the latest WordPress version when no `core` version is specified.

It would be ideal if the code was able to determine the version of WordPress used by docker directly, but I'm not sure how this would be accomplished. The `tests/phpunit` directory download is setup during configuration before docker containers start running. Since we don't have direct access to the docker image, the code uses the assumptions above to pull the "correct" version of WordPress test files to match the release container. The code will also default to `trunk` when the API fails to resolve, so the failure case should be the same behavior as before.

## Testing Instructions

For testing, I'm using the [repository linked above](https://github.com/Automattic/vip-decoupled-bundle/pull/57#issuecomment-1202067748) where I discovered the issue. Here is a reproduction of the original problem using the current version of `wp-env`:

1. Install the current latest version of `wp-env`:

    ```bash
    npm install -g @wordpress/env
    ```

2. Clone [the `vip-decoupled-bundle` repo](https://github.com/Automattic/vip-decoupled-bundle) for testing

    ```bash
    git clone git@github.com:Automattic/vip-decoupled-bundle.git
    cd vip-decoupled-bundle/
    ```

3. Edit `.wp-env.json` and remove the `"core"` value to use the default WordPress version.

    ```diff
    {
    "plugins": [
        "."
    ],
    +    "config": {}
    -    "config": {},
    -    "core": "WordPress/WordPress#6.0.1"
    }
    ```

4. Run `wp-env` provisioning:

    ```bash
    wp-env start
    ```

5. Install and run tests:

    ```bash
    composer install
    composer run test
    ```

6. You should see [the error documented in this comment](https://github.com/Automattic/vip-decoupled-bundle/pull/57#issuecomment-1200742563) resulting from a `test/phpunit` and `WordPress` version mismatch.

Using the files from this branch, here's how to test the fix:

1. In a separate directory, clone the [`fix/wordpress-phpunit-version-mismatch` branch](https://github.com/alecgeatches/gutenberg/tree/fix/wordpress-phpunit-version-mismatch):

    ```bash
    git clone git@github.com:alecgeatches/gutenberg.git -b fix/wordpress-phpunit-version-mismatch --depth 1 gutenberg-alecg
    cd gutenberg-alecg/
    ```

2. Enter the `wp-env` package and install dependencies:

    ```bash
    cd packages/env/
    nvm use
    npm install
    ```

3. From the `vip-decoupled-bundle` directory, recreate the enviroment with branch version of `wp-env`:

    ```bash
    # In vip-decoupled-bundle/

    wp-env destroy
    node <path-to>/gutenberg-alecg/packages/env/bin/wp-env start
    ```

4. Run tests again:

    ```bash
    composer run test
    ```

The tests should now succeed, as the downloaded phpunit files now target WordPress 6.0.1.

### CODE REVIEW

**Comment by alecgeatches** [comment]
Tagging @ObliviousHarmony to check out these `phpunit` test file code changes for recent related work in https://github.com/WordPress/gutenberg/pull/41780. Thank you!

**Comment by ObliviousHarmony** [comment]
Thanks @alecgeatches,

@noahtallen actually already noticed this mistake and has opened #42826 to resolve it. We talked about how best to approach the problem and decided that if we're going to default to the `latest` version, we should assume that version throughout `wp-env`. I appreciate that we all came to the exact same solution for getting the latest version though!

**Comment by noahtallen** [comment]
Yeah, thanks for working on this! One of the differences with my approach in #42826 is that we now download a WordPress copy so that the phpunit code can find a version to match to (rather than assuming that what Docker provides will always match the latest stable version). This way, we can control the WordPress version rather than Docker providing whatever they want.

**Comment by alecgeatches** [comment]
@ObliviousHarmony @noahtallen Whoops, I missed https://github.com/WordPress/gutenberg/pull/42826 when looking for an already existing issue. I like the changes you've made over there better, and happy this is fixed. Thank you!

**Pull request closed without merging**
