### PR TITLE
translation should depend on number of items

### PR DESCRIPTION
**Pull request by iworks**
## What?

The translation string should be depend on number of items.

## How?

I added only a string for single item.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thanks for catching this, @iworks!

**Comment by Mamaduka** [comment]
@ellatrix, @vcanales, I'm flagging this for the next RC. This is a new string, and a fix for it can probably go even after "string freeze."

**Comment by ellatrix** [comment]
We're in [hard string freeze](https://make.wordpress.org/polyglots/handbook/glossary/#hard-freeze) though. I can ask about it.

**Comment by ellatrix** [comment]
Backported with #63038

**Pull request merged**
