### PR TITLE
Typo fix in a documentation MD file

### PR DESCRIPTION
**Pull request by elhardoum**
## Description

I've updated a simple typo replacing `REAMD.md` to `README.md`. The wp-org docs link to many 404 pages though, which I am not sure of the docs build process, but I believe wp-docs backend takes slugs and markdown sources from the [`docs/manifest.json`](/WordPress/gutenberg/blob/master/docs/manifest.json) file.

Here are the 404 links in this page:
https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/plugin-sidebar-0/plugin-sidebar-1-up-and-running/

- ```[registerPlugin](/packages/plugins/README.md)```
Correct link: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-plugins/

- ```[createElement](/packages/element/README.md)```
Correct link: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/packages-element/

- ```[packages](/docs/designers-developers/developers/packages.md)```
Correct link: https://wordpress.org/gutenberg/handbook/designers-developers/developers/packages/

This link on the other hand is working:
```
[PluginSidebar](/packages/edit-post/README.md#pluginsidebar)
```

## How has this been tested?

No.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Good catch, thank you for fixing it 👍

**Comment by gziolo** [comment]
@dd32 or @tellyworth, can you further investigate whether there were any changes in Gutenberg handbook which cause 404 errors?

**Comment by gziolo** [comment]
All links should work properly after this patch https://meta.trac.wordpress.org/changeset/8503 applied by @dd32. @elhardoum, can you confirm you no longer see 404 pages when navigating links?

**Comment by elhardoum** [comment]
@gziolo can confirm, no more 404 pages on that handbook page. Thanks for assisting on this!

**Pull request merged**
