### PR TITLE
Edit Site: Fix settings mutation in `ScreenBlock`

### PR DESCRIPTION
**Pull request by tyxla**
## What?
This PR fixes a mutation that we're performing in `ScreenBlock` and updates to use a new object instead.

## Why?
Mutating objects could lead to subtle bugs.
In this particular case, I'm fixing it to resolve an ESLint error that was raised by the React Compiler ESLint plugin in https://github.com/WordPress/gutenberg/pull/61788

## How?
Using a new object instead of mutating the existing one. 

Since this already memoized object is used in plenty of places, I'm introducing some memoization to preserve the original behavior and have as little performance impact as possible. We're using boolean flags to ensure the change happens only if necessary. 

The fix isn't ideal. Ideally, this should be part of the `useSettingsForBlockElement()` hook; however, I'm concerned that this hook is used in a few other places, but the workarounds are only in one of them. That's why I chose to do it inline and preserve the pre-existing behavior. I'm planning to monitor performance metrics after shipping. 

## Testing Instructions
* Verify testing instructions of #53900 still work.
* Verify testing instructions of #56897 still work. 
* Smoke test global styles of a few more blocks.
* Verify all checks pass

### Testing Instructions for Keyboard
None

## Screenshots or screencast 
None

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thank you, @tyxla!

**Comment by tyxla** [comment]
Failing e2e tests seem related. I'll be taking a look (likely tomorrow).

**Comment by tyxla** [comment]
> Failing e2e tests seem related. I'll be taking a look (likely tomorrow).

Actually, fixed, it was a silly bug. @Mamaduka could you take another look when you get a chance?

**Review by Mamaduka — APPROVED** [review]
🚢

**Pull request merged**
