### PR TITLE
Serializer: Remove HTML beautification, preserve whitespace

### LINKED ISSUE #4456: New lines in shortcode content are ignored
## Issue Overview

The new editor does not respect new lines in shortcode content. It's impossible to use the new editor to edit posts which depend on this. For me this is a blocker; it breaks my sites.

I have a number of shortcodes where each line in the content is expected to be processed separately. With Gutenberg v2.0.0 it's impossible to safely edit a post containing these shortcodes without the content being broken.  Take for example the [bw_csv] shortcode which converts CSV content into a table.

```
[bw_csv]One,Two,Three
A,B,C
D,E,F
[/bw_csv]
```
During shortcode expansion the first line becomes table the table heading.
Subsequent lines are table rows. So the expected output is like this.

One | Two | Three
--- | ---- | ----
A | B | C
D | E | F

When the new lines are removed by the editor the shortcode does not expand correctly. Everything is treated as the table heading. 

The basic problem can be demonstrated even without the shortcode being active.
In the current editor you can quite happily switch between Visual and Text and the site is not broken.  
Once the content is converted the new lines in the original source are lost. 

## Steps to Reproduce (for bugs)

1. Create a new post using Posts > All Posts > Add New > Classic Editor
2. Enter content as in the shortcode above
3. View the post.
4. The content should appear as typed.

Repeat the above steps for another new post
5. Now Edit the post using Gutenberg
6. The new line characters do not survive the conversion.
7. Any attempt to recreate the original content using Gutenberg will fail.
8. Switching to the Code editor to remove unwanted paragraphs ( #3900 ) doesn't work as that ignores new lines as well. They disappear as soon as you click on Update.

I've also tried using different block types: Shortcode, Custom HTML. 

## Expected Behavior

- The editor should not be removing new lines.
- It should not add anything either.
- It works in WordPress 4.9.1
- In my opinion the Shortcode block should support content created AS IS. It should respect any new line characters in the content. 

## Current Behavior
I've been unable to find any existing block that respects my new lines. 
- Custom HTML strips the new lines on save.
- The shortcode block also strips new lines.

## Possible Solution
Shortcode block should respect the content as typed.

## Screenshots / Video

image
image
image

## Related Issues and/or PRs

#3900 
#1709 - see https://github.com/WordPress/gutenberg/issues/1709#issuecomment-321574711

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by aduth**
Supersedes #6716 
Fixes #4456

This pull request seeks to remove in-block HTML beautification. Per intent with #633, there are still newlines between blocks. Within a block, however, the default serialization will not inject any of its own automated whitespace or tabbing. Existing intentional whitespace will be preserved (e.g. code blocks, shortcode blocks).

This has a few benefits:

- Performance
   - `js-beautify` accounts for 48kb (18.1kb gzipped), now removed
   - No longer need to parse / rewrite HTML when saving a post during serialization stage
- Accuracy
   - `children` parse would include (often wrongly) text nodes not always intended but automatically injected by beautifier
   - No more collapsing whitespace in shortcode blocks
      - Verified in updated `adding-blocks` E2E test which would have previously failed in master (see bd78d55)
   - Surfaces potential issues with raw handler not stripping newlines where stripping may be intended (see new `test/integration/fixtures` output files, e.g. `apple-out.html` table block)

**Implementation notes:**

The vast majority of affected file changes are fixture updates. The only meaningful changes are those made within `blocks/api/serializer.js`, though fixtures verification would be good as well.

**Testing instructions:**

Verify there are no issues with serializing and restoring block contents.

Examples:

 - Save a Demo post and reload it, ensure no validation errors
 - Save a post including a Columns block and reload it, ensure content preserved and no validation errors

### CODE REVIEW

**Review by danielbachhuber — COMMENTED** [review]
Can you include a test specifically for #4456? My understanding is that we'd need to change the Shortcode Block `<input>` to `<textarea>` to properly display multi-line shortcodes.

Also, it'd be great if you merged in #7846 to incorporate those tests.

**Comment by aduth** [comment]
Rebased against master.

@danielbachhuber The tests added in 6ae7a11 specifically target multi-line shortcode (the shortcode block is already a `textarea` field). Is this what you had in mind; or something different?

**Comment by danielbachhuber** [comment]
> (the shortcode block is already a textarea field)

Ok, great.

> Is this what you had in mind; or something different?

Could you add one more test for `segmentHTMLToShortcodeBlock`?

**Comment by aduth** [comment]
I don't think that falls within the scope of what this pull request is targeting. Raw handling is a different feature than the serialization beautifier.

**Comment by danielbachhuber** [comment]
> I don't think that falls within the scope of what this pull request is targeting. Raw handling is a different feature than the serialization beautifier.

Ok. I still think it would be a helpful test to have to truly fix #4456. Would you like me to add the test when I have a moment?

**Comment by aduth** [comment]
That's fine. I guess I'm unclear about what's specifically not covered already to address #4456 . The classic editor content issue is already fixed (on master), and this one resolves issues with shortcode block (with tests). There's nothing in the original report that touches `segmentHTMLToShortcodeBlock` .

**Comment by danielbachhuber** [comment]
@aduth Ok. I'll defer to your better judgement for this PR, and follow up with a second PR for anything I think of.

**Review by danielbachhuber — APPROVED** [review]

**Comment by mtias** [comment]
And such was the way beauty left our world...

**Pull request merged**
