### PR TITLE
chore($deps): update react-resizable-box -> re-resizable

### PR DESCRIPTION
**Pull request by andreiglingeanu**
## Description

This pull request will replace the outdated [`react-resizable-box`](https://www.npmjs.com/package/react-resizable-box) with the new and shiny [`re-resizable`](https://github.com/bokuweb/re-resizable) and update the `image-block` to work accordingly.

## How Has This Been Tested?

There were no automated tests for the image block. This was tested manually by dragging the image that is currently into the image block.

## Screenshots (jpeg or gifs if applicable):

screen recording 2017-10-24 at 07 29 pm

## Types of changes

The change is a dependency update with slight changes to adapt to new `re-resizable` interface. Everything besides that stays the same.

Also, this pull request bumps the webpack to `3.8.1` version, which is totally not a breaking change.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.
- [x] Maybe refactor the `width`/`height` calculation based on aspect ratio to reflect the new component. Not sure if that is needed will definitely love to receive some feedback on that one.

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
I think there may have been an issue with updating the `package-lock.json` here. There are many more removals than I would have expected. Running `npm install` locally reveals changes to re-add them (including Webpack).

**Comment by andreiglingeanu** [comment]
Indeed. Did a guard `npm install`. Now the diffs looks a bit more realistically.

**Comment by andreiglingeanu** [comment]
Is there anything I could do in order to get that merged?

**Review by aduth — CHANGES_REQUESTED** [review]
I'm observing that when resizing an image using the handles, the size resets to its original when releasing the click. I'm thinking this could be related to the changes in math to apply width change by a delta? Specifically seeing this for a newly inserted image, which I believe might not have the width/height attributes assigned to perform the delta on.

I'm also still seeing changes incurred when running `npm install`. Might be OS or version specific? Specifically it's a minor rearrangement of the `string_decoder` dependency within `package-lock.json`.

**Comment by andreiglingeanu** [comment]
Hey @aduth, I just updated the event at which we do `setAttributes`. Now we do that when the drag action gets finished. No more resets to the original value. Also, now I use the `currentWidth/currentHeight` computed values, they seem to be fetching dimension from the DOM when the `width/height` is not present in the state yet.

I can probably see why do not get the `width` and `height` from `wp.media.*` info, we do need to account here for the container width and image should never exceed it.

https://github.com/WordPress/gutenberg/blob/53c990aaf6691fffd51ce48542a03b87b182950f/blocks/library/image/block.js#L54-L56

<hr>

For the `package-lock.json` thing, I do not get any changes in my `package-lock.json` after I run `npm install`. It might be a minor NPM versions clash between ourselves.

**Comment by aduth** [comment]
>we do need to account here for the container width and image should never exceed it.

If we're not already doing this, do you mind filing an issue and/or pull request for this?

**Review by aduth — APPROVED** [review]

**Review by aduth — APPROVED** [review]
Works nicely now 👍  I pushed updates from what I'm seeing on `package-lock.json` with a fresh install. Might be different version, but I am running the latest. Hopefully avoids unintended changes in master.

**Comment by andreiglingeanu** [comment]
> If we're not already doing this, do you mind filing an issue and/or pull request for this?

Sure. I do have a couple of ideas on how to improve that. Will definitely get back in an issue.

Thanks for fixing the `package-lock.json` thing for me and getting that merged.

**Pull request merged**
