### PR TITLE
Evaluate WP commands with shell-like API in e2e tests

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Based on #33414.

_WIP_

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think we can use REST API to activate/deactivate plugins - https://make.wordpress.org/core/2020/07/16/new-and-modified-rest-api-endpoints-in-wordpress-5-5/

**Comment by adamziel** [comment]
Do we have more places where eval could be useful? This PR addresses plugins activation/deactivation which could be a regular api endpoint (or two) so `eval` just for that seems excessive 😅 .

**Comment by Mamaduka** [comment]
I agree with @adamziel. It would be nice to avoid `eval` if we can.

Checked themes API, and it doesn't handle activation/deactivation, but we can extend it on our end.

**Comment by kevin940726** [comment]
> I think we can use REST API to activate/deactivate plugins - [make.wordpress.org/core/2020/07/16/new-and-modified-rest-api-endpoints-in-wordpress-5-5](https://make.wordpress.org/core/2020/07/16/new-and-modified-rest-api-endpoints-in-wordpress-5-5/)

Oh somehow I missed it! Good to know that we actually support it.

Yeah I agree `eval` is not ideal, and I personally would prefer REST API over using `eval`. I guess we can wait and see if there're other use cases that's not supported via REST API.

**Comment by kevin940726** [comment]
Closing in favor of #33414.

**Pull request closed without merging**
