### PR TITLE
[RNMobile] RichText should delete its Enter in Heading block

### PR DESCRIPTION
**Pull request by hypest**
## Description
Fix for https://github.com/wordpress-mobile/gutenberg-mobile/issues/4322

### Related PRs
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/4365

### Test 1
1. Using the demo app on Android 12
2. Insert a heading block and input some words
3. Place the cursor in the middle of a word and hit the Enter key on the virtual keyboard
4. Notice the block split into 2 heading blocks and the caret being at the beginning of the second block
5. Hit the Enter key on the virtual keyboard again
6. Notice that a new paragraph block has been added between the two heading blocks, **and that the second heading block doesn't have an empty line in its start**

### Test 2

Follow the same steps as in Test 1, but on an Android 11 device/emulator. This is a test to confirm that the behavior is not broken on current Android version.

## Types of changes
1. Have the heading block pass the `deleteEnter` prop to its RichText when on native mobile. I opted for a platform conditional (versus for example forking the edit.js into edit.native.js) to avoid forking the block for this kind of small tweak. Also, opted for [not defaulting the RichText component](https://github.com/WordPress/gutenberg/blob/1b15cf17199126b73aeb3644be7527e7806e22fc/packages/block-editor/src/components/rich-text/index.native.js#L97) to `deleteEnter=true` since that would increase the impact of the change to too many other components/blocks. The fix in this PR is targeting the heading block only. If the same issue exists in other blocks, we can reconsider where to have the fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
👋 @ajitbohra! GitHub added you automatically as a reviewer. I believe the PR here should only really affect the native mobile side of things but yeah, would appreciate a look/review from you if you have the time, thanks!

👋 @SiobhyB, added you as a reviewer to make sure the native mobile mobile side of this PR is OK, thanks!

**Review by SiobhyB — APPROVED** [review]
I confirmed that the splitting the heading block works as expected (with no extra lines) on both Android 11 and 12 with this PR applied. 🚀 

It was also interesting to learn a bit about the `deleteEnter` prop, thanks for adding me as a reviewer and for the fix!

**Comment by hypest** [comment]
👋 @ajitbohra, sorry for re-pinging. Let me know if you're planning to take a peek at the changes in this PR, since you are marked as a code owner, or you're happy with the reviewing that happened so far. I can then go ahead and update from trunk to resolve the `packages/react-native-editor/CHANGELOG.md` conflict and merge. Thanks!

**Review by ajitbohra — APPROVED** [review]
Code wise LGTM 👍

Makes sense using platform check instead of forking.

**Comment by hypest** [comment]
Updated from trunk (and develop on the gutenberg-mobile side) and tested this still working OK on physical device and emulator, and as CIs are now green, I'm going ahead with the merge.

**Pull request merged**
