### PR TITLE
Debug performance tests issues

### PR DESCRIPTION
**Pull request by WunderBart**
## What?

Let's keep this PR for debugging failing performance tests.

### CODE REVIEW

**Comment by WunderBart** [comment]
Currently, on `trunk`, it seems like the Site Editor doesn't load the test post at all:

Typing 2023-02-17T14-10-11

@youknowriad @kevin940726, any idea what might be causing it?

**Comment by t-hamano** [comment]
If you don't mind, could you please test the following code once? Perhaps it is taking a long time to load the posted content.

```diff
diff --git a/packages/e2e-tests/specs/performance/site-editor.test.js b/packages/e2e-tests/specs/performance/site-editor.test.js
index a14b40d72b..5be2fbdfc4 100644
--- a/packages/e2e-tests/specs/performance/site-editor.test.js
+++ b/packages/e2e-tests/specs/performance/site-editor.test.js
@@ -140,11 +140,12 @@ describe( 'Site Editor Performance', () => {
                await page.waitForSelector( '.edit-site-visual-editor', {
                        timeout: 120000,
                } );
-               await canvas().waitForSelector( '.wp-block', { timeout: 120000 } );
+               await canvas().waitForSelector( '.wp-block', { timeout: 500000 } );
 
                // Measuring typing performance inside the post content.
                await canvas().waitForSelector(
-                       '[data-type="core/post-content"] [data-type="core/paragraph"]'
+                       '[data-type="core/post-content"] [data-type="core/paragraph"]',
+                       { timeout: 500000 }
                );
                await enterEditMode();
                await canvas().click(
```

**Comment by WunderBart** [comment]
> If you don't mind, could you please test the following code once? Perhaps it is taking a long time to load the posted content.

👋 Hi @t-hamano! Just now, I've pushed a commit that should verify if the test post size is the issue (https://github.com/WordPress/gutenberg/pull/48208/commits/1e1ecde54200380bb079b3e1581233c69a6a5fc2). Let's see if that works and then eventually try another approach 🤞

**Comment by WunderBart** [comment]
Looks like [it's not the post size](https://github.com/WordPress/gutenberg/actions/runs/4204575321/jobs/7295434371) - it still loads with a WSOD canvas. The weirdest part, though, is that I cannot seem to reproduce locally no matter what I do. I've followed the exact same steps the CI does (I think), and I'm still getting pass on each run. I've also tried running the `./bin/plugin/cli.js perf` script but it fails when trying to start `wp-env` with `Failed to fire hook: while creating logrus local file hook: user: Current requires cgo or $USER set in environment`. 

Going to try higher timeout values, [as suggested](https://github.com/WordPress/gutenberg/pull/48208#issuecomment-1434711873) by @t-hamano above. It would also be nice to have the console logs - I'll see if I can get them.

_edit:_ Just noticed that these timeouts are actually huge and I don't think they even last to the given value. The global timeout will most likely end the job before reaching `500000` ms (~8 minutes). I don't think it makes sense to test such values - what could take over 8 minutes to load? 😅 What do you think @t-hamano?

_edit again:_
OK let's try it (with a bit smaller value), it won't harm anyone! 😄

**Comment by t-hamano** [comment]
Yes, the huge timeouts are just to find the cause 😄

```
TimeoutError: waiting for selector `[data-type="core/post-content"] [data-type="core/paragraph"]` failed: timeout 30000ms exceeded
```

This test failure logs indicate that this line has passed:

https://github.com/WordPress/gutenberg/blob/0b5ca2239f012e676d70d5011f9f96c503cc8220/packages/e2e-tests/specs/performance/site-editor.test.js#L143

Therefore, I suspect that it is not a complete WSOD canvas and that it is taking time to load the submitted content.

**Comment by WunderBart** [comment]
Still the same thing. I'm heading out for the week, @t-hamano, so feel free to commandeer this branch. Good luck! 🙌 

Also, cc @youknowriad @kevin940726 as I couldn't get to the bottom of the issue. Hopefully will be more lucky on Monday.

**Comment by t-hamano** [comment]
Thanks for addressing this issue! I also put a [call out](https://wordpress.slack.com/archives/C02QB2JS7/p1676646200644429) to the `#core-editor` channel on Slack.

**Comment by kevin940726** [comment]
Based on the canvas HTML, it seems like the problem might be within the Query block?

image

**Comment by t-hamano** [comment]
> Based on the canvas HTML, it seems like the problem might be within the Query block?

This is very strange. The test attempts to reference a template with a post type of **page**. If the emptytheme is used in the test, then the **Singluar** template should be referenced. And the text "No Results Found." is only present in `core/comment-template`, `core/post-template` and `core-template-part`. But this template does not have those blocks.

singular

Are we not accessing the correct template?

**Comment by t-hamano** [comment]
I have committed to find out what page the test indicates (i.e., the text of the `title` tag) when it fails. The text of the title tag should be expected to be:

```
Singular ' Template ' Editor ' {Site Title} - WordPress
```

**Comment by t-hamano** [comment]
Okay, according to [artifacts](https://github.com/WordPress/gutenberg/actions/runs/4215667135), it looks like Puppeteer is looking at the Index template instead of the expected template 🤔

	<title>Index ‹ Template ‹ Editor ‹ d-7-e-5717-b-8-e-8-a-2389-e-5-b-4-e-61-a-77-aeee-0-da-11-f-447-b — WordPress</title>

**Comment by kevin940726** [comment]
@t-hamano Yeah, you're right. It's not the expected outcome. At least we now know what went wrong 😅 . My guess would be that somehow `createPost` and `saveDraft` don't work as expected, but I'm not familiar with that area to have more guesses. 🤔 

The image in https://github.com/WordPress/gutenberg/pull/48208#issuecomment-1434706279 by @WunderBart also indicates that it's not loading the page template, as the sidebar will look different.

**Comment by kevin940726** [comment]
https://github.com/WordPress/gutenberg/pull/48063 is the first PR I've seen to have this error. Before that, the error was different: `Couldn't find "Paragraph" in the Blocks category.`. There might be multiple issues 🤔 .

**Comment by t-hamano** [comment]
If you access a non-existent post in the site editor, the sidebar navigation itself does not appear. However, artifacts shows the Index template. So the editor canvas might not correctly parse the URL path?

capture

**Comment by kevin940726** [comment]
Okay, [9bc7099](https://github.com/WordPress/gutenberg/pull/48208/commits/9bc7099358989729d80340a7b1ee3f48ae2f59d1) seems to fix the first issue. The page now loads and the selector successfully selects the paragraph block. As a matter of fact, the HEAD commit for the performance test was [successfully completed](https://github.com/WordPress/gutenberg/actions/runs/4216736492/jobs/7319997844). However, the trunk test now fails with a familiar error (`Couldn't find "Paragraph" in the Blocks category.`)

Typing 2023-02-19T14-54-24

Looking at the screenshot, it seems like the page is focusing on a list item block. It's not allowed to insert a Paragraph block there hence the error. I have two guesses:

1. Layout shifting after the page is loaded.
2. Animation caused by entering the edit mode.

Let's try them one-by-one.

**Comment by t-hamano** [comment]
Performance test passed 🤣 Thank you so much!

**Comment by kevin940726** [comment]
So [d96dbd0](https://github.com/WordPress/gutenberg/pull/48208/commits/d96dbd0718d53101544c518479f67583d6a26ed0) works, but we still don't know the exact reason why it failed 😅 . Layout shifting seems like the most possible answer. (FWIW, if we ever migrate the performance test to Playwright then this might become trivial.)

This branch is obviously not in a ready-to-merge state. I'll defer the optimal solution for others more familiar with the code (@WunderBart, @youknowriad, @dmsnell 🙇) .

**Comment by ellatrix** [comment]
Any way we can isolate the problem and fix it in a separate PR? A lot of PRs are blocked by the failing performance test.

**Comment by youknowriad** [comment]
yeah I don't understand why the particular change solves it but. happy to see this small change in its own PR to unblock PRs for folks

**Comment by WunderBart** [comment]
Nice sleuthing @t-hamano @kevin940726, thank you! 🚀 I've isolated the fix to https://github.com/WordPress/gutenberg/pull/48240. I think we should also merge the [artifacts upload](https://github.com/WordPress/gutenberg/pull/48208/commits/2e0074ba8ad2705a17da38729471e7c40a90f9fc) for the perf tests. I'll move it to another PR.

**Comment by WunderBart** [comment]
Isolated artifacts upload to https://github.com/WordPress/gutenberg/pull/48243

**Comment by t-hamano** [comment]
The performance test failure issue has been fixed in #48240. The artifacts upload issue has been submitted as #48243.

So let's close this PR. Thank you for addressing this issue, @WunderBart!

**Pull request closed without merging**
