### PR TITLE
Fix styling of classic block's block controls

### LINKED ISSUE #12104: Classic editor 'more options' disappears at 220% zoom
Not sure how much of a problem this is, but if you zoom in the classic editor the 'more options' button disappears at a certain point. Here is 200%:

edit_post_ _wordpress_latest_ _wordpress

And it disappears at 220%:

edit_post_ _wordpress_latest_ _wordpress

The other buttons all wrap round properly as you zoom further

The more button also seems to be 1 pixel too far down vertically, and overlaps the border when you highlight it.

**To Reproduce**
1. Add a classic editor block
2. Zoom the browser window to 220%
3. Note the more options ellipsis menu disappears

**Desktop (please complete the following information):**
Mac+Chrome

### LINKED ISSUE #16137: Classic Block has broken block switcher
**Describe the bug**
The Classic Block seems to have picked up a block switcher, perhaps after the group block was merged?

**To reproduce**
1. Fire up the latest version of master (5.9.0-rc.1)
2. Add a Classic Block to your editor
3. See the block switcher in the top right corner when the block is selected

**Expected behavior**
There is no block switcher, it should look like this:

image

**Screenshots**

classic-block

### LINKED ISSUE #16525: Classic block: Block's toolbar items are extending beyond the toolbar awkwardly
**Describe the bug**
The Classic block's toolbar is extending beyond the block awkwardly.

**To reproduce**
1. Open a post that was created in the Classic Editor.
2. Observe the Classic block.
3. Click on the Classic block and observe the toolbar.
4. See toolbar options extend beyond toolbar.

**Expected behavior**
The toolbar options should not extend beyond the toolbar.

**Screenshots**

classic-block

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox 67.0.4
 - Gutenberg 6.1

### PR DESCRIPTION
**Pull request by talldan**
Fixes #16525 
Fixes #16137
Fixes #12104

## Description
This PR fixes a few issues with the classic block's styling that seem to have recently broken.

#### Before
(the introduction of the group transform for the classic block has made its block controls hang over the edge)
Screen Shot 2019-09-04 at 4 24 41 pm

#### After
(the block controls are now in line with other blocks)
Screen Shot 2019-09-05 at 1 02 55 pm

#### Before
Screen Shot 2019-09-05 at 1 02 08 pm

#### After
Screen Shot 2019-09-05 at 1 07 33 pm

#### Before
Screen Shot 2019-09-05 at 1 01 57 pm

#### After
Screen Shot 2019-09-05 at 1 10 14 pm

#### Before
Screen Shot 2019-09-05 at 1 12 56 pm

#### After
Screen Shot 2019-09-05 at 1 13 16 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
I was mostly interested in fixing this bug very quickly, but I suppose it would also be possible to bring the classic block's toolbar more inline with other blocks:

Screen Shot 2019-09-04 at 4 57 03 pm

**Comment by kjellr** [comment]
Thanks, @talldan. This must've popped up when the group block landed? I don't recall the classic block having a block switcher control in the first place. I think both of those controls were intended to be tucked inside of the block like so: 

Screen Shot 2019-09-04 at 8 19 14 AM

... but that creates a weird line break in the first row of controls. In any case, I think your proposed toolbar makes a lot of sense here. I think that's the better route.

**Comment by mapk** [comment]
Thanks for picking this one up, @talldan. I like the proposed solution of aligning the elements to match the other block toolbars. That one's a win! https://github.com/WordPress/gutenberg/pull/17323#issuecomment-527810711

**Comment by ZebulanStanphill** [comment]
I was confused by the Classic block's block switcher being on the right rather than the left, so I also like the proposal to move it and the ellipsis menu to the same spot as every other block.

**Comment by talldan** [comment]
Thanks for the feedback. I've applied that recommendation and fixed a bunch of other issues at the same time. This should be good for a review.

**Comment by kjellr** [comment]
Thanks Dan. I pushed up a couple tiny additional fixes while we're in here: 

**1. Corrected the initial toolbar label height:** 

_Before_
Screen Shot 2019-09-05 at 9 38 08 AM

_After_
Screen Shot 2019-09-05 at 9 37 48 AM

**2. Corrected the TinyMCE toolbar width on mobile:**

_Before_

Screen Shot 2019-09-05 at 9 48 29 AM

_After_

Screen Shot 2019-09-05 at 9 44 41 AM

**3. I also removed the drop shadow underneath the toolbar.** 

This is admittedly more of a personal preference, but we don't really use shadows like that anywhere, so I think this seems more natural. 

_Before_

Screen Shot 2019-09-05 at 9 51 28 AM

_After_

Screen Shot 2019-09-05 at 9 51 46 AM

**Review by kjellr — APPROVED** [review]
This is looking good, and should be ready to land. 👍

**Comment by talldan** [comment]
Thanks folks!

**Pull request merged**
