### PR TITLE
[RNMobile] Fix for extra BR tag on Title field on Android

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR is a fix for https://github.com/wordpress-mobile/gutenberg-mobile/issues/1078  _(Pressing enter on the title creates a BR tag)_
It does set the proper props to instruct AztecWrapper on Android to remove the new line char ( converted to BR on HTML ) when Enter.key is pressed on the keyboard.

GB-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1095

### CODE REVIEW

**Comment by daniloercoli** [comment]
@hypest Not sure if it's worth to default the `deleteEnter` prop in `RichText` for mobile to `true`.
`deleteEnter={ this.props.deleteEnter !== undefined ? this.props.deleteEnter : true }`
(Or change it to true in the native wrapper in Android)

This way there is no need to other fields to declare it to true every time.

**Review by SergioEstevao — APPROVED** [review]
Tested it on the demo app and it's looking good.

**Review by mkevins — APPROVED** [review]
Tested on WP-Android (aabfb2baf), and this works as described.

**Comment by hypest** [comment]
> Not sure if it's worth to default the deleteEnter prop in RichText for mobile to true.
> deleteEnter={ this.props.deleteEnter !== undefined ? this.props.deleteEnter : true }
> (Or change it to true in the native wrapper in Android)
>
> This way there is no need to other fields to declare it to true every time.

The default is `false` pretty much. For example, the list block let's Aztec handle the Enter within its internal handling of the lists. Other blocks might need similar approach (to let Aztec handle it), that's why I left it default to false. We might want to revise in the future, when we will have a better picture of what do the blocks need from Aztec most of the times, and change the default. Is it OK with you to leave it to `false` for the time being @daniloercoli ?

**Comment by daniloercoli** [comment]
Sure, i'm ok with that @hypest. Let's merge this 🚀

**Pull request merged**
