### PR TITLE
Add missing field _invalid in menu item REST API

### LINKED ISSUE #34628: schema for "/__experimental/menu-items" errors
I'm not sure any if these cases are intentional but,

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1067-L1070

this endpoint return array of numbers for `menus` not a number

https://github.com/WordPress/gutenberg/blob/dd5fd6b2466d33177d46dcdc0733abd0217e044a/lib/class-wp-rest-menu-items-controller.php#L1046-L1051

also `_invalid` is missing not null or any falsy value

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Description
Add missing field _invalid in menu item REST API. Originally flagged in #34628

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

Fixes #34628

### CODE REVIEW

**Review by noisysocks — COMMENTED** [review]
We should add the extra attribute to `get_item_schema` and modify any unit tests that test `get_item`. Also, does it need to be prefixed with `_`? I didn't think that was a convention that the REST API ever used.

**Comment by TimothyBJacobs** [comment]
I agree with @noisysocks.

**Comment by spacedmonkey** [comment]
>We should add the extra attribute to get_item_schema 

To be clear, it was already there, we just didn't return it. 

> modify any unit tests that test get_item

Added to tests. 

>Also, does it need to be prefixed with _?

Removed

**Review by noisysocks — APPROVED** [review]
Nice one 👍

**Review by TimothyBJacobs — APPROVED** [review]

**Pull request merged**
