### PR TITLE
Fix nested template parts flow in Editor

### LINKED ISSUE #54279: Edits to templates and template parts inside subfolders are not saved correctly
### Description

Block themes can place template parts in subfolders inside the `parts` folder. (See previous issue: https://github.com/WordPress/gutenberg/issues/20375)

Changes made to these template parts are not saved as a user customization to that part.
Instead, it looks like a new template part is created, and there is something wrong with the saved state: the changes to the customized part show as not being saved.

### Step-by-step reproduction instructions

Activate Twenty Twenty-Three.

Inside the parts folder, create a new folder called "headers".
Move header.html inside this folder.

In home.html, change
`<!-- wp:template-part {"slug":"header","tagName":"header"} /-->` to 
`<!-- wp:template-part {"slug":"headers/header","tagName":"header"} /-->`

Confirm that the header template part loads correctly.
In the editor, select the header template part and make some changes. Either directly on the home template screen or in isolation -it doesn't matter.
Save.
Notice that the save seems complete, and the "Site updated" notification appears.
But the Save button is still in the state that shows that there are unsaved changes, and the site preview button next to it is disabled.

Click on the Icon in the top left corner of the Site Editor to open the navigation sidebar (the dark grey sidebar on the left side)
Confirm that the save button at the bottom of the sidebar is showing that there are unsaved changes.
Click on this save button.
Notice that the notification "Site update" shows up but the state doesn't change; it still shows that there are unsaved changes.

Using the sidebar, please navigate to the "All template parts" screen to view the list of template parts.
Notice that the headers/header template part added by the theme is **not** labeled as being customized.
Instead, there are multiple user-created template parts with the name `headers//header` in the list.

List of template parts that show the incorrect template parts 

### Screenshots, screen recording, code snippet

(I only have mobile internet at the moment, I will upload a video later.)

### Environment info

Tested on macOS, nginx, PHP 8.0.22 using:
WordPress 6.3.1 with and without Gutenberg 16.6.0.
WordPress 6.2.2

I did not test on versions older than 6.2.2.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

WIP. 

Closes https://github.com/WordPress/gutenberg/issues/54279

### CODE REVIEW

**Comment by getdave** [comment]
Screen Shot 2023-09-28 at 09 25 33

It looks like when we fetch all the template parts we end up with duplicate records for what _should_ be the same template part. This consists of:

1. `header/header-primary` - the template part from the filesystem.
2. `header-header-primary` - the template part from the database (basically `#1` but with customisations made in the editor).

AFAIK there should only be a single record. Will now dive deeper into how these records are retrieved and processed on REST.

**Comment by getdave** [comment]
## Notes

- This document is useful - https://github.com/WordPress/gutenberg/blob/232e37fac89883a2ef0056d150e5f981b1d0a664/docs/explanations/architecture/full-site-editing-templates.md
- Template Parts are handled by the [`WP_REST_Templates_Controller` REST class](https://github.com/WordPress/wordpress-develop/blob/ea5856efe87f9fdc1940fedb3606e81ee04b4965/src/wp-includes/post.php#L440). 
- The [following line](https://github.com/WordPress/wordpress-develop/blob/ea5856efe87f9fdc1940fedb3606e81ee04b4965/src/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php#L205-L207) is illuminating:
> This method doubles the last slash if it's not already doubled. It relies
> * on the template ID format {theme_name}//{template_slug} and the fact that
> * slugs cannot contain slashes.

- Confirmed that REST API is returned x2 TP records representing the same template part - one with source `theme` and one with source `custom`. This is wrong.
- function `_build_block_template_result_from_post` does not find a matching file system template for the Template Part CPT in the database. As a result the template object return is marked as `$template->has_theme_file = false` when it should be true.
- Possible culprit function `_get_block_template_file` calculates the _Post_ Template Part matching filesystem path as `wp-content/themes/emptytheme/parts/headers-header-primary.html` when it needs to be `/var/www/html/wp-content/themes/emptytheme/parts/headers/header-primary.html` (notice slash instead of hyphen). Given that all the template parts have their slugs saved with single hyphens as delineators, there is no way to reverse engineer the file path from the slug.

**Comment by bangank36** [comment]
From https://github.com/WordPress/gutenberg/issues/54279#issuecomment-1738841238
> Therefore I propose we consider utilising post meta to store the original template part filesystem path

I think this is the right way to improve the template synchronization process
Let's call the meta `original_template_path` for now...
- Update [_build_block_template_result_from_post](https://github.com/WordPress/wordpress-develop/blob/e3a612a97c4c45acd7613779a46d86860e76cc65/src/wp-includes/block-template-utils.php#L727C10-L727C48) to pass the `original_template_path` instead of the `post_name` into [_get_block_template_file](https://github.com/WordPress/wordpress-develop/blob/e3a612a97c4c45acd7613779a46d86860e76cc65/src/wp-includes/block-template-utils.php#L740)
- When [get_block_template](https://github.com/WordPress/wordpress-develop/blob/e3a612a97c4c45acd7613779a46d86860e76cc65/src/wp-includes/block-template-utils.php#L1032C10-L1032C28) is called, the $id is expected to be hyphenated slug, if there is no matched DB record, the $id passed to [get_block_file_template](https://github.com/WordPress/wordpress-develop/blob/e3a612a97c4c45acd7613779a46d86860e76cc65/src/wp-includes/block-template-utils.php#L1080C20-L1080C43) should extracted from `original_template_path` post meta

@getdave

**Comment by getdave** [comment]
This won't work. We'll need a more comprehensive solution.

**Comment by bangank36** [comment]
> This won't work. We'll need a more comprehensive solution.

@getdave were you mentioning the hyphens replacement or the proposal of saving the template part as post meta?

**Comment by getdave** [comment]
> > This won't work. We'll need a more comprehensive solution.
> 
> @getdave were you mentioning the hyphens replacement or the proposal of saving the template part as post meta?

Just the approach in this PR. The Post Meta seems like the best approach.

**Comment by bangank36** [comment]
> Just the approach in this PR. The Post Meta seems like the best approach.

Sure, I am giving it a try!

**Pull request closed without merging**
