### PR TITLE
Alt image setting

### PR DESCRIPTION
**Pull request by etoledom**
## Description
This PR implements the Alt settings on image blocks.
The UI is temporary, so don't worry about the Textarea control being in the bottom-sheet itself, or the styles of it. We are working on it with Thomas.

Also: 
- Imported `BaseControl` and `TextareaControl` for parity with Web.
- Removed the `Done` button from the bottom-sheet as requested by Thomas.
- Small tweaks on the BottomSheet.Cell to behave better with longer texts.
- Made the bottom-sheet avoid the keyboard on iOS. (On Android it was already working)

**(Updated GIF)**
alt-setting

To test:
- Run the example project from the related `gutenberg-mobile` branch (https://github.com/wordpress-mobile/gutenberg-mobile/pull/531)
- Select an image block with image.
- Tap on the settings button (wheel in the inline tool bar)
- In the bottom-sheet, write something in the textinput control.
- Check that the Alt change.
- Close the bottom-sheet (swipe down or tap in the background)
- Open it again.
- Check that the old Alt value is there.

### CODE REVIEW

**Review by marecar3 — APPROVED** [review]
LGTM! 
update: Couldn't test on rotation change as content disappears due to other problems.

**Comment by etoledom** [comment]
Thank you @marecar3 for your review!

> update: Couldn't test on rotation change as content disappears due to other problems.

`due to other problems`, meaning that the issue not related with this PR, right?

---

I had to make a few changes to the Cells. To comply with Thomas design, I gave the label the possibility to be editable as a `TextInput`.

It should still be flexible enough for the requirements of `Image Uploads`, and I think that these changes won't affect it.

Still, if you could take another look it would be great. Thank you and sorry for asking review of the same PR again.

I updated the GIF in the description to show the new behavior.

image

**Comment by marecar3** [comment]
LGTM @etoledom !

**Comment by etoledom** [comment]
Thank you!

**Pull request merged**
