### PR TITLE
Verse block: Add support for the padding to the verse block

### PR DESCRIPTION
**Pull request by scruffian**
## Description
This adds support for custom padding to the Verse block. This also removed padding from the block in the editor, so that the editor and the frontend match.

## How has this been tested?
- Add a verse block to a post
- Adjust the padding in the editor
- Check that the padding is updated in the frontend

## Screenshots 
Editor:
Screenshot 2021-03-12 at 13 02 45

Frontend:
Screenshot 2021-03-12 at 13 02 51

## Types of changes
New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Seems cool. What does the removal of the 1em default padding mean for existing themes?

**Comment by scruffian** [comment]
> What does the removal of the 1em default padding mean for existing themes?

If existing themes add the padding to the frontend to match the editor and don't also add it to the editor styles then the frontend won't match the editor anymore - the frontend will stay the same though.

**Comment by jasmussen** [comment]
I'm thinking mostly in terms of existing themes that don't style the verse, but perhaps relied on the existing verse style. Very edgecase stuff, and probably acceptable.

**Comment by scruffian** [comment]
> I'm thinking mostly in terms of existing themes that don't style the verse, but perhaps relied on the existing verse style. Very edgecase stuff, and probably acceptable.

Yeah this could be a problem, but it would only impact the editor.

**Comment by carolinan** [comment]
Is not adding the visualizer on purpose?

375 (directory) themes uses wp-block-verse but that doesn't tell us much
https://wpdirectory.net/search/01F0KB3C3SWBX6PC047SSB3VW1

**Review by jasmussen — APPROVED** [review]
Oh of course! I missed that it was the editor stylesheet.

**Comment by scruffian** [comment]
@carolinan good point, I added the visualizer.

**Comment by carolinan** [comment]
For some reason, the visualizer goes outside the block 🤔 Perhaps it is better to remove it again.

the padding visualizer goes to the edge of the editor and over the next block

block editor, Twenty Twenty-One. Chrome Version 89.0.4389.82, Win10

**Comment by scruffian** [comment]
I added a wrapper div to fix this:

Screenshot 2021-03-15 at 12 00 30

Not sure if there's a better way to do this.

**Comment by jasmussen** [comment]
If at all possible, I would avoid a wrapper. In the past adding wrappers have bitten us.

**Comment by youknowriad** [comment]
I have the same issue about the need for a wrapper in #29335 for the visualizer in the group block, I'm leaning towards removing the visualizer for now until we find a non intrusive way to do it. (potentially using a Popover but may be a bit complex)

**Comment by carolinan** [comment]
The visualizer is nice to have but the padding is still visible (more visible if it is large, of course).

**Comment by scruffian** [comment]
Ok, removed the visualizer!

**Pull request merged**
