### PR TITLE
Update "hidden" icon to be clearer, and invert logic as used in Data Views

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

This PR updates the `unseen` icon to be clearer, and inverts the logic for which icon to show in Data View configurations.

For the moment, the eye is a closed eye, and the _seen_ icon is shown for the button that hides a particular property:

show hide

In this branch, I'm proposing an alternatetive to the closed icon, an eye with a strike-through. This is similar to icons for unlink, remove-submenu, remove-bug, and other similar icon pairs. Additionally it shows the unseen icon for the action to hide a particular property:

after

## Testing Instructions

Please test the site editor > Pages, and test the "View options" dropdown.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
I'd be happy for others to give feedback on the icon itself, but I think inverting the icon and changing it to a strikethrough eye makes sense.

It also matches the icon on the login screen:

image

image

This PR also brings Storybook's password field into consistency with the login screen:

http://localhost:50240/?path=/story/components-experimental-inputcontrol--show-password

image

image

**Review by jameskoster — APPROVED** [review]
The icon with strike seems more explicit to me which feels like a win.

**Comment by jasmussen** [comment]
Thank you. Do I need to add a changelog entry?

**Comment by t-hamano** [comment]
The icon design has changed so much that it might be worth adding a changelog.

**Comment by jameskoster** [comment]
It might be worth adding a data views changelog entry too?

**Comment by jasmussen** [comment]
Done, but 😩—the tests fail so often these days, I have to restart them endlessly.

**Comment by t-hamano** [comment]
It seems that many other PRs have failed tests as well, so let's try restarting it at a later date 👍

**Comment by t-hamano** [comment]
The tests should pass now. See #65939

**Comment by jasmussen** [comment]
Thanks for all the help!

**Pull request merged**
