### PR TITLE
RichText: remove wrapper (and use Popover for inline toolbar)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Hopefully unblocks #15554. Preparatory works has been done in #17580.

This PR removes the wrapper div around rich text's editable element.

Why? In some cases, it's important that the rich text element is a direct child of its parent (e.g. `figcaption` inside a figure, so that it is announced correctly.

`RichText` currently wraps the `contenteditable` element with `tagName` in an extra `div` element. This is mainly useful to position the inline toolbar. The inline toolbar can also be positioned with JS though.

Hopefully this can be used in #15554 so we don't need to create a shadow `RichText` element.

I can see it also being useful more generally for block that need a semantic relationship between the RichText element and its parent, e.g. for table cells within a table and perhaps in the future for list items in a list.

### Implementation notes

* The `wrapperClassName` prop is kept for now. If it is used, the editable element will still be wrapped in a `div`. We can deprecate this prop in a follow-up PR.
* I used `Popover` to render the inline format toolbar. To position it correctly next to the editable element, we need the ref, so I adjusted `<RichText>` and `<Editable>` to use `createRef` and `forwardRef`.

## How has this been tested?
Ensure the inline toolbar is positioned correctly in all blocks. E.g. in the gallery block.

## Screenshots 

Screenshot 2019-10-02 at 11 44 16

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by youknowriad** [comment]
Makes me wonder if we can somehow make this work for all use-cases? Is that feasible in your opinon?

**Comment by ellatrix** [comment]
@youknowriad What do you mean with use cases? Do you mean doing this for all blocks? I think, yes, we should add the prop for all blocks eventually. I'm not sure if we can just do it by default because some external blocks may rely on the class and/or wrapper element to position.

**Comment by youknowriad** [comment]
> What do you mean with use cases? Do you mean doing this for all blocks?

yes, that's what I mean, at some point I thought it was possible, the reason I say we should do it for all is that it makes editor styles way simpler (frontend would match backend more easily). 

It's something that can affect themes yes and block authors but we should do a dev-note about it. The public API is still the same.

**Comment by ellatrix** [comment]
@youknowriad Yeah I agree that we it would be way better if we can remove the wrapper for all blocks by default. The only issue I have found so far is the gallery caption, because the captions are absolutely positioned. That's the only scenario the inline toolbar wouldn't work be correctly positioned by itself. A more complex solution would be to always position the inline toolbar with JS and inline styles. What do you think?

**Comment by ellatrix** [comment]
To be honest, positioning it with JS makes sense... we already do it for the autocomplete pop up, the link pop up, etc...

**Comment by youknowriad** [comment]
> A more complex solution would be to always position the inline toolbar with JS and inline styles. What do you think?

Yes, this makes sense to me too. It's a bit hard to achieve properly (scrolling...) but if we manage to abstract this properly to avoid visible complexity in the core, I'm all for it.

**Comment by ellatrix** [comment]
Yes, either we still position it above rich text, and reposition if rich text's position is absolute, or we simply use `Popover`. I think it would be better to just go for `Popover`, so it benefits from improvement there too, and we eliminate some logic in rich text.

**Comment by youknowriad** [comment]
👏 Great work here, it seems to work perfectly :)

I think this PR can in theory break some editor styles because of the wrapper removal.  So it probably needs a dev note and we should do some theme testing.

cc @kjellr @jasmussen for more testing

**Comment by jasmussen** [comment]
This is working well for me. Really nice:

popover

I kind of even want this for ALL text now, i.e. remove it from the block toolbar! 😱 — I know, _controversial_!

There are a couple of little things. I quadrupled the size to make it more visible:

Screenshot 2019-10-02 at 09 53 16

1. The abs. positioning on non retina screen aligns to subpixels, which means icons will be blurred. I'm 99% sure we can't fix this, and it's okay, only I will notice it. But in case there's magic to make it unblurred, figured I'd mention.
2. It's a little close ot the text, can it be pushed upwards ever so slightly?
3. There's a 2px gray border, it should just be 1px.  

Really nice work.

**Comment by ellatrix** [comment]
> It's a little close ot the text, can it be pushed upwards ever so slightly?

Sure. I believe it was positioned 4px upwards before, so I can restore that.

> There's a 2px gray border, it should just be 1px.

Ah, thanks! I find what's causing this.

**Comment by ellatrix** [comment]
1. Repositioning on scroll is now smooth since #17699.
2. I removed the double border. Both the popover and the toolbar components were providing one.
3. I added some space between the toolbar and the rich text element (4px).
4. I corrected the toolbar positioning to exclude the padding of the rich text element, which can be quite a lot in case of the gallery caption.

**Comment by jasmussen** [comment]
Great work. Looks nice in TwentyNineteen:

Screenshot 2019-10-02 at 11 41 25

I do think the toolbar can go upwards another 2 pixels or even more, but it's fine.

In TwentyTwenty the toolbar isn't left aligned with the caption:

twentytwenty

But that isn't a regression of this PR, it's also the case in master:

Screenshot 2019-10-02 at 11 42 25

So not a blocker for merging this. TwentyTwenty may be doing something fancy with the captions that is out of our control, so don't spend too much on this.

**Comment by ellatrix** [comment]
@jasmussen The alignment has indeed been an issue for a long time. I'd suggest resolving this in a separate PR, as it's not related to what we're fixing here. It might make it easier though. If we align the toolbar, it will need to work correctly in RTL as well, so I don't think the solution is a trivial one.

I increased the buffer by two now.

**Comment by jasmussen** [comment]
All good on my end! 👍 👍

**Review by youknowriad — APPROVED** [review]

**Comment by ellatrix** [comment]
Thanks for the quick reviews @jasmussen and @youknowriad. The last commit removed some more dead CSS in the image and gallery blocks. We not need the table and table-caption ticks anymore for the image block, and the gallery block no longer needs to position the inline toolbar. The DOM now look exactly like it would on the front-end, which will be a lot easier for themes.

**Comment by ZebulanStanphill** [comment]
@jasmussen 
> I kind of even want this for ALL text now, i.e. remove it from the block toolbar! scream — I know, controversial!

If the inline rich text controls were moved out of the block toolbar, then there might be enough space to display the block name in the toolbar, which would help a lot with identifying what kind of block you've selected. Do you think that's something worth seriously considering?

**Comment by jasmussen** [comment]
I'm not seriously considering an on-select toolbar. But it's also not off the table if a PR appears, that makes it work superbly well. It has to have a benefit over what we have today, which it might given the right context. 

> then there might be enough space to display the block name in the toolbar

I do want to display the block name in the toolbar, I really do. But not only does the block toolbar have to work in deeply compact nesting situations, but it also has to accommodate every 3rd party block there will ever exist. And some blocks have really long block names, like "Testimonials Carousel", "Open Table Form", "Click to Tweet", "Decorative Heading", "Masonry Gallery", or hey, even "Legacy Widget (Experimental)". Add in german, and our desire to bump minimum font sizes from 13 to 14px and you have a challenge on your hands. I'm aware that not all of those blocks can transform, and I know that you could set a max-width and something like `text-overflow: ellipsis;` — but it's starting to become complex.

That's not a no — it's just why I personally think that the way forward is Element Queries. That is, if the block toolbar can scale to fit the available space, then we can show the block title when there's space, and collapse it when there isn't. The current challenge here is that element queries are still experimental, and the polyfill doesn't work with React.

**Pull request merged**
