### PR TITLE
Make the inserter full height

### PR DESCRIPTION
**Pull request by youknowriad**
Alternative to #19836

Tries to accomplish the same result with smaller changes that work across inserters.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for working on this. I imagine we'll want to use this as the basis going forward. Since working on the last one, I've been thinking that perhaps the treatment of blocks themselves might need a little more work, so I think it would be good to freshen up the mockup and then I can help bring this branch home.

**Comment by youknowriad** [comment]
Noting that this PR is also a requirement before starting to explore showing the block patterns in the inserter.

**Comment by youknowriad** [comment]
Can we merge this and continue iteratively or what needs to be done here?

**Comment by jasmussen** [comment]
Took this branch for a spin, here's a GIF:

gif

I do think it's a superior experience, but I'd love @mtias thoughts on it before we merge. I believe he's been thinking about the inserters a lot lately, and might have thoughts.

If we do go forward with this branch (I'm a fan), then two things:

1. There are a bunch of vertical scrollbars on the preview, not sure why exactly, probably something I can help fix if need be.
2. Let's bid farewell to the initial help text. It's a ton of verbiage and once you've read it a single time, you need not read it again.

**Comment by enriquesanchez** [comment]
This feels vastly better than what we have. On an "averagely sized" window, it looks great:

Screen Shot 2020-03-03 at 17 21 37

I'm however not a fan of all the empty space when the window is taller than average:

Screen Shot 2020-03-03 at 17 22 11

@jasmussen not sure if you've put any thought on this. I myself I'm undecided on how to go about this and if it's a big issue at all. 

@youknowriad I think I found a minor bug: when increasing my browser's window height, the inserter does not accurately grow in proportion to the window:

Screen Shot 2020-03-03 at 17 21 57

**Comment by jasmussen** [comment]
> not sure if you've put any thought on this. I myself I'm undecided on how to go about this and if it's a big issue at all.

I think it's not a big issue, but I definitely hear you, it's something to consider. 

The reason for the very tall inserter, outside of just leveraging the space, is because people don't scroll and discover more blocks. I would suggest that's an argument to explore collapsing only _some_ of the block sections, like Embeds perhaps, and then defaulting more categories to open.

**Comment by youknowriad** [comment]
> when increasing my browser's window height, the inserter does not accurately grow in proportion to the window:
@enriquesanchez This doesn't happen to me unless the dev tools are open which make me think it's fine.

**Comment by youknowriad** [comment]
did some cleanup here and rebased, it should be good.

**Review by karmatosed — APPROVED** [review]
Design wise, this does what expect it to. I will note that as the breadcrumbs become more important, potentially not overlapping those could be an iteration. That said, let's get this in so removing the design feedback label for now.

**Comment by youknowriad** [comment]
Let's try that.

**Pull request merged**
