### PR TITLE
Fix save, undo and redo keyboard shortcuts in navigation editor

### PR DESCRIPTION
**Pull request by grzim**
Saving post logic moved to upper layer so both - save button and cmd+s shortcut are using the same piece of code.

## Description

Regarding https://github.com/WordPress/gutenberg/issues/28213 keyboard shortcut to save navigation added.
The listener is added to the editor. As the editor does not play any interactive role, I have disabled the linter rule `eslint-disable-next-line jsx-a11y/no-static-element-interactions`

## How has this been tested?
Tested manually

## Types of changes

New feature 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — COMMENTED** [review]
Something I didn't realise is that there is already some code for the shortcut:
- https://github.com/WordPress/gutenberg/blob/b864c5de3e0b90b8c9558477176200b54ef6e9e6/packages/edit-navigation/src/components/layout/shortcuts.js#L13-L22
- https://github.com/WordPress/gutenberg/blob/b864c5de3e0b90b8c9558477176200b54ef6e9e6/packages/edit-navigation/src/components/layout/shortcuts.js#L49-L57

Sorry for that, I just thought they hadn't been implemented. The existing implementation uses the `useShortcut` and `registerShortcut` functions, the idea behind that APIs is that someday shortcut customisation can be added as a feature.

None of these shortcuts seem to be working though, so it'd be good to figure out why and fix them.

**Comment by grzim** [comment]
It is not working as `<NavigationEditorShortcuts/>` is not added to layout.index.js . It can be easily solved, nevertheless, I don't like the approach which is used here.
Is there any solid argument to keep a convention like `<BlockEditorKeyboardShortcuts.Register />` ? 
I really don't like this idea as it can be very confusing. 
Furthermore, from my experience, this entire approach with components returning null is improper as this kind of logic should be put to custom hooks.

**Comment by talldan** [comment]
@grzim I'm ok with only using hooks. I'm not completely sure why it's a component, but I think other editors also implement it this way using shortcuts, and that was likely copied in the navigation editor.

**Comment by grzim** [comment]
@talldan I have made a little investigation and it is just like you said. Editors implement it this way in order to make it possible to add shortcuts to blocks like this:
```
<BlockEditorProvider
			settings={ settings }
			value={ blocks }
			onInput={ onInput }
			onChange={ onChange }
			useSubRegistry={ false }
		>
			<KeyboardShortcuts />
...
</BlockEditorProvider>
```
The key concept is to make it possible to nest `<KeyboardShortcuts /> ` in any level of jsx structure and it will be applied only to the element in which `<KeyboardShortcuts /> ` is placed.
This is a kind of hacky approach as HOC with hooks should be used instead. 
So here we can either use hooks as this would be a cleaner solution or leave it as it is now what makes it less clean but consistent with other editors. In my opinion - consistency wins here.

**Review by talldan — APPROVED** [review]
> So here we can either use hooks as this would be a cleaner solution or leave it as it is now what makes it less clean but consistent with other editors. In my opinion - consistency wins here.

Agreed. Could always explore refactoring it all to hooks in a separate PR.

I recall another potential issue with the `Register` components is that they always have to come before the actual shortcut component, so definite scope for improvement.

Anyway, This is working nicely, I rebased locally to bring in some other recent fixes and can confirm save, undo, and redo are now working well. Thanks @grzim  🎉

**Pull request merged**
