### PR TITLE
wip: Hide overflowing  navigation menu items

### PR DESCRIPTION
**Pull request by vcanales**
## Description

This PR tries to implement automatically hiding items that do not fit on the horizontal navigation block, and showing them within a dropdown instead, following the approach discussed in https://github.com/WordPress/gutenberg/issues/27131#issuecomment-763165601 ([codepen](https://codepen.io/vcanales-the-styleful/pen/eYdXWgz)). The approach uses CSS and JavaScript to detect when an item is being 'wrapped' (moved to a new line). 

The current challenge is applying this detection to the Navigation block's InnerBlocks, which requires identifying the underlying DOM element to add CSS classes to it and to move it to a different container.

### In progress
- [ ] Try to group unwrapped InnerBlocks in a different container.
- [ ] Experiment with CSS grid instead of flex. The reason we have to play a bit with the DOM is that flex does not allows us to organize elements both horizontally and vertically within a flex container, so a new container has to be created to group the invisible elements within a dropdown—CSS Grid might allow this kind of behavior, perhaps by creating two grid areas.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
This is cool, I can't wait to test it! I'm getting this error when running:

Screenshot 2021-02-02 at 11 35 25

This is despite a few npm install's, so I suspect you forgot to include a module that's needed.

**Comment by vcanales** [comment]
> This is cool, I can't wait to test it! I'm getting this error when running:

Sorry about that, it's fixed now.
Keep in mind that this only shows the hiding menu items, so not much more to check out at the moment—trying to manipulate InnerBlocks has been a bit harder than I expected.

**Comment by jasmussen** [comment]
This is what I see, editor: 

editor

This is what I see on the frontend:

front

Quick notes:

- The brown and green I assume are just debug colors.
- Some of the broken layout is my own fault from my theme.

I'm missing the overflow button. I'm guessing that's also my theme? 

But overall, the popping off of menu items seems to work really well, so high level this seems promising. It opens a few questions around editing, specifically around how you edit the menu when some items are in the popover. I think the approach we should try and find here is: only pop off items when the navigation block is _not_ selected. As soon as you select the navigation block, you see every menu item and can edit. This embraces the "unselected is a preview, selected has additional controls" principle.

Another thought, and perhaps you're already pondering this, instead of building this into the navigation block, could this be a separate "Responsive Menu" block? Anything you put inside it is a hamburger on mobile, and shown on desktop. And this "gradual reveal" is then an option of that block — showing the sequence of content base on available space. I could see it being useful for other blocks, such as social links.

Finally, I wanted you to be aware of #28265. That PR creates a single "Page List" block which outputs all pages, as a single block. Ideally the frontend should be unchanged, so I suspect the primary challenge will be the editor preview, and I think we can probably just fake that with overflow: hidden;.

**Comment by vcanales** [comment]
> * The brown and green I assume are just debug colors.

That is correct :)

> As soon as you select the navigation block, you see every menu item and can edit. This embraces the "unselected is a preview, selected has additional controls" principle.

Actually, I imagine this as the Dropdown showing up when the Navigation is selected. Perhaps this allow the user to, for instance, use a different style for a Block when it is displayed within the dropdown menu—this is future talk though.

> Another thought, and perhaps you're already pondering this, instead of building this into the navigation block, could this be a separate "Responsive Menu" block?

I had not though of that. I'm not sure if I'm understanding this correctly— do you mean having a normal Navigation block, and then a responsive block within it, or both blocks living side by side, with only one showing up depending on the resolution? 
If it's the second way, would the user have to create each menu manually? I'm not sure if there's a way to make the elements of a Navigation Block shareable.

> Finally, I wanted you to be aware of #28265. That PR creates a single "Page List" block which outputs all pages, as a single block. Ideally the frontend should be unchanged, so I suspect the primary challenge will be the editor preview, and I think we can probably just fake that with overflow: hidden;.

Thanks for bringing up. Indeed it could pose some challenges, both in code and UI. The latter because we'd have Dropdowns within Dropdowns if the pages element is made invisible. I'll play around with the work on that PR later to check out how it behaves at the moment.—it looks like it's quite close to getting merged.

**Comment by jasmussen** [comment]
> do you mean having a normal Navigation block, and then a responsive block within it, or both blocks living side by side, with only one showing up depending on the resolution?
If it's the second way, would the user have to create each menu manually? I'm not sure if there's a way to make the elements of a Navigation Block shareable.

I mean basically this hierarchy of blocks, forgive the crude ascii mockup:

```
<Site logo />
<Site tagline />
<Responsive Menu>
	<Navigation />
	<Paragraph (or other block) />
</Responsive Menu>
```

In the above, the Responsive Menu block would ensure that the Navigation and Paragraph block collapsed into a hamburger menu on mobile, and showed up on desktop. This Responsive Menu block would also have the option to "pop off" these items into the overflow menu, as this effort explores.

> The latter because we'd have Dropdowns within Dropdowns if the pages element is made invisible

Potentially we could show menu items just as indented submenu items when in the overflow menu, rather than fold-out sub sub menus.

**Comment by vcanales** [comment]
Ah yes, that makes a lot of sense. The current method assumes some things from its children, such as their height and that they are `display: block;`—I'm not sure what challenges that might create if we were to make it available for other blocks. I will make this into a component within the Navigation Block in order to get something that works there, and I think we can work on abstracting it later.

**Comment by vcanales** [comment]
Closed in favor of https://github.com/WordPress/gutenberg/pull/30047

**Pull request closed without merging**
