### PR TITLE
[Mobile] Use react-native-url-polyfill in globals

### PR DESCRIPTION
**Pull request by mkevins**
### Related PR

`gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2923

## Description

Uses `react-native-url-polyfill` via import in `globals.js`. This is needed for properly merging URL query parameters duing middleware processing for endpoints utilising api-fetch. We have already incurred the cost to the bundle size, since we are utilizing this module in `is-url.native.js`. This PR makes sure we are using the polyfill implementation globally.

It seems that the unit tests we currently have for URL are not being run against the default URL implementation provided by the react-native runtime. I've opened a branch (https://github.com/WordPress/gutenberg/pull/27868) for demonstration purposes to have the tests running with the default URL implementation, and several of the tests fail. I've also added logging for errors, which typically are caught and silently ignored. We can see [here](https://github.com/WordPress/gutenberg/pull/27868/checks?check_run_id=1598383769#step:6:153) the failures arise from unimplemented getters.

This PR fixes this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2922

### Steps to test

1. Create a new post or page (on a site with some published posts and pages)
2. Add a button block
3. Edit the link in the button block
4. Tap "Search or type URL" to open link picker
5. Begin typing a few characters and wait for the results
6. Erase the search a type a few different characters

**Expected behavior**
The results should be different for searches which have differerent queries. The search results should reflect the query being searched for.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Tug** [comment]
Change looks good to me, could we have a test as part of this change as well. If needed I can test that removing the import actually makes the test fail

**Comment by mkevins** [comment]
> Change looks good to me, could we have a test as part of this change as well. If needed I can test that removing the import actually makes the test fail

It turns out we already have several tests for url, which were passing spuriously. In [a previous approach](https://github.com/WordPress/gutenberg/pull/27856) (before I realized we are already including this polyfill with our bundle, but not using it universally), we tried manually patching the `URL` implementation, and this solved the underlying issue. Tests were also added on that branch for the patched prototype method. These tests intermittently failed (with `--maxWorkers=2`), which was unexpected, and further investigation revealed that the patch was occasionally being applied to a different `URL` implementation, incompatible with the manual patch (which relied on the `this._url` property in React Native's `URL`). The tests have been running against a `URL` implementation different from that which we are using in production.

This also explains why the unit tests did not break, even though the actual behavior in the app _did_ break. I created [this branch](https://github.com/WordPress/gutenberg/pull/27868/files) to demostrate that several `url` tests do indeed fail when tested against the `URL` implementation that is actually used in production. These same tests pass with the polyfilled version added here https://github.com/WordPress/gutenberg/pull/27867/commits/e61c14d3215f1eba67b5af9b3fe9322df70fb3d5.

**Comment by enejb** [comment]
This works as expected for me. Lets fix the conflict in the index.native.js file and ship this :)

**Comment by mkevins** [comment]
It seems the fixture tests for native were disabled when the native test file was [deleted here](https://github.com/WordPress/gutenberg/pull/27956/files#diff-6f66ed1b5dc2f813d49920e54bf1407532368fb227404c950c2a1a059b7123c3). I've re-added the tests, and ensured we are testing against the polyfill implementation used in production with this PR.

I've added some exclusions to the fixtures, since they've been updated in the same jest upgrade PR. Also, I removed the native fork of `is-url.native.js`, since the only difference was the inclusion of the polyfill, which we are now using globally.

**Review by enejb — APPROVED** [review]
I tested this and it worked well for me. Thanks for the fixes!

**Comment by mkevins** [comment]
Thanks for the review Enej, and for troubleshooting the CI issues with me. :smile:

**Pull request merged**
