### PR TITLE
Add: Preset gradient functionality button block

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Implements: https://github.com/WordPress/gutenberg/issues/16482
Related: https://github.com/WordPress/gutenberg/issues/16662

This PR adds a set of Gradient related functionality and components and uses them to implement gradient functionality in the button block.
For now, we still don't have a custom gradient functionality we just have gradient presets.

Themes will be able to configure gradient presets. But we need a default set of gradients when themes did not pass their own set. I think this set is not very creative and we should look into having an awesome set :)
cc: @mapk, @kjellr 

## How has this been tested?
I added the button block. I used the gradient panel and I verified the preset gradients work as expected.

## Screenshots 
image

### CODE REVIEW

**Comment by senadir** [comment]
🎉🎉🎉🎉
Will test today & report back, thank you so much for working on this!

**Comment by senadir** [comment]
as per today's editor chat, there has been a discussion of whether we should use classes for gradients or directly inline them.

in my point of view, I think classes are the best, most compatible solution in case of updating & or changing the visual identity

**Comment by mapk** [comment]
> I think this set is not very creative and we should look into having an awesome set :)

In addition to some of Kjell's example above, I'd like to see a cool gradient and warm gradient if it's not too much. I can see these gradients being used as backgrounds to the Group block and Cover block.

**Cool**

- Vivid Green Cyan (# 00d084) to Vivid Cyan Blue (# 0693e3)

**Warm**

- Luminous Vivid Amber (# fcb900) to Luminous Vivid Orange (# ff6900)

Screen Shot 2019-08-28 at 4 45 16 PM

> as per today's editor chat, there has been a discussion of whether we should use classes for gradients or directly inline them.
> in my point of view, I think classes are the best, most compatible solution in case of updating & or changing the visual identity

I'd also agree that classnames would be wonderful here. 👍

**Comment by jorgefilipecosta** [comment]
Hi @mapk, @kjellr, I updated the PR to use the suggested backgrounds.
We have now many predefined gradients. Should we also include some radial gradients (in that case probably we need to remove some of the current gradients)?
We have a problem right now we can not visually differentiate "Black to White" from 
"Black to Transparent" as the background of the gradient picker is also white. Maybe we can try to add small png bellow as background with gray and white squares to indicate transparency?
Regarding the class usage, I update the attribute to be "customGradient" so right now we will always set custom values. This change allows us to quickly right after adding the classes mechanism. I'm not adding it right now because this PR is already huge and if I increase its size, even more, it becomes impossible to review.
This PR depends on https://github.com/WordPress/gutenberg/pull/17154 which is pure code refactor I would like a review in that PR first so we can advance with this one :)

**Comment by kjellr** [comment]
> Hi @mapk, @kjellr, I updated the PR to use the suggested backgrounds.

I think I'm actually still seeing the old colors here? 

Screen Shot 2019-09-04 at 1 42 14 PM

> We have a problem right now we can not visually differentiate "Black to White" from
"Black to Transparent" as the background of the gradient picker is also white. Maybe we can try to add small png bellow as background with gray and white squares to indicate transparency?

Yeah, that makes sense. Something like this: 

Frame 3

We could draw that grid as an SVG behind the gradient. [Here's a sample SVG to try](https://cloudup.com/cLyGYFS4X2J). 

Trying this out, I'm wondering if it actually makes sense to have these exist in their own panel in the first place? Since these gradients are colors, I'd expect to find them appended to the rest of the color swatches: 

Frame 4

**Comment by jorgefilipecosta** [comment]
Hi @kjellr,
> I think I'm still seeing the old colors here?

Sorry, I missed to push my update it should be fixed now.


> >We have a problem right now we can not visually differentiate "Black to White" from
"Black to Transparent" as the background of the gradient picker is also white. Maybe we can try to add small png bellow as background with gray and white squares to indicate transparency?

> Yeah, that makes sense. Something like this:
Frame 3

I will try to add this transparency mark.


> Trying this out, I'm wondering if it actually makes sense to have these exist in their own panel in the first place? Since these gradients are colors, I'd expect to find them appended to the rest of the color swatches:

Soon we will have a custom gradients functionality I opted for a separate panel to not make a single panel very huge.
We could open the custom gradients panel in a Popover (although none of the designs proposed suggests that), but if we open in a popover we will need a Custom gradient button and custom color button and I'm not sure if having the two buttons is intuitive.
Having the colors and gradients together means 24 color options by default, I guess it may be too many options for a single panel.

**Comment by mapk** [comment]
> I updated the PR to use the suggested backgrounds.

Looking through, I only see a few. Are we missing the gradients I had suggested earlier?

Here's what I'm seeing right now. I notice the color white by itself is included there. And two of the Black-to-white gradients are duplicated.

**Comment by jorgefilipecosta** [comment]
> Looking through, I only see a few. Are we missing the gradients I had suggested earlier?

Hi @mapk the gradients you suggested Vivid Green Cyan (# 00d084) to Vivid Cyan Blue (# 0693e3) and Luminous Vivid Amber (# fcb900) to Luminous Vivid Orange (# ff6900) was there, but I wrongly set one of the transparency values the problem was fixed.

Screenshot 2019-09-07 at 18 40 02
Screenshot 2019-09-07 at 18 40 09

> Here's what I'm seeing right now. I notice the color white by itself is included there. And two of the Black-to-white gradients are duplicated.

Hi @mapk the color white is White to Transparent, and one of the Black-to-white gradients is, in fact, a black to transparent. Both white and transparent were suggested as noted before we will need a way to indicate transparency (the typical white and dark squares). I hope to add this functionality very soon.
For now, to test if it gradients work well, we can nest the button inside a group and change the background color of the group.

**Comment by jorgefilipecosta** [comment]
The transparency indication was added now we can differentiate between white and transparent gradients:
Screenshot 2019-09-07 at 19 43 19

Props to @kjellr for providing the transparency SVG!

**Comment by kjellr** [comment]
Thank you, @jorgefilipecosta! This is looking great. A few things to note: 

The transparency SVG is looking great. I'm seeing it applied to selected colors, even when they aren't transparent though: 

transparent

---

Seeing these in action, I think we can trim out the `Light Green Cyan to Vivid Green Cyan` color swatches. Those are really subtle, and it's hard to tell they're gradients at a glance. 

---

The `White to Transparent` options need a little adjusting so that their base color is white the whole time. Something like `linear-gradient(90deg, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0) 100%)`, with a `transparent` background color. 

Current: 
Screen Shot 2019-09-09 at 1 47 27 PM

Should be:
Screen Shot 2019-09-09 at 1 48 26 PM

---

Also, I wonder if we can reorder some of the items, so that similar gradients are right next to each other? 

Current:

Screen Shot 2019-09-09 at 1 49 35 PM

Suggestion: 

Screen Shot 2019-09-09 at 1 51 21 PM

**Comment by jorgefilipecosta** [comment]
Hi @kjellr, I applied all the suggested improvements for the default gradients. Regarding the transparency problem on the active option, I spent some time trying to find a solution that did not evolve a significant refactor of the styles in this component and unfortunately, I did not found a "decent" solution. I will try to look into this problem again tomorrow with fresh eyes.

**Comment by huntersinclairtiv** [comment]
How close is this to being added to the product?

**Comment by jorgefilipecosta** [comment]
This PR was rebased, and the transparency problem on the active option was fixed.

**Comment by jorgefilipecosta** [comment]
> How close is this to being added to the product?


Hi @huntersinclairtiv, the code seems ready and the issues fixed. But we still need a code review on https://github.com/WordPress/gutenberg/pull/17154 before we can merge this PR so the timing, for now, is uncertain.

**Comment by jasmussen** [comment]
I'm so excited for gradients to land, I took a stab at making a wider range of presets. The idea being that if we are launching V1 with presets ONLY, and not yet with a UI to customize those presets, it's important we launch with a range of high quality and widely useful gradients right off the bat. So I made these:

Screenshot 2019-09-24 at 13 06 31

1. There are no duplicates for each direction. They are all top left to bottom right. The reason being that, arguably, these are easier to use. Also, it feels of more value to have a range of different gradients, than a bunch of confusing duplicates each with different orientations.

You could also see this as a _bold first step_ and the next immediate step right after being to let you customize those presets using the UI outlined in https://github.com/WordPress/gutenberg/issues/16662.

Props @onuro, as I used some of the gradients they provided in the sketch file on that thread.

2. There are a range of gradients built using the existing gutenberg palette, and a number of additional ones, some that feature multiple color stops. I also tweaked the capitalization a little bit to match the capitalization of those colors. 

3. It removes the transparent gradients. Those can be cool, but they aren't that useful in the context of just the block. It's nice that the foundations for adding these (gray square pattern below), so let's add some like that, when this feature expands beyond the Button block.

Let me know what you think!

**Comment by mapk** [comment]
> There are no duplicates for each direction. They are all top left to bottom right. The reason being that, arguably, these are easier to use. Also, it feels of more value to have a range of different gradients, than a bunch of confusing duplicates each with different orientations.

Excellent reasoning, @jasmussen! In the future we can add a gradient direction control as you noted.

> It removes the transparent gradients.

Nooooo! Alrighty, I get your point. 😉 In context of the Button block, this makes sense.

**Review by mapk — APPROVED** [review]
From a design perspective, this looks like a great v.1.

**Comment by spacedmonkey** [comment]
It should be possible to define gradient in PHP using `add_theme_support` similar to [editor-color-palette](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#block-color-palettes). Could I recommend `editor-gradient-presets` as a name.

**Comment by jorgefilipecosta** [comment]
> It should be possible to define gradient in PHP using add_theme_support similar to editor-color-palette. Could I recommend editor-gradient-presets as a name.

Hi @spacedmonkey, yes the plan is for themes to be able to change the default gradient presents. When this is merged the following step is a custom gradient component and in parallel, we will add the theme API's `editor-gradient-presets` sounds like a good name to me, thank you for the suggestion 👍

**Comment by spacedmonkey** [comment]
Created a follow up issue here. https://github.com/WordPress/gutenberg/issues/17774

**Comment by mmtr** [comment]
Button blocks with gradients are currently considered invalid blocks when loaded on multisite WordPress install. I created an issue with more context: https://github.com/WordPress/gutenberg/issues/17938

**Comment by jorgefilipecosta** [comment]
Just for the record, a PR that addressed the button invalidation problem on WordPress multisite installs was recently submitted and merged https://github.com/WordPress/gutenberg/pull/17940.
Thank you for reporting this issue @mmtr!

**Pull request merged**
