### PR TITLE
Try: Remove important on disabled switcher state.

### LINKED ISSUE #29130: Block switcher icon no longer overrides custom background color
The [block-switcher stylesheet](https://github.com/WordPress/gutenberg/blob/2475a366cf1dbc2e7ffa347de8eba5624c180a88/packages/block-editor/src/components/block-switcher/style.scss#L50-L59) no longer has a background color for block switcher icons in the `disabled` state.

PR #16390 added a gray background color to make sure the dark icon color had contrast, and then #19344 removed the light background.

[Original report by @dingo_d on Trac](https://core.trac.wordpress.org/ticket/26350#comment:37
)
> In the wp-includes/css/dist/block-editor-style.min.css there is a
> `.components-button.block-editor-block-switcher__no-switcher-icon:disabled .block-editor-block-icon.has-colors{color:#1e1e1e!important}`
> 
> Which turns all the icons in the editor for blocks black (dark gray). Not sure why, as I don't see this in the GB on github 🤷🏼‍♂️
> 
> This is grating because when you are building your own blocks and icons, they are turned black, even though you set the color to be white for instance (when you want to switch one block to another).
> 
> We have fills in the icons set to `currentColor` so that the background of the icon can come through and it looks seamless in the block picker.

CSS overrides the color of the icon in the editor

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #29130 by removing an !important selector.

## How has this been tested?

Paste this in your functions.php

```
/**
 * Custom post type and template
 */

// Create a custom post type.
function myplugin_custom_post_type() {
	register_post_type( 'podcast',
		array(
			'labels' => array(
				'name' => __( 'Podcasts' ),
				'singular_name' => __( 'Podcast' )
			),
			'public' => true,
			'has_archive' => true,
			'rewrite' => array('slug' => 'podcast'),
			'show_in_rest' => true,
			'supports' => [
				'title', 'editor', 'custom-fields', // Custom fields must be supported for meta handling to function.
			],
		)
	);
}
add_action( 'init', 'myplugin_custom_post_type' );

// Assign a post template to our custom post type
function myplugin_register_template() {
	$post_type_object = get_post_type_object( 'podcast' );
	$post_type_object->template = array(
		array( 'core/heading', array( 'level' => 3, 'content' => 'Description', ) ),
		array( 'core/paragraph', array( 'placeholder' => 'Add description', ) ),
		array( 'core/heading', array( 'level' => 3, 'content' => 'Heading', ) ),
		array( 'core/paragraph', array( 'placeholder' => 'Add show notes', ) ),
	);

	// Lock the template from being rearranged or items deleted.
	$post_type_object->template_lock = 'all'; // Can be "all" or "insert", the latter allows moving blocks around.
}
add_action( 'init', 'myplugin_register_template' );
```

Now you have a new CPT, "Podcasts", create a new such and note how the blocks are locked. By being locked, they can't be transformed, meaning the rule to ensure no hover style on the block switcher icon takes effect:

Screenshot 2021-03-04 at 09 26 43

This icon should stay black even when hovering.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
Seems like the rule is to ensure the block switch icon is "grayed" out when it's disabled (for normal icons and colored icons like embeds..), if we don't want that anymore, can we just remove the rule?

**Comment by jasmussen** [comment]
That shows it like so:

Screenshot 2021-03-08 at 10 23 59

The comment adjacent to it shows this:

`// Even when the block switcher does not have any transformations, it still serves as a block indicator.`

So it seems to suggest that it should not be grayed in that state. But I don't have a strong opinion.

**Comment by youknowriad** [comment]
Not sure I understand :P What impact does the rule has no? (after your changes) none? or does it still trigger in some cases?

**Comment by jasmussen** [comment]
Sorry, it's definitely a bit fuzzy. This is the full rule in trunk:

```

// Even when the block switcher does not have any transformations, it still serves as a block indicator.
.components-button.block-editor-block-switcher__no-switcher-icon:disabled {
	opacity: 1;

	// Since it's not clickable, though, don't show a hover state.
	&,
	.block-editor-block-icon.has-colors {
		color: $gray-900 !important;
	}
}
```

_This PR just removes the !important_.

With the rule present, !important or not, a locked block, or a block without transformations, looks like this:

Screenshot 2021-03-08 at 10 32 31

With the entire rule removed, it looks like this:

110301500-723ab880-7ff8-11eb-9c52-3035ba64abf0

Note the semi transparent block switcher icon.

The removal of the !important rule just makes it easier to let the icon colors bleed through.

**Comment by youknowriad** [comment]
Ok this makes sense :) Thanks.

**Review by youknowriad — APPROVED** [review]

**Pull request merged**
