### PR TITLE
Crop preview with react-easy-crop

### LINKED ISSUE #23567: Error rotating images
**Describe the bug**

In some cases when rotating an image in the editor an error is thrown from `canvas.toBlob`, and the image is not rotated.

In Firefox the error is:

```
SecurityError: The operation is insecure.
```

In Google Chrome the error is:

```
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```

The error does not seem to happen on initial image placement—only when editing a previously placed image.

**To reproduce**
1. Add an image to your media library
2. Add that new image to a new post
3. Save as draft
4. Reload editor
5. Try to rotate the placed image
6. See error in console and that image wasn't rotated

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Replaces the canvas-based rotation preview with react-easy-crop preview.

Fixes #23567. Sometimes rotating the image caused an error due to `canvas.toBlob`.

It is possible to have a crop out of bounds from the image by using a portrait image, rotating it to landscape and then using a portrait aspect ratio. This may be able to be fixed in a future PR by setting a minimum zoom on rotation and aspect ratio changes, but for now a black background was added so the cropping area is still visible in this condition.

Calculations are done generically for any rotation based on how WP_Image_Editor handles rotations. So this also paves the way for a straighten control (rotate between -45 and 45 degrees) and re-adding the flip option now that react-easy-crop supports flip in version 3.1.0.

## How has this been tested?

Extra steps to verify #23567:

1. Add an image to your media library
2. Add that new image to a new post
3. Save as draft
4. Reload editor
5. Rotate the placed image in the editor
6. See that the image rotates properly

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
After rotation, I see this:

Screenshot 2020-06-30 at 15 53 18

**Comment by ajlende** [comment]
Are you referring to the extra space around the crop area? If so, that's just how react-easy-crop works right now. When rotating, it attempts to resize the crop area based on the calculated width of the rotated image since the image size doesn't change with the rotation.

scale crop area

There's two open issues (https://github.com/ricardo-ch/react-easy-crop/issues/116 and https://github.com/ricardo-ch/react-easy-crop/issues/141) that are related to rotating that I can tackle if you consider this a blocker. I don't see it as a problem right now, as the extra padding is in line with https://github.com/WordPress/gutenberg/issues/22576.

**Comment by ellatrix** [comment]
> Are you referring to the extra space around the crop area?

I'm referring to both the extra padding around the image _and_ the crop size being off. Regarding the extra padding (or "air"), I don't really like this change as it takes away the preview effect. In fact, I think the raster should exactly match the width/height of the image. It could be useful to see the cropped parts of the image, but maybe we can overflow those if the user is going to move the image.

**Comment by ajlende** [comment]
> and the crop size being off

Hmm, looks like that's only happening with landscape images for me. I'll take a look into it.

If that gets fixed, is the padding/air also a blocker for this PR? Or is it something that I could try to fix in react-easy-crop and then fix here with just a dependency update?

**Comment by ellatrix** [comment]
> If that gets fixed, is the padding/air also a blocker for this PR?

It would be great if we can get it to work without any visual differences from what we have now. Other than that, I think this is a good change!

**Comment by ajlende** [comment]
The fact that you can't zoom out to fill the whole frame is [a bug in react-easy-crop](https://github.com/ricardo-ch/react-easy-crop/issues/151). I'm going to fix it there instead of making a workaround here, so this PR will be on hold until that fix gets put into a release.

**Comment by skorasaurus** [comment]
think this can be closed since the original issue https://github.com/WordPress/gutenberg/pull/28255  ? Reopen if you think this using react-easy-crop is a better solution long term.

**Pull request closed without merging**
