### PR TITLE
List v2: fix migration when nested list is invalid

### LINKED ISSUE #44757: List v2: Lists with 3 levels are impossible to edit without breaking after Gutenberg 14
### Description

Lists with 3 levels **made before Gutenberg 14**, with this update if edited will be broken.

Adding new items or changing the URL breaks the list. Outdent and Indent don't work either.

### Step-by-step reproduction instructions

1. Build a 3-level list with Gutenberg older than 14 or without Gutenberg.
2. Install Gutenberg 14.
3. Edit the list: add new items, change URLs, etc.

### Screenshots, screen recording, code snippet

Here is an example:

Adding a new item or changing the URL breaks the list. It is impossible to do something without completely redoing the list.

I have many lists with dozens of items, now it's impossible to make changes to lists with 3 levels without breaking them. Remaking lists with several dozen items is a huge job. Removing Gutenberg makes lists made after version 14 uneditable unless redone. And wordpress.com users don't even have that possibility. 

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## What and why?

This should fix #44757. The problem with this list is that there's multiple nested lists inside one list item, which is (for us) invalid. Thankfully we have existing code that takes care of this in the raw handler, but we're not making use of it. This PR changes list migration so that it now runs through the raw handler, which fixes the lists.

## How?

Use the `rawHandler`. 

## Testing Instructions

See #44757 and added test.

### CODE REVIEW

**Comment by michalczaplinski** [comment]
👋 Hi there! Is this intended to be merged before the RC2 tomorrow?

**Comment by ellatrix** [comment]
This should be merged, yes, but needs a review.

**Comment by cbravobernal** [comment]
The fix is not working in my environment :-(

Gutenberg: Version 14.4.0-rc.1
WP: 6.2-alpha-54646)

I'm using

```
<!-- wp:list -->

<ul><li><strong>Item</strong><ul><li><strong>Item</strong><ul><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a href="#" target="_blank" rel="noreferrer noopener">Item</a></li></ul></li></ul><ul><li><strong>Item</strong><ul><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank"><strong>Item</strong></a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li></ul></li></ul><ul><li><strong>Item</strong><ul><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li><li><a rel="noreferrer noopener" href="#" target="_blank">Item</a></li></ul></li></ul></li></ul>

<!-- /wp:list -->
```

https://user-images.githubusercontent.com/37012961/197565265-5b81e8ee-113d-4566-9be8-507562f489d8.mov

**Comment by ellatrix** [comment]
@c4rl0sbr4v0 I tried your HTML and it's working fine? Note that this PR will not fix list blocks if they're already migrated. Only unmigrated blocks. So create a new post with your content to test the PR.

**Review by mcsf — APPROVED** [review]

**Comment by ironprogrammer** [comment]
As this is [being discussed](https://wordpress.slack.com/archives/C03LZ88NX6G/p1666982786544189) for backport to WordPress 6.1.1 or as a possible RC6 candidate, here is an additional report confirming reproduction in 6.1-RC5 and patch efficacy:

## Reproduction Report

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6
- Browser: Safari 16.0
- Server: nginx/1.23.2
- PHP: 7.4.32
- WordPress: 6.1-RC5-54715-src
- Theme: twentytwentythree v1.0
- Active Plugins:
  - gutenberg NOT active

### Actual Results
- ✅ Non-migrated List block markup (from [Issue 44757](https://github.com/WordPress/gutenberg/issues/44757#issuecomment-1271845029)) necessitates block recovery, and recovered nested list elements are treated as one list item, causing odd editing behaviors.

## Patch Test Report

### Environment
- Active Plugins:
  - gutenberg v14.4.0 (`trunk` with #44822 merged)

### Actual Results
- ✅ Patch allows non-migrated List block markup to be edited as expected. Block recovery still required.

### Supplemental Artifacts
| | |
|:-------------------------:|:-------------------------:|
| Repro | Patched |
| repro | patch |

**Pull request merged**
