### PR TITLE
Revert #55219 fix/block-settings-origins

### LINKED ISSUE #52200: Global styles: Default font sizes are added
### Description

I created a blank theme and added custom font sizes.
This works intended in the editor, but in the Global styles, default font sizes are added in the drop down (S, M, L, XL)

### Step-by-step reproduction instructions

1. Copy the nearly blank theme.js from below
2. Go into Global Style → Typography → Text
3. See in the drop down the additional "Small, Medium, Large, Extra Large" font sizes, that shouldn't be there.

<details><summary>theme.js</summary>
<p>

```javascript
{
  "settings": {
    "appearanceTools": true,
    "color": {
      "background": true,
      "custom": true,
      "customDuotone": true,
      "customGradient": true,
      "defaultDuotone": false,
      "defaultGradients": false,
      "defaultPalette": false,
      "duotone": [],
      "gradients": [],
      "palette": [],
      "text": true
    },
    "layout": {
      "contentSize": "620px",
      "wideSize": "1000px"
    },
    "shadow": {
      "defaultPresets": true,
      "presets": []
    },
    "spacing": {
      "customSpacingSize": true,
      "spacingScale": {
        "increment": 1.5,
        "mediumStep": 1.5,
        "operator": "*",
        "steps": 7,
        "unit": "rem"
      },
      "spacingSizes": [],
      "units": ["%", "px", "em", "rem", "vh", "vw"]
    },
    "typography": {
      "customFontSize": true,
      "dropCap": true,
      "fluid": true,
      "fontFamilies": [
        {
          "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
          "name": "System Font",
          "slug": "system-font"
        },
        {
          "fontFace": [
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "700",
              "src": ["file:./assets/fonts/barlow_italic_700.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "700",
              "src": ["file:./assets/fonts/barlow_normal_700.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "600",
              "src": ["file:./assets/fonts/barlow_italic_600.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "600",
              "src": ["file:./assets/fonts/barlow_normal_600.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "italic",
              "fontWeight": "400",
              "src": ["file:./assets/fonts/barlow_italic_400.ttf"]
            },
            {
              "fontFamily": "Barlow",
              "fontStyle": "normal",
              "fontWeight": "400",
              "src": ["file:./assets/fonts/barlow_normal_400.ttf"]
            }
          ],
          "fontFamily": "Barlow",
          "slug": "barlow"
        }
      ],
      "fontSizes": [
        {
          "name": "Display xl",
          "slug": "Display-xl",
          "size": "96px",
          "fluid": {
            "max": "96px",
            "min": "52px"
          }
        },
        {
          "name": "Display lg",
          "slug": "Display-lg",
          "size": "72px",
          "fluid": {
            "max": "72px",
            "min": "46px"
          }
        },
        {
          "name": "Display md",
          "slug": "Display-md",
          "size": "60px",
          "fluid": {
            "max": "60px",
            "min": "42px"
          }
        },
        {
          "name": "Display sm",
          "slug": "Display-sm",
          "size": "52px",
          "fluid": {
            "max": "52px",
            "min": "40px"
          }
        },
        {
          "name": "Heading 1",
          "slug": "Heading-1",
          "size": "48px",
          "fluid": {
            "max": "48px",
            "min": "36px"
          }
        },
        {
          "name": "Heading 2",
          "slug": "Heading-2",
          "size": "36px",
          "fluid": {
            "max": "36px",
            "min": "30px"
          }
        },
        {
          "name": "Heading 3",
          "slug": "Heading-3",
          "size": "28px",
          "fluid": {
            "max": "28px",
            "min": "26px"
          }
        },
        {
          "name": "Heading 4",
          "slug": "Heading-4",
          "size": "24px",
          "fluid": {
            "max": "24px",
            "min": "22px"
          }
        },
        {
          "name": "Heading 5",
          "slug": "Heading-5",
          "size": "20px",
          "fluid": {
            "max": "20px",
            "min": "19px"
          }
        },
        {
          "name": "Heading 6",
          "slug": "Heading-6",
          "size": "18px",
          "fluid": {
            "max": "18px",
            "min": "17px"
          }
        },
        {
          "name": "Paragraph lg",
          "slug": "paragraph-lg",
          "size": "18px",
          "fluid": {
            "max": "18px",
            "min": "17px"
          }
        },
        {
          "name": "Paragraph base",
          "slug": "paragraph-base",
          "size": "16px",
          "fluid": {
            "max": "16px",
            "min": "16px"
          }
        },
        {
          "name": "Paragraph sm",
          "slug": "paragraph-sm",
          "size": "14px",
          "fluid": {
            "max": "14px",
            "min": "14px"
          }
        },
        {
          "name": "Info md",
          "slug": "Info-md",
          "size": "12px",
          "fluid": {
            "max": "12px",
            "min": "12px"
          }
        },
        {
          "name": "Info sm",
          "slug": "Info-sm",
          "size": "10px",
          "fluid": {
            "max": "10px",
            "min": "10px"
          }
        }
      ],
      "fontStyle": true,
      "fontWeight": true,
      "letterSpacing": true,
      "textDecoration": true,
      "textTransform": true
    },
    "useRootPaddingAwareAlignments": true
  },
  "styles": {
    "spacing": {
      "padding": {
        "bottom": "0px",
        "left": "16px",
        "right": "16px",
        "top": "0px"
      }
    }
  },
  "templateParts": [
    {
      "area": "header",
      "name": "header"
    },
    {
      "area": "footer",
      "name": "footer"
    }
  ],
  "version": 2,
  "$schema": "https://schemas.wp.org/trunk/theme.json"
}
``` 

</p>
</details> 

### Screenshots, screen recording, code snippet

| Block styles (as it should be) | Global styles (with additonal font sizes) |
|--------|--------|
| image | image |

### Environment info

- WP 6.2.2
- GB 16.1.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #58753: Default color presets rendering in the Cover block when defaultPalette is false
### Description

Setting `settings.color.defaultPalette` in theme.json should remove the default color palette presets from the Cover block placeholder (as it does in WordPress 6.4.X). 

With Gutenberg active, the default color presets are unexpectedly rendered as choices within the placeholder. 

### Step-by-step reproduction instructions

1. Install and activate the Twenty Twenty Four theme. 
2. Add a page.
3. Add a cover block to the page.
4. See the core presets within the placeholder.

### Screenshots, screen recording, code snippet

In the screenshot below I am showing how the default color presets are disabled for Twenty Twenty Four, as only the theme's color presets are rendering in the Color settings. But the placeholder is not respecting the theme.json, rendering the core presets alongside the theme's: 
 
CleanShot 2024-02-06 at 16 03 48

### Environment info

Does not occur with WordPress 6.4.x, but it does when Gutenberg is active. 

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Revert for #55219.

## Why?

Partially fixes #52200

Closes https://github.com/WordPress/gutenberg/issues/58753

In draft because the code that needs to be reverted is now used in more places, and we need to confirm if it needs to be reverted here or in the specific place that it was changed before. 

## How?

Make the `mergeOrigins` function work like it did before, by just returning the highest priority value instead of flattening them in one array. We may want to do some additional renames like suggested in https://github.com/WordPress/gutenberg/pull/55219#issuecomment-1938169927.

## Testing Instructions

- verify that https://github.com/WordPress/gutenberg/issues/55011 is still fixed.

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

TODO

### CODE REVIEW

**Comment by youknowriad** [comment]
Ok, it seems in the discussion #55219 most people thinking the revert is the way to go for now.

cc @matiasbenedetto how do you feel about it? Do you think this can work for the font library as well? 

Thanks

**Comment by getdave** [comment]
I added https://github.com/WordPress/gutenberg/issues/58753 to the list of Issues that this PR would resolve.

**Review by MaggieCabrera — DISMISSED** [review]
I tested this using the theme.json file in #52200 and the font sizes of the theme were showing correctly. I then added an extra font size using one of the slugs for preset core font sizes and its value was overridden correctly too.

**Comment by MaggieCabrera** [comment]
> I added #58753 to the list of Issues that this PR would resolve.

Can confirm this is fixed too

**Comment by scruffian** [comment]
Onew problem with this PR is the impact it has on Font Family. If I have a theme with 2 active fonts, and then I install a new one using the Font Library, I now lose access to the theme's fonts in the Post Editor.

For example here I am using a theme that has two fonts - Crimson Text and Roboto Mono, and I have installed Aboreto from Google Fonts.

In trunk I see this:
Screenshot 2024-02-13 at 10 33 01

But with this PR I see:
Screenshot 2024-02-13 at 10 33 32

I think the way forward is probably going to be to make an exception for Font Family until we can find a better solution for all cases.

**Comment by getdave** [comment]
@scruffian Good catch. I don't think it's good to have the Theme fonts overriden because a user adds a custom one.

Unless there are objections, let's implement a constant for exceptions whereby we _merge_ instead of override. The only value in the constant would be for font families.

**Comment by t-hamano** [comment]
> Onew problem with this PR is the impact it has on Font Family. If I have a theme with 2 active fonts, and then I install a new one using the Font Library, I now lose access to the theme's fonts in the Post Editor.
> 

Yes, reverting #55219 means reproducing #55011, which #55219 originally wanted to solve. We need to add logic to manually merge font families from each origin, rather than retrieving them from the merged origin.

I'd like to look into it, but if it doesn't seem to be ready in time for WP6.5 Beta1, I might be able to do a follow-up.

**Comment by youknowriad** [comment]
@scruffian @getdave I've restored the behavior for font families but also found that the merge function was used for shadow presets, so I kept this like trunk as well. 

I also removed the two expected functions mergeOrigins and hasMergedOrigins. Both of these functions seemed like early abstraction that are not clear enough. We might want to revisit if/when we unify all the panels.

**Comment by youknowriad** [comment]
I'd appreciate more testing here.

**Review by getdave — COMMENTED** [review]
I see a bug where at a block level we are missing the Theme defined font families as these are not being merged.

This represents a regression of https://github.com/WordPress/gutenberg/issues/55011

https://github.com/WordPress/gutenberg/assets/444434/48d387c0-60f4-484d-afe6-24bd6a548871

**Comment by youknowriad** [comment]
@getdave fixed I think, another round of testing?

**Comment by t-hamano** [comment]
@youknowriad My understanding is that there is no need to split the origin when it comes to **font size**.

https://github.com/WordPress/gutenberg/pull/58951/commits/f1537365d082cddc601c01961f57152891126324#diff-cd3303ad473e0bbfc9d92758c62c8f4295b31a0bb8283a3e4445c38fb73c0f4dR233-R235

**Comment by t-hamano** [comment]
> I see a bug where at a block level we are missing the Theme defined font families as these are not being merged.

Regarding this, I have confirmed that both theme fonts and user-installed fonts are displayed correctly at both block level and global styles.

**Comment by youknowriad** [comment]
@t-hamano For me, since font sizes is within the `__EXPERIMENTAL_PATHS_WITH_MERGE` we need to do the same as font families.

**Comment by youknowriad** [comment]
@t-hamano Is there a way to test the impact on font sizes

**Comment by t-hamano** [comment]
I think we need to test if the things mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/58951#pullrequestreview-1877498256) work properly

**Comment by t-hamano** [comment]
> For me, since font sizes is within the `__EXPERIMENTAL_PATHS_WITH_MERGE` we need to do the same as font families.

That may be true, I'll test it

**Review by getdave — COMMENTED** [review]
✅ The latest changes fix https://github.com/WordPress/gutenberg/issues/55011 so that Font Families are merged.

Screen Shot 2024-02-13 at 11 53 59

**Comment by youknowriad** [comment]
Given that there are still e2e test failures and the tied schedule to beta1. I'm going to play it safe and leave this PR for beta2. WDYT?

**Comment by t-hamano** [comment]
I think it would be better to simply revert #55219 at the Beta1 stage. The font family issue reported in [this comment](https://github.com/WordPress/gutenberg/pull/58951#issuecomment-1941124581) might be worth investigating a little more and fixing for Beta2.

**Comment by getdave** [comment]
> Given that there are still e2e test failures and the tied schedule to beta1. I'm going to play it safe and leave this PR for beta2. WDYT?

It's now very close to when we need to be stable for Beta 1 and there still seems to be a lot of potential for side effects and regressions from this revert. 

I agree with your suggestion. This will have to be a known bug for Beta 1. All the associated Issues are tagged with this PR as the fix and we can inform Release Leads that this PR is a "known quantity".

**Comment by getdave** [comment]
We really need to merge the backports https://github.com/WordPress/gutenberg/pull/58964 now so we've left WP Core `trunk` in a stable state for the Beta 1. It's too close to the line.

**Comment by scruffian** [comment]
I wonder if the problem here is that we are treating all preset the same. Should we merge custom and theme, but override default?

**Comment by youknowriad** [comment]
> I wonder if the problem here is that we are treating all preset the same. Should we merge custom and theme, but override default?

I don't think we should change the behavior of how presets work here. We should just restore how it worked on 6.4.

**Comment by t-hamano** [comment]
I tried updating this PR to backport to Beta2. Make clear decisions about whether to "merge" or "override" origins based on the current expected behavior. Please let me know if this change makes sense.

At least the following should work:

- The font family should be a _merge_ of user fonts and theme fonts (The issue reported in [#55011](https://github.com/WordPress/gutenberg/issues/55011) should not reoccur).
- Regarding font size, the default font size preset should _override_ the theme font size preset (should fix [#55744](https://github.com/WordPress/gutenberg/issues/55744)).
- Regarding spaicing, the default spacing preset should _override_ the theme spacing preset (should fix the problem reported in [this comment](https://github.com/WordPress/gutenberg/issues/55744#issuecomment-1788439020)).
- In the Cover block, the default color preset should not be visible (should fix [#58753](https://github.com/WordPress/gutenberg/issues/58753))

P.S. It seems like a lot of tests are failing, but they don't seem to be related to this PR 🤔

**Comment by matiasbenedetto** [comment]
I just made a quick test around the font families part: currently, both theme and custom fonts are featured as expected in font pickers of site, block, and post editor.

**Comment by getdave** [comment]
If we added test coverage for [the items where we don't wish to see regressions](https://github.com/WordPress/gutenberg/pull/58951#issuecomment-1941667373) this will provide greater confidence when merging this PR.

**Comment by ajlende** [comment]
I spent this morning trying to refactor the code to remove `overridePresets` and simplify things some. The override should, theoretically, already be happening when you `useSettings` if the value is in `PATHS_WITH_OVERRIDE` and you grab the top-level value.

Unfortunately, it seems the `decodeValue` function expects the origins to be split out meaning that you can't decode a `var:preset|font-size-large`, for example. So we're stuck with manually splitting out the origins in `useBlockSettings` (f1537365d082cddc601c01961f57152891126324) and the `overridePresets` in a bunch of places where they don't belong (706b623c7bb13c33ff089386352dc9b9dab1d98b).

I think that's fine for now to mitigate the critical problems we have for beta 2, but we should open a follow-up to clean this up some since it's quite messy and more complicated than it should be.

**Comment by youknowriad** [comment]
I think useBlockSettings, should have the exact same structure as theme.json (so splitted) and it should be the responsibility of the panels/UI to do what they want with the presets. Also the "default" logic is that the presets don't override each other, they're just different presets (theme, user and default) and the user could pick from any. If a customization options don't do that, it's the outlier IMO. Obviously we can have some utilities to help the panels deal with these things but we should be aware of wrong abstractions like we've tried to do before this PR.

Now, this PR seems ready for me, but we need to investigate the failing e2e tests, we may have introduced unwanted bugs.

**Comment by youknowriad** [comment]
`getBlockSettings` should ideally don't do anything at all, just return the keys but there's a backward compatibility aspect there where initially we didn't have "sources" (custom, user, theme), so keys like `color.palette` or `typography.fontFamilies` needed to keep returning the same values we had before introducing the sources. So ideally the `getBlocksSettings` is something that we shouldn't have to touch anymore at all.

**Comment by ajlende** [comment]
Just pushed a rebase with trunk to work off latest changes when debugging tests.

**Comment by ajlende** [comment]
> `getBlockSettings` should ideally don't do anything at all, just return the keys but there's a backward compatibility aspect there where initially we didn't have "sources" (custom, user, theme), so keys like `color.palette` or `typography.fontFamilies` needed to keep returning the same values we had before introducing the sources. So ideally the `getBlocksSettings` is something that we shouldn't have to touch anymore at all.

Works for me. Sounds like we should be deprecating usage of `getBlockSettings` for any of the `__EXPERIMENTAL_PATHS_WITH_OVERRIDE` then. We have `getBlockSettings` that merges origins, `useBlockSettings` that bypasses merging those origins, and various panels that want to merge them again. It's causing a lot of confusion for folks writing and reviewing code in this part of the codebase.

**Comment by ajlende** [comment]
Looks like the rebase fixed the tests.

**Review by scruffian — APPROVED** [review]
This is testing well for me.

**Comment by t-hamano** [comment]
I made the comment more clear via c5f9252. I would appreciate it if you could confirm whether my understanding is correct.

**Review by andrewserong — APPROVED** [review]
This is testing well for me, too, and I like how straightforward the code change looks, too 👍

> In the Cover block, the default color preset should not be visible (should fix https://github.com/WordPress/gutenberg/issues/58753)

Just confirming that this fixes that issue. One issue that was present prior to #55219 is that if a user sets a custom color, then the Cover placeholder will override theme colors in its color picker, instead of providing a combined list of theme + custom colors, which the PR in https://github.com/WordPress/gutenberg/pull/58869 would have allowed. That's not a blocker at all for this PR, though, as the behaviour here is what was in WP 6.4. Assuming this PR lands, I'm happy to do a reworked version of #58869 that looks into combining those palette buttons for theme + custom, but I imagine that'd be a fix for 6.6 as it's more "improvement" territory than a bug fix.

| If a custom color is set, it overrides the placeholder's palette buttons | If no custom color is set, the theme's palette is used |
| --- | --- |
| image | image |

LGTM! ✨

**Comment by andrewserong** [comment]
> I made the comment more clear via https://github.com/WordPress/gutenberg/commit/c5f9252d8a061d59c3b65845546e6689e34db4fd. I would appreciate it if you could confirm whether my understanding is correct.

That reads nicely to me, @t-hamano!

**Comment by t-hamano** [comment]
Thank you everyone for your feedback! I think there is no problem with merging this PR, but I would like to wait for @getdave and @youknowriad to confirm it again.

**Comment by MaggieCabrera** [comment]
If we bring this in today, should it be backported to 17.7?

**Comment by youknowriad** [comment]
No problem for me, but I do see related e2e test failures, anyone looked at these?

**Comment by youknowriad** [comment]
@MaggieCabrera Let's keep 17.7 equivalent to beta1 (shipped yesterday) for clarity. So let's keep this PR for next Gutenberg releases.

**Comment by t-hamano** [comment]
The test passed, but the e2e test regarding the navigation menu seems to be unstable. Based on [the logs](https://github.com/WordPress/gutenberg/actions/runs/7895281006/job/21556552498?pr=58951) and the failure-artifacts, this instability might be related to #58987.

**Comment by youknowriad** [comment]
Ok Let's ship it then. Thanks folks, we might want to follow-up with some e2e tests for these flows to avoid regressions later.

**Comment by getdave** [comment]
Great to see this land. Thanks for everyone's work here.

> Thanks folks, we might want to follow-up with some e2e tests for these flows to avoid regressions later.

I do think this aspect is important.

**Comment by matiasbenedetto** [comment]
I think this PR is causing a regression. I'm unable to open the typography panel. The editor breaks. I'm getting this running Gutenberg trunk:

```
TypeError: overriddenFontSizes is undefined
    getUniqueFontSizesBySlug typography-panel.js:111
    TypographyPanel typography-panel.js:192
    of react-dom.min.js:109
....
```
    
Screenshot from 2024-02-15 14-32-11

**Comment by scruffian** [comment]
@matiasbenedetto do you have reproduction steps? It's working for me :)

**Comment by matiasbenedetto** [comment]
> @matiasbenedetto do you have reproduction steps? It's working for me :)

Yes, use 'empty' theme and follow the video steps.

This little PR should solve it.
https://github.com/WordPress/gutenberg/pull/59101

https://github.com/WordPress/gutenberg/assets/1310626/7321b456-ad04-489f-bc36-3f834728032e

**Comment by matiasbenedetto** [comment]
The same logical error repeats in shadows, too. I'll add the fix in https://github.com/WordPress/gutenberg/pull/59101

**Comment by youknowriad** [comment]
@t-hamano I see that you restored the two exported functions "overrideOriginals" and "hasOrigin". I had explicitly removed these. See this comment https://github.com/WordPress/gutenberg/pull/58951#issuecomment-1941236724 because IMO, these are bad factorizations. It gives the impression that all the customization tools should work that way but it shouldn't, I prefer to avoid the indirection here personally. 

Any particular reason for having these functions?

**Comment by t-hamano** [comment]
@youknowriad As mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/58951#issuecomment-1941667373), I thought it was necessary to clearly indicate "merge" and "override" at this time, so I restored the function. Instead, I made the comments more detailed to communicate what the function does to help with refactoring in the future.

https://github.com/WordPress/gutenberg/blob/0e899f76951edd6e4b8ec9cc5d8260b3b7bba0ed/packages/block-editor/src/store/get-block-settings.js#L114-L121

https://github.com/WordPress/gutenberg/blob/0e899f76951edd6e4b8ec9cc5d8260b3b7bba0ed/packages/blocks/src/api/constants.js#L274-L277

**Comment by youknowriad** [comment]
@t-hamano So it's not that important but for me there are two things here:

 `__EXPERIMENTAL_PATHS_WITH_OVERRIDE ` is just here to support backward compatibility for `useSetting` hook. If we could remove it/deprecate it, I'd do it. Which means for me that we shouldn't give this behavior too much "visibility"/"importance" in our code base. Exposing that behavior gives is importance and people mike think that they should do the same for future presets.

The other thing is that `get-block-settings.js` is not the right file to export utilities or expose them to be used in UI components. In fact, I believe it's clearer for maintainability to just have the logic (which is very small) collocated in the UI components directly, you don't have to understand an external function, you can just the small code inline.

**Comment by t-hamano** [comment]
I see. I would like to submit a PR for refactoring, should we backport it to WP6.5? There should be no problem if we refactor correctly, but I'm a little concerned that it might introduce new regressions to WP6.5.

**Comment by youknowriad** [comment]
@t-hamano A PR that we don't backport is fine too :)

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-beta-2 branch to get it included in the next release: f2a53235b9

**Comment by creativecoder** [comment]
Note that as part of curating the Gutenberg 17.8 changelog, I added the label [Global Styles](https://github.com/WordPress/gutenberg/labels/Global%20Styles) to this PR to better categorize it.

Please let me know if there is a different label that would be a better fit.

**Pull request merged**
