### PR TITLE
[RNMobile] Add OfflineStatus component

### LINKED ISSUE #6405: Introduce a visual indicator to inform users when the editor is in an offline state
Image

### PR DESCRIPTION
**Pull request by derekblank**
## What?
Adds a mobile component to display a visual indicator when working offline within the mobile editor. (Note: the functionality to subscribe to network status is handled in https://github.com/WordPress/gutenberg/pull/56861.)

See related discussions in a [previous attempt](https://github.com/WordPress/gutenberg/pull/56848).

## Why?
Overall, to improve the user's experience when uploading media. 

Addresses:
* https://github.com/wordpress-mobile/gutenberg-mobile/issues/6405

## How?
Adds OfflineStatus component and associated icon/style files. 

## Testing Instructions
The component is included in block-list behind a dev flag. To test this PR, build the app locally and turn on Airplane Mode while using the editor.

<details><summary>Test Diff</summary>

```diff
diff --git a/packages/block-editor/src/components/block-list/index.native.js b/packages/block-editor/src/components/block-list/index.native.js
index 810e23e4c1..19540eddb4 100644
--- a/packages/block-editor/src/components/block-list/index.native.js
+++ b/packages/block-editor/src/components/block-list/index.native.js
@@ -28,6 +28,7 @@ import {
 	DEFAULT_BLOCK_LIST_CONTEXT,
 } from './block-list-context';
 import { BlockDraggableWrapper } from '../block-draggable';
+import OfflineStatus from '../offline-status';
 import { useEditorWrapperStyles } from '../../hooks/use-editor-wrapper-styles';
 import { store as blockEditorStore } from '../../store';
 
@@ -235,6 +236,7 @@ export default function BlockList( {
 			onLayout={ onLayout }
 			testID="block-list-wrapper"
 		>
+			<OfflineStatus />
 			{ isRootList ? (
 				<BlockListProvider
 					value={ {
```

</details>

## Screenshots or screencast 
Light | Dark
-|-
 |

### CODE REVIEW

**Comment by derekblank** [comment]
@dcalhoun This PR updates the offline icon provided by the design team, which appears to resolve the vertical centering issue [mentioned here](https://github.com/WordPress/gutenberg/pull/56848#pullrequestreview-1770086787).

**Comment by derekblank** [comment]
In an attempt to further debug the Android dark/light mode issue [mentioned here](https://github.com/WordPress/gutenberg/pull/56848#issuecomment-1846474465), I compared against the Paywall block [dark/light color implementation](https://github.com/Automattic/jetpack/blob/2da159e318f306b794d75191fb3d36206882c998/projects/plugins/jetpack/extensions/blocks/paywall/edit.native.js#L8-L20), which are identical to the colors and hooks used in the OfflineStatus component. I noted that this issue also affects the Paywall block in the same way. See example video:

<details><summary>Paywall Block Video Example</summary>

<video src="https://github.com/WordPress/gutenberg/assets/643285/3e168095-5725-4ffe-a2a0-4f02a96ff20e" />

</details>

For both, we will likely need to implement a solution to accomodate theme styles like was done on [RichText placeholderTextColor](https://github.com/WordPress/gutenberg/blob/2642697ff65f6f011044f8939f9f7ed70af2945c/packages/block-editor/src/components/rich-text/native/index.native.js#L1066-L1099).

**Review by dcalhoun — COMMENTED** [review]
> In an attempt to further debug the Android dark/light mode issue [mentioned here](https://github.com/WordPress/gutenberg/pull/56848#issuecomment-1846474465), I compared against the Paywall block [dark/light color implementation](https://github.com/Automattic/jetpack/blob/2da159e318f306b794d75191fb3d36206882c998/projects/plugins/jetpack/extensions/blocks/paywall/edit.native.js#L8-L20), which are identical to the colors and hooks used in the OfflineStatus component. I noted that this issue also affects the Paywall block in the same way. 

I debugged further. This issue appears to be that the [color values](https://github.com/WordPress/gutenberg/blob/c0b18b08cb32aa3c766f7ea4a872544cca310506/packages/base-styles/_colors.native.scss#L88-L102) used in both `OfflineStatus` and the aforementioned block are based upon opacity, specifically **8-digit** [hexadecimal colors](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color). 

> For both, we will likely need to implement a solution to accomodate theme styles like was done on [RichText placeholderTextColor](https://github.com/WordPress/gutenberg/blob/2642697ff65f6f011044f8939f9f7ed70af2945c/packages/block-editor/src/components/rich-text/native/index.native.js#L1066-L1099).

From my perspective, the illegible text means we should not use these opacity-based colors for anything that is displayed atop the editor canvas, whose background color we cannot predict due to the current WYSIWYG feature driven by theme colors. I do not think we need to implement JavaScript logic to accommodate theme styles. WDYT?

**Comment by derekblank** [comment]
> This issue appears to be that the [color values](https://github.com/WordPress/gutenberg/blob/c0b18b08cb32aa3c766f7ea4a872544cca310506/packages/base-styles/_colors.native.scss#L88-L102) used in both OfflineStatus and the aforementioned block are based upon opacity, specifically 8-digit [hexadecimal colors](https://developer.mozilla.org/en-US/docs/Web/CSS/hex-color).

I did have a thought that it could possibly be related to the hexadecimal alpha values, but hadn't made it there debugging yet. From preliminary testing, using six-digit hex values should resolve the issue. I'll update, and thanks for testing. 👍

**Review by dcalhoun — APPROVED** [review]
I retested the styles atop dark editor backgrounds, they are now far more legible. Additionally, I pushed a small import path fix to resolve a Jest test module resolution error. 

I believe this is ready to merge and is hidden behind a `__DEV__` flag while we work to finish related user-facing features. 🚀

**Pull request merged**
