### PR TITLE
Enable flaky tests reporter bot in PRs

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Continued from https://github.com/WordPress/gutenberg/pull/34432. The bot has been enabled for a week now and is pretty stable on trunk. I think it makes sense to enable it on all PRs to unblock contributors from flaky e2e tests.

You can view all the [issues](https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22%5BType%5D+Flaky+Test%22+) the bot has created.

## How has this been tested?

No way to test it for now. We just have to be sure that the bot won't run arbitrary code from all PRs opened in this repo for security reasons.

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
One concern I have is that a PR can be significantly behind `trunk` and still be running flaky tests that have been solved in `trunk`. Any thoughts on that @kevin940726?

Maybe it'd be worth investing time into making sure tests always run on the latest code in `trunk`. I never really understood why they don't do that.

**Review by noisysocks — APPROVED** [review]
@talldan's comment aside, the code looks good 👍

**Comment by kevin940726** [comment]
> Maybe it'd be worth investing time into making sure tests always run on the latest code in trunk. I never really understood why they don't do that.

Good question! I don't really know either, but I'd imagine it's the other way around. I'll do some research.

**Comment by kevin940726** [comment]
Okay I did some research.

The `pull_request` event our e2e workflow is running on will run on the **merge commit** of that PR to the latest base branch. `GITHUB_REF` will look something like `refs/pull/:prNumber/merge`, and `GITHUB_SHA` is the latest commit of `GITHUB_REF`, that's why `GITHUB_SHA` is not the same as the latest commit of the PR. Github will automatically do a merge on their side and use the latest merge commit to run our tests. As for branches with merge conflicts, GH simply won't trigger the `pull_request` event ([ref](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request)).

> Maybe it'd be worth investing time into making sure tests always run on the latest code in trunk. I never really understood why they don't do that.

So I think it's the other way around. GH will always run on the latest code on trunk.

**Comment by kevin940726** [comment]
I also added a note in the testing documentation. Please help review it if you think it needs more clarity :).

**Comment by noisysocks** [comment]
Thanks for checking that. I say let's try it :shipit:

**Comment by talldan** [comment]
> So I think it's the other way around. GH will always run on the latest code on trunk.

I'm not completely confident about that, because regularly I've seen the advice to 'rebase a PR' when a test has been fixed in `trunk` and have observed that happening, even had it happen in my own PRs. If the tests already run based on code merged with the `trunk` that wouldn't be needed.

**Comment by kevin940726** [comment]
> I'm not completely confident about that, because regularly I've seen the advice to 'rebase a PR' when a test has been fixed in `trunk` and have observed that happening, even had it happen in my own PRs. If the tests already run based on code merged with the `trunk` that wouldn't be needed.

It just happened to one of my PR and I think I know why. It's because rebasing a PR is the easiest way to re-trigger the workflow. If we only re-run the workflow, the commit will still be the outdated merged commit that never pass, we have to re-trigger the `pull_request` event. The easiest way to re-trigger the event is to rebase it onto the latest trunk, which will have the updated merge commit. Does that make sense?

I guess we could try creating the merge commit on our end using `@actions/checkout` if necessary. Not sure if it's worth it though 🤔. Probably need to get back to this in the future if needed.

**Comment by talldan** [comment]
> It just happened to one of my PR and I think I know why. It's because rebasing a PR is the easiest way to re-trigger the workflow. If we only re-run the workflow, the commit will still be the outdated merged commit that never pass, we have to re-trigger the pull_request event. The easiest way to re-trigger the event is to rebase it onto the latest trunk, which will have the updated merge commit. Does that make sense?

Right, I see. So technically if an empty commit is pushed, that will make the workflow use the latest merge ref?

**Comment by kevin940726** [comment]
> So technically if an empty commit is pushed, that will make the workflow use the latest merge ref?

I think so, but I haven't tested it 😅.

**Pull request merged**
