### PR TITLE
Remove the site editor sidebar navigation edit button

### PR DESCRIPTION
**Pull request by draganescu**
## What?

The site editor navigation section lists all available navigations. Focusing on one exposes an edit button which opens the focused navigation edit mode. Let's remove this button.

## Why?

Editing navigation in isolation never amounted to much and that button creates the illusion that the navigation is not editable in place already. Since we have some discoverability issues around editing menus using the navigation block we don't want any more confusion on top.

## How?

Just removed the button.

## Testing Instructions

1. Make sure to have some navigations created
2. Go to the site editor > navigation
3. Select a navigation
4. **Notice in the up right side of the sidebar there is no edit button**

### Before

Screenshot 2024-02-24 at 12 24 12

### After

Screenshot 2024-02-24 at 12 22 50

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
I'm cool with this on the proviso that we fully remove the Nav Focus Mode screen entirely in a close follow up.

Why? Because just removing the "Edit" button means the screen is only accessible to sighted users which isn't great.

**Comment by draganescu** [comment]
@getdave yes, #59340 solves this. I would hold off in cleaning up the code for any wp_navigation exceptions yet. For now we just remove this useless feature from being accessed.

**Review by richtabor — APPROVED** [review]
Looks good. If we revisit this view we can explore adding it back.

**Review by richtabor — APPROVED** [review]
This makes sense to me. Once we identify what the navigation view in the canvas can benefit, we can revisit this.

**Comment by Mamaduka** [comment]
@afercia created a somewhat related PR - #59282.

**Pull request merged**
