### PR TITLE
Update re-resizable dependency

### LINKED ISSUE #16950: Fix deprecated componentWillReceiveProps lifecycle method usage in ResizableBox component
**Describe the bug**
The [`ResizableBox`](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/resizable-box) component in `@wordpress/components` is throwing a React Strict warning when it is implemented:

<details>
<summary>Console Error</summary>
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in StrictMode (created by Editor)
    in Editor
    in Unknown (created by WithSelect(Editor))
    in WithSelect(Editor)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Resizable
</details>

I traced the warning all the way to the implementation of the re-resizable package:

https://github.com/bokuweb/re-resizable/blob/7ea154470567735149d5e3827cc9fb856f8e8f68/src/index.tsx#L463-L465

Unfortunately, this package does not have a newer release fixing the issue (GB is using the latest version), so I've opened an issue in their repository: https://github.com/bokuweb/re-resizable/issues/504.  There's some uncertainty on how active that package is so we'll have to see what happens.

### PR DESCRIPTION
**Pull request by swissspidy**
## Description

Fixes #16950 after the upstream library was updated.

## How has this been tested?

Not tested yet.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by nerrad** [comment]
If this gets tested and merged before I get a chance to do that (which will be absolutely okay if that happens 😄 ) we should let the author of the package know it fixed things for us too: https://github.com/bokuweb/re-resizable/issues/504

**Comment by gziolo** [comment]
I think we should include a note in the changelog of `@wordpress/components` package. Some similar entries can be found in:
https://github.com/WordPress/gutenberg/blob/master/packages/scripts/CHANGELOG.md

> The bundled eslint dependency has been updated from requiring ^5.16.0 to requiring ^6.1.0.

**Comment by swissspidy** [comment]
> I think we should include a note in the changelog of `@wordpress/components` package.

Done!

**Review by nerrad — APPROVED** [review]
I've confirmed this fixes the error and components using resizable are working as expected.  Thanks for getting this updated @swissspidy !

**Pull request merged**
