### PR TITLE
Fix missing selected block highlighting in list view

### LINKED ISSUE #24520: block navigation no longer highlights currently selected block
The block navigation is not highlighting the block that the cursor is currently in

**To reproduce**
Click on a block
Click on the 'Block Navigation'
It has the top block highlighted not the block the cursor is currently in

**Expected behavior**
It should highlight the block that the cursor is currently in

**Editor version (please complete the following information):**
- WordPress version: 5.5
Default Gutenberg
Theme: twentytwenty
NO plugins

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Chrome
 - Version 84.0.4147.105 

**Screenshots**
block-navigation

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #24520

#22996 accidentally removed the styles for selected blocks in list view. As mentioned in the PR description, this wasn't intended to have any effect on the post editor, only the experimental navigation editor screen.

I've added those styles back and also added some styles for the navigation screen that remove the highlight only on that screen.

### Post editor
1. Add some blocks
2. Select a block
3. Open List View
4. The selected block should be highlighted

### Nav Screen
1. Open the experimental navigation screen
2. Add some blocks
3. The selected block isn't highlighted

### Post editor
Screenshot 2020-08-18 at 12 53 27 pm

### Nav Screen
Screenshot 2020-08-18 at 12 54 22 pm

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ntsekouras** [comment]
Should this highlight the block that the cursor is currently in? If yes, it's not doing it when tested. - Chrome

**Comment by talldan** [comment]
@ntsekouras Thanks for testing. Yep, the icon for the block should display with a black background. Maybe the style is too subtle:
Screenshot 2020-08-18 at 5 26 00 pm

It's also a little easy to confuse with the blue border, which is the focus ring.

**Comment by ntsekouras** [comment]
> It's also a little easy to confuse with the blue border, which is the focus ring.

Yes. I had in mind to look for focus ring :) 

> Maybe the style is too subtle

IMO it might be yes, especially with black/white only contrast. You might miss that and think a selected icon is the actual icon. But this might be for another follow up issue/discussion.

**Review by ntsekouras — APPROVED** [review]
Thanks 👍 !

**Comment by talldan** [comment]
Thanks @ntsekouras, I made a new issue about the design:
Screenshot 2020-08-18 at 12 53 27 pm

**Pull request merged**
