### PR TITLE
Raw handling: fix pasting special spaces

### LINKED ISSUE #15649: Paste handler strips white space characters
It seems that special characters are stripped from the paragraph block. For example, if you try to paste a thin space (`&#8201;`) nothing appears. 

**To reproduce**
1. Go here and copy a thin space character: http://www.elizabethcastro.com/html/extras/entities.html#punct
2. Try to paste the thin space in a paragraph block in Gutenberg editor.

**Expected behavior**
The thin space would appear in the editor as well as render on the website page.

**Local env.**
- MacOS Sierra 10.12.6
- Chrome 74.0.3729.131 (Official Build) (64-bit)
- WordPress 5.2

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #15649.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by noisysocks** [comment]
I followed the steps in https://github.com/WordPress/gutenberg/issues/15649#issuecomment-635111760 and am still seeing the issue where pasting a thin space into the editor does nothing.

**Comment by ellatrix** [comment]
@noisysocks Could you share what's logged in the console after pasting the thin space in Gutenberg?

**Comment by noisysocks** [comment]
I get this:

```
Received HTML:

 <empty string>

Received plain text:

  

Processed inline HTML:

 <empty string>
```

I confirmed that there's a thin space in there by copy and pasting some of the output to `console.txt` and running:

```
Desktop % xxd -b console.txt
00000000: 01010010 01100101 01100011 01100101 01101001 01110110  Receiv
00000006: 01100101 01100100 00100000 01110000 01101100 01100001  ed pla
0000000c: 01101001 01101110 00100000 01110100 01100101 01111000  in tex
00000012: 01110100 00111010 00001010 00001010 00100000 11100010  t:.. .
00000018: 10000000 10001001
```

The last 3 bytes there are the UTF-8 encoding of a thin space (U+2009).

**Comment by ellatrix** [comment]
Ok, so your thin space is in plain text?

**Comment by ellatrix** [comment]
@noisysocks Thanks, that was helpful. The markdown converter is stripping that whitespace, so I made it skip if the plain text is just whitespace.

**Review by noisysocks — APPROVED** [review]
Fixed! 🎉

**Pull request merged**
