### PR TITLE
Patterns Explorer: Makes the pagination items horizontally stacked on larger screens only

### LINKED ISSUE #61754: Patterns Explorer: Improve pagination layout when 'Show button text labels' preference is enabled
### Description

When the preference 'Show button text labels' is eneabled, the Patterns Explorer pagination items are stacked vertically because of a CSS `flex-direction: column;`. Screenshot:

Screenshot 2024-05-17 at 09 34 45

Not sure this is ideal. 

I'm not sure what the reasoning behind this layout was. It appears to be [new CSS](https://github.com/WordPress/gutenberg/blob/2e439917b871eac2219b90c176ff4618c6e0852a/packages/block-editor/src/components/block-patterns-paging/style.scss#L26-L31) introduced in https://github.com/WordPress/gutenberg/pull/53835 and seems intentional.

While on small screns laying out these items vertically would make sense, on large screens there is space to lay out them horizontally, no differently from their layout when 'Show button text labels` is disabled. Screenshot:

Screenshot 2024-05-17 at 09 42 17

I'd like to propose to stack them vertically only udner a certain viewport width.

### Step-by-step reproduction instructions

- Go to the post editor > Options > Preferences > Accessibility
- Enable the 'Show button text labels' preference.
- CLose the preferences modal dialog and open the main inserter > Patterns
- Click 'Explore all patterns'
- Sctoll the modal dialog at the bottom.
- Observe the pagination items are unexpectedly stacked vertically.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by amitraj2203**
## What?
Fixes: #61754

## Why?
The current vertical stacking of pagination items in the Patterns Explorer doesn't make optimal use of available screen space. To address this, pagination items will now stack vertically only when the viewport is below 960px width. Beyond that, they will be horizontally aligned for better visibility.

## How?
This PR adds a media query to change the flex-direction.

## Testing Instructions
1. Go to the post editor > Options > Preferences > Accessibility
2. Enable the 'Show button text labels' preference.
3. Close the preferences modal dialog and open the main inserter > Patterns
4. Click 'Explore all patterns'
5. Scroll the modal dialog at the bottom.
6. Observe the pagination items.

## Screenshots or screencast 
https://github.com/WordPress/gutenberg/assets/77401999/48a2fed0-8f06-49b0-ac94-116db3a62468

### CODE REVIEW

**Comment by amitraj2203** [comment]
Additionally, I noticed that the same styles for pagination items are also being applied when we go to:
1. Go to the post editor > Options > Preferences > Accessibility
2. Enable the 'Show button text labels' preference.
3. Close the preferences modal dialog and open the main inserter > Patterns
4. Click 'All'
5. Scroll the subsection to the bottom.

image

---

So I have added separate styles for this part which will keep these items vertically stacked at all viewports but for the modal one, the items will be stacked as per the viewport.

image

**Comment by amitraj2203** [comment]
@WordPress/gutenberg-components Can you please review it.

**Review by afercia — APPROVED** [review]
> Additionally, I noticed that the same styles for pagination items are also being applied when we go to: [...] All

Oh, thanks for pointing it out. That's likely the reason why the vertical stacking was added as the patterns list is in a very narrow column. It should not apply to the pagination in the Patterns explorer modal dialog though.

The CSS changes look good to me 👍🏽 
Could you please rebase on top of latest trunk? Thanks!

**Comment by amitraj2203** [comment]
@afercia I have rebased it.

**Comment by afercia** [comment]
Thanks @amitraj2203

**Pull request merged**
