### PR TITLE
Core Data: Fix ESLint warnings for the hooks directory

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
PR fixes ESLint warning for Code Data hooks.

## Why?
Ideally, the project should not have any ESLint errors and warnings.

## How?
```
npm run lint:js -- packages/core-data/src/hooks --fix
```

## Testing Instructions
Running following lint command should return warnings

```
npm run lint:js -- packages/core-data/src/hooks
```

## Screenshots or screencast 

CleanShot 2023-02-07 at 10 13 22

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Thank you for the fix.

Would it be a good idea to promote this warning to an error? People fix those warnings anyway, so why not enforce that on PR authors?

**Comment by Mamaduka** [comment]
That makes sense and will match PHPCS standards.

You'll have to commit extra changes when working in the files with warnings. I think most of us have "format on save" enabled in the editors.

We can fix the remaining warning in a single go and add the commit to the `.git-blame-ignore-revs`.

**Comment by gziolo** [comment]
> You'll have to commit extra changes when working in the files with warnings. I think most of us have "format on save" enabled in the editors.

I think it requires running `npm run lint -- --fix` (plus the name of the rule that signals violations) because Prettier doesn't format code comments.

**Comment by Mamaduka** [comment]
The ESLint extensions does, at least in VSCode.

**Comment by tyxla** [comment]
As initially brought up by @gziolo I'm suggesting that we change the `jsdoc/check-line-alignment` to `error` in #47878.

**Pull request merged**
