### PR TITLE
Try: Remove dashed outlines for child and parent blocks.

### PR DESCRIPTION
**Pull request by jasmussen**
This PR reverts past efforts by myself and Kjell to make parent/child block interactions easier. This is not because that effort was not necessary, it is more necessary than ever, but it was because it did not work as well as we had intended. In actual practice the added padding and dashed outlines added confusion and additional UI complexity, where it was meant to do the opposite.

Instead, there is an incoming breadcrumbs toolbar intended to alleviate the same problem. Tracked here: https://github.com/WordPress/gutenberg/issues/17089, I would encourage you test the PR here: https://github.com/WordPress/gutenberg/pull/17838. With this breadcrumb toolbar present, the current state of what you're editing becomes visible in a more more clear (text indication) way, with consistent buttons (breadcrumbes) to select parent blocks, without hunting pixels.

Additional efforts such as those being explored in https://github.com/WordPress/gutenberg/issues/17088 can help as well.

Before:

before

After:

after

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
I'm not a fan of this. I think the dashed outlines are still helpful even with the breadcrumb bar added, since they give a general sense of not just the immediate hierarchy, but also siblings at the same level. Here's an example of what I mean:

image

It's clear how many levels of nesting I'm at and which blocks are in the same column/columns/group. You lose this useful visual information if you only have the breadcrumb bar.

**Comment by youknowriad** [comment]
With the new Breadcrumb and the select tool merged, I think this makes a lot of sense. The layout is closer to the frontend this way and there's no feeling of jumpiness when you navigate your post.

**Review by youknowriad — APPROVED** [review]

**Comment by ZebulanStanphill** [comment]
With the introduction of the select tool, my opinion has changed. I no longer oppose this change. I think that the combination of the select tool, the breadcrumb bar, and the Block navigation menu are enough to traverse nested blocks without having to add padding to InnerBlocks areas, especially considering future improvements such as the ones proposed in #18014 and #18132.

**Review by ZebulanStanphill — APPROVED** [review]

**Comment by jasmussen** [comment]
Thanks for the reviews.

I believe along with the arguments laid out, some improvements to hover styles and tweaks to navigation/selection mode, this will feel even more appropriate, and it removes a great deal of CSS written to just target a few blocks.

Rebased and will merge if the checks pass.

**Pull request merged**
