### PR TITLE
1.9.1 version bump

### PR DESCRIPTION
**Pull request by hiddenpearls**
It is showing me an update to 1.9.1 as We have already released 1.9.1 to wordpress.org

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ntwb** [comment]
@aduth As you packaged up 1.9.1 and wrote the comment on #3979, should this be merged and a 1.9.2 release created?

**Comment by aduth** [comment]
I'm not sure a release is warranted just to avoid the upgrade prompt when running master. My hesitance to bump the version was that the history won't truly reflect the point at which the upgrade occurred (since the release was cherry-picked). That said, maybe it doesn't matter and we could go ahead and merge?

**Comment by ntwb** [comment]
I believe a full release was on the cards for this week, if so merge this, then bump _all the things_ for a 1.9.2 or 2.0.0 release maybe

**Comment by gziolo** [comment]
We are on 2.x version. Closing this one as it is no longer relevant. Thanks for opening this PR, we should merge this way sooner :(

**Pull request closed without merging**
