### PR TITLE
Remove duplicate question in FAQ

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Remove duplicate `What are “blocks” and why are we using them?` question in FAQ.

Kept recently updated answer from @annezazu.

### CODE REVIEW

**Comment by mcsf** [comment]
What is it a duplicate of? Can you point to that material?

**Review by Soean — APPROVED** [review]
The new version is in line 49

**Comment by annezazu** [comment]
Whoops. Thank you for this update :)

**Comment by mcsf** [comment]
> The new version is in line 49

Something dumb must have happened in my diff reading :)

**Pull request merged**
