### PR TITLE
Fix/block toolbars with preview

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fix rendering of block toolbars with responsive preview by always fixing them to top on Tablet and Mobile previews.

## How has this been tested?

Browser tested only.

## Screenshots 

Screen Shot 2020-02-21 at 2 34 41 pm

Screen Shot 2020-02-21 at 2 44 55 pm

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for your help on this @tellthemachines we're almost there

Something is off in the style of the top toolbr for mobile/table previews

Capture d’écran 2020-02-21 à 8 16 43 AM

I believe that's most likely because some styling that are meant for contextual toolbars are bleeding to the top toolbar in these previews. The mix might be just moving some styles around.

**Comment by tellthemachines** [comment]
> Something is off in the style of the top toolbr for mobile/table previews

Should be fixed now!

**Comment by youknowriad** [comment]
Thanks, it's better

Capture d’écran 2020-02-24 à 9 23 59 AM

I still see the black borders though, Maybe some wrong CSS. selector not targetting the contextual toolbar. specifically? cc @jasmussen

**Comment by jasmussen** [comment]
Interesting, the off-borders only happen when the "Top Toolbar" option is not toggled. When it is, they look correct:

Screenshot 2020-02-24 at 09 30 46

In other words, the difference is a classname:

gif

So, to the div that has the following classnames: 

`edit-post-layout is-mode-visual block-editor-editor-skeleton`

... if you add this, it works:

`edit-post-layout is-mode-visual block-editor-editor-skeleton has-fixed-toolbar`

**Review by youknowriad — COMMENTED** [review]
@tellthemachines While checking this PR, I was wondering something, why the "block-editor" package has to know about the "previewDeviceType" at all? Why it's not just an "edit-post" or "editor" thing?

(That's not something for this PR obviously)

Edit: follow-up here https://github.com/WordPress/gutenberg/pull/20409

**Comment by youknowriad** [comment]
@jasmussen while this class would have fixed it, I don't think it was the right fix. Instead, I updated the block-toolbar styles so that the "contextual" style override the default lighter borders instead of the opposite.

**Review by youknowriad — APPROVED** [review]

**Comment by jasmussen** [comment]
There used to be a separator:

Screenshot 2020-02-24 at 10 05 57

And there's an issue when you _don't_ have the top toolbar option enabled, where the smart mover thing does its autohide stuff.

**Comment by youknowriad** [comment]
Good catch, these should be fixed now.

**Comment by jasmussen** [comment]
💪

**Pull request merged**
