### PR TITLE
Lowered specificity of alignment rules for support layout so wide alignments work.

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

https://github.com/WordPress/gutenberg/pull/38613 introduced a bug where wide alignments max-width rules where less specific than the new ones introduced for general alignments. This PR reduced the specificity of the new rule so wide alignments work again.

Props to @jasmussen for [the code](https://github.com/WordPress/gutenberg/pull/38613#discussion_r810935084)

## Testing Instructions

Test on a block theme that wide alignments have the correct max-width

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, and thanks for the incredibly fast PR! I'd like to test more, but this appears to be working on the frontend:
frontend

I'm not seeing it working in the editor:
Screenshot 2022-02-21 at 11 52 47

Are there two instances of these rules that need to be updated? I'm seeing this code in the inspector for the editor:

Screenshot 2022-02-21 at 11 53 04

When I update that to use the new `:where` wrapper, it works in the editor too. I'm having some build issues at the moment so it's possible this is on my end.

**Comment by MaggieCabrera** [comment]
> I'm not seeing it working in the editor

You are right, I missed that, good catch! Should work now

**Review by jasmussen — APPROVED** [review]
The original div removal change is important, and in the name of responding quickly to these side-effects, I think we should land it. It works well for fullwide, wide, floated, and content widths in editor and frontend:

Screenshot 2022-02-21 at 12 00 37
Screenshot 2022-02-21 at 12 00 26

_Note that the fullwide not being fullwide in the editor, as best I can tell, is a padding issue with TT2, one which requires a bit more of a holistic solution we didn't get to in time for 5.9._

Also, to the best of my reading of the `:where` selector, this is what it was designed for, and it helps lower the specificity instead of raise, which should only make this safer than it was before. 

I would love more testing and sanity checks, CC: @jffng if you have time, since you reported the original issue. But I'd be happy to land this soon so we can see if there are additional issues.

**Comment by jffng** [comment]
> It works well for fullwide, wide, floated, and content widths in editor and frontend

+1.

Tested across a variety of block themes and this change restores the correct alignment and preserves the intention of the original PR, thank you both!

**Pull request merged**
