### PR TITLE
Fix: Embed Block: Match HTML in the editor and frontend

### LINKED ISSUE #65179: Embed Block: Match HTML in the editor and frontend
Discovered while reviewing #64970

## What problem does this address?

In #64970, the `figcaption` element was moved into the `figure` element in the editor. However, the HTML in the frontend and editor do not match completely.

Editor:

```html
<div tabindex="0" class="block-editor-block-list__block wp-block is-selected wp-embed-aspect-16-9 wp-has-aspect-ratio wp-block-embed" id="block-87cbd5e9-5d49-47a8-9085-b7e6a72d8c58" role="document" aria-label="Block: YouTube Embed" data-block="87cbd5e9-5d49-47a8-9085-b7e6a72d8c58" data-type="core/embed" data-title="YouTube Embed">
  <figure class="wp-embed-aspect-16-9 wp-has-aspect-ratio wp-block-embed is-type-video">
    <div class="wp-block-embed__wrapper">
      <iframe title="Embedded content from youtu.be" class="components-sandbox" sandbox="allow-scripts allow-same-origin allow-presentation" width="620" height="349"></iframe>
    </div>
    <figcaption role="textbox" aria-multiline="true" aria-label="Embed caption text" aria-readonly="false" class="block-editor-rich-text__editable wp-element-caption rich-text" contenteditable="true" data-wp-block-attribute-key="caption" style="white-space: pre-wrap; min-width: 1px;">Caption</figcaption>
  </figure>
</div>
```

Frontend

```html
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio">
  <div class="wp-block-embed__wrapper">
    <iframe title="Matt Mullenweg: State of the Word 2023" width="500" height="281" src="https://www.youtube.com/embed/c7M4mBVgP3Y?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>
  </div>
  <figcaption class="wp-element-caption">Caption</figcaption>
</figure>
```

As you can see, in the editor, the block wrapper element is a `div` element, not a `figure` element.

This isn't an issue in most cases, but it can cause a visual difference when a block next to an Embed block has zero margins applied. This is because [the figure element has a bottom margin](https://github.com/WordPress/gutenberg/blob/aca9273fd451cd9f264dd8116f9816e5b7ec3487/packages/block-library/src/common.scss#L158-L163) applied to it.

Editor:

editor

Frontend:

frontend

## What is your proposed solution?

We should be able to make it match the front-end HTML by applying a figure element instead of the block wrapper div in the editor, and removing the existing figure element.

As a preliminary to this, it might make sense to rewrite the [EmbedPreview component](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/embed/embed-preview.js) from a class component to a function component.

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

- Fixes - https://github.com/WordPress/gutenberg/issues/65179

## Why?

- To match the exact HTML for frontend and backend as per - https://github.com/WordPress/gutenberg/issues/65179

## How?

- PR removes the block wrapper div, instead adds `figure` as a wrapper, so it matches with frontend markup.

## Testing Instructions

1. Open any post/page.
2. Add embed block.
3. Add URL to be embeded, check for frontend and backend markup. 
4. It should be similar.

### Testing Instructions for Keyboard

- None.

### Backend

```
<figure tabindex="0" class="block-editor-block-list__block wp-block is-selected wp-embed-aspect-16-9 wp-has-aspect-ratio wp-block-embed" id="block-8d19fac7-16f5-44ac-8ae0-6630fd12dc9d" role="document" aria-label="Block: YouTube Embed" data-block="8d19fac7-16f5-44ac-8ae0-6630fd12dc9d" data-type="core/embed" data-title="YouTube Embed">
    <div class="wp-block-embed__wrapper">
        <iframe title="Embedded content from www.youtube.com" class="components-sandbox" sandbox="allow-scripts allow-same-origin allow-presentation" width="462" height="260">
        </iframe>
    </div>
</figure>
```

### Frontend

```
<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio">
    <div class="wp-block-embed__wrapper">
        <iframe title="Alexandre Corbeil on Gaining New Skills at Trebas Institute Toronto" width="500" height="281" src="https://www.youtube.com/embed/BOM34PANOHM?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="">
    </iframe>
    </div>
</figure>
```

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

There are two things that need to be addressed in order for this PR to move forward.

### Fix E2E tests

The `figure` tag applies to the block itself, not inside it. Therefore, `currenEmbedBlock.locator('figure')` can no longer find the `figure` element.

The following changes are required:

```diff
diff --git a/test/e2e/specs/editor/various/embedding.spec.js b/test/e2e/specs/editor/various/embedding.spec.js
index fb9746dce5..fe488f9130 100644
--- a/test/e2e/specs/editor/various/embedding.spec.js
+++ b/test/e2e/specs/editor/various/embedding.spec.js
@@ -134,15 +134,15 @@ test.describe( 'Embedding content', () => {
                        'https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/'
                );
                await expect(
-                       currenEmbedBlock.locator( 'figure' ),
+                       currenEmbedBlock,
                        'WordPress valid content. Should render valid figure element.'
-               ).toHaveClass( 'wp-block-embed' );
+               ).toHaveClass( /wp-block-embed/ );
 
                await embedUtils.insertEmbed(
                        'https://www.youtube.com/watch?v=lXMskKTw3Bc'
                );
                await expect(
-                       currenEmbedBlock.locator( 'figure' ),
+                       currenEmbedBlock,
                        'Video content. Should render valid figure element, and include the aspect ratio class.'
                ).toHaveClass( /wp-embed-aspect-16-9/ );
```

### Restore `is-type-video` CSS class

On the frontend, the `figure` tag may have classes like `is-type-video` applied, but not in the editor.  We need to restore [the removed CSS](https://github.com/WordPress/gutenberg/pull/65478/files#diff-a934ed89988ca9bb62271ff86a51f0a003f77b9d92e99b679d00a586fef44ba2L101) to the block wrapper.

**Comment by hbhalodia** [comment]
Thank You, @t-hamano for review. I would address the requested feedbacks.

**Comment by hbhalodia** [comment]
Hi @t-hamano, On adding the className to the block wrapper, some functionalities are breaking in the editor, for example, If I do not add the class, then if you click on the video, you can see the block controls, and you can update it, but on adding the class, block controls are not visible, and you would not able to update anything. Here is the screencast for the same.


https://github.com/user-attachments/assets/540fe9d0-eccd-44e8-9afa-38e6363366b8

**Comment by t-hamano** [comment]
We cannot add the `className` prop directly to the `figure` element.

The `blockProps` itself contains classNames, but if we add the `className` prop after `blockProps`, the `className` from `blockProps` will be overwritten and the block will not work properly.

We will probably need to add the class name via `useBlockProps`, like so:

```javascript
const blockProps = useBlockProps( {
	className: clsx( {
		'is-type-video': 'video' === type,
	} ),
} );
```

**Comment by hbhalodia** [comment]
Hi @t-hamano, I have added the requested changes, and added the fix by changing the `blockprops.className`, this is because, className and type are added after the blockProps is being added, hence we cannot directly add there, so need to update the className in a way.

Thank You,

**Comment by t-hamano** [comment]
@hbhalodia Thanks for the update!

I've tried several providers, or updating additional CSS classes, etc. and everything seems to work fine.

- Could you rebase this PR? It should fix the E2E test failure.
- This might be a matter of preference, but class names might be better for an ad-hoc approach:
  ```diff
  diff --git a/packages/block-library/src/embed/edit.js b/packages/block-library/src/embed/edit.js
  index b69fc75cef..17f6261751 100644
  --- a/packages/block-library/src/embed/edit.js
  +++ b/packages/block-library/src/embed/edit.js
  @@ -251,9 +251,6 @@ const EmbedEdit = ( props ) => {
                  className: classFromPreview,
          } = getMergedAttributes();
          const className = clsx( classFromPreview, props.className );
  -       blockProps.className = clsx( blockProps.className, className, {
  -               'is-type-video': 'video' === type,
  -       } );
   
          return (
                  <>
  @@ -265,7 +262,12 @@ const EmbedEdit = ( props ) => {
                                  toggleResponsive={ toggleResponsive }
                                  switchBackToURLInput={ () => setIsEditingURL( true ) }
                          />
  -                       <figure { ...blockProps }>
  +                       <figure
  +                               { ...blockProps }
  +                               className={ clsx( blockProps.className, className, {
  +                                       'is-type-video': 'video' === type,
  +                               } ) }
  +                       >
                                  <EmbedPreview
                                          preview={ preview }
                                          previewable={ previewable }
  ```
  Similar approaches can be found [here](https://github.com/WordPress/gutenberg/blob/e0c5a598a8aa23dc045864a65c7b967547a01439/packages/block-library/src/button/edit.js#L265-L269) and [here](https://github.com/WordPress/gutenberg/blob/e0c5a598a8aa23dc045864a65c7b967547a01439/packages/block-library/src/gallery/gallery.js#L35-L45).
- While testing this PR, I noticed that there were some CSS classes missing from the editor. It would be nice to address this in a follow-up:
  - `wp-block-embed-{variationName}` (example: `wp-block-embed-youtube`)
  - `is-provider-{providerName}` (example: `is-provider-youtube`)
  - `is-type-rich` (For example, when you embed Twitter, this CSS class is added to the front-end:)

**Comment by hbhalodia** [comment]
Hi @t-hamano, thanks for the feedback. I would update the PR with requested changes.

**Comment by hbhalodia** [comment]
Hi @t-hamano, I have updated the PR with the requested changes. Can you please review the same.
Thank You,

**Review by t-hamano — APPROVED** [review]
LGTM! Thanks for the update 👍

**Pull request merged**
