### PR TITLE
Update columns index.js adding translatable (i18n) parts

### PR DESCRIPTION
**Pull request by nukaga**
Adding translatable (i18n) parts

## Description
Part of the series of sentences displayed in "lorem ipsum" was not translatable.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @nukaga thank you for your contribution 👍 
These strings are example text and not supposed to be readable, but I guess in some languages with different charsets this example text may not look good, so making them translatable seems like a solution. Any thoughts on this @swissspidy?

**Comment by swissspidy** [comment]
> I guess in some languages with different charsets this example text may not look good

Just think about Arabic or Japanese and how lorem ipsum does not work for these languages.

**Comment by swissspidy** [comment]
Ideally we'd also add some translator comment that mentions that this is example text.

**Comment by torounit** [comment]
Should use `_x` instead of `__`  ?

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by jorgefilipecosta** [comment]
> Should use _x instead of __ ?

Hi @torounit, _x should be used when the same word/string can have different translations depending on the context it is used. It seems, this example strings don't fit that use case, so I think we can use __.,

**Pull request merged**
