### PR TITLE
Add a filter to allow re-ordering of the block inserter tabs

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Currently there is no way for plugin developers to change the order of the panel tabs on the block inserter, ie. some sites may want to favour the use of patterns over individual blocks and so have the patterns tab as the first selected item when the inserter is opened.

## How has this been tested?

Can be tested by checking out this PR and adding the following code at bottom of the tabs.js file.

```
addFilter(
	'editor.BlockInserterTabs.order',
	'myplugin/inserter-order',
	(tabs) => tabs.reverse()
);
```

Before:
Screen Shot 2021-02-04 at 8 59 20 AM

After:
Screen Shot 2021-02-04 at 9 00 07 AM

## Types of changes
Adds a filter

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by draganescu** [comment]
This looks like a useful but a bit overly specific filter ;)

**Comment by glendaviesnz** [comment]
> This looks like a useful but a bit overly specific filter ;)

@draganescu Do you think it would be better to leave off the `.order` so it could be used for manipulation of the tabs in ways other than ordering ?

**Comment by glendaviesnz** [comment]
> This looks like a useful but a bit overly specific filter ;)

@draganescu I have made the filter less specific. Let me know if there is a better, even less specific, way to handle this that I am overlooking.

**Review by draganescu — COMMENTED** [review]
I think this is a useful filter and in the current form it is generic enough. I wonder though ... this filter allows one to also add a tab. That tab though has no corresponding content, so it looks like some kind of incomplete API for the inserter.

Should we allow new tabs and their content for the inserter, in a separate API?

Maybe here instead of a filter to the tabs themselves, create a filter that takes the default order `['block', 'patterns', 'reusable']` and return the new order, via fixed names, discarding anything that is not implemented? Then we sort them by the order returned by the filter.

**Comment by mcsf** [comment]
I don't think this should be a filter.

If the impetus is to make Patterns more prominent, we need a different mechanism for that, like initialising the Inserter with a “default” tab without changing order.

**Comment by draganescu** [comment]
Yes @mcsf that was also a feeling I shared. But don't plugins "get it" - the inserter - already initialized in editors? It does feel like that is some kind of "setting" for the inserter, but the question is outside of filtering it how can 3rd parties change it?

**Comment by mcsf** [comment]
> but the question is outside of filtering it how can 3rd parties change it?

Why should they? I think we are pretty much talking in abstract, and need to be very careful, very conservative, about permissive APIs such as this. From the use case on which the PR is grounded, it seems to me like actual ordering or filtering is not the solution. If some other party has very specific intentions for the block editor — such as adding random functions to the Inserter — at some point it warrants its own editor — like core does with `edit-site`, `edit-navigation`, and like third-parties do with [`blockbook`](https://github.com/youknowriad/blockbook).

**Comment by glendaviesnz** [comment]
thanks for the feedback @draganescu and @mcsf  - closing this PR in favour of exploring a configuration option instead.

**Pull request closed without merging**
