### PR TITLE
Block Parser: Disable console.info in production 

### LINKED ISSUE #33148: Flood of `console.info()` notices
## Description
In WordPress 5.8-beta1 through RC1, the browser console is displaying many notices when editing a post. The errors are a variation of:

```
Block successfully updated for `core/button` ( 
Object { name: "core/button", icon: {…}, keywords: (1) […], attributes: {…}, providesContext: {}, usesContext: [], supports: {…}, styles: (2) […], save: save(), apiVersion: 2, … }
 ).

New content generated by `save` function:

<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color has-background no-border-radius" style="background-color:#000000;color:#ffffff">Visitar</a></div>

Content retrieved from post body:

<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color has-background no-border-radius" style="background-color:#000000;color:#ffffff">Visitar</a></div> blocks.min.js:2:51968

```

Is this an intentional decision to include these notices now? If so, could the notices be updated to be conscious of when `WP_DEBUG` and only output this information when set to `true`? I can open up a companion ticket on Trac if appropriate.

This behavior did not occur in WordPress 5.7.2.

[Originally reported in the Alpha/Beta/RC forums](https://wordpress.org/support/topic/5-8-rc1-bug-i-see-a-lot-of-console-messages-new-content-generated-by-save/).

## Step-by-step reproduction instructions
1. Install 5.8 RC1.
2. Open the console.
3. Edit the Sample Page post created with all new installs.
4. Observe the notices.

## Expected behaviour
Minimal notices are displayed in the console.

## Actual behaviour
A lot of notices are displayed in the console.

## WordPress information
- WordPress version: 5.8 RC1
- Gutenberg version: NA
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Mac
- Operating system: MacOS 10.15.x
- Browser: Firefox

### PR DESCRIPTION
**Pull request by mkaz**
## Description

The block validation will display a console.info for blocks succesfully updated during the validation process. This PR wraps that console.info in a check for production so it is not displayed for produciton instances.

Fixes #33148

## How has this been tested?

- Open a post created in a previous version (sample post with buttons works)

- Confirm validation notice is shown in console (info needs to be checked)

- Apply fix and run against production build
    - Production build created using: `npm run build`
   
- Test again and confirm no console.info

## Types of changes

Wraps console.info with a production environment check.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Tested and works as expected. I don't see logs after running `npm run build`.

We have a similar issue and related PR we can close once this is merged. Issue #30697 - PR #30705.

**Review by mcsf — CHANGES_REQUESTED** [review]
We have always logged these validation notices, intentionally, both on production and dev builds. They can be important clues when user content is automatically migrated/updated, especially in the context of troubleshooting, and they are useful to extenders and admins even when running production.

**I don't think it should be on the table to suppress these** without some discussion and without first asking some questions. What has changed, why now? Is the volume of notices greater? If so, what does that mean? What is being validated: just user content, or perhaps some application fixtures (e.g. block examples or patterns)? I suspect there are lots of fixtures across Gutenberg and themes that need to be updated to the latest shapes of blocks.

If we don't give this due diligence, we'll just normalise validation notices into irrelevance.

**Comment by desrosj** [comment]
> I don't think it should be on the table to suppress these without some discussion and without first asking some questions. What has changed, why now? Is the volume of notices greater?

Totally agree here. Based on my testing, there were no notices present in 5.7.2 when visiting the default Sample Page in WordPress vs. in 5.8 development releases (beta1-RC1). The [code firing this notice has been in place for over 2 years](https://github.com/WordPress/gutenberg/blame/trunk/packages/blocks/src/api/parser.js#L598-L605), so the change causing the increase in notices is coming from a different location.

I'm not familiar enough with recent internal changes to know what may have changed to cause the number of `block.validationIssues` to increase this much.

**Comment by Mamaduka** [comment]
These notices are triggered by block patterns.

**Comment by desrosj** [comment]
> We have always logged these validation notices, intentionally, both on production and dev builds. They can be important clues when user content is automatically migrated/updated, especially in the context of troubleshooting, and they are useful to extenders and admins even when running production.

Playing devil's advocate, I'd argue that PHP notices and warnings are a similar parallel to these notices. But those are hidden unless `WP_DEBUG` mode is `true`.

I would not be opposed to leaving these notices as visible for any site running the plugin, but thinking it does not benefit the majority of users to display these console notices in Core itself unless debugging has been turned on.

**Comment by mkaz** [comment]
I updated the code with a better implementation, using `GUTENBERG_PHASE === 2` check. The plugin will set to 2, but core does not per this [feature flag docs](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/feature-flags.md) so this will display the notice if using plugin but not core.

The previous production check wasn't great because then it wouldn't even show using plugin to test. Also, for future reference there is a [warning package](https://github.com/WordPress/gutenberg/tree/trunk/packages/warning) that would've been better choice if trying to limit in production.

@mcsf @desrosj I see both sides of keeping and removing, so will let y'll decide if it should be merged or not.


Also, it looks like the root cause is related to #33017 and @ntsekouras / @Mamaduka fixed in #33117 but not sure why both those would be in RC1 - is it a dependency issue of pulling future block patterns to an older editor? See https://github.com/WordPress/pattern-directory/issues/245

**Comment by pbiron** [comment]
I've been testing in 2 environments: 1 running 5.7.2 w/ twentytwenty and 1 running 5.8-RC1 w/ a child of twentyseventeen (also happened as early as 5.8-beta1 I think).

In 5.7.2 I get no `console.log()` output, but in 5.8.X is see a bunch of `console.log()` output.  After investigating, all the 5.8.X output is coming from block patterns registered by the bundled themes, even tho those patterns are *not* used in the post I'm editing.

To further test, I switched the 5.7.2 site to use twentyseventeen and the 5.8.X site to use twentytwenty.  Same results: no `console.log()` output in 5.7.2 and lots of output in 5.8.X.

This suggests that something has change din 5.8 about how `createBlockWithFallback()` is getting called for block patterns.  That is, somehow the patterns in these bundled themes are generating validation errors in 5.8.X but not in 5.7.2.

**Comment by mcsf** [comment]
> Playing devil's advocate, I'd argue that PHP notices and warnings are a similar parallel to these notices. But those are hidden unless `WP_DEBUG` mode is `true`.
> 
> I would not be opposed to leaving these notices as visible for any site running the plugin, but thinking it does not benefit the majority of users to display these console notices in Core itself unless debugging has been turned on.

The crucial difference between regular PHP notices and these is that these pertain to user content (while regular notices pertain to execution of code, which is the domain of the admin or developer) and they reflect potential modifications of user content.

> I updated the code with a better implementation, using `GUTENBERG_PHASE === 2` check. […] I see both sides of keeping and removing, so will let y'll decide if it should be merged or not.

I appreciate the follow-up and trying to find a compromise, @mkaz, though I'd still like to keep the logging in place and weed out runaway block validations.

> Also, it looks like the root cause is related to #33017 […] but not sure why both those would be in RC1 - is it a dependency issue of pulling future block patterns to an older editor? See [WordPress/pattern-directory#245](https://github.com/WordPress/pattern-directory/issues/245)

Thanks for digging, that seems like the best lead. It seems the fix landed in the plugin but is yet to be backported to core. @ntsekouras is away for the day, but he may confirm our next move on Monday.

**Comment by ntsekouras** [comment]
>Also, it looks like the root cause is related to #33017 […] but not sure why both those would be in RC1 - is it a dependency issue of pulling future block patterns to an older editor? See WordPress/pattern-directory#245

>Thanks for digging, that seems like the best lead. It seems the fix landed in the plugin but is yet to be backported to core. @ntsekouras is away for the day, but he may confirm our next move on Monday.

These are kind of two different things. #33017 is not in core as it was merged in GB `11.0-rc` and the regression fix is targeted for the same version `11.0`. These were actual errors in the editor and not just `info logs`.


#33148 issue is about deprecation warnings coming from block patterns. In 5.8 there have been introduced many enhancements and features around block patterns that require the parsing of them during the loading of the editor (in browser's idle time though to be non-blocking). The parsing is needed and cannot be avoided.


>If we don't give this due diligence, we'll just normalise validation notices into irrelevance.

I agree with this 100%!

**Comment by gziolo** [comment]
Thinking a bit more about it, it’s inevitable that with block patterns we will see more and more of those logs. Maybe, we should be less concerned about successful migrations.

I see a ton of `console.info` logs when developing Gutenberg. It's inevitable to see the growing number of (successful) validation logs with the growing number of block patterns in the directory. I doubt that those patterns are going to be updated often after they get submitted. Well, I think it's great that they work fine even when core blocks update the output format.

What worries me here, that those logs come from ~the preview in the block inserter~ the block patterns parsing that isn't related to the content used on the site. I don't think we should be really reporting those issues on production as they bring only confusion. What matters here is if they get correctly inserted into the content/template.

**Comment by mcsf** [comment]
#34163, which was just merged, might a good enough solution to close this one. WDYT?

**Comment by gziolo** [comment]
Closing this one in favor of #34163 that has landed. Thank you @mkaz for sparking the fruitful discussion 😄

**Pull request closed without merging**
