### PR TITLE
Revert moving is-typing class

### LINKED ISSUE #29391: Navigation Link Block: Crashes when you edit the title
## Description

The Navigation Link Block crashes when you attempt to edit the text of the block.

## Step-by-step reproduction instructions

1. Add a Navigation block
2. Add a Link block
3. Enter the URL `https://example.com` and press enter. The text of the block will change to "example.com"
4. Click on the text so that the cursor is somewhere in the text field
5. Press an arrow or letter key

## Expected behaviour

The cursor should move or the letter should be inserted.

## Actual behaviour

The block crashes.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/128240/109358055-226a2d80-7851-11eb-89ce-0ffd5581bc69.mov

## WordPress information
- WordPress version:  5.7-beta1-50237
- Gutenberg version:  master c993a8
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Desktop
- Operating system:  macOS Big Sur
- Browser:  Reproduced in Chrome 88.0.4324.192 and Firefox Developer 87.0b2

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #29391.
Introduced by #29186.
Alternative to #29596: there's no need to revert the whole commit.

Fixes an error in the navigation block if you type in a child block. Partly reverts #29186. Somehow moving the `is-typing` class causes the problem, but I haven't tracked down why it causes an infinite loop.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by gwwar — APPROVED** [review]
Thanks @ellatrix for taking a look! The smaller revert here does the trick for fixing typing behavior in the Navigation block.

**Comment by georgeh** [comment]
Also confirming that this fixes #29391 for me too. Thanks @ellatrix!

**Comment by ellatrix** [comment]
Great! Seems like it would be good to have some navigation block e2e tests.

**Comment by gwwar** [comment]
> Seems like it would be good to have some navigation block e2e tests.

Yes, that's next :D I'm working on re-enabling them in https://github.com/WordPress/gutenberg/pull/29543

**Pull request merged**
