### PR TITLE
Allow drag and dropping blocks and patterns in zoom-out mode

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

This PR updates the zoom-out with the following changes:

 - Removes the always visible in-between inserters
 - Restores the regular in-between inserter (which also serves as a drag and drop insertion point)
 - Fix drag and drop into the canvas while in zoom-out mode.

## Testing Instructions

1- Open the site editor
2- Click the toolbar button to enter zoom-out mode
3- Try dragging patterns from the inserter into the canvas.

## Screenshots or screencast 

https://user-images.githubusercontent.com/272444/191828158-86b40065-8df6-45be-8337-dc8ff9e243e2.mov

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks, it's working as advertised for me. There are a couple of quirks with the Inserter (notice how it behaves oddly if its visible before engaging zoom-out mode) but they're probably edge cases.


https://user-images.githubusercontent.com/846565/191924272-09c8e0c8-6f34-4816-884a-5053de494f32.mp4

**Comment by youknowriad** [comment]
@jameskoster yeah, it seems like the issue is that it's visible in the first place because in theory, it should be hidden unless you're hovering between blocks.

**Comment by youknowriad** [comment]
@jameskoster it also looks like a safari bug that is already present in trunk, just made visible here.

**Comment by youknowriad** [comment]
Ok, so to keep this PR small and focus on the bug fix for drag and drop, I restored the inserters. I think it's now 100% an improvement over trunk.

I'll leave inserter related explorations separate.

**Review by jameskoster — APPROVED** [review]
Inserters restored. Drag and drop working.

https://user-images.githubusercontent.com/846565/191960563-7fda5258-1f32-4fe8-9703-f92e8c1aa54b.mp4

**Pull request merged**
