### PR TITLE
Try removing backdrop blur to see if that improves performance

### PR DESCRIPTION
**Pull request by glendaviesnz**

### CODE REVIEW

**Comment by priethor** [comment]
Thanks for trying this, @glendaviesnz !

[@annezazu's testing](https://github.com/WordPress/gutenberg/issues/43877#issuecomment-1246099149) and my own show performance is indeed good with this change. Given performance is more priority than aesthetics, can we get this merged soon to release a second Gutenberg 14.1 RC and backport to WP 6.1? cc @c4rl0sbr4v0

**Review by cbravobernal — APPROVED** [review]
LGTM

**Comment by cbravobernal** [comment]
[Cherry-picked for 14.1](https://github.com/WordPress/gutenberg/commit/9e55eaf27166dcaf1f2dbc28a9399f3fe97c8c4b) 🚀

**Comment by ockham** [comment]
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: 6b849726c7

**Pull request merged**
