### PR TITLE
Add custom placeholder icon

### PR DESCRIPTION
**Pull request by ajitbohra**
## Description
Currently `Placeholder` component does not support custom icon like `IconButton`.  Allowing custom icon will make the component more flexible. 

## How Has This Been Tested?
Manually 

## Screenshots (jpeg or gifs if applicable):
placeholder-icon

## Types of changes
Nonbreaking component change

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Nice 👍 

Evidenced by this bug, maybe we need future consolidation of this logic into an "Icon" component. Not necessary, but an idea.

**Comment by ajitbohra** [comment]
@aduth same thought `Icon` Component to dry the icons implementation. Will also help in code consistency have identified few places which can be refactored. Planning to work on the PR for the same.

**Comment by ajitbohra** [comment]
@aduth 

Was looking to drying up Icon:

Currently, we are allowing the custom icon for:
- ButtonIcon
- Placeholder 
- BlockIcon

Have noticed we already have a reusable component for the same `BlockIcon` either we can use this or rename it to `Icon` to be more generic and refactoring code referencing it. Also, we can move it to Components your thoughts.

**Comment by aduth** [comment]
Yeah, good call, `BlockIcon` looks like it could easily be generalized as `Icon`. There's nothing block-specific about it. Moving to `components` sounds reasonable. Since it's exposed as part of the public interface, we could either keep it (as a simple pass-through to `Icon`) or [`deprecate`](https://github.com/WordPress/gutenberg/blob/master/utils/deprecation.js) it.

**Comment by ajitbohra** [comment]
@aduth deprecating it sounds much better will work on the initial PR

**Pull request merged**
