### PR TITLE
Replace RovingTabIndex with reakit composite

### PR DESCRIPTION
**Pull request by talldan**
## Description
Follow up to #19799, related to #22373, see comment thread https://github.com/WordPress/gutenberg/pull/19799#issuecomment-627259656 for further info.

Replaces the internally used `RovingTabIndex` component with the `Composite` component from Reakit library. `Composite` is already used by another component to implement a grid, so it seems like a good opportunity to consolidate and rely on the more robust implementation of a library.

Props to @diegohaz for the work on Reakit and the example that this is based on:
https://codesandbox.io/s/reakit-composite-treegrid-sh6uu?file=/src/TreeGrid.js

## Types of changes
Non-breaking refactor

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
There are some difficult challenges here.

The block navigation has now evolved to have both `RichText` and a `DropdownMenu` components within cells, and both those components currently don't support `refs` or being focus managed.

`DropdownMenu` also has some toolbar behavior built-in (down arrow opens the menu), which is problematic in this usage.

**Comment by diegohaz** [comment]
> The block navigation has now evolved to have both `RichText` and a `DropdownMenu` components within cells, and both those components currently don't support `refs` or being focus managed.

Is there an issue I can check to learn more about that change on the block navigation?

> `DropdownMenu` also has some toolbar behavior built-in (down arrow opens the menu), which is problematic in this usage.

The WAI-ARIA Authoring Practices has a section about this: https://www.w3.org/TR/wai-aria-practices/#gridNav_inside. But this is really tricky indeed.

For dropdowns, I think it's easier to just disable the arrow down key on them like on this example: https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html#ex2_label

**Comment by diegohaz** [comment]
By the way, `DropdownMenu` doesn't need to accept `ref` to work with this. You can pass `ref` to the `toggleProps` prop and it will be passed to the toggle button. I've updated the CodeSandbox with that: https://codesandbox.io/s/reakit-composite-treegrid-sh6uu?file=/src/App.js:691-935

**Comment by talldan** [comment]
@diegohaz Thanks for your feedback so far, that's been really helpful.

I think I'm going to park this PR for the time being as the Block Navigation UI is in some pretty rapid development at the moment and I can't keep up 😄 

One thing I did spot, and I wasn't sure whether it was an issue with this PR or something upstream with Reakit, is that when re-ordering rows in the table (e.g. when moving blocks), the keyboard navigation order became incorrect. It felt like there might be a cached version of the expected order of elements held internally.

For example if I have blocks A, B, and C, arrowing through the rows works as expected, but then reordering to A, C, B, keyboard navigation would go from A to B to C still.

**Comment by diegohaz** [comment]
> One thing I did spot, and I wasn't sure whether it was an issue with this PR or something upstream with Reakit, is that when re-ordering rows in the table (e.g. when moving blocks), the keyboard navigation order became incorrect. It felt like there might be a cached version of the expected order of elements held internally.
>
> For example if I have blocks A, B, and C, arrowing through the rows works as expected, but then reordering to A, C, B, keyboard navigation would go from A to B to C still.

Oh, good catch! I haven't looked into it yet, but I'm pretty sure that's a limitation on Reakit. For performance reasons, `composite.items` will be updated only when items mount/unmount. So, re-mounting the item could work, but it's not a good solution here as we would lose focus and internal state on the moving item. 😕

I'll make sure this is supported in the next version.

**Comment by diegohaz** [comment]
FYI, Reakit v1.1.0 will remove the `unstable_` prefix from the Composite components and introduce a `composite.unstable_sort()` method that can be used after composite items are re-ordered.

- [Demo](https://next.reakit.io/storybook/?path=/story/composite--dynamic-composite)
- [Code](https://github.com/reakit/reakit/blob/55197659d782d94699715ca64504e46d908c31d8/packages/reakit/src/Composite/__examples__/DynamicComposite/index.tsx#L39-L41)

**Pull request closed without merging**
