### PR TITLE
Docs: Add an example for the e2e tests snapshot update

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
PR documents method for updates e2e test snapshots.

## Testing Instructions
None

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Looks good! I guess it may be worth adding instructions for Playwright as well, but I don't know what they are 🤔

**Comment by Mamaduka** [comment]
> I guess it may be worth adding instructions for Playwright as well, but I don't know what they are 🤔

I've not used Playwright's command so far. Maybe it should be a part of the [migration guide](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md) for now. @kevin940726, what do you think?

**Comment by kevin940726** [comment]
Good idea! It's pretty similar in Playwright, just append `-u` to the CLI. Official doc [here](https://playwright.dev/docs/test-cli#reference).

**Comment by Mamaduka** [comment]
Thanks, @kevin940726. Added Playwright instrcution as well.

**Pull request merged**
