### PR TITLE
Hover fix

### LINKED ISSUE #10320: (Mobile) :hover styles on component menus are following thumb movements
**Describe the bug**

The `:hover` styles for component menu buttons aren't disabled as they should be resulting in the components menus following the thumb movements. 

**To Reproduce**

1. On mobile, go to adding a new post. 
2. Open any of the component drop down menus and scroll up and done a bit.

**Expected behavior**
On mobile, I'd expect that these styles would not show since hover isn't really an option.

**Screenshots**
Link to screencasts here: http://cld.wthms.co/rOz1SC and here: http://cld.wthms.co/VbiBYh

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 12
 - Browser: Firefox Focus 7.0, but also recreated on Chrome 69.0.3497.105, Safari native
- Gutenberg Version: master

### PR DESCRIPTION
**Pull request by jobthomas**
## Description

Fixes #10320 

## How has this been tested?

Tested on iOS 12 Safari - and Firefox Focus

## Types of changes

Disabling `:hover` for mobile

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tofumatt** [comment]
Any chance we could get before/after screen recording of this in action? That'd make review easier ❤️

**Review by tofumatt — APPROVED** [review]
Shoot; thought I approved this but I must've got distracted by another tab or a shiny object 😅

Thanks for the PR and thanks for the screenshots; they really helped!

I tweaked your comment to point to the PR and this looks good. I'll merge it once Travis is green 😄

**Comment by jobthomas** [comment]
Seems like Travis isn't happy ;) Thanks for the update @tofumatt

**Comment by tofumatt** [comment]
Travis was buggy with this PR and the failures are complaining about PHP files not in this change 🤷‍♂️

Just gonna merge because this works for me locally...

**Comment by shaunroselt** [comment]
So I haven't tested this yet, but it sounds sad when reading this.

I actually use my phone (Samsung Galaxy S9+) with Samsung DeX for all of my development work. I hope hovering will still work on my phone. I don't want this disabled at all.

**Comment by jobthomas** [comment]
@shaunroselt could you share a specific example of this? With most phones, it's required to actually click something in order to open up a section, not hover over (you can't hover with a finger).

That said, the only change it that it doesn't show up as a different colour on mobile.

**Comment by jobthomas** [comment]
Just as reference, the `$break-medium` is set to 782px. Based on what I can read, the Galaxy S9 is a higher resolution than that, so that would mean this pull request doesn't affect your device. The external monitor should also not be affected by this at all. 

All this does is not change the colours of the hover option _if_ the screen is less wide than 782px.

**Comment by shaunroselt** [comment]
> Just as reference, the `$break-medium` is set to 782px. Based on what I can read, the Galaxy S9 is a higher resolution than that, so that would mean this pull request doesn't affect your device. The external monitor should also not be affected by this at all.
> 
> All this does is not change the colours of the hover option _if_ the screen is less wide than 782px.

@jobthomas Okay that sounds better. Thanks. I have a 1920x1080 monitor at home and work for my phone. My actual phone resolution is just a bit bigger than 1440p.

Thanks

**Comment by jobthomas** [comment]
> I have a 1920x1080 monitor at home and work for my phone. My actual phone resolution is just a bit bigger than 1440p.

Nothing to worry then. It's only for devices smaller than that breakpoint.

**Pull request merged**
