### PR TITLE
Mobile master to master

### PR DESCRIPTION
**Pull request by SergioEstevao**
## Description

Bring some missing changes from RNMobile/master to the master branch.

## How has this been tested?

This can be tested using this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1375

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
After the last change is now working perfectly again 🎉 
Thank you @SergioEstevao for the update!

**Comment by gziolo** [comment]
You need to fix one issue before merging:

```
/home/travis/build/WordPress/gutenberg/packages/format-library/src/link/index.native.js
[0]   99:1  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by gziolo** [comment]
Hopefully, b23d6f9 fixes it.

**Comment by SergioEstevao** [comment]
@gziolo I'm still seeing a test failing but I don't think it's in anyway related to my changes... Can you help me?

**Comment by gziolo** [comment]
Yes, it looks like new e2e test for local autosave has some issues, @mcsf can you investigate?

**Comment by mcsf** [comment]
> Yes, it looks like new e2e test for local autosave has some issues, @mcsf can you investigate?

On it.

**Pull request merged**
