### PR TITLE
Update improve backward compatibility for deprecated settings

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR improves backward compatibility for deprecated settings.
It now follows this model:

- We remove the settings passed from the server on the Gutenberg plugin. We keep passing them during WordPress 5.6.
- We keep default values for the settings on the block editor client side.
- We change the back-compatibility model of useEditorFeature. Currently, if the equivalent old setting exists, it uses it. Now given that the old setting will exist all the time because it has a default value, we use the new setting if it exists and fallback to the old if it does not exist.

## How has this been tested?
I verified the default settings appear on the playground.
I verified the normal post editor still used settings from theme.json

### CODE REVIEW

**Comment by youknowriad** [comment]
It seems once we do that folks, should have the possibility to upgrade to the new API useEditorFeature. So I think it's probably better to wait for 5.6 before landing this as `useEditorFeature` is still experimental.

**Comment by jorgefilipecosta** [comment]
This PR is a must-have for 5.6 because without the PR on 5.6 on themes that don't explicitly set a color palette, or gradients, or font sizes the defaults will not appear. As now the defaults are passed by the global styles mechanism that will not be part of 5.6.

**Review by oandregal — APPROVED** [review]

**Comment by nosolosw** [comment]
Fixes https://github.com/WordPress/gutenberg/issues/25652

**Comment by noahtallen** [comment]
I hate to say it, but this actually broke backwards compatibility (at least in the way we were using it).

In order to enable custom line height for all themes, we were filtering editor settings to add the `enableCustomLineHeight` key. One would think that the `deprecatedFlags` feature would handle that, but unfortunately, since the _default_ (i.e. global) value for custom line height is false, the code will return false. It would only return the deprecated flag if the default value was undefined, which is not the case for line height.

**Comment by nosolosw** [comment]
Hi @noahtallen I believe this is a bug we need to fix. However, it seems to me that the bug is not in the client's `useEditorHook` but in how we source the existing settings. See https://github.com/WordPress/gutenberg/issues/26537 for details.

Essentially, we need to make this work for the following two use cases:

- WP core without the Gutenberg plugin => will use the existing features (eg: `enableCustomLineHeight`).
- WP core with the Gutenberg plugin => will use the new experimental features that can be enabled per context (global, paragraph, etc). In this case, we need to retrofit the existing settings into the new structure.

**Pull request merged**
