### PR TITLE
Add label elements to scheduler and visibility

### PR DESCRIPTION
**Pull request by Soean**
## Description
Changes the html element of the sidebar panel name for `post-schedule` and `post-visibility` from span to label. It also adds an ID for better accessibility.

Separated from #3188

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Looks good 👍

**Comment by afercia** [comment]
Sorry I'm not sure I understand why we should use label element associated to buttons. What is the reasoning behind this change?

While, technically, buttons are labelable elements, now clicking these new labels will activate the buttons making the popovers appear. This could be confusing for users. Not to mention the buttons accessible name is now calculated based on the new labels and the buttons text, highly confusing for assistive technologies users:

screen shot 2017-11-06 at 22 28 47

screen shot 2017-11-06 at 22 28 52

About these two buttons, see also "Controls labels should be meaningful even when read out of context" #470. The current practice to name the buttons with the current value of their underlying options rather than with the name of the available action is far from ideal.

**Comment by aduth** [comment]
>now clicking these new labels will activate the buttons making the popovers appear. This could be confusing for users.

This is what seemed sensible to me in my review, considering the behavior of labels in activating other types of form control (checkbox, radio). I do not feel strongly here and am happy to reverse these changes if this is not the case.

>Not to mention the buttons accessible name is now calculated based on the new labels and the buttons text, highly confusing for assistive technologies users:

Is this a result of the changes here, or to the general point raised in #470 that the buttons lack context? Is there any way for the relationship between a label and the button to be leveraged in screen readers to lend clarity here (i.e. Visibility -> Public, Publish -> November 6)?

**Comment by afercia** [comment]
The primary purpose of a label is giving controls a name. For example, an input field may use an "Email" label. The interaction (clicking on the label focus/checks the control) is a secondary effect.

What happens here is the label contributes to the calculation of the control accessible name. Labels should be meaningful even when read out of context. Users can jump directly to one of thes buttons and what they would here would be something like:
"Private Visibility"
and
"November 6, 2017 10:47 pm Publish"

Buttons should identify the underlying action. For example, would you give a form submit button a text "Send on November 6, 2017 10:47 pm"? Certainly not. You would likely just describe the button action: "Submit".

In this case, for example, "Private Visibility" would make me think that activating the button I set Visibility to Private. Highly confusing for users.

This actually increases the confusion caused by giving the buttons a name that is not the available action but the current setting value, as described on #470 and doesn't help to solve the issue.

I'd recommend to reconsider this change.

**Comment by Soean** [comment]
I wanted to make it more consistent with the labels. But your explanation makes it clear why it doesn't become more user-friendly. Thank you, I have learned something new and will think about it next time. We should therefore reverse this change here.

**Comment by afercia** [comment]
Thanks @Soean !

**Pull request merged**
