### PR TITLE
Fix #18825: Styles for the toggled state in the ToolbarButton added back

### LINKED ISSUE #18825: Blocks: Styles for the toggled state in the ToolbarButton removed
I noticed that this change created regression for toolbar buttons:
toggled-buttons

When they are toggled they no longer change their visual appearance. This is how it worked before 7.0:

Screen Shot 2019-11-29 at 15 38 14

It was introduced in #18631.

/cc @mapk @jasmussen @enriquesanchez

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Fixes #18825.

> I noticed that this change created regression for toolbar buttons:
> toggled-buttons
> 
> When they are toggled they no longer change their visual appearance. This is how it worked before 7.0:
> 
> Screen Shot 2019-11-29 at 15 38 14
> 
> It was introduced in #18631.

An alternative to #18860.

### After

Screen Shot 2019-12-02 at 13 10 48

Screen Shot 2019-12-02 at 13 11 15
Screen Shot 2019-12-02 at 13 11 35

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by gziolo** [comment]
The only issue I see is:

Screen Shot 2019-12-02 at 13 01 40

However, it's something that exists in the master as well for focused and hovered buttons:

Screen Shot 2019-12-02 at 13 12 58

**Review by jasmussen — APPROVED** [review]
toggles

Nice. Very nice.

**Comment by gziolo** [comment]
I moved the styles to the `ToolbarButton` component after talking with @youknowriad. In my testing, it works the same, but it's scoped more strictly.

**Review by youknowriad — APPROVED** [review]
LGTM

**Pull request merged**
