### PR TITLE
Increase Link UI search results to 10 on Nav Editor screen

### LINKED ISSUE #34283: Show more items in the "Recent" items of the Link UI when adding a new Nav item in the Nav Editor
## What problem does this address?

Currently when adding a new nav link item in the Nav _Editor_ you get to see recently updated items:

Screen Shot 2021-08-25 at 09 34 54

However there are only 3 and these are not contextual to the type of link you are adding (eg: Post, Page, Custom...etc).

## What is your proposed solution?

- [ ] Show more items by default - possibly 10? Check for UX on scrolling...etc.
- [ ] Make the suggestions based on the type of link being added - it should be aware of the context and show recent Pages when adding a `Page` link.

### PR DESCRIPTION
**Pull request by getdave**
## Description

As outlined in https://github.com/WordPress/gutenberg/issues/34283 when you add a new nav item the link UI only shows 3 initial search results. The same happens if you perform a search.

This PR amends the Nav Editor screen only to allow up to 10 search suggestion items to be displayed in the link UI. This provides more initial options for the user to choose from.

Ultimately we will also have [the bulk addition UI](https://github.com/WordPress/gutenberg/issues/31667) to help make it easier to find and insert items but in the meantime this tweak should improve the UX.

Fixes https://github.com/WordPress/gutenberg/issues/34283

## How has this been tested?

* Create at least 10 Posts and 10 Pages and 10 Categories/Tags.
* Enable Nav Editor experiment.
* Go to Nav Editor screen.
* Create blank menu.
* Add a menu item.
* See up to 10 initial suggestions based on the type of item you added (ie: Post, Page, Category...etc).
* Perform a text search - see up to 10 suggestions based on the type of item you added (ie: Post, Page, Category...etc).

Check this change has not impacted other editors/screens. Only the Nav Editor.

## Screenshots 

https://user-images.githubusercontent.com/444434/133259586-e1203c06-c200-48a6-910c-ebb5a77ef322.mp4

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
@rolf-yoast as we discussed this change.

**Comment by getdave** [comment]
@javierarce Are you happy with this change from a UI perspective?

**Review by Mamaduka — APPROVED** [review]
It works as expected 🚢 

P.S. I think we should add the "[Type] Enhancement" label for the changelog.

**Comment by javierarce** [comment]
> @javierarce Are you happy with this change from a UI perspective?

Yes, I think it is a good improvement, @getdave.

**Comment by getdave** [comment]
> I think we should add the "[Type] Enhancement" label for the changelog.

Excellent thinking 👍

**Pull request merged**
