### PR TITLE
Fix uncategorized pattern browsing when pattern has no categories 

### LINKED ISSUE #66944: Pattern without categories break the editor when browsing uncategorized patterns.
## What?
Patterns without categories break the editor when browsing uncategorized patterns.

### Step-by-step reproduction instructions

1. Activate TT5 theme.
2. Use the site editor
3. Open the inserter
4. Browse the patterns from the inserter
5. Click 'Explore all patterns' button at the bottom of the patterns inserter.
6. Click 'Uncategorized' in the pattern modal.

See the screencast below

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c30b0a8f-de3b-4f2b-9d7b-1e932df3b0dc

### Environment info

- WordPress 6.7 rc5

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Fix uncategorized pattern browsing when pattern has no categories. 

## Why?
Fixes: https://github.com/WordPress/gutenberg/issues/66944

## Testing Instructions
Follow instructions in  https://github.com/WordPress/gutenberg/issues/66944

### CODE REVIEW

**Comment by getdave** [comment]
Thanks @matiasbenedetto! When merged this will need to be moved to the `Punted to 6.7.1` column.

**Review by ramonjd — APPROVED** [review]
LGTM

Tested and could reproduce the error.

TT5 patterns without categories include `twentytwentyfive/template-404-vertical-header-blog` and `twentytwentyfive/template-page-photo-blog`. These had no `categories` property.

Can confirm that this PR prevents the browser from crashing.

Thank you!

Screenshot 2024-11-13 at 4 59 57 pm

**Review by Mamaduka — APPROVED** [review]
Thank you, @matiasbenedetto!

**Comment by cbravobernal** [comment]
I just cherry-picked this PR to the wp/6.7 branch to get it included in the next release.

**Pull request merged**
