### PR TITLE
Update embed block transforms to permit multiple links to be pasted in a paragraph (#27551)

### LINKED ISSUE #27551: Can not convert a classic block with multiple links to blocks. Can't even paste multiple links
**Describe the bug**
Whenever I try to:
1. Paste multiple URLS (like a list of sites)
2. Convert a classic editor block with multiple URLs.

It tries to embed those URLs as a single link.
Please see the screenshot:
[https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif](https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif)
**To reproduce**
- Paste multiple links at once, like these:
`The List of Sites:
https://addthis.com
https://elegantthemes.com
https://generatepress.com
https://woocommerce.com
https://backlinko.com
https://elementor.com
https://elmastudio.de
https://wptavern.com`

- OR if a Classic Block already has a list of links, Convert that to blocks.

**Screenshots**
[https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif](https://gauravtiwari.org/wp-content/uploads/2020/12/screenshot-erro.gif)

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.5.3]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] : Gutenberg is Installed.
- If the Gutenberg plugin is installed, which version is it?: 9.4.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version : 86

### PR DESCRIPTION
**Pull request by gaavar**
## Description

Modified `isMatch` function inside `embed/transform.js` to only trigger `embed` block for links containing single
https links.

This allows users to copy-paste multiple links at once without triggering an embed block which earlier malformed links by 
concatenating them together. 

## How has this been tested?

Tested this visually by pasting only one link and several links in the paragraph editor.

## Screenshots 
Multiple https links pasted together in the paragraph editor does not trigger Embed block.
image
Single https link pasted in the paragraph editor triggers Embed block.
image

## Types of changes

Bug Fix

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — COMMENTED** [review]
@gaavar Some of the checks are failing. This project users a version of 'prettier' for code formatting. You can run `npm run format-js packages/block-library/src/embed/transforms.js` in the command line to format the file, or alternatively install a prettier plugin in your editor.

**Comment by talldan** [comment]
BTW, another handy thing, if you write 'Fixes #27551' in the PR description when creating the PR, github automatically links the PR to the issue, and will close the issue when the PR is merged.

**Comment by gaavar** [comment]
@talldan Thank you so much for the code review! I have made the necessary changes and tested the code again visually.
 
I had some questions!

- So far, if you paste multiple links, that won't trigger embed blocks for each of those links but just treat them as plaintext. Is having embed blocks for each of the links the intended behavior that should be part of this bug fix?
- Is there a better way to test this code such as maybe unit tests that I should look into? (For now, I have tested it this visually!)

**Comment by gaavar** [comment]
- I am looking into the end-to-end test failure. I am not sure how to resolve the static test failure as I tried the commands it suggested but noticed no changes or any diffs locally.

**Review by talldan — APPROVED** [review]
Looks great now, thanks so much for addressing the changes, and your patience for this final review.

Congrats on your first contribution!

**Pull request merged**
