### PR TITLE
Add new overlay text icon, and use for image

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This adds a new overlay text icon, and uses it in the image block for the conversion to cover.

## How has this been tested?

Test converting an image to a cover using the toolbar button.

## Screenshots 

Before:

Screenshot 2021-02-22 at 12 54 47

After:

Screenshot 2021-02-22 at 12 59 40

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Please note I had to commit using --no-verify because of an update-api-docs.js failure that appeared unrelated. But wanted to just share in case it wasn't.

**Review by gwwar — APPROVED** [review]
Icon changes look good ✨ 

| Storybook | Image |
|-----|-----|
| Screen Shot 2021-02-23 at 9 58 45 AM | Screen Shot 2021-02-23 at 9 52 22 AM |

**Comment by jasmussen** [comment]
Thanks for the green light Kerry! I actually got some feedback suggesting a lowercase a might better ambiguate from text color:

Screenshot 2021-02-24 at 09 59 48

So I took the liberty of pushing that. I'll let this one sit for a moment, and then merge later today unless objections land!

**Comment by jasmussen** [comment]
Landing this one, and always happy to revisit!

**Comment by shaunandrews** [comment]
Just a quick note that I keep seeing this and think its a broken font, like the missing @ sign in the screenshot:
image

**Comment by jasmussen** [comment]
_Good thing we went lowercase the_ 😅 

I think the new icon is a big upgrade over what was there before, and that it's worth trying this out for a plugin version, see how it feels. If it still feels like a missing glyph in a week or two, I'll come back to this one. What do you say?

**Pull request merged**
