### PR TITLE
WIP: Show sibling inserter on hover

### PR DESCRIPTION
**Pull request by kirilzh**
## Description
Addresses: #22867

What I'm trying to do is detect over which block-id the mouse is hovering, find its index and then show two sibling inserters on the bottom and top respectively. I'm stuck however on handling blocks that have nested blocks in them. In such cases the event.target is the innermost element and I haven't found an elegant solution to the problem. :( 

Screen-Recording-2020-07-31-at-1

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think we've been slowly removing things from "hover" because of the distraction it can create when writing and moving the mouse. This PR seems to go a bit in the other direction, I want to make sure this is intended.

**Comment by jasmussen** [comment]
Hello, thank you for the PR! 

I would agree with Riad above, that we've been going back and forth on this one. The reason being the tension between the block editor being a place to create layouts, and the block editor being a place to write. When the sibling inserter appears immediately on hover as shown in this PR, it is incredibly easy to get to. But it also gets in the way of just writing when that's what you want. 

I understand the high level goal of #22867, and believe there is a great deal of improvement to be made to how the sibling inserter appears (we need to find the balance between it being there when you need it and not when you don't), but I do worry this goes too far in the other direction making it overwhelming. 

Is there a way the balanced can be pulled back again, and the delay being reintroduced if tuned?

**Comment by MichaelArestad** [comment]
> Is there a way the balanced can be pulled back again, and the delay being reintroduced if tuned?

I would second this. Adding a slight delay will make it less distracting.

**Comment by paaljoachim** [comment]
I also think we should have the blue line have a smaller width. Perhaps it should also be a little thinner.

**Comment by paaljoachim** [comment]
@kirilzh Kiril told me that he is not working on Gutenberg any longer. This also means that someone else will need to either take over this PR, or that we need to close it.

**Comment by youknowriad** [comment]
Closing this PR as there has been a lot iterations on this over time. Thanks all for your efforts.

**Pull request closed without merging**
