### PR TITLE
Integration tests: remove client ID from fixtures

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Similarly to #38638, the client ID is a useless piece of data to have in the test fixtures since it's just the block index.

JS change to review: https://github.com/WordPress/gutenberg/pull/38685/files?file-filters%5B%5D=.js&show-viewed-files=true
The fixtures are regenerated.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by dmsnell — APPROVED** [review]
Thanks for the follow-up. I had wondered if `clientId` is necessary. Same for `isValid` but we had _one_ `isValid: false` in there and I didn't want to poke it.

In testing I removed all the `.json` files and regenerated the fixture data with `GENERATE_MISSING_FIXTURES` and apart from a formatting difference, they were semantically identical.

**Comment by talldan** [comment]
> Same for isValid but we had one isValid: false in there and I didn't want to poke it.

An `isValid: false` probably points to a bug somewhere, or incorrect fixture data. 😬 

The tests should probably fail if `isValid` is ever `false` because I think the point of these tests is to have a valid block as a result.

**Comment by dmsnell** [comment]
> The tests should probably fail if isValid is ever false because I think the point of these tests is to have a valid block as a result.

I guess there are two: [core cover gradient](https://github.com/WordPress/gutenberg/blob/c292c8b206b9b6562a4883781658d0c0a400ac22/test/integration/fixtures/blocks/core__cover__gradient__deprecated-8.json) and [core file pdf](https://github.com/WordPress/gutenberg/blob/c292c8b206b9b6562a4883781658d0c0a400ac22/test/integration/fixtures/blocks/core__file__pdf-preview__deprecated-1.json). Both of these tests are testing deprecated blocks and their updates and so I think the point of the test is to ensure we don't break that update process.

If you see otherwise then yeah, let's zap the property. I'm reluctant to remove something though that I think people are relying on.

**Comment by talldan** [comment]
`isValid` should still be `true`, even for deprecations.

For the file block one, the fixture is wrong. It looks like it happened after this change - https://github.com/WordPress/gutenberg/pull/37100.

I think one of the anchor elements (the button one) should have an href that matches the `href` attribute, but it still has the port `8888`.

It is difficult to adjust a deprecated fixture. It's not straightforward to use the editor to produce the markup, so I imagine this adjustment was done by hand, and that's how the error happened.

(edit: here's a fix for the file fixture - https://github.com/WordPress/gutenberg/pull/38725)

The cover fixture looks like it was only just added - https://github.com/WordPress/gutenberg/pull/38392.

**Comment by ramonjd** [comment]
Fix for the Cover Block deprecation:

https://github.com/WordPress/gutenberg/pull/38728

Thanks for the heads up, folks.

**Comment by dmsnell** [comment]
Should we remove `isValid` from the fixtures instead of merging #38725 and #38728?

**Comment by ramonjd** [comment]
> Should we remove isValid from the fixtures instead of merging https://github.com/WordPress/gutenberg/pull/38725 and https://github.com/WordPress/gutenberg/pull/38728?

Given that the tests were passing when `isValid` was `false`, I wouldn't miss it. :) 

It did lead us to to an invalid fixture however, so perhaps the alternative is to configure the tests to return a fail instead.

**Comment by talldan** [comment]
I can't think of a reason for an invalid fixture. So I agree, I think `isValid: false` should cause the test to fail, and then there's no need for `isValid` in the snapshot. 

There might be added complexity in recursing through inner blocks and also checking their validity. Though I don't know whether that's strictly necessary, as an inner block should have its own fixture.

**Pull request merged**
