### PR TITLE
Revert "Enable Block Renaming support for (almost) all blocks (#54426)"

### PR DESCRIPTION
**Pull request by getdave**
## What?

This reverts commit 7aa5a913473c223402549a9060aafac652153965.

## Why?

Perf regression https://github.com/WordPress/gutenberg/pull/54426#issuecomment-1755733955

## How?

`git revert 7aa5a913473c223402549a9060aafac652153965`

### CODE REVIEW

**Comment by youknowriad** [comment]
FWIW I personally don't mind "not reverting" and debugging the issue but if you think this gives you more time and confidence to debug at ease, it's ok as well.

**Review by youknowriad — APPROVED** [review]

**Comment by getdave** [comment]
> FWIW I personally don't mind "not reverting" and debugging the issue but if you think this gives you more time and confidence to debug at ease, it's ok as well.

I don't have time to debug right now so yeh let's revert this and then we can investigate likely culprits. Nothing jumps out at me but then I've been starting at it a long time.

**Comment by youknowriad** [comment]
I'm guessing it's the "renaming" hook itself that has some kind of issue and it was just made visible because it was enable in all blocks (especially paragraph)

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/55250

**Pull request closed without merging**
