### PR TITLE
Update query block creation and replacement flows

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
part of #28737 

Now the query block starts with a placeholder allowing to pick a pattern or staring blank:
image

And there is also a "Replace" button on the toolbar that allows to totally replace an existing query block with a pattern:
image

## Testing Instructions
- Try the creation and modification flows for the queryblock.

### CODE REVIEW

**Comment by jameskoster** [comment]
Nice, it's working as advertised 🙂

Something about the 'replace' label doesn't work as well here as it does on the template part block. It may be time to consider moving this button to the transform menu like in the designs [here](https://github.com/WordPress/gutenberg/issues/28737#issuecomment-1039124007), and updating the label for non-template-part blocks to say something like "View patterns".

The three column pattern layout in the modal is less successful here as well. The thumbnails feel too small to give a useful preview:

Screenshot 2022-02-23 at 16 56 17

I appreciate this may be subjective, but to me suggests that we should consider some view options in the modal. Obviously this is something we can handle separately.

**Comment by annezazu** [comment]
>The three column pattern layout in the modal is less successful here as well. The thumbnails feel too small to give a useful preview:

Want to give a +1 to this feedback as it also came up around the current template part modal in the [latest FSE Outreach Program call for testing. ](https://make.wordpress.org/test/2022/02/23/fse-program-testing-call-12-hyping-headers/#comment-2367)

**Comment by jameskoster** [comment]
I opened #39308 to explore the modal design in more detail. 

Besides that, I still think the 'Replace' language and position feel a bit off here.

**Comment by paaljoachim** [comment]
Thank you for working on this Jorge!

I mentioned the same issue with the modul being too small here:
https://github.com/WordPress/gutenberg/pull/39147#issuecomment-1072083707
The first step might be to extend the size of the modul (grid view) for all moduls that show previews.

The Replace button works nicely! It is helpful to be able to go back and choose another Query Loop layout.
Now we just need a way to save a custom layout as a Query Loop template/pattern.

One thing I am wondering about. Replacing a layout, Page template/pattern, Query Loop template/pattern and other kinds of templates/patterns that will show up. I assume that there should be one method to replace the current selected pattern/template. Should we have one method consistent of various patterns/templates reflected in the sidebar to replace the layout?

Should Replace instead be in the sidebar top area below the description of a Query Loop? 
@jasmussen

**Comment by paaljoachim** [comment]
It seems this issue is very much also associated with this PR.

[Query loop block] Display an option to "Replace"
https://github.com/WordPress/gutenberg/issues/39466

**Comment by mauriac** [comment]
> It seems this issue is very much also associated with this PR.
> 
> [Query loop block] Display an option to "Replace" #39466

Yes you're right. I tested and it fix the issue you mentionned.

**Comment by mauriac** [comment]
> It seems this issue is very much also associated with this PR.
> 
> [Query loop block] Display an option to "Replace" #39466

Yes you're right. I tested and it fix the issue you mentionned.

**Comment by adamziel** [comment]
@jorgefilipecosta do you think could still land until Wednesday next week to be included in WordPress 6.0 release? To increase visibility, we can add it to the WordPress Editor 6.0 project board.

**Comment by jorgefilipecosta** [comment]
This PR was updated following a @mtias suggestion to keep the option to choose between carousel and grid views:

image


I think this PR should be part of 6.0.
It basically keeps to the existing design but moves to a modal and adds a replacement flow to be consistent with template parts.
Are there any design insights you could share @jameskoster, @jasmussen? Thank you in advance!

**Comment by paaljoachim** [comment]
Retesting.

Before:
Screenshot 2022-04-01 at 22 06 58

After - in a modal:
Screenshot 2022-04-01 at 22 08 36

After choosing a pattern it is seen on the canvas.
One can then click "Replace" which brings up the modal for choosing another Query Loop pattern. In the background one can see the existing Query Loop pattern. So one can somewhat compare with the Query Loop pattern currently in use to a new one might want to choose instead.

Screenshot 2022-04-01 at 22 12 08



The flow works, but I am just hesitant in moving it into a modal.

**Comment by jameskoster** [comment]
I think the design could use some massaging in order to work better in the modal. One thing that stands out: the previews in the carousel are less successful than the grid due to the missing background color... it's not clear where the UI ends and the pattern begins.

I'm going to explore how we can optimise the other details.

**Comment by jasmussen** [comment]
In case it's useful here, I've tried some CSS to enable a masonry grid of patterns in https://github.com/WordPress/gutenberg/pull/40034#issuecomment-1088335676.

**Comment by jameskoster** [comment]
Here's a take on how we might update the modal:


https://user-images.githubusercontent.com/846565/161726175-854f17cb-ae07-438f-9506-49182d357ab5.mp4

* The carousel adopts the body background color from global styles
* Actions are moved to the bottom of the modal
* Slightly increased modal size
* Removed the titles on the pattern grid – not sure how useful these really are and I find them a bit distracting. Not a strong opinion on this one.

**Comment by jorgefilipecosta** [comment]
> Here's a take on how we might update the modal:
> 
>  modal.mp4 
> * The carousel adopts the body background color from global styles
> * Actions are moved to the bottom of the modal
> * Slightly increased modal size
> * Removed the titles on the pattern grid – not sure how useful these really are and I find them a bit distracting. Not a strong opinion on this one.

This modal looks really nice 👍  Thank you @jameskoster I'm working on updating this PR to match the design :)

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, I submitted an update that makes this PR go in the direction of the design you proposed. Let me know what further improvements we can do or if you think this is ready for a first interaction so it is part 6.0 but we can continue to do follow-up improvements.

**Comment by jameskoster** [comment]
Nice, this is looking much better already! A couple of observations:

When a 'short' pattern is visible, the white space at the bottom of the modal is a bit jarring:

Screenshot 2022-04-07 at 13 48 58

Could we apply the background color to the entire carousel area?

If you have scrollbars set to permanently visible on your OS, the modal action area is prone to jumping around a bit:


https://user-images.githubusercontent.com/846565/162202815-1933597a-5817-4bb7-981a-a4c529f79b35.mp4

We can probably make the modal larger as well, I'll try some options.

**Comment by jameskoster** [comment]
Pushed some styling updates to increase the modal dimensions, and try the masonry layout that @jasmussen has going on in https://github.com/WordPress/gutenberg/pull/40034.


https://user-images.githubusercontent.com/846565/162219387-ac830c9f-a9c6-426d-ad2b-7a18c669578d.mp4



The staggered loading is very awkward, but I think that's something to fix elsewhere.

**Comment by jasmussen** [comment]
The masonry adds a lot 👍👍

We have to be careful with the column count method, though. There are cases where it will break items across columns, we want to avoid that. There should be a trick to fixing that, just something to be mindful of. Same with focus styles: unless inset, they might wrap across columns.

**Comment by paaljoachim** [comment]
Should we include a blank/empty pattern?

**Comment by paaljoachim** [comment]
Retesting.

This looks really nice! It creates a better overview than what we currently have!

Local site in Desktop Server running WP 5.9.3
Twenty Twenty Two
Chrome

I see jumping arrows when close to the end of the carousel.

https://user-images.githubusercontent.com/5323259/162260901-92542878-765e-4d1e-851d-825d8175b926.mp4

Questions that come up as I scroll through.
Should there be number like 1/25 - 2/25 - 3/25 or something like it to give a signal of how many patterns there are to choose from? 
Brainstorming....
What would be cool is to have a customization screen at the end to where one can add the various inner blocks associated with the Query Loop and put together a new Query Loop pattern.

**Comment by jorgefilipecosta** [comment]
> Could we apply the background color to the entire carousel area?

< If you have scrollbars set to permanently visible on your OS, the modal action area is prone to jumping around a bit:

Hi @jameskoster both issues were fixed. It required a lot of trial and error and some JavaScript given the way the resizing of the preview iframes happens etc but it seems to be working.

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta, the scrollbar issue is indeed fixed :)

I'm still seeing the background issue though 🤔 

Screenshot 2022-04-08 at 09 59 06

**Comment by jorgefilipecosta** [comment]
> Thanks @jorgefilipecosta, the scrollbar issue is indeed fixed :)
> 
> I'm still seeing the background issue though 🤔
> 
> Screenshot 2022-04-08 at 09 59 06

Strange this is what I see:

image


The background gets applied. Does all the editor canvas has a background applied?
Maybe it is some caching issue could you do a new build and reload the page without caching?

**Comment by jorgefilipecosta** [comment]
> Should we include a blank/empty pattern?

I guess for that the user should press the start blank button and not open the modal.

**Comment by jameskoster** [comment]
> Does all the editor canvas has a background applied?

Yes but it is using a css var, not sure if that affects anything?

I don't think it's a caching issue, I see the background color applied, it's just always `rgba(0,0,0,0)`. 

I tried setting the main background color to a hex value and that didn't work either 🤔

**Comment by jorgefilipecosta** [comment]
Hi @paaljoachim,
Thank you for the feedback and testing!

> I see jumping arrows when close to the end of the carousel.

That issue should be fixed.

> Should there be number like 1/25 - 2/25 - 3/25 or something like it to give a signal of how many patterns there are to choose from?

It totally makes sense to do that and provides an indication of how many patterns are there. But given that the current carousel also does not do that we can do that in the future.

> What would be cool is to have a customization screen at the end to where one can add the various inner blocks associated with the Query Loop and put together a new Query Loop pattern.

I thank bringing customization to the modal adds a lot of complexity (it would be a very huge task from the code point of view). I guess if the user wants to customize that can be done after the pattern is selected on the editor.

**Comment by jorgefilipecosta** [comment]
> > Does all the editor canvas has a background applied?
> 
> Yes but it is using a css var, not sure if that affects anything?
> 
> I don't think it's a caching issue, I see the background color applied, it's just always `rgba(0,0,0,0)`.
> 
> I tried setting the main background color to a hex value and that didn't work either 🤔

It seems the computation of the background color is failing on your setup. What theme are you using?

**Comment by jameskoster** [comment]
Twenty Twenty-Two.

**Comment by jorgefilipecosta** [comment]
> Twenty Twenty-Two.

That's also the one I'm using. Even if you apply a global background color on the site editor it does not work?

**Comment by jameskoster** [comment]
@jorgefilipecosta the plot thickens... I'm only seeing the issue in the Site Editor. It's working fine in the Post Editor :)

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta the plot thickens... I'm only seeing the issue in the Site Editor. It's working fine in the Post Editor :)

Thank you for the debugging 👍  I proposed a fix for the issue let me know if now things are working.

**Comment by jameskoster** [comment]
Now neither the Post Editor or the Site Editor are working correctly 🙈

**Comment by jorgefilipecosta** [comment]
> Now neither the Post Editor or the Site Editor are working correctly 🙈

That's not good news 🙈


That's what I'm seeing in the post and site editor respectively:
image


image

It seems working.

What issue are you facing? I also made a change to address double scroll bars maybe that fixed the issue?

**Comment by jameskoster** [comment]
> What issue are you facing?

The same as before, a white gap at the bottom of the carousel 🤔 

Site Editor:
Screenshot 2022-04-08 at 12 23 55

Post Editor:
Screenshot 2022-04-08 at 12 24 02

**Comment by paaljoachim** [comment]
I am not sure what your talking about the mention of the background color, but just checking it where it is right now I see this:
Query-Loop-Modal

The jumping movements (at the end of the carousel) of the left and right arrows have been removed.
I do though see a grey border area on the right and bottom (just below the patterns), and this seems a bit out of place.

**Comment by jameskoster** [comment]
> I do though see a grey border area on the right and bottom (just below the patterns), and this seems a bit out of place.

I think that might be the double-scrollbar issue that @jorgefilipecosta fixed :)

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,
I also tested on [gutenberg.run](http://gutenberg.run/38997) and the issue is also not happening there:
image


Could you test on http://gutenberg.run/38997 and let me know if things worked?

**Comment by paaljoachim** [comment]
Or just use this method:
https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/
(That is what I use. It is an easy way to test.)

**Comment by paaljoachim** [comment]
I just tested gutenberg.run in Chrome. There I do not see the border I mentioned in my comment above.

This is what I see:
Screenshot 2022-04-08 at 14 14 02

Screenshot 2022-04-08 at 14 14 18

**Comment by jorgefilipecosta** [comment]
> I just tested gutenberg.run in Chrome. There I do not see the border I mentioned in my comment above.
> 
> This is what I see: Screenshot 2022-04-08 at 14 14 02
> 
> Screenshot 2022-04-08 at 14 14 18

The background of the site is white so the modal is also white. If you apply a background on the site editor for the site does the modal also gets that background color on the carousel view?

**Comment by paaljoachim** [comment]
In Twenty Twenty Two. Local test site running WP 5.9.3.
Going to the Site Editor I see this:

URL: https://full-site-editing.dev.cc/wp-admin/themes.php?page=gutenberg-edit-site&postType=page&postId=149
Fatal error: Uncaught Error: Class 'WP_Style_Engine_Gutenberg' not found in /Users/paaljoachimromdahl/Sites/full-site-editing.dev.cc/wp-content/plugins/gutenberg-query-block-pattern-modal/lib/block-supports/spacing.php on line 55

I have only have Autoptimize and Gutenberg PR build plugins activated.

**Comment by jorgefilipecosta** [comment]
> In Twenty Twenty Two. Local test site running WP 5.9.3. Going to the Site Editor I see this:
> 
> URL: [full-site-editing.dev.cc/wp-admin/themes.php?page=gutenberg-edit-site&postType=page&postId=149](https://full-site-editing.dev.cc/wp-admin/themes.php?page=gutenberg-edit-site&postType=page&postId=149) Fatal error: Uncaught Error: Class 'WP_Style_Engine_Gutenberg' not found in /Users/paaljoachimromdahl/Sites/full-site-editing.dev.cc/wp-content/plugins/gutenberg-query-block-pattern-modal/lib/block-supports/spacing.php on line 55
> 
> I have only have Autoptimize and Gutenberg PR build plugins activated.

Does that issue only happen on this PR? In this PR we are not touching on WP_Style_Engine_Gutenberg class or any PHP code at all.

**Comment by paaljoachim** [comment]
I am able to enter the Site editor:
When deactivating the Gutenberg PR build.
+
Installing and activating the standard Gutenberg plugin version 12.9.0

--

EDIT:
I downloaded another Gutenberg PR build to see if it would work this time, but the same fatal error is seen.

Screenshot 2022-04-08 at 14 45 16

**Comment by jameskoster** [comment]
I see the same issue on gutenberg.run:

Screenshot 2022-04-08 at 13 40 33

Where should the background be applied? I'm only seeing the `height` declaration on `.block-editor-block-pattern-setup__carousel` now 🤔

**Comment by paaljoachim** [comment]
I believe there is a problem in WP 5.9.3 as I have seen a similar problem with it elsewhere. (Gutenberg run has WP 5.9.2 installed.)

Anyhow. I used gutenberg run and see this when changing the global background color to green.

Screenshot 2022-04-08 at 14 47 36

It works for me.

**Comment by paaljoachim** [comment]
@jameskoster Is it a cache thing? (As in not showing the newest build.)

**Comment by jorgefilipecosta** [comment]
> I see the same issue on gutenberg.run:
> 
> Screenshot 2022-04-08 at 13 40 33
> 
> Where should the background be applied? I'm only seeing the `height` declaration on `.block-editor-block-pattern-setup__carousel` now 🤔

Now we are applying the background by changing the height of the frame to cover all the modal.

I tried different browsers etc and things seemed to work but I found an issue with some screen resolutions. Maybe that was the issue @jameskoster was facing. @jameskoster could you do a new check and verify if the issue is gone?

**Comment by jameskoster** [comment]
That seems to have done the trick @jorgefilipecosta :)

The last thing I can see to fix is the flash of white between slides. It's particularly egregious when the patterns have a dark background:

https://user-images.githubusercontent.com/846565/162453747-0b3d67b3-7b30-4f18-bcbe-ea70fe8ebea0.mp4

I think I can fix that with css though. Watch this space :)

**Comment by jorgefilipecosta** [comment]
Thank you @jameskoster the flashing issue seems fixed 👍 
I guess we have an MVP ready?

**Comment by jameskoster** [comment]
Yes I think so 🚀

**Comment by gziolo** [comment]
This PR was cherry-picked for Gutenberg plugin release v13.0 and WordPress 6.0 Beta 1.

**Comment by jameskoster** [comment]
@jorgefilipecosta should we migrate this behaviour to the template part replacement flow as well? :)

**Comment by pablohoneyhoney** [comment]
A few notes on this one, apologies if late:


The interface now is optimizing for single/grid view, and the carousel UI (arrows) are downplayed (both visually and in location), perhaps it should be the other way around?

Have we tried to have only one bar that hosts all interactions in a single line avoiding the _sandwich_ effect? 

The toolbar says _Replace_, then the modal titles _Choose patterns_, and the button says _choose_. It sounds disconnected verbally. If we say _replace_, perhaps we title _Select another pattern_, and button _insert_?

**Comment by jameskoster** [comment]
Thanks @pablohoneyhoney, not too late at all – these are the kind of things we can refine in the run up to 6.0. I think this PR was mostly about migrating the existing interface from the canvas to a modal, and in that spirit we moved the actions to the bottom of the UI in order to be consistent with other modals.

Combining all interaction elements in a single row might be a tall order, but perhaps we could place the pagination arrows either side of the pattern, and remove the confirmation button in favor of a click on the pattern itself?


https://user-images.githubusercontent.com/846565/162930212-0ba48226-204f-4d2b-a8b6-38618a832119.mp4


I find the additional distance between back/forward arrows quite taxing on my wrist as a trackpad user, but perhaps it's worth the trade-off.

**Comment by jorgefilipecosta** [comment]
> @jorgefilipecosta should we migrate this behaviour to the template part replacement flow as well? :)

I'm not sure, I think the template part shows the patterns grouped by template part type, eg: header, footer etc.
But maybe if you are already in a header template part it makes sense?

**Comment by jorgefilipecosta** [comment]
Regarding the UI, I think the modal component does not support adding additional buttons there, but that is not a blocker if we want to add the button there we can look into ways to do it.
I'm happy to continue to iterate on this UI if we decide on what the next improvement should be.

**Comment by jameskoster** [comment]
> I'm not sure, I think the template part shows the patterns grouped by template part type, eg: header, footer etc.
But maybe if you are already in a header template part it makes sense?

I'm referring to this modal, which appears if you select a Template Part and click "Replace":

Screenshot 2022-04-13 at 08 47 08

It would benefit from the carousel / grid options, as well as the larger dimensions etc.

**Pull request merged**
