### PR TITLE
Button Block: Update to use color support utils to retrieve classes and styles

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## Description

This updates the button block to use a [new utility exported from the block support hooks](https://github.com/WordPress/gutenberg/pull/30869) to retrieve color related CSS classes and inline styles which are then applied to inner elements.

The original `color-props.js` function has been re-worked into the new utilities mentioned above.

## How has this been tested?

Manually and via `npm run test-unit` to ensure fixture tests still show the correct classes and styles being applied.

#### Test Instructions

1. Create a new post and add a button block to it
2. Adjust the button's colors via the inspector controls and check the button updates appropriately
3. Save the post and confirm the colors are correct on the frontend.
4. Run `npm run test-unit` and confirm no failures.

## Types of changes

Refactor. No new features, no breaking changes.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by oandregal** [comment]
It looks like mobile still uses the `packages/block-library/src/button/color-props.js` file, so we can't remove it. I've pushed a commit to revert its removal ― hope you don't mind, wanted to speed this up.

@geriux we're introducing a new utility for retrieving classes and inline styles at https://github.com/WordPress/gutenberg/pull/30869 Could any of you at mobile check that utility and remove `packages/block-library/src/button/color-props.js` at your convenience?

**Review by oandregal — APPROVED** [review]
I've noticed that there was a test failure due to removing `packages/block-library/src/button/color-props.js` that mobile still uses it so I reverted the removal of that file.

Other than that this is ready. Let's wait for tests to pass to merge this, in case I missed something.

**Comment by aaronrobertshaw** [comment]
> I've noticed that there was a test failure due to removing packages/block-library/src/button/color-props.js that mobile still uses it so I reverted the removal of that file.

Thanks, I saw that this morning. My mistake, I missed updating the native edit component.

I've just pushed a [commit](https://github.com/WordPress/gutenberg/pull/30870/commits/65c89757ce956a0e25bd9ae2424975c7fb026134) that updates the button edit component for mobile. As it is a class component the hook utility couldn't be used cleanly in place of the original function from `color-props`. Instead it uses the same utility as the button save function with a few extra tweaks to enforce colors when the theme doesn't load the color stylesheets in the editor. To do that I needed to retrieve available colors and gradients from settings via the component's `withSelect`.

In addition, the native button edit component was still relying on the withColors hook and therefore attributes that wouldn't match those provided by the colors support the button block opts into via the block.json. I believe the last commit brings the native component up-to-date in that respect.

With all the above changes, I deleted the `color-props.js` file again and it was working for me locally. I'm pretty new to the React Native side of things so a sanity check on the approach taken would be greatly appreciated! 🙏

**Comment by jd-alexander** [comment]
Hi @aaronrobertshaw I added the `Mobile App - i.e. Android or iOS`  label to this PR, so that Mobile Gutenberg folks can be notified of conversations here. @hypest @chipsnyder do we need to run any tests on our side for extra verification here?

**Comment by aaronrobertshaw** [comment]
> I added the mobile label to the PR, so Mobile Gutenberg folks can be notified of conversations here.

Thanks @jd-alexander, I'll keep that label in mind in future.

**Comment by geriux** [comment]
> @geriux we're introducing a new utility for retrieving classes and inline styles at #30869 Could any of you at mobile check that utility and remove `packages/block-library/src/button/color-props.js` at your convenience?

Will do! Thanks for the heads up!

**Comment by geriux** [comment]
> With all the above changes, I deleted the color-props.js file again and it was working for me locally. I'm pretty new to the React Native side of things so a sanity check on the approach taken would be greatly appreciated! 

Hey @aaronrobertshaw 👋  I'll run some sanity checks, thanks for updating the native files 🎉

**Comment by geriux** [comment]
Did some sanity checks and everything looks good on mobile 👍 

<kbd></kbd>

Thanks!

**Review by geriux — APPROVED** [review]
LGTM!

**Pull request merged**
