### PR TITLE
fix: Native inner blocks merge where appropriate

### LINKED ISSUE #44990: Removing empty List block with delete key fails, leads to iOS crash
## Description
When attempting to remove an empty List block by pressing the keyboard delete key, the block is not removed on Android and the app crashes on iOS. 

## Step-by-step reproduction instructions
1. Add a List block to the content. 
2. Pressing the <kbd>Delete</kbd> key. 

## Expected behaviour
The List block is removed and replaced with a Paragraph block. 

## Actual behaviour
**Android:** The List block is not removed nor replaced. 
**iOS:** The app crashes. 

## Screenshots or screen recording (optional)

<details><summary>Android Screencast</summary>

https://user-images.githubusercontent.com/438664/195932209-1e240670-9eb8-4532-8ead-981d00ba37d7.mp4

</details>

<details><summary>iOS Screencast</summary>

https://user-images.githubusercontent.com/438664/195932001-8622ac2e-d0a9-45f7-84f8-ac8f387ae587.MP4

</details>

## WordPress information
- WordPress version: 6.1
- Gutenberg version: 14.3.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Geologist

## Device information
- Device: Samsung Galaxy S20, iPhone SE
- Operating system: Android 12, iOS 16.1
- WordPress app version: [1.84.0](https://github.com/WordPress/gutenberg/releases/tag/rnmobile%2F1.84.0) or soon-to-be 20.10 beta

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?

Apply https://github.com/WordPress/gutenberg/pull/43181,  a recent web-based refactor for List merging, to the native components to avoid errors and crashes. The spirit of the web refactor was to improve the experience when interacting with List V2 blocks. 

## Why?

Fixes https://github.com/WordPress/gutenberg/issues/44990. Allows merging Lists into other Lists and unwrapping Lists when merging into non-Lists. 

## How?

Apply the changes from https://github.com/WordPress/gutenberg/pull/43181 to the sibling `packages/block-editor/src/components/block-list/block.native.js` file. Additionally, pass the required `onMerge` and `rootClienId` props down the tree to the relevant locations. 

## Testing Instructions

<details><summary>Sample Markup</summary>

```html
<!-- wp:paragraph -->
<p>A quick brown fox jumps over the lazy dog.</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>One</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>One</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Two</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Three</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>A quick brown fox jumps over the lazy dog.</p>
<!-- /wp:paragraph -->
```

</details>

From my research, mobile OS' do not support _forward_ delete, i.e. the <kbd>Delete</kbd> key rather than <kbd>Backspace</kbd> key. So, not every test criteria from https://github.com/WordPress/gutenberg/pull/43181 is applicable, and therefore are struck below. 

* Place the caret at the start of the first list and press Backspace. Should unwrap the list as well. Undo.
* ~Place the caret at the end of the first list and press Delete. Should merge the lists. Undo.~
* Place the caret at the start of the second list and press Backspace. Should merge the lists as well. Undo.
* ~Place the caret at the end of the second list and press Delete. Should merge the second paragraph with the list. Undo.~
* Place the caret at the start of the second paragraph and press Backspace. Should merge the second paragraph with the list as well.

## Screenshots or screencast 

https://user-images.githubusercontent.com/438664/196576888-6ffff4b4-fce1-44de-965c-4147974e9980.mov

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
I was able to reproduce the issue, and verify the fix from this PR. Nice work, LGTM! 🚀

**Comment by fluiddot** [comment]
I noticed that the [`End-to-End Tests Playwright / E2E Tests` PR check](https://github.com/WordPress/gutenberg/actions/runs/3278087608/jobs/5396976940) is not passing after multiple retries. However, I saw that this PR check is also failing in recent commits of `trunk`. Looks like [this PR](https://github.com/WordPress/gutenberg/pull/45087) already addresses it, so I'll update the PR with the latest changes from `trunk`.

**Comment by fluiddot** [comment]
> Apply the changes from https://github.com/WordPress/gutenberg/pull/43181 to the sibling packages/block-editor/src/components/block-list/block.native.js file. Additionally, pass the required onMerge and rootClienId props down the tree to the relevant locations.

Not for this PR but I'm wondering if we could extract the logic within the `onMerge` function so we don't need to duplicate it in the native file.

**Comment by fluiddot** [comment]
> I noticed that the [`End-to-End Tests Playwright / E2E Tests` PR check](https://github.com/WordPress/gutenberg/actions/runs/3278087608/jobs/5396976940) is not passing after multiple retries. However, I saw that this PR check is also failing in recent commits of `trunk`. Looks like [this PR](https://github.com/WordPress/gutenberg/pull/45087) already addresses it, so I'll update the PR with the latest changes from `trunk`.

Solved ✅  after updating the PR with the latest changes from `trunk` branch.

**Comment by ndiego** [comment]
Hi all, does this fix need to backported to 6.1?

**Comment by fluiddot** [comment]
> Hi all, does this fix need to backported to 6.1?

Hey @ndiego, thanks for the heads up 🙇. AFAIK, this PR only updates files of the native version (i.e. files with extension `.native.js`), so we wouldn't need to include it in the web version and version 6.1.

**Comment by dcalhoun** [comment]
> Not for this PR but I'm wondering if we could extract the logic within the `onMerge` function so we don't need to duplicate it in the native file.

@fluiddot I agree. I considered this as well, and it reinforced my concerns about the diverges of web and native components. For this specific case, merely abstracting `onMerge` may be appropriate. At a higher level, I'd like to consider how we avoid splitting _entire_ (`edit`) modules to start — hopefully we could identify better composition to avoid this type of issue. 

> Hi all, does this fix need to backported to 6.1?

@ndiego thanks for checking! The native editor has its own, separate release cycle. I do not believe the code changes here impact the web editor and therefore do not need to be considered for a specific web editor release.

**Comment by ndiego** [comment]
Ok cool, thanks for the clarification!

**Comment by fluiddot** [comment]
> @fluiddot I agree. I considered this as well, and it reinforced my concerns about the diverges of web and native components. For this specific case, merely abstracting onMerge may be appropriate. At a higher level, I'd like to consider how we avoid splitting entire (edit) modules to start — hopefully we could identify better composition to avoid this type of issue.

@dcalhoun I totally agree. Ideally, we should only have one `edit` module for both versions (i.e. web and native) in each block, and the logic of the block split into smaller modules. This way we could apply the tweaks required for the native version on the specific files, avoiding code duplication and potentially missing fixes applied in the web version.

This is definitely a challenge as it can be tricky to follow this structure across the Gutenberg codebase. Nevertheless, a huge improvement in getting both versions closer in terms of logic. One part that will be particularly complex to tackle is the rendering since the markup and elements used in each version usually differ.

**Comment by dcalhoun** [comment]
> One part that will be particularly complex to tackle is the rendering since the markup and elements used in each version usually differ.

Indeed. I feel https://github.com/WordPress/gutenberg/issues/18018 is somewhat related to this subject, and opens discussion on how we compose markup/styles. 

> [...] avoiding code duplication and potentially missing fixes applied in the web version.

Yep, an example is already showcasing itself where https://github.com/WordPress/gutenberg/pull/45075, a continuation of this PR's origin, should be applied to native as well.

**Comment by fluiddot** [comment]
> Yep, an example is already showcasing itself where #45075, a continuation of this PR's origin, should be applied to native as well.

Good point, let's follow up on that PR to include it in the native version once it's merged 👍 .

**Pull request merged**
