### PR TITLE
Add Hero1 block pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a Hero section block pattern for #20345.

**⚠️ Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.**

75184492-11e91980-570a-11ea-92e5-c0d31f4a2682

```
<!-- wp:group {"backgroundColor":"very-light-gray","align":"full"} -->
<div class="wp-block-group alignfull has-very-light-gray-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"textColor":"very-dark-gray"} -->
<h2 class="has-very-dark-gray-color has-text-color">Lorem ipsum sit amet, consectetur adipiscing elit</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"very-dark-gray","fontSize":"medium"} -->
<p class="has-text-color has-medium-font-size has-very-dark-gray-color">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"strong-blue","borderRadius":2} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background has-strong-blue-background-color" style="border-radius:2px">Call to action</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":306,"width":512,"height":384,"sizeSlug":"large","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/swinging-1024x768.png" alt="" class="wp-image-306" width="512" height="384"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->
```

### CODE REVIEW

**Comment by youknowriad** [comment]
Oh something else we should avoid using in patterns are "theme specific colors" (the ones from the palette) because these don't translate properly between themes.

**Comment by enriquesanchez** [comment]
>we should avoid using in patterns are "theme specific colors" (the ones from the palette) because these don't translate properly between themes.

@youknowriad Oh, I was not aware of this! So custom colors are preferred then? I was under the impression that the previews would match the look and feel of the current theme, just like block previews do right now.

**Comment by youknowriad** [comment]
Ideally, we avoid opinionated colors entirely I think. Something like `has-very-light-gray-background-color`  className won't work unless the theme has that color in its palette. 

So yeah, if we really need colors and can't just accept the default ones, it's probably better to go with custom ones for now.

**Comment by enriquesanchez** [comment]
@youknowriad what about things such as `has-medium-font-size`? Should those class names also be removed?

**Comment by youknowriad** [comment]
Potentially, though most themes do share the same font sizes names.

**Comment by enriquesanchez** [comment]
> Potentially, though most themes do share the same font sizes names.

@youknowriad Ok, I think it'll be important to clarify all of these requirements and constraints. For now I'll continue adding these PRs and will watch out for color-specific class names.

**Comment by enriquesanchez** [comment]
Closing since we've decided to go with text-only patterns.

**Pull request closed without merging**
