### PR TITLE
Template Part: Improve title editing interactions.

### PR DESCRIPTION
**Pull request by epiqueras**
## Description

This PR makes two changes:

- Template Part: Select all text on name panel focus.
So that it is easy to replace the initial title.

- Core Data: Use the edited entity record for the multi-entity saving panel.
So that edited titles are reflected in the panel's list.

## How has this been tested?

It was verified that the changes described above are applied.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by MichaelArestad** [comment]
So much better!
image

**Review by ZebulanStanphill — APPROVED** [review]
Just to be clear, this does _not_ fix #24000, in case anyone was wondering. (Notably, that issue only occurs with Template Parts that have already been saved.)

Anyway, I tested this branch and it's definitely an improvement over `master`, so I'm approving this.

**Comment by ZebulanStanphill** [comment]
Actually, it looks like the bug doesn't even happen with new Template Parts _after_ they're saved (and you refresh the page). I'm actually not sure what exactly causes the bug to occur, but I can consistently reproduce it with the Header template part provided by the demo templates.

**Comment by Addison-Stavlo** [comment]
> but I can consistently reproduce it with the Header template part provided by the demo templates.

Oh?  Maybe it is specific to the demo templates?  If you turn the demo templates off and use a block based theme are you able to reproduce the same bug with the template parts the theme provides?  (It may also require cleaning the environment to test this, I have had some odd issues after switching away from demo-templates in the past).

**Comment by ZebulanStanphill** [comment]
@Addison-Stavlo It still happens with block based themes. I think it may have something to do with the difference between theme-provided template parts and user-created ones?

Let's continue this discussion in #24000, if necessary.

**Pull request merged**
