### PR TITLE
Polish the Site Logo block.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This PR takes a stab at a few of the items from #30406. Specifically it:

1. Improves the description in the block sidebar.
2. Sets a default (until resized) width of 120px.
3. Polishes the placeholder state to work well in the small size.

I could use advice on the description in the sidebar, is it precise enough? 

Note that for 2, I entirely removed the "Logo width" range control in the sidebar. It seemed duplicate compared to the control that exists in the canvas itself, and it was problematic insofar as it showed the image dimensions even when you hadn't explicitly set the width of the image at all (and was therefore subject to theme styles). Is there any reason to keep that control that I'm missing?

## How has this been tested?

Test inserting a site logo, test setting it, and that it looks correct in editor and frontend.

Then try resizing the site logo and check that also looks good.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jameskoster** [comment]
Works for me.

I wonder if the description can be simplified a little, taking cues from the Site Title block?

> Displays and enables editing of the site logo.

---

> Is there any reason to keep that control that I'm missing?

Perhaps for devices or scenarios where dragging doesn't work so well?

**Comment by jasmussen** [comment]
> Perhaps for devices or scenarios where dragging doesn't work so well?

Doi, of course. I'll add it back and see what I can do. Probably if it's unset by default, it will be more accurate to the default size.

**Comment by paaljoachim** [comment]
Hey Joen. It looks like I am not able to build a special Gutenberg plugin by going to the Checks tab -> looking in the left sidebar for Gutenberg Build. It would be nice to see a screenshot (or to test it).

I checked the code. Sidebar description says this:
"Allows you to define a logo to be used across your site. Once defined, changing it in one template will change it in all places where it's used as well."

That feels like a good and clear description.

**Comment by jasmussen** [comment]
Ack, sorry about that. I had taken before and after screenshots, and somehow I forgot to paste them in here! Here's before:

Screenshot 2021-04-07 at 08 30 46

Here's after:

Screenshot 2021-04-07 at 08 29 54

_Note that being centered is a bug in my theme, not a bug with the block._

Here's the drag and drop zone:

dragondrop

I'll work to restore the width in the inspector now.

**Comment by jasmussen** [comment]
Addressed the feedback:

status

**Comment by jameskoster** [comment]
In terms of the changes proposed in the OP this works well.

There's something about that placeholder state though... In the future I wonder if it wouldn't be better to programatically generate a "logo" and insert that. Consequently the thing a user sees after inserting the Site Logo block feels a bit more logo-ish. Does that make sense? Replacing it is just a case of using the already-familiar image tools.

logo

**Comment by jasmussen** [comment]
I don't disagree. But in the name of moving us onward from this:



... do you think maybe this PR could serve as a starting point?

**Review by jameskoster — APPROVED** [review]
Yes. Sorry I forgot to write that comment as a review!

**Comment by jasmussen** [comment]
I do love the idea that we can auto-generate a logo based on site properties. Want to ticket it, or at least suggest it in a comment on #30406? Thanks for the review, I'm going to land this one.

**Comment by paaljoachim** [comment]
Does it have an upload media link?

**Comment by jasmussen** [comment]
Yes, inside the media library.

**Comment by paaljoachim** [comment]
Of course..:)
Good point.

**Pull request merged**
