### PR TITLE
Image Block: add caption field to placeholder

### LINKED ISSUE #22294: Possibility to fill out caption before image upload
Sometimes, I'd like to write a page and lay it out before uploading images. It would be nice if I could fill out caption in image placeholders before uploading the images. It also lets me remember what to upload as the caption is a clue.

I realise this may conflict with inserting an image from the media library that already has a caption, but imo the caption written in the block should then be kept.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #22294.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
This behavior has been raised here as problematic https://github.com/WordPress/gutenberg/pull/21252#issuecomment-640184810 

It did seem a bit unexpected for me too. I'm on the fence.

**Comment by ellatrix** [comment]
Why is it problematic? It seems like the question raised is whether it can be moved to the top

**Comment by ellatrix** [comment]
Placeholders were added to Gutenberg so you could fill create and fill out some content while leaving other places black to fill in later. I believe this fits that vision?

**Comment by RickorDD** [comment]
Can we talk about this again in the next core-editor meeting next Wednesday?

**Pull request merged**
