### PR TITLE
Fix for #36523: Unable to drag patterns in Safari

### LINKED ISSUE #36523: Unable to insert Patterns using Safari by drag and dropping them
### Description

Inserting a pattern by drag and dropping it from the sidebar inserter doesn't work in Safari.

I was able to insert patterns this way using both Firefox and Chrome on a mac.

### Step-by-step reproduction instructions

Using Safari:

1. Go to the Site Editor.
2. Open the block inserter from the top bar.
3. Open the Patterns tab bar.
4. Try to drag a Pattern into the canvas.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/4933/142012599-588bc4a0-70fb-46c8-85d8-b2276e342886.mp4

### Environment info

- WordPress 5.8.2, Gutenberg 11.9.0, TT1 Blocks.
- Mac with bigSur 11.6
- Safari 15.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jorgecontreras**
## Description

Fixes issue: Unable to insert Patterns using Safari by drag and dropping them.

The problem was caused by the positioning of the iFrame that renders the Pattern preview, which was on top of the draggable div element. Most browsers handled it well, but not Safari. To solve this, a new draggable div element was created and placed on top of the iFrame.

## How has this been tested?
Using Safari:

1. Go to the Site Editor.
2. Open the block inserter from the top bar.
3. Open the Patterns tab bar.
4. Confirm ability to drag a Pattern into the canvas.

Repeated the steps above with Google Chrome, Firefox and Brave browsers.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by javierarce** [comment]
Thanks for this fix, @jorgecontreras! I was able to drag patterns using Safari and it keeps working for other browsers (I tested it with Firefox, and Chrome for macOS)

**Comment by jorgecontreras** [comment]
> Thanks for this fix, @jorgecontreras! I was able to drag patterns using Safari and it keeps working for other browsers (I tested it with Firefox, and Chrome for macOS)

Thanks for confirming on your end @javierarce. I am going through the e2e tests, because some of them seem to have failed. Checking if we need to update the snapshots... will keep you guys posted.

**Comment by talldan** [comment]
Thanks for the PR @jorgecontreras. It looks like a lot of the end to end test failures were because of a 404 result from an HTTP request, which I don't think your changes would have caused. It could be that there was an issue with the environment, or something was fixed in `trunk` at some point after your PR was created.

I'd recommend rebasing the branch against trunk and pushing to see if that changes the results.

**Comment by Mamaduka** [comment]
Hi, @jorgecontreras

I just wanted to do a quick follow-up on this PR. As Daniel mentioned rebasing on top of the current trunk might fix most of the issues with E2E tests.

**Comment by jorgecontreras** [comment]
> Hi, @jorgecontreras
> 
> I just wanted to do a quick follow-up on this PR. As Daniel mentioned rebasing on top of the current trunk might fix most of the issues with E2E tests.

Hi @Mamaduka I did rebase the branch and closed this PR. I then opened this PR instead: https://github.com/WordPress/gutenberg/pull/37308, E2E tests keep failing. I ran a few of them in my local and they pass, not sure what I am missing.

**Pull request closed without merging**
