### PR TITLE
Potential fix for embed space: move styles to theme.scss

### LINKED ISSUE #10109: Giant space above all Youtube video in Posts
**Describe the bug**
Giant space above all Youtube video when VIEWING Posts in Gutenberg: Version 3.9.0

**To Reproduce**
1. Go to 'ALL POSTS.'
2. Click on 'EDIT'  A POST YOU KNOW HAS A YOUTUBE VIDEO
3. Scroll down to 'YOUTUBE VIDEO BLOCK'
4. You CAN'T SEE the error in the actual Post Edit, but you can see the giant space when VIEWING the post.

**Expected behavior**
There should be reasonable space around the Youtuve video.

**Screenshots**
error - space above youbue video

**Desktop (please complete the following information):**
 - OS: WINDOWS 10
 - Browser CHROME
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
Latest version of Gutenberg: Version 3.9.0

### PR DESCRIPTION
**Pull request by jasmussen**
This PR fixes #10109.

But it does so in a semi-nuclear way, by removing the responsiveness by default, and making it something a theme author has to opt into by opting into Gutenberg "opinionated" styles. This might be the solution we go with, hence this PR, but I would love for us to consider it a "Plan B" while we explore better solutions.

### CODE REVIEW

**Comment by notnownikki** [comment]
This makes me sad because it works so nicely for themes that don't have their own support...

I've been thinking about a block level toggle for responsiveness, so that if you're using a wide theme and embedding narrow videos you could tell it not to make them wide and ultra tall. I think we should do that anyway, but I'm not sure if it would be an acceptable solution for this too.

**Comment by jasmussen** [comment]
> I've been thinking about a block level toggle for responsiveness, so that if you're using a wide theme and embedding narrow videos you could tell it not to make them wide and ultra tall. I think we should do that anyway, but I'm not sure if it would be an acceptable solution for this too.

If we were to make a toggle, the thing we'd want to toggle off is the percentage padding hack that we use to create CSS responsiveness. This is what was causing the issue in #10109, becuase that theme already used the same hack, tied to different markup, to achieve responsiveness. 

I agree this would be a bummer, and I hope we can think of other solutions.

**Comment by chrisvanpatten** [comment]
I don't love this either, but as a plan B it makes sense.

I think it's worth waiting a bit though. So far we only have one reported theme that conflicts. If there's evidence the problem is more widespread maybe we could revisit, but as of right now it feels a bit like we'd be throwing the baby out with the bathwater to accommodate one case.

**Comment by notnownikki** [comment]
I think it's worth doing the block level opt out _anyway_, because if you're embedding 9:16 ratio videos on a wide theme, then you might want to opt those out.

And if code changes can't work around this, and it's a problem on multiple themes, then a new media option that opts out of gutenberg responsiveness site-wide might be best?

**Comment by jasmussen** [comment]
> I think it's worth doing the block level opt out anyway, because if you're embedding 9:16 ratio videos on a wide theme, then you might want to opt those out.

🤘

That's pretty baller to do, though.

So that sounds like a "Make video responsive [on/off]" toggle, that defaults to on? I think this would be a good feature.

**Comment by notnownikki** [comment]
> So that sounds like a "Make video responsive [on/off]" toggle, that defaults to on?

Exactly! I have some updates to the category list to do, them I'm going to start on that.

**Comment by jasmussen** [comment]
Closing this for now, in favor of #10477.

**Pull request closed without merging**
