### PR TITLE
Fix error related to Appium when installing dependencies in NPM version 7.5.2

### PR DESCRIPTION
**Pull request by fluiddot**
Addresses https://github.com/WordPress/gutenberg/issues/28834

## Description

Running `npm install` with NPM version `7.5.2` produces the following error:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path <WORKSPACE_DIR>/gutenberg/node_modules/appium/node_modules/.bin/authorize-ios
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '<WORKSPACE_DIR>/gutenberg/node_modules/appium/node_modules/.bin/authorize-ios'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     <HOME_DIR>/.npm/_logs/2021-02-08T11_26_48_383Z-debug.log
```

## How has this been tested?

1. Install latest NPM version `7.5.2` (with NVM: `nvm install --latest-npm`)
2. Run `npm install`

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ockham** [comment]
I've merged https://github.com/WordPress/gutenberg/pull/28824, will rebase this PR now.

**Comment by ockham** [comment]
BTW @fluiddot, I'm not really seeing any errors/warnings about the `git+ssh` protocol issues that you mentioned in https://github.com/WordPress/gutenberg/pull/28824#issuecomment-775249989 :thinking: 

Instead, I'm still getting the other error (about `chmod 'gutenberg/node_modules/appium/build/lib/main.js'`):

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path gutenberg/node_modules/appium/build/lib/main.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod 'gutenberg/node_modules/appium/build/lib/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by fluiddot** [comment]
> BTW @fluiddot, I'm not really seeing any errors/warnings about the `git+ssh` protocol issues that you mentioned in [#28824 (comment)](https://github.com/WordPress/gutenberg/pull/28824#issuecomment-775249989) 🤔
> 
> Instead, I'm still getting the other error (about `chmod 'gutenberg/node_modules/appium/build/lib/main.js'`):
> 
> ```
> npm ERR! code ENOENT
> npm ERR! syscall chmod
> npm ERR! path gutenberg/node_modules/appium/build/lib/main.js
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, chmod 'gutenberg/node_modules/appium/build/lib/main.js'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> ```

Yeah I had that too, I'm not sure what's causing it, the only way I got it fixed was by running `npm install` with `npm@6` and then switch to `npm@7`. After that even removing the `node_modules` folder and installing all dependencies again worked.

I though that it could be related to the new `package-lock` format, are you having this error with the changes from this branch?

**Comment by fluiddot** [comment]
Regarding the errors with `git+ssh`, this is only happening on CI jobs ([an example](https://github.com/WordPress/gutenberg/pull/28849/checks?check_run_id=1856842454)), I think it can't be reproduced locally.

There's an [opened issue](https://github.com/npm/cli/issues/2610) on `npm/cli` repository about this.

**Comment by fluiddot** [comment]
I checked in the NPM 7 release post that now `npm install` will always resolve dependencies with `git+ssh`:

From ["Changes in npm v7"](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major):
> Git dependencies on known git hosts (GitHub, BitBucket, etc.) will always attempt to fetch package contents from the relevant tarball CDNs if possible, falling back to git+ssh for private packages. **resolved value in package-lock.json will always reflect the git+ssh url value**. Saved value in package.json dependencies will always reflect the canonical shorthand value.

Unless we find a workaround for this, one option would be to update the CI workflows so they have access by SSH to the forks.

**Comment by ockham** [comment]
> I checked in the NPM 7 release post that now `npm install` will always resolve dependencies with `git+ssh`:
> 
> From ["Changes in npm v7"](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major):
> 
> > Git dependencies on known git hosts (GitHub, BitBucket, etc.) will always attempt to fetch package contents from the relevant tarball CDNs if possible, falling back to git+ssh for private packages. **resolved value in package-lock.json will always reflect the git+ssh url value**. Saved value in package.json dependencies will always reflect the canonical shorthand value.
> 
> Unless we find a workaround for this, one option would be to update the CI workflows so they have access by SSH to the forks.

Hmm, still sounds like a bug to me. I mean `npm` is now part of GitHub, certainly they should make sure that an `npm` upgrade won't break GitHub Actions workflows that attempt to fetch `npm` dependencies from GitHub? :thinking:

**Comment by ockham** [comment]
> > BTW @fluiddot, I'm not really seeing any errors/warnings about the `git+ssh` protocol issues that you mentioned in [#28824 (comment)](https://github.com/WordPress/gutenberg/pull/28824#issuecomment-775249989) thinking
> > Instead, I'm still getting the other error (about `chmod 'gutenberg/node_modules/appium/build/lib/main.js'`):
> > ```
> > npm ERR! code ENOENT
> > npm ERR! syscall chmod
> > npm ERR! path gutenberg/node_modules/appium/build/lib/main.js
> > npm ERR! errno -2
> > npm ERR! enoent ENOENT: no such file or directory, chmod 'gutenberg/node_modules/appium/build/lib/main.js'
> > npm ERR! enoent This is related to npm not being able to find a file.
> > npm ERR! enoent 
> > ```
> 
> Yeah I had that too, I'm not sure what's causing it, the only way I got it fixed was by running `npm install` with `npm@6` and then switch to `npm@7`. After that even removing the `node_modules` folder and installing all dependencies again worked.
> 
> I though that it could be related to the new `package-lock` format, are you having this error with the changes from this branch?

Ah! Seems like I don't! I removed my `node_modules` (and `packages/*/node_modules`), checked out this branch, enabled node 14 + npm 7, and was able to run `npm i` :tada:

I'm getting a `package-lock.json` diff from that tho -- with the `git+https` -> `git+ssh` changes :grimacing: 

```diff
diff --git a/package-lock.json b/package-lock.json
index 1fb46604ba..379e505aaf 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -72915,11 +72915,11 @@
 			"integrity": "sha512-ng6Tm537E/M42GjE4TRUxQyL8sRfClcL7bQWblOCoxPZzJ2J3bdALsjeG3vDnVCIfI/R0AeFalN9KjMt0+Z/Zg=="
 		},
 		"@react-native-community/masked-view": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-masked-view.git#f65a51a3320e58404d7f38d967bfd1f42b439ca9",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-masked-view.git#f65a51a3320e58404d7f38d967bfd1f42b439ca9",
 			"from": "@react-native-community/masked-view@git+https://github.com/wordpress-mobile/react-native-masked-view.git#f65a51a3320e58404d7f38d967bfd1f42b439ca9"
 		},
 		"@react-native-community/slider": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-slider.git#d263ff16cdd9fb7352b354342522ff030f220f42",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-slider.git#d263ff16cdd9fb7352b354342522ff030f220f42",
 			"from": "@react-native-community/slider@git+https://github.com/wordpress-mobile/react-native-slider.git#d263ff16cdd9fb7352b354342522ff030f220f42"
 		},
 		"@react-navigation/core": {
@@ -103911,7 +103911,7 @@
 			}
 		},
 		"jsdom-jscore-rn": {
-			"version": "git+https://git@github.com/iamcco/jsdom-jscore-rn.git#a562f3d57c27c13e5bfc8cf82d496e69a3ba2800",
+			"version": "git+ssh://git@github.com/iamcco/jsdom-jscore-rn.git#a562f3d57c27c13e5bfc8cf82d496e69a3ba2800",
 			"from": "jsdom-jscore-rn@git+https://github.com/iamcco/jsdom-jscore-rn.git#a562f3d57c27c13e5bfc8cf82d496e69a3ba2800",
 			"requires": {
 				"htmlparser2-without-node-native": "^3.9.2",
@@ -113333,7 +113333,7 @@
 			}
 		},
 		"react-native-dark-mode": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-dark-mode.git#f09bf1480e7b34536413ab3300f29e4375edb2c6",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-dark-mode.git#f09bf1480e7b34536413ab3300f29e4375edb2c6",
 			"from": "react-native-dark-mode@git+https://github.com/wordpress-mobile/react-native-dark-mode.git#f09bf1480e7b34536413ab3300f29e4375edb2c6",
 			"requires": {
 				"@types/events": "^3.0.0",
@@ -113351,7 +113351,7 @@
 			}
 		},
 		"react-native-gesture-handler": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-gesture-handler.git#b80e959908b383a26d6e35d992d6d529efad0b16",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-gesture-handler.git#b80e959908b383a26d6e35d992d6d529efad0b16",
 			"from": "react-native-gesture-handler@git+https://github.com/wordpress-mobile/react-native-gesture-handler.git#b80e959908b383a26d6e35d992d6d529efad0b16",
 			"requires": {
 				"@egjs/hammerjs": "^2.0.17",
@@ -113361,14 +113361,14 @@
 			}
 		},
 		"react-native-get-random-values": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-get-random-values.git#f03f2c16414aff4ea76064dcd00a9e3c6efc838d",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-get-random-values.git#f03f2c16414aff4ea76064dcd00a9e3c6efc838d",
 			"from": "react-native-get-random-values@git+https://github.com/wordpress-mobile/react-native-get-random-values.git#f03f2c16414aff4ea76064dcd00a9e3c6efc838d",
 			"requires": {
 				"fast-base64-decode": "^1.0.0"
 			}
 		},
 		"react-native-hr": {
-			"version": "git+https://git@github.com/Riglerr/react-native-hr.git#2d01a5cf77212d100e8b99e0310cce5234f977b3",
+			"version": "git+ssh://git@github.com/Riglerr/react-native-hr.git#2d01a5cf77212d100e8b99e0310cce5234f977b3",
 			"from": "react-native-hr@git+https://github.com/Riglerr/react-native-hr.git#2d01a5cf77212d100e8b99e0310cce5234f977b3"
 		},
 		"react-native-hsv-color-picker": {
@@ -113385,7 +113385,7 @@
 			"integrity": "sha512-+/bcZWFeZt0xSS/+3CHM5K7qPL4vDO/3ARLIowzFpUPGZiPsv9+NET+XNqqseRYwFJwYMmtX+Q4TZKxAVy09ew=="
 		},
 		"react-native-keyboard-aware-scroll-view": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view.git#678a4d459caa2f7f448202574dddc6a19954500c",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view.git#678a4d459caa2f7f448202574dddc6a19954500c",
 			"from": "react-native-keyboard-aware-scroll-view@git+https://github.com/wordpress-mobile/react-native-keyboard-aware-scroll-view.git#gb-v0.8.8",
 			"requires": {
 				"prop-types": "^15.6.2",
@@ -113393,7 +113393,7 @@
 			}
 		},
 		"react-native-linear-gradient": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-linear-gradient.git#52bf43077171cff8714ce3e0155f3ebb7f55bc37",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-linear-gradient.git#52bf43077171cff8714ce3e0155f3ebb7f55bc37",
 			"from": "react-native-linear-gradient@git+https://github.com/wordpress-mobile/react-native-linear-gradient.git#52bf43077171cff8714ce3e0155f3ebb7f55bc37"
 		},
 		"react-native-modal": {
@@ -113406,7 +113406,7 @@
 			}
 		},
 		"react-native-reanimated": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-reanimated.git#ed48f510fba751cd75da7629e92276166766be91",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-reanimated.git#ed48f510fba751cd75da7629e92276166766be91",
 			"from": "react-native-reanimated@git+https://github.com/wordpress-mobile/react-native-reanimated.git#ed48f510fba751cd75da7629e92276166766be91",
 			"requires": {
 				"fbjs": "^1.0.0"
@@ -113443,7 +113443,7 @@
 			}
 		},
 		"react-native-safe-area-context": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-safe-area-context.git#1e3c0d34f31b59fb79f71ec0b4c39c513f684871",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-safe-area-context.git#1e3c0d34f31b59fb79f71ec0b4c39c513f684871",
 			"from": "react-native-safe-area-context@git+https://github.com/wordpress-mobile/react-native-safe-area-context.git#1e3c0d34f31b59fb79f71ec0b4c39c513f684871"
 		},
 		"react-native-sass-transformer": {
@@ -113464,11 +113464,11 @@
 			}
 		},
 		"react-native-screens": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-screens.git#b3d907bda2695743f35fd874261dcd27e0912eca",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-screens.git#b3d907bda2695743f35fd874261dcd27e0912eca",
 			"from": "react-native-screens@git+https://github.com/wordpress-mobile/react-native-screens.git#b3d907bda2695743f35fd874261dcd27e0912eca"
 		},
 		"react-native-svg": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-svg.git#a628e92990a2404e30a0086f168bd2b5b7b4ce96",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-svg.git#a628e92990a2404e30a0086f168bd2b5b7b4ce96",
 			"from": "react-native-svg@git+https://github.com/wordpress-mobile/react-native-svg.git#a628e92990a2404e30a0086f168bd2b5b7b4ce96",
 			"requires": {
 				"css-select": "^2.0.2",
@@ -113550,7 +113550,7 @@
 			}
 		},
 		"react-native-video": {
-			"version": "git+https://git@github.com/wordpress-mobile/react-native-video.git#1b964b107863351ed744fc104d7952bbec3e2d4f",
+			"version": "git+ssh://git@github.com/wordpress-mobile/react-native-video.git#1b964b107863351ed744fc104d7952bbec3e2d4f",
 			"from": "react-native-video@git+https://github.com/wordpress-mobile/react-native-video.git#1b964b107863351ed744fc104d7952bbec3e2d4f",
 			"requires": {
 				"prop-types": "^15.5.10"
```

**Comment by ockham** [comment]
We might try setting `persist-credentials` to `false` for our checkout actions, see https://stackoverflow.com/a/62124409 :thinking:

**Comment by ockham** [comment]
> We might try setting `persist-credentials` to `false` for our checkout actions, see https://stackoverflow.com/a/62124409

Trying in ceee13c056 for the unit test workflow :crossed_fingers:

**Comment by fluiddot** [comment]
> > We might try setting `persist-credentials` to `false` for our checkout actions, see https://stackoverflow.com/a/62124409
> 
> Trying in [ceee13c](https://github.com/WordPress/gutenberg/commit/ceee13c056ff7fb41c36c94e1df4e4e0465b0af7) for the unit test workflow 🤞

I'm afraid it still fails 😭 .

I was checking the [documentation](https://github.com/actions/checkout#usage) from `actions/checkout` and I think `persist-credential` should be `true` if we want to use the SSH key generated to fetch other repositories.

**Comment by ockham** [comment]
> I'm afraid it still fails 😭 .

Yeah, I saw that :confused: 

> I was checking the [documentation](https://github.com/actions/checkout#usage) from `actions/checkout` and I think `persist-credential` should be `true` if we want to use the SSH key generated to fetch other repositories.

That's the default setting I think (so that's what we've been implicitly trying prior to my change).
I actually did mean to _not_ use the SSH key, since those other repos are public, so they should be available without a key. That was my line of thinking at least -- we've now seen that that doesn't work either.

**Comment by fluiddot** [comment]
> That's the default setting I think (so that's what we've been implicitly trying prior to my change).

Right, I forced the value just in case but we should remove it since it's the default one.

> I actually did mean to _not_ use the SSH key, since those other repos are public, so they should be available without a key. That was my line of thinking at least -- we've now seen that that doesn't work either.

Yeah but even for public repos I think you need a SSH key if you checkout via SSH, I think that's the cause for the forked repos to fail in the CI.

In previous projects what I did was to have a GitHub user (like a Bot) with minimum permissions and add the SSH key as a secret to be used in the workflow. In that case it was required for private repos, I'm surprised that it could be required also for public ones 🤔 .

**Comment by fluiddot** [comment]
I've created an example repository for reproducing the problem with CI in an empty project.

The created repository is named [github-actions-test](https://github.com/fluiddot/github-actions-test) and only contains a [`package.json`](https://github.com/fluiddot/github-actions-test/blob/main/package.json) file that includes React, React native and one of dependencies that are causing CI to fail (`@react-native-community/masked-view`).

I created a [PR](https://github.com/fluiddot/github-actions-test/pull/1) that includes a simple workflow for testing NPM install. Unfortunately the [jobs](https://github.com/fluiddot/github-actions-test/pull/1/checks?check_run_id=1862251428) are failing with exactly the same error:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/wordpress-mobile/react-native-masked-view.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

Looks like that GitHub actions can't checkout repositories via SSH unless we explicitly add an SSH key for it. I found an [issue](https://github.com/actions/setup-node/issues/214) related to this in `actions/setup-node`.

I'm thinking about different solutions for this but all of them would imply to change the way we reference them, instead of using commit hash we should use versions and therefore create releases for each one. This way we could reference the tarball URL from the release or publish it to NPM.

Example of tarball URL:
```
"@react-native-community/masked-view": "https://github.com/wordpress-mobile/react-native-masked-view/archive/v0.1.10-wp.tar.gz",
```

**Comment by fluiddot** [comment]
By the time I was testing I spotted that there's a new version of [NPM `7.5.3`](https://github.com/npm/cli/releases/tag/v7.5.3) that fixes the problem of changing `git+https` urls to `git+ssh` 🎊.

**Comment by ockham** [comment]
> By the time I was testing I spotted that there's a new version of [NPM `7.5.3`](https://github.com/npm/cli/releases/tag/v7.5.3) that fixes the problem of changing `git+https` urls to `git+ssh` .

Yesss! That's great to hear!

(And TBH, from your description of the underlying issue and potential workarounds, this is the only solution that makes sense IMO -- People can't be assumed to suddenly add GitHub bots with minimum permissions just to be able to install npm dependencies because of an npm bug :sweat_smile: )

**Comment by ockham** [comment]
Anyway, I'll:
- Revert the unit test workflow changes.
- Try this again locally (with npm 7.5.3).
- If it works, I'll also revert the `git+https` -> `git+ssh` changes in the package lock, and will push those.
- If all goes well, the PR should then go green :crossed_fingers:

**Comment by fluiddot** [comment]
> > By the time I was testing I spotted that there's a new version of [NPM `7.5.3`](https://github.com/npm/cli/releases/tag/v7.5.3) that fixes the problem of changing `git+https` urls to `git+ssh` .
> 
> Yesss! That's great to hear!
> 
> (And TBH, from your description of the underlying issue and potential workarounds, this is the only solution that makes sense IMO -- People can't be assumed to suddenly add GitHub bots with minimum permissions just to be able to install npm dependencies because of an npm bug 😅 )

Yeah it didn't make sense for public repos. Now the problem I'm facing is that running `npm install` doesn't change the URL format from `git+ssh` to `git+https` if it's already included in the `package-lock.json` file. So I need to uninstall and install again those dependencies to leave the correct URL format 😅 .

**Comment by ockham** [comment]
> * If it works, I'll also revert the `git+https` -> `git+ssh` changes in the package lock, and will push those.

Ah I see you've already done that in ae4ee0c0c90cb4adb6d5593a840fbc186a14c262 :tada:

**Comment by ockham** [comment]
> Yeah it didn't make sense for public repos.

:+1: 

> Now the problem I'm facing is that running `npm install` doesn't change the URL format from `git+ssh` to `git+https` if it's already included in the `package-lock.json` file. So I need to uninstall and install again those dependencies to leave the correct URL format  .

Hmm, maybe it'd be easier to start from a clean slate (i.e. fresh branch) in that case?

**Comment by fluiddot** [comment]
> > Yeah it didn't make sense for public repos.
> 
> 👍
> 
> > Now the problem I'm facing is that running `npm install` doesn't change the URL format from `git+ssh` to `git+https` if it's already included in the `package-lock.json` file. So I need to uninstall and install again those dependencies to leave the correct URL format  .
> 
> Hmm, maybe it'd be easier to start from a clean slate (i.e. fresh branch) in that case?

Yep, I'm thinking to rebase this branch and start from scratch.

**Comment by ockham** [comment]
> Yep, I'm thinking to rebase this branch and start from scratch.

Not sure it's worth rebasing? Looking at the PR, there are basically only two changes we'd like to keep:
- The appium upgrade (which we need for npm 7 to work with this repo), and
- The npm 7 specific changes to `package-lock.json` (are there any? :grimacing: )

We might be able to file a new PR with the appium upgrade only (performed using npm 6). This should then unblock the npm 7 upgrade, which we could even do in a separate PR :thinking:

**Comment by fluiddot** [comment]
> Not sure it's worth rebasing? Looking at the PR, there are basically only two changes we'd like to keep:
> 
> * The appium upgrade (which we need for npm 7 to work with this repo), and
> * The npm 7 specific changes to `package-lock.json` (are there any? 😬 )

Yeah the reference for the dependencies with format `git+https` need to be updated to prevent NPM to change them to `git+ssh`.

> 
> We might be able to file a new PR with the appium upgrade only (performed using npm 6). This should then unblock the npm 7 upgrade, which we could even do in a separate PR 🤔

Yeah, makes sense to make it in two separate PRs, one for updating the `package-lock.json` file to version 2 and another one for the `appium` upgrade.

**Comment by fluiddot** [comment]
I'm closing this PR because this issue will be addressed with the following PRs:
- Update Appium dependency version to 1.20.2 #28890
- Update lock file format version to version 2 (NPM 7) #28886

This is the status of this fix so far:
## CI failures due to not having access to some repositories
This has been fixed in NPM version `7.5.3` and by updating the references of the forked dependencies from `react-native-editor` package.

## Dependencies install error
The original error related to https://github.com/WordPress/gutenberg/issues/28834 has been fixed by upgrading `appium` dependency, however a new error is now thrown quite similar but referencing a new file:
```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/runner/work/gutenberg/gutenberg/node_modules/appium/build/lib/main.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/runner/work/gutenberg/gutenberg/node_modules/appium/build/lib/main.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

I've created an [issue](https://github.com/appium/appium/issues/15095) in Appium repository just in case they can fix it, although this [issue](https://github.com/npm/cli/issues/2251) is already reported in `npm/cli`.

**Pull request closed without merging**
