### PR TITLE
Update: element/serialize.js inline svg attrs

### LINKED ISSUE #6441: Serialisation breaks namespaced attributes like `xlink:href`
## Issue Overview

In version 2.7.0 I'm seeing inline SVGs break that make use of the `xlink:href` attribute. It gets rewritten as `xlinkhref`.

## Steps to Reproduce (for bugs)

1. Create a block that outputs a tag from the `save` property with a namespaced attribute eg. `xlink:href`
2. Save the post
3. Check the markup when viewing the page, `xlink:href` is now `xlinkhref`

Chrome latest on OSX High Sierra.

## Expected Behavior

Namespaced attributes should be preserved.

## Current Behavior

Namespaced attributes are sanitised / serialised incorrectly.

## Possible Solution

Consider the need for `fast-react-render` lib based on it being deprecated.

Alternatively add support for known valid namespaced attributes and handle them in the `getNormalAttributeName()` function of `element/serialize.js`.

## Todos
- [x] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by roborourke**
## Description

Added support for namespaced inline SVG attributes.

Fixes: #6441 

## How has this been tested?

Checked the output on save and whether blocks were marked as valid after saving and reloading the editor.

Also extended the test for normalized attribute names.

## Types of changes

This is a bug fix that will only invalidate any existing blocks with the incorrect affected attributes.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by roborourke** [comment]
Let me know if this needs re-doing, have some additional CI stuff on our fork. A squash merge should at least hide it from the history.

**Comment by gziolo** [comment]
React has a quite long name, I guess we should double check more of those attributes listed in:
https://github.com/facebook/react/blob/9ff3ce67eaf07e8f62704133a8d748f1c0679a59/packages/react-dom/src/shared/possibleStandardNames.js

**Comment by roborourke** [comment]
To be fair the list of attributes to support manually isn’t that big.
Programmatic support just isn’t possible as it’s not consistent where
camelcase means hyphenation or no spaces, or indeed a colon. It should be
explicit. For the sake of a few hundred bytes this seems reasonable to me.

JSX and react handle this just fine, it’s the `fast-react-render` library
used in serialisation that’s broken.

**Comment by mcsf** [comment]
Note that I don't really have an opinion, but I felt those questions were worth asking. Unless @aduth would rather not, I'm OK merging this. And thanks for bringing the issue to our attention.

**Comment by roborourke** [comment]
Appreciate the feedback :) Will see what other cases won’t be covered by
the current solution and add those

**Comment by aduth** [comment]
I'm okay with the general idea of improving the compatibility with React, but I would love to know if there's actually a standard, specification, or general pattern that React is using to determine how to name these properties, so that we could guarantee completeness or leverage patterns where possible to improve future compatibility. There may be some inconsistency with camelcasing on attributes as a whole, but could we apply this to e.g. `xlink:`prefixed attributes? My worry is the maintenance burden with keeping a list up-to-date.

>JSX and react handle this just fine, it’s the `fast-react-render` library
>used in serialisation that’s broken.

To clarify, as I see it the only thing broken is compatibility with React. There's nothing I've seen demonstrated that React is strictly "correct" here, as many of these namings don't appear to have any basis in reality outside of React itself†.

† _I'm not stating this as fact, rather based merely on my current understanding. Am happy to be presented with corrections to the contrary._

**Comment by aduth** [comment]
>provide a guide to the DOM->HTML mapping the serialiser needs

This is fine. But to be clear, `xlinkHref` is not a DOM property, nor are any of the other properties currently included in the pull request. These names exist only within the realm of React.

**Comment by roborourke** [comment]
@aduth ahh I see, don't know if it caused some confusion but the attributes I've targeted here are specific to inline SVG markup which is valid in HTML. So not specific to React necessarily.

**Comment by aduth** [comment]
`xlink:href` is specific to inline SVG markup, and works perfectly well with the existing serializer:

```js
with ( wp.element ) {
    renderToString( createElement( 'svg', { 'xlink:href': 'https://example.com' } ) );
}
// "<svg xlink:href="https://example.com"></svg>"
```

`xlinkHref` _is_ specific to React.

**Comment by aduth** [comment]
I had to check it several times myself to make sure it wasn't 😄 In some ways I'd hoped there was some standard React was using for this naming, so we could base our implementation against that standard.

Ultimately, I think it would be good to have the compatibility, if only to avoid surprises from developers (such as yourself) who are led to believe they are targeting React, particularly when it works in the client-rendered variant. 

A good next step might be to identify the minimal set of these properties that React supports which won't be serialized well in our implementation. From there we can either determine to create a mapping, or generalized logic for converting.

**Comment by roborourke** [comment]
Digging in to this again and they've updated the list: https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/possibleStandardNames.js

It is really annoying though because React has support for custom attributes now! https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

So it's perhaps possible to drop this change altogether and recommend some approaches to using inline SVGs that don't transform the attributes. Specifically in my case I'm using `create-react-app`, `react-app-rewired` and `react-app-rewire-svg-react-loader`. I'll see if there's another / better solution for it.

**Comment by aduth** [comment]
Would be curious to see if we could hook in to [React's `getPropertyInfo`](https://github.com/facebook/react/blob/6a530e3baa9c44a509979c5d7013d4e1617cbc76/packages/react-dom/src/shared/DOMProperty.js#L178-L180) to be able to reference the most up-to-date property mappings. To my knowledge, this is not exposed on a public API, and would require either integrating to their internal source or maybe some build script to pregenerate the attributes mappings based on this file.

**Comment by aduth** [comment]
>It is really annoying though because React has support for custom attributes now! https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

This should work already with our serializer.

**Comment by aduth** [comment]
The `DOMProperty.js` file is interesting too because it highlights a few reserved prop names we're not really respecting in our implementation:

https://github.com/facebook/react/blob/6a530e3baa9c44a509979c5d7013d4e1617cbc76/packages/react-dom/src/shared/DOMProperty.js#L205-L217

**Comment by aduth** [comment]
Is it likely this will be resumed, or can it be closed?

**Comment by aduth** [comment]
I think this one will need more thought, so I'm going to opt to close the pull request in favor of its issue #6441. I'll post a status recap there shortly.

**Pull request closed without merging**
