### PR TITLE
Cancel left margin when full width block appender used at root level of layout

### LINKED ISSUE #33085: Unexpected margin left for block appender in widgets screen
## Description

There's a unexpected margin on the block list appender in the new Widgets screen.

## Step-by-step reproduction instructions

1. Go to Appearance -> Widgets
2. Look at the block list appender

## Expected behaviour

It should not have margins.

## Actual behaviour

It has a `8px` margin-left.

## Screenshots or screen recording (optional)

image

## WordPress information
- WordPress version:  master
- Gutenberg version:  trunk
- Are all plugins except Gutenberg deactivated?  Yes
- Are you using a default theme (e.g. Twenty Twenty-One)?  Yes

## Device information
- Device:  Desktop
- Operating system:  macOS
- Browser:  Brave (Chromium 91)

### PR DESCRIPTION
**Pull request by getdave**
## Description
This PR ensures that when a full width block appended is used at the root level of the block list then it doesn't have any left margin applied to it.

It looks like[ we've been tinkering with the block appended margins quite a bit](https://github.com/WordPress/gutenberg/commits/trunk/packages/block-editor/src/components/block-list-appender/style.scss) so it's obviously a thorny area.

This fixes https://github.com/WordPress/gutenberg/issues/33085

## How has this been tested?

I don't have a high degree of confidence in the test scenarios I'll need to run through but here's a start:

* Activate TT1.
* Go to Appearance -> Widgets
* Look at the block list appender - check there is no additional left margin.
* Also check full width appender that is used in the Group block.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by getdave** [comment]
@jasmussen I'd really appreciate your 👀 on this one as I expect there are a number of test scenarios I'll need to run through to ensure this change doesn't introduce any regressions.

**Comment by jasmussen** [comment]
Thanks for the PR.

I'm still investigating why the margin is there in the first place. It's also present, but cancelled out, in the block editor when inserting a Group block:

Screenshot 2021-06-30 at 10 59 33

Screenshot 2021-06-30 at 10 59 26

I feel like it's there for a reason, and if not, we can remove it entirely. But I'll dig a little deeper and get back to this one!

**Comment by jasmussen** [comment]
Okay, so here's why the left margin is there:

Screenshot 2021-06-30 at 11 03 12

so it _has_ to have an explicit left margin that isn't "auto", in order to work inside flex containers:

Screenshot 2021-06-30 at 11 03 52

But obviously when the big white plus button is used, that margin is useless. 

Let me look at whether there's a better way to cancel out that margin. The thing is, I'd like to remove that in-canvas inserter entirely, in favor of something that's abs-positioned/popovered, for some of the reasons outlined in #31886. So I'd love to find CSS that doesn't assume that black plus will exist forever, instead of overriding it.

**Comment by getdave** [comment]
We really need a way to distinguish between the "plus" appended and the full width one.

**Comment by jasmussen** [comment]
Yep, I'm looking into that now. `block-list-appender__toggle` is only used on the black plus, and `block-editor-button-block-appender` is the only remaining class on the white one.

I think there's an opportunity for a refactor, also in context of #33025, but let's find a small fix in the mean time. I shall return in a bit.

**Comment by jasmussen** [comment]
I have #33088 as an alternate fix.

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/33088

**Pull request closed without merging**
