### PR TITLE
WIP: absorb format boundaries into RichText toTree

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Related: #13153, #12973, #12978, #11091, #12966, #11178, #11276, #11743.

This PR adds boundary logic to the Rich Text package.

How is it done? Zero width non breaking spaces are being added in front of the text inside the format element, and in front of the text after the format element. These are used the trick the browser to move the caret next to them. This basic addition already fully enables inserting text in any position. Of course the zero width characters are only added to the editable tree, not the saved one.

Next, we look at the deepest selected format, which receives a class to style the selected element. To know the selected format, the state must have some additional information about which format is selected at a certain index. We need add an extra property to the value `selectedFormat`: `0` for outside, `1` for inside the first format, `2` for inside the second format, if any, etc. This information is derived from the DOM during `create`.

To do:

* Add `getActiveFormat` unit tests.
* Add boundary e2e tests.
* Fix failing e2e tests.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
It's still in progress, I'm removing it from 4.5 milestone.

**Comment by youknowriad** [comment]
First impressions: It seems to work fairly well.

Bug encountered for now: "Backspacing at the beginning of a paragraph with a format applied" don't merge blocks.

**Comment by youknowriad** [comment]
Another small bug but I believe this one is also an existing bug in master:

 - Try activating a format (italic) and start writing, the button is not set as active even if it is because if you start writing, it's indeed italic.
 - Try activating two formats and start writing, only the last one is applied.

**Comment by iseulde** [comment]
Closing in favour of #13697.

**Comment by iseulde** [comment]
@youknowriad That last issue you're describing is currently an issue as well I think. See #11743.

**Pull request closed without merging**
