### PR TITLE
Remove experimentalUIParts API

### PR DESCRIPTION
**Pull request by youknowriad**
This PR removes the experimentalUIParts API as this became useless with the G2 refactoring.

cc @ockham

### CODE REVIEW

**Comment by gziolo** [comment]
Do you know the initial commit that introduced it? It’d make it easier reviewing 😃

Code looks good but I might overlook something.

**Comment by Soean** [comment]
@gziolo https://github.com/WordPress/gutenberg/commit/cd015494bb5ac6bec044d55c799ce6be03f8bfa8

**Comment by youknowriad** [comment]
I'm merging this now, We can revert it if there's feedback suggesting it's still important.

**Comment by ockham** [comment]
Thanks @youknowriad! I haven't really kept up with G2, would you have any pointers as to how we can disable the block toolbar now? :sweat_smile: (That's what we were using `hasPopover` for.)

**Comment by sirreal** [comment]
A bit late. This is the first I'm coming across this after tracking it down as the cause of this issue: https://github.com/Automattic/wp-calypso/pull/42031#pullrequestreview-412541881

`hasPopover` was introduced in https://github.com/WordPress/gutenberg/pull/19922, which was added to support rendering a BlockList without a Block toolbar. I know it was an experimental API, but this will be a regression for our consuming application. We'll need to resort to CSS hiding the block toolbar in order to upgrade the block-editor package.

What were the motivations for removal? Can we restore this functionality?

**Comment by ockham** [comment]
I just chatted with @youknowriad. He told me that Gutenberg folks are generally opposed to keeping an experimental API that isn't used in the project itself and where the use-case is not very wide for third-party plugins.

He had an alternative suggestion though:

Hide the block toolbar for blocks that don't have any block controls, and that live inside a locked template ([such as](https://github.com/Automattic/wp-calypso/blob/2c466a1f7c2575f5db0b7638dfb660fd359f4307/client/landing/gutenboarding/gutenboard.tsx#L78)).

We're both not entirely sure if we'd inadvertently prevent any other block interactions that way, but agreed that it might be worth exploring in a PR and soliciting feedback that way.

**Pull request merged**
