### PR TITLE
Allow moving metaboxes to previously empty area

### LINKED ISSUE #7960: No way to drag metabox back into sidebar / below content if there are no other metaboxes there
## The issue
If there is a metabox in the sidebar area, you can drag it into the larger area below the content area. However, once you have dragged metaboxes out of the sidebar, there is no way to drag any of them back into the sidebar unless you move them back from the Classic Editor interface. The same applies to moving all the metaboxes out of the area below the main content of the post.

Still an issue in Gutenberg 7.2.0.

### PR DESCRIPTION
**Pull request by aristath**
## Description
Fixes #7960 
In https://github.com/WordPress/gutenberg/commit/cbf425bc76d5797082cd63c8ecb4b6122f15910f we added `isVisible`. The value of that does 2 things:
1. On initial page-load it skips adding to the DOM metabox areas that will not be visible
2. Visually hides a metabox-area if the metaboxes inside it get moved to another area and it's empty.

The problem with the current implementation is that since an empty area doesn't get rendered on initial page-load, it's impossible to move blocks to a new metabox area that doesn't exist.

This PR changes the behaviour above so empty metabox areas will now get added to the DOM - but they will still be visually hidden. This change allows metaboxes to be moved to another metabox-area, even if that was previously empty (and therefore not visible and rendered with the previous implementation)

## How has this been tested?
Tested by installing ACF and adding a metabox area on the side.
Before this commit the metabox could not be moved anywhere. After this commit it is possible to move it.

## Types of changes
Removes the `isVisible` condition from metabox rendering.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] ~~My code follows the accessibility standards.~~ 
- [ ] ~~My code has proper inline documentation.~~ 
- [ ] ~~I've included developer documentation if appropriate.~~ 
- [ ] ~~I've updated all React Native files affected by any refactorings/renamings in this PR~~.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Should we remove [`isMetaBoxLocationVisible`](https://github.com/WordPress/gutenberg/blob/1bec21feb1ba8110fdd11b01c84dc2a3849884a1/packages/edit-post/src/store/selectors.js#L235) since it's not being used anywhere now?

Also, I noticed that you forgot to update the `withSelect` call to stop providing the now unused `isVisible` value.

**Comment by aristath** [comment]
`isVisible` can still be used in many places, and chances are there's plugins out there that use `isMetaBoxLocationVisible` in some way, so I chose to leave those as-is. The problem is that `isVisible` was behaving like `exists`, so all this PR does is make it do what it's supposed to do.

**Comment by ZebulanStanphill** [comment]
Okay, but there's no reason to grab the `isVisible` value from a `withSelect` call if it never gets used by the wrapped component.

**Comment by aristath** [comment]
Makes sense... pushed an additional commit :+1:

**Comment by ZebulanStanphill** [comment]
Hmmm... I expected this to allow me to drag-and-drop metaboxes from the footer area to the sidebar area. I still can't, but I _can_ use the new up/down buttons (introduced in WP 5.5) to move from the sidebar to the footer (and vice-versa), which I couldn't before. So this is definitely an improvement.

image

One issue I noticed is that moving from the footer area to the sidebar area doesn't work if the Document Settings sidebar is closed. But I wouldn't consider that a blocker.

I did notice some more odd behavior, but I'm pretty sure it's caused by ACF, not WordPress itself. The weird behavior is that sometimes, pressing up/down on a metabox seems to do nothing. I think it has something to do with ACF altering the editor to have two footer areas (`is-normal` and `is-advanced`); sometimes you move from the "advanced" to the "normal" one, but of course, since they're both on top of each other, this isn't clear at all. Again, I wouldn't consider this to be a blocker, and I think this one is more of an ACF issue anyway?

image

Overall, I think this PR looks good to merge, but I'd like to get one more technical review just in case.

**Comment by aristath** [comment]
Thank you for testing and reviewing this @ZebulanStanphill!

> Hmmm... I expected this to allow me to drag-and-drop metaboxes from the footer area to the sidebar area. I still can't, but I can use the new up/down buttons (introduced in WP 5.5) to move from the sidebar to the footer (and vice-versa), which I couldn't before. So this is definitely an improvement.

Correct. Adding a drag dropzone to something that doesn't technically exist visually would complicate this a lot and has the potential to cause more issues than it would solve. Using the up/down arrows is the only way to move blocks to an empty area, and since we now have the buttons it makes sense...

> I did notice some more odd behavior, but I'm pretty sure it's caused by ACF, not WordPress itself. The weird behavior is that sometimes, pressing up/down on a metabox seems to do nothing. I think it has something to do with ACF altering the editor to have two footer areas (is-normal and is-advanced)

Yeah, that part is indeed coming from ACF :sweat_smile:

**Comment by sybrew** [comment]
> Adding a drag dropzone to something that doesn't technically exist visually would complicate this a lot and has the potential to cause more issues than it would solve. 

But... something like this already works (quite well!) on the WordPress admin Dashboard page (see image attached). 

image

Couldn't we make the 'Drag boxes here' pop-in on-drag when no box exists (`!document.getElementById('postbox-container-2').querySelector('.postbox')`)? If that's desired but stifles a (quick) fix for #7960, then I'd suggest making a separate a11y-related issue and merging this PR ASAP (TYVM).

**Comment by draganescu** [comment]
Something I've noticed here is that:
- adding a field group that is set to show Normal - after content
- in the post editor if one clicks the down arrow the field group moves to the side
- refreshing the post moves the field group back to Normal - after content

This is unexpected. It should either / or:
- not allow moving to the side if by post saving is not working
- allow by post position or change the field group positioning for all posts

**Comment by paaljoachim** [comment]
Hi @aristath Ari.

How can we help move this PR forward?
Thanks! @ockham

**Comment by mikeaskew4** [comment]
Looking forward to this fix, thanks y'all.

**Comment by paaljoachim** [comment]
Riad perhaps you could also take a look at this one?
@youknowriad 

Associated: 
Fix metabox reordering
https://github.com/WordPress/gutenberg/pull/30617

**Comment by paaljoachim** [comment]
Hey @ribaricplusplus Bruno

As you worked on
Fix metabox reordering PR: https://github.com/WordPress/gutenberg/pull/30617

Perhaps you might be able to take a closer look at this PR and help get it merged?
Thanks!

**Comment by ribaricplusplus** [comment]
Hi there!

I resolved conflicts between trunk and this PR so the fix works again. There are just 2 things:

**Drag and drop**

It would be great if we could make drag and drop work, especially because it's not too difficult. In fact it's just a style issue, drag and drop doesn't work when there are no meta boxes because the drop zone height is 0. When I increase the drop zone height through dev tools (selector `.edit-post-meta-boxes-area .ui-sortable`), then drag and drop works: https://vimeo.com/638390107/97914b9052

The only problem is that always having this extra height doesn't look nice, so maybe we could listen for UI sortable events and only add height when drag starts: https://api.jqueryui.com/sortable/#event-activate

**Can't move between location with arrows when Post sidebar hidden**

This was mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/25187#issuecomment-690703227).

> One issue I noticed is that moving from the footer area to the sidebar area doesn't work if the Document Settings sidebar is closed. But I wouldn't consider that a blocker.

It would be awesome if we could fix this, but if not let's at least create a separate issue for the problem. The fix may require modifying WP Core postbox script where the click on those arrows is handled (https://github.com/WordPress/wordpress-develop/blob/a1a11d6cebd379e8ba95727fafd945f483f5114c/src/js/_enqueues/admin/postbox.js#L98), I'm not sure.

Other than that, everything looks good to me.

**Comment by paaljoachim** [comment]
Perhaps @gwwar @talldan @andrewserong or @aristath can help with the last remaining pieces here (give some advice etc). The PR seems almost ready to land.

**Comment by aristath** [comment]
Thank you for picking this up @ribaricplusplus and updating the PR 👍 
The PR here doesn't solve the issue 100%, but it doesn't introduce any new issues and it definitely greatly improves what we currently have. I see no reason why we can't merge this one as-is and investigate the remaining issue on a separate ticket.

**Comment by ribaricplusplus** [comment]
I agree, there is no reason not to merge this. But maybe we should leave #7960 opened until we get drag and drop working, I'm leaving that up to you to decide. I created a separate issue for the arrows problem.

**Review by ribaricplusplus — APPROVED** [review]

**Comment by paaljoachim** [comment]
What followups have you created @ribaricplusplus Bruno?
Can you also add the links in here and in the issue? Making it easier for others to also followup on these.

**Comment by ribaricplusplus** [comment]
I wrote the relevant summary here https://github.com/WordPress/gutenberg/issues/7960#issuecomment-950888657

So the follow ups are:
1. The existing #7960 issue. Leaving it opened until we fix drag and drop.
2. The problem with arrows when the sidebar is not visible #35923

**Comment by albanyacademy** [comment]
anyone else stumbles on this, admin css:
```
.is-dragging-meta-boxes {
	.meta-box-sortables, .ui-sortable {
		min-height: 2rem; // or whatever
	}
}
```
addresses the dropzones being 0, but also only when you're actually dragging stuff.

**Pull request merged**
