### PR TITLE
Update/heading - Make HeadingToolbar a component

### PR DESCRIPTION
**Pull request by mrmadhat**
## Description
Previously `HeadingToolbar` was a component created as an internal dependancy of the Heading block. This change would make `HeadingToolbar` (renamed to `ToolbarHeading` to be in line with `Toolbar` and `ToolbarButton`) independant of the Heading block and allow it to be reused in other blocks. For example, I would like to use HeadingToolbar as part of a solution to #10746 

## How has this been tested?
I have tested this in browser

## Types of changes

Improvement - Reusability of code

## Checklist:
- Changes to code are it's location, actual code with very small exceptions doesn't change

### CODE REVIEW

**Comment by aduth** [comment]
The `components` package is intended to contain only generic UI components, nothing domain-specific. I feel this falls a bit too much in the realm of the latter, as it targets specifically support for blocks implementations.

If the goal is to support a similar toolbar in the Cover Image block, I think it would make sense to contextualize this to somewhere common for blocks: `block-library` (no precedent), `editor`, or even just leave it where it is and point to it directly from the Cover Image implementation.

Maybe also worth pointing out that this problem goes away if Cover Image block becomes reimplemented as properly supporting nested blocks, or block functionality otherwise abstracted in some mixin pattern, rather than continued one-off additions to individual blocks.

**Comment by mrmadhat** [comment]
Thanks for your comments @aduth I mentioned the initial ticket in the [editor chat](https://wordpress.slack.com/archives/C02QB2JS7/p1541601203908200) last week and the response was similar to yours with layout blocks such as container being looked at/introduced later. I can see how there wouldn't be a need for the toolbar to be shared across blocks once this happens because the header block would be used as a whole.



The only issue (for me) is that the cover block becomes unusable for the purpose it was created for in the mean time.

image

image

**Comment by aduth** [comment]
I could see a few steps to iterate on the Cover Image block toward #10746. If the block is intended to serve to present a heading (which it appears to), maybe we could at least make that change now as an improvement, even if the heading level is not immediately available to be customized.

It appears you came to a similar realization in #10746?

>I think initially it would be best to remove the paragraph and exchange it for a heading.

I'm not strictly opposed to the HeadingToolbar as a thing, nor to the idea of choosing heading level for a cover image block, but I wouldn't like to see HeadingToolbar in `components`.

**Comment by mrmadhat** [comment]
I'm still getting used to all the different packages of Gutenberg so knowing where things should go can be confusing at times. The reason why I didn't point to it directly was my editor gave me a lint warning saying direct path imports not allowed but that doesn't seem to be there anymore, if there isn't an issue with doing that then that works for me.

I have been working on this separately as part of a plugin, I've created a cover which follows heavily from the original cover but with the addition of a heading with selectable level and sub-heading. But I would be happy to add this to the original cover block, directly import the heading toolbar and submit it as a seperate pull request.

image

**Pull request closed without merging**
