### PR TITLE
Update animation for line and sibling inserter

### PR DESCRIPTION
**Pull request by mtias**
## What?

- Use tween instead of spring for a more subdued effect.
- Increase delay slightly to reduce accidental triggers.

## Testing Instructions

1. Open the editor and hover between blocks.2. 
2. Drag an image into the canvas and move around without dropping the file.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Nice. It's a small change. The "before" gif here is bouncy:

before

The after, is much calmer and linear:
after

after line

**Comment by talldan** [comment]
It's definitely much nicer for the in-between inserter.

It feels a little bit unresponsive for drag and drop when there's a higher frequency of drop locations:

https://user-images.githubusercontent.com/677833/191203369-c5876619-3b0b-44c6-acbb-cd0cdcfe9159.mp4

Here's how it is in `trunk` for reference:

https://user-images.githubusercontent.com/677833/191203744-978ea6e0-1e8f-40d7-8180-7ebf07df92f1.mp4

Because the line starts at full width in `trunk` it feels a bit smoother IMO (it doesn't matter so much if the animation doesn't finish in time), even though I'm not as keen on the bouncy animation.

**Comment by jasmussen** [comment]
> It feels a little bit unresponsive for drag and drop when there's a higher frequency of drop locations:

Nice catch. To an extent I could see this being a benefit, and something to potentially even explore further: it remains difficult to get the precise balance right as to how soon the sibling inserter should invoke, which is _when you need it and otherwise not_. Perhaps it's the kind of fuzzy that can be mitigated through animation?

**Comment by mtias** [comment]
I considered leaving the bounciness for the single line case only, but while it seems alright in the one-tree level context, it seems a bit too chaotic on multi-level ones in the site editor. In any case, it seems like something we can further adjust.

**Pull request merged**
