### PR TITLE
Try: New share icon

### PR DESCRIPTION
**Pull request by jasmussen**
This PR tries to replace the existing share icon, with a new one:

Screenshot 2021-01-29 at 14 10 24

The existing vectors are nice, but the concept used makes for a floaty and slightly imbalanced icon:

Screenshot 2021-01-29 at 14 12 24

The new one is also a standard share icon, but due to the more boxy nature, it rests better in the toolbar:

Screenshot 2021-01-29 at 14 14 31

It also works nicely as a "container of social links":

Screenshot 2021-01-29 at 14 14 52

**Note:** This PR _replaces_ the existing share icon. As an alternative, and if we prefer to keep the old icon around, I can add a new icon and switch Social Links to using it. Let me know.

### CODE REVIEW

**Comment by jasmussen** [comment]
Here's a tweak that makes the box and arrow conflict less:

Screenshot 2021-02-01 at 11 22 22

**Comment by paaljoachim** [comment]
Hi Joen.

I am not sure about this one as it reminds me too much of the open in a new tab icon.
https://www.ecosia.org/images?q=open%20new%20tab%20icon

Example.
open-512

**Comment by kjellr** [comment]
I like it — it's equivalent to the "share" icon used in iOS, so it instantly reads as "Share" to me.
 
IMG_61D7DD2A3106-1

The usage of the arrow feels more at home amongst our current icons when compared to the boxy endpoints in the existing share icon. 

My only concern is that folks will think it _is_ actually a share icon. Which I suppose could've been the case with the existing one if the user was on Android. 😅

**Comment by draganescu** [comment]
While it does look like the iOS version, it does not mean the same thing in this context. Unsure if it is an actual problem, but the current icon better represents what the block is for, The iOS version is more indicative of opening the share sheet, and looks more like an action, thing to which as @paaljoachim note, the arrow does a great contribution to.

So, say, even if I do not confuse this icon with what it does on iOS, does it really help to identify what the social links block does? I don't think it does.

**Comment by bph** [comment]
The Social links block are not actually **sharing links** - that's what the iOS icon does and what I tried to convey in #26780 - The current implementation are **Social Profile** links. 

Here is the [developer documentation for sharing a post on twitter. ](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview)

A profile link just goes to the [bloggers profile ](https://twitter.com/hellojoen)

If you use the sharing icon you are adding the expectation that when people click on it they are actually sharing the post on the social platform 

The designs in #26780 by @mapk are  actually much better in showing the right purpose

**Comment by jasmussen** [comment]
Good thoughts all around. I'm going to close this one for now and leave the adjacent issues open, and circle back when I haeve a moment. Thanks!

**Pull request closed without merging**
