### PR TITLE
Chore: Update browserlist package to fix test errors

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Fixes issue with the failing unit tests caused by one of the dependencies being out of date. As explained in detail by @afercia in https://github.com/WordPress/gutenberg/pull/13385#issuecomment-455876024:

> Note: locally, I get 2 tests failures:
> 
> - `babel-plugin › .getTranslatorComment() › should not return translator comment on same line but after call expression`
> - `Babel preset default › transpilation works properly`
> 
> both seem related to:
> ```
>     Expected mock function not to be called but it was called with:
>     ["Browserslist: caniuse-lite is outdated ...
> ```
> 
> they happen also on master and seem completely unrelated to the changes in this PR.

In addition, I updated the following dependencies which also were using the outdated `browserlist` and `caniuse-lite` packages:
- `"autoprefixer": "^9.4.5"`
- `"postcss": "^7.0.13"`
- `"stylelint": "^9.10.1"`

First two dependencies had breaking changes so it causes some differences in the generated CSS code. In theory, it should be safe as they claim it should have the only impact on the code, because they claim to provide backward compatibility for IE:

> We removed Node.js 4 and Node.js 9 support since it doesn’t have security updates anymore.
> 
> We removed IE and “dead” browsers (without security updates) from Babel’s targets. Don't worry, Autoprefixer still generate IE-compatible code. These changes affect websites which run Autoprefixer on client-side like CodePen.

There is a similar note for PostCSS.

## How has this been tested?
`npm test`
`npm run build`

### CODE REVIEW

**Review by afercia — APPROVED** [review]
Thanks, all tests pass 👍

**Comment by gziolo** [comment]
@karmatosed, @jasmussen or @mapk - can you spot any visual differences in the editor with these changes applied? In theory, there should be no change, it should only contain some optimizations in the generated CSS.

**Comment by gziolo** [comment]
@afercia, I know you use IE, can you double check it doesn't regress with the additional commit applied?

**Comment by jasmussen** [comment]
Took this for a quick spin and did not see any regressions 👍 👍

**Comment by afercia** [comment]
> I know you use IE,

I do, but only for testing purposes on a second laptop. I'll try to test it as soon as I have some spare time.

**Comment by gziolo** [comment]
Thanks for help everyone 🥇

**Pull request merged**
