### PR TITLE
Use double quotes in all NUX tips

### LINKED ISSUE #9205: NUX Tips inconsistently use double quotation marks versus single quotation marks
Some of the NUX (New User Experience) tips inconsistently use double quotation marks, and others use single quotation marks.

>Welcome to the wonderful world of blocks! Click the “+” (“Add block”) button to add a new block. There are blocks available for all kind of content: you can insert text, headings, images, lists, and lots more!

>You’ll find more settings for your page and blocks in the sidebar. Click ‘Settings’ to open it.

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
Fixes #9205. Changes all NUX tips to consistently use double quotes rather than single quotes.

:tada::balloon:First Gutenberg PR hype!:balloon::tada:

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Test failure is valid; I did not realize the text of the tips was duplicated in the tests and has to be changed there as well. Will fix.

**Review by tofumatt — APPROVED** [review]
Those single-quotes were bugging me, thanks for filing the issue *and* for opening the PR! Nice! 👍

**Comment by ZebulanStanphill** [comment]
:balloon::smile::tada:

**Comment by chrisvanpatten** [comment]
giphy

**Pull request merged**
