### PR TITLE
Docs: Document block validation, clarify extensibility validation

### LINKED ISSUE #4759: blocks.getSaveContent.extraProp not working.
Hi,

I've tried the example here : https://github.com/WordPress/gutenberg/blob/master/docs/extensibility.md

````
// Our filter function
function addBackgroundProp( props ) {
	return Object.assign( props, { backgroundColor: 'red' } );
}

// Adding the filter
wp.hooks.addFilter(
	'blocks.getSaveContent.extraProps',
	'myplugin/add-background',
	addBackgroundProp
);
````

It's not working and returning **Block validation: Block validation failed** error. Thanks!

### PR DESCRIPTION
**Pull request by aduth**
Closes #4759 

This pull request seeks to add documentation for block validation, describing the process for determining whether a block is invalid, options presented to the user for resolving the invalidation, and debugging steps for plugin authors. Further, it clarifies a confusion about block extensibility and its relation to validation.

__Testing instructions:__

There are no behavior impact expected with the changes proposed here.

### CODE REVIEW

**Comment by youknowriad** [comment]
Validation is also tied to the deprecated blocks API which is documented on a separate page right now. I wonder how we could better organize all these related docs.

**Comment by aduth** [comment]
>Validation is also tied to the deprecated blocks API which is documented on a separate page right now. I wonder how we could better organize all these related docs.

Maybe it'd be enough to add a question to the FAQ section here about "intended invalidations" ?

>**I changed my block's `save` behavior and now old content includes invalid blocks. How can I fix this?**
>
>Refer to the guide on [Deprecated Blocks](https://wordpress.org/gutenberg/handbook/block-api/deprecated-blocks/) to learn more about how to accommodate legacy content in intentional markup changes.

**Comment by youknowriad** [comment]
> Maybe it'd be enough to add a question to the FAQ section here about "intended invalidations" ?

@aduth I like this proposal 👍

**Comment by aduth** [comment]
Updated in 94902d946bb639b3b30503d34e46a4d9cba1549d

**Pull request merged**
