### PR TITLE
Scripts: Added FortAwesome/Font-Awesome license in list of GPL 2 compatible licenses

### PR DESCRIPTION
**Pull request by bfintal**
## Description

I've added the license `(CC-BY-4.0 AND MIT)` in the list of GPL 2 compatible licenses, it's the license label used by https://github.com/FortAwesome/Font-Awesome FontAwesome isn't used in Gutenberg, but the addition is for other projects that can use `check-licenses`

## How has this been tested?

Tests ran: `npm run check-licenses` and `npm run lint-js`

## Types of changes

New feature: Added `(CC-BY-4.0 AND MIT)` in the list of GPL 2 compatible licenses

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by pento — APPROVED** [review]
Both of these licenses are GPL compatible. In the case of Font Awesome, the code is MIT, the icons are CC-BY 4.0 ([ref](https://github.com/FortAwesome/Font-Awesome#license)).

**Comment by aduth** [comment]
An aside to the specific change, but if there's an established pattern of defining multilicensed projects using `(X AND Y)`, maybe we could automate the parsing to check that each are individually valid licenses. As I write this, I see we do this already for "OR" combinations. Perhaps worth creating as a separate task?

**Comment by pento** [comment]
Yah, `OR` was the more common occurrence when I originally wrote this script, so I just wrote a basic parser for those expressions.

The two major factors for doing it in our own script, instead of using an existing package, were:
- The official SPDX parser doesn't allow for invalid license strings.
- There wasn't anything that worked really well for extracting the license from places other than `package.json`.

We'd probably need to keep our extractor, but something like this could work:

- Test if the license is valid with [spdx-expression-validate](https://www.npmjs.com/package/spdx-expression-validate).
- If it isn't, try and correct it with [spdx-correct](https://www.npmjs.com/package/spdx-correct).
- Check if the license is GPL-2.0 compatible with [spdx-satisfies](https://www.npmjs.com/package/spdx-satisfies).

That at least avoids us having to write a proper expression parser.

**Comment by aduth** [comment]
Let's get this in as-is and iterate on improvements separately.

**Pull request merged**
