### PR TITLE
Unify saving flow between template mode and default mode

### PR DESCRIPTION
**Pull request by youknowriad**
I removed the specific saving flow of the template mode in this PR in order to unify the header between the "template mode" and the regular post editing mode. The idea was to highlight the flows we need to fix.

 - What does "save draft" mean when we have changes in both post and template?
 - Should we show "save draft" if we only have changes in the template?
 - Do we want to keep the "two steps" saving flow: saving templates changes first in  the multi-entity sidebar followed by the pre-publish sidebar when we click "publish" and we have changes in both templates and post?

I also noticed that there's a small bug right now in this last item, the pre-publish sidebar doesn't open when the multi-entity saving flow finishes.

Curious if you have any thoughts/explorations about the above @jameskoster @jasmussen

### CODE REVIEW

**Comment by jasmussen** [comment]
Cool PR. This is before, even before the frame:

before

And this is what I see now:

after

Did I get that right?

Just as a single PR, this _seems_ like an improvement to me (not discounting Matías feedback that we need to refine the visuals of the back button, that's a separate thing). But it does seem to speak to a larger question about the role of the this template editing mode. This PR kind of makes it a property of the post editing flow, which as a user experience makes sense. But it does change the framing. Curious what @jameskoster thinks.

**Comment by youknowriad** [comment]
I do think this is the right direction: a unique saving flow regardless of the mode you're in but I also think the current saving flow is broken and way too complex: maybe it should work like this:

 1- Clicking "save draft": if there are dirty multi-entities (like templates), show a panel  with these changes + a specific messages saying that all the changes are going to be published. Only the post is going to be saved as draft. (with the possibility to uncheck the other changes)
 2- Clicking "publish/update": the same thing as 1 expect that it actually publishes the post  as well.  I'd also prefer if we avoid the two steps we have right now personally here multi-entity panel + pre-publish panel and instead just a have a unified panel.
 3- Do not show the "save draft" button if the post is not "dirty" 
 4- Only show the "saved" check when everything is saved.

**Comment by jameskoster** [comment]
Yeah I totally agree with the unification. If we're to update the save UI every time a user edits a different entity (content, template, style) it will end up being too convoluted and feeling too complex.

> Clicking "save draft": if there are dirty multi-entities (like templates), show a panel with these changes + a specific messages saying that all the changes are going to be published. Only the post is going to be saved as draft. (with the possibility to uncheck the other changes)

I'm a little uncomfortable with mixing the save-draft and publish actions here. I wouldn't expect a "Save draft" button to ever _publish_ anything. It may be better if the action is consistent regardless of the affected entities. So "Save draft" would enable you to save drafts for all new & unpublished entities including templates, and perhaps even styles in the future.

"Save" and "Update" can behave the same as they do now – show the multi-entity panel. We can probably use the same label for both buttons.

"Publish" essentially behaves the same as "Save" and "Update". The only difference being that it outlines any unpublished entities will be published in the multi-entity panel, and that everything else will be saved. 

Here are some scenarios and the UI a user would see in them:

### Un-saved changes to published content, un-saved changes to published template:

* "Save draft" button is hidden since everything is published
* "Save" / "Update" button reveals multi-entity save panel

### Un-saved changes to un-published content, un-saved changes to published template:

* "Save draft" button reveals multi-entity panel for drafts. Only content is listed in this scenario.
* "Save" / "Update" button is hidden because there are new entities
* "Publish" button reveals multi-entity panel. The UI clarifies that the content will be published and the template will be saved/updated.

### Un-saved changes to published content, un-saved changes to un-published template:

* "Save draft" button reveals multi-entity panel for drafts. Only template is listed in this scenario
* "Save" / "Update" button is hidden because there are new entities
* "Publish" button reveals multi-entity panel. The UI clarifies that the content will be saved/updated and the template will be published.

### Un-saved changes to un-published content, un-saved changes to un-published template:

* "Save draft" button reveals multi-entity panel for drafts. Both the content and the template are listed in this scenario
* "Save" / "Update" button is hidden because there are new entities
* "Publish" button reveals multi-entity panel listing indicating that both the un-published content and template will be published.

--- 

There are a number of other considerations here, like multi-entity scheduling and multi-entity status updates (switch from published to draft).

**Comment by youknowriad** [comment]
> So "Save draft" would enable you to save drafts for all new & unpublished entities including templates, and perhaps even styles in the future.

We don't support drafts for anything but regular posts/pages, basically there's no such thing as "unpublished template" or "unpublished reusable block".

**Comment by jameskoster** [comment]
Should there be? 😛

If not, then that does simplify things. I do still stand by the point that the "Save draft" button probably shouldn't actually publish anything though. So to revise your first point from earlier:

> 1- Clicking "save draft": if there are dirty multi-entities (like templates), show a panel with these changes + a specific messages saying that all the changes are going to be published. Only the post is going to be saved as draft. (with the possibility to uncheck the other changes)

I would say that clicking this button would just reveal a snackbar to confirm that just the post draft was saved. In this scenario the "Publish" button would open the Multi-entity panel and indicate that the content will be published, and which template(s) (if any) will be updated.

**Comment by youknowriad** [comment]
I'm not sure how to move forward here, I'd love some design explorations that include the following constraints:

 - Only posts/pages can have drafts
 - How/where to show the "pre publish" checks
 - What happens if the user disables the "pre publish" checks
 - What does "save draft" do in the different situations
 - What does "revert to draft" do in the different situations
 - What does "publish/update" do
 ...

I started some implementation based on my "simple" approach here https://github.com/WordPress/gutenberg/pull/30793#issuecomment-818571886 and even that it's very hard.

Starting to think we should land the PR as is and still continue iterating on the flows once we have designs that take into consideration all the complexities.

**Review by jameskoster — APPROVED** [review]
I opened https://github.com/WordPress/gutenberg/issues/30800 for a more detailed design exploration.

**Pull request merged**
