### PR TITLE
ESLint: Fix a bunch of ESLint alignment warnings

### PR DESCRIPTION
**Pull request by tyxla**
## What?
This PR fixes a bunch of ESLint warnings, as well as a couple of TS errors that were unveiled with those fixes.

## Why?
Ideally, we shouldn't have any ESLint warnings/errors. This fixes 151 of the total 167 existing ones.

## How?
We ran `npm run lint:js:fix` and did a couple of TS massaging changes. Basically `EntityRecordKey` is a `number | string`, which required the additional TS changes.

## Testing Instructions
* Verify there are only 16 `jest/expect-expect` or `jest/no-disabled-tests` warnings when running `npm run lint:js`.
* Verify all checks are green.

### Testing Instructions for Keyboard
None

## Screenshots or screencast 
None

### CODE REVIEW

**Review by jsnajdr — APPROVED** [review]
:+1:

**Review by ntsekouras — APPROVED** [review]

**Review by Mamaduka — APPROVED** [review]
Sweet 🚢

**Comment by gziolo** [comment]
> Ideally, we shouldn't have any ESLint warnings/errors. This fixes 151 of the total 167 existing ones.

I wanted to echo my comment https://github.com/WordPress/gutenberg/pull/47811#pullrequestreview-1286665564 from yesterday:

> Thank you for the fix.
>
> Would it be a good idea to promote this warning to an error? People fix those warnings anyway, so why not enforce that on PR authors?

It would be in another PR for those rules covering stylistic violations😄

**Comment by tyxla** [comment]
> > Ideally, we shouldn't have any ESLint warnings/errors. This fixes 151 of the total 167 existing ones.
> 
> I wanted to echo my comment [#47811 (review)](https://github.com/WordPress/gutenberg/pull/47811#pullrequestreview-1286665564) from yesterday:
> 
> > Thank you for the fix.
> > Would it be a good idea to promote this warning to an error? People fix those warnings anyway, so why not enforce that on PR authors?
> 
> It would be in another PR for those rules covering stylistic violations😄

I'm happy to try that out 👍

**Comment by tyxla** [comment]
> > > Ideally, we shouldn't have any ESLint warnings/errors. This fixes 151 of the total 167 existing ones.
> > 
> > 
> > I wanted to echo my comment [#47811 (review)](https://github.com/WordPress/gutenberg/pull/47811#pullrequestreview-1286665564) from yesterday:
> > > Thank you for the fix.
> > > Would it be a good idea to promote this warning to an error? People fix those warnings anyway, so why not enforce that on PR authors?
> > 
> > 
> > It would be in another PR for those rules covering stylistic violations😄
> 
> I'm happy to try that out 👍

Suggested in #47878.

**Pull request merged**
