### PR TITLE
Fixes update-readme script

### LINKED ISSUE #15626: Documentation: core/data README is only updated for changes in selectors
How to reproduce:

* Make a change in the JSDoc of `addEntities` to be found in`packages/core-data/src/actions.js`
* Make a change in the JSDoc of `canUser` to be found in`packages/core-data/src/selectors.js`
* Execute `npm run docs:build`.

Notice how `packages/core-data/README.md` only reflects the changes in the `selectors.js` file, while `docs/designers-developers/developers/data/data-core.md` contains both changes.

### PR DESCRIPTION
**Pull request by oandregal**
This PR does two things:

* **Fixes https://github.com/WordPress/gutenberg/issues/15626 and https://github.com/WordPress/gutenberg/issues/15680 by making the script synchronous**. In https://github.com/WordPress/gutenberg/pull/15200 we missed the fact that to fill tokens within the same file we need to execute docgen synchronously, otherwise, the last token process will overwrite the first.

* **Updates our `espree` dependency to 4.0.0.** When error reporting was back, we uncovered that introducing short Fragment syntax in https://github.com/WordPress/gutenberg/pull/15120 caused docgen to fail. The reason is that the `espree` version we used didn't support that. This fixes it by upgrading it to one that does. A couple of restrictions:
  * [espree](https://github.com/eslint/espree/releases) uses [acorn-jsx](https://github.com/RReverser/acorn-jsx/releases) to power JSX parsing.
  * `acorn-jsx@4.1.0` added support for JSX fragment short syntax (patched in 4.1.1).
  * `espree@4.0.0` added `acorn-jsx@4.1.1`. We should use this at a minimum.
  * `espree@4.1.0` added `acorn@6` and `acorn-jsx@5` for parsing. This caused an error I couldn't identify the source.
  * `espree@5.0.0` removed support for the [attachComment](https://github.com/eslint/espree/releases/tag/v5.0.0). We use this for collocating the JSDoc comment with the proper export statement. Without this we can't migrate to `espree@5.0.0`. 

## Test

- Reproduce instructions at https://github.com/WordPress/gutenberg/issues/15626
- Go to `packages/a11y/src/index.js` and introduce a syntax error. For example, change `export const setup = function() {` to `export c setup = function() {`. Make sure `npm run docs:build` fails.

### CODE REVIEW

**Comment by nosolosw** [comment]
Note that this is failing due to some syntax the parser doesn't understand. It looks like this broke with the introduction of short Fragment syntax https://github.com/WordPress/gutenberg/pull/15120

**Comment by nosolosw** [comment]
The reason it got in was that errors weren't reported by the update-readme script https://github.com/WordPress/gutenberg/issues/15680

**Review by mkaz — APPROVED** [review]
Looks good. 

I tested it out running the update-readmes script and did not see any local changes around the core-data whitespace or other issues.

**Comment by aduth** [comment]
It doesn't seem we should need to make _everything_ synchronous, vs. just those occurring in the same file. That being said, some recent similar explorations in build parallelization have not proved much value in naive implementations like `Promise.all` for dozens of tasks, so it may be okay to avoid the overhead in managing synchronous and asynchronous tasks. 

The other option to explore if performance becomes a bottleneck is something more like what I'm considering in #15230.

**Pull request merged**
