### PR TITLE
Update tooltip colors

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Update the tooltip colors.

## Why?
The current colorisation causes them to blend into the dark material in the site editor:

This PR changes the background color to `$gray-800`, but black could work too:

| Gray 800 | Black |
| --- | --- |
| Screenshot 2023-05-19 at 14 38 42 | Screenshot 2023-05-19 at 14 40 17 |

cc @ciampo @mirka as I noticed some preparatory theming styles were used here. I didn't want to update `$components-color-foreground` as I'm sure it's used elsewhere without issue.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Any preference?

**Comment by paaljoachim** [comment]
It would be helpful with feedback on this one from component container contributors.
Are there already some default colors used in the WordPress core ecosystem?

**Comment by jameskoster** [comment]
My preference would likely be dictated by feedback around theming. 

In that respect I suppose it's a conceptual question about whether tooltips should be a shade lighter or darker than the base background color.

In the examples below the lighter shade works a bit better for me. Both in terms of perceived elevation, and because the darker shade has a 'disabled' feel about it in light mode. What do you think?

Screenshot 2023-05-19 at 16 30 00

Of course Tooltips may be a unique case, and display the same regardless of mode / theme. I'll cc @SaxonF as I know he's thought about these details more than me :)

**Review by mirka — COMMENTED** [review]
Basically, the theme-ready `gray-*` scale is set up to darken in inverse directions based on whether the theme background is considered dark or light. (See this [color scheme demo](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-theme--color-scheme) in Storybook and tweak the control for the `background` prop.)

Based on the theme-ready colors we have at our disposal right now, a straightforward combination would be:

```scss
background: $components-color-gray-100;
color: $components-color-foreground;
```

This way the tooltip background is guaranteed to be at least slightly different from the themed background color. However, this will be a major stylistic change for all the current usages of Tooltip, being that most app backgrounds tend to be white.

https://github.com/WordPress/gutenberg/assets/555336/4a2e6850-1c97-4a2b-b943-416fa253e999

> Tooltips may be a unique case, and display the same regardless of mode / theme.

Yes, a completely static setup (as proposed in this PR) is also probably fine for now, though not 100% theme-ready because we can't guarantee that `black` has sufficient contrast against the themed background color. But I am ok with merging as is, we can deal with it later when it comes to it 👍

**Comment by jameskoster** [comment]
Yeah the theming part is a bit more involved. I was playing with some ideas at the weekend and figured we may need to consider things like elevation here too. Not necessarily shadows, but the general order/layering of different materials (tooltips, popovers, snackbars, modals, the frame etc), and the affect that has on coloring.

With that said, I'll merge this as it addresses a pain point in trunk, and we can circle back when we have a more robust color system in place.

**Pull request merged**
