### PR TITLE
Combine the two React Native test workflows into one

### PR DESCRIPTION
**Pull request by desrosj**
## Description
To try and help alleviate the GitHub Action backlog we keep encountering, let's combine the React Native test workflows into one.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [X] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ocean90** [comment]
I think it makes sense to combine them into one workflow as it’s more less testing the same only with different OS. So far I haven’t figured out what GitHub really prefers. But since [each job runs in its own VM](https://docs.github.com/en/actions/using-github-hostedx-runners/about-github-hosted-runners#about-github-hosted-runners) it shouldn’t really matter?

Related to the inner workings of GitHub Actions: https://www.liatrio.com/blog/github-actions

**Comment by gziolo** [comment]
It looks like those two workflows still pass, run independently and execution time is similar so it should be good. I asked in the #mobile channel on WordPress Slack for confirmation (link requires registration at https://make.wordpress.org/chat):

https://wordpress.slack.com/archives/C02RQC4LY/p1621573264003900

**Comment by ceyhun** [comment]
re-run

The main reason for having them as separate `workflows` was because GitHub Actions is missing a `Re-run failed jobs` option. So now if iOS fails but Android passes and if we'd like to re-run iOS, we'll also need to re-run the passing Android `job`.

Based on the limitations explained [here](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits), I think our GitHub Actions queue's concurrency depends on `runs-on` (Windows, Ubuntu or macOS) and `jobs`, but **not** on `workflows`. If we make this change we'll still keep having 2 macOS `jobs` even though we have 1 `workflow`, so we will still be limited by the 5 concurrent macOS `jobs`.

**Comment by ceyhun** [comment]
@desrosj Do you think there might be other advantages to combining the workflows?

**Comment by desrosj** [comment]
> The main reason for having them as separate `workflows` was because GitHub Actions is missing a `Re-run failed jobs` option. So now if iOS fails but Android passes and if we'd like to re-run iOS, we'll also need to re-run the passing Android `job`.

Ah, this makes sense to me! I think we could close this out then.

The only other thing we could try here would be to run everything up through `npm ci`, upload an artifact, and use that artifact in both test jobs. But I don't know if we'll see enough improvement to justify merging them. I'll give it a shot just to see how it goes.

I'm mainly going through our workflows looking for ways we can speed things up, and/or combine like testing into better grouped workflows. But it seems the benefits of keeping these separate are greater.

**Comment by youknowriad** [comment]
I like this UI/flow personally https://github.com/WordPress/gutenberg/actions/runs/864731320 
It seems that's what Github envisions as "workflows" instead of separate jobs.

It might not be a strong argument compared to other considerations though

**Comment by gziolo** [comment]
Screen Shot 2021-05-21 at 20 54 13

It looks like `npm ci` takes 6 minutes to run. It's the place where we should seek improvements, too. It would be great to investigate that further. There is a related issue that raises the issue of the gigantic total download size of `node_modules`: https://github.com/WordPress/gutenberg/issues/26993. There is also a long list of post-install tasks. Maybe we could avoid some of them.

**Comment by desrosj** [comment]
I'm going to close this out. I don't think combining the workflows will result in meaningful improvements besides consolidation of similar testing.

**Pull request closed without merging**
