### PR TITLE
Update Appium dependency version to 1.20.2

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3121

## Description

Appium dependency has recently included a fix for preventing an error when using NPM version 7 so it would be nice to update it.

## How has this been tested?

Appium is used for running the end-to-end tests on the mobile version of the editor so for verifying that this is working it will require to run them.

**It will be tested in the `guteberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3121, so this PR shouldn't be merged until that PR is approved.**

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by fluiddot** [comment]
Looks like one of the dependencies required by Appium has an incompatible license:
`Module argparse has an incompatible license 'Python-2.0'.`

I'm not sure what's the solution for this, what's done in this cases?

**Comment by fluiddot** [comment]
> Looks like one of the dependencies required by Appium has an incompatible license:
> `Module argparse has an incompatible license 'Python-2.0'.`
> 
> I'm not sure what's the solution for this, what's done in this cases?

Confirmation for adding `Python-2.0` has been requested in the WordPress Slack in the #core channel ([comment from original issue](https://github.com/WordPress/gutenberg/issues/28834#issuecomment-776519918)).

**Comment by ockham** [comment]
Reading this comment in our `check-license` script: https://github.com/WordPress/gutenberg/blob/1a29dbdecb6222a62ff66fa1eb5e3bb66ede44a4/packages/scripts/scripts/check-licenses.js#L67-L79

we might actually with the `Python-2.0` license (and add it to that list) -- since I think we're not including `appium` in any of our builds.

cc/ @gziolo

**Comment by gziolo** [comment]
@ockham, yes, I made the same assumption but I didn't get any clear answer on the WordPress Slack. I would do it personally unless someone confirms it's no go.

**Comment by ockham** [comment]
I had a closer look at the [`argparse`'s `LICENSE` file](https://github.com/nodeca/argparse/blob/70fc26eb5a9a829d6ddcceb6b4c87802218227fd/LICENSE), and reading it more closely, it turns out that it's actually almost certainly not just Free Software, but even compatible with the GPL :tada:

---

Here's the nitty gritty:

Unlike the [`Python-2.0` license at SPDX](https://spdx.org/licenses/Python-2.0.html), it doesn't contain the following part:

> 7. This License Agreement shall be governed by and interpreted in all respects by the law of the State of Virginia, [...]

That part is found in the "CNRI OPEN SOURCE LICENSE AGREEMENT (for Python 1.6b1)" section. (I'm not even sure if that part is legally binding or just there for historic purposes.) Anyway, I think that that part is what [is mentioned by the GNU project's license list as the reason for that license being GPL-incompatible](https://www.gnu.org/licenses/license-list.en.html#PythonOld):

> This is a free software license but is incompatible with the GNU GPL. The primary incompatibility is that this Python license is governed by the laws of the State of Virginia, in the USA, and the GPL does not permit this.

Anyway, `argparse`'s `LICENSE` has the following instead:

> 7. This License Agreement shall be governed by the federal
intellectual property law of the United States, including without
limitation the federal copyright law, and, to the extent such
U.S. federal law does not apply, by the law of the Commonwealth of
Virginia, excluding Virginia's conflict of law provisions. [...]

Note that this is identical to what the GNU Project calls the [Python-2.0.1 license](https://directory.fsf.org/wiki/License:Python-2.0.1) (which unfortunately isn't an SPDX-listed license), and [lists as GPL-compatible](https://www.gnu.org/licenses/license-list.en.html#Python) :tada:

**Comment by ockham** [comment]
The way forward (based on https://github.com/WordPress/gutenberg/pull/28890#issuecomment-777799177).

_In an ideal world:_ SPDX would include `Python-2.0.1`, and `argparse` would set its `package.json`'s `license` field to it.
  - We might want to file an issue/PR against [SPDX' GitHub repo](https://github.com/spdx/license-list-XML), and follow up on the [issue](https://github.com/nodeca/argparse/issues/160) I filed on `argparse`'s.
  - We could then set the `Python-2.0.1` as GPL compatible in our license checker.

_More practically, to unblock us:_ We can include the `Python-2.0` license in our `otherOssLicenses` array (as described [here](https://github.com/WordPress/gutenberg/blob/1a29dbdecb6222a62ff66fa1eb5e3bb66ede44a4/packages/scripts/scripts/check-licenses.js#L67-L79)). (That license can remain there even if we are eble to make the "ideal world" scenario a reality.)

_As a follow-up:_ Maybe using an existing (3rd party) license checker tool could alleviate some maintenance burden. See e.g.
- https://github.com/github/licensed
- https://github.com/google/licensecheck

**Comment by ockham** [comment]
> _More practically, to unblock us:_ We can include the `Python-2.0` license in our `otherOssLicenses` array (as described [here](https://github.com/WordPress/gutenberg/blob/1a29dbdecb6222a62ff66fa1eb5e3bb66ede44a4/packages/scripts/scripts/check-licenses.js#L67-L79)). (That license can remain there even if we are eble to make the "ideal world" scenario a reality.)

https://github.com/WordPress/gutenberg/pull/28968

**Comment by ockham** [comment]
I've just merged https://github.com/WordPress/gutenberg/pull/28968, going to rebase this PR now.

**Review by gziolo — APPROVED** [review]
CI looks good, so it's up to you @fluiddot to merge it when everything is ready in both repositories that have React Native code 👍🏻 

Awesome collaboration with @ockham 👏🏻

**Comment by fluiddot** [comment]
Thank you very much @ockham and @gziolo for the help and the awesome work on this 🎊 !

> CI looks good, so it's up to you @fluiddot to merge it when everything is ready in both repositories that have React Native code 👍🏻
> 
> Awesome collaboration with @ockham 👏🏻

Yeah, I've already requested review on the `gutenberg-mobile` PR so once I have the approval there I'll merge this one.

**Comment by fluiddot** [comment]
Tested and approved via https://github.com/wordpress-mobile/gutenberg-mobile/pull/3121#pullrequestreview-590515015.

**Comment by ockham** [comment]
> _In an ideal world:_ SPDX would include `Python-2.0.1`, and `argparse` would set its `package.json`'s `license` field to it.
> 
> * We might want to file an issue/PR against [SPDX' GitHub repo](https://github.com/spdx/license-list-XML), and follow up on the [issue](https://github.com/nodeca/argparse/issues/160) I filed on `argparse`'s.

https://github.com/spdx/license-list-XML/issues/1200 and https://github.com/nodeca/argparse/issues/160#issuecomment-782278150

**Pull request merged**
