### PR TITLE
Pass down focus prop in Toolbar component

### LINKED ISSUE #975: Toolbar component missing argument?
https://github.com/WordPress/gutenberg/pull/896/files#diff-1e5b5fc5d157e4b4b0bfc9e3693ca62bR33

Not totally sure, but I think the toolbar is missing an argument `focus`.  @iseulde could you explain the intent of that change so I don't goof things up.  I think we need to add `focus` to the signature at the top?

### PR DESCRIPTION
**Pull request by ellatrix**
Closes #975. Props @BE-Webdesign!

### CODE REVIEW

**Comment by iseulde** [comment]
I'm not sure why the linter didn't catch this.

**Comment by aduth** [comment]
>I'm not sure why the linter didn't catch this.

Was just about to ask the same thing 😄

**Comment by BE-Webdesign** [comment]
Yeah, no idea, good thing we are starting to add tests in.

**Review by BE-Webdesign — APPROVED** [review]

**Comment by aduth** [comment]
Guessing it was considering it as the `window` global focus?

https://developer.mozilla.org/en-US/docs/Web/API/Window/focus

**Comment by BE-Webdesign** [comment]
> Guessing it was considering it as the window global focus?

That sounds like the culprit.

**Comment by iseulde** [comment]
Huh, didn't even now that existed.

**Comment by iseulde** [comment]
I'm all for removing the `browser` setting and explicitly getting from the `window` object...

**Comment by aduth** [comment]
>I'm all for removing the `browser` setting and explicitly getting from the `window` object...

Worth exploring. Are `window` and `document` considered permitted only by that env flag though? Webpack remaps `global` as `window` if I recall correctly, so at worst we'd have `global.getComputedStyle`, `global.document.querySelector`, etc.

**Comment by iseulde** [comment]
Actually, I removed the `browser` flag, and it still does not error.

**Comment by aduth** [comment]
Might be picking up default from `eslint-config-wordpress`:

https://github.com/WordPress-Coding-Standards/eslint-config-wordpress/blob/25114c9/index.js#L4

In which case we'd need to explicitly set it to `false`.

**Comment by iseulde** [comment]
@aduth Perfect! :)

**Pull request merged**
