### PR TITLE
Composite: refactor to TypeScript

### PR DESCRIPTION
**Pull request by margolisj**
## What?

Upgrading Composite component to Typescript.

## Why?

Typescript is the only sane was to maintain a codebase this large.

### CODE REVIEW

**Comment by margolisj** [comment]
@mirka @ciampo Smallest one yet for #35744. Hopefully it really was this easy. Like always, lmk if there are any other changes necessary. Cheers.

**Review by ciampo — APPROVED** [review]
LGTM 🚀 

Would you mind adding an entry to the CHANGELOG in the `Unreleased` section, under an `Internal` sub-section? (here's [an example](https://github.com/WordPress/gutenberg/blob/3434e37ccbff3d5f60dc1684255bf0b5b453a469/packages/components/CHANGELOG.md?plain=1#L57) of a similar entry)

We can merge as soon as that's done!

**Comment by margolisj** [comment]
@ciampo Added changelog and rebased from current trunk.

**Review by ciampo — APPROVED** [review]
LGTM 🚀 

Thank you, @margolisj !

**Pull request merged**
