### PR TITLE
Tree Grid: Fix keyboard navigation for expand/collapse table rows in Firefox

### LINKED ISSUE #37972: List View: Cannot collapse parent Block which contains child Blocks with screen reader
### Description

The List View does not allow you to collapse a parent Block such as Columns Block while using a screen reader.

### Step-by-step reproduction instructions

1. Open a Post or Page for editing.
2. Insert some Blocks.
3. Insert a Columns Block and choose a variation from the list.
4. Open the List View.
5. With the keyboard, navigate to the Columns Block.
6. Notice how pressing Left Arrow on the Columns Block does not collapse the children Column Blocks within.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

Browser: Firefox
Screen Reader: NVDA
OS: Windows 10 Professional
Gutenberg Version: trunk

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by alexstine**
## Description

Fixes #37972

- Remove useCallback().
- Switch from .ariaExpanded to .getAttribute() for better browser support.

## How has this been tested?

Tested in Firefox with NVDA screen reader on Windows 10.

1. Open the editor.
2. Insert some Blocks.
3. Insert a Columns Block and choose a variation.
4. Open the List View.
5. Try to collapse and expand the Columns Block.
6. Notice the state of aria-expanded on the table row change.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
> Switch from .ariaExpanded to .getAttribute() for better browser support.

Looks like this is the cause of the issue. `ariaExpanded` isn't supported in Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaExpanded

Thanks for fixing it @alexstine. What do you think about restoring the `useCallback` that's removed in the PR?

**Comment by alexstine** [comment]
@talldan useCallback() is also a problem. If I use useCallback(), I get really strange behavior with keyboard keys not being detected correctly. E.g. if I collapse the column and then try to expand again, it returns false super early. It's like useCallback() effects the use of event.keyCode being reliable and returning the currently pressed key. I thought the whole point of useCallback() was only to execute a function once after mounting, not to execute time and time again with keyboard interaction. Did I not understand the docs here or is there something else possibly going on? I console.log most of the code and it is clear, using the useCallback() function messes with keyboard key detection.

The ariaExpanded issue was a quick find for me because I quickly realized logging after the conditional statements was returning nothing. Checking MDN gave me my answer.

Thanks.

**Comment by alexstine** [comment]
@talldan I saw your note about the missing deps from useCallback(). Sure enough, everything is working now.

**Review by talldan — APPROVED** [review]
That fixes it, thanks @alexstine!

I'll add the 'Backport to WP Minor Release' label so that this makes its way into WordPress 5.9.1.

**Pull request merged**
