### PR TITLE
Default to content-box box-sizing for the metabox area.

### PR DESCRIPTION
**Pull request by igorschoester**
## Description

This is meant to keep the plugin default box-sizing the same as used in WordPress.
By applying `box-sizing: content-box;` to the `.edit-post-meta-boxes-area` class.

As per @afercia 's [comment](https://github.com/WordPress/gutenberg/issues/5353#issuecomment-369926527).

## How Has This Been Tested?

I tested it with Yoast SEO plugin to see the CSS came through the build properly.

Fixes: #5353

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for working on this. 

I think we might need a more nuanced approach than unsetting the property again. The initial point in #5353 seems to suggest that the rule is, perhaps, a bit too broadly applied. And so I'd like to, as soon as I can, try and narrow that ruleset down to apply, perhaps, primarily to the editor and UI, and not necessarily to `*`.

Ideally we shouldn't have to unset the previous value, as `content-box` is the default behavior.

**Comment by jasmussen** [comment]
On second thought, perhaps it *is* the right approach to override like this, despite my previous comment.

CC: @aduth and @youknowriad for a technical perspective.

**Comment by aduth** [comment]
If meta boxes are simply outputting the same as in classic editor, and classic editor meta boxes display with `content-box`, I agree that should be preserved for backwards compatibility.

To the implementation itself:

- This style shouldn't be applied in the layout stylesheet, it should be applied in `edit-post/components/meta-boxes/meta-boxes-area/style.scss`
- The current recommended practice for applying `box-sizing` to all elements has changed so that `*` applies `box-sizing: inherit`
   - https://www.paulirish.com/2012/box-sizing-border-box-ftw/
   - I think we should do this in the editor, which then simplifies this implementation to applying `box-sizing: content-box` to _only_ `.edit-post-meta-boxes-area` and its descendents would inherit this automatically

**Comment by igorschoester** [comment]
> I think we should do this in the editor, which then simplifies this implementation to applying box-sizing: content-box to only .edit-post-meta-boxes-area and its descendents would inherit this automatically

Where do you propose `box-sizing: inherit` is done?
Inside `.gutenberg` is discouraged, also in your link (While this PR is applying it for the second time 😉).
And to apply it on everything is risky because it will affect all the screens.

**Comment by igorschoester** [comment]
@aduth Does this last commit reflect the changes you proposed?

**Review by aduth — APPROVED** [review]
It does, yes, thank you. I've confirmed that elements within meta boxes are applied `content-box`, while those in the rest of the Gutenberg interface have `border-box`.

Not sure if @jasmussen wanted a final say on this, but otherwise I think it looks good 👍

**Comment by afercia** [comment]
Double checking with @igorschoester not sure this works as expected.
See WordPress common.css:
```
.postbox-container .meta-box-sortables {
    box-sizing: border-box;
}
```

this will make all the content of the meta boxes switch again to `border-box` because not they all inherit, while previously the rule above applied only to the targeted element.

Also, all input fields (input, textarea) are supposed to stay `border-box`.

**Comment by jasmussen** [comment]
No need for my say 😉

But maybe double check with Andrea.

**Comment by igorschoester** [comment]
I changed the approach to applying `border-box` more sparingly to Gutenberg itself. So the plugin area remains unaffected and keeps the default `content-box`.

In the block layour I still use a universal selector. Maybe this could be refined more. I chose this solution because I'm unsure what the possibilities are here. Can a plugin add a block that does not have a Gutenberg class?
```scss
.edit-post-layout__editor * {
	box-sizing: border-box;
}
```

I tested it by taking before and after screenshots and comparing them. The text on the sidebar and menu's slightly moved. So slightly I did not notice with the naked eye.

**Comment by afercia** [comment]
Noticed with @igorschoester this needs to be updated after https://github.com/WordPress/gutenberg/commit/d8bc60dcc5062329544232947111572f68ff63f2

**Review by atimmer — APPROVED** [review]
Looks good to me.

**Comment by afercia** [comment]
After all, seems this change doesn't break things _that_ much 🙂 I was expecting more breakage.

A few things that look a bit different after this change and could be easily fixed:
- inserter > shared block preview is larger
- content structure popover is larger 
- more menu is larger
- publish sidebar is 1px larger 
- blocks > more options menu is larger 

Also, some subtle alignments of the borders:

screen shot 2018-03-12 at 15 27 50

screen shot 2018-03-12 at 15 31 57

I'd defer any decision to the project leads.

**Comment by jasmussen** [comment]
I much appreciate the work that's gone into this, but those kind of pixel regressions are ones we kind of want to avoid at this stage, as they are likely to propogate and balloon. Just a casual look reveals additional regressions that are hard to catch:

screen shot 2018-03-12 at 15 53 20

Especially given that we hope to build a release soon, perhaps it's better to revert at this time and explore again post-release? I do agree with Andrew it would be nice if there was a better way to allow this selector to affect most of the UI, since it's been built since April 2017 assuming the selector was in place. 

CC: @mtias

**Comment by aduth** [comment]
Revert at #5569

**Comment by atimmer** [comment]
Makes sense to revert. I wasn't aware that a release would be going out soon.

@aduth, @jasmussen What do you think is the best way forward? Re-merge this after release or a new PR that tackles this differently?

**Comment by jasmussen** [comment]
> Makes sense to revert. I wasn't aware that a release would be going out soon.

No worries.

> What do you think is the best way forward? Re-merge this after release or a new PR that tackles this differently?

Reflecting upon this PR, it seems perhaps most pragmatic to revisit this comment: https://github.com/WordPress/gutenberg/issues/5353#issuecomment-369926527

That is — find a way to apply `box-sizing: border-box;` to Gutenberg in a way that is, perhaps, more performant than using the `*` selector (or perhaps that's plenty performant?), and then override it using `box-sizing: content-box;` on the metaboxes.

In a way it comes down to philosophy. Considering we are working with a new codebase, if we were to want to create a better foundation for UI in the future, which box model do we prefer — the one where border is included in the width, or the one where it isn't? If it's the border-box model, then it would be nice for it to apply to, basically, everything, and then be overridden.

**Comment by aduth** [comment]
Recent resources I've found suggest performance implications of `*` are typically overblown and doesn't have a noticeable impact one way or the other. Commented as such in original text of #5180.

Seems like the easiest approach would be:

_edit-post/assets/stylesheets/main.scss_:

```scss
.gutenberg {
	* {
		box-sizing: border-box;
	}

	// ...
}
```

_edit-post/components/meta-boxes/meta-boxes-area/style.scss_:

```scss
.edit-post-meta-boxes-area {
	* {
		box-sizing: content-box;
	}
}
```

**Comment by jasmussen** [comment]
@igorschoester @atimmer will this work? Seems quick ☝️

**Comment by igorschoester** [comment]
@jasmussen Yes, it was the first proposal 😉
I'll create a new branch with that solution.

**Pull request merged**
