### PR TITLE
Update the padding values on the Card component to align with proposed spacing system

### PR DESCRIPTION
**Pull request by jameskoster**
## Description
This PR updates the padding values on the Card components (header, body, footer) to be multiples of 8, and align more neatly with the "consistent spacing system" proposed [here](https://make.wordpress.org/design/2019/10/31/proposal-a-consistent-spacing-system-for-wordpress/). While multiples of 4 are totally acceptable, being a little stricter and using 8 as a preference creates a greater sense of consistency and robustness.

I also renamed the `size` prop to `padding` which is more explicit. `Size` felt a bit too ambiguous.

## How has this been tested?
Testing required :)

## Screenshots 
padding

The top row are the current values, the bottom row are the proposed values.

## Types of changes
CSS changes and some find / replace.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
Unfortunately, renaming `size` to `padding` is a breaking change and ideally we avoid these since the component already ships with WP. Also, I feel it's misleading as well because one could assume that it's CSS padding and provide numbers.

**Comment by jasmussen** [comment]
This seems good to me!

I assume we can't really use the grid-unit variables here? In that case, ship it!

**Comment by jameskoster** [comment]
> I assume we can't really use the grid-unit variables here?

I don't believe those have been implemented yet?

Also, the padding styles are defined in a .js file, I'm not sure if that would have access to those variables?

**Comment by jasmussen** [comment]
Well they're in master: https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_variables.scss#L22

**Comment by jameskoster** [comment]
Ah, I was looking for the vanilla css vars suggested in the post on make 🤦‍♂ 

> Also, the padding styles are defined in a .js file, I'm not sure if that would have access to those variables?

Do you know if those vars are accessible in `card-styles.js`?

**Comment by jasmussen** [comment]
No, I don't think they are, and that's fine. But the values you chose are compatible :) that's a great start.

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! This reminds me! In the future, it would be handy to have a `js` based mixin (maybe something like `spacing(3)`) to retrieve these values

**Comment by ItsJonQ** [comment]
Will merge this when Travis is green and happy
Thanks again for working on this!

**Pull request merged**
