### PR TITLE
Update Gutenberg release docs to include the new Gutenberg Release Team

### PR DESCRIPTION
**Pull request by priethor**
## What?
Updates the Gutenberg release docs to include the new [Gutenberg Release Team](https://github.com/orgs/WordPress/teams/gutenberg-release/members).

### <samp>🤖 Generated by Copilot at e486e95</samp>

This change improves the release documentation for the Gutenberg plugin, by clarifying the requirements, roles, and procedures for creating a stable version. It also fixes a broken link and formatting issues in `docs/contributors/code/release.md`.

## Why?
Getting the final approval to upload the new plugin version to the plugin directory wasn't always speedy, and it's not clear who to ask; pinging the whole Gutenberg core team can feel too much.

## How?
By adding a new Gutenberg team that will get the approval notification request emails. The members of this team are folks usually involved in Gutenberg releases that are not necessarily Gutenberg Core members. They can help review releases speedily or be directly pinged for release-related questions. If having yet another team doesn't actually help, we can delete it again.

### <samp>🤖 Generated by Copilot at e486e95</samp>

* Clarify the requirements and permissions for releasing a stable version of the Gutenberg plugin ([link](https://github.com/WordPress/gutenberg/pull/50036/files?diff=unified&w=0#diff-17d1ffea91f685c145076051d0b46384b2cf600635cc9429d877e168914aca1bL5-R8))
* Add the WordPress core team and the Gutenberg Release team as possible approvers for uploading the plugin to the WordPress.org repository ([link](https://github.com/WordPress/gutenberg/pull/50036/files?diff=unified&w=0#diff-17d1ffea91f685c145076051d0b46384b2cf600635cc9429d877e168914aca1bL88-R91))
* Suggest contacting the approvers ahead of time or in the Slack channel to expedite the process ([link](https://github.com/WordPress/gutenberg/pull/50036/files?diff=unified&w=0#diff-17d1ffea91f685c145076051d0b46384b2cf600635cc9429d877e168914aca1bL88-R91))
* Fix a broken link to the Gutenberg Release team ([link](https://github.com/WordPress/gutenberg/pull/50036/files?diff=unified&w=0#diff-17d1ffea91f685c145076051d0b46384b2cf600635cc9429d877e168914aca1bL88-R91))

### CODE REVIEW

**Review by fabiankaegy — COMMENTED** [review]
I had not known about the formation of this new team before this PR :) So I can't give the final approval for it. But the updates you've made are clear to understand and easy to parse :)

**Comment by priethor** [comment]
> I had not known about the formation of this new team before this PR

I just created it 😅, based on the feedback received during the last couple of releases. Props to @gziolo for the idea 💡

**Review by bph — APPROVED** [review]
Makes sense to me. Yay @gziolo 

I would add the step 
> reaching out _before_ launching the release process so that somebody is ready to approve is recommended

To the release checklist as well.  (= separate PR)

**Comment by gziolo** [comment]
I have also added the new team to the list of folks who can approve npm packages release automatically triggered with every Gutenberg RC1 plugin release.

**Pull request merged**
