### PR TITLE
Update media and video icons

### PR DESCRIPTION
**Pull request by richtabor**
## What?
Was fixing the core/media-text media-container-icon and noticed that the `media` and `video` icons are the same icons. The `media` icon is used when referencing the Media Library ([storybook](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library)), even though its technically a video icon:

CleanShot 2023-03-31 at 19 24 30
CleanShot 2023-03-31 at 19 24 59

I have two proposed paths to take: 

1. Update the `media` icon to accurately reflect images and videos. Then tweak the places where the existing `media` icons are used, to reference the actual `video` icon (what this PR does). 

2. Update the `media` icon to accurately reflect images and videos. Keep the new `media` icon assigned to the Media Library menu items. The downside here is that it's not always the case that images can be replaced by videos (but perhaps it should be). Currently, the Image block does not allow for video file types. 

Another alternative would be to add a new icon to the library, but I don't feel it's necessary while this media/video icon discrepancy is in play. 

## Testing Instructions

1. Open a Post or Page. 
2. Insert a Media & Text block.
4. See new `media` icon.
5. Open the "Replace" popover within the block's toolbar. 
6. See no changes with the existing "Media Library" icon (uses the `video` icon). 

## Screenshots or screencast 

The custom media-container-icon in the Media & Text block in trunk. It doesn't fit the design language of all the other icons, and shouldn't be its own custom icon in the block anyhow:

CleanShot 2023-03-31 at 19 38 47

The updated `media` icon, now in use within the Media & Text block placeholder state:

CleanShot 2023-03-31 at 19 43 11

CleanShot 2023-03-31 at 19 34 10

The `video` icon, now in use within Media Library menu items. There is no visual change; just referencing the actual video icon.  

CleanShot 2023-03-31 at 19 28 52

### CODE REVIEW

**Comment by jameskoster** [comment]
Wouldn't it make sense to use the media icon on the 'Open Media Library' button too? 🤔 

I don't think it's necessarily a blocker because it'd be nice to update the old icon regardless, but the new one looks a _little_ busy. Is there a more abstract way to represent images/video/audio? A couple of ideas that might inspire something better:

Screenshot 2023-04-03 at 12 38 58

**Comment by richtabor** [comment]
> Wouldn't it make sense to use the media icon on the 'Open Media Library' button too? 🤔

Ha, maybe. I'm not sure why the video icon is representative of the Media Library currently. I like its simplicity though. 

> but the new one looks a little busy. 

Agreed. It's basically a filled-in group block. I'll take a few to jam on that left-most icon; there's potential there. 

CleanShot 2023-04-03 at 12 56 08

**Comment by apeatling** [comment]
Good catch, I also agree the replacement icon should be used for the open media library action as well.

**Comment by paaljoachim** [comment]
I like the new icon Rich shared here: https://github.com/WordPress/gutenberg/pull/49523#issuecomment-1494666988
It should be used in the various placeholders for media as well as in various drop downs where media is to be added. I believe that is a few places...

**Comment by richtabor** [comment]
I updated the media icon as such. Thoughts? 

CleanShot 2023-04-04 at 16 34 51
CleanShot 2023-04-04 at 16 30 54

**Comment by paaljoachim** [comment]
Hey Rich. That looks really nice! Well done!

**Review by apeatling — APPROVED** [review]
I think it's definitely an improvement, so I say LGTM. :+1:

**Pull request merged**
