### PR TITLE
Components: Update Dashicon to latest build

### PR DESCRIPTION
**Pull request by aduth**
Closes https://github.com/WordPress/gutenberg/issues/3952
Related: https://github.com/WordPress/dashicons/pull/305
Related: https://github.com/Automattic/wp-calypso/pull/25590#issuecomment-404233976 (cc @jsnajdr)

This pull request seeks to incorporate the latest version of the Dashicons React component generated from the `WordPress/dashicons` repository, which defines the component class using the `@wordpress/element` module dependency, rather than relying on the presence of a `wp.element.Component` global.

**Testing instructions:**

Verify there are no regressions in the display of icons throughout the application.

### CODE REVIEW

**Comment by jasmussen** [comment]
It'll be a little while of afk before I can test properly, so if you'd like to get this in sooner, would be good up expand the review range. But purely as a sanity check, this looks good to me 👍👍

**Review by gziolo — APPROVED** [review]
Nice 👍

**Comment by gziolo** [comment]
I think we have also a corresponding issue for it, I will try to track it down.

**Comment by jsnajdr** [comment]
Thanks for the quick fix! I updated the vendored Gutenberg in Automattic/wp-calypso#25590 to the latest version and removed another custom patch from there.

**Pull request merged**
