### PR TITLE
TRY: Text Block: Sometimes the cursor gets moved behind the first character

### LINKED ISSUE #1607: Text Block: Sometimes the cursor gets moved behind the first character
weird text bug

In the gif above, you'll notice that as soon as I start typing, my cursor gets positioned behind the first letter. Very strange.

Just a guess, but maybe something related to the drop cap feature?

### PR DESCRIPTION
**Pull request by tg-ephox**
fixes https://github.com/WordPress/gutenberg/issues/1607

Have investigated this issue a lot and was un-able to replicate in plain JS or React outside of Gutenberg. Safari behaves differently than FireFox and Chrome in that it leaves the cursor in the block when the link or button is clicked, and when typing is started again in the block after focus has moved, the selection point is lost maybe?

This fix is a little heavy handed but makes the behaviour the same as FireFox and Chrome, in that when a link/button is clicked, the cursor does not remain in the block.

### CODE REVIEW

**Comment by youknowriad** [comment]
Not an easy issue indeed. I think the fix here, breaks the formatting toolbar. Sometimes clicking formatting buttons changes the position of the caret.

**Comment by karmatosed** [comment]
@tg-ephox could you iterate based on feedback for this as would love to get this into 1.1.

**Comment by tg-ephox** [comment]
@youknowriad @karmatosed have made some progress on this.  Removed all of Gutenberg/React from `createEditorInstance` (main Gutenberg entry point) so that its just using some plain javascript to render a TinyMCE instance and a button and the issue still occurs!  My suspicion is that a plugin or another JS library is causing this, as I can't replicate it outside of Wordpress. Will start removing JS libraries next!

**Comment by tg-ephox** [comment]
@youknowriad @karmatosed this could be a TinyMCE/Safari bug... I do however have a fix but its outside the realm of Gutenberg!  If the `tabindex="0"` is removed from the div with id `wpbody-content` this issue no longer occurs.

screen shot 2017-09-01 at 3 23 37 pm

Issue can be replicated with this page.  Click on the content to focus the editor, then click the button and type again.

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
  </head>
  <body>
        <div class="gutenberg__editor" tabindex="0">
            <p id="editor" contenteditable="true">Here is some content</p>
            <button id="button">Click Me</button>
        </div>
        <script type='text/javascript'>
            document.getElementById('button').onclick = (event) => event.preventDefault();

            const tinySettings = {
                theme: false,
                inline: true,
                toolbar: false,
                browser_spellcheck: true,
                entity_encoding: 'raw',
                convert_urls: false,
                plugins: [],
                formats: {
                    strikethrough: { inline: 'del' },
                },
                target: document.getElementById('editor'),
                setup: ( editor ) => {
                },
            };

            tinymce.init(tinySettings);
        </script>
        </body>
</html>

**Comment by tg-ephox** [comment]
@youknowriad this doesn't appear to happen in current WP editor (typing then clicking the Preview button) but im not sure that the Preview button handler calls `event.preventDefault`.  I noticed also that the TinyMCE instance in the current editor is in an iframe, so this would have differences with selection and focus also...  Here is a [TinyMCE fiddle](http://fiddle.tinymce.com/IYfaab) (Safari only) that replicates the issue also.

**Comment by annaephox** [comment]
Hey @youknowriad were you able to remove tabIndex from "wpbody-content" (see highlighted part above)? Thx

**Comment by youknowriad** [comment]
@annaephox no, we're not `wpbody-content` is hard coded in the WordPress admin-header file. I think we should investigate the root problem in TinyMCE, but it's ok for me to add a temporary commented javascript hack to remove this class in `createEditorInstance` call.  Not sure if it have an impact on the UI (styling) though, we'll have to check.

**Comment by annaephox** [comment]
@youknowriad : this issue is fixed in TinyMCE 4.7
Can we close this off?

**Comment by annaephox** [comment]
@tg-ephox : reminder to test this again when Gutenberg updates to TinyMCE 4.7

**Comment by youknowriad** [comment]
@annaephox Great news, I tested on https://github.com/WordPress/gutenberg/pull/2787 and it works like a charm, no bug any more. 🎉 Thanks for the fix

**Pull request closed without merging**
