### PR TITLE
Keep the focus in the block navigation when user's last interaction was with the block navigation

### PR DESCRIPTION
**Pull request by adamziel**
## Description

PR https://github.com/WordPress/gutenberg/pull/22427 introduced an experimental ellipsis menu to the block navigation on the experimental nav management screen. Unfortunately, duplicating a block using that menu transfers the focus back to the editor area. To provide the best possible experience for users using mostly their keyboards, we should do the following:

* When the block is duplicated using the ellipsis menu in block navigation, we should `.focus()` the new item in the block navigation.
* When the block is duplicated using the editor area menu, we should `.focus()` the new block in the editor area.

I've been thinking about possible ways of approaching this issue and concluded that the editor must know whether or not it is allowed to grab the focus. This PR introduces the new editor state variable called `isAutoFocusEnabled`. The editor will only `focus()` on the new block if `isAutoFocusEnabled === true`. 

## How has this been tested?
1. Go to the experimental navigation page
1. Add a few menu items
1. Duplicate a menu item using the controls in the editor area, confirm the new block in the editor area gained focus.
1. Duplicate a menu item using the controls in the block navigation area, confirm the new block navigation item gained focus.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by adamziel** [comment]
One last issue here is that the block is not possible to select using the block navigation. This is an issue on the master branch too though, so we could probably address it in another PR.

**Review by youknowriad — COMMENTED** [review]
I know that in other similar use-cases  ( `replaceBlocks` action), instead of having an auto-focus  mode, we rely on a flag in the action to not update the selection. can't tell which approach is better but seems like some consistency would be good?

**Comment by youknowriad** [comment]
> I've been thinking about possible ways of approaching this issue and concluded that the editor must know whether or not it is allowed to grab the focus. This PR introduces the new editor state variable called isAutoFocusEnabled. 

It's not clear to me what this mode is for since in the same dropdown if you click a block, the idea is to go focus the block which kind of defeats the purpose of the mode. Is it an indication that having more description actions is maybe a better approach?

**Comment by draganescu** [comment]
The navigator should be a summarized view of the block hierarchy. They way things are going, considering we plan to manipulate all the document's structure from the navigator, we need both things to work.

I would explicitly add an action, "Go to block", that selects the block from the editor, instead of having a mode that auto selects the block when I click on it in the navigator.

The focus problem is that when I work in the context of the  summarized view of the block hierarchy I do not want to be transferred to the editor unexpectedly. I do wonder if the editor needs anything changed, or if the navigator itself has to manage its focus more thoroughly.

**Comment by adamziel** [comment]
@youknowriad @draganescu The culprit is the following excerpt from the `block-wrapper.js`:

https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-list/block-wrapper.js#L126-L130

As you can see, it will continue to "steal" the focus as long as the block is selected.

In order to move along without an autofocus mode, we would either need to:

1. Make sure the block is NOT selected when the user interacts with a related block navigation item, which may or may not defeat it's purpose, or
1. Figure out a condition different than `isAutoFocusEnabled` that would the prevent the block-wrapper from grabbing the focus

**Comment by adamziel** [comment]
> I would explicitly add an action, "Go to block", that selects the block from the editor, instead of having a mode that auto selects the block when I click on it in the navigator.

@draganescu it's the other way around :-) that mode prevents the editor from performing the default action of selecting the block

**Comment by youknowriad** [comment]
> As you can see, it will "steal" the focus when the block becomes selected.

Yes,  I know but unless  I'm wrong it could be solved by  saying "duplicate but don't select"?

**Comment by adamziel** [comment]
> Yes, I know but unless I'm wrong it could be solved by saying "duplicate but don't select"?

Right, that's correct. My assumption was that we want to select after duplicating though. Maybe it's time to take a step back and consider separating the selection in the navigator from the selection in the editor?

**Comment by youknowriad** [comment]
> Maybe it's time to take a step back and consider separating the selection in the navigator from the selection in the editor?

Does the selection in the navigation serve other purposes than just an "indication" about the block selected int the editor?

**Comment by adamziel** [comment]
> Does the selection in the navigation serve other purposes than just an "indication" about the block selected int the editor?

It's not obvious to me at the moment. In the post editor, one of the purposes the navigator serves, is to make it easy to reach a deeply nested block - it simply selects it once you click on the navigator item. In this experiment though, even though we use the navigator component, we customized it so that it no longer selects a related block on click - instead it makes it possible to quickly edit the link text.

Let's pause on this PR for a moment - I'll start a discussion in the original issue https://github.com/WordPress/gutenberg/issues/22089

**Comment by adamziel** [comment]
It seems like we're moving away from navigator items being editable by default which also solves the underlying issue behind this PR. It may re-emerge at some point, but for now this PR may be safely closed.

**Pull request closed without merging**
