### PR TITLE
Template Part placeholder - Add title step to creation flow.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Related to discussion on #29950 -  Adds a title step to the creation flow from the Template Part placeholder.  Here we prompt the user with a modal (similar to the "make template part" flow from the block settings ellipsis menu) to change the name of the title from "Untitled Template Part".  If the modal is cancelled, we revert to the placeholder and the template part is not created.

Screen Shot 2021-07-26 at 2 47 41 PM

## How has this been tested?

With FSE enabled, test the following in both the Site and Post editor:
* Insert a template part block placeholder (Header, Footer, or Template Part).
* Select the "New %s" option.  
* A naming input should appear.
* Cancelling  (or clicking outside) the modal should revert the block back to the placeholder state.
* "Create" should create the new template part with the name that was given in the input field.

## Types of changes

New feature (non-breaking change which adds functionality) 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by david-szabo97 — COMMENTED** [review]
Looking good!

Few things:

1. Template part placeholder changes when I click on the new button.
2. "Create" button is enabled when the name field is empty.


https://user-images.githubusercontent.com/2256104/127643521-c3d0312c-b73c-4cc6-a44c-2681348385e7.mov

**Comment by Addison-Stavlo** [comment]
> Template part placeholder changes when I click on the new button.

Right 🤔 .  Its moving to the patterns setup component, and since there are no patterns registered here that forwards it to the 'create blank' step of that component which triggers creation but doesn't render anything on the page....    Now after talking it out I realize we can make that step render a placeholder as well. 🤣   That seems like something we should do.

> "Create" button is enabled when the name field is empty.

Good catch!  thanks for taking a look @david-szabo97  😁

**Comment by Addison-Stavlo** [comment]
Updated so the 'create blank' step renders a placeholder, and the 'create' button in the title naming step disables if the title is blank.

Screen Shot 2021-07-30 at 8 12 27 AM

I think I may still need to follow up on some minor e2e test adjustments to accommodate the extra step in creation.

**Comment by david-szabo97** [comment]
Changes looking good! Last piece of the puzzle is the e2e test 😄

**Comment by Addison-Stavlo** [comment]
> Last piece of the puzzle is the e2e test 😄

Success

**Review by david-szabo97 — APPROVED** [review]
🚢 ✅

**Pull request merged**
