### PR TITLE
Update 'Welcome Guide' illustrations

### LINKED ISSUE #21396: Update "Welcome Guide" to match new inserter styles
The "welcome guide" is still showing white and around "insert block" buttons but these are now black and square.

Screen Shot 2020-04-03 at 19 55 42

The style of the "insert block" on the "welcome guide" should be updated to match the current style.

### PR DESCRIPTION
**Pull request by enriquesanchez**
Fixes #21396

This PR updates the illustrations used in the Welcome Guide modal to match the new editor's styles (G2).

### Before

old

### New

new

It also updates the little inline inserter icon in the description of "Get to know the block library":

Screen Shot 2020-04-09 at 13 41 57

### CODE REVIEW

**Comment by karmatosed** [comment]
Great iteration. One point which maybe is a hint at needing to change UI would be this:

image

The dots to navigate being the same background color is a little strange for me. It then seems like the background should interact.

**Review by mapk — APPROVED** [review]
Looks pretty good to me and worked well. 

I'm not sure if we have a pattern of dots elsewhere that we can pull from. If there are some quick changes that can be made to those, go for it. Otherwise, this works!

**Comment by mtias** [comment]
I would also love to try the gifs from https://github.com/WordPress/gutenberg/issues/19209 (defaulting to the static images if prefers-reduced-motion is set).

**Review by mtias — APPROVED** [review]

**Comment by enriquesanchez** [comment]
Merging these updated illustrations. I'll look at moving forward the proposal from #19209 on separate PRs.

**Pull request merged**
