### PR TITLE
added label to manage locations menu

### PR DESCRIPTION
**Pull request by Quintis1212**
Hi , I added label to manage location menu on "Navigation screen: regression of improved menu locations select placeholder #30330" issue

### CODE REVIEW

**Comment by talldan** [comment]
Hi @Quintis1212, thanks for working on this.

Looks like there are some conflicts. Just to check, when creating the branch, did you use `master` or `trunk` as the base? 

The repository now uses `trunk` as the main branch. Anything branched off of `master` will be outdated.

**Comment by Quintis1212** [comment]
> Hi @Quintis1212, thanks for working on this.
> 
> Looks like there are some conflicts. Just to check, when creating the branch, did you use `master` or `trunk` as the base?
> 
> The repository now uses `trunk` as the main branch. Anything branched off of `master` will be outdated.

Hi @talldan   ) I have created this PR from trunk , I don't know why there is a conflict. What can I do to help this PR ?I ve created branch for this PR 7 days ago

**Comment by talldan** [comment]
@Quintis1212 It seems like when you created the branch your version of trunk was out of date. I think the file you edited has since moved because there were some changes to the UI (this is where the file is nowhttps://github.com/WordPress/gutenberg/blob/trunk/packages/edit-navigation/src/components/inspector-additions/manage-locations.js).

I think your options are to either rebase or merge the latest code from trunk into your branch, fix the conflicts and push.

Or for a small change like this it might be easier to create a new branch off of (an up-to-date) trunk and use that instead.

**Comment by Quintis1212** [comment]
> @Quintis1212 It seems like when you created the branch your version of trunk was out of date. I think the file you edited has since moved because there were some changes to the UI (this is where the file is nowhttps://github.com/WordPress/gutenberg/blob/trunk/packages/edit-navigation/src/components/inspector-additions/manage-locations.js).
> 
> I think your options are to either rebase or merge the latest code from trunk into your branch, fix the conflicts and push.
> 
> Or for a small change like this it might be easier to create a new branch off of (an up-to-date) trunk and use that instead.

@talldan PR from new branch - https://github.com/WordPress/gutenberg/pull/30933

**Comment by kevin940726** [comment]
Thanks, I'll close this in favor of #30933.

**Pull request closed without merging**
