### PR TITLE
Change the write story placeholder

### LINKED ISSUE #9076: Revisit the "Write your story" prompt
I'll pre-empt this by saying this is pretty trivial and could described as bikeshedding. However, since it's the first thing a user sees, I felt like it was at least worthy of a discussion and a documented decision. 

When first creating a new post, the prompt in the content area is "Write your story". After entering any content, the prompt in the standard empty paragraph block is "Add text or type / to add content". Why are these different?

[Carl noted in his fantastic user story example](https://github.com/WordPress/gutenberg/issues/5113#issue-297909295) that this would be a strange prompt for anyone who is just using WordPress as a CMS and not for blogging or writing stories (which is a _huge_ portion of WordPress users). 

Looking back through both Slack and git history, I can't seem to find any discussion around the decision for the verbiage of this prompt, or even where this was originally introduced. It looks like it got added in #3623, but I'm not positive that it wasn't in another file before that. 

[Joen noted here](https://github.com/WordPress/gutenberg/issues/7271#issuecomment-408784686), that our goal is to optimize for both people writing text _and_ people building websites. I understand the point of this verbiage is to "[keep it human, engaging](https://wordpress.slack.com/archives/C02QB2JS7/p1520596743000139)", and I know that [it is filterable](https://github.com/WordPress/gutenberg/pull/5549), but it feels like favoring one use case over another here. 

While you can make an argument that it's generic enough to work for posts in many/most situations, it doesn't really make sense for pages in the majority of contexts. Maybe for an "About" or "History" type page, but that's 1 out of an entire site. 

Is it worth it to make them different by post type? Is it better to keep them consistent, but generalize it more so it's not so writing-specific?

### PR DESCRIPTION
**Pull request by youknowriad**
closes #9076

This PR tries to replace the "Write your story" placeholder with the paragraph placeholder "Add text or type / to add content" and also removes the default placeholder from the paragraph block.

Let me know how it feels.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
"Add text or type / to add content" has already felt a bit confusing to me. It looks like the slash is being used in an "or" kind of sense, as if the sentence says "Add text or type OR to add content", which is rather confusing. I feel like adding quotation marks around the slash would help:

>Add text or type “/” to add content

What do you think? Ideally, you would wrap the slash with a `<kbd>` element, but I don't think you can use HTML elements in the placeholder text.

**Comment by jasmussen** [comment]
Question: could we cycle through various tips? I like the idea of a few writing prompts intermingled with a few tips. Like "What's on your mind?" "Write your story..." could be two writing prompts, while "Add text or type /" etc. are essentially tips. So we could have an array of maybe 5 total, shown at random.

**Comment by youknowriad** [comment]
@jasmussen yes we can unless there's an explicitly defined prompt by the WP filter.

I'm happy to update the PR once we reach consensus between the designers :P 


@ZebulanStanphill I think it makes sense.

**Comment by 0aveRyan** [comment]
This appears a duplicate of https://github.com/WordPress/gutenberg/issues/9076

**Comment by karmatosed** [comment]
Just to summarise, right now we have 2 options being suggested?

- Add text or type / to add content in all cases.
- Rotate around a few?

If I am right my concern with rotating is consistency. I am not set on the first option as the only way to write this though. What other options are there?

**Comment by earnjam** [comment]
What about always using "Add text or type / to add content" on pages and any custom post types, but allowing the more engaging writing prompts to rotate on posts, which are generally going to be more writing-focused?

**Comment by kjellr** [comment]
> What about always using "Add text or type / to add content" on pages and any custom post types, but allowing the more engaging writing prompts to rotate on posts, which are generally going to be more writing-focused?

This seems like a solid direction to me. 👏 

Since this is primarily copy-related at this point (and since it's already received feedback from a few designers), I'm going to remove the `Needs Design Review` label and add `Needs Copy Review` to get some copy feedback. 👍

**Comment by michelleweber** [comment]
Even with the quotations marks, "Add text or type /" feels a bit confusing -- isn't typing "/" adding text? If I can just start adding text, why do i need to bother with the /? Or does adding text specifically mean pasting?

**Comment by 0aveRyan** [comment]
@michelleweber I agree it feels a little awkward and doesn't explain itself. What are your thoughts on `Add text... Type / to insert a block`?

I realize there are already some contrast issues, but it'd be great to have a small, distinguishing design treatment for the <kbd>/</kbd> so it doesn't feel like a substitute for `or`.

screen shot 2018-09-06 at 5 29 09 pm

**Comment by jasmussen** [comment]
Placeholder contrast will be addressed when https://github.com/WordPress/gutenberg/pull/9562 is merged. 

I think the point about making sure slash is not mistaken as "or" is a great point, but are there any verbiage changes we can make instead to ameliorate this?

Also worth noting that the slash command is noted in the Keyboard Shortcuts sheet now:

screen shot 2018-09-07 at 11 03 45

I'm personally of the opinion that while the slash command is great, it's okay that it's treated as a power user feature. I think if people start to think it's a primary way of inserting blocks, it will be a turnoff.

**Comment by michelleweber** [comment]
Typing the slash doesn't insert a text block, it pulls up a list of blocks you can add, right? If that's right, "Add text... Type / to insert a block" kinda makes it sound like all you can do is add text/a text block. It seems like we want something more like "To add a text block, just start writing. For quick access to  other common blocks, type a /."

**Comment by kjellr** [comment]
> "To add a text block, just start writing. For quick access to other common blocks, type a /."

What about something like: `Start writing or type / to choose a block`?

> I'm personally of the opinion that while the slash command is great, it's okay that it's treated as a power user feature. I think if people start to think it's a primary way of inserting blocks, it will be a turnoff.

I agree. I wonder if we can actually eliminate mention of the slash command from this placeholder and put it in a tip or something? If this is a power user feature, it doesn't make sense to show it on every single new line.

**Comment by jasmussen** [comment]
> Start writing or type / to choose a block?

I like that a lot.

> I wonder if we can actually eliminate mention of the slash command from this placeholder and put it in a tip or something? If this is a power user feature, it doesn't make sense to show it on every single new line.

Possibly. For now, though, this is the primary way, based on the feedback we've received in chat and on Twitter, that people have discovered how to use the command. I suppose it's fine that they don't discover it at all, or have to dive into the keyboard shortcuts sheet to find it:

screen shot 2018-09-10 at 08 53 48

But we've actually also seen a bunch of angry users that were frustrated that it wasn't more discoverable, "because the feature was so cool". 

At some point I discussed with @talldan a way to surface a tip only after you'd started pressing Tab (try this in Slack, it shows you a tip as soon as you start tabbing). That could be a neat way to do it. But until that time, perhaps it'd be good to keep this around.

**Comment by youknowriad** [comment]
closing in favor of #11560

**Pull request closed without merging**
