### PR TITLE
Mobile - Link - Fix clipboard keeping previous state

### LINKED ISSUE #3056: Autofill URLs aren't updated if a new URL is copied
**Describe the bug**
Selecting new text does not update the autofill for links

**To Reproduce**
1. Go to a new post or page 
2. Type some text 
3. Leave the app to copy a URL
4. Highlight some text and open the link picker. 
5. Notice the URL has been auto-populated
6. Leave the app to copy a different URL
7. Highlight some new text and open the link picker. 
8. Notice the **OLD** URL has been auto-populated
9. Copy a non URL text
10. Highlight some new text and open the link picker. 
11. Notice the **OLD** URL has been auto-populated

**Expected behavior**
The auto-populated URL should reflect what is currently in the clipboard. 

**Smartphone (please complete the following information):**

iOS:
 - Device: iPhone 11
 - OS: iOS 13.5.1
 - Tested in WP iOS 16.5

Android:
 - Device: Pixel 3a
 - OS:  Android X
 - Version: 29
 - Tested in WP Android 16.5

### PR DESCRIPTION
**Pull request by geriux**
## Description
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/3056

Setting different links from the clipboard in the same Paragraph block is not working correctly, the first link won't update after new links have been copied.

This PR resets the stored copied link from the clipboard once the link modal has been closed.

## How has this been tested?

**Using the same Paragraph block**

1. Go to a new post or page
2. Add a Paragraph block and type some text
3. Leave the app to copy a URL
4. Highlight some text and open the link picker.
5. **Expect** to see the URL has been auto-populated
6. Leave the app to copy a different URL
7. Highlight some new text from the same block and open the link picker.
8. **Expect** to see the **new** URL has been auto-populated
9. Copy a non URL text from the same block
10. Highlight some new text and open the link picker.
11. **Expect** to **not see** a link auto-populated

### Before
https://user-images.githubusercontent.com/4885740/106293864-c494f680-624e-11eb-9b0c-871e72b48ae0.mov

### After
https://user-images.githubusercontent.com/4885740/106294003-ef7f4a80-624e-11eb-8c5c-7391db41b8c9.mov

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by chipsnyder — APPROVED** [review]
This is working great now Nice work @geriux!

**Comment by fluiddot** [comment]
👋 I was wondering if we should include this fix in the [`CHANGELOG` file](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-editor/CHANGELOG.md), what do you think?

If so let me know because since these changes will be included in the beta fix `1.46.1`, I can include it in the release notes too.

**Comment by geriux** [comment]
> 👋 I was wondering if we should include this fix in the [`CHANGELOG` file](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-editor/CHANGELOG.md), what do you think?
> 
> If so let me know because since these changes will be included in the beta fix `1.46.1`, I can include it in the release notes too.

I feel like this is a bit of an edge case not many users encountered so I don't think we should include it as a user-facing release note.

**Comment by fluiddot** [comment]
> > 👋 I was wondering if we should include this fix in the [`CHANGELOG` file](https://github.com/WordPress/gutenberg/blob/master/packages/react-native-editor/CHANGELOG.md), what do you think?
> > If so let me know because since these changes will be included in the beta fix `1.46.1`, I can include it in the release notes too.
> 
> I feel like this is a bit of an edge case not many users encountered so I don't think we should include it as a user-facing release note.

Ok, makes sense if it's a bit of an edge case, thanks for the info!

**Pull request merged**
