### PR TITLE
Move the default heading styles from editor styles to theme.scss

### PR DESCRIPTION
**Pull request by youknowriad**
The goal of this PR is always the same of #29517 and #29556: Make frontend and backend look similar by default.

The way we achieve that is that we should empty the "editor-styles.scss" because this file applies styles the backend that the them don't necessarily have. So our options are something like:

 1- Remove these styles.
 2- Apply these styles to both frontend and backend by default
 3- Only apply these styles in both frontend and backend if the theme opt-into the opinionated theme styles.

The current implementation in this PR does 3 (moves the default heading styles from editor-styles to theme.scss), This can be impactful for themes with the opt-in true. I'm not sure yet if this is the best approach or we should go with "1" instead. Let's test in some themes and gather opinions. 

**Edit:** Found a better solution explained here https://github.com/WordPress/gutenberg/pull/29588#issuecomment-791452141

### CODE REVIEW

**Comment by jasmussen** [comment]
Love this. I'd love @kjellr thoughts on it, but I think it's time.

`revert` is new to me! Nice!

**Comment by youknowriad** [comment]
I changed my mind :) and found a better fix IMO.

This fix uses the "revert" value to override the wp-admin styles for headings and "revert" to the browser defaults for these styles unless a theme provides its own editor styles which are going to be higher specificity.

I think this is the ultimate fix :P I'm tempted to use that for all the other things  in the editor-styles.scss file (I'll do separately if this works well).

[Revert is supported](https://caniuse.com/?search=revert)  in 89% of the browsers and probably something like 96% of the browsers we actually support. I think it's fine because what will happen if the browser doesn't support it is just that the editor won't look exactly like the frontend by default, so I think it's a good progressive enhancements strategy.

I'd love some testing in various themes for this PR.

**Comment by scruffian** [comment]
Yeah my concern with the previous suggestion is that it wouldn't work if the theme opted out of block styles, because of this issue: https://github.com/WordPress/gutenberg/pull/29252

**Comment by youknowriad** [comment]
If this proves to be good solution I'll update the list PR to do the same.

**Comment by scruffian** [comment]
In "empty theme" the margins look different. Editor:
Screenshot 2021-03-05 at 14 42 00

Front end:
Screenshot 2021-03-05 at 14 42 05

I suppose this is because somewhere in the context a different base is being set, but I couldn't find where.

**Comment by youknowriad** [comment]
> I suppose this is because somewhere in the context a different base is being set, but I couldn't find where.

I think it might be because of the default block margins applied to all blocks in the editor but I'll confirm.

**Comment by scruffian** [comment]
The margins are exactly the same value in ems in the inspector, it's just that the browser is displaying an em at different sizes.

**Comment by scruffian** [comment]
Actually it's not the margins at all it's the line-height, which is coming from this line: https://github.com/WordPress/gutenberg/blob/da8555d258edbe676fa079fb51252f918ae032e1/packages/editor/src/editor-styles.scss#L14

**Comment by scruffian** [comment]
Changing to `line-height: initial` fixes it.

**Comment by youknowriad** [comment]
> Changing to line-height: initial fixes it.

yes, that's a good fix but I'll leave all the "body" things for later (to be edited in one go)

**Comment by youknowriad** [comment]
@scruffian https://github.com/WordPress/gutenberg/pull/29590 this PR builds on top of the current one and applies bigger changes to the wrapper, lists and paragraphs. I mostly wanted to "validate" the approach and probably land it in smaller pieces starting with the current one for headings.

**Comment by youknowriad** [comment]
Ok let's close in favor of #29590 which is more ambitious but better.

**Pull request closed without merging**
