### PR TITLE
Build: remove global install of latest npm since we want to use the paired node/npm version

### PR DESCRIPTION
**Pull request by gwwar**
## Description

When running `./bin/setup-local-env.sh` this tells the node version manager nvm to switch to the current Node LTS line. However we also have a line `npm install npm -g` that also installs the latest npm version (unpaired) and pollutes the local nvm cache. 

For example on a local system with v10.16.3 not installed yet we should see v10.16.3 paired with (npm v6.9.0)

```bash
$ nvm install v10.16.3
Downloading and installing node v10.16.3...
Local cache found: $NVM_DIR/.cache/bin/node-v10.16.3-darwin-x64/node-v10.16.3-darwin-x64.tar.xz
Checksums match! Using existing downloaded archive $NVM_DIR/.cache/bin/node-v10.16.3-darwin-x64/node-v10.16.3-darwin-x64.tar.xz
Now using node v10.16.3 (npm v6.9.0)
```

Now try running `npm install npm -g` and check the nvm versions, we can see that the cache will now always point at the wrong pairing when switching.
```
$ npm install npm -g
/Users/kerryliu/.nvm/versions/node/v10.16.3/bin/npm -> /Users/kerryliu/.nvm/versions/node/v10.16.3/lib/node_modules/npm/bin/npm-cli.js
/Users/kerryliu/.nvm/versions/node/v10.16.3/bin/npx -> /Users/kerryliu/.nvm/versions/node/v10.16.3/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.11.1
added 19 packages from 13 contributors, removed 15 packages and updated 52 packages in 5.647s
$ nvm install v10.16.3
v10.16.3 is already installed.
Now using node v10.16.3 (npm v6.11.1)
```

This PR removes the `npm install npm -g` line so we don't point at edge npm in bin/setup-local script. This also updates travis.yml to not install edge npm.

## Testing Instructions:

- Travis should be green ✅
- Uninstall your cached LTS version: `npm uninstall v10.16.3`
- Run `./bin/setup-loacal-env.sh`, with a missing node version you'll be prompted to nvm install. Verify that the success message says: `Now using node v10.16.3 (npm v6.9.0)`
- Run `./bin/setup-local-env.sh`. Local dev should work as expected. 

```bash
$ ./bin/setup-local-env.sh 
WARNING: Node version does not match the latest long term support version. Please run this command to install and use it:
WARNING: nvm install
WARNING: After that, re-run the setup script to continue.
$ nvm install
Found '/Users/kerryliu/checkouts/gutenberg/.nvmrc' with version <lts/*>
Downloading and installing node v10.16.3...
Local cache found: $NVM_DIR/.cache/bin/node-v10.16.3-darwin-x64/node-v10.16.3-darwin-x64.tar.xz
Checksums match! Using existing downloaded archive $NVM_DIR/.cache/bin/node-v10.16.3-darwin-x64/node-v10.16.3-darwin-x64.tar.xz
Now using node v10.16.3 (npm v6.9.0)
```

### CODE REVIEW

**Comment by pento** [comment]
@gwwar: I'm cool with this PR. Can you remove it from `.travis.yml`'s `before_install` section, too? Travis is currently failing because of that.

**Comment by gwwar** [comment]
That look about right @pento? I'm guessing Travis should go green then 😄

**Comment by pento** [comment]
Yah, that looks right. Let's see what happens!

**Review by pento — APPROVED** [review]
💖

**Comment by gwwar** [comment]
Thanks for the quick review @pento !

**Comment by ntwb** [comment]
I realize the npm bug introduced recently was unfortunate, I believe this has since been fixed in a subsequent version...

The advantages of using the latest npm (not withstanding new releases with bugs) are primarily having the bug fixes in 6.9.0 fixed with 6.9.1 for starters, likewise for the 6.10.x and 6.11.x range of releases that include bug fixex.

The change in this PR goes back on a decision made quite some time ago to *not* to use the "paired" version of npm that ships with Node.js, and always use the latest npm release when possible:

> As noted in the docs [here](https://github.com/WordPress/gutenberg/blob/2a10279f45debec2746ee59345073eae7bb2a100/docs/contributors/getting-started.md#getting-started)
>
> _"You also should have the latest release of npm installed. npm is a separate project from Node.js and is updated frequently. If you've just installed Node.js which includes a version of npm within the installation you most likely will need also to update your npm installation. To update npm, type this into your terminal: npm install `npm@latest -g`"_

Using the latest release of npm is also a recommendation of the npm team themselves:

> https://www.npmjs.com/get-npm
>
> _"npm is a separate project from Node.js, and tends to update more frequently. As a result, even if you’ve just downloaded Node.js (and therefore npm), you’ll probably need to update your npm."_

Lastly, `nvm` itself supports installing the latest npm via the `--latest-npm` cli flag:
> _"After installing, attempt to upgrade to the latest working npm on the given node version"_

**Comment by nerrad** [comment]
Given what @ntwb has written above, should we revert?

**Comment by gwwar** [comment]
Is there a specific feature we're looking for to run edge? Node releases are tested with specific npm versions. We'll be okay now but I'd expect more bugs/complications if major versions of npm aren't in sync.

https://nodejs.org/en/download/releases/

**Comment by ntwb** [comment]
> Is there a specific feature we're looking for to run edge? Node releases are tested with specific npm versions. We'll be okay now but I'd expect more bugs/complications if major versions of npm aren't in sync.

Node,js and npm are not developed to be "in sync", npm is developed independently of the Node.js project and the recommended version to be used is the latest version of npm that ships with bug fixes for any currently supported Node.js version.

npm edge versions are shipped as [npm canary](https://www.npmjs.com/package/npmc)

Historically in this project we've not seen many issues with updated releases of npm, we did have significant issues when npm introduced the `package-lock.json` file in the 5.x releases, so much so it was imperative that we updated the 5.x versions to the latest release due to the number of bugs initially shipped in 5.0

**Pull request merged**
