### PR TITLE
Visual polish on the prototypes.

### PR DESCRIPTION
**Pull request by jasmussen**
This replaces Merriweather with Noto Serif as discussed in a meeting. It also adjusts the active states for buttons.

The font change affects all prototypes.

As a sidenote, setting an alignment doesn't update the active state. Getting an undefined error for `updateBlockControlsPosition`, which doesn't seem to be a function in the code. Did this regress somehow?

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
@jasmussen I fixed the `updateBlockControlsPosition` regression in 852daf1. Sorry about that :)

The updated CSS/Fonts are looking great (I do prefer the old lighter toolbars, but I understand the accessibility issues)

**Comment by jasmussen** [comment]
Thank you!

The `is-active` isn't set on the button that toggles the alignments, though:

screen shot 2017-03-08 at 12 51 14

Perhaps we never got that working initially?

**Comment by iseulde** [comment]
Looking good! Should the button icons be lighter by default? It makes it slightly less readable.

**Comment by iseulde** [comment]
If we opt for a border, maybe just on the bottom makes is slightly less busy?

screenshot 2017-02-23 19 55 41

**Comment by iseulde** [comment]
> Going to see if I can do some sharing of styles across the prototypes, so we can normalize.

I can add the style for the single MCE one if you like.

**Comment by jasmussen** [comment]
> I can add the style for the single MCE one if you like.

I'd like to try and explore the shared CSS file a bit further, see if we can do some magic here. I could also swear I saw a SASS variable somewhere, which would be a great way to normalize colors.

**Comment by youknowriad** [comment]
> Perhaps we never got that working initially?

@jasmussen Yes, we never updated the active button on the alignment toolbar

**Comment by jasmussen** [comment]
> If we opt for a border, maybe just on the bottom makes is slightly less busy?

Let's try the full border for now, see how it feels when we use it everywhere. This is yet another aspect I suspect will keep getting tuned.

**Pull request merged**
