### PR TITLE
Fix design of color/gradient controls in editor panel

### PR DESCRIPTION
**Pull request by stokesman**
#23802 had a lot of good improvements and this follows up on that addressing three issues.

1. Since it was merged the default position of labels in `SelectControl` changed #25427, throwing the alignment off in `CustomGradienPicker`.

2. The change to make the swatches align on the right side with their neighboring controls https://github.com/WordPress/gutenberg/pull/23802#issuecomment-681867143 currently only works when there is no scrollbar on the settings sidebar and can be improved to work with or without scrollbars.

3. The "dial" of the `AnglePickerControl` was able to push out of alignment (to the right) when the settings sidebar has a scrollbar.

All of the above can be noted in the "before" screen capture below.

Before | After
----|----
color-gradient-panel-before | color-gradient-panel-after

<details>
<summary>After screen recording comparing settings sidebar with and without overflow</summary>

</details>

<details>
<summary>Before screen recording comparing settings sidebar with and without overflow</summary>

</details>

An aside is the `AnglePickerControl` gets a default label which according to its readme it already had. 

## How has this been tested?
Wordpress 5.5.1, Chrome 85
Resolutions from 280 to 1440.

## Types of changes
Non-breaking design fixes
Accessibility fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by stokesman** [comment]
CC @jasmussen and @ItsJonQ because of their work in #23802

**Review by jasmussen — APPROVED** [review]
This is a good one. 

Before:

Screenshot 2020-10-19 at 18 37 52

After:

Screenshot 2020-10-19 at 18 40 26

I was worried that the "Type" label would be vastly longer in german or other languages, though it appears that particular phrase hasn't yet been widely translated. So I manually found the longest version of "Type" that I could on Google Translate, and even in (what I hope is) Malay it works:

Screenshot 2020-10-19 at 18 44 13

Well done. And thank you.

I would love for this to get a few more code-review eyes before merge, but from what I can tell, this is solid, including the code. Nice little win.

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Great use of the `Flex` components @stokesman . That `5/4` combo is an interesting one! :)

**Comment by stokesman** [comment]
Thanks for reviewing Joen and Jon!

**Pull request merged**
