### PR TITLE
Dom Package: Fix `placeCaretAtHorizontalEdge`

### LINKED ISSUE #26983: DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement'
Reported by bradmarshall:
https://core.trac.wordpress.org/ticket/51577

-----

Actual behaviour:
dom.js is attempting to access the `selectionStart` property on input[type=email] in Gutenberg running WordPress 5.5.1, which triggers a DOM exception in the WP admin which breaks the gutenberg block containing the input.

Why?
This MDN article (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) states that only certain types of inputs and textareas impmlement selectionStart / selectionEnd but it looks as though numerous functions throughout the file attempt to use selectionStart/selectionEnd without first qualifying the type of input in question. Therefore, any input[type=email] elements in a block are crashing out.

Expected behaviour:
dom.js should not attempt to use selectionStart/selectionEnd on just any type of input - it should instead first check to make sure it's one of type=text, search, URL, tel or password. Gutenberg blocks containing input types other than these should not crash.

Version: 
WordPress 5.5.1

### LINKED ISSUE #47439: Business Hours Block: Breaks on List View
#### Steps to reproduce

1. Create a new page
2. Add the Business Hours block
3. Deselect the block, and then select it again using the List View option

#### What I expected
For the Business Hours block be selected.

#### What happened instead
It shows the error `This block has encountered an error and cannot be previewed.`

#### Screenshot / Video
BusinessHoursBlockIssue

#### Browser / OS version
OS X 10.15.7
Chrome 86.0.4240.193

#### Context / Source
#dogfooding

### PR DESCRIPTION
**Pull request by jeyip**
## Description

When using the list view to select a jetpack Business Block, the execution thread was invoking `placeCaretAtHorizontalEdge` from the `dom` library. `placeCaretAtHorizontalEdge` was, however, attempting to reassign `selectionStart` and `selectionEnd` on HTML Input Elements, and unfortunately, not all input types support those attributes. See [relevant documentation](https://html.spec.whatwg.org/multipage/input.html#do-not-apply).

https://github.com/WordPress/gutenberg/blob/d27e094d2bac7a5d1bdfd55598007563324e10e3/packages/dom/src/dom.js#L290-L297

Because the business block was using "time" input elements, the block broke.

## How has this been tested?

- Set up local instance of WordPress with Gutenberg
- Install Jetpack plugin
- Navigate to page or post editor
- Insert a paragraph block and add text content
- Insert a business hours block
- Focus on the paragraph block
- From the list view, focus on the business hours block
- Confirm that the block no longer errors on focus

### Before
BusinessHoursBlockIssue
## Types of changes

Fixes https://github.com/Automattic/wp-calypso/issues/47439

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — COMMENTED** [review]
See also https://github.com/WordPress/gutenberg/pull/26074.

The same feedback on that fix seems to apply here:
> The issue that I noticed when testing is that up/down arrow key navigation doesn't work in the same way for email inputs as it does for other inputs (see the search block for an example), the input is essentially a trap for navigating between blocks unless the user switches to navigation mode using escape.

**Comment by jeyip** [comment]
Really good observation @talldan.

I can confirm that, at the very least, the behavior from the "time" input matches that of a native "time" HTML input (pressing up and down arrow keys will update hours and minutes). 

I think the concern about the regression in keyboard accessibility is fair, but given that this issue seems to make multiple blocks uneditable and #26074 has been open for about a month, I'm wondering if it's worthwhile to merge either #26074 or my fix and handle keyboard problems in the future. Either way, happy to defer to your expertise @ellatrix

**Comment by talldan** [comment]
> I can confirm that, at the very least, the behavior from the "time" input from the Business Hours block in this pull request matches that of a native "time" HTML input (pressing up and down arrow keys will update hours and minutes).

That would seem to be a problem where up/down has two uses. I'm not sure how a user can get to get to the previous/next block if one of these inputs is first/last in a block's interface. Tab is used for accessing the block settings or block toolbar.

Currently the best thing seems to be using navigation mode, but I don't think that a very discoverable feature and probably shouldn't be the default way to navigate.

So there are probably two separate issues:
- Inputs like `date` implicitly use arrow keys, and overriding this for switching between blocks is probably bad practice, but leaving the user with navigation mode as the only way to get between blocks is also not the best experience.
- Some inputs like `email` don't support `selectionStart`, but could probably behave just like `text` inputs in blocks and still support up/down arrow key navigation between blocks (at least I'm not aware of any native interaction that would prevent it?).

**Comment by jeyip** [comment]
> So there are probably two separate issues:
>
> - Inputs like date implicitly use arrow keys, and overriding this for switching between blocks is probably bad practice, but leaving the user with navigation mode as the only way to get between blocks is also not the best experience.
> - Some inputs like email don't support selectionStart, but could probably behave just like text inputs in blocks and still support up/down arrow key navigation between blocks (at least I'm not aware of any native interaction that would prevent it?).

Totally agree with your breakdown. We _could_: 

1. use a text input with a time-based input mask
2. override the traditional behavior of a time input 

Neither seem ideal for accessibility. @talldan Do you happen to know who I'd reach out to get to a resolution on this decision?

**Comment by jeyip** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/pull/28559

We can always reopen this if it seems promising again 🙂

**Pull request closed without merging**
