### PR TITLE
Site Editor Sidebar: remove `hasGlobalStyleVariations` condition for the Styles nav item

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Follow up to https://github.com/WordPress/gutenberg/pull/67537

cc @Mayank-Tripathi32  

👋🏻 

1. Remove `hasGlobalStyleVariations` condition to show the Styles menu item in the edit site sidebar.
2. Also, move its `uid` and `to` props to `MainSidebarNavigationContent` for consistency and convenience.

## Why?

The sidebar navigation styles item [now contains the global styles UI](https://github.com/WordPress/gutenberg/pull/65619) and no longer just the variations. For this reason it's okay to remove the condition. 

## Testing Instructions

1. Use a block theme without style variations, like https://wordpress.org/themes/onyxpulse/
2. In "mobile" view (narrow viewport) open Appearance > Editor
3. Select Styles. Ensure that you can see the Global Styles UI
4. Switch to a theme with style variations, e.g., https://wordpress.org/themes/twentytwentyfive/
5. Select Styles. Ensure that you can see the Global Styles UI.

## Screenshots or screencast 

https://github.com/user-attachments/assets/71457419-2fcd-47c8-a622-f5e1b5d16dff

### CODE REVIEW

**Review by tellthemachines — COMMENTED** [review]
The change makes sense to me but I'm struggling to reproduce the issue with themes without variations (I'm testing by removing the variation from Empty Theme).

**Comment by ramonjd** [comment]
> The change makes sense to me but I'm struggling to reproduce the issue with themes without variations (I'm testing by removing the variation from Empty Theme).

Thanks for testing @tellthemachines 

I installed the theme [onyxpulse](https://wordpress.org/themes/onyxpulse/), which doesn't have variations.

**Review by tellthemachines — APPROVED** [review]
I know what happened, I tested trunk after #67537 was already merged 😄 

LGTM!

**Comment by priethor** [comment]
Since this is just a code quality follow-up to #67537 and generates conflicts with 19.8, let's skip the backport to 19.8. Thanks for following up with the polishing, though! ❤️

**Comment by ramonjd** [comment]
Sorry, I forgot to remove the label. Thank you!

**Pull request merged**
