### PR TITLE
Update pattern import menu item

### PR DESCRIPTION
**Pull request by jameskoster**
Follow-up to https://github.com/WordPress/gutenberg/pull/54337.

## What?
Update the appearance / label of the pattern import menu item.

### Before
Screenshot 2023-09-25 at 11 06 39

### After
Screenshot 2023-09-25 at 11 24 33

## Why?
The `upload` icon is more indicative of the action. The shorter label is less noisy and a bit easier to interpret at a glance.

### CODE REVIEW

**Comment by carolinan** [comment]
But is the label descriptive enough for users to understand they can't import template parts?

**Comment by carolinan** [comment]
I guess this has already been discussed, but many people who see this will not know what .json or JSON is.

**Comment by kevin940726** [comment]
> But is the label descriptive enough for users to understand they can't import template parts?

This is my only concern. Otherwise this looks better than before!

**Comment by jameskoster** [comment]
Is there any reason that template parts cannot be imported? 🤔 

> I guess this has already been discussed, but many people who see this will not know what .json or JSON is.

Agreed, but I think there needs to be _some_ hint about what filetype is accepted. I hoped including the `.` prefix + lowercase might help compared to plain "JSON" which is more ambiguous.

**Comment by jasmussen** [comment]
Icon seems better. No personally strong opinion on the label.

**Comment by t-hamano** [comment]
I think we need to think about the balance with the export menu.

Personally, I think it's fine to keep the current label. This is because when selecting files to import, you should be limited to only files with the `.json` extension (this is true on Windows, but it's also true on MacOS, right?)

export

**Comment by jameskoster** [comment]
> This is because when selecting files to import, you should be limited to only files with the .json extension

This is true, but my point is that .json isn't going to be familiar to less technical WordPress users. If you're not already familiar with that filetype then "JSON" could be ambiguous. Is it software, a library, something else? There's nothing in the UI to guide them to the correct filetype. 

Agree it should be consistent with the export action though. So happy to tackle the label separately.

**Review by t-hamano — APPROVED** [review]
LGTM! Regarding labels, I realized that the UIs of other importers/exporters might be helpful.

### Theme Export (.zip)

export-theme

### Export Posts (.xml)

download

### Import Posts (.xml)

import-post

### Download Personal Data (.zip)

download-personal-data

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-beta3 branch to get it included in the next release: e93d3487fe

**Pull request merged**
