### PR TITLE
Fix icon size regression

### PR DESCRIPTION
**Pull request by jasmussen**
This PR fixes an icon size regression that was introduced in #9828. Basically SVG icons are _between 20 and 24px_.

If an SVG has an explicit width, it uses that width, within the boundaries of those extremes. But unfortunately it also means if the SVG _doesn't_ have an explicit width or height, it collapses to the min-width and min-height.

This PR updates documentation, and adds explicit dimensions for all block icons used.

Before:

screen shot 2018-10-23 at 11 34 25

After:

screen shot 2018-10-23 at 11 39 07

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
@jasmussen I think this is actually another issue. In the BlockIcon component, we should be enforcing `width="24"` and `height="24"` if those attributes aren't provided:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-icon/index.js#L24-L25

I'm inclined to think this is related to all the React Native-related SVG refactoring… cc @gziolo 

That said I think it's good for this to land either way — better to be explicit about width/height if possible because it encourages users to do the same!

**Review by chrisvanpatten — APPROVED** [review]
Approving for the explicitness of providing width/height (I think it's good for us to be explicit) but we should still look into why the default width/height attributes aren't being applied inside `<BlockIcon />`.

**Comment by jasmussen** [comment]
> In the BlockIcon component, we should be enforcing width="24" and height="24" if those attributes aren't provided:

I really like the sound of that, and I'd like to do that in this branch. Let me see if I can.

**Comment by jasmussen** [comment]
Boy that's a gnarly rebase. Something big just changed with embeds that moved it all elsewhere. I might do a complete _re-do_ of this one. Apologies if that requires an extra ping.

**Comment by jasmussen** [comment]
Interesting, from a casual dive into the BlockIcon component, it looks like it _should_, as Chris suggests, output explicit widths and heights on each icon, according to https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-icon/index.js#L25. @gziolo you are stronger than me in code, can you figure out why those attributes aren't properly output?

**Comment by chrisvanpatten** [comment]
@jasmussen Sorry yes that was slightly confusingly worded — I meant that it should already be enforcing that 24 default 😄 

There was a lot of work done around the move to the React Native-friendly version of the SVG component so my guess is that it's connected to that work.

**Comment by jasmussen** [comment]
Closing this in favor of #10987.

**Pull request closed without merging**
