### PR TITLE
Site Editor: Add template part missing state

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
If a template part has been deleted or unavailable for some reason, we had a spinner loading infinitely. Added a `missing` state to the block to be more user friendly.

NOTE: We have a [regression](https://github.com/WordPress/gutenberg/issues/28153) that doesn't show the spinner. So if you test on master right now, then you will only see an empty template part block with no spinner. If you checkout to this branch you will see the warning.

## How has this been tested?
1. Open site editor
2. Add Template Part block, create a new template
3. Add some content
4. Save
5. Go to WP Admin -> Appearance -> Template parts
6. Delete your new template part
7. Go back to site editor
8. Make sure you see the warning instead of an empty template part block (or infinitely loading spinner)

## Screenshots 
image

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I didn't test but the changes make sense to me.

**Review by mattwiebe — APPROVED** [review]
Nice improvement! Works well for me in testing.

**Review by vindl — COMMENTED** [review]
This is working fine for me too. One minor detail that could be improved is the vertical centering of the warning message:

Screenshot 2021-01-18 at 22 54 02

The bottom margin on `block-editor-warning__message` is throwing it off.

**Comment by david-szabo97** [comment]
> This is working fine for me too. One minor detail that could be improved is the vertical centering of the warning message:
> 
> Screenshot 2021-01-18 at 22 54 02
> 
> The bottom margin on `block-editor-warning__message` is throwing it off.

Created a PR to fix it in the component: https://github.com/WordPress/gutenberg/pull/28316

**Review by vindl — APPROVED** [review]
> Created a PR to fix it in the Warning component: #28316

Thanks! :shipit:

**Pull request merged**
