### PR TITLE
Site Editor: Allow all classic themes to access Patterns page

### PR DESCRIPTION
**Pull request by t-hamano**
Part of #52150 
Core ticket: https://core.trac.wordpress.org/ticket/58827

## What?
This PR allows client-side access to the Patterns page for all non-block themes.

tt1-site-editor

## Why?
Currently, only classic themes that support `block-template-parts` can use the Template Parts Editor in the Site Editor.

Starting with WordPress 6.3, all themes can create unsynced patterns. For non-block themes, the Patterns page in the Site Editor is not accessible, so users always need to use the WP-Admin style pattern editing UI.

However, I believe the Patterns page in the Site Editor is designed to be available regardless of the type of theme.

## How?
This PR permits the following in the classic theme:

- Allow access to the Patterns page via the Command Palette
- On the Patterns page, do not display the "Manage all template parts" menu only for classic themes without `block-template-parts` support.
- When the back button is pressed on a Template Part page, it takes the user to the Patterns page instead of the dashboard.

### Preparation

If this change makes sense, I would like to propose the following changes in the core after this PR is merged:

- For all classic themes, display the Patterns menu item in the Appearance menu, regardless of whether it supports `block-template-parts` or not (Do not show the Template Parts menu).
- When a browser is reloaded or accessed from outside the Site Editor, allow access if the page is a permitted page in that theme.

For now, comment out the following to temporarily allow access:
https://github.com/WordPress/wordpress-develop/blob/54a177910a80083930ee1284f648c1db5bf2e5c0/src/wp-admin/site-editor.php#L22-L32

To test the hybrid theme, you may want to use the wp-env test environment that has Emptyhybrid theme (`localhost:8889/wp-admin`).

### Block Theme

All operations are still possible and there should be no commands, pages, or UI that will be unavailable in this PR.

### Hybrid Theme (Emptyhybrid)

- Activate Twenty Twenty One theme.
- Open the Post Editor.
- Execute the "Patterns" action from the Command Palette.
- The Site Editor's Patterns page should appear.
- The 'Create template part' button should not appear in the drop-down.
- Should be able to perform all operations related to the pattern.
- Should be able to access the All template parts page.
- Template parts should not be able to be created.
- If you press the back button continuously, you should move in the order "All template parts", "Patterns", Dashboard.

### Classic Theme (Twenty Twenty One)

- Activate Twenty Twenty One theme.
- Open the Post Editor.
- Execute the "Patterns" action from the Command Palette.
- The Site Editor's Patterns page should appear.
- The 'Create template part' button should not appear in the drop-down.
- The "Manage all template parts" button should not appear.
- Should be able to perform all operations related to the pattern.
- Pressing the back button should take you to the dashboard.

## About Backward Compatibility

My concern is that unless the Patterns menu item is added to the core side and the classic theme has access to Patterns page, it will not work ideally.

Specifically, classic themes that support `block-template-parts` can access the Template Parts page from the template parts menu item in the admin panel. However, the pattern page cannot be accessed directly, and the back button must be pressed once from the template parts page.

So, if this feature is implemented in WP6.4, then the above inconsistency will occur until the minimum WordPress version supported by the Gutenberg plugin is raised to 6.4.

If you have a better approach to resolving this issue, please let me know.

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for your efforts in improving access to the Patterns site editor page for non-block-themes @t-hamano.

It appears we have an issue we with the pattern commands available in the command palette. While testing this I noticed two patterns related commands. 

Screenshot 2023-09-01 at 4 21 48 pm

It looks like https://github.com/WordPress/gutenberg/pull/53496 introduced the more recent command when it probably needed to just update the [existing one](https://github.com/WordPress/gutenberg/blob/trunk/packages/core-commands/src/admin-navigation-commands.js#L43-L63) that took into account whether or not the user could access the site editor's pattern page. 

I imagine we need to consolidate those commands before applying the new logic here.

cc/ @glendaviesnz & @richtabor 

I'm also not sure what the current thinking is around allowing classic themes to access the patterns page just yet. If we proceed with this PR, I get the feeling we should also be cleaning up the access to the template parts list page etc as well.

Alternatively, perhaps a tracking issue to make sure we don't leave any loose ends here would help.

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

> It looks like #53496 introduced the more recent command when it probably needed to just update the existing one that took into account whether or not the user could access the site editor's pattern page.

I agree. I have submitted #54133 which fixes this issue.

>I'm also not sure what the current thinking is around allowing classic themes to access the patterns page just yet. If we proceed with this PR, I get the feeling we should also be cleaning up the access to the template parts list page etc as well.

The issue of compatibility between the classic theme and the command palette or site editor has often been addressed. Here is an example, which I believe is compatible enough for now, except for the duplication of pattern commands you reported.

- #52656
- #52884
- #52154
- #52987
- #53123

**Comment by glendaviesnz** [comment]
> I'm also not sure what the current thinking is around allowing classic themes to access the patterns page just yet.

I think it would be good to get some design input into this to see if we can define exactly what level of compatibility we want to provide to classic/hybrid themes. I have added the needs design input flag - but feel free to remove if you don't think this is needed.

**Comment by t-hamano** [comment]
I have Rebase this PR with the latest trunk, which will also fix the duplicate Pattarns command.

By the way, here is what I have in mind as a patch to submit to the core:

<details><summary>Details</summary>

```diff
diff --git a/src/wp-admin/menu.php b/src/wp-admin/menu.php
index 17317f9daa..460cd8d787 100644
--- a/src/wp-admin/menu.php
+++ b/src/wp-admin/menu.php
@@ -204,6 +204,8 @@ if ( ! is_multisite() && current_user_can( 'update_themes' ) ) {
 
 if ( wp_is_block_theme() ) {
        $submenu['themes.php'][6] = array( _x( 'Editor', 'site editor menu item' ), 'edit_theme_options', 'site-editor.php' );
+} else {
+       $submenu['themes.php'][6] = array( __( 'Patterns', 'site editor menu item' ), 'edit_theme_options', 'site-editor.php?path=/patterns' );
 }
 
 if ( ! wp_is_block_theme() && current_theme_supports( 'block-template-parts' ) ) {
@@ -219,9 +221,7 @@ $customize_url = add_query_arg( 'return', urlencode( remove_query_arg( wp_remova
 // Hide Customize link on block themes unless a plugin or theme
 // is using 'customize_register' to add a setting.
 if ( ! wp_is_block_theme() || has_action( 'customize_register' ) ) {
-       $position = ( wp_is_block_theme() || current_theme_supports( 'block-template-parts' ) ) ? 7 : 6;
-
-       $submenu['themes.php'][ $position ] = array( __( 'Customize' ), 'customize', esc_url( $customize_url ), '', 'hide-if-no-customize' );
+       $submenu['themes.php'][7] = array( __( 'Customize' ), 'customize', esc_url( $customize_url ), '', 'hide-if-no-customize' );
 }
 }
 
-if ( ! ( current_theme_supports( 'block-template-parts' ) || wp_is_block_theme() ) ) {
-       wp_die( __( 'The theme you are currently using is not compatible with the Site Editor.' ) );
-}
-
-$is_template_part = isset( $_GET['postType'] ) && 'wp_template_part' === sanitize_key( $_GET['postType'] );
+$is_template_part      = isset( $_GET['postType'] ) && 'wp_template_part' === sanitize_key( $_GET['postType'] );
 $is_template_part_path = isset( $_GET['path'] ) && 'wp_template_partall' === sanitize_key( $_GET['path'] );
+$is_patterns           = isset( $_GET['postType'] ) && 'wp_block' === sanitize_key( $_GET['postType'] );
+$is_patterns_path      = isset( $_GET['path'] ) && 'patterns' === sanitize_key( $_GET['path'] );
+
 $is_template_part_editor = $is_template_part || $is_template_part_path;
+$is_patterns_editor      = $is_patterns || $is_patterns_path;
 
-if ( ! wp_is_block_theme() && ! $is_template_part_editor ) {
-       wp_die( __( 'The theme you are currently using is not compatible with the Site Editor.' ) );
+if ( ! wp_is_block_theme() ) {
+       if ( ! current_theme_supports( 'block-template-parts' ) && $is_template_part_editor ) {
+               wp_die( __( 'The theme you are currently using is not compatible with the Site Editor.' ) );
+       }
+       if ( ! $is_template_part_editor && ! $is_patterns_editor ) {
+               wp_die( __( 'The theme you are currently using is not compatible with the Site Editor.' ) );
+       }
 }
```

</details>

**Review by aaronrobertshaw — COMMENTED** [review]
Apologies for the delays on getting back to this one @t-hamano, I've been wrestling with exactly what access classic patterns should have to the site editor's pattern page.

> However, I believe the Patterns page in the Site Editor is designed to be available regardless of the type of theme.

I'm not one of the design team but I'm not sure I agree with this 100%. Which, I believe, is why we were waiting on some design feedback.

After some further discussions, I think there's some middle ground for classic themes that we could achieve for the 6.4 release.

1. Only classic themes that also adopt `block-template-parts` support can access the pattern page.
2. Without template parts support, a classic theme should be directed to the `wp_block` post-type index page and editor (as they do on trunk now in commands etc).

This would help prevent adding additional complexity to the patterns pages and screens. Make the page more consistent for all users that can access it etc.

It seems the primary issue for classic themes is the ability to easily access the post-type index page for patterns. The links via the block toolbar or command palette aren't easily discoverable.

The main proposal floated to address that was adding a link under Appearance > Patterns in wp-admin. Doing that only for classic themes without template part support would probably get my vote.

cc/ @SaxonF @jameskoster @glendaviesnz any thoughts given the limited time until the next beta?

**Comment by t-hamano** [comment]
Thank you for the suggestion @aaronrobertshaw!

> Only classic themes that also adopt block-template-parts support can access the pattern page.

Does this mean that when I press the back button on the "All Template Parts" page, I will be redirected to the Patterns page instead of the dashboard? Or do you mean that in addition to those, the classic theme with opt-in block-template-parts will show 'Patterns' menu item instead of 'Template Parts' in the Appearance menu?

**Comment by aaronrobertshaw** [comment]
Sorry for the confusion, I could have been clearer in my comment.

> Does this mean that when I press the back button on the "All Template Parts" page, I will be redirected to the Patterns page instead of the dashboard?

That's a good question. It might depend on whether the Appearance > Template Parts link continues to go to the All Template Parts index page or to the main Patterns page with a default template part category selected.

If it was the latter, back from the Patterns page would go back to wp-admin for both patterns and template parts (for classic themes with `block-template-parts`). The All Template Parts page's back button would then go back to the patterns page as suggested.

> Or do you mean that in addition to those, the classic theme with opt-in block-template-parts will show 'Patterns' menu item instead of 'Template Parts' in the Appearance menu?

Eventually, Template Parts will be rolled into Patterns, so this will possibly be what it is long term. I'm not sure that will happen now though. Which, is why we might need some further thought on these links.

> It seems the primary issue for classic themes is the ability to easily access the post-type index page for patterns. The links via the block toolbar or command palette aren't easily discoverable.

To bring the discussion back to what I think is the primary issue, classic themes need an easy way to access patterns and edit them. That could be solved by linking to `edit.php?post_type=wp_block` with no further changes to the patterns pages or their navigation.

**Comment by kevin940726** [comment]
I also created https://github.com/WordPress/gutenberg/pull/54342 as an alternative approach so that we can play with both and decide which is better for the users. Good thing is that seems like there's no blocker in terms of code and implementation, so we just need come to a consensus 👍 .

**Comment by t-hamano** [comment]
Thanks for trying a different approach, @kevin940726!

What I would like to see is whether it makes sense to **allow all themes to access the Pattern page**, ultimately including classic themes that have not opted into `block-template-parts`. If there is no difference in understanding on this point, I think it would be better to proceed with #54342, which is a more gradual approach, and set it as a landing point in WP6.4 👍

What do you think?

**Comment by jameskoster** [comment]
> What I would like to see is whether it makes sense to allow all themes to access the Pattern page, ultimately including classic themes that have not opted into block-template-parts

Patterns are still useful to sites with classic themes, no? I think it makes sense to allow access even if they don't support template parts.

**Comment by kevin940726** [comment]
If we want to allow all themes to access `site-editor.php?path=/patterns`, then I think this PR is more suitable than #54342. #54342 is heavily based on this PR anyway! What additional changes we want to add or remove here to make it mergable? I can provide any help here to get us across the finish line!

**Comment by aaronrobertshaw** [comment]
Thanks for weighing in @jameskoster 👍 

> Patterns are still useful to sites with classic themes, no? I think it makes sense to allow access even if they don't support template parts.

The consensus is definitely classic themes should have easier access to patterns. The question is whether that access should be the site editor patterns page or the post type page in wp-admin as you noted in https://github.com/WordPress/gutenberg/issues/52150#issuecomment-1628521974.

1. `site-editor.php?path=/patterns`
2. `edit.php?post_type=wp_block`

The "manage patterns" links in the editor only direct classic themes to the second link above. 

| Block Toolbar | Options Menu |
|---|---|
| Screenshot 2023-09-13 at 11 23 18 am | Screenshot 2023-09-13 at 11 22 36 am |


Adding an Appearance > Patterns link to `edit.php?post_type=wp_block` is how I was leaning as an intermediate step while the patterns management page in the site editor stabilized. 

My understanding is that for all classic themes to be directed to the site editor's pattern management page we need a core patch so that access is permitted to that page when reloading etc. 

Would that prevent this change landing in Gutenberg, which could be used on WP <6.4? If that means we can't then update the manage pattern links, would it not be better to keep classic themes all going to the same patterns page?

If all that isn't a concern, then I don't have a strong opinion on direction, so if you're happy with **all** classic themes going to the patterns management page in the site editor, we should proceed with this PR. It will just need to update all the links missed that point to the `edit.php?post_type=wp_block` location.

**Comment by t-hamano** [comment]
> The question is whether that access should be the site editor patterns page or the post type page in wp-admin as you noted in https://github.com/WordPress/gutenberg/issues/52150#issuecomment-1628521974.

In my opinion, in the future, all themes should have access to the Patterns page in the Site Editor (`site-editor.php?path=/patterns`). With that in mind, the Post Type page (`edit.php?post_type=wp_block`) might only exist as a fallback page.

> My understanding is that for all classic themes to be directed to the site editor's pattern management page we need a core patch so that access is permitted to that page when reloading etc.
> 
> Would that prevent this change landing in Gutenberg, which could be used on WP <6.4? If that means we can't then update the manage pattern links, would it not be better to keep classic themes all going to the same patterns page?

I think you are right. I have come up with the following plan to allow all themes to have access to the Site Editor's Patterns page in the future while maintaining full backward compatibility.

- In all classic themes, change this PR so that the "Manage Patterns" link and command palette action always point to `edit.php?post_type=wp_block`. This is to prevent errors in accessing the Site Editor in WP versions that don't have a patch that allows access to `site-editor.php?path=/patterns` from classic themes. For example, if your site is under WP6.3 and you are using the latest Gutenberg, which includes this PR.
- Submit a following core patch:
  - Add a Patterns link under the Appearance section that points to `site-editor.php?path=/patterns`.
  - Allow all classic themes to access `site-editor.php?path=/patterns`.
  - This patch is part of WP6.4.
- In the future, when the minimum WordPress version supported by Gutenberg is 6.4, all classic themes should have access to `site-editor.php?path=/patterns`, so change the Manage Patterns link and the Command Palette action to always point to `site-editor.php?path=/patterns`.

Assuming this PR is merged and a patch like the one above is applied to WP6.4, the following scenario would be possible:

- **WP <6.3 without latest Gutenberg Plugin**: same as before.
- **WP < 6.3 with the latest Gutenberg plugin**: _almost_ the same as before. However, when you access the template parts page (`site-editor.php?path=/wp_template_part/all`) in a classic theme that supports `block-template-parts` and press the back button, the Patterns page (`site-editor.php?path=/patterns`) is displayed.
- **WP 6.4 with or without the latest Gutenberg Plugin**: All classic themes have a Patterns menu under the Appliance menu that takes you to the Patterns page (`site-editor.php?path=/patterns`) All classic themes can be accessed from the Patterns menu under the Appearance menu. However, the "Manage Patterns" link and command palette always point to `edit.php?post_type=wp_block`.

Sorry if there are any points that are confusing. I would appreciate your honest feedback 🙇

**Comment by aaronrobertshaw** [comment]
> In my opinion, in the future, all themes should have access to the Patterns page in the Site Editor (site-editor.php?path=/patterns

Yes, I agree 100% that, **in the future**, all themes will have access to the patterns management page in the site editor. I don't think that future will be until the minimum supported version is WP 6.4. 

> **WP 6.4 with or without the latest Gutenberg Plugin:** All classic themes have a Patterns menu under the Appliance menu that takes you to the Patterns page (site-editor.php?path=/patterns) All classic themes can be accessed from the Patterns menu under the Appearance menu. However, the "Manage Patterns" link and command palette always point to edit.php?post_type=wp_block.

I believe the inconsistency here is a problem. Users should be taken to the same location via the Appearance > Patterns link or the "manage patterns" link. 

As noted previously, my vote is that the Appearance > Patterns link for classic themes in 6.4 goes to `edit.php?post_type=wp_block` which is consistent with the manage patterns links. It also still covers the primary issue which is providing access to some level of pattern management for classic themes. 

I do appreciate the desire to access the new site editor page, it is the goal long term, no arguments here. To maintain a consistent experience in a backwards-compatible manner, I think we need to take this interim step.

**Comment by t-hamano** [comment]
> I believe the inconsistency here is a problem. Users should be taken to the same location via the Appearance > Patterns link or the "manage patterns" link.
> 
> As noted previously, my vote is that the Appearance > Patterns link for classic themes in 6.4 goes to edit.php?post_type=wp_block which is consistent with the manage patterns links. It also still covers the primary issue which is providing access to some level of pattern management for classic themes.

I see, so it seems better to proceed with #54342, which has consistent Pattern links and is a more step-by-step approach?

However, I have concerns regarding the following specification:

> For classic themes with `block-template-parts` support: "Manage patterns" points to `site-editor.php?path=/patterns`. Add a `Patterns` link under the Appearance section that points to `site-editor.php?path=/patterns` as well.

I think this would work well for WordPress with the core patch applied as suggested in #54342.

For example, suppose you have a WordPress 6.3 site with the Classic theme with `block-template-parts` support enabled, and the Gutenberg plugin with #54342 included is enabled.

- Since the core patch has not been applied, the Template Parts link will still appear in the Appearance section. Users will access the Template Parts link. When the back button is pressed, the user is taken to the Patterns page. In other words, to access the Patterns page, the user must go through the Template Parts link. Also, reloading the browser on the Patterns page will result in an access error.
- The Manage Patterns link or the Patterns link in the command palette points to `site-editor.php?path=/patterns`. If the core patch is not applied, the Patterns page cannot be accessed and an error will occur when accessing the link.

I would like to consider whether this backward compatibility issue is acceptable.

**Comment by aaronrobertshaw** [comment]
@t-hamano thanks for your patience in working through this one 👍 

The backwards compatibility issue is a concern, 100%.

When I initially floated allowing classic themes with `block-template-parts` support access to the site editor's pattern page, I hadn't yet thought of this BC issue.

All commands from the command palette, the "manage patterns" links, and the Appearance > Patterns link should go to `edit.php?post_type=wp_block` for classic themes until WP 6.4 is the minimum supported version.

**Comment by t-hamano** [comment]
> All commands from the command palette, the "manage patterns" links, and the Appearance > Patterns link should go to edit.php?post_type=wp_block for classic themes until WP 6.4 is the minimum supported version.

That's right, I'm sorry I couldn't convey my intentions well 😅

Based on this, my new plan is as follows.

- Close this PR and [#54342](https://github.com/WordPress/gutenberg/pull/54342): Because in the trunk, all classic themes are already handled to always point to `edit.php?post_type=wp_block`. If classic themes have a route or action that allows access to `site-editor.php?path=/patterns`, we need to fix it.
- Submit a core patch like below:
  - For classic themes: Add a Patterns link under the Appearance section that points to `edit.php?post_type=wp_block`.
  - For classic themes with `block-template-parts` support: Add a Patterns link under the Appearance section that points to `edit.php?post_type=wp_block`. Existing Template Parts link will _remain_ as before.
  - Apply the changes described in [this comment](https://github.com/WordPress/gutenberg/pull/54066#issuecomment-1706058876) to allow access to the Site Editor from the classic theme. However, this does not need to be _officially_ announced, as this is the preparation that the classic theme will be able to access `site-editor.php?path=/patterns` on a consistent basis in the future.
- When the minimum WordPress version supported by the Gutenberg plugin was raised to 6.4:
  - Change all pattern links to point to `site-editor.php?path=/patterns` in all classic themes. This is because WordPress 6.4 has already allowed access to `site-editor.php?path=/patterns` from the classic theme.
  - Submit a core patch like below:
    - Change the Patterns link in the Appearance section from `edit.php?post_type=wp_block` to `site-editor.php?path=/patterns`.
    -  For classic themes that support `block-template-parts`, _remove_ the Template Parts link in the Appearance section.

It will probably be around WP6.5 or WP6.6 that classic themes will be able to consistently use the site editor pattern page, but I think backwards compatibility will be maintained.

---

Alternatively, I think the following approach may be possible:

- On the Gutenberg side, check if the Patterns link (`site-editor.php?path=/patterns`) has been added in the Apperance section and add it as an endpoint. In other words, it checks to see if a patch has been applied to the core that allows the classic theme to access `site-editor.php?path=/patterns`.
- If the Patterns menu has been added, point all pattern links to `site-editor.php?path=/patterns`. For example, as below:
    ```javascript
	const isBlockBasedTheme = useIsBlockBasedTheme();
	const { hasPatternsMenu } = useSelect(
		( select ) =>
			select( coreStore ).getCurrentTheme()?.has_patterns_menu,
		[]
	);
	const patternsUrl =
		isBlockBasedTheme || hasPatternsMenu
			? addQueryArgs( 'site-editor.php', {
					path: '/patterns',
			  } )
			: 'edit.php?post_type=wp_block';
    ```

**Comment by kevin940726** [comment]
Correct me if I'm wrong, so here's basically the plan now:

In Core WP 6.4:
1. Add an `Appearance -> Patterns` link for all classic themes that point to `edit.php?post_type=wp_block`.
2. Allow `site-editor.php?path=/patterns` access for classic themes.

In gutenberg after the minimum required version is WP 6.4:

3. Change all "Manage patterns" links to point to `site-editor.php?path=/patterns`.
4. Change the `Appearance -> Patterns` links for classic themes to point to `site-editor.php?path=/patterns`.

---

(Oops, @t-hamano beat me to it 😂)

**Comment by aaronrobertshaw** [comment]
> Based on this, my new plan is as follows.

The new plan makes sense to me 👍

**Comment by t-hamano** [comment]
Thanks for all your advice🙇 Then I would like to submit the core patch as soon as possible.

Or should we update [this patch](https://github.com/WordPress/wordpress-develop/compare/trunk...kevin940726:wordpress-develop:fix/allow-patterns-access-for-block-template-parts) submitted by @kevin940726?

**Comment by kevin940726** [comment]
> Or should we update [this patch](https://github.com/WordPress/wordpress-develop/compare/trunk...kevin940726:wordpress-develop:fix/allow-patterns-access-for-block-template-parts) submitted by @kevin940726?

I haven't submitted the patch, it's just a branch on my fork 😅 . But we can certainly use that if you prefer. Given that it's only a few lines, and you've done most of the work, I think you can submit the patch so that you'll get the credit you deserve. 💯

**Comment by aaronrobertshaw** [comment]
> Then I would like to submit the core patch as soon as possible. Or should we update [this patch](https://github.com/WordPress/wordpress-develop/compare/trunk...kevin940726:wordpress-develop:fix/allow-patterns-access-for-block-template-parts) submitted by @kevin940726?

Whatever is easiest for you! 

I like @kevin940726's suggestion that you take the deserved credit. Whether it ended up as a small change or not, it took patience, perseverance, and care to arrive at the best result. That's worth celebrating in my book 🎉 

Kudos also to Kai for helping us work through possibilities 👍

**Comment by t-hamano** [comment]
I discovered the unintended behavior while writing a core patch to allow access to the Pattern page from the classic theme. Therefore, I have submitted #54422 which fixes this one.

**Comment by t-hamano** [comment]
Core patch submitted: https://github.com/WordPress/wordpress-develop/pull/5201

**Review by aaronrobertshaw — COMMENTED** [review]
I believe the consensus ended up that all the links to patterns page should remain consistent. 

From that, my understanding is that the command palette changes here need to be reverted so that classic themes will still be directed to the `edit.php?post_type=wp_block` page matching the "manage patterns" links in the editor along with the new Appearance > Patterns link introduced in https://github.com/WordPress/wordpress-develop/pull/5201

**Comment by t-hamano** [comment]
This PR was originally intended for the classic theme to have consistent access to the Patterns page in the Site editor (`site-editor.php?path=/patterns`). However, after some discussion, we came to the conclusion that the post type index page (`edit.php?post_type=wp_block`) should be accessed consistently as before.

As a result, I think this PR should be closed, as I suggested in [this comment](https://github.com/WordPress/gutenberg/pull/54066#issuecomment-1717123517). Instead, I'm filing #54422 to address the issue that can occur if users access the pattern page directly. Is my understanding correct?

**Comment by aaronrobertshaw** [comment]
> As a result, I think this PR should be closed, as I suggested in https://github.com/WordPress/gutenberg/pull/54066#issuecomment-1717123517. Instead, I'm filing https://github.com/WordPress/gutenberg/pull/54422 to address the issue that can occur if users access the pattern page directly. Is my understanding correct?

No issues here with closing this PR 👍 

I was confused given this PR was linked from your core patch in this [comment](https://github.com/WordPress/wordpress-develop/pull/5201#issuecomment-1726991594) which said you wanted to ship it.

**Comment by t-hamano** [comment]
> I was confused given this PR was linked from your core patch in this [comment](https://github.com/WordPress/wordpress-develop/pull/5201#issuecomment-1726991594) which said you wanted to ship it.

Admittedly, the Gutenberg link I put in the core patch wasn't the right one 🙈 I would like to close this PR and update the core patch information.

**Comment by aaronrobertshaw** [comment]
> Admittedly, the Gutenberg link I put in the core patch wasn't the right one

All good. I'm easily confused though 😂

**Comment by tinjure20** [comment]
I have been trying out [this new 6.4 feature](https://github.com/WordPress/gutenberg/issues/52150#issuecomment-1717627370) to learn more about exposing patterns in classic themes. I am basically following to the [instructions outlined in this PR](https://github.com/WordPress/wordpress-develop/pull/5201#issue-1894481375) and using these testing environment:

- WordPress: 6.4-beta1-56750
- PHP: 8.0.22
- MacOS Ventura 13.5.2
- Theme: TT1 v1.9
- Plugin: Gutenberg 16.7 active

I could replicate the instructions for the TT3 theme [described here](https://github.com/WordPress/wordpress-develop/pull/5201#issue-1894481375).

For the TT1, I was only able to **expose template parts**, but not the **patterns** described in the instructions. I get the following message: 

Screenshot 2023-09-30 at 5 08 21 AM

What am I doing wrong here?

**Comment by t-hamano** [comment]
Hi @tinjure20,

You are not performing an incorrect test procedure. The [#5201](https://github.com/WordPress/wordpress-develop/pull/5201) has not yet been committed into the WP core, so even if you update to WordPress Beta, you still cannot access it from the Classic Editor except for the Template Parts Editor in the Site Editor.

**Comment by tinjure20** [comment]
Hello @t-hamano,

Thank you very much for your prompt response. Just a quick questions: when this feature would be available? by RC1?. Thank you.

**Comment by t-hamano** [comment]
Hi @tinjure20,

I don't yet know in which phase it will be included, but we are doing our best to ship this in 6.4.

**Comment by aaronrobertshaw** [comment]
Unfortunately, this has been moved to WP 6.5. More info can be found on the related [issue](https://github.com/WordPress/gutenberg/issues/52150#issuecomment-1743235386) and [core patch](https://core.trac.wordpress.org/ticket/58827#comment:9)

**Pull request closed without merging**
