### PR TITLE
E2E: Block Hierarchy Navigation wait for the column to be highlighted

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
The "Block Hierarchy Navigation" e2e test [fails](https://github.com/WordPress/gutenberg/runs/3162134316) from time to time. Unfortunately, I'm unable to reproduce this locally.

Based on the screenshot from the artifacts, it looks like block selection happens before navigation reaches the third and last column block.

I'm adding an extra check to verify that the third block is highlighted before selecting it. This should also give keyboard navigation a little spare time to finish.

## How has this been tested?
Locally using the following command:

```
npm run test-e2e -- packages/e2e-tests/specs/editor/various/block-hierarchy-navigation.test.js
```

## Screenshots 
should navigate block hierarchy using only the keyboard

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
@Mamaduka I'm going to try to rerun the e2e tests here 3/4 times to see how it goes.

**Comment by Mamaduka** [comment]
> I'm going to try to rerun the e2e tests here 3/4 times to see how it goes.

I can do that as well. It's not a problem. I will leave a comment about the results.

**Comment by youknowriad** [comment]
First and second run successful, third in progress.

**Comment by Mamaduka** [comment]
@youknowriad current failure isn't related to this test - https://github.com/WordPress/gutenberg/pull/33721/checks?check_run_id=3180467512

**Review by youknowriad — APPROVED** [review]
Let's merge when the current run passes.

**Pull request merged**
