### PR TITLE
Better CSS reset style loader order

### LINKED ISSUE #21785: Default editor styles load after core blocks' editor styles, rather than before.
## Description
The styles in [packages/editor/src/editor-styles.scss](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/editor-styles.scss) are loaded after [packages/block-library/src/editor.scss](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/editor.scss). I would expect them to be loaded before.

Because of the editor style wrapping that currently happens, style rules like `ul` become `.editor-styles-wrapper ul`, which has a specificity of 0-1-1, and so even a style rule in a core block's `editor.scss` like `ul.has-background` (which has the same specificity) will be overridden, because the default editor styles are applied after.

I discovered this issue while working on #21387, where I ran into the exact scenario described in the previous paragraph.

## Expected behavior
The editor styles provided by the core blocks would be applied after the default editor styles, not before.

## Environment
- WordPress 5.4.2
- Gutenberg plugin 8.5.1

### PR DESCRIPTION
**Pull request by youknowriad**
Related #29976 
closes #21785 

This PR remove the "editor-styles.css" file which was being used as "Admin Reset" and move it to a dedicated style that is enqueued explicitly instead of considering this style as a regular "theme editor style".

To clarify here, let's take a look at a paragraph style: We know that WP Admin defines a default size for the paragraph like this:

```css
# wp-admin.css
p { font-size: 14px }
```

To fix that issue, we wrap the editor in a `editor-styles-wrapper` classname and we use this class to reset wp-admin styles. So we do this:

```
# reset (inline)
.editor-styles-wrapper p {
  font-size: reset;
}
```

Some blocks do define precise sizes for some paragraphs for instance:

```
# block-library-style.css
.wp-block-latest-comments p {
  font-size: 0.8em;
}
```

Sometimes themes override default block styles for instance by doing:

```
# theme-editor-style (inline)
.editor-styles-wrapper .wp-block-latest-comments p {
  font-size: 0.6em;
}
```

In trunk, there's no difference between the "reset style" and the "theme editor style" , both these two stylesheets are considered "editor styles" and loaded as an injected style tag (so latest order), so the styles are being loaded in the following order:

 - wp-admin.css
 - block-library-style.css
 - reset (inline)
 - theme-editor-style (inline)

(in the example above, it means the reset of the paragraph size will override the style of the comment block)

It is clear here that the "reset" style could inadvertently  override some legit block styles from `block-library-style.css`. So what I'm doing in this PR is that I'm changing the way this "reset" get enqueued, instead of considering it an editor style, it's just a regular stylesheet file that get inserted in the editor before the blocks stylesheet, so we get the following order:

 - wp-admin.css
 - reset.css
 - block-library-style.css
 - theme-editor-styles (inline)

**Notes**

This PR doesn't solve everything :), there are two remaining things:

 - You'll notice that if you load a saved post (not a new post) in the editor, the stylesheets of the blocks used in the content of that post end up being loaded first before all the other stylesheets potentially breaking some styles. This is a Core issue related to these lines:  https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/class-wp-block.php#L227-L234 which I believe should be removed entirely (need its own ticket/PR)
 - In the example above if theme decided to define a default size for the paragraph block by doing 
 
```
.editor-styles-wrapper  p {
  font-size: 10px;
}
```

it would have overriden the latest comments block styles because the specificity is equal and the theme overrides are always loaded last. I believe there's no easy fix for this (aside the iframe). In these cases, the theme-author needs to provide an override for the comments block as well. (of course using theme.json config solve this too instead of providing a CSS file).

### CODE REVIEW

**Comment by skorasaurus** [comment]
possibly related or solves: https://github.com/WordPress/gutenberg/issues/21785

**Comment by jasmussen** [comment]
Amazing PR. This test well for me, and I'm excited to land it and the followup you mention.

Are there any specific test instructions you'd like me to follow? Just in general testing, I see no before/after difference.

**Comment by youknowriad** [comment]
@jasmussen well, it's too broad to have some specific instructions but I'd say just test several themes editor styles and check that think work at least as good as "trunk"

For the follow-up, I'd need some help from @gziolo and @aristath

**Comment by aristath** [comment]
This looks good!

> You'll notice that if you load a saved post (not a new post) in the editor, the stylesheets of the blocks used in the content of that post end up being loaded first before all the other stylesheets potentially breaking some styles.

What if on the editor, we add the reset as a dependency on all stylesheets enqueued?
Wouldn't that ensure that it gets loaded first? 🤔

**Comment by youknowriad** [comment]
> What if on the editor, we add the reset as a dependency on all stylesheets enqueued?
> Wouldn't that ensure that it gets loaded first? 🤔

it would solve the issue but it means we register the style differently between frontend and backend which is a bit weird. I think the enqueuing is rendered is something that might be problematic in the long run but I wouldn't mind that approach though

**Review by aristath — APPROVED** [review]
The failing tests should be addressed before merging, but the logic in this PR makes perfect sense and will improve things in the long run. We can start with this one and continue improving it in subsequent PRs. 👍

**Comment by talldan** [comment]
Just testing this in the navigation and widgets editors, this seems to cause some styling issues.

## trunk
Screenshot 2021-03-22 at 5 48 43 pm

## this branch
Screenshot 2021-03-22 at 5 51 43 pm

**Comment by jasmussen** [comment]
The effect this has on the navigation screen seems okay insofar as it does render browser defaults. Perhaps the followup is to add the system font definition to just that screen? Happy to do so in a followup.

**Comment by youknowriad** [comment]
So are we ok with this impact? I'm not sure I know the navigation screen enough to be able to say how best to address this. I guess before this PR, the navigation screen didn't use the "reset" at all and was just inhering wp-admin defaults which doesn't seem like a great thing either?

**Comment by jasmussen** [comment]
I'm happy to reintroduce systemfonts to the navigation screen. That is what we're using now, and there is CSS just for the screen anyway.

**Comment by youknowriad** [comment]
Ok Let's do this then.

**Comment by talldan** [comment]
The main impact seems to be the block toolbar positioning and the font, so I'm sure we can fix those things.

cc @noisysocks @kevin940726 as this also affects the widget editor for non legacy widget blocks.

**Comment by youknowriad** [comment]
I'll try to push a PR for the widgets screen.

**Comment by jasmussen** [comment]
Followup in https://github.com/WordPress/gutenberg/pull/30085.

**Comment by gziolo** [comment]
> well, it's too broad to have some specific instructions but I'd say just test several themes editor styles and check that think work at least as good as "trunk"
> 
> For the follow-up, I'd need some help from @gziolo and @aristath

This is the related ticket in WordPress core:
https://core.trac.wordpress.org/ticket/50328

We should prioritize it for WordPress 5.8 cycle. It looks like explored several things in https://core.trac.wordpress.org/attachment/ticket/50328/50328-skip-assets.diff, but eventually switched to other tasks.

**Pull request merged**
