### PR TITLE
Update the backup icon to better align with WordPress icon package dna

### PR DESCRIPTION
**Pull request by jameskoster**
I believe the current backup icon – used in the "Revisions" link – is based on an old Dashicon. This PR updates it to match the other icons in the WordPress Icons package, namely:

* The stroke on the arrow is now 1.5px
* Arrow head matches the "rotate" icons that already exist

Before:

Screenshot 2020-12-03 at 11 14 22

After:

Screenshot 2020-12-03 at 11 32 17

Rotate icon for reference:

Screenshot 2020-12-03 at 11 35 20

Additional considerations:

The new icon is a 1:1 match with the rotate icon, just rotated slightly to make room for the "hands" of the "clock". If we break that 1:1 relationship ever so slightly we get a sharper icon.

So there's a question to be asked around sharpness vs consistency. Thoughts?

Screenshot 2020-12-03 at 12 29 16

## To test:

* Open a post and check the revisions link in the sidebar. It should look like that "After" screenshot above.

### CODE REVIEW

**Comment by shaunandrews** [comment]
I like that the circle's line-width now matches better with the other icons. But, the clock hands being triangular really bug me; Why not just use lines?

**Comment by jameskoster** [comment]
Here's a couple of other options that use lines for the hands. The first one uses an _identical_ arrow to the `rotate` icon and a different hand position. I quite like that one :) 

Screenshot 2020-12-04 at 18 56 27

Figma link [here](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=5415%3A22292) in case anyone would like to play with these.

**Comment by mapk** [comment]
@jameskoster I'm really digging that first one in the last set. The arrow feels more defined and the hands look good, although seem to reflect a checkmark. 🤔 

Screen Shot 2020-12-04 at 1 05 56 PM

**Comment by jasmussen** [comment]
I'd agree with Shaun, the triangular arrows don't really share DNA with the new icon set. However we have htis icon for rotate, that you could take inspiration from:

Screenshot 2020-12-07 at 09 23 03

Here's the time machine icon:

Screenshot 2020-12-07 at 09 24 27

The ingredients in use there seem to get the balance right.

**Comment by jameskoster** [comment]
> However we have htis icon for rotate, that you could take inspiration from

That is precisely what the icon is based on, it's the same arrow just tidied up a bit 😆

Here's a version that is – ahem – _loosely_ inspired by the Time Machine icon:

Screenshot 2020-12-07 at 10 42 10

**Comment by jasmussen** [comment]
I think that one works. 👍 👍

**Review by jasmussen — APPROVED** [review]
Big improvement, and the metrics look good:

Screenshot 2020-12-08 at 11 51 44

Let's get this in.

**Pull request merged**
