### PR TITLE
Docs: Remove Block Grammar doc and all corresponding internal links.

### LINKED ISSUE #51067: Consider removing "Block Grammar" documentation page
## What problem does this address?
The [Block Grammar](https://developer.wordpress.org/block-editor/contributors/code/grammar/) doc in the Block Editor Handbook contains code examples without any context. It's unclear what the doc is trying to convey, and it also has not been meaningfully updated since it was written in 2018. 

## What is your proposed solution?
In the interest of reducing the maintenance burden of the Block Editor Handbook and ensuring all pages are up-to-date and accurate, **I recommend we remove this page**. 

However, if folks feel it is valuable, the page will need to be updated with a proper description and explanations for each code example. I am happy to create this PR, given the necessary direction. 

As the original author @mcsf, I would love your insight here. Thanks! 🙏

### PR DESCRIPTION
**Pull request by ndiego**
Fixes https://github.com/WordPress/gutenberg/issues/51067

## What?
This PR removes the [Block Grammar](https://developer.wordpress.org/block-editor/contributors/code/grammar/) documentation page and all internal links to this page. 

## Why?
As noted in https://github.com/WordPress/gutenberg/issues/51067, the Block Grammar page is no longer needed in the Block Editor Handbook.

### CODE REVIEW

**Comment by ndiego** [comment]
@mcsf I am guessing I also need to remove the [generate-public-grammar.js](https://github.com/WordPress/gutenberg/blob/trunk/bin/generate-public-grammar.js) file, but I am not exactly sure how that file works. Is there anything else that needs to be updated related to the generator file?

**Comment by mcsf** [comment]
> @mcsf I am guessing I also need to remove the [generate-public-grammar.js](https://github.com/WordPress/gutenberg/blob/trunk/bin/generate-public-grammar.js) file, but I am not exactly sure how that file works. Is there anything else that needs to be updated related to the generator file?

@ndiego: nope, you can safely delete it. It was there to be called manually whenever (= never) the grammar would change.

**Review by mcsf — APPROVED** [review]
Assuming the generator script is also removed, LGTM! Thanks for the cleanup

**Comment by ndiego** [comment]
Perfect, thanks! I will tackle this today

**Pull request merged**
