### PR TITLE
Experiment: Load the template when editing a page

### LINKED ISSUE #29821: When editing the page_for_posts page the canvas should match the front end
Setting a static home page unlocks an affordance to specify a separate page to display the post archive:

Screenshot 2021-03-12 at 13 20 07

When presented in the editor the content of this page does not reflect what you see on the frontend. Indeed any changes you make are essentially ignored until you unset this page as the `page_for_posts`.

Here's an example of a perfectly reasonable user flow which behaves in a very unexpected way:

https://user-images.githubusercontent.com/846565/110946015-4ee47600-8336-11eb-9e59-6a189e689a7a.mp4

I appreciate this isn't really a bug – WordPress has always handled this the same way. But with all the blocks we've built for the Site Editor there's potential for us to do better in this specific instance. To kick off discussion, one idea would be for this page to display a single Query block, which cannot be removed. Perhaps some of the attributes are locked as well. Pattern transforms (https://github.com/WordPress/gutenberg/issues/28736) could be possible.

It's worth acknowledging that this issue is not restricted to the page for posts. There are other templates in the site editor that should 'lock down' specific blocks. I think that is a slightly different issue though, and worth discussing elsewhere (https://github.com/WordPress/gutenberg/issues/27848#issuecomment-797494456).

Edit: This is somewhat related to https://github.com/WordPress/gutenberg/issues/28341

### PR DESCRIPTION
**Pull request by creativecoder**
## Description

An experiment for editing the full page template and content when loading a page in the editor.

My main intention with this PR is to explore how we can resolve #29821, so that special pages like the "Posts page" are represented more accurately in the editor. As a side effect, this allows editing the full template of any page.

This PR has some hacks that would need to be resolved before a change of this sort could be merged.

## How has this been tested?

- Set a Posts page in Settings > Reading if you don't already have one set
- Note that you'll need content to exist in that page already, otherwise you can't load the block editor (see https://core.trac.wordpress.org/ticket/45537)
- Try editing the Post page, or any other page

## Screenshots 

**Editing the Posts page**

https://user-images.githubusercontent.com/1699996/119416107-8bc6d480-bcb8-11eb-842f-1d6286adeabc.mov

**Loading a "normal" page in the editor**

https://user-images.githubusercontent.com/1699996/119416223-d0eb0680-bcb8-11eb-954e-4d302f103d08.mov

## Types of changes

Experimental

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jameskoster** [comment]
This is very cool to see, thanks for putting it together! Seeing the template will be helpful in many contexts, and crucial in situations like editing the Posts page. 

I do think it's important that the template is only visible and not _directly_ editable though. Otherwise we're blurring the lines between the post editor and the template editor too much. It's vital that folks understand which they are editing so that they are able to interpret whether their changes will have knock-on effects or not. 

The inverse is true as well – when editing a template any visible content should not be directly editable. If you have a moment, please check out https://github.com/WordPress/gutenberg/pull/31461 where I (crudely) explored a solution to this inverse. It may be necessary to get that interaction right as a prerequisite?

Another thing we'll probably need is a toggling affordance. IE it should be possible to edit the post with or without the template visible. See https://github.com/WordPress/gutenberg/issues/27847.

I acknowledge this goes way beyond this PR, but is still relevant – do we need to consider how block insertion works for the Posts page? Since that page technically doesn't have any "content" and only renders a template, I don't know if it should be possible to insert blocks while editing that page?

**Comment by Addison-Stavlo** [comment]
> do we need to consider how block insertion works for the Posts page? Since that page technically doesn't have any "content" and only renders a template, I don't know if it should be possible to insert blocks while editing that page?

The Posts page isnt an actual page post that can be opened in the page editor though, right?  Just a template that will include posts through a query?  In that case it would really only be available to edit in template editing, and block insertion should work as normal as we can and should be able to add blocks to a template itself.

**Comment by jameskoster** [comment]
On the technical side yes that is true. It's what makes this problem so tricky! 

1. The Posts page is presented to the user as a _page_, and so loaded with all the expectations that go along with page editing.
2. The user needs access to _some_ page editing functionality in order to change things like the title, the publish status, the permalink, or to create a new template.
3. When editing the template (in most cases this will be `index`) the user needs to understand that their changes can affect more than just the Posts page.

Considering that users edit this page via the "Pages" menu, coupled with point 3 from above, it seems important to open it in the Post Editor initially. This provides access to the editing capabilities outlined above. But it also surfaces the question from before.... since the "Posts page" isn't technically a page, how do we communicate that users aren't able to add blocks to it in the same way they do with other pages?

Iirc, when you edit the Posts page in the classic editor the content input is hidden and replaced with a notice. We could potentially do something similar here. That might serve as a stop-gap until we can implement a richer experience like the one in this PR.

**Comment by Addison-Stavlo** [comment]
Yeah, definitely tricky. 

> The Posts page is presented to the user as a page
> Considering that users edit this page via the "Pages" menu

Is it currently?  Or is that what we are proposing?

I think adding the 'posts page' under pages as if it were a regular page post type starts to blur the lines and confuse things a bit. Perhaps what might make sense instead is a link to something like "edit homepage template" from there in that case.

Generally the posts list has nothing but "post" post types, and the page list "page" post types.  If we are going to add something to one of those lists that doesn't really correspond to those post types, we should have some form of an asterisk to convey that.  Otherwise we conflate concepts of pages and templates, and blur expectations of users.  We run into user confusions such as "why did this page change completely on theme switch, while all my other pages in this list stayed  as they were?".

Having a link to edit that template from there could make sense, but branding it as a page entirely seems problematic.

**Pull request closed without merging**
