### PR TITLE
Update Heading Block description

### PR DESCRIPTION
**Pull request by 0aveRyan**
The current description for Heading blocks confusingly states that Headings are placed above the post or page contents, when they're used to describe document sections.

* Headings divide the page contents, aren't placed above.
* Headings may be used in CPTs -- direct reference to Post or Page should be removed.
* Headings vs. Subheadings -- one is used for SEO weighting, one is simply formatted paragraph text... we don't want to get overly technical, but this distinct difference should be gently explained.

### CODE REVIEW

**Comment by michelleweber** [comment]
Could you share screenshots of the things you think should be changed? And do you have proposed language (it's fine if you don't)? Thanks!

**Comment by 0aveRyan** [comment]
@michelleweber 
This is the description that prompted this PR:
old-heading

These headings are used inside the page content to divide it, not above it.

This description is also not super clear:
old-subheading

Updated Heading description:
new-heading

Updated Subheading description:
new-subheading

**Comment by michelleweber** [comment]
Perfect, thanks. I'll offer tweaks that you can take or leave; your suggested changes are clear, but I'd love to bring the tone more in line with the other descriptions.

Heading: Help visitors (and search engines!) understand what they're reading with a short description.

I still like the subhead description, but if you want something more pointed:

Subheading: Add a subtitle above a section of your content to introduce your next topic and help readers follow the flow.

(Personally, I'm not sure the user needs to know at this point that the heading is used for SEO, I think they just need to know what happens when they insert this block. So my instinct would be either to save the space and remove that, or include it as a parenthetical to make it clear that it's supplemental info.)

**Comment by chrisvanpatten** [comment]
One note about the subheading block is that it can only be used once (see #8140).

**Comment by 0aveRyan** [comment]
@chrisvanpatten yeah.. that's really not apparent, I think #8140 needs reopened. As indicated in that PR and in the audit in #8234 (which suggests killing it), it's super confusing when to use it. 

Also, it seems strange that a Subheading is simply a `<p>` tag with a targetable classname. If it stays, there should be a way to set this to a true semantic heading tag, but that makes it all the more confusing.

I appreciate the value, I've built plenty of news sites with those subheading decks, but without a way to really explain itself easily and the nuance between it and say an `<h3>` it seems likely it would often be used incorrectly as the review indicated.

**Comment by chrisvanpatten** [comment]
> Also, it seems strange that a Subheading is simply a <p> tag with a targetable classname. If it stays, there should be a way to set this to a true semantic heading tag, but that makes it all the more confusing.

It's not semantically a heading though :)

But yes I agree about reopening #8140 and totally appreciate the confusing name.

**Comment by 0aveRyan** [comment]
For this PR, I've reverted changes to the Subheading block to make the correction to the Heading block only.

**Comment by ZebulanStanphill** [comment]
><samp>Briefly describes the following section to visitors and search engines.</samp>

><samp>Help visitors (and search engines!) understand what they're reading with a short description.</samp>

I do not either of these descriptions work. It sounds like some kind of meta description. A heading is definitely _not_ a short description of the content that follows. It is the title of a section of a document... or in other words, the heading of a section of a document.

How about something like this:

<samp>Use a heading to add a title to a section of content.</samp>

Or alternatively:

<samp>Add a title to a section of content with a heading.</samp>

Or how about this:

<samp>Use headings to divide your content into named sections.</samp>

**Comment by michelleweber** [comment]
Heading: Help visitors (and search engines!) understand what they're reading. Add headlines to introduce your topics and help readers follow the flow.

And for subhead, the original subhead text plus "Use it under a heading to add context." for more clarity.

**Comment by 0aveRyan** [comment]
@michelleweber thank you for your patience :relieved: I think these are getting nicely refined. 

If I may be a bit picky, Headings could be used to title Video/Embed blocks, Audio/Playlist blocks, etc, so I'm not sure about `reading` and `readers`. How do you feel about `Introduce topics and help visitors (and search engines!) understand how your content is organized.`?

I hesitate to update the Subheading in this PR if #8140 is being reopened as @chrisvanpatten indicated, so that can be a separate PR. As-coded, the block can only be inserted once, intending to be used as the first block in `the_content`, however can be inserted elsewhere and there's a plugin to allow infinite copies of it... I think as-named it's a bit confusing and the independent block audit suggested removing it. If it does stay, I think it's single-use limitation would need to be conveyed in the description.

**Comment by michelleweber** [comment]
@0aveRyan, that sounds just fine to me!

**Review by karmatosed — APPROVED** [review]
Thanks for this everyone, looks great and I agree let's focus on heading as depending on the issue, subheading may not be around long.

**Pull request merged**
