### PR TITLE
Layout: Reduce specificity of flex and grid margin overrides

### PR DESCRIPTION
**Pull request by andrewserong**
⚠️ 🚧 🚧 🚧 🚧 This currently does not play nicely with Classic themes 🚧 🚧 🚧 🚧

In Classic themes, the `classic.css` file includes `margin-left: auto` and `margin-right: auto` rules. Reducing the specificity of the margin overrides for flex rules causes an issue in the block editor for the social icons block — the individual social icons blocks with this PR applied have margin rules applied that override the now reduced rule. Here's a screenshot of how it currently looks:

image

---

## What?

Reduce the specificity of the `flex` and `grid` layout type margin overrides, for consistency with the `flow` and `constrained` layout types.

This resolves an issue where flex and grid layout types have margin override specificity that interferes with setting margins at the block level in global styles.

## Why?

As reported in https://github.com/WordPress/gutenberg/pull/45196#pullrequestreview-1435758566 the flow and constrained layouts currently allow block-level-in-global-styles rules to override general layout styles. However, `flex` and `grid` don't have that lower level of specificity for their `margin: 0` rules. From a little digging, it appears that the solution back in https://github.com/WordPress/gutenberg/pull/47858 was to reduce specificity for the `spacingStyles` rules for each layout type. However, the `flex` and `grid` layouts had their overrides in `baseStyles`, which doesn't include the extra `:where()` rule to lower the specificity. The fix is to move the margin overrides for these two layout types over to `spacingStyles`.

## How?

* Move the `margin: 0` override rules for `flex` and `grid` layout types over to `spacingStyles` so that they receive the lower specificity rules introduced in #47858.

The difference in output of rules is:

```
body .is-layout-flex > * {
```

Becomes:

```
:where(body .is-layout-flex) > * {
```

## Testing Instructions

1. In the site editor, set the Cover block to have margin at the block level in global styles, e.g. set it to `50px`
2. Add a Stack block somewhere in your template.
3. Add a Cover block within the Stack block.
4. Note that the margins should appear to take effect in the site editor.
5. Save the template and global styles and view the site front end.
6. The margins should be consistent on the site front end.
7. Back in the site editor, add blocks before and after the Cover block, still within the Stack block. The margins should still take effect.
8. Save and double check on the site frontend.
9. Try the above, but activate the Grid experiment in Gutenberg and add the Cover block as a child of the Grid block. As with the Stack block, the margin rules should apply as expected in the editor and on the site frontend.
10. Double-check that default / fallback gap styles are still working as expected on Classic themes (e.g. test Columns and Social Icons blocks)

A question / note to the reviewer: the `flex` and `grid` rules, in contrast to flow/constrained, do not do anything about resetting margins for first/last items. I think that's likely preferable due to how these layout types work, but I'm curious what folks think. Is the change in this PR the desired approach for these layout types?

## Screenshots or screencast 

Prior to this PR, the margins would only look correct in the site editor, but not on the site frontend. So for these before/after screenshots, we're looking at the site front end:

| Before | After |
| --- | --- |
| image | image |
| image | image |

### CODE REVIEW

**Comment by andrewserong** [comment]
This appears to mostly be working, except for a conflict with `classic.css` which includes `margin-left: auto` and `margin-right: auto` rules. Perhaps those rules should also be reduced so that they don't conflict with other margin rules 🤔

**Comment by aaronrobertshaw** [comment]
Thanks for spinning up this PR so quickly @andrewserong 🚀 

I can confirm it does fix the original issue flagged via https://github.com/WordPress/gutenberg/pull/45196#pullrequestreview-1435758566. 

> Perhaps those rules should also be reduced so that they don't conflict with other margin rules 

The catch with the `margin: auto` styles for classic themes might be a bit tricky to solve. I haven't gotten to get my hands too dirty with this yet but a quick test at removing or reducing the specificity of those styles does show some ill effects in the site editor. 

If we can't lower the specificity of the classic margin auto styles, could we reintroduce the layout styles at a higher specificity in `classic.scss`? For the classic styles to be enqueued the theme can't have a theme.json, and so also wouldn't have global styles. The higher specificity then might not be an issue.

Something to explore perhaps, what do you think?

**Comment by andrewserong** [comment]
Thanks for taking a look, Aaron! 🙇 

> could we reintroduce the layout styles at a higher specificity in classic.scss? ... Something to explore perhaps, what do you think?

Worth trying, especially since this is all about just a single rule! I have a few other tasks to focus on this week, so might not have much time to immediately work on this PR, but I'll come back to it 👍

**Comment by aaronrobertshaw** [comment]
> I have a few other tasks to focus on this week, so might not have much time to immediately work on this PR, but I'll come back to it

Understood, I'm in the same boat. 

FWIW I've given the following snippet a quick run by appending it to `classic.scss` and for me it sorts out the flex and grid layouts using classic themes along with this PR. The fix for the original issue continues to work also.

I don't think I have a full grasp on all the ins and outs of the layout support styles so there's every chance I've missed something. I'll happily wait until you have a chance to revisit this, then I can test and review again.

```scss
/**
 * Layout Styles
 */
.editor-styles-wrapper {
	.is-layout-grid > *,
	.is-layout-flex > * {
		margin: 0;
	}
}
```

**Comment by sabernhardt** [comment]
Related: [Trac 60080](https://core.trac.wordpress.org/ticket/60080)

**Comment by andrewserong** [comment]
This PR is pretty old now, and there are specificity reduction efforts happening elsewhere, so I'll close this PR out for now.

**Pull request closed without merging**
