### PR TITLE
Move the reusable UI to the top

### PR DESCRIPTION
**Pull request by jasmussen**
Now that you can create very long blocks, the UI for entering the name of a reusable block fits better at the top.

GIF:

reusable ui near top

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Looks and works great.

**Comment by youknowriad** [comment]
Oh the test failure seems legit.

**Comment by mtias** [comment]
This makes a lot of sense.

**Comment by jasmussen** [comment]
So, this was the failing test:

screen shot 2018-09-12 at 13 29 38

Which I fixed in https://github.com/WordPress/gutenberg/pull/9818/commits/2bd8e70149e401baebb7480f028570ff96fa02ac. 

However — I have ZERO idea why those tests failed for me. The test expected "Oh! Hello there!", but the snaps showed "Hello there!" — I haven't touched those files at all. Where and how did this change because it wasn't in this PR?

**Comment by youknowriad** [comment]
yes, I don't think we should just change those strings without understanding why, I'll look

**Comment by youknowriad** [comment]
It looks like "editing" is not working properly in the test

**Comment by jasmussen** [comment]
I'm unsure how to fix that, or, frankly, why this PR caused them to fail.

**Comment by youknowriad** [comment]
It's related to the tab order, I pushed a fix, let's see how it goes.

**Comment by jasmussen** [comment]
Thank you Riad!

**Pull request merged**
