### PR TITLE
Tags: Fix the tags input in IE11

### LINKED ISSUE #8653: IE11: Clipped placeholder text inside of the tag field in the document sidebar
**Describe the bug**

In IE11, the "Tag" field in the document sidebar has the bottom of the placeholder text clipped off:

screen shot 2018-08-07 at 8 13 53 am

**To Reproduce**

1. Use IE11
2. Open the document sidebar
3. Expand the "Tag" section

**Tested in**
Windows 7, IE 11.0.9600.19080
Gutenberg 3.4

### PR DESCRIPTION
**Pull request by youknowriad**
closes #8653

**Testing instructions**

 - Check that the tags input's placeholder is not cropped in IE11

### CODE REVIEW

**Comment by aduth** [comment]
Why does this happen?

**Comment by youknowriad** [comment]
I don't really know, I noticed that if you put a line-height in inputs, its height increase accordingly in other browsers but not in IE. http://joshnh.com/weblog/line-height-doesnt-work-as-expected-on-inputs/ 

Apparently, we can drop the line-height entirely. I'll try later.

**Comment by jasmussen** [comment]
Could we do with a min-height instead of a height?

**Comment by youknowriad** [comment]
min-height works, updated

**Review by jasmussen — APPROVED** [review]
Cool.

**Comment by aduth** [comment]
So what is effectively the line height of that input now? Will it appear visually centered in the 24px height?

**Comment by aduth** [comment]
Yes, that appears to be correct 👍 https://codepen.io/aduth/pen/mjgGLO

**Pull request merged**
