### PR TITLE
Update list layout action styling

### PR DESCRIPTION
**Pull request by jameskoster**
This PR updates some style details in list layout now that actions have been added.

### Align along X axis
This matches table layout and eliminates the uncanny alignment visible on trunk:

| Before | After |
| --- | --- |
| Screenshot 2024-05-20 at 16 15 26 | Screenshot 2024-05-20 at 16 15 56 |

### Icon color on selected items

This also matches table layout. Specifically: Icon buttons remain `$gray-900` when the list item is selected.

| Before | After |
| --- | --- |
| Screenshot 2024-05-20 at 16 13 41 | Screenshot 2024-05-20 at 16 13 51 |

### Improve truncation

When hidden, actions are positioned so that they do not occupy any visual space. This allows the title to span the full width of the row:

| Before | After |
| --- | --- |
| Screenshot 2024-05-20 at 16 19 40 | Screenshot 2024-05-20 at 16 19 02 |

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
WFM.

Separately, I wonder, is this line-height a bit tall?

Screenshot 2024-05-21 at 09 30 23

**Comment by jameskoster** [comment]
> Separately, I wonder, is this line-height a bit tall?

Yes good spot. I pushed some tweaks to reduce the spacing between title + field values. Also to update the front/posts page badges.

| Before | After |
| --- | --- |
| Screenshot 2024-05-21 at 12 16 52 | Screenshot 2024-05-21 at 12 16 46 |

**Comment by jameskoster** [comment]
I think the tests are failing because the buttons are hidden using `display: none`. Even though they're visible when the row is focused/selected/hovered I suspect this could be an issue for screen readers. I'll try a different hiding method.

**Comment by keoshi** [comment]
@cleacos @madebynoam @lucasmendes-design @jeffgolenski

This PR can also impact our usage of the data view component.

**Comment by jameskoster** [comment]
The failing tests here seem to relate to the dropdown component rather than the changes in this PR 🤔 

If @ntsekouras or someone from @WordPress/gutenberg-components has time to take a look I'd appreciate it 🙏

**Comment by tyxla** [comment]
> The failing tests here seem to relate to the dropdown component rather than the changes in this PR 🤔
> 
> If @ntsekouras or someone from @WordPress/gutenberg-components has time to take a look I'd appreciate it 🙏

Attempting the usual suspect fix with waiting for the focus in https://github.com/WordPress/gutenberg/pull/61797/commits/9aadc16b916d5bf4188c50f5e217efa33e1b10a7.

**Comment by tyxla** [comment]
Seems like it's all green and good to go. Disabled the auto-merge because it needs a rebase.

**Comment by ntsekouras** [comment]
Thank you @tyxla for looking into the tests failure!

**Pull request merged**
