### PR TITLE
WIP: Check for Theme Support before adding style attributes in editor

### LINKED ISSUE #26506: Background Colors assigned as 'preset' colors do not render correctly in the editor while in dark mode.
Causes https://github.com/Automattic/themes/issues/2644

When a 'preset' color is selected as the background color for an element BOTH of these things happen in the editor:
* the background-color is set as a style attribute to the color value selected (i.e. style="background-color:rgb(0,0,0)")
* the appropriate class is applied to the element (i.e. class="has-PRESET-background-color")

While the user's preferences are set to "light mode" this renders fine; the color values are the same.

The 'dark mode' of a theme changes the preset values to support that dark mode and the value are no longer the same as defined by the theme for the editor's consumption. Thus, while the user's preferences are set to "dark mode" this does NOT render fine as there is a mismatch between what the expected "preset" color is as represented in the editor and what will actually render as defined by the theme.

What is rendered in the VIEW is correct, as only those elements that have a custom color that is NOT set to a 'predefined' color have the style attribute added.

**To reproduce**
1. Set your system appearance to 'Light' mode.
1. Activate Spearhead (a theme that has dark mode support).
2. Add a <p> block to a page and add some text.
3. Change the background color to the preset 'Foreground' which is represented as a BLACK color option.
4. Note that the Background Color of the <p> block is correctly rendered as BLACK (and foreground text white).
5. Change your system appearance to 'Dark' mode.
6. Note that the Background Color of the <p> block is still rendered as BLACK (however the foreground text is now also black).
7.  Publish the page and observe it in VIEW mode.
8. Note that the <p> tag is correctly rendered with a "white-ish" background (the FOREGROUND color of the theme while in dark mode).

**Expected behavior**
An element that has a BACKGROUND COLOR or TEXT COLOR applied that is NOT a 'custom color' but instead a color defined as a 'preset' color should NOT have the color values applied via a style attribute, but only by way of the 'preset' color classes.  (This is the same color attribute assignment behavior found in the rendered view.)

**Screenshots**
`<p>` block in editor view with 'Foreground' preset color applied as the background (light mode):
image
The same block in view mode (light mode):
image

`<p>` block in editor view with 'Foreground' preset color applied as the background (dark mode):
image
The same block in view mode (dark mode):
image

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg"
- If the Gutenberg plugin is installed, which version is it? 9.2.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: FireFox

**Additional context**
- This has been raised in the context of this issue: https://github.com/Automattic/themes/issues/2644

### PR DESCRIPTION
**Pull request by pbking**
## Description

When the Block Editor handles blocks that support color, if the color
applied is a palette color the value of that color is still applied by
way of a style attribute.  This is done to provide backward
compatability for themes that don't include the palette CSS in their
editor stylesheet.  However, for themes that DO provide those classes,
and especially for those where the behavior isn't just "change the
color" (i.e. Spearhead 'dark' mode) this logic breaks expected behavior.

This is an attempt to allow a theme to express, by way of a theme
supports flag, that those style attributes should NOT be applied to the
block; the classes will suffice.

Fixes: https://github.com/WordPress/gutenberg/issues/26506

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by pbking** [comment]
I expected this to be relatively simple but I got really stuck trying to get an updated value of the theme supports configuration.

The value of themeSupports appears to be cached in a way that I can't bust. It is pre-loaded in a `<script id='wp-api-fetch-js-after'>` and the value doesn't reflect what is CURRENTLY set by a theme (by adjusting values set by add_theme_support in functions.php).

I have not been able to find the code that queues this 'wp-api-fetch-js-after' inline script to determine what's happening. Instead it appears to be some historical value. Even attempting this on a completely fresh WordPress installation didn't provide the values expected.

Also attempted was to bump the version in the theme I am testing with, but to no avail.  The changed VERSION (via style.css) of the theme IS correctly expressed in that preloaded data...but the value of themeSupports is not.

**Comment by youknowriad** [comment]
This is a very complex thing. I think personally we shouldn't be introducing a new theme support or config but we should instead do this:

 - Automatically generate the styles from the define palettes and inject it to the editor
 - Remove that fallback.

I actually thought the first step here was already implemented by @jorgefilipecosta at some point for Global styles. Maybe @nosolosw could confirm or deny that?

**Comment by pbking** [comment]
Hey @youknowriad if I understand correctly, that actually IS what is happening (by way of #22356).  That is what I am attempting to UNdo (in a targeted way).   In this instance, Spearhead has a dark mode, and when that is the case the palette color "Black" actually is a white color, which is correctly handled and expressed in the class applied to the block, but that value (in that scenario) is different than the "light" version that is expressed in the hex value in the color palette.

**Comment by youknowriad** [comment]
>  In this instance, Spearhead has a dark mode, and when that is the case the palette color "Black" actually is a white color, 

How is this spearhead doing this? By using a global classname or something? How do you think such behavior should be handled with global styles in mind (no css basically)?

This seems to fall into the use-case of "nested context" maybe? this is: potentially being able to define styles for a specific context which in this situation would be a `.wp-style-is-dark-mode` container. And done this way, I assume global styles would generate the right CSS for it. We don't support nested contexts like that yet though. So I wonder if we should introduce a stopgap for now or not. (and maybe leaning towards the latter)

**Comment by pbking** [comment]
I would assume that Global Styles would always appropriately supply the classes to drive this scenario, so I would expect that if styles were being driven by theme.json then this flag should be defaulted to TRUE making the behavior of adding the colors to the style attributes a thing that only happens for "classic" themes (and then, only classic themes without the flag).  At least that's the fix I was working towards.  Any ideas that stop forcing the color into the style attribute would be a dandy fix.

Spearhead handles this pretty cleanly with a media query.  If a user has a system dark mode set and a user uses a palette color then the class for that palette color is just re-defined as the inverse(ish).  Something only do-able in CSS due to the media-query but still very do-able in combination with theme.json styling techniques.

**Comment by youknowriad** [comment]
Doing some cleanup to old PRs. This draft PR seems staled. Is it still relevant. Closing but let me know if I missed anything.

**Pull request closed without merging**
