### PR TITLE
Don't add default-custom-properties styles to all compiled files

### LINKED ISSUE #27663: Block styles contain duplicated styles
**Describe the bug**

Came up in https://github.com/WordPress/gutenberg/pull/25220#issuecomment-742603823

The build worker for Sass files adds [_default-custom-properties.scss](https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_default-custom-properties.scss) to all compiled files:

https://github.com/WordPress/gutenberg/blob/5060734d4cf0002cc0f4d0c02bfd7e86b6de7d1a/bin/packages/build-worker.js#L112-L116

The default-custom-properties file only contains styles for the admin-color scheme so should only be added to editor styles.

cc @gziolo who initially reported the issue in the PR.

### PR DESCRIPTION
**Pull request by aristath**
Fixes https://github.com/WordPress/gutenberg/issues/27663

After we split compiling of block-styles in https://github.com/WordPress/gutenberg/pull/25220 we noticed that some styles get duplicated in all blocks.
This PR fixes the issue by correcting where the `default-custom-properties` get included.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
I wish we had visual regression testing integration 😄 

Based on the comment from the bot, it looks like it works like a charm. So great work on that field. It still needs to be verified that nothing has changed in the UI for
- non-FSE theme
- FSE theme

**Comment by aristath** [comment]
Examining the compiled files in `build/block-library/` I can see that the styles are properly included in the `build/block-library/style.css` file which is used for non-FSE themes, and the `build/block-library/common.css` file which is used for FSE themes, so it _should_ be OK.
Previously these styles were also included in `build/block-library/blocks/*/style.css` files for FSE themes - which is no longer the case :+1:

**Review by gziolo — APPROVED** [review]
Based on the previous comment 🚢

**Comment by carolinan** [comment]
Thank you for fixing this, 
this is also a quality of life improvement, it was starting to annoy me every time I opened the dev tools 😄 
Before 😄

before |    | 

With the pull request applied:

after

**Comment by aristath** [comment]
Pushed an additional commit to make sure only the `block-library` files get affected by the PR.

**Comment by aristath** [comment]
Tested with an FSE theme and a non-FSE. Looked in all scss files for the admin-scheme vars and they are only used for editor styles. The vars are properly defined in the editor and removed on the frontend.

**Comment by jasmussen** [comment]
I think this one regressed color themes inside the editing canvas. Say you pick "Midnight" as color theme, the focus style for selected blocks should be red. But it's now WordPress blue.

**Comment by jasmussen** [comment]
Specifically, these two CSS variables are no longer available for content inside the editing canvas: `var(--wp-admin-border-width-focus)`, `var(--wp-admin-theme-color)`. @aristath any thoughts on whether this is easy or hard to fix?

**Comment by aristath** [comment]
Checking and will submit a follow-up PR :+1:

**Comment by jasmussen** [comment]
Happy to help test. Not urgent since it's scheduled for 9.9, but would be good to fix before then.

**Pull request merged**
