### PR TITLE
Adjust legacy widget form styles to match editor.

### LINKED ISSUE #32955: Styling issues with legacy widget form.
## Description
Styling of legacy widget is off as core CSS styles are not applied. Take this example from the [web stories](https://wordpress.org/plugins/web-stories/) plugin

Screenshot 2021-06-24 at 11 29 08

Compared the original view. 

Screenshot 2021-06-24 at 12 09 54

List of issues include.
- Strange font selection. As inputs are wrapped in P tags. 
- `.widefat` not applying to select menus. 
- Labels are bold
- Spacing issues. 

## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #32955 by adding styles for legacy widget form fields that match the editor defaults (as much as possible given we don't control the markup of third party widget forms.)

## How has this been tested?

Activate Twenty Twenty theme, install Web Stories plugin.
In Widgets editor, add Web Stories legacy widget and check that form fields look reasonably consistent with editor styles.

## Screenshots 

Screen Shot 2021-06-25 at 1 54 12 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by talldan — APPROVED** [review]
There are still a few things that look a bit out like the arrows on selects and number fields:
Screenshot 2021-06-25 at 3 15 06 pm

But I think this is already a great improvement and would be good to merge.

**Comment by talldan** [comment]
The test `Multi-entity save flow › Post Editor › Save flow should work as expected` is failing, but I'm going to merge this on the understanding that this PR only changes legacy widget block css, and can't possibly be causing that test to fail.

I think #32889 is fixing the issue with that test anyway.

**Comment by spacedmonkey** [comment]
I am still seeing issues with number and select fields. 

Screenshot 2021-06-25 at 17 13 15

It is a good step forward but doesn't fix the original issue #32955 . This is a simple css fix, any chance of getting this in? CC @tellthemachines

**Comment by tellthemachines** [comment]
@spacedmonkey your screenshot shows the styles previous to this PR are still applying. Can you rebuild your env with the latest changes and recheck?

**Pull request merged**
