### PR TITLE
Prefix useSimulatedMediaQuery __experimental

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Adds the `__experimental` prefix to `useSimulatedMediaQuery`. 

## How has this been tested?

Tested locally to make sure the function still works.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Looks good.

I noticed the linked conversation (https://github.com/WordPress/gutenberg/issues/23669#issuecomment-666089153) mentioned making it unstable, experimental seems ok too, but it might be worth documenting why in the PR.

**Comment by ellatrix** [comment]
Experimental = we plan to stabilise it
Unstable = internal thing that we can't hide

**Comment by youknowriad** [comment]
Are we ok changing that today without ensuring at least 2 releases backward compatibility in the plugin?

**Comment by ellatrix** [comment]
The alternative being that we just return the string untouched if we deprecate it?

**Comment by youknowriad** [comment]
yes, something like that. searching on wpdirectory.net it seems it's not being used by third-party code. So I'm fine either way.

**Pull request merged**
