### PR TITLE
Add preformatted block

### PR DESCRIPTION
**Pull request by ellatrix**
See #516.

### CODE REVIEW

**Comment by iseulde** [comment]
This block is meant for preformatted text, not code. Feel free to change or remove the content added.

**Comment by iseulde** [comment]
See #826 for code block.

**Comment by jasmussen** [comment]
Nice!

I think we should zero out the margin on the `pre`. The margin will then be implied by the block padding instead. Otherwise works exactly as I would have expected. Very cool!

**Comment by jasmussen** [comment]
Did some polish here. 

One thing is missing from the stylesheet, and that's the new code font size variable that I introduced for the code block in https://github.com/WordPress/gutenberg/pull/826/commits/215881cd38ea799c797c459cce2d4a416bad3110. So once we have both merged, we should add `font-size: $text-editor-font-size;` to this pre block.

**Review by aduth — APPROVED** [review]
Conflicts, but otherwise looks good 👍

**Pull request merged**
