### PR TITLE
Revert date changes from branch 'replace-moment'

### PR DESCRIPTION
**Pull request by vcanales**
Revert changes from https://github.com/WordPress/gutenberg/pull/25782 and https://github.com/WordPress/gutenberg/pull/27002. The move made on https://github.com/WordPress/gutenberg/pull/25782 was prematurely deemed correct, and a lot of timezone issues were surfaced later. The plan going forward is to improve on testing, including testing on multiple timezones. 

This will deal with a collection of issues, which should be taken into account when this is revisited:
- https://github.com/WordPress/gutenberg/issues/27500
- https://github.com/WordPress/gutenberg/issues/27159
- https://github.com/WordPress/gutenberg/issues/27251

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by david-szabo97** [comment]
Unit tests are passing locally  ✅
Creating a new post shows Publish as expected   ✅
Calendar is showing the correct date ✅ 
Sidebar is showing the correct date  ✅

Let's see what happens to the E2E tests.

**Comment by ockham** [comment]
For context: We've decided to revert after discussion between @vcanales, @david-szabo97, and myself, since the `moment` -> `date-fns` migration seems to have cause a number of issues (https://github.com/WordPress/gutenberg/issues/27514, https://github.com/WordPress/gutenberg/issues/27251), some of which have the potential to crash the editor.

While we have two fixes in the works (WordPress/gutenberg#27398 and WordPress/gutenberg#27519), it's hard to ensure that they cover all issues and don't introduce new bugs, since we're also lacking test coverage (https://github.com/WordPress/gutenberg/issues/27500).

Our plan is thus:

- [ ] Revert (@vcanales)
- [ ] Add test coverage for all those issues, and any UI issues that we're finding now (@david-szabo97)
- [ ] Add a test matrix in CI for different timezones and locales (@ockham)
- [ ] Re-attempt the migration

**Review by david-szabo97 — APPROVED** [review]
Tested in UTC-10 and UTC+10, LGTM ✅

**Comment by swissspidy** [comment]
@vcanales Did you ever get around to taking another stab at this?

**Pull request merged**
