### PR TITLE
BorderBoxControl: Reduce gap value when unlinked

### LINKED ISSUE #65207: BorderBoxControl: Horizontal scrollbar is displayed in block sidebar
### Description

Note: This can be reproduced on Windows OS/Chrome browser where the browser scrollbar has a physical width.

The sidebar width is 280px. However, due to a 17px scrollbar on Windows OS/Chrome browser, the actual content width is 263px. In this case, the box control does not fit into the grid layout and an overflow occurs.

### Step-by-step reproduction instructions

Access a block that supports borders and click the "Unlink sides" button.

### Screenshots, screen recording, code snippet

image

image

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #65207

## What?

~~This PR narrows the width of the input field so that the `BorderBoxControl` component doesn't overflow the block sidebar.~~

This PR changes the gap of the `BorderBoxControl` component from 16px to 12px to prevent horizontal scrolling in block sidebars.

## Why?

When a block sidebar has a scrollbar, the width of the container in which the `BorderBoxControl` component is rendered is `231px` on Windows and `233px` on MacOS.

On the other hand, the `BorderBoxControl` component has a width of `248px` (Input field `116px` + gap `16px` + input field `116px`). This width is larger than the container width on both Windows and MacOS.

## How?

~~Change the input field width to 104px. This makes the entire component width smaller than the block sidebar container width.~~

Change the Gap value from `16px` to `12px`. The BorderBoxControl component still overflows its container, but the horizontal scrollbar no longer appears.

## Testing Instructions

- Insert a Paragraph block.
- Open the Border setting from the Dimensions panel.
- Click the Unlink sides button.

## Screenshots or screencast 

~~In my environment (Windows OS), the number of digits that can be displayed changes from 4 to 3, but I'm sure there are very few users who want to apply a 4-digit border.~~

| Before | After |
|--------|--------|
| image | image |

### CODE REVIEW

**Comment by t-hamano** [comment]
I am wondering whether we should also change the width when linked:

https://github.com/WordPress/gutenberg/blob/865a05834d3af46a6eecd142fe6acda40642756d/packages/components/src/border-box-control/border-box-control/component.tsx#L115-L117

**Review by tyxla — COMMENTED** [review]
This doesn't look too good on MacOS with even 3-digit numbers for borders:

Screenshot 2024-11-18 at 16 32 23

Increasing it to 108px seems to do the job for me:

Screenshot 2024-11-18 at 16 32 35

I wonder if that would be an acceptable compromise on Windows as well?

**Comment by t-hamano** [comment]
Thanks for the review!

> Increasing it to 108px seems to do the job for me:
> I wonder if that would be an acceptable compromise on Windows as well?

At 108px, it will overflow the container width of `231px` by 1px on Windows (Input field `108px` + gap `16px` + input field `108px` = `232px`).

This might be acceptable, but what do you think?

231px


Another thing I noticed is that when I select the `rem` unit, the input field becomes narrower:

| trunk (116px) | This PR (108px) |
|--------|--------|
| image| image| 

Personally, I think few users will want to use a radius larger than 100px, so as long as two digits are always visible, I think it's acceptable.

**Review by tyxla — COMMENTED** [review]
I'm a bit worried about this solution, since we're chasing ghosts.

Would it be better if we just reduce the `gap` prop from `4` to `3`? That would reduce the gap between the left and right control groups, and maybe fix the overflow issue, which is the primary reason for this PR?

**Comment by t-hamano** [comment]
> Would it be better if we just reduce the `gap` prop from `4` to `3`? That would reduce the gap between the left and right control groups, and maybe fix the overflow issue, which is the primary reason for this PR?

This approach prevents the horizontal scrollbar from appearing:

image

But the component is overflowing the container width:

image

Maybe this is a good approach for now 🤔

**Comment by tyxla** [comment]
I'm personally OK with this. Should we ping @WordPress/gutenberg-design just in case?

**Comment by jasmussen** [comment]
I think this one is fine to ship without changing gaps, as fixing the horizontal scrollbar is the most important. Text inputs are organically scrolling horizontally, for example you might have a default address input field where a very very long irish address might require you to use the right hand arrow-key to navigate to the end of it. What if someone wanted a 999999px border? We can only optimize for the 80% use case, and thankfully base inputs handle the rest.

What I do think we can do separately, is consider changing the default width of the inspector from 280px to potentially 284px. I also think the "rem" unit selector button can become square in aspect ratio; that might mean the 2 letter _rem_ text might have very little padding, but since it's a text only button, that shouldn't be too big a problem. But as a unit select, I don't expect it to change size between selections, just like I wouldn't expect a select control to change sizes between selected options. A -1px letter spacing option could even be explored for the unit itself.

**Comment by t-hamano** [comment]
In this PR, I adopted the approach of changing the gap from 4 (16px) to 3 (12px). I also updated the PR description and screenshots.

> What I do think we can do separately, is consider changing the default width of the inspector from 280px to potentially 284px. 

This approach also works.

In fact, it only takes a 1px adjustment somewhere to make the horizontal scrollbar disappear 😅 I think we have two options: slightly increase the width of the sidebar or slightly decrease the gap of the BorderBoxControl or the width of the input field.


https://github.com/user-attachments/assets/96f60fde-ec13-4389-b535-1d37947224fc

**Comment by jasmussen** [comment]
I'm happy with either, or both, including making the individual inputs not quite as wide.

**Comment by t-hamano** [comment]
What do you think about merging this PR?

This PR simply reduces the gap value from `16px` to `12px`. In fact, it overflows the container width, but the horizontal scrollbar never appears.

**Comment by tyxla** [comment]
I'm personally good with merging it 👍 Feel free to ship, given we have a design approval on it.

**Review by jasmussen — APPROVED** [review]

**Review by tyxla — APPROVED** [review]

**Pull request merged**
