### PR TITLE
Update `react-dates` to 21.8.0

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Updates the `react-dates` dependency of `@wordpress/components` to 21.8.0.

## Why?
I was hoping that updating `react-dates` would fix the `console.warn()` that is emitted because `DayPicker` uses `componentWillReceiveProps` which is deprecated. Unfortunately it does not.

Still, it's probably worth updating the package anyway so that we have the latest bug fixes and security fixes.

## How?
I bumped the version in `packages/components/package.json` and ran `npm install`.

## Testing Instructions
This PR is based off of https://github.com/WordPress/gutenberg/pull/40754 which includes tests. You can also:

- Play around with the _Publish_ popover in the post sidebar to check that there is nothing off.
- Play around with the `DateTimePicker` story to check that there is nothing off.

### CODE REVIEW

**Review by ciampo — APPROVED** [review]
LGTM 🚀 

The fact that `react-dates` doesn't have a CHANGELOG with what's changed across versions doesn't help, but during my testing I couldn't find any regressions.

The package seems actively maintained, but the latest release is almost 2 years old — IMO we should consider alternatives.

**Review by aaronrobertshaw — COMMENTED** [review]
@ciampo was too fast for me 🚀 

I tested this as well.

- Publish popover looked & worked ok
- DateTimePicker story works well
- Tests still pass

**Comment by ciampo** [comment]
> @ciampo was too fast for me 🚀

Haha although the score at this point is probably like Marco 1 - Aaron 93 😅

**Comment by noisysocks** [comment]
Thanks for reviewing! I found a changelog here just FYI. Not a lot that concerns our usage of the package, really.

https://github.com/react-dates/react-dates/blob/master/CHANGELOG.md

**Comment by ciampo** [comment]
Thank you for surfacing the changelog! I had previously looked into the ["releases" section](https://github.com/react-dates/react-dates/releases) and somehow missed completely the CHANGELOG file 😅

**Pull request merged**
