### PR TITLE
Fix notice styling regression

### LINKED ISSUE #9422: Failure notices: text misaligned
Some failure notices look different from the success notices (apart from the used colors):

screen shot 2018-08-29 at 11 18 03

- text is not aligned vertically
- the notice height is smaller

Seems to me `noticeMessage` here:
https://github.com/WordPress/gutenberg/blob/a7b4d66f154c87c79d36992590116a656b39a2e6/packages/editor/src/store/effects/posts.js#L278

should be wrapped within a paragraph.

### LINKED ISSUE #9725: Component notice for interacting with Reusable Blocks has improper HTML causing layout issue
**Describe the bug**
The notice component when interacting with a reusable block does not appear to have the correct HTML markup. The message should be wrapped in a **<p>** tag not a **<div>**.

**To Reproduce**
1. Create a block (example: paragraph)
2. Click on '...' (more options)
3. Click on 'Add to Reusable Blocks'
4. See message
5. Click Save
5. See message again

**Expected behavior**
Aligned correctly with proper HTML markup.

**Screenshots**
error

### PR DESCRIPTION
**Pull request by youknowriad**
Just a tiny PR aligning notices properly.

closes #9725  and closes #9422

I suspect this being a regression of #8856

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Confirmed, fixes this! Scratching it from my own list, thanks Riad! 

screen shot 2018-09-10 at 14 30 16

**Comment by afercia** [comment]
@youknowriad shouldn't the notices always be wrapped in a paragraph as https://github.com/WordPress/gutenberg/pull/9426 was proposing for #9422 ?

**Comment by youknowriad** [comment]
@afercia The issue is that in some cases, the paragraph styling is changed (like in the sidebar) breaking the notices, An alternative fix would have been to override the notices styles as well in the sidebar, I preferred the "smaller" change.

**Comment by afercia** [comment]
OK thanks, going to close the other PR then.

**Pull request merged**
