### PR TITLE
Update cleanForSlug() to remove additional non-word characters

### LINKED ISSUE #12907: Some inappropriate characters are included in auto-generated permalinks
**Describe the bug**

In WordPress 5.0.1, creating a post or page with colons or exclamation marks in the title produces a permalink that takes the expected post/page slug form (lowercase alphanumeric with hyphens instead of spaces) but includes these special characters. Once the post/page is published the characters are stripped from the permalink.

**To Reproduce**

1. Create a new post or page.
2. Enter a title with colons or exclamation marks.
3. Save draft.
4. Inspect the permalink.

**Expected behavior**

The permalink should contain only alphanumeric characters and hyphens, even before publishing the post/page.

**Screenshots**

The bug visible in the page title:

Screen shot of the page title and permalink.

The bug visible in the document inspector:

Screen shot of the permalink the document inspector.

**Desktop:**

 - OS: macOS Mojave 10.14.2
 - Safari 12.0.2

**Additional context**

- I'm using the WordPress 5.0.1 bundled version of Gutenberg.
- Other characters may be included as well, but I ran into the issue with these two (colon and exclamation mark) and haven't explored further.

### PR DESCRIPTION
**Pull request by earnjam**
## Description
This updates the `cleanForSlug()` function to remove punctuation characters that would get removed by `sanitize_title()` upon publishing. 

This fixes the original issue from #12907 regarding punctuation in the slug. It doesn't resolve the related issues referenced there that were opened for characters in other languages (such as German and Danish) not being converted properly. If we merge this and close #12907, we may want to reopen one of those that was closed as a duplicate in order to keep a more accurate record. 

On investigating removing other punctuation, I realized `sanitize_title()` allows underscores in slugs, so I adjusted the function to allow those, but to remove any other non-hyphen punctuation. I also removed the `toLower` dependency and switched to `.toLowerCase()`

## How has this been tested?
Used identical strings with a variety of characters in the classic editor and in the current editor to test how they compared. Also updated the unit tests to reflect the new characters that should be removed. 

## Screenshots 
Here is a sample string in the classic editor:
Screen Shot 2020-03-18 at 1 14 05 PM

Vs the block editor after this change:
Screen Shot 2020-03-18 at 1 15 26 PM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by aduth** [comment]
> to remove punctuation characters that would get removed by `sanitize_title()` upon publishing.

For posterity's sake, the reference implementation:

https://github.com/WordPress/wordpress-develop/blob/5.3.2/src/wp-includes/formatting.php#L2145
https://github.com/WordPress/wordpress-develop/blob/5.3.2/src/wp-includes/formatting.php#L1215-L1986

**Review by aduth — APPROVED** [review]
This seems like a reasonable change to me.

Do you know of any usage of `cleanForSlug` which may have relied on this behavior, broken as it may have been, for which these changes might cause some unforeseen incompatibility?

If the idea is for it to adhere to core's equivalent treatment of `sanitize_title`, it could be a good idea (perhaps separately from here) to include some or all of its test cases:

- https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/formatting/SanitizeTitleWithDashes.php
- https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/formatting/SanitizeTitle.php
- https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/formatting/RemoveAccents.php

**Comment by earnjam** [comment]
I have another branch I started for duplicating `sanitize_title()` in JS, but this seemed like a quicker win until I could get that complete and more broadly tested.

**Comment by gziolo** [comment]
Should we add a note in the changelog of the url package? It looks like it can be merged otherwise.

**Pull request merged**
