### PR TITLE
Use custom name in block sidebar if available (retaining block type information)

### PR DESCRIPTION
**Pull request by getdave**
## What?

~Removes the block's name (e.g. `Group`) from the inspector controls if a custom name is defined.~

Use custom name (e.g. "My cool block") in block sidebar details panel if defined and include a "badge" to retain information about the original block type (e.g. `Group`).

## Why?

Suggested by @richtabor in https://github.com/WordPress/gutenberg/pull/65398#issuecomment-2368853179.

Discussion in this PR has evolved the concept somewhat.

## How?

Change code.

## Testing Instructions

- Create x2 Group blocks
- Rename the first Group block with a custom name.
- Check that only the custom name/block name is shown in the block's inspector controls based on whether the block has/hasn't a custom name.

## Screenshots or screencast 

Screen Shot 2024-12-16 at 11 23 14

Screen Shot 2024-12-16 at 11 23 02

### CODE REVIEW

**Comment by jameskoster** [comment]
I wonder if it makes sense to include the description when what the block has a custom name. It can make for clunky reading:

Screenshot 2024-09-25 at 11 52 59

**Comment by getdave** [comment]
I'm just going to flag that I'm not sure if there might be accessibility concerns that we should consider here for non-sighted users who may lack the ability to perceive the nature of this block (i.e. a Group block) without the affordances offered by:

- the actual name of the block (i.e. `Group`)
- some description of the block

I wonder if @jeryj can offer any insight here? 

I'm wondering whether removing _all_ context about the block from this panel is actually helping our users. It might look "cleaner" but potentially at the cost of adding confusion.

**Comment by t-hamano** [comment]
I re-read #53735, and it looks like the block renaming feature was introduced to make blocks easier to distinguish/find in the List View.

If only the custom block name was shown in the inspector control, it would feel less relevant in the Settings and Styles panels below.

Another reason is that in Figma for example, the Layers panel shows the custom name, but the design panel shows the original component name:

figma

Therefore, I lean towards keeping it the way it is.

**Review by draganescu — DISMISSED** [review]
Yes.

Edit:

What if we add the block name before the description so text here

image

would read:

**Client testimonial**
Group block. Gather blocks in a container.

**Comment by jeryj** [comment]
It's confusing to me to rename the sidebar settings with the renamed section. I would rather not put the custom name in the inspector controls. In the list view, the custom name is helpful because it helps you identify which item you want to select. You can't select anything via the inspector, so I think it should remain Group Block so it's an accurate representation of what you have selected.

**Comment by draganescu** [comment]
I think @jeryj has a point - and actually seeing the block description under block name is quite weird.

**Comment by getdave** [comment]
Thinking back to when we introduced renaming, I'm sure we had a similar discussion. I cannot find it though as Github appears to have buried it.

**Comment by jameskoster** [comment]
Seeing the custom name in the Inspector can provide helpful context when List view is closed. Technically the icon should communicate the block type but I appreciate that's not a great affordance currently in term of a11y, maybe a tooltip would help?

Block descriptions are generic... if the block has a custom name it's generally no longer generic and the description can be confusing. I'd be tempted to hide it.

**Comment by draganescu** [comment]
@jameskoster @richtabor does [this suggestion](https://github.com/WordPress/gutenberg/pull/65641#pullrequestreview-2328140456) have any downsides?

**Comment by getdave** [comment]
TBH @draganescu's suggestion seems like the best compromise.

**Comment by richtabor** [comment]
> @jameskoster @richtabor does this suggestion have any downsides?

Just makes it seem more complicated than it needs to be. 

For example, the heading block would read: 

"Heading block. Introduce new sections and organize content to help visitors (and search engines) understand the structure of your content." 

I don't think the description should change based on if you have a custom block name or not, and it would be duplicative to have a Heading label above the description, then lead with "Heading block.".

**Comment by draganescu** [comment]
> I don't think the description should change based on if you have a custom block name or not

Well, that is a trade off compared to not having the block type shown _anywhere_ in the inspector and having to intuit from the block icon or from opening the list view what kind of block you have selected.

> it would be duplicative to have a Heading label above the description, then lead with "Heading block.".

There is no duplication? This PR removes the block type from the title of the panel, to leave the title of the panel exclusively to the block name, manually set by the user.

**Comment by jameskoster** [comment]
Just my opinion, but I find that generic block descriptions combined with specific (custom) block names often leads to confusing and unclear reading. I don't have a strong preference in any direction but could see one of the following working:

1. Show custom block name, hide description. Add tooltip to block icon making it possible to understand block type.
2. Do not show custom block name in the Inspector.
3. Find another way to show custom block names in the Inspector, maybe something similar to how we mark special pages in the document inspector:

Screenshot 2024-09-30 at 13 20 00

**Comment by draganescu** [comment]
Between all options I think the last suggestion from @jameskoster is the best: a label that happens to also look like a label.

**Comment by t-hamano** [comment]
> maybe something similar to how we mark special pages in the document inspector:

Perhaps it will look something like this?

| Paragraph| Table of contents |
|--------|--------|
| image | image |

Or are the default and custom block names reversed?

| Paragraph| Table of contents |
|--------|--------|
| image | image |

**Comment by getdave** [comment]
@t-hamano @jameskoster @richtabor I've updated the PR to utilise the `Badge` component for the block name _if_ a custom name has been defined.

Screen Shot 2024-12-16 at 11 23 02



I don't know about the accessibility of this approach and whether it's necessary that we "decorate" the Badge with additional meta data to denote that it is the name of the block.

**Review by mikachan — APPROVED** [review]
This tests well for me:

- I can see the block name in a badge when the block has a custom name ✅ 
- If a block doesn't have a custom name, then I do not see the badge ✅ 

| trunk | This PR |
| ---- | ---- |
| image | image |

The current design using the badge makes the most sense to me, as it's similar to the page/template name and label:

image

> I don't know about the accessibility of this approach and whether it's necessary that we "decorate" the Badge with additional meta data to denote that it is the name of the block.

I don't see any additional attributes or meta data on the page/template title example above, so based on that, I think the markup is fine. 

I'm leaving a tentative approval, but as I wasn't involved in the previous discussions it'd be good to have some additional eyes on this if possible.

**Comment by jameskoster** [comment]
@getdave do you think the badge could wrap beneath the title when it's long? Similar to the page inspector:

Screenshot 2024-12-16 at 15 02 29

Screenshot 2024-12-16 at 15 04 03

---

> Or are the default and custom block names reversed?

I kind of lean towards this approach, as it leaves the familiar block icon + block title untouched. Not a strong feeling though :)

**Comment by getdave** [comment]
@jameskoster You mean like this...?

Screenshot 2024-12-16 at 15 57 33
Screenshot 2024-12-16 at 15 57 28

**Comment by jameskoster** [comment]
For the wrapping, yes thank you 👍 

The only other piece to decide is what goes in the badge; the canonical block name, or the custom one? 

I kind of like putting the custom name in the badge, because it preserves the familiar icon + block name pattern. However, custom names can be long, and the badge component isn't really designed to handle long strings so looks a bit awkward when wrapping:

Screenshot 2024-12-17 at 12 32 09

That said, long names are elided in List View, so perhaps we could do that in the Inspector too?

Screenshot 2024-12-17 at 12 34 26

Or we just leave things as they are and figure this out separately.

**Comment by getdave** [comment]
I may have jumped in too soon with the merge here. However, luckily if you want to swap those around it will be simply a case of swapping the variables in the implementation.

**Comment by jameskoster** [comment]
No strong feelings on my part, let's see if anyone else has thoughts :)

**Comment by t-hamano** [comment]
Sorry for the late reply. When we have a custom name, we may need to align it with the block icon.

With custom name:

image

Without custom name:

image

**Comment by jameskoster** [comment]
Good spot @t-hamano. Agree the icon / text / badge should be aligned centrally along the X axis:

**Comment by t-hamano** [comment]
FYI, this component was just published to Storybook.

 https://wordpress.github.io/gutenberg/?path=/docs/blockeditor-blockcard--docs

**Pull request merged**
