### PR TITLE
ImageURLInputUI: fix focus loss when settings are changed

### LINKED ISSUE #58509: New lightbox UI triggers a focus loss
### Description

The 'Expand on click' lightbox UI has been moved into the URL input UI in https://github.com/WordPress/gutenberg/pull/57608

It appears the new UI hasn't been tested enough with keyboard as there'a a very clear focus loss, possibly more than one, when using the keyboard.

It appears to be one more case where a focusable element that has keyboard focus gets removed from the DOM without any focus management. Since the element that was focused doesn't exist any longer, focus is lost and the tab sequence starts from scratch from the document root.

Animated GIF to illustrate the focus loss:

focus loss

### Step-by-step reproduction instructions

- Add an image block or a Media & text block or any other block where it is possible to add a link to an image.
- Select the image.
- In the block toolbar click the 'Link' button.
- Press the Tab key five times to move focus to the 'Expand on click' suggested item.
- Press the Enter key.
- Observe the UI changes dynamically and the 'Expand on click' item is removed from the DOM.
- Press the Tab key.
- Observe the tab sequence start from scratch from the document root, from the WP logo.

Please text extensively with the keyboard to check for more potential focus losses.

Since this is a new bug in a new UI meant to be released in WP 6.5. it would be nice to fix it for the release. Cc @annezazu 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #58509

## What?
This PR prevents focus loss from occurring in the `ImageURLInputUI` component used in the Image block and the Media & Text block.

## Why?

My guess is that the components inside the popover will appear and disappear as the URL settings change, causing the focus to be lost unless you explicitly control the focus.

## How?

To control focus, this PR uses the following approaches:

- Allows the `URLPopover` component that the `ImageURLInputUI` component is internally rendering to receive the forwarded ref.
- Use the forwarded ref to refer to the `Popover` component that the `URLPopover` component is internally rendering.
- The `ImageURLInputUI` component focuses on the "first focusable element" each time its state changes based on the `URLPopover` ref.

This approach is also [used](https://github.com/WordPress/gutenberg/blob/408c1186af35e19ed040b8fa56765b1ac731969d/packages/block-editor/src/components/link-control/index.js#L218-L239) in the `LinkControl` component.

This PR allows URLPopover components to accept the ref, but does not necessarily require them to opt in, so there should be no impact to consumers.

Additionally, I added E2E tests to prevent regressions. I've tried to test as much as possible to make sure that the focus is as expected, but it might be a bit redundant.

### Testing Instructions for Keyboard

- Insert an Image block.
- Click the "Link" on the block toolbar.
- You can control everything using just the keyboard and never lose focus.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/54422211/ef5e86f8-b18e-473c-80b7-f62d7c1baf45

### CODE REVIEW

**Review by artemiomorales — APPROVED** [review]
Thanks for looking into this! It works and looks good to me.

**Comment by artemiomorales** [comment]
@t-hamano I added a small commit [here](https://github.com/WordPress/gutenberg/pull/58647/commits/821c7a6dcb261a4925812392e79af321b89de318) to ensure Expand on Click sets focus properly on closing. It may be redundant at the moment since we're handling focus with the `useEffect`, but it may also be good to have this in case someone tries to change the implementation in the future. What do you think?

**Comment by t-hamano** [comment]
@artemiomorales Thanks for the review! The E2E test you added also makes sense to me 👍

**Comment by ciampo** [comment]
Thank you for working on this, @t-hamano  and @artemiomorales !

In theory, `Popover` should be automatically handling keyboard focus when closing: focus should be moved back on the item that was focused before opening the popover, usually the popover trigger (this is achieved via the [`useDialog` hook](https://github.com/WordPress/gutenberg/blob/775eed2cb8e480e5978fd888ba8df7a98e7e53f4/packages/components/src/popover/index.tsx#L267), which internally [calls the `useFocusReturn` hook](https://github.com/WordPress/gutenberg/blob/775eed2cb8e480e5978fd888ba8df7a98e7e53f4/packages/compose/src/hooks/use-dialog/index.ts#L76)).


In this case, it looks like the trigger would be the toolbar button — I think it would be interesting to understand why focus couldn't be returned to that button in the first place ?

We could also argue that the new behavior could be considered an improvement over returning focus on the toolbar button, but I think it's important to understand why we're not seeing the expected behavior in the first place.

**Comment by t-hamano** [comment]
@ciampo 

> I think it would be interesting to understand why focus couldn't be returned to that button in the first place ?

Focus returning to the toolbar button when the popover is closed is working correctly. This PR resolves an issue where content inside a popover loses focus when it is re-rendered.

In this case, wouldn't you need your own focus control?

**Comment by ciampo** [comment]
Ah, got it! So, we're not closing a popover and opening a new one — the same `Popover` stays open, and we swap its contents, right?

If that's the case, then the current solution sounds good :)

**Comment by t-hamano** [comment]
> Ah, got it! So, we're not closing a popover and opening a new one — the same Popover stays open, and we swap its contents, right?

That's right. This problem is not an issue with the focus control provided by the `Popover` component, but an issue within the `Popover` component 😊

**Pull request merged**
