### PR TITLE
Show insertion point after the last block in a container

### LINKED ISSUE #28381: Support showing the insertion point after the last element of a block list.
After #27860 the insertion point (in between insierter) only shows up between two blocks due to a complex positioning logic (center it properly between blocks both vertically and horizontally), this had the side effect of removing the possibility to show at the end of the block list (for instance by selecting the last block, opening the inserter and hovering a block type).

Ideally, we could have a fallback in the calculations to show it right after the last block.

### PR DESCRIPTION
**Pull request by youknowriad**
follow-up to  #27860 (merge in the same changelog entry)
closes #28381

After #27860 the insertion point (in between inserter) only shows up between two blocks due to a complex positioning logic (center it properly between blocks both vertically and horizontally), this had the side effect of removing the possibility to show at the end of the block list (for instance by selecting the last block, opening the inserter and hovering a block type).

This PR solves that by considering a potential nullable next element.

There was also another issue where the hovering a block type in the inserter was showing the wrong insertion point indicator.

### CODE REVIEW

**Comment by kevin940726** [comment]
Thanks! Would probably review it next week. Could you also help to uncomment the tests we commented out before? Just want to make sure we pass the tests 😉.

**Comment by youknowriad** [comment]
> Could you also help to uncomment the tests we commented out before?

I think the test might have been refactored entirely, can't seem to find them.

**Comment by youknowriad** [comment]
nevermind, I was looking at the wrong test :)

**Comment by kevin940726** [comment]
Seems like this test (https://github.com/WordPress/gutenberg/pull/28418/checks?check_run_id=1760742282) is failing for whatever reason 🤔, could you please take a look :) ?

**Comment by youknowriad** [comment]
@kevin940726 It should be fixed now.

**Comment by kevin940726** [comment]
In #25849, there's a fix to show the indicator in between two blocks when the former one is selected (See the screenshot in the PR). When trying this in this PR, it seems like it's not working anymore. Any idea why?

Also, perhaps we should start writing some e2e tests for the insertion indicator to avoid regressions in the future.

**Comment by youknowriad** [comment]
I think the bug here is not in the current PR. It seems the issue is the fact that the insertion point in the state (reducer) is actually not "reset"  properly when you open the inserter a second time.

I believe this might be related to the fix @noisysocks or @talldan worked on to fix the position of the insertion after clicking "Browse All". I'm not really sure I understand the logic of that fix properly but it seems we're missing a reset at some point.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍 

Probably could use some comments to better understand the code though 😅

**Comment by stokesman** [comment]
It's great to see this work coming along. I was curious to see what the inserter button looked like in cases where the default block appender is already showing (at the ends of some block lists) and that is a bit funny but I found something else that is probably of greater concern.

When using the inserter button that appears at the end of a block list, a newly inserted block gets inserted based on the location of the selected block instead of the inserter button. I made a recording with three uses of the same inserter button and three different places where a block gets inserted. None of them the expected position:

https://user-images.githubusercontent.com/9000376/105943104-69c48a80-6015-11eb-83ef-71e0e5256728.mp4

**Comment by youknowriad** [comment]
good catch @stokesman I think it's fixed now.

**Comment by youknowriad** [comment]
The failing e2e tests here are a Core regression tracked here https://core.trac.wordpress.org/ticket/50025

**Comment by draganescu** [comment]
@youknowriad testing #28382 i got this weird behavior with the inserter not being removed. Can you think of anything from this PR that may be the cause, so I can open an informed issue?


https://user-images.githubusercontent.com/107534/106244522-af4ea680-6213-11eb-8525-9991aed82213.mp4

**Comment by youknowriad** [comment]
@draganescu I don't know really on top of my mind, the interactions here are a bit complex and I didn't test nested menus in popovers. Please do track this.

**Pull request merged**
