### PR TITLE
build: Patch boost install checksum mismatch error

### PR DESCRIPTION
**Pull request by dcalhoun**
## What?

Fix a install error for `boost`.

## Why?

The error prevents successful project builds both locally and on CI servers.

## How?

Apply the workaround provided by the React Native community to address a
checksum mismatch error that occurs when installing `boost`. The error
originates from issues with the `boost` host, JFrog.

https://github.com/facebook/react-native/issues/42180

## Testing Instructions

Verify CI tasks succeed.

### Testing Instructions for Keyboard

N/A, no user-facing changes.

## Screenshots or screencast 
N/A, no user-facing changes.

### CODE REVIEW

**Comment by derekblank** [comment]
It appears the CI is currently failing due to the patch being corrupt or not installable. Investigating...

```
**ERROR** Failed to apply patch for package react-native at path
  
    node_modules/react-native

  This error was caused because patch-package cannot apply the following patch file:

    patches/react-native+0.71.11.patch

  Try removing node_modules and trying again. If that doesn't work, maybe there was
  an accidental change made to the patch file? Try recreating it by manually
  editing the appropriate files and running:
  
    patch-package react-native
  
  If that doesn't work, then it's a bug in patch-package, so please submit a bug
  report. Thanks!
```

**Comment by derekblank** [comment]
Upgrading to `patch-package@8.0.0` and following the steps for [creating multiple patches for the same package](https://github.com/ds300/patch-package?tab=readme-ov-file#creating-multiple-patches-for-the-same-package) appears to have resolved the issue. 👍 

There are two remaining non-required CI failures for checking Node.js versions on windows-latest ([#](https://github.com/WordPress/gutenberg/actions/runs/7457685426/job/20290300018?pr=57658)), but they may not be related.

It may be just as straightforward to wait until the [RN 0.71 patch](https://github.com/facebook/react-native/pull/42177#issuecomment-1881271147) itself is introduced, rather than upgrade patch-package for the whole Gutenberg repo. I do think there is value in upgrading patch-package from 6.2.2 to 8.0.0 as was done in this PR, as eventually we would run into this bug again if ever using multiple patches in the future.

**Comment by fluiddot** [comment]
> It may be just as straightforward to wait until the [RN 0.71 patch](https://github.com/facebook/react-native/pull/42177#issuecomment-1881271147) itself is introduced, rather than upgrade boost for the whole Gutenberg repo.

For reference, the fix for the `boost` podspec has been released in the [React Native version 0.71.15](https://github.com/facebook/react-native/releases/tag/v0.71.15). If we upgrade to that patch version, the package patch wouldn't be necessary.

> I do think there is value in upgrading boost from 6.2.2 to 8.0.0 as was done in this PR, as eventually we would run into this bug again if ever using multiple patches in the future.

I agree, we might run in a similar situation in the future, so I'd also advocate upgrading `patch-package` to a newer version to support multiple patches.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

> There are two remaining non-required CI failures for checking Node.js versions on windows-latest ([#](https://github.com/WordPress/gutenberg/actions/runs/7457685426/job/20290300018?pr=57658)), but they may not be related.

Yep, they seem unrelated to the changes introduced in this PR, so I've re-run them. Once they succeed, we could merge the PR.

**Comment by fluiddot** [comment]
> > There are two remaining non-required CI failures for checking Node.js versions on windows-latest ([#](https://github.com/WordPress/gutenberg/actions/runs/7457685426/job/20290300018?pr=57658)), but they may not be related.
> 
> Yep, they seem unrelated to the changes introduced in this PR, so I've re-run them. Once they succeed, we could merge the PR.

All CI checks passed, I'll proceed with the merge to prevent the CI job `React Native E2E Tests (iOS)` fail in other Gutenberg PRs.

**Comment by derekblank** [comment]
Thank you for picking up the PR to merge this change, @fluiddot. 🙇 

I agree the long term solution should be the upgrade to React Native 0.71.15 outlined in https://github.com/WordPress/gutenberg/pull/57667.

**Pull request merged**
