### PR TITLE
Allow for HTML in `get_the_title`

### PR DESCRIPTION
**Pull request by getdave**
## Description
Fixes potential regression introduced in https://github.com/WordPress/gutenberg/pull/37866#issuecomment-1018716892 whereby `get_the_title` is escaped when in actual fact it's allowed to contain HTML.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
This looks great to me, thanks @getdave!

**Review by Mamaduka — APPROVED** [review]

**Review by aristath — APPROVED** [review]

**Comment by bph** [comment]
@mamaduka  Can this be added to the WordPress 5.9.x project? It should make it into 5.9.1. I don't see that I have the proper privileges  

[Forum post](https://wordpress.org/support/topic/html-tags-in-post-titles-are-gone-when-editing-existing-posts/) for reference

**Comment by Mamaduka** [comment]
@getdave, do you remember if #37866 was cherry-picked for 5.9? I don't see a label on it.

**Comment by getdave** [comment]
I don't believe it was. I started that entire endeavour post-5.9. But it's important to know. How can we check?

**Comment by bph** [comment]
Sorry for all the confusions. It was all about different [HTML in title issue. ](https://github.com/WordPress/gutenberg/issues/38668)
I don't think @Mamaduka there isn't anything to port back to 5.9.  Both prs #38145 and #37866 were just merged for 12.5 🤦

**Pull request merged**
