### PR TITLE
Reset margin for all children of flow layouts

### LINKED ISSUE #34441: Enhance block spacing gap config to also target the first block in a container
#33812 added a `blockGap` property to theme.json which enabled spacing blocks inside a container using a simpler set of rules:

```
[.container] > * + * {
	margin-top: var( --wp--style--block-gap );
	margin-bottom: 0;
}
```

In effect this simplifies margins to be _between blocks_ rather than both before and after, simplifying first-child/last-child rules and margin collapsing. 

However at the moment, the rule only targets n+1 blocks:

A fix would be to also output the following rule:

```
[.container] > * {
	margin-top: 0;
	margin-bottom: 0;
};
```

That would ensure there are no default margins interfering with the first block in a stack.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #34441

Applies the suggestion in #34441 to reset the margin for all children of flow layouts. While the margin-top is applied to all but the first one (to space the children), the reset should apply to all children.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for tackling this! It's nice to roundout the stack rules! It mostly appears to be working exactly as it should, and a group block is a good way to test it. In the following GIF I've commented out a few extra rules I added in my own theme to complement it, but it works as it should:
hey

Two things, though. On the frontend, I'm seeing this rule correctly output:

```
.wp-site-blocks > * + * {
    margin-top: var( --wp--style--block-gap );
    margin-bottom: 0;
}
```

However I'm not seeing a similar rule for the first child. I would assume it to be something like this:

```
.wp-site-blocks * {
    margin-top: 0;
    margin-bottom: 0;
}
```

In my theme, that would've targetted the header. But it doesn't seem to be there.

The other thing, the rule appears to be output for the page title in the editor:
Screenshot 2021-10-07 at 13 15 21

causing it to collapse quite a bit:
Screenshot 2021-10-07 at 13 15 27

That last bit is not a problem, it's something I can fix in an editor style if need be. But judging by the code changes it doesn't seem to have been intentional?

**Comment by youknowriad** [comment]
yeah I forgot the root level, what about now?

**Review by jasmussen — COMMENTED** [review]
Nice, works well for me now, and feels good to land since it's only the missing half of the full stack CSS equation. So I'm tempted to just give this the green check.

But I'm still not sure why it targets the site title wrapper (`.edit-post-visual-editor__post-title-wrapper > *`) — it appears to do it in my theme, where I leverage the gap property, and it's causing the title block to have zero margin:
Screenshot 2021-10-07 at 15 08 34

It's trivial for me to add that back in my editor style, but it seems like a bug it's there in the first place.

**Comment by jasmussen** [comment]
Worth noting, I'm not seeing the title margin cancelled out on either Empty Theme or TT1 blocks:
Screenshot 2021-10-07 at 15 07 35
Screenshot 2021-10-07 at 15 08 12

I haven't yet tested TwentyTwentyTwo — how does the title block look there for you?

**Comment by youknowriad** [comment]
@jasmussen It does impact the post title, that's actually the result of applying the default layout to the post title wrapper. We do this in order to apply the right "max-width" to the post title.

I'm not exactly sure how to solve that at the moment but let me try a few things

**Comment by jasmussen** [comment]
I'm personally okay with the trade-off because it isn't really a "block" yet, and it's one of those things that would be solved if it actually became a block.

The reason I mention it is because right now it behaves add it's own wrapper with a single child, followed by the post content wrapper with all it's paragraphs. Meaning there's no gap between title and post content.

**Comment by youknowriad** [comment]
Maybe a better default would be to explicitly apply the "gap" variable as a margin-top and margin-bottom of the wrapper? (I mean hard-coded in Gutenberg codebase. WDYT

**Comment by jasmussen** [comment]
If the gap is leveraged by the theme, yeah that might make sense. Basically I would ideally expect the editor (post title and a bunch of paragraphs) to look the same as a H1 followed by a bunch of paragraphs on the frontend.

**Comment by youknowriad** [comment]
I pushed a fix let me know how it feels.

**Review by jasmussen — APPROVED** [review]
Looks perfect:
Screenshot 2021-10-07 at 15 55 16
Screenshot 2021-10-07 at 15 55 20

editor gif

If you're happy with the code here, looks good to me. And it feels safe because it's behind the gap support.

**Pull request merged**
