### PR TITLE
Update colors and button labels of 'Three buttons' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Updates background colors and labels of the 'Three buttons' pattern.

Before:
Screen Shot 2020-07-09 at 15 43 37

After:
Screen Shot 2020-07-09 at 15 43 25

### CODE REVIEW

**Comment by kjellr** [comment]
Perhaps it would make sense to source these from the WordPress palette? Maybe a blue one, a dark gray one, and a black one, or something like that? I don't expect that these colors will match many folks' sites out of the box.

**Comment by enriquesanchez** [comment]
@kjellr Thanks for the feedback 🙏

I've updated the colors and also changed the button labels, let me know what you think.

Screen Shot 2020-07-09 at 18 37 14

**Comment by kjellr** [comment]
Thanks! That seems pretty good. Is there a gray we can use that's a little closer to black? It looks a little bit like a disabled button to me.

**Comment by enriquesanchez** [comment]
> Thanks! That seems pretty good. Is there a gray we can use that's a little closer to black? It looks a little bit like a disabled button to me.

Thanks, @kjellr. The next darker shade in the WP color palette is #000. I feel these two colors now feel to close:

Screen Shot 2020-07-10 at 12 59 29

If we want to stick with the WP's colors, what if we tried different shaded of blue?

Screen Shot 2020-07-10 at 12 58 14

**Comment by mapk** [comment]
I like aligning with the WP color palette. Using a primary blue and black is a great idea. What if the third color is either the red, yellow, or green? 
https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=2%3A0

**Comment by enriquesanchez** [comment]
Here are a few variations using WP colors:

Screen Shot 2020-07-10 at 16 54 38

**Comment by kjellr** [comment]
I'm a little stumped on these. The green one seems a little unusual and bright to me. Thinking cohesively about all of the block patterns, are there other colors we're using that we can pull in here instead?

**Comment by mapk** [comment]
I think 3 different colors is where this becomes too much. The one above with two colors from Enrique is visually stronger, but I think the grouping from the color is off. Try one where the "Authors" and "Publishers" are one color and "Books" are another. This way it relates the people together (authors and publishers) in the buttons, and the thing (books) as a separate button. What do you think?

**Comment by kjellr** [comment]
Yeah, pulling three colors in here is difficult, and also may not reflect what users would end up doing.

**Comment by enriquesanchez** [comment]
Agreed. Here's an example following Mark's suggestion:

Screen Shot 2020-07-13 at 13 50 41

**Comment by kjellr** [comment]
Cool, I think that works, or else just having one blue button and two black after it. 👍

**Comment by enriquesanchez** [comment]
@mapk @kjellr Thanks for all the feedback. Updated the colors and now should lool like this:

Screen Shot 2020-07-13 at 15 58 53

**Comment by mapk** [comment]
Here's a quick visual of @kjellr's suggestion for comparison sake.

switch-colors

**Review by mapk — APPROVED** [review]
I think the two blue and the third button in black looks good. Let's roll.

**Pull request merged**
