### PR TITLE
Add a brief description to the Footnotes block

### PR DESCRIPTION
**Pull request by aurooba**
## What and Why?

I noticed there was no description for the Footnotes block. This PR adds a brief one in a similar style to other Core Block descriptions: `Display footnotes added to the page.`. Happy to adjust based on feedback!

### CODE REVIEW

**Review by alexstine — COMMENTED** [review]
@aurooba This looks good. Please run `npm run docs:build` locally to build the required doc changes. Then commit those and this should be good to land pending any further feedback.

**Comment by aurooba** [comment]
@alexstine thank you for that reminder. I always forget that running `npm run build` won't run the `docs`. 😓  Docs build committed!

**Review by alexstine — COMMENTED** [review]
@aurooba Are these changes related? Don't think so.

packages/compose/README.md

Might want to check them out over latest trunk.

**Comment by alexstine** [comment]
Alright, let's see if that gets us green checks.

**Review by alexstine — APPROVED** [review]
👍

**Comment by aurooba** [comment]
@alexstine thanks! I didn't get notified of the comments on these somehow, oops. I appreciate you fixing it up! 🙏🏽

**Pull request merged**
