### PR TITLE
Blocks: Rename the paragraph block > text block

### PR DESCRIPTION
**Pull request by youknowriad**
There has been some back and forth about the name of the default block. It used to be text then paragraph. But it seems that there's been some interest in moving back to text for clarity and to gain some bytes in the post content.

Old posts should still work as normal.

### CODE REVIEW

**Review by mcsf — APPROVED** [review]
🎸

**Comment by mtias** [comment]
Let me ponder this a bit more :)

**Comment by iseulde** [comment]
So the main reason for this is clarity? How does it make things clearer?

**Comment by gziolo** [comment]
I would leave it as it is for consistence - codename matches what users see when using Paragraph and core/paragraph.

**Comment by iseulde** [comment]
Would also leave the codename. `<!-- wp:text -->` sounds like I can put multiple paragraphs in there.

**Comment by gziolo** [comment]
Should we close it? It needs a major rebase and beside we didn't agree that it brings any benefits :)

**Comment by youknowriad** [comment]
Closing for now, we can reopen later if we reach a decision

**Pull request closed without merging**
