### PR TITLE
Update the minimum required WordPress version to 5.5

### PR DESCRIPTION
**Pull request by youknowriad**
This PR updates the minimum required WordPress version to 5.5 and removes all the unnecessary hooks/filters and code that already made its way into Core.

### CODE REVIEW

**Comment by aristath** [comment]
Aren't files like `lib/class-wp-block.php` also used to backport things to wp-core?

**Comment by youknowriad** [comment]
> Aren't files like lib/class-wp-block.php also used to backport things to wp-core?

Not in my knowledge, but I'll check

**Comment by youknowriad** [comment]
@aristath it seems Core only copies automatically the files that come from packages (dynamic blocks and the parser), so I think we're good here.

**Comment by aristath** [comment]
Getting a PHP error in the site-edit screen, looks like we're using the `gutenberg_extend_settings_block_patterns` function in `lib/edit-site-page.php`

**Review by aristath — APPROVED** [review]
LGTM :+1:

**Comment by gziolo** [comment]
I was thinking about doing the same. So great to see it has happened ❤️

**Comment by mtias** [comment]
Nice cleanup

**Pull request merged**
