### PR TITLE
Refactor the Settings button CSS.

### LINKED ISSUE #14474: Settings button: Firefox and NVDA don't announce the aria-expanded state
See #1387, #1388, #1537, #1560.

Although [the original NVDA bug was fixed](https://github.com/nvaccess/nvda/issues/5247) in the 2018.4 alpha builds, [the fix was then reverted](https://github.com/nvaccess/nvda/issues/8341#issuecomment-440447733). Thus, there are still cases where Firefox and NVDA aren't able to announce a change in the `aria-expanded` state.

As explained in the NVDA issue, this is caused by a mix of reasons:
- when there's a CSS pseudo-element change, Firefox rebuilds the set of accessible properties (Firefox bug)
- NVDA thinks it's a new element and doesn't speak anything, not even a focus change (NVDA original bug)

In the case of the Settings button, when the button is _not_ toggled, there's no CSS pseudo-element. Only when the button is toggled, a CSS pseudo-element gets generated.

Testing with Firefox 65 and NVDA 2018.4.1 nothing is announced. See in the animated GIF below: 

- when landing on the button, NVDA correctly announces "Settings button expanded"
- toggling the button, nothing gets announced

settings button aria expanded NVDA

Seems to me this button styling can be implemented even without the CSS pseudo-element, which would solve the issue. Will try a quick PR.

### PR DESCRIPTION
**Pull request by afercia**
Fixes #14474.

This PR seeks to solve a Firefox / NVDA bug where changes to the Settings button `aria-expanded` state are not announced because of the CSS pseudo-element used for styling. For more details, please see the related issue #14474.

I've opted to just remove the CSS pseudo element and re-implement the styling by other means.

Worth nothing the `.is-toggled:hover` state didn't work as intended, not even on master. I had to use `!important` to override a pile of `:not()` selectors used in the icon-button. Adding one more `:not()` there didn't seem to me the best option.

The CSS should replicate the current styling. Do feel free to change it if desired, but please don't use a CSS pseudo-element 🙂 

/Cc @jasmussen 

Screenshot (for comparison, see the GIF on the issue):

Screenshot (190)

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice.

Tab, hover, focus, look good.

There's a small subtle change with the selected state that we should fix. The radius is off, and there's some shimminess around the corners. I've zoomed in these so it's visible.

Before:

before

After:

after

Two ways to fix this.

1. Remove the inset box shadow you added, and add padding: 7px to the toggled button instead. This keeps it 34px, which makes it more closely match the preview/publish buttons heights, which is why we initially made the toggled button 34px tall.

2. Remove the inset box shadow you added, and accept that it is now 36px like the other icon buttons in the menu. We might want to compensate by making the preview and publish buttons taller, to match. 

To accomlpish 2, you'd need to find the spot in the code that compiles into this:

```
.edit-post-header .components-button.editor-post-save-draft, .edit-post-header .components-button.editor-post-switch-to-draft, .edit-post-header .components-button.editor-post-preview, .edit-post-header .components-button.editor-post-publish-button, .edit-post-header .components-button.editor-post-publish-panel__toggle {
    margin: 2px;
    height: 33px;
    line-height: 32px;
    font-size: 13px;
}
```

And change the height to 36, and line-height to 35. That would make it look like this:

Screenshot 2019-03-20 at 09 50 05

But that's sort of a big change. Since we mean to revisit buttons and their focus states across WordPress, perhaps it's best to go with option 1 for now?

**Comment by afercia** [comment]
Curious that a solid box-shadow doesn't fully cover the background. Yep I'd go with padding: 7px and margin 1px.

**Comment by afercia** [comment]
Done.

**Comment by jasmussen** [comment]
A bit busy today so can't review, but putting it in a milestone because the changes look good at a code glance.

**Review by kjellr — APPROVED** [review]
Thanks, @afercia! These changes look good. It's unfortunate to have to use an `!important` override all those button `:not()`'s, but I think it's more or less fine to do it in this specific case. 

I noticed that the height of this button — and all the other toolbar buttons — are different from the height of the text buttons, but seems like that's always been the case, so we can think about that separately:

Screen Shot 2019-04-10 at 2 00 50 PM

**Pull request merged**
