### PR TITLE
Save panel - decouple Site Entity items for individual saving.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Aims to solve #29462 (alternative to #30779) This PR explores decoupling the site entity's edits and modularizing them in the save panel, allowing for individual checkbox selection of each edited item:

Screen Shot 2021-04-13 at 3 22 19 PM

Previously, any combination of these items would fall under the same checkbox with an obscure (actual site title) label and they all would have to be saved (or not saved) together:
image

## How has this been tested?

* Edit the Site Title, Site Tagline, and Site Logo blocks.
* Open the save panel.
* Verify items are separated under their own checkbox.
* Verify items save individually as expected.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by david-szabo97** [comment]
Looking good! The E2E test is failing and there is a conflicting file that needs to be resolved. After those, I'm happy to ✅

**Comment by Addison-Stavlo** [comment]
> The E2E test is failing 

Yeah, I see thats happening but Im not quite sure what that is about yet.  Handled the merge conflict and updated so will see how it goes now.

**Comment by Addison-Stavlo** [comment]
It looks like the `waitForXPath` fixed the e2e tests.  I guess after inserting a site block, we need to actually wait for the entity to be retrieved and the input to be populated before triggering `page.keyboard.type` (not a wait that seems necessary for most other blocks 😆 )

**Review by jameskoster — APPROVED** [review]
Works for me :)

**Review by carolinan — APPROVED** [review]
Not a code review but this is working well for me when I test.

**Review by david-szabo97 — APPROVED** [review]
🚢 🚢 🚢 🚢

**Pull request merged**
