### PR TITLE
Rename "Insert" to "Add"

### PR DESCRIPTION
**Pull request by rileybrook**
## Description
Intent of PR is a copy change. To rename "Insert" to "Add" as discussed and agreed upon in #2975
- This change only affects copy seen by users. 
- No changes have been made to functions, class names, the component named "Inserter" nor any developer documentation. Those changes would warrant separate, future issues as pointed out by @jasmussen in #2975 

## Screenshot Examples of Changes

Before
screen shot 2018-01-10 at 10 34 37 am

After
screen shot 2018-01-10 at 6 10 53 pm

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by jasmussen** [comment]
Wohoo! Thanks so much for doing this! This is all looking good to me. Only point in question is whether we need to change the "Insert" term to "Add" for the table block — I'm fine with it, but that would be the only one where it sort of feels more sensible to use the old term. @karmatosed any thoughts?

Otherwise, 👍 👍  from me, and thanks again.

By the way, did the fork/branch instructions work as intended? Could you describe the steps you took so we can update the contributor instructions?

**Comment by karmatosed** [comment]
👍 from me! Thank you for doing this @rileybrook - excited to get it in!

**Comment by rileybrook** [comment]
Thanks to both of you @karmatosed and @jasmussen. The steps taken below worked as intended.

### Workflow
- Fork Gutenberg repository to personal GitHub account
- Clone forked repo
- Create new branch
- Make code changes
- Commit code changes within newly created branch
- Publish branch
- Submit Pull Request

**Comment by rileybrook** [comment]
Thanks to both of you @karmatosed and @jasmussen. The steps taken below worked as intended.

### Workflow
- Fork Gutenberg repository to personal GitHub account
- Clone forked repo
- Create new branch
- Make code changes
- Commit code changes within newly created branch
- Publish branch
- Submit Pull Request

**Pull request merged**
