### PR TITLE
URL: Use test data from web-platform-tests for isURL spec conformance

### LINKED ISSUE #20534: URL: Use test data from web-platform-tests for isURL spec conformance
The `@wordpress/url` implementation of `isURL` is [documented](https://github.com/WordPress/gutenberg/blob/master/packages/url/README.md#isURL) as to conform to the [URL Standard](https://url.spec.whatwg.org/) definition of a [valid URL string](https://url.spec.whatwg.org/#valid-url-string). There are [test cases](https://github.com/WordPress/gutenberg/blob/251bab458ee5c91d43d44a355b1388044233e9bf/packages/url/src/test/index.test.js#L32-L61) to verify this behavior, but they are written ad hoc based on our own understanding of what should and should not be considered a valid URL.

However, there is a canonical resource for test data associated with web standards:

https://github.com/web-platform-tests/wpt

Specifically, there is test data provided which can be used to assert whether a given input should be considered valid:

https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json

Per https://github.com/WordPress/gutenberg/pull/20435#issuecomment-592538369, our current alignment of "valid" only checks whether a parse would fail. In the above data set, this is reflected as the `"failure": true` object value.

**Task:** Use `urltestdata.json` from the above repository as reference data to use in our own `isURL` tests.

**Implementation Notes:**

- Note that the URL standard is a living standard, and as such may change over time. Additionally, the web-platform-tests project may seek to add or change the test cases. Based on this, we should anticipate that the test data may need to update to use a more recent copy.
- We could choose to load the file over the network by referencing the repository URL, but we should be mindful to avoid inadvertent test failures caused by network instability.
- We should not want the tests to suddenly fail, thus the test data should be pinned to a specific version that we can update as needed.
- In mind of all of the above, we probably want a local copy of `urltestdata.json`, optionally reduced to the minimal set of properties, since we only need `input` and `failure` properties for our purposes. For easy updates, we could consider writing an ad hoc script within the `url` package whose implementation would download and transform the latest version.

### PR DESCRIPTION
**Pull request by aduth**
Closes #20534

This pull request seeks to enhance tests for `@wordpress/url` `isURL` to conform to those defined by the [Web Platform Tests project](https://github.com/web-platform-tests/wpt). As outlined in #20534, it includes a script to download and transform the [URL test data](https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json), which is then loaded by the `@wordpress/url` unit tests as fixture data for the `isURL` tests.

You can run the script directly:

```
node packages/url/scripts/download-wpt-data.js
```

**Testing Instructions:**

Ensure unit tests pass:

```
npm run test-unit packages/url/src/test/index.test.js
```

### CODE REVIEW

**Comment by aduth** [comment]
@SergioEstevao Note the failing native tests. Is this something you might be able to take on? (i.e. fixing the implementation)

```
FAIL ../../packages/url/src/test/index.native.js
  isURL
    ✓ https://test:@test
    ✓ https://:@test
    ✕ non-special://test:@test/x (2ms)
    ✕ non-special://:@test/x (1ms)
    ✕ lolscheme:x x#x x
    ✓ file://example:1/ (1ms)
    ✓ file://example:test/
    ✕ file://example%/
    ✓ file://[example]/ (1ms)
    ✓ http://example.com/././foo
    ✓ http://example.com/./.foo
    ✓ http://example.com/foo/.
    ✓ http://example.com/foo/./ (1ms)
    ✓ http://example.com/foo/bar/..
    ✓ http://example.com/foo/bar/../
    ✓ http://example.com/foo/..bar
    ✓ http://example.com/foo/bar/../ton (4ms)
    ✓ http://example.com/foo/bar/../ton/../../a
    ✓ http://example.com/foo/../../..
    ✓ http://example.com/foo/../../../ton
    ✓ http://example.com/foo/%2e
    ✓ http://example.com/foo/%2e%2
    ✓ http://example.com/foo/%2e./%2e%2e/.%2e/%2e.bar (1ms)
    ✓ http://example.com////../..
    ✓ http://example.com/foo/bar//../..
    ✓ http://example.com/foo/bar//..
    ✓ http://example.com/foo
    ✓ http://example.com/%20foo (1ms)
    ✓ http://example.com/foo% (1ms)
    ✓ http://example.com/foo%2
    ✓ http://example.com/foo%2zbar
    ✕ http://example.com/foo%2Â©zbar (1ms)
    ✓ http://example.com/foo%41%7a (1ms)
    ✕ http://example.com/foo	%91
    ✓ http://example.com/foo%00%51 (1ms)
    ✕ http://example.com/(%28:%3A%29) (1ms)
    ✓ http://example.com/%3A%3a%3C%3c
    ✕ http://example.com/foo	bar (1ms)
    ✓ http://example.com\\foo\\bar
    ✓ http://example.com/%7Ffp3%3Eju%3Dduvgw%3Dd (1ms)
    ✓ http://example.com/@asdf%40
    ✕ http://example.com/你好你好
    ✕ http://example.com/‥/foo (1ms)
    ✕ http://example.com/﻿/foo
    ✕ http://example.com/‮/foo/‭/bar (1ms)
    ✓ http://www.google.com/foo?bar=baz#
    ✕ http://www.google.com/foo?bar=baz# »
    ✕ data:test# » (1ms)
    ✓ http://www.google.com
    ✓ http://192.0x00A80001
    ✓ http://www/foo%2Ehtml
    ✓ http://www/foo/%2E/html
    ✓ http://user:pass@/
    ✕ http://%25DOMAIN:foobar@foodomain.com/
    ✕ http:\\www.google.com\foo
    ✓ http://foo:80/ (1ms)
    ✓ http://foo:81/
    ✓ httpa://foo:80/
    ✓ http://foo:-80/
    ✓ https://foo:443/
    ✓ https://foo:80/
    ✓ ftp://foo:21/ (1ms)
    ✓ ftp://foo:80/
    ✓ gopher://foo:70/
    ✓ gopher://foo:443/
    ✕ ws://foo:80/ (2ms)
    ✕ ws://foo:81/
    ✕ ws://foo:443/
    ✕ ws://foo:815/ (1ms)
    ✓ wss://foo:80/
    ✓ wss://foo:81/ (1ms)
    ✓ wss://foo:443/
    ✓ wss://foo:815/
    ✓ http:/example.com/
    ✓ ftp:/example.com/
    ✓ https:/example.com/
    ✕ madeupscheme:/example.com/ (1ms)
    ✓ file:/example.com/
    ✓ ftps:/example.com/
    ✓ gopher:/example.com/
    ✕ ws:/example.com/ (1ms)
    ✓ wss:/example.com/
    ✓ data:/example.com/
    ✕ javascript:/example.com/
    ✓ mailto:/example.com/ (1ms)
    ✓ http:example.com/
    ✓ ftp:example.com/
    ✓ https:example.com/
    ✕ madeupscheme:example.com/
    ✓ ftps:example.com/ (1ms)
    ✓ gopher:example.com/
    ✕ ws:example.com/
    ✓ wss:example.com/
    ✓ data:example.com/
    ✕ javascript:example.com/ (1ms)
    ✓ mailto:example.com/
    ✓ http:@www.example.com
    ✕ http:/@www.example.com (1ms)
    ✕ http://@www.example.com
    ✓ http:a:b@www.example.com
    ✓ http:/a:b@www.example.com
    ✓ http://a:b@www.example.com (1ms)
    ✕ http://@pple.com
    ✓ http::b@www.example.com
    ✓ http:/:b@www.example.com
    ✓ http://:b@www.example.com
    ✓ http:/:@/www.example.com (1ms)
    ✕ http://user@/www.example.com
    ✓ http:@/www.example.com
    ✓ http:/@/www.example.com
    ✓ http://@/www.example.com (1ms)
    ✓ https:@/www.example.com
    ✓ http:a:b@/www.example.com
    ✓ http:/a:b@/www.example.com
    ✓ http://a:b@/www.example.com
    ✓ http::@/www.example.com
    ✓ http:a:@www.example.com (1ms)
    ✓ http:/a:@www.example.com
    ✓ http://a:@www.example.com
    ✓ http://www.@pple.com
    ✓ http:@:www.example.com
    ✓ http:/@:www.example.com
    ✓ http://@:www.example.com
    ✓ http://:@www.example.com (1ms)
 
    ✓ https://�
    ✓ https://%EF%BF%BD
    ✕ https://x/�?�#� (1ms)
    ✕ https://faß.ExAmPlE/
    ✕ sc://faß.ExAmPlE/ (1ms)
    ✓ https://x x:12
    ✓ http://./
    ✓ http://../
    ✓ http://0..0x300/
    ✓ http://[www.google.com]/
    ✕ http://host/?'
    ✕ notspecial://host/?'
    ✓ about:/../
    ✓ data:/../ (1ms)
    ✕ javascript:/../
    ✓ mailto:/../
    ✕ sc://ñ.test/
    ✕ sc://!"$&'()*+,-.;<=>^_`{|}~/ (1ms)
    ✓ sc:///
    ✓ sc:// /
    ✕ sc://%/
    ✓ sc://@/ (1ms)
    ✓ sc://te@s:t@/
    ✓ sc://:/
    ✓ sc://:12/
    ✓ sc://[/
    ✓ sc://\/
    ✓ sc://]/
    ✕ sc:\../ (7ms)
    ✓ sc::a@example.net
    ✕ wow:%NBD
    ✕ wow:%1G (1ms)
    ✕ wow:￿
    ✕ ftp://example.com%80/ (1ms)
    ✕ ftp://example.com%A0/
    ✕ https://example.com%80/ (1ms)
    ✕ https://example.com%A0/
    ✕ ftp://%e2%98%83
    ✕ https://%e2%98%83 (1ms)
    ✓ http://127.0.0.1:10100/relative_import.html
    ✓ http://facebook.com/?foo=%7B%22abc%22
    ✓ https://localhost:3000/jqueryui@1.2.3
    ✕ h	t
p://h	o
t:9	0
0/p	a
h?q	u
ry#f	r
g (1ms)
    ✕ http://foo.bar/baz?qux#fobar
    ✕ http://foo.bar/baz?qux#foo"bar
    ✕ http://foo.bar/baz?qux#foo<bar (1ms)
    ✕ http://foo.bar/baz?qux#foo>bar
    ✕ http://foo.bar/baz?qux#foo`bar (1ms)
    ✓ https://0x.0x.0
    ✕ https://0x100000000/test
    ✕ https://256.0.0.1/test (1ms)
    ✓ file:///C%3A/
    ✓ file:///C%7C/
    ✕ file:\\// (1ms)
    ✕ file:\\\\
    ✕ file:\\\\?fox
    ✕ file:\\\\#guppy (1ms)
    ✓ file://spider///
    ✕ file:\\localhost//
    ✓ file:///localhost//cat (1ms)
    ✕ file://\/localhost//cat
    ✓ file://localhost//a//../..//
    ✕ file://example.net/C:/
    ✕ file://1.2.3.4/C:/
    ✕ file://[1::8]/C:/
    ✕ file:/C|/ (1ms)
    ✕ file://C|/
    ✕ file: (1ms)
    ✕ file:?q=v
    ✕ file:#frag (1ms)
    ✓ https://[0::0::0]
    ✓ https://[0:.0]
    ✓ https://[0:0:]
    ✓ https://[0:1:2:3:4:5:6:7.0.0.0.1] (1ms)
    ✓ https://[0:1.00.0.0.0]
    ✓ https://[0:1.290.0.0.0]
    ✓ https://[0:1.23.23]
    ✓ http://?
    ✓ http://#
    ✕ sc://ñ (1ms)
    ✕ sc://ñ?x
    ✕ sc://ñ#x (1ms)
    ✕ sc://?
    ✕ sc://#
    ✓ tftp://foobar.com/someconfig;mode=netascii (1ms)
    ✓ telnet://user:pass@foobar.com:23/
    ✕ ut2004://10.10.10.10:7777/Index.ut2
    ✓ redis://foo:bar@somehost:6379/0?baz=bam&qux=baz
    ✓ rsync://foo@host:911/sup
    ✓ git://github.com/foo/bar.git (1ms)
    ✓ irc://myserver.com:6999/channel?passwd
    ✓ dns://fw.example.org:9999/foo.bar.org?type=TXT
    ✕ ldap://localhost:389/ou=People,o=JNDITutorial
    ✕ git+https://github.com/foo/bar (1ms)
    ✕ urn:ietf:rfc:2648
    ✕ tag:joe@example.org,2001:foo/bar (1ms)
    ✕ non-special://%E2%80%A0/
    ✕ non-special://H%4fSt/path (1ms)
    ✕ non-special://[1:2:0:0:5:0:0:0]/
    ✕ non-special://[1:2:0:0:0:0:0:3]/
    ✕ non-special://[1:2::3]:80/ (1ms)
    ✓ non-special://[:80/
    ✕ blob:https://example.com:443/
    ✓ blob:d3958f5c-0777-0845-9dcf-2cb28783acaf
    ✓ http://0177.0.0.0189 (1ms)
    ✓ http://0x7f.0.0.0x7g
    ✓ http://0X7F.0.0.0X7G
    ✓ http://[::127.0.0.0.1]
    ✕ http://[0:1:0:1:0:1:0:1]
    ✕ http://[1:0:1:0:1:0:1:0] (1ms)
    ✕ http://example.org/test?"
    ✓ http://example.org/test?#
    ✕ http://example.org/test?< (1ms)
    ✕ http://example.org/test?>
    ✕ http://example.org/test?⌣
    ✓ http://example.org/test?%23%23 (1ms)
    ✓ http://example.org/test?%GH
    ✕ http://example.org/test?a#%EF
    ✕ http://example.org/test?a#%GH (1ms)
    ✓ a
    ✓ a/ (1ms)
    ✓ a//
    ✕ http://example.org/test?a#bc
```

**Comment by SergioEstevao** [comment]
@aduth I had a look and tried to implement a solution based on a REGEX, but I got to the conclusion that I was almost impossible to implement one that validates correctly all the cases on the test set.

I was thinking couldn't we just import the full [whatwg-url ](https://github.com/jsdom/whatwg-url) package in RN and use the URL class as we do in the web?

@etoledom did you try to do that on your previous implementation?

**Comment by aduth** [comment]
> I was thinking couldn't we just import the full [whatwg-url ](https://github.com/jsdom/whatwg-url) package in RN and use the URL class as we do in the web?

I had meant to circle back here before your comment. Coincidentally, I was going to suggest exactly the same. 

There was some discussion in #20172 about this. Apparently there were some issues in Android, but it's unclear if those were caused specifically by `react-native-url-polyfill`, or the `whatwg-url` package it uses under the hood.

**Comment by aduth** [comment]
Based on @charpeni's comment at https://github.com/WordPress/gutenberg/pull/20172#issuecomment-596507662, I tried again to reincorporate `react-native-url-polyfill`. I've not tested this with the actual emulators (like in https://github.com/WordPress/gutenberg/pull/20172#issuecomment-585612552), but at least the tests seem to run okay. The results are slightly better than they were previously. The key failure now is with unicode support, which appears to be intentionally omitted from `react-native-url-polyfill`. I'm not entirely clear yet if this is something we'd be okay with. If it is, we'd need to expand upon the [proposed exception logic](https://github.com/WordPress/gutenberg/blob/d372189684d3008bb865d354fa373b2bfa83d211/packages/url/scripts/download-wpt-data.js#L76-L83) to exclude these test cases.

**Comment by SergioEstevao** [comment]
@aduth I will retry this on the simulators and see if all builds correctly now.

I also think it's a good idea to add the unicode test to the exception lists for now.

**Comment by aduth** [comment]
Some of the failures are a bit peculiar.

For example:

```
  ● isURL › ftp://example.com%80/
    expect(received).toBe(expected) // Object.is equality
    Expected: false
    Received: true
      35 | 		'%s',
      36 | 		( input, isFailure ) => {
    > 37 | 			expect( isURL( input ) ).toBe( ! isFailure );
         | 			                         ^
      38 | 		}
      39 | 	);
      40 | } );
      at toBe (packages/url/src/test/index.test.js:37:29)
```

I guess it's based on the forked differences of `whatwg-url-without-unicode`:

https://github.com/charpeni/whatwg-url/commit/6bf57ad8866a87f8596b507e322672e2555ad985

I observe in the regular `whatwg-url` that it fails here, as a result of `domainToASCII`:

https://github.com/jsdom/whatwg-url/blob/aa7d237ec8dc6294314a0dfb47a4b26c7d523395/src/url-state-machine.js#L380-L381

image

I guess it may technically fall under the scope of "unicode" validation omitted by the fork?

Aside: Does bundle size matter as much in React Native to warrant worrying so much over the ~100kb difference between `whatwg-url-without-unicode` and `whatwg-url` ?

Anyways, I guess I can make add some exception logic for now, since these are edge cases, even if technically valid. But the closer we can align these, the better.

**Comment by charpeni** [comment]
Tests related to Unicode support were skipped in https://github.com/charpeni/whatwg-url/commit/473d32f560d7ecfcd1e7844d92ac2856417f3768. Tests are still running on CircleCI, and [react-native-url-polyfill does have a Detox setup](https://github.com/charpeni/react-native-url-polyfill/tree/master/detox) to run the polyfill on an iOS simulator.

> Aside: Does bundle size matter as much in React Native to warrant worrying so much over the ~100kb difference between whatwg-url-without-unicode and whatwg-url ?

A difference of ~341 KB*. 😬 

Some context around this, It's worrying enough that it couldn't be included in the core of React Native, even with ~41 KB. Adding ~341 KB _(+51%)_ to the bundle seems excessive to handle Unicode which are like 1% of URL use cases.

**Comment by aduth** [comment]
> A difference of ~341 KB*. 😬

Ah, thanks for correcting. I think I had the number stuck in my mind from the [133kb of `mappingTable.json`](https://unpkg.com/browse/tr46@2.0.2/lib/mappingTable.json), which is fair to say is not representative of the full difference.

Thanks for the extra context as well. I admit I have a tendency to obsess over the edge cases, but I think it's a case to consider being pragmatic, given the circumstances.

**Comment by SergioEstevao** [comment]
@aduth I created a [PR on  GB-mobile project](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1996) to add the polyfill library to the project again. 

It looks it's building correctly now, and all tests are green. Just waiting for @etoledom  to double-check the build issues.

**Review by SergioEstevao — APPROVED** [review]
GB mobile is working correctly with these changes now, so it's a :shipit: for me!

**Pull request merged**
