### PR TITLE
Multiple blocks: Make the added padding when there is a background color optional

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Some blocks add default padding when the background color is enabled. This can be unexpected for users, as expressed in https://github.com/WordPress/gutenberg/issues/36586 and https://github.com/WordPress/gutenberg/issues/30725

It affects:
- Paragraph
- Heading
- Columns
- List
- Preformatted

By moving the CSS from the blocks `style.scss` to `theme.scss`, this style is part of the `wp-block-styles` theme support, and theme developers can decide if they want to use this style or not.

This pull request is a continuation of a style change already made for the group and template part blocks.
**This change must be considered carefully because it is a visible change for existing websites.**
The change gives developers and users more control, which may outweigh the initial visual change.

All the affected blocks have padding support, except for preformatted ([PR](https://github.com/WordPress/gutenberg/pull/45196)).
Users can add the padding back if the theme has support for padding.
- Themes without theme.json enable padding through `add_theme_support( 'custom-spacing' ).`
- Themes with theme.json enable padding through appearanceTools or settings.spacing.padding.

The default padding can be added back for all theme types with `add_theme_support( 'wp-block-styles' )`

## Testing Instructions

Sample block markup for testing
```<!--wp:paragraph {"backgroundColor":"pale-cyan-blue"} -->
<p class="has-pale-cyan-blue-background-color has-background">Paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"backgroundColor":"pale-cyan-blue"} -->
<h2 class="wp-block-heading has-pale-cyan-blue-background-color has-background">Heading, H2</h2>
<!-- /wp:heading -->

<!-- wp:columns {"backgroundColor":"pale-cyan-blue"} -->
<div class="wp-block-columns has-pale-cyan-blue-background-color has-background"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Column 1</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Column 2</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:list {"backgroundColor":"pale-cyan-blue"} -->
<ul class="has-pale-cyan-blue-background-color has-background"><!-- wp:list-item -->
<li>Paragraph</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Heading</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Columns</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Preformatted</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:preformatted {"backgroundColor":"pale-cyan-blue"} -->
<pre class="wp-block-preformatted has-pale-cyan-blue-background-color has-background">Preformatted</pre>
<!-- /wp:preformatted -->
```

## Screenshots or screencast 

Classic theme (with no custom CSS)
Editor, before:
classic theme, editor, before
Editor, after:
classic theme, editor, after

Front, before:
classic theme, front, before
Front, after:
classic theme, front, after

Twenty Twenty-Three
Editor, before:
TT3, editor, before
Editor, after:
TT3, editor, after

Front, before:
Screenshot 2023-05-20 at 14 45 42
Front, after:
Screenshot 2023-05-20 at 14 49 27

### CODE REVIEW

**Comment by carolinan** [comment]
There is still something affecting the padding of the heading block with the background color. Some styles may be from Core or were not built properly in my test.

**Comment by carolinan** [comment]
@WordPress/block-themers What are your thoughts about making the padding which is added when a block has a background color optional, through `add_theme_support( 'wp-block-styles' );`.

I think the default padding is especially bad on the heading block.

**Comment by philhoyt** [comment]
While I see the benefit of additional padding from an intrinsic design philosophy, providing a more "designed" experience by default, The additional padding often causes large inconsistencies between elements and makes creating complicated layouts more difficult. I hope to see this merged.

**Comment by fabiankaegy** [comment]
I agree with the statement from @philhoyt. 

It would be useful to be able to customize / configure the default spacing that gets applied to an element when a background is added. Kind of with more context aware global styles. 

But in it's current form the default padding that is arbitrary and doesn't abide by the spacing presets / design tokens is always a hurdle and causes a lot of issues.

**Comment by mikachan** [comment]
I'm in favour of making the padding optional through `add_theme_support( 'wp-block-styles' )` 👍

**Comment by paaljoachim** [comment]
It is great to see this PR on it's way. There is a jump that happens when adding or removing background color which in a sense feels like a bug. Automatically adding or removing padding based on adding/removing background color just seems weird. When a user adds a background color they can see the result and then choose to add the padding they need.
It would be very nice to get this resolved soon. Thank you Carolina for working on this PR!

**Comment by paaljoachim** [comment]
Any additional thoughts?
@WordPress/gutenberg-design

**Comment by ndiego** [comment]
> I'm in favour of making the padding optional through add_theme_support( 'wp-block-styles' ) 👍

I concur.

**Comment by jameskoster** [comment]
Seems reasonable to me 👍

**Comment by scruffian** [comment]
Another option that I think it worth considering is to add the padding as a setting at the same time as adding the background color. That way it gets set, which is probably what most users want, but it can be removed using the padding tool, if its not what you need.

**Comment by MaggieCabrera** [comment]
> Another option that I think it worth considering is to add the padding as a setting at the same time as adding the background color. That way it gets set, which is probably what most users want, but it can be removed using the padding tool, if its not what you need.

This seems like the most reasonable option, but maybe not the easiest

**Comment by paaljoachim** [comment]
Let's see if I get this correct.... I initially gave it a thumbs up but need to go through the logic.

> Another option that I think it worth considering is to add the padding as a setting at the same time as adding the background color. That way it gets set, which is probably what most users want, but it can be removed using the padding tool, if its not what you need.

A user adds a background color and padding are automatically added. User wonders why padding is added and if they happen to look in the sidebar settings they will see that padding values have been added. Based on this I would likely report a bug with the title: Adding background color padding is automatically added.
Background color and padding do not have a natural association with each other.

It is better to have the flow like so.
User adds a background color. Notices that there is no padding and that only the block area contains the background color. Perhaps that is the effect they need? We do not know. If not then they can open the sidebar settings Dimension controls and add in padding. Perhaps even the Dimensions control for padding can be seen but that it contains no padding and the user can then add the padding this is needed.

Going through the above flow I would then suggest this:
As a user adds background color have Dimension controls padding become visible (if they currently are hidden) in the sidebar settings. So that the user can see the padding controls they can add padding values to make the background color area bigger. So the only change I would make is have the padding controls become obvious/visible in the sidebar settings but the controls should not show any value. It is up to the user to add these in.

**Comment by scruffian** [comment]
Since we already add a padding when a background color is added it seems reasonable to assume that this is the behaviour most users would expect.

**Comment by carolinan** [comment]
It is tricky. The suggestion is better than what we have now without the PR.
But it still means that anyone who doesn't want the padding has to remove it manually every time.
Maybe there needs to be a second theme.json setting / theme support for  spacing > BackgroundPadding (true or false).

**Comment by paaljoachim** [comment]
When an user adds one behavior it is not beneficial for Gutenberg to add another behavior not directly added by the user themselves. We can not assume what the user wants. It is up to us to make the Gutenberg experience as smooth as possible based on the actions the user decides to take.

When an additional behavior is added not directly controlled by the user then Gutenberg needs to alert the user. Letting them know that something else also happened even though the user did not add it themselves.

**Comment by Ren2049** [comment]
I think the most confusing part of the auto padding isn't even related to the added padding itself, but that there are no indicators of the amount of padding on the padding sliders because they dont show the actual state. 

Right now you have to engage with the slider at zero wiggling it a bit to apply your own padding. A lot of people won't even bother trying to engage with the sliders if they're showing zero thinking that this isn't the place to change it. 

The lack of state on sliders is a severe UX glitch which should have priority over this one because it drags other experiences down which may even be good ideas.

Also how about a toggle like global content width but for a global padding value?

**Comment by carolinan** [comment]
No options show the value from theme.json and I agree this is a problem.

**Comment by jameskoster** [comment]
> I think the most confusing part of the auto padding isn't even related to the added padding itself, but that there are no indicators of the amount of padding on the padding sliders because they dont show the actual state.

The range controls are most egregious, but this is a pretty widespread issue: https://github.com/WordPress/gutenberg/issues/43082

**Comment by Ren2049** [comment]
Wow it seems to be a big problem @jameskoster

If it can't get fixed soon I think a introductory design guide could be helpful where users are made aware that they can overwrite stuff despite the handles/sliders showing no state. E.g. a small link in the right sidebar "learn how to design with blocks" or something. Users shouldn't be expected to figure it out themselves.

Maybe start the guide right away saying that it's still a work in progress and making users aware of the things that don't work yet perfectly right away. This document could evolve over time as things progress.

**Pull request closed without merging**
