### PR TITLE
Update the Gutenberg plugin to require at least the WP 6.0 version

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

WordPress 6.1 is out for a few weeks now, so it's time to update the minimum required WP version to 6.0 for the Gutenberg plugin.

## How?

The process I used is to remove the lin/wordpress-6.0 folder and fix any errors. I've noticed that the Gallery block v2 should now always be considered enabled. (Please correct me if I'm wrong @glendaviesnz @ramonjd @geriux) So I went ahead and remove all code related to this check (including on native).

There are some APIs that are marked for removal in WP 6.2 so we can remove them now from the Gutenberg plugin, but I left these for a separate PR.

## Testing Instructions

1- Run Gutenberg on top of 6.1
2- Run Gutenberg on top of trunk

### CODE REVIEW

**Comment by glendaviesnz** [comment]
>  I've noticed that the Gallery block v2 should now always be considered enabled

Yes, that should be correct from the web perspective, will let @geriux confirm from mobile side. With the removal of the v1 code the edit-wrapper was redundant, so have [removed that](https://github.com/WordPress/gutenberg/pull/46102/commits/638b707fbb995a347a81243df09cba59ae154a99).

**Comment by fluiddot** [comment]
> I've noticed that the Gallery block v2 should now always be considered enabled

We checked the adoption metrics of V2 vs V1 in native and seems like we still have a meaningful ratio of users using V1, mainly in self-hosted sites. This means that if we remove Gallery block V1, those users won't be able to edit the Gallery block in the app.

On the other hand, I'm concerned that it will take a long time until we get a high adoption of Gallery V2, and I understand that we'd like to remove V1, especially now that we have three WP versions out that support V2 (i.e. 5.9, 6.0 and 6.1).

One option we're discussing is to render the Gallery block unsupported in the native version if it's V1. However, for this, we'd need to work on that implementation before removing the Gallery block V1 code. @youknowriad would it be possible to delay merging this PR until we provide a workaround for the native version? Thanks!

cc @geriux

**Comment by geriux** [comment]
Hey there 👋 we are ok with removing the V1 of the Gallery block 👍 but we are currently looking into a workaround for users that haven't updated yet which is still a bit high for us to remove all of it without informing the users or breaking the user experience.

**Comment by youknowriad** [comment]
@geriux Since in the web, the Gutenberg plugin now only works with Gallery V2, can we keep the v1 code for the mobile and ship the current PR with the web changes. In other words, would it be possible to revert all my "native" file changes here and ship?

**Comment by geriux** [comment]
> In other words, would it be possible to revert all my "native" file changes here and ship?

Would that revert include the changes in the Gallery files that are not "native" but are shared with mobile?

**Comment by youknowriad** [comment]
> Would that revert include the changes in the Gallery files that are not "native" but are shared with mobile?

It seems like these include the whole gallery block changes (almost), this makes the revert less tempting to me. I guess it's better to wait here until you all come up with the right workaround in that case.

**Comment by geriux** [comment]
> It seems like these include the whole gallery block changes (almost), this makes the revert less tempting to me. I guess it's better to wait here until you all come up with the right workaround in that case.

Sounds good, we will need to keep all of the `.swift` `.java` code that reference to `galleryWithImageBlocks` though since we will depend on that flag, as well as in the `.js` files where we pass this flag to the editor.

As for the `__unstableGalleryWithImageBlocks` flag in [this code](https://github.com/WordPress/gutenberg/pull/46102/files#diff-e6bd94e1847aea4b70a6cc1ac9b2471dd3d882f6cbf1ab51438e23b02ca5194fL142), we'll move it to the mobile block editor settings endpoint 👍

**Comment by youknowriad** [comment]
@geriux would you be able to make the changes in this PR when you figure out how to handle this?

**Comment by geriux** [comment]
> @geriux would you be able to make the changes in this PR when you figure out how to handle this?

Sure! Will do 👍

**Comment by youknowriad** [comment]
Ok, so to avoid blocking this PR further, I've decided to remove all the gallery block related changes. It should be now ready to go.

**Comment by geriux** [comment]
> Ok, so to avoid blocking this PR further, I've decided to remove all the gallery block related changes. It should be now ready to go.

Sounds good! Could I make a quick change to have[ this flag](https://github.com/WordPress/gutenberg/pull/46102/files#diff-e6bd94e1847aea4b70a6cc1ac9b2471dd3d882f6cbf1ab51438e23b02ca5194fL142) in the mobile [block editor settings](https://github.com/WordPress/gutenberg/blob/trunk/lib/experimental/block-editor-settings-mobile.php#L29-L33) endpoint?

**Comment by youknowriad** [comment]
@geriux Isn't that already set in the WP provided endpoint?

**Comment by geriux** [comment]
> @geriux Isn't that already set in the WP provided endpoint?

I'm not sure, which endpoint is that?

**Comment by youknowriad** [comment]
@geriux I mean that this is already set on WordPress core directly https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-includes/block-editor.php#L233

**Comment by geriux** [comment]
> @geriux I mean that this is already set on WordPress core directly https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-includes/block-editor.php#L233

Oh! I see! Sorry I missed that, all good then! Thank you!

**Review by ellatrix — APPROVED** [review]

**Pull request merged**
