### PR TITLE
[Android] Fix Gboard enter detection in EnterPressedWatcher

### LINKED ISSUE #3316: Enter detection fails in EnterPressedWatcher for Gboard keyboard
## Description

The mechanism to detect whether the `[ENTER]` key was pressed is not reliable for users with the Gboard keyboard. The Gboard keyboard exhibits some unusual behavior regarding the `TextWatcher` interface methods, which are breaking some assumptions in the logic we are using for key detection. This manifests as various bugs, and is likely not limited to the `[ENTER]` key (e.g. I believe `[BACKSPACE]` detection may be affected in a similar manner).

### Example bug

On a Pixel 3a (physical device) with the Gboard keyboard:

1. Create a new post
2. Add a paragraph block
3. Type a word (e.g. "Hello") without a space
  * Observe that the keyboard suggestions
  * Observe that the word is underlined
4. Press `[ENTER]`
5. Observe that the block does not split - instead, a newline is added to the paragraph block

#### Expected

The block should split and form a new paragraph block below.

## Deeper details

The `EnterPressedWatcher` class works by implementing the `TextWatcher` interface, overriding the following methods:

* `beforeTextChanged`
* `onTextChanged`
* `afterTextChanged`

and tracking state during a user's manipulation of the `EditText` input. These methods allow us to observe the mutations to the `CharSequence`, and to provide a means to reconcile what has changed, and respond in some way after evaluating the changes at each stage of the update. Typically, these changes are fairly straightforward, and these methods are invoked with predictable index boundaries for a given text input operation, but here is where Gboard exhibits some unusual behavior.

Here is a table describing some observations that surprised me:

Consider a scenario where we have the input with text `Hello worl`, and we then press `d` on the keyboard:

Comparison |`TextWatcher` Interface Method | `text: CharSequence` | `start: Int` | `count: Int` | `after: Int` | `before: Int`
-|-|-|-|-|-|-
Expected | `beforeTextChanged` | "Hello worl" | 10 | 0 | 1 | N/A
Actual | `beforeTextChanged`| "Hello worl" | 6 | 4 | 5 | N/A
Expected | `onTextChanged` | "Hello world" | 10 | 1 | N/A | 0
Actual | `onTextChanged`| "Hello world" | 6 | 5 | N/A | 4

The surprising part is that some characters from the original text are being replaced when nothing was selected (just a normal caret at the end of the input). It seems instead that Gboard is actually replacing the last 4 characters with those same 4 characters _plus_ the typed text. It is even possible to notice a small underline style applied to the characters that will be included in the replacement. Before this, I would have only expected `beforeTextChanged` to be called with a `count` > 0 if there was a selection prior to the new characters being typed (or if characters were being deleted).

Note that the result is the same (and that the sum is still 11 for `start + after` and `start + count` for `beforeTextChanged` and `onTextChanged` respectively).

Interestingly, after selecting one of the suggestions offered by Gboard, the `onEnter` behavior was works normally (and the underlined text goes away).

### PR DESCRIPTION
**Pull request by mkevins**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3316

## Description

This PR addresses the Gboard issue by searching the `CharSequence` for a newline, instead of only checking the first character of the text in `onTextChanged`. If it finds a newline, its offset is then used for further processing. If the newline is the first character, the offset will be `0`, so previous (non-gboard) behavior will be the same as before. This is a more general solution.

## How has this been tested?

This should be tested both with and without gboard keyboard via [this suite of writing flow tests](https://github.com/WordPress/gutenberg/pull/30368#issuecomment-813975280).

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
Thanks for the draft fix @mkevins ! I got curious about the fix and looked at the code.

We've indeed have noticed in the past that GBoard's autosuggestion system performs these "weird" text chance events where a single char is is actually added after the whole word is first removed from the text buffer.

I'm not yet sure about trying to fix the issue by essentially mimicking the logic GBoard uses. I feel it's a bit complex and prone to breakages if GBoard updates it's logic.

I took a stab at it and tried a different idea: to just _search_ for the Enter character instead of using the change event's positioning variables. Check out [the gist here](https://gist.github.com/hypest/5b0111fa04b63328559b262ea741881d) for a diff against the production code, where I basically rely on `newTextCopy.lastIndexOf(Constants.NEWLINE)` to find the char. Looks like it fixes the issue for me using the GBoard. This is a crude first attempt to see if it works. I'm thinking we should actually search for multiple occurances of the char (think: pasting many paragraphs of text) too, but that will require more adaptations to the code.

Anyway, just a proposal, let me know what you think! Thanks!

**Comment by mkevins** [comment]
Thanks for taking a look at this one Stefanos! :smile: 

> I'm not yet sure about trying to fix the issue by essentially mimicking the logic GBoard uses. I feel it's a bit complex and prone to breakages if GBoard updates it's logic.

To clarify, the earlier approach wasn't really "mimicking" gboard, but rather trying to "detect" it. I agree, though, that in some sense, it relies on specific behavior of Gboard that may change at some point in the future. Also, in some sense, that's how we got here :laughing: .

I think to address the other cases that my approach hadn't yet handled, we'd inevitable need to do a search for the newline, so your solution is actually more general, and covers these cases, as well as the usual non-Gboard keyboards, at least in my understanding. I tested your patch, and included it in this PR (reverting the "segmented" approach).

I tested this with several scenarios, and it seems to solve the issue and I did not encounter any regressions either. I tried a few different things, such as having text selected when pressing enter (which does not work, but is not a regression either - think of that one as an easter egg in inserting a newline in lieu of shift-enter :smiley: ).

Regarding paste, the good news is that we actually bypass paste when we have a paste handler on the Gutenberg side, so that is all handled in JS. Was there a particular scenario you had concerns with in paste where perhaps we don't have a gb handler?

**Comment by hypest** [comment]
Oh, good to see you like and incorporated the gist Matthew! And thanks for putting it through more testing. I can't hide my feeling that it could introduce other bugs so, your testing helps alleviate the fear :)

> Regarding paste, the good news is that we actually bypass paste when we have a paste handler on the Gutenberg side, so that is all handled in JS.

🎉 awesome!

> Was there a particular scenario you had concerns with in paste where perhaps we don't have a gb handler?

Not really. Just looking at the code and how it only searches for >1< Enter char, just makes me wonder what would happen if the text had more, and that's when the "what happens when pasting multiple paragraphs" came to mind, nothing more specific. It's good that the paste is handled elsewhere anyway so, we can leave it at that for the time being 👍

**Comment by mkevins** [comment]
# Writing flow tests for [ENTER] behavior

These tests should be performed both with and without a Gboard keyboard. It may be worth paying close attention to the known issues with enter key behavior to make sure there aren't any new regressions, and if possible, whether some other issues are fixed by these changes.

## With Gboard keyboard

:x: Multiline components - Test Cases

 <details>
 <summary>Testing Steps</summary>

Test the next steps on:
- :x: Quote block - On enter splits the block instead of adding newline without splitting
- :x: Verse block - On enter adds two <br> tags instead of just one
- :x: Preformatted block - On enter adds two <br> tags instead of just one
- Code block (DEV only)
- :x: Pullquote block - On enter adds two <p> tags instead of just one

##### TC001

**Known Issues**
- On Android, tapping Enter to split a quote or pullquote citation both splits the block and adds a newline to the citation ([#2498](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2498))
- :heavy_check_mark: On Android, pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior ([#27690](https://github.com/WordPress/gutenberg/issues/27690)) - This appears to have been fixed
- On Android, there is sometimes a loss of lines when entering multiple lines. ([#29861](https://github.com/WordPress/gutenberg/issues/29861))
- There is sometimes inconsistent HTML surrounding newlines in the Pullquote and Quote Block.  ([#1396](https://github.com/WordPress/gutenberg/issues/1396))

**New line on multiline components**

- Start typing and press enter to create a new line.
- The new line should be created, without splitting the block.
- On citations, pressing Enter at the end of a citation splits the block, but pressing enter in the middle of a citation creates a new line.
- Check on HTML mode that the resulting HTML code is correct:
  - *Quote*: `<p>` tags per paragraph.
  - *Quote citation*: `<br>` ending lines.
  - *Verse*: `<br>` ending lines.
  - *Preformatted*: `<br>` ending lines.
  - *Code*: (Invisible `\n`) new line character.
  - *Pullquote*: `<p>` tags per non-wrapping "line"
  - *Pullquote citation*: `<br>` ending lines.

 </details>

 ---

 - [x] Rich Text Formatting - Test Cases

 <details>
 <summary>Testing Steps</summary>

#### **Precondition**

Have a rich-text based component with content (Paragraph, Heading, Quote, Media Caption, etc...)


##### TC003

**Alignment Split**

- Write some lines on a paragraph block.
- Set an alignment on the block.
- Move the caret by the half of the text and press enter to split it.
- Check that the new block has the same alignment.
- Check that the text alignment corresponds to the setting.


 </details>

 ---

:x: Splitting and merging - Test Cases

 <details>
 <summary>Testing Steps</summary>


**Known Issues**
- :heavy_check_mark: **[Android]** Cannot split blocks immediately after prepending to a "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2372 - this issue seems to be resolved
- :heavy_check_mark: **[Android]** Splitting block before "swiped" word loses "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2373 - this issue seems to be resolved

#### **Precondition**

Start from an empty post.

*Initial steps*

- Repeat the next steps on a Paragraph and Heading block
- Write (or paste) a paragraph with a few lines
- Set the caret by the half of the paragraph
- Press Enter (Intro) to split the block into two.


##### TC001

**Known Issues**

- **[Android]** Deleting "swiped" or selected words can prevent merging two blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after writing**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block).
- Delete all new text using the delete button until the blocks are merged again.
- Check that the blocks were merged.


##### :x: TC002

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after selection**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block)
- Select all the newly written text,
- Press delete to remove all selected text.
- :x: Press delete once again to merge the blocks. - Unable to merge after selection was deleted
- Check that the blocks were merged.


##### TC003

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting text**
- Follow the initial steps.
- Move the caret a few words.
- Delete all those words until the blocks merge.
- Check that the blocks were merged.


##### TC004

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting all**
- Follow the initial steps.
- Select and remove all content of the new block
- Press delete to remove the empty block.
- Check that the previous block was selected.


##### TC005

**Merge multiple blocks**
- Follow the initial steps.
- Press enter two times to create an empty block in between
- Press back two times to merge everything again.
- Check that the blocks were merged.


##### :x: TC006

**Splitting/merge list block** - cannot add new items to list, can only split into new lists with one item on entering
- Write some items on a list block
- Put the caret by the half of them (at the end of the item) and press Enter to create a new item.
- Press Enter again to split the block into two, with an empty paragraph block in the middle. The paragraph block at the middle should be focused.
- Write something on that newly created paragraph block.
- Move the cursor to the beginning of the paragraph block
- Press delete to merge the paragraph block with the upper list block.
- Check that the new word should be a new list item.
- Move the caret to the beginning of the second list block.
- Press delete once to merge it back into the first list block.
- Check that everything was merged and there’s just one list block.

 </details>

## With non-Gboard keyboard

 - [ ] Multiline components - Test Cases

 <details>
 <summary>Testing Steps</summary>

Test the next steps on:
- Quote block
- Verse block
- Preformatted block
- Code block (DEV only)
- Pullquote block

##### TC001

**Known Issues**
- On Android, tapping Enter to split a quote or pullquote citation both splits the block and adds a newline to the citation ([#2498](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2498))
- On Android, pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior ([#27690](https://github.com/WordPress/gutenberg/issues/27690))
- On Android, there is sometimes a loss of lines when entering multiple lines. ([#29861](https://github.com/WordPress/gutenberg/issues/29861))
- There is sometimes inconsistent HTML surrounding newlines in the Pullquote and Quote Block.  ([#1396](https://github.com/WordPress/gutenberg/issues/1396))

**New line on multiline components**

- Start typing and press enter to create a new line.
- The new line should be created, without splitting the block.
- On citations, pressing Enter at the end of a citation splits the block, but pressing enter in the middle of a citation creates a new line.
- Check on HTML mode that the resulting HTML code is correct:
  - *Quote*: `<p>` tags per paragraph.
  - *Quote citation*: `<br>` ending lines.
  - *Verse*: `<br>` ending lines.
  - *Preformatted*: `<br>` ending lines.
  - *Code*: (Invisible `\n`) new line character.
  - *Pullquote*: `<p>` tags per non-wrapping "line"
  - *Pullquote citation*: `<br>` ending lines.

 </details>

 ---

 - [x] Rich Text Formatting - Test Cases

 <details>
 <summary>Testing Steps</summary>

#### **Precondition**

Have a rich-text based component with content (Paragraph, Heading, Quote, Media Caption, etc...)


##### TC003

**Alignment Split**

- Write some lines on a paragraph block.
- Set an alignment on the block.
- Move the caret by the half of the text and press enter to split it.
- Check that the new block has the same alignment.
- Check that the text alignment corresponds to the setting.


 </details>

 ---

 - [ ] Splitting and merging - Test Cases

 <details>
 <summary>Testing Steps</summary>


**Known Issues**
-  **[Android]** Cannot split blocks immediately after prepending to a "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2372
- **[Android]** Splitting block before "swiped" word loses "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2373

#### **Precondition**

Start from an empty post.

*Initial steps*

- Repeat the next steps on a Paragraph and Heading block
- Write (or paste) a paragraph with a few lines
- Set the caret by the half of the paragraph
- Press Enter (Intro) to split the block into two.


##### TC001

**Known Issues**

- **[Android]** Deleting "swiped" or selected words can prevent merging two blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after writing**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block).
- Delete all new text using the delete button until the blocks are merged again.
- Check that the blocks were merged.


##### TC002

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after selection**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block)
- Select all the newly written text,
- Press delete to remove all selected text.
- Press delete once again to merge the blocks.
- Check that the blocks were merged.


##### TC003

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting text**
- Follow the initial steps.
- Move the caret a few words.
- Delete all those words until the blocks merge.
- Check that the blocks were merged.


##### TC004

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting all**
- Follow the initial steps.
- Select and remove all content of the new block
- Press delete to remove the empty block.
- Check that the previous block was selected.


##### TC005

**Merge multiple blocks**
- Follow the initial steps.
- Press enter two times to create an empty block in between
- Press back two times to merge everything again.
- Check that the blocks were merged.


##### TC006

**Splitting/merge list block**

- Write some items on a list block
- Put the caret by the half of them (at the end of the item) and press Enter to create a new item.
- Press Enter again to split the block into two, with an empty paragraph block in the middle. The paragraph block at the middle should be focused.
- Write something on that newly created paragraph block.
- Move the cursor to the beginning of the paragraph block
- Press delete to merge the paragraph block with the upper list block.
- Check that the new word should be a new list item.
- Move the caret to the beginning of the second list block.
- Press delete once to merge it back into the first list block.
- Check that everything was merged and there’s just one list block.

 </details>

**Comment by mkevins** [comment]
Unfortunately, it seems that the current change (https://github.com/WordPress/gutenberg/pull/30368/commits/2ea16549c625676a153dc5f17750589b4d37cc40) set may introduce other regressions in writing flow tests, although it does seem to fix some known issues as well.

Fixes:

* Pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior https://github.com/WordPress/gutenberg/issues/27690
* Cannot split blocks immediately after prepending to a "swiped" word wordpress-mobile/gutenberg-mobile#2372
* Splitting block before "swiped" word loses "swiped" word wordpress-mobile/gutenberg-mobile#2373

Regressions:

* Multiline Components – TC001 - New line on multiline components
  * Quote block – On enter splits the block instead of adding newline without splitting
  * Verse block – On enter adds two <br> tags instead of just one
  * Preformatted block  – On enter adds two <br> tags instead of just one
  * Pullquote block -On enter adds two <p> tags instead of just one
* Splitting and Merging - TC002 – Merge after Selection - Unable to merge after selection was deleted
* Splitting and Merging -TC006 - Splitting and Merging List Block – cannot add new items to list, can only split into new lists with one item on entering

More details in the [testing steps listed here](https://github.com/WordPress/gutenberg/pull/30368#issuecomment-813975280).

**Comment by hypest** [comment]
Thanks for running more detailed tests @mkevins ! Will have a look at the regressions from my side too 👍 

Sorry, read your comment above too fast Matthew. Are you trying to check the solution in this PR, or perhaps do more testing on the [merged PR with the dropping selection event solution](https://github.com/WordPress/gutenberg/pull/29683)? 🤔

**Comment by mkevins** [comment]
> Thanks for running more detailed tests @mkevins ! Will have a look at the regressions from my side too 

Awesome, thanks Stefanos!

> Sorry, read your comment above too fast Matthew. Are you trying to check the solution in this PR, or perhaps do more testing on the [merged PR with the dropping selection event solution](https://github.com/WordPress/gutenberg/pull/29683)?

I'm checking the current changeset (https://github.com/WordPress/gutenberg/pull/30368/commits/2ea16549c625676a153dc5f17750589b4d37cc40) in this PR by running through the writing flow tests that involved [ENTER] keypresses. My intention is to check for any possible regressions we may face by altering the enter-detection mechanism. So far, I've encountered a few, mostly to do with lists and (pull)quote blocks.

**Comment by mkevins** [comment]
# Writing flow tests for [ENTER] behavior

Since the approach searching for newlines seems to introduce some regressions, I also tried the tests w/ the earlier approach, since it was written with the intent to minimize side effects by attempting to detect and isolate Gboard specific behavior. I performed these tests both with and without a Gboard keyboard with this changeset: https://github.com/WordPress/gutenberg/pull/30368/commits/7363bb5f1a5a1a99ddead0c822eb0d3b2c1da32e.

It seems that most of the behavior is unchanged (i.e. I did not encounter any new regressions), and the specific case of pressing `[ENTER]` at the end of a suggested word seems to work correctly with these changes. I also noticed that a few of the known issues seem to be resolved on `trunk`, and noted that in those cases.

## With Gboard keyboard

 - [x] Multiline components - Test Cases

 <details>
 <summary>Testing Steps</summary>

Test the next steps on:
- Quote block
- Verse block
- Preformatted block
- Code block (DEV only)
- Pullquote block

##### TC001

**Known Issues**
- On Android, tapping Enter to split a quote or pullquote citation both splits the block and adds a newline to the citation ([#2498](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2498))
- :heavy_check_mark: On Android, pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior ([#27690](https://github.com/WordPress/gutenberg/issues/27690)) - this seems to be fixed on `trunk`
- :heavy_check_mark: On Android, there is sometimes a loss of lines when entering multiple lines. ([#29861](https://github.com/WordPress/gutenberg/issues/29861)) - this seems to be fixed on `trunk`
- There is sometimes inconsistent HTML surrounding newlines in the Pullquote and Quote Block.  ([#1396](https://github.com/WordPress/gutenberg/issues/1396))

**New line on multiline components**

- Start typing and press enter to create a new line.
- The new line should be created, without splitting the block.
- On citations, pressing Enter at the end of a citation splits the block, but pressing enter in the middle of a citation creates a new line.
- Check on HTML mode that the resulting HTML code is correct:
  - *Quote*: `<p>` tags per paragraph.
  - *Quote citation*: `<br>` ending lines.
  - *Verse*: `<br>` ending lines.
  - *Preformatted*: `<br>` ending lines.
  - *Code*: (Invisible `\n`) new line character.
  - *Pullquote*: `<p>` tags per non-wrapping "line"
  - *Pullquote citation*: `<br>` ending lines.

 </details>

 ---

 - [x] Rich Text Formatting - Test Cases

 <details>
 <summary>Testing Steps</summary>

#### **Precondition**

Have a rich-text based component with content (Paragraph, Heading, Quote, Media Caption, etc...)


##### TC003

**Alignment Split**

- Write some lines on a paragraph block.
- Set an alignment on the block.
- Move the caret by the half of the text and press enter to split it.
- Check that the new block has the same alignment.
- Check that the text alignment corresponds to the setting.


 </details>

 ---

 - [x] Splitting and merging - Test Cases

 <details>
 <summary>Testing Steps</summary>


**Known Issues**
- :heavy_check_mark: **[Android]** Cannot split blocks immediately after prepending to a "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2372 - seems to be resovled on `trunk` as well
- **[Android]** Splitting block before "swiped" word loses "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2373

#### **Precondition**

Start from an empty post.

*Initial steps*

- Repeat the next steps on a Paragraph and Heading block
- Write (or paste) a paragraph with a few lines
- Set the caret by the half of the paragraph
- Press Enter (Intro) to split the block into two.


##### TC001

**Known Issues**

- **[Android]** Deleting "swiped" or selected words can prevent merging two blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after writing**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block).
- Delete all new text using the delete button until the blocks are merged again.
- Check that the blocks were merged.


##### TC002

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after selection**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block)
- Select all the newly written text,
- Press delete to remove all selected text.
- Press delete once again to merge the blocks.
- Check that the blocks were merged.


##### TC003

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting text**
- Follow the initial steps.
- Move the caret a few words.
- Delete all those words until the blocks merge.
- Check that the blocks were merged.


##### TC004

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting all**
- Follow the initial steps.
- Select and remove all content of the new block
- Press delete to remove the empty block.
- Check that the previous block was selected.


##### TC005

**Merge multiple blocks**
- Follow the initial steps.
- Press enter two times to create an empty block in between
- Press back two times to merge everything again.
- Check that the blocks were merged.


##### TC006

**Splitting/merge list block**

- Write some items on a list block
- Put the caret by the half of them (at the end of the item) and press Enter to create a new item.
- Press Enter again to split the block into two, with an empty paragraph block in the middle. The paragraph block at the middle should be focused.
- Write something on that newly created paragraph block.
- Move the cursor to the beginning of the paragraph block
- Press delete to merge the paragraph block with the upper list block.
- Check that the new word should be a new list item.
- Move the caret to the beginning of the second list block.
- Press delete once to merge it back into the first list block.
- Check that everything was merged and there’s just one list block.

 </details>

## With non-Gboard keyboard

 - [x] Multiline components - Test Cases

 <details>
 <summary>Testing Steps</summary>

Test the next steps on:
- Quote block
- Verse block
- Preformatted block
- Code block (DEV only)
- Pullquote block

##### TC001

**Known Issues**
- On Android, tapping Enter to split a quote or pullquote citation both splits the block and adds a newline to the citation ([#2498](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2498))
- :heavy_check_mark: On Android, pressing enter multiple times in the content of a Pullquote or Quote block causes unintended behavior ([#27690](https://github.com/WordPress/gutenberg/issues/27690)) - this seems to be fixed on `trunk`
- :heavy_check_mark: On Android, there is sometimes a loss of lines when entering multiple lines. ([#29861](https://github.com/WordPress/gutenberg/issues/29861)) - this seems to be fixed on `trunk`
- There is sometimes inconsistent HTML surrounding newlines in the Pullquote and Quote Block.  ([#1396](https://github.com/WordPress/gutenberg/issues/1396))
**New line on multiline components**

- Start typing and press enter to create a new line.
- The new line should be created, without splitting the block.
- On citations, pressing Enter at the end of a citation splits the block, but pressing enter in the middle of a citation creates a new line.
- Check on HTML mode that the resulting HTML code is correct:
  - *Quote*: `<p>` tags per paragraph.
  - *Quote citation*: `<br>` ending lines.
  - *Verse*: `<br>` ending lines.
  - *Preformatted*: `<br>` ending lines.
  - *Code*: (Invisible `\n`) new line character.
  - *Pullquote*: `<p>` tags per non-wrapping "line"
  - *Pullquote citation*: `<br>` ending lines.

 </details>

 ---

 - [x] Rich Text Formatting - Test Cases

 <details>
 <summary>Testing Steps</summary>

#### **Precondition**

Have a rich-text based component with content (Paragraph, Heading, Quote, Media Caption, etc...)


##### TC003

**Alignment Split**

- Write some lines on a paragraph block.
- Set an alignment on the block.
- Move the caret by the half of the text and press enter to split it.
- Check that the new block has the same alignment.
- Check that the text alignment corresponds to the setting.


 </details>

 ---

 - [x] Splitting and merging - Test Cases

 <details>
 <summary>Testing Steps</summary>


**Known Issues**
-  **[Android]** Cannot split blocks immediately after prepending to a "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2372
- **[Android]** Splitting block before "swiped" word loses "swiped" word https://github.com/wordpress-mobile/gutenberg-mobile/issues/2373

#### **Precondition**

Start from an empty post.

*Initial steps*

- Repeat the next steps on a Paragraph and Heading block
- Write (or paste) a paragraph with a few lines
- Set the caret by the half of the paragraph
- Press Enter (Intro) to split the block into two.


##### TC001

**Known Issues**

- **[Android]** Deleting "swiped" or selected words can prevent merging two blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after writing**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block).
- Delete all new text using the delete button until the blocks are merged again.
- Check that the blocks were merged.


##### TC002

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after selection**
- Follow the initial steps.
- Write some more text where the caret is placed (beginning of new block)
- Select all the newly written text,
- Press delete to remove all selected text.
- Press delete once again to merge the blocks.
- Check that the blocks were merged.


##### TC003

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting text**
- Follow the initial steps.
- Move the caret a few words.
- Delete all those words until the blocks merge.
- Check that the blocks were merged.


##### TC004

**Known Issues**
- **[Android]** Deleting "swiped" or selected words prevents merging blocks https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375

**Merge after deleting all**
- Follow the initial steps.
- Select and remove all content of the new block
- Press delete to remove the empty block.
- Check that the previous block was selected.


##### TC005

**Merge multiple blocks**
- Follow the initial steps.
- Press enter two times to create an empty block in between
- Press back two times to merge everything again.
- Check that the blocks were merged.


##### TC006

**Splitting/merge list block**

- Write some items on a list block
- Put the caret by the half of them (at the end of the item) and press Enter to create a new item.
- Press Enter again to split the block into two, with an empty paragraph block in the middle. The paragraph block at the middle should be focused.
- Write something on that newly created paragraph block.
- Move the cursor to the beginning of the paragraph block
- Press delete to merge the paragraph block with the upper list block.
- Check that the new word should be a new list item.
- Move the caret to the beginning of the second list block.
- Press delete once to merge it back into the first list block.
- Check that everything was merged and there’s just one list block.

 </details>

**Comment by mkevins** [comment]
Closing as these changes were brought in with: https://github.com/WordPress/gutenberg/pull/32471

**Pull request closed without merging**
