### PR TITLE
Add 'View site' action to 'Site updated' snackbar

### PR DESCRIPTION
**Pull request by jameskoster**
Screenshot 2023-07-17 at 15 56 46

## What?
Add a 'View site' action to the 'Site updated' snackbar in the site editor.

## Why?
This seems like a moment where the user may want to view their changes on the frontend.

## Testing Instructions
1. Open the site editor.
2. Change the site in any way (edit a page, template, styles, etc).
3. Save changes
4. Observe the "View site" link in the resulting Snackbar
5. Click "View site" and ensure the link works

### CODE REVIEW

**Comment by jasmussen** [comment]
I could see this, but I'm not entirely sure we want to add this to the snackbar.

Working through it, the snackbar persists between both edit and site views, and in both those views we have these two:

site view external link button

edit view external link button

post editor view post button

Among the above three, there's likely some further consolidation we can do, as both the edit view toolbar evolves, and as the site editor evolves.

The main issue with snackbars right now is that they persist for a much too long time. They even stack endlessly, so in some cases you'll end up with a stack of 5 or 6 snackbars that still linger on screen as you're just working through editing content, templates, and styles. We _have_ to cut back on that, both by throttling (so you only ever see at most 2, perhaps 3 snackbars stacked), but also the time these linger on screen.

Last I revisited the PRs that extended the time these stayed on screen, the argument was that they contained important information, and I believe the "view post" link was specifially mentioned. To me that's an argument to embrace the permanent buttons for those actions, and actually consider _removing_ those actions from the snackbars — keep them as ephemeral as they need to be in order for them to be able to fade out in a reasonable amount of time (closer to something like _two_ seconds instead of the current _ten_ seconds). 

I recognize we can probably refine the component further, so that for example snackbars that do not feature any actions fade out quickly, and snackbars that _do_ feature actions can stay for a bit longer, but even in that case I would only ever put "fine to miss" actions there, and still fade them out aggressively. If we truly deeply want a snackbar to linger, they should not fade out at all, and require dismissal using an X.

That's a roundabout way of saying, perhaps it's best to keep this one ephemeral?

Not a strong opinion, even if my opinion on fading out snackbars quickly is :)

**Comment by richtabor** [comment]
> I could see this, but I'm not entirely sure we want to add this to the snackbar.

I think we should. "View $postType" is available on the snackbar when publishing within the post editor. I always expect the same within the site editor. 

Snackbars do need revisiting in general, but from my POV publishing and clicking the "View post" link is a super helpful flow to quickly see the front-end. You don't have to find the externalLink icon, or other links to the front-end, it's presented to you.

**Comment by jameskoster** [comment]
I agree with pretty much everything you said @jasmussen, but unless we intend to remove actions altogether it seems mostly separate to this particular PR. Like @richtabor said this is about surfacing the action in a relevant moment and aligning with similar Snackbars in the post editor.

**Review by richtabor — APPROVED** [review]
CleanShot 2023-11-22 at 15 14 59
Works as expected.

**Pull request merged**
