### PR TITLE
Experiment: Allow creating template parts from block library

### PR DESCRIPTION
**Pull request by talldan**
## What?
Exploration for #31746

Allows selection of a pattern or existing template part from the inserter prior to insertion of Header / Footer (template part) blocks.

## How?
I'm currently testing a few ideas around how to implement this.

Currently this adds an `inserterItem` property for for blocks and block variations that can be defined as a React component. It replaces the normal item for the block in the inserter.

The block editor package also exports a `InserterListItemWithModal` (name could be revised) component that makes it easier to implement an inserter item that launches a modal and has the right aria roles.

For header and footer template part variations, the pattern selection modal is shown and the inserted template part will be pre-configured with that pattern.

Problems with this approach:
- Drag and drop from the inserter is very difficult to implement
- Introduces a new block API and quite a few code changes
- The new block API is very open, plugins could easily break keyboard navigation in the inserter, or make their blocks have gigantic icons! Ideally there would be a way to lock this down to only work with `InserterListItemWithModal`.

## Testing Instructions
1. For best results use a theme like 2022 that has template part patterns.
2. Load the site editor
3. Open the block library
4. Select the 'Header' or 'Footer' template part variations.
5. Choose a pattern.

## Screenshots or screencast 

https://user-images.githubusercontent.com/677833/180133809-267989d2-07d4-45b0-9cef-fafaf6b2a2f3.mp4

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for the PR @talldan, it's good to see this in action to get a better feel for the overall flow(s). Based on some initial exploration I think it can work well. 

I imagine the new 'Template Parts' section in the Inserter is to aid testing, but just to clarify – these can probably live in the 'Theme' section for now.

It tripped me up a bit to see _existing template parts_ as options in the modal, that seems a bit redundant. It might be better to only surface patterns here. On a similar note, it could be confusing to see patterns that have already been used to create template parts, e.g. the 'Large header with dark background' in Twenty Twenty-Two. If it's possible to exclude such patterns that would be 👌

New Header and New Footer UX feels good, but I'm not sure how useful New Template Part is going to be. The scope of a general template part is very broad, so the likelihood of patterns we surface being relevant is quite low. Without some kind of filtering options on the modal, it feels too clunky. For now I would be inclined to limit this to the creation of headers and footers only.

> It also feels like the template selection modal could be polished before adding this option so prominently.

I think it's probably ok to add this without polish for now, as the modal refinement could be quite a big project. There are some designs in https://github.com/WordPress/gutenberg/issues/39308#issuecomment-1133086932 that explore this in detail.

> Inserted template parts are 'untitled'

Could we use the pattern name as a 'default' title?

> I also wonder whether we want to show the normal Header / Footer / Template Part blocks within the library in addition to these new items. It feels like duplication.

Agreed. Existing template parts should be listed by name instead (#31748, https://github.com/WordPress/gutenberg/issues/41399).

**Comment by talldan** [comment]
Thanks for the feedback @jameskoster - I'll get to work on making those changes.

**Comment by mtias** [comment]
> Could we use the pattern name as a 'default' title?

That'd be good. Also we should take into account what template you are creating it in — if I'm creating a new header on a category archive template, and I already have a header template part, the name should probably be something like "Archive {Name of Pattern}".

**Comment by talldan** [comment]
Throughout development so far I've been focusing on launching a modal directly from the inserter menu item. An alternative simpler technical solution is to insert a template part block as normal when clicking the item in the inserter, but have the block open the pattern selection modal straight away when certain conditions are met (an initial attribute is set?).

I think it would be possible to do this without any block API changes, but there's a drawback that it'll be more difficult to get the accessibility story right (`aria-haspopup` and `aria-expanded` need to somehow be set on the inserter item).

**Comment by talldan** [comment]
@jameskoster I've pushed an iteration on this that includes most of the changes discussed. Template part naming doesn't quite do what @mtias mentioned yet, still looking into that one, but it will use the pattern name. Let me know what you think.

I'm still trying a few things when it comes to the technical implementation, so this PR is not ready for code review yet.

**Comment by jameskoster** [comment]
Thanks @talldan, I appreciate the work in this update. Here's what I'm seeing:

https://user-images.githubusercontent.com/846565/178268664-b08423ec-b21c-4ddb-b4a6-ad0e5b2543e8.mp4

It feels pretty slick to use, but there are a couple of drawbacks:

1. It's not clear whether I'm inserting an existing template part, or creating a new one based on a pattern.
2. I'm missing a way to start blank. 

These are relatively easy to fix, but we should think holistically about which approach will be best. 

On the one hand we have a single Header block – as in this PR – which handles both the insertion of existing template parts _and_ the creation of new ones via patterns. On the other hand we have the option of listing existing template parts in the Inserter (https://github.com/WordPress/gutenberg/issues/31748), then having a dedicated "New template part" block which opens the pattern modal. Considering that we also want to list existing template parts in the Patterns tab (https://github.com/WordPress/gutenberg/issues/41399), I'm inclined to say that the latter could be the way to go. But, there's also a world where we implement both, so that we have:

1. Monolithic 'Header' block that allows selection of existing template parts and creation of new ones
2. A 'New Header' block that opens the pattern modal
3. Dedicated blocks for each existing template part

I would love to hear thoughts from @WordPress/gutenberg-design on this one.

**Comment by jameskoster** [comment]
If we add 'New header' and 'New Footer' blocks, here are some icons based on the recently added 'Add template' icon:

Screenshot 2022-07-11 at 14 22 55

**New header**

```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M18.5 8V5.5H17.5H16V4H17.5H18H18.5V1.5H20V4H22.5V5.5H20V8H18.5ZM16 10.5H10L10 18.5H18C18.2761 18.5 18.5 18.2761 18.5 18V10.5H20V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V6C4 4.89543 4.89543 4 6 4H13.5V7.5H16V10.5ZM8.5 10.5H5.5V18C5.5 18.2761 5.72386 18.5 6 18.5H8.5L8.5 10.5Z" fill="#1E1E1E"/>
</svg>
```
**New footer**
```
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M18.5 8V5.5H18H17.5H16V4H17.5H18H18.5V1.5H20V4H22.5V5.5H20V8H18.5ZM18.5 10.5H20V18C20 19.1046 19.1046 20 18 20H6C4.89543 20 4 19.1046 4 18V6C4 4.89543 4.89543 4 6 4H13.5V5.5H10L10 13.5H18.5V10.5ZM8.5 13.5H5.5V6C5.5 5.72386 5.72386 5.5 6 5.5H8.5L8.5 13.5Z" fill="#1E1E1E"/>
</svg>
```

**Comment by talldan** [comment]
Thanks for the further feedback @jameskoster. I'll have a think about the best way to achieve that and let you know when I have something more to test.

**Comment by jameskoster** [comment]
Just connecting a dot that @critterverse pointed out to me... the work here could go a long way towards closing https://github.com/WordPress/gutenberg/issues/41397 as well. If it's not suitable to include in this PR, perhaps we can look into it as a follow up.

**Comment by talldan** [comment]
> 1. Monolithic 'Header' block that allows selection of existing template parts and creation of new ones
> 2. A 'New Header' block that opens the pattern modal
> 3. Dedicated blocks for each existing template part

I think it makes sense to break this up into two or three PRs along those lines.

For the last one, it looks like there are a lot of similarities to the way we show each instance of a reusable block in the inserter rather than just one 'reusable block'. At the moment, reusable block doesn't use block variations to achieve this, there's a very ad-hoc piece of code that shouldn't really be there:
https://github.com/WordPress/gutenberg/blob/f01f981c8934523b42531d1ddb03da4cf5cf45c9/packages/block-editor/src/store/selectors.js#L1937-L1982

I think there's a good opportunity to remove this code in favor of using the block api.

**Comment by jameskoster** [comment]
> I think it makes sense to break this up into two or three PRs along those lines.

Yeah that seems like a good idea. I suppose this PR can facilitate the first point in the list.

To that end, the missing pieces are:

* The modal should list both existing template parts _and_ patterns
* The UI should communicate whether each entity is an existing template part of a pattern. Can we reuse the existing 'Replace' modal? (Bonus points if we can update "Existing template parts" to "Existing Headers").

modal

* When the user elects to insert a pattern we should go ahead and create a template part and use the pattern name for the template part name. (This would cover the groundwork required for 41397 🎉).
* There should be an option to start blank, a footer action could work:

Screenshot 2022-07-13 at 12 52 44


> it looks like there are a lot of similarities to the way we show each instance of a reusable block in the inserter rather than just one 'reusable block'

There are a lot of similarities in general, not to mention patterns as well 😁 The more we can align the interactions and obfuscate the underlying complexity, the better the experience will be 💪

**Comment by talldan** [comment]
This should be getting closer to what's described in the last comment.

> Bonus points if we can update "Existing template parts" to "Existing Headers"

We don't have an internationalized plural form of the area label, but I can look at adding this.

> There should be an option to start blank, a footer action could work:

This is still on my to do list.

Let me know if there's anything else I missed.

**Comment by jameskoster** [comment]
> We don't have an internationalized plural form of the area label, but I can look at adding this.

No worries, let's do it in a follow up. I'll make an issue.

Aside from the missing 'Start blank' option this is working really well, except for one quirk: If you choose a pattern in the modal, a template part is created with the name of that pattern. If you repeat the process _another_ template part is created _with the same name_, which can lead to confusion:

Screenshot 2022-07-15 at 15 01 20

Two possible resolutions:

1. Check if a template part with the same name already exists, and if so append `-1` to the name of the new template part.
2. Hide patterns with names that match existing template parts

Each have some trade-offs. Option 1 could result in a proliferation of template parts if the user isn't diligent. The second option could lead to legitimate patterns being hidden. 

What do you think?

Edit: I noticed it's possible to give a template part a duplicate name even when creating manually, so I opened https://github.com/WordPress/gutenberg/issues/42473. Perhaps it's better to address this separately?

**Comment by jameskoster** [comment]
I just noticed something else, unsure if it's only on this PR or an existing problem; if you drag 'Header' from the Inserter on to the canvas nothing happens.

**Comment by paaljoachim** [comment]
Let's see if I understand this correctly based on my limited understanding. Brainstorming coming up based on the initial post by Dan. Voicing my confusion.

There will be icons called New Header, New Footer etc directly in the Block inserter screen.
I find Workflows section currently somewhat confusing as it really overlaps clicking the Header, Footer and Template Part icons seen in the Themes section.

First off all I might start the Block Inserter with the Theme section instead of the Text section when in Full Site Editing, as it would show possible blocks/template parts one could add to a template before going into more detailed blocks.

**Comment by jameskoster** [comment]
@paaljoachim please see the three bullet points at the end of [this comment](https://github.com/WordPress/gutenberg/pull/42142#issuecomment-1180391165) for an overview of what we're considering. This PR originally concentrated on the second point, but kind of morphed into concentrating on the first one :)

**Comment by talldan** [comment]
@paaljoachim I think the video on the PR description was a little outdated when you read it. It's updated now.

**Comment by talldan** [comment]
I've put together an alternative PR - #42581.

The difference in that PR is that when selecting a Header or Footer from the inserter, the block is inserted first and then the inserted block immediately displays the selection modal.

There are some differences in the user flow - if the user closes the modal, the block is still present in a placeholder state.

I thought it'd be interesting to try because it's only a few lines of code to achieve almost the same thing and doesn't require any new APIs. It still has a few issues to iron out though, and it isn't quite as smooth as this PR.

**Comment by noisysocks** [comment]
Very interesting problem!

Just an idea, but what if, instead of `inserter: JSX.Element` which is rendered after the button in the inserter is clicked, you have `inserterButton: JSX.Element` which allows block authors to entirely replace the button in the inserter. Then, the template part block specifies a custom inserter button which has an `onClick` that renders a modal before eventually calling `insertBlock`.

I'm thinking that should let you set `aria-haspopup` on the button and also implement the fun animation that @jameskoster has at the end of https://github.com/WordPress/gutenberg/issues/31746#issuecomment-843067374 because you can set a `ref` on the button and use that to calculate when the animation should start.

Regarding drag-and-drop, could we treat this flow as a _progressive enhancement_ to the default flow and not bother having it for block insertion flows that don't involve selecting an item in the inserter? So that's drag-and-drop, `/` inserter, quick inserter, programmatic insertion (e.g. by a plugin), etc.

**Comment by jameskoster** [comment]
> I've put together an alternative PR - https://github.com/WordPress/gutenberg/pull/42581.

Good to try! Having both behaviours (open modal and insert block) execute concurrently feels a little bit clunky to me. I fear it would get clunkier when we get around to implementing the animation @noisysocks linked to.

> Regarding drag-and-drop, could we treat this flow as a progressive enhancement to the default flow and not bother having it for block insertion flows that don't involve selecting an item in the inserter?

Yeah that could work :)

**Comment by talldan** [comment]
I've refactored this so it works closer to how @noisysocks described `inserterItem: ReactComponent`.

This API is a bit too open right now as it allows plugins to render anything in the inserter for their block. It'd be good to start with something more restrictive, so I'm working on that next.

**Comment by jameskoster** [comment]
Nice! I think we're just missing a solution to the duplicate name issue, and the start blank affordance.

**Comment by talldan** [comment]
I've added the 'Start blank' option. I think the modal also requires a loading spinner, as most of the actions involve an API request and aren't immediate. Any thoughts on how it should look, @jameskoster?

**Comment by jameskoster** [comment]
Oh good idea. We can probably just use the [Spinner](https://wordpress.github.io/gutenberg/?path=/story/components-spinner--custom-size) component.

**Comment by noisysocks** [comment]
Looking good in my testing. Nice that the focus isn't lost when pressing <kbd>ESC</kbd> too.

> This API is a bit too open right now as it allows plugins to render anything in the inserter for their block. It'd be good to start with something more restrictive, so I'm working on that next.

Yeah, makes sense. We have to be especially careful here as some plugins could abuse this to promote their blocks. (Though admittedly, bad actors will always find a way...)

**Comment by jameskoster** [comment]
Here's where we are:

https://user-images.githubusercontent.com/846565/182835821-d128351f-4446-4c0e-8418-34c91e885005.mp4

The spinner appearing above the content feels a bit awkward, could we place a white scrim over them, or just hide them?

Otherwise we're looking good :)

One thing to think about – potentially as a follow-up – what can we do to mitigate the proliferation of template parts? If you insert a header and choose a pattern, the template part is created immediately. If you undo, it persists in the system. If you delete the block before saving, it persists. If you repeat the process (create template part from pattern) you essentially end up with duplicate template parts. It's easy to see many unused / duplicate template parts building up over time.

**Comment by talldan** [comment]
> The spinner appearing above the content feels a bit awkward, could we place a white scrim over them, or just hide them?

@jameskoster There is an overlay, but maybe it's too subtle. I've pushed a commit to make it more obvious.

**Comment by talldan** [comment]
> One thing to think about – potentially as a follow-up – what can we do to mitigate the proliferation of template parts? If you insert a header and choose a pattern, the template part is created immediately. If you undo, it persists in the system. If you delete the block before saving, it persists. If you repeat the process (create template part from pattern) you essentially end up with duplicate template parts. It's easy to see many unused / duplicate template parts building up over time.

Some random thoughts—it may be interesting to treat patterns a bit like the theme provided template parts. When a user creates a template part from a pattern, the pattern name is recorded in the template part data, and after making customisations the user has the option of clearing those customisations back to the original template.

If the user tries creating a second template part from a pattern, a dialog can be shown offering the option of using the existing template part (and the UI can show whether this existing template part has had customisations).

There may be some challenges though - a pattern can be provided from a number of sources (plugins, themes, pattern directory), and can change over time or even be deleted, so I don't know whether 'clearing customisations' would always reliably give the user what they want.

**Comment by jameskoster** [comment]
> There is an overlay, but maybe it's too subtle. I've pushed a commit to make it more obvious.

Much better! :) I think this PR is ready for a wider audience / review now.

I suppose the proliferation issue will be resolved if/when we combine patterns with template parts (see discussion in https://github.com/WordPress/gutenberg/issues/34352). Still, I think there are some behind-the-scenes adjustments we can implement to help such as:

* Deleting template parts created from patterns if they aren't actually used in the document.
* Ensuring template parts cannot have duplicate names (https://github.com/WordPress/gutenberg/issues/42473).

**Pull request closed without merging**
