### PR TITLE
Update/site editor list view block hover

### PR DESCRIPTION
**Pull request by Copons**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jeyip** [comment]
Continuing the discussion from here https://github.com/WordPress/gutenberg/pull/29103#issuecomment-781294081

> I've been mulling over this for a long time, and I'm still not exactly sure if this is the right way to go.
>
> My doubt can be boiled down to: what's the difference between "highlight" and "hover"?
>
> On a technical level, the highlight is tracked with Redux, while the hover is handled via internal state (via hook, but that's irrelevant).
There are subtle visual differences: hover adds a blue (admin theme color) border, while highlight adds a black border, with a slightly different thickness.
>
> In this PR (and in my initial experiment as well), we are setting a block highlighted on hover, which in turn means that hovering on a block will make it both hovered and highlighted.
>
> Do we need both states?
Is hover semantically different than highlight, and therefore should they be kept separate?
>
> I've got a draft (#29005) that moves the block hover state to Redux, basically mirroring the highlight behaviour.
I haven't opened it for review because I'm not totally convinced by it.
>
> Besides the question about highlight/hover, I also wonder if dispatching on every mouseover and mouseout might be a performance issue. 🤔

I spent some time mucking around with debouncing and implementing mouseenter alongside mouseout to explore how much more performant we could make the interactions (not much)

**Comment by Copons** [comment]
@jeyip Thanks for moving the convo here! I'm sorry I didn't surface this PR sooner to avoid the duplication, but I kinda thought I was working on this alone... 😄 

I'll ping some designers that may have some insights regarding the hover/highlight distinction: @shaunandrews @jameskoster @mtias 
The tl;dr would be: blocks can be highlighted and hovered. Are there any semantical differences?
While hovering seems to only affect the block's own visual appearance, the highlight is tracked in Redux. Are there any side effects tied to highlighting a block?

**Comment by mtias** [comment]
I think we should generally use the "highlight" in these operations. (I used it for hovering/focusing on the parent block selector in the toolbar, and I think should be the exact same for the list view.) The other hover we have is meant to be used as a visual artefact (gray instead of blue) when just moving across the canvas. I think it should be restricted to that effect and don't be part of the redux store.

**Comment by Copons** [comment]
> I think we should generally use the "highlight" in these operations. (I used it for hovering/focusing on the parent block selector in the toolbar, and I think should be the exact same for the list view.) The other hover we have is meant to be used as a visual artefact (gray instead of blue) when just moving across the canvas. I think it should be restricted to that effect and don't be part of the redux store.

@mtias To give some context to the issue at hand: the main Persistent List View PR (#28637) already uses the highlight to... highlight blocks when **hovering on the List View items**.

In this PR we are figuring out how to do the opposite: highlight the List View item when **hovering the block**.
The problem is that the List View and the blocks are independent between each other, and so we would need to keep track of the hovered block in Redux, in order to share the info across the two contexts.

There are three options, as far as I can see, and I'm not convinced by any of them. 😅 

1. Add a new `hoveredBlock` reducer that tracks the hovered state of a block, replacing the `isHovered` internal state. (Approach proposed in this PR)
2. Kill the `isHovered` internal state, and use the (pre-existing) `highlightedBlock` reducer for both the highlighted and hovered state.
3. On block hover, we use both the `isHovered` internal state (for styling purpose?) and the `highlightedBlock` reducer (to share the info app-wide). (Proposed in #29103)

The way I see it, hover and highlight serve a very similar purpose, and their major difference is how they are triggered (mouseover or Redux action).
I'd be inclined in using the approach number 2 (basically merging hover and highlight), but I'm wary of any unforeseen consequences.

**Comment by mtias** [comment]
Ah, yes, got it. I think we need to go with `isHighlighted` in general. If there's anything to be done differently for actual selection, we should be using `isSelected`. That also applies to the hover effect on blocks themselves. cc @jasmussen

**Comment by Copons** [comment]
The related issue for this was closed for the time being (see [comment](https://github.com/WordPress/gutenberg/issues/28699#issuecomment-782116766)), so I'm going to close this PR as well!
cc @jeyip

**Pull request closed without merging**
