### PR TITLE
Update Dashicons

### PR DESCRIPTION
**Pull request by jasmussen**
This PR brings in an updated Dashicons sprite, and uses a couple of the new icons, Saved and Insert. The undo/redo/preview icons are also redesigned. 

There's also a new `heading` icon, cc: @iseulde 🎉

Screenshot:

screen shot 2017-04-17 at 09 38 29

Building this, I noticed a build issue with the component which I will fix upstream in the dashicons repo.

### CODE REVIEW

**Comment by jasmussen** [comment]
Question: the Dashicon component we include in Gutenberg is called `index.js`. But it is the uncompiled version we are using. Should we be including `index.jsx` instead? Dashicons outputs them both.

**Comment by youknowriad** [comment]
@jasmussen We're not using the `.jsx` convention for files containing JSX in the Gutenberg repository. Even if the file contains some JSX, it'll work as expected.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by iseulde** [comment]
Thanks! I'll update the heading PR

**Comment by joyously** [comment]
I just thought I'd ask: Are the undo and redo icons universal? or are they reversed for RTL languages?

**Comment by jasmussen** [comment]
> I just thought I'd ask: Are the undo and redo icons universal? or are they reversed for RTL languages?

Good question, they probably should be reversed. 

As with mobile responsive improvements, there will be a phase for optimizing for RTL.

**Pull request merged**
