### PR TITLE
Add undefined clientID case to isBlockSelected selector

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

When I was testing the changes from [PR](https://github.com/WordPress/gutenberg/pull/29309), I realised that the selector `isBlockSelected` from the store of the block editor package is not handling properly the case receiving an undefined `clientId`.

This case is probably an edge case for the editor but not for the native unit tests that render the blocks via the `react-test-renderer` library, in this case the blocks don't have a `clientId`.

## How has this been tested?

This has been tested by adding a new unit test for this case and running `npm run test`.

Additionally this change has been tested too in the mentioned [PR](https://github.com/WordPress/gutenberg/pull/29309) that originated the fix by running `npm run native test`.

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
> This case is probably an edge case for the editor but not for the native unit tests that render the blocks via the `react-test-renderer` library, in this case the blocks don't have a `clientId`.

Great debugging!
Any way we can adjust the tests instead?

**Comment by ellatrix** [comment]
Technically, if you ask if `undefined` (as a client ID) is selected, the answer should be yes. 😄 Not sure what is the *right* thing to do here. I would first try to adjust the test cases to include an ID if that's possible at all, maybe throw and error if no client ID is given. If that's not possible, maybe we should return nothing (`undefined`) if no client ID is given? It's falsy and seems like a better response than a pure `false`.

**Comment by ZebulanStanphill** [comment]
Calling the function with an `undefined` `clientId` sounds like something that should be disallowed by static typing in the first place and caught by a linter.

**Comment by mcsf** [comment]
> I would first try to adjust the test cases to include an ID if that's possible at all, maybe throw and error if no client ID is given.

This would be my choice too.

**Comment by fluiddot** [comment]
I agree that the `isBlockSelected` function shouldn't be called with an undefined `clientId`, so I'll review the unit tests and adjust them given that not passing a `clientId` could have undesired side effects. 

Meanwhile I'm going to close this PR. Thanks for your feedback 🙇 !

**Comment by ellatrix** [comment]
@fluiddot Thanks! Let me know when you have a new PR for a swift review and merge.

**Comment by fluiddot** [comment]
> @fluiddot Thanks! Let me know when you have a new PR for a swift review and merge.

I created this [issue](https://github.com/WordPress/gutenberg/issues/29442) with a potential solution for the problem with the native unit tests. I think it's the better solution but I'd like to have some feedback from other contributors.

**Pull request closed without merging**
