### PR TITLE
Add a "global_styles" filter

### PR DESCRIPTION
**Pull request by aristath**
## Description

While working on an FSE theme and trying to figure out how to load webfonts, it became apparent that there is currently no way for a theme to determine if a webfont defined in the `theme.json` file is actually used. As a result, themes are forced to always load webfonts they want to use.

This PR adds a `global_styles` filter to allow 3rd-party developers (both in themes and plugins) to filter the global styles on the frontend in order to add things if needed.

Example for the webfont:
```php
add_filter( 'global_styles', function( $styles ) {
    // Check if the "Literata" webfont is used.
    if ( false !== strpos( $styles, 'var(--wp--preset--font-family--literata)' ) ) {
        // Add webfont styles.
        $styles .= my_theme_get_webfont_styles( 'literata' );
    }
    return $styles;
} );
```

## Types of changes

* Added a filter in the `gutenberg_experimental_global_styles_get_stylesheet` function's return.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by nosolosw** [comment]
:wave: I have two thoughts about this:

- While we need to add hooks https://github.com/WordPress/gutenberg/issues/27504 I rather not do it until things are more stable. Use cases are very welcome, though

- What you want to do in this particular case is not to enqueue unused fonts, correct? This sounds like something core should do instead of letting plugins/themes to deal with it. Would you be interested in taking a stab at this? IIRC Jorge may have left some ideas on the original PR https://github.com/WordPress/gutenberg/pull/24868

**Comment by aristath** [comment]
> What you want to do in this particular case is not to enqueue unused fonts, correct?

Correct

> This sounds like something core should do instead of letting plugins/themes to deal with it. 

The problem is that core doesn't have a method to load fonts... As a result plugins & themes are forced to deal with it anyway and re-invent the wheel every time. There have been proposals to add an API to allow loading webfonts with a consistent method, but that's a big project on its own and will probably take a long time before something can land in core.
I'd love to take a stab at this, but that can't happen until core has something we can actually use :wink:

**Comment by aristath** [comment]
Rebased the PR and fixed a conflict, this is now again ready for a review.

**Comment by oandregal** [comment]
In https://github.com/WordPress/gutenberg/pull/34843 I'm asking people for thoughts about consolidating parts of the global styles API, particularly the API for themes & plugins to get access to the data from `theme.json`. I'd argue we should wait for those conversations to settle before we create any filters.

**Pull request closed without merging**
