### PR TITLE
Replace metabox arrows with Dashicon chevrons for greater consistency. 

### PR DESCRIPTION
**Pull request by kjellr**
This is a half-step towards closing #15881. 

---

The expand/collapse arrows for custom meta boxes are currently not in sync with the Material chevron icons used in the rest of Gutenberg: 

Screen Shot 2019-06-11 at 3 56 34 PM

This is because the arrows are Dashicons, brought in via core's `common.css`. Since we don't have an iconfont version of the usual expand/collapse arrows we use in Gutenberg, this PR pulls in the closest Dashicon alternatives: 

Screen Shot 2019-06-11 at 3 53 16 PM

The Dashicon chevrons are _almost_ the same as the ones we use. Considering how similar they are (and how small the icons are here), I think it makes sense to switch to these ones until we can implement a more permanent fix. 

Untitled-1

### CODE REVIEW

**Comment by jasmussen** [comment]
I do kind of wonder if a half step makes sense. I kind of think no-one but you and me will notice that the dashicon isn't the same as the material chevron. At the same time, it does bug me :D 

But I also don't want to block this PR as it's a good step towards consistency, so on that note I wouldn't object. But I still wonder, what would it take to make the full step?

**Comment by kjellr** [comment]
> But I still wonder, what would it take to make the full step?

I'm not totally sure. It appeared to me that those controls are basically just inherited from WP-Admin. I _think_ someone would have to rebuild with pure Gutenberg components, which doesn't seem like a huge priority for us at the moment? I wonder if @youknowriad or @noisysocks has some idea (I see they've worked on the `meta-boxes-area` component before).  

Also, @jasmussen, another option would be to swap out the existing chevrons with Material ones in Dashicons itself... we're already using an incongruent one for [the back button in fullscreen mode](https://github.com/WordPress/gutenberg/pull/13403#issue-246342236), and I can't think of a great argument for why they should be slightly different.

**Comment by jasmussen** [comment]
> Also, @jasmussen, another option would be to swap out the existing chevrons with Material ones in Dashicons itself... we're already using an incongruent one for the back button in fullscreen mode, and I can't think of a great argument for why they should be slightly different.

There's a larger discussion there, largely [summarized in this comment](https://github.com/WordPress/gutenberg/issues/9647#issuecomment-456738147), which suggests mostly that path for WordPress as a whole, Material icons plus dashicons to fill in the gaps. But Dashicons as they are today are incompatible because of the smaller (20x20) pixel grid than Material (24x24). 

The real solution is of course to refactor out the use of Dashicons in that particular metabox instance, but I would agree that's a larger undertaking.

In any case, no _real_ objections, just good to muse about this! :)

**Comment by noisysocks** [comment]
In theory, fixing this for reals should just be a matter of changing the `<span>` here to be a `<svg>`:

https://github.com/WordPress/wordpress-develop/blob/5fea17ba03c42d16a6517b164d3437bd53ac8ac9/src/wp-admin/includes/template.php#L1277

So, something like:

```php
if ( $current_screen->is_block_editor() ) {
	echo '<svg class="toggle-indicator" aria-hidden="true"><path>...</path></svg>';
} else {
	echo '<span class="toggle-indicator" aria-hidden="true"></span>';
}
```

This would have to be done in Trac and not here in the Gutenberg repo.

**Comment by chrisvanpatten** [comment]
I think a good clarifying question here is asking how the project leads see the future of meta boxes?

My interpretation was that meta box support in Gutenberg was provided primarily as a way to ease a transition to more Gutenberg-y implementations (e.g. sidebar API, blocks, etc). If that is still the case, they are effectively a deprecated feature and I’m not sure it makes sense to make accommodations and affordances for them. The slight design variations are a reminder that they are _not_ native to Gutenberg, and they can (and will) behave differently from other elements of the interface.

**Comment by noisysocks** [comment]
cc. @youknowriad

**Comment by mapk** [comment]
> If that is still the case, they are effectively a deprecated feature and I’m not sure it makes sense to make accommodations and affordances for them. The slight design variations are a reminder that they are not native to Gutenberg, and they can (and will) behave differently from other elements of the interface.

This is a fair discussion and good points being raised. I'd agree that they will be deprecated at some future point. But this time is probably a ways off still. For this reason, I would love to see them more aligned to the Gutenberg interface + icons. The quick change to Dashicons chevrons works for me here as providing a bit of consistency in the interim. I'd avoid going to Trac with this in Core.

**Comment by chrisvanpatten** [comment]
I guess I'll just voice my objection again — WordPress has a long history of pulling code into the future far beyond its usefulness. With the recent addition of a SlotFill which now allows truly Gutenberg-native panels in the Document Settings panel, there is finally a full end-to-end migration path for custom metaboxes. With this new addition, there is very little justification for someone to use legacy metabox code, and I think making a design affordance for the legacy approach is a mistake.

**Comment by kjellr** [comment]
> I guess I'll just voice my objection again — WordPress has a long history of pulling code into the future far beyond its usefulness. With the recent addition of a SlotFill which now allows truly Gutenberg-native panels in the Document Settings panel, there is finally a full end-to-end migration path for custom metaboxes. With this new addition, there is very little justification for someone to use legacy metabox code, and I think making a design affordance for the legacy approach is a mistake.

I definitely appreciate the sentiment of the objection here, and we definitely want folks to natively implement their custom meta boxes.

But from a user's perspective, the user generally wouldn't know or care if these boxes are using a legacy approach or not. They look similar enough to the rest of the editor that the inconsistency in the expand/collapse arrows reads as just a design oversight. It's all just a single interface, in the eyes of the user.

**Comment by paaljoachim** [comment]
A few comments as I see it.
Do please switch out the metaboxes arrows with the ones used other places such as the sidebar.

Metaboxes are very likely still used by a lot of users in probably many different ways. We still need to continue the support for a few (likely a bunch) years and perhaps find a way to create a better transition of the older code used in the metaboxes to a call it version 2 metaboxes. 
This is a potential discussion for another time. 

Go go.... get the new arrows in place for the metaboxes..:)

**Comment by draganescu** [comment]
I also approve of this, and while I understand @chrisvanpatten 's perspective it does look like an unfinished job to the user. @kjellr did anything new happen in the meantime (new UI, icons etc) that should prevent us from merging this?

**Comment by kjellr** [comment]
> did anything new happen in the meantime (new UI, icons etc) that should prevent us from merging this?

Yeah, the chevron icon has changed, so the dash icon one is less of a decent replacement. The difference is more obvious, but it's still better than what's there today. I'd get some feedback from @mapk or @jasmussen on whether this is an improvement or not.  


Current: 

Screen Shot 2020-04-22 at 8 58 15 AM


This PR: 

Screen Shot 2020-04-22 at 8 54 44 AM

**Comment by jasmussen** [comment]
Thanks for keeping on this. This has been out of mind for me for a while. Since then with some of the G2 efforts, I've been wanting to look at panels, and try to reduce borders and icons whenever possible. I don't have a clear picture of how the sidebar could be refined, but the short is that I would expect it to change further with some of the G2 designs Pablo created in #18667. So we may want to keep this one sitting for a while further :|

Alternately — what would it take to fix the problem at the root? Actually use the Icon component, or just bake in the SVGs, in the metabox panels themselves?

**Comment by annezazu** [comment]
Closing this out due to lack of activity and the age of this effort. Feel free to reopen or create a new PR if folks want to continue this work.

**Pull request closed without merging**
