### PR TITLE
Fix issues causing the cover block to black out with a fixed background

### LINKED ISSUE #28557: Changing alignment of the cover block when set to fixed position breaks image
## Description
Originally reported by @Azragh [here](https://github.com/WordPress/gutenberg/pull/28499#issuecomment-768882756). There are issues with the cover block losing the background image when some settings are changed or the block is duplicated with ctrl + shift + D.  

I have verified both that this is happening for me, but that it is unrelated to the changes in #28499. (I reverted those changes locally and it was still happening) I know @jasmussen has been working through some issues with the cover block, so possibly related to those?

## Step-by-step reproduction instructions

1. Create a new post
2. Add a cover block with a background image
3. Toggle the "fixed background" option
4. Change the alignment of the cover to be aligned left
5. See that the background of the cover is now just the color black

## Expected behaviour
That the background image remains when the alignment is changed

## Actual behaviour
The background image disappears when the alignment is changes

## Screenshots or screen recording (optional)
8B2sQItjxU

## WordPress information
Latest master using local wp-env environment

## Device information
- Device: Desktop
- Operating system: Mac OS Catalina
- Browser: Chrome  88.0

### PR DESCRIPTION
**Pull request by brentswisher**
## Description
Fixes #28557. There were actually two things that were happening to cause the problem:

### First Issue
The CoverEdit component was setting a background using both `background: ` and `backgroundImage:` This was causing a console error(See below), and is [know to cause inconsistent styling](https://reactjs.org/blog/2020/02/26/react-v16.13.0.html#warnings-for-conflicting-style-rules).
```
react_devtools_backend.js:2430 Warning: Removing a style property during rerender (backgroundImage) when a conflicting property is set (background) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
    in div (created by CoverEdit)
    in CoverEdit (created by WithInstanceId(CoverEdit))
```

### Second Issue
Ironically, once I fixed that, ANY background image with the "fixed background" option was hidden. This is because when setting the styles, after the line setting the backgroundImage for the background, there was a line possibly setting a backgroundImage for a gradient. This was correctly checking for an image background to prevent a gradient from getting set, but was incorrectly setting backgroundImage to undefined if the condition failed - overwriting the existing backgroundImage with `undefined`.

## How has this been tested?
Add a Cover block with an image background
Observe you can toggle a fixed position, change the block alignement, and the background image still displays
Also, observe there are no longer warning in the console

## Screenshots
jPFTq3qKWu

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Confirmed, this works well for me. This could use some eyes, CC: @WordPress/gutenberg-core

**Review by draganescu — APPROVED** [review]
Tested this and works as described and I like the small reduction in logic for applying the style.

**Review by aristath — APPROVED** [review]

**Comment by nosolosw** [comment]
Tested this myself and the code looks fine, so I'm going to go ahead and merge this to release the RC.

**Comment by Azragh** [comment]
Almost fixed. But if I reload the Page with F5 it's still the same. Mentioned it [here](https://github.com/WordPress/gutenberg/pull/28499#issuecomment-768882756).

**Comment by nosolosw** [comment]
:wave: @Azragh I've tried to reproduce as per your instructions and I couldn't. Could you create an issue with the specific steps to reproduce this and also information about your browser, Gutenberg version, and WordPress versions in use?

**Comment by ockham** [comment]
Cherry-picked to `release/9.8`.

**Comment by brentswisher** [comment]
@Azragh - it looks like what you are referencing is the same problem reported in #28425 which I have just verified is fixed in the latest version of the master branch. If you are still having it happen even with the latest version of master, you can comment on that issue with the information @nosolosw requested above and I can re-open it and take a look. Thanks!

**Pull request merged**
