### PR TITLE
Raw Handling - msListIgnore - Check attributes are valid

### PR DESCRIPTION
**Pull request by geriux**
## What?
Fixes some edge cases where there are invalid attributes in the `style` attribute. Ideally, there should only be valid values but it looks like this is not the case with MS Word.

## Why?
There are some [crash reports](https://github.com/wordpress-mobile/gutenberg-mobile/issues/6782
) in the mobile editor related to this code.

## How?
By checking both `key` and `value` are not `undefined`.

## Testing Instructions

Paste the following snippet into the Web or Mobile editor:

```html
<p class=MsoListParagraphCxSpFirst style='text-indent:-18.0pt;mso-list:l0 level1 lfo1'><span
style='mso-bookmark:_Hlk64885792'><![if !supportLists]><span style='font-family:
Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore; invalid-style'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>One <o:p></o:p></span></p>
```

### Testing Instructions for Keyboard
N/A, does not apply.

## Screenshots or screencast 

Web Editor Before|Web Editor After
-|-
<kbd>Screenshot 2024-04-02 at 15 31 06</kbd>|<kbd>Screenshot 2024-04-02 at 15 30 33</kbd>

Mobile Editor Before|Mobile Editor After
-|-
<kbd>Screenshot 2024-04-02 at 15 31 06</kbd>|<kbd>Screenshot 2024-04-02 at 15 30 33</kbd>

### CODE REVIEW

**Comment by ellatrix** [comment]
Should we add that snippet to the integration tests? Where does that "invalid-style" come from?

**Review by ellatrix — APPROVED** [review]

**Comment by geriux** [comment]
> Should we add that snippet to the integration tests? 

Good idea! I'll add that!

> Where does that "invalid-style" come from?

Unfortunately, I couldn't find a real case for the reproduction steps so I added `invalid-style`

**Comment by ellatrix** [comment]
I mean, if it's not real HTML that comes from MS Word, then no need to add an integration test. I thought their markup changes and that is causing a failure.

**Review by twstokes — APPROVED** [review]
LGTM @geriux! 🙇

**Pull request merged**
