### PR TITLE
Merge two similar strings.

### PR DESCRIPTION
**Pull request by dimadin**
There are two tooltips of the same toolbar icons that differ only in capitalization of second word.

This PR uses Title Case for both, however, I am not sure what case should be used because it's inconsistent. Other icons use Sentence case, but this _pencil_ icon (Edit) uses both Title Case (Edit Gallery, Edit Table) and Sentence case (Edit image).

screen shot 2018-11-10 at 12 59 34
screen shot 2018-11-10 at 12 58 28

### CODE REVIEW

**Comment by ocean90** [comment]
My vote would be for sentence case.

**Comment by michelleweber** [comment]
Good catch -- tooltips like this should be sentence case.

**Comment by dimadin** [comment]
Then we should also review toolbar tooltips in other blocks (like I mentioned, already saw _Edit Gallery_ and _Edit Table_).

**Comment by gziolo** [comment]
@dimadin can we update the other one as discussed? :)

**Comment by dimadin** [comment]
@gziolo Done. Should we also change instances I mentioned above, or that can wait?

**Comment by gziolo** [comment]
Yes, please as it was already raised and is similar to the change you are about to introduce 👍

**Comment by dimadin** [comment]
New pull request or this one?

**Review by gziolo — APPROVED** [review]
Let's merge this one and open another one referencing this 👍

**Pull request merged**
