### PR TITLE
Remove feature flag for mobile page templates

### LINKED ISSUE #1962: Make SPTs(Layouts) public
Let's remove the feature flag and open SPTs(Layouts) for public usage.

### PR DESCRIPTION
**Pull request by koke**
We are ready to launch Starter Page Templates on mobile (#18055). Since we ended up with a mobile-only implementation for now, I'm removing the feature flag

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1962

gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1987
gutenberg PR: https://github.com/WordPress/gutenberg/pull/20718
WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13595
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11409

cc @iamthomasbishop

### CODE REVIEW

**Comment by koke** [comment]
The envelope emoji is not looking right on Android:

Screenshot_20200309-125151

**Comment by koke** [comment]
On Android (Moto G5 Plus), if I focus on the paragraph, the border overlaps the template picker:

Screenshot_20200309-133235

**Comment by pinarol** [comment]
> On Android (Moto G5 Plus), if I focus on the paragraph, the border overlaps the template picker:

I thought this was already discussed when we drop the first design which had the buttons under the paragraph block. Because this is pretty much an expected result of sticking the buttons to the keyboard. When the viewport is small things will overlap, same in the landscape mode:

IMG_3619

BTW I think in reality it is more clear that the picker buttons are moving with the keyboard, so the overlapping didn't feel that buggy to me, also, I was able to close the keyboard. 

However, could we use a similar approach to "BlockInsertionPoint" to show the picker buttons? So we'd completely avoid overlapping? @koke

**Review by pinarol — APPROVED** [review]
LGTM! Tested with WPiOS, WPAndroid. 

- [x] Apply/cancel template WPiOS
- [x] Apply/cancel template WPAndroid
- [x] Dark mode WPiOS
- [x] Checked template contents&emojis on WPiOS
- [x] Checked template contents&emojis on WPAndroid

Let's also get a 👍 from @iamthomasbishop

**Comment by koke** [comment]
> When the viewport is small things will overlap

That makes sense, I think what I found surprising was the border above the buttons. I would expect the border to have scrolled behind the picker, or even the block to have a white background that partially covered the picker. This way it looks like something is wrong in the Z axis

**Comment by pinarol** [comment]
Or, it can be a result of transparency. I observe that on iOS the border is below the buttons:

IMG_3620

On Android I am not able to get to a similar state because the screen is too small in Landscape mode, and too big in Portrait.

**Comment by iamthomasbishop** [comment]
@koke along with the landscape feedback @pinarol mentioned above, here is some feedback from  my initial spin through the test build:

## UI

* Can we add ~12px of padding at the top of the page content? I believe we are applying additional padding on top of the post/page title in the editor, so this would align with that (example: https://cloudup.com/cbMvzmdHb6a)
* The App Bar seems a bit too tall compared to the native one (~9 or 10px too tall). Can we shorten it up slightly to align more with the native one? I believe 56px tall should work across platforms (example: https://cloudup.com/c-hVuBGgeVv)
* [iOS] Dark Mode: border-bottom on the navigation bar is a bit too strong. We can probably dim it down a bit?
* [iOS] Dark Mode: I wonder if we should apply a dark gray bg on the Navigation Bar to match the native one. Thoughts @kokejb?
* Can we display a Snackbar/Notice briefly after the template is applied? Something like this: https://cloudup.com/cDYvDtvc38y
* Can we apply a 300ms fadeOut to the inline picker buttons when they disappear?
* When title already exists, applying the template shouldn’t override the existing title

## Blocks

* Lack of alignment controls on Button block feels weird (example: https://cloudup.com/cIR3RJqFDNm)
* Can we remove the dashed borders from Spacer blocks on the Template Preview? They feel unnecessary during preview
* Should images on image blocks be full-width? (Example: https://cloudup.com/c3c0uNa5Ncx)
* On Services layout: This is my fault because I prepped the contents, but the Spacer below Focus section should be 24px, not 32 (example: https://cloudup.com/c7pv9iOZjR4)

**Comment by pinarol** [comment]
> Lack of alignment controls on Button block feels weird (example: https://cloudup.com/cIR3RJqFDNm)

I am a bit confused about this one because we had decided this way: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1790#issuecomment-584301584 This doesn’t necessarily mean we should change that plan, right? @iamthomasbishop

**Comment by koke** [comment]
> here is some feedback from my initial spin through the test build

Thanks for the detailed feedback @iamthomasbishop. Could you specify which ones would you consider blockers? There are some of those that seem like quick fixes, but others would be more challenging and probably handled better as a second iteration on it. Particularly:

> Can we display a Snackbar/Notice briefly after the template is applied?

It seems doable, but I don't recall having a similar thing anywhere in gutenberg-mobile, so we'd have to build the component, or bridge the existing native one.

> Can we apply a 300ms fadeOut to the inline picker buttons when they disappear?

I haven't done any animations so far. My understanding is that this would be relatively easy, but we might be in for a surprise 😅 

> Lack of alignment controls on Button block feels weird

I imagine we'd just have to update the templates to use buttons when https://github.com/WordPress/gutenberg/pull/20191 is merged

> Can we remove the dashed borders from Spacer blocks on the Template Preview?

Removing them on preview only might complicate things. Could we remove them in all cases?

> Should images on image blocks be full-width?

I'm seeing them full width on my iPhone. Do you get that behaviour consistently? 🤔

**Comment by iamthomasbishop** [comment]
> Could you specify which ones would you consider blockers?

@koke Honestly, I wouldn't consider any of them "complete" blockers. And while I obviously would prefer to solve as many as possible prior to shipping, here are the few that I would like to be solved prior to shipping if were to ship today (in order of priority):

* Lack of alignment controls on Button block feels weird (example: https://cloudup.com/cIR3RJqFDNm)

* Should images on image blocks be full-width? (Example: https://cloudup.com/c3c0uNa5Ncx)

* On Services layout: This is my fault because I prepped the contents, but the Spacer below Focus section should be 24px, not 32 (example: https://cloudup.com/c7pv9iOZjR4)

* When title already exists, applying the template shouldn’t override the existing title

------------

### Your Questions

> It seems doable, but I don't recall having a similar thing anywhere in gutenberg-mobile, so we'd have to build the component, or bridge the existing native one.

Ok, fair enough. I was hoping we'd be able to bridge to the existing component, but if not let's not worry about it.

> I haven't done any animations so far. My understanding is that this would be relatively easy, but we might be in for a surprise 😅

Sounds good. Honestly, it's not anything critical, but it may be a nice little improvement if it doesn't require a bunch of work 😄 

> I imagine we'd just have to update the templates to use buttons when #20191 is merged

That's right, should have mentioned that in my previous comment (cc @pinarol, as you were asking [here](https://github.com/WordPress/gutenberg/pull/20718#issuecomment-597037763)).

> Removing them on preview only might complicate things. Could we remove them in all cases?

I think we could remove the dashed borders for the static state of the Spacer block altogether, but I don't feel _super_ strongly about it. I was thinking the dashed border would be useful to provide a clear tap target and an indication as to what is taking up that space, rather than just have whitespace, but now it kinda feels unnecessary and repetitive in most cases. With that said, it's not specific to this feature, so maybe we can consider it separately.

> I'm seeing them full width on my iPhone. Do you get that behaviour consistently? 🤔

I should have been a little more specific — I'm seeing this only on the Team template, and testing primarily on an iPhone 11 Pro. [This is what I'm seeing](https://cloudup.com/cbwpHiZqS6u) (in the template preview and in the editor once applied). FWIW, on iPad (full-screen and split-view) the images span the full viewport width. 🤷‍♂ 

-------

### Other questions

* Do we expect the Cover block to be merged in time for us shipping this? If so, we might also want to consider utilizing it in the templates (if we feel compelled to do so)

**Comment by pinarol** [comment]
> Do we expect the Cover block to be merged in time for us shipping this? If so, we might also want to consider utilizing it in the templates (if we feel compelled to do so)

@iamthomasbishop We added gradient and video background support as well! 🎉 But we'll need a final design review from you for removing the DEV flag, so I am not certain about when it can be publicly available yet.

**Comment by koke** [comment]
> I'm seeing this only on the Team template, and testing primarily on an iPhone 11 Pro. This is what I'm seeing (in the template preview and in the editor once applied).

That's what I understood, but I'm seeing something different. I tried with the iPhone 11 Pro simulator in case it was device specific, but I'm still seeing them full width. https://cloudup.com/c0j0S2N5xvs

I'm not sure what's going on but maybe there was some glitch calculating the image sizes and now it's cached? Can you try uninstalling the build and installing again and see if it's still happens.

I'm not sure what else to try, since I can't make it happen 😞

**Comment by iamthomasbishop** [comment]
> That's what I understood, but I'm seeing something different. I tried with the iPhone 11 Pro simulator in case it was device specific, but I'm still seeing them full width. https://cloudup.com/c0j0S2N5xvs

Very interesting 🤔 I've been bouncing between various alpha builds, so I don't think re-installing will solve anything — but I'll give it a try!

**Comment by koke** [comment]
I'm going to go ahead with this PR and move all the items to separate issues.

> On Services layout: This is my fault because I prepped the contents, but the Spacer below Focus section should be 24px, not 32

Fixed here in https://github.com/WordPress/gutenberg/pull/20718/commits/ab3ea1a96edc1ea85d125bfac123bbe28ad91f61


> - Can we add ~12px of padding at the top of the page content? I believe we are applying additional padding on top of the post/page title in the editor, so this would align with that (example: https://cloudup.com/cbMvzmdHb6a)
> - The App Bar seems a bit too tall compared to the native one (~9 or 10px too tall). Can we shorten it up slightly to align more with the native one? I believe 56px tall should work across platforms (example: https://cloudup.com/c-hVuBGgeVv)
> - [iOS] Dark Mode: border-bottom on the navigation bar is a bit too strong. We can probably dim it down a bit?
> - [iOS] Dark Mode: I wonder if we should apply a dark gray bg on the Navigation Bar to match the native one. Thoughts @kokejb?
> - Can we apply a 300ms fadeOut to the inline picker buttons when they disappear?

https://github.com/wordpress-mobile/gutenberg-mobile/issues/2012

> - When title already exists, applying the template shouldn’t override the existing title

Moved to https://github.com/wordpress-mobile/gutenberg-mobile/issues/2013

> - Can we display a Snackbar/Notice briefly after the template is applied? Something like this: https://cloudup.com/cDYvDtvc38y

I understand we're not doing this for now?

> - Lack of alignment controls on Button block feels weird (example: https://cloudup.com/cIR3RJqFDNm)

It should resolve once buttons block ships, although it'll require updating the templates

> - Can we remove the dashed borders from Spacer blocks on the Template Preview? They feel unnecessary during preview

@iamthomasbishop I'm not sure if we made a decision here

> - Should images on image blocks be full-width? (Example: https://cloudup.com/c3c0uNa5Ncx)

Still investigating, I can't reproduce the issue

**Comment by iamthomasbishop** [comment]
> I understand we're not doing this for now?

(re: snackbar) That's correct.

> I'm not sure if we made a decision here

(re: removing dashed borders from static Spacer blocks)

I think we can handle that separately, as an iteration on the Spacer block itself.

**Pull request merged**
