### PR TITLE
Update sidebar titles for Template and Page management data views

### LINKED ISSUE #56199: DataViews: Frame title should match current view
For instance in this view:

Screenshot 2023-11-16 at 10 22 04

The frame title should be "Drafts" instead of "Pages":

Screenshot 2023-11-16 at 10 23 09

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Update the titles in the sidebar for the manage pages, and manage template pages.

## Why?
There currently exists some inconsistencies, and awkward repetition. This can be observed in the screenshots below:

manage

Note:

* Repeated "Pages" title in both sidebars, and in the content frame. This is inconsistent with Templates.
* "All templates" repeated in the sidebar title and the default view label.

## This PR

manage

In this PR all the titles / labels follow a consistent convention:

* Main sidebar title is "Pages" / "Templates".
* In the management view, the sidebar title is "Manage pages" / "Manage templates" rather than "Pages" / "All templates"
* Content frame matches the main sidebar title, IE "Pages" / "Templates".

The last point is not ideal, but it's a reasonable temporary state until we untangle the details necessary to close #56199.

### CODE REVIEW

**Review by juanfra — APPROVED** [review]
Thanks for working on this, James!

The fix works as expected.

https://github.com/WordPress/gutenberg/assets/252415/4a4bea6b-1161-474b-839a-e4d67b1c1737

**Comment by oandregal** [comment]
With this PR, when I visit each entity in Site Editor I'd see in the sidebar:

| Entity | Sidebar title |
| --- | --- |
| Navigation | "Navigation" |
| Styles | "Styles" |
| Pages | "Manage pages" |
| Templates | "Manage templates" |
| Patterns | "Patterns" |
| Template Parts | "All template parts" |

**Comment by jameskoster** [comment]
@oandregal you should only see "Manage pages" and "Manage templates" when you click the "Manage all pages" or "Manage all templates" links respectively. 

Thanks for pointing out template parts, they should match. I'll push an update for that.

**Comment by t-hamano** [comment]
Personally, I feel uncomfortable with this change 😅 I feel that the sidebar title should say "what this page is about" and should not include any actions. I feel that it is better to limit text containing "Manage" to elements that request some kind of action, such as links and buttons.

I'm thinking that maybe the "Manage XXX" button itself is unnecessary.

For example, taking templates as an example, the current flow looks like this:

- At the root of the site editor, click "Template".
- The sidebar displays a list of all templates, including custom templates.
- Click the "Manage all templates" button and the canvas will render all templates via the data view.

This means that two clicks are required for the user to actually "manage" the template.

Theoretically, I predict that if we display the data view directly when you click "Templates" menu at the root of the site editor, there will be no problem. The data view covers all functionality and also allows us to switch to the experimental list layout to preview the canvas. We can also add new templates using the button on the top right.

If we could eliminate this double screen, I think there would be no need to worry about what to do with the title of the sidebar like we did this time.

However, if we were to proceed with this approach, I think we would also need to resolve the routing issue in mobile views, as was attempted in #59014.

cc @youknowriad

**Comment by jameskoster** [comment]
> Theoretically, I predict that if we display the data view directly when you click "Templates" menu at the root of the site editor, there will be no problem.

I believe that is the intention for 6.6 and beyond, but it isn't going to happen in time for 6.5, so we're left with these inconsistencies / peculiarities:

* The are currently _two_ sidebars with the title "Pages".
* The sidebar title for page management is inconsistent with the sidebar title for template / template part management.

If I am understanding your feedback correctly, the concern is more about the chosen titles, "_Manage_ Pages", etc? I feel these titles describe what the pages are generally about, and of course match the preceding links. IE "Manage all pages" goes to a page titled "Manage pages".

I'm totally open to alternative titles though if you have a suggestion. If the duplication isn't a concern then an alternative approach would be to rename the template / template part management sidebars to "Templates" and "Template parts" respectively. 

There's no _perfect_ solution here really, but it would be nice to polish the 6.5 experience a little if possible.

**Comment by richtabor** [comment]
A bit of an aside, but it feels like we're adding multiple layers without much benefit. 

For example, the "manage pages" view is nice, but when would you see it? What's the benefit to seeing it in its own view rather than using the sidebar of the previous view with the list of pages? If it's the added actions, we could add a vertical ellipsis with delete, duplicate, view in a new tab. Is that the plan eventually?

**Comment by t-hamano** [comment]
Ah, I overlooked that this was an improvement for WP6.5. If so, what do you think of the following configuration?

- Desigin
  - Navigation
  - Styles
  - Pages
    - All pages 
  - Templates
    - All templates
  - Patterns
    - All template parts 

In other words, the sidebar title that appears after clicking the "Manage all XXX" button will be "All XXX."

**Comment by youknowriad** [comment]
I don't have a strong preference between "manage" and "all" but I agree that we should be consistent here.

As for the two layers, yes, we all agree that it's largely unnecessary but we're doing this because:

 - The list view flows are not ready yet to be included in 6.6 and we will continue iterating with the goal of unifying both pages.
 - These manage pages exist (at least for template) in 6.4.

**Comment by jameskoster** [comment]
> If it's the added actions

It's also;

* Access to the bundled views; "Drafts", "Trash". 
* Avoiding duplicate page lists visible at the same time (one in the sidebar and one in the content area).

> In other words, the sidebar title that appears after clicking the "Manage all XXX" button will be "All XXX."

I don't mind "All", but lean slightly towards "Manage" because otherwise the sidebar title and the default view label would match. I worry that might lead to some confusion?

Screenshot 2024-02-19 at 14 39 32

**Comment by t-hamano** [comment]
I see, that's certainly difficult to understand 😅 After all, "Manage" may be better.

Could you resolve the conflict so that we can move forward with this PR? This PR makes changes to files that no longer exist in trunk, but I think the following is the new changes that should be made. Sorry for confusing you 🙏
https://github.com/WordPress/gutenberg/blob/0dc55a842ae9d124601ae6577c4ff5f24898f428/packages/edit-site/src/components/sidebar/index.js#L77

**Comment by t-hamano** [comment]
@jameskoster Thanks for the update!

For some reason, in the PR after rebasing, it seems that the change in title also affects the title of the sidebar item. There may have been some changes in the trunk, so I'll look into it a bit.

Templates:

image

Template parts:

image

✅ Pages:

image

**Comment by t-hamano** [comment]
@oandregal @ntsekouras,

I added a new `contentTitle` to the `config` to correctly display the title of the sidebar screen (e.g. "Manage templates") and the title of the first item in the dataview (e.g. "All templates") separately.

It seems to be working as expected, could you confirm if this approach is correct?

https://github.com/WordPress/gutenberg/assets/54422211/c9a1d77d-9aab-4336-bd93-912c2c9fd39c

**Comment by jameskoster** [comment]
I can't comment on the method, but can confirm this is now working as expected for me.

**Comment by t-hamano** [comment]
I would like to add this PR to the editor tasks project board to ensure it ships to WP6.5.

**Review by ntsekouras — APPROVED** [review]
LGTM, thanks! I'm not loving the `contentTitle` name, but I don't think it matters much and that it's fine to land for 6.5.

**Comment by t-hamano** [comment]
P.S. Currently, GitHub Actions seem to be failing due to an issue with the latest version of mariadb.

See: https://wordpress.slack.com/archives/C02QB2JS7/p1708499504613749

**Comment by annezazu** [comment]
Was reviewing this for triage and saw it was ready to merge. Moving ahead so we get it into 6.5.

**Comment by getdave** [comment]
I just cherry-picked this PR to the cherry-pick-wp-6-5-beta-3 branch to get it included in the next release: 3c1c03ac5d

**Pull request merged**
