### PR TITLE
Add Testimonials block pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a 'Testimonials' block pattern for #20345.

Screen Shot 2020-03-13 at 15 56 43

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. Let me know if you think it can be improved or if we should close this PR instead.

**Comment by mapk** [comment]
@enriquesanchez if you make those images circular instead square, I think this one is good to merge.

**Comment by enriquesanchez** [comment]
>if you make those images circular instead of square, I think this one is good to merge.

@mapk I'm using the 'Media & Text' block, which oddly enough does not allow to change the style of images from squared to circular.

I'll try using a column block instead.

**Comment by enriquesanchez** [comment]
@mapk pushed an update:

Screen Shot 2020-04-14 at 17 36 02

**Comment by mapk** [comment]
@enriquesanchez, the colors feel a bit much. Maybe it's the hues? Let's try this pattern without any color and begin there.

**Comment by enriquesanchez** [comment]
@mapk Updated colors:

Screen Shot 2020-04-27 at 13 41 17

**Review by mapk — APPROVED** [review]
Let's merge it. With the possibility that Core may not roll out with patterns ourselves, let's at least get some in to fiddle with. This is a good one. 👍

**Comment by enriquesanchez** [comment]
Thanks @mapk!

Looks like I need to rebase this one first. I'll merge once all of that is done.

**Pull request merged**
