### PR TITLE
FSE -  Follow-up to #25995: Use `WP_Theme::get_stylesheet` instead of the private property.

### PR DESCRIPTION
**Pull request by fklein-lu**
## Description
As noted in [this comment](https://github.com/WordPress/gutenberg/pull/25995/files#r504983933) on PR #25995, the `WP_Theme::get_stylesheet()` method should be used instead of of accessing the private property.

Code like `wp_get_theme()->stylesheet` only works because it is implemented as part of the `__get()` method. PHP IDE's and code analysis tools will flag this as a pattern to avoid.

## How has this been tested?
Manually tested by verifying that template parts are still correctly being displayed on the frontend.

## Types of changes
PHP code style enhancement.

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
Thanks for picking this up, it looks good and works well in testing.  

I noticed another place that we forgot to update from using `textDomain` that may be worth adding in the changes here:
https://github.com/WordPress/gutenberg/blob/d7014b5f043001225a7d108287dcf5b13d159147/lib/template-parts.php#L249

There it is still using `textDomain` as the theme name when creating a draft of the template part.  It has been working fine in testing since for these block based themes textDomain is currently set up to be the same as the stylesheet name, but we should probably make it consistent. 😁

**Comment by fklein-lu** [comment]
Good catch! Updated as suggested.

**Review by Addison-Stavlo — APPROVED** [review]
This works well for me, thanks!

note - the e2e failures seem unrelated and are failing the same on other PRs atm as well.

**Review by vindl — APPROVED** [review]
Nice catch!

**Comment by gziolo** [comment]
Can you rebase this PR? @Addison-Stavlo or @vindl – it's fine to merge approved PRs for contributors that aren't members of the project and can't really do it themselves 😄

**Comment by fklein-lu** [comment]
Messed up that rebase, clean PR in #26539.

**Comment by Addison-Stavlo** [comment]
> @Addison-Stavlo or @vindl – it's fine to merge approved PRs for contributors that aren't members of the project and can't really do it themselves 😄

Oops!  Yes, i completely overlooked that.  Will do. 👍

**Pull request closed without merging**
