### PR TITLE
Add theme support for custom palettes and shared "ColorPalette" component

### PR DESCRIPTION
**Pull request by mtias**
image

Done via:

```php
add_theme_support( 'gutenberg', array(
	'colors' => array(
		'#A156B4',
		'#D0A5DB',
		'#EEE',
		'#444',
	),
) );
```

### CODE REVIEW

**Review by karmatosed — COMMENTED** [review]
This looks really good. My only thought would be can somehow it be indicated the order the colors appear? I know it doesn't matter but for some it will visually matter, maybe just a comment in code?

**Comment by mtias** [comment]
The order would be the order in the array. Do you mean to clarify that?

**Comment by karmatosed** [comment]
@mtias yes I think clarifying it is good, perhaps just a code comment though.

**Review by melchoyce — APPROVED** [review]
Great idea, seems easy for themers to implement. 👍

Any way we could also have it support Sass color variables somehow?

**Review by youknowriad — APPROVED** [review]
Awesome feature, code looks good.

Looks like there's a small phpcs error

**Pull request merged**
