### PR TITLE
Default Block Appender: Remove redundant event handlers

### PR DESCRIPTION
**Pull request by aduth**
Related: https://github.com/WordPress/gutenberg/pull/3623#discussion_r170792860

This pull request seeks to remove two of the three event handlers from the `DefaultBlockAppender` component: `onClick` and `onKeyDown`. This operates on the assumption that it is not possible to click or keydown the input without the `onFocus` event already having been handled, incurring the replacement of the default block.

**Testing instructions:**

Verify there are no regressions in the behavior of the default block appender.

Ensure end-to-end tests pass:

```
npm run test-e2e
```

### CODE REVIEW

**Comment by youknowriad** [comment]
The input has "role" button and in Firefox I think, buttons don't get the focus when you click on them, so might be good to check. I can do it a bit after.

**Comment by aduth** [comment]
>buttons don't get the focus when you click on them, so might be good to check

Interesting to note and, if true, would be good to leave a comment clarifying this, as it's not obvious at a glance. I should clarify part of the goal here is to sanity check myself in asking "Is it possible to click a button without also causing it to receive focus?"

**Comment by youknowriad** [comment]
Related https://gist.github.com/cvrebert/68659d0333a578d75372

**Comment by aduth** [comment]
Yeah, just rediscovered this one as well. The difference is that this is not a `button` element, it's an `input` (`type="text"`) with role of button. In brief testing in Firefox, it works as expected.

**Comment by aduth** [comment]
Related: https://github.com/WordPress/gutenberg/pull/1195#discussion_r122204692 (when it was `button`)

**Comment by youknowriad** [comment]
I tested and it works well in Firefox too. I wonder if we should be cautious? Is there any particular reason for removing those? Extra actions?

Anyway, I'm fine either way and there's a failing unit test.

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by aduth** [comment]
>Is there any particular reason for removing those?

If it serves no purpose, it shouldn't exist.

**Comment by youknowriad** [comment]
My thinking was that maybe some browsers do weird things here, and it's hard to test all supported browsers, but yes, it's fine.

**Comment by aduth** [comment]
Do you recall why we chose to use `<input>` in #1195 ? It looks from my comment at https://github.com/WordPress/gutenberg/pull/1195#discussion_r122204692 that earlier iterations of the branch had implemented it as a `<button>`.

I'm wondering if it's perhaps related to this.

**Comment by youknowriad** [comment]
I think it's because of this https://github.com/WordPress/gutenberg/issues/4829#issuecomment-374213658

**Comment by aduth** [comment]
>My thinking was that maybe some browsers do weird things here, and it's hard to test all supported browsers, but yes, it's fine.

I'd rather we have code we understand well than code which exists to hope to protect against some unknown browser behaviors.

**Comment by aduth** [comment]
>I think it's because of this #4829 (comment)

That sounds right. What I'll do is add an inline code comment explaining both why it's an input and, if it were to be a button, the caveat about Firefox behavior.

**Comment by aduth** [comment]
Added comments and updated tests in rebased 88991ff

**Comment by aduth** [comment]
Going to save this one for after release.

**Pull request merged**
