### PR TITLE
Update Jest to latest version, and use optimized JSDOM

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR adds an `overrides` field to `package.json` to force JSDOM v22 that includes a [`.getComputedStyle` optimization.](https://github.com/jsdom/jsdom/pull/3482) This should speed up unit test runs. Although for some reason I don't see convincing results locally, the improvement is from like 50 seconds to 48 seconds, very small. Let's see if CI results are better.

I'm also upgrading Jest from 29.5.0 to 29.6.2 in this PR. `npm install` for the changed `package.json` was installing some 29.6.2 dependencies anyway, so I decided to do a proper upgrade.

Updating JSDOM to v22 has two other consequences that needed some tests to be fixed:
- URL spec has been updated to reject some silly URLs like `http://\u001f!\"$&'()*+,-.;=_{}~/"` There are very technical reasons, related to TR46 localized domain names, why this URL used to be valid and now no longer is.
- `window.getComputedStyle` in JSDOM now returns "resolved" color values, i.e., `color: black` is resolved to `color: rgb(0,0,0)`. This is the correct behavior, and instances of the `.toHaveStyles` Jest helper need to be updated accordingly.

**How to test:**
The changes affect only unit tests, both web and mobile. There should be no impact on production code.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Peformance tests are repeatedly failing, the only explanation is that we screwed some packages in the lockfile. I now rebased onto the latest trunk, hoping it helps.

**Review by tyxla — APPROVED** [review]
LGTM, great idea to use `overrides` to benefit immediately from the newer JSDOM 👍 

For the protocol, in my local testing (M1 Max), I saw some solid improvement:

this branch:
Run 1: 77.495 s
Run 2: 65.499 s

trunk:
Run 1: 87.772 s
Run 2: 74.769 s

🚀

**Comment by gziolo** [comment]
I remember times before when we could execute unit tests in less than 30 seconds 😄 

Happy to see that you keep checking how performance can get improved.

**Comment by jsnajdr** [comment]
> I remember times before when we could execute unit tests in less than 30 seconds 😄

That can always be fixed by removing some tests :wink:

When running the unit test suite locally, I see that many warnings and errors are scrolling by as the tests run. That's expected for tests that specifically test for error conditions, but many other warnings probably shouldn't be there. I suspect that many of our tests are half-broken. But not broken enough to make them fail. That could also have some infuence on running times.

**Comment by gziolo** [comment]
In fact, printing to the console might have a bigger impact on the execution time than people would think. We maintain hundreds of test files, and thousands of tests so that takes some time to even log all the test files.

**Pull request merged**
