### PR TITLE
Post Comments Form: Add style attributes

### PR DESCRIPTION
**Pull request by Copons**
## Description

Update the Post Comments Form block:

- Add support for colors, font size, line height, and text alignment.
- Convert the to light block wrapper.
- Render warnings if the comment status of the element in context is unknown, or if the comments are closed.

Note: the block is not much more than a placeholder.
It shows the whole `comment_form()` function in the front end, but in the editor it just renders "Post Comments Form".
I intentionally avoided to try to replicate `comment_form()` in the editor to avoid endlessly bloating this PR and get it stuck in a design feedback loop. 🙂 
Nevertheless, the style is applied to the front end — although in some cases the theme might prevail.
I don't find much value in fixing these cases right now, and I'd rather have a proper discussion about how to make the form consistent between editor and front end.

## How has this been tested?
Tested in Post, Page, and Site Editor, on Chrome 83 on macOS 10.15.5.
Tested on posts and pages, with comments allowed and otherwise.

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — APPROVED** [review]
This works well on my end and looks good.

For the link colors being overridden by the theme, I would vote to either:
* Get rid of the link color support in the block.json for now.
* or use the similar style rules we set for other FSE blocks to ensure they are rendered properly on the front-end.

```
.wp-block-post-comments-form.has-link-color a,
.wp-block-post-comments-form.has-background.has-link-color a {
	color: var(--wp--style--color--link);
}
```

I think it would be better to not have the option at all than to have a 'false' option that is not applied on the front-end.  Il leave that decision up to you though. 😄

**Comment by Copons** [comment]
> For the link colors being overridden by the theme

Actually, the link colors were applied correctly in my test, as far as I could see! (might have missed some links maybe?) 

There were other quirks, possibly caused by the Seedlet theme.
The most obvious one is the form header ("Leave a Reply") which is styled flex/space-between, and is always stuck on the left, regardless of the block's text alignment.

**Comment by Addison-Stavlo** [comment]
> Actually, the link colors were applied correctly in my test, as far as I could see! (might have missed some links maybe?)

They should work fine with no background applied.  I noticed with the background applied the font color for links wasn't being applied.

**Comment by Copons** [comment]
@Addison-Stavlo ah, I think that's because I've got the theme on this branch https://github.com/Automattic/themes/pull/2275 😅 
(Maybe that branch would help getting rid of the Core overrides 🤔 )

**Comment by Addison-Stavlo** [comment]
Hrm maybe... i checked out that branch and restarted my env and am still seeing the same.  Could be something on my end though.

**Comment by Copons** [comment]
@Addison-Stavlo I'm seeing this:

| Text Color | Link Color | Screen |
| - | - | - |
| (default) | (default) | Screenshot 2020-07-27 at 11 34 55 |
| Green | (default) | Screenshot 2020-07-27 at 11 35 08 |
| Green | White | Screenshot 2020-07-27 at 11 35 25 |

As far as I understand this should be correct 🤔

**Comment by Addison-Stavlo** [comment]
Yeah that looks correct to me.  Awesome.  Im not sure why Im having issues but it looks like that branch is working as expected.

**Pull request merged**
