### PR TITLE
Embed hermes aar to react-native-bridge as a module

### PR DESCRIPTION
**Pull request by oguzkocer**
## Description

This PR improves how `hermes` library is added to the `react-native-bridge` Android project. Previous to this change, we had a few issues:
* Hermes library was missing from the `aar`
* We were tracking the `hermes` library in `git` as we weren't able to use the one in the `node_modules` which is the source of truth
* We had extra Gradle tasks to backup the hermes library

From my research, the "proper" way to add a local aar to a project seems to be adding a new module for it. This is done by importing the `aar` in Android Studio by following `File -> New -> New Module -> Import .JAR/.AAR Package` which creates a `build.gradle` file for the module that adds the `aar` as an artifact. Since we have debug and release versions of the library, we introduce 2 modules for it.

## How has this been tested?

By running `./gradlew clean build` in the `react-native-bridge` project, we can verify that `hermes` library is added to the generated aars for both debug and release builds. Please see the screenshot for the folder structure of the aars.

## Screenshots 
Screen Shot 2021-01-26 at 12 51 30 PM

## Types of changes

Build file changes to the `react-native-bridge` Android project.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

cc @mokagio @mchowning @cameronvoell

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
- `./gradlew clean build` ✅ with the caveat that I had to comment the `delete nodeModulesFolder` instructions first
- `./gradlew bintrayPublish` ✅ with the same caveat as above. I used `hermes-embed-pr`, if you want to pick up the same AAR to test on WPAndroid
- Use the generated AAR in WPAndroid fetching from Bintray, build is ✅ but I get this when I load the editor

Screen Shot 2021-01-28 at 6 12 00 am

I was able to work around it by running `npm run start:reset` from `libs/gutenberg-mobile`, but I expected it to work out of the box 🤔 .

Then I though, maybe the Bintray AAR is built for release only? So I run the app again using the `vanillaRelease` flavor instead of the default `vanillaDebug` and the activity crashes when I open the editor.

I "Debug" instead of "Run" it, and found this in the logs:

```
D/SoLoader: About to load: libhermes.so
D/WordPress-API: Dispatching action: EditorThemeAction-FETCH_EDITOR_THEME
D/SoLoader: libhermes.so not found on /data/data/org.wordpress.android/lib-main
D/SoLoader: libhermes.so found on /data/app/org.wordpress.android-uoKHWYkxKZaHXIUlb-mC4A==/lib/x86_64
    Not resolving dependencies for libhermes.so
D/WordPress-API: EditorThemeStore: TransactionsStore: On FETCH_EDITOR_THEME
D/WordPress-API: ReactNativeStore: executeRequest
D/SoLoader: Loaded: libhermes.so
    About to load: libhermes-executor-release.so
D/SoLoader: libhermes-executor-release.so not found on /data/data/org.wordpress.android/lib-main
    libhermes-executor-release.so found on /data/app/org.wordpress.android-uoKHWYkxKZaHXIUlb-mC4A==/lib/x86_64
    Not resolving dependencies for libhermes-executor-release.so
```

Maybe I should have moved all of the flavors to release/vanillaRelease?

**Comment by oguzkocer** [comment]
@mokagio Thank you for the review! It looks like maybe the js bundle is missing from the aar or the hermes changes didn't work 🤔 I am currently working on something else and it might be a day or two before I can follow up on this. Could you let me know the bintray version you used to test it?

**Comment by mokagio** [comment]
@oguzkocer no worries.

The version is `hermes-embed-pr`, I created it locally. Here's the [link to Bintray](https://bintray.com/wordpress-mobile/maven/react-native-gutenberg-bridge/hermes-embed-pr#files/com%2Fgithub%2Fwordpress-mobile%2Fgutenberg-mobile%2Freact-native-gutenberg-bridge%2Fhermes-embed-pr).

I'm pretty sure I updated the code to force the bundle to be rebuilt, although something could have slipped through.

I'll double check later today if I get the time.

**Comment by mokagio** [comment]
I run the app on the emulator after building it with `assembleVanillaRelease` and experienced the same issue.

I'm trying to export the bug report via the Android tool, but my emulator is stuck loading Gmail... 😓

**Comment by oguzkocer** [comment]
@mokagio Thanks! That should be good enough for now. I'll follow up on this.

**Comment by oguzkocer** [comment]
Closing in favor of #29488.

**Pull request closed without merging**
