### PR TITLE
Chrome: Adding a confirm utility to replace `window.confirm` calls

### PR DESCRIPTION
**Pull request by youknowriad**
**Testing instructions**

Try to toggle the "private" visibility to see the dialog.

### CODE REVIEW

**Comment by jasmussen** [comment]
Pushed a little polish. I think we might want to do more polish, but this is great for now!

**Comment by aduth** [comment]
Out of curiosity: Why do we want this?

**Comment by youknowriad** [comment]
> Out of curiosity: Why do we want this?

I don't know, It just seems a better UI to me :). I expect us to need this later for deletions and stuff like that?

**Comment by aduth** [comment]
>I expect us to need this later for deletions and stuff like that?

`window.confirm` would work just as well?

Maybe not as pretty 😛  But also consistent / expected.

Can't always use the styled dialog anyways, e.g. `beforeunload` (though from what I hear, browsers are starting to prevent this "leave confirmation" for `window.confirm` as well).

**Comment by jasmussen** [comment]
> Can't always use the styled dialog anyways, e.g. beforeunload (though from what I hear, browsers are starting to prevent this "leave confirmation" for window.confirm as well).

Great question to be asking! I'm actually fine with using the stock `confirm` box. Can we translate it?

**Comment by jasmussen** [comment]
I think the styled version looks decent, but since we have no urgent need for it, and it's conceivable it could come with various accessibility issues we'd want to address, perhaps we should go with window.confirm for now, and then revisit this PR if and when it becomes necessary.

**Comment by youknowriad** [comment]
Ok Closing for now :)

**Pull request closed without merging**
