### PR TITLE
[Social Icon]: Update the `link` and `mail` block variation's icons

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?

This PR updates the icon of the `link` Social Link's block variation to match the `link` icon of `@wordpress/icons`. For security reasons(svg) this block is rendered server side and we can't actually use it directly from the JS package.

So, I just updated the current icon's path to match the `link`'s path from the JS package.

It also updates the `mail` variation's icon.

## Testing Instructions
1. Insert Social Icons block and add a `link` and a `mail`
2. Observe the

## Screenshots or screencast 
Screenshot 2023-04-20 at 12 53 00 PM

### CODE REVIEW

**Comment by jasmussen** [comment]
Looks good, thanks for doing this. I hate to say this, but should we also update the email icon while we're there? We would need to design one, one doesn't exist for this yet. But the thinner stroke width of the new link icon stands out compared to the more solid email.

**Comment by ntsekouras** [comment]
>but should we also update the email icon while we're there?

Sounds good! I just opened the PR because of the nuances of this block, so anyone that can provide the new icon is welcome!

**Comment by jasmussen** [comment]
How about this?
Screenshot 2023-04-20 at 11 01 40

That's this:

```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="enable-background:new 0 0 24 24" viewBox="0 0 24 24"><path d="M19 5H5c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm.5 12c0 .3-.2.5-.5.5H5c-.3 0-.5-.2-.5-.5V9.8l7.5 5.6 7.5-5.6V17zm0-9.1L12 13.6 4.5 7.9V7c0-.3.2-.5.5-.5h14c.3 0 .5.2.5.5v.9z" style="fill-rule:evenodd;clip-rule:evenodd;fill:#1e1e1e"/></svg>
```

Probably no need to add that to the icon library, it's just a replacement for the social link SVG. 

here it is shown next to the link:

Screenshot 2023-04-20 at 11 00 29

**Review by jasmussen — APPROVED** [review]
Unless others disagree, this seems a big win both in terms of visuals, and the SVG compression (looking at all the red).

**Comment by jameskoster** [comment]
Do we definitely want to use the WordPress icons on the frontend? Probably not a big deal, but I'm not sure if we're doing this elsewhere?

**Comment by jameskoster** [comment]
The mail icon likely has uses outside of the social icons block, it'd be good to add that one to the main package in a follow up.

**Comment by jasmussen** [comment]
> Do we definitely want to use the WordPress icons on the frontend? Probably not a big deal, but I'm not sure if we're doing this elsewhere?

I think what we want is to use _good_ icons on the frontend. The existing ones are not good. I can say that, as I designed them, a lifetime ago 🙈

**Comment by ntsekouras** [comment]
So I guess we can land this for now? 😄

**Review by mcsf — APPROVED** [review]
Good initiative!

**Pull request merged**
