### PR TITLE
Tag Processor: Only define classes if they don't already exist.

### PR DESCRIPTION
**Pull request by dmsnell**
## What?

Wraps HTML Tag Processor class definitions inside `if ( ! class_exists( … ) )` checks.

## Why?

In preparation for a merge into WordPress 6.2 we're wrapping the class definitions for the HTML Tag Processor and its dependent helper classes in checks for whether they already exist. This ensures that they don't trigger errors if and when they are included both by Core and by the Gutenberg plugin on sites having the plugin installed.

## How?

Using the `if ( … ) :` and `endif;` syntax here to avoid introducing another indent level for what is essentially the entire file.

If this file is required multiple times then successive calls will be effective noops.

## Testing Instructions

If any problems are introduced here they should completely crash the PHP unit tests.

### CODE REVIEW

**Review by adamziel — APPROVED** [review]
This is great, thank you!

Oh, and the linter is ruthless and wants us to indent these classes :-(

**Comment by dmsnell** [comment]
The linter is ruthless, I agree 😄 

I wasn't sure what ignore-statement I needed to find to blast over the code to get the linter to chill out. None of the classes in Core are indented, and I couldn't find any ignore comments there so I think the linter only marches over Gutenberg.

If I can find the ignore comment I'll add it.

**Comment by dmsnell** [comment]
The linter problem seemed more challenging than I first expected: because the problem isn't the `if ( ! class_exists() ) :` line, it's _every other line in the file_.

In response I have taken an approach that is objectively less safe so I don't have to fight against the linter.

**Review by adamziel — APPROVED** [review]

**Comment by ockham** [comment]
Thank you @dmsnell and @adamziel!

I'll try a rebase to get failing tests to pass.

**Pull request merged**
