### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
I have made 6 PRs that have been merged so far, so I think that means I can be on this list now. :stuck_out_tongue:

### CODE REVIEW

**Review by ntwb — APPROVED** [review]
Indeed, thanks for your contributions @ZebulanStanphill 💐

**Comment by youknowriad** [comment]
You also contributed with a lot of discussions in issues ;)

**Comment by ZebulanStanphill** [comment]
Thanks. :smile:

Should these kinds of PRs be added to the version milestones? It looks like the previous ones were.

**Comment by youknowriad** [comment]
It doesn't really matter but yeah why not

**Pull request merged**
