### PR TITLE
Code block: should use RichText (native)

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Ideally both the mobile version of code uses the RichText just like the web version.

Related: #43204 (though we don't absolutely need this PR, I thought it's good to clean this up)

### CODE REVIEW

**Review by geriux — APPROVED** [review]
LGTM! Thanks for updating this! I've added a few commits to fix some styling issues. With these changes we will be able to enable this block for production 🚀 (I'll do this in a separate PR).

**Comment by ellatrix** [comment]
Thanks @geriux!

**Comment by timnolte** [comment]
@ellatrix & @geriux can either of you explain why this change was needed. I need to do some further testing but this appears to be related to the Code Block being broken with `<br>` tags now ending up in the frontend code. I'm not clear on why the Code Block ever needs RichText when the result is frontend code using the `<pre>` tag.

I need to do some further investigation to see if there are actually changes to the RichText block that are causing the recent issue reported in the pending WP 6.5 release.

Ref: #59548

**Comment by timnolte** [comment]
To follow up, there is a string of changes around white space and the `<br>` tag issue but it sure seems like it still isn't fully resolved.

Ref: #58659

**Pull request merged**
