### PR TITLE
Widget editor: Add toolbar button to move between widget areas

### PR DESCRIPTION
**Pull request by talldan**
## Description
Progresses #27409.

Implements a toolbar button for all (non-widget area) blocks to allow them to switch between widget areas.

Some notes on the implementation:
- This is currently only implemented in the standalone widget editor. As a follow-up, I'll look into the customizer editor and sharing code between the two.
- I looked at whether it was possible to make this work for multi-block selections, but it seems not possible right now to render a general toolbar item that shows when any blocks are selected.
- The hooks folder in the WordPress editor seemed to have both React hooks and WordPress filters, so I've split it into two.

## How has this been tested?
Added an e2e test

Manual testing
1. Open the standalone widget editor
2. Add a widget in a widget area
3. Using the toolbar button, move the widget to another widget area

## Screenshots 
Screenshot 2021-04-14 at 4 16 22 pm

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
I tested this locally with great results. The code is all right as well 👍

**Comment by noisysocks** [comment]
Nice work.

> As a follow-up, I'll look into the customizer editor and sharing code between the two.

Yes what other code is duplicated between `edit-widgets` and `customise-widgets`? We should probably do a little audit and move the repeated bits into a new package called `widgets`.

**Comment by talldan** [comment]
It might be an option to move the legacy widget block out of the block library.

At a quick glance I don't think there's much else. Maybe we should avoid introducing this package too soon.

**Comment by paaljoachim** [comment]
Hey

I just noticed the icon which reminds me of a "slalom slope" look a like icon in the toolbar. Hovering and clicking showed me that it is the "Move to Widget area" icon. I did a quick search online and came across this icon: https://cdn4.iconfinder.com/data/icons/proglyphs-computers-and-development/512/Move-512.png

Screen Shot 2021-05-18 at 00 26 01

With the new icon I found I did quick mockup.
Widget-screen-new-move-to-icon

**Comment by noisysocks** [comment]
cc. @critterverse for thoughts on the icon.

**Comment by cgaits** [comment]
move
 This is using a rotated download type icon which I think aligns with the visual to move.

**Comment by MDWolinski** [comment]
A suggestion would be to have a Filmstrip style icon.  I mocked one up, but not an icon designer myself, so someone more experienced could iterate on it. Possibly put an arrow inside the main box, if that's better (or not).

Filmstrip

**Comment by critterverse** [comment]
Hey all, I'm questioning whether this should be treated as a primary action that lives in the toolbar. What if it goes into the ellipses menu with other secondary actions? In this case, we could treat the widget area selection as a modal (vs. how it currently appears as a popover from the toolbar):

move-step1
move-step2

I think this could help because we've got a lot of different arrow-based icons which starts to get confusing, and "move to widget area" is a tricky thing to communicate clearly in icon format.

**Comment by kellychoffman** [comment]
Nice. I think the text based option is the clearest way to go.

**Comment by paaljoachim** [comment]
I went ahead and added this new issue:
https://github.com/WordPress/gutenberg/issues/32119

(As we need to move the discussion out of the merged PR.)

**Pull request merged**
