### PR TITLE
Add icons for image tools, other, and update list icons

### PR DESCRIPTION
**Pull request by jasmussen**
This PR does three things:

- It adds the new icons we need for the incoming rich image tools (from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-632567310, cc @ajlende) 
- It adds two new icons, fullscreen and asterisk
- It updates list type icons to have not just one bullet

Screenshot 2020-05-25 at 10 31 46

_"Loop" is part of that screenshot, but the icon is already in the package_

Screenshot 2020-05-25 at 10 48 01

### CODE REVIEW

**Review by ajlende — APPROVED** [review]

**Comment by jasmussen** [comment]
Thank you Alex. I'm afk today, feel free to merge when the checks pass

**Comment by ellatrix** [comment]
This PR is adding icons, but they are not used anywhere, or replacing other icons. Is this by intention?

**Comment by jasmussen** [comment]
Yes, all of them have been requested on various PRs, most notably the image tools one, so they _will_ be used. It's a chicken and egg thing. They should ideally be added on a per PR basis, but that often means the PR has to be postponed, so sometimes they get merged with the wrong icons and those are replaced later.

**Comment by ellatrix** [comment]
Thanks @jasmussen! And thanks for updating the list icons.

**Pull request merged**
