### PR TITLE
Fix warning plugin activation

### PR DESCRIPTION
**Pull request by mcsf**
Guard against undefined constant GUTENBERG_DEVELOPMENT_MODE.

## Screenshots (jpeg or gifs if applicable):
image

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]
Thank you!

**Comment by mcsf** [comment]
🌟

**Comment by aduth** [comment]
Why would the constant not be defined if the code to define it occurs immediately prior to `gutenberg_pre_init` ?

**Comment by iseulde** [comment]
Yeah, I assumed `BEGIN AUTO-GENERATED DEFINES` also meant it would be generated for build. Could use a comment I guess saying that is not so.

**Pull request merged**
