### PR TITLE
Prevent duplicate queries

### PR DESCRIPTION
**Pull request by aaronjorbin**
When passing args to WP_Query::__construct method (in this case, but creating a new WP_Query, this one internally executes the WP_Query::get_posts method and stores the result in the WP_Query::posts property. When calling the WP_Query::get_posts again, the same SQL query gets executed, and the result is again stored in the WP_Query::posts property.

Originally done in WordPress Core in https://core.trac.wordpress.org/changeset/51144 for https://core.trac.wordpress.org/ticket/53176 with props to jorbin and david.binda.

### CODE REVIEW

**Comment by youknowriad** [comment]
Looks like there's a conflict (need a rebase), but other than that, this is looking good. Thanks for the backport :)

**Comment by aaronjorbin** [comment]
@youknowriad yep, I fixed that up.

**Review by youknowriad — APPROVED** [review]
👍

**Comment by youknowriad** [comment]
(Added the backport to core label, just to make sure we include this in `wp/trunk` later as this is already in Core)

**Pull request merged**
