### PR TITLE
Plugin: Enable publishing and saving in production

### LINKED ISSUE #1036: Plugin: Enable saving and publishing
This step needs to be done when we are ready.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1036 

The new post link is live, we can now enable publishing and saving in production.

### CODE REVIEW

**Comment by BE-Webdesign** [comment]
Couple of things going on with this that I don't think are 100% related to this PR, but I came across while testing.

#1: I didn't notice while testing #1065, but if you edit a post that already exists, using Gutenberg, it will highlight the Gutenberg > New Post submenu.

#2: Our "dirty" checking doesn't seem to update when you change the text of a block until you click outside the block. It would be nice to be able to type some stuff then be able to hit the update button right away.

**Comment by aduth** [comment]
>Our "dirty" checking doesn't seem to update when you change the text of a block until you click outside the block. It would be nice to be able to type some stuff then be able to hit the update button right away.

It does seem prone to race conditions, but in my testing I was finding that it saves content correctly when following the flow you described?

**Comment by BE-Webdesign** [comment]
>It does seem prone to race conditions, but in my testing I was finding that it saves content correctly when following the flow you described?

Oh the saving works correctly. I mean, it won't allow you to hit the update button if you type some text and just sit there. Let me make a gif, give me a moment.

**Comment by BE-Webdesign** [comment]
no-update

**Comment by youknowriad** [comment]
Like discussed with @mtias I updated this to display a confirmation when publishing new posts. We'll drop this confirmation once we have frontend support.

**Comment by youknowriad** [comment]
@BE-Webdesign To clarify the behaviour of the `onChange` handler of the Editable:

It works like this because it's hard to get TinyMCE work in a controlled way. We limit `onChange` calls to `focusout` calls only to avoid some issues we were seeing (focus jumps...), but this doesn't mean we can't try to enable it right now, we had several improvements in how content and focus are updated in the Editable, it could just work right now.

**Pull request merged**
