### PR TITLE
Update image editor to use new REST API

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Updates the inline image editor to use the new image editing REST API WordPress/wordpress-develop#845 ([Trac #52192](https://core.trac.wordpress.org/ticket/52192)). I'll keep this in draft until that lands.

## How has this been tested?

Ensure the image editor works the same as before this change.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by antpb** [comment]
I think the end to end tests will work now that 845 is merged! :)

https://github.com/WordPress/wordpress-develop/pull/845

**Comment by Mamaduka** [comment]
Hi, @ajlende

What's the status of this PR? The core patch landed in WP 5.7.

**Comment by ajlende** [comment]
@Mamaduka the status is that I forgot about it 😅

I can probably get this taken care of some time this week, though.

**Comment by Mamaduka** [comment]
Thanks, @ajlende.

I'm just going through old PRs, trying to figure out which are still actionable and which ones we can close.

**Review by scruffian — APPROVED** [review]
I tested:
✅ cropping an image
✅ rotating an image
✅ zooming an image
❌ applying a filter to an image (not duotone)

The filters aren't working in trunk either so I assume that's not related to this PR.

**Pull request merged**
