### PR TITLE
Add support for @ignore in the docgen tool

### PR DESCRIPTION
**Pull request by ryanwelcher**
## What?
The current `docgen` tool does not recognize the `@ignore` tag. This PR adds that functionality into the tool to allow items to be marked as `@ignore` so that they won't be added to the documentation. 

This is part of a larger effort to improve the Data Modules reference - https://github.com/WordPress/gutenberg/issues/42125

## Why?
Currently, only items tagged as `@private` are not documented and if the tool also supports `@ignore` it will allow us to match how [core indicates that an item should not be documented.](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#phpdoc-tags)

## Testing Instructions
1. Go to the `package/docgen` directory
2. Create a new file called `test.js` in the root with the following code:
```js
/**
 * Returns something from state.
 *
 * @param {Object} state
 * @param {string} data
 *
 * @return {string} The thing we wanted from state.
 */
export function getThingFromState( state, data ) {
	return state[ data ];
}
```
3. Run `node ./bin/cli.js test.js` and check the generated file to confirm the function is documented
4. Add the `@ignore`
5. Run `node ./bin/cli.js test.js` and check the generated file to confirm the function is  NOT documented

### CODE REVIEW

**Review by dmsnell — APPROVED** [review]
Please lean on other review; I don't have strong feelings about this. Not sure we should assume that a standard approach in PHP implies it should translate into JS so I don't think I agree with the premise, but I feel like `docgen` is something not worth spending too much time debating about.

Supporting it in `docgen` is one thing, but we should maybe raise the conversation in the Make chat when discussing a project-wide convention. People may have opinions there.

**Comment by gziolo** [comment]
> Supporting it in `docgen` is one thing, but we should maybe raise the conversation in the Make chat when discussing a project-wide convention. People may have opinions there.

You will find occurrences of `@ignore` in JavaScript code in WordPress core:

Screenshot 2022-07-07 at 07 16 40

It would be great though to confirm with core committers that it is the correct usage for the Gutenberg project.

**Review by gziolo — APPROVED** [review]

**Comment by ryanwelcher** [comment]
> Supporting it in `docgen` is one thing, but we should maybe raise the conversation in the Make chat when discussing a project-wide convention. People may have opinions there.

Totally agree. This PR is not intended to make a statement about _**how**_ things should be documented but rather to ensure that whatever tag is used ( `@ignore`, `@private` `@internal` ) has the expected outcome of that item not appearing in the docs.

To that end, I think we need to add `@internal` as well.

**Comment by ryanwelcher** [comment]
It looks like `@ignore` is the way to go based on https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/#supported-jsdoc-tags

**Pull request merged**
