### PR TITLE
Add template areas to template details

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Address a part of https://github.com/WordPress/gutenberg/issues/29147.

Add **Template Areas** section to the template details in the header dropdown. This PR focuses on adding the functionality, styling will be done in other PRs.

## How has this been tested?

1. Activate `tt1-block` theme
2. Go to Site Editor
3. View a template and click to open the dropdown in the top bar
4. Should see the template areas of the template
5. Hover/Focus on template areas should highlight the corresponding blocks
6. Click on them should select the corresponding blocks

## Screenshots 
image

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jameskoster** [comment]
Working perfectly here. 

https://user-images.githubusercontent.com/846565/135255274-87abd1e5-b3e2-41a3-83b2-8386638eb92f.mp4

Do you intend to add this feature to the Template tab in the Inspector separately?

**Comment by kevin940726** [comment]
> Do you intend to add this feature to the Template tab in the Inspector separately?

Yep, I'm working on it on a different branch :). Figured it would be easier to review.

**Comment by mtias** [comment]
Nice work!

**Review by jameskoster — APPROVED** [review]
Approving from the design side :)

**Pull request merged**
