### PR TITLE
REST API: Apply allowed_block_types filter to Block Types endpoint

### PR DESCRIPTION
**Pull request by ockham**
## Description

This is more of an RFC -- this code would currently produce an error.

In #21065, a new endpoint was introduced to return registered blocks:

> - `__experimental/block-types` List of all blocks
> - `__experimental/block-types/<namespace>/<block_type>` ie __experimental/block-types/core/post-author". Get details on a single block type
> - `__experimental/block-types/<namespace>` ie __experimental/block-types/core . Get all blocks in a single name space. 

By comparison, there's an [`allowed_block_types` hook](https://developer.wordpress.org/block-editor/developers/filters/block-filters/#hiding-blocks-from-the-inserter) in Core that's [applied](https://github.com/WordPress/wordpress-develop/blob/83e78d8cdd0282883d1b61d0b4d2820a9cadcebf/src/wp-admin/edit-form-blocks.php#L150) upon loading the Block Editor, allowing filtering of the blocks that are available to the user in the inserter.

I think it would make sense to apply that same filter to the `block-types` endpoint. However, that is not straight-forward, as the filter currently accepts a second argument: the current post object (which is, of course, readily available in a Block Editor context).

Somewhat related: https://github.com/WordPress/wordpress-develop/pull/419 

## Questions

- Do people agree that it makes sense to apply the filter to the endpoint?
- If yes, how do we get hold of a post ID? Do we mandate passing one to the endpoint? That'd mean a significant API change; but maybe it is arguable that a list of blocks _needs_ a post context? (Think e.g. Site Editor (`wp_template` CPTs) vs Post Editor.)

cc/ @spacedmonkey @TimothyBJacobs for opinions :slightly_smiling_face: 

## How has this been tested?
Hasn't yet :grimacing: 

## Types of changes
RFC

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
In my opinion, the block types endpoint should return the full list of registered blocks.

We could add a `for_post=<id>` parameter to the block types endpoint, but I could see that list being filtered for other scenarios that aren't posts and I'd prefer not to add a bunch of those filters, particularly if . For me, the list of allowed block types is a property of the object being edited. 

So I would implement this as a property on the posts endpoint that would be the list of allowed block names. It would only be available in the `edit` context. This might also be a time to look at implementing the [proposed](https://core.trac.wordpress.org/ticket/49330) `block-editor` context.

**Comment by ockham** [comment]
> In my opinion, the block types endpoint should return the full list of registered blocks.

I don't have a strong preference for either option, but a point can be made that the only place were blocks are currently made available in the editor does apply that filter (which is contextual). This is my main reason for wondering if the same pattern might make sense to carry over to the endpoint.

> We could add a `for_post=<id>` parameter to the block types endpoint, but I could see that list being filtered for other scenarios that aren't posts and I'd prefer not to add a bunch of those filters, particularly if . For me, the list of allowed block types is a property of the object being edited.

Right. By comparison, what would be a typical use case for the block types endpoint? :thinking: 

> So I would implement this as a property on the posts endpoint that would be the list of allowed block names. It would only be available in the `edit` context. This might also be a time to look at implementing the [proposed](https://core.trac.wordpress.org/ticket/49330) `block-editor` context.

Ah, thanks for the link, wasn't aware of that conversation!

**Comment by TimothyBJacobs** [comment]
> I don't have a strong preference for either option, but a point can be made that the only place were blocks are currently made available in the editor does apply that filter (which is contextual).

Yeah that's definitely true. For me though, I think that list could grow so it wouldn't be the most forward compatible interface.

> Right. By comparison, what would be a typical use case for the block types endpoint? 

As a developer, I want to be able to limit the blocks that can be used in the widgets screen, navigation screen, and full site editing. I think those would be different filtering contexts. For those, they could perhaps be done with the same arguments because they are each backed by posts. But what about term descriptions or author archives?

**Comment by ockham** [comment]
> > I don't have a strong preference for either option, but a point can be made that the only place were blocks are currently made available in the editor does apply that filter (which is contextual).
> 
> Yeah that's definitely true. For me though, I think that list could grow so it wouldn't be the most forward compatible interface.
> 
> > Right. By comparison, what would be a typical use case for the block types endpoint?
> 
> As a developer, I want to be able to limit the blocks that can be used in the widgets screen, navigation screen, and full site editing. I think those would be different filtering contexts. For those, they could perhaps be done with the same arguments because they are each backed by posts. But what about term descriptions or author archives?

Hmm, what would it mean to insert a block in an author archive? Wouldn't one just be editing the corresponding template? And for term descriptions, those are currently plain text, AFAICT :thinking: 

Not trying to hair-split, but it seems like a post object based filter might give us pretty good coverage of most of the use cases you're listing, and it'd be nice if 

1. we could re-use the existing filter
2. wouldn't have to introduce a ton of contexts.

**Comment by ockham** [comment]
I'll add that in contexts like the Site Editor, it's possible to switch between the currently edited template (i.e. `wp_template` post object) on the client side (without a server side reload). This means that we can't simply apply this filter in `lib/edit-site-page.php`, since it'd only apply to the initially loaded template. Instead, we'd need to fetch the allowed blocks for the currently loaded template somehow from the REST API. (Just to document a use case.)

**Comment by TimothyBJacobs** [comment]
> Hmm, what would it mean to insert a block in an author archive? Wouldn't one just be editing the corresponding template? 

The template would, but the users themselves also have a description field that often is shown in the archive. Also plain text, but I think in an ideal world it'd be a block editor. So that belongs to the user object.

> And for term descriptions, those are currently plain text, AFAICT

Yeah those are currently a plain text input, I thought the idea was that we'd be able to edit those with the block editor at some point?

>  Instead, we'd need to fetch the allowed blocks for the currently loaded template somehow from the REST API. (Just to document a use case.)

That seems like a strong argument for making it a property of the post being edited :) Then you wouldn't need to refetch the block types definition, you'd just be getting the list of block names from the post object you've selected.

**Comment by ockham** [comment]
Some related discussion (about we should filter by context rather than post object): https://github.com/WordPress/gutenberg/pull/24006#discussion_r460784097

**Comment by ockham** [comment]
Closing. We might opt to make allowed blocks a property of the post object (as returned by the posts/pages/post types endpoint), see discussion above.

**Pull request closed without merging**
