### PR TITLE
Ensure menus before map operation in Nav block

### PR DESCRIPTION
**Pull request by getdave**
## Description

This PR fixes a potential source of error in the Navigation block placeholder whereby the "existing menus" dropdown attempts to map over variables which are expected to be arrays but which may undefined.

This PR safeguards against this. 

Note that `<MenuGroup>` will not render anything if it doesn't have children which really helps us out here.

## How has this been tested?

1. Make sure you have no Classic Menus in your database (switch to a classic theme and delete them all!)
2. Switch to block theme.
3. Add Nav block.
4. See placeholder.
5. Click "Select existing menu...`.
5. The block should not crash. The dropdown should only show menus if they exist.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by talldan — APPROVED** [review]
LGTM, thanks for fixing this.

**Comment by getdave** [comment]
Rebasin' then I'll merge this.

**Review by adamziel — APPROVED** [review]
I never thought I’d approve a PR from my phone, but here we go

**Comment by andrewserong** [comment]
Cherry picked into the Gutenberg 11.9 release in: https://github.com/WordPress/gutenberg/commit/885dc536596e77195f13ccb88ab02ad726d94cc8

**Pull request merged**
