### PR TITLE
Experiment how React hooks can improve our codebase

### PR DESCRIPTION
**Pull request by youknowriad**
React 16.7 introduces this concept of [hooks](https://reactjs.org/docs/hooks-intro.html). In this PR, I'm creating some hooks to explore this API and how it can improve or not our codebase and APIs.

So far, I'm thinking that it's a great API, I like how you can reason about discrete behaviors and combine them later in components without having to wrap your components or create extra DOM nodes you don't really need.

 - See how I created two simple hooks `useImageSize` to retrieve the image size and height, `useElementSize` to retrieve the size of an element and refresh it if the window is resized.
 - See how I refactored our current `ImageWidth` component to combine the two hooks above instead of a complex component class.
 - I think the `ImageWidth` component can be eliminated entirely (in favor of using the hooks directly in the image block) but I didn't want to push the refactor further.

### CODE REVIEW

**Comment by youknowriad** [comment]
Nice to see that React 16.7 is passing all of our tests. There's a lot of warnings (deprecations) though :)

**Comment by gziolo** [comment]
> +75 −76

This is surprising (even if you subtract 2 lines added for React version upgrade).

It definitely promotes code reuse and composition similar to what HOCs offer with much easier syntax. By easier, I mean no need to create all those wrapping components which do nothing and introduce lots of confusion. I'm looking forward to the day when 16.7 stable is out 💯

**Comment by mtias** [comment]
I think it matches our journey between render props, higher-order wrapping functions, and `support` statements, and I think it would greatly simplify the expression of these (colors, alignments, etc) while providing the flexibility that "support" lacks.

**Comment by youknowriad** [comment]
Closing, let's revisit once hooks are officially shipped.

**Comment by dsifford** [comment]
Psssssssssst, @youknowriad... They've officially shipped! :blush: 

https://github.com/facebook/react/pull/14679

**Comment by youknowriad** [comment]
Not quite yet, but hopefully very soon :)

**Pull request closed without merging**
