### PR TITLE
Register Assets: cache bust without filemtime

### PR DESCRIPTION
**Pull request by hellofromtonya**
## Description
#18227 reports times when outdated assets are being served when updating the plugin. `filemtime` is suggested as the root cause. Though I was unable to reproduce, it is conceivable that the `filemtime` could cause this problem. Why?

The asset version strategy in the registration uses [`filemtime`](https://www.php.net/filemtime) to generate a unique version based on the asset file's modification time. The return of `filemtime` is cached in the realpath cache with an expiration defined by the [`realpath_cache_ttl` option in php.ini](https://www.php.net/manual/en/ini.core.php#ini.realpath-cache-ttl).

This PR replaces `filemtime` with 2 different strategies:
- For production, it uses `GUTENBERG_VERSION` as the asset version.
- For development, it uses current time in seconds via `time()` as the asset version.

Note:
[`time()`](https://www.php.net/manual/en/function.time.php) is not cached in the realpath cache.

Benefits:

- Simplifies the code
- Avoids an extra hit to the filesystem (teeny tiny performance boost though user will never see it as it's in microseconds)
- Mitigates the realpath cache scenario

## How has this been tested?
Validated new version of the stylesheet loads when updating the plugin.

Steps:
1. Installed/activated version 9.9.3
2. In stylesheet `build/build-directory/style/css`, changed `:root{--wp-admin-theme-color:#00ba3e;`
3. Noted asset's version `...gutenberg/build/block-directory/style.css?ver=1615418702`
4. Updated to new version with this PR's changes

Results:
The updated stylesheet was served to the browser.
- The color changed to #007cba and rendered
- Version changed `..gutenberg/build/block-directory/style.css?ver=1615469843`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by mkaz — APPROVED** [review]
The change looks good, tested and works fine.

The one caveat might be for Gutenberg developers who do not set the WP_DEBUG constant, we probably will want to confirm that is mentioned in the docs somewhere. This can be a separate PR.

**Comment by hellofromtonya** [comment]
>The one caveat might be for Gutenberg developers who do not set the `WP_DEBUG` constant, we probably will want to confirm that is mentioned in the docs somewhere. This can be a separate PR.

What constant are Gutenberg devs more inclined to set, if any? The PR can check for either `WP_DEBUG` or ____.

**Comment by mkaz** [comment]
> What constant are Gutenberg devs more inclined to set, if any? The PR can check for either `WP_DEBUG` or ____.

I'm not sure, my guess is none on the PHP side. The expectation is more setting in at build using something like:

```
$ NODE_ENV=development npm run build
```

Here is the dev setup document: 
https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/getting-started-with-code-contribution.md

**Comment by hellofromtonya** [comment]
That makes.

It's a reasonable expectation when working in `npm run dev` that dev versions will be served up. The `WP_DEBUG` constant is set when using `wp-env`. In a separate PR we could add default set up for those not using `wp-env`.

**Comment by aristath** [comment]
> What constant are Gutenberg devs more inclined to set, if any? The PR can check for either `WP_DEBUG` or ____.

Usually I have `SCRIPT_DEBUG` enabled... People working on Gutenberg do mostly JS work, so frequently that is set to true in order to get better debug info in the browser console

**Comment by hellofromtonya** [comment]
>Usually I have SCRIPT_DEBUG enabled... People working on Gutenberg do mostly JS work, so frequently that is set to true in order to get better debug info in the browser console

In looking at [constants predefined when running wp-env](https://github.com/WordPress/gutenberg/tree/trunk/packages/env#default-wp-config-values), both are set to `true`:

```
WP_DEBUG: true,
SCRIPT_DEBUG: true,
```

`SCRIPT_DEBUG` is already being used as development flag in the same file. 

Switching to use `SCRIPT_DEBUG` for consistency.

**Review by aristath — APPROVED** [review]

**Comment by gziolo** [comment]
When I tested it locally I saw the following:

> Warning: Use of undefined constant GUTENBERG_VERSION - assumed 'GUTENBERG_VERSION' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/plugins/gutenberg/gutenberg.php on line 245
  | GUTENBERG_VERSION
 
It looks like `GUTENBERG_VERSION` is only set on `production` when using the build version of the plugin. You should be able to reproduce it by setting `SCRIPT_DEBUG` to `false`.

**Review by gziolo — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by hellofromtonya** [comment]
@gziolo I was looking at that earlier today, but then got sidetracked. I'm thinking about altering the decision to include checking if `GUTENBERG_VERSION` is not defined, then it's also in a development or test mode. Why? As you pointed out, that constant is for production, i.e. meaning it's defined in the production version of the plugin.

**Comment by hellofromtonya** [comment]
Commit https://github.com/WordPress/gutenberg/pull/29775/commits/352e06ae161ddb9f738e82320203e8d20874c464 flips the check around by determining if in production mode, else it defaults to use `time()` as the asset version. For prod mode, it checks:

- Is `GUTENBERG_VERSION` defined? If yes, do the next check; else use `time()`
- Is in not in debug/dev mode, where debug/dev is determined by `SCRIPT_DEBUG` defined and `true`? If not in debug/dev mode, then use `GUTENBERG_VERSION`; else use `time()`.

**Testing locally**

When the above conditions are met:

```html
<link rel="stylesheet" id="wp-edit-blocks-css" href="http://wpcore.local/wp-content/plugins/gutenberg/build/block-library/editor.css?ver=10.1" media="all">
```

When adding  `define( 'SCRIPT_DEBUG', false );` to `wp-config.php`:
```html
<link rel="stylesheet" id="wp-edit-blocks-css" href="http://wpcore.local/wp-content/plugins/gutenberg/build/block-library/editor.css?ver=10.1" media="all">
```

When commenting out `define( 'GUTENBERG_VERSION', '10.1.1' )` in the plugin:

```html
<link rel="stylesheet" id="wp-edit-blocks-css" href="http://wpcore.local/wp-content/plugins/gutenberg/build/block-library/editor.css?ver=1615918791" media="all">
```

When restoring the constant and then changing `define( 'SCRIPT_DEBUG', true );`:

```html
<link rel="stylesheet" id="wp-edit-blocks-css" href="http://wpcore.local/wp-content/plugins/gutenberg/build/block-library/editor.css?ver=1615918820" media="all">
```

**Review by gziolo — APPROVED** [review]
Awesome work polishing the logic 💯

**Pull request merged**
