### PR TITLE
Global Styles: Save and Delete functionality for user variations

### PR DESCRIPTION
**Pull request by ribaricplusplus**
## What?
Partially addresses #45371. Makes it possible to save and delete custom user variations. Adds a warning that is shown if a user has modified Global Styles and then tries to switch either to a theme variation or a custom user variation, because if the user switches, they would lose the unsaved changes.

This PR also makes a small tweak to `wp-env` to make it possible to run xdebug for php unit tests. Just run them using `npm run test:unit:php:debug`

@carolinan @annezazu Can you help me find someone to review this? I don't know who to ping.

## Testing Instructions

The PR includes unit tests and e2e tests. For manual testing, see the screencasts for a demonstration of all testable functionality.

## Screenshots or screencast

Creating and deleting variations

https://user-images.githubusercontent.com/43731400/211765851-f0f7f83c-dc84-4a1a-b8e5-21d078ea1d52.mp4

Switching between variations

https://user-images.githubusercontent.com/43731400/211767194-54d6e9ba-c811-4e12-bd1f-c9df1fc32b53.mp4

Keeping the selected custom variation in sync with current user global styles

https://user-images.githubusercontent.com/43731400/211767870-f738ab36-b127-4a46-bfbc-4351e976962a.mp4

Display a warning if unsaved changes are about to be lost while switching

https://user-images.githubusercontent.com/43731400/211768609-5bf1fe40-0508-4279-a7a7-a56d42352436.mp4

### CODE REVIEW

**Comment by ribaricplusplus** [comment]
@jasmussen @youknowriad @ellatrix Can I have some help finding someone to review this?

**Comment by youknowriad** [comment]
This is an impressive PR. Great work. It's going to take some time for me to review it properly. That said, first I think I want to mention is that if you're able to split it into smaller PRs that can ship independently, I think that's better for reviews and iterations.

For instance the "wp-env" change is clearly something that need to be extracted out of this PR into a dedicated PR.

**Comment by youknowriad** [comment]
I also see that there are some changes to the php side (endpoints I assume), is it possible to extract these to their own PR? In other words, does it make sense for these changes to happen independently or not?

**Comment by ribaricplusplus** [comment]
> That said, first I think I want to mention is that if you're able to split it into smaller PRs that can ship independently, I think that's better for reviews and iterations.

Thank you for looking into it! I will try to split the things I can into other PRs. The wp-env thing definitely can go to an independent PR.

> I also see that there are some changes to the php side (endpoints I assume), is it possible to extract these to their own PR? In other words, does it make sense for these changes to happen independently or not?

Unfortunately I don't think it makes sense splitting the PHP endpoints into a separate PR, because the JavaScript relies on new endpoints to work.

**Comment by youknowriad** [comment]
> Unfortunately I don't think it makes sense splitting the PHP endpoints into a separate PR, because the JavaScript relies on new endpoints to work.

Yeah, but I mean can we land the endpoints first and then the JS changes?

**Comment by ribaricplusplus** [comment]
> Yeah, but I mean can we land the endpoints first and then the JS changes?

Yep, we could do that. Should I split it that way?

**Comment by youknowriad** [comment]
> Should I split it that way?

Yeah I think so, especially if these endpoints changes could make sense regardless of whether we land the JS or not.

**Comment by ribaricplusplus** [comment]
Alright. I will do that and ping you when it's done. Thanks a lot for your help.

**Comment by ribaricplusplus** [comment]
@youknowriad I split this PR into 3:

- PHP Changes (should be merged first): https://github.com/WordPress/gutenberg/pull/47075
- JS Changes (depend on PHP changes): https://github.com/WordPress/gutenberg/pull/47076
- WP Env change (not relevant for you I guess): https://github.com/WordPress/gutenberg/pull/47077

I'm closing this PR in favor of those 3.

**Comment by annezazu** [comment]
Thanks @ribaricplusplus -- apologies for the delay in getting back to you. Had this to get to today and, upon catching up, I see you've already gotten direction!

**Pull request closed without merging**
