### PR TITLE
[RNMobile] Use Hermes bytecode

### PR DESCRIPTION
**Pull request by hypest**
## Description
This PR build and uses the React Native Hermes bytecode format for the native editor bundle. This provides better performance on Android.

~Note: This PR is build on top of https://github.com/WordPress/gutenberg/pull/26691 so tests can succeed locally on Android 10 devices too.~

## How has this been tested?
Locally on an Android 10 device (Pixel 2 XL) via issuing `npm run test:e2e:android:local` and smoke testing the native demo app. See the [results of the Writing Flow manual tests in this comment](https://github.com/WordPress/gutenberg/pull/26732#issuecomment-723043019).

## Types of changes
* The Android bundle is pass through the Hermes compiler to transform it to bytecode format before using it.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by hypest** [comment]
The gallery UI test [seems to fail](https://github.com/WordPress/gutenberg/pull/26732/checks?check_run_id=1363215393) but the Gallery block is working OK my my local WPAndroid test. Will investigate deeper.

**Comment by hypest** [comment]
Android Testing ⌛ ,  Results below:

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text forma

**Comment by hypest** [comment]
Will update this PR to include the native mobile tests fix that got merged to master.

**Comment by hypest** [comment]
I've rebased the PR to decouple it from https://github.com/WordPress/gutenberg/pull/26691 now that I've verified that the Hermes changes didn't break any test.

**Review by mchowning — APPROVED** [review]
Tested these changes in the demo app and WPAndroid and everything is working great.

**Review by mchowning — APPROVED** [review]
Tested these changes in the demo app and [WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/pull/13297#pullrequestreview-525510919) and everything is working great.

**Pull request merged**
