### PR TITLE
Fix the quick inserter for blocks with custom svg icons

### LINKED ISSUE #3190: Custom SVG in Inserter
## Issue Overview
When I add a SVG as an icon to a custom block, it is not displayed in the inserter with the three blocks at the bottom.

bildschirmfoto 2017-10-26 um 23 25 47

It works in the menu inserter and /inserter

## Steps to Reproduce (for bugs)
1. Create a custom block
2. Add an custom SVG as icon.
3. Hover over the Inserter at the bottom.

## Expected Behavior
The SVG icon should be displayed next to the block title

## Current Behavior
No icon next to the block title

## Possible Solution
The `components/icon-button` uses `<Dashicon />`, it should use `<BlockIcon />` instead.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3190

This PR uses the `BlockIcon` component to display the blocks with custom SVG icons properly on the "quick inserter" (inserter shown when hovering the bottom inserter).

**Testing instrructions**

 - Set a custom SVG icon to one of your most used blocks, example:

```
<svg width="20" height="20">
	<circle cx="10" cy="10" r="8" stroke="green" strokeWidth="2" fill="yellow" />
</svg>
```

 - The icon should show up properly in the quick inserter

### CODE REVIEW

**Review by aduth — COMMENTED** [review]
Should `IconButton` be able to support a React element for its `icon` prop? (i.e. pass `BlockIcon` as prop?)

**Comment by youknowriad** [comment]
> Should IconButton be able to support a React element for its icon prop? (i.e. pass BlockIcon as prop?)

Good question, I don't know, the downside is that it could be anything not only icons, which would defeat its purpose. I guess it's ok.

**Comment by youknowriad** [comment]
Though, in this particular use-case it would introduce a bit of complexity because we need the wrapper span to style the icon consistently

**Comment by aduth** [comment]
I wondered about that too; can't we style the icon directly?

**Comment by Soean** [comment]
Works for me, now I can see the Icon of my custom block.

**Comment by aduth** [comment]
>Though, in this particular use-case it would introduce a bit of complexity because we need the wrapper span to style the icon consistently

Still seems like it should be fine to pass the span-wrapped BlockIcon as an `icon` prop.

**Review by aduth — APPROVED** [review]

**Comment by youknowriad** [comment]
@aduth The switcher was seeing the same issues. 16c1b07 should fix it, I've updated the IconButton to allow elements as icons like suggested.

**Pull request merged**
