### PR TITLE
Lower spacer  and cover block step values

### LINKED ISSUE #22166: Spacer height input steps in 10 not 1
**Describe the bug**
The spacer block height input steps in 10, why should the user be limited in increments of 10? What if they wanted a spacer that was 15px?

**To reproduce**
1. Add a spacer block
2. Use up/down arrows on number input
3. Notice it steps in increments of 10

**Expected behavior**
Steps of 1 to allow any height to be entered.

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Default

### PR DESCRIPTION
**Pull request by MichaelArestad**
## Description
Fixes #22166 This lowers the step value of the spacer and cover block slider controls.

### Before
When using the `RangeControl` input, the user could not set a value between 1 and 10 px either by using the slider or with the text input. 

### After
By lowering the step value to 1 (by removing it), the user can enter specific values.

### Additional thoughts
I believe the issue of not being able to enter any specific pixel value into the `RangeControl` when a step larger than 2px is set  (3+) is still a problem. Perhaps @ItsJonQ might have an idea about that.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ItsJonQ — APPROVED** [review]
🚀 That should do it! Thank you @MichaelArestad for this!!

I'm unsure as to why it was updated last time. Hopefully we can avoid ping ponging back to step = `10` 🙈

**Comment by MichaelArestad** [comment]
> I'm unsure as to why it was updated last time. Hopefully we can avoid ping ponging back to step = 10 🙈

Same. I'm going to leave this open for a little bit just in case.

**Comment by Soean** [comment]
It was introduced with 10 in https://github.com/WordPress/gutenberg/pull/10291 by @mcsf

**Comment by mcsf** [comment]
> It was introduced with 10 in #10291 by @mcsf

Actually, the change was inherited from before, it's just that the RangeControl got moved around.

**Comment by mcsf** [comment]
> Actually, the change was inherited from before, it's just that the RangeControl got moved around.

I'm still to blame, though. 😅 #2815, so nearly three years ago.

**Comment by ninetyninew** [comment]
Is there a reason why the spacer height has a minimum value of 20? I wanted to add a spacer at 15px recently and couldn't?

**Comment by mcsf** [comment]
> Is there a reason why the spacer height has a minimum value of 20? I wanted to add a spacer at 15px recently and couldn't?

This has been extensively debated:

* [Core Editor meeting of April 15](https://make.wordpress.org/core/2020/04/20/editor-chat-summary-wednesday-15-april-2020/)
* [Trac ticket](https://core.trac.wordpress.org/ticket/49862#comment:3)
* #18906

The latter remains an open issue, so, in order to keep the present PR focused, I suggest you follow that other issue.

**Pull request merged**
