### PR TITLE
Remove overflow to have SafeArea over the BlockList

### LINKED ISSUE #1424: [iOS] SafeArea is drawn behind block content
This gives the illusion that the SafeArea (space between the bottom toolbar and the edge of the screen on the iPhone X family (and 11 family) is transparent.

On this screenshot, the SafeArea is red, and the block content is noticeably drown on top of it.

IMG_2A76FBACC416-1

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description
Fix SafeArea to be hierarchically over the Block List.

Ref to gb-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1425
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1424
## How has this been tested?

Tested on iOS:

1. Check if the SafeArea is not transparent and the block content isn't drown on top of it.

## Screenshots 
Screenshot 2019-10-09 at 09 51 33

## Types of changes
Remove `overflow: 'visible'` from `KeyboardAwareFlatList` on iOS.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Working great! Thank you @lukewalczak 🙏 

I have restarted a couple of failing e2e tests. Will merge when we get the ✅

**Comment by lukewalczak** [comment]
@etoledom I think that for failing test we need to first wait for merge https://github.com/WordPress/gutenberg/pull/17859

**Comment by etoledom** [comment]
Thanks for the heads up @lukewalczak !
Let me know when the branch gets updated 👍

**Comment by lukewalczak** [comment]
@etoledom I've updated my branch with the latest `master`. Hopefully Travis will get us green light 🚥

**Pull request merged**
