### PR TITLE
Code & Preformatted Blocks: delete on backspace from an empty block

### LINKED ISSUE #26326: Writing flow: Backspace from empty code or preformatted block does not delete the block
**Describe the bug**

Reporting because it's easy to implement.

### PR DESCRIPTION
**Pull request by daddou-ma**
closes #26326
## Description
adding `onRemove` handler to each of Code and Preformatted Blocks. to deleted the empty block when pressing backspace.

### Enhancements
- Code Block: delete empty block on backspace.
- Preformatted Block: delete empty block on backspace.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by ellatrix** [comment]
Would it be possible to add a simple e2e test?

**Review by gziolo — APPROVED** [review]
Proposed changes alone work properly. It's a nice improvement 👍

**Comment by gziolo** [comment]
> Would it be possible to add a simple e2e test?

@daddou-ma, it would be really nice to open a follow-up PR that covers UI interactions for those 2 blocks to prevent future regressions. Test specifications live in:
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/code.test.js
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/preformatted.test.js

**Comment by daddou-ma** [comment]
> > Would it be possible to add a simple e2e test?
> 
> @daddou-ma, it would be really nice to open a follow-up PR that covers UI interactions for those 2 blocks to prevent future regressions. Test specifications live in:
> 
> * https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/code.test.js
> * https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/preformatted.test.js

Thanks for approving changes ^^. Yes, I will work on it.

**Comment by daddou-ma** [comment]
> > Would it be possible to add a simple e2e test?
> 
> @daddou-ma, it would be really nice to open a follow-up PR that covers UI interactions for those 2 blocks to prevent future regressions. Test specifications live in:
> 
> * https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/code.test.js
> * https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/specs/editor/blocks/preformatted.test.js

@gziolo @ellatrix, I've made a PR #26972 with e2e tests covering those changes. could you check it, please?

**Pull request merged**
