### PR TITLE
Icons: Adds bell and bell-unread icons

### PR DESCRIPTION
**Pull request by javierarce**
## What?
Adds two new icons: `bell` and `bell-unread`.

## Why?
These are common icons helpful to indicate notifications and pending notifications.

## Testing Instructions
- Run Storybook locally `npm run storybook:dev`
- Open the icon library `http://localhost:50240/?path=/story/icons-icon--library`
- Search for the `bell` and `bell-unread` icons.

## Screenshots
image
image

## References

Proposals in the Figma library:

- [bell icon](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=61962-15588&t=LbA8Tzv1mg6cEntE-4)
- [bell-unread icon](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=61962-15620&t=LbA8Tzv1mg6cEntE-4)

### CODE REVIEW

**Comment by javierarce** [comment]
The `bell-unread` icon has one extra path (`<circle cx="17" cy="7" r="2.5"/>`) so its color can be customized with CSS.

**Comment by jameskoster** [comment]
I like the design :) 

If you run the markup through https://svgomg.net/ I think there's potential for some further optimisation.

We tend to avoid separate paths within the same icon, but the justification seems valid here. I'd welcome more feedback on that from @WordPress/gutenberg-design.

**Comment by javierarce** [comment]
> If you run the markup through https://svgomg.net/ I think there's potential for some further optimisation.

Oops, you are right. I just optimized the icons a bit more.

**Review by jameskoster — APPROVED** [review]

**Review by jameskoster — CHANGES_REQUESTED** [review]
Ah, I noticed there's no changelog entry, lets add that before merging :)

**Comment by javierarce** [comment]
> Ah, I noticed there's no changelog entry, lets add that before merging :)

@jameskoster: added

**Review by jameskoster — APPROVED** [review]

**Comment by jameskoster** [comment]
Thank you! :)

**Pull request merged**
