### PR TITLE
Recreate `package-lock.json` using Node.js 8.9.3 & npm 5.6.0

### PR DESCRIPTION
**Pull request by ntwb**
## Description

Follow up to #4073 

This PR regenerates the `package-lock.json` via `npm install` using Node.js `8.9.3` and npm `5.6.0`
## How Has This Been Tested?

Tested using `npm test`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ntwb** [comment]
Looking at this PR what I notice is:

• Various Jest modules have been reordered, `expect`, `jest-mock`, `jest-leak-detector`,  `jest-mock` etc but everything looks good to me in this regard.

• Lots of module hashes switching from `sha1`'s to `sha512`'s, I'm not sure if this is a recent change to, or a recent release of npm to now preference `sha512`'s or not.

• Quite a few packages have _minor_ semantic version bump, so that's probably a good thing to get a few packages updated that have had minor bugs fixed and had a new minor release released.

**Comment by gziolo** [comment]
`sha1` vs `sha512` is a well-known issue. It would be great to see it finally fixed, but it might just the fact that they are added using a single machine :)

We have now e2e tests which give a better confidence about such changes. Speaking myself, I'm fine with merging this one.

**Comment by gziolo** [comment]
Have you checked if it has impact on the bundles size for Gutenberg build files? I guess it shouldn't have, but better to double check.

**Comment by ntwb** [comment]
Testing: `npm run package-plugin`

This branch: `gutenberg.zip` = `1,392,157 bytes`
Current `master` branch: `gutenberg.zip` = `1,392,318 bytes`

**Review by gziolo — APPROVED** [review]
Let's get it in then 👍

**Pull request merged**
