### PR TITLE
Editor: Fix Block Embed Input size

### LINKED ISSUE #19420: Input larger than embed button
On the Instagram embed the input for URL is larger than the embed button:

image

### PR DESCRIPTION
**Pull request by ItsJonQ**
This update fixes the Input vs. Button sizing and alignment as seen in Embed
blocks, such as Instagram, Twitter, or YouTube.

The problem stemmed from the Placeholder component from `@wordpress/components`.
The `display: flex` container caused the `input` to grow responsively
(height wise), which was triggered by the mysterious margin below the button.

The solution involved neutralizing the margins for both the `input` and `button`
elements, allowing for their heights and alignments to match.

## How has this been tested?
Tested locally in Gutenberg

##### Before

Screen Shot 2020-01-06 at 12 23 51 PM

##### After

Screen Shot 2020-01-06 at 12 23 26 PM

---

##### Margin inconsistencies

Screen Shot 2020-01-06 at 12 22 48 PM

Screen Shot 2020-01-06 at 12 22 31 PM

## Types of changes
The code was introduced in the `@wordpress/components` layer, for the `Placeholder` component. Given how this Component is used within Gutenberg, I feel like this adjustment in margins is a safe fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

---

Resolves https://github.com/WordPress/gutenberg/issues/19420

### CODE REVIEW

**Review by karmatosed — APPROVED** [review]
Looks good to me and fixes the issue, thanks!

**Comment by youknowriad** [comment]
Could this have impacted the table block placeholder

Capture d’écran 2020-01-07 à 8 59 00 PM

**Comment by ItsJonQ** [comment]
@youknowriad Oh dear! Let me take a look

**Comment by ItsJonQ** [comment]
@youknowriad Update!~ Yes it did. Although... looking at the Table Block placeholder styles... the relationship of the margins x child elements feel strange.

I'm going to follow up with an update to hopefully address both Embed + Table Blocks

**Comment by youknowriad** [comment]
Looks like this is already fixed in master now right?

**Pull request merged**
