### PR TITLE
Border Radius Support: Fix application of zero radius values

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## Description
Fixes problem where explicitly setting a border radius of zero wasn't honoured #27667 (review)

_Note: This splits out the fix for zero values from exploration on setting min/max values etc in https://github.com/WordPress/gutenberg/pull/28541_

## How has this been tested?
Manually.

#### Testing instructions

1. Checkout this PR
2. Update your theme.json file to opt into the border radius support and define a border radius style for the image block context. [Example theme.json gist](https://gist.github.com/aaronrobertshaw/8736ff074de23d1b5a4fa147b6bcda2e).
3. Create a new post and add an image block. It should display with the default radius set in your theme.json
4. Select the block and confirm that you can apply a 0 value border radius and it takes affect.

## Screenshots 
| Before | After |
|-|-|
| ZeroBorderRadius | ZeroBorderRadius-Fix |

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This worked for me in terms of being able to set the 0 radius, but for some reason the default radius doesn't show in the slider when you first add the image or reset the slider. The image shows the default radius setting, but slider shows 0:

radius

**Comment by aaronrobertshaw** [comment]
> This worked for me in terms of being able to set the 0 radius, but for some reason the default radius doesn't show in the slider when you first add the image or reset the slider. The image shows the default radius setting, but slider shows 0:

Thanks for the review 👍 

The [original PR](https://github.com/WordPress/gutenberg/pull/28541) that contained this specific fix included an arbitrary property in the theme.json schema's supports for the default. This was a hack requiring the theme developer to have to manually add that property to match whatever value they added in the theme.json styles. They would also need duplicate it per context e.g. to have different radii for `core/image` vs `core/group`.

The FSE gets the merged global styles added to the state. From there they can be used to set defaults on controls. Unfortunately, at this stage we do not have access to those merged styles. In the next evolution of the block supports mechanism I'm hoping that will be addressed. 

So to not add new properties to the schema then have to make a breaking change in dropping them, I limited the scope of this PR to only fixing the application of `0` value border radii.

**Review by glendaviesnz — APPROVED** [review]
Look like a good solution to me based on the explanation of the reason for the approach in https://github.com/WordPress/gutenberg/pull/28998#issuecomment-780930657

**Comment by ramonjd** [comment]
I'm just testing as a learning exercise, so don't have much context on this but can verify that:

✅ I can apply a `0` for the border radius of an image block
✅ The border radius is displayed both in the editor and in the published post

The default value in `experimental-default-theme.json` isn't shown on new image blocks [as explained above](https://github.com/WordPress/gutenberg/pull/28998#issuecomment-780930657).

Which makes me wonder, do we need to set the default to `50px` if it's not taking effect?

**Comment by aaronrobertshaw** [comment]
Thanks @ramonjd for giving this a test.

> Which makes me wonder, do we need to set the default to 50px if it's not taking effect?

If I understand your question correctly. In this instance the theme.json was only setting the default 50px border radius for testing so that we could visually see the application of the explicit `0` border radius. Without that default 50px being picked up by the border radius block support the explicit `0` border radius would appear the same as the default state where no radius was ever set.

**Review by apeatling — APPROVED** [review]
Looks good to me and makes sense :+1:

**Pull request merged**
