### PR TITLE
Add new wrapContents prop to PluginSidebar

### PR DESCRIPTION
**Pull request by ryanwelcher**
## What?
This PR is an attempt at the implement for the solution proposed in #64272 to allow developers to define a basic UI wrapper for the content of a PluginSidebar.

## Why?
As mentioned in #64272 this is a much better developer experience.

## How?

I have added a new `wrapContents` prop that if true, will wrap the `children` of the `<ComplementaryArea />` component in a `<PanelBody>` component. `wrapContents` is false by default for backwards compatibility with existing implementations.

## Testing Instructions
1. Checkout this branch
2. Register a new PluginSidebar ( code I tested with is below )
3. Confirm that when `wrapContents` is `true`, the content are wrapped (see screenshot below)
4. Confirm that when `wrapContents` is `false`, the content are NOT wrapped (see screenshot below)

### Code 

```jsx
import { registerPlugin } from '@wordpress/plugins';
import { PluginSidebar } from '@wordpress/editor';
import { __ } from '@wordpress/i18n';
import { Button, TextControl, SelectControl } from '@wordpress/components';
import { useState } from '@wordpress/element';

registerPlugin( 'wraps-content', {
	render: () => {
		const [ text, setText ] = useState( '' );
		const [ select, setSelect ] = useState( 'a' );

		return (
			<PluginSidebar
				name="wraps-content"
				title="My sidebar title"
				wrapContents
			>
				<h2>
					{ __( 'This is a heading for the PluginSidebar example.' ) }
				</h2>
				<p>
					{ __(
						'This is some example text for the PluginSidebar example.'
					) }
				</p>
				<TextControl
					label={ __( 'Text Control' ) }
					value={ text }
					onChange={ ( newText ) => setText( newText ) }
				/>
				<SelectControl
					label={ __( 'Select Control' ) }
					value={ select }
					options={ [
						{ value: 'a', label: 'Option A' },
						{ value: 'b', label: 'Option B' },
						{ value: 'c', label: 'Option C' },
					] }
					onChange={ ( newSelect ) => setSelect( newSelect ) }
				/>
				<Button variant="primary">{ __( 'Primary Button' ) } </Button>
			</PluginSidebar>
		);
	},
} );
```

### wrapContents is true
Cursor_and_Edit_Post_“BlockEditChildren”_‹_Gutenberg-works_—_WordPress

### wrapContents is false
Cursor_and_Edit_Post_“BlockEditChildren”_‹_Gutenberg-works_—_WordPress_and_index_js_—_gutenberg-no-upstream2__Workspace_
st

### CODE REVIEW

**Comment by mtias** [comment]
It seems this should likely be the default and the opposite case (I need no padding at all because I'll handle stuff) to be an opt-out prop. Handling this through props is also not ideal. If there's a semantic need to have PanelBody we should encourage that explicitly. And if there is not, we should just make PluginSidebar have padding by default. Maybe the prop is more around spacing — cc @WordPress/gutenberg-components

**Comment by ryanwelcher** [comment]
> It seems this should likely be the default and the opposite case (I need no padding at all because I'll handle stuff) to be an opt-out prop.

I agree completely but the issue is that all of the current implementations will get their UI "double wrapped" if it's opt-out.

**Comment by mirka** [comment]
There is no semantic need to use `PanelBody`, but we have to remember that the core sidebar layouts are all based on the collapsing `PanelBody` pattern. Having padding by default on the entire sidebar would make it very hard to use collapsing `PanelBody`s at all, since they are designed to be full-width.

Also, the devex isn't going to be as simple as "the container padding is enabled by default so I can just place my controls in there". There is still the problem of achieving consistent spacings between the controls. That's what `PanelRow` can do.

Sidenote: However, the controls layout situation in the sidebar is currently a mess. Some components have bottom margins built in, which we are on the way to deprecating (#39358). On top of that, WordPress automatically applies a bottom margin on certain components (those based on `BaseControl`) in the sidebar, but not all. This makes it very hard to lay out components in a consistent, modern way like flex containers with `gap`s, or even with `PanelRow`s. We're working on it.

**Review by tyxla — COMMENTED** [review]
My $0.02: here's another group of reasons to consider this `wrapContents` prop unnecessary:

* The most basic `PluginSidebar` example already includes `PanelBody`. If there are any examples that don't use it, we could update them.
* Having the panel body wrapper is achieved with basic component composability. Having the flexibility to compose components provides a better developer experience and a more expressive API than an arbitrary prop.
* This adds an extra way to add a `PanelBody` wrapper, which is unnecessary ambiguity, and that would contradict the [WordPress philosophy](https://wordpress.org/about/philosophy/#:~:text=Decisions%2C%20not%20options) without a good reason.

**Comment by ryanwelcher** [comment]
Thanks for the feedback everyone! Based on them, I'll close this out in favor of ensuring we have better examples in the docs.

**Pull request closed without merging**
