### PR TITLE
Migrate/shortcut help

### PR DESCRIPTION
**Pull request by alvitazwar**
## What?
Based on https://github.com/WordPress/gutenberg/pull/38570, part of https://github.com/WordPress/gutenberg/issues/38851. Migrate [shortcut-help.test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/shortcut-help.test.js)
## Why?
See https://github.com/WordPress/gutenberg/pull/38570 for its background and rationale.

This is split into a new PR for easier review.

## How?
See https://github.com/WordPress/gutenberg/pull/38570 for the proposed migration steps.

## Testing Instructions
 npm run test:e2e:playwright /test/e2e/specs/editor/various/shortcut-help.spec.js
## Screenshots or screencast 

https://user-images.githubusercontent.com/55917380/204663597-725e3ff0-abca-4d87-bb26-586b68cfd18f.mov

### CODE REVIEW

**Comment by alvitazwar** [comment]
@Mamaduka  Can you please take a look on this?

**Review by Mamaduka — COMMENTED** [review]
@alvitazwar, the migrated tests seem to be failing. Do you mind checking again if they run locally for you?

**Comment by stokesman** [comment]
I've picked this up over in #53832. I tried pushing changes here but it didn't work 🤷. The new branch is based on this one so @alvitazwar’s commits are preserved.

**Comment by Mamaduka** [comment]
Closed in favor of #53832.

**Pull request closed without merging**
