### PR TITLE
Add fallback to old gallery edit and save for existing gallery

### PR DESCRIPTION
**Pull request by glendaviesnz**
Related to [refactor of Gallery block to nest image blocks](https://github.com/WordPress/gutenberg/pull/25940).

Because the Gallery refactor is a major braking change, this PR:

- Adds a fallback to the old gallery edit and save functions for existing block content rather than transforming them. 
- Adds an experimental flag so users can opt in to show the refactored Gallery block for new blocks.

### To test

Check out this PR

- Add some markup from existing gallery versions to the editor code view (you can find current and old gallery markup [in the fixtures folder](https://github.com/WordPress/gutenberg/tree/master/packages/e2e-tests/fixtures/blocks)).
- Exit code view and make sure the Gallery has not been transformed into the new InnerBlocks format. Check it can be edited, new images added via media dialog and drag and drop, and displays in front end correctly.
- Add a new Gallery and make sure it is also the existing format.
- Toggle the `Enable the refactored gallery block` experiments flag in `wp-admin/admin.php?page=gutenberg-experiments` and make sure that adding a new gallery adds the refactored gallery block and that it is full functional.

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
Maybe instead of `-v1` files we just leave all the v1 files in a single subfolder `v1` or `old` or something like that?

**Comment by glendaviesnz** [comment]
> Maybe instead of `-v1` files we just leave all the v1 files in a single subfolder `v1` or `old` or something like that?

nice, that is tidier, will do that.

**Comment by andrewserong** [comment]
This is testing well for me manually, @glendaviesnz, and respects having a v1 and v2 gallery in the same post, which is nice! It was also good to see that even if I switched off the experiment, the v2 gallery continues to render correctly on the front end of the site. The addition of the `edit-wrapper` file and feature flag feels like a clean way to keep both versions in the repo, but neatly separated, too 👍

**Review by youknowriad — APPROVED** [review]
Let's get this merged to the other PR, the diff of the other PR will get clearer :)

**Pull request merged**
