### PR TITLE
Global Navigation: Fix to Page List

### PR DESCRIPTION
**Pull request by scruffian**
WIP

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for the PR!

Here's a quick GIF showing this page list replacement:

state

It may be worth restating some of the context for the navigation section. It looks like it won't make it for 6.2, but it'll be useful for future reintroductions.

The way I think about it is that the Site Editor is a high level, well, _site editor_. That means upon entering it, with the main navigation pieces on the left and the site preview on the right, it is laid out that way to indicate: you are seeing your whole site, not just one particular template. A _Design → Navigation_ section should lean into this, as should a future [Design → Styles](https://github.com/WordPress/gutenberg/pull/49014#issuecomment-1467612155) section.

It's the the idea that when you are editing your whole site, you are in this receded high level view, whereas the fullscreen view is a more in-depth view. In that light: locking the navigation section to showing a page list (i.e. all the pages and the basic structure of your site), can make sense. Every website has a "physical" structure. If a contact page is published, it exists on `/contact/`, if an About page is published, it exists on `/about/`. This is true regardless of any customized menus you have. The section is about the structure of your site, even if it might also be about your menu.

Another benefit of having a section such as this, is the content editing aspect. This is a major motivation for the inclusion of the section, making the site editor about truly _editing your site_, not just templates. 

As is, this PR accomplishes that. (The locks would be good to hide.)

Given we'll have some time to refine this before 6.3, however, it would be good to restate and revisit these values, and how it relates to menu editing. Given this is a receded view, perhaps the more locked-in structure of the Page List interface fits well with the receded view? Or do we eventually allow a fuller editing interface, similar to what is shipping in the plugin at the moment? There are pros and cons to both.

If it's purely a page list:

* Reordering can exist, through changing the `order` metadata of pages
* The "Add new page" can start the "new page" flow, perhaps open a modal with page templates and let you edit the new page directly in the site editor. 
* Properties such as "Set as home page" or "Set as posts page" can exist, as it becomes more about site structure than it does about menu editing.
* It has been true of WordPress for more than a decade that until you actually create a custom menu, your menu is made up by the pages you've published. This section could reflect that truth.
* This PR would not necessarily preclude the section being upgraded to have custom menu edting capabilities in the future, perhaps with a site structure/main menu switcher interface. Things like Site Logo and Social Links could still show up in custom menus and still be reorderable, ,ut instead of being editable there, they’d be grayed or locked, and steer you towards fullscreen editing inside a template part if you need to customize. I.e. similar to the _detail page with edit button_ concept the other sections have: receded editing only.
* It might even be an opportunity to simplify or clarify the “lightweight menu” editing flow that has occasionally been a soiurce of confusion (where if your menu only has page links, the plusimmediately insert a page link, and only if the menu has non-page links will the plus opens the inserter). This clarity could lock the pages-only behavior to the receced view, and the full inserter to the fullscreen view.

It would be good to mock up all the flows here to boost our confidence. CC: @WordPress/gutenberg-design

**Comment by jameskoster** [comment]
In the 6.2 scope this felt like a potential alternative to what we have on trunk. But since the Navigation panel [has been pulled](https://github.com/WordPress/gutenberg/pull/49043), I agree that we should take the time to continue design explorations.

**Comment by paaljoachim** [comment]
I look forward to seeing smaller pieces of the various descriptions Joen mentioned. As it fairly quickly goes over my head...:)

**Comment by SaxonF** [comment]
For comparison I created a branch `update/global-navigation-to-pages` that uses same list system as templates/template-parts rather than blocks, it also adds an "add page" action. It takes you to drill down view where we could explore template selection as part of new page flow.

I suppose it really depends on where we want this experience to go as to whether we use page list block vs generic menu list. i'd expect the behaviour between lists like templates, template parts, pages and whatever else comes next to be consistent.

https://user-images.githubusercontent.com/1072756/225178974-fce91025-9ce8-459d-bf02-a585aa9021bd.mp4

**Comment by jasmussen** [comment]
I feel really reluctant to call this "Pages", because of its duplication with what's at the top level. I do think there's a future where these two main sections converge in some form or other. But in my mind, the Navigation section is not just about pages, it's also about the Home page, and the Posts page, and the properties we can surface for those two. While those are technically _pages_, they are also partially templates, making it appropariate to surface them here as something else entirely.

To be sure, content access in the site editor has come up a number of times, but if we want to solve that separately from the navigation piece, it should be visually separated from the other main sections, so that it can be denoted as a more temporary thing. 

I do really like the idea that the plus _creates a new page_, and I think we can merge that concept with having a "Navigation" or "Structure", or "Sitemap", whatever is the best term. Navigation and "menu" verbiage may have confused people to think that the section is mainly about editing your menu — I see that as an optional bonus to actually surfacing the physical structure of your site.

**Comment by scruffian** [comment]
Closing this until we have a more clear direction.

**Pull request closed without merging**
