### PR TITLE
[Enhancement] Establish consistency regarding alignment options between the archives and categories blocks

### LINKED ISSUE #9413: Sync up alignment options for the Archives and Categories blocks
**Describe the bug**

The Archives block currently contains options for Left, Center, and Right alignment: 

screen shot 2018-08-28 at 3 38 09 pm

The Categories block currently contains those same options, but also includes "Full" alignment:

screen shot 2018-08-28 at 2 45 14 pm

Since these blocks are similar in function and appearance, we should sync up these alignment options. To do so, I suggest we remove the "Full" alignment from the Categories block — it doesn't seem like it'd be a frequently used setting for a list.

### PR DESCRIPTION
**Pull request by nfmohit**
## Description
This PR closes #9413 which suggests the sync up of alignment options in the archives and categories blocks. This removes the "Full" alignment option from the categories block so it stays consistent with the archives block.

## How has this been tested?
This PR has been tested by going through the following steps:

1. Started a new post using the Gutenberg editor.
2. Added the "Categories" block.
3. Made sure that the "Full" alignment option doesn't show up in the block alignment toolbar.

## Screenshots 
pull-9413

## Types of changes
This PR just removes the `full` option from the `controls` parameter that defined the alignment options in the "Categories" block.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by gziolo** [comment]
This PR needs to be updated to work with the current implementation ogf Category block.

**Review by gziolo — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by nfmohit-wpmudev** [comment]
Thank you for the heads-up @gziolo, a refresh is coming up real soon  ❤️

**Comment by nfmohit-wpmudev** [comment]
PR refreshed, thank you for the review @gziolo ❤️

**Review by gziolo — APPROVED** [review]

**Comment by nfmohit-wpmudev** [comment]
Thank you for the merge and for your kind words @gziolo ❤️

**Pull request merged**
