### PR TITLE
Block Library: Fix archive block classes (#26349)

### PR DESCRIPTION
**Pull request by fklein-lu**
## Description

Issue #26349 describes how Archive blocks have an extra space before the first class. So currently the output is `class=" wp-block-archives-list wp-block-archives"`.

By using an array for constructing classes instead of string concatenation, this issue can be avoided.

This PR also fixes the escaping to always be late, and adds PHP unit tests for good measure.

## How has this been tested?
- PHP unit test.
- Manual test:
  - Open the post editor and add an Archives block.
  - View the post on the frontend and note the classes have no prepended space anymore.

## Types of changes

Bug fix, no breaking changes.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by fullofcaffeine** [comment]
This seems to work well! I tested one of the problematic blocks with Gutenberg 9.2.0 and after applying this fix, the class doesn't have the leading space anymore.

| Vanilla GB 9.2.0  | This branch |
| ------------- | ------------- |
| beforefix | fixapplied |

I don't have the permissions to approve this PR, and I'd rather leave the final decision to one of the core devs, but looks good so far.

**Comment by ockham** [comment]
Possibly fixed by #26309?

**Comment by ockham** [comment]
> Possibly fixed by #26309?

Confirming that the tests added by this PR pass if run against `master` (with #26309 merged).

**Comment by ockham** [comment]
> > Possibly fixed by #26309?
> 
> Confirming that the tests added by this PR pass if run against `master` (with #26309 merged).

Interestingly, I still see a leading space when running tests on our (closed) CI system: https://github.com/WordPress/gutenberg/pull/26309#issuecomment-714586966 :thinking:

**Comment by gziolo** [comment]
@fklein-lu, can you rebase this PR. It looks like the block's `render_callback` was fixed as @ockham mentioned but we would still benefit from having this unit test added.

**Review by sirreal — APPROVED** [review]
I'm not very familiar with the php unit tests, but this seems fine to me. Thanks!

**Comment by Mamaduka** [comment]
Hi, @fklein-lu

Can you rebase this PR? I think we're good to merge.

**Pull request closed without merging**
