### PR TITLE
Don’t use TypeScript files in scripts package

### PR DESCRIPTION
**Pull request by swissspidy**
## What?

This is a follow-up to #53108, where I added TS files to the scripts package instead of plain JS files.

## Why?

I just realized that the scripts package is not using TypeScript, so these files were not converted to JS on build.

## How?

Converts the two files to plain old JS files.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]

**Comment by Mamaduka** [comment]
@mikachan, can we include this in the beta 2 package release? It doesn't affect WP itself, just a tooling-related change.

**Comment by mikachan** [comment]
Yes this can be included, just wrapping up the final batch of commits for Beta 2 now 👍

**Comment by Mamaduka** [comment]
Thank you, @mikachan!

**Comment by mikachan** [comment]
I just cherry-picked this PR to the commits-for-6.4-beta2 branch to get it included in the next release: c4ffd4ac4b

**Pull request merged**
