### PR TITLE
Add 'It's Time' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a block pattern for #20345.

Screen Shot 2020-03-24 at 11 42 58

### CODE REVIEW

**Review by mtias — APPROVED** [review]

**Comment by mtias** [comment]
Let's get this one in @enriquesanchez :)

**Comment by mtias** [comment]
This one should have some line-height adjustments for when it breaks into two lines:

image

**Comment by mtias** [comment]
@enriquesanchez also why is there an empty column on the left set to zero value?

image

**Comment by mtias** [comment]
We should also really not do this :) A spacer would be better.

image

**Comment by enriquesanchez** [comment]
@mtias oh, I totally forgot about that hidden "space" :) I was messing with and trying different ways of aligning things. I'll open a new PR to fix that and adjust the line-height.

As for the empty column, it was recommended to me as a hack to to have the text expand full width. If I were to use a paragraph block, its width would be very narrow and limiting.

**Comment by ZebulanStanphill** [comment]
>As for the empty column, it was recommended to me as a hack to to have the text expand full width. If I were to use a paragraph block, its width would be very narrow and limiting.

Huh? Why would it be narrow?

**Pull request merged**
