### PR TITLE
[RNMobile] Fix broken "Link To" settings and add "Image Size" settings

### LINKED ISSUE #23576: [Mobile] Gallery "Link To -> Attachment Page" option not creating an anchor
**Describe the bug**
The "Link To" setting for Gallery block is not working for the "Attachment Page" option.

**To reproduce**
1. Create a Gallery block with a few images
2. Tap the settings gear
3. Tap the "Link to" setting and select "Attachment Page"
4. Save the post
5. Preview the post on web

**Expected behavior**
The images in the gallery should link to the respective attachment page

**Smartphone (please complete the following information):**
* Device: Pixel 3a
* OS: Android 10 - Device: [e.g. iPhone6]

**Additional context**
This seems to primarily affect self-hosted sites, since .com sites appear to use a separate mechanism to display the images (via JS instead of an anchor).

In debugging this a bit, I discovered that this issue is not present for gallery images that have completed uploading while the editor is closed. The processor is adding the data-link attribute, which I believe is absent from the media upload object returned to the editor when completed while the editor is open.

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes: https://github.com/WordPress/gutenberg/issues/23576

## Related PRs

* `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4841

## What?

This PR fixes the native version of the Gallery block's broken **Link To** settings and also adds **Image Size** settings.

## Why?

The reason that the settings are broken in the native version of the block is that `per_page=-1` (an unbounded query) is used when fetching the gallery's images. Unbounded queries aren't currently supported on the native side, as per the open issue at https://github.com/wordpress-mobile/gutenberg-mobile/issues/2661.

Updating the query, not only fixes the broken **Link To** settings, but also enables support for the **Image Size** settings, which become visible in the native block's settings.

## How?

With this PR, the unbounded query is replaced with `imageIds.length` to fix the issue on native. This approach was chosen as it was initially suggested here: https://github.com/WordPress/gutenberg/pull/34389#issuecomment-938553026

## Testing Instructions

* In the iOS or Android app, add a Gallery block with a few images.
* Tap the settings gear.

### 1. Link To Settings

* Tap the **Link To** setting and select one of the options.
* Save the post.
* Tap the ellipsis in the app's upper right and select **Switch to HTML Mode**.
* Confirm that the appropriate `<a href="URL">` tags are surrounding the gallery's images.

### 2. Image Size Settings

* Tap the **Image Size** setting and select one of the options
* Save the post.
* Tap the ellipsis in the app's upper right and select **Switch to HTML Mode**.
* Confirm that the appropriate class (e.g. `size-large` if **Large** was selected) has been added to the HTML for the gallery's images. 

### 3. Regression Testing

We should confirm that the Gallery block still works the same as it did before on the web, by experimenting with the its settings with this branch checked out on the web.

## Screenshots or screencast 

You'll see that the `<a href="URL">` tags are correctly added when using the **Link To** settings within the app: 

https://user-images.githubusercontent.com/2998162/167485223-c0a12b61-2222-4969-8660-5e266532786d.mov

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks for the ping, @SiobhyB.

I wasn't aware that unbounded queries aren't supported on the native side.

I just merged a small improvement for the gallery, and it caused the merge conflict - #40945. But I think we should be good to merge this after the conflict is resolved.

**Comment by SiobhyB** [comment]
@Mamaduka, thanks so much for taking a look! I hadn't been aware that unbounded queries were unsupported on native until diving into this bug either.

> I just merged a small improvement for the gallery, and it caused the merge conflict - https://github.com/WordPress/gutenberg/pull/40945. But I think we should be good to merge this after the conflict is resolved.

Appreciate the heads-up, I've gone ahead to resolve the conflict now. 🙇‍♀️ Let me know if anything looks off or if you spot any regressions on the web-side that I may have missed.

_Aside: Looking at the changes in https://github.com/WordPress/gutenberg/pull/40945, I'm wondering if the introduction of `per_page=-1` in `use-short-code-transform.js` may also cause an issue on the native side. I'll do some testing and either follow up on that issue (if all looks good) or with a separate PR if I spot a regression._

**Comment by Mamaduka** [comment]
It might be a good idea to update `useShortCodeTransform` as well, just to be on the safe side 👍

**Comment by SiobhyB** [comment]
Thanks @Mamaduka, after some quick testing, I confirmed what seemed to be an issue there as well, so updated in https://github.com/WordPress/gutenberg/pull/40947/commits/b89791bafb555732be6ce9ad9f315fafb21f8147. Let me know if all looks okay to you or if anything needs tweaking!

**Review by Mamaduka — APPROVED** [review]
Thanks, @SiobhyB. The code looks good and tests well for me on the desktop.

**Review by mchowning — APPROVED** [review]
Code looks good and is working well in my tests. Nice job @SiobhyB ! 👍

**Pull request merged**
