### PR TITLE
[RNMobile] Update Slider to reflect changes immediately

### LINKED ISSUE #2192: Update Slider to reflect changes immediately
Can we make Slider to reflect changes immediately without needing to wait for the hand gesture to end?

### PR DESCRIPTION
**Pull request by dratwas**
## Description
This PR fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2192
gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2286

In this PR i use `onValueChange ` instead of `onSlidingComplete ` to set the value.

<details>
 <summary>Outdated</summary>
Unfortunately in the current state, it is laggy because of performance issues in block-list. (The whole app is re-rendered on every change). I tried these changes with that PR (https://github.com/WordPress/gutenberg/pull/22144) - and it works much better. I suggest merging the PR with optimization first.
</details>

I need to NOTE that it is not a performant way of doing that kind of thing in React Native since the communication is async and we can lose frames. Especially in our case, because there are a lot of things that happen on each change of attribute. We shouldn't rely on the value from redux when we "animate" the height etc. It doesn't mean that we shouldn't use `onValueChange` instead of `onSlidingComplete` but we should change how it is handled in Block. As an example, In the spacer block, we could rely on the local state and set the attribute with a debounce effect. Thanks to that the height should be more responsive because right now I can feel the delay.

There is also an issue with the undo mechanism that I described here - https://github.com/wordpress-mobile/gutenberg-mobile/issues/2192#issuecomment-630010164

This issue was fixed, however it introduced a regression and had to be reverted.

## How has this been tested?
- open mobile app
1.
- add spacer block
- open settings of the spacer block
- change the height of spacer - change should be visible while moving the slider
- change the height a few time more
- press on the undo button - the height should be reset to initial one
- the undo level should be created only when we change a different attribute
2.
- add button block
- open settings of that button
- change the border-radius -  change should be visible while moving the slider
- the undo level should be created only when we change a different attribute
3.
- add spacer block and open settings
- change the input value to less than minimum value i.e `2`
- the slider should show the minimum value (20)
- the height of the block should be changed to the minimum value (20)
- there should be a possibility to change the input value
- after return, if the input value is lower than the minimum value then is set to minimum and the same with the maximum limit

<details>
 <summary>Outdated</summary>
In the current state, the undo level is created for every change that means 10 undo levels will be created when sliding from 0 to 10 (https://github.com/wordpress-mobile/gutenberg-mobile/issues/2192#issuecomment-630010164)
</details>

## Screenshots 

without optimization | with optimimsation
--- | ---
slideiosbefore | sliderios

## Types of changes
Update Range Control to reflect changes immediately

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by geriux — APPROVED** [review]
LGTM! 

One thing to mention for future references is that the PR description is a bit outdated because both the [block list optimization](https://github.com/WordPress/gutenberg/pull/22144) and the [transient edits](https://github.com/WordPress/gutenberg/pull/22492/files) issues were addressed. ✅

> I need to NOTE that it is not a performant way of doing that kind of thing in React Native since the communication is async and we can lose frames. Especially in our case, because there are a lot of things that happen on each change of attribute. We shouldn't rely on the value from redux when we "animate" the height etc.

I agree with this, luckily after the optimizations you did in the other PRs it is working fine for these cases. But definitely something to keep in mind.

I tested the `Spacer` `Buttons` and `Cover` blocks on both main apps and demo for iOS and Android.

Great work @dratwas !

**Review by lukewalczak — CHANGES_REQUESTED** [review]
Observing changes immediately looks good in blocks such as Spacer or Button 🎉 
However, I have found one issue - using input next to the slider value cannot be changed to eg. `22`, _gif for the reference_:

**Comment by dratwas** [comment]
Thanks for your review!

@lukewalczak I pushed new changes that fix the issue you mentioned. Could you please check it? :)

**Review by lukewalczak — APPROVED** [review]
Input issue is fixed! 🎉

**Comment by dratwas** [comment]
Hey @lukewalczak could you please re-check that one more time? After a long time all blockers are resolved and I updated this PR :)

**Comment by lukewalczak** [comment]
I've observed one more issue: there is an option to add mutiple `dots` in input next to the slider. Please check that

**Comment by dratwas** [comment]
Hey, @geriux could you please check this PR one more time? Luke is on holidays now :) I already fixed the issue with multiple dots. Now adding of dots is not allowed if the `toFixed` prop is not set.

**Comment by geriux** [comment]
> Hey, @geriux could you please check this PR one more time? Luke is on holidays now :) I already fixed the issue with multiple dots. Now adding of dots is not allowed if the `toFixed` prop is not set.

Of course! will do 👍

**Review by geriux — APPROVED** [review]
LGTM!

Tested it on both iOS and Android, following the test cases and also different tests with Cover, Columns / Column (Using decimals), Latest posts, and Buttons block.

Nice work!

**Pull request merged**
