### PR TITLE
RNMobile: Add integration test to verify button block border radius functionality

### LINKED ISSUE #3667: [Integration test] Buttons block - Breakage case - Border radius changes are not being stored
**PR where the breakage was fixed:** https://github.com/WordPress/gutenberg/pull/32717

## Tasks
1. Identify the block/component that is affected.
1. Add a test file for covering the breakage in the block/component folder.
1. Run the test and verify that it passes.
1. Revert the changes made for the fix.
1. Run the test again and verify that it fails.
1. _(Bonus)_ Add more test cases to the block/component.
1. Celebrate 🥳 !

### Notes
- If a test already exists in the block/component folder, review if the test cases can be migrated to the integration test.
- Some functionality might be not possible to replicate in the integration tests. In that case, indicate the blockers in the issue.

### PR DESCRIPTION
**Pull request by guarani**
#### [NEW] Button block border radius tests

Adds a test to the button block on mobile to ensure button radius changes are saved properly. Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/3667.

#### [BUGFIX] Reusable block tests

The test should assert the existence of a React element but because of a missing `await`, was instead asserting an unresolved Promise instead. Since the unresolved Promise is a value, `toBeDefined` was returning `true` and the test was passing.
Fixing the test involved resolving the Promise using `await` so that what's asserted is an actual React element.

#### [NEW] Button block border radius tests

1. Revert the changes made for the [Fix: RNMobile borderRadius value setting](https://github.com/WordPress/gutenberg/pull/32717). The easiest way to do this is to apply this patch (which takes care of resolving conflicts):

```
commit a44a42614abfb01b36865f100b7652f36afa045b
Author: Paul Von Schrottky <paul.von.schrottky@automattic.com>
Date:   Fri Jul 9 15:50:40 2021 -0400

    Revert " Fix: RNMobile borderRadius value setting (#32717)"
    
    This reverts commit 4f9097daf6868669c7b4e77fa1f45fb41a94288a.

diff --git a/packages/block-library/src/button/edit.native.js b/packages/block-library/src/button/edit.native.js
index 923ed47282..3af54435fe 100644
--- a/packages/block-library/src/button/edit.native.js
+++ b/packages/block-library/src/button/edit.native.js
@@ -236,18 +236,11 @@ class ButtonEdit extends Component {
 		setAttributes( { text: value } );
 	}
 
-	onChangeBorderRadius( newRadius ) {
-		const { setAttributes, attributes } = this.props;
-		const { style } = attributes;
-		const newStyle = {
-			...style,
-			border: {
-				...style?.border,
-				radius: newRadius,
-			},
-		};
-
-		setAttributes( { style: newStyle } );
+	onChangeBorderRadius( value ) {
+		const { setAttributes } = this.props;
+		setAttributes( {
+			borderRadius: value,
+		} );
 	}
 
 	onShowLinkSettings() {
@@ -382,7 +375,7 @@ class ButtonEdit extends Component {
 		const {
 			placeholder,
 			text,
-			style: buttonStyle,
+			borderRadius,
 			url,
 			align = 'center',
 			width,
@@ -394,8 +387,6 @@ class ButtonEdit extends Component {
 			return null;
 		}
 
-		const borderRadius = buttonStyle?.border?.radius;
-
 		const borderRadiusValue = Number.isInteger( borderRadius )
 			? borderRadius
 			: styles.defaultButton.borderRadius;

```
2. Optional: Verify that the [Buttons block - Border radius changes are not being stored](https://github.com/WordPress/gutenberg/issues/32701) bug is again present.
3. Run the new test (which should fail):

```
npm run test-unit:native packages/block-library/src/buttons/test/edit.native.js
```
4. Discard the patch changes and re-run the text (it should now pass)

#### [BUGFIX] Reusable block tests

Run the test and ensure it passes:
```
npm run test-unit:native packages/block-library/src/block/test/edit.native.js
```

## Types of changes
- A new integration test and a fix to an existing test

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by fluiddot** [comment]
I noticed when running the integration test that the following console error is logged:
```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
```

I think it was caused by the `useResizeObserver` mock because we're returning a Jest mock function as the first item:
https://github.com/WordPress/gutenberg/blob/cb25feffa9c9f177733c48c871640545f51ae1d8/test/native/setup.js#L199
However, per the original code, we should return a JSX element:
https://github.com/WordPress/gutenberg/blob/dd4ce77932f4d002f0681d067273ee3061bddf47/packages/compose/src/hooks/use-resize-observer/index.native.js#L51-L55

**Comment by fluiddot** [comment]
> I noticed when running the integration test that the following console error is logged:
> 
> ```
> Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
> ```
> 
> I think it was caused by the `useResizeObserver` mock because we're returning a Jest mock function as the first item:
> https://github.com/WordPress/gutenberg/blob/cb25feffa9c9f177733c48c871640545f51ae1d8/test/native/setup.js#L199
> 
> 
> However, per the original code, we should return a JSX element:
> https://github.com/WordPress/gutenberg/blob/dd4ce77932f4d002f0681d067273ee3061bddf47/packages/compose/src/hooks/use-resize-observer/index.native.js#L51-L55

I fixed the issue in [this commit](https://github.com/WordPress/gutenberg/pull/33211/commits/dc934033106b8c340de94c85d4f1360e4b3714ca).

**Review by fluiddot — APPROVED** [review]
Awesome work @guarani 👏 !
LGTM 🎊 !

**Comment by fluiddot** [comment]
An important thing that we should keep an eye on is the integration tests duration, for this case, the duration is around `600 ms`.

**Comment by guarani** [comment]
Thanks for fixing that console error. I'd seen it but hadn't checked if it was new or not.

> An important thing that we should keep an eye on is the integration tests duration, for this case, the duration is around `600 ms`.

I'll keep an eye on this. While the tests themselves are quick, the entire execution time (from when I execute the command till when it finishes) is quite long. I see 59.19 seconds for a run of a single test.

**Comment by fluiddot** [comment]
> Thanks for fixing that console error. I'd seen it but hadn't checked if it was new or not.

I think it was introduced when I added the `useResizeObserver` mock so it was new.

> > An important thing that we should keep an eye on is the integration tests duration, for this case, the duration is around `600 ms`.
> 
> I'll keep an eye on this. While the tests themselves are quick, the entire execution time (from when I execute the command till when it finishes) is quite long. I see 59.19 seconds for a run of a single test.

I experienced the same, however, in the CI, running all the tests take less time 😄 (probably thanks to the Jest cache):
Screenshot 2021-07-14 at 09 37 29


**Buttons block - Integration test:**
Screenshot 2021-07-14 at 09 37 20

**Pull request merged**
