### PR TITLE
Docs: Minor copy edits for the Block Development Environment page

### PR DESCRIPTION
**Pull request by ndiego**
This PR makes some minor copy changes to [Block Development Environment](https://developer.wordpress.org/block-editor/getting-started/devenv/) page to improve readability. One line is also turned into a callout.

### CODE REVIEW

**Comment by desrosj** [comment]
👋 Sorry for any noise. I'm using this draft PR as a way to test a few changes to Props Bot.

**Review by fabiankaegy — APPROVED** [review]
Looks good 👍

**Comment by ndiego** [comment]
@desrosj should I wait to merge this (once approved) until you are done testing? If so, just ping me when the coast is clear.

**Comment by desrosj** [comment]
Just seeing this, but merging was totally fine! I was able to get everything sorted out (see #58617).

**Pull request merged**
