### PR TITLE
Use an expandable panel for the post visibility

### PR DESCRIPTION
**Pull request by youknowriad**
related https://github.com/WordPress/gutenberg/pull/3036#issuecomment-337178253

This updates the design of the publish dropdown and also fixes the double popover issue.

screen shot 2017-10-17 at 12 12 46

**Notes**

The next step would be to do the same for the PostSchedule component

### CODE REVIEW

**Comment by jasmussen** [comment]
I can't believe how fast you are. Wow. 

I do like this, I think it works really well. Can the same be done for the calendar dropdown? 

I also noticed that if you set your post to private, it asks to publish immediately. I can't recall the context for that — but it seems iffy in this context.

**Comment by karmatosed** [comment]
Ditto on the fast work, this is ace!

**Comment by youknowriad** [comment]
> Can the same be done for the calendar dropdown?

Yes, Just wanted to split the work into two PRs

**Comment by jasmussen** [comment]
Then go forth and conquer!

**Pull request merged**
