### PR TITLE
Shortcuts: Add Ctrl+Y for redo to all editor instances on Windows

### PR DESCRIPTION
**Pull request by t-hamano**
Part of #43352
Follow-up on #42627

## What?

This PR adds `Ctrl+Y` for redo to all editor instances on Windows.

## Why?
The redo shortcut by `Ctrl+Y` was added by #42627, but I found that it doesn't work outside of the post editor.

## How?
Added as an alias as well as the post editor.

## Testing Instructions
This test can only be performed on Windows, but please make sure that redo by `Ctrl+Y` is performed on all instances of the editor.

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
DID NOT TEST, but code looks good 👌🏻

**Comment by t-hamano** [comment]
@draganescu 
Thanks for the code review!
I would like to merge this PR, but I will be waiting for at least one more Windows user to test it.

**Comment by t-hamano** [comment]
I have merged the latest trunk into this PR and the shortcut appears to be working as expected with this PR change.
If there are no concerns I would be willing to merge.

**Comment by t-hamano** [comment]
I called for testing on Slack, but maybe there is no one who can test on Windows 😅
I would like to merge this PR in hopes of getting feedback.

**Pull request merged**
