### PR TITLE
WordPress 5.8.1 backports

### PR DESCRIPTION
**Pull request by desrosj**
## Description
This cherry picks the following commits to the `wp/5.8` branch for inclusion in WordPress 5.8.1 (RC due out Wednesday, September 1, 2021.

-  #33384
- #33381
- #33498 
- #33549 
- #30617 
- #32083
- #33814 
- #33457 
- #33482
- #33621
- #33699 
- #33618 
- #33679
- #33739 
- #33771
- #33802 
- #34280 
- #34314 
- #34076

Partial cherry pick:
- #32935 (class change in tests)

Trac ticket: https://core.trac.wordpress.org/ticket/54052.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
Screen Shot 2021-08-30 at 21 56 20

It needs to be investigated. It should be an easy fix. We need to add a missing import statement:

```js
import { store as editorStore } from '@wordpress/editor';
```

**Comment by desrosj** [comment]
Also, I know some of the commits cherry picked here were not marked with the label or appropriate milestone. My reasoning for including the first 4 commits in the list above was to avoid some problematic merge conflicts in the other commits that followed these. It may result in a few more packages being updated than necessary for the release, but it will make backporting any PRs with README updates much easier during 5.8.x.

**Comment by paaljoachim** [comment]
Adding also these two Reusable block PRs
**Add Convert to Regular Blocks button to ellipsis Dropdown**
https://github.com/WordPress/gutenberg/pull/32310
and
perhaps also: https://github.com/WordPress/gutenberg/pull/31109#issuecomment-908677124

**Comment by talldan** [comment]
> It needs to be investigated. It should be an easy fix. We need to add a missing import statement

Looks like #30617 depends on #34170, and the latter isn't included in this PR. Adding the missing import would help, but the argument in the calls to `controls.dispatch` and `controls.select` might also need to be changed back to the `editorStore.name` style. I'm not 100% sure though, @gziolo would know better.

**Comment by gziolo** [comment]
> > It needs to be investigated. It should be an easy fix. We need to add a missing import statement
> 
> Looks like #30617 depends on #34170, and the latter isn't included in this PR. Adding the missing import would help, but the argument in the calls to `controls.dispatch` and `controls.select` might also need to be changed back to the `editorStore.name` style. I'm not 100% sure though, @gziolo would know better.

The simpler way would be to access the name of the story through the imported object so we don't have to bring more unrelated code from #34170:

```js
import { store as editorStore } from '@wordpress/editor';

controls.select( edtiorStore.name ).selector();
```

> Also, I know some of the commits cherry picked here were not marked with the label or appropriate milestone. My reasoning for including the first 4 commits in the list above was to avoid some problematic merge conflicts in the other commits that followed these

That's a good strategy. I was initially surprised seeing some of PRs on the list, but it all makes sense 👍🏻

**Comment by talldan** [comment]
> The simpler way would be to access the name of the story through the imported object so we don't have to bring more unrelated code from #34170:

Yep, that's what I was suggesting 😄

**Comment by desrosj** [comment]
> Adding also these two Reusable block PRs
> **Add Convert to Regular Blocks button to ellipsis Dropdown**
> #32310
> and
> perhaps also: [#31109 (comment)](https://github.com/WordPress/gutenberg/pull/31109#issuecomment-908677124)

In my opinion, both of these feel like they are bug fixes by way of enhancement/refinement and I think I'm more comfortable waiting until 5.9 to include these. If a few Gutenberg leads feel that this is important and low risk enough to include, I'm happy to reconsider.

@talldan @gziolo would either of you be able to perform a partial cherry pick of the needed code? It's not clear to me where those imports would need to take place.

**Comment by gziolo** [comment]
@desrosj, any idea why some (or even all) CI jobs run twice when targeting WP release branches?

I added two commits that should make static analysis CI jobs pass.

**Comment by desrosj** [comment]
Thanks!

> @desrosj, any idea why some (or even all) CI jobs run twice when targeting WP release branches?

Ah that is my fault. They are running twice because they are configured to happen on `pull_request`, and `push` events to `trunk`, `release/**`, or `wp/**` branches, and I named my branch `wp/5.8.1-fixes`.

Looks like the performance tests are failing, but the failing test is a timeout. I've restarted it.

**Review by gziolo — APPROVED** [review]
It looks like CI checks pass now so we should be good to go 👍🏻

**Comment by desrosj** [comment]
Just noting that the failing end-to-end tests were run on the `push` event. The ones running for this pull request are passing, so it should be fine to merge.

**Pull request merged**
