### PR TITLE
Updated @since Doc Order in Inline documentation

### PR DESCRIPTION
**Pull request by shail-mehta**
Need to Update  According to Php [Coding Standard](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/) in Below File

- lib/block-supports/block-style-variations.php `@since` Should add before `@see` tag

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think a similar fix needs to be made to the core as well:

https://github.com/t-hamano/wordpress-develop/blob/a27e6a8ecd5279a45e47ef88d048643740d07b5a/src/wp-includes/block-supports/block-style-variations.php#L201

As previously suggested in [this comment](https://github.com/WordPress/gutenberg/pull/66084#pullrequestreview-2364884395), could you submit a core ticket, a core patch, and add a backport changelog to this PR?

**Comment by shail-mehta** [comment]
Thanks for the Feedback.

I forgot to add backport pr changelog url i will update it soon.

**Comment by shail-mehta** [comment]
@t-hamano Thank you for the review.

I have created ticket in core: https://core.trac.wordpress.org/ticket/62730

Here is Pull Request URL in wordpress-develop Repo: https://github.com/WordPress/wordpress-develop/pull/8032  

Also added Backport Changelog in this PR.

**Review by t-hamano — APPROVED** [review]
LGTM 👍 Thanks for the update!

**Pull request merged**
