### PR TITLE
Tooltip: avoid unnecessary re-renders of <select> child elements

### LINKED ISSUE #37856: Changing the unit or value of dimension controls sometimes doesn't work in the site editor
### Description

When I set the value or unit of the padding or margin of a block and try to change it, it reverts to the initial value/unit. 

### Step-by-step reproduction instructions

1. In the site editor go to a group block for example. 
2. Try to set the bottom padding to 5 rem.
3. Save
4. Now try to set the bottom padding to 1 px. Or to 0.
5. It reverts to 5 rem.

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress 5.9 RC-1
- Firefox
- Ubuntu

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix: #37856 / #38113 / #41845

## What?
This PR prevents the `Tooltip` component from re-rendering child components when the children's select list is chosen.

## Why?
Through I was investigating #41845, I found that the behavior of the `onMouseDown` event when a select list is chosen varies from browser to browser.

As mentioned in [this comment](https://github.com/facebook/react/issues/12584#issuecomment-383233455), in Firefox, `onMouseDown` is also fired when a select list is selected.

> Was just having a little poke at this. I believe @skiritsis is on the right track. There are two MouseDown events getting fired. First, a MouseDown fires when the select is initially interacted with and the browser shows the list of values. Second, a MouseDown again fires when any specific value is chosen from that modal list. If you throw a console.log into that handleMouseDown function to output the value of the select list, it will show the correct value prior to the setState() call.

This means that in Firefox, the `onMouseDown` event in `Tooltip` is also triggered when the children's select list is selected.

I'm not sure, but I would expect that the `Tooltip`'s `onMousedown` firing would cause the child component to re-render and the select element's `onChange` event is triggered with the old value.

As far as I know, this problem occurs in the following cases in Firefox:

- When changing the unit for a single direction in `BoxControl` (`BoxControl` has `UnitControl` components surrounded by a `Tooltip`.)
  - #37856
  - #41845
- When there is a `SelectControl` in the `Tooltip` component
  - #38113

## How?
I have made it so that the process is canceled only when the select list is selected in the `onMouseDown` event of the Tooltip component.
I think there is a smarter way to handle this.

## Testing Instructions

- Open Firefox.
- Insert any block.
- From the sidebar, view the item with the `BoxControl` and click "Unlink Sides".
- Confirm that the units in either direction are changed correctly.

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
I tried on my local machine, and I can still replicate the bug — maybe I'm doing something wrong in my testing?

Also, if the problem is caused by the `select` component, should we try to add a fix in select-related components directly? Maybe we could look at calling `stopPropagation` or something like that?

**Comment by t-hamano** [comment]
I have created a video to test the effectiveness of this PR.
I hope these steps prove useful.

(I have tested it on Windows, but since #41845 is reported on MacOS, so I think it isn't an OS issue.)

https://user-images.githubusercontent.com/54422211/179801439-708545ee-3e2e-4c49-806d-4b85d7630943.mp4

> Also, if the problem is caused by the select component, should we try to add a fix in select-related components directly? Maybe we could look at calling stopPropagation or something like that?

`Tooltips` may contain components that are not controlled by Gutenberg, such as pure select elements or select elements from third-party libraries.
Given that, I think the problem needs to be resolved on the Tooltip component side.

**Review by andrewserong — COMMENTED** [review]
What a fascinating problem, thanks for digging in @t-hamano! It looks like it might not just be us struggling with odd behaviour with select elements in Firefox, I found this bug report too, that seems tangentially related: https://bugzilla.mozilla.org/show_bug.cgi?id=1430892

Similar to @ciampo, in testing this PR, I found it a bit unreliable as to when it seemed to fix the issue and when it didn't. When I moved the mouse even slightly while interacting with the `select` component, it would still seem to be behave strangely sometimes resulting in the wrong unit being selected.

If I removed all of the `eventHandlers` from the `Tooltip` component that seemed to fare a little bit better 🤔 

* I think @ciampo makes a good point at seeing what we can do with the components in this repo that use `select` and see if there are fixes we need to implement there. But also:
* The Tooltip component appears to add event handlers in order to emit events to its children — this behaviour seems to have been around a long time, but it also seems like it could be error-prone if it results in firing more events than it really should? Rather than just focusing on a single handler and element, do we need to revisit this behaviour across the `eventHandlers` in the component?
* This might not be at all related, but I noticed that the SelectControl component provides a `noop` function for some of its `on` methods, e.g. [here](https://github.com/WordPress/gutenberg/blob/dfc4b8b8b831c6d5e2c280b06c5871d91e66f337/packages/components/src/select-control/index.tsx#L42) — could the presence of `noop` props be confusing the `Tooltip` component into emitting events when it shouldn't? (This is probably a long shot, but just thought I'd mention it, because I find the logic of the Tooltip component a little challenging to follow)

Not sure if any of that is helpful, but happy to do further testing of this PR tomorrow!

**Comment by aaronrobertshaw** [comment]
Thanks for working on a fix for this @t-hamano 👍 

While investigating https://github.com/WordPress/gutenberg/issues/41845 earlier this afternoon, I found that the border radius control also has the same problem in Firefox that this PR attempts to resolve. A git bisect pointed to the [addition of tooltips around the inner `UnitControl` components](https://github.com/WordPress/gutenberg/pull/40983) and, therefore, their unit selects as well. That appears to fit neatly with the other issues discussed here.

As @andrewserong and @ciampo mention, preventing the issue as close to the source as possible sounds good. I'm not sure  how reliably we can count on that though if a simple `<select>` can be wrapped in a tooltip. 

After checking out this PR I didn't have much success testing. The bug is still present for me.

https://user-images.githubusercontent.com/60436221/179948413-d8c92e22-1d43-4969-942d-1cb921d713be.mp4

**Comment by t-hamano** [comment]
I have tested on [Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-experimental-boxcontrol--default) to clarify the problems we are currently experiencing with `trunk`.

I believe the issue is a problem that occurs when a select element is wrapped in a `Tooltip` (In other words, `BoxInputControls`).
More interestingly, the units can be changed correctly by keyboard operation.

Therefore, I think we need to handle `mousedown` event correctly in `Tooltip` component.

https://user-images.githubusercontent.com/54422211/179960885-d6232f08-eba1-425a-8f29-106acc96f81f.mp4

**Comment by ciampo** [comment]
I gave this PR another spin, and I think that the reason why the fix didn't work for me (or for Aaron and Andrew) is because the same early return added to the `createMouseDown` function, should be also added to the `createMouseUp` function

<details>

<summary>Suggested change</summary>

```diff
diff --git a/packages/components/src/tooltip/index.js b/packages/components/src/tooltip/index.js
index bbe410f50a..840232c248 100644
--- a/packages/components/src/tooltip/index.js
+++ b/packages/components/src/tooltip/index.js
@@ -133,6 +133,10 @@ function Tooltip( props ) {
 	};
 
 	const createMouseUp = ( event ) => {
+		if ( event.target.tagName === 'OPTION' ) {
+			return;
+		}
+
 		emitToChild( children, 'onMouseUp', event );
 		document.removeEventListener( 'mouseup', cancelIsMouseDown );
 		setIsMouseDown( false );
```

</details>

Having said that, I think it still makes sense to investigate a bit further what @andrewserong suggested

> * The Tooltip component appears to add event handlers in order to emit events to its children — this behaviour seems to have been around a long time, but it also seems like it could be error-prone if it results in firing more events than it really should? Rather than just focusing on a single handler and element, do we need to revisit this behaviour across the `eventHandlers` in the component?
> * This might not be at all related, but I noticed that the SelectControl component provides a `noop` function for some of its `on` methods, e.g. [here](https://github.com/WordPress/gutenberg/blob/dfc4b8b8b831c6d5e2c280b06c5871d91e66f337/packages/components/src/select-control/index.tsx#L42) — could the presence of `noop` props be confusing the `Tooltip` component into emitting events when it shouldn't? (This is probably a long shot, but just thought I'd mention it, because I find the logic of the Tooltip component a little challenging to follow)


With regards to where the fix should be applied:

> A git bisect pointed to the https://github.com/WordPress/gutenberg/pull/40983 and, therefore, their unit selects as well. That appears to fit neatly with the other issues discussed here.
> ...
> Therefore, I think we need to handle mousedown event correctly in Tooltip component.

A fix to `Tooltip` could make sense too. As said earlier, in principle it would be good to fix this issue "at the source", although it may not be a perfect solution either, since the bug is related to the native `select` element in Firefox — and therefore, we could still replicate the bug if `Tooltip` was wrapped around a native `<select>`

**Comment by t-hamano** [comment]
@ciampo 

Thank you for the detailed explanation!

> I gave this PR another spin, and I think that the reason why the fix didn't work for me (or for Aaron and Andrew) is because the same early return added to the createMouseDown function, should be also added to the createMouseUp function

May I commit the suggestion and test to see if it has been fully improved in other people's environments?

And I also couldn't think of an appropriate PR title to describe this issue.
If you have a good idea, could you rename the title?

**Comment by ciampo** [comment]
> May I commit the suggestion and test to see if it has been fully improved in other people's environments?

Of course! Feel free to commit and test :) 

If this approach solves the issue, it would be interesting to understand if we can, as a follow-up, rewrite the Tooltip component in a less convoluted way (basically following @andrewserong's [advice](https://github.com/WordPress/gutenberg/pull/42483#pullrequestreview-1044521475)) 

> And I also couldn't think of an appropriate PR title to describe this issue. If you have a good idea, could you rename the title?

I'll see if I can come up with something!

**Comment by t-hamano** [comment]
I have tested again #37856 / #38113 / #41845 which are the subjects of this resolution.
In my environment, they all appear to be resolved by this PR.

**Review by ciampo — APPROVED** [review]
> I have tested again #37856 / #38113 / #41845 which are the subjects of this resolution. In my environment, they all appear to be resolved by this PR.

Those issues seem to be fixed for me as well — thank you for working on this 🚀 

It'd be great if you could work on a follow-up PR with the enhancements suggested in the previous messages.

**Comment by t-hamano** [comment]
> It'd be great if you could work on a follow-up PR with the enhancements suggested in the previous messages.

Is this what you are referring to?

> - The Tooltip component appears to add event handlers in order to emit events to its children — this behaviour seems to have been around a long time, but it also seems like it could be error-prone if it results in firing more events than it really should? Rather than just focusing on a single handler and element, do we need to revisit this behaviour across the eventHandlers in the component?
> - This might not be at all related, but I noticed that the SelectControl component provides a noop function for some of its on methods, e.g. [here](https://github.com/WordPress/gutenberg/blob/dfc4b8b8b831c6d5e2c280b06c5871d91e66f337/packages/components/src/select-control/index.tsx#L42) — could the presence of noop props be confusing the Tooltip component into emitting events when it shouldn't? (This is probably a long shot, but just thought I'd mention it, because I find the logic of the Tooltip component a little challenging to follow)

**Comment by ciampo** [comment]
> Is this what you are referring to?
> 
> > * The Tooltip component appears to add event handlers in order to emit events to its children — this behaviour seems to have been around a long time, but it also seems like it could be error-prone if it results in firing more events than it really should? Rather than just focusing on a single handler and element, do we need to revisit this behaviour across the eventHandlers in the component?
> > * This might not be at all related, but I noticed that the SelectControl component provides a noop function for some of its on methods, e.g. [here](https://github.com/WordPress/gutenberg/blob/dfc4b8b8b831c6d5e2c280b06c5871d91e66f337/packages/components/src/select-control/index.tsx#L42) — could the presence of noop props be confusing the Tooltip component into emitting events when it shouldn't? (This is probably a long shot, but just thought I'd mention it, because I find the logic of the Tooltip component a little challenging to follow)

Yes. In particular, it looks like `Tooltip` is written in a very convoluted way, especially around event handlers. It would be good to understand if we can simplify its code!

**Pull request merged**
