### PR TITLE
Fix bumped specificity for layout styles in non-iframed editor

### PR DESCRIPTION
**Pull request by talldan**
Core backport PR - https://github.com/WordPress/wordpress-develop/pull/7145
Core backport trac ticket - https://core.trac.wordpress.org/ticket/61829

## What?
Fixes the issue mentioned in https://github.com/WordPress/gutenberg/issues/53468#issuecomment-2241279024 to restore theme.json spacing rules taking precedence over the implicit spacing rules in a non-iframed editor.

## How?
In `trunk` the code generates a selector like `.is-layout-flow > *` (specificity 0,1,0) which is fine normally. When in a non-iframed editor, the `transformStyles` function prefixes selectors with `.editor-styles-wrapper` to scope them to the editor canvas, so it becomes `.editor-styles-wrapper .is-layout-flow > *` (specificity 0,2,0), a bump in specificity that causes the precedence of styles to change.

In this PR I've changed the selector to `:root :where(.is-layout-flow) > *` (still specificity 0,1,0). `transformStyles` handles 'root' selectors a little differently, it'll instead replace the `:root` part so it becomes `.editor-styles-wrapper where(.is-layout-flow) > *` (keeping the specificity at 0,1,0).

The other layout selector that this affects is the `:first-child` `:last-child` selectors that are responsible for resetting margin at the start and end of a block list. They traditionally have a 0,2,0 specificity so that they can override both the above rule and any rules in the theme.json. Those selectors are also maintained at 0,2,0 with this change, they become something like `:root :where(.is-layout-flow) > :first-child`.

<details><summary>Here's a list of selectors that will be updated (according to our php tests)</summary>

```diff
-.is-layout-flow  > :first-child {
+:root :where(.is-layout-flow) > :first-child {

-.is-layout-flow  > :last-child {
+:root :where(.is-layout-flow) > :last-child {

-.is-layout-flow  > * {
+:root :where(.is-layout-flow) > * {

-.is-layout-constrained  > :first-child {
+:root :where(.is-layout-constrained) > :first-child {

-.is-layout-constrained  > :last-child {
+:root :where(.is-layout-constrained) > :last-child {

-.is-layout-constrained  > * {
+:root :where(.is-layout-constrained) > * {

-.is-layout-flex  {
+:root :where(.is-layout-flex) {

-.is-layout-grid  {
+:root :where(.is-layout-grid) {

-.wp-block-social-links-is-layout-flow  > :first-child {
+:root :where(.wp-block-social-links-is-layout-flow) > :first-child {

-.wp-block-social-links-is-layout-flow  > :last-child {
+:root :where(.wp-block-social-links-is-layout-flow) > :last-child {

-.wp-block-social-links-is-layout-flow  > * {
+:root :where(.wp-block-social-links-is-layout-flow) > * {

-.wp-block-social-links-is-layout-constrained  > :first-child {
+:root :where(.wp-block-social-links-is-layout-constrained) > :first-child {

-.wp-block-social-links-is-layout-constrained  > :last-child {
+:root :where(.wp-block-social-links-is-layout-constrained) > :last-child {

-.wp-block-social-links-is-layout-constrained  > * {
+:root :where(.wp-block-social-links-is-layout-constrained) > * {

-.wp-block-social-links-is-layout-flex  {
+:root :where(.wp-block-social-links-is-layout-flex) {

-.wp-block-social-links-is-layout-grid  {
+:root :where(.wp-block-social-links-is-layout-grid) {

-.wp-block-buttons-is-layout-flow  > :first-child {
+:root :where(.wp-block-buttons-is-layout-flow) > :first-child {

-.wp-block-buttons-is-layout-flow  > :last-child {
+:root :where(.wp-block-buttons-is-layout-flow) > :last-child {

-.wp-block-buttons-is-layout-flow  > * {
+:root :where(.wp-block-buttons-is-layout-flow) > * {

-.wp-block-buttons-is-layout-constrained  > :first-child {
+:root :where(.wp-block-buttons-is-layout-constrained) > :first-child {

-.wp-block-buttons-is-layout-constrained  > :last-child {
+:root :where(.wp-block-buttons-is-layout-constrained) > :last-child {

-.wp-block-buttons-is-layout-constrained  > * {
+:root :where(.wp-block-buttons-is-layout-constrained) > * {

-.wp-block-buttons-is-layout-flex  {
+:root :where(.wp-block-buttons-is-layout-flex) {

-.wp-block-buttons-is-layout-grid  {
+:root :where(.wp-block-buttons-is-layout-grid) {

```

</details> 

## Testing Instructions
1. Add some very obvious margin rules to your theme.json like this for paragraphs (under `styles.blocks`):
```json
"core/paragraph": {
	"spacing": {
		"margin": {
			"top": "4rem",
			"bottom": "4rem"
		}
	}
},
```
2. Create a new post. Ensure you don't have custom fields active.
3. Insert 3 paragraphs with text, check that the margin looks right. The first paragraph should have no top margin, the last no bottom margin, but in all other cases there should be `4rem` top/bottom margin.
4. Activate Custom Fields in the editor preferences to 'un-iframe' the editor
5. Check that the styles are the same without the iframe

Also worth checking out `trunk` and comparing the styles. You should see that in trunk the iframed editor looks correct, but when you activate custom fields the non-iframed editor styles are broken.

#### Before
Screenshot 2024-07-31 at 4 33 10 PM

#### After
Screenshot 2024-07-31 at 4 33 30 PM

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
Thanks for digging into this one!

I'm curious as to why we need to change the PHP output of the layout support instead of updating `transformStyles` to resolve it and / or handle layout styles differently via a utility function. Since this will affect the output on the site frontend it sounds like a broader change than only looking at styling in the non-iframed editor?

My main concern whenever looking at the layout styles we're outputting is that it can be tricky to predict how it might affect themes out in the wild, and `tellthemachines` isn't currently around, who I usually ping for insights into these kinds of changes 😄

**Comment by talldan** [comment]
I had a look at something like that originally as part of another PR I'm working on (#63972), but I have concerns over how reliable it'd be because it'd mean quite a bit of manipulation of the selector. The `:first-child`, `:last-child` selectors would need to be split and reassembled, it's not just a simple wrapping.

`transformStyles` processes so much CSS (including third party stylesheets), so I think it might be even harder to predict the results.

This also changes the selectors back to be closer to how they were prior to #61638 (where the problem was introduced), the change to the selectors before that was in #60228 if you want to have a look at the history. (I should have left some of that info in the PR description)

**Comment by andrewserong** [comment]
Thanks for the extra context! In that case, should we also be updating the JS version `getLayoutStyles` so that they use the same rules for consistency? Around here: https://github.com/WordPress/gutenberg/blob/aa6bb1d800af1500838ffadb46ac81ef8243b94a/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L570

I mightn't get a chance to test this in much detail this week, but happy to give it a proper run through next week if it's still open. I'll just add @ellatrix as a reviewer too, given the history with #61638.

So far it's testing well for me in the iframed and non iframed editors, according to the testing instructions (and other blocks like Heading, etc have their default layout rules applied as expected):

| Iframed | non-iframed |
| --- | --- |
| image | image |

**Comment by andrewserong** [comment]
I think I might have found a difference that this PR creates compared to `trunk`:

On `trunk` if I give the Group block a block spacing value in global styles as well as a paragraph block vertical margin styles, then the paragraph block's margin styles will win out:

image

With this PR, it looks like the Group block's block spacing value wins out:

image

Are you able to replicate that? The steps I used:

1. In global styles, give the Paragraph block some vertical margins
2. In global styles, give the Group block a block spacing value
3. Add a Group block to a template with several child paragraph blocks
4. Look at the spacing between the blocks in `trunk` vs this PR

**Comment by talldan** [comment]
> Thanks for the extra context! In that case, should we also be updating the JS version getLayoutStyles so that they use the same rules for consistency? Around here:

<s>It's interesting you mention those lines, as it looks like those were wrapped in `:where` since #42665 (back in 2022), but #61638 changed them (maybe it shouldn't have?).</s>

edit: I was incorrectly looking at the fallback styles in the above comment. I've pushed a commit to update the JS version.

**Comment by talldan** [comment]
> Are you able to replicate that?

I'm not seeing that, and I'm not sure why it would happen as the styles in your screenshot have the same specificity as before and I haven't changed anything else.

There is something else that seems wrong (in both trunk and this PR).

If I follow your steps I see different results depending on whether I have this snippet in my theme's theme.json or not:
```js
"core/paragraph": {
	"spacing": {
		"margin": {
			"top": "4rem",
			"bottom": "4rem"
		}
	}
},
```

I wouldn't expect that as the styles are being overridden by global styles.

Possibly this is what you were seeing too? Maybe you accidentally removed the snippet when changing branches. It might be that the styles are being added in a different order depending on whether theme.json defines some block margin. 🤔

**Comment by andrewserong** [comment]
> I'm not seeing that, and I'm not sure why it would happen as the styles in your screenshot have the same specificity as before and I haven't changed anything else.

Thanks for trying to reproduce! I think this was my own user error when running through this quickly yesterday. So far it's all looking consistent to me while testing locally, but I'll run it through a few more themes to be sure 👍

**Comment by andrewserong** [comment]
Alrighty, so this appears to be testing well for me so far, but it'd be good to get another set of 👀 to confirm.

One question, it looks like this PR is only updating the specificity for the spacing styles rules. Do they also need to be updated for the base styles, too? I'm imagining not?

image

Around this line and beyond: https://github.com/WordPress/gutenberg/blob/65410c213877267f18bab4e20c2110b1ba8d200e/lib/class-wp-theme-json-gutenberg.php#L1763

I couldn't see any issues caused by the existing base layout rules between the iframed and non-iframed editor (I think the rules were last updated in https://github.com/WordPress/gutenberg/pull/60228), so it sounds like they could probably remain as-is for now? From my perspective it's good if we can do the smallest set of changes required to fix the bug at hand.

In testing so far with this PR:

* ✅ Block-level margin styles in global styles overrides base spacing styles
* ✅ Block-level margin styles in global styles overrides block level spacing in global styles (e.g. Group block set to `0` block spacing will be overridden by paragraphs within the Group if paragraphs have margin set)
* ✅ Block instance level block spacing overrides global styles margin rules
* ✅ Block instance level margins override block instance level block spacing
* ✅ Block spacing for buttons, social icons, row, stack, and grid all appear to be working
* ✅ All the above are testing well in the iframed and non-iframed post editor, and in the site editor and site frontend for me

So, all looks promising to me!

**Comment by talldan** [comment]
> One question, it looks like this PR is only updating the specificity for the spacing styles rules. Do they also need to be updated for the base styles, too? I'm imagining not?

I'm not sure, you might have to point me to the base styles.

There have been a couple of reports that I still need to investigate that look similar to this:
- https://github.com/WordPress/gutenberg/issues/63925
- https://github.com/WordPress/gutenberg/issues/64266

**Comment by andrewserong** [comment]
> I'm not sure, you might have to point me to the base styles.

They're in the same function, from this line onwards: https://github.com/WordPress/gutenberg/blob/245248e8c1948806a826dcac4c8e07cf8234c879/lib/class-wp-theme-json-gutenberg.php#L1765

The logic is fairly similar to the spacing styles, in that the rules are grabbed from the layout definitions here: https://github.com/WordPress/gutenberg/blob/0af7e1402ce2e8c04fd382f3de55449b74342b1c/lib/block-supports/layout.php#L17

Then they're constructed around here: https://github.com/WordPress/gutenberg/blob/245248e8c1948806a826dcac4c8e07cf8234c879/lib/class-wp-theme-json-gutenberg.php#L1782

And here: https://github.com/WordPress/gutenberg/blob/245248e8c1948806a826dcac4c8e07cf8234c879/lib/class-wp-theme-json-gutenberg.php#L1830

**Comment by talldan** [comment]
@andrewserong I'm not seeing any issues - I tried lots of different layouts and they look the same between iframed/non-iframed editors, and behave the same when applying global styles and block styles.

It's hard to test exhaustively as those rules do generate a lot of selectors (there really needs to be automated testing in place rather than relying on manual testing).

There is a similar non-iframed bug to this reported in https://github.com/WordPress/gutenberg/issues/63925, though it's more related to element/block styles selectors so I think a separate PR would make sense. I'm still not sure what the fix will look like for that one.

**Comment by andrewserong** [comment]
Thanks for checking @talldan! In that case, it sounds like let's keep the base styles as they are — the fewer things we need to change in one PR, the better, IMO 🙂

**Review by andrewserong — APPROVED** [review]
After re-testing this is still testing well for me. Based on the discussions so far, I think it's good that this change is contained to just the spacing part of the layout styles as that reduces the scope for potential breakages given that changes here rely heavily on manual testing 👍

I ran through [the same testing steps as last week](https://github.com/WordPress/gutenberg/pull/64076#issuecomment-2264313308), all looking good. I thought I found a bug at first when setting paragraph margins at the block level in global styles and how those margins work at the root level in the site editor. It looks like there's an inconsistency in the order of the output between the site editor and site frontend, and it's the same in this PR as on `trunk`, so not a blocker to landing. Just thought I'd mention it here in case anyone else runs into it while testing.

Note here that the root layout rules override the paragraph margins in the site editor but not the site frontend:

| Site editor | Site frontend |
| --- | --- |
| image | image |

LGTM, but it'd be good to get a second review since this is aimed at 6.6.2.

**Review by ramonjd — APPROVED** [review]
I compared output in the un-iframed and framed editors, and the frontend.


✅  Theme.json/global spacing styles are applied as expected with the 'un-iframed' editor

| Before  | After |
| ------------- | ------------- |
| Screenshot 2024-08-08 at 9 41 23 PM  | Screenshot 2024-08-08 at 9 41 07 PM  |

✅  Block styles are overriding theme.json/global styles on the frontend

I tested Group blocks as well in various types (row, grid etc) and can't find any discrepencies.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for fixing this one @talldan and @andrewserong for the extra checklist of things to test 🙇 

I've also given this PR a run according to the test instructions and checklist in https://github.com/WordPress/gutenberg/pull/64076#issuecomment-2264313308. It's working well for me. Nice work!

| Site Editor | Frontend |
|---|---|
| Screenshot 2024-08-09 at 5 23 18 PM | Screenshot 2024-08-09 at 5 23 43 PM |

| Post Editor (non-iframed) | Frontend |
|---|---|
| Screenshot 2024-08-09 at 5 31 01 PM | Screenshot 2024-08-09 at 5 25 23 PM |

> It looks like there's an inconsistency in the order of the output between the site editor and site frontend

I can see the different style order in the provided screenshots but when I was testing locally I couldn't replicate the issue. The ordering remained consistent between both editors and the frontend.

Modifying block margins etc at either the block type level or root styles level didn't seem to make a difference. I could be missing something of course but thought I'd flag that I wasn't seeing the issue.

_Edit: Appears I was looking at the `.is-layout-constrained` style rather than root block gap styles with `.wp-site-blocks`_

**Comment by hellofromtonya** [comment]
PHP changes were committed into WordPress Core's trunk via https://core.trac.wordpress.org/changeset/58890.

**Comment by cbravobernal** [comment]
Removing the label as it was already included in 6.6

**Pull request merged**
