### PR TITLE
Don't show tooltip in zoom out toggle button when showIconLabels is true

### PR DESCRIPTION
**Pull request by t-hamano**
Fix the issue raised in [this comment](https://github.com/WordPress/gutenberg/issues/65491#issuecomment-2361119959)

## What?

Change the toggle button so that a tooltip is not displayed when `showIconLabels` is true.

## Why?

The button already has text displayed, so the tooltip text is redundant.

### Testing Instructions for Keyboard

- Enable "Show button text labels" via the Preferences modal
- Focus/Hover the "Toggle Zoom Out".
- The tooltip should not be displayed.

### Before

image

### After

image

### CODE REVIEW

**Review by afercia — APPROVED** [review]
LGTM to me, thanks

**Comment by afercia** [comment]
Spoke too soon. There's a few failing tests but they seem unrelated.

**Comment by t-hamano** [comment]
Thanks for the review!

The cause of the test failure is investigated here: https://wordpress.slack.com/archives/C02QB2JS7/p1727152145938689

**Review by draganescu — APPROVED** [review]
🙇🏻 thank you so much!

**Pull request merged**
