### PR TITLE
Mobile Release v1.54.0

### PR DESCRIPTION
**Pull request by jhnstn**
## Description
Release 1.54.0 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3559

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by dcalhoun — APPROVED** [review]
LGTM. Per the release checklist, we shouldn't pull `trunk` in or merge this until _after_ we finish the "Integrate the Release" section and begin the "Sync the Release to Development Branches" section.

**Comment by fluiddot** [comment]
I noticed that there's no `1.54.0` section in the [`react-native-editor` changelog file](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md), usually, we update it when cutting a new release although I've just realized that it's not included in the release scenario steps 🤔.

**Comment by dcalhoun** [comment]
> I noticed that there's no `1.54.0` section in the [`react-native-editor` changelog file](https://github.com/WordPress/gutenberg/blob/trunk/packages/react-native-editor/CHANGELOG.md), usually, we update it when cutting a new release although I've just realized that it's not included in the release scenario steps 🤔.

Whoops. Yes, for better or worse it is not an explicit task in the release scenario. It is a checklist item on the GB Mobile PR itself. However, it lists two locations in one task. I have overlooked the second location myself multiple times. It may be worth splitting the locations into two separate tasks in the PR. 

>Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.

**Comment by fluiddot** [comment]
Yeah, I was thinking of adding an extra step in the Release Checklist Template to make this step clearer, wdyt?

**Comment by dcalhoun** [comment]
> Yeah, I was thinking of adding an extra step in the Release Checklist Template to make this step clearer, wdyt?

I'm torn. It's a long checklist. 😄 However, having checklists in multiple locations isn't a great aspect either. 🙃 

At this point, I definitely think we need to split the two locations into separate tasks. If we add those tasks to the release scenario checklist, then I think we should remove them from the PR checklist. Having the same task in two locations would likely lead to people overlooking tasks they think they already completed due to repetition/noise.

**Comment by fluiddot** [comment]
> > Yeah, I was thinking of adding an extra step in the Release Checklist Template to make this step clearer, wdyt?
> 
> I'm torn. It's a long checklist. 😄 However, having checklists in multiple locations isn't a great aspect either. 🙃

You're right, it's getting too long to keep adding items 😄 , let's try to avoid it 👍 .

> At this point, I definitely think we need to split the two locations into separate tasks. If we add those tasks to the release scenario checklist, then I think we should remove them from the PR checklist. Having the same task in two locations would likely lead to people overlooking tasks they think they already completed due to repetition/noise.

I'm leaning more on the option of splitting the two locations into separate tasks to make it clearer. ~~I'll update the [PR remplate](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/.github/PULL_REQUEST_TEMPLATE.md) with this.~~

**EDIT:** I've just realized that the change has to be done in the [release pull request template](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/release_pull_request.md).

**Comment by fluiddot** [comment]
@dcalhoun Heads up that I've just opened this [PR](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/50) for splitting the entry.

**Pull request merged**
