### PR TITLE
Icons: Update lock and unlock icons to be smaller.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Based on conversation in https://github.com/WordPress/gutenberg/issues/29864#issuecomment-1059100385, the existing lock icons are a bit chunky:

before

This PR updates them with some unpublished concepts that are less chunky:

after

Figma has been updated.

## Testing Instructions

Test in storybook and observe the "after" icons there.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Here's an example of updated icons from Block Locking UI.

CleanShot 2022-03-07 at 17 45 45

**Comment by jasmussen** [comment]
Hmm. The icons look a teensy bit small here, and also a bit smaller than [the icon example here](https://github.com/WordPress/gutenberg/issues/29864#issuecomment-1058488673). I'll update these once more!

**Comment by jasmussen** [comment]
Alright, I've updated the icons to be slightly bigger to match what was suggested on the other thread:

Screenshot 2022-03-10 at 10 07 33

**Comment by jameskoster** [comment]
I'm not sure if it's the dimensions of each element in relation to one another, but as it gets larger it starts to resemble a bag.

Probably not a big deal, mostly just a curious observation. 

If we wanted to address that, I think a keyhole helps:

Screenshot 2022-03-10 at 11 30 06

But totally understand if we want to keep it minimal. We can always address this if/when we add a bag icon in the future.

**Comment by jasmussen** [comment]
The hole always felt "decorative" to me, but I agree it's a nice option to have. We could potentially start here, for the locking UI, and get a feel for it, and I'd be happy to follow up?

**Review by jameskoster — APPROVED** [review]
Seems fair.

This is working for me:

Screenshot 2022-03-10 at 13 36 07

**Comment by jasmussen** [comment]
Cool, I'll land and I'll be on the lookout for followups!

**Pull request merged**
