### PR TITLE
Removed line break within the code block

### PR DESCRIPTION
**Pull request by SavPhill**
## What?

There is a line break within the code block. 
## Why?

I have removed the line breaks as the line break during the class are not necessary.
## Testing Instructions

Navigate to: https://developer.wordpress.org/block-editor/explanations/architecture/styles/#block-styles 

See the unnecessary line breaks within the second code block.

### CODE REVIEW

**Comment by skorasaurus** [comment]
thanks, looks good to me.

**Comment by SavPhill** [comment]
Giving this PR a bump as it's 5 months without any movement.

**Review by annezazu — APPROVED** [review]

**Comment by annezazu** [comment]
Hey there. Can you try merging in latest trunk? Right now, some of the automated items have failed/didn't report and it's making it so it can't be merged.

**Comment by SavPhill** [comment]
> Hey there. Can you try merging in latest trunk? Right now, some of the automated items have failed/didn't report and it's making it so it can't be merged.

Hi, thank you. I pushed the latest trunk. Looks like some tests are slow to complete.

**Comment by SavPhill** [comment]
Bump to reduce stagnation. Any further feedback for this PR?

**Comment by mburridge** [comment]
Some tests were failing, and it's not possible to re-run the tests now as more than [30 days have passed](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs?tool=webui). Could you merge the latest trunk into the branch and try again.

**Comment by ryanwelcher** [comment]
I've taken the liberty of updating this branch with latest `trunk` to re-trigger the tests. If any fail at this point, we should be able to re-run then. Sorry for the delay on this @SavPhill, we'll get this merged ASAP!

**Comment by SavPhill** [comment]
> I've taken the liberty of updating this branch with latest `trunk` to re-trigger the tests. If any fail at this point, we should be able to re-run then. Sorry for the delay on this @SavPhill, we'll get this merged ASAP!

Thank you @ryanwelcher

**Pull request merged**
