### PR TITLE
Navigation mode: polish enabling when no block is selected

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Polishes #19238: don't enable navigation mode on tab, but rather use the `FocusCapture` elements to detect incoming keyboard navigation. This fixes an issue where navigation mode is enabled after tabbing outside the block list (e.g. document sidebar) and then clicking on a block.

To do: add e2e tests.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by youknowriad — COMMENTED** [review]
So I remember properly, this behavior is related to the "PostTitle" component where sometimes we tab through it and sometimes we don't right?

What if instead of trying to hack around "auto-enabling" the navigation mode, we make sure the "PostTitle" behaves like a block. I guess thisi means when we tab out from it in edit mode, instead of going to the next block, we just skip all the blocks?

**Comment by ellatrix** [comment]
@youknowriad It's related, but it should work from both sides. When I tab from the header to the block list, and no blocks are selected, navigation mode should be enabled. When I tab backwards from the document sidebar, and no blocks are selected, navigation mode should also be enabled. I do agree that the post title should behave as much as possible like a block, or be a block, since it's wrapped in `WritingFlow`.

**Comment by youknowriad** [comment]
I guess what I don't understand is why we auto-enable Navigation block. I think explicitness is better in most cases.

**Comment by ellatrix** [comment]
@youknowriad Yes, it would be better if navigation mode were enabled _by default_. This would make most sense because you **`Escape`** from Edit mode to Navigation mode, and **`Enter`** Edit mode from Navigation mode. But since persists through clicks, we can't have it on by default I guess. Otherwise, if you load a page and click on a block, you're still in Navigation mode.

**Comment by youknowriad** [comment]
> Yes, it would be better if navigation mode were enabled by default.

We had it by default and it broke other stuff (first focus in the post title) and also a lot of confusion from users so we reverted.

**Comment by ellatrix** [comment]
Exactly, so we can't enable it by default, and this seems like the right solution.

May I ask why it is ok to auto-enable Edit mode when using the mouse, but not ok to auto-enable Navigation mode when using the keyboard?

**Comment by youknowriad** [comment]
> May I ask why it is ok to auto-enable Edit mode when using the mouse, but not ok to auto-enable Navigation mode when using the keyboard?

Good question :) I guess I'm biased here but the thinking for me at least is that "double click" explicitly means "edit" whlie "tabbing" not necessarily "navigation mode" (since you can also tab in "edit" mode)

**Comment by youknowriad** [comment]
That's a good point though.

**Comment by ellatrix** [comment]
So the double-click is a bit like tabbing into the block list without any block selected. :)

**Comment by youknowriad** [comment]
Ok you convinced me :P

**Review by youknowriad — APPROVED** [review]

**Comment by ellatrix** [comment]
@youknowriad Thanks for the discussing and review. I'll add an e2e test for this behaviour before merging.

**Pull request merged**
