### PR TITLE
ItemGroup: experimenting with chevron icon

### PR DESCRIPTION
**Pull request by ciampo**
## Description

This PR adds a couple of Storybook examples about how a chevron icon (">") could be displayed within the `Item` component (in the `ItemGroup` "family") — see #36653 for more context.

## How has this been tested?

Visit the "Complex Layouts" example in the `ItemGroup`'s Storybook

## Screenshots 

https://user-images.githubusercontent.com/1083581/142629959-ace0007d-5f4d-4cac-9372-c70a13bc5177.mp4

## Types of changes

Enhancement / new feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
Oh nice, thanks for the PR and the video. Just at a glance this seems like a decent solution in both enabling a longer text label by default, while still showing the chevron when in the context of moving into the property.

The chevron part of the ItemGroup component is not one I've a deep understanding of. @pablohoneyhoney I think you've put thought into this: from the video above, what are your thoughts? Thanks both!

**Comment by ciampo** [comment]
> The chevron part of the ItemGroup component is not one I've a deep understanding of. @pablohoneyhoney I think you've put thought into this: from the video above, what are your thoughts? Thanks both!

Just to clarify — with this PR, the chevron is **not** part of the `Item` component. Instead, I've created a Storybook example where I show how a chevron icon could be used / composed with a `Item` component

More context in https://github.com/WordPress/gutenberg/issues/36653

**Comment by jasmussen** [comment]
Sounds good to me on a high level. Coming at it mostly from looking at where these behaviors could/would be used, my instinct goes towards global styles, where the inspector slides right in waterfall behavior — that could benefit from the chevron. Whereas when the ItemGroup is used for colors in the post editor, for example it would not slide the inspector, but just immediately go to an overlay — in that case, a right pointing chevron would not be as useful. So it seems good to enable both.

Mockup from #35093

**Comment by pablohoneyhoney** [comment]
Nice!

The notes above by @jasmussen make a lot of sense. 
Let me know if this is helpful. In essence, so far we identified these contexts within Styles, which I think matches with the video instances:

- Group of items that serve as a navigational system, drilling down to related controls or category items (like the list of general elements under color). Expected behavior: show arrow by focus and hover. 

Screen Shot 2021-11-23 at 10 30 04 AM

- Individual item that serves as a navigational system, drilling down to related controls or category items (like the special access to blocks-level styling). Expected behavior: show persistent arrow, always visible. 

Screen Shot 2021-11-23 at 10 20 52 AM

- Group of items or individual item that serve as an inline setting or manifest something in context (like the color picker). Expected behavior: hide arrow. 

Screen Shot 2021-11-23 at 10 26 14 AM

Not sure if this would be considered the same component, but it's a similar case than last. 

Screen Shot 2021-11-23 at 10 28 23 AM

- Items (regularly single or isolated) that are meant to surface contextual information about that item (like the number of colors in palette).
 
Screen Shot 2021-11-23 at 10 27 47 AM

As far as the cases of the arrow appearing in larger texts (which we should recommend against anyways, so perhaps there's a cap or a tip showing if that's the case), the video above looks good.

**Comment by ciampo** [comment]
Thank you @jasmussen and @pablohoneyhoney for your feedback!

> > Sounds good to me on a high level. Coming at it mostly from looking at where these behaviors could/would be used, my instinct goes towards global styles, where the inspector slides right in waterfall behavior — that could benefit from the chevron. Whereas when the ItemGroup is used for colors in the post editor, for example it would not slide the inspector, but just immediately go to an overlay — in that case, a right pointing chevron would not be as useful. So it seems good to enable both.
>
> The notes above by @jasmussen make a lot of sense.
> Let me know if this is helpful. In essence, so far we identified these contexts within Styles, which I think matches with the video instances:
> [...]
> As far as the cases of the arrow appearing in larger texts (which we should recommend against anyways, so perhaps there's a cap or a tip showing if that's the case), the video above looks good.

Glad to see that the examples that I created seem to cover all cases where a chevron icon would be useful.

Just to be clear, the approach that we'd be taking with this PR is to add an example to Storybook of how the chevron icon could be added to an `Item`/`ItemGroup` — this mean that, when this "pattern" needs to be used (for example, in the global styles sidebar), developers will still need to implement it, but they will able to copy (or at least get inspired by) this Storybook example.

We discussed this approach and its alternatives in #36653





> Not sure if this would be considered the same component, but it's a similar case than last.
> 
> Screen Shot 2021-11-23 at 10 28 23 AM

I don't think that the area clicked to open the color picker in this example is an `Item` (within an `ItemGroup`).

**Review by mirka — APPROVED** [review]
Really nice story, it's simple enough but covers all the bases 💯

**Comment by ciampo** [comment]
> Really nice story, it's simple enough but covers all the bases 💯

Nice! I'll go ahead and merge this. We can always iterate over whatever approach we decided taking in #36653

**Pull request merged**
