### PR TITLE
Media & Text: Add spacing block supports

### PR DESCRIPTION
**Pull request by ndiego**
Related:

- https://github.com/WordPress/gutenberg/issues/43241
- https://github.com/WordPress/gutenberg/issues/43243

## What?
Add padding and margin support to the Media & Text block.

## Why?
To create consistency across blocks.

## How?
Added the relevant block supports in block.json

## Testing Instructions
1. Insert a new Media & Text block. 
2. Confirm that the dimensions control panel is there and there are no defaults.
3. Add padding and margin.

## Screenshots or screencast 
media-text-spacing

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
Apologies for leaving basically the same feedback on each of these PRs @ndiego, but thanks so much again for digging into all these opt-ins!

It looks like this block will also need the `box-sizing: border-box` rule in order for the padding to line up with adjacent blocks like Group.

image

Here's the comparable rule from the Cover block that we can use: 

https://github.com/WordPress/gutenberg/blob/f764be498ceb34149a530f8d1f8d48046c859da8/packages/block-library/src/cover/style.scss#L10-L11

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for putting this PR together @ndiego 👍 

I'd like to echo Andrew's suggestions around `box-sizing`. Also, to help with tracking our progress towards improving consistency in our design tool availability I've added this to the current [tracking table](https://github.com/WordPress/gutenberg/issues/43243).

**Comment by ndiego** [comment]
Thanks! I'll get box-sizing taken care of today.

**Comment by ndiego** [comment]
@aaronrobertshaw `box-sizing` has been added and tested. All looks good on my end.

**Review by andrewserong — APPROVED** [review]
Thanks for updating this one, too, @ndiego!

✅ Padding is working as expected in the post editor
✅ Padding is working as expected in the site editor and set in global styles 

image

LGTM! ✨

**Comment by ndiego** [comment]
Thanks for reviewing @andrewserong. These Admin e2e tests keep timing out, any ideas?

**Comment by andrewserong** [comment]
@ndiego I think it's just an unrelated flaky e2e test. Looks like it's passing now, so I'll merge this in!

**Pull request merged**
