### PR TITLE
E2E tests: Handle upgrade screen

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
E2E tests might get stuck on the "Database Update Required" screen. This PR takes care of the screen by automatically clicking on update.

## How has this been tested?
The quickest way is to change the `db_version` option in the database.
1. Add this line 
```js
update_option('db_version', get_option('db_version') - 1);
```
at https://github.com/WordPress/gutenberg/blob/cdc34fb17eb058b56a8e55f583c17b5fe1db54d7/gutenberg.php#L17-L19 after the comment.

2. Open http://localhost:8889
3. Then open http://localhost:8889/wp-admin
4. Make sure upgrade screen pops up
5. Comment the line you just added (or remove it)
6. Now run e2e tests interactively (`npm run test-e2e -- --puppeteer-interactive`)
7. Make sure puppeteer successfully goes through the upgrade screen

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jeyip** [comment]
There are e2e failures, but I believe that they're unrelated (and should be fixed by #28638). I'll rebase this PR now.

**Comment by david-szabo97** [comment]
@jeyip Silly question, did you run `npm run build` before running tests?

**Comment by jeyip** [comment]
> Silly question, did you run npm run build after checking out the branch but before running tests?

I didn't! Lemme give that a shot 👍

**Comment by jeyip** [comment]
Blowing everything away and re-rerunning specs fixes the issue :shipit:

**Review by jeyip — APPROVED** [review]

**Review by vindl — APPROVED** [review]

**Pull request merged**
