### PR TITLE
RNMobile: Fix broken doc link

### PR DESCRIPTION
**Pull request by guarani**
## Description

This change just updates the link to the React Native Editor docs

## How has this been tested?

Make sure link now works.

## Types of changes

Update documentation.

## Checklist:

No checklist items are applicable to this PR.

### CODE REVIEW

**Review by dcalhoun — APPROVED** [review]
Thanks for fixing this! The new link works as expected for me.

**Comment by guarani** [comment]
Checks failed 😰 Re-running tests.

**Comment by guarani** [comment]
Checks failed again, re-running tests 😓

**Comment by guarani** [comment]
Tests failed yet again 😨 re-running.

**Pull request merged**
