### PR TITLE
Fix typo in the media-categories component

### PR DESCRIPTION
**Pull request by Rahmon**
## What?

This PR fixes a typo in the media-categories component.

While I was translating the WordPress to Portuguese (PT-BR), I noticed that a placeholder in a `sprintf` function was using a different position compared with the hint for translators.

## Why?

This PR is necessary to show the correct hint for translators.

## How?

Updating to use the correct placeholder position.

## Screenshots or screencast 

image

### CODE REVIEW

**Review by alexstine — APPROVED** [review]
This looks right to me. 👍

**Comment by alexstine** [comment]
@Mamaduka Is this one needed for backporting? The translation strings do clearly look wrong here.

**Comment by Mamaduka** [comment]
Thanks for the ping, @alexstine! Added label for the backporting.

**Comment by alexstine** [comment]
@Mamaduka Thanks. I am never positive on what should be eligible for backport and what is not. The whole idea of trying to figure out which portions of Gutenberg go out in a release is a terrible experience. Maybe it is documented somewhere but I have never found a clear way. Anyway, that is slightly off topic.

**Comment by Mamaduka** [comment]
It's a bit tricky during the RC phase, but we're already backporting one internalization fix, and I'm also okay with including this one.

Generally, we try to use the [release project board](https://github.com/orgs/WordPress/projects/63/views/1) for triaging and tracking fixes that need to be backported.

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: c1d64c0060

**Comment by hellofromtonya** [comment]
The threshold for deciding what to backport in Core's RC cycle is this: 

Was the string introduced in the 6.2 cycle?

If yes, then it's okay to backport. cc @Mamaduka

**Pull request merged**
