### PR TITLE
Post featured image: Add title attribute

### PR DESCRIPTION
**Pull request by carolinan**
## What?

This PR adds an option to add a title attribute to the post featured image. The setting is in the Advanced panel in the block settings sidebar.

## Why?

There are inconsistencies between the available features for the image block and the post featured image block.
This PR is meant to reduce one of these inconsistencies to make it easier for users to use the blocks.

## How?

- Adds a new block attribute called title.
- Adds a new text input control in the Advanced panel.

## Testing Instructions
1. Create a new post and assign it a featured image.
2. Add a post featured image block. -The "Link to post" setting should be toggled off.
3. With the block selected, open the Advanced panel in the block settings sidebar.
4. Locate the TITLE ATTRIBUTE setting and add a text. Save.
5. Refresh the editor, open the advanced panel, and confirm that the attribute has saved correctly.
6. View the post on the front of the website, confirm that the image has a title attribute, for example by viewing the source.
7. Go back to the editor and enable the "Link to post setting". Save and view the post on the front:
- If the post has a title, the linked image should not have a title attribute. This is to ensure that the post title in the alt attribute is used as the link text / accessible name.

## Screenshots or screencast 
The block settings sidebar for the post featured image block with the new title attribute setting in the Advanced panel.

### CODE REVIEW

**Comment by alexstine** [comment]
@carolinan So if the post has a title, the `alt` will be used but not the `title`? Are you communicating that to users anywhere that way they know their `title` attribute will likely never be used but under rare conditions?

**Comment by joedolson** [comment]
In principle, I don't see a benefit to encouraging the use of the title attribute. What is the feature in the image block that you're adding this to match? The only existing title field I'm aware of for images is in the media library, but that's the post title, which is used in list view as the link to the image, and is not used as a title attribute. 

image

(Image shows the usage of the title input field in the media library.)

**Comment by carolinan** [comment]
The option to add the title attribute to the image block is indeed different from the title field in the media library.
The input field is in the Advanced panel in the block settings sidebar, and it has a help text that says:
Describe the role of the image on this page. Note: Many devices and browsers do not display this text.


The user is not informed that the post title is used instead of the title attribute.
They are also not informed that the alt text in the media library is ignored in favor of the post title.

There needs to be a continued discussion about if the featured image block should also have the alt text setting that the image block has. I am torn because it is used conditionally, only when the block is not linked.

**Comment by joedolson** [comment]
Ugly. And the description field is not available in the image block at all, I see. I'd much rather see the description field available in the advanced area over the title attribute, even though that field is not used at all. 

I definitely agree that this needs to be made more coherent for both contexts, but I think that we don't want to encourage the use of title attributes. I'm 100% in favor of communicating more effectively to the user how various texts will be used, though.

**Comment by carolinan** [comment]
I am working on the caption as well, but I am unsure of where the media description would be used.

**Comment by joedolson** [comment]
Historically, it's been rarely used, usually only appearing on the attachment template in a classic theme. I don't believe there are any core functions that use it. That's why it would really only be suitable as an advanced field; it's almost certainly only going to be used in contexts with some degree of customization. Although I think it would be quite reasonable to make the image block output it when provided.

If I were dreaming, I'd want to make a database change to swap the description with the alt attribute. The description is stored in post content, and the alt attribute is in post meta, and there are so many things that would be made easier if those were switched.

**Comment by carolinan** [comment]
I am also not sure that adding feature parity with the image block is encouraging the user, the setting is pretty well hidden.
I vaguely remember discussing the help text in the past, but after that I forgot the setting even existed.

**Comment by afercia** [comment]
For reference: this is the pull request that added the title attribute to the Image block: https://github.com/WordPress/gutenberg/pull/11070

Regarding the help text, I'm not sure the term `role` is appropriate.  In https://github.com/WordPress/gutenberg/pull/11070 the help text went from:
`Provide a clear name for this image.`
to:
`Provide an optional description for this image.`
and finally to:
`Describe the role of this image on the page`

I think it was done to try to explain it's about the purpose of the image, not necessarily the image content. However, it's still not that clear. Also, it's even more confusing when comparing with the Alt help text.

Alt text:
`Describe the purpose of the image. Leave empty if the image is purely decorative.`

Title attribute:
`Describe the role of this image on the page`

As a user, I'd be pretty confused. What's the difference between 'purpose' and 'role'?
Also, the link after this text points to the title attribute specification on the HTML living standard page, where there's no concept of 'role'.

Ideally, this help text should be a bit rephrased to explain a few key concepts:
- it's advisory information
- it's an optional, additional, description of the image purpose or a description of some image properties (e.g. credits)
- many devices and browsers do not display this text

I do realize communicating these concepts in a short sentence is hard. It would be great to find a better prhasing though and update the Image block help text as well.

**Comment by afercia** [comment]
Overall, I'd say both the Media Library and the editor user interface don't explain very well that all these fields are meant for. It's true that themes and plugins can use these values for any purpose and even use them wrongly, However, conceptually, some fields belong to the post attachment while others belong to the image. For xample:

Title and Description are mainly properties of the post attachment.
Alt text, Caption, and Title attribute are properties of the image / figure.

The UI doesn't do a great job to separate these properties. They're all mixed up and not explained very well.

This is a separate issue though and should be addressed holistically in WP core and the editor. Some consistency would be great too.

**Comment by afercia** [comment]
Keeping in mind that WordPress should [not encourage the use of the title attribute](https://core.trac.wordpress.org/query?keywords=~title-attribute), I'd recommend to rephrase all the occurrences of the help text for this field, for all blocks.

The current text:

`Describe the role of this image on the page.[(Note: many devices and browsers do not display this text.)(opens in a new tab)](https://www.w3.org/TR/html52/dom.html#the-title-attribute)`

Doesn't explain very well that this field is only meant for additional, optional, description. Do not use it for important information, as by its own nature the title attribute content is not available to all users.

**Comment by carolinan** [comment]
> I'd recommend to rephrase all the occurrences of the help text for this field, for all blocks.

I believe that would need to be a separate issue.

**Comment by carolinan** [comment]
This has gone stale and there are too many merge conflicts, closing.

**Pull request closed without merging**
