### PR TITLE
Feat: Add new typography options for figcaption on image block [#34643]

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

- Adds new typography options that can be used to set fig captions.

## Why?

- Issue - https://github.com/WordPress/gutenberg/issues/34643

## How?

- Added experimental typography options as supports to image block.

## Testing Instructions

- Testing how PR is affecting the blocks is being added in below screencast.

### Testing Instructions for Keyboard

- NIL

## Screenshots or screencast 
[ImageBlockCaption.webm](https://user-images.githubusercontent.com/58802366/214600300-d7e83b2c-3c97-4881-821f-aa427bbdb2d5.webm)

### CODE REVIEW

**Comment by hbhalodia** [comment]
Hi @Mamaduka, I have added only for the font Size and a selector. Can you please review the PR. Thanks.

**Review by Mamaduka — APPROVED** [review]
The codewise looks good.

@richtabor, I would appreciate 2nd opinion, if having a Typography option on Image block makes sense.

cc @scruffian.

**Comment by richtabor** [comment]
> @richtabor, I would appreciate 2nd opinion, if having a Typography option on Image block makes sense.

No, I don't think it does. 

We do have the ability to style captions within theme.json — that should probably be exposed within Global Styles in the Elements panel instead. 


```
"styles": {
	"elements": {
		"caption": {
			"color": {
				"text": "#111111"
			},
			"typography": {
				"fontSize": "0.8rem",
				"lineHeight": ".7",
				"textTransform": "uppercase"
			}
		}
	}
}
```

CleanShot 2023-02-17 at 13 28 33

**Comment by scruffian** [comment]
Can you give a context when this would be useful?

**Comment by richtabor** [comment]
> Can you give a context when this would be useful?

The idea is to be able to set a different caption font size on a per-image basis. 

I don't think we should have font size for captions on individual image blocks — but rather expose figcaption element styling within Global Styles.

**Comment by richtabor** [comment]
@Mamaduka I think we're good to close this out, now that caption support is added to Global Styles via https://github.com/WordPress/gutenberg/pull/49141? 

I don't foresee further implementing image-specific caption size controls. Site-wide control is pretty nice in #49141 though.

**Comment by Mamaduka** [comment]
I'll close the PR. Thanks for contributing, @hbhalodia!

**Pull request closed without merging**
