### PR TITLE
Removed styling information

### PR DESCRIPTION
**Pull request by mrmadhat**
## Description
Removes styling output see #10734 

## Types of changes
Documentation

### CODE REVIEW

**Review by Soean — DISMISSED** [review]
This file is auto-generated, see https://github.com/WordPress/gutenberg/blob/master/bin/generate-public-grammar.js#L98
You have to remove it on this file and then regenerate it.

**Comment by mrmadhat** [comment]
@Soean I have removed the styling from bin/generate-public-grammar.js how do I regenerate it?

**Comment by Soean** [comment]
Maybe @mcsf can help

**Comment by mcsf** [comment]
@mrmadhat: `./bin/generate-public-grammar.js`

**Comment by mrmadhat** [comment]
Thanks @mcsf I realised what was going on after your comment. The reason why I thought it wasn't working was because the grammar.md file didn't change after running the script but this was because I'd already removed the styling info manually in the initial commit!

**Comment by mcsf** [comment]
Makes sense. 😅 Thanks for working on this!

**Review by mcsf — APPROVED** [review]

**Pull request merged**
