### PR TITLE
Migrate the Github Actions to the new YAML syntax

### PR DESCRIPTION
**Pull request by youknowriad**
I just used the Github tool to migrate our Github actions workflows to the new yaml syntax.

### CODE REVIEW

**Review by senadir — APPROVED** [review]
since it was done by an [automated tool](https://github.com/actions/migrate) i don't think there should be any problems, and I don't think we can test it before merge, so all good i guess.

**Review by ntwb — APPROVED** [review]
I guess the updated actions don't work on the actual PR making the change 😏

Merge away and see what happens next PR :yolo:

**Comment by youknowriad** [comment]
Let's see :P

**Comment by ntwb** [comment]
@youknowriad lol, and, nope, no actions queued on the #16985 PR

**Comment by senadir** [comment]
a lot of them did in #16984

**Comment by ntwb** [comment]
Hehehehe, so no change in behavior of the actions then ;)

**Comment by noisysocks** [comment]
I think @talldan convinced me that all our project automation actions should be in one workflow. We should also look into making them JavaScript-based instead of Docker-based. I might have a play with it on Wednesday 🙂

**Comment by talldan** [comment]
I was thinking about this as a way to reduce the amount of checks in PRs by a factor of 3.

However, I just noticed when I went to the 'actions' tab in Github (https://github.com/WordPress/gutenberg/actions), that a little popup showed up asking me if I wanted to enable the new actions from this PR. I clicked enable. Let's see if that makes a difference.

There's also some details about the process on this PR:
https://github.com/actions/migrate/issues/26

**Comment by youknowriad** [comment]
We should rename the checks title to be smaller :)

**Comment by talldan** [comment]
I've spotted some issues. It looks like exit code 78 isn't supported any more by actions—created a PR here:
https://github.com/WordPress/gutenberg/pull/17002, but the filter we're using also uses 78.

Multiple checks are still showing. The logging shows that actions are being triggered multiple times for any of the following things that can happen to a PR:
`assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked`

Yet to discover if there's a way to improve this.

**Pull request merged**
