### PR TITLE
Upgrade framer-motion

### PR DESCRIPTION
**Pull request by sirreal**
## What?

Upgrade framer-motion package.

This is a significant diff, although I see no [release notes to speak of](https://github.com/framer/motion/blob/main/CHANGELOG.md#1100-2024-01-23) on why it's a major (potentially breaking) version change.

> [11.0.0] 2024-01-23
> Changed
> Replaced velocity-check jobs in favour of passive detection.
> Post-commit render moved to a microtask.

```sh
npm diff --diff=framer-motion@10.13.0 --diff=framer-motion@11.1.9
```

Includes https://github.com/WordPress/gutenberg/pull/61532
Extracted from https://github.com/WordPress/gutenberg/pull/61486

## Why?

This package has type conflicts with recent types, these can manifest causing build issues. https://github.com/framer/motion/pull/2587https://github.com/framer/motion/pull/2587

## How?

Upgrade the package to include the fix.

## Testing Instructions

I'm not sure where or how this is used.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I tested all the animations that I can think of in our code and everything seems to be working properly.

**Comment by sirreal** [comment]
There are 3 snapshot failures that are reproducible locally. I would really appreciate help getting this landed if someone can investigate those.

**Comment by youknowriad** [comment]
For me these snapshots are not very useful and ideally the test should be more specific.

That said, adding `opacity: 1;` to a div doesn't change anything really so I'd say just regenerate the snapshot. It's highly possible that some internal thing to motion.div is now adding the opacity explicitly (instead of omitting it) when it's 1 or something like that.

**Comment by sirreal** [comment]
I updated the snapshots.

**Pull request merged**
