### PR TITLE
Replace the fullscreen "x" icon with a back arrow

### PR DESCRIPTION
**Pull request by kjellr**
As per comments by @SNaushadS and others in #9567, the `x` icon in the upper left corner of fullscreen mode could be misinterpreted as a button for exiting out of full screen mode. Since the button takes you "back" to the All Posts screen, a back arrow may make more sense here.

Current: 

screen shot 2018-09-12 at 12 36 02 pm

New:

screen shot 2018-09-12 at 12 35 18 pm

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
Would this also be a good candidate for a tooltip?

**Comment by youknowriad** [comment]
@chrisvanpatten I think there's already a tooltip

**Comment by kjellr** [comment]
That's right:

screen shot 2018-09-12 at 12 52 52 pm

**Comment by chrisvanpatten** [comment]
My bad! 🙈

**Comment by jasmussen** [comment]
Love this, and love Andrews suggestion also.

**Comment by jasmussen** [comment]
Added the icon to Dashicons: https://github.com/WordPress/dashicons/pull/321

Added the sprite to Gutenberg in https://github.com/WordPress/gutenberg/pull/10025

CC: @kjellr

**Comment by kjellr** [comment]
@jasmussen You are the absolute best. Looks great:

screen shot 2018-09-19 at 1 17 50 pm

screen shot 2018-09-19 at 1 18 08 pm


Would someone mind giving this a review?

**Review by aduth — APPROVED** [review]
Code-wise this is 👍

**Comment by jasmussen** [comment]
Ship it!

**Comment by kjellr** [comment]
🎉  Thanks, all!

**Pull request merged**
