### PR TITLE
Icons: Update cloud upload and add cloud download icon.

### PR DESCRIPTION
**Pull request by matt-west**
## What?

Update the cloud upload icon to make the arrow more readable. This PR also adds a counterpart for cloud download this is not currently available.

[Figma assets](https://www.figma.com/design/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=101380-5176&t=rBwTA6B3mCzObCo6-4)

| Current | Proposal |
|--------|--------|
| cloud-upload-current | cloud-upload |
| Not available | cloud-download | 

## Why?

The current cloud upload icon likes whitespace around the arrow, which makes it difficult to quickly read at smaller sizes. 

There is no cloud download icon equivalent in the current icon package, however this could be useful for interfaces that include push and pull actions.

## Testing Instructions
Open Storybook and observe the icons.

## Screenshots or screencast 
The cloud upload icon is currently used in the editor toolbar on mobile. 

Here’s a comparison of how that toolbar looks with the current and proposed icons.

| Current | Proposal |
|--------|--------|
| Simulator Screenshot - iPhone 16 - 2024-10-07 at 10 11 54 | Simulator Screenshot - iPhone 16 - 2024-10-07 at 10 11 19 | 

Here’s a continuity test showing the new icons alongside others in the icon package.

imageimage

### CODE REVIEW

**Comment by matt-west** [comment]
@jasmussen @jameskoster Would you mind taking a look at this proposal for updating the `cloudUpload` icon to improve readability. I also added a corresponding `cloudDownload` icon to complete the set.

This work came out of a new push/pull feature we’re building for Studio, but thought it would be useful to have in Core too.

I’ve maintained the current cloud dimensions which fit snuggly within the `16px` guide. It feels a touch small to me in comparison to other icons though. What do you think?

**Comment by jasmussen** [comment]
At a glance, looks _substantially_ improved, solid work.

Do note that, at least for the moment and this is pending better ideas, the "cloud upload" button is the icon-fallback for "Save draft", when the post editor is on mobile. This was never great, and worth looking at separate mobile editing improvements, so that it can perhaps become a text button on mobile instead. But does this change anything as far as this work? My instinct, no, it's fine.

**Comment by matt-west** [comment]
> the "cloud upload" button is the icon-fallback for "Save draft", when the post editor is on mobile. This was never great, and worth looking at separate mobile editing improvements, so that it can perhaps become a text button on mobile instead.

Agreed. At the resolution shown below, it could make more sense to use an icon for the _Preview_ button and display the _Save draft_ text instead. There may not be enough space to accommodate that in non-English languages though.

image

**Comment by jameskoster** [comment]
Looks good to me, nice work. But lets update the svgs so they include a single path. We should add a changelog entry too.

**Comment by matt-west** [comment]
Thanks @jameskoster. I’ve reduced the icons to a single path and added entries to the changelog.

**Review by jameskoster — APPROVED** [review]
Looks good to me. Thanks so much :)

**Comment by matt-west** [comment]
@jameskoster Can you please set this to merge again. I rebased to bring in some changes from trunk that fixed a broken test but it disabled the auto-merge.

**Comment by jameskoster** [comment]
Done! Thanks again.

**Pull request merged**
