### PR TITLE
Tested up to WP 5.9

### PR DESCRIPTION
**Pull request by walbo**
## Description
- Update the tested up to version in the readme file.
- Update the tested up to version in the create block templates.
- Update the tested up to version in the create block tutorial template

## Types of changes
Non breaking change

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Makes sense to me. We should look at updating the minimum supported version to 5.8 a few weeks after 5.9 lands

**Comment by gziolo** [comment]
> Makes sense to me. We should look at updating the minimum supported version to 5.8 a few weeks after 5.9 lands

Can we do it now? Do you think there is a lot of value in using WordPress 5.7 with the most recent version of Gutenberg from the plugin's mission perspective? It creates a ton of maintenance burden, so I would consider dropping support when beta 1 for the next major release gets published. It means that now during 5.9 RC, we would support only 5.8. We would update the minimum version to 5.9 when 6.0 Beta 1 is ready, and so on.

**Comment by youknowriad** [comment]
@gziolo At this point it doesn't matter match for both cases. That burden is not going to be felt because 5.9 is almost "done" and by the time we land a PR to update the minimum version and ship a plugin release, 5.9 is going to be out in the wile 🤷‍♂️ 

If we are to change the policy for the future, that's something else (say by the start of 6.0 beta, we remove support for 5.8)

**Comment by gziolo** [comment]
> If we are to change the policy for the future, that's something else (say by the start of 6.0 beta, we remove support for 5.8)

Yes, this is exactly what I propose. At the same time we wouldn't have to wait a few more weeks to drop support for 5.7.

**Comment by Mamaduka** [comment]
I think this PR broke the performance test on the trunk.

**Comment by walbo** [comment]
> I think this PR broke the performance test on the trunk.

Looks like the performance tests uses the `Tested up to` to define what version of WP to use in https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/performance.yml#L50 

Since 5.9 isn't released before later today the WP version doesn't exists. Should the test use `latest` istead? (so it fetches https://wordpress.org/wordpress-latest.zip)

cc @youknowriad

**Comment by youknowriad** [comment]
the test shouldn't use latest because it would break with old branches. I guess we just merged this PR too soon, so we should just wait, it's just one day :)

**Pull request merged**
