### PR TITLE
[docs] fix incorrect es5 in transform example

### PR DESCRIPTION
**Pull request by dsifford**
Should be self-explanatory.

Let me know if there's any further details/clarification you'd like from me.

### CODE REVIEW

**Comment by dsifford** [comment]
Okay looking further into this, it appears that both ways are being used in `core/heading`... 

https://github.com/WordPress/gutenberg/blob/d0879a46999941ce1f229153febea8cfd96a75a0/packages/block-library/src/heading/index.js#L110-L131

What exactly is happening here? How is this even functioning right now? I must be missing something....

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @dsifford thank you for your contribution, this change looks correct 👍 
Would it also be possible to change the to transform samples, that contains the same error:
https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-registration.md#L283-L93

https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-registration.md#L319-L334

> What exactly is happening here? How is this even functioning right now? I must be missing something....

In the case you provided the code works because we are transfroming from a prefix transform and not from a block. In a prefix transform there is no block and the transform function just receives the text string in the content parameter.

**Comment by mkaz** [comment]
@jorgefilipecosta I think this one is now ready to go :+1:

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍

**Comment by dsifford** [comment]
Thanks for picking up my slack @mkaz! Sorry about that, other work got out ahead of me and needed to catch up. 😅

**Pull request merged**
