### PR TITLE
[WP6.2] Revert dynamic block anchor support

### PR DESCRIPTION
**Pull request by t-hamano**
## What?

This PR removes `anchor` support from `block.json` in dynamic blocks, among changes made in #44771.

## Why?
As reported by #48232, a problem was found in backward compatibility. A resolution was attempted in #48438, but more discussion and exploration are needed, so we have decided to revert this feature in the WordPress 6.2 release.

## How?
As noted in [this comment](https://github.com/WordPress/gutenberg/pull/48438#issuecomment-1448157260), we will follow these steps:

* Revert `block.json` anchor support from #44771.
* Remove `block-supports/anchor.php` from the core.
* Leave the `$attributes_to_merge` change in the core so that the feature can be implemented from the plugin.

This PR falls under the first step of the above.

First of all, I reverted the commit made in #44771. Then I re-added the PHP and documentation changes that did not need to be changed in this step.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think there's no need to keep PHP changes in the `wp/6.2` branch since the feature isn't shipping with this WP version.

**Comment by t-hamano** [comment]
> I think there's no need to keep PHP changes in the wp/6.2 branch since the feature isn't shipping with this WP version.

Makes sense, reverted.

**Comment by t-hamano** [comment]
[The E2E test is failing](https://github.com/WordPress/gutenberg/actions/runs/4293735990/jobs/7494299499) but does not appear to be related to this PR.

**Comment by Mamaduka** [comment]
Rebased the branch. The issue should be fixed after this backport https://github.com/WordPress/gutenberg/pull/48206#issuecomment-1448444069.

**Review by Mamaduka — APPROVED** [review]

**Comment by t-hamano** [comment]
Thanks for the response, @Mamaduka!

I would like to start with the following next steps.

> Remove `block-supports/anchor.php` from the core.

**Comment by Mamaduka** [comment]
@t-hamano, I already handled that this morning - https://core.trac.wordpress.org/ticket/57830#ticket.

**Pull request merged**
