### PR TITLE
Button component: Add margin around the dash icon

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
Dashicon is misaligned in the button component. Fixes it by making it look the same as an SVG icon. SVG icons are 24x24, whereas dashicons are 20x20. So the PR adds 2px margin to the left to make it centered and adds 10px (2px to center + 8px to add spacing between icon and text) to the right.

## How has this been tested?
1. Apply diff to change `strikethrough` icon to a dashicon:
```
diff --git a/packages/format-library/src/strikethrough/index.js b/packages/format-library/src/strikethrough/index.js
index bc64632bfa..6e7ed42688 100644
--- a/packages/format-library/src/strikethrough/index.js
+++ b/packages/format-library/src/strikethrough/index.js
@@ -22,7 +22,7 @@ export const strikethrough = {
 
                return (
                        <RichTextToolbarButton
-                               icon={ formatStrikethrough }
+                               icon="editor-strikethrough"
                                title={ title }
                                onClick={ onClick }
                                isActive={ isActive }
```
2. Open block editor
3. Add paragraph
4. Click dropdown in the toolbar
5. Make sure strikethrough text is aligned with the rest of the items

## Screenshots 

| **before** | **after** |
| - | - |
| image | image
 |

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Copons** [comment]
What about adding the `strikethrough` icon, reusing the original Dashicons' SVG source as an Icon component?

Basically moving (and adapting as needed) this:
https://github.com/WordPress/dashicons/blob/master/sources/svg/editor-strikethrough.svg?short_path=b0b9c01

into this folder:
https://github.com/WordPress/gutenberg/tree/master/packages/icons/src/library

**Comment by david-szabo97** [comment]
There are plugins out there are using dashicons. And the `Icon` component does support using dashicons so I think this CSS change is necessary.

**Comment by ntsekouras** [comment]
Your change makes sense to me, but should we make sure that this css won't affect other buttons that wouldn't need to? I haven't checked for other usages, but maybe there are other buttons with dashicon inside that need different margin 🤔

**Comment by david-szabo97** [comment]
All the dashicons are 20x20
image

Maybe it would make sense to change them to 24x24 in the toolbar? 🤔 Just to match them up with the SVG icons.

**Comment by ntsekouras** [comment]
>Maybe it would make sense to change them to 24x24 in the toolbar? 🤔 Just to match them up with the SVG icons.

I just tried that and doesn't work as expected, so your current change seems better. @jasmussen any input here :)

**Comment by jasmussen** [comment]
Dashicons are retired and we should encourage moving towards the new SVG icon component.

It's okay to support the 20x20 dashicons through the highly scoped `.dashicon` class, so in that vein, no objections to this CSS here, provided it works as intended. Be sure to test in plugin menus and for plugins that add pinned sidebars.

That said, I can't reproduce the specific steps here, I see the new WordPress icon for strikethrough:

Screenshot 2021-01-15 at 10 00 44

**Comment by ntsekouras** [comment]
> That said, I can't reproduce the specific steps here, I see the new WordPress icon for strikethrough:

@jasmussen just search for `icon={ formatStrikethrough }` (only one occurrence) and replace with `icon="editor-strikethrough"`.

Then in any RichText like paragraph check the misalignment.

**Comment by jasmussen** [comment]
Sure that lets me reproduce the issue. My point is: when I see a dashicon misaligned in the menu, my instinct is to replace it with a new icon, not to align the dashicon properly.

**Comment by david-szabo97** [comment]
> Sure that lets me reproduce the issue. My point is: when I see a dashicon misaligned in the menu, my instinct is to replace it with a new icon, not to align the dashicon properly.

That's right. This change is meant for third-party plugins. We should consider deprecating `dashicon` usage in the `Icon` component. A warning might help in letting know third-party devs to replace their dashicon with the new SVG icons or custom SVG icon.

**Comment by ntsekouras** [comment]
>We should consider deprecating dashicon usage in the Icon component. A warning might help in letting know third-party devs to replace their dashicon with the new SVG icons or custom SVG icon.

@david-szabo97 could you add this change as well in this PR?

**Comment by david-szabo97** [comment]
> > We should consider deprecating dashicon usage in the Icon component. A warning might help in letting know third-party devs to replace their dashicon with the new SVG icons or custom SVG icon.
> 
> @david-szabo97 could you add this change as well in this PR?

Would you mind if we get this merged and open a separate PR for the deprecation? Just to keep discussions separate.

**Review by ntsekouras — APPROVED** [review]
Thanks! 👍

**Pull request merged**
