### PR TITLE
TreeGrid: Update callback unit tests to use TreeGridRow and TreeGridCell sub components

### PR DESCRIPTION
**Pull request by andrewserong**
## Description

This is a quick follow-up to #38942 to update the `TreeGrid` component's tests for its callback methods to use the `TreeGridRow` and `TreeGridCell` subcomponents so that the tests better match real world usage of the component. Thanks for the feedback @ciampo! 

## Testing Instructions

Check that the CI jobs pass, or test locally via:

```
npm run test-unit -- --testPathPattern packages/components/src/tree-grid/test/index.js
```

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
LGTM - should [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/tree-grid/test/index.js#L49) also be updated at the same time?

**Comment by andrewserong** [comment]
Good thinking, thanks @glendaviesnz I've updated that test and the snapshot too 👍

**Review by glendaviesnz — APPROVED** [review]
LGTM 🎉

**Comment by ciampo** [comment]
Thank you @andrewserong and @glendaviesnz !

**Pull request merged**
