### PR TITLE
Footnotes

### LINKED ISSUE #1890: Add Footnotes Support
Implement a block for footnotes.

---

Prior pull requests: #2818

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #1890.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by paaljoachim** [comment]
@ellatrix Ella let us know how we can help.
Thank you for working on the footnotes feature!

**Comment by paaljoachim** [comment]
There was just a question on the Gutenberg plugin support forum about Footnotes:
https://wordpress.org/support/topic/footnotes-5/

**Comment by avirankatz** [comment]
This is a much required feature, would be great to see this in the next version

**Comment by paaljoachim** [comment]
Hey @ellatrix 

If you can get a first working version in place in this PR then we can go ahead and test it out and give feedback.
By downloading the Gutenberg PR build as mentioned here: https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/

Thanks!

**Comment by robsonsobral** [comment]
Is this PR dead?

**Comment by paaljoachim** [comment]
Hey @robsonsobral 

I assume it needs to be reworked.
It depends on a developer who is willing to continue @ellatrix's work or that she is able to find some time to work on this PR.

**Comment by robsonsobral** [comment]
Thank you, @paaljoachim .

I'm looking desperately for a markdown extra Gutenberg Block because of footnotes without look.

I'm no close to a WP dev to tackle this task myself.

Thank you!

**Comment by ellatrix** [comment]
Let's close this in favour of #47682 and discuss more there.

**Pull request closed without merging**
