### PR TITLE
[Block Library - Media Text]: Fix deprecations regression

### LINKED ISSUE #42805: Media & text block validation error from blocks in the pattern directory
### Description

Since https://github.com/WordPress/gutenberg/pull/40806 there is a block validation error for media & text block created before the pull request was merged. But the errors are specifically for media & text blocks in the pattern directory, and I am not able to reproduce it with local blocks.

### Step-by-step reproduction instructions

I used this method to test "local" blocks:

1. Deactivate Gutenberg. Activate Twenty Twenty-Two.
2. Using WordPress 6.0 or newer, go to either editor and add two media and text blocks:
one with media on the left, and one to the right. Save.
3. Activate Gutenberg trunk.
4. Refresh the editor where you placed the blocks.

You should see errors for block patterns in the block pattern directory if you open the browser developer tools console, but not for any of the blocks that are placed in the editor.

### Screenshots, screen recording, code snippet

[See screenshots in the discussion on the pull request.](https://github.com/WordPress/gutenberg/pull/40806#issuecomment-1193958784)

### Environment info

WordPress 6.0.1
Gutenberg current trunk.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/42805

Recently a [change](https://github.com/WordPress/gutenberg/pull/40806) in Media Text block introduced a regression in the deprecated versions handling. This PR fixes that.

## Testing instructions
1. No errors when loading the editor coming from pattern directory
2. No other errors or issues observed with Media Text blocks.
3. Test the below markup by deactivating GB, then save the post and the re-activate GB.

```
<!-- wp:media-text {"mediaPosition":"right","mediaId":5263,"mediaLink":"https://wordpress.org/patterns/pattern/image-and-quote-on-a-background/pear-3/","mediaType":"image","verticalAlignment":"center","style":{"color":{"background":"#f1f5c7"}}} -->
<div class="wp-block-media-text alignwide has-media-on-the-right is-stacked-on-mobile is-vertically-aligned-center has-background" style="background-color:#f1f5c7"><figure class="wp-block-media-text__media"><img src="https://s.w.org/patterns/files/2021/06/pear-1-1024x1024.png" alt="" class="wp-image-5263 size-full" /></figure><div class="wp-block-media-text__content"><!-- wp:group {"style":{"spacing":{"padding":{"top":"2em","right":"2em","bottom":"2em","left":"2em"}}}} -->
<div class="wp-block-group" style="padding-top:2em;padding-right:2em;padding-bottom:2em;padding-left:2em"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.2","fontSize":"36px"}}} -->
<p style="font-size:36px;line-height:1.2"><strong>Even the bitterest fruit has sugar in it.</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-small"} -->
<p class="has-extra-small-font-size">– Terry a O'Neal</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:media-text -->
```

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
It works as expected. Thank you, Nik!

What was the cause of the issue, the missing `supports` parameters?

**Comment by ntsekouras** [comment]
>What was the cause of the issue, the missing supports parameters?

Yes and the attributes could affect the comparison. 

Code ref: https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/parser/apply-block-deprecated-versions.js#L65
```
// Block type properties which could impact either serialization or
// parsing are not considered in the deprecated block type by default,
// and must be explicitly provided.
```

**Comment by carolinan** [comment]
Thank you!

**Comment by Mamaduka** [comment]
Cherry-picked for Gutenberg 13.8.

**Pull request merged**
