### PR TITLE
Improve inserter UI on mobile devices

### LINKED ISSUE #4077: Mobile inserter flow and iterations to the top bar
Right now the inserter flow and appearance is like this on mobile and it's not great:

issues-inserter

I am proposing an iteration to the inserter and flow that sees it adapt to the mobile experience.

inserter-flow-02

A few points to bring out here:

- The '+' inserting icon will on mobile only appear in the top bar. This will stay fixed to the top in order to allow this to be visible at all times. These top bar changes shown here are essential to this new flow. See 
- When clicking the '+' a modal will pop up (similar to now) with some visual changes.
- The modal will have a white header and in it a shortened (with '...') title of the post being written. This hooks it back to the original content.
- The inserter will be 3 columns (issue for desktop in #4080 ).
- The inserter will have center titles with lines to separate.
- Search highlights the input field to make sure the keyboard is connected to the focus area.

You can see the flow in the outlined mock.

### PR DESCRIPTION
**Pull request by noisysocks**
## Description

Closes #4077.

| Before | After |
| --- | --- |
| local wordpress test_wp-admin_post-new php_gutenberg-demo iphone 6_7_8 3  | local wordpress test_wp-admin_post-new php_gutenberg-demo iphone 6_7_8 2 |

Tweaks the inserter UI on mobile to display the post title in a header above the search bar. We accomplish this by adding a new `headerTitle` property to `<Popover>` and `<Dropdown>`.

## How Has This Been Tested?

1. Check that the new UI behaves correctly when viewed on a mobile device
2. Check that long post titles appear truncated with an ellipsis
3. Check that the UI has not changed when viewed on a desktop

### CODE REVIEW

**Comment by brandonpayton** [comment]
The implementation looks good to me, but I think it would be good to find a prop name that describes the purpose of the text better than ‘headerTitle’. It isn’t really the popover title but an indication that the popover exists in the context of editing a post. I haven’t thought of a better name yet but decided to share the concern.

**Comment by noisysocks** [comment]
I'm not sure, either. I was trying to choose a name that makes sense when you consider `Popover` by itself as standalone component.

Maybe we could adjust the existing `expandOnMobile` prop to accept options?

```js
<Popover expandOnMobile />
<Popover expandOnMobile={ { enabled: true, title: 'Title to show when expanded' } } />
```

**Comment by karmatosed** [comment]
Thanks for going this, so good to see mobile getting better each PR.

One tiny point, could we adjust the alignment so the title and search line up? I know they are different sizes but that slight out of line would be good to fix.

**Comment by noisysocks** [comment]
Thanks @karmatosed! I increased the padding on the search field so that the post title, _Search for a block_, and _Frequent_ all align:

local wordpress test_wp-admin_post php_post 218 action edit iphone 6_7_8

**Comment by youknowriad** [comment]
Noting that the title also shows up when you open the sidebar. Was this intended?

--
I'm no designer but is it obvious that this text is the post title? Also, the fact that it doesn' really look like a header is weird to me, but again I'm no designer just my two cents.

**Comment by karmatosed** [comment]
@youknowriad thanks for your feedback. There is a suggestion to make it grey, would you feel that made it more of a header?

**Review by karmatosed — APPROVED** [review]

**Comment by noisysocks** [comment]
> Noting that the title also shows up when you open the sidebar. Was this intended?

Yep, this was done in https://github.com/WordPress/gutenberg/pull/5511.

---

Thanks for reviewing. I'll merge this for now. Let me know if you want to tweak the colours, etc.

**Comment by youknowriad** [comment]
Yes, maybe I'd prefer if it was grey, but happy to try as is for now.

**Pull request merged**
