### PR TITLE
Set fixed version of @babel/runtime to 7.0.0-beta.55

### LINKED ISSUE #8580: @babel/runtime 7.0.0-beta.56 Causes build errors when using various packages.
**Describe the bug**
2 Days ago babel released `runtime` version 7.0.0-beta.56, which has breaking changes. These cause build errors in every project that require gutenberg packages that rely on babel.

**Workaround:** In the `package.json` of your project define ` "@babel/runtime": "7.0.0-beta.55",` as a dependency so `npm` doesn't install version `7.0.0-beta.56`.

**Screenshots**
screen shot 2018-08-06 at 10 49 42

**Additional context**
https://github.com/babel/babel/pull/8266

### PR DESCRIPTION
**Pull request by abotteram**
## Description

Set the version of `@babel/runtime` to the latest working version for @wordpress packages.

Fixes: #8580 

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by moorscode** [comment]
This should be a temporary fix. Preferred to set the minimal required version to 5.6 and adjust the code to work with the breaking changes introduced in that version.

**Comment by youknowriad** [comment]
What would be the fix if we want to upgrade to the last version?

**Comment by gziolo** [comment]
Yes, it would be nice to bump to the latest Babel version instead :)

**Comment by ntwb** [comment]
Why not upgrade the underlying issue?

i.e upgrade from `@babel/runtime` to `@babel/runtime-corejs2`

See also https://babeljs.io/docs/en/next/babel-runtime

**Comment by Xyfi** [comment]
@ntwb It seems that changing `'@babel/plugin-transform-runtime'` to `[ '@babel/plugin-transform-runtime', { corejs: 2 } ]` in `packages/babel-preset-default/index.js` is also a solution.

**Comment by Xyfi** [comment]
@ntwb @gziolo @youknowriad  but we should also set a fixed version for babel packages as long as it is in beta.

**Comment by ntwb** [comment]
@Xyfi It has been in _beta_ for quite some time and we are using _beta_ features I believe, @gziolo can also explain why the `^` caret is used, I believe it is a Lerna v3 functionality we are able to leverage that would not be typically used in a _single repo_ Node.js project.

**Pull request closed without merging**
