### PR TITLE
PostTaxonomiesFlatTermSelector: abstract wrapper component

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Follow up to:

- https://github.com/WordPress/gutenberg/pull/66566

Noticed by me and @kevin940726 while testing https://github.com/WordPress/wordpress-develop/pull/7693

Props to @kevin940726 for working out the culprit

## Why?

The controls appears to rerender when adding a tag, or at least, it loses focus.

https://github.com/user-attachments/assets/36f0ee20-495f-4e03-b38d-190edcf746cb

## How?
Extract Wrapper into an external component to avoid rerender, and therefore, blur/clearing tag control.

## Testing Instructions

1. Create a new post or page.
2. Add a tag in the post/page settings side bar.
3. Ensure that you can continue to add tags and that your input is not lost.

https://github.com/user-attachments/assets/24749b4b-10f9-48e8-a91c-6b90d6480ed0

### CODE REVIEW

**Review by kevin940726 — APPROVED** [review]
Works like a charm 💯.

**Comment by andrewserong** [comment]
Thanks for the quick fix!

**Comment by Mamaduka** [comment]
Thanks for fixing this, @ramonjd and @kevin940726!

Side note: We need to stabilize the e2e test runner and reporter. Otherwise, the genuine regressions can be (and are) ignored with the current report rate.

**Comment by t-hamano** [comment]
Thank you for the quick fix!

**Comment by priethor** [comment]
I just cherry-picked this PR to the release/19.6 branch to get it included in the next release: bec138a1a42

**Pull request merged**
