### PR TITLE
[Inserter]: Fix `onHover` error on patterns tab in mobile

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Follow up of: https://github.com/WordPress/gutenberg/pull/47316

Fixes the error when we try to insert a pattern from the main inserter, in mobile view.

## Testing instructions
1. In mobile view, open a page/post and then the main inserter
2. Go to the patterns tab and select one to insert it
3. No errors should occur

### CODE REVIEW

**Review by ndiego — APPROVED** [review]
This fix works as expected. 💪

Previously, inserting a pattern on a mobile device with trigger an error. Using Gutenberg with this fix solves the issue.

patter-error

**Comment by Mamaduka** [comment]
The failing test was fixed in #49455.

**Comment by ryanwelcher** [comment]
I just cherry-picked this PR to the release/15.5 branch to get it included in the next release: 73c3b837c6

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: [7eb2a4e](https://github.com/WordPress/gutenberg/commit/7eb2a4e47aa7c7b61c4a21277f89091bd9f98690)

**Pull request merged**
