### PR TITLE
Fix Copy block button focus loss and try to remove the visually hidden textarea

### LINKED ISSUE #23994: The new "copy block" action triggers a focus loss
**Describe the bug**

In WordPress 5.5, the block editor has a new feature to copy the block content. When using a keyboard, activating the "Copy" button triggers a focus loss: focus is lost and the tab sequence starts over from the document root.

Focus losses are one of the worst experiences for keyboard users and assistive technologies users, as any previous context is lost and users are forced to navigate again though great part of the UI to get back to the previous position.

**To reproduce**
- in WordPress 5.5 Beta 2
- edit a post
- edit a paragraph
- using the keyboard, navigate to the block toolbar:
  - either by pressing Shift-Tab
  - or by pressing Alt+F10
- focus is now on the toolbar
- use the left/right arrow keys to move to the "More options" button in the toolbar
- press Enter or Spacebar to open the More options menu
- use the down/up arrow keys to navigate to the "Copy" button
- activate the "Copy" button either with Enter key or Spacebar key
- the block content is copied, a "snackbar" notification appears
- now press the Tab key
- observe the tab sequence start over from the document root: the first focused element is the skip link

Animated GIF to illustrate the behavior:

copy block

Noting that:
- the focus loss doesn't happen when using the keyboard shortcuts Cmd (Ctrl) + C
- doesn't happen when cutting a block with Cmd (Ctrl) + X

Since this is a new feature in WordPress 5.5, I'm setting the priority to "high" as any new released feature should be as accessible as possible (certainly should avoid focus losses).

### PR DESCRIPTION
**Pull request by afercia**
closes #23994 

## Description

This PR seeks to solve two issues with the Clipboard.js-powered "Copy" block button.

1. Focus loss when pressing the button
2. The visually hidden textarea used by Clipboard.js is added within the button and stays there: thus, there's an additional, unexpected, tab stop and the textarea is announced by screen readers

For more details, please see the related issue https://github.com/WordPress/gutenberg/issues/23994

## Notes

These behaviors are Clipboard.js bugs (or "features") that produce a sub-optimal experience for keyboard users and assistive technology users.

While working on recent changes in WordPress core I stumbled upon the same issues. See:
https://core.trac.wordpress.org/changeset/48233
https://core.trac.wordpress.org/changeset/48232

I also reported these two issues upstream:
https://github.com/zenorocha/clipboard.js/issues/680
https://github.com/zenorocha/clipboard.js/issues/684

In the meantime, I guess they can be fixed in our implementation.

1
The focus loss is fixed by explicitly setting the focus back on the button. See also similar fixes used in the core changesets linked above.

2
I'd greatly appreciate some help to fix the second issue. 
Ideally, the visually hidden textarea should be removed on the copy action `success`. This is why I fixed it in core. Worth noting Clipboard.js re-adds the textarea at any click so removing it on success looks safe.

However, I couldn't find a nice way to use the fix used in core also in `useCopyOnClick`.

As far as I see, `clipboard.current.destroy();` is used in the `useEffect` cleanup but that's not enough.
It should be called on success. I couldn't find a way to make it work other than adding _one more timeout_ which I guess isn't ideal. Any help would be greatly appreciated.

### CODE REVIEW

**Comment by afercia** [comment]
Fixes https://github.com/WordPress/gutenberg/issues/23994

**Comment by afercia** [comment]
To clarify: I did try to call `clipboard.current.destroy()` in the `success` callback but that doesn't seem to work unless using a `setTimeout()`.

**Comment by afercia** [comment]
Question:
Is there the need to add the visually hidden textarea within the button in the first place? See:
`container: ref.current,`

Now that the implementation is based on `useEffect`, seems to me it would be safe to remove `container: ref.current,` and let `Clipboard.js` append the visually hidden textarea to the body. I tested it a bit and seems to me this way the textarea is removed after copying. Also, the `useEffect` cleanup makes sure the textarea is removed when the component unmounts, correct? Am I missing something?

Pinging @ellatrix and @gziolo as I saw you worked on this bit of code.

**Review by youknowriad — APPROVED** [review]
This fix is looking good for me. I don't know about the other suggestion. Hopefully, someone will chime in.

**Comment by afercia** [comment]
I _can_ open a separate issue, but that requires time. My time is _very, very, limited_. I'd appreciate if next time an issue gets closed when all the problems reported are actually fixed...

**Comment by ellatrix** [comment]
@afercia So is everyone's...

**Comment by afercia** [comment]
I just wanted to note that closing issues and merging PRs that don't fully solve the reported bugs don't help in spending our time in the best way.

**Pull request merged**
