### PR TITLE
Add font weight picking mechanism

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR adds a font-weight picking mechanism.

The mechanism is very simple and allows to use all valid CSS values for font-weight. Themes can disable font-weight picking via theme.json or set default values there.

Question: Should themes be able to restrict what font weights are available? If yes, should the restriction be dependent on a font family?

## Screenshots 

image

image

### CODE REVIEW

**Comment by aristath** [comment]
Hmmm inherit & initial are OK as words, but the rest of them IMO should not be available both as numeric values and text... Bold is the same as 700 in most cases, or at least that is the CSS convention.
It would make more sense to me as a user to have options formatted like this instead:
```
[
	{ value: 'inherit', label: __( 'Inherit' ) },
	{ value: 'initial', label: __( 'Initial' ) },
	{ value: '100', label: __( '100 - Thin' ) },
	{ value: '200', label: __( '200 - Extra Light, Ultra Light' ) },
	{ value: '300', label: __( '300 - Light' ) },
	{ value: '400', label: __( '400 - Normal, Book, Regular' ) },
	{ value: '500', label: __( '500 - Medium' ) },
	{ value: '600', label: __( '600 - Semi Bold, Demi Bold' ) },
	{ value: '700', label: __( '700 - Bold' ) },
	{ value: '800', label: __( '800 - Extra Bold, Ultra Bold' ) },
	{ value: '900', label: __( '900 - Black, Heavy' ) },
]
```

> Question: Should themes be able to restrict what font weights are available? If yes, should the restriction be dependent on a font family?

Tricky topic.
If themes & plugins are allowed to add google-fonts, adobe-fonts etc via hooks, then they will definitely need a way to limit the font-weights depending on the font-family selected.
Not all font-families are available on all font-weights, and depending on the webfonts platform used, selecting a non-existing font-weight for a font-family may return an error and the webfont won't get loaded.
So a filter should be available for the weights, accompanied by an event which will trigger on font-family switching.

**Comment by aristath** [comment]
I was thinking about this one this weekend... It's something we'll definitely need, but then I realized that we may need 2 controls implementations for this!
Traditionally fonts have weights ranging from `100` to `900`, with a step of `100`. But nowadays we also have Variable Fonts, and they are getting increasingly popular. These fonts don't have "standard" font-weights, and are a lot more versatile.
Google fonts already have [a big collection of variable fonts](https://fonts.google.com/?vfonly=true) and more are added every day (or current "legacy" fonts are getting converted to variable fonts).
An example of the Literata font (also available on GFonts) can be seen below, there the weight can be any number between 200 and 900.

Screencast showing the font-weight of the Literata font, smoothly changing using a slider control

If I'm using a variable font-family on my site and have found that a font-weight of 350 is what I need for my design, then 300 or 400 will be close, but not quite right. So the dropdown won't do in that case, I'd need a slider - otherwise I'd have to resort to writing custom CSS for that :thinking:

**Comment by LittleBigThing** [comment]
Couldn't choosing the **font weight** be similar to choosing **font size** for consistency?

We could have a set of registered weights, optionally with names, per font family. And then there could be a dropdown for custom weights. Custom weights could be disabled by the theme completely, just like for font sizes. Custom weights could be restricted or a range if it is a variable font?

Also, I am not sure either whether using inherit and initial (and too much options) are useful for average users (however they are defined).

**Comment by jorgefilipecosta** [comment]
Closed in favor of https://github.com/WordPress/gutenberg/pull/26444.

**Pull request closed without merging**
