### PR TITLE
Fix props in example code for Edit Post module

### PR DESCRIPTION
**Pull request by ediamin**
## Description

Fix the props in example code for Edit Post module's [PluginBlockSettingsMenuItem](https://github.com/WordPress/gutenberg/tree/master/packages/edit-post#PluginBlockSettingsMenuItem) API

## How has this been tested?

I made a custom component that uses this example code snippet with my fixes.

## Types of changes

Fixed with proper JSX syntax that we use to write props value

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Thanks for the fix 👍

**Review by gziolo — CHANGES_REQUESTED** [review]
Travis fails and I discovered what’s the reason. The same change needs to be applied to JSDoc comment of the documented component. So it’s autogenerated from source code with `npm run docs:build` command.

**Comment by ediamin** [comment]
@gziolo updated the JSDoc too. I hope this time Travis won't fail.

**Review by gziolo — APPROVED** [review]
All good now, thanks!

**Pull request merged**
