### PR TITLE
Site Editor: Check whether the data is loaded. If the data is loaded and the template is still unknown, give appropriate feedback

### LINKED ISSUE #29265: Site Editor: Stuck in loading if a non-existing postId is given
## Step-by-step reproduction instructions
1. Start your local dev environment
2. Open site editor using this link: http://localhost:8888/wp-admin/admin.php?page=gutenberg-edit-site&postId=nothing&postType=wp_template (note `postId=nothing`)

## Expected behaviour
Either
- show template not found
- load homepage

## Actual behaviour
Stuck in loading with grey screen

## Screenshots or screen recording (optional)
http://localhost:8888/wp-admin/admin.php?page=gutenberg-edit-site&postId=nothing&postType=wp_template
image

## WordPress information
- WordPress version: 
- Gutenberg version: `master`
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 blocks

## Device information
- Device: Desktop
- Operating system: Mac Big Sur
- Browser: Chrome latest

### PR DESCRIPTION
**Pull request by boblinthorst**
## Description

Created to try and resolve https://github.com/WordPress/gutenberg/issues/29265.

Shows "Template not found" if there's no found template for the post id.

I'm not particularly comfortable in this context, so if this PR does not solve the issue in the desired way, don't feel bad about closing it. 

## How has this been tested?

I visited the proved link in the issue, and checked the added feedback is shown. I also visited a normal template page, to ensure this feedback does not show when it is not appropriate.
## Screenshots 

Site_Editor__beta__‹_WordPress_Awesome_—_WordPress

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by aristath — APPROVED** [review]
Looks good to me, however, I'd be more comfortable merging this with a 2nd review from someone

**Comment by youknowriad** [comment]
That PR is fine but I wonder if it's actually better to show a message on a higher level (hide the entire page) similar to what is done on the post editor?

Capture d’écran 2021-04-12 à 9 11 12 AM

**Comment by aristath** [comment]
Hmmm I kinda prefer this implementation... It still shows the site-editor and I can navigate to a different template and keep working. The post-editor one is good at what it does, but it would feel a bit like a screen-of-death in the site-editor IMO 🤔

**Comment by youknowriad** [comment]
Maybe then a message on the  "canvas" of the site editor? I don't feel strongly here either way :)

**Comment by david-szabo97** [comment]
> Maybe then a message on the "canvas" of the site editor?

This. The text in the header doesn't really stand out in this case so it's easy to miss it. We could use the same message as we use for the post editor: "You attempted to edit an item that doesn't exist. Perhaps it was deleted?"

Otherwise looks good and works well! Thanks for working on this! 🙇

**Comment by aristath** [comment]
Thank you both for the feedback, excellent points!

@bobbingwide is currently unavailable to continue working on this (the PR was part of a contributors-day) so I pushed a commit to add a notice in the canvas when the template can't be found:

perhaps-deleted-notice

Would that work? 
Someone else will need to review the PR and give the 🆗✅  before we proceed

**Comment by bobbingwide** [comment]
> @bobbingwide is currently unavailable to continue working on this (the PR was part of a contributors-day) 

I think you meant @boblinthorst

**Comment by aristath** [comment]
Oops, my bad... apologies, bad github auto-complete 🤦

**Comment by david-szabo97** [comment]
Looks good to me! Once we have a test I'm happy to approve 😄

**Comment by aristath** [comment]
> Looks good to me! Once we have a test I'm happy to approve 😄

That's going to be a problem... I don't (yet) know how to write these tests 🤐😅

**Comment by david-szabo97** [comment]
> > Looks good to me! Once we have a test I'm happy to approve 😄
> 
> That's going to be a problem... I don't (yet) know how to write these tests 🤐😅

Would you be interested in writing your first test? :D If not, let me know and I'll take it over.

First of all, we don't really have a function that you can use to visit the site editor with specific URL parameters. In our case we need to visit the site editor with custom URL parameters to access a non-existing template. You can extend the existing `visit()` function at https://github.com/WordPress/gutenberg/blob/aa05bd47df3247730065b197a170ab84e4c6761f/packages/e2e-tests/experimental-features.js#L105 Basically you just need to add a new parameter and destructure it into the `query`.

Once that's done you can create a new test file in: https://github.com/WordPress/gutenberg/tree/trunk/packages/e2e-tests/specs/experiments

You should copy-paste an existing test as a base for your test. https://github.com/WordPress/gutenberg/blob/37e15797f2259ee0661b56b5a8f877bde9f29099/packages/e2e-tests/specs/experiments/site-editor-export.test.js is a very short test file that should work for you.

**Review by david-szabo97 — APPROVED** [review]
Rebased, once tests are passing I'll merge

**Pull request merged**
