### PR TITLE
Make anchor always render after Additional CSS class

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/7964

### CODE REVIEW

**Comment by gziolo** [comment]
I suspect it might produce another issue when the combination of advanced controls is different.

What if you have blocks as follows:
- anchor & class name
- anchor only
- class name only

Depending on the order of re-render it might still differ. I think there is something with keys applied to fills which doesn't trigger full re-render. Maybe we should always reset slots when a different block is selected. I don't know, we had similar issues in the past. @aduth fixed them but it looks like we still encounter some very rare edge case. Unfortunately, I couldn't identify the prior fix.

**Comment by nosolosw** [comment]
> I suspect it might produce another issue when the combination of advanced controls is different.

@gziolo Yeah, that's the concern I've mentioned [in the original issue](https://github.com/WordPress/gutenberg/issues/7964#issuecomment-434681969) and the reason I'd be cautious before applying this PR.

**Comment by aduth** [comment]
If these are added by filters and there's a desired order, it seems like something we should be using filter priority for. 

https://www.npmjs.com/package/@wordpress/hooks

**Comment by nosolosw** [comment]
Closing this as I think we prefer alternate approaches to fix the general issue.

**Pull request closed without merging**
