### PR TITLE
Scripts: Use the latest version of webpack for build and start commands

### PR DESCRIPTION
**Pull request by gziolo**
## Description
This PR upgrades the version of `webpack` used in `@wordpress/scripts`.

There should be no changes in how `npm run dev` and `npm run build` work in Gutenberg.

In addition, I updated the list of dependencies for `@wordpress/scripts` to use ranges for consistency.

### CODE REVIEW

**Comment by gziolo** [comment]
cc @jsnajdr @simison

**Comment by simison** [comment]
Failed JavaScript unit tests just look like you should update some snaps?

**Comment by gziolo** [comment]
> Failed JavaScript unit tests just look like you should update some snaps?

I will fix it soon. It looks like `webpack` produces a different hash for files, interesting. @sirreal, any idea what could happen?

**Comment by gziolo** [comment]
Updated with 29a3e3e.

**Comment by gziolo** [comment]
@youknowriad - this is another one to include in the npm release process since we use a super out of date version of `webpack`.

**Comment by jsnajdr** [comment]
> It looks like webpack produces a different hash for files, interesting.

That hash includes also the webpack runtime code. If something in the code that loads and executes the webpack chunks and modules changes, the bundle's hash will change, too.

**Review by simison — APPROVED** [review]
CI build obviously succeeds and I appreciate the version range change. 👍 

Does version range change need a major Semver update?

**Comment by gziolo** [comment]
> Does version range change need a major Semver update?

`webpack` follows sem ver as far as we can tell, so it's safe to assume there are only enhancements added given it is still v4.x.

**Comment by gziolo** [comment]
@youknowriad - another one to include in the next npm release.

**Pull request merged**
