### PR TITLE
Removes hardcoded body text color from some block patterns

### LINKED ISSUE #24391: Some block patterns don't respect the theme color palette and look out of place or broken
**Describe the bug**

Some block patterns have hardcoded color values and don't follow the theme palette, causing them to look out of place or broken when used from some themes. 

I've found the following blocks seem to have hardcoded values by adding them to a dark them (`Rivington`):

* `Two columns of text`
* `Two columns of text with images`
* `Three columns of text with buttons`
* `Heading and Paragraph`

The blocks above will probably look broken under darker themes.

I'm not sure about the following blocks as they look okay under `Rivington`, but I suspect they also have hardcoded color values:

* `Large header with a heading and a button`
* `Large header with a heading`
* `Three buttons`
* `Two buttons`

**To reproduce**

1. Install and activate Gutenberg `8.7` in your WordPress instance;
2. Install and activate a dark theme, e.g. [`Coral Dark`](https://wordpress.org/themes/coral-dark/);
3. Add a new post;
4. Add any of the block patterns listed above to the page and observe how they look out of place or broken visually.

**Expected behavior**

The blocks get the right color values from the theme and blend in nicely.

**Screenshots**

| `Two columns of text` | `Two columns of text with images` | `Three columns of text with buttons` | `Heading and Paragraph` |  `Large header with a heading and a button` | `Three buttons` | `Two buttons` |
| --- | --- | --- | --- | --- | --- | --- | 
| twocolumnsoftext | twocolumnsoftextwithimages | threecolumnsoftextwithbuttons | headingandparagraph | largeheaderiwithaheadingandabutton | threebuttons | twobuttons |

**Editor version (please complete the following information):**
- WordPress version: `5.4.2`
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? `gutenberg plugin`
- If the Gutenberg plugin is installed, which version is it? `8.7`

**Desktop (please complete the following information):**
 - OS: `Linux Mint 18.04`
 - Browser: `Firefox Quantum 80.0b4`

### PR DESCRIPTION
**Pull request by enriquesanchez**
Fixes #24391 

## Description
Removes some hardcoded text color values from patterns that have body text with no specific background color. This ensures that it respects the themes default color for body text and avoids contrast issues, particularly in dark themes.

## Screenshots 

**Two columns of text**

| Before             | After     |
| :------------- | :----------: |
|  Screen Shot 2020-08-06 at 13 02 17 | Screen Shot 2020-08-06 at 13 02 10   |

**Two columns of text with images**

| Before             | After     |
| :------------- | :----------: |
|  Screen Shot 2020-08-06 at 13 01 26 | Screen Shot 2020-08-06 at 13 01 35 |

**Text three columns and buttons**

| Before             | After     |
| :------------- | :----------: |
|  Screen Shot 2020-08-06 at 13 03 21 | Screen Shot 2020-08-06 at 13 02 31 |

**Heading and a paragraph**

| Before             | After     |
| :------------- | :----------: |
| Screen Shot 2020-08-06 at 13 03 25 | Screen Shot 2020-08-06 at 14 01 01 |

## Types of changes
Visual changes to block patterns.

### CODE REVIEW

**Comment by mapk** [comment]
Most of them worked well for me.

✅  Two columns of text
✅  Two columns of text with images
✅  Three columns of text with buttons
❌  Heading and Paragraph

patterns


For some reason, the Heading and Paragraph was showing a block error for me in both the Preview and on the page.

Screen Shot 2020-08-06 at 12 55 41 PM

When I attempted the block recovery, it showed the Heading, but without the proper color contrast.

Screen Shot 2020-08-06 at 12 56 05 PM

**Comment by youknowriad** [comment]
I think going forward ideally, it's better to make these fixes in Core itself or in both places. At some point once the plugin will start requiring WP 5.5 as the minimum version, we will be able to remove them entirely from the plugin.

**Comment by fullofcaffeine** [comment]
Hi @enriquesanchez, thanks a lot for working on this 🙇🏻 

I see that @mapk already tested it quite well, but I went ahead and tried it myself, too, nevertheless. Here are my findings:

The "Headings And Paragraphs" pattern shows an "invalid content" error message:

1p

After attempted recovery:

1q

The thumbnail in the inserter is also shown with the error message:

1r

This also happens with these related blocks:

issues

After attempted recovery:

recovery

The other blocks changed here looks fine:

lookfine


I tested locally in a custom wp-env running WP `5.4.2`, Gutenberg 8.7 (checked-out and built from within this branch) 
wppl

wpv

and with the Rivington theme activated:

wprv


I'm assuming this should be a simple thing to fix. Let me know if I can help!

**Comment by enriquesanchez** [comment]
Thanks, @fullofcaffeine and @mapk for help testing! 🙌 

 I think I've fixed the invalid content issue.

**Review by mapk — APPROVED** [review]
It appears to be working great for me now.

**Preview**

Screen Shot 2020-08-10 at 4 39 39 PM

**Pattern**

Screen Shot 2020-08-10 at 4 39 46 PM

**Comment by enriquesanchez** [comment]
Corresponding Trac ticket for reference: https://core.trac.wordpress.org/ticket/50892

**Pull request merged**
