### PR TITLE
Handle direct image data paste

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
This PR aims to:

1. Allow pasting standalone images directly into Gutenberg and upload them.
2. Upload pasted base64 encoded images.

## How Has This Been Tested?
1. Right click any image (on the web or in a native app) and choose "Copy image". *Not* "Copy Image URL/Address". Not sure how this works on Linux and Windows. This copies the image data, no HTML. Now paste it in Gutenberg. Without this PR, nothing will happen. With this PR, it should be inserted as a block and be uploaded to the server.
2. Find a base64 encoded image. Pasted content from MS Word Online has it for example. Without this PR it will display (data in src). With this PR it will display as a linked blob (no data in src) and upload.

## Screenshots (jpeg or gifs if applicable):

screenshot 2017-09-26 00 03 15

### CODE REVIEW

**Comment by mkaz** [comment]
I first tested "Copy Image" without the PR and it still pasted the image but it did so by setting the img src to the original external URL, the img tag was included within the text block which confused Gutenberg a little.

With the PR implemented, the pasting of the image worked as described. Tested on both Firefox on Linux and Edge on Windows. Both worked as expected, uploading the image and creating a block. 

One minor issue was my cursor needed to be within the preceding text block in order to paste. I'm not sure if that can be overcome, since I don't think the browser has a focus on where the paste should go.

One major issue is when simply trying to add a new Image block I would get the following error

block-suffered

**Review by mkaz — CHANGES_REQUESTED** [review]
See previous comment. Inserting image causes block suffering

**Comment by iseulde** [comment]
> One minor issue was my cursor needed to be within the preceding text block in order to paste. I'm not sure if that can be overcome, since I don't think the browser has a focus on where the paste should go.

Could you elaborate? What's happening exactly and what do you expect?

**Comment by mkaz** [comment]
I switched from the Gutenberg editor tab to the browser tab that had the photo I wanted to copy. After right-click and copying, I switched back to the Gutenberg tab and typed `ctrl-v` to paste, nothing happened. There was no cursor showing on the Gutenberg editor, however once clicking into the existing text block to get a cursor and then typing `ctrl-v` the paste worked as expected.

**Comment by iseulde** [comment]
Sounds like #2303 :)

**Comment by iseulde** [comment]
I'm hoping we can fetch all blobs back with `fetch( url ).then( ( response ) => response.blob() )`, but I'm having issues with some URLs. Looking into that.

**Comment by mkaz** [comment]
@iseulde yep, looks like the same issue.

I also reviewed your a0a428a update and it fixes the previous issue.

:+1:

**Comment by mkaz** [comment]
One thing I just noticed that an empty block is created below the new image block.

**Comment by iseulde** [comment]
@mkaz I believe that's chrome right? Yeah, I'm aware, it should normally split the block and insert in between, but for some reason the selection changes.

**Comment by iseulde** [comment]
I've been searching for hours, but can't figure out why it won't work in this context. When you fetch the URL, it comes back as plain text. Even loading it in a tab it's plain text, but inside the image source it's not... I made a codepen, but there it works fine... https://codepen.io/iseulde/pen/qPrNWz

**Comment by iseulde** [comment]
Abandoning searching for the cause. Let's just keep caching the blob and use that. I'll look into the splitting issue now

**Comment by iseulde** [comment]
Don't know what goes wrong in chrome with the selection. today I wanted to try again, but now the paste event won't fire at all with image data... 🤷‍♀️

**Comment by iseulde** [comment]
Rebased, will attempt to fix the issues again.

**Comment by iseulde** [comment]
@mkaz Okay, fixed the Chrome issue. How is it working now on your end? Tested Firefox, Safari and Chrome, all works great.

**Review by mkaz — APPROVED** [review]

**Pull request merged**
