### PR TITLE
Render `InlineUI` only if modal is closed and object is active

### LINKED ISSUE #27608: Inline image width dialogue overlays media libary
**Describe the bug**
Originally reported in [Trac-51983](https://core.trac.wordpress.org/ticket/51983) by @cjallen1.

After inserting and selecting an inline image and clicking inline image again (to replace the image), the width field is displayed on top of the media library.

**To reproduce**
1. Open the editor.
2. Insert an inline image into a paragraph block.
3. Click "inline image" again.
4. Notice the width input is on top of the media library.

**Screenshots**
Screen Shot 2020-12-09 at 08 51 28
Screen Shot 2020-12-09 at 08 51 15

Was able to reproduce with a fresh install on WordPress `trunk`. Also tested with the Gutenberg plugin active, but the issue persists.

### PR DESCRIPTION
**Pull request by hsingyuc**
## Description
Fix #27608 
Render `InlineUI` only if the modal is closed and the object is active

## How has this been tested?
1. Insert an inline image, click on the image, and click on `inline image` on the editor.
1. Check if the modal and `InlineUI` render as expected.

## Screenshots 
1. Before
before

2. After
test
after

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — COMMENTED** [review]
Thanks for the PR @hsingyuc!

Whilst this works well, I was wondering if you considered adjusting the z-index of the image size popover? Anything 160000 or lower seems to work, and I feel like that'd be the right way to go.

I noticed there's a special z-index in place on the video block's tracks popover, so this would be similar to that:
https://github.com/WordPress/gutenberg/blob/576efb31ae3d175b57c421594ca19ff79a382d52/packages/base-styles/_z-index.scss#L53-L54

Adjusting the z-index seems like it'd require the following:
- Adding a classname to the popover in the InlineUI component (something like `block-editor-format-toolbar__image-popover`)
- Adding a new z-index to the z-index file above
- Adding a style for the popover in the packages/format-library/src/image/style.scss file.

**Comment by hsingyuc** [comment]
@talldan Thanks for the review! 

I used z-index locally to solve the problem, but after considering the accessibility concerns, I think not showing the popover seems better than hiding it via z-index. Are there advantages to using z-index in this case?  Please let me know if I'm missing something.

**Comment by talldan** [comment]
@hsingyuc Would you be able to go into more detail about the accessibility concerns?

**Comment by hsingyuc** [comment]
@talldan My understanding is the popover can announce itself on screen readers when mounted. It also detects clicks outside of the popover using `PopoverDetectOutside`. I feel using z-index will lead to unexpected behavior while the media modal is open, but please let me know if I'm wrong on this and I can update accordingly.

**Comment by talldan** [comment]
> My understanding is the popover can announce itself on screen readers when mounted.

@hsingyuc I don't think there are any announcements when a popover is already open, only when focus enters or is within a popover will a screenreader convey the semantics.

>  It also detects clicks outside of the popover using PopoverDetectOutside.

`PopoverDetectOutside` only works when focus is inside the popover, so I don't think this will cause an issue.

There are a few other places in the UI where popovers are open in the background while modals are open, so I don't think there will be any problems.

As an aside, I've noticed while testing that it doesn't seem to be possible for users to access the image size popover using a keyboard only, so I've made a separate issue for that (https://github.com/WordPress/gutenberg/issues/28159).

**Comment by hsingyuc** [comment]
@talldan  ok! Changes have been pushed.

**Comment by talldan** [comment]
Thanks, I've approved and merged that one, so will close this one.

**Pull request closed without merging**
