### PR TITLE
Gallery: Update UI of controls

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description
This update adjusts the UI of the left/right and close controls of a Gallery item with the core Gallery block. 

## How has this been tested?
* Tested locally on Gutenberg

## Screenshots 
Screen Shot 2020-03-10 at 4 28 04 PM

## Types of changes
* Update Gallery control icons to use Chevron (left/right) from @wordpress/icons
* Reduce Gallery custom control border radius

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Resolves comment from:
https://github.com/WordPress/gutenberg/issues/20575#issuecomment-596217030

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Nice work, this is what I see:

gallery

- Better icons
- Correct border radius
- Works well!

This is before:

Screenshot 2020-03-11 at 08 07 30

Nice!

**Comment by mtias** [comment]
I like that it's also mostly red code :)

**Review by youknowriad — APPROVED** [review]
Nice

**Comment by jasmussen** [comment]
Red code is the best code.

**Comment by ItsJonQ** [comment]
Thanks for the review all! Yes, red code is best code 😂 .
Will merge it up

**Pull request merged**
