### PR TITLE
Adjustments for welcome guide

### PR DESCRIPTION
**Pull request by karmatosed**
- Reduces header to have text on desktop on one line.
- Reduces line-height on header and makes it number over px.
- Tried to avoid widows but needs longer lasting solution.

Before

image

After

image

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Thanks for working on this. 

This is a small PR, which improves the situation:

welcome

I would suggest this window needs a fair bit of more love than just this one PR. The vertical alignment of the text jumps quite a bit between slides, and overall the layout could use a little massaging, perhaps even rephrasings. The icons in the SVGs also look squished in places, even if they aren't.

However because this is such an improvement over what's currently merged, it's good as an interim fix provided we do more polish!

**Comment by karmatosed** [comment]
I agree this needs deeper iterations as yes this is just a little plaster fix.

**Comment by marco-firmo** [comment]
Hey, with the latest version of Gutenberg i found that problem:

TypeError: Cannot read property 'disableTips' of null
    at ho (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/build/edit-post/index.js:6:82642)
    at je (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:78:476)
    at ph (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:215:173)
    at lh (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:126:409)
    at O (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:121:71)
    at ze (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:118:14)
    at http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:53:49
    at unstable_runWithPriority (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react.min.0212dc62.js:26:340)
    at Ma (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:52:280)
    at mg (http://palazzoducale.genova.it/wp-content/plugins/gutenberg/vendor/react-dom.min.b694e242.js:52:496)

My Wordpress Setup
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

extension: mysqli
server_version: 5.7.26
server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.39 (Win64) PHP/7.3.5
php_version: 7.3.5 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 120
memory_limit: 1024M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 16M
curl_version: 7.64.0 OpenSSL/1.1.1b


My Plugin List:
Advanced Custom Fields Multilingual: version: 1.5.0, author: OnTheGoSystems
Advanced Custom Fields PRO: version: 5.8.7, author: Elliot Condon
Custom Post Type UI: version: 1.7.2, author: WebDevStudios
Disable Comments: version: 1.10.2, author: Samir Shah
ETT Blocks: version: 1.0.0, author: ETT SPA
Gutenberg: version: 7.2.0, author: Gutenberg Team
Hummingbird: version: 2.2.2, author: WPMU DEV
Regenerate Thumbnails: version: 3.1.2, author: Alex Mills (Viper007Bond)
WPML Media: version: 2.5.5, author: OnTheGoSystems
WPML Multilingual CMS: version: 4.3.6, author: OnTheGoSystems
WPML String Translation: version: 3.0.6, author: OnTheGoSystems
WPML Translation Management: version: 2.9.4, author: OnTheGoSystems

**Comment by youknowriad** [comment]
This might be related to the nux deprecation cc @noisysocks

**Pull request merged**
