### PR TITLE
docs(env): escape pipes in table cells

### PR DESCRIPTION
**Pull request by simono**
See https://github.github.com/gfm/#example-200

## Description
Fixed pipes inside tables cells.

## How has this been tested?
Content is now displayed correctly on the GitHub page.

## Types of changes
Doc improvements.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Soean** [comment]
Will the escape be a problem, when we render it on https://developer.wordpress.org/block-editor/packages/packages-env/ ?

**Comment by simono** [comment]
> Will the escape be a problem, when we render it on https://developer.wordpress.org/block-editor/packages/packages-env/#wp-env-json ?

@Soean Can you give me a hint, how I can test this? I didn't found a way to generate the HTML docs.

**Review by noisysocks — APPROVED** [review]
Definitely looks better in GitHub. Thanks @simono! If it breaks wordpress.org then we should fix the parser that builds those docs pages.

**Comment by Soean** [comment]
@noisysocks Now the backslash is rendered in the handbook: https://developer.wordpress.org/block-editor/packages/packages-env/#wp-env-json

**Comment by simono** [comment]
@noisysocks @Soean Thanks for the merge. Let me know if I can help to fix the backslashes in the handbook.

**Comment by noisysocks** [comment]
I created a ticket for the parsing issue in Meta Trac: https://meta.trac.wordpress.org/ticket/5123

This is the plugin that parses the markdown, if you'd like to try your hand at writing a patch to fix the issue: https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown

**Pull request merged**
