### PR TITLE
Fix undefined drop-cap class

### PR DESCRIPTION
**Pull request by swissspidy**
Right now when adding a new text block, it gets a `drop-cap-undefined` class because `dropCap` is not defined in the block (instead of `drop-cap-false` I guess). If the drop cap toggle is turned on, there will be a `drop-cap-true` class. 

It makes more sense to only add a `drop-cap` class if it's enabled and don't do anything else otherwise. You can target non-drop-cap blocks using the `:not()` CSS selector already.

Plus, `drop-cap` is more readable than `drop-cap-false` and `drop-cap-true`.

### CODE REVIEW

**Comment by youknowriad** [comment]
Should this sync with the "drop cap" updates in #1418?

**Comment by swissspidy** [comment]
The drop cap changes in #1418 don't touch the same lines as this PR does.

If I rename the class to `has-drop-cap` in this PR, it could simply go in before the other (which seems to be still in the works).

**Comment by mtias** [comment]
Yes, let's update to `has-drop-cap`. Thanks for fixing.

**Review by youknowriad — APPROVED** [review]
👍 Ship it

**Pull request merged**
