### PR TITLE
[RNMobile][Embed Block] Fix loading glitch with resolver resolution approach

### PR DESCRIPTION
**Pull request by fluiddot**
Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4146

## Description

This PR reverts the changes introduced in #33574 for fixing a loading glitch, and applies a different approach using the `hasFinishedResolution` selector to determine if the embed preview is being fetched.

**NOTE:** These changes were motivated by the findings posted in [this comment](https://github.com/WordPress/gutenberg/pull/35674#issuecomment-947504628) after debugging deeper the issue.

## How has this been tested?

Follow the testing instructions from the reverted PR #33574 and verify that the original issue is not happening.

## Screenshots 
N/A

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by fluiddot** [comment]
I'd like to note that the original issue can also be reproduced in the web editor, although in this case, the glitch is almost unnoticeable (see attached video recorded at slowmo).

<details><summary>Click here to display the video</summary>

<video src=https://user-images.githubusercontent.com/14905380/138072881-e26ff9ad-4b02-4284-8d5a-e897982dc0e7.mp4>

</details>

On one frame (00:05), we can see that the embed is reporting that the content couldn't be embedded but in the next frame, the preview is loading.

Screenshot 2021-10-20 at 12 04 08

We might consider applying the same approach in the web version of the embed 🤔 .

**Review by jd-alexander — APPROVED** [review]
Thanks for this slick glitch fix @fluiddot 🥇 I was able to verify that the issue no longer occurs on iOS or Android. LGTM 🚢 

-------

For the web, I wasn't able to reproduce but I think that is because my internet connection is good so the preview appeared instantaneously. Is Network Link Conditioner something you utilize to throttle network speed?

**Comment by jd-alexander** [comment]
> I'd like to note that the original issue can also be reproduced in the web editor, although in this case, the glitch is almost unnoticeable (see attached video recorded at slowmo).
> 
> Click here to display the video
> On one frame (00:05), we can see that the embed is reporting that the content couldn't be embedded but in the next frame, the preview is loading.
> 
> Screenshot 2021-10-20 at 12 04 08
> 
> We might consider applying the same approach in the web version of the embed 🤔 .

I agree with applying this fix to the web as well 👍🏾

**Comment by fluiddot** [comment]
> For the web, I wasn't able to reproduce but I think that is because my internet connection is good so the preview appeared instantaneously. Is Network Link Conditioner something you utilize to throttle network speed?

Not sure if it would be easier to reproduce it by throttling the network speed, I haven't tested this approach. In my case what I did was to record a video and check frame by frame 😅 .

> I agree with applying this fix to the web as well 👍🏾

Ok, I'll open a new PR applying the fix to the web version 👍 .

**Comment by fluiddot** [comment]
@jd-alexander I've just opened the [GB-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4146), let me know if you could take a look at it, thanks 🙇 .

**Comment by jd-alexander** [comment]
> @jd-alexander I've just opened the [GB-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4146), let me know if you could take a look at it, thanks 🙇 .

Sure, will do!

**Pull request merged**
