### PR TITLE
[Mobile] EmptyList now uses `useEditorWrapperStyles` hook and removes `ReadableContentView`

### LINKED ISSUE #5618: Refactor BlockList component to improve performance and remove class component usage
The current implementation of the `BlockList` component is using a class component and has some areas that could benefit from optimization and refactoring. In order to improve the performance of the component and to remove the usage of class components, we should consider the following changes:

- ~Update code to use functional components instead of class components.~ https://github.com/WordPress/gutenberg/pull/50293
- Revisit the usage of the `getStyles` function. Is it still necessary? What is it doing currently for the whole list if it's used in a block-level? Maybe move it somewhere else.
- Revisit `contentContainerStyle` and its calculations. Are there ways to optimize these calculations to improve performance?
- Revisit margin calculations. Are there ways to optimize these calculations to improve performance?
- Refactor the `EmptyListComponent` component. Can we optimize its rendering or use it differently? Especially if we are removing `ReadableContentView` in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/5614.
- Make sure the performance is as expected using the optimization approaches for FlatList and React Native in general.

Overall, we should aim to improve the performance and maintainability of the `BlockList` component while removing the usage of class components. This will ensure that the component is optimized for performance and can be easily maintained in the future.

### PR DESCRIPTION
**Pull request by geriux**
Closes https://github.com/wordpress-mobile/gutenberg-mobile/issues/5618

**Related PRs:**
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/5764

## What?
Follow up of https://github.com/WordPress/gutenberg/pull/50447 it updates the last component pending to use the `useEditorWrapperStyles` hook.

## Why?
The `EmptyList` component in the BlockList was still using the `ReadableContentView` component.

## How?
By updating the component to use the `useEditorWrapperStyles` hook. It also removes the `ReadableContentView` component from the codebase.

## Testing Instructions

- Open the editor
- Add a Group block
- Check the appender shows correctly
- Change the orientation to landscape
- Change the alignment of the block to full-width
- **Expect** the appender to adjust to the new block's width size.

### Testing Instructions for Keyboard
N/A

## Screenshots or screencast 
Portrait | Lanscape (Full-width alignment)
-|-
<kbd></kbd> | <kbd></kbd>

### CODE REVIEW

**Review by dcalhoun — APPROVED** [review]
Looks good! 🚀 

I verified the test plan succeeded on an iPhone 14 Pro simulator and Google Pixel 3 XL emulator.

**Comment by dcalhoun** [comment]
I imagine it likely makes sense to first merge https://github.com/WordPress/gutenberg/pull/50447 and then update this to target the `trunk` branch.

**Comment by geriux** [comment]
> I imagine it likely makes sense to first merge #50447 and then update this to target the `trunk` branch.

Exactly, let's do that 👍

**Comment by dcalhoun** [comment]
@geriux https://github.com/WordPress/gutenberg/pull/50447 is now merged. 🚀

**Pull request merged**
