### PR TITLE
Try making the hover state of nested blocks more visible

### PR DESCRIPTION
**Pull request by kjellr**
Following up from #14961.

Currently, when you hover over the new dashed borders for nested blocks, nothing happens: 

old

In the original PR, we briefly discussed [improving upon this by adopting a hover state](https://github.com/WordPress/gutenberg/pull/14961#issuecomment-495361430). This PR implements a similar hover state to the one proposed there, but it uses a `border-style` change instead, which I think is a little more visible than jus the color change. Still could use some iteration though: 

updated

**Todo:** 

- [ ] Make this work for an individual column block when its child is selected. Something's blocking that right now.
- [x] Build in styles for dark mode.

### CODE REVIEW

**Comment by kjellr** [comment]
I've adjusted the colors a little bit to make this a little smoother: 

hovers

Now, the all-around hover border color more closely matches the thick left border (and breadcrumb), which feels much more subtle and considered. 

In order to make this feel natural, I had to lighten the dashed border colors by a couple steps. This makes them a little less easier to see, but I think it still feels pretty solid overall.

**Review by karmatosed — APPROVED** [review]
I like this a lot, it's subtle enough to give me feedback but also feels not overwhelming. I do think testing this with some deep level nesting is important but getting it in seems sensible to me as a starting point.

**Comment by kjellr** [comment]
Thanks, @karmatosed! I've pushed a couple small fixes: 

- Dark mode styles, to match those already in place for the standard block borders.
- A fix that allows these hover states to show up in situations where nesting runs 3+ levels deep (like the columns block). 

Mind giving this one more look?

**Comment by mapk** [comment]
After just testing this, I believe it looks good! There's some subtle hover and click targeting that seems off a bit though. I imagine these issues are more about nesting than this specific PR, so I don't want to hold this one back b/c of them. But this is what I was experiencing.

nesting

**Comment by kjellr** [comment]
> I imagine these issues are more about nesting than this specific PR, so I don't want to hold this one back b/c of them. But this is what I was experiencing.

Yeah, I've seen that too. I think the block boundaries need to be fine-tuned a little bit, but that's probably a much more complicated problem. 😄

**Comment by karmatosed** [comment]
Works well for me with changes. I stand by we should iterate based on feedback of deeper nesting and I do also agree there is something weird going on about boundaries to fix in another issue.

**Pull request merged**
