### PR TITLE
Update icons for Paragraph, Heading and Subheading for clarity

### PR DESCRIPTION
**Pull request by jasmussen**
This PR changes the Paragraph heading to an outline version of the paragraph symbol. This is done to fix the confusion where the text-icon looks confusing next to alignments: https://mobile.twitter.com/webmatros/status/1030816482614235137

By using the Paragraph icon, it shows what the block is.

This PR also adds new icons for Heading and Subheading, a capital H and smallcap italic H respectively. This is inspired by the same reasons as the "P for Paragraph" argument, H for Heading. Subheading was changed additionally because its previous visual language could also be confused with alignments.

screen shot 2018-08-20 at 09 58 35

Edit: Don't mind the icon that says "Broken" — this was me testing a shared block to try and break something ;)

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
I like it. 👍🏻

**Comment by mtias** [comment]
Nice, thanks for addressing.

I do have concerns with "H" as it doesn't make a lot of sense in most languages and I feel it's too English centric (I know this also corresponds to the HTML tag). It's one where it'd be nice to have localized icons. I do think the "T" works a bit better as the latin root is at least a bit more common across more languages.

**Comment by tofumatt** [comment]
Oh, shoot, that’s a good point. I didn’t even think of that, sorry.

- Matt (Sent from mobile)

**Comment by jasmussen** [comment]
@tofumatt Don't worry about it, it's good to move fast. Also, I have it fixed in https://github.com/WordPress/gutenberg/commit/ef8070390f5372f207d08ab87bff908a53a4e69e :)

**Pull request merged**
