### PR TITLE
Add scroll on sidebar

### PR DESCRIPTION
**Pull request by jasonagnew**
Possible solution to allow scrolling on the sidebar #1373

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, thank you!

I was curious why `overflow: auto;` wasn't sufficient. Turns out in https://github.com/WordPress/gutenberg/blob/master/components/panel/style.scss#L24, we have a negative 1px right margin (presumably to hide the nested border). It goes deeper than that, as it seems every panel in the sidebar has a left and right border, and therefore negative left and right margins to hide those borders. These negative margins are causing the horizontal scrollbar. 

@youknowriad I think you worked on these files, any reason why we can't just replace the negative left/right margins and full border on every `component-panel`with `border-top: 1px solid $light-gray-500;` and `border-bottom: 1px solid $light-gray-500;`? That way we could just use `overflow: auto;`

**Comment by youknowriad** [comment]
@jasmussen I'm not certain exactly. We had a lot of discussion in the PR about these. I think the idea was to allow the `PanelBody` to be used separately from the `Panel` but maybe this is not really needed.

**Comment by jasmussen** [comment]
> @jasmussen I'm not certain exactly. We had a lot of discussion in the PR about these. I think the idea was to allow the PanelBody to be used separately from the Panel but maybe this is not really needed.

Alternately we can let the panel component be born with a full border, but then override it for the sidebar. But we'd still need to remove the negative margins.

**Review by youknowriad — APPROVED** [review]
Thanks for working on this

**Pull request merged**
