### PR TITLE
CoverImage: add text formatting.

### LINKED ISSUE #1492: CoverImage: text should have inline formatting toolbar
image

(Bold, italic, etc).

### PR DESCRIPTION
**Pull request by mtias**
image

Fixes #1492

### CODE REVIEW

**Comment by mtias** [comment]
@jasmussen tweaked the link-boundary background a bit in this context.

**Comment by jasmussen** [comment]
Looks good! 👍 👍

**Comment by iseulde** [comment]
Not a big fan of limiting formatting options. Similarly, we do still show italic on quote style 2. I wonder if styling `h* strong` to `font-weight: normal;` would help. Similarly `p em` to `font-style: normal;` for the quote.

**Comment by mtias** [comment]
It'd be cool to try.

**Comment by mtias** [comment]
image

@iseulde let's try it on this one and if we like it we can extend to headings.

**Pull request merged**
