### PR TITLE
Fix taxonomies flaky tests

### PR DESCRIPTION
**Pull request by JustinyAhin**
## Description

Fix for #35483.
The test fail was due to a wrong selector.

`.editor-post-taxonomies__hierarchical-terms-input input[type=text]` was used before. This will look for a text input inside the element with the class `.editor-post-taxonomies__hierarchical-terms-input`. While the input itself has this class name.

## How has this been tested?
Run `npm run test-e2e -- packages/e2e-tests/specs/editor/various/taxonomies.test.js` locally and check the changed test still passes.

Use `for i in {1..5}; do npm run test-e2e -- packages/e2e-tests/specs/editor/various/taxonomies.test.js; done` to run the test file 5 times for instance.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
The change here looks seems logical.

**Comment by JustinyAhin** [comment]
The new selector is not found https://github.com/WordPress/gutenberg/pull/35534/checks?check_run_id=3867770004#step:6:60 🤔

**Comment by Mamaduka** [comment]
Hi, @JustinyAhin

The sector should be correct. The `className` passed to a `TextControl` is applied to the wrapper div element, not the input.

P.S. I changed that selector in #33545.

**Comment by JustinyAhin** [comment]
> Hi, @JustinyAhin
> 
> The sector should be correct. The `className` passed to a `TextControl` is applied to the wrapper div element, not the input.
> 
> P.S. I changed that selector in #33545.

Hey @Mamaduka 

Here is what is currently outputted 
CleanShot 2021-10-12 at 11 06 25@2x

**Comment by Mamaduka** [comment]
Here is the markup I see on the current Gutenberg `trunk` build.

CleanShot 2021-10-12 at 13 15 31

Also, looking at the failure artifacts from the issue, it seems that the "Categories" panel isn't open, and I think that's the cause of the e2e test failure.

should be able to open the categories panel and create a new main category if the user has the right

**Comment by youknowriad** [comment]
It seems it's open but the categories are not loaded yet, maybe a missing waitForSelector somewhere?

**Comment by JustinyAhin** [comment]
> It seems it's open but the categories are not loaded yet, maybe a missing waitForSelector somewhere?

Yes, we could probably wait for `.editor-post-taxonomies__hierarchical-terms-list` after this line https://github.com/WordPress/gutenberg/blob/2078af7715a86c5d2a08c0ea3cf364a4f42ce5b4/packages/e2e-tests/specs/editor/various/taxonomies.test.js#L72?

**Comment by Mamaduka** [comment]
Most likely, this condition is true at the time test is trying to click on "Add new category."

https://github.com/WordPress/gutenberg/blob/2078af7715a86c5d2a08c0ea3cf364a4f42ce5b4/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L232-L234

I simulated this scenario and got the visually same result
CleanShot 2021-10-12 at 13 26 34

@JustinyAhin that check might help, so code waits a little more before `useSelect` is resolved.

**Comment by JustinyAhin** [comment]
@Mamaduka I think I might have one issue with my setup. I've just deleted my Gutenberg folder, clone and build again. But the input still have this class name: `.editor-post-taxonomies__hierarchical-terms-input`; not like in the screenshot you shared.

**Comment by Mamaduka** [comment]
@JustinyAhin, sorry, I know this sounds silly, but can you check if the Gutenberg plugin is active on the test setup?

It happened to me more than once 😅

**Comment by JustinyAhin** [comment]
> @JustinyAhin, sorry, I know this sounds silly, but can you check if the Gutenberg plugin is active on the test setup?
> 
> It happened to me more than once 😅

🤦🏻‍♂️🤦🏻‍♂️ oh it was that 😅
Thank you so much

**Comment by JustinyAhin** [comment]
> @JustinyAhin that check might help, so code waits a little more before `useSelect` is resolved.

@Mamaduka could you explain this a bit more for me please?

**Comment by Mamaduka** [comment]
@JustinyAhin it might take some time for `useSelect` to load (resolve) categories. As you mentioned, it might be a good idea to wait for the `.editor-post-taxonomies__hierarchical-terms-list` element.

**Comment by JustinyAhin** [comment]
@Mamaduka this is ready to go. Maybe you can look one last time? :)

**Review by Mamaduka — APPROVED** [review]
Thanks for the ping, @JustinyAhin. I think this looks good 👍

**Pull request merged**
