### PR TITLE
EditPostPreferencesModal: refactor to remove snapshots for index.js

### PR DESCRIPTION
**Pull request by ramonjd**
## What?
Every second or third run, I'm seeing the following errors in both local and CI JS unit tests

```console
FAIL packages/edit-post/src/components/preferences-modal/test/index.js (5.323 s)
  ● EditPostPreferencesModal › should match snapshot when the modal is active › large viewports

    expect(received).toMatchSnapshot()

    Snapshot name: `EditPostPreferencesModal should match snapshot when the modal is active large viewports 1`

    - Snapshot  - 0
    + Received  + 2
```

This PR already tried to fix this test:

- https://github.com/WordPress/gutenberg/pull/53814

Historical context: https://github.com/WordPress/gutenberg/pull/52133#issuecomment-1680399985

Instead of waiting around for aria-kit to add the tab-index attribute, this PR just gets rid of the relevant snapshot, and, rather, tests for main view elements to verify that the viewport switch is made. Thanks to @andrewserong for helping to debug

The snapshots seem to only test whether `useViewportMatch` renders the correct views. By testing for some key elements we don't need the entire snapshot.

There's also a strong argument to turn this into an E2E test, but for now, I'm just getting the tests to pass to unblock folks.

## How are you?
All good here, thanks!

## Testing Instructions
Check CI

`npm run test:unit packages/edit-post/src/components/preferences-modal/test/index.js` until you get sick of it

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Looks good to me! It might be worth confirming with @ntsekouras or others if there were any other reasons that snapshot tests were used for this component, over testing for the visibility of particular child components as in this PR. Personally, in general, I much prefer tests like in this PR, as it makes it clearer what's being tested for, and is less prone to fail due to side effects.

Since it sounds like this will help unblock things on `trunk`, this LGTM to merge, and we can always roll back if it turns out that the snapshots were needed for other aspects of the test coverage (or add additional tests for what needs to be covered).

Thanks for this!

**Review by jsnajdr — COMMENTED** [review]
Thank you for fixing this. My previous attempt to fix the snapshot has failed, and it would be exceedingly difficult to make it really right. Testing for specific elements or behavior is better than a summary snapshot.

**Comment by andrewserong** [comment]
Thanks for confirming, Jarda!

**Comment by ntsekouras** [comment]
>It might be worth confirming with @ntsekouras or others if there were any other reasons that snapshot tests were used for this component, over testing for the visibility of particular child components as in this PR

No specific reasons.. These tests look fine, thank you for handling that!

**Comment by ramonjd** [comment]
Thanks for double-checking everyone! 🙇🏻

**Comment by Mamaduka** [comment]
I've noticed [similar failures](https://github.com/WordPress/gutenberg/actions/runs/6052658823/job/16426570034?pr=54119#step:5:44291) (Modal or Popover related) with `packages/nux/src/components/dot-tip/test/index.js`.

**Comment by ramonjd** [comment]
> I've noticed similar failures (Modal or Popover related)

I saw those too. The opacity changes on the inline styles. I wasn't sure if it was related to the aria-kit changes or not, but maybe there's scope to remove the snapshot there too.

**Comment by ramonjd** [comment]
@Mamaduka I have a PR up to fix that test:

- https://github.com/WordPress/gutenberg/pull/54168

**Pull request merged**
