### PR TITLE
Block library: migrate Classic Blocks to HTML Blocks

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Any classic blocks are now converted to proper HTML blocks on load. As discussed with @azaozz, we don't really want them to stay freeform, so this seems like a better approach than passing the HTML block to the freeform handler. I also changed it so that if there's only freeform (old) content, we don't convert it to an HTML block for now. Maybe we can refine that experience in a separate PR: show a modal to ask to convert to blocks.

But with this PR, we can already start to prevent TinyMCE from loading if there are is no freeform blocks. This PR prevents people from adding any new Classic blocks.

This also removes the problem of loading TinyMCE in an iframed editor.

## Why?

This block was helpful at the early stages of Gutenberg, but it should no longer be used.

### CODE REVIEW

**Comment by azaozz** [comment]
Think this is looking very good! 

One place that can probably be better is to add the modal with "Convert to blocks" when the whole post is plain HTML. Perhaps the big chunk of HTML looks a bit "scary" at the moment:

Screen-Shot

Would be quite better imho with a modal that shows preview of the converted post, and has a nice "Convert to blocks" button with big friendly letters :) 

Then, if the user selects to Cancel, perhaps can look at offering to load TinyMCE? Thinking a canonical/core plugin would be good enough for that. Can probably make an "Edit as classic block" button that will either load TinyMCE if the plugin is present, or open the Install plugin screen.

For under-the-hood this means everything related to "freeform" and "Classic block" can do now. Also perhaps everything related to loading TinyMCE in the block editor in core (PHP) can be moved to the canonical plugin, or keep the minimum and add filters.

**Comment by azaozz** [comment]
Related: https://github.com/WordPress/gutenberg/issues/34023, and perhaps https://github.com/WordPress/gutenberg/issues/33832 for possible changes to `freeformContentFallbackBlock`.

**Comment by ellatrix** [comment]
> One place that can probably be better is to add the modal with "Convert to blocks" when the whole post is plain HTML. Perhaps the big chunk of HTML looks a bit "scary" at the moment:

Yes, we should definitely do that if all the content is simply freeform. We could also offer a diff of the current and newly converted blocks side by side? Not sure if that would do more damage than good.

> Then, if the user selects to Cancel, perhaps can look at offering to load TinyMCE? Thinking a canonical/core plugin would be good enough for that. Can probably make an "Edit as classic block" button that will either load TinyMCE if the plugin is present, or open the Install plugin screen.

Yeah, maybe!

**Comment by azaozz** [comment]
> could also offer a diff of the current and newly converted blocks side by side?

For posts with "mixed content", i.e. some blocks and some loose (freeform) HTML in between? Been wondering how to preserve the current workflow(s) as there may still be use cases for this type of posts. 

Do you think it would be good to add a param to the HTML blocks when they were auto-created as a result of loose HTML? Such param then can be used to make the "Convert to blocks" button more prominent (as in this patch), and also by the canonical plugin (if we decide to make it, see above) to offer to load TinyMCE for editing them? This will be quite close to the current Classic block workflow but will load TinyMCE on demand and "as needed" (as a second choice added from a plugin). 

>  Not sure if that would do more damage than good (showing a diff/preview)

Yea, not sure either. Perhaps can experiment a bit with it after the modal for the HTML-only posts is in. Can even try to arrange for some user testing (need to find users that need these "mixed" posts).

**Comment by talldan** [comment]
The widget editors also use the HTML block. A couple of issues popped up:
- It causes the HTML block's delimiter attributes not to be saved as there is no delimiter for freeform blocks (https://github.com/WordPress/gutenberg/issues/35266). I don't think the core implementation of the block has any attributes like that, but plugins could add them.
- The autop issue @azaozz mentioned (https://github.com/WordPress/gutenberg/issues/33832), which was only resolved in the widget editors. It may be possible to apply the same fix to the post editor, not sure, I don't recall many of the details.

I personally feel like a separate non-classic freeform block might be a decent way to solve the problems, the first issue sounds quite difficult to resolve in any other way.

**Comment by skorasaurus** [comment]
When I first saw this PR by chance, I was initially (and irrationally) alarmed because we have probably a few dozen pages still stored as classic blocks (that were made in the TinyMCE editor and continued to be edited as 'classi'c blocks) because we have some technical debt (refactoring some CSS styling that would need to be writte; others things that I haven't thought of and shortcodes that haven't migrated into blocks) that still haven't been resolved. 

Once I read over the proposal and remembered that they will be HTML blocks; I was mostly relieved although while testing this out; I found a couple issues: 

I opened a page (previously consisted of one large classic block; it's also one of our most popular pages that receives 40k visits/year); its contents were automatically opened in an HTML block; when I went to update; I received the 'the editor has an unexpected error', the error contents are immediately below:

I received an error, below: 

```
em@https://local.wordpress.test/wp-content/plugins/gutenberg/build/components/index.min.js?ver=5263f223ea79420985a1:1:243391
Md@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:132545
Mp/<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:167185
Mp@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:168556
g@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:47901
Un@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:48226
qn@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:49187
Jm@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:216691
Nm@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:208394
Dm@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:208281
_m@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:208045
vm@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:206395
fs/<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:94002
unstable_runWithPriority@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:20757
us@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:93746
fs@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:93949
ds@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:93882
dm@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:203363
Pf@https://local.wordpress.test/wp-content/plugins/gutenberg/build/vendors/react-dom.js?ver=a7f0d591a8f246422ae15d7678f43fdc:1:142535
e@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:23519
t@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:23565
ae/h/t.subscribe/o<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:19096
ue/instantiate/b</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:17208
p@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:7125
ue/instantiate/c</</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:13814
i/</</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=a4f02cded081b94dc342:1:8959
F/</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:9390
x/</</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:10478
ue/instantiate/f</<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/data/index.min.js?ver=4b5186a369d36ea9f14f:1:14512
an/<@https://local.wordpress.test/wp-content/plugins/gutenberg/build/editor/index.min.js?ver=e86ba7ef1e5fcfe8ad72:1:43434

```
the console for said page also contained an additional error: 

```
Uncaught TypeError: b.useId is not a function
    em PresenceChild.mjs:9
    Md react-dom.js:1
    Mp react-dom.js:1
    Mp react-dom.js:1
    g react-dom.js:1
    Un react-dom.js:1
    qn react-dom.js:1
    Jm react-dom.js:1
    Nm react-dom.js:1
    Dm react-dom.js:1
    _m react-dom.js:1
    vm react-dom.js:1
    fs react-dom.js:1
    unstable_runWithPriority react.js:1
    us react-dom.js:1
    fs react-dom.js:1
    ds react-dom.js:1
    dm react-dom.js:1
    Pf react-dom.js:1
    e index.js:225
    t index.js:236
    o registry.js:222
    Redux 4
    F promise-middleware.js:20
    x resolvers-cache-middleware.js:57
    f Redux
    an actions.js:211

```

I appreciate your effort on this and I understand the need for deprecation but I think communicating the removal of the classic block is important and there may be many other users like me and this will need further testing before merging. 


Lastly, I had wp_debug on in my test environment and also had received the error 

`Warning: file_get_contents(/path/to/install/public_html/wp-content/plugins/gutenberg/lib/../build/block-library/blocks/freeform/block.json): failed to open stream: No such file or directory in /path/to/install/public_html/wp-content/plugins/gutenberg/lib/blocks.php on line 144
`

**Comment by azaozz** [comment]
> I personally feel like a separate non-classic freeform block might be a decent way to solve the problems

Yep, but that would just replace "freeform" with something else that will still have "special status" and be generally an exception. The idea here is to not have exceptions any more, i.e. a post edited in the block editor will only have blocks. Will make the workflow more consistent and 100% future-proof (and improve and simplify handling in the back-end) :) 

On the other hand thinking that having an attribute on the HTML block that signifies when loose HTML (freeform content) was auto-converted to it would be quite useful. Of course the first choice there would be to Convert to blocks. But keeping it as HTML block or even having the option to edit it with TinyMCE would be nice and will ensure parity with current workflows.

Thanks for linking the two issues. Yes, autop will have to go almost completely. The only time it makes sense to use it is when opening old posts for editing, or newer posts with loose HTML between the blocks. The removal of `<p>` should not happen any more at all (think there was an issue for that too).

**Comment by azaozz** [comment]
> Once I read over the proposal and remembered that they will be HTML blocks; I was mostly relieved although while testing this out; I found a couple issues

Thanks for testing! 

Yes, there are several issues. The current code is only to try to get the new workflows (and eventual UI changes) right. Once the special status of "freeform" is removed, and the loose HTML between blocks is treated as (standard) HTML blocks, all remaining issues will be resolved (there are at least four previously reported). For now please test with copies of posts or on staging, etc.

> I think communicating the removal of the classic block is important

Yes, definitely. Not there yet though, still need the "Convert to blocks" modal that shows a preview of the conversion when opening an old HTML-only post. Also perhaps to get the companion "Edit with TInyMCE" canonical plugin started (if we go that way), etc.

**Comment by ellatrix** [comment]
@skorasaurus the useId error is some problem right now in trunk after the upgrade to React 18. It's not related to the Classic Block.

**Comment by ellatrix** [comment]
> Lastly, I had wp_debug on in my test environment and also had received the error

Yes, we'll probably need to be a bit more conservative in removing the actual code and block. I'll change this PR so we leave the classic block in place, but "upgrade" it to an HTML block on load, similar to what we did for the list/quote block version upgrade.

**Comment by ellatrix** [comment]
I changed it so that any classic blocks are now converted to proper HTML blocks on load. As discussed with @azaozz, we don't really want them to stay freeform, so this seems like a better approach. I also changed it so that if there's only freeform (old) content, we don't convert it to an HTML block for now. Maybe we can refine that experience in a separate PR: show a modal to ask to convert to blocks.

But with this PR, we can already start to prevent TinyMCE from loading if there are is no freeform blocks. This PR prevents people from adding any new Classic blocks.

**Comment by ellatrix** [comment]
I don't plan to work on this, so I'll close it for now. Feel free to take it and start and another PR if anyone is interested.

**Pull request closed without merging**
