### PR TITLE
Increase colour contrast on block mover buttons (#557)

### PR DESCRIPTION
**Pull request by njpanderson**
Have checked the new contrast meets WCAG AA using the following tool:

http://webaim.org/resources/contrastchecker/

If there’s a better checker you guys all use, do let me know in the comments!

### CODE REVIEW

**Comment by jasmussen** [comment]
This is what I see:

screen shot 2017-06-02 at 10 05 35

Nice, looks good, thanks for working on this!

I did notice that the dark gray hover color doesn't actually work —  it's replaced by a $medium-blue-500 color. Which frankly is probably better as it matches the hover color for similar buttons. So that hover rule can probably be removed. Otherwise 🚢

**Comment by njpanderson** [comment]
Have removed the redundant hover. This might be my smallest PR ever, now ;)

**Comment by jasmussen** [comment]
Not sure why travis failed on that one. But the change looks good now!

**Comment by njpanderson** [comment]
I don't know if you fixed something @jasmussen but it seems to be passing here now.

**Comment by jasmussen** [comment]
I guess the test ran again. Ship it!

**Pull request merged**
