### PR TITLE
Update the site hub to show the page title and the template title

### PR DESCRIPTION
**Pull request by youknowriad**
Related #36667

## What?

This PR updates the site hub to show the "page title" and "template title" instead of the "template title" and "template type" per suggestion from @jameskoster 

## Testing Instructions

1- Open the site editor
2- Navigate it and check how the content of the site hub changes.

### CODE REVIEW

**Comment by youknowriad** [comment]
My personal feeling is that it's:

 - Too early for this PR since at the moment, the case where the page is "filled" in the site editor is rare.
 - I feel it's a bit weird to not know what type of entity we're showing.

That said, I'm happy to disagree and commit.

**Comment by jameskoster** [comment]
Thank you for putting this together, it's working as advertised:

Screenshot 2023-01-13 at 17 39 21

> Too early for this PR since at the moment, the case where the page is "filled" in the site editor is rare.

It's true, this is a forward thinking change based on the idea that the general site editing experience will be more "content first" when we add other features like browse-aility. 

Still, if we delay the change then we risk frustrating folks by changing the behaviour of a fairly critical element in the UX down the road.

> I feel it's a bit weird to not know what type of entity we're showing.

Do you mean whether it's a template or a template _part_? I'm not too worried about that because (imo) the frame contents makes it clear enough, e.g:

Screenshot 2023-01-13 at 17 50 43

Though it's worth noting the frame height should wrap the template part height. I'm sure we had that before, so perhaps this was a regression from another change 🤔 

The only thing I'm not sure about is whether or not to display the site title when there's no item of reference:

| No site title | Site title |
| --- | --- |
| Screenshot 2023-01-13 at 17 58 39 | Screenshot 2023-01-13 at 17 57 44 |



Keen to get the thoughts of @WordPress/gutenberg-design here.

**Comment by richtabor** [comment]
> The only thing I'm not sure about is whether or not to display the site title when there's no item of reference:

I think so yes.

**Comment by jameskoster** [comment]
> I feel it's a bit weird to not know what type of entity we're showing.

I still don't consider this a blocker personally, but I explored it a bit more anyway. None of these designs feel right, but sharing in case they inspire:

### Text label
Screenshot 2023-01-16 at 11 40 34

This feels too noisy, and we'd run into issues with long titles / localisation

### Icons
Screenshot 2023-01-16 at 11 41 48

I'm not keen on the small icons which break the existing sizing convention, but I already had to increase the general dimensions to make this work visually so would consider this a maximum. Also not entirely sure the icons are intuitive enough... they're ok for delineating templates from template parts, but posts from pages? This approach could also get tricky with duplicate taxonomy names for different post types, and custom post types in general. 

### Tooltips
Screenshot 2023-01-16 at 11 44 42

I suppose this could be a low-risk short-term solution. But it might interfere with interactions we want to add to the site hub in the future (e.g. Invoking a global search, viewing the frontend, etc).

As I said, none of these feel right. Imo we can merge this, and address this detail in a follow-up if/when the need arises.

**Comment by youknowriad** [comment]
Ok how should we proceed here? Merge? Add the site title when there's no "content"?

**Comment by jasmussen** [comment]
I'd avoid icons for the time being. I also tend to lean towards https://github.com/WordPress/gutenberg/pull/47140#issuecomment-1381555904 that we might want to pause this PR until we're a bit further with the role of the site hub. Something like figuring out where the global save button exists, that seems a tough nut to crack on its own, and might inform what we show as far as titles. Not a strong opinion.

**Comment by youknowriad** [comment]
Closing this as the design has evolved already.

**Pull request closed without merging**
