### PR TITLE
E2E Tests: Try running in Firefox (in addition to Chrome)

### PR DESCRIPTION
**Pull request by ockham**
## Description
First stab at running e2e tests in Firefox, when run in CI.

Sometimes we see errors that only manifest in Firefox, such as the issue that was fixed by https://github.com/WordPress/gutenberg/pull/28212. In order to catch those earlier, it makes sense to add Firefox coverage to our automated tests.

Inspired by https://github.com/Automattic/jetpack/pull/17893 (which I haven't gotten to work yet :grimacing:)

## How has this been tested?
See if the e2e tests GH Actions pass :crossed_fingers: 

To run locally (with tests visible):

```
npm run test-e2e -- --puppeteer-interactive --puppeteer-product=firefox
```

### CODE REVIEW

**Comment by ockham** [comment]
Aah, we're using `puppeteer-core` (which doesn't download any browsers) rather than `puppeteer` itself...

**Comment by gziolo** [comment]
> Aah, we're using `puppeteer-core` (which doesn't download any browsers) rather than `puppeteer` itself...

Yes, we don't want everyone to download 150-ish MB hoping they run e2e tests locally for every PR 😅

**Comment by Mamaduka** [comment]
I think this would be easier after the Playwright migration is finished. See #38851.

**Comment by kevin940726** [comment]
This is now possible after https://github.com/WordPress/gutenberg/pull/44631 in Playwright. Should we close this now?

**Pull request closed without merging**
