### PR TITLE
GalleryBlock: place edit button in separate toolbar.

### LINKED ISSUE #1129: Gallery: Improve the "edit gallery" button
Current state:

current

That button on the left opens the gallery so you can edit it. 

Let's make this a separate button, with an edit icon:

button

(the right most one here)

### PR DESCRIPTION
**Pull request by mtias**
image

Fixes #1129.

@jasmussen do you want to add the proper icon?

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice!

Like @njpanderson, we should use the edit icon here. That's what the current gallery uses also.

**Comment by jasmussen** [comment]
I dig it! Works well. 👍

**Comment by aduth** [comment]
Two things:

- We created [`BlockControls`](https://github.com/WordPress/gutenberg/blob/master/blocks/block-controls/index.js) (and later similarly [`InspectorControls`](https://github.com/WordPress/gutenberg/blob/master/blocks/inspector-controls/index.js)) as abstractions to obscure the underlying fill behavior and naming. We should decide whether this is a pattern we want to embrace and apply it consistently.
- On the point of consistency, while perhaps out of scope of this pull request, seems we should move all controls to be rendered as descendants of the `edit` component.

**Comment by youknowriad** [comment]
> On the point of consistency, while perhaps out of scope of this pull request, seems we should move all controls to be rendered as descendants of the edit component.

Agree, That was my intention after merging #1019

**Comment by paaljoachim** [comment]
This is really picky but I feel there is too much space between the icons in the toolbar:
toolbar

Here is one that shows the two groups closer together.

toolbar

**Pull request merged**
