### PR TITLE
Update the audio and video blocks to use a light wrapper in the editor

### PR DESCRIPTION
**Pull request by youknowriad**
Everything is in the title.

**Testing instructions**

 - Make sure the video/audio blocks work properly in the editor.

### CODE REVIEW

**Review by ZebulanStanphill — APPROVED** [review]
Everything seems to work the same as `master`. Test failures appear to be intermittent.

**Comment by ellatrix** [comment]
Do the alignments work fine? Somehow I thought we'd be blocked by the alignment work, but I guess your recent PR fixed that. :)

**Comment by ZebulanStanphill** [comment]
@ellatrix Some things are definitely broken (e.g. left/right-floating videos), but they're already broken the same way in `master`, so this PR doesn't make anything worse as far as I can tell.

**Comment by youknowriad** [comment]
Yes, the recent alignments PR allows us to refactor all blocks that rely on  the "align" hook (and were blocked).

**Comment by apeatling** [comment]
@youknowriad This change means that wrapping core blocks with custom notices becomes much harder. You can see the issue reported here: https://github.com/Automattic/jetpack/issues/15796

We used the classname to filter on the core video block, but with the new light block wrapper it's not possible to include the notice within the block, so it disconnects. Is there a way that you know of where we can achieve the same result with this new light wrapper?

**Comment by youknowriad** [comment]
@apeatling Oh, sorry for the breakage Andy. 

> We used the classname to filter on the core video block

Can you clarify a bit how this className was used, AFAIK, we didn't remove classNames in this change, but we removed "markup".

---

Unfortunately, the update here is a fundamental piece in Gutenberg and not something we'd like to reconsider. The idea is that the editor markup should be as close as possible to the frontend without superfluous markup added by the editor. 

When using the new approach we did want to "enhance" the markup ourselves with controls like the "block toolbar", but in these situations, we're not embedding markup anymore. What we do instead is use a "Popover" rendered outside the block list and "anchor it" above the block wrapper element. Maybe that's an approach that can be used by  Jetpack too.

**Comment by apeatling** [comment]
> Can you clarify a bit how this className was used, AFAIK, we didn't remove classNames in this change, but we removed "markup".

We were using the className passed in props of the `editor.MediaPlaceholder` to filter the media placeholder on the video block: https://github.com/Automattic/jetpack/blob/master/extensions/blocks/videopress/editor.js#L27

Granted this is not what it was designed for, just noting that it's not available here anymore. :)

Totally agree with the direction of this change, and keeping editor markup as close to the frontend as possible. We've reverted this specific change on dotcom, and I'll have a look at the new Popover approach and see where we can adjust our setup. Thanks!

**Comment by ockham** [comment]
> > Can you clarify a bit how this className was used, AFAIK, we didn't remove classNames in this change, but we removed "markup".
> 
> We were using the className passed in props of the `editor.MediaPlaceholder` filter to replace the media placeholder on the video block: https://github.com/Automattic/jetpack/blob/master/extensions/blocks/videopress/editor.js#L27
> 
> Granted this is not what it was designed for, just noting that it's not available here anymore. :)

@youknowriad Could this be considered an (indadvertent) API change? I just looked into this aspect of the issue, and without the `className` passed, it's basically impossible now to tell from inside the `editor.MediaPlaceholder` which block we're dealing with. I can replace the media placeholder for all blocks that upload videos, but that would be too wide a net to cast...

**Comment by youknowriad** [comment]
I don't think that className was ever meant to be used this way. I'm pretty sure you can get the block name using `useBlockEditContext` API

**Comment by ockham** [comment]
> I don't think that className was ever meant to be used this way. I'm pretty sure you can get the block name using `useBlockEditContext` API

Ah that's great, thanks! Wasn't aware of that :smile:

**Comment by retrofox** [comment]
> The idea is that the editor markup should be as close as possible to the frontend without superfluous markup added by the editor.

does it mean if we try to extend the block edit function... all markup generated by the components added will be rendered outside of the block markup?

```es6
const { createHigherOrderComponent } = wp.compose;
 
const withSomething =  createHigherOrderComponent( ( BlockEdit ) => {
    return ( props ) => {
        return (
            <>
                <MyCustomComponent />
                <BlockEdit { ...props } />
            </>
        );
    };
}, "withInspectorControl" );
 
wp.hooks.addFilter( 'editor.BlockEdit', 'my-plugin/with-inspector-controls', withSomething );
```

Nice idea, btw.

**Pull request merged**
