### PR TITLE
Reorganize e2e tests folders and files

### PR DESCRIPTION
**Pull request by youknowriad**
This PR doesn't change much aside moving files around in e2e-tests package:

 - Move non-experimental stuff out of the "experimental" folder.
 - Move site editor into its own top level folder.
 - Only keep the navigation screen in the "experimental" folder.
 - Separate the site editor utils from the enabled of the different Gutenberg experimental features.

This organization helps us run Gutenberg e2e tests from these stable folders against Core Trunk. I'm adding the backport label for this reason.

### CODE REVIEW

**Comment by Mamaduka** [comment]
@youknowriad, should we move shared utils into the `e2e-test-utils` package? It should fix current e2e test failures on this branch.

I'm also not sure why test runner picks files without the `.test.js` suffix.

**Comment by youknowriad** [comment]
> should we move shared utils into the e2e-test-utils package?

Yeah I thought about this but wanted to keep this small. Another option would be to move them to the root folder (where they were) or update the test matcher like you suggest (`*.test.js`)

**Review by Mamaduka — APPROVED** [review]
Thanks, Riad.

Changes look good to me, and I agree that updating the test matcher is the right decision here.

**Comment by youknowriad** [comment]
Looks like there's still a failure that I need to debug :)

**Pull request merged**
