### PR TITLE
Prevent Single Panel in Block Switcher from being Collapsed

### LINKED ISSUE #9522: Why can you collapse the Block Switcher?
I'm unsure if this is a bug, or if the option serves a purpose I am not seeing. 

When switching blocks, there's an option to collapse the pop-up. With it collapsed, it doesn't really seem to serve a true purpose, and might just be something that got overlooked. 

why-is-this-here

### PR DESCRIPTION
**Pull request by milesdelliott**
## Description
Fixes:https://github.com/WordPress/gutenberg/issues/9522
If there is only a single panel body in the block switcher (Only transformation or only styles) the panel body will be forced open

## How has this been tested?
No errors when running npm test
Manually tested with some dummy components that have various combinations of having and not having transformations and styles
Node version 8.12.0
NPM version 6.4.1

## Types of changes
Bug fix (addresses #9522)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Does this actually prevent the toggle button from appearing as a toggle button? Or does it just force it to remain open? If the latter, wouldn't there be potential for confusion in that it appears collapsible?

**Comment by aduth** [comment]
It does seem separate, though definitely related and perpetuated by the changes proposed here.

I don't feel strongly whether it be addressed separately or here. It seems like it should be simple enough to infer the forced value by presence in props (`props.hasOwnProperty( 'opened' )`) to vary the render result accordingly.

**Comment by milesdelliott** [comment]
Yeah, I have working code to detect whether or not the prop is there, but I didn't want to start jumping into rewriting the component without input from others.

**Comment by gziolo** [comment]
@milesdelliott - what's the status of this one?

I see two issues referenced #9889 and #9522. Does it target both or only the one mentioned in the description?

**Comment by rodrigoi** [comment]
@milesdelliott this looks good, but needs a rebase since some variable names have changed (like `hasStyles` -> `hasBlockStyles`) and the file has conflicts.

**Comment by gziolo** [comment]
@milesdelliott thank you for working on this one. This PR is outdated and needs to be refreshed as mentioned in the previous comments. I'm closing this one to let others fix this issue. Feel free to reopen when you find some time to look at it again.

**Pull request closed without merging**
