### PR TITLE
Extract Embed Block template code to a package.

### LINKED ISSUE #13490: Expose embed block creation function
**Is your feature request related to a problem? Please describe.**
I would like a way to register new embed blocks simply via a public API. Currently, the only way to create a new embed seems to be replicating all related core code.

**Describe the solution you'd like**
I would like to see the function [`getEmbedBlockSettings`](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/embed/settings.js#L40) exported to a public API.

**Describe alternatives you've considered**
As mentioned, so far the alternatives would be to replicate all functionality in `getEmbedBlockSettings` and `getEmbedEditComponent`, along with all dependencies. This would be very inefficient and not inherit any Core improvements automatically, requiring maintenance.

### PR DESCRIPTION
**Pull request by pento**
## Description

Fixes #13490.

This PR extracts the common code used by Core's embed blocks into a new `@wordpress/embed-block` package, allowing plugins to make use of this simpler method for creating embed-style blocks.

## How has this been tested?

Automattic/jetpack#14648 is an experiment in making use of this new package.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [ ] I've included developer documentation if appropriate.
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by pento** [comment]
This is currently a first pass, but I'd appreciate some early feedback on the direction. 🙂

**Review by gziolo — COMMENTED** [review]
This is a very interesting idea to move all common code related to embeds to its own package. In fact, there is some prior-art for media utils. See [@wordpress/media-utils](https://github.com/WordPress/gutenberg/tree/master/packages/media-utils) package introduced by @jorgefilipecosta. It's definitely a good direction if we want to make it easier to build custom embeds.

The biggest challenge is how to ensure that only essential APIs are exposed from this package and are well documented. In particular `utils.js` files, it seems like it shouldn't be part of the public API.

**Comment by pento** [comment]
> The biggest challenge is how to ensure that only essential APIs are exposed from this package and are well documented. In particular `utils.js` files, it seems like it shouldn't be part of the public API.

I agree, this will need auditing. I just went with `export *` while hacking it together to get it working. 🙂

**Comment by pento** [comment]
I have some time to push this forward again, so I've updated the PR, and created a sample use: Automattic/jetpack#14648

@gziolo Do you have more thoughts on the viability of this approach?

**Comment by gziolo** [comment]
@mcsf, did you have a chance to look at embeds and how they could possibly be refactored to sue variations? Still, it might be necessary to expose some components as proposed in this PR.

**Comment by mcsf** [comment]
> @mcsf, did you have a chance to look at embeds and how they could possibly be refactored to sue variations? Still, it might be necessary to expose some components as proposed in this PR.

_(Oops, I missed this ping due to some AFK time.)_

I looked at embeds very experimentally as a prelude to the work on Social Icons, which was more pressing. I still think it's fairly feasible to turn Embeds into variations of a single block type. @pento, if you're interested in this, I can cc you in that task so we can figure out what makes most sense to extract from `block-library`.

**Comment by mcsf** [comment]
@gziolo: looking at embeds, it becomes clear that we need slash-inserter support for variations.

**Comment by gziolo** [comment]
> @gziolo: looking at embeds, it becomes clear that we need slash-inserter support for variations.

I'm putting it on my todo list 👍

**Comment by pento** [comment]
@mcsf: I don't know that I'll have wild amounts of time to devote to this, but if you can give me some more details on what needs to be done, I'll see what I can wrangle.

**Comment by mcsf** [comment]
> @mcsf: I don't know that I'll have wild amounts of time to devote to this, but if you can give me some more details on what needs to be done, I'll see what I can wrangle.

@pento: don't worry, I'll share a PR whenever I have something and it should become apparent what could be reused. Honestly, though, my wish is that we could, over the next quarter, greatly simplify the way that embeds work (and turning them into a variation would be a definite first step) so that there is actually very little that needs to be reused. I suspect that advances in React from the last year and half (cf. hooks) could help us untangle some design patterns in the embeds code base, too.

**Comment by pento** [comment]
Sounds like a plan, @mcsf. I'm going to close this PR out, then, and we'll pick it back up again when you've had a chance to explore the block variation idea.

**Pull request closed without merging**
