### PR TITLE
FormTokenField: Make it possible to add children

### PR DESCRIPTION
**Pull request by scruffian**
## Description
This makes it possible to add children to FormTokenField. There are cases where we want to use this component within a form and we'd like to add a button, but it's hard to do so. This PR will make it simpler

## How has this been tested?
Try adding a child component to FormTokenField

## Screenshots 
This adds a "test" paragraph
Screenshot 2020-01-15 at 16 13 29

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by aduth** [comment]
>There are cases where we want to use this component within a form and we'd like to add a button, but it's hard to do so.

Can you elaborate on these use-cases?

I think the screenshot as presented appears problematic, though I suppose that could be a result of it intending to be a contrived example. It seems problematic because it disassociates the help text from the field input. I think it's worth considering in how: (a) If this is the default behavior, then it sets up developers for failure (to easily introduce negative UX implications) and (b) Whether there might be a better way to abstract this if the intention is something more like "adding buttons alongside [the screenshot's "Embed" button]" (e.g. something like a `buttons` or `actions` prop, etc).

**Comment by aduth** [comment]
What does the "Embed" button do? Is it something like a `<button type="submit">` ?

If it were, then just like submit buttons in a form, I don't think it would make sense as embedded in the input itself. I could imagine a layout like the one in the screenshot, but I would view it more like a flex row of:

```
+---------------+----------+
| [Input]       | [Submit] |
| Help Text     |          |
+---------------+----------+
```

**Comment by scruffian** [comment]
This is the way we approached it in the OpenTable block:
https://github.com/Automattic/jetpack/blob/c433ab7ff6bf42c36a4a3c725009c93b0a183587/extensions/blocks/opentable/editor.scss

Now I look at it, it's not that much additional CSS. I guess we don't need this after all :)

**Comment by aduth** [comment]
I looked a little closer at how it's used in the OpenTable block (https://github.com/Automattic/jetpack/pull/14220). If I understand correctly, the field can also accept embed code, and the button would interpret the input value as embed code?

If that's the case, I think at that point it can't really be considered a token field. Or at least it's more of an overloaded field which can be used either for tokens, or for this custom code. Personally I might worry about the usability of this approach vs. separate inputs, but I think it would be fine to consider it as something different from a token field. It would be more of a custom implementation and not really a valid use-case for the scope of what this component is intending to support.

**Pull request closed without merging**
