### PR TITLE
Remove padding from Home Link block

### PR DESCRIPTION
**Pull request by ndiego**
## Description
No other link block in core includes padding, yet the Home Link block does. This forces theme developers to override this padding to ensure link consistency. Removing this default padding will improve implementation of the Navigation block. The current workaround it to use a Custom Link that manually directs to the site's homepage.

## How has this been tested?
Removing the offending CSS simply makes the Home Link block look like all other link blocks in the Navigation block.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by gwwar — APPROVED** [review]
Good catch, this test well for me. I think styles here diverged from navigation link and the navigation block, but https://github.com/WordPress/gutenberg/blob/4fdffac83552063c56a71f5c5dd96359c2a580be/packages/block-library/src/navigation/style.scss#L272-L274 should cover this.

cc @jasmussen

**Comment by gwwar** [comment]
Here's a video of that padding in action when a background color is set 

https://user-images.githubusercontent.com/1270189/125972330-d045f31e-56b2-4b14-8199-4da0d058a3dc.mp4

**Comment by gwwar** [comment]
Thanks for this one @ndiego !

**Comment by jasmussen** [comment]
Thanks for the PR, thanks for the ping! This specific problem speaks also to both issues #31879 and #33048, as both of those are about enabling global style control. #31878 hopefully also helps.

**Pull request merged**
