### PR TITLE
Fix: Script with glob option doesn't work on Windows

### PR DESCRIPTION
**Pull request by t-hamano**
Follow-up to #67708, #67829, #67833

## What?

I have found that scripts with the glob option, although they don't cause errors, don't actually delete the files on Windows OS.

## Why?

Perhaps single quotes have a special meaning in the Windows OS shell.

## How?

To eliminate these errors, I use escaped double quotes in all commands. ~~For the `fixtures:clean` script, I tried not to use regular expressions so that it would work on Windows OS.~~

## Testing Instructions

Note that the order in which files are displayed by the ls command may vary depending on your operating system.

### clean:package-types, clean:packages

```
npm run build:packages
ls packages/dataviews
```

print

```
build
build-module
build-style
build-types
build-wp
node_modules
src
build.js
CHANGELOG.md
package.json
README.md
tsconfig.json
tsconfig.tsbuildinfo
```

```
npm run clean:package-types
ls packages/dataviews
```

print

```
build
build-module
build-style
build-wp
node_modules
src
build.js
CHANGELOG.md
package.json
README.md
tsconfig.json
```

```
npm run clean:packages
ls packages/dataviews
```

print

```
node_modules
src
build.js
CHANGELOG.md
package.json
README.md
tsconfig.json
```

### fixtures:clean

```
- Windows: ls test/integration/fixtures/blocks | Select-Object -First 10
- Linux, Mac OS: ls test/integration/fixtures/blocks | head -n 10
```

print

```
core_buttons__simple__deprecated.html
core_buttons__simple__deprecated.json
core_buttons__simple__deprecated.parsed.json
core_buttons__simple__deprecated.serialized.html
core__4-invalid-starting-letter.html
core__4-invalid-starting-letter.json
core__4-invalid-starting-letter.parsed.json
core__4-invalid-starting-letter.serialized.html
core__archives.html
core__archives.json
```

```
npm run fixtures:clean
- Windows: ls test/integration/fixtures/blocks | Select-Object -First 10
- Linux, Mac OS: ls test/integration/fixtures/blocks | head -n 10
```

print

```
core_buttons__simple__deprecated.html
core__4-invalid-starting-letter.html
core__archives.html
core__archives__showPostCounts.html
core__audio.html
core__audio__deprecated-1.html
core__avatar.html
core__block.html
core__block__overrides.html
core__block__overrides__deprecated-1.html
```

### CODE REVIEW

**Comment by gziolo** [comment]
It's one of those moment where I appreciate the backward compatibility policy followed by WordPress 😄 

I'll give it a spin on macOS.

**Review by sirreal — APPROVED** [review]
This seems to work correctly for me, so if it works correctly on Windows I'm happy 🙂

**Comment by t-hamano** [comment]
Thanks for the review! I would like to merge this PR as it is working in my environment 👍

**Comment by gziolo** [comment]
I'm happy to test with `trunk` :)

**Comment by gziolo** [comment]
Everything works correctly on my end when using scripts that execute `rimraf` with globs. Again, I'm on macOS.

**Pull request merged**
