### PR TITLE
Release automation: try cherry-picking automation

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

The idea is to have a designated label `Backport to WP 6.6 Beta/RC` and once a PR against trunk is merged with that label, it automatically cherry-picks that PR into the right release branch, removes the label, and comments on the PR. It should also work if the label is applied after merge. If there is a conflict, it will comment on the PR to make a PR against the `wp/*` manually.

## Why?

Cherry-picking can be tedious, and it would be good to cherry-pick as soon as PRs are merged into trunk. That way conflicts can be detected and addressed early.

## How?

See the workflow for details in logic.

To see it in action, this is the latest version: https://github.com/WordPress/gutenberg/pull/62735#issuecomment-2182500147

Also, jobs will wait for the last one to finish so the checkout are always fresh.

image

## Testing Instructions

I will attempt to create two branches that are based on this one:
* [`wp/0.0`](https://github.com/WordPress/gutenberg/tree/wp/0.0), to test if PRs get cherry-picked.
* [`try/cherry-pick-automation-trunk`](https://github.com/WordPress/gutenberg/tree/try/cherry-pick-automation-trunk) to simulate trunk.

Then I will create a few PRs against `try/cherry-pick-automation-trunk` to test if they get cherry-picked:
* ✅ One applying the label before merge: #62731
* ✅ One applying the label after merge: https://github.com/WordPress/gutenberg/pull/62735#issuecomment-2182500147
* ✅ One with a conflict. It works: https://github.com/WordPress/gutenberg/pull/62724#issuecomment-2182323507

### CODE REVIEW

**Review by vcanales — APPROVED** [review]
LGTM. I like the requirement of creating PRs to the `wp/*` branch in order to merge changes that had caused conflicts.

**Comment by desrosj** [comment]
This is really neat! Thanks for this, @ellatrix.

I did make one small adjustment to the syntax for the versions of third-party actions to use in #62836. When possible we should use [full commit SHAs as an extra level of hardening to be safe](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions). The `actions/checkout` was also a few versions behind, but Dependabot took care of that for us.

**Comment by ellatrix** [comment]
Sounds good, thanks!

**Comment by gziolo** [comment]
This is awesome! One question, who decides about adding `Backport to WP 6.6 Beta/RC` label? On the technical level, the commit can always get reverted from the release branch if the release squad disagrees, so maybe it is not an issue at all.

**Comment by gziolo** [comment]
It could also get extended to backporting to the Gutenberg plugin release branches when there is a bug fix to land during RC or after the final release. At that point, we could delete the old [bin/cherry-pick.mjs](https://github.com/WordPress/gutenberg/blob/trunk/bin/cherry-pick.mjs) script crafted by @adamziel long time ago 😀

**Comment by ellatrix** [comment]
Yes, anyone who can add labels can add it. Th Editor Tech Leads should double check the commits before publishing packages, revert if they disagree with something. They would have to do this previously as well, but before cherry-picking. Tbh, I don't think it's a big deal, we should put trust in people and correct/ping if needed.

**Comment by gziolo** [comment]
> Tbh, I don't think it's a big deal, we should put trust in people and correct/ping if needed.

Agreed. I guess it was the experience in the WP 6.6 release cycle so it's best to repeat it in the future 👍🏻

**Pull request merged**
