### PR TITLE
Mobile Release v1.52.2

### PR DESCRIPTION
**Pull request by jd-alexander**
## Description
Release 1.52.2 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3494

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jd-alexander** [comment]
Quick question @fluiddot When the build isn't able to pass due to conflicts here, I have seen times in the past where we have created another PR to have the build pass there. Is that now a standard approach here?

**Comment by fluiddot** [comment]
> Quick question @fluiddot When the build isn't able to pass due to conflicts here, I have seen times in the past where we have created another PR to have the build pass there. Is that now a standard approach here?

We've done that in the past but I'm not sure if it's now a standard, in my opinion since the changes that this PR includes are already in `trunk` and the PR checks passed, I think it's not really necessary for approving it. In any case, once the GB-mobile release PR is merged, we would have to update this branch with `trunk` and will see if PR checks are 🟢 .

EDIT: For the [`1.52.1`](https://github.com/WordPress/gutenberg/pull/31609) we didn't do it.

**Comment by jd-alexander** [comment]
> We've done that in the past but I'm not sure if it's now a standard, in my opinion since the changes that this PR includes are already in trunk and the PR checks passed, I think it's not really necessary for approving it. In any case, once the GB-mobile release PR is merged, we would have to update this branch with trunk and will see if PR checks are 🟢 .

> EDIT: For the 1.52.1 we didn't do it.

Thanks for sharing. I will follow suit and avoid creating the additional PR.

**Review by fluiddot — COMMENTED** [review]
The file changes LGTM 🎊 !

I'll approve it once I finish the smoke testing.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 ! (approved via https://github.com/wordpress-mobile/gutenberg-mobile/pull/3494#pullrequestreview-658807433)

_Smoke test was done on iPhone 11 (iOS 14.2) and Samsung Galaxy S20 FE 5G (Android 10)._

**Pull request merged**
