### PR TITLE
Preformatted: Add spacing support

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Adds margin and padding to the preformatted text block.

## Why?

For consistency, to allow users to add padding to the block.

## Testing Instructions
Make sure that the active theme supports spacing, for example in theme.json.

Create a new posts or page.
Add a preformatted text block.
Confirm that there is a dimension panel, and that the padding and margin settings are available but not enabled by default.

Test the padding and margin settings in the block editor, Site Editor Styles sidebar (global styles) and front.
Adjust the padding and margin via theme.json and confirm that it is applied in the editors and front.

## Screenshots or screencast 

https://user-images.githubusercontent.com/7422055/223356862-c51995d6-e875-4388-9efe-d911dcd7c019.mov

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for continuing to adopt block supports @carolinan, appreciate it 👍 

This is pretty close to working well for me. Unfortunately, I hit similar issues to https://github.com/WordPress/gutenberg/pull/45107.

✅ Spacing supports are applied in the editor for individual blocks
✅ Margins for top-level individual blocks get applied on the frontend
❓ The box-sizing reset isn't applied on the frontend. Makes padding impact block width incorrectly.
✅ Theme.json/global styles set padding works (ignoring the box-sizing issue noted above)
❓ Theme.json/global styles set margins are only applied in the editor
❓ When nested in a Group block, horizontal margins restrict the available width for the Preformatted block, while vertical margins appear to push outside the block instead. This occurs on both the editor and frontend for me.

It feels like spacing supports alongside layout support are now a bit broken. It's very likely I'm just missing something obvious.  @tellthemachines or @andrewserong can you point us in the right direction to making this all behave?

**Comment by andrewserong** [comment]
> @tellthemachines or @andrewserong can you point us in the right direction to making this all behave?

Not sure if it helps, but there's an open issue in https://github.com/WordPress/gutenberg/issues/43404 for the problem with the specificity of layout margin rules and how they behave alongside margins set in theme.json/global styles. Unfortunately, it doesn't appear yet to have an obvious fix, as reducing the specificity of the base layout rules then causes issues with styles that are shipped with the core blocks.

Is the current behaviour any different to what was reported there?

In general, I think margin is a challenging block support to reason about since its rules are shared with layout, so it's good when we opt in to it, for it to be not-exposed-by-default, as in this PR.

**Comment by aaronrobertshaw** [comment]
Is it worth reducing the scope of this PR to just adding padding support, such that it can move forward while we wait for the fix for layout styles overriding margin?

**Comment by carolinan** [comment]
Sure, it is a small code change.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for dusting this one off @carolinan 👍 

While re-testing this PR I found a padding issue when the preformatted block has a background color. Global Styles and theme.json applied padding will work in the editor but the `.wp-block-preformatted.has-background` style overrides it on the frontend.

We might be able to get away here by wrapping the block's `has-background` style in `:where` to lower its specificity.

Also, given it's been a while, I believe the fix for the layout styles overriding margin supports was merged in https://github.com/WordPress/gutenberg/pull/47858.

It might be worth re-adding that given we have to make changes here anyway. What do you think?

**Comment by carolinan** [comment]
I did not double-check the margin on this block because I ran into issues with the margin on the comments pagination block https://github.com/WordPress/gutenberg/pull/43905#issuecomment-1504618224,

I will check it now.

**Comment by carolinan** [comment]
I think that the default padding should only be enforced when a background color is added, if the theme 
adds support for `add_theme_support( 'wp-block-styles' ); `?

https://github.com/WordPress/gutenberg/issues/30725

**Comment by carolinan** [comment]
Related: https://github.com/WordPress/gutenberg/pull/37356

**Comment by carolinan** [comment]
Using Twenty Twenty-Three.
When I enable the margin block support and adjust the blocks margin in the Styles sidebar, the following happens:

- Block editor: Only top and bottom margin works. Left and right margins are overwritten by:
```
.editor-styles-wrapper .block-editor-block-list__layout.is-root-container > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
	max-width: 650px;
	margin-left: auto !important;
	margin-right: auto !important;
}
```
- Front: None of the margins work:
```
body .is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
	max-width: var(--wp--style--global--content-size);
	margin-left: auto !important;
	margin-right: auto !important;
}

body .is-layout-constrained > * {
	margin-block-start: 0;
	margin-block-end: 0;
}
.wp-block-preformatted {
	margin-top: var(--wp--preset--spacing--50); // This is overwritten
	margin-right: var(--wp--preset--spacing--50);  // This is overwritten
	margin-bottom: var(--wp--preset--spacing--50);  // This is overwritten
	margin-left: var(--wp--preset--spacing--50);  // This is overwritten
}
```

**Review by aaronrobertshaw — COMMENTED** [review]
Thank you @carolinan for your effort and patience in working through the kinks in adopting spacing supports to blocks.

> I think that the default padding should only be enforced when a background color is added, if the theme adds support for add_theme_support( 'wp-block-styles' ); ?

That would be the ideal case. This is a breaking change as [noted](https://github.com/WordPress/gutenberg/issues/30725#issuecomment-1510963060) on the linked issue however, so I don't think we can relocate those styles in this PR. It needs a wider solution.

> When I enable the margin block support and adjust the blocks margin in the Styles sidebar, the following happens:
> 
> - Block editor: Only top and bottom margin works. Left and right margins are overwritten by:
> - Front: None of the margins work:

The interactions between layouts and margin styles get a bit confusing at times. To me, the current behaviour is mostly making sense. As a top-level block, I'd expect the left/right margins to be overridden as they are. 

For an individual block's styles, which are applied via inline styles, I would also expect those top/bottom margins to get applied. They do, and are consistent between the editor and frontend for me.

Screenshot 2023-05-22 at 2 35 49 pm



When applying a global styles margin for the Preformatted block type, I'd expect those to respect the bounds of a layout. So for a top-level block, the layout overrides the top margin of the first block and overrides the bottom margin for the last block. This is the behaviour I get when testing as well in both the editor and frontend.


https://github.com/WordPress/gutenberg/assets/60436221/1b1b740a-4207-4d97-98b4-dd737d8f4b4c


One scenario where I did find a discrepancy though was when nesting the block within a container using a flex layout e.g. Row or Stack blocks. In the editor, the margins are applied but overridden on the frontend.

| Editor | Frontend |
|---|---|
| Screenshot 2023-05-22 at 2 30 10 pm<p>`body .is-layout-flex > *`<br />vs<br />`.editor-styles-wrapper .wp-block-preformatted`</p>| Screenshot 2023-05-22 at 2 30 30 pm  <p>`body .is-layout-flex > *`<br />vs<br />`.wp-block-preformatted`</p> |




@tellthemachines or @andrewserong perhaps you could provide some insight on to what extent layouts should override margins?

**Comment by carolinan** [comment]
We need to try set aside our own knowledge. As a user, all that is known is that "the setting isn't doing what it says". They don't know anything about boundaries of the layout.

**Comment by andrewserong** [comment]
> @tellthemachines or @andrewserong perhaps you could provide some insight on to what extent layouts should override margins?

Thanks for the ping! From a quick skim of the layout rules, I think it might be to do with the `flex` (and `grid`) layouts outputting the margin override in `baseStyles` instead of `spacingStyles` (`spacingStyles` output is the one that recently had specificity reduced in https://github.com/WordPress/gutenberg/pull/47858). I can have a play swapping them over and see if that fixes it up.

**Comment by andrewserong** [comment]
> I can have a play swapping them over and see if that fixes it up.

I've opened a WIP PR over in #50825 — it appears to mostly work pretty well, but unfortunately has some conflicts styles that are included in `classic.css`. I'm not too sure what the best fix for that would be, but happy for any feedback on that if anyone has any ideas of what the desired approach should be 🤔

**Comment by tellthemachines** [comment]
> Front: None of the margins work:

With constrained layout this is no longer an issue since #47858. I notice your code snippet still shows the old rule (`body .is-layout-constrained > *`) so rebasing the branch should have solved that already, barring any caching issues.

The issue with flex rules and margins is a different one. It would be good to make sure what is the desired behaviour there; there's a bit more about it in #44736.

**Comment by carolinan** [comment]
I have placed two preformatted blocks in the block editor. 
Padding: works everywhere.
Margin:
The inline styles work everywhere.

Global styles:
In the editor and front:
The top margin of the first block does not work, **but this is as planned.**
The bottom margin of the second and last block does not work, **but this is as planned.** (The block appender can affect this test, so remove any trailing paragraphs)
Left and right margin does not work, it is always auto.

I think this is unblocked, or do we wait for the flex issue?

**Comment by tellthemachines** [comment]
> I think this is unblocked, or do we wait for the flex issue?

I don't think it's worth waiting for the flex issue, as it'll be fixed separately in #50825. In any case, it affects all blocks with margins, not specifically this one.

**Comment by carolinan** [comment]
If this is unblocked, can someone approve it? 😸

**Review by aaronrobertshaw — APPROVED** [review]
My apologies that this took so long to come back to, @carolinan 🙇 

I believe the spacing supports for this block are behaving as expected and https://github.com/WordPress/gutenberg/pull/50825 will take care of the remaining issues within flex containers.

As others have noted, I don't think the wait on https://github.com/WordPress/gutenberg/pull/50825 needs to block this PR any further.

**Pull request merged**
