### PR TITLE
[Block Library]Rename Query and QueryLoop blocks to QueryLoop and PostTemplate respectively

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Part of: https://github.com/WordPress/gutenberg/issues/30910

>Let's consider changing the names from "Query" and "Loop" to "Query Loop" and "Post Template" for more clarity.

This PR rename `Query` and `QueryLoop` blocks to `QueryLoop` and `PostTemplate` respectively.

## Notes
1. These two blocks will be shipped with 5.8 for the first time and if we decide on going through with this, these changes will need to be back ported asap.
2. By making this change it means that every block theme will need to update with the new blocks as they existing ones won't work as expected (invalid blocks).  
3. I have updated the block patterns to use `QueryLoop` and `unregister` the core `Query` patterns. If this lands we'll need to make the pattern changes and back port to core as well.
4. I had created a deprecated version of `Query` block but this is not needed right now as the block has been renamed, so I have deleted it in this PR.
5. Failing tests are mostly(haven't checked all them yet) about FSE tests that use a `tt1-blocks` version with the old block. This produces block invalidations and therefore `console.error` logs that make the tests fail. I'll look into this more but this must be done in coordination with the update of `tt1-block` theme and then update the version that GB tests are using. I have created a draft PR in `theme-experiments` repo here: https://github.com/WordPress/theme-experiments/pull/265

**Please test carefully and if you have some time it would be great to check about any missing strings that might be used for example in css class names or such details.** I think I've covered it all but lots of moving parts with renaming. Also be vigilant with the fact that the `Query` block has been renamed to `QueryLoop` so it might be a bit confusing to see the changes as `QueryLoop` was an existing block.

## Testing instructions
1. Insert `Query` block in a page/FSE and make changes in editor and view front-end as well.
2. Everything should work just as before.
3. Make sure the patterns work and the styles are the expected ones as before.

### CODE REVIEW

**Comment by carlomanf** [comment]
Why not just leave the code-level naming as it is, and update the user-facing naming? Most users will never see the code-level naming anyway.

**Comment by jameskoster** [comment]
Big +1 from me on making these block names (and descriptions – that can come later I suppose) more user-friendly. A couple of thoughts on the proposals here:

I'm not convinced that adding "Loop" to the Query block name really helps all that much. I acknowledge that if you're a WordPress developer then "Loop" aids recognition of the block purpose, but does it communicate that message more clearly than "Query" on its own? For the average user, "Query" and "Loop" are equally challenging, but since this is a more technical, template-centric block that might be ok? The key here will probably be getting the description right.

We should be mindful of using the "Template" label in a block name due to the fact that templates already exist as a different (and complex) feature. Anything that muddies the waters there probably isn't super helpful. That said I'm struggling to come up with a better suggestion :D Perhaps "Post" alone might work, if we describe its template-like nature in the description? Otherwise we're kind of scrambling around for "template" synonyms.

**Comment by ntsekouras** [comment]
>Why not just leave the code-level naming as it is, and update the user-facing naming? Most users will never see the code-level naming anyway.

That could be a way simpler option in terms of changes, but it would be inconsistent with all the other blocks and could definitely create confusion for the users that will see the code, like theme authors.

**Comment by priethor** [comment]
Great refactor @ntsekouras, everything seems to work as expected!

As far as the new names themselves, I'm on the same boat as @jameskoster. Moreover, I believe both blocks should have a similar name that lets users understand the inner block _belongs_ to the parent, similarly to `Columns` and `Column`; something along the lines of `QueryLoopTemplate` or `QueryLoopBody` if we want to avoid the word _Template_.

If I were to suggest a different naming approach, `Teasers` and `Teaser` come to mind, as I find it's a recognizable user-friendly name for this kind of content representation. Although the Query block is so powerful it can do much more than classic teasers, there can be variations for those specific representations.

**Comment by jameskoster** [comment]
Thinking about the UX relationship between the query block and its variations (like the Posts List – https://github.com/WordPress/gutenberg/issues/32268) I wonder if something like this might work:

Screenshot 2021-05-28 at 12 48 42

So when you insert the Posts block on its own, it behaves as a custom query with all the associated display options and filters, and simplified structure (no pagination). 

But when it is wrapped inside the Global Query block (which is only available when editing a template) then... you guessed it, it inherits the query from the URL. In this case the layout options remain and pagination can be added, but the filters are removed.

**Comment by ntsekouras** [comment]
>So when you insert the Posts block on its own, it behaves as a custom query with all the associated display options and filters, and simplified structure (no pagination).

@jameskoster That actually involves technical implications with innerBlocks and query context, and `Query` doesn't work that way. It's definitely out of scope of this PR.

**Comment by carlomanf** [comment]
> > Why not just leave the code-level naming as it is, and update the user-facing naming? Most users will never see the code-level naming anyway.
> 
> That could be a way simpler option in terms of changes, but it would be inconsistent with all the other blocks and could definitely create confusion for the users that will see the code, like theme authors.

Inconsistent with other blocks how? Isn't the whole idea of block variations to show a different name to the user from what's in the code? If there are going to be multiple variations with different names, then at least one will have to be mismatched with the code. Given that's unavoidable, you might as well avoid inflicting a breaking change after a months-long "outreach program" that has encouraged users to add this block to their sites. (I can't believe this actually has to be explained.)

**Comment by jameskoster** [comment]
I'm basically describing the Posts variation of the Query block which we have an issue for here: https://github.com/WordPress/gutenberg/issues/32268.

In terms of this PR, it would still just be a case of updating the names (and probably the icons). This feels like a good step in isolation, but it's really just one small part of a bigger puzzle. I'm trying think a little more holistically about the UX we want to create in #30910, and aim for that while working on these smaller pieces.

I totally appreciate the the underlying technicals that will connect all these things would need to happen separately.

**Comment by ntsekouras** [comment]
>Inconsistent with other blocks how? Isn't the whole idea of block variations to show a different name to the user from what's in the code? If there are going to be multiple variations with different names, then at least one will have to be mismatched with the code. Given that's unavoidable, you might as well avoid inflicting a breaking change after a months-long "outreach program" that has encouraged users to add this block to their sites. (I can't believe this actually has to be explained.)

As you can see this renaming is under discussion and not finalized. There might be no renaming at all depending on the feedback. This PR handles the 'bigger' approach and if go with the renaming and we end up changing just the `labels`, it will need a new PR with just a couple of code lines to change.

**Comment by mtias** [comment]
If we were doing a block name change we would likely add a case for handling the name, like we have done with other block renames without breaking anything.

That said, I think `wp:query` with a title "Query Loop" is fine. The inner template is the one that we should probably rename entirely with a fallback.

**Comment by ntsekouras** [comment]
>That said, I think wp:query with a title "Query Loop" is fine. The inner template is the one that we should probably rename entirely with a fallback.

I can make these changes to move this forward. So the final question is if we rename `QueryLoop` to `PostTemplate` as in this PR or something different.

**Comment by jameskoster** [comment]
I still think something simple like "Posts" can potentially work for both the Query Loop _and_ a Query variation for displaying posts.

If I insert a "Posts" block I see all the options to create my custom query like so:

Posts variation

But if I put a "Posts" block inside a Query block in the template editor then the options from before aren't available – they are inherited from the Query instead:

Template

In terms of UX, the result is the perception of a single block for displaying posts regardless of context (post editing or template editor). The posts can be specific, or inherited from the global query. This is of course based on the notion that the Query block itself is restricted to the template editor.

To reiterate, these are different blocks that use the same name and description. So I acknowledge we'd need to figure out things like how/when they appear in the inserter to avoid duplication. That seems relatively straight-forward though... the `query loop` should not appear in the Inserter unless the cursor is inside a Query. Likewise if the cursor is inside a Query then the `posts` variation shouldn't appear. Hopefully the developer experience would be ok as well... I can't imagine theme developers making the mistake of inserting a posts variation of the query block inside another query block...

---

Perhaps this is too far out, I don't know :) But it seems important to consider not only the names of these blocks in isolation, but other parts of the UX, such as exactly where the Query block will be surfaced, the names of Query variations, and so on.

**Comment by ntsekouras** [comment]
>Perhaps this is too far out, I don't know :) But it seems important to consider not only the names of these blocks in isolation, but other parts of the UX, such as exactly where the Query block will be surfaced, the names of Query variations, and so on.

I think this PR can be limited to the base/generic names for the blocks. The block variation proposal for handling things differently through `Query` needs to be explored but not block this PR, since it affects many more stuff like `context detection`, `block patterns`, `different sensible defaults for inherit` between editors (site and post editor), etc..

So we should take into account that we could have a possible handling through variations but we need to decide on the best name for `QueryLoop` as a default, independently of  `inherit query` related controls and functionality.

**Comment by jameskoster** [comment]
In that case "Post Template" seems like a fair solution, at least as an interim. It's certainly an enhancement on "Query Loop" :) 

I still have some reservations about using the term "Template" but don't really have any alternative suggestions.

We should probably update the description of this block as well, perhaps something like:

> Blocks inside the Post Template determine the layout of each post returned by the Query.

The Query block itself could do with a better description too, but that is a little tricker as it currently has to account for multiple contexts (inheriting from URL or not). Perhaps that can wait until we know for sure whether it will actually be surfaced in the post editor or not.

**Comment by ntsekouras** [comment]
I'm closing this in favor of https://github.com/WordPress/gutenberg/pull/32514. It was much simpler to create a new PR than reverting so many renamings here that included `Query` to `QueryLoop`.

Please continue the discussions in the new PR.

**Pull request closed without merging**
