### PR TITLE
Rename "Navigation Menu Item" to "Link".

### LINKED ISSUE #18521: Update "Navigation Menu Item" terminology
Please see https://github.com/WordPress/gutenberg/pull/18422

### PR DESCRIPTION
**Pull request by mtias**
Closes https://github.com/WordPress/gutenberg/issues/18521

Revise how we name and refer to navigation items in different places.

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
I like the idea of making the nomenclature consistent with what a _user_ would expect rather than thinking about this technically as a "child Block of the Nav Menu Block" (which is developer-centric).

**Question**: is it _always_ the case that the "item" is a link? Or am I splitting hairs here? Could we not have nav items which aren't actually linked and therefore do not technically constitute "links"?

**Comment by getdave** [comment]
Looks like this will need a rebase now.

@mtias Do you consider this Blocking and do you want someone to take this over for you or will you continue?

**Comment by mtias** [comment]
Yes, we should settle on names here before switching the experimental flag off.

**Comment by shaunandrews** [comment]
Seems to me that we should not assume an item within the Navigation block will be a link. It’s a fairly common (even if not recommended) pattern to use a non-link item to create a group within a Navigation. To me, “Menu Item” seems obvious.

**Comment by mtias** [comment]
> pattern to use a non-link item to create a group within a Navigation

A non-link item should likely be a different block — paragraph, heading, etc.

**Comment by retrofox** [comment]
> A non-link item should likely be a different block — paragraph, heading, etc.

So the idea to render in the front-end an item which doesn't have defined a link with an `<span>` element doesn't make sense. https://github.com/WordPress/gutenberg/pull/18442

We need to re-define the behavior and workflow for the nav menu. Wondering for instance how to switch between the Nav Item to another block (paragraph, heading, etc) according to whether the item has defined a link or not.

**Comment by shaunandrews** [comment]
> A non-link item should likely be a different block — paragraph, heading, etc.

How would you add a different block? We don’t show the block inserter anymore, we just add the menu item block. As @retrofox mentions, I guess we could do some magic to change the block depending on if it has a link, but that seems very opaque and confusing.

**Comment by obenland** [comment]
> How would you add a different block? We don’t show the block inserter anymore, we just add the menu item block.

For now the navigation only allows one type of inner block, so there's no need for a selector. Once support for other types of blocks gets added, I'd anticipate the selector to come back.

**Review by obenland — APPROVED** [review]
I think that should cover it! Next up: `core/navigation-menu` => `core/navigation`.

**Pull request merged**
