### PR TITLE
Themes: Support title in templateParts

### LINKED ISSUE #34723: theme.json: support a description value for templateParts
## What problem does this address?

In theme.json `templateParts` supports two values: `name` and `area`. 

`name` matches with the filename for a template part. When viewing Site Editor > Template Parts, available parts are described using the value for `name`. This can result in an "unfriendly" label for each part, especially if using overly descriptive names.

For example, the following in theme.json:
```
"templateParts": [
     {
         "name": "header-site-logo",
         "area": "header"
     },
     {
         "name": "header-site-logo-navigation",
         "area": "header"
     },
     {
         "name": "header-site-logo-site-title-navigation",
         "area": "header"
     }
 ]
```
...currently displays like this in the Site Editor:

template-part-label-current

## What is your proposed solution?

Is it possible to support a third value in `templateParts`, please? Perhaps `description` could work as the key. 

This would allow for the following:
```
"templateParts": [
     {
         "name": "header-site-logo",
         "area": "header",
         "description": "Logo only"
     },
     {
         "name": "header-site-logo-navigation",
         "area": "header",
         "description": "Logo & navigation"
     },
     {
         "name": "header-site-logo-site-title-navigation",
         "area": "header",
         "description": "Logo, site title & navigation"
     }
 ]
```
template-part-label-proposed

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Adds "title" support in `templateParts` theme.json configuration.

Fixes #34723.

Cc @gziolo, I saw that you introduced i18n for the `customTemplates` title, and I just wanted to check if I'm handling it correctly here.

## How has this been tested?
1. Update `templateParts` definition in theme, e.g. Blockbase.
2. Go to the Site Editor -> Template Parts.
3. Check that provided "title" is displayed.

## Example
```json
"templateParts": [
      {
	      "name": "header",
	      "title": "Header",
	      "area": "header"
      },
      {
	      "name": "footer",
	      "title": "Footer",
	      "area": "footer"
      }
]
```

## Screenshots 
| Before | After |
| --- | --- |
| CleanShot 2021-10-14 at 13 09 52 | CleanShot 2021-10-14 at 13 10 20 |

## Types of changes
Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
> I saw that you introduced i18n for the customTemplates title, and I just wanted to check if I'm handling it correctly here.

It should work on the Gutenberg/WordPress core side, but we also will have to open a patch against WP-CLI to update the i18n schema used there.

Edit: it looks like it should be automated now:

https://github.com/wp-cli/i18n-command/blob/ea8a6b3ab19c490798b420beabf06ece40b8e708/src/ThemeJsonExtractor.php#L19

**Comment by Mamaduka** [comment]
> it looks like it should be automated now:

Great news. Thanks, @gziolo.

**Comment by gziolo** [comment]
There is another unit test that covers translations in `theme.json` that could get updated, too:
https://github.com/WordPress/gutenberg/blob/trunk/phpunit/class-wp-theme-json-resolver-test.php#L191-L199

**Comment by Mamaduka** [comment]
@gziolo, how do you update language files for the test theme?

**Comment by Mamaduka** [comment]
@gziolo figured it out.

P.S. Sorry about my Polish; I had to use a google translator.

**Comment by gziolo** [comment]
> @gziolo figured it out.
> 
> P.S. Sorry about my Polish; I had to use a google translator.

Good job updating the test 👍

I guess the translation is correct 😃

**Review by gziolo — APPROVED** [review]
It looks good and it has enough test coverage 🚀

**Pull request merged**
