### PR TITLE
Use "Save as Pending" when the Pending checkbox is active

### LINKED ISSUE #8894: Consider adding a "Save as Pending" button to make the pending state more clear for ongoing updates by editors/administrators
**Describe the bug**
Pending management can be confusing for Editors / Administrators if they want to keep a post/page in review or add a new one to the pending reviews.

**To Reproduce**
1. As a contributor
- I can save my post in draft mode ;
- When I click on the "Publish..." button of the fixed top bar, the confirmation message informs me my post will be pending a review from an editor.

2. As an Editor
- If i want to keep the post in Pending, I must click on the "Save Draft" of the fixed top bar, otherwise clicking on the "Publish..." does what it means : it's publishing the post even if the Pending review checkbox is active.
- if activate the Pending review checkbox for a page i want to submit for review, i must click on the "Save Draft" button to have the page in Pending review.

**Expected behavior**
As an editor/administrator, if the "Pending Review" checkbox is active the "Save Draft" button should have its text edited to "Save as Pending". Deactivating the "Pending Review" checkbox should then edit the text of the "Save as Pending" button to "Save Draft".

**Screenshots**
Here are 2 screenshots

classic-editor
In the classic editor the "Save Draft" button has been replaced by a "Save as Pending" button

modern-editor
In the Gutenberg the "Save Draft" button has not been replaced by a "Save as Pending" button

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 68.0.3440.106 

**Additional context**
- Gutenberg 3.5.0.

### PR DESCRIPTION
**Pull request by imath**
## Description
This my suggestion to fix #8894, an issue I posted 2 weeks ago. It simply gets the edited post status and use "Save as Pending" instead as "Save Draft" if this status is pending (meaning the Pending checkbox is active). As soon as this checkbox is unchecked, the button use "Save Draft".

## How has this been tested?
I've tested using Gutenberg on my local environnement. I also ran successfully `npm run test`

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by youknowriad** [comment]
Maybe we should just remove the button, because I expect the "publish" button to do the exact same thing right?

**Comment by imath** [comment]
No the "publish" button is publishing the post, it does not leave it as Pending

**Comment by youknowriad** [comment]
I'll just add a "Design Feedback" label to get better thoughts :P 

I was personally thinking the "publish" button should follow whatever options are defined in the document sidebar:

 - If it's public, it should say "Publish"
 - if we set a future date, it should say "Schedule"
 - If we're a contributor, it says "Submit for review",
 - Maybe if the "pending" status is checked, it should say "Submit for review" as well?

**Comment by imath** [comment]
@youknowriad I see what you mean, sorry. I haven't tested as a contributor. This is another case : if as an administrator i open a submitted for review post and i click on "Save Draft" it keeps the post as Pending.

**Comment by youknowriad** [comment]
Yes, these two are related. We should change the label like you did, or change the behavior of the publish button and hide the save draft button, I was just sharing the possible alternative. Let's wait for designers to chime-in and give more thoughts ;)

**Comment by karmatosed** [comment]
I agree with you @youknowriad:

> If it's public, it should say "Publish"
if we set a future date, it should say "Schedule"
If we're a contributor, it says "Submit for review",
Maybe if the "pending" status is checked, it should say "Submit for review" as well?

Let's get that in and see what it feels like.

**Comment by imath** [comment]
Thanks for your feedback @karmatosed I will update the PR in this direction asap.

**Comment by youknowriad** [comment]
Thanks for the updates @imath works great for me. A couple of questions/suggestions:

 - When we're a "contributor" and we already submitted the post for review, should the publish button say "update" instead of "submit for review" (no strong opinion personally)?
 - The "submit for review" button is big and I think one of the decisions behind keeping "publish" in the first step (before opening the panel) was to make sure it always fits. cc @jasmussen for confirmation that it's fine to change.

**Comment by jasmussen** [comment]
> The "submit for review" button is big and I think one of the decisions behind keeping "publish" in the first step (before opening the panel) was to make sure it always fits. cc @jasmussen for confirmation that it's fine to change.

Correct, this is a big part of it. Specifically this needs to be tested on an iPhone 5 in German. 

Whatever the label is, if it fits in german on an iphone 5, ship it. If it doesn't fit, that's a blocker for the label change. 

The easiest way to test this is to use Chrome. Open the inspector, and click the little "mobile" icon in the top left corner of the inspector, then choose iPhone 5. 

screenshot 2018-10-10 at 10 27 24

**Comment by imath** [comment]
@youknowriad about:

> When we're a "contributor" and we already submitted the post for review, should the publish button say "update" instead of "submit for review" (no strong opinion personally)?

I'm in favor of keeping how it's labelled into the classic editor see screenshot below:

classic-editor

@jasmussen I've done the test the way you advised to do it. Here's the screenshot with "Submit for Review..." (when pre publish checks are on).


publish-checks-enabled

So part of the top bar is not visible, so I guess it's a problem but, I wanted to stress the fact you already are in troubles without this change **if pre publish checks are off**, because in this case, it's not "Publish..." but "Submit for Review", see screenshot below.

publish-checks-disabled

So what about using a preview icon instead of the "Preview" button for Mobile ?

**Comment by jasmussen** [comment]
Thank you for testing german.

I don't agree it's okay to merge this just because there's an existing regression with the button as a result of toggling off the pre-publish checks.

Instead I will open a separate ticket for that issue, good catch. I would suggest the best solution is to always keep the pre-publish checks on mobile, and not show the option to disable them there.

**Comment by imath** [comment]
@jasmussen thanks for your feedback. I reverted so it's now using "Publish..." for the toggle just like before.  

publish-checks-enabled

**Comment by jasmussen** [comment]
Thanks so much, that looks good! I created #10475 to track the regression.

**Review by youknowriad — APPROVED** [review]
LGTM 👍 

Separately, it would be good to add an e2e test with the contributor role. This looks like something that can regress easily.

**Comment by imath** [comment]
Thanks a lot @youknowriad 👍

**Pull request merged**
