### PR TITLE
[RNMobile] iOS Image block caption multiline fix

### PR DESCRIPTION
**Pull request by etoledom**
This PR fixes an issue on iOS where pressing Enter on a Image Block's caption field, it won't do anything.

It should append a `<br>` tag and create a new line.

`gutenberg-mobile` side PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1107

To test:
- Run the example project.
- Select the Image block with content.
- Write something in the caption field.
- Press enter,
- Check that a new line is created.
- Switch to HTML mode.
- Check that the new line was created by appending a `<br>` tag.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
> Press enter,

or press Shift+Enter ?

**Comment by etoledom** [comment]
> or press Shift+Enter ?

A single Enter should make a new line on the Image Caption field by appending a `br` tag. That's how web works.

**Review by SergioEstevao — APPROVED** [review]
Working great! Good catch!

**Comment by etoledom** [comment]
Thank you!

**Pull request merged**
