### PR TITLE
Try an alternative way to navigate the inserter + some tweaks

### PR DESCRIPTION
**Pull request by youknowriad**
inserter

### CODE REVIEW

**Comment by jasmussen** [comment]
I dig it. It basically runs with an idea by @karmatosed to have an ellilpsis on the right side of the tabbar, and in turn replaces the tabbar. I like this for a number of reasons:

- It visually lightens the whole UI
- It makes the category group much more scalable
- It makes the inserter menu look like it's made of _menu material_, same as other popout menus
- It scales better to the incoming Inline Images feature, where we can do [something like this](https://github.com/WordPress/gutenberg/pull/5794#issuecomment-381056583), which would be harder with the tabbed interface

Designwise, this looks great. I'm assuming it handles mobile as well? How about the Saved blocks previews?

One thing I don't love is the all-caps small "SUGGESTED" title. Not that it doesn't look good, but because it's the only place we use that heading. 

The pattern we should emulate here is that of other menu subheadings:

screen shot 2018-04-13 at 12 59 08

**Comment by youknowriad** [comment]
> I'm assuming it handles mobile as well? 

In mobile the navigation menu take the whole area under the search input.

> How about the Saved blocks previews?

These show like today, which means they'll cover the navigation menu but I think it's fine

> Tne thing I don't love is the all-caps small "SUGGESTED" title. Not that it doesn't look good, but because it's the only place we use that heading.

Sure, I'll update. Though, do you think we can use it elsewhere in a separate PR. I think for these small titles, it feels a bit better (at least for me).

**Comment by jasmussen** [comment]
> Sure, I'll update. Though, do you think we can use it elsewhere in a separate PR. I think for these small titles, it feels a bit better (at least for me).

We can certainly use it in more places than once, for example replace all menu subheadings with allcaps. However this feels a bit screamy when it reaches the 13px font size that we should ideally never go under. I notice it's 12px here, would you hate to go 13?

**Comment by afercia** [comment]
@karmatosed thanks for asking. Instead of "how we make a sidebar like this accessible" (which can't be made 100% accessible) I think a more proper consideration is what we miss with this new proposed implementation compared to what we have with the tabbed interface implementation. 

Not everything can be made accessible if it's not designed since the beginning with accessibility in mind. I'm sorry but this is of fundamental importance for all designers and developers to understand. Designing a new fancy interface without any initial accessibility consideration and then asking other people "now make it accessible", is not a good path if we want this project to be accessible. This must change.

While a tabbed interface is standard because it's part of the ARIA specification and provides an expected, well defined, interaction model that users are used to (it's used also in the operating systems UI), this new fancy panel and the scrolling div are not standard. There's not a defined interaction model users can predict.

I'm a bit surprised a so drastic change is proposed at this point of the project. The current interfaces was developed in several steps with a good collaboration between teams and with a good balance between visuals and accessibility. It was agreed on. It was tested at length. We've involved testers even at WordCamp US and they spend the whole day testing the inserter with keyboard only.

I'll leave out considerations about how much this kind of unexpected changes can cost in terms of time spent in design and implementation.

Moving on to an _initial_ accessibility feedback, far from pretending to cover all the potential critical points:

- the current tabbed interface is better because it has a predictable interaction model
- it gives feedback about the currently selected tab, for example screen readers announce "tab, selected, 2 of 4" and so on
- keyboard users can use arrow keys to switch tabs and then jump directly in the panel using the Tab key: this is one of the main advantages of a tabbed interface because users are not forced to go through all the tabs
- when jumping to a panel, it is correctly announced because it's labeled and it will say users if the panel is about Blocks, or Embeds, etc.
- there are no focus losses, focus works generally well except for #5242 which is still to implement
- various other details, but overall the important thing is the current interface is rich of information and feedback and that's what users need

About the new proposed UI:
- there's a general lack of feedback
- pressing the toggle button doesn't give any audible feedback about what just happened
- the expanding panel uses the roles menu and menuitem but that's not appropriate: menus should be used exclusively for "desktop-like" menus, i.e. menus with items that are actionable controls that "do something" /Cc @aardrian
- the panel items are more links for navigation, i.e. links to in-page anchors in the scrollable div, so semantically this is more a navigation menu and should be implemented accordingly
- once a menu item in the panel gets activated, there's no feedback at all about what happened other than the visual feedback (the div scrolls)
- closing the panel clicking on the X button produces a focus loss (focus is not moved anywhere)
- users are forced to tab through all the items in the panel to finally get to the block types
- the scrollable div now lists _all_ the block types together: when exploring the content with a screen reader this is overwhelming information because there are dozens of block types announced all together
- most importantly, the scrolling is pointless when using a keyboard: yes the div scrolls and brings into view the related block types but then keyboard users have to tab into the block types panel and, of course, they are forced to start from the first block type at the top

Have you tested it using a keyboard, at least? Besides the scrolling, there should be a mechanism for keyboard users to jump directly to the group of block types related to the choice they've made: e.g.
- press "Embeds"
- the panel scrolls and sighted keyboard users can see the related block types
- we shouldn't assume they want to directly jump there
- maybe they want to press "Shared" to see the following group
- they should be offered an option to jump to the related group, if they want
- how to communicate all this to non-sighted screen reader users would be a challenge (and this is one of the main reasons that make me think it can't be made accessible)

Overall, I think the new proposed interface offers a reduced level of accessibility and not all the issues can be fully solved. I'm afraid it would be a regression compared to the current UI.

**Comment by aardrian** [comment]
I was tagged by @afercia , so I am looking. Is there a code version of this?

I am at WCLDN contributor day and had the chance to ask a couple people what problem this is trying to solve. I understand it is related to the growing number of tabs in that interface element, coupled with text expansion from localization.

This challenge is not new, and to borrow from Bruce Tognazzini a bit, I think the underlying concept in this image is _viable_ but can better lean on existing UI patterns.

Immediate changes I would make:

- Instead of tabs in the current UI (not the example above), have a list on the left (instead of the right as this example shows).
- That list is visible by default with an option to collapse it.
- It can still use the ARIA tab model for screen readers, to a point.
- Chunking them first may be more valuable than a very long list, particularly for users running large fonts, using a screen magnifier, or using a screen reader. Users who rely on a keyboard will benefit as well from being able to jump into groups instead of navigate 20 distinct tab things.

These modifications can mitigate some of the issues Andrea raises above. Again, code unseen.

**Comment by karmatosed** [comment]
My thoughts on this are pretty much 100% what @aardrian says. I think we can make this work and balance the accessibility concerns.

**Comment by shaunandrews** [comment]
I think the drawer looks a little complicated for what is already a pretty complex piece of UI. I wonder if we can simplify the lines a bit and make the drawer feel a little more like a part of the popover, and not another piece sticking off the side. Here's a quick mockup:

screen shot 2018-04-24 at 1 13 11 pm

Along that same idea, I wonder if we could simplify even more and just some form of dropdown to navigate between groups of blocks:

screen shot 2018-04-24 at 1 13 17 pm

**Comment by karmatosed** [comment]
@shaunandrews I really like the first option, that feels like it takes this idea and builds nicely on it. I'm slightly less keen on the drop down, although I could be convinced. I am wondering if it scales as we add more categories and I think it could cause issues with accessibility (I may also be wrong). I do feel the top option has a solid, strong style I'd like to see us take into code. To me, that solves some of the previous issues we have we have already with the library.

**Comment by iamthomasbishop** [comment]
Just my 2 cents on the latest proposals, from the mobile angle:

I _really_ like that top variation that @shaunandrews proposed, specifically for desktop context - although I might remove the hamburger icon altogether and force expand the right side.

With that said, I'm not sure if it'd translate well to smaller screens. For mobile I think the current horizontal tabs UI is more familiar and discoverable than the proposals (again, for mobile specifically), so my opinion is we should keep that in mind.

The biggest issue I have with horizontal tabs is future scalability when we have 10000000 block types, but I'm also not loving the idea of tucking the options behind a hamburger menu, or even worse a dropdown.

**Comment by afercia** [comment]
From an accessibility perspective, the "dropdown" could be a better solution depending on the implementation... if it's a native select, that would be 100% accessible because... it's native! However, it would need a button i.e.  no action triggered `onChange`.

As per the "side panel" I can only repeat the a11y recommendation previousl expressed by @aardrian and myself: move it to the left and still use an ARIA tabbed interface (vertically positioned):

- have a list on the left (instead of the right as this example shows): this is important for content linearization: navigation should come first and visual order should match DOM order
- That list is visible by default with an option to collapse it: having a tabbed interface, we can't hide tabs by default
- It can still use the ARIA tab model for screen readers, to a point.
- Chunking them first may be more valuable than a very long list, particularly for users running large fonts, using a screen magnifier, or using a screen reader. Users who rely on a keyboard will benefit as well from being able to jump into groups instead of navigate 20 distinct tab things.

Again, the great advantage of ARIA tabs is that they don't force users to press tab to navigate all the tabs. Tabs are navigated with arrows, pressing the Tab key brings users directly inside the tab panel. This is even more important with 20 or more tabs.

> The biggest issue I have with horizontal tabs is future scalability when we have 10000000 block types

Sure but with 10000000 block types also the tabs on a side or a dropdown would be an issue as well.

Is there any design of how this (see below) should look when there are 20 or more block types? (Please move the panel on the left 🙂)

screen shot 2018-04-24 at 1 13 11 pm

**Comment by jasmussen** [comment]
> The biggest issue I have with horizontal tabs is future scalability when we have 10000000 block types, but I'm also not loving the idea of tucking the options behind a hamburger menu, or even worse a dropdown.

Good observation, and this is why we added tabs in the first place. A thought, though: having used Gutenberg for a year now, I've increasingly found myself not using the tabs _a single time_. Either the block I need is available directly as a suggested block, or I search. I say this not to project my behavior on to everyone — that would be making assumptions about how other people use Gutenberg — but purely as an observation: are people actually using the tabs, and if they aren't, would a filter mechanism, whether through popout menu, popover, dropdown or otherwise, be sufficient?

**Comment by hedgefield** [comment]
I would say so, I've never used the tabs either. I like @shaunandrews first mockup a lot too. I would also prefer it if it's always visible, and shown on the left. Good stuff! Looks much better than it did before already.

On the matter of scalability, I wonder if it wouldn't make sense to stretch the inserter to something like browser height. That would give plenty more space, and it's not like there's anything below it that you need to interact with at the same time.

And whatever the case, if the categories list gets too long you can always use the search field or scroll down. It feels like a backup.

**Comment by youknowriad** [comment]
Thanks all for your feedback, highly appreciated.

The fact that it feels like a backup (and seems that most of us agree on that point) is exactly why I think it should be closed by default. You don't need it unless you really want it.

Also, it opens on the right because this is the natural flow due to the position of the inserter at the moment: most inserters we have opens on the right and there's not enough space on the left (if you close the WP sidebar for instance). We also use this space to show previews of saved blocks which means we're not losing place by adding this to the right.

Regarding accessibility, it has already been updated to follow the guidelines:

 - Return focus on close
 - Tab aria model
 - Filtering instead of scrolling.

I'll update to match the proposed design.

**Comment by youknowriad** [comment]
About the suggested tab names. Not certain the proposed reorganisation make sense. It remplaces "blocks" by "All" but the thing is "blocks" doesn't really show all the blocks: The saved and embed blocks are not shown. The "All" is what we show when no filter is selected, I believe we can add a tab for this but how to we name the current "blocks" tab, should we leave it as is?

**Comment by youknowriad** [comment]
inserter

**Comment by karmatosed** [comment]
> On the matter of scalability, I wonder if it wouldn't make sense to stretch the inserter to something like browser height. That would give plenty more space, and it's not like there's anything below it that you need to interact with at the same time.

The issue of scale we have is a valid one but I do think we have to consider the impact of a full scale library. I am not right now convinced this is the best route, that doesn't mean we don't have an issue of scale - we are facing that. Can we do things like surface blocks better? Favouriting is one thing we could also add (I'm going to make an issue for that to surface as an idea). An imposing full height library may not bring the benefits it first seems it would, there's a flow break I think we can avoid and work in smart ways of surfacing blocks that people need. There is a powerful connection in someone seeing what they are writing and creating.

> The fact that it feels like a backup (and seems that most of us agree on that point) is exactly why I think it should be closed by default. You don't need it unless you really want it.

I think having it open by default feels like a balance we have to make for accessibility and usability. Until we have the surfacing I do think tabs aren't as 'unused' as those of that use it all the time think.

> About the suggested tab names. Not certain the proposed reorganisation make sense. It remplaces "blocks" by "All" but the thing is "blocks" doesn't really show all the blocks: The saved and embed blocks are not shown. The "All" is what we show when no filter is selected, I believe we can add a tab for this but how to we name the current "blocks" tab, should we leave it as is?

Can we have all literally showing in all? Otherwise yes 'all' isn't a good way.

If having it open left is an accessibility blocker we can bring that in without breaking the flow too much, that feels like a point whilst a negotiation, a good one to adapt to. That's of course assuming it is a blocker.

**Comment by youknowriad** [comment]
@afercia Both of these symptoms are due to the use of the grid layout. The first one is easily fixable: we can show everything at the top or use a scrollbar, I do think the scrollbar is better and I don't think we would add extra tabs there (at least not that much).

I'll see if I can make the grid layout work on IE11 because it ensure a good DOM position (the filtering panel shown right after the toggle) but can use something else if not (flexbox or relative positionning).

**Comment by afercia** [comment]
@karmatosed thanks, yes having the "menu" open by default would be far better for the simple reason it's part of a tabbed interface. Assistive technology users need it open by default. We can't implement a tabbed interface and hide half of it. Giving the ability to collapse it is already a big trade-off. Tabbed interface are supposed to be complete, made of a tab list, tabs, and tab panels. When the "menu" is closed, we have just tab panels...announced as such... users will wonder what that does even mean:

tab panel but no tabs

Having the "menu" on the right is a blocker for accessibility. One of the fundamental WCAG rules is that the visual order should match the DOM order. Imagine low vision users who use a screen magnifier or users with cognitive impairments or various other cases: they all will be confused by the fact focus goes in an unexpected place or even outside their limited vision field. Instead (quoting): When the source order matches the visual order, everyone will read the content and interact with it in the same (correct) order.

**Comment by afercia** [comment]
Some more considerations:

## Usability

As I see it, presenting _all_ the block types in the initial view is a big usability issue: potentially, there may be hundreds of block types and having a huge list to scroll is far from ideal. Also, in the initial view users will see a "Suggested" title which is misleading as they're actually viewing all the block types instead.

A11y note: screen readers tend to read all the content of a tab panel when landing on it: NVDA does it and reads out all the block types... that's an overload of information that should be definitely avoided:

nvda reads out all

I'd strongly recommend to reconsider the idea of showing all by default. There's an overload of information for all users. Add to that the menu is closed by default and not so discoverable (though that will change maybe?), it also requires an additional click... too many steps to filter the blocks. Also, having the shared block previews that overlay and hide the menu is far from ideal.

To me, the expanding panel is not the best idea in the first place, it breaks the tabbed interface and makes things less discoverable. Can we consider to make it always visible? What is the value added by making it collapsible?

Some more usability considerations:
- the buttons labels and naming mismatch: is this an "inserter navigation" or a "Navigation Panel"? Do users know what an "inserter" or a "panel" are? I'd use just "Block types navigation".

screen shot 2018-04-25 at 11 05 06
screen shot 2018-04-25 at 11 05 09

- to backup the previous point, please also consider to avoid the word "toggle" as it's very hard to translate, see core Trac ticket: "Remove use of "Toggle" in strings" https://core.trac.wordpress.org/ticket/34753. 
- please let's try to avoid excessive capitalization "Close Navigation Panel" seems a bit too much to me and "Toggle inserter navigation" isn't capitalized
- is there really the need for the "Navigation" title in the panel? It's pretty clear it's a navigation tool. Removing the title would also save some vertical space.
- is there really the need for the "Close" button? There's already the Toggle one.
- the "triangle hamburger" icon: it's not really clear what that does mean. I think in Gutenberg there are other patterns for icons that open menus. Please, no hamburgers :)

## Accessibility (see also previous comments)
- the toggle button needs `aria-expanded`: right now, when clicked there's absolutely no feedback about what happened. A good feedback can be given by the combination of a good button label together with screen readers announcing "expanded/collapsed". Hearing `Block types navigation {expanded}` and `Block types navigation {collapsed}` would be perfectly understandable.
- pressing Escape when in the "menu" doesn't work and there's a focus loss: we should make a decision here. Focus should be moved back to the "invoking context" but this can be different depending on the interaction and pending changes to the UI. Should Escape close just the menu and focus be moved back to the button that opens the menu? Or should Escape close the whole inserter and focus be moved back to the "Add block" button,  as it does when pressing Escape in the inserter main panel? I'd say the second option seems simpler and more predictable. Instead, a "double step Escape" flow seems a bit more complicated
- the focus style on the tab panels was implemented for good reasons and it's now missing 

focus style

**Comment by shaunandrews** [comment]
Tried the nav list on the left. Its ok, but then the pointer and everything gets weird. I don't hate it, but I don't love it.

screen shot 2018-04-25 at 10 03 07 am

Here's another one that incorporates the nav visually into the rest of the popover, so it feels less like an add on. It also keeps the search at the top, making the pointer feel a little more natural.

screen shot 2018-04-25 at 10 04 45 am

One thing worth experimenting with is how this all scrolls. Like @afercia mentions, as this nav list grows its going to need to expand or scroll. We could have individual scrollable areas, but that just gets messy really quickly. In the mockup above, I tried to show how the popover could work as one big scrollable area.

**Comment by shaunandrews** [comment]
gute-inserter-drawer

A few things I noticed after getting this PR running locally:

1. The current toggle button (Also: What is that icon?) has some extra spacing below it. This is in Safari.
2. The entrance animation is pretty nice, but I noticed that the 'X' icon moves with the transition, but the rest of the elements within the drawer are fixed. It looks a little strange. Either nothing within the drawer should move, or everything should move together. Having a mix is a little disorienting.
3. There's no exit transition, which feels "wrong" when paired with a nice entrance transition.

**Comment by afercia** [comment]
> Also: What is that icon?

It's a triangle hamburger.

**Comment by chrisvanpatten** [comment]
I reeeally like the look of that 2nd mockup @shaunandrews! I can't vouch for its a11y-friendliness but visually it's the best one I've seen so far.

What would be the accessibility impact of having the height of the inserter be flexible up to a point (like maybe a max-height of 75vh?), and then have the tab list scroll if it's longer than that… strictly as a fallback? I don't think anyone wants a world in which the list of tabs is that long, but it's a case that probably has to be handled to be safe.

**Comment by chrisvanpatten** [comment]
> Why we should limit the height in the first place? When users install a lot of plugins that add lots of block types, then they would expect to see the new block types in the inserter. The most obvious thing would be jus show the new tabs.

I definitely agree — hiding is never good — I'm just imagining a case where there are like 50 tabs for some reason and the block inserter ends up being 2000px tall or something 😂

It also creates an issue if the inserter is inserted in the "above" position… it will scroll off the top of the page and you won't be able to access everything (example below where I just extended the height of the existing inserter):

screen shot 2018-04-25 at 13 29 22

**Comment by chrisvanpatten** [comment]
Also happens if you insert toward the end of the post although it's less of an issue there because you could just theoretically have the content area extend to fit the inserter…

screen shot 2018-04-25 at 13 30 55

**Comment by afercia** [comment]
@chrisvanpatten interesting. Thanks to your last screenshots I've noticed that it already happens in this PR, adding just 10 tabs. On a small but not so small screen (iPad) and with some short content 😬 

screen shot 2018-04-25 at 20 01 43

That's because the menu is initially closed and the inserter positions itself "thinking" it has enough space. But then, when the menu expands, the height increases and... boom: it goes off screen.

I think we've underestimated the effect of the height on the position calculation. Or, the menu needs to be initially open, as mentioned in https://github.com/WordPress/gutenberg/pull/6168#issuecomment-384251080
> I think having it open by default feels like a balance we have to make for accessibility and usability.

**Comment by shaunandrews** [comment]
Another option occurred to me earlier today; We could follow the pattern from the sidebar with the accordions as a way to group blocks:

screen shot 2018-04-27 at 11 52 31 am

**Comment by chrisvanpatten** [comment]
I LOVE that, but I think the main problem is that it's not necessarily clear from looking at it that there's a scroll (especially in your animated example… until you actually do scroll). And I think the scroll + accordion could get cumbersome very quickly.

Which is a shame, because it looks very very very pretty :)

**Comment by karmatosed** [comment]
@shaunandrews you are on a roll! This is excellent and really nice to see all these explorations.

I am right now wondering why we haven't considered the accordion as well yes that totally could work! My slight reservation right now is how that scales but right now we have that issue. I also think having the search at the top maybe is a good idea over right at the bottom if we have this interface. I sort of come back to the fact search should be the 'goto' area.

Another thing I instantly really like is the notifications number, used as a count in the shared blocks but I'm imagining that as indication number of new blocks. I can see that being so useful for new blocks as themes and plugins add it. That would be great to explore whatever interface we go with.

For some reason I am less keen on the pill shapes, I don't have a solid reason as much as it feels very different from what we have now. That's not to say it's bad as much as seems to not fit. It also doesn't mean what is there now shouldn't be adapted. The same goes with the colors, I can see them as being a distraction to some but really useful and cheery to others, maybe a plugin?

**Comment by chrisvanpatten** [comment]
A few random brainstormy ideas… (feel free to disregard!):

I think the "there's more to scroll" would be a bit clearer if that subtle gradient at the bottom of the scroll window was a bit taller, maybe?

untitled_5_sketch

Resizable…? What if the bottom was draggable to make it taller or shorter?

untitled_5_sketch

Might also be helpful to have some kind of message for new users indicating it's scrollable that fades after you scroll (and never shows again)…

untitled_5_sketch

Just some random thoughts :)

**Comment by chrisvanpatten** [comment]
Oh shoot, and the thought that inspired that brainstorm session and I promptly forgot to mock up…

On scroll, maybe the currently open accordion header could be pinned to the top so you don't forget where you are?

untitled_5_sketch

**Comment by chrisvanpatten** [comment]
Sorry for the commentspam, and potentially dumb question, but something else occurred to me… has there been any consideration of positioning the inserter to the right of the inserter button?

In the current inserter, on smaller screens (like iPads or my 11" MacBook Air) you get this issue:

screen shot 2018-04-27 at 14 54 29

But if you insert it to the right (sorry this is kinda hacky but you get the idea!)…

untitled_5_sketch

You have the freedom to position it in the middle, and a user can expand it and keep it in view a lot easier.

**Comment by shaunandrews** [comment]
> that it's not necessarily clear from looking at it that there's a scroll (especially in your animated example… until you actually do scroll)

Take these mockups for what they are: Approximations of a real UI. A real UI would have scrollbars dictated by the OS (I assume, I don't think wp-admin/Gute do any custom scrollbars). This means for Windows users with a mouse, there would be visible scrollbars; For Mac users scrollbars would appear briefly (by default) and then fade away about the mouse is moved over the scrollable area.

> I think the scroll + accordion could get cumbersome very quickly.

I kinda of agree with you here, but I'm willing to try it and see what actual problems we run into.

> he search at the top maybe is a good idea over right at the bottom

My motivation for moving the search to the bottom was to put the focus on the blocks; The blocks are the star here, the search is just on way to find a block. I still see the search being given focus immediately when you open the picker, so the workflow should remain mostly unchanged.

> I am less keen on the pill shapes

I stole the shape from the iOS keyboard apps. I don't love it either, but its always fun to try new things. :)

> The same goes with the colors, I can see them as being a distraction to some but really useful and cheery to others

I think we need to add something to block listing to let them standout from each other. Right now Dashicons or Gridicons aren't unique enough for everyone. Some more custom illustrations (by letting people use SVG's) would go a long way, but I think when paired with a color — it really allows developers to let their brand shine through. Without color, I worry that all blocks just blend together in the picker.

**Comment by chrisvanpatten** [comment]
@shaunandrews I went back and struck through my original comment up there because on reflection my concerns weren’t as bad as I first thought :) sorry about that! Excited to see this evolve.

**Comment by shaunandrews** [comment]
screen shot 2018-04-28 at 11 25 16 am


Playing some more. I think maybe we could keep the colors for the "official, out-of-the-box" blocks the same (a light gray), and reserve the brighter colors for developers and brands.

**Comment by jasmussen** [comment]
I was about to suggest that you use colors from Hugo, https://codepen.io/hugobaeta/pen/grJjVp, but I also don't want to put out the wildfire that has captured you. Flame on!

**Comment by karmatosed** [comment]
@shaunandrews just as a little iteration, what do you think of bringing back the buttons with the text included and combining with the accordion? I am enjoying the exploration but I do wonder which method has better readability - not sure of the answer yet.

2018-04-28 at 17 49

I do like how 'app' like this is going with the buttons. We maybe can open up the background color and an icon for developers to give them that option.

**Comment by iamthomasbishop** [comment]
I must say @shaunandrews - the last iteration is pretty great. I wasn't feeling the color icons initially but this (neutral "official" icons with the potential to customize others) feels like a sweet spot. 

I also think this is feeling very native app-like, and while I'm not 100% sold on the treatment, I like where it's heading. 

My initial reaction to pulling the labels out if the icon is that it would add for more visual separation, which I like. It's also a more familiar style for native app users. My only concern is how does it look & feel in the grand scheme of things, inside the rest of the UI?

🤘

**Comment by iamthomasbishop** [comment]
Also fwiw: on mobile/native GB we will be making the button/pill/icon taparea larger for a more spacious tap area and to make drag-n-drop-to-add more discoverable. The sacrifice there is you show less blocks on the picker. Idk if that is applicable to web but I thought it was worth mentioning 🙂

**Comment by ianstewart** [comment]
@shaunandrews one thing I really like about your last iteration — ignoring the obvious super-cool app-like space for new blocks to bring character and branding — is the use of negative space and colour (the grey) + contrast to separate the blocks. It's easier to "read" than using lines as separators for these elements. And "feels" more like abstracted blocks in the selector.

**Comment by shaunandrews** [comment]
Worked up a little gif to get a feel for how the accordions would work:
block picker in motion

Also, here's a quick comparison of the current blocks and the updates I made above:

screen shot 2018-05-07 at 9 57 53 am

**Comment by karmatosed** [comment]
@shaunandrews thank you for the gif, that's really useful to see it in action. I really do like the feel of this and flow. I have to say I still am not totally sure about the background on icons and lack of larger button including text. That said, I do think we can run with your suggestion and at least see what the feedback is of it in a PR. @youknowriad would you be up for doing that?

**Comment by youknowriad** [comment]
Sure @karmatosed I'll give a try 👍

**Comment by youknowriad** [comment]
Ok! so I tried this in https://github.com/WordPress/gutenberg/pull/6636 As a developer, what I like about this is the code simplification :) 

I didn't implement the color API yet.

Let me know what's missing.

**Comment by afercia** [comment]
> what I like about this is the code simplification :)

And if this goes in, I think we should further simplify and remove the roles menu, menuitem, and remove arrows navigation :) The groups wouldn't be "menus" any longer, arrows navigation would be inappropriate and not expected. They would be just accordions with buttons as content.

**Comment by shaunandrews** [comment]
> Gutenberg is already icon heavy. If we can do without them, perhaps that's best, at least for now.

Sure. I was trying to find a way to make the Favorite and Shared accordions stand out from the rest—especially the Shared section, as thats the same icon used to denote shared blocks in the editor.

> I feel like maybe for the core offering, none of the out-of-the-box blocks should have color.

Agreed. That last few mockups have been sticking with a single, gray color for "out-of-the-box" blocks.

> However, maintaining the correct icon and brand color, obeying brand guidelines, for each of these services, will quickly become an onerous task, and is arguably a task WordPress shouldn't even be part of in the first place.

FWIW, I wasn't suggested these as replacements for the embeds—you may notice that the Embed blocks are listed in one of the accordions in my latest mockup. I was just showing what a branded block could look like; Those are imaginary blocks from Spotify, YouTube, and WooCommerce.

**Comment by jasmussen** [comment]
> Those are imaginary blocks from Spotify, YouTube, and WooCommerce.

Solid — just wanted to clarify because both Spotify and YouTube have oembed counterparts. But I definitely agree that if those three made their own core blocks, they should totally be able to look like that.

**Comment by aardrian** [comment]
@gravityrail Please note, CSS alone may be inadequate to meet the WCAG 2.0 AA compliance that Gutenberg needs to hit. The icon will not be announced as that symbol by screen readers (if at all), so if it relies strictly on visuals it needs some other indicator.

**Comment by gravityrail** [comment]
@aardrian the intention here is not to use CSS to specify the icon or icon title itself (that code is unchanged), but rather for lightweight branding (e.g. background color). 

That said, of course people could use CSS to add meaning to the icon, so perhaps we should also create a hook for those people to add `aria-*` properties there too.

**Comment by youknowriad** [comment]
Thanks all for the feedback, closing in favor of #6636

**Pull request closed without merging**
