### PR TITLE
 Components: Refactor MenuItems* components

### PR DESCRIPTION
**Pull request by gziolo**
## Description
This PR addresses ~two~ three comments from #5761:
- https://github.com/WordPress/gutenberg/pull/5761#discussion_r176813993 - renames `<MenuItemsItem />` to `<MenuItem />` and `<MenuItemsGroup />` to `<MenuGroup />` as suggested by @mtias.
- https://github.com/WordPress/gutenberg/pull/5761#discussion_r176974149 - simplifies the logic for `classnames` as it does a truthiness check, so there's no need to coerce to a boolean value in `<MenuItem />` component. Suggested by @aduth.
- https://github.com/WordPress/gutenberg/pull/5729#discussion_r177282259  - when testing an example, I intuitively expected this to be the children of the component, and had to circle back here to find out it wasn't. Suggested by @aduth.
## Screenshots (jpeg or gifs if applicable):

There should be no visual changes:

screen shot 2018-03-26 at 12 54 03

## Types of changes
Refactoring.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by atimmer — APPROVED** [review]
Looks good 👍

**Comment by gziolo** [comment]
I'll wait with merge until #5729 is in, to avoid merge issues in there.

**Comment by gziolo** [comment]
@Xyfi can you double check if this works properly with the Plugins API?

With the latest changes applied you will have to register a menu item as follows:
```js
const {
	registerPlugin,
} = wp.plugins;
const {
	PluginMoreMenuItem,
} = wp.editPost.__experimental;
const Component = () => {
	return (
		<PluginMoreMenuItem
			name="more-menu-item"
			icon={ Icon }
			target="my-sidebar"
			type="sidebar"
		>
			My item
		</PluginMoreMenuItem>
	);
};
registerPlugin( "my-plugin", {
	render: Component,
} );
```

**Comment by gziolo** [comment]
@atimmer I rebased with all the changes introduced in #5729. I also added new commit 3b3f28faececb882889c7ab95c547a35109c0441, which addressed the latest comment from @aduth from the same PR.

**Review by abotteram — DISMISSED** [review]
All seems to be in order, works fine with the plugin API.

I think the file `components/menu-items/style.scss` is redundant and can be removed, please double-check.

**Comment by gziolo** [comment]
> I think the file components/menu-items/style.scss is redundant and can be removed, please double-check.

Good catch, leftover from the merge conflict. It's removed now.

**Review by abotteram — APPROVED** [review]

**Pull request merged**
