### PR TITLE
Add paragraph selection filter for Gutenberg editor

### PR DESCRIPTION
**Pull request by hussain-t**
## Description
This PR solves issue #27481

This PR adds a filter that allows to override the paragraph selection count in Gutenberg. This is so that we can select specifically the number of paragraphs that can be selected letter by letter instead of the whole paragraph being selected.

Here is the plugin [repository](https://github.com/hussain-t/gutenberg-paragraph-selection-length) for the custom paragraph selection.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks for contributing, @hussain-t.

I'm pinging the core team if they've explored this feature and have any pointers.

I noticed that if I select text across two-paragraph blocks and hit delete, it removes both blocks instead of merging them.

https://user-images.githubusercontent.com/240569/151361569-43f8e670-aaa9-4fd4-8564-6b4a9fe1d091.mp4

While I think this is a nice workaround. There're more user interactions we'll need to account for.

**Comment by mtias** [comment]
Correct, this doesn't really change how multi-selection works, only the visual feedback. There were some past explorations about proper partial selections but were more involved in implementation. It's still on the wishlist to resurface but it requires some time to dive through the writing flow components.

**Comment by getdave** [comment]
Thank you for raising this PR. I completely understand the motivation to fix the problem 👏 

Some quick debugging reveals that multi-selection appears to be handled in and around

https://github.com/WordPress/gutenberg/blob/262d4675532ead489a37bfb7957a84f9b3bd8817/packages/block-editor/src/components/block-list/use-block-props/use-multi-selection.js#L32

One of the first things I've noticed is that [the `MULTI_SELECT` action](https://github.com/WordPress/gutenberg/blob/262d4675532ead489a37bfb7957a84f9b3bd8817/packages/block-editor/src/store/reducer.js#L1299-L1304) only has fidelity down to a `clientId` level, whereas [the `SELECTION_START` action type](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/store/reducer.js#L1280-L1292) (used when making a selection within a single block) provides the offset values for where the selection starts and ends.

Hopefully someone with more experience in this area of the codebase can provide some additional insight and perhaps examples of previous explorations.

**Comment by hussain-t** [comment]
@Mamaduka Thanks for taking a look and reporting the deletion issue. I will try if I can find a fix for it. I have noticed another issue with this workaround. Once you delete the blocks the focus disappears.

Could anyone point where the deletion happens?

**Comment by hussain-t** [comment]
Thanks @mtias. I understand this is a workaround and not a perfect solution for the multi-selection issue :)

**Comment by hussain-t** [comment]
@getdave Thanks for taking a look at the PR.

**Comment by Mamaduka** [comment]
Hi, @hussain-t

This feature was added via https://github.com/WordPress/gutenberg/pull/38892. So I think we can close this PR.

Thanks again for contributing.

**Pull request closed without merging**
