### PR TITLE
Add color block support to latest posts

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Add color block support to the latest posts block.
Partial for https://github.com/WordPress/gutenberg/issues/34647.

## Why?

To allow customizing the colors.

## Testing Instructions

1. Apply the PR
2. Create a couple of posts, some with featured images, that can be used to test the latests posts block.
3. In the block editor, create a new post or page and add a latest posts block.
4. Try the block color options (also in combination with the other block options).
5. Save and view the post or page on the front.
6. confirm that the colors are applied and that the editor and front match.

## Screenshots or screencast 
Editor:
The block is selected and color options are visible in the block settings sidebar

Front
the latest posts block has a gradient background, text and link colors applied

### CODE REVIEW

**Review by aristath — APPROVED** [review]
LGTM! 👍

**Comment by carolinan** [comment]
@aaronrobertshaw Hi, this color support PR is from June, so it is not in the tracking issue.

**Comment by aristath** [comment]
@carolinan this PR needs to be rebased because there are currently some conflicts with trunk 👍 
Once rebased and all tests pass, I think we can go ahead and merge it.

**Comment by carolinan** [comment]
With spacing and colors combined:
latest posts block with color and spacing options enabled

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for adding color support here @carolinan 👍 

It's testing well for me.

✅ Theme.json
✅ Global styles
✅ Individual block styles 
✅ Displays consistently on both the frontend and editor

**Comment by aaronrobertshaw** [comment]
I've started re-running the failed test, as it looks unrelated. Feel free to merge once everything is green 🙂

**Pull request merged**
