### PR TITLE
Framework: Pin nvmrc to specific current LTS

### PR DESCRIPTION
**Pull request by aduth**
Related Slack discussion ([link requires registration](https://make.wordpress.org/chat/)): https://wordpress.slack.com/archives/C02QB2JS7/p1588794429373800

This pull request seeks to update `.nvmrc` to designate the actual current LTS version. This is intended to future-proof builds which occur when checking out an older version of the branch. Notably, this is an issue today when checking out old versions of Gutenberg, where we had used an older version of the [`node-sass` dependency](https://www.npmjs.com/package/node-sass) which only works in e.g. Node 10 or earlier. If, at the time, `.nvmrc` had specified `10` as the Node version of the project, it would not be as much an issue†. With these changes, we can at least try to correct this problem moving forward.

Note that the primary downside here is that we will need to manually update this value over time, as the LTS changes. Based on the [release schedule](https://nodejs.org/en/about/releases/), this should be expected to occur once every year (each October).

**Testing Instructions:**

Running `nvm install` should install Node v12.16.3:

```
nvm install --latest-npm && nvm use
```

**Follow-up tasks:**

† This only really helps if one knows to run `nvm install && nvm use` after checking out an older branch / commit. Ideally we can make this more seamless, or at least more noisy as part of checks prior to any actions we expect to depend on this behavior.

Example ideas:

- `post-checkout` git hook to run `nvm install && nvm use`
- Something similar to [this official documented automation](https://github.com/nvm-sh/nvm/blob/master/README.md#automatically-call-nvm-use) 
- Better integration with [`prebuild` `check-engines` step](https://github.com/WordPress/gutenberg/blob/70a4af60c50926b696787a7f74c7eb58eb31e37a/package.json#L188)
   - Specify `engines` in `package.json`?
   - Support `.nvmrc` in `check-engines`?

### CODE REVIEW

**Review by chrisvanpatten — APPROVED** [review]
Makes sense to me!

I also did some quick digging to compare this with tying to a specific LTS "codename" (e.g. `lts/erbium`) and it turns out internally `nvm` converts those names to the version number anyway, so there's no practical difference. If anything, this is clearer because the codenames aren't often used.

**Comment by chrisvanpatten** [comment]
I think this makes sense. One thought: is it worth documenting that this is expected to reflect the latest LTS release? Unfortunately it doesn't look like `.nvmrc` can accept comments, but it probably wouldn't hurt to make it explicit somewhere.

**Comment by aduth** [comment]
> One thought: is it worth documenting that this is expected to reflect the latest LTS release? Unfortunately it doesn't look like `.nvmrc` can accept comments, but it probably wouldn't hurt to make it explicit somewhere.

It would be nice if we could include a comment in the file, yeah. I dug a bit into the documentation and source code, and can't seem to find any indication of a syntax for supporting comments.

Where do you imagine it might make sense to document this otherwise? We do already have the expectation outlined in the "Getting Started" guide, but this is just the general expectation, not anything about `.nvmrc` and how it's managed:

>The first step is to install the latest active LTS release of Node, along with the latest version of NPM.

https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md

**Comment by chrisvanpatten** [comment]
How about something like this:

> Gutenberg is built using the latest active LTS release of Node, along with the latest version of NPM.
>
> The easiest way to install and manage node and NPM (on macOS, Linux, or Windows 10 with the Linux Subsystem) is by using nvm. Once nvm is installed, you can install the correct version of Node by running `nvm install --latest-npm` in the Gutenberg directory.
>
> This also makes it easier to build older versions of Gutenberg while ensuring you have the same version of node which was used at that time. Gutenberg's `.nvmrc` file is regularly updated to the current available LTS release, so `nvm install` on an older branch will use whichever LTS version was active at that time.

**Comment by aduth** [comment]
It reads nicely to me. My only hesitation is that this document is the entry point for new contributors, and is already pretty over-encumbered with information. While it's all certainly useful, some of it isn't particularly relevant for a new contributor's first steps (e.g. working in old branches).

**Comment by chrisvanpatten** [comment]
@aduth Maybe if it were formatted more like this:

---

Gutenberg is built using the latest active LTS release of Node, along with the latest version of NPM.

The easiest way to install and manage node and NPM (on macOS, Linux, or Windows 10 with the Linux Subsystem) is by using nvm. Once nvm is installed, you can install the correct version of Node by running `nvm install --latest-npm` in the Gutenberg directory.

> **Note:** If you find yourself needing to build older versions of Gutenberg, `nvm` make that process easier. Because Gutenberg's .nvmrc file is regularly updated to the current available LTS release, running `nvm install` on an older branch will install whichever LTS version was active at that time.

...

---

I also simplified the language a bit to reflect that this is intended for new contributors.

**Comment by whyisjake** [comment]
Related: #22120 and #22121.

**Comment by whyisjake** [comment]
Also related: https://core.trac.wordpress.org/ticket/50094

**Comment by aduth** [comment]
> @aduth Maybe if it were formatted more like this:

Thanks @chrisvanpatten . It seems like a nice balance of information. I think it also does a good job to consolidate / highlight the expected versions of Node/NPM in that introductory sentence. 

Separately, something about the existing "Python requirement" paragraph stands out to me as disjointed. I don't think it's directly related to what's being modified here, so maybe consider as a separate task.

**Review by chrisvanpatten — APPROVED** [review]

**Pull request merged**
