### PR TITLE
Add html generation for photo type embed previews

### PR DESCRIPTION
**Pull request by notnownikki**

### CODE REVIEW

**Comment by mkaz** [comment]
Works as expected, looks good :+1:

**Review by mkaz — COMMENTED** [review]
Looks good, works as expected :+1:

**Review by aduth — CHANGES_REQUESTED** [review]
One moment, I have a possible concern here I'd like some time to explore.

**Comment by aduth** [comment]
XSS is fun:

1. Navigate to Gutenberg
2. Insert Embed block
3. Insert as URL: http://i1070.photobucket.com/albums/u489/aduthie7/sad-baby_zpsnscz2ovs.jpeg
4. Click Embed
5. Get hacked

This is one benefit of using React elements over concatenating strings.

In this case, we __must not__ allow user values to be inserted into the generated markup.

**Comment by notnownikki** [comment]
@aduth aha, I did try to find a service where that was a problem, but it looked like the embed API returned safe values. Thanks for finding one that didn't, will change things :smile:

**Comment by notnownikki** [comment]
Ok, switched to JSX for the photo preview. I was under the impression that the embed API supplied clean values, but now I see it was actually cloudup sanitising things.

**Comment by aduth** [comment]
One-off sanitization scares me a bit. I'm looking at `HtmlEmbed` and wondering if we should be doing more [sandboxing](https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/). I'm also curious to know if the oEmbed endpoint performs [discovery](https://codex.wordpress.org/Embeds#What_About_oEmbed_Discovery.3F), which would open up `html` to be injected by any properly-configured website.

**Comment by notnownikki** [comment]
Yes, we absolutely should be doing sandboxing, but it's difficult. On the initial version of this block, we agreed that we'd just inject the html into a div for now, so we could get the block working, and look at sandboxing once it was done.

I do not like the current implementation of HtmlEmbed, but the amount of work needed to get sandboxed iframes working correctly is not a small amount. Calypso has a resizing iframe, but it does not work by itself, there is more code needed to correctly calculate the height of embedded content for previews, and that code needs to be looked at and brought over into the HtmlEmbed component. It's not simple :( I'm looking at it though.

**Comment by notnownikki** [comment]
I opened https://github.com/WordPress/gutenberg/issues/1348 to track the sandboxing issue.

**Comment by notnownikki** [comment]
Got the ok from @mtias to merge this, as long as we're working on the sandboxing.

**Pull request merged**
