### PR TITLE
Centralize constants for the navigation block.

### LINKED ISSUE #50183: Extract Nav block allowed inner blocks to constant and reuse across controlled and uncontrolled inner blocks files
We should normalize these lists to a single `const` and import into the relevant files.

_Originally posted by @getdave in https://github.com/WordPress/gutenberg/pull/49160#discussion_r1180480317_

### PR DESCRIPTION
**Pull request by juanfra**
## What?

Centralize constants for the navigation block. 

Fixes https://github.com/WordPress/gutenberg/issues/50183

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
Looking good 👍 Thanks for the PR!

Could we [rebase this](https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/git-workflow.md#keeping-your-branch-up-to-date) against upstream `trunk`?

Once done we should be good to merge?

**Comment by getdave** [comment]
cc @scruffian here as I think we was working on something similar.

**Review by scruffian — APPROVED** [review]
Let's rebase and merge!

**Comment by juanfra** [comment]
Thanks!

**Comment by getdave** [comment]
Thank _you_ 🙇

**Pull request merged**
