### PR TITLE
Remove "max-width" from PanelRow label to fix the styling of the RangeControl when inside a PanelRow.

### PR DESCRIPTION
**Pull request by kmgalanakis**
## Description
The change I'm undoing was introduced in https://github.com/WordPress/gutenberg/pull/3786. This change creates an in issue on the rendering of `RangeControl`, as it's described in https://github.com/WordPress/gutenberg/issues/4402.

## Screenshots (jpeg or gifs if applicable):
before_after

before_after_rc

As it's seen, my change doesn't affect the selects with long names in sidebar but fixes the styling issue of a `RangeControl` inside a `PanelRow`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by laras126** [comment]
@aduth Yes – that max-width is there to force a long label to wrap instead of squishing the select, e.g. this is a long label _without_ max-width: 
squished select

@kmgalanakis – Maybe adding a wrapping element around the input and the range would help? That may make the flexbox respond more appropriately, or you could give that a width 100% to ensure it falls below the label. 

Another option would be to scope the max-width style by adding an additional class to `components-panel__row` for simple inputs.

Also noting @karmatosed's response to #4402.

**Comment by kmgalanakis** [comment]
@laras126 I followed your first suggestion but couldn't make it work properly.

As far as your second suggestion is concerned, I'm not sure I totally understand what needs to be done there.

@aduth using the current codebase, I couldn't reproduce https://github.com/WordPress/gutenberg/issues/3432. Maybe another change after that, made the `max-width` change obsolete.

**Comment by aduth** [comment]
@kmgalanakis Can you verify whether this note in @laras126 still holds true after removing the `max-width` ?

>Yes – that max-width is there to force a long label to wrap instead of squishing the select, e.g. this is a long label without max-width:

**Comment by kmgalanakis** [comment]
@aduth if I get her comments straight, yes, it holds even after removing the `max-width`.

I would really appreciate, though, if @laras126 could verify that.

**Comment by jasmussen** [comment]
This is an old fork! I do apologize for not getting to review this sooner, and thank you for your PR. 

It was a big hard to reproduce the issues, but as far as I can tell, both situations work when I tested this. Maybe worth getting in, then just being mindful of any regressions with wrapping?

**Comment by coreymckrill** [comment]
I can confirm that the styling issue with a `RangeControl` inside a `PanelRow` is still happening in 3.6.2.

**Comment by karmatosed** [comment]
I would add a note, this is good to get in if we can get the PR refreshed as there seem conflicts. I am like @jasmussen conscious of regression here. That said let's test thoroughly and be sure before merge.

**Pull request closed without merging**
