### PR TITLE
Clean the patterns list to include in core

### PR DESCRIPTION
**Pull request by youknowriad**
Reduce the available patterns on the plugin to prepare for inclusion on Core and keep only non-opinionated ones. Still a work on progress. Also, make the patterns fully translatable.

### CODE REVIEW

**Comment by carolinan** [comment]
Is this set? I really liked the testimonials pattern.

**Comment by youknowriad** [comment]
I personally don't have an opinion but I'd like to move quickly with this to be ready for beta1

**Comment by shaunandrews** [comment]
image

Seeing the Image block placeholders in the previews is really strange. I suggest we show real images (at least in the example previews), or we remove the patterns with images. To be honest, the two patterns with images ("Two columns of text with images" and "Three columns of text with images & buttons") are not super compelling, and could just be removed.

image

I find the "Large header & two columns of text" pattern to be duplicative; Its just two of the other patterns combined, and I'm not sure why it exists.

Also, I've noticed that none of the patterns are showing at full width in the inserter panel — this leads to alignment issues with centered text and buttons. Its possible this is outside the scope of this PR, but felt worth mentioning.

**Comment by enriquesanchez** [comment]
Thanks for the feedback @shaunandrews!

>Also, I've noticed that none of the patterns are showing at full width in the inserter panel 

I'm not seeing this, @youknowriad can you confirm?

**Comment by enriquesanchez** [comment]
>Is this set? I really liked the testimonials pattern.

I added it back, but with just two testimonials instead of three for simplicity.

**Comment by youknowriad** [comment]
The last changes here reverted the translations I added previously, can we restore these?

**Comment by enriquesanchez** [comment]
>The last changes here reverted the translations I added previously, can we restore these? 

My apologies @youknowriad, this was an oversight! I'll restore them asap.

**Comment by youknowriad** [comment]
Thanks Enrique, no worries, I would add them back myself but these little things take time to get right :P

**Comment by enriquesanchez** [comment]
@youknowriad 

Would you happen to know how to fix this error?

```
FILE: /app/lib/patterns/quote.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 10 | ERROR | [x] String "</p><cite>" does not require double quotes;
    |       |     use single quotes instead
    |       |     (Squiz.Strings.DoubleQuoteUsage.NotRequired)
```

As far as I can tell, those quotation marks are needed 🤷‍♂️

**Comment by youknowriad** [comment]
yes Enrique, I'll fix these.

**Comment by youknowriad** [comment]
This is looking very good 👍 Thanks Enrique

**Comment by mtias** [comment]
@carolinan I think it'd be great to include more Quote and Testimonial related patterns, but one issue with the testimonials one is that it's compiled using a paragraph block, not a quote, so the semantics we'd be promoting could be a bit problematic. There are also some smaller issues with the avatar placeholder not being retina, the name and image not being vertically aligned, etc.

**Comment by carolinan** [comment]
OK, sounds valid :).. maybe later ;)

**Comment by enriquesanchez** [comment]
I've removed 'Testimonials' for the reasons outlined above.

**Comment by youknowriad** [comment]
I know this is not perfect and designers are iterating on the patterns for 5.5 but let's get this as v1.
This Core trac ticket will serve as a tracking ticket for this task https://core.trac.wordpress.org/ticket/50550

**Pull request merged**
