### PR TITLE
Reduce specificity of global styles body margin reset rule.

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Follow-up to #60106, which reduced the specificity of global styles rules generated from theme.json and user settings. Because any base styles defined in theme.json are now output under `:where(body)`, the `body` rule that resets margin to 0 will override any margins defined in theme.json.

This PR reduces the specificity of the body margin reset (it still overrides user agent styles at zero specificity) so it doesn't interfere with theme-defined styles.

Props to @dsas for bringing this to my attention!

## Testing Instructions

1. In your theme's theme.json, add some values under `style.spacing.margin`, e.g. `"top": "20px", "bottom": "20px"`
2. Check that those values are overridden on trunk, but not in this PR branch.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Great catch, I didn't realise that you could even set root margin spacing since we don't have a control for it in global styles! But editing the `theme.json` manually and adding the margin rules works nicely with this PR applied in both the post and site editors and on the site frontend.

image

LGTM! ✨

**Review by ramonjd — APPROVED** [review]
Not as fast as Andrew 😄  but can confirm that the specificity is lowered and styles apply as expected 👍🏻 


Screenshot 2024-05-03 at 11 24 42 am


Screenshot 2024-05-03 at 11 26 14 am

**Comment by pbking** [comment]
I just cherry-picked this PR to the release/18.3 branch to get it included in the next release: 46c1ecb29d

**Comment by Mamaduka** [comment]
@tellthemachines, I think this change caused a regression for non-iframed editors reported here: #61565 and #61582.

**Pull request merged**
