### PR TITLE
Split paragraphs immediately on ENTER

### PR DESCRIPTION
**Pull request by ellatrix**
This PR changes the behaviour of the text/paragraph block. Now pressing ENTER will immediately split the block instead of allowing one line break inside the paragraph. SHIFT+ENTER will now create a line break instead of splitting the block immediately.

### CODE REVIEW

**Comment by spocke** [comment]
Nice. I think this approach makes a lot more sense for enter behavior.

**Comment by iseulde** [comment]
Not sure why the tests failed...

**Comment by iseulde** [comment]
Is there any way to force another run?

**Comment by youknowriad** [comment]
@iseulde weird, I used to be able to restart a job. I can't do it anymore

**Review by youknowriad — APPROVED** [review]
Anyway, I really like this behaviour 👍

**Comment by nylen** [comment]
> weird, I used to be able to restart a job. I can't do it anymore

Same.  I bet @pento broke it

**Comment by pento** [comment]
@youknowriad, @nylen: Could you try visiting your respective Travis CI profile pages, and clicking the "Sync account" button? I had to do the same, it was fine after that.

**Comment by youknowriad** [comment]
I see the "restart job" button again without doing anything 🤔

**Comment by nylen** [comment]
> I see the "restart job" button again without doing anything 🤔

Same, seems fine now.

**Comment by iseulde** [comment]
@m Sorry about the change! I'm really fine with it either way...

**Comment by mor10** [comment]
FWIW this is the correct handling of Enter keypresses. Enter alone should always generate a new paragraph in HTML. Shift+Enter generates a line break. This is a universal standard across all word processing applications which is what WP tries to emulate with a WYSIWYG editor.

**Comment by aduth** [comment]
@m Can you elaborate on the reaction? This was a major topic for an editor office hours conversation, during which we were hard-pressed to find use cases for when a single line break would be the desired behavior. 

https://wordpress.slack.com/archives/C02QB2JS7/p1500483704729747

While creating a new editor gives us some flexibility to establish new patterns, if the widespread convention across other editors is to split paragraphs on the single enter press, won't new users arrive with this expectation and find the disjunction to be disruptive?

**Pull request merged**
