### PR TITLE
Fix latest posts excerpt escaping

### LINKED ISSUE #38515: Latest posts block's read more link gets rendered as plain text in frontend
### Description

Just noticed that with the newest version of the plugin the read more link isn't a link anymore.

### Step-by-step reproduction instructions

Add a latest posts block, set content to excerpt and grid view.

### Screenshots, screen recording, code snippet

image

image

### Environment info

Newest WP and Gutenberg Plugin, theme twentytwentyone, no other stuff active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## Description

Overzealous escaping of Latest Posts block caused the bug in https://github.com/WordPress/gutenberg/issues/38515.

This PR fixes https://github.com/WordPress/gutenberg/issues/38515.

## Testing Instructions

1. Install and activate TT1 (classic!).
2. Add some posts with some content. I used Fakerpress Plugin to generate this for me.
3. New Post - add following content:

```
<!-- wp:latest-posts {"displayPostContent":true,"excerptLength":10,"displayAuthor":true,"displayPostDate":true,"postLayout":"grid","displayFeaturedImage":true} /-->
```

4. Publish and view post on front of site.
5. See "Read more" excerpt is no longer output as HTML.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by getdave** [comment]
@Azragh Does this fix the Issue you reported?

**Comment by Mamaduka** [comment]
@getdave it looks like PR has extra commits 😄

**Comment by getdave** [comment]
Yeh. How did that happen 🤔 Let me sort that.

**Comment by getdave** [comment]
@Mamaduka Ok fixed ✅

**Comment by Azragh** [comment]
@getdave wow that went fast. can't test atm but will look into it asap.

**Review by draganescu — APPROVED** [review]
Tested and works as described.

**Pull request merged**
