### PR TITLE
Post author name: Add "post" prefix to CSS class

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Updates a CSS class that was missed when the block changed name from "author name" to "post author name".

## Testing Instructions

1. Open a Post or Page.
2. Insert a post author name block
3. Enable the link option in the block settings sidebar
4. View the front. View source. Confirm that the class name on the link is "wp-block-post-author-name__link"

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by aristath — APPROVED** [review]
There was a failing test but I don't believe it's related to this PR 'cause I've seen the same test fail in other PRs lately.
I rebased the PR, hopefully that will fix the issue.
The code looks good and does what it's supposed to do, so I'll go ahead and pre-approve this so it can be merged once all tests pass 👍

**Comment by carolinan** [comment]
We don't need to keep the old class name for compatibility, right? It's still experimental, I think the impact is minimal.

**Comment by aristath** [comment]
> We don't need to keep the old class name for compatibility, right? It's still experimental, I think the impact is minimal.

I concur.

**Comment by carolinan** [comment]
I moved the block from `const __experimentalGetCoreBlocks` to `const __experimentalRegisterExperimentalCoreBlocks`, experimental blocks.

**Comment by carolinan** [comment]
Meh, I clearly messed that move up while trying to resolve the merge conflict in the GitHub ui.

**Comment by carolinan** [comment]
@talldan Did I move the block to the correct section? (Experimental)

**Review by scruffian — APPROVED** [review]
This looks good to me and it fixes https://github.com/WordPress/gutenberg/issues/39095

**Pull request merged**
