### PR TITLE
Block editor: use proper insertion point for drop

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Currently an insertion point is added through a block class for drop on a block list. We should use the insertion point component for this instead, used by the inserter.

Additionally, the appender is currently used as an insertion point, which shouldn't be used as in some contexts there may be no appender.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
Great to see these two similar systems reduced to one. I gave the PR a test and noticed that sometimes when dragging a block the sibling appender is showing over the insertion point (reproduced in Firefox):
dropzones

The positioning horizontally of the sibling appender also doesn't look right, though I couldn't get it to trigger in the navigation block outside of the drag and drop bug.

**Comment by ellatrix** [comment]
Thanks for testing!

**Comment by youknowriad** [comment]
Oh I missed this PR, there might be some duplication with https://github.com/WordPress/gutenberg/pull/27860

**Comment by ellatrix** [comment]
Continuing in #29933.

**Pull request closed without merging**
