### PR TITLE
Modal: Fix sticky header when rendering Modal with overflow content

### PR DESCRIPTION
**Pull request by ItsJonQ**
This update fixes the "stickiness" of the Modal header when rendering very tall content within the Modal body.
This issue was recently discovered in the [Preferences Modal PR](https://github.com/WordPress/gutenberg/pull/28329#issuecomment-763798698)

The solution involved swapping the CSS rule `height: 100%` to `min-height: 100%`.
This achieves the requirement of forcing the content height of the Modal frame.
However, it also allows for the content height to "grow", providing more space for the "sticky" header.

GIF demo of solution:

Screen Capture on 2021-01-21 at 08-22-59

## How has this been tested?

Locally on Gutenberg

* npm run dev
* Open the Keyboard Shortcuts modal
* Ensure it still works

Bonus:

Adjust one of the contents of that modal to have a height of `200vh`, making it very tall.

Screen Shot 2021-01-21 at 8 32 07 AM

Ensure the sticky header still works.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Yep, this seems good to me. But I wonder, did you find any context in the file history for why it was height vs. min-height? I feel like in the back of my memory there was a reason for it. Was there an overflow property attached to the container? What happens if there's no height or min-height attached?

**Comment by ntsekouras** [comment]
>What happens if there's no height or min-height attached?

While trying to make sticky `block manager` elements in: https://github.com/WordPress/gutenberg/pull/28329, before leaving it for a follow up, by having no height defined at all, makes `sticky` not to work. So it seems that there is the need for at least a `min-height:0` for something `sticky` to work.

That was my `fix` for resolving this, but I was overriding in the specific modal. Also by having this change, I couldn't make the sticky work well for inner elements.

I'm not css expert though... :)

**Comment by ItsJonQ** [comment]
Are you folks 👍 on me merging this one? :D

**Comment by mirka** [comment]
Thanks for working on this! We've been cleaning up stale PRs, and it looks like this issue was already fixed. Closing out for now 🙏

**Pull request closed without merging**
