### PR TITLE
Update docs manifest

### PR DESCRIPTION
**Pull request by swissspidy**
Tests are currently failing because the docs manifest isn't up to date.

I just ran `npm run docs:build` to fix this.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]

**Comment by swissspidy** [comment]
The build failures are unrelated and known, see https://wordpress.slack.com/archives/C02QB2JS7/p1545052471047000

**Comment by tofumatt** [comment]
Looks like this is superseded by #12980, so I'm gonna close this one, but thanks for the PR! 😄

**Comment by swissspidy** [comment]
@tofumatt #12980 is this PR...

**Comment by tofumatt** [comment]
😅 Oops, I meant #12983. Updated the original comment; my bad!

**Pull request closed without merging**
