### PR TITLE
Framework: Adding withInstanceId Higher Order Component

### PR DESCRIPTION
**Pull request by youknowriad**
Several components needs to generate an instanceId for HTML ids etc... In this PR I'm adding a `withInstanceId` Higher Order Component providing the instanceId as a prop.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Would perhaps like to have seen tests and a `README.md`, but otherwise can confirm this looks and works well 👍

**Comment by nb** [comment]
Do we need another HOC, can’t we solve this with `this.id = uuid();` in the component’s constructor? This way we won’t need the state and will be simple enough to be self-contained and easy enough to online.

For the record, since c2732e7203b458f09f8452c3c85862bdb7f64fe4 visual editor block instances receive `id` as part of their props.

**Comment by youknowriad** [comment]
> Do we need another HOC, can’t we solve this with this.id = uuid(); in the component’s constructor? 

@nb We need a constructor to do so, which forces us to use the class component syntax and I'd much rather prefer the functional components unless we explicitly need refs, state or lifecycle methods.

--
I've added a unit test and some documentation.

**Comment by nb** [comment]
A class isn't so bad, so I’d still personally prefer less HOCs simply, because this way we need to communicate one less thing (what does this `withInstanceId` do and where does `instanceId` come from), but I don’t have strong opinion. Don’t mind me and carry on :)

**Comment by youknowriad** [comment]
Another difference with the `uid` is that it's component-specific, maybe this difference is not that important tough.

Thanks for the discussion, I'm merging now. This PR also bootstraps the Higher-Order Components Documentation. If the concern is raised again, we could revisit.

**Comment by aduth** [comment]
>I’d still personally prefer less HOCs simply, because this way we need to communicate one less thing

I'm sympathetic to the "one less thing" argument, but higher-order components are a pretty fundamental pattern for shared component behaviors. In fact, I'd worry that shielding developers from the concept could be a disservice in, for example, understanding what something like `connect` is doing (creating a new modified component wrapper) vs. merely repeating the pattern (it's a thing that injects props by _magic_).

**Comment by nb** [comment]
We’re on the same page about `connect` for sure. To me, the one-line ID generation is on the other side of the useful/indirection tradeoff.

**Pull request merged**
