### PR TITLE
Scripts: Add `--dist-tag` flag to the `packages-update` command

### PR DESCRIPTION
**Pull request by gziolo**
## What?

Alternative to and potentially closes #36005.
Related to https://github.com/WordPress/gutenberg/issues/35630.
Related to #24376.

Adds `--dist-tag` flag to the `packages-update` command to allow specifying a custom dist-tag when updating npm packages.

## Why?

This is especially useful when using [`@wordpress/dependency-extraction-webpack-plugin`](https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin). It lets installing the npm dependencies at versions used by the given WordPress major version for local testing, etc. Example: `wp-scripts packages-update --dist-tag=wp-6.0`.

## Testing Instructions

I tested with a custom block that has `@wordpress/scripts` installed (inception 🙃). However, I used the version from this branch located in the Gutenberg repository:

```sh
cd my-block
../gutenberg/node_modules/.bin/wp-scripts packages-update --dist-tag=wp-6.0
../gutenberg/node_modules/.bin/wp-scripts packages-update
```

## Screenshots or screencast 

Screenshot 2022-04-21 at 13 47 52

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
Awesome enhancement it will make the release process and the patch releases much simpler 👍

**Comment by adamziel** [comment]
This was backported to wp/6.0 branch to be included in WordPress 6.0 Beta 3 tomorrow: 73e2443ca935c27551a367728c0dc8223a25db0d

**Comment by bph** [comment]
_changed my mind about `needs dev note` because this was already merged for WP 6.0_

**Comment by adamziel** [comment]
Plus this is relevant mostly for the release leads.

**Pull request merged**
