### PR TITLE
Fix broken links to the block editor developer handbook

### LINKED ISSUE #29662: Fix broken links on developer.wordpress.org/block-editor
## Description
After merging the new table of content of the block editor developer handbook and changing the files/folders structure (https://github.com/WordPress/gutenberg/pull/28665), there are some broken links that were not caught during the process.

This issue track these links to fix them.

The list of the broken links can be found here https://docs.google.com/spreadsheets/d/11-AnXMjwjt7k2LGm2uLr-UlTemTxuCg_UUEb6lFsaXM/edit?usp=sharing. Anyone feel free to report if you spot one.

### PR DESCRIPTION
**Pull request by JustinyAhin**
Fixes https://github.com/WordPress/gutenberg/issues/29662.

### CODE REVIEW

**Comment by talldan** [comment]
@JustinyAhin I think the newly added page for Block Variations is now also missing from the handbook:
https://github.com/WordPress/gutenberg/pull/29515

At least I couldn't see it (cc @ntsekouras)

**Comment by JustinyAhin** [comment]
> @JustinyAhin I think the newly added page for Block Variations is now also missing from the handbook - #29515
> 
> At least I couldn't see it (cc @ntsekouras)

I just added it in https://github.com/WordPress/gutenberg/pull/29663/commits/c064acf3e27e5b47eb5996feb7a8fcc884cd15db

**Comment by JustinyAhin** [comment]
If you look at the homepage, you’ll see these two "Getting Started"

CleanShot 2021-03-09 at 15 55 38@2x


It is a bit weird because the first lines of toc.json (https://github.com/WordPress/gutenberg/blob/trunk/docs/toc.json#L2) say there should be an only one "Getting Started" page with "Tutorials" as subfolder and `glossary`, `faq`, etc... as single pages.

I assume this is duplicated because there is another page with the same slug.  I tried to fix it in https://github.com/WordPress/gutenberg/pull/29663/commits/93e92afe0ae447a2a24b1d1d84b55fb6bff8ca4d.

cc @mkaz do you have any idea/input about this?

**Comment by mkaz** [comment]
The first getting started is from the title of the `docs/readme.md`

The second Getting Started is the section from: `docs/getting-started/README.md`

**Comment by JustinyAhin** [comment]
> The first getting started is from the title of the `docs/readme.md`
> 
> The second Getting Started is the section from: `docs/getting-started/README.md`

Ok, i think I get it now. Thanks :)

**Review by mkaz — APPROVED** [review]
Thanks for finding and fixing the links 👍 

Let's merge these in, since its a good first pass and we can continue to find additional and update as we go.

Thanks for tackling the reorg issue, I've wanted to do it for awhile but knew it would be messy and didn't quite have the courage to do so. So appreciate you "ripping the band-aid off" and getting the update. out.

**Comment by ntsekouras** [comment]
Thanks for handling this!

>@JustinyAhin I think the newly added page for Block Variations is now also missing from the handbook - #29515

I didn't see the link for block variations here: https://developer.wordpress.org/block-editor/reference-guides/block-api/

**Pull request merged**
