### PR TITLE
Don't set font-style when using dropcap (#6284)

### PR DESCRIPTION
**Pull request by davisshaver**
See https://github.com/WordPress/gutenberg/issues/6284

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Related https://github.com/WordPress/gutenberg/pull/6133#issuecomment-381334721

The style came in an uber-commit (8dfc4c51d29c8bcfc799eb335a87085cf8ece5b9) and it's not clear what the original source is.

**Comment by aduth** [comment]
This was moved from `RichText` to `core-blocks/paragraph/style.scss` in fcecbb2b83a0fcd3f4d4b6da5964f929b6c8dc31.

**Comment by karmatosed** [comment]
Drop cap should not be adding a style like this so 👍 from me on fixing this.

**Comment by davisshaver** [comment]
@karmatosed updated!

**Review by aduth — APPROVED** [review]
👍

**Pull request merged**
