### PR TITLE
Gallery Block: Cleanup v1 code

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

While working on unrelated PRs, I found that the Gallery V1 code is still around and if I'm not wrong, this code is not needed anymore. 

I'm certain that it's not needed in web but have a small doubt for native, although given the time passed since the release of V2, I expect that it's not needed anymore but would need confirmation. cc @geriux @fluiddot 

## Testing instructions

There should be no functional change and the gallery block should work just like today.

### CODE REVIEW

**Comment by geriux** [comment]
Hey 👋 I'll test this a bit today but I yeah I agree on removing it 🙌

**Comment by geriux** [comment]
@youknowriad is it ok if I push some changes to this branch?

**Comment by youknowriad** [comment]
Yes, please go ahead. Thank you :)

**Review by geriux — APPROVED** [review]
LGTM! Thanks for working on this! 🚀

**Comment by youknowriad** [comment]
Nice thanks for the help.

**Pull request merged**
