### PR TITLE
Support custom units on theme.json

### PR DESCRIPTION
**Pull request by youknowriad**
Related #20588
Alternative to #24873
Similar to #24761 but for custom units.

The idea of this PR is to support configuring custom unit support from theme.json.

**Testing instructions**

* Check that you can config custom units using the theme.json `spacing.units` path.
* Check that you can still use the `custom-units` theme support flag.
* Check that it's opt-out now.

### CODE REVIEW

**Comment by youknowriad** [comment]
The dev note is needed because it's opt-out now.

**Comment by youknowriad** [comment]
Any reviews here @ItsJonQ @nosolosw thanks :)

**Comment by ItsJonQ** [comment]
@youknowriad Reviewing now! 🙏

**Review by ItsJonQ — APPROVED** [review]
@youknowriad Amazing! Moving things to the `theme.json` way is a breath of fresh air. Tested this locally, and it is working. I tried both disabling, adding custom units, and using just the default settings.

It was helpful for me to see the conversion of `add_theme_supports` to the new `editorFeature` method via `theme.json`.

Thanks a bunch!

**Review by aristath — APPROVED** [review]

**Pull request merged**
