### PR TITLE
Fix link color selector

### PR DESCRIPTION
**Pull request by oandregal**
Reported by @carolinan 

## How to repro

Using a theme with support for theme.json v1, add this to the `styles.blocks` section:

```
"core/post-date": {
    "elements": {
        "link": {
            "color": {
                "background": "#111",
                "text": "#333"
            }
        }
    }
}
```

The expected output is:

```css
.wp-block-post-date a { background: #111; }
.wp-block-post-date { --wp--style--color--link: #333; }
```

What actually happens instead is:

```css
.wp-block-post-date a { background: #111; }
.wp-block-post-dte { --wp--style--color--link: #333; } /* Note how the "a" was removed from the selector */
```

### CODE REVIEW

**Comment by oandregal** [comment]
I think this should be part of a 10.6.X patch release, so milestoned it accordingly.

**Comment by youknowriad** [comment]
Hi @nosolosw What's the story of the CSS variable? When can we generate this instead:

```
.wp-block-post-date a { background: #111; color:  #333; }
```

**Comment by jorgefilipecosta** [comment]
> Hi @nosolosw What's the story of the CSS variable? When can we generate this instead:
> 
> ```
> .wp-block-post-date a { background: #111; color:  #333; }
> ```

Hi @youknowriad,

The PR https://github.com/WordPress/gutenberg/pull/31524, will remove the usage of the CSS variable. It should be ready but it was not approved yet, and its something major so probably should not be part of a patch release and we should merge this PR first.

**Review by jorgefilipecosta — APPROVED** [review]
Fixes the issue in my tests 👍

**Pull request merged**
