### PR TITLE
Newly created paragraph block is not showing the font size.

### PR DESCRIPTION
**Pull request by andreyc0d3r**
Newly added paragraph block is not showing the font size. 

The font size is not set for components-range-control__number element. This commit fixes the issue.

### CODE REVIEW

**Comment by aduth** [comment]
As I understand it, this may have been an intentional choice to not have an explicit size assigned for the paragraph, but rather to inherit the size which would otherwise apply by default there, since 16px may not be the default depending upon the theme.

**Comment by aduth** [comment]
Related: #5269

@mtias , having introduced this, can you clarify whether it was intentional to not explicitly tie the default size to a fixed numeric value?

**Comment by gziolo** [comment]
I don't think this is expected to enforce the default size for all Paragraph blocks. As far as I remember from discussions with @jorgefilipecosta, it is possible to provide a different size using CSS, and we are able to detect it and set proper value, i.e. if a theme author changes the default font size to 17px, it will be set as a default value, but it won't force the block to append a class name or style which would duplicate the information. @jorgefilipecosta, can you confirm?

**Comment by jorgefilipecosta** [comment]
The size number field field is blank to indicate to the user that no choice regarding the font-size was mad.
By default not setting a font-size may render 16px, but if we change to another theme the default size may be other and paragraphs with the default size may change the size. Where if we change the font size to 16px explicitly if we change theme that value may not be the same as the default one.

We may improve this if we find a UI that allows the user to know the default font-size value e.g: 16 px but also shows that this value was not set it is just a default in that scenario and may change (something identical to a placeholder in a text field).

**Comment by aduth** [comment]
Based on previous comments, closing this pull request as invalid. Thanks for the contribution and for prompting the discussion!

**Pull request closed without merging**
