### PR TITLE
Change subhead to say subheading

### PR DESCRIPTION
**Pull request by karmatosed**
Try branch for #5790.
Props @afercia

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
I think we should also update block's name, file name and everything that uses the old name. Not sure if `core/subhead` is an easy change in terms of backward compatibility.

**Comment by karmatosed** [comment]
@gziolo ah ok I didn't go deeper than copy as wasn't sure. Let me dive more! Thanks.

**Comment by karmatosed** [comment]
> Not sure if core/subhead is an easy change in terms of backward compatibility.

I think this isn't and I found with changing things too much things imploded a little. What would be the basics I should change as a 'worst case'?

**Review by gziolo — APPROVED** [review]
I asked @youknowriad if there is an easy way to update `core/subhead` to `core/subheading`. He suggested using similar solution to:
https://github.com/WordPress/gutenberg/blob/master/blocks/api/parser.js#L231-L234

However, it doesn't work with Subheading because it uses auto-generated `className` for the block and it breaks all the existing blocks.

I would limit this change to what we already included.

**Comment by aduth** [comment]
>I would limit this change to what we already included.

Would that mean changing the file name back to `subhead/` if we're keeping with the `core/subhead` technical name?

**Comment by karmatosed** [comment]
Just looping back but some feedback on this is that it may be preferred to be called subtitle. Before we change things here we should make sure there's a decision in that issue #5790

**Comment by aduth** [comment]
I think the slug and the folder name should match. Ideally the slug and the canonical "title" align, though there's already a few cases of precedent where we've been fine to diverge: namely the "Classic" block (`core/freeform`) and "Shared Block" block (`core/block`). In both of these cases, the directories still align with the actual slug, regardless of its human-readable named title.

**Comment by gziolo** [comment]
@karmatosed @aduth - this PR was updated to contain only text changes as discussed. As soon as it's decided what name this block should have, those texts should be updated. We can also add the old name as `key` in block's definition to improve discoverability.

**Review by aduth — APPROVED** [review]
Code-wise 👍

**Comment by gziolo** [comment]
> Because of keyword issues on headings where subtitle is a keyword already, for now lets go with subheading and close this. It is a fairly easy change to iterate on.

Subheading it is 👍

**Pull request merged**
