### PR TITLE
Icons: Update "close small" icon so that its shape matches the "add" icon dimensionally

### PR DESCRIPTION
**Pull request by jameskoster**
Before:

Screenshot 2021-03-19 at 09 47 49

Screenshot 2021-03-19 at 09 51 50

After:

Screenshot 2021-03-19 at 09 49 50

Screenshot 2021-03-19 at 09 52 43

This helps create harmony across the set, particularly is https://github.com/WordPress/gutenberg/pull/29759 lands.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Details matter. Nice.

I'm a bit curious why the filesize diff is so much bigger — did the new SVG add a bunch of points? 12 should be enough if I'm counting correctly?

But that's a small thing. Ship it.

**Review by aristath — APPROVED** [review]

**Comment by jameskoster** [comment]
@jasmussen I think it's because the old version is two strokes (4 points) whereas the new one is an outlined shape (12 points).

Using an outlined shape means the "stroke" will scale along with the size of the icon instead of remaining consistent:

Screenshot 2021-03-22 at 11 08 40

I'm not exactly sure which is the preference here. Different icons behave differently in this respect currently.

**Comment by jasmussen** [comment]
Oh definitely should be an outline shape!

Edit: that was unclear.

It should definitely be an _outlined_, i.e. solid, shape. So your change is preferable.

**Comment by jasmussen** [comment]
☝️ Edited, because my previous comment was unclear :D

**Comment by david-szabo97** [comment]
You need to run `npm run test-unit -- -u` to update the test snapshots. Then commit those files.

**Comment by david-szabo97** [comment]
Looks like you need to run `npm run test-e2e -- -u` to update E2E snapshots too

**Comment by jameskoster** [comment]
Tried that, no files were updated 🙈

**Pull request merged**
