### PR TITLE
Fix alignment of notice lists in block placeholders

### LINKED ISSUE #19671: Block Placeholder: Notices
**Describe the bug**
Notices look off in the new block placeholder:
Screenshot 2020-01-15 at 14 42 06

**To reproduce**
1. Add a block that uses notices in the placeholder
2. Make an error happen
4. The padding around the notice looks wrong

**Expected behavior**
In the old design Notices looked fine in this contect

**Screenshots**
Screenshot 2020-01-15 at 14 42 06

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Additional context**
- Please add the version of Gutenberg you are using in the description: Lateset

### PR DESCRIPTION
**Pull request by p-jackson**
## Description

This change updates the margins of the notice UI added to block placeholders using the `withNotices` mixin. The update was necessary after #18745 which made the content of block placeholders left-aligned.

Fixes #19671

## How has this been tested?

- Get the File block into error state by uploading an invalid file and then look at the rendered output to observe any layout issues.
- Tested with File block in column layout
- Tested mobile width
- Safari, FF and Chrome on Mac
- Viewed the fix in [a testing block](https://gist.github.com/p-jackson/fe601434d0ab5202387f9799ebae184e) with no other content but the placeholder. This was to check that the fix worked in general, not just for the File block.

## Screenshots 

**Before #18745**
Block placeholder content is centred.
before

**After #18745**
With alignment bug as reported by #19671
image

**After this fix**
Vertical margins the same as before #18745, but notice is now full width
image

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by epiqueras — CHANGES_REQUESTED** [review]
I don't think we should remove the set width.

**Comment by p-jackson** [comment]
Thanks for taking a look at this @epiqueras :)

> I don't think we should remove the set width.

To my eye at least the full width notice looks a little nicer than having the extra `40px` on the right:

image

It's so close to full width that IMO it really feels like it should be anchored to the right-hand side.

I'm happy to add the width rule back if that's the layout we want though. I may have missed something that makes the extra space necessary.

**Comment by epiqueras** [comment]
@jasmussen Did you add the width there for a reason?

**Comment by jasmussen** [comment]
I'm sure there was a reason, but that reason isn't there anymore. It seems like both of the margin and width rules can be removed:

widt

**Review by epiqueras — APPROVED** [review]

**Pull request merged**
