### PR TITLE
Update version of the plugin to 3.6.0.

### PR DESCRIPTION
**Pull request by mtias**
## Changelog

* Updated block inserter and library with new icons for all core blocks.
* Allow showing the sidebar and inspector controls when editing a block in HTML mode.
* Add new block keyboard shortcuts and consolidate their display in menus:
* * Insert Before / After block.
* * Duplicating block.
* * Toggling the inspector.
* * Remove block keyboard shortcut.
* Updated block inserter and library with new icons for all core blocks.
* Allow showing the sidebar and inspector controls when editing a block in HTML mode.
* Add new block keyboard shortcuts and consolidate their display in menus:
* Insert Before / After block.
* Duplicating block.
* Toggling the inspector.
* Remove block keyboard shortcut.
* Add new keyboard shortcuts help modal documenting available shortcuts.
* Hide keyboard shortcuts on mobile screens.
* Open new window if prior preview window has been closed.
* Bring the preview tab to the front when clicking the preview button.
* Avoid changing the label of the “publish” button if an auto-save is being performed.
* Update the Block Inserter to allow searching for terms that contain diacritics.
* Take into account children blocks when handling disabled blocks.
* Offer chance to add and revise Tags and Post Format during pre-publish flow.
* Let menus grow based on the length of its elements.
* Add visual padding to menus.
* Avoid scrollbars on Audio block when shown full-width.
* Improve permalink UI and make it responsive.
* Change color of links in gallery block caption.
* Simplify the styling of the “Toggle publish panel” aria-region to avoid content jumps.
* Make active pill button look pressed.
* Make sure Latest Posts alignment class behaviour is consistent.
* Show drop-zone background when file is dragged.
* Reset active sidebar tab on initial load.
* Apply new checkbox CSS to radio buttons and fix border radius.
* Add a couple new dashicons for insert before / after block.
* Add styles for Spinner component (was relying on core before).
* Add styles for Notice component.
* Refactor template select field to use SelectControl.
* Correctly handle per_page=-1 in the queried data state.
* Create dummy context components for type switch.
* Add RegistryConsumer export to data module.
* Add has_blocks function to the repertoire.
* Add has_block function and unit tests.
* Add has_block function and unit tests for it.
* Introduce strip_dynamic_blocks() for excerpts.
* Fix issue with default appender placeholder on IE11.
* Fix issue with shortcode block UI on IE11.
* Fix tag input interface on IE11.
* Fix issue with custom element serializer on IE11.
* Fix issue with meta boxes overlapping the content on IE11.
* Fix invalidation case of custom block classes.
* Fix unhandled error dialog styling issue.
* Fix paragraph splits on react native implementation.
* Fix code block style regression.
* Fix issue with code font-size on heading contexts.
* Fix case where crashed block would overlap with surrounding blocks.
* Fix issue with block styles on IE11.
* Fix the heading level buttons on IE11.
* Fix issues with drag and drop over text.
* Fix small bug with recent blocks hover style.
* Use argument swapping instead of named arguments for string placeholders.
* Pass the the search result object to props.onChange on UrlInput.
* Add localization context to occurrences of “More” string.
* Add a Heading block implementation for mobile app.
* Add the react-native entrypoint to all runtime packages.
* Move MoreMenu specific styling away from Popover CSS.
* Ensure meta box functions are available in editor context.
* Ensure the full content integration test is run.
* Remove client-side document title updates.
* Remove TinyMCE shim that was removed in WP 4.9.7.
* Remove the workaround for intermittent multiple-tab preview test failure.
* Remove Promise.resolve call that’s already handled by the JS runtime.
* Remove redundant event handlers from default block appender.
* Deprecate withContext HOC and remove its usage.
* Some localization & spelling fixes.
* Update docs for templateLock’s insert option.
* Extract Core Blocks to a block-library npm package.
* Add a license checker script.
* Allow access to the WordPress installation if DOCKER_ENV=localwpdev.
* Bring the handbook design up to date.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by pento** [comment]
Last minute addition of #9058!

Perhaps modify the "Add generic has_blocks function to the repertoire." to include it:

> Add generic `has_block()` and `has_blocks()` functions to the repertoire.

**Comment by youknowriad** [comment]
I also merged https://github.com/WordPress/gutenberg/pull/9069 but it's not worth mentioning, it's just a regression fix for another item on the list

> Let menus grow based on the length of its elements.

**Comment by mtias** [comment]
I'm going to experiment with locking these PRs after they are merged as it might be helpful for browsing changes-since.

**Pull request merged**
