### PR TITLE
Migrate a11y test to Playwright

### PR DESCRIPTION
**Pull request by JustinyAhin**
## What?
Migrate [`a11y.test.js`](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/a11y.test.js) to its Playwright version.

## Why?
See https://github.com/WordPress/gutenberg/pull/38570 for its background and rationale.

## How?
See [MIGRATION.md](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md) for migration steps.

## Testing Instructions
Run ` npm run test-e2e:playwright -- /test/e2e/specs/editor/various/a11y.spec.js`.

### CODE REVIEW

**Comment by JustinyAhin** [comment]
@kevin940726 changing the keyboard shortcut from `Control+Alt+H` to `Shift+Alt+H` makes it pass on CI but not locally on my Mac.

I think that's what the [`pressKeyWithModifier()`](https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/e2e-test-utils/src/press-key-with-modifier.js#L142) was handling in the previous stack. But I can not see how I could migrate this util.

**Comment by Mamaduka** [comment]
Should we close this in favor of #46038? The new PR will run a11y tests with multiple browsers.

**Comment by afercia** [comment]
> Should we close this in favor of #46038? The new PR will run a11y tests with multiple browsers.

@Mamaduka Sorry for the confusion, I wasn't aware of this PR. I'd vote in favor of #46038, also because this PR is a bit stale. For example, some utils have already been merged into trunk e.g. `create-new-post.js`.
Functionally, the ported tests seem equivalent to me. #46038 uses less CSS selectors in favor of more user-facing attributes.
However, the new constrained tabbing failures surfaced in #46038 by running the tests with multiple browsers would need to be addressed first.

**Comment by Mamaduka** [comment]
@afercia, I agree that the tests in the new PR (after issues are fixed) will give us better coverage.

Also, role-based locators are always preferred, and we're trying to include this in migrations whenever possible.

**Pull request closed without merging**
