### PR TITLE
Add ESLint rule to wrap multiline JSX in parentheses

### PR DESCRIPTION
**Pull request by koke**
## Description

I noticed this is the prevalent style across the codebase but it's not currently enforced by ESLint.

I added [react/jsx-wrap-multilines](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md) to the recommended set of rules.

I also changed the default configuration to ensure new lines after the parentheses. There were 18 violations with the default settings and 23 with the new-line setting.

The `condition`, `logical`, and `prop` configurations also seemed nicer to me, but enabling them bumped the violation count to 118, so it doesn't seem there's enough consensus on that one.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by koke** [comment]
cc @aduth since [your past suggestion to do this](https://github.com/WordPress/gutenberg/pull/6541#discussion_r185823981) was the only result when searching for this rule 😊

**Comment by gziolo** [comment]
This requires a note in the CHANGELOG of the `@wordpress/eslint-plugin` as this is a new feature added.

**Comment by koke** [comment]
Good call, I missed that one. Pushed in 1fbe05e91

**Comment by gziolo** [comment]
It got me thinking whether it will play nicely with Prettier, @jsnajdr opened #18048 which we should land sooner than later.

**Comment by koke** [comment]
I tried that branch and cherry-picked the change to enable the rule. It doesn't seem to conflict (although I'm seeing some unrelated lint errors , but it's also not catching any violations.

I think if prettier is going to land soon, this PR just becomes superfluous, so it depends on the timeline for that.

**Comment by jsnajdr** [comment]
Prettier inserts parens around multiline JSX expressions in most cases, so it shouldn't conflict with this ESLint rule. But once Prettier gets merged, these formatting-only ESLint rules become superfluous -- the formatting is handled by AI and doesn't need to be checked by another AI 🙂 That's why my PR removes them and why there even exists a `eslint-config-prettier` package that disables formatting rules.

**Comment by etoledom** [comment]
@koke - since the [Prettier PR](https://github.com/WordPress/gutenberg/pull/18048) already landed, is this PR still relevant?

**Comment by gziolo** [comment]
We still need to formal all files but it shouldn’t be an issue anymore. From now on, Prettier is the boss in terms of formatting 😃

**Pull request closed without merging**
