### PR TITLE
Use controlled InnerBlocks in reusable blocks

### PR DESCRIPTION
**Pull request by chrisvanpatten**
## Description
A small PR branched from #21427 which switches reusable blocks from a nested BlockEditorProvider area to the controlled InnerBlocks API introduced in #21368.

## How has this been tested?
Tested in browser.

## Types of changes
Non-breaking change to reusable blocks.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
The test failures are legitimate but I'd love @ZebulanStanphill to validate that the fix actually solves the problem identified in #21427 before I clean those up.

**Review by ZebulanStanphill — CHANGES_REQUESTED** [review]
On the bright side, the reusable block no longer appears empty for a moment when switching between editing and not editing.

However, it looks like things are overall a lot more broken at the moment.

Try inserting two of the same reusable block, and then editing one of them. The other one will disappear until you stop editing.

Also, editing the reusable block is pretty broken. Try typing a bunch of characters in the reusable block and then saving; the saved version will be missing the last few characters. This lines up with the current end-to-end test failures.

Maybe some of this has to do with `handleModifyBlocks` no longer being called upon the `input` event? Not really sure.

**Comment by chrisvanpatten** [comment]
> Try inserting two of the same reusable block, and then editing one of them. The other one will disappear until you stop editing.

This one is super interesting. I wonder if @noahtallen has any ideas about this — perhaps there's something about the way controlled InnerBlocks handles state that would implicitly "link" the two instances together?

> Also, editing the reusable block is pretty broken. Try typing a bunch of characters in the reusable block and then saving; the saved version will be missing the last few characters. This lines up with the current end-to-end test failures.

This is definitely concerning, and does seem likely related to onInsert vs onChange. It's possible onChange needs to be called more frequently, or perhaps that controlled InnerBlocks may need to support onInsert in some way.

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten I think controlled `InnerBlocks` already supports `onInput`, seeing as that [the Template Part block uses it](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/template-part/edit/inner-blocks.js#L20).

**Comment by ZebulanStanphill** [comment]
I just checked, and it turns out the can't-have-more-than-one problem isn't exclusive to reusable blocks. A similar bug happens with Template Part (recently renamed to Section) blocks. See #22639.

**Comment by chrisvanpatten** [comment]
> @chrisvanpatten I think controlled InnerBlocks already supports onInput, seeing as that the Template Part block uses it.

Rad! I didn't know! Going to need to go back and update some of my own code…

**Comment by ZebulanStanphill** [comment]
Unfortunately, it doesn't look like adding `onInput` handling changed anything.

**Comment by chrisvanpatten** [comment]
@ZebulanStanphill I think it did help? In the first commit, "Reusable blocks › can be inserted and edited" and "Reusable blocks › can be converted to a regular block" failed, but in the `onInput` commit only "Reusable blocks › can be inserted and edited" failed.

The remaining issue definitely stems from #22639 though.

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten Huh. I tested out the branch myself earlier and the behavior didn't seem any different. But I just tested again and now it looks like the typing-quickly issue is fixed. I guess it might have been a browser cache issue on my end? Anyway, you're right; that issue is fixed. :smiley:

**Comment by noahtallen** [comment]
>  I wonder if @noahtallen has any ideas about this

I bet the issue you linked to covers everything! Another observation is that there is a significant amount of state in `block-editor/store` which does extra stuff just to handle reusable blocks. (e.g. makes sure they are excluded from the root entity, etc) Those seemed kinda hacky to me when I was working with that state a while ago, given that it is overriding the default behavior just for one block type. I wonder if that state is compatible with the controlled inner blocks state.

**Comment by johnstonphilip** [comment]
Just noting that this would also solve these additional issues:

- You can add more than 1 block to a reusable block (maybe that's fine?)
- You do not get access to the sidebar controls for any block inside a reusable block.

**Comment by ZebulanStanphill** [comment]
> * You can add more than 1 block to a reusable block (maybe that's fine?)

Not entirely sure what you mean, but a reusable block containing multiple blocks at the top-level has always been allowed and intended. The reusable block itself acts like a parent block, albeit one that does not produce any wrapping markup on the front-end.

**Comment by johnstonphilip** [comment]
@ZebulanStanphill Good to know! Then disregard that sentence :)

**Comment by ZebulanStanphill** [comment]
This needs a rebase now that #21427 is merged. However, it looks like it may be blocked either way until #22639 is resolved.

**Comment by youknowriad** [comment]
I missed this branch. I opened a new fresh one (similar  in purpose here) #27887

**Comment by chrisvanpatten** [comment]
Thanks for taking over here, @youknowriad!

**Pull request closed without merging**
