### PR TITLE
Display ESnext examples first

### PR DESCRIPTION
**Pull request by pbrocks**
## Description

Following up from the meeting, I switch the placement of the Code tabs for JS type in the `block-registration` page.

```
{% codetabs %}
{% ESNext %}
```js
transforms: {
    from: [
        {
            type: 'prefix',
            prefix: '?',
            transform( content ) {
                return createBlock( 'my-plugin/question', {
                    content,
                } );
            },
        },
    ]
}
```
{% ES5 %}
```js
transforms: {
    from: [
        {
            type: 'prefix',
            prefix: '?',
            transform: function( content ) {
                return createBlock( 'my-plugin/question', {
                    content,
                } );
            },
        },
    ]
}
```
{% end %}```

## How has this been tested?

Not sure how to test, but I'd like to

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
I just wanted to make sure you are aware of #17873 from @mkaz. You should coordinate efforts 😄

**Review by mkaz — CHANGES_REQUESTED** [review]
Nice work! :+1:

It looks like one section in the block-edit-save.md file was missed, switch that one around and it'll be good to go. Section: **Saving Attributes to Child Elements**

Also for block-registration.md I'm not sure how much both syntaxes are really needed. Well, since I suppose our minimum browser version still include IE11 and [it does not support arrow-functions](https://caniuse.com/#feat=arrow-functions) we do need it.

**Comment by gziolo** [comment]
@pbrocks, do you plan to refresh this PR? It was so close to land 😃

**Comment by kathrynwp** [comment]
@pbrocks @gziolo @mkaz Hey there! I'm circling back to see whether this PR is still valid and planned, or whether it's best to close it out. Let me know, thank you.

**Comment by gziolo** [comment]
I think we can close it. It would be faster to apply the same changes again if they are still necessary. I think we switched to a slightly different approach for presenting code examples.

**Pull request closed without merging**
