### PR TITLE
First pass at using the new sidebars and widget endpoints.

### PR DESCRIPTION
**Pull request by TimothyBJacobs**
## Description
Use the new sidebars and widget endpoints introduced in #25958.

## How has this been tested?
Manual testing, PHPUnit testing.

## Types of changes
Refactoring.

Right now the saves are all separate requests. This is blocked on #26024.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
PHPUnit tests failures are unrelated see, #26085.

**Comment by helen** [comment]
The first time I tried to save after switching to this branch and building I got `There was an error. can't access property "id", g is undefined`, after that I got the correct `Widgets saved.` message. Just wanted to note that in case it's reproducible and needs to be fixed.

**Comment by TimothyBJacobs** [comment]
> The first time I tried to save after switching to this branch and building I got `There was an error. can't access property "id", g is undefined`, after that I got the correct `Widgets saved.` message. Just wanted to note that in case it's reproducible and needs to be fixed.

This happens when the response returned when trying to create an endpoint doesn't return a valid response. This happened in particular because RSGW generates a fatal error when calling `wp_kses`.

I've added a specific error message when saving a widget fails due to this reason, `Could not save the widget "%s". An unexpected error occurred.`. But I'm not sure what should happen here to resolve the error for the user. Should we prompt them to remove that widget?

**Comment by adamziel** [comment]
Merging with base branch, let's consider this as a single PR.

**Pull request merged**
