### PR TITLE
Update datepicker styling to inherit font-family/colour scheme

### PR DESCRIPTION
**Pull request by paulwilde**
Updates the datepicker style so its more consistent with the overall Gutenberg UI.

datepickers

### CODE REVIEW

**Comment by jasmussen** [comment]
This seems a _vast_ improvement over what was there before. That's a lot of variables and CSS to override the datepicker, though — are there any bundled style we could unload so we don't have to override? Or is this the simplest it gets?

Either way, 👍 👍  visually, nice work 🏅

**Comment by paulwilde** [comment]
@jasmussen I honestly don't think there's much else that can be done to slim it down rather than manually styling the datepicker and ignoring the import all together.

The CSS which is being imported is around [500 lines long](https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss), so it's not that huge to be honest.

**Comment by jasmussen** [comment]
Then no objections and thanks for the contribution!

**Comment by aduth** [comment]
Related: #1311

**Comment by karmatosed** [comment]
Let's get this in as we haven't a decision unless I'm missing it, on replacing. It feels a solid fix to get in today. Thanks.

**Comment by mtias** [comment]
Thanks @paulwilde, this is great. When/if we replace the base component we'll just replicate the styling.

**Pull request merged**
