### PR TITLE
Fix warnings during tests and prevent them from reoccurring

### PR DESCRIPTION
**Pull request by nylen**
We have a few warnings appearing during test suite runs:

```
  1) full post content fixture core__table:
     Error: Warning caught via console.error: Warning: validateDOMNesting(...): Whitespace text nodes cannot appear as a child of <table>. Make sure you don't have any extra whitespace between tags on each line of your source code. See table > #text.

  2) state editor() "before all" hook:
     Error: Warning caught via console.error: The "save" property must be specified and must be a valid function.

  3) state editor() "after all" hook:
     Error: Warning caught via console.error: Block "core/test-block" is not registered.
```

(Output is from the test suite after checking out only the first commit in this branch.)

Like in PHPUnit, these should fail the build.  The way of accomplishing this in JavaScript is a bit hacky but I think it is probably worth doing.

@gziolo - it looks like this may cause problems with Jest and #1382 (IMO adopting Jest is more important than this change).  Thoughts?

@EphoxJames - I cannot figure out why these warnings about whitespace text nodes appear in test mode but not when saving/editing posts.  Thoughts?

### CODE REVIEW

**Comment by nylen** [comment]
Rebased after adding Jest in #1382.  This seems to still be working fine (try it by applying this, for example):

```diff
diff --git a/blocks/api/test/registration.js b/blocks/api/test/registration.js
index d601ac5..6141bb8 100644
--- a/blocks/api/test/registration.js
+++ b/blocks/api/test/registration.js
@@ -36,6 +36,7 @@ describe( 'blocks', () => {
 		setUnknownTypeHandler( undefined );
 		setDefaultBlock( undefined );
 		console.error.restore();
+		console.error( 'hi :)' );
 	} );
 
 	describe( 'registerBlockType()', () => {
```

**Comment by gziolo** [comment]
I like the idea of promoting console errors to test errors unless explicitly wrapped with proper expect call 👍

**Comment by nylen** [comment]
080b7a5 is _interesting_ code, but not the kind I'd like to merge, especially since this is only needed during test runs.  Now taking a different approach that allows only these mysterious warnings.

**Comment by EphoxJames** [comment]
I'll remove the whitespace from the table serialization test input which I'd imagine will fix the warning.
It seems a pretty silly warning though as whitespace does nothing to break xhtml and actually makes the test input readable.

**Comment by nylen** [comment]
> I'll remove the whitespace from the table serialization test input which I'd imagine will fix the warning.

:+1: I guess this is OK, though it'd be nice to know more about what is happening here.

**Pull request merged**
