### PR TITLE
Navigation: adjust mobile close button position when admin bar is visible

### PR DESCRIPTION
**Pull request by mikachan**
## What?

This PR adjusts the position of the close button in the mobile navigation dialog when the user is logged in (when the admin bar is visible). Before, the close button would seem to jump in position compared to the hamburger menu.

## Why?

This isn't an issue when the admin bar is not visible, so this aligns the two views.

## How?

I've added a top margin to the dialog div which matches the `$admin-bar-height` or `$admin-bar-height-big`, depending on the breakpoint.

## Testing Instructions

1. Activate Twenty Twenty-Two
2. Make sure there is a navigation block in the header with the Overlay Menu set to Mobile
```
<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}} -->
<!-- wp:page-list /-->
<!-- /wp:navigation -->
```
3. Make sure you're logged in
4. On the front end, adjust your screen size to around 440px wide
5. Open the mobile menu dialog by clicking the hamburger menu
6. You should see the close button position is in the same position as the hamburger menu icon

## Screenshots or screencast 

Before:
<video src="https://user-images.githubusercontent.com/1645628/173099015-01592d14-2d10-437a-b3ac-9f7dc89aded7.mov" width=180 />

After:
<video src="https://user-images.githubusercontent.com/1645628/173098981-512c50f0-2f6b-4e24-a4a0-2b099bad8c71.mov" width=180 />

### CODE REVIEW

**Review by pbking — APPROVED** [review]
Thank you for this @mikachan.  This looks right to me and now works as I would expect it to.

**Review by carolinan — APPROVED** [review]
This works well in themes where the menu is aligned to the right.
It is less obvious when the menu is in different positions, but still an improvement.

**Comment by iamtakashi** [comment]
Hi all,

Thanks for working on this! However, this change seems to be pushing also the navigation items down. Am I missing something?

Screenshot 2022-06-23 at 15 33 23

**Comment by iamtakashi** [comment]
In the example above, the navigation was set to display the overlay menu only for mobile.

Screenshot 2022-06-23 at 15 51 58

The issue can only be seen on the front of the site. No navigation is affected in the editor.

**Comment by mikachan** [comment]
> However, this change seems to be pushing also the navigation items down.

👋 Could you share which theme this is in, or the markup for this menu? I'm guessing the 'Start a project' button is absolutely positioned, or it's styled in another way which means the top margin doesn't affect it.

Either way, I can take a look and spin up another PR.

**Comment by iamtakashi** [comment]
Hi @mikachan 👋 , the theme is something that I'm working on now, and it hasn't yet been released. The button is placed normally next to the navigation block in a Row block. Anyway, this is the markup of the entire header.

```
<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"className":"gapless-group","layout":{"inherit":"true"}} -->
<div class="wp-block-group gapless-group"><!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"40px","bottom":"40px"}}},"layout":{"type":"flex","justifyContent":"space-between"}} -->
<div class="wp-block-group alignfull" style="padding-top:40px;padding-bottom:40px"><!-- wp:group {"layout":{"type":"flex"}} -->
<div class="wp-block-group"><!-- wp:site-logo {"width":64} /-->

<!-- wp:site-title /--></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:navigation {"ref":373,"__unstableLocation":"primary","layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right","orientation":"horizontal"},"style":{"spacing":{"margin":{"top":"0"}}}} /-->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Start a project</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```
I've just tested this with Twenty Twenty-Two, and the issue can be seen with the theme too.
Screenshot 2022-06-23 at 17 05 14

Please let me know if there is anything that I can help with!

**Comment by mikachan** [comment]
Thanks, this helps a lot! I understand now, this is affecting items that aren't even inside an open mobile menu. Good spot!

This should fix the issue: https://github.com/WordPress/gutenberg/pull/41949

**Pull request merged**
