### PR TITLE
Add adjustable height in focus mode

### LINKED ISSUE #35512: Template part editor: adjust height to contents
Let's ensure the height of the canvas is reasonable and adjusted to the contents.

image

cc @jameskoster

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Close https://github.com/WordPress/gutenberg/issues/35512. Alternative to https://github.com/WordPress/gutenberg/pull/35856. Implement the design similar to the one in https://github.com/WordPress/gutenberg/issues/35512#issuecomment-949753478.

The height of the canvas is now determined by the template part contents. You can also manually resize the height if needed. The preview options are removed, in the future we can re-implement a new "viewport width" similar to the one in the design of pattern directory.

## How has this been tested?

1. Activate `tt1-blocks` theme
2. Go to Site Editor
3. Edit a template part (block toolbar -> Edit)
4. Play with the resizer

## Screenshots 

https://user-images.githubusercontent.com/7753001/138814439-714fb2ab-f41a-4cc4-9e52-a35cef3d615b.mp4

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for trying this out. Imo it feels good except I don't think the height should be adjustable – it doesn't really serve any practical purpose that I can see.

**Comment by kevin940726** [comment]
> Thanks for trying this out. Imo it feels good except I don't think the height should be adjustable – it doesn't really serve any practical purpose that I can see.

Sure I can try another one without this feature.

It just seems natural to me to be able to also resize the height when we can resize the width. It could be useful when the template part flows vertically rather than horizontally, like the vertical nav bar in wp-admin for instance, so that the users can view it with different heights and make adjustments. It doesn't feel like a necessity to me though, but rather exists for compatibility reason.

**Comment by shaunandrews** [comment]
I agree with Jay; Changing the height doesn't really serve a purpose.

**Comment by kevin940726** [comment]
Close in favor of #35974.

**Pull request closed without merging**
