### PR TITLE
Font Size Picker: Use a Button Group instead of a Select.

### PR DESCRIPTION
**Pull request by epiqueras**
Explores #17755 

Screen Shot 2019-10-03 at 11 57 50 AM

### CODE REVIEW

**Comment by karmatosed** [comment]
Unfortunately, for me I really don't think this fits buttons like this or the styling. I am incredibly reluctant to add another interaction pattern like this.

@jasmussen explored how it could be to have it show on select. I wonder if that could be a great middle-ground?

image

**Comment by epiqueras** [comment]
I agree, I'd go with @jasmussen's approach.

**Comment by mapk** [comment]
With Joen's approach, the font-size would be displayed in the default state of the selectbox if not in the dropdown, as I understand it. This would cause some visual inconsistencies.

**Normal font sizes look great.**

v3

**But Larger font sizes would look disproportionate.**

v3-larger

So ultimately I don't think this is a good solution for font-sizes, although a beautiful one for displaying various typefaces.

**Comment by epiqueras** [comment]
It could also be shown below it, as a preview.

Anyway, it looks like we can use Downshift now and stick to the original design: https://github.com/WordPress/gutenberg/issues/16473#issuecomment-527220828.

**Comment by mapk** [comment]
I was concerned how this might look in other languages, but when switched wp-admin settings to Russian, none of this inside Gutenberg changed from English to Russian. Is this right? If these buttons never change language, then we may be okay. But if they do change, then we end up with something like this:

Screen Shot 2019-10-03 at 1 54 25 PM

But English alone looks to be somewhat difficult. In the PR, the word "Huge" has the "g" breaking out below the button.

Screen Shot 2019-10-03 at 1 59 11 PM

**Comment by epiqueras** [comment]
This PR doesn't run the values through any i18n functions, but neither did the previous version.

**Comment by gziolo** [comment]
> This PR doesn't run the values through any i18n functions, but neither did the previous version.

Those options are translated on the server and every theme can provide their own set.

**Comment by jasmussen** [comment]
Sorry @karmatosed, I'm afraid the idea I had fell apart after I realized that the font size when set on the `select` element would affect the content of the dropdown as well. So we'd have to do some funky JS on-click handling that would probably not work well enough.

**Pull request closed without merging**
