### PR TITLE
Edit Site: Add browse mode.

### LINKED ISSUE #23328: Site editor: Add Browse Mode
Currently there are two cursor modes in the editor: Edit and Select. They look like this:

image

@mtias [suggested](https://github.com/WordPress/gutenberg/issues/19204#issuecomment-567236656) it might be nice to explore the idea of a third mode allowing the user to browse around their site within the editor. 

@shaunandrews [quickly proposed some designs for it](https://github.com/WordPress/gutenberg/issues/19204#issuecomment-577282108).

In order to focus the discussion, I create a prototype using Shaun's design to get an idea for the feel as well as a new issue. The other issue is a bit dated and messy and I'll likely close it shortly.

## Prototype i1

[Try the prototype](https://www.figma.com/proto/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=5945%3A10712&viewport=349%2C338%2C0.5&scaling=min-zoom).

The biggest change is the removal of the text at the bottom of the popover. I'm not sure that was scalable in the long run. Instead, there are short descriptions with each tool to help the user get a rough idea what each is for. Perhaps we could also integrate hotkeys like in other menus? The hover/focus states should not change so I didn't include them in the mockup.

## Screenshot

image

[Source figma file](https://www.figma.com/file/TR15iRvk7toGHnKb68QN1K/Full-Site-Editing?node-id=5945%3A10997)

## Ideas for improvements
* Shaun mentioned it might be a good idea to show a visual indicator to make it clear what links can be clicked. Perhaps a hover/focus state?

CC @epiqueras since I know you were interested.

### PR DESCRIPTION
**Pull request by epiqueras**
## Description

Closes #23328.

This PR implements browse mode navigation from #23328.

## Screenshots

ezgif-4-14f75a598c64

## Checklist:

- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
@mapk or @MichaelArestad, did you have a chance to test this PR to validate how it fits with what was proposed in #23328?

**Comment by mtias** [comment]
Yes, I like this direction but is not immediately a priority.

**Comment by MichaelArestad** [comment]
I am not sure we should move forward with this yet. @mapk and @dubielzyk followed up with iterations that show promise.

**Comment by priethor** [comment]
Work towards Browse mode has been resumed in #44770. Since this PR has been stalled for a couple of years and the Site Editor has greatly changed, let's close it in favor of #44770 🙏

**Pull request closed without merging**
