### PR TITLE
Docs: Release: Clarify pinging core team members

### PR DESCRIPTION
**Pull request by mcsf**
Reduce the bus factor by not referencing an individual contributor.

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
Good call; I've tweaked it to include a link to the team members (9d2c2905ee08448bc93bde4cbd0892010a36db2e). 👍

**Comment by mcsf** [comment]
Thanks! Though I've noticed that that link requires being logged in.

**Comment by tofumatt** [comment]
Oh, shoot. Still, probs better to have the link than not.

Also we should link directly to the Slack channel; I've added the link.

**Comment by tofumatt** [comment]
Gonna merge this because it's worth having. Not sure if it belongs in a milestone cc @youknowriad

**Comment by mcsf** [comment]
Thanks!

**Pull request merged**
