### PR TITLE
[RNMobile] Enable Audio Block

### PR DESCRIPTION
**Pull request by ceyhun**
## Description

This PR enables Audio Block for mobile.

GB Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3070

### Test upload:

1. Add Audio block
1. Choose to upload:
	* From device
	* From WP Media Library

### Test replace:

1. Add Audio block
1. Choose an audio
1. Press audio block
1. Select "Replace audio" from the toolbar
1. Choose a new audio

### Test caption:

1. Add Audio block
1. Choose an audio
1. The block should be selected with "Write caption..." placeholder for caption field
1. De-select block
1. Caption field should be hidden
1. Switch to HTML
1. Check there are no `<figcaption>` tags
1. Switch to Visual
1. Select Audio block
1. Type some words in the caption field
1. Add some bold/italic words
1. Move the cursor to the middle and press enter
1. Caption should have a new line
1. Move the cursor to the end and press enter
1. A new paragraph block should be created
1. Switch to HTML
1. Check if `<figcaption>` tags contain correct information (for bold, italic, etc. and `<br>` tags for new lines)
1. Save the post and open it from the web browser
1. Check if the caption shows correctly 

### Test settings:

1. Add Audio block
1. Choose audio
1. Press gear icon and modify settings
1. Check if they are reflected by previewing the post

### Test playing:

1. Add Audio block
1. Choose an audio
1. Tap "OPEN" to play the audio

### Test cancel action:

* Add a Audio block to an empty new post.
* Add a large file to the block.
* While the file is uploading, tap on theAudio  block to see the cancel action sheet/dialog.
    * Tap the Stop upload action.
    * The Audio block should go back to the empty state.
    
### Test error and retry:

* Add a Audio block to an empty new post.
* While it's uploading, turn un Airplane mode.
    * See the Audio block switch to its error state.
* While in the error state, tap on the Audio block to see the Retry action sheet/dialog.
* After reconnecting the device, press the Retry action.
    * Check that the audio file starts uploading again until it successfully finishes uploading.

## Screenshots 

audio-block-states

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jd-alexander** [comment]
I tested the behavior described above on Android and I was able to get all the behavior above working except the autoplay. For some reason, the audio file does not autoplay in Preview mode. I am seeing around the web that autoplay doesn't work well in Chrome sometimes. I am looking at [this question](https://stackoverflow.com/questions/50490304/how-to-make-audio-autoplay-on-chrome) for clues about what could be taking place.

**Comment by ceyhun** [comment]
>I tested the behavior described above on Android and I was able to get all the behavior above working except the autoplay. For some reason, the audio file does not autoplay in Preview mode. I am seeing around the web that autoplay doesn't work well in Chrome sometimes. I am looking at this question for clues about what could be taking place.

@jd-alexander I tested this by opening the post from the web editor again and the option is reflected there. Also I created another post with Audio Block with autoplay option and published it from mobile. When I open it from the web browser and inspect the page, I can see that `audio` tag has the `autoplay` option as `<audio autoplay>`.

**Comment by jd-alexander** [comment]
> @jd-alexander I tested this by opening the post from the web editor again and the option is reflected there. Also I created another post with Audio Block with autoplay option and published it from mobile. When I open it from the web browser and inspect the page, I can see that audio tag has the autoplay option as <audio autoplay>.

Thanks @ceyhun for running these tests. I was able to reproduce this as well and it is indeed compliant with the way the block is supposed to behave. This is not a blocker in any way as more research is needed in this matter so this can be done afterward. We are good to go here!

**Review by jd-alexander — APPROVED** [review]
LGTM 🚢

**Pull request merged**
