### PR TITLE
Navigation: Make Navigation a static block

### PR DESCRIPTION
**Pull request by noisysocks**
Work in progress. 

Implements part of https://github.com/WordPress/gutenberg/issues/24364.

Makes Navigation a static block and Navigation Link a mostly static block.

Tasks remaining:

- [ ] Fix block context not being passed to `save()`.
- [ ] Handle migration of older `rgb*` attributes.
- [ ] Test all attributes.
- [ ] Test migration from older blocks.

### CODE REVIEW

**Comment by noisysocks** [comment]
Here's a first pass at making Navigation a static block. I like the amount of red—it's a big simplification.

Unfortunately, though, there's a problem: any existing dynamic Navigation blocks that are out there will not render properly in the frontend until the user re-saves the post that the block is in. This is because we're deleting the `render_callback` and so WordPress won't know what to do with the `<!-- wp:navigation /-->`. Re-saving the post fixes it because Gutenberg will replace the `<!-- wp:navigation /-->` with what `save()` returns.

We either have to:

1) Not bother doing this and keep everything dynamic.
2) Keep the `render_callback` around for a while. (Forever?)
3) Accept that Navigation is experimental and that sites using it may break.

Thoughts? @talldan @draganescu @adamziel

**Comment by noisysocks** [comment]
This was discussed during the Nav sync in #core where we decided:

1. Let's keep Link dynamic.
2. Let's keep the `render_callback` around for two releases with a deprecation notice.

**Comment by youknowriad** [comment]
I thought it was important for that block to be dynamic in order to adapt to changes to the permalink structure...?

**Comment by noisysocks** [comment]
> I thought it was important for that block to be dynamic in order to adapt to changes to the permalink structure...?

Yes, we'll need to keep Link dynamic for this reason. Do you think Navigation should remain dynamic as well?

**Comment by youknowriad** [comment]
> Do you think Navigation should remain dynamic as well?

What do you mean by Navigation here? I personally don't know enough here to share an informed opinion. I know initially, @mtias was in favor of a fully dynamic block.

**Comment by adamziel** [comment]
@youknowriad Rob meant we could use a combination of static (navigation) and dynamic blocks (link) to have both:

* Auto-updating links when dynamic blocks are available
* A decent fallback in all other cases (like using a classic editor)

**Comment by noisysocks** [comment]
I figured that if a block _can_ be static then it _should_ be static. Since Navigation merely renders a container `<nav><ul><InnerBlocks /></ul></nav>`, it _can_ be static.

Happy to keep both Navigation and Link dynamic if we think that's better. The argument about compatibility with the Classic Editor holds less water when we're talking about Navigation because it's not common that you would insert a Navigation block into a post or page.

**Comment by youknowriad** [comment]
It makes sense for me 👍 I just wanted to make sure we were not regressing on the dynamic behaviors.

**Comment by mtias** [comment]
Not sure I see much value in keeping an empty container static when it doesn't really provide useful semantics. I always thought a potential static fallback for a navigation block should instead be a semantic link to a site's sitemap (new feature in 5.5!)or something to that effect.

**Comment by noisysocks** [comment]
At any rate, this PR is stale! Closing it for now.

**Pull request closed without merging**
