### PR TITLE
Style engine: move backend scripts to package

### PR DESCRIPTION
**Pull request by ramonjd**
Requires: 

- https://github.com/WordPress/gutenberg/pull/39446

## What?

A very naïve attempt at:

- copying package PHP files over to /build
- ensuring `_gutenberg/_wp` renaming is minimized for core patches

## Why?

1. The Style Engine backend is an implementation of the JS version. Keeping them together in the package makes the relationship more conspicuous.
2. The Style Engine is something that might be used across Gutenberg PHP files in the future. The intention is to make backporting to core easier. See discussion over at https://github.com/WordPress/gutenberg/issues/33241#issuecomment-876218087

Historical context/discussion:
- https://github.com/WordPress/gutenberg/issues/33241#issuecomment-876218087
- https://github.com/WordPress/gutenberg/pull/39446#issuecomment-1076050281
- https://github.com/WordPress/gutenberg/pull/39446#discussion_r834186170

## How?
- Move Style Engine class to `packages/style-engine`
- Update Webpack packages script to:
    - copy the class to build
    - rename classes and methods so that they don't conflict with core (`_gutenberg`)

## Testing Instructions
Build the project via `npm run dev` or `npm run build`

Check that the PHP file in `packages/style-engine` is copied to `/build` and:
- renamed to `*-gutenberg.php`
- edited so that class names have `_Gutenberg` appended

Follow the test instructions in https://github.com/WordPress/gutenberg/pull/39446, and check that the margin and padding block support styles are output correctly on the frontend.

### Unit tests

```bash
npm run test-unit-php /var/www/html/wp-content/plugins/gutenberg/packages/style-engine/phpunit/class-wp-style-engine-test.php
```

```bash
npm run build
npm run test-unit-php /var/www/html/wp-content/plugins/gutenberg/phpunit/block-supports/spacing-test.php

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hi, @ramonjd

In case you missed this, @noisysocks recently merged best practices for Gutenberg PHP - https://github.com/WordPress/gutenberg/blob/trunk/lib/README.md.

**Comment by ramonjd** [comment]
> In case you missed this, @noisysocks recently merged best practices for Gutenberg PHP

Thanks @Mamaduka I did read this. What it doesn't cover is this novel situation:

_How should we import individual PHP files – in this instance a class that might be used across Gutenberg – from `/packages/**`?_

There's a solution perhaps related to the way we import block `index.php`, though I suspect we need to come up with an approach that takes into account the build/renaming/unit tests, and then document in the file you cited. 

I'm very keen to hear folks' advice on this, since I'm just hacking around. 😄

**Comment by ramonjd** [comment]
After hacking my way into a hole, I have the following open questions:

### What we want - high level

- For the Style Engine PHP file and its tests to live in `packages/style-engine`
- To make both WordPress core migration and future Gutenberg development easier by auto-renaming classes and methods, `_Gutenberg` and `gutenberg_`
- Not to create a hacky precedent. It has to be sustainable if future packages want to do the same thing.

### What we want - low level 

1. Copy the file into the Gutenberg lib directory
2. Rename the file and the class names
3. Require the renamed file and use the renamed class in the app
4. Somehow do all the above during tests as well.


**_OR_** 

Can we accept for now that the Style Engine PHP file lives as part of `lib` next to the files with which it's closely coupled and try to mitigate any future core migration pains there?

### How?

Not the way I've done it 😄 

🤷 

- How should we get the PHP file included as part of the tests? What about creating a composer package? Maybe we need a package copy/build step in bootstrap? 
- Should we keep a list of package php files that need to be included in Gutenberg build, like a static JSON file or something
- How can we ensure we can keep iterating on a package PHP file once a file is in WordPress?
- In the package, should we go full-blown composer, PHP unit and everything else?

cc @youknowriad @apeatling @andrewserong 

and cc @gziolo and @ockham, who I know also have experience in the build process

Thanks for your advice!

**Comment by youknowriad** [comment]
Hi @ramonjd it's unclear to me from the message, what errors you had with our current way of doing things and why we need to change our approach?

I'm all for using the best approach and don't mind changing but I'd like to understand the struggles with the current way we do things (block-library) which is the following:

 - PHP file is part of the npm package, that way the update happens automatically in Core when we do the npm package update.
 - We rename the functions and generate a "build" version of the php files in `build` folder in Gutenberg (that way we clearly separate source and build)
 - Renaming the functions allows us to load 2 versions without conflicts (Core and Gutenberg), so we can continue iterating.
 - We need to assume the built files exist in other parts of Gutenberg php code (unit and `lib` folder) to `require` them.

I think the thing that differ from `block-library` setup is that we will be using the renamed classes/functions outside the `block-library` folder. I think that's in `lib/block-supports` mostly for now and maybe it's fine to refer to the "gutenberg" version directly there for now since we're back porting these files (block supports) manually at the moment, so we can rename at the moment we backport them.

---
The above is mostly about moving this forward with what we already know/do. I think exploring alternatives is possible but it's unclear to me, what will we do here: Composer packages are interesting of course but we'd need to solve "auto loading" and whether it's fine for us to rely on composer auto-loading, we'd need to start a discussion in make/core with the whole community about it (I'm sure a lot of them will be delighted to use composer packages but I think there will be a resistance too). With composer packages, we won't solve the "duplication" problem though, if we load the package in core and Gutenberg, we'll have same class/file names.

**Comment by ramonjd** [comment]
Thanks a lot for the explanation @youknowriad ! 

> it's unclear to me from the message, what errors you had with our current way of doing things and why we need to change our approach?

I'm not suggesting we change the approach. The source of my uncertainties stems mostly from not being sure whether what I'm doing is right at all 😄 

I'm also conflicted in relation to how to deal with PHP unit tests: the file needs to be copied and renamed before the unit test runner kicks off (I've hacked this into bootstrap.php)

I think you've confirmed the general direction,  which is really helpful. 

I'm not too far off conceptually I believe, I just need to dig a little deeper as I'm still working out the parts.

> We rename the functions and generate a "build" version of the php files in build folder in Gutenberg (that way we clearly separate source and build)

Looks like this is where my initial attempt is probably not right. I'm writing to `/lib` directly just to get it working. 

This branch actually works locally for me, and I (mostly) followed the block-library approach. 

The branch isn't building on CI yet though.

I'll keep plugging away. Thanks again! 🙇

**Comment by gziolo** [comment]
I'm looking at the moment at `lib/block-supports` and it's really difficult to tell whether there were any functional changes introduced in the WP 6.0 release cycle. It definitely is an issue that all functions are prefixed with `gutenberg_` and they can easily diverge with WordPress core because some fixes might get applied directly there. It's a very difficult problem to resolve. From the backporting to WP core perspective, it would be better to limit the number of files that change in every WordPress release and ensure it's easy to discover.

**Comment by youknowriad** [comment]
@gziolo For the block supports, I think we should do the same as "block-library" (and the proposed changes for style engine here), meaning I believe we should just write them as if we were in Core, copy them automatically as part of the package update in core (like we do for blocks and parser) and rename them automatically in the gutenberg plugin in the web pack build.

In previous version (5.9, 5.8) we kind of this that process manually: replace the files in core with the Gutenberg's files, rename the functions again.

**Comment by gziolo** [comment]
@youknowriad. It isn't that the syncing core blocks with WordPress core don't have any drawbacks. It was criticized several times in the past, including this issue https://github.com/WordPress/gutenberg/issues/33241. Anyway, if you feel strongly about that approach then we can give it a try. From the perspective of someone merging the changes into WordPress core, it seems to be easier to leave everything to the script.

**Comment by youknowriad** [comment]
> It isn't that the syncing core blocks with WordPress core don't have any drawbacks.

I agree it's not perfect, especially for Gutenberg itself as it adds this "renaming stuff" complexity, but I think it still a bit better than having to do all these backports manually, don't you think?

>  it seems to be easier to leave everything to the script.

Yes, that's the main selling point here.

**Comment by youknowriad** [comment]
This is looking good to me, do you think there's any blockers left?

**Comment by glendaviesnz** [comment]
This all worked as advertised for me:

✅ Files as copied to /build folder and renamed and `Gutenberg` appended to class name
✅ Unit tests passed
✅ Styles were added to the sampe `h1` blocks on frontend

**Comment by ramonjd** [comment]
Thanks for testing @glendaviesnz !

> This is looking good to me, do you think there's any blockers left?

I can't think of any, though I can't help but feel I have a limited overview of all the working parts. 

Things are working as they should so far so I suppose we could go ahead and merge and then 🤞

**Review by andrewserong — APPROVED** [review]
Nice work @ramonjd, thanks for the follow-up! This is testing well for me:

✅ Builds file to correct location when running `npm run build` 
✅ Builds file to correct location when running `npm run dev`
✅ Classes and function names correctly have gutenberg appended or prepended, respectively
✅ Tests are passing, and padding / margin behaviour still works correctly on the front-end

It looks like now that the test file is moved into the package, we should be able to remove the duplicate at https://github.com/wordpress/gutenberg/blob/44925a947fde29feaab512e0adf4291272209d59/phpunit/style-engine/class-wp-style-engine-gutenberg-test.php ?

There were good points raised in the discussion about what to do about the naming of the function calls / class names when the style engine is called from within the block supports files, but I reckon we could look at that separately if/when we want to improve things for the block supports directly.

This looks good to try to me!

**Comment by youknowriad** [comment]
LGTM to me as well. We'll need to make a specific patch for this for WordPress trunk (add the code to copied php files from packages) when we decide to include the style engine in Core. If it's for 6.0 that's easy (it's this week), otherwise it's going to be for 6.1 and we need to make sure we don't forget :P

**Comment by ramonjd** [comment]
> We'll need to make a specific patch for this for WordPress trunk (add the code to copied php files from packages) when we decide to include the style engine in Core. If it's for 6.0 that's easy (it's this week), otherwise it's going to be for 6.1 and we need to make sure we don't forget :P

Good call.

We've [left it out of 6.0](https://github.com/WordPress/wordpress-develop/pull/2500) because it's not really doing much. 

But I've set a reminder in my brain for 6.1 to get back to you 😄

**Comment by ramonjd** [comment]
> It looks like now that the test file is moved into the package, we should be able to remove the duplicate at https://github.com/wordpress/gutenberg/blob/44925a947fde29feaab512e0adf4291272209d59/phpunit/style-engine/class-wp-style-engine-gutenberg-test.php ?

Oh, yeah! I'll do that before merging this PR. Thanks for spotting that @andrewserong

**Comment by noisysocks** [comment]
> @gziolo For the block supports, I think we should do the same as "block-library" (and the proposed changes for style engine here), meaning I believe we should just write them as if we were in Core, copy them automatically as part of the package update in core (like we do for blocks and parser) and rename them automatically in the gutenberg plugin in the web pack build.

💯 yes.

**Pull request merged**
