### PR TITLE
Rename functions containing `fse`

### PR DESCRIPTION
**Pull request by aristath**
## Description

"FSE" was a term used in the initial development stages on Full Site Editing. However, these terms bled into function-names and inline docs. We should remove references to FSE since this is not what it will be called.
This should change prior to 5.8 because once functions get in, it will be extremely hard to remove them without adding deprecations & aliases.

The same should happen in core - see https://core.trac.wordpress.org/ticket/53497

## Changes:
* Tweaked wording in inline comments
* Renamed `gutenberg_is_fse_theme` to `gutenberg_is_block_theme` and added a deprecation notice in the `gutenberg_is_fse_theme` function 'cause I see it's used in some plugins (including Jetpack)
* Renamed `gutenberg_extend_block_editor_settings_with_fse_theme_flag` to `gutenberg_extend_block_editor_settings_with_block_theme_flag`
* Renamed `_gutenberg_migrate_remove_fse_drafts` to `_gutenberg_migrate_remove_wp_template_drafts`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by aristath** [comment]
Related patch for core: https://github.com/WordPress/wordpress-develop/pull/1425

**Comment by gziolo** [comment]
It looks like some e2e test failures are legit and they require some further investigation. The naming patterns look better. Should we split it into the part that renames only the function used in WP core to speed up the process? @youknowriad, what do you think?

**Comment by youknowriad** [comment]
What are the functions that are on Core? AFAIK, there aren't but maybe I'm wrong.

**Comment by aristath** [comment]
> What are the functions that are on Core? AFAIK, there aren't but maybe I'm wrong.

I found `gutenberg_is_fse_theme` which is used in a couple of checks, and I'm going through all files to see if there's any more... It's just going a bit slow 'cause I'm looking for `fse` which also happens to be a part of other words like `offset` so there's quite a few of them :grimacing:

**Comment by desrosj** [comment]
Full Site Editing references a specific group of features that are available. Wouldn't changing this be misleading?

For example, `gutenberg_is_fse_theme()` detects whether the theme has the needed files to support block templates. Changing it to `gutenberg_is_block_theme()` is not really accurate because you can be a block theme and not have support for block templates.

**Comment by aristath** [comment]
> Should we split it into the part that renames only the function used in WP core to speed up the process?

Good idea. I only included the PHP changes in this PR :+1: 

> For example, `gutenberg_is_fse_theme()` detects whether the theme has the needed files to support block templates. Changing it to `gutenberg_is_block_theme()` is not really accurate because you can be a block theme and not have support for block templates.

:thinking: A "block" theme the way I understand it is a theme that supports block templates, so has a `block-templates/index.html` file which can be used with the site-eeditor.
If that is not the case, then I'd be happy to rename the function to something more appropriate/suitable, any ideas?

**Comment by desrosj** [comment]
I could also be incorrect in my understanding. As I understand it currently, there is the potential for a difference between themes that are block-based and themes that have FSE support. I believe it's also potentially possible that a traditional theme could add support for block templates and not be a true block-based theme.

Also, it's important to note that the checks in Core are only there until FSE is fully merged. After that, the code being targeted in #32950 will be removed because Core will be able to determine FSE (or block-based theme support) on its own.

**Comment by aristath** [comment]
> I could also be incorrect in my understanding. As I understand it currently, there is the potential for a difference between themes that are block-based and themes that have FSE support. I believe it's also potentially possible that a traditional theme could add support for block templates and not be a true block-based theme.

:sweat: we've messed things up a lot with naming... The distinction I've seen most people do is this:

* Themes that are built using block templates (previously known as FSE) are "block" themes
* "Classic" themes (for lack of a better word) can opt-in to support block-templates, but they are not FSE/block themes
* There are a few themes that claim to be "block-based", but they use the term mostly as a marketing gimmick and describe the fact that they have block styles properly apply both in the frontend and the editor, and sometimes have actual `block-styles` and `block-patterns` defined.
* A theme can either be based on block templates (making it an FSE/block theme) or not. All block themes support block-templates, and classic themes may optionally add support for block templates but that doesn't make them block themes

As I was writing this [this comment](https://wordpress.slack.com/archives/C02QB2JS7/p1624544422045700?thread_ts=1624458882.469800&cid=C02QB2JS7) came in, so I assume `is_block_theme` is OK? :thinking: 

> Also, it's important to note that the checks in Core are only there until FSE is fully merged. After that, the code being targeted in #32950 will be removed because Core will be able to determine FSE (or block-based theme support) on its own.

I agree, and it's great that we're adding that check there. However, if it's in core a lot more people will notice it and start using it, making it will be a lot easier to change the name now than change it in the future

**Comment by youknowriad** [comment]
Why is `gutenberg_is_fse_theme` being checked on core code base since it's not present there anyway?

**Comment by youknowriad** [comment]
I agree with the purpose of this PR though, I think we shouldn't refer to "FSE" in our codebase because it doesn't mean anything:

 - If we're referring to theme.json, we can do so directly
 - If we referring to custom block-templates support, we already have the theme support flag
 - If we're referring to themes with html block templates, I think we can refer to these as block themes.
 - ...

**Comment by aristath** [comment]
> Why is `gutenberg_is_fse_theme` being checked on core code base since it's not present there anyway? 

It's used to add an error when the user tries to activate a block theme without Gutenberg enabled (see https://core.trac.wordpress.org/ticket/53410)

**Comment by youknowriad** [comment]
@aristath interesting, why can't we just check the presence of the Gutenberg plugin, since this function can be iterated on and removed from Gutenberg?

**Comment by desrosj** [comment]
@youknowriad That was the original implementation in [Core-51193](https://core.trac.wordpress.org/changeset/51193). However, that won't work for any site running Gutenberg as an mu-plugin. I believe that the Gutenberg tests were broken because of [Core-51193](https://core.trac.wordpress.org/changeset/51193) since the plugin is tested as an mu-plugin.

[Core-51197](https://core.trac.wordpress.org/changeset/51197) changed to using a `function_exists()` check for `gutenberg_is_fse_theme()` since that will be more reliable.

**Comment by youknowriad** [comment]
Thanks for the explanation @desrosj . The reliability is arguable. it's a function in an evolving plugin, so it's subject to change right? and this PR is proving that as we'd have to update the core patch accordingly after this one lands.

I understand the logic though and I don't feel so strongly.

**Comment by desrosj** [comment]
I still feel that "Full Site Editing" refers to a specific feature, but I defer to the team about the proper naming for the related functionality. 

If we're going to change these names, we must do it prior to 5.8 RC1 so that we can make any adjustments needed to the check for the plugin. It's only meant to be in place until FSE is fully merged into Core, so it's temporary.

I've opened [Core-53515](https://core.trac.wordpress.org/ticket/53515) to explore how to improve the checks and the notice in 5.8.1.

**Comment by aristath** [comment]
I believe this was already done in core, so now would be the time to do this in the plugin as well.
I rebased the PR and tweaked things where necessary :+1:

**Comment by aristath** [comment]
Closing this one as it's no longer relevant

**Pull request closed without merging**
