### PR TITLE
Remove color, spacing, and layout options for Template Part block

### LINKED ISSUE #30732: Style changes made to template parts are only applied to one page
During a user testing session on April 9, following the FSE outreach program [testing call #4](https://make.wordpress.org/test/2021/03/25/fse-program-testing-call-4-building-a-restaurant-themed-header/), users worked with the header template part in the site editor. 

Several users described that when they changed the colors of the header (template part) and saved, the change was only visible on the page they had been working on (the index).

They expected the changes to be applied to all pages where this specific header (template part) was used.

----
Currently, only the content of a template part is update for all pages, not the styles.

### PR DESCRIPTION
**Pull request by jameskoster**
As discussed in https://github.com/WordPress/gutenberg/issues/30732, allowing folks to apply style to the template part block, _in addition_ to the styles within the template part can lead to confusion.

For example if you add a background color to your header template part whilst editing the Index template, that change will _only be applied to the Index template_. This is due to the block styles being local to the parent template rather than the template part. The confusion arises because this is conceptually antithetical with the idea of Template Parts existing as discrete global entities. When users edit their header, they expect those changes to be applied globally. To add even more confusion, when you then go to edit the template part in isolation your changes aren't present. This is highlighted in the following video:

https://user-images.githubusercontent.com/846565/142222017-c61916b3-668b-4767-873d-21b8904700bc.mp4

This PR removes those options from the block.

The main drawback here is that it removes the option of providing per-template-overrides for template parts, which can occasionally be a useful feature for theme authors. However this "feature" is ultimately the cause of the aforementioned confusion so an alternative is required. Fortunately it is very easy for theme authors to work around this by creating additional template parts as required, which is a practise more conceptually aligned with the Template Part featured anyway.

Unfortunately I can't think of a way to make this change backwards compatible, so would love to discuss options there.

### CODE REVIEW

**Comment by kjellr** [comment]
Just a heads up that we currently apply padding to just about every template part block in Twenty Twenty-Two.
For example:  

https://github.com/WordPress/twentytwentytwo/blob/76dc10d8fad1c3354bfd3dad19016547a39e0954/block-templates/index.html#L1

This is is primarily a stopgap until [a better solution to site padding is in place](https://github.com/WordPress/gutenberg/issues/35607). If this PR were to land before that, we'll need to probably add some additional Group wrapper blocks. We might need to do that anyway though — we apply layout to most of these blocks too, and we definitely want to preserve that behavior. 

Either way, just want to flag that this would require a bunch of Twenty Twenty-Two rework. (cc @jffng so you're aware too)

**Comment by jameskoster** [comment]
Yup, that's the drawback here. Any themes making use of this affordance would need to be slightly refactored. But like you said, it really should just be a case of adding a Group, and applying the styling to that instead.

**Comment by jameskoster** [comment]
One idea to provide backwards compatibility here would be to conditionally show/hide the UI rather than fully disabling the features.

So if a theme has set padding on the Header in the Page template, the padding control would be visible while editing that template. Otherwise the padding control is hidden from the UI and cannot be added.

Edit: A similar but more aggressive approach would be to make the feature code-only. So you can add padding to template parts in the template.html file, but users will not be able to change those values in the UI.

**Comment by shaunandrews** [comment]
This feels like the wrong solution to the problem.

> This is due to the block styles being local to the parent template rather than the template part.

This feels like the part that needs to be fixed. In many ways, I think of template parts like `div`'s, and as such, I should be able to apply options (like color, spacing, and layout) to a template part. Having to add an unnecessary Group block to resolve this feels like it defeats the purpose of the template part block.

I could actually see an argument that the current behavior is actually desirable, allowing one template part to behave differently depending on the template that contains it.

**Comment by jameskoster** [comment]
> This feels like the part that needs to be fixed

The thing is, block styles being local is fundamental principle of the block editor. We did explore making them "sync" with the template part so that they are applied globally in https://github.com/WordPress/gutenberg/issues/30732#issuecomment-958855550. 

But this means you'd lose the per-template override option, and surfaces a technical problem – it's not currently possible to apply styles to a _document_ (the template part in this case). So to do this we'd need to break an existing heuristic _and_ open a can of worms on the tech side. 

> I could actually see an argument that the current behavior is actually desirable, allowing one template part to behave differently depending on the template that contains it.

I agree it can be desirable, but not in the majority of cases. I don't think this should be the default behaviour. As outlined in #30732 the expectation is that any changes made to the template part are applied globally, which isn't what currently happens. 

We need to entertain both options – changes being local, or pushed upstream to the template part itself. The latter feels like it should be the default experience, and the former is a complex feature that needs more design consideration in order to make it feel intuitive.

All this considered, the additional group block feels like the lesser of two evils. It solves the original issue without breaking an existing convention or adding any technical overhead, and gives us time to work out the nuance of template part overrides.

**Comment by carolinan** [comment]
> Just a heads up that we currently apply padding to just about every template part block in Twenty Twenty-Two.

Sounds like it might be good to add it as a default in theme.json instead?

**Comment by kjellr** [comment]
> Sounds like it might be good to add it as a default in theme.json instead?

Maybe, but that seems like a tangent, and I hope it goes away entirely anyway. 😅

**Comment by overclokk** [comment]
I talk about this issue **9 months ago** (nine) https://github.com/WordPress/gutenberg/issues/29228 but no one listened to me and now problems are popping up like mushrooms, I'll repeat here, `wp:template-part` **must work** like [get_template_part()](https://developer.wordpress.org/reference/functions/get_template_part/) only includes the template you want to include and stop, no other behavior or it'll add side effect like this one, so please, **remove also the div wrapper** that is useless.

If you want to have a  different style for a template part in a specific page, create a new template part.

**Comment by ellenbauer** [comment]
> I could actually see an argument that the current behavior is actually desirable, allowing one template part to behave differently depending on the template that contains it.

That would be a smart approach in my opinion, as it would be cool to have the possibility to just change the background of a header template part without the need to create a second template part for the second color. This can add up to a lot of header template parts on a colorful website :)

**Comment by ellenbauer** [comment]
Can I add one question here: Would it still be possible to add a class name to wp:template-part even if color, spacing and layout options are not supported any longer?

**Comment by overclokk** [comment]
@ellenbauer If you need different style for a template part why not just using pattern instead of template part, wp:template-part should not add any style.

**Comment by ellenbauer** [comment]
@overclokk Thanks a lot for your answer, by pattern, do you mean the new pattern block?

**Comment by jameskoster** [comment]
> Would it still be possible to add a class name to wp:template-part even if color, spacing and layout options are not supported any longer?

Yes. The parent template is also added as a class to the `body` tag.

> If you need different style for a template part why not just using pattern instead of template part, wp:template-part should not add any style.

Another option would be to insert the template part inside a group, and add a background color to that group:

Screenshot 2021-11-22 at 10 20 00

**Comment by Andrew-Starr** [comment]
Yes please remove all styling options from `wp:template-part`

Like others have said, it will only get exponentially more confusing as more block themes are released, and more and more non-technical users begin activating them.

We need to get ahead of this now before it becomes too late to even consider reversing it.

Imagine a new WordPress user who changes the background color of the header template part on the index template, and their frustration when this change is not visible when viewing pages, posts etc.

Inevitably they will naturally assume there is a problem with the theme not working correctly.
How do we then explain to the user why this "issue" is happening, in a non-technical way that they can understand?

And then imagine having to provide ongoing help and support for this problem forever...

**Comment by overclokk** [comment]
@ellenbauer yes, the block pattern. Very usefull also for template variations.

**Comment by carolinan** [comment]
As it is still a container block, would it not need to keep the layout option? Or support it but not show the control.

**Review by aristath — APPROVED** [review]
I believe this is a change for the better and will reduce confusion. 👍 

Code-wise it's a minimal change and the code looks good.

**Comment by overclokk** [comment]
The div wrapper remains to be removed as well.

The `"tagName":"header"` I means.

**Comment by MaggieCabrera** [comment]
+1 on removing the div wrapper here

**Comment by aristath** [comment]
I'm not sure that removing the `tagName` (and therefore the wrapper) would be viable...
A template-part should be a `<header>`, `<main>`, `<footer>` or `<aside>` and without the `tagName` we won't be able to mark them as such. The `<div>` is a fallback and not the norm.

**Comment by overclokk** [comment]
@aristath  Yes, the template part can be anything you want (`<header>`, `<main>`, `<footer>` or `<aside>`) just using the group block as a wrapper inside the file itself, so this will also allow to better reusability of the file and less duplication.
So wp:template-part will allow only to include file just like `include*` or `require*` in PHP

**Comment by overclokk** [comment]
And in future we can think to makes `wp:template-part` more dynamic https://github.com/WordPress/gutenberg/issues/32939

**Comment by jameskoster** [comment]
Before merging this I'd like more input on backwards compatibility. Is there any way we can deprecate these tools so that themes that are using them still work the same, but the options disappear from the UI?

**Comment by overclokk** [comment]
@jameskoster it is still an alpha version and experimental, it is a matter of little refactoring of the html files.

**Comment by jameskoster** [comment]
That is true, but this is still arguably a breaking change for anyone using a block theme. So if we can mitigate any headaches that would be worthwhile.

**Comment by overclokk** [comment]
@jameskoster I agree with you but only if it was the stable version, in this case that is not even a beta a developer knows that the code could have changed, I'm a developer too but I prefer in this case to add less code as possible considering that we still are in time to make changes.

**Comment by ellenbauer** [comment]
I'm making the required changes in our block theme right now. So going forward we will only have something like:

`<!-- wp:template-part {"slug":"header"} /-->`
`<!-- wp:template-part {"slug":"footer"} /-->`

etc. Then I add the `"tagName":"header"` inside a group block. Is this approach the right one going forward? just to confirm I'm making the correct changes.

**Comment by aristath** [comment]
> etc. Then I add the "tagName":"header" inside a group block. Is this approach the right one going forward? just to confirm I'm making the correct changes.

Undecided.
This PR is about removing color, spacing & layout options from template-parts and has nothing to do with the `tagName`. Any discussion about the `tagName` should be held in a different, more related thread. It was mentioned here as a thought, but it doesn't belong here 👍

**Comment by overclokk** [comment]
@aristath and so be it https://github.com/WordPress/gutenberg/issues/36853 if all of you want to add something there you are welcome.

**Comment by overclokk** [comment]
@ellenbauer if you add template part like this `<!-- wp:template-part {"slug":"header"} /-->` the wrapper html element will fallback to a `div` element by default.

**Review by carolinan — APPROVED** [review]

**Comment by jameskoster** [comment]
Thanks for the ✅ @carolinan. 

It seems twenty twenty-two is ready for this change. I also tested a variety of FSE-tagged themes from the directory against this PR last Friday and didn't spot any major or unexpected issues. 

I'm going to merge this one now.

Edit: spoke too soon, merge conflicts to resolve first :d

**Comment by mtias** [comment]
Some context that wasn't incorporated in the discussion here is that template parts are also going to become viable style providers. What that means is that a `wp:template-part` node won't just be referencing inner blocks stored elsewhere, but also `wp_style` objects (think subsets of `theme.json`) if one exists for that same reference/slug. These template part style objects would allow configuring things like color palettes, default font sizes, etc, at the scope of a template part alone. This is definitely more of an advanced use case, but it's worth keeping in mind as it's not directly comparable to using a group within.

**Comment by jameskoster** [comment]
Seems like that would be a good point to explore in more detail the idea of local style overrides for template parts.

**Comment by carolinan** [comment]
In 5.9-RC1-52446, the color settings are not removed from the template part. Adding the backport to minor release label.

**Comment by dianeco** [comment]
Does it mean that these options will be available for WP 5.9 and later removed in a minor release?
If that's the case, IMO, it will be confusing for users who have previously built using these options to not be able to modify them anymore (or worse, if it changes the design of what they've created).

**Comment by jameskoster** [comment]
Agreed, this could cause a few headaches if it's not included in 5.9. Is it definitely too late? 🤔

**Comment by kjellr** [comment]
cc @noisysocks for thoughts about inclusion at this point. 

I do expect a major uptick in block theme creation as soon as 5.9 is released, and delaying this would potentially cause breakage later on. There's no really fallback in place, right? Once these features are removed, they're gone.

**Comment by noisysocks** [comment]
It should be okay to include this in RC 3 as I don't see any string changes or new code in the diff.

**Comment by carolinan** [comment]
That's a big relief. It did not get any traction when I brought it up on Slack.

**Pull request merged**
