### PR TITLE
Site editor: fix for how CSS Custom Properties are generated

### LINKED ISSUE #33300: Site editor: custom theme vars for block level not enqueued
## Description

The custom variables included in settings/blocks of theme.json are not included in the full site editor

## Step-by-step reproduction instructions

Include this in the `theme.json`

```json
{
    "version": 1,
    "settings": {
        "custom": {
                "my-own": {
                    "test": "root"
                }
        },
        "blocks": {
            "core/button": {
                "custom": {
                    "test": "button"
                }
            }
        }
    }
}
```

## Expected behaviour

The expected CSS output in the front-end and editors (post, site) is:

```css
body {
  --wp--custom--my-own--test: root;
}
.wp-block-button__link {
  --wp--custom--test: button;
}
```

## WordPress information

- WordPress version: 4.7.2
- Gutenberg version: 11.0.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information

- Device: laptop
- Operating system: Windows 10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/33300

### CODE REVIEW

**Comment by franmastromarino** [comment]
Great news!

**Review by jorgefilipecosta — COMMENTED** [review]
On my tests it seems --wp--custom--my-own--test is being correctly output on the site editor with this PR but the block level variable --wp--custom--my-own--test is still missing.

**Comment by oandregal** [comment]
> On my tests it seems --wp--custom--my-own--test is being correctly output on the site editor with this PR but the block level variable --wp--custom--my-own--test is still missing.

It works for me :thinking: This is my setup:

- The latest WordPress version.
- Empty theme with this `theme.json`:

```
{
	"version": 1,
	"settings": {
		"color": {
			"gradients": [],
			"link": true,
			"palette": []
		},
		"spacing": {
			"customPadding": true
		},
		"typography": {
			"customLineHeight": true,
			"fontFamilies": [],
			"fontSizes": []
		},
		"layout": {
			"contentSize": "840px",
			"wideSize": "1100px"
		},
		"custom": {
			"my-own": {
				"test": "root"
			}
		},
		"blocks": {
			"core/button": {
				"custom": {
					"test": "button"
				}
			}
		}
	}
}
```

For me, the resulting CSS in the site editor is this:

```css
body {
  --wp--preset--color--black: #000000;
  --wp--preset--color--cyan-bluish-gray: #abb8c3;
  --wp--preset--color--white: #ffffff;
  --wp--preset--color--pale-pink: #f78da7;
  --wp--preset--color--vivid-red: #cf2e2e;
  --wp--preset--color--luminous-vivid-orange: #ff6900;
  --wp--preset--color--luminous-vivid-amber: #fcb900;
  --wp--preset--color--light-green-cyan: #7bdcb5;
  --wp--preset--color--vivid-green-cyan: #00d084;
  --wp--preset--color--pale-cyan-blue: #8ed1fc;
  --wp--preset--color--vivid-cyan-blue: #0693e3;
  --wp--preset--color--vivid-purple: #9b51e0;
  --wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(
    135deg,
    rgba(6, 147, 227, 1) 0%,
    rgb(155, 81, 224) 100%
  );
  --wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(
    135deg,
    rgb(122, 220, 180) 0%,
    rgb(0, 208, 130) 100%
  );
  --wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(
    135deg,
    rgba(252, 185, 0, 1) 0%,
    rgba(255, 105, 0, 1) 100%
  );
  --wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(
    135deg,
    rgba(255, 105, 0, 1) 0%,
    rgb(207, 46, 46) 100%
  );
  --wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(
    135deg,
    rgb(238, 238, 238) 0%,
    rgb(169, 184, 195) 100%
  );
  --wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(
    135deg,
    rgb(74, 234, 220) 0%,
    rgb(151, 120, 209) 20%,
    rgb(207, 42, 186) 40%,
    rgb(238, 44, 130) 60%,
    rgb(251, 105, 98) 80%,
    rgb(254, 248, 76) 100%
  );
  --wp--preset--gradient--blush-light-purple: linear-gradient(
    135deg,
    rgb(255, 206, 236) 0%,
    rgb(152, 150, 240) 100%
  );
  --wp--preset--gradient--blush-bordeaux: linear-gradient(
    135deg,
    rgb(254, 205, 165) 0%,
    rgb(254, 45, 45) 50%,
    rgb(107, 0, 62) 100%
  );
  --wp--preset--gradient--luminous-dusk: linear-gradient(
    135deg,
    rgb(255, 203, 112) 0%,
    rgb(199, 81, 192) 50%,
    rgb(65, 88, 208) 100%
  );
  --wp--preset--gradient--pale-ocean: linear-gradient(
    135deg,
    rgb(255, 245, 203) 0%,
    rgb(182, 227, 212) 50%,
    rgb(51, 167, 181) 100%
  );
  --wp--preset--gradient--electric-grass: linear-gradient(
    135deg,
    rgb(202, 248, 128) 0%,
    rgb(113, 206, 126) 100%
  );
  --wp--preset--gradient--midnight: linear-gradient(
    135deg,
    rgb(2, 3, 129) 0%,
    rgb(40, 116, 252) 100%
  );
  --wp--preset--font-size--small: 13px;
  --wp--preset--font-size--normal: 16px;
  --wp--preset--font-size--medium: 20px;
  --wp--preset--font-size--large: 36px;
  --wp--preset--font-size--huge: 42px;
  --wp--custom--my-own--test: root;
}
.wp-block-button__link {
  --wp--custom--test: button;
}
```

Can you perhaps try with that setup? Or share if you have anything different?

**Comment by oandregal** [comment]
@jorgefilipecosta would you be able to share your steps and environment to see why/where it fails for you?

**Review by jorgefilipecosta — APPROVED** [review]
I did a new set of tests and everything seems fine 👍  I probably did something wrong on my first test.

**Pull request merged**
