### PR TITLE
Embed: use 100% width for iframe.

### PR DESCRIPTION
**Pull request by mtias**
image

### CODE REVIEW

**Comment by jasmussen** [comment]
Works well for me! 👍

**Comment by mtias** [comment]
Do you anticipate the generic width rule to have issues elsewhere?

**Comment by jasmussen** [comment]
No, not width. Height, perhaps, but none that I can think of.

**Comment by mtias** [comment]
Ok, will merge.

**Comment by aduth** [comment]
I think `ResponsiveWrapper` would serve well for embed iframes, since it can handle adjusting both height and width of the frame for smaller viewports if the natural dimensions are known:

https://github.com/WordPress/gutenberg/tree/master/components/responsive-wrapper

(Should write some docs 😄 )

**Comment by youknowriad** [comment]
@aduth should we use Stroybook or write our own devdocs like calypso

**Comment by aduth** [comment]
@youknowriad Would be interesting to explore, certainly. I think now that things have started to settle a bit more and documentation is clearly a pain point of past JavaScript in core, we have some good opportunities to showcase automated documentation. This is where I'm starting to go with #989, hoping to turn it into a function reference for eventual integration into [the WordPress code reference](https://developer.wordpress.org/reference/). Something to what we did with [Selectors DevDocs](https://wpcalypso.wordpress.com/devdocs/selectors/). We should probably reach out to the Documentation team to start coordinating too.

**Pull request merged**
