### PR TITLE
Remove the nux package

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

This package has been marked for removal for WordPress 6.2. There's no precedent on how to proceed with package removals. I've elected to remove it entirely to cleanup the repository properly. Let me know if you think there are any downsides to this. Also I think we have tools that rely on the presence of the folders so better to get rid of it to avoid performing builds... for this folder.

We'd need to follow-up on this on WordPress Core to actually remove the dependency and the script handle.

### CODE REVIEW

**Comment by noisysocks** [comment]
Won't doing this break backwards compatibility for `wp.nux`? Or is it safe because no plugins use this?

**Comment by youknowriad** [comment]
> Won't doing this break backwards compatibility for wp.nux? Or is it safe because no plugins use this?

It is a breaking change, the idea is that it's low impact and that the developers have been notified about it for a long time now. (At least 26 months)

**Comment by fabiankaegy** [comment]
I don't have a real opinion for how to best deal with this. Just wanted to share the usage data here in the ticket:

- [`@wordpress/nux`](https://www.wpdirectory.net/search/01GK15W6PTWFSXZ0J7EN899EYG) - 328 matches
- [`wp.nux`](https://www.wpdirectory.net/search/01GK15X4H2A5E53Z0WKRPYAM8S) - 29 matches

**Comment by youknowriad** [comment]
Thanks for the links @fabiankaegy that's very helpful.

I tried to go through the results to assess how valid are these results. I found that most of the results (like 99%) of the `@wordpress/nux` search query are due to some kind of build tool that automatically adds the package to the package.json debs even if the plugin don't use it. I believe it's better to focus on the second set of results (`wp.nux` or `wp-nux` which both give the exact same results)

So for the second search query, a number of plugins mention `wp-nux` as a dependency. So we need to ensure that the parent script is still loaded even if a dependency is not present. If it's not the case by default we can keep an empty script attached to the wp-nux handle around.

Other than that, there seem to be only two plugins that may be using the wp.nux global:

 - The WordPress Editing Toolkit (I can get this plugin to update their usage)
 - UltraBlocks – Advanced Blocks for WP Gutenberg (I was not able to confirm whether they really use it because the link to open the code breaks, so we might want to check with them when this PR lands. I know @annezazu usually helps with this kind of outreach)

**Review by jorgefilipecosta — APPROVED** [review]
The code changes look good to me, and we have the plan to warn the possible user of the package, so it seems this change can be merged.

**Comment by noisysocks** [comment]
> So for the second search query, a number of plugins mention `wp-nux` as a dependency. So we need to ensure that the parent script is still loaded even if a dependency is not present. If it's not the case by default we can keep an empty script attached to the wp-nux handle around.

👍 makes sense. Might be worth preparing the Core patch now.

**Comment by youknowriad** [comment]
I'll see if I can prepare the core patch

**Comment by youknowriad** [comment]
Core patch available here https://github.com/WordPress/wordpress-develop/pull/3775

**Comment by tyxla** [comment]
Thanks @youknowriad 🙌

**Comment by annezazu** [comment]
>UltraBlocks – Advanced Blocks for WP Gutenberg (I was not able to confirm whether they really use it because the link to open the code breaks, so we might want to check with them when this PR lands. I know @annezazu usually helps with this kind of outreach)

I have reached out to them :) Apologies for the delay here. I accidentally marked this as read and happened to stumble back on it.

**Pull request merged**
