### PR TITLE
Cherry pick "Stabilise role attribute property (#65484)"

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Cherry-pick #65484 manually and resolve the conflict.

I think we should retain the original commit message and the props when merging too? 🤔 

## Why?

See https://github.com/WordPress/gutenberg/pull/65484#issuecomment-2371161703.

## How?

I left out some changes in https://github.com/WordPress/gutenberg/pull/65518 that's not in the  release branch. Do we want to also backport that PR?

## Testing Instructions

CI should pass.

### CODE REVIEW

**Comment by getdave** [comment]
Thanks @kevin940726. Sorry I didn't get around to this before you did.

**Comment by Mamaduka** [comment]
@kevin940726, do you mind including these two follow-ups in this PR, #65616 and #65617? 🙇

**Comment by noisysocks** [comment]
> do you mind including these two follow-ups in this PR, https://github.com/WordPress/gutenberg/pull/65616 and https://github.com/WordPress/gutenberg/pull/65617? 🙇

I'm on it.

**Comment by noisysocks** [comment]
Actually, I'll cherry pick those separately so the history doesn't get squashed.

**Review by noisysocks — APPROVED** [review]

**Pull request merged**
