### PR TITLE
Editor Onboarding: "The Basics" help section - Details Part 2

### LINKED ISSUE #30626: Add “The basics” Help Section Articles
## What problem does this address?
The mobile editor is a powerful tool for creating content, but many users fail to understand the extent of what they can do with it. 

## What is your proposed solution?
We will add a Help section that provides additional details on common tasks related to adding, editing, and removing blocks. This iteration will be limited to the "The basics" articles section.

Mobile help section articles

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/3824
* https://github.com/wordpress-mobile/WordPress-iOS/pull/17008
* https://github.com/wordpress-mobile/WordPress-Android/pull/15164

## Description
Fixes https://github.com/WordPress/gutenberg/issues/30626. Iterates upon the work completed in https://github.com/WordPress/gutenberg/pull/33790. This work improves accessibility, copy, and design of the editor help section. 

## How has this been tested?

⚠️ The Editor Onboarding features, including the Help button, are only available to 50% of users based on user ID. You must be logged into a WPCom account or receive a anonymous ID that is included in the cohort. 

<details><summary>Help Section: Visual</summary>

1. Install builds for iOS and Android from the sibling PRs. 
2. Launch the post editor. 
3. Tap the three-dot menu in the top right corner. 
4. Tap Help. 
5. ℹ️ **Expected:** Navigating to each topic results in the correct content is displayed. 
6. Close the editor. 
7. Enable dark mode of the device.
8. Repeat steps 2-5. 

</details>

<details><summary>Help Section: Audible</summary>

1. Install builds for iOS and Android from the sibling PRs. 
2. Launch the post editor. 
3. Enable VoiceOver/TalkBack. 
4. Select and activate the three-dot menu in the top right corner. 
5. Select and activate Help.
6. ℹ️ **Expected:** Navigating and comprehending each topic is easy with the screen reader. 

</details>

<details><summary>Existing Bottom Sheet Headers</summary>

1. Install builds for iOS and Android from the sibling PRs. 
2. Launch the post editor. 
3. Add a Paragraph block. 
4. Tap Link button in toolbar. 
5. Tap Link to Cell. 
6. ℹ️ **Expected:** Verify the Cancel/X button, title, and Apply/Checkmark button all render and function as expected. 
7. Add a Cover block. 
8. Add background media. 
9. Tap block settings button. 
10. Tap Edit focal point. 
11. ℹ️ **Expected:** Verify the Cancel/X button, title, and Apply/Checkmark button all render and function as expected. 

</details>

## Screenshots 

<details><summary>UX Interactions</summary>

https://user-images.githubusercontent.com/438664/130818291-58a4a8d0-43f4-457a-9dd9-8c1315143a1c.MP4

</details>

<details><summary>Screenshots</summary>

| iOS | Android |
| --- | --- |
| help-index-ios | help-index-android |
| help-index-ios-dark | help-index-android-dark |
| help-detail-ios | help-detail-android |
| help-detail-ios-dark | help-detail-android-dark |

</details>

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
Wow, the help section is great! Feel like the type of onboarding to introduce in other aspects of the app too!

I made a quick pass using the [WPAndroid installable build 113968](https://113968-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-15164-build-113968.apk) (I understand @jhnstn will also do his passes too), and here are my notes. Most are about the UX so, pinging both @kyleaparker and @dcalhoun on this 👍

### Potential blockers
1. Looks like there's an issue with navigating between the topics where the topic shown is now actually the one tapped on. Steps to reproduce:
  a. Tap on "What is a block?"
  b. The correct help section is shown ("Welcome to the world of blocks...")
  c. Tap on the back button on the Android bottom bar to return to the help sections list
  d. Tap on the "Add blocks" topic
  e. Notice that the "What is a block?" section is shown again 💥

2. The bottomsheet title reads "How to edit your site" when editing a post. Not sure if that's intended? Maybe we'd expect a "How to edit your post"? in that case?
2. The "back" navigation button in the bottomsheet header is presenting too small of a git target. Is this something we can work on before the releasing the feature? See the video where the white circle is my tapping and only when I'm getting very close to the back arrow the tap is triggering the nav action:

https://user-images.githubusercontent.com/1032913/129372171-97af2def-48ef-4fa6-8ace-20bc7775d116.mp4


## Non blocking (non-blockers for this PR or out-of-scope)

1. In Dark Mode, the image assets don't blend too well since they depict the blocks in light mode. I think this is probably highly subjective and just wanted to put it out there.
2. For a couple of the current help topics, we show the same screenshot of the 3-dot block toolbar button, which is the first step for navigating to the option at hand. I understand that since the options are actually in bottomsheets the screenshots wouldn't be compact enough if we depicted both the 3-dot menu and the bottomsheet. I wonder though if we could improve this somehow. For example, show the bottomsheet option in some kind of inset or overlay along with the 3-dot menu.
3. Known from [other places as well](https://href.li/?https://github.com/WordPress/gutenberg/issues/32409) but looks like the bright-and-full-width image asset in the "What is a block?" topic doesn't allow the scrollbar to be too visible on Android dark mode. I think it's outside the scope of this PR but I wonder if there's anything quick we can do for improving this? cc @kyleaparker . See the following screengrab of the issue on my Pixel 2XL in dark mode where the ephemeral scrollbar is only adding a barely noticeable tint over the underlying image:



4. The "The basics" group title makes me expect more groups and I was scrolling to find them. No strong feelings but, maybe we don't need it as long as we have only one group? Perhaps we can introduce it when we'll add more groups?

4. Enhancement idea: with the amount of prose in the sections, I wonder if it makes sense to try and make the text selectable (think: long-clicking to select some words) to enable searching the web for terms. I find myself doing that quite often on the web (browsers) and I wonder if it makes sense here too?

I'll pause at this point as the comment is already getting too big, sorry about that. Let me know if anything is unclear, thanks!

**Comment by dcalhoun** [comment]
Thanks for the review, @hypest. 🙇🏻 

## Potential Blockers

> 1. Looks like there's an issue with navigating between the topics where the topic shown is now actually the one tapped on.

Good catch. I was able to reproduce this and it appears to be specific to the Android bottom bar back button. I'll investigate. 

> 2. The bottomsheet title reads "How to edit your site" when editing a post. Not sure if that's intended? Maybe we'd expect a "How to edit your post"? in that case?

The copy is from the design comps, but I agree the copy could be misinterpreted. I suppose the editor context could either be a post or page. I believe we could use the `postType` to have a title match the context with "How to edit your post/page." 

> 3. The "back" navigation button in the bottomsheet header is presenting too small of a git target. Is this something we can work on before the releasing the feature? 

It does appear the smaller back button target is fairly small throughout the app for other bottom sheets as well. I will attempt to improve this. 

## Non-Blockers

> 1. In Dark Mode, the image assets don't blend too well since they depict the blocks in light mode. I think this is probably highly subjective and just wanted to put it out there.

I agree, the images do have a high amount of contrast in Dark Mode. @kyleaparker if you agree and are willing to create Dark Mode visual illustrations, we could likely swap out the images based upon the Dark Mode setting fairly easily. The only downside I perceive is that we'd double the amount of images we bundle with the app. 

> 2. For a couple of the current help topics, we show the same screenshot of the 3-dot block toolbar button, which is the first step for navigating to the option at hand. I understand that since the options are actually in bottomsheets the screenshots wouldn't be compact enough if we depicted both the 3-dot menu and the bottomsheet. I wonder though if we could improve this somehow. For example, show the bottomsheet option in some kind of inset or overlay along with the 3-dot menu.

I am struggling to follow and identify what you are referencing with this comment. Would you be willing to elaborate further please? 
 
> 4. The "The basics" group title makes me expect more groups and I was scrolling to find them. No strong feelings but, maybe we don't need it as long as we have only one group? Perhaps we can introduce it when we'll add more groups?

That makes sense to me. It is easy to remove. @kyleaparker WDYT about removing the section heading for now? 

> 5. Enhancement idea: with the amount of prose in the sections, I wonder if it makes sense to try and make the text selectable (think: long-clicking to select some words) to enable searching the web for terms. I find myself doing that quite often on the web (browsers) and I wonder if it makes sense here too?

This could be a nice enhancement. From researching briefly, we could [enable `selectable`](https://reactnative.dev/docs/text#selectable), which allows Android to select/copy as expected (although I only got it to work once, maybe nested `Touchable`s could be causing issue 😕). However, iOS [only supports](https://github.com/facebook/react-native/issues/13938) copying the entirety of a given `Text` element. There is [a workaround to enable selection for iOS](https://github.com/facebook/react-native/issues/13938#issuecomment-520590673), but I am not sure it is worth its weight. There is a [feature request](https://react-native.canny.io/feature-requests/p/support-selecting-text-within-text-elements-for-copypaste-etc) to improve this, but it is fairly old. Enabling `selectable` could be a good first improvement. WDYT?

**Comment by hypest** [comment]
> I believe we could use the postType to have a title match the context with "How to edit your post/page."

That would work yeah, and now I wonder if we can instead just go with a slightly more general title, to avoid having to specialize it. Like, how about "How to edit content". Totally open for more ideas, it feels we should be able to find one that is general enough but usable.

> It does appear the smaller back button target is fairly small throughout the app for other bottom sheets as well. I will attempt to improve this.

Thanks! It's almost out-of-scope for this PR but yeah, since the user would probably navigate through the sections exploring the info, the small hit target can get frustrating. Sounds like something to try to tackle in a timebox manner and take it to a separate PR if it proves too much for this PR.

> I am struggling to follow and identify what you are referencing with this comment. Would you be willing to elaborate further please?

Oh sorry. I was referring to the ["Remove blocks" asset](https://github.com/WordPress/gutenberg/blob/update/editor-onboarding-help-detail-view/packages/editor/src/components/editor-help/images/remove-blocks.png) and how we use the same in the "Customize blocks" case. I was mistaken there though: we are not using the same asset. I guess that glancing at those 2 assets wasn't enough for me to see that in the Customize Blocks one the blue dot is trying to indicate the cog icon, not the 3-dot menu :(.

> Enabling selectable could be a good first improvement. WDYT?

Thanks for looking into that already David! Since word-level is not yet well supported, it's better to leave this for a separate discussion, perhaps trying out the `selectable` in a demo build and feel it out. At this stage, I think the most we should add to the effort is to open an enhancement ticket. I can do that and link it here.

**Comment by kyleaparker** [comment]
>The bottomsheet title reads "How to edit your site" when editing a post. Not sure if that's intended? Maybe we'd expect a "How to edit your post"? in that case?

We can change it so it's more contextual for now and say "How to edit your post" or "How to edit your page". The thought behind the original title was that this would be relevant with FSE when people are focused on creating or editing their website. Most people talk about editing their website rather than posts/pages. 

> In Dark Mode, the image assets don't blend too well since they depict the blocks in light mode. I think this is probably highly subjective and just wanted to put it out there.

If I make dark versions of each image are they easy to switch out?

>For a couple of the current help topics, we show the same screenshot of the 3-dot block toolbar button, which is the first step for navigating to the option at hand. I understand that since the options are actually in bottomsheets the screenshots wouldn't be compact enough if we depicted both the 3-dot menu and the bottomsheet. I wonder though if we could improve this somehow. For example, show the bottomsheet option in some kind of inset or overlay along with the 3-dot menu.

As a future iteration we could use animations instead of static images. The dot is also meant to help people with the first step of knowing where to go to find certain actions and I had originally imagined it as a pulsating dot to draw the eye a bit more. 

>Known from other places as well but looks like the bright-and-full-width image asset in the "What is a block?" topic doesn't allow the scrollbar to be too visible on Android dark mode. I think it's outside the scope of this PR but I wonder if there's anything quick we can do for improving this? cc @kyleaparker . See the following screengrab of the issue on my Pixel 2XL in dark mode where the ephemeral scrollbar is only adding a barely noticeable tint over the underlying image:

We are planning to try out a full height bottomsheet which may fix this issue

**Comment by dcalhoun** [comment]
> If I make dark versions of each image are they easy to switch out?

@kyleaparker yes, from a quick exploration, I believe swapping images for Dark Mode should be an easy switch. 

> > [...] See the following screengrab of the issue on my Pixel 2XL in dark mode where the ephemeral scrollbar is only adding a barely noticeable tint over the underlying image:
> 
> We are planning to try out a full height bottomsheet which may fix this issue

The "What is a block?" content in particular will likely always exceed the height of a small device. Also, landscape orientation may experience overflow more often. So, this may still remain an issue in some contexts. That said, my suggestion would be to consider it out of scope for this work and an opportunity for further improvement later.

**Comment by dcalhoun** [comment]
@hypest @kyleaparker I believe I have addressed the feedback and agreements so far. I am going to consider all other feedback as non-blocking, and opportunities for future improvement. Please let me know if I am mistaken, as I have also requested @jhnstn provide his review so that we can move towards merging this work when possible. Thanks! 

## Completed Improvements

* Fix Android hardware back button: https://github.com/WordPress/gutenberg/pull/34018/commits/de431c21457b0de704505e1917305af4b6115b68
* Add back button to bottom sheet:  https://github.com/WordPress/gutenberg/pull/34018/commits/cc045baa9ed76ff42acadeb8486bd1853c7df330
* Help section title adapts to post/page context: https://github.com/WordPress/gutenberg/pull/34018/commits/dd5c7d86876ee70ffe47457d0e96f8b7b605d62d
* Remove the unnecessary "The basics" section title: https://github.com/WordPress/gutenberg/pull/34018/commits/6371410dd3790b640f4d8f1a1746509491f9655c
* Enable text selection in Help articles: https://github.com/WordPress/gutenberg/pull/34018/commits/d6baa7aa285504a9e81b78168c81bf61304a031c
* Increase size of navigation header tap targets: https://github.com/WordPress/gutenberg/pull/34018/commits/c24c06e619f53132fb5c02a433eac249df950c71

## Future Improvements Opportunities

* New images for Dark Mode. 
* Improve scroll bar visibility atop full-width images. 
* Improve text selection for iOS.

**Review by jhnstn — APPROVED** [review]
Code changes LGTM, I've run through the testing steps on both iOS and Android. Everything is working as expected. Nice work!

**Comment by hypest** [comment]
> Improve scroll bar visibility atop full-width images.

Just wanted to link to a [relevant ticket and decision here](https://github.com/WordPress/gutenberg/issues/32409#issuecomment-902707368) where we'll be adding some scrollbar related tweaks to improve visibility and we could do the same in the help sections too.

**Pull request merged**
