### PR TITLE
Add an interactive variant to `@wordpress/create-block`

### PR DESCRIPTION
**Pull request by luisherranz**
## What?

Add an `interactive` variant to the `@wordpress/create-block` package.

## Why?

So people can use this variant to start testing the Interactivity API.

## How?

I followed what @ryanwelcher did in [this PR](https://github.com/WordPress/gutenberg/pull/41289) and added a new variant for an `interactive` block.

I also added the possibility of adding a `viewScript` field to the `block.json` file.

## Testing Instructions

- Run the `@wordpress/create-block` package using:
  - `cd packages/create-block`
  - `node index.js`
- Choose the `interactive` variant.
- Fill in the rest of the answers.
- Take a look at the files:
  - The `block.json` should have `supports.interactivity: true` and a `viewScript` field.
  - The `render.php` file should contain directives.
  - There should be a `view.js` file with an import of `@wordpress/interactivity` and a call to `store()`.

If you want to try that the interactivity works, you can use `wp-now`:

- `cd (installation directory) && npm start`
- `npx @wp-now/wp-now start` (in another terminal)
- Go to wp-admin
- Install Gutenberg 16.2 or higher
- Add a new post or edit an existing one
- Add the new block
- Save the post
- Go to the frontend
- Check that the toggle works

## Screenshots or screencast 

<a href="https://www.loom.com/share/3680f3b779e14306b8a7fd5bb484988c">
    
  </a>

https://www.loom.com/share/3680f3b779e14306b8a7fd5bb484988c

## Questions

- Do we want to install `wp-now` and add npm scripts to run it?
- If so, only for the interactive or for all the examples?
- Is it enough with this basic example?

### CODE REVIEW

**Comment by luisherranz** [comment]
Another question: This variant requires Gutenberg (16.2+). Where should we inform the user that Gutenberg needs to be installed in other for this to work?

**Comment by juanmaguitar** [comment]
Given the current state of the Interactivity API package (still [experimental](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/README.md)), I wouldn't create a `variant`  but a `template` (as explained [here](https://github.com/WordPress/gutenberg/blob/98c01fd86022d91fb8eebc41fdc07bbca6651117/packages/create-block/docs/external-template.md)) and publish it as an NPM package.
In this way, people will have the option to create a boilerplate for an interactive block (via template) but the default behavior will remain the same. 

Also, ideally, this `template` would include a `README.md` (in the generated folder for the block) with all pertinent explanations for the block to properly work (like the Gutenberg 16.2 dependency)

I think having a direct `interactive` variant may be confusing right now. When the interactivity API is properly merged into core then it could be the right time to create a `variant`.

**Comment by ryanwelcher** [comment]
The code looks good to me. This package will be published with the next GB release so it would contain this variant before the API that is leverages is available in core. I agree with @juanmaguitar that it would be better to create an [External Template](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/packages-create-block-external-template/) and then move it into the package once the API has landed.

**Review by ryanwelcher — COMMENTED** [review]
The code looks good to me. However, I agree with @juanmaguitar that this is probably better as a template until the API is available in core. One benefit of using it's own template is that we can introduce any number of variants to show different and more complex examples

**Comment by luisherranz** [comment]
Ok, thanks for your feedback. I'll migrate this to a template and we'll merge this variant at a later point 🙂

**Comment by juanmaguitar** [comment]
@luisherranz to speed up things, I have created this PR https://github.com/WordPress/gutenberg/pull/52549 over `create-block-interactive-template` branch with the proper modifications to "migrate" this code to a template.

**Comment by luisherranz** [comment]
Awesome. Thank you, Juanma.

**Pull request closed without merging**
