### PR TITLE
New block: Post navigation

### LINKED ISSUE #55157: Insert post navigation links as two links inside a <nav> element
## What problem does this address?
The post navigation link block: AKA the next and previous post links for single posts, can be difficult for users to insert correctly, because you need to add two copies of the block and then change one of the variations.

For the next and previous navigation to be as accessible as possible, both blocks needs to be placed inside a `<nav> `element.
While the user can place the blocks inside a group, the group does not have an interface for changing the element from a `<div>` to a `<nav>`. It can only be done by changing the code in the code editor. This limitation was created on purpose because you need advanced knowledge of when to use the `<nav>` to not cause unintended accessibility problems.

You can compare this with inserting the query pagination block. This block already uses a nav, and the three inner blocks are placed together: Next page, the paginated links, and previous page.

## What is your proposed solution?

Instead of the inserter adding the individual next and previous links, it should prioritise a pattern where both blocks are placed in a way that ensures accessible markup.

In the example pattern below, note that besides the `<nav>` element, a unique, identifying aria label is added to the group:

```
<?php
/**
 * Title: Post navigation
 * slug: twentytwentyfour/post-navigation
 * inserter: no
 */
?>

<!-- wp:group {"tagName":"nav","ariaLabel":"<?php esc_attr_e( 'Posts', 'twentytwentyfour' ); ?>","style":{"spacing":{"padding":{"bottom":"0vh"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"space-between"}} -->
<nav class="wp-block-group" style="padding-bottom:0vh" aria-label="<?php esc_attr_e( 'Posts', 'twentytwentyfour' ); ?>">
<!-- wp:post-navigation-link {"type":"previous","label":"<?php echo esc_html_x( 'Previous: ', 'Label before the title of the previous post. There is a space after the colon.', 'twentytwentyfour' ); ?>","showTitle":true,"linkLabel":true,"arrow":"arrow"} /-->
<!-- wp:post-navigation-link {"label":"<?php echo esc_html_x( 'Next: ', 'Label before the title of the next post. There is a space after the colon.', 'twentytwentyfour' ); ?>","showTitle":true,"linkLabel":true,"arrow":"arrow"} /-->
</nav>
<!-- /wp:group -->
```

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Closes https://github.com/WordPress/gutenberg/issues/55157

The purpose of adding this new block is to:

- Make it easier for users to add both the next and the previous posts links together, instead of having to insert two separate blocks and (commonly) wrap them inside a group/row/stack/column to position them.
-  Improve the accessibility of the post navigation

## Why?

- Navigations should be wrapped inside a `<nav> `element.
- Needing to add the next and previous posts blocks separately is time consuming.
- The most common use case is to have both a previous and next post link in your template, not just one of them.
- It makes the post navigation work more like the query pagination, which already uses a wrapper.

## How?

Adds a new block called Post Navigation.
The block adds a `<nav>` element and inserts two post navigation link blocks as inner blocks.
One of the inner blocks is of the "previous" block variation.
The block supports adding an aria label. The user can add a "navigation name" in the Advanced panel.
The block also supports color and typography options.

##  Note on accessibility
While using a nav element is an improvement, this block is still not as accessible as the post navigation function that is available for classic themes, because it does not have a visually hidden heading inside the nav element, above the links.
[the_post_navigation](https://developer.wordpress.org/reference/functions/the_post_navigation/)
[get_the_post_navigation](https://developer.wordpress.org/reference/functions/get_the_post_navigation/)
[navigation markup](https://developer.wordpress.org/reference/functions/_navigation_markup/)

## Testing Instructions
Activate a block theme.
The post navigation block can be tested using a single post, or the single post template.
Add the block.

Confirm that:
- Both the next and previous post navigation links show in the editor.
- The toolbar options work.
- The setting panel options work.
- The blocks and their settings display correctly on the front.

### Testing Instructions for Screen readers

Activate a block theme.
The post navigation block can be tested using a single post, or the single post template.
Add the block.
Save and go to the front of the website.
Navigate to where you placed the block.
Confirm that the first of the two links are announced as part of a navigation, and that the aria label is announced.
If you did not change the aria label in the blocks Advanced panel, the default label is "Posts".

## Screenshots or screencast 
The Post Navigation block in the Site Editor, with the list view and settings panel opened.

### CODE REVIEW

**Comment by fabiankaegy** [comment]
Hey @carolinan 👋 

Would it be possible to have this be a pattern that consists of a row block with the tag name set to `nav` instead? 

I'm not sure a custom block is the right answer for the valid issue you point out :)

**Comment by carolinan** [comment]
The reason for that is in the linked issue.
The patterns are not surfaced the same way as blocks and are more difficult to find. And having the block would make it consistent with the query pagination.

**Comment by carolinan** [comment]
I would still prefer for this to be a block, but how does one even add a new core pattern? Are they added by issues and PR's to the pattern directory repository?

**Comment by talldan** [comment]
> I would still prefer for this to be a block, but how does one even add a new core pattern?

There are a mixture of ways at the moment. There are some in the `block-patterns` folder in core:
https://github.com/WordPress/wordpress-develop/tree/trunk/src/wp-includes/block-patterns

They're registered here:
https://github.com/WordPress/wordpress-develop/blob/e3e7fdbf7c3fd9f04871118a16b98f1544e94984/src/wp-includes/block-patterns.php#L18-L37

The majority are registered from the pattern directory, those that are 'featured' or have the 'core' keyword:
https://github.com/WordPress/wordpress-develop/blob/e3e7fdbf7c3fd9f04871118a16b98f1544e94984/src/wp-includes/block-patterns.php#L211-L287

These patterns are only loaded when `core-block-patterns` support is active.

I'm not sure what the preference is for adding new bundled patterns. This one seems more like a useful utility pattern rather than the more stylistic patterns in the directory, so maybe the first way?

edit: also just to mentioned that if you wanted to experiment with adding the pattern in the gutenberg plugin to start with, it should be possible to add code similar to how those core patterns are loaded in a `lib/compat/wordpress-6.7` folder

**Comment by carolinan** [comment]
I still disagree that this should be a pattern and not a block. It is an accessibility issue that the individual blocks are added without the nav element.

It would be good to document how to add a new pattern.

**Comment by talldan** [comment]
> I still disagree that this should be a pattern and not a block. It is an accessibility issue that the individual blocks are added without the nav element.

Sounds like a good argument for it being a block. Group doesn't support `nav`, and I don't think there are options for making blocks visually hidden (for the heading), so it'd be hard to make a pattern work.

If you go with the blocks approach, could it be worth also making the `post-navigation-link` blocks only insertable as a child of this new block (using the `parent` block property)? That way it'd also help to reduce the number of blocks available globally and enforce the accessibility concerns.

**Comment by carolinan** [comment]
<del>It is possible to only have one of the links, and then the nav may not be the correct element to use.</del>

**Edit:** Actually there are of course situations where this will only show one link: when there are no previous or no next posts, so ignore the comment above.

But should we remove the ability to only insert one of them?

**Comment by talldan** [comment]
> Edit: Actually there are of course situations where this will only show one link: when there are no previous or no next posts, so ignore the comment above.

> But should we remove the ability to only insert one of them?

Are you saying that when there's only one link, there shouldn't be a wrapping `nav` element?

If so, would being able to insert those blocks alone solve that issue? I think the templated blocks for pagination will be the same, whether at the the start, middle, or end of pagination. The blocks themselves would require some conditional logic on what to display.

**Comment by carolinan** [comment]
No, I am saying ignore the comment about not using nav when it only contains one link :)

**Comment by ntsekouras** [comment]
>No, I am saying ignore the comment about not using nav when it only contains one link :)

So is having a `nav` for a single item is acceptable a11y wise? I couldn't see something specific in the [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav). If yes, should we just wrap the individual blocks with `nav`?

**Comment by carolinan** [comment]
It might be valid HTML, but no, because both links are part of the same navigation.
It should work the same as the query pagination.

**Comment by carolinan** [comment]
I made the following changes:

- Added post navigation as the parent for post navigation link.
- Removed the template lock from post navigation so that the inner blocks can be deleted.

The behavior of the post navigation block when all inner blocks are deleted matches the button and columns block:
- The parent is empty in the editor
- The empty parent block is printed on the front.

It would be good to solve the empty tag on the front for all these blocks.

**Comment by carolinan** [comment]
Question, do I need to create a Trac ticket for the changes to the list of registered blocks in lib/blocks.php?
According to the error, I do, but isn't this list automated?

"// This file was autogenerated by tools/release/sync-stable-blocks.js, do not change manually!

**Comment by carolinan** [comment]
And for @beafialho, the reason I pinged you was because I am wondering wether this change offers enough flexibility for designers to position the next and previous post links.

**Comment by beafialho** [comment]
Thank you for the ping @carolinan! Just tried this and it seems like an improvement that makes sense overall.

When I click the "Post Navigation" block, I am only seeing the typography settings in the styles panel. My suggestion is that this block has the same settings that are available for the row block (where we usually add both "Next" and "Previous" links), as this allows for more granular design customization. Here's a screen recording of that I mean:

https://github.com/user-attachments/assets/2ce7f864-01a9-47c2-82b3-2ca245844bf4

I also suggest that we make it possible to add the "Next" and "Previous"links if one desires to, outside of the Post Navigation block. Is this helpful?

cc: for your input as well @richtabor @henriqueiamarino

**Comment by henriqueiamarino** [comment]
I am with @beafialho here. Having the same settings from the row block will certainly enhance customization and add consistency. In the future, this should be extended to all navigation elements and pagination, which is similar. For instance, why not add these options to the Post Navigation?
This is not necessary at the moment, but I firmly believe it's a path to take.

Screenshot 2024-07-12 at 10 39 12

**Comment by carolinan** [comment]
> I am with @beafialho here. Having the same settings from the row block will certainly enhance customization and add consistency. In the future, this should be extended to all navigation elements and pagination, which is similar. For instance, why not add these options to the Post Navigation? This is not necessary at the moment, but I firmly believe it's a path to take.
> 
> Screenshot 2024-07-12 at 10 39 12

The icon option is already on the individual inner blocks.

**Comment by carolinan** [comment]
Yes this feedback is helpful, thank you.

- I have removed the parent limitation from the post navigation link.
- I have added border, padding, top and bottom margin, and block spacing.

 I am unsure about min height and shadow?

It does feel strange that the inner post navigation link blocks do not have padding and margin settings.

**Comment by ntsekouras** [comment]
I'm not really fond of the idea of a new block and maybe the strongest argument would be discoverability of a pattern that would do that. A thing that resonated with me is that is indeed quite similar to Query Pagination, so it could justify the wrapper block(if we eliminate the pattern approach). 

Having said that, if we go with this approach, should we consider moving some controls like the `arrow` on the new block like we do for the Query Pagination, to update both inner blocks together?

**Comment by carolinan** [comment]
I would need some help with how to move the icon options:
- Designers has asked to continue to be able to place the individual next and previous blocks, so does that mean the option would not be moved, but be on both the inner blocks and the parent wrapper? Then it would be inconsistent again.
- What happens / what should happen with existing, already placed blocks that use the option`?

**Comment by ntsekouras** [comment]
>Designers has asked to continue to be able to place the individual next and previous blocks, so does that mean the option would not be moved, but be on both the inner blocks and the parent wrapper? Then it would be inconsistent again.

Yeah, in that case it doesn't make sense to move controls to the parent.

**Comment by carolinan** [comment]
@WordPress/gutenberg-core How can we arrive at a final decision about whether this block should be added or not?
In my opinion the need for the accessibility fix is reason enough, and the improved consistency with other pagination blocks is a bonus.

**Comment by draganescu** [comment]
I think we should not make this block. While it makes sense, after all there is for instance a media+text block which could just as well be a pattern (although its a relic of earlier iteration), it seems the wrong tool for the problem at hand:

> making post navigation using rows and next / prev post blocks cannot be in a nav tag

This shows that we have some limitations in how we express structure semantically. I can even say it could be better to allow nav for group than to add this block just for this reason. Other than this it doesn't add too much, because unlike media+text this is a template block, not used in posts, so the frequency of every having to build row+next+prev is quite low.

**Comment by carolinan** [comment]
I would challenge you to watch a user add these blocks. The accessibility is what is most important for _me_, but users are also struggling with needing to insert two copies and positioning them.

Adding the nav to the group still requires that the user knows it needs to change the elements, and that they need to use more than one block type.

**Comment by carolinan** [comment]
I would also challenge the assumption that users don't add this block:  Are there statistics for this?

**Comment by carolinan** [comment]
I am asking for more valid arguments against than "I don't _want_ another block" "I am not _found of_ adding another block".

**Review by draganescu — COMMENTED** [review]
> I would also challenge the assumption that users don't add this block: Are there statistics for this?

@carolinan I am not saying people don't add it or will not add it. They will definitely use it. What I am saying is that compared to the other block that is just a combo of blocks (media+text) this is not a content block, so it will be less frequently used to warrant the shortcut.

However, my main argument is not against the block: it is to signal that the main benefit of this block is that it solves the lack of semantics in wrapper blocks. And that should not be solved via a new block, but by solving the lack of semantics in wrapper blocks.

> users are also struggling with needing to insert two copies and positioning them.

This too points to a problem that should not be solved the wrong way: why do the users struggle? I think users would struggle because building layout is not the simplest thing. All tools have certain complexity levels where the UI itself can't convey everything. 

> I am asking for more valid arguments against 

For any new block the arguments _for it_ should be compelling not so much against it. To me the best argument **for** this block is that we have plenty of shortcut (macro) blocks:

- gallery, even though we have image and columns and rows
- media text, even thgouh we have columns image and paragraph
- buttons, even though we have row and button
- author name even though we have author which also includes the name
- query pagination

---

Separately, one problem @carolinan is that this block is inherently more restrictive b/c of allowed blocks. The row block allows for separators and decoration between the links.

---

Edit: just for reference there  is a proposal for a dialog block of which I am not convinced either https://github.com/WordPress/gutenberg/issues/61297 - so it's gonna be a perpetual issue. And I don't decide anything :)

**Comment by afercia** [comment]
I will leave the decision on whether to use a new block or provide another mechanism to contributors more familiar than me with this kind of decisions.

I'd be more interested in solving the underlying usability and accessibility issues. Quoting from the original description:

> Make it easier for users to add both the next and the previous posts links together, instead of having to insert two separate blocks and (commonly) wrap them inside a group/row/stack/column to position them.

As a user, why on earth I have to add two separate blocks (Previous and Next) and then wrap them in a parent block? That is an unnecessarily complex, unintuitive, and time-consuming flow. In most of the cases, users would want to just add a previous/next navigation with just one click.
Potentially, in rare cases, specific designs may want to use only the 'next' or only the 'previous' links. As such, in my opinion:

- Users should be able to add a prev/next navigation with just one click.
- As such, there should be a mechanism that adds by default the previous and next links. Maybe also the number links?
- The navigation should be wrapped by default into a group with a `<nav>` element and it should be labelled meaningfully - - The UI should allow users to edit the `<nav>` element label because multiple `<nav>` elements on the same page must be distinguished by the means of labels.
- Users should be able to _remove_ the prev/next/numbers link, if they want to.

**Comment by t-hamano** [comment]
Maybe I'm missing something, but why can't we just add a `nav` element to the HTML options for the Group block?

image

In my opinion, these existing elements are just as important as the `nav` element. It is up to the user to choose these elements, so just like the `nav` element they can be used in the wrong way. But they also have help text to assist with that decision. I don't understand why we can't add a `nav` element here.

**Comment by draganescu** [comment]
@t-hamano 's question is very pertinent

**Comment by carolinan** [comment]
Adding the nav element to the group does not remove the need for this block.

**Comment by afercia** [comment]
> why can't we just add a nav element to the HTML options for the Group block?

That would help but still:
- many users wouldn't have a clue they should use a `<nav>` element
- the UI should provide a way to label the `<nav>` because whe a page has multiple `<nav>` elements, they need to be distinguished by the means of a label. See https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation.html `If a page includes more than one navigation landmark, each should have a unique label.` 

> It is up to the user to choose these elements

I would argue this is not in line with what WordPress always aimed to to. Historically, WordPress always aimed to output valid, semantic, and accessible HTML on the front end. The classic template functions for things like posts navigation etc. take care to output a `<nav>` element. See for example `get_the_posts_navigation`, `get_the_post_navigation`, `get_the_comments_navigation` and similar functions that, under the hood, use `_navigation_markup` to generate the HTML and output a labeled `<nav>` element. There has been previous work to make sure these functions output semantic and accessible navigation. In the same way, the editor should make sure all the navigations rendered on the front end use a labeled `<nav>` element. This is a responsibility that can't be delegated to users.

**Comment by t-hamano** [comment]
Another suggestion is to create variations of the Group block.

<details><summary>Code</summary>

```javascript
wp.blocks.registerBlockVariation( 'core/group', {
	name: 'group-navigation',
	title: 'Post navigation',
	category: 'theme',
	icon: () => {
		return wp.element.createElement(
			wp.primitives.SVG,
			{ xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 24 24' },
			wp.element.createElement( wp.primitives.Path, {
				d: 'M21 17.5L21 6L13 6L13 17.5L21 17.5ZM10 14.5L3 14.5L3 16L10 16L10 14.5ZM3 11L10 11L10 12.5L3 12.5L3 11ZM10 7.5L3 7.5L3 9L10 9L10 7.5Z',
			} )
		);
	},
	attributes: {
		metadata: {
			name: 'Post navigation',
		},
		tagName: 'nav',
		ariaLabel: 'Posts',
		layout: {
			type: 'flex',
			justifyContent: 'space-between',
		},
	},
	allowedBlocks: [ 'core/post-navigation-link' ],
	innerBlocks: [
		[ 'core/post-navigation-link', { type: 'previous' } ],
		[ 'core/post-navigation-link' ],
	],
} );
```

</details> 

image

Additionally, provides a UI for editing the ariaLabel attribute (See [this comment](https://github.com/WordPress/gutenberg/issues/67407#issuecomment-2507433456)).

The reason I'm cautious about adding new blocks is that once a block is shipped into core, we need to continue maintaining it in a backwards-compatible manner for as long as the block is available: we can deprecate it, but we can't remove the code. So I'm wondering if there's a way to solve this without adding a new block.

**Comment by youknowriad** [comment]
@t-hamano Great thinking. I like the variation approach.

The other thing I wanted to mention, is that we can potentially add some smart detection on how people are using the different tag names and if we can detect mis-use show nudges like we do for color contrast.

**Comment by carolinan** [comment]
I am very surprised by the reluctance to solve this the same way the existing paginations have been solved, I am sensing that this has become about the argument rather than the solution and I don't appreciate it.
There has been no reports of there being any issues with these existing combined blocks that would require changes to those, that would mean turning them into something else like a variation.

**Comment by carolinan** [comment]
This block does absolutely not create a larger maintenance burden than any of the other proposed blocks.

**Comment by carolinan** [comment]
And as far as I know, you can not style those kind of variations site wide. Just like you can't style stack and row separately from the group.
Not with global styles (Styles sidebar) nor a JSON file. And this includes the new section styles and variations in theme.json.

**Comment by carolinan** [comment]
Styling block variations would be good to have, [but there is no ETA on resolving it](https://github.com/WordPress/gutenberg/issues/67444): I don't think that solving known accessibility issues should be blocked by possible future changes, unless that future change is on the immediate roadmap and there is progress.

**Comment by carolinan** [comment]
On the other hand, I wish we had planned for having a single pagination block from the beginning, where the query pagination, comment pagination, next/previous could have been variations or where the pagination type would have been detected automatically depending on the context.

**Comment by aaronrobertshaw** [comment]
> I don't think that solving known accessibility issues should be blocked by possible future changes

To play devil's advocate here, is the ability to style the proposed variation via Global Styles a true blocker for that approach?

**Comment by carolinan** [comment]
Yes because it is a subpar experience compared to editing and styling the other pagination blocks, and creates another inconsistency between them.

**Comment by carolinan** [comment]
There was a comment that this block is only used in templates. Without statistics, we can't know if that is accurate, in the support requests I have received, the user have tried to add it to the post content in the block editor when using Twenty Twenty-Three because that theme does not include this navigation by default.

**Comment by carolinan** [comment]
@WordPress/gutenberg-core How can we move this forward? I see other new blocks getting merged after two weeks without discussion, I still don't think that the arguments against this block are valid.

**Comment by jameskoster** [comment]
There is a lot of drift in terms of container block style support. For example I think it’s super weird that you can set background images on some, but not others (like the Pagination block, incidentally). This forces theme devs to utilise inefficient workarounds such as wrapping blocks like Pagination in a Group just to get access to certain style options. The knock-on effect is a more convoluted block tree that is harder for end users to navigate.

The more 'containers' are added, the worse these inconsistencies seem to get.

For that reason I prefer the variation suggestion. It ensures this ‘block’ always matches the Group block in terms of style options, and as already mentioned; reduces the maintenance burden.

I should say that this is all assuming there aren't any styling options that this block needs that are not already present on Group.

**Comment by carolinan** [comment]
The problem is still that 
- Using a variation creates yet another inconsistency with the existing pagination blocks.
- Users/developers/designers will not be able to style the pagination separately from group blocks, such as setting a default alignment and spacing around or between the next and previous links, nor style variations of it.
- Having a variation of a group block that is not a container **but for a single purpose**, this is different from the current group block variations stack, row and grid. This does not make the next and previous navigation easier to use, it makes it more difficult for user to know _which group to use when and for what._

**Comment by carolinan** [comment]
I understand that the background image was a single example, but I still feel strongly that not having a background image option is preferable over not being able to add default styles at all.

**Comment by jameskoster** [comment]
If you wanted to make a particular style/layout reusable would it not be more appropriate in this case to create a template part or synced pattern? It doesn't seem like a block that will be used very often outside of specific templates?

**Comment by carolinan** [comment]
I have already responded to that multiple times in this discussion, but to add to that:

1) That assumes the user has the knowledge to do that. 
2) Synced patterns can not be added by themes and template parts can't be used in the post content/block editor.
3) As you know styles are more portable and flexible when added in theme.json rather than hardcoded as part of the HTML markup. The second also prevents use of style variations since the variations cant override this markup.
4) There are no stats that show how these blocks are used or that it would not be used more if it was easier to add.

**Comment by jameskoster** [comment]
> That assumes the user has the knowledge to do that.

Since this is a block targeted more towards theme devs that seems like a reasonable assumption?

> template parts can't be used in the post content/block editor

Is this a block we expect people to use inside the Content block? It feels more like a template block to me.

These are just my opinions. I don't want to block the effort, but there doesn't seem to be clear consensus either way on this one.

**Comment by afercia** [comment]
I do understand all the different reasoning on this issue but, to me, the most important point is addressing the underlying usability issue. As mentioned [in my previous comment](https://github.com/WordPress/gutenberg/pull/57664#issuecomment-2505681012), the current flow to add a fully working post navigation is unnecessarily complex, time consuming, and unintuitive.

I would argue that what users need in most of the cases, whether they are theme authors, devs, or content authors, is to be able to just add a fully working Post navigation with just one click. The block should allow to _remove_ nested blocks if users want to, for example, remove the previous link. Not the other way around.

**Comment by carolinan** [comment]
I disagree with the notion and  practice that if a block is used in the Site Editor it is acceptable for that block to be more difficult to use and for it to not be accessible.

That is not how you empower people to create better websites. That is not how you help users learn.
That is how you make people feel like they are not smart enough to do it, it is how you alienate users and push them away.

**Comment by talldan** [comment]
> I would argue that what users need in ost of the cases, whether they are theme authors, devs, or content authors, is to be able to just add a fully working Post navigation with just one click. The block should allow to remove nested blocks if users want to, for example, remove the previous link. Not the other way around.

It looks like @t-hamano's example block variation does that.

**Comment by carolinan** [comment]
I am not going to spend more time on this.

**I am expecting to see the following merged:**
- A fully accessible next and previous post navigation.
- That does not require multiple steps to set up.
- That can be styled site wide by all: designers, developers, users.
- That can be inserted even if the core block patterns are disabled.

**Comment by t-hamano** [comment]
I think the fact that the only way to fully solve accessibility issues is to add a new block means that the editor itself may lack a UI to assist users in creating fully accessible pages.

The Post Navigation Link block isn't the only thing that is expected to be wrapped in a nav element -- for example, a user may insert link buttons or link lists that have navigational implications.

With that in mind, I think the following approach might be effective in the long term:

- Implement an accessibility check button in the editor. When pressed, the entire content or template is parsed, and users are warned about markup or blocks that may not be accessible.
- Show some kind of warning in the block sidebar when the Post Navigation Link block is used alone. For example, "It is recommended that this block be wrapped in a Group block as a nav element."

Either way, I'd love to hear from anyone who has other ideas or approaches to finding the ideal solution.

**Comment by carolinan** [comment]
Adding the nav element to more blocks is already discussed in a separate issue and PR: 
https://github.com/WordPress/gutenberg/issues/64051
https://github.com/WordPress/gutenberg/pull/66866

**Comment by carolinan** [comment]
The nav element is not the only issue that needs to be solved.
The inconsistencies with the other blocks and lack of styling option is not solved by an improved accessibility checker, and everyone so far is dismissing this feedback and the reply to the question that was asked "is the lack of styling really a problem?".

Again, if a theme developer wants to style the query pagination and the next and previous post links the same way, **and then design it differently in a style variation**, they can't do that.
For example TT5 has a border above the next and previous links that can't be added in any way but using the HTML markup, which again, can't be overridden by a JSON style variation.

**Pull request closed without merging**
