### PR TITLE
Update block inserter and library terminology and labels

### LINKED ISSUE #61483: Improve the block inserter labeling
### Description

Noticed after some recent changes to the block inserter in https://github.com/WordPress/gutenberg/pull/61004 and https://github.com/WordPress/gutenberg/pull/61421. Hat tip to @carolinan for pointing me at this.

## Title case capitalization
Traditionally, all WordPress features are title case. The term 'block inserter' feels a little too technical to me and I'd personally prefer a more intuitive, simpler name. Regardless, whatever this feature name is, it should be always title case: Block Inserter. This is no different for other features e.g. List View, Document Overview, and many other ones.
Title case should be used everywhere the 'Block Inspector' terminology is used, for example also in the commands palette.

## The verb 'toggle'
See https://github.com/WordPress/gutenberg/discussions/42492 and similar trac ticket for Core. The verb 'toggle' should be avoided. The button that opens the Inserter is labeled `aria-label="Toggle block inserter"`. Also, for consistency, Document Overview, List View, Settings panel don't use the verb 'toggle'. It is used in the command palette and it should be removed from there as well.

## The name 'Block Library' is obsolete
The navigable region where the block inserter renders within is still labeled 'Block Library'. This should be updatred to 'Block Inerter' as it's confusing for screen reader users. They will activate a button labeled 'Block inserter' to get a UI that is labeled 'Block Lirary'. Screenshot with VoiceOver running:

Screenshot 2024-05-08 at 12 20 29

## The new Close button label should be simplified
In https://github.com/WordPress/gutenberg/pull/49614 some labels for some Close buttons were simplified based on the following criteria:
- When the Close button is contained within a labelled UI that provides enough context, shorten the button label to just 'Close'.
- Otherwise, keep some contextual information in the button label.

In the same way, as this UI is already labeled, the Close button label should be simplified.

### Step-by-step reproduction instructions

Observe the labels used in the UI in the places described above.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/61483

## What?

The term 'block inserter' is used inconsistently in user-facing strings. All text and label referencing it can be improved.

## Why?

- WordPress features should always use title case capitalization.
- The verb 'Toggle' should be avoided.
- The term 'Block Library' is used as synonym of 'Block Inserter' but that's less than ideal in the UI when controls refer to the same feature but use different terminology.
- All X 'Close' icon button can be labeled just 'Close' when the context already provides the 'what' is going to be closed.

## How?

- Makes the term 'Block Inserter' always use title case capitalization.
- Removes the verb 'Toggle' from the Block Inserter toggle button.
- Replaces the term 'Block Library' with 'Block Inserter' everywhere it makes sense.
- Simplifies the label of the Block Inserter X close button from 'Close block inserter' to 'Close'.
- Adjusts tests accordingly.

## Testing Instructions

- Go to the Post editor.
- Hover of focus the button that opens the Block Inserter.
- Observe the button tooltip text is 'Block Inserter' title cased and the verb 'Toggle' has been removed.
- Open the Block Inserter.
- Inspect the source in your browser dev tools and observe the element with CSS class `interface-navigable-region interface-interface-skeleton__secondary-sidebar` which is the ARIA landmark with role=region is now labeled `Block Inserter` instead of `Block Library`.
- Hover or focus the X close button at the top right of the Block Inserter and observe the tooltip text is now 'Close'.
- Search through the entire codebase and observe all the occurrences of 'Block Inserter' are now title case, except in the changelog files.

### CODE REVIEW

**Comment by afercia** [comment]
I have no idea why that e2e test keeps failing with error message `Error: A snapshot doesn't exist at ...`.
The test passes locally. Using the flag to regenerate snapshots doesn't update any snapshot:
`npm run test:e2e -- --update-snapshots editor/blocks/group.spec.js`

Any help would be appreciated, thanks @WordPress/gutenberg-core

**Comment by t-hamano** [comment]
The snapshot title is automatically generated from the test title. [The test title has changed](https://github.com/WordPress/gutenberg/pull/61493/files#diff-e4d70190be6440c6c46af1ae9dd394ad8bbe62fbe2dda9a56c14eac6ff893075L19-R19) in this PR, so the snapshot file name must also be updated.

I pushed the fix, so this should pass.

**Comment by youknowriad** [comment]
I have some reservation about this new terminology, but I'll share on the issue for now.

**Comment by afercia** [comment]
> I have some reservation about this new terminology, but I'll share on the issue for now.

Yeah I have reservations as well. This PR is an attempt to standardize on the terminology 'block inserter' for now but, as the discussion on the issue evolves, it appears 'block inserter' is not an appropriate naming any longer.

**Comment by afercia** [comment]
> The snapshot title is automatically generated from the test title. [The test title has changed](https://github.com/WordPress/gutenberg/pull/61493/files#diff-e4d70190be6440c6c46af1ae9dd394ad8bbe62fbe2dda9a56c14eac6ff893075L19-R19) in this PR, so the snapshot file name must also be updated.

🤦🏽‍♂️ thanks @t-hamano, I learned a new thing.

**Comment by afercia** [comment]
There's some agreenent the terminology  'Block Inserter' isn't appropriate any longer so I'm going to close this PR.
There's steel the need to find a new terminology to be used consistently in the editor. Discussion can continue on the associated issue https://github.com/WordPress/gutenberg/issues/61483

**Pull request closed without merging**
