### PR TITLE
RichText: List: Fix outdent with children

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

After #12667, outdenting list items with children became broken. The children should also be indented.

## How has this been tested?

Start with the following content:

```html
<!-- wp:list -->
<ul><li>A<ul><li>B<ul><li>C</li><li>D</li></ul></li></ul></li></ul>
<!-- /wp:list -->
```

Set the caret at "B", then press the outdent button. "C" and "D" should also be one level outdented.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Works well in my testing.

**Comment by iseulde** [comment]
Thanks!

**Comment by mcsf** [comment]
Starting with the following list:

```
<!-- wp:list -->
<ul><li>A<ul><li>B<ul><li>C</li></ul></li><li>D</li></ul></li></ul>
<!-- /wp:list -->
```

Place the caret on **D**, then decrease indentation.
Observed: nothing changes.
Expected: for **D** to return to level 0, like so:

```
<!-- wp:list -->
<ul><li>A<ul><li>B<ul><li>C</li></ul></li></ul></li><li>D</li></ul>
<!-- /wp:list -->
```

**Comment by iseulde** [comment]
Thanks @mcsf! I'll follow up with a PR.

**Comment by mcsf** [comment]
Conversely, starting at:

```
<!-- wp:list -->
<ul><li>A<ul><li>B<ul><li>C</li></ul></li></ul></li><li>D</li></ul>
<!-- /wp:list -->
```

Place the caret at **D**, then increase indentation.
Observed: **D** jumps from level 0 to 2.
Expected: **D** jumps to level 1.

**Comment by iseulde** [comment]
The first one is fixed by #13562. Looking into the other one now.

**Pull request merged**
