### PR TITLE
FontSizeControl (Next): Fix SelectDropdown voiceover focus issues

### LINKED ISSUE #28411: FontSizePicker accessibility issues
## Description
https://github.com/WordPress/gutenberg/pull/27594 was recently merged. The new components are behind a flag and won't ship to core, but I noticed a few accessibility issues that will need to be resolved.

- The font size select doesn’t announce whether it’s collapsed or not when focused
- When opened, the font size picker relays the incorrect amount of items
- The reset button is skipped in tab order when typing in a custom font size for the first time, as it only becomes enabled when focus leaves the input

I haven't tested using NVDA, would be good to get someone with good experience of accessibility testing to do a more thorough test.

## Step-by-step reproduction instructions
With Voiceover active
1. Add a paragraph block
2. Navigate to the Block Inspector
3. Tab to the Font Size Picker dropdown
4. Note that the collapsed/expanded state wasn't read by VO
5. Open the Font Size Picker dropdown
6. Note that the number of items read by VO is incorrect, and the first focused item seems to have an index of 2
7. Press escape to dismiss the dropdown and tab to the Custom Font Size input
8. Enter a value, tab to the reset button
9. Note that the reset button was bypassed in the tab order.

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8
- Are all plugins except Gutenberg deactivated? Y
- Are you using a default theme (e.g. Twenty Twenty-One)? Y (2021)

## Device information
- Device: Desktop
- Operating system: Mac OS
- Browser: Safari with Voiceover

### PR DESCRIPTION
**Pull request by ItsJonQ**
This update fixes the voiceover focus interactions for the  (next) `FontSizeControl` component (recently merged https://github.com/WordPress/gutenberg/pull/27594)

The solution was to update to the latest `@wp-g2` version (v0.0.143):
https://github.com/ItsJonQ/g2/releases

These changes include updates to `z-index` and interaction fixes to the underlying `SelectDropdown` component (https://github.com/ItsJonQ/g2/pull/239).

Potentially resolves https://github.com/WordPress/gutenberg/issues/28411

## How has this been tested?

Tested locally on Gutenberg with Chrome + Firefox + Voiceover (Mac OS)
Also tested in the `@wp-g2` [pull request](https://github.com/ItsJonQ/g2/pull/239) in a similar manner.

To test:

* run `npm run dev`
* Click on a text-based block (e.g. Paragraph)
* Ensure the font size picker interactions are working as intended

## Checklist:
- [x] My code is tested.
- [n/a] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
@ItsJonQ Looking good. Only one of the items I mentioned still seems to be an issue. When the Font Size dropdown (button element) initially receives focus it doesn't seem to have the `aria-expanded` attribute. That's only added after opening it for the first time. Here's what Voiceover reads when it's focused for the first time:
Screenshot 2021-01-22 at 12 41 43 pm

Compared to when the dropdown has been toggled open and closed at least once:
Screenshot 2021-01-22 at 12 40 28 pm

**Comment by ItsJonQ** [comment]
@talldan Wonderful!! Thank you for that feedback 🙏

**Comment by gziolo** [comment]
Reakit is deduplicated now 🎉 
Screen Shot 2021-01-22 at 16 22 07

**Review by diegohaz — COMMENTED** [review]
Nice! Tested with NVDA and JAWS on Firefox and the reset button focus has been fixed. The only remaining issue from @talldan's list is the lack of `aria-expanded` in the first render.

**Comment by ItsJonQ** [comment]
@talldan + @diegohaz Fixing it here:
https://github.com/ItsJonQ/g2/pull/244

Will create a release and make an update in this PR as soon as I can 🙏

**Comment by ItsJonQ** [comment]
@gziolo Hmm! It looks like there's something in the latest [rtlcss V3.0.0](https://github.com/MohammadYounes/rtlcss/releases/tag/3.0.0) that's causing issues with babel (specifically with `let`)

https://github.com/WordPress/gutenberg/runs/1750693127?check_suite_focus=true

**Comment by gziolo** [comment]
> @gziolo Hmm! It looks like there's something in the latest [rtlcss V3.0.0](https://github.com/MohammadYounes/rtlcss/releases/tag/3.0.0) that's causing issues with babel (specifically with `let`)
> 
> https://github.com/WordPress/gutenberg/runs/1750693127?check_suite_focus=true

I can see it in the source of the package. It looks like they write code to target code in Node.js mostly. It looks like @jsnajdr was right that it's inevitable that we will have to start transpiling some of the packages in `node_modules` :(

**Comment by ItsJonQ** [comment]
Not sure what to do with the failing E2E test :(.

I think there's something to it, but I'm not sure what.

```
● Font Size Picker › should reset a named font size using the reset button

    expect(received).toMatchSnapshot()

    Snapshot name: `Font Size Picker should reset a named font size using the reset button 1`

    - Snapshot  - 2
    + Received  + 2

    - <!-- wp:paragraph -->
    - <p>Paragraph with font size reset using button</p>
    + <!-- wp:paragraph {"fontSize":"normal"} -->
    + <p class="has-normal-font-size">Paragraph with font size reset using button</p>
      <!-- /wp:paragraph -->

       96 | 		// Ensure content matches snapshot.
       97 | 		const content = await getEditedPostContent();
    >  98 | 		expect( content ).toMatchSnapshot();
          | 		                  ^
       99 | 	} );
      100 | 
      101 | 	it( 'should reset a named font size using input field', async () => {
```

Replicating the actions locally, it works as expected.

Running it locally, the "reset" related ones pass for me.

There's another failure, but that's related to the theme's font setting for what a "small" size (test is looking for `13`, but the theme uses `19` for `small`).

Screen Shot 2021-01-26 at 10 34 51 AM

**Comment by ItsJonQ** [comment]
cc'ing @gziolo. Would you know what we can do for the E2E failure? The hardest thing is that it's inconsistent between my local machine and what's on Github actions

**Comment by gziolo** [comment]
I rebased this branch. It fails for me locally in a different test:

> should reset a named font size using the reset button

The one you highlighted passes 🤷🏻

**Comment by ItsJonQ** [comment]
Resolve in https://github.com/WordPress/gutenberg/pull/28707

**Comment by ItsJonQ** [comment]
Resolved in https://github.com/WordPress/gutenberg/pull/28707

**Pull request closed without merging**
