### PR TITLE
Perf: Try out post editor perf tests with tinymce disabled

### PR DESCRIPTION
**Pull request by tyxla**
## What?

This PR explores running the post editor performance tests with TinyMCE disabled.

This PR is a continuation of #50387. 

DO NOT MERGE.

## Why?
To assess the performance impact through the performance tests.

## How?
We're duplicating the post editor perf tests to try it out.

## Testing Instructions
Observe the performance test results.

### Testing Instructions for Keyboard
None

## Screenshots or screencast 
None

### CODE REVIEW

**Comment by c4rl0sbr4v0** [comment]
We already have this warning on console. Is due to disabling tinymce?

Screenshot 2023-07-03 at 15 06 07

**Comment by tyxla** [comment]
First results are as follows:

```
| Metric               | Original | TinyMCE disabled | Impact       |
|----------------------|----------|------------------|--------------|
| serverResponse       | 211.18   | 266.22           | -26.06307415 |
| firstPaint           | 257.38   | 255.34           | 0.7926023778 |
| domContentLoaded     | 682.94   | 524.12           | 23.25533722  |
| loaded               | 683.78   | 524.82           | 23.24724327  |
| firstContentfulPaint | 1263.36  | 1098.7           | 13.03349797  |
| firstBlock           | 11783.38 | 11537.76         | 2.084461335  |
```

My initial interpretation: even though the `serverResponse` was 25% slower (IIUC there isn't anything particular from the experiment that should slow it down), the `domContentLoaded` and `loaded` were 23% faster, and `firstPaint` was relatively 27% faster considering the slower `serverResponse`. I expect that if `serverResponse` end up equal, we'll have even more impressive results.

I'd have to run some more tests on it to get a better understanding.

**Comment by tyxla** [comment]
Doing some more runs after talking to @WunderBart with the following setup:

- A: branch to disable other tests: https://github.com/WordPress/gutenberg/compare/try/perf-tests-only-post-editor?expand=1
- B: branch to force-enable the experiment: https://github.com/WordPress/gutenberg/compare/try/always-enable-no-tinymce?expand=1
- manually triggered workflow: https://github.com/WordPress/gutenberg/actions/runs/5446319457
- ran workflow with the first branch (A), comparing between `trunk` and the second branch (B).

Results so far appear to demonstrate 10% faster post editor loading metrics!

**Comment by tyxla** [comment]
It's a bummer that perf tests have a bunch of noise, though. Some runs will show a ~20% improvements, others 10%.... I'd regrettably say this is not a very reliable way to assess performance improvements.

**Comment by tyxla** [comment]
Now that we have a raw idea of the perf improvements, I'm going to be running some manual tests and some debugging to try to repro warnings reported in https://github.com/WordPress/gutenberg/pull/50387#issuecomment-1619940612. 

Closing this one and deleting the aforementioned branches for the time being.

**Pull request closed without merging**
