### PR TITLE
Block categories: Clean these up by moving several blocks from Design to Theme

### PR DESCRIPTION
**Pull request by kellychoffman**
Cleaning up the block categories within the Block Inserter. This PR moves the following blocks from the Design category to the Theme category, based on the intended usage of the blocks. 

- Navigation (vertical)
- Navigation (horizontal)
- Login/out
- Query
- Post Title
- Post Content
- Post Date
- Post Excerpt
- Post Featured Image
- Post Author
- Post Comment
- Post Comments
- Post Comments Count
- Post Comments Form
- Post Comments Link
- Term Description
- Next post
- Previous post

### CODE REVIEW

**Comment by shaunandrews** [comment]
I wonder if "Theme" could be confused as meaning "provided by your theme."

**Comment by priethor** [comment]
> I wonder if "Theme" could be confused as meaning "provided by your theme."

My first thought was similar back when the category was created in #30016, but categories should not address a block's origin but their content; similarly, we don't have a "plugins" category.

**Review by priethor — COMMENTED** [review]
Looks good to me. In #30016 it was suggested to leave widget-like blocks (Site Logo, Title, etc) in the widgets section, so waiting for @mtias to confirm.

As a side note, if we do move these blocks to "Themes" we will have:
- Posts List block under "Themes"
- Latest Posts and Page List blocks under "Widgets".

Having these similarly named blocks in different categories can be confusing for users, but I don't think this should be a blocker as these widget blocks might be replaced in the future by more Query block variations (#32332).

**Review by priethor — APPROVED** [review]

**Comment by jasmussen** [comment]
Got the tests passing on this one! Feel free to press the green button 👌

**Pull request merged**
