### PR TITLE
Load `word-count` and do not allow our `wp-utils` script to clobber it

### LINKED ISSUE #1569: Webpack build process is overridding wp.utils
I was working on #1557 and noticed that even though `word-count.js` was added as a dependency, it was not available at `window.wp.utils`. The entire object is being overridden by the following portion of `webpack.config.js`

```
const entryPointNames = [
	'element',
	'i18n',
	'components',
	'utils',
	'blocks',
	'date',
	'editor',
]


entryPointNames.forEach( entryPointName => {
	externals[ entryPointName ] = {
		'this': [ 'wp', entryPointName ],
	};
} );
````
Essentially, any items in entryPointNames will be added to the`wp` object and override anything already exisiting with the same name.

Can we namespace this to `wp-gb` or something similar?

### PR DESCRIPTION
**Pull request by ryanwelcher**
Renaming the `utils` to `utils-gb` to avoid overidding the `wp.utils' object. Fixes #1569

### CODE REVIEW

**Comment by nylen** [comment]
There is a cleaner way to fix this, especially given that these two things will probably eventually be merged into `wp.utils` together (see ongoing conversation about JS modules in core).  We just need to require that the webpack version of `wp.utils` is loaded first.  From previous discussion around https://github.com/WordPress/gutenberg/pull/940#issuecomment-305004654:

> `word-count.js` [doesn't clobber `window.wp.utils`](https://github.com/WordPress/wordpress-develop/blob/4.7.5/src/wp-admin/js/word-count.js#L216-L219)

> So this means that the webpack version needs to be loaded first. We can accomplish this by adding `wp-utils` as a dependency of `word-count`.

Also I think it's a bit weird that as a result of this PR, our utilities would be accessed via `window.wp['utils-gb']` in externall code.

**Comment by ryanwelcher** [comment]
Until everything that lives in `wp.utils` is merged into the GB version, any item that lives in that object will not be available when Gutenberg is loaded. That will mean that `wp-utils` will have to be a dependency for anything that core adds to the `wp.utils` object and then only in the context of Gutenberg so the script will load.

**Comment by adamsilverstein** [comment]
@nylen any suggestions for how we "add wp-utils as a dependency of word-count."? Do you mean in the webpack config?

**Comment by nylen** [comment]
> any suggestions for how we "add wp-utils as a dependency of word-count."?

As done in f43c8e9.  To test, load the plugin and verify that `wp.utils.WordCounter` (from core) and `wp.utils.keycodes` (from `wp-utils`) are both available.

> That will mean that `wp-utils` will have to be a dependency for anything that core adds to the `wp.utils` object and then only in the context of Gutenberg so the script will load.

It doesn't quite mean that, because we will only add the `word-count -> wp-utils` dependency when we are actually loading `wp-utils` in Gutenberg context.

As [discussed in Slack](https://wordpress.slack.com/archives/C02RQBWTW/p1498684978387938), I expect the longer-term way to resolve this will be to make `wp.utils` the first module that Webpack builds for us in WP core.  It's a great candidate since the core version only contains this one thing.

**Comment by nylen** [comment]
This was not in the right place the first time around.  Amended in b41ff21.

**Comment by ryanwelcher** [comment]
I've reverted the changes to the folder names. Thanks for your insight and help on this @nylen !

**Pull request merged**
