### PR TITLE
Added WhatsApp icon to the Social Icon Block

### PR DESCRIPTION
**Pull request by paulopmt1**
## What?

I have added the Whatsapp icon to the Social Icons Block, as my first Gutenberg contribuition.

## Why?
WhatsApp is really famous in Brazil, it's used for everything here, so I wanted my first Gutenberg contribution to impact these users.

This is related to: https://github.com/WordPress/gutenberg/issues/30378
 

## Testing Instructions

1. Open a Post or Page
2. Add a Social Block
3. Add the WhatsApp Icon
4. Add content to it, normally https://wa.me/your-phone-number
5. Save and make sure it appears as expected in the editor as well as the preview

## Screenshots or screencast 

In the editor:

image

Result in the preview:

image

### CODE REVIEW

**Comment by paaljoachim** [comment]
Hi Paulo Marcos.

Thank you for your very first contribution to Gutenberg! It is much appreciated!

I tested the PR using the Gutenberg PR build. Using this method: https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/
Adding the WhatsApp icon looks identical to adding other social media icons.

Backend:
Screenshot 2022-07-14 at 13 36 02



Testing the Frontend with Twenty Twenty Two showed some weirdness which has I believe nothing to do with this PR, so feel free to skip this part.
Screenshot 2022-07-14 at 13 37 52

Testing the Frontend with Twenty Twenty One showed this:
Screenshot 2022-07-14 at 13 41 18

From what I see this PR in relation to design and functionality works as it should.
Both of the above screenshots shows what it would look like when hovering the cursor over the Whatsapp icon. Showing the status area of the browser with the link.

**Comment by ndiego** [comment]
@paulopmt1 this looks great! The PR is testing well and I see no issues. Can you try and rebase the PR, that hopefully will fix the failing check. I am also going to have someone check the svg. Looks good to me, but not my area of expertise. Once the failing checks are cleared and we have confirmation on the svg, I'll approve and we can get this merged!

**Comment by ndiego** [comment]
@critterverse, @jameskoster or @javierarce would anyone be able to do a quick review of the new WhatsApp `svg` in this PR. Otherwise, the PR looks good to go once the failing check is corrected. Thanks for your help 🙏

**Comment by critterverse** [comment]
Nice, agree that this is a great addition to the social icons. I redrew this to match the lineweight used in our other icons before realizing that we don't customize social icons to match our library and generally use the logo as is. So this LGTM!

**Review by ndiego — APPROVED** [review]
This all looks good, lets 🚢!

**Comment by paulopmt1** [comment]
Thanks, @paaljoachim, @ndiego, and @critterverse for reviewing my first Gutenberg PR! I'm really happy to have my own code in Gutenberg, and will start a new task now!

**Comment by fluiddot** [comment]
👋 I checked this change in the native version of the editor and worked fine 🎊 .

**Comment by Hativ** [comment]
If I change the icon color (with the setting of the block), the WhatsApp icon doesn't look good anymore and doesn't match the others:

image

**Comment by paaljoachim** [comment]
Hi Hativ. @Hativ 
Can you create a new github issue and link to this merged PR? It would make it easier for someone to tackle it.

**Comment by ndiego** [comment]
@Hativ @paaljoachim I see what the issue is. I will create an issue and the corresponding PR to get this fixed.

**Pull request merged**
