### PR TITLE
[RNMobile][Monorepo] Update from master and fix web e2e tests

### PR DESCRIPTION
**Pull request by cameronvoell**
Part of the [Monorepo effort](https://github.com/WordPress/gutenberg/pull/18508)

## Description
This PR aims to get web e2e tests working on the monore repo feature branch ([feat/import-gutenberg-mobile-no-squash](https://github.com/WordPress/gutenberg/tree/feat/import-gutenberg-mobile-no-squash)). It does so by updating from gutenberg `master` and gutenberg-mobile `develop`.

## How has this been tested?
This enables back travis CI on the `feat/import-gutenberg-mobile-no-squash` branch.
- Check that all tests are passing in this PR
- Check that the gutenberg demo is running fine locally and that there is no regression: `npm run native ios/android` and `npm run native start`

## Types of changes
- Update from master

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Tug** [comment]
Works great locally!

I think it would be good to integrate them with Gutenberg CI tests and make sure they run correctly on saucelabs now

**Comment by mkevins** [comment]
Hi @Tug :wave: :smiley:  Just a heads up, since I noticed a few commits that change the screen coordinates for the Android emulator: the copy-paste UI tests currently rely on tapping a screen offset from the carret position since the UI to copy and paste is part of the OS and not the app, and thus cannot be clicked via the usual XPath mechanism. In case you see failures for these E2E tests, it may be possible that these offsets need to be tweaked for different screen sizes, or a change in the API level. If these tests are not failing (or are failing for other reasons), no need to alter anything, I just wanted to point out there is the potential for fragility there.

**Comment by Tug** [comment]
Hi @mkevins! Indeed I tried to reproduce the saucelab env by tweaking the sceen size but I was careful not to chang the coordinates offsets dw there ;)
It seems it's not enough though, some tests that are succeededing locally are failing in travis. In the end I don't think this testing env is super stable and we might go with github actions as we already have them green in [this PR](https://github.com/WordPress/gutenberg/pull/22189) by @ceyhun :)

**Review by Tug — COMMENTED** [review]
This is in a good state now, @ceyhun could you have a look at it?

**Review by ceyhun — APPROVED** [review]
Ran native apps locally and both iOS and Android work great 👍

**Comment by hypest** [comment]
Will merge this now with "Merge commit" GitHub option turned on, to preserve the commit history. Will remove the option right afterwards.

**Pull request merged**
