### PR TITLE
Remove ifBlockEditSelected internal higher-order component

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to remove the `ifBlockEditSelected` internal helper of the `@wordpress/block-editor` package. The motivation here is (a) to flatten the common block React element hierarchy and (b) to favor hooks-based implementations over higher-order components. `ifBlockEditSelected` was a useful and expressive helper at the time it was originally implemented, due to the cumbersome nature of using React Context `<Consumer>` elements. With `useContext`, it's much simpler now to get direct access to the context object properties relevant for this behavior. For some affected components, it's arguably still more verbose than the previous implementation, but it seems like a reasonable compromise. A flattened element hierarchy _may_ bring some improved performance and debugging benefit.

**Testing Instructions:**

Verify no regressions in the behavior of affected components. For example, block toolbar and inspector controls should only appear for the selected block.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Makes sense, good memories from old times when HOCs were cool :)

**Comment by aduth** [comment]
The end-to-end tests illustrate a legitimate issue, which is that the previous implementation would pass along `props`. In this case, it's `props.children` which is important. It's a fairly straight-forward fix, but there are a couple ways of going about it:

- Provide all props?
   - `return isSelected ? <Fill { ...props } /> : null;`
- Provide children?
   - `return isSelected ? <Fill>{ children }</Fill> : null;`
- Always render fill and pass children only if selected?
   - `return <Fill>{ isSelected ? children : null }</Fill>;`

It could depend on a few things:

- Is `Fill` expecting to receive any other props?
- Would consistently rendering `Fill` help or hurt performance in any way?

**Comment by ellatrix** [comment]
I think we should just pass `children`?

**Comment by aduth** [comment]
Updated in e6e03c9 to pass only `children` to the fill (second option from https://github.com/WordPress/gutenberg/pull/22905#issuecomment-639029005). I also confirmed that the [implementation of `Fill`](https://github.com/WordPress/gutenberg/blob/1d0eecb53fc3b91b1ad7bd51a368e088243fa8eb/packages/components/src/slot-fill/fill.js#L18) should only require `children` to be passed. Passing all props could be more thorough, but I think it's best to be explicit about what's expected. This introduces a bit of inconsistency with existing code, which could perhaps be updated separately ([this line](https://github.com/WordPress/gutenberg/blob/e6e03c9556f281452e7caf9d48bd8881d4a64a68/packages/block-editor/src/components/inspector-controls/index.native.js#L26) passing all `props`).

**Comment by gziolo** [comment]
The only place where props are passed to `InsepectorControls`:

https://github.com/WordPress/gutenberg/blob/ecbcae6a4578346b63d7b7985b493c7c1ca6d50a/packages/block-editor/src/components/spacing-panel-control/index.js#L27

It doesn't look like there is anything passed down really. It looks not needed.

**Pull request merged**
