### PR TITLE
Add a welcome guide to the template editor.

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
See #29031.

WIP PR for the Welcome Guide for Site/Template editor. It should be visible by default when the post editor is in "template mode."

To toggle the feature use following code snippett in console or use "Options" menu:
```js
wp.data.dispatch('core/edit-post').toggleFeature('welcomeGuideTemplate');
```

## Screenshots 

https://user-images.githubusercontent.com/240569/116553056-c3856b00-a90a-11eb-986f-18a2d21a942a.mp4

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
For 5.8 it's important to have that (or an alternative version of it) in the "template mode" of the post editor. The site editor is not being shipped in 5.8, so it's a bit less important.

**Comment by Mamaduka** [comment]
@youknowriad so conditionally render different "Welcome Guide" when post type is `wp_template` or `wp_template_parts`. Is this logic correct?

**Comment by youknowriad** [comment]
no, more something like this:

 - create  a  page
 - click the "new" link under "template" in the sidebar
 - you'll enter "template mode" there, I think  we should show a guide for that mode (which is very close to the site editor) when you first enter it.

**Comment by Mamaduka** [comment]
Thank you for the clarification; it makes sense.

I will update the code and logic.

**Comment by Mamaduka** [comment]
Updated logic to conditionally render Welcome Guide and removed old one from `edit-site` package.

**Comment by jameskoster** [comment]
Nice 🚀  

I think we'll definitely need to update the copy for 5.8 though. The third slide can be removed altogether for now, since global styles wont be present. The first two can perhaps be combined?

> Welcome to the template editor
> Templates express the layout of the site. Customize all aspects of your posts and pages using the tools of blocks and patterns.

**Comment by Mamaduka** [comment]
> I think we'll definitely need to update the copy for 5.8 though. The third slide can be removed altogether for now, since global styles wont be present. The first two can perhaps be combined?

Sounds good. Do you want me to push this update, or should we wait for design feedback from others?

**Comment by jameskoster** [comment]
Probably ok to push now and refine while we work on the graphics.

**Comment by youknowriad** [comment]
How is this looking?

Should we remove the snackbar with this addition ? cc @mtias 

Also, I think this welcome guide is an opportunity to expand on this mode more, this one is different than the site editor, I think it should say things like:

 - You're now editing a block template assigned to the current page. 
 - Different pages can share the same template, and in this case, changes to the template impact.

WDYT? cc @jameskoster

**Comment by jameskoster** [comment]
The copy has been updated to remove the Site Editor parts:

Screenshot 2021-05-04 at 15 47 00

> You're now editing a block template assigned to the current page.

I think this is inherently implied by the flow: Edit page -> Edit template.

> Different pages can share the same template, and in this case, changes to the template impact.

A slide to cover this makes sense, but we need to strike the right balance between informing and intimidating. Maybe something like:

> **With great power comes great responsibility**
> A single template will often be responsible for the display of many posts or pages. So remember that your changes can affect documents other than the one you're editing.

**Comment by paaljoachim** [comment]
This looks like it heading in a nice direction!
Thanks for working on this George!

**Comment by cgaits** [comment]
As a full time WP dev, I would like to see a way of turning it off as it gets annoying after seeing over 100 times.

**Comment by jameskoster** [comment]
@cgaits you should only see it once 👍

**Comment by cgaits** [comment]
> @cgaits you should only see it once 👍

It was not a clear comment, I apologize. As a dev, I build multiple pages and websites in a workweek; I see it pop up many times. My comment should have been is there a way to turn it on or off in the settings, and is it worth to add other such features in settings, for example what type of the widget screen we see, classic or new... Setting is usually the first part of WordPress customization.

**Comment by jameskoster** [comment]
Turning it off in the settings honestly sounds like more work than simply clicking the `X` the first time you see it?

**Comment by jameskoster** [comment]
Any thoughts @youknowriad? I'm thinking this would be ok to merge, and we can refine the slides (if needed) once have a clearer picture of exactly what template editing functionality will ship in 5.8.

**Comment by youknowriad** [comment]
Sounds good to me, what about removing the snackbar notice? Isn't it just a duplication now?

**Review by youknowriad — APPROVED** [review]

**Comment by jameskoster** [comment]
Yes I think that's fair. The welcome guide + the frame should be adequate in communicating when a user is in template editing mode.

**Comment by youknowriad** [comment]
While trying to remove the notices, I kind of changed my mind :P. The snackbars can be useful if it's not the first time you go into template mode (say you create a template for a post but you already got the introduction). Let's keep them for now and reconsider later.

**Comment by Mamaduka** [comment]
I also find them useful reminders.

**Comment by youknowriad** [comment]
Looks like the change here introduced a failure in e2e tests, I think the welcome guide is getting in the way of the test :) Maybe we can do something like the post editor and auto close this automatically. Is this something you can help with @Mamaduka ?

**Comment by Mamaduka** [comment]
@youknowriad I can try to have a look later today but might be too late for a release.

P.S. Sorry, I would love to do it now, but currently in line for my vaccine jab 💉

**Comment by talldan** [comment]
I can take a look.

**Comment by paaljoachim** [comment]
Testing.

WordPress 5.7.2. Twenty Twenty One.
A special Gutenberg version of this PR.

This is what I see:


https://user-images.githubusercontent.com/5323259/118801447-5168cc00-b8a1-11eb-8bf7-578982d45447.mp4


It is really helpful having the Welcome Guide in place.

**Comment by talldan** [comment]
c354833d1876721b70d74423a442ba38746a720e should fix the tests, and I've rebased so that the fixes in `trunk` are in this branch too.

**Comment by youknowriad** [comment]
Thanks @talldan

**Comment by Mamaduka** [comment]
Thanks, @talldan.

**Pull request merged**
