### PR TITLE
Add contenteditable to tinymce instance.

### PR DESCRIPTION
**Pull request by jasmussen**
This allows us to test on mobile.

### CODE REVIEW

**Comment by jasmussen** [comment]
Actually don't approve this quite yet. @mtias posed a good question: shouldn't TinyMCE add the `contenteditable` property dynamically? And so could it be that TinyMCE isn't working on mobile at all, or is there something else going on? 

As it stands, this prototype doesn't work on an iPhone: https://wordpress.github.io/gutenberg/tinymce/

With `contenteditable="true"` added, as this PR did, editing works. Here's a video, which also shows the link boundary feature not working as it does on a desktop:

https://cloudup.com/cDp3NDa3TSp

CC: @spocke @Afraithe any insights? Thanks

**Comment by spocke** [comment]
You shouldn't need to add any contenteditable true. Could be some initialization thing with the prototype a.f.a.i.k. it loads properly on iphone. The link was blue on the iphone if I dragged the caret inside so it seems to be loading at least from here. It loads the tinymce js file from our fiddle domain and that is not a proper cdn so it takes a while to load.

Setting contenteditable="true" would just fake an editor until it's loaded so not sure what that would do once the editor does get loaded if it's in a editing state.

**Comment by jasmussen** [comment]
Thanks for looking. So does that URL work on your iPhone? On my iPhone 6 in Safari, the soft keyboard never comes up. It behaves as just a non-editable div. Perhaps there's a race condition?

Let me know if there are other ways I can help test on iphone/ipads.

**Comment by mtias** [comment]
It works for me on iPhone.

**Comment by Afraithe** [comment]
Yes, the area is editable for me on a iphone without a bt keyboard. (Iphone 6+)

There are 2 issues here, 
- contentEditable=true, this should definetly not be needed, something else is wrong (editor isn't loaded?)
- BT keyboard not working with the boundry link feature, I went out this lunch and got Spocke his shiny new Apple BT keyboard to test this with. Need to get him a bigger desk, 3 keyboards on it now.

**Comment by nylen** [comment]
@jasmussen can we close this one out?

**Comment by jasmussen** [comment]
Yes, sorry! Closing!

**Pull request closed without merging**
