### PR TITLE
Fix AlignmentMatrixControl focus issue

### PR DESCRIPTION
**Pull request by rmorse**
## Description
This fixes a bug in the AlignmentMatrixControl where simply rendering a control triggers a focus event which in turn triggers a change event / state change.

To replicate
- add a new cover block, change the alignment (eg, bottom right) then close the control / block
- re-select the block, and click the button to open the alignment matrix again
- Notice it immediately resets itself to top left (with a state change)

After digging around I realised this was to do with the fact the `onChange` event is triggered by `onFocus` of the `cell`.

I think due to the way the reakit components work (I'm not too familiar), when rendering, the first element is focussed immediately/automatically - in this case `top left`.

Looking at [their docs](https://reakit.io/docs/composite/#performance), I see examples of a `CompositeItem` using `onClick` - so I tried with that and it works.

What this does "break" is:
- Previously when the control is visible (after pressing the button to show it), any keyboard arrow presses would immediately trigger a state change and update the cover attributes
- Now, navigating with a keyboard doesn't commit any change to the block until enter has been pressed

Personally, I think this still feels natural, but I think it may need a bit of a rethink in terms of UI - perhaps, we have a "focussed" color state for when the keyboard is in the process of selecting an alignment, and when it is selected, we get the larger, black square we currently have.

## How has this been tested?
By opening the control an observing behaviour to mouse + keyboard events

## Screenshots 
Before:
align-matrix-issue

After:
align-matrix-issue-after

## Types of changes
This is a 1 line bug fix that will only have a small negative effect for keyboard users - and fixes a bug that causes a state change whenever the component is rendered.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by diegohaz — COMMENTED** [review]
Thanks, @rmorse!

With #27699, the `useFocusOnMount` hook — the popover uses that — has been changed so it looks for tabbable elements right away when the popover element is mounted. At this point, in the very first render, all the composite items have `tabIndex="0"` (in a second render, only the active item will have `tabIndex="0"`). That's why the first item is receiving focus even when it's not the active item.

To keep the current behavior (reflecting the change on the UI when navigating with the keyboard), I suggest we force the `tabIndex` value instead of using `onClick`.

**Comment by rmorse** [comment]
Ah yes that makes better sense :) thanks!

**Review by diegohaz — APPROVED** [review]
This looks good! Thanks! The failing test is not related to this change and I think was fixed on master already.

**Comment by diegohaz** [comment]
@rmorse Can you please merge master into your branch?

**Comment by rmorse** [comment]
@diegohaz done :)

**Pull request merged**
