### PR TITLE
Add global styles PHP filters

### PR DESCRIPTION
**Pull request by aristath**
See #27504 

## Description

Adds 2 new filters:
* `global_styles_get_data`: Filter JSON for global-styles
* `global_styles_get_stylesheet`: Filter generated css from global-styles

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by aristath** [comment]
Today I came across another issue that highlighted the importance of these filters:
I wanted to only load a google-font if the user has selected it in their global-styles... To do that we need to be able to hook in there and check all fontFamily selections.

**Comment by carolinan** [comment]
I ran into the same problem or question today as I was preparing a post about theme directory requirements for full site editing themes.

Themes are required to enqueue their fonts.
If a theme adds several font family options, it would have to enqueue all fonts in the editor and front at all times,
because there is currently no easy way to find out which font the user has selected.
Including all fonts that way would increase the loading time and would go against best practices.

There needs to be a filter that is easy to use, to keep the entry barrier low.

**Comment by gziolo** [comment]
@jorgefilipecosta and @nosolosw, do you have it on your radar? I think I saw another PR that proposes filters for Global Styles.

**Comment by aristath** [comment]
Closing this one as it's no longer relevant.

**Pull request closed without merging**
