### PR TITLE
Update writing-your-first-block-type.md

### PR DESCRIPTION
**Pull request by truongwp**
## Description
Fix some wrong strings in writing-your-first-block-type.md

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
Hey @truongwp - thanks for spotting this!

It looks like the file also has an ESNext example, and if a user is following that they'll have written 'Basic example with JSX! (editor)' or 'Basic example with JSX! (front)'.

I think it'd be good to change the ESNext example so that it uses the same string as the ES5 version. Would you be happy to change that?

**Comment by gziolo** [comment]
> I think it'd be good to change the ESNext example so that it uses the same string as the ES5 version. Would you be happy to change that?

If we are going to change code snippet, we should also update their corresponding example in https://github.com/WordPress/gutenberg-examples repository. The idea is that the tutorial re-creates the same code.

**Comment by truongwp** [comment]
@gziolo I can check all tutorials and make them be the same as the handbook

@talldan Yes, I will change that

**Review by gziolo — APPROVED** [review]
Nice thank you for adding these changes 👍

**Comment by gziolo** [comment]
Opened a follow-up PR: https://github.com/WordPress/gutenberg-examples/pull/73.

**Pull request merged**
