### PR TITLE
Reuse isHorizontalEdge for RichText

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This branch removes some duplicate logic in RichText where isHorizontalEdge can be used. We do have to move dom utils though.

## How Has This Been Tested?
Make sure backspace can still be used to merge blocks. Also make sure blocks are not merged unless the caret is really at the start or end.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
A meta-question which is not so specific to this pull request: What is the long-term plan for `utils`? It's convenient because it's already exposed as a module, but it concerns me especially because its a single shared scope of variables. The fact that we have named files within it exported by `index.js` makes me wonder why those individual files aren't themselves modules, e.g. `@wordpress/dom`. Is it merely the fact that there's overhead in creating a module that deters us from wanting to do this? Or is this too granular? Is `utils` a legitimate and useful classifier for these types of functions?

**Review by aduth — APPROVED** [review]
A nice consolidation 👍

**Comment by iseulde** [comment]
@aduth I was wondering the same thing... Also a lot of these functions in dom.js seem like random utility things rather than some well baked module. Not sure what to do for now.

**Comment by iseulde** [comment]
Oh and apart from `getScrollContainer` (not sure it belongs to that file), these are selection API helper functions. Maybe we should rename that file and/or move it to a separate module.

**Comment by youknowriad** [comment]
I believe this PR introduced this regression #5345 

This probably means `isHorizontalEdge` works differently than `isEndOfEditor`

**Comment by iseulde** [comment]
@youknowriad It works the same but doesn't seem to account for empty containers.

**Pull request merged**
