### PR TITLE
Update Dashicons.

### LINKED ISSUE #528: SVG icons accessibility
SVG icons are tricky for accessibility. Some browsers/screen readers combinations announce the SVG `<title>` (if any) no matter what you try to do to avoid it. Even adding `aria-hidden="true"` to the icons doesn't work for some combos.

IE 11 + NVDA:

ie11 nvda svg title

IE 11 and AViewer (see the SVG title is part of the calculated accessible name):

ie11 svg title

Are the `<title>` really needed? Is there any case where we'd want the SVG icons to be announced? I guess the titles could be entirely removed, and when UI controls that use the icons need to be labeled, that could be done on the controls, for example:
`<button aria-label="Some label here"><SVG here></button>`

@davidakennedy and @samikeijonen could chime in here, they have a lot of experience with SVG icons for all the job done for Twenty Seventeen 🙂

### PR DESCRIPTION
**Pull request by jasmussen**
This removes the title element from the sprite. This should finally fix #528.

Corresponding upstream PR: https://github.com/WordPress/dashicons/pull/192

### CODE REVIEW

**Comment by jasmussen** [comment]
It looks like the tests fail for the icon unit test. Is that test written to look for the title? @BE-Webdesign I think you may have done some of the magic here, can you provide me with a sanity check (not urgent)? I know I made a mistake upstream that I'm fixing, but I'm not sure what's up here. Thank you.

**Comment by BE-Webdesign** [comment]
@jasmussen,

Okay read over #528, are we supposed to add an `aria-label` instead.  If you need help let me know I can either fix it for you or show you how to change the tests.

**Comment by jasmussen** [comment]
> Okay I read over #528, are we supposed to add an aria-label instead? T

My reading is that whatever label we add should be in a parent containing element:

`<button aria-label="Some label here"><SVG here></button>`

CC: @afercia

**Comment by afercia** [comment]
Yes when the icon is not purely decorative and represents content that needs to be announced, then this content can be provided as aria-label on the containing element or, as mentioned in #528, using the Twenty Seventeen approach with screen-reader-text e.g.:
```
<button type="submit" class="search-submit">
	<svg class="icon icon-search" aria-hidden="true" role="img">
		<use href="#icon-search" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-search"></use>
	</svg>
	<span class="screen-reader-text">Search</span>
</button>
```

Either way, the title should be removed. 

I forgot to clarify that SVGs should also have `aria-hidden="true" role="img"`, sorry for being unclear.

**Comment by BE-Webdesign** [comment]
> <button aria-label="Some label here"><SVG here></button>

You have better eyesight than me 😲

**Comment by BE-Webdesign** [comment]
If you need any assistance with the tests let me know, happy to help.

**Review by aduth — APPROVED** [review]
Fixed failing test in 9b21b6fb8a150e262290c27a53b177e61687a95f. Up to you if you'd like to merge as-is and address @afercia's comment in a subsequent pull request:

>I forgot to clarify that SVGs should also have `aria-hidden="true" role="img"`, sorry for being unclear.

**Comment by jasmussen** [comment]
Thanks! Merging this and putting in an upstream fix again.

**Pull request merged**
