### PR TITLE
Bump e2e test utils version

### PR DESCRIPTION
**Pull request by vcanales**
## Description
Necessary since a new function was added, but the previous version seems to be cached, causing e2e tests to fail.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by tellthemachines** [comment]
Hi @vcanales ! Version bumps are managed automatically as part of the release process. In this case, version 4.15.0 is the latest, so bumping to 4.15.1 won't work. You can always check the latest version of any package on [its npm page](https://www.npmjs.com/package/@wordpress/e2e-test-utils).

**Comment by vcanales** [comment]
> Hi @vcanales ! Version bumps are managed automatically as part of the release process. In this case, version 4.15.0 is the latest, so bumping to 4.15.1 won't work. You can always check the latest version of any package on [its npm page](https://www.npmjs.com/package/@wordpress/e2e-test-utils).

I see, thanks for the heads-up. What would be the correct process to release a new version of this package? As I mention in the description, not bumping the version is causing e2e tests breakage.

**Comment by tellthemachines** [comment]
> What would be the correct process to release a new version of this package? 

It's unlikely the package will be updated before mid-November when 5.6 RC1 is complete, as up to then we'll only be releasing patch updates for Core.

> As I mention in the description, not bumping the version is causing e2e tests breakage.

Could you provide some more details on which tests are failing, and how you're running the test suite? I'm assuming you're not running it within the Gutenberg repo, as in that case you'd have access to the latest `e2e-test-utils`.

**Comment by vcanales** [comment]
> Could you provide some more details on which tests are failing, and how you're running the test suite? I'm assuming you're not running it within the Gutenberg repo, as in that case you'd have access to the latest `e2e-test-utils`.

It was failing on PRs such as [this one](https://github.com/WordPress/gutenberg/pull/26353/checks?check_run_id=1314179190#step:7:46), but I realize now that it's not doing the same for newer PRs. I think it may have been a matter of updating dependencies, clearing the dependency cache, or something else that I can't identify.

The specific error that I was getting was related to a function called `activateTheme`, which was added to `e2e-test-utils` earlier yesterday. CI was complaining about it not being present on some PRs, and I was able to fix the issue on this PR by bumping the version, as that invalidated the previous version of `e2e-test-utils`, which didn't have the new function.

I'm closing this now, as it seems to have been fixed elsewhere, maybe because the cache expired; honestly how the GitHub actions dependency caching works is a mystery to me, but my theory is that `e2e-test-utils` wasn't being built on GitHub Actions, therefore the new function was temporarily unavailable.

**Pull request closed without merging**
