### PR TITLE
Prevent unexpected copying of the post title

### PR DESCRIPTION
**Pull request by t-hamano**
@edit: This PR originally attempted to solve the copying problem in the post title and the widget areas at the same time. However, I have decided to resolve the widget issues separately in a new issue #45398. For details, please see the edit history.

## What?
This PR prevents copying of a post titles.

## Why?

When text is selected in the post title, `getSelectedBlockClientIds` is executed.
The post title is a block, but the `clientId` is empty, so the correct block name cannot be obtained at this point:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/copy-handler/index.js#L34

As a result, a message with an undefined value is displayed.

https://user-images.githubusercontent.com/54422211/170080258-f1df225a-8d52-4a61-b05e-7cbc8c721204.mp4

## How?

Make `getSelectedBlockClientIds` return an empty array if clientId of the selected block is an empty string or undefined value.

## Testing Instructions

- Select one of the letters in the post title.
- Click between the letters to deselect them.
- Press `Ctrl(Cmd)` + `C` or `Ctrl(Cmd)` + `X` .
- **On trunk**: Confirm that the notification message contains "undefined" text.
- **On this branch**: Confirm that no notification message appears and nothing is copied to the clipboard.

### CODE REVIEW

**Comment by t-hamano** [comment]
The unit test failed, so I would like to find out where the mistake is.

**Review by Mamaduka — COMMENTED** [review]
Thanks for the PR, @t-hamano.

I didn't get a chance to start reviewing this yet.

Can you update the title and description so it matches the latest changes?

**Comment by t-hamano** [comment]
@Mamaduka 
I have updated the title and description.
However, I think there is a mistake somewhere. because e2e tests failed.
I would like to update PR so that e2e tests pass in my local environment.

**Comment by t-hamano** [comment]
The rebasing passed all tests.
Please advise if you have a better approach to this PR,

**Comment by t-hamano** [comment]
I have confirmed that this problem still reproduces with the latest trunk. I have also confirmed that this PR will solve the problem.
I would appreciate it if someone could review if this PR makes sense 🙏

**Comment by michalczaplinski** [comment]
Taking a look at this now!

**Comment by michalczaplinski** [comment]
Thanks for the PR @t-hamano! I've tested it and confirmed that it fixes both issues as you described.

- The fix for the post title is great 👍 Awesome work.

- The fix for the widget areas I am little hesitant about. The previous UX was:
  
  1. A user copies a widget.
  2. They try to paste it in the block editor.
  3. They are faced with an error message so they remove the content.
  
  The UX in this PR is:
  
  1. A user copies a widget.
  2. They try to paste it in the block editor.
  3. The content does not paste anything and the user does not know why. They might see that nothing is copied into the clipboard at which point they would might try copying the widget again and pasting it again. Not a great user experience.
  
  So while I understand that the widget area blocks can't be used by the block editor and their HTML has no use I think it's still a better user experience to show an error message in the block editor rather than fail to copy them.

**Comment by noisysocks** [comment]
I don't think we should fix this by adding an exception to `@wordpress/block-editor` code. `@wordpress/block-editor` is pretty low level and shouldn't have to worry about specific scenarios in which it is used including the widgets editor.

Is there an alternative way to fix this in `@wordpress/edit-widgets`?

Thinking more higher level, I think this is yet another example of why it was a mistake to implement widget areas using blocks 😅 See https://github.com/WordPress/gutenberg/issues/33254.

**Comment by t-hamano** [comment]
Thank you for the review, @michalczaplinski!

> So while I understand that the widget area blocks can't be used by the block editor and their HTML has no use I think it's still a better user experience to show an error message in the block editor rather than fail to copy them.

This PR prohibits the copying of the widget area itself, so the snack bar message itself does not appear to indicate that it has been copied.
Therefore, we do not think there is a problem with UX, how do you think?

**Comment by michalczaplinski** [comment]
Hey @t-hamano !

Aside from the question of the user experience I'm afraid I'll have to side with @noisysocks here (thanks for chiming in Robert, btw!). Sorry about this! I didn't consider that the `block-editor` should be agnostic of things like widgets.

I'd still very much like to fix this issue but I'm not very familiar with the `edit-widgets` package. Do you see any other way to fix it in `@wordpress/edit-widgets` @t-hamano ?

**Comment by t-hamano** [comment]
I am trying to solve this in the `@wordpress/edit-widgets` package, but so far it has not worked 😅
I cannot prevent the copy handler provided by `@wordpress/block-editor` by any means. I would like to try a few more approaches.

**Comment by t-hamano** [comment]
As for the widget area fix, I have yet to find a workable solution, so I have cut it out as a separate issue #45398, and reverted the changes. Also, perhaps I should not have addressed the two issues at the same time.

Sorry for the confusion 🙏

**Review by michalczaplinski — APPROVED** [review]
The fix works great @t-hamano 👍 

We can tackle the widgets issue in the other PR!

**Pull request merged**
