### PR TITLE
[Experiment] Capture screencasts for failing tests

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Capture screencasts for failing tests.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by adamziel** [comment]
💯  thank you for exploring that @kevin940726 ! I wonder if it would be simpler to leverage this API instead:

```js
let displayMediaOptions = {video: true, audio: false};
navigator.mediaDevices.getDisplayMedia(displayMediaOptions)
.then(function(stream){
  video_el.srcObject = stream;
})
```

Normally you have to click on a dialog window to confirm which window you want to capture, but I wonder if there's a way around that in puppeteer. This could potentially help: https://github.com/puppeteer/puppeteer/issues/4835

**Comment by adamziel** [comment]
I can see the video in the artifacts bundle, great job! One thing that's inconsistent is how short the video is (3s)
 compared to the error message (`TimeoutError: waiting for function failed: timeout 30000ms exceeded`)

**Comment by youknowriad** [comment]
Any details about this change? What was wrong previously?

**Comment by adamziel** [comment]
@youknowriad it's a new thing. We have a screenshot capture now, this adds a video capture.

**Comment by gziolo** [comment]
That's a nice feature 👍🏻 

I'm wondering how much does it impact the duration of individual tests when the screencast is recorded. For the screenshot you only take an action when the test fails, here you probably need to record every test and store it only when the test fails.

**Comment by kevin940726** [comment]
Superseded by #38570.

**Pull request closed without merging**
