### PR TITLE
Separator: Add means to control height

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## Description
* Add customizable height to the separator block

## How has this been tested?
Manually.

#### Testing Instructions
1. Checkout this PR, create a new post and add a separator block
2. Select the separator block and adjust its height via the bottom resize handle
3. Confirm the block still displays correctly and that different colors & block styles can be applied.
4. Adjust the separator block's height via the height control in the sidebar control and confirm the block's height updates
5. Change the height units between `px`, `em` or `rem`. Switching units will reset the height. Adjust it again via the sidebar control and confirm visual height of block adjusts.
6. Save the post and confirm the separator's height on the frontend
7. Repeat steps 1-6 using different themes (several use varying methods of styling the block e.g. bottom borders, background colors and pseudo elements).

#### Native Testing Instructions
1. Checkout this PR, start up native emulation e.g. `npm run native start` and `npm run native ios`
2. Add a separator block to the post
3. Open the block's controls and adjust its height in pixels
4. Switch to other height units and ensure that the control's value is set to the default for that unit and the block's height visually adjusts accordingly.

## Screenshots 
SeparatorHeightV2

[Previous pixel height only iteration screenshot](https://user-images.githubusercontent.com/60436221/105670260-77eaac00-5f2c-11eb-9130-97cd417764c1.gif)

## Types of changes
New feature.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
As far I remember this blocks is cross-platform and works in React Native. I anticipate this refactoring will break it in the mobile app.

@hypest, I'm flagging it so the mobile team could advise on how to move forward in a seamless way.

**Comment by hypest** [comment]
Thanks for the ping @gziolo , I opened https://github.com/wordpress-mobile/gutenberg-mobile/pull/3041 on the gutenberg-mobile side to have the extended native mobile tests run. We can look into this deeper if any test fails 👍

**Comment by geriux** [comment]
Hey 👋 

> I anticipate this refactoring will break it in the mobile app.

Indeed, it's broken using this PR.

One issue is related to accessing an undefined variable:

<kbd></kbd>


Second, is because it's using `div`:

<kbd></kbd>

We had similar [issues](https://github.com/WordPress/gutenberg/pull/26157/files#diff-4be1bed70cc6656cd97abd3b8fdf26a6af6ce2af50eef512a84bd9bc7ad6c25eR19) for this block before. I'd suggest avoiding using `div` in cross-platform components but if it's really needed then using `View` from `packages/primitives/src/view`

Please let us know if there's something we can help with to not block this PR, even if it's just testing any new changes.

Thanks!

**Comment by apeatling** [comment]
@aaronrobertshaw I think this should also include an input field so the user knows what height has been set, and adds the ability set a specific value. Much like the search block input minus the percentages?

Screen Shot 2021-01-22 at 11 37 52 AM

**Comment by paaljoachim** [comment]
Here is an issue for the Separator block: https://github.com/WordPress/gutenberg/issues/25989
There is also an older PR here: https://github.com/WordPress/gutenberg/pull/26764

**Comment by paaljoachim** [comment]
Or we can also use the same setup as the Spacer block.

Screen Shot 2021-01-23 at 00 20 12

@ItsJonQ and @jasmussen might also want to know about this PR.

**Comment by aaronrobertshaw** [comment]
Thank you everyone for the testing and feedback 👍 

> I think this should also include an input field so the user knows what height has been set, and adds the ability set a specific value. Much like the search block input minus the percentages?

A control for the separator's height has been added to the sidebar matching the control in the spacer block as suggested.

> Indeed, it's broken using this PR.

I've added optional chaining to the call to replace the problematic class from the `className`. As suggested I've replaced the `<div>` with `<View>`. I no longer receives the reported errors when running this PR on mobile locally.

Regarding the use of `div` or `View`, I couldn't find a way around needing a wrapper here to still maintain the styling for the visual separator itself. There is a mix of approaches to styling the separator such as border bottom (default style), pseudo elements (dots) and background with fixed height (custom colors, non-dots). On top of that, different themes took different approaches again. So the wrapper to provide the height in the editor was the best that worked for me. The frontend remains essentially the same except for the styles splitting the height into as top and bottom margins on the normal `<hr>`.

@geriux it would be good to take you up on that offer to give this PR another test. 

I also attempted simply adding the height control to the `separator-settings.native.js` file. While that works for specifying the height, the display of the block in the editor would need updating so that the separator's `hr` is vertically centred in the wrapper. I'm not sure of the best course of action here or whether I should be adding the native controls at all at this point.

Open to any suggestions on that.

**Comment by aaronrobertshaw** [comment]
Another approach to adding margins or height to the separator block can be found in https://github.com/WordPress/gutenberg/pull/28451 created today.

**Comment by paaljoachim** [comment]
#28451 contains a very fascinating suggestion about how to better control where the line is seen in the Separator block!
In addition one would be able to change the width of the Separator line.

**Comment by aristath** [comment]
Just my 2c: On my FSE theme I have responsive/adaptive typography (see [theme.json](https://github.com/aristath/q/blob/9c84d8f9f661da493ff89bb863a91d8826ec07da/experimental-theme.json#L41)). If the height is limited to `px` values then it will look OK for one viewport, but not scale properly for all viewports unless it's possible to also use `em` values.

**Comment by apeatling** [comment]
This is one reason to use the same control as the search block. You can then select different units, including ems.

**Comment by aaronrobertshaw** [comment]
I've updated this to use a `<UnitControl>` allowing non-pixel heights. The `<ResizableBox>` element didn't want to play nice with values that weren't in pixels or percentage. That said, I've worked around that such that we can at least see how the `ResizableBox` and its draggable handles UI might work with margins or heights of different units.

I'd say it would be possible to combine this with the approach using the margins-based spacing support.

The PR description has been updated with a [new GIF of the current UI](https://user-images.githubusercontent.com/60436221/105989563-086fea80-60ed-11eb-9aad-066ba80cb9b8.gif).

**Comment by aaronrobertshaw** [comment]
After evolving this PR to handle different units, `em` & `rem`, the resulting code could benefit from a refactor. I think it's important to settle on an agreed approach and UI moving forward though before investing further efforts.

Notes:

- Using the `Resizablebox` gives a more user friendly option to control height
- This PR's wrapper allows for the separator block to be easily selectable by clicking anywhere in its height. 
- If only adjusting the margin you have to use the block navigator or be able to target the very thin `<hr>` to select the block.
- Changing units results in a reset of the height value

Next steps:

- Should the UI include the `ResizableBox` component to provide user friendly draggable sizing? 
- Refactor this PR to polish up the code
- Possibly iterate again to use spacing support to control margins

**Comment by geriux** [comment]
> @geriux it would be good to take you up on that offer to give this PR another test.

@aaronrobertshaw related to the things you mentioned for the vertical alignment issue and the settings, I pushed [some changes to another branch](https://github.com/WordPress/gutenberg/compare/add/custom-separator-height...add/custom-separator-height-mobile?expand=1) and I was able to have it working like this:

<kbd></kbd>

One thing I had to change was the default height for the main container, not sure if that would break your current work. Let me know! Thanks!

**Comment by aaronrobertshaw** [comment]
@geriux Thanks for all the effort working on the mobile side to this! 👍 

> One thing I had to change was the default height for the main container, not sure if that would break your current work. Let me know! Thanks!

Unfortunately, that does break the functionality allowing non-pixel units such as `em` and `rem`.

I haven't been able to spend much time exploring this yet but will be able to take a deeper dive on Monday. My guess is we need a dedicated `edit.native.js` file to handle the mobile specific behaviour.

Using the cover block as an example, it allows non-pixel units for its minimum height, but requires converting those non-pixel values via `useConvertUnitToMobile` hook. That in turn relies on the `GlobalStylesContext`.

https://github.com/WordPress/gutenberg/blob/37feae16118334b48c01c444c95a710298ed32c3/packages/block-library/src/cover/edit.native.js#L106-L109

**Comment by aaronrobertshaw** [comment]
I've taken another run at updating the display and control of the separator block's height on mobile. It's a bit rough at the moment and could do with a refactor, which I'll do if the general approach gets the nod.

**Comment by geriux** [comment]
> I've taken another run at updating the display and control of the separator block's height on mobile. 

That looks great! Thanks for making the changes for mobile!

>  My guess is we need a dedicated edit.native.js file to handle the mobile specific behaviour.

Yeah, I agree. It made more sense to share the same file before since it was a very simple component.

**Comment by aaronrobertshaw** [comment]
Thanks @stokesman, I appreciate your time taking a look at this PR and the work on the alternative approach.

> I think there's been some recent regression around block selection that has something to do with that. I haven't seen it reported but was meaning to get to that.

The current situation is less than ideal, it definitely shouldn't be so hard to click to select the block. Given this is the primary means of block selection, I'd say it's pretty important to address.

> On an implementation note, it's interesting that the height is applied through margins. Say this lands and then later margin is added to spacing block support. We'd have to avoid enabling margin for the Separator block (and forgo control of individual sides). Or, if enabled, we'd have to remove the height control (or maybe have the height update as the margins update, which seems funky).

Given the current methods of styling the separator's `<hr>`, leveraging margins does solve the problem without introducing additional markup purely for an aesthetic change.

I don't have very strong opinions on how a custom separator height is implemented behind the scenes. One big issue though is the UX around how the user achieves that custom height. 

I think the ability to click a drag handle in the editor itself to visually resize the height of the block is a must. It is the most intuitive means of doing this and is consistent with the Spacer block. The `UnitControl`, or even the spacing control in the future, within the sidebar gives power users finer control over the height. For example using `ems` so its height matches responsive/adaptive typography. 

Being able to adjust the top and bottom margins independently had been considered however I thought it best to leave to a future iteration. Left and right margins I think will interfere too much with block alignments.

> I wonder about the need to support this feature for now. 

We have a number of block patterns driving the need for this rather soon. 

I think you are right, wrapping the separator in a group block could achieve a similar outcome. For the average user though, I do not think that is going to be very intuitive or even thought of.

**Comment by stokesman** [comment]
Thanks for the thorough reply @aaronrobertshaw

>Being able to adjust the top and bottom margins independently had been considered however I thought it best to leave to a future iteration.

I'd been concerned about the feasibility of a future iteration, at least with regards to integration with spacing block supports. Akin to what is brought up in #28518 (which you may have good suggestions for given your work on the PRs mentioned within).

After further consideration, any concern of mine is gone. I've realized that even if an ad-hoc implementation here could make difficult any later block spacing integration, the features that could be enabled by that (and are probably more niche uses anyway) can be had with the idea I'd suggested previously. E.g. If it's desired to adjust the spacing on the sides it can put it inside a Group to provide the padding.

One idea I had for this PR is that maybe it wouldn't hurt to label the setting “Vertical margins” since that's actually what gets adjusted. Plus it makes sense for splitting out as top and bottom in a later iteration.

**Comment by aaronrobertshaw** [comment]
> I'd been concerned about the feasibility of a future iteration, at least with regards to integration with spacing block supports. Akin to what is brought up in #28518 (which you may have good suggestions for given your work on the PRs mentioned within).

At this stage, I don't know what the outcome of https://github.com/WordPress/gutenberg/issues/28518 will be. It seems to me that a lot of things we need to accomplish are blocked by that. Leaving the user to go without a feature or suffer an inferior experience to what we could provide.

Even though the preferred way to add styles is via block supports, the current proposed approach to spacing doesn't provide the usability of the resizable box. This block could be argued to add a new category to the linked issue where the block support controls are insufficient to a block's needs. 

The downside is the inability to leverage global styles or the theme.json for this first iteration. Themes can already target the separator block with standard CSS so the sacrifice appears to be a user not being able to override that via global styles.

> After further consideration, any concern of mine is gone. I've realized that even if an ad-hoc implementation here could make difficult any later block spacing integration, the features that could be enabled by that (and are probably more niche uses anyway) can be had with the idea I'd suggested previously.

In the case of this PR, despite the complexity around the UI, it really comes down to setting an attribute representing the height and then using that to apply margins when the block is saved. That attribute could be `height` as it is now or `marginTop`/`marginBottom`. Once spacing with margins support was in place, I saw it being a matter of adding a deprecation that moved the attribute value into the appropriate style attribute property. Then updating the UI around the controls injected via block support. This is assuming the decision to opt-in to spacing margins support is made.

Given the wide spread implications of the spacing controls using margins, I didn't see that being something that landed in the near future.

**Comment by stokesman** [comment]
A couple of issues I saw in testing this and #28688 were that the first attempt to drag the handle doesn't work (unless height was already established by setting it in the inspector controls) and the height does not update while dragging (unlike in the Spacer block).

**Comment by aaronrobertshaw** [comment]
> A couple of issues I saw in testing this and #28688 were that the first attempt to drag the handle doesn't work (unless height was already established by setting it in the inspector controls) and the height does not update while dragging (unlike in the Spacer block).

The issue preventing drag resizing on initial insertion has been fixed. The height isn't currently set in the attributes until the resize is complete in the `onResizeStop` handler. Updating the height on every resize event at the moment is pretty chunky. I will address that when I polish whichever out of this PR or https://github.com/WordPress/gutenberg/pull/28688 moves ahead.

**Comment by stokesman** [comment]
>Updating the height on every resize event at the moment is pretty chunky.

Not surprising but I'd guess no worse than other blocks' resizing operations. Also, I do find any dragging-based interaction in Gutenberg to get much chunkier when the dev tools are open.

**Comment by aaronrobertshaw** [comment]
This now sets the height `onResize` rather than `onResizeStop`.

**Comment by apeatling** [comment]
I think we should concentrate on https://github.com/WordPress/gutenberg/pull/29363 and look to add the handle in a future iteration.

**Comment by aaronrobertshaw** [comment]
Thanks @apeatling , I'll close this PR in favour of #29363

**Pull request closed without merging**
