### PR TITLE
Added a "plain" style for quote blocks

### PR DESCRIPTION
**Pull request by Baelx**
## Description
- Implements #28524

## How has this been tested?
Ran `npm run test`. All tests passing.

## Screenshots
image
image
image

## Types of changes
Simply adds a "Plain" style to quotes to allow them(in part) to function as text indentation. Selecting "Plain" will set border-left: none in the code.

## Checklist:
- [ X ] My code is tested.
- [ X ] My code follows the WordPress code style. 
- [ X ] My code follows the accessibility standards. 
- [ X ] I've tested my changes with keyboard and screen readers. 
- [ N/A ] My code has proper inline documentation. 
- [ N/A ] I've included developer documentation if appropriate. 
- [ N/A ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Baelx** [comment]
`npm run test` should have caught the error above given it runs `npm run test-e2e`. Nevertheless, I'm now having a lot of difficulty generating a new snapshot for the quote block but that's all that's needed at this point. If someone with a fully-functional test framework for Gutenberg feels like pulling this branch, updating the snapshot, that'd be appreciated. Otherwise, I'll delete this PR until I'm up and running. Cheers.

**Review by talldan — APPROVED** [review]
@Baelx Thanks for working on this, looks good in my testing.

I think this test is going to be troublesome because of the way it uses an index to click on a style:
https://github.com/WordPress/gutenberg/blob/8c95aeddf2a3c206d2ccb756614cefa747948fce/packages/e2e-tests/specs/editor/various/style-variation.test.js#L26

If other styles are added it'll fail again. It'd be better to use the style's name. I updated the file to the following and it passes (the test description was also wrong so including it in my code snippet below):
```js
describe( 'Block styles', () => {
	beforeAll( async () => {
		await createNewPost();
	} );

	it( 'Should switch to the large style of the quote block', async () => {
		// Inserting a quote block
		await insertBlock( 'Quote' );
		await page.keyboard.type( 'Quote content' );

		await clickBlockToolbarButton( 'Quote' );

		const largeStyleButton = await page.waitForXPath(
			'//*[@role="menuitem"][contains(., "Large")]'
		);
		await largeStyleButton.click();

		// Check the content
		const content = await getEditedPostContent();
		expect( content ).toMatchSnapshot();
	} );
} );
```

FWIW-I usually update snapshots using watch mode (`npm run test-e2e:watch`), sometimes I use the filters provided by watch mode to only run the test in the file in question.

**Comment by Baelx** [comment]
> @Baelx Thanks for working on this, looks good in my testing.
> 
> I think this test is going to be troublesome because of the way it uses an index to click on a style:
> https://github.com/WordPress/gutenberg/blob/8c95aeddf2a3c206d2ccb756614cefa747948fce/packages/e2e-tests/specs/editor/various/style-variation.test.js#L26
> 
> If other styles are added it'll fail again. It'd be better to use the style's name. I updated the file to the following and it passes (the test description was also wrong so including it in my code snippet below):
> 
> ```js
> describe( 'Block styles', () => {
> 	beforeAll( async () => {
> 		await createNewPost();
> 	} );
> 
> 	it( 'Should switch to the large style of the quote block', async () => {
> 		// Inserting a quote block
> 		await insertBlock( 'Quote' );
> 		await page.keyboard.type( 'Quote content' );
> 
> 		await clickBlockToolbarButton( 'Quote' );
> 
> 		const largeStyleButton = await page.waitForXPath(
> 			'//*[@role="menuitem"][contains(., "Large")]'
> 		);
> 		await largeStyleButton.click();
> 
> 		// Check the content
> 		const content = await getEditedPostContent();
> 		expect( content ).toMatchSnapshot();
> 	} );
> } );
> ```
> 
> FWIW-I usually update snapshots using watch mode (`npm run test-e2e:watch`), sometimes I use the filters provided by watch mode to only run the test in the file in question.

Thanks a lot for that, @talldan. That makes sense!

**Comment by talldan** [comment]
@Baelx Just checking in, will you be able to update that test?

**Comment by Mamaduka** [comment]
Hi, @Baelx

I just wanted to check in if you have time to rebase and update the test?

Thanks

**Review by mkaz — APPROVED** [review]
It looks like this one just needed a push to get over the hump. I rebased and moved the updated style definition to block.json.

I also updated the test and snapshot per @talldan.

So I think this makes it good to go.

**Pull request merged**
