### PR TITLE
Remove aria-expanded from close button in Publish panel

### LINKED ISSUE #20278: Standarize 'close' icon across the UI
**Describe the bug**
We are currently using different versions of the 'close' icon in different parts of the UI. It'd be best if we standarize to a single one.

**Screenshots**
Screen Shot 2020-02-17 at 18 10 39
Screen Shot 2020-02-17 at 18 10 28
Screen Shot 2020-02-17 at 3 58 16 PM

### PR DESCRIPTION
**Pull request by enriquesanchez**
Fixes #20278

This tiny PR removes the `aria-expanded` attribute from the Close (X) button in the Publish panel. The attribute is not necessary in this button (the close button hasn't opened a menu) and it was making the button to be displayed in the wrong color.

## How has this been tested?
Locally.

## Screenshots

**Before:**
Screen Shot 2020-03-18 at 10 16 22

**After:**
Screen Shot 2020-03-17 at 18 53 47

## Types of changes
HTML and visual.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Looks good to me, well spotted! It looks like some snapshots need to be updated, but once that's done I don't see an issue merging.

**Comment by jasmussen** [comment]
I have a small fix I'd like to push to this one. Hold tight for a few minutes as I'm rebuilding my wp env because "don't ask" :)

**Review by jasmussen — APPROVED** [review]
Very nice PR, small and to the point — keep this going! I see this now:

now

This is superb. But I also discovered this:

Screenshot 2020-03-19 at 08 11 06

The border is off by one 😱 

So I took the liberty of pushing https://github.com/WordPress/gutenberg/pull/20993/commits/c36659999245eae9cc9e5730f1dd982e38186219 to address that. I also updated the snapshots.

Ship it!

**Comment by enriquesanchez** [comment]
Thank you @talldan and @jasmussen! Good catch on that border! 😄

**Pull request merged**
