### PR TITLE
Chrome: Try a foldable sidebar for the settings and the publish button

### PR DESCRIPTION
**Pull request by youknowriad**
Not sure this is something we want to do, but worth exploring. This uses a unique UI pattern (sliding sidebar) for The Post Settings, the block settings and the publish panel.

kapture 2017-11-01 at 11 26 22

### CODE REVIEW

**Comment by jasmussen** [comment]
Yay experimentation. You always did great work.

There's some interesting stuff here — moreso in actually trying out this branch than just looking at the GIF. 

I have a feeling that we'll probably want to keep the _sidebar_ using the behavior it always did — it's either toggled on, or off. But the sliding sidebar for the publish button seems really really interesting. 

Could we try a version that keeps the sidebar behavior from master, but slides the publish sidebar in on top, or does that require a crazy refactor of things? In my mind it would just cover the sidebar entirely, if already there, and it would cover the _content_ if not there.

**Comment by karmatosed** [comment]
Firstly, I am all for experiments as it's how we work out what we want. In this case I tend to think the existing behaviour feels better.

One thing we can take from this is the smoother interaction. Can we somehow bring that feeling to the action as it is?

**Review by karmatosed — COMMENTED** [review]
Firstly, I am all for experiments as it's how we work out what we want. In this case I tend to think the existing behaviour feels better.

One thing we can take from this is the smoother interaction. Can we somehow bring that feeling to the action as it is?

**Comment by karmatosed** [comment]
I am going to close this as I feel we reached a point with this. Let's iterate away from this PR.

**Pull request closed without merging**
