### PR TITLE
Add table block header and footer toggles

### PR DESCRIPTION
**Pull request by talldan**
Related issues: #15283, #6923

## Description
Adds some toggle switches to allow a user to add and remove header and footer sections to the table block.

## How has this been tested?
1. Add a table block
2. Specify the initial columns and rows
3. Use the toggle switches in the sidebar to display and hide header and footer rows

## Screenshots 
Screen Shot 2019-05-03 at 2 56 20 pm

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
This could definitely do with a design review. One area in particular would be making the table header and footer rows look nice. Especially with the striped style variation. Here's what it looks like with no styling:
Screen Shot 2019-05-03 at 3 01 40 pm

Something like this might be an improvement:
Screen Shot 2019-05-03 at 2 59 59 pm

(cc: @jasmussen - I remember you worked on stripes initially, let me know if you have any ideas on this 😄)

**Comment by talldan** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/15283

Perhaps given this information, the header section should be toggled on when creating a table?

**Comment by jasmussen** [comment]
This is what I'm seeing:

table

This isn't bad, actually!

The double borders beetween normal content and header or footer would be nice to not have. Not sure why they're present, but I can take a look if you need help. 

I don't think we need to, or even should, do anything at all to style the table or footer sections. These are primarily there for semantics, and we should allow their default styles to shine through. I.e. bold headers, and the footers just look the same. 

One question though is around flipping those switches. It's definitely boolean as it is now, which begs the question: is it ever okay to have _two_ headers in a row? Or two footers in a row? O)r could you have a tablehead in the middle of a table? Because if that's semantically allowed, we'll need a different approach entirely :/

**Comment by talldan** [comment]
Wow, thanks for that fast reply @jasmussen!

> The double borders beetween normal content and header or footer would be nice to not have. Not sure why they're present, but I can take a look if you need help.

I added them thinking it improved things visually 😊 Pretty easy to remove them 😄  

> I don't think we need to, or even should, do anything at all to style the table or footer sections.

It's worth checking out the striped variation. At the moment the stripes don't quite line up when a header is added. Not sure how we could make that work with pure css.

> One question though is around flipping those switches. It's definitely boolean as it is now, which begs the question: is it ever okay to have two headers in a row?

It is possible at the moment to add additional header/footer rows using the insert row option. I do have a concern that if the header/footer isn't presented differently it might be hard for the user to understand where they're inserting rows.

> Or could you have a tablehead in the middle of a table?

At the moment I definitely feel it's sensible to keep it simple. The table block should still support other complicated tables if they're pasted

**Comment by jasmussen** [comment]
Yep, definitely good thoughts, and I share your desire both to keep things simple, and to ship improvements like this feature which is missing.

My question is purely one of valid HTML semantics, and perhaps in a way even accessibility: is the following markup okay? 

````
<table>
    <thead>
...
    </thead>
    <tbody>
...
    </tbody>
    <thead>
...
    </thead>
    <tbody>
...
    </tbody>
</table>
```

If the above is not semantic/valid, it makes it a fair bit easier for us because those toggles can be completely fine for us even longterm. 

My concern is that if that markup is valid, a boolean choice is insufficient, and I'm worried about us moving too far down one path if we know at some point in the future we want to support something else.

**Comment by talldan** [comment]
@jasmussen I think we're ok. According to MDN:
> The [`<thead>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead "The HTML <thead> element defines a set of rows defining the head of the columns of the table.") must appear after any [`<caption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption "The HTML Table Caption element (<caption>) specifies the caption (or title) of a table, and if used is always the first child of a <table>.") or [`<colgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup "The HTML <colgroup> element defines a group of columns within a table.") element, even implicitly defined, but before any [`<tbody>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody "The HTML Table Body element (<tbody>) encapsulates a set of table rows (<tr> elements), indicating that they comprise the body of the table (<table>)."), [`<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot "The HTML <tfoot> element defines a set of rows summarizing the columns of the table.") and [`<tr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr "The HTML <tr> element defines a row of cells in a table. The row's cells can then be established using a mix of <td> (data cell) and <th> (header cell) elements.The HTML <tr> element specifies that the markup contained inside the <tr> block comprises one row of a table, inside which the <th> and <td> elements create header and data cells, respectively, within the row.")element.

(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead)

And for tfoot:

> The [`<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot "The HTML <tfoot> element defines a set of rows summarizing the columns of the table.") must appear after any [`<caption>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption "The HTML Table Caption element (<caption>) specifies the caption (or title) of a table, and if used is always the first child of a <table>."), [`<colgroup>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/colgroup "The HTML <colgroup> element defines a group of columns within a table."), [`<thead>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead "The HTML <thead> element defines a set of rows defining the head of the columns of the table."), [`<tbody>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody "The HTML Table Body element (<tbody>) encapsulates a set of table rows (<tr> elements), indicating that they comprise the body of the table (<table>)."), or [`<tr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr "The HTML <tr> element defines a row of cells in a table. The row's cells can then be established using a mix of <td> (data cell) and <th> (header cell) elements.The HTML <tr> element specifies that the markup contained inside the <tr> block comprises one row of a table, inside which the <th> and <td> elements create header and data cells, respectively, within the row.")element. Note that this is the requirement as of HTML5.\
[HTML 4](https://developer.mozilla.org/en-US/docs/HTML) The [`<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot "The HTML <tfoot> element defines a set of rows summarizing the columns of the table.") element cannot be placed after any [`<tbody>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody "The HTML Table Body element (<tbody>) encapsulates a set of table rows (<tr> elements), indicating that they comprise the body of the table (<table>).") and [`<tr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tr "The HTML <tr> element defines a row of cells in a table. The row's cells can then be established using a mix of <td> (data cell) and <th> (header cell) elements.The HTML <tr> element specifies that the markup contained inside the <tr> block comprises one row of a table, inside which the <th> and <td> elements create header and data cells, respectively, within the row.") element. Note that this directly contradicts the above normative requirement from HTML5.

(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot)

**Comment by jasmussen** [comment]
That sounds very promising indeed! And it suggests this could be a fruitful path forward. 👍👍

**Comment by talldan** [comment]
I've removed the borders for the header/footer rows for now.

**Review by jasmussen — COMMENTED** [review]
This is what I see now:

table

Honestly, I think given the semantics of the footer and header, this is a pretty elegant and good solution. It solves a problem, and as such, I'm just about ready to approve this.

But we need to think about how to deal with the striped variation:

stripes

Here's a design I think could work:

Screenshot 2019-05-06 at 09 01 17

The difference there:

- No borders around the th elements
- no backgrounds behind the header or the footer

Remove those, and this is good to go!

**Comment by talldan** [comment]
@jasmussen Thanks for all the feedback. That's a nice and simple solution, I like it!

I've made those adjustments. Here's how it looks now with the Gutenberg Starter Theme:
Screen Shot 2019-05-07 at 5 38 28 pm

**Comment by jasmussen** [comment]
I think that looks solid, especially given we mean to provide a baseline that themes can style further.

I checked this branch out intending to test it, but for whatever obscure reason I can no longer see the toggles in the sidebar. I am _convinced_ that it is an error on my part, and ascribing it to me being up at 4:30am today with a screaming baby.

SO, judging purely by the screenshot, 👍 👍 from me. Would still love a sanity check from @kjellr, and a code review, but otherwise, good to go!

**Comment by kjellr** [comment]
> Would still love a sanity check from @kjellr, and a code review, but otherwise, good to go!

Yep, that's working pretty well. I think we're good from a purely visual perspective. 👍 

I do have one minor UX thing to note: If you enter text in a header or footer row and then toggle it off, your text disappears forever. I wonder if we should add a warning/confirmation in this case?

**Comment by talldan** [comment]
> I do have one minor UX thing to note: If you enter text in a header or footer row and then toggle it off, your text disappears forever. I wonder if we should add a warning/confirmation in this case?

Hey @kjellr 👋, thanks for the feedback. That's a good concern. Undo works in this case, but I don't think it's always apparent to a user in the moment that they can use undo.

I'll explore a few options around improving this.

**Comment by jasmussen** [comment]
Honestly I don't think we need to do anything more. We have visible undo and version history for this. Adding additional one off UI will just fragment the experience. Columns block also does this.

I don't want to dismiss the feedback, I had the same thought. But I also feel like this is a place where we have to trust in the undo.

**Comment by talldan** [comment]
I tried a couple of things:

1. Adding a message:
headerwarning

2. Temporarily caching the content in component state and reinstating it if it's toggled back on:
cache

The second option was pretty easy to implement, but I do worry there might be edge cases I haven't thought about in the implementation.

**Comment by jasmussen** [comment]
Of those two, I think number 2 makes the most sense because it feels the most natural. But I also genuinely feel that such an effort should be made _not_ on a per-block basis, but if possible, in a more generic way so that it would apply to all blocks that could do this, even third party blocks. I would go so far as to say that if we can't do that, we shouldn't do it at all. 

Existing desktop apps also have this type of "lossy" behavior, and relies on undo as well.

**Comment by talldan** [comment]
I wonder if it seems destructive because the toggle feels like a show/hide action, instead of the add/remove action that's actually happening.

I'll hold off pushing a solution, if there are some strong opinions that the action shouldn't be destructive I can look at pushing a commit with some caching of content.

**Comment by jasmussen** [comment]
It's the same thing with the columns block. Create 3 columns, write something in column 3, resize in the sidebar to be 2 columns, and column 3 is lost. But it's so trivial to step back with the undo/redo buttons which are even surfaced visibly, that I honestly don't think it's a problem. It's the same in Keynote — if you use a template that has photo, title, body, fill those three out, and swap this to be a template that features only title and body, the photo is lost and does not come back when you swap back to the previous template. You just have to undo. It feels completely natural in practice.

**Comment by youknowriad** [comment]
Another possibility could be a confirmation message if the content is not empty when you untoggle

**Comment by jasmussen** [comment]
It feels like this is one of the places where we either trust our undo, or don't. If we trust it, we could also show a transient snackbar notice that you can undo: https://github.com/WordPress/gutenberg/issues/13905#issuecomment-465039365

**Comment by youknowriad** [comment]
@jasmussen I don't disagree, just wanted to share another possibility :)

**Comment by jasmussen** [comment]
Oh I didn't want to come off as dismissive, I apologise if I did! Your suggestion reminded me of the snackbar notice which seems a perfect place to show little contextual tips like this!

**Review by youknowriad — APPROVED** [review]
Code wise, this looks good. Thanks for the improvement @talldan 
An e2e test could be good addition :)

**Comment by talldan** [comment]
Thanks everyone for the help! E2E tests have been added, will merge once everything passes.

**Comment by patrikhuber** [comment]
Hi, awesome to see this! When will this make it into official WordPress?

**Comment by patrikhuber** [comment]
This comment here https://github.com/WordPress/gutenberg/issues/1470#issuecomment-475278393 mentions

> Also table headers + footers can be made position: sticky; which is also awesome for long tables.

I was wondering whether this could be added?

**Comment by talldan** [comment]
@patrikhuber apologies for the lack of response! I'll respond now though I realise it's a month later 😊 

> Hi, awesome to see this! When will this make it into official WordPress?

You might have already spotted it, but it should be in available in WP5.3.

> I was wondering whether this could be added?

If there's no open issue on github for this, the best thing to do would be to create one. Let me know if you're happy to do that.

If you're after this functionality in the meantime, I think it should be possible using a custom class name for the table block and adding an associated css rule in the customizer's custom css panel.

**Comment by UnionDesign** [comment]
Nice. Enabling a <thead> section is great. But ideally a user could select any cell and set it as a <th> cell. Sometimes your <th> cells are vertical. Maybe that's plugin territory / too complex.

**Comment by patrikhuber** [comment]
@talldan Thanks for the reply!
I just tried it out in WP5.4, the Table block is indeed slowly getting useful in Gutenberg.

>> If there's no open issue on github for this, the best thing to do would be to create one. Let me know if you're happy to do that.

Well as you mention, it's quite easy to add via a line of custom CSS, I'm not too big on it, it would be more of a "nice to have" in the GUI. If you or @strarsis (who raised this originally in https://github.com/WordPress/gutenberg/issues/1470#issuecomment-475278393) feel that it's important enough then by all means open an issue for it and I'll give my upvote!

**Pull request merged**
