### PR TITLE
InputControl: Remove floating label variant

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screenshot of the InputControl component in Storybook

This update **removes** the floating label variant for the `InputControl` component.

The reason for this is because the previous implementation relied on a HTML setup that was invalid and impeded a11y. The effect was achieved by leveraging `fieldset` and `legend` to achieve the "cutout" effect for the floating label. Semantically, this isn't ideal for an individual `input` field.

We took at other solutions with more appropriate HTML markup (e.g. Google/GMail). There was a tiny implementation detail that prevent us from moving forward with those solutions. Notably, the "cutout" effect was achieved by having a background defined (hard-coded) and set on the floating label. On predictable backgrounds (e.g. white), this is fine as the text label background blends with the application background (white on white). This makes it more complic
ated to synchronize backgrounds if/when the `InputControl` may be used on backgrounds that isn't white and/or if the input background (`Backdrop`) changes colours (e.g. in disabled state, or autofill/autocomplete).

Since we currently aren't using floating labels in Gutenberg, it's probably simpler to remove for now. If we need this feature, we can come back to it in the future.

For context, the floating labels were originally developed as part of `BoxControl`. The cluster of inputs within `BoxControl` evolved a lot during the design process. The result (which was merged) dropped the floating label featu
re.

The issue regarding HTML structure and a11y was originally raised by @afercia here:
https://github.com/WordPress/gutenberg/pull/22329#issuecomment-691481613

Below is a screenshot of the new rendered HTML markup:

Screenshot of rendered HTML markup

(It's hard to read I know 😂 )

## How has this been tested?

Tested in local Storybook + Gutenberg

* Run `npm run dev`
* Add a Cover block
* Examine the height control in the sidebar (this one is powered by `InputControl`)

### Focus issue

Noted by @afercia here (https://github.com/WordPress/gutenberg/pull/22329#issuecomment-692155667), clicking the label does not focus the `input`. This has been resolved. This was previously broken due to `pointer-event` interception.

### Toned down border styles

The border styles have been adjusted to match the other input/select controls (using the `gray700` from `base-styles`).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by afercia — COMMENTED** [review]
From an accessibility perspective, this solves the problem of some `<label>` elements not being clickable any longer (too many `pointer-events: none;`). 👍  Will leave more in-depth code review to someone more skilled than me.

**Review by youknowriad — APPROVED** [review]
Nice to see al the "red".

I think we'd need "inline labels" at some point in all controls (BaseControl maybe) (not sure that's what floating labels are about)

**Comment by ItsJonQ** [comment]
> I think we'd need "inline labels" at some point in all controls (BaseControl maybe) (not sure that's what floating labels are about)

@youknowriad Haii! The floating labels were to achieve this UI:

92995535-c4e15f00-f504-11ea-9f01-88f272818128

I'm not too sure what inline labels are 😊 . I googled, but I see varying results.

Thanks! <3

**Comment by youknowriad** [comment]
> I'm not too sure what inline labels are 😊 .

i was just thinking labels on the left of inputs like we do for "Parent page" or "Post Author".

**Comment by ItsJonQ** [comment]
@youknowriad Gotcha :)

Consistent `Controls * Labels * Layout` has been one of the main focuses for G2. It was one of the drivers for me pursuing G2 to begin with 😂 .

I've come up with some solutions to handle simple use-cases. I'm not working on figuring out how these UIs can scale to the variety of different control types (especially if they need to be combined):

https://github.com/ItsJonQ/g2/issues/43

**Comment by ItsJonQ** [comment]
Thanks for the review @youknowriad + @afercia ! I'll merge this up :)

**Pull request merged**
