### PR TITLE
URL Package: Refactor normalizePath function to use URLSearchParams interface

### LINKED ISSUE #36046: Refactor `normalizePath` function to use `URLSearchParams.sort` to sort the request parameters
## What problem does this address?
We have `normalizePath` function in the `wordpress/url` package.
We could refactor it to reduce its size.

## What is your proposed solution?
We could use `URLSearchParams.sort` function to sort the request parameters instead of implementing our custom solution.
Please check https://github.com/WordPress/gutenberg/pull/35992#discussion_r738013100 to see the proposed solution.
All props go to @kevin940726.
Make sure that the unit tests don't fail and it works the same way as the old implementation.

### PR DESCRIPTION
**Pull request by amustaque97**
Fixes: #36046

## Description

Refactor `normalizePath` function to use `URLSearchParams.sort` instead of custom sort code.
https://github.com/WordPress/gutenberg/blob/trunk/packages/url/src/normalize-path.js#L18-L33

## How has this been tested?

Not sure how to test it from the wordpress. Since it is a janitorial changes I ran test cases and they are passing fine.

## Screenshots 
Screenshot 2021-11-02 at 9 53 45 PM

## Types of changes

Janitorial / Code Improvement
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

cc @anton-vlasenko @kevin940726

### CODE REVIEW

**Review by kevin940726 — APPROVED** [review]
LGTM 👍

I think this worth an entry in the CHANGELOG file. We can just edit the existing one since I don't think it has been released yet.

**Comment by amustaque97** [comment]
@kevin940726, native mobile test case is failing. It might be happening because `URLSearchParams` is not supported natively. We might need to add pollyfill. I was checking this https://www.npmjs.com/package/react-native-url-polyfill

Could you please take a look at this and then we can discuss further on how to go about it?

Thanks

**Comment by kevin940726** [comment]
Huh, right! I totally forgot about react native. With that in mind, I think we can close this PR for now, especially when it doesn't add any other benefits besides bundle size improvements, which could be even bigger if we decided to ship a polyfill. We can come back to this after react native natively supports `URLSearchParams`. WDYT?

**Comment by amustaque97** [comment]
> Huh, right! I totally forgot about react native. With that in mind, I think we can close this PR for now, especially when it doesn't add any other benefits besides bundle size improvements, which could be even bigger if we decided to ship a polyfill. We can come back to this after react native natively supports `URLSearchParams`. WDYT?

Completely agree with you 😄 we already have things working in place. Let's close this PR.

**Comment by anton-vlasenko** [comment]
I'm closing the PR because of https://github.com/WordPress/gutenberg/pull/36151#issuecomment-960741852

**Pull request closed without merging**
