### PR TITLE
Remove redundant bg color within button appender

### PR DESCRIPTION
**Pull request by lukewalczak**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by pinarol** [comment]
I know this is a simple PR but we still need a gutenberg-mobile companion PR to update develop branch.

**Comment by lukewalczak** [comment]
https://github.com/wordpress-mobile/gutenberg-mobile/pull/1348

**Review by pinarol — APPROVED** [review]
LGTM! 🎉

**Comment by etoledom** [comment]
Thank you both! 🙏

**Pull request merged**
