### PR TITLE
RichText: fix wordwise selection on Windows

### LINKED ISSUE #14170: Windows: Ctrl + right / left arrows doesn't navigate by word any longer
Noticed while re-resting https://github.com/WordPress/gutenberg/issues/6002#issuecomment-468345267

On Windows, standard keyboard shortcuts to move the caret "by word" in a textarea are `Ctrl + right arrow` and `Ctrl + left arrow`. This used to work within the blocks rich text area but seems it's now broken.

- test with any browser on Windows
- go in a standard textarea, for example in WordPress > Settings > Discussion
- enter some text in one of the textareas there
- verify `Ctrl + right arrow` and `Ctrl + left arrow` move the caret "by word"

Then go in the Block Editor, create a new post, add same text in a paragraph:
- `Ctrl + right arrow` and `Ctrl + left arrow` move the caret **by character**
- expected: by word

Note: `Shift + Ctrl + right arrow` and `Shift + Ctrl + left arrow` still work correctly and select text **by word**

In any editor, standard operations like navigating / selecting text should always work with the native shortcuts. Not to mention the breakage of standard keyboard navigation is even more serious for assistive technologies users.

This appears to have changed at some time, sorry I'm not able to trace down exactly when.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

@afercia I think this should fix #14170, but I can't be sure as I can't test on Windows.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by afercia** [comment]
Fixed a typo. Tested on Windows, works thank you!

I'd suggest to document with some inline comment all those conditions. At first glance it's not clear why they're there especially for who's not so familiar with this specific component.

**Comment by afercia** [comment]
Some documentation for `handleHorizontalNavigation()` would help as well 🙂

**Comment by iseulde** [comment]
@afercia Added documentation :)

**Review by afercia — APPROVED** [review]
Thanks ❤️ LGTM

The added docs are good start to improve the documentation for the whole component. Still hart to understand at first sight for someone new to this code 🙂 For example, I had to dump `selectedFormat` to understand what actually is.

**Pull request merged**
