### PR TITLE
Add multi-select buffer

### PR DESCRIPTION
**Pull request by ellatrix**
Forces you to move at least 25px inside another block to trigger multi selection.
Should also fix the float issue.

Adding now since I think most other multi select bugs are gone.

### CODE REVIEW

**Comment by notnownikki** [comment]
I like this, and I'm wondering if it would be good to check that the pointer is into the boundary of the block on the x axis as well.

This shows two behaviours of selecting, the first is a swipe across to select the text in a paragraph, and the second is a drag upwards to select multiple blocks.

two selects

I feel like there's a difference between the two, as I often find myself doing the first one when I want to select a paragraph, and the second when I want to select multiple blocks. What do you think?

**Comment by iseulde** [comment]
@notnownikki Thanks for the feedback! Let's do it!

**Comment by iseulde** [comment]
@notnownikki Actually, I'm not sure what the difference should be. A buffer horizontally wouldn't help anything at all as you'd only select vertically. If you move horizontally, you'd still have the vertical buffer and you'd have to move 25px in the horizontal zone of the sibling block.

Is that screenshot taken with this branch? It doesn't look like the buffer is active in any direction.

**Comment by notnownikki** [comment]
@iseulde Yeah, that screenshot is on the branch, I tested the buffer works by setting it to a huge amount that would never get triggered, and it worked as expected.

The x-axis thing was a separate idea, really, I just wondered what you thought of it, seen as we're looking at the code that triggers multi select :) I just thought that it made sense to only do multi select if the pointer goes over the blocks, as in the first example select, the pointer doesn't appear to go over them. Am I making sense there?

**Comment by iseulde** [comment]
@notnownikki Yep, you do! :) I get it now. That's actually a feature, so select continues even if you move out of the block list (and doesn't stick where you left the area). The idea is to make it work similarly to normal select. Select some text, and you'll see the same behaviour. :)

**Comment by notnownikki** [comment]
@iseulde  Aha, I see! Then, perhaps what I'm asking is if we can _start_ multiselect only when the pointer goes over the next block? From then on, the pointer could move in and out of the blocklist as much as the user likes, and maintain the current behaviour? (Perhaps we should discuss this out of this PR, as I'd be happy to put together a branch showing what I mean, and this PR looks good to go to me!)

**Comment by jasmussen** [comment]
Really really really nice, thank you for working on this! 

I think we should start with a pretty tall number as the buffer zone. It looks like we can always decrease this number, and as such it's one that we are likely going to be tweaking many times. 

And so it feels to me like we should start with the _largest possible buffer we can imagine_, that way when we adjust there's only one direction to go (lowering). Multi select is my favorite feature right now, but it also activates too often. How about we start at 60? That way if there are two single paragraph blocks next to each other, you can still select them both. Sort of like this:

screen-shot-2017-06-24-at-09 29 02

**Comment by iseulde** [comment]
@jasmussen Hm, wouldn't that be a bit too much? Some blocks are less than 60px, so you would not even be able to select those. At first I thought to set the buffer to the block paddings (14px), so as soon as you enter the actual content, it would trigger, rather than just entering the box. Then I even added  11px more. I think, if you drag the pointer even further away, the chance is pretty high that you intended to select further.

I guess you could argue that you can select the block by selecting further and then going back a bit. But you can also easily deselect by going back a bit if the multi selection is unwanted, just like normal text selection.

Either way, I have no strong opinion, I'm okay with adjusting.

screenshot 2017-06-24 18 04 44

**Comment by jasmussen** [comment]
Depends on how it feels of course, I haven't yet had time to play with the branch and adjust the values. I'm also okay with starting with a smaller value. The key being that it seems we should try and start with the highest value we can, and then adjust downwards as we use the feature and decide it isn't sensitive enough.

**Comment by iseulde** [comment]
@jasmussen Is this better?

**Comment by jasmussen** [comment]
I think this is good! 👍  on the experience.

**Comment by notnownikki** [comment]
Just rebased this on master and tested the issue selecting a floated pullquote - works nicely now.

:+1:

**Comment by iseulde** [comment]
Still need an approval. :)

**Comment by jasmussen** [comment]
I see one from Nicola! Ship it!

**Review by notnownikki — APPROVED** [review]

**Pull request merged**
