### PR TITLE
[Components]: Rename SegmentedControl to ToggleGroupControl

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Follow up of: https://github.com/WordPress/gutenberg/pull/34017#issuecomment-899389795

In this PR `SegmentedControl` is renamed to `ToggleGroupControl`. The internal `RadioGroup` used is from `Reakit` so it needs more investigation if it can be removed with the current `RadioGroup` from `wordpress/components` - this is subject to change name as well to `ToggleGroup` and not be exposed in a follow up PR probably..

## Testing instructions
1. Everything should work as before in storybook
2. The sole usage for now is in `PostFeaturedImage` when a `height` value is set. So this should work as expected

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I think this renaming makes sense. 

@mtias mentioned his doubts about the `Control` suffix. While it's a legitimate thing, I wonder if we should stick to it for consistency reasons with components we can't rename.

**Comment by ntsekouras** [comment]
>@mtias mentioned his doubts about the Control suffix. While it's a legitimate thing, I wonder if we should stick to it for consistency reasons with components we can't rename.

After checking the other component names here: https://developer.wordpress.org/block-editor/reference-guides/components/, I thought it was better to keep the suffix for consistency, so I agree with Riad. I have no strong opinions though, and can be changed if needed..

**Comment by mtias** [comment]
If we'd like to be moving to a different place regarding naming I don't think current consistency should be the deciding factor. It'd be best to avoid a subsequent rename. Curious what @diegohaz thinks as it's an important part of making the component set approachable.

**Comment by diegohaz** [comment]
Regarding the `Control` suffix, I'd vote for consistency. If we're already using this suffix in other components (and it would be harder to change them), let's stick with it.

Regarding `ToggleGroup`, I wonder if it would conflict with the [toggle button semantics](https://www.w3.org/TR/wai-aria-practices-1.2/#button).

I see 2 patterns with which this component design could be implemented: radio group or tab list. We're currently using the radio group here, which makes more sense for the use cases we have. But I can see [how this component design could be used to control the visibility of sections](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/), in which case the tab list would make more sense.

But I don't think the toggle button pattern applies here. For example, in the image below we have a group of toggle buttons (format) and a radio group (alignment).

Screenshot of a toolbar with a toggle button group and a radio group

Screenshot from https://www.w3.org/TR/wai-aria-practices-1.2/examples/toolbar/toolbar.html

The main difference is that the toggle button group may have more than one selected (technically, `pressed`) item, whereas the radio group may only have one at a time.

The markup is also quite different:
```html
<!-- toggle button group (simplified) -->
<div>
  <button type="button" aria-pressed="true"></button>
  <button type="button" aria-pressed="true"></button>
  <button type="button" aria-pressed="false"></button>
</div>

<!-- radio group (simplified) -->
<div role="radiogroup">
  <div role="radio" aria-checked="false" tabindex="-1"></div>
  <div role="radio" aria-checked="true" tabindex="0"></div>
  <div role="radio" aria-checked="false" tabindex="-1"></div>
</div>
```

On the other hand, I guess "toggle group" doesn't necessarily mean "a group of toggle buttons", and I can find a lot of examples on the internet where "toggle group" is just another name for "radio group".

I also understand that, since we're not only dealing with semantics, but also with layout, `RadioGroup` may not be the most appropriate name (we may still need a `RadioGroup` component with the standard bullet layout, after all).

So, I'm not opposed to `ToggleGroupControl` if we agree it doesn't conflict with the toggle button pattern. But I also think `SegmentedControl` is a good name since the component looks really similar to the iOS component with the same name.

**Pull request merged**
