### PR TITLE
Block Templates: Fix PHP notices on WP 5.8

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
When the plugin runs on WP 5.8.x, it will use the `WP_Block_Template` class from the core, which doesn't have new properties. To avoid PHP notices, we've to use dynamic properties when building templates from the file.

Note: The issue doesn't affect WP 5.9.

## How has this been tested?
1. Clone this branch.
2. Open Site Editor with `WP_DEBUG_LOG` enabled.
3. The `debug.log` shouldn't contain notices.

## Log
```log
PHP Notice:  Undefined property: WP_Block_Template::$origin in ~/Projects/gutenberg/wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-gutenberg-rest-templates-controller.php on line 467
PHP Notice:  Undefined property: WP_Block_Template::$author in ~/Projects/gutenberg/wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-gutenberg-rest-templates-controller.php on line 477
```

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by cbravobernal** [comment]
Hi there!

I'm still having those notices when being on site editor.

Attached a Loom Video:
https://www.loom.com/share/8b7dd24c887e4dd1bf57089112a9970b

**Comment by Mamaduka** [comment]
Thanks for testing, @c4rl0sbr4v0.

Are you using wp-env with WP 5.8.x?

I've to call it a day, but will check back on this issue tomorrow morning :)

**Comment by cbravobernal** [comment]
I was using `wp-env` with a development version (5.9-alpha-52268).

Using 5.8 is working fine!

**Review by cbravobernal — APPROVED** [review]

**Comment by Mamaduka** [comment]
Makes sense :) This should fix the notice for 5.9 - https://github.com/WordPress/wordpress-develop/pull/1967.

**Pull request merged**
