### PR TITLE
Add 'reusable' keyword to Pattern blocks

### LINKED ISSUE #52194: Renaming Reusable Blocks Should Still Be Discoverable
### Description

As a user familiar with Reusable Blocks, I expect to find them as a search result when inserting a block even if that feature has moved. Assume I do not know that the feature as moved. 

How do I navigate to see all reuseable blocks I previously created? How do I get to the manage reusable blocks counterpart? 

### Step-by-step reproduction instructions

In 6.2.2:

- Create a Reusable Block 
- Insert it from the Block Inserter searching for "reusable" and/or the reusable block tab
- Insert it using the / command in a paragraph block searching for "reusable"

In 6.3b2 
Attempt the same

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/5519705/d3c911bd-5d7f-4bd0-8f6f-1a181e39ea43

https://github.com/WordPress/gutenberg/assets/5519705/2fcd3c40-94aa-4b09-a812-084445ada912

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Fixes https://github.com/WordPress/gutenberg/issues/52194.

## Why?
Reusable blocks were renamed to Pattern blocks. We can help users adjust to this change by having pattern blocks appear when one searches the inserter for "reusable".

## How?
Adds "reusable" to the `keywords` for the Pattern block and to the virtual block definitions built by `getInserterItems` for each reusable block.

## Testing Instructions
1. Go to the post editor.
2. Add some blocks.
3. Select some blocks and press Options in the block toolbar.
4. Select _Create pattern/reusable block_.
5. Open the inserter.
6. Search "reusable".
7. Your newly created pattern should appear.

### CODE REVIEW

**Review by glendaviesnz — APPROVED** [review]
Tested well for me. It would be great if both synced and unsynced patterns were listed, but this is a bigger job as inserting an unsynced pattern is a different process from a synced one, so definitely a follow-up

**Comment by glendaviesnz** [comment]
Looks like `packages/block-editor/src/store/test/selectors.js` needs to be updated

**Comment by noisysocks** [comment]
> Tested well for me. It would be great if both synced and unsynced patterns were listed, but this is a bigger job as inserting an unsynced pattern is a different process from a synced one, so definitely a follow-up

Might leave this for you 😅 not very familiar with the patterns work y'all have been doing.

> Looks like `packages/block-editor/src/store/test/selectors.js` needs to be updated

Updated 👍

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-batch-pre-RC1 branch to get it included in the next release: 605f510c49

**Pull request merged**
