### PR TITLE
Autocomplete: Announce results to screen readers when first becoming visible

### LINKED ISSUE #5592: "Slash menu": improve instructions and feedback
Follow up to https://github.com/WordPress/gutenberg/issues/5591 to address the second part of the feedback we're getting from assistive technologies users. For full details, please refer to #5591.

Screen reader users are able to use the slash menu. However, only 10 block types are displayed by default and there are no instructions that typing actually filters the list and makes new results appear in the menu.

In the test session reported on #5591 the user had a simple task: add a table with 2 columns, 2 rows and add some data in the cells

The feedback was:
> When I hit slash, table wasn't included in the menu.

I'm wondering if this applies also to sighted users: they can certainly try to type something and they will see the menu changes, but maybe discoverability is not that great.

Unfortunately, the audible message used for screen reader users is always the same for all the auto-completers in Gutenberg. It's always:
`nn results found, use up and down arrow keys to navigate.`

screenshot 77

In this specific case, screen reader users need some more context and a meaningful message instructing them to type to refine the search results.

Once they start typing, I think the feedback is good enough. The only issue is the initial message and instructions, clearly not sufficient to understand how this feature works.

screenshot 78

Why the initial message "10 results found, use up and down arrow keys to navigate." is confusing?

I guess because users have typed just a slash `/`. Actually, they haven't typed any search term but they get a message that says `10 results found`. Instead, the message should briefly reflect what actually happens in the UI:
- 10 initial choices are displayed
- typing something will display other search redsults

To communicate this, there's the need of a different message.

I'd propose to consider a way to make each autocompleter have its own message. One size doesn't fit all. These auto-completers work  in different ways and they need to be communicated with different, meaningful messages.

Optionally, it would be great to have 2 different messages based on the user workflow:
- a message when the menu opens for the first time
- a different message for the search results

### PR DESCRIPTION
**Pull request by alexstine**
## What?

Changes the `speak()` function to fire when autocomplete items change. This allows screen reader users to know how many results exist initially before filtering.

## Why?

Fixes #5592

## How?

Modify the code and add an E2E test.

## Testing Instructions

1. Open a post or page.
2. Add a new block.
3. Type "/".
4. Notice how the `aria-live="assertive"` region at the bottom of the page announces the initial 9 results. This uses debounce, wait a few seconds.
5. Enter another keyword and ensure the results are updated.
6. Pressing escape should close suggestions list.

### Testing Instructions for Keyboard

Same.

### CODE REVIEW

**Comment by joedolson** [comment]
This looks technically fine, although I don't hear any significant difference between how this works now and how it worked before. However, I don't think this does anything to solve the problem cited in #5592. The change needed there is to 

1) Differentiate between initial state and search results (e.g. "9 most recent blocks shown. Use arrow keys..." vs. "9 results found"
2) Provide instructions in initial state. "9 most recent blocks shown. Start typing to search blocks. Use arrow keys..."

**Comment by alexstine** [comment]
@joedolson This field has a label already? Type slash to insert a block or start typing to create a paragraph block.

**Comment by alexstine** [comment]
Due to the way this component is designed, trying to figure out these state announcements will not be easy. The change in place now will at least tell users how many blocks are in view after typing "/". I think it is a small improvement at least.

**Comment by joedolson** [comment]
This is about the state when you first type the slash. The results brought up are not search results, and there's no information about what they are or what to do if the block you want isn't in that collection.

Seems like you'd know it was initial state just be catching the keycode of the slash character. Is there a reason that wouldn't work?

**Comment by alexstine** [comment]
It's mostly based on the rules that components package must be generic. I will try to find a way to communicate initial results as all we're given is a large object. Then the object gets filtered based on search queries. I know we're given initial results, I just need to figure out how to split that into something I can build conditionals around.

**Comment by alexstine** [comment]
@joedolson Does this latest commit get us closer? Now I am explaining to users that these are initial results that can be filtered.

**Comment by joedolson** [comment]
Definitely moving in the right direction. My only quibble here is that the text implies that you're filtering the initial set (e.g, you've been given a set that contains all results, and you're filtering those results), but you've actually only been given a subset. Filtering allows you to filter the set of all blocks, not just the initial set.

That might be a subtlety that isn't really crucial, however. It's definitely better than it was before!

**Comment by alexstine** [comment]
@joedolson I tried again. Maybe now it is clear?

**Review by chad1008 — COMMENTED** [review]
This looks good and works well for me, I can see how it's an improvement. One small nit that we may not want/be able to address now is that the "n initial results" phrasing in place with this change implies that the initial list is _always_ a subset of the whole list, which it may not be. For example, on a small site with only three users, typing `@` will pull up all three users, but the screen reader will refer to them as 'three initial results', and instruct the user to type to filter all results... implying there are more results to find when there actually aren't.

I recognize this is kind of the opposite concern from what @joedolson raised, and we may need to prioritize one over the other, in which case I think the current approach of always guiding the user towards typing to filter makes the most sense 👍

**Comment by joedolson** [comment]
No, that's totally in agreement with my comments, if I understand you correctly. The initial state shouldn't use the word "results", because it's not the result of a query.

**Comment by chad1008** [comment]
I was actually keying in more on the word "initial", because with a small dataset, the items displayed aren't "initial" (which implies there are more that aren't currently shown). If a given completer returns a short enough list (like the three-user site example above) the completer will open with the _full_ list. I don't think it's a huge problem, and the cases where it actually causes any confusion will be few and far between.

**Comment by joedolson** [comment]
I'd argue that they're still initial, in that they are not changed by user input. You can still filter to fewer than the initial results, even if there are no additional results to be found.

**Review by joedolson — APPROVED** [review]
This looks good to me; I think the e2e failure we're seeing is an unrelated timeout. But somebody who knows those better could disagree. The improvement for screen readers in using the autocomplete block selector is significant.

**Pull request merged**
