### PR TITLE
Button Block: Apply Stretch Styles Correctly

### LINKED ISSUE #52533: Buttons have mismatched heights
### Description

I built a page with 4 inline buttons on top. The text on two of them drops down to a second line so the buttons are of different heights. There used to be the option to adjust that but I don't see it any longer, or potentially it's been removed. It could be just me but I created a vanilla wordpress site with just gutenberg and still had the same issue. I can't imagine I'm the only one who thinks buttons all with matching heights is visually appealing. Any help would be apprieciated.

### Step-by-step reproduction instructions

Create New Page > Create 4 buttons that display inline > Now how do you make them uniform?

### Screenshots, screen recording, code snippet

Screen Shot 2023-07-11 at 3 35 10 PM

### Environment info

Wordpress Version 6.2.2
Twenty Twenty Three Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #52533

## What?

This PR ensures that buttons are stretched correctly when "Stretch to fill" or "Stretch items" are applied.

## Why?

When "Stretch to fill" or "Stretch items" is applied to the Buttons block, its child element (`.wp-block-button`) is stretched by the `align-items: stretch` style. However, the actual button is the `.wp-block-button__link` element inside it, and since this has the `display: inline-block` style, there is no visible change.

As I've researched in [this comment](https://github.com/WordPress/gutenberg/issues/52533#issuecomment-2029688551), it appears that the stretch option for the Button block never worked when it was first implemented.

## How?

Make the actual button height/width 100%. This will make the actual button the same size as the flex layout child.

However, simply changing the height or width to 100% will not center the content inside when buttons of different heights are lined up:

image

I first thought of applying `display: inline-flex` instead of `inline-block` to center the content, but if it contains `br` tags or inline formatting, it will cause an unintended layout:

| Actual | Expected |
|--------|--------|
| image | image | 

So I left it as `inline-block` and applied `align-content:center`. This CSS is now defined as available for block containers other than flex/grid layouts, and should be supported in major browsers ([W3C link](https://www.w3.org/TR/css-align-3/#align-justify-content)).

## Testing Instructions

- Insert multiple buttons.
- Vary the length of the button content and add some inline formatting to the content.
- Horizontal layout: If you select "Stretch to fill", the button height should expand to the container height and the text inside should be centered.
- Vertical layout: If you select "Stretch items", the button width should expand to the container width.

### Horizontal Layout

| Before | After |
|--------|--------|
| image| image| 

### Vertical Layout

| Before | After |
|--------|--------|
| image | image |

### CODE REVIEW

**Comment by jasmussen** [comment]
This seems good to me, thanks for the careful research and attention. In case @tellthemachines has a chance to look, I'd defer to her! Otherwise 👍 👍

**Review by tellthemachines — APPROVED** [review]
Just gave this a test run and it LGTM! Tried Buttons block both standalone and inside Navigation block and nothing seems broken, plus stretching now works as expected in both vertical and horizontal orientation.

**Comment by t-hamano** [comment]
Thanks for the review!

**Comment by iandunn** [comment]
Hi all, unfortunately this broke back-compat with existing content, for example:

| WordPress 6.7.2 | WordPress 6.8 |
|-----------------|---------------|
| Screenshot 2025-06-02 at 3 27 53 PM | Screenshot 2025-06-02 at 3 28 07 PM     |
| Screenshot 2025-06-03 at 9 35 19 AM | Screenshot 2025-06-03 at 9 35 28 AM |

My workaround was to add this to my CSS:

```css
.wp-block-button__link {
	height: auto;
	width: auto;
}
```

IMO it should be considered a bug, though, and reverted. Maybe a more targeted style would provide a solution to https://github.com/WordPress/gutenberg/issues/52533 ?

**Comment by t-hamano** [comment]
@iandunn The problem has been fixed in #70054. The PR is planned to be part of a minor WordPress release.

**Comment by patrickwc** [comment]
I also had an issue in my theme, buttons are now always set to `height: 100%` which is not very backwards compatible. 

I don't understand why using Stretch to fill creates a custom CSS class name e.g. `.wp-container-core-buttons-is-layout-58176225` with `align-items: stretch;`. If it toggled on an off a standard class like `is-stretch-to-fill` the width and height rules could only be applied to buttons which are set to stretch to fill. As it is this solution is very opinionated CSS and breaks some styling in older layouts.

**Comment by iandunn** [comment]
Thanks @t-hamano !

**Pull request merged**
