### PR TITLE
RangeControl: animate thumb and track only when using marks

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Related to https://github.com/WordPress/gutenberg/pull/67611/files#r1880356463

Tweaks the animation applied to the thumb and track elements of `RangeControl`, so that the animations only apply when the component is showing "marks"

## Why?

The animation can introduce a subtle delay that can make the experience of dragging the thumb feel slow and unresponsive.

This PR tries to achieve a good compromise by keeping the animation enabled when the component shows marks, since the experience of dragging the thumb is "stepped" and the animation doesn't really introduce a delay.

## How?

CSS changes

## Testing Instructions

- Drag the thumb on a `RangeControl` that doesn't show marks — the thumb and the slider should update instantly following the cursor (ie. no animation)
- Add `marks` to the `RangeControl` — the thumb and track should animate, like they already do on `trunk`

The difference is subtle. Artificially slowing down the transition duration could help debug the changes.

### CODE REVIEW

**Review by jameskoster — APPROVED** [review]
Seems okay to me :)

**Review by youknowriad — APPROVED** [review]
Thanks for the follow-up :)

**Review by mirka — APPROVED** [review]
🚀

**Review by tyxla — APPROVED** [review]
Tests well for me 👍 Thanks!

**Comment by ciampo** [comment]
Thank you all for all the reviews! I'm not going to add a CHANGELOG entry since this PR basically stacks with #67611

**Pull request merged**
