### PR TITLE
Global styles revisions: refactor sticky pagination footer to use CSS

### PR DESCRIPTION
**Pull request by ramonjd**
## What?
A follow up to:

- https://github.com/WordPress/gutenberg/pull/56799

Let's fix the pagination to the bottom of the sidebar panel using CSS.

We can now delete the Slot Container, which is not used elsewhere.

> [!WARNING]
> Because the footer now sits within a scrollable container, the width of the pagination will be affected by the browser's scrollbar. See the screencasts below. So, one option is to forget about this PR.

## Why?
CSS.

## How?
Making the footer sticky. 

And relying on the convenient fact that `.edit-site-global-styles-sidebar__navigator-screen` has a `display: flex` rule.

## Testing Instructions
Open up the site editor, ensuring you have plenty of Global styles revisions (more than 10 to enable pagination).

Check that the pagination:

1. Works
2. Sticks to the bottom.

### Trunk
https://github.com/WordPress/gutenberg/assets/6458278/8be2af80-f604-4952-86df-96f74fb90a5e

### This PR

https://github.com/WordPress/gutenberg/assets/6458278/b69dcb0d-2443-4d24-bbaa-32c27448a106

### CODE REVIEW

**Comment by andrewserong** [comment]
Just double-checking while testing, but it looks like the screengrabs in the PR description are the wrong way around? (I.e. the screengrab for Trunk is actually the screengrab for this PR?)

**Review by andrewserong — APPROVED** [review]
Tests well for me across Chrome, Safari, FF, and Edge!

> Because the footer now sits within a scrollable container, the width of the pagination will be affected by the browser's scrollbar. See the screencasts below. So, one option is to forget about this PR.

I actually don't mind it. It only really affects the final page of the results, and only in browser windows short enough for a scrollbar to be present, so doesn't _sound_ like a blocker to me. But I'm not a designer!

I think overall, going with a CSS approach keeps things simpler, which seems worthwhile to me in this case. LGTM ✨

**Comment by ramonjd** [comment]
Thanks @andrewserong!

**Comment by ramonjd** [comment]
> Just double-checking while testing, but it looks like the screengrabs in the PR description are the wrong way around? (I.e. the screengrab for Trunk is actually the screengrab for this PR?)

You are right. Good quality control! Fixed.

**Pull request merged**
