### PR TITLE
Consistent default typography controls across blocks

### PR DESCRIPTION
**Pull request by richtabor**
## What?

Adjust the default controls across typography blocks to ensure they are consistent experience across the editor. 

- Heading 
- Post title
- Pullquote
- Query title
- Quote
- Site Title
- Verse

## How?
Adjusting block.json for each. 

## Testing Instructions

1. Open a post or page.
2. Insert the blocks listed above. 
3. See font size as the default control across the board.

## Screenshots or screencast 

| Before  | After |
| ------------- | ------------- |
|CleanShot 2023-10-10 at 09 17 40|CleanShot 2023-10-10 at 09 17 49|

### CODE REVIEW

**Comment by richtabor** [comment]
Pending @WordPress/gutenberg-design review, I'd appreciate help on the tests.

**Comment by jameskoster** [comment]
This makes sense to me, however I'd be a little wary about merging given the logic about which controls to display might also be affected by https://github.com/WordPress/gutenberg/issues/49278. Would this be too confusing?

**Comment by richtabor** [comment]
> This makes sense to me, however I'd be a little wary about merging given the logic about which controls to display might also be affected by https://github.com/WordPress/gutenberg/issues/49278. Would this be too confusing?

I think it helps if we have consistent default views across the board. Then if a default value is applied from Global Styles, then those should be reflected in the UI.

**Comment by jameskoster** [comment]
Yes I suppose this change moves us in the right general direction by displaying fewer controls that have no locally assigned value.

**Review by jameskoster — APPROVED** [review]

**Comment by richtabor** [comment]
@Mamaduka Any chance you could help with the tests here? 🙇‍♂️

**Review by Mamaduka — APPROVED** [review]
E2E tests should be fixed now ✅

**Pull request merged**
