### PR TITLE
Font library: lib-font as npm dependency

### LINKED ISSUE #53653: Font Library: How to add lib-font package (or equivalent).
## What ?
We need to add the [lib-font package](https://github.com/Pomax/lib-font) (or a better equivalent) to read font assets metadata in the Font Library.

## Current situation: 
We are adding the files library files in the codebase, adding minor changes:

See these how we are adding the library files on [Font Library Frontend PR](https://github.com/WordPress/gutenberg/pull/53884):
https://github.com/WordPress/gutenberg/tree/d01a98d03724c90fb08a47a2504608e52c78b800/packages/edit-site/lib

## Context
In Create Block Theme plugin, we use the same library to read the font assets metadata (font name, font weight, font style, etc) without changing the library source code. To avoid compiling errors, we needed to add [custom Webpack config options](https://github.com/WordPress/create-block-theme/blob/trunk/webpack.config.js).

@youknowriad suggested that we should avoid changing the Webpack configuration file for Gutenberg. Because of that, we are using the bundling approach, changing a few things in the library's source code (see the comments in the  [Fonts Library frontend PR](https://github.com/WordPress/gutenberg/tree/34dd73eaa26a461897413f60fea6cb065e6c27ae/packages/edit-site/lib) ).

## More Context
Added a question in the lib-font repo about the Webpack bundling: https://github.com/Pomax/lib-font/issues/135

## Alternatives
It is not a requirement to use [Lib-font](https://github.com/Pomax/lib-font). We can try another alternative.
The pros of this lib:
- It is used on Create Block Theme plugin, and it is working OK
- The most lightweight alternative I found.

The con seems to be this issue.

## Tracking issue
https://github.com/WordPress/gutenberg/issues/52698

### PR DESCRIPTION
**Pull request by vcanales**
This change required applying a change in the webpack config suggested by lib-font's developer, detailed [here](https://github.com/Pomax/lib-font/#how-do-i-use-this-with-webpack).

Closes https://github.com/WordPress/gutenberg/issues/53653

### CODE REVIEW

**Review by matiasbenedetto — COMMENTED** [review]
:wave: Thanks for digging into this. 

The webpack config added in this PR is the same we are using in [Create Block Theme plugin webpack config.](https://github.com/WordPress/create-block-theme/blob/trunk/webpack.config.js)

In the [original issue description](https://github.com/WordPress/gutenberg/issues/53653) I pointed out that @youknowriad suggested avoiding changing the Gutenberg's webpack config. That was the main reason to open the issue.

I'm not sure about all the outcomes around changing the webapck config, so It would be useful to get a review from Riad.

**Comment by youknowriad** [comment]
It's just a shame that the package requires a special config of your bundler. I can live with that but remember that you'll have to update Core's webpack config as well. Fortunately, it's the edit-site package and not a generic package that is used often by third-party JS devs.

**Comment by vcanales** [comment]
> It's just a shame that the package requires a special config of your bundler. 

I agree, but since we're not getting help with the library from the dev, this and forking it seem like the two only choices if we want to keep it. I wouldn't mind maintaining a fork; I don't know if there's precedent for incorporating this sort of library to the WordPress org as a fork.

**Comment by matiasbenedetto** [comment]
>  I can live with that but remember that you'll have to update Core's webpack config as well.

@youknowriad if you are okay with importing the package like this, at least for this next release, please approve the PR.
We can follow-up later.

**Review by matiasbenedetto — CHANGES_REQUESTED** [review]
@vcanales please, remember that to make the library work as expected apart from adding the lib-font main file, the other 2 files (`inflate` and `unbrotli`) are required to uncompress the font files. In Create Block Theme plugin we are adding them like this:

https://github.com/WordPress/create-block-theme/blob/ac882b43bd8f13cd052a722027d9c55b90593142/admin/manage-fonts/local-fonts-page.php#L8-L9

**Comment by youknowriad** [comment]
👍 Please don't wait for my approval, this LGTM

**Comment by getdave** [comment]
@vcanales Is this PR still relevant? If so are you targeting for WP 6.5?

**Pull request closed without merging**
