### PR TITLE
List Block: fix merging with indented list items

### LINKED ISSUE #17843: List: Merging lists erroneously joins indented items
**Describe the bug**
Assuming two List blocks:

 _List one_

* ABC
  * DEF
  * GHI
  * JKL

_List two_

* MNO

Merging these lists will yield:

* ABC
  * DEFGHIJKL
* MNO

**To reproduce**
1. Start a new post
2. Add two consecutive List blocks, per the example above
3. Place the caret at the start of _MNO_
4. Press <kbd>Backspace</kbd>

Alternatively:

3. Place the caret at the end of _JKL_
4. Press <kbd>Delete</kbd>

**Expected behavior**
The merged list would be:

* ABC
  * DEF
  * GHI
  * JKL
* MNO

/cc @ellatrix

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #17843. The problem is that `create` is missing the `multilineWrapperTags` argument when using it with an (indented) list. This needs to be provided in the attribute definition. Since lists are kind of a strange case, I've added the key as unstable. Ideally, in the future, we use blocks for each list item.

## How has this been tested?
See #17843 and the e2e test case I've added.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ellatrix** [comment]
@mcsf Oops, forgot that there are two `create` calls, for each block. Should be fixed now.

**Comment by ellatrix** [comment]
Introduced in #14640, which I don't think was included in WP 5.2.

**Review by mcsf — APPROVED** [review]
Thanks for the quick fix! Works well for me.

Where do you see `__unstableMultilineWrapperTags` going in the future? Do we need a follow-up issue to revise? I ask only because it's introducing a hidden interface, but as far as the fix goes it looks good to merge.

**Comment by ellatrix** [comment]
@mcsf I see it as something special that is only needed for nested lists and shouldn't be needed for other blocks. In addition, I think we'd like to revise the list block in the future to use nested block and one rich text instance per item.

> Since lists are kind of a strange case, I've added the key as unstable. Ideally, in the future, we use blocks for each list item.

**Comment by ellatrix** [comment]
Thanks for the review!

**Comment by ellatrix** [comment]
To be honest, I wish we had done the same for `multiline`, but it's been around for a long time... It you think it's better to remove the `__unstable` prefix, I'm fine with that.

**Comment by mcsf** [comment]
> To be honest, I wish we had done the same for `multiline`, but it's been around for a long time... It you think it's better to remove the `__unstable` prefix, I'm fine with that.

No, I think it's better to keep the prefix!

**Pull request merged**
