### PR TITLE
Fix undefined setAttributes in code example

### PR DESCRIPTION
**Pull request by dhaaker**

### CODE REVIEW

**Comment by gziolo** [comment]
Can you explain why is it an issue?

I see that `setAttributes` is used through `props` so it shouldn't be necessary:
```js
props.setAttributes( ... );
```

Do I miss something?

**Comment by dhaaker** [comment]
@gziolo Sorry, my mistake. I was working through the examples and in the previous example (03) the setAttribute is not used through `props`.

```javascript
// Example 03
const { attributes: { content }, setAttributes, className } = props;
const onChangeContent = ( newContent ) => {
    setAttributes( { content: newContent } );
};
```
So, by adding only the new lines from the next section, I ended up with:

```javascript
const onChangeContent = ( newContent ) => {
    setAttributes( { content: newContent } );
};
const onChangeAlignment = ( newAlignment ) => {
    props.setAttributes( { alignment: newAlignment === undefined ? 'none' : newAlignment } );
};
```
Thank you for your assistence, very much appreciated!

**Comment by gziolo** [comment]
I'm open to changes if you think that it would be better for consistency. We would have to submit a patch to https://github.com/WordPress/gutenberg-examples/blob/master/04-controls-esnext/src/index.js#L37 as well. We try to keep those two in sync :)

**Comment by dhaaker** [comment]
I will go through the entire Blocks tutorial again to see if improvements are possible. If so, then I'll get back with a more thorough PR.

**Comment by gziolo** [comment]
> I will go through the entire Blocks tutorial again to see if improvements are possible. If so, then I'll get back with a more thorough PR.

Awesome, thank you 💯

**Pull request closed without merging**
