### PR TITLE
i18n: merge similar translation strings

### PR DESCRIPTION
**Pull request by ramiy**
## Description

Merge two similar translation strings.

## Types of changes

Text change

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
Unfortunately, If we merge this change, the description of the calendar starts rendering incorrectly as this strings are escaped:
image


The string that the widget uses is 'A calendar of your site&#8217;s Posts.' so I totally understand the motivation to use the same string.

I guess there are some possible options:
Change the core version to the one we currently use in the block editor? (not sure if this option would work, would love some thougths on this).
Apply some kind of unescape function to the result of the translation and keep this change. (this may have security implications).

cc: @aduth, @swissspidy any thougths on this?

**Comment by aduth** [comment]
If it's trivial to consolidate to the string using the unencoded entity, I think it would simplify things on Gutenberg's end to avoid needing to consider unencoding (both for the potential performance overhead, and in the security implications).

**Comment by jorgefilipecosta** [comment]
I submitted a core patch to try to consolidate the core version to the editor version https://core.trac.wordpress.org/ticket/47485. Let's see where it goes.

**Comment by aduth** [comment]
> I submitted a core patch to try to consolidate the core version to the editor version https://core.trac.wordpress.org/ticket/47485. Let's see where it goes.

It appears this has been committed from core, and the strings are now merged.

https://core.trac.wordpress.org/changeset/45492

Thanks @ramiy, @jorgefilipecosta

**Pull request closed without merging**
