### PR TITLE
Font Library: Avoid running init functions when font library is available in core.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Avoid running init functions from the plugin when the font library is available in core.

## Why?
- Avoid creating repeated endpoints.
If the Gutenberg plugin is installed on WordPress core trunk (6.5-alpha) the font collection endpoints are created twice each, one by core and one by the plugin.  This PR avoids that.

## How?
Checking the WordPress version before running the endpoints creation function.
If the WordPress core version is < 6.5-alpha, the font collection endpoints are not created by the Gutenberg plugin.

## Testing Instructions
1. 
- Install and activate this Gutenberg PR on **WordPress core trunk version**.
- Check that the `/font-collections/` and `/font-collections/<slug>` endpoints are not repeated.
- Check that the font collections load as expected.

2. 
- Install and activate this Gutenberg PR on **WordPress 6.4.3 version**.
- Check that the `/font-collections/` and `/font-collections/<slug>` endpoints are not repeated.
- Check that the font collections load as expected.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
I agree that this is something we could do. It will clarify that any changes to the controller for future versions need to happen on a new `compat/wordpress-6.6` instead. 

But I'd like to note also that most other controllers that were added to Gutenberg were actually being registered twice during that transition period.

**Comment by desrosj** [comment]
👋 Hi @matiasbenedetto! Just a friendly reminder to manually review, update as needed, and include the `Co-authored-by` trailers in the merge commit message. In case it was missed, here's the [announcement post](https://make.wordpress.org/core/2024/02/01/new-commit-message-requirements-in-git-hello-props-bot/) and the [accompanying handbook page with the specific details](https://make.wordpress.org/core/handbook/best-practices/contributor-attribution-props/#github-repositories-merge-commits).

If it was on accident, no big deal! But just trying to make sure everyone is aware as we retrain our brains. 😄

**Comment by matiasbenedetto** [comment]
Hi @desrosj, yep, sorry I did that on several PRs, but I forgot to do that on others; my bad.
I have 2 questions:
1. Is it possible to fix the error on an already merged PR?
2. Is it possible to automate the inclusion of the new Co-authored-by credits automatically on the merge commits messages? that would be very useful.

**Comment by desrosj** [comment]
@matiasbenedetto There's no way to go back and change the commit message without changing the commit SHA and breaking things. But, in the long scheme of a release, that's OK. As long as everyone that contributed has other credits in the release! The overall counts for contributions are not a huge deal and being off by one or two is ok.

The process cannot be 100% automated for a few reasons. But mainly, if it were fully automated we would potentially incentivize behavior that we do not want to see, ie. commenting on lots of issues just to accumulate lots of credits. It also would not give the opportunity for someone to add a contributor who did not directly interact in GitHub. Maybe a designer, or someone that gave important feedback during a Slack conversation.

The goal is to make this as friction-less as possible, but some level of human interaction is necessary. If you have ideas how to further improve the process, please do share them in the https://github.com/WordPress/props-bot-action/ repo. We've already implemented several suggestions in the short week since the tool was merged!

**Comment by matiasbenedetto** [comment]
Thanks for the detailed answer

**Pull request merged**
