### PR TITLE
Enable smooth scrolling iOS with new scroll container

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
This PR enables smooth scrolling on iOS with the introduction of a separate scroll container for the content. See 43b84a59aa0a3514804c33e6f602874204fe40ae. It also adds it for the sidebar. Maybe there's some places I missed.

## How Has This Been Tested?
Use iOS and scroll the main content and side bar.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Review by aduth — COMMENTED** [review]
Tested on iPhone emulator and feels good for editable content area. I notice the sidebar doesn't scroll all the way to the bottom, but this issue is present on master as well.

A couple general questions:

- Should this always be the desired behavior for iOS scrolling? This property is not currently applied elsewhere in the admin (scrolling admin sidebar on mobile)
- In looking into this property, [this article on css-tricks.com](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/) mentions something about having to be explicitly `overflow-y: scroll`. I'm not really sure the reasoning for this, and it seems to work well enough as-is, but figured I'd note it. Maybe an issue with older versions of iOS?
- Would autoprefixer be smart enough if we applied the property as `overflow-scrolling: touch` in case other browsers can make use of this?

**Comment by jasmussen** [comment]
Thank you for this PR! 

Andrew already reviewed excellently so I'll just echo his sentiments, but also provide some answers as I've been using this property in the past.

> Should this always be the desired behavior for iOS scrolling? This property is not currently applied elsewhere in the admin (scrolling admin sidebar on mobile)

Yes. This scroll behavior is default for page scrolling on the `html` element. I don't know why it isn't enabled by default for custom scrollable fields. Seems like since it's the expected behavior in mobile Safari (with the overscroll bounce and momentum etc), this should be a property to _opt out of_ rather than in to. 

There is a conflict when you're using parallax scrolling built using `perspective` and z-depth, where having this property enabled causes that not to work at all. Which makes me slightly nervous about the sticky positioning we'e got going on, so I'm going to try this in the Xcode Simulator in a bit. 

> In looking into this property, this article on css-tricks.com mentions something about having to be explicitly overflow-y: scroll. I'm not really sure the reasoning for this, and it seems to work well enough as-is, but figured I'd note it. Maybe an issue with older versions of iOS?

Pretty sure it should work just with `auto` as well.

> Would autoprefixer be smart enough if we applied the property as overflow-scrolling: touch in case other browsers can make use of this?

Alas, [no](https://github.com/postcss/autoprefixer/issues/337#issuecomment-205718995).

**Comment by jasmussen** [comment]
Here's a screen recording from the simulator:

https://cloudup.com/cPqaiwqqZrC

Based on this, smooth scrolling seems to be working as intended!

Incidentally this recording also reveals that there's a horizontal scrollbar somewhere that we need to track down, almost certainly not as a result of this PR. And that iPhone X notch is going to take some getting used to, huh?

**Comment by iseulde** [comment]
Yeah, no such thing as `overflow-scrolling`...

**Review by mcsf — APPROVED** [review]

**Comment by iseulde** [comment]
I see there's also scrolling in the inserter, but I have no way to test this as the inserter is always off-screen. Merging, we can add it in more places later.

**Pull request merged**
