### PR TITLE
Bump plugin version to 1.5.0

### PR DESCRIPTION
**Pull request by pento**
## Changelog

* Set Gutenberg as the default editor (still allow creating new posts in Classic Editor).
* Add metabox support—this is an initial pass at supporting existing meta-boxes without intervention.
* Display inserter button between blocks.
* Improve block navigation performance.
* Hide core namespace in comment serialization. wp:core/gallery becomes wp:gallery.
* Implement a dropdown for Publish flow.
* Allow multiselect to work on shift-click.
* Insert new block from title on enter.
* Use a dropdown for the block menu (settings, delete, edit as HTML).
* Add expandable panel for post visibility.
* Add expandable panel for post scheduling.
* Implement more inline formatting boundaries.
* Better clearing of block selection.
* Show placeholder hint for slash autocomplete on new text blocks.
* Remove multi-selection header in favor of default block controls (mover and menu).
* Allow blocks to disable HTML edit mode.
* Adjust transition and delay of inserter between blocks.
* Added text color option for button block.
* Hide extended settings if sidebar is closed.
* New embed icons.
* Move the store initialization to a dedicated component.
* Improve scroll position of scrollable elements.
* Drop undefined blocks from recent blocks.
* Update HTML block description.
* Update embed block description.
* Add description for classic block.
* PHPCS-specific improvements.
* Add a default block icon.
* Adjust line height of classic text to match paragraph blocks.
* Adjust filter order in classic block so plugins that extend it can work properly.
* Set textarea value as prop and not children.
* Fix mobile issues with block setting menu.
* Fix undefined colors warning.
* Fix broken upload button on image placeholder.
* Fix post edit URL when saving a post/page/CPT.
* Fix conflict with new TinyMCE version and heading blocks.
* Tweak block sibling element for better target surface.
* Avoid loading Gutenberg assets on non-Gutenberg pages.
* Adjust Jest configuration.
* Document supportAnchor in block API.
* Updated TinyMCE to latest.
* Document block name usage in serialization and add example of serialized block.
* Updated FAQ section.
* Upgrade React and Enzyme dependencies.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Looks legit 👍

**Review by ntwb — CHANGES_REQUESTED** [review]
Also [package-lock.json](https://github.com/WordPress/gutenberg/blob/master/package-lock.json#L3) needs bumping from 1.4 to 1.5

Bumping `package.json` and `package-lock.json` can be done by running `npm --no-git-tag-version version major|minor|patch`, we should probably document this somewhere 🤔

**Comment by gziolo** [comment]
Isn’t it enough to run ‘npm version major’ to get package.json and package-lock.json updated?

**Comment by ntwb** [comment]
I don't believe so @gziolo, from the [docs](https://docs.npmjs.com/cli/version)
> If run in a git repo, it will also create a version commit and tag. This behavior is controlled by `git-tag-version` (see below), and can be disabled on the command line by running `npm --no-git-tag-version version`. 


p.s. I mostly forget about this command most of the time and update both files manually 😂

**Review by ntwb — APPROVED** [review]

**Pull request merged**
