### PR TITLE
Templates: Apply template for new post only

### PR DESCRIPTION
**Pull request by aduth**
Related: #9287

This pull request seeks to resolve an issue where removing all blocks from a post with a template assigned would reintroduce the template blocks after saving and reloading the editor. This is in contrast with removal of a single block from template, where the edits would be respected. 

It may be that we want to communicate to the user that the block content is in conflict with the template, or provide the option to insert the template for a truly-empty post, but the default behavior should respect the saved content of the user if they had removed the blocks in a previous session.

**Testing instructions:**

Verify that removing all blocks from a post with template, saving that post, and reloading the page, reflects that the blocks are still removed. I found this easiest by reusing the template plugin from within the test folder:

```
cd path/to/plugins
ln -s gutenberg/test/e2e/test-plugins/templates.php templates.php
```

Then activate the plugin from Plugins screen in administration. This will enable a new Books post type with a default template.

Ensure end-to-end tests pass:

```
npm run test-e2e
```

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by youknowriad** [comment]
The e2e test breakage seems legitimate though

**Comment by aduth** [comment]
I renamed the test case and I guess forgot to update the snapshot. See c25fc3a.

**Comment by jasmussen** [comment]
I _think_ this branch made it so the demo content no longer loads. Though note that the way I found this PR was not due to code changes, it was simply looking at https://github.com/WordPress/gutenberg/commits/master, and "Packages: Make usage of `core-data` explicit (#8911)" was the last commit where the demo content worked.

**Comment by aduth** [comment]
Created #9433 to track for release.

**Pull request merged**
