### PR TITLE
Fix button isDefault isBusy hover

### LINKED ISSUE #14296: Button isBusy styles overwritten on hover/focus
**Describe the bug**
If you assign the prop "isBusy" to a Button component that also has the "isDefault" prop, then the "isDefault" styles will override the background animation on hover/focus. So if you want to apply the busy styles to a button on click, it won't show the animation until the user clicks away from the button.

**To Reproduce**
If you use this code and click/hover/focus you can see the different styles being applied.
```
<Button
  isDefault
  isBusy
>
  Button
</Button>
<Button
  isPrimary
  isBusy
>
  Button
</Button>
```

**Expected behavior**
I would think that the "isBusy" styles should override any other buttons styles. Currently focus overrides the animation with both default and primary styles, and hover overrides the animation on default styles. At the least, I think both styles should behave the same.

**Screenshots**
This is the code above. I'm not changing the props on click or anything.
chrome-capture

### PR DESCRIPTION
**Pull request by sbardian**
## Description
CSS update for isDefault and isBusy buttons.  This change is pertaining to issue #14296.  The update seems to fix the issue. 

Closes #14296 

## How has this been tested?
All tests pass running `npm test`

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @sbardian thank you for your contribution, it seems to fix the problem in my tests 👍

We have some duplicate code:
https://github.com/WordPress/gutenberg/blob/2e2dc6b198bbf3ed2611b41e4a706086ec38d2d2/packages/components/src/button/style.scss#L187-L192


Would it be possible to remove the duplication by adding the selectors &.is-defaul.is-busy,&.is-defaul.is-busy:disabled, and &.is-defaul.is-busy[aria-disabled="true"] to the code already existing ?

**Comment by sbardian** [comment]
@jorgefilipecosta you are correct.  I have this updated and it seems to still fix the issue.  Thanks!

**Review by jorgefilipecosta — APPROVED** [review]
LGTM 👍 Thank you for your contribution!

**Comment by youknowriad** [comment]
I wonder if this is related to this regression #15029

**Pull request merged**
