### PR TITLE
Fix e2e failures on 'Front Page' template.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Attempting to fix e2e failures on a "Front Page" template selector.  It looks like tt1-blocks no longer supplies a front-page template, and using Index should work as the tests were not reliant on the specific template.

🤞  on CI checks.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jeyip — COMMENTED** [review]
I confirmed in e2e failure artifacts that the Front Page isn't a selectable template, which explains why the Front Page template selectors are timing out.

+1 from me if the e2e specs for multi-entity-editing and template-part pass in this PR

**Review by vindl — APPROVED** [review]
I think this is fine to merge since it resolves a lot of existing FSE test failures. The ones related to Navigation editor can be handled separately.

**Comment by jeyip** [comment]
We're seeing a new e2e spec failure on this PR. For some reason, the navigation editor is getting stuck on the "Experiment settings" screen.

navigation-editor-displays-the-first-menu-from-the-rest-response-when-at-least-one-menu-exists-2021-02-01t17-54-46

This PR does, however, successfully remove a large swath of existing failures, so +1 from me.

**Review by jeyip — APPROVED** [review]

**Comment by ockham** [comment]
Thanks a lot, y'all! :heart:

**Pull request merged**
