### PR TITLE
WIP: Resizable HTML block.

### LINKED ISSUE #8245: Make custom HTML blocks resizable
image

I don't always need to see every line of code in a custom HTML block, especially when I'm editing a completely different element. Sometimes I just want to minimize it or limit it to a certain height.

Please consider adding a stretch handle or minimize button.

### PR DESCRIPTION
**Pull request by v9ai**
## Description
Fixes: https://github.com/WordPress/gutenberg/issues/8245

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by ellatrix — CHANGES_REQUESTED** [review]
If we make the text area not auto resize by default, then we have this for free from the browser? Perhaps `PlainText` should accept a `rows` prop to be passed down to `textarea`. The presence of this prop would also disable autoresizing.

**Comment by sarahmonster** [comment]
@nicolad It looks like this PR could use a design review. Would it be possible for you to rebase so we can test it out

**Comment by nicolad** [comment]
> @nicolad It looks like this PR could use a design review. Would it be possible for you to rebase so we can test it out
Hi @sarahmonster, I've synced this branch with master, thx for letting me know.
I will loop back on this when I will be less busy with a11y PRs.

**Comment by mapk** [comment]
I've just tested this and didn't notice any resizing abilities. Am I missing something here?

html

Maybe we can make this block react similarly to the [recent Shortcode block changes](https://github.com/WordPress/gutenberg/pull/15365)? The Shortcode block grows as text is typed to a limited height. Once the height reaches 250px it stops growing and just adds a scroll ability. Would that work better?

**Pull request closed without merging**
