### PR TITLE
Try removing block breadcrumbs

### PR DESCRIPTION
**Pull request by kjellr**
As noted in issues like https://github.com/WordPress/gutenberg/issues/16334 and https://github.com/WordPress/gutenberg/issues/14095#issuecomment-468778570, the block breadcrumbs that currently appear on hover may not be necessary UI elements. This PR gives us an opportunity to test what it's like with them gone. 

**Before:** 

Screen Shot 2019-07-10 at 9 20 55 AM

**After:**

Screen Shot 2019-07-10 at 9 19 51 AM

### CODE REVIEW

**Comment by kjellr** [comment]
(Also worth noting: even if we decide to remove this from hover, we may not want to remove it entirely since it may be used for things like #16500)

**Comment by chrisvanpatten** [comment]
As I noted in #16334 I was originally totally in favor of this change but I've definitely re-evaluated and now think it would be a mistake. If this change goes through, you lose an easy way to discern what type of block you're looking at without selecting the block.

For now while the number of core blocks is relatively low, this might not be a huge problem — after all, it's easy to tell apart a paragraph and image block, for instance. But as the number of third party blocks grows (accelerated by the block editor) I think there is tremendous value in making it easier to identify a block in a more ambient way, which these breadcrumbs currently provide.

**Comment by kjellr** [comment]
Yeah, I'm not 100% sure that this makes sense either. It could also be that we just need to rethink the display of these breadcrumbs: maybe they're more like standard tooltips for instance.

**Comment by paaljoachim** [comment]
I kinda like having the block type visible on hover as it quickly gives an overview of the type of block in use.

**Comment by mtias** [comment]
@kjellr I think with block navigation mode we might be able to do this https://github.com/WordPress/gutenberg/pull/16500. What about as a start if we remove the breadcrumb on nested blocks? I think that is adding a lot of noise and not being super helpful.

**Comment by kjellr** [comment]
> What about as a start if we remove the breadcrumb on nested blocks? I think that is adding a lot of noise and not being super helpful.

Yeah, that could be a good route to try out. I tried it out quickly with CSS, and it definitely helps to reduce the noise a bit. 

breadcrumb

We still need to clean up hover states inside these nested blocks (#16820), so let's revisit once that's sorted out too. I'll close this PR in the meantime.

**Pull request closed without merging**
