### PR TITLE
Fix flaky test by finalising request resolution in Nav block e2e test

### LINKED ISSUE #39231: [Flaky Test] shows a loading indicator whilst ref resolves to Navigation post items
<!-- __META_DATA__:{"failedTimes":6,"totalCommits":1} -->
**Flaky test detected. This is an auto-generated issue by GitHub Actions. Please do NOT edit this manually.**

## Test title
shows a loading indicator whilst ref resolves to Navigation post items

## Test path
`specs/editor/blocks/navigation.test.js`

## Errors
<!-- __TEST_RESULTS_LIST__ -->
<!-- __TEST_RESULT__ --><time datetime="2022-03-04T22:42:12.929Z"><code>[2022-03-04T22:42:12.929Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1936139462"><code>types/expand-data-registry</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-07T20:29:32.426Z"><code>[2022-03-07T20:29:32.426Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1947657062"><code>PR-template-update</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-09T03:32:42.814Z"><code>[2022-03-09T03:32:42.814Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1955094049"><code>try/fixing-performance-tests</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-09T08:17:56.474Z"><code>[2022-03-09T08:17:56.474Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1956000311"><code>wp/next</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-10T10:27:54.540Z"><code>[2022-03-10T10:27:54.540Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1962421669"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-15T08:23:21.976Z"><code>[2022-03-15T08:23:21.976Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1985374634"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-15T10:29:27.866Z"><code>[2022-03-15T10:29:27.866Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1985376732"><code>fixup/changelog-section</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-17T01:19:26.857Z"><code>[2022-03-17T01:19:26.857Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1995943703"><code>try/expose-enqueue-webfont-method</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-17T08:06:35.341Z"><code>[2022-03-17T08:06:35.341Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1997267652"><code>update/npm-publish-workflow</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-17T15:58:56.579Z"><code>[2022-03-17T15:58:56.579Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1999197020"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-17T17:07:56.976Z"><code>[2022-03-17T17:07:56.976Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/1999605072"><code>try/test-github-actions</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-18T10:04:08.129Z"><code>[2022-03-18T10:04:08.129Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2003355068"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-18T14:44:59.724Z"><code>[2022-03-18T14:44:59.724Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2004632828"><code>release/12.8</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-18T15:26:05.035Z"><code>[2022-03-18T15:26:05.035Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2004851085"><code>refactor/ts-base-control</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-19T05:37:06.611Z"><code>[2022-03-19T05:37:06.611Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2007691108"><code>fix/image-align-center</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-21T00:31:40.348Z"><code>[2022-03-21T00:31:40.348Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2013438119"><code>fix/gallery-e2e-flakiness</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-21T16:20:57.073Z"><code>[2022-03-21T16:20:57.073Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2017209469"><code>add/puppeteer-local-chrome-env</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-25T05:23:05.765Z"><code>[2022-03-25T05:23:05.765Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2038202701"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-25T10:43:25.577Z"><code>[2022-03-25T10:43:25.577Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2039430483"><code>update/quote-block-v2-register</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-03-25T11:16:53.133Z"><code>[2022-03-25T11:16:53.133Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2039565305"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-16T16:01:43.736Z"><code>[2022-06-16T16:01:43.736Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2510092620"><code>propose/use-resource-permissions</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-16T17:43:22.868Z"><code>[2022-06-16T17:43:22.868Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2510648098"><code>add/post-comments-form-warning-enable-comments-button</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T09:22:15.200Z"><code>[2022-06-17T09:22:15.200Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2514342259"><code>remove/lodash-is-number</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T11:24:33.976Z"><code>[2022-06-17T11:24:33.976Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2514730000"><code>remove/lodash-to-string</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T12:00:35.482Z"><code>[2022-06-17T12:00:35.482Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2515149869"><code>trunk</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T12:31:16.675Z"><code>[2022-06-17T12:31:16.675Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2514501404"><code>update/spinner-typescript</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T13:31:37.896Z"><code>[2022-06-17T13:31:37.896Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2515539050"><code>remove/lodash-is-nil</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-17T15:55:42.884Z"><code>[2022-06-17T15:55:42.884Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2516453876"><code>update/html-block</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-18T16:52:19.088Z"><code>[2022-06-18T16:52:19.088Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2520557391"><code>refactor/list-block-e2e-playwright</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-18T23:36:32.748Z"><code>[2022-06-18T23:36:32.748Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2522062335"><code>add/e2e-style-variation-playwright</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-19T10:11:49.682Z"><code>[2022-06-19T10:11:49.682Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2515560285"><code>fix/block-settings-menu-controls-check</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T01:50:19.434Z"><code>[2022-06-20T01:50:19.434Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2525928954"><code>add/spacing-sizes-part-1</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T09:33:29.255Z"><code>[2022-06-20T09:33:29.255Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2527856722"><code>remove/lodash-find-key</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T11:32:11.626Z"><code>[2022-06-20T11:32:11.626Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2528032140"><code>remove/lodash-size</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T12:50:59.723Z"><code>[2022-06-20T12:50:59.723Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2528939023"><code>add/UI-for-block-element</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T14:37:28.780Z"><code>[2022-06-20T14:37:28.780Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2527832808"><code>remove/lodash-find-last</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-20T15:07:16.751Z"><code>[2022-06-20T15:07:16.751Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2528812440"><code>rnmobile/add/integration-test-helpers</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><time datetime="2022-06-21T08:57:43.071Z"><code>[2022-06-21T08:57:43.071Z]</code></time> Test passed after 2 failed attempts on <a href="https://github.com/WordPress/gutenberg/actions/runs/2528135290"><code>try/improve-contrast-checker</code></a>.<!-- /__TEST_RESULT__ -->
<br/>
<!-- __TEST_RESULT__ --><details>
<summary>
	<time datetime="2022-06-22T05:43:16.494Z"><code>[2022-06-22T05:43:16.494Z]</code></time> Test passed after 1 failed attempt on <a href="https://github.com/WordPress/gutenberg/actions/runs/2533135767"><code>rnmobile/update-aztec-placeholder-api</code></a>.
</summary>

```
  ● Navigation › loading states › shows a loading indicator whilst ref resolves to Navigation post items

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Failed to load resource: the server responded with a status of 404 (Not Found)"]

      at Object.assertExpectedCalls (../jest-console/build/@wordpress/jest-console/src/index.js:36:4)
          at runMicrotasks (<anonymous>)

```
</details><!-- /__TEST_RESULT__ -->
<!-- /__TEST_RESULTS_LIST__ -->

### PR DESCRIPTION
**Pull request by getdave**
## What?
Fixes to the e2e tests to resolve https://github.com/WordPress/gutenberg/issues/39231.

Closes https://github.com/WordPress/gutenberg/issues/39231.

## Why?

This e2e test keeps failing https://github.com/WordPress/gutenberg/issues/39231 because the resolution function maybe be null and not callable.

## How?

Conditionalises the calling of the resolution function to check whether it is a function.

### CODE REVIEW

**Comment by getdave** [comment]
@talldan I wonder if your expert knowledge of e2e tests can shed any light on this.

It passes locally but is flaky on CI.

When the block is added with the `ref` of `1` a request should made to the endpoint `/wp-json/wp/v2/navigation/2?context=edit&_locale=user`. However the request match obviously doesn't always work and thus the `resolveNavigationRequest` var is not always a function.

The question is _why_ does the request sometimes not match?

**Comment by talldan** [comment]
@getdave I don't know for sure. I'd recommend having a look through the docs for request interception and then taking a look at how `setUpResponseMocking` works:
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagesetrequestinterceptionvalue

I wonder if there's an issue in that this code never calls `request.respond` or `request.continue`. The docs seem to mention that's an important part of handling requests. I think it should call `request.continue` when it's ready to resolve. Usually `createJSONResponse` handles that implementation detail (but using `request.respond` to change the response).

Having said that, I don't know that the request technically needs to resolve. The promise code might not be necessary at all. The tests don't do anything after the promise resolves, so maybe the easiest option is to not resolve.

**Comment by getdave** [comment]
> Having said that, I don't know that the request technically needs to resolve. The promise code might not be necessary at all. The tests don't do anything after the promise resolves, so maybe the easiest option is to not resolve.

I guess I didn't want to risk having a unfulfilled `Promise` hanging around.

**Comment by getdave** [comment]
@talldan I took a more careful look at `createJSONResponse` and `setUpResponseMocking` and as a result I've tried calling `request.continue()` when the Promise is resolved. Let's see how that pans out.

**Comment by getdave** [comment]
Github Actions are down now so I'll have to wait until tomorrow to see if this works on CI. Oh the suspense!

**Comment by getdave** [comment]
I'm going to re-run these tests several times to see if they are still flaky. 

- [x] [Run 1](https://github.com/WordPress/gutenberg/runs/5689572105?check_suite_focus=true)
- [x] [Run 2](https://github.com/WordPress/gutenberg/runs/5716919229?check_suite_focus=true)
- [x] [Run 3](https://github.com/WordPress/gutenberg/runs/5717313730?check_suite_focus=true)
- [x] [Run 4](https://github.com/WordPress/gutenberg/runs/5717697970?check_suite_focus=true)
- [x] [Run 5](https://github.com/WordPress/gutenberg/runs/5718065727?check_suite_focus=true)

**Comment by getdave** [comment]
Ok this passed 5 times without issue. Going to merge and 🙏 that fixes it.

**Review by scruffian — APPROVED** [review]

**Pull request merged**
