### PR TITLE
DataViews: add description to pages

### PR DESCRIPTION
**Pull request by oandregal**
Part of https://github.com/WordPress/gutenberg/issues/55083
Follow-up to https://github.com/WordPress/gutenberg/pull/57578

## What?

- Updates the description for Pages:
  - Before: "Browse and edit pages of your site"
  - After: "Browse and manage pages"
- Add the same description to dataviews-powered Pages as well.

| | Before | After |
| --- | --- | --- |
| Pages (stable) | Captura de ecrã 2024-01-12, às 09 31 39 | Captura de ecrã 2024-01-15, às 12 33 48 |
| Pages (dataviews) | Captura de ecrã 2024-01-12, às 09 45 29 | Captura de ecrã 2024-01-15, às 12 33 33 |

## Why?

All root pages have a description and the existing page we aim to replace also has one.

## How?

Adds the description to the sidebar component.

## Testing Instructions

- Enable the "new admin views" experiment and visit "Manage all pages".
- Verify the description is there.

### CODE REVIEW

**Comment by jameskoster** [comment]
I've seen comments about avoiding language that alludes to personal ownership to account for different user roles, so perhaps something like:

> Browse and manage pages.

Still, I'm not entirely convinced about the value this description adds. Is it really needed? Let's ping @WordPress/gutenberg-design for more input.

**Comment by oandregal** [comment]
> Still, I'm not entirely convinced about the value this description adds. Is it really needed?

This PR adds the text in use by the existing page to the new one. I thought we'd want the same, but happy to iterate on the copy or having no text at all.

**Comment by paaljoachim** [comment]
I did not see any difference from before and after.... Where is the adjustment?

EDIT.
Based on the text "Browse and manage pages" in the top left area I see the before does not have it and the after does.
I am not sure of the value of this description. If it exists in another place then it would be nice with a consistency between them.

Edit 2.
Brain storming...
Now as I gradually get into it. It does have value as it brings an extra clarity to what can be done in the screen. I also believe all these kinds of pages should have a description in them.

**Comment by jameskoster** [comment]
> I thought we'd want the same

I think the inclusion of 'your' in the Pages panel was an oversight. There were a few PRs to remove similar language in other parts of the UI.

"Browse and manage pages" seems fine to try.

**Comment by oandregal** [comment]
> "Browse and manage pages" seems fine to try.

👍 

Used this for both the stable Pages and the dataviews-powered one. Update the PR description with before/after screenshots as well.

**Review by jameskoster — APPROVED** [review]

**Pull request merged**
