### PR TITLE
19.8 Edit Site: styles nav item does not open on mobile for themes without style variations 

### PR DESCRIPTION
**Pull request by ramonjd**
## What?

Resolves https://github.com/WordPress/gutenberg/issues/67532 for 19.8
1. Remove `hasGlobalStyleVariations` condition to show the Styles menu item in the edit site sidebar.
2. Also, move its `uid` prop to `MainSidebarNavigationContent` for consistency and convenience.

## Why a hotfix for this branch?

Since https://github.com/WordPress/gutenberg/pull/67199 a few things have changed in trunk so this PR targets the state of 19.8 only.

In trunk this bug has been fixed by the following PRs:

- https://github.com/WordPress/gutenberg/pull/67537
- https://github.com/WordPress/gutenberg/pull/67545

## Why?

BUG! When a block theme doesn't have style variations, the newer experience for top level styles in the Site Editor does not open on mobile.

The sidebar navigation styles item [now contains the global styles UI](https://github.com/WordPress/gutenberg/pull/65619) and no longer just the variations. For this reason it's okay to remove the condition. 

## Testing Instructions

1. Use a block theme without style variations, like https://wordpress.org/themes/onyxpulse/
2. In "mobile" view (narrow viewport) open Appearance > Editor
4. Select Styles. Ensure that you can see the Global Styles UI
5. Switch to a theme with style variations, e.g., https://wordpress.org/themes/twentytwentyfive/
6. Select Styles. Ensure that you can see the Global Styles UI.

## Screenshots or screencast 

https://github.com/user-attachments/assets/e75c3ab4-1040-4541-ab9a-19376fa7d41c

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Tests well for me.

It's interesting the way the little style preview in the sidebar doesn't expands on mobile, but I guess this is a separate bug. It makes it looks like there's a double horizontal rule:

https://github.com/user-attachments/assets/848fd423-fb57-44a1-9081-fda0c950abeb

**Review by aaronrobertshaw — COMMENTED** [review]
This is testing as advertised for me. 

The only difference I spotted between the changes here and the linked PR was this didn't add the `to="/styles"` prop. Was that intended?

Here's what I'm seeing:


https://github.com/user-attachments/assets/c510c52a-985b-438f-9d9a-7b5e874bf27d

**Comment by ramonjd** [comment]
Thanks a lot for testing @aaronrobertshaw 

> The only difference I spotted between the changes here and the linked PR was this didn't add the to="/styles" prop. Was that intended?

The `to` prop was introduced in https://github.com/WordPress/gutenberg/pull/67199, which is slated for 19.9 so I had to work with the "is" state of 19.8.

Cheers!

**Comment by ramonjd** [comment]
> but I guess this is a separate bug. It makes it looks like there's a double horizontal rule:

Thanks @talldan 

Funny you should mention that 😄 

- https://github.com/WordPress/gutenberg/pull/67548

**Pull request merged**
