### PR TITLE
Mobile - RichText - Update logic for the placeholder text color

### LINKED ISSUE #6069: Update the Title and Paragraph block default placeholder text colors for standard themes
When using a standard theme, we are setting a lighter color for the placeholder text color for the Title and the Paragraph blocks. We should update it to the expected color of the recent design changes:

<kbd></kbd>

### PR DESCRIPTION
**Pull request by geriux**
**Related PRs:**
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/6182
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21544

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/6069

## What?
This PR updates the logic for the placeholder text colors for the RichText component and block-based themes.

## Why?
Previously, the same colors were displayed for both the placeholder text and the populated RichText component.

## How?
Opacity is added to the placeholder text color, utilizing the default text color derived from the theme settings.

The update also resolves a pre-existing issue where the empty placeholder displayed a smaller font size in instances where the current theme had a font size larger than the mobile editor's default. The font size now aligns with the Paragraph block's default size.

## Testing Instructions
**Precondition:** Use a block-based theme like `Didone`

- Open [the build from this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/21544#issuecomment-1714309636)
- Open the editor
- Expect to see the default block appender with the right styling
- Tap on the default block appender
- **Expect** to see the new Paragraph block to match the font size of the default block appender
- Type some text
- **Expect** the value color to not have any opacity

## Screenshots or screencast 

**Note:** Screenshots done using the Didone theme.

Before Default Block Appender|After Default Block Appender
-|-
<kbd></kbd>|<kbd></kbd>

Before Placeholder color|After Placeholder color
-|-
<kbd></kbd>|<kbd></kbd>

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
LGTM! I was able to follow the testing steps successfully. 🚀

**Comment by osullivanchris** [comment]
LGTM!

**Comment by osullivanchris** [comment]
@geriux what opacity value did you use for placeholders? I'm not noticing a huge distinction in some places.

**Comment by geriux** [comment]
> @geriux what opacity value did you use for placeholders? I'm not noticing a huge distinction in some places.

We are using a hexadecimal color code for the transparency, for the placeholders is `63%` which has as hex code `A1`. I used [this list as a reference](https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4). We then append that hex code to the text color of the theme.

**Comment by osullivanchris** [comment]
ok cool thanks, 63% sounds good.

**Pull request merged**
