### PR TITLE
Categories List Block: Match the markup on the block editor to the front end

### LINKED ISSUE #42984: Categories List block: CSS classes inconsistency in the list
### Description

The editor displays the following CSS classes in the list of the block:

`wp-block-categories__list wp-block-categories__list-level-0`

The website displays the following CSS classes in the list of the block:

`wp-block-categories-list wp-block-categories`

### Step-by-step reproduction instructions

1. Go to the Widgets screen
2. Add Categories block
3. Publish changes

I used default WordPress theme with support for widget areas: Twenty Twenty One

### Screenshots, screen recording, code snippet

Editor:
Category block in the editor

Website:
Category block on the actual website

### Environment info

Fresh WordPress installation:
 
- Twenty Twenty One theme (Version: 1.6)
-  WordPress (Version:  6.0.1)

No plugins.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fix: #42984

## What?
This PR makes the markup on the block editor the same as on the front editor in order to keep the markup consistent.

## Why?
If class names and makups are different between the editor and the front end, it will be difficult to use a common selector for styling.

Also, I could not find any reason for different markup on the editor.

## How?
In order to get closer to the frontend markup, I have taken the following actions:

-  Change the block tag according to its display status (i.e., when displayed in a list, it becomes `ul` tag)
- Remove unused elements and class names on the front end (`.wp-block-categories__list`, `.wp-block-categories__list-level-{level}`, `.wp-block-categories__post-count`, `.wp-block-categories__dropdown`）
- Add empty option tag ("Select Category") to dropdown
- Add missing class names (`li.cat-item,cat-item-{id}`, `option.level-{level}`)

## Testing Instructions
- Insert the Categories List Block.
- Toggle the option variations and confirm that the frontend and block editor markup is nearly identical for both variations.

## Screenshots or screencast

Below is a comparison of the block editor and front-end markup for one variation.

### Frontend

frontend

### Block Editor

block-editor

### CODE REVIEW

**Comment by carolinan** [comment]
Wish: To be able to style the post count, the span and the class name that was used in the editor should be added to the front instead of removed from the editor.

**Comment by t-hamano** [comment]
> Wish: To be able to style the post count, the span and the class name that was used in the editor should be added to the front instead of removed from the editor.

Thanks for your input!
On the front end, the block is output via `wp_list_categories`.
And the "Show post counts" option is internally controlled at this lines in the WordPress core:
 https://github.com/WordPress/wordpress-develop/blob/de3fbdecc0eca1ec876dfd04bbf642a7f60a57b4/src/wp-includes/class-walker-category.php#L192-L194

So this might be something to consider in the WordPress core.

Also, there is `wp_list_categories` filter hook to rewrite the final HTML, but I think this should be used by the user, not by the core block.

**Review by carolinan — APPROVED** [review]
I have tested the PR, and I have not found any issues. Moving the class `wp-block-categories-dropdown` from the `select` to the wrapping div is an improvement.

I found one plugin in the plugin directory that styles this class:
https://wpdirectory.net/search/01GCGP40C3JA2F62XNK7G0VQTV

There are 251 themes in the theme directory that styles this class, but I did not dig deep enough to see if it was an editor style or front end style:
https://wpdirectory.net/search/01GCGP7P7R5R9YFQ98S4VGA0GY

I would consider the change low risk.

**Comment by t-hamano** [comment]
@carolinan 
Thank you for investigating the scope of the impact!
I, too, consider this change low risk.
In the past, PRs with markup changes in the editor has not specifically mentioned the scope of their impact, and I believe this PR is similar.

- #41631
- #39414
- #30148


Therefore, I would like to merge this PR as is.

**Pull request merged**
