### PR TITLE
Content Block: Change placeholder and e2e test to refer to Content block

### PR DESCRIPTION
**Pull request by jordesign**
## What?
Updates the placeholder text for the Content block (which was recently changed from the 'Post Content' block) so it no longer refers to _itself_ as the Post Content block.

## Why?
Recently the Post Content block was changed to just be the 'Content' block. This update brings the placeholder text up to date.

Addresses  https://github.com/WordPress/gutenberg/issues/53894

## Testing Instructions

1. Open or add a template in the site editor
2. Add a 'Content' block
3. Confirm that the placeholder content refers to the 'Content' block, not the 'Post Content' block

## Screenshots or screencast 
Screenshot 2023-08-24 at 12 51 54 pm

### CODE REVIEW

**Comment by andrewserong** [comment]
Thanks for opening this PR @jordesign! The code change is generally looking good. One issue in this PR is that the included changes in `package-lock.json` appear to be causing the Github Actions to fail.

Do you mind removing the change to `package-lock.json`? I think you should be able to do it locally by running `git checkout trunk ./package-lock.json` to restore the file in this branch to the state that is on trunk:

image

Then, you'd commit and push the updated file.

If you're finding that there's often changes to `package-lock.json` when creating branches, one approach to avoid it is to use `npm ci` when installing dependencies instead of `npm install` — `npm ci` uses the versions of dependencies from the `package-lock.json`, so your local environment will more closely match the environment used in Github actions.

**Comment by jordesign** [comment]
Thanks @andrewserong  - I had been wondering why that kept showing up as changed 😂 

I've reverted back to the old version of it now

**Comment by andrewserong** [comment]
@jordesign thanks for updating! It looks like you might need to do a fresh `pull` of trunk, as the changes to `package-lock.json` appear to be from an older version (GB `16.1.0-rc.1`).

Apologies, I didn't catch that you're working from a fork, so likely your trunk branch is behind the origin trunk. A couple of ways to update to the latest file:

* The quick way for this branch, you can specify the remote at the same time as checking out the single file, so `git checkout origin/trunk ./package-lock.json` (`origin/trunk` instead of `trunk`) — if your remote pointing to `wordpress/gutenberg` is different to `origin` then use that word instead. You can check your current remotes by running `git remote -v`.
* Or, check out your `trunk` branch and `pull` the latests changes before switching to your PR's branch and doing the previous `git checkout trunk ./package-lock.json` command above

**Comment by jordesign** [comment]
Right you are - that should be resolved now @andrewserong

**Review by andrewserong — APPROVED** [review]
Thanks for the updates Jordan, this LGTM! ✨

I noticed one of the playwright e2e jobs failed, but the error message didn't look related to this PR, so I've just kicked it off again to see if that'll get it passing 🤞

**Comment by jordesign** [comment]
Fantastic - looks like it worked this time around - so I'll merge that now.

**Pull request merged**
