### PR TITLE
Preference modal: avoid fetching all reusable blocks when the site editor loads

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Introduced in #65026, which adds an option to the preferences modal to hide the starter patterns modal. This is causing all reusable blocks and patterns to be fetched on load.

We can prevent this by only calling the hook when the modal is open.

But, why do we need to load all starter patterns in the first place? Why not just always show the option?

And, why do we need this option at all? What happened to: decisions, not options? This modal should be adjusted to be less annoying in the first place.

## Why?

All reusable blocks and patterns are fetched on editor load.

## How?

Moving the `useStartPatterns` hook into a wrapper and returning early in the parent component.

## Testing Instructions

1. From WP Admin, open the site editor (don't click on the preview to enable "edit" mode)
2. Check in the browser's network tab that `/wp/v2/block-patterns/patterns&_locale=user` is not called.

### CODE REVIEW

**Comment by ramonjd** [comment]
> And, why do we need this option at all? What happened to: decisions, not options? This modal should be adjusted to be less annoying in the first place.

It was a compromise I guess. 

My opinion, [stated several times](https://github.com/WordPress/gutenberg/pull/65026#issuecomment-2333723060), was that the modal is annoying and it should be removed completely until something better is proposed.

I'm still of that opinion.

**Comment by andrewserong** [comment]
> But, why do we need to load all starter patterns in the first place? Why not just always show the option?

Good question. I guess because [the modal itself](https://github.com/WordPress/gutenberg/blob/fa78b66aea850d13e0621d0fcc6ddaf5ca3772f4/packages/editor/src/components/start-page-options/index.js#L96) will only display if the site has start patterns, so it could be confusing if there's a preference that doesn't appear to do anything? I.e. should this preference be visible on Classic themes?

> My opinion, https://github.com/WordPress/gutenberg/pull/65026#issuecomment-2333723060, was that the modal is annoying and it should be removed completely until something better is proposed.

I agree. If done well, I don't mind the idea of a modal for selecting patterns, like via the "Explore all patterns" button in the patterns tab in the inserter. To me this particular modal feels more intrusive than useful.

---

In terms of the scope of this PR, nice idea moving to a wrapper and returning early to skip calling the hooks when not needed! Looks like some of the tests are failing. Are they related to the change?

> And, why do we need this option at all? What happened to: decisions, not options? This modal should be adjusted to be less annoying in the first place.

If you have ideas about how it could be less annoying, let's open an issue for it.

**Comment by ramonjd** [comment]
Tests need to be fixed.

I updated the test instructions to make it clearer what this PR does.

**Comment by ramonjd** [comment]
Thanks for getting the PR up. LGTM.

I'll fix the failing tests and merge it.

**Review by ramonjd — APPROVED** [review]

**Comment by andrewserong** [comment]
Thanks for getting this over the line, @ramonjd! 🙇

**Comment by ellatrix** [comment]
@ramonjd Yes, in my opinion too, this modal is annoying to ALL users, and should just be removed we should trigger zoom out mode as proposed in #61489. :)

**Pull request merged**
