### PR TITLE
Rename the wp-env schema to not be a dotfile

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Rename the wp-env schema to not be a dotfile.

## Why?

Schemastore.org also stores schemas for dotifles without the dot, and we're mostly mirroring how they handle schemas.

## How?

Rename the wp-env schema to not be a dotfile.

## Testing Instructions

Can't properly be tested until merged, but schema urls will have to be updated to `https://schemas.wp.org/trunk/wp-env.json`.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
I tested how the `theme.json` and `block.json` schemas are redirected.

```
$ curl -s -o /dev/null -w "%{redirect_url}\n" https://schemas.wp.org/trunk/block.json
https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/block.json
```

```
$ curl -s -o /dev/null -w "%{redirect_url}\n" https://schemas.wp.org/trunk/theme.json
https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json
```

Regarding the wp-env scheme, it seems like the redirect URL is not correct, whether there is a dot or not.

```
$ curl -s -o /dev/null -w "%{redirect_url}\n" https://schemas.wp.org/trunk/.wp-env.json
https://raw.githubusercontent.com/
```

```
$ curl -s -o /dev/null -w "%{redirect_url}\n" https://schemas.wp.org/trunk/wp-env.json
https://raw.githubusercontent.com/
```

Will this issue be resolved if this PR is merged?

**Comment by ajlende** [comment]
> Will this issue be resolved if this PR is merged?

Judging from the tests you did, it doesn't look like it. And after some more searching, I found a systems request [Add redirect for Font Collection JSON schema](https://make.wordpress.org/systems/2024/01/16/add-redirect-for-font-collection-json-schema/) which worked and I assumed didn't need the systems change.

I asked in [#meta](https://wordpress.slack.com/archives/C02QB8GMM/p1718649686552709) on the Making WordPress slack if it could get added.

I still think we should keep the rename, so I've updated the description to reflect that.

Once I figure out the process, I'll update the README.md with details for future developers adding schemas.

**Comment by t-hamano** [comment]
I checked the "[Schema redirect for .wp-env.json](https://make.wordpress.org/systems/2024/06/18/schema-redirect-for-wp-env-json/)" post. From what I saw in the post, it seems that the redirection is done for the dotted file.

```
https://schemas.wp.org/trunk/.wp-env.json
=>
https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/.wp-env.json
```

Therefore, I am concerned that if we push ahead with this PR, the redirected file will not be found.

If we go ahead with this PR and take Schemastore.org into consideration, should we change the redirect to the following:

```
https://schemas.wp.org/trunk/wp-env.json
=>
https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/wp-env.json
```

**Comment by dd32** [comment]
> Therefore, I am concerned that if we push ahead with this PR, the redirected file will not be found.

100% move forward with this, I'll update the systems request to match.

**Review by sirreal — APPROVED** [review]

**Comment by ellatrix** [comment]
I just cherry-picked this PR to the wp/6.6-rc-1 branch to get it included in the next release: 861b0892b3

**Pull request merged**
