### PR TITLE
Update npm lockfile to version 3

### PR DESCRIPTION
**Pull request by sirreal**
## What?

[Update the package-lock.json file to the v3 format:
](https://docs.npmjs.com/cli/v8/using-npm/config#lockfile-version)
> 3: Only the new lockfile information introduced in npm version 7. Smaller on disk than lockfile version 2, but not interoperable with older npm versions. Ideal if all users are on npm version 7 and higher.

Given our engines and engine-strict setting, npm versions earlier than 7 should not be used and there should be no downsides to this change:

https://github.com/WordPress/gutenberg/blob/3214be4cc64b10feb2935da43962480cc562b285/package.json#L17-L20

https://github.com/WordPress/gutenberg/blob/3214be4cc64b10feb2935da43962480cc562b285/.npmrc#L2

## Why?

The file should be smaller without other changes. It should be strictly better.

The package-lock.json file goes from `3475383` to `1926901` bytes in this PR, a savings of ~1.5MB.

## Testing Instructions

CI should pass on the PR. Locally the project should work without any changes: `npm ci`, `npm run build`, etc.

### CODE REVIEW

**Comment by sirreal** [comment]
I created a PR for Core as well: https://github.com/WordPress/wordpress-develop/pull/7526

**Comment by gziolo** [comment]
Assuming CI passes, it should be fine to upgrade the lock file 👍

**Review by DaniGuardiola — APPROVED** [review]
I see red, I approve

image

Jokes aside, this makes sense to me 👍

**Comment by tyxla** [comment]
Thank you @sirreal 🚀

**Pull request merged**
