### PR TITLE
Query: Require queryId for enhanced pagination to prevent PHP notices.

### LINKED ISSUE #55719: Enhanced Pagination throws notices if Query ID is not defined.
### Description

Enhanced pagination of the query block throws notices if the query ID is not defined.

```
Notice: Undefined index: queryId in .../gutenberg/build/block-library/blocks/query.php on line 150
Notice: Undefined index: queryId in .../gutenberg/build/block-library/blocks/query.php on line 25
Notice: Undefined index: queryId in .../gutenberg/build/block-library/blocks/query.php on line 170
```

In the Site Editor, it appears this is prevented from happening, so the issue only occurs if the incorrect markup is used in the  files of a distributed theme.

I think if the queryId is not defined, then enhanced pagination can be prevented. Generating a queryId could work but may lead to collisions if there are two queries on the page and one of them has the value defined.

### Step-by-step reproduction instructions

1. Enabled debug mode in your wp-config file:
   ```php
   define( 'WP_DEBUG', true );
   define( 'WP_DEBUG_LOG', true );
   define( 'WP_DEBUG_DISPLAY', true );
   ```
2. Download and activate  [peters-sample-theme.zip](https://github.com/WordPress/gutenberg/files/13211136/peters-sample-theme.zip) which contains bad markup in `templates/index.html`
3. Visit the theme on the front end of the site.
4. Observe the notices thrown

### Screenshots, screen recording, code snippet

Stack trace attached, it's quite a lot because it's generated with xdebug enabled.

[debug.log](https://github.com/WordPress/gutenberg/files/13211170/debug.log)

### Environment info

- WordPress trunk (6.5-alpha @ https://github.com/wordPress/wordpress/commits/cc0246c154bc090bc95849f27a2747b3e524f116 )
- Gutenberg trunk @ 929a37d9f45479915358746c334e9a668fda780c

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by peterwilsoncc**
## What?

Adds a check to ensure the Query ID is set before rendering enhanced pagination.

Fixes #55719.

## Why?

Without a Query ID the enhanced pagination will throw a notice. The Query ID doesn't include a default so can be unset.

## How?

Within `render_block_core_query()` the conditions checking `$attributes['enhancedPagination']` are modified to also check `isset( $attributes['queryId'] )`. If either item is not set then the feature is not enabled.

## Testing Instructions

1. Enable debug mode in your wp-config file:
   ```php
   define( 'WP_DEBUG', true );
   define( 'WP_DEBUG_LOG', true );
   define( 'WP_DEBUG_DISPLAY', true );
   ```
2. Download and activate  [peters-sample-theme.zip](https://github.com/WordPress/gutenberg/files/13211136/peters-sample-theme.zip) which contains bad markup in `templates/index.html`
3. Generate some sample posts via WP CLI: `wp post generate`
4. Visit the the front end of the site.
   - on trunk you should see some notices thrown
   - on this branch the notices should not throw
5. Activate the TT2 theme
6. Edit the home page to enable advanced pagination on the query loop
7. Navigate posts, ensure advanced pagination works.

### Testing Instructions for Keyboard

N/A

### CODE REVIEW

**Comment by hellofromtonya** [comment]
## Test Report
This report validates that the indicated patch addresses the issue.

### Environment
- OS: macOS
- Web Server: Nginx
- PHP: 8.0.30
- WordPress: 6.4 RC2
- Browser: Firefox
- Theme: https://github.com/WordPress/gutenberg/files/13211136/peters-sample-theme.zip
- Active Plugins: None

### Actual Results 
* Before the patch, can reproduce the PHP Warnings 🐞❌
* After applying the patch: no PHP Warnings ✅ 

  **Test Report Icons:**
  🐞 <= Indicates where issue ("bug") occurs.
  ✅ <= Behavior is ''expected''.
  ❌ <= Behavior is ''NOT expected''.

**Review by hellofromtonya — APPROVED** [review]
[See my test report](https://github.com/WordPress/gutenberg/pull/55720#issuecomment-1787188784) which confirms:

* can reproduce the PHP Warning before this PR
* this PR resolves the issue.

**Comment by hellofromtonya** [comment]
React Native e2e tests (Android): 
The failing test is unrelated to this PR, as it seems the service is unavailable. Restarting.

**Comment by hellofromtonya** [comment]
@SiobhyB @mikachan marking this PR for cherry-picking for 6.4 RC3.

**Review by DAreRodz — APPROVED** [review]
Thanks for the fix, @peterwilsoncc! 🙏

The enhanced pagination indeed requires the `queryId` attribute to be set to generate the `data-wp-navigation-id` prop, so this change makes total sense.

**Comment by mikachan** [comment]
I just cherry-picked this PR to the 6.4-rc3-2 branch to get it included in the next release: de980d5e73

**Comment by peterwilsoncc** [comment]
Thanks for merging this promptly. I've created #55747 as a follow up to investigate whether the ID can be autogenerated if it's missing in order to respect developer intent.

**Pull request merged**
