### PR TITLE
Open "docs" folder for the Interactivity API package and Getting Started Guide

### PR DESCRIPTION
**Pull request by juanmaguitar**
## What?
Open the "docs" folder for the Interactivity API package with some initial content

## Why?
So there's a main reference for the docs of this project

### CODE REVIEW

**Review by luisherranz — APPROVED** [review]
Looks good to me!! 🙂

I only have one comment: I see that [the official guide recommends Node 14](https://developer.wordpress.org/block-editor/getting-started/devenv/#node-development-tools), but in my experience that's only true for Gutenberg itself, not for external plugins relying on `wp-scripts`. So I would not recommend having to install Node 14, which is complex because it's an outdated version. Whatever version people have should be fine. Actually, `wp-now` requires at least Node 16, so if we are recommending it, it would be very confusing to ask people to run `wp-scripts` with Node 14 and `wp-now` with Node 16+. Anyway, I would just say "Node".

**Comment by juanmaguitar** [comment]
> Actually, `wp-now` requires at least Node 16

@luisherranz Do you have located any official resources stating this recommendation for `wp-now`?
I don't see any references to the recommended Node version at https://www.npmjs.com/package/@wp-now/wp-now

**Comment by luisherranz** [comment]
It looks like their [minimum supported version is Node 18](https://github.com/WordPress/playground-tools/issues/87#issue-1792086820) as of today.

**Comment by juanmaguitar** [comment]
> [...] I would not recommend having to install Node 14, which is complex because it's an outdated version. Whatever version people have should be fine. 

@luisherranz As per your feedback, I have updated the docs to remove any specific recommendation for a Node version.

**Review by luisherranz — APPROVED** [review]

**Pull request merged**
