### PR TITLE
Add `require-module` to `npmPackageJsonLintConfig` in `package.json`

### PR DESCRIPTION
**Pull request by ntwb**
## Description

Follow up to #14388 to add `require-module` to the `npmPackageJsonLintConfig` in `package.json`

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ntwb** [comment]
13 packages affected:

```shell
[1] ./packages/babel-plugin-import-jsx-pragma/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/babel-preset-default/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/block-serialization-spec-parser/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/browserslist-config/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/docgen/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/e2e-tests/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/eslint-plugin/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/is-shallow-equal/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/jest-preset-default/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/library-export-default-webpack-plugin/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/npm-package-json-lint-config/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/postcss-themes/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] ./packages/scripts/package.json
[1] ✖ require-module - node: module - module is required
[1] 1 error
[1] 0 warnings
[1] 
[1] Totals
[1] 13 errors
[1] 0 warnings
```

**Comment by gziolo** [comment]
Is there any way for a package to mark that it is not using `module` at all. It might be all correct that they don't provide `module` because they are never transpiled.

**Comment by ntwb** [comment]
There is not, currently, I've added a comment to https://github.com/tclindner/npm-package-json-lint/issues/93#issuecomment-472337529 which is seeking to add exceptions for another rule, and as noted in my comment there, there are quite possibly other rules that on occasion exceptions would be handy.

**Comment by aduth** [comment]
Would it be fair to consider this as blocked by https://github.com/tclindner/npm-package-json-lint/issues/93 ?

Otherwise, how can we move forward here?

**Comment by aduth** [comment]
https://github.com/tclindner/npm-package-json-lint/issues/93 appears to have been addressed. Should this be updated now?

**Comment by youknowriad** [comment]
Hi There! I've triaging PRs today and it seems this one is stale. I'm going to close now but please consider reopening if you have some time to refresh it. Thanks.

**Pull request closed without merging**
