### PR TITLE
Document Actions: Fix Block Editor Inserter Overlap with Document Titles

### PR DESCRIPTION
**Pull request by jeyip**
## Description

When scrolling through the block editor, if a sibling inserter is being displayed, it will overlap the document actions labels.

## How has this been tested?

1. Set up the site editor locally
2. Navigate to the site editor 
3. Hover over a sibling inserter
4. Scroll down through the editor until the inserter would overlap the document actions labels
5. Verify that there is no visual overlap

### Before
Screen Shot 2020-10-02 at 5 06 04 PM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
It fixes it under document actions, but I think we may want to set this color for the entire header in edit-site (as opposed to just the document-actions area)?

For instance, with the block toolbar issue we were also talking about, if we lower its z-index under the header, it still shows up under other sections of the header that are still transparent:

Screen Shot 2020-10-02 at 8 08 50 PM

**Comment by jeyip** [comment]
**Note:**

The block toolbar overlaps as well, but it is a separate issue with a separate cause. We're only addressing the inserter bug in this PR.

**Review by Addison-Stavlo — APPROVED** [review]
This looks good to me.  Thanks for jumping on it!  😁

**Comment by jeyip** [comment]
Thanks Addie! Waiting on specs to pass and then I'll merge it.

**Review by noahtallen — APPROVED** [review]
Code looks good to me!

**Pull request merged**
