### PR TITLE
Fix arrows navigation in the block more options menu

### LINKED ISSUE #7443: Block More Options menu: arrows navigation doesn't work any longer
Seems to me this is a recent regression, noticed for the first time at WCEU contributor day. To reproduce:

- Tab to the More Options ellipsis menu in a block or click directly on it
- the menu opens
- focus is correctly set on the first menu item

screen shot 2018-06-21 at 17 53 28

- at this point, try to use down and arrow keys to navigate the menu: nothing happens
- pressing Tab works
- press Tab to move to the second item
- try again the down and arrow keys
- arrows navigation works only on the last three items
- expected: it should work since the beginning, starting from the first menu item

### PR DESCRIPTION
**Pull request by afercia**
## Description

Fixes the arrows navigation in the blocks More Options menu after recent changes in #7199 

The new slot/fill implementation of the first menu item broke arrows navigation, for more details please refer to the related issue #7443 

This PR tries to fix it passing the `deep` prop, which makes the menu get also the focusable element that are not direct children of the menu.

Also, to make sure the `<div>` element used by Slot is ignored by assistive technologies and the accessibility tree is "flattened" and made only by menu > menuitem, it uses a `role="presentation"` on the div. As with all the ARIA things, this doesn't affect anything for browsers as it's only used by assistive technologies. See the ARIA Authoring Practices, where `role="none"` (alias of `presentation`) is used to flatten the tree:
- https://www.w3.org/TR/wai-aria-practices/#menu
- https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html
- https://www.w3.org/TR/wai-aria-1.1/#presentation

Ensuring to flatten the tree structure is important for the way assistive technologies perceive a menu, for example one of the reasons is they calculate and announce the number of items in the menu and their position:

screenshot 11

## How has this been tested?
- npm test and updated snapshots
- tested with different browser / screen reader combos

To test:
- open a block More Option menu either by clicking on it or using the keyboard
- using the arrow keys, navigate through the menu items and check navigation works correctly

Fixes #7443

### CODE REVIEW

**Comment by aduth** [comment]
@youknowriad Do you happen to recall the context for why `deep` was needed as part of its introduction in #3303 ? I think we should just remove the prop and have this be its default behavior.

**Comment by youknowriad** [comment]
@aduth I don't think there was a strong argument for it. It was just incidental to the fact that we have several levels of containers sometimes. And adding `role="representation"` is not always the answer because of the fact that the components should be independent from each other and sometimes adding a `role="representation"` to a DOM element should be a decision made within the component as a standalone unit instead of adding it just to satisfy the fact that the component is wrapped with a menu which can be true now, but since the component is reusable might not be always the case.

**Review by aduth — APPROVED** [review]
Pushed c8f558f to remove the `deep` prop. LGTM if LGTY.

**Comment by afercia** [comment]
For reference: the div with role-presentation could go away if https://github.com/WordPress/gutenberg/pull/7231 gets merged.

**Pull request merged**
