### PR TITLE
Add block toolbar button margin

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Addresses issue #19018 according to the design suggestions by @shaunandrews .  

* This PR adds 2 px of margin to the buttons inside the block editor components toolbar.

* Lingering Design Question:  Do we want that padding in the block-mover buttons or not?  (see screenshots below)

The specificity required to achieve this without effecting other buttons in the editor was used as: `.block-editor-block-toolbar .components-toolbar .components-button`

However, this specificity also effected the buttons inside the block mover which I have removed with equivalent specificity via the cascading behavior `.block-editor-block-toolbar .block-editor-block-mover .components-button`

## How has this been tested?

Tested on local docker environment.

## Screenshots 
**Before**
Screen Shot 2020-01-16 at 3 56 15 PM

**After**
Screen Shot 2020-01-16 at 3 55 27 PM

**Padding in block-mover buttons**
Screen Shot 2020-01-16 at 3 55 18 PM

**No padding in block-mover buttons (current state of PR)**
Screen Shot 2020-01-16 at 3 57 04 PM

## Types of changes

Minor style change (non-breaking change which fixes an issue).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by mapk** [comment]
I do like the added space between the buttons and the toolbar, but is there a way we can do this without making the toolbar bigger? Many users dislike the way the toolbar overlaps content, and I'd rather not make that more difficult for them.

I adjusted the CSS a bit, but it's still not right because there's a fuzzy corner issue now.

`box-shadow: inset 0 0 0 1px #fff, inset 0 0 0 2px #555d66;`

hover 2020-01-16 19_17_39

**Comment by youknowriad** [comment]
in #19344 the design is changing drastically. Do you think we should wait until we land that refactor?

**Comment by shaunandrews** [comment]
I generally like the changes in this PR. 👍 

> but is there a way we can do this without making the toolbar bigger?

As part of the G2 #19344 design work, one of the changes suggested was making the toolbars bigger. I had the same reaction (Noo! Not bigger!) but over time, I think having larger tap targets is helpful and would line up to a larger overall grid. With the updated block UI design, things get simpler overall and I don't see a larger toolbar getting is the way as much.

**Comment by chrisvanpatten** [comment]
Agreed with @youknowriad — #19344 is getting really close to getting landed and it seems like it would be better to hold off on smaller changes like this, which may not be necessary in a week or two.

**Comment by Addison-Stavlo** [comment]
Thanks for the responses all!  Will wait on #19344 to land before going any further here.

**Comment by Addison-Stavlo** [comment]
Closing this as the issue was fixed via the other PR.

**Pull request closed without merging**
