### PR TITLE
Use tertiary variant on Link Control cancel button 

### PR DESCRIPTION
**Pull request by getdave**
## What?

Implements feedback in https://github.com/WordPress/gutenberg/pull/47309#issuecomment-1398111009

## Why?

Must match design in https://github.com/WordPress/gutenberg/issues/47310

## How?

Use ~`link`~ `tertiary` variant on button component for Cancel button

## Screenshots or screencast 

Screenshot 2023-01-20 at 17 49 52

### CODE REVIEW

**Comment by jasmussen** [comment]
No I meant the tertiary style, not the link variant. CC: @jameskoster

**Comment by getdave** [comment]
**Question**: the design shows no underline on the button by default. However that is not the default state of the `<Button>` component. 

Please advise.

**Comment by jasmussen** [comment]
We usually pair a primary button with a tertiary button:

Screenshot 2023-01-20 at 10 45 45

It should be no different here.

**Comment by getdave** [comment]
Ah yes thank you 👍  I just realised I was using the `link` variant which I assumed was what we were looking to use. Just learnt we have a `tertiary` variant that matches the design.

**Review by jasmussen — APPROVED** [review]

**Pull request merged**
