### PR TITLE
Fix typo in block.json schema

### PR DESCRIPTION
**Pull request by t-hamano**
## What?
Fix typo in block.json schema. There is no impact on the code.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thanks, @t-hamano!

**Comment by t-hamano** [comment]
When I merged this PR, I got an error message (I think it was something like "merge failed").
Curiously, the PR has been merged into trunk and the changes are reflected, but the status remains unresolved. I would like to close this PR as merging again may cause problems.

pr

**Comment by t-hamano** [comment]
@Mamaduka 
Have you ever encountered a case like this? As it is, it may not get on the Gutenberg milestone or changelog, but this PR is a very minor typo correction, so if there are no problems, I will leave it closed.

**Comment by Mamaduka** [comment]
I've seen a similar error before, but it usually got resolved after I refreshed the page.

**Pull request closed without merging**
