### PR TITLE
Reducer for user specific data

### PR DESCRIPTION
**Pull request by notnownikki**
This is so they are populated when editing exisitng posts as well as creating new posts.

### CODE REVIEW

**Comment by notnownikki** [comment]
Fixes https://github.com/WordPress/gutenberg/issues/1897

**Review by westonruter — CHANGES_REQUESTED** [review]
I don't think this is the right action, because whenever I save a post it causes the list of recent blocks to get reset. For example, if I add a Custom HTML block, then I hit the inserter again and I see it listed at the top in the recent blocks. Then if I hit Save, the Custom HTML block is then removed from the inserter unexpectedly.

**Comment by notnownikki** [comment]
Gah, I guess I need to add debug code to see the actual lifecycle of a post. Thanks for spotting that.

**Comment by notnownikki** [comment]
I think we need to dispatch a new action called 'LOAD_USER_PREFERENCES' which will let this reducer populate the recently used blocks (and in the future, let other reducers load user preferences from an API and apply them).

@mtias @nylen I'd like your input on this too, it seems like we need that action here, even though it's not loading the state of recently used blocks from any API right now, it feels like the right type of action to do it in.

**Comment by notnownikki** [comment]
I've added a `userData` reducer which handles the `LOAD_USER_DATA` action. This is populating user specific data such as editor preferences (when they arrive) and block usage data. Right now, the block usage data isn't persisted using an API, but with this reducer gives us a place to insert that behaviour.

@aduth @nylen @mtias would you mind taking a look too? This will impact how we implement user preferences

**Review by aduth — APPROVED** [review]
This will need some more thought around what we expect a payload for user preferences to look like. For example, I'd expect the `LOAD_USER_DATA` to not be handled by the reducer, but instead an effect which loads data from the API, or even in the meantime, just dispatch a follow-up action with the simulated recent blocks, to at least get a sense of the structure of user preferences.

In the meantime, however, I think this is a good step in resolving the issue with existing posts and moving user data out of the editor undoable history.

**Comment by notnownikki** [comment]
"How to do async stuff in a reducer" was my next thing to learn, looks like you answered that question for me, @aduth :smile:

**Pull request merged**
