### PR TITLE
Refactor: Remove post actions hook.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
As a follow-up to the discussions that happened at https://github.com/WordPress/gutenberg/pull/60754#pullrequestreview-2006281765.
This PR does the following refactors:

- Removes the usePostActions hook and exports a postActions object with the questions.
- Makes all the actions action objects and not hooks.
- In order for the callbacks of actions to access the store the callback of the action can now return a function that receives {registry, select, and dispatch} like our store actions.
- Adds an onActionPerformed function to the action API.
- Passes the action itself to the RenderModal so it can access onActionPerformed.
- Adds a WordPress data dependency on dataviews.

cc: @youknowriad, @ntsekouras.

## Testing Instructions
I tried to use the the actions on dataviews (pages, templates on patterns) as single action and as bulk actions and verified things work.
I tried to use actions on the post editor for a post and on the site editor inspector and details panel for a page and checked thins still work.

### CODE REVIEW

**Review by mcsf — COMMENTED** [review]
Preliminary thoughts:

* Overall, an improvement for sure. Seems like the right direction, so don't take my next comments as blockers.
* On one hand, I like the "transparency" of dealing with a simple structure, like the `action` object and the `action.callback` function. On the other hand, it doesn't feel great to need to do the thunk-like juggling (`if ( typeof returnResult === 'function' ) {`) across three different files whenever we call the callback.
  * That makes me wonder if we'll want to delegate the actual calling of the callback to some central system (but which? something like `editorActions.dispatch( action )`?)
  * I was so thirsty for a more consistent solution that I even wondered — and forgive the blasphemy — if we'd be better off with actions as class instances (`class EditPostAction extends Action`)? 🙈 But this would disrupt the convenience of wrapping functions (`onActionPerformed: ( ...args ) => {`), forget it.
* Even as I type this, I realise that I'm mixing up `action.onActionPerformed` and `action.callback` throughout the diff. That's something to work on.
* And speaking of confusion, even though it doesn't come from this PR, I can't help but notice that we are setting up our readers for confusion in a few subtle ways, like naming:
  * In a file where there are two main "entities" (Data Views **items** and **actions**), we see identifiers like `BulkActionItem`. I have to think twice whenever I return to this branch.
  * I also sense we are repeating work in some places, like how some cascading components each compute `eligibleItems`.

**Comment by jorgefilipecosta** [comment]
Thank you a lot for the review @mcsf!

> On one hand, I like the "transparency" of dealing with a simple structure, like the action object and the action.callback function. On the other hand, it doesn't feel great to need to do the thunk-like juggling (if ( typeof returnResult === 'function' ) {) across three different files whenever we call the callback.

It is definitively not great, but that is internal for an extender that complexity is not seen. It is a thunk-like implementation. I will try to make it more abstracted with a function executeAction( action ) that may be reaped on two places dataviews and editor but at least that complexity is localized and not on click handlers.

> That makes me wonder if we'll want to delegate the actual calling of the callback to some central system (but which? something like editorActions.dispatch( action )?)

This mechanism needs to be shared between the dataviews and editor package and it is not obvious the package where it could reside.

> Even as I type this, I realise that I'm mixing up action.onActionPerformed and action.callback throughout the diff. That's something to work on.

What do you think we can do here? Naming changes or do you have another improvement in mind?

> I also sense we are repeating work in some places, like how some cascading components each compute eligibleItems.

It seems we have a case where it happens and computation of eligible items could be reused in packages/dataviews/src/bulk-actions.js. I will address this in a parallel PR if there is other cases let me know.

**Comment by Mamaduka** [comment]
Would it make sense to have a `registerPostAction|unregisterPostAction` API for managing the post actions?

It could have a special flag for core actions that can't be removed, but developers could add, remove or extend actions. This would also be useful for requests like https://github.com/WordPress/gutenberg/pull/60637#issuecomment-2075839979 and #61083.

**Comment by jorgefilipecosta** [comment]
Closing this PR as we end up going another path at https://github.com/WordPress/gutenberg/pull/61520.

**Pull request closed without merging**
