### PR TITLE
Switch from UglifyJS to Terser to build the polyfill script

### PR DESCRIPTION
**Pull request by jsnajdr**
Webpack and other tools switched from UglifyJS to Terser several years ago, but our script for bundling the `polyfill` script still uses UglifyJS. This PR switches to latest version of Terser.

Terser-minified files are around 1% bigger that uglified ones. I've seen this elsewhere, too. But I guess it's worth using the same minifier consistently.

I fixed the condition that preserves license comments to also catch a lowercase `"license"` string. Then the minified `polyfill.min.js` has a license comment at the beginning.

**How to test:**
`cd packages/babel-preset-default` and run `npm run build`. The build files are in the package's `./build` subfolder.

I'm not sure if and how this script is ran during Gutenberg build. Maybe only Core builds the polyfill?

### CODE REVIEW

**Review by tyxla — APPROVED** [review]
Looks good ✅ 

Fixed core-js comment is there as expected:

Screenshot 2024-09-12 at 14 48 44

Any default terser settings differ from the uglifyjs ones? Maybe it's worth checking.

> I'm not sure if and how this script is ran during Gutenberg build. Maybe only Core builds the polyfill?

Yes it is. It's part of `wp-scripts build` / `wp-scripts start`. See:

https://github.com/WordPress/gutenberg/blob/cc133bfae5fe1b575e754fbcd71ff3505a448a35/packages/scripts/config/babel-transform.js#L10

and:

https://github.com/WordPress/gutenberg/blob/cc133bfae5fe1b575e754fbcd71ff3505a448a35/packages/scripts/config/webpack.config.js#L177

**Comment by jsnajdr** [comment]
> Yes it is. It's part of wp-scripts build / wp-scripts start. See:

@tyxla what you're linking to are usages of the Babel preset. I.e., the `index.js` file. But the `bin/index.js` script is independent, and I'd say the polyfill is not very related to the Babel preset. It looks random that it's a part of this package and not a part of another.

**Review by sgomes — APPROVED** [review]
LGTM, the file built correctly, and the file size is similar 👍

This also prepares us for a feature where polyfill code is not written in ES5.

Great work, @jsnajdr! 🙌

**Comment by tyxla** [comment]
> @tyxla what you're linking to are usages of the Babel preset. I.e., the `index.js` file. But the `bin/index.js` script is independent, and I'd say the polyfill is not very related to the Babel preset. It looks random that it's a part of this package and not a part of another.

Hmm yes, you're right. I don't see an immediate direct usage of the script itself. Maybe the script was there solely to quickly test the package functionality, like we did for this PR.

**Comment by jsnajdr** [comment]
> Hmm yes, you're right. I don't see an immediate direct usage of the script itself.

I finally found how it's used:
1) The polyfill script is built as part of `npm run build:packages`
2) The Gutenberg plugin itself doesn't use it, but Core uses it for the `wp-polyfill` script: https://github.com/WordPress/wordpress-develop/blob/47122105f20624e5a6b8ed151d732157f2f2605c/tools/webpack/packages.js#L84

**Pull request merged**
