### PR TITLE
Fix 'Multi entity saving -> site editor' e2e failures.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Should fix the e2e failures in multi-entity-saving tests.  Oddly `insertBlock( 'Template Part' )` doesn't seem to work consistently anymore (not sure why, manual flow seems to work fine still).  Since we just needed to add something/anything to dirty the editor, changing this to a paragraph block seems to fix the test.

## How has this been tested?

Ensure CI e2e checks don't fail on multi-entity-saving tests.

Run `npm run test-e2e:watch` locally and run the `multi-entity-saving` file.  Verify tests pass.
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jeyip** [comment]
I came to the exact same conclusions as you have @Addison-Stavlo . What a strange issue 😕 

I was reluctant to open a PR to fix the issue by replacing the block we insert, but now that I think more about it, I agree that this is useful to unblock e2e tests in general.

I'm still concerned about the template part insertion failure. I think it would be worthwhile to create a separate issue (happy to handle that), but I'm curious what your thoughts are.

**Review by jeyip — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
> I'm still concerned about the template part insertion failure. I think it would be worthwhile to create a separate issue 

Yeah, im a bit confused by it as well.  The template-part tests that go through inserting seem to be working still. 🤔

**Comment by noahtallen** [comment]
It's possible that we used a second template part block to test nested template part block insertion & dirty states, but I kinda forget :)

**Comment by talldan** [comment]
Something that might have made the results in this PR confusing is that I'd already made some changes to the test in https://github.com/WordPress/gutenberg/pull/26341 which was merged before this. It seems to have been passing ok since #26341 in commits to `master` so the change here might not have made much difference.

I definitely observed the same thing, that Template Parts couldn't be inserted. I changed the test to first close the navigation panel (seems unusual, but it wouldn't work without this), and also click a block in the editor before inserting. My feeling was that the inserter was possibly attempting to insert the Template Part somewhere it couldn't be, but when trying out things manually it always worked.

Still, I don't really understand the FSE flow that much yet having not worked on it, so happy for the tests to be changed to something more logical.

**Comment by Addison-Stavlo** [comment]
>  It seems to have been passing ok since #26341 in commits to master so the change here might not have made much difference.

Oh interesting!  I noticed they weren't failing on github, but running locally after that change I was still seeing them fail at the block insertion step.  🤷‍♀️  It seems difficult to get local e2e to give the same results as the CI checks sometimes... 🤔

**Pull request merged**
