### PR TITLE
[RNMobile] Fix UBE Text Selection Bug on Android

### LINKED ISSUE #3862: UBE: Android text selection toolbar is blocking access to dropdown menus
### Expected behavior
I expected the Android text selection toolbar to be dismissed after clicking the page menus so the results from the user's last action would be fully accessible.

### Actual behavior
Android text selection toolbar is not dismissed and blocks the access to the 'more settings' and to the 'options' dropdown lists.

### Steps to reproduce the behavior
1. Open a post with unsupported blocks (p2/task in this case)
2. Click on the question mark in the block
3. 'Edit using web editor'
4. Select part of the tex
    * Android text selection toolbar is displayed
5. Click the chevron icon to expand the edition options
6. Try to select 'Inline code'
    * Expected: By clicking outside the Android text selection toolbar it should be dismissed and the result of the user's last action would be completely accessible.
    * Observed: Android text selection toolbar is not dismissed and the 'Inline code' is not accessible.

##### Tested on Samsung Galaxy Note20, Android 11, WPAndroid 18.0-rc-2 and Play Store version (17.9.1)
https://user-images.githubusercontent.com/42008628/129751141-0d9c2b0d-d2dd-4e30-bb3c-196842b8d62c.mp4

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3862

* gutenberg-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3937
* wordpress-android: https://github.com/wordpress-mobile/WordPress-Android/pull/15304

## Description

As outlined in more detail at https://github.com/wordpress-mobile/gutenberg-mobile/issues/3862, the floating toolbar that appears when text is selected blocks access to dropdown menu items in some cases. This is specific to the Unsupported Block Editor (UBE) and can prevent users from being able to format their text selection.

With this PR, the text selection toolbar is now correctly dismissed when a "parent" menu item is tapped in the UBE's main toolbar, so users will always be able to access the dropdown menu items.

## How has this been tested?

1. In a browser, add a block that's unsupported in the apps to a post e.g. the [timeline block](https://wordpress.com/support/wordpress-editor/blocks/timeline-block/) on a WordPress.com site.
2. In the Android app, open the post, tap the question mark alongside the unsupported block, and then **Edit using web editor**.
3. Enter some text into the UBE and select some of it, so that the text selection toolbar pops up.
4. Tap the chevron icon in the toolbar to view the formatting options in the dropdown menu.
     * Before fix: The text selection toolbar is not dismissed when the icon is tapped, making some of the menu items inaccessible.
    * With fix: The text selection toolbar is dismissed when the icon is tapped.

## Screenshots 

You'll see that the text selection toolbar is now being correctly dismissed, while maintaining the selection.

https://user-images.githubusercontent.com/2998162/133992368-6ba74d09-f0e1-4b42-aca1-728748565f00.mov

## Types of changes

This PR introduces a bug fix (a non-breaking change which fixes an issue), with the following high-level notes on the code changes:

<details><summary>Initial solution, before refactor:</summary>

* From initial research described at https://github.com/wordpress-mobile/gutenberg-mobile/issues/3862#issuecomment-905021557, I determined that there needed to be some kind of "action" on the selected text in order for the toolbar to be dismissed.  
* [JavaScript's setBaseAndExtent method](https://developer.mozilla.org/en-US/docs/Web/API/Selection/setBaseAndExtent) enables changes to the range of selected text. With this PR, the method's used to reset the text selection (using the original range). This has the effect of removing the text selection toolbar, by dispatching an "action" of sorts, while maintaining the original selection/range.
* This feels like a very hack response that requires the dropdown menu to be tapped twice, as it's dismissed along with the text selection toolbar. I'd be keen to hear other thoughts.</details>

<details><summary>Updated, current solution:</summary>

* A function named `hideTextSelectionContextMenu` is used to [notify the Android side of the codebase](https://github.com/WordPress/gutenberg/pull/34668/files#diff-68f745abbbac9d9a1951418eb41094e55ff3b2635444d3f8bc1d26802961ada9R23) when buttons impacted by the bug are tapped. 
* Android's ActionMode hides text selection toolbar whenever the `hideTextSelectionContextMenu` function is called. More specficially, [ActionMode's `finish` method](https://developer.android.com/reference/android/view/ActionMode#finish()) is utilised to remove the toolbar. 
* The changes in https://github.com/WordPress/gutenberg/pull/34668/commits/4f1ca312d1e5a96165d620cbf8c7f1f404bb3b41 prevent the need for the dropdown menu to be tapped a second time after the text selection toolbar is dismissed.
</details>

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by SiobhyB** [comment]
@fluiddot, would you maybe have the time to review this PR this week? I've attempted to outline the reasoning behind the changes as clearly as possible, but it's also a pretty hacky fix and I'd be happy to clarify anything (via Zoom or text) if needed. 

I've also generated an installable build that's available at https://github.com/wordpress-mobile/WordPress-Android/pull/15304/#issuecomment-915939893.

**Comment by fluiddot** [comment]
> @fluiddot, would you maybe have the time to review this PR this week? I've attempted to outline the reasoning behind the changes as clearly as possible, but it's also a pretty hacky fix and I'd be happy to clarify anything (via Zoom or text) if needed.
> 
> I've also generated an installable build that's available at [wordpress-mobile/WordPress-Android#15304](https://github.com/wordpress-mobile/WordPress-Android/pull/15304).

Sure, I'll spare some time this week to review it 👍, I'll also assign myself as a reviewer.

**Comment by SiobhyB** [comment]
@fluiddot, I've refactored this PR, following our Zoom, to utilise [Android's ActionMode](https://developer.android.com/reference/android/view/ActionMode) and the installable build can be found [here](https://github.com/wordpress-mobile/WordPress-Android/pull/15304). 

I initially tried using [the `hide` method](https://developer.android.com/reference/android/view/ActionMode#hide(long)), but realised that this will only ever hide the menu for a few seconds, no matter what number is passed. I took a screen recording to show the menu displaying again after just a few seconds, despite the fact I'd passed 10000 (10 seconds) to the method:

https://user-images.githubusercontent.com/2998162/135236004-6eb3c4cc-b1b8-4e2f-aaff-573a26275565.mov

This limitation of `hide` is also backed up in the documentation:

> NOTE that there is an internal limit to how long the mode can be hidden for. It's typically about a few seconds.

`finish` was the only method that did the job fully for me, though it still means that the menu items need to be tapped twice when there's a text selection. I experimented a little with ways around this (such as using JavaScript's `click()` method) but couldn't quite get this working.

Let me know if you think there's still a way that we could prevent the need for two taps here, I'd love to get it working without that quirk, if possible. 🙇‍♀️  If it's not possible, I think two taps would still be a better experience than the current blocking behaviour.

**Comment by fluiddot** [comment]
> @fluiddot, I've refactored this PR, following our Zoom, to utilise [Android's ActionMode](https://developer.android.com/reference/android/view/ActionMode) and the installable build can be found [here](https://github.com/wordpress-mobile/WordPress-Android/pull/15304).
> 
> I initially tried using [the `hide` method](https://developer.android.com/reference/android/view/ActionMode#hide(long)), but realised that this will only ever hide the menu for a few seconds, no matter what number is passed. I took a screen recording to show the menu displaying again after just a few seconds, despite the fact I'd passed 10000 (10 seconds) to the method:
> 
>  UBE.hide.recording.mov 
> This limitation of `hide` is also backed up in the documentation:
> 
> > NOTE that there is an internal limit to how long the mode can be hidden for. It's typically about a few seconds.

Thanks for trying the approach with the `hide` function, I didn't have too much hope on that option but it was worth trying it, too bad it didn't work 😞 .

> `finish` was the only method that did the job fully for me, though it still means that the menu items need to be tapped twice when there's a text selection. I experimented a little with ways around this (such as using JavaScript's `click()` method) but couldn't quite get this working.
> 
> Let me know if you think there's still a way that we could prevent the need for two taps here, I'd love to get it working without that quirk, if possible. 🙇‍♀️ If it's not possible, I think two taps would still be a better experience than the current blocking behaviour.

I explored the idea you had about automatically clicking the button when hiding the floating bar and I implemented it in [this commit](https://github.com/WordPress/gutenberg/pull/34668/commits/4f1ca312d1e5a96165d620cbf8c7f1f404bb3b41). So far looks like addresses the issue and doesn't require the double-tap 🎊 . It would be great if we test it further and if it goes well, I think we could wrap up the PR and merge it.

**Comment by SiobhyB** [comment]
@fluiddot, thanks so much for this 🙇‍♀️ I created [a new installable build here](https://github.com/wordpress-mobile/WordPress-Android/pull/15304#issuecomment-915939893) and tested it on a physical Pixel 5. It worked well, with a slight flicker, which we discussed isn't avoidable with this approach. I didn't find it jarring, though, and think it seems like a good solution.

**Comment by fluiddot** [comment]
@SiobhyB I've implemented a new approach because I noticed that for some of the dropdown menus the last solution I implemented wasn't hiding the floating menu. For the new solution, I refactored a bit the code and now instead of listening to focus events, we listen to clicks. This way we can prevent the propagation of the event and delay the click right after the context menu is hidden, which prevents flickering. Besides, I added listeners to know when the context menu is visible and only override the click event if it's being shown.

I've tested further and I think this could be definitive solution for this 🤞 , nevertheless, I'd appreciate it if we could test it again before approving it. Let me know your opinion regarding this approach and if you'd like to continue with it. Otherwise, I'll be more than happy to revert it and go with the previous approach 👍 .

**Comment by SiobhyB** [comment]
@fluiddot, sorry I didn't get back to you yesterday! I wanted to make sure I took the time to understand the changes that have been implemented. I've done that now and it all makes sense to me, I also created [another installable build](https://github.com/wordpress-mobile/WordPress-Android/pull/15304#issuecomment-915939893) and confirmed all works super smoothly on my Pixel 5 🎉  

To tie things up, I created the issue for the mobile web at https://github.com/WordPress/gutenberg/issues/35447, as we discussed.

I'm happy to ship this if you are now, too :D

**Comment by fluiddot** [comment]
> @fluiddot, sorry I didn't get back to you yesterday! I wanted to make sure I took the time to understand the changes that have been implemented. I've done that now and it all makes sense to me, I also created [another installable build](https://github.com/wordpress-mobile/WordPress-Android/pull/15304#issuecomment-915939893) and confirmed all works super smoothly on my Pixel 5 🎉

No worries, I'm happy to see that works smoothly 😊. If you have any doubt about the changes I made please let me know, I'll be more than happy to jump into a quick call to explain them.

> To tie things up, I created the issue for the mobile web at #35447, as we discussed.

Awesome, thanks for creating the issue 🙇 .

> I'm happy to ship this if you are now, too :D

Yeah, I'm going to do a final review as double-check but I think we already tested enough to merge it.

**Review by fluiddot — APPROVED** [review]
LGMT 🎊 !

_Tested on Simulator - iPhone 12 Pro Max (iOS 14.5) and Samsung Galaxy S20 FE 5G (Android 10)._

**Comment by SiobhyB** [comment]
Thanks so much for all your support on this one, @fluiddot 🙇‍♀️ 

I'll go ahead with the merge domino! :D

**Pull request merged**
