### PR TITLE
Gallery Block: Use better key for gallery list items

### LINKED ISSUE #30473: Gallery Block: Identical Images Get Duplicated When Moving
## Description

When adding the same image to a gallery block, moving adjacent images will duplicate that image multiple times.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Add a gallery block
2. Add two images that are the same next to each other.
3. Try and use the arrows on an adjacent image to move it over.
4. Watch the  other image take over the gallery.

## Expected behaviour

The images to just swap positions normally.

## Actual behaviour

Another image was duplicated instead. 

## Screenshots or screen recording (optional)

Easier to see with this:

ezgif com-optimize

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Twenty Twenty One

## Device information
- Operating system:  Mac OS 11.2.3
- Browser:  Chrome 89.0.4389.114 || Firefox 86.0.1 (

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Galleries can have the same image listed more than once. Users can do this by editing individual items and selecting the image that's already in the gallery. In this case, image ids can't be used as unique key props.

Fixes #30473.

## How has this been tested?
1. Add a gallery block
2. Add two images that are the same next to each other.
3. Try and use the arrows on an adjacent image to move it over.
4. Duplicated images shouldn't replace other images.
5. Following error shouldn't appear in the browser console:

```
Warning: Encountered two children with the same key, `[image.id]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

## Types of changes
Bugfix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hello, @glendaviesnz

Is this something we can merge before gallery block refactoring?

**Review by glendaviesnz — APPROVED** [review]
This tested well for me. 

The only thought I had was whether it was possible on a slow connection with a large image to end up with two images with the same temporary url as the key, but as far as I can tell it is impossible to insert an image again from the media library until it is fully uploaded, at which point it has an id, so I don't think there is any need to also append `index` to the fallback url key.

I also pinged @mkevins re the native side and he thinks this change is fine on the mobile side.

There is nothing to stop this being merged ahead of the gallery refactor PR. We will just pull this change into the deprecated v1 gallery code in that PR when we do another pull from trunk before merge.

**Comment by glendaviesnz** [comment]
@Mamaduka it doesn't look like the e2e test failures are related but you might want to just double check those.

**Comment by Mamaduka** [comment]
Thanks for the review, @glendaviesnz

**Comment by mkevins** [comment]
Thanks for checking and updating the `*.native.js` file @Mamaduka :smile: :+1:

**Pull request merged**
