### PR TITLE
Add manage with live preview link

### LINKED ISSUE #26244: Widgets Screen: Provide 'Manage with Live Preview'
**Is your feature request related to a problem? Please describe.**
With the Legacy Widget editor there was the 'Manage with Live Preview' which would take you to the Customizer > Widgets screen.
Screen Shot 2020-10-16 at 5 26 15 PM

**Describe the solution you'd like**
This screen still exists so we should provide the same link.

One concern is you can't really edit block widgets from the Live Preview it takes you back to the widgets screen.

### PR DESCRIPTION
**Pull request by draganescu**
## Description

Fixes #26244

This small PR proposes a place for the manage with live preview button, which allows users to switch between the customizer and the stand along widgets editor.

## How has this been tested?

1. Go to Appearance > Widgets
2. Without anything selected, in the sidebar (inspector) notice the Manage with live preview button

### The old button

Screen Shot 2020-10-16 at 5 26 15 PM

### The new button

Screen Shot 2021-03-12 at 22 02 49

## Types of changes

Adds one button to the widgets complimentary area. Non breaking change.

### CODE REVIEW

**Comment by draganescu** [comment]
@shaunandrews do we have a better idea of where to place this?

**Comment by shaunandrews** [comment]
I'm not sure we even need this button. We don't have it in the new Menu's screen, either.

However, if we do think we need it perhaps it can look more like a link (tertiary button):

image

**Comment by draganescu** [comment]
@shaunandrews made it tertiary it now looks like this:


https://user-images.githubusercontent.com/107534/112030719-36990600-8b43-11eb-874a-2989267b6656.mp4

**Review by youknowriad — APPROVED** [review]
For me it's a link, so why not just show a regular link. That said, I'll leave that to the designers @shaunandrews

**Comment by noisysocks** [comment]
> I'm not sure we even need this button. We don't have it in the new Menu's screen, either.

I am also not sure we need this.

Here is the ticket for originally adding this button: https://core.trac.wordpress.org/ticket/28032. It was intended to onboard existing users to the Customizer and was intended to be temporary as the thought was that the Widgets screen would be removed one day.

**Comment by draganescu** [comment]
Well, yes, but the screen has not been removed, the link has been there in the old screen for ages, there is an obvious thing sill missing from the new editor (preview) and the link is still needed for folks that land here and don't know about the powers in the customizer :)

As I also said [here](https://github.com/WordPress/gutenberg/issues/26244#issuecomment-802713720) I still think we need to keep these detail level features if we don't solve their original problem.

**Pull request merged**
