### PR TITLE
Avoid using CSS variables for block gap styles

### LINKED ISSUE #36521: Block Spacing setting causes conflict with blockGap (Columns, Navigation, etc.)
### Description

When `blockGap` is enabled on a theme, the "Block Spacing" setting is enabled for a number of blocks, notably Columns and Navigation. With `blockGap`, the following CSS is added, which adds "block gap" via a `margin-top: var( --wp--style--block-gap );` to each block. (There are separate issues with this, which I will detail in another issue)

image

Now if you apply the "Block Spacing" setting to, for example, the Columns block, the setting will override the `margin-top` applied by the CSS above. This is confusing. As a user, I would expect the "Block Spacing" setting to control with space between each column, not the top margin on the Columns block itself, especially since the Columns block supports the margin dimension.

The conflict is due to the "Block Spacing" setting applying its own `--wp--style--block-gap` variable. You can see that here:

image

Since the main `blockGlap` CSS also uses this variable to control the vertical distance between blocks, it gets overridden by the "Block Spacing" setting.

### Step-by-step reproduction instructions

1. Install emptytheme or Twenty Twenty-Two.
2. Make sure `blockGap` is enabled in theme.json
3. Add a Columns block or Navigation block. 
4. Apply a custom "Block Spacing"
5. See that this setting controls both the space between columns/nav items as well as the `margin-top`.

### Screenshots, screen recording, code snippet

This is what a "Block Spacing" of `4rem` should look like on emptytheme. 

image

This is what it actually looks like. 

image

### Environment info

WordPress 5.8.2, Gutenberg 11.9

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
Closes #36521 

This PR removes the block gap style CSS variable because of the conflicts it creates. We can still keep the variable but only for the "root level" theme.json style config.

**Todo**

 - [x] Update the block specific block gap to not rely on CSS variables (only works for layout based blocks)
 - [x] Update theme.json support to only generate the block gap CSS variable for the root level styles.
 - [x] Update the theme.json per block block gap support: 
     - I think we may forced to drop per block theme.json block gap support because we don't know the chosen layout statically for each block in theme.json (the user could change it and the block gap styles are layout type specific)
 - [x] Ensure Columns block compatibility (PR: https://github.com/WordPress/gutenberg/pull/37436)
 - [x] Ensure Navigation block compatibility (PR: https://github.com/WordPress/gutenberg/pull/37543)

### CODE REVIEW

**Comment by youknowriad** [comment]
> I think we may forced to drop per block theme.json block gap support because we don't know the chosen layout statically for each block in theme.json (the user could change it and the block gap styles are layout type specific)

Is this an acceptable tradeoff for now? I can't see how we could allow it while solving the conflicting issue.

**Comment by jasmussen** [comment]
What's the best way to test it? As a quick superficial test, basics look okay to me:
Screenshot 2021-12-14 at 11 41 32

Screenshot 2021-12-14 at 11 46 31

I did notice a hiccup on the frontend:
Screenshot 2021-12-14 at 11 41 16

And an error in the nav block:
Screenshot 2021-12-14 at 11 46 09

> I think we may forced to drop per block theme.json block gap support because we don't know the chosen layout statically for each block in theme.json (the user could change it and the block gap styles are layout type specific)

Can you expand on the consequences of this? Does that mean I won't be able to do this?

```
			"core/navigation": {
				"spacing": {
					"blockGap": "48px"
				}
			},
```

**Comment by ndiego** [comment]
This is a tough one. I really like the simplicity of the CSS variables, but I cannot think of an alternative solution to this PR other than even more CSS variables like https://github.com/WordPress/gutenberg/pull/35454. But introduces other questions/potential issues. 

I will give this PR a thorough test today!

**Comment by carolinan** [comment]
> > I think we may forced to drop per block theme.json block gap support because we don't know the chosen layout statically for each block in theme.json (the user could change it and the block gap styles are layout type specific)
> 
> Is this an acceptable tradeoff for now? I can't see how we could allow it while solving the conflicting issue.

I think it is acceptable, there is still the ability to add top margins if needed.

**Comment by youknowriad** [comment]
@oandregal @jorgefilipecosta I'd appreciate some help on the two remaining todo list items here when you have time :)

**Comment by ramonjd** [comment]
Thanks for kicking this off! 🙇 

I took a look at the following blocks:

1. Social links
2. Buttons
3. Navigation
4. Columns (needs to opt-in to `__experimentalLayout.default.type.flex`)

Social links and Buttons work pretty well out of the box!

> Update the block specific block gap to not rely on CSS variables (only works for layout based blocks)

I might be wrong, but I guess we'd have to modify the CSS for [Columns](https://github.com/WordPress/gutenberg/blob/feb915f8d789b1a36f6fac92114055df97d8afcf/packages/block-library/src/columns/style.scss) and [Navigation](https://github.com/WordPress/gutenberg/blob/075207b54d12f04c31be58e0009e744de4c71519/packages/block-library/src/navigation/style.scss), which rely on the block style `spacing.blockGap` (now [ignored](https://github.com/WordPress/gutenberg/pull/37360/files#diff-292053c9ec98ebdd73943767587e8093315ad3a2bf01ca3b5352efc48326becdR77)) and the value of `--wp--style--block-gap`  to control not only gap but margins as well. 

Columns is not yet a layout based block, so it might have to opt-in to `__experimentalLayout` and look at replacing the margin values formerly defined by `--wp--style--block-gap`.  cc @andrewserong for thoughts.

Happy to help out here as this PR evolves.

**Comment by youknowriad** [comment]
Indeed @ramonjd blocks that don't use the "layout support" won't be able to use block gap anymore. I think that's fine to be honest and we don't need to support per block block gap for these blocks right now but we can iterate on them to add layout support.

It's also fine to leave the CSS variables in their styles if needed as the root CSS variables will still be generated from theme.json

**Review by andrewserong — COMMENTED** [review]
Thanks for digging into this one @youknowriad!

I'm wondering if it's possible to reduce the scope of the change in this PR slightly, so that we can preserve the Columns block blockGap control in the shorter-term so that we can incrementally move to the layout support without dropping the per-block individual control.

Is the root of the problem in #36521 that the rendered Layout style sets for the block's children a value that references the CSS variable? E.g. `$selector > * + * { margin-top: var( --wp--style--block-gap )`? If so, I'm wondering if we can update `gutenberg_get_layout_style` so that it always uses a real value instead of referencing the CSS variable. I was thinking if around line 171 of `layout.php`, if we ensure that `$gap_value` is either the block's `style.spacing.blockGap` value, or the theme's root level `style.spacing.blockGap` value, then `gutenberg_get_layout_style` might never need to reference a CSS variable in its generated styles?

If we can get it to do that, then we might be able to safely retain the inline CSS variable rendering used by the Columns, Buttons and Navigation blocks.

In addition to the Columns styling, the Buttons block also still uses the CSS variable for button width calculation, so it might not be easy to remove the block-level CSS variable entirely. However, with the main margin styles that are applied to children no longer using the CSS variable, in theory it sounds like the conflict might then be resolved?

> It's also fine to leave the CSS variables in their styles if needed as the root CSS variables will still be generated from theme.json

So long as blocks include CSS variables in their styles, I think this means we'll still need to render the inline CSS variable for the blocks to be styled correctly? Apologies if I'm missing some details here, though!

**Comment by youknowriad** [comment]
> so that we can preserve the Columns block blockGap control in the shorter-term so that we can incrementally move to the layout support without dropping the per-block individual control.

Unfortunately I don't think we can.

Basically, we have to keep the root CSS variable as a fallback, otherwise there's no solution for theme.json to define a consistent gap across blocks and layouts (flex, flow...)

The way columns work is that they have custom styles relying on the CSS variable and when the user changes the value of the gap, we update the CSS variable. The problem is that setting that CSS variable causes the parent (often root) container margins to break because of the `> *` selector. 

There are some approaches to solve that for the columns block:

 - Generate custom styles for the columns block when the block gap value changes
 - Rely on an adhoc CSS variable for the columns block's block gap value.

Both these solutions basically mean having custom logic for the block instead of relying on the block support. I think the work needed is probably bigger than refactoring the block to use the layout abstraction.

**Comment by youknowriad** [comment]
> So long as blocks include CSS variables in their styles, I think this means we'll still need to render the inline CSS variable for the blocks to be styled correctly? Apologies if I'm missing some details here, though!

The blocks shouldn't include CSS variables in their styles ideally. The blocks should be relying on the layout block support to generate the right styles for them: if they have a custom block gap value, it will generate styles with that value (no variable), if they don't have a value, it will generate a fallback to the root CSS variable.

For blocks that don't use the layout abstraction yet, they can't have block gap support, they can use the CSS variable in their styles if they want to still consume the "root theme.json block gap" but custom block gap support is not possible.

**Comment by ramonjd** [comment]
Thanks for the explanations @youknowriad 🙇 

> There are some approaches to solve that for the columns block:
>  - Generate custom styles for the columns block when the block gap value changes
>  - Rely on an adhoc CSS variable for the columns block's block gap value.

Without thinking too deeply about it, the adhoc CSS variable approach is very tempting as it might be neater than whatever we'd have to do to set and utilize the block gap value across various Columns Block elements.

I suppose the fallback value would be the value of the root theme.json block gap (if it exists), e.g., from [columns/style.scss:](https://github.com/WordPress/gutenberg/blob/release/12.2/packages/block-library/src/columns/style.scss#L46)

```scss
// Add space between the multiple columns. Themes can customize this if they wish to work differently.
// Only apply this beyond the mobile breakpoint, as there's only a single column on mobile.
&:nth-child(even) {
    margin-left: var(--wp--style--columns-block-gap, var(--wp--style--block-gap, 2em));
}
```


> For blocks that don't use the layout abstraction yet, they can't have block gap support

Just checking, would that include the Columns block? It hasn't opted into `__experimentalLayout`, but if we can something custom working as per your suggestions, we wouldn't need to (?)

**Comment by youknowriad** [comment]
I the our time is better spent moving the columns block to the layout abstraction instead of implementing a "custom block gap" support specific to a given block. Ideally we want consistency across all blocks. At least I believe we should give it a try and see how complex it would be, maybe it's not that hard?

The CSS variables approach suffers from another problem (that I just noticed today in trunk for the general block gap), When you apply it, if you have nested columns blocks, the inner one will get the block gap applied to the outer one.

**Comment by andrewserong** [comment]
> our time is better spent moving the columns block to the layout abstraction instead of implementing a "custom block gap" support specific to a given block. Ideally we want consistency across all blocks. At least I believe we should give it a try and see how complex it would be, maybe it's not that hard?

Thanks for the explanations @youknowriad! You make very good points about consolidating on the block support providing the necessary styling instead of the individual block having its own ad hoc approach. This sounds like a good way for the block support to work to me, and a good direction forward for the API.

My main concern is to ensure that we don't break or lose behaviour for the blocks we've already opted-in to the block gap support (as folks had been wanting gap support for columns and buttons for quite a while). But I'm very happy for us take your lead here and investigate how complex it'll be to switch over the Columns block to using the Layout support. Let's see how it goes!

One other thing for us to keep in the back of our minds as we work on the Layout support is the outstanding issue in https://github.com/WordPress/gutenberg/issues/35376 that the styles are not rendered over the REST API so won't render correctly in the post content block within the editor. We've gotten close a couple of times at coming up with a solution for it, but unfortunately recent attempts for a fix were blocked (for very valid reasons). I don't believe we're close to a fix for it (my [most recent attempt](https://github.com/WordPress/gutenberg/pull/36847) is pretty messy and I'm not sure will be viable, either), so just wanted to flag it in case it winds up being a blocker.

**Comment by MaggieCabrera** [comment]
This PR breaks blocks that define a blockGap in their markup like so:

`<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}},"layout":{"type":"flex","allowOrientation":false,"justifyContent":"space-between","flexWrap":"nowrap"}} -->`

In my experience so far we've needed to do this mostly on row blocks where we want to reset the gap to zero, what would be the best way to do that?

**Comment by youknowriad** [comment]
@MaggieCabrera conceptually, it shouldn't break that use case, maybe it's because the group block doesn't support blockGap officially yet which should happen after #37459 get merged. You can maybe a try a branch with both PRs to see if it still works.

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera conceptually, it shouldn't break that use case, maybe it's because the group block doesn't support blockGap officially yet which should happen after #37459 get merged. You can maybe a try a branch with both PRs to see if it still works.

you are right and the markup does work on blocks that support it, thank you!

**Comment by youknowriad** [comment]
I think we should merge this today (before beta4 for 5.8), I wouldn't want to include a broken block gap implementation in 5.8. Potentially we can also include the columns block refactor if it's deemed ready to keep the block gap support for columns block, alternatively we can temporarily remove the block gap control from that block.

**Comment by ndiego** [comment]
Just catching up on this PR. 

> Potentially we can also include the columns block refactor if it's deemed ready to keep the block gap support for columns block, alternatively we can temporarily remove the block gap control from that block.

@youknowriad does the above mean that block spacing would not be supported in the Columns block in 5.9 if the block is not refactored? Would this break themes that are using it?

**Comment by youknowriad** [comment]
> does the above mean that block spacing would not be supported in the Columns block in 5.9 if the block is not refactored? Would this break themes that are using it?

yes, Unless we refactor it we need to accept one of two things:

 - Columns block not supporting custom block gap (it can still use the default top level one)
 - Block gap broken in a lot of places

**Comment by youknowriad** [comment]
Btw, here's the PR that refactors the columns block #37436

**Comment by ndiego** [comment]
> Btw, here's the PR that refactors the columns block #37436

Perfect, thanks. I will allocate some time this afternoon to test.

**Comment by glendaviesnz** [comment]
I just looked at updating the Navigation block, but there is an issue with modifying this block to support this approach. 

It works well for Group, Buttons, Columns as the children that need the gap applied are direct children of the block wrapper to which the gap CSS is applied. 

With the Navigation block, however, the children to which the gap needs to be applied are nested 5 levels under the parent block wrapper. I think the only way around this will be to manually assign the blockGap attribute to the relevant wrappers. Luckily it is a dynamic block so won't need a deprecation to do this. I have [started a PR ](https://github.com/WordPress/gutenberg/pull/37543) to explore this approach.

**Comment by glendaviesnz** [comment]
> I can't see a way of supporting gap in the Navigation block using this approach unless there was something similar to `skipSerialization` which allowed the gap style value to be applied to an inner wrapper instead of the parent.

Actually, one option for the Navigation block might be to manually apply the value from the `style.blockGap` attribute as a style value on the relevant wrapper. This would require adding a deprecation, but would at least maintain the support of the gap setting for this block.

**Comment by glendaviesnz** [comment]
I tested the Social block again and there seemed to be an issue with this approach, but it seems like it is an existing bug that also happens on trunk, in that the blockGap attribute is wiped on editor reload if a justification attribute is not also set - have added a [separate issue](https://github.com/WordPress/gutenberg/issues/37542) for this

**Comment by jasmussen** [comment]
I could swear block gap used to affect only the block, but at the moment in trunk, it affects everything. I guess that's part of what we need to fix here:

Screenshot 2021-12-22 at 14 22 32

Screenshot 2021-12-22 at 14 23 01

**Comment by youknowriad** [comment]
I've rebased this PR to solve conflicts and also disabled the block gap support for both columns and navigation blocks. We can work on restoring these in #37436 and #37543.

The current PR needs to land anyway because we need to move away from the CSS variables, there's no solution that retains the variable and allows per block config without the variable leak that is explained in #36521

**Review by jasmussen — APPROVED** [review]
I spent a little time testing this one today, and understanding the nuance of the issue. The challenge is outlined in <a href="https://codepen.io/joen/pen/GRMyqbg?editors=1100">this codepen</a>:

- A globally defined variable is well inherited by blocks.
- Those blocks can override the variable in their own scope.
- But when a block overrides it in its own scope, it leaks into the parent spacing rule.

This PR is important to land so we don't have to handle a tricky deprecation, but for any block that supports the block editor concept of `layout`. That means Buttons and Social Icons work right out of the box, but Navigation and Columns do not. As Riad notes, we can restore those controls separately:
gap

In light of that, and in light of how important this one is to land, it definitely feels like the tradeoff is acceptable.

**Comment by ramonjd** [comment]
Just noting here that we _might_ need to update a [WordPress core test](https://github.com/WordPress/wordpress-develop/blob/2648a5f984b8abf06872151898e3a61d3458a628/tests/phpunit/tests/blocks/render.php#L212) when/if this changeset makes it into the next version of WordPress.

@fullofcaffeine found that equality checks on rendered blocks and fixtures in `test_do_block_output()` could fail if blocks – such as the [recently-updated Columns Block](https://github.com/WordPress/gutenberg/pull/37436) – opt into the layout abstraction and therefore receive a dynamic class name via `wp-container-` + `uniqid()`.

The short of it is that the fixture, which has static classnames, doesn't match the rendered block. 

Sniffing around, I see that [some Gutenberg tests](https://github.com/WordPress/gutenberg/blob/d968d7b885555a9600e53c1a53047f5fc72e2b58/phpunit/class-elements-test.php#L15) handle this via a string replace on the `id` portion of the classname. That could be an approach.

I'm not sure whether we should prepare core for this now, or (something I suspect is better) waiting until the next core update and dealing with the failing tests then. Gutenberg changes a lot so maybe we should fix it when the next update happens...  assuming the code is still there 😄

**Comment by scruffian** [comment]
It is a shame that since this change blocks can't set a gap in theme.json. I opened https://github.com/WordPress/wordpress-develop/pull/2307/files to see if we could find a way round that... cc @youknowriad

**Comment by youknowriad** [comment]
@scruffian unfortunately, it's done on purpose, if you allow tweaks (like your PR does), it's going to recreate the issues fixed by this PR. Basically, The wrong "margin-top" can be applied to a social-links block (or a buttons block) if you tweak its gap using theme.json.  Instead of using the margin top of the default gap, it will use the one specific to that block.

**Pull request merged**
