### PR TITLE
Add `my_` prefix to callback function for registering post type

### PR DESCRIPTION
**Pull request by Shelob9**
Simple doc fix for #5149

## Checklist:
- [x ] My code is tested.
- [x ] My code follows the WordPress code style.
- [x ] My code has proper inline documentation.

### CODE REVIEW

**Comment by youknowriad** [comment]
This is a duplicate of #4980 but I'd be inclined to merge this one if you can address @aduth 's comment https://github.com/WordPress/gutenberg/pull/4980#discussion_r167358846

**Comment by Shelob9** [comment]
@youknowriad I can edit. I replied to that comment with why I partially disagree. I will refesh my PR tomorrow.

**Comment by Shelob9** [comment]
@youknowriad I updated based on https://github.com/WordPress/gutenberg/pull/4980#discussion_r167358846

**Review by youknowriad — APPROVED** [review]
LGTM 👍  Thanks

**Pull request merged**
