### PR TITLE
fix image block regression

### LINKED ISSUE #16284: Image Block: Image has extra padding, no drag handles, and is missing caption styles
**Describe the bug**

There seems to have been a regression in the image block. Images inside the block now come with extra padding, are missing drag handles, and are missing their caption styles.

**To reproduce**

1. Add an image block
2. Insert an image
3. See error

**Screenshots**

_Gutenberg Master/6.0_
Screen Shot 2019-06-25 at 10 51 08 AM

_Gutenberg 5.9.2 (Expected):_
Screen Shot 2019-06-25 at 10 50 43 AM

### PR DESCRIPTION
**Pull request by draganescu**
Fixes #16284 
Added back a missing className in the edit function of the image block.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 

@kjellr do you want to test it?

**Comment by youknowriad** [comment]
Merging to proceed with the release.

**Comment by kjellr** [comment]
This looks good, and fixes all the issues noted in #16284. I'm seeing one other small regression though: the placement of the inline formatting tools for the caption are misplaced now: 

Screen Shot 2019-06-26 at 7 46 13 AM

Here's a  screenshot from Version 5.9.2 for reference: 

Screen Shot 2019-06-26 at 7 45 50 AM

**Comment by youknowriad** [comment]
Mmm, right on time @kjellr I'll try to see if I spot the differences quickly.

**Comment by youknowriad** [comment]
@kjellr The good news is that this regression is not on 6.0.0 but it's on master so we have time to fix it.

I think it comes from #15212 cc @ellatrix

**Comment by kjellr** [comment]
Sounds good, thanks for the quick fix!

**Pull request merged**
