### PR TITLE
Update: Increase bottom padding on gallery image caption

### LINKED ISSUE #8018: Multi-line gallery captions are visually imbalanced.
In multi-line captions, the bottom-most line appears closer to the bottom of the box than to the line of text above it. This creates uncomfortable visual tension on that last line, and pulls it away visually from the text above it. 

Adding just a tiny amount of additional padding between the caption and the bottom of the box helps relieve that:

screen shot 2018-07-18 at 8 37 58 am

### PR DESCRIPTION
**Pull request by johnwatkins0**
## Description
This resolves #8018 by increasing the bottom padding of gallery image captions by 4px. 

## How has this been tested?
Visually verified the change in the editor (in English and in an RTL language) and in the published post.

## Types of changes
One character change in an SCSS file.

### CODE REVIEW

**Comment by karmatosed** [comment]
In theory this could be a good addition but the PR needs refreshing. Could you work on that please @johnwatkins0?

**Comment by johnwatkins0** [comment]
Updated to address staleness, @karmatosed.

**Comment by jasmussen** [comment]
Be sure to check the contrast is sufficient when moving the text upwards.

**Comment by gziolo** [comment]
What is missing to land this one?

**Comment by kjellr** [comment]
This works well, but just needs a tiny adjustment to the gradient. I was unable to pull the branch down to test (I think the source repo has been deleted), so I created a fresh PR with that change: #13623

I'll close this issue and we can migrate over there instead. 

Thanks for getting this going, @johnwatkins0!

**Pull request closed without merging**
