### PR TITLE
Automated Testing: Remove Puppeteer CI Job

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Now that [Playwright migration is completed](https://github.com/WordPress/gutenberg/issues/38851), we can safely remove Puppeteer and related.

## Testing Instructions
CI should be green.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think this needs to become a peer dependency just like Playwright. @swissspidy, @gziolo what do you think?

https://github.com/WordPress/gutenberg/blob/8ce1a6cc74afcba5a49f39cc08883a850f112a4d/packages/scripts/package.json#L79

**Comment by gziolo** [comment]
> I think this needs to become a peer dependency just like Playwright. @swissspidy, @gziolo what do you think?
> 
> https://github.com/WordPress/gutenberg/blob/8ce1a6cc74afcba5a49f39cc08883a850f112a4d/packages/scripts/package.json#L79

As long as it works when using `@wordpress/scripts` alone which it should, it's fine with me.

**Comment by youknowriad** [comment]
@Mamaduka can we remove the npm dependency entirely since we now recommend playwright, It can be a breaking change in the wp-scripts package but that seems fine.

**Review by ellatrix — COMMENTED** [review]
Is this all that needs to be removed? What about the e2e-tests package?

**Comment by Mamaduka** [comment]
> Is this all that needs to be removed? What about the e2e-tests package?

First we’ll need to relocate test plugins in different directory and then I guess deprecate the package. Not sure what’s the policy about that.

**Comment by talldan** [comment]
> First we’ll need to relocate test plugins in different directory and then I guess deprecate the package. Not sure what’s the policy about that.

I think `@wordpress/nux` is a package that has been deprecated in the past. There was also an attempt to remove it in the past which didn't go so well as it's used by core. This one might be different as it's only a dev dependency. 🤔

**Comment by ntsekouras** [comment]
>@Mamaduka can we remove the npm dependency entirely since we now recommend playwright, It can be a breaking change in the wp-scripts package but that seems fine.

➕ to this.

**Comment by kevin940726** [comment]
Another smaller thing is that we can now reference `npm run test:e2e` directly to `npm run test:e2e:playwright` in this repo. We can keep the `test:e2e:playwright` script for a while for muscle memory.

**Review by talldan — APPROVED** [review]
I noticed we're still running the puppeteer CI job. It takes five minutes even though it runs no tests 😆 

Would love to see this PR merged to reduce our computations. ❤️ 

A small tracking issue for all the tasks associated with removing puppeteer would be great if anyone wants to volunteer to do that.

**Comment by Mamaduka** [comment]
Good point, @talldan!

I'll create a separate issue to remove Puppeteer from the `scripts` package. We can discuss the best options there.

**Comment by talldan** [comment]
Decided to rebase this and it'll auto-merge when all tests pass.

**Comment by talldan** [comment]
Oops, I forgot to add the co-authors. Sorry everyone 😞

**Pull request merged**
