### PR TITLE
Remove oEmbed fixture files

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

I don't think these are that useful to have because all of them have the same `save` functions and attributes as the embed block. They bloat PRs (such as #7890) that change the embed block, and it's a waste of time to update them all.

### CODE REVIEW

**Comment by notnownikki** [comment]
+100

**Review by tofumatt — APPROVED** [review]
Makes sense to me, I don't think they're useful tests looking at this diff now.

more-red-than-green

**Review by notnownikki — APPROVED** [review]
This is my favourite PR of the week.

**Comment by jasmussen** [comment]
This thread: 🏆

**Comment by iseulde** [comment]
Cool, that didn't need much convincing! :)

**Comment by ntwb** [comment]
Noice 💐

**Pull request merged**
