### PR TITLE
RichText: fix caret position when deleting a selected word

### LINKED ISSUE #11964: RichText: incorrect caret position after deleting selected word
**Describe the bug**

Splitting this out from #11564.

From @dd32:

>  If I select a word (either by highlight, or double click) and then backspace it (But NOT when placing the cursor after the word and backspacing it), the DOM would read word1 word2 (two spaces) but the UI would show the cursor directly before word2 such like this: word1 |word2, typing would then eat that second space and result with word1 word4word3 instead of the expected word1 word4 word3.
>
> Testing in Firefox 63.0.3 caused the same carrot positioning, but the space would re-appear once the word started being typed.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #11964 and adds e2e tests.
Also fixes an issue where CTRL+A wouldn't select all blocks if you first select all text in a rich text field by triple clicking and then pressing CTRL+A.

In #11627 I retained deletion handling for uncollapsed selections (meaning text is selected) because I couldn't figure out the problem fast enough with letting it be handled natively again. It turns out TinyMCE is handling the case where an instance is entirely selected, and the React `onKeyDown` event is only fired after the TinyMCE event, causing TinyMCE to delete the contents first, and then us thinking the field is empty and merging it with the neighbouring block. The solution is to prevent the TinyMCE behaviour in that case, and handle it ourselves.

@notnownikki I also updated the tests you have added, to check if the space is actually there before retyping.

## How has this been tested?
See #11964 and above.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by notnownikki — APPROVED** [review]
Thanks for the test fixes and improvements :)

I've gone through all the steps manually and everything works as expected, :+1: from me!

**Comment by notnownikki** [comment]
Just an aside: is there already an issue open for the caret placement after undoing deletion?

**Comment by iseulde** [comment]
> Just an aside: is there already an issue open for the caret placement after undoing deletion?

I'm not sure. Caret position in general is never set after undoing changes. It's an old issue that probably needs a bit of work.

**Comment by iseulde** [comment]
Thanks for testing @notnownikki!

**Pull request merged**
