### PR TITLE
Column: Add border radius support and content clipping

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related:
- https://github.com/WordPress/gutenberg/pull/39967

## ⚠️ Disclaimer ⚠️ 

_This is a very quick and rough draft to demonstrate the UX issue around adding border radius support to the Column block._

## What?

Adds border-radius support to Column blocks and provides the option to toggle content clipping on and off for the column.

## Why?

Enabling border radius support for individual columns will allow matching height columns to have rounded corners as per this [design mockup](https://github.com/WordPress/gutenberg/pull/39967#issuecomment-1118944562). It was initially omitted from #39967 due to concerns around content clipping.

## How?

- Opts into border radius support
- Injects a new "Clip content" control into the border block supports panel 
- If "Clip content" is enabled, then `overflow: hidden` is applied via the column's inline styles.

## Known Issues

⚠️☠️   **When clipping column content in the editor, the block inserter within the column will also be hidden.** ☠️ ⚠️

Given the inserter is added within the Column block's markup I haven't found a way around this problem.

| Default | Clipped |
|---|---|
| Screen Shot 2022-05-09 at 6 52 13 pm | Screen Shot 2022-05-09 at 6 52 03 pm |

## Testing Instructions

1. Edit a post, add a columns block including multiple columns with content
2. Apply a background color on each column
3. Apply a border radius to a column and experiment with toggling on clipping
4. Notice how when clipped, in most situations, the block inserter is also clipped presenting a problem that may block introduction of clipping

## Screenshots or screencast 

https://user-images.githubusercontent.com/60436221/167376238-598926ff-9a56-46b0-9f97-612f1b21f546.mp4

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
@jasmussen I've take a run at your [suggestion](https://github.com/WordPress/gutenberg/pull/39967#issuecomment-1085519758) from https://github.com/WordPress/gutenberg/pull/39967 to explore a "Clip content" toggle alongside border radius support for individual Column blocks. 

As noted in the PR description there's a bit of a UX problem if we clip column content in the editor. I didn't have any success finding a solution here.

Given there is a [desire for rounded corners](https://github.com/WordPress/gutenberg/pull/39967#issuecomment-1118944562) on Column blocks, would it still be worth adding (without Clip content option) in a  "your mileage may vary" kind of way? Any other ideas?

**Comment by paaljoachim** [comment]
Hi @aaronrobertshaw 

It looks like this PR was forgotten about.
Joen @jasmussen and Rich @richtabor. Let's see what we can do to move this PR forward.
Thanks.

**Comment by aaronrobertshaw** [comment]
Thanks for the nudge @paaljoachim. It is still in my backlog but unfortunately not a priority.

We still have the primary UI issue where clipping content via border-radius will obscure the block inserter. I'm not sure there's a quick fix we can make to move this forward. It's more likely to be working out what compromise is acceptable.

**Comment by jasmussen** [comment]
Took it for a quick spin, and here's a quick GIF:

radius

 I don't personally see any urgency on this one, but longer term, I do think most of these tools should be available for most blocks. And yes, this PR highlights some of those challenges, clipping or otherwise.

One instinct is that for blocks where radius is less useful, like containers group, columns, etc — radius could potentially be a non-default tools panel option. While the toolspanel interface could use separate love for clarity and resetting, this is nevertheless a good example of why curated defaults can make sense.

As far as the question on clipping, that is a good question. I have a feeling that at some point in the future, it will likely be useful to be able to toggle clipping _off_, i.e. it might need to be a separate design tool. In the past we've discussed adding overflow support hidden in the "Advanced" menu, but considering scrollbar use cases and more, we might indeed want overflow as a separate design tool. 

The question then is what to default to. We can't default every block to overflow: hidden; — yet that is clearly the superior experience when changing the shape of a block, such as using the radius here. So in these cases, should changing the radius also apply overflow: hidden? Not sure, and would be good to get further with design tooling and componentry in general before we touch that, probably.

As far as the plus button, I'm still not crazy about it being there, in-canvas. We might still need it, but I feel like there might be a better solution we can find. If all else fails, it might need to be popovered, live outside the block itself, so it would not get cropped.

**Comment by aaronrobertshaw** [comment]
Closing this draft PR as it is rather stale now. 

There still aren't many options to handle the inserter being hidden. Before this could be resurrected, a solution to that is needed.

**Pull request closed without merging**
