### PR TITLE
File Block: Makes the button an element button

### PR DESCRIPTION
**Pull request by scruffian**
## What?
Makes the button in the file block a button element.

## Why?
This enables themes to target the button in file blocks without custom CSS.

## How?
Adds the experimental class name to the button. The shortcoming of the approach is that it won't work for blocks that have already been serialised. The alternative approach is to add the file block button class name to the list of selectors in the element selector, but this will cause bloat to this selector which we will need to support forever.

This approach is a compromise which will work for newly added form blocks, but not existing ones.

## Testing Instructions
- Use this PR: https://github.com/Automattic/themes/pull/5849
- Switch to Archeo
- Create a new post
- Add a file block
- Confirm that the button looks the same as other buttons in the editor and the frontend

## Screenshots or screencast 
Screenshot 2022-05-23 at 13 15 23

cc @WordPress/block-themers

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
LGTM!

**Comment by MaggieCabrera** [comment]
I'm getting specificity issues here too using Blockbase with [this PR](https://github.com/Automattic/themes/pull/6042):


Screenshot 2022-05-26 at 12 57 05

**Comment by youknowriad** [comment]
There's also a missing block deprecation here (extra classname for the file block). Please can you ensure that all the blocks that had support for all these new elements (new classnames) have the needed deprecations. See #45153

**Comment by scruffian** [comment]
Deprecation added here: https://github.com/WordPress/gutenberg/pull/45159

I'll follow up with the others shortly.

**Comment by youknowriad** [comment]
Thanks @scruffian

**Pull request merged**
