### PR TITLE
Navigation Block / Page List: Unify menu item styles.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This PR unifies the CSS for menu items. 

- Instead of duplicate CSS for how flyout menus work, how triangles are rotated, and the metrics of each aspect, this unifies the styles for meny items from both Page List and custom menu items into one.
- The recently landed markup simplificiation levels the playing field for style inheritance. That means text-decoration, underline, font colors, font, font family rules now correctly display for menu items both custom and those from the Page List.
- Because of the CSS unification, some of the bugs that have been fixed for menu items, are now also fixed for Page List when used inside navigation. This helps prevent CSS from going out of sync.

There is an argument for having CSS be scoped to each block, even if it means duplication. However in this case, the Page List block is a separate block that works outside of the navigation block. Therefore I would argue that it is the purview of the Navigation block to handle the styling of Page List items, when it is used inside, therefore it's appropriate to group styles for both inside navigation.

## How has this been tested?

As a preface, please create and publish a number of pages, some that include at least 2 levels of subpages.

Now insert a navigation block, and in that, include both the Page List block, as well as some custom/manually inserted menu items. Please also include some custom submenu items. 

Please test that menu items look identical whether they are from the Page List or custom. 

Ideally, test in both the post editor and the site editor. It's good to test first with the Empty Theme from https://github.com/WordPress/theme-experiments so you see the default block rules on their own. Then you can test in other themes. For example, TwentyTwentyOne includes some blanket margin rules for blocks that make things look a bit off, but that's a pre-existing issue. TT1 blocks does not have this issue.

Please test the navigation screen, but with a non-FSE theme active (see https://github.com/WordPress/gutenberg/issues/28874)

## Screenshots 

Before, editor, site editor, frontend in "empty theme":

before editor

before site editor

before frontend

After, editor, site editor, frontend:

after editor

after site editor

after frontend

GIF showing how the style properties now work identically for both types of menu items:

styles

GIF showing the same, but for TT1 Blocks:

tt1blocks

GIF showing the navigation screen looking slightly more uniform:

navigation

Note that the navigation screen could benefit from a separate look, happy to do so as a followup. But for now I wanted to primarily touch the block, and not regress the screen.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by georgeh** [comment]
In Twenty Twenty One (not TT1 Blocks):

The text size and appearance settings don't seem to apply to everything. I created a navigation block, added the all pages block, then added a Category link block. 

In the Typography settings, when I change the text size on the navigation block to 10 and the appearance to Extra Light, it looks like this:

image

"Uncategorized" is the category link block. This _does_ match the published view:

image

In Twenty Seventeen everything seems to work correctly.

**Comment by draganescu** [comment]
The existence of the pages list block in the navigation screen is accidental today. It only appears if you click create from all pages in the placeholder of an empty menu. However, without the theme opt-in no blocks other than the link block should be used in the navigation block, by default. Just thought I'd mention that (and should probably open an issue asap :) )

**Comment by jasmussen** [comment]
> The existence of the pages list block in the navigation block is accidental today

Just to be sure, you mean the navigation screen, don't you?

**Comment by draganescu** [comment]
Yes, oops! Fixing its styling is good but I thought it's a good note.

**Comment by jasmussen** [comment]
Yep makes sense!

**Comment by jasmussen** [comment]
Note that this PR already includes the fix that was created in #30009.

**Review by vcanales — APPROVED** [review]
#### Works for me:
- Typography.
- 1. Font size.
- 2. Appearance.
- 3. Letter Case.
- Color settings.
- Custom classes.
- Show submenu indicator icons on-off

Text decorations work for me on the parent, and the style is not applied to submenu items — from your own gifs it seems to be the expected behavior.

https://user-images.githubusercontent.com/1157901/112142625-992aea00-8bb5-11eb-9f3f-4f41be8ca9ae.mov

Tested on TT1 and TT1 blocks and achieved the same result.
This LGTM!

**Comment by jasmussen** [comment]
Thank you!

**Pull request merged**
