### PR TITLE
Remove image 100 percent width style.

### LINKED ISSUE #17787: Using width: 100% on img causes problems
**A style is making my image too big.**
Using WP 5.3 beta2
A media-text block with a small image is stretched, making the image blurry and out of position.
The problematic CSS is (found in wp-includes/css/dist/block-library/style.min.css?ver=5.3-beta2-46391)
```
.wp-block-media-text > figure > img, .wp-block-media-text > figure > video {
    width: 100%;
}
```
**To reproduce**
1. Add a Media-Text block
2. Select a small image (mine is 165px wide)
3. Add some text
4. Duplicate the block
5. Align the second block opposite the first
6. (Save) View on front end to see the images stretched.

**Expected behavior**
I expect the images to show at no larger than the original.

**Screenshots**
This is how it looks in the editor. The images look stretched if I use a wide window.
media-tet-blocks-editor

This is the front end.
stretched-image-front-end

This is the front end when I disable the `width: 100%` rule mentioned above.
media-text-blocks-with-width-disabled

**Desktop (please complete the following information):**
 - OS: Ubuntu Studio 16.04
 - Browser SeaMonkey 2.49.5

### PR DESCRIPTION
**Pull request by adamsilverstein**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/17787

## How has this been tested?
* Viewed images on front end.
* Verified "width: 100%" style no longer present.

I also tested a video (uploaded mp4) and see a separate width 100% style.

image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by paaljoachim** [comment]
@tellthemachines and @jasmussen 

I am wondering if the image 100 percent width style is also influencing various issues:
https://github.com/WordPress/gutenberg/issues/26715
and
https://github.com/WordPress/gutenberg/issues/17795
As well as a few other issues as well.

**Review by jasmussen — CHANGES_REQUESTED** [review]
Thanks so much for the PR. It's a simple change, those are always good. And the PR works well for simple cases:

Screenshot 2021-02-09 at 09 57 29

Screenshot 2021-02-09 at 09 57 25

However it breaks apart as soon as you use a small image, or a video. Here's a small image:

Screenshot 2021-02-09 at 09 58 17

Notice how the resize handle floats in the middle. Here's before:

Screenshot 2021-02-09 at 09 58 11

Notice how the photo is fuzzy because it's scaled beyond its intrinsic resolution, but at least the resize handle is accurate.

Here's a big video added:

Screenshot 2021-02-09 at 10 01 23

It blows past the boundaries of the media area. Here's before:

Screenshot 2021-02-09 at 10 01 36

Now in inspector testing, it did appear that at least the video issue could be solved by changing the max-width to 100% instead of "unset" — though if we did that, we would have to do a little digging to find out why it was set to "unset" in the first place (#9416).

Even if we did do that, though, we'd still have the issue for both images and video, where if the dimensions are too small for the allocated area, the resize handle will sit in the middle and do nothing until it reaches the image boundary:

small

So I see a few paths forward:

1. The technical one, where we have to write a whole bunch of logic to figure out that the image is smaller than the allocated space, and then resize the media area accordingly. 
2. Apply the 100% max-width and decide that the resize handle floating in the middle is _fine_ — that there isn't enough resolution so it shouldn't be scaled up.
3. Decide that the current behavior is correct: that the Media & Text block is designed to crop and fit an image or video on the left, and that the separator is sole arbiter of the layout, and that if you add too small an image it's either because you want 8-bit graphics on the left, or you should either replace the image, or size the slider to the left to reach fidelity.

Honestly, 3 appeals the more to me. Even if the image is pixelated, there are tools to address that, and the block functions predictably. To an extent, it's the same with the cover block, or even the Group block once that gets background-image functionality: the fidelity of your design depends on the material you provide.

**Comment by paaljoachim** [comment]
My gut feeling said that this might affect various blocks boundry area and the image inside it, but I might just be mistaken.

**Comment by hedgefield** [comment]
Thanks for doing the testing @jasmussen, and I agree with your third suggestion - the block separator should determine the area where an image can be shown, and if the image is too small or of a different proportion to that area, it fills the empty space and gets cropped accordingly. If that makes the image look bad, it's up to the user to provide a proper image for it. That's basically what Facebook or Instagram etc do too.

**Comment by tellthemachines** [comment]
I'm putting in a vote for @jasmussen 's number 2 solution. My reasoning is: 

* There's a setting in the Media & Text block sidebar that allows us to pick the image size, so it stands to reason that picking "medium" or "thumbnail" should give us a smaller image and not just the same size image with a crappy resolution 😛 

* The resize handle should be in the middle, independently of the size of the image, because by default the area devoted to image and text is 50/50. If the text can occupy just a fragment of its space (say it's a single, centre-aligned word) then the image should also be able to do so.

**Comment by paaljoachim** [comment]
I am wondering if this issue is associated:
https://github.com/WordPress/gutenberg/issues/17826

**Comment by jasmussen** [comment]
Pretty sure that's unrelated. This issues seems very specific to the `img` element being used in a relatively pure form in the Media & Text block.

**Comment by adamsilverstein** [comment]
Thanks for the detailed reviews and feedback here. I'm always keenly aware of the wide ranging side effects of changing even a single CSS line so I'm grateful to have the wider review.

How do the solutions you describe apply to the issue reported in the original ticket? https://github.com/WordPress/gutenberg/issues/17787

**Comment by jasmussen** [comment]
> How do the solutions you describe apply to the issue reported in the original ticket? 

Going back to that one, the key issue I reviewed based on, was "a style is making my image too big". I initially thought the problem here was that a very small image when uploaded would become blurry when forcefully scaled up beyond its intrinsic resolution.

However that might have been a misunderstanding on my part (focusing too much on the `width: 100%;`), and that the underlying issue may be images that on the frontend [go beyond the boundaries](https://user-images.githubusercontent.com/7957680/66261528-9a374400-e794-11e9-845d-94e07475df08.jpg).

Removing the `width: 100%` rule will almost certainly not fix this, as I tested that in this PR. However setting a max-width as suggested [here](https://github.com/WordPress/gutenberg/issues/17787#issuecomment-540080831), might.

Right now the max-width is `unset`, and while the `width` should be enough, if a theme's CSS styles override this, or even add a high min-width, then those rules will win out.

I created a separate PR with an alternate approach here: #28922

**Comment by adamsilverstein** [comment]
> I created a separate PR with an alternate approach here: #28922

Excellent, thanks for continuing the work on this @jasmussen - your reasoning and solution seems more ideal. My change was based purely on the problem description in the issue and I am glad it spurred conversation leading to the real solution.

I have one final question which I will leave on the new PR. Closing this one for now.

**Pull request closed without merging**
