### PR TITLE
FIX: HOOKS: Naming is unexpected

### LINKED ISSUE #3620: HOOKS: Naming is unexpected
## Issue Overview

Existing hooks use naming like 'core\anchor-attribute' but the '\a' is a non-existent escape sequence so this is interpreted as 'coreanchor-attribute'.  

I stumbled across this today investigating hooks for use in footnotes and created a hook named 'core\footontes' but '\f' is a valid escape sequence for ASCII character 12 (Line Feed) so my hook name was failing validation [here](https://github.com/WordPress/packages/blob/d62ecb778b95421fda0a069ddc52ac12a5480e73/packages/hooks/src/validateNamespace.js#L16)

Incidently the coment [here](https://github.com/WordPress/packages/blob/d62ecb778b95421fda0a069ddc52ac12a5480e73/packages/hooks/src/validateNamespace.js#L5) wasn't updated when the validation rules changed.

## Possible Solution

Use '-' to delimit hook name.

## Screenshots / Video

screen shot 2017-11-23 at 3 49 40 pm

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by tg-ephox**
## Description

fixes https://github.com/WordPress/gutenberg/issues/3620
## How Has This Been Tested?

Covered by existing unit tests

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
Right, it was a coincidence that it wasn't caught by validation mechanism. See related tests for hooks library:

https://github.com/WordPress/packages/blob/master/packages/hooks/src/test/index.test.js

**Comment by youknowriad** [comment]
I think I prefer "/" to match the blocks name

**Comment by gziolo** [comment]
It's not allowed at the moment, we will have to update `hooks` library and relax validation.

**Comment by tg-ephox** [comment]
@youknowriad it used to accept a name in the form [`vendor/plugin/function`](https://github.com/WordPress/packages/commit/f552dae81b2cfcf8768fc6b870868e5776afc523#diff-c252268e807f30f3a19f54f9715985d3)

**Comment by adamsilverstein** [comment]
we are addressing this in https://github.com/WordPress/packages/pull/47

**Comment by gziolo** [comment]
Yes, we do, but @tg-ephox proposed a more advanced solution, where you can pass down your custom validation method. Something we can still consider.

**Comment by adamsilverstein** [comment]
That seems like overkill, the point of this namespace restriction is to keep naming consistent, adding a custom validation method defeats that. If you really want to you could probably overwrite the method directly :)

**Comment by aduth** [comment]
Let's make sure to reverse these changes now that the `/` hooks namespacing has been published.

**Comment by gziolo** [comment]
I have changes for it ready locally. I’ll push together with HOC like filters for EditBlock tomorrow 😃

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/pull/3827/commits/c9310eb32696c4b9d733d05c06a6de4a481ecea8 is going to address it as part of #3827.

**Pull request merged**
