### PR TITLE
Try: Fix buttons faux space-between.

### PR DESCRIPTION
**Pull request by jasmussen**
Buttons in the Buttons block appear to be have "space-between" applied, even when they don't:

Screenshot 2021-01-26 at 10 40 34

This is because inside a flex container, if a margin is set to auto, that's the net result.

This PR fixes that. After:

Screenshot 2021-01-26 at 10 40 40

The frontend already worked.

Screenshot 2021-01-26 at 10 40 46

One larger issue is this rule from #21971:

```
// Extra specificity needed to override default element margins like lists (ul).
.block-editor-block-list__layout .wp-block {
	margin-left: auto;
	margin-right: auto;
}
```

It's going to continue to cause headaches for flex containers and themes. I wonder if there's a way we can refactor that rule away, without regressing what 21971 meant to fix. CC: @kjellr @scruffian.

Another issue was the use of the `_variables.scss` stylesheet to store a margin property that was used across the Button and Buttons blocks. It was added in #25999, but no block values should be added there, that stylesheet is purely for UI. And in adding a variable there, it also goes against the componentization / isolation of styles to each block container.

For that reason, I'd very much welcome input on how we can refactor this:

- The variable, now renamed `$blocks-block__margin` is used primarily in the Button block stylesheet. This is fine.
- It's used in the Buttons editor stylesheet only to increase specificity of the rules, due to the "auto" margins mentioned above. This one is hard to fix without refactoring away those auto margins.
- I'm unsure exactly why it's needed in the Buttons block, it seems like we could let rules here be inherited from the Button block @ntsekouras?

### CODE REVIEW

**Comment by scruffian** [comment]
I can't replicate this in master.

**Comment by jasmussen** [comment]
> I can't replicate this in master.

Sorry, I should've clarified in the instructions. It depends a little on the theme. Some people style those Button blocks, and inadvertently fix this, others do less. I think if a theme _doesn't_ style those buttons, it's more likely to happen.

You can try TT1 Blocks, I can reproduce it there. Theoretically you could also reproduce it by toggling off editor styles:

Screenshot 2021-01-28 at 12 38 08

**Comment by scruffian** [comment]
This looks good in the editor but not so good in TT1 Blocks on the frontend:
Screenshot 2021-01-28 at 11 44 08

**Comment by scruffian** [comment]
> It's going to continue to cause headaches for flex containers and themes. I wonder if there's a way we can refactor that rule away, without regressing what 21971 meant to fix. CC: @kjellr @scruffian.

To me this seems to be a function of the way we deal wide/full alignments. We try to keep the site content 100% wide so that we can implement wide and full alignments, but this causes other issues. IMO we should just constrain the site to whatever the content width is and then let blocks break out of it when they are wide/full width...

**Comment by jasmussen** [comment]
Thank you for reviewing and chiming in, I appreciate that a lot.

> IMO we should just constrain the site to whatever the content width is and then let blocks break out of it when they are wide/full width...

So negative margins or something like that? This is tricky to accomplish in the editor without the iframe, because vw units don't work. It's also a little bit less flexible with regards to various layouts you might want to use. Technically a theme _could_ do this already now in the editor style (aside from the vw unit). 

Perhaps the real solution is the refactor of wide and fullwide to be more of a prop on the container than a default for post content, which Riad has been talking about for a while.

Looking at that frontend issue now, thank you, good catch!

**Comment by scruffian** [comment]
Bring on the iframe!

**Comment by jasmussen** [comment]
Thanks for testing, everyone. It appears there's an issue with TT1 Blocks on the frontend, and I will look at what that is as soon as I can. I'm currently having some trouble getting TT1 Blocks to work with the plugin, and I believe things will work once https://github.com/WordPress/theme-experiments/pull/182 lands. When that happens, I'll test again, and revisit!

**Comment by jasmussen** [comment]
I managed to push a fix for TT1 blocks frontend. Before:

Screenshot 2021-02-05 at 08 57 45

After:

Screenshot 2021-02-05 at 09 05 30

It's this TT1 blocks CSS that does it:

Screenshot 2021-02-05 at 08 58 01

Blanket targetting like that is arguably not best practice, but nevertheless it's fair enough to do, so I felt it okay to push a fix here.

Pleas test this one again, and test:

- No justification
- Left, center, right justifications.

**Comment by aristath** [comment]
Should this fix be in Gutenberg, or in TT1-blocks? :thinking:

**Comment by ntsekouras** [comment]
Thanks for working on this Joen!

> Should this fix be in Gutenberg, or in TT1-blocks? 🤔

I also feel like this should be in TT1-blocks, since everything works well when testing with `Twenty Twenty-One`.

Also in this PR the buttons don't work well with `vertical` orientation.

**Comment by jasmussen** [comment]
That was my question to myself as well. However two reasons made me choose to include the fix here:

1. Because Buttons is a flex container with justification controls, the `margin` properties are intrinsic to the alignment.
2. Many more themes than just TT1 blocks blanket target blocks like this. It's not good practice, but I believe it's best to account for it, at least a little bit.

**Comment by jasmussen** [comment]
Thank you Nik, I'll take a look at the vertical orientation.

**Comment by jasmussen** [comment]
@ntsekouras what issues are you seeing with the vertical orientation? It seems to be working for me:

Screenshot 2021-02-05 at 09 45 11

**Comment by ntsekouras** [comment]
>@ntsekouras what issues are you seeing with the vertical orientation? It seems to be working for me:

Sorry I didn't clarify. It doesn't seem to work on the front-end. Buttons seem to always be `right`.

**Comment by jasmussen** [comment]
I'm not seeing that in TT1 blocks, or my own theme, in this branch:

buttons

**Review by ntsekouras — APPROVED** [review]
Tested and works great! Thanks Joen!

My comments about `vertical` were due to some development env problem of mine 😄

**Comment by jasmussen** [comment]
Let's land this as it improves the flex situation of the Buttons block a great deal, and I'm happy to follow up on any issues. Thanks all.

**Pull request merged**
