### PR TITLE
Fix image block v6 deprecation

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Fixes an image block deprecation issue surfaced in https://github.com/WordPress/gutenberg/issues/52388#issuecomment-1630025459. I'm not sure if it really solves the original issue because the page should load despite block validation errors.

> Greenshift has a lot of block validation errors:
>
> Screenshot 2023-07-11 at 12 46 21 pm

## Why?

Bug fix

## How?

1. Fix `getBorderClassesAndStyles` import.
2. Fix incorrect comment.
3. Add `attributes` and `supports` to the deprecation.
4. Add integration tests for the deprecation.

## Testing Instructions

Integration tests have been added for the deprecation. They should pass.

To manually test, add a v6 image block to a post via the code editor and save:

```html
<!-- wp:image {"align":"left","width":164,"height":164,"sizeSlug":"large","style":{"border":{"radius":"100%"}},"className":"is-style-rounded"} -->
<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%" width="164" height="164"/></figure>
<!-- /wp:image -->
```

You should no longer see the deprecation warning.

```
Block validation: Block validation failed for `core/image` ({name: 'core/image', icon: {…}, keywords: Array(3), attributes: {…}, providesContext: {…}, …}).

Content generated by `save` function:

<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%;width:164px;height:164px" width="164" height="164"/></figure>

Content retrieved from post body:

<figure class="wp-block-image alignleft size-large is-resized has-custom-border is-style-rounded"><img src="https://s.w.org/images/core/5.8/portrait.jpg" alt="" style="border-radius:100%" width="164" height="164"/></figure>
```

### CODE REVIEW

**Comment by jeryj** [comment]
Testing well! On `trunk` on the Greenshift theme I see the error:



On this PR it's working well without any errors 👍🏻

**Review by jeryj — APPROVED** [review]
Testing well and fixes the mentioned issue!

**Review by scruffian — APPROVED** [review]
LGTM. Well done for finding this. 👏

**Comment by ramonjd** [comment]
Nice work, thank you 🙏 

Now we know who to come to for deprecation troubleshooting :trollface:

**Comment by Mamaduka** [comment]
I noticed another issue with the deprecation. Here's a follow-up #52853.

**Comment by Mamaduka** [comment]
@draganescu, do we need to backport this and #52853, into 6.3 RC?

Edit: I tentatively added the backported labels, as I noticed this PR was already tagged in a project.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/further-bugfixes-rc2 branch to get it included in the next release: 0c4681824e

**Comment by mburridge** [comment]
I just cherry-picked this PR to the release/16.3 branch to get it included in the next release: bf38308cf2

**Pull request merged**
