### PR TITLE
remove defaultProp from required property in components/modal

### LINKED ISSUE #16062: Modal component defines a defaultProp for a required property.
**Describe the bug**
This could lead to bugs and could be confusing for newcomers. Modal requires a defined `onRequestClose` function so that the modal itself can be closed, yet it has a `defaultProp` of `lodash.noop`.

https://github.com/WordPress/gutenberg/blob/a57202e635ff0cd190a09128d27951620db9a870/packages/components/src/modal/index.js#L165-L179

**Expected behavior**
This should be a fatal error if the prop is not provided since it is critical for the modal to function properly.

### PR DESCRIPTION
**Pull request by dsifford**
closes #16062

Let me know if you have any further questions/comments.

### CODE REVIEW

**Comment by gziolo** [comment]
I'm wondering whether we should update docs to reflect that it is optional instead. It seems to be safer.

**Comment by dsifford** [comment]
That works too! Won't hurt my feelings to close this PR if that's the preferred route :stuck_out_tongue_closed_eyes:

**Comment by dsifford** [comment]
Though, I'm wondering if that will result in a component that renders with close buttons that aren't usable. Is that an a11y issue?

**Comment by aduth** [comment]
> Though, I'm wondering if that will result in a component that renders with close buttons that aren't usable (or, rather, that when clicked don't do anything). Is that an a11y issue?

It would, and it is. Nothing really guarantees that a developer implementing `onRequestClose` would handle this appropriately, but it is expected that a developer _should_ be using the prop to manage the closing of the modal (and as such, its existence is at least appropriate as a signal that it's being handled).

Reflecting on this, I think it would be perfectly reasonable to mark this prop as "Required". Normally I would be concerned about the backwards-compatibility impact of removing this default prop, but since it is explicitly documented as required, I think it would be fair to let this go through as proposed.

**Review by aduth — APPROVED** [review]
Per comments, I think this is an appropriate improvement. I'd wait to merge pending @gziolo's thoughts.

**Comment by gziolo** [comment]
> Per comments, I think this is an appropriate improvement.

Agreed, it will at least give some feedback when this prop isn't provided but the end effect will be the same. I didn't consider it.

**Pull request merged**
