### PR TITLE
[Mobile] - Quote - Use nested blocks

### PR DESCRIPTION
**Pull request by geriux**
This is a follow up of https://github.com/WordPress/gutenberg/pull/25892

- `Gutenberg mobile PR` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/4725

## What?
This PR adds compatibility to the new format of the Quote block on mobile.

## Why?
To stay up to date with core changes and prevent invalid content or other possible issues.

## How?
It changes the shared code by adding a missing text alignment needed in mobile as well as the style prop to be able to render colors.

Adds a new feature in the Paragraph block to inherit the parent's alignment if there's any set. 

Within `BlockQuotation` removes some unneeded code that was used in the previous quote format. As well as setting the styles in the container. It also updates the style paddings to take into account inner blocks.

## Screenshots or screencast 

iOS | Android
-|-
<kbd></kbd> | <kbd></kbd>

### Quote block with inner blocks

iOS | Android
-|-
<kbd></kbd> | <kbd></kbd>

### Quote block with text and background colors.

iOS | Android
-|-
<kbd></kbd> | <kbd></kbd>

### Quote block with alignment set

iOS | Android
-|-
<kbd></kbd> | <kbd></kbd>

### Quote block with another kind of inner block e.g. Image

iOS | Android
-|-
<kbd></kbd> | <kbd></kbd>

### CODE REVIEW

**Review by jhnstn — COMMENTED** [review]
I noticed that the text color "bleeds" out the left side of the block :  
Screenshot_20220401-161919

Here the text is green which you can see on the left side of the block. I don't see this same behavior on other nested blocks.

Besides that everything works as expected 👍

**Comment by geriux** [comment]
> I noticed that the text color "bleeds" out the left side of the block 

Oh that's the left border that's applied to the Quote block. If a text color is applied to the block, the left border would use the color as well like:

Without a text color set the line is black:
<kbd></kbd>

If you select a text color:
<kbd></kbd>

Thanks for testing it out!

**Comment by jhnstn** [comment]
> Oh that's the left border that's applied to the Quote block. If a text color is applied to the block, the left border would use the color as well like:

Thanks for clearing that up @geriux !

**Review by jhnstn — APPROVED** [review]
Thanks @geriux  Looks good 👍

**Comment by geriux** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/pull/40439

**Pull request closed without merging**
