### PR TITLE
[RNMobile] Implement recovery option for invalid blocks

### PR DESCRIPTION
**Pull request by SiobhyB**
Related PRs:

* `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4996

## What?

If a block's validation fails within the mobile app, users are shown an error but not provided with any options for recovering the block. This PR introduces an option for users to attempt block recovery. They'll be prompted to tap on a block if they wish to attempt recovery.

## Why?

The option to attempt block recovery already exists on the web, as shown in the following screenshot:

Screenshot 2022-06-27 at 23 02 07

This PR, therefore, brings the native behaviour more inline with the web. In doing so, it will provide users with an option to recover content and the look/feel of their content, without them needing to manually re-add blocks/content.

## How?

The `attemptBlockRecovery` function has been implemented following the same patterns found in web's version of the function here: 
https://github.com/WordPress/gutenberg/blob/286e6be2b13fc6ab2059b66d5c79728d811562ee/packages/block-editor/src/components/block-list/block-invalid-warning.js#L122-L124

## Testing Instructions

* Navigate to the post editor in the iOS or Android app.
* Add a new block, making sure to fill out some content or upload media if appropriate.
* Switch the editor to HTML mode.
* Remove the `wp-block-xxx` class name from the block's HTML.
* Switch the editor back to visual mode.
* Verify that the new "Tap to attempt block recovery" prompt appears alongside the now-invalid block.
* Tap on the block and confirm that it's recovered, with the content that was added also being recovered.

## Screenshots or screencast 

| Before  | After |
| ------------- | ------------- |
|  |  |

The following recording shows what happens before and after tapping the updated error message: 

https://user-images.githubusercontent.com/2998162/176045857-366250cf-374c-452c-9e66-4548b988202a.mp4

### CODE REVIEW

**Comment by derekblank** [comment]
@SiobhyB 👋 The code changes look good! I started reviewing this locally but ran into what seems like [this issue](https://github.com/Automattic/jetpack/pull/24020) with the Jetpack sass files. I'm curious if you think it might be an expected issue here, or something just related to my local setup that I need to update. Going to continue to review once I get around it, however.

**Comment by SiobhyB** [comment]
@derekblank, thank you for taking a look! For the error: I wonder if it may be related to the fact [the submodule reference was recently updated](https://github.com/wordpress-mobile/gutenberg-mobile/commit/75fd560cabea4eac92455b345f7f8f3babc48fe3) in Gutenberg Mobile. Does running `git submodule update --init --recursive` from the Gutenberg Mobile directory fix it by any chance? 🤔

**Review by geriux — APPROVED** [review]
LGTM! I tested this both on iOS and Android, this addition is awesome, especially when there are issues with newer/older block formats 👏

**Comment by derekblank** [comment]
> I wonder if it may be related to the fact [the submodule reference was recently updated](https://github.com/wordpress-mobile/gutenberg-mobile/commit/75fd560cabea4eac92455b345f7f8f3babc48fe3) in Gutenberg Mobile. Does running `git submodule update --init --recursive` from the Gutenberg Mobile directory fix it by any chance? 🤔

@SiobhyB Yep, that was the issue -- thank you!

**Review by derekblank — APPROVED** [review]
I was able to run through the testing steps successfully on iOS and Android without issues. LGTM as well. 👍 Nice work!

**Pull request merged**
