### PR TITLE
Docs: Add Custom Block Editor to TOC and Manifest

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Add entry for Custom Block Editor to Table of Contents

## Types of changes

Documentation.

### CODE REVIEW

**Review by Soean — APPROVED** [review]
Looks good to me

**Comment by mkaz** [comment]
@Soean This almost worked. Something is getting messed up on publish. Any ideas?

**Comment by Soean** [comment]
It work's for the readme https://developer.wordpress.org/block-editor/developers/platform/custom-block-editor/

I think, we also have to add the `tutorial.md`.

**Comment by mkaz** [comment]
ah ok... so I guess it only knows about the files in the TOC

**Comment by mkaz** [comment]
One more try: https://github.com/WordPress/gutenberg/pull/20750

**Pull request merged**
