### PR TITLE
[RNMobile] Improve UI of error boundary component

### PR DESCRIPTION
**Pull request by fluiddot**
## What?

**This PR is a follow-up of https://github.com/WordPress/gutenberg/pull/59221.** Update the UI of the Error Boundary component that is displayed in editor-level exceptions.

## Why?

This enhancement will provide a better experience when the user encounters editor-level exceptions.

## How?

* Update styles and rendering logic of the `ErrorBoundary` component, located in the editor package.
* Remove usage of `Warning` component as the design of the `ErrorBoundary` component is now custom. 

## Testing Instructions

1. Apply the following patch file to show the Error boundary component:
```patch
diff --git forkSrcPrefix/packages/editor/src/components/error-boundary/index.native.js forkDstPrefix/packages/editor/src/components/error-boundary/index.native.js
index 6f76a4fbdccfe58b388206e750b2dd30e64cc0fd..532d8988b728ff237c62bbe837069f7eff2be726 100644
--- forkSrcPrefix/packages/editor/src/components/error-boundary/index.native.js
+++ forkDstPrefix/packages/editor/src/components/error-boundary/index.native.js
@@ -89,7 +89,7 @@ class ErrorBoundary extends Component {
 		super( ...arguments );
 
 		this.state = {
-			error: null,
+			error: Error( 'test' ),
 		};
 	}
 

```
2. Rotate the device, use different device sizes, and switch between light/dark modes.
3. Observe that the UI is rendered properly.

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

**iPhone:**
| Light | Dark |
|--------|--------|
|  |  |
|  |  | 

**iPad:**
| Light | Dark |
|--------|--------|
|  |  |
|  |  | 

**Android:**
| Light | Dark |
|--------|--------|
|  |  |
|  |  |

### CODE REVIEW

**Review by jhnstn — APPROVED** [review]
Looks good :shipit:

**Comment by fluiddot** [comment]
@osullivanchris let me know if you have any thoughts/feedback about the UI changes. In the meantime, I'm going to merge this PR so it's included in the next GBM version (being cut tomorrow March 14th, 2024).

**Comment by osullivanchris** [comment]
Hey looks good. Some thoughts (none of which are blockers)
- primary button in dark mode can be pure black on white rather than grey background
- grey icon background can be a darker color in dark mode 
- img attached of dark mode version re; the above
- can we add an attribute to the text so that we don't get a single orphan word on the last line?
- maybe we should get editorial to review this copy - I know there's a label not sure if its working, some discussion on slack

image

**Comment by fluiddot** [comment]
Thanks @osullivanchris for the feedback 🙇 ! I'll address this in a separate PR.

> * can we add an attribute to the text so that we don't get a single orphan word on the last line?

The text is wrapped based on the device's width, so I don't think there's an attribute to avoid a single ophan word in the last line. To achieve this, we'd need to perform different layout calculations, so not sure if it's worth the effort for a screen that (hopefully) not many users will see. WDYT?

Alternatively, we could break the line to ensure there's two words in the last line. But this would imply setting a fixed width so the rest of the content fits a similar layout. I.e. the second paragraph has a similar width.

> * maybe we should get editorial to review this copy - I know there's a label not sure if its working, some discussion on slack

Good point. I'm not sure if the GitHub label `Needs Copy Review` triggers an internal process but we can try. I'll do this in the new PR.

**Comment by fluiddot** [comment]
For reference, I've addressed part of the feedback shared [here](https://github.com/WordPress/gutenberg/pull/59823#issuecomment-1995067074) in https://github.com/WordPress/gutenberg/pull/59859.

cc @osullivanchris

**Comment by geriux** [comment]
Hey @fluiddot 👋 it appears the usage of `/` for a division is deprecated in the latest SASS version as you can see in [this warning](https://buildkite.com/automattic/gutenberg-mobile/builds/8891#018e41a2-30ae-42c2-ba93-5945a487ce1f/562-876). Now they recommend using `math.div($size, 2)`.

**Comment by fluiddot** [comment]
> Hey @fluiddot 👋 it appears the usage of `/` for a division is deprecated in the latest SASS version as you can see in [this warning](https://buildkite.com/automattic/gutenberg-mobile/builds/8891#018e41a2-30ae-42c2-ba93-5945a487ce1f/562-876). Now they recommend using `math.div($size, 2)`.

Good observation. I'll take a look and see if we can use the new format. Since we transform SASS code, I'm not sure if importing the `math` library would work. Alternatively, I can remove the division op with a fixed value.

**Pull request merged**
