### PR TITLE
Update: Use theme and core styles as defaults on the global styles

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Currently, the themes can set styles using theme.json but on the global styles editing UI even if the theme sets some styles, things appear empty, making it hard for the user the make small adjustments.

This PR makes sure the editing UI of global styles reflects the styles set by the theme and core.

## How has this been tested?
I added the following config to theme.json of 2021 blocks theme:
```
	"core/post-date": {
		"styles": {
			"typography": {
				"fontSize": "40px",
				"lineHeight": "3"
			},
			"color": {
				"background": "#f00",
				"text": "#0f0"
			}
		}
	}
```

I opened the site editor, and on the global styles sidebar, Post Date panel I verified the UI reflected the styles configured by the theme.

### CODE REVIEW

**Comment by nosolosw** [comment]
:wave: I've done some testing of this PR and this is what I see.

## How it works in the master branch

The UI controls only reflect user choices but not base styles (theme+core), hence the controls show the default value when the user hasn't chosen any:

Captura de ecrã de 2020-11-10 13-05-08

## How it works in this branch (using preset values)

Updated the theme.json of TwentyTwentyOne blocks theme to look like this:

```json
	"core/post-date": {
		"styles": {
			"typography": {
				"fontSize": "var(--wp--preset--font-size--extra-small)",
				"lineHeight": "var(--wp--custom--line-height--body)"
			},
			"color": {
				"background": "var(--wp--preset--color--black)",
				"text": "var(--wp--preset--color--green)"
			}
		}
	},
```

When I add the block to the editor I see it correctly styled, but the UI controls behave weirdly:

- font size value is set to custom
- line height value is unaffected (takes the default 1.5)
- color controls
  - have a  preview color (square with color alongside the control name), but it's white, not the proper color
  - the color value is not marked as selected

Captura de ecrã de 2020-11-10 12-56-43

## How it works in this branch (using raw values)

Updated the theme.json of TwentyTwentyOne blocks theme to use the corresponding raw values for the presets above:

```json
	"core/post-date": {
		"styles": {
			"typography": {
				"fontSize": "16px",
				"lineHeight": "1.7"
			},
			"color": {
				"background": "#000000",
				"text": "#D1E4DD"
			}
		}
	},
```

The editor is correctly styled and the UI controls do reflect properly the values:

Captura de ecrã de 2020-11-10 12-59-50

**Comment by nosolosw** [comment]
Based on my testing above, my first instinct is to think that we want it to work when using presets, otherwise it produces confusing results. It's highly likely that theme authors use presets to set the values of the style properties most of the time ― TwentyTwentyOne does and so the other themes I've checked.

**Comment by jorgefilipecosta** [comment]
Hi @nosolosw,

Thank you for the review. We now handle the case where variable references are used.

**Comment by nosolosw** [comment]
I think we could do with some tightening up of the API, so it doesn't see an explosion for each degree of freedom we want to give the consumer. I think we should optimize for the main use case:

- getStyleProperty( context, property ) => returns the user or fallbacks to base styles (merged style property)
- setStyleProperty( context, property ) => sets the user property

The question is how do we allow to retrieve the specific user values if there's one. There are a few options:

1. Consumers specify whether they want the default value or all (merged and user): `getStyleProperty( context, property, all = false )`.

```js
// Main use case: get merged value.
const color = getStyleProperty( 'core/paragraph', 'color' ); 

// Use case: get both values.
const { user, merged } = getStyleProperty( 'core/paragraph', 'color', true );
```

2. Consumers specify the origin they want to get data from: `getStyleProperty( contex, property, origin = 'merged' )`. `origin` can be 'merged' (default behaviour) or 'user'.

```js
// Main use case: get merged value.
const color = getStyleProperty( 'core/paragraph', 'color' );

// Use case: get both values.
const color = getStyleProperty( 'core/paragraph', 'color' );
const userColor = getStyleProperty( 'core/paragraph', 'color', 'user' );
```

3. Add a new method `getStylePropertyFromUserOrigin`.

```js
// Main use case: get merged value.
const color = getStyleProperty( 'core/paragraph', 'color' );

// Use case: get both values.
const color = getStyleProperty( 'core/paragraph', 'color' );
const userColor = getStylePropertyFromUserOrigin( 'core/paragraph', 'color' );
```

I listed them in order of personal preference. I'd rather not do 3, though. What do you think?

**Comment by jorgefilipecosta** [comment]
Hi @nosolosw thank you for the suggestions. I updated the code to use option 2.

**Review by oandregal — APPROVED** [review]
I submitted a fix to prevent some bad data input, other than that this works so can :ship: 

As a potential iteration on this code, I'd like `getValueFromVariable` and `getPresetVariable` hidden from the UI panels. They shouldn't have to know these internal things, rather this should be `getStyleProperty` / `setStyleProperty` responsibility to do.

**Pull request merged**
