### PR TITLE
Image block: try caption as inner block

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

caption-as-block-2

Having a caption as a block would mean it's super easy to add alignment and typography controls.
This also means we no longer need the horrible `inlineToolbar` rich text API.

Code-wise it's a pretty easy change to make.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by carolinan** [comment]
I really like this idea.
I think it would be great if text alignments could be added.
I am wondering if the movers and drag handles should be there, I was not able to move the caption above the image, and since it's a media caption I don't think that should be possible?

**Comment by ellatrix** [comment]
@carolinan Thanks for the feedback! Yes, perhaps we can remove the block movers for now, but maybe they're worth restoring in the future to move the caption above or below the image. I think we should allow the user to decide. According to the spec, you can position it anywhere you like. :)

**Comment by paaljoachim** [comment]
This is great! Thank you very much for working on this, Ella!

This is what I see:
Adding an Image block the caption shows up in the placeholder.

Screen Shot 2021-05-14 at 14 41 33

---

One general problem with the caption is that it aligns to the boundary box.
The caption aligns nicely to Large and Full, but not on Medium or Thumbnail images.


https://user-images.githubusercontent.com/5323259/118273052-bd26ef80-b4c3-11eb-9fd5-b381b47f6ffb.mp4



Associated issues:
Image block caption to become an inner/child block
https://github.com/WordPress/gutenberg/issues/28920

Image block selecting medium or thumbnail does not relocate caption - caption centered in relation to boundry box. 
https://github.com/WordPress/gutenberg/issues/17162

Important comment: #13684 (comment)

Missing text-align for image caption
#19975

**Comment by ellatrix** [comment]
> The caption aligns nicely to Large and Full, but not on Medium or Thumbnail images.

That happen in `trunk` too?

**Comment by paaljoachim** [comment]
I believe that the caption area has always aligned to the boundry box, and not the image inside of it. 

WordPress 5.7.2. Twenty Twenty One.
Deactivating the Gutenberg plugin.

Screen Shot 2021-05-14 at 16 06 40

**Comment by paaljoachim** [comment]
Hi @ellatrix and @Mamaduka 

One of the most obvious problems with alignment is as I mentioned above. That caption aligns to the boundary box. This means when the image is smaller than the boundary box the caption alignment will be off.

I believe the first challenge is figuring out a way to align the caption to the image inside the boundary box. So that we will automatically see the caption center aligned to the image at the size it is seen. Be it Full, Large, Medium or thumbnail.

**Comment by ellatrix** [comment]
@paaljoachim I don't understand how the PR is different from trunk. It looks the same to me.

**Comment by paaljoachim** [comment]
Hey @ellatrix 
I looks like we have a misunderstanding here. (I sent you direct message on Slack as well). It looks like I am not totally clear on what I am communicating.
Relating caption to boundry box is the same in trunk and in this PR. 

1- I assume the first step is making the caption an inner block.
2- The next step seems natural to figure out how to center align caption to all the different image sizes. 
3- Then to add caption alignment to the inner block toolbar, so one can left/center/right align the caption to any size image (including smaller size images.)

I assume the misunderstanding is that I brought up the caption alignment issue which is not really a part of this PR.

**Comment by jasmussen** [comment]
Nice. Before:

before

After:

after

This is a cool PR, and the promise of a simpler API, a reused block interface, and alignments, that's awesome.

However the PR also highlights that we still have some work to do with the block interface:

- Selecting parent child blocks, and highlighting the relationship between blocks that are strongly tied to a particular block
- The appender making a jump on first click, and perhaps more importantly the layout ship that the black appender plusses make.

I definitely think we'll want this at some point. The block is the primary API to emphasize here, and improving the block API, moving more and more towards blocks and block nesting, is a symbiotic relationship that improves all aspects of it. In this case, I think we will want to improve the block appenders and parent/child interface a little bit before we move too much farther with this one.

**Comment by paaljoachim** [comment]
It would be nice to get an update on this PR.
Thanks!

**Comment by paaljoachim** [comment]
@glendaviesnz @andrewserong I believe you might want to know about this PR.

**Comment by ellatrix** [comment]
Tbh, I still really want this, but not sure if I will ever try it again (lot of other things to do) and it's probably best to start a new PR.

**Pull request closed without merging**
