### PR TITLE
[RNMobile] Improve unsupported block message for reusable block

### LINKED ISSUE #32616: Reusable block: Add convert to regular blocks button in the unsupported block message
## Description

When editing a reusable block, the block only displays the message `Reusable blocks aren't editable on WordPress for <Platform>`, however, we provide an alternate way to edit it only for the current post/page via converting the block into regular blocks. As an improvement, we could add the convert button in the bottom sheet to let the user convert it easily.

Additionally, it would be nice if we update the message to make it clearer, it could be something like:
`Editing reusable blocks is not yet supported on WordPress for <Platform>`

## Step-by-step reproduction instructions

1. Add a reusable block to a post/page.
2. Tap on the block to edit it.
3. Observe the unsupported block message.

## Expected behaviour

Provide an alternative for editing the block when displaying the unsupported block message.

## Actual behaviour

The block only displays the unsupported block message.

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 8 (simulator)
- Operating system: iOS 14.2
- WordPress app version: `develop`

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3621

## Description

The unsupported block message has been updated and the convert to regular blocks button has been also included.

## How has this been tested?

1. Add a reusable block to a post/page.
2. Tap on the block to edit it.
3. Observe that the unsupported block message has been updated and provides an alternative to edit the block.
4. Tap on "Convert to regular blocks".
5. Observe that the reusable block is converted to regular blocks.

## Screenshots 

iOS - Light|iOS- Dark|Android- Light|Andoid - Dark
--|--|--|--
|||

https://user-images.githubusercontent.com/14905380/122185556-7b57e300-ce8d-11eb-856a-3fb927b80af1.mp4

## Types of changes

Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by fluiddot** [comment]
@iamthomasbishop I'd appreciate your input on this change, let me know if you have any suggestions, thanks 🙇 !

**Comment by iamthomasbishop** [comment]
@fluiddot Looks pretty good. I think we could make the "alternatively" part a bit clearer, maybe something along the lines of:

`Alternatively, you can detach and edit these blocks separately by tapping “convert to regular blocks”.`

What do you think?

**Comment by fluiddot** [comment]
> @fluiddot Looks pretty good. I think we could make the "alternatively" part a bit clearer, maybe something along the lines of:
> 
> `Alternatively, you can detach and edit these blocks separately by tapping “convert to regular blocks”.`
> 
> What do you think?

Sure! I'll update that part with your suggestion, thanks!

**Comment by fluiddot** [comment]
I updated the screenshots and video capture of the PR description with the last changes mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/32618#issuecomment-861884536).

@iamthomasbishop I finally changed the message to
`Alternatively, you can detach and edit these blocks separately by tapping "Convert to regular blocks".`, the only modification I made was to capitalize the word `Convert` to match the action button, let me know if you agree to this change, thanks!

**Review by guarani — APPROVED** [review]
Looks great! I tested on both platforms.
The only issue I ran into was https://github.com/WordPress/gutenberg/issues/32699, which is a known issue.

**Pull request merged**
