### PR TITLE
Add Typography: text orientation (writing mode)

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Adds a new text orientation option where text can be displayed horizontally or vertically.
Partial for https://github.com/WordPress/gutenberg/issues/50319

## Why?

To allow more design options.

## How?

- A new orientation setting is added to the Typography panel with the help of a writing-mode-control component.
- It has two options: Horizontal and vertical, that each adds inline CSS for `writing-mode` through the Style Engine.
- A writing mode block support is added under typography, and it is disabled by default.
- The block support is enabled for paragraphs and post navigation links in block.json.

## Testing Instructions
This setting is disabled by default and can be enabled for themes that include theme.json.

1. In theme.json, under settings > typography, add `writingMode: true`
2. Under styles > blocks, add
```
"core/paragraph": {
	"typography": {
		"writingMode": "vertical-rl"
	}
}
```
3. Activate the theme. Confirm that all paragraphs are vertical.
4. Remove the block style from theme.json.
5. Go to the Site Editor, Styles, Blocks, Paragraph, Typography, and set the orientation to vertical. Confirm that the block is vertical.
6. Change the orientation to horizontal and confirm the change is applied.
7. Next, select a paragraph block and find the orientation setting in the block settings sidebar, typography panel. It should not be displayed by default, but be available from the three dot menu.
8. Confirm that both options work in the editor and front.
9. Change the site language to use an RTL language, and repeat step 7. Confirm that both options work and that the text is facing the correct direction.

## Screenshots or screencast 
https://github.com/WordPress/gutenberg/assets/7422055/1d222d1a-99d7-4db9-b803-4649c104b6a4

### CODE REVIEW

**Comment by carolinan** [comment]
I think I got the two terms text-orientation and writing-mode confused. Do I need to rename this block support to writingMode, but keep the "Orientation" label for the control?

**Comment by jasmussen** [comment]
This is great! Thank you for working on it. I will give it a review as soon as I have a moment. For the mean time, CC: @WordPress/gutenberg-design 

A quick thought: the writing-mode and text-orientation CSS properties I agree are a bit confusing. I would personally be okay with not adhering to those, and simply calling this "Orientation". Not a strong opinion.

**Comment by carolinan** [comment]
I _think_ the writing-mode and the text-orientation would need to be two separate block supports but I will think some more about it and test a few things with the style engine.

**Comment by jameskoster** [comment]
This looks neat, thanks for working on it. 

I think it might be worth trying the icons from the original issue, if not too much trouble. The `arrowDown ` kind of suggests `text-orientation: upright;`.

**Comment by SaxonF** [comment]
Very neat! I'm wondering whether a more generic transform rotate setting (which looks [like was explored previously](https://github.com/WordPress/gutenberg/issues/20926)) would be more valuable _if the purpose behind this work is mainly for design tool reasons_? Putting it another way, if we ever release a rotate setting (which other design tools have), how would that overlap with the function of typography orientation?

**Comment by carolinan** [comment]
I did not know there were more than one issue and a pull request, would have saved me some time if I would just have copied it 🤣 

Reading from the discussion, there seems to be less support for a rotation setting.
Personally I rotate all sort of stuff, like an entire media & text block, headings, images. With a rotation option, I would expect to be able to adjust  an item to only a few degrees, and that's different from this feature.

**Comment by carolinan** [comment]
> This looks neat, thanks for working on it.
> 
> I think it might be worth trying the icons from the original issue, if not too much trouble. The `arrowDown ` kind of suggests `text-orientation: upright;`.

Can I copy those icons from Figma to the icon library? I did not find a link to the prototype in the issue.

**Comment by jasmussen** [comment]
My apologies, [the Figma is here](https://www.figma.com/file/ERw9rIxFxJP19g4eJVfN15/6.3-issues-needing-design?type=design&node-id=364%3A24208&t=TR2G93OpWdpqDPv0-1), and here are SVG icons you can add to the library. text-vertical:

```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="enable-background:new 0 0 24 24" viewBox="0 0 24 24"><path d="M7 5.6v1.7l2.6.9v3.9L7 13v1.7L17.5 11V9.3L7 5.6zm4.2 6V8.8l4 1.4-4 1.4zm-5.7 5.6V5.5H4v14.3l3.6-2.2-.8-1.3-1.3.9z"/></svg>
```

text-horizontal:

```
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" style="enable-background:new 0 0 24 24" viewBox="0 0 24 24"><path d="M8.2 14.4h3.9L13 17h1.7L11 6.5H9.3L5.6 17h1.7l.9-2.6zm2-5.5 1.4 4H8.8l1.4-4zm7.4 7.5-1.3.8.8 1.4H5.5V20h14.3l-2.2-3.6z"/></svg>
```

**Comment by mtias** [comment]
There's also #20926. @jasmussen can we consolidate all the issues and close them?

**Comment by jasmussen** [comment]
Yep, I closed that one in favor of what this PR solves.

**Comment by carolinan** [comment]
With updated icons:
Typography panel text orientation buttons

**Comment by jasmussen** [comment]
Looks great, thanks for adding those icons. 

I'm happy to give a green check, but I can't find the text orientation control in my paragraph, what am I doing wrong?
Screenshot 2023-06-13 at 11 24 56

**Comment by carolinan** [comment]
It is disabled by default, did you enable it in theme.json?

**Review by jasmussen — APPROVED** [review]
Works well and prominence is managed in the toolspanel:

orientation

The above full paragraph isn't the best example of a decorative use case, but the base CSS is going to be very useful. 

I would appreciate a code sanity check. Thank you Carolina!

**Comment by jasmussen** [comment]
Yes, apologies on the theme.json part. Still caffeeinating.

**Comment by carolinan** [comment]
I wonder if there is a way to turn off the text alignment **toolbar** option when the vertical orientation is used. It does nothing.

**Comment by jasmussen** [comment]
It does represent the styles applied, even if those styles don't do anything, so I'd keep all that as-is.

**Comment by jasmussen** [comment]
What's the main blocker for this one?

**Comment by carolinan** [comment]
Code review.

(I don't feel strongly about this going into 6.3.)

**Comment by jasmussen** [comment]
The code here works super well, the feature has its prominence balanced through the ellipsis menu, and it's a really nice design tool. I broadened the ping range a bit as I'd _love_ to see this land in 6.3.

**Review by aristath — APPROVED** [review]

**Comment by draganescu** [comment]
@jasmussen the code looks great - adds another piece, does nor introduce potential future legacy issues. Do you want to hold back on merging, because of doubts about the usefulness?

**Comment by jasmussen** [comment]
No, I'm super antsy to get this in, I just don't want to press the green button on behalf of anyone :)

**Comment by aristath** [comment]
>  I just don't want to press the green button on behalf of anyone :)

Merged 👍 
This is a safe change, and it's actually necessary so we can move to the next step. In a follow-up PR we should add more options for text-orientation & writing-mode, so it can be used in other scenarios as well as vertical languages 🙇

**Comment by jasmussen** [comment]
🚀 

Thanks for working on this!

**Comment by mtias** [comment]
Can we also support bottom up direction?

**Comment by carolinan** [comment]
> Can we also support bottom up direction?

Yes, with transforms. I still need to figure out how to use more than one CSS property for one typography setting in the style engine.

**Comment by jasmussen** [comment]
> Yes, with transforms. I still need to figure out how to use more than one CSS property for one typography setting in the style engine.

Related to this comment, and also [as noted here](https://github.com/WordPress/gutenberg/issues/20926#issuecomment-1611479881), can we leverage the text-align buttons for this flipping?

vertical text paragraph with text align dropdown open

Essentially when you choose "text align right" in that case, it'd transform/flip the text.

**Comment by carolinan** [comment]
I like that!

**Comment by tellthemachines** [comment]
@carolinan I'm trying to test this change and can't find the orientation control in the typography panel for Paragraph blocks. Am I missing something? Does this have to be enabled in the theme?

**Comment by carolinan** [comment]
Yes, this setting is disabled by default and can be enabled for themes that include theme.json. It is in the testing instructions.

**Comment by tellthemachines** [comment]
Oooh I missed that somehow, thanks!

**Pull request merged**
