### PR TITLE
[RNMobile] Show button settings when the Button block is initially added

### LINKED ISSUE #2657: Button settings hidden when block first added
**Describe the bug**
When adding a button block, the block isn't wide enough to display the settings button. 
 
**To Reproduce**
1. Create a new page or post
2. Add the **Buttons** block
3. Start typing the button label
4. Notice the settings button eventually appears

**Expected behavior**
I would expect the settings button to always be visible 

**Screenshots**

Untitled 2020-09-23 16-09-26

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2657

Gutenberg Mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/2671

## Description
Currently, when the Button block is added the block isn't wide enough to display the settings button. You would have to type some text for it to become visible. This change increases the `minWidth` of the Button block so that the control has enough space to be shown. 

## How has this been tested?
This has been tested by adding the Button block to the canvas on both Android & iOS and the settings button is visible. 

To test: 

1. Open the inserter. 
2. Add the Button block. 
3. Observe that the settings button is visible without typing anything. 

## Screenshots 

iOS | Android 
--------|-------
 <kbd></kbd>      |     <kbd></kbd>
  
## Types of changes

- This PR currently branches from a button fix, thus it will remain a draft until that PR is merged and the base branch is then set back to `master`. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jd-alexander** [comment]
@etoledom @guarani let me know if you would be able to give me a review here. I had branched from a button fix branch so I am seeing the commits even though the diff doesn't show those changes because I synced with `master`. Let me know if I need to get this resolved or it's fine 🙏

**Comment by etoledom** [comment]
Since we squash-merge, starting a PR from another branch that is then merged to master is always a bit troublesome. But agains, since finally it's a squash and there are no extra diffs, I think it should be OK.

What I usually do in these cases, is to rename the branch locally, start a new branch with the same name than this one from master, cherry-pick the commits, track the new branch to this remote one and force-push. In this way the commits are clean (if there's a better way I'd be glad to know it!).

**Review by etoledom — APPROVED** [review]
Working great as expected 🎉 !

Thank you @jd-alexander for this improvement 🙏

**Comment by guarani** [comment]
For the record, tested and working great too. Thanks @jd-alexander !

**Comment by jd-alexander** [comment]
Nice @etoledom I did what you said and it worked perfectly. The history is now clean. Loving these cool git tricks 😉

**Comment by jd-alexander** [comment]
@etoledom could you re-run this for me? I just did with an empty commit but still got a failure. I will be able to merge things after this PR is in which will make three 😄

**Comment by etoledom** [comment]
Everything ✅ 
Let's :shipit: 

Great job @jd-alexander ! 🎉

**Pull request merged**
