### PR TITLE
[RNMobile] Tweaks to Badge Component's Styling

### PR DESCRIPTION
**Pull request by SiobhyB**
`gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3642

## Description

This PR includes some tweaks to the badge component's styling. Specifically, it reduces its padding and changes the background color to a darker gray. 

## How has this been tested?

The updated badge component was compared to the original design mocks here:

| Padding | Margin |
| ------------- | ------------- |
|  |  |

To view the badge component:

* Navigate to the post editor in Android and add an image block.
* Upload an image to the image block and set it as the post's featured image (via Post Settings).
* Observe the _Featured_ badge to the block's upper right.

## Screenshots 

| Before  | After |
| ------------- | ------------- |
|  |  |

_Tested on a Pixel 3a emulator, Android 10_

## Types of changes

* A few [tweaks were made to the badge component's _style.css_ file](https://github.com/WordPress/gutenberg/pull/32865/files#diff-59da596260b632571075a233c14c4c1277bdb8937125bc43fa2d153c4e0f79ab), with an updated background colour and margin/padding updates to match the component's initial design mocks.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by SiobhyB** [comment]
@iamthomasbishop, I've made an initial pass at correcting the component's styles based on your feedback. I've followed the original padding/margin for the badge component, but let me know if there's anything else you think needs changing here.

I prefer the larger margin when the badge is by itself (without the edit button displaying) but wondered whether the badge may now look a bit "off" when displayed alongside the image block's edit button. It's possible I've been staring at this too long. :D I'll defer to your preference here, as I don't have a super strong opinion either way.
 
| Margin: 10px | Margin: 8px |
| ------------- | ------------- |
|  |  |

**Comment by iamthomasbishop** [comment]
Thanks for the ping, @SiobhyB ! This looks pretty good, esp the last example above, because it's closer to vertically centered with the edit button on the opposite side:

<a href="https://user-images.githubusercontent.com/1200432/123006133-dd788280-d37c-11eb-93aa-14226a3d7cac.png"></a>

Let's roll with that for now,  and we can always iterate if necessary in the future. Nice work!

**Review by iamthomasbishop — APPROVED** [review]
Thanks for the ping, @SiobhyB ! This looks pretty good, esp the last example above, because it's closer to vertically centered with the edit button on the opposite side:

<a href="https://user-images.githubusercontent.com/1200432/123006133-dd788280-d37c-11eb-93aa-14226a3d7cac.png"></a>

Let's roll with that for now,  and we can always iterate if necessary in the future. Nice work!

**Comment by SiobhyB** [comment]
Thank you for this @iamthomasbishop, I've gone ahead to update the margin to the `8px` option shown in your second screenshot and I'll merge this tomorrow, when the (unrelated-to-this-PR) issues with the e2e failures are resolved. :)

**Pull request merged**
