### PR TITLE
Site editor: Updated template content

### PR DESCRIPTION
**Pull request by MichaelArestad**
## Before
image

## After
image

Notes:
* The white background is specific to a theme and isn't a change.
* I did have to completely rebuild my dev environment to see changes.

### CODE REVIEW

**Review by epiqueras — COMMENTED** [review]
Beautiful.

@mtias, are you ok with this for now? I think it was good to have columns in there to remind us of how much work those interactions need.

**Review by mapk — APPROVED** [review]
I really like this change. It works and communicates the FSE experience so much better! Thanks, @MichaelArestad.

**Comment by mtias** [comment]
Yes, definitely want to preserve columns here. It exposes a lot of areas we need to improve.

**Comment by MichaelArestad** [comment]
@mtias Got it. I'll add both in another PR this week. Thanks.

**Comment by mtias** [comment]
I think the left site title and right menu is a good one to test given how ubiquitous. Then we could have different templates for with / without sidebar for the main content.

**Comment by MichaelArestad** [comment]
@mtias I did away with that because the template part is restricted to the theme's main column width. It just looked broken on Twenty Twenty.

**Comment by epiqueras** [comment]
Can't we resize the column?

**Comment by MichaelArestad** [comment]
> Can't we resize the column?

Good question. I think what we need is the max-width for post content, but no max-width for other template parts.

**Comment by epiqueras** [comment]
So, full alignment for the template part?

**Comment by MichaelArestad** [comment]
> So, full alignment for the template part?

Yep!

**Pull request merged**
