### PR TITLE
FormToggle: component styles for external use

### LINKED ISSUE #8871: FormToggle: Component wrongly styled
**Describe the bug**
When rendering a `FormToggle` component outside WordPress, it is displayed with wrong styles because of the lack of the WordPress core styles.

**To Reproduce**
- Demo: https://mmtr.github.io/wordpress-components/#/form-toggle
- Code: https://github.com/mmtr/wordpress-components/blob/master/src/examples/form-toggle.jsx

**Expected behavior**
It is styled like if the component is rendered inside WordPress.

**Screenshots**
screen shot 2018-08-11 at 12 34 58
screen shot 2018-08-11 at 12 35 05

**Desktop:**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

### PR DESCRIPTION
**Pull request by jrtashjian**
## Description
Identified styles causing rendering issues with the FormToggle component outside of the block editor.

## How has this been tested?
1. Created a new plugin utilizing React and the `@wordpress/components` package.
2. Imported and rendered a FormToggle component as well as a ToggleControl component.
3. Verified component looks as issue #8871 has described (and shown with images).
4. Verified component looks correct within the block editor.
5. Applied CSS fixes to component.
6. Verified component looks correct and unchanged within the block editor.
7. Verified component looks correct in the test plugin (outside of the block editor).

## Screenshots

*Broken:*

formtoggle-broken

*Fixed:*

formtoggle-fixed

## Types of changes
Fixes #8871

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by simison** [comment]
Does it still work also when the element is disabled? (disabled state had some styling issues previously)

**Comment by ajitbohra** [comment]
Toggle works fine in the plugin, but not rending as expected outside editor 

To test `FormToggle` and `ToggleControl` in isolation check
https://wpcalypso.wordpress.com/devdocs/gutenberg-components
https://wp-storybook.netlify.com/

**Comment by gziolo** [comment]
@jasmussen and @kjellr - can you help to land this PR as it seems like @jrtashjian doesn't work on it anymore.

**Comment by jasmussen** [comment]
Thank you for this PR. I just took it for a spin, and honestly, it seems _perfect_ to me as is, and no other change should be made IMO.

To answer @simison, if the form toggle gets wrapped in the `components-disabled` wrapper, it looks like this:

screenshot 2019-02-06 at 10 02 24

To answer @ajitbohra, this is how it looks like on storybook:

storybook

This is how it looks like on the calypso devdocs:

no margin change

So you can see it's offset. But this is CSS bleed that we, in my opinion, should not accommodate in this PR, but report as a bug in Calypso. Behold this wonderful that is inherited from Calypso:

screenshot 2019-02-06 at 09 58 48

If we uncheck that margin ... 

screenshot 2019-02-06 at 10 08 58

We get this:

toggle

That margin is pretty broad and heavy handed, so it should be fixed in Calypso. 

👍 👍 to this PR as is!

**Review by gziolo — APPROVED** [review]

**Comment by gziolo** [comment]
@jrtashjian congrats on your first code contribution to Gutenberg and thank you, everyone, for help with reviews 💯

**Comment by jrtashjian** [comment]
Awesome. Thanks everyone! 🎉

**Comment by ajitbohra** [comment]
@jrtashjian thanks for your contribution to Gutenberg.

Shared those links for reviewers to check component in isolation.

**Pull request merged**
