### PR TITLE
Use NPM workspaces

### PR DESCRIPTION
**Pull request by yusuke-omae**
## What?
Enable npm workspaces.

## Why?
npm workspace can detect incorrect management of monorepo.
This PR is a follow-up to #48950 and #53426.

### CODE REVIEW

**Comment by gziolo** [comment]
@kevin940726, I see some Ci jobs failed. Do you remember what other changes were necessary to enable workspaces?

**Comment by kevin940726** [comment]
I don't recall exactly the parts needed, but I also don't remember having to change so many lines in `package-lock.json` 🤔. I think there might be something wrong there and maybe we could try regenerating them?

**Comment by gziolo** [comment]
The difference was that the local packages were still listed as dependencies in the `package.json` in the old PR:

Screenshot 2024-06-18 at 09 18 04

I'm wondering how the changes proposed in this PR impact how dependencies get resolved. Do all of them get recognized as production or development dependencies? I also wonder what implications it has on how we scan licenses, as there is a more relaxed set of rules for dev dependencies.

**Comment by sirreal** [comment]
@yusuke-omae 👋 Thanks for starting on this. Work to migrate to npm workspaces was unintentionally duplicated in https://github.com/WordPress/gutenberg/pull/65681. If you're interested in collaborating on it please help out there.

**Pull request closed without merging**
