### PR TITLE
Delay private publish

### LINKED ISSUE #9396: Setting post visibility to "private" forces immediate publishing of post
When publishing a post, if you set the visibility to "private" in the pre-publish panel, a browser notification appears, asking if you want to immediately publish the post as private. Dismissing the notification reverts the selection, and approving it publishes the post immediately.

This also happens in the document settings sidebar, where it's even more likely that users wouldn't want to immediately publish their post:

I'm not sure if this is by design, but it feels like unexpected behaviour, especially when it's presented in line with the public/password-protected options, both of which don't force an immediate publish. We also skip all of the pre-publish and post-publish checks altogether when using this approach, which means the publishing experience feels markedly different when publishing a private post. 

## Steps to reproduce

1. Write a post.
2. Press the "Publish" button.
3. Open the "Visibility" panel.
4. Select the "Private" radio option.

### PR DESCRIPTION
**Pull request by earnjam**
**Update:** This PR no longer changes the verbiage on the Publish button per feedback. [See updates below](https://github.com/WordPress/gutenberg/pull/12023#issuecomment-494741488) for most recent details.

## Description
This is an approach to setting private visibility that doesn't immediately publish the post. Instead it changes the verbiage on the publish button and disables the save draft button, allowing a user to continue working on the post before going live. 

Fixes #9396 

### With the pre-publish panel
private-publish-prompt

### With immediate publish
immediate-private-publish

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @earnjam,

I'm noticing a bug in this branch:
Create a new post, write a time, random content.
Set a publish date for the future.
Set visibility to private.
Press schedule and finish the process.
Reload the post and now the post visibility is set to public.

**Comment by earnjam** [comment]
Thanks for catching that @jorgefilipecosta

In the classic editor, if you set post visibility to private, then the post date didn't matter. It was live for any logged in user, and hidden (returns a 404) for any non-logged in user. This makes sense because all scheduled posts are visible for logged in users. So scheduling doesn't matter if it's private, but we should just make sure to account for the date when transitioning from private to public. 

I'll update the branch so that `private` takes priority over `future` when setting post status. The opposite is true in this PR currently.

**Comment by gziolo** [comment]
@earnjam - do you have any plans to update this patch to address feedback from @jorgefilipecosta and ensure that code is refreshed to use all the latest changes from `master` branch? We could include it in the next Gutenberg 5.1 release when it's ready.

**Comment by gziolo** [comment]
In two weeks.

**Comment by earnjam** [comment]
I rebased `master` and fixed the issues with scheduled vs private and the associated labeling. Should be good for review now.

**Comment by youknowriad** [comment]
Thanks for the update @earnjam 

Added a "Needs design feedback" label. This PR changes the flows a little bit and to be honest, whenever we touche these buttons and anything related to "post status", I freak out as it's very sensible, it affects (scheduling, autosaves, metaboxes,dirty checking...).

Let's get some design eyes and if it's a good direction, let's make sure we test this PR properly.

**Comment by mapk** [comment]
Hey @earnjam I'm sorry no one has provided a design review. I'd like to provide one, but can't get this PR running locally. Can you rebase it?

I prefer the pre-publish panel to stay inline with the current publish flow. Thanks!

**Review by aduth — COMMENTED** [review]
If I recall correctly the challenges around setting private visibility without publishing, I would have expected to see some more changes here to the underlying data mechanics of considering a post as "saveable" (e.g. `isEditedPostSaveable`). Otherwise, I suspect the autosave mechanic could still save the post in an unintended state? Likewise for Cmd+S ? It seems this should be forbidden at the data flow (the `savePost` action), not just hidden from the interface.

**Comment by sarahmonster** [comment]
Hi @earnjam! I'm trying to test this branch locally but I'm running into some errors:

```
getInsertUsage@http://localhost:8888/wp-content/plugins/gutenberg/build/editor/index.js?ver=1556206494:38503:3
buildBlockTypeInserterItem@http://localhost:8888/wp-content/plugins/gutenberg/build/editor/index.js?ver=1556206494:38652:16
./packages/editor/build-module/store/selectors.js/getInserterItems<@http://localhost:8888/wp-content/plugins/gutenberg/build/editor/index.js?ver=1556206494:38702:6
callSelector@http://localhost:8888/wp-content/plugins/gutenberg/build/editor/index.js?ver=1556206494:6277:18
runSelector@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=1556206494:2420:23
./packages/editor/build-module/components/inserter-with-shortcuts/index.js/__webpack_exports__.default<@http://localhost:8888/wp-content/plugins/gutenberg/build/editor/index.js?ver=1556206494:18158:12
getNextMergeProps@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=1556206494:1983:14
ComponentWithSelect@http://localhost:8888/wp-content/plugins/gutenberg/build/data/index.js?ver=1556206494:2001:28
zf@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:69:258
Mf@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:87:4
ph@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:98:474
eg@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:125:307
fg@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:126:168
wc@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:138:237
fa@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:137:115
lg@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:148:342
re@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:23:322
Xb@http://localhost:8888/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:40:304
```

Other than that (not sure it's related, I seem to be finding all the strange errors of late) this feels like a better solution than the current setup where selecting private visibility immediately publishes the post. 😱

One thing I noticed whilst testing is that there's some inconsistency in the way the three different visibility options behave:



*Public* sets the publish button text to "publish", and the status to "public".
*Private* sets the publish button text to "publish privately", and the status to "private".
*Password protected sets the publish button text to "publish", and the status to "password protected". 

To increase consistency here, I'd recommend either:

a) Keeping the text of the publish button consistent, regardless of visibility settings.
b) Changing the text of the publish button when publishing a password-protected post.

My instinct is to opt for a) here, especially since the visibility is then reiterated in the pre-publish panel, which is going to be redesigned a bit to aid in user certain when publishing (see #7602 for more), but I'd love additional feedback from a user experience perspective.

**Comment by earnjam** [comment]
@sarahmonster I last updated this PR ~2 months ago, so I wouldn't be surprised if has new issues by now. I'll take a look at it.

**Comment by earnjam** [comment]
@aduth I'll look more closely at it to confirm, but since the autosave mechanic should only be saving revisions, it seems like it would be unaffected by this. 

I suppose for a new post that has yet to be published, autosave updates the original post, which has a status of `auto-draft`, so perhaps there is a risk there that the autosave mechanic would change that status to `private`?

**Comment by aduth** [comment]
> I suppose for a new post that has yet to be published, autosave updates the original post, which has a status of `auto-draft`, so perhaps there is a risk there that the autosave mechanic would change that status to `private`?

That's what I'm worried about, yes.

**Comment by sarahmonster** [comment]
@earnjam How can we help move this PR forward? It's been identified as a high-priority accessibility issue in #15328 and this seems like a good solution, so it would be super fantastic to see it implemented. 🙌

**Comment by earnjam** [comment]
I’ll revisit this this week and see if we can get this across the finish line.

**Comment by mapk** [comment]
I just tried testing and got an error on this PR.

`Notice: Trying to get property 'base' of non-object in /var/www/html/wp-content/plugins/gutenberg/gutenberg.php on line 117 `

**Comment by earnjam** [comment]
> I just tried testing and got an error on this PR.
> 
> `Notice: Trying to get property 'base' of non-object in /var/www/html/wp-content/plugins/gutenberg/gutenberg.php on line 117 `

The branch hasn't been touched in ~3 months, and it doesn't have any changes to `gutenberg.php`, so that's probably an old issue that is no longer relevant. I'll get it rebased so we can more accurately test.

**Comment by jasmussen** [comment]
Thanks for working on this. 

I would strongly echo Sarah's suggestion here: 

> a) Keeping the text of the publish button consistent, regardless of visibility settings.

This ensures that we don't need to have a separate mobile story for this, where "Publish privately..." won't fit, and even less so when translated to German which adds 20%.

I agree "Publish..." might feel like strange verbiage and subtly implies "private", but of the options immediately on the table it still feels like the best option. 

Would love thoughts from @mtias as well, as I recall him having some thoughts on the private visibility control.

**Comment by jasmussen** [comment]
One additional thought: we have a new "Snackbar" component that can show unintrusive notifications. We could pop up one saying "Your post will not be public". Or, if we like that train of thought, we could even show an old fashioned Notice, that says "This post is will be published as private.", and depending on the strenght we could make that notice undismissable until the post is public.

**Comment by earnjam** [comment]
Just rebased from `master` to get this branch back up to date. Not seeing the errors described by @sarahmonster or @mapk. 
I also: 
- dropped the `Publish Privately` labels on the button and just went back to `Publish` per recommendation.
- confirmed that this does not mess with auto-saves and will not inadvertently publish content as brought up by @aduth 

I think the main thing I'd like to get some design/UX feedback on is the flow of going from a privately published post to a draft. 

In the classic editor, we had two separate inputs—one for controlling status, the other for visibility. Technically, they are both are part of the same thing since visibility is just a post status of `private` vs everything else. Because of that, you could not have a post that was both `private` and a `draft`. 

So this was the flow when going from a privately published post back to a draft.

public-to-private-classic

You had to switch visibility to `public`, and then post status to `draft` to get the `Save Draft` button to display.

In Gutenberg, we don't have a post status input. The `Publish` and `Save Draft` buttons control it. So this is the current flow:

gut-revert-to-draft

Visibility is auto-switched back to `public`. This makes sense because we're saving the post as a `draft`, so it can't have `private` as the status. 

The concern here is a user not realized they had lost their visibility setting when switching to a draft. Do we want to let it revert back to `public` like this? Or would it be better to try to maintain `private` as the visibility setting after saving the status as `draft`? The downside of that is the post would remain dirty and if the user tried to navigate away, they would get a warning of unsaved changes despite having just clicked the button to save it as a draft. 

Another possibility is using one of the notification options mentioned by @jasmussen to let the user know that the visibility was also set back to public when they converted to draft.

**Comment by sarahmonster** [comment]
This issue may become either easier, or thornier, with changes slated in #12788, which aims to introduce a "status" indicator to the "Status & Visibility" section. 

Since Status and Visibility are different things and they're presented to users as different things, it should be possible to have a `draft` (status) and `private` (visibility) post. It sounds like this might not be possible from a technical perspective, but that's likely to lead to more awkward work-arounds.

> Or would it be better to try to maintain private as the visibility setting after saving the status as draft? The downside of that is the post would remain dirty and if the user tried to navigate away, they would get a warning of unsaved changes despite having just clicked the button to save it as a draft.

This would definitely be better from a user experience perspective, with the exception of unsaved changes warning. How could we avoid that situation?

**Comment by earnjam** [comment]
> This issue may become either easier, or thornier, with changes slated in #12788, which aims to introduce a "status" indicator to the "Status & Visibility" section.
> 
> Since Status and Visibility are different things and they're presented to users as different things, it should be possible to have a `draft` (status) and `private` (visibility) post. It sounds like this might not be possible from a technical perspective, but that's likely to lead to more awkward work-arounds.

You can see in the gif I posted above, the old editor didn't allow that. It just auto-changed status to `Privately Published` once visibility was set to `private`. Not sure that's best solution, but that's the prior art. 

 
> > Or would it be better to try to maintain private as the visibility setting after saving the status as draft? The downside of that is the post would remain dirty and if the user tried to navigate away, they would get a warning of unsaved changes despite having just clicked the button to save it as a draft.
> 
> This would definitely be better from a user experience perspective, with the exception of unsaved changes warning. How could we avoid that situation?

Not sure we can because it is actually an unsaved change. Saving it means it wouldn't be a draft anymore. We'd have to come up with a way to store that information temporarily (possibly in postmeta?)

**Comment by sarahmonster** [comment]
So I think the crux of the problem here is that, as a user, `status` and `visibility` are presented as two different, largely unconnected, elements. It doesn't necessarily make sense that changing the _visibility_ of a post should change the _status_. 

How is this set up from a technical side of things? Are visibility settings stored in the same database location as the status? (I am guessing yes, but I can't find a good map of the WordPress database structure to confirm this guess.) I'm wondering if there's a way we could skirt the technical issues in order to make for a clearer user experience here.

**Comment by earnjam** [comment]
@sarahmonster Yep, exactly right.

Visibility has 3 settings: Public, Private, Password.

**Public:** basically no change.
**Private:** `post_status` is set to `private`
**Password:** Some value is saved to the `post_password` column in `wp_posts`. Since it is a separate column, it can technically be applied to any post status. 


Because of that, private is the tricky one. I'm sure we can dig up some old discussions on Trac about why it was split out to the Visibility select.

**Comment by sarahmonster** [comment]
So, the `ideal` solution here is definitely to have the database structure reflect what we show to users, so we don't need to create awkward workarounds, but I'm aware that may be some amount of hassle that may not be strictly warranted here.

What about repurposing that `post_password` column and storing the post visibility there? It'd definitely be a hacky solution, but it's sort of related, and it would allow us to keep visibility separate from status, avoiding unexpected behaviours like these.

**Comment by mapk** [comment]
> So I think the crux of the problem here is that, as a user, status and visibility are presented as two different, largely unconnected, elements.

Sarah's point here is spot on! We're presenting the user with a mix of signals, but at least keeping the database clean.

> What about repurposing that post_password column and storing the post visibility there? It'd definitely be a hacky solution

I'm cringingly agreeing here. I almost feel like I'd rather hack the database to provide the user with a clear UX rather than the other way around right now. If it's possible without breaking things of course.

**Comment by mapk** [comment]
Here's my experience in this PR right now.

private

**Comment by youknowriad** [comment]
> I'm cringingly agreeing here. I almost feel like I'd rather hack the database to provide the user with a clear UX rather than the other way around right now. If it's possible without breaking things of course.

That's not something we could consider. It has huge backward compatibility concerns as Gutenberg is not the only possible editor for WordPress, there's the classic editor, there are other alternative editors as well. I don't think that's reasonable.

I agree that it's not ideal to have the visibility and the status and I know that I'm not proposing solutions here but that's the reality here. Changing the database structure (which also means the REST API) is something very impacting that takes time. Is it worth it the efforts that it requires? It's very unclear.

**Comment by mapk** [comment]
> That's not something we could consider.

Completely fair. Glad to have your comment to keep us within limitations. 😉 Alrighty, maybe looking at the snackbar notifications as proposed above should be considered?

**Comment by sarahmonster** [comment]
I'm concerned that this will have knock-on effects that will create suboptimal or cascading effects across the user experience, especially as we cement the "visibility is different from status" in #12788. I also understand this is a lot of work, and it sounds like that's not an investment we can or want to make right now.

Ultimately, this means we'll continue to need to create some kind of awkward workaround to account for the mismatch. I'm not sure that this solution is going to be better than the previous solution. Users may have already learnt to work with the existing workaround, so let's not make them learn a new one.

Until we're able to invest the time and resources into fixing the data structure, we should close this PR.

**Comment by earnjam** [comment]
> Until we're able to invest the time and resources into fixing the data structure, we should close this PR.

Why? The A11y issue of #15328 still remains and is a pretty big one. 

I'd lean more toward reverting to the classic editor visibility workflow in the short term, which has been around for many years and is an improvement on the status quo, than simply punting this issue until we have time to wade into the mess that will result from changing data structure. 

Realistically speaking, I don't foresee this part of the application design changing anytime soon.

**Comment by mapk** [comment]
> I'd lean more toward reverting to the classic editor visibility workflow in the short term, which has been around for many years and is an improvement on the status quo

Can you provide an example of this flow, @earnjam? If this is something you can rework in this PR and it fixes the a11y issue, let's try it out.

**Comment by earnjam** [comment]
I've rebased master onto this branch and updated. It's got a couple of failed e2e tests that I think just need to be updated to reflect some UI changes. I'll fix those this morning, but it would be good to get design/UX feedback on this, because that's still the major holdup. 

> > I'd lean more toward reverting to the classic editor visibility workflow in the short term, which has been around for many years and is an improvement on the status quo
> 
> Can you provide an example of this flow, @earnjam? If this is something you can rework in this PR and it fixes the a11y issue, let's try it out.

@mapk The flow in this PR is essentially the flow from the classic editor. 

Quick highlights:
- You can set to private and continue working on the post until you're ready to publish. 
- The post is considered dirty with that change, so if you navigate away after switching, it will warn you. 
- The save draft button is hidden on switching to private because you can't have a private draft. (private is a non-draft status similar to published) 
- Once the private post is "published", the switch to draft button returns, allowing you to "unpublish"

I think the remaining question is [one I posed earlier in the thread](https://github.com/WordPress/gutenberg/pull/12023#issuecomment-494741488), about how to handle the switch back to draft after "publishing" the private post. It will kick the visibility back to public because you can't have a private draft. (Both are stored in `post_status`. Draft is basically the same thing as private but with the possibility of a floating date. Private must have a date set.) Is that too confusing? 

Should we add a snackbar notice or something similar to make that more obvious that it has occurred? It's possible a user might switch a published private post to a draft, then publish again not realizing that it had changed to public.

**Comment by earnjam** [comment]
Ok, tests are passing now. 

This primarily needs UX feedback, since there isn't much programmatically changed here.

**Comment by mapk** [comment]
> Draft is basically the same thing as private but with the possibility of a floating date. Private must have a date set.) Is that too confusing?

Yes! 😆 This whole system of draft vs. private vs. published leaves me in confusion every time.

> Should we add a snackbar notice or something similar to make that more obvious that it has occurred?

Yes again. If we're switching a setting on the post that isn't obvious to the user (ie. switching a draft post back to public) we should alert the user. That's kinda a big deal. A Snackbar notification sounds like the right way to go. Can you include that in this PR, @earnjam?

**Comment by earnjam** [comment]
@mapk We already show a snackbar notice when reverting to a draft. What do we think about modifying the message in the notice to something like this? I worry it isn't visible enough. 

Current notice:
Screen Shot 2020-03-18 at 7 41 03 PM

Modified message:
Screen Shot 2020-03-18 at 7 45 00 PM

**Comment by earnjam** [comment]
I should also clarify that this wouldn't be something new to this PR. Currently if you revert a `private` post to `draft`, then it switches the visibility to `public` and does not tell you. This PR does not change that.

**Comment by mapk** [comment]
Love it. Let's add that additional text to the snackbar notice! Thanks, @earnjam.

**Comment by mapk** [comment]
I just tried testing the PR and got this:

Screen Shot 2020-04-13 at 8 04 14 PM

No msg about the visibility. Is that included here?

**Comment by earnjam** [comment]
@mapk Right, that's the current version that we already have. I haven't updated it on this branch yet! 🙂

**Comment by mtias** [comment]
Missed the prior conversation here. The relationships between statuses is very convoluted and leads to an awkward experience. I agree with the comments about trying to improve it and work around the data and status design. That's the point of the "switch to draft" action as well, as it encapsulates something that makes sense for the user.

That said, I do worry a bit about the implications for a user switching the status and then doing a lot of changes. In my testing, after saving a draft, switching it to "private", making some updates, letting the browser sit for a bit, and then reloading the page actually ended up publishing the post as private. I don't think this experience would be super great even if we address the auto-save issue that seems to be happening. Would a user have clarity on whether things are saved or published?

Regarding the snack-bar notice, I'd suggest tweaking the wording to be something like "Post reverted to draft and reseted its visibility". Otherwise it could be misleading as a sentence — _I reverted to draft to make it private why would you say it's set to public again?!_ "Public draft" reads a bit as an oxymoron.

**Comment by mapk** [comment]
Good point @mtias. How about...

"Post reverted to draft and caused the visibility to be reset."

**Comment by earnjam** [comment]
Digging into the autosave issue mentioned by @mtias, I realized it is in fact autosaving the status change. This occurs for any status that isn't already `private`. 

I tested putting in some logic to prevent autosaves, and that worked ok because the post is considered dirty when the status is changed. So the user can't navigate away without knowing they are going to lose something. 

The keyboard saves are a harder problem to solve. [We currently block them at the UI level](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/global-keyboard-shortcuts/save-shortcut.js#L19-L26) to prevent posts from being saved if they aren't considered dirty. We could add on to that, even though it really should be handled at a lower level. Regardless of where it's done though, I don't think that randomly disabling keyboard saves is optimal when the post is otherwise considered dirty, even if we were to show a notice saying it didn't save and why it didn't save. 

Not passing the status in the autosave would allow content work to be saved, but then it doesn't know about the visibility change if you were to restore it. 

I'm running out of ideas for how to handle it. Short of data storage changes, which are frankly not likely to ever occur, I'm not sure how to tackle this in a graceful way. We'd be trading one inconsistency (a sidebar control publishing the post immediately) for a new one (blocking saves under certain conditions that wouldn't make sense to users). 

If anyone has any other ideas I'm happy to run with them, but otherwise I think I'll bow out of this one and focus on something else. 

The snackbar notice verbiage change is an independent issue from this PR. That is something that occurs right now and could be solved separately. So someone can open a PR just for that change if they want. It would require a [new label added to the list of post type labels](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L1692-L1723), so it would need a trac ticket and patch as well.

**Comment by mtias** [comment]
Thanks for attempting this and recapping @earnjam. That's my takeaway as well. There is a fundamental problem in the way the data is modelled and the UI will have to be trading faithfulness to the true state (clarity) with an inconvenient experience. In that sense, being upfront about what would happen (forcing to publish privately) is likely a better tradeoff since it reduces the potential for the user making a mistake.

I guess we could look into storing a "fake-status" of pending-private that only stores the intention of switching the status to "private" when the user goes through the publish button flow. That would allow us to present the UI as if the status was both _unpublished_ and _private_ (the real status would be just "draft" and wouldn't conflict with auto-saves).

This has its fair share of problems, though, since it's an ad hoc status that _only the editor_ (so far) would understand and not the wider ecosystem — for any other external editor, app, plugin, etc, the post would be just set to "draft", which means if you publish through any mechanism that is not the editor WordPress won't necessarily know to set it as "private" at the right time, which could lead to disclosing information and a much bigger problem than the UI inconvenience we were trying to address.

We could move a layer deeper and try to have this "fake status" at a lower level, and ensure all publish actions and hooks are able to account for it if it's set, but I'd imagine it will still possibly lead to issues if a client or flow somehow unawarely forces the "publish" status in a way that WP cannot intercept. If we were to explore anything like it, it'd probably have to be thoroughly thought out and presented more widely as a proposal since the current state has been the status quo for so long.

**Comment by earnjam** [comment]
I thought about possible ways to save it externally to status temporarily, but nothing seemed quite right and had the shortcomings you mentioned about other editors or external code not being aware of it. 

The cleanest method is just a break of backwards compatibility on `private` as a post status. But that is such a massive breaking change that I don't see that realistically happening unless it's part of a major undertaking to shift the way we handle content restrictions as a whole. That's something core has never done well and the legacy design makes it near impossible to change without breaking a lot of stuff.

**Pull request closed without merging**
