### PR TITLE
Add font-size option to cover text.

### PR DESCRIPTION
**Pull request by mtias**
This PR does two things:

* Updates `RangeControl` to have a number input, adds icon support, and moves the label to the top.
* Adds font-size support to cover text.

font-size-control

----

cc @jasmussen @karmatosed @melchoyce @westonruter

### CODE REVIEW

**Comment by jasmussen** [comment]
Love this feature. Super nice work. 

I still think this should be _the text block_, and not a separate block. But okay to explore separately, if you're okay with merging the two later on. 

I'm a fan.

**Comment by mtias** [comment]
I think if I can get to adding the "clear colors" options and refine the palette accessibility a bit, then we could look at combining next week. I agree in the long term "cover text" should disappear as it's not obvious what it does or when you should consider it over text. (This does make me regret the renaming of text to paragraph, though.)

**Review by aduth — APPROVED** [review]
The behavior is a bit odd going from "unset" to a specific font size, but I don't think we can (or care to) figure out what the default value is to assign.

**Comment by mtias** [comment]
> but I don't think we can (or care to) figure out what the default value is to assign.

I originally had the default we use in the editor, and it was alright. If this value comes through the theme add_support definition, we could use that. If the default is the same as assigned, we can avoid adding the styles. But it didn't seem too intuitive, and a theme may have dynamic sizes depending on context. A default may still be desirable but it would have to be client side only (i.e. just assign temporarily if it's not set, but don't mess with the attributes).

**Pull request merged**
