### PR TITLE
Improve documentation in CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by MaedahBatool**
## Description

Improve documentation in CONTRIBUTING.md file. Title-cased the headings and fixed grammatical/typo issues and errors.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by michelleweber** [comment]
Is there anything in particular you need reviewed?

**Comment by youknowriad** [comment]
I just wanted a quick check for the proposed changes 🤷‍♂️

**Comment by michelleweber** [comment]
In line 26, I'd move "also" before "need."

In line 51, I'd keep the original "you'll."

In line 117, lowercase a.

Otherwise, looks good!

**Comment by gziolo** [comment]
@MaedahBatool can rebase this PR and address feedback from @michelleweber? Thanks :)

**Review by gziolo — APPROVED** [review]
I applied changes myself. @MaedahBatool thanks for your contribution and @michelleweber for copy review. This looks like a nice improvement.

**Pull request merged**
