### PR TITLE
Eslint: set line width to 80

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Follows #19963 and #18048.
See https://github.com/WordPress/gutenberg/pull/19963#discussion_r373448249.

This PR changes the Prettier `printWidth` option to `80` and the `tabWidth` option to `4`.

Extract from https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#spacing:

> Lines should usually be no longer than 80 characters, and should not exceed 100 (counting tabs as 4 spaces). This is a “soft” rule, but long lines generally indicate unreadable or disorganized code.

This seems to have been incorrectly implemented by #18048. The `tabWidth` was set to `2` and the `printWidth` to `100`. While this is a "soft" rule and `100` is within that rule, Prettier _does_ enforce creating lines at an ideal width of `100`, making this a hard rule. Since most lines should not exceed `80`, it makes more sense to set it at `80`. So far we've also formatted docs at `80`, and while it's not ideal in some cases to create docs within this width, it's almost never difficult to format code within `80`.

As said before, while it's meant to be a "soft" rule, Prettier enforces `100` and uncollapses destructruring with a single line if it's below `100`. For example:

```js
		const {
			format,
			__unstableMultilineTag: multilineTag,
			preserveWhiteSpace,
		} = this.props;
```

is forced to be

```js
		const { format, __unstableMultilineTag: multilineTag, preserveWhiteSpace } = this.props;
		                                                                     // ^ Outside the 80th column.
```

Personally I find this enforcement quite annoying since my editor width is only slightly over the 80th column.

If approved, I would recommend to merge this as soon as possible to avoid having to rebase PRs twice.

## How has this been tested?

I changed the config and ran `npm run lint-js:fix`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by epiqueras** [comment]
Can you separate the PR into two commits, one that changes the config and one that runs the formatting?

Otherwise, it's impossible to review.

**Comment by ellatrix** [comment]
It even exceeds the width of the diff on Github:

Screenshot 2020-01-31 at 20 31 58
Screenshot 2020-01-31 at 20 32 10

**Comment by ellatrix** [comment]
@epiqueras Sorry about that! Config change in f676f33.

**Review by epiqueras — APPROVED** [review]

**Comment by ellatrix** [comment]
@epiqueras How did you bypass linting for #19963? There seem to be some cases with unused variable etc.

**Comment by epiqueras** [comment]
You moved `eslint-ignore` comments. Just place them correctly again.

You also need to update snapshots.

**Comment by ellatrix** [comment]
Ah, makes sense! 😅 Thanks

**Comment by ellatrix** [comment]
@epiqueras Thanks for the quick review!

**Comment by epiqueras** [comment]
Thanks for handling this! :smile:

**Pull request merged**
