### PR TITLE
RichText: Fall back to setTimeout if no requestIdleCallback

### PR DESCRIPTION
**Pull request by mcsf**
## Description

See https://github.com/WordPress/gutenberg/pull/14776#discussion_r317968149. If `window.requestIdleCallback` isn't available, fall back to ~`window.requestAnimationFrame`~ `window.setTimeout`. This approach is also used in `priority-queue`:

https://github.com/WordPress/gutenberg/blob/9c58193621b4bb913bcc6991426c1e9b97dcc9f7/packages/priority-queue/src/index.js#L1

## How has this been tested?

Make sure the behaviour introduced in #14776 is preserved both in environments that provide `requestIdleCallback` (e.g. Firefox) and those that don't (Safari).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ellatrix** [comment]
Oh, sorry, I saw usage when recording a performance profile, so I assumed it was fine. Unfortunately an animation frame won’t work I think. It will be too early if there’s multiple selection changes like the list input rule. Is there any other way to creat a fallback? Perhaps wait 100ms or so.

**Comment by mcsf** [comment]
> Perhaps wait 100ms or so.

@ellatrix: I trust your judgment on those heuristics. Would you rather implement that with just `setTimeout`, or build something atop `requestAnimationFrame`?

**Comment by ellatrix** [comment]
@mcsf not sure if it matters or what the difference may be. The important thing is that all changes have been completed and all selection changes are done. That’s why I picked an idle period. This is also fine from a UX point of view cause you cannot realize an automatic change happened before an idle period to undo it. I think 100 ms or even less is fine to replace this, I don’t think it really matters how unless there’s some way to detect idleness. The nice thing about idleness is that you’re sure all work is done, no matter how slow the browser is.

**Comment by mcsf** [comment]
> I think 100 ms or even less is fine to replace this, I don’t think it really matters how unless there’s some way to detect idleness. The nice thing about idleness is that you’re sure all work is done, no matter how slow the browser is.

Yeah, idleness is a lot nicer, but I'm fine with the trade-off that it might not be as smooth on browsers that haven't implemented `requestIdleCallback` yet. I've pushed another commit so that the fallback uses `setTimeout(_, 100)` instead of `requestAnimationFrame`. What do you think, @ellatrix?

**Review by ellatrix — APPROVED** [review]
Sounds good

**Comment by mcsf** [comment]
Thanks for the quick review!

**Pull request merged**
