### PR TITLE
[Details Block]: Adds anchor support in details block

### LINKED ISSUE #66723: Details Block: Add Anchor Support
Requesting to have anchor support for the Details Block. 

[Anchor support](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-supports/#anchor) allows editors to hyperlink to a specific details block; 

e.g. my-website.local/#website-policy could directly link to the details block where it is placed on a page. 

Anchor support is already enabled for the heading, list, and paragraph blocks (and possibly others).

### PR DESCRIPTION
**Pull request by amitraj2203**
## What?
Closes #66723 

## Why?
Adds anchor support in details block

## Testing Instructions

1. Create a post or page.
2. Insert a details block.
3. On the Inspector control, open the `Advanced Panel` and see the `HTML Anchor` option

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM! I think all static blocks need anchor support, as was done in #23197.

**Comment by t-hamano** [comment]
@amitraj2203 Could you rebase this PR? The stalling CI should work (See #66771).

**Comment by amitraj2203** [comment]
@t-hamano Done

**Comment by skorasaurus** [comment]
Thank you for your work on this =)

**Pull request merged**
