### PR TITLE
Post title: Re-add the paragraph level (without UI)

### LINKED ISSUE #53594: Regression: Post Title block doesn't support paragraph; level:"0" results in <h0> elements
### Description

Previously, the Post Title block offered the option to display the post title in a paragraph tag. It appears that this was [removed in 6.3](https://github.com/WordPress/gutenberg/commit/2875c37abc2151770f7f662838c63fdfc181e336#diff-7b855403e27d2c801f7c373431522a9ec3326befb3bc3929c8ed725e58b30e5fL31) ([also here](https://github.com/WordPress/gutenberg/commit/2875c37abc2151770f7f662838c63fdfc181e336#diff-219750c7b147906f9497f25cc7ae5c33a0ef3362f3dfb244dde22af37451de95L37)) as part of the work to pull the HeadingLevelDropdown into its own component. Given that the component supports a paragraph tag when `level: "0"`, I don't understand why this was removed.

I have a site using a Post Title block with `level: "0"`. In 6.2, it outputs a paragraph. In 6.3, it creates an `h0` element that results in some styling issues for us. Notably, the block doesn't appear to have any validation issues, I think because `0` is expected as a supported value of the `level` attribute (as it should be).

Given that this was previously supported and produces an invalid HTML element, this feels like a fairly urgent issue worth addressing in a point release.

Tagging the three people who worked on the relevant commit in hopes of gaining some context: @carolinan, @geriux, @Mamaduka 

### Step-by-step reproduction instructions

1. Paste `<!-- wp:post-title {"level":0} /-->` into post editor
2. View resulting post markup with `<h0>` elements around the Post Title

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 6.3
- No Gutenberg plugin
- Custom theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Enables using post titles as paragraphs.

Closes https://github.com/WordPress/gutenberg/issues/53594

## Why?

Previously, using a post title as a paragraph was possible by changing the markup. This ability was removed in 6.3.
This PR allows using paragraphs again, but only by editing the block markup and setting the "level" block attribute to 0.

## How?

The PR 
- Updates the condition in edit.js and index.php to change the tag to `<p>` if the level attribute is set to 0.

## Testing Instructions
Apply the PR.
Either copy and paste this code snippet into the block editor, or add a post title block and manually edit the level attribute in the code editor mode.

`<!-- wp:post-title {"level":0} /-->`

- Confirm that the element that is used for the block in the editor and front of the site is a `<p>`.
- Confirm that there are no regressions in the action of switching the levels using the block toolbar:  That switching from the paragraph to any other level works.

## Screenshot
Below is a screenshot of the post title block in the block editor. The only UI change is that the toolbar shows the paragraph icon when someone has set the level attribute to 0.

The post title block in the editor, with the paragraph showing as the current level in the block toolbar.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Nice work, this looks like a good clean fix to me!

| Before | After |
| --- | --- |
| image | image |

✅ The block still defaults as an `h2`
✅ Paragraph is now able to be selected, and outputs correctly on the site frontend
✅ All other heading levels work as expected

LGTM! ✨

**Review by t-hamano — CHANGES_REQUESTED** [review]
Sorry, I would like to temporarily pause the merging of this PR.

This is because supporting the paragraph level in the Site Title block seems to have accessibility concerns, as discussed in #30549.

Regarding support for the paragraph, the following specification changes have been made.

- Up to WP6.2, level zero (paragraph) was supported _internally_.
- In WP6.3, level zero is no longer considered, so incorrect `h0` tag is output

If we re-add paragraph block support now, we might need to remove this support again in the future if paragraph support is deemed inappropriate from an accessibility perspective. In fact, #42590, which is similar to this PR, has been closed.

I think it would be better to discuss this issue further to see if there is a more ideal solution.

@alexstine Please let me know if you have any feedback regarding this PR 🙏

**Comment by andrewserong** [comment]
Thanks for the extra context @t-hamano, I didn't realise there was so much prior discussion surrounding it! Apologies, I should have read a bit more of the history before hitting ✅. Good idea holding off for now and getting more feedback 👍

**Comment by alexstine** [comment]
@t-hamano I really don't mind if this is allowed internally that way our blocks can take advantage of it. What I don't want is this to be put in reach of end users. For example, this is a very valid use-case.

```
<ul>
<li><a href="https://www.google.com"><p>Google Title</p></a></li>
</ul>
```

This is not.

```
<a href="https://www.google.com"><p>Google Title</p></a>
```

I am very against shipping a feature to core that will allow people to output titles in a very semantically bad format for accessibility. Because one could style these links to look like a list visually with no list semantics being communicated to end users of assistive tech. Because it only uses the paragraph tag over a heading tag, it makes it even more undiscoverable. The only method would be the link itself which we all know how reliable that is, sarcasm noted.

My answer is still no for the UI but yes if it is needed internally.

CC: @afercia @joedolson 

Thanks.

**Comment by carolinan** [comment]
Yes it is because of the accessibility concerns that I did not include it when the HeadingLevelDropdown was moved to a component.
But it is also frequently requested by users.

Many use cases for linking to the current post could be solved if the Link Controls supported it.
Many use cases for linking to the home page could be solved if the Home link block worked outside the navigation block. Note that the home link only uses `<a>` in that case.

**Comment by carolinan** [comment]
Whether a title with a paragraph is discoverable or useful is going to depend on the layout. 
We can't assume that there is not a heading in addition to the paragraph.

**Comment by carolinan** [comment]
I pushed the code changes that removes the paragraph from the drop down, but I do not have time to update the PR description right now.

With this change, `<!-- wp:post-title {"level":0} /-->` should still work.

**Comment by afercia** [comment]
The use case mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/53594#issuecomment-1802301093), which is about the ability to use the Post title in a Query loop for a simple list of posts, makes perfectly sense to me. A heading would not be appropriate in that case.

However, I don't think the ability to render a heading as a paragraph should be in the heading level dropdown menu. 

Conceptually and semantically, the heading level dropdown menu is specific to the concept of 'level'. A 'level' is only for headings. The toggle button that opens the menu is labeled 'Change level'. The menu itself is labeled 'Change level'. If I remember correctly this was one of the arguments to remove the `Paragraph` option from the menu for the Heading block. Also, the Heading block can already be 'Transformed to' a Paragraph block by the means of the block switcher. A Paragraph can be transformed to a Heading as well. That changes the _block type_ though and we don't want to change the Post title block to another block type, we only want to _render_ it with a different HTML tag.

It's a _rendering_ option. As such, I'd tend to think it should go in the block variations. That wouldn't be much different from what other blocks already do. For example the Group block provides both block _transforms_ and block _varaitions_. The Group block can be transformed to:
- Another block type e.g. a Cover block.
- A Group variation e.g. Row, Stack, Grid.

I'd consider to add the HTML tag choice to the variations. It would be useful for other blocks too.

I'd also agree that it would be nice to explore an option fo render the Post title as 'Plain text', ie.: with no wrapping HTML tag.

I'd also like to remind that, for exampke. the Group block does provide a setting to choose the HTML tag the block is rendered with. It's a little buried down in the block Settings > Advanced section and it should probably be more prominent. I'd would like to see this HTML element setting moved to the block variations.

Screenshot of the Group block HTML element setting:

Screenshot 2024-04-08 at 13 24 51

I will create a new issue for discussion.

**Comment by t-hamano** [comment]
@alexstine @afercia, thank you for your comments.

Based on your opinion, is it okay to support paragraph level _internally_? In other words, we will ship this PR as is.

The Post Title block supported heading level in #22872 about 4 years ago. At the same time, it seems that the paragraph level is also supported internally (I don't know why the paragraph was was supported).

However, given this fact, I feel that allowing the paragraph level internally makes sense from a backward compatibility perspective.

> I'd also agree that it would be nice to explore an option fo render the Post title as 'Plain text', ie.: with no wrapping HTML tag.

I remembered the Block Binding API. Looking at the video attached to [this comment](https://github.com/WordPress/gutenberg/issues/53300#issuecomment-1808020238), it appears that binding the post title to any block via the UI is being considered. If this could be applied, I think it would be possible to express the post title text in a more plain format.

**Comment by carolinan** [comment]
The heading block transformation is unrelated to the post title. The post title can't be transformed to a pragraph **block** and maintain its link and title. 
It can only be placed inside a group or column.

**Comment by alexstine** [comment]
@carolinan 

> We can't assume that there is not a heading in addition to the paragraph.

We also can't assume that there will be and not having a heading is worse than a possible duplicate. Thanks for the updated PR.

**Comment by afercia** [comment]
> Based on your opinion, is it okay to support paragraph level internally? In other words, we will ship this PR as is.

I don't think the paragraph 'level' should be implemented internally as a 'level' becasue, well, it's not a level.
This applies to other blocks as well.

ReL the transforms: I didn't mean to use _block_ transforms. I suggested to consider block _variations_ transforms, which is a different thing.

To me, it seems that from an user perspective a few concepts are pretty confusing in the UI:
- Block transform as in, for example, transform a Heading to a Paragraph and viceversa.
- Block variations transform e.g. Group, Row, Stack, Grid.
- Blocks that don't change to another block type but can change the HTML tag they are rendered with from heading to paragraph and vice-versa e.g. Post Title in this PR, Site Ttitle, Site Tagline. It's not clear why the `HeadingLevelDropdown` sometimes provides the Paragraph option and sometimes doesn't. The Paragraph shouldn't be there in the first place as this menu is about _heading levels_.
- Blocks that can change the HTML tag they are rendered with in the block settings Advanced section > HTML element e.g. the Group block.

All this is extremely confusing and I'm not sure users are interested to know whether it's a _block transform_ or a _block varaition_ or a HTML element setting. The just want to _change_ how the block renders.

Overall. I'd think all these transforms / variations / HTML element settings should be reconsidered and made way ore intuitive for users.

**Comment by carolinan** [comment]
I disagree with the suggestion to move the level selection from the toolbar to the element selection in the Advanced panel.
And I disagree with moving the HTML selection from the Advanced panel to a more prominent position.


- Users should not need to know HTML to write accessible content.
- As a user, I understand that Heading 1 comes first and is largest, not because I know about HTML tags, but because I have used other word processors before like Microsoft Word or Google Docs.
- As a user I see the tooltip text "Change level". Not "Change heading level" so there is nothing that indicates that I am selecting "heading levels" only. As a user, I may have no prior knowledge of that there are 6 default HTML tags and styles that are called levels.  It doesn't matter to me as a user what the _component_ is called.

- As a user, I want to change the style and size of my text. 
 - I want it to be easy. 
 - I want it to be in the same place.
 - I don't want to have to open a panel, pick the right tab panel, find the option, understand what an HTML element is, and select `<p>`, `<h4>` and so on. If I have to take all those steps, chances increases that I am only going to change the size of my text from the typography panel instead, and I will end up with an H2 heading that looks like a paragraph.
 - I don't want one option to be in the toolbar and another in the sidebar, because all I want is for my text to look like the rest of my text, or to be a little bit larger than the rest of my text.

The HTML element selection is placed in the Advanced panel because it is an advanced tool that requires some knowledge of HTML and because it is an action that isn't used that often. Editing the text and adding appropriate headings is a more frequent action than changing a div to a span.

Using Google Docs as an example, you can select "regular text", (not "paragraph") and it is in the same option as the heading selection. (it might be "normal text", I am not sure because my Drive is in Swedish so I am translating).

Using Microsoft Word as an example, you select "normal" in the same option that you select headings. But in that option you can also select strong, quote, title, subtitle, list etc. And they are deliberately calling it a style option.

**Comment by t-hamano** [comment]
The component name `HeadingLevelDropdown` or the term "level" may be the cause of the confusion, but such a toolbar dropdown exists in the Classic Editor, so I think users are familiar with this UI. In the screenshot below, you can see that the dropdown includes paragraph, all heading levels, and preformatted.

image

**Comment by alexstine** [comment]
@t-hamano As far as I'm aware, there is not a setting in the classic editor to make a post title a paragraph. I don't honestly care if there is a paragraph option for some blocks, just not like this. If a query block wants to display the post titles as paragraphs because it is using a semantic list, great. I will never support giving users the ability to choose this from the UI. This is a feature that we should support for developers, nothing more, nothing less. Otherwise, this is going to be prone to terrible misuse.

**Comment by carolinan** [comment]
I already removed the option from the UI yesterday. The PR only fixes the regression where the paragraphed used to work when it was added manually in the code.

There is one UI change. When a developer or advanced user has manually changed the code to use a paragraph, the toolbar will show the paragraph icon.

**Review by alexstine — APPROVED** [review]
@carolinan Thanks for clearing that up.

@t-hamano I think we're good to unblock this now.

**Review by t-hamano — APPROVED** [review]
Let's ship this PR.

As mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/60548#issuecomment-2042724235), whether it was intentional or not, it's true that we've been allowing the paragraph level internally for nearly four years. This PR fixes a regression that occurred in WP6.3, and I believe paragraph levels should be allowed, at least internally, to maintain backward compatibility.

Let's continue discussing overall UI issues and improvements in a separate issue.

**Pull request merged**
