### PR TITLE
[RNMobile] Use BlockEdit component when testing component rendering

### LINKED ISSUE #29442: Use BlockEdit for block rendering unit tests
## What problem does this address?

Currently the unit tests related to rendering blocks are using the edit component of the different blocks. However the blocks are rendered in the editor through the `BlockEdit` component which includes a context with different properties like `clientID` that could be required by other logic from the blocks.

In fact, I realised when testing the changes that will introduce this [PR](https://github.com/WordPress/gutenberg/pull/29309), that rendering blocks without a `clientId` produce errors when running the unit tests, in this case the selector `isBlockSelected` which is heavily used in blocks returns `true` when the `clientId` is `undefined`.

## What is your proposed solution?

My solution here is to add extra logic to the unit tests that renders blocks, first we should register the block as the editor does and then create a function that returns the `BlockEdit` component that will render the block we want to test.

Here is an example:
```
/**
 * Internal dependencies
 */
import { metadata, settings, name } from '../index';

/**
 * WordPress dependencies
 */
import { BlockEdit } from '@wordpress/block-editor';
import { registerBlockType, unregisterBlockType } from '@wordpress/blocks';

const Block = ( { clientId, ...props } ) => (
	<BlockEdit name={ name } clientId={ clientId || 0 } { ...props } />
);

describe( '<BLOCK_NAME> Block', () => {
	beforeAll( () => {
		registerBlockType( name, {
			...metadata,
			...settings,
		} );
	} );

	afterAll( () => {
		unregisterBlockType( name );
	} );

        it( 'renders without crashing', () => {
		const component = renderer.create(
			<Block />
		);
		const rendered = component.toJSON();
		expect( rendered ).toBeTruthy();
	} );
...
} );
```

As you can see, instead of rendering the Edit component of the block, we use the `BlockEdit` component by passing the block's name through the `name` prop and a default `clientId`.

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/29442.

Add extra logic to some of the native unit tests that renders blocks:
- Register the block as the editor does
- Create a function that returns the `BlockEdit` component that will render the block that we want to test

This way, by rendering the edit components from the `BlockEdit` component, we add the block edit context that could be required by other components when they're rendered.

In fact, this is the case when the incoming changes from this [PR](https://github.com/WordPress/gutenberg/pull/29309) would be merged, the `RichText` editor component will require the `clientID` property that is [exposed from a new context](https://github.com/WordPress/gutenberg/pull/29309/files#diff-d29a003e50a56a46a0ac111e36b422fa65317ee80a5f9672d014aa5b03f0f174R58) that is rendered in `BlockEdit` component.

### Caveats

My initial approach was to apply this change to all the native unit tests that render edit components but didn't work.

For example in the `File` block, one of the tests [triggers the `onLayout` handler](https://github.com/WordPress/gutenberg/blob/5ae2b1b06666ad1a75d5e92bfbdec4b4e728b071/packages/block-library/src/file/test/edit.native.js#L44-L46). If we render the `BlockEdit` component, we don't have access to the instance required to trigger that handler so the test fails.

I spent some time on finding an alternative but I didn't find any that fits easily. One option I tried was using the `enzyme` library but when rendering the component via the `mount` function, `AztecView` generates multiple errors. Shallow rendering is not enough because the required handler that we want to trigger is in the children.

Probably the best option would be to integrate a more complete library like [`@testing-library/react-native`](https://testing-library.com/docs/react-native-testing-library/intro/), that provides a lot interesting functionality that would make easier to do native unit tests.

### Test with latest changes from `trunk` branch
1. Run `npm run native test`.
2. Observe that all unit tests pass.

### Test with changes from [PR](https://github.com/WordPress/gutenberg/pull/29309)
1. Checkout branch `try/block-context-cleanup` from the [PR](https://github.com/WordPress/gutenberg/pull/29309).
1. Cherry-pick changes from this PR's [commit](https://github.com/WordPress/gutenberg/commit/742eb696556f87707aca0517656d7464ab543bdc) without committing via the command `git cherry-pick -n 742eb696556f87707aca0517656d7464ab543bdc`.
2. Run `npm run native test`.
3. Observe that all unit tests pass.
4. Discard changes from the cherry-pick.

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by guarani — APPROVED** [review]
I confirmed that this fixes the tests in https://github.com/WordPress/gutenberg/pull/29309 🥇 .

**Comment by fluiddot** [comment]
I've just pushed a couple of changes to debug the `React Native E2E Tests (iOS)` workflow because it's failing all the time 😞 .

**Comment by fluiddot** [comment]
> I've just pushed a couple of changes to debug the `React Native E2E Tests (iOS)` workflow because it's failing all the time 😞 .

Looks like the changes have fixed the workflow so I'm going to make a separate PR for those and then update this one.

**Comment by ellatrix** [comment]
> Looks like the changes have fixed the workflow so I'm going to make a separate PR for those and then update this one.

Looks good. Can we merge this one and follow up with anything else?

**Comment by fluiddot** [comment]
> > Looks like the changes have fixed the workflow so I'm going to make a separate PR for those and then update this one.
> 
> Looks good. Can we merge this one and follow up with anything else?

I'd rather merge the changes in the e2e tests in another [PR](https://github.com/WordPress/gutenberg/pull/29589) I've just created to prevent confusion. Once it's approved I'll merge all of them and then we can update your branch.

**Comment by fluiddot** [comment]
@guarani I assigned you as a reviewer of the PR I had to create to fix the e2e tests oft this one. Let me know if you have some time to check it, if not we could find someone else to take a look, thanks 🙇 !

**Comment by fluiddot** [comment]
> @guarani I assigned you as a reviewer of the PR I had to create to fix the e2e tests oft this one. Let me know if you have some time to check it, if not we could find someone else to take a look, thanks 🙇 !

This was approved in the [PR](https://github.com/WordPress/gutenberg/pull/29589) where the e2e tests for iOS were fixed.

**Pull request merged**
