### PR TITLE
FormTokenField: Added Padding to resolve close button overlap issue

### LINKED ISSUE #41447: FormTokenField: Styling is broken when `isBorderless`
When the `isBorderless` prop is `true`, the styling of the tokens are broken. The "delete" icon is jammed too close.

## Screenshot

Broken borderless token styling

## Screen recording

https://user-images.githubusercontent.com/555336/171091093-9f1c4fa6-5008-40d9-8259-d6d1160bebe8.mp4

### PR DESCRIPTION
**Pull request by akasunil**
## What?

Fixed issue of close button overlap while isBorderless prop is true in FormTokenField component.  

## Why?
FIx [#41447 ](https://github.com/WordPress/gutenberg/issues/41447)

## Testing Instructions
Please include step by step instructions on how to test this PR.
 1. Open a Post or Page edit.
 2. Go to tags input.
 3. Add tags and check design.

## Screenshots or screencast 

CleanShot 2022-06-05 at 13 09 28@2x

### CODE REVIEW

**Review by mirka — COMMENTED** [review]
Thanks for the patch!

I can see the CSS structure is not in an optimal place to begin with. For example, the button outline is already too close to the text in the default variant, and starts to overlap text in the borderless variant. And the default/borderless switching really shouldn't be this hacky.

https://user-images.githubusercontent.com/555336/172156300-a0493706-3e66-42a3-a990-24648841d83b.mp4

But I understand that a proper fix requires a bit more in-depth reworking of the elements. So I'm fine with merging the bandaid fix in this PR for now, as it is at least incrementally better and doesn't add any complexity that would be hard to remove when refactoring.

I'd just like to rope in @jameskoster for a quick design check on the spacings. (Bonus: James, it would be cool if you could give us some updated mockups of this component so the button isn't jammed and has the newer look & feel 🙂 Not necessary for this PR though.)

**Comment by jameskoster** [comment]
Here's what I see:

Screenshot 2022-06-07 at 09 38 33

To my eye the `X` looks a little too close to the text. I think we can increase that to 24px (`$grid-unit-30`), which also helps (a little) with the outline issue:

Screenshot 2022-06-07 at 09 39 55

---

Agree this component could use some design love. I'm not sure about the history, but I don't know that we really need the 'borderless' variant, there's probably more value in a consistent appearance? It's especially strange since neither variant has a border :)

**Comment by mirka** [comment]
@sunil25393 Thanks for updating! If you could add a brief [changelog entry](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md), this PR is ready to merge 👍

**Review by mirka — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
