### PR TITLE
Issue #4455 - filter out custom taxonomies that have been overridden …

### LINKED ISSUE #4455: Custom taxonomy throwing an error
I'm registering a custom taxonomy like this:

```
/**
 * Register custom featured taxonomy
 */
function prefix_register_featured_taxonomy() {

	$labels = array(
		'name' => esc_html__( 'Featured Locations', 'text-domain' ),
		'singular_name' => esc_html__( 'Featured Location', 'text-domain' ),
		'all_items' => esc_html__( 'All Locations', 'text-domain' ),
	);

	$args = array(
		'label' => esc_html__( 'Featured Locations', 'text-domain' ),
		'labels' => apply_filters( 'prefix_featured_taxonomy_labels', $labels ),
		'public' => false,
		'hierarchical' => true,
		'show_ui' => true,
		'show_in_rest' => true,
		'show_in_menu' => false,
		'show_in_nav_menus' => false,
		'query_var' => true,
		'rewrite' => false,
		'show_admin_column' => true,
		'show_in_quick_edit' => true,
		'sort' => true,
		'capabilities' => array(
			'manage_terms' => false,
			'edit_terms' => false,
			'delete_terms' => false,
		),
	);

	register_taxonomy( 'prefix_post_featured', array( 'post' ), apply_filters( 'prefix_featured_taxonomy_args', $args ) );
}

add_action( 'init', 'prefix_register_featured_taxonomy', 10 );
```
Then I'm adding terms manually like this:

```
/**
 * Add default featured terms upon theme activation
 */
function prefix_add_featured_terms() {

	if ( get_option( 'prefix_featured_terms_added' ) ) {

		// Return if terms have already been added.
		return;

	} else {

		// Array of Featured Locations.
		$featured_terms = array(
			'slider'   => esc_html__( 'Post Slider', 'text-domain' ),
			'tiles'    => esc_html__( 'Post Tiles', 'text-domain' ),
			'carousel' => esc_html__( 'Post Carousel', 'text-domain' ),
			'archive'  => esc_html__( 'Post Archive', 'text-domain' ),
			'widget'   => esc_html__( 'Posts Widget', 'text-domain' ),
		);

		// Add terms to custom taxonomy Featured Locations.
		foreach ( apply_filters( 'prefix_featured_terms', $featured_terms ) as $term => $name ) {
			if ( ! term_exists( $name, 'prefix_post_featured' ) ) {
				wp_insert_term(
					$name, 'prefix_post_featured', $args = array(
						'slug' => $term,
					)
				);
			}
		}

		// Set an option, that terms have been added.
		update_option( 'prefix_featured_terms_added', true );

	}

}

add_action( 'init', 'prefix_add_featured_terms', 20 );
```

The taxonomy terms aren't displayed in the Gutenberg sidebar and there's an error:

`Warning: call_user_func() expects parameter 1 to be a valid callback, function 'post_categories_meta_box' not found or invalid function name in /Users/user/Dev/projects/stage/wp-content/plugins/gutenberg/lib/meta-box-partial-page.php on line 256`

### PR DESCRIPTION
**Pull request by bobbingwide**
…by gutenberg_override_meta_box_callback

## Description
Adds another test to see if a meta box for a custom taxonomy should be filtered out of the list of taxonomies destined for the Extended setting area.

The change is described in https://github.com/bobbingwide/oik-a2z/issues/8

I did not remove the test that failed to find the custom taxonomy by comparing directly against callback.
This is belt and braces; I don't know all the cases where the filter function is invoked. 

## How Has This Been Tested?
Tested manually using a custom letter taxonomy attached to posts.  
Screen captures show before and after.
Note: In the screenshots the custom taxonomy was manually marked as `show_in_rest`, so it appeared in the Categories & Tags block.

## Screenshots (jpeg or gifs if applicable):
image
image

## Types of changes
Fixes #4455.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by pento — CHANGES_REQUESTED** [review]
Thanks for the PR, @bobbingwide!

So, I think the bug here is that `gutenberg_intercept_meta_box_render()` is overriding the callback for Core metaboxes, which it shouldn't do.

I think something like this is the correct fix, if you're able to update your PR.

```diff
diff --git a/lib/meta-box-partial-page.php b/lib/meta-box-partial-page.php
index 3e6e80db..52f30ab1 100644
--- a/lib/meta-box-partial-page.php
+++ b/lib/meta-box-partial-page.php
@@ -173,10 +173,16 @@ add_filter( 'filter_gutenberg_meta_boxes', 'gutenberg_filter_meta_boxes' );
 function gutenberg_intercept_meta_box_render() {
        global $wp_meta_boxes;
 
+       $filtered_meta_boxes = apply_filters( 'filter_gutenberg_meta_boxes', $wp_meta_boxes );
+
        foreach ( $wp_meta_boxes as $post_type => $contexts ) {
                foreach ( $contexts as $context => $priorities ) {
                        foreach ( $priorities as $priority => $boxes ) {
                                foreach ( $boxes as $id => $box ) {
+                                       // Don't override meta boxes that Gutenberg handles itself.
+                                       if ( ! isset( $filtered_meta_boxes[ $post_type ][ $context ][ $priority ][ $id ] ) ) {
+                                               continue;
+                                       }
                                        if ( ! is_array( $box ) ) {
                                                continue;
                                        }
```

**Comment by bobbingwide** [comment]
Hi @Pento, thanks for your solution. I'm having trouble understanding these scenarios.

When the custom taxonomy is attached to posts then your logic is necessary.
When the custom taxonomy is attached to any other post type then it's not
...And nor is the code I started with.

**Comment by greatislander** [comment]
In testing this PR, I can confirm that it resolves https://github.com/WordPress/gutenberg/issues/4455 both for custom taxonomies added to core post types and custom taxonomies added to custom post types.

**Comment by greatislander** [comment]
Appears to be fixed by https://github.com/WordPress/gutenberg/pull/5221/.

**Pull request closed without merging**
