### PR TITLE
Enhancement  to issue #28859

### PR DESCRIPTION
**Pull request by Quintis1212**
Hello everyone ) this is enhancement  for #28859 issue. I made a  focus settings specific to an image and reset to a neutral position when a new image is uploaded

### CODE REVIEW

**Comment by stokesman** [comment]
Hi @Quintis1212, thanks for your work on this.

I was surprised by the approach here as I would have thought to handle this within the Cover block and not in the focal point picker component. But then it seems you've intended to make an extra enhancement beyond what (I interpret) is needed to resolve the issue. I can see how the title of the issue might suggest it though.

As I interpret it, the needed solution is to reset the focal point when changing the media. This PR does that. The extra enhancement would be to restore a previously set focal point for a previously used image. Though, that part didn't work for me when I tested this. 

I think it'd be best to narrow the focus of this PR to just make the reset and for that, I don't think the focal point picker component should be changed. Mostly because the changes required can be less. At present, the single place this enhancement is needed is the Cover block. The only other use of the focal point picker is in the Media & Text block and that block already resets the focal point when the media changes. The same behavior in the Cover block could be had by adding a single line. Note that the Cover block already resets the focal point when changing the media if the type of media is a video:
https://github.com/WordPress/gutenberg/blob/26560b62f9571772c5b49b6cece3271c556e97bf/packages/block-library/src/cover/shared.js#L100-L107

That's my take and hopefully, it makes sense to you as well.

**Comment by Quintis1212** [comment]
> Hi @Quintis1212, thanks for your work on this.
> 
> I was surprised by the approach here as I would have thought to handle this within the Cover block and not in the focal point picker component. But then it seems you've intended to make an extra enhancement beyond what (I interpret) is needed to resolve the issue. I can see how the title of the issue might suggest it though.
> 
> As I interpret it, the needed solution is to reset the focal point when changing the media. This PR does that. The extra enhancement would be to restore a previously set focal point for a previously used image. Though, that part didn't work for me when I tested this.
> 
> I think it'd be best to narrow the focus of this PR to just make the reset and for that, I don't think the focal point picker component should be changed. That's because there should be a solution with fewer changes. At present, the single place this enhancement is needed is the Cover block. The only other use of the focal point picker is in the Media & Text block and that block already resets the focal point when the media changes. The same behavior in the Cover block could be had by adding a single line. Note that the Cover block already resets the focal point when changing the media if the type of media is a video:
> https://github.com/WordPress/gutenberg/blob/26560b62f9571772c5b49b6cece3271c556e97bf/packages/block-library/src/cover/shared.js#L100-L107
> 
> That's my take and hopefully, it makes sense to you as well.

Hi @stokesman , i add new code to shared.js in cover block as you advised:  
`
		setAttributes( {
			url: media.url,
			id: media.id,
			backgroundType: mediaType,
			...( mediaType === VIDEO_BACKGROUND_TYPE
				? { focalPoint: undefined, hasParallax: undefined }
				: {} ),
			...( mediaType === IMAGE_BACKGROUND_TYPE
				? { focalPoint: undefined, hasParallax: undefined }
				: {} ),
		} );

`

But its work with errors : 
Снимок экрана от 2021-02-26 18-58-25

**Comment by stokesman** [comment]
@Quintis1212, That error is odd. I just tested that change on both master and then even this branch and couldn't reproduce the console error 😕 . Besides that, this would be the more appropriate change:
```javascript
		setAttributes( {
			url: media.url,
			id: media.id,
			backgroundType: mediaType,
			focalPoint: undefined,
			...( mediaType === VIDEO_BACKGROUND_TYPE
				? { hasParallax: undefined }
				: {} ),
		} );
```
It makes the reset of `focalPoint` unconditional (since both media types should reset that).

Maybe restarting the `npm run dev` could clear up the issue. That or there's something else going on in your branch and perhaps a rebase on master could help.

**Comment by annezazu** [comment]
@Quintis1212 is work continuing here on your PR? For now, going to mark as stale :) Let me know if there's any support that can be provided to help you merge any of your open PRs.

**Comment by Quintis1212** [comment]
@annezazu  Hi . I am closing this PR

**Pull request closed without merging**
