### PR TITLE
Design: Augmented shadows for modals and popovers

### PR DESCRIPTION
**Pull request by jameskoster**
By layering multiple values we can create shadows with greater resolution that better indicate elevation while maintaining subtlety. The current values are a little insipid by comparison.

### Popover
| Trunk | This PR |
| --- | --- |
| Screenshot 2022-12-01 at 13 10 34 Screenshot 2022-12-01 at 13 16 56 | Screenshot 2022-12-01 at 13 10 41 Screenshot 2022-12-01 at 13 17 02  |

### Modal
| Trunk | This PR |
| --- | --- |
|  Screenshot 2022-12-01 at 13 11 32 Screenshot 2022-12-01 at 13 21 05 | Screenshot 2022-12-01 at 13 11 40 Screenshot 2022-12-01 at 13 21 11 |

The values here are just examples, and intentionally a little stronger to best communicate the difference. They no doubt need refinement. 

Side note: It might be good to rename `$shadow-popover` and `$shadow-modal` to something like `$elevation-medium` and `$elevation-high`?

### CODE REVIEW

**Comment by jasmussen** [comment]
Oh this is a fun one, nice!

I like the high elevation one much better. The low elevation one feels like it has the right ingredients too, but it feels a bit too, well, elevated and visible, whereas the existing one feels very subtle. Perhaps it can be closer to the canvas?

**Comment by javierarce** [comment]
After a quick test, I think this looks very nice.

> Side note: It might be good to rename $shadow-popover and $shadow-modal to something like $elevation-medium and $elevation-high?

+1 it's a good idea to make this component agnostic. This should be reflected in the Library, so I'll add a label to update Figma if that idea is implemented and merged.

**Comment by jameskoster** [comment]
I tried adjusted values (changing one means changing the other as well to maintain the same 'light source config'):

Screenshot 2022-12-02 at 12 57 21
Screenshot 2022-12-02 at 12 57 32

**Review by jasmussen — APPROVED** [review]
GIFS showing the shadows under popovers before:
before
and after:

after

Improvements all around, and two sanity checks, let's try this 🙏 

I still think the low-elevation (popover) shadow is a teensy bit bottom heavy. But it would be easy to follow up on, so sounds good.

One thing though: wouldn't it be better to use pure $black for these, rather than $gray-900? Outside of actually adding a tint to the shadow I don't see any benefit in the shade of gray. But maybe I'm missing something?

**Comment by jameskoster** [comment]
I used gray-900 to bring a brand element to the shadows, but yes it's probably not needed. I'll remove it.

**Pull request merged**
