### PR TITLE
Fix docs for units

### PR DESCRIPTION
**Pull request by aristath**
EDIT: Invalid.

### CODE REVIEW

**Review by carolinan — CHANGES_REQUESTED** [review]
Thank you for looking into this but I am still not able to select different units in the padding control in my test theme. 🤔 

In the components/unit-control/README.md the code example still includes "Global" and is missing "Defaults". Global is no longer used in theme.json

**Comment by aristath** [comment]
@carolinan hmmm changing this in the Q theme fixed it on my end... https://github.com/aristath/q/commit/cb7baa400e959bfe2c6ab0ff3bb43c8f3ccd39e3 Does it not work for you?

**Comment by carolinan** [comment]
I tried the latest version of Q from GitHub, and manually updated Armando, TT1 Blocks and empty theme, tested with current trunk of Gutenberg and 10.4.1, group block and cover block in block- and site editors. The control only offers px.
Chrome, Windows 10.
Quick test with Firefox and Q, same result.

**Comment by aristath** [comment]
Hmmmm it looks like the issue is not what I thought it was. I'll close this one for now and continue debugging :+1:

**Pull request closed without merging**
