### PR TITLE
Suppress block inserter focus loop

### PR DESCRIPTION
**Pull request by guarani**
## Description

Addresses https://github.com/WordPress/gutenberg/issues/30562 (suppresses bug instead of fixing it)

Related to https://github.com/wordpress-mobile/gutenberg-mobile/pull/3681

This introduces a `setTimeout` to suppress the focus loop issue that was uncovered by the block inserter search focus issue.

## How has this been tested?

1. Run the packager from the linked Gutenberg Mobile PR: `npm run start:reset`
2. Build and run the WordPress for iOS app in Xcode
3. Open the editor and expect the bundle to load from the running packager
4. Try to reproduce the bug described in https://github.com/WordPress/gutenberg/issues/30562:
  a. With the cursor in a block that contains text, add a new block via the new block inserter search
  b. Ensure that block selection and keyboard focus don't behave unexpectedly
5. Repeat the previous step with VoiceOver on

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by guarani** [comment]
Admin tests failing, re-running ⏳

**Comment by guarani** [comment]
I gave this a quick test and it does seem to work ok. I do notice a slight delay between inserting a block and the keyboard focus moving to the new block.
I'm marking this ready for review and adding @jhnstn as reviewer, like we discussed offline, but I'll be doing a little more testing as well on this to get more confidence on the fix.

**Comment by guarani** [comment]
Admin tests still failing, re-running...

**Review by jhnstn — APPROVED** [review]
I tested this out in all the scenarios I've run into with the inserter block search input and everything looks good.
Code LGTM 👍 
:shipit:  once the tests pass

**Comment by guarani** [comment]
> I tested this out in all the scenarios I've run into with the inserter block search input and everything looks good.
> Code LGTM 👍
> :shipit: once the tests pass

Awesome! I tested this as well on a physical iPhone 11 device:
- Inserting various different blocks
- Inserting when the cursor is already in a block with/without text
- Inserting to the start or end of a post (via the block inserter button long-press gesture)
- Inserting to above or below the currently selected block (again via the block inserter button long-press gesture)

All is looking good from my side too.

**Comment by guarani** [comment]
Tests are still failing – I updated with the latest from `trunk` in the hope that that fixes it.

**Comment by guarani** [comment]
Re-requesting a review now that we've addressed a VoiceOver issue that was discovered earlier.

**Review by jhnstn — APPROVED** [review]
LGTM, nice catch regarding the screen reader

**Comment by guarani** [comment]
Re-running the admin tests, 🤞 they pass

**Comment by guarani** [comment]
Re-running admin tests for the 5th time.

**Comment by guarani** [comment]
Tests passed! 🥳 Merged
cc @jhnstn

**Pull request merged**
