### PR TITLE
RN: Button Block set the width to fixed when width is set

### PR DESCRIPTION
**Pull request by enejb**
## Description
In https://github.com/WordPress/gutenberg/pull/28543 we shipped a new button width setting. 
However it doesn't quite work as expected. Since if you type too many characters the buttons width expands and takes the buttons don't fit on the row as expected any more. 

This PR tried to fix that by setting the maxWidth to the minWidth if a width is set and not null. (Auto) 

Before:
image (3)

After:
Screen Shot 2021-02-25 at 12 46 58 PM

## How has this been tested?
Add 4 different 25% width Button blocks. Notice that they all fall in the same line. Take up the whole editor. 
Set up different width buttons do things work out as expected? 

## Screenshots 

25%
iOS | Android
--- | ---
<kbd>Screenshot_1616539291</kbd>|<kbd>simulator_screenshot_297D273D-E881-46FA-84D0-A117FC9AF665</kbd>

50% and 75%
iOS | Android
--- | ---
<kbd>simulator_screenshot_4BE51D1F-27D5-4495-A91C-F30B3ED98AD2</kbd>|<kbd>Screenshot_1616540199

</kbd>

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by geriux** [comment]
Hey @enejb I was testing this and it works great on iPhone but on Android, there's this issue:

<kbd></kbd>

Looks like it's adding some extra height to the buttons when the max width is limited to the min width.

**Comment by enejb** [comment]
I did a bit of an investigation here and it seems that the root cause is that the Aztac Editor doesn't return the correct height back to the react native side. here https://github.com/WordPress/gutenberg/blob/915a40f95379d9b64c286bd2af2fcd11f609e7d0/packages/react-native-aztec/src/AztecView.js#L59

I am not really sure how to go about fixing this.

**Comment by enejb** [comment]
Thanks to @AmandaRiu, we were able to come up with a solution that works well. 🥳

**Review by geriux — APPROVED** [review]
LGTM! Tested it on both iOS and Android and it is working correctly. Nice work!

**Pull request merged**
