### PR TITLE
Upgrade showdown and do some lockfile gardening

### PR DESCRIPTION
**Pull request by sgomes**
## Description
The `showdown` dependency was upgraded to the latest version, 1.9.1. This is a minor version, so it should be backwards compatible.
[The 1.9.x range is significantly smaller than the currently used version, 1.8.6](https://bundlephobia.com/result?p=showdown@1.9.1), by about 20KB uncompressed, or 9KB gzipped.

In addition, I performed some gardening on the lockfile, reducing duplicate dependencies by reusing the same version where the ranges allow.

This PR as a whole should save around 23KB uncompressed (9KB gzipped) in the blocks chunk, and a much tinier 3 KB uncompressed (860B) in the components chunk, without any code changes. I guess the GitHub action will tell!

## How has this been tested?
Ran build, ran unit tests, performed ad-hoc testing of editor.

## Types of changes
Dependency upgrades and lockfile management only.

## Checklist:
- [X] My code is tested.

### CODE REVIEW

**Comment by gziolo** [comment]
Should we also update `showdown` in `@wordpress/blocks` to ensure all 3rd party projects have the most performant version?

It's still at `"showdown": "^1.8.6",`

**Comment by sgomes** [comment]
> Should we also update `showdown` in `@wordpress/blocks` to ensure all 3rd party projects have the most performant version?
> 
> It's still at `"showdown": "^1.8.6",`

@gziolo Do you mean updating the version range from `^1.8.6` to `^1.9.1`? Both should pick up `1.9.1` on install, but the latter will force the new version.

**Comment by gziolo** [comment]
> > Should we also update `showdown` in `@wordpress/blocks` to ensure all 3rd party projects have the most performant version?
> > It's still at `"showdown": "^1.8.6",`
> 
> @gziolo Do you mean updating the version range from `^1.8.6` to `^1.9.1`? Both should pick up `1.9.1` on install, but the latter will force the new version.

Yes, it will also ensure we publish a new patch version of the package (well, it would happend regardless for sure). It's definitely nice to have but it might be also a good practice to follow :)

**Review by gziolo — APPROVED** [review]

**Comment by sgomes** [comment]
> > @gziolo Do you mean updating the version range from `^1.8.6` to `^1.9.1`? Both should pick up `1.9.1` on install, but the latter will force the new version.
> 
> Yes, it will also ensure we publish a new patch version of the package (well, it would happend regardless for sure). It's definitely nice to have but it might be also a good practice to follow :)

Sounds good, done! 🙂

**Comment by gziolo** [comment]
All good, feel free to merge when Travis is green.

**Comment by sgomes** [comment]
@gziolo I think it's best if you take another look after the last commit, since there are now small unexpected changes in other packages. Travis isn't complaining any more about how running `npm i` produces a different lockfile, though.

Thank you!

**Comment by gziolo** [comment]
Looks good 👍

**Comment by sgomes** [comment]
Thanks again, @gziolo!

**Comment by aduth** [comment]
>In addition, I performed some gardening on the lockfile, reducing duplicate dependencies by reusing the same version where the ranges allow.

Can you elaborate more on what was done here, and why? I'm encountering some issues in my pull request #21868 where I'm seeing "Build artifacts" that I'm unable to reproduce locally. I see [almost all recent builds](https://github.com/WordPress/gutenberg/pulls) are failing as well. These changes seem particularly suspect.

**Comment by aduth** [comment]
> I'm encountering some issues in my pull request #21868 where I'm seeing "Build artifacts" that I'm unable to reproduce locally.

I was able to reproduce locally after removing local `node_modules`. Hoping c37ce38610df8001bf65d93ee1a3fe8d6c683d8b will resolve it.

**Comment by sgomes** [comment]
> I was able to reproduce locally after removing local `node_modules`. Hoping [c37ce38](https://github.com/WordPress/gutenberg/commit/c37ce38610df8001bf65d93ee1a3fe8d6c683d8b) will resolve it. Not sure it's actually related to anything here.

@aduth Right, that does sound unrelated, as far as I can tell.

For reference, what I did was an `npm dedupe`, followed by a lot of manual editing, since `npm dedupe` like to mangle the `version` and `resolved` fields together, for some reason.

After this, an `npm i` is needed too, otherwise the "Build artifacts" CI check will complain (and since `npm dedupe` often leaves the lockfile in a bad state, yay bugs). Since you're doing an `npm i`, however, you need to look out for changed packages and make sure there were no unexpected changes.

Managing monorepos with `npm` can be a pain.

**Pull request merged**
