### PR TITLE
Export the image editor so it can be used by plugins or themes.

### PR DESCRIPTION
**Pull request by herregroen**
## Description
Exports the `ImageEditor` so it can be used by plugins or themes.

### CODE REVIEW

**Comment by swissspidy** [comment]
Citing #23053

> In the future, if this component could be useful for other blocks and if it is ready, we can consider creating a separate component in the block editor package, maybe similar to the replace flow. Having it in the block library as a filter for a block doesn't make much sense right now.

**Comment by jdevalk** [comment]
Honestly I disagree with that point of view. Now we're being blocked from using it and forced to just copy / paste the code into our own plugin.

**Comment by swissspidy** [comment]
@jdevalk What I am getting from the cited statement (and what I wanted to share) is that this component should be exposed via `@wordpress/block-editor`, not as part of the image block in `@wordpress/block-library`. I don't think you'd disagree with that..?

**Comment by jdevalk** [comment]
Ah my apologies I completely misunderstood what you were saying then :-)

**Comment by ellatrix** [comment]
@jdevalk Could you elaborate how you'd like to use it?

**Comment by jdevalk** [comment]
> @jdevalk Could you elaborate on how you'd like to use it?

We have images in our HowTo and FAQ blocks, we'd like to add the same image editing options to those.

**Comment by talldan** [comment]
This PR is a bit light on info, noting that this was discussed in slack where there's some more information:
https://wordpress.slack.com/archives/C02QB2JS7/p1592219787143400

One of the considerations mentioned there is that the feature is being developed as an experiment.

It also looks like it depends on an `experimental` REST API endpoint that is currently only defined in the Gutenberg plugin, so that would have to be migrated to WordPress core. I think there was some discussion around allowing experimental REST API endpoints in core, but I'm not fully up-to-date on that.

**Pull request closed without merging**
