### PR TITLE
Move Alignment, movers and trash icons to the icons package

### PR DESCRIPTION
**Pull request by youknowriad**
Everything is in the title :) 

**Testing instructions**
check the naming of the icons and the UI quickly.

### CODE REVIEW

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Tested locally. Icons appear to be loading and rendering as expected 👍

**Comment by jasmussen** [comment]
Before you merge, one thing we need to review are the icon names, because they are easy to change now, hard to change later.

From a quick glance, do we need "block" in the names?

**Comment by youknowriad** [comment]
For now, names are still easy to change later because the package is bundled.

That said, the "block" is to differentiate with the text and block align ones. It seemed to me that the text alignment are more "standard", so I didn't have an suffix there, the block alignment less standard, that's why I opted for "block" there.

noting that we already had an align-justify (so text alignment) before this PR.

**Comment by jasmussen** [comment]
I wonder if we should invert that thinking, and go with "align left" as the block level stuff, and "text align left" as the inline level stuff. I'm open to anyone feeling strongly about this, but I worry that "block" can be confused with gutenblocks when it in fact refers to _block level_.

**Comment by jasmussen** [comment]
There was also some conversation about the full-wide being renamed from being an alignment to something else. CC: @karmatosed in case she can remember.

**Comment by ZebulanStanphill** [comment]
I agree that "alignBlockWide" and "alignBlockFull" really don't make sense as names when you think about it... actually, "alignBlockLeft" and "alignBlockRight" aren't really accurate either since the icons depict floating behavior where the surrounding stuff wraps around the rectangle, which is different from an actual standard alignment to the left or right.

There has been discussion about this sort of thing in #19672.

**Comment by youknowriad** [comment]
Open to suggestions, I want to state though that alignLeft and alignRight for the block positionning icon is very weird too. As far as I know these are specific to blocks and in other icon libraries, generally for users when we say "align" we mean "text align".

**Comment by jasmussen** [comment]
> generally for users when we say "align" we mean "text align"

My gut told me that for normal people when they say align, they mean _both_. I want this block aligned left, and this text aligned right. 

This is not to make a giant conversation out if it, though, because these are only icon names, and I'm sure once the dust settles we'll have a nice storybook page letting you pick the icons visually so you know what you're doing. 

All that's important is we have some nicely structured names that ideally follow some understandable heuristic. To me, personally, "block" should not be part of the name, and since there are only four text justifications, we might as well explicitly prefix those text. Also keep in mind that we will likely be adding a _slew_ of alignment icons for future advanced flex-based alignments, making the heuristic for naming these more important.

Another aspect is the idea that you should be able to have _two_ "alignments" at once, for example full width and full height. Yeah, it can get messy.

Thanks for the link, Zeb, that's the one I was looking for.

**Comment by youknowriad** [comment]
I don't mind adding "text" prefix to the text alignment. But I do think we need a prefix too for the block alignment. I don't really care if it's not "block", but these are not just align. That's too confusing for me.

What about "position-left" like proposed on that thread.

**Comment by jasmussen** [comment]
> What about "position-left" like proposed on that thread.

If it's as easy to change as you say it is, yes, I think that's a great start. 

Wide and fullwide and full height could also be `stretch-`.

**Comment by youknowriad** [comment]
I renamed the icons and used the three categories: text-align-*, position-* and stretch-*

**Comment by jasmussen** [comment]
If the icons truly are easy to rename if additional feedback comes in to suggest it, I say go forth and merge!

**Comment by youknowriad** [comment]
For now, they are easy to rename. If we decide to make them public API in Core later, they won't be.

**Comment by jasmussen** [comment]
> If we decide to make them public API in Core later, they won't be.

Let's perhaps try and make a callout when that happens, to do a last sanity check on the names, before we do that public API change. For now it feels like the changes in this branch respect the conversation from 19672

**Comment by jasmussen** [comment]
[Here's also a good thought](https://github.com/WordPress/gutenberg/pull/19386#issuecomment-572744034) from our friend Matías: 

> [...] we were discussing using `alignment` for the distributions of elements within the container (left, center, space-between, etc) and `position` for how the container is displayed (wide, full-width, floated, etc).

Perhaps this is an argument for naming text alignments, simply `align` instead of `text-align` as I suggested. 

I wonder if stretch is a bad term — I think it makes sense for "stretch full height" as that is less of a position thing and more of a behavior on the block. And if that is the case, then "stretch wide" and "stretch full wide" also seem behavioral. What are your thoughts here?

**Comment by youknowriad** [comment]
I like the current names and I admit I don't like back and forth here cause it takes some time to rename everything. So at this point, I'm more like: just give me the names you want to use :)

**Comment by jasmussen** [comment]
Yes, my apologies for that. 

Let's rename "text-align" back to "align", so that they can in the future refer to flex alignments like space-between as well. Let's keep "stretch" for now, and then @mtias can bonk me on the head if he hates it.

**Comment by ZebulanStanphill** [comment]
For the record, I think stretch makes sense for wide/full, and I'm happy to stick with that unless someone suggests something better.

**Pull request merged**
