### PR TITLE
Upgrade Reakit to version 1.3.4

### LINKED ISSUE #677: useEventListenerOutside and focus loss
### Current behavior

When a nested dialog is `modal: false`, and there's a focus loss, the focus is given to an element outside of the nested modal, calling hide [here](https://github.com/reakit/reakit/blob/239eb5622a1a02cd6f69c857bb725c8250dad155/packages/reakit/src/Dialog/__utils/useHideOnClickOutside.ts#L61). It's probably due to the fact that for the browser, the parent dialog focusable elements are on the same "plane". For context, the bug occured on my application when the activeElement was unmounted.

### Steps to reproduce the bug

https://codesandbox.io/s/nice-cloud-xo9th using chrome.

### Expected behavior

The nested dialog should not close (ie if reakit still relies on focus event for this, the nested dialog container should get the focus on focus loss).

### Possible solutions

As it's a focus loss problem, I've tried to play with tabIndex in order to force the browser `activeElement` selection, without success. Programmatically, clicking on the button, I can focus the nested dialog container using a ref, but it does not really scale. There's probably a reason for reakit to rely on the focus event (probably no focus trap), but that's the source of the issue.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Memory: 825.36 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - ~/Code/eeselapp/eesel/node_modules/.bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Browsers:
    Brave Browser: 80.1.5.115
    Chrome: 83.0.4103.97
    Safari: 13.1.1
```

### LINKED ISSUE #698: Animated disclosures warning if stopAnimation never called
See this twitter thread: https://twitter.com/ZakStrassberg/status/1288854665581473792

If a disclosure with animated: true doesn't have a transition attached to it, stopAnimation is never called and focus management breaks. I thought it was a ref issue until I looked into source.

[Diego proposed:](https://twitter.com/diegohaz/status/1288880616109465601)
> Hmm, I think in development we can set a time limit for `stopAnimation` to be called when animated is true, and emit a warning if the limit is reached.

### LINKED ISSUE #702: [Radio] Tab moves focus to body instead of next tabbable item in the dom
### Current behavior

Hitting `Tab` from the <Radio/> moves the focus to body instead of the next focusable element in the DOM.

### Steps to reproduce the bug

https://codesandbox.io/s/useradio-reakit-issue-xu62i

1. Click on top of the body.
2. Hit `Tab` to move the focus to the 1st <Radio /> within 2st <RadioGroup />
3. Hit `Tab` moves the focus to the body

### Expected behavior

3. Hit `Tab` should move the focus to the 1st <Radio /> within 2nd <RadioGroup />

### Possible solutions

I tried to look into solving this issue, but I am still getting familiar with Reakit repo. So no luck.

But here's something I tried, I did the same Radio example with React Aria

Works smooth - https://codesandbox.io/s/useradio-spectrum-rl7hj?file=/src/App.js

---

More examples with Radio using Reakit and `useFocusRing` from React-Aria - https://codesandbox.io/s/useradio-reakit-c72nc

### Environment

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"

Mac OS - Catalina 10.15.5
Google Chrome 84

### LINKED ISSUE #722: [Button] As 'a' with disabled prop focuses on `tab`
### Current behavior

image

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/button-with-a-disabled-bug-7znw8
2. Press Tab on the preview to see the button focus when keyboard press but not on pointer press.
3. Expect to see the button getting focused.

### Expected behavior

Button should not be focusable at all when `disabled`

### Possible solutions

```
const [isLink, setIsLink] = React.useState(false);

React.useEffect(() => {
      const element = ref.current;
      if (!isButton(element)) {
       if(element.tagName === "A") {
          setIsLink(true)
       }
     }
    }, []);

return {
   href: isLink & disabled ? undefined : htmlHref
}
```

### LINKED ISSUE #747: Infinite Toolbar/Composite rendering loop on Firefox
### Current behavior

I'm in the process of debugging a strange performance issue with Firefox in the old and big app I'm in charge of.

The app uses multiple `Toolbar`s inside a big component. This component is rendered in different ReactDOM tree (new React UIs attached to legacy views) at different moment.

First, there is only one `Toolbar`. Then, the user click somewhere and there is another one. Then three, etc.

After the second `Toolbar` is rendered, the performance issue starts. The `useToolbarState` hook of the second `Toolbar` keeps firing, rerendering the component hosting the toolbar. According to the React profiler, there is a new `items` prop passed to the toolbars components. It's like an infinite loop.

Seems to have appeared after the `2.0.0` update.

### Steps to reproduce the bug

I've not succeeded for now at reproducing the bug in a Codesandbox the cleanest way possible but it's on this Codesandbox : https://codesandbox.io/s/bug-reakit-toolbar-fujdb?file=/src/App.tsx

1. Open the sandbox with the app preview in the right panel
2. Open the Firefox console. You should see some `console.log({ toolbar })`. No infinite loop for now
3. Edit the `aria-label` from "test" to "test-111234" for example. In the console you should now see an infinite steam of `console.log({ toolbar })` after the hot loading has updated the component.

### Expected behavior

No infinite rendering loop.

### Possible solutions

I think I have a fix. Debugging Reakit locally I came across the `sortBasedOnDOMPosition` Composite helper.

https://github.com/reakit/reakit/blob/62cfafecb85521fd15c292a80af40da93adf705a/packages/reakit/src/Composite/__utils/sortBasedOnDOMPosition.ts#L8-L25

The `sort` function, and especially the way it sets `isOrderDifferent` to `true` seems to be the source of the issue. I think Firefox is not calling the sorting function consistently (`a` and `b` sometimes inverted ?) and that could make the function think the order of `copy` after sorting is different than `items` but it's not.

With the version of the function below the rendering issue seems to be fixed because we compute `isOrderDifferent` by comparing `items` and `copy`.

```ts
export function sortBasedOnDOMPosition<T extends Item>(items: T[]): T[] {
  const copy = items
    .map((item, index) => [index, item] as [number, T])
    .slice();

  copy.sort((a, b) => {
    const elementA = a[1].ref.current;
    const elementB = b[1].ref.current;

    if (!elementA || !elementB) return 0;

    // a before b
    if (isElementPreceding(elementA, elementB)) {
      // isOrderDifferent = true;
      return -1;
    }

    // a after b
    if (isElementFollowing(elementA, elementB)) {
      return 1;
    }

    return 0;
  });

  const isOrderDifferent = copy.reduce<boolean>(
    (localIsOrderDifferent: boolean, slot: [number, T]) => {
      const [index, newItem] = slot;

      const initialItem = items[index];

      return localIsOrderDifferent || newItem !== initialItem;
    }, false,
  );

  if (isOrderDifferent) {
    return copy.map(([_, item]) => item);
  }

  return items;
}
```

### Environment

Firefox 80.0.1. Not reproduced on Chrome.

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 875.79 MB / 16.00 GB
    Shell: 5.0.0 - /usr/local/bin/bash
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 85.1.14.81
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 14.0
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-spring: 8.0.27 => 8.0.27 
    react-test-renderer: 16.13.1 => 16.13.1 
```

What do you think of this issue ? Do you want me to open a PR with this `sortBasedOnDOMPosition` fix ?

### LINKED ISSUE #751: Click on menu,Screen scrolled upwards automatically
## 🐛 Bug report
This is not a bug in library,but when I visited home page https://reakit.io and after first load of page clicking on menu button of `TabsModalMenu.js` and `TabsModalMenuMenu.js` ,it automatically scrolled upward.
### Steps to reproduce the bug
1. Open new tab
2. Go to reakit.io
3. Click on menu of two tabs mentioned above

### Possible solutions
I think we have to put `event.stopPropagation()`.I can't find code of that in this repo.

### Environment 
Browser : FireFox (81.0), Chrome (Version 85.0.4183.121)

real
reakkit

### LINKED ISSUE #776: Peer deps: Add React 17
### Current behavior

With React 17 installed, there's a bunch of warnings like so:

```
reakit@1.1.0 requires a peer of react@^16.8.0 but none is installed.
``` 

reakit has react 16 as a peer dep. The new React 17 is very compatible is probably still compatible with reakit. I would assume it's fine changing this line (and similar):

https://github.com/reakit/reakit/blob/3ac8395575e25848a8f23fd38bab9678e97ba9a7/packages/reakit/package.json#L48-L49

to this:

```json
"react": "^16.8 || ^17"
```

### Steps to reproduce the bug

Ensure npm 6

```
mkdir test-react-17
cd test-react-17
npm init -y
npm i react react-dom
npm i reakit
```

image

### Expected behavior

No peer dep warnings.

### Possible solutions

Use an or clause for peer deps (assuming it's compatible)

```json
"peerDependencies": {
  "react": "^16.8 || ^17"
}
```

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

npx: installed 1 in 0.88s

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 250.59 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.111
    Edge: 86.0.622.51
    Firefox: 80.0.1
    Firefox Developer Edition: 73.0
    Safari: 14.0
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    reakit: ^1.2.5 => 1.2.5 
```

Related #723

### LINKED ISSUE #790: Radio button onChange handler fires twice
### Current behavior

When you click on a radio button with an onChange handler, it fires twice: once for a click event and once for a change event.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/react-playground-forked-lt85u?file=/index.js
2. Open the console
3. Click the Radio button
4. Watch two events fire

### Expected behavior

The onChange handler should fire once.

### Possible solutions

I'd look into not using the `onChange` handler [here](https://github.com/reakit/reakit/blob/57b1238e714bb4dda3984d62268313c180fcc6a8/packages/reakit/src/Radio/Radio.ts#L128) and instead making a separate handler for clicks

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.0.1
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 119.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.23.0 - ~/.config/nvm/versions/node/v10.23.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.config/nvm/versions/node/v10.23.0/bin/npm
  Browsers:
    Chrome Canary: 89.0.4335.0
    Safari: 14.0.1
  npmPackages:
    reakit-utils: ^0.13.1 => 0.13.1
```

### LINKED ISSUE #798: Can't pass option props together with the `state` prop
### Current behavior

It's not possible to pass option props to components together with the `state` prop.

For instance, in the example below, `hideOnClickOutside` is a custom prop (option prop) that should be consumed by `Dialog`. It works when using `{...state}`, but not with `state={state}`. In fact, this custom prop is not filtered by the `splitProps` helper and ends up in the markup.

```jsx
<Dialog state={state} hideOnClickOutside={false} />
```

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/mystifying-tharp-gcyrw?file=/index.js
2. Open dialog.
3. Click outside.
4. It closes the dialog.

### Expected behavior

The dialog shouldn't be closed by clicking outside.

### LINKED ISSUE #808: Combobox popover position is wrong when Combobox container is fixed/relative + minValueLength + input click
### Current behavior

When using the Combobox inside a container that is either fixed or relative, and using the minValueLength option: bad things happen. The positioning of the popover is wrong initially and once you validate an option will become OK.

(tested on chrome and safari latest, macOS bigsur)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/zealous-sara-ljyyb?file=/src/App.tsx
2. **Click** on the input
3. Type "a"
4. Popover position is bad
5. Validate first result
6. Click again on the input
7. Popover position is good

**Demo:**
Kapture 2020-12-09 at 00 11 22

**How it's made:**
I replicated the Combobox fetch example (https://github.com/reakit/reakit/tree/master/packages/reakit/src/Combobox/__examples__/ComboboxFetch) and added:
- two containers to demonstrate the issue
- minValueLength: 1

### Expected behavior

Popover position should be good even if minValueLength: 1 is used and the container is fixed/relative

### Possible solutions

As discussed on Twitter, because this only happens on click (if you tab to the input: it works!) this might be an issue with the click handler of the input doing some unexpected changes compared to tab.

As a workaround, instead of using the minValueLength option, for now I am using:

```js
      <ComboboxPopover
        {...combobox}
        style={{
          visibility:
            combobox.inputValue.length < 1 || matches.length === 0
              ? "hidden"
              : "visible",
        }}
      >
```

Which seems to be "fine" but most probably not very aria friendly.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 51.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 73.0.1
    Safari: 14.0.1
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-hook-form: 6.12.2 => 6.12.2
    react-loading-skeleton: 2.1.1 => 2.1.1
    react-script-hook: 1.2.1 => 1.2.1
    react-select-search: 2.2.3 => 2.2.3
    react-transition-group: 4.4.1 => 4.4.1
    react-use: 15.3.4 => 15.3.4
    reakit: 1.3.1 => 1.3.1
```

### PR DESCRIPTION
**Pull request by diegohaz**
This PR upgrades Reakit to version 1.3.4.

The most relevant feature is that composite items are now automatically sorted when their position change in the DOM, so we don't need to call `unstable_sort()` manually anymore.

<details><summary>Changelog since v1.1.0</summary>

### Bug Fixes

* Revert `CompositeItem` tabIndex fix ([#821](https://github.com/reakit/reakit/issues/821)) ([1390d31](https://github.com/reakit/reakit/commit/1390d31a3d0b1f5e1b0555001e6d6d096b57ec0e))

### Bug Fixes

* Fix `CompositeItem` with `tabindex=0` on the first render ([#817](https://github.com/reakit/reakit/issues/817)) ([3d81514](https://github.com/reakit/reakit/commit/3d815148d74e333ec975ff871a92f39aaa307fa8))

### Bug Fixes

* Accept other option props together with the `state` prop ([#799](https://github.com/reakit/reakit/issues/799)) ([a21bb2b](https://github.com/reakit/reakit/commit/a21bb2b22780121125bbf3dfc6160ac29e1a0741)), closes [#798](https://github.com/reakit/reakit/issues/798)
* Add React 17 to peer dependencies ([#807](https://github.com/reakit/reakit/issues/807)) ([411b5aa](https://github.com/reakit/reakit/commit/411b5aa8adf63f3149b40db6a499e65b58929b29)), closes [#776](https://github.com/reakit/reakit/issues/776)
* Fix `Menu` scroll jump ([#801](https://github.com/reakit/reakit/issues/801)) ([96f5dd5](https://github.com/reakit/reakit/commit/96f5dd52704444862d16167db3c82fb89838e3ae)), closes [#751](https://github.com/reakit/reakit/issues/751)
* Fix badly positioned popover on click + minValueLength ([#809](https://github.com/reakit/reakit/issues/809)) ([2c847da](https://github.com/reakit/reakit/commit/2c847da75edebae2f511fb5f50c516dfcfa71981)), closes [#808](https://github.com/reakit/reakit/issues/808)

### Bug Fixes

* Add missing quote in querySelector in `Dialog` ([#793](https://github.com/reakit/reakit/issues/793)) ([d9a49ef](https://github.com/reakit/reakit/commit/d9a49efa432b4dc8df51dc62f0d1b5023236dff4))
* Native radio input firing onChange callback twice on click ([#791](https://github.com/reakit/reakit/issues/791)) ([6a436bb](https://github.com/reakit/reakit/commit/6a436bb5adccd53e37604195980bd67e7119972e)), closes [#790](https://github.com/reakit/reakit/issues/790)

# [1.3.0](https://github.com/reakit/reakit/compare/reakit@1.2.6...reakit@1.3.0) (2020-11-12)

### Features

* Add `Role` component ([#728](https://github.com/reakit/reakit/issues/728)) ([5fa51a7](https://github.com/reakit/reakit/commit/5fa51a7891085aeeb6a0e3ea44ef3d294fccc8ba))
* Add `shift` option to `useCompositeState` ([#727](https://github.com/reakit/reakit/issues/727)) ([7861395](https://github.com/reakit/reakit/commit/7861395ac8c1eaf979b5e4835ae99c001c39f312))
* Add experimental `Combobox` component ([#688](https://github.com/reakit/reakit/issues/688)) ([ad7063b](https://github.com/reakit/reakit/commit/ad7063b0096c19e3295a74213a4ec821683f12ff))
* Add experimental `includesBaseElement` option to `useCompositeState` ([#726](https://github.com/reakit/reakit/issues/726)) ([cf3ba56](https://github.com/reakit/reakit/commit/cf3ba5687ea339de0f8917d2b1e83797403cdddc))
* Show warning if disclosure stopAnimation is not called in time ([#701](https://github.com/reakit/reakit/issues/701)) ([0dd2683](https://github.com/reakit/reakit/commit/0dd2683c99f68ae0f3b32b25b9c989dc4b012ba6)), closes [#698](https://github.com/reakit/reakit/issues/698)
* Trigger `onChange` when setting `CompositeItemWidget` value ([0b5b3cb](https://github.com/reakit/reakit/commit/0b5b3cb64ba5cc6cba000d0cdc972ab81fe4247e))

### Bug Fixes

* Fix Composite `unstable_virtual` option on mobile devices ([#783](https://github.com/reakit/reakit/issues/783)) ([ecdc4ef](https://github.com/reakit/reakit/commit/ecdc4ef8ddd72ef136d8c72d969a3fe73505fd74))
* Stop warning when using invalid composite roles on `Composite` ([#784](https://github.com/reakit/reakit/issues/784)) ([9bcbfe6](https://github.com/reakit/reakit/commit/9bcbfe6740c6e5e3e7ff6d51bb081a7ecc7af08d))

### Bug Fixes

* Fix `Composite` infinite loop on Firefox ([#748](https://github.com/reakit/reakit/issues/748)) ([4a1c644](https://github.com/reakit/reakit/commit/4a1c644a758264f4da77a3f4e2bc28aed6a16a48)), closes [#747](https://github.com/reakit/reakit/issues/747)
* Fix `disabled` prop being passed to elements that don't support it ([#725](https://github.com/reakit/reakit/issues/725)) ([d982a61](https://github.com/reakit/reakit/commit/d982a61074bf3ed899ebe4a6e4744cec32191b57)), closes [#722](https://github.com/reakit/reakit/issues/722)
* Fix disabled events when using the `as` prop ([#736](https://github.com/reakit/reakit/issues/736)) ([c594166](https://github.com/reakit/reakit/commit/c5941668d0ebc69f04171f2f6cfb44ecf8917495))

### Bug Fixes

* Fix internal dependency versions ([3d4cb42](https://github.com/reakit/reakit/commit/3d4cb4217a52ec719e8a2823d21e08c7cc42dd30))

### Bug Fixes

* Fix SSR check ([#717](https://github.com/reakit/reakit/issues/717)) ([1f09fc9](https://github.com/reakit/reakit/commit/1f09fc9879ecd9516d514c7a848b7a62a1b93358))

### Bug Fixes

* Assert `focus` method exists on the dialog disclosure element ([#710](https://github.com/reakit/reakit/issues/710)) ([85dd073](https://github.com/reakit/reakit/commit/85dd073a4f3e5832340c4a05d9af6bb4798c69a1))
* Fix blur event on `Composite` for React 17 ([#711](https://github.com/reakit/reakit/issues/711)) ([0ad76e6](https://github.com/reakit/reakit/commit/0ad76e61560da5f25e99a01d9842bf53e18d7993))
* Fix disclosure detection when `unstable_virtual` is `true` on React 17 ([#715](https://github.com/reakit/reakit/issues/715)) ([81ec3a3](https://github.com/reakit/reakit/commit/81ec3a31c2e5fec4a8817acd3e10361247d95377))
* Fix intermediate `focus`/`blur` event order in `Composite` ([#713](https://github.com/reakit/reakit/issues/713)) ([891976b](https://github.com/reakit/reakit/commit/891976b047aebe93e802a16b7aaf25708cc5c65a))

### Bug Fixes

* Fix tabbing between multiple `RadioGroup`s ([#703](https://github.com/reakit/reakit/issues/703)) ([212adbd](https://github.com/reakit/reakit/commit/212adbd292702948ab71a44a22d9862117468668)), closes [#702](https://github.com/reakit/reakit/issues/702)

# [1.2.0](https://github.com/reakit/reakit/compare/reakit@1.1.2...reakit@1.2.0) (2020-08-06)

### Features

* Add experimental `Grid` component ([#685](https://github.com/reakit/reakit/issues/685)) ([51e17fb](https://github.com/reakit/reakit/commit/51e17fbaab188a501dc267863f363e880cbba717))
* Add stable `composite.sort` method ([#690](https://github.com/reakit/reakit/issues/690)) ([1f66168](https://github.com/reakit/reakit/commit/1f6616883800eb2e367cbcee12dce7399d25e159))
* Add stable `id.setBaseId` method ([#691](https://github.com/reakit/reakit/issues/691)) ([5c52c71](https://github.com/reakit/reakit/commit/5c52c712395c63f73284558dd84a230c6e2026c7))
* Automatically sort composite items based on DOM position ([#696](https://github.com/reakit/reakit/issues/696)) ([bdaab5d](https://github.com/reakit/reakit/commit/bdaab5df2f6fd3445320a6f98975301ab7a84971))
* Focus `Menu` instead of `MenuItem` on mouse click on `MenuButton` ([#694](https://github.com/reakit/reakit/issues/694)) ([d57b97f](https://github.com/reakit/reakit/commit/d57b97f2f64c883a95c73acf7ad0275dfdbd642a))

### Bug Fixes

* Fix `composite.unstable_sort` on Firefox ([f973f77](https://github.com/reakit/reakit/commit/f973f77ea58811ee009f2de649b6426aa98617c9))
* Fix `Dialog` focus loss ([#682](https://github.com/reakit/reakit/issues/682)) ([8ae0da7](https://github.com/reakit/reakit/commit/8ae0da741ca45fed6bc1a7c25a3fc9aa60340b44)), closes [#677](https://github.com/reakit/reakit/issues/677)
* Fix `MenuButton` not receiving focus after `Menu` closes ([#692](https://github.com/reakit/reakit/issues/692)) ([e649f20](https://github.com/reakit/reakit/commit/e649f203334468ceb23ef33be49b24098b4a0eab))

### Bug Fixes

* Restore missing `Composite` references ([9d9eff2](https://github.com/reakit/reakit/commit/9d9eff216328038b34af50cea03f45f8297e0756)), closes [#667 (comment)](https://github.com/reakit/reakit/pull/667#issuecomment-647108385)

</details>

### CODE REVIEW

**Review by kevin940726 — APPROVED** [review]
🎉

**Comment by gziolo** [comment]
Thanks @diegohaz 👍🏻 

I raised that in the past, it looks like we should look into how we could stop duplicating bundled code from Reakit:
Screen Shot 2021-01-07 at 07 56 59

We could add shared APIs to `@wordpress/a11y`, but there is one line that I personally find as tricky:

https://github.com/WordPress/gutenberg/blob/61f57f4b8c22b4ef3e44280f1667be5723751573/packages/a11y/src/index.js#L40

Any thoughts?

**Comment by diegohaz** [comment]
> I raised that in the past, it looks like we should look into how we could stop duplicating bundled code from Reakit:

@gziolo I don't really know how to interpret that table. I expect that when we use both `@wordpress/block-library` and `@wordpress/components` we would get the same Reakit source. But maybe it's a problem when we use the browser distributions? How would adding Reakit only to `@wordpress/a11y` solve this problem?

**Comment by gziolo** [comment]
The issue exists inside the WordPress core/Gutenberg plugin. We have a long list of entry points. They are externalized between each of them and referenced through `wp.*` globals in the build code. It means that when you import Reakit for a given entry point it is properly tree-shaken but if several entry points use Reakit, all of them can bundle the same code. Given that there is already `@wordpress/a11y` package, we could make it a proxy to Reakit and resolve this issue by forbidding direct imports from Reakit.

**Comment by diegohaz** [comment]
That makes sense! Why do you think that line (`domReady( setup );`) would be problematic?

**Comment by gziolo** [comment]
> Why do you think that line (`domReady( setup );`) would be problematic?

It might be my personal resistance to side effects in packages. Maybe we could lazy execute it when `speak` is called for the first time 🤔

**Comment by gziolo** [comment]
@youknowriad, is https://github.com/WordPress/gutenberg/pull/28013#issuecomment-755928763 something we should plan for WordPress 5.7 or you think we can delay further?

**Comment by youknowriad** [comment]
Do you think the solution here could be to use components from "Components" that rely on reakit instead of using reakit directly in the other packages?

**Comment by gziolo** [comment]
Yes, that would work as well since `@wordpress/components` is the most nested component here.

**Pull request merged**
