### PR TITLE
Add in all dependencies for a given block

### PR DESCRIPTION
**Pull request by jghazally**
Previously Gutenberg Plugin added these dependencies, related to:
https://core.trac.wordpress.org/ticket/45219
and
https://github.com/WordPress/gutenberg/issues/11069

## Description
Documentation needs to be updated to include other dependencies.

## How has this been tested?
With WP 5.0 beta

## Types of changes
Documentation

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Instead of just listing the current set of dependencies that will work for most blocks, shouldn't the docs explain _why_ you should use whichever dependencies? I think it makes more sense to explain that you should declare a dependency when you use something from the particular package. Otherwise the same dependency problem seen in existing plugins could happen again due to people not specifically declaring dependencies. The docs should try to clarify this behavior to avoid similar issues from happening in the future, as well as discourage the poor practice of declaring dependencies that aren't actually needed by explaining when and why you should declare dependencies.

**Comment by jghazally** [comment]
Agreed, perhaps someone with a little more understanding of the two dependencies that I've included can add them to the description section under:

*Note the ~two~ four script dependencies:*

**Comment by mkaz** [comment]
@jghazally Thank you for you taking your time to improve the documentation. I just created a test block using the existing code, without the added dependencies, and it works fine. So I don't think this PR is needed for that sample code.

The two issues you linked to does highlight a need to call out dependency clarification, however since the sample code works without, it is better not to include something that is not be used.

Please take a look at PR #12346 which I added an additional line to the dependency note which hopefully clarifies without have to alter the sample code. Let me know what you think.

**Comment by jghazally** [comment]
@mkaz perfect, #12346 works.

**Pull request closed without merging**
