### PR TITLE
Add testimonials02 pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a Testimonials section block pattern for #20345.

⚠️ **Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.**

Screen Shot 2020-03-04 at 18 50 24

```
<!-- wp:group {"customBackgroundColor":"#f6f6f6","align":"full"} -->
<div class="wp-block-group alignfull has-background" style="background-color:#f6f6f6"><div class="wp-block-group__inner-container"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":358,"width":173,"height":173,"sizeSlug":"large","className":"is-style-rounded"} -->
<div class="wp-block-image is-style-rounded"><figure class="aligncenter size-large is-resized"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/Group-1.png" alt="" class="wp-image-358" width="173" height="173"/></figure></div>
<!-- /wp:image -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph {"align":"left","customTextColor":"#444444"} -->
<p style="color:#444444" class="has-text-color has-text-align-left">"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"left","customTextColor":"#444444","fontSize":"normal"} -->
<p style="color:#444444" class="has-text-color has-text-align-left has-normal-font-size"><strong>Dorothy Salazar</strong><br><em>Somewhere, USA</em></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":367,"width":175,"height":175,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large is-resized"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/Group-3-4.png" alt="" class="wp-image-367" width="175" height="175"/></figure></div>
<!-- /wp:image -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph {"align":"left","customTextColor":"#444444"} -->
<p style="color:#444444" class="has-text-color has-text-align-left">"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"left","customTextColor":"#444444","fontSize":"normal"} -->
<p style="color:#444444" class="has-text-color has-text-align-left has-normal-font-size"><strong>Arthur Walters</strong><br><em>Somewhere, USA</em></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":365,"width":174,"height":174,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large is-resized"><img src="https://nrqsnchztest.blog/wp-content/uploads/2020/02/Group-2-2.png" alt="" class="wp-image-365" width="174" height="174"/></figure></div>
<!-- /wp:image -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph {"customTextColor":"#444444"} -->
<p style="color:#444444" class="has-text-color">"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customTextColor":"#444444"} -->
<p style="color:#444444" class="has-text-color"><strong>Doris Cole</strong><br><em>Somewhere, USA</em></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->
```

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. We can use Gravatar's default avatar image instead.

Let me know if you think it can be improved or if we should close this PR instead.

**Comment by mapk** [comment]
@enriquesanchez, Can you show how this would look with the Gravatar image instead?

**Comment by enriquesanchez** [comment]
@mapk @mtias Here are a couple of of variations of how it could look like with Gravatar's default avatar:

Screen Shot 2020-04-10 at 16 17 55

Screen Shot 2020-04-10 at 16 24 11

**Comment by mapk** [comment]
@enriquesanchez, can you incorporate real text here? I like the second row with the circular Gravatar images.

**Comment by enriquesanchez** [comment]
Since this starting to look very similar to #20894, I'm going to close this one.

**Pull request closed without merging**
