### PR TITLE
Navigation: Remove outdated separate "Home" link styles

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

The Home link block which can be inserted in the Navigation block simply links to your homepage. It currently duplicates some styles (padding, margin, others) from other Navigation items. But as of #33918, those styles are no longer needed. This PR removes them.

## How has this been tested?

Try the navigation block with a home link, and verify that the Home link has the same paddings, gap and other metrics that other items have:

Screenshot 2021-11-18 at 12 08 24

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by carolinan** [comment]
I was able to confirm the issue, and the pull request solves it.

This block is not already in WordPress core (unless you can show me where, because I do not see it in trunk?),
and as the feature freeze is in place for 5.9, I don't think this can be backported to WordPress core in 5.9.
I assume this will be up to the 5.9 release squad and core committers.

**Review by carolinan — APPROVED** [review]

**Comment by jasmussen** [comment]
Thank you for the review. I think it's entirely harmless to not backport this one, it's mostly a cleanup. The styles output were overridden by the generic classes anyway.

But the block _should_ be shipped already. The way you insert it is a bit roundabout at the moment:
nav home link

This speaks to us needing to continue to refine and improve the "lighter navigation flow" (#34041), which right now leans heavily towards the simpler experience.

**Comment by carolinan** [comment]
Yeah I struggled with figuring out how to add the block.

**Comment by carolinan** [comment]
It is not included: https://core.trac.wordpress.org/browser/trunk/src/wp-includes/blocks?rev=52212

**Comment by jasmussen** [comment]
Ah! No urgency then. Thanks again.

**Pull request merged**
