### PR TITLE
Scope Nav Menu sidebar to Plugin only

### PR DESCRIPTION
**Pull request by getdave**
## What?
This PR scopes the new Nav Menu sidebar to be a Plugin only feature in order to ensure it does not get included in WordPress 6.0.

## Why?

Please see reasons in https://github.com/WordPress/gutenberg/issues/40080.

## How?

I'm using `process.env.IS_GUTENBERG_PLUGIN` to scope the Nav Sidebar code itself and the toggle button in the Nav block toolbar.

I have tried to optimise for dead code elimination by rendering either the component itself or a `React.Fragment`. By using the true component only by way of a conditional Webpack will eliminate the dead code _within_ the `if()` when we're not building for the Gutenberg Plugin.

There may be a better way to achieve this - cc'ing @talldan who I believe created the `IS_GUTENBERG_PLUGIN` functionality.

## Testing Instructions

- Goto Site Editor
- Check that by default
    - the Nav sidebar is shown
    - you can see the sidebar toggle control in the Nav block toolbar.
- Open the root `package.json` file and update the following line to be `false`
https://github.com/WordPress/gutenberg/blob/21421dc55dd2087cc629a16627866a452aecfe38/package.json#L22
- 🚨 **Rebuild** the Gutenberg Plugin `npm run dev`.
- Goto Site Editor and check that
    - you _cannot_ see the Nav Sidebar pinned item anymore.
    - the toggle is _no longer_ present in the Nav block toolbar.

⚠️ Don't forget to flip your `package.json` back to `true` again after you test this PR 😄 

## Screenshots or screencast 

The following screenshots show the elements that should be excluded by this PR:
Screen Shot 2022-04-06 at 07 10 11

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
Tested and works as described. The code is the minimal intervention required.

**Comment by draganescu** [comment]
Adding here for good measure @talldan 's mention that we should also check "if the original PR introduced any new selectors, actions or other public APIs and conditionally excluding those from core".

**Comment by Mamaduka** [comment]
@getdave this change triggers the following warning in Site Editor - WP 6.0 betas.

CleanShot 2022-04-28 at 17 45 49

**Comment by getdave** [comment]
I'll fix that

**Comment by getdave** [comment]
@Mamaduka I think [this fix](https://github.com/WordPress/gutenberg/pull/40722) should do the trick.

**Pull request merged**
