### PR TITLE
Columns: fix appender

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Restores the appender in the columns block after a non paragraph.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
There's one tiny problem with this, and that's this trailing empty div when the last block is a paragraph:

Screenshot 2020-03-25 at 12 19 39

**Comment by mtias** [comment]
This restores the inserter for me, but it makes it appear all the time now:

image

It should only show when:

- Focus is on parent block containing `InnerBlocks` (example: **Column**).
- When a child block within said inner blocks is selected (example: the **Audio** block within **Column**).

**Comment by ellatrix** [comment]
I think we should just merge this, and fix the small issue later.

**Comment by ellatrix** [comment]
@mtias This is how it worked before... Ok, I'll change it to those conditions.

**Comment by mtias** [comment]
@ellatrix there was a brief period where it worked well — cc @jasmussen as he looked at that when I mentioned it to him.

**Comment by jasmussen** [comment]
I'm looking at a CSS fix for the show on-select @ellatrix

**Comment by jasmussen** [comment]
Okay I pushed some CSS to fix this for the columns block:

columns

Note that this also regressed with the group block, it appears. I tried copying the fix you wrote here, and it does work it seems:

```
		<Block.div className={ className }>
			<div className="wp-block-group__inner-container">
				<InnerBlocks
					renderAppender={
						hasInnerBlocks
							? undefined
							: () => <InnerBlocks.ButtonBlockAppender />
					}
				/>
			</div>
		</Block.div>
```

adding that to the groups edit.js restores it. Any reason not to fix this also in this PR?

**Comment by jasmussen** [comment]
The CSS fix works also for Media & Text.

As mentioned, it doesn't for Group. 

media and text

**Comment by jasmussen** [comment]
Refined the animation a little.

It causes a jump when you select. Let's see if we can remove that separately.

columns


In https://github.com/WordPress/gutenberg/pull/21142/commits/ff69cf9f038f8ad4b01ebfb40796be6a38e5653c I took the liberty of "fixing" this issue for the group as well. Please sanity check that code for me as I copy pasta'ed @ellatrix fix.

**Comment by ellatrix** [comment]
For me this is good if it's good for @mtias and you :)

**Review by jasmussen — APPROVED** [review]

**Comment by ellatrix** [comment]
There's a strange unit test error that seems... unrelated?

**Comment by ellatrix** [comment]
The unit tests pass for me locally.

**Review by mtias — APPROVED** [review]
Let's get it in :)

**Comment by ellatrix** [comment]
(And I've already restarted the job.)

**Comment by ellatrix** [comment]
It seems like it's caused by the group fix, because the commit before that passes. 🤔

**Comment by ellatrix** [comment]
I will just merge because the failure is present in master...

**Comment by mtias** [comment]
Thanks for addressing this!

**Pull request merged**
