### PR TITLE
Taxonomiees: Improve Tags/Categories response size by limiting the requested fields

### LINKED ISSUE #3913: Tag search should only retrieve required data
## Issue Overview
When adding a tag, Gutenberg makes (debounced) requests to the server as I start to type a tag name. Each search hits the tags endpoint and returns the full data for (up to 100) tags matching my search. This can be a very large amount of data, here is a sample showing only **two results**:

The only data we actually need to retrieve here is the term name and id. This issue came up recently for the classic editor as we worked to transition from a custom ajax endpoint to using the rest api instead, see https://core.trac.wordpress.org/ticket/38922#comment:5 

Since https://core.trac.wordpress.org/changeset/41744 we should be able to retrieve just the fields we actually need, as in @ryelle's patch here: https://core.trac.wordpress.org/attachment/ticket/38922/38922.7.diff 

Here is the data returned after the patch:

## Steps to Reproduce (for bugs)
Create a new post and add some tags. Open the network inspector and examine the api requests made as you add tags.

## Expected Behavior
The api responses should only include the information required to display and add the tags: namely the tag name and id.

## Current Behavior
All data about each matching tag is returned, including _links data, resulting in a payload that is an order of magnitude greater than needed. This degrades performance and consumes far more data than needed, a potentially large consideration in some environments. 

## Possible Solution
Add `_fields: [ 'id', 'name' ]` to the api requests.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Test other searches in Gutenberg to insure only the required data is returned.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3913

Request only the required data from the taxonomies endpoints.

**Testing instructions**

 - Create a post
 - Create a tag
 - Type in the tags input
 - Check that the triggered requests only return `id`and `name` for each tag
 - Assign tags and check that it saves properly.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
Tests well for me 👍

**Comment by adamsilverstein** [comment]
Great!

**Comment by aduth** [comment]
Noting that `withAPIData` has built-in options for caching requests, so varying the `?_fields` parameter would be treated as a separate request.

**Comment by adamsilverstein** [comment]
@aduth that should be fine here though, right? since the ?_fields won't change? i'm not sure these requests should be cached because terms could change on the server and you would have to flush the cache (reload?) to pick up changes?

**Comment by aduth** [comment]
I guess in this case there's no difference since the hierarchical and non-hierarchical term selectors are querying different data anyways (categories vs. tags), but in other cases we're reusing the same data across many components so filtering fields could cause multiple requests unintentionally.

>i'm not sure these requests should be cached because terms could change on the server and you would have to flush the cache (reload?) to pick up changes?

_...Something something [hard things in computer science](https://martinfowler.com/bliki/TwoHardThings.html)_ 😄 

To the previous point, however, we definitely don't want to be firing 20 requests for the same endpoint just because 20 components happen to be using the data. Some amount of caching is quite reasonable to expect.

**Comment by adamsilverstein** [comment]
> Some amount of caching is quite reasonable to expect.

Absolutely! The caching you describe sounds ideal. Also, thanks for the link to the hard things source, I had only seen some of the riffs. 

In this case the request is an admin side search so minimal/no caching seems appropriate.

**Pull request merged**
