### PR TITLE
Block Library (Avatar Block): Remove Unnecessary '&& check' as 'optional chaining (authorDetails?.avatar_urls) check' is already used

### PR DESCRIPTION
**Pull request by hz-tyfoon**
## What?
In line number 81 & 85, There's `&&` check for `authorDetails` and then optional chaining (`?.`) is used. Looks like using both of them together is unnecessary. 
Just only using `authorDetails && authorDetails.avatar_urls` without the 'optional chaining (`?`)' is enough.
Or Just only using the latter check like `authorDetails?.avatar_urls` is also enough. (I did this one in my PR)

## Why?
In the scenario where `authorDetails` is `null` or `undefined`, just using the optional chaining check like this: `authorDetails?.avatar_urls`  will prevent any error and will return 'undefined'. So, in that scenario there won't be any error and also as `Conditional (ternary) operator` is used for `avatarUrls` & `sizes`, both of this will be `null` (won't cause any error).

### CODE REVIEW

**Review by cbravobernal — APPROVED** [review]
Thanks for contributing! LGTM! Let's see if we pass the admin e2e tests os we can merge it.

**Review by aristath — APPROVED** [review]

**Comment by hz-tyfoon** [comment]
> Thanks for contributing! LGTM! Let's see if we pass the admin e2e tests os we can merge it.

Thanks. 🙂

**Review by alexstine — APPROVED** [review]
Tested and looks good. E2E tests now passing.

**Comment by hz-tyfoon** [comment]
> Tested and looks good. E2E tests now passing.

Cool. Thanks @alexstine. 💚

**Pull request merged**
