### PR TITLE
Plugin: Bump minimum WordPress version to 5.3

### LINKED ISSUE #20484: Gutenberg is unintentionally incompatible with WordPress 5.2.x.
**Describe the bug**

Introduced in #17151. Quoting from https://github.com/WordPress/gutenberg/pull/17151#issuecomment-591633757

The [introduction](https://github.com/WordPress/gutenberg/pull/17151/files#diff-620130744b6b73b822a3df609671d930) of `gutenberg_extend_settings_image_dimensions` **breaks Gutenberg in WordPress 5.2.x**, due to the call to `wp_get_registered_image_subsizes`, a function [introduced in 5.3.0](https://github.com/WordPress/WordPress/blob/ac9b6fcef88b8de83ed551fa60e2e2d3cdf4e51e/wp-includes/media.php#L879-L888).

The Gutenberg plugin [requires WordPress 5.2.0+](https://github.com/WordPress/gutenberg/blob/d026d5b5c189e85bf1bb83321a74494c664e0159/readme.txt#L3). We should either bump that to 5.3.0, or guard against missing `wp_get_registered_image_subsizes` in `lib/client-assets.php`.

### PR DESCRIPTION
**Pull request by mcsf**
## Description
Fixes #20484 

With the release of RC1 for WordPress 5.4, and given the constraints raised in #20484, this PR bumps the required WordPress version for running the Gutenberg plugin from 5.2 to 5.3.

In the process, this PR eliminates the interception of core's `block_editor_preload_paths` filter, which was in place to provide compatibility for the following features:

- Preload autosaves (#15067). Landed in core in 5.3.
- Preload blocks permissions (#15061). Landed in core in 5.2.

@talldan, @aduth: As authors of the aforementioned PRs, could you confirm these removals for me?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Soean** [comment]
We also can remove `gutenberg_safe_style_css_column_flex_basis` and maybe `gutenberg_register_vendor_scripts`? @gziolo

**Comment by talldan** [comment]
@mcsf That looks good to me, thanks for handling that!

**Comment by gziolo** [comment]
> We also can remove `gutenberg_safe_style_css_column_flex_basis` and maybe `gutenberg_register_vendor_scripts`? @gziolo

I would keep `gutenberg_register_vendor_scripts` because we are going to bump React and lodash in the future and we need to test that in the plugin first. Those versions align with WP core but at least React had 4 minor releases in the meantime. We can remove `lodash` from the function because it's still the latest version.

**Comment by Soean** [comment]
@gziolo Ok, then we should adjust the the TODO inside the function: https://github.com/WordPress/gutenberg/blob/287498f4782ed74a28a1563a19212554b1807823/lib/client-assets.php#L214-L215

**Comment by mcsf** [comment]
@Soean, @gziolo: I've pushed 1018968 and 9ac1e2a, please have a look. 🙇 For the TODO note, I'll let you work it out.

**Comment by aduth** [comment]
> * Preload blocks permissions (#15061). Landed in core in 5.2.
> 
> @talldan, @aduth: As authors of the aforementioned PRs, could you confirm these removals for me?

Confirmed via: https://github.com/WordPress/WordPress/blob/5.3/wp-admin/edit-form-blocks.php#L51

**Comment by aduth** [comment]
I don't think we need the React or Lodash registrations? As of WordPress 5.3, the versions are the same as what we're overriding:

https://github.com/WordPress/WordPress/blob/5.3/wp-includes/script-loader.php#L94-L97

To @gziolo's point in https://github.com/WordPress/gutenberg/pull/20628#issuecomment-595147738, it might be something where we want to keep the function for the sake of anticipating some future use. I don't feel strongly one way or the other, but it would be easy enough to refer back to the history of the file to restore the function if and when it's needed once more.

**Comment by mcsf** [comment]
I really don't feel strongly about this; I can either remove `gutenberg_register_vendor_scripts` entirely, or hollow it out, or something else. State your preferences. :)

**Comment by aduth** [comment]
I'd suggest to just remove it altogether.

**Comment by mcsf** [comment]
> I'd suggest to just remove it altogether.

I starting doing this, then realised that `gutenberg_register_vendor_scripts` is used by the script `bin/get-vendor-scripts.php`, itself used by `bin/build-plugin-zip.sh`. I could remove `get-vendor-scripts` and remove the logic in `build-plugin-zip` to skip that step, but at this point I'm thinking that it's a lot of useful machinery that we might bring back soon. Despite [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), now I'm leaning more towards emptying the function and leaving it in place, so that every other piece can still rely on it. 

I've tentatively pushed 1be218b. Thoughts?

**Comment by aduth** [comment]
Fair enough. I don't feel too strongly about it, and agree that it would be a pain to bring everything back in place at a later point. One suggestion I might make is to include an inline code comment explaining why we have an empty function there.

**Comment by mcsf** [comment]
Done.

**Comment by aduth** [comment]
I'm glad you raised the point about the plugin build script and its implementation for downloading vendor dependencies. In revisiting my own #20225, I sense that the use of `gutenberg_register_vendor_script` there would not be sufficient to account for the polyfill in the plugin build. It's already the case prior to that pull request, too:

https://plugins.trac.wordpress.org/browser/gutenberg/tags/7.6.0/vendor
https://plugins.trac.wordpress.org/browser/gutenberg/tags/7.6.0/lib/compat.php#L58
https://plugins.trac.wordpress.org/browser/gutenberg/tags/7.6.0/lib/compat.php#L101

Trying to think how best to address this (without also needlessly blocking this pull request or #20225). I imagine the solution would be one of either (a) move these `gutenberg_register_vendor_script` into `gutenberg_register_vendor_scripts` or (b) update the implementation of [`get-vendor-scripts.php`](https://github.com/WordPress/gutenberg/blob/master/bin/get-vendor-scripts.php) to account for more than just `gutenberg_register_vendor_scripts`.

**Review by aduth — APPROVED** [review]
Per my previous comment, I think it will be easiest to merge this, then I can rebase my other pull request with the necessary changes to account for the polyfill vendor scripts.

The changes here look sensible to me 👍

**Comment by mcsf** [comment]
Thanks, I appreciate the deep dive and unblocking.

**Pull request merged**
