### PR TITLE
Format Library: add subscript and superscript

### LINKED ISSUE #3507: Buttons for superscript and subscript
## Issue Overview
Content editors don't have an easy way to use superscript and subscript.

Gutenberg version 1.7

## Possible Solution
As this type of formatting is applied only to a few letters, these buttons could be displayed only when the user selected some text.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #3507. Since rich text buttons are now in a collapsed dropdown list and not visible by default, it doesn't hurt to add these buttons, even if usage would be relatively low. The buttons represent semantic elements.

https://www.w3.org/TR/html52/textlevel-semantics.html#the-sub-and-sup-elements

Most editors have buttons for this, e.g. Google Docs:

Screenshot 2020-04-23 at 12 48 46

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
This is what I see:

subsup

Lovely, people are going to love this. I think it's also a good use of a dropdown.

I'd put both options at the end below text color, though. 

And yes, we do need some icons. I made these:

Screenshot 2020-04-24 at 12 00 23

I don't love them, but so long as we name them correctly, `subscript` and `superscript`, we can get them into the icon component and iterate. Here are SVGs:

Subscript:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16.9 18.3l.8-1.2c.4-.6.7-1.2.9-1.6.2-.4.3-.8.3-1.2 0-.3-.1-.7-.2-1-.1-.3-.4-.5-.6-.7-.3-.2-.6-.3-1-.3s-.8.1-1.1.2c-.3.1-.7.3-1 .6l.2 1.3c.3-.3.5-.5.8-.6s.6-.2.9-.2c.3 0 .5.1.7.2.2.2.2.4.2.7 0 .3-.1.5-.2.8-.1.3-.4.7-.8 1.3L15 19.4h4.3v-1.2h-2.4zM14.1 7.2h-2L9.5 11 6.9 7.2h-2l3.6 5.3L4.7 18h2l2.7-4 2.7 4h2l-3.8-5.5 3.8-5.3z"/></svg>
```

Superscript:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16.9 10.3l.8-1.3c.4-.6.7-1.2.9-1.6.2-.4.3-.8.3-1.2 0-.3-.1-.7-.2-1-.2-.2-.4-.4-.7-.6-.3-.2-.6-.3-1-.3s-.8.1-1.1.2c-.3.1-.7.3-1 .6l.1 1.3c.3-.3.5-.5.8-.6s.6-.2.9-.2c.3 0 .5.1.7.2.2.2.2.4.2.7 0 .3-.1.5-.2.8-.1.3-.4.7-.8 1.3l-1.8 2.8h4.3v-1.2h-2.2zm-2.8-3.1h-2L9.5 11 6.9 7.2h-2l3.6 5.3L4.7 18h2l2.7-4 2.7 4h2l-3.8-5.5 3.8-5.3z"/></svg>
```

**Comment by Wingo5315** [comment]
@jasmussen Implementation looks good – especially with the icons on the left of it!

**Comment by jasmussen** [comment]
> when text is selected, the subscript and superscript icons should appear to the right of the hyperlink butto

This doesn't scale very well to narrow contexts, and since you have to select something to make it bold would be barely different from having them there all the time.

Putting them in the drop-down is an effort to strike the balance between having the feature available, but recognizing that it's a feature you'll use rarely, unlike bold and italic.

This is always a difficult balance to find, but I think it's the right balance.

**Comment by ellatrix** [comment]
@jasmussen Perfect! Thanks for the icons!

**Comment by piettt** [comment]
Wonderfull !.
And if I can, I would say that adding a "non breaking space -"&nbsp;" this will also be fine.

Regard.

PS: how can we test or help ?

**Comment by paaljoachim** [comment]
Hey @piettt 

One way I usually help/test is to open PR's in gutenberg.run and add the PR number. It usually takes 3-4 tries before I am able to enter the site to test what the PR does. There I might take screenshots, or just in general see how something works and then give feedback.

Do also join the WordPress slack #core-editor channel. See https://make.wordpress.org/core/ for more information. 

Have a great day!

**Pull request merged**
