### PR TITLE
Remove `gutenberg_should_block_use_interactivity_api ` and the old implementation of interactive blocks

### PR DESCRIPTION
**Pull request by SantosGuillamot**
## What?
Remove the `gutenberg_should_block_use_interactivity_api ` function and the conditionals using it. Additionally, I took the opportunity to remove the old implementation of blocks using the Interactivity API.

## Why?
Now that we are planning on using the Interactivity API in both WordPress 6.4 and Gutenberg, we don't need to keep supporting the old versions.

## How?
I just removed the function that was checking if it was in Gutenberg and I removed the conditionals to ensure they work the same way in WordPress and Gutenberg.

Additionally, I reverted the changes made [here](https://github.com/WordPress/gutenberg/pull/52553/files#diff-a1f260292faa29d2f30136c99f839fd77d716b21450ec6ab89bb11e6f721a1eb) to only have the Interactivity API version.

## Testing Instructions
* Include a navigation block, check that it only enqueues the `view.js` file with the Interactivity API code, and check that the overlay menu and the submenu work as expected.
* Include a file block, check it only enqueues the `view.js` file with the Interactivity API, and check it shows the preview when the setting is activated.

### CODE REVIEW

**Comment by luisherranz** [comment]
An additional disclaimer for anyone seeing this PR: the version of the Interactivity API that we plan to merge with 6.4 will be private to Core blocks and still subject to change (or even be reverted if necessary). More info here:
- https://github.com/WordPress/gutenberg/issues/54291

**Review by luisherranz — APPROVED** [review]
Looks great, Mario! I've tested it and everything seems to work great 🙂

_BTW, I removed the directives example in the comment because it's a bit cumbersome to keep it up to date and I think that the Tag Processor code can be read easily enough._

**Comment by luisherranz** [comment]
@westonruter: now that we plan to proceed with [this plan](https://github.com/WordPress/gutenberg/issues/54291) for the Interactivity API in WP 6.4, we are removing the `gutenberg_should_block_use_interactivity_api` filter because it doesn't suit any purpose anymore and [it was causing problems in WP Core](https://wordpress.slack.com/archives/C055Y7FKS7N/p1694128892167449?thread_ts=1694112328.255489&cid=C055Y7FKS7N). I hope that is ok 🙂

**Comment by SantosGuillamot** [comment]
I just merged this pull request because it is blocking the package sync settings. @westonruter if you have any concerns I'm happy to revert these changes or work on an alternative. Just let me know 🙂

**Comment by westonruter** [comment]
I guess the only problem is that any minor releases between now and 6.4 won't be able to update the `@wordpress/block-library` package since 6.3.x still needs the removed code.

**Comment by luisherranz** [comment]
I thought those minor releases didn't use `trunk` but a release branch that still contains the `block-library` code in the state that was when it was merged with WP 6.3, and any cherry-picked fixes. And that packages for those minor releases were released in npm using a patch bump of the version that was included in WP 6.3 (that is, 8.Y.X where Y is the release at the time of WP 6.3 and X is incremental).

**Pull request merged**
