### PR TITLE
Image editing: try transparent zoom control

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Follow up to #23418.
For now it's not possible to put the range control inside the toolbar because it already handles horizontal keyboard navigation. In #23418 an additional toolbar was created, but I find it quite tightly packed for smaller images and it obscures the image.

|Before|After|
|---|---|
|Screenshot 2020-07-02 at 14 34 53|Screenshot 2020-07-02 at 14 33 10|

Another reason why I like this more is that the image, the scrolling and pinching gesture for zooming are closely connected to the slider control.

zoom-control

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
I do appreciate how this makes the zoom control work better in constrained spaces, something which would also be solved by moving it to the actual toolbar. But I wonder if there's sufficient contrast here, and I personally really liked the aspect ratio moving out of the toolbar and into context of the zoom bar. 

Have we looked into how hard it would be to get the zoom toolbar into the block toolbar itself? I do sense that it's getting very close to sunday here ... but on the other hand, we might end up with an image editing interface that feels frankensteinian :(

**Comment by ellatrix** [comment]
Contrast on white:

Screenshot 2020-07-02 at 17 14 40

Perhaps the "rail" could receive some shadow or an outline?

> Have we looked into how hard it would be to get the zoom toolbar into the block toolbar itself?

I don't know honestly. What would the solution be? Use Space/Enter and Esc to move focus into the slider?

**Comment by jasmussen** [comment]
> I don't know honestly. What would the solution be? Use Space/Enter and Esc to move focus into the slider?

Yes, what Diego suggested, that it's behaving like a popover inside the toolbar.

**Comment by ellatrix** [comment]
And wee also move the input field inside the toolbar?

**Comment by jasmussen** [comment]
Yep, and that's why it's important that all other buttons are hidden in this cropping/editing mode.

**Comment by ellatrix** [comment]
Closing in favour of #23677.

**Pull request closed without merging**
