### PR TITLE
Tweak more icons for high resolution devices

### PR DESCRIPTION
**Pull request by richtabor**
More work on https://github.com/WordPress/gutenberg/issues/49311.

## Screenshots

Before / After: 

icons

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Fantastic. Just needs a Figma update as well.

**Comment by richtabor** [comment]
> Fantastic. Just needs a Figma update as well.

Already done (just not published)! ✅

On the publishing note, what're the expectations on how often/when/how the library is updated/published?

**Comment by jameskoster** [comment]
I tend to publish once the associated PR is merged.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the release/16.1 branch to get it included in the next release: f315a17963

**Pull request merged**
