### PR TITLE
Chore: Update  package lock once more to resolve CI issue

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Seems like it's been updated again in the short time since #27098.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
I remember now why it's happening. There is some type of bug with the lock file and npm aliases. This must be one of the dependencies of Prettier or Puppeteer 😞

**Comment by ellatrix** [comment]
@gziolo This is what I mean with the package lock having to be updated all the time when (I think) some upstream package is updated.

**Comment by ellatrix** [comment]
Ah, ok 👍 😄

**Comment by gziolo** [comment]
There are two reasons why we use forks that create friction:
- spaces around everything aren't supported by Prettier formatting in JS
- we didn't want to download Chromium when Puppeteer installs from npm

**Pull request merged**
