### PR TITLE
Gallery Block: adding buttons to remove image from galleries inline

### LINKED ISSUE #2128: Gallery: Add inline editing to allow removing images from block
The gallery block currently relies on the core media modal dialog to remove individual images, this should be managed within the block itself. 

Add (x) for each image allowing for it to be removed from gallery block

### PR DESCRIPTION
**Pull request by youknowriad**
screen shot 2017-09-04 at 12 14 10

fixes #2128

### CODE REVIEW

**Comment by mtias** [comment]
I think you should "select" an image before being able to remove it. That should help with UI noise as well. (I explored it a bit in an old captions PR.)

**Comment by youknowriad** [comment]
> I think you should "select" an image before being able to remove it

how should we "show" the selected state? A stronger border on the image? any design proposals?

**Comment by mtias** [comment]
This was Joen's proposal back then:

image

**Comment by mtias** [comment]
For reference: https://github.com/WordPress/gutenberg/pull/1831

**Comment by munirkamal** [comment]
This looks great addition to the gallery block. Also how about adding the possibility to re-arrange the images in a gallery block inline, by simply drag-n-drop?

May be extending the "Joen's proposal" and add another icon for "move" which would allow to hold that image and move it within gallery block to drop on the desired place.

**Comment by youknowriad** [comment]
@mtias this toolbar in this proposal could overlap the block's controls toolbar. I'm putting it under the image to start.

**Comment by youknowriad** [comment]
After several attempts, I think showing the menu inside the image is the best approach for now. We'll have to revisit the "overflow: hidden" style of the wrapper if we want something like the proposal (above or under the image)

screen shot 2017-09-04 at 15 26 37

**Comment by youknowriad** [comment]
@munirkamal there's an issue for that too https://github.com/WordPress/gutenberg/issues/743 ;)

Feel free to add any complementary proposal/idea on the issue.

**Review by karmatosed — APPROVED** [review]
Looks good to me 👍

**Comment by mtias** [comment]
@youknowriad I think the X was better in this case, as the trash icon can sort of imply "deleting the image".

**Comment by karmatosed** [comment]
On seeing your comment @mtias I took a step outside and saw what existing pattern there was on in WP.

2017-09-04 at 21 24

In actual images:

2017-09-04 at 21 25

It made me think how obvious hovering is to seeing deleting. Would it maybe be good to see like this? Perhaps that's something to investigate though in testing.

**Pull request merged**
