### PR TITLE
ColorPicker: Only display detailed inputs

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Related:
- https://github.com/WordPress/gutenberg/issues/37981

## What?

Removes the requirement to toggle display of detailed input fields for the ColorPicker's different color models.

_This PR only addresses the UI change not updating pasted hex values. That will be addressed separately._

## Why?

To ease the editing of color values by reducing assumed knowledge and the number of clicks required to make a change via the inputs.

Further reasoning and discussion can be found in: https://github.com/WordPress/gutenberg/issues/37981

> Users who want to input their own custom HEX values need to learn to hit that icon before they can modify the current HEX value. I've found this to be confusing personally — more often than not, I'm coming here to input a custom value, not copy one, and I have to do an extra click to make that happen.

## How?

- Removes the toggling of "detailed controls" and instead immediately renders the color inputs
- Creates a new `ColorCopyButton` component internal to the `ColorPicker`. 
    - Handles copying a string representation of the current color model's value to the clipboard as per the functionality currently on trunk when the user clicks the color value prior to toggling on detailed controls.
- Removes the now unused internal `ColorDisplay` component.

## Testing Instructions

1. Ensure the existing unit tests still pass: `npm run test-unit  packages/components/src/color-picker/test`
2. Fire up Storybook and explore the new UX via the [ColorPicker Page](http://localhost:50240/?path=/story/components-colorpicker--default)
3. In the editor, create or edit a post, select a block e.g. paragraph and test configuring various custom colors still works. 

## Screenshots or screencast 

| Before | After |
|---|---|
| <video src="https://user-images.githubusercontent.com/60436221/169749207-b6a37d26-62e1-440f-b879-22feb46c67ed.mp4" /> | <video src="https://user-images.githubusercontent.com/60436221/169749224-32d4fa59-37a5-49d6-81ee-beda61b1542c.mp4" /> |

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
Nice work @aaronrobertshaw, the code change looks good to me, and having an explicit Copy button feels like a better use of space to me (and it also feels nicer being able to immediately interact with the Hex input field).

I noticed that each of the non-Hex inputs cause there to be horizontal and vertical scrollbars in my environment. I was wondering if the `AuxiliaryColorArefactWrapper` is slightly too big for the popover, and if it might need to be constrained somehow.



I see this is the same for those components on `trunk`, though, so also fine if you think we should address that separately (I think it felt a bit more obvious to me now that the dropdown to change color types is more prominent). What do you think?

**Comment by aaronrobertshaw** [comment]
Thanks for reviewing @andrewserong 👍 

> having an explicit Copy button feels like a better use of space to me (and it also feels nicer being able to immediately interact with the Hex input field).

Another reason for this was non-hex color models can't simply be copied from an individual input field. It made sense to me that the UI also be consistent between the different color models.

> I noticed that each of the non-Hex inputs cause there to be horizontal and vertical scrollbars in my environment. 

I noticed this as well when testing the recent change of Popovers to the floatingUI library. Given it was an existing problem on trunk, my plan was to address it separately.

**Comment by andrewserong** [comment]
> Given it was an existing problem on trunk, my plan was to address it separately.

That sounds reasonable to me. I've tested in Storybook + and in the post and site editors and this is otherwise looking good as far as I can tell (code looks good 👍). I couldn't quite work out why the Heading e2e test is failing, since it looks like it should be passing after your code change 🤔 (and stepping through those steps manually in the editor appears to work well)

Happy to do more testing / review again tomorrow!

**Review by andrewserong — APPROVED** [review]
Thanks for fixing up the e2e tests! This is still testing nicely for me after the rebase.

Unrelated to this PR, I've noticed some more slightly unusual behaviour with the Popover, on shorter screens when we open the popover closer to the bottom of the screen. When we switch between different color types, instead of the Popover moving up, we get a longer vertical scrollbar as in the screengrab below:



I believe this is to do with the `size` middleware we're using in the [Popover component's middleware](https://github.com/WordPress/gutenberg/blob/8b1492131355aa6d42272faba25b841f0cd4509d/packages/components/src/popover/index.js#L188) (currently it sets a maximum height, which is based on the available space between where the popover opened and the edge of the viewport). I think, along with the horizontal scrollbar, it could be a good thing for us to look at trying to tweak in follow-ups — potentially within the Popover logic. I ran into some related issues while working on https://github.com/WordPress/gutenberg/pull/41361 (which looks at removing the `maxWidth` setting), so just thought I'd mention it in case you've run into similar issues while testing this PR.

All that said, this PR looks good to me, and like I mentioned earlier, I think it's a much nicer way for it to work, with an immediately usable Hex field and a nice big Copy button 👍

LGTM! 🎉

**Comment by aaronrobertshaw** [comment]
Thanks for reviewing this again 🙇 

>  I think, along with the horizontal scrollbar, it could be a good thing for us to look at trying to tweak in follow-ups

Sounds like a plan 👍 

I'll get this merged to resolve https://github.com/WordPress/gutenberg/issues/37981.

**Comment by andrewserong** [comment]
> along with the horizontal scrollbar

I've opened up a (non-urgent) fix for the horizontal scrollbar in https://github.com/WordPress/gutenberg/pull/41646

**Pull request merged**
