### PR TITLE
Parser: Fix JS/PHP inconsistencies with empty attributes

### PR DESCRIPTION
**Pull request by dmsnell**
This patch updates a couple of inconsistent behaviors when dealing with
empty attributes and with the way PHP and JS treat empty objects differently.

## PHP empty attributes
When returning blocks without attributes the spec PHP parser has been
sending `[]` instead of `{}` due to complications of how PHP serializes
empty arrays to JSON.

In this patch we're adding a new test to verify the behavior and then
fixing the spec parser so that the output from the PHP version matches
the output from the JS version identically.

## Bug with empty attributes in comments
The default parser introduced a bug where `<!-- wp:anything {} /-->` would
fail to parse because it expected some content inside the curly brackets for
the JSOn attributes.

This is fixed in this patch by changing the `+?` quantifier in the RegExp
tokenizer with a `*?` to allow for empty attributes.

A test suite has been added to verify that when we parse an array of different
block formulations that they produce what we expect. A bug in a test was the
reason I didn't originally find this bug.

### CODE REVIEW

**Comment by mcsf** [comment]
I was about to approve this, but in the course of testing I found an issue that is also present in `master`:

Open Gutenberg's Code Editor, paste the following:

```
<!-- wp:foo {"id":824} -->
.
<!-- /wp:foo -->

<!-- wp:foo {} -->
.
<!-- /wp:foo -->

<!-- wp:foo -->
.
<!-- /wp:foo -->
```

I expected this to be preserved verbatim or at the very least to have the middle block "self-correct" by deleting its empty attributes object. Instead, upon blurring the code editor, I get this:

```
<!-- wp:foo {"id":824} -->
.
<!-- /wp:foo -->

<p><!-- wp:foo {} --><br>
.<br>
<!-- /wp:foo --></p>
<p><!-- wp:foo --><br>
.<br>
<!-- /wp:foo --></p>
```

Comparing the two spec and default parsers:

image

image

* * *

I assume this to be independent of the current PR, so it's up to you whether we should address it separately. In any case, 👍.

**Comment by dmsnell** [comment]
Thanks for pointing out that bug @mcsf - I saw that a day or two ago and forgot to submit a new PR to fix it - #11690

I believe this is due to demanding that attributes aren't empty, but there's no reason they can't be.

**Comment by dmsnell** [comment]
Squashed and rebased; former HEAD was 052c689

**Comment by dmsnell** [comment]
@mcsf I folded the `{}` fix into this PR since this is where all the tests are introduced. should be fixed for you now - thanks again for pointing that out.

**Comment by gwwar** [comment]
With d1acdf6 @mcsf are we good to 🚢 ?

**Review by pento — APPROVED** [review]
👍🏻 Looks good!

**Pull request merged**
