### PR TITLE
Prevent a block and console error for `input[type=email]`

### LINKED ISSUE #26983: DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement'
Reported by bradmarshall:
https://core.trac.wordpress.org/ticket/51577

-----

Actual behaviour:
dom.js is attempting to access the `selectionStart` property on input[type=email] in Gutenberg running WordPress 5.5.1, which triggers a DOM exception in the WP admin which breaks the gutenberg block containing the input.

Why?
This MDN article (https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) states that only certain types of inputs and textareas impmlement selectionStart / selectionEnd but it looks as though numerous functions throughout the file attempt to use selectionStart/selectionEnd without first qualifying the type of input in question. Therefore, any input[type=email] elements in a block are crashing out.

Expected behaviour:
dom.js should not attempt to use selectionStart/selectionEnd on just any type of input - it should instead first check to make sure it's one of type=text, search, URL, tel or password. Gutenberg blocks containing input types other than these should not crash.

Version: 
WordPress 5.5.1

### PR DESCRIPTION
**Pull request by kienstra**
## Description
Fixes an issue where if an `input[type="email"]` is at the top of a block, there's a block and console error. Though this is fixed once you reload the page.

## How has this been tested?
Steps to reproduce:
1. Use Chrome or Firefox, any WordPress version, like `5.5.1`, and the `master` branch of Gutenberg
1. Create a new post
1. Copy this into the console:
```js
wp.blocks.registerBlockType(
	'example/email-input-reproduce-issue',
	{
		title: 'Email Input',
		category: 'common',
		icon: 'wordpress-alt',
		keywords: [ 'Foo' ],
		attributes: {
			'email': {
				type: 'string',
			},
		},
		edit: function( props ) {
			return wp.element.createElement( 'input', { type: 'email', value: props.email } );
		},
	}
);
```
4. Insert the 'Email Input' block you just registered:insert-block
5. Expected: The block should display
6. Actual: There's a block and console error:
block-herb

```
DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('email') does not support selection.
    at placeCaretAtHorizontalEdge (https://path/to/wp-content/plugins/gutenberg/build/dom/index.js?ver=cbf62a0bae5cfd2eeff038ee115edc0a:390:32)
```

That error is from:
https://github.com/WordPress/gutenberg/blob/efc836a778dc8ee74d94e1cb8eecef2d0878f612/packages/dom/src/dom.js#L281

It [looks like](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) the `selectionStart` property applies 'only to text/number-containing or elements'. 

## Screenshots 
With this PR, there's no error:

no-error

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by kienstra** [comment]
Hm, the [PHPUnit failure above](https://github.com/WordPress/gutenberg/pull/26074/checks?check_run_id=1249754212#step:7:95) is from:

```
/var/www/html/wp-content/plugins/gutenberg/phpunit/class-block-supported-styles-test.php
```

...which this PR doesn't touch.

**Comment by kienstra** [comment]
This should be ready for review, not planning any more commits unless more builds fail.

**Review by nickcernis — APPROVED** [review]
Looks good! I confirmed the original report and fix.

Before:

Screenshot 2020-10-14 at 18 55 17

After:

Screenshot 2020-10-14 at 18 57 22

**Comment by kienstra** [comment]
Hi @ellatrix,
Would you be able to review this when you have a chance? Thanks!

**Review by talldan — COMMENTED** [review]
This looks like a worthwhile fix given an email input currently crashes the block 😓 .

The issue that I noticed when testing is that up/down arrow key navigation doesn't work in the same way for email inputs as it does for other inputs (see the search block for an example), the input is essentially a trap for navigating between blocks unless the user switches to navigation mode using `escape`.

I'm not sure if that's related to the change here or if some other code needs to be fixed. @ellatrix any thoughts?

**Comment by ellatrix** [comment]
It sounds like we need to adjust `isEdge` too?

**Comment by diegohaz** [comment]
Thanks a lot for contributing @kienstra! I just created #28559 based on this PR. I believe that solves this issue without the side effects @talldan mentioned.

**Comment by t-hamano** [comment]
Having checked this PR again, I assume that a similar problem may have been solved by #40192.

> The issue that I noticed when testing is that up/down arrow key navigation doesn't work in the same way for email inputs as it does for other inputs

This issue also appears to have already been resolved.

@talldan @ellatrix 
I think we can close the following issues and PRs, how do you think?

- #26074
- #28559
- #26983

### Screencast

https://user-images.githubusercontent.com/54422211/208304181-4a9abc07-fe2d-4fea-bbcc-3e3793a80b60.mp4

**Pull request closed without merging**
