### PR TITLE
[Documentation]: Spelling error in `JustifyContentControl` example

### PR DESCRIPTION
**Pull request by Tumas2**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by alexstine — COMMENTED** [review]
@Tumas2 Thanks for the PR.

Can you maybe add a quick note in the description for what this fixes? Other than that, looks good to go. For me, having a good description makes all the difference. You may even want to edit the title just to make this more discoverable in the future.

Thanks. 👍

**Review by ntsekouras — APPROVED** [review]
Thanks for your contribution @Tumas2 !

>Can you maybe add a quick note in the description for what this fixes? 

@alexstine's suggestion is a good one and having a good description is always helpful.

**Comment by Tumas2** [comment]
> Thanks for your contribution @Tumas2 !
> 
> >Can you maybe add a quick note in the description for what this fixes? 
> 
> @alexstine's suggestion is a good one and having a good description is always helpful.

Yes I will definitely do that next time.
Not gonna lie this is the first time I contribute to anything open source so I wasn't even sure this was gonna get looked at or picked up

**Comment by alexstine** [comment]
@Tumas2 We all start somewhere. Glad to have you contributing.

**Pull request merged**
