### PR TITLE
Template Switcher: Add current theme

### LINKED ISSUE #20469: Theme name in Template Selector
It'd be good to display the current theme name in the template selector of `edit-site`.

image

### PR DESCRIPTION
**Pull request by ockham**
## Description
Display the current theme name in the template selector of `edit-site`.

Since the `/themes` endpoint currently only exposes the `theme_supports` field for each theme, this PR adds a number of additional fields to it, using the `rest_prepare_theme` hook. (I also filed a https://github.com/WordPress/wordpress-develop/pull/222 against Core to extend the, err, upstream endpoint accordingly so that we can eventually drop the filter.)

In addition, this PR adds a new `getCurrentTheme` selector and related reducer/resolver/action to `core-data` (including a `themes` reducer for better normalization).

Finally, that selector is used to render the theme name in `edit-site`'s template selector.

The fields I've chosen to add should be sufficient to implement the on-hover previews seen at https://github.com/WordPress/gutenberg/issues/20469#issuecomment-597806801:

image

However, this PR doesn't implement those previews yet, since we need to implement the underlying fly-out menu component first (see #20470).

Fixes part of #20469.

## How has this been tested?
- If you haven't done yet, enable the site editor (and the demo templates) in Gutenberg > Experiments.
- Go to the Site Editor menu.
- Click on the template switcher.

## Screenshots

image

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by noahtallen** [comment]
I wonder, does the code in #222 need to go into the Gutenberg plugin for the time being? Otherwise, wouldn't the feature be broken until the next WordPress core update?

**Comment by ockham** [comment]
> I wonder, does the code in #222 need to go into the Gutenberg plugin for the time being? Otherwise, wouldn't the feature be broken until the next WordPress core update?

I think so, yeah. Probably by tapping into [`rest_prepare_theme`](https://github.com/WordPress/wordpress-develop/blob/90b0f49b1a36ed336f6416a8343e8d3d4bf491d0/src/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L175) I think? :slightly_smiling_face:

**Comment by ockham** [comment]
> > I wonder, does the code in #222 need to go into the Gutenberg plugin for the time being? Otherwise, wouldn't the feature be broken until the next WordPress core update?
> 
> I think so, yeah. Probably by tapping into [`rest_prepare_theme`](https://github.com/WordPress/wordpress-develop/blob/90b0f49b1a36ed336f6416a8343e8d3d4bf491d0/src/wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php#L175) I think?

Yep, that worked: c74cf62 :tada:

**Review by youknowriad — APPROVED** [review]
Probable some failures on php linting.  Otherwise, it looks good to me.

**Comment by ockham** [comment]
> Probable some failures on php linting. Otherwise, it looks good to me.

Thanks Riad! Ah, looks like it's actually a PHP unit test, I'll look into it.

**Pull request merged**
