### PR TITLE
Editor: Move PluginPostPublishPanel and PluginPrePublishPanel to editor package

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Related: https://github.com/WordPress/gutenberg/issues/52632, https://github.com/WordPress/gutenberg/issues/59878
Extracted from: https://github.com/WordPress/gutenberg/pull/60289

This PR  moves PluginPostPublishPanel and PluginPrePublishPanel to editor package. This is a prerequisite for unifying the publishing flow between post and site editors.

## Testing Instructions
1. Observe that previous panel usage from `edit-post` packages works as before
2. Test by rendering something in the slots from `editor` package.

Example code:
```
import {
	PluginPostPublishPanel,
	PluginPrePublishPanel,
} from '@wordpress/editor';
const MyPluginPostPublishPanel = () => {
	return (
		<>
			<PluginPostPublishPanel
				className="my-plugin-post-publish-panel"
				title={ __( 'My post panel title' ) }
				initialOpen
			>
				{ __( 'My post publish panel content' ) }
			</PluginPostPublishPanel>
			<PluginPrePublishPanel
				className="my-plugin-post-publish-panel"
				title={ __( 'My pre panel title' ) }
				initialOpen
			>
				{ __( 'My pre publish panel content' ) }
			</PluginPrePublishPanel>
		</>
	);
};
```

### Notes

The editor package doesn't auto generate docs and will explore this separately. I'll have a PR soon for that.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thank you, @ntsekouras!

The changes work as expected. I used the [`publish-panel.js`](packages/e2e-tests/plugins/plugins-api/publish-panel.js) example plugin for testing.

The failing unit test will need fixing before we can land this.

**Review by youknowriad — APPROVED** [review]
I didn't test but the changes make sense.

**Comment by gaambo** [comment]
I see the [editor package docs](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-editor/) and [slotfills reference](https://developer.wordpress.org/block-editor/reference-guides/slotfills/) still using the import from `edit-post`. 
Since this change is in the plugin right now, but will land in core 6.6 - when does it make sense to change documentation? What's the rule for such cases? 

I guess there's no hurry before 6.6, since even afterward the old import will work for two core versions. But does it make sense to change such required doc-changes somewhere?

**Comment by youknowriad** [comment]
In general, we used to make the changes to the documentation as we make the changes to the code. So we could make them right now.

It's true that it might confuse some developers but I feel like this is a problem that should be solved in the site (have a version selector or something)

**Comment by gaambo** [comment]
Thanks for the information, then I will make a PR for docs.

**Pull request merged**
