### PR TITLE
Set Style sidebar panel initialOpen to false

### LINKED ISSUE #24072: Initially close the Block Styles sidebar panel
Applying a Block Style is not be a high-priority action within a block's Settings Sidebar. Thinking through the flow of editing, its not likely a style will be changed often. I suggest initially closing the Styles `PanelBody` to limit the amount of actionable UI when a block's settings sidebar is opened. 

While not a _major_ deal using core blocks, if any third-party blocks add a Block Style to a particular block, it can quickly clutter the sidebar - pushing all other controls away and directly affecting cognitive overload.

### Before:
Screen Shot 2020-07-20 at 2 43 58 PM

### After: 
Screen Shot 2020-07-20 at 2 43 45 PM

### With CoBlocks (adding block styles): 
Screen Shot 2020-07-20 at 2 52 16 PM
Screen Shot 2020-07-20 at 2 50 28 PM

**Describe the solution you'd like**
Set the `initialOpen` prop to `false` for the Styles PanelBody which will clean up the Settings Sidebar UI and lowering cognitive overload.

**Describe alternatives you've considered**
Closing the Styles panel every time I open a block that has a number of Block Styles, before moving to edit additional sidebar controls.

### PR DESCRIPTION
**Pull request by richtabor**
## Description
This PR sets the initialOpen prop to false for the Styles PanelBody which will clean up the Settings Sidebar UI and lowering cognitive overload. Closes #24072.

### Before:
Screen Shot 2020-07-20 at 2 52 16 PM

### After:
Screen Shot 2020-07-20 at 2 43 45 PM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
This has been explicitly changed to true in a previous PR #20617 cc @pento @jasmussen

**Comment by richtabor** [comment]
> This has been explicitly changed to true in a previous PR #20617 cc @pento @jasmussen

Ah, I see. I still stand by the reason behind the change back. I'd appreciate feedback from @pento and @jasmussen for sure :)

**Comment by ZebulanStanphill** [comment]
It's kinda weird that Styles is even in the inspector in the first place. Every other control I can think of only appears in either the toolbar or the inspector. But Styles appears in both.

If I recall correctly (and correct me if I'm wrong), Styles was added to the inspector to make it more discoverable. But the inspector is supposed to be for secondary controls. It's where controls are supposed to be intentionally hidden to a degree.

To me at least, that seems to indicate that the real problem is that the purpose of the block/style switcher in the toolbar is not as obvious as it should be. The accessibility team has already [pointed out](https://github.com/WordPress/gutenberg/issues/21935#issuecomment-654405787) some of the issues with the current switcher design.

If the block/style switcher's purpose was more obvious, we wouldn't need the Styles panel in the inspector in the first place.
But as for a more immediate action, yeah

**Comment by ZebulanStanphill** [comment]
As for a more immediate action, though, I'm fine with this PR.

**Comment by pento** [comment]
I agree that there appears to be too much going on in the sidebar in the screenshots of the Image block, but I don't think changing the `initialOpen` prop of the Styles panel is the correct solution here.

Take the Quote block, for example:



Starting with the Styles panel closed makes the sidebar appear underutilised, there's a huge amount of blank space not being used.

Or looking at Jetpack's Map block:



Closing the Styles panel improves things a little, but there's still a lot going on. I suspect the overload stems from having multiple panels open, one after the other. I'm wondering if a better approach might be to have a clearer boundary between panels. Eg, 



(Disclaimer: this particular style obviously doesn't fit as a standalone change, but I think it illustrates the idea.)

**Comment by richtabor** [comment]
Perhaps an optimal solution would be that the Styles panel remembers its open/closed state editor-wide (like how the Document panels do)? So if a use closes the Styles panel on one block, its closed throughout the editor. Is that possible?

**Comment by richtabor** [comment]
I don't think its a matter of how much white-space is available, but rather how much cognitive load is present one way or the other. With a block such as the Quote block its not a big deal having it open - as there are no other controls - but for other blocks, even the JetPack Map block, its quickly an intensive experience. 

Also, if JetPack - or even another third party plugin - adds more map styles (which isn't out of the question), the styles will keep pushing the others controls out of the way, and keep adding to the cognitive load.

**Comment by jasmussen** [comment]
> I don't think its a matter of how much white-space is available, but rather how much cognitive load is present one way or the other. 

I think this is a good observation. However I disagree with changing it to be collapsed by default.

Part of the purpose of the G2 design revamp was exactly that, to reduce, simplify, optimize, combine and lighten this very cognitive load, editor-wide. 

We did not get to the sidebar with those efforts. But that doesn't mean we shouldn't. There are many many efforts that can be taken to simplify things here, including finding a better grid system for controls inside, reducing borders where possible, and making labels consistent and in the same spot, add contextuality where possible. Many of my recent PRs have taken steps towards that, [including by reducing the shades of gray](https://github.com/WordPress/gutenberg/pull/23648), and by [emerging steps for a grid system](https://github.com/WordPress/gutenberg/pull/23578). I hope to continue that work on a per-control basis, work with @ItsJonQ to improve things there. 

This is a much harder process than simply collapsing by default. But ultimately, I believe it is the better approach. By allowing things to collapse we are, to an extent, encouraging kitchen sink sidebar design. Whereas if we attack head on what makes it kitchen-sinky, we can benefit the issue at the core. 

In this case, I do agree that the style picker is in a bad state. For starters we've done a little work to improve it directly in the switcher: 

Screenshot 2020-08-03 at 10 37 29

I'd love if we found a way to make this feel natural enough that it might even be in the switcher _only_, but I'm not confident in that.

In the mean time, what are the biggest problem with the style picker display in the sidebar? To me:

- "Default style" feels like it's using a temp design
- The thumbnails could be visually simplified a bit, there are some mockups from Pablo I've seen for patterns, that might reduce this a bit.
- At the very least, the spacing between thumbnails and all around the panel, as well as the minimum default height could be massaged to make the entire panel be at least a third smaller, if not more.

All that would help.

**Comment by skorasaurus** [comment]
@richtabor 

The style sidebar panel has been redesigned (no longer including the image preview of style in the sidepanel) quite a bit and the initial issue has been closed (https://github.com/WordPress/gutenberg/issues/24072); want me to close this ?

**Comment by richtabor** [comment]
The current implementation is much better. Closing.

**Pull request closed without merging**
