### PR TITLE
update the block toolbar ESnext code.

### PR DESCRIPTION
**Pull request by bhvreddy**
the current code seems not working. but please check and proced. ( i am just started learning block editor )

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by aristath** [comment]
Hello @bhvreddy, thank you for working on this!

I haven't tested the changes yet, I just took a quick look at the diff. Could you please revert the spacing changes in this PR? Extra spaces are always used as per the [WordPress Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#spacing) to improve code readability :+1:

**Review by bhvreddy — COMMENTED** [review]
updated spaces - format

**Comment by skorasaurus** [comment]
Hi, 

Thank you for the contribution; I tested your changes in a new block; and they work for me! :)  The current tutorial code in trunk (found at https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/block-controls-toolbar-and-sidebar/#block-toolbar ) had not. 

I'm rusty on es5... I checked that code and I don't think that needs any changes to it (the existing code works for me) but would appreciate a second look.

**Review by skorasaurus — APPROVED** [review]

**Comment by bhvreddy** [comment]
I tested the es5 code, its works fine.

**Review by gziolo — APPROVED** [review]
Thanks for fixing it.

**Pull request merged**
