### PR TITLE
Docs: Enhance Block Context documents

### PR DESCRIPTION
**Pull request by atachibana**
@mkaz @aduth 

This PR is enhancement of block context:
- Added complete example based on this guide and E2E test code.
- Replaced `block.json` by example source code for consistency and easiness.
- Added notice to block context is not available to `save`. This is spec. See PR #21467 though I spent whole hour to search here and there ...

### CODE REVIEW

**Review by mkaz — APPROVED** [review]
-- Errant comment. Moved to #25299

**Comment by atachibana** [comment]
@mkaz 
Above your comment must be another issue's, though your discussion caused my interests :-)

**Comment by mkaz** [comment]
Ok, that is weird, maybe I had the tabs open wrong, that comment was intended for #25299

**Review by mkaz — APPROVED** [review]
This looks good, I like the full example included at the bottom.
Thanks!

**Review by aristath — APPROVED** [review]

**Pull request merged**
