### PR TITLE
Editor: Animate the inserter and list view panels

### PR DESCRIPTION
**Pull request by youknowriad**
Similar to #60561
Related to #60423

## What?

This PR animates the left sidebar of the post and site editors (opening and closing the sidebar). 

## Testing Instructions

- Try the post and site editors.
- Try opening and closing inserter and list view sidebars there.

### CODE REVIEW

**Comment by youknowriad** [comment]
So far this breaks zoom-out mode because:

 - In order for this animation to work we need a fixed width for the sidebar (or at least the interface component need to know the width of the sidebar). 
 - Everywhere in the post/site editors the width of the inserter and list views are fixed (350) except in zoom-out mode where the pattern inserter pushes the canvas, so the width is dynamic there.

We should either:

 - Abandon the idea of animating these sidebars
 - Make zoom-out work like regular inserters (the patterns cover the canvas a bit)
 - Leave the behavior of zoom-out as is and try to figure out a way to "provide" the sidebar width to the animation dynamically. (Obviously, I'll try exploring this but I'm unsure at the moment about how effective the solution would be, let's see).

**Comment by youknowriad** [comment]
Also, I don't really understand why the patterns inserter behaves differently between post and site editors, it should behave the same way IMO.

**Review by ellatrix — APPROVED** [review]
Compared to the sidebar one, this one feels a bit laggier, maybe we should look into optimising the inserter showing 🤔 I can see for example the scrollable height increasing while the animation is happening

**Comment by richtabor** [comment]
> Make zoom-out work like regular inserters (the patterns cover the canvas a bit)

If we want to have an experience where you compose pages with patterns, i.e. an "Add new page" flow where you browse and add patterns to a page without having to go in-and-out of the inserter, we can't have the sidebar covering the page.

**Comment by jameskoster** [comment]
If we _do_ animate these sidebars ideally they'd use the same easing as the inspector/global styles.

If you open the inserter, then open list view, there's a jump that would be good to eliminate (similar issue to the one in https://github.com/WordPress/gutenberg/pull/60561 when switching between inspector + global styles).

**Comment by richtabor** [comment]
> Also, I don't really understand why the patterns inserter behaves differently between post and site editors, it should behave the same way IMO.

Yes, let's bring zoom out to the post editor so we can make these 1:1.

**Comment by youknowriad** [comment]
I think this PR was not ready to merge :) you folks are too quick.

**Pull request merged**
