### PR TITLE
Social Link: add missing 'width' and 'height' attributes

### PR DESCRIPTION
**Pull request by merkys7**
## What?

All SVG in social-link.php have "...<svg width="24" height="24" viewBox="0 0 24 24"..." but the last one named "Share Icon" have no fixed WIDTH and HEIGHT
## Why?

No WIDTH and HEIGHT cause the large icon
## How?

Adds missing WIDTH and HEIGHT options

Related: https://core.trac.wordpress.org/ticket/51120

### CODE REVIEW

**Comment by amustaque97** [comment]
@merkys7 thank you for working on this 👏🏻 . It would be great if you can add testing instructions.

**Comment by carolinan** [comment]
I tried to test this but as far as I can tell, this icon is never used? When I add the block, I can not find an option to use it.
"Share" is not listed as a variation here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/variations.js
What problems does the missing size cause?

**Comment by amustaque97** [comment]
> I tried to test this but as far as I can tell, this icon is never used? When I add the block, I can not find an option to use it. "Share" is not listed as a variation here: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/variations.js What problems does the missing size cause?

yes right, even I was not able to figure it out. That's why I asked the author for steps to reproduce.

**Comment by Soean** [comment]
It is used as a fallback, if there is no Icon for the service: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/index.php#L96

You can test it by editing the code like this:
```HTML
<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"https://wordpress.org/","service":"this-does-not-exist"} /--></ul>
<!-- /wp:social-links -->
```

**Review by Soean — APPROVED** [review]
There is no visible change, but I think it is good to be consistent here.

**Comment by desrosj** [comment]
Just noting that this was also reported in [Core Trac](https://core.trac.wordpress.org/ticket/51120) and linking.

**Pull request merged**
