### PR TITLE
Display Saving label while save in progress

### LINKED ISSUE #707: UI: Separate out drafting, saving, publishing actions
We'll soon be able to save and publish posts! #594!

Once that's in, we should consider splitting the flow up, so the publish button doesn't do it all. 

**Saving & Publishing**

saving publishing

The indicator on the left shows the saved state. It autosaves the post, like it always has, and indicates when changes are saved. 

When there are unsaved changes, you can either wait for the auto-save to kick in, or you can click "Save", as a blue button.

The publish button has two roles:

- Publishing the post the first time
- Updating a published post

In addition to this, it can show a "working" animation when content is being published or updated. 

**Edit:** I updated the mockup to remove the dropdown button, as that is unrelated to this ticket. See also https://github.com/WordPress/gutenberg/issues/707#issuecomment-304934065.

### PR DESCRIPTION
**Pull request by aduth**
Closes #707
Related: #1203

This pull request seeks to resolve a regression introduced in #1203 where the "Saving" label is no longer shown in the header while a save is in progress. The issue is due to the fact that when a save begins, [post edits are cleared](https://github.com/WordPress/gutenberg/blob/d80189e0c958fdd07e119572f9caf11ebd47de28/editor/effects.js#L37-L40), meaning that the post is considered un-saveable (no title, content, or excerpt). Due to the order of logic in `SavedState`, this resulted in nothing been shown, instead of the "Saving" label, despite a save being in progress.

__Implementation notes:__

Should we really be clearing post edits when a save is initiated? My thinking is that we should optimistically persist them as being the current state of the post. cc @youknowriad 

__Testing instructions:__

Verify that a Saving label is shown after clicking Save in the editor bar, while the request is in progress. Using [Chrome Developer Tools network throttling](https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions) to emulate a slower connection can help identify the change in label.

### CODE REVIEW

**Comment by youknowriad** [comment]
> Should we really be clearing post edits when a save is initiated? My thinking is that we should optimistically persist them as being the current state of the post. cc @youknowriad

I don't understand, that's exactly what we're doing.

**Review by youknowriad — APPROVED** [review]
Tested and approved :) 

And thanks for the unit tests

**Comment by aduth** [comment]
>I don't understand, that's exactly what we're doing.

Right, my question could have been phrased better. I mean to suggest maybe we shouldn't be doing this.

**Comment by youknowriad** [comment]
@aduth We're doing so to avoid mixing the persisted edits with the edits added during the save. Diffing could be an alternative.

**Comment by aduth** [comment]
>avoid mixing the persisted edits with the edits added during the save

Why do we need to avoid it? Isn't this why we include redux-optimist, so we can revert if we need to?

**Comment by youknowriad** [comment]
@aduth but that's not about reverting. I'm having a hard time understanding what you mean exactly. We clear the edits before saving, that way new edits are added even if we didn't get the response yet and we're. So we're already optimistically clearing edits and moving them to the currentPost.

**Comment by aduth** [comment]
Okay, you've reminded me of the fact we need to preserve edits made while the save is in-flight. That makes sense now.

**Pull request merged**
