### PR TITLE
i18n: Add ‘translators’ note to Code block example

### PR DESCRIPTION
**Pull request by mcsf**
Follows #18964.

### CODE REVIEW

**Comment by aduth** [comment]
I don't see how this translator message could possibly be extracted, if it's not associated with any localization function.

See also: https://github.com/WordPress/gutenberg/pull/18964#issuecomment-562893296

**Comment by Soean** [comment]
A general question: In the WordPress plugin repository is only the minified code, without the translator comments, so can't use them at the moment, right?

**Comment by mcsf** [comment]
> I don't see how this translator message could possibly be extracted, if it's not associated with any localization function.
> 
> See also: [#18964 (comment)](https://github.com/WordPress/gutenberg/pull/18964#issuecomment-562893296)

Ouch. For context, I opened this very PR from my phone as a follow-up to that one, but somehow I missed the disappearance of `__`. I'll wait for the fix (#19001) and rebase. 

> A general question: In the WordPress plugin repository is only the minified code, without the translator comments, so can't use them at the moment, right?

This is a great question that I hadn't considered. Looking up a string in GlotPress seems to confirm that there's nothing in place to preserve translator notes.

**Comment by aduth** [comment]
@Soean It's likely, yes. I remember some initial discussion of this when the tooling around string extraction was changed toward relying on the plugin repository (I believe it's the same as in WP-CLI's i18n command). 

In any case, I don't know that it's been explored yet, the most direct solution here would seem to be some configuration of Uglify/Terser to allow these comments to remain. This configuration exists already, typically used for copyright/license headers. I think it can be reused for this purpose.

I've created #19006 to track this.

**Review by ellatrix — APPROVED** [review]

**Pull request merged**
