### PR TITLE
Template Loader: Localize empty template message.

### PR DESCRIPTION
**Pull request by epiqueras**
https://github.com/WordPress/gutenberg/pull/20239#discussion_r380369846

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
👍 Not much to look at :)

**Comment by mtias** [comment]
I had assumed this was just placeholder content for now?

**Comment by epiqueras** [comment]
Yeah, but is it wrong to localize it?

**Comment by mtias** [comment]
Not wrong, but should be generally unnecessary with very work-in-progress things as it'd trigger folks to waste some effort translating text that is ephemeral.

**Comment by epiqueras** [comment]
I suspected that. Should we revert this?

**Comment by mtias** [comment]
No need to :)

**Pull request merged**
