### PR TITLE
Post: add backdate warning

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Adds a notice to posts when the "scheduled" publish date is in the past. 

Addresses https://github.com/WordPress/gutenberg/issues/13230. 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by kjellr** [comment]
This is looking great! I pushed a quick spacing adjustment. Here are current screenshots: 

Screen Shot 2020-09-23 at 11 40 59 AM

Screen Shot 2020-09-23 at 11 40 48 AM

---

For that second one, I wish we could hide the border above the notice, but my brain is blocked thinking of a way to do that with CSS. 🤔 

Two other quick bugs: 

- I saw this notice appearing when I opened up _any_ old post, but I think it should appear only if the post is in draft mode, correct? 
- I noticed that [the empty panel](https://cloudup.com/c2kHw31V_jA) is appearing when the date is set to "Immediately". This should be hidden.

**Comment by ellatrix** [comment]
@kjellr Like this?

Screenshot 2020-09-23 at 18 55 04

**Comment by kjellr** [comment]
Yes, exactly!

**Comment by ellatrix** [comment]
I guess it would be nice if somehow it could be part of the button. Not sure what makes most sense in this case.

**Comment by ellatrix** [comment]
Without hover:

Screenshot 2020-09-23 at 18 57 11

**Comment by kjellr** [comment]
That looks great, thanks. I pushed a tiny update to adjust the top spacing to match other panels: 

Default|Hovered
---|---
Screen Shot 2020-09-23 at 2 33 31 PM|Screen Shot 2020-09-23 at 2 35 04 PM

**Comment by ZebulanStanphill** [comment]
We shouldn't be adding this as a separate section from the main Post Schedule section, as semantically that makes no sense. It also can't be part of the accordion's button text since that would mess up the (already not ideal) semantics/a11y. (The "Publish: PUBLISH DATE" label is not the right kind of button label. It should just be "Publish date" or something like that.)

The correct way to show this kind of information (both the current publish date and any important warning notice) would be through a summary that is separate from the button+heading of the accordion, but still part of the accordion, and shown when the accordion is collapsed.

Luckily, I've already implemented this in #25170, so I'd suggest checking out that PR and helping it get merged. Without the summary prop API, I think the best we can do is put the warning inside the main content of the accordion, which would risk users not even realizing its there if they don't open the accordion.

**Review by afercia — CHANGES_REQUESTED** [review]
Totally agree this info shouldn't be part of the panel button, as it would break the accordion semantics and accessibility: this is an info that is extraneous to the button's purpose. Also, as mentioned by @ZebulanStanphill, the Visibility and Publish panels accessibility is finally going to be fixed in #25170 and #24024 and this extraneous info would break that attempt.

Regarding the notice, seems to me this message is important enough to interrupt the user's flow (and interrupt whatever a screen reader is announcing in that moment) so I'd consider to make the `speak()` message assertive. I think this can be done by passing a `politeness="assertive"` propo to the Notice.

From a visual perspective, worth noting the first notice will appear behind the datepicker and it will be almost entirely hidden. Users would need to first close the datepicker to be able to see the notice:

Screenshot 2020-09-24 at 12 17 02

This is more a design thing but I thought to note it anyways.

**Pull request closed without merging**
