### PR TITLE
wp-env.json: Pin tt1-blocks dependency to v0.4.3

### PR DESCRIPTION
**Pull request by ockham**
## Description

Gutenberg's end-to-end tests were broken for a while after TT1 Blocks removed their `front-page` template (https://github.com/WordPress/theme-experiments/pull/179) -- which our e2e tests relied on. This was thankfully fixed on the Gutenberg side by @Addison-Stavlo in https://github.com/WordPress/gutenberg/pull/28638.

Per [discussion](https://github.com/WordPress/gutenberg/issues/28692#issuecomment-772797992) with @jeyip, we might be able to avoid a similar situation in the future by pinning our TT1 Blocks dependency to a given version.

See https://github.com/WordPress/gutenberg/issues/28692 for more background.

## How has this been tested?
Verify that automated tests pass.

### CODE REVIEW

**Comment by ockham** [comment]
Well, that didn't work :confused:

**Comment by ockham** [comment]
I think we probably need the long-form SHA (unless we get tags), but that's a bit gross -- ideally, we could pass shortened ones, and they'd get auto-expanded for us.

**Comment by ockham** [comment]
Found something here: https://github.com/nodegit/nodegit/issues/569, will try that.

**Comment by ockham** [comment]
Hmm, maybe the problem isn't so much in expanding short SHAs, but in the branch fetching logic (that maybe doesn't work with commit SHAs)? Found this: https://github.com/nodegit/nodegit/blob/7df154a5eb9e93ad933f0a9864f06e2395d32d21/examples/checkout-remote-branch.js -- might give this a try tomorrow.

**Comment by ockham** [comment]
I think the underlying issue is that `nodegit` is a rather low-level API wrapper for `libgit2` -- where things like `checkout` have a rather different meaning from their `git` CLI counterparts we all are used to.

I've noticed that for the GB release tools, we use a different git library, [`simple-git`](https://github.com/steveukx/git-js): https://github.com/WordPress/gutenberg/blob/8d1d96d6945c03a5759586b7ab7903e99164765a/bin/plugin/lib/git.js#L4
OTOH, `nodegit` is only used by `wp-env`'s download script.

So I think that he fact that `nodegit` is low-level and complex, and that there's `simple-git`, and that we're already using it :smile: is a good indicator that we might want to migrate the `wp-env`'s download script to `simple-git`, too :grimacing:

**Comment by ockham** [comment]
I just discovered https://github.com/WordPress/gutenberg/issues/26660. I think it's fair to say that this PR is blocked by that issue.

**Comment by ockham** [comment]
@carolinan has kindly tagged [`tt1-blocks@0.4.3`](https://github.com/WordPress/theme-experiments/releases/tag/tt1-blocks%400.4.3) in `theme-experiments`, so we should be able to use that tag instead of the commit SHA :tada:

**Comment by youknowriad** [comment]
Any idea how we'll keep this up to date?

**Review by youknowriad — APPROVED** [review]

**Comment by ockham** [comment]
Thanks for approving, Riad!

I'm almost surprised this works now -- it never did when I was using a commit SHA to pin instead. I guess it's because of the way we fetch with `--depth=1` (and `--no-single-branch`)? Which might give us tags, but of course no 'random' commits further down in git history. (`nodegit`'s error messages were unfortunately less than helpful when that happened. Due to `nodegit`'s low-level nature, it was just some complaint about an invalid `OID` or so.)

This means this PR is no longer blocked by #26660. However, it might still be nice to get #28848 in, since `simple-git`'s API (and error messages!) are more high-level, and easier on the eye :sweat_smile: 

> Any idea how we'll keep this up to date?

Manually, I'm afraid. That's the price we pay for a stable test environment.
IMO, it's a price worth paying: It might require us to communicate more with themes folks, but in exchange, we know that our tests won't break unexpectedly (as was the case with a [TT1 Blocks update](https://github.com/WordPress/theme-experiments/pull/179) that broke tests for around a day, until they were fixed by https://github.com/WordPress/gutenberg/pull/28638.). Instead, we can handle updates in dedicated PRs, where we can sort out any errors that might crop up in an isolated environment.

The alternative would be to stop relying on an external theme for testing, as discussed in https://github.com/WordPress/gutenberg/issues/28692 -- but that has of course other drawbacks; most of all, it's no longer a "real world" theme, so we might lose touch with latests developments and requirements of block template themes more easily.

**Comment by ockham** [comment]
Hmm, `package-lock.json` is out of sync. I've filed https://github.com/WordPress/gutenberg/pull/28884 to fix it.

**Comment by ockham** [comment]
#28884 has been merged, and I've rebased this PR :crossed_fingers:

**Pull request merged**
