### PR TITLE
Make a simple version of DefaultBlockAppender for mobile

### PR DESCRIPTION
**Pull request by Tug**
## Description
This PR creates a mobile version of DefaultBlockAppender so we can have it in the react native app

## How has this been tested?
Tested with https://github.com/wordpress-mobile/gutenberg-mobile/pull/299

## Screenshot

image

## Types of changes
- Mobile app compatibility improvements

### CODE REVIEW

**Comment by koke** [comment]
It works great, but it looks a bit basic.

screen shot 2018-11-29 at 19 16 44

@iamthomasbishop I don't see any designs for the default text, the closest I see is this placeholder:

screen shot 2018-11-29 at 19 16 06

In https://github.com/wordpress-mobile/gutenberg-mobile/pull/286 I introduced the color palette we're using in the apps, and https://github.com/wordpress-mobile/react-native-aztec/pull/82 started using NotoSerif for AztecView. Since you're calling `DefaultBlockAppender` directly from gumbo in https://github.com/wordpress-mobile/gutenberg-mobile/pull/299 maybe we can pass the style from there with the custom colors and fonts.

**Comment by iamthomasbishop** [comment]
I like your copy better :) The only thing I'd change is change `choose a block` to `add content`.

**Comment by iamthomasbishop** [comment]
The only change in style of a placeholder vs. default text is the color, which is `#87a6bc` (`$gray` in the WPcom color palette).

**Comment by koke** [comment]
I'll have limited availability next week, you might want to ask for another reviewer

**Comment by Tug** [comment]
Ok, I'll update the copy and the color 👍 
Btw, I was inspired from the Gutenberg web version which uses this one `Start writing or type / to choose a block`.

**Review by koke — APPROVED** [review]
Looks great 👍

**Pull request merged**
