### PR TITLE
Rollback navigation areas

### PR DESCRIPTION
**Pull request by adamziel**
## Description

Related to https://github.com/WordPress/gutenberg/issues/36524. This PR rolls back navigation areas.

## Test steps

Confirm that all editors load properly, and the navigation block is being saved and rendered as expected.

## Concerns

This block was shipped in Gutenberg 11.9, and now it's being reverted. It is hard to provide a fallback, too – it would essentially mean retaining the block. If Gutenberg is an "early preview" of the next WordPress, it should be okay to revert this PR. Still, I would like to get more opinions on that: @getdave @draganescu @noisysocks @talldan @mtias  @youknowriad @jsnajdr @youknowriad @spacedmonkey @tellthemachines @azaozz @hellofromtonya.

### CODE REVIEW

**Comment by spacedmonkey** [comment]
+1 to removing navigation areas. I have never really understood why they are needed. We already have menu locations. We could reuse those, instead of reinventing the wheel with this new watch of locating mechanism. 

What do we think of finding way to pin a menu block to a location?

**Comment by noisysocks** [comment]
> This block was shipped in Gutenberg 11.9, and now it's being reverted. It is hard to provide a fallback, too – it would essentially mean retaining the block. If Gutenberg is an "early preview" of the next WordPress, it should be okay to revert this PR.

One option might be to move the block behind the `GUTENBERG_PHASE` environment variable so that it remains in the plugin but does not ship in Core. In practice this would be done by registering the block in `__experimentalRegisterExperimentalCoreBlocks` instead of `registerCoreBlocks`. 

https://github.com/WordPress/gutenberg/blob/abff0e0bf0b1c50886c87175a7db1217442c736c/packages/block-library/src/index.js#L238

If the plan is to remove Navigation Area altogether, I'd suggest the following path:

1. Put Navigation Area behind `GUTENBERG_PHASE` so that it doesn't ship as part of WP 5.9.
2. Add a `deprecated()` notice to Navigation Area's `index.php` and `edit()` function.
3. Remove the Navigation Area after 2 plugin releases. (This is the Gutenberg deprecation policy.)

**Comment by getdave** [comment]
Once this is rebased we should be ready to rollback Navigation Areas. There now appears to be a consensus here that we should do that.

**Comment by noisysocks** [comment]
Removing this from the board as https://github.com/WordPress/gutenberg/pull/36727 is what we want for WP 5.9. (If I'm understanding things correctly.)

**Comment by draganescu** [comment]
With #36727 merged can this be closed?

**Review by spacedmonkey — APPROVED** [review]

**Comment by talldan** [comment]
Would be good to get an update on this.

I plan to remove the theme switching code as part of https://github.com/WordPress/gutenberg/issues/36962, btw. I may also remove a few other things.

**Comment by adamziel** [comment]
@talldan let's close this PR for now, it falsely suggests this is something to merge soon. In reality, we're waiting the deprecation period of two Gutenberg releases: https://github.com/WordPress/gutenberg/issues/36728

**Pull request closed without merging**
