### PR TITLE
Date: merge 6.4 and 6.5 compat files

### LINKED ISSUE #58431: Check whether the 6.4 script-loader.php compat file should be removed in favor of the 6.5 one
### Description

https://github.com/WordPress/gutenberg/pull/56682 added a compat file `lib/compat/wordpress-6.5/script-loader.php` for the Wordpress 6.5 release.

I'm not very familiar with how copat files work @Mamaduka pointed out that:

> There's already a gutenberg_update_wp_date_settings filter in WP 6.4; we should probably remove it to avoid double filtering.

And yes basically the new `lib/compat/wordpress-6.5/script-loader.php` file is the same of the 6.4 one with the only addition of one line. I'd appreciate someone more familiar with compat files than me to double check whether the 6,4 file should be removed. Cc @WordPress/gutenberg-core 

### Step-by-step reproduction instructions

Compare the filter callbacks `gutenberg_update_wp_date_timezone_settings` and `gutenberg_update_wp_date_settings`:
- `lib/compat/wordpress-6.5/script-loader.php`
- `lib/compat/wordpress-6.4/script-loader.php`
- Also important: evaluate whether the change from https://github.com/WordPress/gutenberg/commit/fa802d10e65c7d0951cc0f2357c367b0ab19861c needs to be added to the 6.5 comapt file

### Screenshots, screen recording, code snippet

N/A

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ramonjd**
Resolves https://github.com/WordPress/gutenberg/issues/58431

## What and how?
This commit merges the 6.4 and 6.5 compat changes for `gutenberg_update_wp_date_settings()`, and stores them in a single place in compat/6.5.

### 6.4 compat changes (already [merged to Core for 6.4](https://github.com/WordPress/wordpress-develop/pull/5101))
- https://github.com/WordPress/gutenberg/pull/53931 
- https://github.com/WordPress/gutenberg/pull/58406

### 6.5 compat changes (needs backporting for 6.5)
- https://github.com/WordPress/gutenberg/pull/56682

## Why?

Compat code consolidation and to avoid duplicate filters.

## Testing Instructions
Fire up this branch and open the editor.

In the browser console, run `wp.date.getSettings()`.

Check that properties exist for:

1. `timezone.offsetFormatted` exists
2. `l10n.relative.*` exists

Smoke test functionality.

1. Follow test instructions in https://github.com/WordPress/gutenberg/issues/56254 to see timezone offset
2. Run `wp.date.humanTimeDiff( new Date() )` in the console. You should see a relative translation `"a second ago"`

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
The changes work as expected. Thank you, @ramonjd!

**Comment by getdave** [comment]
Thank you for working on this and the associated backport to WP Core. I added it to the [PHP Sync Tracking Issue](https://github.com/WordPress/gutenberg/issues/57959).

Once the code is merged into WP Core we'd be grateful if you could:

- check off the line items in the [PHP Sync Tracking Issue](https://github.com/WordPress/gutenberg/issues/57959) 
- remove the `Needs PHP backport` label
- add the `Backported to WP Core` label

Thank you in advance 🙇

**Comment by ramonjd** [comment]
Thanks @getdave 

This PR doesn't need a backport. It's just a bit of cleaning up.

@afercia already has a patch for the 6.5 changes added to Gutenberg in https://github.com/WordPress/gutenberg/pull/56682

See: https://core.trac.wordpress.org/ticket/60105

**Comment by getdave** [comment]
Thanks for confirming.

**Pull request merged**
