### PR TITLE
Document settings: improve accessibility of "Status & visibility" controls

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
Partially addresses #470. This PR splits the "Status & visibility" panel into multiple smaller panels, making things more organized and more accessible. It's not perfect, but it's better than what we currently have. It's also brings consistency with the pre-publish checks.

## How has this been tested?
I tested to make sure the controls all still work, and the Post Format panel is hidden when post formats are not supported.

## Screenshots
(If the text seems to be missing some boldness, that's just due to my device's default font lacking enough font weight variations.)

image
image
image
image

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Notably, the pre-publish panel for post formats includes this helpful description of the feature. Should I add this to the standard Post Format panel? Before, it would have taken up too much space, but now that it is in its own panel, I think it's a good opportunity to reuse it there.
image

**Comment by jasmussen** [comment]
Thank you for the PR! Before:

before

After:

after

I believe a design problem was not considered in the mockup this is based on (https://github.com/WordPress/gutenberg/issues/470#issuecomment-627628262), which causes some problems. Notably that when all 4 panels are expanded, the total height takes up the entire space of the document sidebar.

It's unfortunate the old issue has lingered for so long. It seems like there was an agreement on https://github.com/WordPress/gutenberg/issues/470#issuecomment-510830072 as a path forward. My time is very limited right now, but I would very much like to work with you, or shepard myself, an implementation that implements that design instead.

**Comment by ZebulanStanphill** [comment]
Alright, I've drastically altered the implementation to be closer to the mockup linked by @jasmussen. Here's what it looks like now:

(Note that for the sake of this screenshot, I changed the font to "Noto Sans" which, unlike my system font, makes `font-weight: 500` look different from `font-weight: 400`.)

image

This implementation does not have the weirdly-labeled-button issue that my previous implementation had, so a11y-wise, it should be a definite improvement.

Notably, I kept Post Format in its own panel. I decided it belonged there for two reasons:

- Post formats don't really belong with the other controls, in my opinion.
- I wanted to be able to show the help text explaining what post formats are (copied from one of the pre-publish checks), which would have taken up too much space in the "Status & visibility" panel.

Overall, this implementation would be good to merge right now, except perhaps for one thing: the stylistic appearance... or lack thereof. I've gone pretty barebones here, and that's partially on purpose, to ensure that it doesn't end up looking too funky when the words get longer due to a language with long words.

It's true that in my previous implementation, the panels take up a lot of space when they're all open; but why would you have them all open at once? The solution to the a11y deficiencies of the previous implementation would be to add a way to show a summary/description below a **collapsed** accordion panel, with the description _not_ semantically being part of the heading/button that opens the panel.

It would be easy to revert to the previous implementation, but figuring out how to implement the panel description/summary idea is something I would need help with, both to figure out what the exact semantics should be, and also how to get it looking right with minimal CSS trickery.

It would be good to get some opinions from the accessibility team on how we should proceed here.

**Comment by afercia** [comment]
@ZebulanStanphill thanks for trying this! While the separation between the buttons action and the settings state is definitely an improvement, I'm not sure this PR goes in the direction that was discussed on Slack and that got some consensus on the original issue.

See Slack discussion starting from https://wordpress.slack.com/archives/C02RP4X03/p1589556569213500
See ast proposal and discussion on the original issue starting from https://github.com/WordPress/gutenberg/issues/470#issuecomment-627628262

The idea is to use the same UI of the pre-publish checks, which would allow for better consistency. It would also allot to remove the popovers in favor of the disclosure pattern, which is way more familiar to users. Ideally, the buttons of the current pre-publish UI should be changed as explained on https://github.com/WordPress/gutenberg/issues/470#issuecomment-635364842

**Comment by ZebulanStanphill** [comment]
@afercia I have reverted the PR to use the original approach (based on the pre-publish checks). I have also created #25170 to explore a solution to the a11y problems with the current "Title: State" approach.

**Comment by afercia** [comment]
@ZebulanStanphill cool, thanks! Tested it and the interaction with the disclosure panels feels to much natural and easy. Really hope we get some consensus here 🎉  

Agree the ideal companion for this change is #25170 which would finally solve #470 by separating the action from the state. One more 🎉

**Review by afercia — COMMENTED** [review]
From an accessibility perspective, this is a great and long hoped-for improvement. I'd definitely approve it from an a11y perspective.
Pending a more in-depth technical review and design feedback.

**Comment by shaunandrews** [comment]
I'm not sure how I feel about this.

Having a separate accordion for Visibility makes a lot of sense to me, and perhaps makes it more explicitly obvious the privacy of your document along with how to change it. I _do_ question the need for these repetitive text labels:

image

--

The "Publish: Immediately" accordion, however, is confusing; I think it's because "Publish" appears as a verb. I could see people being confused that tapping on the accordion could actually "publish immediately" rather than allow you to change the post's date. Perhaps it should say "Date: Now" or something? Or maybe there _isn't_ an explicit value until you select one.

--

Here's the bit that concerns me the most:

image

This General accordion is kind of nonsensical; Why are these things grouped together? Without the visibility and status in this section, the remaining items might need to find a better home.

**Comment by ZebulanStanphill** [comment]
@shaunandrews Thanks for the feedback.

I've switched to "Publish date:" labels now.

@afercia Is it okay to `display: none` the `<legend>` containing the "Post Visibility" text? The pre-publish checks already do this, but of course, that doesn't mean it's the correct approach.

As for the stuff in the General accordion, I agree the contents are kind of all over the place. I'm just not sure where else to put them. Would "Pending review" belong under the "Visibility" accordion? How about "Stick to the top of the blog"?

Also, it's important to remember that #25170 would help this PR immensely, and getting it merged would help solve the remaining problems that this PR can't fix alone. Also, this PR's branch is currently based on #24079, so that PR needs to get merged first.

**Comment by afercia** [comment]
> I think it's because "Publish" appears as a verb.

I'd agree "Publish" should be a noun and maybe just changing it to "Publish date" would make more sense.

> This General accordion is kind of nonsensical; Why are these things grouped together? Without the visibility and status in this section, the remaining items might need to find a better home.

Yep, I see that. Worth noting that Sticky/Pending/Author/Move to trash are already grouped within the "Status and Visibility" panel although they're not logically related to a "status" (at least not Author and trash) and certainly not to "visibility". One could argue that "sticky" does relate to visibility but not in the actual meaning of _the visibility setting_, which is only related to public/private/password protected. Te "sticky" setting has always been a source of debate in Classic Editor as well.

Personally, I'd like to see "Move to trash" in a more prominent place. In Classic Editor it's visually connected to the "Publish" button, which makes sense and also makes it easier to find. 

It would be great to see some exploration to find a better home for those 4 controls. On the other hand, those could just be left out from this PR and go in a follow-up. With some little help from design 🙂 

In the meantime, I'd agree this PR starts to solve a problem that is waiting since more than 3 years (see #470) and I'd love to see it merged.

**Comment by ZebulanStanphill** [comment]
Changing "Publish:" to "Publish date:" has a bit of an unfortunate visual side effect:

image

The spacing is already a bit weird here due to `display: inline-flex` being applied to `.component-button`, but the text wouldn't be this long if we were using the `summary` prop in #25170. In other words, please review that PR and help it get merged.

**Comment by ZebulanStanphill** [comment]
Just pushed a simple style fix for the text/icon overlap that could happen. All I had to do was increase the right-side padding to account for the expand/collapse icon.
image

**Comment by afercia** [comment]
> the text wouldn't be this long if we were using the summary prop in #25170.

I'd agree the text length issue is not a problem because it's addressed in #25170. The Safari / VoiceOver buggy behavior discussed there appears to be a VoiceOver bug. The information is available anyways, it's just not announced automatically.

@shaunandrews some design magic to "find a better home" for sticky, pending, author, and trash would be great. As said above, I'm not sure they belong to "Status and Visibility" even in the current implementation.

**Comment by enriquesanchez** [comment]
I agree with @shaunandrews that there's no need to repeat the label here:

88862009-d1b02a80-d1c4-11ea-910d-91d906facd4e

We can do without it and the overall control is still obvious:

Frame 97

Note: The above mockup is pending the feedback provided on https://github.com/WordPress/gutenberg/pull/25170#issuecomment-708719537.

---

I also agree that the stuff inside the 'General' panel feels thrown in without much thought, but you can also argue that not much is changing now because previously these were all under 'Status & visibility' all the same. 

We should change the panel's label from 'General' to 'Status', and this way we keep at least a bit of the previous organizaton. From "Status & Visibility" to "Status" _and_ "Visibility". 

For clarity, I'd only move the author's select component to the next line below. This should also help with space with long names and translations:

Frame 98

---

How does all of this feel to you, @ZebulanStanphill?

**Comment by ZebulanStanphill** [comment]
@enriquesanchez The author field is already displayed like that? As for the other stuff, I've gone ahead and implemented them. Here's how it looks now:

image

**Comment by enriquesanchez** [comment]
@ZebulanStanphill Looks great!

Screen Shot 2020-10-22 at 16 35 46

**Comment by ZebulanStanphill** [comment]
The "Status & visibility" UI has taken a different direction, and though much of the accessibility issues still remain, I no longer think the design in this PR is the best way to tackle them. I think something more like the [mockups shown here](https://github.com/WordPress/gutenberg/issues/39082#issuecomment-1185628521) is the way to go, albeit with some markup magic to make the function of the buttons clearer to screen readers.

These buttons are essentially virtual `<select>`s, except that they open full pop-ups rather than a simple menu like an actual `<select>`. Surely there must be a way to convey this concept to screen readers via HTML tags and attributes? Anything else feels needlessly space-consuming for the vast majority of users.

For these reasons, as well as a general lack of spare time on my part, I'm closing this PR.

**Pull request closed without merging**
