### PR TITLE
Limit NPM compatible version to be below 7

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

Related to https://github.com/WordPress/gutenberg/issues/28834, we have a dependency that is producing an error when running `npm install` with NPM version 7. Since this issue is coming from NPM, until a fix is released we could limit the use of NPM to version 6.

For this purpose, the PR adds a condition in the engine property of `package.json` file to set the version compatibility of NPM below 7.

_Documentation about the engine parameter: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines_

### Verify that dependencies are installed with NPM version 6
1. Run `npm install -g npm@6`.
2. Run `npm install`.
3. Observe that the installation succeeds.

### Verify that dependencies are not installed and fails with NPM version 7
1. Run `npm install -g npm@7`.
2. Run `npm install`.
3. Observe that the installation fails with an error related to the NPM version (see screenshot).

## Screenshots 
Screenshot 2021-02-15 at 11 44 29

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ockham** [comment]
Do we still need this, now that npm 7.5.3 is out, and https://github.com/WordPress/gutenberg/pull/28890 seems to fix the issue with Appium?

**Comment by fluiddot** [comment]
> Do we still need this, now that npm 7.5.3 is out, and #28890 seems to fix the issue with Appium?

Oh I didn't realised that there's a new NPM version 🎊 . I'll check it out but if it works with the Appium update we don't need this PR.

**Comment by fluiddot** [comment]
> Do we still need this, now that npm 7.5.3 is out, and #28890 seems to fix the issue with Appium?

Not sure why but looks like the CI is still failing with latest NPM version, you can check it in a [PR](https://github.com/WordPress/gutenberg/pull/28886/files) I created that updates the lock file format version of `package-lock.json` file to version 2.

I saw that NPM released recently a new version [`7.5.4`](https://github.com/npm/cli/releases/tag/v7.5.4) but the original issue regarding the dependencies install as described in this [comment](https://github.com/WordPress/gutenberg/issues/28834#issuecomment-776129586) hasn't been yet addressed.

**Comment by kevin940726** [comment]
Thank you for making this! I also made a PR before I noticed this: https://github.com/WordPress/gutenberg/pull/29204, it also tries to fix the `check-latest-npm` script.

> Do we still need this?

I believe we still need it until npm fixes https://github.com/npm/cli/issues/2610.

**Comment by fluiddot** [comment]
> Thank you for making this! I also made a PR before I noticed this: #29204, it also tries to fix the `check-latest-npm` script.

Thanks! Since your PR covers also the `check-latest-npm` script I think we could close this in favour yours.

> 
> > Do we still need this?
> 
> I believe we still need it until npm fixes [npm/cli#2610](https://github.com/npm/cli/issues/2610).

Good catch, I'm not sure if there're more cases affected by this issue but I managed to fix the ones located in the package `react-native-editor` (fix [here](https://github.com/WordPress/gutenberg/pull/28886/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119)) that were making the CI fail due to not having access to some repositories.

**Comment by ockham** [comment]
> > Thank you for making this! I also made a PR before I noticed this: #29204, it also tries to fix the `check-latest-npm` script.
> 
> Thanks! Since your PR covers also the `check-latest-npm` script I think we could close this in favour yours.

I've approved and merged that other PR :smile: I'll close this one.

Thanks all!

**Comment by kevin940726** [comment]
> Good catch, I'm not sure if there're more cases affected by this issue but I managed to fix the ones located in the package `react-native-editor` (fix [here](https://github.com/WordPress/gutenberg/pull/28886/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119)) that were making the CI fail due to not having access to some repositories.

Didn't know that there's a workaround for that! Seems like that there are other issues though 😅 .

**Pull request closed without merging**
