### PR TITLE
Added escaping function to p element attribute for 'dynamic' create-block template.

### PR DESCRIPTION
**Pull request by ghost**
## What?

This PR simply uses the `wp_kses_data();` function to escape the data, as per the Phpcs WordPress Coding Standards instruction within the IDE. Probably not essential, but I was confused.

### CODE REVIEW

**Review by ryanwelcher — APPROVED** [review]
This is a great addition! Thanks for taking the time to put it together.

**Comment by gziolo** [comment]
I’m not sure it’s necessary here. We should double-check at which stage `wp_kses_data` gets applied to all blocks.

**Comment by gziolo** [comment]
See:

https://github.com/WordPress/wordpress-develop/blob/9d4750abd0e72b77b015701b98f31ae77ced880b/src/wp-includes/blocks.php#L794

All blocks get automatically sanitized.

**Comment by ghost** [comment]
@gziolo, this doesn't appear to be strictly true. See [#2085](https://github.com/WordPress/WordPress-Coding-Standards/pull/2085#issuecomment-1258611559) in the WPCS Repo.

**Comment by Mamaduka** [comment]
I think per discussion in https://github.com/WordPress/WordPress-Coding-Standards/pull/2085, the hardening should happen in `get_block_wrapper_attributes`.

The current assumption is that the `get_block_wrapper_attributes` doesn't need escaping.

**Comment by jordesign** [comment]
@lewis-elborn  - just looping back to this stale PR to see if it is something you're still pursuing or if it can be closed?

**Comment by ryanwelcher** [comment]
Based on  https://github.com/WordPress/WordPress-Coding-Standards/pull/2085#issuecomment-1335254387, I think we should revisit this as something we should do. @Mamaduka @gziolo any thoughts?

**Pull request closed without merging**
