### PR TITLE
Update mixin that sets hover style on some buttons

### LINKED ISSUE #17337: Hover state of Top Toolbar buttons do not match
**Describe the bug**
The hover state of the Top Toolbar items do not match between the "Options" button on the far right, and the 5 buttons on the far left.

**To reproduce**
1. Hover over the "Block navigation" button in the Top Toolbar.
2. Observe the hover state.
3. Hover over the "More tools and options" button in the Top Toolbar.
4. Observe that its hover state is different.

**Expected behavior**
I expected the hover state of the "More tools and options" button to match that of the other buttons on the left side.

**Screenshots**

**Block navigation button** (hovered)

Screen Shot 2019-09-04 at 4 27 21 PM

**More tools and options button** (hovered)

Screen Shot 2019-09-04 at 4 27 06 PM

**Desktop (please complete the following information):**
 - OSX
 - Firefox 68.0.2
 - Gutenberg 6.4

### PR DESCRIPTION
**Pull request by enriquesanchez**
Fixes #17337

This is a small update to the `button-style__hover` mixin in `_mixins.scss`. The change makes the hover style match the "hard line" style used on the block toolbar and the "Settings" and "More tools & options".

hovers

## Some nitpicks

This change makes more noticeable the size/padding difference between the top toolbar and block toolbar buttons that was already present. Not sure if it's worth looking at this, thoughts?

toolbar-hovers

We also have another hover style in the block inserter, should we also look at updating this one?

Screen Shot 2019-09-25 at 1 27 47 PM

### CODE REVIEW

**Comment by mapk** [comment]
I really like the consistency here, @enriquesanchez! Thanks for taking this on!

I also noticed that this PR updates these as well, which is excellent.

icons

**Comment by mapk** [comment]
It also updated it here too:

toptoolbar

One thing to note for another PR is the "Block Navigation" popover hover state AND the block's "More Options" popover hover state don't match the rest of the popover hover states. We'll need to create another PR for this.

**Comment by enriquesanchez** [comment]
Thanks for the feedback @mapk!

I've created another PR (#17621) to address the hover styles of the dropdown menus.

**Comment by karmatosed** [comment]
Should buttons have the style that is coming from core over the hardline? Specifically, the publish button.

**Comment by enriquesanchez** [comment]
@karmatosed I'm not sure. Think that can be explored on another issue? Particularly if it refers to the Publish button.

**Comment by enriquesanchez** [comment]
@mapk I added the styles to match the updates from #17621, which has already been merged. Would you mind giving it a second look just to be safe?

**Review by mapk — APPROVED** [review]
Just tested again, @enriquesanchez and it works really well. It has removed the original hover effect which would have been odd keeping and now shows the lighter grey. Thanks! 👍 

hover

**Pull request merged**
