### PR TITLE
Comment Reply Link: Add border support

### PR DESCRIPTION
**Pull request by shail-mehta**
## What?

Add border block support to the `Comment Reply Link` block.

Part of https://github.com/WordPress/gutenberg/issues/43247

## Why?
`Comment Reply Link` block is missing border support.

## How?

Adds the border block support in block.json.

## Testing Instructions

- Go to Global Styles Settings. ( Under Appearance > Editor > Styles > Edit styles > Blocks )
- Make sure that `Comment Reply Link` block's border is Configurable via Global Styles.
- Edit Template/Page &  Add  `Comment Reply Link` block and Apply the border Styles.
- Verify that `Comment Reply Link` block styles take precedence over global Styles.
- Verify that `Comment Reply Link` block borders display correctly in both the Editor and Frontend.

## Screenshots or Screencast 

https://github.com/user-attachments/assets/51b5f6e3-b807-4bda-9f88-1e0cc836fd7a

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
Thanks for the PR @shail-mehta 👍 

Before landing this one, I'd like to seek some additional insight on how we might work toward a more curated UI, including consistent decisions across related or similar blocks.

@richtabor if you get a chance can you provide some guidelines that we might be able to apply to decide when block support controls should be displayed by default or not for a block?

As can be seen in this [tracking issue](https://github.com/WordPress/gutenberg/issues/43247) there are a lot of new PRs open adding border support. In most cases, the need for borders is pretty niche. The same could be said for spacing (padding/margin) support too. 

Would it be fair to say, that if the block is primarily typographic in nature it would be better to make spacing and border controls hidden by default? So all the link related blocks like post and comment navigation links have these controls hidden to start.

**Comment by richtabor** [comment]
> @richtabor if you get a chance can you provide some guidelines that we might be able to apply to decide when block support controls should be displayed by default or not for a block?

> Would it be fair to say, that if the block is primarily typographic in nature it would be better to make spacing and border controls hidden by default? So all the link related blocks like post and comment navigation links have these controls hidden to start.

Yea, that’s a good idea.

**Comment by shail-mehta** [comment]
I have added border control and spacing control, which are hidden by default. Additionally, I have rebased the current branch.

**Review by ramonjd — APPROVED** [review]
Margin/padding and border controls are hidden by default:

Screenshot 2024-09-04 at 10 48 48 AM

Block border styles overwrite the global styles. Looks as expected on the frontend:

Screenshot 2024-09-04 at 10 47 34 AM

**Comment by shail-mehta** [comment]
Thank you for the review.

**Pull request merged**
