### PR TITLE
Fix @wordpress/data documentation

### PR DESCRIPTION
**Pull request by fritz-cwp**
## Description
Fixed syntax errors and logic in the sample code in the README for @wordpress/data.

## How has this been tested?
Verified with a linter on my local environment.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by fritz-cwp** [comment]
I also wrote a little utility to overwrite the functions in the `registerGenericStore` sample code. The current sample only handles a flat object, but it seems like it will often be the case that the store has nested actions, e.g., `actions.articles.delete()`. The utility therefore will overwrite the functions on nested structures as well. It might be a bit overkill, so I left it out of this PR for now.

```js
const deepFunctionOverwrite = ( obj, replacer ) => {
	return Object.keys( obj ).reduce( ( acc, key ) => {
		if ( typeof obj[ key ] === 'function' ) {
			acc[ key ] = replacer( obj[ key ] );
		} else if ( ! Array.isArray( obj[ key ] ) && typeof obj[ key ] === 'object' ) {
			acc[ key ] = deepFunctionOverwrite( obj[ key ], replacer );
		} else {
			acc[ key ] = obj[ key ];
		}
		return acc;
	}, {} );
};

const mappedActions = deepFunctionOverwrite( existingActions, originalFn => ( ...args ) =>
	reduxStore.dispatch( originalFn( ...args ) )
);
```

**Review by aduth — APPROVED** [review]
Thanks for these fixes 👍 

>but it seems like it will often be the case that the store has nested actions, e.g., `actions.articles.delete()`.

While I've not considered it previously, it's not been something which has been needed, at least in Gutenberg's case as it's scaled up. I think it's instead that actions are either implemented (a) across unique stores or (b) generic enough to not need to exist distinct groupings if the behavior is common.

**Comment by jeffpaul** [comment]
@fritz-cwp I've tried to reach out via other channels, but I have been unsuccessful in getting in touch.  I wanted to make sure you saw the request to you for consent to re-license your contributions to Gutenberg under GPLv2 and MPLv2 here: https://github.com/WordPress/gutenberg/issues/31893.  If you would kindly review that description and comment accordingly it would be greatly appreciated.

Thanks!
Jeff.

**Comment by jeffpaul** [comment]
@fritz-cwp I've tried to reach out via other channels, but I have been unsuccessful in getting in touch. I wanted to make sure you saw the request to you for consent to re-license your contributions to Gutenberg under GPLv2 and MPLv2 here: https://github.com/WordPress/gutenberg/issues/31893. If you would kindly review that description and comment accordingly it would be greatly appreciated.

Thanks!
Jeff.

**Pull request merged**
