### PR TITLE
Experimenting with adding writing mode to layout

### PR DESCRIPTION
**Pull request by ramonjd**
## Description

TBD

https://user-images.githubusercontent.com/6458278/149256476-4bb87869-2c36-4523-be35-feb6d3bdfa3f.mp4

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by jasmussen** [comment]
Ths is exciting to see even as an experimental draft, thanks for working on it! Adding it to the group block could make sense, as opposed to having to add it to multiple paragraphs. On the other hand, it might be easier to handle the prominence of the feature (which I would still consider useful when needed, but still a bit of a rarity). An answer might present itself as we explore a bit further. (The Layout panel could use love regardless, it might even evolve into a tools panel on its own!)

Also from [the excellent conversation on the other thread](https://github.com/WordPress/gutenberg/issues/20926#issuecomment-1011680774), it seems like `text-orientation: mixed;` might make for a good starting point, wouldn't you think?

Really nice to see this, I think if we can manage the prominence right, it could be both a useful tool for language expression, as well as a nicely decorative tool for other contexts 👌

**Comment by ntsekouras** [comment]
Thanks for experimenting with this @ramonjd !

Personally I don't see how this fits with the `layout` abstraction. It feels like this could be more of a new support flag that adds the css value maybe?

**Comment by ramonjd** [comment]
> Personally I don't see how this fits with the layout abstraction. It feels like this could be more of a new support flag that adds the css value maybe?

Thanks for the comment @ntsekouras !!

Would you mind elaborating? If I understand correctly, the suggestion is to add the css value inline as per margin/padding? Or have it as a support flag underneath something else, e.g., typography. Or something else?

I had the feeling that it's probably not the most appropriate place to add the control, but I looked first at layout for reasons mentioned over in the [issue](https://github.com/WordPress/gutenberg/issues/20926#issuecomment-1011770664)

> I started off categorizing vertical text direction as a "layout" issue as opposed to a "typography", primarily because it requires a few layout changes, but also because fiddling with writing modes changes the block flow direction.

Also, changing the writing mode required overwriting css set by the layout hooks, e.g., margin-top. 

I suppose we could still detect writing mode support - wherever it exists –  in the layout hooks themselves and modify the CSS accordingly as we do with blockGap support. That sounds like a legit alternative approach. 👍 

Now that I'm seeing it half-working 😆 I'll play around with it. 

Cheers! 🍺

**Comment by ntsekouras** [comment]
Noting that I haven't thought this in depth, and just expressing my initial thoughts 😄 

>but also because fiddling with writing modes changes the block flow direction.

Exactly that! Right now the layouts we have implemented have been implemented with the default writing mode `horizontal-tb` and are already doing quite a lot of things there in terms of css rules setting (maybe we should also revisit that). So by changing a very fundamental prop(because it affects the block flow direction) we would need to add way more complexity and mix terms with what they are doing. For example if we apply this to `Group` and we have `paragraphs` or block in general that have `display:block`, they fill all the available space. What this means is that our `width` setting automatically becomes(need to be updated) as our `height`.

>Would you mind elaborating? If I understand correctly, the suggestion is to add the css value inline as per margin/padding?

So with the above being said, should/could this be a new layout entirely? Should we use this at a block level only? Could [CSS Logical Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) help us with this if we could apply them to the existing layouts?

Thanks again for experimenting with this though, because it's a way to get more answers.

--cc @youknowriad if you have any thoughts about this.

**Comment by youknowriad** [comment]
@ramonjd I'm still not sure whether this should be a layout property or its own dedicated one. The question for me is: does it make sense to apply this to a specific block or it only makes sense for container blocks?

When it comes to the "layout" dependency, it seems there's no dependency if we switch the `margin-top` to `margin-block-start` which takes the writing mode into consideration (maybe I'm wrong I didn't test).

**Comment by ramonjd** [comment]
Thanks @ntsekouras and @youknowriad for helping here. I'm grateful for your input and the questions. 🙇 

> The question for me is: does it make sense to apply this to a specific block or it only makes sense for container blocks?

> Should we use this at a block level only? 

I started from the assumption that we'd be applying writing mode to containers, e.g., Group or Column, because of the way the property affects a block of content and how individual units of content flow/stack themselves within that container.

For example, I assumed it would be easier to tell a Navigation block to render its children vertically, rather than set each child element individually. 

Looking at a few Japanese/Korean etc websites however, there's a bit of a mix: many designs apply the `writing-mode: vertical-[lr|rl]` definition to `<p />` or `<a />`, depending on the design. 

Screen Shot 2022-01-17 at 10 46 06 am

I think I need to experiment a bit more with what's possible in the block editor, and the balance between vertical writing for design's sake vs vertical writing as a practical content layout option.

All that aside, I still think it would be great to be able to offer users the ability to create websites such as the above. 😄 

> Right now the layouts we have implemented have been implemented with the default writing mode horizontal-tb and are already doing quite a lot of things there in terms of css rules setting (maybe we should also revisit that). So by changing a very fundamental prop(because it affects the block flow direction) we would need to add way more complexity and mix terms with what they are doing. 

This is a terrific observation!

If we were to define writing mode at a container level, maybe it would be useful to address the foundation first, that is, revisit layouts with the intention of explicitly implementing horizontal writing mode but with the intention that they may be toggled to "vertical".

I believe the advice that you both offer in relation to CSS logical properties and `margin-block-start` is a worthy place to start experimenting. 

This is something I hadn't yet tested, thanks for bringing it to my attention.

> I'm still not sure whether this should be a layout property or its own dedicated one

 I'm also still wondering at categorization. To me, it's almost a "typographic layout", as it affects the style of written language (vertically stacked characters) but also the orientation and direction of surrounding content.

Thinking of a possible future, we could open up a new category – "Writing Mode or something i18n-related" – through which we'd offer control over a block's RTL property, text orientation as well as horizontal/vertical writing mode 🤷 

Regardless, for now, I think to chip away at this, I can:

- experiment with some patterns in the block editor, comparing block- and container- level support for writing mode
- see if layout might benefit from [CSS logical properties ](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties)to allow frictionless switching of writing modes

**Comment by karmatosed** [comment]
First, this is amazing to see as a work in progress. 

> Also from the excellent conversation on the other thread, it seems like text-orientation: mixed; might make for a good starting point, wouldn't you think?

I kind of like the idea of setting things 'by the text' and it feels like a text-align, although I know that's got some complications.

**Comment by ramonjd** [comment]
I might move this to an issue to capture these discussions seeing as this PR might not survive. 

https://github.com/WordPress/gutenberg/issues/38038

**Comment by jasmussen** [comment]
> I might move this to an issue to capture these discussions seeing as this PR might not survive.

Just wanted to note that this PR has been an excellent test of the concept, showing opportunities and limitations. Thank you!

It seems like margin control is a bit of a doozy, since it _doesn't_ orientation with the text. I.e. if you have multiple paragraphs, something like `p { margin: 2em 0; }` will put them all flush side by side. That might be an argument in favor of starting with the property being just a single tool applicable via the typography panel, like so:

mock

You should still be able to select multiple paragraphs and apply it across all of them. It wouldn't solve the margin issue, but it might make it less prominent?

**Comment by ramonjd** [comment]
> That might be an argument in favor of starting with the property being just a single tool applicable via the typography panel

Thanks for putting more thought into this!

After researching/testing out different scenarios for [the issue](https://github.com/WordPress/gutenberg/issues/38038), I think I agree that beginning at the (text) block level might be the most pragmatic way to move forward.

We might miss out on the "block flow" aspect, that is, multiple paragraphs with `writing-mode: vertical-rl` properties will not be in the order in which they're supposed to be read (right to left), but we'll get the effect which is more than we have now. 

If we start smaller, hopefully it'll be more portable/amenable to iterative improvements too.

**Comment by ramonjd** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/38319

**Pull request closed without merging**
