### PR TITLE
Force POSIX implementation for strings relative path output

### LINKED ISSUE #597: Translation .pot build replaces '/' with '\' in Windows.
The dreaded Windows slash debacle appears to be present in the translation build.  Yes, I am one of those terrible Windows users 😲.  I am not familiar with how the build works, otherwise I would be glad to patch.  When the .pot file is built instead of:
```
blocks/components/editable/index.js:38
```

You get:
```
blocks\components\editable\index.js:38
```

Currently in all of my PRs I don't stage the .pot file for commit and hopefully the changes get put in on someone else's PR.  Most likely node's `resolve()` is changing the resolve to match Windows' paths since I am on Windows?

### PR DESCRIPTION
**Pull request by aduth**
Fixes #597 

This pull request seeks to ensure consistent output of the `languages/gutenberg.pot` file between Windows and Unix by forcing the relative path string references to use the POSIX implementation of [Node's `path` module](https://nodejs.org/api/path.html#path_path_posix).

__Testing instructions:__

1. Run `npm run gettext-strings`
2. View `languages/gutenberg.pot`
3. Note that file references use `/` slash, not `\`

@BE-Webdesign, would you mind taking this for a spin on Windows?

Note: As of #614, the `.pot` file is now ignored from the Git repository, so you shouldn't expect to see any changes reported by `git status`.

### CODE REVIEW

**Comment by BE-Webdesign** [comment]
This is better but I think the `process.cwd()` is still in Windows style, so when the path is made relative it doesn't work correctly.

I got it to work by doing something like this:

```
{ relative } = require( 'path' ).posix;
{ sep } = require( 'path' );
// Do the above however you want so that the module is not required twice.

// For the comments part
relative( process.cwd().split( sep ).join( '/' ), filename ) + ':' + path.node.loc.start.line
```

I don't know if that works on *nix.  I don't have node installed on my VM.

**Review by BE-Webdesign — CHANGES_REQUESTED** [review]
At line 205ish relative( process.cwd().split( sep ).join( '/' ), filename ) + ':' + path.node.loc.start.line.  Should be used where sep is taken from the base path module so it will match either a Windows separator or a POSIX separator.

**Comment by nylen** [comment]
Given that the .pot file no longer exists in the repository after #614, why do we need to do this at all?

**Comment by aduth** [comment]
>Given that the .pot file no longer exists in the repository after #614, why do we need to do this at all?

Since we'll still need to generate strings, I think there's value in ensuring that the output is consistent across OS's (OSes? OSs? Grammar 😩 ).

**Comment by BE-Webdesign** [comment]
The only benefit will come from someone who wants to help develop, work on translations and happens to use Windows.

**Comment by nylen** [comment]
Pretty sure the correct spelling is OS\es.  :trollface:

**Comment by aduth** [comment]
@BE-Webdesign I've taken another stab at this. I found `process.cwd()` could simply be replaced with `'.'` .

In my testing, there's still a minor issue where if the project is cloned in "My Documents", the filename passed from Babel starts with `C:/Users/<user>/Documents`, but `process.cwd()` evaluates to `C:/Users/<user>/My Documents/`, resulting in `../../Documents/` prefixes to files in the generated POT file. I think we'll want to investigate this, but I'm not considering it high enough priority for now to spend much more time on.

**Comment by BE-Webdesign** [comment]
>I've taken another stab at this. I found process.cwd() could simply be replaced with '.' .

Ah, that is a great idea.

>In my testing, there's still a minor issue where if the project is cloned in "My Documents", the filename passed from Babel starts with C:/Users/<user>/Documents, but process.cwd() evaluates to C:\\Users\\<user>\\My Documents, resulting in ../../Documents/ prefixes to files in the generated POT file. I think we'll want to investigate this, but I'm not considering it high enough priority for now to spend much more time on.

That is super edge-casey and I don't think warrants any fix really.  You can also mess with your user path a lot on windows so I wouldn't worry about this.

**Review by BE-Webdesign — APPROVED** [review]

**Comment by aduth** [comment]
Thanks for taking a look @BE-Webdesign !

**Pull request merged**
