### PR TITLE
Fix placeholder in the tag field was being cut off with long text

### PR DESCRIPTION
**Pull request by mirucon**
## Description
Fixed that the placeholder text in the tag field was being cut off when it's a long text. This mostly causes an issue with translations, such as Japanese and Chinese.

* With Japanese text
screen shot 2018-07-09 at 07 29 06

* With Chinese text
screen shot 2018-07-09 at 07 28 21

With the changes I made in this PR, it will be:

screen shot 2018-07-09 at 07 45 44
screen shot 2018-07-09 at 07 58 18

I use sibling combinator to make sure that the element "`components-form-token-field__input`" will not be 100% width when the placeholder is not shown. I could also use ":placeholder-shown" here, but since it's not supported by Edge yet, using sibling combinator would probably be better.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
Thanks for the pull request. I can confirm the problem in master; is there a related GitHub issue tracking this?

I am noticing a regression in behavior though: When inserting a tag, the caret is forced to a new line in the input even if it's not necessary to do so.

image

Since the input occurs within a flex container, I wonder if we could assign a `flex-basis: 100%` and `flex-shrink: 1` to let the input grow as much as possible (for the placeholder to be shown), but also shrink as needed?

**Comment by mirucon** [comment]
Thanks for pointing that out @aduth !
I just had a simple mistake in the previous commit so fixed it in the latest commit. Using `flex-basis` or `flex-shrink` wasn't really needed since `width: auto` works as we expect.
And I'm not really sure if there's GitHub issue for this; I just quickly searched but could not find one.

**Review by aduth — CHANGES_REQUESTED** [review]
I'm unforunately still seeing the newline issue noted in https://github.com/WordPress/gutenberg/pull/7795#pullrequestreview-137434900, even after the most recent commit.

**Comment by mirucon** [comment]
What browser do you use @aduth? I tried Google Chrome and Safari on macOS 10.13.5 and Microsoft Edge on Windows 10, these are working fine for me. I'm sure it also works on a secret window.
Anyway, there was conflict with the master, so I've back merged and resolved conflicts.

* Google Chrome
screen shot 2018-07-19 at 07 05 01

* Safari
screen shot 2018-07-19 at 07 32 22

* Edge
screen shot 2018-07-19 at 07 07 54

**Review by aduth — APPROVED** [review]
I think I must have been running a stale copy of the branch. Deleting it and starting fresh, it works as expected.

Thanks for the contribution, and for the patience in my stumbling through the review 😄

**Comment by mirucon** [comment]
Thanks for merging this! I actually forgot to update the CONTRIBUTORS.md file within the PR, would you mind doing it for me? My WordPress.org username is the same as GitHub username which is `@mirucon`

**Comment by aduth** [comment]
Sure thing. Added in ce6643a.

**Pull request merged**
