### PR TITLE
Heading block: add wide and full width options

### LINKED ISSUE #25655: Add wide- and full-width support to headings
**Is your feature request related to a problem? Please describe.**
Using wide-width or full-width container blocks like columns, groups, and covers, you can create some great text layouts. However, there's no way to align headings, for example, to the left-most edge of the container width, without putting it inside a container of it's own (like a columns block). This creates both UI and markup bloat, when all I want to do is adjust the width of a heading, like so:

image

**Describe the solution you'd like**
Add wide- and full-width support to heading blocks.

Note: this issue came up in relation to https://github.com/WordPress/twentytwentyone/issues/37.

### PR DESCRIPTION
**Pull request by oandregal**
Fixes https://github.com/WordPress/gutenberg/issues/25655

### CODE REVIEW

**Comment by kjellr** [comment]
When testing this PR, I'm not seeing these options available in the toolbar: 

Screen Shot 2020-10-07 at 2 24 58 PM

**Comment by nosolosw** [comment]
:thinking: it works fine for me 

201008-0844-heading-block-alignment

**Comment by nosolosw** [comment]
Rebased and pushed to fix the e2e tests (a fix was recently merged for them).

**Review by draganescu — APPROVED** [review]
Simple and useful update.

**Comment by jasmussen** [comment]
A couple of quick thoughts.

First off, this is a good update, as it enables some layouts that are currently _arbitrarily limited_. Especially if when a fullwide group block creates a centered column inside by default (just like post content), allowing these widths enables designs that were otherwise off-limits.

In fact it begs the question if not _all_ (or the majority) of blocks should enable these width buttons. For starters, perhaps, #25080 and #25147 would be good to address.

However it also brings up the question of where the control should live. For the heading block, it _barely_ fits on small screens:

Screenshot 2020-10-08 at 09 54 21

The separator block will be fine.

But if we are to bring this to all blocks (in future explorations), we can't actually put it in the toolbar for all of them. For a list block, it just won't fit. We could put in the sidebar as we have in the past for some blocks.

So as we add these controls to more blocks, it would be good to think about a basic heuristic for when it goes in the block toolbar, vs. a sidebar. One basic version would be: if it's a primary action, put it in the toolbar. The question then is, whether it's a primary action for the heading block — I'm not sure. 

That's not to hold up this PR — just that, maybe we want to move it to the sidebar in the future, as part of expanding these controls to more blocks.

**Comment by briceduclos** [comment]
@nosolosw Great! A useful addition would be to add these options to the paragraph block. As the paragraph supports large font sizes, it can be useful for some layouts. For example, here's a screenshot of a page designed by @melchoyce from the Twenty Twenty One Figma. For the moment, it's not possible to achieve this layout.

wide

**Comment by dianeco** [comment]
@nosolosw The options aren’t in the same order as for all the other blocks: Wide width should be before Full width.

`"align": [ "full", "wide" ],` should be replaced by `"align": [ "wide", "full" ],`

**Comment by nosolosw** [comment]
Thanks for reporting, Diane! I wasn't aware that set the order for the controls. Fix at https://github.com/WordPress/gutenberg/pull/26260

**Pull request merged**
