### PR TITLE
Support [nested] lists in table cells by reformatting simple content to appear more list-like.

### PR DESCRIPTION
**Pull request by mpkelly**
**Note**: This PR needs some more test cases, and some edge cases could be improved, but I'd like to get feedback on the general approach. 

Related to https://github.com/WordPress/gutenberg/issues/45774

## What?
It's based on requirement 2 from https://github.com/WordPress/gutenberg/issues/45774. It allows `ul` and `ol` elements to be pasted into tables. These elements are converted to simple content and whitespace is used to make them look like the source lists. 

## Why?

Increase parity between Gutenberg and other editors. 

## How?

Allow the list schema to be embedded into `td` and `th`. Add a `transform` function for `tables` that can reformat lists. 

## Testing Instructions

1. Check out this branch and create a table in Google Docs that has ordered or unordered in its cells. See the screenshots below. 
2. Paste the table into Gutenberg to see the result
3. Try adding content before/after the list.
4. Try nesting lists to any depth. 

## Screenshots or screencast 

Google Docs table with lists

image

Gutenberg

image

Note that the two arrows. This content was added to a `li` by using `shift` + `enter`. Ideally, they should be indented so they look closer to the source content.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> This PR needs some more test cases, and some edge cases could be improved, but I'd like to get feedback on the general approach.

@mpkelly Oof, this looks like a bit of a rabbit hole. Sorry I dragged you into this!

Overall, the approach you've taken seems in line with my expectations. While it might not be perfect, it's certainly better than the current behavior.

@ellatrix What do you think about the proposed changes? Is there anything you might do to improve upon it?

**Comment by ellatrix** [comment]
1. What's the use case for lists in a table? From your example, it seems like there's more lists in a single cell than table, which may not be what table is designed for?
2. I'm very hesitant to make allow any block in table at all. Tables are great for data, but we shouldn't tempt user to using it for layout.
3. It becomes much harder to add features like sorting later on.

I see that you're not using the table block right now? How will this be edited without the block?

**Comment by ellatrix** [comment]
Oooh, I see that you're creating markdown. Can't we use showdown (which we are already using) to convert the HTML to markdown?

**Comment by mpkelly** [comment]
Thanks for your input, @ellatrix. 

>What's the use case for lists in a table? From your example, it seems like there's more lists in a single cell than table, which may not be what table is designed for?

The plan was to allow pasting content like this while still making it look list-like:
https://user-images.githubusercontent.com/36432/201934749-9beeaf3f-d078-4d13-bf7e-b25229f03e46.png

> I'm very hesitant to make allow any block in table at all. Tables are great for data, but we shouldn't tempt user to using it for layout.

I need some guidance here. I changed some code called "paste" schema and figured this would only allow lists to be supported in memory during paste. Is this not correct?

> It becomes much harder to add features like sorting later on. 

It's only simple content that gets added to the block after the paste transformation.

> Oooh, I see that you're creating markdown. Can't we use showdown (which we are already using) to convert the HTML to markdown?

Actually, it's not markdown, just simple HTML content that the table cell already supports that is made to look like a list without using `ul`, `ol`, or `li` elements.

**Comment by mpkelly** [comment]
@danielbachhuber I don't know if it will be easy to detect new lines created with `shift` + `enter`, so we might want to consider shipping this, which is still an improvement. For reference, here's what you'd see if those two lines I highlighted above were removed. 

image


image

And here's your original table. It will look better once I rebase with trunk and `colspan` is supported:

Screenshot 2565-12-07 at 15 41 39

@ellatrix, how do feel about this getting merged? Hopefully I answered your questions above.

**Comment by danielbachhuber** [comment]
> I don't know if it will be easy to detect new lines created with `shift` + `enter`, so we might want to consider shipping this, which is still an improvement.

@mpkelly Sounds good to me!

**Comment by mpkelly** [comment]
Looks like I messed up my rebase. I am going to create a new branch and PR.

**Pull request closed without merging**
