### PR TITLE
[RNMobile] Splitting block causes content loss

### LINKED ISSUE #2373: Splitting Block Before Swiped Word Loses Word
### Describe the bug

On Android, splitting a paragraph block with the cursor immediately before a swiped word causes that word to be lost.

losing_word_on_split mp4

### To Reproduce

1. Add multiple words to a paragraph block by "swiping"
2. Place the cursor directly in front of one of the words you entered by swiping
3. Tap Enter to split the block
4. Observe that the word the cursor was immediately in front of was lost in the split

### Expected behavior

Splitting a block should never lose content.

### Smartphone
 - Device: Pixel 1
 - OS: Android X
 - Version: 1.30 release testing (c2a85e0)

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2373

Gutenberg Mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/2777

## Description
When we press enter in front of swipes words, it causes the cursor to go on the new line but the text that follows is deleted. 
This was occurring because there's an `EnterPressedWatcher` that processes the input changes of the `AztecText` component and the logic within it was causing the deletion. For more clarity, within `EnterPressedWatcher` there exists logic that determines if the changes contain a newline character which would mean that the enter key was pressed. Once this exists then we simply replace this character with space and send an event to the `RichText` component from within `ReactAztecText` with this change. The problem with the current approach is that we are only looking for the character at the end of the changed content received from the `AztecText` component and as noticed in the demonstration below, we can press enter anywhere within the `RichText` component so the solution for this is to utilize the `start` index of the changes to determine if a newline character was inserted and thus all changes that follow that newline will be propagated instead of a single character.

## How has this been tested?
To test that this behavior has been fixed you can follow the testing instructions below. 

----------------

### Swiped words with Google Keyboard

1. Ensure that Google Keyboard is installed on a physical android device. 
2. Swipe a set of words. 
3. Put the cursor before the last word that was swipe in. 
4. Press enter. 
5. Observe that the enter action has put the content after the cursor on a new line and the text was not deleted. 

Before | After 
--------|-------
  <kbd></kbd> | <kbd></kbd> 
      
-------------------

### Typing words with a normal keyboard

1. To ensure no regressions have occurred, simply type and press enter normally. 
2. Observe that the cursor and enter action behaves as expected and no text has been deleted. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
Thanks a lot for working on this @jd-alexander! I verified that swiped words are no longer lost as described in the issue, but there's a regression in Paragraph blocks.

Typing Enter inside a Paragraph block should split the block, however what I'm seeing is that a new line is created instead. (There are blocks that allow newlines such as Verse and Preformatted, and they're working great.)

<details>
  <summary>See screen recording</summary>
  <table>
    <tr>
      <td></td>
    </tr>
  </table> 
</details>

**Comment by jd-alexander** [comment]
Thanks for checking this @guarani I am going to have a look at it again to see what's causing this.

**Comment by jd-alexander** [comment]
Just an update for this task. I spent some time digging into it yesterday trying to figure out the root cause of the splitting issue since this solution hasn't solved it completely. I eventually took a look at the `onSplit` behavior of the `RichText` component because the new paragraph block that is being created ( and has its text disappearing) is attached to this functionality. 

Next steps is to put breakpoints into the [`onEnter` function of the `RichText`](
https://github.com/jd-alexander/gutenberg/blob/18e102cce854d839a5518c54b8823c3d28797e88/packages/block-editor/src/components/rich-text/index.js#L338) component that causes the splitting to see where the value is actually being lost since the fixing the `TextWatcher` resolved the first issue. 

I will try to take another look at this soon.

**Comment by jd-alexander** [comment]
@guarani I will be closing this PR for now. I had another look on Friday at it and I wasn't able to make much progress in tracking down the issue. I think we are close to finding the cause of this. This can be revisited at another HACK Week.

**Pull request closed without merging**
