### PR TITLE
Add richText identifier to blocks

### LINKED ISSUE #58996: Return AttributeKey as number
### Description

`getSelectionStart()` function of block editor return attributeKey as number in Gutenberg file block. is it expected behavior? Shouldn’t it return selected attribute key from available attributes of file block instead of number ? what does this number represent ?

### Step-by-step reproduction instructions

Execute `wp.data.select("core/block-editor").getSelectionStart()` after selecting file block in editor

### Screenshots, screen recording, code snippet

CleanShot 2024-02-14 at 11 40 34@2x

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by akasunil**
Fixed https://github.com/WordPress/gutenberg/issues/58996

## What?
Added `RichText` Identifier to some blocks.

## Why?

`getSelectionStart() `function of block editor return number as attribute key for blocks instead of attribute name in string.

## How?

I have added `RichText` Identifier argument for some block's `RichText` component where this argument was missing.

## Testing Instructions

   - Go to gutenberg editor
   - Focus on core/file block
   - Execute `wp.data.select("core/block-editor").getSelectionStart()` 
   - you will receive focused attribute name as string ( either fileName or downloadButtonText, whichever you are editing) instead of number

### CODE REVIEW

**Comment by Mamaduka** [comment]
Thanks for the PR, @sunil25393! Could you include testing instructions in the PR description?

**Comment by akasunil** [comment]
@Mamaduka Updated PR description with testing instructions

**Review by jsnajdr — APPROVED** [review]
Looks good, thank you for a thorough fix :+1:

**Comment by jsnajdr** [comment]
@sunil25393 Can you please rebase your fork branch onto the latest `trunk`? That should hopefully fix the failing e2e tests.

**Pull request merged**
