### PR TITLE
Reusable blocks e2e tests fail if starting from new post

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
Sparked by #9962. These tests should still pass and demonstrate some issues starting from a new post.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by iseulde** [comment]
See 
https://github.com/WordPress/gutenberg/issues/9962#issuecomment-425752585.

**Comment by aduth** [comment]
cc @noisysocks

**Comment by noisysocks** [comment]
I rebased this and pushed up some changes which should hopefully fix the failing tests here.

There were three problems:

**1) A reusable block's _Name_ field would get selected after a `fetchReusableBlocks()`**

After a successful fetch request, `RECEIVE_REUSABLE_BLOCKS` was dispatched which would then in turn dispatch `RECEIVE_BLOCKS`. This meant that there was a brief moment (after the first dispatch but before the second dispatch) where `getReusableBlock( ref )` would return a reusable block that referenced a block that didn't exist in the store. This caused the block to render its _Block has been deleted or is unavailable_ message, which in turn caused `ReusableBlockEditPanel` to remount, which in turn caused the _Name_ field to be `select()`ed.

I fixed this by removing the `RECEIVE_REUSABLE_BLOCKS` effect handler and instead making the reducer handle `RECEIVE_REUSABLE_BLOCKS` directly.

**2) Race condition between deleting a reusable block and fetching reusable blocks**

After clicking _Remove from Reusable Blocks_ on a new post with a reusable block in it, both `deleteReusableBlock()` and `fetchReusableBlocks()` would be dispatched at the same time. This was because the cursor would be placed into a Paragraph block which then activates `blocksAutocompleter`. These two HTTP requests would race and, often, the response to `fetchReusableBlocks()` would come back before the block had been deleted, causing Gutenberg to mistakenly show the deleted block in the inserter. 

I fixed this by moving `fetchReusableBlocks()` from `blocksAutocompleter` and into `SETUP_EDITOR`.

**3) E2E test not able to click on a reusable block in the inserter**

Since the tests are now always starting from a new post, we now need to wait for `fetchReusableBlocks()` to finish before we can click on the reusable block in the inserter.

I fixed this by using `waitForSelector()`.

**Comment by noisysocks** [comment]
Hm, damn, still some failures on Travis CI. I'm not sure if they're related.

**Comment by gziolo** [comment]
@iseulde can you rebase with master and see if failures were unrelated to this PR?

**Comment by catehstn** [comment]
Moving this to 4.6, no rush to get it in today.

**Comment by gziolo** [comment]
@noisysocks and @iseulde - this one needs to be refreshed. Do you plan to get back to this PR? I'm marking it as `Stale` to make triaging and reviewing PR easier.

**Comment by iseulde** [comment]
I don't. Looked at this at a meetup quick.

**Comment by noisysocks** [comment]
I don't have the bandwidth to do a lot here, but I can rebase it and maybe that will fix the test failures I was getting in https://github.com/WordPress/gutenberg/pull/10267#issuecomment-437758120.

**Pull request closed without merging**
