### PR TITLE
Use user-specified defaults for image block, not constants

### PR DESCRIPTION
**Pull request by feastdesignco**
## Description

Asking you guys to use the user-specified defaults already in the database instead of constants

## How has this been tested?

Not tested at all - above my head.

## Types of changes

You guys broke the features we rely on to set the default align + image size

This is unbreaking it.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Nope.

### CODE REVIEW

**Comment by talldan** [comment]
> This is unbreaking it.

@feastdesignco I can't really tell from the code how this is 'unbreaking' it, the change doesn't seem to do anything. Not sure if this pull request is still in progress, but either way, more detail in the description would help.

One final thing, there are lots of contributors who aren't 'guys', would be great if you could be a little more inclusive.

**Comment by feastdesignco** [comment]
No, it doesn't actually unbreak it.

As noted, this sort of change is above my level. I'm unable to fix it. But the issue was raised 2 years ago and remains unresolved.

Wordpress has options (image_default align, image_default_size) for users to override the default layout + default image size. The image block in the block editor ignores these.

The word 'guys' has no meaning related to gender, it's a figure of speech. If you self-identify as a tree I'm all for it, if you're able to help. Please keep the discussion on topic.

**Comment by karmatosed** [comment]
@feastdesignco, I totally understand you are looking to get a fix here, however, I would encourage you to think that @talldan was coming from a place of help here. The word guys does have a gendered meaning, whether you meant it like that or not, it's a hard habit to break through and I absolutely see you didn't mean it to exclude.

Let's move on together to a solution, considering the person beyond the avatar as we interact. How can we progress this forward collaboratively? Does #8663 need a decision?

**Comment by ErnestPH** [comment]
Any updates on this? How can we make full as the default image size instead of large? :) Thanks!

**Comment by Mamaduka** [comment]
Fixed via #29966.

**Pull request closed without merging**
