### PR TITLE
Post Title Block: Add style attributes

### LINKED ISSUE #19491: Add styling attributes to Site Title, Site Description, and Post Title Blocks
**Is your feature request related to a problem? Please describe.**
In our user testing of full site editing on WordPress.com, users regularly expected to be able to style their site title and description in the same way they can with headings and paragraphs. They primarily expect to be able to change the **font size**, **text color**, and **alignment** of these blocks, and express frustration when they do not see the same options.

**Describe the solution you'd like**
There are three core blocks, Site Title, Site Description, and Post Title that currently do not support font size, text color, and alignment options. I suggest adding these so that when these blocks are ready to be used in production, we can avoid further user frustration.

* Site Title has been merged and can be updated: https://github.com/WordPress/gutenberg/pull/17207
* Site Description hasn't yet been merged: https://github.com/WordPress/gutenberg/pull/23788
* Post Title as a block is very rudimentary, but it does exist: https://github.com/WordPress/gutenberg/pull/18461

/cc @obenland

### PR DESCRIPTION
**Pull request by Copons**
Fixes #19491 
(last PR needed)

## Description

- Add support for text and background colors, line height, font size to the Post Title block.
- Fix an issue causing the `HeadingLevelDropdown` to move to the top of the page when changing the heading level.

#### More on the `HeadingLevelDropdown` issue

To reproduce, try changing the heading level of a Post Title block from its toolbar.
You'll notice that the block toolbar will disappear, while the heading dropdown remains visible but moved to the top of the screen; since the block is still technically selected, to make the toolbar show up again, you'll need to deselect and reselect it.

I'm not 100% sure about it, but I think it's caused by the re-render upon changing the light block wrapper tag.
I've simply tried copying the approach from [another block](https://github.com/WordPress/gutenberg/blob/131b21eade6ec3e722c8e2d5b4d6770f573440a0/packages/block-library/src/group/edit.js#L19), and it fixed the issue straight away.

## Types of changes
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — APPROVED** [review]
This works well for me!

That is a very odd issue with the toolbar on the level setting change.  I thought I had an idea but tested a bit and proved myself wrong 🤣  ... 🤷‍♀️ .  It works well with the way we are now defining the `BlockWrapper` though!  🎉

**Comment by strarsis** [comment]
So this feature is planned to be released with a near future Gutenberg release?
(Same/related? https://github.com/WordPress/gutenberg/pull/23788)

**Comment by noahtallen** [comment]
@strarsis Hey! So, these blocks are part of the full site editing project. With a Gutenberg plugin, you can currently go into the "experiments" settings (under Gutenberg in the wp-admin sidebar). There, you can enable the full site editing (FSE) experiment. With that enabled, you can use these blocks, and also try out the early stages of the site editor. These blocks exist in the current Gutenberg plugin with the FSE experiment enabled.

These will remain experimental blocks for the near future, though, since everything related to full site editing is under active development. (And things can change a lot.) You should not yet rely on them for production use cases

**Comment by strarsis** [comment]
@noahtallen: Ah, please also notice that posts can have their own headings, too. And for posts having formattable headings (like a subheading) would be great, too.

**Comment by noahtallen** [comment]
This issue is a helpful overview of FSE blocks: https://github.com/WordPress/gutenberg/issues/22724

**Pull request merged**
