### PR TITLE
Interactivity API: Prevent non-object state from being added

### PR DESCRIPTION
**Pull request by sirreal**
## What?

Prevent interactivity store state from being set to non-object.

## Why?

`store.state` is expected to be an object. [There is code that prevents state from being updated if it is not an object](https://github.com/WordPress/gutenberg/blob/afc08a1ca41dfb4c2e9fd6effd3d9878c1955381/packages/interactivity/src/store.ts#L23), but it's possible to set the state to a non-object initially, which breaks subsequent updates.

See https://github.com/WordPress/wordpress-develop/pull/6261#discussion_r1524471565 and [this Core Trac comment](https://core.trac.wordpress.org/ticket/60761#comment:6) for related details.

## How?

`isObject` checks are applied when updating state, apply isObject to initial state as well, default to `{}` if non-object state was provided.

## Testing Instructions

This PR includes e2e tests. [You can see a failing run before the fix was pushed here.](https://github.com/WordPress/gutenberg/actions/runs/8284886462/job/22671424040?pr=59886)

### CODE REVIEW

**Comment by sirreal** [comment]
The status check is confused here, it says there's a failing label job, but that seems stake or wrong.

I do need to add a changelog before this lands.

**Review by DAreRodz — APPROVED** [review]
Fix looks good to me, 😄 although I would move the test to `store.spec.ts` and `packages/e2e-tests/plugins/interactive-blocks/store/`, as those are the test files we currently have for the `store()` function.

Could you update that before merging?

**Comment by sirreal** [comment]
I've updated the tests as requested and verified they fail if I revert the fix:

```
    Locator: getByTestId('state-0')
    Expected string: "right"
    Received string: "wrong"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for getByTestId('state-0')
      -   …
      -   locator resolved to <div data-testid="state-0" data-wp-text="state.0">wrong</div>
      -   unexpected value "wrong"


      28 |      } ) => {
      29 |              const element = page.getByTestId( 'state-0' );
    > 30 |              await expect( element ).toHaveText( 'right' );
         |                                      ^
      31 |      } );
      32 | } );
      33 |
```

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-rc2-6.5 branch to get it included in the next release: 6421202b180

**Pull request merged**
