### PR TITLE
Add reusable block icon.

### PR DESCRIPTION
**Pull request by jasmussen**
This adds a reusable block icon to the menu. 

It also:

- Moves icons to the right. You can still show shortcut and icon.
- Harmonizes and simplifies menu item paddings, aligns it to the 12px grid.
- Updates the check icon to match the WordPress design libraries.

Props to @MichaelArestad for some mockups that inspired these changes.

Before:

Screenshot 2020-06-29 at 10 49 27

After:

Screenshot 2020-08-28 at 11 28 54

Screenshot 2020-08-28 at 11 25 30

In no places (that I could find) do we currently show BOTH a shortcut, and an icon. But since it's theoretically possible this will be necessary (props @shaunandrews), it is accommodated. The following is a fake example (reusable blocks don't have a shortcut):

Screenshot 2020-08-28 at 11 17 10

### CODE REVIEW

**Comment by jasmussen** [comment]
Adding "in progress" because the icon really needs to be on the right to look balanced, and that needs more work.

**Comment by jasmussen** [comment]
I moved the icon to the right, in the spot of the shortcut, as outlined in #18667. Screenshots:

Screenshot 2020-07-09 at 12 31 10

This also affects other menu items:

Screenshot 2020-07-09 at 12 31 00

Screenshot 2020-07-09 at 12 31 17

I think it adds a nice bit of consistency and balance. I'd like for more work to be done to optimize the code, there's a lot of duplication and it can align to the grid. But it's somewhat deep surgery so probably best done separately.

**Comment by shaunandrews** [comment]
Does this mean a menu item could have an icon or a shortcut, but not both?

**Comment by jasmussen** [comment]
> Does this mean a menu item could have an icon or a shortcut, but not both?

Yes and no. You can still add an icon, as shown in the tools menu, but it's a different code syntax for it, not perhaps as such something you should only do if you know what you're doing. Which goes okay with the idea that we should be using less icons overall in menus.

> What happens when I select Code Editor in the more menu; Does the shortcut get replaced by a check mark?

Serendipitiously, this is already the case in the core project, because the shortcut for the active editor view is intentionally hidden. But yes, now that's also technically the case.

**Comment by jasmussen** [comment]
Refreshed this one, and revisited. It now:

- Allows both icon and shortcut
- Harmonizes and simplifies menu item paddings, aligns it to the 12px grid.
- Updates the check icon to match the WordPress design libraries.

Props to @MichaelArestad for some mockups that inspired these changes.

I have updated the screenshots in the PR description to match these changes.

**Comment by MichaelArestad** [comment]
@jasmussen This looks and feels solid. I did a bit of clicking around and for the most part, everything worked very well.

I see one spot in the site editor where the icon alignment is a little weird. I suspect it is because the component configuration might be custom or something specific to the editor CSS: 

image

**Comment by jasmussen** [comment]
Ugh we need a new icon for that :D great call, let me take a look at that one. Thank you Michael!

**Comment by shaunandrews** [comment]
image

There's something _off_ about the alignment of the icon when compared to the shortcuts and the focus ring. Otherwise, I dig it.

**Comment by jasmussen** [comment]
I optically spaced the icon a bit more:

Screenshot 2020-09-02 at 09 59 13

The idea is that all icons have a little bit of clearance:

Screenshot 2020-09-02 at 10 00 53

It's now 2px compared to 4 before. What do you think?

**Comment by jasmussen** [comment]
Regarding the Export icon in the site editor, I found this icon:

Screenshot 2020-09-02 at 10 06 09

That's upload. I took inspiration from that to create a new "Download":

Screenshot 2020-09-02 at 10 06 06

So here's before:

Screenshot 2020-09-02 at 10 09 58

Here's after:

Screenshot 2020-09-02 at 10 10 07

I added the new icon to the Figma WordPress Design Library also.

**Review by shaunandrews — APPROVED** [review]

**Comment by mtias** [comment]
Thanks @jasmussen ! We might end up removing the reusable block one now that it exists as a tab and is not present elsewhere, but the improvement in the positioning and the other icons is great.

**Pull request merged**
