### PR TITLE
Fix regression with appender.

### PR DESCRIPTION
**Pull request by jasmussen**
This PR is a hotfix for a small regression introduced in https://github.com/WordPress/gutenberg/pull/9735. Basically the empty "Write your story" placeholder had no top margin, and jumped when clicked. This PR fixes that.

Before:

before

After:

after

Additionally it fixes an issue I think might have regressed with editor styles. The appender _height_ used to be the same as a paragraph height (28px, 56px with margins). But this regressed. This PR adds an explicit height to the appender input field to fix this, noting that a Paragraph is actually a paragraph, whereas the appender is an input field. 

height

☝️ in that GIF I type in "Write your story", then delete the block, then use undo/redo to ensure they look identical

### CODE REVIEW

**Review by kjellr — COMMENTED** [review]
✅ Looks good to me. No more jumping cursor. 👍

**Comment by jasmussen** [comment]
Awesome, thanks so much. Can you approve the PR?

**Review by kjellr — APPROVED** [review]
👏

**Comment by websevendev** [comment]
Hello,

is this working as intended?

Previously a nested block had a bunch of extra margin above and below (which I could collapse but I don't mind them since it makes the editor experience easier), but was positioned somewhat realistically compared to the front end. Now, how ever, it has less margin on top and more on bottom which is a completely inaccurate representation:


Although that's not a big deal, since the block appenders tend to also leave a lot of trailing space that's not actually there on the front end.

But also take a look at this use case:

I've got these nested column blocks in a grid block, `.editor-block-list__layout` is set to `display: flex; flex-direction: row;` and the first column is now offset by the reduction of `first-child` margin:



I guess I can manually set a fixed margin, but honestly I think they should be consistent out of the box. I thought `.editor-block-list__layout` is designed to allow rearranging blocks the way you need them with flex or even CSS grid, so currently it feels a bit inconsistent that the first child margins are altered.

Thanks!

**Comment by jasmussen** [comment]
Thanks for the report, @websevendev that looks like a regression. Not of this PR, but a related one. I will take a look.

**Pull request merged**
