### PR TITLE
Icons: Update search icon to be optically more balanced.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

The search icon was slightly right-heavy:

Screenshot 2023-03-29 at 09 55 16

Screenshot 2023-03-29 at 09 55 20

This PR nudges it a pixel, making it a bit more optically balanced:
Screenshot 2023-03-29 at 09 13 46

Screenshot 2023-03-29 at 09 13 42

## Testing Instructions

Test that the appears looks as intended in storybook.

### CODE REVIEW

**Comment by jameskoster** [comment]
Good idea. 

It may not matter, but one observation is that this change would make the Search icon quite a bit smaller relative to others in the set. The new iteration is ~13 x 13 while others trend towards 16 x 16. This makes it look quite small in a lineup:

Screenshot 2023-03-29 at 10 22 06

Again it might not matter, but the the balance may be improved if the handle was tilted exactly 45º instead of the current:

Screenshot 2023-03-29 at 10 24 58

Feel free to discard, but I tried a different version, slightly larger, with a 45º handle:

Screenshot 2023-03-29 at 10 26 45

**Comment by jasmussen** [comment]
Oh that's a good one, let me do a quick pass.

**Comment by jasmussen** [comment]
How's this?

Screenshot 2023-03-29 at 14 20 05

Screenshot 2023-03-29 at 14 21 41

?

**Comment by jameskoster** [comment]
That looks good tot me!

**Review by jameskoster — APPROVED** [review]

**Comment by richtabor** [comment]
Good stuff!

**Pull request merged**
