### PR TITLE
Global Styles: Remove more menu item

### LINKED ISSUE #51861: Consider removing "Settings" and "Styles" from the Site Editor More Menu
Was resolving https://github.com/WordPress/gutenberg/issues/51859 when I noticed an inconsistency between the post and site editors. There is not a Plugins > Settings control within the post editor menu; so do we need one in the Site Editor? If not, do we need the "Styles" control as well? 

Both the Styles and Settings sidebars can be invoked from the editor header; seems a bit redundant to have these controls in both places. 

CleanShot 2023-06-23 at 12 21 50

### PR DESCRIPTION
**Pull request by youknowriad**
closes #51861 

## What?

Just a tiny PR to remove the "styles" menu item from the "plugins" section in the site editor's more menu. Global styles are not plugins so they shouldn't show up there.

## Testing Instructions

Open the site editor
Notice there's not "styles" in the more menu top right.
You can still access global styles using the regular header button.

### CODE REVIEW

**Comment by jasmussen** [comment]
It's worth being clear that the purpose of that section is for you to be able to open any of the additional sidebars beyond the block inspector, on mobile. Without a menu item there, you cannot. I allude to that [here](https://github.com/WordPress/gutenberg/issues/51861#issuecomment-1609029750). If we move global styles into site view (#65619), this PR will become moot. But it's still relevant to think about, especially for inline comments, or third party plugins. How can you access those from mobile? While especially Settings may be unique, because that menu item is always pinned to the top toolbar, inline comments, and global styles (for now), are not.

**Comment by youknowriad** [comment]
Ok, if you think we should keep it, we can close this PR and close the issue as well :)

**Comment by jasmussen** [comment]
Worth hearing @richtabor, in case I missed some nuance!

**Comment by richtabor** [comment]
I'm curious if this menu item is necessary going forward, now that https://github.com/WordPress/gutenberg/pull/65619 has landed.

**Comment by youknowriad** [comment]
I think it's tied to the discussion here #66719 

If the decision is to remove the global styles sidebar, I think it becomes clear that the button is not necessary anymore. We might want to keep a button in the header as a "hint" that things moved.

My preference would be to remove the sidebar because I think its value in the template/page editor is small (only for advanced users) compared to the confusion that it creates. But let's see how the discussion unfolds there.

**Pull request closed without merging**
