### PR TITLE
Add initial quick inserter

### PR DESCRIPTION
**Pull request by youknowriad**
related #21080 

This PR starts implementing the quick inserter. It's early implementation and the task has proven to be harder than expected for two reasons:

 - The inserter is a complex UI with a lot of logic and interactions
 - The quick inserter specs are still early and not very precise yet, I'm thinking iterating on this PR will help us clear things out.

I'm still trying to figure out what would be the MVP to ship this.

Capture d’écran 2020-06-01 à 12 17 48 PM

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @youknowriad! 👋

Took it for a test on Firefox. I found a placement bug when the inserter is near the top of the document:

Screen Shot 2020-06-02 at 17 59 12

The inserter looked good when invoked from a lower place:

Screen Shot 2020-06-02 at 18 04 03

Did a quick test with only keyboard and I did not find any issues.

**Comment by youknowriad** [comment]
Thanks @enriquesanchez yes,  it seems the Popover component doesn't refresh its size when the size of the content changes (start searching), I'll try to debug it.

**Comment by jasmussen** [comment]
Amazing work, Riad. I'm happy to get an initial version of this in, but I think we need to try and move a little closer to [the mockups](https://github.com/WordPress/gutenberg/issues/21080#issuecomment-629346711). 

The initial state:

Screenshot 2020-06-03 at 10 06 18

The mockup:

Screenshot 2020-06-03 at 10 06 49

- If we can default to opening up and right from the plus, this is a good start. I'm aware that there are situations where it will open in other directions, that's fine — but we should have a good default.
- We need to unblock [the popover PR](https://github.com/WordPress/gutenberg/pull/22516#discussion_r430912873) so we avoid using the block UI for this popover.

Search:

Screenshot 2020-06-03 at 10 09 58

I don't know how possible this is, can we be smarter about the height of the inserter? It was cropped by the viewport and I had to scroll to see the whole thing:

Screenshot 2020-06-03 at 10 10 05

I imagine that this is very technically challenging, so as an alternative, we should look into a max-height. As it is, this is very tall compared to the mockup:

Screenshot 2020-06-03 at 10 12 14

Some things that should help make it smaller:

- Gray separator between blocks and patterns, that way we can also remove the headings for each group.
- Scale down the patterns a great deal. Should fit 2 side by side.
- Adjust the spacing of blocks. I'm happy to help here if need be.

The browse all — I can't recall where that discussion landed. Is it complicated to build?

**Comment by youknowriad** [comment]
pushed some updates here per the comments. The Popover size and direction is still not adapting properly to the content height change. I explored some solutions but it's a bit challenging. Maybe @ellatrix could land a hand here when you find some time.

**Comment by mtias** [comment]
Have been giving this a run through over the past few days. The things that have stand out from the designs:

- Initial state just with search didn't feel great. It seemed to over-optimize for search. The default state of showing 6 most used blocks seems better.
- Patterns make sense to be included in searches but not on the empty / default state.
- Continuing the browsing experience in the main sidebar inserter is going to be important.
- I'm quite liking the smaller patterns in the inserter, I think an inserter that only opens with patterns is going to be super useful for certain contexts (sections, template parts, etc). I could even see it included in block placeholders.

**Comment by mtias** [comment]
This is looking good. Once we address these I think we can merge:

- Patterns cannot be inserted for me (get an error).
- The "X" (from wordpress/icons) should replace the search icon.
- The "browse all" should drop the border radius and needs a better focus style (cc @jasmussen).
- Would it make sense to preserve the search term when switching to the main inserter?

It's also very frustrating to me that arrow keys closes the inserter.

**Comment by jasmussen** [comment]
> and needs a better focus style (cc @jasmussen)

Am aware, and haven't forgotten the tabs. I'm still looking for a good design, but in the meantime I pushed a change that at least fixes things:

focus

**Comment by youknowriad** [comment]
> Patterns cannot be inserted for me (get an error).
> The "X" (from wordpress/icons) should replace the search icon.

These two items are implemented/fixed

> Would it make sense to preserve the search term when switching to the main inserter?

Potentially, but maybe we can start without it first to avoid the added complexity (communication between block-editor and external module) and add later?

I'd appreciate another round of feedback here. thanks.

**Comment by enriquesanchez** [comment]
Tested this one again on Safari + VoiceOver.

Keyboard navigation feels solid and predictable. I ran into some issues however when attempting to do a search.

### 1. The inserter's position shifted as soon as I started typing.

From

Screen Shot 2020-06-19 at 17 37 51


To

Screen Shot 2020-06-19 at 17 37 59


### 2. On the main inserter, after entering a search string I hear the number of results found, but I couldn't hear that in the quick inserter.

It'll be great to be able to also hear the number of returned results here.

### 3. The 'close' button for a search entry is labeled after the search string, and there's no indication that this is a reset or cancel button

Screen Shot 2020-06-19 at 17 31 16

In the above example, I only hear 'quo, button'. This problem is also present in the main inserter. I think it'll be best if the action could be communicated better. Something like 'Reset search'?

### 4. Focus is unpredictable after canceling/resetting a search

If I click the 'quo' button above, I then see this:

Screen Shot 2020-06-19 at 17 31 48

I'm not sure where my focus landed, it looks like somewhere in between the search field and the first block because if I do `shift + tab` I move my focus back to the search field, and with `tab` I move to the first block.

I think the expected behavior here would be to have the focus back in the search field because I'm canceling a search query after all.

### 5. The 'Browse all' button could include a bit more info for users of assistive technology

Screen Shot 2020-06-19 at 17 55 41

After I click it, I immediately hear that my focus is now on a search field, but I have no clue or context that I'm on the main inserter now. I think that the 'Browse all' button could be more descriptive of what will happen by including more context. Maybe something like ´aria-label="Browse all. This will open the main inserter panel in the editor toolbar."´?

Screen Shot 2020-06-19 at 17 59 55

Or something along those lines...

**Comment by youknowriad** [comment]
Thanks for the feedback @enriquesanchez I think I fixed most of it.

For the first point, it can't be fixed entirely because the Popover will switch position when there's no enough space to show everything in the default position but I changed the default position to "bottom" that way it favors the space under the button over the space on top of it.

**Review by mtias — APPROVED** [review]
This is looking in a good state for me. There are a few further tasks to do but we can split it into separate work.

**Comment by enriquesanchez** [comment]
@youknowriad Tested again and it's so much better, thank you for working on those improvements 🎉

I came across one little issue, and it's after typing a search query, such as "quo", I hear 2 results found, which is expected. If I delete the query, I then hear "79 results found". I assume the "79" comes from the total of blocks I have, but I'm wondering if we should announce the number of items when the search field has been reset?

**Comment by jasmussen** [comment]
Not a blocker for merging this PR, but the X close icon used to clear a search should be the small one, `closeSmall` that was recently merged in.

**Comment by mtias** [comment]
Thanks for all the iterations here 🎈

**Comment by StevenDufresne** [comment]
@youknowriad @mtias Where does the block directory logic fit in?... on the eve of the block directory launch 😄.

**Comment by mtias** [comment]
It's similar to the autocomplete inserter, which is the one that more clearly should not integrate the block directory, in my opinion. The quick inserter is in-between — perhaps we should integrate it down the road but I'd prefer to continue to refine the experience first in the main inserter.

**Comment by jasmussen** [comment]
I'm seeing an error in the beta widgets screen where searching doesn't work, giving this error:

`search-items.js:118 Uncaught TypeError: Cannot read property 'filter' of undefined`

**Comment by youknowriad** [comment]
@jasmussen would you mind ticketing that, I can look later.

**Comment by jasmussen** [comment]
Done: #23649

**Pull request merged**
