### PR TITLE
Date package: Fix timezone issues

### LINKED ISSUE #27500: Date: Tests are false-positive, assumes it is ran in GMT timezone and en_US locale
**Describe the bug**
1. Date package assumes the environment is in `GMT` all the time. This causes false positives in the CI (since the tests are passing). In real use-case, the Date package might be returning wrong results. Which might cause several other bugs.

2. Date package tests assume your locale is `en_US`. Runs on CI fine, but my locale is set to `en_GB` so one particular test is failing for me. (`should support "T" to obtain the timezone abbreviation for the given date`)

**To reproduce**
1. Run `npm run test-unit packages/date/src/test/index.js` (Run tests in your local timezone, if your local timezone is GMT, use the TZ environment variable to change it to something else)
2. See 3-4 tests are failing
3.  Run `TZ='GMT' npm run test-unit packages/date/src/test/index.js` (Run tests in GMT, should be the same as running in the CI)
4. Tests should pass or see one test failing (depending on your locale): `should support "T" to obtain the timezone abbreviation for the given date`

You can fake your timezone and locale to mimic the CI environment: `TZ='GMT' LANG="en_US.UTF-8"  npm run test-unit packages/date/src/test/index.js`. Running the unit test like this will make sure your tests are passing. (Though it's obviously false-positive)

### PR DESCRIPTION
**Pull request by david-szabo97**
Fixes #27500 https://github.com/WordPress/gutenberg/issues/27251

## Description
Removed `getDate` and `isInTheFuture` in favor of `isSiteDateInTheFuture`, `parseSiteData`, `siteDateToLocalDate` and `localDateToSiteDate`. These functions are supposed to be more descriptive to avoid confusion and bugs.

## How has this been tested?
You can follow testing steps in the two mentioned issues: #27500 #27251

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ockham** [comment]
:wave: @david-szabo97 I think that @vcanales is working on a fix in #27398, ICMYI :blush:

**Comment by vcanales** [comment]
Hi, thanks for taking on this. I believe our approaches to fix the assumptions that were made before are similar. We also tackled some of the issues of usage I was facing regarding the scheduled post selector. I'm not sure how to proceed though; tests are mostly passing on https://github.com/WordPress/gutenberg/pull/27398, and there’s a few eyes on it already. Let me know what you think!

**Comment by david-szabo97** [comment]
@vcanales I'm happy to review and help to debug yours! Thank you for your work!

I'm a bit unhappy with the current public API of the `date` package. I think getting rid of `getDate` and replacing it with a few "timezone" converter functions is more descriptive and easier to use. Please take a look at my implementation and see if it makes sense to you. Although I couldn't perfect the implementation and tests are still failing, I think a new public API would make sense.

**Comment by vcanales** [comment]
> I'm a bit unhappy with the current public API of the `date` package. I think getting rid of `getDate` and replacing it with a few "timezone" converter functions is more descriptive and easier to use.

I think this makes sense, although removing those functions would also make it a breaking change; I even found that I broke some things while trying to not alter the API (which is also kind of why the current implementation is not the cleanest). The current API is used by some plugin makers for instance, so a transition period might be necessary.   

I do agree that publishing time zone utilities would be preferable, and would also be more in tune of the functional approach of `date-fns`. 

Perhaps we could consider making 2 steps out of this: getting the current breakage out of the way, and then rethink `@wordpress/date` in a way in which it's less influenced by the previous `momentjs`-based implementation, applying what you've done here.

**Comment by gziolo** [comment]
> The current API is used by some plugin makers for instance, so a transition period might be necessary.

There shouldn't be such thing like a transition period in terms of API exposed in the WordPress Core. The expectation is to keep old method signatures even when deprecated forever.

**Comment by david-szabo97** [comment]
We can keep the old functions and deprecate them. Meanwhile, we can introduce new functions and use them in Gutenberg. This can be done in one or two steps.

**Comment by ockham** [comment]
Per convo with @david-szabo97, we'll focus on getting #27398 ready for now in order to avoid removing functions.

**Pull request closed without merging**
