### PR TITLE
Fonts Library: change upload directory to wp-content/fonts

### LINKED ISSUE #53965: Font Library: use /wp-content/fonts instead of /wp-content/uploads/fonts to store font assets.
## What
Currently, we are storing the Font Library assets in `/wp-content/uploads/fonts`.
@mtias suggested we should change it back to ` /wp-content/fonts`

## Why?
- We should keep uploads for things you insert into posts.
- If we end up adding folders to media library and someone adds a "fonts" folder for some reason.

### PR DESCRIPTION
**Pull request by jffng**
**What**
This PR closes https://github.com/WordPress/gutenberg/issues/53965.

**How**
We can't use `wp_handle_upload` because this function only works to move files into the `uploads` directory (or subdirectory). This PR reworks the implementation to `rename` the temporary file to its new location in the `wp-content/fonts` directory.

**To test**
- Ensure the related `wpFontFamily` tests pass 
- Check out https://github.com/WordPress/gutenberg/pull/53884 and verify you can install / uninstall a font successfully.

### CODE REVIEW

**Review by matiasbenedetto — COMMENTED** [review]
> @matiasbenedetto what is the best way to test this, or is the tests passing sufficient?

Yep, it should be enough because we are testing if the files exist in the right location.

https://github.com/WordPress/gutenberg/blob/22d24f352df72b7507939f3eb70d7b372547c5c3/phpunit/tests/fonts/font-library/wpFontFamily/install.php#L96-L99

Please update the tests to look for the files in the right place. I think we would need to update here, for example: https://github.com/WordPress/gutenberg/blob/22d24f352df72b7507939f3eb70d7b372547c5c3/phpunit/tests/fonts/font-library/wpFontFamily/base.php#L28-L34

There could be an enhancement opportunity there :point_up: by simplifying and avoiding the need to define the `$upload_dir` in the set_up method.

**Review by matiasbenedetto — COMMENTED** [review]
After the tests work as expected, making a manual test round would be nice, too. For that, you can checkout the frontend branch: https://github.com/WordPress/gutenberg/pull/53884 build, and after that, checkout this branch and use the UI to upload a few fonts.

**Comment by jffng** [comment]
There are [two related tests erroring or failing](https://github.com/WordPress/gutenberg/actions/runs/6050219304/job/16419641379?pr=54076#step:15:64), which are passing for me locally. Any idea why these would fail in the CI but not locally?

**Review by matiasbenedetto — COMMENTED** [review]
> There are [two related tests erroring or failing](https://github.com/WordPress/gutenberg/actions/runs/6050219304/job/16419641379?pr=54076#step:15:64), which are passing for me locally. Any idea why these would fail in the CI but not locally?

I suspect that the destination folder is not being created on the CI machine. I'll take a look at that.


Apart from that, @jffng, could you please add your findings about why we could not use `wp_handle_upload()` function to move the uploaded files?

**Comment by jffng** [comment]
> could you please add your findings about why we could not use wp_handle_upload() function to move the uploaded files?

The [current implementation uses the core function `wp_handle_upload`](https://github.com/WordPress/gutenberg/blob/trunk/lib/experimental/fonts/font-library/class-wp-font-family.php#L227) to move the font files to the correct folder.

If we want to store the fonts in `wp-content/fonts`, we can't use this function because it is designed to move files within `wp-content/uploads` only: https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-admin/includes/file.php#L979-L987.

As far as I can tell, there is no option to override this: https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-admin/includes/file.php#L776-L789

**Review by matiasbenedetto — CHANGES_REQUESTED** [review]
> As far as I can tell, there is no option to override this: https://github.com/WordPress/wordpress-develop/blob/6.3/src/wp-admin/includes/file.php#L776-L789

This function is for that:


https://github.com/WordPress/gutenberg/blob/2c0aebde6419008a0e6d93de77cdab4c2a09914f/lib/experimental/fonts/font-library/class-wp-font-library.php#L112-L115

It is called by the `install()` method before writing the files and it's removed just after to avoid changing the normal work of the rest of the codebase:

https://github.com/WordPress/gutenberg/blob/2c0aebde6419008a0e6d93de77cdab4c2a09914f/lib/experimental/fonts/font-library/class-wp-font-family.php#L544-L547 


I just tried something like this, changing these `WP_Font_Library` methods and it seems to work as expected :

```php
public static function get_fonts_dir() {
    return path_join( WP_CONTENT_DIR, 'fonts' );
}
```
	
```php
public static function set_upload_dir( $defaults ) {
	$defaults['basedir'] = WP_CONTENT_DIR;
	$defaults['baseurl'] = content_url();
	$defaults['path']    = self::get_fonts_dir();
	$defaults['url']     = $defaults['baseurl'].'/fonts';
	$defaults['subdir']  = 'fonts';

	return $defaults;
}
```

I think it would be nice to continue using wp_handle_upload() due to their fine tunning around security and server edge cases.

**Comment by matiasbenedetto** [comment]
Another way to test manually is running this in your console. It's a POST request to install one font family.
You need to update these parameters to your local dev env:
- location (your test URL)
- header Cookie
- header X-WP-Noce

```
curl --location 'http://localhost/wp1/wp-json/wp/v2/fonts?' \
--header 'X-WP-Nonce: f8a6ddb873' \
--header 'Cookie: wordpress_logged_in_2deaa0cca6489f796dc77dfbf8093554=admin%7C1694439469%7C1y868xyGGOHTwsT0m6fWjX4ZHmWDURInUlyUtylHvDg%7Cd76eab503a23d6965189b349984e7ef47fd0e24d2047550e7f642ef7596b0ede' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'fontFamilies=[{"name":"Aguafina Script","fontFamily":"Aguafina Script, cursive","slug":"wp-font-lib-aguafina-script","category":"handwriting","fontFace":[{"downloadFromUrl":"http://fonts.gstatic.com/s/aguafinascript/v17/If2QXTv_ZzSxGIO30LemWEOmt1bHqs4pgicOrg.ttf","fontWeight":"400","fontStyle":"normal","fontFamily":"Aguafina Script"}]}]'


```

**Comment by jffng** [comment]
@matiasbenedetto good suggestion, thank you! 

Closing this in favor of #54122.

**Pull request closed without merging**
