### PR TITLE
Editor: Fix term selector component exports

### LINKED ISSUE #41661: PostTaxonomiesHierarchicalTermSelector in filter create infinite loop
### Description

In packages/editor/src/components/post-taxonomies/README.md, 
the last example says to use wp.editor.PostTaxonomiesHierarchicalTermSelector in the editor.PostTaxonomyType

While testing, I got infinite loop. I think the problem is that PostTaxonomiesHierarchicalTermSelector was exported as a wrapped component with withFilters('PostTaxonomyType') and seems to call the hook in a infinite loop.

It doesn't happen with OriginalComponent because this one is not wrapped.

### Step-by-step reproduction instructions

1. Use last example of post-taxonomies README
2. Open a page with gutenberg 12.6+ and the custom taxonomy
3. experience infinite loop...

### Screenshots, screen recording, code snippet

_No response_

### Environment info

wordpress 5.9 with gutenberg 12.6 or 13.4

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #41661.

PR directly exports `FlatTermSelector` and `HierarchicalTermSelector` components without applying the filter.

## Why?
The developers have to use the same filter to change components used for rendering the taxonomy, causing an infinite loop.

## Testing Instructions
1. Register taxonomy for a post (snippet 1).
2. Open a post.
3. Copy the last example from readme and run it via the DevTools console (snippet 2).
4. Confirm that the "Tracks" taxonomy panel is updated to use the `HierarchicalTermSelector` component.
5. Confirm that there's no infinite loop - the browser doesn't freeze or crash.

```php
add_action( 'init', static function() {
	$args = array(
		'public'            => true,
		'hierarchical'      => false,
		'label'             => 'Tracks',
		'show_ui'           => true,
		'show_in_rest'      => true,
		'show_admin_column' => true,
		'query_var'         => true,
		'rewrite'           => array( 'slug' => 'genre' ),
	);

	register_taxonomy( 'track', array( 'post' ), $args );
} );
```

```js
const el = wp.element.createElement;
const HierarchicalTermSelector = wp.editor.PostTaxonomiesHierarchicalTermSelector;

function customizeTrackSelector( OriginalComponent ) {
	return function ( props ) {
		if ( props.slug === 'track' ) {
			return el( HierarchicalTermSelector, props );
		} else {
			return el( OriginalComponent, props );
		}
	};
}

wp.hooks.addFilter(
	'editor.PostTaxonomyType',
	'my-plugin/set-hierarchical-term-selector',
	customizeTrackSelector
);
```

### CODE REVIEW

**Comment by mcsf** [comment]
This effectively removes the ability for third parties to filter `FlatTermSelector` and `HierarchicalTermSelector`. It restricts the filterable versions indirectly to `PostTaxonomies` and `MaybeTagsPanel`, which are the only first-party consumers of those components. I am not sure if that's intentional, but it seems like a break in the API that we should avoid.

**Comment by Mamaduka** [comment]
Thanks for the feedback, @mcsf.

I think the original intention for exporting these components was UI reusability - #38419.

**Comment by Mamaduka** [comment]
@mcsf, one other option I can think of is to update the README example, but that won't prevent an infinite loop when used with the `editor.PostTaxonomyType` filter.

**Comment by mcsf** [comment]
> I think the original intention for exporting these components was UI reusability - #38419.

Thanks, that's useful context. I spent some time digging up the trail of issues leading up to where we are.

* I suspect it was a mistake to introduce to open up FlatTermSelector and HierarchicalTermSelector _under the same hook name_ in #8225, as now we have confusing semantics between those two components and their main consumer PostTaxonomies, and it's hard to fix this without breaking third-party uses.

* The other thing is that the example use case that was presented as justification for #38419 (per #17476) did not actually require exposing FlatTermSelector and HierarchicalTermSelector:

```js
// DO NOT USE THIS
function customizeTaxonomySelector( OriginalComponent ) {
    return function( props ) {
        if ( 'my_taxonomy' !== props.slug ) {
        	return <OriginalComponent { ...props } />;
        }

        return <HierarchicalTermSelector { ...props } />;
    };
}
wp.hooks.addFilter( 'editor.PostTaxonomyType', 'my-custom-plugin', customizeTaxonomySelector );
```

The snippet above is instructing the editor to always use the hierarchical selector when handling `my_taxonomy` terms. Well, that's precisely what PostTaxonomies does:

https://github.com/WordPress/gutenberg/blob/739f26f6814ba1a32576af5ae5f4c87206d55ff4/packages/editor/src/components/post-taxonomies/index.js#L36-L38

Custom taxonomies should make sure they [register themselves as hierarchical](https://github.com/WordPress/wordpress-develop/blob/a649d581284fcb4b144630f2095471f54d8549d3/src/wp-includes/taxonomy.php#L451).

* * *

> one other option I can think of is to update the README example, but that won't prevent an infinite loop when used with the editor.PostTaxonomyType filter.

Honestly, I think that's the most _correct_ and safest thing to do. I mean, the example needs to be changed anyway, per my previous point about `taxonomy.hierarchical`. Along with a change of example, the docs should come with a warning to not call FlatTermSelector or HierarchicalTermSelector inside that hook, lest the editor lock up.

Then, if someone _really_ wants to be able to hook into `editor.PostTaxonomyType` to redirect to either FlatTermSelector or HierarchicalTermSelector, we can consider exporting undecorated counterparts to these components, either as:

```js
export FlatTermSelector as UnfilteredFlatTermSelector;
export default withFilters( 'editor.PostTaxonomyType' )( FlatTermSelector );
```

or

```js
const FilteredFlatTermSelector = withFilters( 'editor.PostTaxonomyType' )( FlatTermSelector );
FilteredFlatTermSelector.Unfiltered = FlatTermSelector;
export default FilteredFlatTermSelector;
```

* * *

To reiterate, I think this PR should pivot to fixing the documentation and accompanying example. On the other hand, the idea of exporting undecorated components is something we should be careful about, and only consider in a new PR/issue if there is pressure to do so. wdyt, @Mamaduka?

**Comment by Mamaduka** [comment]
@mcsf, the documentation update makes sense to me. So I will try to come up with something simple and update the PR.

**Comment by ocean90** [comment]
> Custom taxonomies should make sure they [register themselves as hierarchical](https://github.com/WordPress/wordpress-develop/blob/a649d581284fcb4b144630f2095471f54d8549d3/src/wp-includes/taxonomy.php#L451).

As mentioned in #17476, some custom taxonomies need to be non-hierarchical but should still be selected by checkboxes. For example for pre-defined list of items where an author can't add more items.

Looking at a project, which is still using a copy of `flat-term-selector.js`, I found the comment "_Remove filter `editor.PostTaxonomyType` to prevent recursion._" in the changes section. So this was kind of known but missed while working on #38419.

I think the proposed change in this PR makes sense since it appears that the current exports are causing breakage and back-compat shouldn't be a real issue here.

**Comment by mcsf** [comment]
Thanks for the context, @ocean90. 

@Mamaduka, in light of that, what do you prefer to do?

**Comment by Mamaduka** [comment]
@mcsf, I would prefer to go with my initial fix.

**Review by ocean90 — APPROVED** [review]
Looks good to me, fix seems to be an oversight from #38419. Not sure if we need some tests here so this doesn't happen again?

**Comment by Mamaduka** [comment]
> Not sure if we need some tests here so this doesn't happen again?

I'm not sure about the tests.

Let's merge this fix, and happy to a follow-up if I can think of a good way to test the exports.

**Pull request merged**
