### PR TITLE
ToolsPanel: Display optional items when values are updated externally

### LINKED ISSUE #47368: Not all styles panels are visually updated on copy/paste block styles
### Description

Not all pasted styles are "visually" applied in the inspector panel when copying and pasting block styles. The styles are technically applied to the block, but tools that were not already applied to a styles panel, do not get updated. If you deselect the block and then reselect, all styles panels are correctly updated. 

### Step-by-step reproduction instructions

1. Add a heading block and add many custom styles to it, including padding and margin. 
2. Add another unstyled heading block. 
3. Copy the styles for the first heading to the unstyles heading block.
4. See that the applied padding and margin styles do not show up in the Dimensions panel even though they are applied to the block. If you look closely, you will also see that only Typography tools that were already applied to the unstyled heading block get updated. 
5. Click off of the block and then reselect. See that the Dimensions panel is displaying as expected. 

### Screenshots, screen recording, code snippet

copy-past-styles-error

### Environment info

- WordPress 6.1.1
- Gutenberg trunk
- TT3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/47368

Related:
- https://github.com/WordPress/gutenberg/pull/47673
- https://github.com/WordPress/gutenberg/pull/47590

## What?

Potentially fixes design tools not showing in the inspector when pasting block styles.

_Note: If an optional control has been toggled on, or customized previously, then block styles are pasted, that optional control will continue to be displayed. It will reflect the current value though. Reselect the block, and that control will be hidden, as per normal._

_Does this behaviour actually help highlight to the user what's changed?_

## Why?

When pasting styles, their values should be reflected in the design tools without having to de-select and re-select the block.

## How?

Allows optional ToolsPanelItems to override the ToolsPanel's inner menu item state when the optional item previously wasn't toggled on for display. 

## Testing Instructions

1. `npm run test:unit packages/components/src/tools-panel/test`
2. `npm run storybook:dev` - Ensure no behavioural differences between trunk and this branch. Particularly with the conditional item examples.
3. Open the editor, add two heading blocks
4. Select the first heading block and tweak as many design tool values as you like. Make sure to toggle on at least one optional control e.g. Dimensions > padding.
5. Via the block toolbar's overflow menu, choose "Copy styles"
6. Select the second heading block, and choose "Paste styles" under the overflow menu
7. You should see all the copied style values and controls within the block inspector sidebar
8. Repeat steps 3-7, however, this time before pasting styles, tweak an optional design tool that you did not set on the first block (e.g. Dimensions > margin).
9. Note that the optional control that wasn't within the copied styles is reset but still shown.

## Screenshots or screencast 

https://user-images.githubusercontent.com/60436221/216564519-79d4b5b2-0eed-4a2c-aa4b-70a6a8ce8218.mp4

### CODE REVIEW

**Comment by richtabor** [comment]
Confirmed that this works as expected. I see the controls populate with proper values when copying styles from one block to another. ✅

**Comment by glendaviesnz** [comment]
@aaronrobertshaw this tested well for me with a single block selection, but not multiselection, so taking a look to see if I can work out why that is - but might be worth merging as is if that is not an easy fix as a single block is probably the most likely use case.

**Review by glendaviesnz — APPROVED** [review]
LGTM:

✅ Unit tests pass
✅ Storybook examples work the same as on trunk
✅ Pasting styles optional tools panel items causes the tools panel to rerender with the new controls in place with the correct settings
✅  Additional optional controls not in the pasted group are reset but still render

As already noted it doesn't work for multi-selected blocks but we should go ahead and merge this as the main use case will be single blocks and we can handle multi-selects separately later.

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.

**Pull request merged**
