### PR TITLE
Site Editor: Remove dead code

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Part of #36597.

Removes unused code left-overs after recent Template list refactoring.

I mostly checked for unimported components; this shouldn't affect anything.

## How has this been tested?
All checks are passing.

* Site Editor should load without errors.
* Navigating between the Template list and Editor shouldn't trigger any errors.

## Types of changes
Code Quality

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by mkaz** [comment]
Is this related to https://github.com/WordPress/gutenberg/issues/37571 ?

**Comment by Mamaduka** [comment]
@mkaz, this is a general clean-up of the `edit-site` package.

Re #37571 - we can probably ignore most of the "Can't perform a React state update on an unmounted component" warnings. React 18 is removing them  - https://github.com/reactwg/react-18/discussions/82.

**Comment by ockham** [comment]
Should we also get rid of these consts? I found them while looking for occurrences of the filenames of the files that this PR deletes. They look unused to me (but I don't know a lot more context):

https://github.com/WordPress/gutenberg/blob/2e5af3fc1f2082eabe0f113e728b18d7d3b4703f/packages/edit-site/src/components/navigation-sidebar/navigation-panel/constants.js#L71-L73

We might also wanna audit adjacent constants.

**Review by ockham — APPROVED** [review]
Seems to be working well, and I couldn't find any of theses files used anywhere in the codebase.

I'd suggest removing a few constants as part of this PR though: https://github.com/WordPress/gutenberg/pull/37581#issuecomment-999737762

**Comment by Mamaduka** [comment]
Thanks for the review, @ockham. Removed constants as via 0b0767e35379108379db9bcdc32358f3f930a685 and I think I got all of them 😄

**Comment by ntsekouras** [comment]
`-1000 lines` 🥇 Nice!!

**Review by ockham — APPROVED** [review]
Thanks @Mamaduka, LGTM!

I've noticed that some e2e tests were failing. Re-running in the hope they were unrelated 🤞

**Pull request merged**
