### PR TITLE
Make the custom CSS validation error message accessible

### LINKED ISSUE #56437: Make the custom CSS validation message accessible
### Description

Splitting this out from https://github.com/WordPress/gutenberg/issues/56082#issuecomment-1808295146

In the global styles > advanced panel, users can enter custom CSS. When the CSS is invalid, a vaiidation message is provided by the means of a red icon with a tooltip. Screenshot:

Screenshot 2023-11-22 at 13 57 50

This information is not accessible. Quoting from https://github.com/WordPress/gutenberg/issues/56082#issuecomment-1808295146

- No audible feedback is provided.
- The icon is just an SVG icon wrapper in a focusable `div` element.
- The focusable `div` element has no labeling and no ARIA role, it's just a silent tab stop.
- It should not be a focusable div in the first place.

I disagree with the design feedback provided in https://github.com/WordPress/gutenberg/pull/47132. Instead of adopting single-use 'ad hoc' design inspired to other tools (Codepen in this case), we should just reuste the editor components. They aim to be accessible and reusable, whilc 'ad hoc' designs defeat the purpose of usability, accessibility and maintenance. I'd argue ad-hoc implementations also defeat the purpose of reusable components in the first place. 

The error message should simply use a standard notice / warning, which has been designed to provide information in an accessible way. 

Also, whjn fixing this, some E2E test should be added to make sure the message works as intended, to avoir future regressions like https://github.com/WordPress/gutenberg/issues/56082

### Step-by-step reproduction instructions

- Go to the Site editor > Styles > More > Additional CSS
- Add this in the Additional CSS textarea: `body {background: red;}`
- Save.
- Edit the textarea again and remove the closing bracket `}`.
- Move focus away from the textarea.
- Observe a red icon appears at the bottom right of the textarea.
- Observe there is no audible feedback for screen reader users.
- Observe the red icon provides a some meaningful information only when hovered or focused.
- Observe the red icon is within a focusale `<div>` element that is not labelledd and has no ARIA role.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/56437

This PR changes the custom CSS validation error message to make it accessible. On top of that, I'd like to add a few considerations:
- Using ad-hoc components that are only used once in a single place defeats the entire purpose of building reusable components.
- Instead, using the existing components makes sure that there is design consistency and that the components are accessible, as they are supposed to be designed, built, and tested for accessibility.
- I'd recommend to not introduce ad-hoc, single-use, components in the future. If there is a proven need for a new UI components that covers a vlaid use case and can be reused across the editor, I'd suggest to design a new component to be included in the `components` package. Only by doing that the new component would be guaranteed to be consistent, reusable, tested, and accessible.

## What?

The custom CSS validation error message is not accessible. It is also a unique UI in the editor, there's no other usage of a red icon with tooltip and I'd argue it's am unexpected pattern for users.

## Why?

Any user-input validation message must be accessible.

## How?

Replaces the current implementation based on a red icon plus tooltip with the standard Notice component.
- The Notice is set to error instead of warning, because this is an error.
- The Notice will produce by. default an accessible audible message with `assertive` politeness level.
- I'm placing the Notice at the top of the textarea because it's more visible in that spot.

## Testing Instructions

- Follow the reproduction instructions from the issue https://github.com/WordPress/gutenberg/issues/56437
- Observe that instead of a red icon at the bottom right of the textarea, an error Notice is shown before the textarea.

## Screenshots or screencast 

Before and after:

before and after

### CODE REVIEW

**Review by alexstine — APPROVED** [review]
@afercia Thanks for the PR.

This whole area of the editor brought out a huge sigh from me, I have no idea how this landed in such an inaccessible state. Styles tab needs a lot of work.

This gets us a little closer. 👍

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by afercia** [comment]
Thanks everyone for your feedback and review.
Noting that some design feedback was requested on December 18, which is more than one month and a half ago, but no feedback was provided. I think one month and a half is more than enough to provide feedback. The lack of feedback after such a reasonable wait shouldn't be a blocker. Merging.

**Comment by youknowriad** [comment]
Should we backport this to WordPress 6.5?

**Comment by afercia** [comment]
@youknowriad I wasn't planning to ask beckporting it but if that's possible yes, it would be welcomed.

**Comment by youknowriad** [comment]
I think it's a good fix to have and we're still early in the beta cycle, let's add it.

**Comment by youknowriad** [comment]
Would love a fact check from designers @jasmussen @jameskoster @SaxonF

**Comment by jameskoster** [comment]
Now that the textarea is full-height I tend to agree it was easy to miss the icon in the bottom right. Especially on larger screens. That could have been helped by setting a red border on the textarea too, but I don't suppose that would address the a11y concerns. 

Given this is a low-traffic area, and hopefully errors are few and far between, a notice seems a reasonable interim despite the rough appearance. I'm not sure it should be dismissible though?

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the more/backports-for-beta3 branch to get it included in the next release: 79dffd9133c

**Pull request merged**
