### PR TITLE
Update grid icon.

### PR DESCRIPTION
**Pull request by jasmussen**
The site editor save dialog uses a grid icon that's a dashicon:

Screenshot 2020-09-14 at 08 16 23

This PR updates it:

Screenshot 2020-09-14 at 08 35 20

However, addon question: should we be using the "layout" icon instead?

Screenshot 2020-09-14 at 08 17 57

Or better yet: why don't we remove the icon entirely? I'm not sure it adds anything at all:

Screenshot 2020-09-14 at 08 37 00

### CODE REVIEW

**Comment by aristath** [comment]
> Or better yet: why don't we remove the icon entirely? I'm not sure it adds anything at all:

Removing it would make more sense to me... I don't see a point to it :thinking:

**Comment by jasmussen** [comment]
> Removing it would make more sense to me... I don't see a point to it 🤔

👍 👍 — but the dashicon still remains — I can update the PR to both update the gridicon, _and_ remove it from usage in that save changes dialog, what do you think?

**Comment by aristath** [comment]
Doing a search I found that the `grid` icon is only used in these files:
https://github.com/WordPress/gutenberg/blob/b506d04df3f4bb8a5d09f6b195419cff98c6bdf3/packages/editor/src/components/entities-saved-states/entity-type-list.js#L11
https://github.com/WordPress/gutenberg/blob/b506d04df3f4bb8a5d09f6b195419cff98c6bdf3/packages/block-library/src/rss/edit.js#L16
https://github.com/WordPress/gutenberg/blob/b506d04df3f4bb8a5d09f6b195419cff98c6bdf3/packages/block-library/src/latest-posts/edit.js#L33

I'd say it's safe to change it :+1: 

In the dashicons page, there's an icon for grid (the updated one): https://developer.wordpress.org/resource/dashicons/#grid-view
and the old one is labeled as `screenoptions`: https://developer.wordpress.org/resource/dashicons/#screenoptions

**Comment by jasmussen** [comment]
Removed the icon:

Screenshot 2020-09-14 at 11 20 23

I could use a sanity check on https://github.com/WordPress/gutenberg/pull/25285/commits/59473b78ec2c38d6062d3fc238d9b43ee083ca1b, otherwise this one seems ready to go.

**Review by aristath — APPROVED** [review]
Tested and confirmed, works as expected.
Code looks good to merge :+1:

**Comment by jasmussen** [comment]
Thank you!

**Comment by MichaelArestad** [comment]
Love it!

**Pull request merged**
