### PR TITLE
Process: Add checklist item about API changes in a PR

### PR DESCRIPTION
**Pull request by akirk**
## Description

To avoid situations where data corruption can be a result of changing API (see #18616 which started storing escaped titles in the database), we need to better aware of such changes. Most API changes will be without side-effects but without awareness of potential breaking changes, those that do have side-effects might be recognized too late.

By flagging API changes, they can be reviewed in bulk before a release, and the correct measures can be taken, for examply by adding a Changelog entry.

## Types of changes
Adds a new checklist item to the PR template:

[ ] My code adds or changes API interaction.

## Checklist:
(none apply since this is not a code change)

## Proposal in change of process
We should create a new status label `Changes API` so that we can review API changes before releases. There should also be new labels `Requires Changelog Entry` and `Has Changelog Entry` which can be used in such a case but might be useful in further scenarios when we want to ensure that important changes are not forgotten in changelogs.

### CODE REVIEW

**Comment by youknowriad** [comment]
While I completely agree on the principle, experience had shown that these templates are not effective and shouldn't be considered as sufficient. This is to say that I'm ok with this addition but I don't expect it to have meaningful impact.

**Review by mkaz — APPROVED** [review]
I'll approve because it can't hurt adding an extra prompt for people to consider.
Though I'll echo @youknowriad comment that the checklist items are not too effective.

**Comment by gziolo** [comment]
In the ideal case,  a bot would apply labels snd comment with recommendations on how to include CHANGELOG chsnges or Dev Notes 😃

We can land it after rebase, but as Riad mentioned the more items on the list the more people ignore thrm 🙁

**Comment by Mamaduka** [comment]
The project now uses a simplified PR template with no checklist. See #39229.

I'm going to close this PR.

**Pull request closed without merging**
