### PR TITLE
Fix intermittent RichText e2e test failure

### PR DESCRIPTION
**Pull request by youknowriad**
It seems like there might a be a very small delay between the mouse moving and the block toolbar being shown causing a test failure.

This PR fixes the issue by waiting for the toolbar to show before proceeding.

### CODE REVIEW

**Review by diegohaz — APPROVED** [review]
I was looking into this right now! Thanks for solving it! 😊

**Comment by ellatrix** [comment]
Did this start happening very recently?

**Comment by youknowriad** [comment]
@ellatrix I only saw it today.

**Comment by diegohaz** [comment]
It seems that it started on #19242, specifically on this line: https://github.com/WordPress/gutenberg/blob/c919bce572840f3c87cb82a62b3357765b0d64e7/packages/components/src/slot-fill/bubbles-virtually/slot.js#L28

The old implementation was using `componentDidMount`, which is synchronous. Changing that to `useLayoutEffect` (the equivalent to cDM) also seems to fix this issue.

**Comment by youknowriad** [comment]
@diegohaz Seems like using `useLayoutEffect` would be a better fix as it's more generic.

**Comment by diegohaz** [comment]
We may lose some performance benefit. But, yeah! Using `useLayoutEffect` may prevent future issues if there is code expecting this to by sync.

**Comment by youknowriad** [comment]
I updated, let's see what travis says.

**Comment by youknowriad** [comment]
@diegohaz Looks like there's a JS unit test failure now, would you be able to help?

**Comment by diegohaz** [comment]
It seems that storyshots is trying to create portal now that it's sync. Storyshots uses react-test-renderer underneath, which doesn't support portals.

Mocking `ReactDOM.createPortal` fixes this, but I'll see if there's a better way to handle it. I think it's better to simply disable storyshots for SlotFIll, as it doesn't add much value.

**Comment by diegohaz** [comment]
Should be fixed now!

**Comment by youknowriad** [comment]
Thanks :) I'm questioning Storyshots more and more. I haven't seen any value so far.

**Pull request merged**
