### PR TITLE
Fix generating admin schemes styles if the selector is composed of mu…

### PR DESCRIPTION
**Pull request by youknowriad**
This fixes the style of the publish button when saving is in progress.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for working on this. I don't know if I'm doing something wrong, but I'm seeing no changes when publishing using the Midnight theme. It's stil blush when working.

Also noticed something weird with the excerpt box:

screen shot 2018-05-16 at 12 12 00

though that seems to be in master as well. Ack, I think I need to break for lunch so I'm not missing something obvious here.

**Comment by jasmussen** [comment]
Oh, the excerpt thing is fixed in your `update/button-component` branch, so let's not worry about that here.

**Review by gziolo — APPROVED** [review]
Code wise looks good, if @jasmussen is fine with design part then :shipit:

**Comment by youknowriad** [comment]
It looks like we had two different bugs having a similar effect on different admin schemes :)

It should be fixed now, I also cleared some duplicated styles.

**Comment by jasmussen** [comment]
Confirmed, the publish box is now candy colored. Nice work! 👍 👍

**Pull request merged**
