### PR TITLE
[Block Library]: Update the relationship of `No results` block  to `ancestor`

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
This PR just add a bit more flexibility to the insertion of `No results` inside a Query Loop block. Previously you could insert them through the inserter only if they were direct parents of Query Loop, but now they can be inserted in nested blocks(ex Group), as long as they have Query Loop as an ancestor. 

Similar with: https://github.com/WordPress/gutenberg/pull/67657 and https://github.com/WordPress/gutenberg/pull/58602

## Testing Instructions
1. Inside a Query Loop block add a `Group` and then insert through the inserter `No results` block.
2. The above block cannot be inserted through the inserter if it doesn't have a Query Loop ancestor.
3. No regressions are introduced and everything else should work as before.

### CODE REVIEW

**Comment by gziolo** [comment]
Was there any discussion about which blocks could benefit from using `ancestor` instead of `parent`? Comments block could also get similar updates wherever applicable:

Screenshot 2023-02-23 at 12 23 48

Actually, it's the only block that uses that API, but in a slightly different way than this PR explores.

It also made me wonder whether the Comments block doesn't use `ancestor` for the Comment Template block to avoid the risk of inserting the block into self.

**Comment by ntsekouras** [comment]
>Was there any discussion about which blocks could benefit from using ancestor instead of parent?

In various issues at some point, but not a separate issue. We also introduced a new Query Loop PR that wraps these blocks inside `Group` blocks. That was my main trigger for this PR right now. I think the main reason for some `comment` blocks to use this API, is because they cannot work outside of this context at all.

>It also made me wonder whether the Comments block doesn't use ancestor for the Comment Template block to avoid the risk of inserting the block into self.

That's a good point and is something we might not want for Post Template... Maybe @ockham or @c4rl0sbr4v0 could share some insights?

**Comment by webmandesign** [comment]
+1 This would really be great! It would most likely solve my issue #48296 when I want to use `core/query-pagination` (and also `core/comments-pagination`) as a Template Part or Pattern.

**Review by Mamaduka — APPROVED** [review]

**Comment by gziolo** [comment]
Yeah, good idea to move forward with this change 👍🏻

**Pull request merged**
