### PR TITLE
Consistency for Edit/Save button labels and styles

### LINKED ISSUE #6469: Consider to improve consistency of the button labels and styles
Please see below, a quick comparison between the post permalink buttons and the shared block button. Initially, the both display an "Edit" button with the same style:

screen shot 2018-04-27 at 18 20 10

Instead, when editing:
- the first button becomes "OK" and is styled like a default button
- the second button becomes "Save" and is styled like a primary button (I understand it's to differentiate it from the "Cancel" button)

screen shot 2018-04-27 at 18 20 22

A few considerations:
- what is the standard text for a save action in Gutenberg? "OK" or "Save"? Seems to me using always the same text would improve consistency and make things easier for users
- should the "OK" button be styled as a primary button?
- what is the standard for a save button, should it always be paired with a "Cancel" button? 

/Cc @karmatosed

### PR DESCRIPTION
**Pull request by Soean**
## Description
Fixes #6469
Old PR: #7593 (messed up after rebase)

# 1.
- Renames permalink-save button from `OK` to `Save`

Before:
bildschirmfoto 2018-06-27 um 23 22 11
After:
bildschirmfoto 2018-06-27 um 23 18 58

# 2.

- Removes the `Cancel` button from Shared Blocks title edit
- Removes primary button style from `Save` button
- Cancels edit, if user clicks outside.

Before:
bildschirmfoto 2018-06-27 um 23 22 45
After:
bildschirmfoto 2018-06-27 um 23 19 22

### CODE REVIEW

**Comment by Soean** [comment]
@noisysocks in the old PR: 
>But I'm worried that this change makes it easy for a user to lose their changes to a  shared block. Right now, if a user is editing their shared block, and then clicks away to e.g. copy some text, their changes remain on screen. With this patch, if a user clicks away, any changes are lost and there is no way to undo the action.

**Comment by SuperGeniusZeb** [comment]
Is <kbd><samp>Save</samp></kbd> really correct for the permalink editor? Is the permalink actually saved, or is it not saved until an auto or manual full post save happens? If it is not actually saved, then I think the button should be <kbd><samp>Done</samp></kbd>. Otherwise a user may think that they do not need to use the main <kbd><samp>Publish</samp></kbd> button in order to save their changes, and will be confused when they try to leave the page and their browser tells them that there are unsaved changes, or they may want to not save certain changes but do not realize that the permalink change is one of them.

**Review by karmatosed — APPROVED** [review]
We do have to be cautious to see if people are ok about just having 'save', however it is a pattern many applications use. Let's get this in and take from there observing.

**Comment by noisysocks** [comment]
losing-changes

I'm still very concerned about this making it easy for a user to accidentally lose their changes. I'd prefer that we keep the Cancel button. Any thoughts, @karmatosed?

**Comment by karmatosed** [comment]
> How about we simply keep the unsaved changes when the block is unselected?

This sounds reasonable to me.

**Comment by gziolo** [comment]
This PR needs to be rebased.

**Comment by Soean** [comment]
@gziolo I will work on my open pull request tomorrow

**Comment by gziolo** [comment]
Feel free to remove the label when it gets updated 💯

**Comment by jasmussen** [comment]
Sorry for missing this, but the discussion seems to be in good hands. I agree with all of you.

> Curious if @jasmussen has any ideas here—from memory, the Edit / Cancel / Save flow originally came from a conversation that we had last year 🙂

No discussions, and the idea of simply keeping the unsaved changes when clicking out also seems to jive with my gut. The alternative would be to create an "are you sure" dialog when de-selecting, which is intrusive.

**Review by gziolo — CHANGES_REQUESTED** [review]
I think e2e tests for reusable blocks are failing after this change was introduced. It feels like they need to be updated after `Cancel` button was removed. 

I will add this PR to 4.1 milestone.

**Comment by Soean** [comment]
Thanks for you feedback, I fixed the tests.

**Review by gziolo — APPROVED** [review]
It looks like all feedback was addressed, let's get it in for 4.0 since it's ready.

**Pull request merged**
