### PR TITLE
Docs: Update slug for block-based theme tutorial

### LINKED ISSUE #25707: "Block-based Themes (Experimental)" Documentation is missing from the handbook
This appears to be still present here on GitHub: 

https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/block-based-themes.md

But it no longer shows up in the handbook for some reason: 

Screen Shot 2020-09-29 at 11 55 00 AM

### PR DESCRIPTION
**Pull request by kjellr**
One attempt to fix #25707.

This PR updates the slug for the block-based themes tutorial doc from `block-based-themes` to `block-based-theme`. 

As @TimothyBJacobs [pointed out on slack](https://wordpress.slack.com/archives/C02QB2JS7/p1601909983319300), `block-based-themes` is the only slug that shows up twice [in the manifest](https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json). It's possible that the second one is cancelling the first one out when the docs get replicated over on https://developer.wordpress.org/block-editor/. 

I'm not sure how to see if this works before committing, so I'm open to suggestions there. 😄

### CODE REVIEW

**Comment by carolinan** [comment]
@kjellr can you refresh this? 😄

**Comment by kjellr** [comment]
@carolinan Thanks for the ping! I think this should all be up to date now.

**Review by JustinyAhin — APPROVED** [review]
Changes look good to me.

**Review by aristath — APPROVED** [review]

**Comment by carolinan** [comment]
It looks like it "sort of" worked -the page and child page is published again but I think it was meant to be under https://developer.wordpress.org/block-editor/developers/themes/ not
https://developer.wordpress.org/block-editor/tutorials/block-based-themes/

**Comment by carolinan** [comment]
I wonder if we should delete this, it does not feel relevant anymore, but I am not sure how to redirect it.
https://developer.wordpress.org/block-editor/tutorials/block-based-themes/block-based-themes-2-adding-blocks/

**Comment by JustinyAhin** [comment]
To clarify @carolinan, what you want is:

- Move this page https://developer.wordpress.org/block-editor/tutorials/block-based-themes under this one https://developer.wordpress.org/block-editor/developers/themes
- Hide this page https://developer.wordpress.org/block-editor/tutorials/block-based-themes/block-based-themes-2-adding-blocks from the documentation

**Comment by carolinan** [comment]
That is correct.

**Pull request merged**
