### PR TITLE
[RNMobile] Add shallow rendering tests for native version of Preformatted block

### PR DESCRIPTION
**Pull request by Tug**
## Description
This PR adds very simple tests (snapshot testing) for the native version of the Preformatted edit component. It also adds a very simple test for the save component (compatible both web and native)

## How has this been tested?
- Run `npm run test-unit:native -- packages/block-library/src/preformatted/test/edit.native.js`
- Run `npm run test-unit -- packages/block-library/src/preformatted/test/save.js`

## Types of changes
Using react-test-renderer instead of enzyme for react-native, limited to shallow rendering for now.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@Tug tests are failing in CI, are those related to your changes?

**Comment by Tug** [comment]
@SergioEstevao Looks unrelated at first sight (timeouts on e2e tests). WIll wait for tests to finish running on the last commit to confirm

**Review by SergioEstevao — APPROVED** [review]
This is looking good!

**Comment by gziolo** [comment]
@Tug do you plan to rebase and merge this PR? It was approved a few months back 😃

**Comment by Tug** [comment]
Thanks for the heads up @gziolo  👍
Letting the CI tests run, then I'll merge

**Comment by hypest** [comment]
> End-to-End Tests / Admin - 1 (pull_request) Failing after 17m — Admin - 1 

Failed job ^ will restart it now.

**Pull request merged**
