### PR TITLE
update react & react-dom & react-test-renderer to 16.9.0

### PR DESCRIPTION
**Pull request by senadir**
Updated some packages to the latest [React version](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html)

changes in React includes: 
- renaming deprecated lifecycle methods 
`componentWillMount` → `UNSAFE_componentWillMount`
`componentWillReceiveProps` → `UNSAFE_componentWillReceiveProps`
`componentWillUpdate` → `UNSAFE_componentWillUpdate`
- Async `act()` for Testing 
- Performance Measurements with `<React.Profiler>`
and some other stuff you can react in the changelog above

### CODE REVIEW

**Comment by senadir** [comment]
had to delete the node_modules folder because it was causing some cache problems with a core package from another PR, that's why the pacakge-lock is updated to this extend

**Comment by gziolo** [comment]
> had to delete the node_modules folder because it was causing some cache problems with a core package from another PR, that's why the pacakge-lock is updated to this extend

I don't think this is the expected number of changes for the lock file. Can you try doing it again with the original lock file? It should be no more than dozens of lines updated. Did you follow: https://github.com/WordPress/gutenberg/tree/master/packages#production-dependencies?

**Comment by senadir** [comment]
@gziolo I will try again, the depencedy in question was stylelint-plugin, a package I introduced in another PR, it shouldn't even exist in master or the branch I created, yet npm kept saying he didn't find it, removing node_modules fixed the issue but caused this new lock file

**Comment by senadir** [comment]
@gziolo seems it worked, I should have kept the lock file & deleted the modules folder, not both

**Comment by gziolo** [comment]
I nearly forgot about `react-native` and that we need to wait until the new version is released which works with `react` 16.9.x.

@koke and @hypest, do you follow progress on the next version of RN?

**Comment by koke** [comment]
It looks like React Native only upgrades the React dependency on major versions, there's a tracking issue for the next minor one ([0.60.5](https://github.com/react-native-community/releases/issues/130)), but I don't know of a timeline for 0.61 yet.

**Review by gziolo — COMMENTED** [review]
Great work @senadir. I tested and it all looks good. I rebased to master to ensure it still passes with the latest changes in the `master` branch.

Can we include a note in the changelog on `@wordpress/element` before we proceed?

Similar to:
https://github.com/WordPress/gutenberg/blob/master/packages/scripts/CHANGELOG.md#new-features-1

It's rather internal change as we don't introduce new features.

**Comment by gziolo** [comment]
It looks like React Native 0.61.0 is still not there. However, we'd like to move forward with the changes so we could properly test Gutenberg with React 16.9.0 in the upcoming release cycle of WordPress 5.3. Related RN issue: https://github.com/react-native-community/releases/issues/140.

**Review by gziolo — APPROVED** [review]
I added CHANGELOG entry. Let's move forward with this PR.

**Pull request merged**
