### PR TITLE
Fix Block Rename UI perf regression

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes performance regression with selecting blocks identified in https://github.com/WordPress/gutenberg/pull/54426#issuecomment-1755733955.

## Why?

Performance is good.

## How?

Ensures that block renaming UI is only rendered for blocks which are seletected. Failure to do so leads to expensive slots being rendered for all blocks.

Perf tests caught this because it renders 1000 blocks 👏 👏 👏 

## Testing Instructions

- Verify that you can still rename all blocks via block options menu `Rename` (also in list view via same option).
- Verify that performance test output for `focus` `minFocus` and `maxFocus` are all ~100ms (as per [commit prior to the one which caused the regression](https://github.com/WordPress/gutenberg/actions/runs/6467142579/job/17556606187))

Also you can run the performance tests locally and compare the output on _this branch_ vs `trunk`. The command is:

```
npm run test:performance -- -g "Selecting blocks"
```

You should notice that the `focus` metric goes down significantly between `trunk` (regression) and this PR (proposed fix).

### CODE REVIEW

**Comment by getdave** [comment]
Waiting on Perf test results...

**Comment by scruffian** [comment]
```
npm run test:performance -- -g "Selecting blocks" 

> gutenberg@16.8.0-rc.2 test:performance
> wp-scripts test-playwright --config test/performance/playwright.config.ts -g Selecting blocks


Running 2 tests using 1 worker

  ✓  1 [chromium] › post-editor.spec.js:208:7 › Post Editor Performance › Selecting blocks › Set up the test post (5.2s)
  ✓  2 [chromium] › post-editor.spec.js:214:7 › Post Editor Performance › Selecting blocks › Run the test (16.9s)

  2 passed (22.7s)

post-editor

┌──────────┬────────────┐
│ (index)  │   value    │
├──────────┼────────────┤
│  focus   │ '36.49 ms' │
│ minFocus │ '34.04 ms' │
│ maxFocus │ '38.62 ms' │
└──────────┴────────────┘
```

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by getdave** [comment]
@scruffian can you compare the output you shared with that you would get from running the same tests against `trunk` locally?

**Comment by youknowriad** [comment]
Makes sense and the perf test confirms it.

**Comment by scruffian** [comment]
On trunk: 

```
┌──────────┬────────────┐
│ (index)  │   value    │
├──────────┼────────────┤
│  focus   │ '89.28 ms' │
│ minFocus │ '84.7 ms'  │
│ maxFocus │ '94.46 ms' │
└──────────┴────────────┘
```

**Comment by getdave** [comment]
We need to keep an eye on https://www.codevitals.run/project/gutenberg to see if the `Block Select` metric improves in PR's commit (`bd3ea8771a09e6e86f6d662fe0242089d81c7873`).

**Comment by getdave** [comment]
I also created [this PR which proposes updating the docs on the `Block.Edit` filter ](https://github.com/WordPress/gutenberg/pull/55252)with some warnings about potential for performance regressions.

**Comment by getdave** [comment]
Screen Shot 2023-10-12 at 09 31 44

Circling back here to confirm this PR [fixed the perf regression](https://www.codevitals.run/project/gutenberg).

**Comment by jsnajdr** [comment]
@getdave Today I independently discovered this issue when profiling for #54819, and I think there should be an even better fix. For a large post with approx 1000 blocks, we are currently wrapping every block with the `withBlockRenameControl` HOC. It this PR the HOC was optimized to add only one Fill to the `BlockSettingsMenuControls` slot, not 1000 of them.

But what if we didn't use the `editor.BlockEdit` filter at all? Find some other filter which runs just once for the entire editor. After all, there is just one Block Settings Menu and just one extension slot. We need to extend it only once. Usages of `PluginBlockSettingsMenuItem` could be an inspiration.

Alternatively, the rename UI doesn't need to be a plugin. It could be hardcoded directly into the Block Settings Menu, like, for example, `BlockLockMenuItem` is.

**Comment by youknowriad** [comment]
> Alternatively, the rename UI doesn't need to be a plugin. It could be hardcoded directly into the Block Settings Menu, like, for example, BlockLockMenuItem is.

I think ultimately, we need to better architecture all the built-in hooks we have (style, anchor, classname, rename, layout...). Most (if not all) don't need to use hooks and can be adde to the corresponding components, but if we ever do so, let's make sure we add them in an organized way :)

**Comment by getdave** [comment]
> Alternatively, the rename UI doesn't need to be a plugin. It could be hardcoded directly into the Block Settings Menu, like, for example, `BlockLockMenuItem` is.

I think what you suggest above is the most pragmatic option for now. This could be actioned in tandem with the follow up in https://github.com/WordPress/gutenberg/issues/55194 to make metadata a default global attribute.

**Pull request merged**
