### PR TITLE
Storybook: Add DateTimePicker

### PR DESCRIPTION
**Pull request by marekhrabe**
## Description
Adds a simple story for the `DateTimePicker`. 

## How has this been tested?
In the storybook, `npm run storybook:dev`

## Screenshots
Screenshot 2020-05-01 at 12 50 15

## Types of changes
New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by earnjam — COMMENTED** [review]
There is overlap between this and #22043. 

As part of fixing a bug, that one adds the `DateTimePicker` to the storybook. But it also adds `TimePicker` and `DatePicker` as separate isolated components. Difference in this one is the use of state. Perhaps we can combine the two?

**Review by brentswisher — CHANGES_REQUESTED** [review]
This is looking great, thank you for your work! One very minor change, if you could move the const `is12Hour` to the `_default()` function, and then in `DateTimePickerWithState` accept and pass on props to `<DateTimePicker>`.  (If that doesn't make sense take a look at the checkbox-control story for an example of what I mean.)

To be clear, this will function the same as your code. The only reason for the change is it makes it more clear to end-users in storybook what is happening when viewing the code in the docs panel.  Otherwise, all they see is `<DateTimePickerWithState />`:  Components___DateTimePicker_-_Default_⋅_Storybook

**Comment by marekhrabe** [comment]
@brentswisher this makes sense. after my update:

Screenshot 2020-05-15 at 11 18 41

**Comment by gziolo** [comment]
I have just discovered that the same story was added in another PR:

https://github.com/WordPress/gutenberg/blob/29bb0e64441a4ea70e784c6b18afcc9522a70c63/packages/components/src/date-time/stories/index.js#L21-L36

Let's close this PR. @marekhrabe, it looks like you landed 😄

**Pull request closed without merging**
