### PR TITLE
Fix gallery to image transform and inconsistent types used in gallery block

### LINKED ISSUE #20041: Gallery Images Need to Be Resolved After Transforming into Image Blocks
I have been having a problem with needing to resolve images after transforming a gallery into blocks. I have three photography blogs and it is happening on all of them. 

I saw this post here that was closed about the problem. 

https://github.com/WordPress/gutenberg/issues/14231

The part that is missing is that the photos are imported as a gallery and as soon as you transform the gallery into individual blocks, by clicking the **Image button**, so you can tag the images individually then save and go back in it wants you to resolve all the images. 

Here a couple of photos. 

shot
shot2

So this is the process: 

1. You upload the images as a gallery
2. You transform the gallery images into blocks using the block transformation button (or you can't tag the images in the visual editor). 
3. Once you transform the images into blocks.  Save the post and exit the post back to the main post editor. 
4. Go back into the post and it will ask you to transform all of the images. 

It happens to us every time on 3 different blogs. We have created nearly 30 posts that it has happened on and nobody can figure out the problem from multiple help forums. 

Here is another post I did on Wordpress with no resolution.

https://wordpress.org/support/topic/breaking-image-gallery-into-blocks-creates-a-mess/

Please help!!

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #20041

Fixes gallery to image transforms that were broken because the gallery block inconsistently stores image ids sometimes as numbers, but other times as strings. They're set as numbers initially when a gallery is created, but then as strings when loading a post and an existing gallery block is parsed. 

The image block expects them to be numbers, so transforming an existing gallery block to images caused invalid image blocks.

This PR tidies up the inconsistencies:
- Set `type` on gallery block attributes so that types are enforced.
- Ensure `attributes.images[ index ].id` is always stored as a string by parsing the initial value.
- Ensure the `attributes.ids` array is always updated as numbers by explicitly parsing the values.
- Use `attributes.ids` when transforming galleries to images, as the attribute types are both numbers. 
- When looking up captions, always use the string value.
- Always pass a number to the `getMedia` selector. It seems like if you try `getMedia( 71 )` and `getMedia( '71' )` the cache lookup doesn't resolve both ids as the same, resulting in a new HTTP request being made. This might be something to fix in a separate PR—entities could either (a) accept strings or numbers, but consistently convert them to the same type or (b) throw an error if the wrong type is used.

## How has this been tested?

1. Add a gallery with some images
2. Save the post and reload
3. Transform the gallery to images.
4. Save and reload
5. Expect that none of the image blocks should be invalid.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

My feeling is this is non-breaking and doesn't require a block deprecation. Any existing galleries saved into posts will have their ids stored as strings in the data-id attribute. Every deprecation also stores ids this way. So setting the id `type` as string shouldn't cause an issue for existing blocks.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by pinarol** [comment]
hi @talldan 👋 @mkevins and I are actually working on [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) project so you might want to invite someone comfortable reviewing web side as well. 

Having said that, we definitely need to test this on mobile and see if it is breaking anything. @mkevins will help you if any change is needed on `*.native.js` files. My only request is not merging this before mobile tests are done. We'll check this shortly. Thanks!

**Comment by talldan** [comment]
Thanks @pinarol, some validation/testing that this still works on mobile would be greatly appreciated.

I've pinged a few extra people for review.

**Comment by mkevins** [comment]
Hi @talldan :wave:  for some reason I got a 404 on the linked issue. Anyway, thanks for addressing the types for ids. I have tested this on WordPress-Android (merged locally onto https://github.com/WordPress/gutenberg/pull/20043)  with the following flows, and I haven't observed any regressions :tada: :

- [x] Gallery block - Add caption to gallery images - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Choose from device (stay in editor) - Successful upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc005)
- [x] Gallery block - Choose from device (stay in editor) - Failed upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Choose from device (leave the editor) - Successful upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc007)
- [x] Gallery block - Choose from device (close and re-open the editor with ongoing uploads) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc008)
- [x] Gallery block - Take a photo - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)
- [x] Gallery block - Choose from the free photo library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

This looks good to me, and I appreciate the comments :+1: .

**Review by draganescu — APPROVED** [review]
The transforms all work and the code looks perfect!

**Comment by talldan** [comment]
Thanks for the reviews and testing.

@mkevins yep, for some reason the issue, #20041, disappeared, possibly deleted? I still have some email notifications about it, so that's how I know I'm not going crazy.

**Pull request merged**
