### PR TITLE
Fix shortcode not showing in the widgets screen

### LINKED ISSUE #27793: Shortcode block not working in Widgets screen
**Describe the bug**

When used in the Widgets screen, a shortcode block won't render the content but instead shows the shortcode text as a paragraph.

From [this forum topic](https://wordpress.org/support/topic/shortcode-needs-html/).

**To reproduce**
1. Go to Widgets screen.
2. Add a shortcode block, with a shortcode in it.
3. Save and view site.
4. Verify the shortcode text appears instead of expected content.

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

Fix #27793.

Add `do_shortcode()` to the widgets screen.

Also fixed flaky widgets e2e tests, as it turns out it's no longer expected to move focus to the newly added blocks.

## How has this been tested?

Added e2e test, or:
1. Go to the widgets screen
2. Add a shortcode block
3. Add a video shortcode like: `[video src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"]`
4. Save
5. Go to the site's frontend
6. Observe that the video is showing correctly on screen

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think it was an explicit decision to avoid supporting shortcakes in these new screens. Can't we remove the block in these screens instead?

**Comment by kevin940726** [comment]
I thought that I've read similar discussions somewhere, but couldn't remember where 🤔.

**Comment by youknowriad** [comment]
I think @azaozz might remember this but yeah it's an oldish which we'd have a hard time finding :)

**Comment by draganescu** [comment]
@youknowriad I don't remember either taking such a decision. People use shortcodes to edit their sidebars so removing the block would make this new screen less functional than the old one. Also, what would be the advantage of not supporting such a  block, as long as we edit the same old "sidebars"?

**Comment by youknowriad** [comment]
This decision was made a long time ago :)  and the reasoning is:

 - widgets screen is a new thing in wordpress
 - Shortcodes are soft deprecated.

=> Don't support shortcodes in new things like FSE or widget screen.

**Review by draganescu — APPROVED** [review]
Shortcodes are a functional element of the widget admin screen that we're trying to update here, so we should aim for feature partiy with the old screen. Fixing a bug with displaying them is therefore a good step in this direction.

On @youknowriad 's concern of trying to not bring along deprecated features into new things, it is a good perspective but it does not apply to this work here or to the navigation block editor as these editors aim to update old functionality, they're not new per se - as, say, the site editor is.

**Pull request merged**
