### PR TITLE
Gallery block: Crop images even when they're linked

### PR DESCRIPTION
**Pull request by code-flow**
Fix: Image cropping did not work when images were linked to the media file or the attachment page.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice work, good catch!

Did you test in IE11? It's been a while since I tested that hack, and it's not pretty. I'm wondering if it works with that sort of comma separation. I can test if you don't have access, let me know.

**Comment by code-flow** [comment]
Sadly it's not working in IE at all. This is because it only allows object-fit:cover on img-Elements. See [this comment as a reference](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13603873/#comment-0) (from caniuse.com).

**Comment by jasmussen** [comment]
@code-flow My apologies for the belated reply. I didn't have a virtual machine for Windows set up at the office, only at home, so I wasn't able to check until now (where I've set one up). 

And yes, I recall now and you're right. Neither Edge nor IE11 support Object Fit, which is why we use that IE hack to simply disable it and make sure images are at least vertically centered even if not actually cropped. This is something we can look at addressing separately to this ticket if someone wants to, but it shouldn't be a blocker for your PR. 

However it does change how your PR should look, it should probably look like this:

screen shot 2018-01-24 at 09 28 14

If you'd like to rebase and update to ☝️ I'll merge the PR for you. Or if you'd rather make a new PR, just CC me on it and I'll thumb up and merge.

Thank you again for your help!

**Comment by code-flow** [comment]
Sorry for my late response. I came across this again and finally made the right changes. Hope this helps ;)

**Comment by jasmussen** [comment]
Thank you for this! I'm going to merge 🎉

**Pull request merged**
