### PR TITLE
Try using virtualized list in Inserter

### PR DESCRIPTION
**Pull request by david-szabo97**
Related: https://github.com/WordPress/gutenberg/issues/26080

NOTE: This is just experimentation and looking forward to what everyone thinks about it. If it's something that we agree on then I'll refactor the code to make it production-ready! The design (padding) is a little bit off and some components don't really make sense anymore, those are something to do when this gets accepted.

## Description
Inserter is a long scrollable list of blocks. All the items in this list are rendered all the time which takes a significant time to mount (adds ~1300 DOM element). This exploration uses `react-virtualized` to turn the list into a virtualized list.

Virtualized list is a scrollable list that only renders the visible items. If you have 200 items in the list, but only 30 items are visible at the moment then only those will be mounted and rendered.

## Measurements 

My measurements are based on 4x CPU slowdown and 153 blocks in the `Inserter`. Measurement times are the time the `click` event on `Add block` (+ button in the top left corner) takes.

Times measured on `master` branch:

- 717ms
- 651ms
- 653ms
- 609ms
- 628ms

Times measured on this branch:

- 333ms
- 293ms
- 256ms
- 260ms
- 241ms
- 260ms
- 238ms

### Pros
- We only render the items that are visible which results in less DOM elements
- Inserter opens faster

### Cons
- If we are scrolling fast then it takes a little bit of time for the content to show up
- We need to make sure items' height is fixed. Block names can be long which means they get wrapped onto as many lines it needs to. We will need to fix this to 2 or 3 lines and hide the rest. This also results in some extra spacing between rows since we need to fix the height for each row.

## How has this been tested?
* Open block editor
* Click + button (add block) in the top left corner
* It should open faster

## Types of changes
Optimization

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think we avoid virtualization like that in general because it's only visual and doesn't work well for screen readers (things not announced properly...), I'm not sure there's a solution for this kind of issues. Maybe @enriquesanchez or others know here.

For the patterns instead of doing virtualization, we opted towards using lazy-rendering using the `useAsyncList` hook.

That said, I think the block types inserter is something we didn't try to optimize before, so I'd like to understand the performance issues first before thinking about the best solution for these performance issues. Do we have any ideas on what components are causing issues there? which ones rerender unnecessarily...

**Comment by youknowriad** [comment]
>  it shouldn't be a problem since (I guess) the screen reader doesn't need to know about the hidden items.

I think that's a wrong assumption since the screen readers have modes where it exposes the whole DOM structure and allow navigating... without necessarily rendering. That said, I'm also not an expert there.

**Comment by enriquesanchez** [comment]
I don't have any prior experience with react-virtualized, but I know that assistive technologies work best when we have a stable DOM that is not moving/changing constantly. 

If only a few blocks are mounted, how would a screen reader know how many are there in total?

We also use headings for category titles. These are useful for those using screen readers and other asissitve technologies to navigate and quickly jump to a section regardless of scroll position. How would virtualization affect this?

**Comment by david-szabo97** [comment]
Closing this since I don't see any option to make this accessible. I'll look into `useAsyncList`

**Pull request closed without merging**
