### PR TITLE
link fix: block editor Sidebar Tutorial

### LINKED ISSUE #33265: Wrong link in the docs
The Sidebar Plugin section in the Metaboxes page in the docs:
https://developer.wordpress.org/block-editor/how-to-guides/metabox/

links to a non-existent page:
https://developer.wordpress.org/block-editor/how-to-guides/sidebar-tutorial/plugin-sidebar-0.md/

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #33265
Hey @talldan! how does this look?
let me know if this needs any changes! thanks!

### CODE REVIEW

**Review by skorasaurus — CHANGES_REQUESTED** [review]
Thanks for the your effort but I think the link is still incorrect. The file is still within the /sidebar-tutorial/ folder as shown in https://github.com/WordPress/gutenberg/tree/trunk/docs/how-to-guides/sidebar-tutorial

I think the link should just need the / removed at the end to work. :)  e.g.

`[Sidebar Tutorial](/docs/how-to-guides/sidebar-tutorial/plugin-sidebar-0.md)`


The .md is necessary because the files are transferred from markdown to html and the link will automatically be updated when the documentation is updated.

**Comment by rbrishabh** [comment]
makes sense @skorasaurus! thanks for your review :)

**Review by skorasaurus — APPROVED** [review]
Looks good to me; thanks for your patience and then the prompt response :)

**Review by mkaz — APPROVED** [review]
Thanks for the fix :+1:

**Pull request merged**
