### PR TITLE
Add 'Hero and two columns" pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a block pattern for #20345.

Screen Shot 2020-03-24 at 18 29 27

### CODE REVIEW

**Comment by mtias** [comment]
Can we use a different gradient to the ABC! one?

**Comment by enriquesanchez** [comment]
@mtias changed to `blush-light-purple`:

Screen Shot 2020-03-30 at 16 25 23

**Comment by enriquesanchez** [comment]
Made some updates:

Screen Shot 2020-04-08 at 15 46 50

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. Let me know if you think it can be improved or if we should close this PR instead.

**Comment by mapk** [comment]
The one without the tan background works better here.

What if you drop the entire left column so that you have the large Cover block on top and then one right column with text below it?

**Comment by enriquesanchez** [comment]
>The one without the tan background works better here.

@mapk Oh, right. I'm using Twenty Twenty and that's the default background color. I'll switch to the Starter theme for this one as well.

>What if you drop the entire left column so that you have the large Cover block on top and then one right column with text below it?

Is this what you had in mind?

Screen Shot 2020-04-14 at 17 49 53

**Comment by mapk** [comment]
I'd add a bit more spacing between the button and paragraph above it. But afterwards, good to go.

**Review by mapk — APPROVED** [review]
LGTM :shipit:

**Comment by enriquesanchez** [comment]
You make a good point @carolinan. There are two reasons why I used a Paragraph block:

1. Because the Cover block starts with a Paragraph block by default.
2. Not knowing where and how this pattern will be placed in relation to other content, I wasn't sure if I should make assumptions about what heading level to use, for example. 

What do you think?

**Pull request merged**
