### PR TITLE
Add a Table of Contents block

### LINKED ISSUE #1760: Add Block: Table of Contents
Had to delete all issue directions, as it is not a bug.

I know there are 2 issuse about  block. But I would like to ask for additional feature, block, a bit different. Just to se what others say about it. Can dare to say I needed it often.

As it is now it is easy to echo in template Post pagination, from "nextpage".  

- It is just numbers in most cases.
- It is like a black hole, never know what to expect when clicking on number.
- Not user friendly at all. 

I would like to ask for one new block with actually 2 under-blocks. 
One for "nextpage" pagination, and other (optional) for Table of Content (TOC). Like plugins below make it:

https://wordpress.org/plugins/table-of-contents-plus/
https://wordpress.org/plugins/bainternet-simple-toc/

It is needed often for serious news portals. Following a story that spans under long time period. 
Can be used for any story, article, on smaller websites, when some update about news comes after long time.

I tried before all those plugins but decided to stay away from them. Usually one man developing, in free time. And any sligh change in WP URL routing code makes those plugins have groove problems with permalinks. Not to mention additional problem with cache plugins. You are after all huge base of coders who could maintain this Gutenberg block much better.

### PR DESCRIPTION
**Pull request by pento**
## Description

This is a first pass at creating a dynamically generated table of contents block. It still lacks... most things, and is at least partially a sandbox for me to play around with creating more complex blocks. 🙂

Fixes #1760.

### CODE REVIEW

**Comment by mtias** [comment]
Interesting approach. When I was going to tackle this one I thought it might be interesting to make it static—it'd update whenever you interact with the editor, and would save HTML directly. That would be regenerated whenever you edited headings in the editor.

**Comment by pento** [comment]
Yah, I thought about that - having to write duplicate code (one for the block render in JS, one for the frontend render in PHP) isn't ideal, but it means that any headers added by not-Gutenberg will be correctly rendered.

I tend to lean towards implementing this kind of logic in the server side, instead of requiring every editor that interacts with a WordPress site to implement it.

**Comment by pento** [comment]
In order to show the ToC in the block render inside Gutenberg, I believe I'm blocked on #2473.

**Comment by gziolo** [comment]
I think you are no longer blocked. It is possible to access every piece of the state through `data` module as described here: https://github.com/WordPress/gutenberg/tree/master/data.

**Comment by mcsf** [comment]
@pento, feel free to reopen this one. For now, with the branch stale, I'll close it as we're making sense of all open PRs. 🙇

**Pull request closed without merging**
