### PR TITLE
Framework: Upgrade to wp-prettier@2.x

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to attempt to upgrade to the 2.x major version of Prettier (still `wp-prettier` fork).

See changelog: https://prettier.io/blog/2020/03/21/2.0.0.html

~**Status:** It's considered in progress due to a few potential errors in the formatted output, and related need to wait for a new stable release of `wp-prettier`.~ **Edit:** Fixed, see https://github.com/WordPress/gutenberg/pull/22610#issuecomment-634552341.

**Status (2020-05-27):** Awaiting stable published release of `wp-prettier@2.0.5`.

Notable changes:

- [As noted in the release notes](https://prettier.io/blog/2020/03/21/2.0.0.html#always-add-a-space-after-the-function-keyword-3903httpsgithubcomprettierprettierpull3903-by-j-f1httpsgithubcomj-f1-josephfrazierhttpsgithubcomjosephfrazier-sosukesuzukihttpsgithubcomsosukesuzuki-thorn0httpsgithubcomthorn0-7516httpsgithubcomprettierprettierpull7516-by-bakkothttpsgithubcombakkot), the default behavior is changed to add a space after the `function` keyword. This contributes to a majority of the included modifications.
- ~There are a few changes which seem to be unexpected, where a space is omitted or put on the wrong side of a parenthesis.~ **Edit:** Fixed, see https://github.com/WordPress/gutenberg/pull/22610#issuecomment-634552341.

<details><summary>Click to expand outdated issues explanation</summary>
Examples:

https://github.com/WordPress/gutenberg/blob/2cc80de37432d0d377b670ae4ab9f6fd08f8df3b/packages/blocks/src/api/factory.js#L353

https://github.com/WordPress/gutenberg/blob/2cc80de37432d0d377b670ae4ab9f6fd08f8df3b/packages/block-editor/src/components/colors/use-colors.js#L220

https://github.com/WordPress/gutenberg/blob/2cc80de37432d0d377b670ae4ab9f6fd08f8df3b/packages/block-library/src/gallery/tiles.native.js#L59

https://github.com/WordPress/gutenberg/blob/2cc80de37432d0d377b670ae4ab9f6fd08f8df3b/packages/block-library/src/index.native.js#L125

I note the issue at the upstream https://github.com/Automattic/wp-prettier/issues/19, which is intended to be fixed by the https://github.com/Automattic/wp-prettier/pull/20 , currently only available in a beta release. It's not entirely clear if this addresses both of the issues seen in the examples above, where template strings are one problem, but also a problem in some parenthesis usage (cc @sirreal, @scinos, @griffbrad).
</details>

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Just thought I'd bring up an issue I've been having with the WP fork of Prettier that I'm hoping might get fixed in this update: when the second or third clause of a ternary expression includes a function call that takes up multiple lines, the closing parentheses is preceded by 2 spaces:

Example taken from #21063:
```js
return rootChildBlocks
	? filteredItems.filter( ( { name } ) =>
		rootChildBlocks?.includes( name )
	  )
	: [];
```

Maybe whatever issue is causing this behavior is related to the issues you're running into.

**Comment by sirreal** [comment]
`wp-prettier@2.0.4` version has known bugs. It should probably be deprecated, it really isn't suitable for usage.

Can we try `wp-prettier@next` (currently `wp-prettier@2.0.5-beta-2`) here?

**Comment by aduth** [comment]
> Just thought I'd bring up an issue I've been having with the WP fork of Prettier that I'm hoping might get fixed in this update: when the second or third clause of a ternary expression includes a function call that takes up multiple lines, the closing parentheses is preceded by 2 spaces:

Are you sure this is a bug, and that it's specific to `wp-prettier`?

[From what I can tell](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAJUQQwDCAFgJYA2AJgEKURgDWAzgDpRswD8uAZlXjpqASXgBbFgDoBlIQApci4LigBDcXFwBfXAEpcAXgB8HLlwJEyVOg2YtuU8lDCVM1OC0XrN+szFw-ThgkXABtAF0AbhAAGhAIAAcYcmgWZFA1VAIAdwAFLIR0lDVKHLUAT3T4gCNUNWYMAGVEhucAc2QYVEw4eNIYcUoAdQp4FlawOCai8hSANzmK5HAWapBnFjhUGDz69vE1ZD5SrfiAKxYAD1p6xpgmjTgAGWc4Y9O+kEurpo7KOAARUwRHeSBOlDOIFaqC2qBWNTUNTglDi0NQzhgw3I1BgpGQADYABzxRIELbDeqJFZkzzbebveIARxB8D2SWKIDULAAtFA4HAPNQ0egWeR0Hs1AcjuDPvEtuJyF0el8WP8gaywRCoTAkdjcfikAAmeLdNRUDrECDiQ4rTwAVjRmC2ABUkcVtV95r0RFAPLAmmAMckAIJ+powCoAj6QuDabRAA), it works this way in Prettier as well. And I might assume it's intentional, to try to "align" all lines of the ternary expression as indented by two spaces (aligning to `? ` or `: ` from the first line of each branch).

**Comment by aduth** [comment]
> Can we try `wp-prettier@next` (currently `wp-prettier@2.0.5-beta-2`) here?

Yeah, we can. I'd probably not want to merge with the beta release, but it could be a good way to see which bugs (if any) still exist.

**Comment by aduth** [comment]
Some related discussion during today's [Weekly JavaScript Chat](https://make.wordpress.org/meetings/) ([link requires registration](https://make.wordpress.org/chat/)):

https://wordpress.slack.com/archives/C5UNMSU4R/p1590502200310200

One notable remark: Many of the changes affected by the `function` keyword spacing change should most likely be refactored anyways, toward using either arrow functions or function declarations, rather than function expression. This would avoid a lot of the revisions in the first place, making it a less impactful change. It could even be done as a (optionally blocking) separate effort to this pull request.

**Comment by ZebulanStanphill** [comment]
> > Just thought I'd bring up an issue I've been having with the WP fork of Prettier that I'm hoping might get fixed in this update: when the second or third clause of a ternary expression includes a function call that takes up multiple lines, the closing parentheses is preceded by 2 spaces:
> 
> Are you sure this is a bug, and that it's specific to `wp-prettier`?
> 
> [From what I can tell](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAJUQQwDCAFgJYA2AJgEKURgDWAzgDpRswD8uAZlXjpqASXgBbFgDoBlIQApci4LigBDcXFwBfXAEpcAXgB8HLlwJEyVOg2YtuU8lDCVM1OC0XrN+szFw-ThgkXABtAF0AbhAAGhAIAAcYcmgWZFA1VAIAdwAFLIR0lDVKHLUAT3T4gCNUNWYMAGVEhucAc2QYVEw4eNIYcUoAdQp4FlawOCai8hSANzmK5HAWapBnFjhUGDz69vE1ZD5SrfiAKxYAD1p6xpgmjTgAGWc4Y9O+kEurpo7KOAARUwRHeSBOlDOIFaqC2qBWNTUNTglDi0NQzhgw3I1BgpGQADYABzxRIELbDeqJFZkzzbebveIARxB8D2SWKIDULAAtFA4HAPNQ0egWeR0Hs1AcjuDPvEtuJyF0el8WP8gaywRCoTAkdjcfikAAmeLdNRUDrECDiQ4rTwAVjRmC2ABUkcVtV95r0RFAPLAmmAMckAIJ+powCoAj6QuDabRAA), it works this way in Prettier as well. And I might assume it's intentional, to try to "align" all lines of the ternary expression as indented by two spaces (aligning to `? ` or `: ` from the first line of each branch).

Huh, I guess I was mistaken. So... are we okay with this behavior? It doesn't really bother me.

**Comment by aduth** [comment]
> Huh, I guess I was mistaken. So... are we okay with this behavior? It doesn't really bother me.

It probably wouldn't be my first choice if I had full control over it. But given that we largely relent this control of decision-making to Prettier, we'll have to accept that it is what it is 🤷

**Comment by scinos** [comment]
> I'd probably not want to merge with the beta release, but it could be a good way to see which bugs (if any) still exist.

If those bugs are gone in the beta version, it will be a very strong signal that it is ready to be promoted out of beta.

**Comment by aduth** [comment]
The latest commit 279a80b uses the beta version 2.0.5-beta-2 .

It does appear to fix the issue with spacing in template strings 🎉 

Unfortunately, there are still some problems with parenthesis placement in some cases, where the space is put on the wrong (right-hand) side of the paranthesis.

Examples:

- https://github.com/WordPress/gutenberg/pull/22610/files#diff-c109b8d8ed07b3519b0cccb7aa9164b5
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-a5c77b070da74373cd1d937dee3a77ea
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-903d9fb271407adcc417922d742dc8c9
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-8619f969f601dd5bca28262cbae77bf4
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-44c0d7ad891d2d3fdde18044f97b5135
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-35d10f50d32f140a7ffdb8cf513328b3
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-5a04405ff53a434339280724f16ef501
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-4cae6dcd76cd21ded2f5ad5fe41b9451
- https://github.com/WordPress/gutenberg/pull/22610/files#diff-d066abbb51854de985e2e0c1dd102821

Based on the examples, it seems to mainly afflict single-line ternary expressions.

**Comment by sirreal** [comment]
> Unfortunately, there are still some problems with parenthesis placement in some cases, where the space is put on the wrong (right-hand) side of the parenthesis.

Thanks @aduth, that's extremely helpful. I've opened https://github.com/Automattic/wp-prettier/issues/25 to track this and we'll get a fix before the `wp-prettier@2.0.5` release.

**Comment by aduth** [comment]
> Some related discussion during today's [Weekly JavaScript Chat](https://make.wordpress.org/meetings/) ([link requires registration](https://make.wordpress.org/chat/)):
> 
> https://wordpress.slack.com/archives/C5UNMSU4R/p1590502200310200
> 
> One notable remark: Many of the changes affected by the `function` keyword spacing change should most likely be refactored anyways, toward using either arrow functions or function declarations, rather than function expression. This would avoid a lot of the revisions in the first place, making it a less impactful change. It could even be done as a (optionally blocking) separate effort to this pull request.

See: #22647

**Comment by sirreal** [comment]
I pushed a commit which upgrades to `wp-pretter@2.0.5-beta-3` and it appears to fix the issues with ternaries https://github.com/WordPress/gutenberg/pull/22610#issuecomment-634227551.

**Comment by aduth** [comment]
Thanks @sirreal for the quick turnaround!

I've also since merged #22647, then squashed and rebased this branch. The changes are much more reasonable for review now: down from 132 files changed (+387, -431) to to 56 files (+236, -280).

The individual changes appear to be correct as well!

Would you be okay to publish a stable `wp-prettier@2.0.5` ?

**Comment by sirreal** [comment]
There are a few more formatting fixes we're landing in https://github.com/Automattic/wp-prettier/pull/30.

I hope we can get 2.0.5 released in the next day or two.

**Comment by sirreal** [comment]
I've updated to `wp-prettier@2.0.5-beta-4` (
a97e303) and pushed the formatting changes separately in 7610ace6ec8e03b3768f5b8b80e93d1c0a2da7ce. There's now space inside `${ expressions }` in template strings.

**Comment by sirreal** [comment]
`wp-prettier@2.0.5` has been released 🎉 

I've updated the packages here, `npm run format-js` results in no new changes.

**Review by sirreal — APPROVED** [review]
This looks great 👍 

I think we need changelog entries for the affected packages: `scripts` `eslint-plugin`. I would like to see those before this is merged.

**Review by ntwb — APPROVED** [review]
Nice _pretty_ changes here, looks good to me using the [hide whitespace](https://github.com/WordPress/gutenberg/pull/22610/files?diff=unified&w=1) diff view.

Add the changelog entries as @sirreal mentioned and it's good to go 💯

**Comment by aduth** [comment]
Added CHANGELOG entries in 8c4de39.

I also (locally) rebased and re-ran `npm run format-js` to ensure there were no extra changes necessary since the last rebase.

**Comment by aduth** [comment]
Thanks all for the assist here 😃

**Pull request merged**
