### PR TITLE
Add: className prop support to server side render.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Required by: https://github.com/WordPress/gutenberg/pull/13511

In https://github.com/WordPress/gutenberg/pull/13511 a need appeared where it was necessary to add some styles to the wrapper container of a ServerSideRender component.
In order to do that the easy way is to add className support for ServerSideRender.

## How has this been tested?
I replaced the ServerSideRender usage on `packages/block-library/src/archives/edit.js with `<ServerSideRender className="my-random-class" block="core/archives" attributes={ attributes } />` `.
I added an archives block I inspected the dom and I checked the class "my-random-class" was applied.

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
I haven't tested but code-wise it looks very good. Can you also update docs to mention `className` in the list of supported props?

**Comment by jorgefilipecosta** [comment]
Hi @gziolo,

> I haven't tested but code-wise it looks very good. Can you also update docs to mention className in the list of supported props?

Docs were added.

**Review by gziolo — APPROVED** [review]
I added a few tiny tweaks to the docs. Code wise everything looks great and tests well.

**Comment by jorgefilipecosta** [comment]
Thank you for the review and tweaks @gziolo!

**Pull request merged**
