### PR TITLE
Docgen: replace assertions for `getIntermediateRepresentation` unit tests with snapshots

### PR DESCRIPTION
**Pull request by ciampo**
## Description

Replace all the assertions in the [`getIntermediateRepresentation` unit tests](https://github.com/WordPress/gutenberg/blob/trunk/packages/docgen/test/get-intermediate-representation.js) with equivalent [snapshot checks](https://jestjs.io/docs/snapshot-testing).

This approach requires less developer maintenance while serving the same purpose as the previous hand-written assertions.

## How has this been tested?

- Run `npm run test-unit packages/docgen`
- Make sure that all tests are passing

## Screenshots 

N/A

## Types of changes

Refactor

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] (N/A) I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by tyxla — APPROVED** [review]
Looks good and tests pass 👍 

I might be missing some context or rationale, but I'd love to get a second opinion on whether this is a good (and common in Gutenberg) use case for inline snapshot testing. FWIW I can definitely see value in it and how it reduces the manual part of maintaining these tests, which is why I am inclined to agree to move forward here.

**Comment by ciampo** [comment]
> I'd love to get a second opinion on whether this is a good (and common in Gutenberg) use case for inline snapshot testing

Absolutely. In fact, we discussed also measuring the time that those tests take before and after this PR — I am planning on posting that data later today

**Comment by ciampo** [comment]
I did a little experiment to understand if there's a difference in execution speed when using inline snapshots.

- I pulled the latest changes on `trunk` and rebased this PR's branch on top of it
- I ran the `npm run test-unit packages/docgen` command for 5 times on both branches

Results
- Average execution time on `trunk`: `3.5578s`
- Average execution time on this PR: `3.1494s`

Although this is by no means a comprehensive analysis, these first results seem to show that **there isn't a loss in performance when running tests with inline snapshots.**

<details>

<summary>View details</summary>

On `trunk` (no snapshots):
```
Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        4.749 s
Ran all test suites matching /packages\/docgen/i.

--- 

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        3.399 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        4.033 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        2.818 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   0 total
Time:        2.79 s
Ran all test suites matching /packages\/docgen/i.
```

On this branch (with inline snapshots):

```
Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   27 passed, 27 total
Time:        3.645 s
Ran all test suites matching /packages\/docgen/i.

--- 

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   27 passed, 27 total
Time:        3.848 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   27 passed, 27 total
Time:        2.72 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   27 passed, 27 total
Time:        2.72 s
Ran all test suites matching /packages\/docgen/i.

---

Test Suites: 6 passed, 6 total
Tests:       107 passed, 107 total
Snapshots:   27 passed, 27 total
Time:        2.814 s
Ran all test suites matching /packages\/docgen/i.

```
</details>

**Review by gziolo — APPROVED** [review]
Nice, thank you for working on this PR 👍🏻

**Pull request merged**
