### PR TITLE
Edit Site: Fix canvasMode var

### PR DESCRIPTION
**Pull request by tyxla**
## What?
Fix a missed instance from #66213.

## Why?
It's causing errors 😉 

## How?
Just using the right var.

## Testing Instructions
#66213 testing instructions should do.

### Testing Instructions for Keyboard
Same

### CODE REVIEW

**Review by ciampo — APPROVED** [review]

**Review by Mamaduka — APPROVED** [review]
Thank you, @tyxla!

**Review by sirreal — APPROVED** [review]
Seems reasonable, thanks for the fix 👍

**Comment by oandregal** [comment]
Thanks! I wonder why the tests didn't report issues in the original PR 🤔

**Comment by oandregal** [comment]
> Thanks! I wonder why the tests didn't report issues in the original PR 🤔

Related https://github.com/WordPress/gutenberg/pull/66213#issuecomment-2429125646

**Comment by youknowriad** [comment]
Thanks for the quick follow-up

**Comment by youknowriad** [comment]
Looks like just a rare case where two PRs got merged almost at the same time and both with tests passing.

**Pull request merged**
