### PR TITLE
Change z-index to fix block mover over link input

### PR DESCRIPTION
**Pull request by Rahmon**
## Description
Block mover handles showing over link input #3464 

## How Has This Been Tested?
This has been tested with "npm test", "npm run test-e2e" and manually on Chrome and Firefox.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Should the mover be lowered? Not sure why it would need to be so high in the first place.

**Comment by Rahmon** [comment]
I set the z-index of mover to be lower and it's worked.

**Comment by aduth** [comment]
Was already lowered once in dbb97428580576ec53187391a93da7ffda67a935 so I think it should be fine to do so here.

**Review by aduth — APPROVED** [review]
👍

**Pull request merged**
