### PR TITLE
Framework: Upgrade React version to 16.3.0

### PR DESCRIPTION
**Pull request by gziolo**
## Description
This PR updateS React version to version 16.3.0 (it was moved to its own PR from #5029). One of the new features that 16.3.x is going to introduce is [new context API](https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b).  There are no breaking changes in this release.

_Note:_ Enzyme hasn't published a new version yet although they landed in `master` changes required to make it possible to test new Context Components. We will have to tackle it separately with `@wordpress/jest-preset-default` upgrade.

Release details:
https://reactjs.org/blog/2018/03/29/react-v-16-3.html

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Review by pento — APPROVED** [review]
DO IT

**Review by atimmer — APPROVED** [review]
Don't let your dreams be dreams

**Comment by youknowriad** [comment]
Let's merge it to see if anything breaks soon enough.

**Pull request merged**
