### PR TITLE
[Monorepo] Master PR

### PR DESCRIPTION
**Pull request by dratwas**
Explores #11491.
Superseeds #17456 started by @Tug

This is a migration of gutenberg-mobile to gutenberg repository with git history.

## How has this been tested?
At this stage, there is nothing to test.

list of all related PRs:
- [x] [[Monorepo][base-branch] import of gutenberg-mobile](https://github.com/WordPress/gutenberg/pull/18508)
- [x] [[Monorepo] Split gutenberg-mobile to 3 packages - bridge, editor, aztec](https://github.com/WordPress/gutenberg/pull/18509)
- [x] [[Monorepo] Rename react-native-gutenberg-bridge to react-native-bridge](https://github.com/WordPress/gutenberg/pull/18515)
- [x] [[Monorepo] Move dependencies to root package.json and change yarn to npm](https://github.com/WordPress/gutenberg/pull/18531)
- [x] [[Monorepo] Port react-native-aztec to js](https://github.com/WordPress/gutenberg/pull/20533)
- [x] [[Monorepo] Keep up with gutenberg-mobile and gb `master`](https://github.com/WordPress/gutenberg/pull/20533)
- [x] [[Monorepo] Fix android build](https://github.com/WordPress/gutenberg/pull/18569) 
- [x] [[Monorepo] Fix iOS build](https://github.com/WordPress/gutenberg/pull/18566) 
- [x] [[Monorepo] Fix linting](https://github.com/WordPress/gutenberg/pull/21349) 
- [x] [Fix license check script to ignore sub-dependencies of ignored packages](https://github.com/WordPress/gutenberg/pull/21606)
- [x] ~[[Monorepo] Move pods to the root level and add bundles](https://github.com/WordPress/gutenberg/pull/18579)~
- [x] ~[[Monorepo] Setup Jitpack](https://github.com/WordPress/gutenberg/pull/18580)~
- [x] ~[[Monorepo] Port mobile e2e tests](https://github.com/WordPress/gutenberg/pull/18576)~
- [x] [[Monorepo] Merge gutenberg-mobile and gutenberg master (again)](https://github.com/WordPress/gutenberg/pull/21790)
- [x] [[Monorepo] Fix license check errors in monorepo branch](https://github.com/WordPress/gutenberg/pull/22106)
- [x] [[Monorepo] Update from master and fix web e2e tests](https://github.com/WordPress/gutenberg/pull/21966)
- [x] [[Monorepo] Use github actions to run React Native e2e tests](https://github.com/WordPress/gutenberg/pull/22189)
- [x] [[Monorepo] Integrate with gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2172)
- [x] ~Fix i18n and `npm run native bundle` (do we even need a bundle on gutenberg?)~
- [x] [[Monorepo] Merge gutenberg-mobile and gutenberg master (yet again)](https://github.com/WordPress/gutenberg/pull/23248)
- [x] [Merge to `master`](https://github.com/WordPress/gutenberg/pull/22714)

### CODE REVIEW

**Review by Tug — APPROVED** [review]
This LGTM, it seems all the commits are ported with their rightful author 👍 
As discussed, we'll be fixing tests progressively in the `feat/import-gutenberg-mobile` branch!

**Comment by Tug** [comment]
@dratwas Any blocker for this one?

**Comment by dratwas** [comment]
@Tug I'm afraid that I need to update it from `develop` gutenberg-mobile` branch since a lot of things have changed

**Comment by Tug** [comment]
@dratwas although it's ok to not be 100% in sync with gutenberg-mobile (this is a branch experiment, and we can always merge in the latest change progressively), it's true that we haven't updated it for a while, updating now

**Review by maxme — APPROVED** [review]
Obviously I haven't reviewed the code, but I checked the commit history looked like what we have  in `gutenberg-mobile` and I also checked the changes were contained in `packages/react-native-editor/`

---


These changes are contained in `packages/react-native-editor/` only:

```sh
$ git diff --name-only feat/import-gutenberg-mobile...rnmobile/import-mobile | cut -d "/" -f1-2 | uniq
packages/react-native-editor
```

--- 

Commit history looks like the same in this PR and in the `gutenberg-mobile` repo.

```
$ cd gutenberg-mobile
$ git shortlog -s
```

and

```sh
$ git shortlog -s feat/import-gutenberg-mobile...rnmobile/import-mobile
```

gives almost the same results.

Note: I'm not sure how relevant some of the dotfiles are in there, but seems like we don't want to complexify this by filtering them out yet.

**Pull request merged**
