### PR TITLE
Try: New Buttons icon.

### PR DESCRIPTION
**Pull request by jasmussen**
This PR adds a new icon for the _Buttons_ block (plural):

Screenshot 2021-01-29 at 12 11 33

Before, the Buttons block had the same icon as the Button (singular), which wasn't very clear either when selecting blocks, or using the block navigation tool:

Screenshot 2021-01-29 at 13 02 22

The new buttons icon is just two button icons side by side. It's a bit smaller, but it helps explain the hierarchy:

Screenshot 2021-01-29 at 13 03 07

### CODE REVIEW

**Comment by pablohoneyhoney** [comment]
Maybe stacked vertically?

**Comment by jasmussen** [comment]
Here are two stacked versions:

Screenshot 2021-01-29 at 18 05 47

Screenshot 2021-01-29 at 18 10 39

Any preference? 

I also pushed a small fix to the regular buttons icon, I noticed that the "text label" was not perfectly vertically centered. It is now:

Screenshot 2021-01-29 at 18 08 12

**Comment by pablohoneyhoney** [comment]
The wider version seems to be semantically more obvious to me.

**Comment by jasmussen** [comment]
This looks like a winner:

Screenshot 2021-02-02 at 08 19 41

**Review by aristath — APPROVED** [review]
Nice! LGTM :+1:

**Comment by talldan** [comment]
Maybe the two different icons can be used for the horizontal/vertical variations of buttons, @jasmussen.

**Comment by jasmussen** [comment]
> Maybe the two different icons can be used for the horizontal/vertical variations of buttons

Interesting idea! I'm still a bit fuzzy on block variations vs. style variations — to an extent I think of Navigation as one block with two orientations, same with Buttons. But at the same time we do have unique icons and names for "Menu Items" (page link, tag link, etc.)

I wonder if it sets a bad precedence, though — while the two icon variations shown in this conversation map very well to the varying orientations of the block, ultimately they are still meant to represent the block in an abstract way through the iconography, moreso than a literal way. Take the Navigation block as an example:

Screenshot 2021-02-02 at 08 44 26

That's a compass, implying you use the navigation as a wayfinder, and it has no other literal comparison. 

I'm happy to provide the icon if we deem it necessary, but I'm leaning towards keeping it abstract, even if it also happens to be literal in this case.

**Comment by jasmussen** [comment]
Going to land this one and follow up with anything that might come! Thanks for the reviews.

**Comment by talldan** [comment]
That's a good point @jasmussen, I suppose it depends if the block appears in the inserter. I don't think the navigation block's variations should be in the inserter now that they can be switched in the inspector.

**Comment by jasmussen** [comment]
> I don't think the navigation block's variations should be in the inserter now that they can be switched in the inspector.

I think there's a separate conversation to have there, because I still don't think it's a great interface that you can switch styles in the block toolbar using the switcher, and switch the _orientation_ in the inspector. They seem related. But that's a very non-urgent hyperoptimization that I'm sure we'll get to one day 😅

**Comment by talldan** [comment]
Yeah, I think there's probably a better way of handling it as part of the general concept of layout.

**Pull request merged**
