### PR TITLE
ToggleGroupControl: rewrite backdrop animation with framer-motion's shared layout animations

### LINKED ISSUE #37506: Color select component backdrop render and animation opportunities
### Description

The rendering on the backdrop is inconsistent when rendering inside an animating parent. The current implementation has a delay of 100ms but it's not very reliable, and is also dependent on the parent animating for 100ms.

### Step-by-step reproduction instructions

1. Add a group block
2. Open the color settings
3. Press Background color
4. Toggle gradient and solid items

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/1478421/146626852-1d982150-080d-48bb-980d-08968087a887.mov

### Environment info

- Gutenberg 12.2.0-rc.1
- TT1 Blocks
- Chrome
- Mac

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Completely rewrite the `ToggleGroupControl` 's animated backdrop using `framer-motion`'s [shared layout animations](https://www.framer.com/docs/layout-group/).

Supersedes #40107 

Fixes https://github.com/WordPress/gutenberg/issues/37506

## Why?

Current implementation is complex, difficult to read, imperative (based off arbitrary timeouts), and [buggy](https://github.com/WordPress/gutenberg/issues/37506).

## How?

Main changes are:

- deleted the `ToggleGroupControlBackdrop`, and the imperative logic that came with it
- re-implemented the backdrop using `framer-motion`'s shared layout animations:
    - the main way this works is by using the same value for the `layoutId` attribute to tag the components that participate to the same shared layout animation
    - each `ToggleGroupControl` also defines its own "namespace" for the shared layout animations via the `LayoutGroup` component, in order to avoid conflicts between different instances of the component
- cleanup up some styles and removed some unused variables
- memoized some classnames

## Testing Instructions

Make sure that the backdrop animation works as expected:
  - in Storybook (check all of the different examples for `ToggleGroupControl`)
  - in the block editor (in particular, test for the scenario highlighted in #37506)

## Screenshots or screencast 

https://user-images.githubusercontent.com/1083581/162973588-26f77da2-4c4e-4c2f-a953-ef7ab81d3198.mp4

### CODE REVIEW

**Comment by ciampo** [comment]
For some reason, it looks like the new approach doesn't work in the block inspector controls:

https://user-images.githubusercontent.com/1083581/163015309-5081f115-b711-4b3e-93fb-4e27a40e1ae5.mp4

While it seems to work just fine in the Site editor:

https://user-images.githubusercontent.com/1083581/163015598-757a417e-669a-4eaf-ab5a-fa98252a769f.mp4

I wonder if the problem is related `InspectorControls.Slot` and more in general the slot-fill mechanism — I pushed a temporary change (https://github.com/WordPress/gutenberg/pull/40276/commits/9b63e86f50f28c0cb6df2a48fce2cde5d37e7403) to show how the same component works fine outside of the slot, but doesn't inside the slot.

@aaronrobertshaw maybe you could you help here? I'm not really knowledgeable about this part of the codebase

**Comment by stokesman** [comment]
Awesome @ciampo! This was actually the first approach I tried and I ran into the same issue. I spent plenty of time trying to work around it and didn't find a solution that worked in every situation. I didn't realize it worked fine inside of Site Editor or outside of that slot so maybe that can lead the investigation somewhere more fruitful.

If we can figure out what is going on in this inspector slot it might help fix other issues. It's great that you've isolated it.

**Comment by aaronrobertshaw** [comment]
> I wonder if the problem is related InspectorControls.Slot and more in general the slot-fill mechanism — I pushed a temporary change (https://github.com/WordPress/gutenberg/commit/9b63e86f50f28c0cb6df2a48fce2cde5d37e7403) to show how the same component works fine outside of the slot, but doesn't inside the slot.

We can probably narrow the investigation further to just the block editor's `InspectorControls` slot.

I created an extra storybook example rendering the `ToggleGroupControl` via a slot (with and without virtual bubbling) and it appears to work OK.

<details>
<summary>ToggleGroupControl SlotFill Example</summary>

```diff
diff --git a/packages/components/src/toggle-group-control/stories/index.js b/packages/components/src/toggle-group-control/stories/index.js
index d56541974d..9cbb82a84f 100644
--- a/packages/components/src/toggle-group-control/stories/index.js
+++ b/packages/components/src/toggle-group-control/stories/index.js
@@ -18,6 +18,7 @@ import {
 	ToggleGroupControlOptionIcon,
 } from '../index';
 import { View } from '../../view';
+import { createSlotFill, Provider as SlotFillProvider } from '../../slot-fill';
 import Button from '../../button';
 
 export default {
@@ -232,3 +233,38 @@ export const DoubleToggles = () => {
 		</View>
 	);
 };
+
+const { Fill: InspectorControls, Slot } = createSlotFill( 'InspectorControls' );
+InspectorControls.Slot = Slot;
+
+// TODO: Remove before merging as well.
+export const RenderViaSlot = () => {
+	const [ alignState, setAlignState ] = useState();
+	const aligns = [ 'Left', 'Center', 'Right' ];
+
+	return (
+		<SlotFillProvider>
+			<InspectorControls>
+				<ToggleGroupControl
+					onChange={ setAlignState }
+					value={ alignState }
+					label={ 'Pick an alignment option' }
+				>
+					{ aligns.map( ( key ) => (
+						<ToggleGroupControlOption
+							key={ key }
+							value={ key }
+							label={ key }
+						/>
+					) ) }
+				</ToggleGroupControl>
+			</InspectorControls>
+			<View>
+				<InspectorControls.Slot bubblesVirtually />
+				<Button onClick={ () => setAlignState( undefined ) } isTertiary>
+					Reset
+				</Button>
+			</View>
+		</SlotFillProvider>
+	);
+};

```
</details>

https://user-images.githubusercontent.com/60436221/163114075-5c953532-0446-4730-95c9-9eb2d419f608.mp4

**Comment by ciampo** [comment]
Alright, I spent the past couple of days looking into it until I found the cause of the issue:

basically, the `ToggleGroupControl` component that gets injected via Slot/Fill is initially rendered in another part of the React Tree — when the `motion` elements used for the backdrop animation are mounted, they initially take, as their parent `motion` element, the [two `motion.div` elements defined in the `VisualEditor`](https://github.com/WordPress/gutenberg/blob/721e3c4d3c1854ca839b0dd0713e8756060aaacd/packages/edit-post/src/components/visual-editor/index.js#L197-L220), even if that wouldn't be true anymore after they get "teleported" via Slot/Fill to the block controls in the sidebar.

This mismatch causes some issues (which I haven't pinpointed exactly yet) in `framer-motion`'s [node projection logic](https://github.com/framer/motion/blob/720667e61d26be82d39fc726e84e2f6820859baa/packages/framer-motion/src/projection/node/create-projection-node.ts), which basically prevents motion from calculating correctly the sizes and transformations to apply during the animation.

This can be verified by:

- swapping `motion.div` with a simple `div` in the [`VisualEditor` component ](https://github.com/WordPress/gutenberg/blob/721e3c4d3c1854ca839b0dd0713e8756060aaacd/packages/edit-post/src/components/visual-editor/index.js#L197-L220), which should temporarily fix the issue in the sidebar
- checking out the new Storybook example that I added [in the last commit](https://github.com/WordPress/gutenberg/pull/40276/commits/62348288182ea31c3cae8804a602bd4b4b01fcf1), where I took @aaronrobertshaw 's latest code snippet and simply wrapped the `InspectorControls` fill inside a `motion.div` — the animations in this story should _not_ work (unless the `motion.div` is swapped with a regular `div`)

---

I'm not sure yet if there's a solution here that will fix this incompatibility between `framer-motion` and Slot/Fill (react portals), but at least now we have a way to reproduce the issue!

**Comment by ciampo** [comment]
I spent some more time investigating the issue and I managed to reproduce it even more in isolation:

- using a custom, simpler version of a `Toggle` component
- using the same dependency versions as in this PR (`react@17.0.2`, `framer-motion@6.2.8`)
- using both `Slot/Fill` from `@wordpress/components`, but also a vanilla React portal

You can see the little demo I built on CodeSandbox [here](https://codesandbox.io/s/framer-motion-and-portals-ozvlh3?file=/src/App.js).

As for the next steps, I'm a bit out of ideas — ~I'm probably going to open~ I opened an issue on the `framer-motion` repository (https://github.com/framer/motion/issues/1524), but I wonder if anyone else here has any ideas about how to potentially fix this on our end? (@youknowriad maybe you could take a look?)

**Comment by ciampo** [comment]
Update:

following a piece of advice shared in https://github.com/framer/motion/issues/1524#issuecomment-1280834006, I managed to get shared layout animations in `ToggleGroupControl` working also in `Slot`/`Fill`s (i.e InspectorControls) ([commit with the fix](https://github.com/WordPress/gutenberg/pull/40276/commits/f58e571293071e52d773aaa81577610615facdd3)).

There's still one final issue left: somehow, when selecting a block that has an assigned font-size, the selected option animates down unexpectedly:

https://user-images.githubusercontent.com/1083581/196258254-bd938052-ea9d-466c-9ebb-91228eaeca69.mp4

I haven't managed to isolate the cause yet, but it seems related to the block editor specifically (both post editor and site editor) — I haven't been able to reproduce it in Storybook for the `FontSizePicker` component.

Has anyone got any ideas on what could cause this animation glitch?

**Comment by ciampo** [comment]
Update: in an effort to isolate the cause of the glitch, I experimented with:

- tweaking `FontSizeEdit` so that the internal font size value is hardcoded (i.e it's not read/written dynamically from the settings)
- rendering the same `FontSizeEdit` component in the sidebar without nesting it in `ToolsPanel` / `SlotFill`

<details>

<summary>See code diff</summary>

```diff
diff --git a/packages/block-editor/src/components/block-inspector/index.js b/packages/block-editor/src/components/block-inspector/index.js
index 379d8806f2..37c37ae3c4 100644
--- a/packages/block-editor/src/components/block-inspector/index.js
+++ b/packages/block-editor/src/components/block-inspector/index.js
@@ -35,6 +35,7 @@ import BlockVariationTransforms from '../block-variation-transforms';
 import useBlockDisplayInformation from '../use-block-display-information';
 import { store as blockEditorStore } from '../../store';
 import BlockIcon from '../block-icon';
+import { FontSizeEdit } from '../../hooks/font-size';
 
 function useContentBlocks( blockTypes, block ) {
 	const contenBlocksObjectAux = useMemo( () => {
@@ -260,6 +261,8 @@ const BlockInspectorSingleBlock = ( { clientId, blockName } ) => {
 				label={ __( 'Color' ) }
 				className="color-block-support-panel__inner-wrapper"
 			/>
+
+			<FontSizeEdit />
 			<InspectorControls.Slot
 				__experimentalGroup="typography"
 				label={ __( 'Typography' ) }
diff --git a/packages/block-editor/src/hooks/font-size.js b/packages/block-editor/src/hooks/font-size.js
index f8fa94538f..0c8b5fcb33 100644
--- a/packages/block-editor/src/hooks/font-size.js
+++ b/packages/block-editor/src/hooks/font-size.js
@@ -114,41 +114,10 @@ function addEditProps( settings ) {
  *
  * @return {WPElement} Font size edit element.
  */
-export function FontSizeEdit( props ) {
-	const {
-		attributes: { fontSize, style },
-		setAttributes,
-	} = props;
-	const fontSizes = useSetting( 'typography.fontSizes' );
-
-	const onChange = ( value ) => {
-		const fontSizeSlug = getFontSizeObjectByValue( fontSizes, value ).slug;
-
-		setAttributes( {
-			style: cleanEmptyObject( {
-				...style,
-				typography: {
-					...style?.typography,
-					fontSize: fontSizeSlug ? undefined : value,
-				},
-			} ),
-			fontSize: fontSizeSlug,
-		} );
-	};
-
-	const fontSizeObject = getFontSize(
-		fontSizes,
-		fontSize,
-		style?.typography?.fontSize
-	);
-
-	const fontSizeValue =
-		fontSizeObject?.size || style?.typography?.fontSize || fontSize;
-
+export function FontSizeEdit() {
 	return (
 		<FontSizePicker
-			onChange={ onChange }
-			value={ fontSizeValue }
+			value={ '2.25rem' }
 			withReset={ false }
 			size="__unstable-large"
 			__nextHasNoMarginBottom

```
</details>

https://user-images.githubusercontent.com/1083581/196266608-352ad8bf-38b8-4c7d-9ae4-ab3a68355411.mp4

In my tests,  the `FontSizeEdit` that is not rendered inside `ToolsPanel` / `SlotFill` does not suffer from the glitch — **and so the issue could be related to either `SlotFill` or `ToolsPanel`.**

---

I then tested this theory in [this CodeSandbox](https://codesandbox.io/s/framer-motion-and-portals-framer-motion-7-2-1-y9vu1d), and it looks like wrapping the component in `SlotFill` causes the initial animation to glitch:


https://user-images.githubusercontent.com/1083581/196267906-75612b8e-c434-4e9c-b97a-73e9a2d6faf8.mp4

---

@youknowriad , this is not high priority, but it would be great if you could take a look at this. Also happy to pair on this issue together!

**Comment by youknowriad** [comment]
@ciampo At this point, I admit I was not able to understand why this is happening. Do you know any wild guesses?

**Comment by ciampo** [comment]
After [the update to a more recent framer motion version](https://github.com/WordPress/gutenberg/pull/49822), I wanted to test and see if the situation improved. I tried rebasing but `ToggleGroupControl` has changed a lot since this PR was opened, and so I decided to open a new PR: https://github.com/WordPress/gutenberg/pull/50278

Going to close this PR, we can continue the conversation there.

**Pull request closed without merging**
