### PR TITLE
Add `fullScreen` control to the block alignment toolbar

### PR DESCRIPTION
**Pull request by retrofox**
## Description
This PR adds a `fullScreen` control to the `<BlockAlignmentToolbar />` component., trying to tackle the _Full Screen alignment/display option on several blocks (https://github.com/WordPress/gutenberg/issues/16385)_ issue.

Screen Shot 2019-09-04 at 10 27 47 AM

### Related Issues:

* https://github.com/WordPress/gutenberg/issues/16698: Add vertical alignment to Media & Text block
* https://github.com/WordPress/gutenberg/issues/16385: Full Screen alignment/display option on several blocks

### How does it look
It adds the `fullScreen` control into the Alignment toolbar:

### How does it work
It applies almost the same behavior to the full mode does, but cut the height to the current height of the viewport.

#### `wide` alignment (already done)
It applies almost the same behavior to the full mode does, but cut the height to the current height of the viewport.

## How has this been tested?
TBD

## Pending Tasks

- [x] Experiment with background image CSS.
- [x] Consider finding a better control Icon
- [x] Consider joining the `expand` control into the alignment toolbar.
- [ ] Test deeply all combinations in different devices/platforms.

### CODE REVIEW

**Comment by mapk** [comment]
I really like the concept, @retrofox! I believe adjusting a block to be full-screen-height could open up some amazing layout design.

I am concerned about adding another toolbar section for this control. If we do ever decide to include `wide width` or `full width` in this section, I could see its validity. However, it does operate well paired with some of those other alignments, so being able to multiselect those is a big part of this feature.

I haven't looked at the code, but taking a look at how it functions in the Editor, I found a few areas needing refinement. I'm using the [Gutenberg Starter Theme](https://github.com/WordPress/gutenberg-starter-theme) for testing which uses basic default Gutenberg styles in both the Editor and the frontend.

1. The icon for this feature left me confused. It took me some time to figure out that it was indicating height and not horizontal margins or fluctuations. Once I understood, it made perfect sense, but I wonder if there's another option?

2. When toggled "on" the full-screen height distorted the image in my Image block. It probably shouldn't do that. Maybe it should default with something like `background-size:cover`?

3. When toggled "on" and having the `wide width` or `full width` options "on" the block inside the editor expanded a great deal lower than the image in my Image block. I would imagine the image should fill the block height, but it wasn't.

distort


While you're working on this PR, I'd love to get more design feedback from others.

**Comment by mapk** [comment]
Also congrats on your first PR!! 🎉

**Comment by mtias** [comment]
@mapk I tend to agree, this makes sense as part of the general alignments group, specially if we are looking at collapsing it always: https://github.com/WordPress/gutenberg/pull/16557

However, this also has the advantage of being orthogonal to some of the wide alignments so you could make different interesting combinations. Perhaps we could split the alignment group within the dropdown (with a separator)? Not sure if that would increase or decrease its usability.

**Comment by retrofox** [comment]
> The icon for this feature left me confused. It took me some time to figure out that it was indicating height and not horizontal margins or fluctuations.

I only turned the `full width`  icon 90 degrees. 

> Once I understood, it made perfect sense, but I wonder if there's another option?

I'd like listening to suggestions in this case since I'm not a designer which leads me to do implementations that only me understand :-D 

> When toggled "on" the full-screen height distorted the image in my Image block.

Something to fix. :+1:

> It probably shouldn't do that. Maybe it should default with something like background-size:cover?

yes, for instance, I like how the `core/cover` handles the image using background-size instead of an `` tag. I'm afraid that switching to use CSS for the `core/image` could require more investment and changes, though. Will glad to follow this path if we consider it worths.

> When toggled "on" and having the wide width or full width options "on" the block inside the editor expanded a great deal lower than the image in my Image block. I would imagine the image should fill the block height, but it wasn't.

Yup confirmed. Let me do another iteration.

**Comment by retrofox** [comment]
> Perhaps we could split the alignment group within the dropdown (with a separator)?

Good option imo.

**Comment by retrofox** [comment]
Hi @mapk!, I've creates a different approach to implement the `expand` mode fo the `core/image` block to deal with the issues that mentioned last week. As you suggested, I've tried using the background image CSS approach. I've activated `gutenberg-starter-theme` as well.

I've added an animation but tbh it isn't enough to show the whole changes. It seems that's just a matter of testing deeply :-D 

gutenberg-wide-full-expand

**Comment by BinaryMoon** [comment]
I like the idea of stretching content to 100vh but am not sure about using background-size.

Using the image element means we can take advantage of responsive images sizes, but background-size cover requires the largest image likely to be used, which is bad for small devices on slow connections.

Could this use object-fit instead? There is a cover option available so images can still be scaled nicely.

**Comment by retrofox** [comment]
> Could this use object-fit instead? There is a cover option available so images can still be scaled nicely.

Definitely going to gid on this, @BinaryMoon. 👍

**Comment by jasmussen** [comment]
Really nice work. 

I would definitely echo Mark and Matías on this one — the only challenge with this one is how we show it in the toolbar. And an additional toolbar group feels like the wrong path for this. 

I understand that wide and fullwide are not traditional "alignments" thinking like how we're used to, but they have fit very nicely with left/center/right for exactly the reason you allude to: they do not stack.

At the same time, in the same design, Bold and Italic buttons stack — those are just toggle buttons. 

For that reason, I think the option to explore is this one: https://github.com/WordPress/gutenberg/pull/16738#issuecomment-515435754

Go with the dropdown, and put a separator into the dropdown. You could even have a subheading, like:

```
Block Layout
- Left
- Center
- Right
- Wide
- Full wide
___________
Additional Layout Effects
- Full-height
```

One of the reasons for the dropdown PR is to enable clearer labels and additional layout options like this. By adding a separator in that dropdown, we keep the "non-stackable" effect of the basic alignments, but allow additional on top of that.

**Comment by mapk** [comment]
@retrofox, this is feeling really good. Let's implement Joen's suggestion above https://github.com/WordPress/gutenberg/pull/16738#issuecomment-518138626. This probably involves rebasing with `master` to get the latest collapsed block toolbar version.

After that we can revisit the icon.

**Comment by mapk** [comment]
Just tested again today, and it appears I can no longer select both "full height" and "full width" as I once was able. I'm not sure if this is because they are both in the same condensed menu now, but I'd like this to work in conjunction with the "full width" and "wide width" selections as well. 

Also it appears selecting full height in the editor didn't do anything visually. The frontend doesn't show it as full height anymore either.

full

**Comment by mapk** [comment]
Also to think about... if we are now providing multiple items within the dropdown that can be selected, I imagine each selected item should be visible in the block toolbar, yeah? 

Screen Shot 2019-08-14 at 7 08 19 AM

This doesn't feel quite right though.

There's also a multi-select issue created here: https://github.com/WordPress/gutenberg/issues/17009

**Comment by retrofox** [comment]
> Just tested again today, and it appears I can no longer select both "full height"

right, it's in work in progress. :-/ Sorry, Mark. Going to update soon.

> I imagine each selected item should be visible in the block toolbar, yeah?

It makes sense to me, but I guess it will require to create a new Toolbar block (like as I did before of removing it :-))

**Comment by shaunandrews** [comment]
> wide and fullwide are not traditional "alignments"

I run into this confusion all the time. I myself always have trouble remember exactly what "full-width" actually means — and I see users who click "full-width" and are never certain exactly what it did. I fear that adding "full-height" to the list of alignments is just going to exacerbate this confusion.

These two options (full-height/width) aren't related to alignment of an element. I wonder if it would make sense to break these out into a "dimensions" control of some sort. I could see other values outside of "full" being useful — that is, imagine being able to set the width to 50%.

**Comment by retrofox** [comment]
> I wonder if it would make sense to break these out into a "dimensions" control of some sort

I had created an <BlockExpandToolbar /> which had only the expand button and was tempted to move the wide and width buttons from the alignment toolbar to this one so finally, both toolbars had got with three controls.

**Comment by kjellr** [comment]
👋 We discussed this ticket in [today's #design chat](https://wordpress.slack.com/archives/C02S78ZAL/p1566411563271100) on slack. (A WordPress.org slack login may be required to view the transcript). 

A few things to note: 

- We should consider changing this to a "Full Screen" option, that makes the object both 100vw and 100vh. This seems to be the most common use case for using this option, and will sidestep the multi-select issue at hand.
- Eventually, we may want to consider breaking out alignment and width/height options into their own control: it's been noted before, but wide/Full/Fullscreen aren't truly alignments. 
- Also, the icon used in this PR is also used for "Flip Image" in core. If we use "fullscreen" here, we should consider using some variation of Material's fullscreen icon for this: 

Screen Shot 2019-08-21 at 2 40 31 PM

**Comment by kjellr** [comment]
> thanks @kjellr, do you know if this icon is already available?

I don't think it's in `dashicons`, unfortunately. @jasmussen should this be added there for now, alongside the other alignment icons? 

Either way, [here's a SVG](https://cloudup.com/cl26ZWzKF0A) that uses the same grid as the existing alignment icons:

alignment

**Comment by jasmussen** [comment]
Yeah we can add this to Dashicons. I've got a bit on my plate so can't do it in the near future. I'm wondering: can we add it as an inline SVG in the mean time?

**Comment by kjellr** [comment]
> Yeah we can add this to Dashicons. I've got a bit on my plate so can't do it in the near future. I'm wondering: can we add it as an inline SVG in the mean time?

No problem, thanks @jasmussen. I opened a PR for it here: https://github.com/WordPress/dashicons/pull/373

**Comment by retrofox** [comment]
> Eventually, we may want to consider breaking out alignment and width/height options into their own control: it's been noted before, but wide/Full/Fullscreen aren't truly alignments.

What do you think at least for now move divide the aligments options as below?

image

**Comment by retrofox** [comment]
> I don't think it's in dashicons, unfortunately. @jasmussen should this be added there for now, alongside the other alignment icons?

Let's use the SVG icon for now :-)

**Comment by kjellr** [comment]
> What do you think at least for now to divide the alignments options as below?

I'm not sure that actually makes sense just yet. Adding the divider seems correct from a conceptual perspective, but functionally all items in that menu are still operating at the same level of hierarchy: selecting one from that first set will deselect the active one from the second set. The divider confuses that. 

In any case, I don't think we need to address this separation in this PR, so I'd vote to just leave it as is for the moment.

**Comment by retrofox** [comment]
> In any case, I don't think we need to address this separation in this PR, so I'd vote to just leave it as is for the moment.

Sorry, do you mean to move the divider at the bottom leaving the `Full Screen` separated from the other controls, or just remove the divider from there?

**Comment by kjellr** [comment]
> Sorry, do you mean to move the divider at the bottom leaving the Full Screen separated from the other controls, or just remove the divider from there?

I think we can leave that separator out entirely for now.

**Comment by mapk** [comment]
No separator works well. 

Screen Shot 2019-08-29 at 8 09 42 AM

The only problem I still see is that it's not aligning correctly in the Editor or on the frontend to full-screen.

**Comment by paaljoachim** [comment]
Hey Damian @retrofox 

Could you add a status update letting us know how this PR is doing. Let us know what is needed to move it onward. Thanks.

**Comment by retrofox** [comment]
> Could you add a status update letting us know how this PR is doing?
> Let us know what is needed to move it onward. Thanks.

Definitely going to do it today or tomorrow in my morning.

**Comment by retrofox** [comment]
I've been updated the PR:

* `<BlockAlignmentToolbar >` handles this new mode
* Implement this alignment in the `<EditImage />` block (only in the Editor side)
* Implement frontend is wip

I've seen that some styles are already handled by the theme. I've added the root css rules in order to make it work as better as possible.

### How it works:

It applies almost the same behavior to the `full` mode does, but cut the height to the current height of the viewport. I think it's a good scope before to start to explore other functionalities.

**Comment by retrofox** [comment]
Updated PR description

**Comment by mapk** [comment]
Hey @retrofox, would you mind rebasing this PR? I'd like to see where it's at. Thanks!

**Comment by retrofox** [comment]
Going to update soon. It needs a deep rebase.

**Comment by paaljoachim** [comment]
Just a heads up alignments are being reworked these days. There are two links right above here to take a closer look at.

**Comment by paaljoachim** [comment]
Hey @retrofox 
It would be great with a status update of this PR.
Thanks.

**Comment by retrofox** [comment]
closing in favor of https://github.com/WordPress/gutenberg/pull/26615

**Pull request closed without merging**
