### PR TITLE
[RNMobile][Embed Block] Revert workaround for loading glitch

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

This PR reverts the changes introduced in https://github.com/WordPress/gutenberg/pull/33574.

## How has this been tested?

Follow the testing instructions from the reverted PR https://github.com/WordPress/gutenberg/pull/33574 and verify that the original issue is not happening.

## Screenshots 

N/A

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jd-alexander** [comment]
I am currently seeing this issue on WP Android at times when I spin up this solution in metro server. So I will run the cases mentioned and the UI state changes will occur as expected and then randomly this bug appears. I am working on capturing it due to it occurring randomly.

**Comment by fluiddot** [comment]
> I am currently seeing this issue on WP Android at times when I spin up this solution in metro server. So I will run the cases mentioned and the UI state changes will occur as expected and then randomly this bug appears. I am working on capturing it due to it occurring randomly.

Right, I've just tested on an Android device and I managed to reproduce it. I guess the original issue was maybe easier to reproduce on Android 🤔 .

I'll try to figure out a new approach to prevent the original issue 🔧 .

**Comment by fluiddot** [comment]
> > I am currently seeing this issue on WP Android at times when I spin up this solution in metro server. So I will run the cases mentioned and the UI state changes will occur as expected and then randomly this bug appears. I am working on capturing it due to it occurring randomly.
> 
> Right, I've just tested on an Android device and I managed to reproduce it. I guess the original issue was maybe easier to reproduce on Android 🤔 .
> 
> I'll try to figure out a new approach to prevent the original issue 🔧 .

I finally found the culprit of this behavior:

We're using the selector `isRequestingEmbedPreview` to determine if the embed preview is being fetched, however, it doesn't guarantee that it will return `true` right after calling the selector `getEmbedPreview` with an URL. The `true` value is returned after a couple of renders which produces the loading glitch described in the original issue.

The `isRequestingEmbedPreview` selector internally checks the `isResolving` status of the `getEmbedPreview` resolver, which initially returns `undefined` until the API request starts.

<details><summary>Click here to see code references</summary>

https://github.com/WordPress/gutenberg/blob/752d7759b373a1e748cabdc7f04cefcd99ccb684/packages/core-data/src/selectors.js#L42-L46
https://github.com/WordPress/gutenberg/blob/752d7759b373a1e748cabdc7f04cefcd99ccb684/packages/data/src/redux-store/metadata/selectors.js#L67-L69
https://github.com/WordPress/gutenberg/blob/752d7759b373a1e748cabdc7f04cefcd99ccb684/packages/data/src/redux-store/metadata/selectors.js#L8-L27

</details>

In the following logs, you can see how the `isResolving` status and other related variables, change in different renders right after changing the URL of the embed.

<details><summary>Click here to see logs</summary>

1. Changing URL: `{"new": "https://www.youtube.com/watch?v=ssfHW5lwFZg", "previous": undefined}`

2. `{"fetching": false, "hasPreview": false, "isResolving": undefined, "url": "https://www.youtube.com/watch?v=ssfHW5lwFZg"}`
Right after the URL changes, the `getEmbedPreview` selector is called but the `isResolving` status remains `undefined` for a couple of renders.

3. `{"fetching": true, "hasPreview": false, "isResolving": true, "url": "https://www.youtube.com/watch?v=ssfHW5lwFZg"}`
When the resolver of the `getEmbedPreview` selector is triggered and the API request starts, the `isResolving` status changes to `true`, as well as the result of `isRequestingEmbedPreview` returned in the "fetching" variable.

4. `{"fetching": true, "hasPreview": true, "isResolving": true, "url": "https://www.youtube.com/watch?v=ssfHW5lwFZg"}`
At this point, the API request finished as the preview is ready (`hasPreview` is `true`), but the `isResolving` status is still `true`. Looks like it requires another cycle to update the value.

5. `{"fetching": false, "hasPreview": true, "isResolving": false, "url": "https://www.youtube.com/watch?v=ssfHW5lwFZg"}`
Once the preview is ready and the resolver has finished, `isResolving` and `fetching` are `false`. This value will remain until the cached value is invalidated.

</details>

Following the approach I did for the reusable block to determine the loading state ([reference](https://github.com/WordPress/gutenberg/blob/4b02914c44c5b65db1533de20570999ab033e901/packages/block-library/src/block/edit.native.js#L88-L94)), I'm going to check if the resolver has finished for this purpose. So the following `isResolving` values, `undefined` and `false`, will tell us if the embed preview is being fetched after the URL changed. I'll open a new PR with this workaround and reference it here 🎊 .

**Comment by fluiddot** [comment]
> Following the approach I did for the reusable block to determine the loading state (reference), I'm going to check if the resolver has finished for this purpose. So the following isResolving values, undefined and false, will tell us if the embed preview is being fetched after the URL changed. I'll open a new PR with this workaround and reference it here 🎊 .



@jd-alexander here is the PR https://github.com/WordPress/gutenberg/pull/35798 regarding the new approach for this issue, let me know if you could take a look, thanks 🙇 .

**Comment by jd-alexander** [comment]
> > Following the approach I did for the reusable block to determine the loading state (reference), I'm going to check if the resolver has finished for this purpose. So the following isResolving values, undefined and false, will tell us if the embed preview is being fetched after the URL changed. I'll open a new PR with this workaround and reference it here 🎊 .
> 
> 
> 
> 
> 
> 
> 
> @jd-alexander here is the PR https://github.com/WordPress/gutenberg/pull/35798 regarding the new approach for this issue, let me know if you could take a look, thanks 🙇 .

Thanks @fluiddot I will take a look. Thanks for the logs and explanation here about the root cause of the issue.

**Comment by fluiddot** [comment]
Closing this PR in favor of https://github.com/WordPress/gutenberg/pull/35798.

**Pull request closed without merging**
