### PR TITLE
Navigation block: check that the modal is set before using `contains`

### PR DESCRIPTION
**Pull request by luisherranz**
## What?

The context property that stores the modal can be `null`, so we should check that it's not `null` before using `contains`.

## Why?

I saw an error in the console while testing the menu. 

## How?

Just use the `?` optional property access operator.

## Testing Instructions

Unfortunately, I was not able to find the steps to reproduce it again.

### CODE REVIEW

**Comment by SantosGuillamot** [comment]
I believe the forced push, or the rebase, affected the PR. There are many changes that I think are not relevant to this 😄

**Comment by luisherranz** [comment]
I fixed it. Let's see if tests finally pass.

**Comment by luisherranz** [comment]
Tests finally passed, I need an approval 🙂

**Review by Mamaduka — APPROVED** [review]

**Comment by luisherranz** [comment]
Thank you, @Mamaduka! 😄

**Pull request merged**
