### PR TITLE
[Tiny PR] Add updated README files during precommit

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Currently, `README.md` files are updated during `precommit`, but the changes are not added. This has been annoying me for a while. Only later on you realise that there are unstaged changes created by `./bin/update-readmes.js` and then you need to commit them separately.

Here I've added `git add .` after `node ./bin/update-readmes.js`. Note that this doesn't add any other unstaged changes as they are stashed.

## How has this been tested?

Update some documentation that would be added to a `README.md` file. Commit the change. Ensure that the automated `README.md` change is part of the commit.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
Tested and yes thank you that was annoying :) especially when you are not used to a stack that automagically does so many things.

**Comment by youknowriad** [comment]
This s a very dangerous change IMO, I often have changes locally that I don't want to commit. I'd prefer reverting this personally.

**Comment by ellatrix** [comment]
@youknowriad Oh, I thought it would only add the readme changes as the rest would be stashed. Let me follow up with a PR.

**Comment by aduth** [comment]
I just came across this, since I'm in the same situation as described by @youknowriad and am unable to make a partial commit of files 😬

**Comment by ellatrix** [comment]
@aduth Ok, sorry, I'll work on a fix right away. I thought I saw the unstated changed stashed but apparently they are not.

**Comment by aduth** [comment]
> @aduth Ok, sorry, I'll work on a fix right away. I thought I saw the unstated changed stashed but apparently they are not.

No rush. I managed to get around it by temporarily reverting the changes from this branch.

More of a "+1" if anything, though I suppose I could have just as well used reactions for that. Sorry to pile on!

**Comment by ellatrix** [comment]
Created a PR to revert the change.

**Pull request merged**
