### PR TITLE
Disable pointer events on unselected iframe

### PR DESCRIPTION
**Pull request by ellatrix**
See #1002. Props @westonruter.

### CODE REVIEW

**Comment by iseulde** [comment]
Note: the `iframe-overlay` is not used anywhere atm.

**Comment by jasmussen** [comment]
Nice! Seems to work as intended. That is, when you click it the first time, it doesn't start, it selects the block. Nice. Clicking the second time, starts the video.

Are we sure we want the latter? Do we want to let you play the video in the editor at all? I have no strong opinion here, and I defer to those of you with good arguments on hand.

If we do want to allow it, though, I noticed that the invisible area to the left and right of the inline toolbar is unclickable no matter any preceeding clicks. This area:

screen shot 2017-06-06 at 13 15 25

Not a deal breaker, but if we do want to allow the video to play, we should consider making that area clickable also.

**Comment by iseulde** [comment]
I'll look into the issue. Yeah, maybe let's see how this goes, and if we still want to block interacting with  selected iframes at a later point, we can. :)

**Comment by iseulde** [comment]
Okay, I have to admit that it would not be as straightforward as I thought. It looks like we're better off with some kind of wrapper component like `<ClickToPlay message="..." icon="..." />` because embedding a tweet does not create an iframe. Or just a wrapper component to block interaction entirely for the time being.

**Comment by iseulde** [comment]
I'll close this PR as the approach does not accomplish what was intended.

**Pull request closed without merging**
