### PR TITLE
Replace "Add new post" link text with more meaningful Label

### PR DESCRIPTION
**Pull request by carstingaxion**
## What?

This PR replaces the static "*Add new post*" link text inside the the query block, with a more meaningful label from the currently selected post type.

## Why?

This PR is [polishing the existing UI](https://github.com/WordPress/gutenberg/pull/27732) with data, that is already available, without introducing any new elements. 

## How?

Removes a static text string, with the `add_new_item` label from the currently selected post type.

## Testing Instructions

1. Open a post or page.
2. Insert a query block.
3. Open the inspector controls
4. Switch the queried post type
5. And see the link text change, depending on the selected post type, within the `CreateNewPostLink` element.

### Testing Instructions for Keyboard

*Test can be done by keyboard as well, without any additions to my **Testing Instruction**.*

### Before

https://github.com/WordPress/gutenberg/assets/198883/a2bdb869-305a-448d-b47c-7a201db8dfdb

### After

https://github.com/WordPress/gutenberg/assets/198883/593ee111-2674-400c-9bac-420b68fa4578

### CODE REVIEW

**Comment by carstingaxion** [comment]
Thanks for taking a look @torounit! Please let me know if I can do, provide or change anything.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think the approach itself makes sense, but I think it's recommended to use `useSelect` hook instead of using `select()` directly in React components.

```javascript
const CreateNewPostLink = () => {
	// ...
	const addNewItemLabel = useSelect(
		( select ) => {
			const { getPostType } = select( coreStore );
			return getPostType( postType )?.labels?.add_new_item;
		},
		[ postType ]
	);
	// ...
};
```

Furthermore, in this case, it is assumed that `postType` is not `null`, so I think the following line should be removed:

https://github.com/WordPress/gutenberg/blob/447c008972c021dad1eac9c57933649dcc23a803/packages/block-library/src/query/edit/inspector-controls/create-new-post-link.js#L11

Instead, I think it's better to avoid rendering the `CreateNewPostLink` component itself if `postType` is falsy:

```javascript
{ !! postType && (
	<BlockInfo>
		<CreateNewPostLink postType={ postType } />
	</BlockInfo>
) }
```

Also notice that the prop has been changed to only `postType`. `CreateNewPostLink` component only handles `postType` as a prop, but this should eliminate nested destructuring of props.

If you have any questions, please feel free to comment 👍

**Comment by carstingaxion** [comment]
Wow. Thank you @t-hamano ! Thank you very much for your detailed review and your explicit suggestions on what to improve AND why. 

For sure I'll update my PR.

**Comment by carstingaxion** [comment]
OH no.

**Comment by t-hamano** [comment]
Hi @carstingaxion,

Don't worry about a lot of commit history being added to this PR or a lot of people being notified 😄

If you are concerned about making new changes to this PR, you can close this PR, check out the latest trunk branch again, and submit a new PR with your changes.

**Comment by carstingaxion** [comment]
> Don't worry about a lot of commit history being added to this PR or a lot of people being notified 😄

Thank you for your empathic comment @t-hamano , yes I was a little thrilled.

> If you are concerned about making new changes to this PR, you can close this PR, check out the latest trunk branch again, and submit a new PR with your changes.

That is, what I'll do now.

**Pull request closed without merging**
