### PR TITLE
Fix document title text wrapping and centering.

### LINKED ISSUE #25942: Document title in document actions area wraps text too early
**Describe the bug**
When the title in the document actions area is too long, it wraps very easily. This causes visual issues and overlaps with the template part title.

**To reproduce**
1. get fse set up
2. navigate to the site editor
3. inspect the document title area, and change the title div to have a lot of text
4. select template part
5. see error

**Expected behavior**
The text should not wrap at all. If the text is too long, it should probably be truncated. However, in this situation, the text isn't even "too long", it just wraps very early.

**Screenshots**
Template part selected:
Screen Shot 2020-10-07 at 8 06 06 PM

Nothing selected:
Screen Shot 2020-10-07 at 8 06 10 PM

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Fixes #25942 by moving the absolute positioning from the title to the newly introduced title-wrapper.  Also requires a nowrap declaration.

In the future we may still want to enable a max-width for this component in general and cutting off the overflow of text on the right hand side.  This might be a bit tricky with the current absolute positioning approach, and may require redoing the animations as well if we need to change that positioning.

## How has this been tested?

* Enable FSE and open the site editor.
* select a template part
* use devtools (or any other method) to make the text for the primary name sufficiently longer.
* verify the text does not wrap and stays centered.

## Screenshots 
Screen Shot 2020-10-09 at 2 00 56 PM

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jeyip** [comment]
The text doesn't wrap and it _does_ stay centered, but it also looks like the absolute positioning causes some overlap depending on the length of the template name or the width of the viewport.

Screen Shot 2020-10-09 at 11 27 18 AM

**Comment by Addison-Stavlo** [comment]
>  some overlap depending on the length of the template name or the width of the viewport.

Yeah, this is pre-existing though.  Id be in favor of merging a fix like this to fix the wrapping/centering that got garbled (I think some of that is my fault from the h1 wrapper PR).  And we can look into how to reorganize to handle max-width/overflow in a follow up?

I also wonder how much of an issue the width is for the template name.  With most pre-existing template names that are used in template resolution I wouldn't expect them to be ridiculously long? 🤔   And the long template part name may be easier to handle given its not absolutely positioned.

**Comment by Addison-Stavlo** [comment]
> (I think some of that is my fault from the h1 wrapper PR)

I totally messed up the centering when I did that:
Screen Shot 2020-10-09 at 3 36 40 PM

Its ugly and I cant bear looking at it 🤣

**Comment by Addison-Stavlo** [comment]
closing this PR as https://github.com/WordPress/gutenberg/pull/25757 changed the dom structure and fixed the centration.  Will still need to follow up to properly handle the wrapping and overflow

**Pull request closed without merging**
