### PR TITLE
Image block: Fix focus style not around whole image when linked

### LINKED ISSUE #62544: Image block: Focus style not around whole image when linked
### Description

When the image block is linked the focus style for the link does not stretch around the whole image. This happens because both `a` (anchor) and `img` (image) tags have `display: inline` by default.

### Step-by-step reproduction instructions

1. Open a clean installation of WordPress with a block theme, e.g. on https://playground.wordpress.net/ with current WordPress `6.5.4`.
2. Insert an image block and link the image with a URL.
3. Tab to the linked image using the keyboard in the frontend.
4. The link's outline will not stretch around the whole image.

### Backend
grafik

### Frontend (with WordPress twenty-twentyfour)
grafik

### Should look like this
grafik

(The outline should also have a second color or whitespace towards the image, but that's a problem of the twenty-twentyfour theme focus style and not the same issue as the stretching around the anchor.)

### Environment info

- Firefox 126.0.1 & Chrome 125.0.6422.142
- MacOS 14.5
- WordPress 6.5.4 on Playground
- No special Gutenberg version installed

- I could also recreate it with Gutenberg at commit ee30a87abd733d00338730eed831cfc02d27edf0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by amitraj2203**
## What?
Fixes: #62544 

## Why?
When the image block is linked the focus style for the link does not stretch around the whole image.

## How?
Adds display property to `Image` block and `Media & Text` block.

## Testing Instructions

1. Open a post or page.
2. Insert Image or media & Text block.
3. Link the Image with a link and open the post/page in frontend.
4. Use the tab button to go to that Image and see the focus style is wrapping to whole Image now.

## Screenshots or screencast 
https://github.com/WordPress/gutenberg/assets/77401999/25dbf467-38f8-4303-83dc-c2f6e83cbcea

### CODE REVIEW

**Comment by amitraj2203** [comment]
Hi @t-hamano, can you please review this PR?

Thanks

**Comment by talldan** [comment]
@amitraj2203 This seems to work for most use cases, but in testing I'm seeing an issue with image blocks that are aligned full no longer having the right alignment (tested in Firefox):

In trunk:
Screenshot 2024-06-19 at 4 33 16 pm

In this PR:
Screenshot 2024-06-19 at 4 31 33 pm

**Comment by amitraj2203** [comment]
@talldan I have fixed it. Can you please verify it again.

**Review by t-hamano — COMMENTED** [review]
Thanks for the ping!

I tested this PR and the focus outline looks incorrect in the Image block when the image size is less than the content.

image

How about going back to `display: inline-block` and applying 100% width only for wide and full width?

```diff
diff --git a/packages/block-library/src/image/style.scss b/packages/block-library/src/image/style.scss
index 913cf48b90..fadb52e594 100644
--- a/packages/block-library/src/image/style.scss
+++ b/packages/block-library/src/image/style.scss
@@ -1,7 +1,7 @@
 .wp-block-image {
 
-       > a {
-               display: block;
+       a {
+               display: inline-block;
        }
 
        img {
@@ -32,6 +32,11 @@
                text-align: center;
        }
 
+       &.alignfull a,
+       &.alignwide a {
+               width: 100%;
+       }
+
        &.alignfull img,
        &.alignwide img {
                height: auto;
```

**Comment by amitraj2203** [comment]
@t-hamano Thanks for reviewing PR. I have addressed the changes.

**Review by t-hamano — COMMENTED** [review]
Thanks for the update!

I tried various variations and found that they only solved the focus issue and didn't introduce any new layout or size issues.

This may seem like a small thing, but the `&__` style isn't used much in the Gutenberg project.

We might want to change the syntax as follows:

```diff
diff --git a/packages/block-library/src/media-text/style.scss b/packages/block-library/src/media-text/style.scss
index 2828ea507f..de020611b3 100644
--- a/packages/block-library/src/media-text/style.scss
+++ b/packages/block-library/src/media-text/style.scss
@@ -12,10 +12,6 @@
        &.has-media-on-the-right {
                grid-template-columns: 1fr 50%;
        }
-
-       &__media > a {
-               display: inline-block;
-       }
 }
 
 .wp-block-media-text.is-vertically-aligned-top {
@@ -72,6 +68,10 @@
        /*!rtl:end:ignore*/
 }
 
+.wp-block-media-text__media a {
+       display: inline-block;
+}
+
 .wp-block-media-text__media img,
 .wp-block-media-text__media video {
        height: auto;
```

**Comment by amitraj2203** [comment]
@t-hamano Thanks for the review. Updated it.

**Review by t-hamano — APPROVED** [review]
LGTM!

**Pull request merged**
