### PR TITLE
Update: Post publish buttons and alignment.

### PR DESCRIPTION
**Pull request by juanfra**
👋 Hello gutenfriends,

## Description

I have implemented the changes proposed in this issue: https://github.com/WordPress/gutenberg/issues/19175

The idea is to have a more clean and clear layout for the publish panel.

## How has this been tested?

I have tested the changes by opening the page editor, and trying to publish a page. Checking that the buttons respond as they should, and that the changes represent the decisions taken in the issue. I have also ran tests, and update snapshots.

*Tested:*

- Opened the page editor.
- Added title and text block. 
- Hit "Publish" button.
- Confirm that there's two buttons: "Publish" and "Cancel". Hitting "Publish" will indeed publish the page and open the confirmation panel, with the "Close" button. Hitting "Cancel" will close the panel.
- I have also tested scheduling the page.

## Types of changes

- Updated block code to use the button without icon.
- Updated the block code to act as the designs proposed in the issue.
- Updated the code CSS to make that section look as the designs. Also removed the block code that is irrelevant due to these new changes.
- Updated snapshots.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by paaljoachim** [comment]
Great work @juanfra !

Here is an animated gif of what it looks like:
Publish-flow-buttons

**Comment by folletto** [comment]
Nice work.
Unfortunately the screenshot doesn't seem to load, can you update it?

From the gif it seems the buttons aren't aligned to the content tho:
Screenshot 2020-05-20 at 12 37 21

Can we make sure the left and right margins are aligned with the text below?

**Comment by juanfra** [comment]
Thank you both for taking the time to look at this!

It seems that the gif I initially posted was too heavy for GitHub, sorry for that. I'm adding a new one now.

With regards to the alignment, great catch! that was the original padding for the panel header. Adjusted that to have the same as the other elements of the panel.

**Comment by folletto** [comment]
Looks good to me now 👍

**Comment by paaljoachim** [comment]
An update.
I mentioned the PR for Andrei @draganescu and he told me that the testing needs to be fixed in relation to the testing. @juanfra let us know if you need help with this part. This is Juanfra's first contribution to Gutenberg! Yayy! Which also means he might need some extra help.

**Comment by juanfra** [comment]
Thanks @paaljoachim! Started checking the code here a couple weeks ago and I'm excited to start contributing if possible.

Yes, at first I wasn't aware of the e2e tests so I only ran the basic `npm test`, updated snapshots and committed the proposed changes.

Then, once the PR was in place and I saw the results from travis I found out there were more. But, as the failing tests are part of the experiments folder, related to full site editing and multi entity saving I thought they weren't related to my changes (But I haven't had the time to check the entire codebase to see if the saving panel for the editor is being used elsewhere).

So Today I had a free hour and I tried to debug a bit further, but when I run e2e tests locally, there are a ton failing. So I guess I'm probably missing something. Any recommendations @draganescu?

**Comment by juanfra** [comment]
**Update:** Used the rest of my free hour to check this out and it should be good to go now. 

Thank you both!

**Review by kirilzh — APPROVED** [review]

**Comment by kirilzh** [comment]
Nice work. The new buttons look really good. 🎉 

Approved your PR. @juanfra please resolve the any conflicts that have arisen.

**Comment by juanfra** [comment]
Seems that we should wait on this https://github.com/WordPress/gutenberg/pull/23370

**Comment by paaljoachim** [comment]
Hey @juanfra and @kirilzh #23370 has now been merged.
Lets get this PR merged as well..:)

**Comment by juanfra** [comment]
Hi @paaljoachim!

Thanks for the follow-up. Yes, I merged the changes to this branch once it was merged. Everything is passing now, I'm waiting for a new approval + merge from @kirilzh 

Thank you both :)

**Review by kirilzh — APPROVED** [review]

**Comment by paaljoachim** [comment]
Congratulations @juanfra !

**Comment by MichaelArestad** [comment]
Nice job! It's a bit odd at specific screen sizes because the buttons stretch pretty wide. You can see that here:

image

This issue could be resolved by adding a max-width like this:

image

**Comment by juanfra** [comment]
Thanks @MichaelArestad,

Yeah, I agree, I could add that for viewports between `$break-medium` and `$break-mobile`. What number would you set as `max-width`? Not sure how long these words can get on different languages.

I'd be happy to push this fix :)

**Comment by MichaelArestad** [comment]
> Yeah, I agree, I could add that for viewports between $break-medium and $break-mobile. What number would you set as max-width? Not sure how long these words can get on different languages.

@juanfra Good question. I quickly picked an arbitrary number of `160px` that looked about right and it's a multiple of 8. That might be good enough.

**Comment by juanfra** [comment]
Thanks @MichaelArestad! Added a new PR with the changes https://github.com/WordPress/gutenberg/pull/22390

**Pull request merged**
