### PR TITLE
Convert quote to / from pullquote

### PR DESCRIPTION
**Pull request by oandregal**
Addresses https://github.com/WordPress/gutenberg/issues/10548

Adds a transformation to convert `quote` to `pullquote` and viceversa.

### CODE REVIEW

**Review by tofumatt — COMMENTED** [review]
E2E tests for these types of things (just a `toMatchSnapshot()` should work) are always great, sorry to harp on about them!

(Otherwise code looks good to me.)

**Comment by nosolosw** [comment]
@tofumatt how do I prepare a snapshot? I haven't done it before.

_I wouldn't ask if we weren't counting the minutes for the UI freeze because I can google, but :man_shrugging: _

**Comment by talldan** [comment]
@nosolosw There's an example here of using snapshots in e2e tests:
https://github.com/WordPress/gutenberg/blob/master/test/e2e/specs/links.test.js#L55

Typically, when you run jest (`npm run test-e2e` or `npm run test-e2e:watch`) the snapshot files will be created automatically the first time. If the snapshots need to be updated, jest usually tells you in watch mode and you can use the `u` key to update them.

**Comment by tofumatt** [comment]
No worries! `jest` (`npm run test-e2e:watch`) will generate them for you for all new tests. Just write:

```js
expect( await getEditedPostContent() ).toMatchSnapshot();
```

at the end of your test and look for the new snapshot file generated. Ensure the HTML looks like what you expect, commit it, and then you're good. Once it's generated, if the result ever changes jest will yell at you 😄

**Comment by tofumatt** [comment]
@talldan and I are secretly the same person.

**Comment by nosolosw** [comment]
That's cool! Added e2e test in 45f89a9 Will merge after lunch if CI doesn't yell at me.

**Review by tofumatt — APPROVED** [review]
Very nice (tests are the best)! 🚢

**Comment by paaljoachim** [comment]
A z-index issue:
z-index-issue

**Comment by nosolosw** [comment]
@paaljoachim I'm not able to repro ( the popover correctly changes up/down when there is no space ). Tried in both mobile viewports and desktop, scrolling both with the keyboard (arrows) and the mouse (grabbing the scrollbar). Could you provide more details?

**Comment by paaljoachim** [comment]
Hey @nosolosw 

I am trying various things to replicate it, and I am noticing it is difficult to get it the exact same. It seems to happen in certain conditions that I was able to replicate at first but after trying a few variants I am not able to do so again. So I will we will just let it go for now and just call it a gremlin in the system...:) If it comes up again then you atleast know about it.

**Comment by nosolosw** [comment]
@paaljoachim thanks for your testing!

**Pull request merged**
