### PR TITLE
Components: Fix FormTokenField input position when typing

### PR DESCRIPTION
**Pull request by ItsJonQ**
This update improves the internal `input` element's position within the `FormTokenField`. The `input` now aligns (when possible) next the the previous token elements, rather than always jumping to the bottom (when empty).

The fix involved making the `input` width adaptive using Flexbox (`flex: 1`).

For the following screenshots, I've coloured the `input` background to make it easier to see it's position within the `FormTokenField`.

##### Before

Screen Shot 2020-11-05 at 11 37 09 AM

The `input` is at the bottom.

##### After

Screen Shot 2020-11-05 at 11 37 17 AM

The `input` snaps to the left, aligning to the tokens.

## How has this been tested?

Tested locally in Gutenberg.

* `npm run dev`
* Go to a Post
* Add tags
* Ensure that the text caret is (mostly) aligned next to the added tags.

Note: I've noticed that there's still "jumping" with this interaction - more noticeable when entering tags rapidly. This issue existed before this fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
Wut.. E2E 😭

**Review by jasmussen — APPROVED** [review]
For what is two lines of code, this seems like an _unbelievably_ good change. Here's before:

before

Here's after:

after

Ship it as fast as you can!

**Comment by ItsJonQ** [comment]
@jasmussen Thank you for the review! I just rebased with latest `master`. Hopefully the tests will pass 🤞

**Comment by ItsJonQ** [comment]
So far it looks like the test failure is (unfortunately) consistent with the failures on recent commits on `master` (🙈 ).
That being the Static Analysis test.

Everything else looks happy. Based on that assessment, I'm going to merge this up.

Thanks all!

**Pull request merged**
