### PR TITLE
Fix: Add ability to opt out of Core color palette V2

### LINKED ISSUE #36407: Missing ability to remove/override "Core" color palette
### Description

In the original tracking issue from Matias (#29568) it was outlined that

> Of course, it still needs to be possible to fully disable the default palette since sites that have stricter branding guidelines might prefer to remove it entirely, the same way the custom colors interface can be disabled, but it should not be the default behaviour that a theme palette overwrites the color palette.

Looking at the implementation now that does not seem to be the case. 

This is a big problem for custom builds with strict design systems where the litigation to certain brand colors is a very important need that is no longer met without the ability to remove / override that "Core" palette. 

I do understand and agree that the default behavior should be having both paletes. But like @mtias mentioned initially then this was proposed themes should be able to override / remove that. 

### Step-by-step reproduction instructions

There are no steps to reproduce as there is no API to remove the Core palette. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by fabiankaegy**
## Description

Add the ability for themes using `theme.json` to opt out of showing the "Core" color Palette and Core Gradients.

```json
{
	"version": 1,
	"settings": {
		"color": {
			"corePalette": false,
			"coreGradients": false
		}
                "blocks": {
                	"core/heading": {
          			"color": {
            				"corePalette": true,
            				"coreGradiens": true
         			 }
        		}
		}
	}
}
```

This is the second iteration of this PR. See #36447 for more details about the initial approach. 

Closing #36407 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by oandregal — APPROVED** [review]
Nice! Thanks for the quick turnaround, Fabian.

**Comment by fabiankaegy** [comment]
@noisysocks Since the ticket #36407 was on the 5.9 Must-Have Board as a Bug Fix, I am adding the WP 5.9 Backport babel to this PR. Please remove if that was incorrect

**Comment by steveangstrom** [comment]
Will this solve the issue for the huge majority of user with PHP themes, as referenced in  https://github.com/WordPress/gutenberg/issues/36489

My suspicion is "no"

**Comment by oandregal** [comment]
@fabiankaegy I've prepared https://github.com/WordPress/gutenberg/pull/36496 to disable the core palette by default for themes with no `theme.json`.

**Comment by Andrew-Starr** [comment]
This does remove the core palette and gradients from the post editor, but not from the site editor.

Is this intentional or a bug?

**Comment by oandregal** [comment]
Hi Andrew, the fix for the site editor landed in https://github.com/WordPress/gutenberg/pull/36639 which is part of Gutenberg 12.1.

**Comment by skorasaurus** [comment]
to anyone wondering, these have been renamed to from "corePalette" and "coreGradients" to defaultPalette" and "defaultGradients"

**Pull request merged**
