### PR TITLE
Editor: Update hover color of editor document title

### PR DESCRIPTION
**Pull request by nirav7707**
# What?
Follow up to: 
- https://github.com/WordPress/gutenberg/issues/60059

https://github.com/nirav7707/gutenberg/assets/56816580/fcb57e33-7e90-40d6-ac2b-c09176712a79
# Why?
- differentiate from synced assets

### CODE REVIEW

**Comment by richtabor** [comment]
Thanks @nirav7707! 

After testing, I pushed a few small adaptations. 

We don't have a color change when viewing a synced element, I think we should do the same for the unsynced — that way it's a bit clearer that there is a color difference, and they're also more consistent. 

### Visual 

https://github.com/WordPress/gutenberg/assets/1813435/5613cf2d-ba2c-4ec8-a186-501e391e3e2e

**Review by richtabor — APPROVED** [review]
LGTM

**Comment by jameskoster** [comment]
Should we fix the hover color of the `< Back` button while we're here?

Screenshot 2024-03-22 at 15 16 07

**Comment by richtabor** [comment]
> Should we fix the hover color of the < Back button while we're here?

Sure thing. I made it $gray-900 in https://github.com/WordPress/gutenberg/pull/60113/commits/7dfe9ccadf3f0c9d7ab9dda85760f7c0b2ee61dc.

**Review by jameskoster — APPROVED** [review]
Nice. I like the subtle animation.

**Pull request merged**
