### PR TITLE
Navigation: Prepare for hard deprecation

### PR DESCRIPTION
**Pull request by mirka**
## What?

Starts logging a deprecation warning for `Navigation`, with an explicit end version.

## Why?

After passive deprecating (#61099) this component, we have had to do maintenance work on it many times. Given the [low usage](https://wpdirectory.net/search/01JFGKB7PQQNK63ATYAQS7SNFQ), I think it would be beneficial to eventually hard remove this code from the codebase.

## Testing Instructions

✅ Deprecation warning should be logged in the Storybook.
✅ Unit tests should pass.

## ✍️ Dev Note

The `Navigation` component (and all its subcomponents) are deprecated, planned for hard removal in WordPress 7.1. Use the [`Navigator`](https://wordpress.github.io/gutenberg/?path=/docs/components-radiocontrol--docs) component instead.

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
Should we add JS doc `@deprecated` comments [here](https://github.com/WordPress/gutenberg/blob/3133f56f3f99543ed92557d47f364842bd31e94b/packages/components/src/index.ts#L122-L126), similarly to what we've done for other components?

**Review by tyxla — COMMENTED** [review]
I think we can also add a README callout as we do for other hard deprecated components:

```
<div class="callout callout-alert">
This component is deprecated.
</div>
```

**Review by tyxla — APPROVED** [review]
LGTM 👍 

Thanks for writing a dev note proactively 🌟

**Comment by mirka** [comment]
> Should we add JS doc `@deprecated` comments [here](https://github.com/WordPress/gutenberg/blob/3133f56f3f99543ed92557d47f364842bd31e94b/packages/components/src/index.ts#L122-L126), similarly to what we've done for other components?

They were marked in the source files when we first passive deprecated them. It should already be working as expected:

Deprecation warning in IDE

> I think we can also add a README callout as we do for other hard deprecated components:

Also [already done](https://developer.wordpress.org/block-editor/reference-guides/components/navigation/) when we passive deprecated it 👍

**Pull request merged**
