### PR TITLE
Apply i18n functions to Nav block menu drops when selecting existing Menu

### PR DESCRIPTION
**Pull request by getdave**
## Description
When browsing the code I noticed that i18n had been omitted from the `Select existing menu...` dropdown.

This PR fixes that.

## How has this been tested?
Check the UI remains the same as `trunk`.

## Screenshots 

Screen Shot 2021-11-08 at 12 51 25

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]

**Comment by getdave** [comment]
Sorry...merged quickly and didn't edit the commit name. A bit nebulous!

**Comment by getdave** [comment]
@noisysocks What workflow should I follow to get this fix into WP 5.9?

**Comment by ntsekouras** [comment]
>What workflow should I follow to get this fix into WP 5.9?

Add the `backport to WP` label.

**Comment by noisysocks** [comment]
Yep. I'll pick it up next week now that it has the label 🙂

**Comment by andrewserong** [comment]
Cherry picked into the Gutenberg 11.9 release in: https://github.com/WordPress/gutenberg/commit/469b99488ab5c25734d3c6dc929bec6c40012779

**Pull request merged**
