### PR TITLE
[TypeScript] Preserve the generic signature of getEntityRecord and getEntityRecords through currying

### PR DESCRIPTION
**Pull request by adamziel**
Most of the code proposed here once was a part of trunk. It got reverted in a large cleanup PR to reduce the complexity of the types, but unfortunately there is no way around the complex currying method proposed here.

## What problem does this PR solve?

`select( coreStore ).getEntityRecord()` has an incorrect TypeScript signature:

```ts
(kind: string, name: string, key: EntityRecordKey, query?: GetRecordsHttpQuery | undefined) => EntityRecord
```

It's supposed to be the same as the signature of `getEntityRecord` declared in selectors.ts, minus the state argument:

```ts
<
	EntityRecord extends
		| ET.EntityRecord<any>
		| Partial<ET.EntityRecord<any>>
>(
	state: State,
	kind: string,
	name: string,
	key: EntityRecordKey,
	query?: GetRecordsHttpQuery
) => EntityRecord | undefined;
```

This is because [TypeScript doesn't correctly curry generic functions](https://github.com/WordPress/gutenberg/pull/41578):

```ts
type CurriedState = F extends ( state: any, ...args: infer P ) => infer R
    ? ( ...args: P ) => R
    : F;

type Selector = <K extends string | number>(
    state: any,
    kind: K,
    key: K extends string ? 'string value' : false
) => K;

type BadlyInferredSignature = CurriedState< Selector >
// BadlyInferredSignature evaluates to:
// (kind: string number, key: false | "string value") => string number
```

## How does this PR propose to solve it?

This PR explicitly specifies both the curried and the uncurried signature. [This is the only working solution I found](https://github.com/WordPress/gutenberg/pull/41578).

Both signatures are shipped via the `GetEntityRecord` interface:

```ts
export interface GetEntityRecord {
	// Callable signature:
	< EntityRecord >( state: State, /* args */ ): EntityRecord | undefined;

	// Artificial property to couple with the callable signature:
	CurriedSignature: < EntityRecord >( /* args */ ): EntityRecord | undefined;
}
```

Then, the currying code in `@wordpress/data` gives `CurriedSignature` precedence over automatically currying the selector.

This commit also includes a docgen update to add support for typecasted selectors, otherwise CI shows a fatal error.

## Testing Instructions
Create the following test file and confirm it behaves in line with the screenshots below:

```ts
// Create a temporary file: packages/core-data/src/test.ts
import { useSelect } from '@wordpress/data';
import { store } from './index';
import type { Attachment } from './entity-types';

export function ReactComponent() {
    const attachment = useSelect(store, []).getEntityRecord<Attachment<'edit'>>('', '', '');
    return attachment?.title.rendered;
}
```

## Screenshots or screencast 

**Before:**
CleanShot 2022-09-26 at 18 54 54@2x

**After:**
CleanShot 2022-09-26 at 18 46 51@2x

cc @dmsnell @gziolo @noisysocks

### CODE REVIEW

**Review by dmsnell — APPROVED** [review]
Seems fair to bring this back, and thanks for the `docgen` fix. I don't suppose we would want to put these in separate PRs would we?

**Comment by adamziel** [comment]
I can think of reasons both to split them, as they address separate packages and could be used independently, and to keep them in the same PR, as today one is only needed because of the other. I feel like splitting them would be the correct way to do it, but it's not a big diff and it don't think it will matter that much – I'll just merge this PR and ship both in one commit.

**Comment by adamziel** [comment]
cc @michalczaplinski – this one needs a backport.

**Comment by michalczaplinski** [comment]
@ockham Does this one need to be cherry picked manually into the `wp/6.1` branch or was this picked up by the script and published to npm already? 🤔

**Comment by adamziel** [comment]
@michalczaplinski the script automatically comments on the PRs it picks up. I also don't see this PR on the [list of commits in the `wp/6.1` branch](https://github.com/WordPress/gutenberg/commits/wp/6.1).

**Comment by michalczaplinski** [comment]
Thanks for clarifying @adamziel! I haven't had the chance to run the script myself so wasn't quite sure how it works :) Bernie was kind enough to show me today 👍

**Comment by michalczaplinski** [comment]
Cherry-picked for the 6.1 release in https://github.com/WordPress/gutenberg/pull/44656

**Pull request merged**
