### PR TITLE
Docs/iAPI: Fix wrong code snippets in API reference

### PR DESCRIPTION
**Pull request by atachibana**
## What?

The snippets in the API reference contain some errors:

wp-context sample
- missing quotes

wp-init sample
- Since getElement() appears for the first time on this page, it should be mentioned that this function needs to be imported.
- `</>` should be `</p>`

Derived state sample
- Last comma should be semi colon.

getElement sample
- invalid comment and output json

withScope sample
- missing bracket

wp_interactivity_process_directives
- wrong namespace

Some minor typos were also fixed.

### CODE REVIEW

**Review by shail-mehta — APPROVED** [review]
LGTM 👍

**Comment by atachibana** [comment]
@shail-mehta 
Thank you. Can I ask this merge?

**Comment by shail-mehta** [comment]
@atachibana

Could you please rebase the branch with the trunk so I can merge it?  (`</p>` tag closing issue was fixed in last week. I apologize, I didn't notice this PR at that time.)

**Comment by atachibana** [comment]
@shail-mehta 
I have updated it. I hope this can be merged correctly.

**Comment by shail-mehta** [comment]
Thanks for the Update @atachibana.

**Pull request merged**
