### PR TITLE
Update gallery markup for using list

### PR DESCRIPTION
**Pull request by samikeijonen**
## Description
Update gallery block for using list markup. See issue #2900.

There is also lot's of small CSS changes. Note that I didn't implement `alignleft` or `alignright` styles yet. It needs further investigation if we decide to go with this markup.

## How Has This Been Tested?
- Tested with several default themes and random .org themes.
- Tested with 1 - max columns.
- Run `npm test` without errors.

## Types of changes
- Markup changes to list format.
- CSS changes because of markup changes.
- CSS class name for list item, I suggest `blocks-gallery-item`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by samikeijonen** [comment]
@afercia This is the first patch for switching list format in gallery block. As usual Screen readers don't announce this as list because there is `list-style-type: none` (and probably `flex` also).

Even if I tested adding `role="list"` list item count was not right. I had 5 images in the gallery and VoiceOver announced `List 2 items`. Which is weird.

**Comment by afercia** [comment]
Tested a bit, from a semantics and accessibility perspective this would be a very nice improvement.

Historically, the gallery markup in WordPress has always been not so ideal. Even the HTML5 one. A gallery is basically a list of images. Marking it up as a list would provide important information about the number of items in the list.

Screen readers would announce the total number of items, and also announce `n of n` for each item.

When testing this, please consider Safari has a bug (probably Apple would call it a "feature") and when list are styled with `list-style: none` it doesn't expose the list as a list. VoiceOver won't be able to announce the list information. Adding a redundant `role="list"` is a workaround, and WordPress is already doing that in a few places. However, it would be fixing a browser bug that should be fixed upstream, so basically a hack around a bad browser's behavior. Here's how it would work adding a `role="list"` to the `<ul>` element:

screen shot 2017-11-13 at 18 40 47
screen shot 2017-11-13 at 18 45 43

**Comment by samikeijonen** [comment]
Thanks for testing @afercia!

> Even if I tested adding role="list" list item count was not right. I had 5 images in the gallery and VoiceOver announced List 2 items. Which is weird.

As you mentioned in the Slack it was about the missing `alt` texts. Which means that VoiceOver doesn't announce images without `alt` text.

**Comment by afercia** [comment]
> Which means that VoiceOver doesn't announce images without alt text.

Not sure, in a first test one of the images in my gallery had no alt text and VoiceOver announced the filename (as it is supposed to do). It can depend on many factors like settings, or the specific filename :)

**Comment by aduth** [comment]
Related: #2541

**Comment by afercia** [comment]
As I see it, the sooner this change happens, the better. An image gallery is basically a _list_ of images and as such should be marked up as a list. Apart from the current merge conflicts, it would be nice to have some feedback here 🙂

**Comment by jasmussen** [comment]
Thanks for the PR! 

I apologize in advance for being lazy, but it's easier to test and review PRs when they're branched off of master as opposed to forked. ;)

Markup change seems fine to me. I noticed the move to a negative left margin instead of negative right margin, that seems fine, though I've recently in another PR changed the .blocks-gallery-image to have an even 8px margin all around, and then a negative 8px margin all around the container. This makes for a cleaner outline, but we just have to remember to fix that in rebases. 

As such, 👍 👍  to the markup change, especially if it improves accessibility (thank you!), but I'd defer to @aduth or @youknowriad on how to best roll this out in a non-disruptive manner.

**Comment by samikeijonen** [comment]
For me it would probably be just easier to create fresh PR. If someone have extra time, feel free to do it :)

**Comment by jasmussen** [comment]
Opened this one: #3996.

Perhaps we can close this one?

**Comment by samikeijonen** [comment]
I fixed merge conflicts and tried deprecate fallback in 62f2f4d7f81d94775eb3ec14cdf745b8b29cf161 but I think it's not working.

**Comment by jasmussen** [comment]
@samikeijonen in https://github.com/WordPress/gutenberg/pull/3996 I tried to create a brand new pull request for you where I ported your changes so you don't have to fix merge conflicts in this one. Can you test if that's working for you?

**Comment by samikeijonen** [comment]
@jasmussen I noticed it but forgot it after holidays! Working with this or #3996 are both fine by me.

**Comment by Soean** [comment]
#3996 was merged to we can close the PR

**Pull request closed without merging**
