### PR TITLE
fix: update block category to design and build documentation.

### PR DESCRIPTION
**Pull request by snehapatil2001**
Issue: https://github.com/WordPress/gutenberg/issues/60930

### Issue
The experimental Table of Contents block in the Gutenberg repository is using the category "layout" in its `block.json` file. However, "layout" is not listed as a valid block category according to the `block.json` schema. The valid categories are:
- "text"
- "media"
- "design"
- "widgets"
- "theme"
- "embed"

### Solution
This **PR** resolves the issue by changing the category of the Table of Contents block from "layout" to "design", which is one of the valid categories listed in the schema. This ensures that the block complies with the schema and avoids any validation issues.

### Changes
- Updated the `block.json` file for the experimental Table of Contents block to change the category from "layout" to "design".
- Build Documentation.

### Tests
- [x] Verified that the block appears correctly under the "design" category in the block inserter.
- [x] Checked that the block functions as expected without any validation errors.

### CODE REVIEW

**Review by fabiankaegy — APPROVED** [review]
Great catch. Thanks for the fix :)

**Comment by snehapatil2001** [comment]
@fabiankaegy  Do I have to make any more changes or is it good to be merged??

**Comment by akasunil** [comment]
@snehapatil2001  Yes, it ready for merge once all checks are passed. I see some tests are still pending, Can you sync with trunk? that might resolve it.

**Comment by snehapatil2001** [comment]
@akasunil Synced up with trunk.

**Comment by t-hamano** [comment]
Hi @akasunil, 

When you merge the pull request, please paste the props mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/61905#issuecomment-2127156404) into the commit message.

**Pull request merged**
