### PR TITLE
Fix: Broken link in "Updating to New Release" section

### PR DESCRIPTION
**Pull request by gregrickaby**
## Description
The links to the changelog were 404-ing. I pointed them to the correct URL on Github.

### CODE REVIEW

**Review by Soean — APPROVED** [review]

**Comment by gziolo** [comment]
Can you provide more details in which context it shows 404? I tried on GitHub and npm and they properly link opening the changelog file.

**Comment by Soean** [comment]
@gziolo They are broken in the handbook: https://developer.wordpress.org/block-editor/packages/packages-scripts/#updating-to-new-release

**Comment by gregrickaby** [comment]
@gziolo Just agreeing with @Soean, the links are in the Handbook: https://developer.wordpress.org/block-editor/packages/packages-scripts/#updating-to-new-release

Sorry I should have mentioned that in my original PR note.

**Review by gziolo — APPROVED** [review]
Cool, it makes sense then 👍

**Pull request merged**
