### PR TITLE
[ Latest Posts ] Fixes the read more link added by themes in Latest Posts

### LINKED ISSUE #20511: [ Latest Posts ] The "Continue reading" link added to excerpts by some default themes has the wrong URL
**Describe the bug**
Some default themes (Twenty Thirteen through Twenty Seventeen) use the `excerpt_more` filter to add a "Continue Reading" link at the end of trimmed excerpts. They all use basically the same function, which looks like this:

```php
$link = sprintf(
	'<p class="link-more"><a href="%1$s" class="more-link">%2$s</a></p>',
	esc_url( get_permalink( get_the_ID() ) ),
	/* translators: %s: Name of current post */
	sprintf( __( 'Continue reading<span class="screen-reader-text"> "%s"</span>', 'twentyseventeen' ), get_the_title( get_the_ID() ) )
);
```

When this filter is applied to excerpts in the context of the Latest Posts block, however, the context of the global `$post` object is not what the theme function expects, so `get_the_ID()` is picking up the ID of the post or page where the Latest Posts block is located, rather than the post that is being rendered within the block. Thus, the links appended to excerpts within the block are not linking to the right place.

**To reproduce**
1. Publish a couple of posts with a significant amount of content (so it will get trimmed for the excerpt).
1. Add the Latest Posts block to a page. In Post content settings, turn on Post content, and then ensure that the Excerpt is the type of content to show.
1. With Twenty Sixteen activated, view the page. The "Continue Reading" links do not link to the actual posts. (The other problem, of there being two links at the end of the excerpt, is described in #20510)

**Expected behavior**
Perhaps if the `render_block_core_latest_posts()` function used `setup_post_data()` within its loop for rendering each post item, the links would contain the correct URLs. But I haven't tested this.

**Desktop (please complete the following information):**
- OS: macOS Catalina
- Browser: Firefox 73
- WP: 5.3.2
- Gutenberg: 7.6.0

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Closes #20511

## How has this been tested?
1. Use the twenty sixteen theme
2. Create a post
3. Add a Latest Posts block
4. Set up the block to show excerpts and make sure the excerpt length is set so that read more links show up
5. On the front end you should see the read more link added by the theme.

## Screenshots 

Screenshot 2020-02-28 at 20 18 40

## Types of changes
Non breaking changes in `LatestPosts` front end rendering.

### CODE REVIEW

**Comment by skorasaurus** [comment]
Thanks for the PR and as much as I don't want to unnecessarily block progress (and your PR solves the problem for my custom theme), [this PR](https://github.com/WordPress/gutenberg/pull/20541/commits/cdeee6f9185270c3d42076c42cab6e2cd9b647b0) does have a blocker: 

Gutenberg now ignores the [excerptLength](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/latest-posts/edit.js) that is configured by the user within the block's inspector control. 

The excerpt length on the front end (the render block viewed by the user) is [now always 55, the default for an excerpt](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-includes/formatting.php#L3804) regardless what the user sets in the block's inspector control/panel.

**Comment by draganescu** [comment]
Hi there @skorasaurus I am not sure which PR you linked to. This one here does nothing to the length setting. Maybe wrong link?

**Comment by draganescu** [comment]
hi there @skorasaurus after a rebase the fix in master is in this PR as well. The length is now respected via a new filter used at render time in the `LatestPosts` block.

**Comment by skorasaurus** [comment]
Thanks, I confirm the read more links are fixed as well as the excerptLength that is defined by the user in the block editor.

**Review by talldan — APPROVED** [review]
@draganescu and I had a discussion about this change, so just replicating my thoughts here.

This change does alter the behavior of the block (in addition to fixing the bug), so worth documenting that.

The block's output in the post now respects the `excerpt_more` filter, so for some themes this improves things. It also introduces consistency, so the excerpts produced by the block match those elsewhere on the site.

However, the way the block appears in the editor is now inconsistent with what's displayed in the post. Additionally, some themes that don't use `excerpt_more` will find that the 'Read more' link is no longer present (e.g. Twenty Twenty, although worth mentioning that this is consistent with the rest of the site).

I don't think there's a win win situation in solving this bug, so I'm approving this, but it'd be good to look at how the editor version of the block can be made consistent with the post in a follow-up.

**Comment by draganescu** [comment]
Thank you @talldan for the summary!

**Pull request merged**
