### PR TITLE
Docs: Update extensibility docs for Editor's UI

### PR DESCRIPTION
**Pull request by gziolo**
## Description
I noticed that we don't have a reference to Editor's UI extensibility docs and we obviously don't have all filters documented. I bet we have more features that should be documented here. Let's work collectively to make it happen. Feel free to take over this PR and improve this content. I'm happy to help to move it forwards with reviews. However, I might not have time to spent too much time on it in the upcoming days.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
@ajitbohra Are you taking it from here on these docs? If you could get a baseline, I can review it from there.

**Comment by ajitbohra** [comment]
@chrisvanpatten yes will get the initial draft ready and ping you.

**Comment by gziolo** [comment]
@kadamwhite and @mikeselander are close to provide 2 new filters. Let's make sure they are included in this new document.

**Comment by gziolo** [comment]
#11184 has landed, I updated the stub file to include them with 3fba988.

**Comment by ecobux** [comment]
See also #6225

**Comment by gziolo** [comment]
It looks like those changes should land now in this file: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/filters/editor-filters.md.

**Pull request closed without merging**
