### PR TITLE
Docs: Add info about npm release types and their schedule

### LINKED ISSUE #18075: Documentation: Make it easier to check when the next npm release is scheduled
There are some existing documents which contain the necessary details, but they are hard to discover and aren't properly cross-linked:
- https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#packages-releases-and-wordpress-core-updates
- https://github.com/WordPress/gutenberg/blob/master/packages/README.md#releasing-packages

There is also https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/packages.md which doesn't contain any reference.

There is also this roadmap issue (https://github.com/WordPress/gutenberg/issues/15068) pinned and displayed on the issues page:
Screen Shot 2019-10-23 at 13 15 41

We could include the details about the major WordPress releases and how it impacts npm releases.

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Depends on #29379.

Fixes: #18075.

> There are some existing documents that contain the necessary details, but they are hard to discover and aren't properly cross-linked:
> 
> -  https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#packages-releases-and-wordpress-core-updates
> - https://github.com/WordPress/gutenberg/blob/master/packages/README.md#releasing-packages
>
> There is also https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/packages.md which doesn't contain any reference.

## Types of changes

Documentation.

You can browse the updated sections:

- [Packages Releases to npm and WordPress Core Updates](https://github.com/WordPress/gutenberg/blob/b1f60e2ac37db8cb7fa523855f4cc4b95ab9258d/docs/contributors/release.md#packages-releases-to-npm-and-wordpress-core-updates)
- [Development Releases](https://github.com/WordPress/gutenberg/blob/b1f60e2ac37db8cb7fa523855f4cc4b95ab9258d/docs/contributors/release.md#development-releases)

### CODE REVIEW

**Comment by gziolo** [comment]
@adamsilverstein and @nerrad, I think that most of the content added in this PR would nicely convert to a very informative blog post at https://make.wordpress.org/core/.

**Review by sirreal — APPROVED** [review]
So is `patch` like long term support (LTS) release? It corresponds to whatever is in WP Core latest? I didn't know we were doing anything like that 🙂

**Comment by gziolo** [comment]
> So is `patch` like long term support (LTS) release? It corresponds to whatever is in WP Core latest? I didn't know we were doing anything like that 🙂

It isn't only for the current major release of WordPress but also for the previous versions that still get security patches. @whyisjake and @desrosj might have the more precise answer here that we should include in the documentation.

**Comment by gziolo** [comment]
I clarified one of the sentences pointed by @adamsilverstein on WordPress Slack in https://github.com/WordPress/gutenberg/pull/29028/commits/1f04452601f4c80c24e6b155b44bb130732f5c84.

**Pull request merged**
