### PR TITLE
Add text-orientation to the typography block support

### LINKED ISSUE #50319: Typography: Add option for vertical text (writing-mode/text-orientation)
Through a combination of `text-orientation: mixed;` and `writing-mode: vertical-rl;`, you can achieve vertical text. This is useful for some writing forms. Shown here, [a 12th century Japanese scroll](https://en.wikipedia.org/wiki/Japanese_language):

Image

Beyond enabling vertically written languages, the orientation can also have decorative properties:

Image

We should consider adding support via the Typography panel. An initial version could be a single directional toggle, similar to that of Layout blocks:

Image

This should be fairly simple to implement, as it's a matter of adding `writing-mode` to paragraphs:

```
writing-mode: vertical-rl;
```

Note that the `rl` part would have to be derived from the general writing direction (LTR needs `vertical-rl`, RTL needs `vertical-lr`).

See also: https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

Depending on the utility, the feature could theoretically be expanded in the future with glyph orientation (text-orientation). But I want to emphasize the following mockup would be a future followup, and the design control and iconography could use feedback:

Vertical text, slightly longer term version with more options

The above would require the addition of `text-orientation: upright;` (where `text-orientation: mixed;` is otherwise a good adaptive default).

See also: https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation

### PR DESCRIPTION
**Pull request by scruffian**
## What?

Adds a text-orientation typography block support, to be combined with the writing mode block support.
Adds support for text-orientation to paragraph blocks.

Follow up to https://github.com/WordPress/gutenberg/pull/50822
Closes https://github.com/WordPress/gutenberg/issues/50319

## Testing Instructions
This setting is disabled by default and can be enabled for themes that include theme.json.

1. In theme.json, under settings > typography, add `writingMode: true` and `textOrientation: true`.
2. Under styles > blocks, add
```
"core/paragraph": {
	"typography": {
		"writingMode": "vertical-rl",
		"textOrientation": "upright"
	}
}
```
3. Activate the theme. Confirm that all paragraphs are vertical and upright, top to bottom.
4. Remove the block style from theme.json.
5. Go to the Site Editor, Styles, Blocks, Paragraph, Typography, and set the writing mode to vertical and text-orientation to upright. Confirm that the styles are applied.
6. Change the writing mode to horizontal and confirm the change is applied.
7. Next, select a paragraph block and find the text orientation setting in the block settings sidebar, typography panel. It should not be displayed by default, but be available from the three dot menu.
8. Confirm that all four writing mode and text orientation options work in the editor and front.
9. Change the site language to use an RTL language, and repeat step 7. 

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/7422055/d579f804-f90f-4fbe-8b94-e044692ae4e4

Props @carolinan  who all the work on this PR

### CODE REVIEW

**Comment by scruffian** [comment]
I think we need to undo this change as well: https://github.com/WordPress/gutenberg/pull/53175

**Comment by Mamaduka** [comment]
Hi, @scruffian

I see the following error when pulling the `trunk`, and then the `pull` command bails out. I had to use `git reset` to pull the latest changes. It could be my local setup, but I wanted to mention it just in case.

```
error: cannot lock ref 'refs/remotes/origin/temp': 'refs/remotes/origin/temp/undefined-index-slug' exists; cannot create 'refs/remotes/origin/temp'
```

## Screenshot
CleanShot 2024-03-17 at 07 45 18

**Comment by talldan** [comment]
Going to close this and delete the branch to hopefully solve the issue mentioned above.

(@scruffian is aware I'm doing this)

**Comment by Mamaduka** [comment]
Thanks, @talldan. Branch deletion resolved the issue on my end.

**Comment by scruffian** [comment]
moved to https://github.com/WordPress/gutenberg/pull/60030

**Pull request closed without merging**
