### PR TITLE
Add README to the useSetting component

### LINKED ISSUE #52079: Add README.md file for use-setting component
## What problem does this address?

The [use-setting component](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/use-setting) is missing a README.md file. As per #22891
## What is your proposed solution?

Pinging original creator of this component @youknowriad . and other recent committers @andrewserong and @ingeniumed, if you have the bandwidth could you add a README.md file for this component. Thank you.

[This README](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/alignment-control/README.md) is a good example to follow.

Please let me know if there's anything I can do to help with the creation of the README.md file for this component.

### PR DESCRIPTION
**Pull request by ingeniumed**
## What?

This will add a README for the useSetting component, with relevant details and examples of usage.

## Why?

This will resolve #52079 

## How?

The README is what's needed to resolve that issue.

## Testing Instructions

N/A

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

N/A

### CODE REVIEW

**Comment by ingeniumed** [comment]
I'm am not able to add the developer-documentation label to this PR unfortunately that would resolve the above problem.

**Comment by juanmaguitar** [comment]
> I'm am not able to add the developer-documentation label to this PR unfortunately that would resolve the above problem.

@ingeniumed label has been added.

Thanks a lot for working on [this issue](https://github.com/WordPress/gutenberg/issues/52079)

**Review by mburridge — APPROVED** [review]
LGTM

**Comment by ingeniumed** [comment]
Thanks for approving it! You would need to merge it in as well, as I don't have permission to merge it unfortunately.

**Comment by mburridge** [comment]
Merged

**Comment by ingeniumed** [comment]
@mburridge - I think you closed the PR instead of merging it in. Would be able to re-open and merge it in?

**Pull request merged**
