### PR TITLE
Use data URI for `FocalPointPicker` video story

### PR DESCRIPTION
**Pull request by stokesman**
## What?
Updates the video story so it does not rely on an external link.

## Why?
The present link is 404.
https://github.com/WordPress/gutenberg/blob/233142b1aca24e8a51da7bf6029155b9f59c8777/packages/components/src/focal-point-picker/stories/index.js#L42-L43

## How?
Updates the utility function `isVideoType` to recognize data URIs and uses one to replace the story’s video url.

## Alternatives to consider
We can probably get a smaller data URI than the one here (~18kb) but I figured it'd be fun to try this one. Of course, if we'd prefer to to just find a new link for an external video that's fine by me.

## Testing Instructions
Try the story out and confirm the video works.

## Screenshots or screencast 
nyan-in-story

### CODE REVIEW

**Review by mirka — COMMENTED** [review]
Thanks for fixing this!

The only downside I guess is that the 18kb will be included in the initial JS bundle for everyone, regardless of whether they're going to see the FocalPointPicker story... I do think  there's a benefit to using data URIs so we don't have to deal with dead links though. As much as I want the nyan cat, should we try a smaller URI, or some video file hosted on wordpress.org servers? No strong opinion on the specifics.

Also, even if we do end up using a video file, I think it would be nice to keep the enhancement you made in `isVideoType()`.

**Comment by ciampo** [comment]
I force-pushed this PR to unblock CI tasks — but it still looks like @mirka 's request to make the video data smaller hasn't been addressed yet

**Comment by mirka** [comment]
Although, the "bundle bloat" problem is a non-issue now that our story files are chunked 😄 Still, one could say that a video URL would be a more realistic use case than a data URL. I'll suggest this video URL from wordpress.tv that will likely stay up for a while: https://videos.files.wordpress.com/NGYE1Hqy/video-206c645332.mp4

**Comment by stokesman** [comment]
Thanks Marco!

I still favor data URI for its resource conservation and network independence. Subjectively, nyan cat seems like more fun too. If no one can get up the courage to approve though I will acquiesce and make the suggested change.

Alternatively if anyone feels like making the change please do. You'll have my approval.

**Review by mirka — APPROVED** [review]
Fair enough 😄 Let's go with the data URI then!

**Comment by ciampo** [comment]
Sounds good, let's merge!

**Pull request merged**
