### PR TITLE
Tapping on an empty editor area creates a new paragraph block

### PR DESCRIPTION
**Pull request by marecar3**
This PR introduces tappable empty editor area which creates a new paragraph block.

Related Gutenberg PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1200

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Looks good and works great as expected! 🎉 
Nice call using the list footer @marecar3 

Great job!

**Comment by marecar3** [comment]
Thanks @etoledom !

**Comment by mchowning** [comment]
Nice job @marecar3 ! This works very well!

I do see two small issues in testing this.

### 1: Tapping footer adds block below selected block

If a block is selected, then tapping the footer inserts the new paragraph block underneath that selected block instead of at the end of the post. I observed this behavior on both Android and iOS. My assumption was that we wanted the footer to always insert the new block at the end of the post, but I admittedly didn't see that specifically called out in the discussion of [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/358).

#### Steps to reproduce:
1. Open demo app.
2. Select any block _other than the last block in the post_ (The "What is Gutenberg?" heading block is a good candidate).
3. Scroll to the bottom of the post and tap on the invisible footer.
4. Note that an empty paragraph block was inserted underneath the previously selected block, and that no block was added to the end of the post.

insert_below_selected mp4

### 2: Keyboard dismissal and re-insertion is more noticeable now

This issue is pretty minor, but on Android when we add an empty paragraph after an already empty paragraph the keyboard is dismissed and immediately reappears. This hasn't been noticeable until now because the add bottom sheet hides it (mostly). It is just more noticeable now when you add an empty paragraph block by tapping the footer after an empty paragraph block because there is no bottom sheet to hide it. Admittedly, this is a very edge case with minimal user impact, but I wanted to point it out. 

I do not observe this issue on iOS.

#### Steps to reproduce:
1. Open demo app
2. Add empty paragraph block to end of post
3. Tap on invisible footer at end of post (after newly added empty paragraph block)
4. Observe that (a) keyboard dismisses and reappears and (b) screen jumps

add_two_at_end mp4

**Comment by etoledom** [comment]
Good catch @mchowning !
I completely missed that one

**Pull request merged**
