### PR TITLE
Updated code to set active pattern and its styling

### PR DESCRIPTION
**Pull request by ciampo**
## What?

A few changes applied on top of https://github.com/WordPress/gutenberg/pull/65917 to showcase some feedback

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Thank you so much, it's working well to me.

Regarding design and styles, I believe that we need something that indicates the "selected" one more prominently. I see that the "selected" is very subtle and uses a semi-transparent overlay. This means that it won't work on dark color schemes (something that's included in Twenty Twenty-Five). I think it could work if we use the accent color for the border, in addition to the overlay.

https://github.com/user-attachments/assets/810e9787-90d9-4cc0-a21a-068232c54ff5

The other thing I noticed, that's probably unrelated to this work and basically related to the reload, is that the selection is dismissed when you navigate out and then you come back to change the selection. It's probably something that we would want to address at some point. It can be seen in the screencast when I'm going to select the Style and come back to pick the design.

**Comment by ciampo** [comment]
- Asked for design feedback in https://github.com/WordPress/gutenberg/issues/65127#issuecomment-2421790683
- For the reload / persistence of the selected indicator, we may want to ask for help from someone more familiar with how this data is stored and retrieved (I had already pinged some folks [here](https://github.com/WordPress/gutenberg/pull/65917#discussion_r1791543545) but no answers so far

**Comment by ciampo** [comment]
> * Asked for design feedback in [Add "selected" styling to active elements in the design selector. #65127 (comment)](https://github.com/WordPress/gutenberg/issues/65127#issuecomment-2421790683)

Feedback [received](https://github.com/WordPress/gutenberg/issues/65127#issuecomment-2422445422) — I updated the styles in this PR (and suggested an equivalent pack in the original PR).

> * For the reload / persistence of the selected indicator, we may want to ask for help from someone more familiar with how this data is stored and retrieved (I had already pinged some folks [here](https://github.com/WordPress/gutenberg/pull/65917#discussion_r1791543545) but no answers so far

We got an answer — it looks like we won't improve that particular aspect for now

**Comment by juanfra** [comment]
Fantastic, thank you Marco!

**Comment by ciampo** [comment]
Closing as https://github.com/WordPress/gutenberg/pull/65917 was merged

**Pull request closed without merging**
