### PR TITLE
Merge bug fixes into wp/trunk

### PR DESCRIPTION
**Pull request by ellatrix**
This is a list of cherry-picked bug fixes to be included in WordPress Beta 2.

Please let me know if I missed any commits, or if I included something by accident (a bug fix for something broken during the 5.4 cycle, or something for phase 2).

Cc @mirka @nosolosw @Jackie6 @kjellr @jasmussen @notnownikki @aduth and @youknowriad. Have a look through the commits tab.

Tests should pass for this branch.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Not sure how best to review this. I took a look over my own fixes and those I had a hand in reviewing. In that and a short run-through of the branch, it all appears in order.

One of #14772 and #14791 are bug fixes which should be included at some point in a WordPress 5.2 beta, depending on whether we'd want to wait for those to land or merge separately.

**Comment by ellatrix** [comment]
Hm, the tests are not running on Travis if you select a different base. This is a bit annoying.

**Comment by ellatrix** [comment]
Added 933ca4a just to run the tests. I'll remove it again later.

**Comment by ellatrix** [comment]
@youknowriad So is this ok to merge with `wp/trunk`, or should we create a `wp/5.2`?

It looks like ideally we wait for some more commits: #14772, #14791 and maybe #14239.

@pento Just so you know about this branch. Don't release Beta 2 before we merge it with trunk. 🙂

**Comment by youknowriad** [comment]
Let's follow Core exactly, for now, this means this goes into `wp/trunk` but when performing the package creation, we should update only the last number (patch).

**Comment by ellatrix** [comment]
I'm about to merge this and start the package process from `wp/trunk`. @gziolo Does that sound correct?

**Comment by gziolo** [comment]
I see 👍 from @youknowriad which means it should be good :)

Please note that there is one breaking change included for the `@wordpres/block-editor` which means it will require a major version bump. It's surprising but it should be okay as this package wasn't in core before 5.2.0.

**Comment by youknowriad** [comment]
@gziolo What is this breaking change?

**Comment by youknowriad** [comment]
Just read it, I actually it's not even a breaking change for me, It's a bug fix.

**Comment by ellatrix** [comment]
Ok merging then!

**Comment by aduth** [comment]
a6ff3a0 is the merge commit for #14772 . Can we cherry-pick that one in?

**Comment by ellatrix** [comment]
@youknowriad @aduth Did we want to limit this to commits that made 5.4, or not?

**Comment by aduth** [comment]
@ellatrix Sorry, I misunderstood what was meant with targeting 5.4 as meaning only bug fixes which had already been released with 5.4, not bug fixes _for_ bugs introduced or present in 5.4.

**Pull request merged**
