### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by walbo**
## Description
Noticed that multiple packages have unused dependencies. This PR removes the unused dependencies.

## Types of changes
Code Quality

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
This is great. Thank you for spending time cleaning all those packages. We have ESLint rules in place that ensure all uses dependencies are listed in `package.json` files, but we don't have anything to enforce the removal of dependencies that are no longer used. 

You need to rebase this branch before we can land it as it looks like several CHANGELOG files have conflicts after one of PRs got merged in the last 13 hours 😅

**Review by gziolo — APPROVED** [review]

**Comment by walbo** [comment]
> This is great. Thank you for spending time cleaning all those packages. We have ESLint rules in place that ensure all uses dependencies are listed in `package.json` files, but we don't have anything to enforce the removal of dependencies that are no longer used.
> 
> You need to rebase this branch before we can land it as it looks like several CHANGELOG files have conflicts after one of PRs got merged in the last 13 hours 😅

Should be resolved now.

I used a script locally to help me find all the unused packages. I'll explore a bit later and try to make it into an action. Would be nice if the CI could pick up unused dependencies.

**Comment by gziolo** [comment]
> I used a script locally to help me find all the unused packages. I'll explore a bit later and try to make it into an action. Would be nice if the CI could pick up unused dependencies.

That would be lovely if we could include it in this workflow:

https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/static-checks.yml

**Review by aristath — APPROVED** [review]
This is amazing work, that you @walbo for all the hard work that went in this PR! 👍

**Pull request merged**
