### PR TITLE
Revert "Use `UnitControl` instead of `RangeControl` for column width"

### PR DESCRIPTION
**Pull request by ceyhun**
## Description

This temporarily reverts this PR: https://github.com/WordPress/gutenberg/pull/24711 until regressions on web and mobile described in that PR are resolved.

### CODE REVIEW

**Review by lukewalczak — APPROVED** [review]
Tested and works properly, there is no crash on mobile 🎉 

revert_columns

**Comment by ntsekouras** [comment]
I think the revert could potentially affect other merged PRs (after this one) that had to do with `Columns` block. For example it will affect this one: https://github.com/WordPress/gutenberg/pull/25829.

And this one is I know because I was the author. There could be many more... 🤔

**Comment by lukewalczak** [comment]
Hello @ntsekouras, could you please checkout on revert branch and test if your functionality works as expected?

**Comment by ntsekouras** [comment]
> Hello @ntsekouras, could you please checkout on revert branch and test if your functionality works as expected?

It doesn't break it, but it's definitely not correct, as I'm adding a `string` value and is not set, since it wants `number` again.

Can we find a solution for the mobile problems mentioned here: https://github.com/WordPress/gutenberg/pull/24711#issuecomment-707058795,  instead?

**Comment by lukewalczak** [comment]
From my perspective, introducing the `UnitControl` is really nice feature, but mobile platform is not prepared currently for that, we are not handling units and there is no UI control component for that.

**Comment by ockham** [comment]
> > Can we find a solution for the mobile problems mentioned here: #24711 (comment), instead?
> 
> From my perspective, introducing the `UnitControl` is really nice feature, but mobile platform is not prepared currently for that, we are not handling units and there is no UI control component for that.

Any chance we can add those missing features to the mobile platform (possibly at the cost of pushing back a release)? It seems like reverting this PR might otherwise cause us other problems (including block invalidations on websites that have already upgraded to GB 9.1 and where the new version of the Column block has been used).

**Comment by lukewalczak** [comment]
I think we can close that PR in favour of temporary [workaround](https://github.com/WordPress/gutenberg/pull/26095).

**Pull request closed without merging**
