### PR TITLE
Update template part icons in the library mosaic (grid items)

### LINKED ISSUE #51905: Library: In the mosaic of entries template parts do not display the correct icon
Screenshot 2023-06-26 at 13 22 54

The icon in the navigation sidebar does not correlate with the one you see in the purple field, adjacent to the template part name. This is true for all template parts; Headers, Footers, and Uncategorized.

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Updates the icons in the grid items in the library to indicate if the template part is a header, footer, or uncategorized.

Closes https://github.com/WordPress/gutenberg/issues/51905

## Why?

The icons did not match with the icons in the sidebar.

## How?

The PR adds a condition that uses the `categoryID` to determine which icon to display.

## Testing Instructions

- Activate a block theme that has at least one footer, header, and uncategorized template part.
- Open Appearance > Editor > Library.
- In the menu, click on Headers, Footers, and Uncategorized, respectively.
- Confirm that the icons in the sidebar and the preview ( the mosaic /grid) match.

## Screenshots or screencast 
After:
The header template part in the library grid has a header icon.

### CODE REVIEW

**Review by aristath — APPROVED** [review]
Failing tests are not related to this PR, and what the code does here is simply changing the icons. @WordPress/gutenberg-design @jasmussen I think this is OK to be merged so I'll go ahead and pre-approve it, pending feedback from designers 👍

**Comment by jasmussen** [comment]
Thanks for the ping! @jameskoster has followed the library work a bit more closely.

**Review by jameskoster — APPROVED** [review]
LGTM!

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/wp6-3-beta3 branch to get it included in the next release: b64bc8a33b

**Pull request merged**
