### PR TITLE
Try: Show two columns of patterns.

### PR DESCRIPTION
**Pull request by jasmussen**
This takes a stab at one half of #28312, showing two columns of patterns in the main inserter, just like we do in the sibling inserter:

Screenshot 2021-01-19 at 12 41 38
Screenshot 2021-01-19 at 12 54 34

The purpose is to show the breadth of patterns, when there are a lot of them. Combined with the drag and drop that was recently added, to me this feels worth trying.

### CODE REVIEW

**Comment by joanrho** [comment]
Thanks for spinning this up so quickly! Tested via gutenberg.run and it works as expected. 

I appreciate how this layout strengthens the relationship between the quick/sibling inserter and the main sidebar inserter and allows me to view more pattern options at once ([see my comment here](https://github.com/WordPress/gutenberg/issues/28312#issuecomment-763878052) for a demo of what more patterns might look like based on the current experience with WordPress.com's larger pattern library).

Curious to hear if others think this might help set us up for better pattern browsing as the Core pattern library grows.

**Comment by hedgefield** [comment]
This looks excellent. In this example all the patterns have the TT1 green background, what happens when a pattern has a white background? Adding a little border or something like that could help prevent it from blending into the rest of the inserter panel. Otherwise I dig it!

**Comment by shaunandrews** [comment]
I like that it's easier to scan through a bunch of patterns, if they exist, but I I kind of miss the bigger previews. Either in this PR or a new one, it could be nice to display a larger flyout preview when hovering/focusing the preview.

--

Not for this PR, but there could be an interesting followup using math to output some sort of tiled view, mixing full-width and half-width; something based on the rendered height, maybe.

**Comment by joanrho** [comment]
@hedgefield Great point about adding borders to the patterns. 

In my [original mocks](https://github.com/WordPress/gutenberg/issues/28312), I explored a borderless direction to carry over our existing styles in the Inserter which align with our treatment of Block Icons over in the Blocks tab (no borders except on hover), but I agree that adding a border could help with identifying pattern boundaries. Perhaps something like an inset shadow _below_ the pattern to act as a border for any patterns with a transparent background color? 

Here's what that could look like (the "Call to action" and "Quote and logos" patterns have background colors, the rest do not):

PatternBorders


@shaunandrews Great suggestions.

> it could be nice to display a larger flyout preview when hovering/focusing the preview.

Were you thinking of something like the block preview? Here's what that could look like with the styles carried over from the block previews for blocks (left-alignment + heavier font weight for block/pattern name):

Patterns-BlockPreview

> there could be an interesting followup using math to output some sort of tiled view, mixing full-width and half-width; something based on the rendered height, maybe.

I really like this idea. It'd be especially helpful for shorter patterns, like Headers or Footers, which look quite squashed at half-width size. Here's a demo of how it could look:

Patterns-mixedwidths-min


The first full-width pattern has a pair of patterns above it that aren't quite the same height (so there's a larger gap between the second/right half-width pattern and the full-width one), and the second full-width pattern has a pair of patterns above it that are better matched in height. If we can somehow calculate pattern heights to pair similar ones together, the mixed half- and full-widths might work nicely. Can anyone chime in on the feasibility of that?

**Comment by jasmussen** [comment]
Specifically regarding borders, this PR doesn't touch what exists there, so borders remain. 

> Not for this PR, but there could be an interesting followup using math to output some sort of tiled view, mixing full-width and half-width; something based on the rendered height, maybe.

:daydream:

**Comment by shaunandrews** [comment]
I'd still love to see this one merge.

**Comment by jasmussen** [comment]
Rebased.

**Comment by draganescu** [comment]
Rebased for testing and in my  setup (with WP 5.8 RC 1) I see only one column. I tested in the site editor and in the post editor.

**Comment by jasmussen** [comment]
Thanks for testing Andrei. I still think there's a place for this one, but it's lingered for a bit and probably drifted. Since it's no longer working, I'll close it for now. But let's keep the original issue open so it doesn't fall off the radar.

**Pull request closed without merging**
