### PR TITLE
Update the Dashicons component

### PR DESCRIPTION
**Pull request by jasmussen**
This PR brings two new icons for Gutenberg, and one icon that was added for core.

- Shortcode can be used for the Shortcode block, to finally look more in place.
- Break-link lets us iterate on the link interface. CC @karmatosed @randerson
- Tide is for the WordPress core Tide team.

Upstream PR: https://github.com/WordPress/dashicons/pull/269

### CODE REVIEW

**Review by aduth — APPROVED** [review]

**Comment by jasmussen** [comment]
Thanks for the review, however after some new feedback upstream I'm going to postpone merging this and update the component once again.

**Comment by jasmussen** [comment]
CC: @karmatosed @randerson, turns out there's already an unlink icon https://developer.wordpress.org/resource/dashicons/#editor-unlink

**Comment by jasmussen** [comment]
Addressed the upstream feedback. This can be merged, though I'm AFK next week.

**Review by gziolo — APPROVED** [review]
LGTM

**Pull request merged**
