### PR TITLE
Data views: Update 'Rows per page' view option label to account for Grid layout

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
When the grid layout is selected the 'Rows per page' view option now reads 'Entries per page'.

## Why?
In the context of grid layout 'Rows per page' is ambiguous. Does it refer to the individual items or the number of rows in the grid?

## Testing Instructions
1. In the Site editor go to manage pages or templates
2. In view options switch to grid layout
3. Check the 'Entries per page' label

Screenshot 2024-01-30 at 15 37 08

I'd appreciate input from @WordPress/gutenberg-design on the terminology. Possible alternatives to 'entries':

* 'Records per page'
* 'Items per page'
* $post-type (e.g. 'Patterns per page')
* Something else?

Worth noting that all of these options could effectively account for any layout meaning we could potentially remove the conditional logic and simplify things a bit. I suppose that's a question of consistency versus specificity.

### CODE REVIEW

**Comment by t-hamano** [comment]
I prefer to use "Items per page" for all layouts. It feels versatile and matches any layout.

In the core dashboard, everything is unified with "Number of items per page" (even the user list!)

image
image
image

**Comment by t-hamano** [comment]
I think the question of what words to use is also related to #58482, which aims to improve the messages when there are no results.

**Comment by jasmussen** [comment]
Items per page seems good to follow 👍 👍

**Comment by jameskoster** [comment]
Thanks both. I updated to remove the logic and use 'Items per page' regardless of layout:

Screenshot 2024-01-31 at 16 21 08

**Review by ciampo — APPROVED** [review]
🚀

**Pull request merged**
