### PR TITLE
Global Styles: Prevent duplicate block style variations CSS

### LINKED ISSUE #62457: Section Styles: unecessary additional CSS output
### Description

While testing the Section Styles I found some oddities in the CSS output. Some additional and unnecessary CSS is output, which is not ideal and should be restricted with some further code enhancements. 

Testing instructions are below.

### Step-by-step reproduction instructions

I've attempted to create a reduced test case.

1. Add a new file into the parent Twenty Twenty-Four theme for section styling: `twentytwentyfour/styles/mock.json` with the following code: https://gist.github.com/colorful-tones/56c090ab4b458cdfc77025dd076889e5#file-twentytwentyfour-mock-json
2. Create a post or a page and add a Paragraph block, and choose the 'Mock' block style variation from the Block Styles panel. Save, and visit the front end of the site.
3. View Source and search for `mock` to see all the styles output.

Notice that there are multiple entries for CSS being output and I'm not totally clear as to why. For example, with only a single `<p class="is-style-mock is-style-mock--e1aa201d31a4b92642d4459514f98ae8">some text</p>` element on the page - I see the following CSS being output on the front end of the site (in top-down order of being output on the page)

First related `mock` CSS output on the page:

```css
<style id='global-styles-inline-css'>
:root :where(p.is-style-mock){background-color: #eed8d3;color: #201819;font-family: Arial, sans-serif;font-size: clamp(48.588px, 3.037rem + ((1vw - 3.2px) * 3.704), 96px);padding: 120px;}
</style>
```

Second instance of `mock` CSS output on the page:

```css
<style id='block-style-variation-styles-inline-css'>
:root :where(p.is-style-mock--e1aa201d31a4b92642d4459514f98ae8){background-color: #eed8d3;color: #201819;font-family: Arial, sans-serif;font-size: clamp(48.588px, 3.037rem + ((1vw - 3.2px) * 3.704), 96px);padding: 120px;}

:root :where(p.is-style-mock--1aa4a837b1ec90d53ffc7707030b43c1){background-color: #eed8d3;color: #201819;font-family: Arial, sans-serif;font-size: clamp(48.588px, 3.037rem + ((1vw - 3.2px) * 3.704), 96px);padding: 120px;}
</style>
```

Note: the original block id associated with the final `<p>` class is `e1aa201d31a4b92642d4459514f98ae8`, which matches the last declaration for `p.is-style-mock--1aa4a837b1ec90d53ffc7707030b43c1`. However, where is the `p.is-style-mock--e1aa201d31a4b92642d4459514f98ae8` even coming from and being output on the page? Why are there two declarations of the same and both targeting `p.is-style-mock` (one just being more specific with `--1aa4a837b1ec90d53ffc7707030b43c1`)?

I feel like the expected outcome would be to just see the _only_ following CSS output on the page.

```css
<style id='block-style-variation-styles-inline-css'>
:root :where(p.is-style-mock--1aa4a837b1ec90d53ffc7707030b43c1){background-color: #eed8d3;color: #201819;font-family: Arial, sans-serif;font-size: clamp(48.588px, 3.037rem + ((1vw - 3.2px) * 3.704), 96px);padding: 120px;}
</style>
```

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/405912/163395cc-e1f1-44c9-a5a2-4bfce8787626

### Environment info

- WordPress 6.6-beta1 (with WordPress Beta Tester plugin)
- Gutenberg plugin active at latest stable: 18.5.0
- See theme info in testing instructions

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/62457

## What?

As the new section styles feature requires styles generated per application of block style variations so they can be nested, there's superfluous CSS generated in the frontend theme.json stylesheet. This PR removes that.

## Why?

Less CSS.

## How?

Adds option in theme json to opt out of style generation for block style variations. A similar option is added to the `useGlobalStylesOutput` hook in the editor.

## Testing Instructions

1. Register a custom block style variation e.g. through a theme.json partial: `/styles/partial.json`

```
{
	"$schema": "https://schemas.wp.org/trunk/theme.json",
	"version": 2,
	"title": "Custom",
	"slug": "custom",
	"blockTypes": [ "core/group" ],
	"styles": {
		"color": {
			"background": "aliceblue"
		}
	}
}
```

2. In both editors add a group block and apply the `Custom` block style variation.
3. Inspect the group block and confirm there is only a single `is-style-custom-*` css class matched
4. Save the page or post and confirm the same on the frontend

Note: Core blocks with variations can also be used for testing, e.g. Button or Image. These blocks those also have other styles from the block library enqueued that would match. The removal of redundant CSS is clearer when testing with a custom variation.

| Before | After |
|---|---|
| Screenshot 2024-06-14 at 7 27 54 PM | Screenshot 2024-06-14 at 7 29 16 PM |

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
While backporting this one I found there's a difference between Gutenberg's and Core's `get_block_nodes` function signature. Gutenberg accepts and additional argument. That might need addressing before the `$options` arg proposed here lands.

**Comment by aaronrobertshaw** [comment]
I tracked the divergence between Core and Gutenberg `get_block_nodes` signatures to https://github.com/WordPress/gutenberg/pull/41217 not being backported. 

As `get_block_nodes` is private it shouldn't be an issue to belatedly backport the minor signature and code change. I've done that in this PR's backport (https://github.com/WordPress/wordpress-develop/pull/6827). 

No further changes on that front should be required here, so I'll flag this one ready for review.

**Comment by aaronrobertshaw** [comment]
The test failures appear unrelated so I've kicked off a re-run of those tests. If they don't pass, I'll dig into them first thing tomorrow.

**Review by oandregal — APPROVED** [review]

**Comment by aaronrobertshaw** [comment]
The PHP changes were backported and merged in time for 6.6 beta 3. I missed the backport label on this one for the JS changes to be cherry-picked, sorry.

**Comment by ellatrix** [comment]
I just cherry-picked this PR to the wp/6.6-rc-1 branch to get it included in the next release: 5d940ff48a

**Pull request merged**
