### PR TITLE
Remove Interactivity API experimental flag

### PR DESCRIPTION
**Pull request by SantosGuillamot**
## What?
I'm opening this pull request to be ready to remove the experimental flag for the Interactivity API and make the Navigation, File, and Image blocks use the Interactivity API by default. The idea is to ensure everything is ready for the moment we decide to remove the Experimental flag.

## Why?
At this moment, users can only test the Interactivity API and its functionalities if they activate the Experimental flag in the Gutenberg Experiments page.

## How?
These are the steps I took so far:
* I removed the conditional loading from the `load.php` file.
* I changed the `viewScript` field of the `block.json` of the Navigation, File, and Image blocks to read the `interactivity.js` file.
* I removed the old `view.js` files.
* I moved the directives directly to the `index.php` of the Image and File blocks. At this moment they are still using the Tag Processor, but I want to explore which is the best approach.
* I added some logic to ensure the JS files are only loaded when they are necessary. I want to explore the possibility of reusing the same function for all the blocks.
* I added some logic to load the directives conditionally (WIP)

## Testing Instructions
* Test that the Navigation, the File, and the Image lightbox blocks work as expected.
* Test that the scripts are loaded conditionally:
    * In the navigation block: when the overlay is set to off, and the submenus options to "open on click" and "show arrow" are disabled, scripts and  directives shouldn't be there.
    * In the file block: when the "Show inline embed" option is disabled, scripts and directives shouldn't be there.
    * In the image block: when the "Lightbox" is disabled from all the images, scripts and directives shouldn't be there.

### CODE REVIEW

**Comment by SantosGuillamot** [comment]
Right now, to do the conditional loading of scripts, I'm reusing the same logic for [the Navigation](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/navigation/index.php#L367-L381), the [File](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/file/index.php#L17-L31), and the [Image](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/image/index.php#L48-L62) block. Would it make sense to create a function that can be reused by all the blocks? If so, which is the best place to do so? cc: @gziolo

I'm thinking of something like:

```php
function load_view_js_file ( $block, $view_js_file, $should_load_view_script ) {
    if ( ! wp_script_is( $view_js_file ) ) {
		$script_handles = $block->block_type->view_script_handles;

		// If the script is not needed, and it is still in the `view_script_handles`, remove it.
		if ( ! $should_load_view_script && in_array( $view_js_file, $script_handles ) ) {
			$block->block_type->view_script_handles = array_diff( $script_handles, array( $view_js_file ) );
		}
		// If the script is needed, but it was previously removed, add it again.
		if ( $should_load_view_script && ! in_array( $view_js_file, $script_handles ) ) {
			$block->block_type->view_script_handles = array_merge( $script_handles, array( $view_js_file ) );
		}
    }
} 
```

**Comment by carolinan** [comment]
To me, this feels rushed, the image light box was merged less than 24 hours ago?
There is a similar PR opened by Carlos, I suppose this one replaces https://github.com/WordPress/gutenberg/pull/50915?

**Comment by SantosGuillamot** [comment]
> To me, this feels rushed, the image light box was merged less than 24 hours ago?

Oh, my intent wasn't to release it whenever this pull request is ready. I just thought it would be good to have everything ready for the moment we decide not to use the Experimental flag anymore. I'll clarify that in the opening post.

> There is a similar PR opened by Carlos, I suppose this one replaces https://github.com/WordPress/gutenberg/pull/50915?

I wasn't aware of it. Thanks for sharing 🙂 Yes, the goal is the same. I'll coordinate with him to see how to approach it.

**Comment by cbravobernal** [comment]
I've closed  #50915 and will follow this one better 😄

**Comment by gziolo** [comment]
Thank you for opening this PR. It's great to see what needs to be done to switch to Interactivity API as the default way for developing core blocks. 

> Right now, to do the conditional loading of scripts, I'm reusing the same logic for [the Navigation](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/navigation/index.php#L367-L381), the [File](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/file/index.php#L17-L31), and the [Image](https://github.com/WordPress/gutenberg/blob/experiment/remove-interactivity-api-experimental-flag/packages/block-library/src/image/index.php#L48-L62) block. Would it make sense to create a function that can be reused by all the blocks? If so, which is the best place to do so

We discussed some aspects of it in the private discussion, but let me summarize some talking points for transparency. The default behavior for view scripts changed in WordPress 6.1 release. That's when the conditional loading for the File block and the Navigation blocks regressed, and the scripts are always loading when the block is rendered. The changes proposed fix that logic, and it's a great win. The approach is quite good, and it should work in most of the cases. I hope it will work with all sites that extend those blocks, but we will see later if we miss something at the moment.

The helper function sounds like a good idea only if we want to offer that solution as a general way for block developers to control enqueueing view scripts. We need to keep in mind that once this function lands in WordPress core plugins might start using it so we will have to maintain it for a long time. I'm not entirely sure if that's the intent here, as we can explore different ways that would allow achieve the same goal of changing how WordPress core works today.

**Comment by SantosGuillamot** [comment]
> We need to keep in mind that once this function lands in WordPress core plugins might start using it sp we will have to maintain it for a long time. I'm not entirely sure if that's the intent here, as we can explore different ways that would allow achieve the same goal with changing how WordPress core works today.

Oh, you're right. The way I understood it, this function was a workaround until we research a better way to do it. So maybe it doesn't make sense to create a function at this point.

**Comment by gziolo** [comment]
> Oh, you're right. The way I understood it, this function was a workaround until we research a better way to do it. So maybe it doesn't make sense to create a function at this point.

The body of the function works perfectly fine. It's probably an acceptable trade-off to have it duplicated in 3 blocks for now as it improves the performance for site visitors.

**Pull request closed without merging**
