### PR TITLE
[Mobile] - Disable FastImage on Android

### PR DESCRIPTION
**Pull request by geriux**
**Related PRs:**
- `Gutenberg Mobile` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/5102
- `WordPress iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/19202
- `WordPress Android` -> https://github.com/wordpress-mobile/WordPress-Android/pull/17042

## What?
There's a current issue on Android https://github.com/WordPress/gutenberg/issues/43149 where in some cases the images will disappear with the React Native FastImage library.

## Why?
While we investigate the issue and have a fix that covers all cases we should disable it.

## How?
By disabling FastImage on Android in all cases and only using the built-in React Native Image component.

## Testing Instructions

Test the following cases with the following environments for both iOS and Android:

- [ ] Simple site (public)
- [ ] Simple site (private)
- [ ] Atomic site (public)
- [ ] Atomic site (private) (optional: there's another issue that's already [reported](https://github.com/wordpress-mobile/WordPress-iOS/issues/19055) where media, in general, is not working for Atomic private sites)
- [ ] Self-hosted site (public)
- [ ] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

### Test case 1 - Image block upload

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block

### Test case 2 - Gallery block upload

- Open the app
- Create a new post
- Add a Gallery block
- Upload some images from the device
- Once the images finish uploading **expect** to see the images visible in the block

### Test case 3 - Rotate the device with an Image block 

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block
- Rotate the device
- Expect to image to be visible

## Screenshots or screencast 
N/A

### CODE REVIEW

**Comment by mkevins** [comment]
## 🟢 WordPress-Android Testing

Tested on a Pixel 3a (physical device)

### Test case 1 - Image block upload


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [ ] Atomic site (private) <s>(optional: there's another issue that's already [reported](https://github.com/wordpress-mobile/WordPress-iOS/issues/19055) where media, in general, is not working for Atomic private sites)</s> - I tried but was unable to test due to the linked issue
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block


### Test case 2 - Gallery block upload


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add a Gallery block
- Upload some images from the device
- Once the images finish uploading **expect** to see the images visible in the block

### Test case 3 - Rotate the device with an Image block 


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block
- Rotate the device
- Expect to image to be visible

**Comment by mkevins** [comment]
## 🟢 WordPress-iOS Testing

Tested on an iPhone 11 (physical device)

### Test case 1 - Image block upload


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block


### Test case 2 - Gallery block upload


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add a Gallery block
- Upload some images from the device
- Once the images finish uploading **expect** to see the images visible in the block

### Test case 3 - Rotate the device with an Image block 


- [x] Simple site (public)
- [x] Simple site (private)
- [x] Atomic site (public)
- [x] Self-hosted site (public)
- [x] Self-hosted site (private) (optional: there's no setting to set a site as private, I tried using the `WP Maintenance Mode` plugin)

 Steps:

- Open the app
- Create a new post
- Add an Image block
- Upload an image from the device
- Once the image finish uploading **expect** to see the image visible in the block
- Rotate the device
- Expect to image to be visible

**Review by mkevins — APPROVED** [review]
These changes look good. I tested the scenarios in the description, and everything is working as expected. Thank you for wrangling this Gerardo! Also, thanks for removing the custom logic for handling the orientation change. Hopefully this will no longer be needed when this is re-enabled 👍

**Comment by geriux** [comment]
Thank you for the review and testing @mkevins!

**Pull request merged**
