### PR TITLE
Beef up the padding on component panel titles.

### LINKED ISSUE #1335: Component panel titles are hard to click
I think because the sidebar UI visually resembles an old-school accordion, I'm conditioned to think the entire rectangle area (used to roll open a panel) should be clickable.

Currently, the component panel titles are only as tall as the text, and do not fill the padded area.

I propose we bulk-up the `.components-icon-button` to cover the padded area. This would result in no visual changes, but increase the targetable area of each title button by `15px` in each direction.

Going to try to submit a pull-request for this shortly.

### PR DESCRIPTION
**Pull request by JJJ**
This increases the size of the clickable target area for component panel titles by 30px in each direction, making them easier to click open & closed.

Fixes #1335.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice! Thanks for doing this!

I think we should probably remove the border radius on the focus rectangle for this one:

screen shot 2017-06-21 at 17 09 09

With that done, though, 👍 👍

**Comment by aduth** [comment]
Alternative to negative margin is to create a separate wrapping component for the content itself, applying default padding there, and letting button / toggle render naturally at the bounds of the panel.

Downside is more nodes on the page.

Thoughts?

**Comment by JJJ** [comment]
> Thoughts?

I agree, negative margins are undesirable – it's hard for me to gauge to what degree for this project compared to others (WordPress itself, for example, is full of them.) My preference would be not to perpetuate the bad habit, but I didn't want to rough up Gutenberg too assertively out of the gate.

> I think we should probably remove the border radius on the focus rectangle for this one

Good catch. I'll push that to my branch soon if no one else gets to it first.

**Comment by JJJ** [comment]
> I think we should probably remove the border radius

Once I removed the radius, it revealed there was a `1px` margin between the button and the container elements. This had the undesirable effect of revealing a gap around the outline & box shadow.

I believe that gap was unintentional, so I've also set `margin: 0;` on those buttons in the same commit.

**Comment by youknowriad** [comment]
Did you try to rebase here? I think the 1px margin might have been fixed.

**Comment by aduth** [comment]
>Once I removed the radius, it revealed there was a `1px` margin between the button and the container elements. This had the undesirable effect of revealing a gap around the outline & box shadow, and because those container elements have horizontal borders already, I believe that gap was unintentional, so I've also set `margin: 0;` on those buttons in the same commit.

Not sure if this one is browser-specific, but FWIW I was not able to reproduce this margin when removing the margin locally.

It feels a little crowded when focus highlight is active on an expanded panel, but I don't find it particularly problematic.

**Review by aduth — APPROVED** [review]

**Comment by jasmussen** [comment]
Thanks for this PR! Feels sooo much better now.

**Pull request merged**
