### PR TITLE
Refactor resetBlocks to action-generators

### PR DESCRIPTION
**Pull request by nerrad**
## Description

As part of the ongoing refactor of effects to controls/action-generators, this is the first part of doing the work in the `@wordpress/block-editor` package.  In this pull:

- `replaceBlocks` is migrated to action-generators.
-  unit tests are updated
- `STORE_KEY` constant introduced and exported (this reduces chance of human error in adding the store reference). Importing the key allows for automatic dependency management to pick up the `block-editor` package dependency as well.
- Remove the custom `controls.js` file and usage since `@wordpress/data-controls` is a suitable replacement.

## How has this been tested?

* [x] Created blocks, converted to reusable and back again.
* [x] Verify unit tests pass
* [x] Verify no e2e tests fail.

## Types of changes

This should not be a breaking change.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by nerrad** [comment]
I'm doing this in smaller pulls so it's easier to review

**Comment by aduth** [comment]
This will need a refresh after #14003 which, as noted at https://github.com/WordPress/gutenberg/pull/14003#issuecomment-477304162 , had some overlapping effort with respect to the `ensureDefaultBlock` refactoring.

**Comment by nerrad** [comment]
Latest work refreshes this pull to refactor `resetBlocks`.  Some of the original work int his pull was handled elsewhere.

**Comment by nerrad** [comment]
This pull is ready for another review.

**Comment by gziolo** [comment]
I see @adamziel opened #27298 with a similar goal. Which PR should be reviewed first? I want help to remove all remaining effet 😃

**Comment by nerrad** [comment]
If @adamziel's pull is more recent and refactors the same thing, probably best to focus on his. This pr is really stale as it's been sitting for a while.

**Comment by gziolo** [comment]
Yes, it is. Let's focus on the most recent one. Thank you for understanding 😃

**Pull request closed without merging**
