### PR TITLE
[Full Site Editing]: Include theme's templates in template list in post editor

### LINKED ISSUE #41617: Page templates are no longer displaying in editor
### Description

Before Gutenberg 13.4 update we were able to choose page templates from the dropdown.

Now it's no longer working, page templates are not recognized by the editor.

Page template created like so and placed in **page-templates** directory.
```
<?php
/**
 * Template Name: Full-width Contained
 */
```

This is happening in there is **block.json** file present in the theme directory.

### Step-by-step reproduction instructions

1. Activate Gutenberg 13.4
2. Edit any page
3. No page template dropdown displayed

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
Fixes: https://github.com/WordPress/gutenberg/issues/41617
Regression from: https://github.com/WordPress/gutenberg/pull/41387

## Why?
In the [PR that caused the regression](https://github.com/WordPress/gutenberg/pull/41387), I overrode the `templates` that were coming from `get_page_templates`(core) but that made the php theme templates lost. This PR fixes that by excluding only the needed templates.

## Testing Instructions
1. Add a php template in theme's `templates` directory.
```
<?php
/**
 * Template Name: Full-width Contained
 */
```
2. Edit any page
3. Observe that the php templates are in the list

### CODE REVIEW

**Review by carolinan — APPROVED** [review]
I tested classic themes by adding theme support for block-templates to Twenty Twenty.
I tested block themes by adding a PHP template to Twenty Twenty-Two.
The PR solves the problem. The added context in the comment is clear.

**Comment by skorasaurus** [comment]
Thanks for the quick repair on this; the regression had been affecting me as well; and I can also confirm this PR fixes the issues I experienced.

**Comment by mburridge** [comment]
Added the Needs Dev Note label in case this needs a dev note (either individual or as part of a "misc" dev note) for WP 6.1 release.

**Comment by ntsekouras** [comment]
>Added the Needs Dev Note label in case this needs a dev note (either individual or as part of a "misc" dev note) for WP 6.1 release.

This was a small regression so the fix restored the previous functionality. No need for dev note.

**Pull request merged**
