### PR TITLE
Components: Introduce portal-based slot / fill alternative, render Popover as slot / fill

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to refactor Popover to simplify rendering as a slot / fill pair, rather than require a custom context provider providing a DOM node render target.

__Implementation notes:__

Originally I sought to implement this using `react-slot-fill` as we use elsewhere, but quickly encountered similar issues as discovered in #2734 where lifecycle of slot content is not always predictable since component updates are [reflected only after a subsequent state change](https://github.com/camwest/react-slot-fill/blob/f4087870aa3f74b86cb55f882e9f398586800256/src/lib/components/Slot.ts#L53). 

Recognizing that React 16's portals feature provides the tools for a Slot / Fill implementation, I sought to explore what would be necessary for a first-party implementation. Happily it seemed to work quite well, needing only a context provider to register, unregister, and retrieve `ref` nodes of the rendered `Slot`s to which a `Fill` can create a portal. The first-party portal implementation does not suffer from the same lifecycle issues as `react-slot-fill`. Further encouraging is that such an approach [appears advocated by Dominic Gannaway](https://wordpress.slack.com/archives/C5UNMSU4R/p1506440954000270), a React core team member.

We should decide whether this is worth using as a substitute to `react-slot-fill`. It may be worthwhile to split this pull request into two, where the first would convert existing usage to the new WordPress-specific `slot-fill`.

__Testing instructions:__

Verify that there are no regressions in Popover usage, particularly:

- Different types of popovers (tooltips, dropdown)
- Focus should transition into popover when opened (e.g. Inserter)
- Popover should reorient itself when lacking sufficient space to open in the desired direction
- Popover should close when clicking outside
- No console errors should be logged in any of the above

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Such a great code :). Simple and efficient.
Agreed we should replace our current slot and fill usage.

Before or after this PR, doesn't matter that much for me.

**Comment by aduth** [comment]
Rebased to resolve conflicts. I started toying locally to see whether the custom implementation would work well for our other use of Slot / Fill and for the most part it does. One issue was if a fill is rendered before the slot is mounted. The updated implementation now tracks all fills and forces a re-render should a slot become registered for that name. Further, I made the provider context optional for slot and fills, avoiding the need to mock tests on Fill (default behavior will render children verbatim in-place).

Finally, since I did the work... I decided to just finish dropping `react-slot-fill` here :neutral_face:

**Comment by aduth** [comment]
>Further, I made the provider context optional for slot and fills, avoiding the need to mock tests on Fill (default behavior will render children verbatim in-place).

Hmm, this appears to be problematic, since for something like block inspector, if the sidebar panel isn't opened, the inspector controls will render adjacent the preview, rather than not render at all. Probably need to revert this specific change.

**Comment by aduth** [comment]
This grew a bit larger than I would have liked, but it should be pretty well settled now. In recent changes:

- Reverted to not rendering a fill if context is not available, but kept revisions to avoid errors being thrown in the process
- Updated Popover to check whether slot context exists. This is a workaround to preserve previous portal behavior (which, frankly, probably wouldn't have worked after a React 16 upgrade), and from a developer experience improves usability of the Popover component to be slot-optional (first iterations of the popover rendered in-place).

**Comment by youknowriad** [comment]
Still working great 👍

**Comment by mtias** [comment]
Nice work here, @aduth.

**Pull request merged**
