### PR TITLE
Output width and height attributes for Image blocks

### PR DESCRIPTION
**Pull request by kienstra**
## Description
Could you use this PR for #6652, which ensures that most Image block `` elements will have a `width` and `height`?

Before, Image blocks usually only had `width` or `height` attributes for the `` if the user edited the `<input>` elements for those, or clicked a percentage pillbox:

before-width-height

This PR sets the `width` and `height` on selecting an image from the Media Library, and on selecting from the 'Image Size' `<select>` element. Clicking a percentage pillbox, like `25%`, still updates the `width` and `height`:

changing-these-width-height

**The is-resized class**
Before, there was an `is-resized` class that applied only [when there were width or height attribute values](https://github.com/WordPress/gutenberg/blob/df3d36633e718a9932507cd2b9105e77809d0c91/packages/block-library/src/image/edit.js#L262). These values only existed on editing the [Width and Height TextControls](https://github.com/WordPress/gutenberg/blob/df3d36633e718a9932507cd2b9105e77809d0c91/packages/block-library/src/image/edit.js#L303) [directly](https://github.com/WordPress/gutenberg/blob/df3d36633e718a9932507cd2b9105e77809d0c91/packages/block-library/src/image/edit.js#L312), or from [clicking the percentage pillbox](https://github.com/WordPress/gutenberg/blob/df3d36633e718a9932507cd2b9105e77809d0c91/packages/block-library/src/image/edit.js#L329) (shown in the first screenshot above).

But now, there are almost always `width` and `height` values, as they're added via the Media Library, and updated as shown in the second screenshot above.

So this [adds the attribute isResized](https://github.com/WordPress/gutenberg/blob/6ec4102d0ec8aa78b659db45e95ad7a2b436eb2f/packages/block-library/src/image/index.js#L72) to apply the class `is-resized` in the same cases where it was applied before.

## How has this been tested?
1. Created a new Image block, and verified that it had `width` and `height` attributes, but no `is-resized` class
width-height-present

2. Changed that image's 'Image Size' to `Thumbnail` as shown in the second screenshot above.
3. Verified that the `width` and `height` are changed to `150`, and there is no `is-resized` class:
width-height-changed

4. Clicked the `75%` pillbox, as shown in the first two screenshots.
5. Verified that the `width` and `height` are correct, and the `is-resized` class is present:
is-resized-class

Tested on Chrome Version 68.0.3440.106 (Official Build) (64-bit)

## Screenshots 
**Before:**
no-width-height

**After:**
width-height-present-media-library

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by kienstra** [comment]
It looks like the [Travis build failed](https://travis-ci.org/WordPress/gutenberg/builds/421912348?utm_source=github_status&utm_medium=notification). Would someone have permissions to click 'Restart build'?

**Comment by Soean** [comment]
@kienstra I restarted the test. The test snapshots with image blocks have no height and width attributes like in your code, so they fail.

**Comment by kienstra** [comment]
Thanks, @Soean! I'll work on that now.

**Comment by kienstra** [comment]
**Thank You**
*Travis Builds Passing*

Hi @Soean,
Thanks for your help in restarting the Travis build, and pointing to the solution to the failed tests.

Would you be able to use this PR for #6652? Sorry for the delay in fixing the tests.

**Comment by kienstra** [comment]
**Question About PR**

Hi @joemcgill,
Hope you're doing great!

Could you use this PR for #6652, and if so, would you be available to review it?

Thanks!

**Comment by hacknug** [comment]
Any plans on merging this any time soon?

**Comment by kienstra** [comment]
If you would like to merge this, please ping me here and I'll resolve the merge conflicts.

**Comment by AdrienPerinot** [comment]
@kienstra I see this was closed. It seems to me that it's a rather important enhancement, as most if not all of the lazyload plugins rely on this to avoid jumps. There seem to be no clean workaround at the moment. Why was it closed :( ? Can it be planned for a future update ?

As a side note, inline images should also have these height/width attributes.

**Comment by kienstra** [comment]
Hi @AdrienPerinot,
Thanks for bringing this up.

I closed it because it wasn't reviewed. But if someone would like to review it, I'd be glad to update it and resolve the merge conflicts.

**Comment by AdrienPerinot** [comment]
I see - wish it was reviewed as it is a must have in my opinion.

**Comment by kienstra** [comment]
Thanks! Maybe contacting core Gutenberg contributor(s) would help.

**Pull request closed without merging**
