### PR TITLE
Improve Parser Performance

### PR DESCRIPTION
**Pull request by pento**
## Description

The PHP parser has some performance issues on larger posts, I've been doing a bit of tweaking to get some more speed out of it.

The `Block_List` `pre` rule now does a simple search for strings that aren't `<!--`. Its a reasonable assumption that the vast majority of strings that do match this will be the start of a block, so we're probably going to the `bs` rule once it does match.

The `Block_Balanced` `children` rule has a similar simple search, for the same reason.

The `Block_Name_Part` rule explicitly defines a handful of block names. This feels a bit weird to be doing in the parser, but `$( [a-z][a-z0-9_-]* )` is such a slow rule to match, that I think it's worth it.

I've also enabled pegjs' internal caching on the PHP parser, as this appear to give a decent boost, too.

## How has this been tested?

Comparing the current parser with this PR, I get some pretty clear performance gains:

| File | Current | This PR | Improvement |
| --- | --- | --- | --- |
| [demo-post.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/demo-post.html) | 29.8ms | 7.3ms | 4x |
| [shortcode-shortcomings.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/shortcode-shortcomings.html) | 77.9ms | 16.5ms | 4x |
| [redesigning-chrome-desktop.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/redesigning-chrome-desktop.html) | 227.9ms | 52.6ms | 4x |
| [web-at-maximum-fps.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/web-at-maximum-fps.html) | 169.1ms | 41.3ms | 4x |
| [early-adopting-the-future.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/early-adopting-the-future.html) | 270.8ms | 62.9ms | 4x |
| [pygmalian-raw-html.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/pygmalian-raw-html.html) | 421.9ms | 254.6ms | 1x |
| [moby-dick-parsed.html](https://raw.githubusercontent.com/dmsnell/gutenberg-document-library/master/library/moby-dick-parsed.html) | 5402.3ms | 1197.7ms | 4x |

### CODE REVIEW

**Comment by pento** [comment]
Hacking this into `::parse()` (and `$prepre` handling into `peg_join_blocks()`) improves `pygmalian-raw-html.html` from a 1x increase to a 6x increase. (In raw numbers, ~420ms down to ~60ms.)

```php
	$prepre = '';
	for ( $ii = 0; $ii < $this->input_length - 3; $ii++ ) {
		if (
			'<' === $this->input[ $ii ] &&
			'!' === $this->input[ $ii + 1 ] &&
			'-' === $this->input[ $ii + 2 ] &&
			'-' === $this->input[ $ii + 3 ]
			) {
				break;
			}

			$prepre .= $this->input[ $ii ];
	}

	if ( $ii === $this->input_length - 3 ) {
		$prepre .= $this->input_length[ $ii ]
				. $this->input_length[ $ii + 1 ]
				. $this->input_length[ $ii + 2 ];

		$this->cleanup_state();
		return array( array( 'attrs' => array(), 'innerHTML' => $prepre ) );
	}

	if ( $ii > 0 ) {
		$this->input = array_slice( $this->input, $ii );
		$this->input_length -= $ii;
	}
```

**Comment by gziolo** [comment]
I moved `blocks/api/post.pegjs` to its own package in #7664. It generates new JS file for parser out of updated grammar every time you run `npm install`, `npm run dev` or `npm run build`. Let's make sure it gets properly regenerated with the proposed changes.

**Comment by nylen** [comment]
> It's a pity that the pegjs model parses an array instead of char-by-char, making this function necessary.

It sounds like this is the thing to fix here.  [phpegjs](https://github.com/nylen/phpegjs) does this to avoid issues with the ways multibyte char handling differs in JS vs PHP, see https://github.com/WordPress/gutenberg/pull/1775.

I think that when the grammar rules themselves do not contain multibyte chars (like the Gutenberg grammar), we should be able to work directly with a string instead.  How can we test and prove that?

> I've also enabled pegjs' internal caching on the PHP parser, as this appear to give a decent boost, too.

How does this change affect memory usage during parsing?

**Comment by dmsnell** [comment]
Thanks for working on this @pento.

I think that this will end up failing the `Block_List` won't it if we have a normal HTML comment somewhere before the first block?

I've got mixed feelings too about optimizing the grammar itself. I know we have need but I'd rather see us build a new implementation of the PHP parser by hand which conforms to the grammar. We _do_ have ways of automating the tests and performance of alternate parsers.

Since the grammar isn't all that complicated I think we can make a good one by hand that is faster than the generated one. I'd love it if we can keep the _intention_ and _specification_ as clear as they can be.

**Comment by pento** [comment]
> I think that when the grammar rules themselves do not contain multibyte chars (like the Gutenberg grammar), we should be able to work directly with a string instead. How can we test and prove that?

Yah, that should be possible. UTF-8 encoding requires that only ASCII characters can have the `0xxxxxxx` bit structure, all other characters (including single-byte UTF-8 characters) must be made of bytes that have variations of the `1xxxxxxx` bit structure. So, it's not possible for an ASCII character to match any part of a UTF-8 character.

> I think that this will end up failing the Block_List won't it if we have a normal HTML comment somewhere before the first block?

Maybe, I didn't test it that much. 🙂

> I've got mixed feelings too about optimizing the grammar itself. I know we have need but I'd rather see us build a new implementation of the PHP parser by hand which conforms to the grammar.

This is another viable option if the [PCRE parser](https://github.com/Hywan/gutenberg-parser-rs/blob/php_fallback/bindings/php/pure/ParserPCRE.php) doesn't work out. 

I tend to agree that, rather than optimising the grammar, a better focus would be on improving `phpegjs` performance for cases that are valuable to us, though that gets a bit tricky with the current grammar. For example, `$("<!--" .)*` could pretty clearly be optimised to use `strpos()` to find the next occurrence of `"<!--"`, grab everything that happened before it, and move the `currPos` forward. Optimising `$(!Block .)*`, on the other hand, which could benefit from exactly the same optimisation, would be significantly more involved.

Hand-coding a PHP parser is an option that would probably give us better memory usage than PCRE, but I don't know how well it would do on time. It would also be less than fun to maintain, if we were to make significant changes to the grammar.

Anyway, thanks for the thoughts, y'all. I'm going to close this for now, pending the outcome of the significantly more advanced experiments in PCRE parsing.

**Pull request closed without merging**
