### PR TITLE
Fix: DatePicker missing focus on datepicker #15929

### LINKED ISSUE #15929: Datepicker: selected date missing focus styling
When tabbing through the datepicker, non-existent focus styling on the selected date makes it look as though focus has been lost:

To reproduce:

1. Write a new post.
2. Open the sidebar and select the date to open calendar.
3. Press "Tab" 7 times to select the currently-selected date.
4. No focus indicator is shown around the current selection.

I'd recommend using a much louder focus style than the existing browser-default outline—probably matching the focus ring style used on other components.

### PR DESCRIPTION
**Pull request by senadir**
closes #15929

## Description
add border to days on focus, also darken the selected day background color on focus

## How has this been tested?
- open editor
- select publish date or any component that use datePicker
- tab your way around days

## Screenshots 
image

## Types of changes
Bug fix

## Checklist:
- [x ] My code is tested.
- [x ] My code follows the WordPress code style. 
- [x ] My code follows the accessibility standards. 
- [x ] My code has proper inline documentation. 
- [x ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by kjellr** [comment]
Thanks, @senadir! The border on days looks great, but can we try using `box-shadow` to replicate something like that fr the focus+selected state instead of just the darkened blue? For example: 

Frame 5

You can check out [the Button block](https://github.com/WordPress/gutenberg/blob/20582e5368ab5de2157ebfe33c38aa08c5e287dc/packages/block-library/src/button/editor.scss#L29-L35) for an example of how that's been handled in the past.

**Comment by afercia** [comment]
Discussed during today's accessibility bug-scrub. Needs testing but as a general feedback, any _shape_ with sufficient contrast that indicates focus would be fine.

Reminder: to support Windows High Contrast Mode, there's the need to use a transparent `outline`, see other usages across Gutenberg.

**Comment by senadir** [comment]
as a side note: after @kjellr & @afercia comments, I feel like a unified design system should be put in place? is there any implementation of such sort? colors used, components, best practices, methodology? has there been any discussion about this? a design system will not only benefit contributors but third party integrators as well. I have a good experience in building & documenting design systems and I would like to participate if there's anything of that sort

**Comment by kjellr** [comment]
> I feel like a unified design system should be put in place? is there any implementation of such sort? colors used, components, best practices, methodology? has there been any discussion about this?

Yes! The design team has been discussing this frequently, and we're starting to get this going by thinking through, standardizing, and documenting all the components used in Gutenberg. 

Here's an example of some of that work, related to creating a [Figma](http://figma.com) library of all visual components: 
https://make.wordpress.org/design/2019/05/17/discussion-how-do-we-organise-figma-libraries/

And here's an example of some of the documentation work: https://github.com/WordPress/gutenberg/pull/16038

We don't have a consolidated place to check the status of the work at the moment, but following along at https://make.wordpress.org/design/ is a great start. We'd love your help if you're interested! You can comment there to get started, or join the weekly design team chat in [Slack](https://make.wordpress.org/chat/) (Wednesdays at 18:00 UTC in the [#design](http://wordpress.slack.com/messages/design/) channel)

**Comment by senadir** [comment]
just about the slack thing, I can't recover my account, who should I contact?

**Comment by kjellr** [comment]
> just about the slack thing, I can't recover my account, who should I contact?

Try sending an email to `forum-password-resets@wordpress.org` — they may be able to help you get sorted out.

**Comment by senadir** [comment]
as with my conversation
 with @kjellr on slack, this still needs more a11y testing before merging since I'm not sure how it will work on Windows high contrast mode

**Comment by afercia** [comment]
Discussed during today's accessibility bug scrub. As per the normal focus style, anything that's a visible _shape_ is fine.

For Windows high contrast mode Gutenberg is using a specific pattern: a transparent outline that's visible only in Windows high contrast mode. 

That's because Windows high contrast mode removes backgrounds and box-shadows. Only borders and outlines work. Please refer to buttons or other implementations for more details. Thanks for working on this!

**Comment by kjellr** [comment]
Hey @senadir! 

I just took this for a spin. Just want to note that we'll need to make sure that we implement this in a way that the `box-shadow` is applied outside of the numbers: 

outside

That way, we'll have both a color and size change, which is necessary for better accessibility. This should be achievable if we also adjust the border spacing (and if necessary, the size of the calendar days) a little bit.

**Comment by ItsJonQ** [comment]
Hi all! 👋 

Just checking out this PR. This initiative looks great! Thank you @senadir !
With the feedback from @kjellr + @afercia , are you able to proceed?

Thanks again!

**Comment by tellthemachines** [comment]
Hi @senadir , thanks for working on this!

I checked your changes on Windows in high contrast mode, with both Edge and Firefox, and the outlines on focus are working fine:
negativeoffset

However, there's no way of telling which day is currently selected:
selectioninvisible

I'm not sure if that's out of scope for this PR, as design might want to have a think about the best way to handle this. One possibility would be removing borders from all but the selected date, so high contrast would then show the circular border on selection, and it would still be easily distinguishable from the outline that's used on focus. Perhaps @kjellr could help out here?

One other thing that perhaps _could_ be fixed as part of this PR is the contrast of the selected date, as reported in #15278. 
Tl,dr: the blue background on the selected date has insufficient contrast with the white text. It can be easily fixed by using a slightly darker shade of blue, same as we've done for the Publish button. That would mean changing `background` to `theme( button )` in `.CalendarDay__selected`. perhaps the hover and focus styles could also adopt that darker shade.

Thanks again, and sorry for causing scope creep 😅

**Comment by jasmussen** [comment]
Hi folks. This PR seemed slightly abandoned, so I took the liberty of taking the learnings from this PR and the conversation here, to create #21600 as an alternative.

**Comment by jasmussen** [comment]
I fixed this in 21600, so closing this one!

**Pull request closed without merging**
