### PR TITLE
Fix permissions warning showing when inserting a navigation block

### LINKED ISSUE #41858: Inserting a navigation block shows a 'You do not have permissions ...' error
### Step-by-step reproduction instructions

1. Insert a navigation block
2. See a snackbar message saying 'You do not have permissions to edit this menu ...'

Expected: no message about not having permissions - I haven't created a menu yet.

### Screenshots, screen recording, code snippet

Screen Shot 2022-06-22 at 4 03 01 pm

### Environment info

- Mac OS / Brave

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by talldan**
## What?
Fixes #41858, an incorrect permissions warning was showing 

## Why?
I think the main reason for the bug is that `canUserUpdateNavigationMenu` is `undefined` in this situation, so `! canUserUpdateNavigationMenu` resolves as truthy. One way to fix it might be to make this a more explicit `canUserUpdateNavigationMenu === false`, but I don't know specifically if that'd be the right thing to do and what other values that variable can have.

## How?
This message should only show when the navigation block has an active navigation menu selected/assigned. There's no check for that, so I've added one (checking for the `ref` being truthy).

## Testing Instructions
1. Add a navigation block in the post editor
2. There should be no snackbar permissions message

### CODE REVIEW

**Comment by adamziel** [comment]
@talldan good spot!

It can be `true`, `false`, or `undefined` at the moment. It would be easier to reason about if the `hasResolved` part didn't say `true` in this case, though.

I'd change this fragment instead:

https://github.com/WordPress/gutenberg/blob/e5429075c59fc0b5048c27714c0b3d5c721f04e8/packages/block-library/src/navigation/use-navigation-menu.js#L49-L53

To say:

```js
				canUserUpdateNavigationMenu: canUpdate,
				hasResolvedCanUserUpdateNavigationMenu:
					ref && hasResolvedPermissions,

				canUserDeleteNavigationMenu: canDelete,
				hasResolvedCanUserDeleteNavigationMenu:
					ref && hasResolvedPermissions,
```

**Comment by getdave** [comment]
Thank you for the fix 👏 

This seems like a regression. Should we add a test for it or do we want to avoid another potentially flaky test?

**Review by getdave — APPROVED** [review]
I tested and was able to replicate the Issue on `trunk`. I switched to this branch and it was fixed. 

Thank you 👏

**Comment by getdave** [comment]
> canUserUpdateNavigationMenu

If there is no menu then this should be falsey. In fact any call to the hook when the `ref` is empty should result in falsey values right?

**Comment by talldan** [comment]
> Should we add a test for it or do we want to avoid another potentially flaky test?

I'm migrating the tests to playwright at the moment, which is how I discovered the bug. I think it may be a bit tricky to write a test that catches this, as it's always difficult to check for the absence of something. We can try asserting `expect( snackbarMessage ).not.toBeVisible()`, but that may still pass incorrectly if there's any kind of delay showing the snackbar message.

> If there is no menu then this should be falsey. In fact any call to the hook when the ref is empty should result in falsey values right?

I think it depends on the question being asked. If it's "can I update or delete the current menu", then it should probably be `undefined` when no menu is set to indicate it couldn't be determined. If it's "can I update or delete any menu", then maybe it should have a boolean value. I don't know what level of granularity the permissions system has in WordPress, so not sure which is right.

> I'd change this fragment instead:

I'll go for something like this `ref ? hasResolvedPermissions : undefined`, just in case `ref` is set to `null` or `0` by other code 😅 .

**Comment by getdave** [comment]
> I think it depends on the question being asked. If it's "can I update or delete the current menu", then it should probably be `undefined` when no menu is set to indicate it couldn't be determined. If it's "can I update or delete any menu", then maybe it should have a boolean value. I don't know what level of granularity the permissions system has in WordPress, so not sure which is right.

From what I remember the permissions are on a per post (menu) basis. So you can ask "can I update Menu X" but not "can I update all menus". I wish I'd written this down when I was working on the permissions feature of Nav block but turns out I didn't so I can't be 100% sure. I remember discussing with @spacedmonkey who has a very good understanding of the permissions system.

I agree regarding `undefined` (i.e. `falsey`).

**Pull request merged**
