### PR TITLE
Image: Batch image edits

### LINKED ISSUE #22566: Add transform effects to image editing
Follow-up from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-607087425

Flip and rotate can be animated to give visual feedback before the image has finished processing. The flip effect appeared in the initial prototype, but was lost during some of the edits.

rich image flip prototype

### LINKED ISSUE #22579: Queue up image edits to only apply once all edits are complete
Follow-up from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-623770557

> Wondering what would be a good way to handle multiple actions all at once, so normal editing operations do not have to "edit" the image and add new files. (The old image editor in WP "stores" the actions in an array (which also allows for easy undo/redo) and generates only a temp preview image. The actual changes are applied to the original image on save).

Similarly to the crop view, we might have an 'edit' view. We could apply each change on the frontend using the image transformations from #22566. Queue up the effects and have an apply button or even maybe only apply the transformations when the draft is saved or published. I'm not sure if it would be easy or even possible to have everything apply on save, but I think that could make for a better user experience.

### LINKED ISSUE #22580: Adjust image editing naming schema
Follow-up from https://github.com/WordPress/gutenberg/pull/21024#issuecomment-623770557

> I'm not that fond of the naming schema. crop-21-41-35-20-rotate-180-crop-21-41-35-20-IMG_20190825_104317-scaled-300x225.jpg doesn't sound particularly good (compared to IMG_20190825_104317-scaled.jpg) and will easily exceed the max file name length allowed on some filesystems.

If we had a reference to the original, unedited, image stored and we did the batched edits from #22579, we could better calculate a name for images. The order of operations is still important, so rotate-90-scale-300x255 is different from scale-300x225-rotate-90.

I like that the current implementation includes the unique edits that were made to the image so an edit doesn't have to be made if there's already a matching filename. It also has the benefit of making it easy, when browsing your media, to know which edits have been made if you had a couple different crops and were comparing between the two. A more reliable way to test for sameness could be to store an checksum of the image and compare against that instead.

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Adds the ability for edits to be previewed in the browser before saving the file on the backend.

TODO

## How has this been tested?

TODO

## Screenshots 

TODO

## Types of changes

Fixes #22580
Fixes #22579 
Fixes #22566

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
@ajlende What's left here?

**Comment by ajlende** [comment]
The quick list is:

1. Clean up and organize the REST API code. It isn't very readable right now, old routes can probably be removed, etc.
2. Decide on a naming schema for edited images now that all edits happen at once.
3. Add crop CSS previews.
4. Show rotated and flipped images in crop mode. `react-easy-crop` supports rotation, but not flipping, so I'm going to have to figure out a way around that.
5. Fix container height when rotating. `transform: rotate()` doesn't update layout, so the image width isn't correct and it's still overlapping things above and below it right now.
6. Adjust the toolbar and edit flow to match the mockups that @jasmussen made (https://github.com/WordPress/gutenberg/issues/22579#issuecomment-637988232)

I'm afraid there isn't going to be a way around this being a big PR. Lots of the changes are interconnected.

**Comment by ellatrix** [comment]
> Decide on a naming schema for edited images now that all edits happen at once.

What are the options? If it's marked as experimental, we can still change it in the coming days.

> Add crop CSS previews.

I think we'd like to move towards previewing in JS (using a blob url). This would be the closest structurally to replacing the src afterwards. I wouldn't get stuck too much on the previews in this PR.

**Comment by ellatrix** [comment]
I'm wondering if we'll have to roll our own cropper/editor. This component could also be combined with the resizer that we currently have. If we reuse the same element, this would also avoid a re-render between view and edit mode (avoiding an image reload).

**Comment by ajlende** [comment]
@spacedmonkey Maybe it would be part of the answer? Right now the existing endpoints for crop/rotate/flip each generate a new image, and one of the main purposes of batching was to avoid that. Even if we passed a filename or overwrite flag, writing to disk for each image edit also seems like it might be quite slow. I'd also like to maintain the statelessness of the endpoints, so I wouldn't want to make the existing endpoints just queue up and not apply the edits. That's why I ended up with a new endpoint. I hadn't seen that trac ticket yet, so if you have other suggestions I'd be happy to hear 🙂

**Comment by ellatrix** [comment]
If we're blocked at flipping the image, could we temporarily remove that option?

**Comment by paaljoachim** [comment]
This seems more like a feature that could use time to mature in the Gutenberg plugin before being added to core. I would suggest holding off on 5.5 and instead give it more time and then add it to 5.6.

**Comment by ellatrix** [comment]
I've merged #23284. I hope we can easily build further on that. :)

**Pull request closed without merging**
