### PR TITLE
Block Gap: Fix block spacing control for axial gap supported blocks

### LINKED ISSUE #61849: Layout Styles: Adding block gap global styles does not work for Columns block
### Description

The application of block gap styles globally for Columns blocks works in the site editor but not the frontend or post editor. It does appear to be working for other blocks such as the Cover block.

### Step-by-step reproduction instructions

1. Navigate to Appearance > Editor
2. Add Columns and Cover blocks to a page and give them some content
3. Navigate to Global Styles > Blocks > Columns and give it some block gap
4. Confirm the Cover block displays the block gap in the editor
5. Save and view on the frontend. Notice the lack of block gap
6. Back in the site editor, adjust the global block gap style for the Cover block
7. Save the page and confirm it is rendered correctly in both the editor and frontend

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/60436221/647b0d54-c417-49e4-9d5f-f1e4d7708baa

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes: https://github.com/WordPress/gutenberg/issues/61849

## What?

Fixes issue affecting blocks adopting axial block gap support when theme sets shorthand string value.

## Why?

Previously, when a block adopting axial block gap support had a simple string value assigned to `blockGap` within a theme, the string value wasn't handled correctly. 

The block spacing control would expect a full block gap value object but instead get a non-axial value (an object with only `top` defined). This resulted in incorrect styles being generated where the "single" value was assigned to the row gap and `0` to the column gap. Any adjustment of the theme's value in Global Styles would break the gap styles.

## How?

Make the conversion of simple string values to a gap value object, aware of whether the block has axial support or not.

## Testing Instructions

For testing you'll need a theme that assigns a string value to `blockGap` within a block type's styles. The easiest option will be to test with TT5 as it does this for both the Columns and Buttons blocks.

1. Create a post and add content containing various types of blocks that have blockGap support e.g. Group, Cover, Columns, Buttons, Social Links etc.
2. Adjust the block spacing within Global Styles for each block with gap support. 
3. Check that each block's spacing is correct in both the editor and on the frontend.
4. Make sure to confirm non-axial gap supported blocks still function (i.e. those that simply set `"blockGap": true` within their block.json supports.
5. Test tweaking theme.json `blockGap` styles to use different values e.g. simple strings, presets, or an object specifying different gaps per side (`top` and `left`)

<details>
<summary><strong>In case it helps, here's a snippet of block markup covering multiple gap supported blocks</strong></summary>

```html
<!-- wp:cover {"customOverlayColor":"#965151","isUserOverlayColor":true,"minHeight":176,"minHeightUnit":"px","layout":{"type":"constrained"}} -->
<div class="wp-block-cover" style="min-height:176px"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim" style="background-color:#965151"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"textAlign":"center","fontSize":"xx-large"} -->
<h2 class="wp-block-heading has-text-align-center has-xx-large-font-size">Cover</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"backgroundColor":"accent-5"} -->
<div class="wp-block-column has-accent-5-background-color has-background"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"backgroundColor":"accent-6"} -->
<div class="wp-block-column has-accent-6-background-color has-background"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"style":{"color":{"background":"#e0edf4"}}} -->
<div class="wp-block-column has-background" style="background-color:#e0edf4"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:social-links -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"w","service":"wordpress"} /-->

<!-- wp:social-link {"url":"w","service":"bluesky"} /-->

<!-- wp:social-link {"url":"w","service":"facebook"} /-->

<!-- wp:social-link {"url":"w","service":"twitter"} /-->

<!-- wp:social-link {"url":"w","service":"youtube"} /--></ul>
<!-- /wp:social-links -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button 1</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button 2</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button 3</a></div>
<!-- /wp:button -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">Button 4</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>Text in a grouped paragraph.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Text in a grouped paragraph.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```
</details>

## Screenshots or screencast 

https://github.com/user-attachments/assets/35e395d7-10e1-4b3b-99b2-9323ab5a1d58

### CODE REVIEW

**Review by andrewserong — COMMENTED** [review]
I only had a quick change to take this for a spin, but it's testing nicely for me so far! If there's still time, this feels like a nice fix to get in for 6.7 to me, and good idea treating the string-based value as a single value that we then pass along to an object representation of the gap 👍

I'll give it another test / review tomorrow if this it still open by then.

**Review by t-hamano — COMMENTED** [review]
I recalled that I was trying to attempt to solve a similar problem with the #65306. The implementation is slightly different, but the logic being attempted looks largely the same 👍

**Comment by getdave** [comment]
Thanks to everyone for their work here. I trust you'll understand that I've taken the liberty of removing the Backport label as there is no guarantee this can be included in 6.7.

The final RC3 has been cut and if any final fixes are pushed to the 6.7 release they need careful discussion and approval from release leads. I appreciate your understanding here.

From the Issue I note that this problem has been evident for some time:

> I've been digging into this issue and it appears to have been around for a long time

Therefore I'm proposing that this fix does not meet the criteria for inclusion in any final RC prior to release. It also doesn't _appear_ to be a critical PR that would _significantly_ impact lots of sites. Please advise if I'm wrong.

As a result I think it should be punted to 6.7.1 but I'd appreciate a confidence check from @kevin940726 @ndiego and @colorful-tones.

**Comment by getdave** [comment]
@juanfra @carolinan Does this issue _significantly_ impact TT5?

**Comment by carolinan** [comment]
I have not seen this issue, so not significantly? It depends how much trouble it is to add it this late. If there is an RC later today then maybe it can be included?

**Comment by ndiego** [comment]
> As a result I think it should be punted to 6.7.1 

Yes. I am all for fixing this issue asap, but we are running out of time on 6.7. If this issue was not introduced in 6.7 and does not directly impact TT5, it should be punted.

**Comment by getdave** [comment]
> If this issue was not introduced in 6.7 and does not directly impact TT5, it should be punted.

This is my logic also.

**Comment by juanfra** [comment]
It is testing nicely for me. I believe the issue doesn't directly impact TT5. The fix will be a nice improvement for parity between the editor and the site. 

However, I also agree that as it wasn't introduced in 6.7, we may want to punt it.

https://github.com/user-attachments/assets/86be96d6-e256-4bc7-9b99-60a86c6123ee

**Comment by aaronrobertshaw** [comment]
Thank you everyone for weighing in. I'm happy to defer to the consensus of punting this to a point release.

> If this issue was not introduced in 6.7 and does not directly impact TT5, it should be punted.

To be clear though the issue this PR fixes does directly impact TT5.

You can see where [TT5 assigns a string value for `blockGap`](https://github.com/WordPress/twentytwentyfive/blob/trunk/theme.json#L232-L241) to blocks that expect axial gap values i.e. Columns, Buttons etc. With string values assigned there, a user cannot adjust spacing for Columns or Buttons blocks via Global Styles.

So, yes, the bug wasn't introduced in 6.7 but TT5's use of shorthand string values exposes the bug more prominently in this release.

> Does this issue significantly impact TT5?

The emphasis on _significantly_ here is the key. 

It definitely isn't critical but I don't think it's accurate to say the bug doesn't directly impact TT5. Hence this long-winded comment for anyone coming to this issue post-release 🙂

**Comment by ramonjd** [comment]
>  I also agree that as it wasn't introduced in 6.7, we may want to punt it.

+1

**Review by ramonjd — APPROVED** [review]
Tested on TT5 according to instructions. 

Split block gap controls appear and work correctly with shorthand values.

Here's the columns block global styles control:

| Trunk | This PR |
|--------|--------|
| Screenshot 2024-11-07 at 11 04 33 am | Screenshot 2024-11-07 at 11 05 12 am |

**Review by andrewserong — APPROVED** [review]
This is testing nicely for me and I haven't been able to fault it:

✅ Confirmed the issue in TT5 (or TT4 with the Buttons block)
✅ With this PR applied, for Axial controls, they're now consistently available in global styles when a string-based value is used, and making adjustments using the block spacing controls works as expected
✅ Blocks that do not use axial controls (e.g. Cover) continue to work as expected

From my perspective this would be a nice-to-have if there's another RC happening, as it fixes a bug that's present in TT5. While adjusting block spacing on particular blocks isn't a particularly visible bug in common usage (i.e. I imagine most people won't be adjusting this), for folks that do go to make adjustments this bit of the UI will likely feel broken without this fix.

That said, given how soon 6.7 is to coming out, punting to 6.7.1 also sounds reasonable to me, if we're comfortable with this being a known issue with the TT5 theme / GB behaviour.

LGTM!

**Pull request merged**
