### PR TITLE
remove comments from compiled styles

### LINKED ISSUE #43173: Compiled block styles contain a lot of trash
### Description

All block styles contain ~75 lines of comments which are not needed. For example you can take a look at https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/buttons/style.css
These comments get added to all non-minified stylesheets and they don't make any sense.

We should remove comments when these styles are getting compiled.
These files should not be minified, but all comments should still be getting removed.
I think we'll be able to do that by changing this function a bit... https://github.com/WordPress/gutenberg/blob/eb6b3ff23a58c18019b66814606f594e86711c85/tools/webpack/shared.js#L73-L94

The result would be smaller styles in the WordPress package, and easier to read/debug source code in pages

### PR DESCRIPTION
**Pull request by aristath**
## What?
Fixes #43173

### CODE REVIEW

**Comment by Mamaduka** [comment]
@aristath, should we close this in favor of https://core.trac.wordpress.org/ticket/56388?

**Comment by aristath** [comment]
Sure, makes sense to commit the one in WP instead of this one.
Closing, thanks for the follow-up!

**Comment by aristath** [comment]
I'm reopening this one because tests are failing in the Core PR: https://github.com/WordPress/wordpress-develop/pull/3095
From what I understand, this PR would first need to be merged in Gutenberg, then the one in Core can be merged once tests pass

**Comment by ndiego** [comment]
Hi @aristath I am seeing this PR on the [6.1 project board](https://github.com/orgs/WordPress/projects/46/views/1). Does this need to be backported to 6.1, or are these Gutenberg only changed. I am a bit confused 😅 If the later, can I remove this from the 6.1 board?

**Comment by aristath** [comment]
Hey @ndiego!
This needs to be merged in Gutenberg, so that the tests stop failing in the relevant Core PR. So this is basically a prerequisite for a commit that is supposed to go in 6.1 in Core 👍

**Review by cbravobernal — APPROVED** [review]
LGTM

**Comment by cbravobernal** [comment]
Hi @aristath ! 
Should this PR be cherry-picked for RC3?

**Comment by aristath** [comment]
Thank you @c4rl0sbr4v0 !

> Should this PR be cherry-picked for RC3?

This PR goes hand-in-hand with https://core.trac.wordpress.org/ticket/56388, so I'd say yes if we want to merge that PR in Core as well 👍

**Comment by peterwilsoncc** [comment]
Re backporting: I am not keen on changing the build setup like this so late in the cycle.

I'd feel differently if it affected `*.min.css` files but as it only affects users with `SCRIPT_DEBUG: true` in their wp-config.php file, I think it's safer to wait until 6.2

However, it's probably best to ask @jeffpaul @getsource and @dream-encode as the WP 6.1 tech leads.

**Comment by cbravobernal** [comment]
Let's remove the label not to be auto-included then.

**Comment by hellofromtonya** [comment]
Following up: Decision made today to punt the corresponding [Core Trac ticket](https://core.trac.wordpress.org/ticket/56388). Why?

See @peterwilsoncc's [comments above](https://github.com/WordPress/gutenberg/pull/43177#issuecomment-1289945321) and the explanation:
>It's too late in the 6.1 cycle with RC3 happening in a few minutes and final release next week. Moving this ticket to 6.2 cycle.

**Pull request merged**
