### PR TITLE
Add text columns pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a Text columns block pattern for #20345.

75240656-fc84f580-57c4-11ea-9813-9404b8114037

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"fontSize":"huge"} -->
<p class="has-huge-font-size"><strong>Sea id autem nominavi deseruisse</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:spacer {"height":53} -->
<div style="height:53px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
What if instead of relying on the "huge" font size that can change between themes, we use a heading block?

This is a cool pattern.

**Comment by enriquesanchez** [comment]
>What if instead of relying on the "huge" font size that can change between themes, we use a heading block?

@youknowriad Yeah, or we could also use a specific px value. I feel that would be preferable, assuming that we'd also don't have much control over how themes style headings

**Comment by jasmussen** [comment]
Nice.

Can we do this instead?

```
<!-- wp:columns {"verticalAlignment":null,"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"fontSize":"huge"} -->
<p class="has-huge-font-size"><strong>Sea id autem nominavi deseruisse</strong></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

The big difference is I removed a spacer above the separator, and used vertical alignment in the columns block instead. That is a more safe design.

The reason I used a big font size instead of a heading was to avoid the trouble we might get into with the margins and treatments headers have in some themes, like TwentyNineteen:

Screenshot 2020-03-09 at 15 52 12

I think as far as launching with some patterns that are interesting to use, this is good enough to go, as it is a non-trivial layout and is interesting. 

But as shown from the screenshots Enrique added, there are some things we need to tweak with global styles and others to enable the full design to come to bear. So I'd like to revisit this pattern again in the future.

On a meta level, I'd love for us to start thinking about an overarching "identity" for the block patterns, that also doesn't use lorem ipsum text or other clear dummy content. We could always use content from a public domain book, and use the same book with different excerpts across the various patterns. Not [this book](https://www.gutenberg.org/ebooks/765) but our friends at "Project Gutenberg" have many on offer.

**Comment by jasmussen** [comment]
I think we may want to wait on this one until we can colorize the separator and perhaps adjust the line height. The code creates a general pattern but doesn't look as close to the vision is perhaps it should. That way perhaps we can also tell a better story with the colors and text.

**Comment by mapk** [comment]
I agree. @enriquesanchez can you work in real text on this pattern and adopt some of the recommendations from Joen. After this, I think we can get this in.

**Comment by jasmussen** [comment]
So actually, despite my specific feedback, I think the important bit is this one: https://github.com/WordPress/gutenberg/pull/20671#issuecomment-596593817

— this pattern I made (and thank you Enrique for porting it!) does not yet meet the criteria for being worthwhile, which is: *something that we can ship today, _and_ be proud of*.

This one, in the mockup above, I'm proud of. But sans the global style features necessary to colorize the separator and tweak the line-height, I'm not. It will eventually pass the checks, but until it does, I'd pause this one. 

Thanks again.

**Comment by mapk** [comment]
Alrighty, looks like we're pausing on this.

**Pull request closed without merging**
