### PR TITLE
Remaps some font names so that they work in iOS.

### PR DESCRIPTION
**Pull request by diegoreymendez**
## Description

Remaps the font names for native so that they also work in iOS.

## How has this been tested?

Tested through: https://github.com/wordpress-mobile/gutenberg-mobile/pull/530

## Types of changes

Changes some font names in the native .js files to also work in iOS.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Unfortunately does't work on Android.
The following GIST here: https://gist.github.com/daniloercoli/14b811c39eb74abfe9ca0b6d2ba2c5e4 is a viable solution to the problem.

**Comment by hypest** [comment]
Can we use SCSS styles for this? We can have `.ios.scss` and `.android.scss` variants to differentiate the platforms and it doesn't have to be a runtime check at all.

**Comment by daniloercoli** [comment]
Font related properties need to be passed as props to the component.
We can use the CSS file variants where we set them via CSS.

**Comment by diegoreymendez** [comment]
@hypest - That's a good observation, but I think it may be better to hold on that for now, let me explain why.

Ultimately the component shouldn't define its own font... in our case the fonts we set should really be an app-level definition.

So I was hoping, right after we finish this, to make sure the fonts are passed to these components by our gutenber-gmobile JavaScript code, probably through props (and from core CSS files).  The thing is, I've been avoiding optimizations for now, since any extra files and code added at the component level is something we'll have to also delete when we move to the proposed solution.

All in all, I was hoping to scope these PRs to just making the fonts be right, and afterwards spend some time in the proposal above.

How does that sound?

**Comment by hypest** [comment]
Hmm, maybe I have missed some context here, sorry if so.

Seems to me that this PR just changes one hardcoded value to another. And as per Danilo's comment the change doesn't work on Android. So, a cross-platform solution is needed anyway.

With that as a starting point, it seems that we can use the style files already in place per platform (see the Code block's SCSS files for [android](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/code/theme.android.scss) and [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/code/theme.ios.scss)) and we can have similar for any block that doesn't already.

We also have in place a way to go at the "app level" and set variables that can be reused by any SCSS file. See the [_variables.scss](https://github.com/WordPress/gutenberg/blob/master/assets/stylesheets/_variables.scss) file. If that doesn't apply well, we can even introduce a new, dedicated for mobile global variables file and set it [here in the transformer](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/sass-transformer.js#L68-L75) on the gutenberg-mobile side.

It's more of a code-structure thing at this point and less an optimization point.

What am I missing? 🤔

**Comment by daniloercoli** [comment]
> What am I missing? 🤔

We didn't find a way yet to pass `fontFamily` to AztecWrapper via CSS.

**Comment by diegoreymendez** [comment]
@daniloercoli - This is ready for review, but please don't merge your PR to develop yet,as I have to do the actual work of making sure the title looks good in iOS.

**Review by daniloercoli — APPROVED** [review]
Nice work, really!

**Pull request merged**
