### PR TITLE
Media&Text: round position attribute on focal point save

### LINKED ISSUE #33615: Media & Text Focal Point Picker Producing Long Decimal Values
## Description
When setting a focal point on Media & Text blocks, the `background-position` value sometimes isn't rounded correctly. For examples:

- `55.00000000000001% 50%` for what should be 55% 50%
- `56.99999999999999% 50%` for what should be 57%, 50%

It does not impact every number. In my testing, I got the weird long decimals for 55-58% in both the X and Y axes.

This is extremely similar to an issue with Cover blocks in #18665 that was fixed in late 2019.

## Step-by-step reproduction instructions
1. Insert Media & Text Block
2. Set at least one focal point value to between 55%-58%

## Expected behaviour
Value in code matches value in UI.

Note: Attempting to fix the values in the code editor results in "This block contains unexpected or invalid content."

## Actual behaviour
```html
<!-- wp:media-text {"mediaId":8,"mediaLink":"https://playground.local/2012-04-22_11-21-16_856/","mediaType":"image","imageFill":true,"focalPoint":{"x":0.55,"y":"0.50"}} -->
<div class="wp-block-media-text alignwide is-stacked-on-mobile is-image-fill"><figure class="wp-block-media-text__media" style="background-image:url(https://playground.local/wp-content/uploads/2020/09/2012-04-22_11-21-16_856-1024x577.jpg);background-position:55.00000000000001% 50%"><img src="https://playground.local/wp-content/uploads/2020/09/2012-04-22_11-21-16_856-1024x577.jpg" alt="" class="wp-image-8 size-full"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…","fontSize":"large"} -->
<p class="has-large-font-size">This is a block.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text -->
```

## Screenshots or screen recording (optional)
image

## WordPress information
- WordPress version: 5.8
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, Twenty Twenty

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Firefox 91

### PR DESCRIPTION
**Pull request by walbo**
## Description

Currently, the focal point is not rounded in the Media & text block. That makes the block markup contain styles with many decimal places.

This PR fixes the problem and adds deprecation logic to keep current blocks valid.

Same logic was added to the cover block in #19183

Fixes #33615

## How has this been tested?
1. On the trunk branch, I inserted a media text block with an image and enabled "Crop image to fill entire column".
2. I set the focal point coordinates to left 56% and top 57%.
3. I checked on the code editor that the background-position was `56.00000000000001% 56.99999999999999%`.
4. I saved the post.
5. I switched to this branch and reloaded the post.
6. I verified the block was still valid and in the code editor I verified the background-position was now `56% 57%`.
7. I inserted another block with same attributes and verified in the code editor that the position was `56% 57%`.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hi, @walbo

Sorry, it looks like this PR fell through the cracks.

Do you mind rebasing this? I would be happy to help with testing 🙇 

Thank you

**Comment by walbo** [comment]
> Hi, @walbo
> 
> Sorry, it looks like this PR fell through the cracks.
> 
> Do you mind rebasing this? I would be happy to help with testing 🙇
> 
> Thank you

Yep 👍  Don't have time this week, but can fix it next week. Will tag you for a review when ready.

**Comment by walbo** [comment]
@Mamaduka Should be rebased and updated now. Sorry for the big changeset in the deprecated file. Made v1-v5 variables instead of having an huge array.

**Review by Mamaduka — APPROVED** [review]
Thank you, @walbo!

The deprecation clean-up looks good.

I tested new deprecation with a few different block setups from the pattern library, and there are no issues ✅

**Comment by walbo** [comment]
Thanks for the review and the help on testing 👍

**Pull request merged**
