### PR TITLE
Site editor: Fix e2e tests navigation panel

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
Change template name in E2E to match the current naming.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jeyip — COMMENTED** [review]
Do we want to update the "Front page" string in `packages/e2e-tests/specs/experiments/multi-entity-saving.test.js:209` as well?

**Comment by jeyip** [comment]
I ran both tests locally. The multi-entity editing test is still passing 🎉 I'm curious though -- did you happen to run into any problems with `Template Part › Template part block › Should load customizations when in a template even if only the slug and theme attributes are set.` returning a 404 error?

I'm pretty certain the issue is something with my local testing environment because of the nature of the error and the fact that it's passing without issue in Github Actions, but I was wondering if you saw anything similar.

Either way, +1 when my question about "Front page" in `multi-entity-saving.test.js` is resolved.

**Comment by david-szabo97** [comment]
> Do we want to update the "Front page" string in `packages/e2e-tests/specs/experiments/multi-entity-saving.test.js:209` as well?

Gotcha! Updated that as well. Thanks!

> I ran both tests locally. The multi-entity editing test is still passing 🎉 I'm curious though -- did you happen to run into any problems with Template Part › Template part block › Should load customizations when in a template even if only the slug and theme attributes are set. returning a 404 error?

E2E tests aren't working for me locally at all 😄

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
> E2E tests aren't working for me locally at all 😄

Is your current workflow to wait for github actions jobs to pass? 😿  

If you ever need something run quickly, feel free to ping me if you see me online. I'm happy to checkout your branches for a little bit and run tests locally until you you get your e2e testing environment ironed out 🙂

**Comment by Addison-Stavlo** [comment]
These axe-core error failures look unrelated as they seem to be happening on all PRs currently.   It looks like the axe is having problems injecting into the iframe / block previews (and does it even make sense for it to be since it is a disabled preview in the first place).  🤔

**Comment by Addison-Stavlo** [comment]
Also noting that the changes like 'Front Page' don't seem to fix any failures that I am able to reproduce locally or seeing on current CI checks? 🤔   These e2e's are a pain.

**Comment by david-szabo97** [comment]
> Is your current workflow to wait for github actions jobs to pass? 😿

Yes 😅 

> If you ever need evaluated quickly, feel free to ping me if you see me online. I'm happy to checkout your branches for a little bit and run tests locally until you you get your e2e testing environment ironed out 🙂

Thank you! I will ping you next time!

> Also noting that the changes like 'Front Page' don't seem to fix any failures that I am able to reproduce locally or seeing on current CI checks? 🤔 These e2e's are a pain.

I saw an E2E test fail on one of the PRs that said it can't find the `Front page` template. So I thought this might fix that 😄 AFAIK XPath contains is case sensitive so it would make sense for those tests to fail.

**Comment by Addison-Stavlo** [comment]
> I saw an E2E test fail on one of the PRs that said it can't find the Front page template. So I thought this might fix that 😄 AFAIK XPath contains is case sensitive so it would make sense for those tests to fail.

Yeah.  I have seen that before as well.  I cant get consistent results from either CI or local though, which is strange.  You think it would fail consistently?  Either way, the changes here still make sense to me.

**Comment by david-szabo97** [comment]
I think it should fail consistently, since XPath is case sensitive. But I can't say it for sure since E2E tests are kinda unreliable 😅

**Comment by jeyip** [comment]
> I think it should fail consistently, since XPath is case sensitive.

I wasn't able to have it fail consistently in my local environment. I do, however, remember seeing the failure that you're describing pop up non-deterministically (it resolved itself on a rerun). 

I agree with Addie. I'd expect it to fail consistently as well. The changes make sense either way, and my hope is that they solve the non-deterministic failures.

**Review by Addison-Stavlo — APPROVED** [review]

**Review by Copons — APPROVED** [review]
Changes make sense to me.

**Pull request merged**
