### PR TITLE
[RNMobile] [Embed block] Generic “No Preview” Embed preview UI

### PR DESCRIPTION
**Pull request by jd-alexander**
`gutenberg-mobile` PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/3927

## Description

Implements the Generic **No Preview** Embed preview UI when an embed is successful, but we're unable to show an inline preview.

## How has this been tested?
⚠️ I have not been able to find an Embed that recreates the scenario described below. I will continue my investigation to find a suitable candidate for testing. 

I thought any Facebook URL would work since its embed definitions have `previewable` as `false`. However, I wasn't able to get `false` when the embed was fetched.

Therefore I had to set `previewable` to `false` programmatically for the UI to be rendered via the logic below. 

https://github.com/WordPress/gutenberg/blob/f155d2744192fbdf958f0ce074956664b60e92aa/packages/block-library/src/embed/embed-no-preview.native.js#L206

1. Add an Embed block. 
2. Embed an URL that can be embedded but has no preview. 
3. Notice that the "No preview available" UI is displayed. 

## Screenshots 

<kbd></kbd>

## Types of changes

The main changes that were implemented here are the `NoEmbedPreview` component was consolidated to support both the Provider **Coming Soon UI** and the Generic **No Preview UI**.

1. `isProviderPreviewable` ( false), `previewable` ( true) - this should show the Provider **Coming soon UI** if the previewable is set to true but the provider doesn't allow previews. Therefore the bottom sheet should open. 

2.  `isProviderPreviewable` ( true), `previewable` ( false) - This should show the Generic **No Preview UI**, since the content cannot be previewed at all. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by fluiddot** [comment]
> ⚠️ I have not been able to find an Embed that recreates the scenario described below. I will continue my investigation to find a suitable candidate for testing.
>
> I thought any Facebook URL would work since its embed definitions have previewable as false. However, I wasn't able to get false when the embed was fetched.

Right, the Facebook URL in theory should have the attribute `previewable` as `false` as is set in its variant:
https://github.com/WordPress/gutenberg/blob/d3a512834b47ccada9e5e0d574b8a7c0bf159c13/packages/block-library/src/embed/variations.js#L70

However, I checked that that the preview data returns the provider name with the value `Embed Handler` (generic embed), so unlike Instagram, it's picking the generic variant instead of Facebook.

I noticed that on the web version this is working on sites with Jetpack, so I investigated this further and I realized that we would need to incorporate the embed variations from Jetpack to enable this.
- [Embed variants index](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/extensions/extended-blocks/core-embed/index.js)
- [Facebook variant](https://github.com/Automattic/jetpack/blob/edbb7f3197ff9f284e7ba5e622dab15b879be07b/projects/plugins/jetpack/extensions/extended-blocks/core-embed/facebook.js)

Although this would require refactoring a bit how we integrate blocks from Jetpack because these variations overwrite the core ones ([reference](https://github.com/Automattic/jetpack/blob/edbb7f3197ff9f284e7ba5e622dab15b879be07b/projects/plugins/jetpack/extensions/extended-blocks/core-embed/facebook.js#L29-L67)). This means that we would need to import the Jetpack's embed variations before registering the core blocks for this purpose.

I wouldn't block this PR due to this issue but it would be nice if we open a new issue as a follow-up.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**NOTE:** I posted [this comment](https://github.com/WordPress/gutenberg/pull/34626#issuecomment-916866118) related to Facebook embed, it shouldn't block the PR but we should address it in the future.

**Comment by jd-alexander** [comment]
> However, I checked that that the preview data returns the provider name with the value Embed Handler (generic embed), so unlike Instagram, it's picking the generic variant instead of Facebook.

> I noticed that on the web version this is working on sites with Jetpack, so I investigated this further and I realized that we would need to incorporate the embed variations from Jetpack to enable this.

Thanks for the insights and investigative work @fluiddot 😄  It would make sense for us to integrate the Jetpack blocks eventually. 

> I wouldn't block this PR due to this issue but it would be nice if we open a new issue as a follow-up.

I created an issue to track this https://github.com/wordpress-mobile/gutenberg-mobile/issues/3951

**Comment by fluiddot** [comment]
> > I wouldn't block this PR due to this issue but it would be nice if we open a new issue as a follow-up.
> 
> I created an issue to track this [wordpress-mobile/gutenberg-mobile#3951](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3951)

Thank you so much for opening the issue ❤️ .

**Pull request merged**
