### PR TITLE
Font Library: Add 'No fonts installed' message on library tab when fonts aren't available

### LINKED ISSUE #63731: Font Library: Add 'No fonts installed' message on library tab
### Description

There should be a message indicating that no fonts are installed when custom fonts are removed and there are none installed. If we navigate to the library tab, it appears blank.

Additionally, the preceding action's "Font uninstalled successfully" message ought not to show up when we reopen the modal.

### Step-by-step reproduction instructions

- Go to typography styles
- Install custom fonts
- Then remove it 
- Move to library tab, you'll see blank page.

### Screenshots, screen recording, code snippet

Here is video for more details:
 
[Index-‹-Template-‹-gutenberg-‹-Editor-—-WordPress.webm](https://github.com/user-attachments/assets/5e3368b7-631f-4898-b5eb-782e5a22a8a5)

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

### PR DESCRIPTION
**Pull request by akasunil**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/63731

## Why?

There isnt any message indicating that no fonts are installed on library tab of font library modal.

## How?

This PR add message on library tab of font library modal when no fonts are installed.

## Testing Instructions

- Go to typography setting under global styles 
- Install custom fonts, Notice will appear.
- Remove custom fonts, reopen modal, Notice should be removed.
- Check library tab, there will be message `No fonts installed.`
 
## Screenshots or screencast 
[Index-‹-Template-‹-gutenberg-‹-Editor-—-WordPress (2).webm](https://github.com/user-attachments/assets/549d0cbc-20eb-40b2-bed9-861c4fecf692)

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think the code is entirely correct, but the text might be better centered, like the DataViews:

image


Let's some design feedback on this.

**Comment by richtabor** [comment]
Curious, do we need a Library tab if there's no contents in the Library tab?

**Comment by t-hamano** [comment]
> do we need a Library tab if there's no contents in the Library tab?

It would also be possible to hide the Library tab when there is no font.

If we implemented this approach, the Library tab would appear the moment you add a font from the "Upload" or "Install Fonts" tab for the first time.

Another concern is what happens when you delete a font in the Library tab. I'm worried that it will be confusing if the Library tab suddenly disappears when you delete the last font.

**Comment by akasunil** [comment]
> but the text might be better centered, like the DataViews

It require to update all its parent styles to have full height.

**Review by t-hamano — APPROVED** [review]
LGTM!

> > but the text might be better centered, like the DataViews
> 
> It require to update all its parent styles to have full height. 

That's true. This will have a bit of a big impact because we'll need to adjust the styles across this content to center the text.

This wouldn't be hard to achieve if the entire modal content was composed of flex, but since that's not the case currently, we'll address this in a future follow-up.

**Comment by akasunil** [comment]
> we'll address this in a future follow-up.

Got it, ill create separate issue for it and will get feedback from design team.

**Pull request merged**
