### PR TITLE
Fix issues with Escape key while editing link

### PR DESCRIPTION
**Pull request by mkaz**
* Switch to using event.key instead of event.keyCode which is deprecated
* Add event.stopPropagation() instead of default
* Add remove event listener on unmount
* Use keydown event not keypress - keypress doesnt work with Escape key

### CODE REVIEW

**Comment by aduth** [comment]
There's a browser support consideration in choosing to adopt `key`, since it's only available in the very latest version of iOS Safari, and only has partial support in IE11: 

http://caniuse.com/#feat=keyboardevent-key

**Comment by mkaz** [comment]
@aduth ok, good point, switched back to using keyCode. 

MDN docs made it seem like it was time to switch, though in this case since its the Escape key wouldn't make much difference for iOS :-)

**Comment by aduth** [comment]
>Add event.stopPropagation() instead of default

Can you explain this change?

>though in this case since its the Escape key wouldn't make much difference for iOS :-)

Bluetooth keyboards! But yeah, edge case.

**Comment by mkaz** [comment]
Initially I had `event.preventDefault()` but switched it to `event.stopPropagation()` since I'm not trying to stop the default Esc action, but stopping the event from propagating to the above component

I want the Escape to only close the link box that this component opens and not close the block overall.

**Review by aduth — APPROVED** [review]
Looks good 👍

**Pull request merged**
