### PR TITLE
Editor: Migrate and unify the panel preferences

### PR DESCRIPTION
**Pull request by youknowriad**
Related #52632 
Similar to #57468 

## What?

This PR continues the work on the great unification between post and site editors. In this PR we're unifying the "Document settings panels" preference. If the user disables a panel in the post editor, the panel should still be hidden in the site editor.

This PR also adds the panels to the "preferences modal" in the site editor to match the post editor preferences modal.

## Testing instructions

- try enabling/disabling hiding/showing panels in the post editor.
- open a page in the site editor, notice that the panels are also the same.

### CODE REVIEW

**Comment by ramonjd** [comment]
To test I rebased to fix conflicts in migrations/preferences-package-data/convert-editor-settings.js - I hope you don't mind!

LGTM

All settings work except the accessibility labels in the site editor, but this is a trunk issue. I cleared local storage 🤔 

I'm going to have a quick look.


https://github.com/WordPress/gutenberg/assets/6458278/6065a5da-9c1d-4c61-8bca-1ab310308a4f

**Comment by ramonjd** [comment]
> I'm going to have a quick look.

PR:

- https://github.com/WordPress/gutenberg/pull/57563

**Review by ramonjd — APPROVED** [review]
LGTM[^1]

[^1]: If it looks good to @andrewserong 😄

**Review by andrewserong — COMMENTED** [review]
This is looking pretty good to me, too! It seems that the test failure for `should show the New Post page in Gutenberg` is happening locally, too. From manually testing it looks like with this PR applied, the Summary panel is defaulting to closed for that test, whereas on trunk it's open, so the check to see if the Post Format combobox fails [here](https://github.com/WordPress/gutenberg/blob/1f75b41023abfec2d627b5596b2a852dd332c085/test/e2e/specs/editor/various/new-post.spec.js#L43). Any idea why this PR would alter the open state for that panel?

Here are a couple of screenshots from manual testing locally:

| Trunk (summary panel is open) | This PR (summary panel is closed |
| --- | --- |
| image | image |

As for the behaviour in this PR, it's all working well for me manually:

✅ Settings set on `trunk` are persisted / migrated correctly when applying this PR
✅ Settings set in the post editor are reflected in the site editor and vice versa

One detail that isn't a blocker for this PR, but that I found a little confusing at first, is that which settings are visible is dependent on context. So if you open the template editor, the Document settings area is empty, but when you edit a page within the site editor, you can then see the settings available. This could make it challenging for folks wanting to quickly update settings if they're sometimes visible and sometimes not:

| Preferences while editing a template | Preferences while editing a page |
| --- | --- |
| image | image |

Would it be worth exposing all the settings available in the site editor so that folks don't need to be on a particular part of the site editor in order to see all the available settings?

**Comment by youknowriad** [comment]
I think showing all the possible panels all the time in the preferences modal has a downside of potentially confusing users: They'll try to enable a panel but that panel doesn't show up because the CPT doesn't support it for a reason. So I'm not sure it's the best path there.

I'm going to check why the default values are different, it seems a bit weird :)

**Comment by youknowriad** [comment]
Ok I've found that I was missing some initializations. Let's see if it fixes everything.

**Pull request merged**
