### PR TITLE
Latest Posts: Avoid unnecessary re-renders

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
A small performance fix. Similar to #38316.

We should avoid `map/filter/reducde` operations inside `useSelect` hook. PR updates `getEntityRecords` query arg to use `_embed` functionality for fetching featured image details.

## Testing Instructions

1. Enable "Highlight updates when components render" in React DevTools.
2. Add the Latest Posts and Paragraph blocks to the post editor.
3. Start typing in paragraph check that Latest Posts doesn't re-render as we type.

## Screenshots 

https://user-images.githubusercontent.com/240569/151954944-2e30ea1c-6e1b-4a05-ab29-66ea4a2a7b07.mp4

https://user-images.githubusercontent.com/240569/151954931-3c50246e-1f90-451c-a106-5de9f4b958cf.mp4

## Types of changes
Performance

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Looking at the "Performance Tests" results, I see that PR doesn't improve typing, but I think the Latest Post block isn't used inside test data.

**Review by ntsekouras — APPROVED** [review]
Nice cleanup George! LGTM 👍

**Comment by ntsekouras** [comment]
>>Looking at the "Performance Tests" results, I see that PR doesn't improve typing, but I think the Latest Post block isn't used inside test data.

Yeah, it isn't.

**Comment by Mamaduka** [comment]
Thanks for testing, Nik.

**Pull request merged**
