### PR TITLE
Increase specificity of .nvmrc version

### PR DESCRIPTION
**Pull request by vcanales**
## What?
Specify minimum minor version of node on .nvmrc to match the `engine` specified on package.json.

## Why?
If I have previously installed a lower node version than what's required in package.json, using `nvm use` will succeed, but `npm i` will fail. This changes moves the failure in the chain, so that it will be nvm that'll let you know that you have to install a newer version of node.

**Before:**
```sh
➜  gutenberg git:(trunk) nvm use
Found 'gutenberg/.nvmrc' with version <20>
Now using node v20.9.0 (npm v10.1.0)
➜  gutenberg git:(trunk) npm i
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: gutenberg@17.4.1
npm ERR! notsup Not compatible with your version of node/npm: gutenberg@17.4.1
npm ERR! notsup Required: {"node":">=20.10.0","npm":">=10.2.3"}
npm ERR! notsup Actual:   {"npm":"10.1.0","node":"v20.9.0"}
```

**After:**
```sh
➜  gutenberg git:(increase-specificity-of-nvm-version) nvm use            
Found 'gutenberg/.nvmrc' with version <20.10>
N/A: version "v20.10" is not yet installed.

You need to run `nvm install` to install and use the node version specified in `.nvmrc`.
```

Trac ticket: https://core.trac.wordpress.org/ticket/59663.

### CODE REVIEW

**Comment by desrosj** [comment]
Hey @vcanales! Thanks for this one. I've gone and added the corresponding Trac ticket to the PR description so that this shows up there. There's already a suggestion and a PR there for this. I expressed some thoughts around the change in the ticket, and working to gather a bit more info before making a decision. But wanted to acknowledge that I saw this!

**Comment by vcanales** [comment]
Thanks for taking a look, and for the extra context. I'll echo the questions that @kraftbj made over there, since I have the same ones:

> IMO, if the version in nvmrc could be met by versions not meeting package.json, one or the other should be adjusted (e.g. why 20.10 vs 20.x as the minimum? Is there a functional reason why 20.10 is the minimum of the LTS?)

**Comment by desrosj** [comment]
Is this still a problem? The corresponding Core ticket has been closed out.

This is really only a problem when the versions defined in `engines` is bumped to the latest version at the time because some contributors will not always have the latest release. Now that a bit of time has passed and the latest is now 20.12.2, this is less likely to be encountered.

**Comment by vcanales** [comment]
While it's true that it's less likely to happen, I don't see why we wouldn't want to keep `.nvmrc` and `package.json` versions in more precise sync.

**Comment by desrosj** [comment]
The value in `engines` is not regularly updated. If we define `20.10` in the `.nvmrc` file, then contributors would be unable to use `nvm` to easily run the latest version (`nvm install` would be stuck in the `12.10.x` range) unless we continuously update the version in the file. Instead of creating that maintenance burden, just specifying `20` fixes that with the possibility of some issues initially when the project bumps the minimum required version.

**Pull request closed without merging**
