### PR TITLE
Fix encoded characters in navigation link text

### LINKED ISSUE #30111: Navigation Block: Creating a draft page with “&” results in HTML Entities
## Description

When using the Create Draft feature in the navigation block, if you add &, it results in a draft being created showing the HTML entities for ampersand instead of &. 

This came up as part of feedback for [the third round of testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/03/09/fse-program-testing-call-3-create-a-fun-custom-404-page/#comment-1430). 

## Step-by-step reproduction instructions

1. Add the navigation block. 
2. Add a new menu item. 
3. Select adding a new link and begin typing the title of a page that doesn't exist. When you do so, include &.
4. Select the option to create a page draft.
5. See that the menu item doesn't show ampersand. 

## Expected behaviour

The & would show in the navigation block.

## Actual behaviour

HTML entities were shown in the navigation block.

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/112059251-37b93b80-8b21-11eb-9803-38e7ce6ab36c.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop 
- Operating system: MacOS
- Browser: Chrome Version 88.0.4324.192

### PR DESCRIPTION
**Pull request by donnapep**
## Description
Fixes #30111. Renders `title.raw` instead of `title.rendered`.

## How has this been tested?

1. Add the navigation block.
2. Add a new menu item.
3. Select adding a new Link and begin typing the title of a page that doesn't exist. When you do so, include &.
4. Select the option to create a page draft.
5. See that the menu item shows the ampersand.
6. Select adding a new Post Link and begin typing the title of a page that doesn't exist. When you do so, include &.
7. Select the option to create a post draft.

## Screenshots
Screen Shot 2021-03-24 at 6 59 13 AM

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gwwar** [comment]
Whoops, looks like this one got lost in the PR list. The code change here looks correct. @donnapep do you mind rebasing with trunk (or let us know if you'd like us to take over). I can help review this one

**Comment by annezazu** [comment]
Seems like this one should likely be taken over :)

**Review by getdave — CHANGES_REQUESTED** [review]
Thank you for raising this and apologies that it flew under my radar.

I've tested and I think it might be more complex than I'd hoped. Especially as it no longer appears to work.


https://user-images.githubusercontent.com/444434/168378688-5e8bd79c-f33f-4122-add5-f3f5f2297308.mov

I think this is all happened because we're escaping the title/label prematurely (i.e. before the point at which it is _rendered_).

The escaping of the label within the `updateNavigationLinkBlockAttributes` method which causes the `post.title.rendered` to be converted into an `&amp;`. This still happens with `.raw` as shown in the video above.


Normal Post links are rendered into a `<RichText>` so the escaped HTML renders correctly. However, draft pages (those created inline within the Link UI) are rendered into a `<span>` which means that the escaped HTML shows up in it's raw form.

I will raise a PR which properly applies the escaping at the point of _output_ which will allow us to be more selective in our application of escaping.

**Comment by getdave** [comment]
This was fixed here https://github.com/WordPress/gutenberg/pull/41063

**Pull request closed without merging**
