### PR TITLE
Featured image block and Image blocks: remove descendent space

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

This is an alternative to https://github.com/WordPress/gutenberg/pull/35273 while also applying it to the Image block, who also has that unwanted space between figure and image tags. 

## How has this been tested?

Insert the blocks on emptytheme, check that there's no space between the figure tag and the image tags.

## Screenshots 
Screenshot 2021-10-08 at 17 51 22

## Types of changes

Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
I wasn't even aware of this issue, and now I dearly want it fixed, so thanks so much for tackling this one. 

I can confirm that trunk shows that extra space for the Image block:
Screenshot 2021-10-11 at 08 51 30

I can also confirm this branch fixes it:

Screenshot 2021-10-11 at 08 43 20

I wasn't personally familiar with the vertical-align trick leveraged here, my instinct would naturally be to go towards the line-height fix as I've used that for similar situations in the past. What's the benefit of the vertical align trick, and are there any side effects to maybe be aware of?

**Comment by MaggieCabrera** [comment]
hi, @jasmussen thanks for having a look! To be honest I'm not sure what is the best solution here. I'm reading more about the origin of the problem [here](https://mor10.com/removing-white-space-image-elements-inline-elements-descenders/) and it recommends using `display:block;` instead. I think that could cause more problems than this or the line-height solution. I went for this one because it's actually the one that I've used in the past.

I could only thing of this maybe affecting the gallery block but it seems like there the fix is doing nothing because the gallery is already using flexbox (using anything except inline/inline-block would solve the issue). It looks the same with or without the fix:
Screenshot 2021-10-11 at 09 13 35

What I've seen is that we can't make the line height solution on the image block cause it messes up the caption:

No Line-height | Line-height: 0
--- | ---
Screenshot 2021-10-11 at 09 22 53 | Screenshot 2021-10-11 at 09 22 46

**Review by jasmussen — APPROVED** [review]
Excellent sleuthing work. This definitely seems to be the better solution over both line-height and display: block. This solution worked well in my testing. Let's try this, especially as it's so easy to follow up.

**Comment by MaggieCabrera** [comment]
Thanks Joen, I'll bring this in then!

**Pull request merged**
