### PR TITLE
Site Editor: restore block-library editor.css outside canvas

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

In #66544 @t-hamano observed that a bit too many styles have been removed in https://github.com/WordPress/gutenberg/pull/66432. Indeed, it should have kept loading `editor.css` files defined by blocks because they target both content and UI outside the canvas. The remaining styles should still be removed though. 

One light problem is that all the styles we want to remove are added as dependencies of `wp-edit-blocks`. So restoring `wp-edit-blocks` will add back all the styles we don't want. To fix the issue we can register a separate handle `wp-block-library-editor`, which exclusively loads the editor styles.

## Why?

Fix a regression from #66432.

## Testing Instructions

In content only mode, select an image and click the "alternative text" button in the toolbar.

### CODE REVIEW

**Comment by t-hamano** [comment]
This PR works for me.

My only concern is that deleting `wp-edit-blocks` or changing the handle name would be a breaking change. For example, block developers might apply their own styles to block sidebars, etc. with code like this:

```php
wp_enqueue_style(
	'my-block-common',
	'path/to/block-common.css'
	array( 'wp-edit-blocks' )
);
```

I searched the WP Directory and it seems that a lot of plugins enqueue styles that depend on the `wp-edit-blocks` handle.

https://wpdirectory.net/search/01JBC821K2ZBFBMPF7QQSP7W8K

**Comment by ellatrix** [comment]
@t-hamano 

1. Using `wp-edit-blocks` will still work. It's used in the canvas. So if you add dependencies to `wp-edit-blocks`, it should still work.
2. Blocks should never add `wp-edit-blocks` as a dependency. It should be the opposite: `wp-edit-blocks` should contain all the blocks' style sheets as dependencies.

**Comment by ellatrix** [comment]
What I mean is: nothing about `wp-edit-blocks` changes. It's all still there.

**Comment by t-hamano** [comment]
> Using `wp-edit-blocks` will still work. It's used in the canvas.

If developers are  adding a `wp-edit-blocks` handle to a dependency to enqueue a style _outside of the canvas_, the style won't be loaded outside of the canvas (root document), right?

Relying on `wp-edit-blocks` to apply styles outside of the canvas may not be a recommended use case, but I thought some dev notes might be needed.

**Comment by ellatrix** [comment]
@t-hamano I'm not sure I understand. Do you mean:

* Someone adds `wp-edit-blocks` as a dependency to their style? Even in trunk, this will not make it load outside the canvas.

Or:

* Someone adds their style as a dependency to `wp-edit-blocks`? Indeed, then the style will not load. But it's generally hard to to change the dependencies of a handle that you did not create (in this case `wp-edit-blocks`). How would this be done?

**Comment by t-hamano** [comment]
Sorry, maybe I misunderstood. I don't think this PR is a breaking change. Let me explain a bit more.

- In trunk, the style with a handle `wp-edit-blocks` is not loaded outside of the canvas.
- A third-party developer tries to apply a style outside of the canvas via code like this:
  ```php
  function my_enqueue_block_editor_assets() {
    wp_enqueue_style(
  		'my-block-style',
  		plugin_dir_url( __FILE__ ) . 'style.css',
  		array( 'wp-edit-blocks' )
  	);
  }
  add_action( 'enqueue_block_editor_assets', 'my_enqueue_block_editor_assets' );
  ```
  - What I misunderstood: their style will be not loaded outside of the canvas.
  - Actual: Both the styles with the handle `wp-edit-blocks` and their styles are loaded outside of the canvas.

Is my understanding correct?

Also, if we go ahead with this PR, do we also need a backport PR to core?

**Comment by ellatrix** [comment]
@t-hamano Ah, in that case, this PR will not make any difference? Because merely adding `wp-edit-blocks` as a dependency does not cause it to load wherever `wp-edit-blocks` is enqueued? In other words removing `wp-edit-blocks` outside the canvas does not change anything for this code.

Yes, I'll add it to https://github.com/WordPress/wordpress-develop/pull/7643 :)

**Comment by ellatrix** [comment]
In fact, it will actually undo the removal of this PR because the action is called outside the canvas: https://github.com/WordPress/wordpress-develop/blob/695476ea5e51d1c92f389ac236b138ceeaee8a99/src/wp-admin/site-editor.php#L177

**Review by t-hamano — APPROVED** [review]
Thank you for the detailed explanation.

I may not understand everything correctly, but if this PR does not affect backward compatibility, I think it's okay to ship it.

If this PR is shipped, will https://github.com/WordPress/wordpress-develop/pull/7643/ be updated?

**Comment by t-hamano** [comment]
BTW, should this PR be backported to Gutenberg 19.6? It looks like 19.6 RC1 is just about ready.

**Comment by ellatrix** [comment]
@t-hamano Yes, I'll update the core PR. Thank you for the review!

**Comment by ellatrix** [comment]
> BTW, should this PR be backported to Gutenberg 19.6? It looks like 19.6 RC1 is just about ready.

I'll check with the person doing the release.

**Comment by cbravobernal** [comment]
I just cherry-picked this PR to the release/19.6 branch to get it included in the next release: 37368403cf

**Comment by Mamaduka** [comment]
I think this introduced the following warning in the editors.

## Screenshot
CleanShot 2024-10-31 at 09 55 21

**Comment by ellatrix** [comment]
@Mamaduka Ah, will fix

**Comment by ellatrix** [comment]
@Mamaduka Fixed in #66628.

**Pull request merged**
