### PR TITLE
Delete webpack.config.js

### PR DESCRIPTION
**Pull request by brucie1080**
## Description

git remote add origin https://github.com/brucie1080/delete-tree.git
git push -u origin master
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by brucie1080** [comment]
git remote add origin https://github.com/brucie1080/delete-tree.git
git push -u origin master

**Comment by brucie1080** [comment]
git remote add origin https://github.com/brucie1080/delete-tree.git
git push -u origin master

**Comment by gziolo** [comment]
We don’t plan to remove Webpack in the upcoming weeks.

**Comment by gziolo** [comment]
We don’t plan to remove Webpack in the upcoming weeks.

**Comment by brucie1080** [comment]
You mother fuckers better delete that shit take it down whatever it is u
gotta do i promise i will sue the fuck out of u

**Comment by karmatosed** [comment]
@brucie1080 language and aggressive comments will not to tolerated against contributors. Whilst you may feel passionate about something the approach you are taking is not going to get you there. Please note I have reported your behaviour regarding this also.

**Pull request closed without merging**
