### PR TITLE
[RNMobile] Fix React Native error from function declaration hoisting

### LINKED ISSUE #3149: Inserting Gallery, Media-Text or Audio block crashes the app
**Describe the bug**
Inserting Gallery, Media-Text or Audio block crashes the app

**To Reproduce**
1. Open the editor
2. Add a Gallery, Media-Text or Audio block
3. Notice that the app crashes

**Expected behavior**
Inserting Gallery, Media-Text or Audio block does not crash the app

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020, Pixel 2 XL
 - OS: iOS 14.2,  Android 11
 - Version `gutenberg/master`:`c5ae463d0fae24cf51c54f98922bb0de382ce6e6`

**Additional context**
The issue was caused by the changes of https://github.com/WordPress/gutenberg/pull/28676

### PR DESCRIPTION
**Pull request by dcalhoun**
**Gutenberg Mobile:** wordpress-mobile/gutenberg-mobile#3150

## Description

Fixes wordpress-mobile/gutenberg-mobile#3149.

It is unknown why relying upon function declaration hoisting causes an
error in React Native, but it does occur. Recent changes with #28676
refactored a class to a functional component, including leveraging
function declaration hoisting. I.e. the function was referenced
prior to its declaration in terms of the order of the lines of code.

Re-ordering the code so that the function declaration occurs prior to
referencing it appears to resolve the error in React Native.

Related: https://git.io/JtXMm

<details>
<summary>Mobile Error</summary>

ios-function-hoisting-error

</details>

## How has this been tested?

Manually tested modifying the focal point for a Cover block in both the web editor (macOS Safari) and native editor (iOS).

## Screenshots

<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/438664/107998497-e3172380-6faa-11eb-9917-ab0aacb900e4.mov

</details>

<details>
<summary>Native Mobile</summary>

https://user-images.githubusercontent.com/438664/107998512-edd1b880-6faa-11eb-871b-6876225112a1.mov

</details>

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by stokesman** [comment]
Wow! So glad you had this idea. Thanks for looking into it! I don't think it would have ever occurred to me.

**Comment by dcalhoun** [comment]
@ItsJonQ will you please review and verify the web editor focal point picker continues to function as expected, given that was the focus of #28676?

@jd-alexander I believe these changes resolve the native mobile editor crash that was introduced in #28676. Will you please review and help verify? Also, I do not have write permissions for `gutenberg` to request reviewers or attempt to re-run the CI suite. If you are willing to help me manage that, it'd be appreciated. Thank you!

**Comment by jd-alexander** [comment]
> @jd-alexander I believe these changes resolve the native mobile editor crash that was introduced in #28676. Will you please review and help verify? Also, I do not have write permissions for gutenberg to request reviewers or attempt to re-run the CI suite. If you are willing to help me manage that, it'd be appreciated. Thank you!

Thanks, @dcalhoun I have added myself and @ItsJonQ as reviewers and I will re-run test(s) in the event any of them fail.

**Comment by stokesman** [comment]
I've tested this for web. The focal point picker is working as expected. I can't vouch for mobile as I've not yet been able to get the RN/mobile dev env working.

Also, I restarted the tests, probably a second before Joel would've seen it.

**Review by stokesman — APPROVED** [review]

**Review by jd-alexander — APPROVED** [review]
Thanks for these changes @dcalhoun 😄  I first verified that the function declaration hoisting issue existed on master and then I added your fork's remote, checked out this branch, and verified that the issue has been resolved by utilizing the blocks below since they utilize the `withNotices` HOC that was refactored in the linked PR.

Blocks tested : 
- Cover's edit focal point functionality
- Gallery
-  Media-Text
- Audio block

Thanks again for this fix.  LGTM 🚢

**Comment by gziolo** [comment]
This issue is very strange. Function hoisting is a language feature 🤷

The fix is good but it shouldn’t be necessary. I would expect many places relaying on hoisting in the repository.

**Comment by hypest** [comment]
Thanks for the fix David and thank you all for being quick at reviewing!

> The fix is good but it shouldn’t be necessary.
👋 @gziolo , can I interpret your response there as a LGTM? I can go ahead and merge if so. For context, David and Joel are a few hours away due to timezones and I'd prefer to merge and let the native editor release process resume asap. Thanks!

**Pull request merged**
