### PR TITLE
Try: Use column gap for button blocks

### LINKED ISSUE #28468: Adjust right margins for buttons that are set at 25%, 50%, and 75% widths
When a user combines button blocks of varying preset widths (25%, 50%, 75%), they will never actually take up 100% of the available space. There's always an extra margin on the right side:

Screen Shot 2021-01-25 at 12 01 40 PM

This may get pretty unweildy, but we should work out a way to ensure that various combinations of these blocks end up taking up the full 100% width when placed together.

Related: https://github.com/WordPress/gutenberg/pull/28467

### PR DESCRIPTION
**Pull request by kjellr**
Fixes https://github.com/WordPress/gutenberg/issues/28468. 

This is a redo of https://github.com/WordPress/gutenberg/pull/29165. As @mtias [pointed out](https://github.com/WordPress/gutenberg/pull/30449#issuecomment-827871967), the latest versions of Safari on Mac (v 14.1) and iOS (v14.5) both fully support `column-gap` now — even when used for `flexbox`. 🙌 I've tested this on my own devices and it works well. 

The main consideration here is that for users on older versions of Safari, this will appear broken (as shown in the screenshots in https://github.com/WordPress/gutenberg/pull/30449). I don't think there's any way around that given the issue described in https://github.com/WordPress/gutenberg/pull/30449. 

Before|After
---|---
Screen Shot 2021-04-30 at 10 46 50 AM|Screen Shot 2021-04-30 at 10 48 19 AM

### CODE REVIEW

**Comment by jasmussen** [comment]
This is great, this is beautiful, themers are going to love it:

Screenshot 2021-05-03 at 09 48 26

At some point once the dust settles, we should see if this gap could become a global styles property; since it's so easy to change and resilient, it would be nice to handle in such a neat way.

I tested the justifications. Left looks good:

Screenshot 2021-05-03 at 09 47 11

Space between looks amazing:

Screenshot 2021-05-03 at 09 47 22

Center is good:

Screenshot 2021-05-03 at 09 48 06

Right justified is given some left margin which is possibly/probably unnecessary now?

Screenshot 2021-05-03 at 09 47 40

So happy we can land this now. Thank you Kjell!

**Comment by kjellr** [comment]
> Right justified is given some left margin which is possibly/probably unnecessary now?

Good catch! I've pushed a small update to zero that out. 

How do you feel about this aspect of the problem here: 

> The main consideration here is that for users on older versions of Safari, this will appear broken (as shown in the screenshots in #30449). I don't think there's any way around that given the issue described in #30449.

I'm having trouble deciding how much of an issue that is here. 🤔 I'm sure there are some folks stuck on older versions of Safari, and this will probably look like a breaking change for them. But because of that Safari bug, I'm just not sure there will ever really be a way around that.

**Comment by jasmussen** [comment]
It's been a while since I investigated safari update mechanisms; can anyone get stuck on an old version of Safari? And if yes, can we find any browser stats to look at?

If it's mostly a matter of people updating their browsers/systems, I'd personally feel the pros to this approach vastly outweigh the downsides, which are mostly visual.

**Comment by kjellr** [comment]
> It's been a while since I investigated safari update mechanisms; can anyone get stuck on an old version of Safari? And if yes, can we find any browser stats to look at?

@iamthomasbishop or @mattmiklic: You may know a little about this on the iOS side at least: In general, the PR here is made possible by a Safari fix that is only available in last week's iOS + MacOS releases. Are large portions of the WordPress app's stuck on old iOS versions? Or do they tend to update relatively quickly?

On the Mac side, I'm less clear how we'd be sure. I can do a little digging tomorrow to figure it out.

**Comment by mattmiklic** [comment]
We dropped support for iOS 12 in January once we had over 98% of users on iOS 13 or higher. Generally we find that iOS users update pretty quickly. The same is not necessarily true on Android where we still support versions back to 5.0 (from 2014). Your mileage may vary on the web. 😃

**Comment by jasmussen** [comment]
I found [this handy Safari version history on Wikipedia](https://en.wikipedia.org/wiki/Safari_version_history#Version_compatibility) — though it doesn't appear to include Safari 14.1 yet. Nevertheless it seems to suggest that at least Mojave versions of the operating system and onwards get Safari updates still, which is all to suggest that _if you use Safari on a Mac operating system is more than two years old, you might get sub-optimal multi-button layouts_, and anything later than that we _should_ be pretty good pretty soon.

I'd be happy to land this as a result.

**Review by jasmussen — APPROVED** [review]
Before:

Screenshot 2021-05-11 at 08 49 07

After:

Screenshot 2021-05-11 at 08 46 42

The difference is clear, this change feels worth it. I think we should get it in.

_I think before you land this you might want to rebase, I'm seeing [an issue](https://user-images.githubusercontent.com/1204802/117771171-1e399380-b236-11eb-96a9-c039b44ceae6.png) that is almost certainly unrelated to this, but just shows the age of the branch._

**Comment by kjellr** [comment]
Sounds good, thanks! I just merged in the latest from `trunk`, and I'll merge once the tests pass. 🙌

**Pull request merged**
