### PR TITLE
Fix 'jump' for nested items in list

### LINKED ISSUE #12526: List block: avoid "jump" when nesting a list item
When nesting a list item, there's a visible vertical "jump" of the item (and the whole UI below it). Here's a GIF:

nested list jump

This happens because any `<li>` element in the WordPress admin inherits a `margin-bottom: 6px;` from `common.css`. All that's needed to avoid this unpleasant "jump" is to reset the bottom margin to `0` in the List block `editor.scss`. /Cc @jasmussen

### PR DESCRIPTION
**Pull request by Naerriel**
## Description
Fix 'jumping' of nested items in list: #12526 
Change margin-bottom and line-height in block-list file.

## How has this been tested?
I have ran 'npm run test' and have seen that all tests passed or skipped.

## Screenshots
block-list

## Types of changes
Minor bug fix: #12526

## Checklist:
- [x] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for this PR! 

As I noted in https://github.com/WordPress/gutenberg/issues/12526#issuecomment-443628919, I think the real fix is to make us not have to override this style. But perfect should not be the enemy of good and this might be worth merging as such.

But I'd appreciate a sanity check by @chrisvanpatten, as this touches style scoping, and he seems to be skilled in that area ;)

**Comment by Naerriel** [comment]
If I understand correctly, the same problem with jumping would occur in every Wordpress list but it wouldn't be as visible as in Gutenberg, because you can't nest in an instant a list element.

Do I get it right?
Do you want me to fix this? :smile: 
If yes, do you want me to fix this the same way?

**Comment by jasmussen** [comment]
We do need to fix it, yes, and your fix might be fine. I just want to verify we shouldn't fix it in a different way, so awaiting a response from Chris when he has a minute. (Thanks Chris)

**Comment by chrisvanpatten** [comment]
I think the only potential change to reduce specificity a bit would be something like this:

```scss
.block-library-list .editor-rich-text__tinymce,
.block-library-list .editor-rich-text__tinymce ul,
.block-library-list .editor-rich-text__tinymce ol {
	padding-left: 1.3em;
	margin-left: 1.3em;
}

.block-library-list .editor-rich-text__tinymce li {
	margin-bottom: 0;
	line-height: 2;
}
```

Admittedly I haven't had time to test this so take that with a grain of salt.

Also, is the line-height necessary? @afercia implied in the original ticket that margin-bottom should be enough. Setting line-height seems like it could have other implications…

**Comment by Naerriel** [comment]
It isn't necessary but then the list elements would be much closer together, than before. I can skip it.

**Comment by afercia** [comment]
I'd tend to think the line-height should be inherited from the theme.

**Comment by chrisvanpatten** [comment]
Agreed w/ @afercia that we should let themes set the line height on these elements :)

**Comment by Naerriel** [comment]
Is that now all right, or should I rather modify core wordpress styles?

**Comment by gziolo** [comment]
Can we decide whether this should be fixed in core or here?

**Comment by jasmussen** [comment]
Thank you for your PR! 

I took a stab at fixing this in WordPress upstream, but decided that this wasn't the place to fix it. In wp-admin it's, for better or worse, a design decision. The reason it wasn't an issue in the past is the editing canvas was in an iframe, preventing CSS bleed.

In the future, Shadow DOM will hopefully allow us to accomplish something similar here. In the mean time, that means we need to fix it in Gutenberg. But it also means we need to fix it in a way that has us "embrace" it. For that reason I took a different approach and created #12941. Can you take a look and see if that PR can replace this? Thank you for your work.

**Comment by Naerriel** [comment]
Yes, I think that #12941 can replace mine and I prefer your approach as it doesn't change the initial style.

Thank you!

**Pull request closed without merging**
