### PR TITLE
Fix admin menu scroll on editor page

### LINKED ISSUE #20943: WP Admin sidebar not scrollable at high zoom levels
**Describe the bug**

When zooming in to the point where the wp-admin sidebar is hidden by default, with a hamburger icon at the top left of the page, the sidebar is not scrollable. This only happens in the editor page, in all other wp-admin sections it works fine. I can reproduce it in all major browsers: Chrome and Firefox on both Windows and Mac, IE and Safari.

**To reproduce**
1. With the editor open in a 1300px wide browser window, and _not_ set to full screen mode
2. Zoom in to somewhere between 170% and 200%
3. Verify that the admin sidebar is not scrollable.
4. Open editor sidebar, verify that now the admin sidebar is scrollable
5. Close editor sidebar again, admin sidebar not scrollable once more
6. Zoom in a level or so more, to about 250%
7. Verify that, while admin sidebar now scrolls, layout is very broken, especially on Chrome (see below screenshot)

**Expected behavior**

Expect to be able to fully scroll the admin sidebar at all zoom levels.

**Screenshots**

Admin sidebar not scrollable between 170% and 200%:

Screen Shot 2020-03-17 at 11 19 21 am

Layout broken at 250% on Chrome:

Screen Shot 2020-03-17 at 11 20 13 am

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser: All browsers

### PR DESCRIPTION
**Pull request by tellthemachines**
## Description

Fixes #20943.
At certain zoom levels (between 170 - 200% on a 1300px wide window), the admin sidebar becomes unscrollable on the block editor page (it works fine in the rest of wp-admin). I'm not quite sure what causes this, but it's probably related to the content being scrollable independently from the menu. It is fixed by adding `overflow-y: auto` to `#wpwrap`, which doesn't break anything (the default overflow value is `visible`, which mostly behaves like `auto`). 🤷‍♀️ anyway, it works.

## How has this been tested?

Tested across browsers, on macOS and Windows. 

Make the wp-admin visible in the block editor, then zoom in just until the menu folds up into a hamburger icon. Open the hamburger and verify the menu is scrollable.

## Types of changes

 Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
This fixes it for me! Very unusual issue.

I also noticed that at narrower screen sizes the whole top admin bar scrolls as well. Seems to be caused by this style, which overrides `position: fixed`:
```css
@media screen and (max-width: 600px)
#wpadminbar {
    position: absolute;
}
```

**Comment by jasmussen** [comment]
Thanks for tackling this. It's a good fix, but I think we need to add a responsive wrapper to it.

Specifically, at the <960px breakpoint, that's when the menu collapses and can only be opened with the hamburger button. Anything above that, and the sidebar scrolls without the overflow rule. In these, it's fine, as you can see I've toggled off the rule in the inspector:

Screenshot 2021-02-12 at 10 59 39

Screenshot 2021-02-12 at 11 00 04

At below the 960 breakpoint is where the rule becomes necessary:

Screenshot 2021-02-12 at 11 00 14

You could potentially do something like this:

```
.block-editor-page #wpwrap {
	overflow-y: auto;
	@include break-large() {
		overflow-y: initial;
	}
}
```

It's _probably_ okay that the overflow-y is automatic even at desktop breakpoints. But because this has been a sensitive part of the UI for a while, it might be good to be cautious with the fix.

Nice work!

**Comment by stokesman** [comment]
Zoom is a bit of a distractor here. It can be reproduced at window widths of less than 782px. (Zooming to 170% on a 1300px width window effectively makes a ~765px width window.)

There is fixed positioning on the `html` element (overridden at 782px and up) and if that's disabled the menu can be scrolled:
https://github.com/WordPress/gutenberg/blob/aedca439b94675ae302853ff9f5d957b94c48c97/packages/interface/src/components/interface-skeleton/style.scss#L1-L11

At present, I don't have a better suggestion than the changes proposed here. Just wanted to help clarify the issue.

**Comment by tellthemachines** [comment]
> Zoom is a bit of a distractor here. It can be reproduced at window widths of less than 782px. (Zooming to 170% on a 1300px width window effectively makes a ~765px width window.)

To clarify, this issue only happens between the breakpoint at which the side menu becomes a hamburger(782px) and the one at which the admin top bar stops being fixed (600px). So you can reproduce it at any width between 600px and 782px.

I'll put the rule inside a media query to be on the safe side.

**Pull request merged**
