### PR TITLE
Add tests for BlockAlignmentToolbar.

### PR DESCRIPTION
**Pull request by BE-Webdesign**
## Description
Add tests for BlockAlignmentToolbar.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
👍  

Same minor comment https://github.com/WordPress/gutenberg/pull/3858#discussion_r155738644

**Comment by gziolo** [comment]
Let me copy from another PR:

> Yes, totally on board with what @youknowriad suggested. It will be much easier to follow smaller tests that are laser focused. Given that you had to add inline comments, it looks like all parts of the code that are divided that way could be put in their own `test` block with comment used as a description.

**Comment by BE-Webdesign** [comment]
Updated.

**Review by gziolo — APPROVED** [review]
I added a few small adjustments. It's ready to merge.

**Pull request merged**
