### PR TITLE
Marks the selectors and actions of the commands store as a public API

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

There has been a clear interest from folks to have a direct access to the "store" API (selectors and actions) of the commands center to enable:

 - API access without React (no hooks)
 - Access to unregistration APIs (removing commands registered by Core for instance)

This Pr makes the "commandsStore" a public API like any other store but marks some specific actions of the store (setContext) as private. That one is something we don't want to open yet to third-parties.

## Testing Instructions

1- Open the site editor
2- Check that the command center still works
3- Check that you can call selectors from the console `wp.data.select( wp.commands.store ).getCommands()`

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!

**Comment by TimothyBJacobs** [comment]
> That one is something we don't want to open yet to third-parties.

Is there a tracking issue for this @youknowriad or another place to see more details about why it isn't available? My understanding is that is what would block plugin from using it on our own admin pages?

**Comment by youknowriad** [comment]
> Is there a tracking issue for this @youknowriad or another place to see more details about why it isn't available? My understanding is that is what would block plugin from using it on our own admin pages?

I don't understand the question. 

--

To detail more here, the API to create "custom contexts" is not something I'm confident making public yet. But also I don't think it's the most important API for third-party developers, plugins can add commands and command loaders to the command center. They can also add "contextual" commands (commands that show up automatically when you open the command center) to the contexts core defines. What they can't do is define their own contexts.

**Comment by TimothyBJacobs** [comment]
> I don't understand the question.

I'm wondering what the path is to the API being public? Is it something we plan to have in place by 6.3 release?

---

> They can also add "contextual" commands (commands that show up automatically when you open the command center) to the contexts core defines. 

Right. My use case is one of the plugins I work on has it's own React powered admin pages. We'd love to add a command center implementation to our own plugin page that would let users quickly take actions in our plugin. These actions aren't at all related to the Site Editor or Block Editor though.

My understanding, is we'd need to define our own context to do that properly, but I may be misunderstanding the API.

**Comment by youknowriad** [comment]
@TimothyBJacobs you should be able to use the command center in your own pages but without the "contextual commands" feature. So basically you'd search for all commands. I think at some point we'd probably open the custom context API too but right now, it's not something I'm confident about for forwards compatibility. So most likely something we could for 6.4, once have more feedback and experience with the command center.

**Comment by TimothyBJacobs** [comment]
Aha! I understand, thanks @youknowriad! That seems reasonable to me. Thanks for clarifying!

**Pull request merged**
