### PR TITLE
Dismissible-notices: fix text overlapping icon (X)

### PR DESCRIPTION
**Pull request by Naerriel**
## Description
Fix of issue #11156 - added a margin on the right of dismissible notices.

## How has this been tested?
I looked on the styles manually on left-to-right and right-to-left views.

## Screenshots 
dismissible-notice

## Types of changes
Change in styles.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
Thank you for your changes @Naerriel, things worked great on my tests and it improves the behavior in some resolutions and when resizing.
Before:
jan-21-2019 10-39-48

After:
jan-21-2019 10-38-42

**Comment by jorgefilipecosta** [comment]
Pinging to @jasmussen to have a last look regarding the design/CSS change.

**Comment by jasmussen** [comment]
Love it. Can we change the 25px to `#{ $icon-button-size-small + $border-width }`? That comes to the same, but uses variables.

**Comment by gziolo** [comment]
@Naerriel would you mind applying the change @jasmussen shared so we could merge your first contribution? :)

**Comment by Naerriel** [comment]
@jasmussen @gziolo Thank you for feedback and reminding me. :)

**Review by gziolo — APPROVED** [review]
All good, nice work 👍 

Congrats on your first contribution landing to Gutenberg 🎉

**Pull request merged**
