### PR TITLE
Fix: Clicking On Backspace Makes Reusable Block Modal Disappear

### LINKED ISSUE #36513: Selected blocks get deleted when creating a reusable block and pressing backspace key
### Description

When creating a reusable block via selecting multiple blocks, pressing the backspace key when typing a name in the "Create Reusable block" dialog leads to deleting the selected blocks and therefore the dialog to disappear. This behavior makes it very difficult to create a reusable block as removing characters when setting a name is very common.

### Step-by-step reproduction instructions

1. Add multiple blocks to a post.
2. Select multiple blocks.
3. Click on the options button located in the toolbar (the three dots icon).
4. Click on "Add to Reusable blocks" option.
5. Select the Name input field.
6. Type a name and press the backspace key.
7. Observe that the selected blocks are deleted and the "Create Reusable block" dialog is closed.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/14905380/141965638-b75f064e-35fb-4e94-951d-43958b0f0e0e.mp4

### Environment info

- Gutenberg: v11.8.3
- Editing Toolkit: 3.19495
- WP AMP: 2.0.5
- CoBlocks: 2.10.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by delowardev**
## Description

When creating a reusable block, if someone tries to delete a character from the block name by clicking backspace it removes all the selected blocks instead of deleting the character.

See: #36513

## How has this been tested?

WP Version: 5.8.2
Device: Macbook Pro M1
OS: macOS Monterey

Please check the attached video on how to replicate and test.

## Screenshots 

[!Video](https://user-images.githubusercontent.com/14905380/141965638-b75f064e-35fb-4e94-951d-43958b0f0e0e.mp4)

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hi, @delowardev

@costdev [mentioned](https://github.com/WordPress/gutenberg/issues/37539#issuecomment-998798313) that we'll need to check the `DELETE` keycode as well.

**Comment by delowardev** [comment]
> Hi, @delowardev
> 
> @costdev [mentioned](https://github.com/WordPress/gutenberg/issues/37539#issuecomment-998798313) that we'll need to check the `DELETE` keycode as well.

DELETE key check added in https://github.com/WordPress/gutenberg/pull/36663/commits/83582bf8581644b645934f80b77b36d2365d37ce

**Comment by Mamaduka** [comment]
Thank you, @delowardev.

**Comment by ntsekouras** [comment]
Thanks for the PR @delowardev !

This feels like there is a deeper underlying issue and we should try to dig deeper first.

**Comment by delowardev** [comment]
@ntsekouras 
My point was it shouldn't fire delete events when the user is writing something ( when the input field is in focus ). But you're right, actually; another solution could be preventing the delete operation when the modal is open.

**Comment by ntsekouras** [comment]
Thanks for your work here @delowardev! I'll close this as an alternative approach was merged for this here: https://github.com/WordPress/gutenberg/pull/37595

**Pull request closed without merging**
