### PR TITLE
Add tests for fluid layout + typography

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Adds unit tests for the fix in #53551.

### CODE REVIEW

**Review by andrewserong — APPROVED** [review]
Thanks for the quick follow-up! Adding the extra test theme looks like a good and straightforward way to handle this and keeps things simple 👍

LGTM! ✨

**Comment by ramonjd** [comment]
Thanks for taking care of this 🙇🏻

**Comment by ramonjd** [comment]
Similar to https://github.com/WordPress/gutenberg/pull/53551#issuecomment-1676471757 I can integrate into the current [backport core patch](https://github.com/WordPress/wordpress-develop/pull/4989) since it's related.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/bugfixes-6-3-1 branch to get it included in the next release: 9b939ffbde

**Pull request merged**
