### PR TITLE
Always show the block appender when its parent is selected

### LINKED ISSUE #5055: Inserter UI disappears when i type, and it's not obvious how to get them back
## Issue Overview

If you have no empty paragraph blocks, and you click out of editing the document so that is there no currently active block (e.g. click between the blocks and the right hand column of menus), the inserter and frequently used blocks are gone.

## Expected Behavior

If nothing is selected and you have no empty paragraph blocks, the inserter / frequently used blocks UI should still be visible, at the bottom of the document.

### LINKED ISSUE #5803: Clicking below bottom text block does not defocus it, which can be confusing
If the bottom text block is focused, its UI could be blocking the block above it. Clicking in the vast space below the bottom block does not defocus it. Instead, you have to click somewhere in the "gutter".

kapture 2018-03-26 at 13 32 28

My expectation would be that clicking in a vast empty expanse would deselect a block. I found myself struggling to deselect the block and reveal the hidden block above it. <kbd>Esc</kbd> does not work. Clicking in the vast expanse below only works if you click in the GUTTER. Clicking above sometimes inserts a block, if you aren't careful with your click.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5055
closes #5803 

Builds on top of #36605 

This PR simplifies the behavior the default block appender:

  - When a container block is selected, its appender is shown
  - When no block is selected, the appender of the root level is shown.

This basically removes the special case we had in place about the last paragraph in a block list being a paragraph.

Let me know what you think @jasmussen

### CODE REVIEW

**Comment by jasmussen** [comment]
Just for consistency, I agree: either we always show, or we never show. But I'd like very much for this one to be paired with 36605 so we don't have plusses everywhere. Thanks Riad!

**Comment by youknowriad** [comment]
I agree that this one doesn't work well without #36605

**Comment by ZebulanStanphill** [comment]
Glad this is finally being addressed. I tried doing something similar in #28529 but ran into some end-to-end test failures. I think this PR will finally resolve #5055.

I'm noticing some odd behavior when clicking on the bottom of the editor canvas. To see what I mean, go into a mostly empty post, add a Paragraph, add an Image (just leave it as a placeholder), then click below the Image. The cursor jumps to the Paragraph for some reason. This is not how it behaves in `trunk`.

**Comment by youknowriad** [comment]
@ZebulanStanphill That's probably a bug that's already in trunk but hidden. In trunk, there's an appender that is always visible after the last image block while in this PR, there's nothing, so the click is forwarded to the first block maybe? What would be your expectation here?

**Comment by ZebulanStanphill** [comment]
@youknowriad I would expect the last block to be selected. The current behavior in `trunk` (appender aside) was modeled after editors like Microsoft Word where clicking the bottom of the page puts the cursor at the end of the text.

**Comment by jasmussen** [comment]
>  The current behavior in trunk (appender aside) was modeled after editors like Microsoft Word where clicking the bottom of the page puts the cursor at the end of the text.

Definitely. However I'm starting to think of that as a mostly failed experiment mostly resulting in empty trailing paragraphs, and difficulty in deselecting blocks that's increasing a bit with the site editor. I'm tempted to think it's worth revisiting/reverting that code, essentialy addressing #5803.

**Comment by ZebulanStanphill** [comment]
@jasmussen I agree. Now that the root appender only shows when no blocks are selected, I found it confusing that clicking the empty bottom of the canvas didn't take my selection off the blocks, yet clicking the empty left/right regions did.

**Comment by youknowriad** [comment]
@ZebulanStanphill @jasmussen this makes sense, I tried it in the last commit and it feels good for me. WDYT

**Comment by jasmussen** [comment]
I see this:
this

The fact that I can deselect without creating an empty paragraph feels right. It also works well for groups:
group

There's one single place in the entire codebase where I feel like the old behavior was better, and that's the navigation block for creating submenus. The details are in [this PR which sort of restores the behavior](https://github.com/WordPress/gutenberg/pull/36720), though that would break with this PR. I don't mean that to be a blocker: I think there are other paths we can take. But I do wonder: should there be some way the block itself could opt in to the "show appender even when a child is selected" behavior? It would make sense for submenus.

**Comment by youknowriad** [comment]
> should there be some way the block itself could opt in to the "show appender even when a child is selected" behavior?

It should already possible to do this somehow with the `renderAppender` prop of inner blocks I think but it might require some custom code in the block and not just a flag or something.

**Comment by jasmussen** [comment]
Sounds good!

**Comment by youknowriad** [comment]
This one should be ready, I had to change some keyboard related things too (highlighted by the previous e2e test failures)

 - Focusing the appender doesn't create paragraphs automatically, you need to hit "Enter" after that to do so. I think this behavior is clearer over trunk but wanted to highlight it.
 - Hitting arrow when on the last block, used to move the focus to the appender which created a paragraph at the end. This is also not the case anymore, we stay stuck there. I also think it's better but it may make appending blocks at the end using keyboard only harder.

**Comment by jasmussen** [comment]
Here's the post editor:
post editor

Here's the site editor:
site editor

I also love the amount of red code in this PR. I really appreciate that we are moving forward with some unification and cleanup of the appender code, and I think this feels like a good step on the way.

One thing this PR does is to canonize and solidify the notion that _you have to select the right container for the appender for that container to be shown_. I think this is correct for us to do, the previous behavior was so unclear in very many cases. That being said, I do think that there will be some exceptions to this rule (as noted, #36720) — but I'm happy to treat those as exactly that: exceptions, and requiring a little block-specific code to tune the behavior there. Still, let's keep an eye on this change across blocks, and see what, if anything, we might need to follow up on. Moreso than the fixed-position change, I think that change can trip up some exotic flows.

If you have high confidence in the code, I'm happy to give this one a green check on behavior alone: the code looks good to my eyes. Otherwise it seems like this one mostly just needs a code sanity check.

**Comment by jasmussen** [comment]
Oh one thing I noticed, and it's probably related to what you mentioned here:

> Focusing the appender doesn't create paragraphs automatically, you need to hit "Enter" after that to do so. I think this behavior is clearer over trunk but wanted to highlight it.

While I think that could potentially work for the appender when it sits at the bottom of a post, it tripped me up in the initial state here:

default appender

Is it crucial for this PR to make this change at the same time?

**Comment by youknowriad** [comment]
> Is it crucial for this PR to make this change at the same time?

It's the same component, so when I change one, it changes the other, that said, we can try to introduce a special case if needed. Maybe check the content of the block editor and if it's empty create a paragraph.

The reasoning for me here is that if I put myself in a screen reader mode, I feel like navigating the UI (hitting tab/shift tab) shouldn't actually do any action. That said I'd be fine with this small exception if needed.

**Comment by jasmussen** [comment]
It's only the initial state where we see "Add title" and "Type / to insert a block" where it feels like it affects the writing flow.

**Comment by youknowriad** [comment]
I added the special case.

**Comment by jasmussen** [comment]
Works perfect 👌

**Comment by youknowriad** [comment]
Can I get a ✅

**Review by jasmussen — APPROVED** [review]
This works well for me, and is an important followup to recent abs-position improvements.

**Review by ellatrix — APPROVED** [review]
Good riddance. :) It's nice to be consistent and remove the canvas click redirect.

**Comment by youknowriad** [comment]
I'm hesitant about the "backport" label here. What do you think?

**Comment by jasmussen** [comment]
> I'm hesitant about the "backport" label here. What do you think?

I guess this change is mostly invisible on top of the already merged fixed appender change. In that light, whether it lands or not is less important?

**Pull request merged**
