### PR TITLE
[RNMobile] Fix `react-native-prompt-android` package integration

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3548
[Only for testing] `WPAndroid` PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14713

## Description

This PR updates the `react-native-prompt-android` package so it include the Jitpack setup for Android, which fixes a crash that is produced upon opening the editor.

## How has this been tested?

**It's required to test the changes with an installable build, [here](https://github.com/wordpress-mobile/WordPress-Android/pull/14713#issuecomment-847785798) you can find one that was generated for testing.**

1. Open a post/page
2. Observe that the app doesn't crash

## Screenshots 

N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
I tested these changes with the linked WP Android PR, and I verified that the editor opened successfully and the issue was resolved. Once this PR has been updated with the commit hash from `trunk` of https://github.com/wordpress-mobile/react-native-prompt-android we are good to go. LGTM 🚢

**Comment by fluiddot** [comment]
> I tested these changes with the linked WP Android PR, and I verified that the editor opened successfully and the issue was resolved. Once this PR has been updated with the commit hash from `trunk` of https://github.com/wordpress-mobile/react-native-prompt-android we are good to go. LGTM 🚢

Ok, I've just updated the package reference to point `master` [commit `6c5122664d25b7f1cdeefc119e69329493a077a8`](https://github.com/wordpress-mobile/react-native-prompt-android/commit/6c5122664d25b7f1cdeefc119e69329493a077a8), once the PR checks pass, I'll merge it 👍 .

**Comment by fluiddot** [comment]
There's a good number of PR checks that are failing but I don't think it's related to these changes. In fact, I noticed that the recent commits merged into `trunk` have the same checks failing so probably it's safe to merge it. @hypest I don't have permission to merge it so what do you think about skipping those checks?

**Common checks that are failing:**
- End-to-End Tests / Admin (1,2,3,4)`
- Unit Tests / PHP 

**EDIT:** Looks like the check "Performances Tests / Run performance tests " is failing, I'll try to restart it just in case it's caused by flakiness.

**Comment by jd-alexander** [comment]
> There's a good number of PR checks that are failing but I don't think it's related to these changes. In fact, I noticed that the recent commits merged into trunk have the same checks failing so probably it's safe to merge it. @hypest I don't have permission to merge it so what do you think about skipping those checks?

👋🏾 Just chiming in here, are we able to check with the folks who are responsible for these tests to see if they can disable them or resolve them? If not can we ping someone involved so that they can also sign off on the skipping of these tests? Let me know what you think about this as well @hypest

**Comment by jd-alexander** [comment]
@fluiddot I took the liberty of merging `trunk` into this branch since there have been some e2e fixes that landed a couple of hours ago 🙏🏾

**Comment by fluiddot** [comment]
> @fluiddot I took the liberty of merging `trunk` into this branch since there have been some e2e fixes that landed a couple of hours ago 🙏🏾

Thank you very much @jd-alexander for updating it ❤️ ! Looks like the checks that were failing now are 🟢, however, new ones (`Compressed Size / Check` and `Static Analysis (Linting, License, Type checks...)`) have failed. I'm going to restart them and if they pass I'll merge the PR.

**Comment by hypest** [comment]
> Looks like the checks that were failing now are 🟢

Happy to see that! I'd otherwise prefer to hold off a bit until trunk would get green again.

**Comment by fluiddot** [comment]
> > Looks like the checks that were failing now are 🟢
> 
> Happy to see that! I'd otherwise prefer to hold off a bit until trunk would get green again.

All 🟢  so I'm merging the PR 🎊 .

**Comment by youknowriad** [comment]
This commit in trunk seem to have a introduced a number of failure. Do we know whether these are related? Can we check?

**Comment by fluiddot** [comment]
> This commit in trunk seem to have a introduced a number of failure. Do we know whether these are related? Can we check?

This PR only introduced a bump for a dependency of the `react-native-editor` package, not sure why it's making so many PR checks to fail 🤔 . As far as I checked, it's failing when running `npm ci`, the error is:
`ERR! cb() never called!`, I'll investigate further.

**Comment by fluiddot** [comment]
I'd like to note that all checks passed on the PR before merging 🤔 .

**Comment by youknowriad** [comment]
Yes, it happens sometimes, maybe because some things landed in trunk in the mean time that could have impacted this PR. It could also be a temporary npm breakage or something like that.

**Comment by youknowriad** [comment]
They might be intermittent failures since I don't see them failing on this recent PR https://github.com/WordPress/gutenberg/pull/32228

**Comment by fluiddot** [comment]
> Yes, it happens sometimes, maybe because some things landed in trunk in the mean time that could have impacted this PR. It could also be a temporary npm breakage or something like that.

Yep, I'm going to restart the jobs that failed just in case it's something temporary, thanks for the help 🙇 !

**Comment by fluiddot** [comment]
Looks like it was a temporary breakage because after restarting them now are they're passing 🤷‍♂️ .

**Comment by youknowriad** [comment]
Thanks and sorry for the false alarm.

**Pull request merged**
