### PR TITLE
Site Icon Focus fix

### LINKED ISSUE #61339: Focus ring doesn't match button Site Hub Icon size
### Description

The site icon in the header of the site editor has a smaller focus ring.

### Step-by-step reproduction instructions

1. Use the keyboard to move focus to the site hub button
2. The focus ring does not match the size of the site hub button

### Screenshots, screen recording, code snippet

Open Navigation tooltip with focus ring about 8px inside of the edge of the site icon

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #66375: No focus style for Open Navigation button
### Description

There are no focus styles for the Open Navigation button on the site editor header.

### Step-by-step reproduction instructions

- Move focus to the "Open Navigation" button in the site editor header
- Open Navigation tooltip will be visible but no focus styles are present

### Screenshots, screen recording, code snippet

Open Navigation tooltip but no focus style

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by karthick-murugan**
## What?
Fixes #61339
Fixes #66375
This PR updates the SCSS file for the site icon to improve focus visibility.

## Why?
The focus ring on the site hub icon was not visible or visually appealing when using keyboard navigation, impacting accessibility.

## How?
The SCSS file gutenberg/packages/edit-site/src/components/site-icon/style.scss has been modified to add a blue border outline around the site icon when it is focused.

## Testing Instructions

1. Open the dashboard and navigate to Appearance > Editor.
2. Click anywhere in the container to close the navigation.
3. Use the keyboard to focus on the site icon in the top left corner.
4. Ensure the blue border outline appears around the site icon when focused using keyboard navigation.

### Testing Instructions for Keyboard
Ensure the blue border outline appears around the site icon when focused using keyboard navigation.

## Screenshots or screencast 

**Screenshot:**
site_icon_focus

**Video:**
https://github.com/user-attachments/assets/4a5609a0-0827-4e43-b64d-c8b27f714aaf

### CODE REVIEW

**Comment by karthick-murugan** [comment]
@jeryj - Closed the previous PR https://github.com/WordPress/gutenberg/pull/65936 and created this new one, since resolving some conflict issue brought in many commits to that PR. We can continue our discussion here.

Regarding your latest message, I tried with the before , after pseudo element but did not get the desired result. Adding a 1px padding was doing the job, but not sure if that will be a accepted fix. Please provide your inputs.

**Comment by jasmussen** [comment]
Nice work, thanks for the PR. 

It's not clear that this fully solves the original issue, though:

Screenshot 2024-11-13 at 10 10 35

The 1px padding also makes the icon itself jump a little bit inwards, which is jarring.

I think what we need to do is create a pseudo element. Someting like this might work:

```
.edit-site-editor__view-mode-toggle button:focus{
	position: relative;

	&::before {
		content:"";
		display: block;
		position: absolute;
		z-index: 1;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
		box-shadow: inset 0 0 0 var(--wp-admin-border-width-focus) var(--wp-admin-theme-color), inset 0 0 0 calc(#{ $border-width } + var(--wp-admin-border-width-focus)) $white;
	}
}
```

Screenshot 2024-11-13 at 10 20 42

**Comment by karthick-murugan** [comment]
[jasmussen](https://github.com/jasmussen) Updated the proposed changes. Can you please review it?

**Review by jasmussen — APPROVED** [review]
WFM!

**Review by Mamaduka — APPROVED** [review]
The changes test well for me as well ✅

**Pull request merged**
