### PR TITLE
Switch performance tests to Playwright: Take 2

### PR DESCRIPTION
**Pull request by WunderBart**
## What?

A second (and hopefully last) attempt to switch the perf specs to Playwright. 🤞 

The [original PR](https://github.com/WordPress/gutenberg/pull/52022) was [reverted](https://github.com/WordPress/gutenberg/pull/53741) because the tests couldn't handle the environment in which the editor canvas is not iframed (legacy). I've implemented that partially in https://github.com/WordPress/gutenberg/pull/53744, and the rest should be in this PR. 

_edit:_

Tested via a custom workflow, running against the base commit (legacy editor) now passes: https://github.com/WordPress/gutenberg/actions/runs/5893776939/job/15986051163

## Testing Instructions
See https://github.com/WordPress/gutenberg/pull/52022

### CODE REVIEW

**Comment by WunderBart** [comment]
Running a perf job against the base branch to ensure the legacy canvas is now handled as expected: https://github.com/WordPress/gutenberg/actions/runs/5892879390/job/15985139816

/cc @swissspidy

**Comment by WunderBart** [comment]
@kevin940726 @youknowriad, any chance you could take a look? I'm AFK next week, so it would be great to land it today!

**Review by swissspidy — APPROVED** [review]

**Comment by WunderBart** [comment]
@Mamaduka @kevin940726 not sure what to do with [that flaky E2E](https://github.com/WordPress/gutenberg/actions/runs/5893478235/job/16005468331?pr=53768) - I've re-run the job several times already, but it keeps failing and blocking this PR. I can also see it failing on `trunk`, so it's unrelated to my changes. Will try to rebase now.

**Comment by Mamaduka** [comment]
@WunderBart, I tried but failed to debug that one as well :(

I wonder if it's related to change #53744 or its combination with other PRs. I started noticing this failure more often after it got merged.

**Comment by WunderBart** [comment]
> @WunderBart, I tried but failed to debug that one as well :(
> 
> I wonder if it's related to change #53744 or its combination with other PRs. I started noticing this failure more often after it got merged.

I think it actually started to be flakier after the PR right above mine: https://github.com/WordPress/gutenberg/pull/53736. I don't think the changes from #53744 could have caused it. I've only slightly changed how we check for the legacy canvas presence. I will double check though and see if I can fix that spec. I'd really love to land this one today! 🙌 

/cc @jsnajdr, do you think anything from #53736 could make [that spec](https://github.com/WordPress/gutenberg/actions/runs/5893478235/job/16005468331?pr=53768) flakier?

**Comment by WunderBart** [comment]
@Mamaduka, as they say, the seventh time's a charm, amirite? 😅 All E2Es now passed, but the JS unit ones didn't. Hope to get a pass after a (single) rerun! 🤞

**Comment by youknowriad** [comment]
This switch made the "first block load" metric very unstable. Also it increased the numbers for "typing" and "select block" metrics.

**Comment by WunderBart** [comment]
> This switch made the "first block load" metric very unstable. Also it increased the numbers for "typing" and "select block" metrics.

FBL does look particularly unstable. I'd try waiting for the block to be attached to DOM instead of becoming visible for starters. Playwright waits for the element to be [visible by default](https://playwright.dev/docs/api/class-locator#locator-wait-for:~:text=Defaults%20to%20%27visible%27), which is opposite to [what Puppeteer does](https://pptr.dev/api/puppeteer.waitforselectoroptions#:~:text=visible,false). The massive post content that we're testing against halts the UI for a bit, which could be making the visibility callback timing so random.

I'm going to see if that helps and make a PR.

Regarding the Typing and Block Select metrics, it looks like they went back down (and stabilized?) after the [recent base branch update](https://github.com/WordPress/gutenberg/commit/f39b0d827669efe63f993d1c4e4379c21c530d11).

| Type | Block Select |
| ------------- | ------------- |
| Screenshot 2023-09-04 at 14 44 22 | Screenshot 2023-09-04 at 14 44 05 |

**Comment by WunderBart** [comment]
I've downloaded raw metrics for a few recent jobs and noticed huge spikes there (10-13 seconds), usually happening for 1-3 samples and then returning to stable-ish ~2.5 seconds. Interestingly, it seems to be happening for the latest ref only, not the base one, which is why we see such big spikes, as the normalization factor gets heavily distorted. Unfortunately, so far, I haven't been able to reproduce this behavior locally + I'm getting much lower values (stable ~1.1s). Any idea what might be causing those delays? cc @dmsnell.

Anyway, one immediate solution for this would be calculating the median, not the average, as it would filter out those outliers.

Here are the aforementioned raw metrics:

| Sample | Job 1      | Job 2      | Job 3 | Job 4      | Job 5      |
|--------|------------|------------|-------|------------|------------|
| 1      | 12891 ⚠️  | 2900       | 2630  | 2487       | 3061       |
| 2      | 13240 ⚠️  | 2906       | 2429  | 2443       | 2330       |
| 3      | 13028 ⚠️  | 2889       | 2408  | 2482       | 10369 ⚠️   |
| 4      | 2853       | 3010       | 2574  | 2666       | 9738 ⚠️    |
| 5      | 2788       | 14855 ⚠️  | 2568  | 2508       | 2334       |
| 6      | 2882       | 3050       | 2364  | 2448       | 2333       |
| 7      | 2986       | 2918       | 2418  | 2387       | 2268       |
| 8      | 3003       | 2857       | 2478  | 3070       | 2236       |
| 9      | 2890       | 2945       | 2570  | 2533       | 2269       |
| 10     | 2839       | 2893       | 2536  | 11380 ⚠️  | 2175       |


---

Another thing I've noticed is that the codevitals value seems to be 10x'd for some reason. The first block definitely does not take 29 seconds to load. 🤔 Is this intended, @youknowriad?

Screenshot 2023-09-04 at 15 55 28

**Comment by youknowriad** [comment]
> The first block definitely does not take 29 seconds to load. 🤔 Is this value intended, @youknowriad?

I'm definitely not 10xing on purpose but maybe it's the normalization. In other words, the first time we computed the values, the environment might have been slower than the environment we use today (like the CI runner for instance)

**Comment by WunderBart** [comment]
@youknowriad `average` -> `median` switch in https://github.com/WordPress/gutenberg/pull/54157

**Pull request merged**
