### PR TITLE
Consolidate edit media icons in toolbar

### PR DESCRIPTION
**Pull request by fabiankaegy**
## Description
Addressed the issue described in #17219 I have added the "new" modify media icon to the Video, Media-Text & Cover block, to make it consistent with the icon used in the image block.

The thing that feels wrong, is that I've added the icon inside each of the block folders, rather that just having it once. If there is a place where these shared resources should go that would make it way cleaner. 

## How has this been tested?
The included test suite has passed with the changes and the blocks delivered the expected experience in manual testing.

## Types of changes
I've changed the edit media icon in the Toolbar of three blocks to make it consistent throughout all blocks.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by talldan** [comment]
Thanks for working on this @fabiankaegy. There's been some other work underway to change the user flows for media blocks.

https://github.com/WordPress/gutenberg/pull/16200 is exploring this for the audio block.

Consistency is always good though. I've added `Needs Design Feedback` so that the design team can check they're happy with this change.

**Comment by fabiankaegy** [comment]
Okay awesome, to make it easier to see what Icons I'm talking about, here are two screenshots of the icons in use:

## `Image Block`:
Bildschirmfoto 2019-08-28 um 13 00 27

## `Cover Block`:
Bildschirmfoto 2019-08-28 um 13 00 08

**Comment by shaunandrews** [comment]
Over in #11952 it looks like we’re planning on replacing the cryptic icon with a label. I’d expect us to do the same for all media related blocks like the ones you show above.

**Comment by fabiankaegy** [comment]
@shaunandrews Yes and that might be the clearest solution. All I thought is, that the inconsistency is not great. 

Also if the icon is going to be used it maybe should be included here so it can be referenced everywhere without being repeated:
[Dashicons Gutenberg Icons](https://github.com/WordPress/dashicons/tree/master/sources/svg/gutenberg)

**Comment by paaljoachim** [comment]
I have noticed that the embed Video block, Cover block, Media & Text still uses a pencil and should instead use the same icon as is used in the Image block.

Is the first step to consolidate the edit image/media icons before the first version of this PR is merged https://github.com/WordPress/gutenberg/issues/11952 ? 

@kjellr @mapk @karmatosed @mtias @draganescu @senadir

**Comment by mapk** [comment]
@fabiankaegy, thanks for taking the time on this contribution. However, I think we're super close to finalizing the "Replace" media system in #16200. I'd rather extend our efforts there right now. Once this is integrated, we'll need to update all the appropriate blocks and test them extensively. 

Can we close this for now? It might be a good idea to line up an issue that identifies all the blocks that will need to be updated once #16200 is complete.

**Pull request closed without merging**
