### PR TITLE
FSE Navigation sidebar: Show single post template in posts templates

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
Show `single-post` template in the posts menu.

## How has this been tested?
1. Open Site Editor
2. Open Navigation sidebar
3. Click Templates
4. Click + button to add a new template, choose Post
5. Navigate to Posts submenu
6. Make sure Post is displayed

## Screenshots 
image

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jameskoster — CHANGES_REQUESTED** [review]
It works! Two observations:

1. The template is empty – should it be?
2. Can we add the Post template to the top level of template navigation, rather than inside the "Posts" section?

**Comment by david-szabo97** [comment]
> It works! Two observations:
> 
> 1. The template is empty – should it be?
> 2. Can we add the Post template to the top level of template navigation, rather than inside the "Posts" section?

1. I don't think we have a default file template for it in our block themes.
2. The reason I put `single-post` into `Posts` is that the `page` template is in the `Pages` submenu. Since we already have `home` and `single` templates inside the `Posts` submenu, it would make sense to have the `Post` in there as well. Let me know what you think.

**Comment by jameskoster** [comment]
> I don't think we have a default file template for it in our block themes.

If we have a default for `single` or `singular` we could just copy that for now?

> Let me know what you think.

I can't find the issue now but we discussed also moving the `page` template out of the "Pages" section and up to the top level. 

The reasoning behind for this suggestion is that the `page` and `post` templates often govern the vast majority of content on a site, and are therefore likely to be edited more frequently. The "Posts" and "Pages" sections will house templates that are specific to _individual_ posts / pages (`post-$id` etc), and therefore much less likely to be edited with the same frequency, hence the lower prominence in the iA.

We don't have to do it in this PR though :) 

FWIW `single` should certainly not be in the "Posts" section, since that template can also resolve for pages.

**Review by Addison-Stavlo — APPROVED** [review]
Tested and this works as advertised.  This looks consistent to me 👍  - I think its more up to you whether we want to re-arrange what shows up where here or in a follow up.

> FWIW single should certainly not be in the "Posts" section, since that template can also resolve for pages.

The description for `single` says: "Used when a single entry that is not a page is queried" - so it doesn't seem to be intended for pages.  Maybe we are confusing it with the general template "singular"?

**Comment by jameskoster** [comment]
> Maybe we are confusing it with the general template "singular"?

You're correct. `single` is only for `post`s, and `singular` is post type agnostic. It's 2021 and I still get confused by the `single` and `singular` templates 🤦‍♂️

**Comment by Addison-Stavlo** [comment]
>  It's 2021 and I still get confused by the single and singular templates 🤦‍♂️

You are not alone. 🤣   I didn't remember the difference either until i went looking for it and saw the description.

**Comment by jameskoster** [comment]
For the record, this is why I would advocate not offering these templates as options in the (+) menu at all. They're difficult to understand, and probably best left for themers to use at their discretion.

"Page" (`page`) and "Post" (`single-post`) are just far easier to understand, and cover the same use cases in the vast majority of situations anyway.

`</rant>`

**Comment by Addison-Stavlo** [comment]
> For the record, this is why I would advocate not offering these templates as options in the (+) menu at all.  They're difficult to understand, and probably best left for themers to use at their discretion.

They do at least have the accurate description there though.  It does enable a good flow for those themers.

I would suspect most non themers would rather get a theme that supplies these templates than create them themselves or wouldn't need to use this "+" flow option.  But even in the case they do the descriptions should definitely help guide them.

**Comment by vindl** [comment]
> I don't think we have a default file template for it in our block themes.

I think the existing setup should handle this situation and fall back to the more generic template that handles the rendering of `single-post` on the front end. In that sense it should be enough for block themes to provide `index` template and it should be inherited here. But if that's not working in all cases it's a separate issue that can be handled outside of this PR.

**Review by vindl — APPROVED** [review]

**Review by jameskoster — APPROVED** [review]

**Comment by Copons** [comment]
So, it seems there is an unrelated issue on template creation: the template is created correctly, with the correct fallback content (retrieved with [this function](https://github.com/WordPress/gutenberg/blob/master/packages/edit-site/src/utils/get-closest-available-template.js) — we might want to add a `single-post` case, along with `attachment`, returning `single`).
The new template is in state, with the correct ID, it's even saved in the DB (check `wp-admin/edit.php?post_type=wp_template`), but its content never reaches the editor canvas.
Reloading the Site Editor will make it show up just fine.

I'm looking into it. 👍

**Pull request merged**
