### PR TITLE
Post Author Block: add duotone suport 

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

This PR adds duotone support to the post author block

## How has this been tested?

Using emptytheme

## Screenshots 

Editor

Screenshot 2021-08-31 at 10 54 22

Frontend

Screenshot 2021-08-31 at 10 54 28

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
This is what I see:

hey

And the filter as the code suggests applies only to the avatar image, and not the text or anything else:

Screenshot 2021-08-31 at 11 39 02

Seems good to me!

_Separately it looks like there's a lot of low hanging fruit we could pick with the post author block, but that's definitely separate.

**Comment by carolinan** [comment]
I'd like to see a decision about the direction of the post author block before more features are added, to not make it more complicated _if the block is split._
https://github.com/WordPress/gutenberg/issues/24952

**Comment by ajlende** [comment]
> I'd like to see a decision about the direction of the post author block before more features are added, to not make it more complicated _if the block is split._ #24952

@carolinan Do you think #24952 will be resolved soon? Since this only adds a single line to the block.json, it doesn't seem to me like there's very much complexity added, and people who are already using the post author block could benefit from this feature now.

**Review by ajlende — APPROVED** [review]
Forgot to press the Approve button yesterday :sweat_smile: But the change works well for me!

With the featured image and now this, on some pages, there are starting to be a lot of generated SVGs. It's something that I'll look into, and maybe it can be included with the theme.json work in #34073.

**Comment by carolinan** [comment]
> @carolinan Do you think #24952 will be resolved soon?

Only if people engage in the conversations so that it can be resolved. Basically someone needs to make a decision.

**Review by carolinan — APPROVED** [review]

**Pull request merged**
