### PR TITLE
Adds "Template Parts" command to site editor

### LINKED ISSUE #60443: Command Palette: Add 'Template Parts' command
## What problem does this address?
When I'm working on templates in the site editor, I'll often have the need to also quickly jump to the Template Parts section to work on common parts like the header or footer. 

The Command Palette is generally my tool of choice when navigating the many avenues of the site editor, but sadly, 'template parts' is not a command that the palette is aware of. 

While I'm pleased with the efficiencies CP brings during 90% of my daily driving, breaking out the mouse to customize my template parts is draining.

## What is your proposed solution?
It's time to include Template Parts in the command palette.
GKRI9K1XsAE6xiZ

### PR DESCRIPTION
**Pull request by bacoords**
## What?

Adds command to directly access your Template Parts while in the site editor.

## Why?

This was actually a command that existed but was removed in #52817 as the Patterns and Template Parts UI were somewhat merged. However, since Template Parts are still a distinct entity and not always discoverable as something you'd find under "Patterns", this PR adds the direct link via command palette.

Closes #60443

## How?

New command was added mostly matching the original but deep linking directly to template parts instead linking to Patterns and requiring an additional click to see.

## Testing Instructions

1. Open the site editor.
2. Click `cmd-k` to trigger the Command Palette
3. Start searching for Template Parts
4. Select Template Parts and confirm you're navigated to the correct screen

## Screenshots or screencast 
Screenshot 2024-05-01 at 7 25 52 AM

## Needs feedback on:

- Currently the command loads in the site editor but not the page editor because only admins can edit the template parts. To load in the page editor, it needs to be checking user permissions _before registering the command_, but I wasn't seeing a clear way to do that.

### CODE REVIEW

**Comment by bacoords** [comment]
@annezazu @colorful-tones Do you know who I would @ to get labels and feedback on this PR? (Commands / Core Commands)

**Comment by colorful-tones** [comment]
> @annezazu @colorful-tones Do you know who I would @ to get labels and feedback on this PR? (Commands / Core Commands)

I've assigned a few folks for PR review that I feel like could help move this forward. I think this would be a nice addition for WP 6.6 and would be happy to triage it onto the board, but I don't want contributors to feel like I'm adding more work. For now, I'll leave it off.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

This PR makes sense to me, but I'd like to pass on a few points to move forward.

- I think this command should be added to `site-editor-navigation-commands.js` instead of `admin-navigation-commands`. Then you may be wondering why the "Patterns" command exists in `admin-navigation-commands`, but I think the Patterns command should also be moved to `site-editor-navigation-commands.js`. Please refer to the explanation of [#54133](https://github.com/WordPress/gutenberg/pull/54133) for the reason why it currently exists in `admin-navigation-commands`.
- This command should only be enabled if the template part actually exists. You will probably need to get the template parts via the `getEntityRecords` selector and check their number.
- You could reuse the [useIsTemplatesAccessible()](https://github.com/WordPress/gutenberg/blob/3d8b192c3df3b02f4c1efc9d8154b715dc189600/packages/core-commands/src/site-editor-navigation-commands.js#L260) hook to check if the site editor is accessible.
- Finally, I think [here](https://github.com/WordPress/gutenberg/blob/3d8b192c3df3b02f4c1efc9d8154b715dc189600/packages/core-commands/src/site-editor-navigation-commands.js#L340) is where this command should be added. The Patterns command mentioned above should also be moved here via a separate PR.

If there is anything you do not understand in these explanations, please feel free to ask 👍

**Comment by bacoords** [comment]
Thanks for the help on this!

> I think this command should be added to site-editor-navigation-commands.js instead of admin-navigation-commands. 

I originally wrote it this way, but then the command is displayed in the initial blank state when you open the command palette in the site editor. I'm wondering if that's the ideal behavior and if we want that? (I'm not personally against it, but I assume since it's not in the main navigation on the left-hand sidebar, maybe it's not wanted in the initial command palette state?) 

> This command should only be enabled if the template part actually exists. You will probably need to get the template parts via the getEntityRecords selector and check their number.

Can you clarify? I believe that a user can create new template parts regardless of whether any exist in the theme already, as long as it's a block theme.

> You could reuse the [useIsTemplatesAccessible()](https://github.com/WordPress/gutenberg/blob/3d8b192c3df3b02f4c1efc9d8154b715dc189600/packages/core-commands/src/site-editor-navigation-commands.js#L260) hook to check if the site editor is accessible.

From what I can tell, that hook only tells me if the current user can `read` templates. An editor-level user can technically read templates but aren't allowed to access the site editor, so in my testing, the hook didn't prevent the command from loading for non-admin users. 

I'm wondering if these types of commands should rely on a slightly different hook that checks `.canUserEditEntityRecord( 'templates' )` because in the latest Gutenberg right now editors see all of these options (Templates, Patterns, etc) in the command palette and they all send the user to a "Sorry, you are not allowed to access this page." screen. (This appears to be new behavior and is not in WordPress 6.5: [Playground Link](https://playground.wordpress.net/#{%20%22landingPage%22:%20%22/wp-admin/%22,%20%22steps%22:%20[%20{%20%22step%22:%20%22runPHP%22,%20%22code%22:%20%22%3C?php%20require%20'/wordpress/wp-load.php';%20$user_id%20=%20wp_create_user('myuser',%20'mypass',%20'myuser@localhost');%20(new%20WP_User($user_id))-%3Eset_role('editor');%22%20},%20{%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20{%20%22resource%22:%20%22wordpress.org/plugins%22,%20%22slug%22:%20%22gutenberg%22%20},%20%22options%22:%20{%20%22activate%22:%20true%20}%20},%20{%20%22step%22:%20%22login%22,%20%22username%22:%20%22myuser%22,%20%22password%22:%20%22mypass%22%20}%20]%20}))

> The Patterns command mentioned above should also be moved here via a separate PR.

I've opened this as a separate PR so we can move these forward together #61416 

Thanks again for the feedback.

**Comment by t-hamano** [comment]
As stated in [this comment](https://github.com/WordPress/gutenberg/pull/61416#issuecomment-2097428349), in order to proceed with this PR, it seems necessary to resolve #61419 first.

**Comment by t-hamano** [comment]
> but then the command is displayed in the initial blank state when you open the command palette in the site editor.

This is probably because you tried adding it to [a command that has a 'site-editor' context](https://github.com/WordPress/gutenberg/blob/990214e2dc21142a5f2fadea2c7a4e89975a8004/packages/core-commands/src/site-editor-navigation-commands.js#L372)? By default, a command should not be displayed if it has no context.

> I believe that a user can create new template parts regardless of whether any exist in the theme already, as long as it's a block theme.

After running this command, I expect the "All template part" menu on the Patterns page to be focused. However, if the theme does not have any template parts and no new template parts have been created yet, this menu itself will not be displayed. This is why I suggested checking if the template part actually exists.

I would like to suggest using the `getNavigationCommandLoaderPerTemplate()` function and changing it as follows.

```javascript
const getNavigationCommandLoaderPerTemplate = ( templateType ) =>
	function useNavigationCommandLoader( { search } ) {
		// ...
		const commands = useMemo( () => {
			// ...
		}, [ isBlockBasedTheme, orderedRecords, history ] );

		if ( records.length > 0 && templateType === 'wp_template_part' ) {
			commands.push( {
				name: 'core/edit-site/open-template-parts',
				label: __( 'Template parts' ),
				// ...
			} );
		}

		return {
			commands,
			isLoading,
		};
	};
```

**Comment by bacoords** [comment]
Thank you for the feedback! A few updates:

- Technically the "All Template Parts" screen still loads if you don't have any template parts, but because the sidebar navigation just shows "Patterns", I agree it's a confusing experience and that using `getNavigationCommandLoaderPerTemplate` is the cleanest approach in the context of this PR.
- I've added the command to the `getNavigationCommandLoaderPerTemplate` but ended up needing to put it inside the useMemo to make sure it wasn't loading the command multiple times and dependent on the records. That did require a little bit of reconfiguring the return and using the memo dependencies correctly, but I believe it's all functioning correctly now.

There is still a separate permissions issue that these template parts now load in the command palette for "Editor" level users, but if they select one, it send them to an error page. If it makes sense, I can open a separate PR for that.

**Review by t-hamano — APPROVED** [review]
LGTM!

- ✅ Works both inside and outside of the site editor.
- ✅ It also works with classic themes that support template parts.

> There is still a separate permissions issue that these template parts now load in the command palette for "Editor" level users, but if they select one, it send them to an error page. If it makes sense, I can open a separate PR for that.

Yes, I also noticed this issue in #61444.

> While creating this PR, I also noticed that individual pages, individual templates, and individual template parts were exposed to non-admin users via the command palette. These are caused by the fact that there is no permission check in the first place, so I would like to fix it in a follow-up PR.

However, I haven't started creating a PR yet, so if you're interested in working on it, I'd be happy to review it.

**Pull request merged**
