### PR TITLE
Fix/22442 default required removed urlinput

### PR DESCRIPTION
**Pull request by HILAYTRIVEDI**
The `required `field in the `URLInput `set to false for now. In the future a control can be added.

### CODE REVIEW

**Comment by carolinan** [comment]
Hi @HILAYTRIVEDI 
It looks like this pull requests includes code from 34677?
Can you please separate them, and also use the pull request template?

**Comment by HILAYTRIVEDI** [comment]
> Hi @HILAYTRIVEDI
> It looks like this pull requests includes code from 34677?
> Can you please separate them, and also use the pull request template?

Sure

**Comment by skorasaurus** [comment]
ref https://github.com/WordPress/gutenberg/issues/22442

**Comment by carolinan** [comment]
I am closing this pull request because it has not been maintained and updated in two years, and because it contains changes that are that are unrelated -like the color of the social icons block.

**Pull request closed without merging**
