### PR TITLE
Improves the alt text copy for images

### PR DESCRIPTION
**Pull request by karmatosed**
This PR brings the copy in from #19068 and iterates alt text on images to be a little more explanatory.

Here is what the result is:

image

What I am looking for specifically is feedback around the following:

- The copy contents. In seeing this PR it is a lot visually for a link. What should be split or could?
- What should have a link?
- Should we keep the link out?

### CODE REVIEW

**Comment by enriquesanchez** [comment]
How about if we remove the link on the first sentence and add a "Learn more" link at the end of the paragraph?

**Comment by karmatosed** [comment]
@enriquesanchez that's a good idea. The only ponder is should we remove the 'leave empty'?

I haven't pushed the PR but this is what it could look like, I pushed with removing leave empty to see.

image

**Comment by carolynannewells** [comment]
Hello! Jumping in from editorial. I don't think we need to keep the "leave empty" sentence. We could also simplify the text even further: 

Explain the image for the vision impaired. Learn more.

**Comment by afercia** [comment]
I asked the accessibility team to discuss this proposed change during next meeting on Slack.. 

Personally, I don't see the need to change the current text. It was carefully crafted to communicate two fundamental concepts;
1. The alt text describes _the purpose_ of the image, it's not the image description. The purpose can be very different from the image content, depending on usage and context. The link points to a resource that explains this concept in detail..
2. In most of the cases, images are purely decorative and don't need an alt text. The part "Leave empty if the image is purely decorative." is fundamental to communicate this concept to users as they tend to think they have to provide an alt text in all cases (which is wrong).

Additionally, the same text/link is used in other places in the WordPress admin (edit media page, media library, media modal...) so any change should be coordinated across the WP admin.

**Comment by karmatosed** [comment]
@afercia thanks for your thoughts. It's worth noting that there has been a companion trac ticket to the original issue #19068 here for a while, https://core.trac.wordpress.org/ticket/48939 is the ticket. Whilst it might seem clear, the text really isn't so let's see how we can find a balance between what needs to be there and what can be iterated to make it clearer.

> The alt text describes the purpose of the image, it's not the image description. 

I don't think the current PR's text is saying anything else, however are you of that feeling? To be clear here is what it is currently suggested to say:

image

**Comment by afercia** [comment]
>  It's worth noting that there has been a companion trac ticket to the original issue here for a while, https://core.trac.wordpress.org/ticket/48939 is the ticket

It is worth noting that the Trac ticket didn't have the "Accessibility" focus set so no one in the Accessibility team was aware the ticket existed 🙂 

> Whilst it might seem clear, the text really isn't so

I'm not sure I fully understand what specific parts of the current text aren't clear. Can you please clarify which specific parts aren't clear enough?

As per the new proposer text:

- "giving context to visitors with vision impairments" isn't fully correct: the alt text is an alternative for users who can't see the image and also when images aren't loaded for any reason. When an image is "broken" and doesn't load, browsers display the alt text.
- The link "Learn more" is equivalent to the various "Read more", "Click here" and the like: it's definitely not clear especially when read out of context and, generally, such links are a bad practice. Using as link text the sentence that is relevant to the link purpose is way better.
- The new proposed text doesn't clarify at all that in most of the cases an empty alt text is the best option because in most of the cases images are purely decorative. This is a fundamental point that was carefully considered when the current text was elaborated and crafted in the shortest possible way.

Comparing the two text:

Current:
[link]Describe the purpose of the image[/link]. Leave empty if the image is purely decorative.

New proposal:
Alt Text explains an image's purpose, giving context to visitors with vision impairments. [link]Learn more.[/link]

I'm not sure I understand how the new text improves clarity over the current one. Overall, I don't see a good reason to change it but I asked the accessibility team to have a look and discuss during next meeting on Slack anyways, for greater transparency. Also, I'm not sure this is a decision that can be made by only one accessibility team member because the current text was discussed and agreed upon by the entire team.

**Comment by karmatosed** [comment]
There seem some merge conflicts and also some discussion here not leading to a conclusion, so for now closing this PR.

**Pull request closed without merging**
