### PR TITLE
Adds default wp-block-list class to list block

### PR DESCRIPTION
**Pull request by luminuu**
## Description

This pull request adds a default class `wp-block-list` to the list block on the frontend. The issue for this is #12420. The change enhances the developer experience as it enables developers to use a specific selector for the list block, without having to rely on any parent elements or using too many :not() statements.

## How has this been tested?

Local environment: MAMP with WP 5.8.2 installed on macOS Catalina
Tested by adding a new list block to a post. Also changed various settings as well as adding additional CSS classes at the advanced tab. 

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
There's a much simpler way of doing this, if I recall correctly. Just remove [this line](https://github.com/WordPress/gutenberg/blob/914c9c960a230136072119451eeb2ebb2625f3e4/packages/block-library/src/list/block.json#L40) in the List `block.json`.

By default, the block editor generates a class name from the name in the `block.json` and adds it to the block's markup automatically. The reason the List block didn't have it was that it was explicitly disabling the feature.

Also, it's likely that several tests will need to be updated to reflect the altered markup.

**Comment by luminuu** [comment]
> There's a much simpler way of doing this, if I recall correctly. Just remove [this line](https://github.com/WordPress/gutenberg/blob/914c9c960a230136072119451eeb2ebb2625f3e4/packages/block-library/src/list/block.json#L40) in the List `block.json`.
> 
> By default, the block editor generates a class name from the name in the `block.json` and adds it to the block's markup automatically. The reason the List block didn't have it was that it was explicitly disabling the feature.
> 
> Also, it's likely that several tests will need to be updated to reflect the altered markup.

This was actually my first try but it didn't seem to have any effect. But I'm happy to learn if I just missed something else.

I also didn't expect that many tests to fail but they just do because of the altered markup with the class, as it seems.

**Comment by luminuu** [comment]
I've checked again on the code and it looks like I actually missed something while testing earlier. I reverted my previous change and removed the className property in block.json as suggested by @ZebulanStanphill.

I also updated a few files related to tests to make them pass with the new markup, still working on that.

**Comment by markhowellsmead** [comment]
See also https://github.com/WordPress/gutenberg/issues/12420#issuecomment-976007056.

**Pull request closed without merging**
