### PR TITLE
Raw handler: always normalize

### LINKED ISSUE #19533: Gutenberg is not normalizing if text is pasted from within Gutenberg
**Describe the bug**
If NFD text (decomposed characters) is pasted in the editor it gets normalized on paste via JS/ES6.

Since this issue/PR for details: 
https://github.com/WordPress/gutenberg/issues/433
https://github.com/WordPress/gutenberg/pull/6880

But if I have NFD text in the editor from before Gutenberg and copy&paste it from within Gutenberg, it does not normalize.

**To reproduce**
1. Go to https://core.trac.wordpress.org/ticket/30130 and download the PDF
2. Open the PDF in Preview on a Mac
3. Copy the content to the editor (in Chrome or Firefox, NOT Safari)
4. Paste it in classic WP editor (no normalization - which is correct)
5. Switch to Gutenberg
6. Copy the text inserted in 4. and paste it in a new paragraph
7. No normalization. **Not** correct this time.
(8. You can copy and paste direct from the PDF to Gutenberg, which is working correctly.)

**Expected behavior**
I expected the normalization to happen all the time, even if copy&paste from within Gutenberg.

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6, but should happen on all Macs (tested up to 10.14)
 - Browser: Paste in Firefox/Chrome (Safari is normalizing all inputs)

**Smartphone (please complete the following information):**
 This could not be reproduced in iOS.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #19533.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by ellatrix** [comment]
@Zodiac1978 does this fix your problem?

**Comment by Zodiac1978** [comment]
@ellatrix Can you point me to a tutorial on how to apply this change? I have downloaded the branch and lokked at the files, but I can't find paste-handler.js for example in the Gutenberg plugin (7.2) or in WP core (5.3.2). Any help is much appreciated!

**Comment by Soean** [comment]
@Zodiac1978 The easiest way is to test this PR on http://gutenberg.run/19559

If you want to test it local. you have to clone this repository into you plugin folder, 
`git clone https://github.com/WordPress/gutenberg.git`
check out the branch
`git checkout try/raw-handler-normalize`

After this, you have to build the JS files. Run `npm install` and `npm run build`. 
There is no single `paste-handler.js` loaded in the browser, a compiled JS file will be loaded. Maybe you have to delete your browser cache.

Here are docs about this topic: https://github.com/WordPress/gutenberg/blob/master/docs/contributors/getting-started.md

**Comment by Zodiac1978** [comment]
@Soean Thanks for the link and explanation. Much appreciated!

@ellatrix If i use the link from @Soean (http://gutenberg.run/19559) and copy the content from the PDF into title and content it doesn't work at all. Nor normalization in titel and no normalization in content anymore.

**Comment by Zodiac1978** [comment]
@ellatrix Any idea why this does not work as expected?

**Comment by Zodiac1978** [comment]
Getting "Invalid pull request" for http://gutenberg.run/19559 - Just FYI @ellatrix

**Pull request closed without merging**
