### PR TITLE
Site editor: Fix non-us spelling in sidebar

### LINKED ISSUE #48966: Small typo in WP 6-2 Site Editor
### Description

https://build.trac.wordpress.org/browser/trunk/wp-includes/js/dist/edit-site.js?marks=8008#L8008
reads:
`description: (0,external_wp_i18n_namespaceObject.__)('Create new template parts, or reset any customisations made to the template parts supplied by your theme.')`

Since source language is US English, customisations should be changed to customizations.

Rel: https://core.trac.wordpress.org/ticket/57895

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet

N/A

### Environment info

N/A

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?
Changes customisations to customizations

## Why?
All source strings should be in US spelling. Sorry Charles, that is just how it is 😄 
Fixes: #48966

## How?
With my keyboard.

## Testing Instructions
Look at customizations and if you can imagine dear Elizabeth turning in her grave it is correct.

### CODE REVIEW

**Review by alexstine — APPROVED** [review]
👍

**Comment by Mamaduka** [comment]
Thank you, @glendaviesnz! Is this alternative to #48967?

**Comment by glendaviesnz** [comment]
> Thank you, @glendaviesnz! Is this alternative to #48967?

🤦 that is weird @Mamaduka , I am not sure how I missed that other PR being attached to the issue, I must have done this before I had my first ☕ for the day.

We should probably close this in favour of @dream-encode one if the import statement issue over there can be sorted.

**Comment by Mamaduka** [comment]
Not a problem. Let's keep both open for now 👍

**Review by apeatling — APPROVED** [review]
I think we can merge this one since it doesn't have the import statement issue?

**Review by hellofromtonya — APPROVED** [review]
Yes, the string is now in the US form. LGTM 👍 

This change can be updated in WordPress Core for 6.2 RC2.

**Comment by hellofromtonya** [comment]
@Mamaduka please include this fix in the 6.2 RC2 package updates.

**Comment by hellofromtonya** [comment]
>I think we can merge this one since it doesn't have the import statement issue?

I agree with @apeatling. This PR is fixes the reported issue for 6.2 RC2. Props will also be given to @dream-encode. 

Then the `import` fix in PR #48967 can be handled separately, but not as part of 6.2 RC fixes.

**Comment by Mamaduka** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: f230fa4922

**Pull request merged**
