### PR TITLE
Revert "[Try] Customizable toolbar contents (#23613)"

### PR DESCRIPTION
**Pull request by talldan**
This reverts commit 5078c43a3d72eded68d94488dbe6093454815a0e.

## Description
Reverts the API introduced in #23613, which will be superseded by #25890.

While there's still a desire to add in-toolbar editing of items  (Linking #23375, Image cropping), the approach taken in that PR isn't accessible as it replaces the DOM and results in focus loss.

I don't see a way to rework this existing API to be accessible, so I think it's best to start from scratch with something new.

This API is currently unused, so there should be no issue reverting.

### CODE REVIEW

**Comment by adamziel** [comment]
Not a blocker by any means, but just noting reverting these changes would rid this nice side-effect of having CSS transitions in place:



I quite enjoyed the aesthetics of smooth resizing (vs instant change) so just flagging it here. CC @shaunandrews @mapk, maybe it would inspire some future work.

**Comment by gziolo** [comment]
Should it be merged or closed now that a few weeks passed? 😃

**Comment by adamziel** [comment]
@talldan this has conflicts now, would you solve them and ping me? Let's get this in

**Comment by talldan** [comment]
Rebased!

**Review by adamziel — APPROVED** [review]
LGTM 👍

**Pull request merged**
