### PR TITLE
Dataviews: Add: Bulk actions toolbar.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Implements a toolbar to make bulk actions more visible as suggested by @jameskoster in https://github.com/WordPress/gutenberg/issues/59043#issuecomment-1979230772.

## Testing
Select some items and verify a toolbar with bulk actions appears.
Apply some bulk actions and verify things work as expected.

## Screenshot
Screenshot 2024-03-08 at 16 11 20

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for kicking this off :) A couple of quick comments on the functionality:

* Would it be possible to make the toolbar appear with some subtle animation, similar to Snackbars? This will help bring it to the users attention.
* Can we also fix it in position? Currently if many records are visible the toolbar is hidden from view until you scroll.
* There's a regression with the pagination bar – it should be sticky link on trunk.

**Comment by jorgefilipecosta** [comment]
Thank you for the review @jameskoster!


> * Would it be possible to make the toolbar appear with some subtle animation, similar to Snackbars? This will help bring it to the users attention.

We already have a subtle on the popover. It's the default behavior and we are not removing it. If we want something more disabled I guess we would need to introduce different animations on the popover component itself or change the animation for all the popover. Would it be possible to share which Gutenberg animation would you want to replicate?

> * Can we also fix it in position? Currently if many records are visible the toolbar is hidden from view until you scroll.

I think it should be fixed, the popover should now automatically find a place visible to show the toolbar if it is not possible to show it at the buttom.

> * There's a regression with the pagination bar – it should be sticky link on trunk.

It should also be fixed now.

**Comment by jameskoster** [comment]
I made a quick prototype to demonstrate the animation and scroll behavior. The animation is based on the Snackbar component.

https://github.com/WordPress/gutenberg/assets/846565/491a16c3-46df-4cb4-a269-c27955c27655

Appreciate the animation may be tricky to replicate if we're using the popover component. The fixed position during scroll is more important.

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, I updated this PR. Now the toolbar should always be visible, and I introduced an animation similar to the SnackBar. Let me know if this is the expected behavior.

**Comment by jameskoster** [comment]
@jorgefilipecosta thanks for the updates! I pushed some style adjustments – in terms of design we're looking pretty good.

One observation; I'm only seeing the toolbar on the pages data view, not on the Patterns or Templates data view 🤔

**Comment by jameskoster** [comment]
@jorgefilipecosta one other observation: when you view Trash, select an item, and click "Restore" in the toolbar there's a brief flash of different actions before the toolbar disappears. 

You can see it briefly in this video:


https://github.com/WordPress/gutenberg/assets/846565/e3835f58-f250-4712-a2a8-c8c68d73b0e8


It is much more apparent when you have a large selection (also notice the flashing save button in the bottom left):



https://github.com/WordPress/gutenberg/assets/846565/bb981ddf-61d9-4571-bf6d-96c313d3e00c

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, thank you for the reviews.
The toolbar was not showing on templates because we were only including primary actions and templates don't have any primary action. I updated and now the toolbar is available for any bulk action with an icon.

Regarding the flashing issue on post restore, it is something complex, I made some changes which should reduce the perception of the issue.

**Comment by jameskoster** [comment]
Thanks for the update :) I see the toolbar on the Templates page, but not the Patterns page. For Patterns, 'Delete' and 'Export as json' should be available as bulk actions ('Delete' should invoke a confirmationdialog).

There seems to be a z-index issue on the templates page:

Screenshot 2024-04-10 at 18 32 57

> Regarding the flashing issue on post restore, it is something complex, I made some changes which should reduce the perception of the issue.

Here's what I see:

https://github.com/WordPress/gutenberg/assets/846565/025d166d-6df6-47a0-b9f9-998d3354a860

It's an improvement, but it _feels_ a bit laggy. I think it's because it's not obvious anything is happening until you see the records disappearing in the background. An idea to try: 

1. Add the `isBusy` prop to the 'Delete' button when records are being deleted.
2. Do not update the count ("Are you sure you want to delete **20** pages?") in the modal each time a record is deleted.

In the resulting Snackbar, instead of "Pages moved to trash", could it read "_X_ pages moved to trash"?

**Comment by jameskoster** [comment]
This is working better with the frozen modal, thanks for working on it! Could we also try adding the `isBusy` prop to the button?

On a similar train of thought; I wonder if it would it be possible to apply this treatment to the bulk action toolbar itself? IE when there is no confirmdialog for an action (e.g. restoring trashed pages), freeze the toolbar on-click and add `isBusy` to the selected action:

toolbar

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,
I implemented the busy states as suggested. I ended up inspired by @mcsf approach to avoid rerendering using references (it was a really nice idea that had not occurred to me before). I continued with the reference idea but added logic for busy states. I think this is ready for another pass.

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta, it's close now!

The busy prop is working well for actions without a confirmation modal. But when there's a confirmation modal (e.g. trashing) it's the button in the modal that should receive the busy prop. Is that possible?

Screenshot 2024-04-22 at 15 48 13

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,
I tested this in multiple browsers and it seems the busy state is reflected also on the button inside the modal.
This is what I'm seeing:

https://github.com/WordPress/gutenberg/assets/11271197/23465a6c-048e-4ea2-a1d9-e0040d902360

(This test has code to simulate a very slow server response while reverting each post to make it easier to see busy states but without that, the busy states are also shown on the modal it is just much faster).

The busy states appear on the button that opens the modal and on the modal. Would you prefer them to be just shown on the modal?

**Comment by jameskoster** [comment]
> Would you prefer them to be just shown on the modal?

Yeah, if it's possible? 🙏  I think it will be less distracting.

**Comment by jorgefilipecosta** [comment]
> > Would you prefer them to be just shown on the modal?
> 
> Yeah, if it's possible? 🙏 I think it will be less distracting.

The change was applied, when there is a modal the busy state is now only reflected on the modal button.

**Comment by jorgefilipecosta** [comment]
> > Would you prefer them to be just shown on the modal?
> 
> Yeah, if it's possible? 🙏 I think it will be less distracting.

Hi @jameskoster, the change was applied, when there is a modal the busy state is now only reflected on the modal button.

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta, it's working well now.

I think the last thing to tweak before getting wider feedback is the busy state on the toolbar buttons. It's a bit strange how the button spans the full height of the toolbar here:

Screenshot 2024-05-01 at 11 15 15

I'll see if I can push a fix for that. 

---

Not to fix here, but noting there's an issue where the busy state on the button is overridden by the hover state. If you don't move the mouse after clicking the button you don't see the busy animation at all.

https://github.com/WordPress/gutenberg/assets/846565/5c065591-48f4-4629-b2be-12c5f57ac094

It would be good to follow up to ensure the animation persists on hover.

**Comment by jameskoster** [comment]
Pushed some adjustments. I see one remaining issue. On the templates page, the actions in the toolbar are inconsistent with the actions in the menu. In the screenshot below notice how I can reset / delete via the menu, but in the toolbar these actions are disabled.

Screenshot 2024-05-01 at 11 36 50


Ideally the actions in the toolbar should be enabled too.

I noticed that no actions appear in the Patterns page, but I assume that's because there are no `primary` actions on that page?

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,
> Pushed some adjustments. I see one remaining issue. On the templates page, the actions in the toolbar are inconsistent with the actions in the menu. In the screenshot below notice how I can reset / delete via the menu, but in the toolbar these actions are disabled. 

This was fixed.

> I noticed that no actions appear in the Patterns page, but I assume that's because there are no primary actions on that page?

Exactly we don't have primary actions there yet. As a follow up we can decide if some of the pattern actions should be primary.

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta, very close now! I noticed there's a small bug with the template delete action when invoked from the toolbar, it seems to do both; reset _and_ delete. To replicate:

1. Edit a theme template
2. Create a custom template
3. Go to templates data view and select the theme template you edited and the custom template
4. Click "Delete" in the quick actions toolbar
5. Notice that the custom template is deleted as expected, but also the theme template gets reset. This is inconsistent with the "Delete" action in the bulk actions _menu_ which behaves correctly.


https://github.com/WordPress/gutenberg/assets/846565/aea0cc8f-de0c-41ab-b259-babcd47862ef

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, good catch, the bug where delete also reverts the customizations was fixed.

**Comment by jameskoster** [comment]
Nice, I think this is ready for wider feedback :)

**Comment by jarekmorawski** [comment]
I just took it for a spin and it's looking great! I have a few thoughts but feel free to disregard them if you plan on making further UX changes.

- I wonder if the toolbar should be dark to stand out more against the white background of the table. If there are not enough items to fill the screen, it's pretty easy to miss (especially on larger screens where the toolbar is pretty far away from the top of the table).
- Should we make the X/Cancel button subtler? It could be just me, but it looks like a content-related action, similar to `Move to trash`. The tooltip only says `Cancel`, which doesn't make it clear if I'll be canceling the bulk editing flow or the item (in some products, `Cancel` can be an actual action).
- Do we still need the `Edit X items` in the top right corner given that we now have the toolbar?
- If so, can we align the copy so it's clear both elements do the same thing? We could use the toolbar's description as the button label (`X items selected` vs. `Edit X items`).
- Would it make sense to reveal additional selection options when the user clicks `X items selected` in the toolbar? Being able to select or deselect all can be useful in some situations.
- Minor details, but we can display the tooltip _above_ the button? Currently, we show it under the toolbar, which makes it a bit difficult to read because it's too close to the edge of the screen.

**Comment by jameskoster** [comment]
> I wonder if the toolbar should be dark to stand out more against the white background of the table. If there are not enough items to fill the screen, _it's pretty easy to miss_

I share this concern, and making the toolbar dark could be something to try. I'd lean towards looking into that separately because there could be other options (different animation effect, dark border, etc.).

> Should we make the X/Cancel button subtler?

Do you have a suggestion? Maybe we don't need the cancel button given you can use the checkbox in the table header?

> Do we still need the Edit X items in the top right corner given that we now have the toolbar?

Do you mean the label, or the menu itself? I think we still need the menu – it's much more accessible quick-action interface for screen readers and keyboard users. The quick-actions toolbar is mostly an affordance for sighted mouse/trackpad users. It would be nice to combine them somehow down the road but until now a solid design hasn't presented itself. 

> If so, can we align the copy so it's clear both elements do the same thing?

There's a nuance that makes the labelling a bit tricky, the options in this menu / toolbar aren't really "edits", they're "actions". It's an important distinction because we need to entertain bulk _editing_ down the road. This may also be one to look into separately there's a bright idea.

> Would it make sense to reveal additional selection options when the user clicks X items selected in the toolbar? Being able to select or deselect all can be useful in some situations.

If it's trivial for @jorgefilipecosta to implement I reckon that's worth a try.

> Minor details, but we can display the tooltip above the button?

Good catch, I'll tweak that.

**Comment by jameskoster** [comment]
@jorgefilipecosta I think there's one last small change to make here. When the button (both in the toolbar and the modal) are busy, can they also be `disabled` (with `__experimentalIsFocusable`)?

Thanks!

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,

The disabled of the buttons while busy was added, let me know if it is the expected behavior.

Regarding:
> Would it make sense to reveal additional selection options when the user clicks X items selected in the toolbar? Being able to select or deselect all can be useful in some situations.

We can explore this in a follow-up PR, as this one is already big, but it seems like a good thing to add.

**Comment by jameskoster** [comment]
I see the button in the toolbars are not `disabled` + `busy`, but the one in the modal (the 'Delete' button) is still only `busy`.

**Comment by jorgefilipecosta** [comment]
> I see the button in the toolbars are not `disabled` + `busy`, but the one in the modal (the 'Delete' button) is still only `busy`.

Hi @jameskoster, I'm sorry there was an error while pushing and my changes were not yet there 😅
The changes should now be available.

**Review by jameskoster — APPROVED** [review]
It's working now :) 

A _tiny_ detail to fix:

Screenshot 2024-05-09 at 16 08 38

1. The 'restored' snackbar refers to `post`s, but these are pages.
2. The 'moved to trash' snackbar could show the count.

Otherwise this looks good in terms of design, and is ready for a code review. Thanks for all the hard work!

**Comment by jorgefilipecosta** [comment]
> It's working now :)
> 
> A _tiny_ detail to fix:
> 
> Screenshot 2024-05-09 at 16 08 38
> 1. The 'restored' snackbar refers to `post`s, but these are pages.
> 2. The 'moved to trash' snackbar could show the count.
> 
> Otherwise this looks good in terms of design, and is ready for a code review. Thanks for all the hard work!

Hi @jameskoster,
I improved the messages in a separate PR because this issue already existed. The fix is available https://github.com/WordPress/gutenberg/pull/61539.

Thank you for all the reviews and suggestions you made on this PR.

**Pull request merged**
