### PR TITLE
Interactivity API: Delay block hydration to allow interactive block stores to initialize

### LINKED ISSUE #66691: Image Block: Lightbox does not work
### Description

When I insert an Image block with the lightbox enabled into the content, the lightbox doesn't work. Also, the Navigation block doesn't work either.

The following error is logged in the browser console:

```
view.js:46 Uncaught (in promise) ReferenceError: Cannot access 'state' before initialization
    at get isMenuOpen (view.js:46:21)
    at callback (signals.ts:106:15)
    at y.x (utils.ts:179:11)
    at __webpack_modules__../node_modules/@preact/signals-core/dist/signals-core.module.js.h (index.ts:567:22)
    at c (index.ts:415:18)
    at t (index.ts:61:39)
    at r (index.ts:102:3)
    at deepMerge (state.ts:397:7)
    at store (store.ts:247:12)
    at view.js:21:33
```

I think this issue is related to #66001. I temporarily reverted #66001 and it fixed the issue.

### Step-by-step reproduction instructions

This issue is a bit unstable, refresh your browser a few times if you can't reproduce it.

- Insert an Image block.
- Apply lightbox and save the post.
- Check the post on the frontend.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/f0ae9362-2879-4df3-b929-7c64472c1e25

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #66691.

When `scheduler.yield()` is available, the `splitTask()` function is implemented to use it. When a task is split with `scheduler.yield()` it results in the tail being added to the front of the task queue. In contrast, when `splitTask()` is implemented with `setTimeout()` (when `scheduler.yield()` is not available), then the tail of the split task is added to the end of the task queue. It appears there is a race condition between the call to `init`. 

In particular, given this `init` function:

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/interactivity/src/init.ts#L30-L46

It is getting invoked _before_ the code in a block's `view.js` is invoked, for example:

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/block-library/src/image/view.js#L22

When `splitTask()` is was using `setTimeout()` then the calls to `await splitTask()` had the effect of delaying the hydration until _after_ the blocks' view modules execute. But when `splitTask()` is implemented with `scheduler.yield()` the hydration logic is executing _before_ the interactive blocks' view module (i.e. the store initialization) executes. 

Of note, the error also occurs if `await splitTask()` is eliminated from `init` function as well, indicating that it was not correctly accounting for delaying the Interactivity API's `init` until _after_ the interactive blocks have all initialized. There seems to be a dependency problem here, where hydration of an interactive block should be blocked until its corresponding view script module has loaded. This seems to be related to:

* https://github.com/WordPress/gutenberg/issues/2768
* https://github.com/WordPress/gutenberg/discussions/52723
* [Blocks: Introduce a way to enqueue view scripts only when needed for interactivity](https://core.trac.wordpress.org/ticket/59462)

In the mean time, adding a `setTimeout()` to handle the delay seems to do the trick.

# Code execution with `splitTask` implemented with `setTimeout` 

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/interactivity/src/init.ts#L31-L38

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/block-library/src/image/view.js#L22

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/interactivity/src/init.ts#L39-L46

# Code execution with `splitTask` implemented with `scheduler.yield` 

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/interactivity/src/init.ts#L30-L46

https://github.com/WordPress/gutenberg/blob/7f49b39e1e3e2eaf274b6fb03ae22508cc583d31/packages/block-library/src/image/view.js#L22

### CODE REVIEW

**Comment by michalczaplinski** [comment]
Thanks for investigating and creating the PR @westonruter ! 🙂 

The current solution does fix the problem. However, even with the current workaround, the issue will persist if I remove or comment out the `splitTask ()` calls in `init().` I think it's not optimal that we have an implicit dependency on `splitTask()` which should just be a performance optimization.

I'm currently trying to figure out a better way to handle this.

**Review by cbravobernal — APPROVED** [review]
As @michalczaplinski commented, we can work in a follow-up PR to find a better solution. Meanwhile, I'll merge it and include it on today's Gutenberg release.

**Comment by cbravobernal** [comment]
I just cherry-picked this PR to the release/19.6 branch to get it included in the next release: f4b013f830d

**Comment by westonruter** [comment]
> The current solution does fix the problem. However, even with the current workaround, the issue will persist if I remove or comment out the `splitTask ()` calls in `init().` I think it's not optimal that we have an implicit dependency on `splitTask()` which should just be a performance optimization.

@michalczaplinski Really? I commented out the `splitTask()` calls and I was getting the error still. I just checked again, and I continue to get the errors. With this merged PR, I commented out these lines:

```diff
diff --git a/packages/interactivity/src/init.ts b/packages/interactivity/src/init.ts
index fa1eec51c3e..adc17a6458e 100644
--- a/packages/interactivity/src/init.ts
+++ b/packages/interactivity/src/init.ts
@@ -40,17 +40,17 @@ export const init = async () => {
 	 * This occurs when splitTask() is implemented with scheduler.yield() as opposed to setTimeout(), as with the former
 	 * split tasks are added to the front of the task queue whereas with the latter they are added to the end of the queue.
 	 */
-	await new Promise( ( resolve ) => {
-		setTimeout( resolve, 0 );
-	} );
+	// await new Promise( ( resolve ) => {
+	// 	setTimeout( resolve, 0 );
+	// } );
 
 	for ( const node of nodes ) {
 		if ( ! hydratedIslands.has( node ) ) {
-			await splitTask();
+			// await splitTask();
 			const fragment = getRegionRootFragment( node );
 			const vdom = toVdom( node );
 			initialVdom.set( node, vdom );
-			await splitTask();
+			// await splitTask();
 			hydrate( vdom, fragment );
 		}
 	}
```

And I get these errors:

image

**Comment by michalczaplinski** [comment]
@westonruter, I'm unsure what you mean 🙂. I think that we're in agreement that the `Cannot access 'state'...` issue persists even if you comment out the `splitTask()` calls in `init()`. This is what I meant with my previous comment.

**Comment by westonruter** [comment]
@michalczaplinski Oh, hah, sorry! I misunderstood.

**Comment by michalczaplinski** [comment]
Sorry, I should have been more clear earlier too 🙂 . Here's my expanded explanation with additional details:

Adding `await new Promise(...)` inside the `init()` (which was done in the current PR) fixes https://github.com/WordPress/gutenberg/issues/66691. This fix ALSO works even if you comment out the `splitTask()` calls.

However, relying on `await new Promise(...)` inside the `init()` can be brittle. Imagine a custom block adding another `await new Promise(...)` at the module level in its `view.js` file. This will cause the same problem to reappear because now the individual `view.js` file adds a task to the end of the task queue. 

I'm not sure if there's a better solution at this point than what was merged in the current PR. @DAreRodz and I have considered wrapping the `init()` with `DOMContentloaded` as it was removed [here](https://github.com/WordPress/gutenberg/pull/62734/files#diff-4de475b0cec8c41772c15d23b8362d381a8afb8fe03afd746c21a4f698eb55f2L58-L61), but that does not solve the problem either.

**Comment by westonruter** [comment]
> I'm not sure if there's a better solution at this point than what was merged in the current PR. @DAreRodz and I have considered wrapping the `init()` with `DOMContentloaded` as it was removed [here](https://github.com/WordPress/gutenberg/pull/62734/files#diff-4de475b0cec8c41772c15d23b8362d381a8afb8fe03afd746c21a4f698eb55f2L58-L61), but that does not solve the problem either.

AFAIK, the `DOMContentLoaded` event won't work specifically because these are script modules, and script modules execute after this event. So if any script module tries to add a `DOMContentLoaded` event, the event will never fire.

**Comment by michalczaplinski** [comment]
> AFAIK, the DOMContentLoaded event won't work specifically because these are script modules, and script modules execute after this event. So if any script module tries to add a DOMContentLoaded event, the event will never fire.

right, exactly 🙂

**Comment by luisherranz** [comment]
@DAreRodz let's take a look at this for WordPress 6.8 to see if we can ensure there are no issues when stores initialize after the `init` function is called, which is necessary for future implementations, like lazy loading blocks.

That being said, it's okay for the blocks that load initially to do so before the init function, as it is happening today (because we can optimize a few things in the init function itself).

**Comment by westonruter** [comment]
I've re-opened #66691 because it doesn't seem this issue is reliably fixed. As per https://github.com/WordPress/gutenberg/issues/66691#issuecomment-3122013287, I still get errors sporadically, like:

> ReferenceError: Cannot access 's' before initialization at get isMenuOpen

**Comment by DAreRodz** [comment]
Thanks, @westonruter. We have opened an issue to address the initialization inconsistencies currently present in the Interactivity API.

- https://github.com/WordPress/gutenberg/issues/70870 

Also, for this error in particular, there is a specific issue, so we already have this one on our radar. 🙂 

- https://github.com/WordPress/gutenberg/issues/70874

**Pull request merged**
