### PR TITLE
Issue/4998 - Make query-panel block available

### LINKED ISSUE #4998: The query-panel block cannot be accessed via wp.blocks
## Issue Overview

The `query-panel` block cannot be accessed via `wp.blocks`.

## Steps to Reproduce

```
const QueryPanel = wp.blocks.QueryPanel;
console.log(QueryPanel);
```

Will be `undefined`.

### PR DESCRIPTION
**Pull request by amdrew**
Fixes #4998

### CODE REVIEW

**Comment by paulwilde** [comment]
It would make sense to rename this component if it were to be exposed, as it doesn't do what I would expect from the name. It's more of an abstraction of logic for the Latest Posts block rather than a standalone component that is very reusable.

**Comment by jorgefilipecosta** [comment]
> It's more of an abstraction of logic for the Latest Posts block rather than a standalone component that is very reusable.

Hi @amdrew thank you for creating this PR. I think the component should be exposed, and it was a bug  that it was not exposed before.

> It's more of an abstraction of logic for the Latest Posts block rather than a standalone component that is very reusable.

Hi @paulwilde, the QueryPanel component was implemented according to what was specified in issue  https://github.com/WordPress/gutenberg/issues/2662. The idea is for the component to be reusable and used outside latest posts.
It allows us to abstract a UI to select the category, number of items and order criteria, with the possibility to hide some of the inputs. The expectation was that querying posts will be a very recurrent pattern in blocks, e.g for custom post types. As a practical use case, using this component we can create a "book" query UI as part of some other block or plugin. The block creator besides this Component can include UI to input other filters. But I agree with you the name is misleading as the component does not query it's just a UI. Maybe we can rename it to something like QueryPanelUI or something similar, I'm totally open to suggestions.

**Comment by paulwilde** [comment]
@jorgefilipecosta Ah that makes more sense. I had a quick look at the file and saw that it was just a couple of controls abstracted into its own file from the Latest Posts block and assumed it was just to make the block file a little more trim. I have used this sort of thing before with widgets, having controls dedicated to selecting a post type, taxonomy & taxonomy term.

I was thinking the name `PostQueryControls` might make more sense, however I see there is no control which includes the selection of a post type.

**Comment by gziolo** [comment]
> I was thinking the name PostQueryControls might make more sense, however I see there is no control which includes the selection of a post type.

It probably might be just `QueryControls` as it abstracts other controls. @jorgefilipecosta shouldn't it be moved to `wp.components` before it gets exposed? I think we moved a few controls from blocks to components some time ago.

**Comment by gziolo** [comment]
@jorgefilipecosta has the alternative solution that moves this component to `wp.components`. Let's close this one and help to merge #5319. Thanks for raising this issue and initial explorations 👍

**Pull request closed without merging**
