### PR TITLE
ColorGradientControl: Fix awkward padding in popover

### PR DESCRIPTION
**Pull request by mirka**
Part of #43014

## What?

Fixes the awkward padding when the ColorGradientControl's tab switcher appears in a popover (https://github.com/WordPress/gutenberg/pull/41900#issuecomment-1193795265).

## Why?

There is actually a [further redesign](https://github.com/WordPress/gutenberg/pull/41900#issuecomment-1205124434) in the works, but that is going to take a little more time to achieve. So here is an easy, incremental step to make it less weird in the meantime.

## How?

- Remove popover padding so the tab switcher goes edge-to-edge.
- Always add padding to the panels when they are either within a TabPanel, or within a popover.

## Testing Instructions

1. `npm run dev`
2. In the post editor, add a Code block. In the Inspector, see the color popovers for Text and Background.
3. In the Global Styles sidebar, check the Colors settings.

### Before

The tab panel switcher has too much padding

### After

https://user-images.githubusercontent.com/555336/183015280-a0431083-b475-455c-9cfb-cf7e324f82a3.mp4

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Big improvement. Clunky padding above and left of the tabbar before:
Screenshot 2022-08-05 at 10 30 40

Nice and compact after:

Screenshot 2022-08-05 at 10 30 19


I'd encourage a code sanity check, but visually this is a good bugfix. (I still prefer the segmented control, but happy to try this 😅 )

I'm reminded that we have an opportunity to revisit the Swatch component as well — the swatch buttons are currently bigger inside the swatch panel than they are inside the ItemGroup. They should all be 20x20px:

Screenshot 2022-08-05 at 10 31 13

That's separate to this PR, but it stood out. 

Thank you for the work!

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for improving this @mirka 👍 

The awkward padding introduced by https://github.com/WordPress/gutenberg/pull/41900 has been addressed via this PR. 

✅ Extra padding has been removed
✅ Color palette unit tests pass

<details>
<summary>Click for screenshot</summary>

Screen Shot 2022-08-08 at 3 56 58 pm

</details>

While testing, I did notice the extraneous margin on the custom gradient picker. Perhaps this could be another small follow-up? That extra margin has been around for a long time by the looks of it.

<details>
<summary>Click for screenshot</summary>
Screen Shot 2022-08-08 at 3 58 30 pm


</details>

**Review by jameskoster — CHANGES_REQUESTED** [review]
I think there's a small regression here. Previously the swatch rows filled their container 100%:

Screenshot 2022-08-08 at 10 12 56

Now there is a small gap at the end of each row:

Screenshot 2022-08-08 at 10 13 09

Perhaps this was an oversight on the _original_ PR though. If it's easy to address here I think that would be nice.

**Comment by jameskoster** [comment]
Removing the calculated width declaration on `.block-editor-panel-color-gradient-settings__dropdown-content` seems to fixes this, but reduces the swatches in each row to 5.

Screenshot 2022-08-08 at 10 30 41

**Comment by mirka** [comment]
@jameskoster Good catch, thanks! Fixed in e38b7a8:

The popover now fits six swatches

**Comment by mirka** [comment]
> I did notice the extraneous margin on the custom gradient picker. Perhaps this could be another small follow-up?

@aaronrobertshaw Yes, I have a local branch with this fix and will make a PR soon 👍

**Review by jameskoster — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
