### PR TITLE
Scope selector-class-pattern stylelint rule to web stylesheets

### PR DESCRIPTION
**Pull request by dcalhoun**
## Description
Native stylesheets currently do not adhere to the same BEM selector
patterns as web stylesheets. This introduces a custom stylelint plugin
to exclude native stylesheets from the selector-class-pattern rule.

Supersedes #28988.

## How has this been tested?
Ran `npm run lint-css`.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by dcalhoun** [comment]
Aside from the pre-existing linting failures, the CI check failures in this PR appear to be resolved in #29800. Once `fix/styleline-class-name-BEM` is rebased atop the latest `trunk`, the CI checks should, in theory, pass.

**Comment by gziolo** [comment]
What's the difference between this PR and #28988 other than there are no code comments in native `.scss` files?

In both cases, there is some further work necessary to make the linter pass. The remaining violations need to be fixed wherever applicable. I think there are some exceptions:
- at least one native file doesn't have `.native.scss` extension
- `packages/components/src/date-time/datepicker.scss` is coming from the fork so we should disable this rule in the file

**Comment by dcalhoun** [comment]
> What's the difference between this PR and #28988 other than there are no code comments in native `.scss` files?

@gziolo that is the only difference. Native stylesheets and avoiding unnecessary linting noise is the sole focus of this PR. If we decide we _do want_ native stylesheets to adhere to BEM, this PR provides no value. If we decide we _do not want_ native stylesheets to adhere to BEM, this PR allows native developers to avoid the need to remember to add an inline comment to disable the web-specific rule for new stylesheets. This PR avoids the following scenario:

1. Native developer creates new stylesheet.
2. Native developer adds native styles and selectors that do not adhere to BEM, as it is not the team's practice.
3. Native developer receive unexpected linting errors.
4. Native developer investigates the issue and realizes they must add an inline style to disable web-specific linting.

Avoiding that unexpected, unnecessary friction is the focus of this PR.

> In both cases, there is some further work necessary to make the linter pass. 

Absolutely. This PR was solely focused on native stylesheets and iterating on the great progress #28988 made on that subject. I was not attempting to solve all existing linting failures in this PR as I figured that was the scope of #28954. This PR is requesting to merge into `fix/styleline-class-name-BEM` as an interactive step towards addressing all linting errors.

> The remaining violations need to be fixed wherever applicable. I think there are some exceptions:
> * at least one native file doesn't have `.native.scss` extension
> * `packages/components/src/date-time/datepicker.scss` is coming from the fork so we should disable this rule in the file

I perceive `datepicker.scss` to not be native styles and therefore consider it out of the scope of this particular PR. Please let me know if I am misunderstanding that, however. One idea might be to suffix the file with `.vendor.scss` and update the new rule in this PR to exclude any files with that suffix.

Which native file has a filename that does not include `.native.scss`?

I hope this provides insight into my thinking. Thanks for the feedback!

**Comment by gziolo** [comment]
> Which native file has a filename that does not include `.native.scss`?

See: https://github.com/WordPress/gutenberg/pull/29881/checks?check_run_id=2118076618

Screen Shot 2021-03-16 at 13 20 53

> I perceive datepicker.scss to not be native styles and therefore consider it out of the scope of this particular PR

Yes, it's for the web. It isn't vendor code anymore since we maintain a fork of the original library.

So the idea is to merge those changes to the branch opened by @rafaelgalani and fix all the remaining issues there, right?

**Comment by dcalhoun** [comment]
> See: https://github.com/WordPress/gutenberg/pull/29881/checks?check_run_id=2118076618

@gziolo ah, yes. Thank you. 😊 I am happy to investigate resolving that lint error in this PR since it is related to native stylesheets.
 
> Yes, it's for the web. It isn't vendor code anymore since we maintain a fork of the original library.

Alright. I suppose then it may make most sense to update the forked copy to match the BEM selector patterns we desire to use. I would consider that a part of the scope of #28954.

> So the idea is to merge those changes to the branch opened by @rafaelgalani and fix all the remaining issues there, right?

Yes, if the team believes this PR is a sound approach, then I'd recommend we merge this PR into #28954 and resolve the remaining, non-native-stylesheet-related issues there.

**Comment by rafaelgallani** [comment]
Sorry for taking so long to respond.
This approach looks nice since the linting errors are not displayed in `.native.scss` files.
When creating https://github.com/WordPress/gutenberg/pull/28988 I thought providing a way of fixing the linter errors would be good, but this approach seems better. Nice work 😸.

**Review by gziolo — APPROVED** [review]
Let's merge this PR into the active branch from @rafaelgalani and continue there (we still need to fix some violations for the web. Nice work @dcalhoun 👍🏻

**Pull request merged**
