### PR TITLE
Remove em tag from "Lists" in Demo post content

### PR DESCRIPTION
**Pull request by dixitadusara**
As per my suggestion, em tag not suitable for  "Lists" word.

### CODE REVIEW

**Comment by dixitadusara** [comment]
@jasmussen

Please review this PR and let me know why "Lists" word is different from the other words in The Inserter Tool.

**Comment by jasmussen** [comment]
@mtias, any thoughts on this one? I've no strong opinion.

**Comment by mtias** [comment]
It was to showcase inline formatting on lists and to make sure it remains working correctly.

**Comment by dixitadusara** [comment]
Ok, i got it.

**Comment by iseulde** [comment]
Let's close then, if it's there intentionally.

**Pull request closed without merging**
