### PR TITLE
Fix MarginVisualizer and PaddingVisualizer

### PR DESCRIPTION
**Pull request by noisysocks**
## What, why, how?

Fixes two bugs with `MarginVisualizer` and `PaddingVisualizer`. These are the overlays that appear when you hover over the Margin or Padding controls in a block's settings.

### 1. The `MarginVisualizer` doesn't appear at all.

This one's easy to fix. [This line](https://github.com/WordPress/gutenberg/blob/45c03ac3cc9fba28ece589378dabf8bfcdaef2d2/packages/block-editor/src/hooks/margin.js#L23) needs to use the `value` prop instead of `attributes`. It looks like it was missed during a recent refactor: https://github.com/WordPress/gutenberg/pull/56783.

### 2. Both `MarginVisualizer` and `PaddingVisualizer` show the **previous** margin and padding value.

The easiest way to see this bug is to increment/decrement the margin or padding slider one by one using the keyboard arrow keys. You'll note that the visualiser displays the padding of the previous value instead of the current value.

Video of bug in `trunk`:

https://github.com/WordPress/gutenberg/assets/612155/42df2939-0153-44b0-b36f-4ae1577ed82a

This happens because the visualiser overlay uses the `margin` and `padding` value that comes back from `getComputedStyle` which is not updated until right before the browser paints. 

`MarginVisualizer` and `PaddingVisualizer` call `getComputedStyle` in a `useEffect` when `margin` or `padding` changes. React does not guarantee that `useEffect` will be called after the browser paints and, in fact, `useEffect` can be called _before_ a paint when React is handling a user event (e.g. a click) or if a `useLayoutEffect` in the component tree updates state (e.g. calls `setState`). See https://github.com/facebook/react/issues/20863#issuecomment-976582680.

~To fix `PaddingVisualizer` we can use a `ResizeObserver` with `{ box: 'border-box' }` since this will fire when the padding changes.~ **edit:** This doesn't work, see @talldan's comment below, so we have to use the rAF approach described below for both padding and margin.

To fix `MarginVisualizer` is more hacky. To my knowledge there's no API like `ResizeObserver` that we can use that will trigger when the computed margin changes. Instead I've used a `useLayoutEffect` with two calls to rAF to ensure that we call `getComputedStyle` after the first paint but before the second paint. ([This video](https://www.youtube.com/watch?v=cCOL7MC4Pl0) is great if you're like me and need a refresher on how the event loop works.)

Video of this branch:

https://github.com/WordPress/gutenberg/assets/612155/06d5ea59-2f7b-46e6-a06e-f2cd67140f18

## Testing Instructions

Insert a block and tweak its margin and padding in the block settings. The visualiser should appear on canvas and accurately illustrate the block's margin and padding.

### CODE REVIEW

**Comment by talldan** [comment]
Thanks for the PR! Great PR description. These components always seem to be going wrong in one way or another.

I tested the PR, there are some cases where it's not quite working for me. Probably easiest to show in a video:

https://github.com/WordPress/gutenberg/assets/677833/692ad0d4-4ecb-4bb4-97f0-1ba3eed14e1e

Top/Bottom padding does seem to work well. Left/Right padding didn't seem to update for some steps, and also seemed to have outdated values (not sure why as it's the same code as top/bottom padding, but see when I drag back to zero). Margin seems to still have an issue with outdated values.

Here I'm adjusting the size of the 'Team Member' pattern as it's what I had open. Not sure if there's something specific to that pattern that causes this issue. It would be interesting to see if you can also reproduce it or if it's just me!

**Comment by noisysocks** [comment]
Aha, looks like you found a perfect example of a block that doesn't change size if the padding changes. Good catch. Looks like I can't use `ResizeObserver` for padding either 😀

**Comment by noisysocks** [comment]
OK I've updated this to use the rAF approach for both. Since `MarginVisualizer` and `PaddingVisualizer` are now near-identical I DRYed them up using an abstract `SpacingVisualizer`.

**Comment by ramonjd** [comment]
Awesome refactor. Things are working as described for me. The visualizer is updating according the custom or step slider value. 🍺 

https://github.com/WordPress/gutenberg/assets/6458278/61b0da16-0938-4b7f-86a1-cd2daa01121a


Not related to this PR, as it's on trunk as well, but I'm just wondering if the custom slide controller should behave similarly. It doesn't update the visualizer. Or if it's even possible?


https://github.com/WordPress/gutenberg/assets/6458278/885234c6-d478-4e00-b010-72de94ae0f28

**Review by ramonjd — APPROVED** [review]
I consider this to be a good change. Works as described. Neat and tidy, like my desk isn't.

Thank you!

Consider my last [comment](https://github.com/WordPress/gutenberg/pull/59227#issuecomment-1963376057) to be an observation and note for possible investigation.

**Comment by noisysocks** [comment]
> Not related to this PR, as it's on trunk as well, but I'm just wondering if the custom slide controller should behave similarly. It doesn't update the visualizer. Or if it's even possible?

This line implies to me that it's _supposed_ to do that. Must be bug. One thing at a time though 😀

https://github.com/WordPress/gutenberg/blob/8f61b9ba5e1e898626a6b94f52411222e3c2f463/packages/block-editor/src/components/global-styles/dimensions-panel.js#L546

**Pull request merged**
