### PR TITLE
[RNMobile] Native mobile release v1.17.0

### PR DESCRIPTION
**Pull request by hypest**
## Description
This PR tracks the release v1.17.0 of the native mobile block editor.

### Native Mobile Changes:

* Use URL in clipboard, if available, to create a new link (#18279) 
* Fix Rich-Text setSelection call on Android when BR tags at the end of content (#18138)
* Block Merge: guard for undefined attribute definition (#17937)
* RangeControl markup (#18036)
* Show new block indicator in default appender too (#18289)
* Remove custom paragraph options for media-text (#18284)
* Code block: remove escaping from native file (#18369)
* Instruct haste/jest to look for modules in RN/Libraries/Utilities too (#18378)
* Block title in unsupported block (#18268)
* Include PR template check for .native.js refactorings (#15468)
* Media & Text alignment options (#18300)
* Activate preformatted block in the RN app #17906
* Simplify bridge requestMediaPick methods #18303
* Fix paste in post title #18479
* Content alignment options in paragraph block #18433
* Fullscreen Image preview on Android #18493
* Separate options for capturing photo and video #18505

## How has this been tested?
Using gutenberg-mobile side PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1566

## Types of changes
No new changes, everything was introduced in separate PRs that have been merged to master.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by hypest** [comment]
To create a6450c6, I've merged `rnmobile/releases` (hash 705d91151) into `rnmobile/release-v1.17.0` and resolved the conflicts by accepting everything from `rnmobile/release-v1.17.0` which reflects the latest from master anyway.

**Review by mchowning — APPROVED** [review]
Tested via WPAndroid and WPiOS and everything looks good.

**Comment by mchowning** [comment]
Because it is not possible to rebase this branch onto `rnmobile/releases` cleanly and we wanted to avoid squashing the entire release branch into a single commit, I have just tagged the head of this branch for the gutenberg-mobile 1.17 release. We still need to figure out how we want to get these changes back into `master`.

**Comment by Tug** [comment]
I'm not familiar with `rnmobile/releases`, I guess it's a special branch which targets the latest release for `gutenberg-mobile`, I would have thought we would be using a tag for each release instead.
Asking because I feel this PR doesn't really need review, we're basically just updating a branch no?

**Comment by mchowning** [comment]
Hey @Tug ! `rnmobile/releases` is an attempt to create some kind of ongoing latest-released-code along the lines of a git-flow `master` branch in the gutenberg repo. It's very much a wip, and is not really working out so far fwiw. I have [a separate PR](https://github.com/WordPress/gutenberg/pull/18588) for bringing the release changes back into the gutenberg `master` branch.

**Comment by hypest** [comment]
This PR is no longer relevant, closing.

**Pull request closed without merging**
