### PR TITLE
Interface: prevent sidebar layout shift with explicit scroll area

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This has been annoying me for a while.

|Before|After|
|-|-|
|layout-shift|layout-shift-after|

## How has this been tested?

Open the inspector and switch between selecting the heading and paragraph for example.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by stokesman** [comment]
I'm pretty sure this used to not be an issue but haven't tracked down what brought on the change. There's another issue #31165 (Firefox and Safari) that the change in this PR could be said to resolve but not in the ideal way. That is, it resolves the horizontal overflow but it also constantly renders the horizontal scroll track. Here's a demo in Firefox:

https://user-images.githubusercontent.com/9000376/118373232-98398780-b56a-11eb-832f-0484036a8057.mp4

**Comment by ellatrix** [comment]
Hm, right, we should set only `overflow-y`.

**Comment by ellatrix** [comment]
> That is, it resolves the horizontal overflow but it also constantly renders the horizontal scroll track.

@stokesman Fixed the issue now.

**Comment by stokesman** [comment]
👍  that does it. I tested in Firefox and Safari. I think it'd be fine to link #31165 as this does incidentally resolve it.

**Comment by jasmussen** [comment]
Before:

before

After:

after

I'm conflicted. On the one hand I love that it removes the shift. On the other hand, that empty scrollbar is a bit annoying, especially for block inspectors which we can hopefully compress and compact through #27331 so that you won't need to scroll most of the time. 

@stokesman you say you remember this not being an issue — now you mention it I feel the same. Can you recall how it works? Was there reserved space for the scrollbar to take up? I _think_ I remember the sidebar shifting inwards, which if that was the case then I think I like this one better as it doesn't cause a layout shift.

It'd be nice to look up how it used to work. But otherwise, I lean towards us landing this, if nothing else then as an interim fix on the way to better things.

**Comment by stokesman** [comment]
>that empty scrollbar is a bit annoying

The silver lining is that even layout shift within the sidebar is eliminated. Also the gutter is not always present as touch-enabled devices (including touchy mice like apple makes) employ an overlaid scrollbar. If we really wanted there's also `overflow: overlay` (and someday maybe scrollbar-gutter) that could force the same in some browsers but not worth it IMO.

>Can you recall how it works? Was there reserved space for the scrollbar to take up?

Last October when I worked on #26255, I made this screen cap:

So space was not reserved for the sidebar scrollbar and the sidebar also did not shift leftward. I'm still not sure what caused the change but haven't put in much effort to figuring that out. I did have a simple alternative to the changes in this PR that we could test, but not sure it's better (though it avoids the empty scrollbar).

**Comment by jasmussen** [comment]
Great point.

This seems worth it. I think we should try it.

**Comment by ellatrix** [comment]
I think we should do it. Personally I find it pretty annoying :)

**Comment by amir2mi** [comment]
Hi @jasmussen, instead of that fixed space for the scrollbar that is possible with [`scrollbar-gutter`](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property)  why don't have a custom scrollbar over content?
before | after (over content) |after with  [`scrollbar-gutter`](https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property)
----|----|----
before_gif|after_gif|after-with-gutter


Like Slack:
slack

**Comment by jasmussen** [comment]
Hello Amir, thank you for the suggestion.

I think you may actually be on to something. If we can get a CSS/custom scrollbar to work consistently across the browsers we support, it might actually be the best solution. We'll want to move a little carefully because it technically re-skins a very common operating system control. However the pros might outweight he cons, as it allows us to ensure good contrast with the control, it allows us to force the scrollbar visibility for people who prefer reduced motion, and it solves the layout shift problem. 

It might be worth just prototyping in a PR to see how it feels — we might find it appropriate some contexts, like the inspector sidebar, the List View, for popover menus, for when the block toolbar needs to scroll horizontally, or for the site editor navigation sidebar.

**Comment by ellatrix** [comment]
Seems no one cares here, so let's close.

**Pull request closed without merging**
