### PR TITLE
Update clipboard dependency to at least 2.0.1

### PR DESCRIPTION
**Pull request by blowery**
This upgrades the clipboard dependency.

This does not yet update the package-lock.json in the root of the repo; it's unclear to me how that's supposed to happen with the lerna setup.

## Description
This upgrades the clipboard dependency to at least 2.0.1, which resolves a possible conflict with the browser global Clipboard.

See https://github.com/zenorocha/clipboard.js/releases for release notes

## How has this been tested?
* Publish a new post
* Use the Copy Link button in the post publish panel to copy the link to the clipboard

## Types of changes
Dependency update

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by talldan** [comment]
Looks like CI is failing, and when testing locally I'm seeing `UNMET DEPENDENCY clipboard@2.0.1`. Seems to be an issue with the package-lock. Could be related to the version of NPM you're running @blowery.

When I tried removing the package-lock and re-installing, this is the diff I got:
```diff
diff --git a/package-lock.json b/package-lock.json
index ddda05ddf..c5f98d602 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -2146,17 +2146,6 @@
 				"react-dates": "^17.1.1",
 				"rememo": "^3.0.0",
 				"uuid": "^3.1.0"
-			},
-			"dependencies": {
-				"clipboard": {
-					"version": "2.0.1",
-					"bundled": true,
-					"requires": {
-						"good-listener": "^1.2.2",
-						"select": "^1.1.2",
-						"tiny-emitter": "^2.0.0"
-					}
-				}
 			}
 		},
 		"@wordpress/compose": {
@@ -5124,6 +5113,16 @@
 			"integrity": "sha1-/xnt6Kml5XkyQUewwR8PvLq+1jk=",
 			"dev": true
 		},
+		"clipboard": {
+			"version": "2.0.1",
+			"resolved": "https://registry.npmjs.org/clipboard/-/clipboard-2.0.1.tgz",
+			"integrity": "sha512-7yhQBmtN+uYZmfRjjVjKa0dZdWuabzpSKGtyQZN+9C8xlC788SSJjOHWh7tzurfwTqTD5UDYAhIv5fRJg3sHjQ==",
+			"requires": {
+				"good-listener": "^1.2.2",
+				"select": "^1.1.2",
+				"tiny-emitter": "^2.0.0"
+			}
+		},
 		"cliui": {
 			"version": "4.1.0",
 			"resolved": "https://registry.npmjs.org/cliui/-/cliui-4.1.0.tgz",

```
and things worked fine after that.

**Comment by talldan** [comment]
If you want to cherry-pick the commit with those changes onto your branch, I've pushed it - 44ac27d55874460d41c2faa7ca9344657e97f70f

**Comment by gziolo** [comment]
Thanks @talldan, I applied your package-lock.json, testing it locally as I see some additional changes in `fsevents` package.

**Comment by gziolo** [comment]
Huh, now it's exactly the same as the diff Dan shared 🎉 

Merging whenever Travis is happy :)

**Review by gziolo — APPROVED** [review]

**Comment by gziolo** [comment]
I did sanity check, you can still use the copy feature in the More Menu 👍

**Comment by blowery** [comment]
Thanks @talldan! I'm running 6.4.1 here too. Out of curiosity, what OS did you run that on? Did you run that command inside a docker container or on the host?

**Comment by talldan** [comment]
Hey @blowery - using Mac OS X High Sierra, ran the command on the host machine.

Very strange that it produced different output with the same version. Eh, NPM 🤷‍♂️ .

**Comment by talldan** [comment]
Hey @blowery - using Mac OS X High Sierra, ran the command on the host machine.

Very strange that it produced different output with the same version. Eh, NPM 🤷‍♂️ .

**Pull request merged**
