### PR TITLE
Bump React to 16.3.2 to fix IE11 warning

### PR DESCRIPTION
**Pull request by brandonpayton**
## Description

This PR bumps our React version to 16.3.2 to address the following warning seen in IE11:
screen shot 2018-05-08 at 6 37 12 am

React 16.3.2 uses the `Map( iterable )` constructor to create a map of valid Fragment props. This is a
problem in IE11 because IE11 supports a form of Map but not the constructor taking the iterable. The result is that the map is empty and React warns that `children` is not a valid Fragment prop. React 16.3.1 and later contain a fix for this, and I'm bumping to React 16.3.2 as the latest point release.

The React issue:
https://github.com/facebook/react/issues/12500

The fix:
https://github.com/facebook/react/pull/12504

## How has this been tested?

* Ran unit tests.
* Ran e2e tests.
* Loaded Gutenberg in IE11 and verified the warning is gone.
* Manually worked with Gutenberg in Chrome as a quick check that nothing major appears broken with the version bump.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
May bring a nice performance boost as well: https://github.com/facebook/react/pull/12510 Curious if this is where the noticeable regression in development lately had started.

Confirmed appears to work well in IE11 and Chrome.

Travis seems grumpy today, probably a false positive (failing to install PHP?). 

Do we need to update URLs in `class-vendor-script-filename-test.php` as well?

Otherwise LGTM 👍

**Comment by gziolo** [comment]
Travis complains about PHP 5.2 targeted build, but everything looks good. Moving on regardless.

**Comment by gziolo** [comment]
> Do we need to update URLs in class-vendor-script-filename-test.php as well?

Done wite e1990eb.

**Comment by brandonpayton** [comment]
Thanks for the review, @aduth, and for the update to `class-vendor-script-filename-test.php`, @gziolo!

**Pull request merged**
