### PR TITLE
Fix Deleting multiselected blocks

### LINKED ISSUE #2101: Multi-select: backspace or delete, should delete selection
Use case: you create 10 paragraphs. You are fed up, and want it gone. You hit ⌘ A to select them all, and press backspace. 

Current behavior: only the last block selected gets deleted. Desired behavior: all selected blocks get deleted.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #2101 

The code handling this was there but not being triggered properly.

**Testing instructions**

 - Select all blocks (ctrl+A)
 - Hit delete or backspace: the blocks should be deleted.

### CODE REVIEW

**Comment by jasmussen** [comment]
Yaaaay! Love it. 👍 👍

**Comment by notnownikki** [comment]
I was able to break it in a weird way...

I can select the blocks in such a way that I have blocks selected, and I'm editing a single block at the same time. Then, if I press backspace, I can end up merging two blocks instead of deleting them.

multiselectproblem

**Comment by youknowriad** [comment]
@notnownikki Not sure how to reproduce this bug (which browser is this?). 

Anyway, the fact that we're storing the selection and the multi-selection in two different reducer is not a good thing and could lead to this kind of bugs, we should make sure to improve these reducers separately (cc @iseulde )

**Comment by iseulde** [comment]
> we should make sure to improve these reducers separately

Are you saying we should keep them separate or merge them? I'll have a look at this this afternoon!

**Comment by youknowriad** [comment]
@iseulde I'm saying we should merge them

**Comment by notnownikki** [comment]
@youknowriad @iseulde this is how I reproduced it. It's probably a "nikkibug" - that is, something I trigger every time, and no one else does _until_ I point it out... :smile: 

Using chrome.

1) Create three text blocks, with the text "top", "middle", and "bottom".
2) In the bottom block, place the text cursor at the end of the word "bottom".
3) Drag to the beginning of the word "bottom" to select it.
4) Release the mouse button.
5) Move the mouse cursor to the end of the word "bottom".
6) Drag straight upward to select all three blocks.
7) Drag the mouse cursor to the beginning of the word "top" in the top block.
8) Drag the mouse cursor straight down to the bottom block so it is at the beginning of the word "bottom". 
 You should see the word "bottom" is no longer selected, and the text cursor is at the start of the word "bottom".
9) Continue dragging upward to select all three blocks. You should see the text cursor is still active in the bottom block, but all three blocks are selected.
10) Press backspace, and the bottom block will merge into the block above it and lose focus.

weird selection bug

**Comment by notnownikki** [comment]
Further info: this doesn't happen in Chrome 60 or Firefox, but does in Chrome 59 (exact version number: 59.0.3071.109)

**Comment by youknowriad** [comment]
Ok, So I think we should merge this and consolidate the selections reducer separetely.

**Review by ellatrix — APPROVED** [review]
Works great! Awesome!

**Comment by iseulde** [comment]
@notnownikki Could you open a separate issue the bug then? :)

**Pull request merged**
