### PR TITLE
Move CI back to latest WordPress version and bump minimum version to 4.9.8

### LINKED ISSUE #8445: Gutenberg_REST_API_Test fails with WP 4.9.8
**Describe the bug**

When we run the unit tests with WordPress 4.9.8, they fail. They pass with 4.9.7.

The failing test is:

```
1) Gutenberg_REST_API_Test::test_visibility_field_for_non_admin_roles
Failed asserting that true is false.
/home/travis/build/WordPress/gutenberg/phpunit/class-gutenberg-rest-api-test.php:95
```

Our CI has been broken since the 4.9.8 release because all the tests use the latest WP version, so we've pinning to 4.9.7 to unblock people and this can get looked at concurrently.

### PR DESCRIPTION
**Pull request by notnownikki**
## Description

Fix the tests that started failing in WP4.9.8

cc @aduth @BE-Webdesign @danielbachhuber - your names appeared next to issues and code around the failing test :smile: 

If any of you know what's going on with that code, your insight is appreciated!

To fix: https://github.com/WordPress/gutenberg/issues/8445

### CODE REVIEW

**Comment by danielbachhuber** [comment]
```
/**
 * See https://github.com/WordPress/gutenberg/issues/2545
 *
 * Until that is resolved authors will not be able to set taxonomies.
 * This should definitely be resolved though.
 */
wp_set_current_user( $this->author );

$response = rest_do_request( $request );

$result = $response->get_data();

$this->assertFalse( isset( $result['visibility'] ) );
```
I think this can either be changed to `$this->assertTrue()` or removed. The mentioned issue is fixed.

**Comment by notnownikki** [comment]
I've rebased this and reinstated the cli `core update` when we are testing against the latest version. We can now pin to specific WP versions, or use the latest official release, or nightly builds, by specifying the versions in `docker-compose.yml` and `.travis.yml`.

**Comment by aduth** [comment]
Pushing up what I had with removing the temporary compatibility in af4e42e . I'm seeing failures locally which I expect are maybe legitimate and will show through to Travis as well. Not entirely clear yet why they're failing, as the expected behaviors work for me in practice (via REST API console plugin through the admin UI).

**Comment by aduth** [comment]
Travis appears to be happy with these changes. In which case, I suppose this is ready for a proper review.

**Comment by danielbachhuber** [comment]
This will require bumping Gutenberg's minimum supported WP version to 4.9.8

**Comment by aduth** [comment]
@danielbachhuber bumped in 1fa587a

**Comment by notnownikki** [comment]
We're getting hit by those e2e intermittent failures again. I'll try running the job tomorrow morning UK time when Travis isn't as busy.

Also, if we can get some eyes on https://github.com/WordPress/gutenberg/pull/8301 and get it merged, then these intermittent e2e failures should go away.

**Review by danielbachhuber — APPROVED** [review]

**Pull request merged**
