### PR TITLE
Fix label of columns inspector panel

### PR DESCRIPTION
**Pull request by megane9988**
## What?

#56461

## Why?
Increase copy consistency.

## How?

I also changed the copy for a native app.
How do you think about it?

## Testing Instructions

1. Go to the edit post page.
2. Add column block.
3. Check the panel.

## Screenshots or screencast 
image

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM 👍

@fluiddot @geriux Could you please confirm if this change also makes sense for the mobile app?

**Comment by fluiddot** [comment]
> LGTM 👍
> 
> @fluiddot @geriux Could you please confirm if this change also makes sense for the mobile app?

Yeah, I checked the app and the change looks good. Thanks for the call out 🙇 !

| Before | After |
|--------|--------|
|  |  |

**Comment by t-hamano** [comment]
Thanks for the review, @fluiddot!

**Comment by megane9988** [comment]
@t-hamano  @fluiddot Thanks for your fantastic reviews!

**Comment by richtabor** [comment]
Very nice.

**Pull request merged**
