### PR TITLE
Remove right navigation sidebar from edit-site.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Follow up to https://github.com/WordPress/gutenberg/pull/46436.

Removes the right navigation sidebar as now we have that sidebar on browse mode.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you! I guess this mainly needs a technical look.

**Comment by youknowriad** [comment]
I guess since the navigation in the site editor sidebar on the left is behind a feature flag, we should still keep the other one if the feature flag is disabled?

**Comment by youknowriad** [comment]
Do you know when the feature flag is supposed to be removed?

**Comment by jasmussen** [comment]
Was about to ask if the feature flag can instead hide the navigation in the site editor. But I guess the question then becomes: do we actually need that feature flag anymore? It doesn't seem like it. CC: @getdave as I think you may have worked on the inspector interface.

**Comment by jasmussen** [comment]
We need to figure out the save button challenge before we remove the one on the right:

nav

I think we can probably have a good idea for how to do that very soon, as we're working on mockups for it.

**Comment by getdave** [comment]
The experiment was only there as the feature was still experimental. It looks like Jorge is shepherding this out of experimental which seems ok to me.

My understanding is that this is _not_ using the same code as the Nav _block_ "offcanvas" list view which is good as that feature is still experimental at this time.

**Comment by youknowriad** [comment]
I think we can probably close this PR right now as the flag has been removed separately.

**Pull request closed without merging**
