### PR TITLE
Adds link to post on the developer blog to the deprecation page

### PR DESCRIPTION
**Pull request by mburridge**
## What?

This adds a paragraph to the top of the page on Deprecation linking to the [recently published tutorial on deprecation](https://developer.wordpress.org/news/2023/03/block-deprecation-a-tutorial/) in the Developer Blog.

## Why?

The content on the Deprecation page is dense and can be opaque and requires close reading. The tutorial in the Developer Blog provides a shallower learning curve and guides the reader through a series of simple examples of block deprecation. Linking to the tutorial from this page gives the user the option to go to that tutorial should they want to follow an easier learning path.

## How?

I wrote a paragraph of text.

## Testing Instructions

n/a it's just documentation, though you could test that the links go to the desired destination.

### CODE REVIEW

**Comment by bph** [comment]
This is an excellent idea and example of cross-linking we need!  Thank you for thinking of it, @mburridge 

"Those seeking a more gentle introduction may find the" 
In this case, less judgmental would be better. 

Try this: 
"For an introduction, find the [tutorial on the basics of Block Deprecation](https://developer.wordpress.org/news/2023/03/block-deprecation-a-tutorial/) on the WordPress Developer Blog.  

You wouldn't need the  disclaimer regarding substitute etc. You have the clarifying sentence on top, and with adding the word "basics" to the tutorial, takes care of it in conjunction with the word "introduction" :-)

**Comment by mburridge** [comment]
Thanks for that suggestion @bph, I've updated the text taking your comments into account. What do you think?

**Review by bph — APPROVED** [review]
LGTM

**Review by justintadlock — APPROVED** [review]
The changes look good to me.

**Pull request merged**
