### PR TITLE
Set image size in percentages

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

This PR attempts to fix the issue where the width of the editor is different from the front-end, in which case the image might be a lot bigger or smaller than expected. This is especially an issue on small screen devices.

## How Has This Been Tested?
Resize an image and verify that the size is set as a percentage of the content width.

### CODE REVIEW

**Comment by youknowriad** [comment]
My initial reaction is that the image should be the size I set when I resize it, if we use percentage, it depends on the theme :). I guess that's the whole point of your PR but I think the current behavior is the right one :). The theme could provide editor styles to match its width?

I'll defer to others though, I'd be fine with both.

Noting that this breaks old images and we might want to provide a "deprecated" version if we want this in.

**Comment by iseulde** [comment]
I can understand both. Maybe in some cases you need to have it exactly set in pixels, though it could be argued that you could make the image exactly that size with image editing tools. In other cases, I don't feel like setting the size in pixels makes the content very portable across themes and other places where the content is displayed.

**Comment by iseulde** [comment]
> Noting that this breaks old images and we might want to provide a "deprecated" version if we want this in.

@youknowriad Is there any recommended way to do this? I guess we might want to document this too for block authors.

**Comment by youknowriad** [comment]
@iseulde yes, see the "deprecated" property in the quote block for example. Basically, you just put the old `save`, `attributes` and `support` there. It's not finalized yet #3673  but yes we'll have to document this.

**Comment by iseulde** [comment]
Closing this one again for now. May still be interesting, but the main image size issue was fixed.

**Pull request closed without merging**
