### PR TITLE
Fix duotone padding crash

### LINKED ISSUE #31766: Cover Block: Duotone feature crashes editor when attempting to edit unlinked padding.
## Description
I wanted to test the new padding feature on the cover block, then i uploaded an image and added the duotone overlay but  then I wanted to edit it again and the editor crashed. 

## Step-by-step reproduction instructions
1. Add a post
2. Add a Cover block
3. Add a background image
4. add padding to the cover block
5. unlink the sides 
6. set bottom to 45 and top to 25
8. select duotone. 
9. try to edit the padding again. 

A better video. The crash happens when editing padding after duotone is enabled. 
https://recordit.co/VhT8aaWaTt

Error message: 
```
- TypeError: e.forEach is not a function
    - at Vc (http://fse-testing.local/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=8e360919cbf98891d83938131507d2b8:10:8971)
    - at http://fse-testing.local/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=8e360919cbf98891d83938131507d2b8:10:11210
    - at we (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    - at He (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:97:464)
    - at zj (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:228:406)
    - at Th (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    - at tj (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    - at Te (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    - at http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    - at unstable_runWithPriority (http://fse-testing.local/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)

```

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: 10.6
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1-Blocks

## Device information
- Device: Desktop
- Operating system: OS 10.15.7
- Browser: Chrome 90.0.4430.93

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Fixes #31766 

Some of the other block supports filter out falsy values from the entirety of the `style` object. However, lodash's `pickBy` function will convert an Array into an Object, causing the `color.forEach` to be `undefined` when duotone is processing the colors.

This change makes sure that Arrays are not affected by the filtering which fixes the issue.

## How has this been tested?

1. Add cover block
2. Set image background
3. Apply any duotone filter
4. Adjust the padding

## Screenshots 

fix-duotone-padding

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Tested and works as expected.

**Comment by bph** [comment]
@ajlende _I updated my comment_. It all works now. I missed a step when setting up my PR testing suite. 
Sorry about the false positive. 
And thank you for fixing this so fast!

**Review by bph — APPROVED** [review]
All good. Thank you.

**Comment by carolinan** [comment]
The PR works well for me.

**Review by carolinan — APPROVED** [review]

**Pull request merged**
