### PR TITLE
I18n: Make block preview title translatable

### PR DESCRIPTION
**Pull request by Soean**
## Description
This PR adds i18n for the `Preview` title of the block preview component.

### CODE REVIEW

**Comment by aduth** [comment]
Testing instructions: This label in Inserter > Shared:

Preview

**Review by aduth — APPROVED** [review]
👍

**Comment by aduth** [comment]
Actually, while I just merged, one potential issue here is disambiguation of the word "Preview" . Is it a noun or a verb? Good for `_x` context.

https://codex.wordpress.org/I18n_for_WordPress_Developers#Disambiguation_by_context

**Comment by Soean** [comment]
@aduth Thanks, maybe a context is better for some languages. In the preview component it is a noun on the button a verb. In german we have no verb for preview. So we use the noun "Vorschau" for both. I will open another PR.

**Comment by aduth** [comment]
My understanding is context is good to provide anytime there's the potential for ambiguity (here, on part of speech).

In any case, here's an actual example:

https://translate.google.com/#en/es/preview

>noun
>  | el | avance | advance, progress, development, preview, lead, trailer
>  | el | preestreno | preview
>  | la | vista anticipada | preview
>verb
>  | preestrenar | preview
>  | presentar a los críticos | preview, press view
>  | ver antes que los demás | preview, press view

**Pull request merged**
