### PR TITLE
Mobile Release v1.43.0

### PR DESCRIPTION
**Pull request by guarani**
## Description
Release 1.43.0 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2874

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by cameronvoell — APPROVED** [review]
Approved via https://github.com/wordpress-mobile/gutenberg-mobile/pull/2874#pullrequestreview-550700598

**Comment by guarani** [comment]
The "End-to-End Tests / Admin - 3 (pull_request)" test is failing here, but it's also failing on `master`: https://github.com/WordPress/gutenberg/actions?query=workflow%3A%22End-to-End+Tests%22+branch%3Amaster
@cameronvoell, would you agree we can merge this?

**Comment by jd-alexander** [comment]
@guarani these tests are flaky at times. What I normally do is re-run them so I can get all green checks and then I merge. I just did a re-run to see if it passes!

**Comment by guarani** [comment]
Thanks for the re-run @jd-alexander, it looks like these are very flaky indeed 😅 
Do you agree @jd-alexander we can try to merge this with the failing test?

**Comment by guarani** [comment]
> Thanks for the re-run @jd-alexander, it looks like these are very flaky indeed 😅
> Do you agree @jd-alexander we can try to merge this with the failing test?

It looks like @jd-alexander is away. @cameronvoell, would you be able to give a second opinion on whether this can be merged despite the failing test?

**Comment by cameronvoell** [comment]
@guarani It's very rare that we have to merge with failing tests in the gutenberg repo. Usually if there are CI failures on `master` they will be actively worked on. Looking at the recent commits to gutenberg master, it seems that this one is likely already solved. Can you merge in latest from master and re-check?

**Comment by cameronvoell** [comment]
Looks like this is passing after @guarani merged in latest master 🎉  I'll go ahead and merge.

**Comment by guarani** [comment]
> Looking at the recent commits to gutenberg master, it seems that this one is likely already solved. Can you merge in latest from master and re-check?

Thanks for noticing! I'd looked on Thursday last week but had forgotten to check again to see if this had been resolved on `master`. 

> Looks like this is passing after @guarani merged in latest master 🎉 I'll go ahead and merge.

Awesome! I was second time lucky there (first time had resulted in another albeit different failing test).
Thanks @cameronvoell for merging that.

**Pull request merged**
