### PR TITLE
Make the list of widgets excluded from the legacy widget block extensible via a filter

### PR DESCRIPTION
**Pull request by adamziel**
## Description
This PR adds the `widgets_to_exclude_from_legacy_widget_block` filter to enable plugins and themes to add/remove their own widgets from the legacy widget block:

Zrzut ekranu 2020-07-29 o 16 29 47

It also removes a misleading @TODO comment from lib/widgets.php. The feature described in that comment can be achieved by using the transform API that already exists:

```js
{
	transforms: {
		from: [
			{
				type: 'block',
				blocks: [ 'core/legacy-widget' ],
				isMatch: ( { widgetClass } ) => {
					return widgetClass === 'WP_Widget_Custom_HTML';
				},
				transform: ( {} ) => {
					return createBlock( 'core/navigation', {}, [] );
				},
			},
		],
	},
}
```

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Why can't blocks add the transforms themselves? A block can declare a transformation from another block. Is the problem a lack of standard way to determine whether the Legacy Widget block's current widget matches a given block? Perhaps something similar to the `eligible` property in deprecated blocks could be added to transforms?

**Comment by noisysocks** [comment]
> Why can't blocks add the transforms themselves? A block can declare a transformation from another block. Is the problem a lack of standard way to determine whether the Legacy Widget block's current widget matches a given block? Perhaps something similar to the `eligible` property in deprecated blocks could be added to transforms?

That's right. Core and third party blocks can specify a `from` transformation which I think should make this hook unnecessary. Transformations also support an `isMatch` function which can do more advanced conditional logic.

https://developer.wordpress.org/block-editor/developers/block-api/block-transforms/#block

Does that cover all the use cases @adamziel?

**Comment by draganescu** [comment]
@noisysocks with that from transformation added can we map which blocks to which widget it replaces so that the legacy widget does list it in its option? [This](https://github.com/WordPress/gutenberg/blob/master/lib/widgets.php#L109) was suggested in the code of our widgets modifications to support the legacy widget block.

**Comment by adamziel** [comment]
🤦  of course you are right @ZebulanStanphill, this is all that's needed to declare that, let's say', a custom HTML widget may be transformed into a navigation block:

```
	transforms: {
		from: [
			{
				type: 'block',
				blocks: [ 'core/legacy-widget' ],
				isMatch: ( { widgetClass } ) => {
					return widgetClass === 'WP_Widget_Custom_HTML';
				},
				transform: ( {} ) => {
					return createBlock( 'core/navigation', {}, [] );
				},
			},
		],
	},
```

It seems like this PR could just remove [this comment](https://github.com/WordPress/gutenberg/blob/master/lib/widgets.php#L109) then. @noisysocks do you happen to know why was the `isHidden` flag introduced anyway? My thinking is that it would make sense to just always show the "Change into a different legacy widget" button, why exclude core widgets?

**Comment by noisysocks** [comment]
I think the idea is that:

1. We want to support users adding the Legacy Widget block to their posts or widget areas so that they can make use of the wide ecosystem of existing third party widgets that are out there.
2. We don't want users adding the Legacy Widget block to their post to use a Core widget that has an equivalent block, e.g. Search.

So therefore we hide the Core widgets from that dropdown menu.

It makes sense that we should let third parties disable their widgets from appearing in the dropdown, too.

**Comment by draganescu** [comment]
> It makes sense that we should let third parties disable their widgets from appearing in the dropdown, too.

Yes, this. Does the transformation API aromatically achieve this goal?

**Comment by noisysocks** [comment]
> > It makes sense that we should let third parties disable their widgets from appearing in the dropdown, too.
> 
> Yes, this. Does the transformation API aromatically achieve this goal?

No it does not. We should add an `apply_filters` to `$core_widgets` so that plugins can add to this array.

**Comment by draganescu** [comment]
> > Does the transformation API aromatically achieve this goal?

> No it does not. We should add an apply_filters to $core_widgets so that plugins can add to this array.
> Also $core_widgets should probably be named something like $widgets_to_exclude_from_legacy_widget_block... but less verbose.

That is why I think this PR should _not_ be about removing a to do but instead about adding that filter to make that array extensible by third parties.

cc @adamziel

**Comment by adamziel** [comment]
@draganescu thanks for the ping, this discussion is absolutely on my radar and I will get back to it this week :-)

**Comment by adamziel** [comment]
@noisysocks @draganescu I updated the PR using the exact name proposed by @noisysocks (`widgets_to_exclude_from_legacy_widget_block`). It seems a little verbose, but it's also a great name that actually makes the code more readable. I wasn't able to come up with anything better so I'd say let's roll with it.

**Comment by ZebulanStanphill** [comment]
@noisysocks Thanks for clarifying what was supposed to be going on here. Yeah, it definitely makes sense to have a filter for plugins to hook into to prevent users from inserting their legacy widgets through the Legacy Widget block when native block equivalents are available.

**Review by noisysocks — APPROVED** [review]
The name makes me miss Objective-C with its very accurate and long method naming 😂

**Review by draganescu — COMMENTED** [review]
Yes! We can now exclude widgets that have block counterparts or we simply don't want to have them in the Legacy Widget block for some reason :) 🚢 
Later Edit: I approved a merged PR, great job me!

**Pull request merged**
