### PR TITLE
Replace isSmall prop WordPress/Gutenberg#53560

### LINKED ISSUE #53560: Button: Replace deprecated isSmall property with size="small" property
Related to #53472

The deprecated `isSmall` property is being used in the Button component and in the component that wraps the `Button` component.

I believe that the `isSmall` property should be replaced with `size="prop"` to officially deprecate it, as mentioned in [this comment](https://github.com/WordPress/gutenberg/pull/53472#issuecomment-1673643125).

button-deprecated

### PR DESCRIPTION
**Pull request by inc2734**
## What?
Replaced the isSmall property with size="small" for `DropdownMenu` components.

## Why?
https://github.com/WordPress/gutenberg/issues/53560

### CODE REVIEW

**Comment by t-hamano** [comment]
Sorry for the late reply. It appears that some of the code that this PR is trying to change has already been updated in trunk, causing a conflict. Can you resolve this conflict?

Once this PR is merged, all `isSmall` prop replacements should be complete.

Thank you!

**Comment by inc2734** [comment]
Sorry! I think I did something wrong with the operation!

**Comment by t-hamano** [comment]
If you have time to continue working on this PR, please feel free to reopen. I will be happy to review it 👍

**Review by t-hamano — APPROVED** [review]
LGTM 🚀

**Pull request merged**
