### PR TITLE
Removing redundant `currentColor` CSS value

### LINKED ISSUE #12328: Optimizing usage of `currentColor` in CSS
**Issue description**
`currentColor` is a default value for various CSS properties. So, [there is no need to set it up as `border-color` in certain cases](https://github.com/WordPress/gutenberg/pull/10658), for example.

**Expected behavior**
Not using `currentColor` value when redundant.

**Additional context**
- Gutenberg v4.5.1

### PR DESCRIPTION
**Pull request by webmandesign**
Fixes #12328

### CODE REVIEW

**Comment by jasmussen** [comment]
You're [absolutely right](https://codepen.io/joen/pen/daVewm?editors=1100), and this seems like an excellent PR. Thanks so much. Unless Kjell has objections, I think this PR just needs a rebase and then let's ship it! 👍 👍

**Comment by kjellr** [comment]
Looks good to me too! Once those conflicts are sorted out this should be ready to 🚢. Thank you!

**Comment by gziolo** [comment]
@webmandesign would you mind bringing this branch up to date with the changes applied in `master` branch? This is blocking this PR to be included in the upcoming Gutenberg 5.1 release which is planned for early next week.

**Comment by webmandesign** [comment]
Hi guys,

Thank you for feedback and sorry for delay in my answer. As I have a problem with rebase, I've decided to create a new pull request #14119 Please check there for my additional comments.

Thanks again!

**Pull request closed without merging**
