### PR TITLE
Fix e2e tests after the WordPress 5.0 upgrade

### PR DESCRIPTION
**Pull request by youknowriad**
After the WordPress docker image update, the e2e tests broke because the default theme changes which impacts the default font-sizes and the post formats support. We also don't have access to the classic editor anymore.

### CODE REVIEW

**Comment by youknowriad** [comment]
I considered installing the classic editor to test it instead of removing the test but I think it's better addressed in e2e tests in the classic editor plugin instead.

**Comment by youknowriad** [comment]
In order to make the php unit tests pass, I removed some php unit tests which were useless anyway as they were testing the Core code (which is already tested in Core) because you can't reload existing php functions and classes.

Ideally we'd do https://github.com/WordPress/gutenberg/issues/11015 separately and update the minimum version of the plugin to 5.0.

**Review by gziolo — APPROVED** [review]
All the e2e changes look good. I'm  not quite sure whether we need to keep PHP unit tests since they are also in core. I would appreciate confirmation from someone familiar with REST API changes applied to 5.0, @danielbachhuber or @kadamwhite?

**Comment by youknowriad** [comment]
I didn't want to make the decision to update the minimum required version to 5.0 in this particular PR. But yeah, I think we can safely remove most of the php code, unit tests included and update the minimum version.

The current unit tests are running Core code (because of the if class exit tests) which doesn't make a lot of sense.

**Comment by danielbachhuber** [comment]
>  I'm not quite sure whether we need to keep PHP unit tests since they are also in core. I would appreciate confirmation from someone familiar with REST API changes applied to 5.0,

Yes, this is fine. I outlined most of what can be removed in #10656

**Pull request merged**
