### PR TITLE
Working on showing the custom classname in the editor

### PR DESCRIPTION
**Pull request by cguntur**
## Description

This fix intends to fix the custom className not being added in the editor. According to this ticket - https://github.com/WordPress/gutenberg/issues/20849, the className is added to the front end but not the editor. Adding props.className to the gutenberg/packages/block-editor/src/components/block-edit/edit.js was suggested and I added it.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
Can you clarify in the PR description what this is trying to achieve?

**Comment by cguntur** [comment]
I tried testing this with the code mentioned in the related ticket (https://github.com/WordPress/gutenberg/issues/20849), but I couldn't get the class names to show up in the editor even after I added props.className in the specific file when I use editor.BlockEdit

The only way the classes show up in the editor is when I use editor.BlockListBlock.

**Comment by MageEnclave** [comment]
@cguntur @youknowriad has there been any progress on this or a different PR that covers this issue?

**Comment by fabiankaegy** [comment]
Closing this for now as per comment in the issue: https://github.com/WordPress/gutenberg/issues/20849#issuecomment-1776857666

**Pull request closed without merging**
