### PR TITLE
[RNMobile] Fix dismiss keyboard button for the post title

### PR DESCRIPTION
**Pull request by geriux**
Related [gutenberg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1321)

## Description

This fixes an iOS and Android issue with the post title when it is in focus, the option to hide the keyboard wasn't working as expected (it should dismiss the keyboard)

Right now it was only clearing the selected blocks and not the post title so I changed it to dispatch both. If the number of different elements increases another approach should be implemented so it's easy to maintain.

## How has this been tested?
- Open the demo app
- Tap on the Post title
- Tap on the "Hide keyboard option"
- It dismisses the keyboard

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by pinarol** [comment]
hi @geriux 👋 Thanks for the PR. This is working good 🎉 
But there are some lint issues needs fixing.
You can use `npm run lint` to detect those, and `npm run lint-js:fix` to make use of the automation fixing, but it might not fix everything. Travis CI should get green before we can merge.

**Comment by geriux** [comment]
Hey @pinarol ! Sorry about that! Linting issues solved =)

**Comment by pinarol** [comment]
Thanks!

**Comment by pinarol** [comment]
We created a new working branch named `rnmobile/master` to avoid [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1321#issuecomment-524283133) until it is solved. Could you please update this PR's target branch as `rnmobile/master` so that our CI tests can pass and we can merge?

**Comment by geriux** [comment]
Of course! I have a conflict after changing the base that I'll fix today =)

**Comment by geriux** [comment]
@pinarol I see there are a lot of changes when I changed the base, did you mean maybe to make the changes from `rnmobile/master` instead of what I used before? sorry for the confusion 😅

**Comment by pinarol** [comment]
Basically we should base the changes of this PR on 'rnmobile/master' so that we are leaving breaking changes outside. Feel free to do this the easiest way you prefer, you can create a new branch from 'rnmobile/master' and cherry pick this changes onto it.

**Comment by geriux** [comment]
Oh ok! I went ahead and did that, here's the new one. https://github.com/WordPress/gutenberg/pull/17260

**Pull request closed without merging**
