### PR TITLE
Add Align support to Separator block

### PR DESCRIPTION
**Pull request by jordesign**
## Description
Added support for Align controls (limited to Wide and Full) to Separator block
Addresses #25080 

## How has this been tested?
Tested in Local (by Flywheel) on Mac OSX in Chrome/Safari.

Tested with TwentyTwenty theme which renders elements as expected (with good theme support for wide end full alignment).

## Screenshots 

Screen Shot 2020-09-08 at 9 20 13 pm

## Types of changes
Change to existing core block - adding additional functionality/support

## Checklist:
- [x] My code is tested.
- [ x] My code follows the WordPress code style. 
- [x ] My code follows the accessibility standards.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@jordesign Haii! Thanks for working on this one :)

I took it for a spin locally. I think we may need `center` align there as well.

My thinking is it can serve as the "default". Just in case you update to `wide` or `full`, and you want to change it back to the original:

Screen Shot 2020-10-06 at 1 01 25 PM

I don't think we need both `align: true` and `align: [...]` 🤔 

Hope this was helpful!

**Comment by jordesign** [comment]
Thanks @ItsJonQ  - I'm amended that and have an update to the PR

**Review by ItsJonQ — APPROVED** [review]
🚀 Thanks @jordesign ! With that change, it looks good to me :)

**Comment by ItsJonQ** [comment]
@jordesign Hmm! Before I merge this. I had a question!

Do we need the `html: false` setting for any reason?

I'm not too familiar with that property. Briefly poking at the other blocks (via code search), I couldn't find many instances of `html: false`. Just wanted to double check

Thanks!

**Review by ItsJonQ — CHANGES_REQUESTED** [review]
@jordesign Haii! Just checked. I think we need to remove `"html": false`

**Comment by jordesign** [comment]
Thanks @ItsJonQ - updated now

**Review by ItsJonQ — APPROVED** [review]
@jordesign Great! Thank you for the speedy adjustments 🙏

**Comment by ItsJonQ** [comment]
The E2E tests are failing... However, I believe we're having E2E testing issues all around.
I'm 99.9999% certain the failures are **unrelated** to this PR update.

Will proceed with merging.

Thanks again @jordesign !

**Comment by ZebulanStanphill** [comment]
@ItsJonQ To reset to the default, you click the currently-selected option. Arguably, there should be an explicit "unset"/"default" option in these kind of dropdown menus, but that's something that should be addressed for all instances of this kind of menu.

**Pull request merged**
