### PR TITLE
Make navigation placeholder state visible in dark themes.

### LINKED ISSUE #29235: Navigation Block: Empty state isn't visible against dark background
## Description

The navigation block's default state isn't visible against a dark background. 

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Open the site editor or a new page/post. 
2. Add a cover block and set the background to a dark color like black. 
3. Add a navigation block.
4. Select "Start Empty" and see that the default state is almost impossible to see. 

## Expected behaviour

I expected to be able to see the default state. 

## Actual behaviour

I'm unable to see the default, empty state. 

## Screenshots or screen recording (optional)

Screenshot:

Screen Shot 2021-02-22 at 3 17 41 PM

Video: 

https://user-images.githubusercontent.com/26996883/108777432-06991b80-7521-11eb-826d-4ec770969ced.mov

## WordPress information
- WordPress version: 5.6.2
- Gutenberg version: 10.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #29235.

This makes the setup state slightly more opaque in dark themes, when selected.

## How has this been tested?

Use TT1 blocks, set the background color to black in the site editor, text to white, then insert a navigation block and start empty. Then select and unselect to see the difference.

## Screenshots 

state

## Types of changes

The setup state is meant to be purely decorative, so there isn't a contrast ratio to meet. What's important is that the plus button is visible against a dark background.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
@annezazu just flagging you for thoughts on this one.

**Comment by annezazu** [comment]
Thanks for the flag and for jumping in on this so quickly. I have to admit that when selecting the block and the placeholders become more opaque, I still find it really hard to see. I imagine for a11y purposes this won't quite meet the bar.

**Comment by jasmussen** [comment]
I don't know, the important part to see here is the plus button to add, and recent discussions around the setup state confusion to me suggests it's best to remove them entirely (0% opacity). What do you think?

**Comment by gwwar** [comment]
>I don't know, the important part to see here is the plus button to add, and recent discussions around the setup state confusion to me suggests it's best to remove them entirely (0% opacity). What do you think?

@jasmussen Did you mean remove the placeholder bars, so we only see the inserter? 

At least for me, I thought the block was broken when I first interacted with it. I associate the placeholder bars with loading requests, so only displaying the appender could work.

**Comment by gwwar** [comment]
As an aside TIL that Chrome devtools has a [color contrast info in the color picker](https://developers.google.com/web/tools/chrome-devtools/accessibility/reference#contrast). Unfortunately parts of the editor appear to confuse it.

Screen Shot 2021-03-04 at 10 12 10 AM

**Comment by jasmussen** [comment]
Yes exactly, and for the reason you mention. Not necessarily in the placeholder step entirely, though I think that needs more love, but at least for the selected state.

**Comment by gwwar** [comment]
That sounds like a good step to take!

**Comment by jasmussen** [comment]
Alright, this one ended in a pretty good place I think. Here's a light theme:

light theme

Here's a dark theme:

dark theme

**Review by gwwar — APPROVED** [review]
Good improvement @jasmussen ! I think we might want to follow up on spacing for the vertical nav, but I think changes here are good as is, since the current placeholder is a bit wonky.

https://user-images.githubusercontent.com/1270189/110537048-0bd89780-80d7-11eb-86da-113e139db509.mp4

**Comment by jasmussen** [comment]
> I think we might want to follow up on spacing for the vertical nav, but I think changes here are good as is, since the current placeholder is a bit wonky.

Excellent point. I'll definitely put that on my list. Thanks for the reviews!

**Pull request merged**
