### PR TITLE
Ensure that the autosave happens on empty posts in the native apps.

### PR DESCRIPTION
**Pull request by SergioEstevao**
## Description

On the native apps, the publish button is managed by native code on
the apps (non Gutenberg/JS code). In order to update the status of the
publish button correctly, we need to autosave even when there is no
content, in order to send that information across the native code.

## How has this been tested?

This can be tested using this WP-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14329

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Feels weird having `isEditedPostSaveable() returning `true` always for native.
If it works better this way for us now we could pass it but this might hit us at some point in the future. It might be good to think about alternatives.

As I understand, this is basically to get the autosave message when the post became empty (user deleted last character). What about we detect when the post gets empty and trigger the autosave message manually?

I'm approving since it works for us now and we can improve on a different PR

**Comment by mchowning** [comment]
This works for me as expected on iOS. I agree with @etoledom that it feels weird to have `isEditablePostSaveable()` always return true for native, but I don't have a concrete reason that we shouldn't do that, so I'll approve as well.

Also worth noting that Android doesn't disable the publish button as best I can tell, so this fix does not affect that behavior on Android. Also though, since Android does not save on exiting the editor, this change actually fixes an issue where if you delete the last block and then exit the post on Android, the native side would have never gotten notified about the new empty state, so the "saved" post would be from before the block was deleted. Not a big bug, but it is a bug and this does fix it.

**Review by mchowning — APPROVED** [review]

**Comment by hypest** [comment]
> since Android does not save on exiting the editor

Sorry, can you elaborate on that one @mchowning ? I was under the impression that saving _does_ happen upon exit on WPAndroid so, I'm probably missing the circumstances you refer to on this one. Thanks!

**Comment by mchowning** [comment]
> I was under the impression that saving does happen upon exit on WPAndroid so, I'm probably missing the circumstances you refer to on this one.

:wave: @hypest ! WPAndroid currently only saves the post via the autosave mechanism; in other words, on exiting the editor the "saved" post is what was saved during the last autosave. For this reason, it is actually possible to type-then-exit-a-post-very-quickly and to lose a small bit of the just-typed text. iOS handles this differently and does save the post on exiting the editor.

Adding save-on-exit on Android is on my todo list, I just haven't had a chance to finish it up yet (ran into some issues where the save seemed to be bizarrely slow and I haven't had a chance to investigate that). The [description and comments on my draft PR adding the save-on-exit on Android](https://github.com/wordpress-mobile/WordPress-Android/pull/12144) gives _a lot_ of context around this.

**Comment by hypest** [comment]
> WPAndroid currently only saves the post via the autosave mechanism;

Thanks for the link to the [parallel conversation around the fix](https://github.com/wordpress-mobile/WordPress-Android/pull/12144) Matt!
I can be wrong, and just for understanding the history better, did we ever had "save-on-exit" or it's a case missing from the start? I'm under the impression that save-on-exit was there early during the block editor integration to the main app 🤔

**Comment by mchowning** [comment]
> for understanding the history better, did we ever had "save-on-exit" or it's a case missing from the start? I'm under the impression that save-on-exit was there early during the block editor integration to the main app 🤔

I'm not sure, but I bet @malinajirka knows. 🙂

**Comment by malinajirka** [comment]
I'm little late to the party, sorry. My notifications for the gutenberg repo were not set-up correctly.

>I can be wrong, and just for understanding the history better, did we ever had "save-on-exit" or it's a case missing from the start? I'm under the impression that save-on-exit was there early during the block editor integration to the main app 🤔

I believe we used to have save-on-exit. However, with the introduction of the reactive auto-save approach, this flow became obsolete. Technically there isn't any need to save-on-exit as the reactive auto-save always mirrors the changes from the UI to the model. The fact that we can lose changes from the last 500ms is a bug in the throttle implementation. As per the linked conversation we decided to implement save-on-exit instead of fixing the bug in the "throttle" implementation after all - however, it hasn't been implemented yet.

**Pull request merged**
