### PR TITLE
Navigation: Remove from experimental

### LINKED ISSUE #18550: Navigation block: Remove experimental flags
Once #18549 is merged, let's go ahead and remove the `__experimental` flags from the link and navigation components.

### PR DESCRIPTION
**Pull request by obenland**
## Description
Removes the Navigation block from the experiments page and makes it accessible to anyone.

Depends on #18551. 
Fixes #18550. 

## How has this been tested?

No more `Navigation Block` in the experimental Gutenberg section:

Loading menus in Editor and front-end on local test environment.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
Nice 👍 

I tested this manually and I can confirm that the setting is removed from "Experiments" sub page in Gutenberg section. 

I can also see the Block in the inserter by defalult without having to toggle anything "on".

From my limited knowledge of configuration for experiments (is this documented?) it looks like you've been pretty thorough.

I'd suggest it would be ideal to have someone from the Core team (@youknowriad?) look at this to ensure there aren't any other edge cases we're not aware of.

**Comment by retrofox** [comment]
Just FYI, I've changed the base to `master`, since https://github.com/WordPress/gutenberg/pull/18551 is already :shipit:

**Comment by getdave** [comment]
Taking this over for the meanwhile to finish it off.

**Review by youknowriad — COMMENTED** [review]
How about adding some e2e tests to the navigation block? nothing exhaustive but something to ensure the basic interactions are working as intended?

**Comment by getdave** [comment]
> How about adding some e2e tests to the navigation block? nothing exhaustive but something to ensure the basic interactions are working as intended?

@youknowriad I've been thinking about this. Do you consider that a Blocker to launching this Block?

If (as I suspect) it's not, then could we (myself or @obenland) raise an Issue and address in a follow-up PR? I'm happy to take these on.

**Comment by youknowriad** [comment]
It's not but I suspect that the block right now is broken for contributor role and an e2e test will help catch that. https://wordpress.slack.com/archives/C02QB2JS7/p1574176694224900

**Comment by youknowriad** [comment]
Sorry wrong slack link. Here's the correct one https://wordpress.slack.com/archives/C02QB2JS7/p1574173178189700

**Review by retrofox — APPROVED** [review]
Tested and LGTM.

**Comment by getdave** [comment]
> How about adding some e2e tests to the navigation block? nothing exhaustive but something to ensure the basic interactions are working as intended?

@youknowriad I looked and there's [an Issue for automated testing](https://github.com/WordPress/gutenberg/issues/18451). Not sure if/when I can get to that though for various reasons

**Pull request merged**
