### PR TITLE
docs: Further explanation for why .normalize() is optional

### PR DESCRIPTION
**Pull request by tofumatt**
Re: https://github.com/WordPress/gutenberg/pull/6983#discussion_r192382916

Just a brief documentation tweak.

### CODE REVIEW

**Review by noisysocks — APPROVED** [review]
Thanks for going into detail!

**Comment by iseulde** [comment]
Thanks!

**Comment by Zodiac1978** [comment]
> This is unsupported in IE 11 but it's a nice-to-have feature, not mandatory.
> Not normalizing the content will only affect older browsers
> entirely break the app.

@tofumatt I respectfully disagree.

Pasting NFD text will break the internal search in WP and can break the search on the website (like in Firefox), spellcheck, and the display (showing the  character + combining character side by side and not overlaying it, Firefox is failing here for example). 

And it can happen all the time that apps output NFD text and not NFC, like the W3C is recommending. 

Not sure if I would call fixing this breakage "not mandatory".

**Comment by noisysocks** [comment]
@Zodiac1978: Could you please create a new issue with steps to reproduce the bug you've described? Doing this will give everyone a space to discuss the bug and possible solutions e.g. polyfilling `.normalize()`.

**Pull request merged**
