### PR TITLE
Reduce minimum spacer height to 1px, while still retaining clickable area

### LINKED ISSUE #18906: Spacer Block: cannot adjust height to less than 20px
Steps to reproduce:

1. Add a spacer block.
1. In the block settings, set the height in pixels to something less than 20.

**Result:** I am allowed to make a change to "Height in pixels" that is less than 20 and save, however, the change is not reflected on the block and refreshing the page shows that the setting reverted back to the 20px minimum. There is a very small warning that appears on mouseover, but it's very difficult to spot (especially when navigating via the keyboard). Would it be possible to make that warning more explicit, possibly red and inline?

(Out of curiosity) why is the height of the spacer block limited to 20px or larger?

Screen Shot 2019-12-04 at Dec 4 2 29 25 AM
<sup>Tested with Firefox 70.0.1 on macOS 10.14.6 on a site running WordPress 5.3 with no plugins.</sup>

### LINKED ISSUE #24460: Spacer Block: Difficult to enter values directly into input field
**Is your feature request related to a problem? Please describe.**
Yes. If I try to empty the input field to directly put my height numbers into it (via num keys), it jumps back to 20px.
This isn't very convenient. **Test:**

1. Create a spacer block.
2. Mark the number in the input field.
3. Try to write like 500 via num keys. The field jumps to 200.
(Or try to change the height from 20 to 40 only with keyboard input, which is a common task on daily basis.)

**Describe the solution you'd like**
As long I have focus on the field it shouldn't update itself to the min height.
Currently it's updating on input change.

If I don't set any number or a number below min height and focus is lost, it should update itself to the min height.

**Describe alternatives you've considered**
There is no other way, just don't block direct keyboard input for number input fields.

### PR DESCRIPTION
**Pull request by jasmussen**
This PR takes a different approach to allowing a 1px tall spacer block. Alternative to #25525. Fixes #18906. Mitigates #24460.

The primary problem is that the sibling inserter above and below a 1px spacer block makes it appear hard to select the spacer.

It does a few things. First off, through a line height it fixes an issue with the sibling inserter being too tall. That red area is the clickable area shown for debug purposes:

Screenshot 2020-09-22 at 09 29 41
Screenshot 2020-09-22 at 09 29 58

Fixed:
Screenshot 2020-09-22 at 09 31 52

It alos changes the sibling inserter cursor from being hardcoded to `text`, to not being changed at all. In practice that means when you try to click a 1px spacer, you're technically clicking the sibling inserter hover area, but that area redirects to the nearest block which in most cases means the spacer block. So this is more of a visual change — when the cursor was text it didn't seem like a click would select the spacer block when in fact it would:

click

And finally, it adds a hidden "sizer" above the spacer block which provides a minimum clickable area:

click resizer

Here, it's shown in red, that's only for debug purposes. I believe we tried this in the past and it didn't work, but it seems to work fine here:

click resizer

CC and props: @stokesman for the initial work.

### CODE REVIEW

**Comment by jasmussen** [comment]
Note that the uncentered plus that's becoming visible due to the red debug color is a separate issue that I believe @ellatrix has tracked separately. And the jumpiness with the group block is fixed in https://github.com/WordPress/gutenberg/pull/25527.

**Comment by stokesman** [comment]
This is rad! Thanks for picking it up Joen. 

I suggest you add that this fixes #18906. Also while seemingly fixes #24460, that issue (despite its title) is more general and applies to any blocks using RangeControl.

**Comment by jasmussen** [comment]
Thanks so much. I'm out for the day but I'll be back on this tomorrow and hopefully pairing with @talldan on a separate/additional range control fix that only validates/corrects the minimum value once focus is outside of the input field.

**Comment by stokesman** [comment]
> range control fix that only validates/corrects the minimum value once focus is outside of the input field

Hmm... sounds awfully familiar #25131 😉

**Comment by jasmussen** [comment]
:mindblown: 

CC @talldan

**Comment by jasmussen** [comment]
Awesome, I've rephrased the body text to state the issue it fixes and only suggest it mitigates the other one.

I've restarted the tests on this one, it looks like they should pass. So it seems like the next step is just to get a review for this one and hopefully land it. I'll take a look at reviewing #25131 next.

**Review by talldan — APPROVED** [review]
This is working really well in my testing. The spacer is still very easy to select.

The only thing I notice that could be improved still is that it's a little difficult to get the block's border to show in navigation mode, which makes selecting if feel difficult (even though the click area is bigger than the border portrays):
selectmodespacer

I think we should give this a go though and try to improve that separately. Great work @jasmussen and @stokesman and anyone else who has taken time to iterate on this, I think this will make a lot of people happy!

**Comment by Sven74Muc** [comment]
When to expect this in the Gutenberg plugin for testing?

**Comment by jasmussen** [comment]
Version 9.1 I'd think.

**Comment by jasmussen** [comment]
@youknowriad After merging this I'm seeing some block validation issues with existing spacer blocks :( — did I do something wrong here? Do I need to to revert?

**Comment by youknowriad** [comment]
This PR doesn't have any impact on block vallidation, it's probably something else.

**Comment by Sven74Muc** [comment]
Working well, but with one limitaion:

1. I add a spacer and want to adjust the hight with the arrows... not working. 
2. Shifting the circle is working
3. Typing in the size is working
4. After I have changed the size through one of the other methodes cliccking on the up and dow arrows is working
5. Clicking on another block and than back in the spaer block... arrows are not working
6. After I have changed the size through one of the other methodes clicking on the up and dow arrows is working

**Comment by stokesman** [comment]
@Sven74Muc, when you refer to the up and down arrows, I'm thinking you mean the keyboard keys and not the little arrow buttons in the input. Will you clarify that?

**Comment by Sven74Muc** [comment]
Yes, I mean the little arrow buttons.
Using the latest Firefox browser on Win10.

**Comment by Sven74Muc** [comment]
I switched on the troubleshoot mode... disabled all plugins and switched to the twenty twenty theme >>> working
I enabled the Gutenberg plugin >>> not working

**Comment by jasmussen** [comment]
@Sven74Muc Thanks for the report. I can't reproduce, though, even in Firefox. Do you have any additional steps to reproduce? It also works for me in TwentyTwenty
firefox

**Comment by stokesman** [comment]
Thank you @Sven74Muc. I can confirm the issue. Easily reproduced in Firefox by clicking on the little arrows anytime the input does not already have focus. Other browsers focus the input at the same time the arrows are clicked.

Definitely not an issue with this PR. I'll try making a fix since it relates to changes from #25609.

**Comment by Sven74Muc** [comment]
Great, thanks @stokesman 
Sorry if I placed it on the wrong place... It came with the 9.1 update and the issue is with the sizing of the spacer. I'm not a programmer at all... so couldn't see that the issue is comming somewhere else. Hoever, thanks for looking into it!!

**Comment by Sven74Muc** [comment]
Just wondering where you have the arrows... I have them only on the right sidebar, not directly at the block

**Comment by stokesman** [comment]
@Sven74Muc, no worries. When I mentioned that it's not an issue with this PR it was to clarify for other readers. I've drafted a PR that fixes the issue. I'd guess this will be resolved by the next release but I'm not one to say.

**Comment by Sven74Muc** [comment]
Thanks @stokesman

**Pull request merged**
