### PR TITLE
Add a description to the Post Title block

### PR DESCRIPTION
**Pull request by MichaelArestad**
The Post Title block displays the post title and needs a description.

I kept the initial proposal rather simple and to the point:

> Add the title of your post.

@kristastevens Could you take a look, please?

#### Screenshot

image

### CODE REVIEW

**Review by epiqueras — APPROVED** [review]

**Comment by kristastevens** [comment]
Hi @MichaelArestad! Thanks for the ping!  

"Add the title of your post" is succinct and direct. Another idea is "Write the title of your post." It's just a little more specific. I feel like either works well, just wanted to leave another option for you to consider.

**Comment by MichaelArestad** [comment]
> Another idea is "Write the title of your post." It's just a little more specific. I feel like either works well, just wanted to leave another option for you to consider.

Right! I chose "Add" because it'll automatically pull in the title of your site by default.

**Comment by shaunandrews** [comment]
The WordPress Icons Figma shows an updated icon for this block:

image

**Comment by MichaelArestad** [comment]
Added the Post Title icon. 

image

I think this is ready to merge if there are no objections.

**Pull request merged**
