### PR TITLE
Docs: Add block toolbar component readme

### PR DESCRIPTION
**Pull request by JustinyAhin**
## Description
Added documentation for the block toolbar component (see #22891)

## How has this been tested?
N/A, documentation only

## Types of changes
Documentation

## Checklist:
- [n/a] My code is tested.
- [n/a] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by JustinyAhin** [comment]
@mkaz I'm wondering something.
For most of the uses cases of `BlockToolbar`, it is used with the `hideDragHandle` prop like this `<BlockToolbar hideDragHandle />`.

But I can't see nowhere what it `hideDragHandle` does exactly. Any idea? 

Thanks.

**Comment by mkaz** [comment]
It looks like it is used in [the Block-Mover component here](https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/block-mover/index.js#L53) but hard to tell how.

@jasmussen can you add any additional context?

**Comment by jasmussen** [comment]
I can't speak with full authority on that, but I would imagine that is necessary for the situation where a block can't be moved. For example when there's only one block:

Screenshot 2020-09-18 at 18 37 12

Other situations include where a block is locked otherwise.

**Review by gziolo — APPROVED** [review]
It looks like a good start 👍 

We could also add a reference to `BlockControls` component (SlotFill) that typically serves as a way for blocks to inject their toolbar items inside this component.

**Pull request merged**
