### PR TITLE
Fix width issue of text control in plugin sidebar

### LINKED ISSUE #41671: Panel Layout breaks if the Control label is short
### Description

Add a text control in a sidebar panel as below
` <TextControl
                        label={'Title'}
                        value={postMeta._header_banner_heading}
                        onChange={(value) => setPostMeta({ _header_banner_heading: value })}
                    />`
                    
 Now add another textcontrol underneath it with a longer label

` <TextControl
                        label={'Longer Label'}
                        value={postMeta._header_banner_heading}
                        onChange={(value) => setPostMeta({ _header_banner_heading: value })}
                    />`

The first control will break layout and not be full width as all the other controls.  The Label should be such that it should be atleast 42px in length for the input field underneath to display correctly as full width.

### Step-by-step reproduction instructions

1) Create a block plugin with a sidebar panel.
2) Add multiple text controls to it.
3) Any control with a label where the combined length of character is less than 42px in width wont align with the other controls

### Screenshots, screen recording, code snippet

sidebarpanel

### Environment info

Wordpress 6.0 Default Theme and Plugins

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by akasunil**
Input control width gets decreased if label is sort in custom `PluginDocumentSettingPanel`. 

## What?

Fixed [41671](https://github.com/WordPress/gutenberg/issues/41671)

## Testing Instructions

1. Create a block plugin with a sidebar panel.
2. Add multiple text controls to it.
3. Any control with a label where the combined length of character is less than 42px in width wont align with the other controls

## Screenshots or screencast 
CleanShot 2022-06-16 at 20 22 18@2x

### CODE REVIEW

**Comment by akasunil** [comment]
Waiting for PR review

**Comment by FalkoJoseph** [comment]
An update on this? :)

**Comment by akasunil** [comment]
@FalkoJoseph not yet, Still waiting for review.

**Comment by helgatheviking** [comment]
Ran into this bug today... hope this can be reviewed soon.

**Comment by FalkoJoseph** [comment]
> Ran into this bug today... hope this can be reviewed soon.

Doubt it. It's been more than a year ago. The maintainers seem to be more focussed on adding new features for end-consumers, rather than improving quality of life for WordPress developers. 

I've moved to ACF blocks which has skyrocketed our team's productivity, but I keep an eye on Gutenberg. I hope it will one day catch up with modern web development.

**Review by t-hamano — COMMENTED** [review]
Sorry for the late review. I believe the current behavior is expected. Please see [this comment](https://github.com/WordPress/gutenberg/issues/41671#issuecomment-2027329733).

**Comment by t-hamano** [comment]
As mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/41671#issuecomment-2027329733), I think the problem is not with the sidebar or the panel component, but with how `PluginDocumentSettingPanel` is used. I'd like to close this PR, but if there's anything I've missed, please feel free to comment.

**Pull request closed without merging**
