### PR TITLE
Fix a typo in the readme

### PR DESCRIPTION
**Pull request by MehtaRiddhi**
@jasmussen

I have Fixed some content changes in README.md and CONTRIBUTING.md file.

### CODE REVIEW

**Comment by jasmussen** [comment]
I appreciate your desire to contribute to Gutenberg, thank you!

However this is a fairly small change, and IMO not necessary.

**Comment by nylen** [comment]
The first comma is correctly placed.

The second one is a good typo fix:

> editor focus in **a** core

Let's just take that second change, @MehtaRiddhi.  Want to update this PR and get rid of the comma change?

**Comment by MehtaRiddhi** [comment]
@nylen,

Thanks for your suggestion. I have updated my PR and just take the second change.

Please review it and let me know if anything.

Thanks,

**Comment by nylen** [comment]
Thanks for the fix!

**Comment by paulwilde** [comment]
Umm, wasn't it already correct? This doesn't seem to make sense now.

**Comment by nylen** [comment]
"editor focus in core" is fine; the previous "editor focus in a core" makes me think of an apple or a nuclear reactor.

"editor focus in WordPress core" is perhaps better.

**Comment by paulwilde** [comment]
It was changed from "in core" to "in a core" though, not the other way.

**Comment by nylen** [comment]
Ahhh! How did I misread that. Sorry guys :)

**Pull request merged**
