### PR TITLE
Editor: Add ifPostTypeSupports higher-order component (try conditional render HoC pattern)

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to implement a new `ifPostTypeSupports` higher-order component which serves in place of the existing `PostTypeSupportCheck` and attempts to explore a new generalized pattern for conditional component rendering.

**Example Before:**

```jsx
function MyFeaturedImage() {
	return (
		<PostTypeSupportCheck supportKeys="thumbnail">
			<img />
		</PostTypeSupportCheck>
	);
}

export default connect( /* ... */ )( MyFeaturedImage );
```

**Example After:**

```jsx
function MyFeaturedImage() {
	return <img />;
}

export default compose( [
	ifPostTypeSupports( 'thumbnail' ),
	connect( /* ... */ ),
] )( MyFeaturedImage );
```

__Implementation notes:__

The thinking behind the naming convention is that we could create higher-order component-libraries with the following expectations:

Name|Behavior
---|---
`ifSomeCondition`|Renders component only if condition applies
`withSomeProps`|Renders component with additional props

__Testing instructions:__

Verify that there are no regressions in the behavior of post-type-conditional elements:

- Discussion (`comments` or `trackbacks` supports)
- Featured image (`thumbnail` support)
- Excerpt (`excerpt` support)
- Post format (`post-formats` support)
- Author (`author` support)
- Order (`page-attributes` support)
- Last Revision (`revisions` support)

### CODE REVIEW

**Comment by gziolo** [comment]
@jorgefilipecosta opened a similar PR. See https://github.com/WordPress/gutenberg/pull/4812. In general both implementation are similar 😃

**Comment by aduth** [comment]
Well then... 😅 

I think we could probably combine the two branches:

- Take README.md and completed replacement of `PostTypeSupportsCheck` from mine...
- ...and `withConditionalRender` (good idea!) and tests from @jorgefilipecosta 's

Can take a look tomorrow, or if @jorgefilipecosta wants to go ahead, by all means.

**Comment by jorgefilipecosta** [comment]
Thank you @aduth, I will merge both PR's 👍

**Comment by gziolo** [comment]
> Thank you @aduth, I will merge both PR's 

Yes, that would be nice. This one answers also some questions I had in the other PR :)

**Comment by aduth** [comment]
Closing in favor of #4812.

**Pull request closed without merging**
