### PR TITLE
render_block_core_latest_posts() Add filter for The block attributes

### PR DESCRIPTION
**Pull request by ghost**
## Description
Add a filter so that plugins and themes can filter the block attributes.

## Why is this needed.
Plugins may want to filter attributes in some situations. Eg. WPML will need to display posts in the current language only.

## How has this been tested?
This has been tested with WPML using the following code example.

```
add_filter( 'render_block_core_latest_posts_attributes', 'render_block_core_latest_posts_attributes_filter' );
function render_block_core_latest_posts_attributes_filter( $attributes ) {
   $attributes['suppress_filters'] = false;
   return $attributes;
}
```

## Types of changes
Add a new filter

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by andreasciamanna** [comment]
Will this change be included in WP 5.0?

**Comment by swissspidy** [comment]
Shouldn't this be covered by #11730?

**Review by youknowriad — COMMENTED** [review]
I think there's already a filter for the render_callback that is generic (across all blocks), I feel adding a specific filter like this is just a duplication.

**Comment by youknowriad** [comment]
see https://github.com/WordPress/gutenberg/issues/11523

**Comment by grey-rsi** [comment]
@youknowriad @swissspidy it's little different because `suppress_filters` it's not a Gutenberg block attribute by default

image

**Comment by youknowriad** [comment]
It is different, but you can achieve the same use-cases, maybe it's a bit more difficult in some cases and a bit easier in others.

**Comment by grey-rsi** [comment]
@youknowriad I can filter $attributes array with 'render_block' filter but there no way to pass `suppress_filters` to `wp_get_recent_posts` there

**Comment by youknowriad** [comment]
Can't you just regenerate the HTML output of the block the way you want?

**Comment by swissspidy** [comment]
That sounds a bit hacky though, especially since the block HTML output could change.

Why does the block even use `wp_get_recent_posts`? A regular `WP_Query` would have been just fine. This way one doesn't have to work around `suppress_filters` limitations.

**Comment by grey-rsi** [comment]
added https://core.trac.wordpress.org/ticket/45349 for adding filter inside `wp_get_recent_posts` instead

**Comment by gziolo** [comment]
I think it duplicates efforts started in https://github.com/WordPress/gutenberg/pull/11730 which tries to be more generic. There is also a similar proposal which tries to modify a single attribute for Reusable block block: https://github.com/WordPress/gutenberg/pull/8912.

**Comment by grey-rsi** [comment]
@youknowriad @gziolo is it ok if I modify pull request and replace `wp_get_recent_posts` on regular WP_Query like @swissspidy proposed?

**Comment by swissspidy** [comment]
Probably easier to do that in a separate PR as it's a totally different approach.

**Pull request closed without merging**
