### PR TITLE
Native Mobile: RichText: fix circular dependency

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

Currently the native component inside the `rich-text` package is depending on the `block-editor` package, while the `block-editor` package is depending on `rich-text`. It seems to be falling through the cracks is because the `block-editor` dependency is undeclared in the `package.json`.

The only fix is to move this component to the `block-editor` package. It's still using utilities from `rich-text`.

It's worth noting that on the web side, `rich-text` does not export a component at all. It does export a React hook that offers some _very_ basic core rich text functionality, sort of like with Aztec offers I guess. It would be great to create a similar hook in native at some point, if at all possible.

## Why?

I tried using the `rich-text` package in the `blocks` package, and it completely breaks all mobile e2e tests (`blocks` being a dependency of `block-editor`). Tbh, I have no idea why things are not breaking now.

### CODE REVIEW

**Review by derekblank — APPROVED** [review]
Looks good to me. I was able to smoke test the editor and run through our [Writing Flow test cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md) successfully.

@fluiddot @dcalhoun I opened a [companion PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6374). If you have further thoughts we can address them in a follow-up PR.

**Comment by ellatrix** [comment]
Thanks @derekblank!

**Comment by fluiddot** [comment]
> Currently the native component inside the `rich-text` package is depending on the `block-editor` package, while the `block-editor` package is depending on `rich-text`. It seems to be falling through the cracks is because the `block-editor` dependency is undeclared in the `package.json`.

Based on this import statement:
```
import { BlockFormatControls, getPxFromCssUnit } from '@wordpress/block-editor';
```
I saw that the `RichText` component we had in the `rich-text` package imported the following two items:
- `BlockFormatControls` used [here](https://github.com/WordPress/gutenberg/blob/7bba2baa635017a0e98cfeac86ec8b1c456a3757/packages/rich-text/src/component/index.native.js#L1299-L1303).
- `getPxFromCssUnit` used [here](https://github.com/WordPress/gutenberg/blob/7bba2baa635017a0e98cfeac86ec8b1c456a3757/packages/rich-text/src/component/index.native.js#L929-L930).

Not sure if other modules imported in the `RichText` component also depend on the `block-editor` package. If not, I wonder if we could replace the usage of both items instead of moving the entire component to a different package.

- Regarding `BlockFormatControls` usage: I think this should be defined in the `block-editor` `RichText` component instead of here. It depends on the `suggestionOptions` function, but I presume this functionality could also be defined in the parent.
- Regarding `getPxFromCssUnit`: This utility looks quite generic so probably we could move it to another package independent of `block-editor`.

> The only fix is to move this component to the `block-editor` package. It's still using utilities from `rich-text`.

Great work, thanks @ellatrix for addressing the circular dependency. I understand that this workaround makes the `RichText` component diverge between platforms a bit more than we currently have. Eventually, it would be great to reduce this divergence by exploring what I shared above and seeking opportunities to make the `rich-text` package implementation as close as possible on both platforms.
 
> It's worth noting that on the web side, `rich-text` does not export a component at all. It does export a React hook that offers some _very_ basic core rich text functionality, sort of like with Aztec offers I guess. It would be great to create a similar hook in native at some point, if at all possible.

Absolutely, it would be great if we could provide the `rich-text` package the same way as we have on the web side. Especially in the spirit of matching as closely as possible both implementations.

**Comment by ellatrix** [comment]
@fluiddot It was not just the `block-editor` package. It should also not depend a the `blocks` package, so there's even more dependencies.

Further, the native and web side of the `rich-text` package had already diverged significantly. On the web side, we have a relatively simple hook that augments `contenteditable`, while on the native side we had a full React component with Aztec inside it.

The rich text hook and utility functions in the `rich-text` packages are not supposed to have any awareness of block at all, while the rich text component in the `block-editor` does have blocks context.

**Comment by fluiddot** [comment]
> @fluiddot It was not just the `block-editor` package. It should also not depend a the `blocks` package, so there's even more dependencies.

Ah, good to know, thanks Ella for sharing this 🙇 . At some point, we'd need to explore deeper the dependencies in the native version of `RichText` and try to split them following the web approach.

> Further, the native and web side of the `rich-text` package had already diverged significantly. On the web side, we have a relatively simple hook that augments `contenteditable`, while on the native side we had a full React component with Aztec inside it.

I completely agree, the `RichText` package and component have diverged severely between platforms over time. We have in the roadmap revisit it and most likely work on a refactor. We are even considering removing Aztec to make the implementation a bit more seamless between platforms, but we need to explore its feasibility.

**Pull request merged**
