### PR TITLE
Full Site Editing: Remove block template resolution unit tests

### PR DESCRIPTION
**Pull request by ockham**
## Description
Per discussion here: https://github.com/WordPress/gutenberg/pull/36647#issuecomment-974141761

These tests have now been backported to Core, see https://github.com/WordPress/wordpress-develop/pull/1920, so they're no longer needed here.

Note that they also actually contained a test that was falsely negative -- it was only discovered in the process of backporting that the test setup in GB was faulty. This means that it also makes sense to delete the tests from GB in order to remove a false sense of confidence in them.

## How has this been tested?
Verify that CI goes green.

### CODE REVIEW

**Comment by youknowriad** [comment]
@ockham Should we track that falsy test (bug) somewhere.

**Review by youknowriad — APPROVED** [review]

**Comment by ockham** [comment]
> @ockham Should we track that falsy test (bug) somewhere.

I'll file an issue!

**Comment by aristath** [comment]
The PR needs to be rebased, there are now conflicts after merging https://github.com/WordPress/gutenberg/pull/36647

**Comment by ockham** [comment]
Rebased.

**Comment by ockham** [comment]
> > @ockham Should we track that falsy test (bug) somewhere.
> 
> I'll file an issue!

Since the issue is now in Core, I've filed a ticket in Core Trac: https://core.trac.wordpress.org/ticket/54515.

**Pull request merged**
