### PR TITLE
@wordpress/api-fetch  fetchAllMiddleware support CORS and Request parallelization

### PR DESCRIPTION
**Pull request by torounit**
## Description

* Cannot get `link` header in CORS request. Use `x-wp-totalpages` instead.
* Request parallelization on the second and subsequent pages.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
I think it'd be better to address this on the server and include `Link` as an exposed header: https://github.com/WordPress/wordpress-develop/blob/a6b87a8f1c4d6efc4382bfcfc2a188c05c6970c3/src/wp-includes/rest-api/class-wp-rest-server.php#L246

**Comment by torounit** [comment]
@TimothyBJacobs 

With `link` , only request one page at a time.

**Comment by TimothyBJacobs** [comment]
> With link , only request one page at a time.

Can you clarify what you mean by this?

**Comment by torounit** [comment]
@TimothyBJacobs 

Using `link` , a request for the next page is created after the request is completed.

https://github.com/WordPress/gutenberg/blob/316c2f9ef46ed821190e2229ba0b71d01c2bd54a/packages/api-fetch/src/middlewares/fetch-all-middleware.js#L85-L97

This change will execute multiple requests.

before: 
before


after: 

after

**Comment by TimothyBJacobs** [comment]
Ah, thanks for clarifying @torounit.

We'd need to be very careful about such a change. The reason for the limit on the number of items returned in the query is to try and reduce the load imparted on a server as much as possible.

If we send of all the requests at once, we can easily end up overloading some websites. I've seen sites cripple from just asking them to serve a couple of uncached pages at once. We'd be better off increasing the maximum number of items returned from a request at that point.

**Comment by torounit** [comment]
@TimothyBJacobs 

created ticket https://core.trac.wordpress.org/ticket/50369

Thanks !

**Comment by TimothyBJacobs** [comment]
Core ticket has been [merged](https://core.trac.wordpress.org/changeset/48112), thanks for the patch @torounit! Going to close out this issue now.

**Pull request closed without merging**
