### PR TITLE
Change the post template visually

### PR DESCRIPTION
**Pull request by youknowriad**
For block themes, this PR adds a modal to visually see the templates (Page templates) while changing it inside a modal.

**Notes**

 - Ideally, the modal is a fullscreen modal but our component doesn't support that yet, we need to revive the full screen modal separately.
 - Once we have a full screen modal we can consider some animation to slide the modal from the top or something.
 - Right now, I  just added a temporary "Change" link next to the "Edit" link in the template section of the sidebar. We need a better placement for this and maybe replace the "Page attributes" template section entirely.
- You'll notice that the "default" template (the one resolved using the CPT...) is not previewed properly, the problem is technical here, we don't have anyway  to know what template to load  there since it depends on the theme (it can be singlular, it can be single, page...), we might want a dedicated endpoint for this but it's going to be complex, so I think the current behavior might work to start with.

**Testing instructions**

 - Use a block theme.
 - Define some custom Page templates for your theme by adding the  following to your `experimental-theme.json` and by adding  the corresponding html files.
 
```
	"pageTemplates": {
		"custom": {
			"title": "My Custom Template"
		},
		"with-sidebar": {
			"title": "Template with sidebar"
		}
	}
```

 - Create a page, save it and then try to click the "change" link in the sidebar.

### CODE REVIEW

**Comment by youknowriad** [comment]
Time to get some feedback about this.

**Comment by jasmussen** [comment]
Taking a look now, but I think I'm doing it wrong:
 
Screenshot 2021-01-28 at 10 40 04

**Comment by youknowriad** [comment]
@jasmussen mmm, this looks good to me. Weird that it doesn't work, I have the exact same thing.

**Comment by youknowriad** [comment]
Oh (try a page, not a post) just in case.

**Comment by jasmussen** [comment]
Okay I got it working, and I see this:

behavior

_Don't be confused, all three templates are the same, so the preview is correct._

This is a cool feature, big fan.

My thoughts immediately go to: how do we implement this in a way that feels even more intuitive? The flow as is can probably be tweaked to make for a good V1 — white background, better thumbnail treatment, hand cursor when hovering a template part, stronger active state, better "default" thumbnail — and I'd be happy to help with that. 

But in terms of the longer view, I would like to see if we can avoid the modal dialog altogether. I think of this in the same prespective as the preview dropdown resizing the canvas itself, rather than showing previews in a modal dialog. You are affecting the canvas, so you should _affect the canvas_, if that makes sense.

@jameskoster has made some amazing designs for how that might work, and issue #27850 is full of good ideas, notably [this one](https://github.com/WordPress/gutenberg/issues/27850#issuecomment-767577923) helps give a good overview of templates available, while making it clear that it's the entire layout you're switching out.

But that design is probably a big step. A smaller interim step, towards that, might be this mockup:

Screenshot 2021-01-28 at 11 12 52

Essentially we resize the canvas, and show the templates above the canvas with the active one selected. How hard would such a step be to accomplish?

**Comment by youknowriad** [comment]
I don't like the "resize the canvas and show the template on top of it". What I don't like is the gymnastic it forces us to do in terms of CSS and potentially keyboard navigation/accessibility.

I feel we can get very close to that using a full screen modal:

 - Full screen modal showing the exact same design as the mockup above
 - We get the a11y of the modal pattern
 - We don't have to make any hacks to CSS to "resize the canvas" or anything.
 - We lose the resize canvas animation but maybe we can approach it with an nice animation to show the modal.

**Comment by jameskoster** [comment]
I rustled this together in the Inspector just to get an idea of how a full-screen modal might feel. With some design polishing I think it could work.

modal

**Comment by jasmussen** [comment]
> I don't like the "resize the canvas and show the template on top of it". What I don't like is the gymnastic it forces us to do in terms of CSS and potentially keyboard navigation/accessibility.

Would some of the fancy "flip" animations that Jay outlined, for example the first one on [this comment](https://github.com/WordPress/gutenberg/issues/27850#issuecomment-766766108), help address this? 

That animation, specifically, still feels like it manipulates the canvas itself, even if it does technically enter a modal.

**Comment by youknowriad** [comment]
> Would some of the fancy "flip" animations that Jay outlined, for example the first one on this comment, help address this?

At this point, I don't know how we could achieve this animation. Using a modal basically mean rendering a new DOM tree in another place, and not reusing and animating the same element like that animation does. Maybe we could fake it somehow, but it's going to be difficult.

**Comment by jameskoster** [comment]
FWIW this "flipping" or "zooming" animation will likely have many other applications, if we can get it right. IE [zooming in and out of the template editor / template mosaic view](https://github.com/WordPress/gutenberg/issues/20477#issuecomment-766922262).

**Comment by lukecarbis** [comment]
I'd be interested for @ItsJonQ to weigh in on any fancy animations involved in bringing up the modal, and how they might fit with the G2 components design language.

**Comment by paaljoachim** [comment]
Perhaps we can use an existing modal that users, everyone uses a lot.
So that we can keep some consistency with existing modals.

Select-or-Upload-Media-modal

**Comment by jameskoster** [comment]
I shared an alternative design concept for this over in https://github.com/WordPress/gutenberg/issues/27850#issuecomment-824275756

**Comment by youknowriad** [comment]
Closing this one for now. Some of this is being reused in #33770

**Pull request closed without merging**
