### PR TITLE
Build: assign the library exports to window.wp rather than this.wp

### LINKED ISSUE #26134: dependency-extraction-webpack-plugin doesn't work with Webpack 5
**Describe the bug**
Using `@wordpress/dependency-extraction-webpack-plugin` with Webpack 5 throws a build error:

```
[webpack-cli] Promise rejection: TypeError: Cannot read property 'tap' of undefined
[webpack-cli] TypeError: Cannot read property 'tap' of undefined
    at ExternalModuleFactoryPlugin.apply (.../node_modules/@wordpress/dependency-extraction-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:17:37)
    at .../node_modules/@wordpress/dependency-extraction-webpack-plugin/node_modules/webpack/lib/ExternalsPlugin.js:16:63
    at Hook.eval [as call] (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (.../node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at .../node_modules/webpack/lib/Compiler.js:958:23
    at Hook.eval [as callAsync] (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (.../node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (.../node_modules/webpack/lib/Compiler.js:955:28)
    at .../node_modules/webpack/lib/Compiler.js:456:12
    at Compiler.readRecords (.../node_modules/webpack/lib/Compiler.js:797:11)
```

**To reproduce**
1. Install and configure Webpack.
1. Add `@wordpress/dependency-extraction-webpack-plugin`.
2. Build.
3. See error.

**Expected behavior**
Build succeeds with no error.

**Package versions:**
- `webpack` 5.1.0
- `webpack-cli` 4.0.0
- `@wordpress/dependency-extraction-webpack-plugin` 2.7.0

**Additional context**
Webpack 5 is the current stable version of Webpack. This and other `@wordpress` packages should work with it.

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes https://github.com/WordPress/gutenberg/issues/26134.

When the Gutenberg libraries are built into production scripts, they start with a preamble like:
```js
this.wp = this.wp || {}, this.wp.data = ( function( e ) { ... } )( ... );
```
It evaluates an IIFE with the compiled library and assigns the exports to `this.wp.data`. In non-strict mode, `this` evaluates to `window` or `global`. In strict mode, if the script started with `"use strict"`, `this` would be `undefined` and the library would fail to load.

In webpack 5, the modules are in strict mode by default, and opting out of strict mode disables some optimizations like module concatenation. `this.wp` relies on legacy JS features, namely the non-strict mode.

At the same time, many [existing WordPress scripts](https://github.com/WordPress/WordPress/blob/master/wp-admin/js/editor.js) use the same preamble with `window`:
```js
window.wp = window.wp || {}, window.wp.data = ( function( e ) { ... } )( ... );
```

As the scripts are ever loaded into a browser (are they?), `window.wp` is equally good, but compatible with modern JS and tools.

This PR changes the way how build output is generated by webpack, and how the `dependency-extraction-webpack-plugin` imports external modules.

It should be fully backward compatible, because, in the end, if it succeeds, the assignment target is always `window`, both before and after.

Related webpack 5 bug that I found when playing with webpack 5 and `dependency-extraction-webpack-plugin`: https://github.com/webpack/webpack/issues/11724

### CODE REVIEW

**Comment by gziolo** [comment]
It looks like everything works as expected with the changes proposed. We use `wp.*` notation in e2e tests so this should give good feedback. The tests that fail at the moment, were introduced yesterday in `master` branch.

**Comment by gziolo** [comment]
We discussed this PR during the weekly WordPress Core JS meeting. Transcript starts here:

https://wordpress.slack.com/archives/C5UNMSU4R/p1603204040245200
(link requires registration at https://make.wordpress.org/chat/)

The gist of it that we should try to proceed with this approach if nobody raises any blockers in the upcoming days.

In the worst-case scenario, the alternative approach could be using `globalThis` and polyfill it for browsers that don't support it.

**Review by gziolo — APPROVED** [review]
On the technical level, this change works as expected. I tested using JS Console in the browser and I was able to use all tested `wp` modules as before.

Given that we are after WordPress 5.6 beta release, we can give it a try as we will have a few months to observe if it has negative impact.

**Review by sirreal — APPROVED** [review]
I haven't tested this. The changes look good and I believe using `window` is the right direction.

**Comment by jsnajdr** [comment]
> In the worst-case scenario, the alternative approach could be using `globalThis` and polyfill it for browsers that don't support it.

We can use `globalThis` if we decide to, but I'd rather do it when we become aware of an actual use case that requires that. When running Gutenberg packages in Node.js, they should be consumed from NPM packages, not from the built scripts inside the plugin. That leaves workers or service workers where the global object is `self`?

**Comment by gziolo** [comment]
> That leaves workers or service workers where the global object is `self`?

Good point, let's keep it in mind when taking the next steps. As discussed, we can address it separately if it causes issues.

**Pull request merged**
