### PR TITLE
Remove Gutenberg font face tests

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Remove Gutenberg font face tests.

## Why?
The tests that no longer test the code in Gutenberg but the code from core because the classes being tested are not loaded from Gutenberg but from core

## How?
removing the test files.

### CODE REVIEW

**Review by getdave — APPROVED** [review]
LGTM 👍

**Comment by getdave** [comment]
I just _manually_ cherry-picked this PR to the [cherry-pick-wp-6-5-beta-3 branch](https://github.com/WordPress/gutenberg/pull/59394) to get it included in the next release.

I did this to get the tests passing on that PR.

**Comment by creativecoder** [comment]
It looks like this is also needed for the `release/17.8` branch, as the same phpunit tests are failing there. I've added the [Backport to Gutenberg RC](https://github.com/WordPress/gutenberg/labels/Backport%20to%20Gutenberg%20RC) label.

**Comment by creativecoder** [comment]
I just cherry-picked this PR to the release/17.8 branch to get it included in the next release: de472fd5ca

**Pull request merged**
