### PR TITLE
Tweak to "wp-block-gallery" style, to be more efficient

### PR DESCRIPTION
**Pull request by nathansmith**
### NOTE

There are some failing tests that already existed in `master` when I cloned the repo.

That is beyond the scope of the file that I changed in this PR. Hopefully that is okay.

---

### Description

While looking through the CSS for `wp-block-gallery`, I noticed several aspects that could be simplified considerably.

Specifically, the way that "gutters" are created between gallery items. It currently uses `margin-right`, which necessitates a lot of tweaks based on the number of columns, and involves overrides to handle `:nth-of-type(…)` exceptions.

Instead, I ended up refactoring this code for our own usage (at my job), so that we can use WP generated markup in a stand-alone "headless" Gatsby context. My coworkers suggested that I submit a Trac ticket…

https://core.trac.wordpress.org/ticket/50690

…which eventually led me to create this PR.

I simply used interior `padding-left` and `padding-right` for each gallery item `<li>`. With a negative `margin-left` and `margin-right` offset applied to the parent `<ul>`.

---

### How has this been tested?

I visually tested this using a Vagrant setup, with the plugin code running locally via `npm run dev`.

Since this is a style change only, there were not unit tests that needed to be written and/or changed.

I did test on a number of browsers and breakpoints. This is also akin to code we have been using for our own in-house theme approach, and it has served us well so far.

---

### Screenshots

Here are screenshots at several breakpoints. Hopefully these will suffice. If need be, I can provide more.

| &nbsp; | **Chrome** | **Firefox** | **Safari** |
| --: | :-- | :-- | :-- |
| **small width** | chrome-small-width | firefox-small-width | safari-small-width |
| **medium width** | chrome-medium-width | firefox-medium-width | safari-medium-width |
| **large width** | chrome-large-width | firefox-large-width | safari-large-width |

---

### Types of changes

This PR introduces styling changes only. The underlying markup remains untouched.

---

### Checklist

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by noisysocks** [comment]
Thanks for the PR! Can you please rebase master so that the failing tests are fixed?

**Comment by nathansmith** [comment]
cc: @noisysocks 

I rebased `master`.

I apologize for the noisiness of the commit history.

**Comment by noisysocks** [comment]
It looks like there are some CSS linter errors. You can run `npm run lint-style` locally to see them.

```
packages/block-library/src/gallery/style.scss
   52:3  ✖  Unexpected duplicate selector ".wp-block-gallery .blocks-gallery-image img, .wp-block-gallery .blocks-gallery-item img", first used at line 45   no-duplicate-selectors
  105:2  ✖  Unexpected duplicate selector ".wp-block-gallery .blocks-gallery-image, .wp-block-gallery .blocks-gallery-item", first used at line 20           no-duplicate-selectors
```

**Comment by nathansmith** [comment]
cc: @noisysocks 

I made those changes, and everything seems to be passing now.

**Comment by noisysocks** [comment]
Thanks @nathansmith.

I tested this locally using Twenty Nineteen and I see two issues:

1. The amount of whitespace in between gallery images has decreased in both the frontend and editor.
2. The mover controls (⬅️ ➡️) in the editor now sit flush against the gallery image instead of having 10px padding.

| | Before | After |
| - | - | - |
| Frontend | Screen Shot 2020-11-26 at 11 34 10 | Screen Shot 2020-11-26 at 11 34 18 |
| Editor | Screen Shot 2020-11-26 at 11 33 32 | Screen Shot 2020-11-26 at 11 33 34 |

**Comment by nathansmith** [comment]
Just FYI:

I'm going to close this, as I think there are probably a lot of themes that already rely on the previous styling.

We will just continue to add our overrides, but not muddy the waters by attempting to get this into core.

I apologize for the unnecessary chatter, pings, and churn related to this ticket.

Sorry about that! 😆

**Pull request closed without merging**
