### PR TITLE
Make strings translatables in block patterns

### LINKED ISSUE #24646: Fix translatable strings in block patterns (take 2)
_Originally on Core Trac: https://core.trac.wordpress.org/ticket/50845_

**Describe the bug**
Some strings in block patterns are hardcoded, making then non translatables.

**To reproduce**
1. Select another language for WordPress except English
2. Add a large header button or three columns text and buttons patterns
3. Notice that some strings in the patterns are not translated in the selected language.

**Expected behavior**
The strings should be translatables.

### PR DESCRIPTION
**Pull request by JustinyAhin**
## Description
Fix #24646.

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.
- [ ] I've included developer documentation if appropriate.
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Soean** [comment]
Hey @JustinyAhin can you explain why you are removing the `gutenberg` text-domain? It's not needed in core, but i think for the plugin it's necessary.

**Comment by JustinyAhin** [comment]
> Hey @JustinyAhin can you explain why you are removing the `gutenberg` text-domain? It's not needed in core, but i think for the plugin it's necessary.

My bad @Soean. Mistake while integrating the changes from the patch on Trac. Just added two new commits to change that.

**Comment by Soean** [comment]
It also adds a text color, is this intended? `{\"textColor\":\"black\"} -->\n<p class=\"has-black-color has-text-color\"`

**Comment by JustinyAhin** [comment]
> It also adds a text color, is this intended? `{\"textColor\":\"black\"} -->\n<p class=\"has-black-color has-text-color\"`

Should be good now :)

**Review by Soean — APPROVED** [review]
Thanks, looks good now.

**Pull request merged**
