### PR TITLE
Adds top toolbar improvements to site editor

### PR DESCRIPTION
**Pull request by draganescu**
Continues #47277

To make things easier to review this patch applies the top toolbar improvements to the site editor.

https://user-images.githubusercontent.com/107534/228895681-230a2fc5-dd20-4ca4-9b2c-ba7070af6c4f.mp4

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for putting the PR together. 

It brings https://github.com/WordPress/gutenberg/issues/29673 into stark visibility, but even with correct alignment it seems we wouldn't have enough space to accommodate everything nicely on smaller screens.

The duplicated template part name is also awkward:

Screenshot 2023-03-30 at 19 09 25

I think this could use some design exploration to get right.

**Comment by jasmussen** [comment]
We might want to fade out / hide that center element when a block is selected, at the very least on smaller viewport widths.

**Comment by jameskoster** [comment]
That's an option, but if it becomes the way to invoke the [Command Center](https://github.com/WordPress/gutenberg/pull/49330) in the full-screen editor as discussed, then it's importance goes up quite a bit, and I'd be a _little_ nervous about hiding it.

Perhaps we start with that though, and see how it feels?

For the duplicated template part name issue, maybe we hide the one in the center element when top toolbar is enabled? We might be able to remove it altogether in the future.

**Comment by jasmussen** [comment]
> That's an option, but if it becomes the way to invoke the https://github.com/WordPress/gutenberg/pull/49330 in the full-screen editor as discussed, then it's importance goes up quite a bit, and I'd be a little nervous about hiding it.

I'm thinking of it more as the top toolbar being entirely contextual. Just to visualize across the spectrum:

Top Toolbar

That includes an in-exploration new document selector as mocked up by @SaxonF.

**Comment by jameskoster** [comment]
> I'm thinking of it more as the top toolbar being entirely contextual

So the premise is: because I selected a block, I'm working on that block, and won't want to invoke the command center during that process?

That makes sense to me conceptually, but the idea of having to deselect a block before being able to invoke the command center (outside of the keyboard shortcut) seems a little bit unexpected. Especially if we can see per-block commands "make this text sound more formal" being added in the future.

Still, probably fine in the short term 👍

**Comment by draganescu** [comment]
Closed in favor of #49634 which also includes site editor in the update.

**Pull request closed without merging**
