### PR TITLE
Try read only navigation sidebar in browse mode

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Alternative to #48933
Complementary to #48935

Makes the navigation in browse mode unable to edit the menu it displays. It works only as a way to browse through the site using the primary navigation menu which should be visible on the site already.

## Why?

The editing experience in the navigation sidebar is very rough around the edges. The feature itself - being able to browse the website and edit each page you browse to - is extremely valuable in the site editor. However editing the navigation can be better accomplished using the navigation block.

We can follow up later on this feature and make it able to edit the navigation as well.

## How?

For now, pretty hack-y:

- I had to add a new prop to the off canvas editor component to disable drag and drop
- I had to create a work around to disable the more menu
- I have also filtered out any block which is not a navigation link or navigation submenu

## Testing Instructions

1. Check out this branch
2. Have one navigation menu 
3. Use the site editor Navigation sidebar

## Screenshots or screencast 

https://user-images.githubusercontent.com/107534/224122833-bf9f10fd-8e5b-4517-9a74-5dc2edd427f4.mp4

👋🏻  @jorgefilipecosta this PR is pretty rough - I meant it as a way to see how having this as a last reasort feels. Not sure on my implementation choices.

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for putting this together, it's helpful to get feel for how the panel would work without edit capabilities. A couple of notes:

* Custom link handling is still very rough.
* Things break down quite a bit when you have blocks like Search, Site Logo, and particularly: Page List. The disconnect between the panel and the frame here is quite stark:

https://user-images.githubusercontent.com/846565/224139064-86c14a7b-fbbd-414c-aa37-d47568d038cd.mp4

If we could display the children of Page List that would help. 

I'm not sure how it would feel so perhaps something to try: being able to _see_ blocs like Search might help, even if you can't do anything with them. It would clarify the connection between the sidebar and the frame a bit. They could be simply styled with no hover effects. We might do the same for Custom Links.

**Comment by draganescu** [comment]
@jameskoster I missed the page list from filtering great catch 😆 I will push a commit with this in.

Edit: done in [ae73512](https://github.com/WordPress/gutenberg/pull/48971/commits/ae7351225b8bb540e19ce8e33542231b0d5bedef) - @jameskoster try your example now, the need to show non link blocks is less.

I do agree I should try to stryle custom links so that they don't show pointer on hover.

**Comment by draganescu** [comment]
For me the most annoying part is that clicking on an item that has a chevron to expand, navigates instead of expanding! It's so easy to mistake click!

**Comment by jameskoster** [comment]
Since this is read only, do we need to display the Page List parent / structure? The appearance is broken (Page List is selectable, children have odd background):

Screenshot 2023-03-10 at 09 41 37

Simply displaying the children as root level items would likely be better, and fix the chevron issue you mentioned (for Page List at least, submenus are another story).

> the need to show non link blocks is less

It is less, but I still think it's worth a try, purely because it makes that connection with the frame 1:1. Crude example:

Screenshot 2023-03-10 at 09 46 26

**Comment by draganescu** [comment]
Yes, I dislike the page list too showing up there like a parent ... I remember @jorgefilipecosta had an approach to hide it ...

Edit: yes in #48725 we try to hide the parent - but only if the menu is _only a page list_. Given that the page list block could be filtered by parent ID this makes things a bit more complicated.

**Comment by jameskoster** [comment]
One small detail we might consider here, since the menu items are read only: Adding a drilldown indicator (chevron) to the relevant items. 

Screenshot 2023-03-10 at 13 17 45


Related: https://github.com/WordPress/gutenberg/pull/48962

**Comment by scruffian** [comment]
> Custom link handling is still very rough. Things break down quite a bit when you have blocks like Search, Site Logo,

I don't consider that the experience in this PR is any worse for these block than it is in trunk, we just need to get that blue box to fill the container:
Screenshot 2023-03-10 at 15 14 28

IMO this approach removes some of the confusion around what can and cannot be edited, without degrading the experience, but I'll leave the decision about whether to merge it someone who is working on it more closely.

**Comment by draganescu** [comment]
Given the work in https://github.com/WordPress/gutenberg/pull/49043 which hides the navigation screen in core this exploration can be closed.

**Pull request closed without merging**
