### PR TITLE
Button: Remove green background color in button preview

### LINKED ISSUE #21954: Button preview doesn't match styling
**Describe the bug**
The style preview for buttons no longer matches the button being edited.

**To reproduce**
1. Install current master branch.
2. Add a button to the page.
3. Check the previews to see if the button matches. 

Note: it never matched custom color selections or border radius option, only the default.

**Expected behavior**
Button previews will match the button style.

**Screenshots**

WordPress 5.4
Screen Shot 2020-04-28 at 2 31 29 PM

Master
Screen Shot 2020-04-28 at 2 30 47 PM

7.9.1
Screen Shot 2020-04-28 at 2 34 36 PM

**Editor version (please complete the following information):**
- WordPress version: 5.4
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? yes
- If the Gutenberg plugin is installed, which version is it?
- Current master branch, but also noticed with 7.9.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 81

**Additional context**

### PR DESCRIPTION
**Pull request by walbo**
## Description
Remove the green background color in the button example. The button will then use the default button color. This will also make the style from the theme match the preview.

Fixes #21954 

## How has this been tested?
Locally with different bundled themes.

## Screenshots 
button-green-fix

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by skorasaurus** [comment]
Thanks for including screenshots and the PR; I didn't realize this would be such an easy fix! 

I've tested this on a block-based theme (hansen) and the green color background is removed.

**Comment by walbo** [comment]
I have also tested it on a couple of custom themes and havn't found any issues with the fix.

**Comment by stokesman** [comment]
I found no issues testing this on a few custom themes. This seems like the way it ought to be 👍 .

**Review by Mamaduka — APPROVED** [review]
It works as expected. Thanks for the contribution, @walbo.

**Pull request merged**
