### PR TITLE
Nested Blocks: Add Button to Select Parent

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Alternative for #14148. This is a really simple addition. It just adds a button at the start of the block toolbar to select the parent block. Thoughts welcome. (I've been frustrated trying to select parent blocks...) Cc @jasmussen @mapk.

To do: needs a different icon and better hover styles. For the icon, I had something like ↖️ in mind.

screenshot 2019-02-28 at 17 33 07

* I like the idea of clicking through to select a child block as well. This is kind of the opposite. You'd start from the parent instead of the deepest child. See #9628.
* I don't like the idea of adding padding because it no longer correctly visualise how it would look like on the front end.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I love the idea and it's awesome to see iteration happening. 

At a high level, I'm not sure about the placement. I think the Block Icon being the primary icon in the toolbar should be immutable. There's a lot to be said for the 'mental muscle memory' of the block icon/block chip being in a reliable spot every time.

That said, I'm very much just "not sure" — I can totally be convinced in another direction :)

**Comment by mapk** [comment]
Great exploration, @iseulde! This keeps the user's focus within the block which is a step up from the Block Navigation tree at the top of the page which requires the user to search elsewhere for block navigation.

My only concern is this still requires the user to click on "something else" rather than what they want to click on (the parent block). I'm not quite sold on this, but am interested in other's perspectives.

I'm also aware that adding padding as in #14184, does change the layout a bit which isn't ideal. I'd love to see a way to expand the parent block while keeping the child blocks the same, instead of keeping the parent block the same and forcing the child blocks smaller. I'll try to prototype something here soon.

**Comment by mapk** [comment]
Here's that prototype idea I mentioned. https://github.com/WordPress/gutenberg/issues/9628#issuecomment-468481598

**Comment by jasmussen** [comment]
I love that you're tackling this issue. It's crucially important, I think everyone agrees.

I'm personally not so much a fan of adding additional buttons to the block toolbar — it feels like for every button and element we add, we reduce the value of existing buttons. This doesn't mean we might eventually _need_ such a button — just that I'm dreaming of a solution that doesn't require such a button. 

I chatted with you yesterday about a related idea in Slack, and sharing here. Basically we were talking about various ways to make selecting the parent easier. In the case of the quote, we need something intuitive and simple, I believe perhaps @mapk's idea can work well. For other cases where you're working with very complex layouts and deep nesting, it might be okay to have additional redundant UI for that. 

One of the interfaces we had way in the start of the project, was a breadcrumb bar instead of tabs at the top of the sidebar. Instead of "Document" and "Block" tabs, it would say `Document → Block` when a block was selected, and simply `Document` when no blocks were selected. The behavior was technically identical to what we have in master right now, it was just breadcrumbs instead.

One of the things we _could_ explore, is to leverage that breadcrumb trail to work for nested blocks too. I.e. like this:

screenshot 2019-03-01 at 08 26 29

You might even imagine, one day, that we'd want to allow you to select the Site itself, in order to create global changes right then and there. 

This is obviously a sidebar only solution, so it's not a blanket solution for everything. We have the clickthrough on mobile, that could be enhanced and expanded. We have the arrow key navigation, where arrow-up when inside a nested block selects the parent. We have Mark and @kjellr's idea (https://github.com/WordPress/gutenberg/issues/9628#issuecomment-468381291) — between those it feels like there are some avenues to explore before we need to add another button to the toolbar.

**Comment by iseulde** [comment]
> I'd love to see a way to expand the parent block while keeping the child blocks the same, instead of keeping the parent block the same and forcing the child blocks smaller.

@mapk What if the parent is full width? I'm trying to create something with nested blocks where this is the case. I think changing the layout assumes too much.

@jasmussen As discussed in DM, I like the breadcrumb idea. The idea is a bit similar to how the classic editor worked with a trail of elements at the bottom of the editor. The sidebar sounds like a good idea because most of the time you'll be working with complex layouts.

In the case of simpler blocks, the problem remains. If we ever try to use nested blocks for lists and quotes, the sidebar might not be the place where you'd look. Maybe you're right, perhaps we'll need different solutions for different blocks, but this might get a bit confusing.

That's why I just went for the button, as it works everywhere, but yead it comes at the cost of extra UI. :/

**Comment by jasmussen** [comment]
> What if the parent is full width? I'm trying to create something with nested blocks where this is the case. I think changing the layout assumes too much.

If the parent is full-width, we can _scale it down when selected_. Keep in mind, a selected block doesn't have to look 100% like the end result. Like when we pop out a caption field on a selected image. 

Technically it's a hairball — when to scale, when to go outside the boundaries. But if we can describe the flow and edgecases, it seems like it should work.

**Pull request closed without merging**
