### PR TITLE
uuid: Update to v7.0.2, fix imports

### PR DESCRIPTION
**Pull request by ockham**
## Description
Janitorial, similar to https://github.com/Automattic/wp-calypso/pull/39827.

See [v7 breaking changes](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#-breaking-changes).

## How has this been tested?

Smoke tested. Also watch for e2e tests in CI.

## Types of changes

Dependency update, import fixes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by sirreal** [comment]
Not sure how/if node requires should be updated, but this one may have been missed:

https://github.com/WordPress/gutenberg/blob/4cc8121c95b507809056fca158b6bae60ed22157/bin/commander.js#L19

**Comment by ockham** [comment]
> Not sure how/if node requires should be updated, but this one may have been missed:
> 
> https://github.com/WordPress/gutenberg/blob/d788256cb886cbe38f99b18bd0e34219c901eaec/bin/commander.js#L19

Thanks, good spot! https://github.com/uuidjs/uuid#deep-requires-now-deprecated says

```js
const { v4: uuidv4 } = require('uuid');
```

Added e8fff3bae1 to do that.

**Comment by aduth** [comment]
Did they jump straight from 3.x to 7.0 ? I'm trying to determine if there should be breaking changes to consider for versions 4, 5, and 6 ?

**Comment by aduth** [comment]
Since the import change could result in larger bundle size, I checked to confirm that it should be possible to tree-shake `v4` named export, by combination of `sideEffects` and `module`:

https://unpkg.com/browse/uuid@7.0.2/package.json

**Comment by aduth** [comment]
The report at https://github.com/WordPress/gutenberg/pull/21258#issuecomment-605961347 seems to indicate a fair bit of size change. Not sure if it's just that the bot is misbehaving?

**Comment by youknowriad** [comment]
if the bot doesn't behave properly, rebase the branch (I had once seen weird numbers). But after the rebase, the numbers should be accurate;

**Comment by ockham** [comment]
> Did they jump straight from 3.x to 7.0 ? I'm trying to determine if there should be breaking changes to consider for versions 4, 5, and 6 ?

Seems like -- both the Changelog and their [releases page](https://github.com/uuidjs/uuid/releases) seem to indicate so.

**Comment by ockham** [comment]
> > Did they jump straight from 3.x to 7.0 ? I'm trying to determine if there should be breaking changes to consider for versions 4, 5, and 6 ?
> 
> Seems like -- both the Changelog and their [releases page](https://github.com/uuidjs/uuid/releases) seem to indicate so.

Ah, they have something in their README: https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-uuid3

**Comment by ockham** [comment]
> if the bot doesn't behave properly, rebase the branch (I had once seen weird numbers). But after the rebase, the numbers should be accurate.

Rebased :crossed_fingers:

**Comment by ockham** [comment]
Numbers looking better now! :relieved:

**Review by aduth — APPROVED** [review]
> Numbers looking better now! 😌

It does indeed!

**Review by aduth — CHANGES_REQUESTED** [review]
I see local changes to `package-lock.json` when I run `npm install` in my branch. We'll want to make sure those are committed.

```diff
diff --git a/package-lock.json b/package-lock.json
index 2c78f76b8d..2da4a97048 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -11220,7 +11220,8 @@
 						"qs": "~6.5.2",
 						"safe-buffer": "^5.1.2",
 						"tough-cookie": "~2.5.0",
-						"tunnel-agent": "^0.6.0"
+						"tunnel-agent": "^0.6.0",
+						"uuid": "^3.3.2"
 					}
 				},
 				"restore-cursor": {
@@ -11305,6 +11306,12 @@
 					"resolved": "https://registry.npmjs.org/type-fest/-/type-fest-0.8.1.tgz",
 					"integrity": "sha512-4dbzIzqvjtgiM5rw1k5rEHtBANKmdudhGyBEajN01fEyhaAIhsoKNy6y7+IN93IfpFtwY9iqi7kD+xwKhQsNJA==",
 					"dev": true
+				},
+				"uuid": {
+					"version": "3.4.0",
+					"resolved": "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz",
+					"integrity": "sha512-HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==",
+					"dev": true
 				}
 			}
 		},
```

There are intended to be [checks for this](https://github.com/WordPress/gutenberg/blob/8aa3ad42034ebf7dbbe4412cb95c40e92a19a651/.travis.yml#L124-L132), though they have been sometimes unreliable in the Travis environment (often related to optional dependencies, see also https://github.com/WordPress/gutenberg/issues/16157#issuecomment-601187274 ).

Can you check a few things:

- Without changing anything about your setup, can you run `npm install` and check to see whether you see the same local changes?
- If so, can you commit them?
- If not, can you update your version of NPM and see if it makes any difference?
   - `npm i -g npm@latest`

Also related: #21306

**Comment by aduth** [comment]
Hm, after removing `node_modules`, I'm no longer able to reproduce the above local changes... 🤔

**Comment by aduth** [comment]
Strange as well, since this...

https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/package.json#L29-L50

Would seem to indicate that the specific portion of `package-lock.json` I was seeing changed in https://github.com/WordPress/gutenberg/pull/21258#pullrequestreview-385545526 (the `requires` of the `request` package) would be accurate.

**Comment by aduth** [comment]
I can reproduce fairly reliably that the changes are introduced when running `npm install` _twice_ (i.e. running `npm install` with `node_modules` folder already present). Not sure if this is a bug with `npm`. If you're able to reproduce as well, it may be safe enough to just commit those changes? As they seem like they are sensible anyways, per my previous comment.

Separately, we may not want to be using this `request` module anyways for `@wordpress/env`. I've left a related comment about this at https://github.com/WordPress/gutenberg/pull/20426/files#r401599042 .

**Comment by ockham** [comment]
> I can reproduce reliably that the changes are introduced when running `npm install` _twice_ (i.e. running `npm install` with `node_modules` folder already present). Not sure if this is a bug with `npm`. If you're able to reproduce as well, it may be safe enough to just commit those changes? As they seem like they are sensible anyways, per my previous comment.

I can reproduce, and they're the [same as yours](https://github.com/WordPress/gutenberg/pull/21258#pullrequestreview-385545526). Committed the diff as ddfe58668d.

**Review by aduth — APPROVED** [review]
Looks good 👍 Thanks

**Pull request merged**
