### PR TITLE
Color variables, update 4.6 to 4.5. One line code change typo fix. Easy.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

Noticed a tiny typo in a code comment in the base styles. It's 4.5:1 contrast ratio, not 4.6.

### CODE REVIEW

**Comment by t-hamano** [comment]
Against a white background, `#757575` appears to have a contrast ratio of `4.6.1` 🤔

https://webaim.org/resources/contrastchecker/?fcolor=757575&bcolor=FFFFFF

**Comment by jasmussen** [comment]
Right, and that's good, the fuller context of the change is that 4.5:1 is the _minimum_ contrast necessary for text, it's not 4.6. The fact that the value is higher is great. It exceeds the minimum. So I changed it to match the comment below, 3:1 UI contrast, which is techicallly 3.01:1, but 3:1 is the minimum.

**Comment by jameskoster** [comment]
Maybe it's worth being more explicit in the comment? It is a little ambiguous at the moment :)

**Comment by jasmussen** [comment]
Actually you all are right. I think I'll close this PR and instead update the new storybook documentation page!

**Pull request closed without merging**
