### PR TITLE
[RNMobile][Monorepo] Merge gutenberg-mobile and gutenberg master

### PR DESCRIPTION
**Pull request by ceyhun**
## Description

This is part of a migration effort of [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) to gutenberg repository with git history. More related PRs here: https://github.com/WordPress/gutenberg/pull/18508

This PR updates Monorepo branch with latest changes from `gutenberg-mobile/develop` and `gutenberg/master`

## How has this been tested?

- `npm run native start:reset`
- `npm run native test`
- `npm run native bundle:android`
- `npm run native bundle:ios`
- `npm run native android`
- `npm run native ios`
- `npm run lint`
- `npm run test-unit:native`
- Check android and ios apps running in simulators for any errors

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Tug** [comment]
Not sure how but running `npm install` did modify `package-lock.json`, could you check if it's in sync with package.json?

**Review by Tug — APPROVED** [review]
LGTM 👍

**Comment by noahtallen** [comment]
haha, I got kinda confused reading this PR, and then I realized that it is _not_ being merged into master. Otherwise I was about to be concerned about the commit history and files changed 🤦‍♂️

**Comment by ceyhun** [comment]
Sorry about that @noahtallen GitHub auto-requested reviews from everyone 😅 Updated the PR description. 
@gziolo maybe you can have a look to the few commits in the end I made to make this work.

**Comment by hypest** [comment]
Will now merge with "Allow merge commits" option ON.

**Comment by hypest** [comment]
Done.

**Pull request merged**
