### PR TITLE
Changelog automation: make Accessibility a top-level section

### PR DESCRIPTION
**Pull request by priethor**
## What?
Makes a top-level section for Accessibility so that all accessibility-related PRs are grouped there instead of being a subgroup within enhancements or bugfixes.

## Why?
This top-level section is currently done manually to give Accessibility the prominence it deserves in the changelog, so improving the automation makes sense.

## How?
By treating the `Accessibility (a11y)` label as a type mapping rather than as a feature mapping, with higher precedence than bugfix and enhancements labels. Test fixtures are updated, too.

## Testing Instructions
Run `npm run test:unit bin/plugin/commands/test/changelog.js`. There will be a top-level section (`### Accessibility` heading) containing two PRs, whereas before, they appeared under enhancements and bugfixes, respectively.

### CODE REVIEW

**Comment by ndiego** [comment]
Would it make sense to change the name of the label to `[Type] Accessibility (a11y)`? 

We are currently using the `[Type]` prefix for most other top-level categories. This would result in a11y issues/PRs often getting more than one "type", but so long as the `[Type] Accessibility (a11y)` takes precedence in the changelog, it should be fine.

**Comment by priethor** [comment]
> Would it make sense to change the name of the label to [Type] Accessibility (a11y)?

Indeed, I'm proposing that in [this discussion](https://github.com/WordPress/gutenberg/discussions/52727#discussioncomment-6477019). In any case, in order to enforce one and only one label of each type (regardless of their name, although I would add the `[Type]` prefix for consistency), I've tried adding an automated check in #52760

If/when we rename the labels, I can follow-up updating the changelog generation and the automation linked above to use the renamed labels 🙂

**Comment by priethor** [comment]
> Would it make sense to change the name of the label to [Type] Accessibility (a11y)?

Indeed, I'm proposing to add the prefix to the label in #52760, which adds automation to enforce all PRs have one and only one type-related label.

If/when we rename the labels, I can follow up by updating the changelog generation and the automation linked above to use the renamed labels 🙂

**Review by bph — APPROVED** [review]
LGTM - thanks for persisting

**Pull request merged**
