### PR TITLE
Fix to locations

### LINKED ISSUE #30330: Navigation screen: regression of improved menu locations select placeholder
# Description
The improved placeholder from https://github.com/WordPress/gutenberg/pull/29908 has regressed.

This change will need to be reimplemented.

## Step-by-step reproduction instructions
1. Open the nav screen
2. Select manage locations
3. View the locations menu select elements

## Expected behaviour
The improved placeholder is visible

## Actual behaviour
The improved placeholder is not visible, the feature has regressed.

### PR DESCRIPTION
**Pull request by Quintis1212**
new fix to "Navigation screen: regression of improved menu locations select placeholder #30330

Closes https://github.com/WordPress/gutenberg/issues/30330

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hi, @Quintis1212

Thanks for working on this PR.

Can you rebase the latest trunk on top of your branch to resolve conflicts? You can find more details about this Git workflow here - https://developer.wordpress.org/block-editor/contributors/code/git-workflow/#keeping-your-branch-up-to-date.

**Review by getdave — CHANGES_REQUESTED** [review]
The issue here is that part of the file you are editing [has moved to the `sidebar` directory](https://github.com/WordPress/gutenberg/blob/9efab2cbe695ff831c0c8b099b3193629c4989a7/packages/edit-navigation/src/components/sidebar/manage-locations.js#L99-L116).

I think your best move is to 

1. [Update your fork with the latest from Gutenberg](https://github.com/WordPress/gutenberg/pull/30933#issuecomment-837805780). Be sure to `git pull origin trunk` the latest `trunk` from your fork if you use @talldan's Github UI method.
2. Create a _new_ branch in your fork.
3. Redo your changes - they should be made [here](https://github.com/WordPress/gutenberg/blob/9efab2cbe695ff831c0c8b099b3193629c4989a7/packages/edit-navigation/src/components/sidebar/manage-locations.js#L99-L116).
4. Push this new branch up.
5. Close https://github.com/WordPress/gutenberg/pull/32423.

I think you're very close to getting this ready to merge 🤞 .

**Comment by getdave** [comment]
Hey @Quintis1212 👋 - is there anything I can do to help you get this merged? 

Current requirements to get this ready to merge are still https://github.com/WordPress/gutenberg/pull/32423#pullrequestreview-679655682.

Happy to sync up on Core WordPress Slack if that would help you to work through the necessary steps.

**Comment by getdave** [comment]
Hi @Quintis1212. It looks like perhaps you've been unable to find time to follow up here. No problem. If you're still interesting in working on this PR let me know, otherwise I'll take this over and spin up a PR which solves the issue.

Thanks again for contributing here 🙇

**Comment by getdave** [comment]
**Update**: I raised [a PR to supercede this one](https://github.com/WordPress/gutenberg/pull/33748) so I'm going to close it out.

**Pull request closed without merging**
