### PR TITLE
Update block registration function docs and signature.

### PR DESCRIPTION
**Pull request by mtias**
Be consistent about naming.

### CODE REVIEW

**Comment by aduth** [comment]
There were many more instances of "slug" terminology. We also use the same term for block categories and block controls documentation, which is outdated and should probably be removed/updated. I can see to this.

**Comment by mtias** [comment]
Thanks, i had to flee in the middle of fixing other cases.

**Comment by mtias** [comment]
Investigating issue with inserter.

**Comment by aduth** [comment]
There's quite a few "blockType" occurring in the [parser](https://github.com/WordPress/gutenberg/blob/master/blocks/api/parser.js). Should those be updated to "blockName"?

**Comment by aduth** [comment]
Rebased to resolve conflicts, squash, and update parser's "block type" (string) references to "block name".

**Review by youknowriad — APPROVED** [review]
Didn't find any block slug or wrong blockType reference. 👍

**Pull request merged**
