### PR TITLE
Components: Remove the feature flag for G2 components

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Follow-up for #28624.

This PR removes the feature flag `process.env.COMPONENT_SYSTEM_PHASE` that was added to avoid leaking G2 components into WordPress 5.7 release. Now that beta 1 should happen this week, we can get rid of this temporary solution and plan to roll out G2 components in Gutenberg at a larger scale. There are still two versions of the font size picker, but we should plan to remove the old implementation separately.

This PR also includes some clean-up tasks marked in #28624:
- removes unused TS types
- improves where TS checks are enabled
- exposes `FontSizeControl` from `@wordpress/components/ui` that is useful for experiments

## How has this been tested?

I tested in WordPress and Storybook that the font size picker still works.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! Tested well locally and code looks good. Thanks!

**Comment by gziolo** [comment]
This PR is blocked until Component System is officially accepted for inclusion in the WordPress core.

**Comment by gziolo** [comment]
@sarayourfriend, do we still need it or can I close it?

**Comment by sarayourfriend** [comment]
I'm not sure. My gut says we should close this and revisit it at a later date. The current integration plan #30503 says that we'll remove all the `next` files that check this variable. Perhaps we should remove it then?

**Comment by gziolo** [comment]
Sure, we can always reopen but it feels like we will get there in a different way 😄

**Pull request closed without merging**
