### PR TITLE
Apply borders to canvas rather than other UI elements

### PR DESCRIPTION
**Pull request by jameskoster**
This is a potential follow-up to https://github.com/WordPress/gutenberg/pull/31044.

In order to create an outline around the editor canvas, a thin gray border is applied to the top bar, the inspector, and the breadcrumb bar. Highlighted red in the image below:

Screenshot 2021-04-22 at 11 57 35

Since https://github.com/WordPress/gutenberg/pull/30658 was merged, engaging the template editor insets the canvas and exposes the "frame" upon which it sits. The result is effectively a double border – one around the canvas, and one around the frame. Highlighted red once again:

Screenshot 2021-04-22 at 12 07 09

This can be problematic when the frame has a dark background like the one proposed in #31044 as unnecessary visual noise is created between the dark gray and white areas separated by a light gray line:

Screenshot 2021-04-22 at 11 21 27

This PR explores removing the borders applied to the top bar, inspector, and breadcrumb. Instead a single outline is applied to the canvas, which achieves the same visual effect when editing a post, but removes aforementioned visual noise when you transition to editing a template. Here's a gif to demonstrate, once again red is used to higlight the change:

outline

### CODE REVIEW

**Comment by shaunandrews** [comment]
I believe this is why I see a single pixel line down the right-side — but not the left-side — of the editor on my website:

image


I would absolute love for this to be fixed.

**Comment by shaunandrews** [comment]
Just glancing at the changes, I believe this PR will do what I expect. However, I think it needs a rebase. I'm unable to get it running in my local dev environment.

**Comment by jameskoster** [comment]
Give it a try now.

**Review by shaunandrews — APPROVED** [review]
Does what it says. I'd be interested in seeing a follow up that considers using `rgba` or adjusting the color based on the document's background color. The fixed `#ddd` color tends to clash with dark background colors.

**Comment by jasmussen** [comment]
In testing this, I'm having a hard time seeing a difference. Could be an environment thing, but it looks the same to me. But it also works fine for me, so seems okay to land.

Though I'd ask you to change `#ddd` to `$gray-300` as we have that one handy for the purpose :)

**Comment by jameskoster** [comment]
Ah, css vars in .js files is something I haven't figured out how to do just yet :D

**Comment by jasmussen** [comment]
Oh right, I missed that piece. Go for it.

**Comment by talldan** [comment]
I'm seeing the editor header has no border in `trunk`, not sure if it's from this change, but it was the closest match I found from looking at recent commits:
Screenshot 2021-11-05 at 7 27 18 pm

**Comment by jameskoster** [comment]
Yeah something isn't right here. I'll work on a fix.

**Pull request merged**
