### PR TITLE
Block fixtures: Change port to 8889 to placate KSES

### PR DESCRIPTION
**Pull request by ockham**
## Description

Unit tests are currently failing on `trunk` (when used with a current snapshot of the WordPress svn or git repo).

Specifically: `Block_Fixture_Test::test_kses_doesnt_change_fixtures` fails for datasets #54 and #55.

Reading https://github.com/WordPress/wordpress-develop/pull/1998, I believe that the reason might be that our KSES routines are verifying that the specified port matches the one of the local install. And since our tests normally run `localhost:8889`, I'm updating the relevant test fixtures (from previously `8888`) to reflect that.

## How has this been tested?
Verify that CI goes green 🤞 

## Types of changes
Bug fix

### CODE REVIEW

**Comment by gziolo** [comment]
The unit tests runner handles those integrations tests and it has the following URL configured:

https://github.com/WordPress/gutenberg/blob/d2f0c66c3e10e5c0c7aa7f1480506a6d0c1e3ba6/test/unit/jest.config.js#L24

**Comment by ockham** [comment]
Thanks @gziolo. The PR does seem to fix the fixture errors tho (although there's an unrelated error that's still present) -- compare e.g. https://github.com/WordPress/gutenberg/runs/4408490770?check_suite_focus=true (current `trunk`) to https://github.com/WordPress/gutenberg/runs/4408762944?check_suite_focus=true (this PR).

Curious to hear your suggestion -- are you saying you'd rather remove the port altogether from the fixtures? Or is it okay to go ahead with this fix as-is?

**Review by gziolo — APPROVED** [review]
You applied the changes correctly 👍 The same test fixtures are also used with PHPUnit, so it'd be the reason why it needs the same port. It probably is less critical for unit tests, but maybe we should align that separately from this PR.

I got confused because of the location of fixtures 🙈

**Comment by ockham** [comment]
Thanks @gziolo -- I'll go ahead and merge 😄 

---

FWIW, the remaining PHP unit test that's failing

```
1) WP_REST_URL_Details_Controller_Test::test_will_return_from_cache_if_populated
Failed asserting that 'Example Website — - with encoded content.' contains "This value from cache".

/var/www/html/wp-content/plugins/gutenberg/phpunit/class-wp-rest-url-details-controller-test.php:302
```

is probably due to https://github.com/WordPress/wordpress-develop/commit/1270c897a9b9e9f0cd5baa765676ea15a9a13399 (committed today at 11:34 UTC): I noticed it wasn't present on `trunk` for https://github.com/WordPress/gutenberg/runs/4407241926?check_suite_focus=true (at 11:15 UTC) but for the following merge https://github.com/WordPress/gutenberg/runs/4408138725?check_suite_focus=true (at 12:51 UTC), and it touches `src/wp-includes/rest-api/endpoints/class-wp-rest-url-details-controller.php` which seems relevant to the error 😬 

cc/ @audrasjb

**Comment by ramonjd** [comment]
Thanks for looking at this @ockham !

**Comment by ockham** [comment]
> FWIW, the remaining PHP unit test that's failing
> 
> ```
> 1) WP_REST_URL_Details_Controller_Test::test_will_return_from_cache_if_populated
> Failed asserting that 'Example Website — - with encoded content.' contains "This value from cache".
> 
> /var/www/html/wp-content/plugins/gutenberg/phpunit/class-wp-rest-url-details-controller-test.php:302
> ```
> [...]

Filed an issue for this: https://github.com/WordPress/gutenberg/issues/37116

**Pull request merged**
