### PR TITLE
Add Animoto, Dailymotion block embed icons

### PR DESCRIPTION
**Pull request by enriquesanchez**
This PR adds a couple missing embed block icons (Animoto and Dailymotion), partly addressing #9124. I don't intend to add all of the missing icons here, to avoid it going stale.

Screen Shot 2020-04-24 at 17 09 38

### CODE REVIEW

**Review by earnjam — APPROVED** [review]
LGTM 👍 

image

**Comment by earnjam** [comment]
Build fails are because of linting errors in the svgs being exported. Feels a little unnecessary, but they're getting tripped up because there are multiple attributes on the `<Path>` elements, so it wants them to be split out so each attribute is on it's own line. 

The Dailymotion one could probably be done with `foreground` like the other icons, but the Animoto icon has multiple colors (looks like the first one of these with more than one color), so it has to have colors on each path.

**Comment by enriquesanchez** [comment]
Thank you for the fix and the review, @earnjam! 🙏

**Comment by carolinan** [comment]
And has the license and terms of these logos been checked?

**Comment by earnjam** [comment]
Good thought @carolinan. Many tech companies allow usage of their logos within apps and websites and will have brand usage guidelines to clarify their rules (Facebook, Twitter, Spotify, Vimeo, etc all have great documentation for this). 

I did a quick check on the two sites included in this PR. 
Animoto didn't have specific brand guidelines, but [their Terms and Conditions](https://animoto.com/legal/terms) had a section about Intellectual Property. It's only limitation on marks was this:
> Animoto's trademarks and/or service marks may not be used in connection with any product or service that is not provided by Animoto, in any manner that is likely to cause confusion among customers or users of the site, tarnishes or dilutes the marks, or disparages or discredits Animoto

It's likely ok, but there are some grammar errors in that run-on sentence that make it murky.
 
Dailymotion has this in their API terms: 
> In order to use Dailymotion’s trade names, trademarks, service marks, logos, domain names (the “Dailymotion Marks”) for any purpose whatsoever, including to promote your Developer API Product(s), you must first receive written approval from Dailymotion, which may be given via email. 

I'm not sure how well that would hold up where even displaying the company name for any purpose is prohibited without written authorization. By those terms we can't even have the embed block at all without asking them first. But we still want to make sure we're working with these companies and using logos according to their preferences and allowances. 

Unless they have usage terms clearly spelled out online (like the ones I mentioned earlier), we probably do need to be reaching out to all platforms for which we want to bundle logos to get written confirmation. I don't imagine any would say no, but it's the safe practice.

**Comment by carolinan** [comment]
It is also about whether the icons have been created by the team, or downloaded from a third party site.
See https://github.com/WordPress/gutenberg/pull/21900#issuecomment-620475070

**Comment by earnjam** [comment]
Reading further in that thread, I think [the legal perspective from Paul](https://github.com/WordPress/gutenberg/pull/21900#issuecomment-624307120) clears it up that it's fine to use the logos. Seems the only concern would be plucking some custom asset from a non-GPL icon library.

**Pull request merged**
