### PR TITLE
Classic editor block: Remove old back-compat code

### PR DESCRIPTION
**Pull request by Soean**
## Description
This PR removes old back-compat code for WP 4.9 from the classic block.
Added in #10964

@azaozz Can you confirm, we can remove it?

### CODE REVIEW

**Comment by azaozz** [comment]
Yes, not needed any more.

**Comment by azaozz** [comment]
Also this but doesn't seem needed: ref={ ( ref ) => ( this.ref = ref ) }.
(Can't comment inline in the code :( Was that always the case?).

**Comment by Soean** [comment]
Thanks, I also removed this line.

**Comment by ZebulanStanphill** [comment]
#25365 ended up resolving this.

**Pull request closed without merging**
