### PR TITLE
Navigation Editor - Enable save button when change made + add indicators to changed elements

### LINKED ISSUE #30391: Navigation Editor - Detect unsaved changes, and only enable the save button when there are unsaved changes
## What problem does this address?

In order to better handle https://github.com/WordPress/gutenberg/issues/30322 let's divide it into separate issues, each with a corresponding PR.

Currently, the way a user saves their changes is confusing.  Options in the navbar are saved with a save button placed in the header. Moreover, there is no visible clue, helping a user to understand they need to hit the save button to save their changes (to inform, that the changes are not saved immediately). 

## What is your proposed solution?

As described by @shaunandrews the desirable solution is to
- add a dot to every element that has been changed and unsaved (solution similar to  site editor) with a tooltip
- add a save button in the navbar which will be
      - disabled as long as no change is made
      - have a tooltip explaining why it's disabled
      - when enabled, having a dot to indicate it will save elements marked with dots

113044880-2816a400-916c-11eb-9732-64858da545f7

### PR DESCRIPTION
**Pull request by grzim**
## Description

Advances https://github.com/WordPress/gutenberg/issues/30322
Closes https://github.com/WordPress/gutenberg/issues/30391

This PR aims to bring the functionality of enabling the save button only when there are unsaved changes. Also, visible indicators are added to inform users which elements are unsaved.

I have added a mechanism that traces the changes, thanks to which it will be easier to implement https://github.com/WordPress/gutenberg/issues/30423 with information which data is unsaved and will be lost.

Add new pages is not yet saved on `save` button - there is a separate issue for this https://github.com/WordPress/gutenberg/issues/30425

Currently, the dot indicator appears next to `Name` label and not inside the input,
when it comes to Theme location, if a user makes any change the dot will appear next to the first checkbox.

In order to move the dot inside the input, then we would need to style it in a brutal way, placing it absolutely from a container containing entire TextControl elements (or with float, which would be an even worse solution). This would be not a future-proof solution and I don't like it. 
Alternatively, we can make a change inside a TextControl component, so the dot can be styled there.
This change can be added in a separate PR.

If we would like to make changes inside components, we would be also capable of adding dot indicator for each theme location checkbox separately. Without changing ChexbkoxControl the only way is to add a dot as a Header (see issue: https://github.com/WordPress/gutenberg/pull/30037) but it will move the entire Checkbox to the right what would look weird.

There is an issue with a `Tooltip` element - when it is added to a disabled button it adds `,` at the end also makes a button clickable. I have added [issue](https://github.com/WordPress/gutenberg/issues/30422) about this and will also investigate it soon.

## How has this been tested?

1. Navigate to Navigation Editor
2. Select menu (or create one)
3. Make any change in the navbar
4. See the button changes from disabled to enabled and dot indicators are shown in places where a change has been made

## Screenshots 
image

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
@grzim This seems like a lot in one go, and I think we could start even smaller by making sure we're getting the code by that's used to detect unsaved changes absolutely right as a first step and use that to enabled/disable the save button as needed. This is a tried/tested pattern, so it should be easy to ship, and will be a nice win for users.

The changes to individual controls are a lot more involved, so while I think it looks like a great feature, being pragmatic I think it can be a separate PR, because it'll naturally take a lot of dev/design iteration and review to get right.

So going back to how we can detect unsaved changes, I notice this PR mostly tries to implement a completely new way of doing this. I wouldn't have thought that would be needed though, this is a solved problem in other editors, so we should take a look at what the implementation is in those editors and replicate that.

**Comment by grzim** [comment]
As discussed with @talldan it will be better to rely on `wp.data.select( ‘core’ ).getEntityRecordEdits` and `navigationPost`

**Comment by grzim** [comment]
@shaunandrews - I believe we should get rid of dots. Should we notify a user in any other way that certain data is unsaved or just leave the enabled/disabled button as an indicator?

**Comment by shaunandrews** [comment]
> just leave the enabled/disabled button as an indicator

Lets start with this and see how it works for people. We can always add more/better indicators if we find they're needed.

**Comment by getdave** [comment]
@talldan Can this be [closed in favour of what you suggested](https://github.com/WordPress/gutenberg/pull/30420#issuecomment-811626238)?:

1. Breaking the task down into smaller PRs?
2. Utilising existing unsaved changes detection?

**Comment by talldan** [comment]
> @talldan Can this be closed in favour of what you suggested?:

@getdave Yep, sounds good to me.

**Pull request closed without merging**
