### PR TITLE
add isPrivate to block-api docs

### PR DESCRIPTION
**Pull request by ajitbohra**
## Description
Add isPrivate to the block-api docs

Fixes #6565 

## Types of changes
Documentation

### CODE REVIEW

**Comment by aduth** [comment]
Noting that #6346 plans to deprecate this property. (cc @noisysocks)

**Comment by ajitbohra** [comment]
@aduth thanks for sharing the info seems like missed the `isPrivate` depreciation plan. 
I guess in that case we can keep this on hold or close this for now.

**Comment by noisysocks** [comment]
Yes, let's hold off on this for now.

**Comment by gziolo** [comment]
Yes, it should never be exposed as is.

**Comment by Soean** [comment]
#6766 Removes the inPrivate property in lieu of a supports flag.

**Pull request closed without merging**
