### PR TITLE
Respect PHP WordPress core coding standards

### LINKED ISSUE #21891: Bring the coding standards for the PHP implementation of the block parser up to scratch
The [file that contains the PHP implementation of the block parser](https://github.com/WordPress/gutenberg/blob/98ae84a1bfa4b2c453a29ff71e5f184707df3ef1/packages/block-serialization-default-parser/parser.php) does not conform to WordPress core's coding standards (for example, it includes multiple class declarations in one file), therefore [its corresponding file in core](https://github.com/WordPress/wordpress-develop/blob/59433bb3062ad833812a293c0f2255b2d914ad30/src/wp-includes/class-wp-block-parser.php) has to be [excluded from the coding standards checks](https://github.com/WordPress/wordpress-develop/blob/59433bb3062ad833812a293c0f2255b2d914ad30/phpcs.xml.dist#L121) because of its low quality.

This file should be brought up to core coding standards which will allow the coding standards exclusion to be removed from core.

### PR DESCRIPTION
**Pull request by manooweb**
Fixes #21891 

The goal is that parser.php file follows the WordPress coding standards.

So I renamed parser.php file to class-wp-block-parser.php as it is named in WordPress core and I kept only the WP_Block_Parser class.
I referenced it in test-parser.php.

I respectively splited the 2 other classes WP_Block_Parser_Block and WP_Block_Parser_Frame in their own file class-wp-block-parser-block.php and class-wp-block-parser-frame.php.

I also removed the coding standards exclusion rules https://github.com/WordPress/gutenberg/blob/master/phpcs.xml.dist#L78-L90 and made modifications to respect coding standards.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
[I added context on the linked issue](https://github.com/WordPress/gutenberg/issues/21891#issuecomment-626324945), but it's worth noting that ignoring the coding standards was implemented intentionally, because this class was written to align closely with the JavaScript implementation, which has different coding standards.

Consequently I'm not sure we do actually want to make any of these changes, but perhaps documenting them would help future developers understand why the rules were ignored here (or, perhaps more accurately, why we chose not to follow those rules).

**Comment by manooweb** [comment]
First, I'm sorry for the mistakes and because I didn't respect the contributing guide espacially about testing https://developer.wordpress.org/block-editor/contributors/develop/testing-overview/

And I'm sorry I pushed this PR too soon. However it was interesting because I never would have guess what test I had to run for these modifications.

So, I think it's a good first issue 😁 to better know about the code contribution workflow.

Second, I don't really agree about not to respect PHP coding standards. As long as Gutenberg was a feature plugin we could decide not to respect them. But now, because this part of code is integrated in the WordPress core, it should respect them.

It is not difficult to understand  a JS variable name corresponds on a PHP variable name if both of them are close. For example innerBlocks and inner_blocks.
Note that here it isn't consistent https://github.com/WordPress/gutenberg/blob/master/packages/block-serialization-default-parser/parser.php#L83-L89

My main difficulties is to understand how to modify the unit test shared with block-serialization-spec-parser. https://github.com/WordPress/gutenberg/blob/master/packages/block-serialization-spec-parser/shared-tests.js 

Thank you for the guidance. We can close this PR and continue the discussion in the linked issue #21891 
I could propose another PR later after we decided what to do 😊👍

**Comment by chrisvanpatten** [comment]
@manooweb Of course — it's so great to have the learning experience of opening the PR and all that! I think with the parser there are some nuances that we actually have a lot of benefits from keeping the code as similar as possible with JavaScript because historically, this type of parsing has been prone to bugs and issues (see the historical issues around shortcode parsing). Since the "canonical" version of the parser is JavaScript, it helps translate between them a little easier. But agreed that it's a conversation best had on the issue :) Thanks so much for the contribution and please don't be deterred from future PRs!

**Comment by dmsnell** [comment]
Thanks for the poke @chrisvanpatten - I responded in the linked issue #21891. Thanks for your contribution @manooweb! I wish this were a clearer issue for me to understand.

**Review by spacedmonkey — APPROVED** [review]

**Comment by aristath** [comment]
Closing this one, as it has already been implemented in another PR 👍

**Pull request closed without merging**
