### PR TITLE
Cherry-pick PRs for the WordPress 6.1 Beta 3 Release

### PR DESCRIPTION
**Pull request by michalczaplinski**
This PR has all the cherry-picked PRs that need to be merged into the `wp/6.1` branch (note the PR base) for the WordPress 6.1 Beta 3 release.

#### These were cleanly cherry-picked by the script:
   ✅  cherry-pick commit: eb2ded5504  for PR: #44634 – Quote block: stop slash insert...
   ✅  cherry-pick commit: 9d1fe960a2  for PR: #44630 – Query Loop: Fix condition for ...
   ✅  cherry-pick commit: 7e9fd398d0  for PR: #44554 – Hide the Classic block in the ...
   ✅  cherry-pick commit: 1bbc3ab401  for PR: #44594 – Fix navigation block console e...
   ✅  cherry-pick commit: 50bb90d156  for PR: #44555 – Theme export: Fix broken spaci...
   ✅  cherry-pick commit: 2159bbb9c1  for PR: #44580 – Code Block: Add box-sizing to ...
   ✅  cherry-pick commit: 14d650026d  for PR: #44556 – Remove border from Global Styl...
   ✅  cherry-pick commit: ad37bdd3c1  for PR: #44141 – Spacing presets: Modify the st...
   ✅  cherry-pick commit: 4a0fbe0222  for PR: #44453 – [TypeScript] Preserve the gene...
   ✅  cherry-pick commit: 4b92996290  for PR: #44504 – Theme.json: fix some outline p...
   ✅  cherry-pick commit: af3f84e500  for PR: #44516 – Add style-engine to gutenberg ...
   ✅  cherry-pick commit: 9aaf066644  for PR: #44523 – [Block Library - Query Loop]: ...
   ✅  cherry-pick commit: a3e9d0a800  for PR: #44520 – PostFeaturedImage: Fix applica...
   ✅  cherry-pick commit: 32de2fb42b  for PR: #44286 – Post Featured Image: Fix borde...
   ✅  cherry-pick commit: 61a1bc2bbe  for PR: #44482 – Template editor: fix crashes d...
   ✅  cherry-pick commit: add234f03d  for PR: #44480 – Template part: prevent adding ...
   ✅  cherry-pick commit: 33f9e9f1e1  for PR: #44425 – Fix rotated image crop area as...
   ✅  cherry-pick commit: 1876d24756  for PR: #44485 – Fix padding/margin visualizer ...

#### Those I had to cherry-pick manually because they contained some merge conflicts:
   #44569 – 0c807b34bf83a845599e – Theme.json: fix some shadow pr...
   #44575 – b06eac064c2dc451f7fd – ToggleGroupControl: fix unsele...
   #44526 – 1f4e508276f7c6604b1e – TokenInput field: try alternat...
   #44506 – 4a4d110f174f6af72933 – Edit Post: Optimize legacy pos...
   #44258 – cf0b87ad2e0893324ee3 – Add layout styles from Post Co...

### CODE REVIEW

**Comment by michalczaplinski** [comment]
For additional context: 

I have tried using the npm script `npm run other:cherry-pick "Backport to WP Beta/RC"` to automate the job of cherry-picking the PRs, removing the labels and pushing it to github but it appears that it only works for contributors that are members of the [Gutenberg Core](https://github.com/orgs/WordPress/teams/gutenberg-core) github team.

**Review by tellthemachines — COMMENTED** [review]
Changes from #44258 and #44506 are looking good! ✅ 

> Those I had to cherry-pick manually because they contained some merge conflicts

This is painful when it happens! I've found the best way to avoid it is to make sure to cherry-pick the commits in the same order as they were merged to trunk. Unfortunately, GH doesn't seem to have a way to order the PRs by date merged, and date of the last change to the PR is not always reliable as comments etc. also count as changes, so with a big list of PRs it can take some time to get them in order 😅 

(You can also do something like `git rev-list [commit A] | grep $(git rev-parse [commit B])` to check if a certain commit is an ancestor of another but that will probably take even longer than looking through the PR history on GH.)

**Comment by t-hamano** [comment]
I have built and tested this PR and it works correctly for #44504 and #44569 🚀

**Comment by ockham** [comment]
Thank you @michalczaplinski for the PR, and @tellthemachines and @t-hamano for testing!

I think I'll merge this PR soon so I can publish the next round of npms and get the sync PR for `wordpress-develop` ready in time for today's WP 6.1 Beta 3 -- basically to prep for the "happy path".

I'd still like to run the list of cherry-picked PRs (see PR description) by Core folks: @dream-encode @hellofromtonya @audrasjb @desrosj. If y'all disagree with any of those, please LMK -- we'll then revert them and do another round of npms and a new sync PR.

**Comment by ockham** [comment]
I think I'll use "Rebase and merge" to make it easier to revert individual commits (compared to "Squash and merge").

**Pull request merged**
