### PR TITLE
Fix some more multi select issues

### PR DESCRIPTION
**Pull request by ellatrix**
* Make sure `lastClientY` is always accurate.
* `selectionAtStart` should be sync. set (has nothing to do with rendering the component).
* Throttled `onPointerMove` calls should be cancelled on ending the selection, not when the component unmounts.

### CODE REVIEW

**Comment by iseulde** [comment]
If there are no objections, I'm going to merge soon.

**Comment by youknowriad** [comment]
I'm taking a quick look :)

**Comment by youknowriad** [comment]
floated multi select

This is the bug I was talking about. It is still present here. Sometimes I move the cursor slightly when I click and it triggers multiselection because the block is floated.

I guess this is harder to fix because we need to delete overlapping blocks.

Feel free to merge this without it, it could be separate.

**Comment by iseulde** [comment]
@youknowriad Ah, I see! This one definitely also fixes a bug, but it also happens without floating. I can reproduce your issue now too. I'll try to fix in a separate PR.

**Pull request merged**
