### PR TITLE
Add Spinner component to Storybook

### PR DESCRIPTION
**Pull request by brentswisher**
## Description
Add Storyboard integration for the spinner component, part of #17973

## How has this been tested?
run `npm run design-system:dev`
Browse to the local Storybook instance
See Spinner component is rendered when selected in the left-hand navigation

## Types of changes
New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Nice, thank you for adding Spinner to Storybook. 

Unrelated to this PR. I tested on my mobile device. Does it also align to top-right on the desktop viewport as well? I would expect it is not positioned at all and this right aligned rather.

**Comment by brentswisher** [comment]
Thank you for the review, it does align top right on the desktop. It was unexpected to me as well, but I checked the CSS and it was clearly intentional. It might not be a bad idea to track down the instances it is used and see if that is actually needed - it seems like an odd default style to me. If I get a chance later this week I will try to do that and open a follow-up issue if needed.

**Comment by gziolo** [comment]
> it does align top right on the desktop. It was unexpected to me as well, but I checked the CSS and it was clearly intentional.

@mapk or @jasmussen - is it intentional that the spinner aligns to the top right of the area occupied?

@ItsJonQ - what would be the best way to track all issues with existing components where they don't have good enough defaults?

**Comment by jasmussen** [comment]
> is it intentional that the spinner aligns to the top right of the area occupied?

Can you clarify a bit what it means to align to the top right area occupied? When I look at https://wordpress.github.io/gutenberg/design-system/components/?path=/story/spinner--default it's clearly in the top right corner, sure.

Without full clarity, the following are mostly meta thoughts:

- For the _component_, I imagine that it will probably be used in a great variety of contexts, and so the implementer will likely do most of the alignment. 
- By _default_, if the implementer does nothing, I would _imagine_ that the spinner should be centered. However also vertically, which presents quite an implementation challenge at times.

Based on the above, I would assume a spinner component should be born with no alignment CSS at all, and that the context in which the component is used should provide the alignment. 

Is that helpful?

**Comment by gziolo** [comment]
> Based on the above, I would assume a spinner component should be born with no alignment CSS at all, and that the context in which the component is used should provide the alignment.

I would assume the same as a person who would like to consume this component. It looks like we have a good idea for the follow-up task 👍

**Comment by ItsJonQ** [comment]
@gziolo Not yet. But I would love to have something!~ That would be helpful :)!!

I chatted to @karmatosed about this yesterday. We're gonna try to set up something

**Comment by brentswisher** [comment]
I opened issue #18199 so we can track this, I think it will just need to have the float removed from the component and then check each implementation to see if it still looks correct and fix any that are different.

**Pull request merged**
