### PR TITLE
Add more placeholders

### PR DESCRIPTION
**Pull request by ellatrix**
This PR adds placeholders to some blocks that don't currently have one, and formats them in the same way.

It also fixes a bug where styles would be messed up if there is no placeholder. To test that, make sure list and table works fine.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice!

Not sure if it's an issue with this branch, but I noticed a few issues with the text block now. The block boundary doesn't expand on single enter:

screen shot 2017-06-27 at 12 04 49

Also, it's only on text block _deselect_ that a text placeholder appears, it doesn't appear just on double enter:

screen shot 2017-06-27 at 12 05 07

**Comment by iseulde** [comment]
@jasmussen Can reproduce the first issue for a new post, but this seems to have been an issue for a while. The second one I can't reproduce. Placeholder shows fine on double enter...

**Comment by jasmussen** [comment]
Alright I'll ticket the first one. Thanks.

**Comment by iseulde** [comment]
If there are no concerns, I'll merge this soon.

**Pull request merged**
