### PR TITLE
Paste shortcodes

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
This PR adds support for pasting shortcodes, starting with the caption and gallery shortcode.

## How Has This Been Tested?
Create an "old" post and insert a single image (e.g. thumbnail, right aligned) with a caption. Verify that the text mode contains a shortcode. Go back to visual mode and select everything (maybe include a paragraph). Paste it in Gutenberg. There should be an image block, with the caption, correctly aligned.

To do:
* Find a way to support formatted captions.

### CODE REVIEW

**Comment by aduth** [comment]
>shortcakes

Mmm... shortcake.

[Shortcake](https://wordpress.org/plugins/shortcode-ui/) on the mind? 😄

**Comment by iseulde** [comment]
🙈 Autocorrect, continuously have to undo it. Added it to the dictionary now.

**Comment by iseulde** [comment]
Maybe this is not an appropriate PR to add support for gallery as well, since he block would need to support initialisation with IDs only, and it seems `APIDataComponent` does not support nested routes (yet).

**Comment by aduth** [comment]
>and it seems `APIDataComponent` does not support nested routes (yet).

Can you elaborate on what's not supported?

**Comment by iseulde** [comment]
@aduth Unless I'm missing something, the following won't work:

```js
withAPIData( ( props ) => {
	const { images } = props.attributes;

	return {
		images: images.map( ( image ) => {
			return image.id ? `/wp/v2/media/${ image.id }` : image;
		} ),
	};
} ),
```

**Comment by aduth** [comment]
Correct. We could potentially make a separate component responsible only for displaying a single image, then `withAPIData` only needs to request one entity.

**Comment by youknowriad** [comment]
@iseulde can't you do something like ?

```js
withAPIData( ( props ) => {
	const { images } = props.attributes;

	return images.reduce( ( memo, image, index ) => {
		memo[ 'image-' + image.id ] = `/wp/v2/media/${ image.id }`;
		return memo;
	}, {} );
} ),
```

**Comment by iseulde** [comment]
Went with @aduth's suggestion.

**Comment by iseulde** [comment]
Going to request an initial review. I'm not quite sure how we can get the formatting form the caption with the current hpq matchers, so leaving that out for now.

**Comment by mkaz** [comment]
I tested this using Firefox on Linux and it did not quite work as expected.

1. Selecting image and caption from old post and paste in new, it does create an image block - but the caption is not included as a caption part of the image block but a text below

image-caption-paste

2. Testing again with selecting a paragraph below and pasting ended up without the caption shortcode being parses out, it was created as a separate block.

image-caption-paste2

**Comment by iseulde** [comment]
@mkaz Thanks for testing. Do you see any errors in the console? What is it logging for paste? I tried to reproduce this in Firefox, but it works perfectly fine.

**Comment by mkaz** [comment]
Console Log:

```
          Received HTML:

 [caption id="attachment_114" align="alignnone" width="300"]<img class="size-medium wp-image-114" src="http://wpdev.local/wp-content/uploads/2017/09/image-2-300x219.png" alt="" width="300" height="219" /> Mike Tomlin[/caption]<p>Pittsburgh Steeler Coach</p>  index.js:6:7652
Received plain text:

     Mike Tomlin

Pittsburgh Steeler Coach  index.js:6:7703
Processed HTML piece:

 <p>[caption id="attachment_114" align="alignnone" width="300"]</p><img src="http://wpdev.local/wp-content/uploads/2017/09/image-2-300x219.png" alt=""><p> Mike Tomlin[/caption]</p><p>Pittsburgh Steeler Coach</p>
```

**Comment by mkaz** [comment]
For the copy-paste test that only includes caption and photo. The raw HTML view of the post looks like this:
```
[caption id="attachment_114" align="alignnone" width="300"]<img class="size-medium wp-image-114" src="http://wpdev.local/wp-content/uploads/2017/09/image-2-300x219.png" alt="" width="300" height="219" /> Mike Tomlin[/caption]
```

When I copy and paste, the console log results:
```
Received HTML:

 <img class="size-medium wp-image-114" src="http://wpdev.local/wp-content/uploads/2017/09/image-2-300x219.png" alt="" width="300" height="219" />Mike Tomlin  index.js:6:7652

Received plain text:

     Mike Tomlin  index.js:6:7703
Processed HTML piece:

 <img src="http://wpdev.local/wp-content/uploads/2017/09/image-2-300x219.png" alt=""><p>Mike Tomlin</p>
```

**Comment by iseulde** [comment]
Coming back to this, I'm not sure what's going on. Everything works fine for me here in different browsers. Can anyone else reproduce?

**Comment by mkaz** [comment]
I've retested again and can not reproduce the same as above. Tried in a couple different browsers too, (Firefox, Safari, Chrome) though Firefox version upgraded to new 57 (beta).

It is now all working as expected, pasting of caption shortcode comes in as image block, both with/without surrounding paragraph text. 

:+1:

**Review by mkaz — APPROVED** [review]
Comment already added - retested and looks good

**Pull request merged**
