### PR TITLE
Visually hide 'Actions' column header

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Visually hide the 'Actions' column header in data views table layout.

## Why?
We can reduce some visual clutter in the top-right corner of the UI. 

Unlike other column headers the 'Actions' `th` doesn't surface a menu on click, you can also argue that the items in this column are quite clearly actions, so the heading doesn't add a lot of value.

The text is only hidden visually, so will still be announced by screen readers.

| Before | After |
| --- | --- |
| Screenshot 2024-05-16 at 10 38 10 | Screenshot 2024-05-16 at 10 37 20 |

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Can wait to land this until it's been given a gut-check by others, but wfm.

**Review by t-hamano — COMMENTED** [review]
I believe this change should not cause any issues with accessibility.

One question, is `<span className="dataviews-view-table-header">` still necessary? This class seems to [add a small left padding](https://github.com/WordPress/gutenberg/blob/28847b04ce121fd333ee364a6525d2ca7f969e10/packages/dataviews/src/style.scss#L224-L226), but the text is no longer visually present. If it is not needed, we may want to remove this span tag.

**Comment by jameskoster** [comment]
Good point, the `span` can be removed.

**Review by t-hamano — APPROVED** [review]
LGTM 🚀

**Comment by afercia** [comment]
> I believe this change should not cause any issues with accessibility.

Accessibility is not just about screen readers. This change goes in the opposite direction of some accessibility feedback previously reported on this old issue: https://github.com/WordPress/gutenberg/issues/42505. A visible table header helps all users e.g. low vision users to draw their attention and identify the Actions column. The ellipsis button within the column is so thin that is hard to be seen for low vision users. A visible table header definitely helps.
Also, I'd argue that using a table markup _and_ visually hiding the table headers defeats the purpose of using a table in the first place. I'm not sure I can support this kind of approach to design. 'Reducing clutter' is a very subjective perspective and should never get prioritized over semantics and functionality.
I'll submit a quick PR to propose to revert this change.

**Pull request merged**
