### PR TITLE
Mobile - Buttons block - Update block appender logic

### PR DESCRIPTION
**Pull request by geriux**
`Gutenberg Mobile PR` -> https://github.com/wordpress-mobile/gutenberg-mobile/pull/2459

## Description
While testing the [Copy / Cut / Paste / Duplicate feature](https://github.com/WordPress/gutenberg/pull/23110), it was found that after "Cutting" the Button within the Buttons block a couple of times and then adding new ones they'd start duplicating.

I updated the logic of the Buttons appender to use the same one as the menu inserter.

## How has this been tested?
- Start the demo app with metro running
- Add a Buttons block
- "Cut" the Button block that's within.
- Tap on the Buttons block (it's hard to see when there aren't any Buttons inside, another issue will fix this)
- Tap on the + button within the block
- **Expect** to see an empty button
- "Cut" the Button again
- Tap on the + button within the Buttons block
- **Expect** to see an empty button (without duplicates)

## Screenshots 

Before | After
-|-
 | 

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by lukewalczak — APPROVED** [review]
Tested on both platforms and works properly, thanks @geriux 🎉 !

**Comment by lukewalczak** [comment]
Two things which would like to note: 
1. After cutting the last button from buttons there is a space on the left from the button which looks _odd_, I had the same problem with social icons and created a [fix](https://github.com/WordPress/gutenberg/pull/23017/files#diff-260b0f5b413f5ac735a6935b2f8acc34R387-R389) within my PR. Maybe we can introduce that change with your PR (prolly it will be merged earlier than my PR)

2. I think that we should add a _ghost_ placeholder (just the rectangle presenting button shape with specific colors `$dark-ultra-dim` / `$light-ultra-dim`) when we cut the last button and buttons container is empty and is not selected. I can see that on web it behaves the same, but imo looks weird because of that empty space. Wdyt @iamthomasbishop?

**Comment by geriux** [comment]
Thanks for the feedback Luke!

> * After cutting the last button from buttons there is a space on the left from the button which looks _odd_, I had the same problem with social icons and created a [fix](https://github.com/WordPress/gutenberg/pull/23017/files#diff-260b0f5b413f5ac735a6935b2f8acc34R387-R389) within my PR. Maybe we can introduce that change with your PR (prolly it will be merged earlier than my PR)

I'm trying to open the link but it's not redirecting well I think. Can you tell me exactly what is the fix you made for this issue?

Thanks!

**Comment by geriux** [comment]
> 2\. I think that we should add a _ghost_ placeholder (just the rectangle presenting button shape with specific colors `$dark-ultra-dim` / `$light-ultra-dim`) when we cut the last button and buttons container is empty and is not selected. I can see that on web it behaves the same, but imo looks weird because of that empty space. Wdyt @iamthomasbishop?

Yeah, we should definitely add something like that. I'll merge this PR and then work on that depending on what @iamthomasbishop thinks about it.

Thanks!

**Pull request merged**
