### PR TITLE
Add a useFocusOutside React hook

### PR DESCRIPTION
**Pull request by youknowriad**
Follow-up to #27502 
Similar to #27544 

This refactors the existing withConstrainedTabbing HoC as a React hook to avoid the extra wrapper.
The goal here is to be able to remove the PopoverWrapper component that is duplicated across three packages and reuse a single hook.

### CODE REVIEW

**Comment by ellatrix** [comment]
I already had a PR for this: #27050

**Comment by youknowriad** [comment]
I'm sorry I missed your PR. I think though I prefer the current one for a few reasons:

 - The hook being in @wordpress/compose 
 - Avoid the ref as argument pattern which doesn't allow to refresh the behavior if the container changes.

**Comment by ellatrix** [comment]
Yes, my PR wasn't ready at all, it was just an exploration. I had problems making the unit tests pass.

**Comment by talldan** [comment]
> I already had a PR for this: #27050

Oops, me too 😄 https://github.com/WordPress/gutenberg/pull/27369

I avoided DOM event handlers (event though using a ref is a nicer pattern), as I don't think that'll work for nested modals/popovers, which rely on virtual bubbling of events. But maybe there's another way to handle this.

The easiest way to test this that I've found is to use the 'Display Button Labels' option with a smaller screen size and the try accessing the nested popovers in the Tools menu (Outline or Details).

**Comment by youknowriad** [comment]
> I avoided DOM event handlers (event though using a ref is a nicer pattern), as I don't think that'll work for nested modals/popovers, which rely on virtual bubbling of events

I'm on the fence. Logically speaking it seems we want to avoid React virtual bubbling here because technically speaking this is an a11y behavior that rely on DOM and doesn't know anything about slots. That said it goes against "nested popovers" or "nested modals". I wonder if it's a use-case we want to support and whether it's acceptable to just close the parent.

Let's go with your approach for now.

**Comment by ellatrix** [comment]
@talldan How would you merge multiple event handlers? The implementor has to merge all the props?

Personally I think I'd prefer DOM event handlers.

**Comment by youknowriad** [comment]
I'm going to close this for now, I also prefer DOM event handlers but I can't see how we can solve the nested modals/popovers issue with them.

**Comment by talldan** [comment]
@ellatrix There was a bit of discussion about the event handlers here with a few different ideas - https://github.com/WordPress/gutenberg/pull/27369#discussion_r535862725.

@youknowriad I do prefer returning `ref` in terms of the usability of the hook, but was concerned about back compat. Particularly as it's quite an intricate (at least to me 😄) little HOC.

I don't know if we could try something using context to get a similar bubbling behavior, but still use DOM event handlers. The way `withFocusOutside` works seems to mostly depend on `cancelBlurCheck` being called when a legit focus happens to a child, so perhaps that could be propagated up using context?

I'm imagining something where context consumers can register themselves and then also trigger a `cancelBlurCheck`. Seems a bit like an event/emitter pattern coincidentally.

**Comment by youknowriad** [comment]
@talldan worth trying, let's land your first implementation as experimental and see whether we can do this separately.

**Pull request closed without merging**
