### PR TITLE
i18n: Make menu and title labels in Gutenberg plugin translatable

### PR DESCRIPTION
**Pull request by mhimon**
Added translation to Page Title.

### CODE REVIEW

**Comment by ndiego** [comment]
@mhimon can you provide a description to this PR?

**Comment by mhimon** [comment]
> @mhimon can you provide a description to this PR?

Added. Thanks

**Comment by t-hamano** [comment]
Hi @mhimon,

Do you mean you want the menu labels in the Gutenberg plugin to be translatable? Then it would be a good idea to make the first argument, [$page_title](https://developer.wordpress.org/reference/functions/add_menu_page/#parameters), translatable as well.

Note that the plugin label change was also suggested in #8074.

**Comment by mhimon** [comment]
Updated! Thanks.

**Comment by t-hamano** [comment]
@mhimon Sorry for the delay in re-checking this PR. Could you rebase with the latest trunk in order to merge this PR? That way, GitHub Actions that are stopped will be re-run.

**Comment by mhimon** [comment]
@t-hamano please check, Thanks.

**Review by t-hamano — APPROVED** [review]
After closing and reopening this PR, GitHub Action seems to have started working again. I think this change makes sense and I would like to merge it after it passes all tests.

Thanks for your contribution!

**Comment by getdave** [comment]
✅ I updated the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959) to note this PR does not require a backport for WP 6.5.

It only changes the menu item for the Gutenberg _Plugin_ and thus is unused in WP Core.

**Pull request merged**
