### PR TITLE
Fix button width on Widgets Editor.

### LINKED ISSUE #38390: Widgets editor: Block appender does not appear as full width
### Description

The block appender in the Widgets screen appears as a small button to the right of the widget area. It should expand to fill the widget area.

You could potentially use `git bisect` to find what commit broke this.

### Step-by-step reproduction instructions

1. Activate a classic theme.
2. Go to Appearance → Widgets. 
3. Look at the block appender at the bottom of any widget area.

### Screenshots, screen recording, code snippet

Screen Shot 2022-02-01 at 12 15 50

You can see what the appender button _should_ look like when there are no blocks in the widget area:

Screen Shot 2022-02-04 at 10 43 00

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by mjstoney**
Widget appender button width fix. 

## Description

The widget appender button was small due to position absolute. We change the position to relative and now it expands to the width of parent container. 

## Testing Instructions

1. Activate a classic theme.
2. Go to Appearance → Widgets.
3. Look at the block appender button at the bottom of any widget area.
4.  It now takes up the full width instead of being a small square button.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [x] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by draganescu** [comment]
Howdy @mjstoney and welcome to the Gutenberg repository 🙌🏻 This PR is missing an issue, so could you please describe the exact problem and how to reproduce in the description of the pull request?

> The widget appender button was small due to position absolute.

This needs a few details:
- Where?
- What browser?
- What WP version?

A screenshot or gif would also work. Thank you!

**Comment by noisysocks** [comment]
@draganescu: I linked the issue (https://github.com/WordPress/gutenberg/issues/38390). GitHub doesn't make it very obvious 🙂

**Review by noisysocks — APPROVED** [review]
The block appender is looking normal again! Thanks for the fix @mjstoney.

| Desktop | Mobile |
| - | - |
| Screen Shot 2022-02-17 at 13 56 19 | Screen Shot 2022-02-17 at 13 56 08 |

**Comment by mjstoney** [comment]
> The block appender is looking normal again! Thanks for the fix @mjstoney.


Ah thank you for the screenshots, I will be sure to link the issue correctly next time!

**Comment by draganescu** [comment]
Thanks @mjstoney 🙏🏻

**Comment by jeffpaul** [comment]
@mjstoney checking back to see if you can confirm your WordPress.org username so we can ensure you are properly credited in the WordPress 6.0 release coming out on May 24th. You can use the links above or share information directly with me and I'll ensure it's included correctly within the release. And thanks again for your contribution, it's greatly appreciated!

**Comment by mjstoney** [comment]
@jeffpaul Hi I have registered the account name mjstoney and linked my github through wordpress.org. Thanks for the reminder!

**Pull request merged**
