### PR TITLE
Add color icon.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

We have a "color" icon in the WordPress Design Library Figma, this one:

color

It hasn't yet been added to the library, but it will be needed for adding a Color option directly to the Cover block toolbar.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
Cool, can we replace the brush used right now in the Global Styles Sidebar? :)

**Comment by jasmussen** [comment]
Good call. Before:

Screenshot 2021-09-28 at 14 27 24

After:

Screenshot 2021-09-28 at 14 29 19

**Review by youknowriad — APPROVED** [review]

**Comment by jasmussen** [comment]
You're just about my favorite reviewer, Riad!

**Comment by youknowriad** [comment]
Truth is, you just saved me some work hours by doing this PR instead of me :)

**Comment by jasmussen** [comment]
Always happy to help, and you're always welcome to delegate if you can, especially in icon cases.

**Review by mtias — APPROVED** [review]

**Comment by ndiego** [comment]
Just stumbled on this PR. There are a number of other icons missing from the library. Notably this "tip" icon at the bottom of the block inserter. 

image

I would also love to see all the icons that are used in the core Social Icons block added as well. I can put together a PR if this is of interest. Let me know!

**Comment by jasmussen** [comment]
Oh good catch @ndiego, I could've sworn that was an icon part of the library, but it does appear to just be an inline SVG. I'd be happy to review such a PR.

I don't think we should add logos to the icon library, though. There are some challenges already with following logo brand guidelines and keeping up with maintenance, which is a burden I don't think should be put on the icon library. There are separate places to get logos in a react format, though, such as [this one](https://github.com/Automattic/social-logos).

**Comment by ndiego** [comment]
Awesome, thanks. I'll get a PR put together in a day or so. And yeah, I definitely see your point about the Social Icons.

**Pull request merged**
