### PR TITLE
Explore: Multiselection by dragging

### PR DESCRIPTION
**Pull request by adamziel**
Just a fun idea I had after trying out a few note-taking apps. Selecting multiple blocks by drag&drop seems like a natural interaction to have:

https://user-images.githubusercontent.com/205419/134696866-22aaf33a-acd7-4a5c-bcd2-eaa574391544.mp4

To try it yourself, apply this PR and go to Gutenberg demo editor.

The code is not quite mergeable, that's more of an exploration to start a discussion. I wonder what y'all think.

cc @jasmussen @tellthemachines @talldan @noisysocks @ellatrix @talldan @getdave @kevin940726 @javierarce

### CODE REVIEW

**Comment by javierarce** [comment]
> I wonder what y'all think.

I think that this is… very cool! 

The idea would be to invoke this tool from the Select mode, right?

**Comment by kevin940726** [comment]
I think this is pretty cool! 🌟 

Though I don't think this should be enabled by default, this should only be enabled in navigation mode or something like that.

**Comment by jasmussen** [comment]
This is fun, looks great! Making it still simpler to select blocks feels good. Whether it needs to be select mode only or can exist in both I think remains to be seen. But it does remind me that we have some general issues with block selection, that could be good to look at either in conjunction with this, or after.

First off, the multi-select style which paints a browser selection across multiple blocks is misleading and doesn't look very good. We likely need a new design for multi selection. So instead of this:

Screenshot 2021-09-28 at 08 34 32

it could be this:
new multiselect

That might work better with the dragging motion as well, as that makes it even more obvious you are selecting blocks, not text:

new multiselect side

Secondly, deselecting blocks at the moment is a bit fiddly. Simply addressing #5803 would be a good start.

Thirdly, it opens up the conversation about non consecutive block selection (#16797) — what happens when you hold shift and select after you've made an initial selection? 

Finally, and this is something @jameskoster has talked about for a while: it could make sense to let select mode be default. We might need to make it easier to stay in edit mode for longer — but the key benefit would be that we could enhance the Escape key behavior: making the first press of Escape deselect the block.

While these are all separate issues, they do speak of some challenges we have around selection at the moment, which might be good to look at in case we add more complexity with this one.

**Comment by draganescu** [comment]
I tried to revisit this but it doesn't seem to build anymore (ran ye old `npm install` to no success). Nevertheless, could we instead turn it into an issue (including @jasmussen 's suggestions)?

**Comment by adamziel** [comment]
Good idea @draganescu! Let's close this one and continue in https://github.com/WordPress/gutenberg/issues/41684

**Pull request closed without merging**
