### PR TITLE
Update theme.json schema to allow for per-block management of settings.

### PR DESCRIPTION
**Pull request by ryanwelcher**
## Description
This PR is an attempt at addressing #36630. It separates out each of the setting objects ( border, color, spacing etc ) into individual definitions and then combines them on a per-block basis using `allOf`. This allows the schema to use any or all of them to create a schema that is both valid and also reflects what the block actually supports. 

I have includes a single updated block in this PR so we can discuss if this is the correct approach. The `core/button` block only implements the controls for the `border.radius` option so I have updated its entry to reflect such. 

## How has this been tested?
Tested locally by pointing the `$schema` entry to the theme.json [schema definition](https://raw.githubusercontent.com/ryanwelcher/gutenberg/feature/update-theme-json-schema-36630/schemas/json/theme.json) in this PR 

## Types of changes
Schema updates that should have no breaking affect on blocks.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ryanwelcher** [comment]
If this approach seems sound, it may make sense to merge this and then create a tracking ticket for the other blocks. I have spent a fair amount of time looking into the per-block support and can handle the creation of that ticket. It would also be a great place for new contributors to get some props.

**Review by ajlende — APPROVED** [review]
Sorry it took me so long to get around to reviewing this, but I like the idea! Let's get the merge conflicts resolved and do like you said with creating a tracking issue to update the rest of the blocks.

**Comment by ryanwelcher** [comment]
@ajlende I have addressed the merge conflicts but am blocked by some e2e tests. The navigation block e2e failures are unrelated to the changes here. Based on @youknowriad 's [comment here](https://github.com/WordPress/gutenberg/pull/37446#discussion_r777909007) I have also created a PR to skip the test with #37729

**Comment by ajlende** [comment]
Looks like the docgen for the theme.json broke because of the structure change. Care if I push a few commits to this branch to fix it? Otherwise, the change would be in https://github.com/WordPress/gutenberg/blob/trunk/bin/api-docs/gen-theme-reference.js.

**Comment by ryanwelcher** [comment]
> Looks like the docgen for the theme.json broke because of the structure change. Care if I push a few commits to this branch to fix it? Otherwise, the change would be in https://github.com/WordPress/gutenberg/blob/trunk/bin/api-docs/gen-theme-reference.js.

Not at all! I just merged #37729  as well so be sure to pull latest `trunk`

**Comment by ajlende** [comment]
> Not at all! I just merged #37729 as well so be sure to pull latest trunk

Cool, will do!

**Comment by ajlende** [comment]
Alright, I pushed a quick fix that will generate the same docs as before. As a follow-up when all the blocks are updated we can update the docgen to show the settings per-block.

**Pull request merged**
