### PR TITLE
Unlock the private 'kebabCase' function at a file level

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
This is a follow-up to #56758.

PR moves the private `kebabCase` function unlocking at the file level.

## Why?
Private APIs like functions can be unlocked at the file level, avoiding executing unlocking logic multiple times.

## Testing Instructions
CI checks should be green.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hmm, it seems that `.native.js` files only support "just-in-time" unlocking (I should've probably checked the commit [history](https://github.com/WordPress/gutenberg/pull/56758/commits/faa563b80b3e5e991b9023625624b47b62cf483a) 😓)

@tyxla, did you get a chance to have a better look at the problem?

cc @WordPress/native-mobile

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

Importing private APIs at the file level was not possible because it would cause unit test errors in React Native App. To my knowledge, I don't know why this happens 😅

**Comment by tyxla** [comment]
> Hmm, it seems that `.native.js` files only support "just-in-time" unlocking (I should've probably checked the commit [history](https://github.com/WordPress/gutenberg/pull/56758/commits/faa563b80b3e5e991b9023625624b47b62cf483a) 😓)
> 
> @tyxla, did you get a chance to have a better look at the problem?

> Importing private APIs at the file level was not possible because it would cause unit test errors in React Native App. To my knowledge, I don't know why this happens 😅

From my understanding, there should be no good reason for this to happen.

I actually have a clue what the problem might be. Taking a look and will reply shortly.

**Comment by tyxla** [comment]
Okay, found the culprit.

It appears that we have circular dependencies in the native app. Currently, the `@wordpress/components` package is a dependency of `@wordpress/block-editor`. 

However, you can see that we import modules from `@wordpress/block-editor` in `@wordpress/components`:

https://github.com/WordPress/gutenberg/blob/30b5e03b2afc1f5ed68c4f4359cb2bfbfa2e7af5/packages/components/src/mobile/global-styles-context/utils.native.js#L11-L15

That's wrong, of course, since the former isn't a dependency of the latter.

To verify my hypothesis, I ran `npm run test:native:watch packages/format-library/src/link/test/modal.native.js` and it failed. Then, I removed the imports from `@wordpress/block-editor` and on the second run, it passed. 

Resolving this will need some reshuffling of native components here and there, so there are no circular dependencies. A similar fix was done by @ellatrix in #57045.

I'm quite occupied with other things this week, and won't be able to take a look, so feel free to work on this one @Mamaduka @t-hamano. Thanks 🙌

**Comment by tyxla** [comment]
FWIW resolving this will allow us to do single-module unlocks for all other instances we're doing it on runtime for mobile - there are a few more, for example:

https://github.com/WordPress/gutenberg/blob/1f21f61fd6106bdd7f3debd7293d04e2783923c7/packages/block-editor/src/components/block-list/block.native.js#L430

**Comment by Mamaduka** [comment]
Thank you, @tyxla!

I had the feeling that there was something wrong with the config, but circular dependencies didn't cross my mind. Happy to pick it up from here 🙇

**Comment by ellatrix** [comment]
Yes I started looking at fixing the circular dependency but didn't finish it, I also have a PR open for this at #57042

**Comment by dcalhoun** [comment]
For additional context, https://github.com/WordPress/gutenberg/issues/52692 and https://github.com/WordPress/gutenberg/issues/27751 relate to the circular dependency subject.

**Comment by geriux** [comment]
> For additional context, #52692 and #27751 relate to the circular dependency subject.

I'm working on addressing this in https://github.com/WordPress/gutenberg/pull/61102

**Comment by Mamaduka** [comment]
Thank you, @geriux!

I started looking into it, but I've very little experience with RN. I wasn't even able to build the app locally :(

**Comment by geriux** [comment]
> I started looking into it, but I've very little experience with RN. I wasn't even able to build the app locally :(

No worries! I worked on some of those files so that helped a bit! Let us know if the future if we can help with getting the app to build locally 😃

**Comment by geriux** [comment]
Hey everyone 👋 the mobile team just merged https://github.com/WordPress/gutenberg/pull/61102 which should solve the blockers in this PR. Please let us know if there are still blockers that we might have missed. Thank you!

**Comment by tyxla** [comment]
> Hey everyone 👋 the mobile team just merged #61102 which should solve the blockers in this PR. Please let us know if there are still blockers that we might have missed. Thank you!

Great news, thank you so much @geriux 🫶 

@Mamaduka do you need anything else to continue here?

**Comment by Mamaduka** [comment]
@tyxla, I'll rebase and make sure everything is up to date later today.

**Review by t-hamano — APPROVED** [review]
LGTM! Just one thing, can this function also be unlocked at the file level?

https://github.com/WordPress/gutenberg/blob/28847b04ce121fd333ee364a6525d2ca7f969e10/packages/edit-site/src/components/global-styles/font-library-modal/utils/index.js#L187

**Pull request merged**
