### PR TITLE
Chrome: Hide Sidebar Panels if the user don't have the right capabilities

### PR DESCRIPTION
**Pull request by youknowriad**
If the user doesn't have the "publish_posts" capability (a contributor), several panel sidebars should be hidden.

In this PR I'm hiding the "pending" toggle, the "schedule" panel and the post visibility is not editable. (similar to the current editor)

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Nice 👍 

One issue, which I expect is present on master, is that the author dropdown does not show (correctly) for contributor role, but only because it attempts to make the API request for users and fails. Up to you if you'd like to address that here or separately.

**Comment by youknowriad** [comment]
> One issue, which I expect is present on master, is that the author dropdown does not show (correctly) for contributor role

Do you mean, instead of relying on the available users, we should rely on the capabilities?

**Comment by youknowriad** [comment]
@aduth I went ahead and updated to add the capability check. but the API request is still being fetched, because it's being declared on the same `withAPIData` HoC. I don't know if we want to create another inner component just to avoid this failing request. An alternative could be to pass the `dataProps` to the `mapPropsToData` callback, this way we could decide to include an API call depending on the previous result of another API call. This could be something to try separately;

**Comment by aduth** [comment]
Yeah, either of those seem worth exploring. There should ideally be no 403 requests issued if we know they can be avoided.

**Pull request merged**
