### PR TITLE
Added a menu subitem for pages, updated the posts subitem

### PR DESCRIPTION
**Pull request by grantpalin**
## Description
Admin menu amendment per #2239. Adds a **New Page** item above **New Post**.

## How Has This Been Tested?
Ran on a local WordPress install (Windows 10 & XAMPP) using a fresh checkout.

Small amendment to the routine the registers menu items.

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes

Added a **New Page** item above **New Post**.

Amended the New Post configuration to update the title attribute to distinguish posts and pages.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
@karmatosed, it looks like another iteration on Gutenberg menu. It seems like a good addition.

**Comment by aduth** [comment]
Minor, but I might suggest the ordering be placed _after_ New Post, depending on if we expect post to be the more common workflow, or to preserve expectations of previous versions of the plugin, or to preserve ordering of Posts and Pages in the top-level admin sidebar.

**Comment by grantpalin** [comment]
Minor, but probably good for consistency. Updated the PR to switch them around.

**Comment by karmatosed** [comment]
In light of #2951, I am not sure we need this anymore. I would vote to close because we are making it the default.

**Comment by pento** [comment]
bdf94e6 has landed, so the default behaviour when creating a new page is to use Gutenberg - we don't need to add this menu item anymore.

Thank you for the PR @grantpalin, sorry it didn't land, you're always welcome to open new PRs in the future! 🙂

**Pull request closed without merging**
