### PR TITLE
Block Supports: Revert stabilization of typography, border, skip serialization and default controls supports

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
## What?

Reverts the block support stabilization changes made via the following PRs:

- https://github.com/WordPress/gutenberg/pull/67552
- https://github.com/WordPress/gutenberg/pull/67018
- https://github.com/WordPress/gutenberg/pull/66918
- https://github.com/WordPress/gutenberg/pull/66849
- https://github.com/WordPress/gutenberg/pull/63401

## Why?

The approach taken to block support stabilization ironically needs some further time to stabilize itself 🙂  

Additional time is also needed to communicate changes required by 3rd party extenders as a result of these block support stabilizations.

An alternative approach to what has already landed in Gutenberg was proposed but if it is ultimately to be pursued there isn't sufficient time before 6.8 to work through the kinks and communication. More details and discussion can be found [here](https://github.com/WordPress/gutenberg/pull/67729#issuecomment-2553200639).

## How?

Reverts the commits from the PRs listed above.

## Testing Instructions

1. Add a variety of different blocks that opt into typography supports. Ensure both static and dynamic blocks are covered.
2. Apply some global typography styles for the blocks being tested.
3. Select the individual block instances and apply new typography styles to override global styles. Confirm these are applied correctly in the editor.
4. Save and confirm the typography support styles are correctly applied on the frontend.
5. Back in the editor, cross check the default controls defined in the blocks' block.json with the controls displayed by default in the block inspector.
6. Repeat the process from 1-5, this time checking border block supports function as before.
7. Confirm that blocks that skip the serialization of block support styles and classes still function e.g. Images with borders etc.

## Screenshots or screencast 

There should be no visible changes to trunk.

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
cc/ @ndiego, @bph, @justintadlock 

FYI if we land this revert, block supports won't be stabilized for 6.8. Are you aware of any further posts, docs etc that we might need to update to communicate this delay? For example, do we want this on the December [What's New for Developers post](https://developer.wordpress.org/news/2024/12/whats-new-for-developers-december-2024/#stabilizing-experimental-supports-keys)?

**Comment by ramonjd** [comment]
I've only tested this manually according to the instructions. Looks good so far. I'll give it closer look next week. 

Thanks again for all the work coding, testing, and documenting this.

**Comment by ramonjd** [comment]
✅ Checked revert against already-merged PRs 
✅ Tested with static and dynamic blocks (group, image, site title, paragraph)
✅ Global border and typography styles are applied
✅ Block-level border and typography styles override globalstyles
✅ Frontend reflects all changes
✅ Using the previously-stabilized keys in block.json (now invalid) removes support, i.e., they no longer work.


I'm pretty confident that this PR is good to go. It would be good to get a second round of smoke testing.

**Review by ramonjd — APPROVED** [review]
This LGTM

This removes Gutenberg functionality that was in 19.8, but I consider it low risk. The plugin is experimental and we're reverting for the sake of stability. 

If folks agree, I'd be happy to write a post on the Make Core blog to explain the roll back.

**Review by talldan — APPROVED** [review]
LGTM. I cross-checked a lot of the code, and they look like clean reverts.

Manual testing went well for me too following the steps outlined.

The only thing I noticed is that the Font dropdown for a block's styles seems to reset to 'Default' after a reload even if I've picked a different font for the block (the style does stay correct, just the dropdown has the wrong value):
1. Insert a paragraph
2. In the inspector styles tab, click the typography settings menu, and add the 'Font' option.
3. Choose a different font for the block
4. Save and reload
5. Select the paragraph, and view the inspector controls. Observe that 'Default' is selected again.

I imagine it's not related to this PR, but thought I'd mention it.

**Comment by ramonjd** [comment]
> I imagine it's not related to this PR, but thought I'd mention it.

Looks like this on trunk too. If it's an easy fix, I'll throw a PR up.

**Comment by ramonjd** [comment]
> The only thing I noticed is that the Font dropdown for a block's styles seems to reset to 'Default' after a reload even if I've picked a different font for the block (the style does stay correct, just the dropdown has the wrong value):

Good catch! Fortunately it was a one-liner. If you get time to 👀 

- https://github.com/WordPress/gutenberg/pull/68254

**Comment by aaronrobertshaw** [comment]
Thanks for seeing this across the line @ramonjd and @talldan 🙇

**Pull request merged**
