### PR TITLE
Updated several typos in client-assets.php file

### PR DESCRIPTION
**Pull request by shail-mehta**
Updated several typos in lib/client-assets.php file

- `replalce` it should be `replace`
- `devlopment` it should be `development`

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

This change is also [necessary in the core](https://github.com/WordPress/wordpress-develop/blob/6e7acb0103ce64bcd0b66d22cb0efb6249028004/src/wp-includes/script-modules.php#L157), so could you take the following steps according to the [README](https://github.com/WordPress/gutenberg/tree/trunk/backport-changelog)?

- Submit a ticket on Trac
- Submit a PR to `wordpress-develop` repo
- Add the markdown files to `backport-changelog/6.8/{CORE_PR_NUMBER}.md` and update this PR

**Comment by shail-mehta** [comment]
@mukeshpanchal27  @t-hamano  Thank you for the review.

**Comment by shail-mehta** [comment]
@t-hamano Thank you for the steps.

I have created ticket in core: https://core.trac.wordpress.org/ticket/62213

Here is Pull Request URL in wordpress-develop repo:  https://github.com/WordPress/wordpress-develop/pull/7561

**Comment by dilipom13** [comment]
Please change into stable version

**Comment by shail-mehta** [comment]
@t-hamano Core PR is Merged in 6.7, so i need to change in backport changelog in gutenberg in 6.7 instead of 6.8?

**Comment by t-hamano** [comment]
Thanks for the update!

> Core PR is Merged in 6.7, so i need to change in backport changelog in gutenberg in 6.7 instead of 6.8?

Yes, the core ticket certainly appears to apply to WP 6.7. Could you move the changelog file to the `6.7` directory?

**Comment by shail-mehta** [comment]
> Thanks for the update!
> 
> > Core PR is Merged in 6.7, so i need to change in backport changelog in gutenberg in 6.7 instead of 6.8?
> 
> Yes, the core ticket certainly appears to apply to WP 6.7. Could you move the changelog file to the `6.7` directory?

@t-hamano Updated. (Moved changelog in `6.7` instead of `6.8`)

**Review by t-hamano — APPROVED** [review]
LGTM! Thanks for the update.

**Pull request merged**
