### PR TITLE
Move the block manager to the preferences modal

### PR DESCRIPTION
**Pull request by youknowriad**
Just a small PR to propose to move the block manager to the preferences modal, these are all "preferences". 

At the moment, scrolling is a bit weird, if there are experts with sticky positioning here, please do fix it :)

### CODE REVIEW

**Comment by jasmussen** [comment]
Big fan! But there's an issue with scrolling the block manager, the toolbar disappears:

yo

Other than that, 👍 👍

**Comment by ntsekouras** [comment]
Sticky problem is tricky here as it seems that the `Modal` component itself is a bit 'faulty' . See more info here: https://github.com/WordPress/gutenberg/pull/28329#issuecomment-764640379.

There is this PR: https://github.com/WordPress/gutenberg/pull/28394/files that doesn't fix the double sticky part but solves the problem that @jasmussen mentioned.

Also I'm not really sure if this affects other places in a way it shouldn't 🤔

**Review by ntsekouras — COMMENTED** [review]
Code wise this looks good.

There should be just some style polishing about `sticky` and probably these two small issues:
1. Checkbox focus is hidden
2. Info message is larger than the other controls

Screenshot 2021-04-27 at 2 35 25 PM

**Comment by mtias** [comment]
Another thing is the block manager should be absorbed into the "blocks" section, it doesn't make sense to have "block manager" and "blocks" top levels.

**Comment by stokesman** [comment]
I've looked into moving this one along and there's more than one way to do so. Also, besides the `sticky` issue in `Modal` there's one in `Navigation` (used at less than medium breakpoints) also needing a resolution. I've made seperate PRs for both. My take on the most robust way to resolve the `sticky` issue for `Modal` is in #31639 (it also fixes another style issue). A resolution for the `sticky` issue in `Navigation` is in #31874 (plus an animation enhancement).

I've made branch of this PR rebased on changes from those PRs above and the result is #32166. It has a few additional changes addressing preceding comments (https://github.com/WordPress/gutenberg/pull/31191#issuecomment-827566884, https://github.com/WordPress/gutenberg/pull/31191#pullrequestreview-645754716) and proposed improvements. It's there for testing but intentionally left drafted and sparsely described since the PRs it's based on need vetting first.

**Comment by youknowriad** [comment]
@stokesman I think the modal changes now landed, should we include your PRs into the current branch or continue on yours (no preferences from me)?

**Comment by stokesman** [comment]
@youknowriad, I figured the other branch would have an easier rebase and so went ahead and did that. Then it occurred to me the PR #31874 is not needed as there is a easy way to override the `Navigation` styles to make sticky work. So now #32166 is not reliant on a separate PR and I'll go ahead and mark it as ready.

**Comment by youknowriad** [comment]
I'm closing this one in favor of #32166

**Pull request closed without merging**
