### PR TITLE
[RNMobile] Correct navigation toolbar

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

PR is fixing [the issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1677) where items are overlapping in `FloatingToolbar`

ref to gb-mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1769

## How has this been tested?

1. Change font to the largest in device settings
2. Open mobile app
3. Add Media&Text block
4. Rotate device to horizontal mode
5. Press `Paragraph` block
6. Check if items are displayed properly in `FloatingToolbar` 

## Screenshots 

**NOTE** In my screenshots block name is `VeryVeryLongParagraph` just for a proper example displaying

**Long block name with regular font size**

vertical nested | vertical root
--- | ---
Screenshot 2020-01-10 at 14 08 40  | Screenshot 2020-01-10 at 14 08 36

horizontal nested | horizontal root
--- | ---
Screenshot 2020-01-10 at 14 10 37 | Screenshot 2020-01-10 at 14 10 34

**Long block name with the largest font size**

vertical nested | vertical root
--- | ---
Screenshot 2020-01-10 at 14 12 27 | Screenshot 2020-01-10 at 14 12 23

horizontal nested | horizontal vertical
--- | ---
Screenshot 2020-01-10 at 14 13 35 | Screenshot 2020-01-10 at 14 13 33

**Regular block name**

horizontal nested | horizontal root
--- | ---
Screenshot 2020-01-10 at 14 16 07 | Screenshot 2020-01-10 at 14 16 05

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
If we can bring the max font-size down slightly, allowing us to fit more characters before truncating (~15 if possible, as I'm only seeing a few common blocks that contain more than that), I think this truncation solution would work for now.

Side note: I'm not sure if this has been asked already, but if not, I can't believe I didn't think of this sooner. Is it possible to extend the floating toolbar beyond the width of the selected block? That might provide more room and solve the issue, but I think we can't do that because the toolbar isn't actually "floating", but moving the selected block down to make room for the toolbar (if I remember correctly).

The other option that has been floated is: we could also hide the label when the block is very narrow, although this is a bit more of an extreme option.

**Comment by lukewalczak** [comment]
I set `maxFontSizeMultiplier={ 1.25 }` which allows to display 13 characters before truncation. 

image

Presenting more characters means that `maxFontSizeMultiplier` indicator will have value `1`, so the text on the largest size won't be accessible enough.

> Side note: I'm not sure if this has been asked already, but if not, I can't believe I didn't think of this sooner. Is it possible to extend the floating toolbar beyond the width of the selected block

As you noticed current toolbar is not floating, so imo it's not a good approach right now.

Please let me know if value `1.25` for `maxFontSizeMultiplier` (displaying 13 characters like on the screenshot) is acceptable.

**Comment by iamthomasbishop** [comment]
Thanks for the update @lukewalczak. 

> As you noticed current toolbar is not floating, so imo it's not a good approach right now.

That makes sense.

> Please let me know if value 1.25 for maxFontSizeMultiplier (displaying 13 characters like on the screenshot) is acceptable.

This should work. 👍

**Comment by lukewalczak** [comment]
Thanks @iamthomasbishop, the latest changes in the PR support ~13 characters before the truncation and `maxFontSizeMultiplier` value is set to `1.25`.

android | ios
--- | ---
image | Screenshot 2020-01-14 at 12 48 49

**Comment by iamthomasbishop** [comment]
This should work! My vote would be to ship and iterate if necessary.

**Review by geriux — APPROVED** [review]
LGTM! Thanks for this fix! 🚀 Tested both on iOS and Android.

**Pull request merged**
