### PR TITLE
Add template part conversion e2e tests

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Adding tests for convert/detach template part flows that were added in #20445 / #26488 

## How has this been tested?

Tested by running the new tests locally as well as verifying they are doing as expected in interactive/slow-mo mode.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
Looks good to me, especially with the tests passing! I wonder if it might be useful to test with more than one inner block, but that's not a blocker.

**Comment by Addison-Stavlo** [comment]
> I wonder if it might be useful to test with more than one inner block, but that's not a blocker.

Perhaps.  Do you mean to multi-select a couple blocks for converting to template part (instead of just the one)?  I suppose the test could select one, verify the option is there, multi select and convert and then verify it was converted with all the blocks?

**Comment by noahtallen** [comment]
> Or alternatively have 2 separate tests for block conversion vs. multiple block conversion?

I guess that might be "more robust", but yeah, selecting multiple blocks before converting is what I was getting at

**Comment by Addison-Stavlo** [comment]
> I guess that might be "more robust", but yeah, selecting multiple blocks before converting is what I was getting at

👌  - Sounds good.  I added another test for doing the same with a multi-selection, and refactored a little bit.  Could use another 👀  glance and 👍  at some point for a sanity check.  Also rerunning the CI tests here a couple times to be sure things are good.

**Pull request merged**
