### PR TITLE
Fix code example in PluginBlockSettingsMenuItem docs

### PR DESCRIPTION
**Pull request by adekbadek**
Small tweak

### CODE REVIEW

**Comment by mkaz** [comment]
Hi, thank you for this change. It looks good, but one small issue is the PR is opened against the `wp/5.4` branch and should be opened against the master branch. Can you create a new PR against master and I can help approve and get it merged. Thanks!

**Review by mkaz — APPROVED** [review]
👍 Looks good, thanks! See my above comment for switching the PR branch and we can merge.

**Comment by gziolo** [comment]
I tried to switch branches but it isn't straightforward.

**Comment by mkaz** [comment]
Thanks @gziolo for trying, I think @adekbadek will have to do it since its from his fork

**Comment by adekbadek** [comment]
@mkaz done 👍

**Comment by mkaz** [comment]
@adekbadek It looks like the change did not trigger a new build. I think you will need to push a new commit to the branch to trigger the build.

**Comment by aduth** [comment]
I pushed an empty commit in 88d3e3f.

It appears to have worked to kick off the build: https://travis-ci.com/github/WordPress/gutenberg/builds/160567533

**Pull request merged**
