### PR TITLE
Fix Color Picker Format Toggle placement

### LINKED ISSUE #18326: RGB button placement is wonky
Currently, the button placement in Chrome looks like this:

nav-rgblink-buttonplace

### PR DESCRIPTION
**Pull request by jeryj**
Closes https://github.com/WordPress/gutenberg/issues/18326 and https://github.com/WordPress/gutenberg/issues/8197

## Description
Minor style changes to the size and placement of the color picker color format toggle.

## How has this been tested?
Manually, in Chrome.

## Screenshots
Before:
Screen Shot 2020-01-13 at 4 03 37 PM

After:
Screen Shot 2020-01-13 at 3 52 23 PM

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by obenland** [comment]
The amount of changes necessary are a bit more than I expected, but it does look much better. Do we have to add/change these class names?

**Comment by jeryj** [comment]
We didn't _have_ to, but it made the specificity of the selector a bit lower. Otherwise I would have had to do `.components-color-picker__inputs-toggle .components-button` to adjust the button height and padding, and at that point the BEM naming felt a little off. That's why I ended up changing the class names to better reflect the structure.

**Comment by obenland** [comment]
Okay, so this is a "fun" one.

Every input has a height of 30px and a margin of 1px.
Every number input only has a height of 28px.

That's why the button hover border looks off and jumps when looping through the hex input.
To fix that I'd recommend adding that 1px margin to the button and resetting the number inputs to 30px height.

**Comment by jeryj** [comment]
I understand what you're describing and why that makes sense, but my browser isn't showing a jump in the border. Which browser are you using? I wanted to test this one out in a more of them anyways.

color format toggle

**Comment by jeryj** [comment]
I tested the current code in Firefox and Safari and it looks consistently lined up, like in the gif above.

> Every number input only has a height of 28px.

I see what you're describing. There is a `min-height: 30px;` on the inputs, but that height is made up of the line height + padding + border. The button actually uses a `box-shadow` for the border, so it's manually set height of `30px` does line-up with the border from what I see. 

Let me know what you're running into here to make sure I iron out any discrepancies! Thanks for reviewing! 👍

**Comment by apeatling** [comment]
Did a good test of this and checks out for me, the button is correctly sized, placed, and aligned. :+1:

**Comment by obenland** [comment]
@shaunandrews Do you have time to take a look at this? just needs a final ✅.

**Comment by shaunandrews** [comment]
This looks better than it did. 🚢 

--

At some point, I'd love to see further iteration on this UI. The weird down-arrow-scroll thing is very confusing. We could follow Figma's lead here:

image

image

**Comment by jeryj** [comment]
@shaunandrews, yes! That updated design would close https://github.com/WordPress/gutenberg/issues/19608 as well.

**Review by obenland — APPROVED** [review]

**Review by apeatling — APPROVED** [review]

**Comment by chrisvanpatten** [comment]
Just want to point out some additional exploration which is happening in #18678, more from an accessibility perspective.

**Comment by jeryj** [comment]
@chrisvanpatten That's awesome 😍 I opened an issue related to that same thing regarding the dropdown icon.

**Pull request merged**
