### PR TITLE
Try a single icon for title blocks

### PR DESCRIPTION
**Pull request by jameskoster**
We now have quite a few 'Title' blocks, the icons for which are all variations on a common theme; two horizontal lines accompanied by a letter. They look like this:

Screenshot 2022-04-25 at 17 05 31

The letters already seem a little arbitrary, and I'm not sure how useful they are when we factor in i18n. This isn't a convention that will scale well if/when more 'Title' blocks are added.

It may be best to consolidate into a monolithic Title block, but that's a much bigger item. In this PR I just wanted to see if the usability is harmed if these blocks shared a single icon. 

I used the existing `title` icon for convenience, but it may be better to refine the design. For now I'd like to get a sense of whether this is something worth pursuing.

Screenshot 2022-04-25 at 17 03 15

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice PR! I think it's good to pull the breaks on the proliferation of title icons like this — there's an argument for every block needing a unique icon, to be sure, but these title variants haven't quite been clear enough on their own.

I'd use the T with two lines below, though, rather than the big T.

**Comment by jameskoster** [comment]
Title icon updated:

Screenshot 2022-04-27 at 10 32 32

**Review by jasmussen — COMMENTED** [review]
I'd be happy to try this. Not because the T + 2 lines icon is necessarily the best, but because the variants of it (A/C/etc) are not good and it'd be good to curtail that design.

Two things, though: 

1. You're changing the Title icon. I don't know if the T is used anywhere, I don't think it is, but that means it needs a changelog update. https://github.com/WordPress/gutenberg/blob/trunk/packages/icons/CHANGELOG.md
2. Since we are consolidating, should we deprecate/delete all the variant icons that get replaced with this? Or is that something we should postpone until later?

**Comment by jameskoster** [comment]
I'd be anxious about deleting any icons in the set since we don't know for sure whether they're being used by third parties.

**Comment by jasmussen** [comment]
> I'd be anxious about deleting any icons in the set since we don't know for sure whether they're being used by third parties.

Indeed. But we've [done this before](https://github.com/WordPress/gutenberg/pull/38849), and I think it important we do that for mistakes made lest they build up over time. In the case of NPM, the change will be noted as breaking in the changelog, and you can then choose not to update, or address the breaking change while doing so.

In this case, since the PR is in the "try" category, I'd be happy to _try_ this one without any deprecations, but my main concern there is: if we end up liking this change, _eventually_ we'll want to deprecate the icons and remove them from the library. 

What do you think? CC: @javierarce

**Comment by jameskoster** [comment]
I removed the icons :)

**Review by javierarce — APPROVED** [review]
🚀 This looks good to me. I like the consistency of just having one simple icon for every title block.

**Pull request merged**
