### PR TITLE
Navigation: Experiment with adding navigation link variations

### PR DESCRIPTION
**Pull request by gwwar**
WIP Part of https://github.com/WordPress/gutenberg/issues/24814 this PR experiments with registering navigation link variants.

This approach requires https://github.com/WordPress/wordpress-develop/pull/1002 to test.

Screen Shot 2021-02-15 at 12 08 21 PM

https://user-images.githubusercontent.com/1270189/107990032-607d6c80-6f88-11eb-9934-d4af9959cb20.mp4

### Request For Feedback

cc @noisysocks @gziolo 

I put together a pretty quick draft of what this looks like if we populate navigation link variations from the API

1. **Do we need an API update?** As for as I can tell, this requires some API updates to allow filtering, or show the extra visibility properties. I quickly drafted this in https://github.com/WordPress/wordpress-develop/pull/1002. Let me know if I mislooked anything and this an API update is unnecessary.
2. **Where should this live, and when should it fire?** Placement of the `registerBlockVariation` calls is a bit awkward. I had trouble finding a good spot. Our core data stores work best with a react component, so I instead opted for a direct `apiFetch` call which might not be ideal. 
3. **Rethinking Block Attributes** Reading customizer code and what we have here, I think `type` sort of corresponds to a taxonomy.slug or postType.slug value (with a hardcoded exception to tag, which is `post_type`). At a minimum I think I need to pass through if it's a `taxonomy` or `post-type`. I'm also not sure if slug is dependable, beyond the default built-ins. Can slug be renamed. Are collisions allowed? Eg should we be using a post type id/taxonomy id instead?

### TODO
- [x] Finish Search suggestion support handling
- [ ] Verify that we should populate from the API
- [ ] What should we do about custom post type labels/descriptions?
- [ ] Should we allow customization of the inserter icon?
- [ ] Should we respect the `customize_nav_menu_available_item_types` filter?
- [ ] Can we trust a taxonomy/post-type slug, or do we need to rely on ID/term_id
- [ ] Verify what data should be stored in the block / what deprecations should be made

### Testing Instructions
- Start up a local wordpress instance using changes in https://github.com/WordPress/wordpress-develop/pull/1002
- Install the gutenberg plugin with this branch
- Install a plugin with some custom post types and taxonomies
- Click on the block inserter, and add a navigation block
- Click start with empty
- Click on the block inserter in navigation
- Click on show more

### CODE REVIEW

**Comment by gziolo** [comment]
Nice start with this prototype. It shows how complex this setup is.

> Where should this live, and when should it fire? Placement of the registerBlockVariation calls is a bit awkward. I had trouble finding a good spot. Our core data stores work best with a react component, so I instead opted for a direct apiFetch call which might not be ideal.

I agree that the placement isn't good. I don't think we have any side effects defined for others blocks outside if the `Edit` component. The call for block registration happens in the loop for all blocks and this is the only place where side effects exist. 

Ideally, we shouldn't need to use REST API here at all. The only question is what would be the preferred way to set those block variations on the server. `block.json` doesn't fit here as the setup is dynamic.

Could it maybe work as Block Patterns? See explorations for the Query block started by @ntsekouras in https://github.com/WordPress/gutenberg/pull/28891

**Comment by gwwar** [comment]
Thanks @gziolo for taking a look!

> Ideally, we shouldn't need to use REST API here at all.

💯 on this. I sketched out this approach since there isn't a corresponding `register_block_variation`.

> Could it maybe work as Block Patterns instead?

That might be interesting. @jasmussen what do you think? I suppose the main interaction difference, is selecting a link type from the inserter, vs inserting from a flow in the block placeholder. Some cases to consider: within the navigation block, each link is relatively small so the placeholder area will be smaller too. We'll also want to consider a site that has a reasonable number of CPT/Taxonomies added

**Comment by gwwar** [comment]
@gziolo After playing a bit block patterns feels like not a good match for this use case, unless we'd like to rethink how we'd like to build a menu navigation at a higher level.

From what I understand, block patterns are **content focused**. So it makes sense for when we know the full example content (eg two grouped buttons), or are using a single dynamic/query block. "Give me a navigation menu that reflects all pages" is a great example.

| All Pages | Pattern Example |
| ------------- | ------------- |
| ```<!-- wp:navigation {"orientation":"horizontal"} --><!-- wp:page-list /--><!-- /wp:navigation -->``` | Screen Shot 2021-02-16 at 12 41 15 PM |

However if we try this with say a tag variant, we might be able to provide a placeholder, but **how would we add another tag or other link variant after that**? (see placeholder work in https://github.com/WordPress/gutenberg/pull/28861):

| All Pages | Placeholder Example |
| ------------- | ------------- |
| `<!-- wp:navigation {"orientation":"horizontal"} --><!-- wp:navigation-link {"type":"tag"} /--><!-- /wp:navigation -->` |Screen Shot 2021-02-16 at 12 39 54 PM |

**Comment by gziolo** [comment]
> After playing a bit, block patterns feels like not a good match for this use case, unless we'd like to rethink how we'd like to build a menu navigation at a higher level.
> From what I understand, block patterns are content focused. So it makes sense for when we know the full example content (eg two grouped buttons), or are using a single dynamic/query block. "Give me a navigation menu that reflects all pages" is a great example.

All valid points if you think about it overall. The differences between block variations and block patterns are nuanced for more complex blocks. It all depends on what you want to achieve. If there is no way to make it fit the existing APIs, we should evaluate adding a new API that allows registering block variations on the server. There is prior art available for block styles (API introduced before block variations, that can be seen as a subset of functionality):

https://github.com/WordPress/wordpress-develop/blob/f84ebe3fe75ff6c2b1e8ffab3b3d4c76032cc4c5/src/wp-includes/blocks.php#L903-L905

https://github.com/WordPress/wordpress-develop/blob/a55a9183bce9b28fed1b648ec69897be33b56bd9/src/wp-includes/script-loader.php#L2304-L2317

**Comment by youknowriad** [comment]
Interesting challenge:

Did you consider providing the "variations" key of the block server side instead? I mean technically this is equivalent to the suggested `register_block_variation` but you don't really need this function you can just alter the "variations" key of the block type object.

Conceptually speaking, I'm trying to think wether it makes sense to support "dynamic variations" from the client side perspective, or if there are other Block APIs that could benefit from being dynamic. That said, I'd prefer for things like that to take some time to materialize as a generic use-case/API so it's probably better to just start adhoc and keep in mind potential new abstractions in the future if the need materialize more obviously.

**Comment by gziolo** [comment]
> Did you consider providing the "variations" key of the block server side instead? I mean technically this is equivalent to the suggested `register_block_variation` but you don't really need this function you can just alter the "variations" key of the block type object.

The issue is that we don't expose variations from the block type definition to the client. We would need to add handling in a few places, similar to `styles`:

https://github.com/WordPress/wordpress-develop/blob/f400eb5ab9e80f62939bd8630e27e08ee0619ba1/src/wp-includes/class-wp-block-type.php#L151-L158

https://github.com/WordPress/wordpress-develop/blob/e3a98e8f559029a32264b83eae59f90e6e7a375d/src/wp-admin/includes/post.php#L2242-L2257

https://github.com/WordPress/wordpress-develop/blob/f84ebe3fe75ff6c2b1e8ffab3b3d4c76032cc4c5/src/wp-includes/blocks.php#L227-L241

https://github.com/WordPress/wordpress-develop/blob/f400eb5ab9e80f62939bd8630e27e08ee0619ba1/src/wp-includes/rest-api/endpoints/class-wp-rest-block-types-controller.php#L364-L581

**Comment by gwwar** [comment]
@youknowriad @gziolo thanks for taking a look! I sketched out the alternative in https://github.com/WordPress/gutenberg/pull/29095, is this what you were thinking of?

**Comment by gziolo** [comment]
> thanks for taking a look! I sketched out the alternative in #29095, is this what you were thinking of?

Yes, that would be another way of doing it. I'm curious what @youknowriad had in mind.

**Comment by youknowriad** [comment]
Yep, that PR is exactly what I had in mind :)

**Comment by jasmussen** [comment]
Thanks for the ping, sorry for the late response. 

There's a technical angle to this that is possibly over my head, so I'll respond mostly to the user experience side of things.

> Could it maybe work as Block Patterns instead? 

I think we should absolutely use block patterns for the navigation block, perhaps even in the setup state as it's used with the Query block soon. We might potentially be able to leverage some of [this design](https://github.com/WordPress/gutenberg/issues/28735#issuecomment-780651352) by @jameskoster.

However [to your own point](https://github.com/WordPress/gutenberg/pull/29011#issuecomment-780112823), block patterns are definitely about content, and providing a shortcut to nice layouts. You are meant to customize the content inside a block pattern after the fact.

For example I would imagine most navigaiton block patterns to simply include the Page List block, the Social Links block, and the Search blocks, and any combination of those three. If you need custom links, you'd then need to detach the page list block, or to add your own items. 

Was that helpful?

**Comment by gwwar** [comment]
Thanks for chiming in @jasmussen!

> However to your own point, block patterns are definitely about content, and providing a shortcut to nice layouts. You are meant to customize the content inside a block pattern after the fact.

Very helpful to confirm that 💖. I think we'll end up needing both patterns to as you said provide shortcuts and some way of providing CPT/Taxonomy links one by one (which is this PR). I do think I can rule out patterns for this problem as a technical choice, since the navigation configurations we're setting up isn't known beforehand. Eg it'd be a little different if we know we wanted 5 links of X type, or wanted to build a dynamic block that mirrors all categories.

**Comment by gwwar** [comment]
Going to close this draft out for now in favor of https://github.com/WordPress/gutenberg/pull/29095

**Pull request closed without merging**
