### PR TITLE
Mobile: Update the border colours

### PR DESCRIPTION
**Pull request by enejb**
## Description
This PR updates deprecates the following colour variables. 
```
$light-gray-500: #e2e4e7; // Good for "grayed" items and borders.
$light-gray-400: #e8eaeb;
$light-dim: #0000001e; //rgba(0, 0, 0, 0.12); 
```
and replaces them with 

`$neutral-dim-light: rgba($black, 0.12);`
and 
`$neutral-dim-dark: rgba($white, 0.15); `

While at the same create a few different `design tokens` which make it easier to update the colours in the future. 
## How has this been tested?
This has been tested using the demo app on both Android and iOS. In light and dark mode.  

## Screenshots 
In order to make the different changes easier to see. I made the 
following changes to the `_colors.native.scss` file.
```
$border-color: red;
$border-color-dark: red;
$modal-border-color: orange;
$modal-border-color-dark: orange;
$drag-indicator: yellow;
$drag-indicator-dark: yellow;
$spacer-color: blue;
$spacer-color-dark: blue;
```
<details><summary>Highligheted colours</summary>
$border-color and $border-color-dark
Column Block
Screen Shot 2020-09-17 at 2 45 49 PM

Media Text Block
Screen Shot 2020-09-17 at 2 46 08 PM

Cover Block
Screen Shot 2020-09-17 at 2 45 10 PM

Buttons Block
Screen Shot 2020-09-17 at 2 46 27 PM

Contact Info Block 
Screen Shot 2020-09-17 at 2 46 52 PM

$modal-border-color and $modal-border-color-dark

Toolbar 
Screen Shot 2020-09-17 at 2 49 38 PM

Model colours
Screen Shot 2020-09-17 at 3 20 46 PM
Screen Shot 2020-09-17 at 3 20 51 PM

. 
Screen Shot 2020-09-17 at 2 51 00 PM

Screen Shot 2020-09-17 at 2 49 59 PM
Screen Shot 2020-09-17 at 2 50 14 PM

$drag-indicator and $drag-indicator-dark.

Notice the yellow drag handle.
Screen Shot 2020-09-17 at 2 50 14 PM

$spacer-color and $spacer-color-dark.
Spacer Block
Screen Shot 2020-09-17 at 2 44 34 PM
</details>

### With the true colours. 

<details><summary>iOS</summary>

Screen Shot 2020-09-17 at 3 27 13 PM
Screen Shot 2020-09-17 at 3 27 20 PM
Screen Shot 2020-09-17 at 3 27 24 PM
Screen Shot 2020-09-17 at 3 27 30 PM
Screen Shot 2020-09-17 at 3 27 35 PM
Screen Shot 2020-09-17 at 3 27 44 PM

Toolbar
Screen Shot 2020-09-17 at 3 28 25 PM

Modal 
Screen Shot 2020-09-17 at 3 28 49 PM
Screen Shot 2020-09-17 at 3 29 52 PM
Screen Shot 2020-09-17 at 3 29 41 PM

iOS DarkMode
Screen Shot 2020-09-17 at 3 32 51 PM
Screen Shot 2020-09-17 at 3 33 00 PM
Screen Shot 2020-09-17 at 3 33 13 PM
Screen Shot 2020-09-17 at 3 33 30 PM

Modal
Screen Shot 2020-09-17 at 3 31 59 PM
Screen Shot 2020-09-17 at 3 32 37 PM
Screen Shot 2020-09-17 at 3 31 26 PM

Screen Shot 2020-09-17 at 3 33 41 PM
Screen Shot 2020-09-17 at 3 33 48 PM

Toolbar
Screen Shot 2020-09-17 at 3 34 57 PM
</details>

<details><summary>Android</summary>

Blocks

Screen Shot 2020-09-17 at 3 43 11 PM
Screen Shot 2020-09-17 at 3 43 21 PM
Screen Shot 2020-09-17 at 3 43 32 PM
Screen Shot 2020-09-17 at 3 43 40 PM
Screen Shot 2020-09-17 at 3 43 54 PM
Screen Shot 2020-09-17 at 3 45 18 PM
Screen Shot 2020-09-17 at 3 45 44 PM
Screen Shot 2020-09-17 at 3 46 04 PM

Toolbar
Screen Shot 2020-09-17 at 3 44 06 PM

Modal 
Screen Shot 2020-09-17 at 3 44 37 PM
Screen Shot 2020-09-17 at 3 44 50 PM

### DarkMode

Blocks

Screen Shot 2020-09-17 at 3 47 10 PM
Screen Shot 2020-09-17 at 3 47 22 PM
Screen Shot 2020-09-17 at 3 47 33 PM
Screen Shot 2020-09-17 at 3 47 41 PM
Screen Shot 2020-09-17 at 3 47 51 PM

Modal
Screen Shot 2020-09-17 at 3 48 21 PM
Screen Shot 2020-09-17 at 3 48 34 PM
Screen Shot 2020-09-17 at 3 48 55 PM
Screen Shot 2020-09-17 at 3 49 08 PM

Toolbar
Screen Shot 2020-09-17 at 3 48 04 PM

</details>

## Types of changes
Color Refactor.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by enejb** [comment]
Just pushed a change that updates the dark mode to 
Screen Shot 2020-09-17 at 4 52 06 PM
Screen Shot 2020-09-17 at 4 51 58 PM
Screen Shot 2020-09-17 at 4 51 55 PM

And light more do
Screen Shot 2020-09-17 at 4 54 38 PM
Screen Shot 2020-09-17 at 4 54 59 PM
Screen Shot 2020-09-17 at 4 55 06 PM

**Comment by guarani** [comment]
This PR focuses on border colors, but I just want clarify one aspect of this, dashed border colors. 

Looking at the changes regarding dashed border colors, I see:

| Before | After |
| - | - |
| `$gray` (`#87a6bc`)<br>`light-gray-500` (`#e2e4e7`)  | `$border-dashed-color` (`rgba($black, 0.25)`) |
| `$gray-70` (`#3c434a`)<br>`rgba($color: $light-gray-500, $alpha: 0.3)` | `$border-dashed-color-dark` (`rgba($white, 0.27)`) |

What I don't understand is where these conversions are coming from, could you please clarify this?

Also, I'm not able to test this unfortunately, the branch needs updating and I get quite a few linter errors when running `git merge --continue` after manually resolving the conflicts. Let me know if there's anything I can do to help!

**Comment by iamthomasbishop** [comment]
> What I don't understand is where these conversions are coming from, could you please clarify this?

@guarani Good question! They're discrete values, chosen specifically so that the _optical weight_ of the dashed border is roughly the same as the standard border when side-by-side.

**Comment by guarani** [comment]
Un-assigning myself here as I'm no longer working on the editor part of the app.

**Comment by enejb** [comment]
I am closing this now since I think we should come up with a different approach to unifying the colours in the editor. This PR was trying to do too much.

**Pull request closed without merging**
