### PR TITLE
Accessibility: Fix the accessibility of the url input using a combobox

### LINKED ISSUE #2083: The link modal posts list suggestion is not accessible
The link modal posts search / suggestions merged via #1985 

screen shot 2017-07-24 at 13 58 25

should be implemented as an ARIA combobox widget + listbox as done for the Tags suggestion. This was originally noted in the related issue #1040 but the implementation missed to address any accessibility feature.

The PR mentions this:
> This needs some Accessibility eyes, We can navigate using arrows but I guess this is far from perfect.

So I'm opening a specific issue. The UI should basically replicate what was already done for the Tag suggestions, see #1141. I hope the great work done there can be re-used easily. Worth also considering some abstraction.

Worth noting the current implementation is actually an a11y regression compared to the current functionality in WordPress.

### PR DESCRIPTION
**Pull request by youknowriad**
follow-up to #1995 closes #2083 

This PR uses a "combobox" for the post list suggestions and adds some a11y messages.

### CODE REVIEW

**Comment by afercia** [comment]
@youknowriad thanks very much! Noticed a couple things:

When the first option is highlighted, `aria-activedescendant` is not set:

screen shot 2017-07-31 at 12 49 53

When highlighting the other options, it is set. However, all the options have the same ID:

screen shot 2017-07-31 at 12 50 32

not sure it this is because it re-renders every time (seems to me the Tags suggestion don't re-render instead).

Additionally, in the current core implementation (see `wp-includes/js/tinymce/plugins/wplink/plugin.js`) a message `Link inserted.` is used when the link is successfully inserted. I guess this should be done in the other components every time a link is inserted: Enter on the field, click on the button, click/Enter on the highlighted option.

Can't test in Firefox+NVDA because right now there's a JS error, happens also on master:

screen shot 2017-07-31 at 12 33 54

**Review by afercia — DISMISSED** [review]
Please see comment.

**Comment by youknowriad** [comment]
The "Link inserted." message is a bit outside of the scope of this PR since it's not related to the URL input component.

**Comment by afercia** [comment]
Thanks! Looks good to me. Still can't test on Firefox because of the JS error, that seems to me related to the selection range so I'd say it's unrelated to this PR.

To clarify the importance of `aria-activedescendant` and the IDs: VoiceOver works well with just `aria-selected="true"` while other screen readers need `aria-activedescendant` and correct IDs.

> The "Link inserted." message is a bit outside of the scope of this PR since it's not related to the URL input component.

Sure, will open a separate issue.

**Pull request merged**
