### PR TITLE
Remove absolute position from svgs

### PR DESCRIPTION
**Pull request by Kluny**
When an SVG is set as a post's featured image, it overflows the image container. This is because the browser doesn't recognize an svg's height. Since theimage is positioned absolutely, the broswer allocates 0 height to the svg, and the image container collapses. This only happens with svgs, so the absolute position attribute is removed from that image type.

## How Has This Been Tested?
- Create a test post using Gutenberg.
- Upload a jpg image as featured image. 
- Observe that it looks just fine on the page. 
- Allow SVG media uploads by adding the following snippet to your functions.php:

```function mime_types($mimes) {
    $mimes['svg'] = 'image/svg+xml';
    return $mimes;
}
add_filter('upload_mimes', 'mime_types');
```
- Upload an svg image.
- Set it as featured image on your test post. 
- Observe that it overflows the featured image container and looks terrible.
- Apply my patch; run npm; refresh.
- Observe that the svg does not overflow the container anymore.
- Replace it with a jpg again.
- See that the jpg looks okay as well.

## Screenshots (jpeg or gifs if applicable):
Before:
screen shot 2018-03-12 at 15 21 24

After:
screen shot 2018-03-12 at 15 23 25

## Types of changes
Bug fix - solves #5477 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
I'm wondering if this should be something we solve more generically from within the `ResponsiveWrapper` component, when `naturalWidth` and `naturalHeight` props are provided as non-finite values. In this case, they're being passed as `undefined` because the server doesn't have the data about the dimensions of the SVG image.

Maybe something like this:

```diff
diff --git a/components/responsive-wrapper/index.js b/components/responsive-wrapper/index.js
index 3b9957862..e019f1221 100644
--- a/components/responsive-wrapper/index.js
+++ b/components/responsive-wrapper/index.js
@@ -17,12 +17,24 @@ function ResponsiveWrapper( { naturalWidth, naturalHeight, children } ) {
 	if ( Children.count( children ) !== 1 ) {
 		return null;
 	}
-	const imageStyle = {
-		paddingBottom: ( naturalHeight / naturalWidth * 100 ) + '%',
-	};
+
+	const hasFiniteDimensions = (
+		Number.isInteger( naturalHeight ) &&
+		Number.isInteger( naturalWidth )
+	);
+
+	let paddingBottom;
+	if ( hasFiniteDimensions ) {
+		paddingBottom = ( naturalHeight / naturalWidth * 100 ) + '%';
+	}
+
+	const classes = classnames( 'components-responsive-wrapper', {
+		'has-finite-dimensions': hasFiniteDimensions,
+	} );
+
 	return (
-		<div className="components-responsive-wrapper">
-			<div style={ imageStyle } />
+		<div className={ classes }>
+			<div style={ { paddingBottom } } />
 			{ cloneElement( children, {
 				className: classnames( 'components-responsive-wrapper__content', children.props.className ),
 			} ) }
diff --git a/components/responsive-wrapper/style.scss b/components/responsive-wrapper/style.scss
index 47d0f4aa1..dc756d9b0 100644
--- a/components/responsive-wrapper/style.scss
+++ b/components/responsive-wrapper/style.scss
@@ -1,18 +1,14 @@
 .components-responsive-wrapper {
 	position: relative;
 	max-width: 100%;
-}
 
-.components-responsive-wrapper__content {
-	position: absolute;
-	top: 0;
-	right: 0;
-	bottom: 0;
-	left: 0;
-	width: 100%;
-	height: 100%;
+	&.has-finite-dimensions .components-responsive-wrapper__content {
+		position: absolute;
+		top: 0;
+		right: 0;
+		bottom: 0;
+		left: 0;
+		width: 100%;
+		height: 100%;
+	}
 }
-
-img[src$=".svg"].components-responsive-wrapper__content {
-	position: static;
-}
\ No newline at end of file
```

**Comment by aduth** [comment]
I think the wrapper could even be enhanced further to do client-side detection of its own content. An SVG image _does_ have its own `naturalWidth` and `naturalHeight` properties we could be using.

**Comment by Kluny** [comment]
That looks like a good idea, I'll try it now. 

I can establish whether or not the image is an svg using something like this - 

```
async function getImageBlob(imageUrl) {
    const response = await fetch(imageUrl);
    return response.blob();
}

const blob = getImageBlob(children.props.src);
blob.then(function(defs){
    console.log(defs.type); // result is "image/svg+xml"
});```

Not sure whether it's kosher to toss in another image request like that? But I can't see how else to get the image type info out of ResponsiveWrapper's children parameter, let alone size info. 

Think it's worthwhile to check definitively whether the object is an svg, or just keep it as general as possible?

**Comment by aduth** [comment]
Dimensions can be retrieved via the [`Image` constructor](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image):

```js
const img = new Image;
img.onload = () => console.log( img.naturalWidth );
img.src = 'https://assets-cdn.github.com/pinned-octocat.svg';

// 150
```

**Comment by aduth** [comment]
>Not sure whether it's kosher to toss in another image request like that? But I can't see how else to get the image type info out of ResponsiveWrapper's children parameter, let alone size info.

The original issue is partly caused by the fact that we're not requesting the image itself, we're requesting details about the media item from the REST API, and unfortunately it doesn't include these dimensions for SVG images.

I'd be curious if we could avoid the first request altogether (for the media data) and reimplement Responsive (or a further abstraction on top of it, ResponsiveImage) to be the only one to request anything about the image.

Though I note this as a potential future enhancement, because it could require a fair bit of refactoring.

**Comment by Kluny** [comment]
> we're requesting details about the media item from the REST API, and unfortunately it doesn't include these dimensions for SVG images.

I still don't quite understand how SVG images can have height and width properties. I thought SVGs were just a set of instructions about the shape of an image, and you're supposed to supply your own size?

**Comment by aduth** [comment]
@Kluny Hmm, I'm not too sure how the browser decides to assign `naturalWidth` and `naturalHeight` for these images. An SVG does have a [`viewBox`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewbox) defined, from which it can be possible to determine aspect ratio, so maybe it just assigns some default size if not otherwise [explicitly assigned](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width). For our purposes, we really only care about the aspect ratio, so if the size is not precisely "correct", it should be fine.

**Comment by aduth** [comment]
Is it likely this will be resumed, or can it be closed?

**Comment by aduth** [comment]
Closing as stale without response. It can be reopened if development is expected to continue, or a new pull request can be submitted.

**Pull request closed without merging**
