### PR TITLE
Tests: Jest - Add typeahead plugin

### PR DESCRIPTION
**Pull request by ItsJonQ**
Screen Capture on 2020-06-22 at 11-21-12

This update adds a [type ahead](https://github.com/jest-community/jest-watch-typeahead) plugin for Jest. This feature use to be part of Jest core. However, it was abstracted out a couple of years ago. It's a tiny interaction that adds a lot of value for dev experience in regards to testing.

## How has this been tested?

* run `npm install`
* run `npm run test-unit:watch`
* press `p` to pause the tests
* press `p` again to go into "Pattern Mode"
* start typing
* check out the typeahead matching
* press up/down arrows to go through the list
* press enter to run the test

## Checklist:
- [x] My code is tested.
- [n/a] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
This is cool, it seems the package-lock  diff is too big though no? cc @gziolo

**Comment by gziolo** [comment]
Nice, I think you need to apply changes to `package-lock.json` again using the version from the main branch. It shouldn’t be more than a few hundreds of lines changed.

It looks like I didn’t use interactive mode for a while so I missed that 😃Good idea to bring it back 👍

**Review by gziolo — APPROVED** [review]
Cool, now npm applied changes correctly 🎉

**Comment by ItsJonQ** [comment]
@gziolo Yay! Thank you! Let's hope Travis is happy 🙏

**Pull request merged**
