### PR TITLE
Refactor DatePicker to use React hooks

### PR DESCRIPTION
**Pull request by truchot**
## Description
Related to #22890

## How has this been tested?
1. Edit page or post
2. Click on post schedule date
3. Change date

## Types of changes
Refactor to use React hooks.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ZebulanStanphill — CHANGES_REQUESTED** [review]

**Review by ZebulanStanphill — APPROVED** [review]
LGTM (looks good to merge)!

**Comment by ZebulanStanphill** [comment]
It looks like the unit test failures are legitimate. The tests need to be updated due to the changes made to the component. The tests are trying to call `getMomentDate`, which was previously a method of the `DatePicker` class. I'm not sure what the correct solution is at the moment.

**Comment by talldan** [comment]
Probably the easiest option is to extract `getMomentDate` so that it's defined separately to the component. The function would need to be changed to accept `currentDate` as a parameter.

It could then be exported as a named export from the file and imported into the test.

The other option is to keep it internal and try to make similar assertions on the output of the component itself, but that seems a bit more complicated.

**Comment by truchot** [comment]
I'm not sur to understand what I have to do…

**Comment by torounit** [comment]
@truchot 

for testing `getMomentDate` 

1. Move `function getMomentDate` out of `DatePicker`
2. export `getMomentDate` and import in test/date.js.
3. update line `const momentDate = wrapper.instance().getMomentDate();`

**Comment by aristath** [comment]
This PR will need to be rebased to fix the merge conflict and also reset the tests that got stuck 👍

**Comment by Mamaduka** [comment]
Hello, @truchot 

If you have time to rebase the PR, I think we can merge your updates.

**Comment by amustaque97** [comment]
Closing this PR in favour of https://github.com/WordPress/gutenberg/pull/36835

**Pull request closed without merging**
