### PR TITLE
Only apply the social links block migration if there's a need for a migration

### LINKED ISSUE #37542: Social block: block spacing attribute lost if no justification set
### Description

If the block gap attribute is set using the `Block spacing` setting, but a justification setting is not selected, then the block gap attribute is lost when the post is reloaded in the editor:

### Step-by-step reproduction instructions

- Add a Social block
- Add 2 or 3 Social links child blocks
- Set the block spacing to a > 0 value
- Save the post and reload - note that the block spacing value is lost
- Repeat the above but this time also set a justification option before saving and reloading and note that this time the block gap value persists

### Screenshots, screen recording, code snippet

Gap attribute wiped if no justification set:
social-gap-no-justification

If justification is set then the block gap attribute is retained as expected:

social-gap-justification

### Environment info

WP 5.8 and Gutenberg  12.2.0-rc.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #38549: Social Icons 'block spacing' resets after saving
### Description

(FYI I also posted this [here](https://core.trac.wordpress.org/ticket/55088) but as @mauriac mentioned it seems Gutenberg related)

When editing a social icons block, and you set some pixels to the block spacing, hitting save works as expected. Leaving the editing area and entering again, the block spacing field resets, and if you make other changes to the page and hit save. The icons reset their distance.

This was tested on both twentytwentytwo, and blockbase themes, on 3 different installs, locally and on a server.

### Step-by-step reproduction instructions

1. Ad a social icon block
2. Set a spacing
3. Hit save and leave the editor
4. Enter the editor again, the spacing should be reseted
5. Change something else in the page and hit save.
6. Social blocks spacing is removed on the frontend.

### Screenshots, screen recording, code snippet

https://www.youtube.com/watch?v=CBRiVSCuO9U

### Environment info

WordPress 5.9, Full site editing, twenty-twenty two theme and blockbase. Local and server environment.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #38549 
closes #37542 

By default all social links blocks were running through a block deprecation even if they were valid and didn't need the said migration. That's because the migration was checking if layout is undefined, but the layout is undefined by default (default value). The migration running was causing the `style` attribute to get removed because when the migration was added, the style attribute was not present on the "social links" block yet.

This PR fixes by only running the migration on the blocks that really need it (old blocks with old justification classnames).

### CODE REVIEW

**Comment by youknowriad** [comment]
@ntsekouras It seems we have a problem here (see the failing unit test). Basically, for blocks created with the old itemJuistification thing, there's no way for us to know whether the block need migration at the moment where isEligible is called :( because that information is not yet in any attribute (not even `className`). Basically that deprecation is useless and I'm not sure how to solve this. 

Maybe we could accept that social icons blocks created with justification applied in WP 5.8 become invalid. I'd appreciate any ideas.

**Comment by youknowriad** [comment]
We could potentially add the "rawBlock" as a third argument of the `isEligible` function call but it seems like a decision based on a random issue rather than something conceptually right.

**Comment by youknowriad** [comment]
isEligible function is very bad right now, it receives "raw attributes" (comment attributes) and "parsed inner blocks". It's not really coherent. The ideal solution potentially would have been to receive both `rawBlock` and `parsedBlock` objects. It would have been more clear and would have given all the required information to make the call.

**Comment by ntsekouras** [comment]
>The ideal solution potentially would have been to receive both rawBlock and parsedBlock objects. It would have been more clear and would have given all the required information to make the call.

You mean these two and loose the current second param(innerBlocks), correct? That would make sense and for back compat we could make an enhancement to just add a new object with the extra data.

Having said that, even if we add this info I don't see how it can solve our problem. It seems more to me we would need an API with `isEligible` and call the current `save` function of the block (not in the deprecation).

>Maybe we could accept that social icons blocks created with justification applied in WP 5.8 become invalid. I'd appreciate any ideas.

This deprecation was added without taking into account that the `save` function changes 😄 and it was there to cover actually the specific case that was a bug in the implementation in the first place (see https://github.com/WordPress/gutenberg/pull/34493).

>I've [found a bug](https://github.com/WordPress/gutenberg/issues/34003) in `Social Icons` block regarding `itemsJustification` attribute which was introduced in https://github.com/WordPress/gutenberg/pull/28980 and wasn't declared in block.json. With this PR the issue will be resolved as we remove its usage.

So IMO this deprecation could be deleted and accept the fact that blocks with the old `baggy` markup will not have the justification that was set back then. Since then I believe and hope many of that blocks managed to migrate to `layout` attribute and the impact will not be big. In addition the front-end will be displayed as expected because the legacy css classes are there and we only add the `justify-content` property in `layout.php` only if it's set from `layout` object. This doesn't happen in editor because we set the default to `flex-start`. So even smaller impact..?

**Comment by youknowriad** [comment]
@ntsekouras I removed the deprecation, I think that's fine, blocks won't be invalid right? since it will be just a custom class if I'm not wrong.

**Review by ntsekouras — APPROVED** [review]
LGTM! Thanks!

I tested with the removed now markup(`core__social-links__deprecated-1.html`) and some variations - different classes. My observations in my [previous testing](https://github.com/WordPress/gutenberg/pull/38561#issuecomment-1031565413) are still the same. No invalidations and the only view that get's affected is in the editor.

**Pull request merged**
