### PR TITLE
Change all occurrences of 'new window' to 'new tab'.

### LINKED ISSUE #10697: Change all the occurrences of `new window` to `new tab`
Worth considering in core all occurrences of `(opens in a new window)` have been changed to `(opens in a new tab)`, see https://core.trac.wordpress.org/ticket/43803 which will be released in 5.1 (note: not in 5.0).

In Gutenberg, the occurrences of `new window` are sometimes used for visually hidden accessible text and sometimes as visible labels. Regardless, for consistency and preparation with the change landing in core, I'd propose to change all occurrences to `new tab`.

### PR DESCRIPTION
**Pull request by afercia**
## Description
Quoting from the related issue #10697

Worth considering in core all occurrences of `(opens in a new window)` have been changed to `(opens in a new tab)`, see https://core.trac.wordpress.org/ticket/43803 which will be released in 5.1 (note: not in 5.0).

In Gutenberg, the occurrences of `new window` are sometimes used for visually hidden accessible text and sometimes as visible labels. Regardless, for consistency and preparation with the change landing in core, I'd propose to change all occurrences to `new tab`.

Clarification, quoting from the Trac ticket:
> today, it's very likely that browsers will open links with a target="_blank" attribute in a new browser's tab rather than in a new window. It is true that this depends also on user settings, but in the vast majority of the cases they will open in a new tab.

Fixes #10697

### CODE REVIEW

**Review by Luciaisacomputer — APPROVED** [review]
Looks good to me.

**Comment by afercia** [comment]
The build fails, one more case of test `Demo content post › should be created with keyboard` failing @aduth

**Comment by danielbachhuber** [comment]
Merged master to fix the failing build.

**Review by tofumatt — APPROVED** [review]
Works for me! 👍

**Pull request merged**
