### PR TITLE
Update Global Styles code to continue adding settings & styles

### PR DESCRIPTION
**Pull request by oandregal**
Related thread https://github.com/WordPress/gutenberg/pull/38039#discussion_r808702086

This PR renames the `wp_get_global_*` functions to `gutenberg_get_global_*` and updates all the instances in which we use them in the plugin. The rationale for this change is that we're not done adding settings & styles to `theme.json` and we need the Gutenberg plugin to keep iterating while supporting WordPress 5.8 and WordPress 5.9.

Examples of PRs in which we may need these are https://github.com/WordPress/gutenberg/pull/38039 https://github.com/WordPress/gutenberg/pull/32499 https://github.com/WordPress/gutenberg/pull/37770 https://github.com/WordPress/gutenberg/pull/32502 https://github.com/WordPress/gutenberg/pull/38319 Because there're so many of them and we don't know which PR will land first, I've gone ahead and prepared this PR to fast-track these changes so the PRs above can focus on feature work.

## How to test

Automated tests should pass. Load a block-base theme and verify that it works as expected.

### CODE REVIEW

**Comment by oandregal** [comment]
cc a few folks for awareness/review.

**Comment by Mamaduka** [comment]
Should we move these functions out of the `compat/wordpress-5.9` dir?

**Comment by oandregal** [comment]
> Should we move these functions out of the `compat/wordpress-5.9` dir?

Nah, we don't need to. This PR just renames things but does not make any behavioral change we need to port to 6.0 for these functions.

**Comment by oandregal** [comment]
:thinking: Well, at the point the plugin minimum WordPress version is 5.9, the `lib/compat/5.9` folder will be removed. However, at that point, we still want the plugin to use the plugin classes, hence, we'll need to move them to 6.0 then. We may as well move them now.

Pushed that change at https://github.com/WordPress/gutenberg/pull/38883/commits/893e087bbfb031f279661f328726a6042fe1cfaf

**Review by andrewserong — COMMENTED** [review]
Thanks for opening this PR @oandregal! This is now allowing settings to be updated in the post editor, but it looks like updated settings in Gutenberg aren't being loaded in the site editor.

To test, I added a couple of changes from #38039:

* Copied over the changes to `lib/compat/wordpress-6.0/class-wp-theme-json-gutenberg.php`
* In my `theme.json` file, added a `settings.layout.position` key set to value `true`.

In the post editor, I can call `wp.data.select( 'core/block-editor' ).getSettings();` in the browser console and in the returned object under `__experimentalFeatures` I can see the `position: true` value:

image

However, in the site editor, that value isn't being returned:

image

I couldn't quite work out why, though, as I assumed the hook in [block_editor_settings_all](https://github.com/wordpress/gutenberg/blob/526fc2c4adcdc00157836446ff1c34a9d82f3f0e/lib/global-styles.php#L214) should have been allowing the GB settings to override those in core in `edit-site-page.php` [where it calls get_block_editor_settings](https://github.com/wordpress/gutenberg/blob/cd2792da11bf49431429992ccbf7a6551341f378/lib/full-site-editing/edit-site-page.php#L134-L135).

Is there something else we need to add in so that those settings are exposed in the site editor?

**Comment by andrewserong** [comment]
> Should we move these functions out of the compat/wordpress-5.9 dir?

This is a really interesting idea / discussion. I've opened up a separate issue (https://github.com/WordPress/gutenberg/issues/38900) for thinking a bit more about this 🙂

**Comment by ramonjd** [comment]
> This is now allowing settings to be updated in the post editor, but it looks like updated settings in Gutenberg aren't being loaded in the site editor.

@andrewserong The Site Editor store settings appear to have the correct `__experimentalFeatures` but the results from `useGlobalStylesOutput();` do not. 

`useGlobalStylesBaseConfig` in `global-styles-provider.js` pulls its data via `__experimentalGetCurrentThemeBaseGlobalStyles()`, which fetches `/wp/v2/global-styles/themes/${ currentTheme.stylesheet }` (in packages/core-data/src/resolvers.js)

It's long and round about way of saying that you have to copy the public function `get_theme_item` from lib/compat/wordpress-5.9/class-wp-rest-global-styles-controller.php into the `compat/6.0` equivalent. This is because `get_theme_item` refers to `WP_Theme_JSON_Resolver_Gutenberg` and, indirectly, your new properties :) 

That should ensure the Site Editor knows about the settings. Here's how it looks for me:

Screen Shot 2022-02-18 at 1 06 06 pm

**Comment by andrewserong** [comment]
Nice one, thanks @ramonjd, that gets it working for me with both the block-editor and edit-site stores. E.g. calling the following now makes the `position: true` setting available, with that change applied:

```
wp.data.select( 'core/block-editor' ).getSettings();
wp.data.select( 'core/edit-site' ).getSettings();
``` 

@oandregal — can we add the `get_theme_item`, `prepare_item_for_database`, and `prepare_item_for_response` functions from the 5.9 rest controller for global styles to the 6.0 file? I wasn't sure if there are more functions we need than those three, but from a quick look they're the only ones that refer to Gutenberg-specific functions?

**Comment by ramonjd** [comment]
I've cherry picked these changes for a couple of PRs and things are working for me as expected:

- https://github.com/WordPress/gutenberg/pull/38319 
- https://github.com/WordPress/gutenberg/pull/38816

For both the site and post editors, I can:

✅  See the new settings in `__experimentalSettings` and other global settings
✅  See the block and global classes and styles rendered in the page on the frontend 
✅  Use new block supports in the editors, and see my changes reflected on the frontend.

All other functionality appears (at least to me) to work fine. Might need a more experienced eye to confirm this though. 

🍺 Thank you again for confirming the approach on this one. Great to see that we were all on the same page to some extent.

**Review by aaronrobertshaw — COMMENTED** [review]
@andrewserong and @ramonjd beat me to this. 

Thanks for collecting all the required edits in this PR @oandregal 👍 

I'd like to second @andrewserong's requests for additional functions to be copied to the global styles controller.

> can we add the get_theme_item, prepare_item_for_database, and prepare_item_for_response functions from the 5.9 rest controller for global styles to the 6.0 file?

The `get_theme_item` and `prepare_item_for_response` functions were needed at a minimum for me to get PRs extending [border support](https://github.com/WordPress/gutenberg/pull/37770) and adding [height](https://github.com/WordPress/gutenberg/pull/32499)/[width](https://github.com/WordPress/gutenberg/pull/32502) support back to working again in the Site Editor.

- `get_theme_item` was needed to maintain the new settings
- `prepare_item_for_response` fixes global styles "disappearing" after hitting save
- `prepare_item_for_database` would pave the way for potential updates to the theme.json schema so I think makes sense to include now.

Thanks again everyone for working through these issues 🙇

**Comment by oandregal** [comment]
Nice catch, @ramonjd ! Pushed that change as well https://github.com/WordPress/gutenberg/pull/38883/commits/9968127d0d8292176fda55c4d8c0a5b1fc9cfb49

**Review by andrewserong — APPROVED** [review]
Excellent, thanks for following up @oandregal! This is working nicely for me now, manually applying my changes from #38039 to this changeset — the additional sticky position support (and settings) work within both the post and site editors, and custom global styles can still be saved and loaded from the site editor.

LGTM!

**Pull request merged**
