### PR TITLE
Block navigation with keydown

### PR DESCRIPTION
**Pull request by ephox-mogran**
## Description

Removed keyup handling for writing-flow and made keydown navigate blocks

## How Has This Been Tested?

I have manually tested this, but not exhaustively

## Types of changes

Cross between a bug fix and a new feature

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation (no existing documentation)

### CODE REVIEW

**Comment by ephox-mogran** [comment]
I'm not sure if this is the best approach. We may want to keep the keyup handling in there, and just fire movement on subsequent keydowns using the previous shouldMove state value. Thoughts?

**Comment by iseulde** [comment]
This reverts 961c92caa87b9f16271ced8b768fc4f7d71b0f5c. @youknowriad Do you remember why it was done this way?

**Comment by youknowriad** [comment]
Because of this https://github.com/WordPress/gutenberg/pull/2894#issuecomment-334690488

**Comment by youknowriad** [comment]
I can't seem to reproduce the original issue I had with `onKeyDown`, maybe this was fixed somewhere else 👍

**Review by ellatrix — APPROVED** [review]
Also looks good to me.

**Comment by iseulde** [comment]
Going to work further here: #2296.

**Pull request merged**
