### PR TITLE
RNMobile: Fix autoscroll on ListBlock

### PR DESCRIPTION
**Pull request by etoledom**
This is necessary to send an iOS only prop `onCaretVerticalPositionChange` to activate autoscroll when the caret is out of the viewport.

lists-autoscroll

To test:
- Follow the instructions in the [`gutenberg-mobile` side PR.](https://github.com/wordpress-mobile/gutenberg-mobile/pull/890)

### CODE REVIEW

**Comment by ellatrix** [comment]
Just curious: what happens for other blocks?

**Comment by ellatrix** [comment]
Also, ideally this kind of behaviour is built in, especially since we want to try to reuse block code?

**Comment by etoledom** [comment]
This block I believe is the first one we have "multiplatform" (sharing the `edit.js`) that uses RichText.

In all other blocks that use RichText, we have a `.native.js` version where we pass `onCaretVerticalPositionChange` prop directly.

For example: 
https://github.com/WordPress/gutenberg/blob/53a9e94d28c0ca6f168d30d6db4bc5496ea8201a/packages/block-library/src/paragraph/edit.native.js#L105

>  ideally this kind of behaviour is built in

I agree! And it is built in for Android.

Sadly on iOS it needs to be handled manually. And we need to pass the caret information from Aztec native side to our custom autoscroll handler's native side.

**Comment by ellatrix** [comment]
Can it not be passed via context. There are several other things that are done via context instead of passing as props through the block, so that the block author doesn't have to worry about it.

**Comment by etoledom** [comment]
> Can it not be passed via context?

I did some investigation and tests and it seems to work. Thanks for pointing that out!
I'll update this PR on that direction. I might need some help on how to organize the code.

Thank you @ellatrix !

**Comment by etoledom** [comment]
Updated with the requested changes. Now `onCaretVerticalPositionChange` is passed via `withBlockEditContext` directly to `RichText`.

I took the opportunity to remove `onCaretVerticalPositionChange` from `Paragraph` and `Heading` blocks since they are not needed anymore.

cc @ellatrix @pinarol

**Review by pinarol — APPROVED** [review]
Tested with the parent PR. LGTM! 🎉

**Pull request merged**
