### PR TITLE
Revert conditional selects from #47243

### PR DESCRIPTION
**Pull request by jsnajdr**
Proposes to revert #47243 (partially, there were changes like new tests and test refactors that we're keeping) because:
- @youknowriad expressed concerns about the performance regressions this change caused
- it breaks `useSelect` usage in WooCommerce (https://github.com/woocommerce/woocommerce/pull/37641). It's Woo's fault that they're using the hook in a really bad way, but anyway.
- the WooCommerce breakage is breaking WordPress.com, too: https://github.com/Automattic/wp-calypso/issues/76000. This PR could be the emergency Gutenberg patch needed to fix that.

At the same time I'm not very happy about this revert because it brings back incorrect behavior of `useSelect`. For example, here's Google Site Kit folks discussing the bad behavior of conditional selects: https://github.com/google/site-kit-wp/issues/6356#issuecomment-1410242414 Apparently they've been running into the bug. Maybe @kuasha420 would have some feedback to share.

### CODE REVIEW

**Comment by adrianduffell** [comment]
> it breaks useSelect usage in WooCommerce (https://github.com/woocommerce/woocommerce/pull/37641). It's Woo's fault that they're using the hook in a really bad way, but anyway.

FWIW, in Woo we are committed to updating the broken usage of the hook.

**Comment by jsnajdr** [comment]
> FWIW, in Woo we are committed to updating the broken usage of the hook.

Thank you! I created this PR as a stand-by alternative in case the Woo fix was impractical or impossible to ship quickly to everyone affected.

**Comment by kuasha420** [comment]
@jsnajdr Thank you for the tag here and all your effort in the previous PR! I somehow missed that the last PR was merged. 

As I've documented previously in the linked issue, breaking conditional `select`s inside the `useSelect` callback or any selectors that were created with `createRegistrySelect` was a big issue for us because there's various places in Site Kit codebase where we do this. 

I can't really say if what we're doing is "correct" way to use `useSelect` these days, but it worked as expected in previous version. 

We'll probably try to upgrade our code base to use the version without this revert sometimes in the future to see if we face any issues.

Cheers.

**Comment by jsnajdr** [comment]
Thanks @kuasha420 for the info on how you use `useSelect` in `site-kit-wp`. In the latest version of `@wordpress/data`, conditional selects should always work correctly, and should always subscribe to all relevant data stores. But we are considering reverting this change, because it causes a 5% performance regression.

One thing I didn't previously realize is the connection between conditional selects and `createRegistrySelector`. Normally, to make conditional selects work reliably, you only need to make sure that `select()` is always called on all stores the callback uses, like:
```js
useSelect( ( select ) => {
  const CoreUI = select( CORE_UI );
  const CoreUser = select( CORE_USER );
  return (
    CoreUI.getValue( runKey ) &&
    CoreUser.isTourDismissed( tourID ) === false
  );
} );
```
Here we always call `select( CORE_USER )`, and therefore reliably subscribe to `CORE_USER`, even if the `isTourDismissed` selector is not always called.

But what if `isTourDismissed` is a registry selector that conditionally selects from a third store? Like:
```js
const isTourDismissed = createRegistrySelector( ( select ) => ( state, slug ) => {
  const CoreUser = select( CORE_USER );
  const CoreSite = select( CORE_SITE );

  dismissedTourSlugs = CoreUser.getDismissedFeatureTourSlugs();

  if ( undefined === dismissedTourSlugs ) {
    dismissedTourSlugs = CoreSite.getDismissedTourSlugs();
  }

  return dismissedTourSlugs.includes( slug );
} );
```

Now we're in trouble because it's impossible to make sure that `select( CORE_SITE )` actually got called. We no longer have control over that, it's hidden inside the selector. If, on initial call, we don't select from `CORE_SITE`, we won't create a subscription to `CORE_SITE` updates. Then, some time later, `CORE_USER` data change in such a way that we start selecting from `CORE_SITE`, but we're not subscribed to `CORE_SITE` updates.

In https://github.com/WordPress/gutenberg/pull/47243#issuecomment-1493953664 @youknowriad suggested that we just document that conditional selects are not supported. That would work if we had a documented and reliable way how to avoid the problem, but with registry selectors I'm afraid we no longer have this.

**Comment by jsnajdr** [comment]
Seems there is no longer demand to perform the revert. Closing.

**Pull request closed without merging**
