### PR TITLE
Add a 'View Site' link in the site editor

### LINKED ISSUE #35758: Accessing the front-end from the site editor
## What problem does this address?

If I am not mistaken, it is rather tedious to access the front-end of the website after editing it in the site editor. When a page/post is edited and saved, a view page/post appears in the left bottom corner. This is not the case in the site editor. One has to open the left top menu (WordPress logo), navigate back and navigate via the dashboard to view the website’s front-end. This makes **4 clicks**.

## What is your proposed solution?
Maybe this will be addressed in the site preview (#29398). However, it would be nice to have direct access to the front-end in one click in the meantime.
In the left top menu (toggled by the WordPress logo),

- the site title could be a link to the front-end, or
- there could be a link to the front-end, like ‘Visit site’ (see screenshot for raw idea), like in the dashboard top toolbar.

Screenshot 2021-10-19 at 13 12 42

### LINKED ISSUE #42316: Site Editor: Add a link to view the site
To go from the site editor to viewing the frontend of your site is a long-winded exercise. It would be nice if there was a more direct pathway.

A couple of options:

**Add a link to the site title in the navigation panel**

Screenshot 2022-07-11 at 10 05 53

**Add a link to the 'Preview' menu**

Screenshot 2022-07-11 at 10 06 22

With this second option, we might consider [updating the button label](https://github.com/WordPress/gutenberg/pull/29151) since we do not have drafting functionality for templates / styles just yet, and so 'Preview' is a bit of a false promise.

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Add a link from the site editor to view the site.

## Why?
Because it is currently not within easy reach.

## How?
Added a new `MenuItem` to `PreviewOptions` in edit-site/components/header.

As a part of this update I've changed 'Preview' to 'View' for a couple of reasons:

1. There's no way to _pre_view site editor changes yet.
2. The device view options aren't strictly previews, they are just view modes for the canvas.

## Testing Instructions
1. Open the Site Editor
2. Click 'View' in the top toolbar
3. Click 'View Site'
4. Ensure the site homepage is opened in a new tab

## Screenshots or screencast 

https://user-images.githubusercontent.com/846565/178288203-cf071aa1-85aa-431b-8680-11eeee14941c.mp4

### CODE REVIEW

**Comment by javierarce** [comment]
I love this improvement. 

I just saw one thing:

In the post editor this produces the following redundancy:

Screenshot 2022-07-11 at 17 55 34

**Comment by jameskoster** [comment]
Oops 😅

I'll fix that when I get a moment.

**Comment by jameskoster** [comment]
OK I changed the implementation a bit so that the 'View Site' link only appears in the site editor. 

Updating the button label to 'View' in the Site Editor makes sense, I'm not 100% sure about the post editor though. There's value in consistency, and I maintain the viewpoint that the device switchers aren't strictly just previews, but the post editor does include a dedicated preview link. What do you think?

**Comment by paaljoachim** [comment]
Thank you James!!

This looks really good! I have been looking forward to seeing a View page drop down in FSE for quite a while.
Regarding wording...
Instead of a "Preview in new tab" we have the "View Site" (which I find more direct) and the icon which gives the signal that it opens in a new tab. 

Should another PR change the wording in a page and post?
As in "View page/Page" and "View post/Post"

**Comment by annezazu** [comment]
Just noting that this came up as something that would be welcomed in the [FSE Outreach Program's fifteenth call for testing](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/#comment-2608):

>Another thing that feels a bit bumpy is when saving the template, there’s no way to quickly access your site again. You have to manually create a new tab, write the URL and select the post/page/archive you were on. This may be a bit hard for specific archive templates but when implementing what I mentioned in the last paragraph, a referral URL could be stored inside Gutenberg as well, so that a link to the page the user was just on could be generated. Just like you have the “View post/page” links you have in the notifications that appear after saving a post or page.

In this case, the view site would happen post save flow, which to me is the best of both worlds since it helps avoid the confusion that might come from making changes, viewing site, and not seeing those changes there.

**Comment by talldan** [comment]
> Should another PR change the wording in a page and post?
> As in "View page/Page" and "View post/Post"

@paaljoachim There's a subtle difference in that the post editor preview will show unpublished changes, so it slightly different to just viewing the post. That may be a reason not to change the wording.

**Comment by paaljoachim** [comment]
Thanks for the reply, @talldan 

We could perhaps do a "Preview Post" / "Preview Page" and cut out the "in new tab" part in the drop down of posts and pages.
This is though a sidetrack to this PR though.

**Comment by talldan** [comment]
Similar to the quote in Anne's comment, I was also wondering if this is the right thing to show when editing say 'Archive' or 'Search', but when I tested I realised it's still quite useful and doesn't feel out of place. I imagine it's quite difficult to include a link directly to the relevant part of the website based on the template being edited.

I also wondered if the label could be something like 'View homepage'?

It also looks like the linting check has failed, this file needs to be formatted - packages/edit-site/src/components/header/index.js (`npm run format -- packages/edit-site/src/components/header/index.js` should do the trick).

**Comment by talldan** [comment]
> We could perhaps do a "Preview Post" / "Preview Page" and cut out the "in new tab" part in the drop down of posts and pages.

True, that could be simplified. Usually there's some hidden text for screen readers that says 'Opens in a new tab', so it doesn't necessarily have to be visible.

That reminds me, that hidden text should be added in this PR too.

@jameskoster That would involve using the `VisuallyHidden` component like this menu item does:
https://github.com/WordPress/gutenberg/blob/9f0e6be1c2ded47186ac4c009c798fa50d005177/packages/customize-widgets/src/components/more-menu/index.js#L71-L87

**Comment by jameskoster** [comment]
It might be a nice enhancement to explore template-specific 'view' links, but I suspect the logic could get a bit gnarly. Something to explore later methinks :)

I find 'View Site' and 'View Homepage' to essentially be the same thing, but happy to change if there are strong feelings either way.

**Comment by paaljoachim** [comment]
"View Site" the meaning I get is that site is really anywhere on the web site.
"View Homepage" for me means viewing the front page. As I have on occasion a link called "Home" which takes one back to the front page.

It is better to keep "View Site" as one would be viewing really any template one has active at the time. Be it an author/category/comments/404 or any other template. As one would modify a template in the site editor and just view the frontend of what the template looks like.

**Comment by talldan** [comment]
> It is better to keep "View Site" as one would be viewing really any template one has active at the time.

The link does always takes you to the homepage, as discussed above it won't take you to the template being edited.

**Comment by paaljoachim** [comment]
> The link does always takes you to the homepage, as discussed above it won't take you to the template being edited.

I have not yet found that discussion.
Is there a way that we can click "View Site" and it will open the current active template? As it would be very helpful if we could actually view a template that is being worked on. Rather than later on having to figure out how to view a specific template on the frontend.

As from (pre)viewing a post or page. It opens the actual post/page and not the homepage. So that we are used to seeing the current selected post/page on the frontend and transferring this over to the site editor would also very much help. (Example the various call for testings @annezazu usually adds a how to view the current template on the frontend step by adding an URL directly to the template.) If that is not possible or hard to do at present time, then having a step between would be helpful. As in opening the homepage by clicking "View Site".

**Comment by jameskoster** [comment]
> Is there a way that we can click "View Site" and it will open the current active template?

For me, the concept of 'viewing a template on the frontend' doesn't really make sense, and can quickly break down. As an example, what would happen if you tried to 'view' a template that isn't actually in use anywhere at the site? The idea of 'viewing' is content-centric, IE you view a post, a page, a category, etc. I'm not sure we should cross those streams.

When the site editing experience is also more content-centric (IE once [browse mode](https://github.com/WordPress/gutenberg/issues/23328) is implemented) it will make more sense to have contextual view links.

**Comment by paaljoachim** [comment]
Good point James! That crossed in the back of my mind. I was thinking that for some/many templates these could be viewed on the frontend. Browse mode will be helpful and solve the issue of viewing the template as it is seen on the frontend.

**Comment by richtabor** [comment]
Nice! Very welcome change. Tested it out and works as expected. 

One question, should it be `View site` instead? We use "Edit site" for the Admin bar, and "Visit Site" elsewhere; just want to see if there's opportunity for bringing these closer. 

CleanShot 2022-07-21 at 15 43 05@2x

CleanShot 2022-07-21 at 15 44 21@2x

**Review by talldan — APPROVED** [review]
This looks good and I think will be a really useful option. It could be a lower case 's' for 'site'. I often forget the rules around this, but I think most of the UI leans towards sentence case.

Some code formatting needs to be done before this can be merged. I think `npm run format -- packages/edit-site/src/components/header/index.js` is the command that'll sort that out.

**Comment by jameskoster** [comment]
Since 'site' is referring to a specific website, doesn't that make it a proper noun and therefore suitable to capitalisation? I am not a grammar expert either :D

**Comment by paaljoachim** [comment]
We should stick to sentence case as we usually do.
So "View site" would be correct. Grammer well..... It reminds me. We should change "List View" to "List view".....

**Comment by jameskoster** [comment]
Wouldn't nouns over-rule the case convention? 🤔

**Comment by talldan** [comment]
> Wouldn't nouns over-rule the case convention?

I refreshed my grammar skills, and came to the conclusion that I don't think I'd consider it a proper noun. If the button said the name of the site (e.g. 'View Making WordPress'), then I think it would be capitalised, but 'site' is a common noun for a website and should be lower case in a sentence.

I think a similar sentence would be something like "Exit the building" (common noun, so building is lower case) vs "Exit the Empire State Building" (proper noun. so the name of the building is upper case).

BTW, there are e2e tests that are failing and need updating because the test still expects the old name of the button (Preview instead of View) in the post editor. Are you happy to update those @jameskoster? If not, let me know and I'd be happy to add a commit to the branch.

**Comment by jameskoster** [comment]
@talldan what's the command to update the tests? 🙏

**Comment by talldan** [comment]
> @talldan what's the command to update the tests? 

It's a manual process of going through the failing tests and updating the selectors used to interact with the preview button.

**Comment by jameskoster** [comment]
Hopefully I did it correctly... let's see! 🙈

**Comment by talldan** [comment]
Looks spot on! There's a code formatting issue again to resolve in `packages/e2e-test-utils-playwright/src/editor/preview.ts`, but once that's sorted you should be able to merge.

**Comment by tomjn** [comment]
Noting that this didn't just change the preview button in the site editor, it changed it in all editors, including the post editor

**Pull request merged**
