### PR TITLE
Add pricing table pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a Pricing table section block pattern for #20345.

**⚠️ Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.**

<img width="1182" alt="Screen Shot 2020-03-04 at 19 13 41" src="https://user-images.githubusercontent.com/3276087/75938039-45cfe780-5e4c-11ea-9cab-a0cba0104539.png">

```
<!-- wp:group {"customBackgroundColor":"#f2f2f2","align":"full"} -->
<div class="wp-block-group alignfull has-background" style="background-color:#f2f2f2"><div class="wp-block-group__inner-container"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"customBackgroundColor":"#279bd1"} -->
<div class="wp-block-group has-background" style="background-color:#279bd1"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"align":"center","customTextColor":"#222222","fontSize":"large"} -->
<p style="color:#222222" class="has-text-color has-text-align-center has-large-font-size"><strong>Tier 1</strong></p>
<!-- /wp:paragraph -->

<!-- wp:separator {"className":"has-text-color has-background"} -->
<hr class="wp-block-separator has-text-color has-background"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Duis aute irure dolor in.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Reprehenderit in voluptate.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":220} -->
<div style="height:220px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">Select</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"customBackgroundColor":"#279bd1"} -->
<div class="wp-block-group has-background" style="background-color:#279bd1"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"align":"center","customTextColor":"#222222","fontSize":"large"} -->
<p style="color:#222222" class="has-text-color has-text-align-center has-large-font-size"><strong>Tier 2</strong></p>
<!-- /wp:paragraph -->

<!-- wp:separator {"className":"has-text-color has-background"} -->
<hr class="wp-block-separator has-text-color has-background"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Duis aute irure dolor in.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Reprehenderit in voluptate.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Cillum dolore</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":135} -->
<div style="height:135px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link">Select</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:group {"customBackgroundColor":"#279bd1"} -->
<div class="wp-block-group has-background" style="background-color:#279bd1"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"align":"center","customTextColor":"#222222","fontSize":"large"} -->
<p style="color:#222222" class="has-text-color has-text-align-center has-large-font-size"><strong>Tier 3</strong></p>
<!-- /wp:paragraph -->

<!-- wp:separator {"className":"has-text-color has-background"} -->
<hr class="wp-block-separator has-text-color has-background"/>
<!-- /wp:separator -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Duis aute irure dolor in.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Reprehenderit in voluptate.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Cillum dolore</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"customBackgroundColor":"#ffffff"} -->
<p style="background-color:#ffffff" class="has-background">Dolore eu fugiat</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"align":"center"} -->
<div class="wp-block-button aligncenter"><a class="wp-block-button__link">Select</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->
```

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. Let me know if you think it can be improved or if we should close this PR instead.

**Comment by mapk** [comment]
I think this is close, but can use a bit more design adjustments.

- Let's use real text.
- Work on the colors a bit more. I think we can find some really beautiful tertiary or complimentary colors.
- Maybe try using all caps in the buttons.

**Comment by enriquesanchez** [comment]
@mapk @mtias here's a revision:

Screen Shot 2020-04-13 at 15 44 30

**Comment by enriquesanchez** [comment]
@mapk Another iteration:

Screen Shot 2020-04-14 at 16 50 07

What do you think about the list block used for the plean features. Seemed like the most obvious block to use, but there's not much styling that can be applied to it.

**Comment by mapk** [comment]
This looks good for what we can currently achieve in Gutenberg. I like the direction. Let's merge it.

**Comment by mapk** [comment]
@enriquesanchez I noticed you did some more visual updates. Can you share a screenshot? One for the editor and one for the frontend. 🙏

**Comment by enriquesanchez** [comment]
@mapk 

## Inserter:

Screen Shot 2020-05-06 at 17 40 11

## Editor:

Screen Shot 2020-05-06 at 17 39 57

## Front-end:

Screen Shot 2020-05-06 at 17 40 22

------

Not sure what to do about the layout issue on the inserter. I can make the font smaller but that would obviously affect the front-end. 

This may also be a case of fine-tuning how we render previews in the inserter. Most patterns feel very tall and narrow. Is there something that could be done @youknowriad?

**Comment by mapk** [comment]
This should be refined so that the preview is strong before we merge it. If we can't get it there, @enriquesanchez, I suggest we just not merge this one.

**Comment by youknowriad** [comment]
> This may also be a case of fine-tuning how we render previews in the inserter. Most patterns feel very tall and narrow. Is there something that could be done @youknowriad?

Yes, @mtias opened this issue #22147 where we could choose a width per pattern solving this.

**Comment by enriquesanchez** [comment]
Looks like #22216 will let us fix the preview issues.

**Comment by enriquesanchez** [comment]
@mapk Now that `viewportWidth` [can be set for each pattern](https://github.com/WordPress/gutenberg/pull/22216), we can get the preview to display at better proportions:

Screen Shot 2020-05-15 at 14 09 11

(The missing separator on the 1st column is a preview artifact, but it is there).

I'm still not 100% satisfied with how the columns preview with uneven heights, but the output does look much better:

Screen Shot 2020-05-15 at 14 08 00

**Pull request closed without merging**
