### PR TITLE
Mobile Release v1.48.1

### PR DESCRIPTION
**Pull request by fluiddot**
**This PR can't be merged into `trunk` because [include changes that could break the web version](https://github.com/WordPress/gutenberg/pull/29445#issuecomment-795556922), specifically the changes from this [commit](https://github.com/WordPress/gutenberg/commit/956cdfc2a3aedfa2594d3adcde8a22ce19df7ba6).**

Similar to what was done in [`1.48.0` release](https://github.com/WordPress/gutenberg/pull/29686), we should have a different branch without those changes for merging the release into `trunk`.

## Description
Release 1.48.1 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3237

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
Looks good. Noticed the cherrypicked changes in the diff.  LGTM 👍🏾

**Review by jd-alexander — COMMENTED** [review]
@fluiddot just double-checking if we will be including the story-related changes here.

**Comment by fluiddot** [comment]
> @fluiddot just double-checking if we will be including the story-related changes here.

Good question! I see that the `1.47.2` hotfix with the story-related changes was already merged so makes sense to include it here, this way we avoid creating two betafixes.

**Comment by fluiddot** [comment]
@bjtitus  I merged the `1.47.2` hotfix changes into this release in this [commit](https://github.com/WordPress/gutenberg/pull/29680/commits/1c823f689a0bd5a331b96e5fe24038aa19e813ce).

**Review by jd-alexander — APPROVED** [review]
Changes here look good @fluiddot 

1. The splitting/merging functionality is reverted in our mobile release until the fix is completed. 
2. The iOS Story bridge behavior is included to resolve the Story issues. 
3. The page fetching logic that resolves the reusable block crash is operating as expected. 

LGTM. Awaiting CI to pass to verify all is well.

**Comment by fluiddot** [comment]
>Awaiting CI to pass to verify all is well.

The CI looks totally frozen so I don't think it's going to run 😞 . We could either:
1. Push a change to unblock it.
2. Clone the branch and create a new PR to see if they pass.

**Comment by jd-alexander** [comment]
> > Awaiting CI to pass to verify all is well.
> 
> The CI looks totally frozen so I don't think it's going to run 😞 . We could either:
> 
> 1. Push a change to unblock it.
> 2. Clone the branch and create a new PR to see if they pass.

Indeed. We could push an empty commit and see if that works.

**Comment by fluiddot** [comment]
Nope, I pushed an [empty commit](https://github.com/WordPress/gutenberg/pull/29680/commits/075faabe1545bef9025baaff29cf91baa5c9e785) but didn't work 😞 . I think this is most likely caused by having conflict files 🤷‍♂️ , I'm going to create a new branch for fixing the conflicts and there we'll see if the test pass.

**Comment by jd-alexander** [comment]
> Nope, I pushed an [empty commit](https://github.com/WordPress/gutenberg/pull/29680/commits/075faabe1545bef9025baaff29cf91baa5c9e785) but didn't work 😞 . I think this is most likely caused by having conflict files 🤷‍♂️ , I'm going to create a new branch for fixing the conflicts and there we'll see if the test pass.

You are right. I remember seeing this behavior with previous conflicts 👍🏾

**Comment by fluiddot** [comment]
Let's see if they pass in this [PR](https://github.com/WordPress/gutenberg/pull/29791).

I had to update that branch with `trunk` so it's not exactly the same PR, but at least it will give us some confidence to consider this PR ready.

**Comment by jd-alexander** [comment]
> Let's see if they pass in this [PR](https://github.com/WordPress/gutenberg/pull/29791).
> 
> I had to update that branch with `trunk` so it's not exactly the same PR, but at least it will give us some confidence to consider this PR ready.

Understood. So to ensure I understand clearly if that PR passes what will be done next? 

Also, will we be bypassing the failing PHP tests somehow? or are we waiting until they are resolved?

**Comment by fluiddot** [comment]
> > Let's see if they pass in this [PR](https://github.com/WordPress/gutenberg/pull/29791).
> > I had to update that branch with `trunk` so it's not exactly the same PR, but at least it will give us some confidence to consider this PR ready.
> 
> Understood. So to ensure I understand clearly if that PR passes what will be done next?

If the PR passes, we can consider the release ready and start merging the PRs, the first part would be to merge the Gutenberg-mobile PR to trunk, update the Gutenberg reference in the integration branches on `WPAndroid` and `WPiOS` and finally merge them.

> Also, will we be bypassing the failing PHP tests somehow? or are we waiting until they are resolved?

That's a good question, I don't think we can do much thing there apart from wait for a fix.

**Comment by jd-alexander** [comment]
> > > Let's see if they pass in this [PR](https://github.com/WordPress/gutenberg/pull/29791).
> > > I had to update that branch with `trunk` so it's not exactly the same PR, but at least it will give us some confidence to consider this PR ready.
> > 
> > 
> > Understood. So to ensure I understand clearly if that PR passes what will be done next?
> 
> If the PR passes, we can consider the release ready and start merging the PRs, the first part would be to merge the Gutenberg-mobile PR to trunk, update the Gutenberg reference in the integration branches on `WPAndroid` and `WPiOS` and finally merge them.

Indeed! Thanks for doing the GB reference update in the integration branches. Monitoring the builds.
> 
> > Also, will we be bypassing the failing PHP tests somehow? or are we waiting until they are resolved?
> 
> That's a good question, I don't think we can do much thing there apart from wait for a fix.

True.

**Comment by fluiddot** [comment]
This PR will be merged into `trunk` via a new [PR](https://github.com/WordPress/gutenberg/pull/29819) that reverts the [commit](https://github.com/WordPress/gutenberg/commit/956cdfc2a3aedfa2594d3adcde8a22ce19df7ba6) that we can't merge into that branch.

**Comment by fluiddot** [comment]
> This PR will be merged into `trunk` via a new [PR](https://github.com/WordPress/gutenberg/pull/29819) that reverts the [commit](https://github.com/WordPress/gutenberg/commit/956cdfc2a3aedfa2594d3adcde8a22ce19df7ba6) that we can't merge into that branch.

The changes have been merged into `trunk` branch via https://github.com/WordPress/gutenberg/pull/29819.

**Pull request closed without merging**
