### PR TITLE
Post Title Block - fix "'length' of undefined" error.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

In some circumstances the post title block well receive `undefined` as the title value from `post`:
https://github.com/WordPress/gutenberg/blob/aad00526980a69e0a21126db5e15de95247d6c85/packages/block-library/src/post-title/edit.js#L59

Which results in an error when we try to access the `length` property:
https://github.com/WordPress/gutenberg/blob/aad00526980a69e0a21126db5e15de95247d6c85/packages/block-library/src/post-title/edit.js#L92

Screen Shot 2021-03-24 at 2 21 04 PM

This can be reproduced consistently when we insert a Query block and its placeholder state is rendered:

Screen Shot 2021-03-24 at 2 21 13 PM

(notice the block errors in the above previews). 

Here, we define title to have a default value of the empty string so we are not using `undefined` for input values and logic conditions expecting strings.  

## How has this been tested?

After this change we should experience no console errors when inserting a query block, and the previews should show the proper placeholder of "No Title" instead of the block errors shown above:

Screen Shot 2021-03-24 at 2 22 45 PM

Also verify the post title block continues to work as expected in other flows.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by carolinan — APPROVED** [review]
I tested this PR together with 30203 and it is working well for me.

(I am curious why this error was present even if there were no published posts that were missing a title)

**Review by ntsekouras — COMMENTED** [review]
I noticed this error yesterday when doing: https://github.com/WordPress/gutenberg/pull/30203 and meant to see the root cause of this tomorrow. 

This seems an interim fix and not the fix for the root problem, so I don't think we should land this. In my quick check I think it has to do with `isLink` handling in Post Title, but I'll look at it tomorrow if it's not resolved by then :)

**Comment by carolinan** [comment]
I [caused it](https://github.com/WordPress/gutenberg/pull/29824#discussion_r593208423) so I will follow this closely  😬

**Comment by Addison-Stavlo** [comment]
> This seems an interim fix and not the fix for the root problem, so I don't think we should land this.

There may be a larger root to address, but I also think it makes sense to not assume we have retrieved a proper post object in every possible circumstance.  If we are going to show placeholder titles, we should do that when no proper post context is found as well.

Whats happening here is `postType` and `postId` come into the component as `undefined` for this post title block when the query placeholder is inserted somewhere that is not inside the context of a post (the root of the Index template for example).  This results in the `getEditedEntityRecord` returning an empty object `{}`, thus `title` and `link` are undefined.

There is not a problem once we are in the context of a post (placing this inside a page, post, or other query block), as it will pick up that context and show that title in the preview.  Since the query block is our means of supplying a post context to these blocks, I think its fair to assume in placeholder flow/setup that no context may exist.

**Comment by Addison-Stavlo** [comment]
> In my quick check I think it has to do with isLink handling in Post Title,

Sort of, its only triggered when `isLink` is true.  But it happens because of the lack of context supplies the `undefined` title.  

So it may be worthwhile to change the condition for the isLink version of the component from `if ( isLink )` to `if ( isLink && link )` (?), but I think defaulting the title to fallback to an empty string is still a warranted safety measure since we treat it as a string in all circumstances.

**Review by ntsekouras — APPROVED** [review]
Let's go with this for now and we can revisit especially with the changes in `Query` patterns that are being explored right now. Thanks!

**Pull request merged**
