### PR TITLE
Refactor the `core-data` store to thunks

### PR DESCRIPTION
**Pull request by jsnajdr**
Builds on top of the thunks support added in #27276 and refactors the `core-data` actions and resolvers.

Still a work in progress: we'll need to update unit tests and fix the request batching implementation before the updated editor really starts working.

### CODE REVIEW

**Comment by noisysocks** [comment]
> Still a work in progress: we'll need to update unit tests and fix the request batching implementation before the updated editor really starts working.

This should be easier now that https://github.com/WordPress/gutenberg/pull/28210 is merged.

**Comment by jsnajdr** [comment]
@adamziel I now rebased this PR onto the recently merged changes and it's now half the size 🙂 

Things that remain is the `__experimentalBatch` action, the `getKindEntities` helper and all the selector resolvers in `src/resolvers.js`.

**Comment by adamziel** [comment]
@jsnajdr Yay! I split the resolvers migration into a few PRs referenced above. Once merged, they should cover all the resolvers and their related tests.

**Comment by adamziel** [comment]
And this should take care of entities.js: https://github.com/WordPress/gutenberg/pull/34582

**Comment by jsnajdr** [comment]
@adamziel Now the last thing to migrate is the `__experimentalBatch` action :tada:

The rebased PR contains a series of additional cleanups: please have a look at the individual commits.

**Review by adamziel — APPROVED** [review]
LGTM 👍

**Comment by noisysocks** [comment]
This is great!

**Pull request merged**
