### PR TITLE
Unit tests workflow: Run always, but bail early if only docs have changed

### PR DESCRIPTION
**Pull request by ockham**
## Description
I've recently made the PHP and JS unit tests required -- meaning they _have_ to pass before a PR can be merged.
(This is in the wake of a recent issue that left PHP unit tests in a broken state -- also for subsequent PRs.)

@nosolosw then discovered that this affected documentation-only PRs (such as #28639): Since the unit test workflow had a [condition](https://github.com/WordPress/gutenberg/blob/d8d208927e964bf4f928a9e6b378902ed5fc421e/.github/workflows/unit-test.yml#L3-L10) that exempted it from running on such PRs, it never passed -- and the 'required' check criterion was never fulfilled.

This PR removes that condition from the workflow (so that the unit tests workflow always runs). Instead, it adds new steps to each unit test job that will cause them to bail early, if it the changed files are really only documentation files. (This could later be refined to e.g. only run the PHP unit tests if PHP files have been modified.)

This is based on [this answer](https://github.community/t/force-succeed-required-workflow-when-skipped/124055/3) (with a small modification to use `git diff` locally -- rather than the GH REST API -- in order to get the list of files that have been changed by the PR).

## How has this been tested?
Check the unit test GH workflows at the bottom of this PR. We'll also need a documentation-only PR to verify that it skips those -- TBD :thinking:

### CODE REVIEW

**Comment by nosolosw** [comment]
I see that tests are green in this PR, so I presume changes are fine. Not sure how to go about testing this, if others feel confident about shipping, I'll defer to them, as I'm not very knowledgeable about GitHub actions.

However, to offer some thoughts: would you think it'd be useful to create a few test PRs based on this one to test the following use cases:

- A PR that has only PHP changes and makes PHP test fail.
- A PR that has only JavaScript changes and makes JS test fail.
- A PR that has only doc changes.
- A PR that has all of them.

They don't need to make sense, only should make tests fail.

**Comment by ockham** [comment]
> I see that tests are green in this PR, so I presume changes are fine. Not sure how to go about testing this, if others feel confident about shipping, I'll defer to them, as I'm not very knowledgeable about GitHub actions.
> 
> However, to offer some thoughts: would you think it'd be useful to create a few test PRs based on this one to test the following use cases:
> 
> * A PR that has only PHP changes and makes PHP test fail.
> * A PR that has only JavaScript changes and makes JS test fail.
> * A PR that has only doc changes.
> * A PR that has all of them.
> 
> They don't need to make sense, only should make tests fail.

Thanks @nosolosw!

I'm unfortunately less optimistic about this PR :sweat_smile: Tests are indeed running and passing, but the mechanism to suppress them for doc changes isn't working yet.

The problem is that GitHub Actions don't support the concept of exiting early. (That feature has been requested e.g. at https://github.com/actions/runner/issues/662).

The workaround would be to add the exiting logic (or an `if` conditional) to _each individual step_. That will severely clutter the unit test workflow, and make it more fragile when extended in the future, since people might forget to add that logic. I'm not sure that suppressing the unit tests on doc changes is worth that kind of tradeoff.

So at this point, I'm thinking to file a separate PR to simply enable the unit tests workflow for all PRs (including doc changes). (Given the choice between saving some time by not running them on doc fixes, and making them mandatory for all PRs, I have a clear preference for the latter.)

**Comment by nosolosw** [comment]
> So at this point, I'm thinking to file a separate PR to simply enable the unit tests workflow for all PRs (including doc changes). (Given the choice between saving some time by not running them on doc fixes, and making them mandatory for all PRs, I have a clear preference for the latter.)

Ah, so the issue was that they were required **AND** skipped for PRs that had only changes to markdown files (hence they'll block the PR). Is that correct?

It sounds that making them required **and** that they run for all PRs is a fine tradeoff. I also prefer that people wait a bit than not letting them merge PRs unless they have admin permissions.

**Comment by ockham** [comment]
> Ah, so the issue was that they were required **AND** skipped for PRs that had only changes to markdown files (hence they'll block the PR). Is that correct?

Yeah, exactly. Apologies if that was lost in technical details :sweat_smile: 
 
> It sounds that making them required **and** that they run for all PRs is a fine tradeoff. I also prefer that people wait a bit than not letting them merge PRs unless they have admin permissions.

:+1:

**Comment by ockham** [comment]
BTW testing GitHub Actions can be fairly easy, and it's really a great tool, so here are some notes on that:

First, a very small glossary: A _workflow_ (e.g. Unit Tests) can consist of individual _jobs_ (e.g. PHP Unit Tests) which in turn consist of individual _steps_ (e.g. check out code, or run an `npm run build` job).

For this PR, you can simply click on the 'Details' links next to the "Unit Tests / PHP" and "Unit Tests / JavaScript" GitHub Actions workflows at the bottom of the page.

image

Here's e.g. the JavaScript unit test job (on Node 12):

image

In the left sidebar, you can navigate to other jobs in the same workflow, or even to other workflows. Note the new job that I added to the Unit Tests workflow in this PR ("Make a list of files that were changed"):

image

You can expand individual steps in the job, which allows some closer inspection of what's going on:

image

E.g. here I compared the download size from curl to when I run it locally (and successfully), and they matched (so the download is probably successul -- I can rule out a 404 etc).

Let's go back to the JS Unit test workflow now, and expand the step that I added in this workflow:

image

We're not finding any md files, so the subsequent steps are also executed, as they should.

Let's [compare](https://github.com/ockham/gutenberg/pull/3/checks?check_run_id=1818521385) this to a doc-files only [PR I filed against my personal fork](https://github.com/ockham/gutenberg/pull/3) (with the changes from this PR applied to `master`):

image

Hmm. Only `.md` files are found, but subsequent steps are still executed :slightly_frowning_face:

**Comment by ockham** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/pull/28696.

**Comment by nosolosw** [comment]
Thanks for the step-through :) The terminology is now clearer for me.

**Comment by youknowriad** [comment]
> The workaround would be to add the exiting logic (or an if conditional) to each individual step. That will severely clutter the unit test workflow

I think it's a good solution, I think a job can define some "output" variables that can be used in if statements. So the `diff-files-list:` job here would have a `is-only-docs` variable as output, and you could use it in the if statements.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs

**Comment by ockham** [comment]
> > The workaround would be to add the exiting logic (or an if conditional) to each individual step. That will severely clutter the unit test workflow
> 
> I think it's a good solution, I think a job can define some "output" variables that can be used in if statements. So the `diff-files-list:` job here would have a `is-only-docs` variable as output, and you could use it in the if statements.
> 
> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs

I'm just wary of the clutter it would add, TBH. We'd have to add that `if` to each step, IIUC. IMO, it's not worth it.

It might be worth revisiting if https://github.com/actions/runner/issues/662 gets addressed.

**Pull request closed without merging**
