### PR TITLE
Try to figure out which is the right LinkDestination value for an image

### PR DESCRIPTION
**Pull request by jesusangel**
I want to always link the images in my posts to its source url. This way, users can click on the thumbnail and see the image full size. In Gutenberg's image block, the default setting is not to link the images, so I have to manually change the LinkDestination select for each image I insert in the posts.

Users can change the default value of LinkDestination with a plugin and some JavaScript like this:

       function modifyImageLinkDestinationDefault( settings, name ) {

           // Override core default value for LinkDestination and change it to media 
           if ( name == "core/image" ) {
                // Set image block default destination.
                settings.attributes.linkDestination.default = "media";
            }

            return settings;
        }

        // Add settings filter to block registration.
        wp.hooks.addFilter(
            "blocks.registerBlockType",
            "my-plugin/modify-image-link-destination-default",
            modifyImageLinkDestinationDefault
        );
The actual code of the Gutenberg's image block doesn't work well when it finds old posts with no LinkDestination attribute, as no attribute means default value, but the new default value isn't the same as the old one.

Description
I've added code to the componentDidMount method of the image block to figure out which is the right value for the LinkDestination attribute based on the innerHTML. This work is based on @SeanDS pull request #13797 and closes issue #13749.

How has this been tested?
I used the latest development release of Gutenberg (cloned at 313974f), and WordPress 5.1, using docker images. I used the plugin showed above to change the default link target to media. I added several images with different LinkDestination values and I edited again after disabling the plugin.

This change doesn't affect other areas of the code.

Types of changes
Bug fix (non-breaking change which fixes an issue)

Checklist:
[ X] My code is tested.
[ X] My code follows the WordPress code style.
[ X] My code follows the accessibility standards.
[ X] My code has proper inline documentation.
[ X] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by jesusangel** [comment]
After rebasing my changes on the latest commits I did a mistake while resolving conflicts. I need more time to test again my changes.

**Comment by vdrover** [comment]
Any progress?

**Comment by jesusangel** [comment]
I'm sorry @vdrover, but I've been very busy. I'll try to fix the errors next week.

**Comment by bibiwan** [comment]
> I'm sorry @vdrover, but I've been very busy. I'll try to fix the errors next week.

Hi @jesusangel, when do you think you'll be able to fix the errors ? I'm very interested in this PR.

**Comment by SeanDS** [comment]
@jesusangel is the only thing stopping this from being reviewed the CI errors, or is there something else left over from the old PR that needs fixed in the code?

**Comment by thanh25896** [comment]
Why I always got "Parse error: syntax error, unexpected ',', expecting variable (T_VARIABLE)" when added your code to function.php?

**Comment by Soean** [comment]
> Why I always got "Parse error: syntax error, unexpected ',', expecting variable (T_VARIABLE)" when added your code to function.php?

It's not PHP code, you have to put it inside a JavaScript (.js) file.

**Comment by noisysocks** [comment]
Somewhat related to this is https://github.com/WordPress/gutenberg/issues/10173 which is that the image and gallery blocks should respect the `image_default_link_type` filter in WordPress.

**Comment by vigilantspb** [comment]
>     // Add settings filter to block registration.
>     wp.hooks.addFilter(
>         "blocks.registerBlockType",
>         "my-plugin/modify-image-link-destination-default",
>         modifyImageLinkDestinationDefault
>     );

excuse me, where do I have to put this code?

**Comment by ajlende** [comment]
This seems to be resolved by #25578.

The default setting can now be changed by editing the `image_default_link_type` setting in `options.php` to 'post' (for `LINK_DESTINATION_MEDIA`), 'file' (for `LINK_DESTINATION_ATTACHMENT`), or 'none' (for `LINK_DESTINATION_NONE`).

> There is an unfortunate mismtatch between what Gutenberg thinks the option should be and what the historic option values are. The classic editor and previous use `file` to represent Media File, and `post` to represent "Attachment Page". The Gutenberg constants used are `media` and `attachment`.

**Pull request closed without merging**
