### PR TITLE
Android: Reset extracted RN tools only if JS bundle is not up to date

### PR DESCRIPTION
**Pull request by oguzkocer**
## Description
In `android/react-native-bridge` project `resetExtractedRNTools` Gradle task is being run in cached builds even if the JS bundle is up to date. This in turn causes the `npmSetup` task to run again and the whole thing ends up costing 20+ seconds of build time for no gain.

This PR adds a `isBundleUpToDate` check to `resetExtractedRNTools` so that it's only run if the bundle will get rebuilt.

## How has this been tested?

This was tested in https://github.com/wordpress-mobile/WordPress-Android by running the initial build as well as the cached build. The initial build shouldn't be affected whereas the cached build should take 20+ seconds less. It was also tested by comparing the build scans for before and after the change.

## Screenshots 
N/A

## Types of changes

Build file changes in `android/react-native-bridge`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by mchowning — APPROVED** [review]
Tested this fix and it works well at speeding up the WPAndroid builds when it isn't rebuilding the JS bundle. Thanks so much @oguzkocer ! 🎉 

For me, it trimmed about 13 seconds off those builds, mostly by avoiding rerunning the `npmSetup` and `nodeSetup` tasks. This is what the builds look like before the change:

image

And after:

image

Interestingly, the `npmSetup` task still ran the first time I did a build _after_ the bundle was generated, but on any subsequent builds it wouldn't run unless it was recreating the bundle. I'm not sure why it's still running that first time, but it's a pretty minor issue since it only happens the first time.

Not a blocker at all for this PR, but since we are deleting both the npm and node folders in this `resetExtractedRNTools` task, it seems like it would be a good idea to make the `npmSetup` task also depend on this task, i.e. add `npmSetup.dependsOn(resetExtractedRNTools)` around [line 334](https://github.com/WordPress/gutenberg/blob/784c9a153d49419a2cffaed7d871f19fb7fa4d4e/packages/react-native-bridge/android/build.gradle#L334) where we set the task dependency for the `nodeSetup` task.

**Comment by mchowning** [comment]
> Interestingly, the npmSetup task still ran the first time I did a build after the bundle was generated, but on any subsequent builds it wouldn't run unless it was recreating the bundle. I'm not sure why it's still running that first time, but it's a pretty minor issue since it only happens the first time.

Thinking about this some more, I wouldn't be surprised if it is because we [delete the node_modules folder at the _end_ of a build that generates a JS bundle](https://github.com/WordPress/gutenberg/blob/784c9a153d49419a2cffaed7d871f19fb7fa4d4e/packages/react-native-bridge/android/build.gradle#L328) and the npm task uses those files as an input or output.

**Comment by oguzkocer** [comment]
Thanks for the review @mchowning! I can look into your notes when I work on the Gutenberg build next (should be in a couple days) and see if I can fix that as well. I don't think we should hold this PR for it. Let me know if there is anything I need to do to get this PR merged.

**Comment by mchowning** [comment]
> I don't think we should hold this PR for it. Let me know if there is anything I need to do to get this PR merged.

I agree, I was just waiting for CI to pass (it hung for 2 hours and I had to kick off a new build), but we're good now. 😄

**Pull request merged**
