### PR TITLE
Make the Site Logo block placeholder state smaller

### LINKED ISSUE #48217: Site Logo placeholder size is too large
We should make the Site Logo placeholder smaller. The current 120px by 120px placeholder size is quite large and takes up quite a bit of space. 

I propose we reduce it to 80px x 80px. 

Here it is at full size: 

CleanShot 2023-02-17 at 15 49 53

cc @WordPress/gutenberg-design

### PR DESCRIPTION
**Pull request by richtabor**
## What?
Closes #48217 by making the Site Logo block's placeholder state smaller — from 120px by 120px to 60px by 60px.

## Why?
The original intent for `120px` was to match the default image width that is applied when an image is used as the logo. But as a 1:1 ratio, 120px by 120px does not represent a common logo height, and it distorts the vertical spacing of header patterns (causing substantial vertical shift when an image is applied).

Maintaining a 1:1 is important as it helps to differentiate the site logo block from other image placeholders. 

The current method for getting around this is setting the width within the block's attributes, although then the applied image will only render at 60px wide. 

## How?
SCSS change. 

## Testing Instructions

1. Add a Site Logo block, without a site logo uploaded.
2. See a smaller placeholder.

## Screenshots or screencast 

Current: 

CleanShot 2023-02-17 at 16 23 25

Proposed: 

CleanShot 2023-02-17 at 16 22 53

### CODE REVIEW

**Review by carolinan — APPROVED** [review]

**Comment by t-hamano** [comment]
My sense is that the upload button that appears when this block is selected looks very cramped. How about at least 80px or 96px?

site-logo

**Comment by richtabor** [comment]
> My sense is that the upload button that appears when this block is selected looks very cramped. 

The whole 60px x 60px placeholder should probably be entirely the upload button when selected, instead of a hybrid. Though that should be a separate effort imo.

**Review by jameskoster — APPROVED** [review]
I [commented on the issue](https://github.com/WordPress/gutenberg/issues/48217#issuecomment-1443596888) that we might want a more flexible solution here in the long run, but the reduction in size generally seems fine.

**Review by apeatling — APPROVED** [review]
Looks good to me :+1:

**Review by t-hamano — APPROVED** [review]
> The whole 60px x 60px placeholder should probably be entirely the upload button when selected, instead of a hybrid. Though that should be a separate effort imo.

Understood, we can follow up on this point if necessary 👍 Performance test failures will be resolved by rebasing with the latest trunk.

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 28616a37cd

**Pull request merged**
