### PR TITLE
BaseControl: Add `box-sizing` resets

### PR DESCRIPTION
**Pull request by mirka**
Part of #42415 
Part of #41961

## What?

- Add a `box-sizing` reset to BaseControl. This immediately fixes the box-sizing problems we were seeing in the following components:
  - TextControl: Wrong width
  - TextareaControl: Wrong width
  - ToggleGroupControl: Wrong height
- Removes the ad hoc `box-sizing` declarations in components based on BaseControl.

## Why?

We can't guarantee that the surrounding context has a box-sizing reset in place.

## Testing Instructions

1. `npm run storybook:dev`
2. See that the problems with TextControl, TextareaControl, and ToggleGroupControl have been fixed.
3. Extra credit: In your IDE, search for `<BaseControl` to see where it's used in the repo, especially in packages other than wp-components. Take a look at the code (or test in wp-env!) to see if there could be problems.

✅ I have visually inspected all the BaseControl-based components compared with `trunk` to check for regressions

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for your great work!

✅ I have tried changing the global CSS switcher added in #42747 on Storybook, and I have confirmed the widths and heights are maintained correctly on each component.

✅ The issue reported in #41961 (`box-sizing` not applied to input elements in table block placeholders) has been fixed.

---

I think that the following `box-sizing` could also be removed in the BaseControl-based component.

I tried turning `box-sizing` on and off in the developer tools, but the layout was maintained correctly on the Storybook.

https://github.com/WordPress/gutenberg/blob/f46c873f0afa166c36e21eea54138ba3042b79de/packages/components/src/select-control/styles/select-control-styles.ts#L124
https://github.com/WordPress/gutenberg/blob/f46c873f0afa166c36e21eea54138ba3042b79de/packages/components/src/focal-point-picker/styles/focal-point-picker-style.js#L31

**Review by ciampo — APPROVED** [review]
Code changes LGTM 🚀 

Components tested:

- [x] `CheckboxControl`
- [x] `ComboboxControl`
- [x] `FocalPointPicker`
- [x] `RadioControl`
- [x] `RangeControl`
- [x] `SearchControl`
- [x] `SelectControl`
- [x] `TextControl` (fixes width bug)
- [x] `TextareaControl` (fixes width bug)
- [x] `ToggleControl` 
- [x] `ToggleGroupControl` (fixes height bug)
- [x] `ToolsPanel`

**Comment by mirka** [comment]
> I think that the following `box-sizing` could also be removed

Ah sorry, I totally forgot to mention these! 🤦 I left these two intentionally, because they apply to specific tag types (select, img, video) instead of div/span. It is possible that wp-components are used in a CSS environment where there are broadly scoped CSS files similar to `forms.css`. Those files probably won't have weird global styles on div/spans, but it's not unlikely that they have weird style resets on select/img/video. So I thought it wouldn't hurt to keep the box-sizing rules for those as a courtesy defense, since they're already there 😄

**Comment by t-hamano** [comment]
> Ah sorry, I totally forgot to mention these! 🤦 I left these two intentionally, because they apply to specific tag types (select, img, video) instead of div/span. It is possible that wp-components are used in a CSS environment where there are broadly scoped CSS files similar to forms.css. Those files probably won't have weird global styles on div/spans, but it's not unlikely that they have weird style resets on select/img/video. So I thought it wouldn't hurt to keep the box-sizing rules for those as a courtesy defense, since they're already there 😄

Thank you for the detailed explanation.
I think that makes a lot of sense 😄

**Review by t-hamano — APPROVED** [review]

**Pull request merged**
