### PR TITLE
Update: Show more intuitive archive titles on Query Title block.

### LINKED ISSUE #42675: Query Loop: show correct posts after setting "Inherit query from template"
### Description

After creating one of the new templates (categories, tags, date, author, etc), adding a Query Loop block, and setting it to "Inherit query from template", it's not clear that the query loop will correctly show posts based on the template. Instead, nothing changes in the editor (same posts are shown), despite the query loop working correctly on the front end. I understand this might be intentional for a template like Author or Date since that'll depend on which author is being viewed but for templates around categories or tags this proves to be confusing. 

This was found as part of the [fifteenth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2022/07/11/fse-program-testing-call-15-category-customization/).

### Step-by-step reproduction instructions

1. Go to Appearance > Editor > Templates > Add New
2. Create a new category template for a specific category of posts. 
3. Add a query loop block.
4. Toggle on "Inherit query from template" in the block sidebar settings.
5. Notice no change to what posts are displayed in the editor but notice that if you view the category page the template shows correctly. 

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WP 6.0.1
- GB 13.7.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Part of: https://github.com/WordPress/gutenberg/issues/42675 and https://github.com/WordPress/gutenberg/issues/44158.
Follows a suggestion by @jameskoster:
> Similarly it would be nice if the Archive Title block displayed a more contextual placeholder. E.g. in the category template it might display 'Category name'. In category-recipes it would display 'Category: Recipes', etc. This would be a lot more intuitive than the current generic 'Archive Title'.

Now instead of just showing generic titles, we show a more intuitive title.

## Screenshots
Screenshot 2023-07-11 at 17 49 32

## Testing
- I created a template for all tags, for all categories, for all terms of a custom taxonomy.
- I created a template for a specific tag, for a specific category, and for a specific term of a custom taxonomy.
- I opened all templates referred and verified the titles make sense and reference the type of archive. I toggled off "Show archive type in title" in the title of all archive templates and verified the titles still make sense.

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta this is so much better. It's working well for tags, categories, and custom taxonomies. 

Do you think it would be feasible to include author and date archive templates as a part of this work, or is that something to handle separately?

**Comment by jorgefilipecosta** [comment]
> Thanks @jorgefilipecosta this is so much better. It's working well for tags, categories, and custom taxonomies.
> 
> Do you think it would be feasible to include author and date archive templates as a part of this work, or is that something to handle separately?

Hi @jameskoster, thank you for your testing! I think including the other archive types will make this PR bigger but I can follow up with the other changes right after this one is merged.

**Review by jameskoster — APPROVED** [review]

**Comment by carolinan** [comment]
I believe this is the correct issue? https://github.com/WordPress/gutenberg/issues/44158

**Comment by jorgefilipecosta** [comment]
> is the correct issue? #44158

Yes @carolinan, that's the correct issue, thank you for linking it.

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster, the follow-up for authors is available at https://github.com/WordPress/gutenberg/pull/52732.
Regarding the follow-up for dates.
Dates can have the following titles "Day: July 11, 2023", "Month: July 2023", "Year: 2023". The same template is used for Day, month, and year. I think we still can find a better title than "Archive type: Name" but I don't have many ideas. Maybe  "Archive type: Date" or "Type of date archive: Date"? Any other options are welcome!

**Pull request merged**
