### PR TITLE
Bugfix: ServerSideRender should serialize arrays, similarly to objects

### LINKED ISSUE #7086: Server side render encodes some attributes incorrectly
I'm running into a situation where my attributes are being returned in an unexpected format.  For example, an array of Post IDs is converted to an array that contains one comma separated string.

Expected:
```php
$postIds = [
   1,2,3
];
```

Observed:
```php
$postIds = [
   '1,2,3'
];
```

Another example is an array of objects is converted to `[object Object],[object Object]`.  Both cases are problematic because the data are inconsistent between the post editor and front end.  Having to account for both formats increases the chances of buggy code.

I have narrowed the problem down to `getQueryUrlFromObject`, though I can't offer a solution. https://github.com/WordPress/gutenberg/blob/7066905fe907bb8b160d1373a5c5ec3220b5eec0/components/server-side-render/index.js#L68-L74

**Additional context**
- Gutenberg v2.9.2

### PR DESCRIPTION
**Pull request by dimofte**
## Description

Fixes #7086 
The SSR component doesn't properly encode attributes like arrays of objects.

## How has this been tested?
Manually in Chrome on MacOS.
The component doesn't have automated tests and I haven't implemented any.

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Would `_.isObjectLike` work here, in place of `_.isPlainObject`?

https://lodash.com/docs/4.17.10#isObjectLike

Aside: Also mentioned on the pull request where this component was introduced, but it really ought not be the responsibility of the component to do basic behaviors like encoding URL parameters. Instead, we should leverage existing modules, or at the very least extract to a common, generalized/shared/well-tested approach. Currently it's needlessly ad-hoc, which is why it doesn't surprise me there are small issues like this cropping up.

**Comment by chrisvanpatten** [comment]
@aduth Thanks for taking a look!

While we were researching this one (this and #7229 are from us at @tomodomoco) I came across a few JS equivalents of `http_build_query`, which can transform the various data structures into a query string that PHP (and thus the REST API) can read.

These two are both MIT and thus would be compatible w/ Gutenberg:

+ https://github.com/vladzadvorny/http-build-query
+ http://locutus.io/php/url/http_build_query/

Of course Core could also provide this as a module.

Would that be a reasonable approach? That is effectively what `getQueryUrlFromObject` function is doing; just shifts away the responsibility.

**Comment by dimofte** [comment]
`_.isObjectLike` would be more concise and would satisfy the current conditions, but it would also be true for more complex objects (and then `_.map` does apply to object methods, usually with undesired results). My knowledge of this system is limited, so I opted for the fix with the smallest possible splash

**Comment by chrisvanpatten** [comment]
@aduth would it be possible to get a review on this, and then look at reworking it later on? We're happy to own the ticket and create a better solution over the longer term (I think there are some other systemic issues here too that could be solved simultaneously), but right now we have to run off a Gutenberg fork in production to get our SSR blocks rendering, which isn't ideal 😬

**Comment by jasmussen** [comment]
@gziolo @jorgefilipecosta @youknowriad does this issue have an easy resolution? Is this something we could get in 3.1?

**Comment by chrisvanpatten** [comment]
Thanks for the comment @jasmussen.

Just as a bit of background, I agree that either separating the code that builds the query string, or adding a dependency for an existing package that reimplements PHP's `http_build_query` for JS would be ideal. However, I think something like that will obviously take more time, dev discussion, etc.

Adding another check for arrays will solve the problem today, giving us time to think through a more properly-architected solution.

As @dimofte noted: `_.isObjectLike` could work as well, but it will could mean objects with methods pass the check and break serialisation in unexpected ways. Adding _only_ the array check contains the fix to a really small surface area, which feels safer for now.

**Comment by danielbachhuber** [comment]
As noted in https://github.com/WordPress/gutenberg/pull/7229#issuecomment-397597223, we should exclude `attributes` from the request when it is empty.

**Comment by danielbachhuber** [comment]
Also, in looking at this further, I think we should use `vladzadvorny/http-build-query`, either by pulling it in as a dependency or copying its implementation into our codebase with attribution.

I don't think it makes sense for us to re-implement the wheel with `getQueryUrlFromObject()`

**Comment by chrisvanpatten** [comment]
@danielbachhuber agree completely. Would it be possible to merge this in as a temporary fix, and then we'll open a new PR with the `http_build_query` implementation?

**Comment by danielbachhuber** [comment]
> Would it be possible to merge this in as a temporary fix, and then we'll open a new PR with the `http_build_query` implementation?

I'd prefer to get it correct in this pull request, particularly because we don't have any test coverage of `getQueryUrlFromObject()` at this time.

**Comment by chrisvanpatten** [comment]
@danielbachhuber I've replaced this PR with #7339! I've also asked @dimofte to pop in and add a test in that branch, if you think one would be appropriate for the `getQueryStringFromAttributes` method. Thanks! 🎉

**Comment by dimofte** [comment]
I've removed the method `getQueryStringFromAttributes` (for reasons stated in a comment), but I've added the relevant tests to the package itself

**Comment by dimofte** [comment]
closing this PR in favour of #7339

**Pull request closed without merging**
