### PR TITLE
Update token field icon

### PR DESCRIPTION
**Pull request by jameskoster**
Tokens in the [FormTokenField](https://wordpress.github.io/gutenberg/?path=/story/components-formtokenfield--default) component consume an icon (`closeCircleFilled`) that has not been updated to align with the new design language applied to icons in the [WordPress Icons Library](https://github.com/WordPress/gutenberg/tree/master/packages/icons). This icon is one of three `X` icons in Gutenberg. Rather than update `closeCircleFilled` – which as far as I know is _only_ used in these form tokens, this PR replaces `closeCircleFilled` with `closeSmall`, in `FormTokenField`. Fewer icons = more predictable UI.

I also tidied up the padding a little.

Before:

Screenshot 2020-11-05 at 11 57 17

After:

Screenshot 2020-11-05 at 12 19 16

### CODE REVIEW

**Comment by jasmussen** [comment]
This is a nice small win, thank you! Before:

Screenshot 2020-11-05 at 14 14 28

before

After:

Screenshot 2020-11-05 at 14 15 38

after

Nitpick, I noticed that the gray color of the icon doesn't have enough contrast. The easiest fix is to make it $gray-900, like the text. That looks like this:

Screenshot 2020-11-05 at 14 16 58

Or you could tweak the entire chip to not be gray, like this:

Screenshot 2020-11-05 at 14 18 55

Both seem good, but just making the close icon the dark color seems like the smaller change.

**Comment by mapk** [comment]
Thanks for this! I had been working on some redesigns for these tags while digging into the Query block so I thought I'd share them here.

Screen Shot 2020-11-05 at 6 04 38 AM

**Comment by rickybanister** [comment]
I like the shape of those @mapk, but I wonder if the black doesn't feel more like the selected state of menu items elsewhere in the editor? Perhaps a combination of @jasmussen gray outline as a round rect with the black as the selected state as you tab through would make sense? 

I personally would prefer that tags recede into the background most of the time while I focus on editing my content, so the black might stand out a bit too much.

**Comment by jameskoster** [comment]
+1 on the shape, I suspect we can all agree there. I updated the border radius and fixed the contrast issue you noticed @jasmussen.

Screenshot 2020-11-05 at 14 48 51

Further visual treatment can be explored in another PR I think.

**Comment by mapk** [comment]
Looks good, @jameskoster! 👍

**Review by mapk — APPROVED** [review]
LGTM.

**Comment by jasmussen** [comment]
> +1 on the shape, I suspect we can all agree there.

Well 😅  — I had a small preference for the pill shape, because that's how most chips are shaped. 

However I'm happy to try this, as it's trivial to change back, and it does move it to use an existing radius rather than a rarely used pill shape.

**Pull request merged**
