### PR TITLE
Custom Link: Decode value in URL input field

### LINKED ISSUE #55537: Navigation Custom Link Block: Setting's URL input area don't allow to delete texts include `%`
### Description

In the Site Editor, if you add a string containing % to the URL in the setting of a Custom Link Block in the Navigation Block and then try to delete it, you cannot delete it.

### Step-by-step reproduction instructions

1. Block Theme "Twenty Twenty-four" is activated
2. Go Site Editor
3. Move to Navigation
4. Add Custom Link Block
5. Show the config menu
6. Input a string like "20%" including `%` in URL input area
7. Push Delete key

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/487207/c5540719-bb98-4c5c-a164-6cd20da4b3b8

### Environment info

It reproduces whether Gutenberg is enabled or not.

- WordPress: 6.4 RC1 
- Browser: Chrome 117.0.5938.149
- OS: Mac OS 12.5.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by t-hamano**
Fixes #55537
Related to #46435

## What?

This PR fixes an issue where the URL cannot be changed correctly from the navigation sidebar in the Custom Link block.

| Before| After |
|--------|--------|
| before | after | 

## Why?

The URL in this block is sanitized by `esc_url()` when rendered. As a result, the correct URL may not be rendered, for example if it contains parameters as shown below.

```php
echo esc_url( 'https://google.com?param=<%>' );

// > https://google.com?param=%
````

My understanding is that to prevent this, it was changed in #19679 to keep the encoded URL as an attribute value. [This comment](https://github.com/WordPress/gutenberg/pull/46435/files#r1062236863) explains more about why. And then #46435 was filed to properly decode the encoded URL on the front end.

On the other hand, although the URL can be changed from the block sidebar, the encoded URL was displayed as the value of the text field. The encoded URL may represent one character with multiple characters. Deleting one of those characters by keyboard will corrupt the encoded string, and the block will internally attempt to repair the URL, causing problems like the one reported in #55537 to appear.

User-editable fields should display the decoded URL instead of the encoded URL.

## How?

In the URL input field, the encoded URL was decoded using the `safeDecodeURI()` function.

## Testing Instructions

- Click the inserter in the navigation block. Enter `https://google.com?param=<%>` in the text field.
- A Custom Link block should now be created.
- Open the block sidebar.
  - trunk: The URL field should display the encoded URL (`https://google.com?param=%3C%25%3E`).
  - This PR: The URL field should display the decoded URL (`https://google.com?param=<%>`).
- Try editing the URL value, perhaps using the delete key.
  - trunk: You may not be able to delete characters, or unintended encoded characters may be added.
  - This PR: You should be able to change all characters normally.
-  Check the link for this block in the front end.
- The URL should show the correct `https://google.com?param=<%>` without being stripped.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/54422211/ab1bf253-052c-478c-9e42-77d4154d6a04

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
Nice catch.

I test this and it worked.

One thing I noticed though was that if I set the link `Label` to `google.com?param=<%>` then it is filter out on the front of the site.
Screen Shot 2023-11-09 at 12 01 41

Screen Shot 2023-11-09 at 12 01 22

**Comment by t-hamano** [comment]
Thanks for the testing, @getdave!

> One thing I noticed though was that if I set the link `Label` to `google.com?param=<%>` then it is filter out on the front of the site.

I think this is because the label is [filtered by the `wp_kses_post()` function](https://github.com/WordPress/gutenberg/blob/8269b812bdb750261ab723163b97019f3dce46e5/packages/block-library/src/navigation-link/index.php#L228). The `wp_kses_post()` function removes HTML tags that are not allowed in the content. Therefore, the string `<%>` will be considered a tag and will be removed. If you delete the last character and write `google.com?param=<%`, it will be displayed as is.

However, this problem also occurs on trunk. Maybe `esc_html()` is more appropriate?

**Comment by getdave** [comment]
> Thanks for the testing, @getdave!
> 
> > One thing I noticed though was that if I set the link `Label` to `google.com?param=<%>` then it is filter out on the front of the site.
> 
> I think this is because the label is [filtered by the `wp_kses_post()` function](https://github.com/WordPress/gutenberg/blob/8269b812bdb750261ab723163b97019f3dce46e5/packages/block-library/src/navigation-link/index.php#L228). The `wp_kses_post()` function removes HTML tags that are not allowed in the content. Therefore, the string `<%>` will be considered a tag and will be removed. If you delete the last character and write `google.com?param=<%`, it will be displayed as is.
> 
> However, this problem also occurs on trunk. Maybe `esc_html()` is more appropriate?

I suppose the label doesn't have to be 1:1 with the URL especially where that it potentially inappropriate. I think we're good to merge as is.

**Review by getdave — APPROVED** [review]
Concerns resolved. Let's bring this in 👍

**Pull request merged**
