### PR TITLE
FSE: Strip post ids from template part blocks on export.

### PR DESCRIPTION
**Pull request by fklein-lu**
This ensures that exported FSE themes work on other sites.

## Description
Fixes the export of FSE themes so that they can be activated on other sites

## How has this been tested?

Tested:
1. Automated via a WP unit test.
2. Manually by exporting a template with a template part on local, and verifying the output.

## Types of changes

Bug fix: Fixes the issue outlined in #25845.  

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by skorasaurus** [comment]
Thanks for the PR. 

I've tested it manually and functions as expected on my end; the postids are no longer included in the template-part. 

(Made edits to the footer and header both through https://site.test/wp-admin/admin.php?page=gutenberg-edit-site and through  https://site.test/wp-admin/edit.php?post_type=wp_template_part ; then exported the zip.

**Comment by youknowriad** [comment]
I'd love some thoughts about how to make this more generic across blocks. the same issue can happen for reusable blocks for instance and even more complex for image blocks (and other media blocks) where the id is in the markup.

**Comment by youknowriad** [comment]
Thinking more, I guess you could argue that the template parts are a bit special in the sense that they are actually already exported as files to the themes. So yeah, this might have more priority.

I didn't test but I'm on board with this

**Review by youknowriad — APPROVED** [review]
Let's get this in. Seems like a decent fix for now.

**Pull request merged**
