### PR TITLE
[RNMobile] Compile and target Android API 30

### PR DESCRIPTION
**Pull request by hypest**
## Description
Upgrade the targetSdkVersion of the RN build on Android to API 30, to meet [the Google Play Store requirements](https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637402646062706504-1797308153&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console).

### Related PRs
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/4049
* https://github.com/wordpress-mobile/WordPress-Android/pull/15387
* https://github.com/wordpress-mobile/WordPress-Android/pull/15331

## How has this been tested?
By using [the WPAndroid installable build](https://github.com/wordpress-mobile/WordPress-Android/pull/15387#issuecomment-930082745)

## Types of changes
[Android only change] Bumped the `targetSdkVersion` and `compileSdkVersion` to 30.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by antonis** [comment]
Thank you for tackling this issue @hypest 🙇 
I hope that I will be able to get to this by the end of the day or 1st thing tomorrow.

**Review by antonis — APPROVED** [review]
Great work @hypest 👋 
I smoke tested the changes both on Metro and with the release build and did not notice any inconsistencies (except the [upload media from the device issue](https://github.com/wordpress-mobile/WordPress-Android/issues/15333)). I also went through the [SDK changes](https://developer.android.com/about/versions/11/migration) and I don't see something else that needs tweaking on our side.
I would suggest to avoid merging (probably add a do not merge tag/warning) these changes to `trunk` before the [main upgrade PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15331)  is ready for merge and have another quick smoke testing (I'll be happy to do that) when this is done. Wdyt?

**Comment by hypest** [comment]
Thanks for the review @antonis !

> I would suggest to avoid merging (probably add a do not merge tag/warning) these changes to trunk before the main upgrade PR is ready for merge and have another quick smoke testing (I'll be happy to do that) when this is done. Wdyt?

Makes sense to sync the API upgrade and not have the Gutenberg side be on API 30 before all sides are "green" 👍 I'll actually go ahead and turn this into a draft PR just to be sure.

**Comment by hypest** [comment]
@ravishanker pinged me on Slack that we're ready for the merge domino so, will go ahead and merge the Gutenberg and gutenberg-mobile PRs.

**Pull request merged**
