### PR TITLE
Update the Gutenberg plugin to require at least the WP 6.1 version

### LINKED ISSUE #45870: Plugin: viewScript does not work with multiple handles/files
### Description

During block type registration from metadata ( `register_block_type_from_metadata` function ) there is a great possibility to edit block metadata as it passes threw `$metadata = apply_filters( 'block_type_metadata', $metadata );` filter. However there is a callback hooked in `block_type_metadata` filter in gutenberg plugin which registers all scripts ( handles or files ) but actually returns only the first handle name as the value of `viewScript` key in metadata array.

### Step-by-step reproduction instructions

1. Add more than one handles as a value of `viewScript` key in any block.json file:

`{
...
"viewScript": ["file:./slider.min.js", "file:./view.min.js"],
}`

the result should be 
`[
...
'viewScript' => ['slider-handle-name', 'view-handle-name']
]`

the actual result is
`[
...
'viewScript' => 'slider-handle-name'
]`

View script never contains an array of handle name, even if block.json does.

### Screenshots, screen recording, code snippet

image

The above screenshot shows how is it implemented in current `14.5.3` version.

### Environment info

- WP v6.1.1
- Google Chrome Version 107.0.5304.107 (Official Build) (64-bit)
- Desktop with Windows 11

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?

WordPress 6.2 was released a month ago. It's time to bump the minimum required version for the Gutenberg plugin and remove the compat layer.

It also fixes #45870.

## How?
* I removed all the files from the `compat/wordpress-6.1` directory.
* Fixed all the PHP notices and fatal errors.
* Updated client-asset.php to handle preferences API ([7337428](https://github.com/WordPress/gutenberg/pull/50079/commits/73374289c743626f1948139a68b7e4d9cc28294e)). Props to @talldan for leaving detailed instructions 🦸

## Testing Instruction

* Run the Gutenberg plugin with WP 6.1, and confirm editors work as before.
* Run the Gutenberg plugin with WP 6.2, and confirm editors work as before.

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for starting this PR, nice to see. There might be a few more cleanup tasks to do:

 - [x] Update the layout block support https://github.com/WordPress/gutenberg/blob/df354180d5de003204fb5b20af75facadc1b6879/lib/block-supports/layout.php#L86
 - [x] Remove typography deprecated function https://github.com/WordPress/gutenberg/blob/df354180d5de003204fb5b20af75facadc1b6879/lib/block-supports/typography.php#L214-L250
 - [ ] Some routing back compat code to remove https://github.com/WordPress/gutenberg/blob/df354180d5de003204fb5b20af75facadc1b6879/lib/compat/plugin/edit-site-routes-backwards-compat.php#L1
 - [x] Some cleanup in the style engine https://github.com/WordPress/gutenberg/blob/df354180d5de003204fb5b20af75facadc1b6879/packages/style-engine/class-wp-style-engine-css-declarations.php#L20-L31 (cc @ramonjd )

These are the things I found, there might be other stuff that I missed.

**Comment by Mamaduka** [comment]
@fullofcaffeine, can we remove site editor route backward compatibility - `lib/compat/plugin/edit-site-routes-backwards-compat.php`? Introduced here, #42643.

**Comment by ramonjd** [comment]
> Some cleanup in the style engine

Thanks for the ping. I've done a quick smoke test, removing the 6.1 compat code in `gutenberg/packages/style-engine/class-wp-style-engine-css-declarations.php`. Editor and unit tests are good to go.

Below is the diff. I'm happy to throw up a separate PR if it's not included in this one:


<details>

<summary>diff</summary>

```diff
diff --git a/packages/style-engine/class-wp-style-engine-css-declarations.php b/packages/style-engine/class-wp-style-engine-css-declarations.php
index 6e7fdfc58e..a91bcab520 100644
--- a/packages/style-engine/class-wp-style-engine-css-declarations.php
+++ b/packages/style-engine/class-wp-style-engine-css-declarations.php
@@ -17,22 +17,6 @@ if ( class_exists( 'WP_Style_Engine_CSS_Declarations' ) ) {
  * @access private
  */
 class WP_Style_Engine_CSS_Declarations {
-	/**
-	 * An array of valid CSS custom properties.
-	 * CSS custom properties are permitted by safecss_filter_attr()
-	 * since WordPress 6.1. See: https://core.trac.wordpress.org/ticket/56353.
-	 *
-	 * This whitelist exists so that the Gutenberg plugin maintains
-	 * backwards compatibility with versions of WordPress < 6.1.
-	 *
-	 * It does not need to be backported to future versions of WordPress.
-	 *
-	 * @var array
-	 */
-	protected static $valid_custom_declarations = array(
-		'--wp--style--unstable-gallery-gap' => 'gap',
-	);
-
 	/**
 	 * An array of CSS declarations (property => value pairs).
 	 *
@@ -140,23 +124,6 @@ class WP_Style_Engine_CSS_Declarations {
 	 */
 	protected static function filter_declaration( $property, $value, $spacer = '' ) {
 		$filtered_value = wp_strip_all_tags( $value, true );
-
-		/**
-		 * Allows a specific list of CSS custom properties starting with `--wp--`.
-		 *
-		 * CSS custom properties are permitted by safecss_filter_attr()
-		 * since WordPress 6.1. See: https://core.trac.wordpress.org/ticket/56353.
-		 *
-		 * This condition exists so that the Gutenberg plugin maintains
-		 * backwards compatibility with versions of WordPress < 6.1.
-		 *
-		 * It does not need to be backported to future versions of WordPress.
-		 */
-		if ( '' !== $filtered_value && isset( static::$valid_custom_declarations[ $property ] ) ) {
-			return safecss_filter_attr( static::$valid_custom_declarations[ $property ] . ":{$spacer}{$value}" ) ?
-				"{$property}:{$spacer}{$value}" : '';
-		}
-
 		if ( '' !== $filtered_value ) {
 			return safecss_filter_attr( "{$property}:{$spacer}{$filtered_value}" );
 		}

```

</details>

**Comment by Mamaduka** [comment]
Thank you, @ramonjd! I'll include Style Engine cleanup here 👍

**Comment by Mamaduka** [comment]
I removed the remaining compat code beside `edit-site-routes-backward-compat.php`. I'm going to wait for @fullofcaffeine feedback on this one first.

**Review by ntsekouras — APPROVED** [review]
Thanks for handling this George! In my testing everything looked good. We can probably remove some PHP tests too, but we can do it later too.

**Comment by Mamaduka** [comment]
Thanks for testing, Nik!

I'm thinking of merging this, and then I can do a follow-up for the `edit-site-routes-backward-compat.php` and PHP test files.

**Comment by noahtallen** [comment]
Just a heads up -- the "End-to-End Tests / Puppeteer - 3 (push)" seems to be permafailing since this was merged 🤔 

image

**Comment by Mamaduka** [comment]
@noahtallen, failure is caused by the core change. See https://github.com/WordPress/gutenberg/pull/50185

**Comment by tellthemachines** [comment]
Hi! This PR has caused a regression in layout styles, due to the core `class_wp_theme_json` being used instead of `lib/class-wp-theme-json-gutenberg.php`. Adding back the `gutenberg_enqueue_global_styles` function from the 6.1 script loader seems to fix it.

**Comment by ramonjd** [comment]
> This PR has caused a regression in layout styles, due to the core class_wp_theme_json being used instead of lib/class-wp-theme-json-gutenberg.php. Adding back the gutenberg_enqueue_global_styles function from the 6.1 script loader seems to fix it.

Is it specific to the grid layout? As far as I can see [it hasn't yet been shipped to core](https://github.com/ramonjd/wordpress-develop/blob/trunk/src/wp-includes/theme.json#L297) (at the time of writing).  Added comment over [here](https://github.com/WordPress/gutenberg/pull/49050#issuecomment-1534082598).

**Comment by tellthemachines** [comment]
> Is it specific to the grid layout?

No, all the work from #47858 has regressed too. 


Edit: we seem to have this problem every time we remove support for an older WP version; perhaps the code to run the Gutenberg versions of these classes when the plugin is enabled shouldn't live inside the `compat/wordpress-x.x` folders.

**Comment by Mamaduka** [comment]
Thank you, @tellthemachines.

> we seem to have this problem every time we remove support for an older WP version; perhaps the code to run the Gutenberg versions of these classes when the plugin is enabled shouldn't live inside the `compat/wordpress-x.x` folders.

That is very true 😞  I will start looking into how we can fix this in a more future-proof way.

What would be the best way to test that the new method works correctly for layouts? Just make sure changes from #47858 are correctly applied.


Side note: It would be great to add regression tests for layout(s). I belive we briefly talked about this during WordCamp Asia.

**Comment by Mamaduka** [comment]
I started working on the fix in #50310. I would appreciate the testing instructions for the regression.

**Comment by tellthemachines** [comment]
The easiest way to test this is with the following markup:
```
<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p>First child of group</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Second child of group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

The first paragraph inside the group should have the following CSS rule:
```
.editor-styles-wrapper :where(body .is-layout-constrained) > :first-child:first-child {
    margin-block-start: 0;
}
```
And both paragraphs should have:
```
.editor-styles-wrapper :where(body .is-layout-constrained) > * {
    margin-block-start: 1.5rem;
    margin-block-end: 0;
}
```

Whereas in the current state of trunk, both paragraphs have:
```
.editor-styles-wrapper .is-layout-constrained > * {
    margin-block-start: 0;
    margin-block-end: 0;
}
```
And the second paragraph has:
```
.editor-styles-wrapper .is-layout-constrained > * + * {
    margin-block-start: 1.5rem;
    margin-block-end: 0;
}
```

**Comment by tellthemachines** [comment]
> Side note: It would be great to add regression tests for layout(s). I belive we briefly talked about this during WordCamp Asia

Yes that is very true! We definitely need to add tests before stabilising the layout support. Which I hope will happen soon 😅

**Comment by talldan** [comment]
Just a note that this also seems to have caused an issue with the mobile navigation menu toggle - #50211. I did a bisect to check where it was introduced and it seems to be this PR.

#50310 doesn't seem to resolve the issue.

**Comment by Mamaduka** [comment]
Thanks for the note, @talldan.

I think the [block view script handlers](https://github.com/WordPress/gutenberg/blob/e6450b236e3152c6c54d3c04485a7ac46ca78396/lib/compat/wordpress-6.1/blocks.php#L61-L140) were not ported in WP 6.1, and the code was in the wrong compat layer.

@gziolo, @aristath, can you confirm which WP version includes `viewScript` handling so I can update the file in the correct compat directory?

**Comment by talldan** [comment]
It looks like there's also this code here related to view scripts:
https://github.com/WordPress/gutenberg/blob/e6450b236e3152c6c54d3c04485a7ac46ca78396/lib/experimental/blocks.php#L8-L79

If I delete that it works again. 🤷

**Comment by gziolo** [comment]
> can you confirm which WP version includes viewScript handling so I can update the file in the correct compat directory?

`viewScript` and the ability to pass an array of scripts were added to WordPress core in 6.1. 

> It looks like there's also this code here related to view scripts:
> If I delete that it works again. 🤷

That would be very surprising that it impacts the Navigation block. I'll investigate today.

**Comment by Mamaduka** [comment]
@talldan, if I add [both these filters](https://github.com/WordPress/gutenberg/blob/e6450b236e3152c6c54d3c04485a7ac46ca78396/lib/compat/wordpress-6.1/blocks.php#L61-L140), then the `viewScript` works again. Adding just one of them causes a fatal error.

**Comment by gziolo** [comment]
> @talldan, if I add [both these filters](https://github.com/WordPress/gutenberg/blob/e6450b236e3152c6c54d3c04485a7ac46ca78396/lib/compat/wordpress-6.1/blocks.php#L61-L140), then the `viewScript` works again. Adding just one of them causes a fatal error.

We probably need to deregister scripts registered in WP core, similar to this line:

https://github.com/WordPress/gutenberg/blob/e6450b236e3152c6c54d3c04485a7ac46ca78396/lib/compat/wordpress-6.1/blocks.php#L86

We have a similar logic for individual block styles in:

https://github.com/WordPress/gutenberg/blob/d54dc62685dd1b9980c4a06d3f488b87b6c7fe10/lib/blocks.php#L188

**Comment by talldan** [comment]
Out of interest, what's the issue with removing the code in the `experimental/blocks.php` file? What does it do that's different to core?

**Comment by gziolo** [comment]
> Out of interest, what's the issue with removing the code in the `experimental/blocks.php` file? What does it do that's different to core?

See https://github.com/WordPress/gutenberg/pull/50364. It's all about preventing registering a script using the same handle twice. When it happens, `_doing_it_wrong` gets called, and that apparently breaks something.

**Comment by aaronrobertshaw** [comment]
I found this PR via a git bisect while investigating https://github.com/WordPress/gutenberg/issues/50416. That issue appears to be due to the same problem @tellthemachines [flagged](https://github.com/WordPress/gutenberg/pull/50079#issuecomment-1533905463).

A quick test of https://github.com/WordPress/gutenberg/pull/50310 shows it fixes the issue in https://github.com/WordPress/gutenberg/issues/50416 as well.

**Comment by fullofcaffeine** [comment]
@Mamaduka Sorry for missing this one! :/ -- next time if I don't reply in a timely manner, feel free to ping me via Slack in the WP core channel (my handle is the same there).

**Pull request merged**
