### PR TITLE
Initial plugin readme.md based on template from dd32

### PR DESCRIPTION
**Pull request by j-falk**
Initiated a readme.md file with syntax that will work both on github and on wordpress.org when this plugin gets pushed to the .org repo.

Based on dd32's template from https://github.com/dd32/feature-plugin-testing/blob/master/README.md.

I thought I would get this pullrequest setup and continue working on the actual content in the coming days.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, thank you! Is there any overlap with #278?

**Comment by j-falk** [comment]
I think #278 is only about inline documentation in index.php. But you are right that there is a plugin header in index.php which I should move over to the readme.md as part of this pull request.

Will make sure to do that in the next commit.

**Comment by jasmussen** [comment]
Sorry that this PR sort of fell off the map in the crazy whirlwind of development that's happened in the last week. Is it worth rebasing, fixing? How should we merge it? Is it something we should revisit down the road instead or can we make a new PR with the most important changes only, which seem to be the stuff near the top (contributors, versions, etc.)?

**Comment by jasmussen** [comment]
Closing for now. We can reopen when it becomes pressing.

**Comment by j-falk** [comment]
Sorry, totally got swamped at work so haven't been able to do anything around this (or other things too). But I will try to follow along and become more active later if I have the chanse and there is anything that I can contribute with. Thanks for your effort!

**Comment by jasmussen** [comment]
Oh totally understandable, and appreciate the contributions! :)

**Pull request closed without merging**
