### PR TITLE
Testing: Remove unnecessary Enzyme React 16 workarounds

### LINKED ISSUE #11214: Enzyme and React 16 workarounds
This issue is to document the workarounds that we have in place to work with some of React 16 features that aren't supported by Enzyme yet. For reference, https://github.com/airbnb/enzyme/issues/1553 is where the enzyme project is tracking their support of React 16 features.

At the time of creating this issue, we're still using enzyme 3.3.0 and enzyme-adapter-react-16 1.1.1 but the latest releases are `3.7.0` and `1.6.0`. Some of the issues may have been fixed.

- [ ] Mock for forwardRef in [Button](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/button/__mocks__/index.js).
- [ ] BlockContros's [skipped test](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-controls/test/index.js#L30).
- [ ] Only supports the legacy context API.

### PR DESCRIPTION
**Pull request by aduth**
Closes #11214 

This pull request seeks to update unit tests which had implemented workarounds to a previous lack of support for React 16 features, namely context and `forwardRef`.

Specifically:

- Drops a mock implementation of the `Button` component used in unwrapping `forwardRef`
- Un-skips a `BlockControls` snapshot test

In so doing, it bumps `enzyme-adapter-react-16` (once more from #13922) to the latest 1.10.0 release.

**Testing instructions:**

Ensure unit tests pass:

```
npm run test-unit
```

Ensure snapshot changes are sensible.

### CODE REVIEW

**Review by oandregal — APPROVED** [review]
Confirm that tests pass. Looked for `Button` in snapshots and all occurrences I've found are wrapped by `ForwardRef`. Also searched for any other mocks that may be related to this but haven't found any.

Glad to see this happen!

**Review by nerrad — APPROVED** [review]
looks good to me!

**Comment by aduth** [comment]
@nosolosw @nerrad If either of you has availability, could you check to see whether you can reproduce there being local changes to `package-lock.json` after running `npm install` on master? I see some shuffling around of the `enzyme-adapter-react-16`, which makes some sense as far as expecting a different resolved dependency detail than what was changed here, but puzzling in that we should have protections in place from having allowed this to be merged if there were more changes needed.

**Comment by nerrad** [comment]
yup seeing changes in package-lock.json: 

terminal-screenshot

**Comment by nerrad** [comment]
It is puzzling, but I wonder if this branch was up-to-date with master before the merge (might not have known because it would be a fast-forward merge) and something recently got merged into master that affected this (so the normal build checks on travis for the branch didn't pick it up?)

Also, not sure it matters but the version of npm I ran on locally was `6.7.0` and in a mac osx environment.

**Comment by aduth** [comment]
> It is puzzling, but I wonder if this branch was up-to-date with master before the merge (might not have known because it would be a fast-forward merge) and something recently got merged into master that affected this (so the normal build checks on travis for the branch didn't pick it up?)

Looking at the specific change to `package-lock.json` from this pull request:

https://github.com/WordPress/gutenberg/pull/14156/files#diff-32607347f8126e6534ebc7ebaec4853dL2898

It _appears_ wrong. I don't think we would ever expect a +1/-1 change for a dependency update ? Or, at least, the changes introduced by running `package-lock.json` (new resolved version details) appear to make sense as being a result of bumping the version of this package.

I can plan to put together a pull request, and at the same time investigate further why the build did not fail.

**Comment by nosolosw** [comment]
Yeah, so do I (Ubuntu OS, npm 6.4.1). Here's the [diff](https://github.com/WordPress/gutenberg/files/2920087/package-lock.txt).

**Comment by aduth** [comment]
Okay, so I confirmed that `npm run check-local-changes` does produce an error when run immediately after `npm install`.

My current hunch is: We use `npm ci` in the Travis environment, which differs in that it does not update `package-lock.json`, so `check-local-changes` wouldn't consider it:

>It will never write to `package.json` or any of the package-locks: installs are essentially frozen.

*But*, at the same time, it is supposed to exit with an error status if the package lock is incorrect:

>If dependencies in the package lock do not match those in `package.json`, `npm ci` will exit with an error, instead of updating the package lock.

Running `npm ci` locally on `master`, I confirm both that it doesn't write to `package-lock.json` and that it exits _successfully_, which would explain why the build didn't fail. But it's not clear why it exits successfully; perhaps an npm bug?

Related: https://docs.npmjs.com/cli/ci.html

**Comment by nerrad** [comment]
I produced the same results as you running `npm ci` locally (v 6.7.0).  It does sound like the results are not as expected according to the docs for `npm ci` but I wonder if the heuristics matching the dependencies are more as expected for the comparisons.  In other words, its not really doing a tree-shaking comparison but simply looking at specific top-level dependencies (in which case it does mean its a little bit less reliable for what we want it to do here).

**Comment by nosolosw** [comment]
Same here. I actually tried to move `jest-preset-default` from `devDependencies` to `dependencies` to see if that yielded different results but got the same (I had to delete the `npm run check-licenses` of `postinstall` script so it doesn't fail due to a license check).

**Pull request merged**
