### PR TITLE
Use blockGap between Columns blocks 

### LINKED ISSUE #34453: Add support for blockGap between each column in Columns blocks
## What problem does this address?
With the new addition of `blockGap` support to theme.json, we should update the Columns block to reference that gap value — instead of a hard-coded value of `2em`. 

## What is your proposed solution?
Updating the styles to use the generated CSS property `var(--wp--style--block-gap)` instead of the hard-coded value of `2em`, while still providing a fallback to themes that do not have the variable. 

Originally called out in #34347.

### PR DESCRIPTION
**Pull request by richtabor**
## Description
Swapped out the hard-coded values of `1em` and `2em` to use `calc(var(--wp--style--block-gap) / 2)` and `var(--wp--style--block-gap)`, to leverage `blockGap` support added in https://github.com/WordPress/gutenberg/pull/33812. 

Closes #34453. 

## How has this been tested?
Tested with TT1 Blocks, TT1 and TT20.

## Screenshots 
Screen Shot 2021-09-01 at 10 40 03 AM

## Types of changes
Style changes in columns .scss

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
I think instead of doing this adhoc, I'd prefer if we explore making the columns block use an actual "flex" container. It will probably be more work though.

We're experimenting the same for social icons block here https://github.com/WordPress/gutenberg/pull/33987

I think all these horizontal blocks should be using the "flex" layout and avoid adhoc styles added to them directly. (Buttons, Social Links, Navigation, Columns). That way all options and features added to these layouts would benefit all these blocks automatically.

**Comment by richtabor** [comment]
> I think instead of doing this adhoc, I'd prefer if we explore making the columns block use an actual "flex" container. It will probably be more work though.

I agree, in the long haul — but perhaps this could be a stop-gap to start using blockGap sooner?

**Comment by youknowriad** [comment]
I wouldn't mind it personally

**Comment by jasmussen** [comment]
I'm as big of a gap fan as you'll find, so thanks so much for the PR! Testing wise, I'm seeing the same result before and after, so that's good:

before

It also does come with the benefit of tying the gap to the gap custom property, which makes it nicely theme.json'able or themable instead of hard-coded.

To echo Riad, it'd be nice to actually have a flex container here. The biggest benefit of flex & gap to me is that it can let the _parent_ container handle the display of items inside, relieving us of complex first-child/last-child rules. This one just replaces the left-margin value with the custom property. 

But it is a tiny step forward in that it does simplify styling the gap, so it might be worth it. It also seems like any existing theme CSS that customizes this gap would still work? Will this work just fine in themes that don't use theme.json? Should we use `var(--wp--style--block-gap, 2em);` to be sure?

**Comment by jasmussen** [comment]
Actually I missed a small issue, it looks like we have some additional rules in the editor.scss file that need updating:

Screenshot 2021-09-02 at 09 40 46

**Comment by richtabor** [comment]
Good call out @jasmussen — I've pushed an update to address those. 

Here are screenshots for blockGap used in each TT1 Blocks and Twenty Twenty One (to show a block theme vs. older theme):

TT1 Blocks Editor: 
Screen Shot 2021-09-02 at 9 02 41 PM

TT1 Blocks Front-end: 
Screen Shot 2021-09-02 at 9 02 56 PM

Twenty Twenty One editor:
Screen Shot 2021-09-02 at 9 07 05 PM

Twenty Twenty One Front-end:
Screen Shot 2021-09-02 at 9 06 31 PM

**Comment by richtabor** [comment]
@jasmussen 

> Should we use var(--wp--style--block-gap, 2em);

I don't personally think it's necessary to have a fallback, as Gutenberg will add a blockGap value with or without a theme.json present.

**Comment by andrewserong** [comment]
Thanks for adding this in @richtabor, I think this is good pragmatic next step to getting the Columns block using the `blockGap` value, without requiring a bigger refactor! 👍

> Should we use var(--wp--style--block-gap, 2em);

There's [a separate PR here](https://github.com/WordPress/gutenberg/pull/34491) that skips generating layout gap styles if folks opt-out of the global blockGap styling. If I'm reading it correctly, they can set the root level `spacing.blockGap` value to `null` using something like the following in the `theme.json` file:

```
{
...
	"styles": {
		"spacing": {
			"blockGap": null
		}
	}
}
```

This will skip generating the `blockGap` value for the use case of a theme wanting to allow control over individual values instead of the global value (or opt-out entirely). With it set to `null`, the CSS variable will not be generated, so in this PR, that'll currently result in an empty margin:

image

So, for that use case, it looks like it'd still be useful to have the `2em` fallback value in the `var()`s to avoid unintentionally setting margins to `0`?

**Comment by richtabor** [comment]
Thanks for pointing that out @andrewserong — I updated the PR to use the original `2em` value.

**Review by andrewserong — APPROVED** [review]
This is looking great to me @richtabor, it tests nicely, picking up the block gap CSS variable in block based themes, and falling back to the `2em` value in other themes I tested it with (e.g. TwentyTwenty, Maywood):

image

I really like the idea of going with this PR in the short-term, it'll also unlock us opting the Columns block in to the new `blockGap` support from #33991 once this PR lands. I think we get the best of both worlds in starting to use the gap CSS variable, but we also side-step dealing with the breaking change of refactoring the block's CSS to use flex or grid gap, which will be a more complex process since it could break existing themes' columns overrides.

LGTM — adds in the behaviour, and existing themes I've tested it with appear to be unaffected. There is a slight change with this one running TT1-blocks in that the blockGap value is by default set to `24px` in Gutenberg instead of `2em`, but I actually prefer the slightly tighter gap! Since it is a change, though, it might be good to get another review for a second opinion, too 🙂

**Comment by Mamaduka** [comment]
Hi, @richtabor

Can you rebase this PR, and I think we can merge it 👍

**Comment by richtabor** [comment]
> Hi, @richtabor
> 
> Can you rebase this PR, and I think we can merge it 👍

Done, tests are running. Thanks!

**Pull request merged**
