### PR TITLE
Add a lint rule for enforcing ellipsis

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by SuperGeniusZeb** [comment]
Would this conflict with the spread syntax and rest parameter syntax in JavaScript?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

**Review by aduth — APPROVED** [review]
Pushed ee875614492f3cefa4d55ba24e2be0eb46f16d04 to expand to cover all translation functions. This means technically context argument will be flagged, but it's more annoying to try to test `:nth-child` with consideration of plural functions, and it seems a minor consideration anyways.

**Comment by aduth** [comment]
@SuperGeniusZeb No, the selector is restricted to translation functions (`__`, `_x`, `_n`, `_nx`) and only the string arguments passed therein.

**Comment by aduth** [comment]
Slack discussion for context: https://wordpress.slack.com/archives/C02QB2JS7/p1525972061000078

**Comment by danielbachhuber** [comment]
Thanks @aduth !

**Pull request merged**
