### PR TITLE
HTML API: Move into 6.2 Compat Folder since inclusion in Core

### PR DESCRIPTION
**Pull request by dmsnell**
## Status

Is there any guidance on moving PHP support into `lib/compat`? I ran around like a self-driving taxi without its sensors trying to mimic what I saw, the worst kind of imitation. This is probably all wrong.

## What?

Moves the HTML Tag Processor out of `experimental` and into `combat/wordpress-6.2`

## Why?

The Tag Processor was merged into 6.2. It needs to load only when not already present from WordPress itself.

## How?

Copies files from the merged Core code into `lib/compat/wordpress-6.2` and updates the `load.php` file to conditionally load the compatibility class.

## Testing Instructions

Since code in Gutenberg relies on the Tag Processor tests should start failing if something goes wrong. Given that this is merged in Core, ensure that the files copied over are the appropriate files and do not differ from what's in Core. Ensure that they load when running on pre-6.2 versions of WordPress.

### CODE REVIEW

**Comment by noisysocks** [comment]
This looks right to me!

Looks like the lint errors are due to not passing `'gutenberg'` as the second argument to `__`.

Are there any changes that were made to the tag processor in Core before being committed that should be copied back into the plugin?

**Comment by gziolo** [comment]
> Looks like the lint errors are due to not passing 'gutenberg' as the second argument to __.

GitHub CLI is oversensitive in this case. We need to apply the same exceptions as we already use for core blocks that accept translations without the second argument.

This place:
https://github.com/WordPress/gutenberg/blob/862fe670f9a9890e9ebae67ceb2e28bd5bd856f8/phpcs.xml.dist#L28-L30

In fact, I don't think there are many cases where we want the second argument to be `gutenberg` so maybe we should flip the check and list only files where we want to see the second argument.

**Comment by dmsnell** [comment]
> Are there any changes that were made to the tag processor in Core before being committed that should be copied back into the plugin?

@noisysocks the code in this PR/branch diverges significantly from its merge base and those changes are coming back from Core. If it looks like there's nothing different it's likely because GitHub recently decided to hide the most important parts of PR diffs so they could prune out some DB calls 🙃 try clicking on "Load Diff" and you will see it.

**Comment by dmsnell** [comment]
@gziolo @noisysocks it'd be nice to get this in soon before it starts causing conflicts with Core, but do we need to resolve the linter issues here? is there a clear directive on what needs to happen before merging? I don't understand if I should be appeasing the linter or filing an exception or fixing the linter's rules.

**Comment by gziolo** [comment]
> @gziolo @noisysocks it'd be nice to get this in soon before it starts causing conflicts with Core, but do we need to resolve the linter issues here? is there a clear directive on what needs to happen before merging? I don't understand if I should be appeasing the linter or filing an exception or fixing the linter's rules.

I'm trying https://github.com/WordPress/gutenberg/pull/47749/commits/6765520f3888de6f95ac026abe39fa8632178b69 to see if that silences the linting "issues" that are false positives. Again, there should be no second param for the translations used in the code that polyfills functionality present in WordPress core. If that causes trouble, I will try to improve it on my local machine 😅

**Review by gziolo — APPROVED** [review]
Everything looks good.

**Pull request merged**
