### PR TITLE
Remove the document outline from the sidebar

### LINKED ISSUE #6478: Document Outline / Table of Contents inconsistent naming
## Issue Overview
The same feature seems to be called two different things in different locations in the Editor.

## Steps to Reproduce (for bugs)

1. Open the Demo page in Gutenberg editor.
2. View the `i` in the top left to see the "Document Outline"
3. View the Document in the sidebar to see the "Table of Contents"

## Expected Behavior
The feature appears to be the same, but is called Document Outline, or Table of Contents. Since the value appears to just be a graphical linked list of the headings structure, and not a "table" that matches up a heading to a page number (since presumably the term "Table of Contents" comes from printed media), I'd prefer it to be consistently called "Document Outline".

## Current Behavior
Document Outline:
doc-outline

Table of Contents:
toc

## Possible Solution
The immediate solution would be to rename the Table of Contents to Document Outline, so there is consistency.

The slightly more logical solution would be to question why this same information appears twice on the same page.

Since there may be other meta boxes being added to the Document sidebar, the presence of the value in there seems redundant in so much as it also takes up space. 

Also, the rest of the sidebar items are interactive - add a category or tag, write an excerpt, select a featured image, toggle discussion settings etc. The Table of Contents, don't _set_ anything - they are just a means of viewing the structure of the document, and if necessary, internal navigation of that document (though it really would be easier to scroll the content area for all but the longest of documents, rather than moving the pointer to the sidebar, opening the meta box, and finding and clicking the correct heading).

The version in the `i` has more space to accommodate longer headings, which makes it easier to read the structure without line-wrapping.

Can you consider removing the version in the Document sidebar completely?

### PR DESCRIPTION
**Pull request by youknowriad**
closes #6478

**Testing instructions**

 - Add a post with multiple headings
 - Check that the table of contents is not showing up in the sidebar.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I have some slight concerns about this because of what I reported in #6538.

I agree that it should be removed from the sidebar, and of course that doesn't preclude iteration on a fix for #6538, but it does make it a bit more pressing to address that issue.

**Review by karmatosed — APPROVED** [review]
Thanks for working on this, works well.

**Comment by jasmussen** [comment]
Seems cool! 👍 👍

I look forward to improvements to the popover that are being explored separately to make it an extension, and Chris' point is worth looking at as well.

**Comment by youknowriad** [comment]
Yep let's address those points in a separate PR :)

**Pull request merged**
