### PR TITLE
Make the lists more wysiwyg

### PR DESCRIPTION
**Pull request by youknowriad**
Similar to #29517 

When using lists in a theme without any stylesheet, the result in the frontend is different than the result in the backend, the problem is that in the backend there are default styles for lists. In order to solve this, we have two options:

 - Remove the lists editor styles (make the editor map the frontend)
 - Normalize the lists (make the frontend look like the editor)

I thought that the editor styles applied were better defaults for lists than what comes with the browser so I went with the second option. That said, it's the most impactful option, but I think most themes already override these styles in their stylesheets so it might not be that impactful.

What do you think?

**Testing instructions**

 - Test lists, nested and numbered lists in various themes, both frontend and backend.

### CODE REVIEW

**Comment by youknowriad** [comment]
Depending how impactful is this PR, we could decide to remove some of the opinionated styles or move them to "theme.scss" instead of "style.scss".

**Comment by jasmussen** [comment]
I love these PRs, and I love that we're at a place where we can put everything in its right place. Those editor styles you can likely remove once the iframe lands 👌 

However, something's off. This is what I see in trunk:

trunk

This is what I see in this branch:

lists

**Comment by youknowriad** [comment]
@jasmussen I suspect that your build didn't refresh the blocks stylesheet. I can't reproduce your issue on 2020

**Comment by jasmussen** [comment]
I'm still seeing it after running `rm -rf ./node_modules && npm install && npm run dev`, and I'm seeing it with other themes as well. I think it's right, and I think there are two reasons for it:

1. You zeroed out the margin: https://github.com/WordPress/gutenberg/pull/29556/files#diff-9db2e2e3e31d6cbce1fd2d9155704535fb7a56c2bad13a48e46d2be156f26a90R8

2. The CSS from `common.css` now bleeds through:
Screenshot 2021-03-04 at 12 52 44

**Comment by scruffian** [comment]
I see the same thing as @jasmussen. Would it be possible to enqueue the block library CSS after the wpadmin CSS?

**Comment by jasmussen** [comment]
Just discovered this:

Screenshot 2021-03-05 at 09 25 39

Which is an excellent example of why the work you're doing here is so important 💯 

(The above is not broken in trunk)

**Comment by youknowriad** [comment]
I fixed that sidebar tabs bug.

I'm still not able to reproduce the issue for the "common.css" style override personally, I think maybe the order of the stylesheet is inconsistent depending on other factors. So for the moment, I restored the editor styles for "ul" which should have a higher specificity, this is something that can be removed once we iframe the post editor.

**Comment by youknowriad** [comment]
I'm closing this in favor or #29590

**Pull request closed without merging**
