### PR TITLE
Align Submenu block and Nav Link block by including description and wrapping span 

### PR DESCRIPTION
**Pull request by prajapatisagar**
Addresses part of #57099

## What?

This PR fixes the missing `<span class="wp-block-navigation-item__label">` element for navigation items with submenus. 

## Why?

The absence of the `<span class="wp-block-navigation-item__label">` element in navigation items with submenus results in inconsistent markup, potentially impacting accessibility and styling.

## How?

The PR adjusts the rendering logic for navigation items with submenus to include the `<span class="wp-block-navigation-item__label">`.

## Testing Instructions

1. Add a navigation block
2. Add a navigation item to this block
3. Add a second navigation item to this block
4. Add a submenu item to the second navigation block
5. Check the source code

## Screenshots or screencast 
wp-block-navigation-item__label

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I understand the goal is to bring parity between the editor and the frontend but this is extra markup/classnames that we need to support in the future. Why do we need this span? Either in the frontend and the editor, or both.

**Comment by getdave** [comment]
We should bring both navigation-link and submenu blocks into line with each other. That means:

- remove span from both
- add span to submenu

**Comment by getdave** [comment]
@MaggieCabrera As I understand it, I think the `span` is added to the `core/navigation-link` block because there are also scenarios where a description also gets added _within_ the anchor tag.

https://github.com/WordPress/gutenberg/blob/7143076336126c8f09bb704eb0163a8c104dbdd6/packages/block-library/src/navigation-link/index.php#L255-L259

We don't support this on the submenu, which is likely because submenu came after Navigation Link and the two blocks have fallen out of sync as they rely on a lot of duplication.

https://github.com/WordPress/gutenberg/issues/52505 requests that description is added to the submenu block. Therefore I think we should consider pivotting this PR to add the description. At that point the span makes a lot more sense. Do you agree @MaggieCabrera?

@prajapatisagar Would you be interested in adjusting this PR accordingly?

**Comment by prajapatisagar** [comment]
Yes will update the PR accordingly.

**Comment by MaggieCabrera** [comment]
> #52505 requests that description is added to the submenu block. Therefore I think we should consider pivotting this PR to add the description. At that point the span makes a lot more sense. Do you agree @MaggieCabrera?
> 

Thank you for doing the work to uncover the reasons behind the current state of the block! That makes much easier to judge what the direction should be. And what you suggest sounds reasonable to me.

**Comment by prajapatisagar** [comment]
@getdave I have updated the feedback.

**Comment by carolinan** [comment]
Could the documentation about the class names be updated too as part of this PR?
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/README.md

**Comment by prajapatisagar** [comment]
@carolinan I have updated the documentation.

**Review by getdave — APPROVED** [review]
Thanks for your work here @prajapatisagar 👍 

When it comes to WordPress 6.8 I suggest we include a note in the miscellaneous dev notes about these markup changes.

**Pull request merged**
