### PR TITLE
Increase the meta boxes area width

### LINKED ISSUE #5562: Meta boxes area: consider to increase the width
In the Classic editor, plugins have all the available width for their meta boxes. Over time, plugins have built and adapted their meta boxes content based on the full available width, and hopefully implemented some responsiveness.

Instead, in Gutenberg the meta boxes area is always limited to a width of 608 pixels (plus some padding). This is to make the meta boxes area as wide as the post content above.

While it's nice, from a visual perspective, to have the post content and the meta boxes content aligned in one column, 608 pixels can be too limiting for the plugins content and might break their layout.

See the screenshot below, a very quick comparison between the Classic editor and Gutenberg:

screenshot-2018-3-12 edit post wordpress develop wordpress

I guess many plugins will face the same issue, not just the one in the screenshot above 🙂 

I'd propose to consider to increase the meta boxes area width to the full available width.

Alternatively, if the current width is preferred, this should be documented and plugins authors should be informed with a long enough notice so they can adapt and avoid layout breakage.

### PR DESCRIPTION
**Pull request by afercia**
This PR increases the meta boxes area width trying to match the current width in the Classic Editor.

This should help reducing the chances of layout breakage for plugins that expect the max available width for their meta boxes content. For more details please refer to the related issue.

Screenshot:

screen shot 2018-03-12 at 13 48 14

Fixes #5562

### CODE REVIEW

**Comment by jasmussen** [comment]
Have to step out for a bit so expanding the ping range :)

**Comment by paulwilde** [comment]
Personally I'd prefer if it would also not have the margin around each box and box-shadow so that the boxes look more consistent in style with those in the sidebar. I also notice that the box title and arrow is a different colour than those in the sidebar, would be nice if those were both consistent also.

Meta boxes are going to around for years (especially on sites that won't get rebuilt any time soon), so makes sense to make them look as if they are a native part of the UI.

**Comment by jasmussen** [comment]
Code change looks good. 

Designwise, I have no strong opinion personally. In order for us to stay nimble, let's merge this. Because:

- It's a tiny change, easy to revert if there are situations that regress as a result of this
- 2.4 was just released, so it's a good time to merge things so they can simmer in `master` over the weekend
- Given that there are many thumbs pointing upwards and positive reactions on both this PR, and the original ticket in #5562, it _seems_ that the pushback referred to in https://github.com/WordPress/gutenberg/issues/5562#issuecomment-372288437 is perhaps not due to the addition of a max-width to metaboxes. 

Let's still keep an eye on the feedback, and be mindful of this change. But for now, ship it 🚢

**Comment by IreneStr** [comment]
Something went wrong when solving the merge conflicts. I've created a new PR here: https://github.com/WordPress/gutenberg/pull/5565

**Pull request merged**
