### PR TITLE
Site Editor: Update support doc URL in Welcome Guide

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Updates support doc URL in Site Editor Welcome Guide as requested here - https://github.com/WordPress/gutenberg/pull/36172#issuecomment-985191904.

## How has this been tested?
To display editor modal, enter this snippet in DevTools console:

```
wp.data.dispatch('core/edit-site').toggleFeature('welcomeGuideStyles');
```

Confirm that URL is correct.

## Types of changes
Task

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Looks good, thanks!

I guess we should merge this though when the post is published, right?

**Comment by Mamaduka** [comment]
Thanks for testing, Nik.

> I guess we should merge this though when the post is published, right?

I'm not sure about the timeline here. @annezazu will have more details.

**Comment by annezazu** [comment]
I was planning to publish the doc in line with the release. However, if we need it live, I can ship it next week upon my return so this PR is all set for the next beta/RC. I'll plan to do that :)

**Comment by Mamaduka** [comment]
We can merge this, and docs can be published when they are ready. We know the final URL, so there's no need for them to depend on each other.

**Pull request merged**
