### PR TITLE
[RNMobile] Social Icons: Ensure inactive icons are visible with block-based themes 

### LINKED ISSUE #4780: Dark mode: Placeholders in Social Icons block not visible with some block-based themes
**Describe the bug**

When dark mode is enabled and a block-based theme with a light background colour is active, the placeholder icons shown for inactive icons are not visible in the Social Icons block.

**To Reproduce**

1. Enable dark mode on your iOS or Android device and open the app.
2. Activate a block-based theme with a light background colour, such as [Zoologist](https://wordpress.com/theme/zoologist), on a WordPress.com site.
3. Navigate to the site's post editor and observe the light background defined by the block-based theme.
4. Add the Social Icons block to the editor.
5. Notice that only the default active WordPress icon is visible, the other inactive, placeholder icons are not visible.

**Expected behavior**

All icons in the block should be visible, with the inactive, placeholder icons in gray and the active icons in colour.

**Screenshots**

| Expectation  | Actual |
| ------------- | ------------- |
|  |  |

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - Version: [19.7-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/19.7-rc-1)

**Additional context**

This is related to the fact that the editor's background colour doesn't change with dark mode when a block-based theme is active, as outlined in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4468.

### PR DESCRIPTION
**Pull request by SiobhyB**
* Gutenberg Mobile: https://github.com/wordpress-mobile/gutenberg-mobile/pull/6302

## What?

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4780, by ensuring inactive icons within the Social Icons block are always visible within the editor.

## Why?

There are currently certain scenarios where inactive icons in the block are invisible. This happens if a block-based theme with a light background is active, as the native editor displays the light background in contrast with the block's dark mode styles.

## How?

The logic associated with inactive icon styles has been updated so that, instead of using custom colours, we now always use a reduced opacity. This ensures the inactive icons are visible across all types of themes, and also matches the web's behaviour. Further discussion on this approach can be found in the comments here: https://github.com/WordPress/gutenberg/pull/55398#issuecomment-1772693340

## Testing Instructions

* Ensure dark mode is enabled on your device.
* Activate a theme with support for global styles. For example, [Byrne](https://byrnedemo.wordpress.com/).
* While in the site's /wp-admin area in a browser, navigate to the site editor (Appearance → Editor) and select a style with a white background.
* In the app, navigate to the editor for any of the site's posts or pages.
* Verify that the editor's background is white.
* Add a Social Icons block to the editor.
* Verify that the inactive icons in the block are visible.

### Testing Instructions for Keyboard

N/A, solely a visual change.

### Dark mode

| Dark background  | Light background |
| ------------- | ------------- |
|  |  |

### Light mode

| Dark background  | Light background |
| ------------- | ------------- |
|  |  |

### CODE REVIEW

**Comment by SiobhyB** [comment]
> **Note**
> The PHP tests are being super flaky across all PRs at the moment. I've tried re-running them a number of times. I don't believe anything in this PR itself is causing the failures.

**Comment by geriux** [comment]
Thank you for working on addressing this issue @SiobhyB !

I see you mentioned:

>Note, I considered using the block-based themes text colour/background for the inactive styles, but this ended up feeling a bit overbearing for inactive styles. The default styles felt like the best compromise.

But what if we just use the active background but with opacity for inactive states? Similar to what the web editor does:

Screenshot 2023-10-20 at 14 55 27

Have we considered that? It's just an idea, having this approach works too!

**Comment by geriux** [comment]
Something like:

Light|Dark
-|-
<kbd></kbd>|<kbd></kbd>


Light Block-theme|Dark Block-theme
-|-
<kbd></kbd>|<kbd></kbd>

**Comment by SiobhyB** [comment]
> But what if we just use the active background but with opacity for inactive states? Similar to what the web editor does:

@geriux, this is a great idea, I much prefer the look from your screenshots. cc-ing @osullivanchris, @paulforgione for a confidence check on the best approach, too.

**Comment by osullivanchris** [comment]
@SiobhyB @geriux I like using the background color with opacity. It looks good in the first example. I am a bit confused by the 4 screenshots shown [in the second example](https://github.com/WordPress/gutenberg/pull/55398#issuecomment-1772707086). To me, only the light mode screenshot looks like it has inactive buttons? The others all look fully active, unless I've missed something.

**Comment by geriux** [comment]
> @SiobhyB @geriux I like using the background color with opacity. It looks good in the first example. I am a bit confused by the 4 screenshots shown [in the second example](https://github.com/WordPress/gutenberg/pull/55398#issuecomment-1772707086). To me, only the light mode screenshot looks like it has inactive buttons? The others all look fully active, unless I've missed something.

I think it's because I didn't add opacity to the icons and just their backgrounds 😅 , but ideally the opacity should be applied to both the icon and the background. Something like:

<kbd></kbd>

**Comment by osullivanchris** [comment]
> I think it's because I didn't add opacity to the icons and just their backgrounds 😅 , but ideally the opacity should be applied to both the icon and the background. Something like:

Yeah that looks like what I would expect!

**Comment by SiobhyB** [comment]
@geriux, @osullivanchris, thank you both! I've gone ahead to make those changes and updated the screenshots in the PR's description. 

I set the opacity to `0.3`, as that seemed like a nice balance to my eye, but open to any changes you think should be made!

**Comment by osullivanchris** [comment]
@SiobhyB looks good to me!

**Review by geriux — APPROVED** [review]
LGTM! Nice work! 🚀 I've tested this on both iOS and Android

**Pull request merged**
