### PR TITLE
Template Part block - add border states in editor.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Adding is-selected, has-child-selected, and hover border states to the template part block in the editor. (as requested in https://github.com/WordPress/gutenberg/issues/22064)

These borders styles have been intentionally matched visually to fit the style added on the focus state by the block-list component, and change the color appropriately for each state:
https://github.com/WordPress/gutenberg/blob/5597947dadeba0b788269ae50676812c80eeb8f0/packages/block-editor/src/components/block-list/style.scss#L56-L74

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jeyip** [comment]
🚀 Hover state border works displays as expected in Safari, Chrome, Firefox, Edge, and IE11.

**Note:**
Unrelated to the changes made in this PR, but the left and right borders are cut off on my screen.

Screen Shot 2020-08-11 at 2 11 20 PM

**Review by jeyip — APPROVED** [review]
Thanks for handling the code changes @Addison-Stavlo. I see this as great foundation that we can iterate on and modify in future PRs.

**Comment by noahtallen** [comment]
I'll stick a design feedback label on here just to get some ✅ before merging :)

**Comment by noahtallen** [comment]
Here's a gif to see how it looks ^^

Note that in real life, it is more smooth. The frame rate of the gif is just poor. :)

Here is a screenshot of editing a child block in a narrower alignment:
Screen Shot 2020-08-11 at 3 01 07 PM

I'm noticing that in a lot of cases, it takes an extra click to interact with child blocks (and with the inserters). I _think_ this tradeoff is worth it, but it's definitely a consideration. If no block is selected, I'm noticing that some template part child blocks interact directly on first click (including site title and the nav block) but some take that extra click to get into (including paragraph and image blocks). It's kinda weird how that is inconsistent 🤔 And if you have a different block other than the template part selected first, then pretty much nothing will interact without that extra click.

**Comment by Addison-Stavlo** [comment]
> Unrelated to the changes made in this PR, but the left and right borders are cut off on my screen. (Make sure to click on and enlarge the linked image...the preview doesn't seem to be displaying the issue correctly)

I noticed this too!  I think on my screen I slightly see the border on the right side but not the left.  We would see the entire border if we added the `inset` option to the box-shadow border.  But since the current focus style from block-list doesn't do this I haven't changed it here.  Since it would feel a bit odd for the border to be different sizes in different states. 🤔

**Comment by Addison-Stavlo** [comment]
> I'm noticing that in a lot of cases, it takes an extra click to interact with child blocks (and with the inserters).

I see, I am noticing this too!  This is a result of our last change and we are forced to select the template part (clicking on any child block selects the template part first) before being able to select a child.

Maybe we should only disable the pointer events for the block inserters when the template part is not selected, so we can still get to edit existing child blocks in 1 click. 🤔

**Comment by jeyip** [comment]
> actually this does not seem as simple as anticipated.

I've been investigating this as well. It looks like the inserter is not a descendent of the block-list. It's actually rendered in a popover closer to the root of the DOM. This is why we're having trouble selecting it when evaluating the hover state of `.block-editor-block-list__block[data-type="core/template-part"]`.

**Comment by dubielzyk** [comment]
Testing it right now. It feel really nice. The two modes are making it extra complicated to get this feeling right. I love the hover in edit mode, but it feels weird that it doesn't appear everywhere. When I originally outlined this I didn't think we'd have a hover border in Edit mode since that's not how Edit mode behaves. I didn't explain this well in the [original design dump](https://github.com/WordPress/gutenberg/issues/22064#issuecomment-667084051) though.

I think we should have only the hover border appear in Select mode. And when you have Edit mode we shouldn't have any hover border, but still have the active border as outlined in [this comment](https://github.com/WordPress/gutenberg/issues/22064#issuecomment-667084051).

Does that make sense? Would love further thoughts.

**Comment by jeyip** [comment]
> When I originally outlined this I didn't think we'd have a hover border in Edit mode since that's not how Edit mode behaves.

Ahhhh. I see that in your original design dump now. 

I'm playing around with `select mode` while cross-referencing your designs, and it seems like there are two distinct design proposals. The `select mode` hover border for a template part is displayed with a subtle color when a child block is hovered or selected. Does that sound right @dubielzyk ?

Screen Shot 2020-08-12 at 1 22 42 AM

As for `edit mode`, it's a similar idea. The proposal is that, when focusing a child block, a subtle gray border appears around the template part.

Screen Shot 2020-08-12 at 1 34 54 AM

**Comment by dubielzyk** [comment]
>Does that sound right @dubielzyk ?

Exactly. That's the most subtle improvement and the one that would leave it as close to as it is today while also trying to achieve the goal. Once we have that we can build by adding labels, noticed etc. But I think it's important to build something first that tries to work within the parameters.

Once we start adding borders on hover in Edit mode we start ruining the modes themselves and it would then require us to rethink how the modes work.

**Comment by Addison-Stavlo** [comment]
> when a child block is hovered

Currently select mode disables the ability to hover child blocks until either the parent is selected or other children have been selected.  In case A, the parent is selected and has the blue border and children have the 'grey' border on hover.  In case B, the selected child has a blue border and other children have the grey border on hover (and we have the grey border on the template part now from the has-child-selected state).

If our goal is to have the children of the template part hover-able before the template part is selected, that is a diversion from select mode's functionality.  Not only would this currently require a bit of a 'hacky' solution (or just an overhaul of select mode itself for everything to remain consistent with other blocks), but would create inconsistencies with the behavior of select mode in the editor.  This would also make the children of the template part more easily selectable and editable than children of any other types of blocks, which decreases the concern of which parent they belong to and how that might effect things differently than standard blocks.

**Comment by Addison-Stavlo** [comment]
We removed the hover-state border in edit mode.  So now we have:

In **edit** mode:
borders-edit-mode

In **select** mode:
select-mode-borders

I think these are subtle, non-intrusive changes that will have a pretty decent effect on visibility.  I think it coveres everything from the border designs?  Except for the **select** mode design for:

Screen Shot 2020-08-12 at 1 42 51 PM

Since this type of hover state isn't possible in select mode until the parent or other children have already been selected, and there would be some concerns implementing it for template parts only (outlined more in my comment above).

**Review by noahtallen — APPROVED** [review]
This works well for me. My one nitpick is: is it possible to make the border a slight bit smaller in the "editing an inner block" state? It seems like it could be just a bit less intense, if that makes sense

**Comment by jeyip** [comment]
Looks good to me 🙂

**Non-blocking**
Should the border-color be slightly more understated?

**Comment by noahtallen** [comment]
haha, I guess we noticed a similar thing. Either color or width or both could make it less understated, I guess

**Comment by Addison-Stavlo** [comment]
> haha, I guess we noticed a similar thing. Either color or width or both could make it less understated, I guess

Yeah, we should probably try to match its width/color to the grey border applied by select mode hover state.  Looking for what that is...

**Comment by Addison-Stavlo** [comment]
So we are really nitpicking at the border now, but these Gifs might help point out the confusion Im having on which style we should conform to in terms of border width:

Notice the border stays the same width as we go from the blue border of the template part to the grey border when the child is selected:
same-width-as-focusmode

Notice how the grey hover-state border in select mode has a slightly smaller border width:
different-border-select-hover

So I wonder if it is better to conform to the border styles of the blue/focus state, or the grey hover state in select mode. 🤔

**Comment by noahtallen** [comment]
> It is matched in size to the border applied by focus/select state on the template part (the blue border).

In my brain, it makes sense to be less prominent than this, so I can definitely see a case for matching the hover state for select mode

**Comment by Addison-Stavlo** [comment]
> In my brain, it makes sense to be less prominent than this, so I can definitely see a case for matching the hover state for select mode

Updated to match the child-selected state gray border to the gray border shown in select mode hover state.

**Comment by dubielzyk** [comment]
This is looking good to me. Thanks for the context. If we can't select child blocks in Select mode it seems like it'll be harder to use.

I like the GIF where the border widths are the same, so we should aim for that. Can we change the gray color to make it light-gray-700? Or can you point me to the color spec we're relying on and I'll select an appropriate color?

**Comment by Addison-Stavlo** [comment]
> I like the GIF where the border widths are the same, so we should aim for that.

Gif 1 - where the border widths are the 'same', is the same border used in gif 2 where it is 'different' from the hover border applied by select mode.  So having gif 1 causes gif 2 since the 'blue focus border' and the 'gray hover border' from select mode have different widths by default.  We had updated since these gifs to match the opposite, so the blue border is the only wide one ($border-width-focus) while the grey border is thinner ($border-width), which seems to make sense in the states they are used given their names.  Should can increase the border width to achieve the state shown in those gifs again? 🤷‍♀️ 

> Can we change the gray color to make it light-gray-700? Or can you point me to the color spec we're relying on and I'll select an appropriate color?

We can, although that seems very light?  Here is light-gray-700 in contrast to the border applied by the select mode hover state (also notice these are the same widths now in this state, contrary to the above gifs we were talking about):
light-gray-700-2
The darker border is the default applied by select mode in hover state.  The lighter border is our addition using the light-gray-700.  I came by gray-600 previously by visually matching these to be the same color.

> Or can you point me to the color spec we're relying on and I'll select an appropriate color?

[Here is where the base colors live](https://github.com/WordPress/gutenberg/blob/master/packages/base-styles/_colors.scss) - by the comments there is seems gray-200 is the 'standard' border color, but that seems about the same as the light-gray-700 shown above.  I figured it was best to match the color to the gray border in select+hover but we can change it around to whatever makes sense.

**Comment by dubielzyk** [comment]
Thanks for the info. Let me have a look and let's tweak the colors at the last stage. There's a few other things I'm wondering:
- How come Selection mode highlights [two things in this video](https://d.pr/v/JHBUcz)? One for the image itself and one for the container around it, yet the whole thing seems to only be one block element (Site Logo).
- Is it possible to not have the page jump around when selecting different template parts? [See video](https://d.pr/v/2pK15F)

**Comment by dubielzyk** [comment]
>The lighter border is our addition using the light-gray-700. I came by gray-600 previously by visually matching these to be the same color (and verified by searching the codebase that gray-600 is indeed the color applied by select mode hover state).

Quick comment on the color. The reason for wanting a lighter color (~gray300) is so that, in Selection mode, the template hover part border and block hover border isn't the same. With them both the same we end up with [this](https://d.pr/v/kkGfir). The goal is to just highlight that you're selecting a block that's part of something bigger (the template part). Does that make sense?

**Comment by Addison-Stavlo** [comment]
> How come Selection mode highlights two things in this video? One for the image itself and one for the container around it, yet the whole thing seems to only be one block element (Site Logo).

In that video the block in question is the site logo, which has that external wrapper.  Currently the actual block used in this header from seedlet is an image block, which is not the same as site logo and lacks that outer wrapper, etc.

> Is it possible to not have the page jump around when selecting different template parts?

Yeah, but it's not exactly straight forward what is causing it.  The Post Content block also seems to do the same thing (and when group blocks nest either of these selecting them seems to do the same).  I think it's a separate bug to fix outside of this issue specifically.

**Comment by Addison-Stavlo** [comment]
Re - the Colors:

> Does that make sense?

100%, that makes sense.  Give this a spin and see how it feels?  There isnt a gray-300 defined for whatever reason, so for now this is set to gray-200 since that was listed as the standard border color in the file.  We can change it to light-gray-700 if that makes more sense too.  Whatever you think works best sounds good to me.

Also, do you have any idea about what the dark theme color should be for this?  I know its kind of an odd question since we don't have a dark block based theme currently.  I currently set it to gray-700 since that should be a small contrast to a dark theme?  (The other 'wp-admin-blue' border is already taken care of as that consistently turns to white in dark themes, but for our less-apparent border color we do need to set something 🤔 ).

**Comment by noahtallen** [comment]
> But this is more related to the actual block appender system itself and not really specific to the template part block's implementation.

+1. I agree this needs to be drastically improved since it feels very rough, but we can do that in a separate issue :)

**Review by noahtallen — APPROVED** [review]
cc @MichaelArestad @shaunandrews do you have thoughts about this? Unless there are concerns, I think we can move forward with this!

Current look:



Regarding code, I think in the future we might want to make this more general. I could see the same style being useful for the post content block, since it is a block container in the same way. I could see us wanting to apply this style if:
- The block is an inner block controllers
- Or just if the block has inner blocks in general

But that's a discussion code wise :)

**Comment by MichaelArestad** [comment]
@noahtallen It's not really clear to me what the border alone represents or why it is there. I know there is work being done with a label as well so I'm waiting to see how the label is implemented before worrying too much about it.

**Comment by noahtallen** [comment]
it's representing the area around the block area the user is editing. currently it's almost entirely impossible to tell without clicking all over the place to find where the template part ends and begins. but the label will definitely help things a lot too :)

**Pull request merged**
