### PR TITLE
Stop displaying FontSizePicker dropdown when there are no fonts.

### LINKED ISSUE #11628: Hide the Font Size picker on Paragraph blocks when there is only one size defined
**Is your feature request related to a problem? Please describe.**
When the `editor-font-sizes` array has been limited to a single item, paragraphs only have one size. If custom font sizes are also disabled, the font size picker becomes a redundant control. See below screenshot:
image

**Describe the solution you'd like**
When custom font sizes are disabled, and only a single `editor-font-size` is set, the font size picker should not be displayed.

For instance, given the following code:
```php
<?php
	add_theme_support( 'editor-font-sizes', array(
		array(
			'name' => __( 'Normal', 'gutenberg-test' ),
			'shortName' => __( 'N', 'gutenberg-test' ),
			'size' => 16,
			'slug' => 'normal'
		),
	) );
	add_theme_support('disable-custom-font-sizes');
```

I would expect to see the following:
image

**Describe alternatives you've considered**
This could potentially be solved on a case-by-case basis with some custom JS, or by creating a custom block. However, these are not particularly good solutions compared to a simple conditional statement in the original block definition.

### PR DESCRIPTION
**Pull request by Naerriel**
## Description
Closes #11628.
The FontSizePicker currently displays a dropdown with fonts, even when there are no fonts.
This change stops displaying the dropdown in this case.

## How has this been tested?
In `packages/components/src/font-size-picker/index.js` I overwrote `fontSizes` to `[]` and the dropdown would not display anymore.
Ran `npm run test` and see that all tests passes.

## Screenshots 
image

## Types of changes
Bug fix.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
@Naerriel What was the PHP you used to set the font sizes to empty?

**Comment by Naerriel** [comment]
@chrisvanpatten Excellent question. I haven't used the PHP, I set it in JS.
I forgot about that part of the issue. I don't know how to do that and whether it is even possible.

Possible solutions:
1. Modify the default WordPress behaviour to allow disabling editor font sizes (has probably no use case).
2. Close the Pull Request.

I'm not sure if I have got the call to action reached in #11628 correctly as well.
I could delete the Dropdown alongside the reset button, if there is one editor font size and the custom font sizes are disabled, which was the expected behaviour posed by the original poster.

What do you think?

**Comment by chrisvanpatten** [comment]
@Naerriel we do have a PHP function for pre-defining the dropdown sizes, `add_theme_support( 'editor-font-sizes', (array) $sizes );` but from what I don't know if it's possible to set an empty array. If that is possible, and works in combination with this PR, it seems like a great fix. If it isn't possible it might be worth a core patch to allow that behavior so this can land.

**Comment by Naerriel** [comment]
@chrisvanpatten Yes, when you asked your question, I tried to do it in several ways but none worked.

I can patch this behaviour in the core, but I don't think people will use it. If you think that this should be done, I can get my hands on that :smile:

**Review by jorgefilipecosta — APPROVED** [review]
Thank you for your contribution @Naerriel and thank you for reviewing @chrisvanpatten 👍
It should be possible to use `add_theme_support( 'editor-font-sizes', array() )`;. But there is a bug that is affecting this change. I will open a follow-up PR to address this problem.
The change in this PR makes total sense and fixes a bug where the dropdown renders incorrectly so independently of the other bug so I'm going to merge it and then we can continue the iteration.

**Comment by nervewax** [comment]
@jorgefilipecosta Are you able to link to your pull/issue relating to the fix preventing `add_theme_support( 'editor-font-sizes' )` from acting the same way as `add_theme_support( ''editor-color-palette' )`?

[This issue](https://github.com/WordPress/gutenberg/issues/11628) was closed, however the original problem still exists.

**Comment by aduth** [comment]
@nervewax It can be found at:

- #13824
- https://core.trac.wordpress.org/ticket/46290

**Pull request merged**
