### PR TITLE
Add more CI status badges to README

### PR DESCRIPTION
**Pull request by ceyhun**
Added all the GitHub Actions workflow badges to the README. Seems a bit crowded now, any ideas about the layout appreciated!

### CODE REVIEW

**Comment by guarani** [comment]
I previewed it [here](https://github.com/WordPress/gutenberg/blob/68548c9935b17d7439c38abc9b52d8941f51ba6f/README.md):

| Screen Shot 2020-10-14 at 09 39 04 |
| - |

I think it doesn't look overly crowded, although if some of the workflows had shorter names it could work better, e.g.:
| Before | After |
| - | - |
| Performance Tests | Perf Tests |
| End-to-End Tests | Web E2E Tests |
| Static Analysis (Linting, License, Type checks...) | Static Analysis |
| Unit Tests | Web Unit Tests |
| Create Block | Create Block (_leave as is_) |
| Storybook GitHub Pages | Storybook |
| React Native E2E Tests (iOS) | iOS E2E Tests |
| React Native E2E Tests (Android) | Android E2E Tests |
| Compressed Size | Compressed Size (_leave as is_) |

What do you think?

**Review by guarani — COMMENTED** [review]
I previewed it [here](https://github.com/WordPress/gutenberg/blob/68548c9935b17d7439c38abc9b52d8941f51ba6f/README.md):

| Screen Shot 2020-10-14 at 09 39 04 |
| - |

I think it doesn't look overly crowded, although if some of the workflows had shorter names it could work better, e.g.:
| Before | After |
| - | - |
| Performance Tests | Perf Tests |
| End-to-End Tests | Web E2E Tests |
| Static Analysis (Linting, License, Type checks...) | Static Analysis |
| Unit Tests | Web Unit Tests |
| Create Block | Create Block (_leave as is_) |
| Storybook GitHub Pages | Storybook |
| React Native E2E Tests (iOS) | iOS E2E Tests |
| React Native E2E Tests (Android) | Android E2E Tests |
| Compressed Size | Compressed Size (_leave as is_) |

What do you think?

**Comment by gziolo** [comment]
Thank you for opening a follow-up PR. How about we remove some of the less important badges to make sure it isn't so crowded? I think some of those jobs integrate with workflows in PRs before merging like Compressed Size or Performance Tests. @youknowriad should know better.

**Comment by youknowriad** [comment]
True, the storybook deploy too, though to be honest, I don't care much about whether it's crowded or not :P

**Comment by ceyhun** [comment]
Just removed some of the badges and seems to look better now.
@guarani I'm not sure if it's possible to change the text in the badges as the badge svg already comes with it: [for example](https://github.com/WordPress/gutenberg/workflows/Static%20Analysis%20(Linting,%20License,%20Type%20checks...)/badge.svg). It might also be confusing to use different names than workflows for the badges.

**Comment by guarani** [comment]
> Just removed some of the badges and seems to look better now.
@guarani I'm not sure if it's possible to change the text in the badges as the badge svg already comes with it: [for example](https://github.com/WordPress/gutenberg/workflows/Static%20Analysis%20(Linting,%20License,%20Type%20checks...)/badge.svg). It might also be confusing to use different names than workflows for the badges. 

Looks good to me, @ceyhun!

**Review by gziolo — APPROVED** [review]
Looks great 🙌

**Pull request merged**
