### PR TITLE
Upgrade to gradle 6.1.1

### PR DESCRIPTION
**Pull request by oguzkocer**
## Description

This PR upgrades `react-native-bridge` and `react-native-aztec` android projects to Gradle `6.1.1` and gradle plugin `4.0.1`. Upgrading Gradle periodically is a good practice to get the most out of it and beside that, this change is necessary to make these projects play well with WPAndroid composite builds. Composite builds require the same version of Gradle and gradle plugin, so it matches the current WPAndroid values. Technically, we don't have to upgrade the `react-native-aztec` project right now, but I think it's good to do that together with `react-native-bridge`.

I suggest reviewing this PR commit by commit as most of the changes are auto-generated. I'll quickly go over them to make it easier:

* dcf1b7fd87ced54dcb5cdd8d21582cff1145724e and 9f0f47ea55d551ce82c80e18b27898a1406fadfb renames the root project name for the projects to not include `/` as this is not a legal character. This is necessary to get gradle the project to build and it's necessary for composite build to work.
* 58cec5f2a1d5e8ae3cd1db1c94f5e63f98a78bc6 and 4fae4e6d0e0ce4b709c157cbb374026a4dd10339 upgrades gradle to `6.1.1`. This is done by running `./gradlew wrapper --gradle-version 6.1.1 --distribution-type all` command in each project and all the changes are generated by Gradle wrapper.
* eda5f96e080ba9171c7748ef1d8dc0408ed793b7 upgrades android Gradle plugin to `4.0.1`.

cc @mokagio

## How has this been tested?

These are tested by running `./gradlew build` on both projects. Currently `react-native-bridge` will fail with the following error:

```
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the : project caused this error: ~/gutenberg/packages/react-native-bridge/android/vendor/hermes-engine/hermes-release.aar
```

This issue is [addressed in another PR targeting the same WIP branch](https://github.com/WordPress/gutenberg/pull/28216/files#diff-320e7dacc9e9a83ac8128d299319f82cf6dfa2609e0ebbc043d13de33ea92773L185-L186). I did not want to duplicate the change, so in order to test, it might be good to comment out those lines.

I've also tested this as part of composite build for WPAndroid.

## Screenshots 
N/A

## Types of changes

Upgrades to tooling for the android project.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Changes look good. While we're updating gradle in react-native-bridge and react-native-aztecs we should probably do https://github.com/WordPress/gutenberg/tree/master/packages/react-native-editor/android directory as well. 

The lint error in CI seems to be caused by some local changes after running `npm install`. If you commit those changes that error should go away. Not sure about the Performance Test fail, but I doubt it's caused by any changes in this PR, so we can always clear those up on the target branch if need be (might have to pull in latest gutenberg master, not sure).

**Comment by oguzkocer** [comment]
Thank you for the review @cameronvoell!

> Changes look good. While we're updating gradle in react-native-bridge and react-native-aztecs we should probably do https://github.com/WordPress/gutenberg/tree/master/packages/react-native-editor/android directory as well.

I've made this change in https://github.com/WordPress/gutenberg/pull/28305/commits/bbce25ae240e6cc426efa7dc056274c55ab383c6 (generated by gradle script) and https://github.com/WordPress/gutenberg/pull/28305/commits/72a03e63870247d69772cbb66f2ebc419c6e9555. Unfortunately, I am unable to test these changes as I couldn't get gradle to build the project before or after the change. I am getting the same error for each gradle version (once the `Direct local .aar file dependencies are not supported when building an AAR` is bypassed as explained in the PR description) so I guess that's better than nothing. Here is the error I have:

```
ReferenceError: SHA-1 for file ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js) is not computed
error SHA-1 for file ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/lib/polyfills/require.js) is not computed. Run CLI with --verbose flag for more details.
    at DependencyGraph.getSha1 (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:263:13)
    at ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:211:26
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:46:24)
    at _next (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:66:9)
    at ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:71:7
    at new Promise (<anonymous>)
    at ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:63:12
    at Transformer.transformFile (~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/DeltaBundler/Transformer.js:236:7)
    at ~/.npm/_npx/17390/lib/node_modules/react-native/node_modules/metro/src/Bundler.js:87:34
```

> The lint error in CI seems to be caused by some local changes after running npm install. If you commit those changes that error should go away.

The lock file having to be changed without a specific update is a bit weird to me, but if that's part of the process 🤷‍♂️ I've made this change in https://github.com/WordPress/gutenberg/pull/28305/commits/f844285f2f586d6eaae787040997ff1bee40c0a1. I wasn't even sure what to use as the commit message since I didn't manually update anything.

>  Not sure about the Performance Test fail, but I doubt it's caused by any changes in this PR, so we can always clear those up on the target branch if need be (might have to pull in latest gutenberg master, not sure).

Sounds good to me. This PR doesn't change anything in the JS side, so I assume it's unrelated as well.

**Comment by mokagio** [comment]
This looks good to me. 

I run `./gradlew build` in both packages and they succeeded (with the Hermes caveat for the `-bridge` one).

I tried merging these changes on my Bintray publishing work, generating an AAR (`6b3a225c5579ead137fe57cc6c01057b83713522-built-locally`), and using it on the `gutenberg-composite-build` branch in WordPress Android. `./gradlew assembleVanillaRelease` and running it from Android Studio both worked 👍

**Comment by mchowning** [comment]
Based on @mokagio 's testing, it sounds like we can go ahead and merge this to the feature branch. Would you like me to go ahead and merge @oguzkocer ?

**Pull request merged**
