### PR TITLE
Block Supports: Add missing UTF-8 conversion

### LINKED ISSUE #24445: Wide-aligned blocks: Non latin text characters are rendered as gibberish inside the block if set to Wide or Full Width
**Describe the bug**

First reported by @zdenys at https://github.com/Automattic/wp-calypso/issues/44759. The following is a copy of that issue, since it applies to Gutenberg.

**To reproduce**
1. Add a Cover block with paragraph of text with some or all non-Latin characters (I tried Norwegian, Japanese and Chinese)
2. Set Cover Block to Wide or Full Width
3. View Preview or Published site

**Expected behavior**
See all characters rendered normally on the front end just like on the backend. 

**Screenshots**

_Link: https://d.pr/i/5gdq1V_

_Link: https://d.pr/i/gFwXfS_

**Editor version (please complete the following information):**
- WordPress version: 5.5
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? gutenberg plugin
- If the Gutenberg plugin is installed, which version is it? 8.7

**Additional context**
Encoding issue. PR coming right up.

cc/ @sirreal @akirk @simison @yansern

### PR DESCRIPTION
**Pull request by ockham**
## Description
Fixes https://github.com/WordPress/gutenberg/issues/24445.

This should probably be backported to 8.7 (and potentially further back if needed).

## How has this been tested?
See #24445 for instructions on how to reproduce the issue. Verify that this PR fixes it.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. 

props @akirk @sirreal @simison for finding the fix

### CODE REVIEW

**Comment by mcsf** [comment]
@swissspidy: I'd love your eyes on this, if you can spare some time today.

**Comment by ockham** [comment]
Fix for 8.7:

```diff
diff --git a/lib/blocks.php b/lib/blocks.php
index e2298c33ca..b593256d76 100644
--- a/lib/blocks.php
+++ b/lib/blocks.php
@@ -254,7 +254,7 @@ function gutenberg_experimental_apply_classnames_and_styles( $block_content, $bl
 
        // Suppress warnings from this method from polluting the front-end.
        // @codingStandardsIgnoreStart
-       if ( ! @$dom->loadHTML( $block_content, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_COMPACT ) ) {
+       if ( ! @$dom->loadHTML( mb_convert_encoding( $block_content, 'HTML-ENTITIES', 'UTF-8' ), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_COMPACT ) ) {
        // @codingStandardsIgnoreEnd
                return $block_content;
        }

```

(Code was moved and files renamed by #24351)

**Comment by mcsf** [comment]
OK, so this is not affecting WP 5.5 (feel free to double-check), which makes sense considering that the functionality in question (Global Styles-related block support) was intentionally merged after code freeze.

I'll update the metadata accordingly.

**Comment by sirreal** [comment]
I've also tested and confirmed that this **does not** appear to affect WordPRess 5.5.

**Review by sirreal — APPROVED** [review]
I am not an expert in encodings nor DOM manipulations via PHP.

I have confirmed this bug is present in Gutenberg 8.7.

I have tested and confirms that this fixes it in my testing:

I've created a post with a _Cover_ block containing the text `こんにちは世界`.

Without the patch:

Screen Shot 2020-08-07 at 17 22 04

With the patch applied (the block is un-edited):

Screen Shot 2020-08-07 at 17 21 45

This may be worth an 8.7.1 release.

**Comment by ockham** [comment]
```
FAIL packages/e2e-tests/specs/editor/various/adding-blocks.test.js (26.685s)
  ● adding blocks › inserts a block in proper place after having clicked `Browse All` from inline inserter

    expect(received).toMatchSnapshot()

    Snapshot name: `adding blocks inserts a block in proper place after having clicked \`Browse All\` from inline inserter 2`

    - Snapshot  - 4
    + Received  + 0

    @@ -1,13 +1,9 @@
      <!-- wp:paragraph -->
      <p>First paragraph</p>
      <!-- /wp:paragraph -->

    - <!-- wp:cover -->
    - <div class="wp-block-cover has-background-dim"><div class="wp-block-cover__inner-container"></div></div>
    - <!-- /wp:cover -->
    -
      <!-- wp:heading -->
      <h2>Heading</h2>
      <!-- /wp:heading -->

      <!-- wp:paragraph -->

      259 | 		);
      260 | 		await coverBlock.click();
    > 261 | 		expect( await getEditedPostContent() ).toMatchSnapshot();
          | 		                                       ^
      262 | 	} );
      263 | } );
      264 | 

      at Object.<anonymous> (specs/editor/various/adding-blocks.test.js:261:42)
          at runMicrotasks (<anonymous>)

 › 1 snapshot failed.
```

:confused: 

Seems like the DOM operation might remove the empty Cover div? :thinking:

**Comment by ockham** [comment]
Seems to pass locally. I'll re-run the test.

**Comment by ockham** [comment]
Passing now :relieved: 

We should add some test coverage for this though :thinking:

**Comment by ockham** [comment]
> We should add some test coverage for this though :thinking: 

A simple unit test for `gutenberg_apply_block_supports` that feeds it e.g. a wide-aligned cover block with some non-latin chars could do the trick.

**Comment by ockham** [comment]
I'll try writing a quick unit test for this.

**Comment by ockham** [comment]
Added a unit test. I also discovered that I needed to add a line to convert HTML entities back to UTF-8 (after `$dom->saveHtml()`) in order to make sure we feed UTF-8 in, we get UTF-8 (not entities) out.

**Comment by ockham** [comment]
FWIW, cherry-picked the unit test commit on top of `master`, ran them: They fail the block content check that I added, just like they should :tada:

**Pull request merged**
