### PR TITLE
[Block: Group] Add a CSS class to identify the row variation

### LINKED ISSUE #38126: There is no way for the front side to determine that a Group Block is a "Row" variation.
### Description

Since WordPress 5.9, the `wp-container-{id}` class is given to the Group block, and the `flex` style of "Row" is written for this selector.

Class names that can be used to determine whether a block is a "Row" (such as `is-row`) are not output, so the theme cannot adjust the style for "Row" only.

#### Why do we need classes like `is-row`?

In some cases, Block Styles are registered and used for Group blocks.

When these block styles are used in "Row "blocks, the design may be broken.

So, we need to make minor adjustments to the "Row" blocks.

### Step-by-step reproduction instructions

1. Place the "Row" block.

### Screenshots, screen recording, code snippet

スクリーンショット 2022-01-21 17 54 52

スクリーンショット 2022-01-21 17 54 58

### Environment info

- WordPress 5.9-RC3
-Twenty Twenty-One

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Adds the CSS class "is-row" to the group block when the row block variation is used.
Fixes https://github.com/WordPress/gutenberg/issues/38126

## Testing Instructions

1. Open or create a new post or page.
2. Insert a row block and a group block. Save.
3. Apply the PR, refresh the post/page if needed.
4. Add a new row block.
5. Transform the group block to a row.
6. Confirm that:
 - All row blocks has the CSS class is-row, in the editor and front.
 - There are no block validation errors.
7. Transform a row to a group. Confirm that the CSS class is-row is not used on the group.

## Types of changes

Enhancement, new feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for the PR and to be honest, my initial reaction is that I don't think we should be doing that.

I understand the need for folks to design things specifically for the some variations but I don't think having a classname here is the right approach, I'm afraid that it might cause us issues when we introduce new layouts... When do we draw the line, what about when we introduce the vertical/horizontal rows, do we need a className there... Basically, it opens the question of when to stop? When a given property of a block should result in a className or not.

I'd love to learn more about the specific styles that we want to apply differently here.

**Comment by ocean90** [comment]
The reason mentioned in #38126 sounds legit. Some block styles may not be relevant if the row variation is used so you want to avoid having that style applied if for example the `is-row` class exists. But maybe a better solution would be to not show that style if it doesn't work with a specific variation? I don't think that's possible right now.

For the records: There's already a similar [`is-flex-container` class for the Post Template block](https://github.com/WordPress/gutenberg/blob/2323eeca3d0bc8b2723333ccb831ae731ae841aa/packages/block-library/src/post-template/edit.js#L180-L185).

**Comment by Humanify-nl** [comment]
I'd like to add to this discussion that WordPress has always been developer friendly and we need to keep it this way. It has to still work if theme authors decide to disable certain functionality (like blockgap & wp's opinionated block margins) and do it with their own CSS.

Apart from the argument of handling block styles on row variations (which is a good argument on itself), look at what happens when a developer wants to take over how spacing is handled?

**Vertical spacing**
I know WP likes to handle its vertical margins and blockgaps with 'magic' by throwing these on there / removing them when WP opiniates that it is applicable. But a theme author might disagree for certain designs and do it with custom CSS.

This is where Rows & Groups become unmanagable (think of things like `margin-top: 0` for first child, it will not work properly in a row variation).


As @youknowriad posits, maybe a class isn't the best solution but;  

>When do we draw the line, what about when we introduce the vertical/horizontal rows, do we need a className there... Basically, it opens the question of when to stop?

We should draw the line when there is no need for it from a developer perspective. In this case there certainly is. Because I think there are a lot of developer out there that do not want to give users control of spacing because it risks accidentally having users break the carefully made designs.

Extra edit:
I think my TL:DR is that theme.json exists to control the theme values. But sometimes it slips past the general thinking here that developers may turn off certain aspects (like block gap), and then this argument of 'not being able to identify a row' is an issue.

**Comment by carolinan** [comment]
I don't believe the row is tied to the orientation? The default row is horizontal, and would not need an orientation class.
The orientation setting in the layout panel already adds a class,` is-vertical` for the vertical layout. So a vertical row would get the two classes `is-row is-vertical`.

**Comment by youknowriad** [comment]
> I don't believe the row is tied to the orientation? The default row is horizontal, and would not need an orientation class.
The orientation setting in the layout panel already adds a class, is-vertical for the vertical layout. So a vertical row would get the two classes is-row is-vertical.

Yes, this is precisely my argument. The use-case in the issue is unclear, What style are we trying to apply, something that applies to vertical containers or specifically to flow layouts. I think we need that style to understand better.

Generally speaking, this ties with the discussion in #38998: Basically what kind of block state should be reflected as classnames and how. It was argued that most of the state should be server-side generated as it's not semantic.

Also, for this particular change, It seems better to have `is-layout-flex` `is-layout-flow` and added to all blocks that use layout instead of an adhoc fix in the save function of the group block.

**Comment by Humanify-nl** [comment]
> It seems better to have `is-layout-flex` `is-layout-flow` and added to all blocks that use layout instead of an adhoc fix in the save function of the group block.

This is a great proposal. 

Since the amount of blocks has grown over time, from a developer experience perspective, it would be fantastic if there would be a way to know if a block is a 'layout block' (a block that is structure for other blocks) or not, _without tying it to the block-type._

Your proposal would indirectly solve this, it would make it easier to modify the CSS from WP in a consistent way. Because we can target 'only the blocks that have a structural layout function' by selecting these two classes (is-layout-flex, is-layout-row).

**Comment by carolinan** [comment]
I disagree that it matters what style the theme developer wants to apply, be it CSS grid, a pink border, or CSS flex. There needs to be a way for the theme developer to identify that the control has been enabled.
Especially in a controlled design system where the editor default styles need to be replaced.

**Comment by chthonic-ds** [comment]
> There needs to be a way for the theme developer to identify that the control has been enabled.

This is an important point. Adding a Row and a Group block results in identical markup and I've hit a few situations where it would have been convenient for a Row to self-identify as a variation of a Group block.

> It seems better to have is-layout-flex is-layout-flow and added to all blocks that use layout

For the reason mentioned above (["controlled design system where the editor default styles need to be replaced"](https://github.com/WordPress/gutenberg/pull/39181#issuecomment-1067554175)), I have themes where Group and Row blocks default to CSS grid layout. Neither of the suggested classes feel useful in that context.

**Comment by Humanify-nl** [comment]
I’m starting to think it is easier to make row a separate block instead. Doesn’t this solve the whole discussion of whether or not have a utility class for flex orientation? But then we’re probably throwing the baby out…

It starts to sound like we’re reinventing a wheel for utility on a block that do structurally separate things, while it is not a new thing in CSS at all. And now have a discussion about whether or not there should be a way to identify from the front-end what is what, and if that is needed at all (I think consensus is yes)

Isn’t this a simple case of horizontal OR vertical layout? Which could and should be accessible for many blocks (list, navigation, post-template, group, buttons) of which some already have, some don’t. My point is it shouldn’t be specific for the row variation block.

The classes could be ‘is-horizontal’ and ‘is-vertical’ ? (To decouple it from the flex terminology).

This raises the question, is the row variation even needed? Was it not a band-aid? Can a group not have these flex controls natively (horizontal/vertical switch + justify controls if horizontal is turned on)

Or maybe I’m missing out on some important distinction here?

**Comment by mrwweb** [comment]
@youknowriad 

> When do we draw the line, what about when we introduce the vertical/horizontal rows, do we need a className there... Basically, it opens the question of when to stop? When a given property of a block should result in a className or not.

As I've tried to describe in #38998, I think all or nearly all block states _should_ get a class in the front-end markup. A lot of folks here have offered great use-cases for a class identifying the row variation, and I think the discussion shows a really important point: it's impossible to predict what people will need these state classes for but you can be there will be things.

I think you're right that there might be a line for classes that shouldn't be included, but I think the assumption needs to be completely flipped. **All block states should have classes _unless_ a clear argument can be made for how the inclusion of a class could cause problems or is unnecessary.** (Example of a valid reason for exclusion: a state is coupled to some other state that already has a class).

I think @carolinan put it perfectly:

> I disagree that it matters what style the theme developer wants to apply, be it CSS grid, a pink border, or CSS flex. There needs to be a way for the theme developer to identify that the control has been enabled.

And re:

> It was argued that most of the state should be server-side generated as it's not semantic.

How that class is saved and generated is an implementation detail that I don't think really matters for the discussion of whether the class exists or not. If the way the class is implemented in this PR could be better, then that's fine, but it shouldn't be an argument against the class's inclusion.

**Pull request closed without merging**
