### PR TITLE
Add button focus style

### PR DESCRIPTION
**Pull request by ellatrix**
See #574. Also #520.

### CODE REVIEW

**Comment by iseulde** [comment]
Noticed that buttons don't have a focus styles while testing tabbing.

**Comment by afercia** [comment]
Right. Any focusable control should have a focus style, see https://github.com/WordPress/gutenberg/issues/574

**Comment by jasmussen** [comment]
❤️ that you're working on this. It's already much better in this branch. 

Design wise —  and perhaps @afercia can advise here as well: is it better to have _only_ the focus rectangle to indicate highlight, or would it be good to combine it with something like the hover style also?

**Comment by iseulde** [comment]
Might it be good to keep the focus style the same in all of WordPress?

**Comment by jasmussen** [comment]
> Might it be good to keep the focus style the same in all of WordPress?

Absolutely! Good point.

**Comment by jasmussen** [comment]
It seems like we'll want to do further work in order to fully address #574. But this is a GREAT step in the right direction. Thank you. Let's ship this and iterate.

**Comment by iseulde** [comment]
I agree, let's merge and iterate, I mainly just want to see where the focus is now. :)

**Comment by aduth** [comment]
Should the focus styles have been applied to `Button` generally, not `IconButton` specifically?

**Comment by iseulde** [comment]
`Button` already has focus styles, these were for `IconButton` specifically.

**Comment by aduth** [comment]
`.button` has focus styles, but not all `Button`s are `.button`s

**Comment by aduth** [comment]
Related: #839

**Comment by iseulde** [comment]
Okay, but they don't have these styles in common, so do we want them to share it?

**Comment by aduth** [comment]
I guess more to the point, we have `Button`s in the header which don't currently have focus styles even after these changes:

`master`:

image

With f36e1de (#839):

image

**Comment by afercia** [comment]
Not sure but the "Preview" is always disabled for me, any flow to follow to make it enabled? Worth noting disabled buttons are not focusable and shouldn't have a focus style.

**Comment by jasmussen** [comment]
> Not sure but the "Preview" is always disabled for me, any flow to follow to make it enabled? Worth noting disabled buttons are not focusable and shouldn't have a focus style.

This is a recent change, you have to save your post before it gets enabled. This is not explicitly the intended behavior, though, and it is subject to iteration. Ideally we'll make it behave exactly as the current preview button works.

**Comment by afercia** [comment]
> This is a recent change, you have to save your post before it gets enabled

Ah ok thanks. Saving is disabled for now so will wait 😉

**Pull request merged**
