### PR TITLE
Base Styles: Extract long-content-fade to its own file so it can be imported and reused.

### PR DESCRIPTION
**Pull request by vykes-mac**
## What?

Extract the `long-content-fade` mixin to it's own file.

## Why?

So that it can be easily reused by importing when needed. Whenever we need to use it we don't have to include the other mixins in the `_mixins.scss` which might cause collision in other codebases.
## How?

I'm moving the `long-content-fade` mixin from the `_mixins.scss` file into it's own file so it can be imported and reused easily.
## Testing Instructions

1. Checkout his branch to your local repo
2. Verify `_long-content-fade.scss`  can be imported without build errors.
3. In editor add a search block and remove buttons and labels. Preview the post:
       - in html remove search block `.wp-block-search__inside-wrapper` 
       - add class 
```css
.search-component__input-fade {
	display: flex;
	align-items: center;
	border-radius: 0;
	flex: 1 1 auto;
	height: 100%;
	position: relative;
	&::before {
		@include long-content-fade( $direction: right, $size: 70px, $z-index: 2, $color: #fff, $edge: 1px );
		border-radius: inherit;
	}
}
```
5. Verify the long-content-fade is still applied as shown below:
image
Notice fading edges where the text overflows.

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]
Looks great, @vykes-mac ! Thanks for the detailed description 😊

**Comment by jeffpaul** [comment]
@vykes-mac checking back in to see if you're able to confirm your username on WordPress.org so that we can properly credit you within the WordPress 6.2 release later this month?

**Comment by vykes-mac** [comment]
Hi @jeffpaul my username on wordress.org is vykesmac.

**Comment by jeffpaul** [comment]
@vykes-mac wonderful, thank you!  If you follow the steps in https://github.com/WordPress/gutenberg/pull/46485#issuecomment-1361559161, then next time this will happen automatically and I won't have to chase down this thread to remember/find your WordPress.org account... thanks!

**Pull request merged**
