### PR TITLE
Add 'Hero Tucker' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a block pattern for #20345.

Screen Shot 2020-03-24 at 11 41 31

### CODE REVIEW

**Comment by mtias** [comment]
I don't think we should merge this one until there's better control for the line height on the large text on the left.

**Comment by mtias** [comment]
Can we adapt this now that there's control over line height?

**Comment by enriquesanchez** [comment]
@mtias updated line-height:

Screen Shot 2020-03-30 at 15 56 27

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. Let me know if you think it can be improved or if we should close this PR instead.

**Pull request closed without merging**
