### PR TITLE
Writing Flow: fix reverse selection after block deletion from rich text

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

See also #22290.

Currently, when you press Backspace in an empty paragraph that is preceded by an image block (for example), the caret selection ends up at the last text field (caption) but not at end of that field.

It seems that some blocks are passing `onReplace( [] )` as `onRemove` to RichText, which is really strange. Semantically, this should be just `onRemove`, which also handles setting the selection correctly.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
> It seems that some blocks are passing `onReplace( [] )` as `onRemove` to RichText, which is really strange. Semantically, this should be just `onRemove`, which also handles setting the selection correctly.

I suspect that a bunch of blocks are doing it that way because one block did it that way first, and all the other blocks just copied the approach, so now doing it that way _appears_ to be correct because all the other blocks do it that way.

**Comment by youknowriad** [comment]
Do you think we can treat the onReplace([]) exactly like  onRemove on the reducer level (update selection)?

**Comment by ellatrix** [comment]
The selection doesn't happen in the reducer, but rather in the action. I guess we could add it in the replace action?

**Comment by youknowriad** [comment]
or maybe forward the replace action to the "remove" one if the array is empty. Also, I'm wondering if we need to update the selection if the array is not empty and if the behavior there should be different?

**Pull request merged**
