### PR TITLE
Fixes broken img link

### PR DESCRIPTION
**Pull request by mburridge**
## What?

Fixes a broken link to the image on the landing page

## Why?

Image didn't appear

### CODE REVIEW

**Review by fabiankaegy — CHANGES_REQUESTED** [review]
I don't believe we should use images hosted by the Make WordPress Slack in the documentation. All the images should be hosted on .org or the GitHub repo here. 

Looking at where the image was changed the full github URL was used: https://github.com/WordPress/gutenberg/pull/49643/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938L5

**Comment by mburridge** [comment]
Oops sorry, that was a mistake - I thought I had the URL in my clipboard but clearly I'd over-written it.

**Comment by mburridge** [comment]
Fixed now

**Review by fabiankaegy — APPROVED** [review]
Looks great 👍

**Review by juanmaguitar — APPROVED** [review]

**Pull request merged**
