### PR TITLE
RichText: remove native props for web

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

These props are eventually passed down to the container element, which causes a bunch or error to be logged. They should only be passed down in native context.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
This removes the errors but there should be a better way to do it.

**Comment by stokesman** [comment]
This seems to have busted the class name for at least the button block (I reverted dec37e19 to check and my buttons were styled/classed again). I'm glad to see the console clean again though 👍

**Comment by ellatrix** [comment]
@stokesman What do you mean by busted?

**Comment by ellatrix** [comment]
I still see classes rendered for buttons

**Comment by stokesman** [comment]
@ellatrix, I should have said it's in the editor, the frontend is fine.
The outer element of the block seems fine, the inner one only has the `rich-text` class.
image

After reverting 363df9f, the classes `block-editor-rich-text__editable` and  `wp-block-button__link` are present
image

**Comment by stokesman** [comment]
I'm sorry about the bother. The issue resolved when I restarted `npm run dev` and it's something I'll be sure to try in the future.

**Comment by ellatrix** [comment]
No problem!

**Pull request merged**
