### PR TITLE
Improve the block drop-zone indicator timing and behavior

### PR DESCRIPTION
**Pull request by youknowriad**
## What?

I've noticed that when dragging blocks around, sometimes the insertion point animation triggers multiple times for a given position. This PR tries to improve that.

## How?

This PR does two things:

 - Switches from dragOver to dragStart to show the indicator. dragStart runs only once while dragOver runs constantly which is a potential performance issue (that's why it was throttled I guess).
 - Makes sure the insertion point is not hidden on dragLeave if we "entered" another block (if dragOver has just been called).

## Testing Instructions

I need some help testing and validating this properly (compared to trunk).

 - Try dragging blocks around and pay attention to the behavior of the insertion point (the blue line appearing and disappearing)
 - Try also dragging blocks from the inserter.

### CODE REVIEW

**Comment by ellatrix** [comment]
Hm, I'm dragging blocks around, but I don't see any indicator anymore.

**Comment by ellatrix** [comment]
drag-indicator-gone

**Comment by youknowriad** [comment]
@ellatrix you're right, I was testing in Safari, maybe the order of events or something like that is different in Chrome. I'll have to check more tomorrow.

**Comment by talldan** [comment]
> I've noticed that when dragging blocks around, sometimes the insertion point animation triggers multiple times for a given position. This PR tries to improve that.

I'm not sure if we're talking about the same thing, but I've also noticed similar. I think there's one issue when hovering around the space vacated by the dragged block. I think this is because how the dragged block appears changed - it used to completely disappear, but now it's 'greyed out' when dragged.

I started working on something to fix this a few weeks back, but never pushed the branch. Here it is now though - https://github.com/WordPress/gutenberg/pull/44285. Feel free to borrow parts of it, or push directly to it.

**Comment by jasmussen** [comment]
I'm seeing some not too responsive behavior in Chrome. But thank you for testing in Safari, and thanks for focusing on this!

dragondrop

**Comment by youknowriad** [comment]
Closing this in favor of #44285 (not ready yet though)

**Pull request closed without merging**
