### PR TITLE
Fix some documentation links - links to md files require the `.md` extension

### PR DESCRIPTION
**Pull request by adamsilverstein**
* Fix navigating from https://github.com/WordPress/gutenberg/blob/master/docs/extensibility.md

### CODE REVIEW

**Comment by gziolo** [comment]
It’s more tricky change, because at the same time it will break links in [Gutenberg handbook](https://wordpress.org/gutenberg/handbook/extensibility/) 🙁

That’s way all markdown files in docs folder are handbook first, in effect all urls are relative to navigation to .org website.

There are two ways we could fix it I csn think of:
- We put every single doc inside its own subfolder and name the file README.md.
- Or better, we update handbook to be more flexible and strip .md when generating relative urls.
By the way, A similar issue exists when you provide code that uses ES5 and ES.next. It looks properly only in Gutenberg handbook.

**Comment by adamsilverstein** [comment]
> It’s more tricky change, because at the same time it will break links in Gutenberg handbook 🙁

@gziolo thanks for clarifying that, makes sense. yea - I was trying to navigate the md files directly on github which might not be uncommon so it would be nice if it could work.

How frequently is the handbook synced? I tend to use github to see the latest docs and can try to switch to handbook if they are kept in sync.

**Comment by gziolo** [comment]
> How frequently is the handbook synced? I tend to use github to see the latest docs and can try to switch to handbook if they are kept in sync.

I think every 15 minutes. Gary knows best 😃

**Review by pento — APPROVED** [review]
🕺🏻

https://meta.trac.wordpress.org/changeset/7104

**Comment by gziolo** [comment]
This is cool, thanks! We should update other links and move some of the doc files to subfolders to reflect handbook's URL structure. 💯

**Pull request merged**
