### PR TITLE
Inherit color in meta boxes

### PR DESCRIPTION
**Pull request by danielFangstrom**
## Description
Gutenberg overwrites text color in meta boxes, and this fix makes sure that the color is inherited from the parent element instead.

## How Has This Been Tested?
Confirmed that the text color in the meta boxes has changed and that the color in other parts remain the same.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by aduth** [comment]
Related: #5561

**Review by aduth — APPROVED** [review]
Code-wise 👍

**Comment by jasmussen** [comment]
As far as design feedback goes, there are two paths forward for metaboxes. In one path, we do our very best to make PHP metaboxes look like a native, integrated part of Gutenberg. In areas, like text color and metabox styling, perhaps we go slightly too far in overriding, to make things look right.

The other path goes in the opposite direction, where we override as little as possible, and potentially let PHP metaboxes look less integrated into Gutenberg. 

I don't have a strong opinion either way, but this PR definitely goes in the latter direction. If that solves issues, then 👍 👍 from me.

**Review by jasmussen — APPROVED** [review]
Let's keep things moving. If we find this was a negative change we can always revisit.

**Pull request merged**
