### PR TITLE
Post Content: Display attachments

### LINKED ISSUE #29887: FSE - post-content is empty when used in attachment template
## Description

When using the `<!-- wp:post-content /-->` block in the attachment.html template, the post content - in this case the media/image - is rendered empty on frontend.

## Step-by-step reproduction instructions

In a FSE theme, create an attachment.html template containing the following blocks;
```
<!-- wp:post-title /-->
<!-- wp:post-author /-->
<!-- wp:post-date /-->
<!-- wp:post-content /-->
```

## Expected behaviour

The `<!-- wp:post-content /-->` block should render the single media attachment.

## Actual behaviour

The `<!-- wp:post-content /-->` block is empty.

The same block placed in the single.html template does display the single media attachment correctly, but not in the attachment.html template.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.1.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Various FSE themes, all same result.

## Device information
- Device: Desktop
- Operating system: W10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Display attachment information on the front using the post content block.
Fixes https://github.com/WordPress/gutenberg/issues/29887

## How has this been tested?

1. Activate a full site editing theme
2. Upload different types of attachments like a txt file and an image.
3. Add a caption to the image in the media library.
4. From the media library, view the attachment pages.
5. Confirm that attachments displays correctly.
6. Confirm that regular post content still display correctly.

For image attachments, the image, caption, and a link to the full size image should display.
For other formats, a link to the file should display.

 ❓  The full size image link may be too opinionated.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Sandstromer** [comment]
~~This works when the media is unattached, but when attached (Uploaded to) a post/page nothing is displayed.~~

Sorry I was wrong, it is whether the attachment has a 'Description' that determines if it is displayed or not.

For example an uploaded image with an empty 'Description' field displays nothing.

**Comment by Sandstromer** [comment]
Looks like returning nothing too early `if ( empty( $content ) )`

A media attachment will have empty content if there is no 'Description' as this is saved as the `post_content`

**Comment by carolinan** [comment]
I have not been able to fully solve this. Even when the early return is solved, there are other issues.

When I tried to display the attachment in attachment.html using `is_attachment()`, the attachment was duplicated on the single view. This is because the attachment page **is** a single view and `is_attachment` and` is_singular` will both be true.

Attachments are displayed in the singular view with the help of https://developer.wordpress.org/reference/functions/prepend_attachment/
but this returns early on attachment pages.

Displaying the attachment separately and then removing the prepend_attachment filter for the content works, but it doesn't feel like good practice.

**Comment by Sandstromer** [comment]
Would it work to first check if an attachement then do the attachment stuff, then else if not an attachment check if empty and if not empty then do the content stuff for non-attachments.

```
function gutenberg_render_block_core_post_content( $attributes, $content, $block ) {
	if ( ! isset( $block->context['postId'] ) ) {
		return '';
	}

	if ( ! in_the_loop() ) {
		the_post();
	}

	$content = get_the_content( null, false, $block->context['postId'] );

	$wrapper_attributes = get_block_wrapper_attributes( array( 'class' => 'entry-content' ) );

	if ( is_attachment() ) {
		if ( wp_attachment_is_image( $block->context['postId'] ) ) {
			$content = '<figure class="wp-block-image size-large">' .
			wp_get_attachment_image( $block->context['postId'], 'large' );
			if ( wp_get_attachment_caption( $block->context['postId'] ) ) {
				$content .= '<figcaption>' . wp_get_attachment_caption( $block->context['postId'] ) . '</figcaption>';
			}
			$content .= '</figure>';
			// Retrieve image attachment metadata.
			$metadata = wp_get_attachment_metadata( $block->context['postId'] );
			if ( $metadata ) {
				$content .= sprintf(
					'<div class="wp-block-attachment-details full-size-link"><span class="screen-reader-text">%1$s </span><a href="%2$s">%3$s &times; %4$s</a></div>',
					esc_html_x( 'Full size', 'Used before full size attachment link.' ),
					esc_url( wp_get_attachment_url( $block->context['postId'] ) ),
					absint( $metadata['width'] ),
					absint( $metadata['height'] )
				);
			}
		} else {
			$content = sprintf(
				'<div class="wp-block-attachment-details"><a href="%1$s">%2$s</a></div>',
				esc_url( wp_get_attachment_url( $block->context['postId'] ) ),
				get_the_title( $block->context['postId'] )
			);
		}
	} else {
		if ( empty( $content ) ) {
			return '';
		}
		else {
			$content = apply_filters( 'the_content', str_replace( ']]>', ']]&gt;', $content ) );
		}
	}

	return (
		'<div ' . $wrapper_attributes . '>' . $content . '</div>'
	);
}
```

**Comment by carolinan** [comment]
> Would it work to first check if an attachement then do the attachment stuff, then else if not an attachment check if empty and if not empty then do the content stuff for non-attachments.

In this scenario, the description wont show on the attachment pages.
The description is the content. Displaying the content duplicates the attachment,

**Pull request closed without merging**
