### PR TITLE
Fix color focus styles

### PR DESCRIPTION
**Pull request by truchot**
Fix low contrast color when button or input are focus as mentioned in [#15432](https://github.com/WordPress/gutenberg/issues/15432) & [#15325](https://github.com/WordPress/gutenberg/issues/15325) 
I choose `$blue-medium-focus` color for more consistency

## Screenshots
localhost_8888_wp-admin_post php_post=1 action=edit (2)

localhost_8888_wp-admin_post php_post=1 action=edit (3)

### CODE REVIEW

**Comment by truchot** [comment]
It's my first PR so I am interested in your feedbacks :)

**Comment by youknowriad** [comment]
Thanks for the PR @truchot  Is there something wrong with the PR, why all these commits are showing up :)?

**Comment by truchot** [comment]
I may have forgotten something in the process before proposing my PR but I don't know what…
Only the 4 last commits are relevant.

**Comment by aduth** [comment]
@truchot I would suggest one of the following actions:

- Use [interactive rebase (`git rebase -i upstream/master`)](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_reordering_commits) to remove the commits unrelated to your changes (by removing or commenting the lines in the interactive prompt), followed by a force push (`git push -f origin fix/button-focus-styles`)
- Create a new, separate branch and [cherry-pick (`git cherry-pick`)](https://git-scm.com/docs/git-cherry-pick) only the commits relevant to your changes. This will require a new pull request.

**Comment by truchot** [comment]
Maybe this PR can be closed :) 
I open the new here : #15544

**Comment by truchot** [comment]
Thanks @aduth for these tips

**Pull request closed without merging**
