### PR TITLE
WIP: lower specificity to max width on post template

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

When we lowered specificity to the alignment CSS they started following behind other block rules that affect the same properties. In this case the max-width of the post content block styles is more specific than the new layout rules in some cases (in my testing, this shows up on query blocks that have layout inherit and a tagName attribute).

I'm not sure if the correct fix is to lower specificity to the offending CSS or raising it up to the layout styles and then fixing it a different way for alignleft and right. I'm going to keep tinkering but I leave this here for others to chime in.

## Testing Instructions

 To test this, use this block markup on empty theme, use it as index.html:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:query {"queryId":1,"query":{"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","sticky":"","perPage":3},"tagName":"main","displayLayout":{"inherit":true},"layout":{"inherit":true}} -->
<main class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-title {"isLink":true} /-->

<!-- wp:post-excerpt /-->
<!-- /wp:post-template --></main>
<!-- /wp:query -->
```

The post content shows as 100% width without the fix. 

## Screenshots 

Before:

Screenshot 2022-02-23 at 11 25 21
Screenshot 2022-02-23 at 11 25 36

After:
Screenshot 2022-02-23 at 11 27 04

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I have an alternative solution to this one over at https://github.com/WordPress/gutenberg/pull/39016 and I don't know which one is preferred, please any input is welcome.

**Comment by MaggieCabrera** [comment]
Looking at this closely it seems like we could preserve the current selectors if we could change the loading order of the styles. The post-content styles are loading before the layout ones and that's part of why this bug is happening. I'm not sure how to change that order or even if that should be done. In case that's not an option, I think this fix is the best way to go about this bug.

**Comment by scruffian** [comment]
@jorgefilipecosta this bug was introduced by this change: https://github.com/WordPress/wordpress-develop/commit/43a8631882b552dba95bb8b59ab06c1dc49160dd

It seems to me that we should try to preserve the change from that commit, which means we probably need to look at a fix like the one @MaggieCabrera suggests.

**Comment by jffng** [comment]
I prefer this PR to https://github.com/WordPress/gutenberg/pull/39016, mainly because of having to add the `!important` margin rules to the float classes there.

**Comment by jasmussen** [comment]
I still haven't fully understood what the problem is. I have a feeling it has to do with the layout engine not being aware of the wrapping tag that you can select under "Advanced", and so if we land any fixes in the mean time it'd be important to not forget that, if the root cause is actually different. 

I tried recreating the issue in [a codepen](https://codepen.io/joen/pen/bGYKjqP), and of course that clarifies that the 100% max width is meant for the _container_, while the `content` max-width is meant for direct descendants of the container. And so the fact that the former is applied to the latter suggests the container width is applied twice — and it shouldn't, should it?

If it should, it'd still be good to replicate this rather nuanced issue in a simpler codepen so we can have some confidence in the fix and cause.

**Comment by MaggieCabrera** [comment]
This is the best I could manage with codepen: https://codepen.io/onemaggie/pen/VwrBKqw

If you swap the order of the selectors, it works for both cases.

I'm using this markup on emptytheme to highlight how the case with the extra tag has the issue but without it hasn't:

```
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:query {"queryId":1,"query":{"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","sticky":"","perPage":3},"tagName":"main","displayLayout":{"inherit":true},"layout":{"inherit":true}} -->
<main class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-title {"isLink":true} /-->

<!-- wp:post-excerpt /-->
<!-- /wp:post-template --></main>
<!-- /wp:query -->


<!-- wp:query {"layout":{"inherit":true},"queryId":1,"query":{"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"desc","orderBy":"date","author":"","search":"","sticky":""}} -->
<!-- wp:post-template -->
<!-- wp:post-title {"isLink":true} /-->

<!-- wp:post-excerpt /-->
<!-- /wp:post-template -->
<!-- /wp:query -->
```

**Comment by jasmussen** [comment]
That's an excellent codepen, thank you. From just that codepen alone, my question is: should the `wp-block-post-template` class not move to the outermost wrapping container when this extra element is added?

**Comment by MaggieCabrera** [comment]
> That's an excellent codepen, thank you. From just that codepen alone, my question is: should the `wp-block-post-template` class not move to the outermost wrapping container when this extra element is added?

Either that or the "container" class move to the inner element, yes

**Comment by jasmussen** [comment]
Right, that seems to be the issue. Do you have any sense of whether it would be possible to fix this (move the classes) at all?

**Comment by MaggieCabrera** [comment]
> Right, that seems to be the issue. Do you have any sense of whether it would be possible to fix this (move the classes) at all?

No idea, I'm going to investigate!

**Comment by MaggieCabrera** [comment]
I found another way to trigger this bug while testing Skatepark: https://skateparkdemo.wordpress.com/?s=a

If you have a group block with inherit layout and a query loop inside, the same problem with the order of the styles affects the max width of the post content blocks. This only happens in the frontend:


Screenshot 2022-03-01 at 13 04 08

Screenshot 2022-03-01 at 13 04 17

**Comment by jasmussen** [comment]
Indeed, that's a good testable example. To summarize for my own sake, what it boils down to is that the `max-width` attached to `wp-block-post-template` seems to suggest that it should be a _container of child blocks_, not a _child block itself_. Which indicates there are two paths forward:

1. We decide that containers _can_ be children, and either fix the loading order issue, or lower the specificity of the rule (as this PR does) so the child-block rule wins the fight consistently.
2. We decide that it's a bug that such a container class is present on a block meant to be a child of a layout container. Then we have to move that class, or attach the max-width in a different way.

Does that sound about right? If yes, then if we could decide on 1 or 2, it could probably unblock this PR.

**Comment by scruffian** [comment]
I think has to be 1 unless we build a lot of extra things to stop child blocks from also enabling the default layout, which would in turn break a lot of themes.

**Comment by youknowriad** [comment]
Isn't the loading order the same issue as the one raised here? https://github.com/WordPress/gutenberg/pull/38750#issuecomment-1056837132 (so a regression of that PR)

**Comment by jasmussen** [comment]
Is this PR relevant here? https://github.com/WordPress/gutenberg/pull/39164

**Comment by ndiego** [comment]
@jasmussen yes 100%. That PR fixes this issue. Thanks for connecting the dots!

There is a regression in https://github.com/WordPress/gutenberg/pull/38750 and the block support styles are added too early and get overwritten in many situations.

**Comment by MaggieCabrera** [comment]
Yes, the problem is fixed, thank you all for helping investigate the issue!

**Pull request closed without merging**
