### PR TITLE
Update "Local by Flywheel" name and URL.

### PR DESCRIPTION
**Pull request by bdurette**
## Description

"Local by Flywheel" has been rebranded to simply "Local" and the canonical URL for the software is now https://localwp.com. This change updates the documentation to reflect the branding change.

## How has this been tested?
Markdown has been rendered by GitHub in the Preview. Updated URL links were clicked to ensure they are correct.

## Screenshots
N/A

## Types of changes
Documentation change only.

## Checklist:
- [X] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by mkaz — APPROVED** [review]
These changes look good and consistent.
Thanks for keeping the docs up to date. 👍

**Comment by bdurette** [comment]
I'm not sure why the checks were failing. Looks like they've been restarted. Are the checks known to be flaky?

**Comment by bdurette** [comment]
Also, there's an alternative version of this PR that uses the [Git branch naming](https://developer.wordpress.org/block-editor/contributors/code/git-workflow/#branch-naming) conventions. This branch `patch-1` was created by editing directly from the website/GitHub.

**Comment by mkaz** [comment]
@bdurette Branch name doesn't really matter since it all gets merged, not really consequential.
Congrats on your first contribution and thank you!

**Pull request merged**
