### PR TITLE
Validation: Log debugging messages for invalid blocks

### LINKED ISSUE #2837: Validation: Improve developer messaging for invalid blocks
Related: #2210, #2056, #1929

Prior to #2210, when a block was marked as invalid, a console message was logged explaining the difference between the expected and actual content. With the move to creating a formal tokenizing validator in #2210, this was temporarily dropped with the intention of being brought back. Alas, this has not yet been reimplemented, thus the creation of this issue.

__Task:__ Potentially using the [previous logging](https://github.com/WordPress/gutenberg/pull/1929/files#diff-ab72d6ac23a7ac667ec20c403859138dR128) or [an explored diff display](https://github.com/WordPress/gutenberg/pull/2056/files#diff-ab72d6ac23a7ac667ec20c403859138dR139) as inspiration, add messaging when block validation fails. This can probably be added [directly into `isValidBlock`](https://github.com/WordPress/gutenberg/blob/db507cdcb61a460c2669b6b32be2ff779fb514bf/blocks/api/validation.js#L370-L391) with a condition on the current environment.

__Workaround:__ You can [add a breakpoint](https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints) on each of the failing checks to see where validation is bailing:

- https://github.com/WordPress/gutenberg/blob/db507cd/blocks/api/validation.js#L345
- https://github.com/WordPress/gutenberg/blob/db507cd/blocks/api/validation.js#L350
- https://github.com/WordPress/gutenberg/blob/db507cd/blocks/api/validation.js#L357
- https://github.com/WordPress/gutenberg/blob/db507cd/blocks/api/validation.js#L364

In each case, the comments above should explain the reason for failure.

### PR DESCRIPTION
**Pull request by aduth**
Closes #2837

This pull request seeks to add logging to the block validator to emit messages when an invalid block is encountered in a development environment.

Validation

__Testing instructions:__

Modify `post-content.js`, removing, adding, or changing attributes or content which would cause a block to become invalid (i.e. serialize differently on the next load). 

Load the editor and verify that debugging messages are logged in your Developer Tools console.

### CODE REVIEW

**Comment by aduth** [comment]
I enabled logging for all environs which, with [global test console assertions](https://github.com/WordPress/gutenberg/blob/2d50d76c8477199299e4af66c27edc26662b5872/test/unit/setup-test-framework.js#L13-L25), helped identify many legitimate issues both in parser testing, and in the block fixtures. Those have been fixed here. All-environment logging should be helpful for plugin usage to report issues to the original block implementer.

**Comment by ahmadawais** [comment]
@aduth where can I read more about the validation API? 
I figure it must be this file https://github.com/WordPress/gutenberg/blob/db507cd/blocks/api/validation.js

One of the demo tweet blocks I had built it now renders corrupted.
image

With this log message 

image

Whereas I have myself changed the href in `save:` part of `wp.blocks.registerBlockType` API.
E.g. 


Code present [here](https://github.com/ahmadawais/Gutenberg-Boilerplate/blob/master/block/04-tweet/block.js).

Looking forward!

**Comment by aduth** [comment]
@ahmadawais Validation works by comparing what would be saved when running `save` against what is actually saved in post content, considering whether the two markups are "equivalent". In your example, it's finding that the `href` value is not as expected. Based on the fact that `href` is assigned using the tweet content, the `content` attribute is not being parsed correctly when loading from an existing post.

Looking at the code example, I see you're expecting to find a `children` source in a paragraph tag. But you're not saving a paragraph tag from your block; you're saving an `a` (anchor) tag. Changing the selector _might_ be enough, but I also think you could run into issues as `children` value can't easily be passed to `encodeURIComponent` since it's not a string. In fact, it is a React element, so you _could_ pass it to `wp.element.renderToString`, but ideally not since the fact that it's represented as a React element is an implementation detail and is subject to change (see also #3048).

This is an interesting use-case, since you want access to a string representation of the rich text content to be able to encode in a tweet URL. I might imagine depending on the direction we go with #3048 that we'd want some way to convert from a children value to a string (cc @iseulde, @gziolo).

**Comment by ahmadawais** [comment]
@aduth just returning back from vacations and was out of all the Gutenberg dev but want to know if there has been any development in this particular aspect? Any pointers that you have for me to go and read about. As I am sure there's a possibility of having different edit and save interfaces since the saved interface should be clickable whereas `edit` interface should not.

Looking forward!

**Comment by aduth** [comment]
@ahmadawais Is there any reason the Tweetable text needs to be "rich text" in your case (i.e. supporting italics, bold, etc)? Thinking it might make more sense as plain text, in which case you could use a simple text input instead of `Editable`. The value could either be saved in the comment attributes, or sourced / converted from the saved anchor value. Thinking something like:

```js
content: {
	type: 'string',
	source: 'text',
	selector: 'a',
},
```

**Comment by ahmadawais** [comment]
@aduth No not at all. I was actually trying to make it work without any of that, didn't spend a lot of time on it, but didn't get around producing an editable text block that's not rich text. How does one do that?

Also, my guess is that validation won't apply on a case like this with simple text block? I just need the user to write the Tweet's content.

**Comment by aduth** [comment]
>but didn't get around producing an editable text block that's not rich text. How does one do that?

Instead of `Editable`, you could just use a plain `input` type. Similar to Editable, it should behave as a simple controlled component:

https://reactjs.org/docs/forms.html#controlled-components

>Also, my guess is that validation won't apply on a case like this with simple text block?

Not entirely clear what you mean here, but with the plain text input value, it is easy enough to `encodeURIComponent` so I wouldn't expect a validation error to occur if the regenerated markup is equivalent.

**Comment by mtias** [comment]
@aduth @iseulde I've seen this conundrum with people a few times, where they want the display of editable (no borders, consistent font-size, etc) but don't care about rich text. What about adding a mode to Editable via prop to get plain text (would render just a textarea with not tinymce) instead of styling inputs?

**Comment by aduth** [comment]
>@aduth @iseulde I've seen this conundrum with people a few times, where they want the display of editable (no borders, consistent font-size, etc) but don't care about rich text. What about adding a mode to Editable via prop to get plain text (would render just a textarea with not tinymce) instead of styling inputs?

Another benefit to this is that if people are accustomed to working with Editable, they'd be inclined to use it for all text fields, and at least if we provide them the option to configure it for plain text, it would be fine enough to use.

The downside is that `value` of Editable would be overloaded to support both plain strings and the rich text value format.

**Comment by iseulde** [comment]
@mtias @aduth I'm a bit hesitant about this as the component attributes are so incredibly different. I think it makes sense to keep them separated, maybe we just need better naming than `Editable` (sounds general) and `TextareaAutosize`. How about just `RichText` and `PlainText`?

**Pull request merged**
