### PR TITLE
Correct getRedistributedColumnWidths and related tests

### LINKED ISSUE #27616: Negative values in column's width redistribution
**Describe the bug**

During the sanity testing before mobile release @chipsnyder noticed that we are able to get negative percentages in `Columns` and mentioned about it in the [comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2874#issuecomment-741859770). Since the logic for width redistribution is shared the same occurs on web editor. 

**To reproduce**
1. Create a new Blog Post
2. Add A Columns block
3. Select 70/30
4. Change column 1 to 90%
5. Set Column 2 to 10% (or around there)
6. Add a third column

Result: 
With those numbers I got: 73.34%, -6.66% and 33.33%.

columns_web_negative

_The same will happen when adding new column to the following columns: `90/5/5` and many other._

The problem is the wrong math within the function called `getRedistributedColumnWidths` located in [columns utils](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/utils.js#L86-#L98). 

```
export function getRedistributedColumnWidths(
	blocks,
	availableWidth,
	totalBlockCount = blocks.length
) {
	const totalWidth = getTotalColumnsWidth( blocks, totalBlockCount );
	const difference = availableWidth - totalWidth;
	const adjustment = difference / blocks.length;

	return mapValues( getColumnWidths( blocks, totalBlockCount ), ( width ) =>
		toWidthPrecision( width + adjustment )
	);
```

Mentioned method is assuming that **difference** _(difference between available width and new columns width sum)_ is divided equally between columns and subtracted from each of them. As a result we can get negative values, since **adjustment** has higher value than width. 

Let's consider it on the example from reproduction steps:

* Two columns: 90% and 10%
* New column will have width equal 33% _(100 / 3)_
* `availableWidth` refers to the sum of first two columns after adding the third one: 66.67 (100 - 33)
* `total width` refer to the sum of all columns: 100
* `difference` is -33.33 (_66.67 - 100)_
* `adjustment` is -16.665 _(-33.33 / 2)_

Finally we have
* first column: 90 - 16.665
* second column: **10 - 16.665**
* third column: 33.33

**Possible problem solution**

Imo the mechanism should be a bit different and width should be calculated proportionally to the **totalWidth**:

```
export function getRedistributedColumnWidths(
	blocks,
	availableWidth,
	totalBlockCount = blocks.length
) {
	const totalWidth = getTotalColumnsWidth( blocks, totalBlockCount );

	return mapValues( getColumnWidths( blocks, totalBlockCount ), ( width ) => {
		const newWidth = ( availableWidth * width ) / totalWidth;
		return toWidthPrecision( newWidth );
	} );
}
```

As a result we get positive values, divided proportionally:

* first column: 60
* second column: **6.67**
* third column: 33.33

**Expected behavior**

Columns shouldn't have negative width values

**Screenshots**

Attached above.

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"]
- If the Gutenberg plugin is installed, which version is it? [e.g., 7.6]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

### PR DESCRIPTION
**Pull request by lukewalczak**
## Description

Fixes: https://github.com/WordPress/gutenberg/issues/27616

PR introduces the fix for `getRedistributedColumnWidths` function which was returning negative values when adding new columns. More context about the problem is described within the attached issue.

## How has this been tested?

* Unit tests to cover edge cases

To test manually in the editor follow the steps:

1. Create a new Blog Post
2. Add A Columns block
3. Select 70/30
4, Change column 1 to 90%
5. Set Column 2 to 10% (or around there)
6. Add a third column

**Expect only positive values**

## Types of changes

* Bug fix

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
One thing we need to verify is whether those wrongly computed values in saved content would invalidate block when loaded again with the fix 😅

**Comment by lukewalczak** [comment]
> One thing we need to verify is whether those wrongly computed values in saved content would invalidate block when loaded again with the fix 😅

How I can invalidate columns with wrongly computed values?

**Comment by gziolo** [comment]
Using the `master` branch recreate the bug as described in the parent issue or copy this HTML:

```html
<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":73.34} -->
<div class="wp-block-column" style="flex-basis:73.34%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":-6.66} -->
<div class="wp-block-column" style="flex-basis:-6.66%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":33.33} -->
<div class="wp-block-column" style="flex-basis:33.33%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

Save the post, switch to this branch and you can observe it works without validation issues.

The only remaining question is whether we should migrate old content to use the new approach for column width. It would only impact those posts that were modified so it might have surprising side effects.

**Comment by gziolo** [comment]
I think there is at least one more unrelated bug I discovered while testing ...

First, when I change the column width from 70% to 90%, shouldn't the 2nd column update to 10% automatically? 90 + 30 is more than 100 😄 

The other issue is very subtle as it is auto-fixed by the deprecation logic. When I add the 3rd column then the column width is saved as the number while it should be the value in percentage.

**Review by gziolo — APPROVED** [review]

**Comment by lukewalczak** [comment]
> The only remaining question is whether we should migrate old content to use the new approach for column width. It would only impact those posts that were modified and it still might have surprising side effects as people were probably happy about the old distribution.

I think there is no need for that, method `getRedistributedColumnWidths` is called when new column is added or the existing one is removed and all the columns have _explicit widths_

> First, when I change the column width from 70% to 90%, shouldn't the 2nd column update to 10% automatically? 90 + 30 is more than 100 😄

That's the issue which I was raising some time ago and it turned out that sum of the columns can be higher than 100

Do you think we can merge it?

**Comment by gziolo** [comment]
Sure we can :)

**Pull request merged**
