### PR TITLE
Pages data view: Make 'View' button open a new tab

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Update the 'View' button to open a new tab.

## Why?
1. The icon suggests this behavior.
2. The action is different to others in that it takes you to the frontend rather than performing an administrative task.

## Testing Instructions
1. Open the Pages data view
2. Click the 'View' button
3. See the page in a new tab.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

This change was previously discussed and closed in #56737 😄 I prefer this change, but would like to hear from others if this change makes sense once again now.

**Comment by jasmussen** [comment]
As noted, I'd support either direction forward, and favor consistency here!

**Comment by jameskoster** [comment]
Hah, I forgot about that conversation :) My opinion hasn't really changed – if we're going to use this icon then it feels more intuitive (to me) that the link opens in a new tab.

**Comment by t-hamano** [comment]
I think it's OK to merge this PR, but is there any consistency that will be lost with this change or anything we should change in a follow-up?

**Comment by jameskoster** [comment]
The main inconsistency would be the behavior of this button, and the 'View' link in wp-admin post type lists. They're equivalent buttons, but the latter does _not_ open a new tab.

**Review by t-hamano — APPROVED** [review]
I think this change makes sense given the context _within_ the Site Editor and Block Editor. Perhaps in the future, if post type lists become React-based, opening in a new tab will become the default. I approve this PR, but if @jasmussen  has any concerns, please let us know.

**Comment by youknowriad** [comment]
Given that RC1 is today, I'm removing this from 6.5 as non essential.

**Comment by jameskoster** [comment]
Since this will now be a 6.6 thing let's merge and see how it goes. It's a small change that's easily reverted if needed.

**Pull request merged**
