### PR TITLE
Fix pattern block recursion handling

### PR DESCRIPTION
**Pull request by talldan**
Thanks to @ramonjd for catching this - https://github.com/WordPress/gutenberg/pull/60451#issuecomment-2036131501.

## What?
The pattern block's recursion handling is broken in 6.5. While the block won't render infinite children, there are several effects in the block edit that operate on inner blocks, and will run infinitely (or until max depth exceeded) causing an error.

## Why?
These effects are run before the `hasAlreadyRendered` short circuit happens in the block edit function, so there's no protection.

## How?
The fix creates a new wrapper around the previous block edit with the recursion provider logic. This seems this easiest way to fix while still satisfying React's rule of hooks (ugh).

## Testing Instructions
1. Create a pattern, save it and insert it in a post
2. Click 'Edit original'
3. Insert the same pattern again inside itself

In trunk: the editor hangs or the block throws an error
In this PR: a warning shows 'Block cannot be rendered inside itself'

## Screenshots or screencast 
Screenshot 2024-04-04 at 12 36 41 pm

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Wow, thanks for the quick fix. 

Before on trunk, inserting a pattern, for example, inside itself would crash my browser.

This branch displays the expected warning and everything is responsive:


https://github.com/WordPress/gutenberg/assets/6458278/edb0e3ef-ce2b-4ddf-82e1-edbd8fc3da9a

**Review by andrewserong — APPROVED** [review]
+1 thanks for the quick follow-up! Testing nicely for me, too:

image

👍

**Comment by talldan** [comment]
Thanks for the quick reviews!

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the add/fixes-for-651 branch to get it included in the next release: 6a417eb2c1

**Pull request merged**
