### PR TITLE
Revert: Show empty paragraphs on fronted.

### LINKED ISSUE #10051: Suggestion: Make empty paragraph blocks behave consistently on the front and backend
## General Idea:

Let's establish consistency around the way that new, empty paragraphs render in Gutenberg and on the front end. 

- We could do this by adopting the Classic Editor's method of rendering empty paragraphs as `<p>&nbsp;</p>` on the front end. 
- To complete the effect, we'd likely want to adjust our empty paragraph placeholders so that they only appear on hover and select. 

## Details:

Currently, Gutenberg and WP-Admin treat empty paragraphs differently:

image

image

To me, the classic editor approach is closer to what I’d expect: what I typed in the editor is more or less rendered in the front end. 

Here's the technical reason for that difference: Gutenberg renders all those empty blocks as `<p></p>` and they get collapsed in the front end because they’re empty. By contrast, the classic editor renders all those empty paragraph lines as `<p>&nbsp;</p>`. Adding `&nbsp;` in there may seem a little weird — but for a user who doesn’t care about code, it just ensures that an empty paragraph behaves as expected. This functionality is similar to what you see in any other word processor: you hit return a few times, and you get an extra empty line. I tend to like this approach, and I suggest we consider adopting it. 

(Yes, we have a — very useful! — spacer block to add extra space, but that doesn't make a lot of sense if you're in a writing mindset: If you're typing, and you want to add extra empty line, the return is key by far the easiest way to add that.)

---

If we did adopt this, we'd likely want to make a little update to our placeholders too. If empty paragraphs rendered as blank new lines in the front end, they should appear as blank new lines in the backend too. 

To accomplish that, one solution would be to switch to showing the placeholder text only on hover and select:

show-on-hover-select

_(The "show placeholder until you start typing" behavior is similar to the way slack handles their placeholders.)_

This would help us eliminate the very repetitive placeholder effect you currently see when you hit return many times in a row (#2466):

screen shot 2018-09-19 at 1 46 17 pm

---

We've been having great progress in https://github.com/WordPress/gutenberg/pull/9314 around changing that placeholder copy slightly (and also, replacing the default "Write your story" copy at the top of posts with the new version). If the ideas in here make sense for us, I could see this change landing nicely alongside that update.

Looking forward to hearing others' thoughts.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

This PR is a followup to feedback in https://github.com/WordPress/gutenberg/pull/27995#issuecomment-797029996 and https://core.trac.wordpress.org/ticket/52764.

In 27995 we merged a change where an empty paragraph written in the editor, would correspond to en empty paragraph on the frontend. This fixed #10051.

However shortcodes when they get parsed commonly generate lots of empty paragraphs (`<p></p>`), which causes layout issues when those get inflated.

This PR reverts the change.

Editor/frontend before:

| before-editor  | before-frontend  |
|---|---|

Editor/frontend after:

| Screenshot 2021-03-12 at 08 41 17 | Screenshot 2021-03-12 at 08 41 21 |
|---|---|

## How has this been tested?

Insert text, then a slew of linebreaks, then text again, and compare editor with frontend. 

Observe that before, editor and frontend would match perfectly. Observe that after this PR, the paragraphs on the frontend collapse to zero height.

## Types of changes

It's unfortunate that we might not be able to get accurate behavior here. But it is potentially something that could be revisited in the future.

Let me know your thoughts!

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aristath — APPROVED** [review]
I don't like it, but reverting this change does fix the regression with shortcodes.
Thank you for the quick fix!

**Comment by jasmussen** [comment]
Thank you Ari. I'd appreciate thoughts from Kjell or Ben before we merge this one. Just in case there's a solution other than a revert that I'm not seeing.

**Comment by carolinan** [comment]
It is not only shortcodes that have been affected by this, extra p tags are sometimes added when blocks in full site editing themes are rendered on the front. Until those extra p tags have been solved, I think this revert is needed.
Related: https://github.com/WordPress/gutenberg/issues/26731

**Comment by scruffian** [comment]
I think @joyously made a good point:

> My opinion is that the browser has always condensed white space

I wasn't aware of this, but it is true in my testing. Reverting seems best for now.

**Review by scruffian — APPROVED** [review]

**Comment by jasmussen** [comment]
Thanks all. I'll merge when the checks pass and we can look at this again in the future.

**Comment by jasmussen** [comment]
I can't get the e2e tests to pass here. Any insights?

**Comment by mkaz** [comment]
@gwwar Fixed the tests, I rebased and merged for you :tada:

**Pull request merged**
