### PR TITLE
Split @wordpress/url into modules.

### PR DESCRIPTION
**Pull request by sgomes**
## Description
This PR splits `@wordpress/url` into individual modules, while re-exporting them in the index file. This helps with tree-shaking, by enabling clients that only make use of a few functions to drop the code for the remaining ones. This also means that a client that doesn't make use of any `qs`-dependent functions (like `addQueryArgs`) won't need to include that library.

As a bonus, inter-dependencies within the library also become more explicit.

## How has this been tested?
There are no significant changes to functionality, mostly only moving of code around. As such, the unit tests should be sufficient in ensuring that no errors were introduced.

## Types of changes
Non-breaking changes only, as `index` re-exports all the split-out functions.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I think this is a great compromise approach @sgomes. It provides a “default” approach which is broadly compatible, while allowing clients who don’t need those capabilities to use simpler implementations (since tree shaking will handle the business of cutting down the bundle size). Nice stuff!

**Comment by sgomes** [comment]
> I think this is a great compromise approach @sgomes. It provides a “default” approach which is broadly compatible, while allowing clients who don’t need those capabilities to use simpler implementations (since tree shaking will handle the business of cutting down the bundle size). Nice stuff!

Thank you for the kind words, @chrisvanpatten! 🙂

**Comment by sgomes** [comment]
Rebased on master, to see if E2E tests stop failing.

**Comment by aduth** [comment]
I suppose I should have read the entirety of the pull request text before going down a rabbit-hole to prove that the module is already tree-shakeable even without this refactor. 😄 Which is true, save for the one exception you point out, which is that only with this refactor can we avoid unnecessarily pulling in `qs` when not using the functions which make direct use of it.

(That being said, I still think it would have been a worthwhile refactor all the same)

**Review by aduth — APPROVED** [review]
Solid refactor 👍 

I might have liked to also see the test file split up, but it's not as important.

**Comment by sgomes** [comment]
Thanks for the review, @aduth! 👍

**Pull request merged**
