### PR TITLE
[RNMobile] Update color retrieval from settings to useEditorFeature

### PR DESCRIPTION
**Pull request by cameronvoell**
GB-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2648
## Description

Fixes mobile crash on `master` after default color settings were updated here: https://github.com/WordPress/gutenberg/pull/25419

## How has this been tested?

We should test flows using default colors/gradients

We also need to make sure that custom theme still work which are set here: https://github.com/WordPress/gutenberg/blob/5ced7f1ab18d6019da01f2cb812697ddde8837b7/packages/editor/src/components/provider/index.native.js#L127

## Screenshots 
Screenshot_20200921-134023_Gutenberg

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by enejb** [comment]
Should we also add the removed default colors and gradients to `block-editor/src/store/default.native.js` ?

**Review by chipsnyder — APPROVED** [review]
Ran through the regression steps for [editor theme](https://github.com/wordpress-mobile/test-cases/blob/master/test-suites/gutenberg/editor-theme.md)
- ✖️Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001) 
- ✖️Default Gradients - Check that default gradients still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- ✅ Custom Colors - Check that custom colors load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)
- ✅ Custom Gradients - Check that custom gradients load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
        - When changing a theme if the new theme downloads before the existing one then the editor needs to be reopened before it is reflected. This is to be a known [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2637).
- ✅ Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

Overall this looks good and removes the crash. I think we can handle the top two test cases in different PR so we unblock current development.

**Comment by chipsnyder** [comment]
>Should we also add the removed default colors and gradients to block-editor/src/store/default.native.js ?

This is a good idea @cameronvoell I'll leave it up to you if you want to do that now or if you think that's better for another PR

**Review by guarani — APPROVED** [review]
Tested and can confirm no crash anymore, had a quick play with colors on the Cover and Button blocks and could pick the gradient colors only, no built-in choices as we discussed offline 👍

**Pull request merged**
