### PR TITLE
Updates image size to match columns width

### PR DESCRIPTION
**Pull request by enriquesanchez**
Updates the images' size to match the column's width for better visual balance.

Before:
Screen Shot 2020-07-09 at 19 16 38

After:
Screen Shot 2020-07-09 at 19 16 25

### CODE REVIEW

**Review by ZebulanStanphill — CHANGES_REQUESTED** [review]
Using hardcoded image sizes only works when the content width is a certain size. This won't scale to other themes. The images shouldn't have any custom size set, which should make them auto-size to fill the columns regardless of theme.

**Comment by kjellr** [comment]
Yeah, I think @ZebulanStanphill is right here — let's try removing the custom width entirely.

**Comment by enriquesanchez** [comment]
Thank you for the feedback 🙏

I've removed the hardcoded image sizes:

Screen Shot 2020-07-10 at 13 17 39

**Review by mapk — APPROVED** [review]
The alignment looks great now. Thanks!

**Review by ZebulanStanphill — APPROVED** [review]

**Pull request merged**
