### PR TITLE
Fix Columns block pattern picker item margin.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Added equivalent vertical margin to the pattern selection list items of the Columns block.  Addresses Issue #19446.

Before this PR - Margin on the pattern selection list item was defined as `margin: 0 $grid-size 0 0;` giving us 8px of right side margin with none elsewhere.

With this PR - Margin for this item is now defined as `margin: $grid-size/2 $grid-size $grid-size/2 0;`.  While dividing the vertical margin evenly between top and bottom lets the items look more vertically balanced, we have left the horizontal margin all on the right of the item so that the items remain lined up with the Icon above and 'skip' link below.

Note - `$grid-size-small` currently has the same value as `$grid-size/2`, however I chose to keep the standard `$grid-size` variable in place because it better represents the full amount of margin on the list item.  That is, even though we are using `$grid-size/2` the item has a total of `$grid-size` margin on each axis.

## How has this been tested?

Tested on local docker setup with Columns block and nested Columns block.

## Screenshots 

**Before**
Screen Shot 2020-01-07 at 3 45 32 PM
Screen Shot 2020-01-08 at 7 36 30 PM

**After**
Screen Shot 2020-01-08 at 7 27 03 PM
Screen Shot 2020-01-08 at 7 26 58 PM

## Types of changes

Bug fix (non-breaking change which fixes an issue) / Simple style update.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by noahtallen** [comment]
Nice! I wonder if it ought to stay left-justified in order line up with the "skip" text and columns icon at the very top. Adding the vertical margin is nice! Does this have any adverse effects for bigger viewports?

**Comment by Addison-Stavlo** [comment]
> I wonder if it ought to stay left-justified in order line up with the "skip" text and columns icon at the very top.

Ah good catch.  Now that you point that out it seems to be bugging me that it doesn't line up with what is above and below. 😆  I have moved the horizontal margin to the right of the item, but decided to keep the vertical margin split evenly for now (it seems to look more balanced in the horizontal/wide version that way).

Screen Shot 2020-01-08 at 7 27 03 PM

> Does this have any adverse effects for bigger viewports?

Not that I can notice.  
Screen Shot 2020-01-08 at 7 26 58 PM

**Review by noahtallen — APPROVED** [review]
looks great!

**Comment by youknowriad** [comment]
Nice fix thanks. Can we get a quick sanity check cc @jasmussen as you worked on placeholders recently

**Comment by jasmussen** [comment]
Yep, this is great. You could use $grid-size-small instead of $grid-size/2, however I will in the not too distant future try and move all use of those variables towards something like https://make.wordpress.org/design/2019/10/31/proposal-a-consistent-spacing-system-for-wordpress/ so I'll revisit that bit anyway.

As a single PR, this is great, 👍 👍

I would love to, in the future and for anyone available to work on it, for the placeholder to work even better when this compact. This could be, for example, by adding overflow to the placeholder so the content is visibly but nicely cropped, and then expand the placeholder to float above the content when selected. But this is something to consider separately.

**Pull request merged**
