### PR TITLE
List Block: Implement block switcher API

### LINKED ISSUE #704: List Block: Support Switcher
The list block should support the switcher. 

CC: @EphoxJames because you've been involved with this

### PR DESCRIPTION
**Pull request by youknowriad**
closes #704 

Implements switching a list to text, heading or quote block.

### CODE REVIEW

**Comment by jasmussen** [comment]
Works great!

Are we sure we want Heading as a possible transformation here? I do realize this goes back to the discussion we had about converting text to a heading, and I'm okay not rehashing that —  but it feels a little extra weird here, where only the first list item is converted to a heading. 

I'm okay with either, we can always revisit later on if we find it weird, but I figured I'd ask the question.

**Comment by youknowriad** [comment]
> Are we sure we want Heading as a possible transformation here?

Your choice.

**Comment by jasmussen** [comment]
> Your choice.

💥

Let's remove it from the list for now. If you want to, you can convert to text first, then to heading. Thanks Riad!

**Comment by aduth** [comment]
Related: #689 (`concatChildren` proposed to be removed)

**Comment by youknowriad** [comment]
If anyone want to take a final look, I'll be merging this later.

**Comment by aduth** [comment]
Noting my reluctance to further build upon APIs we've identified as problematic, while also acknowledging that alternatives have yet to be fleshed out.

More at https://github.com/WordPress/gutenberg/pull/689#issuecomment-300798226, #771

**Pull request merged**
