### PR TITLE
core-data: use controls from data-controls in favor of the package-local ones

### PR DESCRIPTION
**Pull request by jsnajdr**
The generic `apiFetch`, `select` and `dispatch` controls are frequently duplicated in various stores. This patch fixes that for the `core-data` package.

**How to test:**
- check that both unit tests and e2e tests pass. As the `core-data` store is used at a lot of places, it's hard to point at any single feature.

**Note:**
I think the naming of the _select_ controls in the `data-controls` package is very unfortunate:
- `select` doesn't do the synchronous `select` (return whatever is in the store right now) that we all know from Redux or `withSelect` or `useSelect`, but does the promise-returning resolution based on `__experimentalResolveSelect`. This control should really be called `resolveSelect`.
- `__unstableSyncSelect` has an unwieldy name and should be called `select` or at least `syncSelect`. I don't see anything that should be unstable or experimental about this control. It's the most non-controversial and straightforward `select` I can think of 🙂 

@youknowriad @nerrad Is it possible to fix that naming, or are we stuck with it forever, for back-compat reasons?

It also seems to me that `__experimentalResolveSelect` should be graduated from the experimental state. It's being used in many async workflows that do several async requests sequentially and they depend on each other. Example: fetch info for `postType` and then use its `restBase` to fetch autosaves for it.

Another thing that would deserve first class support is calling a selector while skipping side-effects: something that `__experimentalGetEntityRecordNoResolver` does. That could be called `peekSelect`.

Our selectors and their resolvers are conceptually very similar to selectors in [Recoil](https://recoiljs.org/). There, every "node" has API like:
- `get()`: return the value if resolved or throw a promise if unresolved (this is optimized for Suspense, but conceptually the same thing as our `resolveSelect`)
- `getLoadable()`: return a `{ value, state }` object where `state` can be one of `loading`, `hasValue`, `hasError`. Similar to synchronous `select`. Triggers resolution.
- `peekLoadable()`: same as `getLoadable` but doesn't trigger resolution
- `invalidate()`: drop the cached resolved value -- next `get()` will trigger new resolution.

### CODE REVIEW

**Comment by nerrad** [comment]
I agree naming is unfortunate. Such is what happens as changes evolve over time. I don't think we can change the naming right now for back-compat reasons but happy to be wrong if Riad has ideas. 

I'm okay with the other suggestions regarding graduating unstable/experimental APIs but I'd defer to Riad for the final call here.

> Another thing that would deserve first class support is calling a selector while skipping side-effects: something that __experimentalGetEntityRecordNoResolver does. That could be called peekSelect.

That does sound like it could be good for the use-case where consumers want the current state without triggering any potential resolvers. I think `peekSelect` sounds like a good name.

**Comment by youknowriad** [comment]
Same here, I don't think we can rename now the stable ones. I'm ok with making the experimental APIs stable here.

Maybe we want to wait before introducing peekSelect (wait for a concrete use-case in Gutenberg)

**Comment by jsnajdr** [comment]
> Same here, I don't think we can rename now the stable ones.

One approach that fixes a big part of the damage while keeping back compat:
- keep the existing `select` control, with the `resolveSelect` behavior, but mark it as deprecated to discourage new uses
- introduce controls named `syncSelect` (already there), `resolveSelect` and `peekSelect`, where the "select" word is always prefixed with something that makes the meaning clear.

> I'm ok with making the experimental APIs stable here.

OK, I can do it in another PR. Keeping this one focused on introducing `data-controls` in `core-data` and removing the `core-data` home-grown ones.

> Maybe we want to wait before introducing peekSelect (wait for a concrete use-case in Gutenberg)

I definitely agree with not doing it in this PR, if that's what you mean by "waiting". Regarding the concrete use-case, I believe it's already there in `__experimentalGetEntityRecordNoResolver`. But we can wait until more use cases emerge, this is not urgent at all.

**Comment by youknowriad** [comment]
I'm not sure I like the renaming back-compat approach because I like the parallel between `select` and `dispatch`. In fact with this parallel, I wonder if the current `select` behavior (triggering the resolve as well) is the correct approach. I think we can probably introduce both syncSelect and resolveSelect for explicitness but I'm not sure about the deprecation.

**Review by youknowriad — APPROVED** [review]

**Comment by jsnajdr** [comment]
> In fact with this parallel, I wonder if the current `select` behavior (triggering the resolve as well) is the correct approach.

From a Redux purist perspective, triggering the resolver as a side-effect of `select` has been "incorrect" from the very beginning. A Redux selector should compute and return some value from `state` and do nothing else.

Triggering the resolver is also problematic because it's done during the render phase. It's incompatible with React async rendering: React can discard the render results and never commit them, and yet the side effect will be triggered. It also causes the new "cannot update component while rendering component" React warning and workarounds were needed in #21289. I believe this is an issue with the current `useSelect` and `withSelect` implementation, rather than a "fundamental" problem, and can be fixed by postponing the resolver call to an `useEffect` callback.

Aside from Redux, the concept of "selector with a resolver" is OK, and libraries like Recoil use it: `useRecoilValue( entitySelector( postId ) )` would both return the current value and trigger the resolver. Their implementation does it correctly though, triggering the resolver as effect, after the render result is committed.

My main concern with the naming is that the names of the controls don't correspond to the store methods they are wrappers for: the `select( 'core', ... )` control _doesn't_ synchronously select, as `registry.select( 'core', ... )` would do.

**Comment by youknowriad** [comment]
>  I believe this is an issue with the current useSelect and withSelect implementation, rather than a "fundamental" problem, and can be fixed by postponing the resolver call to an useEffect callback.

The API is meant to be "React-agnostic". If we do this change, it means we're changing the semantics of `registry.select`... probably a BC incompatible change.

**Comment by jsnajdr** [comment]
> If we do this change, it means we're changing the semantics of `registry.select`... probably a BC incompatible change.

I think it's posible to keep `registry.select` as it is and improve only the React bindings. What we want to change is the _scheduling_ of the resolver calls, nothing else.

For regular `registry.select`, the resolvers used to be scheduled synchronously, today they are scheduled with `setTimeout( 0 )`.

For React bindings, we want to batch the resolver calls and fire them all later in a `useEffect` callback. Similarly to how React batches `setState` calls while in DOM event handler callback.

This is a possible implementation of `useSelect` that calls the selectors with a custom `ReactScheduler`:
```js
const useSelect = ( mapSelect ) => {
  const registry = useRegistry();
  const { scheduler, select } = registry.selectWithScheduler( ReactScheduler );
  const mapOutput = mapSelect( select );
  useEffect( () => {
    scheduler.flush();
  } );
  return mapOutput;
}
```
The `ReactScheduler` batches the resolver calls and they are executed only later in `useEffect`.

I'm not sure if this can ever really work, especially in a large React tree where components interact, but it looks like it can be done.

**Pull request merged**
