### PR TITLE
Add missing label and focus style to the code editor textarea 

### LINKED ISSUE #6260: Code editor: the content textarea is unlabelled
When switching Gutenberg to the "Code editor" mode, a title field and a big textarea are the main editable fields in the page. The content textarea misses a label, thus it doesn't have an accessible name. Worth reminding any UI control or form field needs to be labelled...

Strongly recommended: automated tests to check the presence of labels, see #6098

Also, there's no focus style on the textarea (or it's so subtle that I'm not able to see it). I'd recommend to consider to implement a foucs stye and also improve the one for the tilte, which is almost unnoticeable.

### PR DESCRIPTION
**Pull request by afercia**
This PR adds a `<label>` element to the "Code editor" mode textarea using the same pattern used for the post title. Worth noting this pattern matches the visible placeholder text with the visually hidden label to ensure it works for all users and all assistive technology but it's basically a hack and should be avoided as much as possible. Visible labels are always preferable (and a WCAG requirement) for the reasons explained in https://github.com/WordPress/gutenberg/issues/6199 and https://github.com/WordPress/gutenberg/pull/6206#issuecomment-382304688

Also adds a filter, in the same way a filter is used for the post title.

Adds a focus (and hover) style to the content textarea to match the same effects used on the post title (see the code editor polish and focus style #1837 / #4803). The `outline-offset` property won't work in IE11 that just means on hover and focus the outline will appear externally to the box. I guess we can live with that.

It also adds a small bottom margin to the content textarea, because currently, with long content, the textarea touches the viewport bottom edge. I guess avoiding that is a better option.

To test:
- create a new post
- using a screen reader, focus the content and verify the label is announced correctly
- verify the CSS effects on hover and focus
- try to use the filter to change the label and placeholder

Fixes #6260

Screenshots (normal and hover/focus):

screen shot 2018-04-18 at 23 13 54

screen shot 2018-04-18 at 23 14 00

### CODE REVIEW

**Comment by jasmussen** [comment]
text

Seems to work as advertised, and looks good to me, 👍 👍

Is "Add content" the best we can do? It works for me, and I'm aware that "Write your story" isn't setting hearts on fire. But do we want to consider those two phrases in the same light, or should they be different?

**Review by karmatosed — DISMISSED** [review]
Changes outlined above,  lets fix before we merge this.

**Comment by afercia** [comment]
> what we had before worked far better for that reason. Is there a need to change the copy

@karmatosed there was no copy before. Right now the textarea has no label an no placeholder.

**Comment by karmatosed** [comment]
@afercia ah sorry I got myself all confused, apologies. Can't we just have "Write your story, edit text?" for cohesiveness first?

**Comment by afercia** [comment]
Sure, going to change it in `Write your story` for consistency. Not so great for Custom Post Types (e.g products, testimonials, etc.) but it can be filtered and changed by plugins so 👍

**Pull request merged**
