### PR TITLE
Add title to image and video selection sheets

### LINKED ISSUE #986: Add description/title to Image selection sheets
This won't be as big of an issue when we change the `pencil` (replace) icon eventually, but in the meantime, we should add some descriptive titles to the top of the bottom sheet, for some added clarity in the flow.

Replacing an Image:

image

For each platform, I'm hoping we can:

* iOS: add as a top row description to the ActionSheet
* Android: add it as a standard list item – text label color is `$gray-darken-10` instead of `$gray-dark`

This could also apply to initial image selection:

image

### PR DESCRIPTION
**Pull request by guarani**
## Description

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/986
Related https://github.com/wordpress-mobile/gutenberg-mobile/pull/2370

Add descriptive titles to the top of media (image and/or video) selection bottom sheets. This applies when selecting a block's content for the first time, or when replacing existing content. Affected blocks are: Image, Video, Cover, Media & Text, and Gallery. 

@iamthomasbishop the ask here was to add the title to just the image block, but I think the approach here which also handles video based blocks is better for UX (due to consistency) and was easier to implement.

There are two variations for each title, _Choose_ and _Replace_:
- "Choose/_Replace_ image"
- "Choose/_Replace_ video"
- "Choose/_Replace_ image or video"

## How has this been tested?

Download the [iOS build](https://github.com/wordpress-mobile/WordPress-iOS/pull/14436#issuecomment-655235474) and [Android build](https://github.com/wordpress-mobile/WordPress-Android/pull/12375#issuecomment-655238944) to verify the bottom sheet titles for blocks that support media.
- [x] Test cases worked on Android
- [x] Test cases worked on iOS

<details>
<summary>Test cases (click to expand)</summary>

### Image block
- [x] Add an Image block, tap the placeholder, see "Choose image"
- [x] With the image now added, tap the Replace toolbar button, see "Replace image"
- [x] Long-press the existing image, see "Replace image"
- [x] Tap the edit/replace button in the top-right corner of the existing image, choose Replace, see "Replace image"

### Video block
- [x] Add a Video block, tap the placeholder, see "Choose video" 
- [x] With the video now added, tap the Replace toolbar button, see "Choose video"

### Cover block
- [x] Add a Cover block, tap the placeholder, see "Choose image or video"
- [x] With an _image_ now added and the Cover block itself selected, tap the Replace toolbar button, see "Replace image or video"
- [x] Long-press the existing image, see "Replace image or video"
- [x] Add another Cover block, add a video, tap the Replace toolbar button, see "Replace image or video"
- [x] Long-press the existing video, see "Replace image or video"

### Media & Text block 
- [x] Add a Media & Text block, tap the placeholder, see "Choose image or video"
- [x] With an _image_ now added and the Media & Text block itself selected, tap the Replace toolbar button, see "Replace image or video"
- [x] Long-press the existing image, see "Replace image or video"
- [x] Add another Media & Text block, add a video, tap the Replace toolbar button, see "Replace image or video"

### Gallery block
(The Gallery block has no mechanism for replacing images, only for removing and adding them.)
- [x] Add an Gallery block, tap the placeholder, see "Choose image"

</details>

## Screenshots 

<details>
<summary>Screenshots showing how the image picker bottom sheet looks with these changes (click to expand):

</summary>

| | Adding an image for the first time | Replacing an existing image |
| -- | -- | -- |
| **iOS** |  |  |
| **Android** |  |  |

</details>

## Types of changes
- New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

## Edits
- Update to include action for toolbar Replace button: https://github.com/WordPress/gutenberg/pull/23083#issuecomment-644967291
- Update to make sheet titles use sentence case: https://github.com/WordPress/gutenberg/pull/23083#issuecomment-645002001
- Remove the word "from" from sheet titles: https://github.com/WordPress/gutenberg/pull/23083#issuecomment-656898386

### CODE REVIEW

**Comment by mchowning** [comment]
This looks good @guarani. Nice job!

I noticed that there is not a description/title when clicking the change XXX button on the toolbar for the Cover, Media&Text, and Video blocks (it works for the Image block). Was that intentional or is that something that should be addressed?

rotate_image mp4

**Comment by iamthomasbishop** [comment]
@guarani This is looking mostly good. In addition to @mchowning’s feedback, I have just a couple of tiny suggestions:

* On Android, is there any way we can use the standard section title instead of the larger sheet header that you’re using here? ([example](https://user-images.githubusercontent.com/1200432/84825760-8c0a1a80-afe7-11ea-9ae2-3294c03f03fc.png))

* We can probably use sentence case on both platforms for the “choose image from” label. So the labels would become “Choose image from” and “Replace image from”.

**Comment by guarani** [comment]
> I noticed that there is not a description/title when clicking the change XXX button on the toolbar for the Cover, Media&Text, and Video blocks (it works for the Image block). Was that intentional or is that something that should be addressed?

Thanks for catching that oversight @mchowning! Fixed now.

> On Android, is there any way we can use the standard section title instead of the larger sheet header that you’re using here? (example)

@iamthomasbishop thanks for the feedback. I've updated this as you've suggested and it works well. My only concern now is the slightly large gap between the title and the top edge of the bottom sheet (as seen in the [jpg](https://user-images.githubusercontent.com/1200432/84825760-8c0a1a80-afe7-11ea-9ae2-3294c03f03fc.png) you shared with me in a comment above). This gap is already present in other parts of the Android app though, when bottom sheets are shown.
I've updated the screenshots in the PR description above to show how this feature looks, so please feel free to check those out and let me know if anything needs tweaking.

> We can probably use sentence case on both platforms for the “choose image from” label. So the labels would become “Choose image from” and “Replace image from”.

Done 👍

**Comment by guarani** [comment]
@iamthomasbishop even if we migrate to use the [new Pull-Down Menu in iOS 14](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pull-down-menus/) (and perhaps the Menu component on Android) that you've suggested offline, most of this feature will easily transfer across.

**Comment by iamthomasbishop** [comment]
> I've updated this as you've suggested and it works well

@guarani Think this looks fine, although agreed, we might want to adjust the top spacing on sheets that lead with a section title (this happens because the baseline of the text label is shifted a bit towards the bottom edge in order to provide better spacing between sections).

> if we eventually migrate to use the new Pull-Down Menu in iOS 14 (and perhaps the Menu component on Android) that you've suggested offline, most of this feature will easily transfer across.

Agreed, it should translate well.

**Comment by mchowning** [comment]
This is a very minor nitpick, and I don't think it should block this PR at all (I'm not even sure the best way  to improve it), but one thing that I noticed going back through this is that the language now reads just a little bit oddly. For example, the title "Choose image or video from", has as the first option "Choose from device" so it repeats the word "Choose". Then the next option is "Take a Photo", which doesn't flow from the title "Choose image or video from...Take a Photo". In fact, the only option that really flows naturally from the title is "Choose image or video from...WordPress Media Library." I wonder if this is worse/better in other languages. 



Again, this is a very minor point, and I'm commenting on it just as something for us to keep in mind going forward (cc: @iamthomasbishop ), and not because it is something I think we need to urgently fix.

**Review by mchowning — APPROVED** [review]
LGTM! Nice work! 👍

**Comment by guarani** [comment]
> This is a very minor nitpick, and I don't think it should block this PR at all (I'm not even sure the best way to improve it), but one thing that I noticed going back through this is that the language now reads just a little bit oddly. For example, the title "Choose image or video from", has as the first option "Choose from device" so it repeats the word "Choose". Then the next option is "Take a Photo", which doesn't flow from the title "Choose image or video from...Take a Photo". In fact, the only option that really flows naturally from the title is "Choose image or video from...WordPress Media Library." I wonder if this is worse/better in other languages.

@mchowning I agree the wording sounds a bit off. It caught my attention too while testing this PR. I wonder if we should address this now or leave it for later. These titles themselves are new, so tweaking them now might be easier done now before they are translated into other languages. WDYT @iamthomasbishop?

**Comment by iamthomasbishop** [comment]
@guarani mchowning it's slightly awkward, but it doesn't bother me that much tbh. Perhaps removing the word "from" would help (`Choose [image|video]...` and `Replace [image|video]...`)?

**Comment by mchowning** [comment]
> Perhaps removing the word "from" would help

I like that idea! That feels much less awkward to me.

**Pull request merged**
