### PR TITLE
Add fallback handling for plugins or themes using the Customizer

### LINKED ISSUE #35874: Ensure the Customizer is available for plugins or theme options when using a FSE theme
### Description

When using a theme that declares support for Full Site Editing (uses `theme.json`), the _Customize_ options are hidden (you can still access the Customizer directly with a link).

This would require plugins or themes that wish to continue using options to implement their own links, creating multiple entry-points to a core feature, and potential user confusion/frustration.

### Step-by-step reproduction instructions

1. Verify that Twenty Twenty-One is your active theme
2. Install the WooCommerce plugin (uses the Customizer to set up their display options)

The Customizer link is where it usually sits by default, under the Appearance menu item.

3. Switch to the TT1-Blocks theme

The Customizer link is now gone from where it used to be, but replaced with a custom link added by WooCommerce, which takes you to its own area in the Customizer.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Clorith**
## Description
This change introduces a new function, `gutenberg_site_requires_customizer()`, which looks up if any plugins, or theme features, have added support for the Customizer.

It then utilizes that check before letting Full Site Editing filter away the Customizer access points. It is worth noting that the Customizer is not deactivated even without this patch, but it is important to maintain a canonical entry-point for the user when any plugin, or theme feature, relies on it.

This would fix #35874

## How has this been tested?
1. Activate the Twenty Twenty One theme
2. Install the WooCommerce plugin (no setup required, it just needs to be active)
3. You should now see the Appearance > Customizer menu items
4. Switch to the TT1-Blocks theme
5. The Customizer menu is now missing, but a custom "Customize WooCommerce" link is added instead (this is WooCommerce working around the flaw as described in #35874)
6. Apply this patch
7. The Appearance > Customizer link should now have returned
8. De-activate WooCommerce
9. The Appearance > Customizer link should disapear as no more plugins or theme features rely on it.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by carolinan** [comment]
I am still curious why the removal of the menu item simply can't be reverted.

**Comment by Clorith** [comment]
Adding a quick note that my patch here implements a new function, `gutenberg_site_requires_customizer()`, although we could just as easily just add in an if statement for `has_action()` into the two locations that rely on it, this was done in case it needed to be more flexible (for example if strange edge cases needed to be accounted for as well, making it easier to add them in one location right away).

As for the discussion about whether something should be reverted or not, I'll leave that for the product team to tackle, my main concern with this PR was to ensure backwards compatibility and nothing more :)

**Comment by noisysocks** [comment]
Thanks for working on this! 

I think we should strive to implement this PR as the solution to #35874. If possible I'd prefer to **not** always show a link to the Customizer as I feel it will be confusing to users who are brand new to WordPress to have both an Appearance → Editor and Appearance → Customize. 

We may end up having to always show a link to the Customizer. For example, if we don't end up with a solution for https://github.com/WordPress/gutenberg/issues/29126 in time for WP 5.9 then we don't really have a choice. We can make this decision in the 5.9 beta period if need be.

**Review by Mamaduka — APPROVED** [review]
Hi, @Clorith, can you rebase this branch on top of the current `trunk` and I think we're good to merge once all checks are green ✅

**Comment by noisysocks** [comment]
Sorry @Clorith, looks like there are more conflicts. Could you please rebase again? Feel free to merge once resolved.

**Pull request merged**
