### PR TITLE
update readme grammar

### PR DESCRIPTION
**Pull request by timelsass**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
The original version is a common pattern used in other Readme files for UI components.

I personally don't like the fact that this change proposed diverges from other files.

**Comment by swissspidy** [comment]
Aren't those more intended to be headings rather than part of the sentence?

**Comment by timelsass** [comment]
They seemed like they were headings, but they were just bold letters.  I wasn't sure which way was better.  In reading it as it was, I just read "Don't don't" and stopped to reread the section because it caught me off guard.  I can change to headings if that is better?

**Comment by gziolo** [comment]
> They seemed like they were headings, but they were just bold letters. I wasn't sure which way was better. In reading it as it was, I just read "Don't don't" and stopped to reread the section because it caught me off guard. I can change to headings if that is better?

@melchoyce @davewhitley - since you authored most of the design guidelines, what do you think?

If we were to change that, we need to apply it to all README files for components.

**Comment by melchoyce** [comment]
They're meant as headings — some other files list multiple dos/don'ts.

**Comment by mapk** [comment]
I'm not too familiar with the history here. Updating these to be proper headings sounds right, but I agree that this change should continue out to other README file as well. Can this PR include that?

@melchoyce I'm not sure if you're agreeing with this change? Can you clarify?

**Comment by melchoyce** [comment]
Disagreeing — since some readmes include multiple dos/don'ts, it doesn't make sense to collapse them all down into a single sentence.

**Comment by mapk** [comment]
> Disagreeing

Okay, For some reason I thought the change was the heading levels in the description. After looking at the files, I agree with the disagreement here. It's makes more sense to me to keep it as is. Thanks for clarifying this, Mel. 

I'm closing this because the way they're listed now is intentional.

**Pull request closed without merging**
