### PR TITLE
Blocks: Implement recursion checking and reporting for template-parts, post-content and reusable blocks (#26923)

### LINKED ISSUE #26593: Infinite recursion trying to edit a wp_template with revisions containing wp:post-content blocks
**Describe the bug**
I'm learning how to develop a Full Site Editing theme.  
Sometimes I use the **Site Editor (beta)** and other times **Appearance > Templates** or **Appearance > Template Parts**.

Having created a template-part called `post-content` I encountered problems when I attempting to edit some of the Templates ( wp_template ). The editor never loaded. It either timed out or produced a Fatal error - memory exhausted.

I tracked the problem down to a never ending recursion involving `the_content` and `pre_render_block`, while running `WP_Rest_Revisions_Controller->prepare_item_for_response()`. 

The problem occurs when the `wp:post-content` block is being processed.  

Between them the block rendering in `gutenberg_render_block_with_assigned_block_context()` and `the_content` filtering in
`gutenberg_render_block_core_post_content()` produces a never ending recursive loop which isn't shortcircuited by the current test on the `$block->context['postId']`  in `gutenberg_render_block_core_post_content()`. 

Example: 
This is the content of the `revision` postId = 715 which is an autosaved revision of the `single` wp_template 694.
```
<!-- wp:template-part {"postId":665,"slug":"header-2-columns","theme":""} /-->

<!-- wp:post-title /-->

<!-- wp:post-content /-->

<!-- wp:template-part {"postId":548,"slug":"footer-part","theme":"fizzie"} /-->
```

**To reproduce**
1. Using FSE create a template which contains `wp:post-content` ( e.g. `single` ).
2. Edit it to create a revision  (*)
3. Save and return to the dashboard.
4. Use Appearance > Templates.  
5. Use the Edit link to open the editor.
6. Wait until it goes wrong.

(*) I believe the problem may occur with both autosaved revisions and user saved revisions.

**Expected behavior**
The Editor should display the 'single' Template, with the template parts rendered.
The post content block should say "This is a placeholder for post content."

**Screenshots**
Here I get the Fatal error due to the logic in my tracing plugin. It happens a lot earlier than the time out.

image

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta1 
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenber 9.2.2 or latest Gutenberg source with FSE enabled.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Additional context**
- I documented my analysis in https://github.com/bobbingwide/fizzie/issues/7
- I found two ways to fix the problem.
- My current workaround is to extend the shortcircuit logic in `gutenberg_render_block_core_post_content()`
- Add the following test after the first one
```
if ( 'revision' === $block->context['postType'] ) {
		return '';
}
```

### LINKED ISSUE #26923: Fatal errors due to infinite recursion with Full Site Editing
**Describe the bug**
When using Full Site Editing it is fairly easy to create scenarios which lead to the website failing due to infinite recursion. 
Some work has been done to prevent the problems occurring visually in the editor, but once saved it becomes very difficult to recover from the problem. 

In the simplest scenario below the recursion involves a single post using the `core/post-content` block. More complex scenarios involve multiple posts each with their own `core/query` and `core/post-content` blocks. 

WordPress core needs to appreciate that this infinite recursion can occur, take steps to prevent it and produce relevant information to the content creator and/or front end user to explain the actions taken.

I'm raising this as a separate issue to #26593, although I believe the root cause of both problems is the same.
That is, the inability to detect and prevent infinite recursion while processing potentially recursive constructs. 

These recursive constructs include:

- Post Content ( core/post-content )
- Reusable blocks ( core/block )
- Template parts ( core/template-parts )

plus, to be confirmed

- possibly Post Excerpt ( core/post-excerpt )
- Combinations of the above, if that's possible.

**To reproduce**
1. Activate a Full Site Editing theme such as Twenty Twenty-One Blocks
2. Activate Gutenberg as the only plugin.
3. Create a new post.
4. Insert a Post Content block
5. Save
6. View
7. See the Fatal error 

Notes: 
- You may get a Publishing failed message while attempting to Publish the post.  
- This message is the first evidence of the problem.
- If you change the post to remove the `core/post-content` block and save again then you're in #26593 territory.
- Once published you will get Fatal errors if you try to Edit the post.

**Expected behavior**
The infinite recursion should be detected, halted gracefully and an appropriate message reported to the user.
In `WP_DEBUG` mode contextual information should be displayed to assist with problem resolution.

**Screenshots**
In this screenshot the Fatal error occurs when the Allowed memory is exceeded. 
image

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg 9.3.0 and/or Gutenberg built from source

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**

- See also https://github.com/WordPress/gutenberg/issues/22080#issuecomment-628386386 where the basic problem was first mentioned.
- #26593 - which is a convoluted form of the basic problem
- I have not yet looked at https://github.com/WordPress/gutenberg/issues/18704
- For a more complex scenario involving multiple posts containing `core/query` blocks with `core/post-content` within the `core/query-loop` see https://github.com/bobbingwide/fizzie/issues/27
- I've developed a solution to the problem which is along the lines of the solution I developed for a parallel scenario involving shortcodes. See https://github.com/bobbingwide/oik/issues/166

### PR DESCRIPTION
**Pull request by bobbingwide**
## Description
- In #26923 I documented some scenarios where block rendering results in infinite recursion. 
- The problems are easy to create in Full Site Editing using the `core/template-part` and/or `core/post-content` blocks.
- A very similar problem with Reusable blocks ( `core/block` ) was reported #18704.
- In #26951 @carlomanf has developed a solution that checks for recursion for any block within `WP_Block` class.
- In my solution the recursion checking is only performed by block types which can go infinitely recursive.
  - `core/post-content`
 - `core/template-part`
 - `core/block` 
 - I believe it should be possible to cause `core/post-excerpt` to recurse.  

Both solutions rely on a test to see if the block that's about to be rendered is already being processed.

The logic implemented in each solution is:

- Check if the block that's about to be rendered is already being rendered.
- If it isn't already being rendered. ie It's safe to render
  - add it to the stack of blocks being rendered.
  - render the block
  - pop it from the stack
- else don't render it

- In the `WP_Block` fix the recursive block is rendered as an empty string. Neither the end user nor the site administrator is made aware that there was a recursion problem. 
- In this solution, there is an option to report the recursion error. 
- The level of detail reported depends on the setting for `WP_DEBUG`
- This solution also supports extending the base solution for reporting recursion errors.

### Regarding the reusable blocks issue ( #18704 )
- I've developed an extension class for the reusable block recursion problem that attempts to deal with the problem when encountered in a REST request.  
- This error reporting extension for reusable blocks is not (yet) part of this PR. 
- While it is able to deal with a self recursive reusable block
- It is unable to prevent the block editor from going recursive when a user inserts a reusable block that's been returned in the request to fetch reusable blocks. 

### Environment

- Tested with WordPress 5.6-beta3
- Active theme: Twenty Twenty-One Blocks, with some additional template parts, some template parts _commented_ out  and modified CSS.
- Active plugins: Gutenberg
- Plus, used to aid understanding of the post-content output:  
 - oik - for the [bw_list] shortcode
- And during development - oik-bwtrace - used to trace server events

#### Front end
- Tested recursion detection and reporting for template-parts using the `404.html` template and a couple of recursive template parts. 
- Tested recursion detection and reporting for post-content within the query / query loop in multiple pages
- Tested recursion detection for a self recursive reusable block.
image

image

image

## Types of changes
- Fixes #26923
- Fixes #26593 - recently recreated then retested

These changes also include the fixes applied for:
- #26772 
- #26731 

The solution introduces
-  4 new files included in `load.php`
- which implement 2 classes 
  - WP_Block_Recursion_Control 
  - WP_Block_Recursion_Error
- and 3 APIs:
  - gutenberg_process_this_content - performs the check for recursion
  - gutenberg_clear_processed_content - pops the last item processed
  - gutenberg_report_recursion_error

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. 

- I've not delivered any automated tests.
- I imagine the new functions will need documenting so that they can be used by other block developers who may have had to develop their own recursion checking.

### CODE REVIEW

**Comment by carlomanf** [comment]
So, compared to my PR, the only advantage of this one is it reports the error depending on `WP_DEBUG`? I just want to make sure I'm not missing anything else.

I'm happy to add that feature to my PR, considering mine solves the same bug with 4% of the amount of code that yours does.

> * In #26951 @carlomanf has developed a solution that checks for recursion for any block within `WP_Block` class.
> * In my solution the recursion checking is only performed by block types which can go infinitely recursive.

Regarding this point, I should also point out that any third-party plugin can add a block type that has the potential for infinite recursion, and my PR proactively prevents those as well.

**Comment by youknowriad** [comment]
@carlomanf depending on how you're checking for recursions, I'm not sure catching all blocks is a good thing. For example, we can use group blocks inside group blocks that's fine and potentially we could build dynamic group blocks that render inside dynamic group blocks, that's fine too.

**Comment by bobbingwide** [comment]
> I'm not sure catching all blocks is a good thing

@youknowriad I've added a comment to @carlomanf's PR that covers this problem - for the `core/post-title` block. 
 
 https://github.com/WordPress/gutenberg/pull/26951#issuecomment-728927264

> I just want to make sure I'm not missing anything else.

Whichever solution is chosen, we will need to ensure that it's usable and extendable by third party plugins.

**Comment by carlomanf** [comment]
@youknowriad 

> @carlomanf depending on how you're checking for recursions, I'm not sure catching all blocks is a good thing. For example, we can use group blocks inside group blocks that's fine and potentially we could build dynamic group blocks that render inside dynamic group blocks, that's fine too.

The only things my patch is designed to "catch" are fatal errors. Everything else, it should let pass.

That said, @bobbingwide has been very helpful in discovering some false positives, which I have since corrected. He believes he's found another one with the post title block, but I'm not able to reproduce it.

It would be much appreciated if you could test the patch at #26951 and confirm whether you can reproduce Herb's false positive with the post title, or this other hypothetical scenario with group blocks. As far as I can tell, the patch works correctly and doesn't escape anything that wouldn't have otherwise caused a fatal error.

**Comment by mcsf** [comment]
@bobbingwide: thanks for the PR. However, in light of #28405 (merged) and #28456 (to be approved), is there anything left before it can be closed?

**Pull request closed without merging**
