### PR TITLE
Solve #18704 on front-end

### LINKED ISSUE #18704: 500 error and 'Reusable' tab disappears when a reusable block is embedded into itself
**Describe the bug**
When a reusable block has a reusable block embedded (containing the same ID)  it throws a 500 error and the 'Reusable' tab disappears in WP 5.3.

**To reproduce**
1 Go to  wp-admin/edit.php?post_type=wp_block&paged=1

2. Create a new reusable block. For this test, I am calling it 'Reusable Block Test'. You can call it anything you'd like. Publish and save, note the post ID from the URL.

3. Embed a new reusable block into the one you just created. Pick a random block.

p10

4. Switch the view to 'Code Editor' and enter the ID from step #2. Update the post.

p11

5. You should get an error : 'Updating failed. or Updating failed. Error message: The response is not a valid JSON response.  (note that it did update)

6. Go to Posts -> Add New. Open up the "Network" tab in Google Chrome. Clear anything there to get a fresh list. 

p12

7. Add a new block. You should get a 500 error and the "Reusable" tab is missing. 

p15

Request URL: */wp-json/wp/v2/blocks?per_page=100&_locale=user
Request Method: GET
Status Code: 500 
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin

p13

8. Editing the reusable block from step 2 results in a frontend error: 
"There has been a critical error on your website. Please check your site admin email inbox for instructions"

**Expected behavior**
Adding a block allows you to add previously created Reusable Blocks by using the "Reusable" tab

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 78.0.3904.108 

**Additional context**
WP Version:  5.3

### LINKED ISSUE #26923: Fatal errors due to infinite recursion with Full Site Editing
**Describe the bug**
When using Full Site Editing it is fairly easy to create scenarios which lead to the website failing due to infinite recursion. 
Some work has been done to prevent the problems occurring visually in the editor, but once saved it becomes very difficult to recover from the problem. 

In the simplest scenario below the recursion involves a single post using the `core/post-content` block. More complex scenarios involve multiple posts each with their own `core/query` and `core/post-content` blocks. 

WordPress core needs to appreciate that this infinite recursion can occur, take steps to prevent it and produce relevant information to the content creator and/or front end user to explain the actions taken.

I'm raising this as a separate issue to #26593, although I believe the root cause of both problems is the same.
That is, the inability to detect and prevent infinite recursion while processing potentially recursive constructs. 

These recursive constructs include:

- Post Content ( core/post-content )
- Reusable blocks ( core/block )
- Template parts ( core/template-parts )

plus, to be confirmed

- possibly Post Excerpt ( core/post-excerpt )
- Combinations of the above, if that's possible.

**To reproduce**
1. Activate a Full Site Editing theme such as Twenty Twenty-One Blocks
2. Activate Gutenberg as the only plugin.
3. Create a new post.
4. Insert a Post Content block
5. Save
6. View
7. See the Fatal error 

Notes: 
- You may get a Publishing failed message while attempting to Publish the post.  
- This message is the first evidence of the problem.
- If you change the post to remove the `core/post-content` block and save again then you're in #26593 territory.
- Once published you will get Fatal errors if you try to Edit the post.

**Expected behavior**
The infinite recursion should be detected, halted gracefully and an appropriate message reported to the user.
In `WP_DEBUG` mode contextual information should be displayed to assist with problem resolution.

**Screenshots**
In this screenshot the Fatal error occurs when the Allowed memory is exceeded. 
image

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.6-beta3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? [e.g: "gutenberg plugin", "default"] Gutenberg 9.3.0 and/or Gutenberg built from source

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

**Additional context**

- See also https://github.com/WordPress/gutenberg/issues/22080#issuecomment-628386386 where the basic problem was first mentioned.
- #26593 - which is a convoluted form of the basic problem
- I have not yet looked at https://github.com/WordPress/gutenberg/issues/18704
- For a more complex scenario involving multiple posts containing `core/query` blocks with `core/post-content` within the `core/query-loop` see https://github.com/bobbingwide/fizzie/issues/27
- I've developed a solution to the problem which is along the lines of the solution I developed for a parallel scenario involving shortcodes. See https://github.com/bobbingwide/oik/issues/166

### PR DESCRIPTION
**Pull request by carlomanf**
## Description
Partially resolves #18704, only on front-end. Also resolves #26923, further info about this solution is available in my comments on that issue.

## How has this been tested?
Tested it according to #25472, and saw the fatal error disappear and the front-end page load successfully. Without this patch, there was a fatal error.

I didn't attempt to fix the admin experience, but confirmed that it's NOT fixed by this.

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
Is this implementation of the `WP_Block` class loaded in the plugin? It only exists for backward compatibility:
https://github.com/WordPress/gutenberg/blob/1d21b92a078c9b504b899aa93a19f533d4405eb1/lib/class-wp-block.php#L11
Once we enforce WordPress 5.5.0 as a requirement for the plugin, it will be removed.

**Comment by carlomanf** [comment]
@gziolo to be honest, I actually tested this by applying these changes to the core class in wp-includes, but I get very confused about components that are duplicated in the core and the plugin and wasn't sure where was the correct place to submit the patch. Should I open a ticket on trac instead?

**Comment by gziolo** [comment]
Assuming that `WP_Block` class needs to be modified, it will require a patch in WP core so it wouldn't be that bad idea to open a ticket in Trac. Once we have a fix there we can try to use one of the existing hooks to temporarily (until released in WP Core) patch it in the plugin.

**Comment by carlomanf** [comment]
Note that I've just detected a side effect of the patch. Although it successfully escapes fatal errors, it also appears to wrongly escape some blocks that were not causing any fatal errors. This side effect only happens when there is no user authenticated. I will have to investigate when I get time.

**Comment by bobbingwide** [comment]
> Although it successfully escapes fatal errors, it also appears to wrongly escape some blocks that were not causing any fatal errors.

I too noticed that problem. 

Before attempting to implement my own solution to the problem, which is individually applied to potentially recursive block types, I tried this solution.  It incorrectly returned too early for blocks in a `query-loop`.
image


This was running my test case referenced here: https://github.com/bobbingwide/fizzie/issues/27#issuecomment-725676298

**Comment by bobbingwide** [comment]
> Assuming that WP_Block class needs to be modified

Is there any mileage in Gutenberg extending the `WP_Block` related classes to extend the WordPress core functionality when it's required?

And/or instead of using `new WP_Block` potentially recursive blocks could use `new gutenberg_WP_Block_recursive`

**Comment by carlomanf** [comment]
@bobbingwide thank you for pointing out that unexpected result involving the query loop. I just added some commits that appear to fix this.

**Comment by bobbingwide** [comment]
@carlomanf I tried your fix. It got a bit further but still detected recursion too early.
image
Compare this output with my expected output.

BTW. I'm making progress on a very similar solution with the ability to report where the problem occurred. 
I've now refactored my original prototype to use as a class. Now I'm looking into the possibility of extending the class in order to implement context sensitive errors - ie To extend the solution to override the logic for `report_recursion_error()`.

See https://github.com/bobbingwide/fizzie/tree/main/includes

This solution won't require changes to the WP_Block class, but will still require shimming once it's become part of core.

**Comment by carlomanf** [comment]
@bobbingwide It looks like it's the post content and post title block that are getting caught this time. I was able to replicate it with the post content and added another commit to fix this, but I couldn't find any issues with the post title. Hopefully that too gets solved with this new commit. Thanks for testing this out.

**Comment by bobbingwide** [comment]
@carlomanf I retested latest your solution and still got too many false positives.

I changed your recursion detection logic to return a recursion message:
```
if ( in_array( ( array ) $this, self::$currently_rendering)  && $is_dynamic  ) {
                return $this->recursion_message();
            } else {
                self::$currently_rendering[] = (array) $this;
            }
```

Implemented as below:
```
/**
     * Returns a message about the recursion that's occurred.
     *
     * @return string
     */
	function recursion_message() {
        $recursion_message = '';
        // @TODO Test on WP_DEBUG, user is logged in, user has capability to fix etc.
        if (true) {
            // Only echo when safe to do so.
            if ( false ) {
                echo '<br />';
                echo "Recursion detected: ";
                echo $this->parsed_block['blockName'];
                //echo ':';
                //echo $this->block_type;
                //print_r($this->parsed_block);
                echo ' attrs: ';
                echo implode(',', $this->parsed_block['attrs']);
                echo $this->render_context( $this->context );
                //echo '<br />';
            }
            $recursion_message = "<br />Recursion detected:" . $this->parsed_block['blockName'];
            $recursion_message .= '<br />Attrs: ';
            $recursion_message .= $this->render_context( $this->parsed_block['attrs']);
            $recursion_message .= '<br />Context: ';
            $recursion_message .= $this->render_context( $this->context );
            $recursion_message .= '<br />';
            $recursion_message .= $this->render_stack();
        }
        return $recursion_message;
    }

    /**
     * Renders the currently_rendering stack.
     *
     * Aids problem determination by showing the stack of nested blocks
     * where the recursion was detected.
     * @return string
     */
	function render_stack() {
	    $content = '<ol>';
	    foreach ( self::$currently_rendering as $key => $block ) {
	        //print_r( $block );
	            $content .= '<li>';
                $content .= $block['name'];
                $content .= ' ';
                //print_r( $block['context']);
                $content .= $this->render_context( $block['context'] );
                //$content .= ' ';
                //$content .= implode(':', $block['* available_context'] );
                $content .= '</li>';

        }
	    $content .= '</ol>';
	    //echo $content;
	    return $content;
    }

    /**
     * Renders the top level of an array.
     *
     * @param $context
     * @return string
     */
    function render_context( $context ) {
        $content = '';
        foreach ($context as $key => $value) {
            $content .= "$key=";
            if ( is_array( $value )) {
                $content .= '[]';
            } else {
                $content .= $value;
                $content .= ' ';
            }
        }
        return $content;

    }
```

My test case shows the call stack where the `post-title` block was not processed.
image

In the test results for PR #27012 the post titles are displayed because they don't need recursion checking. 
If a block could be given a property that indicates it could go recursive then this solution might be able to satisfy the  requirements.  If this property were the className that handled the recursion error and the recursion checking was only performed when this property was not null, then this solution would work. 

For both our solutions, there's still the problem that once the logic is in core it can't easily be altered in a newer version of Gutenberg.

**Comment by carlomanf** [comment]
@bobbingwide I'm not able to reproduce the false positives with the post title. They're rendering fine for me.

Maybe someone else could test to confirm whether they get these false positives?

**Comment by carlomanf** [comment]
Closing this because it needs to be targeted at core instead.

**Pull request closed without merging**
