### PR TITLE
Adapt site editor layout widths based on viewport size

### PR DESCRIPTION
**Pull request by jameskoster**
https://github.com/WordPress/gutenberg/assets/846565/c21d3157-97e2-4243-8bf8-7d1bfdbaed75

## What?
Update width of site editor layout areas based on viewport size. 

## Why?
The existing one-size-fits-all dimensions do not scale elegantly, and the navigation sidebar is arguably too wide, especially at smaller screen sizes.

* The dark navigation sidebar width scales from 260px to 308px.
* The content area width scales from 360px to 488px.

## Testing Instructions
1. Check out this branch
2. `npm run build`
3. Open the site editor
4. Notice that the width of the dark navigation sidebar, and the content area (in data views list layout) width changes with the viewport.

<details><summary>Original PR</summary>## What?
Reduce the width of the navigation sidebar in the site editor from 360px to 320px.

## Why?
Currently the navigation sidebar and the list layout content frame are roughly equal in width (360px and 380px respectively). Given the nature of the content in each element I'm not sure this is appropriate. 

As the Navigation sidebar consists mostly of menu items it's width can be reduced slightly. This attempts to install more appropriate visual balance between sidebar / content, and provides more space for page contents / preview frames on the right.

The value isn't necessary a proposal, there may be scope to go narrower, or to adjust the width of the content frame instead. The PR mostly aims to start the conversation.

I acknowledge it may be preferable to wait until we have a more concrete vision for the broader admin design for making this change.  

## Testing Instructions
1. Check out this branch
2. `npm run build`
3. Open the site editor
4. Navigate around observing the narrower navigation sidebar

### Before
Screenshot 2024-01-30 at 13 22 45

### After
Screenshot 2024-01-30 at 13 20 41
</details>

### CODE REVIEW

**Comment by jameskoster** [comment]
Another option to consider here is allowing users to resize these columns manually (within certain parameters) rather than setting a static value.

**Review by t-hamano — COMMENTED** [review]
I noticed that the width of the sidebar was increased from 320px to 360px in the past, completely contrary to this PR 😅

- #46769

However, the UI of the Site Editor has changed significantly since then, so I think we can reconsider the ideal width.

Personally, I prefer a narrower width.

**Comment by jasmussen** [comment]
I think we can revisit those widths, and would prefer we do fixed widths before we add user resizing options. But I don't know that it's good to change this width until we have a clearer vision specifically of the split view. There are probably some responsive options we can look at, but it's important to note that this particular sidebar is used across a great deal of sections, and in the future even more. It may be a good change across all of those, but probably best to explore that space a bit more before we commit.

**Comment by t-hamano** [comment]
Since there is currently no details page in the site editor, I'm thinking we might be able to revive this PR.

#60847 suggests reducing the sidebar width to 240px.

240px might be too narrow, but I think we could reduce it to at least 320px.

**Comment by richtabor** [comment]
I think rather than one-off pushes, we should get a clearer view of what the next iteration of this should look/feel like. 

Otherwise we'll change it to one size, then a few months later change it to another. :)

**Comment by jameskoster** [comment]
The sidebar width is currently a bit troublesome on data views side-by-site layout, especially on smaller screens. There's a lot of wasted space in virtually all sidebar instances, and the preview feels somewhat narrow proportionally:

Screenshot 2024-06-18 at 14 58 42

Dimensionally the sidebar is only 20px narrower than the content panel which is close enough to be visually uncanny. 

I do agree we should think about the layout more holistically though.

One thing to try could be scaling the sidebar / content panel widths with the viewport. So instead of static dimensions the layout would shrink / grow accordingly. Rough example:

layout


Perhaps we start by installing a mechanism like this, then adapting the values as required?

**Comment by t-hamano** [comment]
> Perhaps we start by installing a mechanism like this, then adapting the values as required?

That seems like a great approach to me.

Hopefully, we can also fix the overlap at certain screen sizes as reported in #62104.

**Comment by jameskoster** [comment]
I pushed some changes and updated the OP. We can easily tweak values. Let me know what y'all think.

**Comment by jameskoster** [comment]
Any thoughts on this one @WordPress/gutenberg-design ?

**Comment by richtabor** [comment]
Does the dark sidebar ever need to be wider than its default state? 

If it's mostly a list of list of menu items that open secondary panels, I question if it should ever get wider. 

I think only the canvas/frame needs to grow, probably not even the secondary panel (where lists of pages are).

**Comment by jameskoster** [comment]
@richtabor reducing the sidebar width is what this PR originally did. I didn't think you were keen?

I do think that's a reasonable place to start...

**Comment by richtabor** [comment]
> @richtabor reducing the sidebar width is what this PR originally did. I didn't think you were keen?
> 
> 
> 
> I do think that's a reasonable place to start...

Resizing the sidebar is fine, but I don't think that the secondary sidebar should grow as well.

**Comment by jasmussen** [comment]
> Resizing the sidebar is fine, but I don't think that the secondary sidebar should grow as well.

It could have its own behavior, like this, perhaps: https://github.com/WordPress/gutenberg/issues/62748

**Comment by jameskoster** [comment]
Closing since https://github.com/WordPress/gutenberg/pull/63431 was merged.

**Pull request closed without merging**
