### PR TITLE
Env: Add SSL port support to the docker compose

### PR DESCRIPTION
**Pull request by WraithKenny**

### CODE REVIEW

**Comment by WraithKenny** [comment]
A future _enhancement_ might be to change the shape of the `ssl` key:
```json
{
	"ssl": {
		"cert": "./files/mycert.crt",
		"key": "./files/mycert.key"
	}
}
```
so that we can handle mounting for the enduser.

**Comment by WraithKenny** [comment]
For #8211

**Comment by WraithKenny** [comment]
Any feedback? Should I try to automate the SSL Cert management, and automate mounting the required files, or is it enough for now to enable the ports?

**Comment by swissspidy** [comment]
> Any feedback? Should I try to automate the SSL Cert management, and automate mounting the required files, or is it enough for now to enable the ports?

How difficult would it be to integrate something like devcert?

**Comment by WraithKenny** [comment]
not interested in contributing anymore.

**Pull request closed without merging**
