### PR TITLE
Legacy text widget should have option to transform to paragraph block

### LINKED ISSUE #32825: Legacy text widget should have option to transform to paragraph block
## What problem does this address?
Legacy text widget should have option to transform to paragraph block on new widget screen.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Description

Legacy text widget should have option to transform to paragraph block on new widget screen.

## How has this been tested?
Open the widget edit screen and try and transform a text widget to a paragraph block.

#### Add transform option if only text
Screenshot 2021-06-22 at 10 45 25

#### No transform option
Screenshot 2021-06-22 at 10 45 36

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 

Fixes #32825

### CODE REVIEW

**Comment by noisysocks** [comment]
The problem with this is that a Text widget can contain headings, lists, images, etc. This is why the Text widget has the "Convert to blocks" button in the toolbar instead of a transform. I think we should leave it that way or find a way to move the "Convert to blocks" button to the transform menu.

**Comment by spacedmonkey** [comment]
Could we check if contains html / is just text and not offer the transform option. There is a match param we could use for that... 

Let me try and work it out.

**Comment by spacedmonkey** [comment]
@noisysocks I have updated the PR. There is now a check to see if the content of the widget is only text. In my testing it work pretty well... Can you review and get back to me.

**Comment by noisysocks** [comment]
Sounds like a good idea. I haven't tested this but I suspect using `stripHTML` means this won't work if the Paragraph block contains inline formatting e.g. `<b>` and `<i>` tags.

**Comment by spacedmonkey** [comment]
> Sounds like a good idea. I haven't tested this but I suspect using stripHTML means this won't work if the Paragraph block contains inline formatting e.g. `<b>` and `<i>` tags.

Yeah. The block has only allowed for html since 4.9.x. For the longer time, it was just text, so they will be lots of blocks out there that will be just text. I was wonder, if it does contain html, if should be converted to a custom html block? We could do this by inverting the logic. 

```js
{
    block: 'core/html',
    widget: 'text',
    transform: ( { text } ) => ( {
	    content: text,
    } ),
    isMatch: ( { instance } ) => {
	    return ! ( stripHTML( instance.raw.text ) === instance.raw.text );
    },
},
```

**Comment by noisysocks** [comment]
The _Covert to blocks_ button accounts for all of this... I wonder if we can move that button to inside _Transforms_ so that all of this functionality is in the same place? Not sure if it's possible, but it would be the ideal UX.

**Comment by noisysocks** [comment]
Let's hold off on this until 5.8.x. RC is fast approaching and there's a workaround (the "Convert to blocks" button) that users can use.

**Comment by spacedmonkey** [comment]
> The Covert to blocks button accounts for all of this... I wonder if we can move that button to inside Transforms so that all of this functionality is in the same place? Not sure if it's possible, but it would be the ideal UX.

As a user found it very confusing and thought it was a mistake that I could not convert a text widget to a block. I honestly didn't even see that button to convert to block till my second round of testing. UX should be consistent for all blocks. Saying, "You do it differently on this one widget" is just odd to me. 

I feel like this is a shame this is not going in for release. We are going to educate users to click the transform widgets to block and their doesn't work for one of the most popular widgets out there.

**Comment by spacedmonkey** [comment]
@noisysocks What is happening with this PR?

**Comment by noisysocks** [comment]
Fully agree that we ought to converge on using the block transformations UI for all conversion of widget(s) into block(s). That said, we **must** account for that the Text widget may contain different types of content: paragraphs, images, headings, etc. Converting to a HTML block in this case is not a good UX because it assumes the user knows how to read and write HTML.

So this PR needs to try a different approach. Maybe it's possible using a block transform with a custom `__experimentalConvert` callback.

**Comment by spacedmonkey** [comment]
> Converting to a HTML block in this case is not a good UX because it assumes the user knows how to read and write HTML.

Once they convert it to a html block, couldn't they then convert it again into a series of blocks from the html block? Also, if the user has a html in the text block in the first place, it is a reason guess that do know html. How did the html get there in the first place...

**Comment by noisysocks** [comment]
I opened https://github.com/WordPress/gutenberg/pull/34610 which is similar but uses `rawHandler` so that we handle headings, images, etc. correctly.

**Comment by noisysocks** [comment]
Closing this in favour of https://github.com/WordPress/gutenberg/issues/35714 which is a new design we'd like to try.

**Pull request closed without merging**
