### PR TITLE
Update Post Author block - Support changing bio/byline sizes.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

As a follow-up to #22877 - this now allows the user to select and save the relative sizes for their byline and bio text.  Previously, these sizes were set to a fixed ratio of the standard set font size.

relative-font-sizes

## How has this been tested?

Tested between post editor, site editor, and front-end on local docker environment.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
@epiqueras - you also mentioned we should refactor to use `__experimentalUseColors` (https://github.com/WordPress/gutenberg/pull/22877#discussion_r436167890) 

Is that different than what we are currently using here?
https://github.com/WordPress/gutenberg/blob/8ac282605512cb4ee0c90973b60e1d01596df018/packages/block-library/src/post-author/edit.js#L71-L76

I was assuming there was another implementation being referred to that we would add to the "supports" field in the block.json similar to `__experimentalFontSize`, but haven't found anything similar being used elsewhere for colors.

**Comment by epiqueras** [comment]
Yes, it's `__experimentalColor`.

---

I'm not sure a UI for adjusting the relative font sizes makes sense here. This feels like something that should be handled by the theme. If we really do need the customization, perhaps the different pieces should be their own child blocks.

What do you think @mtias @youknowriad ?

**Comment by mtias** [comment]
> If we really do need the customization, perhaps the different pieces should be their own child blocks.

Agreed. We have also been staying away from using sliders for font sizes. If we want granular control over the display (color, text, etc) we should be basing it on child blocks. I think it's fine to wait a bit for that and see what themes expect to do.

**Comment by Addison-Stavlo** [comment]
>  I think it's fine to wait a bit for that and see what themes expect to do.

That sounds fair enough.  We can drop the relative sliders then, and I'l just focus on implementing the `__experimentalColor` here for now.  Thanks for the feedback!

**Comment by Addison-Stavlo** [comment]
closing this.  `__experimentalColor` will be implemented on #23044

**Pull request closed without merging**
