### PR TITLE
Improve the Interactivity API priority levels logic

### PR DESCRIPTION
**Pull request by luisherranz**
## What?

@darerodz and I have been trying to improve the logic of the priority levels implementation.

## Why?

Because we wanted to remove the `Directive` top-level component and leave only components for each priority level and also improve the overall logic:

- [x] Remove the `Directive` component.
- [x] Pass down a stable `ref` (it's broken now).
- [x] Pass all the directives to each level so directive callbacks have access to all the directives even if they are in different levels.
- [x] Don't create a `Directives` component if none of the directives present in the element are registered.
- [x] ~~See if `cloneElement` is still necessary.~~
- [x] ~~See if the recursiveness can be absorbed in the `options.vnode` hook. _Not important unless we can reduce the code size._~~

We left these tasks for later:

- [ ] Rename each priority level component so the Preact DevTools show the existing directives. For example: `Directives: bind, class`.

## How?

So far, we moved the `Directive` component logic to the `options.vnode` hook. We still need to fix the `ref`, but the tests are passing (we need tests that break the `ref`, probably with `wp-show`).

### CODE REVIEW

**Comment by luisherranz** [comment]
@darerodz and I have spent more time on this.

We're going to leave the `Rename each priority level component so the Preact DevTools show the existing directives` task for when we have a development mode because we don't want to include this logic in production, likely whenever [this PR](https://github.com/WordPress/gutenberg/pull/50122) is merged and we also [introduce `preact/debug`](https://github.com/WordPress/block-interactivity-experiments/pull/222).

The logic was mostly working, tho. We just have to create new references for the `Directives` component using `bind` and then we can assign different `displayName`s:

```js
const NextDirectives = useMemo(() => {
  const Comp = Directives.bind();
  Comp.displayName = `Directives - ${Object.keys(
    thisPriorityLevel
  ).join(", ")}`;
  return Comp;
}, []);

// ...

const children =
		restPriorityLevels.length > 0 ? (
			<NextDirectives
        // ...
```

Screenshot 2023-07-19 at 16 14 11

We still need to do it for the root `Directives` component.

**Comment by luisherranz** [comment]
This should be ready for review now.

**Review by DAreRodz — APPROVED** [review]
I think it's a great refactoring (given that I have contributed, haha 😅). Approved! ✅

PS: This is just _nitpicking_; I would have changed `thisPriorityLevel` with `currentPriorityLevel`, and `restPriorityLevel` with `nextPriorityLevel`. As the `Directive` component is iterating through all the priority levels, I feel those names are easier to understand. But there's not need to change them―it's just a feeling. 🤷

**Comment by luisherranz** [comment]
> I would have changed `thisPriorityLevel` with `currentPriorityLevel`, and `restPriorityLevel` with `nextPriorityLevel`.

I like that. I'll change it before merging.

**Comment by luisherranz** [comment]
> We're going to leave the `Rename each priority level component so the Preact DevTools show the existing directives` task for when we have a development mode because we don't want to include this logic in production, likely whenever [this PR](https://github.com/WordPress/gutenberg/pull/50122) is merged and we also [introduce `preact/debug`](https://github.com/WordPress/block-interactivity-experiments/pull/222).

If I'm not mistaken, `SCRIPT_DEBUG` is finally available in Gutenberg, so we can try to add this.

- https://github.com/WordPress/gutenberg/pull/50122

**Pull request merged**
