### PR TITLE
Use an expandable panel for the post schedule component

### PR DESCRIPTION
**Pull request by youknowriad**
related https://github.com/WordPress/gutenberg/pull/3036#issuecomment-337178253

This updates the design of the publish dropdown and also fixes the double popover issue.

screen shot 2017-10-18 at 09 45 46

### CODE REVIEW

**Comment by jasmussen** [comment]
Love it, works great! Thank you for working on this.

I noticed one thing — if you have the publish dropdown open while the autosave kicks in, you get this type of publish button:

screen shot 2017-10-18 at 10 53 08

The easy fix is to just make sure it has the same disabled style as the publish dropdown button itself has when autosaving. This is probably fine since it's arguably an edgecase.

Separately we _could_ explore making it so the publish dropdown button is _never_ disabled, and clicking it also fires off an "autosave" action. Inside this dropdown, the publish button could then be disabled or not depending on what's going on.

**Comment by youknowriad** [comment]
@jasmussen this is a weird `z-index` issue. The background of the button when it has the `is-saving` class is hidden but I'm having a hard time figuring out how to fix it.

**Comment by jasmussen** [comment]
Looking.

**Comment by jasmussen** [comment]
I pushed a fix and some polish to it.

Is the fix kosher? https://github.com/WordPress/gutenberg/pull/3045/commits/24fbc63c328320d67e3130d724feb85286954f8e#diff-7363cc87fd41746921197fe81967c3fdR27

**Comment by youknowriad** [comment]
Nice works great thanks for the fix 👍

**Comment by jasmussen** [comment]
Change looks good! 👍 👍

**Pull request merged**
