### PR TITLE
Screen takeover without any use of modals

### PR DESCRIPTION
**Pull request by maartenleenders**
## Description
This is one version of the screen takeover, this time using no modals at all. Instead, we return early from the render function in `layout.js` when a `screenTakeoverName` is set. When plugin developers create a plugin, they can fill the screen takeover slot ( `PluginScreenTakeover.Slot` ) with content. The slot is prefilled with a header that takes a lot of inspiration from the toolbar header. The an svg icon and a title can be passed to the header, and it has a closing cross (see screenshots).

## How has this been tested?
I've tested the code by using @Xyfi 's [gutenberg-api-tester plugin](https://github.com/Xyfi/gutenberg-api-test). 

## Screenshots
Using @Xyfi's plugin:
image

The screen takeover follows @jasmussen 's (initial) designs and looks as follows:
image

I've noted that when testing with a large post (like the Gutenberg demo post), the experience of closing the screen takeover is a bit rough. It opens and closes quick enough, but it takes a while for the post to be fully loaded again.

**NB** I have yet to write tests, will add a.s.a.p.

## Types of changes
Try for an enhancement that will increase the space plugin developers have to render their content. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by maartenleenders** [comment]
I've tried both, the problem with visibility hidden was that there is still a height somewhere in the layout (so it was not just the screen takeover that was visible, also a large white area that caused scrolling behavior). Might be due to my rusty CSS though.

On the plus side, `display: none` does seem to remember place, so I went with that.

**Comment by maartenleenders** [comment]
_sorry about switching the bases_
@jasmussen Thanks for explaining. So, we can make both options work.
Since `display: none` meets all the requirements already, do I still need to try the `visibility: hidden` approach?

**Comment by jasmussen** [comment]
> Since display: none meets all the requirements already, do I still need to try the visibility: hidden approach?

Depends on whether it lets you keep your place in the text.

Try a really long document, like the demo content. Scroll to the bottom. Then invoke the screen takeover, then close it. You should still be scrolled to the bottom.

**Comment by jasmussen** [comment]
> So that is indeed the case.

Sorry, I'm slow today — is it the case that the scroll position is _restored_, or are you scrolled to the top, when you close the modal?

I just tried checking out this branch and building, and also installed and built the cool API checker plugin. Alas for whatever reason (perhaps I npm run build't the plugin wrong?) I couldn't get any options to show up in the more menu. So I haven't been able to test this myself.

**Comment by maartenleenders** [comment]
Sorry, I messed up the commit history by rebasing wrong remotes and what not.

Cherry picked and made a new PR:
https://github.com/WordPress/gutenberg/pull/6416

**Pull request closed without merging**
