### PR TITLE
Upgrade Gradle to 7.4 & AGP to 7.1.1 (& Disable Jetifier)

### PR DESCRIPTION
**Pull request by ParaskP7**
Related PR: #39508 (updated)

## Description

This PR upgrades all react-native Android libraries to `Gradle 7.4 & AGP 7.1.1`.

It includes the following:
- `Gradle` version upgraded to `7.3.3` with the `./gradlew wrapper --gradle-version=7.3.3 --distribution-type=all` command.
- `AGP` version upgrade to `7.0.4` (see `android/settings.gradle.kts` change).
- Build output diff:
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- Lint output diff
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- The above 4 steps were redone with a follow-up update to `Gradle 7.4` & `AGP 7.1.1`.
- The above `Gradle 7.4 & AGP 7.1.1` upgrade was done for the main 3 react-native libraries:
  - [x] `react-native-aztec`
  - [x] `react-native-bridge`
  - [x] `react-native-editor`
- Also, in addition to the above, the below 13 react-native `wp-fork` libraries were upgrades to `Gradle 7.4 & AGP 7.1.1` as well:
  - [x] [react-native-linear-gradient](https://github.com/wordpress-mobile/react-native-linear-gradient/pull/6) + [react-native-hsv-color-picker](https://github.com/wordpress-mobile/react-native-hsv-color-picker/pull/7)
  - [x] [react-native-svg](https://github.com/wordpress-mobile/react-native-svg/pull/17)
  - [x] [react-native-video](https://github.com/wordpress-mobile/react-native-video/pull/18)
  - [x] [react-native-slider](https://github.com/wordpress-mobile/react-native-slider/pull/11)
  - [x] [react-native-get-random-values](https://github.com/wordpress-mobile/react-native-get-random-values/pull/6)
  - [x] [react-native-masked-view](https://github.com/wordpress-mobile/react-native-masked-view/pull/7)
  - [x] [react-native-gesture-handler](https://github.com/wordpress-mobile/react-native-gesture-handler/pull/12)
  - [x] [react-native-screens](https://github.com/wordpress-mobile/react-native-screens/pull/7)
  - [x] [react-native-safe-area-context](https://github.com/wordpress-mobile/react-native-safe-area-context/pull/10)
  - [x] [react-native-reanimated](https://github.com/wordpress-mobile/react-native-reanimated/pull/9)
  - [x] [react-native-prompt-android](https://github.com/wordpress-mobile/react-native-prompt-android/pull/8)
  - [x] [react-native-webview](https://github.com/wordpress-mobile/react-native-webview/pull/6)
  - [x] [react-native-clipboard](https://github.com/wordpress-mobile/react-native-clipboard/pull/2)
- 13 (see above) react-native `wp-fork` libraries were updated to point to temporary coordinates, which contain the above `Gradle 7.4 & AGP 7.1.1` upgrades. This is done for testing/verification purposes before merging the individual react-native `wp-fork` libraries and creating new tags.
- 13 (see above) react-native `wp-fork` libraries were update to point to new tags, which contains the above `Gradle 7.4 & AGP 7.1.1` upgrades. ⚙️

Related [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4652 
Related [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) PR: [Upgrade Gradle to 7.4 & AGP to 7.1.1 #15865](https://github.com/wordpress-mobile/WordPress-Android/pull/15865) (for manual testing purposes)

## Testing Instructions

Manual testing of the react-native demo `Editor` and main `WPAndroid` app that include these changes.

## Screenshots 

N/A

## Types of changes

Android build file changes for react-native projects & react-native library updates for Android projects.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by fluiddot** [comment]
@ParaskP7 I created the following branch [`rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4`](https://github.com/ParaskP7/gutenberg/compare/update/gradle-to-7.3.3-agp-to-7.0.4...WordPress:rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4) for testing these changes. As you can see in the changes, for fetching the Android artifacts, I'm using the version `update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT`, except for the package `react-native-screens`, which for some reason the artifact was published with the commit SHA 🤷‍♂️ .

In any case, I'm getting the following error when building:
```
Duplicate class com.swmansion.common.GestureHandlerStateManager found in modules react-native-gesture-handler-update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT-runtime (com.github.wordpress-mobile:react-native-gesture-handler:update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT:1bd872fcd9-1) and react-native-reanimated-update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT-runtime (com.github.wordpress-mobile:react-native-reanimated:update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT:1.9.0-g734d446-847)
```

This error is probably the same that I'm trying to fix in https://github.com/WordPress/gutenberg/pull/39430#issuecomment-1068202722. So, once I merge https://github.com/wordpress-mobile/react-native-gesture-handler/pull/18, I'll update everything again.

**Comment by ParaskP7** [comment]
👋 @fluiddot !

Thank you so much for the update and working on this! 🙇 

> @ParaskP7 I created the following branch [rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4](https://github.com/ParaskP7/gutenberg/compare/update/gradle-to-7.3.3-agp-to-7.0.4...WordPress:rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4) for testing these changes. As you can see in the changes, for fetching the Android artifacts, I'm using the version update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT, except for the package react-native-screens, which for some reason the artifact was published with the commit SHA 🤷‍♂️ .

👀 

> In any case, I'm getting the following error when building:
> 
> `Duplicate class com.swmansion.common.GestureHandlerStateManager found in modules react-native-gesture-handler-update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT-runtime (com.github.wordpress-mobile:react-native-gesture-handler:update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT:1bd872fcd9-1) and react-native-reanimated-update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT-runtime (com.github.wordpress-mobile:react-native-reanimated:update~gradle-to-7.3.3-agp-to-7.0.4-SNAPSHOT:1.9.0-g734d446-847)`

🤔 

> This error is probably the same that I'm trying to fix in https://github.com/WordPress/gutenberg/pull/39430#issuecomment-1068202722. So, once I merge https://github.com/wordpress-mobile/react-native-gesture-handler/pull/18, I'll update everything again.

👍 🤞

**Comment by fluiddot** [comment]
@ParaskP7 I finally merged the fix for `react-native-gesture-handler`, and now I'm able to build the demo app with branch [rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4](https://github.com/ParaskP7/gutenberg/compare/update/gradle-to-7.3.3-agp-to-7.0.4...WordPress:rnmobile/try/gradle-to-7.3.3-agp-to-7.0.4). I'll try to spare some time today for smoke testing the changes 🤞 .

**Comment by ParaskP7** [comment]
This draft PR is now closed in favor of the newest and more up-to-date #39508 PR.

**Pull request closed without merging**
