### PR TITLE
Cherry pick PRs for inclusion in WP 6.1 RC-2

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is the PR to cherry-pick the Gutenberg changes for the WordPress 6.1 RC-2 release. The base of this PR is `wp/6.1`.

These are the commits/PRs that are being included here:

8a00f6a963 for PR: #45041 – Font Size Picker Hint: Fallbac...
9ad568e78a for PR: #45045 – Add: Missing output escaping o...
56c871a01d for PR: #44999 – Escape comment author URL
a68fa58705 for PR: #44972  – Navigator: restore focus only ...
346ff74d91 for PR: #44858 – Spacing Sizes Control: Try imp...
6ef0ed8735 for PR: #44878 – Fix: Inspector is usable on th...
a5efd9dd6d for PR: #44809 – Fix list outdents on Enter in ...
1736a08efd for PR: #44864 – List v2: fix selection when cr...
5f1a635603 for PR: #44853 – Fix overflowing patterns
25d2b4c906  for PR: #45050 – Fix visibility of nested Group...
8048ef8 for PR: #44887 – wp-env: Use case insensitive regex...

### CODE REVIEW

**Comment by ockham** [comment]
[PHP unit tests](https://github.com/WordPress/gutenberg/actions/runs/3269800883/jobs/5377723573#step:7:12) and [e2e tests](https://github.com/WordPress/gutenberg/actions/runs/3269800878/jobs/5377723399) are currently failing because of a missing WP git tag (during wp-env setup I believe):

```
✖ fatal:  couldn't find remote ref refs/tags/6.1-RC1-54629
```

It looks like the tip of `wp/6.1` has had [a similar issue](https://github.com/WordPress/gutenberg/actions/runs/3269643907/jobs/5377375731) (albeit for a different commit ID):

```
✖ fatal: couldn't find remote ref refs/tags/6.1-RC1-54541
```

**Comment by ockham** [comment]
This is the full stacktrace found in CI logs:

```
GitError: fatal: couldn't find remote ref refs/tags/6.1-RC1-54541

    at Object.action (/home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:1194:25)
    at PluginStore.exec (/home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:[12](https://github.com/WordPress/gutenberg/actions/runs/3269643907/jobs/5377375731#step:5:13)29:29)
    at /home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:[15](https://github.com/WordPress/gutenberg/actions/runs/3269643907/jobs/5377375731#step:5:16)89:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:1587:[16](https://github.com/WordPress/gutenberg/actions/runs/3269643907/jobs/5377375731#step:5:17))
    at GitExecutorChain.<anonymous> (/home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:1571:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/gutenberg/gutenberg/node_modules/simple-git/dist/cjs/index.js:55:24) {
  task: {
    commands: [ 'fetch', 'origin', 'tag', '6.1-RC1-54541', '--depth', '1' ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
```

Looks like the command might be coming from here: https://github.com/WordPress/gutenberg/blob/bf4eddb29f4c23ce841076b63035350866e81bfe/packages/env/lib/download-wp-phpunit.js#L130

I think the `wpVersion` arg comes from a list of WP versions that is originally built by `readWordPressVersion` -- which reads from `wp-includes/versions.php` (in `~/.wp-env`'s individual subdirs, e.g. `tests-WordPress` or `tests-WordPress-PHPUnit`): https://github.com/WordPress/gutenberg/blob/bf4eddb29f4c23ce841076b63035350866e81bfe/packages/env/lib/wordpress.js#L241-L272

It doesn't seem like there are actually any tags like `6.1-RC1-54541` -- neither in git nor in svn 🤔 

cc/ @noahtallen for `wp-env` expertise.

**Comment by ockham** [comment]
Ah, looks like we actually have code to deal with pre-releases (alpha, beta, RCs):

https://github.com/WordPress/gutenberg/blob/bf4eddb29f4c23ce841076b63035350866e81bfe/packages/env/lib/download-wp-phpunit.js#L121-L131

Seems like we "just" need to tweak the RegEx to understand this kind of RC version format.

**Comment by ockham** [comment]
> Seems like we "just" need to tweak the RegEx to understand this kind of RC version format.

Let's make it case-insensitive then, shall we?

```diff
diff --git a/packages/env/lib/download-wp-phpunit.js b/packages/env/lib/download-wp-phpunit.js
index 923750d58b..3900fd9495 100644
--- a/packages/env/lib/download-wp-phpunit.js
+++ b/packages/env/lib/download-wp-phpunit.js
@@ -122,7 +122,7 @@ async function downloadTestSuite(
        // Alpha, Beta, and RC versions are bleeding edge and should pull from trunk.
        let ref;
        const fetchRaw = [];
-       if ( ! wpVersion || wpVersion.match( /-(?:alpha|beta|rc)/ ) ) {
+       if ( ! wpVersion || wpVersion.match( /-(?:alpha|beta|rc)/i ) ) {
                ref = 'trunk';
                fetchRaw.push( 'fetch', 'origin', ref, '--depth', '1' );
        } else {
```

**Comment by ockham** [comment]
Heh, looks like that change is already in `trunk`: https://github.com/WordPress/gutenberg/pull/44887 😅 

So I guess I'll revert my 8f05087 and will instead just cherry-pick that PR.

**Comment by noahtallen** [comment]
Right on!

**Pull request merged**
