### PR TITLE
Scripts: Add missing root flag to the default Eslint config

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Extracted from #13394 based on a suggestion from @aduth:
https://github.com/WordPress/gutenberg/pull/13394/files#r249797548

This PR adds missing `root` flag in the default ESlint config which works as explained in the docs (https://eslint.org/docs/user-guide/configuring):

> By default, ESLint will look for configuration files in all parent folders up to the root directory. This can be useful if you want all of your projects to follow a certain convention, but can sometimes lead to unexpected results. To limit ESLint to a specific project, place `"root": true` inside the `eslintConfig` field of the `package.json` file or in the `.eslintrc.*` file at your project’s root level. ESLint will stop looking in parent folders once it finds a configuration with `"root": true`.

## Testing

Not sure how to test with the recent configs added which depend on the `.eslintrc.js` in the root folder. Otherwise I would remove it and check whether `npm run lint-js` works.

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
Trying to test this, I still see that ESLint will inherit rules from parent directories.

I think we need to use--either instead of or in addition-- the `--no-eslintrc-js` parameter when falling back to the default-provided configuration.

https://eslint.org/docs/user-guide/command-line-interface#--no-eslintrc

Here:

https://github.com/WordPress/gutenberg/blob/c153cc46f94a36b774ea21d88f05a53716d03922/packages/scripts/scripts/lint-js.js#L30

To:

```js
[ '--no-eslintrc', '--config', fromConfigRoot( '.eslintrc.js' ) ] :
```

**Review by aduth — APPROVED** [review]
Added the proposed change. Feel free to merge if it makes sense to you.

**Comment by gziolo** [comment]
I see this line in ESlint docs and it suddenly makes everything clear:

> If `.eslintrc.*` and/or `package.json` files are also used for configuration (i.e., `-no-eslintrc` was not specified), the configurations will be merged. Options from this configuration file have precedence over the options from `.eslintrc.*` and `package.json` files.

Thanks for catching it. I didn't think about configs located outside of the project at all. Never stop learning :)

**Comment by gziolo** [comment]
Kudos @aduth for changes applied 🥇 

I will merge as soon as Travis will turn green.

**Pull request merged**
