### PR TITLE
Avoid rerenders of the entire BlockInspector when block attributes change

### PR DESCRIPTION
**Pull request by adamziel**
## Description
`BlockInspector` uses `useSlot( InspectorAdvancedControls.slotName )`. Whenever any fill is updated, the entire BlockInspector is re-rendered. This causes performance problems like the ones described in https://github.com/WordPress/gutenberg/pull/21973. This PR extracts the `InspectorAdvancedControls` fills into a sub-component to avoid re-rendering the entire inspector.

## How has this been tested?
For some reason, my react dev tools fail to capture the re-render of `BlockInspector`. This makes testing a little bit harder, but not impossible:

1. Start without applying this PR
1. Add `console.log("BlockInspector rendered")` as a first statement in the `BlockInspector` component
1. Open post editor and add a navigation block with some menu items.
1. Select the entire block and change the background.
1. Confirm that `BlockInspector rendered` was logged about 10 times.
1. Apply this PR and keep the console.log in place
1. Repeat steps 3-4
1. Confirm that `BlockInspector rendered` was not logged in response to changing the background

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by adamziel** [comment]
@youknowriad This PR combined with #21973 fixes the performance issue even without the `memo()` call. I'll trust your judgement here and remove the memo if you think it's worth it. Just to reiterate - my personal opinion is that memo() is still worth having. I see it as buying an insurance against accidentally updating `<BlockInspector />` in a way that would restore re-renders - and our premium is wrapping `<BlockStyles />` in `memo()` . Personally I think it's quite easy to add another hook to BlockInspector without considering the impact on `<BlockStyles />` - and this have real UX consequences for one of the core blocks as seen in #21973. At the same time, `<BlockStyles/>` seems unlikely to become rendered dozens/hundred of times in a single tree so the performance impact of `memo()` should be marginal, even if it ends up being redundant.

**Comment by youknowriad** [comment]
@adamziel Thanks for your work, these improvements are great. I'll take a look at this PR a bit later but keeping "memo"  is totally fine. 

Good point about BlockStyles being expensive, that said, I wonder if the expensive component is actually BlockPreview used by BlockStyles and not BlockStyles itself so I wonder whether we should move the "memo" there.

**Comment by adamziel** [comment]
Thank you!

> I wonder if the expensive component is actually BlockPreview used by BlockStyles and not BlockStyles itself so I wonder whether we should move the "memo" there.

@youknowriad Good point! I'll merge #21973 and spin a new PR for that.

**Review by youknowriad — APPROVED** [review]
I didn't really test the performance impact here but the changes look good regardless.

**Comment by adamziel** [comment]
Awesome, thank you so much! Also, that new PR to `memo()` BlockPreview is available here: https://github.com/WordPress/gutenberg/pull/21993

**Pull request merged**
