### PR TITLE
Fix issue with customizer title overlapping block toolbar

### LINKED ISSUE #32060: Remove scroll behavior on the Customizer description container in Customizer Widgets screen
Hi all, this bug has been spotted in a few different places like #31589 and https://github.com/WordPress/gutenberg/issues/30912#issuecomment-844689897 but splitting it off until it's own issue so it doesn't get lost 😁

Resolving this should get us a step closer towards implementing a solution like the one proposed in #32061

https://user-images.githubusercontent.com/77359364/119009689-64db6c00-b961-11eb-9fc7-6743ad87ebea.mov

I think we should remove the reappear-on-reverse-scroll that is currently applied to the Customizer description container. It's conflicting with the floating block toolbar, which anchors itself to the top of the scroll container while the selected block is passing in or out of view. It also causes issues with the fixed toolbar option, causing the fixed toolbar to lose stickiness and get knocked back into its default position at the top of the editor when scrolling from bottom to top.

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #32060

Adds some CSS to override the 'sticky' title behavior in the widgets block editor part of the customizer.

I looked through the customizer codebase in WordPress core, and couldn't see an options to disable the sticky title. Its inline styles are set using a bunch of JavaScript. As we're now in the feature freeze period, it seems best to fix this in a low impact fashion, but in the long run there are some options:
- Make the sticky title feature configureable for each customizer section.
- Make the widget editor use `position: sticky` styling instead of the custom implementation it has now.

## How has this been tested?
1. Open the customize widgets editor
2. Add enough blocks until you get a decent sized scrollbar.
3. Select a block near the top so that the block toolbar shows
4. Scroll up and down a reasonable distance
5. The title of the customizer sizebar should never overlap the block toolbar (see the issue in the video for an example.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by tellthemachines — APPROVED** [review]
The fix is working well, and I think it's the best way to handle the issue considering where we are in the release cycle. The only thing I'm worried about is this might degrade the experience for mobile users, who will have to scroll all the way back up to move to another customizer section. But given we don't know how common a use case editing multiple sections on a phone is (I'd imagine not very), perhaps we can add it in and then revert if folks complain about it 😅

**Comment by talldan** [comment]
Yeah, I agree it's not ideal, but I feel a reasonable trade-off. The covering of the block toolbar is probably a more frustrating issue. Thanks for the review.

**Comment by critterverse** [comment]
Nice. Thanks @talldan!

**Comment by youknowriad** [comment]
Cherry-picked into 10.7 release branch.

**Pull request merged**
