### PR TITLE
Docgen: Add @typedef and @property tags

### PR DESCRIPTION
**Pull request by Copons**
## Description

* Add support for `@typedef` and `@property` tags.
* Fix the markdown of the SETTINGS_DEFAULT section in the Block Editor package readme.

## Screenshots

| Before | After |
| - | - |
| Screenshot 2019-10-22 at 13 51 03 | Screenshot 2019-10-24 at 16 44 41 |

## Types of changes

Bug fix

### CODE REVIEW

**Comment by ellatrix** [comment]
@Copons I think the readme file is automatically created. Perhaps the source should be updated?

**Comment by Copons** [comment]
> @Copons I think the readme file is automatically created. Perhaps the source should be updated?

Oh damn! I had no idea! 🤦‍♂ 

Coming up with a new approach ASAP then!

**Review by ellatrix — APPROVED** [review]
Looks good, though would appreciate an extra check from @nosolosw for the doc generation changes.

**Comment by nosolosw** [comment]
I think we can go ahead with this.

Some thoughts:

- I've never seen `@typedef` being used within a declaration, but always as a [standalone](https://jsdoc.app/tags-typedef.html) statement. Reading the JSDoc manual, I'm actually unsure how we're suppose to document objects. Using the `property` tag alone should be fine and `typedef` not required, but it's also natural to have the type definition within the object that first declares it.

- Note that a task to add support for `typedef` already existed at https://github.com/WordPress/gutenberg/issues/15186 It was more concerned with pulling the existing type definitions than this change, so I've updated the title to reflect better what it tracks.

**Comment by Copons** [comment]
@nosolosw To be honest, adding support for `@typedef` wasn't in my initial intentions.
But when I've built the docs with `@property`, I've noticed the [`WPEditorInserterItem` changes](https://github.com/WordPress/gutenberg/pull/18059/files#diff-620f753a8404682f22b2be4f45d6eb3c), and they didn't really make much sense in the output readme without the `@typedef` giving a context to the `@property` list.

Now, this PR only takes into account the `@typedef` inside a function docs (I think?), but doesn't work for all those outside (e.g. [this](https://github.com/WordPress/gutenberg/blob/f8b62bd29fc83972256d7b2315dee2341af06cc1/packages/block-editor/src/store/selectors.js#L32-L40) in the same file as `WPEditorInserterItem`).

I think that since this change doesn't really affect them, we could tackle those in a follow up though.

**Review by vindl — APPROVED** [review]

**Pull request merged**
