### PR TITLE
Block Editor: Fix is-hovered event listener

### PR DESCRIPTION
**Pull request by jeyip**
## Description

Potentially addresses https://github.com/WordPress/gutenberg/issues/27296

We were seeing strange behavior when applying and removing the `is-hovered` class

hovered

hovered-2

I couldn't pinpoint the exact problem, but after lots of experimentation, the odd mouseover behavior seems to be the result of race conditions. Instead of assigning hover listeners a single time to each block, we were inadvertently reassigning them over and over again whenever we hovered a block. See the `isHovered` prop from line 60 of the code block below:

https://github.com/WordPress/gutenberg/blob/bd270f35fca4eddebb49e71af98c177469dda22e/packages/block-editor/src/components/block-list/use-block-props/use-is-hovered.js#L36-L60

In practice, the flow of logic would look like this:
- On initial render, a block element would be assigned a `mouseover` event listener
- When a user would hover over the block, a `mouseout` event listener would be assigned as well
- Upon moving the cursor outside of the block, the `mouseover` event listener would be assigned again
- When a user would hover over the block again, another `mouseout` event listener would be assigned

I refactored the hover logic to ensure that hover event listeners are assigned once on initial load, and re-assigned only when `isOutlineMode` and `isNavigationMode` changes

## How has this been tested?

1. Open the site editor
2. Hover over a navigation block with navigation links
3. Ensure that only the block being hovered has an outline
4. Hover over column and columns blocks
5. Ensure that only the block being hovered has an outline
6. Hover over an image placeholder
7. Ensure that the blue outline around the placeholder doesn't flicker while mousing over its child elements
8. Smoke test other blocks and ensure that hover behaves as expected

## Types of changes

Bug Fix

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jameskoster** [comment]
Well, this solves one issue, but introduces another 🙈

The desired effect in the Site Editor is that only the block being hovered has an outline. 

This does fix the weirdness where you can hover over a block and see an outline, then move the cursor _within that same block_ and find that the outline disappears. (IE the navigation issue in #27296).

But having all the parents exhibit an outline _as well_ is confusing.

**Comment by jeyip** [comment]
> The desired effect in the Site Editor is that only the block being hovered has an outline.

Yeah -- [I mentioned this earlier](https://github.com/WordPress/gutenberg/issues/27296#issuecomment-772971667), but I wasn't entirely sure if this change made the experience better or worse. It sounds like the behavior is definitely undesired, so I'll continue refining what I have here. 👍

**Comment by jeyip** [comment]
The PR should be a lot more in line with expected hover behavior. There are still some odds and ends to wrap up, like a strange runtime warning -- I'll look into it more tomorrow.

**Comment by jeyip** [comment]
@jameskoster Ready for another round of testing 👍

**Comment by jameskoster** [comment]
Yesss! This is so much better :) It works exactly as expected from the design perspective.

**Review by Copons — APPROVED** [review]
WFM!

I think there still are some wrinkles, but design review is good, and I'm cool with this codewise, so... 🚢

**Comment by jasmussen** [comment]
Thanks so much for working on this.

I'm not sure if this is related at all, but in the site editor if you mouse over a spacer block, the gray blob is shown. See https://github.com/WordPress/gutenberg/pull/28129

This doesn't work in the post editor. I could swear it used to, but I'm not convinced. But looking at it, it looks like the Spacer block does not have an `is-hovered` class at all in the post editor — is that intended? Thanks for helping me with my debugging here.

**Comment by jeyip** [comment]
Hi @jasmussen! I'll try debugging a little bit.

**Comment by jeyip** [comment]
@jasmussen I loaded [this Gutenberg master commit](https://github.com/WordPress/gutenberg/commit/1a29dbdecb6222a62ff66fa1eb5e3bb66ede44a4), which does not include the hover event changes in this PR. It looks like the issue you're describing already existed in master :(

I'll try and bisect the post editor space block problems before the end of the day. If not, I'll take a look sometime tomorrow or later this week.

**Comment by jasmussen** [comment]
Thank you for looking. Don't spend an ocean of time on it, I did not mean to give you the blame for a feature, just figured it might be related. I'm happy to open a ticket instead and we can let anyone pick it up.

**Comment by jeyip** [comment]
> Thank you for looking.
Of course!

> Don't spend an ocean of time on it, I did not mean to give you the blame for a feature, just figured it might be related.
No worries at all. Thanks for taking the time to point out these issues -- they definitely detract from the quality of the user experience and are important to address. In any case, I was just planning to debug during pockets of free time. Hopefully it's a quick fix 🤞 

> I'm happy to open a ticket instead and we can let anyone pick it up.
I can take care of it 🙂

**Pull request merged**
