### PR TITLE
Framework: Move store files into state directory

### PR DESCRIPTION
**Pull request by aduth**
Iterative progress toward #3012

This pull request seeks to move editor state behaviors into a new state directory. This directory will encompass all state behaviors per the modularity approach proposed in #3012. The changes included merely move the state directory and update all references therein. I debated whether subsequent module splitting should be included in these changes, but decided the potential for merge conflicts was too high to sustain.

__Testing instructions:__

Verify that the editor builds and runs without any errors.

__Follow-up Tasks:__

We should be careful to find and update any current branches / pull requests which add to or reference state after these changes are merged.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by gziolo** [comment]
Merge conflicts need to be resolved and it should be good to go 👍

**Review by gziolo — APPROVED** [review]

**Comment by aduth** [comment]
I'll plan to land this one after the next release.

**Comment by aduth** [comment]
Rebased and... well, decided to adopt the Ducks pattern here and now. This is now a monster of a pull request and we should decide sooner than later if we want to move on it, as conflicts will become increasingly likely. Its only saving grace is that while I split features, I kept a master reference of `selectors` and `actions` from which to import. This may end up being more convenient anyways, particularly for when we decide to expose selectors for plugin usage. We can obviously decide to move away from this if desired. Similarly, I did not do anything to touch effects quite yet, and will leave for future changes.

Ultimately the Ducks modules ended up being:

- `blockInsertionPoint`
- `blockSelection`
- `blocksMode`
- `currentPost`
- `editor`
- `hoveredBlock`
- `isTyping`
- `metaBoxes`
- `notices`
- `panel`
- `preferences`
- `reusableBlocks`
- `saving`
- `ui`

**Review by jorgefilipecosta — APPROVED** [review]
I'm not totally inside the motivations of this change. But I checked the code and the pattern applied in this refactor seems fine, I think this makes our codebase more scalable and easier to work in parallel in different features. I did an extensive set of tests in this branch and I did not found a regression so I'm approving it 
 👍  Nice work handling a huge change like this!

A fear I have is with time we may create huge "ducks" and even bigger "ducks" test files. Would a pattern like editor/state/meta-boxes/{actions, reducer, selectors}.js instead of editor/state/meta-boxes.js following the same rules in the "ducks" pattern but with artifacts separated in files be an option? I think this pattern is similar to what happens in wp-calypso.

**Comment by aduth** [comment]
>Would a pattern [...] following the same rules in the "ducks" pattern but with artifacts separated in files be an option? I think this pattern is similar to what happens in wp-calypso.

Yeah, I never had an initial appreciation for how similar Ducks is to the pattern we introduced to Calypso, but in implementing it here, there is certainly significant overlap, with the main difference being that Ducks places more emphasis on the reducer as the default export of a module (maybe equivalent to a `{subject}/index.js`). Personally I am open to this, but it does increase the sprawl of state, and wouldn't be too difficult to introduce later if we wanted (at least imports could stay the same).

**Comment by gziolo** [comment]
I had to do some research what Ducks pattern is, but as soon as I learned about it I'm fine with the proposed approach. It also seems to be reasonable to keep two global entry points for actions and  selectors. It is much easier to have one place to import things that scan all subfolders for every method. It also ensures that we won't use the same names for different things. Let's rebase and proceed with this one. Next step would be to find a way to make Redux state extensible :shipit:

**Comment by aduth** [comment]
I'll try to rebase to keep this up-to-date, but I'm beginning to question some of the value here. In particular, subject-based selectors can be confusing to implement, since something like `getDocumentTitle` doesn't fit nicely into an existing subject (implemented in `state/ui` without any reducer of its own) and `getEditedPostValue` uses values from multiple state subtrees (both `state.editor` and `state.currentPost`). I think we'd also want to settle on whether a consumer would want to import from `state/selectors` or the subject-specific `state/foo`.

**Comment by gziolo** [comment]
In case of `selectors` I'd be personally happy about having them all in one file as it is at the moment. The file itself can grow big with the time, but we can fix that later. Less choice for the consumers of Redux state equals more consistent way of importing things. We can decide later what to do about actions as it might be a better idea to go the opposite and encourage to import directly from the namespace.

**Review by dmsnell — COMMENTED** [review]
No idea how to even begin reviewing this; sorry 🤷‍♂️ 

I'm mostly dispassionate about it though I encourage grouping functions into fewer files just because of issues with JavaScript.

Please let me know if there are specific ways I can be of assistance here!

**Comment by gziolo** [comment]
I think it's no longer relevant and a bit outdated :)

**Comment by aduth** [comment]
>I think it's no longer relevant and a bit outdated :)

Indeed!

The ducks pattern is still interesting, though added equal parts clarity and confusion; clarity in creating separation where it clearly exists, confusion in things such as selectors or effects which operate on state as a whole.

**Pull request closed without merging**
