### PR TITLE
Run Mocha on Webpack-generated bundle

### PR DESCRIPTION
**Pull request by aduth**
Continuing attempt to enable accurate testing on a Webpack-generated bundle (previously https://github.com/WordPress/gutenberg/pull/289#issuecomment-287480998, #303, https://github.com/WordPress/gutenberg/pull/301#issuecomment-288646926 ).

This pull request updates the Webpack configuration to create a separate testable bundle when `NODE_ENV=test`. This allows us to test files which include loaders like the `pegjs-loader` introduced in #301.

### CODE REVIEW

**Comment by nylen** [comment]
Why the move from `registration.js` back to `index.js`? (I also missed where this was moved in the first place.)

**Comment by aduth** [comment]
`registration.js` was only moved away from `index.js` #301 as a workaround to sorts that the tests previously failed when trying to import `index.js` (because of the `.pegjs` import).

**Comment by nylen** [comment]
Ahh I see. I haven't tested it yet but I support the approach here. Can we merge #308 first?

**Review by youknowriad — APPROVED** [review]
I suspect this to be a bit slower, but definitely better to have a unique build workflow

**Comment by aduth** [comment]
Rebased and found there was some issue with Chai plugins not being respected. Updated to reincorporate the bootstrap file, working well again. Will merge after CI passes.

**Pull request merged**
