### PR TITLE
Prompt to keep or replace Featured Image when replacing Image block media that is set as the Featured Image

### LINKED ISSUE #34429: Mobile: Prompt to keep or replace Featured Image when replacing Image block media that is set as the Featured Image
## What problem does this address?
This enhancement request builds on the work done to implement a "set as featured" button in the image block's settings in wordpress-mobile/gutenberg-mobile#1011.

After setting an Image block as the post's Featured Image, if one replaces the media for that Image block, there is a disconnect as to what occurs to the post's Featured Image. Currently, taking this action causes the original image to _remain as the Featured Image_, even though the media is no a part of the post content. While this outcome could be perceived as correct, it could also cause confusion if the user expects the Featured Image to update as well. 

## What is your proposed solution?

From team discussions, the first thought was that we should default to maintaining the “featured” status even after an image is replaced, but upon further digging we think our suggestion would be to give the option to do one of the following—either:

1. **Keep the current featured image** (“detach” the image block’s connection with the featured status), or
1. **Replace the current featured image** (apply the new image as the featured image)

In theory, that part of the flow could look like this:

featured-image-block-replace-media-flow

In this example, the top row is what you’d see in the editor UI, on canvas. The bottom row is the featured image setting “behind the scenes”.

### Alert/Dialog messaging

We noticed that we already have an ActionSheet implemented that shows a similar message when a user has an existing featured image and tries to apply an image as featured from an Image block’s settings—we can probably re-use that Alert/Dialog in this part, but suggest we refine the messaging a little bit to something like the following:

* Alert/dialog title: `Replace current featured image?`
* Alert/dialog body: `You already have a featured image set. Do you want to replace it with the new image?`
* Action 1: `Keep current featured image`
* Action 2: `Replace with new image`

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/wordpress-mobile/gutenberg-mobile/pull/3930
* https://github.com/wordpress-mobile/WordPress-iOS/pull/17132
* https://github.com/wordpress-mobile/WordPress-Android/pull/15303

## Description
Fixes #34429. If an Image block is set as the post's Featured Image, replacing the Image block's media will prompt the user as to whether they want to replace the Featured Image as well. 

## How has this been tested?

⚠️ Part of the changes in this PR focus specifically on images that need to be uploaded to the site (e.g. from a free image service), as they operate differently than images already found within the site's Media Library. So, it is likely a good idea to test a few different paths to replacing the Image block media. 

### Scenarios

- Uploading a new image from device...
- Selecting an existing image within the Media Library... 
- Switching between _the same_ two images within the Media Library multiple times over...
- Editing the current image for the _Image_ block...

### Testing Steps

1. Launch the post editor. 
2. Add an Image block. 
3. Set media for the block (Image A). 
4. Open the block settings. 
5. Tap "Set as Featured Image."
6. ✅ Verify "Featured Image" badge displays atop image. 
6. Tap three-dot menu in top right of editor. 
7. Tap "Post Settings."
8. ✅ Verify the _Image A_ is set as the Featured Image. 
9. Change the media for the block (Image B). N.b. See "Scenarios" above for various ways to perform this action.
10. Tap "Replace with new image." 
11. ✅ Verify "Featured Image" badge displays atop image. 
11. Tap three-dot menu in top right of editor. 
12. Tap "Post Settings."
13. ✅ Verify _Image B_ is set as the Featured Image. 
14. Change the media for the block (Image C). 
15. Tap "Keep current featured image." 
16. ✅ Verify "Featured Image" badge _no longer displays_ atop image. 
16. Tap three-dot menu in top right of editor. 
17. Tap "Post Settings."
18. ✅ Verify _Image B_ remains set as the Featured Image. 

## Screenshots 

| iOS | Android |
| - | - |
| iOs replace featured image prompt | Android replace featured image prompt |

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by SiobhyB — CHANGES_REQUESTED** [review]
👋 @dcalhoun, I began testing this on Android and already like the updated dialog text. :) 

The replace flow worked smoothly in my testing, but I spotted an issue with the edit flow. As you can see, confirming the replacement while an edited image is uploading, or even if it's finished uploading, doesn't actually work to replace the post's featured image:

https://user-images.githubusercontent.com/2998162/132899568-ac39db46-f237-4fc3-b1ea-1d45a65d90af.mov

In [the `canImageBeFeatured()` function](https://github.com/WordPress/gutenberg/pull/34666/files#diff-7126ae03000a022bcefa0d2a5fb03b6aca56ed4047e3a49d2131babf229cf6c1R537), there's a check for whether an image's ID is greater than zero and I wrote the following in the comments to justify that: 

> // - Images that are uploading or have failed to upload are given a temporary negative ID.

I realise now, however, that that's only true for iOS. Android actually gives uploading images a temporary _positive_ ID. I believe `this.state.isUploadInProgress` could be used with `canImageBeFeatured()` instead, but haven't found that check to be completely reliable in my testing.

Let me know if any further context is needed around the above issue.

**Review by iamthomasbishop — CHANGES_REQUESTED** [review]
@dcalhoun This looks okay for the most part, but I'm wondering if we can/should shorten the action button strings (`replace with new image` and `keep current featured image`). A few suggestions for each:

**Replace** action

- `Replace with new`
- `Replace image`
- `Replace`

**Keep** action

- `Keep current`
- `Keep current image`
- `Don't replace`
- `Cancel`

Curious to hear what y'all think, and we could also see if the Editorial team can give us some feedback. My preference is always on the shortest option that is also clear so fwiw my top picks at the moment would be `Replace image` and `Keep current`.

**Comment by dcalhoun** [comment]
> The replace flow worked smoothly in my testing, but I spotted an issue with the edit flow. 

> I realise now, however, that [negative IDs are] only true for iOS. Android actually gives uploading images a temporary _positive_ ID. I believe `this.state.isUploadInProgress` could be used with `canImageBeFeatured()` instead, but haven't found that check to be completely reliable in my testing.

@SiobhyB thank you for the thorough review. 🙇🏻 It appears it may be a few weeks before I can investigate these issues, but I will definitely follow up. What you outline makes complete sense. 

---

> @dcalhoun This looks okay for the most part, but I'm wondering if we can/should shorten the action button strings (`replace with new image` and `keep current featured image`). 

 > Curious to hear what y'all think, and we could also see if the Editorial team can give us some feedback. My preference is always on the shortest option that is also clear so fwiw my top picks at the moment would be `Replace image` and `Keep current`.

@iamthomasbishop thank you for following up. I agree the current text is a bit verbose. I would point out that a combination of `Replace` and `Cancel` would place us back where we started. I would say that `Replace featured image` and `Keep current` arrive at a good balance of concise and clear.

**Comment by dcalhoun** [comment]
@SiobhyB @iamthomasbishop sorry for the long delay before addressing your latest feedback. I updated the UI text and fixed the edit image flow. New installable builds are available on the sibling PRs. Would you please review/test at your convenience? Thanks! 

> > // - Images that are uploading or have failed to upload are given a temporary negative ID.
> 
> I realise now, however, that that's only true for iOS. Android actually gives uploading images a temporary _positive_ ID. I believe `this.state.isUploadInProgress` could be used with `canImageBeFeatured()` instead, but haven't found that check to be completely reliable in my testing.

@SiobhyB I found the negative ID from iOS is coincidence and does not always occur. It is the result of [iOS hashing the local media ID](https://github.com/wordpress-mobile/WordPress-iOS/blob/c27ea7ce389ed82734108cd2b571fcf8c4f49b7e/WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift#L281-L283) and can occasionally be positive.

**Comment by SiobhyB** [comment]
> @SiobhyB I found the negative ID from iOS is coincidence and does not always occur. It is the result of [iOS hashing the local media ID](https://github.com/wordpress-mobile/WordPress-iOS/blob/c27ea7ce389ed82734108cd2b571fcf8c4f49b7e/WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift#L281-L283) and can occasionally be positive. 

Oh, wow, thank you for that! 🙇‍♀️ This is a good lesson for me to dive a bit deeper into the code to verify assumptions in the future. I'm grateful it was uncovered and addressed in this PR!

**Review by SiobhyB — APPROVED** [review]
I tested the installable builds for both Android and iOS, making sure to test a few different flows, including uploading/cancelling images. All worked smoothly for me! I also verified that the tests pass and the code all seemed sound to me as I walked through it. 

@dcalhoun, approving as this all looks great to me, thank you! 🙇‍♀️ 🚀

**Comment by iamthomasbishop** [comment]
@dcalhoun @SiobhyB  Did a quick test on iPhone (running iOS 15.2.1) and all looks good to me! Thanks y'all! ❤️

**Review by iamthomasbishop — APPROVED** [review]

**Pull request merged**
