### PR TITLE
[FEAT] Support linear gradient in cover block

### LINKED ISSUE #1860: Cover block: Allow rendering gradient background
Depends on 
[Add Cover Block - 1st iteration](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1734)
[Add Button Block](https://github.com/WordPress/gutenberg/pull/18823) Because gradient library ships with this

Cover block on web has the ability to have gradient backgrounds. Let's add the ability to render these types of backgrounds. 

[Overlay gradient settings](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1737)  will be handled in a separate task

### PR DESCRIPTION
**Pull request by dratwas**
## Description
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1860

Gutenberg-mobile PR - https://github.com/wordpress-mobile/gutenberg-mobile/pull/1949

ATM we are able to set the linear gradient as a background in the cover block. Since we don't have the gradient picker on mobile yet I added a possibility to render linear-gradient if it set on the web.

Additionally, I moved the logic from ColorBackground related to the gradient to a separate file - LinearGradient.

### Test case 1
- Add cover block on the web with **predefined** gradient as a background (it has to be linear gradient)
- Open that post on mobile
- The gradient background should be applied to the cover block on mobile

### Test case 2
- Add cover block on the web with **custom** gradient as a background (it has to be linear gradient)
- Open that post on mobile
- The custom gradient background should be applied to the cover block on mobile

### Test case 3
- Set gradient as a background as in previous test cases
- Click on the button in `BlockToolba`r and choose media to set an image as a background
- The gradient should be changed to the image you selected

### Test case 4
- Set gradient as a background as in previous test cases
- Open block settings of the cover block
- there should be only one option "Minimum height in pixel" since we don't support overlay on top of gradient

## Screenshots 
Simulator Screen Shot - iPhone X - 2020-02-24 at 10 33 55

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by geriux — APPROVED** [review]
All test cases worked perfectly, tested on the demo and the main apps for iOS and Android. Gradients look so pretty 🤩nice work! LGTM!

Btw remember to change the base of the PR to develop.

**Comment by dratwas** [comment]
The base branch has been updated :). I also added one test case to check if we have correct settings when the gradient is set

**Comment by pinarol** [comment]
Let's update the PR description to refer to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1860 instead. My bad directing to the wrong issue in the first place.

**Comment by geriux** [comment]
> The base branch has been updated :). I also added one test case to check if we have correct settings when the gradient is set

All working great! Thanks!! Nice work!

**Pull request merged**
