### PR TITLE
Storybook: Organizes components under 'Utilities'

### PR DESCRIPTION
**Pull request by mattrwalker**
## What?
This pull request includes changes to update the categorization of several components in the Storybook configuration. The updates involve changing the `title` and adding an `id` to better reflect the components' roles as utilities.

Changes to component categorization:

* [`packages/components/src/animate/stories/index.story.tsx`](diffhunk://#diff-90a8f8fb2fa5408400b45ceafa79b80d9300f861a0cd9c57276d4696430c4a25L13-R14): Updated `title` to 'Components/Utilities/Animate' and added `id` as 'components-animate'.
* [`packages/components/src/composite/stories/index.story.tsx`](diffhunk://#diff-9f4e3586ab6373dd7040a2836a214af8131c2687b2f620ef56bde389f09c9e3fL19-R20): Updated `title` to 'Components/Utilities/Composite' and added `id` as 'components-composite'.
* [`packages/components/src/disabled/stories/index.story.tsx`](diffhunk://#diff-8ab4721a7fddf366bd6ffb5da0fafb0ebf1c7bae69e201f51c2ee7dab84d99f2L21-R22): Updated `title` to 'Components/Utilities/Disabled' and added `id` as 'components-disabled'.
* [`packages/components/src/keyboard-shortcuts/stories/index.story.tsx`](diffhunk://#diff-7de8bc965e42ce76d80ccb8a08a012f8283fd56f7a911db54414e820cc132a72L13-R14): Updated `title` to 'Components/Utilities/KeyboardShortcuts' and added `id` as 'components-keyboardshortcuts'.
* [`packages/components/src/sandbox/stories/index.story.tsx`](diffhunk://#diff-b68a4e0f8db883479ed68383c1d55b564447c0729d3947cc1fa870a533f8d6b5L13-R14): Updated `title` to 'Components/Utilities/SandBox' and added `id` as 'components-sandbox'.

## Why?
This change is part of the larger [Storybook Improvements](https://make.wordpress.org/design/2024/09/17/design-systems-storybook-improvements/) and the [shared Sitemap](https://www.figma.com/board/0ZfHa37xxWoMqy7McezUNX/WordPress.org-Storybook-Sitemap?node-id=126-5118&t=ruCtnVTDVjHTfksc-1).

## How?
Organizing components in to functional groups helps categorize the content and easier to navigate and understand.

## Testing Instructions
1. `npm run storybook:dev`
2. Observe the updated navigation

## Screenshot
CleanShot 2024-10-17 at 10 17 04@2x

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you Matt.

**Comment by jameskoster** [comment]
Thank you!

Comparing with the [Sitemap](https://www.figma.com/board/0ZfHa37xxWoMqy7McezUNX/WordPress.org-Storybook-Sitemap?node-id=127-6865&t=s5ILi7sPPradUzwL-1) I noticed `Draggable` and `ResizeableBox` aren't included. @WordPress/gutenberg-components do you consider these utilities, and is it worth including them in this PR?

**Comment by ciampo** [comment]
I wasn't involved in auditing the package, but I guess we should follow the sitemap for now and include those components as well

**Review by ciampo — COMMENTED** [review]
We will also need to add any necessary redirects to `storybook/manager-head.html` and add the `Utilities` group to `storybook/preview.js` , similarly to the work done in https://github.com/WordPress/gutenberg/pull/66072/files

**Comment by jameskoster** [comment]
I moved `Draggable` and `ResizeableBox` and updated `preview.js`.

> add any necessary redirect

How do we do this? I couldn't see redirects for the recently updated 'Actions' and 'Containers' categories?

**Review by ciampo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
