### PR TITLE
Update lock file format version to version 2 (NPM 7)

### LINKED ISSUE #29524: Check license script fails in npm version 7.6.0
## Description

Running the command `npm run check-licenses` in npm version `7.6.0` fails with the following error:
```
[1] undefined:1
[1]
[1]
[1]
[1] SyntaxError: Unexpected end of JSON input
[1]     at JSON.parse (<anonymous>)
[1]     at Object.<anonymous> (<WORKSPACE_DIR>/gutenberg/packages/scripts/scripts/check-licenses.js:188:21)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[1]     at internal/main/run_main_module.js:17:47
[1] wp-scripts check-licenses --dev exited with code 1
[0] undefined:1
[0]
[0]
[0]
[0] SyntaxError: Unexpected end of JSON input
[0]     at JSON.parse (<anonymous>)
[0]     at Object.<anonymous> (<WORKSPACE_DIR>/gutenberg/packages/scripts/scripts/check-licenses.js:188:21)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
[0]     at internal/main/run_main_module.js:17:47
[0] wp-scripts check-licenses --prod --gpl2 --ignore=@react-native-community/cli,@react-native-community/cli-platform-ios exited with code 1
```

The error looks like it's related to the command `npm ls` that is used for fetching all the dependencies data.

I tried to run `npm ls --json --all` to check the output of that command and it's giving a lot of error like the following ones:
```
npm ERR! code ELSPROBLEMS
npm ERR! missing: sveltedoc-parser@^3.0.4, required by @storybook/addon-docs@6.1.11
npm ERR! missing: vue@^2.6.10, required by @storybook/addon-docs@6.1.11
npm ERR! missing: canvas@^2.5.0, required by jsdom@16.4.0
npm ERR! invalid: react-refresh@0.4.2 <WORKSPACE_DIR>/gutenberg/node_modules/react-refresh
...
```

## Step-by-step reproduction instructions

1. Install npm version 7.6.0 (you can run the command: `npm install -g npm@7.6.0`
2. Remove `<7` condition from the npm engine section of [`package.json`](https://github.com/WordPress/gutenberg/blob/581121cb2d3a40fb34073f83219033d92e2d02f0/package.json#L19) file ([example](https://github.com/WordPress/gutenberg/pull/28886/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19))
3. Run `npm run check-licenses`
4. Observe that the script fails

## Expected behaviour

Running the script should succeed.

## Actual behaviour

Running the script produces an error.

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: 10.0.1
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: N/A
- Operating system: N/A
- Browser: N/A

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Replaces #28886 (I failed to rebase the old branch from @fluiddot).
Fixes #29524.

The new lock file format is optimized for monorepos so it would simplify the process of updating dependencies for WordPress packages. More about the new lock file format in https://github.blog/2021-02-02-npm-7-is-now-generally-available/.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
`npm ci` fails in GitHub actions with the following error for `react-native-gesture-handler`:

Screen Shot 2021-08-05 at 09 18 08

There are also other similar issues reported for npm 7: #29527 and #29528.

**Comment by gziolo** [comment]
It looks like native unit tests fail locally as well, the issue looks similar to the one with `npm ci` on CI:

Screen Shot 2021-08-05 at 11 22 01

I succesfuly tested locally:
- `npm run dev`
- `npm run build`
- `npm run docs:build`
- `npm run lint`
- `npm run test-unit`
- `npm run storybook:dev`
- `npm run storybook:build`

**Comment by hypest** [comment]
> npm ci fails in GitHub actions with the following error for react-native-gesture-handler:
> ... git@github.com: Permission denied (publickey).

I debugged a bit using [this draft PR](https://github.com/WordPress/gutenberg/pull/33898) @gziolo and looks like npm v6 is used on CI. I [got past the above issue](https://github.com/WordPress/gutenberg/pull/33898/checks?check_run_id=3252189440) when I [manually installed npm v7 in some of the jobs](https://github.com/WordPress/gutenberg/commit/0e0ed807c5732809bd8e9a294361bf6d1e1c5ad9#diff-2141f48e1f87cb8f1726e5dcccf0374348734c4afed35a9f4e1cbd70b6310783R38-R39). Should we use npm7 against the v2 of the lock file? Perhaps we should bump the `actions/setup-node`?

**Comment by gziolo** [comment]
> > npm ci fails in GitHub actions with the following error for react-native-gesture-handler:
> > ... [git@github.com](mailto:git@github.com): Permission denied (publickey).
> 
> I debugged a bit using [this draft PR](https://github.com/WordPress/gutenberg/pull/33898) @gziolo and looks like npm v6 is used on CI. I [got past the above issue](https://github.com/WordPress/gutenberg/pull/33898/checks?check_run_id=3252189440) when I [manually installed npm v7 in some of the jobs](https://github.com/WordPress/gutenberg/commit/0e0ed807c5732809bd8e9a294361bf6d1e1c5ad9#diff-2141f48e1f87cb8f1726e5dcccf0374348734c4afed35a9f4e1cbd70b6310783R38-R39). Should we use npm7 against the v2 of the lock file? Perhaps we should bump the `actions/setup-node`?

According to the [npm documentation](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion):

> The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.

It would be great to have it working on CI with both npm v6 and v7. If it isn't possible we can always enforce npm v7. At the moment when you install Node v12 and v14 they both come with npm v6. Only Node 16 comes with npm 7.

**Comment by gziolo** [comment]
When I run `npm install` locally with npm v6 then `package-lock.json` changes get updated - its format gets reverted to version 1. It means we will have to pick npm v7 as the only possible engine to avoid conflicts in the lock file.

The good news is we should be able to resolve the issue by enforcing npm v7 in GitHub actions as presented by @hypest.

**Comment by gziolo** [comment]
> Production applications should only use Active LTS or Maintenance LTS releases.

We support Node 12 and higher so we need to keep running verifications for Node v12 (Maintenance LTS), v14 (Active LTS), and also expand for v16 when it becomes Active LTS in October, see more at https://nodejs.org/en/about/releases/.

It looks like this topic needs a decision-making process. If we want to switch to npm 7 we can either do it now and install it on every CI node when Node is in use, or wait until Node v16 becomes an Active LTS version and then force npm 7 only for nodes with Node 14 :slightly_smiling_face:

**Comment by gziolo** [comment]
The good news is that this branch doesn't encounter issues with `cb() error` during npm installation as reported in https://github.com/WordPress/gutenberg/issues/33424. It's still not clear whether it's a bug specific to npm v6 or it is related to npm dependencies in `@wordpress/react-native-editor` packages that use git URLs – they are forks of npm packages. I'm going to confirm that by removing all git-based packages from dependencies when leaving everything else as is in `trunk` when using npm v6.

The remaining issues in this branch are related to missing dependencies in `@wordpress/react-native-editor` or because of using their more recent versions from npm. It was the only way to move forward with this process. There are several incompatibilities in the forked packages with other dependencies used in the Gutenberg project. So we either need to stop using forks or update them to let `npm install` work without errors. Some errors reported are included in https://github.com/WordPress/gutenberg/issues/34801.

**Comment by fluiddot** [comment]
👋 We've addressed the `cb() error` error related to forked dependencies in https://github.com/WordPress/gutenberg/pull/34886, so we could resume this PR and check if the PR checks pass with the recent changes in `trunk`.

**Comment by ZebulanStanphill** [comment]
Node v16 is now Active LTS. Is there anything still blocking this PR?

**Comment by gziolo** [comment]
> Node v16 is now Active LTS. Is there anything still blocking this PR?

We have to try again after changes are applied to forks of RN packages that use now tarballs.

I'm going to extract some necessary changes to their PRs and close this PR. We will have to try again from the clean state. First PR related to `puppeteer-core` changes https://github.com/WordPress/gutenberg/pull/36040.

**Comment by gziolo** [comment]
I will start working on it from scratch in https://github.com/WordPress/gutenberg/pull/36041.

**Comment by desrosj** [comment]
Thanks for refreshing this in a new PR @gziolo.

> Node v16 is now Active LTS. Is there anything still blocking this PR?

Just wanted to add that ideally, this change is also made in WordPress Core at the same time. Perhaps we could time this change for after WP 5.9.

**Comment by gziolo** [comment]
> Just wanted to add that ideally, this change is also made in WordPress Core at the same time. Perhaps we could time this change for after WP 5.9.

Yes, that makes a lot of sense. In the meantime, it would be great to update React Native to the latest version which might also help with a few blockers we stumbled upon so far.

**Pull request closed without merging**
