### PR TITLE
Tools: Add bin/diff-php-changes.sh to track PHP changes

### PR DESCRIPTION
**Pull request by mcsf**
## Description

This PR introduces a shell script seeking to make backporting PHP changes from Gutenberg to WordPress core slightly easier by listing PHP files that have been added, removed, or modified between two Git revisions:

## Examples

```
usage: ./bin/diff-php-changes.sh [--filter=<filter>] <range>
    List PHP files that have been added, deleted and/or modified files
    within Git range <range>. For example:

	diff-php-changes.sh origin/wp/5.5..origin/wp/trunk
	diff-php-changes.sh --filter=Ar origin/wp/5.5..origin/wp/trunk

Optionally filter according to `git diff --diff-filter`, e.g.
 --filter=A	Show added paths
 --filter=AD	Show added and deleted paths
 --filter=MR	Show modified and renamed paths
 --filter=d	Exclude deleted paths

Other options:
 -h	Show this help screen
```

```
$ ./bin/diff-php-changes.sh --filter=D origin/wp/5.5..origin/wp/trunk
### origin/wp/5.5..origin/wp/trunk
D       lib/class-experimental-wp-widget-blocks-manager.php
D       lib/class-wp-rest-widget-areas-controller.php
D       lib/editor-features.php
D       lib/patterns/large-header-paragraph.php
```

### CODE REVIEW

**Comment by sirreal** [comment]
If this does what I believe, I think it's duplicating [built-in functionality of git](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203):

```sh
## Added
$ git diff origin/wp/5.5...origin/wp/trunk  --name-only --diff-filter=A '**/*.php' | head -n 3
lib/block-supports/align.php
lib/block-supports/colors.php
lib/block-supports/custom-classname.php

## Modified
$ git diff origin/wp/5.5...origin/wp/trunk  --name-only --diff-filter=M '**/*.php' | head -n 3
lib/block-patterns.php
lib/blocks.php
lib/class-wp-block-patterns-registry.php

## Deleted
$ git diff origin/wp/5.5...origin/wp/trunk  --name-only --diff-filter=D '**/*.php' | head -n 3
lib/class-experimental-wp-widget-blocks-manager.php
lib/class-wp-rest-widget-areas-controller.php
lib/editor-features.php
```

> `--diff-filter=[(A|C|D|M|R|T|U|X|B)…​[*]]`
Select only files that are Added (`A`), Copied (`C`), Deleted (`D`), Modified (`M`), Renamed (`R`), have their type (i.e. regular file, symlink, submodule, …​) changed (`T`), are Unmerged (`U`), are Unknown (`X`), or have had their pairing Broken (`B`). Any combination of the filter characters (including none) can be used. When `*` (All-or-none) is added to the combination, all paths are selected if there is any file that matches other criteria in the comparison; if there is no file that matches other criteria, nothing is selected.
>
> Also, these upper-case letters can be downcased to exclude. E.g. `--diff-filter=ad` excludes added and deleted paths.
>
> Note that not all diffs can feature all types. For instance, diffs from the index to the working tree can never have Added entries (because the set of paths included in the diff is limited by what is in the index). Similarly, copied and renamed entries cannot appear if detection for those types is disabled.

**Comment by mcsf** [comment]
> If this does what I believe, I think it's duplicating [built-in functionality of git](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203):

It does, and I failed to find it in the documentation. 🤦

**Comment by mcsf** [comment]
Pushed a commit to greatly simplify this, @sirreal. :)

**Review by sirreal — COMMENTED** [review]
This seems to work well in my testing.

I don't know how helpful this is for the folks that need it — the folks handling releases and core merges — so I'd love to hear from them.

When we desire functionality that can be provided by tools we already use, I generally prefer to eschew wrappers and encourage usage of the tool itself.

I understand this is important for pulling updates to WordPress core. An alternative might be to add suggested commands to [this doc about the release process](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md#packages-releases-and-wordpress-core-updates)?


A comparison of this wrapper vs. git:

```sh
# using git
git diff origin/wp/5.5...origin/wp/trunk  --name-only --diff-filter=D '**/*.php'
lib/class-experimental-wp-widget-blocks-manager.php
lib/class-wp-customize-widget-blocks-control.php
lib/class-wp-rest-widget-areas-controller.php
lib/customizer.php
lib/editor-features.php
lib/patterns/large-header-paragraph.php
packages/block-library/src/legacy-widget/index.php

# using this wrapper
$ ./bin/diff-php-changes.sh --filter="D" origin/wp/5.5...origin/wp/trunk
### origin/wp/5.5...origin/wp/trunk
D       lib/class-experimental-wp-widget-blocks-manager.php
D       lib/class-wp-customize-widget-blocks-control.php
D       lib/class-wp-rest-widget-areas-controller.php
D       lib/customizer.php
D       lib/editor-features.php
D       lib/patterns/large-header-paragraph.php
D       packages/block-library/src/legacy-widget/index.php
```

**Comment by tellthemachines** [comment]
> When we desire functionality that can be provided by tools we already use, I generally prefer to eschew wrappers and encourage usage of the tool itself.

I tend to agree with this! 

> I don't know how helpful this is for the folks that need it — the folks handling releases and core merges — so I'd love to hear from them.

As someone new to the process, and not super familiar with all the changes that happened since the last release, my biggest stumbling block is not knowing which php files changed (that's easy to achieve with `git diff`), but knowing which of these changes are relevant to include in Core, and which packages they are associated with. That's the problem I'd love to invest some energy in solving, whether by rearranging file structure to make relationships more obvious, or by devising a comment system that can help identify the bits of PHP needed for a certain package update to work, or.... anything else that might be useful here.

But I digress 😄 

The commands I actually used for this job were:

`git diff wp/5.5 wp/trunk --name-status --diff-filter= '**/*.php' > trunk-update.diff`, which output a list of filenames and statuses into a file (I find that handier than just outputting to terminal, so I can keep it open while checking other stuff)  e.g.:

```
M	lib/block-patterns.php
A	lib/block-supports/align.php
A	lib/block-supports/colors.php
A	lib/block-supports/custom-classname.php
A	lib/block-supports/generated-classname.php
A	lib/block-supports/index.php
A	lib/block-supports/typography.php
M	lib/blocks.php
```

I also ran `git diff wp/5.5 wp/trunk --diff-filter= '**/*.php' > trunk-update-details.diff`, which output the line-by-line diff of all the files into another file. I found it useful to check the actual changes in some of the files. The output is pretty long, but easy to search inside by filename.

**Comment by tellthemachines** [comment]
Whoops sorry, wrong button 😅

**Comment by mcsf** [comment]
Thanks for your comments, @sirreal and @tellthemachines. I'd also tend to agree with you on avoiding wrappers, and that the difficulties of backporting PHP changes extend way beyond diffing. My initial instinct was that adding a script would contribute to the visibility of the tool, and it was probably influenced by [_No script is too simple_](https://nicolasbouliane.com/blog/no-script-is-too-simple).

That said, I agree that the release docs are a better investment, so that ought to be the first step.

@tellthemachines, since you're leading this release, you will be the one best informed on what kind of knowledge and steps matter for a release. Are you interested in later adding these steps, if they have merit, to the docs?

As far as this PR is concerned, I think it's safe to close. Do comment or reopen if you feel otherwise.

**Pull request closed without merging**
