### PR TITLE
[RNMobile][Embed block] Include extra embed variants

### PR DESCRIPTION
**Pull request by fluiddot**
- Gutenberg Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008
- WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/17224
- WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15378
- Jetpack PR: https://github.com/Automattic/jetpack/pull/21167

## Description

Add embed variations capabilities to React Native bridge.

## How has this been tested?

Follow testing instructions from https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008.

## Screenshots 

Light mode|Dark mode
--|--
|

## Types of changes

New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by guarani** [comment]
I was just wondering if these new capabilities need to be set to true ([iOS example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-2f5cb024763fc6152e52669fa1d957e4054d38a48984e1600dc8c8949596432dR309), [Android example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-769716bb706f66f37212cb2c4b06ec2e87280a37c66d795ad8b2ca56843e7a95R38)) so that these new blocks are displayed when running the Gutenberg Mobile demo app. I think this would be needed, but I could be wrong here since I'm not too familiar with these embed blocks.

**Comment by fluiddot** [comment]
> I was just wondering if these new capabilities need to be set to true ([iOS example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-2f5cb024763fc6152e52669fa1d957e4054d38a48984e1600dc8c8949596432dR309), [Android example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-769716bb706f66f37212cb2c4b06ec2e87280a37c66d795ad8b2ca56843e7a95R38)) so that these new blocks are displayed when running the Gutenberg Mobile demo app. I think this would be needed, but I could be wrong here since I'm not too familiar with these embed blocks.

Good catch, I think that's the case when running the demo app using the GB-mobile code. I'll update those files with your suggestion, thanks 🙇 !

**Comment by fluiddot** [comment]
> > I was just wondering if these new capabilities need to be set to true ([iOS example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-2f5cb024763fc6152e52669fa1d957e4054d38a48984e1600dc8c8949596432dR309), [Android example](https://github.com/WordPress/gutenberg/pull/34472/files#diff-769716bb706f66f37212cb2c4b06ec2e87280a37c66d795ad8b2ca56843e7a95R38)) so that these new blocks are displayed when running the Gutenberg Mobile demo app. I think this would be needed, but I could be wrong here since I'm not too familiar with these embed blocks.
> 
> Good catch, I think that's the case when running the demo app using the GB-mobile code. I'll update those files with your suggestion, thanks 🙇 !

This has been addressed in [this commit](https://github.com/WordPress/gutenberg/pull/35155/commits/d4f9e8f4ac357d4e320a3c4a17e542b053663dae).

**Review by jd-alexander — COMMENTED** [review]
I verified that the props passed here worked as expected via https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008 I did not notice the Embeds within the demo app. I was of the assumption they may not work due to the fact that the jetpack setup code is not integrated here. Let me know if you have any thoughts on this.

**Comment by fluiddot** [comment]
> I verified that the props passed here worked as expected via [wordpress-mobile/gutenberg-mobile#4008](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008) I did not notice the Embeds within the demo app. I was of the assumption they may not work due to the fact that the jetpack setup code is not integrated here. Let me know if you have any thoughts on this.

Yes, the Jetpack embed variants won't show up in the demo app because they are only registered when running GB-mobile code. However, you could see them if you connect the demo app with the Metro server pointing to GB-mobile.

**Comment by jd-alexander** [comment]
> > I verified that the props passed here worked as expected via [wordpress-mobile/gutenberg-mobile#4008](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008) I did not notice the Embeds within the demo app. I was of the assumption they may not work due to the fact that the jetpack setup code is not integrated here. Let me know if you have any thoughts on this.
> 
> Yes, the Jetpack embed variants won't show up in the demo app because they are only registered when running GB-mobile code. However, you could see them if you connect the demo app with the Metro server pointing to GB-mobile.

Ah thanks for confirming!

**Review by jd-alexander — APPROVED** [review]
I ran the demo app from `gb-mobile` and I was able to see the embed variants. LGTM 🚢

**Pull request merged**
