### PR TITLE
Latest Comments block: use align supports flag + code cleanup

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
This PR updates the Latest Comments block to use `supports: { align }` to add most of its alignment support. It also cleans up the surrounding code a bit. There should be **no change in behavior** from `master`.

## Types of changes
- Using `supports: { align }` to add block alignment support to the block.
- Removed useless `''` value from `enum` property in `align` attribute in the Latest Comments `index.php`. I tested to make sure this has no effect on functionality.
- The attributes in the Latest Comments `index.php` are now in alphabetical order.
- Had to update `test/integration/full-content/server-registered.json` due to the previous 2 changes. I took this opportunity to reorder the blocks alphabetically.
- The imports in the Latest Comments `edit.js` and `index.js` are now in alphabetical order.

## Related issues and PRs
- replaces #9832
- #10706
- #10707
- #10758
- #13215

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Rebased PR and updated it based on feedback on #10758.

**Comment by gziolo** [comment]
@ZebulanStanphill this PR needs to be refreshed again :( Code itself looks good, I would be fine merging it next week after some testing when Travis lets us to do it :)

**Comment by ZebulanStanphill** [comment]
@gziolo Rebased PR.

**Review by codebykat — APPROVED** [review]
Noting that I took this for a spin and didn't find any regressions, with the Latest Comments block or otherwise 👍. The code also looks good.

I did note that, while the `aligncenter` class is added, it seems to not be respected on the front-end. The preview in the editor doesn't match the result.

Editor preview:

Screen Shot 2019-03-09 at 11 03 10 AM

Front-end display:
  
Screen Shot 2019-03-09 at 11 03 16 AM

However this issue, if it is an issue, is also present on master, so not a blocker for this PR.

**Comment by codebykat** [comment]
I opened a separate issue for the alignment problems with this block: https://github.com/WordPress/gutenberg/issues/14358

**Pull request merged**
