### PR TITLE
Fix Link Control 'Open in new tab' option not saving properly on committing link in buttons block

### LINKED ISSUE #40243: When editing a link in a button block, linkTarget is reset even though only the url is changed.
### Description

https://user-images.githubusercontent.com/31400297/162871564-3a4a2d94-fc2a-47cf-8615-ad60b2229ea8.mp4

### Step-by-step reproduction instructions

1. Set up a button block.
2. Set the URL for the link and turn on "Open in new tab".
3. Edit the URL using the "Edit" button and click the "Submit" button to save.
4. Then "Open in new tab" will be turned off.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- WordPress 5.9.3

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by hz-tyfoon**
### This PR fixes #40243
[note: The mentioned issue was not only in buttons block but in the 'link-control' component]

### CODE REVIEW

**Comment by getdave** [comment]
@hz-tyfoon Thank you for the PR. It's much appreciated 👏 

I tested this with the standard link in the Post Editor and I was unable to reproduce. I could however, reproduce with the buttons block. This is using latest Gutenberg `trunk` from Github.

https://user-images.githubusercontent.com/444434/176707163-f52a70c0-e6bf-4cf5-8373-31a2793de938.mov

I believe this is likely due to the fact that the `<LinkControl>` is a controlled component (like a form input) and therefore each consumer must provide their own handling implementation.

At first glance, your fix seems good, but I'm going to dig a little deeper and see if there's fundamental problem with the handler in richtext vs the button block.

Also please could you resolve the unit tests? 🙇

**Comment by getdave** [comment]
The issue is that LinkControl will call `onChange` for any change to the value. The "value" also includes settings such as `opensInNewTab`.

So when the user clicks "Open in new tab" `onChange` is called and the following code sets the Button block's `linkTarget` attribute to `true`.

https://github.com/WordPress/gutenberg/blob/b0244c2e39a48cb83357ed1bb3fd48094e9c8970/packages/block-library/src/button/edit.js#L229-L230

However, when the user clicks submit to "commit" the link then due to the problem that @hz-tyfoon identified the original value of `opensInNewTab` is not provided to the callback and thus in the Button block `onChange` handler `newOpensInNewTab`  has a value of `undefined`. This then overwrites the original setting of the `linkTarget` attribute from `true` to `undefined` which is why the UI behaves as it does.

On balance I think we should update LinkControl to provide the stored value on commit as per this PR. We should update the tests to assert on the full value being provided. Please could you add `opensInNewTab` to the relevant tests to further improve them?

**Comment by hz-tyfoon** [comment]
Hey @getdave. 🙂 
Hope you're doing well.
thanks a lot for your comment. 👍 

> @hz-tyfoon Thank you for the PR. It's much appreciated 👏
> 
> I tested this with the standard link in the Post Editor and I was unable to reproduce. I could however, reproduce with the buttons block. This is using latest Gutenberg `trunk` from Github.
> 
>  Screen.Capture.on.2022-06-30.at.15-45-31.mov 
> I believe this is likely due to the fact that the `<LinkControl>` is a controlled component (like a form input) and therefore each consumer must provide their own handling implementation.
> 


> At first glance, your fix seems good, but I'm going to dig a little deeper and see if there's fundamental problem with the handler in richtext vs the button block.
> 
> Also please could you resolve the unit tests? 🙇

⬆️ I was talking about this issue #42080 with the standard link in the Post Editor. I'm not sure why the unit tests always so stubborn. In my first contribution few days earlier it failed 5-6 times and finally it passed after re-running the test again.

**Comment by hz-tyfoon** [comment]
> The issue is that LinkControl will call `onChange` for any change to the value. The "value" also includes settings such as `opensInNewTab`.
> 
> So when the user clicks "Open in new tab" `onChange` is called and the following code sets the Button block's `linkTarget` attribute to `true`.
> 
> https://github.com/WordPress/gutenberg/blob/b0244c2e39a48cb83357ed1bb3fd48094e9c8970/packages/block-library/src/button/edit.js#L229-L230
> 
> However, when the user clicks submit to "commit" the link then due to the problem that @hz-tyfoon identified the original value of `opensInNewTab` is not provided to the callback and thus in the Button block `onChange` handler `newOpensInNewTab` has a value of `undefined`. This then overwrites the original setting of the `linkTarget` attribute from `true` to `undefined` which is why the UI behaves as it does.
> 
> On balance I think we should update LinkControl to provide the stored value on commit as per this PR. We should update the tests to assert on the full value being provided. Please could you add `opensInNewTab` to the relevant tests to further improve them?



> The issue is that LinkControl will call `onChange` for any change to the value. The "value" also includes settings such as `opensInNewTab`.
> 
> So when the user clicks "Open in new tab" `onChange` is called and the following code sets the Button block's `linkTarget` attribute to `true`.
> 
> https://github.com/WordPress/gutenberg/blob/b0244c2e39a48cb83357ed1bb3fd48094e9c8970/packages/block-library/src/button/edit.js#L229-L230
> 
> However, when the user clicks submit to "commit" the link then due to the problem that @hz-tyfoon identified the original value of `opensInNewTab` is not provided to the callback and thus in the Button block `onChange` handler `newOpensInNewTab` has a value of `undefined`. This then overwrites the original setting of the `linkTarget` attribute from `true` to `undefined` which is why the UI behaves as it does.
> 
> On balance I think we should update LinkControl to provide the stored value on commit as per this PR. We should update the tests to assert on the full value being provided. Please could you add `opensInNewTab` to the relevant tests to further improve them?

Agreed. 👍 
Thanks a ton for taking the time to check this. 💚
@getdave

**Comment by hz-tyfoon** [comment]
Looks like this PR also fixing this issue #40243 as well.

**Comment by talldan** [comment]
@hz-tyfoon Thanks for working on this. There's a unit test for link editing that's failing as a result of these changes and will need to be updated - https://github.com/WordPress/gutenberg/runs/7173641105?check_suite_focus=true.

There's a comment on the other PR that mentions the same issue, and has some details for solving it - https://github.com/WordPress/gutenberg/pull/40244#issuecomment-1172855424.

**Comment by hz-tyfoon** [comment]
> There's a comment on the other PR that mentions the same issue, and has some details for solving it - [#40244 (comment)](https://github.com/WordPress/gutenberg/pull/40244#issuecomment-1172855424).

Sorry for late reply, I somehow didn't notice your comment earlier. @talldan 
Updated the Unit test & looks like the failed JS test have passed now.
Thanks @talldan & @torounit

**Review by getdave — APPROVED** [review]
LGTM - tests now streamlined and the fix seems good. The controlled component should always pass the entire `value` when it calls the `onChange` handler. This PR addresses that so I think it's good.

**Comment by hz-tyfoon** [comment]
Shouldn't (issue: #42032) also be closed, as this PR was originally created to solve that? 🤔

**Pull request merged**
