### PR TITLE
Support pasting table with lists content

### PR DESCRIPTION
**Pull request by mpkelly**
Related to https://github.com/WordPress/gutenberg/issues/45774

## What?
It's based on requirement 2 from https://github.com/WordPress/gutenberg/issues/45774. If you paste a table which includes `ul` or `ol` elements, these elements will be converted to simple content and formatted with whitespace to try and keep the original list structure. This avoids having to support complex nested content in tables. 

## Why?

Increase parity between Gutenberg and other editors. 

## How?

Allow the list schema to be embedded into `td` and `th`. Add a `transform` function for `tables` that can convert these tables into simple content. 

## Testing Instructions

1. Check out this branch and create a table in Google Docs that has ordered or unordered in its cells. See the screenshots below. 
2. Paste the table into Gutenberg to see the result
3. Try adding content before/after the list.
4. Try nesting lists to any depth. 

## Screenshots or screencast 

Source table (Google docs)

image

Gutenberg editor after pasting the table above

image

How the `td` which contained the list looks in the DOM when previewing

image

### CODE REVIEW

**Comment by mpkelly** [comment]
@danielbachhuber , @ellatrix. I recreated this PR from the draft https://github.com/WordPress/gutenberg/pull/46254. Can you give it a review? 

I can beef up the test suite but for now I would like to get some feedback and make sure this PR will be accepted.

**Review by danielbachhuber — COMMENTED** [review]
Sweet! This seems to work pretty well to me from a product perspective. I'll defer to others on the codes.

For Example 4 (below), do we want to alternate between letters and numbers?

## Example 1

### Google Docs

image

### Paste Into Gutenberg

image

## Example 2

### Google Docs

image

### Gutenberg Paste

image

## Example 3

### Google Docs

image

### Paste Into Gutenberg

image

## Example 4

### Google Docs

image

### Paste Into Gutenberg

image

## Example 5

### Google Docs

image

### Paste Into Gutenberg

image

**Comment by danielbachhuber** [comment]
@mpkelly Can you rebase trunk and make sure all of the tests pass?

**Comment by mpkelly** [comment]
Thanks for the ping, @danielbachhuber. There are some test failures, but I can't see why. The `colspan` test I added in a previous PR fails even though that's working fine in the dev environment. Another unrelated test fails due to a difference in how whitespace is encoded. I will try and get everything passing again.

**Pull request closed without merging**
