### PR TITLE
Block Directory: Activate deactivated blocks if already installed 

### PR DESCRIPTION
**Pull request by StevenDufresne**
## Description
This PR is based on [this discussion](https://github.com/WordPress/block-directory/issues/14). It takes the simplest possible route as a conversation piece. It also addresses #19906. 

#### TL;DR
This PR handles the case where:

1. User installs block (block must be in the block directory)
2. Block is deactivated
3. Sometime later, user searches for block in inserter.
4. Nothing is returned

## Current Issue:
- Since the block is deactivated it doesn't show up in the inserter on page load
- Since the block is installed, the block directory api endpoint does not return the block

## Options:
- The UI does not change, the block is returned as a result (Implemented in this PR)
  - If there is a block that is installed but deactivated, skip install and activate the block.
- [Display to the user that the block is disabled using the same Block Directory layout view](https://github.com/WordPress/block-directory/issues/14#issuecomment-513600259)
- [Custom view for disabled blocks](https://github.com/WordPress/block-directory/issues/14#issuecomment-510521517)

## How has this been tested?
1. Install a block from the block directory
2. Deactivate block via `wp-admin/plugins.php`
3. Search for the same block in the inserter
4. Click `Add block`

**Expect** 
- Block to be injected into document
- Save & reload page -> block is functioning properly

## Types of changes
- Searching for a block also returns installed blocks
  - I decide not to check if its activated because the block directory search wouldn't be triggered otherwise, since it only searches if it doesn't have a registered block.
  - We could also check to see if its activated, not sure if its necessary
- In the `/install` endpoint, check if the block is installed. 
  - If installed jump to activation step.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ryelle — APPROVED** [review]
Looks good, my inactive block is activated & added 👍 

> We could also check to see if its activated, not sure if its necessary

I can't think of a valid case where a plugin could be active, but the block scripts not loaded… unless the block is only added to specific pages/post types. But that would cause issue with the current flow too, so I think this is a good minimal-solution to this problem.

**Comment by TimothyBJacobs** [comment]
I think this is a fine intermediary solution. Preferably in the search results we would link to the plugins endpoint for any currently installed plugins but I think that can be implemented later.

**Comment by StevenDufresne** [comment]
Are we comfortable merging this or should we take more time experimenting?

**Comment by TimothyBJacobs** [comment]
I don't have an issue merging it.

**Pull request merged**
