### PR TITLE
Move the updating of Gallery level attributes to the Image block

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description
Moves the management of parent block attrib updates into the child image blocks

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
This is working well for me 👍 

I think it is worth holding off on this for now, until the discussion around image blocks being aware of the context they are in, comes to a conclusion.

**Comment by jasmussen** [comment]
> I think it is worth holding off on this for now, until the discussion around image blocks being aware of the context they are in, comes to a conclusion.

I've been following this PR, and #25940 from the sidelines, and I think this is the best way forward. 

The big challenge is that no other block has sidebar controls where you "apply" a change to child blocks quite like the new Gallery block does. But we still need the ability to define the _default_ "link to" property for child Images.

By making the Image block aware of its Gallery parent, we can hopefully remove the "Apply" button from the Gallery sidebar. That, I think, is key to getting a good V1 out there, getting all the benefits of the refactor, and getting a feel for what edgecases remain, if any. Specifically, I think this makes for a good V1 user experience, which it should accomplish:

- Insert gallery with 3 images.
- Gallery has a dropdown which enables you to link to media file or attachment page. There's no confirm, picking a choice is immediate.
- User selects one Image block inside, and links that directly to Google.com or something, and it overrides the previous choice.

**Comment by aaronrobertshaw** [comment]
> By making the Image block aware of its Gallery parent, we can hopefully remove the "Apply" button from the Gallery sidebar. That, I think, is key to getting a good V1 out there, getting all the benefits of the refactor, and getting a feel for what edgecases remain, if any. Specifically, I think this makes for a good V1 user experience, which it should accomplish:

I don't disagree with the UX aspect of what you are saying. There have been some concerns expressed however with regards to how much context aware logic is too much for the image block. 

My suggestion to hold off on this was not meant to imply a solution to this issue wasn't a part of V1. Instead, just waiting to 
confirm that merging this won't cause excess re-work if we need to rethink how we achieve the UX you describe. 

We have a few options up our sleeve. Whether we need them at all is dependent on the discussion occurring on the main PR https://github.com/WordPress/gutenberg/pull/25940#discussion_r543787331

**Comment by jasmussen** [comment]
> There have been some concerns expressed however with regards to how much context aware logic is too much for the image block.

Absolutely. I will totally defer to you and other developers on that. I speak mainly from the user experience angle here, and believe that it can be delightful when a very basic block gains new powers when put inside another block. A basic example is a Button block that gets distributed horizontally when inside a Buttons block. Or perhaps a new "Mobile menu" block that simply is a popover menu on mobile, and just shows its content directly when on desktop. Put a navigation menu inside it, and there's your hamburger menu. 

I did not mean to dismiss the gnarly details. I know how much code already exists in the Image block 🙈

**Pull request merged**
