### PR TITLE
Fix template part border states.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Similar to the CSS for the entity spotlight, Template Part border state styles were stripped in #27271.  The noted PR was to test showing block borders on hover, but removed a very important non-conflicting border state that is present for entity editing awareness - the has-child-selected state.  This state has since been asked to be re-implemented via PR https://github.com/WordPress/gutenberg/pull/27780.

This PR re-introduces the has-child-selected border state for template parts so that when a child block in a template part is selected a small outline for the template part will be visible.  This state is important for understanding what is/is not part of the template part currently being edited and works together with the entity spotlight system (being fixed here https://github.com/WordPress/gutenberg/pull/28239) to visually highlight this for the user.

## How has this been tested?

* Load the Site Editor
* Select a child block of the template part header.
* Verify the border exists.

Screen Shot 2021-01-15 at 10 50 30 AM

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by mattwiebe — APPROVED** [review]
Works as advertised :shipit:

**Review by jameskoster — CHANGES_REQUESTED** [review]
Selected-but-not-focussed blocks have a block outline, I think we should probably apply the same treatment here.

**Comment by Addison-Stavlo** [comment]
> Selected-but-not-focussed blocks have a block outline, I think we should probably apply the same treatment here.

Oh great catch!  Now I am remembering why we put those extra rules in previously for exactly that reason. That should be good now.

> @jameskoster
Use a grey border when a template part child is selected

I pushed to override this.  We need to be careful about border colors, the old gray border that was developed when we were on a white background wasnt visible enough when we moved to the green of tt1 blocks.  Gray borders aren't consistently going to have the right level of appearance across different background colors, while we can always use the standard wordpress focus and dark theme focus colors and be consistent.

**Comment by Addison-Stavlo** [comment]
> Gray borders aren't consistently going to have the right level of appearance across different background color

Expanding on this. previously higher shades of gray were 'too dark' for white backgrounds, in which the desired shade against white was determined to be gray-300.  On the default tt1 seafoam green background however, gray-300 is almost invisible.  With other shades we don't really have a happy medium of gray that works well for all background colors.  Im not sure what the BEST solution is, but for now I think using theme/dark-theme focus colors is the most consistent way to go about it.

**Comment by jameskoster** [comment]
I don't disagree with anything you've said :) But I do think we should address any color issues from a state of consistency with how blocks behave currently, which is to use a `gray-900` outline when they are selected but not focussed. Gif for reference:

grey

If there's a problem with this, let's address it all in one go?

**Comment by Addison-Stavlo** [comment]
>  which is to use a gray-900 outline when they are selected but not focussed. 

Oh interesting!  Do you know if there is another color used for "dark themes"?  Or is it always gray-900 right now?

**Comment by Addison-Stavlo** [comment]
> Do you know if there is another color used for "dark themes"?

If im reading through the CSS correctly it looks like no.  I see dark theme definitions for some focus states, but 'selected not focused' seems to always be $gray-900.

In that case do you think both of these border states for the template part block should be `$gray-900` in all cases?
* TP Block selected but not focused.
* Child of template part block selected.

**Comment by Addison-Stavlo** [comment]
> do you think both of these border states for the template part block should be $gray-900

Thats the state of this PR now with ef60c11.  Let me know how that feels to you please. 😁

**Review by jameskoster — APPROVED** [review]
> Thats the state of this PR now with ef60c11. Let me know how that feels to you please. 😁

I think this is good for now – we're in alignment with regular block behaviour, so any issues that exist there can be addressed separately in one go.

**Pull request merged**
