### PR TITLE
Fix React error in @wordpress/block-editor docs usage example caused by applying args to setState call

### LINKED ISSUE #25333: `BlockEditorProvider` documentation out of date
**Describe the bug**
Currently the documentation for `<BlockEditorProvider>` suggests using it as follows:

```jsx
const [ blocks, updateBlocks ] = useState( [] );

<BlockEditorProvider
    value={ blocks }
    onInput={ updateBlocks }
    onChange={ updateBlocks }
>
```

Unfortunately this will result in the following error in the console:

> Warning: State updates from the useState() and useReducer() Hooks don't support the second callback argument.
To execute a side effect after rendering, declare it in the component body with useEffect().

The reason for this is that the `onInput` callback now appears to provide more than 1 argument (ie: it doesn't just provide the `blocks`). This means that attempt to call it directly as showing the documentation will cause multiple arguments to be passed to the `updateBlocks` handler for the `useState` hook. This hook interprets any arguments following the first as an attempt to use the unsupported second callback argument pattern.

You can verify the change to two arguments by looking at this tests

https://github.com/WordPress/gutenberg/blob/f12c56320b7123ffb36cd3af713f9bf551b809fc/packages/block-editor/src/components/provider/test/use-block-sync.js#L237-L239

To fix we should update the documentation to use a arrow function to ensure only a single argument is applied:

```jsx
const [ blocks, updateBlocks ] = useState( [] );

<BlockEditorProvider
    value={ blocks }
    onInput={ ( blocks ) => updateBlocks( blocks ) } // note the change here
    onChange={ updateBlocks }
>
```

**To reproduce**
Setup a BlockEditorProvider provider as per the docs. See the error in the console when you type into the Editor.

**Expected behavior**
No error should be in the console.

### PR DESCRIPTION
**Pull request by getdave**
Fix for https://github.com/WordPress/gutenberg/issues/25333

This updates the documented usage example for the `@wordpress/block-editor` docs to avoid showing the following error in the console

> Warning: State updates from the useState() and useReducer() Hooks don't support the second callback 

This is happening because `onInput` and `onChange` handlers are called with x2 args:

1. Blocks
2. Selection ranges.

Supplying the `useState` hook's update handler (ie: `updateBlocks`) as the callback causes it to be called with the **two arguments applied to it**. Unfortunately `useState` only expects **a single argument** which results in the error shown above.

This PR updates to docs to use an arrow function to ensure only a single argument is passed to the `setState` call which fixes the error. We could get fancy with partial application but for the purposes of documentation, a wrapper function is probably the easiest to understand.

## How has this been tested?
You can verify two args are provided to `onInput` and `onChange` in the associated tests for the relevant components:

https://github.com/WordPress/gutenberg/blob/f12c56320b7123ffb36cd3af713f9bf551b809fc/packages/block-editor/src/components/provider/test/use-block-sync.js#L237-L239

Other than that you'd have to test up a test environment which I haven't had the chance to do.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by getdave** [comment]
@cpapazoglou Pinging you for review here until you are a member of `Gutenberg` team.

**Comment by cpapazoglou** [comment]
Thanks @getdave for you great PR & Issue description and for taking time to fix the docs!
Should we maybe fix this doc too
https://github.com/WordPress/gutenberg/blob/cb461d4c842cc3b1d14bb29d3ffd8e0cd123a73c/docs/designers-developers/developers/platform/custom-block-editor/tutorial.md

Apart from that, LGTM!

**Review by mkaz — APPROVED** [review]
Looks good, thanks! 👍

**Comment by getdave** [comment]
Thanks @mkaz. I'll merge this asap.

**Comment by getdave** [comment]
Oh it's already merged 🤷

**Pull request merged**
