### PR TITLE
Tests: Run e2e tests only as an admin

### PR DESCRIPTION
**Pull request by gziolo**
## Description

@youknowriad discovered lately that we run e2e tests twice for the admin user. This PR tries two things:
- remove the duplication
- run all tests as an admin because it's too much work to make author tests pass after several months of development without this type of verification

## How has this been tested?

GitHub actions should pass.

### CODE REVIEW

**Comment by gziolo** [comment]
@youknowriad so many failures, that are concerning, to be honest. The question is whether we want to resolve them or we are good running all tests as admin? We were fine for nearly a yeat if I located the commit that caused the tests to not run as an author...

**Comment by youknowriad** [comment]
It seems the solution for me is to have more targetted author tests so fine to keep the admin only for now.

**Comment by gziolo** [comment]
I updated branch to run tests only as an admin based on the feedback.

**Review by youknowriad — APPROVED** [review]
Thanks

**Pull request merged**
