### PR TITLE
Styles: remove wp-editor from wp-edit-blocks dependencies

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Currently the `wp-edit-blocks` stylesheet (in the `block-library` package) has `wp-editor` set as a dependency. As a result, this stylesheet is loaded in the editor content iframe, even though it shouldn't target components inside the editor content. 

To do: remove the title rules (and maybe component) from the package.

`wp-editor` has the `wp-nux` dependency, which will now also be removed from the iframe.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
WFM

**Comment by gziolo** [comment]
> wp-editor has the wp-nux dependency, which will now also be removed from the iframe.

`@wordpress/nux` is no longer used in Gutenberg. We probably should deprecate this package. Although, some plugins might still depend on it.

**Review by aristath — APPROVED** [review]

**Comment by ellatrix** [comment]
Thanks for the reviews. I noticed we have styling for the post title in that package (a component that will be rendered in the iframe that is _not_ a block), so we'll have to find a better place for it.

**Comment by aristath** [comment]
Is there anything blocking us here? Or should we merge it?

**Comment by youknowriad** [comment]
Was the post title styling fixed https://github.com/WordPress/gutenberg/pull/33496#issuecomment-884840053 I guess that's the last blocker here.

**Comment by ellatrix** [comment]
I moved the `is-focus-mode` class to the post title wrapper, which now emulates the rest of the blocks better (the class is added to the root wrapper), and as a result the CSS for blocks now automatically works for the post title, so this special CSS is no longer needed.

**Pull request merged**
