### PR TITLE
Elements: Buttons: Fix the path with the css to style the cursor for all button elements

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?

In this PR https://github.com/WordPress/gutenberg/pull/42102, we added a stylesheet to style .wp-elements-* elements, but those styles are not being loaded in the frontend.

## Why?

Because those styles are not being loaded in the frontend so they are not being applied.

## How?

In this PR I'm importing the `elements.scss` file in `common.scss` instead of `styles.scss`. Because `style.scss` is not loaded in the frontend and `common.scss` yes.

## Testing Instructions

1. Create a post
2. Add a search form to the post and publish it.
3. Navigate the public version of the post and check if the search form button has a `cursor:pointer` definition. If that's true, the styles are being applied correctly.

### CODE REVIEW

**Comment by scruffian** [comment]
Does that mean we should remove it from style.scss?

**Comment by matiasbenedetto** [comment]
> Does that mean we should remove it from style.scss?

Yep, for some reason, that change was not pushed in the first commit. Now it is there.

**Review by carolinan — APPROVED** [review]
Works well.

I would like to understand why this style needs load even if there are no buttons present on the page?

**Comment by Mamaduka** [comment]
Hi folks,

Is this PR good to merge into the trunk?

**Comment by scruffian** [comment]
> I would like to understand why this style needs load even if there are no buttons present on the page?

It doesn't but we don't have a way of determining if there are elements present on the page.

**Pull request merged**
