### PR TITLE
Improvements to how blocks with a 'disabled' editing mode behave

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Follows https://github.com/WordPress/gutenberg/pull/50643.

Split out of https://github.com/WordPress/gutenberg/pull/50857.

Various improvements to how blocks that have `useBlockEditingMode( 'disabled' )` behave.

- Prevent `DefaultAppender` from appearing in a disabled block.
- Disable selection (using `user-select: none`) in disabled blocks.
- Prevent blocks from being inserted into a disabled block via global inserter.
- Prevent disabled blocks from being removed via keyboard shortcut.
- Prevent disabled blocks from being moved via List View drag and drop.
- Prevent block overlay from appearing on a disabled block.

## Why?
See https://github.com/WordPress/gutenberg/pull/50857.

## How?
Mostly the changes are at the model level (`canInsertBlockType`, `canMoveBlock`, `canRemoveBlock`, etc.). Most of the block editor uses these methods to determine which bits of UI to display.

## Testing Instructions
1. Apply the patch below by copying it and running `pbpaste | git apply`.

```diff
diff --git a/packages/edit-site/src/components/block-editor/index.js b/packages/edit-site/src/components/block-editor/index.js
index cc5e7c8d92..f97599a9b5 100644
--- a/packages/edit-site/src/components/block-editor/index.js
+++ b/packages/edit-site/src/components/block-editor/index.js
@@ -39,7 +39,9 @@ import EditorCanvas from './editor-canvas';
 import { unlock } from '../../private-apis';
 import EditorCanvasContainer from '../editor-canvas-container';
 
-const { ExperimentalBlockEditorProvider } = unlock( blockEditorPrivateApis );
+const { ExperimentalBlockEditorProvider, useBlockEditingMode } = unlock(
+	blockEditorPrivateApis
+);
 
 const LAYOUT = {
 	type: 'default',
@@ -47,6 +49,11 @@ const LAYOUT = {
 	alignments: [],
 };
 
+function SetRootBlockEditingMode( { mode } ) {
+	useBlockEditingMode( mode );
+	return null;
+}
+
 export default function BlockEditor() {
 	const { setIsInserterOpened } = useDispatch( editSiteStore );
 	const { storedSettings, templateType, canvasMode } = useSelect(
@@ -162,6 +169,7 @@ export default function BlockEditor() {
 			onChange={ onChange }
 			useSubRegistry={ false }
 		>
+			<SetRootBlockEditingMode mode="disabled" />
 			<TemplatePartConverter />
 			<SidebarInspectorFill>
 				<BlockInspector />
diff --git a/packages/edit-site/src/hooks/block-editing-mode.js b/packages/edit-site/src/hooks/block-editing-mode.js
new file mode 100644
index 0000000000..24d63f122f
--- /dev/null
+++ b/packages/edit-site/src/hooks/block-editing-mode.js
@@ -0,0 +1,50 @@
+/**
+ * WordPress dependencies
+ */
+import { createHigherOrderComponent } from '@wordpress/compose';
+import { addFilter } from '@wordpress/hooks';
+import {
+	store as blockEditorStore,
+	privateApis as blockEditorPrivateApis,
+} from '@wordpress/block-editor';
+import { useSelect } from '@wordpress/data';
+
+/**
+ * Internal dependencies
+ */
+import { unlock } from '../private-apis';
+
+const { useBlockEditingMode } = unlock( blockEditorPrivateApis );
+
+export const withBlockEditingMode = createHigherOrderComponent(
+	( BlockEdit ) => ( props ) => {
+		const mode = useSelect( ( select ) => {
+			if (
+				[
+					'core/post-title',
+					'core/post-featured-image',
+					'core/post-content',
+				].includes( props.name )
+			) {
+				return 'contentOnly';
+			}
+			if (
+				select( blockEditorStore ).getBlockParentsByBlockName(
+					props.clientId,
+					'core/post-content'
+				).length
+			) {
+				return 'default';
+			}
+		} );
+		useBlockEditingMode( mode );
+		return <BlockEdit { ...props } />;
+	},
+	'withBlockEditingMode'
+);
+
+addFilter(
+	'editor.BlockEdit',
+	'core/edit-site/block-editing-mode',
+	withBlockEditingMode
+);
diff --git a/packages/edit-site/src/hooks/index.js b/packages/edit-site/src/hooks/index.js
index 513634c55b..de9dc8c3f7 100644
--- a/packages/edit-site/src/hooks/index.js
+++ b/packages/edit-site/src/hooks/index.js
@@ -1,6 +1,7 @@
 /**
  * Internal dependencies
  */
+import './block-editing-mode';
 import './components';
 import './push-changes-to-global-styles';
 import './template-part-edit';

```

2. Navigate to Appearance → Editor → Pages and select a page to edit.
3. All blocks should be locked except for the Post Title, Post Featured Image and Post Content blocks.
4. Check:
  - That the appender does not appear at the bottom of the editor, but does appear in the Post Content block.
  - That double clicking or dragging on a disabled block doesn't select it.
  - That when you open the global inserter with no block selected, you can't select a block to insert.
  - That blocks in the List View can't be dragged and dropped.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Works as advertised. With the diff applied:

✅  Prevent `DefaultAppender` from appearing in a disabled block.
✅  Disable selection (using `user-select: none`) in disabled blocks.
✅  Prevent blocks from being inserted into a disabled block via global inserter.
✅  Prevent disabled blocks from being removed via keyboard shortcut.
✅  Prevent disabled blocks from being moved via List View drag and drop.
✅  Prevent block overlay from appearing on a disabled block. 

Tested without patch and can't detect any regressions in editing or template locking

**Comment by youknowriad** [comment]
Hello folks, this PR made the "type" performance 30% worse, I think we should definitely look into that.

**Comment by noisysocks** [comment]
Will look into it!

**Comment by noisysocks** [comment]
Quick update on fixing the performance regression here.

I've merged a few PRs that should reduce the number of times that various components re-render while typing:

https://github.com/WordPress/gutenberg/pull/51628
https://github.com/WordPress/gutenberg/pull/51518
https://github.com/WordPress/gutenberg/pull/51432
https://github.com/WordPress/gutenberg/pull/51319
https://github.com/WordPress/gutenberg/pull/51281

The main problem introduced by this PR though is that we're now calling `getBlockEditingMode()` in `useAppender()` which highlights two existing issues:

- `useAppender()` is written in a way that calculates `hideInserter` unnecessarily when `isParentSelected` is false. 
- `getBlockEditingMode()` is cached using `rememo` which actually hurts us because cache lookups are O(n).

Will open a PR to address these two issues.

**Comment by youknowriad** [comment]
Thanks for the follow-ups @noisysocks I appreciate it.

It's a bit unfortunate that we had this unexpected change in the metrics recently so we can't see the impact of these improvements on the graph so smoothly.

**Comment by youknowriad** [comment]
I've fixed codevitals.run (I had to remove some wrong intermediate numbers). It seems the numbers are not back to where they were before for the typing metric. Do you think #51675 will do the trick?

**Comment by noisysocks** [comment]
I think #51675 will definitely be the most impactful change millisecond wise. Let's merge it and see what happens 😅

**Comment by noisysocks** [comment]
I think that's fixed it @youknowriad. The spike at the end seems to be from codevitals getting confused and thinking that [7f4d64b6](https://github.com/WordPress/gutenberg/commit/7f4d64b62d08b6d300f8229ad44e6baeea08e7b1) comes after [a8ce505d](https://github.com/WordPress/gutenberg/commit/a8ce505db43cf18c8eb474c1d257f4e726c39114).

**Comment by youknowriad** [comment]
@noisysocks Thanks indeed. For the order, I do have a "date" saved to be able to order properly but I just discovered that we're always saving the same wrong date. Something to be fixes there 👍

**Pull request merged**
