### PR TITLE
[Button Block] Allow for text to wrap

### LINKED ISSUE #2249: Wrap button if long single line of text and depending on screen sizes
## Issue Overview
Button goes outside of wrapper container

## Steps to Reproduce (for bugs)
Type/Paste some long sentence inside button block.

- Chrome
- Vivaldi

## Current Behavior
Button goes outside of container and cover Trash icon. If button text is in several rows it will hide the other icon too.

### PR DESCRIPTION
**Pull request by jahvi**
This is my attempt to fix #2249

| Single Line | Multi Line | 
| --- | --- |
| screen shot 2017-08-22 at 9 11 00 pm| screen shot 2017-08-22 at 9 11 08 pm |

I'm hardcoding the top and bottom padding because I'm not sure if there's a way to get this dynamically based on the `$blocks-button__height` and maybe the font size?

### CODE REVIEW

**Comment by annaephox** [comment]
The buttons in the screenshots above look ok to me design wise

/cc @karmatosed

**Comment by karmatosed** [comment]
@jahvi interesting, have you tried this on various browsers? My concern is depending on device/browser this may not hold up.

**Comment by jahvi** [comment]
@karmatosed Yes, it's a relatively simple change in its core so it looks good in all browser/devices, here's a quick report (I feel like the text should always be aligned to the center in the frontend though, not sure if there's a reason for it or just an oversight):

<details>
<summary>Comparison Screenshots</summary>

**Chrome**

| Editor | Frontend |
| --- | --- |
| chrome_b | chrome |

**Firefox**

| Editor | Frontend |
| --- | --- |
| firefox_b | firefox |

**Safari**

| Editor | Frontend |
| --- | --- |
| safari_b | safari |

**Edge**

| Editor | Frontend |
| --- | --- |
| edge_b | edge |

**IE 11**

| Editor | Frontend |
| --- | --- |
| ie11_b | ios |

**Mobile**

| Android 7 | iOS 9 |
| --- | --- |
| android | ios |
</details>
<br>
I also noticed the URL input component overlaps the button in the editor when it has more than one line so I fixed that as well.
<br><br>
My only thought is that the <code>$blocks-button__height</code> variable is only used to calculate the button's border radius now, not the <code>height</code> and <code>line-height</code> as before so I'm wondering if I should get rid of it entirely and hardcode its value.

**Review by youknowriad — APPROVED** [review]
Rebased this, I think this is good to go 👍

**Pull request merged**
