### PR TITLE
Styles: Use `justify-content: flex-start` instead of `start`

### PR DESCRIPTION
**Pull request by tyxla**
## What?
This PR resolves two warnings in Storybook.

Don't merge just yet: #68237 might be a better alternative. 

## Why?
Just fixing warnings.

## How?
Using `justify-content: flex-start` instead of `justify-content: start`.

## Testing Instructions
* In Storybook, verify the warnings from the screenshot are gone.
* Test the following cases and verify there are no visual changes when comparing to trunk:
	* In Storybook, go to Button > Icon and type any text in the button (or just go to `?path=/story/components-button--icon&args=text:WordPress`)
	* In Storybook, go to Tabs > Vertical (or just go to `?path=/story/components-tabs--vertical`)
	* In the site editor, make sure you have done and saved at least a few changes to global styles. Then access global styles revisions from the Global Styles sidebar heading and compare the meta (the author info) under one or more revisions

### Testing Instructions for Keyboard
Same

## Screenshots or screencast 
Screenshot 2024-12-20 at 16 43 29

### CODE REVIEW

**Comment by tyxla** [comment]
I wasn't planning on adding a CHANGELOG entry, but happy to add one if y'all feel it's worthy.

**Review by mirka — COMMENTED** [review]
I was looking into this, and found:

- `start` and `flex-start` are not the same thing. `start` follows text direction and writing mode, while `flex-start` follows the main axis of a flexbox container.
- Browser support is currently acceptable ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#browser_compatibility), [Can I use](https://caniuse.com/?search=justify%20start)).
- Our version of `autoprefixer` is quite old (10.4.14, released nearly two years ago), and this warning has been [removed](https://github.com/postcss/autoprefixer/blob/dae6eb465da5640bb03ecda8b6d6b73e9ba26429/CHANGELOG.md?plain=1#L7-L9) since 10.4.19.

So regardless of whether these changes are appropriate for these three specific stylesheets, I'm wondering if the "correct" way to address this is to update our `autoprefixer` dependency.

**Comment by tyxla** [comment]
That makes sense, @mirka, thanks! 🙌 

It seems like there's no good reason to be on the older version.

I opened an alternative fix in #68237 - please take a look.

**Comment by tyxla** [comment]
Closed in favor of #68237.

**Pull request closed without merging**
