### PR TITLE
Font Library: remove tests from classes that were already merged in core

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Remove tests from classes that were recently merged in core: https://github.com/WordPress/wordpress-develop/pull/6027

## Why?
Updated tests fail if something of the class in Gutenberg repo change because the code used to run the tests come from core and not from the class in this repo.

Suggested here: https://github.com/WordPress/gutenberg/pull/58735#issuecomment-1930619629

## How?
Removing the tests

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM

**Comment by youknowriad** [comment]
Interesting that removing unit tests actually trigger failures in other unit tests. There might be some dependency between multiple tests? (which is not great)

**Comment by matiasbenedetto** [comment]
> Interesting that removing unit tests actually trigger failures in other unit tests. There might be some dependency between multiple tests? (which is not great)

`phpunit/tests/fonts/font-library/wpFontLibrary/base.php` was resetting the list of registered collections. After deleting it, the default collection was registered, so the test failed. This commit fixes the problem by resetting the collections registered before running the rest tests: https://github.com/WordPress/gutenberg/pull/58752/commits/6c30f7637f0dbbc704376b67ec2b536c9033a183

**Comment by creativecoder** [comment]
> This commit fixes the problem by resetting the collections registered before running the rest tests

Nice, this is an important addition. Let's make sure it gets into the Core PR, as it allows running the REST API tests independently without error.

**Pull request merged**
