### PR TITLE
List View: Visual and design improvements

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

In #26141 and #29727, a few tiny design refinements are shown that affect the modal dialog, and items in the list view. Specifically:

- A modal padding that affords a folding chevron on the left.
- A rounded modal and more visible drop shadow. 
- A 36px list view item height, without reducing the hit area size of mover controls.
- A full 24px indentation for nested items.

This PR addresses all of those, so that #26141 can be about adding the folding chevrons alone, and #29727 can be about adding the drag handle and graduating the drag and drop behavior.

## How has this been tested?

Please test every screen that leverages the list view, including the Site editor with the persistent list view, the post editor block navigation, and the modal list view from the Navigation block:

nav

Observe the new design is applied across, but with no regressions. 

Specifically please test also modal dialogs such as keyboard shortcuts or block manager, to see that the tweaked margin works well.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jameskoster** [comment]
Tests well for me. One small thought: 

Currently the indentation is multiples of 24px, and space between icon and label is 6px. If we increase those values to 28px and 8px respectively we see slightly improved visual alignment:

Screenshot 2021-03-11 at 12 17 11

Obviously the trade-off is the additional 6px of horizontal space consumed.

**Comment by jasmussen** [comment]
Excellent point, thank you. 

It's a bit trickier than just perfect metrics, though, because the icon does not fill out the full 24px space, so we actually have to optically hint a little bit. 

Here's the structure before I made any changes, which is a pure 24px indentation:

Screenshot 2021-03-12 at 09 14 26

Note the orange margin here, it's 6px, or half of the 12px grid. 

Screenshot 2021-03-12 at 09 14 37

Here's what happens if we change that to 24px + 6px:

Screenshot 2021-03-12 at 09 15 40

Now the icon footprint aligns perfectly to the text above. But the icon inside does not, it's indented.

The change I pushed, changes the indentation to 24px + 4px, i.e. 2px less than the text is indented:

Screenshot 2021-03-12 at 09 23 42

When pushing the change, it seemed better. But looking now, I'm not actually sure 🙈 

Here's a version where the indentation is 24px + 2px:

Screenshot 2021-03-12 at 09 24 14

That last change I think looks better, but I haven't pushed it. What do you think?

**Comment by jameskoster** [comment]
24 + 2 looks too cramped to my eye:

Screenshot 2021-03-12 at 10 54 08

28 + 8 or 24 + 4 feel like a sweet spot to me, the visual alignment seems good, and all values align to a 4px grid:

Screenshot 2021-03-12 at 11 07 32

**Comment by jasmussen** [comment]
Cool, 4 is what I pushed.

**Review by jameskoster — APPROVED** [review]
Figma component added https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=9490%3A85.

**Comment by jasmussen** [comment]
Thanks so much for the review. Because this one affects all modals, even if tested well, I'm going to let it sit for the weekend to gather additional sanity checks. I don't see how anything should be negatively affected, but still, now there's the weekend!

**Comment by jasmussen** [comment]
I gave the modals a spin:

Screenshot 2021-03-15 at 10 45 06

Screenshot 2021-03-15 at 10 45 20

Screenshot 2021-03-15 at 10 45 53

The change to modals is small. The extra horizontal padding is necessary for aligning the text with the items. I think it's worth it.

But it's also so trivial to change back that if it causes issues, I'll happily follow up.

**Pull request merged**
