### PR TITLE
Query Pagination: Don't render an empty container

### LINKED ISSUE #30522: Query Pagination block is output when empty
## Description
The wrapping div of the Query Pagination block is output when there are no previous/next/number links to display in it, which can result in extra margins on the page. It's extra noticeable if the block has a custom block style, like this one with vertical borders:

image

The screenshot shows a custom theme with a custom block style applied, but it behaves the same in TT1 Blocks without the block style.

## Step-by-step reproduction instructions
1. Activate TT1 Blocks.
2. Set the "Blog pages show at most" option in Settings → Reading to a higher number than the number of posts on the site.
3. View the blog and inspect the Query Pagination block.

## Expected behaviour
The wrapping div of the Query Pagination block shouldn't be output when empty.

## Actual behaviour
The wrapping div is output when the block is empty.

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.3.1
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes, TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Safari 14.0.3

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Fixes #30522.
Alternative to #33635.

Updates Query Pagination block to use `render_callback` for rendering container `div` element. Render callback won't render anything if block content is empty.

## How has this been tested?
1. Add Query block with pagination to page or template.
2. Change the `perPage` number so it shouldn't display pagination.
3. Verify that no empty pagination container is rendered.
4. Change the `perPage` once again, so now it renders paginations.
5. Verify that pagination works correctly.

### Example Query
```
<!-- wp:query {"queryId":17,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:post-title {"isLink":true} /-->

<!-- wp:post-featured-image {"isLink":true,"align":"wide"} /-->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator -->

<!-- wp:post-date /-->
<!-- /wp:post-template -->

<!-- wp:query-pagination -->
<div class="wp-block-query-pagination"><!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /--></div>
<!-- /wp:query-pagination --></div>
<!-- /wp:query -->
```

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jffng — APPROVED** [review]
Thank you for working on this! It works as advertised — no container is rendered if pagination is empty. 

I think this change requires block themes to update their templates if they reference the old query pagination markup. For example, `tt1-blocks`: https://github.com/WordPress/theme-experiments/blob/master/tt1-blocks/block-templates/index.html#L51 — this wrapping div has to be removed for the container not to be rendered.

Should that be documented somewhere?

**Comment by Mamaduka** [comment]
Hi, @jffng

With deprecation in place, old templates shouldn't break, but I think the update would be good.

> Should that be documented somewhere?

Not sure what would be the best place for this. I guess once FSE is stable, we will include similar changes in `make.wp/core` posts.

**Review by carolinan — APPROVED** [review]
Works well.
And I do not see any block validation errors or warnings with themes that still use the old markup.

**Comment by Mamaduka** [comment]
Thanks for testing/reviews, @jffng and @carolinan.

**Pull request merged**
