### PR TITLE
Add caching to schema of REST API.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## What?
Improve performance of the REST API call by caching schema data. See ticket for more details - https://core.trac.wordpress.org/ticket/58657#ticket

### CODE REVIEW

**Review by kadamwhite — APPROVED** [review]
Thanks for catching that missing piece, @spacedmonkey :+1:

**Review by getdave — APPROVED** [review]
Looks good. Thanks for catching this 👍 

For anyone's future reference this is documented at https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/#caching-schema

**Comment by getdave** [comment]
@spacedmonkey Can I confirm whether this change still needs backporting to Core for 6.4? Thank you.

**Comment by spacedmonkey** [comment]
@getdave This ticket was resolved in the WP 6.3 release. See https://github.com/WordPress/wordpress-develop/commit/7faab129f56779d0576bed37d025ef16bcb95bf7

**Comment by getdave** [comment]
Thanks. I got a ping about it today re: 6.4 and so it's good to know it's already sorted. Thanks Jonny 👍

**Pull request merged**
