### PR TITLE
Added a snippet for observing the browser when running e2e tests

### PR DESCRIPTION
**Pull request by draganescu**
## Description
Added instructions on how to run the e2e tests while observing them in the browser in the handbook.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Great first PR 🎉

**Review by gziolo — APPROVED** [review]
Yes, thanks for adding this explanation. 

Aside: Do you think it would make sense to convert those env variables into command args?

**Comment by draganescu** [comment]
@gziolo yes I do, it's a lot easier than that whole string of stuff just to have a command like "--interactive --speed=80"

**Comment by talldan** [comment]
@gziolo yep, could also have a handy shortcut like:
```
npm run test-e2e:watch --observe
```

**Comment by talldan** [comment]
A single shortcut is also an option:
```
npm run test-e2e:watch --interactive
```

**Comment by gziolo** [comment]
I like this proposal a lot, we would have to use `getCliArg` (https://github.com/WordPress/gutenberg/blob/master/packages/scripts/utils/cli.js#L18) or something more advanced like https://www.npmjs.com/package/yargs-parser to get the speed.

For starts, we can override env globals inside this script:
https://github.com/WordPress/gutenberg/blob/master/packages/scripts/scripts/test-e2e.js

Do you want to work on it? Should we open an issue with what you proposed?

**Comment by gziolo** [comment]
Actually, there an issue already which is about improving our docs: https://github.com/WordPress/gutenberg/issues/8319. We could combine all of that into one effort.

**Comment by draganescu** [comment]
Hi @gziolo just a heads up that I'm looking into this :)

**Pull request merged**
