### PR TITLE
Adds justification controls to Social Block

### LINKED ISSUE #18951: Social Block: Update alignment controls
#18909 added ~alignment~ justification settings to the Navigation block. Let's update the Social Links block with those same settings.

Currently those settings are a little buggy, losing the border around the block and adding some margin.

### PR DESCRIPTION
**Pull request by getdave**
Screen Shot 2020-01-02 at 14 07 35

## Description

Closes https://github.com/WordPress/gutenberg/issues/18951.

Adds the ability to justify the horiztonal alignment of the Social Icons. This is achieved similarly to the Navigation Block.

As with [that example](https://github.com/WordPress/gutenberg/pull/18909), please note the distinction between "align" (which is really "float") and "justify" as terms. 

I have noted that _align_ (as opposed to _justify_) left/right is already available on this Block but it actually applies float left/right to the Block _as a whole_ rather than moving the inner items. 

Justification controls allow the user to manipulate the arrangement of the _inner_ items whilst preserving (or manipulating separately) the positioning of the outer Block. Note, however, that this causes some ambiguity in the UI within the Editor when align and justify are applied together. It would be great if @jasmussen were able to advise on this as he was involved in the Nav Block and has the requisite context.

## Questions

* how can we resolve the layout within the editor when applying align and justification at the same time?
* should we add align wide/full to this Block?
* should we create a reusable "BlockJustificationToolbar" as per the `BlockAlignmentToolbar` and `BlockVerticalAlignmentToolbar`?

## How has this been tested?

Manual testing.

1. Add Social Block
2. Add some items.
3. Toggle the Justification.

#### Editor
Screen Capture on 2020-01-02 at 14-08-13

#### Frontend

Note: I've contained the Block within a Group Block with a background to show the boundaries of the justification:

Screen Shot 2020-01-02 at 14 40 57

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by youknowriad** [comment]
In other blocks like "paragraph" we also have "align" and "text align". I wonder if "justify" is just another way of calling "text align".

There's also an issue about addiing a way to clear floats for all blocks which will create multiiple ways to achieve the same behavior.

**Comment by getdave** [comment]
> I wonder if "justify" is just another way of calling "text align".

It is...sort of. But (IMHO) "justify" is more semantically correct. That said, if UX shows users understand "text align" to mean "control justification of content along the main axis" then who am I to argue.

I would say however, that text align feels very specific to the literal interpretation of "aligning some _text_". Whereas justify as a concept is to control position or space something along a line of content.

I also draw on the [CSS Flexbox definitions](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content) which applies the "justify" nomenclature to denote spacing along the main axis:

> The CSS justify-content property defines how the browser distributes space between and around content items along the main-axis of a flex container, and the inline axis of a grid container.

**Comment by getdave** [comment]
I'd value any input on the questions posed above under `Questions`.

**Comment by shaunandrews** [comment]
> I have noted that align (as opposed to justify) left/right is already available on this Block but it actually applies float left/right to the Block as a whole rather than moving the inner items.

> Justification controls allow the user to manipulate the arrangement of the inner items whilst preserving (or manipulating separately) the positioning of the outer Block. Note, however, that this causes some ambiguity in the UI within the Editor when align and justify are applied together.

I struggle with this distinction. To me, the word "justify" is [strongly associated with text](https://practicaltypography.com/justified-text.html). It feels like we're using justify because align is already in use. Maybe we should change the word align to "position", and then replace "justify" with "align".

image

I'm not sure we need to have a separate icon when aligning text vs. blocks (or any other elements) — the text align icons seem to work fine for both situations.

**Comment by obenland** [comment]
I like @shaunandrews‘ idea. Updating the verbiage in that way feels more natural to me.

**Comment by mtias** [comment]
I like simplifying to alignment with the text icons. We might want to support `space-between` in addition to `center`, maybe also `space-around`. How would we represent them?

**Comment by ZebulanStanphill** [comment]
@shaunandrews I agree that "position" works a lot better for what we currently call "alignment" in the block toolbar. "position wide" makes a lot more sense than "align wide".

@mtias Perhaps those options could be represented with icons similar to this:
space-between-and-space-around-icon-mockups

**Comment by draganescu** [comment]
> should we create a reusable "BlockJustificationToolbar" as per the BlockAlignmentToolbar and BlockVerticalAlignmentToolbar?

With the addition of the buttons block this seems even more ... justified :D (sorry)

**Comment by getdave** [comment]
@draganescu You win the internet 😆 

---------

Thanks for everyone's comments. To summarise:

* Rename to `Positioning`
* Support more Flex properties

I'm not clear on the proposed route for icons. Are we going with what @shaunandrews posted above plus the additional icons (yet to be provided) for space-around/between?

**Comment by ZebulanStanphill** [comment]
I was confused and thought the "positioning" name was being suggested for the current `alignleft`/`alignright`/`alignwide`/etc. toolbar. I still think "justify" or "item alignment" would be a better term for the the toolbar being added in this PR.

**Comment by mtias** [comment]
Yes, I thought we were discussing using `alignment` for the distributions of elements within the container (left, center, space-between, etc) and `position` for how the container is displayed (wide, full-width, floated, etc).

**Comment by shaunandrews** [comment]
Quick reference from Figma that offers similar options:

image

...and Sketch's variation:

image

**Comment by jasmussen** [comment]
We have justification controls for navigation, social links, and buttons now. I guess this PR can be closed? Thanks for all the work!

**Comment by mkaz** [comment]
Closed in https://github.com/WordPress/gutenberg/pull/28980

**Pull request closed without merging**
