### PR TITLE
Move "continue writing" next to inserter and show on hover.

### PR DESCRIPTION
**Pull request by mtias**
image

### CODE REVIEW

**Comment by nylen** [comment]
Related: #1501, #1502

**Comment by jasmussen** [comment]
I like the other exploration.

The problem we want to solve is very specific: **if a non-text block is the last block in the list, you should have an easier way to continue writing text, than to first have to click Insert > Text**.

The "Continue writing..." did this, though I agree perhaps not in an elegant way. Both solutions presented here address this also. 

In the past, ideas similar to your "other exploration" have been brought up. I can't recall the specific people who suggested it, but @shaunandrews and @paaljoachim come to mind. My concern back then was that this area below the inserter showed `n` recent blocks, and that these were always visible. I was against this because I was concerned this area would quickly get cluttered, in an editor that is already very rich on interface. Also because if the blocks here changed per recency, you wouldn't be able to develop any spatial memory.

The fading out of everything but the plus, as well as the fact that there are only two blocks there —  text and image —  feels like it can address those concerns. In recognizing that I was probably wrong to disagree with the ideas presented by Shaun and Joachim (and maybe others) in the past, here's an acknowledgement that _you were all probably on to something_, and I was probably wrong.

Therefore, thumbs up from me, provided this can be made accessible (if it isn't already, it possibly is), let's try this and iterate.

**Comment by jasmussen** [comment]
Looks good in latest version! Remember to use `$default-font` for the buttons there, so they get to be system fonts (because it's UI).

**Comment by mtias** [comment]
Push failed :)

**Comment by paaljoachim** [comment]
I added a wireframe of having the text and image next to the inserter a few days ago in an issue about what happens when clicking enter once and twice etc. 
I am not able to locate the issue right now...

**Comment by jasmussen** [comment]
@paaljoachim is this the one? https://github.com/WordPress/gutenberg/issues/1081

In any case, the idea is virtually the same, and I apologize for flip flopping on this. I do think it's valuable that we tried the "Continue writing" idea, though clearly that didn't work when we also had placeholder text. I will admit my mistakes ;)

**Comment by paaljoachim** [comment]
We are all brain storming on ideas. One idea leads to the next..:) It all matures along the way.

**Pull request merged**
