### PR TITLE
Duotone filter not rendering in some places

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?

Fixing duotone rendering in the pattern selection panel.

## Why?

This is necessary to make the pattern preview accurate.

## How?

With this change, the duotone presets will render if the block supports duotone and has no custom duotone applied.

Previously we were rendering just the custom duotone applied to the current block but if the block has a filter applied globally using `theme.json`, the duotone doesn't work because the preset filters are not rendered.

## Testing Instructions

1. Use a theme that supports duotone for example Skatepark
2. Create a new post or page
3. Open the add pattern panel
4. See the patterns that include blocks without a custom duotone applied but with duotone presets in `theme.json` for example "Full-width image with aside caption"  from Skatepark.

## Screenshots or screencast 

| **Before:**  | **After:** |
| ------------- | ------------- |
| image  | image |
| image | image |

### CODE REVIEW

**Review by ajlende — CHANGES_REQUESTED** [review]
I don't think we should need to edit duotone.js to fix this. The `editor.BlockListBlock` hook that you've edited is for rendering custom per-block filters. It is run on every block and should only take the block attributes and render the duotone filters associated with that block.

Did you figure out why some previews were rendering but not others?

**Comment by matiasbenedetto** [comment]
> I don't think we should need to edit duotone.js to fix this. 

Ok, I'll explore an alternative.

> Did you figure out why some previews were rendering but not others?

Yep, the answer is in the PR description:


> Previously, we were rendering just the custom duotone applied to the current block, but if the block has a filter applied globally using theme.json, the duotone doesn't work because the preset filters are not rendered.

**Comment by ajlende** [comment]
> > Did you figure out why some previews were rendering but not others?
>
> Previously, we were rendering just the custom duotone applied to the current block, but if the block has a filter applied globally using theme.json, **the duotone doesn't work because the preset filters are not rendered**.

Maybe a more apt question would be this: why are all the global styles being rendered in the previews except for the duotone ones?

**Comment by matiasbenedetto** [comment]
I'm closing this PR in favor of this alternative approach: https://github.com/WordPress/gutenberg/pull/41249

**Pull request closed without merging**
