### PR TITLE
Use a single Github workflow for all the PR code validation jobs

### PR DESCRIPTION
**Pull request by youknowriad**
The idea of the PR is that we might have been using GitHub Actions in the wrong way. We just copied pre-existing travis jobs as "workflows" where I think the idea of Github is more around reusing "actions" and not "workflows". So we could:

 - have a Pull Request workflow 
 - have a Deploy workflow

This enables some potential Github features (job visualization, jobs dependencies...).

In this PR, I'm approaching that by gathering all "test" workflows into a single one.

I think at the moment we're losing the "path" and "path-ignore" configs from the different specific workflows but we may be able to approach these using reusable GitHub Actions and "if" statements for jobs.

### CODE REVIEW

**Comment by ockham** [comment]
Not sure it's worth it for the PR/code validation workflow. Some thoughts:

- This does look nice: https://github.com/WordPress/gutenberg/actions/runs/482994349 -- but I'm not sure there's a lot of immediate benefit, compared to having these checks in separate workflows.
- IMO, the main difference in the release/build workflow is that individual jobs depend on each other (release creation `needs` -- and thus, waits -- for the `build` job).
- We _could_ explore if that'd be applicable to the PR/code validation workflow tho: Build the plugin once, store as an artifact; make the other jobs depend on the build (well, the ones that need a build anyway -- not sure how many of them really do), and use the artifact.

If we find out that there's not too much benefit in this, we might keep the workflows separate -- it's a bit nicer for editing them IMO :slightly_smiling_face:

**Comment by gziolo** [comment]
Can you restart a single e2e job when it fails or does it restart everything bundled together? Can you group code and non-code verifications separately to use path matching (e.g. PHP unit tests could be skipped when changing Docs)? This are my biggest concerns but otherwise I like consolidation 😃

I'm following this PR as I still want to run some basic code checks on Node 12.x.

**Comment by youknowriad** [comment]
> Can you restart a single e2e job when it fails or does it restart everything bundled together?

No, not possible for now, not sure if Github will implement this or not and this is my main blocker now too

>  Can you group code and non-code verifications separately to use path matching

I think it's very arguable with our current step whether this is useful or not (markdown only PRs are very rare), but yes, it's probably doable, I  just didn't find the right action to do it yet.

**Comment by youknowriad** [comment]
Closing for now, let's try for deployment first.

**Pull request closed without merging**
