### PR TITLE
Remove unnecessary and flaky snapshot test from ResponsiveBlockControl

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
See https://github.com/WordPress/gutenberg/pull/26078#discussion_r506499530 for the original discussion. This test does not appear to add value to the test suite, especially when we're already explicitly testing many parts of the rendered component.

Here's another example PR where this test fails for no good reason: https://github.com/WordPress/gutenberg/pull/26369

## Types of changes
Updating a test.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Blocks https://github.com/WordPress/gutenberg/pull/26369

### CODE REVIEW

**Comment by ItsJonQ** [comment]
I'm 👍 with this change. I've experienced several rounds of this particular snapshot needing updating in the past. I've never worked with this particular component before. I'm curious to hear the thoughts from those who have.

**Comment by saramarcondes** [comment]
@getdave Do you have any insight into this test? Do you think it's okay or bad to remove the snapshot given that we're already testing for a lot of the output explicitly in the same test?

**Comment by getdave** [comment]
> @getdave Do you have any insight into this test? Do you think it's okay or bad to remove the snapshot given that we're already testing for a lot of the output explicitly in the same test?

I'd say you're ok to remove the snapshot. I'm no longer a fan of them anyway and feel they add little or no value here.

Thanks for fixing.

**Review by sirreal — APPROVED** [review]
It seems folks agree to remove this. I'll repeat the following as a desirable direction generally:

> I looked around a bit and there appears to be an official solution for component snapshots with emotion: [`jest-emotion`](https://emotion.sh/docs/jest-emotion).
> 
> If the plan is to continue using emotion it's probably worth getting that set up and working well.

**Comment by saramarcondes** [comment]
@sirreal I'll take a look at this today and open a PR.

@ItsJonQ Is there something similar to `jest-emotion` for G2?

**Comment by ItsJonQ** [comment]
> @ItsJonQ Is there something similar to jest-emotion for G2?

@saramarcondes Funny enough.. I haven't run into the same flakey issues in G2 as I have in Gutenberg.

G2 also uses Emotion, Jest, and Snapshots 🤔 
(G2 doesn't use `jest-emotion` though)

**Pull request merged**
