### PR TITLE
Remove duplicate CopyHanddler

### PR DESCRIPTION
**Pull request by youknowriad**
This component was used twice for not valid reason I think.

### CODE REVIEW

**Review by mcsf — APPROVED** [review]
👍

**Comment by youknowriad** [comment]
I'm surprised by the number of failing e2e tests here, I'll have to circle back a bit later.

**Comment by youknowriad** [comment]
@aduth It looks like this removal affects the "block-editor-writing-flow__click-redirect" do you happen to know why?

**Comment by aduth** [comment]
@youknowriad If I recall correctly, there may be some styles which depend very rigidly on the element hierarchy?

**Comment by aduth** [comment]
https://github.com/WordPress/gutenberg/blob/2f832648001db19cae157ef4f07f39896fa6ee2a/packages/edit-post/src/components/visual-editor/style.scss#L21-L26

**Comment by youknowriad** [comment]
Thanks for the hint @aduth

**Comment by aduth** [comment]
There appear to be some possibly-legitimate build failures now?

**Comment by youknowriad** [comment]
@aduth @developit I believe this PR is showing bad results for the bundle size diff. As in reality it only affects the bundle size of `build/edit-post/index.js` 

I think it's because it's an old unrebased PR but I've had trouble reproducing it with a test PR.

**Review by aduth — APPROVED** [review]
Works 👍

**Pull request merged**
