### PR TITLE
Interface: move Fullscreen mode component to interface package

### PR DESCRIPTION
**Pull request by vindl**
## Description

Move Fullscreen mode component from block-editor to interface package.

## How has this been tested?

Toggle the fullscreen mode in post editor and site editor and verify that they still work as expected.

## Types of changes

Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
Smoke tested the editors.  This works well on my end!

**Review by noahtallen — APPROVED** [review]
This works perfectly for me as well. My only thought (similar to the other PR) is that we should probably update style.scss. For example, `edit-post-fullscreen-mode__slide-in-animation` could probably be renamed. `edit-post-header` also seems out of place (especially since we use this from edit-site), but that might need updated somewhere else

**Comment by youknowriad** [comment]
I personally think the header animation is not useful at all epsecially since it's fullscreen by default, I'd vote for removing it which would save us the need to move it to the right package (edit-post since the element is rendered there) 

cc @kjellr

**Comment by vindl** [comment]
> I personally think the header animation is not useful at all epsecially since it's fullscreen by default, I'd vote for removing it which would save us the need to move it to the right package (edit-post since the element is rendered there)

I agree, especially in light of this exploration which will make it obsolete https://github.com/WordPress/gutenberg/pull/21121.

**Comment by vindl** [comment]
I removed the `__experimental` prefix and animation styles in 72246c87ca8f8a468d28d58b69fa8e970efccc7b.

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Thanks

**Pull request merged**
