### PR TITLE
Cherry pick commits for WP 6.5 Beta 3

### PR DESCRIPTION
**Pull request by getdave**
## What?

Cherry picks the following commits:

### Automatically Picked

#59159 – Search block: use font size for search icon
#59255 – Navigation: Add missing empty space to print out valid HTML.
#59295 – Title & Featured Image: Hide non content controls when block editing mode is 'contentOnly'
#59261 – Style Book: should persist when browsing global styles panels
#58828 – Shadows: Improve accessibility of shadows dropdown
#59283 – Fix query loop with block bindings not working in the editor as expected
#59285 – Update pages dataview icons, add 'drafts' icon
#59233 – Data views: Display all checkboxes when a single item is selected
#59220 – Revert removal of Nav fallback auto embed
#59205 – Font Library: add option to revoke access to Google Fonts
#59314 – Update font collection JSON schema to accommodate the changes made in wp_register_font_collection
#59231 – Update filter control position
#59312 – Fix: Multi line comment format on footnotes block.
#58950 – Disable selection checkbox if no bulk actions are eligible
#59036 – Use NavigatorProvider in Font Library Modal
#59309 – Shadow: Fix layout collapse when indicator is selected
#59320 – Block bindings: fix Enter on disabled rich text
#59296 – Cover block: Clear aspect ratio value when toggling full height
#58766 – Disable core shadow presets by default, let themes opt-in
#59367 – Block Hooks: Take controlled blocks into account for toggle state
#59371 – Block Hooks: Add help text to Plugins panel.
#59011 – Update sidebar titles for Template and Page management data views
#59105 – Editor: Fix post type check in isEditingTemplate selector
#59297 – Fix `DisableNonPageContentBlocks`
#59388 – Cover Block: Restore overflow: clip rule to allow border radius again
#59358 – Dynamically set border panel label based on the controls available
#59363 – Reposition pattern detail icon
#59191 – Cover block: clear the min height field when aspect ratio is set
#59158 – Block Mover: Unify visual separator when show button label is on
#59170 – Fix resetting individual blocks to empty optional values for Pattern Overrides
#58916 – Patterns: disable image caption if part of synced pattern
#59269 – Remove unneeded pattern overrides translation strings
#59065 – Fix Navigation link control overlapping issue
#59179 – Preserve bindings metadata in block transforms
#59187 – Interactivity API: Improve context merges using proxies
#59267 – Top Toolbar: Fix 'collapsed' state synchronization
#59273 – Interactivity API: Prevent unwanted subscriptions to inherited context props
#59241 – Font collection pagination: add min height to avoid infinite number
#59274 – URLPopover: restore min-width style
#59236 – Apply hover styles to filter chip while being configured
#59284 – Update page selector appearance
#59379 – Fixed the font family modal to open in  state when a font is already selected.
~#59333 – Font Library: create post types on init hook~ - I [dropped this one](https://github.com/WordPress/gutenberg/pull/59333#issuecomment-1966442721)

### Manually Picked

Note that the following commits could not be automatically picked by the script and will be manually picked:

- [x] #59220 - I checked and this commit is now empty. I skipped this one.
- [x] #59205 - `const` definitions at top of file. I resolved in favour of single `LOCAL_STORAGE_ITEM`.
- [x] #59036 - I was able to cleanly cherry pick this PR manually. No conflicts.
- [x] #57134 - resolved manually. CHANGELOG changes only.
- [x] ~#59331 - I have not included this one as it did not get merged into `trunk`.~
- [x] #58817 - I had to do this one manually as the cherry pick script failed due to a missing `merge_commit_sha` in API response.
- [x] #59201 - I had to do this one manually as the cherry pick script failed due to a missing `merge_commit_sha` in API response.
- [x] #59039 - I had to do this one manually as the cherry pick script failed due to a missing `merge_commit_sha` in API response.
- [x] #59241 

## How?

⚠️ Note that there were quite a few PRs that needed to be manually resolved.

- Run cherry pick script locally
- Manually resolve any failed cherry picks
- Re-run the cherry pick script to include a 2nd round of PRs (this is due to known bug in script)
- Resolve [errors](https://github.com/WordPress/gutenberg/issues/59398) 
- Manually resolve any failed cherry picks
- Double check no outstanding PRs by querying GH API at `https://api.github.com/search/issues?q=is:pr state:closed sort:updated label:"Backport to WP Beta/RC" repo:WordPress/gutenberg&per_page=100`

## Screenshots or screencast 

Co-authored-by: ramonjd <ramonopoly@git.wordpress.org>
Co-authored-by: juanfra <juanfra@git.wordpress.org>
Co-authored-by: noisysocks <noisysocks@git.wordpress.org>
Co-authored-by: madhusudhand <madhudollu@git.wordpress.org>
Co-authored-by: SantosGuillamot <santosguillamot@git.wordpress.org>
Co-authored-by: jameskoster <jameskoster@git.wordpress.org>
Co-authored-by: getdave <get_dave@git.wordpress.org>
Co-authored-by: matiasbenedetto <mmaattiiaass@git.wordpress.org>
Co-authored-by: jorgefilipecosta <jorgefilipecosta@git.wordpress.org>
Co-authored-by: t-hamano <wildworks@git.wordpress.org>
Co-authored-by: andrewserong <andrewserong@git.wordpress.org>
Co-authored-by: ockham <bernhard-reiter@git.wordpress.org>
Co-authored-by: mattgrshaw <mattshaw@git.wordpress.org>
Co-authored-by: carolinan <poena@git.wordpress.org>
Co-authored-by: pbking <pbking@git.wordpress.org>
Co-authored-by: ntsekouras <ntsekouras@git.wordpress.org>
Co-authored-by: c4rl0sbr4v0 <cbravobernal@git.wordpress.org>
Co-authored-by: kevin940726 <kevin940726@git.wordpress.org>
Co-authored-by: glendaviesnz <glendaviesnz@git.wordpress.org>
Co-authored-by: sunil25393 <sunil25393@git.wordpress.org>
Co-authored-by: DAreRodz <darerodz@git.wordpress.org>
Co-authored-by: Mamaduka <mamaduka@git.wordpress.org>
Co-authored-by: ellatrix <ellatrix@git.wordpress.org>
Co-authored-by: youknowriad <youknowriad@git.wordpress.org>

### CODE REVIEW

**Comment by getdave** [comment]
2 major next steps:

1. Manually cherry pick the PRs that could not be automated (see description).
2. Go through all the PRs to check that none were missed as in Beta 2 some PRs were missed by the script.

**Review by youknowriad — APPROVED** [review]

**Comment by getdave** [comment]
We will need to "Rebase and merge" this PR and not "Squash" it.

**Comment by getdave** [comment]
~Let's hold on merge as we may need to drop https://github.com/WordPress/gutenberg/pull/59333~

I dropped https://github.com/WordPress/gutenberg/pull/59333 as per https://github.com/WordPress/gutenberg/pull/59333#issuecomment-1966442721.

**Comment by getdave** [comment]
🚀 LGTM - remember to `Rebase and merge` 🙏

**Comment by getdave** [comment]
Playwright tests failing due to missing https://github.com/WordPress/gutenberg/pull/59356.

**Update**: i cherry picked that PR.

**Comment by getdave** [comment]
PHPUnit failures being resolved in https://github.com/WordPress/gutenberg/pull/59402

**Comment by getdave** [comment]
OK the tests are now ✅ . Let's get this merged in order that packages are released and synced ready for WP 6.5 Beta 3.

**Pull request merged**
