### PR TITLE
Adding keyword 'download' to the file block for easier searching.

### PR DESCRIPTION
**Pull request by mapk**
## Description
Added a new keyword to the File block for easier searching: `download`.

## How has this been tested?
Tested locally.

## Screenshots

Screen Shot 2019-12-07 at 10 04 01 AM

## Types of changes
Non-breaking changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by melchoyce** [comment]
Is it okay that `package-lock.json` changed too?

**Comment by aduth** [comment]
> Is it okay that `package-lock.json` changed too?

It doesn't seem to me that it should be expected to be updated here.

**Comment by karmatosed** [comment]
Yes, the .json file isn't needed and likely came from doing an npm install audit fix, or something localhost side. @mapk can you push a PR without that file, please?

**Comment by mapk** [comment]
Oh danggit, @melchoyce. I think you're right. Let me see if I can fix that.

**Review by aduth — APPROVED** [review]

**Comment by mapk** [comment]
Thanks, @aduth for figuring out how to reset the package-lock.json file again. I appreciate the insight! 👍

**Pull request merged**
