### PR TITLE
Change "Page Templates" label in Experiments settings

### LINKED ISSUE #18874: State what page templates are clearly in experiments
The experiments section of Gutenberg is amazing but it can be confusing to understand what each is. Just saying 'page templates' really adds to that confusion.

image

It would be great to say what this is as page templates already exist in WordPress.

### PR DESCRIPTION
**Pull request by musus**
## Description
Change labels in more detail

Fixes: #18874

## Screenshots 
ScreenShot 123

### CODE REVIEW

**Comment by draganescu** [comment]
Hi @musus what prompted you do make this PR?

**Comment by musus** [comment]
Hi @draganescu 
We decided to try a Good First bug on WordCamp Tokyo's Contributor Day last year. Are there any problems?

**Comment by draganescu** [comment]
Awesome @musus thanks for picking up the issue. I missed the related issue in the title so I didn't know what this was about.

This experiment is used in the mobile implementation of Gutenberg and so maybe a better name would be "Mobile Page Template Selector"? 

Can you change it like so and solve the conflicting file? Thanks!

**Comment by skorasaurus** [comment]
Thanks for originally making this PR. 

This label has been removed from the experiments settings page; so this pull request is no longer applicable. https://github.com/WordPress/gutenberg/blob/trunk/lib/experiments-page.php

**Pull request closed without merging**
