### PR TITLE
Add Data View Shortcuts: Manage Templates, Pages, and Patterns

### PR DESCRIPTION
**Pull request by karthick-murugan**
## What?
Part of https://github.com/WordPress/gutenberg/issues/60806

Add data view shortcuts.

## Why?
Currently there is no command to view data shortcuts.

## How?
This PR adds shortcut for Pages/Drafts which will navigate to List view of Draft pages in Site Editor.

## Testing Instructions

- Log in to the Dashboard: Access your WordPress admin dashboard by entering your credentials.
- Navigate to the Site Editor: From the dashboard, locate and click on the Site Editor option in the left-hand menu.
- Initiate a Search: In the Site Editor, click on the search icon located at the top left corner of the interface.
- Search for Drafts: Enter the term "Drafts" in the search bar. The search results will display the Drafts/Pages option.
- Select Drafts/Pages: Click on the Drafts/Pages entry from the search results. This action will direct you to the List view of all draft pages within the Site Editor.

## Screenshots or screencast 

https://github.com/user-attachments/assets/0a527642-61e9-4029-9f35-8d7d6f8c1f14

### CODE REVIEW

**Comment by karthick-murugan** [comment]
@t-hamano - Please have a look at this PR if you have some time. Thanks in advance.

**Comment by t-hamano** [comment]
Thanks for the PR! 

I assume that the intention of #60806 is not to add a single command for the draft page list. I think the aim is to detect all views available in the data view and add those commands _automatically_.

Before we move forward with this PR, let's clarify what #60806 is aiming to achieve.

cc @jameskoster

**Comment by karthick-murugan** [comment]
> Thanks for the PR!
> 
> I assume that the intention of #60806 is not to add a single command for the draft page list. I think the aim is to detect all views available in the data view and add those commands _automatically_.

Thank you for the feedback @t-hamano 

You’re absolutely right that the aim of #60806 is to detect all views available in the data view and add those commands automatically. To begin with, I’ve added a single command for Draft pages in this PR as a starting point.

The idea here is to approach this incrementally, where each command could potentially have a separate PR for better focus and review. This will also allow us to refine and ensure the implementation is robust before adding more commands.

Looking forward to your thoughts!

cc @jameskoster

**Comment by jameskoster** [comment]
Yeah the rough idea was to register commands automatically, based on existing data views. 

That said, I don't know how/if data views are registered at a global level, so perhaps it's not possible to do that yet?

**Comment by karthick-murugan** [comment]
Hi @jameskoster,

Following your suggestion in [#60806](https://github.com/WordPress/gutenberg/issues/60806#issuecomment-2553444478), I’ve updated the command palette to include commands like "Manage templates", "Manage pages", and "Manage patterns". You can find the implementation in the video linked below:

🎥 [Implementation Video]

https://github.com/user-attachments/assets/591f5007-d683-4126-b5cb-ed1ef1a623de

I’d appreciate your feedback on whether these updates meet expectations or if additional commands should be included.

@t-hamano, I would also like your input on any additional commands to consider based on your suggestions, ensuring the implementation aligns with all use cases.

Looking forward to your thoughts!

**Comment by jameskoster** [comment]
I noticed in your video that are already commands to access those dataviews, I don't know if they existed when https://github.com/WordPress/gutenberg/issues/60806 was opened, but sorry for the wild goose chase in any case!

Perhaps instead of adding the new commands we just update the labels to read 'Manage Patterns', etc. Currently they just read 'Patterns', 'Templates', etc. which is a bit ambiguous.

**Comment by karthick-murugan** [comment]
> I noticed in your video that are already commands to access those dataviews, I don't know if they existed when #60806 was opened, but sorry for the wild goose chase in any case!
> 
> Perhaps instead of adding the new commands we just update the labels to read 'Manage Patterns', etc. Currently they just read 'Patterns', 'Templates', etc. which is a bit ambiguous.

@jameskoster - Removed the newly added commands and updated the labels to "Manage Pages", "Manage Patterns", "Manage Templates". Please have a look at this video.


https://github.com/user-attachments/assets/4662785b-312f-4685-abbd-48702b89b33b

cc @t-hamano

**Comment by t-hamano** [comment]
Thanks for addressing this issue.

Before moving forward with the code implementation, I think we need to investigate the current behavior and explore what would be ideal. Otherwise, we may end up rewriting the code multiple times.

Currently, there are already commands for all screens: Navigation, Styles, Pages, Templates, and Patterns. So, if we move forward with this PR, we will just need to add "Manage" to those command names.

However, when it comes to screen titles, the word "Manage" has been purposefully removed (See #62107). So at this point I'm not sure if it's OK to use the word "manage" in the command palette.

Personally, I prefer not to include a verb unless the command itself has some action. If it's simply navigating to a page, I expect the command palette to show only the page title.

Let's hear the opinions of other members of the @WordPress/gutenberg-design team as well.

**Comment by karthick-murugan** [comment]
> Let's hear the opinions of other members of the @WordPress/gutenberg-design team as well.

Thank you, @t-hamano, for taking the time to provide this detailed feedback. I appreciate the context and will hold off on further changes until we have additional input from the design team. I’ll proceed as per their recommendations once they’ve shared their thoughts.

**Comment by jameskoster** [comment]
I don't have a strong opinion, I'm happy to defer to @t-hamano on this :) 

We should make a decision on whether or not to close https://github.com/WordPress/gutenberg/issues/60806 though.

**Comment by t-hamano** [comment]
> We should make a decision on whether or not to close https://github.com/WordPress/gutenberg/issues/60806 though.

I searched past issues and found that #60806 may be part of #50407. Perhaps it would be better to close #60806 and discuss it more comprehensively in #50407. #50407 seems to be still under discussion, so it might be good to get a consensus on the basic direction first.

**Comment by karthick-murugan** [comment]
https://github.com/WordPress/gutenberg/issues/60806 - Original Issue has been closed with reason "Not Planned"

**Pull request closed without merging**
