### PR TITLE
Use a DropdownMenu for menu selection in the navigation screen

### LINKED ISSUE #25312: Navigation page: the "Currently editing" select element should not trigger a page re-render on change
**Describe the bug**

In the new Navigation page, the "Currently editing" select element triggers a page re-render when the change event fires. This is a known accessibility barrier as changes of context should always happen on explicit user activation. Worth reminding this behavior is dangerous especially on Windows, where the select elements options can be changed even _keeping the select closed_. For more details, please refer to this Trac ticket:

**Review the usage of the change event on select elements**
https://core.trac.wordpress.org/ticket/40925

The WCAG guidelines explicitly state to provide a submit button to initiate a change of context.

Also, worth noting the current Menus page does have a button to submit the select element changed value, and for good reasons:

Screenshot 2020-09-14 at 19 28 47

**To reproduce**

Animated GIF of the current behavior:

navigation select new

- on Windows
- tab to the Select element
- use the down arrow key to change value 
- as soon as the value changes, the page re-renders showing the new menu even if the user hasn't explicitly submitted the change
- this is even more harming because focus is then moved to the menu being edited: there's a specific issue for that, see #25298 

**Expected behavior**
The page to not re-render on the change event. There should be a button to initiate a change of context.

**Editor version (please complete the following information):**
- WordPress version: 5.6 trunk
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? plugin
- If the Gutenberg plugin is installed, which version is it? 9.0.0-rc.1

### PR DESCRIPTION
**Pull request by talldan**
## Description
Closes #25312.

Use a DropdownMenu component for choosing a menu.

Needs accessibility feedback ...

## How has this been tested?
1. Visit the navigation screen
2. Make sure you have more than one menu
3. Try selecting menus

## Screenshots 
Screenshot 2020-09-17 at 12 37 06 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by draganescu — COMMENTED** [review]
On this PR when I create a new menu the selector does not move to the new menu created, it remains on the previously selected one.

**Comment by talldan** [comment]
@draganescu Good catch. 07208b6 fixes that.

**Comment by shaunandrews** [comment]
I'm thinking it might be better to consolidate the interactions; All the other buttons here (Add new, Manage locations) are DropdownMenu's and maybe this one should be too. It would look something like this:

dropdownmenu

Posted this same comment over on https://github.com/WordPress/gutenberg/issues/25312#issuecomment-694520933

**Comment by talldan** [comment]
Thanks @shaunandrews, that's much nicer. Here's how it looks now:
Screenshot 2020-09-18 at 11 16 13 am

**Review by draganescu — APPROVED** [review]
This works great and looks the same! 👏

**Review by afercia — DISMISSED** [review]
From an accessibility perspective, a `DropdownMenu` looks good to me and I do see it brings in consistency. However, there's no indication of _which_ menu is being edited. I'd like to propose to add a H2 heading, please see my comment on the issue: https://github.com/WordPress/gutenberg/issues/25312#issuecomment-694836182

Roughly:

Screenshot 2020-09-18 at 14 31 28

**Comment by talldan** [comment]
Thanks for re-reviewing @afercia.

Is the position of an `h2` (disregarding the fact it has to come after the `h1` in the DOM) something that needs to be considered? Just wondering how much flexibility there will be in positioning it?

@shaunandrews would be great to get your advice on how to incorporate this into the screen.

**Comment by afercia** [comment]
Well, the visual/reading order should match the DOM order. Apart from that, headings don't necessarily need to look "big". They can be styled, as long as there's a visual hierarchy that matches the semantic hierarchy.

**Comment by talldan** [comment]
Here's what I've come up with, but would be good to get design feedback:
Screenshot 2020-09-22 at 11 04 22 am

**Comment by afercia** [comment]
Thanks @talldan !

Question: is it possible to have a H2 heading also when there are no menus? I'd use a "Create menu" text for the heading or something along those lines. Otherwise, that page section won't have a heading at all (also the current H3 List View will skip a level):

Screenshot 2020-09-23 at 14 55 55

**Comment by shaunandrews** [comment]
I think we can keep the elements together; No need to right-align the buttons:

image

If there are no menus, perhaps we simply state that in the heading:

image

**Comment by talldan** [comment]
Thanks @shaunandrews, I've made those changes:
Screenshot 2020-09-30 at 11 44 39 am

The header can show three things:
- 'Editing: Menu name' (when a menu is selected)
- 'Create new menu' (when the user has no menus)
- 'Loading …' (when the page is loading menus. This last one won't be displayed if the menus are preloaded as per https://github.com/WordPress/gutenberg/issues/24642)

**Comment by talldan** [comment]
> If there are no menus, perhaps we simply state that in the heading:

Oops, I missed this earlier this morning. Somehow I looked at it and thought this text was part of the screenshot 😄 

I've now updated the header text to:
- 'Editing: Menu name' (when a menu is selected)
- 'No menus available' (when the user has no menus)
- 'Loading …' (when the page is loading menus. This last one won't be displayed if the menus are preloaded as per #24642)

**Comment by draganescu** [comment]
@afercia could you re-review this PR? :) It seems it's current state reflects your requested changes. Thank you 🙏

**Pull request merged**
