### PR TITLE
Add storybook for Panel component

### PR DESCRIPTION
**Pull request by mkaz**
## Description

Adds a new Storybook story for the Panel component

## How has this been tested?

Run `npm run storybook:dev`

## Types of changes

Storybook.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@mkaz Hallo 👋 ! Thank you for adding stories for this component.
I tested it locally, and it's working great.

While looking through the component's API, I noticed a potential enhancement we could add to the knobs, specifically the `opened` prop for the `PanelBody`.

Adding a knob for it would look like this:

Screen Capture on 2019-11-21 at 09-08-00

I think it would be handy as it communicates that there's a programmatic way to open/close the `Panel` beyond just clicking it.

What do you think? :)

**Comment by mkaz** [comment]
@ItsJonQ Good suggestion - I initially was looking at the intialOpen property which didn't make sense to toggle after a load, the opened property is a much better knob.

I added it to each of the examples :+1:

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Thank you @mkaz

**Review by ItsJonQ — CHANGES_REQUESTED** [review]
@mkaz Halloo! I just merged a PR that upgrades Storybook to the latest 5.3 release:
https://github.com/WordPress/gutenberg/pull/19599

There's a slight change we'll need to make to the Story, specifically changing the pipe (`|`) to a slash (`/`). for `Components/Panel`.

The Storyshots may need to be regenerated as well, just in case.

Apologies!!

**Review by ItsJonQ — APPROVED** [review]
@mkaz Thank you for the update!! Approved

**Pull request merged**
