### PR TITLE
Use firstChild and lastChild when parsing lists from MS Word

### PR DESCRIPTION
**Pull request by twstokes**
## Description
This PR uses `firstChild` and `lastChild` instead of `firstElementChild` and `lastElementChild` when parsing lists from Microsoft Word. Currently, `firstElementChild` and `lastElementChild` aren't available in the Gutenberg Mobile environment and this leads to a crash when copying from Word.

**Related to:** 
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/4145
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/4174

In this PR we are only referring to Microsoft Word installed on a native platform (PC, Mac, iOS). The web version of Microsoft Word uses a different underlying HTML structure and is not applicable.

## How has this been tested?
**Prerequisites:**
- Word for PC (read-only mode will not let you copy, must use a licensed version or a trial)
- Word for Mac (read-only mode will not let you copy, must use a licensed version or a trial)
- [List Samples.docx](https://github.com/WordPress/gutenberg/files/7461911/List.Samples.docx)

#### PC
1. Copy the list samples (individually or all together) from the above document in Word for PC.
2. In the Gutenberg editor in a browser (e.g. a WP.com site), paste the lists.
3. Observe that the lists are in a corresponding list block and formatted correctly in Gutenberg.

#### Mac
1. Copy the list samples (individually or all together) from the above document in Word for Mac. ⚠️  
2. In the Gutenberg editor in a browser (e.g. a WP.com site), paste the lists into a Paragraph Block.
3. Observe that the lists are in a corresponding list block and formatted correctly in Gutenberg.

⚠️ There is a [known issue](https://href.li/?https://answers.microsoft.com/en-us/msoffice/forum/all/why-is-word-suddenly-creating-two-olelink/3808b279-6bc6-4db0-9a1e-06925b7f31cf?auth=1) when copying from Word for Mac while a utility that intercepts the Pasteboard is running. Please temporarily disable any pasteboard managers while testing, or the underlying HTML from Word will be broken.

### Mobile

In our testing this affected WPiOS only due to [how Android currently extracts the pasteboard data](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4145#issuecomment-949920745).

**Prerequisites:**
- Word for iOS (a license is not required for read-only mode and it allows the user to copy)
- [List Samples.docx](https://github.com/WordPress/gutenberg/files/7461911/List.Samples.docx)

#### WPiOS
1. Copy the list samples (individually or all together) from the above document in Word for iOS. Saving the document in iCloud offers a quick way to transfer it to the mobile device.
2. Paste the lists into a new Post on WPiOS.
3. Observe that the lists are in a corresponding list block and formatted correctly in Gutenberg.

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
👋 @ellatrix! Since you've worked on [adding the related code](https://github.com/WordPress/gutenberg/commit/abb3e4bedfd0b03a4e132606f9f1aed64ad154c0#diff-d237d7cb80b34a3bd8621da871f6bddf9ce950b515a18660856adb992732c70aR50) I wonder if you have thoughts about the approach in this (draft) PR, to replace the `firstElementChild` with `firstChild` for the `node.removeChild()` call ([context here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/4145#issuecomment-953254800)). Anything we should pay attention to perhaps? Do you foresee any issue with this replacement? Thanks!

**Review by ellatrix — APPROVED** [review]
Fine with me.

**Comment by twstokes** [comment]
@hypest would you mind providing a review from the Mobile Gutenberg side? BTW, it looks like E2E tests are currently failing. I'll keep an eye on those. Thank you!

**Review by hypest — APPROVED** [review]
🎉I tested on the iOS demo app and pasting from MS Word works OK! I verified that the same content pasted on the demo app without the changes of this PR, crashes the app as expected.

Let's merge this since it fixes a frequent crash, and can you also try to get the fix onto a betafix, or at least make sure it land in the upcoming native app betas @twstokes ?

> @hypest would you mind providing a review from the Mobile Gutenberg side? BTW, it looks like E2E tests are currently failing. I'll keep an eye on those. Thank you!

Oh, can you try updating from trunk to see if that fixes the failing tests?

Also, not sure if you have tried already, it'd be nice to follow up with a PR that adds some unit testing of this content case, wdyt?

**Comment by twstokes** [comment]
> Let's merge this since it fixes a frequent crash, and can you also try to get the fix onto a betafix, or at least make sure it land in the upcoming native app betas @twstokes ?

Will do!

> > @hypest would you mind providing a review from the Mobile Gutenberg side? BTW, it looks like E2E tests are currently failing. I'll keep an eye on those. Thank you!
> 
> Oh, can you try updating from trunk to see if that fixes the failing tests?

Done! Looks like we're ✅ now.

> Also, not sure if you have tried already, it'd be nice to follow up with a PR that adds some unit testing of this content case, wdyt?

Agreed - I'll follow up. 👍

**Pull request merged**
