### PR TITLE
Try adding borderless header variant to Modal

### PR DESCRIPTION
**Pull request by noisysocks**
Rough attempt at addressing https://github.com/WordPress/gutenberg/pull/41925#discussion_r905878124.

Basically we hide the border that appears underneath the header in `Modal` in a bunch of places. This isn't ideal as we're depending on an internal `Modal` class name (`.component-modal__header`).

| Welcome guide | Template rename | Create custom template | Page pattern picker |
| - | - | - | - |
| Screen Shot 2022-06-28 at 17 33 22 | Screen Shot 2022-06-28 at 17 33 24 | Screen Shot 2022-06-28 at 17 33 28 | Screen Shot 2022-06-28 at 17 33 30 |

My solution is to add a new `headerVariant` prop to `Modal`. The border can be removed by setting this prop to `"borderless"`. I also incorporate the existing `__experimentalHideHeader` prop into this by allowing `headerVariant` to be `"hidden"`.

What do you think @talldan @ciampo?

I'm not so sure. Even with this change, these uses of Modal still reference internal class names a lot. It feels like we're fighting a losing battle..

I note that two of the instances here are asking the user to input some text. Perhaps we could add a new `Prompt` component to compliment the existing `Confirm` component.

Open to suggestions or to just close this.

### CODE REVIEW

**Comment by talldan** [comment]
It looks promising. I'm not hugely into stringly typing these variations, but I know this pattern is being favoured in other components. I like boolean props better because they can be combined (i.e. `<Popover hasStickyHeader hasBorderlessHeader`).

But if the variant approach is preferred, maybe the guide should have a 'sticky' variant, so that those other styles aren't left behind.

The only other option that springs to mind is making a separate `ModalHeader` component. I think this was done with Popover. Might be quite a lot of work, and I'm fully aware that I'm making a lot of work for you at the moment 😄

**Comment by ciampo** [comment]
> I'm not so sure. Even with this change, these uses of Modal still reference internal class names a lot. It feels like we're fighting a losing battle..

This is also my general feeling — it feels a bit like the `Modal` component is not very aligned with the design requirements across the app.

> I'm not hugely into stringly typing these variations, but I know this pattern is being favoured in other components. I like boolean props better because they can be combined (i.e. <Popover hasStickyHeader hasBorderlessHeader).

I also agree with this point — the concept of "variant" works well when the options being represented are mutually exclusive. Daniel's example is fitting — what if the header needs to be borderless AND sticky?

On top of that, I'd also advocate for less presentational variant names than "borderless", as they make it hard to update the design of the component in the future without introducing breaking changes / deprecations.

> The only other option that springs to mind is making a separate ModalHeader component. I think this was done with Popover. Might be quite a lot of work, and I'm fully aware that I'm making a lot of work for you at the moment 😄

Similarly to this idea, I also think that one way to improve the situation may be to "modularize" the `Modal` component (e.g into its wrapper, header, content wrapper, buttons...), so that the consumers of the component can either use the default "monolithic" `Modal`, or compose their own by mixing a matching the subcomponents (and/or replacing them with custom ones).

**Comment by noisysocks** [comment]
Something I wanted to ask @WordPress/gutenberg-design is if it makes sense to have a modal with a border underneath the title and a modal with none? Can we consolidate and choose one design?

**Comment by jameskoster** [comment]
In https://github.com/WordPress/gutenberg/pull/40781 the border beneath the modal title is removed unilaterally. It's just waiting approval :)

**Comment by noisysocks** [comment]
Oh perfect @jameskoster. I think https://github.com/WordPress/gutenberg/pull/40781 is the better direction to go in then.

**Pull request closed without merging**
