### PR TITLE
Quote Block: Add align support

### PR DESCRIPTION
**Pull request by t-hamano**
Part of #43248
Related to #11610

## What?

This PR adds the `align` support to the Quote block.

## Why?

In #11610, it is suggested that the Pullquote block may be deprecated. If the Pullquote block is deprecated, the Quote block must support as many of the same features as possible. The most important feature that the Quote block is missing is `align` support.

## How?

Simply added algin support.

Currently, this block does not support layout, so the content width will be the full width of the block. As a follow-up, I'm considering adding layout support to this block as well, as in #45326.

## Testing Instructions

- Try applying different align layouts to this block.
- When converting the wide/full-width Pull quote block to the Quote block, the width should carry over.

## Screenshots or screencast 

quote

### CODE REVIEW

**Comment by t-hamano** [comment]
Mobile unit tests are failing, so I'm trying to investigate why 👀

**Comment by t-hamano** [comment]
@geriux @dcalhoun I'm trying to add wide support to quote blocks, and I've made two changes to fix the mobile unit test failures. I'd be grateful if you could confirm that these changes are OK 🙇‍♂️

- I added the Quote block to `WIDE_ALIGNMENTS.notInnerContainers` ([Source](https://github.com/WordPress/gutenberg/pull/64188/files#diff-754c29386626931033a15770ba8a40952605ce00b9a96af11d474f18ed69d399R16)). If we don't add it, the following test seems to fail: 
  ```
  isContainerRelated › function returns false for currently NOT supported Blocks types
  ```
- Updated the initial HTML for testing the Qupte block transforms ([Source](https://github.com/WordPress/gutenberg/pull/64188/files#diff-393f448bc1b2d02a17aff77776622787e0bd1ba787cf6c6ef9d21d905614045fR17)). The Quote block did not originally support the block alignment, so the `align` attribute never existed. However, an unintended migration was performed by this PR, which caused a migration message to be displayed in the browser console and made the test appear to have failed. My guess is that since this HTML has the `has-text-align-left` class, it should be `textAlign`, not `align`.

You can see these error messages in the following log: https://github.com/WordPress/gutenberg/actions/runs/10212071395/job/28255325475

**Comment by geriux** [comment]
> I'm trying to add wide support to quote blocks, and I've made two changes to fix the mobile unit test failures. I'd be grateful if you could confirm that these changes are OK 🙇‍♂️

I'll take a look now

**Comment by geriux** [comment]
I've just tested these changes and they are working as expected, the new align options are working for the mobile editor as well.

The code changes look good to me, thanks for the ping! 🚀

**Review by ramonjd — COMMENTED** [review]
Looking pretty good!

✅  Align left/right applies to the block and appears in the document flow as I'd expect
✅  The alignment of Pullquote blocks persists between transforms

Here's me messing around with block conversions:

https://github.com/user-attachments/assets/d3a9267d-813c-48dd-85a8-6486346165e4




I haven't tested in native yet - my computer is complaining about dependencies...

**Comment by ramonjd** [comment]
I don't see any errors in IOS, though it's hard to test on the small screen. But it looks like controls appear okay.

https://github.com/user-attachments/assets/fd53052d-e114-4f70-8161-e6b74523dd8b

Also on iPad testing the pullquote > quote transform

https://github.com/user-attachments/assets/a0e02c12-e3a8-407c-b5d0-fe17fe91c199

**Review by ramonjd — APPROVED** [review]

**Comment by t-hamano** [comment]
Thank you for your reviews!

As a follow-up to this PR, I plan to add layout support to this block. After that follow-up is complete, I will reconsider deprecating the Pullquote block in #11610.

**Pull request merged**
