### PR TITLE
Remove experimental setting for interactivity API and behaviors

### PR DESCRIPTION
**Pull request by cbravobernal**
Unblocks #51156

## What?

Remove Behaviors and Interactivity API from Gutenberg experiments. Behaviors are still disabled by default, and need to be enabled using `theme.json`, Global Styles or block settings.

## Why?

Behaviors are ready to be widely tested. We have two weeks for the next Gutenberg release and we can also, after some more testing, include the backports for 6.4

## How?

Removing some conditionals.

## Testing Instructions

Enable behaviors with the three options available. Check that image lightbox is working as expected.

## Screenshots or screencast 
Before:
Screenshot 2023-07-21 at 13 54 55

After:
Screenshot 2023-07-21 at 13 52 44

### CODE REVIEW

**Review by SantosGuillamot — APPROVED** [review]
I've been reviewing it and it looks great 👏 Thanks for working on it! What I tested:

* There is no experimental setting in the Gutenberg Experiments page.
* The default value of the lightbox is false, and the UI to change it is shown.
* It can be overwritten by the theme.json, both showing the UI and the default value.
* It can be overwritten per block through the Site Editor or through a Post Page.

A couple of comments:

* Should we remove the filter we are using to change the `viewScript` ([link](https://github.com/WordPress/gutenberg/blob/update/remove-experimental-flag-behaviors/lib/experimental/interactivity-api/blocks.php)) and add it directly to the image `block.json`? I mean adding something like `"viewScript": "file:./view-interactivity.min.js"`.

* Now that it is not experimental in Gutenberg, should we add docs somewhere to explain how to enable/disable it through the theme.json? Not sure how this is usually handled.

**Comment by cbravobernal** [comment]
> Should we remove the filter we are using to change the viewScript ([link](https://github.com/WordPress/gutenberg/blob/update/remove-experimental-flag-behaviors/lib/experimental/interactivity-api/blocks.php)) and add it directly to the image block.json? I mean adding something like "viewScript": "file:./view-interactivity.min.js".

@SantosGuillamot I've done it in the last commit. Are we in this case loading the JS of view-interactivity if behaviors are disabled?

**Comment by SantosGuillamot** [comment]
> Are we in this case loading the JS of view-interactivity if behaviors are disabled?

If I am not mistaken, we shouldn't. That should be handled in [this logic](https://github.com/WordPress/gutenberg/blob/9430b441f5ecae771e764eb3a32a9ed5bbb3a89d/packages/block-library/src/image/index.php#L34-L69) that is included in the `index.php` file. Is it loading the scripts for you?

**Comment by cbravobernal** [comment]
> If I am not mistaken, we shouldn't. That should be handled in [this logic](https://github.com/WordPress/gutenberg/blob/9430b441f5ecae771e764eb3a32a9ed5bbb3a89d/packages/block-library/src/image/index.php#L34-L69) that is included in the index.php file. Is it loading the scripts for you?

They are not, then everything is 🟢

**Pull request merged**
