### PR TITLE
Restructure project as mono-repo of independent modules

### LINKED ISSUE #292: Why `external/@wordpress`?
Apologies if I missed this discussion somewhere, but it would be good to have this documented or improved.

Why does the folder structure for the blocks JS look like `external/@wordpress/blocks/index.js` for example?  Isn't all of this code `@wordpress`?

### PR DESCRIPTION
**Pull request by aduth**
Closes #292

This pull request seeks to change the folder structure of JavaScript modules such that each is treated as an independent and self-sufficient module. This will enable third-party plugins to opt-in to behaviors of e.g. registering blocks, without necessarily tying the logic of blocks to the editor itself.

It uses [Lerna](https://lernajs.io/) to achieve this, a tool typically used in managing the distribution of many interrelated packages on [npm](https://npmjs.com). At this time I don't think we'll need distribution and can instead leverage WordPress' own internal script dependency resolution, but the bootstrapping feature allows each submodule to define its own dependencies while still sharing a common Webpack configuration.

The Webpack configuration treats each module as a [library](https://webpack.js.org/guides/author-libraries/) whose output is on the `window.wp[ moduleName ]` global scope. You can see how this has affected existing code where we'd now call `wp.blocks.registerBlock` or `wp.editor.createInstance`.

### CODE REVIEW

**Comment by youknowriad** [comment]
Why do we expect plugin authors to use the npm modules instead of using the globals? I think this leads to duplicate JS codes right? I can see some value in using `@wordpress/element` as a module to reuse some "utils" (even though they'll be duplicates) but are we expecting plugin authors to use `@wordpress/blocks` or `@wordpress/editor`. I'm just trying to understand your idea better :)

**Comment by aduth** [comment]
The idea here is that nobody will use the modules directly, including first-party code. The globals will be the preferred way to interact with the code. This is most obviously seen in 8b866fa02ed04443c11910c49005646b58d20718 . If I could have avoided giving names in `package.json` files I would, but Lerna wasn't liking that very much 😄

**Comment by youknowriad** [comment]
So, why do we use Lerna at all? Isn't this a tool to break a repo to multiple npm modules?

Another question I had, could we still use JSX syntax for WP Elements even if `createElement` is a global variable?

**Comment by aduth** [comment]
>So, why do we use Lerna at all?

The main benefit to us would be its [bootstrap feature](https://github.com/lerna/lerna#bootstrap), which enables each module to define its own dependencies, instead of pulling them up to and sharing a single `package.json`. It's toward a goal of treating them very strictly as separate modules. That said, if there's some valid desire for "shared" dependencies, it's made slightly more complex with this approach.

>Another question I had, could we still use JSX syntax for WP Elements even if `createElement` is a global variable?

Yep, it'd be a simple configuration value on [`babel-plugin-transform-react-jsx`](https://www.npmjs.com/package/babel-plugin-transform-react-jsx):

```json
[ "transform-react-jsx", {
	"pragma": "wp.element.createElement"
} ]
```

**Comment by youknowriad** [comment]
I'm leaning towards having a unique package.json at least for now. I'm not totally against this, but my personal feeling is maybe it's a bit "overengineered" for now.

**Comment by aduth** [comment]
"unique" as in single, @youknowriad ? Sure, I can see that as a near-term simplification. Do you think there's still value at least in `modules` subdirectory and the `entry` Webpack logic which depends upon that structure?

**Comment by youknowriad** [comment]
> Do you think there's still value at least in modules subdirectory and the entry Webpack logic which depends upon that structure?

I think it's good structure 👍 better than having "external" and "editor. And we keep our options open if we want to introduce separate package.json like this later.

**Comment by mtias** [comment]
This seems ok to me.

**Comment by aduth** [comment]
d0a5b1d drops Lerna dependencies, assumes we'll manage dependencies in the single root `package.json` for now.

**Pull request merged**
