### PR TITLE
DataViews build-wp: don't bundle singleton WordPress packages

### PR DESCRIPTION
**Pull request by jsnajdr**
This patch excludes singleton-ish WordPress packages from the `dataviews/wp` bundle. A script that bundles `data`, `hooks` or `i18n` can't really use them as intended because it has its own store/hooks/translations registry and can't use the data that other parts of WordPress put there.

The bundle will now contain plain ES imports like:
```js
import { isRTL } from "@wordpress/i18n";
```
which the build tool for the plugin that uses `@wordpress/dataviews/wp` is supposed to interpret and replace them with `wp.i18n` references.

I'm also inclined to bundle "trivial" WP packages like `deprecated`, `warning` or `is-shallow-equal`. There is not risk of missing backward compatibility. But that's not very important.

Context: https://github.com/WordPress/gutenberg/pull/66825#issuecomment-2517424511

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/66825 was part of 19.8, which was released just a few hours ago. Would we want to release a 19.8.1 with this fix or is it ok to wait until 19.9 (two weeks from now). I feel 19.8.1 would be better because, otherwise, we will be on xmas and people won't have time to send feedback until new year. But I'm not sure how severe the issue is.

**Comment by jsnajdr** [comment]
> Would we want to release a 19.8.1 with this fix or is it ok to wait until 19.9

This `build:wp` output is not part of the Gutenberg plugin at all. It's only present in the `@wordpress/dataviews` package published to NPM. That means backport is not needed. The backport that @priethor did (https://github.com/WordPress/gutenberg/pull/66825#issuecomment-2515230840) was also not necessary.

Both PRs affect only what is regularly published to NPM.

**Comment by oandregal** [comment]
> Both PRs affect only what is regularly published to NPM.

Ah, I see. So, how do we update the dataview package? Can we trigger a new npm release for a single package (dataviews)?

**Comment by jsnajdr** [comment]
> Can we trigger a new npm release for a single package (dataviews)?

@gziolo just did that a few minutes ago, under the `next` tag. You can install `@wordpress/dataviews@next` and it will contain the `/wp` export. The `latest` tag doesn't have that yet.

**Comment by oandregal** [comment]
> just did that a few minutes ago, under the next tag.

Nice, thanks!

I've updated the example plugin to use this approach at https://github.com/wptrainingteam/devblog-dataviews-plugin/pull/3 I tested it on WordPress 6.6 and 6.7, with and without the latest Gutenberg plugin active. It worked in every scenario

**Pull request merged**
