### PR TITLE
Add temporary workaround to fix broken common js import of mini-css-extract-plugin

### PR DESCRIPTION
**Pull request by fabiankaegy**
## Description

This PR updates the version of the `mini-css-extract-plugin` to 2.5.0 which is loaded by default anyways. There is an issue in version 2.5.0 that breaks common js imports that can be worked around by adding `.default` to the end of the `require` statement. 

Closing #37992 

## How has this been tested?

Locally using wp-scripts 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by gziolo** [comment]
Thank you for acting so quickly! I commented on the issue here: https://github.com/WordPress/gutenberg/issues/37992#issuecomment-1013824038.

Let’s if it gets fixed upstream first. In the meantime, can you check why `npm install` generates a different output on CI? See https://github.com/WordPress/gutenberg/runs/4826584359?check_suite_focus=true.

**Comment by leanderseige** [comment]
Untested: would be something like this even more stable in case it changes again in the future?

`const MiniCSSExtractPlugin = require( 'mini-css-extract-plugin' ).default ? require( 'mini-css-extract-plugin' ).default : require( 'mini-css-extract-plugin' );
`
@fabiankaegy what do you think about this?

**Comment by fabiankaegy** [comment]
@leanderseige that is a great idea  👍 Added it :)

**Comment by leanderseige** [comment]
What can we do to get this PR merged? 

@fabiankaegy It seems like the only "required" failing check fails because of changes on package-lock.json. Is it really necessary to modify this file in this PR?

**Review by gziolo — APPROVED** [review]
There is still no new version published for `mini-css-extract-plugin` so let's get this one in to resolve the issue.

**Pull request merged**
