### PR TITLE
Pass block pattern name when using replaceBlocks

### PR DESCRIPTION
**Pull request by glendaviesnz**
## Description

Follow on from  #25165 as it turns out that patterns sometimes use replaceBlocks instead of insertBlocks depending on cursor location.

With the `REPLACE_BLOCKS` action, there is currently no way to tell the difference between a number of arbitrary blocks being inserted versus a defined block pattern being inserted.

Providing the pattern namespace/name within the `replaceBlocks` action creator means that we can determine whether or not these blocks were inserted via a block pattern. 

The meta value of `patternName` is the block pattern namespace and name if inserted via a pattern.

This is information that could be useful for showing the pattern in the undo history, or for plugins to take advantage of. 

## How has this been tested?
Tested locally, all automated tests passing.

## Types of changes
New feature (non-breaking change which adds functionality)

## To Test

* Insert a block pattern while cursor is sitting in a new paragraph block
* Confirm that the `REPLACE_BLOCKS` action has passed the pattern name in the object
* Replace a block, and confirm that the pattern name is false

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by apeatling — APPROVED** [review]
Tested and confirmed this is sending meta through on the `REPLACE_BLOCKS` action. :+1:

**Comment by aaronrobertshaw** [comment]
This also tested well for me. 

* Replacing a block with a pattern, the name is passed to the action in the metadata.
* Replacing a block with another block, no pattern name was passed along.

**Comment by apeatling** [comment]
@youknowriad Does this one look okay? It's a follow on from the `INSERT_BLOCKS` action meta addition.

**Comment by youknowriad** [comment]
Yes, it's fine thanks :)

**Pull request merged**
