### PR TITLE
Rename globe icon to url, and update

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

The `globe` icon was a dashicon, and this PR updates it with new vectors from the WordPress Design Library:

Screenshot 2021-09-22 at 10 32 02

Here's how it looked before in the page selector dialog:

Screenshot 2021-09-22 at 10 31 24

Here's after:

Screenshot 2021-09-22 at 10 37 38

The rename from globe to URL is meant to reflect that it should primarily be used for that purpose.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
CC: @getdave since I think you've worked on these bits. This PR is not at all urgent.

**Comment by getdave** [comment]
> CC: @getdave since I think you've worked on these bits. This PR is not at all urgent.

Do I need to update the Link UI component or is backwards compatibility handled somehow?

**Comment by jasmussen** [comment]
I've updated the link UI files that referenced the globe icon. We might need a dev note for the npm package publication, but otherwise I don't think we need to do anything?

**Comment by Mamaduka** [comment]
@jasmussen currently, I don't see Link UI component updates in this PR. It's the reason for failing checks.

**Comment by jasmussen** [comment]
Ack! I missed a ton of them 🙈 — thanks all, I'll get on that.

**Comment by jasmussen** [comment]
So as I found out when editing some of the files was that `url` is a very very generic term used for lots of code, and so it's a bit of a tricky term. I still feel like it makes sense to keep icon names purposeful, but that shouldn't get in the way of improving the icon just on its own.

So I've reverted back to using "globe", and at some point we can do a pass to see what other icons, if necessary, need renames. I know of a few already that diverge between the Figma and the icon package.

**Review by gwwar — APPROVED** [review]
Looks good to me 👍 
CleanShot 2021-09-22 at 14 53 13@2x

**Pull request merged**
