### PR TITLE
Add duplicate post action

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Part of https://github.com/WordPress/gutenberg/issues/59689.
Adds the duplicate post-action.

@jameskoster After we duplicate a post when we are with the post opened in the editor should we navigate to the new post or keep the current post open?

## Testing Instructions
- Open a page in the post editor and site editor and verify there is an option to duplicate and it works.
- Open the pages (list) data views and verify the duplicate option is available and works.

### CODE REVIEW

**Comment by jameskoster** [comment]
It seems likely you'd want to edit the duplicate immediately. However, if you don't then navigating back to the original is a bit frustrating. I wonder if for this initial implementation you remain on the current page, but the Snackbar includes an "Edit" action?

As a separate note, the actions menu in the Inspector should match the one in the Table (minus the 'Edit' action), currently they're mismatched:

| Inspector | Table |
| --- | --- |
| Screenshot 2024-04-11 at 09 47 46 | Screenshot 2024-04-11 at 09 48 06 |

**Comment by jameskoster** [comment]
> I wonder if for this initial implementation you remain on the current page, but the Snackbar includes an "Edit" action?

This would make things much simpler in the post editor too. Otherwise, if the current page has unsaved changes, the user would see the "Leave site?" dialog after duplicating which would be quite disruptive.

**Comment by jorgefilipecosta** [comment]
Hi @jameskoster,
All your feedback was applied. Now the duplicate action success notification when the user has a post open offers the possibility to edit newly created post, if the user wants to.

**Comment by jameskoster** [comment]
Thanks @jorgefilipecosta! One tiny change request...

After duplicating a page in the editor you have to click _twice_ to edit it because the menu remains open. Would it be possible to auto-close the menu when you click "Duplicate"?

**Review by carolinan — DISMISSED** [review]
When I duplicate a post or page from inside the block editor, the content is not copied.
It just creates a new draft with the same title followed by (Copy).

**Comment by annezazu** [comment]
>When I duplicate a post or page from inside the block editor, the content is not copied. It just creates a new draft with the same title followed by (Copy).

Noting that I found that it just showed as "copy" without the other title and could also replicate the content wasn't brought over:
https://github.com/WordPress/gutenberg/assets/26996883/a3e7c56a-9c14-4a7c-b4b4-6fedc1561192

**Comment by ajitbohra** [comment]
functionality works as advertised for me 👍. Tested using WordPress Playground [PR Previewer ](https://playground.wordpress.net/gutenberg.html)

I like how the revisions extended handles UI/UX wise https://github.com/WordPress/revisions-extended sharing here for reference.

An example of an update getting scheduled.

**Comment by jorgefilipecosta** [comment]
> When I duplicate a post or page from inside the block editor, the content is not copied. It just creates a new draft with the same title followed by (Copy).

Hi @carolinan, good catch on content not being copied it was a regression during the iterations that is now fixed.

**Comment by jorgefilipecosta** [comment]
> Thanks @jorgefilipecosta! One tiny change request...
> 
> After duplicating a page in the editor you have to click _twice_ to edit it because the menu remains open. Would it be possible to auto-close the menu when you click "Duplicate"?

@jameskoster the menu now auto closes and the double click is not necessary.

**Comment by jorgefilipecosta** [comment]
> functionality works as advertised for me 👍. Tested using WordPress Playground [PR Previewer ](https://playground.wordpress.net/gutenberg.html)
> 
> I like how the revisions extended handles UI/UX wise [WordPress/revisions-extended](https://github.com/WordPress/revisions-extended) sharing here for reference.
> 
> An example of an update getting scheduled. [ An example of an update getting scheduled. ](https://camo.githubusercontent.com/0f721ea02b212a259663527555b270756e7f032425555029b75c1071f8dbdb7d/68747470733a2f2f642e70722f692f61657671497a2e676966) [ ](https://camo.githubusercontent.com/0f721ea02b212a259663527555b270756e7f032425555029b75c1071f8dbdb7d/68747470733a2f2f642e70722f692f61657671497a2e676966)


@ajitbohra thank you for the review and for sharing a related UI. I guess for now we can keep the simple approach of an edit button on the notices to avoid complexity on the actions API but in the future, we may explore other possibilities.

**Comment by ajitbohra** [comment]
@jorgefilipecosta agree keeping it simple for initial implementation makes sense.

**Review by jameskoster — APPROVED** [review]
Thanks @jorgefilipecosta this is working well for me :)

**Comment by enricobattocchi** [comment]
Hi everyone, creator of Yoast Duplicate Post here :) 
Are there hooks in place where plugins can add functionality or replace the action with a custom one?

**Comment by jorgefilipecosta** [comment]
> Hi everyone, creator of Yoast Duplicate Post here :) Are there hooks in place where plugins can add functionality or replace the action with a custom one?

Hi @enricobattocchi,
Thank you for reaching out 😊  We don't have yet any hooks in place to register/unregister actions, similar to the other artifacts of "Dataviews" like fields. But there are plans to have API's for that as referred in https://github.com/WordPress/gutenberg/issues/61084.

Given that the Duplicate action has more interest manifested in extending it compared to the other actions, I made the action only available in the plugin for now at https://github.com/WordPress/gutenberg/pull/61192. This makes sure it is not released in core by mistake before the extensibility API's are ready.

**Review by alexstine — COMMENTED** [review]
@jorgefilipecosta I was hoping this would get A11Y reviewed before merged, hopefully some basic testing was done as I don't see any E2E tests.

One question I had is how the new posts are actually being created? Are we actually grabbing the post content from a store and posting it to the rest API? I'm not actually sure how the internals work in this area of Gutenberg. Creating a new post or page is one thing but actually having to create a new post or page then copy the content, meta, excerpt, and anything else, that's another. If we're making one huge batch POST to the rest API, I expect this to fail on shared hosts due to small max HTTP POST limits. If this is going to work, I would think PHP is required here to handle this at the database level directly without having to send this data in through rest.

**Pull request merged**
