### PR TITLE
wp-env: try to fix failing PHP Github actions

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Try to fix failing PHP Github actions by attempting to resolve an error during `wp-env` setup.

I noticed that the error claims that `/etc/apt/sources.list` does not exist. This is a naive PR, but I thought I'd try adding a `touch` command to ensure the file exists. This is the error:

image

After adding the `touch` command, I noticed that it was complaining that `git` wasn't available, so I've added that in, too.

## Why?

Currently all PHP Github actions appear to be failing. This PR attempts to get them working again, in a naive way.

I'm not too sure the exact cause of the errors occurring, but it looks like the official WordPress docker images were recently updated (e.g. [WordPress 8.2 image](https://hub.docker.com/layers/library/wordpress/php8.2/images/sha256-49be2e34db386890752ae32edbfb26ccd574267193ac007fe837d26a2a83a7e4?context=explore)) and are now based on `debian:12-slim`. [Debian 12 (bookworm)](https://www.debian.org/News/2023/20230610) was released about five days ago, so I imagine it's connected to that.

## How?

* Add a `touch` command to ensure that `/etc/apt/sources.list` exists.
* Add a command to install `git` as otherwise the composer command failed.

## Testing Instructions

See if PHP actions will pass.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
This unblocks the CI for now until something else comes along. Thanks @andrewserong 🙇

**Comment by andrewserong** [comment]
Thanks for reviewing @ramonjd!

Now that this is merged to unblock `trunk`, I'll just ping @ObliviousHarmony and @noahtallen for visibility on this PR in case there's any further follow-up required. I see there's a bit of history with some of these commands as in earlier PRs like https://github.com/WordPress/gutenberg/pull/49962, so it'd be good to make sure we haven't missed any nuances for `wp-env`.

**Comment by Luehrsen** [comment]
Is it possible to release a patch for `@wordpress/env` as this issue currently blocks a lot of stuff downstream?

**Comment by noahtallen** [comment]
> it looks like the official WordPress docker images were recently updated (e.g. [WordPress 8.2 image](https://hub.docker.com/layers/library/wordpress/php8.2/images/sha256-49be2e34db386890752ae32edbfb26ccd574267193ac007fe837d26a2a83a7e4?context=explore)) and are now based on debian:12-slim. [Debian 12 (bookworm)](https://www.debian.org/News/2023/20230610) was released about five days ago, so I imagine it's connected to that.

Ahhh that would make sense.

@ObliviousHarmony, since the `/etc/apt/sources.list` file doesn't seem to exist by default in the image, do we need the various `RUN sed -i ... /etc/apt/sources.list` commands anymore, or do we need to rework those some other way?

**Comment by andrewserong** [comment]
> Is it possible to release a patch for @wordpress/env as this issue currently blocks a lot of stuff downstream?

Great question. I'm not too sure how fixes get rolled out to npm packages (and I likely don't have access to it). I'll just ping @WordPress/gutenberg-core in case anyone knows or can help out there.

**Comment by talldan** [comment]
I believe package releases routinely happen at the same time as Gutenberg plugin releases (usually every two weeks on a Wednesday).

It looks like there's a process for an individual package bugfix release:
https://github.com/WordPress/gutenberg/blob/HEAD/docs/contributors/code/release.md#standalone-bugfix-package-releases

I don't personally have any experience of it.

**Comment by noahtallen** [comment]
@Luehrsen, I just updated `@wordpress/env` to v8.1.1, which includes this PR 👍

**Pull request merged**
