### PR TITLE
Slot & Fill: Fix rendering empty fills

### LINKED ISSUE #3417: Inserting Gallery Block crashes Gutenberg
## Issue Overview

After creating a gallery, a JS error is thrown during rendering which breaks the page and shows a blank screen.

The error is:

```
TypeError: Cannot read property 'props' of null
    at index.js:16070
    at U (react.min.6b26329b.js:13)
    at u (react.min.6b26329b.js:12)
    at u (react.min.6b26329b.js:12)
    at u (react.min.6b26329b.js:12)
    at G (react.min.6b26329b.js:14)
    at Object.map (react.min.6b26329b.js:21)
    at index.js:16069
    at arrayMap (index.js:1376)
    at map (index.js:942)
```
Note, this is in `slot.js`.

## Steps to Reproduce (for bugs)

1. Create a new post
2. Insert a gallery

## Expected Behavior

A gallery is inserted and Gutenberg continues to work normally.

## Current Behavior

The app crashes

## Possible Solution

Something is returning a null value, so we'll just have to identify what it is.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3417 props @tg-ephox for the suggested fix

Fills with empty, null, undefined or false children were throwing an error.

**Testing instructions**

 - Add a gallery block
 - Ensure no JS error is thrown

### CODE REVIEW

**Comment by gziolo** [comment]
Would it be difficult to add a unit test to ensure we don't see this error anymore?

**Comment by youknowriad** [comment]
@gziolo Good call, Let me add this.

**Comment by youknowriad** [comment]
@gziolo Really good suggestion, I found several issues when adding the unit test :) 47cb67d

**Comment by gziolo** [comment]
Code looks great, thanks for adding tests. I like how they teach you how you can use Slot & Fill together 👍  Let me run it in the browser before I ✅

**Review by gziolo — APPROVED** [review]
I don't see any error on the console when creating a gallery.

**Pull request merged**
