### PR TITLE
Fix: Add labels to image zoom control

### LINKED ISSUE #24494: The image zoom controls are unlabeled
**Describe the bug**
IN WordPress 5.5 the block editor provides new UIs to edit images in the post context. Amongst them, there's a UI to "zoom" the image. In this mini-UI both the range and the number input are unlabeled. No label element, no aria-label or other labelling. Thus, there's no accessible name assistive technologies can use to announce _what_ these controls are.

Range input:

range

Number input:

number

All interactive elements must have an accessible name. Form controls must be labeled.

For accessibility, these are the recommended ways to label form elements in order of preference:
- a visible `<label>` element
- a visually hidden `<label>` element
- an `aria-label` attribute
- an `aria-labelledby` attribute but only if it points to some meaningful text already present in the page

Aside: I thought there used to be checks to prevent unlabeled form controls, but maybe I'm missing something.

Additionally;
The markup is invalid, as:
- There are `<div>` elements wrapped in a `<span>` element.
- A `color` prop is rendered in the HTML.
- The `inputmode` attribute isn't standard yet: it is in [the HTML Living Standard spec](https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-inputmode-attribute) but it's not present in [the current W3C HTML 5.2 recommendation](https://www.w3.org/TR/html52/editing.html#user-interaction-editing). Worth also noting `inputmode` is not supported by all browsers, most notably not supported by Safari, IE11, Firefox for Android. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode

Passing the related rendered HTML to the W3C validator:

zoom ui invalid markup

### PR DESCRIPTION
**Pull request by sunnyssr**
## Description

- Added labels to image zoom controls while editing image.
- Also fix the semantic error in RangeControl component in which it was using span for wrapping other elements like div, input and others.

## How has this been tested?

- I've tested my changes with screen reader and also through chrome computed property of 

- I've also run unit tests.

- My changes in RangeControl affects many areas but I've already tested them.

## Screenshots 
image
image

## Types of changes

- Add label for image input zoom controls.
- Fix semantic errors

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. 

Fixes #24494

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Thanks for working on the issue @sunnyssr!

Looks like this fixes the issue, though I notice the drag handle tooltip overlaps the label:
Screenshot 2020-08-20 at 2 41 28 pm

What's unusual is that the tooltip is underneath in the storybook:
https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--with-help

I would probably still lean towards merging this and improving the styling later in the spirit of iterative improvements.

**Comment by sunnyssr** [comment]
@talldan
I agree with you on that overlapping issue. In fact, it's happening at a lot of place where this RangeControl component is being used. If you've any suggestions regarding this, I would be glad to work on that.
Adding top margin would add a lot of empty whitespace. I am not sure if shifting the tooltip below of the slider instead of being at top could be a solution. I would love to get design feedbacks on this one.

**Comment by ItsJonQ** [comment]
Haiii!! Re: the `<RangeControl />` tooltip. It tries it's darndest to figure out top/bottom positioning, but sometimes the auto-positioner may not get it right.

For this specific use-case (which I don't think is too uncommon)... do folks feel like it would be better to non render the value tooltip at all? Or adjust it so that it renders on the bottom?

If we would like programatic bottom rendering (aka. forcing it to render on the bottom), I can update `RangeControl` to make that happen 💪

**Comment by talldan** [comment]
@ItsJonQ Forcing it to render below sounds like a good plan 👍

**Comment by talldan** [comment]
Merging this, I don't see the other issue as a blocker. Will raise an issue for it

**Pull request merged**
