### PR TITLE
Update pencil icon.

### PR DESCRIPTION
**Pull request by jasmussen**
Before:

Screenshot 2020-09-08 at 08 47 37

After:

Screenshot 2020-09-08 at 08 53 17

Note, the essence of this PR is to update the icon currently named `pencil`. There's also a separate `edit` icon, which is this one:

Screenshot 2020-09-08 at 08 51 52

Perhaps the "pencil" should be renamed "paintbrush" or "brush", but for now at least this updates the icon.

There's also this icon, which could be used for global styles:

Screenshot 2020-09-08 at 08 49 04

### CODE REVIEW

**Review by ntsekouras — COMMENTED** [review]
Hey @jasmussen! Great icon here but `pencil` is being used from other components as well, that doesn't make much sense to show a brush icon. For example `edit` in `rss` or `embed` blocks among some others.

So we can have two directions here:
1. Create a new `brush` icon ( this one ) and use it FSE page for global styles
2. Rename this one properly and leave or change the `pencil` icon that was used in other components for `edit` to `edit` icon, as you mention in your PR's description.

What do you think?

**Comment by jasmussen** [comment]
Awesome observation, thank you for that context.

The thing is, the edit icon that this replaces should not be used anywhere, it's an old icon. I will see if it makes sense to add a commit that updates those other components to use better icons.

**Comment by ntsekouras** [comment]
>The thing is, the edit icon that this replaces should not be used anywhere, it's an old icon. I will see if it makes sense to add a commit that updates those other components to use better icons.

Do you want me to make these changes for changing pencil to the newer `edit` icon and push them here?

**Comment by jasmussen** [comment]
> Do you want me to make these changes for changing pencil to the newer edit icon and push them here?

Thanks for the offer, that's okay I'll take a look now!

**Comment by jasmussen** [comment]
Again, excellent catch. I believe I caught them all. Before:

Screenshot 2020-09-08 at 10 12 54

After:

Screenshot 2020-09-08 at 10 13 44

(honestly that component could use love and refactor to use the same link popover as normal links, but that's separate)

Embed before:

Screenshot 2020-09-08 at 10 14 41

After:

Screenshot 2020-09-08 at 10 16 23

Actually that one should probably have a "Replace" label just like Image. But that's also separate, so as to keep this PR focused.

I think the remaining question is whether to rename the "pencil" to "brush" given that we already have a pencil in the "edit" icon. @youknowriad any thoughts?

**Comment by ntsekouras** [comment]
The only one left is in `rss` component and then you're done.

**Review by ntsekouras — APPROVED** [review]
That's great 💯 . Even if you decide to rename, it's a small change. Green CI and land this!

**Comment by jasmussen** [comment]
Ugh, I had forgotten to search for "icon: pencil". Updated now:

Screenshot 2020-09-08 at 10 33 00

> I think you could rename the pencil here..

Definitely happy to, just want to make sure that's okay to do with a green light from Riad, for example, since it updates the icon component.

**Comment by ntsekouras** [comment]
>Definitely happy to, just want to make sure that's okay to do with a green light from Riad, for example, since it updates the icon component.

Yes you're right! It might be used by third party code..

**Comment by ocean90** [comment]
Is there a reason why we can't have a separate pencil icon and a new brush icon? This would also allow us to copy the current edit icon to pencil and let edit export the "new" pencil icon without any back-compat issues.

```js
// edit.js
import { default as pencil } from './pencil';
export default pencil;
```

**Comment by jasmussen** [comment]
> Is there a reason why we can't have a separate pencil icon and a new brush icon?

I can do whatever we agree is best. Just making sure I understand correctly: this would effectively be a deprecation of the `edit` icon and suggesting the use of `pencil` instead? Or would we have both an `edit` and `pencil` icon that looked identical?

**Comment by ntsekouras** [comment]
I think what is suggested and probably is a good idea is to leave `edit` and `pencil` icons intact and create a new `brush` icon (the svg you created now) to be used in FSE edit mode. @ocean90 is this correct?

**Comment by jasmussen** [comment]
Ah, if that's the case we'll still need to revisit the `pencil` icon and update it. Conceptually it's the same icon as `edit` and should be updated, as the old icon is deprecated..

**Comment by ocean90** [comment]
> this would effectively be a deprecation of the `edit` icon and suggesting the use of `pencil` instead? Or would we have both an `edit` and `pencil` icon that looked identical?

I wouldn't deprecate it, just making `edit` an alias for `pencil` for now after the current `edit` icon has been copied to `pencil`, basically replacing the old Dashicon. And yes, they would look identical because they would be the same.

**Comment by jasmussen** [comment]
Oooh that makes sense. Thank you, I'll give that a shot (tomorrow, the kids are clawing at me).

**Comment by shaunandrews** [comment]
> I wouldn't deprecate it, just making `edit` an alias for `pencil`

This makes a lot of sense to me, too. Has this been done before, and if so are there examples? I like the idea of having matches for both a specific icon (pencil) and a more general description (edit) and linking between the two.

--

Its not clear to me if the paintbrush is a new or existing icon; Does this icon exist in WP currently?

image

For what it's worth, my first response to seeing this icon is "broom" or "sweep." I _think_ that's because I see a "floor" represented by the horizontal line.

I understand you're attempting to keep it consistent with the existing pencil icon (which has this line), but I'm not sure its helpful or actually even logical. When I think of paint brushed, I don't think of straight, thin lines; I think of swirls and blobs and drips.

**Comment by stokesman** [comment]
I'll second @shaunandrews, that the icon is ambiguous. I wasn't sure if I was seeing a spade. I _think_ the rather large difference in width from the handle to the fiber bundle is mostly to blame.

In case it's open to suggestion, I'll posit a brush meant for more coverage might be better:

Or maybe if the intended purpose is to denote style settings maybe it doesn't have to be a brush:

**Comment by jasmussen** [comment]
> Its not clear to me if the paintbrush is a new or existing icon; Does this icon exist in WP currently?

It exists insofar as it was designed for global styles and were added to the WordPress Design Library:

Screenshot 2020-09-09 at 09 31 27

(rightmost)

I'd prefer to keep this PR focused on replacing the dashicon that's incorrectly used for global styles. That's not to dismiss any critique of the brush, that's perfectly valid, and perhaps [best given as comments directly in the Figma file](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=8%3A13).

So outside of addressing Dominik's feedback on making "pencil" an alias for "edit", what's the next step? I can picture two approaches:

1. Add the brush as is, and then follow up with separate PRs to improve the design. 
2. Remove the brush icon agan, and use a different icon that's more acceptable for now.

An alternative icon for global styles was also designed:

Screenshot 2020-09-09 at 09 35 35

That's definitely more font specific, but I think it can work too. Happy to use that also.

Most importantly, I would prefer we don't overthink this — the PR is meant to be a quick win, and I'm happy to do any followup PRs.

**Comment by jasmussen** [comment]
Oh that's interesting. I just rebased and now the icon looks like this:

Screenshot 2020-09-09 at 09 37 40

😆  — someone else had the same instinct! https://github.com/WordPress/gutenberg/pull/24250/files#diff-3924a41ad88da62082971d8c0aa8b20fL58

That effectively settles the discussion. I'm going to remove the Brush icon again, and encourage you all to share your thoughts in the Figma file. Then I'll refocus this PR on making the "pencil" icon an alias.

**Comment by jasmussen** [comment]
Alright, I changed "edit" to be an alias for "pencil". That helps update all the blocks that used the old dashicon:

Screenshot 2020-09-09 at 10 08 12

I kept the updated brush, because it replaces this dashicon:

Screenshot 2020-09-09 at 10 13 52

So, despite what I said in this comment: https://github.com/WordPress/gutenberg/pull/25135#issuecomment-689368791 — this PR _can_ be a place where we decide what the actual brush should look like, even though it's currently only used in the Legacy Widget block, and broken at that. But here's a stab:

Screenshot 2020-09-09 at 10 33 30

Screenshot 2020-09-09 at 10 34 15

Let me know what you think and I'll update the SVG.

**Comment by shaunandrews** [comment]
image

These work well together. The updates to the paintbrush's handle and tip _do_ help it feel more like a paintbrush. (I also see a fountain pen now, but I think that's OK.)

I'd say push this and we can circle back around when/if we find a use for the paintbrush and see how it works in context.

**Comment by jasmussen** [comment]
Awesome, thanks so much Shaun. @ntsekouras if you can sanity check my last commit, https://github.com/WordPress/gutenberg/pull/25135/commits/6815a592809d57d2ebef6259d9e2cbb3608ee915 — not urgent, just when convenient — let's land this and I promise I'll circle back to the brush icon if/when it gets used and feels like it needs additional updating.

**Review by ocean90 — APPROVED** [review]

**Comment by jasmussen** [comment]
Well there you go! Thank you!

**Pull request merged**
