### PR TITLE
Font Library: Frontend

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Implementation of the frontend for Font Library.

You can see https://github.com/WordPress/gutenberg/pull/50927

## Testing Instructions
To make the fonts library backend work you need to add this line in your `wp-config.php` file:
`define( 'FONT_LIBRARY_ENABLE', true );`

## More info:
Tracking issue: https://github.com/WordPress/gutenberg/issues/52698

### CODE REVIEW

**Comment by anton-vlasenko** [comment]
It appears that there are no testing steps provided for this PR.
@matiasbenedetto, do you have any specific steps for testing it?

**Comment by matiasbenedetto** [comment]
>It appears that there are no testing steps provided for this PR.
@matiasbenedetto, do you have any specific steps for testing it?

Hi @anton-vlasenko due to the latest backend changes the PR is not running yet. I just imported the changes from the old big PR containing backend, frontend and other utiils. 

Sorry for not marking this as a draft before. I will be working on this PR and I'll add the testing instructions and ping you when it's ready for review.

**Comment by hellofromtonya** [comment]
There's consensus to rename the library to a singular form, i.e. from "Fonts Library" to "Font Library". See https://github.com/WordPress/gutenberg/issues/52698.

References in this PR will also need to be updated.

**Comment by matiasbenedetto** [comment]
I'm closing this PR in favor of another PR of a smaller scope that does not include any Google Fonts management: https://github.com/WordPress/gutenberg/pull/53884

**Comment by matiasbenedetto** [comment]
> It appears that there are no testing steps provided for this PR.
> @matiasbenedetto, do you have any specific steps for testing it?

@anton-vlasenko It's ready to test in the other PR: https://github.com/WordPress/gutenberg/pull/53884

**Comment by anton-vlasenko** [comment]
> > It appears that there are no testing steps provided for this PR.
> > @matiasbenedetto, do you have any specific steps for testing it?
> 
> @anton-vlasenko It's ready to test in the other PR: #53884

Thanks for the ping, @matiasbenedetto. I'm on it.
UPD: Since there is no PHP code in that PR, I'm not sure I can be of any help.

**Comment by matiasbenedetto** [comment]
Closed, implemented here: https://github.com/WordPress/gutenberg/pull/53884

**Pull request closed without merging**
