### PR TITLE
fix image insert console error

### PR DESCRIPTION
**Pull request by vladanost**
## Description

Fixes https://github.com/WordPress/gutenberg/issues/3633

Editable component is complaining about the caption value type.
On new Image its an empty string and Editable expects an array (caption is registered as type array) or undefined so I set it to undefined if empty string.

I tried setting a default value when registering block type to empty array but that does not work.
```javascript
caption: {
    type: 'array',
    source: 'children',
    selector: 'figcaption',
    default: [],
},

```
I would also assume that since caption is registered as type array that default value would be empty array. But I guess it doesn't work that way.

## How Has This Been Tested?

Manually tested in the browser. 
Current js unit tests pass.

### CODE REVIEW

**Comment by youknowriad** [comment]
Thanks for catching this bug,

I investigated a bit and I think the default value should be an empty array but the issue we have is elsewhere. When we select an image from the media library, we copy it's caption and it's always a string, we should not copy the caption if it's empty and we should wrap it in an array if it's not empty.

See the `onSelectImage` function in the image block.

**Comment by youknowriad** [comment]
Thanks for catching this bug,

I investigated a bit and I think the issue we have is elsewhere. When we select an image from the media library, we copy it's caption and it's always a string, we should not copy the caption if it's empty and we should wrap it in an array if it's not empty.

See the `onSelectImage` function in the image block.

**Comment by vladanost** [comment]
@youknowriad Thanks. Your suggestion seems to work.

**Review by youknowriad — APPROVED** [review]
Nice Thanks

**Pull request merged**
