### PR TITLE
API Fetch: Improve isMediaUploadRequest check

### LINKED ISSUE #34410: The `mediaUploadMiddleware` is applied to every media endpoint request
Currently the `mediaUploadMiddleware` is applied to every request for `/wp/v2/media` endpoint.

The middleware sets `options.parse` to `false`, which causes `fetchAllMiddleware` to bail early. The latter prevents doing `per_page=-1` queries for media items.

I discovered this while debugging a different PR https://github.com/WordPress/gutenberg/pull/34389#issuecomment-908836129.

We should update the `isMediaUploadRequest` check only to return true when the request also has the `POST` method.

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Updates `isMediaUploadRequest` check and to allow `per_page=-1` get requests for media items.

Fixes #34410.

## How has this been tested?
Unit tests are running locally:
```
npm run test-unit -- packages/api-fetch/src/middlewares/test/media-upload.js
```

Running the following code in the browser console doesn't result in the error - `400: Invalid parameter(s): per_page`

```js
wp.data.select('core').getMediaItems({ per_page: -1 });
```

Check that `mediaUploadMiddleware` is applied to upload requests. This can be done by checking the "Request call stack" in the Network tab.

## Screenshots 
CleanShot 2021-08-31 at 15 39 39

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This worked for me as advertised, and when applied to #34389 it correctly paged the result set for galleries over 100 when per_page set to -1.  

I don't think I have enough background around this part of the code though to sign off on it. @youknowriad, can you see any gotchas with this since you initially added this middleware? The background is that this change is needed to switch the gallery `getMedia` call to use `getMediaItems` instead in order reduce the number of calls needed to get all the image data.

**Comment by Mamaduka** [comment]
Sorry for another ping, @youknowriad. I would love to hear your opinion about this change.

**Review by youknowriad — APPROVED** [review]
I think it was @azaozz that implemented this initially.

It does make sense to limit it to "post" requests (maybe "put" too if that's supported)?
Also, we do have an HTTP1 middleware that transforms "post" to "get" requests, we need to make sure it's applied after this one.

**Comment by Mamaduka** [comment]
Thanks for the review, @youknowriad.

> maybe "put" too if that's supported

I think API currently only supports uploads via the `POST` method.

>Also, we do have an HTTP1 middleware that transforms "post" to "get" requests, we need to make sure it's applied after this one.

The `httpV1Middleware` is applied after media middleware, `wp.apiFetch.use` adds new middlewares at the start of the list. Plus, that's how I see it in the call stack.

**Pull request merged**
