### PR TITLE
Font Library: Refactor Font Family REST API controller with new design

### PR DESCRIPTION
**Pull request by creativecoder**
## What?

Refactors `WP_REST_Font_Families_Controller` to implement [the proposed design](https://github.com/WordPress/gutenberg/issues/57616).

## Why?

This is another step toward refactoring the Font Library in preparation for merging to Core. See https://github.com/WordPress/gutenberg/issues/55278

## Testing Instructions

Test the following following endpoints, which are added or revised from the previous controller design, to ensure the work as expected in the design and have appropriate error handling.

```
GET wp/v2/font-families
GET wp/v2/font-families/<id>
GET wp/v2/font-families/<id>?_embed=true
POST wp/v2/font-families
POST wp/v2/font-families/<id>
DELETE wp/v2/font-families/<id>
DELETE /font-families/1?force=true
```

One thing this endpoint does not currently handle is deleting child font faces when the family is deleted. I plan to handle that in a follow-up PR.

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
This is looking great! Commenting with my initial test report.

#### Happy paths on the following endpoints:

- `GET wp/v2/font-families` ✅
- `GET wp/v2/font-families/<id>` ✅
- `GET wp/v2/font-families/<id>?_embed=true`
- `POST wp/v2/font-families` ✅
- `POST wp/v2/font-families/<id>` ✅
- `DELETE wp/v2/font-families/<id>?force=true` ✅

#### Errors tested:

- I saw an error using a non-admin user on all requests ✅
- Saw missing key errors for `font_family_settings`, `name`, `slug`, `fontFamily` on post requests ✅
- Saw invalid post ID error if I tried to post to a missing font family ID ✅
- Saw invalid post ID if I tried to delete a missing font family ID ✅

**Review by mikachan — APPROVED** [review]

**Comment by Pinkolinka11** [comment]
# > > > > > _```
```
- - - - - [ ] ## > @@@@stephdau @gutenbergplugin 
```
```_

**Comment by Pinkolinka11** [comment]
_****_@@[]()_********************_ _****_

**Comment by Pinkolinka11** [comment]
@gutenbergplugin

**Pull request merged**
