### PR TITLE
Add Features/Services 01 pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Adds a Features/Services section block pattern for #20345.

⚠️ **Waiting on https://core.trac.wordpress.org/ticket/49580 to update image URL paths.**

Screen Shot 2020-03-04 at 18 26 05

```
<!-- wp:group {"backgroundColor":"very-light-gray","align":"full"} -->
<div class="wp-block-group alignfull has-background"><div class="wp-block-group__inner-container"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":317,"width":320,"height":240,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large is-resized"><img src="https://i1.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/meditating.png?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-317" width="320" height="240"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626","fontSize":"large"} -->
<p style="color:#262626" class="has-text-color has-text-align-center has-large-font-size">Feature 01</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626"} -->
<p style="color:#262626" class="has-text-color has-text-align-center">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"customBackgroundColor":"#262626","borderRadius":2} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background-color:#262626;border-radius:2px">Call to action 01</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":319,"width":320,"height":240,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large is-resized"><img src="https://i1.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/reading.png?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-319" width="320" height="240"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626","fontSize":"large"} -->
<p style="color:#262626" class="has-text-color has-text-align-center has-large-font-size">Feature 02</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626"} -->
<p style="color:#262626" class="has-text-color has-text-align-center">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"customBackgroundColor":"#262626","customTextColor":"#ffffff","borderRadius":2,"className":"is-style-fill"} -->
<div class="wp-block-button is-style-fill"><a class="wp-block-button__link has-text-color has-background" style="background-color:#262626;color:#ffffff;border-radius:2px">Call to action 02</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"align":"center","id":322,"width":320,"height":240,"sizeSlug":"large"} -->
<div class="wp-block-image"><figure class="aligncenter size-large is-resized"><img src="https://i2.wp.com/nrqsnchztest.blog/wp-content/uploads/2020/02/unboxing.png?fit=640%2C480&amp;ssl=1" alt="" class="wp-image-322" width="320" height="240"/></figure></div>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626","fontSize":"large"} -->
<p style="color:#262626" class="has-text-color has-text-align-center has-large-font-size">Feature 03</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"align":"center","customTextColor":"#262626"} -->
<p style="color:#262626" class="has-text-color has-text-align-center">Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":25} -->
<div style="height:25px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:buttons {"align":"center"} -->
<div class="wp-block-buttons aligncenter"><!-- wp:button {"customBackgroundColor":"#262626","customTextColor":"#ffffff","borderRadius":2} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#262626;color:#ffffff;border-radius:2px">Call to action 03</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div></div>
<!-- /wp:group -->
```

### CODE REVIEW

**Comment by enriquesanchez** [comment]
Hi @mtias 👋

Wondering if you have any comments about this pattern. I know we decided to go without images for now but I would like to know if you think we can somehow revisit this one or if we should close this PR instead.

**Comment by mapk** [comment]
I think the 3-column features pattern would be heavily used. @enriquesanchez Can you try this pattern out with gradient squares/circles instead of the images? Let's see what that would look like.

**Comment by enriquesanchez** [comment]
@mapk @mtias here's a revised version of this pattern with the suggested updates:

Screen Shot 2020-04-13 at 14 57 56

I had to use a spacer block inside the groups with background gradients to achieve that height, otherwise they'd all appear very short.

**Comment by mapk** [comment]
I vote we close this in favor of https://github.com/WordPress/gutenberg/pull/20898 and https://github.com/WordPress/gutenberg/pull/21135.

**Pull request closed without merging**
