### PR TITLE
Library: Update icons in the creation menu

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Update the icons associated with the "Create template part" and "Create pattern" actions.

## Why?
See https://github.com/WordPress/gutenberg/issues/52043

## Testing Instructions
* Navigate to Site Editor -> Library
* Click +
* Observe updated icons

### Before
Screenshot 2023-06-29 at 11 01 01

### After
Screenshot 2023-06-29 at 11 01 12

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Good simplification!

**Comment by mtias** [comment]
Thanks!

**Review by apeatling — APPROVED** [review]
Much better, works as expected ☑️

**Comment by talldan** [comment]
Just noting that there's a flaky E2E test failing in `trunk` and also in this PR (`Multi-entity save flow › Site Editor › Save flow should allow re-saving after changing the same block attribute`).

I'll move ahead with merging despite that, as this PR definitely doesn't introduce the issue. There'll be some separate investigation into the failing test.

**Pull request merged**
