### PR TITLE
added documentation text-transform component #52072

### PR DESCRIPTION
**Pull request by BenjaminZekavica**
Pull Request #52072

## What?
- added readme for text-transform component

## How?
I added the Readme with all information how to use the text-transform component 

Todo: Please upload the image on the WP Server to embed it.

wp-texttransform-doc

### CODE REVIEW

**Comment by BenjaminZekavica** [comment]
Please can somebody check the Github Action, I can't understand it why the building process has an error :/ Thank u :)

**Review by mburridge — APPROVED** [review]
LGTM

**Comment by mburridge** [comment]
I've also tried re-running the tests.

**Comment by BenjaminZekavica** [comment]
> I've also tried re-running the tests.

@mburridge Thank you so much :) Do you can merged it to the Master. It's important before you start merging, that the picture has a other URL Source. Do you could upload the picture to the WP Server, than I will change the URL.

**Comment by mburridge** [comment]
@BenjaminZekavica I'm going to try to find out the best place to upload the image to.

Some of the components put images in [docs/assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets), like [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-controls/README.md). Others upload the image to Make, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-card/README.md). While yet others have another location for images, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/warning/README.md).

Once I find out the best location for README.md images I'll advise.

**Comment by ndiego** [comment]
> Some of the components put images in [docs/assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets), like [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-controls/README.md). Others upload the image to Make, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-card/README.md). While yet others have another location for images, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/warning/README.md).
>
> Once I find out the best location for README.md images I'll advise.

This is still up for debate. In the interest of getting this PR merged, let's add it to [docs/assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets). It can always be moved later, and this way, we have the actual image in the repo.

**Comment by BenjaminZekavica** [comment]
> > Some of the components put images in [docs/assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets), like [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-controls/README.md). Others upload the image to Make, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-card/README.md). While yet others have another location for images, such as [this one](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/warning/README.md).
> > Once I find out the best location for README.md images I'll advise.
> 
> This is still up for debate. In the interest of getting this PR merged, let's add it to [docs/assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets). It can always be moved later, and this way, we have the actual image in the repo.

@ndiego: That means I have to add in this PR the picture in the right folder and than I  add the path inside the README.md?

**Comment by BenjaminZekavica** [comment]
@mburridge I added the picture inside the folder docs/assets and I added the Link inside the README. It will works after merging. Than the picture will be available. I hope now you could merge.

**Comment by mburridge** [comment]
LGTM. Great work, thanks @BenjaminZekavica 🙌. Just waiting for the checks to complete before merging.

**Comment by BenjaminZekavica** [comment]
> LGTM. Great work, thanks @BenjaminZekavica 🙌. Just waiting for the checks to complete before merging.

@mburridge You're welcome :) I think it's done and it looks the Action Check is without errors.

**Comment by aaronrobertshaw** [comment]
Thanks for getting this documentation sorted while I was out of action @BenjaminZekavica, I appreciate it! 🙇

**Pull request merged**
