### PR TITLE
Make inline image toolbar focussable by keyboard

### LINKED ISSUE #10595: Inline images can't be resized using only the keyboard
Images in an _Image block_ can be resized using the form controls in the sidebar (jumping to the sidebar when using only the keyboard is still not that easy, but it's a separate issue):

screen shot 2018-10-14 at 16 00 00

Instead, _Inline images_ don't expose any control that is operable with a keyboard, they use only the "resize handles":

screen shot 2018-10-14 at 16 01 01

For WCAG compliance, any functionality must be operable using only the keyboard. Worth reminding most assistive technologies for people with motor disabilities either work through the keyboard or emulate the functionality of the keyboard. Besides that, many users make a mixed use of mouse, keyboard, or other input devices. Some users just prefer to use the keyboard. Lack of keyboard operability support is a sign of lack of _device independence_, which is one of the fundamental principles of the Web.

In the Classic Editor inline images are the norm. Although it's not that easy, it's always possible to edit an inline image accessing the "Edit" button in the image toolbar. This gives access to the "Image details" media modal:

screen shot 2018-10-14 at 16 13 29

Instead, in Gutenberg inline images don't have a dedicated toolbar or other dedicated editing controls.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Attempts to fix #10595. I added a keyboard shortcut to focus the contextual toolbar, currently only for inline images, but ideally, it should work the same for any contextual toolbar such as the one for links and ones added by plugins e.g. color. Also tells the user when on image gets selected and deselected, with the shortcut to focus the contextual toolbar.

Not expecting to be perfect from the start. Once it looks good I'll add an e2e test for it to avoid regressions.

**N.B.** There are boundaries around the image, which is a bug that will get fixed by #13948.

## How has this been tested?

In a rich text field, add an inline image. Select it. You should get a spoken message that the image has been selected and which shortcut to use to access the contextual toolbar. Try it. The popover content wrapper should receive focus. You can now tab to the form elements. Edit the width and apply. Selection should go back to the rich text field. Deselect the image and there should be a spoken message again.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by afercia — CHANGES_REQUESTED** [review]
Thanks so much for working on this. After some testing I'm not sure I'm fully convinced the interaction is ideal though. Especially selection and initial focus. Will comment on the related issue for general discussion.

In the meantime, I've noticed a few issues:

1
When the inline image is in a new line (Shift+Enter) and then moving the caret across the image with the arrow keys, the block crashes (at least in Chrome): `Cannot read property top of undefined`

screenshot 2019-02-21 at 15 12 36

2
pressing Escape should close the inline toolbar and move focus back to the previous insertion point/selected image

Testing with Safari and VoiceOver:

3
the image is announced as selected even when it's not "visually" selected and the caret is still before the image. I guess this is because of the TinyMCE boundaries?

screenshot 2019-02-21 at 15 08 10

4
Can't reproduce consistently but trying to select the image and change its size multiple times can produce a duplicated image:

screenshot 2019-02-21 at 15 09 35

**Comment by iseulde** [comment]
> 3
> the image is announced as selected even when it's not "visually" selected and the caret is still before the image. I guess this is because of the TinyMCE boundaries?

> 4
> Can't reproduce consistently but trying to select the image and change its size multiple times can produce a duplicated image:

These issues will be fixed by #33401.

> 2
> pressing Escape should close the inline toolbar and move focus back to the previous insertion point/selected image

Agreed. It should select the image at least.

**Comment by afercia** [comment]
> Agreed. It should select the image at least.

See also #14026

**Comment by guarani** [comment]
Looks like this needs to be rebased with `master` and conflicts resolved to be testable on mobile since this PR pre-dates the monorepo changes.

**Comment by ellatrix** [comment]
Needs to be rethought and refreshed, so closing.

**Pull request closed without merging**
