### PR TITLE
Translatable demo content

### LINKED ISSUE #8547: /gutenberg/post-content.js needs to be translatable.
**Describe the bug**
We're now asking people all over the world to test Gutenberg. But the sample content we offer still can't be translated. Needs to be fixed soon. /gutenberg/post-content.js should use the js-i18n functions.

**To Reproduce**
1. Use WordPress in any language except en_US.
2. While installing Gutenberg, note that information about Gutenberg is (can be) translated to your own language, as well as the text on, for instance, sv.wordpress.org/gutenberg
3. Hit the function for sample content. It will be in English (US)

**Expected behavior**
The sample content should be prepared for translation. This is important, since the visual feeling is very different between Japanese, any RTL language, and English.

### PR DESCRIPTION
**Pull request by swissspidy**
## Description
This PR makes the Gutenberg demo content easily translatable for contributors. For this, the content has been moved from JS to PHP as there's no real need for this to be in a JS file and add it to the build process and everything.

Note: We could consider adding a `"demo content"` context to every string.

## How has this been tested?

I tested this by opening the demo both before and after the change. There's no difference.

I also tested this by extracting strings and updating the translation file to see how the demo content is translated.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 

Fixes #8547.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think this was meant to be a "temporary" page that we remove before 5.0 merge. That's the reason for avoiding i18n here, but if we want it to be translatable, I think this is the right approach.

cc @mtias @karmatosed @jasmussen

**Comment by jasmussen** [comment]
Absolutely, I don't see a situation where this remains in the shipping 5.0 version. 

I don't _object_ to having this be translatable during the plugin phase, but on the other hand, it's a lot of content to translate and a lot of work that will ultimately disappear into the ether, like tears in rain. Is it worth it? If it is, fire away :)

**Comment by jasmussen** [comment]
Per your thoughtful comments, I have no objections to this, so I'll let Riad comment on the code 💕

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by karmatosed** [comment]
Totally agree this will not ship with 5.0 but good to be inclusive now.

**Comment by tobifjellner** [comment]
Thank you guys!

**Pull request merged**
