### PR TITLE
Mobile Release v1.49.0

### PR DESCRIPTION
**Pull request by mkevins**
## Description
Release 1.49.0 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3263

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by chipsnyder — APPROVED** [review]
Sanity tests went smoothly I think we're good to go 👍

**Comment by guarani** [comment]
Hey @chipsnyder, I removed myself as reviewer because I think it was automatically added and not needed, but let me know if that's not the case and I'd be happy to take a look at this! 👍

**Comment by mkevins** [comment]
Just leaving a reminder here that after the release of `gutenberg-mobile` (i.e. after this branch is tagged, but before it is merged into `trunk`), I think we may need to revert the revert commit (https://github.com/WordPress/gutenberg/pull/29884/commits/9fcf73fd0eda1ecf4cc8882ef80f35c23a571efe).

**Comment by chipsnyder** [comment]
The Revert has been reverted https://github.com/WordPress/gutenberg/pull/29884/commits/2e419dbe0d971a010a0053644566dda10b75a721 :)

**Pull request merged**
