### PR TITLE
Post Title: Move selection at the end after pasting over the text

### LINKED ISSUE #59798: Page title: selecting and pasting causes unexpected results
### Description

I found 2 separate issues pasting into the Page Title on 6.5-RC-2. (I assume they're related, so opening as a single ticket, but happy to split up if desired)

1. "OriginalPastedOriginal"
If you start with a page title of "Original", select it JUST RIGHT, and try to paste "Pasted" over it, you can end up with a title of "OriginalPastedOriginal"

Video Demonstration:

https://github.com/WordPress/gutenberg/assets/945157/81523df8-8b32-4cf7-bd4b-e58d223e4602

2. Multiple Pastings

Admittedly another bit of an edge case, but if you do the following:

a) Select your current page title and paste a new one over it. (seems fine. note that the title is not highlighted)
b) Select (doubleclick) the new current page title and paste over it again (seems fine, but not that this time the title IS highlighted)
c) Paste one more time. You'll now find yourself with the pasted text being appended to the page title, instead of overwriting it, despite the fact that the title was highlighted to begin with and thus should have been replaced.

Video Demonstration

https://github.com/WordPress/gutenberg/assets/945157/7cb61859-e6df-44fb-8da8-53322c4210d9

### Step-by-step reproduction instructions

1. "OriginalPastedOriginal"
If you start with a page title of "Original", select it JUST RIGHT, and try to paste "Pasted" over it, you can end up with a title of "OriginalPastedOriginal"

2. Multiple Pastings

a) Select your current page title and paste a new one over it. (seems fine. note that the title is not highlighted)
b) Select (doubleclick) the new current page title and paste over it again (seems fine, but not that this time the title IS highlighted)
c) Paste one more time. You'll now find yourself with the pasted text being appended to the page title, instead of overwriting it, despite the fact that the title was highlighted to begin with and thus should have been replaced.

### Screenshots, screen recording, code snippet

(in original post)

### Environment info

WordPress 6.5-RC-2, Twenty Twenty-Three theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
Fixes #59798.

PR updates the Post Title component to collapse and move the selection at the end after pasting over the text. It matches other `RichText` components and native browser behaviors.

## Why?
While the component updated the internal selection state, it never adjusted the DOM selection. This is handled internally via `applySelection`, but this method was never called due to custom `onPaste` implementation.

## How?
When pasting, use the `value` and `onChange` callbacks provided by the `useRichText` hook to update the text.

## Testing Instructions
1. Open a post or a page.
2. Select the title text and copy it.
3. Pate over the selected text.
4. Confirm that the selection is moved at the end of the text.

### Testing Instructions for Keyboard
Same.

## Screenshots or screencast 

https://github.com/user-attachments/assets/da057bd7-735d-4c4a-a05c-8b5e624b9c2c

### CODE REVIEW

**Comment by Mamaduka** [comment]
@ellatrix, can I get a sanity check for this proposed fix? 🙇

**Comment by ironprogrammer** [comment]
Thanks for the patch! To test in Safari, I also applied the fix from #64671, and it resolved the issue except after an Undo (Cmd+z). In this instance, after Undo, the caret appears to be at the start, but the clipboard is pasted at the end of the field. Happy to report this separately if it should be.

## Test Report

### Environment
- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 14.6.1
- Browser: Safari 17.6
- Server: nginx/1.27.0
- PHP: 8.2.22
- MySQL: 8.0.27
- WordPress: 6.7-alpha-58576-src
- Theme: twentytwentyfour v1.2
- Active Plugins:
  - gutenberg v19.0.0 with both this PR and patch from #64671

### Actual Results
✅ After pasting text into the title field, the caret is positioned at the end of the pasted text.
❌ After Undoing (Cmd+z) a paste, the caret is positioned at the start of the field, but pasted text is inserted at the end of the field (doesn't insert where expected based on caret position).

### Supplemental Artifacts
title-paste-caret
_Figure 1: Demonstration of pasting text at front, end, and Undoing paste where caret appears to be at front but pastes at the end._

**Comment by Mamaduka** [comment]
> After Undoing (Cmd+z) a paste, the caret is positioned at the start of the field, but pasted text is inserted at the end of the field (doesn't insert where expected based on caret position).

I also noticed that, and after digging, it turned out to be a general bug with the RichText component. The same behavior can be reproduced with Tagline block.

## Problem

* RichText only "knows" how to re-adjust selection after undoing for [block attribute values](https://github.com/WordPress/gutenberg/blob/66b8b617c767829d9b7972459ca11e0c037c5e27/packages/block-editor/src/components/rich-text/index.js#L153-L154).
* When undoing entity properties, selection will point to the old `start` and `end`.

Unfortunately, I don't have a solution at the moment. Let's create a separate issue for it.

## Screeencast

https://github.com/user-attachments/assets/0840cbca-1dce-4009-94d5-bbcd4c0ee0ae

**Comment by Mamaduka** [comment]
Thanks for creating a separate issue, @ironprogrammer!

I'll merge this PR.

**Pull request merged**
