### PR TITLE
[RNMobile] Add drag & drop help guide in Help & Support screen

### PR DESCRIPTION
**Pull request by fluiddot**
## What?

Update "Move blocks" section of "Help & Support" screen to incorporate a help guide for the drag & drop feature.

## Why?

Addresses https://github.com/wordpress-mobile/gutenberg-mobile/issues/4840.

## How?

The render function of `MoveBlocks` component has been updated to include further information about the drag & drop funcionality.

## Testing Instructions

1. Open a post/page.
2. Tap on the three dots button located at the top-right corner.
3. Tap on "Help & Support" button.
4. Observe that the "Move blocks" item has a different icon.
5. Tap on "Move blocks" item.
6. Observe that the screen contains information about the drag & drop feature.

**NOTE:** It would be great to test it in both light and dark modes.

## Screenshots or screencast 

**Help & Support screen _(note the change in the icon of Move blocks section)_:**
iOS (light)|iOS (dark)|Android (light)|Android (dark)
--|--|--|--
|||

**Move blocks section:**
iOS (light)|iOS (dark)|Android (light)|Android (dark)
--|--|--|--
|||

### CODE REVIEW

**Comment by fluiddot** [comment]
I'm setting this PR in draft until we update the image to reflect the drag & drop feature.

**Comment by iamthomasbishop** [comment]
@fluiddot This is looking great, nice work! Just a couple of things I noticed, and I'm not 100% sure which are directly related to this ticket, but would be nice to resolve if possible:

## Top-level sheet

<a href="https://user-images.githubusercontent.com/1200432/168304452-f8555cc1-47f7-4f11-a2d0-d8e9e4bd4bf6.png"></a>

1. It looks like the `padding-top` on our section headers is collapsed
2. The colors of the section headers looks off, possibly using `primary` whereas it should be using our usual section header color, which IIRC is `tertiary`
3. Let's remove the `border-bottom` on the last list item in the "The basics" section, as we don't typically show a border-bottom on `:last-child` for lists

## Detail sheet

<a href="https://user-images.githubusercontent.com/1200432/168305228-34d3a1b6-bac2-4341-b089-cbc4f3e65ff5.png"></a>

I noticed that on Android, the second ("old") image has a `border-bottom`. I'm not sure if that was already in place, but in any case, I suggest we either remove the borders entirely or add them to all of the images across the board for consistency — my preference would be the former, to remove all of the borders from images.

**Comment by fluiddot** [comment]
> @fluiddot This is looking great, nice work! Just a couple of things I noticed, and I'm not 100% sure which are directly related to this ticket, but would be nice to resolve if possible:

Thanks @iamthomasbishop for checking the screenshots and good catch on identifying the issues 🙇 .

> ## Top-level sheet
> 
> 1. It looks like the `padding-top` on our section headers is collapsed
> 2. The colors of the section headers looks off, possibly using `primary` whereas it should be using our usual section header color, which IIRC is `tertiary`

Yep, I'm afraid I broke the styles when updating the headings of inner sections, looks like both were using the same styles. I've addressed this issue in https://github.com/WordPress/gutenberg/pull/40961/commits/61bb5559cb01566a63b8387ad7cbfd99c6c67072.

> 3. Let's remove the `border-bottom` on the last list item in the "The basics" section, as we don't typically show a border-bottom on `:last-child` for lists

Good point, I've applied this change https://github.com/WordPress/gutenberg/pull/40961/commits/12fe70287d3a274883e5c617c7d6d316937a9587.

**I've updated the screenshots of the Help & Support screen to reflect these changes.**

> ## Detail sheet
> 
> I noticed that on Android, the second ("old") image has a `border-bottom`. I'm not sure if that was already in place, but in any case, I suggest we either remove the borders entirely or add them to all of the images across the board for consistency — my preference would be the former, to remove all of the borders from images.

That's interesting, I checked the image, and looks like there's actually a border at the bottom on all of them.

Screenshot 2022-05-13 at 17 31 51

In fact, the image from the original designs also had that border:

Screenshot 2022-05-13 at 17 32 37

Probably the fact that it can only be spotted on Android is because the image is being rendered larger. Let me know @iamthomasbishop whether we should update all images and remove the border or add it to the new one, thanks 🙇 !

**Comment by geriux** [comment]
Hey @fluiddot 👋  This is working well 👏 I tested on both light and dark mode, although on WordPress iOS with metro running I can't seem to see the images under the Help & Support screen (only in the demo app), not sure if it's because of something I have locally or if I have to do something specific for it to work. Have you encountered this before?

**Comment by fluiddot** [comment]
> Hey @fluiddot 👋 This is working well 👏 I tested on both light and dark mode, although on WordPress iOS with metro running I can't seem to see the images under the Help & Support screen (only in the demo app), not sure if it's because of something I have locally or if I have to do something specific for it to work. Have you encountered this before?

Yep, I had the exact same issue when testing. I also had to use the demo app for testing the images because on the main apps the images are not displayed. I haven't investigated this issue further, but it might be related to a change we did some time ago related to resolving the assets ([reference](https://github.com/WordPress/gutenberg/pull/33829)) 🤔 .

**Comment by geriux** [comment]
> Yep, I had the exact same issue when testing. I also had to use the demo app for testing the images because on the main apps the images are not displayed. I haven't investigated this issue further, but it might be related to a change we did some time ago related to resolving the assets ([reference](https://github.com/WordPress/gutenberg/pull/33829)) 🤔 .

I see! That explains it, thanks!

**Review by geriux — APPROVED** [review]
LGTM! I updated the bundle to be able to test it in WordPress iOS/Android and it works correctly, the code changes look good as well. Nice work!

I know there's a pending question related to the images in https://github.com/WordPress/gutenberg/pull/40961#issuecomment-1126186988 but once that's handled we are good to merge 👍

**Comment by fluiddot** [comment]
> LGTM! I updated the bundle to be able to test it in WordPress iOS/Android and it works correctly, the code changes look good as well. Nice work!

❤️ 

> I know there's a pending question related to the images in [#40961 (comment)](https://github.com/WordPress/gutenberg/pull/40961#issuecomment-1126186988) but once that's handled we are good to merge 👍

We've discussed this issue internally, and since it's not critical, we decided to do it in a separate PR in order to not block this one. Being this said, I'll proceed to merge the changes 🎊 .

**Pull request merged**
