### PR TITLE
Color Palette: add a purple / violet color option to the default color palette.

### PR DESCRIPTION
**Pull request by mtias**
This should make the color spectrum a bit more complete.

image

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
🌈 Looks good!

**Comment by karmatosed** [comment]
Yay! This is great.

**Comment by kjellr** [comment]
This is an aside, but I was wondering if we should have `white` as one of our color options? This purple and our red color throw up a contrast warning when you first use them as backgrounds. This is easily fixed by using a white text color, but it's a little rough to have to go into the custom color picker to do that: 

purple-white

I also find myself frequently wanting to set white text when in the Cover block for instance.

**Comment by mtias** [comment]
Agreed a white would be useful, also would be good to try a few more grays by default.

**Comment by karmatosed** [comment]
> Agreed a white would be useful, also would be good to try a few more grays by default.

This is just an idea but what about on hovering over a color there being a range of options in that color? The idea may be totally not a great one but my thinking is it stops having lots of colors showing by default, particularly if we're talking shades.

**Pull request merged**
