### PR TITLE
Try reducing specificity of layout style selectors

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Final part of #57841.

Reduces specificity of the layout selectors:

* removes root selector (body) from base styles (base styles are the minimum non-optional styles for each layout type e.g. `display: flex`)
* wraps non-base styles (such as block global spacing styles) in `:where()`
* Removes duplication of selectors where it's no longer necessary due to base style specificity reduction (in the selectors that apply block instance layout styles, such as `.wp-container-core-group-is-layout-10`, as well as the selectors that apply margin overrides such as `:where(.wp-block-group-is-layout-constrained) > :first-child`)

I'll leave updating the test strings to after there's been at least one round of testing and we're reasonably sure of the changes because it's such a pain to do.

## Testing Instructions

1. Test all blocks with layout in both block and classic themes;
2. In block themes check that changing the spacing of a layout block in global styles works correctly;
3. In all themes check that changing the layout settings on a block instance works correctly;
4. Check that margins set by blocks in global styles aren't overridden by layout spacing styles;
5. Exceptions to the above are the top margin of the first block and the bottom margin of the last block in a flow or constrained layout, which should always be 0.

There are likely edge cases I'm missing here. If you can think of any, please test them 🙏

### CODE REVIEW

**Comment by tellthemachines** [comment]
Ok folks, I think I've addressed all the issues that had popped up in #57841, so this is ready for some testing!

**Comment by aaronrobertshaw** [comment]
FWIW I've begun testing this and it's looking good so far ✨ 

Unfortunately, I've run out of time and only gotten to reviewing the code and testing mostly standard blocks in a block theme. If nobody else picks this up in the meantime, I'll finish off reviewing it when I'm back online next week.

So far:

✅ Code changes here almost match 1:1 with the original PR except for a few intentional deviations
✅ Standard core blocks render as expected in a block theme
✅ Global layout styles appear ok for both root and block-type styles (more knowledgeable layout support eyes on this would be great)
✅ Block instance styles related to spacing apply correctly in the editor and frontend

The blocks I've primarily tested with include:
- Cover
- Column
- Columns
- Social Links
- Details
- Navigation
- Gallery
- Quote
- Group
- Buttons

Those I haven't yet looked at are: Query, Post Content/Template, and pagination blocks.

> I'll leave updating the test strings to after there's been at least one round of testing and we're reasonably sure of the changes because it's such a pain to do.

I think you should be right to update the tests. I'm happy to share the load and update the tests further down the line if it turns out we need to.

**Comment by tellthemachines** [comment]
Thanks for testing @aaronrobertshaw!

> I think you should be right to update the tests. I'm happy to share the load and update the tests further down the line if it turns out we need to.

I don't think it's a valuable use of time to update those tests before the changes are final. The only thing they flag is changes to the styles output, which we already know are happening. They're useless in indicating any actual breakage as a result of the changes, because breakage is purely visual. 

The other problem with updating early is that those test strings change often, so the likelihood of merge conflicts increases quite a bit after editing those files.

**Comment by aaronrobertshaw** [comment]
> I don't think it's a valuable use of time to update those tests before the changes are final

Your call, my thinking was these changes already had a fair bit of testing via #57841 and we could have some confidence there that this could land quickly.

**Comment by tellthemachines** [comment]
> we could have some confidence there that this could land quickly.

I hope so! It would be good to get a bit more testing on it though, and many of us are heading into a long weekend, so I'd rather be cautious with the expectation 😅

**Review by aaronrobertshaw — COMMENTED** [review]
I've had a chance to give this some further testing. This time across both classic and block themes.

Block themes included: 2024, 2023, 2022, and emptytheme
Classic themes included: 2021, 2020, 2019, and emptyhybrid

I primarily focused on the same set of blocks from my previous testing that adopt layout or blockGap support but did also quickly smoke test other blocks at random. 

The main blocks tested with included; Cover, Column/s, Social Links, Details, Navigation, Gallery, Quote, Group/Row/Stack, and Buttons.

For the vast majority of cases, this all tested well as per the test instructions.

There did seem to be a couple of theme-specific issues though.

##### 1. TwentyTwentyOne

The Row and Stack blocks display differently between the editor and frontend on this branch. It looks like TT1 adds a `.wp-block-group { display: flow-root }` style. With the current style load order and specificity it is taking precedence over `.is-layout-flex`.

Screenshot 2024-04-04 at 4 27 55 PM

##### 2. TwentyTwenty

TwentyTwenty adds some `.editor-styles-wrapper` scoped styles which reset margins for the Gallery and Quote blocks. On trunk, the higher specificity allows the layout styles to take precedence, however, they lose out on this branch.

##### 3. TwentyTwentyOne & EmptyHybrid

The navigation block's layout controls for justification don't appear to work on trunk or this PR. So just something I thought worth noting.

Do we have an easy means to get a ballpark assessment of how many themes could have styles that may conflict with the reduced specificity here? Or a way to reach out to impacted theme authors like we sometimes do with plugin authors?

All in all, if we can manage the theme-specific issues, I feel like this is pretty close.

That said, some extra eyes and additional reviews would be very beneficial as this one seems like it could be easy to have missed something 🙏

**Comment by talldan** [comment]
Tested lots of patterns across some core themes. The general trend seems to be that really old classic themes are good, new block themes are good, the in between themes (post block editor but pre block themes) have some issues.

I'll also try to test some third party themes (open to recommendations). Here are the issues I spotted:
- Twenty Nineteen in the editor: The 'Text with alternating images' pattern has some subtle differences at wider screen widths. The first columns block has a rule `html :where(.wp-block)[data-align=wide] { max-width: 1100px; }` that's taking effect in this branch, but is overridden in `trunk` by `max-width: var(--wp--style--global--content-size);`.
- Twenty Twenty in the editor: Quite a few of the patterns have extra spacing, especially at the top and bottom, see 'Team members', 'Text with alternating images', 'Feature grid, 3 columns', 'Pricing table' (that one's very noticeable). I think it's the same thing Aaron mentioned, the `body .is-layout-flex > *` rule usually sets margin to 0, but on this branch other styles are taking precedence.
- Twenty Twenty frontend: Seem to be different issues here with widths/alignments of blocks in the patterns. 'Project Description' is an example. Seems to be due to different rules take precedence for wide alignments on the columns block in that pattern.
- Twenty Twenty one frontend: the editor and frontend do seem to be more consistent. Noticing the same `display: flow-root` taking precedence over `display: flex` issue that Aaron did for both stack and row blocks on the front end. For example in the 'Title text and button on left with image on right' pattern.

**Comment by tellthemachines** [comment]
Thanks for testing @aaronrobertshaw and @talldan! I couldn't find all the patterns mentioned (e.g. Project Description) in Twenty Twenty or Twenty Twenty One but I tested with the ones I found and made some adjustments. 

The base layout rule (the one that sets the `display` mode) is now identical to trunk, which should fix the issue with Row blocks in TT1. I also very slightly increased specificity for the rules that output margin overrides on flex and grid children, which should fix the extra margins in patterns. Hopefully that covers everything!

> The first columns block has a rule html :where(.wp-block)[data-align=wide] { max-width: 1100px; } that's taking effect in this branch, but is overridden in trunk by max-width: var(--wp--style--global--content-size);

I think that's actually as it should be! #60489 removes the `max-width: var(--wp--style--global--content-size)` from classic themes so it doesn't override theme-set widths.

**Comment by tellthemachines** [comment]
> The navigation block's layout controls for justification don't appear to work on trunk or this PR. So just something I thought worth noting.

I can only reproduce this if the Navigation block contains a Page List with only one or two short blocks in it. Page List is getting a `margin-right: auto` from [this](https://github.com/WordPress/gutenberg/blob/trunk/packages/edit-post/src/classic.scss#L5) overly generic classic theme stylesheet. 

It could be fixed by adding an override in the Page List editor styles but it's not ideal to so when the issue is specific to classic themes. It could also be fixed by updating the Navigation block to follow other layout blocks in adding layout classes to the inner wrapper instead of the outer. That's a bigger piece of work though.

Edit: actually, it happens with the Search block too. I think moving the layout classes is the best fix for this, if we can do it without upsetting all the layers of custom Nav block behaviour 😅

**Comment by tellthemachines** [comment]
OK folks I think this is ready for another round! @aaronrobertshaw and @talldan, if you could confirm the issues you found are fixed perhaps I'll move on to the test string updates so we can get this merged soonish.

**Comment by ramonjd** [comment]
I've been testing themes 2013-2024, just with Group and Column blocks so far.

Switching between trunk and this branch for each theme I can't (yet) see any regressions. Haven't looked at other blocks.

<details><summary>Here's my test HTML</summary>

```html
<!-- wp:columns {"style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}}} -->
<div class="wp-block-columns" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--60)"><!-- wp:column {"style":{"spacing":{"blockGap":"var:preset|spacing|50"}}} -->
<div class="wp-block-column"><!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"},"blockGap":"var:preset|spacing|80","margin":{"top":"var:preset|spacing|60"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;margin-top:var(--wp--preset--spacing--60);padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:group {"style":{"color":{"background":"#f0e9e9"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#f0e9e9"><!-- wp:paragraph -->
<p>Inner Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#f0e9e9"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#f0e9e9"><!-- wp:paragraph -->
<p>Inner Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#f0e9e9"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#f0e9e9"><!-- wp:paragraph -->
<p>Inner Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"}}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph {"style":{"color":{"background":"#f27c84"}}} -->
<p class="has-background" style="background-color:#f27c84">Row</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#f27c84"}}} -->
<p class="has-background" style="background-color:#f27c84">Row</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#f27c84"}}} -->
<p class="has-background" style="background-color:#f27c84">Row</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"},"blockGap":"var:preset|spacing|50"}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center","orientation":"vertical"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph {"style":{"color":{"background":"#ffdf50"}}} -->
<p class="has-background" style="background-color:#ffdf50">Stack</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#ffdf50"}}} -->
<p class="has-background" style="background-color:#ffdf50">Stack</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#ffdf50"}}} -->
<p class="has-background" style="background-color:#ffdf50">Stack</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"},"blockGap":"var:preset|spacing|60"}},"layout":{"type":"grid","columnCount":2,"minimumColumnWidth":null}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph {"style":{"color":{"background":"#a0ff9e"}}} -->
<p class="has-background" style="background-color:#a0ff9e">Grid</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#a0ff9e"}}} -->
<p class="has-background" style="background-color:#a0ff9e">Grid</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#a0ff9e"}}} -->
<p class="has-background" style="background-color:#a0ff9e">Grid</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"color":{"background":"#a0ff9e"}}} -->
<p class="has-background" style="background-color:#a0ff9e">Grid</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"316px","style":{"color":{"background":"#dfc8c8"}},"layout":{"type":"constrained","contentSize":"158px","wideSize":"278px","justifyContent":"right"}} -->
<div class="wp-block-column has-background" style="background-color:#dfc8c8;flex-basis:316px"><!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph -->
<p>Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph -->
<p>Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph -->
<p>Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#daa0f0"},"spacing":{"padding":{"top":"var:preset|spacing|10","bottom":"var:preset|spacing|10","left":"var:preset|spacing|10","right":"var:preset|spacing|10"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#daa0f0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)"><!-- wp:paragraph -->
<p>Group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
</details>

**Comment by aaronrobertshaw** [comment]
I may have missed it but what was the plan for themes that add `.editor-styles-wrapper` scoped CSS such as TwentyTwenty?

> TwentyTwenty adds some .editor-styles-wrapper scoped styles which reset margins for the Gallery and Quote blocks. On trunk, the higher specificity allows the layout styles to take precedence, however, they lose out on this branch.

Screenshot 2024-04-16 at 3 20 26 PM

I haven't had a chance to look deeper yet. At a glance it looks like https://github.com/WordPress/gutenberg/pull/60154 may have broken TwentyTwenty's left/right margins on galleries and quotes.

| Before | After |
|---|---|
| Screenshot 2024-04-16 at 3 38 43 PM | Screenshot 2024-04-16 at 3 38 24 PM |


**Update**:

I was able to confirm that https://github.com/WordPress/gutenberg/pull/60154 which was merged in https://github.com/WordPress/gutenberg/commit/80a0b128dd3032ea596104e2041205ef2af39fad caused the regression for TwentyTwenty's gallery and quote blocks. 

It also appears when I was last testing, it was prior to that PR merging or I hadn't pulled the latest.

**Comment by tellthemachines** [comment]
> I may have missed it but what was the plan for themes that add `.editor-styles-wrapper` scoped CSS such as TwentyTwenty?

Anything that can be reproduced on trunk is out of scope for this PR 😅  In any case, themes that manually add `.editor-styles-wrapper` probably shouldn't be doing so; I might open a trac ticket to look into it.

**Comment by aaronrobertshaw** [comment]
>  if you could confirm the issues you found are fixed perhaps

I've retested with the layout blocks across 2020 - 2024 and the issues noticed previously with 2021 have been resolved. 

As for the other issues I noted, the nav block issue was out of scope for this PR, but I'd like a plan to address/fix the 2020 issue flagged.

> Anything that can be reproduced on trunk is out of scope for this PR

I'm not sure I agree 100% on this as before https://github.com/WordPress/gutenberg/pull/60154 broke the styles, this PR was breaking them too. Or, am I misunderstanding this comment?

If the considered decision is to dismiss the concern, so be it.

> In any case, themes that manually add .editor-styles-wrapper probably shouldn't be doing so;  I might open a trac ticket to look into it.

True, but the reality is they are. 

Do we need to wait on the results of that ticket or are you happy if some themes break in the meantime?

**Comment by tellthemachines** [comment]
> I'm not sure I agree 100% on this as before #60154 broke the styles, this PR was breaking them too. Or, am I misunderstanding this comment?

I don't believe so, and reverting #60154 on this branch shows Gallery and Quote looking as expected in the editor. I think it's best to fix that separately; I'm hoping we can re-add specificity to the selector without breaking anything else.

> Do we need to wait on the results of that ticket or are you happy to break some themes in the meantime?

No, we'd probably better patch it in the meantime. But [our docs](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles) explicitly state that "...you should not target any of the editor class names directly" so it's not great that default themes are being inconsistent with that recommendation 😬

**Comment by aaronrobertshaw** [comment]
>  I think it's best to fix that separately;

That's fair enough 👍 

My concern was in part, whether the earlier issue (introduced in #60154) might result in other issues in this PR being hidden when comparing back and forth between trunk and this branch. 

> But [our docs](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#editor-styles) explicitly state that "...you should not target any of the editor class names directly" so it's not great that default themes are being inconsistent with that recommendation

Agreed, "do as we say, not as we do" doesn't help anyone much!

> No, we'd probably better patch it in the meantime.

Sounds good. So long as we have a plan to address it, we hopefully won't be breaking any trust with theme authors 🤞

**Comment by tellthemachines** [comment]
Ok I just put up a fix for the Twenty Twenty issue in #60802.

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for the patience here and the quick fix @tellthemachines 👍 

I've given this another run after rebasing on trunk and it's looking good.

Block Themes (tested with 2024 & 2023)
- Didn't spot any new issues across both editors or frontend
- Global styles worked as expected
- Block instance styles related to spacing supports apply correctly

Classic Themes (2020, 2019, Neve, OceanWp, emptytheme )
- Neve: There were some margin differences between the editor and frontend but these were also present on trunk and before https://github.com/WordPress/gutenberg/pull/60154.
- OceanWP: Similar top level margin differences between editor and frontend as Neve. Also on trunk.
- 2019: Didn't centre content but was the same between trunk and this PR

Hybrid Theme (emptyHybrid)
- Didn't spot any issues

Once the tests are updated, this should be good to go 🚀

**Review by aaronrobertshaw — COMMENTED** [review]
It looks like Docker failed to spin up for the PHP e2es but running the updated theme.json tests locally, I still get 36 failures:

Screenshot 2024-04-18 at 5 36 06 PM

**Comment by tellthemachines** [comment]
> It looks like Docker failed to spin up for the PHP e2es but running the updated theme.json tests locally, I still get 36 failures:

I haven't done the PHP ones yet! Just the JS. I should finish updating them all tomorrow.

**Comment by aaronrobertshaw** [comment]
> I haven't done the PHP ones yet! Just the JS. I should finish updating them all tomorrow.

Apologies, I only read the last commit message and thought I could quickly sneak in an approval before finishing up.

**Comment by tellthemachines** [comment]
Ok all the test strings are updated now!

**Review by aaronrobertshaw — APPROVED** [review]
LGTM 🚢 

Layout and Theme.json tests are all passing ✅

**Pull request merged**
