### PR TITLE
ESLint: Remove explicit `react-hooks/exhaustive-deps` disabling

### PR DESCRIPTION
**Pull request by tyxla**
## What?
I propose we remove most of those ESLint disable directives. In many of them (where available), we'll still keep the comments that explain why we're violating the rule. 

## Why?
Currently, we're still explicitly disabling the `react-hooks/exhaustive-deps` rule in many places. This is a problem for the React Compiler, which we're aiming to introduce to Gutenberg soon - it is being disabled entirely for the file where we disable the rule in. See https://github.com/WordPress/gutenberg/pull/61788 for more details and https://github.com/WordPress/gutenberg/pull/66324 as a similar PR that contains some discussion about why we're doing this.

Furthermore, by ignoring the rule, we don't really help with awareness. If the warning is there, there's a chance someone who sees the warning in their IDE to refactor it. When ignored, the IDE doesn't highlight it, so it may forever linger there. That's why for warnings, I see more value in having them there, rather than ignoring them.

## How?
We're removing the `eslint-disable` directives in most of the occurrences. 
This means those will be raised as ESLint warnings, but I'm not concerned about this - this rule is already widely disobeyed across the repository (hundreds of instances), so why should we bother with these 15-20 instances?

## Testing Instructions
No testing needed, this changes just comments and lint results. Make sure all checks are green.

### Testing Instructions for Keyboard
Same

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thanks for the follow-up, @tyxla!

Just cross-referencing other discussions here - #66324.

**Comment by swissspidy** [comment]
Just chiming in here because I saw this

> f the warning is there, there's a chance someone who sees the warning in their IDE to refactor it.
> This means those will be raised as ESLint warnings, but I'm not concerned about this - this rule is already widely disobeyed across the repository (hundreds of instances), so why should we bother with these 15-20 instances?

Don't necessarily agree with this. As a contributor it's already super noisy having dozens or hundreds of warnings across the whole code base. If something needs fixing it should be a proper error, or else disabled. But nobody looks at warnings, especially if there are so many of them already everywhere. You just start ignoring them completely.

**Comment by tyxla** [comment]
FWIW the main point that guides me is moving forward to allow for React Compiler to land. 

I'm happy to disagree here. I don't see how specifically ignoring a warning with `eslint-disable` adds more value than ignoring manually, TBH. Ideally, we should fix all these anyway.

**Comment by Mamaduka** [comment]
@tyxla, can we exclude the `packages/data/src/components/use-select/index.js` file from the Compiler linter paths? It uses `eslint-disable react-hooks/rules-of-hooks`, which we probably can't remove without refactoring `useSelect` again.

**Comment by tyxla** [comment]
> @tyxla, can we exclude the `packages/data/src/components/use-select/index.js` file from the Compiler linter paths? It uses `eslint-disable react-hooks/rules-of-hooks`, which we probably can't remove without refactoring `useSelect` again.

Yeah @Mamaduka, we'll likely have to do it anyway. cc @jsnajdr for feedback, but I think there's no easy way around it without a major refactor.

**Pull request merged**
