### PR TITLE
Move site editor 6.2 specific code to the right file

### PR DESCRIPTION
**Pull request by youknowriad**
I've made a small mistake in https://github.com/WordPress/gutenberg/pull/47777#issuecomment-1427798105 this PR just moves this file content to the 6.2 folder.

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Thank you Riad! Will you be able to create ~~the trac ticket and~~ the back port PR to core?

**Comment by ntsekouras** [comment]
Actually I think this could be part of https://core.trac.wordpress.org/ticket/57631.

**Comment by youknowriad** [comment]
Yeah, it's just two lines to remove.

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.

**Pull request merged**
