### PR TITLE
Add focusable="false" to prevent IE11 getting focus in the SVG icon.

### PR DESCRIPTION
**Pull request by samikeijonen**
More details in the issues #1578.

### CODE REVIEW

**Comment by afercia** [comment]
Just tested on IE 11 and works nicely. This solves a big issue where all the focusable UI controls with an SVG icon required two Tab key presses to continue the content navigation via keyboard. For more details about this IE 11 bug, see http://simplyaccessible.com/article/7-solutions-svgs/#acc-heading-4

**Comment by samikeijonen** [comment]
Is the SVG markup copy from [dashicon repo](https://github.com/WordPress/dashicons/blob/master/react/index.jsx)?  

If it is, it needs to be fixed in there also.

**Comment by jasmussen** [comment]
Thanks so much for the PR, but this change was not pushed back to dashicons upstream, it should've been, otherwise it will regress. Noticed that by accident in https://github.com/WordPress/gutenberg/pull/3025#issuecomment-336824089.

Is there anything we can do to make it so this doesn't regress in the future?

I'll go make the upstream patch, btw.

**Comment by jasmussen** [comment]
Upstream PR created here: https://github.com/WordPress/dashicons/pull/241

The Gutenberg dashicons component is purely a 1:1 direct copy of the component from the Dashicons repo where it is built. It should not be updated directly in Gutenberg.

**Comment by samikeijonen** [comment]
Ok, good to know.

**Pull request merged**
