### PR TITLE
Improve metrics on post publish view buttons

### PR DESCRIPTION
**Pull request by richtabor**
## What?
Tidying up the post publish view to get it better in line with existing UI. 

## Testing Instructions

1. Create a post or page draft. 
2. Ensure pre-publish checks are on.

## Screenshots or screencast 

| Before  | After |
| ------------- | ------------- |
|CleanShot 2023-08-01 at 11 39 25|CleanShot 2023-08-01 at 13 02 13|

### CODE REVIEW

**Comment by jasmussen** [comment]
Much better, thank you for the attention to detail!

Can we change this 8px gap to also be 16px?

Screenshot 2023-08-02 at 10 08 43

And do you know why this panel has a special curiously dark-gray treatment for the disabled input? It looks like it's local to just this input field:

Screenshot 2023-08-02 at 10 09 05

The fact that we could use a better disabled-input design across all inputs is a separate issue, but until we can improve that it seems curious that there's a local override here. Can we remove it?

**Comment by jasmussen** [comment]
Oh, while I'm here, I wonder if we should reduce the button labels:

* View Post → View
* Add New Post → Add new

Not a strong opinion and probably, but the "Post" seems implied, and any time we can remove the CPT type usually translation benefits from it. Also, what's the capitalization story here? I seem to recall us avoiding titlecase 🤔

**Comment by richtabor** [comment]
> And do you know why this panel has a special curiously dark-gray treatment for the disabled input?

@jasmussen I don't, but is this the only readonly input? 

I used the disabled styling from the design library, but kept the color value (as it's not entirely disabled). Also added the gap.

CleanShot 2023-08-11 at 21 57 56

> Oh, while I'm here, I wonder if we should reduce the button labels:

They're currently using the post type's view item and add new item labels, like this: 
```
const viewPostLabel = postType?.labels?.view_item;
const addNewPostLabel = postType?.labels?.add_new_item;
```

I don't mind a follow-up to not use those labels, and simplify to View and Add new though. 🙂

**Review by jasmussen — APPROVED** [review]
Let's get this in, but just in general, the less local overrides we can go with the better. Thanks for the attention to detail!

**Comment by afercia** [comment]
Just noticed that increasing the left/right padding of the URL readonly input as shown [in the last screenshot](https://github.com/WordPress/gutenberg/pull/53245#issuecomment-1675615839) broke the text-overflow ellipsis in Firefox.

Firefox: 

firefox


Chrome:

chrome


Besides that, I'd think the left/right padding is unnecessarily a bit too big and uneven with the top/bottom one.
I'll propose a quick fix PR pinging design.

Edit: weirdly enough, it's the top/bottom value that breaks the ellipsis in firefox.

**Pull request merged**
