### PR TITLE
Markdown rendering issue with angle brackets `<>`

### PR DESCRIPTION
**Pull request by maheshwaghmare**
## Description

On the page https://developer.wordpress.org/block-editor/packages/packages-dom/ the markdown render fail due to the angle brackets.

See
Markdown render issue

## How has this been tested?

Not tested. But, It'll fix the markdown render issue.

## Screenshots

- https://i.imgur.com/1ZkvqQ7.png

## Checklist:
- [ ] My code follows the WordPress code style. 
- [ ] My code is tested.
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Thanks for catching this!

This particular doc needs an extra step. You'll just need to run `npm run docs:build`, commit and push the changes. Let me know if you need any help.

**Comment by gziolo** [comment]
This part of README file is auto-generated from JSDoc so it needs to be changed there first.

**Comment by maheshwaghmare** [comment]
@talldan and @gziolo thanks for the suggestions.

I have just re-generated the docs with command `npm run docs:build`

**Comment by gziolo** [comment]
It removed your changes. You need to apply changes in the JS file in JSDoc comments and run the same command again 😃

**Comment by skorasaurus** [comment]
hi @maheshwaghmare 

Thanks for contributing; I think you'll need to make those changes in https://github.com/WordPress/gutenberg/blob/68da0d9af04f7430d242784921f729aeae1868c2/packages/dom/src/dom.js#L511

**Comment by mkaz** [comment]
Looks like this was fixed in https://github.com/WordPress/gutenberg/pull/34813

**Pull request closed without merging**
