### PR TITLE
Fix build, invalid whitespace

### PR DESCRIPTION
**Pull request by mkaz**
## Description

I introduced a whitespace conflict with build artifact from my change #15612 

This fixes the issue, I'll check with @nosolosw for updating test, it looked green on my PR.

## Types of changes

Documentation, whitespace

### CODE REVIEW

**Comment by mkaz** [comment]
A second run and the whitespace was reversed, after running `npm run docs:build`
I think the build error is unrelated to my change.

**Comment by talldan** [comment]
I've also seen this on another PR, these commits:
- 44bc955 (whitespace changed)
- bde0e03 (whitespace reverted)

At the time I thought it was just down to my inability to use a keyboard, but I think it might've originated from the git hook.

**Comment by nosolosw** [comment]
I see that the changes always happen in `packages/core-data/README.md` :thinking: I'm taking a look into that.

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/issues/15626 is probably related.

**Comment by nosolosw** [comment]
@mkaz @talldan https://github.com/WordPress/gutenberg/pull/15679 fixes the issue. It was more involved than I expected.

**Pull request closed without merging**
