### PR TITLE
Try using the column-gap property to improve spacing between custom-sized buttons

### PR DESCRIPTION
**Pull request by kjellr**
Possible fix for #28468.

This PR tries setting a `column-gap` rule for the parent `wp-block-buttons` block, and then adjusts the width of child buttons to account for that gap. This lets combinations of custom-sized buttons take up the full width of the container, (hopefully) without any extra right margin. I left the existing implementation in place for legacy browsers — this new one only kicks in if your browser supports the `column-gap` property. 

I _think_ all my math works, but it's late in the afternoon on a Friday, so it's possible I've missed something. 😅 

Before|After
---|---
Screen Shot 2021-02-19 at 4 02 15 PM|Screen Shot 2021-02-19 at 3 50 16 PM

### CODE REVIEW

**Comment by jasmussen** [comment]
Wow this is wild! And I can see it working, the code is solid. Before:

Screenshot 2021-02-22 at 10 18 00

After:

Screenshot 2021-02-22 at 10 24 59

The flex "gap" property would've been ideal, but I can see from the discussion that support is lacklustre. But from what I can see, column-gap isn't much better? https://caniuse.com/?search=column-gap

The thing is, I consider Social Links, Navigation, and Buttons to all be 3 configurations of the same general block UI, and 3 blocks that could/should support some of the same things. For example, the justification toolbar is being added to all three (#29160) and made generic. And right now, those horizontal margins for all three are big headaches. If we could replace that with a gap value, one that you might even configure in the sidebar, it would be so ideal.

So I support the end goal, but I'd love if we could find a solution that not only worked better with compatibility, but let us retire BOTH the margins, *and* the baked-in $block-margin SASS variable & calc usage. I know CSS grid can do this, but that seems like a thing to avoid if we can. I may be dreaming?

**Comment by kjellr** [comment]
> The flex "gap" property would've been ideal, but I can see from the discussion that support is lacklustre. But from what I can see, column-gap isn't much better? https://caniuse.com/?search=column-gap

Yeah, it's basically the same. `gap` is just shorthand for `column-gap` and `row-gap` (which we don't really need here since margins works fine for the row gaps). 

> So I support the end goal, but I'd love if we could find a solution that not only worked better with compatibility, but let us retire BOTH the margins, and the baked-in $block-margin SASS variable & calc usage. I know CSS grid can do this, but that seems like a thing to avoid if we can. I may be dreaming?

CSS grid generally isn't a great solution for cases when we don't know the total number of items. I think `flexbox` and something like what we have here makes the most sense for now — and hopefully we could phase out the margin approach once `gap` becomes more widely adopted.

**Review by scruffian — APPROVED** [review]
This approach looks sound to me. Not sure if you want a review from someone else.

**Comment by kjellr** [comment]
Thanks for the review. If @jasmussen's cool with it, I suggest we merge this in and iterate later if need be.

**Comment by jasmussen** [comment]
We've been going back and forth. But it's we're ready to look at follow-ups, let's try it.

**Comment by kjellr** [comment]
Sounds good, let's give it a try! I'll keep my eye on it and see if anything weird happens. Depending on [how this sorts out](https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/), we may be able to remove the fallback code relatively soon.

**Pull request merged**
