### PR TITLE
Popovers: Update border colors to follow the G2 block UI

### PR DESCRIPTION
**Pull request by shaunandrews**
This PR updates the border color for the `Popover` and `Menu` components to fit in better with the new G2 block UI. Here's how the borders look in `master`:

image

And here's how they look in this PR:

image

### CODE REVIEW

**Comment by shaunandrews** [comment]
Part of me wonders if we should remove the `box-shadow` from the `Popover` component, too? They're so subtle right now that they're barely noticeable — and I don't see any shadows in the G2 designs so far.

**Comment by youknowriad** [comment]
For me the difference between these borders and the borders of the panels in the sidebar is disturbing. It feels like two designs are batteling and lack consistency.

I wonder if it's better to refactor the panels at the same time.

**Comment by jasmussen** [comment]
Nice work, Shaun!

I think before we proceed with this, we should work out some heuristics as to _when exactly the borders should look like this_, in part to avoid disturbing Riad, but in part because not all popovers should look like this. 

I think of it this way: if it's primary UI, it has contrast and is at elevation zero. Dark borders and no shadow. Examples: popovers invoked from the block toolbar that is attached to the block. 

If it's secondary UI, it is at elevation 1 and uses the current gray borders and has a drop shadow. Examples: popovers invoked from the top toolbar, modal dialogs, etc.

Another way to think of it **when it's block UI, it has dark borders and no shadow**. I.e. if it's not inside the canvas and in context of the block, it should not have those dark borders. 

I don't think we can create this heuristic in a fancy way, so it seems like we should consider making a prop for it in the popover component.

Other things that will help bring consistency and coherence across popovers is addressing #20765, and making it so there's 12px space between popovers and the opener.

**Comment by youknowriad** [comment]
Is this heuristic just a temporary because our primary UI and secondary UI are not in sync, or is it something that will stay in the final design?

By looking at the final design mockups, it seems to be a temporary one.

**Comment by jasmussen** [comment]
> Is this heuristic just a temporary because our primary UI and secondary UI are not in sync, or is it something that will stay in the final design?

The design in #18667 is very much based on the idea that the block UI is primary UI and therefore has very high contrast borders, and secondary UI like the top toolbar and the sidebar has lighter borders. While I expect the UI to continue to evolve and be refined, this is an aspect that hasn't yet been implemented, but should definitely be tried.

**Pull request closed without merging**
