### PR TITLE
Revert "Use npm workspaces for packages"

### PR DESCRIPTION
**Pull request by sirreal**
This is a revert to land this potentially disruptive change at a more convenient time.

Reverts WordPress/gutenberg#65681

### CODE REVIEW

**Review by getdave — APPROVED** [review]
Thank you for wrangling this 🙇

**Comment by getdave** [comment]
On confirmation from @sirreal I forced merged this as the CI would never pass due to nature of the PR.

**Comment by Mouvedia** [comment]
Can you reopen #59933?
It is blocking stylelint/stylelint-ecosystem-tester#44.

**Comment by sirreal** [comment]
@Mouvedia I expect that migration to npm workspaces move ahead in #66272 later in the week.

(Edit: I don't expect #59933 to be reopened)

**Pull request merged**
