### PR TITLE
Add GPLv2 `LICENSE.md` license

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by jasmussen** [comment]
Nice, thank you! 

Merging.

**Comment by ntwb** [comment]
I expected to now see the _license_ section on the repo frontpage to the right of _45 contributors_

Might be caching, if it doesn't appear there in a couple of days, not caching 😏 

I don't think it matters if `LICENSE.md` includes the `.md` extension or not, time will tell ⌚️

**Comment by jasmussen** [comment]
I see it:

screen shot 2017-06-28 at 12 57 14

Try in an incognito window.

**Comment by swissspidy** [comment]
@ntwb The [help page](https://help.github.com/articles/licensing-a-repository/) says this:

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

So the culprit is 754f23394689a75774723f282f708ee0c744d428.

@jasmussen He's referring to the top section. It should look like this:

screen shot 2017-06-28 at 12 58 00

**Comment by jasmussen** [comment]
Oh, my apologies. Hmm.

**Comment by ntwb** [comment]
Cool, let's leave it as is then, for background on the 754f233 commit, whilst looking to add a LICENSE.md for the new https://github.com/WordPress/packages repo I came here to pinch Gutenberg's, turns out neither had one, so now both have one 😄 

It requested to include the WordPress section via that PR: 
> https://github.com/WordPress/packages/pull/3#issuecomment-311541615

**Pull request merged**
