### PR TITLE
E2E Tests: Use trashAllPosts to delete templates

### PR DESCRIPTION
**Pull request by Mamaduka**

### CODE REVIEW

**Comment by Mamaduka** [comment]
@youknowriad I thought this change would make "E2E Tests Admin 3" less flaky, but it looks like different JS errors cause the issue.

**Comment by talldan** [comment]
I've made an alternative PR - https://github.com/WordPress/gutenberg/pull/39965

**Comment by Mamaduka** [comment]
Thanks, @talldan. PR improved the situation, but I still see some failing tests on the trunk.

**Comment by talldan** [comment]
Yep, I noticed that. This error seems to be another cause of the failure:
```
TypeError: Cannot read properties of null (reading 'frameElement')
```

from this code:
https://github.com/WordPress/gutenberg/blob/606788a48eec4130309402be68c6a87612b3fb9e/packages/block-editor/src/components/block-tools/block-popover.js#L185-L193

And then the array length assertion failure is the other problem.

Something else that I noticed is that these tests use `beforeAll` and `afterAll`, but there's no cleanup between the test cases, so state from one test could leak into the next test.

**Comment by Mamaduka** [comment]
Going to close this one. Tests look stable now.

**Pull request closed without merging**
