### PR TITLE
[RNMobile] Improve File block UI

### PR DESCRIPTION
**Pull request by derekblank**
## What?
Improves UI of the File block on mobile. 

Fixes:

* https://github.com/wordpress-mobile/gutenberg-mobile/issues/6725

## Why?
The appearance of the File block could be improved. When a file is uploaded, the filename and download button text are flush with the block border, and generally looks disorganised.

## How?
Updates the mobile File block to add spacing between the block outline and content, and adds light/dark mode backgrounds to make the File block appear more inline with other media block styles. 

## Testing Instructions
1) Open a Post and add a File block
2) Note that the content is not flush with the block outline (border) and the content has a background color

## Screenshots or screencast 

<details>
<summary>Before</summary>
File block on the bottom, Audio block on top for comparison:

</details>

<details>
<summary>After </summary>
File block on top, Audio block on bottom for comparison:

Light Mode | Dark Mode
-|-
 | 

</details>

### CODE REVIEW

**Review by dcalhoun — COMMENTED** [review]
Thanks for putting this together. The approach is straightforward and makes sense to me. 

I did want to share one thought: My presumption is that the current block design is done in a manner to mimic the visuals found on the front end of the website — i.e., WYSIWYG. 

The native mobile editor doesn't have the most robust/accurate WYSIWYG experience and we've discussed moving away from the approach in the past, but I wanted to discuss before we diverge here. WDYT about this change moving away from a WYSIWYG experience? 

| Web Editor | Web Site |
| - | - |
| editor-file-block | site-file-block |

**Comment by derekblank** [comment]
Thanks for the feedback.

> My presumption is that the current block design is done in a manner to mimic the visuals found on the front end of the website — i.e., WYSIWYG.

This is also my presumption as well. Initially I considered updating the native mobile editor File block UI to be more like the Audio block in the example above. However, after checking the web implementation of the File block, I noted the current implementation of the native mobile editor File block matches the web implementation fairly closely. I opted to keep the native File block UI mostly as-is, with some updated spacing and background colors. 

> The native mobile editor doesn't have the most robust/accurate WYSIWYG experience and we've discussed moving away from the approach in the past, but I wanted to discuss before we diverge here. 

Can you describe this further (or link to any of these discussions)? I'd be in support of improving the experience in any way, but I don't quite follow the updated differences between the web and mobile implementations, or what exactly you're suggesting. 

Native Mobile File block changes (in this PR) | Web
-|-
Screenshot 2024-03-15 at 10 28 06 am |  312980155-76ae0571-d1d6-4620-9b39-0a19b28d047b

**Comment by dcalhoun** [comment]
> Can you describe this further (or link to any of these discussions)? 

I shared internal references privately, but what I intended to share is that we have discussed two possible paths for the native mobile editor moving: 

1. Prioritize a what-you-see-is-what-you-get (WYSIWYG) approach, where the editor renders as close as possible to the front end of the website. 
2. Prioritize device/OS features like dark mode and scaleable text size over WYSIWYG, where the editor render differs from the front end of the website. 

> I'd be in support of improving the experience in any way, but I don't quite follow the updated differences between the web and mobile implementations, or what exactly you're suggesting.

If this proposal is merged, the difference between the web editor and mobile editor implementations would be small. As you pointed out, it is mostly a container background color and padding. As showcased below, the current web and mobile editors share the same approach for background color and padding. 

| Web Editor | Mobile Editor | Mobile Editor (Proposal) |
| - | - | - |
| web-editor | mobile-editor | mobile-editor-proposal |

I shared this overall thought originally as I perceived the proposed modifications to the File block to result in (admittedly small) divergence from what the front-end website render. So, the proposed modifications relate to the aforementioned second path — prioritizing device UI over WYSIWYG. 

I do not share that to say we cannot/should not go down this path, only that it is a change from the project's pursuit of the WYSIWYG approach and could warrant a higher-level consideration with a larger audience discussion.

**Comment by derekblank** [comment]
Thank you for sharing the references. I understand what you mean now about the divergence between WYSIWYG on web. I did note that the web implementation of the File block shares the same less-desirable UI where the block content is flush with the block border. I also noted that several native mobile block implementations diverge from the web WYSIWYG to focus on dynamic text and dark/light mode support, as you stated. 

I'll review the discussions further to help evaluate which approach we want to take. Initially when making these changes on native mobile, I thought that the flush content may have been an uncaught oversight when implementing the block outline changes in the native mobile Editor UX project. Since this behavior is also shared with the web implementation, it may be better to respect [Chesterton's Fence](https://sproutsschools.com/chesterton-fence-dont-destroy-what-you-dont-understand) and not implement these padding changes (unless we found a good reason to do so).

**Comment by derekblank** [comment]
Closing for now. Can re-open later if necessary.

**Pull request closed without merging**
