### PR TITLE
Welcome guide headline update

### PR DESCRIPTION
**Pull request by benazeer-ben**
## What?
Fix for https://github.com/WordPress/gutenberg/issues/67601

## Why?
There is widows for each frame of the welcome guide.

## How?
Updated the headline text as mentioned.

- Welcome to the block editor > Welcome to the editor
- Make each block your own > Customize each block
- Get to know the block library > Explore all blocks
- Learn how to use the block editor > Learn more

## Testing Instructions

- Go to page/post edit screen.
- Make sure Welcome guide option is enable from page/post settings.
- Check and verify each headlines of the welcome guide.
- All are updated as mentioned

## Screenshots or screencast 

customise
explore
learnmore
welcome

### CODE REVIEW

**Comment by annezazu** [comment]
Thank you! Looks good to me.

**Comment by talldan** [comment]
@benazeer-ben Thanks for working on this. It looks like there are some automated tests that need to be updated.

It should be a straightforward matter of updating the strings to match the changes you've made, e.g. - https://github.com/WordPress/gutenberg/blob/63c4d5b1bc5fe0820f59549415b65f3693f08f4e/test/e2e/specs/editor/various/nux.spec.js#L24

**Comment by benazeer-ben** [comment]
Hi @talldan 

Thank you for pointing that out! 

I’ve updated the automated tests to reflect the changes I made. The strings have been adjusted accordingly, and everything should now align with the current implementation. 

Please let me know if there’s anything else I should address.

**Review by talldan — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
