### PR TITLE
Gutenberg Release Workflow: Fix no unreleased pull requests error

### PR DESCRIPTION
**Pull request by luisherranz**
### What

I've modified the release workflow to avoid throwing an error when no additional pull requests have been added to the milestone after the release candidates.

### Why

Because even if the message is correct, showing the word `Error` along with the stack trace gives the impression that something went wrong when it actually didn't.

[I bumped into that error](https://wordpress.slack.com/archives/C02QB2JS7/p1641377484274900?thread_ts=1641374819.273300&cid=C02QB2JS7) when I did the 12.3 release. [It happened](https://wordpress.slack.com/archives/C02QB2JS7/p1637771006080000?thread_ts=1637769197.079100&cid=C02QB2JS7) to @ryanwelcher in the 12.0 release as well.

### How

I've modified the workflow to pass down the version (either `rc` or `stable`) to the function and used it to determine if it should throw an error or just print a line.

## How has this been tested?

I've tested it manually in my own fork.

<a href="https://www.loom.com/share/b7dffbd217064a1e88a0fc332513bf63">
    
  </a>

https://www.loom.com/share/b7dffbd217064a1e88a0fc332513bf63

## Checklist:
- [x] My code is manually tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by ockham** [comment]
Thanks for tackling this! Yeah, the error has caused some confusion in the past, so we better fix it.

I'm not totally sure I agree with the suggested fix 🤔 Typically, the error is encountered not because there were no PRs merged cherry-picked to a release branch between the RC and the stable release, but rather because those PRs didn't have the right milestone attached (i.e. the pointed to the next GB version rather than the current one, which caused the release script to not pick them up).

I think the logic is thus a bit too rigid, since we might want to instruct people that run a release to double-check if there are any PRs that need mentioning in the release notes. Furthermore, I'd rather not infer this from whether or not the current release is a stable one: It's possible that the aforementioned scenario could happen between RCs (not that we've ever really done more than one RC, but it's possible in theory...)

How about we just catch the error and change it into a nicer looking message (possibly wrapped in an `<!-- HTML comment -->` in the release notes draft? :)

**Comment by luisherranz** [comment]
Thanks for taking a look, Bernie 🙂

> the error is encountered not because there were no PRs merged cherry-picked to a release branch between the RC and the stable release

Ok. But that's the problem, because that is what is happening right now: the error also throws when there are no PRs cherry-picked to a release branch between the RC and the stable release.

I'm trying to understand how milestones relate to releases in this process, but I think you're right; the current fix would prevent the legit error from throwing:

> [...] but rather because those PRs didn't have the right milestone attached

---

> How about we just catch the error and change it into a nicer looking message (possibly wrapped in an  in the release notes draft? 

I still think people would wonder if they did something wrong.

This was my understanding of the workflow prior to your comment:

image

I've made a video to see if I'm getting the workflow correctly now, I'm still not sure I'm getting it right:

<a href="https://www.loom.com/share/f12230b295074620b0965aaea7e77465">
    
  </a>

https://www.loom.com/share/f12230b295074620b0965aaea7e77465

_This is the [Excalidraw drawing](https://excalidraw.com/#json=FAlgju6S8pJyVOcGiLW6h,mw9WdTT1QCJcS9UQXPd89Q) in case you want to correct the workflow._

Let me know what you think about what I mentioned at the end of the video, about removing the error and always adding the `If you cherry-picked any PRs, make sure they had the correct milestone associated and they appear in this changelog below.` message to any release after the first RC.

EDIT: Maybe we could even add instructions for when the PRs are missing: `If any PRs are missing, do XXX` (I don't know the procedure).

**Comment by ockham** [comment]
Hey Luis, thanks a lot for the great video and flowchart! I recorded a [video response](https://www.loom.com/share/a36b40a4e15f4a15b2d641ed3ebc31c9) -- a first for me, I hope it makes sense 😅 

The _tl;dr_ is that I agree it makes sense to add a note for the release manager to double-check if there are any PRs that are part of the release branch, but weren't labeled with the correct milestone -- and thus need to be added manually to the release notes; except for the RC1, where that's quite unlikely to happen.

One thing I forgot to mention in the video: I think we should add the relevant logic and message to the GHA workflow (rather than the `changelog.js` script), i.e. somewhere [around here](https://github.com/WordPress/gutenberg/blob/94d553092160adc2e1f9d9362ee87c158a67fea8/.github/workflows/build-plugin-zip.yml#L189-L203). IMO, it's fine to add the note for the release manager as an HTML comment to the release draft; but that should happen in the GHA workflow rather than the `changelog.js` script, which after all can also be run locally.

**Comment by luisherranz** [comment]
> it makes sense to add a note for the release manager to double-check if there are any PRs that are part of the release branch, but weren't labeled with the correct milestone -- and thus need to be added manually to the release notes; except for the RC1, where that's quite unlikely to happen

Ok, that makes sense. 

> IMO, it's fine to add the note for the release manager as an HTML comment to the release draft; but that should happen in the GHA workflow rather than the changelog.js script

Sounds good. My bash scripting abilities are super crappy, but I'll give it a try on Monday 🙂

By the way, is there an easy way to know in the GHA script if is the RC1? 

If not, we could use this message and refine the logic later.

```html
<!-- If this is not the first RC and you cherry-picked any PRs, 
please double-check that they had the correct milestone applied,
and they appear in this changelog. -->
```

**Comment by ockham** [comment]
> Ok, that makes sense.
> 
> > IMO, it's fine to add the note for the release manager as an HTML comment to the release draft; but that should happen in the GHA workflow rather than the changelog.js script
> 
> Sounds good. My bash scripting abilities are super crappy, but I'll give it a try on Monday 🙂

Heh, TBH, my shell scripting is pretty crappy, too -- I constantly have to consult Stackoverflow when writing these workflows 😅 
 
> By the way, is there an easy way to know in the GHA script if is the RC1?

Yeah, so [this line](https://github.com/WordPress/gutenberg/blob/94d553092160adc2e1f9d9362ee87c158a67fea8/.github/workflows/build-plugin-zip.yml#L194) takes the `$VERSION` (e.g. `12.4.0-rc.1`) and splits it into the `$VERSION_ARRAY`, using the period (`.`) as the separator. So we could probably do something like

```bash
if [[ "${VERSION_ARRAY[2]}" == "0-rc" && "${VERSION_ARRAY[3]}" ]]; then
  cat <<- EOF >> release-notes.txt
  <!-- If you cherry-picked any PRs, etc
  etc
  etc -->
  EOF
fi
```

(We still need to solve the original issue, BTW: Detect if the changelog script on [this line](https://github.com/WordPress/gutenberg/blob/94d553092160adc2e1f9d9362ee87c158a67fea8/.github/workflows/build-plugin-zip.yml#L196) returns the confusing error that we'd like to suppress 😅 Might just be a matter of `grep`ping `release-notes.txt` (and removing its contents if the error is there).)

**Pull request closed without merging**
