### PR TITLE
Markdown: Ignore mid-word underscores

### LINKED ISSUE #5335: Copying text with underscores should not convert to italics
Copying text such as `Switch get_locale() to get_user_locale()` produces italics for `locale() to get`. Should not attempt to convert if there is a non-space (or parenthesis, etc) character preceeding the underscore.

### PR DESCRIPTION
**Pull request by mcsf**
## Description
Related: #4942, #4456 

Fixes #5335 

See [Showdown documentation](https://github.com/showdownjs/showdown/blob/master/README.md) for `literalMidWordUnderscores` option:

```
Two _words_ -> Two <em>words</em>
One_word    -> One_word
```

This change removes a small point of collision between two competing formatting systems: Markdown and WordPress shortcode syntax. It fixes cases where pasting a shortcode like `[my_shortcode]foo bar[/my_shortcode]` would be mishandled due to a perceived emphasis (`<em>`) mark in that content.

When pasting:

```
[bw_csv]One,Two,Three
A,B,C
D,E,F
[/bw_csv]
```

Before | After
--|--
before | after

## Types of changes
Bug fix, but also a decision in what we kind of markdown we want to support. I think this is a good chance in itself, but cc @iseulde for thoughts.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by iseulde** [comment]
I can agree with this change. I was thinking we could maybe "protect" shortcakes before handing it over to the Markdown parser. I'm also wondering, since we've been moving shortcake handling up and up, if we should just move it in front of all other handling. This might be less ideal though, as we'd probably make shortcakes out of every link (with the shortcake fallback in place).

In any case, this would need at least a comment, preferably tests to ensure all works as expected. For this we will need to create a WordPress module for shortcakes, instead of using a global.

**Comment by iseulde** [comment]
Unrelate to this, if we continue to use shortcake fallbacks, we might want to rethink how we parse shortcakes. If we just want to match anything (`/\[[a-z][a-z0-9_-]*\]/`), we don't need to parse in so many steps.

**Comment by mcsf** [comment]
(I think your autocorrect is suffering from sugar withdrawal. 😬)

> This might be less ideal though, as we'd probably make shortcakes out of every link (with the shortcake fallback in place).

Yeah, this was my thinking in a previous PR; I wouldn't want to break links/images, and actually I'd be happy if we could fix a different kind of link, the footer kind:

```markdown
This contains an [awesome] link to something. This here is even [better][awesomer].

[awesome]: http://example.org
[awesomer]: http://example.org
```

Which makes me think we might want to perform Markdown parsing before anything else, **assuming** we can get it to leave undefined references alone. That is, given:

```markdown
This contains an [awesome] link to something. This here is even [better][awesomer].

[awesomer]: http://example.org
```

It would generate:

> This contains an [awesome] link to something. This here is even [better](http://example.org).

**Comment by iseulde** [comment]
> Which makes me think we might want to perform Markdown parsing before anything else, assuming we can get it to leave undefined references alone. 

It seems to leave it alone? Or what do you mean?

**Comment by iseulde** [comment]
> (I think your autocorrect is suffering from sugar withdrawal. 😬)

Oops.

**Comment by mcsf** [comment]
@iseulde, so I made this little bundle of horrors:

https://gist.github.com/mcsf/57a4f328ff20ace2b3423bb69c2bcc53

I suggest reading the tests first to get the _intention_. Showdown's extension mechanism feels a bit clunky—from the docs, it doesn't seem like extensions can be dynamic, per-execution, etc., so this patch definitely cheats a lot. Anyway, it... _is_ possible to disable Markdown parsing of shortcode content using Showdown extensions. 😅 It now ignores Markdown-like syntax here:

```markdown
[my_shortcode]hello, _there_.[/my_shortcode]
```

but not here:

```markdown
**oh**, [unknown]hello, _there_.
```

**Pull request merged**
