### PR TITLE
Link UI: Fix focus styles w/ suggestions showing

### PR DESCRIPTION
**Pull request by obenland**
## Description
Limits the height of the suggestion list's top & bottom gradient.

## How has this been tested?
* Checked out #18062 and cherry picked this commit.
* Created a new menu item and started a search for "page" to get a list of suggestions.

#### Before:
Screen Shot 2019-11-05 at 2 02 28 PM

#### After:
Screen Shot 2019-11-05 at 2 02 55 PM

## Types of changes
Bug fix (non-breaking change which fixes an issue) as described in #18135.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by obenland** [comment]
@getdave Do we need those top & bottom gradients at all? They're going from white to transparent on a white background.

**Comment by getdave** [comment]
> I see now that they're there to gracefully hint at more results.

Yep that's why I added them. Tiny hint, but makes a big different in my manual testing.

**Comment by retrofox** [comment]
LGTM 👍, you will need to rebase it, though.

**Review by retrofox — APPROVED** [review]
:shipit: 👍

**Comment by getdave** [comment]
When testing this manually, if I change the bottom gradient to red then I can still see it overlapping when scrolling right to the bottom.

Screen Shot 2019-11-06 at 15 19 59

**Review by getdave — CHANGES_REQUESTED** [review]
When testing this manually, if I change the bottom gradient to red then I can still see it overlapping when scrolling right to the bottom.

Screen Shot 2019-11-06 at 15 19 59

**Comment by getdave** [comment]
A more complex way of doing this might be to [add a `scroll` event listener](https://gist.github.com/getdave/e389ea72ddfc2eb716cbc1cc9af9e707) and check to see if the container has been fully scrolled. If so you can add a class to remove the border.

```
element.scrollHeight - element.scrollTop === element.clientHeight
```

However, if we can solve via CSS that would be _a lot_ easier.

**Comment by obenland** [comment]
For my understanding, you want the gradient and the last item not to overlap at all? Because currently the background and gradient are both white and you won't notice it until the text gets scrolled down. See also  https://github.com/WordPress/gutenberg/issues/18135#issuecomment-550087930

**Comment by getdave** [comment]
My understanding was

* When the container is already scrolled to the bottom (no more items) then there should be no bottom gradient because there is nothing to hint at.
* When the container is already scrolled to the top (no more items) then there should be no top gradient because there is nothing to hint at.

The key is that the gradient only shows in the direction where there are items below the visible area.

**Comment by obenland** [comment]
Yeah I'm not sure we're doing ourselves a favor by trying to make that dynamic. Let me adjust the gradient first and see if that fixes it enough for now.

**Comment by obenland** [comment]
After e0bb753cb8726da979990e1e677dc49c74c2448e:

Last item, scrolled all the way to the bottom:

Screen Shot 2019-11-06 at 3 11 21 PM

Highlighted item with room to scroll:

Screen Shot 2019-11-06 at 3 11 38 PM

**Review by getdave — APPROVED** [review]

**Comment by getdave** [comment]
I tested this and I can longer see the gradient overlapping. :shipit:

**Pull request merged**
