### PR TITLE
Upgrade TypeScript to 5.7 and fix types

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Supercedes #65487

## What?
- Update TypeScript to 5.7.2
- Fix types errors

### Testing Instructions for Keyboard
- CI should be happy

### CODE REVIEW

**Comment by gziolo** [comment]
As we are on this one, can we also increase the minimum required version of TypeScript in the ESLint config package?

https://github.com/WordPress/gutenberg/blob/4335c452609a747faffd74f25b4846d717679e4c/packages/eslint-plugin/package.json#L56

**Comment by manzoorwanijk** [comment]
> increase the minimum required version of TypeScript in the ESLint config package

Done. Thanks

**Review by gziolo — APPROVED** [review]
Looks good to me. The only thing I’m not sure is whether the change fir ESLint config should be flagged as breaking in the changelog.

**Comment by manzoorwanijk** [comment]
> The only thing I’m not sure is whether the change fir ESLint config should be flagged as breaking in the changelog.

Yeah, it should be a breaking change. I have updated the changelog accordingly.

**Comment by gziolo** [comment]
@youknowriad, could you promote @manzoorwanijk to the Gutenberg repository member so he doesn't have to use forks? He had enough commits to qualify for quite some time.

**Review by gziolo — APPROVED** [review]
I tested the changes locally and everything works correctly.

**Comment by youknowriad** [comment]
Invite sent for the repo, thanks for all the contributions.

**Pull request merged**
