### PR TITLE
Expose ThemeSupportCheck component

### PR DESCRIPTION
**Pull request by dougwollison**
Currently the PostTypeSupportCheck wrapper is exposed, but the ThemeSupportCheck one isn't. I'm currently recreating it manually in a project that needs it, since it's for code that I can't easily section out and enqueue conditional on the PHP side.

## Description
I've added an export for ThemeSupportCheck to the editor components listing.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by grappler** [comment]
This would be useful as in [WP 5.4 all of the theme supports](https://core.trac.wordpress.org/ticket/49037) have been added to the REST API.

This is not yet useful for custom theme supports as they can't be registered to the REST API yet: https://core.trac.wordpress.org/ticket/49406

**Comment by ocean90** [comment]
It makes sense to export it now that https://core.trac.wordpress.org/ticket/49406 has landed in 5.5.

@dougwollison Can you give this a rebase please?

**Comment by Mamaduka** [comment]
Hi, @dougwollison

Can you give this a rebase if you have time?

I'll be happy to review and merge changes.

Thanks

**Comment by dougwollison** [comment]
This should be rebased now

**Comment by dougwollison** [comment]
Whoops, did not do that right. Should be actually rebased now.

**Review by Mamaduka — APPROVED** [review]
Thanks for the rebase, @dougwollison.

Changes look good.

**Pull request merged**
