### PR TITLE
Add menu-item-home class to Navigation for front page

### LINKED ISSUE #29423: Page List: missing menu-item-home class for Home Page item
## Description

This issue is related to #29422, but separate as one can be fixed without fixing the other.

In a navigation menu, you might have a "Home Page" item, that links to the homepage (as set in reading options):

Screenshot 2021-03-01 at 10 27 33

For existing WordPress themes and menus, the "Home" menu item gets an additional CSS class, `menu-item-home`, to denote its status. This allows themers to give a special visual treatment to this menu item, should they wish:

Screenshot 2021-03-01 at 10 28 39

This class is missing from the Page List block. 

## Step-by-step reproduction instructions

- Insert a menu block, choose "Add all pages"
- Publish and inspect the website
- Note that the `current-menu-item` class is missing.

### PR DESCRIPTION
**Pull request by georgeh**
Closes #29423

## How has this been tested?
1. Set a static homepage for the WP site
2. Created a Navigation block
3. Added all pages
4. Confirmed that the homepage had the correct class

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
Very nice, thank you! I see the class on the frontend:
Screenshot 2021-12-13 at 10 28 07

I don't see it in the editor, should we have it there too?:

Screenshot 2021-12-13 at 10 28 25

**Comment by georgeh** [comment]
@jasmussen can you try it again? I'm getting the class on the front-end but some async updates were a bit wonky so I'd appreciate another set of eyes.

**Comment by jasmussen** [comment]
Took the latest for a spin, and I might be doing something wrong. I'm still seeing the class on the frontend, but not in the editor. Or was that not the change? Thanks for the work!

**Comment by georgeh** [comment]
@jasmussen it was, of course, a tpyo.

**Review by jasmussen — APPROVED** [review]
Nice! This works well for me. See it on the frontend:
Screenshot 2021-12-21 at 09 05 21

And in the editor:
Screenshot 2021-12-21 at 09 05 32

I'd love a code sanity check, perhaps by @tellthemachines since she's touched this. And this would not be urgent and can easily wait until after the break.

Also, one final question: `menu-item-home` as a class name is probably the right one to use since it matches the existing legacy classname. Just want to flag again whether this is the name we want to use, or whether there's another "this is the homepage" class used somewhere in the codebase.

**Review by Mamaduka — APPROVED** [review]
Thanks, @georgeh.

The code looks good to me 👍

**Comment by Mamaduka** [comment]
Cherry-picked for the 5.9.1.

**Pull request merged**
