### PR TITLE
Get the last mobile changes back in master

### PR DESCRIPTION
**Pull request by Tug**
## Description
Merge the mobile changes back to `master`:
- https://github.com/WordPress/gutenberg/pull/12434
- https://github.com/WordPress/gutenberg/pull/12552
- https://github.com/WordPress/gutenberg/pull/12608
- https://github.com/WordPress/gutenberg/pull/12639
- https://github.com/WordPress/gutenberg/pull/12765
- https://github.com/WordPress/gutenberg/pull/12815
- https://github.com/WordPress/gutenberg/pull/12869

## How has this been tested?
All commits in this branch are part of PRs that have already been approved.
A final check should happen before we merge all our changes back to master

## Types of changes
- Mobile compatibility changes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by youknowriad** [comment]
It looks like it has no web impacts, you can merge at anytime.

**Comment by Tug** [comment]
@youknowriad Thanks for looking into it. I don't have permissions to merge to master though would you mind doing it or giving me the permission?

**Comment by youknowriad** [comment]
Merged, we'll restore the permissions (like before 5.0) in a few days.

**Pull request merged**
