### PR TITLE
Pages: remove unnecessary padding for items

### PR DESCRIPTION
**Pull request by oandregal**
## What?

Note how the outer focus ring doesn't wrap the whole item:

| Before | After |
| --- | --- |
| Screenshot 2024-12-13 at 13 08 02 | Screenshot 2024-12-13 at 13 02 37 |

## Why?

In any other site editor screen, the focus style for the list item takes the whole item.

## How?

Remove unnecessary padding rule.

## Testing Instructions

Go to the Pages screen in the site editor and focus one of the items with the keyboard. Verify the outer ring wraps the whole item.

### CODE REVIEW

**Comment by afercia** [comment]
Good catch. Would this fix also a similar issue for the Navigation panel items? Screenshot:

Screenshot 2024-12-13 at 13 44 04

**Comment by oandregal** [comment]
> Good catch. Would this fix also a similar issue for the Navigation panel items?

No, that's a different thing. The change here only affects screens that use the `DataViewsSidebarContent` component (only Pages and the experimental Post).

**Review by afercia — APPROVED** [review]
LGTM

**Comment by jameskoster** [comment]
This also affects the custom view buttons, making the ellipsis a bit too close to the edge of the container.

Screenshot 2024-12-13 at 13 27 53

But these buttons are already a bit broken, and experimental, so perhaps it's okay?

**Comment by oandregal** [comment]
> This also affects the custom view buttons, making the ellipsis a bit too close to the edge of the container.

Pushed https://github.com/WordPress/gutenberg/pull/67977/commits/2b5bd7baf36ea3ae60c7014e319939b7e23ebc5d that scopes the padding to custom items.

**Pull request merged**
