### PR TITLE
Patterns: split up the block editor inserter patterns tab into separate component files 

### PR DESCRIPTION
**Pull request by glendaviesnz**
## What?

Refactors the block editor inserter patterns tab in to separate component files and renames some components for clarity.

## Why?

The `packages/block-editor/src/components/inserter/block-patterns-tab.js` file has grown quite large over time and contains a mix of hooks, components and util files which makes it more difficult to work on. Also the component naming is a little confusing with a dialog component loading a panel component.

## How?

Breaks all the individual parts of the patterns inserter tab out into separate files in a subfolder. Also renames the dialog and preview components. The pattern previews panel is more of a panel than a dialog so renames the relevant components to better indicate the relationship.

## Testing Instructions

- In the block editor test all aspects of the inserter patterns tab, check categories display as expected, preview panel works, filtering in preview panel, paging for larger categories, patterns insert correctly when selected, etc.
- Check that the explorer panel also works as expected still

### CODE REVIEW

**Review by apeatling — COMMENTED** [review]
I went through the inserter patterns view and from everything I could interact with there I didn't see any issues:


https://github.com/WordPress/gutenberg/assets/1464705/7a90f331-ec78-45e1-a176-3c34ebe1062b

**Comment by apeatling** [comment]
There does seem to be an issue with the patterns explorer. In Safari if I select a pattern category, the explorer modal seems to abruptly close. This doesn't seem to happen for every category though. 🤔

https://github.com/WordPress/gutenberg/assets/1464705/9ba410b0-fed4-4e4c-b8f7-e1541ada9764

**Comment by glendaviesnz** [comment]
Thanks @apeatling, the modal closing is [happening on trunk](https://github.com/WordPress/gutenberg/issues/55110), so I don't think it is related to this PR. I can't replicate this issue, but when you have time can you please see if you experience the same thing on trunk just so we can make sure it isn't a separate issue on this PR?

**Review by aaronrobertshaw — COMMENTED** [review]
Nice work cleaning up the block patterns tab components @glendaviesnz 👍 

The refactored components match existing code (naming changes excepted) and I didn't spot any regressions while testing:

✅ Categories displayed correctly
✅ Previews work as expected
✅ Filtering in the preview panel worked
✅ Paging still functions as before
✅ Pattern insertion still works
❓ Patterns explorer works

I noticed that the patterns explorer closes immediately on category selection in Safari but that also appears to be the case on `trunk` too. Wasn't a similar issue to this fixed recently? Either way addressing it in a follow-up probably makes sense.

Before we land this, there are a few other things we could tweak under the code quality banner. Let me know what you think of;

- Matching file names with the component names e.g. `category-preview-panel.js`
- Using consistent naming for all these components e.g. `BlockPatternsSyncFilter` vs `PatternsCategoryPreviews`
- Should the block patterns explorer's primary file moved to `index.js` for consistency?

**Comment by glendaviesnz** [comment]
Thanks @aaronrobertshaw I have tidied up the file and component naming as suggested.

There is [an open issue](https://github.com/WordPress/gutenberg/issues/55110) for the pattern explorer crashing in Safari which we should follow up separately once these changes are merged.

**Comment by glendaviesnz** [comment]
> I noticed that the patterns explorer closes immediately on category selection in Safari but that also appears to be the case on trunk too.

I wasn't able to replicate this on this PR or trunk, what version of Safari are you running?

**Comment by aaronrobertshaw** [comment]
> I wasn't able to replicate this on this PR or trunk, what version of Safari are you running?

Version 17.1

**Comment by glendaviesnz** [comment]
@aaronrobertshaw are you happy with this PR with the most recent naming changes? I think the safari issue should be dealt with separately as it is an existing issue on trunk.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the updates @glendaviesnz 👍 

After another smoke test, the pattern inserter and explorer are still working as advertised for me.

The naming and organisation of component files looks much better 👌

**Pull request merged**
