### PR TITLE
Fix issue with floated block toolbar on adjecent floats

### LINKED ISSUE #3870: Blocks: Broken layout when multiple floated blocks in succession
## Steps to Reproduce (for bugs)
1. Add an image block.
2. Make it aligned to left.
3. Add a button block.
4. Make it aligned to left.
5. Add another block.

Browser: Chrome
System: macOS

## Expected Behavior

Blocks are properly aligned.

## Current Behavior

Broken layout when multiple floated blocks in succession.

## Screenshots / Video
screen shot 2017-11-30 at 10 09 05

screen shot 2017-12-08 at 15 18 24

/cc @jasmussen

### PR DESCRIPTION
**Pull request by jasmussen**
Fixes #3870

When you have multiple small blocks floated left, each blocks get a more and more indented block toolbar. At some point the block toolbar will be cropped by the viewport itself.

This PR adresses that by making it always leftalign. There appear to be no side-effects, but it would be good to test.

Before:

before

After:

after

### CODE REVIEW

**Comment by youknowriad** [comment]
The side effect I noticed is that the toolbar don't float right floated blocks anymore but maybe that's ok?

**Comment by jasmussen** [comment]
Another case of your eagle eyes! Nice catch. Found a simple fix:

screen shot 2018-02-23 at 12 24 57

**Comment by youknowriad** [comment]
There are some issue like this. But I don't what should be the behavior here, I'm fine with the current one

screen shot 2018-02-23 at 12 42 24

**Review by youknowriad — APPROVED** [review]
LGTM 👍

**Comment by youknowriad** [comment]
OH I'm seeing an issue here. Floated block's toolbars don't stick when scrolling

**Comment by jasmussen** [comment]
Good catches — I don't know that we can fix the toolbar overlap with multiple small paragraphs like that, not easily anyway. I think that's a fundamental challenge between having a block-docked toolbar, and floats.

The sticking toolbar on floats we can't fix easily either, alas — becasue the heightof the floated element is essentially zero, so while the sticking does work, it doesn't scroll with you down the page. 

However we may be able to fix those sticking toolbars as part of a different refactor. I'm about to look into allowing collapsible margins, which is a necessary step towards better nested handling. Part of that means we have to move the toolbar div deeper inside the block, as demonstrated here https://codepen.io/joen/pen/aqKLqa?editors=1100 — if we do that, then the sticking might work because suddenly it's not relative to the zero-height collapsed parent, but to the floated element instead. _Maybe_. 

However I think this is an okay tradeoff to make, as floated items are usually not that tall. And the sticking toolbar still works on normal, wide and fullwide images. Thoughts?

**Comment by youknowriad** [comment]
Yes, in general when you float blocks, these blocks are not supposed to be very long, so I'm ok with the tradeoff.

**Comment by jasmussen** [comment]
Awesome. Merging and we can revisit. Thank you.

**Pull request merged**
