### PR TITLE
Add new hook for Gutenberg latest posts block

### PR DESCRIPTION
**Pull request by romain-d**
Hello, 

following my error on the WordPress trac, I redo this PR here. 
FYI https://core.trac.wordpress.org/ticket/51694

Add a hook to changes arguments of Gutenberg latests posts block query

Romain DORR, Be API

### CODE REVIEW

**Review by noisysocks — CHANGES_REQUESTED** [review]
Thanks @romain-d. Looks good, two notes:

1. Let's drop `core` and simply name this filter `block_latest_posts_query_args`. In WordPress, filters that don't have a prefix are implicitly core filters.

2. Could you please add a doc comment before the `apply_filter` which explains what this filter does? You can see an example of what one of these looks like [here](https://github.com/WordPress/wordpress-develop/blob/2b7b306f249d71e6f9b9f90a9f90552ef72f5660/src/wp-includes/widgets.php#L275-L283). In this case we'll want `@since 5.7.0`.

**Comment by romain-d** [comment]
Hi @noisysocks ,

Thanks for the feedback, I made the requested changes.

Best,
Romain DORR, Be API.

**Review by noisysocks — APPROVED** [review]

**Comment by noisysocks** [comment]
@romain-d: Could you please rebase `master` into this branch? There are some unrelated E2E test failures that are preventing us from getting a ✅.

**Review by noahtallen — APPROVED** [review]
Nice stuff!

**Comment by youknowriad** [comment]
I'm not really sure adding an adhoc hook for a specific block is a good idea? were there any discussion about this?

**Comment by gziolo** [comment]
There is already a general-purpose hook for modifying block's data: [`render_block_data`](https://developer.wordpress.org/reference/hooks/render_block_data/). There are more filters that let you hook into the rendering process. It would be great to know what type of customization they aren't covering.

**Comment by mcsf** [comment]
> I'm not really sure adding an adhoc hook for a specific block is a good idea? were there any discussion about this?

Agreed. Unless there is a really compelling for this block-specific hook, it seems important to revert so as not to open a precedent.

**Comment by noahtallen** [comment]
It seems like the use case would be adding or removing an argument to the query which gets the latest posts for the block. That doesn't seem possible with the existing hooks

**Comment by youknowriad** [comment]
Sometimes, it's not about it being possible or not. We need to make hard decisions. In this particular instance, someone could just replace the latest post block by his own block or override the render function. Yes, it's not as simple as a simple hook but it's better than having adhoc hook that we'll be forced to maintain. Especially since the Query block is meant to  replace that block anyway.

**Comment by noahtallen** [comment]
@youknowriad I added a revert here since I merged this: #27078

**Comment by youknowriad** [comment]
Thank you Noah

**Pull request merged**
