### PR TITLE
Archives: Make the label above the dropdown editable

### PR DESCRIPTION
**Pull request by colinduwe**
## What?
Adds an editable label attribute to the Archives block that is displayed when "display as a dropdown" is selected.

## Why?
https://github.com/WordPress/gutenberg/issues/57528
Currently the dropdown is not editable.

## How?
This initial commit puts the label textControl in the sidebar which is suboptimal. It should be directly editable. 

## Testing Instructions
1. Open a post or page.
2. Insert an archives block.
3. Set to display as a dropdown and show label
4. Set a custom label. 
5. Note that toggling the display as dropdown or show labels shows/hides the textControl for the label correctly.
6. save post and confirm label is shown on the front end and the editor.

### Testing Instructions for Keyboard
Similar to cursor, but confirm that tab controls correctly include the new textControl to set the label. The tab control works correctly when the textControl is removed when the display as dropdown is unchecked.

Screenshot 2024-01-05 at 2 12 47 PM

### CODE REVIEW

**Review by carolinan — COMMENTED** [review]
Hi @colinduwe 
Thank you for working on this enhancement.

The feature works well for me. Code wise, there is only the small coding standard issue with the spacing.

By making the label editable with a TextControl in the settings panel and not as a RichText, we avoid needing to change the `disabled` state of the block in the editor.

But we also loose the RichText features like making part of the text bold or use a different color. And we loose some consistency with other blocks that uses the RichText for the label, like the search block.

I am pinging the @WordPress/gutenberg-design team to ask for their feedback.

I will follow this closely because, no matter if we are editing the label in the canvas or in the inspector (the sidebar),  I want the archives block and categories block to match.
Related: https://github.com/WordPress/gutenberg/pull/56364

**Comment by jasmussen** [comment]
The following is not a strong opinion so I can defer to others if need be. 

Custom prefixes like these felt more appropriate for classic widgets, as there really was no convenient way to give them a title otherwise. In the block editor, in most cases, it's trivial to insert a paragraph or a heading before a particular block. In the case of inserting a heading, it is almost always going to be a better result when inserted manually, since it's important to get the heading level hierarchy right.

Separately, however, there have been some discussions around blocks that are more inline in nature, like next/prev buttons, etc, where a prefix or suffix can be more useful to have, rather than have to deal with row blocks. I vaguely recall some conversations around putting such prefixes and suffixes in the "advanced" section? Regardless of where that landed, it would be good to sync up with the result of that, so we don't create a UI that diverges from it.

**Comment by carolinan** [comment]
The label is required because the select list is a form element.
The label is always present in the markup, but it has not been editable.
So even if the user kept the label visually hidden, they were unable to edit the label based on context.
For example, if the block was set to show a monthly archive, there was no way to use the label "Monthly archive".
There was no way to differentiate the blocks if multiple of them were placed together.

So adding a heading above it is not so helpful.

**Comment by getdave** [comment]
Hi @colinduwe. Thank you very much for this PR.

It looks like you have quite a few files changed here which maybe due to merging rather than rebasing against `trunk`.

You can

- pull the latest trunk
- checkout this branch
- rebase against trunk - `git rebase trunk`.

Then you can force push the branch to update.

**Comment by colinduwe** [comment]
Yes, I'm not 100% clear what went awry when I rebased to apply this branch atop the current trunk. I'm going to close this and submit a new PR that isn't such a mess. Apologies.

**Pull request closed without merging**
