### PR TITLE
Experiment: Measure performance impact of loading blocks and patterns 

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Opened to measure the impact of loading core blocks and block patterns on the block editor's performance.

I want to check the performance metrics when:
- core block patterns are removed
- non-essential core blocks are removed

### CODE REVIEW

**Comment by gziolo** [comment]
## Block Patterns removed

Screen Shot 2021-08-02 at 09 18 30

I see load time decrease by 182 ms, which is 3% faster. It's still in the range of the testing error that was estimated at 5%.

**Comment by gziolo** [comment]
## Most of the core block and all block patterns removed

Screen Shot 2021-08-02 at 12 28 48

I see load time decrease by ~352 ms, which is 5% faster. It's still in the range of the testing error that was estimated at 5%. I would be curious to learn what has the biggest impact on the loading time here – my initial assumption is the time to render all test blocks.

Another observation is that `maxInserterOpen` gets improved by ~85 ms which is nearly 18% faster. That is expected because we render only a handful of blocks. The good news is that the most recent optimizations applied by @youknowriad with the help from @gwwar in https://github.com/WordPress/gutenberg/pull/33749 aren't very sensitive to the number of total blocks rendered anymore.

It's also worth mentioning but the removed core blocks contribute to over 11% of the download size (CSS + JS) when loading the block editor:

Screen Shot 2021-08-02 at 12 50 05

**Comment by gziolo** [comment]
## Most of the core block and all block patterns removed, only blocks present in the loaded post

Screen Shot 2021-08-02 at 13 42 03

I see load time decrease by 95 ms, which is 8% faster. It's also evident that the size of the post is the largest factor that impacts the loading time. It's over 5 seconds decrease, which is 80% faster, when comparing the loading time for `trunk` in the case where only 3 blocks get loaded instead of the large post.

The conclusion is that core block and core block patterns don't have that much impact on the loading time, at least in the case of the e2e test scenario. We should seek for different testing approaches to validate how the bundle size increase for core blocks impacts the perceived performance of the block editor.

**Comment by gwwar** [comment]
Related is also https://github.com/WordPress/gutenberg/pull/33767 where I tested not rendering drag/icons. 🤔  there is some impact, but we may want to keep 🔍 for why these are as slow for the number of items. (For example, maybe we're triggering a number of updates).

```
┌──────────────────┬──────────────────────────────────────────┬─────────────┐
│     (index)      │ 6e17a6b56b47f7afc05c73f0484e0c7b3acf3324 │    trunk    │
├──────────────────┼──────────────────────────────────────────┼─────────────┤
│       load       │               '6253.6 ms'                │ '6420.2 ms' │
│       type       │                '31.73 ms'                │  '36.3 ms'  │
│     minType      │                '25.47 ms'                │ '30.17 ms'  │
│     maxType      │                '63.16 ms'                │ '68.43 ms'  │
│      focus       │               '113.05 ms'                │ '73.18 ms'  │
│     minFocus     │                '57.94 ms'                │ '61.29 ms'  │
│     maxFocus     │               '315.45 ms'                │ '121.83 ms' │
│   inserterOpen   │               '203.71 ms'                │ '296.25 ms' │
│ minInserterOpen  │               '152.52 ms'                │ '234.28 ms' │
│ maxInserterOpen  │                '537.8 ms'                │ '647.84 ms' │
│  inserterHover   │                '23.61 ms'                │ '24.74 ms'  │
│ minInserterHover │                '18.42 ms'                │ '19.59 ms'  │
│ maxInserterHover │                '42.26 ms'                │ '34.85 ms'  │
└──────────────────┴──────────────────────────────────────────┴─────────────┘
```

**Comment by gwwar** [comment]
Btw if folks are looking for leads on improving loading time, a handy thing to do in Chrome is use the "Start profiling and reload page" button, and make sure web vitals is checked.
| Reload | Web Vitals |
|-----|-----|
| Screen Shot 2021-08-02 at 8 50 09 AM | Screen Shot 2021-08-02 at 9 02 39 AM |

Then I'd go through interesting network requests / remove JS to parse / any long running tasks to find any chunks to experiment with. To get a sense of potential gains it can make sense to fully comment out a piece to see if it's worth trying to optimize. (If there isn't a sizable impact we can skip to some other idea).

* This is going to be sensitive to development vs production builds, so be sure to verify an idea early with `npm build` vs `npm run dev`.
* Also test on a guest profile (that doesn't have any extensions set/indexedDB/localStorage data).

**Comment by gwwar** [comment]
Thanks for testing this @gziolo!

> The conclusion is that core block and core block patterns don't have that much impact on the loading time, at least in the case of the e2e test scenario. We should seek for different testing approaches to validate how the bundle size increase for core blocks impacts the perceived performance of the block editor.

I just did a quick check on trunk to see how much time is taken to parse JS from the block-library package. The package is sizable, but I saw several other JS dependencies that were as large or larger.

One thing that stands out is how many other JS dependencies we have for the block editor. It might be interesting to separate out what's needed for wp-admin screens vs the block-editor (or what can be deferred for on demand or async loading). For example, is jQuery/backbone/underscore necessary when we're in fullscreen mode? Can we remove the moment dependency? Are we using all components from the component package? And so on...

Screen Shot 2021-08-02 at 9 24 19 AM

**Comment by gziolo** [comment]
One more thing. I discovered there is Size Limit GitHub Action: https://github.com/ai/size-limit.

> Size Limit is a performance budget tool for JavaScript. It checks every commit on CI, calculates the real cost of your JS for end-users and throws an error if the cost exceeds the limit.

It not only calculates bundle sizes like "Compressed Size" GitHub action but it also can:
- calculate the time it would take a browser to download and execute your JS
- calculations include all dependencies and polyfills used in your JS

> One thing that stands out is how many other JS dependencies we have for the block editor. It might be interesting to separate out what's needed for wp-admin screens vs the block-editor (or what can be deferred for on demand or async loading). For example, is jQuery/backbone/underscore necessary when we're in fullscreen mode?

I filed an issue https://github.com/WordPress/gutenberg/issues/32665 some time ago that proposes to move the Classic block and Meta Boxes to their own package so it is loaded only with the post editor. The rationale behind that was to eventually stop loading jQuery or TinyMCE when those features aren't used.

> Can we remove the moment dependency?

There was a failed attempt to replace `moment` with `date-fns`. We should try it again, the blockers were detected only on the backward compatibility front - it's a very fragile one though.

> Are we using all components from the component package? And so on...

This is where backward compatibility concern kicks in. Even when WordPress core doesn't use some of the components, they are part of public API so they need to be shipped in `@wordpress/components` because 3rd party projects may want to use them. In general, once something becomes public API, we can't tree-shake it.

**Comment by gwwar** [comment]
> One more thing. I discovered there is Size Limit GitHub Action: https://github.com/ai/size-limit.

Oh that's a neat one ✨ Probably very useful to put that up or something similar, especially if we'd like to keep things fast loading after a round of loading improvements.

> There was a failed attempt to replace moment with date-fns. We should try it again, the blockers were detected only on the backward compatibility front - it's a very fragile one though.

Very tempting to 👀 again on that since there are only a few usages.

> I filed an issue #32665 some time ago that proposes to move the Classic block and Meta Boxes to their own package

Nice I'll try to catch up 👀  on related PRs

> This is where backward compatibility concern kicks in. Even when WordPress core doesn't use some of the components, they are part of public API so they need to be shipped in @wordpress/components because 3rd party projects may want to use them. In general, once something becomes public API, we can't tree-shake it.

That's a good point. Over time we'll probably still need to think through a strategy for what might be a core/necessary component, vs opt-in extras. It feels like the package will naturally grow over time otherwise.

**Comment by gziolo** [comment]
#33903 from @youknowriad is close to land. It improves the loading time by nearly 5% for the post editor thanks to some optimizations to the block parsing logic. I'm about to change the base branch here to see how the loading time changes relative to the setup in this test branch. Although, there should be really no difference here.

Update, there is no much difference with https://github.com/WordPress/gutenberg/pull/33804#issuecomment-890958388. It's still 8% which isn't surprising because there are only a few blocks to parse in the tweaked perf test...

**Comment by gziolo** [comment]
Let's close this PR. I will perform some more measurements separately. I'd like to play with the profiler as recommended by @gwwar in https://github.com/WordPress/gutenberg/pull/33804#issuecomment-891146605 🙇🏻

**Pull request closed without merging**
