### PR TITLE
Style book: remove styles from examples

### LINKED ISSUE #67092: The Style Book not working as expected when tweaking dimensions
### Description

When I modify the dimensions of certain blocks in the Style Book globally, it does not work as expected. I would expect you to see the changes you make. When I change the block spacing of the Columns block, the layout becomes misaligned or distorted. When I update the padding of the Group block, nothing changes visually. 

### Step-by-step reproduction instructions

1. Go to the Style Book
2. Modify the block spacing of Columns block and try to update the padding and margin of the Group block

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c114cec2-04ef-40d7-8b62-62bf6e4ea534

### Environment info

- WordPress 6.7 
- Chrome
- MacBook Pro

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

### PR DESCRIPTION
**Pull request by ramonjd**
## What? How? Why?

Resolves https://github.com/WordPress/gutenberg/issues/67092

In the style book, remove block example styles because they prevent global styles from being tested/previewed.

For the cover block example, move the styles up to the container block.

## Testing Instructions

1. Fire up the site editor.
2. Open the style book and head to the "Themes" tab.
3. Find the group block, select it, then edit the group block's global padding styles.
4. You should see the padding changes represented on the canvas.
5. Do the same for the cover block, but edit its font size and text color. The changes should appear!
6. Know that your time is valuable and appreciated.

### Group block
https://github.com/user-attachments/assets/03fe90d0-cfbd-4edf-a538-4cf96f147f62

Also check what the group example looks like in the preview - it's example padding should be preserved:

Screenshot 2024-11-20 at 12 40 26 pm

### Cover block

https://github.com/user-attachments/assets/9f8218fa-4a6c-45d9-aa32-e8c54fdf2109

The cover block preview should look the same as before:

| Trunk | This PR |
|--------|--------|
| Screenshot 2024-11-20 at 12 48 45 pm | Screenshot 2024-11-20 at 12 47 27 pm |

### CODE REVIEW

**Comment by ntsekouras** [comment]
While this solves the issue for `Group`, I'm wondering if a better approach would be to strip the styles from block's examples. That way we'd be covered with any third party block too, right? If we did that we'd probably update `getBlockFromExample` and we should mention it in docs that  a block's example shouldn't contain styles.

Noting that we have at least `Cover` with similar styles in its example.

**Comment by ramonjd** [comment]
> I'm wondering if a better approach would be to strip the styles from block's examples. That way we'd be covered with any third party block too, right? 

That's a good point, thank you! My assumption is to only strip them from the containing block's attributes (?)

My only hesitation is that, existing third party blocks, it would be considered a breaking change, e.g., "Why doesn't my block example look like it did before?"

For that reason, I reckon we should limit it to core blocks at the very start.

For the group block in particular, I think it's still okay to strip the styles here regardless. The padding doesn't contribute a great deal visually, and, as one of the most used core container blocks, I think global styles should take universal precedence.

**Comment by ramonjd** [comment]
>  I'm wondering if a better approach would be to strip the styles from block's examples. That way we'd be covered with any third party block too, right? 

@ntsekouras I took your idea and only applied it to style book blocks. 

This addresses the original issue and also preserves any examples that have styles for the purposes of inserter previews etc.

The group block is the only block affected

As for the Cover block, [the style is applied to the inner block](https://github.com/WordPress/gutenberg/blob/fd3ecc2157c00f7d2d90a4329029120b29d2871a/packages/block-library/src/cover/index.js#L38-L38). 

In my view this should have been applied to the container block. I'll hoist it in this PR. The result should be the same.

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the PR @ramonjd 👍 

✅ Cover block example looks consistent after hoisting styles
✅ Group block example in Style Book now reflects changes in Global Styles padding
✅ Group block examples in inserters appear as before

I think this PR strikes a good balance between maintaining existing rendering for block previews and allowing the Style Book examples to reflect the current Global Styles etc.

I like that 3rd party extenders get the fix/enhancement for free in the Style Book.

🚢 


https://github.com/user-attachments/assets/32436b86-fd88-4ba5-9f5a-8d8195855ae7

Screenshot 2024-11-20 at 11 54 20 am

**Comment by aaronrobertshaw** [comment]
> In my view this should have been applied to the container block. I'll hoist it in this PR. The result should be the same.

This wasn't possible when the example was added, around 2 years ago. The text color support was added a year later. 

The styles could have been moved to the wrapping cover block when that support was added but the Style Book was pretty new then so this issue wasn't foreseen.

**Comment by ramonjd** [comment]
> This wasn't possible when the example was added, around 2 years ago. The text color support was added a year later.

Thanks for the context. Thought it might have been something like that. Another win for block supports! 🏅

**Comment by ntsekouras** [comment]
Thank you @ramonjd!

>@ntsekouras I took your idea and only applied it to style book blocks.

Initially I would suggest that, but then I thought about the previews in Global styles sidebar and that we could need this in general. Probably it's fine to address the specific previews for now - I don't think we have other similar previews.

I also opened a PR about the sidebar previews [here](https://github.com/WordPress/gutenberg/pull/67144).

**Pull request merged**
