### PR TITLE
Update `moment` and `moment-timezone` packages to fix timezone issues

### LINKED ISSUE #47698: DateTimePicker Displays an Incorrect Calendar if the user's timezone is vastly different from the WordPress one.
### Description

When the user's timezone is significantly different than the timezone that WordPress is configured with, the DateTimePicker component displays incorrectly. The first day of the month that is being displayed is the last day of the previous month. This causes some days within the month to disappear.  

Similar issue to https://github.com/WordPress/gutenberg/issues/29306 however this targets the month's display.

### Step-by-step reproduction instructions

1. Change your local machine's timezone to somewhere in England. 
2. Set WordPress's timezone setting to Los Angeles.
3. Edit or Add a new post.
4. Open the DateTimePicker component by trying to schedule a post.

### Screenshots, screen recording, code snippet

image

### Environment info

- WordPress Version 6.1.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by wojtekn**
## What?

In this PR, I propose to update the `moment` and `moment-timezone` packages to match the versions used by WP core.

## Why?

It should fix the timezone-related issues e.g. https://github.com/Automattic/wp-calypso/issues/71529 and fix https://github.com/WordPress/gutenberg/issues/47698

## How?

`moment-timezone` package is being updated to catch with IANA time zone database changes. Last year some time zones were renamed e.g. Kiev to Kyiv (https://github.com/moment/moment-timezone/issues/986). This update should fix issues for such timezone, and possibly it will fix other issues related to timezones.

## Testing Instructions

1. Set WordPress's timezone setting to Kyiv
2. Edit or Add a new post.
3. Open the DateTimePicker component by trying to schedule a post.
4. Choose date and hour
5. Save post
6. Open the DateTimePicker component and confirm that hour displayed is the same as in the block
7. Confirm that there is no "Moment Timezone has no data for Europe/Kyiv." JS error in the browser console 

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

| Incorrect | Correct |
|---|---|
| Screenshot 2023-02-08 at 14 50 00 |  Screenshot 2023-02-08 at 14 50 07 |

### CODE REVIEW

**Comment by gziolo** [comment]
`moment` is externalized in the context of WordPress so we don't have to worry about that part as it's pure for development purposes in the repository and for 3rd party consumes of npm packages. There is a slight increase in the bundle size for `moment-timezone` but that shouldn't be a blocker:

### Before

Screenshot 2023-02-09 at 08 06 29

### After

Screenshot 2023-02-09 at 08 08 49

**Review by gziolo — APPROVED** [review]
I haven't tested the changes, but they look correct and all CI cheks still pass. I can confirm that the version of `moment` aligns now with WordPress core:

https://github.com/WordPress/wordpress-develop/blob/7104aa0a9c75b64ee0bb5e5390bb564519e3022d/package.json#L151

The only caveat is that in core, it's pinned and here we correctly allow newer versions to avoid locking 3rd party package consumers.

**Review by tyxla — APPROVED** [review]
Looks good, tests well too, thanks @wojtekn 👍 

The bundle size change is unfortunate, but it's one more signal that we should be seeking ways to get rid of `moment` completely at some point. There is an open issue about it for anyone interested: https://github.com/WordPress/gutenberg/issues/43533

**Comment by gziolo** [comment]
@Mamaduka or @ntsekouras – is it something you would be fine adding to the scope of the WordPress 6.2 release?

**Comment by Mamaduka** [comment]
@gziolo matching the library versions makes sense to me 👍

**Comment by ntsekouras** [comment]
Cherry-picked this PR to the wp/6.2 branch.

**Pull request merged**
