### PR TITLE
Fix: changing month or day in post publish date closes the popover.

### LINKED ISSUE #17042: Post scheduler: Cannot move to prev/next month
After upgrading to Gutenberg 6.3.0, I cannot move to the previous or next month when scheduling a post publish date. The date picker dialog is hidden after clicking on the navigation buttons:

Aug-15-2019 11-15-40

The issue is not reproducible in Gutenberg 6.2.0.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
## Description
Fix: https://github.com/WordPress/gutenberg/issues/17042

Currently, changing the month using previous/next buttons in the date picker closes the popover making it unusable and making post scheduling an arduous task.

The problem happens because when we click previous/next buttons, a focus lose occurs. I did lots of debugging, and I did not found a cause for this in our code. We will need an upstream commit on react-dates. But until then, this PR uses onPrevMonthClick/onNextMonthClick events to force the focus to be inside the focusable region.

## How has this been tested?
I checked that I could change the day or month in the post scheduler, and the popover does not close.

### CODE REVIEW

**Review by epiqueras — DISMISSED** [review]

**Review by noisysocks — DISMISSED** [review]
When I test this PR I notice that you can no longer dismiss the date picker by clicking anywhere on the _Document_ sidebar. There are similar problems with the inserter and the More menus.

I don't think that this fixes the root cause of the issue which is that there's a _focus loss_ when the _Next month_ button is clicked. It's the loss of focus which is causing `withFocusOutside` to (correctly) close the menu.

You can see what I mean by:

1. Open DevTools.
2. Open the schedule date picker.
3. Click the _Next month_ button.
4. In DevTools, run: `document.activeElement`

`document.activeElement` should be the _Next month_ button, but it is not.

**Comment by jorgefilipecosta** [comment]
Thank you for the reviews @noisysocks, @epiqueras. It seems the previous fix was invalid. And I was not able to find a "correct" fix. Probably we should debug the problem upstream on react dates and add a commit there that avoids the focus lose. But until then I commit a fix that essentially guarantees that when we click next/prev month, the focus is kept on the date picker focusable region.

**Review by epiqueras — CHANGES_REQUESTED** [review]

**Review by epiqueras — APPROVED** [review]

**Comment by noisysocks** [comment]
Cool hack! Thanks @jorgefilipecosta! 👍

**Comment by jorgefilipecosta** [comment]
> This one deserves an e2e test :)

Hi @youknowriad, I totally agree, I will look into creating a simple e2e test.

**Pull request merged**
