### PR TITLE
[Documentation] Add examples for core/keyboard-shortcut package

### PR DESCRIPTION
**Pull request by t-hamano**
## What?
This PR adds examples for the `core/keyboard-shortcut` package docs. Part of #42125

I used `createInterpolateElement` to display the key in the code `tag`, but that made the code a bit longer.
To make example code more simpler, it might be good to remove this function.

## Testing Instructions

Paste the example code from [the documentation page](https://github.com/WordPress/gutenberg/blob/feature/add-examples-for-core-keyboard-shortcuts/docs/reference-guides/data/data-core-keyboard-shortcuts.md) using the following code:

```javascript
import { PluginDocumentSettingPanel } from '@wordpress/edit-post';
import { registerPlugin } from '@wordpress/plugins';

// const ExampleComponent Here

const SlotFill = () => {
	return (
		<PluginDocumentSettingPanel
			name="code-ex"
			title="Data Module Document Test"
		>
			<ExampleComponent />
		</PluginDocumentSettingPanel>
	);
};

registerPlugin( 'code-ex', {
	render: SlotFill,
} );
```

I also created a minimal plugin to test all examples.

[keybard-shortcut-example.zip](https://github.com/WordPress/gutenberg/files/11857048/keybard-shortcut-example.zip)

Import only the examples you wish to test and then build:

example

## Screenshots or screencast

When you run the example code, you should get the following results:

#### getAllShortcutKeyCombinations

getAllShortcutKeyCombinations

#### getAllShortcutRawKeyCombinations

getAllShortcutRawKeyCombinations

#### getCategoryShortcuts

getCategoryShortcuts

#### getShortcutAliases

getShortcutAliases

#### getShortcutDescription

getShortcutDescription

#### getShortcutKeyCombination

getShortcutKeyCombination

#### getShortcutRepresentation

getShortcutRepresentation

#### registerShortcut

registerShortcut

#### unregisterShortcut

unregisterShortcut

### CODE REVIEW

**Comment by gziolo** [comment]
Nice work @t-hamano. Thank you for your another contribution. We need help with reviewing those examples.

**Comment by ndiego** [comment]
This PR was reviewed in today's Block Editor Handbook Docs Scrub, and we wanted to see if anything is holding up this PR besides a thorough review?

**Comment by t-hamano** [comment]
I rebased this PR with the latest trunk branch and tested all the examples again. All samples appear to be working as expected.

**Review by ryanwelcher — APPROVED** [review]
Testing via the plugin and everything worked as expected. This is fantastic work @t-hamano (as usual)! Let's get it merged!

**Comment by ryanwelcher** [comment]
I merged latest trunk and pushed to trigger the checks that didn't report correctly. Hopefully that will get this moved forward. I'll enable auto-merge as well.

**Comment by t-hamano** [comment]
Thanks for the review, @ryanwelcher!

**Pull request merged**
