### PR TITLE
Try: Swap pencil icon for drawer icon in template details panel

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
In the template details panel there is an icon button (`pencil`) which invokes the full-screen editor on click. This PR replaces `pencil` with `drawerLeft` / `drawerRight` (according to `is_RTL()`).

## Why?
I've seen feedback that the pencil icon looks like a 'rename' affordance for the title. 

## Testing Instructions
1. In the site editor open navigate to a template e.g. Index.
2. Observe the pencil icon button is replaced with the drawer icon.

### Before
Screenshot 2023-09-05 at 14 58 10

### After
Screenshot 2023-09-05 at 14 57 53

I'm not sure how successful this is so I've only updated the template details panel for now. Perhaps there are other solutions we might consider. What do y'all think?

### CODE REVIEW

**Comment by jasmussen** [comment]
I see the intent, but I don't know that "Close sidebar & edit" is going to be better than simply "Edit", which would also be inclusive of mobile where this wouldn't be a sidebar that closes.

**Comment by richtabor** [comment]
> I see the intent, but I don't know that "Close sidebar & edit" is going to be better than simply "Edit", which would also be inclusive of mobile where this wouldn't be a sidebar that closes.

Agree. What about a "Edit" button? 

CleanShot 2023-09-11 at 16 35 28

**Comment by annezazu** [comment]
>I've seen feedback that the pencil icon looks like a 'rename' affordance for the title.

Just chiming in that I've seen this feedback as well with the FSE Outreach Program. I'd like to see this iterated upon and am glad to see this PR.

**Comment by jasmussen** [comment]
I think we can find a better edit icon, but I would avoid the "Edit" button label, we had that in earlier mockups and it does not scale to the detail pages that feature both ellipses, edit icons, and .. what was the third?

**Comment by ellenbauer** [comment]
I can see that the Pencil icon can be misunderstood, but I also feel the Sidebar icon is even more confusing if the action is 'edit this template'. 

As it's the most important task for the template imo using the text button 'Edit' feels appropriate as it is not 100% clear that and how a template can be edited.

I have seen that customized Templates do have the Actions icon, so could it also be possible to use that and create a list of possible tasks like edit, clear customizations etc. and have an icon in front of each one. Similar to the screenshot below from Notion?

Screenshot 2023-09-18 at 8 19 54 PM

**Comment by jameskoster** [comment]
> so could it also be possible to use that and create a list of possible tasks like edit, clear customizations etc

That might be worth a try.

**Comment by jameskoster** [comment]
I updated the PR to move the edit action to the ellipsis as suggested.

https://github.com/WordPress/gutenberg/assets/846565/5d4492a8-7c96-41eb-a539-15bf07821d64

I'm not sure how I feel about the reduced prominence in practise, and there's another drawback – theme templates only have a single action which makes the dropdown feel superfluous:

Screenshot 2023-09-19 at 15 06 46

**Comment by jasmussen** [comment]
Appreciate the effort. I personally think it's too early still to remove the edit button, or to put it in the menu.

**Comment by jameskoster** [comment]
Yeah, we're running out of options...

Overall I think I prefer the text button. The scalability issues can potentially be reduced by using the `small` variant, and reducing the size of the panel title a little. I'll try that later.

**Comment by richtabor** [comment]
What about the smaller edit icon? Without the __ under the pencil, perhaps it's less "Edit title".

**Comment by jameskoster** [comment]
Smaller text button:

Screenshot 2023-09-19 at 17 00 45

The alignment is a bit strange due to the funky metrics within this panel. I don't love it.

> What about the smaller edit icon? Without the __ under the pencil, perhaps it's less "Edit title".

I suspect that will produce the same vibe but please feel free to try/commit. Though I noticed that small pencil isn't published, so we'll need to add it. It seems `pencil` and `edit` are identical, so perhaps update `pencil`?

**Pull request closed without merging**
