### PR TITLE
Deprecate the withGlobalEvents HoC

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

With #26737, #26740, #26742 and #26743, all uses in Gutenberg of `withGlobalEvents` have been removed.

* The HoC is not so useful anymore in the age of hooks. With useEffect, it very easy to remove listeners.
* It's only for window events, there's no HoC for global document events.
* When we start using iframes, it shouldn't be assumed which window the handler should be added to.

I don't think it makes much sense to keep this component around.

To do: remove the doc block from the module read me. @nosolosw @youknowriad I'm not sure how this has been handled in the past? How do we mark components as deprecated so the doc builder doesn't include it in the module read me file?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
>  How do we mark components as deprecated so the doc builder doesn't include it in the module read me file?

Why not just remove the file?

**Comment by ellatrix** [comment]
@youknowriad It's not a file, it's the doc block. As long as the HoC is exported, the doc builder will put it in the documentation (if there's no doc block, it will still mention the HoC). So it seems we need a way to tell the doc builder that an export is deprecated. Cc @nosolosw.

**Comment by nosolosw** [comment]
:wave: We can use the `@deprecate` [JSDoc tag](https://jsdoc.app/tags-deprecated.html)! Don't know the specifics of this, but we can add to the JSDoc something like `@deprecated since version. Some explanation goes here.` and it'll be added to the generated docs.

This was modeled after the WordPress docs ([example](https://developer.wordpress.org/reference/functions/is_taxonomy/)) and we have a couple of uses already ([example](https://developer.wordpress.org/block-editor/packages/packages-core-data/#hasUploadPermissions)).

**Comment by ellatrix** [comment]
> and it'll be added to the generated docs

Should deprecated APIs be added to the docs, or be removed? I think they should be removed, or at least from the main page.

**Comment by nosolosw** [comment]
I lean towards maintaining them, as the WordPress PHP docs does. There may be legit reasons why someone has to use a deprecated function: for example, if that code needs to support older versions of the Gutenberg plugin that don't have the new function, etc.

**Comment by ellatrix** [comment]
Here's the solution I went for:

* In order to make the tests pass (without altering them or removing them), I wrapped the HoC in another function to call the `deprecated` function that logs a message in the console. The original HoC will be used for the tests and the wrapped HoC will be exported by the module. The test could arguably be removed, but I'm against removing tests and docs for APIs of which the code is not removed from the code base as well.
* I added `@deprecated` to both functions. Since the exported function is a wrapped function without documentation, the doc builder also removes the documentation from the main page, which is a good thing. It only mentions the HoC by name and that it is deprecated.

I'm happy with this solution. An improvement that could be made is to instruct the doc builder to omit any mention of a function entirely if `@deprecated` is added.

**Comment by ellatrix** [comment]
@nosolosw Ah, I missed your comment. I'm not opposed to keeping the documentation, but I feel like it should be removed from the main page. A separate page with deprecated functions could be linked to at the bottom perhaps. Also, some stuff is just not useful anymore, even for supporting older WordPress versions. This HoC, for example, is not needed for that.

**Comment by nosolosw** [comment]
Would it be sensible to communicate to consumers of this API since which version this was deprecated and what is the current alternative?

**Comment by ellatrix** [comment]
Sure. I've not seen a version number being added lately when APIs are deprecated. It's also not clear wether it should be the Gutenberg plugin version or WordPress version. I think most APIs that are deprecated these days are not expected to be actually removed in the future?

Some examples in the plugin right now (no version was provided):

https://github.com/WordPress/gutenberg/pull/26509/files

https://github.com/WordPress/gutenberg/pull/19299/files

**Comment by nosolosw** [comment]
I've only found one case where the `@deprecated`tag is being used properly: [hasUploadPermission selector](https://developer.wordpress.org/block-editor/packages/packages-core-data/#hasUploadPermissions). It looks like we need to build some expectations as how to manage deprecations in the docs :(

The one thing I'm not really sure about is what's the version we should list there. This being a plugin that has its own users and publishing schedule but that, eventually, ends up in core makes things more difficult to reason about. Is there any place where we can draw inspiration from? My hunch is that adding both the plugin and the core version would be safer.

**Comment by ellatrix** [comment]
Yes, I think we should have a place for both versions and make them mandatory for this plugin with a lint rule?

**Pull request merged**
