### PR TITLE
Template Parts: Support REST API meta queries.

### PR DESCRIPTION
**Pull request by epiqueras**
## Description

Template Part blocks rely on meta queries, but the REST API does not support them by default. So, they break down when they look for `wp_template_part`s, and the other query arguments don't narrow it down enough to find the correct post on the first page of results.

## How to test this?

Verify that inserting template parts works as expected even when you already have a lot of customized template parts.

## Types of Changes

*Bug Fix:* Template Parts now load correctly when you have a lot of `wp_template_part` posts.

## Checklist:

- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by TimothyBJacobs — CHANGES_REQUESTED** [review]
This should be handled by properly registering a collection query parameter using `rest_wp_template_collection_params` and checking for that value in `rest_wp_template_part_query` and formatting the meta_query based on the specific parameter value.

For instance, add a `theme` parameter with a `type` of `string`.

We can't blindly open the posts collection to performing arbitrary meta queries.

**Comment by epiqueras** [comment]
>This should be handled by properly registering a collection query parameter

What does `rest_wp_template_collection_params` do if this still works without it?

>We can't blindly open the posts collection to performing arbitrary meta queries.

What are the things that could go wrong?

**Comment by TimothyBJacobs** [comment]
It registers it as a query parameter so that validation can occur and it is documented in the schema for the resource. That is how the REST API is designed to function. This style is more akin to the legacy `filter` parameter supported by the REST API which was removed.

Meta query parameters are not a public query parameter, see `WP::$public_query_vars` so they should not be allowed to be publicly queried. Exposing it would make it possible to determine the private metadata of a post.

**Comment by TimothyBJacobs** [comment]
> I've updated the code.

Looks good to me, I'd suggest a small change to make sure we don't stomp on anyone else providing a meta query.

```php
function filter_rest_wp_template_part_query( $args, $request ) {
	if ( $request['theme'] ) {
		$meta_query   = isset( $args['meta_query'] ) ? $args['meta_query'] : array();
		$meta_query[] = array(
			'key'   => 'theme',
			'value' => $request['theme'],
		);

		$args['meta_query'] = $meta_query;
	}

	return $args;
}
```

> But it still lets unregistered parameters pass through, right? Because it worked without registering it.

Correct, we don't error on unknown parameters.

**Comment by epiqueras** [comment]
@TimothyBJacobs Done 😄

**Review by TimothyBJacobs — APPROVED** [review]
lgtm!

**Comment by epiqueras** [comment]
Thanks for the quick reviews!

**Pull request merged**
