### PR TITLE
I18n: Use consistent string: 'Link rel'

### PR DESCRIPTION
**Pull request by Soean**
## Description
The label of the link relationship attribute should be consistent `Link rel` to match core and other parts of Gutenberg, so we don't need to translate it twice.

Bildschirmfoto 2020-02-13 um 14 19 16

I opened an issue to discuss changing this label to `Link Relationship` or something else and add a help text. See #20208

### CODE REVIEW

**Comment by michelleweber** [comment]
"Link Relationship" sounds good, and I like the idea of help text.

**Comment by Mamaduka** [comment]
Looking and the current code base, I think `Link rel` is more widely used, and there's only a single place with the `Link Rel` label. It might be better to change the latter for consistency.

https://github.com/WordPress/gutenberg/blob/7829913ae117dfb561d14c600eea7b281afd6556/packages/block-editor/src/components/url-popover/image-url-input-ui.js#L223-L227

**Comment by Soean** [comment]
@Mamaduka Thanks for the feedback, I updated the PR.

**Review by Mamaduka — APPROVED** [review]
Thanks for the follow-up, @Soean!

**Pull request merged**
