### PR TITLE
Remove preferred style variations legacy support

### PR DESCRIPTION
**Pull request by youknowriad**
Related #52632 

## What?

In #34522 we removed the "preferred style variations" feature from Gutenberg but we kept it around for users that had switched the default variation for some blocks. The problem though is that it is not being applied consistently, for example, it's applied in the post editor but not the site editor or widgets editor..., so the value of that fallback is actually not great.

This PR just goes ahead and removes it entirely. It keeps the action around with a deprecated message but from now on, the default variation is the default one specified by Core for everyone.

We may one to have something like it in the future but it will be global styles based instead of a preference.

## Testing Instructions

Nothing really to test here.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Smoke tested editors and blocks with style variations. 

Can't see any regressions.

Thanks for cleaning up.

**Comment by youknowriad** [comment]
I forgot the props, sorry about that :)

**Comment by aristath** [comment]
I have a question regarding this...
We removed them, and the plan always was to re-implement them. However, that never happened... Are you now saying that there are no plans to implement this again - in which case, developers should add a custom interface to do these things?

**Comment by youknowriad** [comment]
All what I'm saying in this PR is that the legacy support we kept was broken (not consistent) and I removed it from the code.

I don't know much about future plans. From my own perspective, future plans would probably include marking variations as preferred on the global styles level, so not a preference which means it might work differently.

**Comment by creativecoder** [comment]
Note that as part of curating the Gutenberg 17.8 changelog, I added the label [[Feature] Style Variations](https://github.com/WordPress/gutenberg/labels/%5BFeature%5D%20Style%20Variations) to this PR to better categorize it.

Please let me know if there is a different label that would be a better fit.

**Pull request merged**
