### PR TITLE
Added optional 'description' prop to inspector controls

### PR DESCRIPTION
**Pull request by paulwilde**
This adds an optional prop to all inspector controls to add description text below. Useful for help text.

screen shot 2017-06-28 at 21 20 45

### CODE REVIEW

**Comment by swissspidy** [comment]
cc @afercia for a11y feedback

**Comment by afercia** [comment]
For all the controls, except "radio", I'd consider to associate the description to the form element with an `aria-describedby` attribute. This way, the description would be read out automatically when the form element gets focused.

I'd consider to don't use italic text (I think I've mentioned this also in another issue for the few cases where it's used in Gutenberg) as it's not a consistent convention across WordPress and makes readability harder for some users.

The description paragraph is a flex-item, not sure if it needs `display: block`. When the description is very short, it doesn't go in a new line because of flexbox. We should make sure it wraps in a new line: should probably have a 100% width:

screen shot 2017-06-29 at 00 23 53

**Comment by gziolo** [comment]
@paulwilde, this PR needs rebase and some small tweaks. It looks like a nice improvement, so it would be nice to land it into master :)

**Review by gziolo — CHANGES_REQUESTED** [review]
Marking that it requires a rebase to continue.

**Comment by gziolo** [comment]
I'm closing this one because it seems to be abandoned. Feel free to update the code to work with the current codebase and reopen. Thanks for spending your time working on this PR.

**Pull request closed without merging**
