### PR TITLE
Inserter: fix line to show again

### LINKED ISSUE #21475: Inserter: Always show blue line
In previous versions, a blue line would appear in the block list, where the block itself would be inserted:

blue line before

This regressed recently, and that blue line is no longer available:

blue line

Let's both fix this, and revisit it. We should try showing this blue line _as soon as you open the inserter_. I.e. this:

Screenshot 2020-04-08 at 09 48 07

So, not just on hovering a block in the inserter, but just by virtue of it being open.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #21475.

Screenshot 2020-07-20 at 17 35 37

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for working on this!

In this branch, as I hover a block in the block library, I'm getting a full on crash with the following error message:

```
TypeError: Cannot read property 'offsetWidth' of null
    at InsertionPoint (http://localhost:8889/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=edf4ad2a28fcfd574858720b31223716:14588:30)
    at renderWithHooks (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:15246:18)
    at updateFunctionComponent (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:17063:20)
    at beginWork$1 (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:18636:16)
    at HTMLUnknownElement.callCallback (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:341:14)
    at Object.invokeGuardedCallbackDev (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:391:16)
    at invokeGuardedCallback (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:448:31)
    at beginWork$$1 (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:23355:7)
    at performUnitOfWork (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22346:12)
    at workLoopSync (http://localhost:8889/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22323:22)
```

I'm not sure it's related, but it _might_ be related to https://github.com/WordPress/gutenberg/issues/20713, which is pending a fix.

By the way the blue line that shows up should look identical to the one that appears when you drag an image from the desktop:

should look

It may already do that, I haven't been able to verify :D but just noting!

**Comment by jasmussen** [comment]
Thanks so much for working on this. I'm still getting that same React error when hovering a block as I mentioned in https://github.com/WordPress/gutenberg/pull/20792#issuecomment-598049165. Not sure if I did it wrong, but I had to check out using `git checkout --track origin/fix/inserter-line`. 

By the way can you make it so that the line is visible as soon as you open the top left inserter? Not just on block hover, but all the time when it's open?

**Comment by ellatrix** [comment]
I've been trying to fix this problem but I get stuck with `getBlockInsertionPoint()` constantly returning different values:

Screenshot 2020-04-15 at 13 19 11

This value just  changes all the time when hovering around in the inserter... Also not sure why blocks are being reset and if that's maybe the cause.

**Comment by ellatrix** [comment]
AH, I just realised there's logging because there's a preview creating another block list with its own insertion point etc.

**Pull request merged**
