### PR TITLE
PHPCS: Color Output & Show Progress

### PR DESCRIPTION
**Pull request by ahmadawais**
I like the colored output for PHPCS. Helps with the readability. As well as the progress! 
Also, this helps to keep the arguments list downsized to just what's needed.

### CODE REVIEW

**Comment by westonruter** [comment]
I usually don't include color or progress by default for the sake of other command-line tools that may invoke `phpcs` and not want those options enabled. This may be a bug in PHPCS, but you can't disable colors with `--no-colors` after being invoked with `--colors`. Likewise, if a command-line tool is wanting to do a quick list of the errors with something like `phpcs --report-emacs | wc -l` then the `-p` progress flag will cause problems here, and you have to modify your script to then add `-q` to suppress the progress and verbosity (which does actually work, in contrast to colors).

**Comment by ahmadawais** [comment]
@westonruter That makes sense! Feel free to close it then.

**Comment by nylen** [comment]
IMO: `phpcs` itself should do this automatically when stdout is a terminal.

**Comment by ntwb** [comment]
I've just opened #1753 that will allow you to create your own "local" `phpcs.xml` to add the `colors`  option to your own custom local config.

Note: If you choose to maintain your own custom local `phpcs.xml` config file you need to regularly check for updates in the upstream `phpcs.xml.dist` file and update your own `phpcs.xml` file as needed

**Comment by ahmadawais** [comment]
@ntwb That works!

**Pull request closed without merging**
