### PR TITLE
Blocks: Fix scrolling to the image block on Insert

### LINKED ISSUE #1048: Jumping to newly inserted block is broken for images
Select a block area further down in the layout.
Scroll further up the page.
Click to insert a new block.
(New wanted action) The page jumps to where I have inserted the new block. Showing me what I have inserted.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1048 

**Testing instructions**

 - Try inserting a new image block
 - The page should scroll to the newly inserted image

### CODE REVIEW

**Comment by BE-Webdesign** [comment]
Is there a way to make this work with the Gallery block as well?

**Comment by BE-Webdesign** [comment]
This works well for the Image block as far as I can tell. Trying to grasp everything in the code at the moment, before I can make a review.

**Comment by youknowriad** [comment]
Actually, the only change is this callback https://github.com/WordPress/gutenberg/pull/1139/files#diff-6a88cecedc3146f08ea0ce69918d2c3bR34

The diff is big due to the edit being moved its own file.

**Comment by youknowriad** [comment]
Gallery block scrolling fixed too :)

**Comment by aduth** [comment]
I believe the cause of the issue occurs here, when the `MediaUploadButton`'s `componentDidMount` opens the media modal:

https://github.com/WordPress/gutenberg/blob/c521550/blocks/media-upload-button/index.js#L30-L32
https://github.com/WordPress/wordpress-develop/blob/21e3c92/src/wp-includes/js/media/views/modal.js#L126

I found that simply wrapping the `MediaUploadButton`'s `this.frame.open()` in a `setTimeout` was enough for scrolling to behave correctly.

Do you think this might be simpler than delegating responsibility to each block with an auto-open media upload button to set the timeout and invoke the focus?

**Comment by youknowriad** [comment]
@aduth Mmm great! that sounds way better to me :)

**Comment by youknowriad** [comment]
@aduth Tried it and we do notice the scrolling happening before the modal being opened but I think it's still worth since it's a one liner fix. What do you think? I'm opening an alternative PR

**Pull request closed without merging**
