### PR TITLE
Try improving block variation placeholders 

### PR DESCRIPTION
**Pull request by richtabor**
WIP. 

### Before

CleanShot 2024-02-05 at 12 59 12

### After

CleanShot 2024-02-05 at 12 57 00

### CODE REVIEW

**Comment by jasmussen** [comment]
Can we do [this](https://www.figma.com/file/46qRP607dtqHGEosEaWWhY/Product-Design-(Previously-6.4-Design)?type=design&node-id=1430%3A560&mode=design&t=CsRvry93RqllrDZk-1)?

columns block like group

The fact that the description in the Group block is left aligned is actually a regression, it was initially designed to be centered. Any effort to reduce the footprint of the container blocks, so they work in more constrained contexts, is valuable. But I think we can take this one a step further. What do you think?

**Comment by hanneslsm** [comment]
>The fact that the description in the Group block is left aligned is actually a regression, it was initially designed to be centered. Any effort to reduce the footprint of the container blocks, so they work in more constrained contexts, is valuable. But I think we can take this one a step further. What do you think?

I think Rich's design is more consistent with other placeholders, like template parts. Or do you want to differentiate Group & Column on purpose from the others?

image


I know it's still a try, but I kinda like the percentage numbers of the columns. Makes it clearer that those are predefined values, not like a row block.

**Comment by jasmussen** [comment]
My argument would be to also update the template part and query loop blocks.

**Comment by jarekmorawski** [comment]
This is an interesting conversation and an important improvement to the overall site editing UX. In addition to improving consistency, can we use this opportunity to expand the variety of block states in the core editor? While working on the Product Collection block, I encountered many situations that required additional input states that did not exist yet.

From a purely visual POV, it'd be fantastic to align on:

- **Block name** -> Do we want to always show it in the placeholder? The Columns block has it, but the new Group block doesn't. I'd vote no because the block name is available in the toolbar and in the Inspector.
- **Vertical alignment** -> Do we want to always align elements to the left? When the content is more visual, like when we're presenting starting layouts in the Group block, I think it makes sense to use center alignment because it improves the visual rhythm. It also works for simpler layouts with just text and buttons.
- **Button weight** -> Do we want placeholder block CTAs to use the primary button style? Personally, I believe it should be reserved for the Publish or Save button in the top bar. A combination of `Outline` and `Text` may work just as well without drawing the attention away from the editor's main CTA.

Moving on to the states, here are the designs I used for the Product Collection block. I abstracted them to let us focus on the fundamental building blocks, layout, and composition. I also included error states because they're becoming increasingly more important thanks to powerful new features like Connections.

### Grid

In the Product Collection block, we use this state to let people easily pick the collection type or change it if the selected one is not available in the currently edited template. In core, it could be used for the Group and Column blocks as well as many others. I imagine that the author could decide whether to show the button labels. The grid item is the same component we use in the block inserter.

image

### Choice

This pattern could be used to ask the user to choose between two options. In Query Loop, it'd let users select a pattern or start blank. Ideally, authors will be able to assign different interfaces to each button, like modals, dropdowns, media pickers, redirects, etc. In the Product Collection block, we'd let merchants choose a specific collection type or start with a custom one.

image

### Search

This option could be used for managing missing context. For instance, if someone links a block to a custom field that was deleted or when the block referred to a Woo product that was unpublished. We'd display a search bar and let users quickly link the block to another asset without going through the whole connection flow again.

image

In the error state, we'll likely need to highlight the missing context in the List View, too. We'd show a small notification dot and replace the affected block's icon with the `warning` icon.

List View

**Comment by jasmussen** [comment]
Nice work Jarek. I especially think that there's some potential to explore the unread dot in the list view, though what constitutes a block in an error state can probably be looked at separately too. That said, it still feels like quite a lot of text, what happens when placeholders are as small as this?

Screenshot 2024-02-18 at 09 13 57

To be fair, that isn't handled too well with the group pattern yet either:

Screenshot 2024-02-18 at 09 15 06

I'd even go so far as to say that it is rare that the block you are suggesting will be inserted in such a narrow context.

However we cannot prevent that from happening, so it is nevertheless a case that needs to be considered.

I personally believe the answer lies somewhere along the lines of [this visual](https://github.com/WordPress/gutenberg/pull/58685#issuecomment-1929189330), which also answers some of your questions; reduce as much as possible. As few actions as possible, label-less if at all possible. This is the unique challenge at hand, balancing the shortcuts with the scalability. The shortcuts are valid, but once icons, descriptions, secondary actions get added to it, to me it diverges too far from the learnings we've made so far, namely that this placeholder state simply does not scale to support a lot of content.

Do you have a version of the mockups that include real shortcuts rather than the example "block actions"?

**Comment by richtabor** [comment]
Closing as we pushed https://github.com/WordPress/gutenberg/pull/59275 forward instead.

**Pull request closed without merging**
