### PR TITLE
Inspector Controls: resort the order of the design tools associated with styles hooks

### PR DESCRIPTION
**Pull request by ramonjd**
Related to https://github.com/WordPress/gutenberg/issues/35541

## Description

This change attempts to sorts the order of block inspector controls according to the following pattern:

1. Layout
2. Color
3. Typography
4. Dimensions
5. Border
6. Advanced

We're dealing with SlotFills, so, like making Bearnaise sauce, the order of execution matters. 

The styles supports – Color, Typography and Border components – [may be reordered.](https://github.com/WordPress/gutenberg/blob/c1b9bbd1984742000e86eabaa8f92a833fdbd816/packages/block-editor/src/hooks/style.js#L267)

The [Dimensions Inspector Controls Group however is rendered as the penultimate SlotFill](https://github.com/WordPress/gutenberg/blob/c1b9bbd1984742000e86eabaa8f92a833fdbd816/packages/block-editor/src/components/block-inspector/index.js#L132), before the Advanced Controls Group.

The consequence is the order is rendered so:

1. Layout
2. Color
3. Typography
4. Border
5. Dimensions
6. Advanced

More excitingly, the reason Layout is currently rendered at the top of the list is [because it's imported after style here](https://github.com/WordPress/gutenberg/blob/69e348ec80dc2cb9d537a8ba3cf6774b48636461/packages/block-editor/src/hooks/index.js#L15).  Last in first out. Moving `import './style';` to the bottom of the import causes the styles supports to be rendered first in the SlotFill.

Anyway, I've left the minor changes to styles as a preliminary PR for now to get us close, but for greater control over order, I think we'll need an immediate followup PR to further explore the use of Inspector Controls groups (introduced in https://github.com/WordPress/gutenberg/pull/34069).

For example, whether we need to create more groups, as queried by @gziolo in https://github.com/WordPress/gutenberg/pull/34069:

```jsx
<InspectorControls.Slot
    __experimentalGroup="layout"
    bubblesVirtually={ bubblesVirtually }
    label={ __( 'Layout' ) }
/>
<InspectorControls.Slot
    __experimentalGroup="dimensions"
    bubblesVirtually={ bubblesVirtually }
    label={ __( 'Dimensions' ) }
/>
<InspectorControls.Slot
    bubblesVirtually={ bubblesVirtually }
    label={ __( 'Border' ) }
/>
```

Or something to that effect. :)

Thank you!

## How has this been tested?

Ensure that you've enabled all block supports in your `theme.json`, i.e., `settings[color|typography|spacing|border]`. 

Next, activate support for a block in its block.json. The Group Block is fine block with which to test. 

Here's how my `supports` object for `group/block.json` looks:

```json
	"supports": {
		"align": [ "wide", "full" ],
		"anchor": true,
		"html": true,
		"color": {
			"gradients": true,
			"background": true,
			"link": true
		},
		"spacing": {
			"padding": true,
			"margin": true,
			"__experimentalDefaultControls": {
				"padding": true
			}
		},
		"typography": {
			"fontSize": true,
			"lineHeight": true,
			"__experimentalFontWeight": true
		},
		"__experimentalBorder": {
			"color": true,
			"radius": true,
			"style": true,
			"width": true
		},
		"__experimentalLayout": true
	},
```

Fire up the Block Editor and insert a Group Block. Select the Group Block and observe the order of the Inspector Controls.

| Before | After |
| ------------- | ------------- |
| Screen Shot 2021-10-13 at 12 13 37 pm  | Screen Shot 2021-10-13 at 2 42 25 pm  |

## Types of changes
Order change in the rendering of style supports components.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
Thanks for getting this started @ramonjd 👍 

The grouped inspector controls slots will add a bit of a wrinkle to this as you mentioned. It might be handy to know that I'm [creating these new inspector control groups](https://github.com/WordPress/gutenberg/pull/33744/files#diff-068538657061c47f0a58cfc331259bbeabe11bcc0c576a0cc496d262e5b0038cR131) as part of switching the block support panels to use the `ToolsPanel`.

These new groups/panels were being approached one at a time, [typography](https://github.com/WordPress/gutenberg/pull/33744), [color](https://github.com/WordPress/gutenberg/pull/34027), then [border](https://github.com/WordPress/gutenberg/pull/33743). I'm not sure there is a quicker or more efficient means of adopting the new groups/approach.

Obviously, this can be landed to get us one step closer if there is a hurry to improve it. Otherwise, we could address it incrementally, ensuring the panel switch PRs match the proposed order.

**Comment by ramonjd** [comment]
> It might be handy to know that I'm creating these new inspector control groups as part of switching the block support panels to use the ToolsPanel.

Very handy, thank you! And thanks for linking to each of the group PRs.

> Obviously, this can be landed to get us one step closer if there is a hurry to improve it. Otherwise, we could address it incrementally, ensuring the panel switch PRs match the proposed order.

I suppose it wouldn't hurt to merge this one and wait until the new groups flow in if folks agree.

**Review by aaronrobertshaw — APPROVED** [review]
LGTM 👍 

I've tested this by opting into all the block supports for a single block and checking the order within the inspector controls is as advertised.

This should be fine to merge as mentioned. It might be best though to keep the original issue open until the PRs switching the block support panels to the `ToolsPanel` and new inspector controls slots are merged.

**Comment by ramonjd** [comment]
> I've tested this by opting into all the block supports for a single block and checking the order within the inspector controls is as advertised.

Thanks for the test and review!

> This should be fine to merge as mentioned. It might be best though to keep the original issue open until the PRs switching the block support panels to the ToolsPanel and new inspector controls slots are merged.

Good point. I'll remove the Resolves keyword from the description.

**Pull request merged**
