### PR TITLE
Migrate new-post to Playwright

### PR DESCRIPTION
**Pull request by kevin940726**
## What?

Based on #38570, part of #38851. Migrate [`new-post.test.js`](https://github.com/WordPress/gutenberg/blob/add/playwright-new-post/packages/e2e-tests/specs/editor/various/new-post.test.js) to its Playwright counterpart.

## Why?

See #38570 for its background and rationale.

This is split into a new PR for easier review.

## How?

See #38570 for the proposed migration steps.

## Testing Instructions

```sh
npm run test-e2e:playwright
```

### CODE REVIEW

**Comment by glendaviesnz** [comment]
I get the following errors when I run this locally:

```
TypeError: pageUtils.createNewPost is not a function

      21 |              pageUtils,
      22 |      } ) => {
    > 23 |              await pageUtils.createNewPost();
         |                              ^
      24 |
      25 |              await expect( page ).toHaveURL( /post-new.php/ );
      26 |
```
and 
```
  2) [chromium] › editor/various/new-post.spec.js:43:2 › new editor state › should have no history =

    page.evaluate: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

**Comment by kevin940726** [comment]
> ```
> TypeError: pageUtils.createNewPost is not a function
> ```

Have you run `npm run dev` or `npm run build` before running the tests? We need this step now to transpile the utils from TypeScript to JavaScript 😅 .

> ```
> page.evaluate: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
> ```

Hmm, I can't reproduce this 🤔. Is there any more info? Perhaps you can run `npm run test-e2e:playwright -- --debug` or `npm run test-e2e:playwright -- --headed` to see if it works in headed mode.

**Comment by glendaviesnz** [comment]
Thanks, `npm run build` fixed it.

Now it is just failing with:
```
  page.waitForSelector: Timeout 10000ms exceeded.
    =========================== logs ===========================
    waiting for selector "role=button[name="Dismiss this notice"] >> text=Draft saved" to be visible
```

For me when running headed the Saved snackbar text shows as just  `Saved`, not `Draft saved`

**Review by glendaviesnz — APPROVED** [review]
LGTM - all tests passed locally

**Pull request merged**
