### PR TITLE
Site Editor: Fix item color and padding in navigation panel

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
https://github.com/WordPress/gutenberg/pull/27003 introduced a few styling changes which broke the color in the navigation panel. Also introduced some inconsistencies in padding.

## Screenshots
Before (`master`) Notice missing template below Front Page
image

After (this branch)
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ x I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Copons** [comment]
There's another inconsistency (might be unrelated to the change, but it's worth fixing it here anyway):

`TemplateNavigationItem`'s buttons are misaligned compared to vanilla `NavigationItem`.
It's noticeable in the "after" screenshot, where the template items' left padding is slightly narrower than the menu items'. 

The reason is that [in the vanilla item](https://github.com/WordPress/gutenberg/blob/ec3da35657c692ccd3379eb51466b413a8dc356f/packages/components/src/navigation/styles/navigation-styles.js#L185), the button has:
`padding: ${ space( 0.75 ) } ${ space( 2 ) };`
which converts into
`padding: 6px 16px;`

Whereas [the custom template item](https://github.com/WordPress/gutenberg/blob/ec3da35657c692ccd3379eb51466b413a8dc356f/packages/edit-site/src/components/navigation-sidebar/navigation-panel/style.scss#L98-L99) has:
`padding-top: $grid-unit-10; padding-bottom: $grid-unit-10;` (inheriting the horizontal padding from `.components-button`)
which converts into
`padding: 8px 12px`

The vanilla `.components-button` has `padding: 6px 12px` (which is consistent with G2), so I think we only need to fix [the style for the custom template item](https://github.com/WordPress/gutenberg/blob/52fbaec4c32c1a58a78e7b9bd57eb635e5fa6a39/packages/edit-site/src/components/navigation-sidebar/navigation-panel/style.scss#L98-L99) like this:
```diff
- padding-top: $grid-unit-10;
- padding-bottom: $grid-unit-10;
+ padding-left: $grid-unit-20;
+ padding-right: $grid-unit-20;
```

**Comment by david-szabo97** [comment]
Nice one! You really got eyes for this 😄 Pushed a commit and updated the "after" image. Thanks!

**Comment by david-szabo97** [comment]
The test is failing because of package-lock being outdated.

**Review by Copons — APPROVED** [review]
Thank you for taking care of this! 🙇‍♂️

**Pull request merged**
