### PR TITLE
Update Button block wording

### LINKED ISSUE #13923: Description for Gutenberg button to include the word "link"
The current description for a Button Gutenberg block element is as such:

> Prompt visitors to take action with a custom button.

As the element inserted is not actually a <button> element but an <a> could we amend the wording to something like:

> Prompt visitors to take action with a button styled link.

Just so it is clear it is a link that just happens to look like a button.

### PR DESCRIPTION
**Pull request by samikeijonen**
## Description
 - Update button block description to mention it's a link.
- Add keyword _link_.

Closes #13923.

## How has this been tested?
Tested on local, I see the wording change. And I can also search using keyword _link_.

## Screenshots 
Button description:
Button block description

Search by keyword link:
Search modal with keyword link

## Types of changes
- Button block description wording.
- Add keyword.

## Checklist:
- [ x] My code is tested.
- [x ] My code follows the WordPress code style. 
- [ x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Code wise, it looks good. I would prefer to wait until someone will confirm that it is indeed the change for the description that it's expected before we proceed with merge.

**Comment by michelleweber** [comment]
A separate small thing that needs updated -- it should be "button-style." Without the dash it's a confusing phrase, and "button-style" is a bit clearer than "styled" (even though "styled" is entirely accurate).

**Comment by gziolo** [comment]
"button-style" it is 👍

**Comment by gziolo** [comment]
@samikeijonen thanks for your another contribution 🎉

**Comment by samikeijonen** [comment]
Thanks @michelleweber and @gziolo!

**Pull request merged**
