### PR TITLE
Remove the subheading block

### PR DESCRIPTION
**Pull request by youknowriad**
In a galaxy far far away, sometimes like more than three years ago, Gutenberg used to have a block called "Subheading", this block doesn't exist anymore, or more exactly, this block is deprecated and hidden, so users are not allowed to use it. This block never made its way into WP as stable, it was kept hidden since then.

This PR tries to remove that block because:

 - It was never stable in WordPress, there's no need to keep it around forever and maintain it as the APIs evolve.
 - Existing markup using the block will continue to work properly, it's just a paragraph. The block is  supposed to be italic a bit bigger than regular paragraphs but the visual change is not drastic with the removed styles, so I think it's fine enough
 - If a user tries to open the editor with a post using that block, he'd get

Capture d’écran 2021-03-08 à 3 54 09 PM

There's another block (text columns) in a similar situation, I wanted to start with this one first and we can see if it's  something we want to expand to other blocks (or other deprecated versions of blocks that were never merged in Core)

### CODE REVIEW

**Comment by jasmussen** [comment]
Oh yeah, it's time.

Could we potentially move it to the block directory, so sites that actually use it have an option to install it as a plugin?

**Comment by youknowriad** [comment]
I'm not sure it's worth adding to the block directory personally,  it's a lot of work (setup a repo, plugin, move the code...) and the block itself, doesn't really add much value.

**Comment by aristath** [comment]
Can't we add a deprecation and convert it to a paragraph, adding a `wp-block-subhead` extra class to it? That way if their theme was using some special CSS for it it will be OK

**Comment by youknowriad** [comment]
No, we can't add such deprecation, at least not at the moment since we don't support cross blocks deprecations.

**Review by mtias — APPROVED** [review]
Seems fine to remove

**Review by aristath — APPROVED** [review]

**Pull request merged**
