### PR TITLE
Interactivity API: Rename `data_wp_context` function

### PR DESCRIPTION
**Pull request by cbravobernal**
## What?

Update Core blocks to be compatible with the refactor done in Core.

https://github.com/WordPress/wordpress-develop/pull/6205

## Why?

Check ticket: https://core.trac.wordpress.org/ticket/60575

## Testing Instructions

Contexts should appear in Navigation and Search block.
These should work as expected.

### CODE REVIEW

**Comment by swissspidy** [comment]
Core change has been committed in https://core.trac.wordpress.org/changeset/57742

**Comment by cbravobernal** [comment]
The sooner we merge, the fewer fatal errors there will be in Gutenberg + WP trunk! 😆

**Review by DAreRodz — APPROVED** [review]
LGTM ✅

**Comment by gziolo** [comment]
@swissspidy, @youknowriad and @getdave, core blocks in WP core still use the old helper method which definitely breaks things. The best approach would be to publish npm packages with this commit and apply it WP core.

Alternatively, we can revert the commit, and try again next time we sync changes from Gutenberg.

**Comment by getdave** [comment]
> The best approach would be to publish npm packages with this commit and apply it WP core.

We'll be publishing packages again on Tuesday prior to RC 1. How critical is it that we do another package update for this one change?

**Comment by swissspidy** [comment]
@gziolo Right, of course! 🤦 Let me revert the core commit, that's the most straightforward way. Then we can introduce after the package update on Tuesday.

**Comment by c4rl0sbr4v0** [comment]
We need to revert Gutenberg one too.

**Comment by swissspidy** [comment]
Why the Gutenberg one? It has a compat copy in `lib/compat/wordpress-6.5/interactivity-api/interactivity-api.php`, no?

**Comment by cbravobernal** [comment]
True, we don't

**Comment by youknowriad** [comment]
I just cherry-picked this PR to the update/packages-6.5-rc1 branch to get it included in the next release.

**Comment by georgestephanis** [comment]
Is there a reason to not keep a copy of the old function in place with a `_doing_it_wrong ` invocation and then calling the up-to-date function name, so that third-party plugins and themes that relied on the legacy function name don't fatal as it's suddenly undefined?

We just hit an issue of this bricking a site when Gutenberg updated to 17.9 as the function wasn't defined.

**Pull request merged**
