### PR TITLE
Fix Post Date block escaping of date HTML

### PR DESCRIPTION
**Pull request by getdave**
## Description

In https://github.com/WordPress/gutenberg/pull/37876#issuecomment-1013307666 we learnt that we escaped a little too late on the Post date block. This cause the HTML itself to be escaped and thus output on the site as raw HTML. That isn't what we wanted.

This PR reverts that and puts the escaping as close to HTML output time as possible.

## How has this been tested?

- Activate TT2
- Add some Posts (I used Fakerpress to generate these).
- Find a Post listing page (probably the front page unless you changed the setting).
- See that the Post data is outputted as a hyperlink without any HTML being displayed.

### Before

Screen Shot 2022-01-17 at 09 23 54

### After
Screen Shot 2022-01-17 at 09 24 14

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by MaggieCabrera — APPROVED** [review]
I could reproduce this on Blockbase too and this fixes it, LGTM!

**Comment by getdave** [comment]
Test failure unrelated. Rerunning

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by getdave** [comment]
OK I _know_ that this test failure is not related to this PR so I'm going to merge anyway and then [look to fix the e2e test in another PR](https://github.com/WordPress/gutenberg/pull/38025).

**Pull request merged**
