### PR TITLE
components: Add normalizeArrowKey

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
Adds a new `normalizeArrowKey` utility required by TextInput

## How has this been tested?
Not sure how to test this effectively without testing the implementation details.

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [N/A] My code follows the accessibility standards. 
- [N/A] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ciampo** [comment]
> Not sure how to test this effectively without testing the implementation details.

Maybe creating a simple input element, adding this in the `onChange` listener, and leveraging React Testing library and the [`user-event` package?](https://github.com/testing-library/user-event#typeelement-text-options) to make sure that the return value is correct?

**Comment by ciampo** [comment]
> > Not sure how to test this effectively without testing the implementation details.
> 
> Maybe creating a simple input element, adding this in the `onChange` listener, and leveraging React Testing library and the [`user-event` package?](https://github.com/testing-library/user-event#typeelement-text-options) to make sure that the return value is correct?

Nevermind, I just realised that this is an issue with IE / Edge. Yeah I guess that the only way would be a few small unit tests:
- one creating a mock event object in the way that IE / Edge would, and checking that the output is normalised
- another one creating a mock event object like other browsers would, and making sure that the output stays the same (ie it didn't need normalisation)
- a last one creating an event object that is not related to arrow keys — and making sure that the output is the same as the input

**Comment by sarayourfriend** [comment]
Added tests, ready for review!

**Review by ciampo — APPROVED** [review]
LGTM! Thank you for adding the tests 🚀

**Pull request merged**
