### PR TITLE
deregister TOC block until issues are resolved

### PR DESCRIPTION
**Pull request by aristath**
## Description
This PR temporarily deregisters the TOC block.
It should be added back once these 2 tickets are resolved:
* https://github.com/WordPress/gutenberg/issues/29560
* https://github.com/WordPress/gutenberg/issues/29561

This 3rd issue would improve the experience, but not a blocker:
* https://github.com/WordPress/gutenberg/issues/29562

## How has this been tested?
Tested by making sure the TOC block is not available to users.

## Types of changes
Commented-out the lines that register the block.
Since this is only temporary, commenting-out seems appropriate.
The e2e fixtures were removed to make the tests pass.

cc @mtias 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mtias** [comment]
Thanks! I agree on the first two being blockers, but I think #29562 could come later.

**Comment by aristath** [comment]
> Thanks! I agree on the first two being blockers, but I think #29562 could come later.

Good point, thank you. Edited the description 👍

**Review by ockham — APPROVED** [review]
Thanks Ari! This is coming in handy for the 10.2.0 RC that I'm about to release :smile:

**Review by ZebulanStanphill — APPROVED** [review]
I'm already working on a refactor PR, so hopefully we should be able to reintroduce the block in Gutenberg 10.3. :+1:

**Comment by ZebulanStanphill** [comment]
Here's the refactor PR: #29739.

**Pull request merged**
