### PR TITLE
Update npx commands in create-block README.md

### PR DESCRIPTION
**Pull request by doughamlin**
## What?
Update npx commands to ensure latest version is used.

## Why?
I followed these directions and it used an old version, which resulted in various flags not working.

## How?
Update the readme

## Testing Instructions
N/A

### CODE REVIEW

**Comment by gziolo** [comment]
Thank you for the report. It looks like it was a bug on npm side: https://github.com/npm/cli/issues/2329. It's been fixed shortly after v7.19.0. There is also a following note in the comments:

> if you have a package globally installed, npx will find and use that before trying to install something else, and it will not automatically fetch the latest version in that case. 

So maybe an alternative would be adding a note to use `@latest` only with older npm versions and when an older version of the package is installed globally.

**Comment by doughamlin** [comment]
Is it a bug or the intended behavior of npx? Commenters in that ticket (as well as other discussions I referenced before opening this PR) don't seem to agree. Either way, it seems not ideal that someone can't copy/paste these commands and expect them to work.

For the record, I was using npx v8.1.0, and that ticket says the bug was fixed in v7.5.2. If I run `npm ls -g` I don't see create-block installed globally, so how would I know is installed? Yes, it is in the `~/.npm/_npx` folder, but who is rummaging through their cache folder? Even after running `npx @wordpress/create-block@latest`, if I run it without the `@latest` I still get the old cached version (2.9.0 published Jun 15, 2020!).

So, it seems anyone who comes back and tries to use a new flag with npx will face a similar result as me. A note to add `@latest` is certainly one way, but could easily be missed.

**Comment by gziolo** [comment]
In that case, it might be fine to include the `@latest` part to avoid all the issues mentioned.

@ryanwelcher, @juanmaguitar and @mburridge, do you agree? We might need to update more places for consistency or include a Troubleshooting section to use as a reference.

**Comment by mburridge** [comment]
I think I would prefer a note on the page to append `@latest` when necessary, rather than make it part of the example commands that should, in general, work.

**Review by juanmaguitar — APPROVED** [review]

**Comment by juanmaguitar** [comment]
@doughamlin Thanks for opening this PR. 
These changes LGTM and will help the developer experience for `create-block`

**Pull request merged**
