### PR TITLE
Layout: Skip outputting base layout rules that reference content or wide sizes if no layout sizes exist

### LINKED ISSUE #60413: 6.5: Maximum width of wide blocks inside group set to Alignment: Full is overwritten in classic themes
### Description

In classic themes in WordPress 6.5, the maximum width of `alignwide` blocks are overwritten when they're direct descendants of a group block set to the "Full" alignment.

Many classic themes built after the block content editor was introduced set the maximum width of `alignwide` blocks with CSS, like this:

```
.alignwide { max-width: 1200px; }
```

When running a classic theme without theme.json in WordPress 6.5 and including a wide block inside a full group, Core outputs the following CSS even though the `--wp--style--global--wide-size` variable is undefined:

```
body .is-layout-constrained > .alignwide {
    max-width: var(--wp--style--global--wide-size);
}
```

This results in the `alignwide` maximum width set by the theme CSS being overwritten by the undefined variable, breaking the layout. I've replicated this in Twenty Twenty and in two of my classic themes (Chaplin and Eksell).

### Expected behavior
The CSS above should not be output if `--wp--style--global--wide-size` is undefined. Given the high specificity of the CSS generated by Core, I'd expect this to affect many classic themes that set a maximum width for `alignwide` with CSS.

### Step-by-step reproduction instructions

1. Activate [Twenty Twenty](http://wordpress.org/themes/twentytwenty/).
2. Create a new post or page.
3. Insert a group set to the full alignment, and inside that group, insert a group set to the wide alignment. Give them different background colors for visibility. You can also copy the code included below.
4. The wide group will fill the parent `.wp-block-group__inner-container` div, instead of maxing out at the `120rem` maximum width set by the Twenty Twenty CSS. 
5. Check the inspector to see that the theme CSS setting a maximum width for `.alignwide` is overwritten by the CSS generated by Core, included above.

### Screenshots, screen recording, code snippet

| WordPress 6.5 | WordPress 6.4 |
|--------|--------|
| localhost_8888_utsikt_wide-inside-full_ (3) | localhost_8888_utsikt_wide-inside-full_ (4) | 

In the screenshots, the black group is set to full and the red is set to wide.

**Block markup**
```
<!-- wp:group {"align":"full","backgroundColor":"primary","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-primary-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Full group.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"align":"wide","backgroundColor":"accent","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-accent-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Wide group.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

### Environment info

WordPress 6.5
With or without Gutenberg active
Twenty Twenty 2.6

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Fixes #60413

If the global theme JSON settings for `settings.layout.contentSize` or `settings.layout.wideSize` aren't set, skip outputting base layout styles that reference the CSS variables for those values.

## Why?

As reported in #60413, when you add a wide block as a child of a Group block in a classic theme such as Twenty Twenty, then the layout support's constrained max-width styles wind up overriding the theme's styles for `.alignwide`. And since there are no content or wide size CSS variables available, this effectively results in wide size blocks being displayed as full width to their container.

With the approach in this PR, the output of the `max-width` rules that reference the CSS variables is skipped if there is no content or wide size value available, which should result in the bug being fixed for themes such as Twenty Twenty. Block themes that set content or wide size should be unaffected.

## How?

In the Theme JSON class, skip output of base style rules that reference either of the content/wide size CSS variables if there is no content or wide size value available.

## Testing Instructions

Activate Twenty Twenty theme and add the following test markup from #60413 to a post:

```html
<!-- wp:group {"align":"full","backgroundColor":"primary","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-primary-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Full group.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"align":"wide","backgroundColor":"accent","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-accent-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Wide group.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

Save and publish the post. On the site front end, prior to this PR, the wide group block will extend to the full width of its container. With this PR applied, its `max-width` should be that provided by the theme (in the case of Twenty Twenty, it's `120rem`).

To test against regressions, switch to a block theme and make sure that constrained layout works as expected in the post and site editors and on the site front end.

### Before

Note how the base layout rules are overriding rules:

image

### After

The base layout rules for max-width are no longer output:

image

### CODE REVIEW

**Comment by andrewserong** [comment]
Just switching this over to Draft — there are some tests to update, and we might also want to include the same logic in the site editor's JS version of global styles 🤔

**Review by tellthemachines — APPROVED** [review]
Thanks for the PR! This change LGTM as is (not taking into account the pending test updates of course 😅 )

I think adding this logic to the JS global styles output can be considered as a follow-up, because it's existing behaviour (the regression we need to fix was caused by the layout classnames changing places in classic themes only) and it doesn't seem to have caused problems in block themes so far, maybe because when the theme doesn't define content widths the wide/full align options aren't available to blocks. So let's try it by all means, but I think it's better to keep this fix small as it's meant to go into the next minor release.

**Comment by andrewserong** [comment]
>  So let's try it by all means, but I think it's better to keep this fix small as it's meant to go into the next minor release.

Good thinking! Agreed. Let's go for the small change in this PR for 6.5.1, and we can explore the JS changes separately if need be 👍

I'll proceed with updating the tests.

**Comment by andrewserong** [comment]
I've updated the tests, and I've started a draft backport PR in core over in: https://github.com/WordPress/wordpress-develop/pull/6362 — I ran out of time to finish that off today, but I'll continue on with it on Monday.

For now, I'll merge this PR in. Thanks again for the review!

**Comment by andrewserong** [comment]
Apologies everyone, I clicked merge too quickly and forgot to add in the `props` 🤦

Thanks again for the bug reports, triage, and reviews, everyone!

**Comment by ramonjd** [comment]
I just cherry-picked this PR to the release/18.1 branch to get it included in the next release: d639f38202

**Comment by creativecoder** [comment]
I manually cherry-picked this PR to the `update/fixes-for-wp-6-5-3` branch to get it included in the next release: https://github.com/WordPress/gutenberg/pull/61299/commits/7b3174467f7475188f1de837beeb55465d6bb3fa

**Comment by wolffe** [comment]
This update broke hundreds of websites.

I have this in my `:root` in all my classic themes:

```
--content_width: <?php echo get_option( 'content_width' ); ?>px;
--global--content-size: <?php echo get_option( 'content_width' ); ?>px;
--wp--style--global--content-size: <?php echo get_option( 'content_width' ); ?>px;
--global--wide-size: 1440px;
--wp--style--global--wide-size: 1440px;
```

I also have these in my `after_setup_theme` filter:

```
add_theme_support( 'align-wide' );
add_theme_support( 'responsive-embeds' );

add_theme_support( 'wp-block-styles' );
add_theme_support( 'custom-line-height' );
add_theme_support( 'custom-spacing' );
add_theme_support( 'block-templates' );
add_theme_support( 'appearance-tools' );

add_theme_support( 'dark-editor-style' );

add_theme_support( 'link-color' );
add_theme_support( 'border' );
```

How do I fix it? What rules do I need to add to my CSS stylesheet?

**Pull request merged**
