### PR TITLE
Input Interaction: fix buffer for the triggering of multi-select

### LINKED ISSUE #12322: Text selection with keyboard triggers blocks multi-selection unexpectedly
Tested on latest master 4.5.1.

Looks like selecting text with the keyboard works differently from selecting text with the mouse. At some point the blocks multi-selection kicks in and breaks the expected behavior.

Selecting text with Shift and Arrow keys is a pretty common expectation for all users, and it's also the only selection method for users who don't use the mouse.

In the GIF below, I'm following 3 steps:
- mouse: selection on 4 lines works as expected
- keyboard: as soon as the selection reaches the 4th line, multi-selection kicks in and doesn't allow to complete the selection as desired
- keyboard on a shorter text: a bit surprisingly, seems the previous incorrect behavior doesn't happen when the selection spans on a shorter text, e.g. only 3 lines

selection short

Additionally, if the selection happens on the last block there's one more breaking behavior. In the GIF below:
- if the selection is on the last 3 lines, I'm able to reach the last line in the text
- if I start from the fourth line from the bottom, I'm unable to reach the last line:

selection last

A similar behavior happens when starting the selection from bottom to top in the first block.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12322. 

Fixes the `buffer` for calculating whether, based on the text selection, multi-selection should be triggered or not. This buffer was originally added with only a collapsed selection in mind, so calculating the line height was a simple matter of taking the height of the selection rectangle.

Solution: use `getComputedStyle` to get the line height from the browser.

Why is this buffer needed in the first place? Depending on the browser, there may be a difference between the height of the selection rectangles and the line height. The selection rectangle may not reach all the way to the line edge. This is why we add a buffer that is the line height divided by two.

## How has this been tested?

See #12322. Put the caret at the start of a paragraph that is at least 4 lines long. Press `shift+arrowDown` and ensure multi-block selection only starts after the last line has been selected.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ellatrix** [comment]
I'll see if I can add a test case.

**Review by aduth — APPROVED** [review]
The implementation is consistent with what I would expect to be an improvement based on the hypothesis in https://github.com/WordPress/gutenberg/issues/12322#issuecomment-472576112 . The need for buffer I still find to be unfortunate, though would be happier to see an improvement than delay on it further.

The end-to-end test is great.

**Review by oandregal — APPROVED** [review]
Fixes the issue and the code is fine. Thanks for the e2e test!

**Comment by ellatrix** [comment]
Thanks for the reviews!

@aduth Yeah the buffer is unfortunate, though I see no better way to address the issue. :/

**Comment by aduth** [comment]
>@aduth Yeah the buffer is unfortunate, though I see no better way to address the issue. :/

Right, if I recall correctly, the issue is that the selection bounding box doesn't align neatly with the edges of the input it's in? I remember exploring this and finding it exceedingly difficult to measure that difference accurately, even going so far as to explore possible effects of various [text metrics](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics) characteristics.

**Pull request merged**
