### PR TITLE
Solved settings panel overflow-x issue in Firefox

### LINKED ISSUE #31165: Settings panel overflow-x scroll
This happens when the Gutenberg plugin is installed and updated I think I have seen this for more than a month.

You can see unnecessary overflow-x scroll when a settings panel toggle is opened.
Gutenberg settings panel scroll problem

To look further it happens when overflow-y has to scroll and in codes, it is here that make this problem:
Gutenberg settings panel scroll problem

This fixed size makes the problem so I solved it with this CSS snippet:
```
@media (min-width: 782px) {
     .interface-complementary-area {
          /* width: 280px; */
         width: 100%;
     }

     .is-sidebar-opened .interface-interface-skeleton__sidebar {
          width: 280px;
     }
}
```

To simplify, The fixed width should be set to its wrapper, not the child [.interface-complementary-area].

The result after that snippet:
solved

### PR DESCRIPTION
**Pull request by amir2mi**
Hi, everything is explained here : [#31165](https://github.com/WordPress/gutenberg/issues/31165)

### CODE REVIEW

**Review by vdwijngaert — APPROVED** [review]
I've tested this, and it does prevent the horizontal scrollbar when the Editor settings sidebar overflows in Firefox. As far as I can tell, these changes do not appear to cause any trouble elsewhere.

**Comment by amir2mi** [comment]
Oops, wrongly committed to this branch pull request, so I removed the last changes. [RTLize header icons]

**Comment by talldan** [comment]
Thanks for working on this @amir2mi. I was just checking why the tests failed. This change does seem to cause some issues in a couple of other block-based editors:
- Appearance > Widgets - the sidebar is now much bigger than normal
- Gutenberg > Navigation (beta) - (this screen has to be enabled in the plugin via the Gutenberg > Experiments page.) When accessing this editor the sidebar is smaller when a block is deselected, but then bigger when a block is selected. It should just be a fixed width (`$sidebar-width`). This also seems to be why the tests are failing—the save button in the editor can't be clicked when a block is selected.

**Comment by amir2mi** [comment]
@talldan I'll be happy if I could help.
Unfortunately, I forgot to check it in other playgrounds.

### Post:
Everything is fine.

### Widget & Navigation:
The problem is a class.
Basically, when the sidebar is opened, the parent in the post editor (`.edit-post-layout`) has a class called `.is-sidebar-opened` now in the widget & navigation area there is not and that's the reason for the mentioned problems.

Sidebar width should be conditional and this condition is based on the `.is-sidebar-opened` class.
I think it does not happen because the sidebar area does not have the `.edit-post-layout` wrapper.

### That is the result before and after that class:
Post:
https://user-images.githubusercontent.com/64708228/117295115-af041e00-ae88-11eb-801e-3861ad2c5e41.mp4


Widget:
https://user-images.githubusercontent.com/64708228/117295027-96940380-ae88-11eb-812d-25adc7f9d8b7.mp4


Navigation:
https://user-images.githubusercontent.com/64708228/117295317-f12d5f80-ae88-11eb-94f7-1b0d6c64ff9d.mp4

**Comment by amir2mi** [comment]
Interface: prevent sidebar layout shift with explicit scroll area #31858

**Pull request closed without merging**
