### PR TITLE
Performance: Use median instead of average to stabilize First Block metric

### PR DESCRIPTION
**Pull request by WunderBart**
## What?
The First Block Loaded has been unstable since the switch to Playwright. From https://www.codevitals.run/project/gutenberg:

Screenshot 2023-09-04 at 16 55 24

After looking into the raw values of the metrics, I found [some spikes distorting the otherwise stable values](https://github.com/WordPress/gutenberg/pull/53768#issuecomment-1705323147). To address that, let's start by calculating the median instead of the average to filter out those outliers.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think it'd be could to figure the reason for the outliers. What's different than puppeteer values?

Other than that, I'm fine with moving to "median" but not sure about doing it only for a single metric while leaving the rest using "average".

**Comment by WunderBart** [comment]
> I think it'd be could to figure the reason for the outliers. What's different than puppeteer values?

Yep, I was planning to continue investigating. The difference is that now we load each page in a new, isolated browser context. With Puppeteer, [we were using](https://github.com/WordPress/gutenberg/blob/57d7861eca9a526d896adf717f64d6483bb6cc6f/packages/e2e-tests/specs/performance/post-editor.test.js#L125) a [single/default context](https://pptr.dev/api/puppeteer.browser.newpage/#:~:text=The%20Page%20is%20created%20in%20a%20default%20browser%20context), so there was likely some sort of caching going on. 

> 
> Other than that, I'm fine with moving to "median" but not sure about doing it only for a single metric while leaving the rest using "average".

To be clear, it's not the only metric that we're currently using median for - we also do that for [TTFB and LCP](https://github.com/WordPress/gutenberg/blob/trunk/test/performance/config/performance-reporter.ts#L81-L83). I'm not sure why those metrics were kept being calculated via medians (maybe just an oversight), but from my current observations, I'd be keen to move all the loading-related metrics to `median`, as they all seem to have the tendency to produce distorting spikes.

**Review by dmsnell — APPROVED** [review]
This is more reason why distributions are going to be more helpful for us. The numbers on my latest PR for many metrics were wildly different than each other, when I know because the change didn't impact any JS, that they should have all been identical. I'm not looking at small differences either, some around 30%+.

I still think `min` is more appropriate for some tests as we are theoretically looking at what impact the _code_ might have on runtime performance, not on environmental factors, and we know that the minimum is the fastest it can get based off of the given code.

This should all get better anyway if we do _significantly more test rounds_ as the numbers should converge. What about setting up a daily task to run the tests something like 30 times (or as many as we can fit inside Github's test runner limitation of six hours)? That has come up before as a way to better measure.

It would lose the close associativity to PRs, but honestly, our numbers have consistently struggled to be reliable on a small scale so it's arguable this connection even exists today. If we ran daily runs with better statistical grouping we might have a better chance at identifying when precisely performance impacts improve or degrade.

**Comment by youknowriad** [comment]
I'm personally still concerned that there's a change that we don't understand here and that the median might be hiding real issues. If we know for sure that it's cache, maybe we can ignore the first run or things like that but at least we know what we're doing. The details are super important for performance tests.

**Comment by WunderBart** [comment]
> I'm personally still concerned that there's a change that we don't understand here and that the median might be hiding real issues. If we know for sure that it's cache, maybe we can ignore the first run or things like that but at least we know what we're doing. The details are super important for performance tests.

I will keep investigating this and try to figure out what causes those spikes in CI (still can't repro locally). We're already filtering out the first sample from metrics in which we identified it as an outlier, but in the FBL metric, [those spikes are occurring at (seemingly) random samples](https://github.com/WordPress/gutenberg/pull/53768#issuecomment-1705323147:~:text=Here%20are%20the%20aforementioned%20raw%20metrics%3A), so we can't really do that. That said, the fact that I cannot repro locally makes me think this isn't a real issue, only something specific to the CI environment.

**Comment by youknowriad** [comment]
> only something specific to the CI environment.

If it were specific to the CI environment, why it wasn't happening when we were using puppeteer?

**Comment by WunderBart** [comment]
> > only something specific to the CI environment.
> 
> If it were specific to the CI environment, why it wasn't happening when we were using puppeteer?

[As I mentioned above](https://github.com/WordPress/gutenberg/pull/54157#event-10280628859:~:text=The%20difference%20is%20that%20now%20we%20load%20each%20page%20in%20a%20new%2C%20isolated%20browser%20context.%20With%20Puppeteer%2C%20we%20were%20using%20a%20single/default%20context%2C%20so%20there%20was%20likely%20some%20sort%20of%20caching%20going%20on.), Puppeteer's stability for Loading metrics was likely related to reusing the browser context for each sample, which we're not doing currently with Playwright.

**Comment by WunderBart** [comment]
@youknowriad, looks like I was wrong - there was a real issue 😄 https://github.com/WordPress/gutenberg/pull/54188

**Pull request merged**
