### PR TITLE
Possible fix for 8522

### PR DESCRIPTION
**Pull request by andreilupu**
## Description
Provided a default `items` entry for array attributes(dynamic blocks) to avoid getting a PHP notice.
I'm not sure if it's the right way of doing it, but I'm giving more details on the issue.

The issue is #8522 

## How has this been tested?
I also added a few PHPUnit Tests for this case

## Types of changes
Bug fix (a non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I’m not totally comfortable with providing a default here; I really feel like improving the docs is the right step. That said, I’d be curious what @DanielBachhuber thinks in particular since this also relates to core REST API stuff in a way.

**Comment by chrisvanpatten** [comment]
(Also I’m so far from being a decision maker; please read the above as just an opinion/thought!)

**Comment by gziolo** [comment]
I have no idea about PHP change. However, I'm certain that `package-lock.json` changes shouldn't be included in this patch.

**Comment by andreilupu** [comment]
oh, thanks @gziolo; that was accidental and will update the branch soon.

**Comment by danielbachhuber** [comment]
> I really feel like improving the docs is the right step.

I agree with this. The expectation is that any attributes of `type=>array` will include some `items` definition.

We shouldn't magically "fix" this, as doing so could cause other unexpected breakage.

**Pull request closed without merging**
