### PR TITLE
Clean script: Use braces instead of @-pattern for glob

### PR DESCRIPTION
**Pull request by sirreal**
## What?
Try braces instead of @-pattern to fix [a windows build issue](https://github.com/WordPress/wordpress-develop/actions/runs/12277835641/job/34258166878):

```
> gutenberg@19.9.0-rc.1 clean:packages
> rimraf --glob './packages/*/@(build|build-module|build-wp|build-style)'

'build-module' is not recognized as an internal or external command,
operable program or batch file.
```

**I don't have a good setup to debug this, I have no good way of reproducing the issue or verifying the fix.**

Follow-up to https://github.com/WordPress/gutenberg/pull/67829.

## Why?

Trying to get those windows build issues addressed.

## How?

Try a different glob pattern to expand to the desired paths.

## Testing Instructions
```sh
npm run build:packages
ls packages/interactivity
```

prints

```
build
build-module
build-types
src
CHANGELOG.md
README.md
package.json
tsconfig.json
tsconfig.test.json
tsconfig.test.tsbuildinfo
tsconfig.tsbuildinfo
```

```sh
npm run clean:packages
npm run clean:package-types
ls packages/interactivity
```

prints

```
src
CHANGELOG.md
README.md
package.json
tsconfig.json
tsconfig.test.json
```

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the fix! I should have thoroughly tested all scripts 😥

I noticed that the `fixtures:clean` command wasn't working properly either on Windows: 

```
npm run fixtures:clean

> gutenberg@19.9.0-rc.1 fixtures:clean
> rimraf --glob 'test/integration/fixtures/blocks/*.+(json|serialized.html)'

'serialized.html)'' is not recognized as an internal or external command,
operable program or batch file.
```

I think this command isn't used in core so maybe we can address it in a follow-up, but will we fix it in this PR?

**Comment by sirreal** [comment]
If the clean packages script is working then we can apply the same change to the fixtures clean script I think. I'll add that change.

**Review by t-hamano — APPROVED** [review]
The error no longer occurs, but it seems that the files are not deleted on Windows OS:


https://github.com/user-attachments/assets/f4a070f7-ab0b-42cd-a979-4c92a7063f2d



However, it works correctly on Linux. Therefore, if this PR is urgent, it may be better to merge this PR once and address the issue in a follow-up.

Therefore, I will approve this PR.

**Comment by sirreal** [comment]
Thanks @t-hamano 😕 

I will land this so that CI is not broken on the Core repo and we can address those problems in a follow-up.

Maybe just using simpler patterns will work for fixtures:

```diff
diff --git before/package.json after/package.json
index a0182e2e27..846fae9550 100644
--- before/package.json
+++ after/package.json
@@ -193,7 +193,7 @@
 		"docs:gen": "node ./docs/tool/index.js",
 		"docs:theme-ref": "node ./bin/api-docs/gen-theme-reference.mjs",
 		"env": "wp-env",
-		"fixtures:clean": "rimraf --glob 'test/integration/fixtures/blocks/*.{json,serialized.html}'",
+		"fixtures:clean": "rimraf --glob 'test/integration/fixtures/blocks/*.json' 'test/integration/fixtures/blocks/*.serialized.html'",
 		"fixtures:generate": "cross-env GENERATE_MISSING_FIXTURES=y npm run test:unit test/integration/full-content/ && npm run format test/integration/fixtures/blocks/*.json",
 		"fixtures:regenerate": "npm-run-all fixtures:clean fixtures:generate",
 		"format": "wp-scripts format",
```

(this works on macOS)

**Pull request merged**
