### PR TITLE
Dynamically search for plugin-proposal-async-generator-functions

### PR DESCRIPTION
**Pull request by chipsnyder**
## Description

Fixes an error related to missing module `@babel/plugin-proposal-async-generator-functions`
`Gutenberg-Mobile` https://github.com/wordpress-mobile/gutenberg-mobile/pull/2662

## How has this been tested?

From `gutenberg-mobile`:
- `npm install`
- `npm start`
- Check that the editor loads
- Stop Metro
- `npm run core start`
Check that the editor loads

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Working great on my end 🎉 

Thank you @chipsnyder for this fix 🙏

**Comment by hypest** [comment]
👋 @chipsnyder (or @etoledom ), wondering if you have some insight on what's the issue here and how the fix ends up fixing it? Curious whether we missing something here 🤔

**Comment by etoledom** [comment]
@hypest - From what I understood, previously `@babel/plugin-proposal-async-generator-functions` was a direct dependency of `gutenberg-mobile` so babel was able to find it as `@babel/plugin-proposal-async-generator-functions`. Now it is a dependency of `@wordpress/babel-preset-default`.

I don't know why this change happened, but it seems to come from this PR: https://github.com/WordPress/gutenberg/pull/25351 (It looks like a simple version update. Npm works on mysterious ways to me).

Even though we have `@wordpress/babel-preset-default` as a dependency, now Babel can't find `@babel/plugin-proposal-async-generator-functions` directly, so we tell it the path of where to find it.

This is roughly my understand and I can be wrong, but it kinds of make sense to me.

**Comment by chipsnyder** [comment]
Hey @hypest,
@etoledom's explanation is right on for everything I found as well. The only things I would add is "lookup" needs to provide enough hints in the form of `../` to be able to find the correct `node_modules` folder as it seems to matter if I'm running `npm start`, `npm run core start` or running as the e2e tests. 

>Npm works on mysterious ways to me

Same here 😄 We also considered adding the dependency directly to `gutenberg-mobile`, which also worked fine. However, I feel like this update is more in line with the change that sparked the need.

**Pull request merged**
