### PR TITLE
Components: Extract a reusable post title component

### PR DESCRIPTION
**Pull request by youknowriad**
Related to #2761 (comment)

This PR extracts PostTitle component to the reusable components folder by removing all layout styles from the reusable components.

**Notes**

 - This also extracts `PostPermalnk`, `BlockSettingsMenu` and `BlockSwitcher` but it's not exposed because it shouldn't be used directly (yet).

 - This also includes a small redesign to the post permalink modal to match the latest block toolbar design

**Testing instructions**

- Test that the Post Title works and looks like master.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, just testing the title component, everything seems to work as it used to, so in that vein, 👍 👍

I did notice some arrow key weirdness, but there's every chance this is unrelated to this PR, but is indeed present in master. After using arrow keys between title and paragraph at some point the caret starts ending up in the middle of the paragraph block:

arrows

**Comment by youknowriad** [comment]
Just cc @mcsf @iseulde about the arrow navigation error above which is not related to this PR

**Comment by tfrommen** [comment]
@youknowriad sorry for digging up this old ticket, but regarding your comment above:

>This also extracts PostPermalnk [...] but it's not exposed because it shouldn't be used directly (yet).

when do you think the `PostPermalink` component **can** be exposed/exported?

In its current form, see [here](https://github.com/WordPress/gutenberg/blob/196a485e3de1c1e0f148d65237b1f80a8a9f576f/packages/editor/src/components/post-permalink/index.js), I don't see anything that would prevent someone from using it in a custom block (or even sidebar).
I guess, when you worked on the post title component (more than one and a half years ago), that was different...?

I'm asking because there is no way to enhance the `PostTitle` block (yet?), so to properly _replace_ it, one would most probably want to use the existing `PostPermalink` component, which is not possible either.

Hope this makes sense. 🙂

**Comment by youknowriad** [comment]
:) To be fair, I'm not certain I can answer the question properly because this component changed a lot since this PR.

I think it probably doesn't harm if we expose it (other than having to maintain it without breaking changes, which is a big question in itself).

**Comment by igmoweb** [comment]
@youknowriad I just created a new PR to expose that component here: https://github.com/WordPress/gutenberg/pull/15943

**Pull request merged**
