### PR TITLE
Fix/Remove edit gallery from media library modal

### LINKED ISSUE #21413: Remove Edit Gallery from Media Library modal
**Describe the bug**

Users are able to edit a gallery from the modal that appears when one clicks on _Media Library_ in a Gallery block. This is confusing, though, as the image captions in this modal differ from the image captions in the block. Having _Edit Gallery_ in the modal is unnecessary as galleries can be edited directly from within the block. **We should remove the _Edit Gallery_ button.** See https://github.com/WordPress/gutenberg/issues/8310 for more context.

**To reproduce**

1. Insert a Gallery block.
2. Upload a few images to the gallery.
3. Add a caption to one or more images.
3. Click _Media Library_.
4. Click _Edit Gallery_.

Note that the image captions that appear in the modal differ from the image captions that appear in the block.

**Expected behavior**

There should not be a _Edit Gallery_ button in the modal.

**Screenshots**

gallery

### PR DESCRIPTION
**Pull request by jessie-ross**
## Description
Remove edit-gallery feature from modal.
Closes #21413 

## How has this been tested?
Click tested on my local.

## Screenshots

Apr-09-2020 21-35-46

## Types of changes
Bug fix, but possibly a breaking change as we are removing a workflow.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by youknowriad** [comment]
I think removing the behavior from the MediaUpload component is not what is being suggested on the issue as this can still be useful for third-party blocks.

Should we instead update the usage of this component done in the GalleryEdit component to make it work more as an image "appender" and not as "edit gallery"?

**Comment by jessie-ross** [comment]
> I think removing the behavior from the MediaUpload component is not what is being suggested on the issue as this can still be useful for third-party blocks.
>
> Should we instead update the usage of this component done in the GalleryEdit component to make it work more as an image "appender" and not as "edit gallery"?

Ah I didn't consider third-party blocks using this. I will take a look at the MediaUpload API (oh there is a Readme!) and see how we might extend it rather than change existing behaviour.

**Comment by jessie-ross** [comment]
@youknowriad 

I can see two general paths forward with this:

1. Extending the Gallery flow.
2. Utilising the Feature image flow - this basically already does what we want it to do with some behavioural differences, so it will require some tweaks.

I feel that this choice hinges on the direction that this area of the code is headed in.

No other part of the code base is using the Gallery flow and it could potentially be deprecated if we want to encourage third party blocks to implement item management in their code. Then the MediaUpload block could eventually be reduced from 3 flows into one. This could simplify the overall MediaUpload API.

Another part to this is that the feature flow seems to be unstable using the unstableFeaturedImageFlow flag, I don't have a good hold on what this is for...

Am I on the right track with this?
Do you have a feel regarding the options above?

**Comment by youknowriad** [comment]
I'm not very familiar with all these "flows" and I consider them just implementation detail. Why not just use a regular image flow, where we just select an image from the media library and append it the gallery upon selection?

**Comment by jessie-ross** [comment]
Ah yep, that is a good solution.

There are two behavioural differences now I can see: 
1. For multi-select, under the normal image flow, you have to hold ctrl/shift/command now.
2. It shows you all media, even the ones you already have.

It looks like I will need to extend wp.media to get those in.

**Comment by youknowriad** [comment]
Looks like the related issue is now closed, so this PR is probably not relevant anymore. Thanks for your effort here.

**Pull request closed without merging**
