### PR TITLE
Remove role attributes on SVGs meant for "decoration" to improve a11y

### LINKED ISSUE #38286: Improve a11y on SVGs throughout Gutenberg
### Description

This issue stems from the work done in #38152 

In many places throughout Gutenberg, we render SVGs with `role="img"` but we do not include an `aria-label`. At first glance this may seem ok because in all instances we also have something like this:

```
<svg role="img" aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg">
      ...
</svg>
```

However in my reading about a11y, I don't believe `aria-hidden="true" focusable="false"` is sufficient here. Since we are including `role="img"`, there should also be an `aria-label` as described here in the [MDN Wed Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg). Now I am by no means a a11y expert, so I would love someone else to confirm or deny this issue. 

If it is an issue, the solution appears to be very simple. We just remove `role="img"` from all these SVGs since they are intended to be hidden from screen readers anyway. They are purely decoration and/or have other descriptive text that is readable by screen readers. 

If someone can confirm, I am happy to put together this PR. 

### Offending files/blocks: 

- [Navigation Link](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation-link/index.php)
- [Navigation Submenu](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation-submenu/index.php)
- [Navigation](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/index.php)
- [Page List](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/page-list/index.php)
- [Social Link](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-library/src/social-link)

### Step-by-step reproduction instructions

1. Using the latest version of Gutenberg, add a Social Icons block to the page.
2. Add a couple social links
3. Preview the page on the frontend and notice `role="img"` being added to all SVG icons.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ndiego**
## Description
Fixes #38286 

In many places throughout Gutenberg, we render SVGs with `role="img"` but we do not include an `aria-label`. At first glance this may seem ok because in all instances we also have something like this:

```
<svg role="img" aria-hidden="true" focusable="false" width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg">
      ...
</svg>
```

However, `aria-hidden="true" focusable="false"` is sufficient here. Since we are including `role="img"`, there should also be an `aria-label` as described here in the [MDN Wed Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/img_role#svg_and_roleimg). The solution is to simply remove the `role` attribute. Refer to #38286 for further discussion on why this is the correct approach. 

## Testing Instructions

1. Using the latest version of Gutenberg, add a Social Icons block to the page.
2. Add a couple social links
3. Preview the page on the frontend and notice `role="img"` is no longer added to all SVG icons. 🙌

## Types of changes
Bug fix

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] I've tested my changes with keyboard and screen readers. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by ndiego** [comment]
I discovered that correcting this issue actually touches virtually every part of the Gutenberg interface. The SVG primitive was also adding the `role="img"` attribute. I have made the update, but given how much this impacts, **very** thorough testing is needed. As of yet, I have not been able to identify any issues with this update. I will keep testing tomorrow...

**Review by Mamaduka — COMMENTED** [review]
It looks like there are a few more snapshots that need an update.

**Comment by ndiego** [comment]
Yeah that last change to the SVG seems to have touched a lot of tests. I will remedy today.

**Review by aristath — APPROVED** [review]
Code here looks good and is a small - but important - improvement.
I'll go ahead and pre-approve this PR so it can be merged as soon as all tests are fixed 👍

**Comment by ndiego** [comment]
@Mamaduka and @aristath I believe I successfully fixed all the tests, but I am still getting one failure related to the gallery block, which is a bit confusing as my edits didn't touch that. I am seeing the same failure in many of the latest PRs. 🤔

**Comment by aristath** [comment]
One of the tests is still failing here... @ndiego could you please rebase the PR? That _should_ fix the error here. If it doesn't, then we should take another look and see if there's something wrong 👍

**Comment by ndiego** [comment]
Looks like everything has passed after the rebase. Merging 🙌

**Pull request merged**
