### PR TITLE
Add stylelint rule to disallow the `order` CSS property

### LINKED ISSUE #61241: Add stylelint rule to prevent usage of the `order` CSS property
### Description

Previously:
https://github.com/WordPress/gutenberg/pull/57519
https://github.com/WordPress/gutenberg/pull/57640
https://github.com/WordPress/gutenberg/issues/58936
https://github.com/WordPress/gutenberg/issues/58940
https://github.com/WordPress/gutenberg/pull/58942
https://github.com/WordPress/gutenberg/issues/59013

Part of an effort to remove all the `order` CSS properties from the codebase.

For accessibility, visual/reading and DOM order must always match when they affect reading order and interaction. Basically thisis almost always the case. There's very limited cases where the `order` property can be used without affecting accessibility, for example when switching the position of an aria-hidden icon, or similar cases where the impact is only 'visual'.

To prevent future usages of the `order` CSS property, I'd like to propose to:
- Add a stylelint config or rule to trigger an error when an `order` property is found.
- In the rare cases where a `stylelint-disable` comment would be appropriate, require to specifi a disable reason.
- As far as I can tell, requiring a description for the disable reason in the comments is a 'global' configuration of stylelint so that will require to add a disable reason to _all_ the `stylelint-disable` comments, which is a good thing anyways.

Currently, there are 2 occurrences of the `order` css property, [here](https://github.com/WordPress/gutenberg/blob/280d316235c81e912484492f1e9d78b0144a4d8a/packages/block-editor/src/hooks/color.scss#L8) and [here](https://github.com/WordPress/gutenberg/blob/280d316235c81e912484492f1e9d78b0144a4d8a/packages/editor/src/components/list-view-sidebar/style.scss#L17). They're both tracked in specific issues and they will be likely removed soon. Other occurrences have been removed already.

### Step-by-step reproduction instructions

- Run `npm run lint:css` in yout terminal, in the project root.
- Observe stylelint doesn't report any error or warning for the usage of the `order` CSS property.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/61241

## What?

This PR aims to prevent the usage of the `order` CSS property.

## Why?

The `order` CSS property has a significant impact on accessibility and its usage must be prevented. In the very rare cases where its usage is appropriate, that should be a conscious choice of contributors and they should be required to add a disable comment with a disable reason.

## How?

- Adds the `order` CSS property to the `property-disallowed-list` rule.
- Adds an error message: `Avoid the order property. For accessibility reasons, visual, reading, and DOM order must match. Only use the order property when it does not affect reading order, meaning, and interaction`
- Makes a disable reason description required for all the `stylelint-disable*` comments by addint the config `"reportDescriptionlessDisables": true`.
- Adds a disable reason to all the existing disable comments.

## Testing Instructions

- Run `npm run lint:css` in your terminal, in the project root.
- Observe no errors are reported.
- Edit any .scss file in any package and add an order property e.g. `order: 1;`.
- Run `npm run lint:css` again.
- Observe stylelint reports an error.
- Check the disable reasons added to all `stylelint-disable` comments are meaningful and appropriate.

### CODE REVIEW

**Comment by afercia** [comment]
Note: this PR touches two files in the `@wordpress/components` package but I don't think the changes there need a changelog entry as they're just changes to the disable comments.

**Comment by afercia** [comment]
@WordPress/gutenberg-core I'd appreciate a review, when you have a chance 🙇🏽‍♂️

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by youknowriad** [comment]
WFM

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by afercia** [comment]
Thanks all for the review.

**Pull request merged**
