### PR TITLE
Fix: Error when calling the PostActions `view-post` callback

### LINKED ISSUE #63457: PostAction View Post returns an error
### Description

The `View` action in Post Actions returns an error in the console since Gutenberg 18.7.0
This error prevents from opening the post in a new window.

### Step-by-step reproduction instructions

1. Go to edit a post. For example `/wp-admin/post.php?post=1&action=edit`.
2. Open the console in Chrome Dev Tools
3. Click in the three dots to open the `Actions` dropdown menu.
4. Click in `View`
5. Observe the error in the console
6. Observe the browser didn't open any new window with the post frontend

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/9a7c2ae2-35d7-4f7e-8511-cbd77d2e6798

### Environment info

Gutenberg v18.7.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by sejas**
## What?

- Closes https://github.com/WordPress/gutenberg/issues/63457

Fixes the error thrown when clicking PostActions View post in the editor.

## Why?

In https://github.com/WordPress/gutenberg/pull/63120 we added support for `onActionPerformed` at action level, but I've observed the object is undefined in all the cases.

I could check. `onActionPerformed` is only used at hook level instead. If we need to remove the logic that unpacks `argsObject`, I'm happy to update this PR or open a new one.

## How?

Add a condition in case the callback options `argsObject` is undefined.

## Testing Instructions

1. Go to edit a post. For example `/wp-admin/post.php?post=1&action=edit`.
2. Open the console in Chrome Dev Tools
3. Click in the three dots to open the Actions dropdown menu.
4. Click in View
5. Observe there are not any issues in the console
6. Observe the browser did open a new window with the post frontend

## Screenshots or screencast 

**Before**

https://github.com/user-attachments/assets/6f279685-fc39-48b9-b1de-09f1070e0491

**After**

https://github.com/user-attachments/assets/fd3df4f6-ad3c-4767-b683-5b96f058d532

### CODE REVIEW

**Comment by sejas** [comment]
@jorgefilipecosta , could you take a look if this is the right direction for this fix? Thank you!

**Review by Mamaduka — APPROVED** [review]
I can reproduce the error, and the fix makes sense.

I'm not super familiar with post actions, so will leave final approval to @jorgefilipecosta.

**Comment by youknowriad** [comment]
This makes sense to me 👍

**Review by jorgefilipecosta — APPROVED** [review]
Tha change look good, thank you for this fix 👍

**Comment by andrewserong** [comment]
I just cherry-picked this PR to the release/18.8 branch to get it included in the next release: e0afea285ec

**Pull request merged**
