### PR TITLE
Use NavigatorProvider in Font Library Modal

### LINKED ISSUE #54431: Font Library: maintain focus order within nested modal
### Description

When testing the work in #53884 it was found that the focus order sequencing fails within the nested modal.

Basically, the Font Library opens in a modal. You can focus on each font in the library. Once you click or `enter` into a font in the library, you go into a nested context screen that lists the weight variations of that font: 100, 200, 400, etc.

The issue lies when you enter into a font’s nested context screen. The focus shifts to the first variation’s checkbox, which allows the builder to enable or disable that variant.

However, the first focus should go to the ‘Back’ button, which would take the builder back to the Font Library overview, and then the next focus would be the first checkbox for the first variant.

This was initially [discussed in](https://wordpress.slack.com/archives/C02RP4X03/p1694557110236409) the Make #accessibility channel.

### Step-by-step reproduction instructions

I believe the only means to test the [Font Library: Frontend [Stage 1]](https://github.com/WordPress/gutenberg/pull/53884) work is by checking out PR #53884 as the work has not been merged yet.

Hopefully, the detailed description (above) will guide users on how to recreate this bug along with the video (below).

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/405912/c3810f8e-1c65-4c86-bae4-30242ccd29ec

### Proposed actionable items to address this issue

- [ ] The 'Back' button should receive the first focus when entering into the Font Variant Overview. This would allow the user to go back immediately and skip over the variant list altogether.
- [ ] After the 'Back' button is focused the variant checkboxes will receive focus.
- [ ] The variant checkboxes should behave a checkboxes and allow the use of the Space Bar to toggle each on/off.

### Environment info

- OS: macOS 13.5.2
- Browser: Firefox 117.0
- PHP: 8.1.22
- WordPress: 6.3.1
- Theme: twentytwentythree v1.2
- Active Plugins: Gutenberg build from this PR #53884

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #58386: Font Library: Make the delete confirm dialog close immediatly after clicking 'Delete'
### Description

When deleting an installed fonr and clicking 'Delete' in the confirm dialog, the confirm dialog stays open untile the font is actually deleted and the fonr library is refreshed.

This seems to be less than ideal for a few reasons>
- As the dialog stays open, users can click 'Delete' ultiple times, especially on a slow internet.
- By clicking multiple times, a new delete request is triggered, which leads to errors like the one in the screenshot below:

Screenshot 2024-01-29 at 14 03 07

- Whatever teherror is, for example no internet connection, the confirm dialog stays open and the error notice appears behind the confirm dialog overlay. The actual error message is partially hidden. Depending on the size of the screen in use, the error may even be completely hidden. I'm not sure hiding error messages is a good user experience. Screenshot:

Screenshot 2024-01-29 at 15 10 53

### Step-by-step reproduction instructions

- Go to Site editor > Styles > Typography > Manage fonts.
- Install a Google font.
- Go to the Library tab and click the font you installed.
- Click 'Delete' at the bottom of the modal dialog. A confirm dialog opens.
- Quickly click 'Delete' multiple times.
- Observe an error message appears within the Fonts modal dialog, behind the confirm dialog overlay.
- Observe that after the font is actually deleted, the confirm dialog and the notice with the error messsage disappear.
- Note: for accessibility, when the confirm dialog closes, focus should be better handled. This is tracked in another issue.
- Install a new Google font.
- Go to the Library tab and click the font you installed.
- In your browser dev tools > Network, set your browseer to 'offline'.
- Click Delete and then Delete again in the confirm dialog.
- Observe the confirm dialog stays open.
- Observe an error message appears within the Fonts modal dialog, behind the confirm dialog overlay.
- Click Delete again. Observe the confirm dialog stays always open.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #58800: Hover Effects for Font Names and Checkboxes in Font Library Modal
## What problem does this address?

The font-variant selection interface currently lacks hover effects for font names and checkboxes. The cursor pointer change is the only indication of interactivity. 
Also, the font selection UI lacks hover effects on the font names, while it already has an effect for the arrow `>`.

https://github.com/WordPress/gutenberg/assets/5287479/66fe6749-0a4f-4ddd-a4fa-0658b750de5f

## What is your proposed solution?

- For font names: A subtle change in the background color or the border of the item to indicate the hover state
- For checkboxes: A border color change or background fill

### LINKED ISSUE #58893: Font Library: Focus loss when deleting fonts and possibly other flows
### Description

I'm not sure this ha been already tracked but there are more focus losses in the FOnts modal dialog than the one already fixed in https://github.com/WordPress/gutenberg/issues/58314

For example, when deleting a font the whole content of the modal dialog updates and the delete button that had keyboard focus disappers. As such, focus is entirely lost. Pressing tab again starts the tab sequence from scratch from the document root _outside of the modal dialog_ which is something that should never ever happen.

See attached animated GIF to better illustrate.

Possibly, there are more flows where focused element get dynamically hidden / removed thus triggering more focus losses.

loss

### Step-by-step reproduction instructions

- Make sure you already have some custom fonts installed, e.g. a Google font.
- Go to Site editor > Styles > Typography > Manage fonts.
- Use the keyboard to navigate the modal dialog focusable elements.
- In the Library tab, select an installed custom font of your choice. 
- In the sub-view with the font details, the Delete button and press Enter.
- In the confirm dialog tab to the Delete button and press Enter.
- Wait for the font deletion to complete successfully.
- The confirm dialog closes.
- Press the tab key.
- Observe focus is lost and the tab sequence starts from scratch from the 'Open Navigation' WP logo in the editor UI _outside of the modal dialog_.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by pbking**
## What?
Refactors and eliminates many view components to simplify and consolidate.
Use `NavigatorProvider` component for panels that drill into details.
Fine-tuned keyboard navigation
Added hover styles
Refactored "Font Preview" component and used it in additional places

## Why?
Simplifies the View Code
Implements Navigator pattern to address a11y navigation concerns
Addresses a number of Accessibility concerns
Fixes: #58893
Fixes: #58800
Fixes: #58386
Fixes: #54431

## Testing Instructions
Ensure that all of the interactions (including error conditions) work as expected including:
Navigating to and installing fonts from the default collection
Installing fonts by uploading them
Deleting installed fonts
Activating and deactivating installed fonts
Activating and deactivating fonts provided by themes

### Testing Instructions for Keyboard
Keyboard interactions are of primary concern for these changes.  Please ensure that all of the actions are easily complete-able with keyboard use.  A complete outline of keyboard steps are too vast to note here.

## Screenshots or screencast 
image

image

image

image

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
Thanks for working on this. This PR seems to be also fixing https://github.com/WordPress/gutenberg/issues/54431

**Comment by colorful-tones** [comment]
Sorry, I’m on vacation until 2/27. This looks promising at first glance, but I will not have the ability to spin it up in a dev server right now. I hope other’s will test and provide feedback to move this along.

**Comment by pbking** [comment]
> Thanks for working on this. This PR seems to be also fixing https://github.com/WordPress/gutenberg/issues/54431

Silly me.  That was the issue that started it all.  I've added it to the fixes list.

**Review by matiasbenedetto — COMMENTED** [review]
The `<FontDemo>` component now expects a font family, and here we are passing a font face. It causes all the variants of a font family to render with the same default style (400, normal) when no preview is provided.

https://github.com/WordPress/gutenberg/blob/5e01a2d17b246071df6af6efc9e32efffb1aa35a/packages/edit-site/src/components/global-styles/font-library-modal/library-font-variant.js#L57-L59

See the comparison:

| trunk | this branch |
| --- | --- |
| Screenshot from 2024-02-21 12-34-22 | Screenshot from 2024-02-21 12-47-05 |

Apart from the bug, I'm not sure that making this component smarter (understanding a more complex data structure as fontFamily instead of the plain fontFace) is needed or wanted. I would lean toward maintaining that component's ability to receive only font faces as a prop.

To reproduce the bug, upload a font family with several font variants using the 'Upload' tab.

**Review by matiasbenedetto — COMMENTED** [review]
On the keyboard navigation side, I tested it, and it feels much better than before. Thanks for adding that.

**Comment by pbking** [comment]
> The <FontDemo> component now expects a font family, and here we are passing a font face. It causes all the variants of a font family to render with the same default style (400, normal) when no preview is provided.

Thank you @matiasbenedetto.  I pushed a small change to better support accepting EITHER a font FACE or a font FAMILY for the demo.

Result:

image

To test I changed the [default font collection](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.5/fonts/fonts.php#L160) to `'https://s.w.org/images/fonts/17.7/collections/google-fonts.json'` so that it would render without previews.

**Comment by matiasbenedetto** [comment]
I think we should not use a custom font on the title, because it can be problematic:


| trunk | this branch |
| --- | --- |
| image | image |

**Comment by pbking** [comment]
> I think we should not use a custom font on the title, because it can be problematic

It's equally problematic for the list you selected the font family for.  If it's a problem as the title here it's a problem in the list and we should probably have some way around that in both places.

**Comment by matiasbenedetto** [comment]
> It's equally problematic for the list you selected the font family for. If it's a problem as the title here it's a problem in the list and we should probably have some way around that in both places.

We should probably find a workaround to the list of fonts, too, in a follow-up. But using the [demo in that title ](https://private-user-images.githubusercontent.com/1310626/306778596-d4a78e7d-aa59-4613-b2a2-9fc473b4e0c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDg0NTMsIm5iZiI6MTcwODYwODE1MywicGF0aCI6Ii8xMzEwNjI2LzMwNjc3ODU5Ni1kNGE3OGU3ZC1hYTU5LTQ2MTMtYjJhMi05ZmM0NzNiNGUwYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTMyMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZkMTE3MDNjM2NiNDVmZmFhOTUwNjliY2Q3NzI1MzczNmIyN2RhNDU5NDkzZjQ0ZTY5MWNhZDk5ODZjNTBhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WK9bDEIS0oGl8klMBOj3eZMAyYET5ZkHhqj6NG7O01M)is not in the mockups, and I don't think it is wanted, and it should not be added at this point either.

**Comment by pbking** [comment]
> But using the demo in that title is not in the mockups

Ok, you got me with that one. :) I've changed it back to a heading.

**Comment by matiasbenedetto** [comment]
@pbking, could you check why this behavior of the margins is happening in this branch?


https://github.com/WordPress/gutenberg/assets/1310626/91067a80-0388-45bf-945f-0c45739af316

**Comment by matiasbenedetto** [comment]
> @pbking, could you check why this behavior of the margins is happening in this branch?

Ohh it's because of the revoke permissions buttons. That's unrelated to the scope this PR. Added a comment in https://github.com/WordPress/gutenberg/pull/59205#issuecomment-1961592518

**Review by matiasbenedetto — APPROVED** [review]
This PR is testing well on my end.
On my tests it is fixing the issues described in https://github.com/WordPress/gutenberg/issues/58893, https://github.com/WordPress/gutenberg/issues/58800, https://github.com/WordPress/gutenberg/issues/58386 and https://github.com/WordPress/gutenberg/issues/54431 and the existing functionality continues working as expected.

**Comment by matiasbenedetto** [comment]
I think PR introduced the following regression: when you click a font from the list, the modal opens in the main library tab and not on the tab listing the variants of the font family clicked. Opening the list of variants of the font clicked in the sidebar was one of the original requirements of the design, so we should restore that behavior. 

Screencast featuring  behavior after this PR:

https://github.com/WordPress/gutenberg/assets/1310626/af0c079e-3794-4948-917d-f7ee5610f18b

**Comment by getdave** [comment]
I just _manually_ cherry-picked this PR to the [cherry-pick-wp-6-5-beta-3 branch](https://github.com/WordPress/gutenberg/pull/59394) to get it included in the next release.

**Pull request merged**
