### PR TITLE
Absorb block manager within blocks preferences

### PR DESCRIPTION
**Pull request by stokesman**
Extension of #31191. It has a few additional changes addressing preceding comments (https://github.com/WordPress/gutenberg/pull/31191#issuecomment-827566884, https://github.com/WordPress/gutenberg/pull/31191#pullrequestreview-645754716) and proposed improvements.

## How has this been tested?
Manually

### > medium breakpoint

https://user-images.githubusercontent.com/9000376/121935411-42890400-ccfd-11eb-8035-1bbdba0b756e.mp4

### < medium breakpoint

https://user-images.githubusercontent.com/9000376/121935464-4e74c600-ccfd-11eb-98be-0d9eaaf7b9dc.mp4

## Types of changes
Enhancement

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by youknowriad** [comment]
This is looking very good both in terms of code and design/behavior.

The only thing that bothered me a bit is the size of the modal in large screens. It seems it's too small (specially in terms of height)

**Comment by jasmussen** [comment]
Nice work as always 👌 

This is what I see:

prefs

In the GIF I stumble a bit on the fact that the active tab is remembered across opening preferences. That's not specific to this branch, so not something to worry about. Just felt slightly weird that it isn't reset on close.

Other than that this is superb, except for that thing Riad mentioned — the height does feel a bit small. Mostly when the height grows smaller at a lower breakpoint. That makes sense at mobile and very small breakpoints. But it doesn't seem like it adds a ton of value that the modal grows less tall beyond the 1440 breakpoint. I know that's an existing issue, but it seems like if we can unify everything beyond medium and upwards on a single height, the goldilocks height, it would address Riad's thought!

Very cool to see this, thank you again.

**Comment by stokesman** [comment]
Good call about that modal height. I have removed the height adjustment at the huge breakpoint. I'm glad to adjust further if needed. Now the height matches what the base Modal style is for max-height (which was recently updated in #31639). 

While I was testing I noticed this annoying gap above the sticky headers can still happen:

https://user-images.githubusercontent.com/9000376/122132983-bbb55380-cdf0-11eb-9099-5e880ee45679.mp4

I found adjusting line-height can fix it but then found `display: flex` also did the trick and that conveniently allowed a little consolidation of style rules so I went with that.

Then I found a tiny bit more ambition and changed a couple of other things:
 - I noticed an ad hoc margin that could be replaced with grid variable (and I shrank it one unit).
 - The larger font-size of the block category titles didn't seem warranted (the same size as the section header they are inside of) so I removed that.

Hopefully that's all good because it seems better to me. I'm happy to change anything.

**Review by jasmussen — APPROVED** [review]
Lovely. Assumming Riad's code review still applies, this one is sweet:

hey

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
the unit tests failure are valid, it seems.

**Comment by stokesman** [comment]
> the unit tests failure are valid, it seems.

Snapshot updated, rebased and fixed an e2e test and all is green.

**Comment by youknowriad** [comment]
Go go merge it :)

**Comment by mtias** [comment]
Looking at this in context I think there are a few design improvements we can make.

- Simplify the title to "Available Blocks" or "Visible Blocks".
- Add a longer text description "Disable blocks that you don't want to appear in the inserter. They can always be toggled back on later."
- The search looks fairly confusing as it stands, can it look the same as the block inserter one with placeholder text?

cc @jasmussen @kellychoffman

**Comment by youknowriad** [comment]
> The search looks fairly confusing as it stands, can it look the same as the block inserter one with placeholder text?

I think a `SearchControl` component extracted from the inserter one would be a good addition to the UI components we have.

**Comment by jasmussen** [comment]
Started work on the above bits of feedback in #32922. Note that I went with "Visible blocks" in sentence case, as the other headlines and titles use that.

**Pull request merged**
