### PR TITLE
Switch react-autosize-textarea to react-textarea-autosize

### PR DESCRIPTION
**Pull request by noahtallen**
## What?
Solves at least part of #48009 

The package we use to auto-resize text areas in React doesn't support React 18 and hasn't been actively maintained for 3 years. Another package, react-textarea-autosize does support React 18, so this PR attempts to switch.

One issue I found so far is that the initial text height is incorrect in some situations. I could only verify this bug in **Firefox**, not Chrome or Safari.

1. Switch to code editor. Initial height will be **incorrect**.
2. Type something or open the dev tools and the height will be **correct**
3. Reload the page -- it'll stay in code editor, and the height will be **correct** this time.
4. Switch back to normal editor, and then back to code editor. Height will be **correct**.
5. Switch back to normal editor, and reload the page. Then open the code editor. Height will be **incorrect**

Not sure why, though. 🤔 Reported the bug here: https://github.com/Andarist/react-textarea-autosize/issues/366

## Why?
We want to upgrade to modern npm/node versions, which means resolving peer dependency errors. As a result, we need to use maintained packages which have peer dependencies on React 18 instead of older React versions.

## How?
Just switching the packages!

## Testing 
This seems to be mostly working, but I'm noticing that the text area does not re-size on initial load. It does resize after reloading the page, for some reason.

We need to test these components:
- [ ] The `BlockHTML` component in `block-editor` (used in the block list in "html" mode)
- [ ] The `PlainText` component in `block-editor`
- [ ] The `CodeEditorTextArea` component in `edit-site`
- [ ] The `PostTextEditor` component in `editor`

### CODE REVIEW

**Comment by t-hamano** [comment]
I happened to be working on a similar problem in #39619.

`PlainText` uses [an internal EditableText component](https://github.com/WordPress/gutenberg/blob/356a1b1555ab7302a6e17d88c32abcace6feb1e7/packages/block-editor/src/components/plain-text/index.js#L21-L23)  when the experimental version is 2. On the other hand, if no version is specified, it uses [the TextareaAutosize component](https://github.com/WordPress/gutenberg/blob/356a1b1555ab7302a6e17d88c32abcace6feb1e7/packages/block-editor/src/components/plain-text/index.js#L28-L33). The effort is to stabilize version 2 and deprecate version 1 to avoid the use of unmaintained `react-autosize-textarea`.

However, as noted in [this comment](https://github.com/WordPress/gutenberg/issues/39619#issuecomment-1428039655), `PlainText` version 2 removes HTML tags, so it cannot be used in the HTML block or the shortcode block, for example. If this PR is merged, Those two blocks could be solved by using the new `react-textarea-autosize` directly.

I will be happy to help with testing!

**Comment by t-hamano** [comment]
> One issue I found so far is that the initial text height is incorrect in some situations. I could only verify this bug in Firefox, not Chrome or Safari.
> 
> Switch to code editor. Initial height will be incorrect.
> Type something or open the dev tools and the height will be correct
> Reload the page -- it'll stay in code editor, and the height will be correct this time.
> Switch back to normal editor, and then back to code editor. Height will be correct.
> Switch back to normal editor, and reload the page. Then open the code editor. Height will be incorrect

I tested it on Windows. Unless my procedure was incorrect, the problem did not reproduce. Is this an OS issue_?

https://user-images.githubusercontent.com/54422211/220232903-f0f50608-dda5-4420-b08d-beb0225faf20.mp4

**Comment by t-hamano** [comment]
I have tested both Chrome and Firefox on Windows OS.

- ✅ The `BlockHTML` component in `block-editor` (used in the block list in "html" mode)
- ⚠️The `PlainText` component in `block-editor`
- ✅ The `CodeEditorTextArea` component in `edit-site`
- ✅ The `PostTextEditor` component in `editor`

As for the `PlainText` component, I only tested the version 1 one. This is because `react-textarea-autosize` is [not used in version 2](https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-editor/src/components/plain-text/index.js#L21-L23).

In the two blocks using PlainText (HTML Block, Search Block), I found the following problems:

--- 

Switching to the code editor and back to the normal editor. Height will be incorrect. Occurs only in Chrome.

<details>
<summary>Screencast for the Custom HTML BLock</summary>

https://user-images.githubusercontent.com/54422211/220238841-4ae7766b-762d-472c-aa4d-8570abec0bac.mp4
</details>

<details>
<summary>Screencast for the Shortcode Block</summary>

https://user-images.githubusercontent.com/54422211/220239959-24ce3132-feca-4a46-bd51-6ad77765ed9b.mp4
</details>

Switching to the code editor for the first time, the HTML will cut off. Occurs only in Firefox.

<details>
<summary>Screencast for the Custom HTML Block</summary>

https://user-images.githubusercontent.com/54422211/220239150-c32c60d6-1a4f-473f-b91a-042d29d5725f.mp4
</details>

<details>
<summary>Screencast for the Shortcode Block</summary>

https://user-images.githubusercontent.com/54422211/220240083-cc513c68-d9a9-4009-92fd-d87d9cbb429c.mp4
</details>

---

As for the React Native app, I can't test it, but the version 1 PlainText component is used in the following three places:

https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-library/src/code/edit.native.js#L41-L53

https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-library/src/file/edit.native.js#L484-L488

https://github.com/WordPress/gutenberg/blob/b2c16f3c684098a8dabff3911c610caa5c053701/packages/block-library/src/search/edit.native.js#L306-L327

**Review by tyxla — COMMENTED** [review]
The code changes themselves look well to me. There are API differences between those two packages, but we're not using any of those APIs, so we're safe on that side.

It seems like the only problem we need to take care of is the regression that came from manual testing - kudos @t-hamano for the thorough testing 🙌

**Comment by noahtallen** [comment]
> I tested it on Windows. Unless my procedure was incorrect, the problem did not reproduce. Is this an OS issue_?

It could be -- I'm on Firefox in macOS. However, the issues you noted sound very similar to that one :) In your first video, I don't think there is enough text in the editor to trigger the bug (it has to be longer than the default minimum height)

Here's my video of the problem: https://user-images.githubusercontent.com/6265975/219794503-2f3282f2-0395-4839-a3e7-f7dc115d0131.mp4

It sounds like we are blocked until we can get the maintainer to release a new version :( There is a proposed fix (https://github.com/Andarist/react-textarea-autosize/pull/353), which might solve these problems for us. However, it doesn't look like the maintainer has been active in the past few weeks. 

I don't think we can reasonably fix the bug on our side

**Comment by t-hamano** [comment]
>  In your first video, I don't think there is enough text in the editor to trigger the bug

You're right, I was also able to reproduce this problem in Windows OS.

> In the two blocks using PlainText (HTML Block, Search Block), I found the following problems:
> Switching to the code editor and back to the normal editor. Height will be incorrect. Occurs only in Chrome.

If you don't mind, could you test if this problem reproduces on MacOS as well? The proposed fix (https://github.com/Andarist/react-textarea-autosize/pull/353) appears to be for firefox, so even if a fixed version is released, this issue might not be resolved.

**Comment by noahtallen** [comment]
The fix was merged in that repo, so hopefully it'll make it to npm in the next day or two, at which point I'll revisit this and test that scenario!

**Comment by t-hamano** [comment]
[v8.4.1](https://github.com/Andarist/react-textarea-autosize/releases/tag/v8.4.1), which fixes bugs related to Firefox, has been released. How about incorporating this package into this PR and testing it again?

**Comment by t-hamano** [comment]
I tried this PR again with the latest version of `react-textarea-autosize` incorporated, but the problem remained 😅

I cannot determine which side this problem is on, but if you click on the `textarea` or resize the screen, the correct height is set. I'm wondering to figure out if we can make this work...

**Comment by t-hamano** [comment]
Update:

[A new PR](https://github.com/Andarist/react-textarea-autosize/pull/371) has been submitted on this issue in the `react-textarea-autosize` repository. This PR also seems to be related to height recalculation, so let's confirm this again when this is merged.

**Comment by noahtallen** [comment]
Nice, thanks for the update!

**Comment by t-hamano** [comment]
Update: I saw [a tweet](https://x.com/yisibl/status/1704879401710846429?s=20) suggesting that the native textarea element might auto-adjust its height.

In the future, if this is supported by major browsers, we may be able to solve this problem without relying on libraries 😊

**Comment by ellatrix** [comment]
Btw, we could completely simulate a textarea with a `contenteditable` div, which we do now with `PlainText`, but there could be some unfixed issues and **currently `PlainText` is only available for blocks**, where it's more important to use different tag names.

Ideally we should deprecate PlainText version 1, as said earlier, so that's one use of textarea less.

> PlainText version 2 removes HTML tags

Yes, we should fix that (I can't remember the reasons there)

**Comment by noahtallen** [comment]
I'm going to close the PR -- the fixes still haven't been shipped to the library, and I won't have time to work on this any more. Plus, Ella's idea sounds more ideal

**Pull request closed without merging**
