### PR TITLE
Explore using a modal to replace the publish panel

### PR DESCRIPTION
**Pull request by brentswisher**
This is a rough attempt at adding a modal as described in #15847. This is a first step toward enhancing the publishing flow, based off of the designs by @sarahmonster and others tracked in #7602. It will need some additional work, but I thought it would be useful to get some feedback on it at this stage before continuing. The conversation about these changes is a bit fragmented so I am hoping that having some code to look at will help prioritize next steps.

@sarahmonster - Thank you for the great design work, you will notice some of the wording different from the mockups. In working through the code there were some variations between the existing panel and the mockups, usually around wording for scheduled posts. Where it made sense to me I kept the same messages if they were similar enough, but I'm happy to change as needed.

Open to any and all criticisms and suggestions. I used the existing postPublishPanel as a rough framework, and I need to review if some of the logic makes sense as a modal. I'll continue to update this as I have availability and depending on if it's looking like a direction worth exploring.

Additional plans for now:
- [x] Review componentDidUpdate in the postPublishModal component, I believe this is unnecessary with it being a modal but wanted to test further before removing.
- [ ] Writing unit tests
- [ ] Review for accessibility using [https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html) as a guideline for a multi-modal flow (I know there was some concern about changing the title of a modal mentioned in one of the issues)
- [x] Clean up design of the post-publish page
- [ ] Explore adding tags and post format suggestions back, but in the post-publish view

### CODE REVIEW

**Comment by brentswisher** [comment]
I have made some updates to bring this into line with an updated prototype in https://github.com/WordPress/gutenberg/issues/7602#issuecomment-517509146. I also made a few intentional changes:
- Left the "Always use these pre-publish checks" checkbox above the cancel and publish button. I believe for accessibility it is generally better to have the submission buttons at the end of a form
- Set a standard width for the modal per @mapk's feedback in the issue.
- Left a "Publishing..." modal with the spinner animation - This is closer to what is there now, and I found the modal blipping in and out very disorienting. I know there are some accessibility concerns with this changing the title of the modal mentions somewhere. My hope is to match this up to the techniques in the delivery address demo [here]( https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html ) to remedy any issues. But feedback from someone on the accessibility team would be great.

Leaving this as a Draft PR as there is quite a bit of back and forth in #7602 about whether a modal is a step forward or not. Hoping that this work will move the conversation forward by being able to experience it, but understand this is far from a settled direction for the publishing flow. (I will also work on getting a version up with this prototype in a full screen modal early next week @karmatosed)

**Comment by karmatosed** [comment]
Thanks for working on this @brentswisher. I have a few pieces of feedback but feel I need to see this in full screen modal first. For me right now the experience is really distracting hopping from one size to other. I also feel the layout is a little confusing. Let's get this into the modal though first and then iterate. It's helpful to see as a prototype and really focuses on evaluating the experience.

**Comment by brentswisher** [comment]
It seems like this isn't a direction that is moving forward, working on cleaning up old PR's so I plan on closing this out next week unless there is some objection that it might still be useful. (Thoughts @karmatosed?)

**Comment by karmatosed** [comment]
@brentswisher I think closing this is fine. I'll do that now. Thanks.

**Pull request closed without merging**
