### PR TITLE
Fix skipped shortcode transforms in raw handling

### LINKED ISSUE #22837: Valid shortcode transforms are skipped in rawHandler calls
**Describe the bug**
Raw handling relies on [`segmentHTMLToShortcodeBlock()`](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/blocks/src/api/raw-handling/shortcode-converter.js) to transform shortcodes into blocks where possible. This function will skip transforming shortcodes with lower transform priority that appear earlier in the HTML string than another transformable shortcode with a higher priority.

The problem occurs because the function assumes that the first matching transform is also the first shortcode in the HTML. Instead, it should call `segmentHTMLToShortcodeBlock()` [on `beforeHTML` in its return value](https://github.com/WordPress/gutenberg/blob/4857ad58c1241b3d63d21a6880c989b85746c3dc/packages/blocks/src/api/raw-handling/shortcode-converter.js#L107) because `beforeHTML` may contain transformable shortcodes with lower priority.

**Example**

Assume a valid, matching transform exists for `[my_block]` with a priority of 15, which is lower than the default priority of 10 for the `[caption]` transform.

````html
<h2>Heading Content</h2>
[caption id="attachment_26694" align="alignright" width="300"]<img class="size-medium wp-image-26694" src="http://wordpress.test/wp-content/uploads/2020/05/placeholderimage-300x169.png" alt="alt text for placeholder image" width="300" height="169" /> placeholder image caption[/caption]
[my_block]Shortcode Content[/my_block]
````
Passing the above content to `segmentHTMLToShortcodeBlock()` has the following, expected result:

````js
[
    0: "<h2>Heading Content</h2>",
    1: {name: "core/image"...},
    2: {name: "namespace/my-block"...}
]
````
However, if you change the priority of the `[my_block]` transform to 5, the result becomes:

````js
[
    0: "<h2>Heading Content</h2>[caption id=\"attachment_26694\" align=\"alignright\" width=\"300\"]<img class=\"size-medium wp-image-26694\" src=\"http://wordpress.test/wp-content/uploads/2020/05/placeholderimage-300x169.png\" alt=\"alt text for placeholder image\" width=\"300\" height=\"169\" /> placeholder image caption[/caption]",
    1: {name: "namespace/my-block"...}
]
````

**Expected behavior**

Transform priority and block registration order should not affect the result of `segmentHTMLToShortcodeBlock()` on the example content. The result should always be:

````js
[
    0: "<h2>Heading Content</h2>",
    1: {name: "core/image"...},
    2: {name: "namespace/my-block"...}
]
````

**Editor version (please complete the following information):**
- WordPress version: 5.4.1
- default editor

### PR DESCRIPTION
**Pull request by apmatthews**
Fixes #22837 

## Description
Changes the shortcode converter in `rawHandler()` to allow non-linear shortcode replacement while segmenting an HTML string. This prevents the priority or registration order of a transform from affecting how shortcodes are parsed out of HTML and into blocks.

I'd appreciate feedback on whether this might have unintended consequences or if there was a reason it was not done before.

## How has this been tested?
~~I've tested locally with the example outlined in #22837, but someone more familiar with the codebase should definitely take a look.~~

Integration test case has been included.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
Could you add a test for this? :)

**Comment by apmatthews** [comment]
@ellatrix The test case has been added. I think I found the right place for it, but I'm new to contributing here so please let me know if I've missed something. 🙂

**Comment by apmatthews** [comment]
It doesn't seem like the test failures are related to this PR. I rebased on `master` again today and got a different set of failures than when I rebased in September.

Anything else I can do help this land in WP 5.6?

**Review by mcsf — APPROVED** [review]
The fix seems sound and the tests catch the issue.

**Comment by mcsf** [comment]
Thanks for the fix, @apmatthews! This should make its way into 5.6. :)

**Pull request merged**
