### PR TITLE
Storybook: Categorize "Other" components

### LINKED ISSUE #18670: Storybook: Categorize "Other" components
**Describe the bug**
`Popover` and `TabPanel` are not categorized under "Components" within Storybook.

**Screenshots**
Screen Shot 2019-11-21 at 10 11 07 AM

### PR DESCRIPTION
**Pull request by ItsJonQ**
## Description
Fixes `Popover` and `TabPanel` categorization for Storybook.

## How has this been tested?
Tested in Storybook

## Screenshots
Screen Shot 2019-11-21 at 10 16 42 AM

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

Resolves https://github.com/WordPress/gutenberg/issues/18670

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Thanks for the fix

**Review by gziolo — APPROVED** [review]
Thanks for fixing it 👍

**Comment by ItsJonQ** [comment]
@youknowriad / @gziolo How do I make Travis like me? 😂

**Comment by youknowriad** [comment]
Tests have been very unstable lately, we should work on it. Ignore the unstable tests or fix them.

**Pull request merged**
