### PR TITLE
Popover: fix inserter glitch

### LINKED ISSUE #18953: Sibling inserter block library keeps resizing itself
## The issue
Try opening the inserter menu from the sibling inserter button. It keeps resizing itself every second.

## How to reproduce
1. Click the sibling inserter

## Environment
- WordPress 5.4-alpha-46814
- Gutenberg `master` as of https://github.com/WordPress/gutenberg/commit/49dac29050c054056746cd861c0d2c2e2146d68a
- Using Dissenter browser 0.70 (based on Chromium 78)

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #18953.

Since #18813, the popover content height it calculated with `scrollHeight`, but this doesn't work properly if the content itself contains another scroll container. As a result, if you open the sibling inserter, the content height will continuously change, causing the content to move up and down every half second.

The solution is to revert to using `getBoundingClientRect` without `maxHeight` set. This can be done right at the start, and for performance reasons at every interval after that because we have to remove `maxHeight` first to get the bounding client rect.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Review by epiqueras — COMMENTED** [review]
>As a result, if you open the sibling inserter, the content height will continuously change, causing the content to move up and down every half second.

I can't seem to reproduce this. Is this browser specific?

**Comment by ellatrix** [comment]
@epiqueras No, I think it's for all browsers. It just got reported here: #18953.

**Review by youknowriad — COMMENTED** [review]
This fixes that particular issue but there's still other glitches, for example, if you open the "More Menu" (top right) in a screen with a small height and then scroll to the bottom of the menu, you'll notice that it will jump to the top again.

**Comment by ellatrix** [comment]
@youknowriad Ah, I see what you mean. It looks like we cannot measure the height after the first time, then, so I'll revert it back to the old behaviour of only measuring once at the start. This will introduce the problem with the "Block Settings" ellipsis menu again though. We have to figure out why the height is not measured correctly at the start.

**Comment by youknowriad** [comment]
yeah, hard problem. Maybe the content is not ready on first render for some reason for these popovers.

**Comment by ellatrix** [comment]
@youknowriad It should be fixed now. Looks like at the animation frame the height is good for both popovers.

**Review by youknowriad — APPROVED** [review]
This is magic

**Comment by ellatrix** [comment]
Ugh, this makes a number of jest tests fail that rely on having the popover visible immediately.

**Comment by ellatrix** [comment]
I'm not sure what to do about the tests here. For the tests, a later refresh fails them. I don't have a good understanding of the react DOM test utils and I'm not sure what they fail...

**Comment by youknowriad** [comment]
Maybe @gziolo can help here :)

**Comment by ellatrix** [comment]
The refresh on animation frame is somehow confusing the tests. If I use `setTimeout` it works fine.

**Comment by youknowriad** [comment]
@ellatrix there's some tricks here https://github.com/facebook/jest/issues/5147

**Comment by ellatrix** [comment]
It looks like a timeout (0) works just fine as well and leaves the tests working. Let's go for that then. I suspect the underlying height problem is the same as:

https://github.com/WordPress/gutenberg/blob/c75761c5ae66473e0ad4e8fc351cc2bd2562f23a/packages/components/src/popover/index.js#L134-L140

Hopefully we find can figure out a proper solution in a follow up PR. Cc @aduth since you created #11430.

**Comment by epiqueras** [comment]
Nice work!

Interestingly, I was never able to replicate #18953 on my machine.

**Comment by youknowriad** [comment]
@epiqueras I did reproduce before this PR, i think it was related to viewport size somehow.

**Comment by epiqueras** [comment]
Ah, that could be it!

**Pull request merged**
