### PR TITLE
Hide metaboxes in Zoom Out

### PR DESCRIPTION
**Pull request by getdave**
## What?

Hides metaboxes in Zoom Out mode.

Closes https://github.com/WordPress/gutenberg/issues/66718

## Why?

Meta boxes don't belong in Zoom Out which is designed for composing content.

## How?

Conditionalise based on Zoom Out state.

## Testing Instructions

- Install Plugin that registers metaboxes (e.g. Yoast SEO)
- New Post
- See Metaboxes
- Enable Zoom Out
- See Metaboxes are hidden.

## Screenshots or screencast 

https://github.com/user-attachments/assets/fb855404-378d-44d8-8751-e3bf754ac04e

### CODE REVIEW

**Review by kevin940726 — APPROVED** [review]
Tested well for me! I'd appreciate if there's someone more familiar with the feature to test any edge cases though.

**Review by MaggieCabrera — APPROVED** [review]
This makes sense to me and works as intended

**Comment by t-hamano** [comment]
I'm away from my desk right now so I can't test it, but the code looks good to me.

**Comment by getdave** [comment]
I ended up force merging this one. The React Native tests passed but something in the process stops the test completing. Here's screenshot to confirm:

Screen Shot 2024-11-05 at 11 24 35

**Pull request merged**
