### PR TITLE
Footnotes: Fix writingMode (text orientation setting) on the front

### LINKED ISSUE #54344: Footnotes: writingMode (text orientation) is not visible on the front
### Description

When the text orientation option is enabled for the footnotes block, the style is not visible on the front, only in the editor.

### Step-by-step reproduction instructions

Activate a block theme.
The writing mode setting is disabled by default; set it to true in theme.json settings > typography > writingMode:

```
	"settings": {
		"typography": {
			"writingMode": true
		}
	}
```

Create a new post or page, and add a footnote.
Select the footnote and enable the vertical text orientation option in the typography panel.
Save and view the front.
Confirm that the text is not vertical on the front.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Closes https://github.com/WordPress/gutenberg/issues/54344
Adds the missing inline styles for the writing mode (text orientation typography setting) on the front.

## Why?

The setting works in the editor but not the front.

## How?

Checks if the attribute for the writingMode block support is set and adds the inline styles to the block wrapper.

## Testing Instructions
Activate a block theme.
The writing mode setting is disabled by default; set it to true in theme.json settings > typography > writingMode:

```
	"settings": {
		"typography": {
			"writingMode": true
		}
	}
```

Create a new post or page, and add a footnote.
Select the footnote and enable the vertical text orientation option in the typography panel.
Save and view the front.
Confirm that the text is now vertical on the front.

## Screenshots or screencast 
In the video, I am setting the text orientation setting to vertical:
https://github.com/WordPress/gutenberg/assets/7422055/e8a514bf-bf4a-44af-bcd1-6ebfb4502779

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
My understanding is that, like other block supports, `writing-mode` style should also output inline styles automatically via the `get_block_wrapper_attributes()` function. Therefore, [this code](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/packages/block-library/src/post-navigation-link/index.php#L32-L34) in the Post Navigation Link block should not be necessary in the first place.

After investigating the problem, I found that the fundamental problem was that the `writing-mode` was removed by [the `safecss_filter_attr()` function in the style engine's `filter_declaration` method](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/packages/style-engine/class-wp-style-engine-css-declarations.php#L125-L132).

[The `safecss_filter_attr()` function](https://github.com/WordPress/wordpress-develop/blob/fe097d1686f6eea3e7a347ad5f361c1bbd6ce1f8/src/wp-includes/kses.php#L2309) currently does not allow the `writing-mode` property.

Therefore, the ideal approach I believe would be the following:

1. Create a `lib/compat/wordpress-6.4/kses.php` file and add a hook to allow the `writing-mode` property on the Gutenberg plugin side (For backward compatibility with WordPress versions supported by the Gutenberg plugin). [Like this](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/lib/compat/wordpress-6.3/kses.php). However, the writing-mode support should have been added in WP6.3, so the `wordpress-6.3` directory might be more appropriate.
2. Confirm that the problem has been resolved in the Footnotes block.
3. Remove [this code](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/packages/block-library/src/post-navigation-link/index.php#L32-L34) in the Post Navigation Link block and verify that the problem does not occur.
4. In the core, submit a patch to allow `safe_css_filter_attr()` function to allow the `writing-mode` property (and add unit tests).

@ramonjd @tellthemachines
I know you are all very familiar with this kind of work, so if you have any problems with these steps, please comment 🙇

**Comment by ramonjd** [comment]
@t-hamano Thanks for the ping.

Yep, those steps sound right and are consistent with past approaches, e.g., https://github.com/WordPress/gutenberg/pull/43004 👍🏻

**Comment by t-hamano** [comment]
Thank you for checking, @ramonjd!

@carolinan I would be happy to help you with these steps if needed 👍

**Comment by carolinan** [comment]
@t-hamano Thank you. I was not happy with needing to add it this way to the PHP files, but could not figure it out. You solved it!
I read your comment yesterday but I have not had time to start working on it, so if you are able to do that, that would be great.

**Comment by t-hamano** [comment]
> 1. Create a `lib/compat/wordpress-6.4/kses.php` file and add a hook to allow the `writing-mode` property on the Gutenberg plugin side (For backward compatibility with WordPress versions supported by the Gutenberg plugin). [Like this](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/lib/compat/wordpress-6.3/kses.php). However, the writing-mode support should have been added in WP6.3, so the `wordpress-6.3` directory might be more appropriate.
> 2. Confirm that the problem has been resolved in the Footnotes block.
> 3. Remove [this code](https://github.com/WordPress/gutenberg/blob/900439e2d123eff21525c1bcc5e1349c787e4e0f/packages/block-library/src/post-navigation-link/index.php#L32-L34) in the Post Navigation Link block and verify that the problem does not occur.

I have submitted #54581 which achieves these three things, so I would like to close this PR.

**Pull request closed without merging**
