### PR TITLE
Query Loop: Add animation when navigating with "enhanced pagination" enabled

### LINKED ISSUE #54060: Add a fading animation to the enhanced Query Loop navigation
## What problem does this address?
As stated [here](https://github.com/WordPress/gutenberg/pull/53812#issuecomment-1693305042) by @pablohoneyhoney, we can improve the UX of the enhanced Query loop powered by the Interactivity API ([Tracking Issue](ttps://github.com/WordPress/gutenberg/issues/53740)) by animating it:

> Would we also add some swift fading to make the transition a bit more kansei? even if the user prefers to deactivate it.

## What is your proposed solution?

- In the frontend: Add a swift fade animation to the pagination
- ~In the Site Editor: When the `Enhanced pagination` toggle is enabled, display a second toggle (enabled by default) to allow the user to enable/disable the animation~

### PR DESCRIPTION
**Pull request by DAreRodz**
## What?

This PR adds a subtle animation when visiting different pages of a Query Loop with "enhanced pagination" enabled. It also adds a smooth scroll behavior for the navigation.

When `reduced-motion` is preferred, the animations and the smooth scroll are turned off automatically.

Will close https://github.com/WordPress/gutenberg/issues/54060.

## Why?

To make the transition a bit more _kansei_, as mentioned in https://github.com/WordPress/gutenberg/pull/53812#issuecomment-1693305042.

## How?

For the animations, I had to add a new option to `navigate()` named `beforeRender`. It's a callback that runs right before we call Preact's render to update the HTML. The callback can be asynchronous, and this PR uses it to animate the current Post Template block before it's updated.

For the scroll behavior, I'm changing the value of the `scroll-behavior` CSS  property on the [`document.scrollingElement`](https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement) to `smooth` right before calling `element.focus()` and restoring its previous value right after.

## Testing Instructions

1. Go to the site editor.
2. In the Blog Home template, enable the "enhanced pagination" setting for the Query Loop block.
3. Ensure you have a Query Pagination block.
4. Visit the home page.
5. Click on Older Posts.
6. Check that the fade-out / fade-in animations occur.
7. Check that the browser smoothly scrolls to the focused item (the first link).
8. Go to your OS accessibility settings and enable "reduce motion".
5. Click on Older Posts.
6. Check that the fade-out / fade-in animations don't happen this time.
7. Check that the scroll jumps directly to the focused item (the first link).

## Screenshots or screencast

| Without `reduced-motion` | With `reduced-motion` |
| --- | --- |
| <video src="https://github.com/WordPress/gutenberg/assets/6917969/f51c151c-16aa-4f63-8eca-a684009acae1"></video> | <video src="https://github.com/WordPress/gutenberg/assets/6917969/285b28a8-84fd-46bb-8b72-1e6a27066b4a" ></video> |

### CODE REVIEW

**Comment by luisherranz** [comment]
I'm not convinced yet about either of these. I think we need to review it more carefully.

**Comment by DAreRodz** [comment]
> I'm not convinced yet about either of these. I think we need to review it more carefully.

@luisherranz, what exactly doesn't convince you? 

- a) the`beforeRender` API
- b) the code that shows the animation
- c) the animation itself
- d) the code to enable the smooth scrolling
- e) all of the above

A little more feedback would be great. 😄

PS: I'm turning this back to draft, just in case.

**Comment by luisherranz** [comment]
I'm not convinced about the API (although that's not critical because it's not public), and the animation doesn't feel right. It's not your fault, it's just that I'm not sure whether it adds value to the navigation or not. My inclination is that it doesn't and needs more experimentation. The smooth scroll is nicer, but it doesn't work in Safari and Firefox ([although it should?](https://caniuse.com/?search=scroll-behavior)) so that needs more experimentation. In general, it feels a bit rushed to fit all this in today's Beta 1.

**Comment by DAreRodz** [comment]
> [...] the animation doesn't feel right.

TBH, I had the same feeling. 🙁  I think it's because the smooth scroll happens simultaneously, so you can barely notice the animation. When there's no scroll, it feels a bit nicer.

> The smooth scroll is nicer, but it doesn't work in Safari and Firefox.

That's bad. I wasn't aware, but it looks like `Element.focus()` doesn't respect the specified `scroll-behavior`. It works though with `Element.scrollIntoView()`, but that would force us to replicate the `focus()` scroll logic programmatically.

**Comment by jasmussen** [comment]
Thank you for taking a stab at this! I would echo Luis, in a direct comparison between these two, I'd prefer _no animation_, but I think we can tweak things so it works. 

Reading into the term "kansei", I'm sensing that captured in that aesthetic sensibility is a need to think about the fuller flow, not just the particular properties of the animation. In that sense, it is good to think through said flow:

* You view a queried list
* You scroll down, past the top of the list, and see pagination
* You click the pagination, and focus is moved to the top of the list prompting the browser to scroll there.

If that is the fuller flow, to realize a good experience we could potentially look at every step of the way:

* The time that passes after clicking "next page"
* The easing in and out of the animation, as well as the duration
* The amount of "overshooting" of the scroll
* The type of animation, as well as duration, of items in the queried list
* Ensure there are never any jarring jumps in height of items. I

Pursuant to what's possible, we might try to string all those properties together in one of two ways:

**Slow version**

* When clicking "Older posts", don't immediately start the animation, instead start the query list animation. Spend maybe 0.4s, perhaps longer, by fading out existing posts, then fading in the new ones. 
* If the query list needs to change height, let that height animation happen at the same time as the new items fade in. Always ease both in and out so it feels smooth. 
* Maintain focus on the "Older posts" button at least until the final _height_ of the previous posts in the list is calculated and the animation there is completed. By maintaining focus there for a brief moment, we also enable the use case where you want to rapidly click in succession to go to a much older page, perhaps looking at the URL to see which number you're pacing to. 
* Then start scrolling up. Ease in and out, and scroll slowly so the acceleration doesn't feel jarring or jumpy. Can be a long slow animation, perhaps a whole second or more.

**Fast version**

If the slow version above ends up feeling annoying, try the same recipe, but speed up every value so it's _faster_ than what's demoed in the video on this PR. Virtually instant, but just _considered_ (as per the recipe), and _eased_ instead.

Hope that helps!

**Comment by pablohoneyhoney** [comment]
Nice try. I agree it isn't ideal. I do wonder (and was the intent when mentioned) if it's simply a slight fade in between pagination, no scrolling up.

**Comment by DAreRodz** [comment]
Thanks for the feedback, @jasmussen and @pablohoneyhoney. 🙏

> simply a slight fade in between pagination, no scrolling up.

I want to try this first, as it seems simpler to develop. Just to clarify―when you say _no scrolling up_, you mean disabling the smooth behavior rather than not scrolling at all, is that right?

**Comment by Poliuk** [comment]
>  I do wonder (and was the intent when mentioned) if it's simply a slight fade in between pagination, no scrolling up.

I've been discussing it with @luisherranz, and we are afraid that removing the scrolling will break the a11y. In case, I've asked @DAreRodz to do a pair programming session with a designer so they can try different approaches synchronously and hopefully land a solution quickly :)

**Comment by jasmussen** [comment]
To understand, focus is moved from the "Oldest" to the top of the query block, just like it would if it was a full page refresh. Correct? To that end, I think Pablo's point that the query itself could have a simple fade in, and just immediately _jump_ (no animation on scrolling) depending on the browsers focus behavior. 

If I'm not wrong, then in cases where the whole query is visible, there would be no scrolling.

**Comment by luisherranz** [comment]
> focus is moved from the "Oldest" to the top of the query block, just like it would if it was a full page refresh. Correct?

Yes. Well, it's not exactly as a full page refresh because, as you say, the focus is moved to the first clickable element of the Query block instead of the first clickable element of the page (which is a better experience in terms of accessibility).

So the focus goes from the link you just clicked to the first clickable element of the Query block.

> If I'm not wrong, then in cases where the whole query is visible, there would be no scrolling.

Exactly. Scrolling is 100% handled by the browser. Each browser does a slightly different thing, but in general they ensure that the new focused element (the first clickable element of the Query block) is visible.

**Comment by DAreRodz** [comment]
This is the latest feedback I received from @jasmussen:

- Don't change the scrolling behavior―it's handled by focus― and don't animate it.
- Add a subtle fade between items in the query loop. I.e. fade out, then fade in items.

Given that, I removed any motion from both the scrolling behavior and the fade-out/in animations. The scroll position changes when the fade-in animation starts, so it feels like the Query Loop items are appearing already in their place.

Also, now that there is no motion at all, I got rid of any code related to `reduced-motion` support.

I think it's better now. 🙂 

| Safari | Firefox | Chrome |
| --- | --- | --- |
| <video src="https://github.com/WordPress/gutenberg/assets/6917969/1f61223a-39e2-4017-95f9-805d5cb86aca"></video> | <video src="https://github.com/WordPress/gutenberg/assets/6917969/d6a59b41-4062-45a8-9f70-fac7f45d1a5c"></video> | <video src="https://github.com/WordPress/gutenberg/assets/6917969/3315d279-4860-41c0-beb6-14b2cbd4c33a"></video> |

cc: @luisherranz @Poliuk

**Comment by jasmussen** [comment]
Agreed, that is a better experience. In general if an animation doesn't feel right, it's usually best to omit it. 

It's a bit frustrating how the three browsers entirely diverge in their handling of focus-scroll, but I'm assuming this is something best left entirely untouched, correct?

What happens to the fade if the next items in the query need to load?

**Comment by DAreRodz** [comment]
> What happens to the fade if the next items in the query need to load?

The fade-out animation is triggered when the data is ready before updating the HTML. The new HTML is updated once the fade-out has finished, and the fade-in animation starts right after.

So, in answer to your question, the transition should only be visible once the following items are ready. In the meantime, you can see the loading top bar progressing, so you still have feedback that the browser is waiting for the following items.

**Comment by luisherranz** [comment]
After more thinking, I'm opposed to this change.

It doesn't make sense to me to introduce imperative APIs to control the `navigate` that we would have to maintain indefinitely when it's so clear that the final solution will be declarative and will use the View Transitions API.

So, in my opinion, we should keep investigating how to control the View Transitions API using directives, and how to grant that control to the themes so they can override the block defaults ([View Transitions discussion](https://github.com/WordPress/gutenberg/discussions/53063)).

**Comment by DAreRodz** [comment]
I'm setting this PR to draft again, as we won't include these changes for now.

**Comment by DAreRodz** [comment]
Changing the type of the PR to "experimental" and closing it. We can revisit these changes in the future if needed. 🙂

**Pull request closed without merging**
