### PR TITLE
Fix: Remove font weight on toolbar tab button - #61254

### PR DESCRIPTION
**Pull request by hbhalodia**
## What?

- Issue - https://github.com/WordPress/gutenberg/issues/61254

## Why?

- This PR would resolve the consistency of the font-weight in the block toolbar.

## How?

- This PR removes the specifically adding the `Font Weight - 500` to the `Custom HTML` block toolbar.

## Testing Instructions

- Open the site.
- Edit any page
- Add the `Custom HTML` block
- Inspect the Toolbar Button `HTML and Preview`, you can see the font weight is now 400.

### Testing Instructions for Keyboard

- NIL

## Screenshots or screencast 

- Before 
Screenshot 2024-05-02 at 12 18 40 PM

- After

Screenshot 2024-05-02 at 12 17 35 PM

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

This PR makes sense to me, but I would suggest further improvements.

These two buttons on the HTML block toolbar are the only elements with the CSS class `.components-tab-button`. Additionally, this CSS class applies styles to the internal `span` elements, but these two buttons do not have `span` elements.

In other words, you should be able to delete everything below.

https://github.com/WordPress/gutenberg/blob/8cf7f3436021e6766e1be60b739d561fb525410e/packages/components/src/toolbar/toolbar/style.scss#L92-L102

https://github.com/WordPress/gutenberg/blob/8cf7f3436021e6766e1be60b739d561fb525410e/packages/block-library/src/html/edit.js#L48

https://github.com/WordPress/gutenberg/blob/8cf7f3436021e6766e1be60b739d561fb525410e/packages/block-library/src/html/edit.js#L55

**Comment by hbhalodia** [comment]
Thanks @t-hamano, I would make the changes asap.

**Comment by jasmussen** [comment]
Good PR 👍 👍

**Comment by hbhalodia** [comment]
Hi @t-hamano, I have reworked on the PR and updated it based on your inputs.

Thank You.

**Review by t-hamano — APPROVED** [review]
LGTM! Thanks for the update.

Before:

before

After:

after

Normally we would need to update [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md) when changes are made to the `components` package, but for this PR we're just removing styles that are no longer in use, so I think we don't need to.

**Pull request merged**
