### PR TITLE
Just trying to measure impact

### PR DESCRIPTION
**Pull request by youknowriad**
Don't merge

### CODE REVIEW

**Comment by gziolo** [comment]
Impressive difference 😃

Can you run another test targeting ES Modules? That should be fun to observe!

**Comment by youknowriad** [comment]
> Can you run another test targeting ES Modules? That should be fun to observe!

What do you mean?

**Comment by gziolo** [comment]
In https://github.com/browserslist/browserslist#full-list, there is `supports es6-module` which would be all browsers that support all the latest syntax and don't require too much transpilation.

**Comment by youknowriad** [comment]
I think support es6-module is not that different from the results here, these browsers should support es6 modules IMO

**Comment by priethor** [comment]
To prepare for the IE support drop post in make.wordpress.org, I've summarised the size changes taking into account only JavaScript files:

Filename|Size (kB)|Change (B)|Variation (%)
-|-|-|-
build/a11y/index.js|1.12|-24.00|-2%
build/annotations/index.js|2.94|-870.00|-29%
build/api-fetch/index.js|2.41|-1034.24|-41%
build/autop/index.js|2.28|-556.00|-24%
build/blob/index.js|0.66|7.00|1%
build/block-directory/index.js|6.90|-1873.92|-26%
build/block-editor/index.js|115.00|-13721.60|-11%
build/block-library/index.js|141.00|-8878.08|-6%
build/block-serialization-default-parser/index.js|1.30|-579.00|-44%
build/blocks/index.js|46.20|-1986.56|-4%
build/components/index.js|161.00|-10752.00|-6%
build/compose/index.js|9.45|-1372.16|-14%
build/core-data/index.js|11.00|-4505.60|-40%
build/data-controls/index.js|0.80|-8.00|0%
build/data/index.js|7.54|-1474.56|-19%
build/date/index.js|31.80|-13.00|0%
build/deprecated/index.js|0.71|-46.00|-6%
build/dom/index.js|4.35|-606.00|-13%
build/edit-navigation/index.js|8.04|-3174.40|-38%
build/edit-post/index.js|302.00|-4014.08|-1%
build/edit-site/index.js|21.10|-3440.64|-15%
build/edit-widgets/index.js|21.50|-4945.92|-22%
build/editor/index.js|38.40|-4986.88|-12%
build/element/index.js|3.44|-1218.56|-34%
build/escape-html/index.js|0.72|4.00|0%
build/format-library/index.js|5.66|-1095.68|-18%
build/hooks/index.js|1.75|-519.00|-29%
build/html-entities/index.js|0.61|5.00|0%
build/i18n/index.js|3.23|-333.00|-10%
build/is-shallow-equal/index.js|0.69|13.00|1%
build/keyboard-shortcuts/index.js|1.65|-888.00|-53%
build/keycodes/index.js|1.41|-523.00|-37%
build/list-reusable-blocks/index.js|2.04|-1085.44|-52%
build/media-utils/index.js|3.05|-2324.48|-74%
build/notices/index.js|1.07|-780.00|-72%
build/nux/index.js|2.30|-1146.88|-48%
build/plugins/index.js|1.66|-890.00|-53%
build/primitives/index.js|1.03|-394.00|-38%
build/priority-queue/index.js|0.77|1.00|0%
build/redux-routine/index.js|2.82|-19.00|0%
build/reusable-blocks/index.js|2.22|-707.00|-31%
build/rich-text/index.js|11.50|-1873.92|-15%
build/server-side-render/index.js|1.64|-1157.12|-68%
build/shortcode/index.js|1.68|-16.00|0%
build/token-list/index.js|0.83|-425.00|-50%
build/url/index.js|1.79|-1064.96|-58%
build/viewport/index.js|1.28|-574.00|-44%
build/wordcount/index.js|1.24|14.00|1%
**Total**|**993,58 kB**|**-85854 B (83.84 kB)**|**-7.78% (Mean variation: -24% per file)**

**Pull request closed without merging**
