### PR TITLE
Migrate Site Editor menu item to Theme Editor

### PR DESCRIPTION
**Pull request by jameskoster**
In a recent change we updated the Appearance > Widgets menu item to link to the new block-based widget management view. In this PR I am proposing we take a similar approach with the Appearance > Theme Editor item.

The "Site Editor" that we are building – at this stage – is essentially a block-based modernisation of the currently code-based Theme Editor. It enables users to edit their templates and styles (when Global Styles comes online). 

It is not 100% clear whether detailed _content_ editing will ever occur here, so calling this environment a "Site Editor" is a little misleading. I suspect that what many expect of the "Site Editor" is actually what the content editor will become, once we load the full template on the canvas in that environment. Initial [work](https://github.com/WordPress/gutenberg/pull/26355) has begun on that.

Before:

Screenshot 2020-11-11 at 12 19 03

After:

Screenshot 2020-11-11 at 12 18 14

### CODE REVIEW

**Comment by jasmussen** [comment]
The change seems fine to me, especially because it's still very beta. It's also an obvious place to look for it. 

Minor:

Screenshot 2020-11-13 at 13 30 52

The "beta" is sort of just hanging there — can/should it have a blob around it like it did in the main menu?

**Comment by jameskoster** [comment]
It looks like we've uncovered a bug in cores color schemes :) When the `.awaiting-mod` is in a sub menu it inherits the hover styles from the parent. With the default theme it works correctly:

Screenshot 2020-11-13 at 12 48 39

**Comment by jasmussen** [comment]
Awesome. Then it's actually my fault :) — I'll look into it.

**Comment by MichaelArestad** [comment]
It's a good idea. Definitely a better spot for now.

**Comment by Addison-Stavlo** [comment]
Im struggling to understand the reasoning behind the name change to "Theme Editor".  Its already adapted to customize Template and Template Part CPTs to be used for your site.  Creating and editing these aren't necessarily customizing your theme, and are not necessarily done for the purpose of theme building.  Similarly, with the removal of widgets and customizer when this is active and the desire for this editor to fill in that functionality it is destined to be more than a 'Theme Editor'.

> It is not 100% clear whether detailed content editing will ever occur here, so calling this environment a "Site Editor" is a little misleading.

If I understood @mtias comments in the past, the goal is to build the Site Editor around templates first to support block based theme building and to adapt it towards supporting content editing after that foundational work is in place?

The overall project has been "Full Site Editing", not "Theme Editing".  The package has been edit-site, not edit-theme.  This change in terminology seems like a large change in how we are viewing the projects scope.

**Comment by jameskoster** [comment]
> for this editor to fill in that functionality it is destined to be more than a 'Theme Editor'.

Without wanting to get too far in to the weeds, I do not think that is the case at all for _this_ editor specifically. Rather, this editor is for templates / template parts as you described, and in the (near 🤞) future Global Styles. Those features combined make up the bulk of what a theme is. I did consider calling it "Template Editor" instead, but that does not satisfactorily encompass the Global Styles element.

> the goal is to build the Site Editor around templates first to support block based theme building and to adapt it towards supporting content editing after that foundational work is in place?

That is exactly what we're doing. Just change the name "Site Editor" to "Theme Editor" for the reasons described above. Content editing will occur where it does currently, and once we begin rendering the template on the Canvas while doing so, the picture will become a lot clearer I think.

**Comment by Addison-Stavlo** [comment]
> Just change the name "Site Editor" to "Theme Editor" for the reasons described above.

While those reasons do make sense, I still think the term "Site Editor" is more fitting.  It can be used to edit aspects of your site such as the title, description, non-theme specific CPTs, etc.  While it is mostly geared around the Theme side at the moment, it still seems to make more sense to use a "Site Editor" as a tool to aid in theme building than to use a "Theme Editor" to manage any site specific data.

**Comment by youknowriad** [comment]
I must say I'm not really convinced by the name change here. When I hear Theme editor, I'd assume the theme files are going to be updated when I save changes and this is not really what this screen is about. Even without the name change, some one raised that he was confused that it didn't touch the files and I believe we should make it more confusing. Also as raised above, we update post content, site content, and any renderend entity basically, so it's not just about templates.

**Comment by Copons** [comment]
I would avoid replacing the code-based Theme Editor menu item.
Just because we are offering a (eventually) easier way to do things, we shouldn't remove a power user tool.
I have no idea how much the code-based editors (themes and plugins alike) are used IRL, but it has happened to me in the past to hotfix some urgent bugs while working on a proper solution.

As for the name, I've been using variants of "site editing" for like 2 years now, so my opinion is biased and would need to time to adjust.

**Comment by jameskoster** [comment]
> When I hear Theme editor, I'd assume the theme files are going to be updated when I save changes and this is not really what this screen is about.

That is a fair, albeit rather technical point. I'm not sure the average user would think this way, or be too worried either way if they did. I think that in general most folks understand that their 'theme' (regardless of whether that is files or database entries) governs how their site looks and is laid out at a high level, both of which are the chief focus of this editor.

> we update post content

The feedback I've heard is that editing content in the context of editing a template is confusing. _Viewing_ content (perhaps in a dedicated mode) would be useful, but editing at the same time is overwhelming. In order to walk before we run I also think that we might be better off not allowing post content to be edited here, but that's something to be explored in another issue.

**Comment by aristath** [comment]
Hmmm just my personal opinion here: The site editor is what it says: a "site" editor, not a "theme" editor.
It is used to not only edit the appearance but also the structure and content of all pages.
We can use the site editor to build menus, edit templates, change global styles, add blocks-as-widgets, add actual content, we can even build a single-page site without ever visiting any other place in our dashboard.
I don't think it fits under the narrow definition of a theme, it really is a **site** editor and handles a lot more than just the appearance.
My 2c: It should stay as is, called Site Editor and be a root-level item. It doesn't belong under appearance.

**Comment by carolinan** [comment]
I don't think theme editor is suitable name, it is the site that is being edited and not the theme files.

The users will not only use this to change theme settings, they may not even think of it as the theme. As they combine 
template parts in a way that is similar to how they combine blocks from plugins and block patterns, it is more similar to the current post editor, than it is to a theme editor.

**Comment by jameskoster** [comment]
Closing for now. We can revisit later.

**Pull request closed without merging**
