### PR TITLE
[RNMobile][Embed block] Fix bottom sheet link color in dark mode

### PR DESCRIPTION
**Pull request by ceyhun**
## Description

Fixes Embed block bottom sheet link color in dark mode

## How has this been tested?
- Switch to dark mode
- Add an embed block
- Press "Add link"
- Check the color of link in the bottom sheet with title `Learn more about embeds`
- Should be the same color as "Add link" button

## Screenshots 

Before | After
-- | -- 
before|after

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
Will go ahead and contribute a review from my side so Carlos can focus on other PRs for the embeds blocks 👍

**Comment by hypest** [comment]
👋 @ceyhun! Using the installable build from [this WPAndroid test PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15264), I see that the color is more bright than the "Before" case, but not the same as the "Add link" button (of the bottom sheet) you mention in the testing instructions. 

The new color is indeed better for dark mode, and light mode works perfect as well so, the PR looks great to me. Can you verify whether the "same as the Add link button" test should hold? Thanks!

screenshot-1630501111541

**Review by hypest — APPROVED** [review]
Changes look and work fine for me, so it's a LGTM for me! I've only left one [comment asking about the test against the "Add link" button color](https://github.com/WordPress/gutenberg/pull/34424#issuecomment-910266599).

**Comment by ceyhun** [comment]
> 👋 @ceyhun! Using the installable build from [this WPAndroid test PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15264), I see that the color is more bright than the "Before" case, but not the same as the "Add link" button (of the bottom sheet) you mention in the testing instructions.
> 
> The new color is indeed better for dark mode, and light mode works perfect as well so, the PR looks great to me. Can you verify whether the "same as the Add link button" test should hold? Thanks!

Thanks @hypest! I added that case based on the example image in a comment shared by @iamthomasbishop (_Internal reference p5T066-2Bq-p2#comment-9741_).

I thought they were the same, but now I checked and the "ADD LINK" button seems to be using the `blue-wordpress` color both in light and dark modes.

https://github.com/WordPress/gutenberg/blob/4ba37034eb26b44e6eae913fa6bbed4efb2b25ed/packages/block-library/src/embed/styles.native.scss#L58

I've tried using `blue-30` instead and this is how it looks:

blue-wordpress | blue-30
-- | -- 
before|after

But this change might mean changing it in other place as well, like Audio Block's `ADD AUDIO` button for example. I'm for merging this PR as it is right now and maybe creating an issue if we think this color change would be a good improvement. WDYT @iamthomasbishop, should we change the empty state buttons colors in dark mode?

**Comment by hypest** [comment]
> I'm for merging this PR as it is right now and maybe creating an issue if we think this color change would be a good improvement. 

+1 for merging since this PR does fix the basic issue of the color being too dark for dark mode.

**Pull request merged**
