### PR TITLE
add `minHeightUnit` to latest core/cover deprecation

### PR DESCRIPTION
**Pull request by flootr**
## Description

Add `minHeightUnit` attribute to latest deprecation of the `core/cover` block introduced in https://github.com/WordPress/gutenberg/pull/25171 (part of Gutenberg 9.8).

This missing property resulted in _invalidation_ of the Cover block when using custom units and upgrading from outdated markup.

Add tests for the regression.

```
Block validation: Block validation failed for `core/cover` ({name: "core/cover", icon: {…}, keywords: Array(0), attributes: {…}, providesContext: {…}, …}).

Content generated by `save` function:

<div class="wp-block-cover has-background-dim" style="min-height:71vw"><img class="wp-block-cover__image-background wp-image-7" alt="" src="[REDACTED]" style="object-position:61% 59%" data-object-fit="cover" data-object-position="61% 59%"/><div class="wp-block-cover__inner-container"></div></div>

Content retrieved from post body:

<div class="wp-block-cover has-background-dim" style="background-image:url([REDACTED]);min-height:71vw;background-position:61% 59%"><div class="wp-block-cover__inner-container"></div></div>
```

## How has this been tested?

In Gutenberg 9.7.4 create a post and add a `Cover` block. Set a background image and change the `minHeight` unit from the block settings to something different than `px` (e.g. `vw`). Copy that block and paste it into Gutenberg 9.8.2. You should see invalidations in the browser console and a broken UI for the block.

With this patch applied you should see valid block UI and a message in the console that the block had been updated successfully.

The new test should pass.

## Types of changes

Bug fix. `minHeightUnit` would otherwise be `undefined`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by sirreal** [comment]
Will you add a CHANGELOG entry [here](https://github.com/WordPress/gutenberg/blob/cae55258569348c22825ae461f5b0b335da24862/packages/block-library/CHANGELOG.md)?

**Review by sirreal — APPROVED** [review]
I've tested by creating a Cover block with 9.7.4 then upgrading Gutenberg to 9.8.2. I see the invalidations as described.

Then I installed the build from this PR and loaded the post. I see the block upgrade messages as described.

👍  Thanks @flootr!

Let's just wait for the newly added tests to pass then this looks ready to me.

**Comment by ockham** [comment]
This needs a rebase in order to pick up the latest fixes to PHP unit tests (which I've just promoted to 'required' :grimacing: )

**Comment by sirreal** [comment]
@ockham Rebased!

**Comment by ockham** [comment]
Thanks, this is looking good and appears to work well.

I _think_ that it might make sense to update the existing `packages/e2e-tests/fixtures/blocks/core__cover__deprecated-6.*` files rather than introducing `core__cover__deprecated-6-1.*`, since we're only modifying an existing deprecation, rather than adding a new one :thinking:

**Comment by sirreal** [comment]
> I _think_ that it might make sense to update the existing `packages/e2e-tests/fixtures/blocks/core__cover__deprecated-6.*` files rather than introducing `core__cover__deprecated-6-1.*`, since we're only modifying an existing deprecation, rather than adding a new one 🤔

I merged the test into the same file. I considered replacing the test, but the reality is that deprecations need to be tested with different inputs. As we observed here, the deprecation was tested but didn't cover all the cases. It seems to make sense to maintain the existing test and add more as we need to test the deprecation's behavior on different serialized content.

**Comment by ockham** [comment]
E2e test failures (because of FSE related things) seem to be unrelated (and have been present for a while :sweat: ). I'll merge, and will cherry-pick to both `release/9.8` and `release/9.9` (cc/ @nosolosw).

**Pull request merged**
