### PR TITLE
Fix editor crash when converting block with visible styles to reusable (after a save and page reload)

### LINKED ISSUE #27243: Converting Table block within a Group to reusable block causes Gutenberg editor to crash
**Describe the bug**
Gutenberg editor crashes when converting table within a group to reusable block

1. Add new post.
2. Add Group block.
3. Add Table block with any number of rows and columns within the Group block.
4. Save draft.
5. Return to Posts management page.
6. Reopen the draft.
7. Click on a table cell to bring up the toolbar.
8. Click on the kebab menu.
9. Click on Add to Reusable block.

**Expected behavior**
Table is converted into a reusable block.

Actual behavior
editor crashes (see stack trace below)

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: [e.g: 5.3.2] 5.5.3
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? "gutenberg plugin",
- If the Gutenberg plugin is installed, which version is it? 9.4.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser: not browser specific - reproed on chrome, safari and firefox

**Additional context**

Stack trace:
Error: An error occurred while running 'mapSelect': Cannot read property 'name' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'name' of null
    at Object.current (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:46:2298)
    at e (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:28762)
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:28927
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:23198
    at Array.forEach (<anonymous>)
    at o (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:23170)
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:20382
    at p (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:11415)
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=465b7310eb6f6a685e44cf8c6c5ce817:1:9762
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:14089

Original stack trace:
    at Fe (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/data/index.js?ver=152d217f4cbf8a22c88dc20c16e8d8c1:1:28554)
    at Qs (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=fdb8c27842d6665c8f717ab07efd9458:46:2160)
    at we (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at He (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:97:464)
    at zj (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:228:406)
    at Th (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    at tj (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    at Te (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    at https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://modern-eagle.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #27243.

This issue happens when a block with block styles is converted to a reusable block. But it only seems to happen if a post with a block is saved, reloaded, and then the block is converted. Strange.

The issue seems to be that the Block Inspector is still rendering the converted block momentarily after it has been removed. This shouldn't happen, because the Block Inspector renders the selected block, and the block selection is updated as part of the process of converting to a reusable block. Most of the block inspector doesn't seem affected by rendering a removed block (seems like it's not being re-rendered), but the block styles do throw an error if the block doesn't exist, perhaps because they do their own `useSelect` call.

In the process of fixing this I changed `BlockInspector` to use `withSelect`.

## How has this been tested?
I've added an end to end test, which fails on `master`.

Manual steps
1. Add a quote block
2. Save the post
3. Reload the page
4. Ensure the block sidebar is visible
5. Select the quote block, block styles should be shown in the sidebar.
6. Convert the block to reusable

Expected: The block should be converted.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
Ok - I discovered that while my change fixed the problem I was trying to address, I'd made a mistake and introduced other bugs (thanks tests).

I'll need to revisit this and find another way.

**Comment by talldan** [comment]
This should be ready for review now, fixed by adding some extra guarding around the rendering of block styles.

**Comment by youknowriad** [comment]
yeah, that's the redux zombie bug, I thought we had it covered in useSelect (with the try/catch but maybe not in some cases)

**Comment by youknowriad** [comment]
These things are very hard to debug, ideally the parent component should rerender first hide the whole inspector before the sub components and the "try  catch" in useSelect is meant to actually catch these potential rerender issues when the child rerenders first. 

That said, I'm not sure I can provide more value, than an explanation of what's happening so I'm fine with the fix as is. It's a stop gap fix though and it can happen again if a new component is added there for instance. So the test is a very good addition. Thanks.

**Review by youknowriad — APPROVED** [review]

**Comment by talldan** [comment]
Thanks for reviewing. I'll try to find out why the new test is failing. Hopefully it will just be a case of making it more robust.

**Comment by youknowriad** [comment]
This issue #29498 is also a zombie bug problem, I wonder if the current PR has an impact there.

**Comment by talldan** [comment]
It doesn't seem to affect #29498 (nav links don't have styles), but I also couldn't reproduce that one against the latest code in `trunk`.

**Pull request merged**
