### PR TITLE
Quality: Promote lint rule to error when validating store string literals

### LINKED ISSUE #27088: Code quality: Replace hardcoded store keys with store definitions
## Description

With #26655 it's possible to use store definitions as param for `select`/`useSelect`/`withSelect` and `dispatch`/`useDispatch`/`withDispatch` API method calls exposed from `@wordpress/data`. It resolves the issue with the need to use unscoped import statements for packages that define stores used as explained in https://github.com/WordPress/gutenberg/issues/8981#issuecomment-717397733:

> To be clear, all packages that use a given datastore should import it in the entry point by convention. It's something that could be improved because if it's missed, it might indeed cause errors. At the moment, there is no simple way to validate it happens. Example:
> https://github.com/WordPress/gutenberg/blob/87fa5f58534281aadd9bdf624f9b8384cfe66c89/packages/edit-post/src/index.js#L4-L10

The next step is to use newly exposed `store` definitions from the corresponding packages similar to how it was applied to the `store` exposef from `@wordpress/viewport` in #26655. Example:

```diff
diff --git a/packages/interface/src/components/complementary-area/index.js b/packages/interface/src/components/complementary-area/index.js
index 56ad63c601e1..f35fcf9d14bc 100644
--- a/packages/interface/src/components/complementary-area/index.js
+++ b/packages/interface/src/components/complementary-area/index.js
@@ -11,6 +11,7 @@ import { useDispatch, useSelect } from '@wordpress/data';
 import { __ } from '@wordpress/i18n';
 import { check, starEmpty, starFilled } from '@wordpress/icons';
 import { useEffect, useRef } from '@wordpress/element';
+import { store as viewportStore } from '@wordpress/viewport';
 
 /**
  * Internal dependencies
@@ -104,10 +105,8 @@ function ComplementaryArea( {
 				isActive: _activeArea === identifier,
 				isPinned: isItemPinned( scope, identifier ),
 				activeArea: _activeArea,
-				isSmall: select( 'core/viewport' ).isViewportMatch(
-					'< medium'
-				),
-				isLarge: select( 'core/viewport' ).isViewportMatch( 'large' ),
+				isSmall: select( viewportStore ).isViewportMatch( '< medium' ),
+				isLarge: select( viewportStore ).isViewportMatch( 'large' ),
 			};
 		},
 		[ identifier, scope ]
```

The goal is to make it simpler to maintain dependencies between packages to avoid bugs when consuming from npm. The other benefit is that we will prevent cyclic dependencies in the early stages of development.

### Tasks

This is the list of store names that should be replaced with their newly introduced store definitions:

- [x] `core`
- [x] `core/annotation` (#28156 @rafaelgalani)
- [x] `core/block-directory` (#27178 @rafaelgalani)
- [x] `core/block-editor`
- [x] `core/blocks` (#27336 @rafaelgalani )
- [x] `core/data`
- [x] `core/edit-navigation` (#27182, #27281 @rafaelgalani)  
- [x] `core/edit-post` (#27414 @rafaelgalani)
- [x] `core/edit-site` (#28695 @david-szabo97)
- [x] `core/edit-widgets` (#28044 @rafaelgalani)
- [ ] `core/editor`
- [x] `core/interface` (#28041 @rafaelgalani)
- [x] `core/keyboard-shortcuts` (#27355 @bosconian-dynamics)
- [x] `core/notices` (#27548 @gziolo)
- [x] `core/reusable-blocks` (https://github.com/WordPress/gutenberg/pull/27094 @grzim)
- [x] `core/rich-text` (#27820 @rafaelgalani)
- [x] `core/viewport` (@gziolo)

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Fixes: #27088.

This is the last step to replace hardcoded store keys with store definitions. This PR promotes `@wordpress/data-no-store-string-literals` ESLint rule to the error level.

## How has this been tested?

`npm run lint-js -- --quiet`

## Types of changes

Code quality.

### CODE REVIEW

**Comment by gziolo** [comment]
There is still 6 errors to fix:

```
/Users/gziolo/Projects/gutenberg/packages/block-library/src/categories/edit.js
  30:9  error  Do not use string literals ( 'core/data' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

/Users/gziolo/Projects/gutenberg/packages/block-library/src/embed/edit.js
  67:8  error  Do not use string literals ( 'core/data' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

/Users/gziolo/Projects/gutenberg/packages/core-data/src/selectors.js
  43:10  error  Do not use string literals ( 'core/data' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

/Users/gziolo/Projects/gutenberg/packages/edit-post/src/components/header/fullscreen-mode-close/index.js
  27:10  error  Do not use string literals ( 'core/data' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

/Users/gziolo/Projects/gutenberg/packages/editor/src/components/post-publish-panel/prepublish.js
  36:9  error  Do not use string literals ( 'core/data' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

/Users/gziolo/Projects/gutenberg/packages/server-side-render/src/index.js
  19:8  error  Do not use string literals ( 'core/editor' ) for accessing @wordpress/data stores. Pass the store definition instead  @wordpress/data-no-store-string-literals

✖ 6 problems (6 errors, 0 warnings)
```

I figured out that `core/data` is from `@wordpress/data` package but the store isn't exposed there. @youknowriad is it something we want to keep internal? What would be an alternative to call `isResolving` or `invalidateResolution`?

Screen Shot 2021-06-09 at 11 07 42


`@wordpress/server-side-renderer` doesn't depend on `@wordpress/editor` at the moment. Do we want to keep it that way? What would be the alternative approach there?

https://github.com/WordPress/gutenberg/blob/8d5139de3f1da2eec6b6923eabefa6450cb977cd/packages/server-side-render/src/index.js#L19-L20

It's worth noting that `@wordpress/block-library` depends on `@wordpress/editor` which is something we were trying to avoid:

https://github.com/WordPress/gutenberg/blob/8d5139de3f1da2eec6b6923eabefa6450cb977cd/packages/block-library/package.json#L49

I see it used with the following blocks:
- Calendar
- Table of Contents
- Template Part

**Comment by gziolo** [comment]
@youknowriad, is https://github.com/WordPress/gutenberg/pull/32537/commits/974557a59be807804d43ce54b2f66e48fb6acea8 correct? I would appreciate your guidance here.

**Comment by youknowriad** [comment]
@gziolo that commit looks correct to me 👍

**Comment by gziolo** [comment]
> `@wordpress/server-side-renderer` doesn't depend on `@wordpress/editor` at the moment. Do we want to keep it that way? What would be the alternative approach there?

It looks like it only needs to provide the current post id when in the context of the post type editor as introduced in https://github.com/WordPress/gutenberg/pull/9323. It looks like something that could be read from the context rather than through the selector.

**Comment by gziolo** [comment]
In https://github.com/WordPress/gutenberg/pull/32537/commits/58aab250eb04d8465fbf9a0e5c8ac1af0a8a8450 I took a similar approach to #32801 and the check go disabled. It requires a more generic approach that should be explored separately.

**Pull request merged**
