### PR TITLE
Title Bar shifts when switching between saved and save

### LINKED ISSUE #52295: Title Bar shifts when switching between saved and save
### Description

When using 6.3 beta 3, I found it really distracting that, if the save status changes, the title bar shifts unexpectedly. In my mind, there shouldn't be shifting and it distracts from the overall refinement of the experience.

### Step-by-step reproduction instructions

1. Open the Site Editor
2. Edit the home template
3. Open styles > typography > text
4. Change the font and then change it back to original font selection. Notice the title bar shifts.

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/26996883/274dffda-b30a-421b-a95e-853f1fcf043c

### Environment info

- WP 6.3 Beta 3
- TT3
- No GB

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by n2erjo00**
## What?
Removed `Saved` string from components button text/aria-label

## Why?

Fixes #52295 

## Testing Instructions

Check the original issue how to replicate the problem but observe now how button width remains the same and layout of header does not shift.

### CODE REVIEW

**Comment by jameskoster** [comment]
Thanks for the pull request. Unfortunately I don't think this solution will cover other languages where "save" and "saved" can be varying lengths. Did you have any other ideas?

**Comment by Mamaduka** [comment]
@jameskoster, maybe we should drop different label text; let the button's disabled state and snackbar communicate the saved state?

**Comment by jameskoster** [comment]
Yes I considered that, but I seem to recall the label change being an a11y requirement. Perhaps @alexstine can confirm? 

Alex: would it be okay for the save button label to say "Save" (rather than "Saved") when the button is disabled?

**Comment by n2erjo00** [comment]
Agreed if we need to support every language version then button text cannot change. My (educated) guess would be that text changes because of accessibility. I think there was specific `aria-*` attribute for that (aria-busy, aria-loading something like that)

I think I have time time to do that upcoming weekend 

Edit: Then again changing aria-attributes or text might/is bit over-engineering. Toggling `disabled` attribute should be enough
☝️ Personal opinion

**Comment by alexstine** [comment]
Preventing the text change is okay but you need to handle this with ARIA. Remember the basics, if sighted people see a loading state, it should be communicated to screen readers.

The disabled attribute is not something that should be used here due to the focus issues. There is an experimental prop on the `Button` component that allows us to deal with this better.

**Comment by Mamaduka** [comment]
Thank you, @alexstine!

The "Save" button already communicates its state using the ARIA attributes, just like the "Publish" button in the post editor. So I think we should be safe just to change the text.

@n2erjo00, do you want to work on this?

**Comment by n2erjo00** [comment]
Yes I can 😁
I'll do this during next weekend

**Comment by n2erjo00** [comment]
What you think about the post editors Update button. It also has text change happening but it does not make header layout shift. Should we in the name of consistency use static text there too?


https://github.com/WordPress/gutenberg/assets/62872075/fc4d22b8-a7d6-4269-af27-e44b63b08c74

**Comment by jameskoster** [comment]
Possibly yes, but let's look into that one separately.

For this PR, your implementation will also affect the button states when previewing a theme. It would probably be better to update `getLabel()` instead of forcing the static value for all use cases.

**Review by Mamaduka — COMMENTED** [review]
I think we can just drop the `disabled` label string from the `getLabel` helper. You don't need to refactor it into multiple helpers.

The `label` and button text should be the same.

## Why
The `label` also renders the `aria-label` attribute, and it should match the text content of the button.

Usually, we would omit the label when a button has the text content, but it's needed here for the tooltip and consistency with other buttons.


## Example
```js
const getLabel = () => {
	if ( isPreviewingTheme() ) {
		if ( isSaving ) {
			return __( 'Activating' );
		} else if ( isDirty ) {
			return __( 'Activate & Save' );
		}
		return __( 'Activate' );
	}

	if ( isSaving ) {
		return __( 'Saving' );
	} else if ( defaultLabel ) {
		return defaultLabel;
	}
	return __( 'Save' );
};
```

**Comment by n2erjo00** [comment]
Removed the "Saved" string from the component. 

Note: header layout shifts when user hits "Save" since the text changes.

**Comment by carolinan** [comment]
Hi @n2erjo00 are you available to update the pull request with the latest changes from trunk, and make sure that the final playwright tests run (and pass).

**Comment by n2erjo00** [comment]
@carolinan Yeah I am here. I'll do updates during this week

**Comment by n2erjo00** [comment]
@carolinan Updated to latest trunk. I don't really remember where this was left before it went stale but looking forward of community input and to see where it goes 😄

**Comment by carolinan** [comment]
Hi @n2erjo00 - Unfortunately I was unable to follow up. Thank you for working on this issue and PR. The issue has been solved with a different pull request, so I will close this.

**Pull request closed without merging**
