### PR TITLE
[RNMobile] Added Audio block to the initial html 

### PR DESCRIPTION
**Pull request by jd-alexander**
## Description

A section was created with the File and Audio block in the initial HTML that is shown when the editor loads in debug mode. 

## How has this been tested?

1. Run the Gutenberg demo app. 
2. Notice that the metro server sets the editor's content from the initial HTML. 
3. Observe that the File block is no longer at the top above the "Welcome to Gutenberg" title. 

Before | After 
--------|-------
 <kbd></kbd>  |      <kbd></kbd>
 
4. Observe that the File and Audio block is rendered in the Media Section

 <kbd></kbd>

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
Tested on iOS and Android simulators with the demo app and it's looking good 👍 `React Native E2E Tests (iOS)` test had failed and I restarted it. I think it's not related to this PR and it's just flaky at the moment.

**Comment by jd-alexander** [comment]
> Tested on iOS and Android simulators with the demo app and it's looking good 👍 `React Native E2E Tests (iOS)` test had failed and I restarted it. I think it's not related to this PR and it's just flaky at the moment.

Thanks for the review 🙇  I saw the appium PR that would allow us to grab the log from the failed tests, so hopefully, that will assist with diagnosis.

**Comment by jd-alexander** [comment]
@ceyhun I just realized the https://github.com/wordpress-mobile/gutenberg-mobile/pull/3168 PR wasn't approved but I know it was probably due to the failing e2e test so we can determine next week if we are merging with the flaky test or if we want to get it resolved and then do merges 🙏

**Comment by ceyhun** [comment]
> @ceyhun I just realized the wordpress-mobile/gutenberg-mobile#3168 PR wasn't approved but I know it was probably due to the failing e2e test so we can determine next week if we are merging with the flaky test or if we want to get it resolved and then do merges 🙏

Oh, I think I just overlooked it, will look into it now, sorry about that 😅

**Pull request merged**
