### PR TITLE
Format Library: Refactor inline link component to use React hooks

### PR DESCRIPTION
**Pull request by aduth**
Related: #19440

This pull request seeks to refactor the inline link UI component (used for adding, viewing, and editing links in a RichText field) as a function component. Originally this was planned as a blocking change to allow for the implementation of additional custom React hooks to be used in this component as a resolution of #18755. This is planned to be addressed separately, and may ultimately not use hooks.

The changes here are intended to be a one-to-one port of the existing component, with the exception of the revisions mentioned at https://github.com/WordPress/gutenberg/pull/19440#issuecomment-571309612. I may plan to extract this (6523f57) as a separate pull request in order to simplify review.

**Testing Instructions:**

Verify there are no regressions in viewing, adding, editing, or removing a link.

### CODE REVIEW

**Comment by aduth** [comment]
> Originally this was planned as a blocking change to allow for the implementation of additional custom React hooks to be used in this component as a resolution of #18755. This is planned to be addressed separately, and may ultimately not use hooks.

See also: #19488, which is currently set to merge to this branch.

**Comment by ellatrix** [comment]
Looks like this will conflict with #19462. Any preference on what to merge first?

**Comment by ellatrix** [comment]
Ah, it looks like that PR is also rewriting the component with hooks.

**Comment by aduth** [comment]
> Ah, it looks like that PR is also rewriting the component with hooks.

Oof 😄 

(cc @youknowriad, I haven't looked closely enough to have a good sense on how to proceed)

**Comment by aduth** [comment]
I guess #19462 simplifies the implementation more, in that `LinkControl` handles most of the specific behaviors? I'd want to consider how this would impact #19488, but I suppose if it can be implemented at `LinkControl` instead, it would have the benefit of being more universal.

**Comment by aduth** [comment]
I think it's probably not worth continuing with this if the plan is to use `LinkControl` more consistently throughout the UI, like iterated in #19462.

**Pull request closed without merging**
