### PR TITLE
Gutenberg Plugin: Format all JSON files using Prettier formatter

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Related to #30240 where @ockham proposed we start formatting more types of files, other than JS files.

It's a result of executing:
`npx prettier --format **/*.json`

Let's see how it plays out in practice with CI checks.

## Known issue

See https://github.com/WordPress/gutenberg/pull/30714/checks?check_run_id=2321165368#step:9:6

`docs/manifest.json` file gets a different end of file when generated with `npm run docs:build`

### CODE REVIEW

**Comment by mkaz** [comment]
😲

**Review by mkaz — APPROVED** [review]
Quite a few files to review 😆 

It looks like most of the fixes are changes to the test fixtures and range parameters,, so those passing will be a good confirmation. Will the auto generated fixtures need to be updated?

I updated the manifest tool to include a new line when it generates, this clears up that error.

**Review by aristath — APPROVED** [review]

**Comment by gziolo** [comment]
> It looks like most of the fixes are changes to the test fixtures and range parameters,, so those passing will be a good confirmation. Will the auto generated fixtures need to be updated?

Good observation. It's hard to tell, but as long as we don't run checks on the formatting it's acceptable. I wanted to split efforts into smaller steps as much as possible.

**Comment by gziolo** [comment]
@mkaz, I tested `npm run fixtures:regenerate` with all the formatting applied and it looks like it uses different formatting so definitely something to look at:

Screen Shot 2021-04-13 at 10 45 25

It is not only `ranges` that is formatted differently but it also uses `spaces` for indentation ...

Filed as #30795.

**Pull request merged**
