### PR TITLE
E2e tests: merge Puppeteer into single job, split Playwright further

### PR DESCRIPTION
**Pull request by ellatrix**
## What?

The Playwright tests have been taking longer and longer (~20 mins), so it'd be good to add more jobs. Since there's still Puppeteer tests remaining, and other tests being added, this will only get worse over time, so I doubled the jobs.

Additionally, since the number of Puppeteer tests is greatly reduced, these test take barely any time anymore, so we can merge them all into one job I think. Again, over time, no tests should be left here.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I think we should also update the repo settings for required jobs. cc @talldan

**Comment by talldan** [comment]
> I think we should also update the repo settings for required jobs. cc @talldan

Unfortunately that can only be done after the PR has merged and the new jobs have successfully completed once on trunk.

At least that's how it was the last few times.

**Comment by talldan** [comment]
I'll go ahead and merge this, then update the required checks 👍

**Comment by ellatrix** [comment]
Thanks!

**Pull request merged**
