### PR TITLE
Feat: Update textControl to searchControl in taxonomy search.

### LINKED ISSUE #64593: Should sidebar "Search categories" filter be a SearchControl?
## What problem does this address?

The "Search categories" field in the Post sidebar uses a normal `TextControl` even though it's a search field.

Search categories input

https://github.com/WordPress/gutenberg/blob/8169dfd2c89b82ed39bb74be8063a715b467c184/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L409-L416

## What is your proposed solution?

@WordPress/gutenberg-design Should this be replaced with the `SearchControl` component, so it can signal that it's a search field, both visually and semantically? At the very least we should probably add back the `type="search"` attribute that seems to have been there in the past.

### PR DESCRIPTION
**Pull request by vipul0425**
## What?
Fixes: #64593 

## Why?
The "Search categories" field in the Post sidebar uses a normal TextControl even though it's a search field.

## How?
This PR updates the TextControl component to `SearchControl` in sidebar taxonomy search.

## Testing Instructions
- Create any post.
- View the post settings in Sidebar and in categories it should be SearchControl now instead of normal TextControl.

### CODE REVIEW

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think everything about the code is correct, let's get some design feedback.

| Before | After |
|--------|--------|
| image | image | 

There are visual changes to the field, but I think this is acceptable.

If changes are necessary, I think it would be better to improve it at the component level, as discussed in #56388.

**Comment by jasmussen** [comment]
I'd tend to agree with Aki 👍 👍

**Review by mirka — APPROVED** [review]
Looks good to me too 👍 The label is hidden by default on `SearchControl`, but it's still accessibly associated to the input. And with the placeholder and search icon, it's a lot visually clearer that this is a search input, even without the visual label. So I think we're good.

**Comment by t-hamano** [comment]
Thanks everyone for your feedback. Let's merge this PR now.

@vipul0425 Thanks for the great work!

**Pull request merged**
