### PR TITLE
Add transparent background in template part focus mode

### PR DESCRIPTION
**Pull request by kevin940726**
## Description

An alternative of https://github.com/WordPress/gutenberg/issues/35512. Based on this [design](https://github.com/WordPress/gutenberg/issues/35512#issuecomment-948426113).

Add a _transparent_ background to the template part focus mode.

## How has this been tested?

1. Activate `tt1-blocks` theme
2. Go to Site Editor
3. Edit a template part by going to the focus mode
4. Observe the _transparent_ background

## Screenshots 

https://user-images.githubusercontent.com/7753001/138389167-24d0fd50-e1bd-44af-a7e4-056c4b9cfe28.mp4

## Types of changes

New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jameskoster** [comment]
I'd be curious to get feedback from other designers around what works best here.

### Outline
Screenshot 2021-10-22 at 10 05 26

### Fill
Screenshot 2021-10-22 at 10 05 43

### "Transparent" texture
Screenshot 2021-10-22 at 10 07 25

The transparent texture feels like overkill in many situations, but comes in to its own when the template part has a background similar to the frame or the outline:


| Background matches the frame | Background matches the outline |
| --- | --- |
| Screenshot 2021-10-22 at 10 13 38 | Screenshot 2021-10-22 at 10 19 40 |


---

@kevin940726 would it be possible to apply the body background color from theme.json to the body in the iframe? Otherwise it will inherit the default white which can produce incorrect results like this:

Screenshot 2021-10-22 at 10 16 44

**Comment by javierarce** [comment]
@jameskoster: 
 
 > I'd be curious to get feedback from other designers around what works best here.

+1 to the transparent texture. As you pointed out it has the best overall contrast of all the options, and it also looks good.

**Comment by jameskoster** [comment]
@kevin940726 for a comparison, would it be possible to try a version where the height wraps the content regardless of the device preview?

**Comment by jameskoster** [comment]
Then we can disable the device preview in this view (the drag handles allow people to try different sizes), with a view to implementing something like @shaunandrews worked on for Patterns:

Screenshot 2021-10-22 at 16 47 24

**Comment by kevin940726** [comment]
Close in favor of #35974.

**Pull request closed without merging**
