### PR TITLE
Post Author / Post Excerpt - change editor selector class

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Changes the block selector used in the editor.scss from `wp-block` to `block-editor-block-list__block`.  As noticed here:
https://github.com/WordPress/gutenberg/blob/d86cd5f0b36b3de3034096c09e0aaf7509367c4c/packages/block-editor/src/components/block-list/block.js#L148-L150

`wp-block` is only added when there is no block alignment set, while `block-editor-block-list__block` is always added to the wrapper.  While this does not create any problems for these blocks currently, it will prevent future conflicts if block alignment support is added.

## How has this been tested?

Test these blocks in the editor and verify that link colors change along with their selected color.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by Copons** [comment]
Not sure this is the best approach.
There might be a bug with the blocks themselves here, but I can't seem to find another block without light wrapper to double check.
The `.wp-block` class is a bit weird with light wrappers as well: when the block isn't aligned, `.wp-block` is on the "block" div (the one with all the classes and data-attributes); when the block is aligned, `.wp-block` is moved to a new div wrapping the block, which takes care of the alignment.

E.g.
```html
<!-- non aligned block -->
<div class="wp-block wp-block-post-author" data-type="core/post-author"></div>

<!-- aligned block -->
<div class="wp-block" data-align="center">
  <div class="wp-block-post-author" data-type="core/post-author"></div>
</div>
```

I'd rather suggest we turn these block as light wrapper to be more consistent with pretty much all other Core blocks, and then we might be able to simplify the CSS selector like this:
```diff
- .wp-block[data-type="core/post-author"].has-link-color .wp-block-post-author a {
+ .wp-block-post-author.has-link-color a {
```
(Unless we need more specificity, but I hope we don't! 🙂 )

**Comment by ockham** [comment]
Agree with @Copons :slightly_smiling_face:

**Comment by Addison-Stavlo** [comment]
This choice of selector in the editor is not out of the ordinary, and is used in blocks using the light block wrapper as well:

https://github.com/WordPress/gutenberg/blob/24c6114df4ff3fd18c34fa258a42f1130577f915/packages/block-library/src/paragraph/editor.scss#L2

^^ Even the paragraph block uses this selector for styles in the editor.

**Comment by Copons** [comment]
@Addison-Stavlo Got it!
Then I'm cool with the quick fix. 🙂

**Review by Copons — APPROVED** [review]

**Pull request merged**
