### PR TITLE
Writing Flow: fix list selection

### LINKED ISSUE #12656: Can't select all list items with Shift + up arrow without selecting previous block
**Describe the bug**

In WordPress 5.0, given a list of at least 4 items in a list block, if I try to select all of those items with CMD + Shift + Left arrow and then Shift + Up arrow, all of the items except for the first can be selected as expected. As soon as I type Shift + Up arrow for the last item, the selection skips and becomes a multi-block selection.

**To Reproduce**
1. Add a paragraph block
2. Add a list block
3. Type 4 or more list items
4. Place cursor at the end of the last list item
5. Type CMD + Shift + Left arrow (OSX) to select all text in the last item
6. Type Shift + Up arrow to add the above list item to the selection
7. Repeat

**Expected behavior**

I expect to be able to select each list item in the block so that I can copy/cut or otherwise manipulate the text.

**Screenshots**

list-item-select

**Desktop (please complete the following information):**
 - OS: Mac OS 10.12.6
 - Browser: Chrome
 - Version:  70.0.3538.110

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #12656.

The problem is that we're looking at a collapsed range when determining if a range is at the vertical edge of an element.

Added an e2e test.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by aduth** [comment]
>The problem is that we're looking at a collapsed range when determining if a range is at the vertical edge of an element.

It's not immediately clear to me: Why does this make a difference? Or, to refresh my memory, why do we collapse the selection at all in this function?

**Comment by aduth** [comment]
I sorta wondered if this might have had something to do with an issue I've experienced in Chrome when dealing which occur at ends of lines as (unexpectedly) reporting to have dimensions on the following (preceding?) line:

https://codepen.io/aduth/pen/WPjQoW

This can happen a lot in our implementation when trying to <kbd>ArrowDown</kbd> after clicking at the end of a line of text. If the line is the second-to-last in a paragraph, it can often skip to the next block unexpectedly.

But I tested the original issue in Firefox (where this bug/inconsistency does not exist) and it works correctly ¯\\_(ツ)\_/¯

**Comment by ellatrix** [comment]
We seem to collapse it for this calculation:

https://github.com/WordPress/gutenberg/pull/19721/files#diff-09079d098673dd8130aa10e0f430a939R115-R123

And also for the horizontal edge calculation, in which case we want the left/right edge of the collapsed range, not the range as a whole (which can change if multiple line are selected).

**Comment by ellatrix** [comment]
@aduth That's correct. I'm aware of the Chrome issue where it selection an invisible bit of the side of the first line. I'm unsure how to account for this. When taking the rectangle of the original range, the rectangle seems to be correct, so that's why I used it instead.

**Comment by ellatrix** [comment]
I made an error when writing the e2e test and now it works fine.

**Comment by aduth** [comment]
There was a failing test. Not one of the usual failures, but doesn't seem like it should be related:

```
FAIL packages/e2e-tests/specs/editor/plugins/inner-blocks-allowed-blocks.test.js (12.198s)
  Allowed Blocks Setting on InnerBlocks 
    ✓ allows all blocks if the allowed blocks setting was not set (4083ms)
    ✓ allows the blocks if the allowed blocks setting was set (3072ms)
    ✕ correctly applies dynamic allowed blocks restrictions (3413ms)
  ● Allowed Blocks Setting on InnerBlocks  › correctly applies dynamic allowed blocks restrictions
    expect(received).toEqual(expected)
    Difference:
    - Expected
    + Received
      Array [
    -   "Gallery",
    -   "Video",
    +   "Image",
    +   "List",
      ]
      81 | 		expect(
      82 | 			await getAllBlockInserterItemTitles()
    > 83 | 		).toEqual( [
         | 		  ^
      84 | 			'Gallery',
      85 | 			'Video',
      86 | 		] );
      at Object.toEqual (specs/editor/plugins/inner-blocks-allowed-blocks.test.js:83:5)
          at runMicrotasks (<anonymous>)
```

I've restarted the build.

**Review by aduth — APPROVED** [review]
Tests well to me 👍

**Comment by ellatrix** [comment]
Thanks for the review!

**Pull request merged**
