### PR TITLE
Update mockups

### PR DESCRIPTION
**Pull request by jasmussen**
New batch of mockups with a bunch of tweaks.

- More contrast between active and inactive formatting buttons
- Updated Header mockup which lets you pick the size. This one looks a bit heavy handed, and needs more iteration. Ideas welcome.
- New mockup: Insert in between blocks using the keyboard
- Slightly adjusted Inserter, which refers to a curated "common" list of blocks, as opposed to "frequently used", as that messes with spatial muscle memory
- Updated mobile interface, which actually shows selection controls, which it didn't before.
- Updated Quote block which shows the ability to pick between several styles.

### CODE REVIEW

**Comment by aduth** [comment]
>Updated Quote block which shows the ability to pick between several styles.

Isn't the idea with the editor that we'll show only a rough approximation of how the quote would appear, but depend on the theme to provide the true styles for the front-end? If so, how would we expect quote styles to work?

**Comment by jasmussen** [comment]
> Isn't the idea with the editor that we'll show only a rough approximation of how the quote would appear, but depend on the theme to provide the true styles for the front-end? If so, how would we expect quote styles to work?

Really, really good question.

Multiple quote styles, regardless of theme, seems like a really solid improvement to the blockquote block, as suggested by @mtias. But your question speaks to an interesting chicken and egg sort of question — how do we ensure some connection between the theme and the quote style? I'm assuming the question will arise for other blocks as well. The heading is in a comparable situation, since the size of the heading is currently a subset of the "Heading" block.

I've been thinking of it as there being generally two styles of quotes. The _long_ quote, where you excerpt or quote other material. Then the more decorative quote, which is bigger, bolder and works better for smaller quotes. Is it enough that we establish these two as _archetypes_ (the 2nd gets a classname like `quote-decorative`)? Or do we need themes to be able to register their support for multiple quote types?

**Comment by aduth** [comment]
>Is it enough that we establish these two as archetypes (the 2nd gets a classname like `quote-decorative`)? Or do we need themes to be able to register their support for multiple quote types?

I would imagine from a user's perspective, it would be quite confusing to try to use the alternate quote style only to not have it make any difference if the theme hasn't yet been updated to support it. Registering theme supports seems like a good option.

**Comment by mtias** [comment]
Yes, the alternate quote style would be what the quote-format now stands for. We could have standard core styles as a fallback if a theme is not doing anything with it, just like we do with galleries, captions, etc.

**Pull request merged**
