### PR TITLE
[RNMobile] Change mediaFiles from string to a dictionary

### PR DESCRIPTION
**Pull request by bjtitus**
## Description

Fixes an incorrect type in the `GutenbergBridgeDelegate` methods for the "media files" block (a.k.a. Stories).

See https://github.com/wordpress-mobile/WordPress-iOS/pull/15811
See https://github.com/wordpress-mobile/gutenberg-mobile/pull/3113

## How has this been tested?

1. Open a post containing a Story block.
2. Attempt to edit the story.
3. An error screen should not appear after this change has been made (nothing should happen when tapping the edit button).

<a href="https://user-images.githubusercontent.com/3250/106991383-57dc9900-6733-11eb-9c51-224211a556c7.png"></a>

I could not find a good place to add a unit test. Please let me know if there's a good way to programmatically test!

## Types of changes

This is a bug fix for delegate methods related to the "media files" Gutenberg block.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by etoledom** [comment]
@Guarani - could you take a look please? 🙏

**Comment by bjtitus** [comment]
@Guarani I just added you to https://bjttestsite12.wordpress.com in order to test this. There's only one post there which includes a story. You should just be able to open it in the app and try to edit that post.

The story editor hasn't been merged in to `develop` yet.

**Review by mzorz — APPROVED** [review]
This one looks good to me @bjtitus! the set of PRs needs updating with latest changes in the base branches

I'll let @guarani give the final word as an iOS dev :)

**Comment by bjtitus** [comment]
Checking the "code tested" checkbox although there are no unit tests for this. The bridge delegates are manually verified as a part of the release process for Mobile Gutenberg.

**Pull request merged**
