### PR TITLE
Refactor Picker and fix state update on an unmounted component

### LINKED ISSUE #1049: Media Picker - Warning - can't perform state update on an unmounted component
Notice the warning below when tried to upload a media in the wp-android app.

Screen Shot 2019-05-30 at 12 35 23

### PR DESCRIPTION
**Pull request by Tug**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1049

## Description
This PR refactors `Picker` as well as the way `Picker` is created in `MediaUpload` and `BottomSheetPickerCell`. Instead of calling a method on the element directly we switch to using a props to show and hide the modal. This pattern is much nicer and won't produce side effects such as methods being called while the component is unmounted.

## How has this been tested?
Use gutenberg mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/1054

## Types of changes
This is a refactor PR, no feature is added or removed.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by Tug** [comment]
So the main problem with https://github.com/wordpress-mobile/gutenberg-mobile/issues/1049 was that in the Image block (and Video block as well) we have either:
- [The `MediaPlaceholder` component rendered](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.native.js#L263) which has its own instance of `MediaUpload` and thus the Modal) when there is no media
- [`MediaUpload` rendered directly](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.native.js#L379) when a media is given.
This results in `MediaUpload` being at different places in the shadow dom tree which translates in a new instance being created (and thus the old one being unmounted)
The React Native Modal has animations and is not designed to be mounted/unmounted, instead it accepts a prop (`isVisible`) to toggle its visibility.
Thus the MediaUpload construct isn't fit to our need. I think it's fine to not use it though as `MediaUpload` is not a core component, just a helper.

**Review by etoledom — COMMENTED** [review]
>  I think it's fine to not use it though as MediaUpload is not a core component

This means that it's not a component that 3rd parties can use for their blocks, right?

In that case I agree that it's OK to not use it and have our own solution. This would mean also that we won't be able to have media blocks "multiplatform".

In my understanding, our previous implementation of `MediaUpload` was still a bit different from the web implementation. We were presenting all options to add media, while the web implementation is used to render the WP Media Library option (and the WP Media Library Picker interface).

Maybe in the future it might make more sense to implement a native version of `/media-utils/src/components/media-upload/index.js` that presents our native MediaPicker controller, as the web counterpart.

Now, this refactor is notoriously simpler, and thank you for fixing the `Picker` API :)
I had issues with the iOS ActionSheet being presented multiple times but I can't reproduce it now.

---

I did find a small issue. On iOS sometimes the Action Sheet won't show. These are the steps:

- Add a new empty Image block.
- Press on ADD IMAGE.
- Select `Choose from device`.
- Cancel the Photos picker.
- Press on ADD IMAGE again.
- Nothing will happen.

The same can be reproduced with an image block with content, using the pencil button.

**Comment by pinarol** [comment]
> I think it's fine to not use it though as MediaUpload is not a core component
> > This means that it's not a component that 3rd parties can use for their blocks, right?

I am a bit confused, if `MediaPicker` will be our private component then what will public version? Jetpack blocks are already using MediaUpload and MediaPlaceholder from multiple places so we'll need to provide sth really soon.

My worry is this PR is converting both `MediaUpload` and `MediaPlaceholder` into something very different from what web has. 

For example this is the usage before this PR:

Mobile version:

```
                    <MediaPlaceholder
                        mediaType={ MEDIA_TYPE_VIDEO }
                        onSelectURL={ this.onSelectMediaUploadOption }
                        icon={ this.getIcon( false ) }
                    />
```

Web version:

```          <MediaPlaceholder
                    icon={ <BlockIcon icon={ icon } /> }
                    onSelectURL={ this.onSelectURL }
                    allowedTypes={ ALLOWED_MEDIA_TYPES }  //actually same as mediaType except it is an array but this can be easily equalized
                />
 ```

But after this PR we'll need to do this to have the MediaPlaceholder, and we'll need to add MediaPicker separately every time we want to add a `MediaPlaceholder`:

```
			<MediaPlaceholder
					mediaType={ MediaPicker.MEDIA_TYPE_IMAGE }
					icon={ this.getIcon( false ) }
					onPress={ ( event ) => {
						this.props.onFocus( event );
						this.onMediaOptionsButtonPressed();
					} }
				/>

			onMediaOptionsButtonPressed() {
				this.setState( { showMediaOptions: true } );
			}

			<MediaPicker
				isOpen={ this.state.showMediaOptions }
				mediaType={ MediaPicker.MEDIA_TYPE_IMAGE }
				onSelectURL={ this.onSelectMediaUploadOption }
				onClose={ this.onMediaOptionsClose }
			/>
 ```

Isn't it possible to minimize this difference?

**Comment by Tug** [comment]
Closing given how old the PR is, will open a new PR if this is needed

**Pull request closed without merging**
