### PR TITLE
[Mobile] Cover block upload progress

### PR DESCRIPTION
**Pull request by mkevins**
## Description
This PR adds the `MediaUploadProgress` component to cover block. This adds a progress bar to the block to indicate the progress of ongoing uploads. It also updates the `id` and `url` of the media to the new server `id` and `url` upon upload completion.

#### Related PRs
* `gutenberg`
  * Enable uploads dev only: https://github.com/WordPress/gutenberg/pull/21196
  * Upload failure UI: https://github.com/WordPress/gutenberg/pull/21198
* `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2070
* `WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11541
* `WordPress-iOS`: https://github.com/wordpress-mobile/WordPress-iOS/pull/13769

## Testing steps
1. Add cover block to a post
2. Tap "Add Image or Video"
3. Tap "Choose from Device"
4. Pick an image to upload from your device

**Expected:**
1. The image should appear as a background to the block
2. A progress bar should display at the top of the image and update as the upload progresses
3. After the upload completes, the media url should be the server url (i.e. begins with `https:`, not `file:`)

## Screenshots

Progress bar | URL scheme
-|-
cover-upload-progress-bar | cover-upload-progress-html

## Additional changes

In order to ensure the progress bar was displayed on _top_ of the media, it was necessary to add a `z-index` to the `MediaUploadProgress` component's `progressBar` class: https://github.com/WordPress/gutenberg/commit/7f00459fac0559d1ae1c8bd09bf8089978be8520.

I also simplified a few other areas via optional chaining: https://github.com/WordPress/gutenberg/commit/5cd723e0d96002ffa1ce1872f9ea431bcb938b59.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by chipsnyder — APPROVED** [review]
LGTM

Tested on iOS and Android
I was able to add Images from the device on iOS and Android. Also tested taking images and video and those worked as well. 

Note:
I am getting validation errors if I back out during upload and come back in. I'm just mentioning it here to capture it; however, this would probably be handled in another phase. I can add more info here if this is unexpected.

**Comment by mkevins** [comment]
> Note:
> I am getting validation errors if I back out during upload and come back in. I'm just mentioning it here to capture it; however, this would probably be handled in another phase. I can add more info here if this is unexpected.

Indeed, this will be handled in another PR. Thanks for testing and reviewing!

**Comment by geriux** [comment]
Hey, @mkevins 👋 While reviewing I noticed some linting issues, I guess since this is not targeting `master` is not running the Travis checks.

```
[0]   198:22  error  'id' is already declared in the upper scope   no-shadow
[0]   199:17  error  'url' is already declared in the upper scope  no-shadow
```

And a few `prettier` warnings just FYI.

**Comment by geriux** [comment]
> I also simplified a few other areas via optional chaining: 5cd723e.

This is so cool! I didn't see this [PR enabling it](https://github.com/WordPress/gutenberg/pull/19831)! Cannot wait to try it :D

**Review by geriux — CHANGES_REQUESTED** [review]
https://github.com/WordPress/gutenberg/pull/21197#issuecomment-609715263

**Comment by mkevins** [comment]
Thanks for testing and reviewing!

**Pull request merged**
