### PR TITLE
Rename `core/text` to `core/paragraph`

### PR DESCRIPTION
**Pull request by nylen**
To make it clearer that the `Text` block is actually a single paragraph rather than a section of continuous text, we should rename it to `Paragraph`.

Split out from #1959, which also introduces a multi-paragraph text block (this PR does not).

To ease potential future rebases, most of the refactoring here was done in a semi-automated fashion using the following commands and the [`codemod`](https://github.com/facebook/codemod) tool:

```sh
git mv blocks/library/text/ blocks/library/paragraph/
cd blocks/test/fixtures/
for i in core__text__*; do git mv "$i" "core__paragraph__${i#core__text__}"; done
cd ../../..
rm -r */build/ coverage/
codemod --extensions js,html,json,php 'core/text(?!-)' 'core/paragraph'
codemod --extensions js "'\\./text'" "'./paragraph'"
# `git add` the changed files
```

### CODE REVIEW

**Comment by iseulde** [comment]
Sounds good to me!

**Comment by jasmussen** [comment]
I can understand the sentiment here — _call it what it is_. I can also understand why you'd want to make this change sooner rather than later, as it invalidates all existing blocks.

However I'm not 100% a fan of making this change now. I feel like there are still many very rough edges around text formatting, specifically around making lists and quotes, that need polish. We have a path forward on that, but it's very conceivable we'll be revisiting some of the behavior around the text block. Even now, you can make a single linebreak and you're still inside the same text block:

```
Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.
Loem ipsum dolor sit amet, ferri vidisse nam eu, ad nec copiosae mnesarchum vituperatoribus. Te brute dicunt sea, ut vis omnium menandri, ut sumo aliquam has. Eum aperiam interpretaris at, sea et recusabo expetenda, omnis tibique mea no. Pri suas partem ea, ius sonet numquam offendit cu, ad simul admodum pri. Eum cu unum choro albucius.
```

This is semantically two paragraphs, but it'd still be part of the same text block.

What I'm trying to say is that I feel like there's not a clear benefit to making this change yet — there might be once the linebreak and list-making flow plays out. I would also suggest that though the intention is right, _make the breaking changes sooner_, it is still a beta and we need to try and keep a cool head and stay nimble, there are likely to be breaking changes in the future also. 

(And even breaking changes shouldn't be too much worse than the text becoming part of the Classic Text block)

**Comment by nylen** [comment]
> I can understand the sentiment here — _call it what it is_.

The idea is from [a comment on WPTavern](https://wptavern.com/gutenberg-0-5-0-adds-new-verse-block-for-poetry-and-a-new-display-for-recent-blocks#comment-225002) - I think it's a really good one.

> I feel like there are still many very rough edges around text formatting, specifically around making lists and quotes, that need polish.

I think both of these things should be improved independently.

> it's very conceivable we'll be revisiting some of the behavior around the text block.

If and when we do this, it should happen in a separate block (`core/text` vs `core/paragraph`). This PR opens the way forward for various options there, such as allowing users a choice of behavior based on which blocks they choose.

In the meantime, plugins should be able to explore those options themselves. That's a bit difficult at the moment: there is this `Text` block which is not really a continuous section of text, so what do I call my plugin's text block? `Actually Text`?

**Comment by nylen** [comment]
In the absence of further feedback I plan to merge this later today.  If and when text behavior changes to make this less necessary or less valid, we can change it back.

As usage grows, we should start thinking more about breaking changes.  Fortunately this case is pretty easy to handle because the blocks have the same structure: just convert the old blocks to the new name whenever we load a post.  This is done in this PR, and future PRs can use similar approaches.

**Comment by mtias** [comment]
Could set up a way to no invalidate `core/text` and set it up as an alias for now? Specially if we were to change this behaviour, we could be invalidating a lot of posts twice, for no super solid reason yet.

**Comment by nylen** [comment]
The current behavior should just be an invisible change, but it's probably possible to not modify existing content.  What would be the benefit of that approach?

**Comment by youknowriad** [comment]
If we want to surface this, maybe we should just rename the title of the block and leave its name as is. This is still a moving part let's not take a final decision here. 

We already have the `Classic Text` with a `core/freeform` name

**Comment by nylen** [comment]
A paragraph is a paragraph, so we should call it a paragraph.  Having the external name different from the internal name doesn't sound like a great idea to me.

I think there is also some benefit to converting "text blocks as they exist today" to `core/paragraph`.  Then we can lock this behavior in place and explore any new behaviors with a different block type.

I don't anticipate any adverse effects from this change either way.

**Comment by nylen** [comment]
> We already have the `Classic Text` with a `core/freeform` name

This is a separate issue... but I do think these two names should match as well.

**Pull request merged**
