### PR TITLE
Add inserter performance measures

### PR DESCRIPTION
**Pull request by david-szabo97**
## Description
Add two new performance measurements:

* Time to open global inserter
* Time to move mouse between two block items in the inserter

## How has this been tested?
`npm run test-performance`

## Screenshots
image

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by david-szabo97** [comment]
Opening performance measurement is related to https://github.com/WordPress/gutenberg/issues/26080

Hover performance measurement is related to https://github.com/WordPress/gutenberg/pull/26348

**Comment by youknowriad** [comment]
That's very cool. Can we add these measures to the performance command output (`performance.js` file) https://github.com/WordPress/gutenberg/pull/26634/checks?check_run_id=1342573998

**Comment by youknowriad** [comment]
Thanks for the updates, that looks better. That said, I wonder if we should split the outputted table somehow, it's becoming unreadable unless you have a giant screen.

Capture d’écran 2020-11-06 à 7 47 03 PM

Or maybe we should remove the "min/max" values from all measures in the output?

**Comment by david-szabo97** [comment]
> Thanks for the updates, that looks better. That said, I wonder if we should split the outputted table somehow, it's becoming unreadable unless you have a giant screen.

How about inverting the table?
image

**Comment by youknowriad** [comment]
That's a lot better thanks.

**Comment by youknowriad** [comment]
Looking at the numbers inserterOpened is changing by 10ms seconds above without any change in the code. Do you think this is within the range of error? Anything we can do to make the number more stable so we can trust it better?

**Review by youknowriad — APPROVED** [review]

**Comment by david-szabo97** [comment]
So far I saw a maximum of 3% difference between runs. I think ~10ms (~2.5%) is fine here.

**Comment by sgomes** [comment]
> Anything we can do to make the number more stable so we can trust it better?

One option is to take multiple before and after measurements, and applying a Welch's t-test to calculate the p-value and thus determine whether the change is significant or just a statistical blip.

I wrote a tool that does this for basic page metrics (not SPA navigation like you need here), but the code might still help: https://github.com/Automattic/lab-assistant

**Pull request merged**
