### PR TITLE
UI: Tweak the notices design and position

### LINKED ISSUE #3457: Improve notices location
Right now notices appear like this:

2017-11-13 at 14 22

In testing this is being seen as easy to miss. So, what can we do about it? Let me give a few options and we can work out where we go from here.

There are 3 basic positions that could be used:

Current position:

position1

Top position:

position2

Fuller current (making it 700 or 800 px wide):

position3

## 1. Variable placing, desktop top.

This position puts the desktop at the top but on mobile varies.

top1

top2

Mobile looks like this:

mobile1

The positive aspect of this placing is it goes with the visual focus area. However, it can lead to a cluttered visual experience. The messages do not appear that often though. It's worth adding in that to deciding on a solution.

What does a longer message/translation look like?

top3

That's not great, but we can iterate on this and we should work out how many messages would get this long.

## 2. Alternative just make the notice look less 'stuck on'
The issue right now is that the notice is incredibly subtle. What about making it wider and having it a little larger?

var1

Either option could work so interested in opinions.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #3457

screen shot 2017-11-27 at 13 48 10

### CODE REVIEW

**Comment by jasmussen** [comment]
I dig it, I can get behind this.

The padding is a little tight around the text on the left:

screen shot 2017-11-27 at 14 03 53

Is this padding that's decided on by WordPress itself, or something we've rebuilt for Gutenberg? If the former, then it shouldn't be fixed, if the latter, then I'd make the padding match top right bottom and left of the text.

**Comment by youknowriad** [comment]
@jasmussen It's a custom padding, I adjusted it, let me know if it's better.

**Comment by jasmussen** [comment]
I think this padding would work better:

```
.editor-layout .components-notice-list .notice {
    margin: 0 0 5px;
    padding: 6px 12px;
    min-height: 50px;
}
```

screen shot 2017-11-27 at 14 15 29

With that, 👍 👍 from me.

**Review by karmatosed — APPROVED** [review]
Great to see this, thanks!

**Pull request merged**
