### PR TITLE
Move and rename the site editor menu item

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Moves the site editor menu item to Appearance and change the label to Editor

For https://github.com/WordPress/gutenberg/issues/29630

## How has this been tested?

Open the WordPress admin area and locate the menu item.

## Screenshots 
Editor (beta) menu item is the first item under the Appearance menu
(Yes, this screenshot also include the plugin Theme Check under the Appearance menu)

## Types of changes

Enhancement

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by carolinan** [comment]
This moves the site editor from `admin.php?page=gutenberg-edit-site` to `themes.php?page=gutenberg-edit-site`
I am not sure what backwards compatibility issues this may cause for plugins and that is why I am not convinced that this is the best way.

**Review by kevin940726 — APPROVED** [review]
LGTM 👍

I don't think this closes #29630 though? There still seems to have some follow-ups to do. (We can open separate issues for them though)

**Review by Mamaduka — APPROVED** [review]
Thanks for working on this, @carolinan.

> This moves the site editor from admin.php?page=gutenberg-edit-site to themes.php?page=gutenberg-edit-site
I am not sure what backwards compatibility issues this may cause for plugins and that is why I am not convinced that this is the best way.

The Site Editor probably will have its custom file, like `themes.php`, when it's gets merged in the core.

P.S. The "Editor" and "Theme Editor" side by side might be a little confusing for users. Should we remove it for Block Themes?

**Comment by noisysocks** [comment]
> The Site Editor probably will have its custom file, like themes.php, when it's gets merged in the core.

Correct, it will end up in `wp-admin/site-editor.php` or similar.

**Comment by carolinan** [comment]
> P.S. The "Editor" and "Theme Editor" side by side might be a little confusing for users. Should we remove it for Block Themes?

I also think it can be confusing, and there may be many simple miss clicks - but I don't want the feature removed. Perhaps moved. 
(And no the code editor mode or the block editing can not replace the theme file editor since they can only change template files not other type of files.)

**Pull request merged**
