### PR TITLE
Move the switch to enable new Font Library to Experiments setting

### PR DESCRIPTION
**Pull request by pbking**
## What?
Moves the switch to turn on/off the Fonts API to the Gutenberg Experiments page.

Also disables the interface when disabled.

image

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
Thanks for adding this, I have't checkout and test it yet but overall looks good and useful. Please rename the option to "Font Library" because "Font API" is another area of the code in charge of something else and soon it will be deprecated.

**Comment by pbking** [comment]
I have updated the names.

**Review by matiasbenedetto — COMMENTED** [review]
This is working great on my end. Thanks for working on this.

My only concern is this:
As far as I know, the Gutenberg experiments page is only available when you have Gutenberg plugins installed and activated. In consequence, this switch will be only available when using Gutenberg. At the same time, the Font Library feature is intended to be in WordPress core, so we won't be able to turn the feature on/off while using just core.   

For those reasons, I'm not 100% sure that we should merge this. What do you think of an alternative like continuing to use the `FONT_LIBRARY_ENABLE` to switch the feature on/off in the backend and add a check in the frontend too as you made in:

https://github.com/WordPress/gutenberg/blob/4a6cfe9398416dd6974e79f572ce23371fd201a7/packages/edit-site/src/components/global-styles/screen-typography.js#L25

**Comment by pbking** [comment]
> For those reasons, I'm not 100% sure that we should merge this. What do you think of an alternative like continuing to use the FONT_LIBRARY_ENABLE to switch the feature on/off in the backend and add a check in the frontend too as you made in:

Sure, that's reasonable.  Do you think it would hurt anything to use the same interface to enable the feature via UI?  I'm not sure what the timeline is expected to be for it being defaulted to ON; That may inform if its even worth having a UI way to do that...

**Comment by matiasbenedetto** [comment]
> I'm not sure what the timeline is expected to be for it being defaulted to ON

This is intended to be working by default on WordPress core 6.4 release.

**Comment by matiasbenedetto** [comment]
> Do you think it would hurt anything to use the same interface to enable the feature via UI?

I'm not sure what interface you are referring to.

**Comment by matiasbenedetto** [comment]
Closing this PR as outdated.

**Pull request closed without merging**
