### PR TITLE
List: Disable edit as HTML support

### PR DESCRIPTION
**Pull request by shimotmk**
## What?

This PR disables HTML editing support for list blocks.
A similar PRs: #11785, #39318 and #49426.

## Why?

> Editing these wrapper blocks in HTML directly is fragile and prone to breaking the users' content. HTML editing should be left to leaf-blocks.

https://github.com/WordPress/gutenberg/pull/11785#issue-380011111

## Testing Instructions

1. Open a Post or Page.
2. Insert a List block.
3. Confirm "Edit as HTML" action isn't available in block Options.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/42362903/0ef42377-3e6c-43b8-958e-d0cf54ff9650

### CODE REVIEW

**Review by ajitbohra — APPROVED** [review]
LGTM 👍

**Comment by shimotmk** [comment]
@ajitbohra
Could you please merge this pull request?

**Comment by shimotmk** [comment]
@ajitbohra
Is this something I need to do?
Is it better to rebase the trunk branch?

**Comment by shimotmk** [comment]
I closed it by mistake.🙇‍♂️
Could someone please give a review?

**Review by Mamaduka — APPROVED** [review]

**Pull request merged**
