### PR TITLE
Fix undo/redo in site editor code editor's mode

### LINKED ISSUE #43277: Undo does not work in the site editor's code editor
### Description

When editing a template or a template part in code view in the site editor, or the isolated template editor, pressing `Cmd + Z` does nothing. This works in the post editor.

### Step-by-step reproduction instructions

1. on trunk
2. have a block theme active
3. go to side editor
4. open a template or template part
5. switch to code editor
6. edit some of the code
7. Press `Cmd + Z`
8. Observe Bug

Sometimes the undo works after saving.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

- Wordpress 6.0
- Gutenberg trunk
- Firefox latest

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by youknowriad**
closes #43277 

## What?

This PR fixes the undo/redo of the site editor's code editor mode but also simplifies the code editor a lot. 

## How?

The main complexity in the previous implementation is that it was actually making the assumption that when you edit the "content" of a record, you also need to edit the "blocks" property to keep it in sync. The reality is that we don't have to keep these two in sync, we can instead just "unset" the blocks which means whenever the blocks will be needed again, they'll just parse again from the edited "content".

Ideally this PR is also merged in coordination with #52417 which simplifies the blocks parsing logic from content too. 

I think we can probably do the same simplification to the code editor of edit-post too.

## Testing Instructions

1- Open the site editor 
2- Switch to code editor mode
3- Edit the content and use undo/redo
4- Everything should work perfectly (undo/redo is per character but that's a separate issue anyway).

### CODE REVIEW

**Review by Mamaduka — COMMENTED** [review]
A general question: Do you think we should retain validation through parsing on blur? It sort of gives you immediate feedback if you mess up the block markup.

With updated behavior (which I really like, btw), you'll only see parse errors after switching to the visual editor.

P.S. I'm unsure if people (except me) find original behavior helpful. We can always land as it is and return the previous `onBlur` handler later.

## Screencast

https://github.com/WordPress/gutenberg/assets/240569/c435d250-7b1c-400f-bee9-c294b335a70f

**Comment by youknowriad** [comment]
Myself too, I grew accustumated to the fact that on blur, we parse and serialize again but to be honest I feel like this was just a habit and a wrong behavior. If someone edits HTML, he wants that HTML to persist.

**Review by jorgefilipecosta — COMMENTED** [review]
Hi @youknowriad, with these changes the undo seems to be character by character, which makes it a little hard to use (each key press creates an undo level). On the edit post, the undo seems to not be happening character by character.

**Review by Mamaduka — APPROVED** [review]
Besides the lack of "coalesced edits", the changes test well for me.

**Comment by youknowriad** [comment]
> Hi @youknowriad, with these changes the undo seems to be character by character, which makes it a little hard to use (each key press creates an undo level). On the edit post, the undo seems to not be happening character by character.

That's because in edit-post, it's not relying on the "undo" of the input and not the actual undo/redo stack we have. and sometimes it's very broken in edit-post today as well. So I think we should both update them to use the current PR behavior instead. and for the character per character, that's something separate IMO, we should solve that by implementing a RichText like behavior and this is something that is being explored (reusable hook) in #52375

**Comment by youknowriad** [comment]
I took another look at the post editor and in my test undo/redo there creates an undo stop when you focus out, it's something we can do in the site editor easily too if we wanted but I still feel that it's wrong but it could undo a very long change if you write something very long in the code editor. Instead we should bring RichText's way of coalescing edits. So I'm going to merge this, and I'll be following-up with the same simplification for the post editor too.

**Pull request merged**
