### PR TITLE
Move more dashicons to the icons package

### PR DESCRIPTION
**Pull request by youknowriad**
The new icons are:

- starEmpty
- starFilled
- starHalf
- insertAfter
- insertBefore
- plusCircleFilled (plus-alt before)
- layout
- media (admin-media before)
- external
- textColor
- controlsRepeat

### CODE REVIEW

**Comment by youknowriad** [comment]
I'd appreciate a mobile check here as there's a few components updated cc @Tug @hypest

**Comment by Tug** [comment]
I noticed a regression in the main inserter icon (the inserter for group looks fine although thicker than the original)
image

This is due to the css border rules we have here:
https://github.com/WordPress/gutenberg/blob/0473209da344111c86ebaedd0ced275769fa03ff/packages/block-editor/src/components/inserter/style.native.scss#L73-L75
https://github.com/WordPress/gutenberg/blob/0473209da344111c86ebaedd0ced275769fa03ff/packages/block-editor/src/components/inserter/style.native.scss#L80

If we remove them though the icon might be too small:
image

**Comment by etoledom** [comment]
The ideal is to use the proper icon we want, instead of hacking its thickness with border color.

@iamthomasbishop, I believe we have talked about this before, and that's why we arrived to this solution, but where can we get the icon with the proper dimensions for the inserter button?

Related: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1457
We can continue this conversation on that ticket. 👍

**Comment by youknowriad** [comment]
How do you think we can unblock this PR?

**Comment by iamthomasbishop** [comment]
I dropped a comment on the [other mobile ticket](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1457) regarding my original proposal to use the Material filled/outlined versions of the plus icon on (native) mobile. However, now that I think about it, it looks like core GB may already be using the Material icons for the appender, so perhaps it's already in the set? If it's already available, why/where is Dashicons `plusCircleFilled` used vs. Material?

**Comment by youknowriad** [comment]
GB web is using the plusCircle icon which is also a dashicon based svg for now. Happy to use it if you think that's the way forward.

**Comment by iamthomasbishop** [comment]
Thanks @youknowriad 😄  I didn't mean to derail this conversation, but I wanted to clarify so we can get it right on mobile.

> GB web is using the plusCircle icon which is also a dashicon based svg for now

I was looking at the [Dashicons docs](https://developer.wordpress.org/resource/dashicons/#plus-alt), and was seeing what looks to be a different icon relative to the one used on the editor. For comparison:

image

On **native mobile**, I'd like to use that same icons as the core web example above for inline appenders (on Group, Gallery, Columns, etc. blocks), but a filled variation on the block toolbar (this looks to my eye like [`add_circle`](https://material.io/resources/icons/?search=add&icon=add_circle&style=baseline) from Material icons). For example:

Screen Shot 2020-02-12 at 11 41 42 AM

Does that make sense? I don't think the appenders/inserter icon need to change on core, I'd just like to avoid using Dashicons `plus-alt` (aka `plusCircleFilled` now) 😄 

--------

Also just as a side-note for us mobile-folk: we're also using `insertAfter` and `insertBefore` on the bottomSheet that shows when long-pressing the block toolbar inserter on Android, per this [recent work](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1835). So we might want to audit whether this PR changes anything there as well. // cc @ceyhun @etoledom

**Comment by Tug** [comment]
Yep I did check `insertAfter` and `insertBefore` during my first pass and they look fine. Same as before but they seemed smaller now that I think about it 🤔

**Comment by youknowriad** [comment]
So our goal here is to get rid of Dashicon component completely and rely on a unified `@wordpress/icons` for all icons across the project. Right now, some of these icons are dashicons, but ultimately (with G2 work), we'll probably update most of them.

So I'd love some help here on how to get rid of the Dashicon strings from the mobile part here.

**Comment by Tug** [comment]
Can we use 
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
	<path d="M2 12C2 6.44444 6.44444 2 12 2C17.5556 2 22 6.44444 22 12C22 17.5556 17.5556 22 12 22C6.44444 22 2 17.5556 2 12ZM13 11V7H11V11H7V13H11V17H13V13H17V11H13Z"/>
</svg>
```
instead for `plusCircleFilled` ?

Props to @iamthomasbishop who (re-)designed it.

**Comment by youknowriad** [comment]
I updated the svg, thanks for the redesign. Since, it's only used in mobile now, it shouldn't have any impact on web. In the future I believe designers should work together to allign icons between web and mobile. (A note that most of the icons are planned to be changed in G2)

**Comment by youknowriad** [comment]
@jasmussen any thoughts on the naming.

**Comment by pablohoneyhoney** [comment]
As we move into integrating the new set of icons for unity and finesse in the interfaces, we need to to streamline that to mobile too @iamthomasbishop 

Latest versions in [this open Figma](https://www.figma.com/file/fnyj380i05vGzuuH60frLQ/G2-Design?node-id=1178%3A0 
)

Re: naming, we are using _icon-paragraph_ 

Screen Shot 2020-02-13 at 10 08 05 AM

**Comment by pablohoneyhoney** [comment]
There's a second semantic category of icons for block types: **block-paragraph**
@youknowriad 

Screen Shot 2020-02-13 at 5 16 17 PM

**Comment by youknowriad** [comment]
Thanks for the insights @pablohoneyhoney

Right now all the icons are being centralized in a `@wordpress/icons` package which lead me to think that the `icon-` in the name is redundant with `import { bold } from '@wordpress/icons';`

I also wonder whether the `block-` is necessary as for instance the `block-paragraph` icon in the context of the "icons" package is a completely valid icon for "paragraph" representations that are not blocks.

That said, these icons are already merged and I believe we should have a discussion to rename all icons at once in a separate context from the current PR.

**Comment by youknowriad** [comment]
I rebased the branch, I'm going to land it soon. Since this is an internal package for now, we can still make all the changes we want/renaming in follow-ups.

**Pull request merged**
