### PR TITLE
FormToggle: do not use "/" math operator

### PR DESCRIPTION
**Pull request by ciampo**
## What?

Refactor `FormToggle`'s styles away from using the `/` math operator

## Why?

As flagged in https://github.com/WordPress/gutenberg/pull/56515#discussion_r1410184116, the `/` operator is deprecated in Sass

## How?

Using the `math` module and the `math.div` operator (as suggested [here](https://github.com/WordPress/gutenberg/pull/56515#discussion_r1410396390))

## Testing Instructions

- Make sure that `FormToggle` renders correctly in Windows High Contrast Mode
- Make sure that there are no deprecation warnings when building the plugin locally (as mentioned by @andrewserong [here](https://github.com/WordPress/gutenberg/pull/56515#discussion_r1410184116))

### CODE REVIEW

**Comment by ciampo** [comment]
Probably there's no need for a CHANGELOG entry, if this is part of the same Gutenberg release.

**Review by jasmussen — APPROVED** [review]
Green check from me, but I saw a comment by @andrewhayward so I'll defer to him if he prefers another path forward.

**Comment by ciampo** [comment]
Yup, Andrew suggested a cleaner solution — just updated the PR to implement his suggestion

**Comment by andrewhayward** [comment]
> ...I'll defer to him if he prefers another path forward.

I'm not overly concerned which approach we use, but going the recommended route is probably better for future-proofing.

> Probably there's no need for a CHANGELOG entry, if this is part of the same Gutenberg release.

Agreed. Do we ever tack two PRs together in the same CHANGELOG entry? Would at least make it clear that they're both relevant.

```
-   `FormToggle`: refine animation and improve high contrast styles
    ([#56515](https://github.com/WordPress/gutenberg/pull/56515))
    ([#56672](https://github.com/WordPress/gutenberg/pull/56672)).
```

**Comment by andrewserong** [comment]
Thanks for the quick follow-up! 🙇

**Pull request merged**
