### PR TITLE
Create @wordpress-mobile/components package

### PR DESCRIPTION
**Pull request by koke**
## Description

This creates a new `@wordpress-mobile/components` package in `packages/mobile/`.

Some things I'm still considering about this one:

- Should Lerna also pick this up and publish to npm on each Gutenberg release, or should we handle mobile packages separately? We can still publish versions manually and Lerna will only publish on release if there have been changes since the last version. I think this would work for us.
- One idea I have about this folder structure is that we would eventually move the other things from the [gutenberg-mobile](https://github.com/wordpress-mobile/gutenberg-mobile) repo and have a `@wordpress-mobile/block-editor` package that would include all the editor initialization.
- The idea behind the different `@wordpress-mobile` prefix is to signal that those packages are React Native code. I don't know if we can also make that more know in the `package.json` to avoid accidental imports.
- Each component needs some documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
> Should Lerna also pick this up and publish to npm on each Gutenberg release, or should we handle mobile packages separately? We can still publish versions manually and Lerna will only publish on release if there have been changes since the last version. I think this would work for us.

If any of the existing packages depend on this package it must be published to npm. In the current implementation `@wordpress/block-library` uses this package but it isn't reflected in `package.json` file. Managing native dependencies in packages it's something which was never solved. Is there at least an issue which tracks it?


> The idea behind the different `@wordpress-mobile` prefix is to signal that those packages are React Native code. I don't know if we can also make that more know in the `package.json` to avoid accidental imports.

Do you think those packages should be published to npm? If yes, then using a different organization will cause issues as all folks doing npm packages release will need to have access sorted out for both `wordpress` and `wordpress-mobile` on npm.

There is also this broader discussion, why those components exist on native mobile and don't have a matching behavior on the web with the mobile viewport?

**Comment by koke** [comment]
> In the current implementation @wordpress/block-library uses this package but it isn't reflected in package.json file.

You're right, I missed that bit. They probably need to be published with the rest. 

> There is also this broader discussion, why those components exist on native mobile and don't have a matching behavior on the web with the mobile viewport?

That's a good point. I'm not sure if all of the native components would have a web counterpart, and I definitely see us building things for native that would eventually be ported to mobile web, but not right away.

I see this as an intermediate step to bring more of the code currently living in `gutenberg-mobile` to Gutenberg, and then refactor as much of it as possible to use the same components/APIs that Gutenberg defines. See https://github.com/wordpress-mobile/gutenberg-mobile/issues/958 for some of the next steps on this front.

That said, it seems sensible that all these would just go to `@wordpress/components` directly, but I'm not entirely sure what are the implications of having native-only components there, and start adding react-native dependencies to Gutenberg packages. I guess this is what you mean by:

> Managing native dependencies in packages it's something which was never solved. Is there at least an issue which tracks it?

What would you say are the challenges on adding `react-native` as a dependency of `@wordpress/components`?

**Comment by gziolo** [comment]
> What would you say are the challenges on adding `react-native` as a dependency of `@wordpress/components`?

I think it would be perfectly fine to define it as a `peerDependency` which means it won't get installed by default but it would give feedback that it's missing when using with projects. Unfortunately, there is no way to mark the dependency as optional and loaded only in the given context :(

It has to be finally explored and fixed to ensure that packages published to npm can be used with 3rd party projects.

**Comment by koke** [comment]
But since the code is actually [importing from react native](https://github.com/WordPress/gutenberg/blob/dbec7f84a1122b311f8eaa3016ab50d91eec25cc/packages/mobile/components/src/picker/index.ios.js#L4), shouldn’t it be a regular dependency?

**Comment by koke** [comment]
I'm closing this for now, and we'll do a new PR to put these components in `@wordpress/components` instead.

**Pull request closed without merging**
