### PR TITLE
Fix inconsistent references to Settings Sidebar

### LINKED ISSUE #14988: Handbook: Resolve inconsistent terminology for the Settings Sidebar
Throughout the Gutenberg handbook, the [Settings Sidebar](https://wordpress.org/gutenberg/handbook/designers-developers/designers/design-patterns/#settings-sidebar) is also called the "Block Sidebar" ([source](https://wordpress.org/gutenberg/handbook/designers-developers/designers/block-design/)) and "Inspector" ([source](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/block-controls-toolbars-and-inspector/#inspector)). The definition of the Settings Sidebar from the [Design Patterns doc](https://wordpress.org/gutenberg/handbook/designers-developers/designers/design-patterns/) is as follows:
>The Settings Sidebar contains additional settings for the document (tags, categories, schedule etc.) and for blocks in the “Block” tab. A cog button in the toolbar hides the Settings Sidebar, allowing the user to enjoy a more immersive writing experience. On small screens, the sidebar is hidden by default.

The documentation should be updated so that the correct terminology is used throughout the handbook so that folks are not confused when referring to the Settings Sidebar.

### PR DESCRIPTION
**Pull request by sarahmonster**
This swaps out instances of Inspector and Block Settings with Settings Sidebar, as per our [Design Patterns doc](https://wordpress.org/gutenberg/handbook/designers-developers/designers/design-patterns/). I think I've got them all, but would appreciate a double-check. 

I've also corrected a few instances of unclear references to the Block Toolbar when I came across them, and I've updated the code where it made sense and wouldn't break things, so we are more consistent about how we refer to things. The term "Inspector" still appears as the name of a React component, but that's a bigger change I'd rather not initiate here.

I've also changed a filename and slug, which I'm hoping won't break things, but we can revert if those will cause issues.

Fixes #14988.

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
Copy-wise, this is in great shape and gets a ✅ from me.

Before merge though, I'd like to get one final look from someone familiar with renaming files though to make sure this will translate correctly to the WP.org mirror. @gziolo can you take a look if you have a moment?

Thanks!

**Comment by gziolo** [comment]
> Before merge though, I'd like to get one final look from someone familiar with renaming files though to make sure this will translate correctly to the WP.org mirror. @gziolo can you take a look if you have a moment?

@chrisvanpatten or @nosolosw should know better, I have no idea how it works at the moment. The biggest concern I would personally have is that we should start adding redirects to every URL we change to ensure they work when linked from external websites.

**Comment by sarahmonster** [comment]
Lovely, I wasn't sure about changing the URL slugs and whether or not they'd redirect. I can roll them back if it seems like it'd be problematic, but if they _will_ redirect it'd be best to change these references in as many places as possible, to reinforce consistent terminology.

**Comment by nosolosw** [comment]
:wave: There are a couple of other places in the docs where we are using inspector rather than settings sidebar: [glossary](https://developer.wordpress.org/block-editor/contributors/glossary/), [block registration](https://developer.wordpress.org/block-editor/developers/block-api/block-registration/).

I've also noticed that the code primitives refer to Inspector ([see](https://developer.wordpress.org/block-editor/packages/packages-block-editor/#API)). Probably that was the term used since the beginning (see glossary). I'd like both code and docs to refer to the same terms, as to have a common vocabulary among all of us, and also not to confuse authors that want to use the block editor APIs. Changing the code is feasible, but I also understand it'll be a slightly bigger challenge that's perhaps best addressed in a different PR.

**URLs**

One thing that we can do to know whether an URL will redirect automatically is to substitute the old slug by the new one. For example:

* old slug: https://developer.wordpress.org/block-editor/tutorials/block-tutorial/block-controls-toolbars-and-inspector/
* new slug: https://developer.wordpress.org/block-editor/tutorials/block-tutorial/block-controls-toolbar-and-sidebar/

It won't work in this case. It's possible to ask people in meta to add this redirect, though. If we wanted to change the URL, we should probably add the redirects it as to not break existing external references to the handbook.

**Comment by sarahmonster** [comment]
> I'd like both code and docs to refer to the same terms, as to have a common vocabulary among all of us

Agreed x 1,000,000!

I noticed this in the code but wasn't comfortable changing it myself for what are probably obvious reasons. 😄 I'm happy to file a follow-up issue though.

Good to know that the URL wouldn't automatically update. Do you think we should just keep the existing URL, or ask for a redirect to be made manually? I'm definitely inclined to change the references in all instances (text, code, and URLs) for better consistency across all areas of the project, but I understand if this could prove more work than strictly warranted.

**Comment by mkaz** [comment]
I've merged and closing this one out to move forward with the changes.

I've created an issue to address code here: https://github.com/WordPress/gutenberg/issues/16437

I created this Meta Trac ticket for redirect: https://meta.trac.wordpress.org/ticket/4582#ticket

And will open a new PR and reference this one for additional documentation changes.

**Pull request merged**
