### PR TITLE
Fix UI order for theme.json spacing sizes

### LINKED ISSUE #62194: customSpacingSize broken in my theme
### Description

Likely as a result of https://github.com/WordPress/gutenberg/pull/61842, my custom spacing sizes are no longer working. My Powder theme (https://github.com/bgardner/powder/blob/main/theme.json#L146) uses t-shirt sizing method, per below (note my theme.json is currently `"version": 2`

```
"spacing": {
	"spacingSizes": [
		{
			"name": "xSmall",
			"size": "clamp(10px, 2vw, 20px)",
			"slug": "x-small"
		},
		{
			"name": "Small",
			"size": "clamp(30px, 4vw, 40px)",
			"slug": "small"
		},
		{
			"name": "Medium",
			"size": "clamp(40px, 6vw, 60px)",
			"slug": "medium"
		},
		{
			"name": "Large",
			"size": "clamp(50px, 8vw, 80px)",
			"slug": "large"
		},
		{
			"name": "xLarge",
			"size": "clamp(60px, 10vw, 100px)",
			"slug": "x-large"
		}
	],
	"units": [ "%", "px", "em", "rem", "vh", "vw" ]
}
```
With Gutenberg 18.5 RC1 active, numbers are now being used in areas such as padding, and the mapping is out of order:

1 = var(--wp--preset--spacing--large)
2 = var(--wp--preset--spacing--medium)
3 = var(--wp--preset--spacing--small)
4 = var(--wp--preset--spacing--x-large)
5= var(--wp--preset--spacing--x-small)

It appears my t-shirt sizing presets are being reordered by alpha in this scale. Expected behavior/output should be:

xSmall= var(--wp--preset--spacing--x-small)
Small = var(--wp--preset--spacing--small)
Medium = var(--wp--preset--spacing--medium)
Large = var(--wp--preset--spacing--large)
xLarge = var(--wp--preset--spacing--x-large)

### Step-by-step reproduction instructions

1. Find a group and try applying padding.
2. Notice that the spacing scale is off.

### Screenshots, screen recording, code snippet

Below is a before/after video of me applying padding to a group block. First instance is with WP 6.5.3 (Gutenberg not active) and the second instance is with WP 6.5.3 (Gutenberg 18.5 RC1 active)

https://github.com/WordPress/gutenberg/assets/486261/9948e8e8-ca37-492e-b20c-d543847a21e0

### Environment info

WordPress 6.5.3, Gutenberg 18.5 RC1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ajlende**
## What?

Solves the ordering issue for spacing sizing presets in v2 theme.json files that don't follow the `'10'`, `'20'`, etc. convention for slugs.

~The labels in the range slider remain numbers as, I believe, that was the intention of the feedback that #44247 fixed on the server instead of in the UI. It was a bug if the slider didn't show numbers.~

The labels are kept as t-shirt sizes when using the slider now.

## Why?

Fixes #62194

> With Gutenberg 18.5 RC1 active, numbers are now being used in areas such as padding, and the mapping is out of order:
> 
> 1 = var(--wp--preset--spacing--large)
> 2 = var(--wp--preset--spacing--medium)
> 3 = var(--wp--preset--spacing--small)
> 4 = var(--wp--preset--spacing--x-large)
> 5 = var(--wp--preset--spacing--x-small)

## How?

It works by only sorting presets when they need to be merged.

See https://github.com/WordPress/gutenberg/issues/62194#issuecomment-2142933855 for details, but to summarize the constraints of the problem:

- Any solution must to work for both v2 and v3 as there is no distinction in the code (v2 shaped theme.json data automatically get converted to the v3 shape before anything can be done with the data).
- Sorting of multi-origin presets must be done in the UI as they are separated out on the server and cannot be merged until they're loaded in the JS.
- Renaming of multi-origin presets must be done in the UI for similar reasons.
- v2 themes with `spacingSizes` slugs that do not conform to the number convention must use the ordering defined in the theme.json file.

V2 theme.json files will _always_ only have one `spacingSizes` array, either the one defined in theme.json the one generated (in order) from `spacingSizes` values.

V2 theme.json files will _always_ only have one origin of `spacingSizes` defined.

V3 theme.json files allow both `spacingScale` and `spacingSizes` to be defined at the same time and the results merged into one array. When this is done on the server, we can sort the merged values. These merged values become `spacingSizes` for their origin in the frontend.

V3 theme.json files allow `default`, `theme`, and `custom` origins for `spacingSizes` that are separated until they reach the frontend. Only sort them in the frontend if more than one origin is defined.

## Testing Instructions

Add this in a `"version": 2` theme.json file.

```json
"spacing": {
	"spacingSizes": [
		{
			"name": "xSmall",
			"size": "clamp(10px, 2vw, 20px)",
			"slug": "x-small"
		},
		{
			"name": "Small",
			"size": "clamp(30px, 4vw, 40px)",
			"slug": "small"
		},
		{
			"name": "Medium",
			"size": "clamp(40px, 6vw, 60px)",
			"slug": "medium"
		},
		{
			"name": "Large",
			"size": "clamp(50px, 8vw, 80px)",
			"slug": "large"
		},
		{
			"name": "xLarge",
			"size": "clamp(60px, 10vw, 100px)",
			"slug": "x-large"
		}
	],
	"units": [ "%", "px", "em", "rem", "vh", "vw" ]
}
```

~The slider should still use numbers, but the presets should remain in their original order.~

The slider uses the preset names and remain in their original order.

xSmall = var(--wp--preset--spacing--x-small)
Small = var(--wp--preset--spacing--small)
Medium = var(--wp--preset--spacing--medium)
Large = var(--wp--preset--spacing--large)
xLarge = var(--wp--preset--spacing--x-large)

Additionally, v3 files should behave the same when `defaultSpacingSizes` is also set to `false`.

### CODE REVIEW

**Comment by bgardner** [comment]
@ajlende Confirmed that this is now working, per video:

https://github.com/WordPress/gutenberg/assets/486261/e761bb8d-6290-4a72-9afe-ece8559372db

**Comment by bgardner** [comment]
Would love to get this approved and into Beta sooner vs. later, so those testing the Beta won't have broken spacing on both front/back end.

**Comment by ndiego** [comment]
I tested the PR, and it works. But as you mentioned, the labels do not display correctly in the Editor UI, which I would consider a regression from 6.5. Named sizes (small, medium, large, etc.) is a pretty common approach. 

image

**Comment by ajlende** [comment]
With a couple folks in agreement about using names instead of numbers, I pushed the change and updated the description on the PR. @ndiego @bgardner

**Review by talldan — APPROVED** [review]
Worked as expected in testing.

I read through the explanation in the description, and the code changes align with what was described, though I'm not totally familiar with this part of the codebase.

**Comment by bgardner** [comment]
@ajlende Checks out and looks good to me as well. Works as expected. LGTM and get this into Beta 1!

**Comment by ndiego** [comment]
Works as expected 👌

image

**Comment by bgardner** [comment]
̶L̶G̶T̶M̶ ̶a̶n̶d̶ ̶g̶e̶t̶ ̶t̶h̶i̶s̶ ̶i̶n̶t̶o̶ ̶B̶e̶t̶a̶ ̶1̶!̶

LGTM and get this into Beta 2!

**Comment by ajlende** [comment]
Ugh. These performance tests. They were passing the entire time. Then I changed the code to do less work in 099aaf7caa76bec21ab8674daf34d2f0ddec47e7. Now they are consistently failing.

**Comment by bgardner** [comment]
@ajlende @richtabor @ndiego Any chance this can get added to 18.5, given it's a fix for https://github.com/WordPress/gutenberg/pull/61842 which was merged in the 18.5 RC? Otherwise, this doesn't make its way into WP 6.6, which means we wouldn't see this solved until 6.7?

**Comment by talldan** [comment]
@bgardner It's labeled as 'Backport to WP Beta/RC', so it will be in 6.6, but might not be in the first beta if it's not in 18.5.

**Comment by justintadlock** [comment]
Can someone else test this setup with custom slugs?

```json
"spacing": {
	"defaultSpacingSizes": false,
	"spacingSizes": [
		{
			"name": "Fluid Scale -3",
			"size": "clamp(0.31rem, 0.11cqi + 0.28rem, 0.35rem)",
			"slug": "minus-3"
		},
		{
			"name": "Fluid Scale -2",
			"size": "clamp(0.47rem, 0.16cqi + 0.42rem, 0.53rem)",
			"slug": "minus-2"
		},
		{
			"name": "Fluid Scale -1",
			"size": "clamp(0.71rem, 0.25cqi + 0.63rem, 0.79rem)",
			"slug": "minus-1"
		},
		{
			"name": "Fluid Scale +/- 0 (Base)",
			"size": "clamp(1.06rem, 0.37cqi + 0.95rem, 1.19rem)",
			"slug": "base"
		},
		{
			"name": "Fluid Scale +1",
			"size": "clamp(1.20rem, 0.85cqi + 0.94rem, 1.48rem)",
			"slug": "plus-1"
		},
		{
			"name": "Fluid Scale +2",
			"size": "clamp(1.34rem,  1.5cqi + 0.89rem, 1.86rem)",
			"slug": "plus-2"
		},
		{
			"name": "Fluid Scale +3 (Global)",
			"size": "clamp(1.86rem,  3.7cqi + -0.05rem, 2.32rem)",
			"slug": "plus-3"
		},
		{
			"name": "Fluid Scale +4",
			"size": "clamp(1.86rem, 7.53cqi + -1.2rem, 3.62rem)",
			"slug": "plus-4"
		},
		{
			"name": "Fluid Scale +5",
			"size": "clamp(1.86rem, 10.2cqi + -2rem, 4.53rem)",
			"slug": "plus-5"
		}
	]
}
```

I'm still seeing both the default sizes and my custom sizes out of order:

image

Want to make sure I'm not doing something weird before opening another ticket.

**Comment by justintadlock** [comment]
I had to bring WordPress trunk build up to date to get the correct order. :)

Though, I'm still seeing the default spacing sizes. They're just appended to the bottom of the list.

**Comment by ajlende** [comment]
> I'm still seeing both the default sizes and my custom sizes out of order:

@justintadlock I haven't been able to reproduce your screenshot at all. It looks like you're editing the block spacing setting for a group block in the post editor. This is what I see with Gutenberg trunk and WordPress trunk.

| Plugin inactive | Plugin active |
| --- | --- |
| Screen Shot 2024-06-07 at 15 36 15 | Screen Shot 2024-06-07 at 15 40 07 |

I'm not entirely sure what's going on. `defaultFontSizes` isn't valid with `"version": 2` if you forgot to update that, but it shouldn't really matter as it should effectively be `false` either way.

> I had to bring WordPress trunk build up to date to get the correct order. :)
>
> Though, I'm still seeing the default spacing sizes. They're just appended to the bottom of the list.

That surprises me. WordPress trunk doesn't have the JS changes for the sorting changes yet, so I would expect them to be in the wrong order until the JS gets backported. Do you have an old version of the Gutenberg plugin active by chance?

**Comment by justintadlock** [comment]
Thanks, @ajlende, for testing. I think I just need to reset my dev environment. I think I've broken something somewhere.

**Comment by ellatrix** [comment]
This was cherry-picked to the wp/6.6 branch.

**Pull request merged**
