### PR TITLE
add left margin to checkbox so the header is no longer overlapping it

### LINKED ISSUE #30036: Checkbox component - heading overlaps checkbox
## Step-by-step reproduction instructions

1. Go to storybook
2. Select checkbox control component `/story/components-checkboxcontrol--all`
3. Select `All` to display the heading
image
4. see the heading is overlapping the label
## Expected behaviour

Heading should not overlap checkbox
image

## Actual behaviour

Heading overlaps checkbox
image

## WordPress information
- Gutenberg version: 10.2.1

## Device information
- Device: MacBook
- Operating system: Big Sur
- Browser: Chrome 89.0

### PR DESCRIPTION
**Pull request by grzim**
## Description

Closes https://github.com/WordPress/gutenberg/issues/30036

Fixes the behavior of CheckboxControl header which was too close to the checkbox
image

## How has this been tested?

1. Go to storybook
2. Select checkbox control component `/story/components-checkboxcontrol--all`
3. Select `All` to display the heading
image
4. see the heading is not overlapping the label
## Screenshots 
image

## Types of changes

Bug fix
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by draganescu** [comment]
Howdy, this change does fix things when the heading is there but it adds some useless space when there is no heading:

Screen Shot 2021-03-25 at 20 05 29

This moves every checkbox a bit more to the right in other places:

Screen Shot 2021-03-25 at 20 02 16
Screen Shot 2021-03-25 at 20 03 50

**Comment by grzim** [comment]
True, the margin shouldn't be applied to the checkbox but rather to the header. I have fixed this. 

Without header:
image


With header:
image

**Comment by shaunandrews** [comment]
Where is this control actually used like this? I'm not sure its good to incorporate a checkbox within a sentence like this... Perhaps it would be better to update the places that use this "header" and have it either on its own line, or incorporated into the label of the checkbox.

**Comment by grzim** [comment]
I haven't found a place in the app where a header is used. But still, it is a part of the components library and it has a bug so it would be good to fix it, remove it or place it in its own line as suggested

**Comment by shaunandrews** [comment]
I question the need for this `header` prop. If its not actively being used, perhaps we can remove it.

Alternatively, perhaps we can put the `header` on its own line, instead of trying to make it look like a single line of text with a checkbox in the middle.

image

**Comment by talldan** [comment]
I guess i was done to replicate the settings in WordPress admin:
Screenshot 2021-04-08 at 11 17 37 am

But when heading is used, the checkbox ends up with two labels 😬 
Screenshot 2021-04-08 at 11 22 03 am

Testing in Voiceover, the 'label' label is ignored when the 'heading' label is used, which is probably a bad thing seeing as the heading is usually the vague description.

The other thing that's weird is that the entire CheckboxControl component doesn't have a proper classname.

> I question the need for this header prop. If its not actively being used, perhaps we can remove it.

Agreed, though it'd have to be a deprecation, as third-parties might be using it.

I'll close this PR and tackle it in a separate one.

**Comment by talldan** [comment]
https://github.com/WordPress/gutenberg/pull/30594 deprecates it.

**Pull request closed without merging**
