### PR TITLE
Update glossary.md

### PR DESCRIPTION
**Pull request by machouinard**
Remove duplicate sentence.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by Soean — APPROVED** [review]
Good catch, thanks for the fix.

**Comment by mkaz** [comment]
This needs to be rebased against master, it looks like it was opened against 5.4 tag.

**Comment by Soean** [comment]
@mkaz We had this issue on slack, see https://wordpress.slack.com/archives/C02QB2JS7/p1585897669457800

**Comment by machouinard** [comment]
> @mkaz We had this issue on slack, see https://wordpress.slack.com/archives/C02QB2JS7/p1585897669457800

Correct, that's where the link took me.  I've since reset my fork to upstream/master but I'm happy to submit a new PR and reference this.

**Comment by mkaz** [comment]
@machouinard Strange, it didn't seem to update here. I guess a PR is opened against where it wants to push too. So I think closing this one and opening new one might be best course of action.

**Comment by machouinard** [comment]
> @machouinard Strange, it didn't seem to update here. I guess a PR is opened against where it wants to push too. So I think closing this one and opening new one might be best course of action.

Created a fresh branch off master, pushed to my repo and opened PR.  Guess I don't understand git as well as I'd thought as it attached itself here.  Let me know if you need me to do anything differently.

**Comment by mkaz** [comment]
Thanks @machouinard for creating the new one and moving the change. I approved and merged #21565, so closing this one out.

**Pull request closed without merging**
