### PR TITLE
Add missing border to colors

### PR DESCRIPTION
**Pull request by richtabor**
## Description
Added missing borders for colors, as noted in https://github.com/WordPress/gutenberg/issues/36543

## Screenshots 
Screen Shot 2021-11-19 at 12 45 23 PM
Screen Shot 2021-11-19 at 12 45 37 PM
Screen Shot 2021-11-19 at 12 45 55 PM

## Types of changes
Bug fix, CSS

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by richtabor** [comment]
Screen Shot 2021-11-19 at 1 05 21 PM

**Comment by jasmussen** [comment]
Code looks good. I think this can work well, but I have no strong opinion personally — except for the white color swatch, I do also apprecite the borderless version. I've CC'ed Pablo for a quick take.

**Review by kellychoffman — APPROVED** [review]

**Comment by Mamaduka** [comment]
Hey, @richtabor

It looks like you need to rebase this branch, and we can merge after it.

**Comment by richtabor** [comment]
@Mamaduka I'll close this — seems it was fixed in another PR since then. 

CleanShot 2022-01-12 at 12 25 10@2x

**Pull request closed without merging**
