### PR TITLE
Fix select element sizing in publish date picker

### LINKED ISSUE #17590: Date picker formatting out of line
Since beta 1 (I think) the date picker now looks like this:

image

### PR DESCRIPTION
**Pull request by talldan**
## Description
Fixes #17590

New styles for select elements in core were clashing slightly with some styling in the publish date picker.

The issue was that the padding and width of the popover of the core select element was being overridden. I've removed the padding and opted to use a max width for the select, which should cover cases where a translated month name is significantly longer.

## How has this been tested?
1. Create a new post
2. Click on the publish date from the sidebar
3. Notice the elements in the popover should be sized and spaced consistently and correctly..

### Before
Screen Shot 2019-09-30 at 5 29 55 pm

### After
Screen Shot 2019-09-30 at 5 28 39 pm

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by jasmussen** [comment]
Looks good, nice. 

Before:

Screenshot 2019-09-30 at 11 53 09

After:

Screenshot 2019-09-30 at 11 54 17

However in looking at this, I also noted these two:

Screenshot 2019-09-30 at 11 51 57

Screenshot 2019-09-30 at 11 52 42

Are those tracked? 

If not, would you mind if I fixed them in this branch?

**Comment by talldan** [comment]
@jasmussen Yep, slipped my mind I was also going to fix the radio button issue. If you have time to do it, that'd be appreciated—I'm at the end of my day now.

The issue with the font-size select element shouldn't happen if you apply the latest patch from https://core.trac.wordpress.org/ticket/47477.

**Comment by jasmussen** [comment]
Cool, I'll bundle a fix for the checkboxes in this one, and ignore the font size one.

**Comment by talldan** [comment]
@karmatosed does note that the spacing between the inputs appears to be a problem on this issue:
https://github.com/WordPress/gutenberg/issues/17593#issuecomment-535446148

**Comment by jasmussen** [comment]
I'll take a look.

**Comment by jasmussen** [comment]
Screenshot 2019-09-30 at 12 03 25

Checkboxes fixed.

**Comment by jasmussen** [comment]
Took a look at the font size thing, and it's not a regression, details in https://github.com/WordPress/gutenberg/issues/17593#issuecomment-536495473.

It's trivial to fix, but to not hold up THIS PR, which is important to get in, I'm going to do that in a separate PR.

**Review by jasmussen — APPROVED** [review]
Tested this, it works well. Lots of red, that's nice.

I added in an additional mini-fix for the radio buttons, so this could use another glance. But this is good to go.

**Comment by youknowriad** [comment]
weren't checkboxes already fixed in master? just making sure this is not unnecessary?

**Comment by talldan** [comment]
@youknowriad As far as I can tell it seems to be a new issue. Not sure how it came to be.

**Comment by jasmussen** [comment]
> weren't checkboxes already fixed in master? just making sure this is not unnecessary?

Did you mean radio buttons?

The problem is that radio buttons in core are sized using `rem` units. I think those are supposed to scale relatively to the body font size, which is why they could look different in the editor.

Long term these should be scaled using px units, there's no benefit to the rem unit, not even when you're zooming.

**Comment by youknowriad** [comment]
yeah, I was thinking about the radio buttons because I saw a related fix when I was compiling the changelog.

👍 Anyway, let's make sure all these design fixes we're making are also working properly in previous Core versions (5.2)

**Pull request merged**
