### PR TITLE
Fix popover flickering on small screens

### LINKED ISSUE #25538: Calendar Date/Time Picker stutters on mobile devices
Depending on the device and the month, when opening the calendar picker, the calendar stutters as the max-width on `.components-popover__content` is rapidly added and removed.

1. Login to admin and edit a post on a mobile device or simulator. 
2. Click on the settings icon
3. Under "Status & visibility" click on the Publish link for calendar picker to pop open
4. If on an Android device you should see the stutter regardless of the selected month (calendar placement is also awkward)
5. If on an iPhone device, change the calendar month to September and observe the stutter
6. Note that calendar content within the wrapper is also off-centered when on a non-stuttering month.

**Expected Behavior**
The calendar picker wrapper should be centered horizontally on the screen and should not stutter. The calendar elements should also be centered within the calendar wrapper.

Here are screencasts of this issue
iPhone X simulator: https://www.loom.com/share/9fbc61c37c33491dbd89027227e14e65
Android: https://youtu.be/i_727BrPCCY

Versions
- WordPress version: 5.5.1
- I've confirmed this happens on both default and sites with the Gutenberg plugin
- Gutenberg 8.9.1

Smartphones
 - Device: iPhone X Simulator, iPhone 11 Pro, Samsung Galaxy Note 10
 - Browser: Safari, Chrome, and Samsung internet (likely this will occur on all browsers)

Observations about this issue
- `.components-popover__content` seems to have conflicting rules. With `min-width: 260px` and yet a dynamically changing inline style that is **less** than the min-width. One example I observed was `max-width: 253px`. The `max-width` should not be less than the `min-width`
- The inline style `max-width` appears to be handled with JS and seems to be at least partially based on the width of the calendar wrapper, which changes depending on month length.
- Increasing the `min-width` on `.components-popover__content` prevents the stuttering for September, but then the calendar placement is even worse on the screen.
- Increasing the negative margin-right on `.components-popover:not([data-y-axis=middle])[data-x-axis=left] .components-popover__content` when the `min-width` is increased helps with placement, but is a bandaid fix.

### PR DESCRIPTION
**Pull request by david-szabo97**
Fixes https://github.com/WordPress/gutenberg/issues/25538 https://github.com/WordPress/gutenberg/issues/24592 https://github.com/WordPress/gutenberg/issues/24482

## Description
Fix popover flickering issues on small screens.

## How has this been tested?
1.
- Open block editor
- Change browser width to ~320px
- Create paragraph block
- Type text
- Click on the Link icon in the toolbar
- Link popover shouldn't flicker anymore

2.
- Create a new post
- Change browser width to ~320px
- Type a title
- Click on the cog
- Change from Block tab to Post tab
- Click the date next to the Publish label
- Calendar popover shouldn't flicker anymore

## Screenshots 
| | |
| - | - |
| image | image |

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by mattwiebe — CHANGES_REQUESTED** [review]
This is a good fix to a really ugly issue. It works well in my testing, but we need to fix either the implementation or the tests in `packages/components/src/popover/test/utils.js` since they're failing on this right now.

**Comment by david-szabo97** [comment]
@mattwiebe  Thanks! Updated the test and added a new one.

**Review by Addison-Stavlo — COMMENTED** [review]
Tested and this seems to solve the problem!  It works well for me and limiting the popover width based on the screen width makes sense.

**Review by mattwiebe — APPROVED** [review]
tests pass, function works, 🚢

**Review by talldan — APPROVED** [review]
This is great, thanks for finally fixing this 🎉

**Pull request merged**
