### PR TITLE
Block preview: fix resize listener

### LINKED ISSUE #38501: Individual patterns not scaled appropriately until after adding
### Description

Pulling from this original issue with scrollbars https://github.com/WordPress/gutenberg/issues/37573, there now seems to be an issue where the height of the patterns preview is off. On my end with 5.9 sans Gutenberg, the experience is one where before adding the pattern, the height is off in the Inserter but, after adding it, the height shows up correctly.

### Step-by-step reproduction instructions

1. Open Inserter > Patterns tab.
2. Scroll through and look at patterns noticing they are cut off.
3. Add a cut off pattern.
4. Open the Inserter > Patterns tab and notice the same pattern you added is the right height.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/26996883/152405319-5546389f-9e82-40ac-b135-f70ba8cb9381.mov

### Environment info

- WordPress 5.9
- No Gutenberg.
- TT2
- MacOS
- Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Fixes #38501.

We're not using `useResizeObserver` correctly. The parent element needs a position. See https://github.com/FezVrasta/react-resize-aware#usage.

This needs to be tested will with different block and patters to make sure the position doesn't mess up the content.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by Mamaduka** [comment]
Great catch. Thank you, @ellatrix.

Do you think we should revert the previous hack that partially resolved the issue? Especially this part with [overflow](https://github.com/WordPress/gutenberg/pull/38175/files#diff-ba97676c79b4678b29dcdb77d3812f7b160b824df934c1289994831df2ce0c0fR40-R52).

Cc @jasmussen, @ndiego, @ixkaito

**Comment by ellatrix** [comment]
Oh I wasn't aware of that. If it doesn't cause any regressions, sure we can remove it. Would be good to check if this fix is good first though for the current issues.

**Comment by jasmussen** [comment]
Thank you for looking at this! I'm happy with whichever fix makes the pattern preview work the best. It might be worth testing with `vh` based patterns, keeping in mind [these observations](https://github.com/WordPress/gutenberg/issues/38501#issuecomment-1029745220) which seem pertinent.

Regarding the overflow rules, I don't have a strong opinion, but I'd like to think we should keep it even if we disable it for testing. Pattern previews, IMO, should be inert. Since it's actual rendered markup, I could easily see some block combinations causing scrollbars intentionally, and I still think those should be disabled in the preview if we can. Not a strong opinion.

**Comment by ndiego** [comment]
I will test this today and report my findings. However, https://github.com/WordPress/gutenberg/issues/38501 indicates this issue is in 5.9, not Gutenberg. It seems many of these pattern preview issues are isolated in 5.9, but do not appear in Gutenberg (ignoring the `vh` issue of course). I am at a bit of a loss how to effectively test these solutions for core.

**Comment by Mamaduka** [comment]
I'm thinking of using forbidden art and directly applying this fix to the core.

Can anyone recommend a theme that uses `100vh` in its patterns or one where I can reproduce the issue the best?

**Comment by jasmussen** [comment]
I believe Blockbase bundles some patterns that are 100vh tall.

**Comment by ndiego** [comment]
This is the pattern content that I have been testing with. Just two columns, one with a Cover block with `100vh` and the other with some text. 

```
<!-- wp:columns {"verticalAlignment":null} -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:cover {"overlayColor":"black","minHeight":100,"minHeightUnit":"vh"} -->
<div class="wp-block-cover" style="min-height:100vh"><span aria-hidden="true" class="has-black-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size">Cover block with 100vh</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:paragraph -->
<p>Some Text</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by Mamaduka** [comment]
I did some initial testing and can confirm that PR fixes #38501.

I can confirm that we cannot remove [overflow](https://github.com/WordPress/gutenberg/blob/8536f6f1aa1df9daa98193964aa8e62cc196cb7a/packages/block-editor/src/components/block-preview/auto.js#L39-L52) or scrollbars are back.

## How tests fix without Gutenberg
_First make sure the plugin isn't active, lost a few minutes because of this_ 😅 

**Inside local tests sites root directory:**
* Backup block-editor.min.js - `mv wp-includes/js/dist/block-editor.min.js wp-includes/js/dist/block-editor.min.bak`
* Copy unminified file - `cp wp-includes/js/dist/block-editor.js wp-includes/js/dist/block-editor.min.js`
* Add patch after line 27193 - `bodyElement.style.position = 'relative';`
* Make sure `SCRIPT_DEBUG` is set to false.

After you're done with testing, restore backup `block-editor.min.js`.

## Screenshots
| Before | After |
| --- | --- |
|CleanShot 2022-02-04 at 16 04 59|CleanShot 2022-02-04 at 16 05 35|

**Comment by ndiego** [comment]
Thanks for the core testing instructions @Mamaduka. I just tested and can confirm this fix works. 🙌

I am still seeing a lot of extra space being generated on specific patterns. This happened before this fix, so a separate issue. 

5.9 without Gutenberg
image

5.9 with Gutenberg
image

**Comment by Mamaduka** [comment]
@ndiego, let's move that into a separate issue.

**Comment by ixkaito** [comment]
The PR looks good to me. I could confirm that it fixes #38501, but it doesn't seem to fix the overflow issue.

Additionally, this patch seems to prevent the first case (100vh blocks with vertical margin) of the vertical expanding issue on Chrome, but on Firefox it doesn't work.

> image

image

However, it doesn't fix the second case (blocks with a height over 100vh) for either browsers.

> image

My conclusion is that we still have to leave the overflow and max height hacks after merging this PR.

**Review by Mamaduka — APPROVED** [review]
Let's merge this. It fixes the linked issue and doesn't cause regressions.

**Pull request merged**
