### PR TITLE
[RNMobile] Revert: RichText: Return early when content has changed in onSelectionChangeFromAztec

### PR DESCRIPTION
**Pull request by SiobhyB**
Reverts WordPress/gutenberg#41682

* `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/4999

## What?

It was recently found that the changes in https://github.com/WordPress/gutenberg/pull/41682 lead to a bug where a block's last character can either be stripped or pushed to a new paragraph. 

## Why?

@dcalhoun's exploration of this issue at https://github.com/WordPress/gutenberg/pull/42046#issuecomment-1171610745 revealed that this will be a complicated issue to fix, so we'll be reverting the original changes for now.

## How?

The changes from the original PR have been reverted. Given this is a revert for an enhancement, no regressions are foreseen.

### CODE REVIEW

**Review by dcalhoun — APPROVED** [review]
LGTM. I was unable to replicate the bug with this PR and the e2e tests appears to be passing as well. Thank you! 🚀

**Comment by kbrown9** [comment]
@dcalhoun @SiobhyB - based on the discussion in PR #42046, it sounds like the bug only occurs on iOS. I haven't been able to reproduce it on Android yet. If it's true that only iOS is affected, do you think we should consider keeping the change for Android? The performance issues on lower-end Android devices can be significant, and it would be nice to improve the performance on those devices soon (assuming no new bugs are introduced, of course).

I am concerned about other hidden bugs, and I think it's reasonable to revert if you're not comfortable keeping the change on Android without further investigation.

**Comment by SiobhyB** [comment]
@kbrown9, thank you for bringing this up for discussion! I agree that it'd be great if at least Android users were able to benefit from [the significant performance improvements](https://github.com/WordPress/gutenberg/pull/41682#pullrequestreview-1010627389) your PR brought.

I'm also a little hesitant for the reasons you describe. It feels like the code around [the RichText component is already tricky to debug](https://github.com/WordPress/gutenberg/pull/42046#issuecomment-1171610745) and it might be preferable to spend a bit more time understanding the code before deciding on a workaround.

My gut is telling me that it may be best to revert for now, to help us get on top of the e2e errors, and then possibly have a new PR for either debugging the core issue or introducing an Android-only workaround. I could be swayed, though. 

@dcalhoun, @fluiddot, pinging to get your opinions here, too. Do you have a preference for how to proceed?

**Comment by fluiddot** [comment]
> I'm also a little hesitant for the reasons you describe. It feels like the code around [the RichText component is already tricky to debug](https://github.com/WordPress/gutenberg/pull/42046#issuecomment-1171610745) and it might be preferable to spend a bit more time understanding the code before deciding on a workaround.

Agreed, the `RichText` component is heavily used so better to be conservative here and review thoroughly the potential Android-only workaround before proceeding.

> My gut is telling me that it may be best to revert for now, to help us get on top of the e2e errors, and then possibly have a new PR for either debugging the core issue or introducing an Android-only workaround. I could be swayed, though.
>
> @dcalhoun, @fluiddot, pinging to get your opinions here, too. Do you have a preference for how to proceed?

Sounds good to me continuing with this PR, at least for addressing the E2E tests failures, and then focus on the Android-only workaround 👍 .

**Comment by SiobhyB** [comment]
Thanks @fluiddot! I'll go ahead to merge this PR for now. @kbrown9, let me know if you'd like to go ahead with the separate Android-only PR and I'd be happy to help in any way.

**Pull request merged**
