### PR TITLE
Disable BlockPreviews from axe-core tests.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Hopes to resolve e2e test failures from the error `"Failed to inject axe-core into frame (about:blank)"` by disabling BlockPreviews from axe tests.  This seems to make sense as Block Previews are disabled from interaction and are used as images, so they should not make sense for a11y tests in the first place.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by talldan** [comment]
Unfortunately it failed on the last run with the `Failed to inject axe-core into frame (about:blank)` error. It seems like a few folks have run into this on the axe repos:
- https://github.com/dequelabs/axe-puppeteer/issues/25
- https://github.com/dequelabs/axe-core-npm/issues/98

Unfortunately both issues are currently closed.

**Comment by talldan** [comment]
I tried a different way on https://github.com/WordPress/gutenberg/pull/26535.

**Comment by Addison-Stavlo** [comment]
> Unfortunately it failed on the last run with the Failed to inject axe-core into frame (about:blank) error.

I wonder if giving the selector for the content instead of the container changes anything.  Running this out of curiousity.

> I tried a different way on #26535.

Great!  I like where that one is going, good catch with the undocumented `disableFrame` function.

**Comment by Addison-Stavlo** [comment]
The template-parts test has passed 3x in a row after a7945f7

**Review by talldan — APPROVED** [review]
Awesome, let's go with this as it's much simpler than #26535.

**Comment by gziolo** [comment]
It still doesn't resolve the issue fully:
https://github.com/WordPress/gutenberg/runs/1325431331?check_suite_focus=true

Screen Shot 2020-10-29 at 11 55 25

**Comment by Addison-Stavlo** [comment]
> It still doesn't resolve the issue fully:

Oof.. the intermittency is a killer.  Should we revert this?

**Comment by gziolo** [comment]
It feels like it helped a bit do it's fine to keep it until there's a better fix discovered.

**Comment by talldan** [comment]
I'll revisit #26535.

**Pull request merged**
