### PR TITLE
Check if experiment enabled for realsies this time

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Does the thing from #52306 except better (adds the missing commit from that PR that addressed feedback)

## Testing Instructions

See #52306

### CODE REVIEW

**Comment by tellthemachines** [comment]
Sorry folks! Hopefully this PR works better 😅

**Review by ramonjd — APPROVED** [review]
Also works 👍🏻

**Review by t-hamano — COMMENTED** [review]
LGTM! In this PR, I can see the intended changes on GitHub as well 👍

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the update/first-pre-beta-4 branch to get it included in the next release: 09a4abe903

**Pull request merged**
