### PR TITLE
Style Engine: Fix wrong property name letterSpacing to lineHeight

### PR DESCRIPTION
**Pull request by suvrodattamitu**
## What?
Fix the wrong property name on style-engine.js from letterSpacing to lineHeight.

## Why?
The property name is wrongly declared.

### CODE REVIEW

**Review by NaeemHaque — COMMENTED** [review]
Thanks, @suvrodattamitu. It looks good.

**Comment by costdev** [comment]
Fixes #48090

**Comment by t-hamano** [comment]
Thanks for the PR, @suvrodattamitu!

Unfortunately, to resolve a single GitHubAction failure, I think you need to rebase with the latest trunk. Is it possible for you to do this?

**Review by t-hamano — APPROVED** [review]
@suvrodattamitu 
Thanks for doing the rebase! All the tests passed.

**Comment by t-hamano** [comment]
@ramonjd @andrewserong 

The name property doesn't appear to be used yet as far as I can tell, but if you have any concerns about merging, please let me know.

**Review by andrewserong — APPROVED** [review]
Good catch, thanks for picking this one up @suvrodattamitu, and thanks for the ping @t-hamano!

No, the `name` property isn't currently used, so this looks safe to merge.

**Pull request merged**
