### PR TITLE
Add natural columns pattern

### PR DESCRIPTION
**Pull request by youknowriad**
This adds the natural columns patter from #20345 
I had to remove a column and replace the images with images from w.org CDN.
It's clear that the choice of images there is lacking (I also don't have any idea how to browse the CDN)

Capture d’écran 2020-03-02 à 3 14 34 PM

### CODE REVIEW

**Comment by MichaelArestad** [comment]
@youknowriad  This is an awesome start. I believe we need to figure out a more structured path forward with example images. I could provide the images I used in my screenshot, but I'd like to get a more curated group of images to use here. I don't think that's a blocker for this, but if we merge this in, we'll want to stub out an issue to improve the images.

**Comment by youknowriad** [comment]
Merged, we can still improve it but I'd love to have a good set of patterns before the next release.

**Comment by mapk** [comment]
@enriquesanchez is working on a set of themed images that share color values.

**Comment by lancewillett** [comment]
> get a more curated group of images to use here

Just curious about this, as the same challenge happens in other parts of the WordPress ecosystem (and likely other open source projects).

High quality images that are open-licensed — rare, zero? 😄

**Comment by youknowriad** [comment]
@lancewillett There's this ticket where they're discussing adding some images to the WP CDN. https://core.trac.wordpress.org/ticket/49580

I know previously we relied on images that fell into the public domain.

**Comment by enriquesanchez** [comment]
Hey @lancewillett! 👋

You're right, we have found it very hard to find a decent set of high-quality public domain images. What we've been doing so far is using images volunteered by members of the community.

**Pull request merged**
