### PR TITLE
Update color palette popover style

### PR DESCRIPTION
**Pull request by jameskoster**
| Before | After |
| --- | --- |
| Screenshot 2022-06-23 at 10 34 22 | Screenshot 2022-06-23 at 10 34 14 |

This PR proposes some small style adjustments that I think improve the appearance of the palette popover.

### Changes

* Increased padding. On trunk the gap between swatches is larger than the popover padding which creates some visual tension in my eye.
* Popover width is calculated mathematically to ensure it wraps 6 swatches snugly.
* Removed a seemingly random bottom margin on the popover contents.

### Still todo

- [x] Apply these changes to the palette popover accessed via the border control which uses a different implementation.

### CODE REVIEW

**Comment by javierarce** [comment]
Nice! I've just tested it and it looks good to me ✨

**Comment by paaljoachim** [comment]
I agree. The changes looks good to me as well!

**Comment by jameskoster** [comment]
cc @ciampo @mirka about how to proceed here. Repeating the work specifically for the color picker in the border control doesn't seem like the optimal approach.

**Comment by ciampo** [comment]
We could try to implement the solution proposed in https://github.com/WordPress/gutenberg/pull/41937#discussion_r914804341 — what do you think, @mirka ?

**Comment by mirka** [comment]
Yes, I'll look into this within the next few days and report back 👍

**Comment by mirka** [comment]
## Progress update

- **Padding**: I'm proposing a solution in #42595.
- **Weird bottom margin**: This can actually be removed via [a prop on `BaseControl`](https://github.com/WordPress/gutenberg/pull/41900/commits/fe9c974f65ab1b162c4d0866fc64f17eb9338b84?w=1). (We're actually aiming to [deprecate this margin](https://github.com/WordPress/gutenberg/issues/38730).)
- **Content width**: I'm kind of indifferent about this at the moment. If it's just for `color-gradients` and BorderControl, it might be too early to abstract into some kind of shared system. I don't mind keeping this ad hoc approach until we see one or two more instances where this is needed.

**Comment by mirka** [comment]
@jameskoster Ok I'm done ✅ 

- Increased padding is now applied in a clean way.
- Width is set without reaching into the internal `.components-popover__content` class.
- Same styling changes are applied on BorderControl:

    https://user-images.githubusercontent.com/555336/180485953-31ef283e-837a-4355-852c-d47dce849a0f.mp4

☝️ By the way, do we care that the checkered pattern for the "transparent" color is now cut off at an awkward place? The `background` pattern isn't adhering to the 4px grid system (the squares are 25px). We might want to address that in a follow-up.

**Comment by jameskoster** [comment]
Thanks @mirka ! :)

The padding is a bit awkward here since we switched to tabs:

Screenshot 2022-07-25 at 10 14 39

But I think that's something to fix in the tabpanel component (https://github.com/WordPress/gutenberg/issues/42320). 

> The background pattern isn't adhering to the 4px grid system (the squares are 25px). We might want to address that in a follow-up.

Agreed. For now I don't think it's a deal-breaker.

**Review by mirka — APPROVED** [review]
> But I think that's something to fix in the tabpanel component (https://github.com/WordPress/gutenberg/issues/42320).

Good call. We can figure out a manageable API once we have the design spec.

I split out the transparent checkered background issue to #42687.

Code-wise, this PR is good to go 👍

**Comment by paaljoachim** [comment]
Sidetrack comment...Related to the Color Panels.
It seems like the Link Color Panel has a Clear color text option while the Text and Background color options do not.
All Color Panels should have the clear option. 
Made an issue for it here: https://github.com/WordPress/gutenberg/issues/42689

**Comment by jasmussen** [comment]
Coming back to this one (thank you for the energy and attention to details!) — I like the padding around the swatches, but the larger padding around the _current_ color spot feels more awkward now, with the same 2px radius looking extra out of place. The panel was originally designed to have that be edge-to-edge, like this:

Screenshot 2022-08-03 at 11 05 10

Screenshot 2022-08-03 at 11 05 14

I believe the previous non-standard padding is something we arrived at exactly because edge-to-edge turned out to be non-trivial to implement. Is that still the case or could we revisit that? CC: @ciampo in case you recall details.

**Comment by jameskoster** [comment]
Oh yes, that would be a nice enhancement.

**Comment by ciampo** [comment]
> I believe the previous non-standard padding is something we arrived at exactly because edge-to-edge turned out to be non-trivial to implement. Is that still the case or could we revisit that? CC: @ciampo in case you recall details.

@mirka 's work with https://github.com/WordPress/gutenberg/pull/42595 may make some of this easier, but we'd still need to take a closer look

**Comment by mirka** [comment]
@jasmussen I'm looking into getting the awkward padding resolved and also get the current color button be edge-to-edge, like in your mockup. One follow-up question: How do we want the edge-to-edge current color button to look when it's under the Solid/Gradient tab switcher? Edge-to-edge with no top-margin?

**Comment by jasmussen** [comment]
Thank you!

> One follow-up question: How do we want the edge-to-edge current color button to look when it's under the Solid/Gradient tab switcher? Edge-to-edge with no top-margin?

That's an excellent question. When there's no switcher, this is the previous flow mocked up:

Color ItemGroup Flow i5

I have an older discarded variant here that I don't love, which nevertheless affords an item above the edge to edge swatch:

Color ItemGroup Flow, i3

My preference, however, would be to always keep the current indicator as the first item, as seen in the mockups for [this pattern addition](#38577):

152792450-44f41640-ca2a-4011-9309-bfdd09d028ae

That's one of the reasons why I've preferred the segmented control. It is secondary to the main color... a property, so to speak, rather than a distinct tab.

**Comment by jasmussen** [comment]
Potentially also relevant, #39452 which details iterations to the duotone configuration, which also keeps the preview/current duotone at the top.

**Comment by mirka** [comment]
Started a tracking issue here: #43014

I love that design! Funnily, to me that flipped order makes the tab panel model even more "correct" 😆

I think the fundamental difference between a tab panel and a radio is that, a radio is for a **"value" that is to be submitted** or persisted, whereas a tab panel is just a temporary way to **expand/collapse information**, much like an accordion. In theory you should be able to expand all the panels into a vertical list and it should still make sense.

The flipped order you propose makes a very logical hierarchy to me:

- Current color ("the value to be submitted")
- Preset colors to choose from
  - Solid
    - Theme colors
    - Default colors
  - Gradient
    - Theme colors
    - Default colors

Whereas previously it was kind of murky:

- Solid
  - Current color ("the value to be submitted")
  - Preset colors to choose from
    - Theme colors
    - Default colors
- Gradient
  - Preset colors to choose from
    - Theme colors
    - Default colors
  - Current color ("the value to be submitted") 👈 this appears twice in the list when there's only one value that will be submitted from this popover

So that leads me to a few more questions:


1. Am I correct to assume that we're also flipping the order for the Gradient picker? This part goes on top of the tabs switcher?

    The gradient swatch from the gradient panel
2. Are we flipping the order when this picker appears in the Global Styles sidebar as well? (minus the edge-to-edge treatment maybe?)

**Comment by jasmussen** [comment]
> Am I correct to assume that we're also flipping the order for the Gradient picker? This part goes on top of the tabs switcher?

Good question. That could be interesting. It seems like that might also line up with some of the hierarchy proposed for gradients in the global styles inspector:
Screenshot 2022-08-05 at 10 39 39

Imprecise mockup, but something along these lines:

Frame 867

That would also answer your second question, as it appears the order in [the Global Styles mockup](https://www.figma.com/file/oEkcAyhIvPFMVEAO8EImvA/Global-Styles?node-id=1700%3A0) I found already orders it _current color/gradient_ first, followed by configuration, then swatches.

If you have a moment to look, @pablohoneyhoney, I'd love your thoughts.

**Pull request merged**
