### PR TITLE
RangeControl: remove margin override and add new opt-in prop

### PR DESCRIPTION
**Pull request by brookewp**
## What?

Added new opt-in prop `__nextHasNoMarginBottom` for useages of `RangeControl` in the Gutenberg codebase and removed margin override. 

## Why?

Part of this project: https://github.com/WordPress/gutenberg/issues/38730
The tl;dr is `BaseControl` has a `margin-bottom` which makes it difficult to reuse and results in inconsistent use. 

## How?

By removing margin overrides in the CSS and adding the prop `__nextHasNoMarginBottom`.

## Testing Instructions

**To note, I've included `comment-author-avatar` and `text-columns` [which have been deprecated](https://wordpress.org/support/article/blocks/#deprecated). I also have included `GalleryEdit` V1, the old version of  `GalleryEdit` (instructions below on how it can still be found and tested).**

### **For `ZoomDropdown`** 

1. Add an image block 
2. Click on the crop icon 
3. Click on the magnifying glass icon to zoom in or out
4. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 25 11 PM

### **For `SpacingInputControl`**

1. Add a group block 
2. Look for 'Dimensions' label in the block settings 
3. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 29 37 PM

### **For `AvatarInspectorControls`**

1. Add an Avatar block
2. Look for 'Image Size' in block settings
3. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 32 58 PM

### **For `ColumnsEditContainer`**

1. Add Columns block to editor
2. Ensure 'Columns' is selected and not a single column
3. Look for range control slider under 'Columns' label in block settings

Screen Shot 2022-11-22 at 6 34 10 PM

### **For `FileBlockInspector`**

1. Add File block
2. Upload / Add PDF from Media Library
3. Look for 'Height in Pixels' label

Screen Shot 2022-11-22 at 6 34 57 PM

### **For `GalleryEdit`**

1. Add Gallery block
2. Upload/Add two or more images from Media Library
3. Ensure 'Gallery' is selected and not a single 'Image'
4. Look for 'Columns' under 'Settings' in block settings
5. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 36 00 PM

#### **For `GalleryEdit` V1**

I have tested this myself (thanks @glendaviesnz for the steps) and it's a bit involved to test, but here are the steps if using `wp-env` and Docker:

1. In `gutenberg/.wp-env.json`, change the first two lines to:

```json
"core": "WordPress/WordPress#5.9",
"plugins": [ "" ],
```

2. Then add Gutenberg 12.0 or lower to `/{DOCKER-CONTAINER}/wp-content/plugins`
3. Run `npx wp-env run cli wp option set use_balanceTags 1` to enable `useBalanceTags`
4. Activate Gutenberg in plugins
5. Add a Gallery block to the editor
6. Look for 'Columns' under 'Settings' in block settings
7. Check that spacing below the slider is the same as before

| **Before (it has a `margin-bottom` of 8px which isn't being applied):**   |  **After (when `margin-bottom` is 0, spacing stays the same):**  |
| ------------- | ------------- |
| Screen Shot 2022-11-23 at 10 33 58 PM  | Screen Shot 2022-11-23 at 10 34 19 PM  |

### **For `LatestComments`**

1. Add Latest Comments block to the editor
2. Look for 'Number of comments' in block settings

Screen Shot 2022-11-22 at 6 36 43 PM

### **For `LatestPostsEdit` & `QueryControls`**

1. Add Latest Posts block
2. Toggle on 'Post content' in the block settings sidebar
3. Look for range control slider under label 'Max number of words in excerpt'
Screen Shot 2022-11-22 at 6 39 54 PM

7. Look for range control slider 'Number of Items' in the block settings sidebar
9. Click on 'Grid View' Icon in the block toolbar
10. Look for range control slider under 'Columns' label in the block settings sidebar

Screen Shot 2022-11-22 at 6 39 58 PM

### **For `MediaTextEdit`** 

1. Add Media & Text block
2. Add / upload image
3. Look for 'Media width' label in the block settings
4. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 44 14 PM

### **For `Overlay`** 

1. Add Post Featured Image block to the editor 
2. Look for 'Overlay Opacity' label in the block settings 
4. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 44 31 PM

### **For `QueryInspectorControls`**

1. Add Query Loop block to the editor
2. Select a template or start with blank
3. Change to 'Grid View' in the block toolbar
4. Ensure parent 'Query Loop' block is selected 
6. Look for 'Settings' in the block sidebar
7. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 47 19 PM

### **For `RSSEdit`**

1. Add RSS block to editor
2. Add RSS feed (e.g. https://developer.wordpress.com/feed/)
3. Change from 'List View' to 'Grid view' in the block toolbar
4. Toggle on 'Display excerpt'
5. Look for range control slider for 'Number of items', 'Display Excerpt', 'Columns' in block settings sidebar

Screen Shot 2022-11-22 at 6 49 25 PM

### **For `SiteLogo`**

1. Add a Site Logo block to editor
2. Add / upload an image
3. See the 'Image Width' label in the block settings sidebar
4. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 50 13 PM

### **For `TagCloudEdit`** 

1. Add Tag Cloud to editor
2. Look for 'Number of tags' in block settings
3. Check that spacing below the slider is the same as before

Screen Shot 2022-11-22 at 6 50 48 PM

#### **For `BorderControl`**:

1. Check out this branch
2. `npm run storybook:dev`
3. Search for 'BorderControl' and click on it
4. Go to 'With Slider' and 'With Slider (Custom Width)'
5. Ensure that sliders are still vertically center with input like below:

Screen Shot 2022-11-29 at 5 34 48 PM

#### **For `ColorPicker`**:

1. While still in storybook with this PR checked out from steps above, search for 'ColorPicker'
2. Click on 'Hex' and change to RGB or HSL to view range control sliders
3. Ensure that sliders are still vertically centered with color input values like below:

Screen Shot 2022-11-29 at 5 45 19 PM

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
Nice work @brookewp ✨ 

All the changes test as advertised for me:

✅ Image: Zoom dropdown
✅ Block Supports: Spacing controls
✅ Avatar: Image size
✅ Columns: Number of columns control
✅ File: Height control
✅ Gallery (Latest): Columns slider
✅ Gallery V1: Columns slider
✅ Latest Comments: Number of comments
✅ Latest Posts: Max words in excerpt, Number of items
✅ Query: Number of items & Columns
✅ Media & Text: Media width
✅ Post Featured Image: Overlay opacity
✅ RSS: Number of items, max words in excerpt, and columns
✅ Site Logo: Image width
✅ Tag Cloud: Number of tags

I found two other uses of the range control that could benefit from the `__nextHasNoMarginBottom` prop to clean up some margin overrides.

- BorderControl uses a [range control](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/border-control/border-control/component.tsx#L106-L117) and overrides its margin [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/border-control/styles.ts#L197-L201)
- ColorPicker uses a [range control](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/input-with-slider.tsx#L62-L72) with inputs for the various parts of a color value. It overrides the margin [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/styles.ts#L42-L44) and [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/styles.ts#L119-L121).

P.S. While it is a very minor edit, we do touch the QueryControls in the components package so that might need a changelog entry.

**Comment by brookewp** [comment]
>I found two other uses of the range control that could benefit from the __nextHasNoMarginBottom prop to clean up some margin overrides.
BorderControl uses a [range control](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/border-control/border-control/component.tsx#L106-L117) and overrides its margin [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/border-control/styles.ts#L197-L201)
ColorPicker uses a [range control](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/input-with-slider.tsx#L62-L72) with inputs for the various parts of a color value. It overrides the margin [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/styles.ts#L42-L44) and [here](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/color-picker/styles.ts#L119-L121).
P.S. While it is a very minor edit, we do touch the QueryControls in the components package so that might need a changelog entry.

Thank you, @aaronrobertshaw, for testing this and for finding more components that could benefit from this! I realize now my search was too limited which is how I missed these - so I'm really glad for this feedback for my upcoming related PRs! 

I've added a changelog and removed the overrides for `RangeControl` in both `BorderControl` and `ColorPicker`. The additional override in `ColorPicker` appears to be for `SelectControl`. I've started working on that already so I'll take note and make sure the margin is removed and the prop added in my upcoming PR! 😄 

*Edited to note that I've added additional testing steps for changes and screenshots to `BorderControl` and `ColorPicker` in PR description under 'Storybook'

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for the continued iteration on this @brookewp!

Also, I meant to say in my earlier review how great the detailed test instructions for this PR are. They really helped expedite the testing and review process 🙇 

I've re-tested everything I checked last time, as well as the `BorderControl` and `ColorPicker` components (both in the editor and Storybook). It is all working as advertised for me.

There's only one small issue we should tweak before landing this. 

The changelog entry I suggested previously should be in the [components package's changelog](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md). My apologies for not being clearer on that one. The main Gutenberg changelog gets updated through the [Gutenberg release process](https://developer.wordpress.org/block-editor/contributors/code/release/).

Maybe something like the following might work for the changelog?

<details>
<summary>Example diff</summary>


```diff
diff --git a/changelog.txt b/changelog.txt
index 8e7f596b07..3a8c82ca84 100644
--- a/changelog.txt
+++ b/changelog.txt
@@ -47,7 +47,6 @@ The following contributors merged PRs in this release:
 -   FocalPointPicker: Update the design of the focal point handle. ([45053](https://github.com/WordPress/gutenberg/pull/45053))
 -   FontSizePicker: Update hint text to match the design. ([44966](https://github.com/WordPress/gutenberg/pull/44966))
 -   CheckboxControl: Move icons out of labels. ([45535](https://github.com/WordPress/gutenberg/pull/45535))
--   RangeControl: remove margin overrides and add new opt-in prop. ([45985](https://github.com/WordPress/gutenberg/pull/45985))
 
 #### Block Editor
 
diff --git a/packages/components/CHANGELOG.md b/packages/components/CHANGELOG.md
index cee4723a7e..c049f17caa 100644
--- a/packages/components/CHANGELOG.md
+++ b/packages/components/CHANGELOG.md
@@ -14,6 +14,7 @@
 
 -   `TabPanel`: Add ability to set icon only tab buttons ([#45005](https://github.com/WordPress/gutenberg/pull/45005)).
 -   `InputControl`, `NumberControl`, `UnitControl`: Add `help` prop for additional description ([#45931](https://github.com/WordPress/gutenberg/pull/45931)).
+-   `BorderControl`, `ColorPicker` & `QueryControls`: Replace bottom margin overrides with `__nextHasNoMarginBottom` ([#45985](https://github.com/WordPress/gutenberg/pull/45985)).
 
 ### Experimental
 

```
</details>

I'll approve this one now in anticipation of the changelog tweak, so it's ready to go.

**Comment by brookewp** [comment]
@aaronrobertshaw, thanks for taking another look and for the changelog info! I thought I was in the `packages/components` file, so my mistake for not seeing the differences. 🙇‍♀️  It's a new process for me, so it's very helpful to see an example diff. I'll keep this in mind for future PRs as well. 🙂 Thank you again for your time and all the feedback!

**Pull request merged**
