### PR TITLE
Components: Add spinner

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Description
Adds a new CSS-in-JS Spinner component.

Something is wrong with the snapshot tests, haven't figured it out yet, maybe @ItsJonQ can diagnose it.

## How has this been tested?
Unit tests and storybook

## Screenshots 

https://user-images.githubusercontent.com/24264157/108519521-8e133000-727e-11eb-8d9e-9d823e61aa79.mov

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- N/A I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ItsJonQ** [comment]
@sarayourfriend Haiii! The component looks okay. Although, I'm not sure why the snapshot test has an entry that looks like this:

```
exports[`props should render size 1`] = `
"Snapshot Diff:
  Comparing two different types of values. Expected [32mobject[39m but received [31mnull[39m."
`;
```

**Comment by sarayourfriend** [comment]
Yeah that's what I was confused about. I need to do some fiddling around with this a little more to get this to a place we can merge it with those tests.

**Comment by ItsJonQ** [comment]
@sarayourfriend Thank you! I checked the other places where we use snapshot diffing. The implementation looks correct 🤷

**Comment by sarayourfriend** [comment]
@ItsJonQ fixed! Was missing the `beforeEach` part 🤦🏼‍♀️

**Review by ItsJonQ — APPROVED** [review]
🚀 from me @sarayourfriend !! I added some README + JSDoc examples really quickly :)

Edit: Ooo! I also made sure it was exported from the `index.js` file.

**Pull request merged**
