### PR TITLE
Revert "[Document Settings]: Add summary panel version 1"

### LINKED ISSUE #40124: It is not clear that the title and excerpt field in the Summary panel can be edited
## What problem does this address?
In the new summary panel in the document settings, it is not obvious that the title and excerpt are editable fields.
They look like plain text.

two paragraphs of plain text are visible below the featured image input field.

## What is your proposed solution?

Please re-consider the usability impact that removing visible and recognizable input fields have for users.

Please re-add a visible border or outline so that the fields can be recognized as editable input fields.

It is also not clear how to resize the excerpt field. It does accept more than one line, but it is not clear that it only expands when you write a text that is long enough.

### PR DESCRIPTION
**Pull request by ntsekouras**
Reverts WordPress/gutenberg#39973

Fixes: https://github.com/WordPress/gutenberg/issues/40124

We are going to exclude `Post summary` panel from `6.0` as it's kind of big change in the last minute and it might need a bit more testing/feedback in the plugin.

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]

**Comment by jasmussen** [comment]
Thank you!

Landing this feature in the plugin, even if just for a few days, has highlighted a few things that ultimately suggests it needs a little more time in the oven, but also that it should return in the future based on what we've learned so far!

The main piece that has been great is the the colophon-like imprint appearance the panel gives off. It is in a very literal sense, a summary of the document, and serves to provide an elegant overview. In fact, when this returns, we should consider adding and integrating this summary also in the pre-publish flow. 

What landed, however, was a minimal V1 version of what was outlined in [the original ticket](https://github.com/WordPress/gutenberg/issues/39082), missing a few key features such as the ellipsis control to manage items inside. In effect this omission came with a few downsides:

* Instead of becoming mainly a summary based on content filled out (related: #40124), it fully absorbed Excerpt and Featured Image panels.
* By way of absorbing those panels, it gave prominence to Excerpt and Featured Image that perhaps was not deserved; the features are crucial when you want them, but not all posts need these. That causes a resting state in many post editors that perhaps emphasized the wrong things.

Both of these issues feel very solvable through the ellipsis functionality, letting us find an interface that can manage prominence while still generating a summary of metadata intentionally added. The PR and brief time in trunk has definitely provided valuable insights to further guide the direction of #39082, so thank you all for letting us try this.

Ultimately the V1 was perhaps too small, and at the same time, too big of a change to land for 6.0. Let's convert it to a branch again, and let it evolve so it can return in the future 🚀

**Comment by jasmussen** [comment]
Fixes #40124.

**Comment by paaljoachim** [comment]
It sounds like a very good idea keeping the summary panel in the plugin for a while so that we can get used to it, and over time also notice various things that will need to be adjusted before adding it into core.

**Comment by carolinan** [comment]
Is there still a branch where the panel can be tested?

**Comment by ntsekouras** [comment]
>Is there still a branch where the panel can be tested?

I guess you can check the [original PR](https://github.com/WordPress/gutenberg/pull/39973).

**Comment by jasmussen** [comment]
It's worth noting that a new variant of this would likely keep the Summary panel static rather than editable.

**Pull request merged**
