### PR TITLE
RangeControl: Convert unit tests to typescript

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Depends on:
- https://github.com/WordPress/gutenberg/pull/40535

Related:
- https://github.com/WordPress/gutenberg/issues/40507
- https://github.com/WordPress/gutenberg/pull/41444

## What?

Converts the `RangeControl` unit tests to typescript.

## Why?

Completes the process of converting the `RangeControl` to TypeScript alongside #40535 & #41444

## How?

- Coverts unit test file to TypeScript and resolve typing errors

## Testing Instructions

1. Run unit tests and ensure they are all passing: `npm run test-unit /packages/components/src/range-control/test`

### CODE REVIEW

**Review by ciampo — APPROVED** [review]
Great work! Code changes LGTM, tests still pass, and there's not TS errors 🚀 

Optionally, we could look into partially rewriting these tests using `@testing-library/user-event` (similarly to what done in #40697 and #41270). In case you feel like working on it, I'll leave it up to you if you want to add those changes in this PR, or apply them in a follow-up PR.

**Comment by stokesman** [comment]
> Optionally, we could look into partially rewriting these tests using `@testing-library/user-event`

The key word "partially" 😄. I had a go at it a few days ago and realized there's no user-event way to manipulate a `input type=range` https://github.com/testing-library/user-event/issues/871.

**Comment by ciampo** [comment]
> > Optionally, we could look into partially rewriting these tests using `@testing-library/user-event`
> 
> The key word "partially" 😄. I had a go at it a few days ago and realized there's no user-event way to manipulate a `input type=range` [testing-library/user-event#871](https://github.com/testing-library/user-event/issues/871).

Oh well 😅 We could at least stop using `document.querySelector` and switch to `getByRole` or something similar

**Comment by aaronrobertshaw** [comment]
Thanks for the suggested improvements 👍 

I've removed the use of `querySelector` from these tests. 

The one catch here was being able to select the icons as they are only spans with no alt, text, or role. I've added a `role="img"` to the `RangeControl`'s icons. Is this ok? Or, does that create different problems?

As for leveraging `@testing-library/user-event` I'd like to address that in a follow-up even if it is only a partial conversion.

**Comment by mirka** [comment]
> The one catch here was being able to select the icons as they are only spans with no alt, text, or role. I've added a `role="img"` to the `RangeControl`'s icons. Is this ok? Or, does that create different problems?

I think this is safe, especially since the svg element is `aria-hidden="true"` to begin with.

But... to be honest I don't think the "should render with icons" test is worth contorting ourselves to avoid a `querySelector`. Querying for the `img` role isn't making our test robust (it will break when we add some kind of other image to the component), and we still need to check for the CSS class names anyway. We might as well just querySelector the class names — it's actually more robust in this case.

**Comment by ciampo** [comment]
I'm actually not sure about adding the `role="img"` to icons — that should be done only if we believe that they should be announced by assistive technology, i.e. if they carry any "semantic value" (which they may not, in case they're added only for "visual presentation")

**Comment by aaronrobertshaw** [comment]
Thanks for the guidance @mirka & @ciampo 🙇 

I've removed the `role="img"` from the Icons and reverted the test to use `querySelector`. (https://github.com/WordPress/gutenberg/pull/41445/commits/57fb884fcca677f815e2c22eff742e021f4fe556)

**Review by ciampo — APPROVED** [review]
LGTM 🚀

**Pull request merged**
