### PR TITLE
CardHeader used instead of CardFooter

### PR DESCRIPTION
**Pull request by gvgvgvijayan**
## What?

CardHeader used instead of CardFooter at the last sub/child component of Card component

## Why?

Give correct sample of Card and it's sub component usage.

### CODE REVIEW

**Review by carolinan — APPROVED** [review]

**Review by skorasaurus — APPROVED** [review]
looks good to me; thanks.

**Comment by gvgvgvijayan** [comment]
Gentle reminder about this PR not yet merged. Please share if anything need from my side. Thanks.

**Review by annezazu — APPROVED** [review]

**Comment by annezazu** [comment]
Hey there. Can you try merging in latest trunk? Right now, some of the automated items have failed/didn't report and it's making it so it can't be merged.

**Comment by gvgvgvijayan** [comment]
@annezazu synced with latest trunk, thanks.

**Comment by t-hamano** [comment]
GitHub Action seemed to have stopped, but after closing and reopening this PR, it seems to have started working again. I also think this change makes sense, so I'm merging it.

@gvgvgvijayan Thanks for your contribution!

**Comment by gvgvgvijayan** [comment]
Thanks for rechecking @t-hamano 🙂

**Pull request merged**
