### PR TITLE
Add filter to REST API image edit.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Description
Add an action after image as been cropped. 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by TimothyBJacobs — CHANGES_REQUESTED** [review]
This can't accept the request object. When 5.6 lands we'll be changing the request format (#23369) to be more robust. We'll be able to provide backwards compatibility for the old request format, but any hooks that are looking at the request object will no longer work since they'll be expecting a different format.

**Comment by spacedmonkey** [comment]
> This can't accept the request object. When 5.6 lands we'll be changing the request format (#23369) to be more robust. We'll be able to provide backwards compatibility for the old request format, but any hooks that are looking at the request object will no longer work since they'll be expecting a different format.

What if we removed $requeset and $response for now? Maybe add `$old_attachment_id`. That way we can change the api without worrying about backwards compatiblity here?

**Comment by TimothyBJacobs** [comment]
That would work. Though at that point is it better than checking for `parent_image`?

**Comment by spacedmonkey** [comment]
As discussed on [slack](https://wordpress.slack.com/archives/C02RQC26G/p1593294414483500). 

I have made the action simplier. As this is a change in behavior to create a new attachment, we should make easy to migrate data from old attachment to new one.

**Comment by azaozz** [comment]
Looks good. Just couple more things that may be "perhaps good to have"?

- Should the action be before or after the response is prepared? Currently it's after, so any changes to the attachment post and image meta will not be in the response. May make sense to fire the action earlier: when everything is in the DB, right after `wp_update_attachment_metadata()`?

 - Would it make sense to have a filter on the new attachment post data before it is inserted? There are already `wp_insert_attachment_data`, `add_attachment`, `save_post_attachment`, `save_post`, and `wp_insert_post` at various stages while or after inserting an attachment, but it's not easy to determine if the new attachment is for an edited image. Can perhaps look at the file name if it has `-edited` before the extension.

Alternatively, looks like it can pass another key in `$unsanitized_postarr` to indicate what the attachment post is for. It will be available in `apply_filters( 'wp_insert_attachment_data', $data, $postarr, $unsanitized_postarr );` that runs before saving to the DB.

**Comment by spacedmonkey** [comment]
@azaozz Decided to follow your advise and convert to a filter. This is a filter that is extremely easy to contain on refactor. It allows for filtering of meta but gives the context of the original attachment id. The filter could be used to migrate data. 

Do you think we need filter and an action?

**Review by TimothyBJacobs — APPROVED** [review]
This filter looks good to me.

**Comment by ellatrix** [comment]
I don't think we should be adding a filter for now. It might be that for the 5.6, we remove this endpoint.

**Comment by azaozz** [comment]
Right, lets keep this to passing the new arg (`parent_image`) in the new image meta. Technically that's enough to detect an edited image, get the old attachment post ID, do whatever needs to be done, etc.

**Pull request merged**
