### PR TITLE
Remove the textdomain from block library

### PR DESCRIPTION
**Pull request by notnownikki**
Fixes: https://github.com/WordPress/gutenberg/issues/12167

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Nice one, thanks 👍

**Comment by notnownikki** [comment]
This fails the lint checks though, do we need to remove that check?

**Comment by gziolo** [comment]
Google says you can disable them: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file :)

**Comment by pento** [comment]
@notnownikki: You should be able to exclude it by adding this to the `phpcs.xml.dist` file:

```xml
<rule ref="WordPress.WP.I18n.MissingArgDomainDefault">
	<exclude-pattern>packages/block-library/src/*</exclude-pattern>
</rule>
```

**Review by pento — DISMISSED** [review]
Feel free to dismiss this block once the `// phpcs:ignore` comments are replaced with the `phpcs.xml.dist` config. 🙂

**Comment by notnownikki** [comment]
Great, have replaced the comments :)

Could someone dismiss the block for me? I can't do that.

**Review by swissspidy — APPROVED** [review]

**Pull request merged**
