### PR TITLE
Add Script Versioning for Cache Busting

### PR DESCRIPTION
**Pull request by kopepasah**
This commit adds script versioning using `filemtime`.

### CODE REVIEW

**Review by aduth — APPROVED** [review]
Hey, this looks great and I'm fine to merge as-is.

One question: Do we want this to apply specific to the `SCRIPT_DEBUG` context? Or would you rather keep this as-is since we don't have a solution for the non-debug case (and I assume this would be addressed separately given discussion at #440).

**Comment by kopepasah** [comment]
Yes, we should address that once the build process provides separate files for development and production.

**Comment by aduth** [comment]
Sounds good, thanks.

**Comment by aduth** [comment]
I noticed today that we're missing versions for files enqueued during `gutenberg_scripts_and_styles`:

- https://github.com/WordPress/gutenberg/blob/f58fea4/index.php#L162
- https://github.com/WordPress/gutenberg/blob/f58fea4/index.php#L216

**Comment by kopepasah** [comment]
@aduth good catch. I created another PR to address this issue: #509

**Pull request merged**
