### PR TITLE
Block library: Extract `deprecated` field to their own files

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Part of aligning block library to Block Registration API RFC #13693.

It's all about moving `deprecated` fields to their own file to follow the proposal drafted in RFC.

Updated blocks:
- `Gallery`
- `Image`

Removed block deprecations
- `Heading` - see https://github.com/WordPress/gutenberg/pull/15057#issuecomment-493063939
- `List` - see https://github.com/WordPress/gutenberg/pull/15057#issuecomment-493063939

## How has this been tested?

`npm test`
`npm run test-e2e`

Manually tested whether all blocks load as before.

### CODE REVIEW

**Comment by ellatrix** [comment]
It's a bit hard to review this without any tests for deprecated blocks. Would it be possible to add some simple tests to see if deprecated block structures are converted correctly?

**Comment by gziolo** [comment]
> It's a bit hard to review this without any tests for deprecated blocks. Would it be possible to add some simple tests to see if deprecated block structures are converted correctly?

Good idea. I will add something based on the existing fixtures. I think Columns and Paragraph block have some coverage already:
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/fixtures/blocks/core__paragraph__deprecated.html
- https://github.com/WordPress/gutenberg/blob/master/packages/e2e-tests/fixtures/blocks/core__columns__deprecated.html

**Comment by gziolo** [comment]
@ellatrix, I opened #15268 with tests covering all possible deprecations. Let's merge it first and then rebase this one.

**Comment by gziolo** [comment]
Blocked by #15268.

**Comment by gziolo** [comment]
Based on my question https://github.com/WordPress/gutenberg/pull/15268#issuecomment-487987106:

> I tried to add tests for List and Heading blocks but it looks like deprecated versions left for those blocks don't work anymore. It looks like #7349 was added temporary and wasn't planned to be supported for long. Does it mean we can safely remove them?

I can confirm that we those deprecations won't work anymore for List and Heading blocks and can be safely removed. The related logic that handles `source: property` was removed in #8276.

**Review by youknowriad — APPROVED** [review]

**Pull request merged**
