### PR TITLE
Update legacy-widget-block.md

### PR DESCRIPTION
**Pull request by cameronjonesweb**
`$control` is not the first argument passed to the event. Anyone who tries to use this code as is will encounter an error stating `$control.find is not a function`.

This blog post will also need updating: https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/

### CODE REVIEW

**Review by jorgefilipecosta — APPROVED** [review]
Yes, it seems the event is the first parameter and the code needs an update. cc: @noisysocks to update post https://make.wordpress.org/core/2021/06/29/block-based-widgets-editor-in-wordpress-5-8/.
THank you for this fix 👍

**Comment by noisysocks** [comment]
Done, thanks for the ping.

**Comment by noisysocks** [comment]
@cameronjonesweb: Could you please rebase `origin/trunk` into this branch?

**Comment by cameronjonesweb** [comment]
@noisysocks done

**Pull request merged**
