### PR TITLE
Replaced shown with visible

### PR DESCRIPTION
**Pull request by garretthyder**
## Description
Updated word choice for better context.
shown is past tense
visible is the antonym of hidden

## How has this been tested?
It hasn't

## Types of changes
Verbiage change

### CODE REVIEW

**Comment by michelleweber** [comment]
What text exactly does this change?  What is the full before/after?

**Comment by garrett-eclipse** [comment]
Hi @michelleweber 
The commit is here - https://github.com/WordPress/gutenberg/pull/7757/commits/d509c7c8cf13058e48ddbe6bc28116195f22c5dc

Original - 'The download button is shown.' / 'The download button is hidden.'
Updated - 'The download button is visible.' / 'The download button is hidden.'

**Comment by michelleweber** [comment]
Looks fine!

**Review by aduth — APPROVED** [review]
Code-wise this is fine.

**Comment by garrett-eclipse** [comment]
@aduth I believe that does it if all the checks pass. Let me know if I'm doing it wrong.

**Comment by aduth** [comment]
Looks great. Thanks!

**Comment by garrett-eclipse** [comment]
Awesome, Cheers

**Pull request merged**
