### PR TITLE
[RNMobile] Update theme updates to use the approach that guarantees delivery

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** wordpress-mobile/gutenberg-mobile#3163
**Related PRs:**
- **Gutenberg-Mobile:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3376
- **iOS** https://github.com/wordpress-mobile/WordPress-iOS/pull/16282

📓 This PR can merge independent of any of the other changes.

## Description
This is connected to the refactor work being done in https://github.com/wordpress-mobile/WordPress-iOS/pull/16282. Previously the theme update events could be lost if the editor was still starting up and required a refresh call. With the "guaranteed" delivery that was added back in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2366, we can now set the theme and trust its delivery will happen.

## How has this been tested?

This can be tested by running the regression [test suite](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/editor-theme.md):
```
- [ ] Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001) 
- [ ] Default Gradients - Check that default gradients still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [ ] Custom Colors - Check that custom colors load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)
- [ ] Custom Gradients - Check that custom gradients load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
- [ ] Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)
```

## Types of changes

Bug Fix 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by chipsnyder** [comment]
@dcalhoun @enejb CC'ing you two since you're the release wranglers for this release. This isn't required for 1.51 but I would like to get it merged for that release if possible. Added you as reviewers just so you're aware.

**Comment by enejb** [comment]
Thanks for starting this @chipsnyder! 

Can you add a bit more context to this change? 
I don't quite understand what you mean by delivery? What is being deliver? The update?

`Update theme updates` I am not sure I follow this. In WordPress you can update themes when there is a new version available from wordpress.org theme repository. But I am not sure how or why that is needed by the editor. 

Thank you!

**Comment by chipsnyder** [comment]
Hey @enejb 👋 

Yup the change here is to modify `bridgeModule.sendEventIfNeeded` to use a method that calls `bridgeModule.sendEvent`. 

The `updateTheme` naming is an event picked up by the Gutenberg Editor that applies theme-specific settings like Custom Colors and Gradients. In the future, this is how we'd pass along font sizes as well. 

The way the bridge between native and ReactNative works means that certain calls can be lost while the editor initializes. So the `sendEventIfNeeded` call allows events to try and be delivered but are deemed not important so they don't have to make it. These would be calls like media upload progress percentages. 

The `sendEvent` function will queue up the events if the editor hasn't finished initializing and replay them once the editor has started.

**Review by antonis — APPROVED** [review]
Great work @chipsnyder 👍 
This LGTM according to your explanation [here](https://github.com/WordPress/gutenberg/pull/30847#issuecomment-819898598) and works as expected (tested via https://github.com/wordpress-mobile/WordPress-iOS/pull/16282) 🎉

**Comment by enejb** [comment]
Thanks for the explanation @chipsnyder

**Pull request merged**
