### PR TITLE
Migrate Splitting Merging test to Playwright

### PR DESCRIPTION
**Pull request by pooja-muchandikar**
## What?

Part of https://github.com/WordPress/gutenberg/issues/38851.
Migrate [splitting-merging.test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/splitting-merging.test.js) to its Playwright version.
## Why?

Part of https://github.com/WordPress/gutenberg/issues/38851.
## How?

See[ MIGRATION.md](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md) for migration steps.
## Testing Instructions

Run` npm run test-e2e:playwright test/e2e/specs/editor/various/splitting-merging.spec.js`

### CODE REVIEW

**Comment by Mamaduka** [comment]
Hi, @pooja-muchandikar

It looks like newly migrated tests are failing on CI.

**Comment by Mamaduka** [comment]
@pooja-muchandikar, it looks like something went wrong with rebase, and now the branch contains more changes.

**Comment by pooja-muchandikar** [comment]
Hi @Mamaduka,

Previously, it was showing conflicts so I tried to resolve the conflicts in last push. The conflicts got resolved but somehow the other file changes are also visible and now again it is showing conflicts 😞. 

Should I close this and create a new PR with the latest changes?

**Comment by Mamaduka** [comment]
Hi, @pooja-muchandikar

That would probably be easier.

Thank you!

**Comment by pooja-muchandikar** [comment]
Sure, 

Closing this PR as suggested will create new PR with latest changes..

**Pull request closed without merging**
