### PR TITLE
Make inline toolbar navigable by arrow keys

### LINKED ISSUE #43564: Inline toolbar keyboard navigation should be consistent with block toolbar
### Description

Currently, the block toolbar, once focused, is navigable with the Arrow keys, because it uses the `NavigableToolbar` component. 

But the inline toolbar, such as appears for Image block captions, doesn't use the same component, so it can only be navigated with Tab key. Ideally, keyboard behaviour should be consistent across both toolbars. We could use `NavigableToolbar` for the inline toolbar too.

### Step-by-step reproduction instructions

1. Add an Image block to the page, and insert an image in it;
2. Caption should be focused automatically;
3. Press Shift+Tab to enter the caption toolbar;
4. Note that the toolbar buttons can only be reached by using Tab or Shift+Tab.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by apmatthews**
## What?

Allows users to navigate the inline toolbar using arrow keys rather than tabs.

## Why?

Users can navigate the block toolbar using arrow keys. The inline toolbar should behave the same way for consistency.

Resolves #43564

## How?

Adds the `NavigableToolbar` component to the inline toolbar.

## Testing Instructions

1. Add an Image block to the page, and insert an image in it;
1. Caption should be focused automatically;
1. Press Shift+Tab to enter the caption toolbar;
1. Note that the toolbar can be navigated using arrow keys.
1. Press Tab and note that focus moves back to the caption.

### CODE REVIEW

**Comment by apmatthews** [comment]
I will follow up on these failing tests next week.

**Review by alexstine — COMMENTED** [review]
@apmatthews Thanks for the improvements. Could you please refresh the branch and maybe tests will pass?

**Comment by alexstine** [comment]
@apmatthews Maybe try one more refresh? Lots seems to be changing around this at the moment.

**Comment by apmatthews** [comment]
@alexstine I've just kicked it off once more. If tests do not pass this time, I'll try and find some time this week to pull it down and debug whatever is failing. The failures don't seem related at first glance, but who knows 🤷🏻. Thanks for bumping it!

**Review by alexstine — APPROVED** [review]
LGTM.

**Pull request merged**
