### PR TITLE
[RNMobile] Update mobile iOS Ruby version to from 2.7.4 to 3.2.2.

### PR DESCRIPTION
**Pull request by derekblank**
## What?
Bumps the iOS Ruby version to 3.2.2.

Related:
* https://github.com/wordpress-mobile/gutenberg-mobile/pull/6180

## Why?
The WPiOS Ruby version was updated to 3.2.2 in https://github.com/wordpress-mobile/WordPress-iOS/pull/21498.

## How?
Updates `packages/react-native-editor/ios/.ruby-version` to 3.2.2.

## Testing Instructions
`rbenv install 3.2.2` should run successfully.

### CODE REVIEW

**Comment by geriux** [comment]
Hey @derekblank 👋 thanks for updating this!

I was able to run the demo app successfully locally 🚀 

This branch doesn't have the latest changes that are in the `trunk` branch, which enables Hermes but I don't think this change would affect that.

I would recommend updating the ruby version for the XCFramework as well, I saw there is a PR [to do that here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6180) but some CI checks failed. Maybe it's worth checking what's causing that failure and updating both the demo app and the XCFramework at the same time. What do you think?

**Review by mokagio — APPROVED** [review]
Looking good. 

My GitHub shows a beta thing that does not look related to the changes in this PR, but I thought worth surfacing:

image

**Comment by derekblank** [comment]
> Looking good.
> 
> My GitHub shows a beta thing that does not look related to the changes in this PR, but I thought worth surfacing:
> 
> image

Thanks for the review @mokagio  - I believe this error you're seeing was related to a flaky E2E test failure that I restarted (and now looks to be succeeding).

**Comment by derekblank** [comment]
> Hey @derekblank 👋 thanks for updating this!
> 
> I was able to run the demo app successfully locally 🚀
> 
> This branch doesn't have the latest changes that are in the `trunk` branch, which enables Hermes but I don't think this change would affect that.
> 
> I would recommend updating the ruby version for the XCFramework as well, I saw there is a PR [to do that here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6180) but some CI checks failed. Maybe it's worth checking what's causing that failure and updating both the demo app and the XCFramework at the same time. What do you think?

Thanks for pointing out the existing [Gutenberg Mobile Ruby 3.2.2 PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6180) that @SiobhyB had started, @geriux! I made some updates to that PR, and the CI now appears to be passing. Additionally, I merged Gutenberg `trunk` with this PR in order to incorporate the Hermes changes. While Gio has already approved this Gutenberg PR, I added you as a reviewer to the Gutenberg Mobile PR just to check if there were any further changes needed there. If not, feel free to approve and merge both PRs to update the Ruby version for the Demo app and XCFramework at the same time.

**Review by geriux — APPROVED** [review]

**Comment by SiobhyB** [comment]
> Thanks for pointing out the existing https://github.com/wordpress-mobile/gutenberg-mobile/pull/6180 that @SiobhyB had started, @geriux!

I just wanted to chime in to say thank you for picking that up! I had begun that PR just before the meetup and it slipped off my radar, I appreciate you both being so proactive and picking it up again 🙇‍♀️

**Pull request merged**
