### PR TITLE
Add "busy button" and Publish Flow.

### PR DESCRIPTION
**Pull request by mtias**
image

See #3496.

- [ ] Figure out how to distinguish "publishing..." from "updating...".

cc @jasmussen @karmatosed

### CODE REVIEW

**Comment by aduth** [comment]
Pushed ec4dc7c which implements the `isPublishingPost` selector. One challenge with this implementation was knowing the transaction ID associated with the in-progress save. Since we previously generated a unique ID, we couldn't necessarily know this without otherwise saving a reference to it. With my changes, this was updated to a static value that can be referenced directly by the selector. I don't _think_ this should be an issue, both because we don't allow simultaneous save requests to occur, but even if we did, from what I can tell redux-optimist will [still clear itself out](http://jsbin.com/qaxekidipe/3/edit?html,js,console) when the doubled-up transaction is committed. Another option could be to check whether a transaction has already begun when saving the post, and commit it prior to beginning a new one.

cc @youknowriad

**Comment by youknowriad** [comment]
Changing the label of the button while saving introduces a weird flickering (the button size changes and reverts quickly) while auto-saving. Do you we could avoid changing the label and just add an `is-busy` style?

**Comment by jasmussen** [comment]
> Changing the label of the button while saving introduces a weird flickering (the button size changes and reverts quickly) while auto-saving. Do you we could avoid changing the label and just add an is-busy style?

This is a good point, but it may be worth it. Two options I can think of:

1. We add a min-width to the button, so the label can increase in width, without a judder. Probably not scalable with translations.
2. We add a `transition` to the button width, and see if that makes it feel less jarring — it could potentially be a non-issue.

What do you think?

**Comment by youknowriad** [comment]
Fixing the width would have been great but it's not possible with translations. I can leave with it, but I think we should avoid the label changing at least for "auto-saves" because it's not an "explicit" click and it's a duplicated information with the Saving indicator.

**Comment by jasmussen** [comment]
Agreed, we have the save status indicator for the autosave, the button itself should probably be only for publishing, updating, and scheduling, as well as "working" versions of those. 

Riad in a little noodling on this branch I can't get the CSS `transition` to have any effect on the width of this — is there something I'm missing or is it just not possible?

**Comment by youknowriad** [comment]
> Riad in a little noodling on this branch I can't get the CSS transition to have any effect on the width of this — is there something I'm missing or is it just not possible?

I think it's because the width property do not change, it's the content that changes

**Comment by jasmussen** [comment]
I think you're probably right. I tried some tricks, but couldn't get it to work.

**Comment by StaggerLeee** [comment]
What is that "gradient" on your button ?

**Comment by mtias** [comment]
It's a transition that signals something is happening and the button is not just disabled.

**Pull request merged**
