### PR TITLE
Clarify the wp-block-styles documentation

### PR DESCRIPTION
**Pull request by kjellr**
This PR adds some clarification to the `wp-block-styles` documentation. 

Previously, it stated:

> Core blocks include default styles. The styles are enqueued for editing but are not enqueued for viewing unless the theme opts-in to the core styles. If you’d like to use default styles in your theme, add theme support for `wp-block-styles`

This is misleading, since what most folks would consider "default" styles (from `style.css`) _are_ enqueued by default. The opt-in actually applies only to the more opinionated styles in `theme.css`. This PR makes that distinction more clear: 

> Core blocks include default structural styles. These are loaded in both the editor and the front end by default. An example of these styles is the CSS that powers the columns block. Without these rules, the block would break entirely on the front end. 
> 
> The block editor allows themes to opt-in to slightly more opinionated styles for the front end. An example of these styles is the default color bar to the left of blockquotes. If you'd like to use these opinionated styles in your theme, add theme support for `wp-block-styles`

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Beautiful improvement.

Stumbled briefly on this one: 

>  Without these rules, the block would break entirely on the front end.

Break how? If you read this quickly you might simply assume you see a table with borders, but in fact you'd see all your blocks in a single column as if they were not in any columns block at all. Fundamentally the columns block is probably good to highlight because it is profoundly useless without them. But I wonder if we can dramatize and clarify at the same time:

>  Without these rules, the block would break entirely on the front end, with a broken layout and no columns to find at all.

**Comment by kjellr** [comment]
> Without these rules, the block would break entirely on the front end, with a broken layout and no columns to find at all.

Good suggestion! I think I can simplify that a little bit to: 

> Without these rules, the block would result in a broken layout containing no columns at all.

**Comment by kjellr** [comment]
(Just trying to get these tests to pass... They keep throwing errors. 😕)

**Comment by jasmussen** [comment]
Isn't there a docs command line change you need to run? The failure could be legitimate. I'll defer to @mkaz on that

**Comment by kjellr** [comment]
I _think_ that shouldn't be necessary here since I'm just changing some existing text. But I'll take a closer look once these tests finish running.

**Comment by jasmussen** [comment]
They've failed a ton lately, and often pass with two or three restarts.

**Pull request merged**
