### PR TITLE
Fix broken links in handbook

### PR DESCRIPTION
**Pull request by ajlende**
# Description

This fixes a handful of links from the docs that were broken either in GitHub or in the Block Editor Handbook including the one mentioned in #15767.

Did a quick check via grep for relative links that don't match the criteria in the [Using Links](https://github.com/WordPress/gutenberg/blob/master/docs/contributors/document.md#using-links) docs, confirmed which ones were actually broken, and updated them accordingly.

```sh
grep -REoh '\(/[^)]*\)' docs/**/*.md | \
	grep -Ev '/docs/.*\.md' | \
	grep -Ev '/packages/[^/]*/README.md' | \
	grep -Ev '/packages/components/src/.*/README.md'
```

## Types of changes

Documentation fixes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mkaz** [comment]
Thanks for these contributions, it does fix a couple of links but I don't think we want to hardcode the links to the github.com repository, they should stay relative and on publish they get translated to Block Editor handbook links also.

Especially now since the handbook is being published off the release tag, and the links will point to the master branch, things will get out of sync or break when moved.

**Comment by ajlende** [comment]
> I don't think we want to hardcode the links to the github.com repository

@mkaz I agree. I suppose this is more of a stopgap to fix 404s until the code to generate the rest of the handbook is written.

There are already a lot of links hardcoded to GitHub that exist (40 results in 22 files in `/docs` that link to master), and many of the things that are linked to don't exist in the handbook right now (for example, all the components in `/packages/block-editor/src/components`).

I can roll back the ones that link to master in this PR if you'd like.

**Review by mkaz — APPROVED** [review]
I suppose a link to Github is better than broken outright. I'll approve and we can fix downstream.

I thought we had the deep linking into packages fixed but I can't find the corresponding ticket. @nosolosw was linking into packages resolved or still open?

**Comment by nosolosw** [comment]
> I thought we had the deep linking into packages

I don't remember that we fixed this. However, I've also been a bit out of the loop in all regarding docs so I may have missed it.

Actually, now that this PR is merged but I don't see the changes in the handbook. Is that because we now pin the handbook to a branch? If that's the case, I wonder if we should cherry-pick commits the handbook branch from now on.

**Comment by mkaz** [comment]
@nosolosw Yes, the handbook is pinned to `wp/5.4` branch. Cherry-picking is probably a good idea, though the branch is locked and requires extra permissions to commit to.

**Pull request merged**
