### PR TITLE
Tests: Specify PHP version in composer

### PR DESCRIPTION
**Pull request by walbo**
## Description
Specify that the composer image should use php 7.4

## How has this been tested?
Unit tests should pass.

## Types of changes
Bugfix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by Mamaduka — APPROVED** [review]
Thanks, @walbo.

**Review by noahtallen — APPROVED** [review]
LGTM! Verified that `npm run prelint-php` (which handles composer install) currently fails on trunk locally, and this branch makes it work.

**Comment by Mamaduka** [comment]
Hi, @walbo

Can you rebase, and we can merge this?

Thanks

**Comment by noahtallen** [comment]
The test failure in this branch appears to be happening on `trunk` as well.

**Pull request merged**
