### PR TITLE
[RNMobile] Refine spacing of Back button on ios

### LINKED ISSUE #2528: [iOS] Refine spacing of "< Back" button
**Note: This issue is iOS-only.** 

While inspecting some bottom sheet refinements, I noticed that the spacing of the "< Back" button on iOS could be refined slightly to align with the system-default. Here is a visual:

<a href="https://user-images.githubusercontent.com/1200432/89212685-86619780-d589-11ea-9d31-e9167fd24731.png"></a>

In other words, we should:

* Remove ~7px of spacing on the left
* Add ~3px of spacing between the icon and text label

It's also worth noting that we're not using the system `<` (chevron) icon, so if we have that available, perhaps we can swap that in here? I wouldn't consider that a blocker because the icon is almost identical other than the rounded corners, so I think this icon is fine as long as we're matching the spacing.

// cc @lukewalczak is this something you would be able to take care of?

### PR DESCRIPTION
**Pull request by lukewalczak**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2528

## Description

Refine spacing of back button on ios

## Screenshots 

before | after
--- | ---
Screenshot 2020-08-04 at 11 32 15 | Screenshot 2020-08-04 at 11 32 22

## Types of changes

Adjust back button paddings 

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style. 
- [X] My code follows the accessibility standards. 
- [X] My code has proper inline documentation. 
- [X] I've included developer documentation if appropriate. 
- [X] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by lukewalczak** [comment]
@iamthomasbishop I refined spacings, however, if you can provide better chevron svg icon which we can use, please let me know!

**Review by dratwas — APPROVED** [review]
LGTM from the code perspective 👍

**Comment by iamthomasbishop** [comment]
@lukewalczak I added a [new iOS back icon](https://zeroheight.com/226850145/p/345d49-icons/b/78279c) (`icon-ios-back-chevron`) and also the [back button unit](https://zeroheight.com/226850145/p/18064e-cell/t/8128cc) to the design docs. A couple of things to note:

* The new icon is 12x21
* With that change, there should be 5px of spacing between icon and label

Altogether, it should look like this: 

<a href="https://user-images.githubusercontent.com/1200432/89468100-61f9ec80-d73c-11ea-9e21-6ccd495a9826.png"></a>

Thank you!

**Comment by lukewalczak** [comment]
**UPDATES**

I've added a new icon called `chevronBackIOS` for navigation header in the bottom sheets

light | dark
--- | ---
Screenshot 2020-08-06 at 11 03 35 | Screenshot 2020-08-06 at 11 03 14

**Comment by iamthomasbishop** [comment]
@lukewalczak _So_ close to exact, I only have 1 more tiny request -- can we remove 3px of margin on the left side of the button? Example:

<a href="https://user-images.githubusercontent.com/1200432/89573567-6aabfa80-d7f0-11ea-87fa-2a88b762a3aa.png"></a>

Thank you for your patience! 😆

**Comment by lukewalczak** [comment]
**UPDATES**

Reduce the spacing - confirmed on slack with Thomas, and it's correct!

Screenshot 2020-08-06 at 22 11 33

**Comment by iamthomasbishop** [comment]
@lukewalczak I think we have a regression on the spacing for the back button, as shown below. Would you mind taking a look at this?

<a href="https://user-images.githubusercontent.com/1200432/98016832-12bb6a80-1dc4-11eb-8328-425612c22244.jpeg"></a>

**Comment by lukewalczak** [comment]
@iamthomasbishop thanks for reporting that, I will check the root of regression and fix it!

**Pull request merged**
