### PR TITLE
Improvements to NPM package caching across workflows

### PR DESCRIPTION
**Pull request by desrosj**
## Description
There are a few changes in this PR.
1. Adding NPM package caching to workflows that run `npm install`/`npm ci` to attempt to shorten the runtime when possible.
1. Adjust NPM cache keys to be consistent across all workflows to increase the likelihood that a cache hit will occur.
1. Include the NodeJS version number in the cache key.

The compressed size workflow runs NPM related tasks through the `preactjs/compressed-size-action`, but no caching was configured. In my testing, I have found that when a cache hit occurs, it reduces the `npm ci`/`npm install` step by 2-3 minutes.

The `cache-name` environment variable has also been eliminated. The value of this variable was only being used in the cache key, so was not necessary.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by gziolo — APPROVED** [review]
Nice unification 👍🏻 

Any idea why some workflows didn't finish?

Screen Shot 2021-06-07 at 11 46 19

**Comment by desrosj** [comment]
@gziolo That I'm not sure of. Looking at the checks attached to the PR, they all seem to have completed successfully. So I think it may have been a hiccup on the Github side. I'll sync with `trunk` and push to rerun everything to confirm.

**Comment by desrosj** [comment]
Ah, actually, it's because the name of the job changed slightly. It seems that `(14)` is being added to the job names when a matrix is defined.

Since the required checks are specified by job name (which is not ideal, but how Github does it), these would need to be updated.

I only added the matrix for simplicity and to use a more consistent pattern across all workflows. Using the matrix allows the NodeJS version to be updated in one place and the cache keys would change automatically along with the matrix value. But having to change the required job name every time the version of Node used is changed is more annoying, and would prevent the PR from showing as "Ready for Merge" like as seen here.

I'll remove the matrix from these workflows.

**Comment by youknowriad** [comment]
We're seeing a lot of nom install related failures in PRs and commits in trunk. While I'm not sure this is the root of the issue, the timing of this related PR is suspicious. https://github.com/WordPress/gutenberg/runs/2772750162?check_suite_focus=true

**Comment by desrosj** [comment]
I followed up with @youknowriad in Slack, and after some investigation it seems it was more likely that this was related to some [service level problems related to an upstream CDN outage](https://www.githubstatus.com/incidents/96l7gcj0fcc8).

I've managed to get all of the workflows that were failing to rerun successfully, except where there were actual failures resulting from the code changes and it seems the upstream issues have been resolved.

**Pull request merged**
