### PR TITLE
3 column inserter

### PR DESCRIPTION
**Pull request by karmatosed**
This is a suggestion for #4080. It increases the 2 columns to 3 for the inserter.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice, I dig this. Though it's a bit cramped when it's just 300px wide:

screen shot 2017-12-20 at 08 43 44

The mobile safe area is 360px. If we make it 350px wide, it'll be more relaxed:

screen shot 2017-12-20 at 08 43 25

What do you think?

**Comment by karmatosed** [comment]
I have now added in the titles and also widened the block:

2017-12-20 at 10 44

**Comment by jasmussen** [comment]
Nice! 👍 👍

**Comment by youknowriad** [comment]
Hey I like it, what if the titles had a border-top as well

screen shot 2017-12-20 at 17 04 28

**Review by youknowriad — APPROVED** [review]

**Comment by jasmussen** [comment]
We tried the top border in the past, but then the topmost group would "stack" the borders. I think we tried some first-child magic to address that, but ran into woes. Not sure.

**Comment by karmatosed** [comment]
For now let's get in the 1 border and pondering a 2. If we can find a good option for it, I like the clarity of 2 :)

**Pull request merged**
