### PR TITLE
Mobile Release v1.35.0

### PR DESCRIPTION
**Pull request by cameronvoell**
## Description
Release 1.35.0 of the react-native-editor and Gutenberg-Mobile.

For more information about this release and testing instructions, please see the related Gutenberg-Mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2557

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by dratwas** [comment]
Hey @cameronvoell Could you please cherry pick this fix to the release branch? https://github.com/WordPress/gutenberg/pull/24656

Thanks! :)

**Comment by cameronvoell** [comment]
> Hey @cameronvoell Could you please cherry pick this fix to the release branch? #24656
> 
> Thanks! :)

Thanks for the fix @dratwas, cherry-picked here: e65ff5866642ae06ef5ec093eacd6a0423c6394f

**Review by ceyhun — APPROVED** [review]
:shipit:

**Comment by cameronvoell** [comment]
Merged using intermediate merge branch - https://github.com/WordPress/gutenberg/pull/24773

**Pull request closed without merging**
