### PR TITLE
Post Tags: Feature Parity for Customization

### PR DESCRIPTION
**Pull request by jeyip**
## Description

This PR addresses a task in #21087 and is meant to add feature parity to FSE blocks. This adds settings (and some necessary restructuring/styles to support) text alignment and the experimental flags for color, fontSize, and lineHeight.

## How has this been tested?

Tested on local docker wp-env environment.

1. Create a post and add tags in the settings sidebar
2. Navigate to the site editor
3. In the template dropdown, navigate to the recently created post
4. Add the post tags block
5. Verify that the correct tags are applied
6. Verify that we can modify the following for the post tags block: 
  - font color
  - font size
  - line height
  - text alignment
  - link color
  - background color

## Screenshots 
Post Tags

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by vindl** [comment]
@jeyip I'm guessing this one just needs to be rebased when https://github.com/WordPress/gutenberg/pull/24082 is merged and it will be ready for review?

**Review by Addison-Stavlo — COMMENTED** [review]
Since there is currently no style hook for `textAlign`, we will need to ensure the proper class is added in the index.php file for this block.

Similar to:
https://github.com/WordPress/gutenberg/blob/799e3550f5f4c57a5f9475dffde2bceb70b04aa3/packages/block-library/src/post-comments/index.php#L34-L37

**Comment by jeyip** [comment]
**Note:**

Continuing the discussion that @Addison-Stavlo brought up here https://github.com/WordPress/gutenberg/pull/24082#discussion_r462469838, it seems like we'll need some design input about what the behavior of `post tags` when some tags cannot be found.

Some ideas:
1. Notify the user that some tags couldn't load and render nothing
2. Notify the user that some tags couldn't load and render the tags that we can find

**Review by vindl — APPROVED** [review]
LGTM :shipit:

**Comment by StefanXhunga** [comment]
Thank you

**Pull request merged**
