### PR TITLE
Buttons block: Fix default alignment icon in toolbar to reflect the actual default alignment of buttons

### LINKED ISSUE #26909: Buttons block: Wrong alignment icon by default
### Problem
When creating a Buttons block, they default to Left alignment. This is good, however, this is not what is represented in the block's toolbar by default. The block's toolbar shows the Center alignment icon.

**Example of problem**

alignment

### Solution
Show the Left alignment icon in the toolbar by default.

Screen Shot 2020-11-11 at 3 53 41 PM

**To reproduce**
1. Add a Buttons block with some buttons.
2. Observe that the buttons are aligned to the Left.
3. Notice the alignment icon in the toolbar shows a Center alignment.
4. Click that icon and select the Center alignment and watch the buttons move to the center.
5. The default position of the buttons does not match the default icon in the toolbar.

**Expected behavior**
I expect the default icon for alignment to represent the default alignment of the buttons. So it should be the Left alignment icon.

**Editor version (please complete the following information):**
- WordPress version: 5.3.3
- If the Gutenberg plugin is installed, which version is it? 9.3

**Desktop (please complete the following information):**
 - OSX Catalina
 - Chrome

### PR DESCRIPTION
**Pull request by mapk**
Fixes #26909. 
Updates the alignment icon in the toolbar to default to "Left" since that is how the buttons are defaulted. This also now aligns with the Navigation block which also defaults to showing the "Left" alignment icon.

## How has this been tested?
Locally.

## Screenshots

**BEFORE**

Screen Shot 2020-11-11 at 4 02 58 PM

**AFTER**

Screen Shot 2020-11-11 at 4 03 06 PM

## Types of changes
Non-breaking changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by kellychoffman** [comment]
👍 looks good to me.

**Review by MichaelArestad — APPROVED** [review]
Looks good to me.

**Comment by mapk** [comment]
Just tried rebasing...

**Comment by MichaelArestad** [comment]
Looks like it worked.

**Pull request merged**
