### PR TITLE
Refactor FocalPointPicker unit test to tsx

### PR DESCRIPTION
**Pull request by alpha951**
## What?

- Renamed the unit tests files for FocalPointPicker component to `.tsx` files.
- Added jest types dev dependency.
## Why?

- To make unit tests typechecked.
## How?

- Renamed the unit test files to `.tsx`

### CODE REVIEW

**Comment by alpha951** [comment]
Fixes : #60529

**Comment by alpha951** [comment]
Please review the changes @WordPress/gutenberg-components

**Comment by alpha951** [comment]
props-bot

**Comment by mirka** [comment]
👋 Hi, thanks for the PR!

The baseline success check for this task is for `npm run build:package-types` to pass without errors. There are some changes that need to be made in the test file for type checks to pass.

Also, we don't need to add a `@types/jest` dependency because they are already available (see `npm ls @types/jest`).

**Comment by mirka** [comment]
This was fixed by another contributor in #61373. Thank you for the attempt 🙏

**Pull request closed without merging**
