### PR TITLE
Nav Browse mode remove "ghost" Nav block

### PR DESCRIPTION
**Pull request by getdave**
## What?

WIP to try and replace need for hidden/ghost Nav block within the Navigation seciton of Browse Mode.

### CODE REVIEW

**Comment by getdave** [comment]
The problem here is that we deprecated the `blocks` prop of List View so now it expects a `rootClientId` from which to list all the child blocks.

Unfortunately in our scenario we don't have a root because these blocks (i.e. those from the `wp_navigation` menu) are at the top level with no parent nav block required.

@scruffian as you deprecated `blocks` what do you think about this? Maybe the effort to remove the Nav block isn't worth it? Other than providing a way to handle entity saving flow, is there anything _else_ that the block provides that we need in the sidebar?

**Comment by scruffian** [comment]
The reason for deprecating `blocks` is that we couldn't see a use case for it, but if we have one I think we should undeprecate it!

**Comment by scruffian** [comment]
> is there anything else that the block provides that we need in the sidebar?

I think the block is also being used to load the navigation menus.

**Comment by getdave** [comment]
> I think the block is also being used to load the navigation menus.

Nope. We're doing that already. @talldan had some ideas in https://github.com/WordPress/gutenberg/pull/49475#issuecomment-1558869184

**Pull request closed without merging**
