### PR TITLE
Accessibility: Fix the accessibility of the menu items in the ellipsis menu

### LINKED ISSUE #4123: Toolbar ellipsis menu: improve menu labels contrast ratio and semantics
In the toolbar ellipsis menu, each menu has a visible label:

screen shot 2017-12-21 at 14 02 07

1
The color contrast ratio of these labels is too low: they use a light gray `#a2aab2` against a white background and the contrast ratio is as low as 2.35:1. See https://jdlsn.com/color/?type=hex&color=a2aab2&color2=ffffff
In the current color palette, the lightest gray that can be used on a white background is `$dark-gray-300: #6c7781;`

2
These labels are just text within a `<div>` element. It would be great to use some more semantic markup, not sure if they should be headings though. Additionally, since the menus use `role="menu"`, it would be great to use these visible labels as target for `aria-labelledby`. This would require to use unique IDs on the labels to be used as reference in the `aria-labelledby` attributes on the menus.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #4123

This PR adds an `aria-labelledby` attribute to these menus and changes the color of the label to match the A11y guidelines.

### CODE REVIEW

**Review by afercia — COMMENTED** [review]
@youknowriad thanks! Seems to me the second menu is now an empty div? Not sure why.

screen shot 2017-12-21 at 16 34 30

**Comment by youknowriad** [comment]
@afercia I think it has always been like that but it should be fixed now.

**Comment by afercia** [comment]
@youknowriad yep, deleted the branch, checked out again and rebuilt: seems fine now. Maybe I've messed up something. Thanks! 🎉

**Comment by youknowriad** [comment]
@afercia Actually, you were right. We had the bug (on master as well) and I pushed a fix after your comment

**Pull request merged**
