### PR TITLE
Fix site editor sidebar scrollbars

### LINKED ISSUE #48796: Site Editor sidebar: unable to scroll, Save button hidden
When there are a long list of items in the sidebar the save button gets pushed off the viewport entirely, and it's not possible to scroll the contents to view it:

https://user-images.githubusercontent.com/846565/223163111-5e1e47f1-ba66-4de3-a388-ae1bf163ec4e.mp4

cc @youknowriad

### PR DESCRIPTION
**Pull request by youknowriad**
closes #48796 

## What?

This PR fixes the scrolling in the sidebar of the site editor if it grows in height.

## Testing Instructions

- Add many templates to your site editor
- try scrolling the sidebar.

### CODE REVIEW

**Comment by youknowriad** [comment]
@jasmussen the visibility hidden trick doesn't seem to work anymore and I'm unsure why 🤔

**Review by ntsekouras — APPROVED** [review]
This works well in my tests, thank you!

**Comment by jasmussen** [comment]
It works if I apply the custom scrollbar to .components-navigator-screen, and make sure it and .edit-site-sidebar__content are 100% high tall. Let me try a separate PR.

**Comment by jasmussen** [comment]
Created #48822 as an alternative.

**Review by jameskoster — APPROVED** [review]
This fixes the original issue, and pins the save panel to the bottom of the sidebar which is what I'd expect:


https://user-images.githubusercontent.com/846565/223384577-cadad3b3-cdd2-48e4-b090-c6598242c764.mp4

**Comment by jasmussen** [comment]
But it breaks the scrollbar style. Let me take a look at #48822 real quick.

**Comment by jasmussen** [comment]
Fix here: https://github.com/WordPress/gutenberg/pull/48822#issuecomment-1457876039

**Comment by ntsekouras** [comment]
Closing as the alternative landed: https://github.com/WordPress/gutenberg/pull/48822. Thank Riad!

**Pull request closed without merging**
