### PR TITLE
Testing: Remove axe verification executed after every test case

### PR DESCRIPTION
**Pull request by youknowriad**
Nothing serious here, I just want to see the impact on the jobs.

### CODE REVIEW

**Comment by youknowriad** [comment]
It's interesting to note that the e2e tests are approximatively 2 to 4 minutes quicker

**Comment by ellatrix** [comment]
I don't mind this :)

**Comment by gziolo** [comment]
My initial intent was to eventually fix all the reported issues but they only accumulate over time as axe team adds rules for missing violations. The number of exceptions has grown over time as contributors learned that it is the fastest way to turn CI green. Some of those issues come from Axe implementation, some are valid reports that are ignored. I just wanted to share my thoughts. It might be fine to just create a test suite that checks the most popular features in the editor instead but limit the number of exceptions present.

**Comment by youknowriad** [comment]
Going to close this now. I believe the tests are more stable now.

**Review by gziolo — APPROVED** [review]
Let's revise the approach taken and pick a few accessibility focused e2e tests that will call `toPassAxeTests` explicitly.

**Pull request merged**
