### PR TITLE
WIP: revert lower specificity for alignments

### PR DESCRIPTION
**Pull request by MaggieCabrera**
## Description

An alternative solution to https://github.com/WordPress/gutenberg/pull/39014. In this case, I've reverted the changes on the specificity of the layout descendants selector and to keep the align left and right working as intended I've opted for overriding what we don't want to apply instead of using `:not`, which was causing specificity battles on a number of edge cases.

## Testing Instructions

Same as https://github.com/WordPress/gutenberg/pull/39014

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
Looks like this one isn't enough, it's failing for me on Blockbase because of the load order of the CSS.

**Comment by MaggieCabrera** [comment]
Closing this in favor of https://github.com/WordPress/gutenberg/pull/39014

**Comment by youknowriad** [comment]
Conceptually, this looks like a better approach to me than the alternative. In other words, if a block need to define a default for this, I'd prefer if they write `.wp-my-block { max-width: something }` and have the layout styles override that (because these are user/theme overrides) instead of the opposite. I guess it may not be easy to get right.

Also, the approach in this PR is exactly the same thing we had for a long time and not sure why it started failing just recently (the move to data-align changed things but this is reverting things to how they were before, so there's something else going on here that we need to find)

**Comment by MaggieCabrera** [comment]
> Conceptually, this looks like a better approach to me than the alternative. In other words, if a block need to define a default for this, I'd prefer if they write `.wp-my-block { max-width: something }` and have the layout styles override that (because these are user/theme overrides) instead of the opposite. I guess it may not be easy to get right.
> 
> Also, the approach in this PR is exactly the same thing we had for a long time and not sure why it started failing just recently (the move to data-align changed things but this is reverting things to how they were before, so there's something else going on here that we need to find)

This doesn't work for the initial issue because of the load order of the CSS. There's two problems at hand: the lower specificity of the container descendants selector and the change of the load order of the CSS, combined with the specific edge case where the extra tag on the query block causes the container selector to be on the wrapper, not the actual block that needs the rule

**Comment by jasmussen** [comment]
We're zeroing in on the cause in https://github.com/WordPress/gutenberg/pull/39014#issuecomment-1049660479.

**Comment by youknowriad** [comment]
> This doesn't work for the initial issue because of the load order of the CSS

When did the loading order change, the styles here has been like that for months and the theme issues are recent right.

**Comment by MaggieCabrera** [comment]
> When did the loading order change, the styles here has been like that for months and the theme issues are recent right.

It changed here https://github.com/WordPress/wordpress-develop/commit/43a8631882b552dba95bb8b59ab06c1dc49160dd but it wasn't a problem until we changed specificity in https://github.com/WordPress/gutenberg/pull/38947

**Comment by youknowriad** [comment]
cc @jorgefilipecosta @oandregal 

Can we agree on the ideal loading order first, try to implement it and try to fix the specificity battles after (as otherwise I feel we're just creating issues by solving other issues).

For me the load order should be:

 - block styles(.wp-block-template)
 - theme styles (.wp-block-template potentially) 
 - user styles (.wp-container > *)

**Comment by youknowriad** [comment]
To be clear, I'm not against the alternative PR but it only solves the problem for a specific block while it seems that something that can impact any block (including third-party ones). Could be a temporary fix.

**Comment by MaggieCabrera** [comment]
> To be clear, I'm not against the alternative PR but it only solves the problem for a specific block while it seems that something that can impact any block (including third-party ones). Could be a temporary fix.

yeah, I'm not so sure myself but I wanted to get the ball rolling and start a conversation

**Pull request closed without merging**
