### PR TITLE
fix/54877: Allow insertion of Buttons in the Navigation Block

### PR DESCRIPTION
**Pull request by Sidsector9**
## What?

In this PR, the `directInsert` prop is set to `false` to enable insertion of other supported blocks.

## Why?

It is counter-intuitive to insert a custom link, and then transform it into a Button, instead of adding a Button just how one would using the default inserter. This fix reduces confusion and improves user experience.

## Testing Instructions

In `trunk`

1. Add a Navigation Block
2. Add custom link to the Nav block.
3. Click the inserter within the Nav Block and see you don't get the option to add the Buttons block.
4. Switch to the fix branch and repeat 1, 2 and 3
5. Observe you get the default inserter to insert the Buttons Block.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/17757960/83ccdaa8-ce53-4142-bccd-eff6417db23f

### CODE REVIEW

**Comment by alexstine** [comment]
Why would you need to add a button to the navigation block in the first place? Just wondering. I forget, does it output an actual `<button>` or `<a>`?

**Comment by hanneslsm** [comment]
> Why would you need to add a button to the navigation block in the first place? Just wondering. I forget, does it output an actual <button> or <a>?

Just visuals, I guess. Like "Sign up now".
The output is `<a>`
```
<div class="wp-block-button">
<a class="wp-block-button__link wp-element-button">Sign up now</a>
</div>
```

**Review by getdave — CHANGES_REQUESTED** [review]
Thank you for the PR. At first glance the motivation seems solid.

However, I know we need to be pretty careful with amending the values in this PR so leaving a blocking review until I have chance to review in greater depth.

**Comment by t-hamano** [comment]
I just wanted to add that #55144 has also been submitted, which takes a slightly different approach to this PR.

**Review by getdave — COMMENTED** [review]
It is my opinion that _if_ we want to add this feature then https://github.com/WordPress/gutenberg/pull/55144 is the way to go. 

Thank you for the PR but I think we should close it out 🙏

**Comment by Sidsector9** [comment]
Closing as discussed.

**Pull request closed without merging**
