### PR TITLE
minimal node and npm upgrade

### PR DESCRIPTION
**Pull request by youknowriad**
Ok this is the third PR to attempt to upgrade node and npm. Sorry :) 

Previous attempts #52363 and #48950

The difference here is that this only upgrades to:

 - node 16
 - npm 8

This matches the Wordpress-develop PR https://github.com/WordPress/wordpress-develop/pull/4028 
And this is due to some current limitations in the build servers of wp.org. See this post for more details https://make.wordpress.org/systems/2023/02/09/upgrade-nodejs-npm-on-the-build-server/

The systems team is aware that the EOL of node 16 is approaching but to avoid blocking things too much, we can still upgrade to 16 which will unblock the yjs dependency needed for phase 3 work for now and 18 once the build servers are ready.

### CODE REVIEW

**Comment by youknowriad** [comment]
Looks like there's some typescript build issues in this PR, not sure I understand these failures.

**Comment by noahtallen** [comment]
I rebased on trunk after merging the typescript update (#52621), and put all of the package-lock.json changes into one commit. (Basically just discarded the current package-lock changes, and ran `npm install` followed by `npm dedupe`.) 

I then ran both `npm run build:package-types` and `npm run lint` locally, and both passed.

One odd thing -- this PR is around +90k lines/-40k lines, but the old PR (#52363) was +55k/-55k lines. So it doesn't seem to be de-duplicating as much this time! Potentially a difference between npm 8 and 9, or some other changes since then?

**Review by jorgefilipecosta — APPROVED** [review]
The change looks good and tested well for me 👍

**Review by ellatrix — APPROVED** [review]
YES!

**Review by ntwb — COMMENTED** [review]
Looks good, though I see this n the ailing CI run:
- https://github.com/WordPress/gutenberg/actions/runs/5802757839/job/15729686496?pr=53426#step:4:234

```
/usr/bin/git reset --hard
HEAD is now at 1ac6aef Merge 3d16f40be7a232c0457569c5e20b8ec087dd42b6 into c94eca530c73cb06d4a73f78559ee27c0bea9ecb
[base] Checkout target branch
  /usr/bin/git fetch -n origin trunk
  From https://github.com/WordPress/gutenberg
   * branch                  trunk      -> FETCH_HEAD
   * [new branch]            trunk      -> origin/trunk
  successfully fetched base.ref
  checking out and building base commit
  /usr/bin/git reset --hard trunk
  fatal: ambiguous argument 'trunk': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  /usr/bin/git reset --hard c94eca530c73cb06d4a73f78559ee27c0bea9ecb
  HEAD is now at c94eca530c Fix Storybook build which broke after Typescript 5 update (#53445)
[base] Cleanup via npm run distclean
  /opt/hostedtoolcache/node/16.20.1/x64/bin/npm run distclean
  
  > gutenberg@16.4.0-rc.1 distclean
  > rimraf node_modules packages/*/node_modules
```

**Comment by youknowriad** [comment]
@ntwb The compressed size check failure is ok because that job compares with trunk and in trunk, node version need to be 14. So it's going to fix itself after merge.

**Comment by ntwb** [comment]
[celebrate]     Stephen Edgar reacted to your message:
________________________________

**Review by ntwb — APPROVED** [review]
:shipit:

**Comment by swissspidy** [comment]
Finally 🎉  Thank you!

**Comment by desrosj** [comment]
The changes required for Core have also been committed. Thanks again, everyone!

**Pull request merged**
