### PR TITLE
Block toolbar: always close options menu after toggling sidebar

### PR DESCRIPTION
**Pull request by creativecoder**
## Description

Two updates to "Show/hide more settings" action in the block toolbar options

- Always close the options menu after opening or closing the sidebar
- Speak message when closing the sidebar

These 2 small bugs were found when implementing the [same functionality for the site editor](https://github.com/WordPress/gutenberg/pull/31305). It appears they were introduced [when this code was refactored](https://github.com/WordPress/gutenberg/commit/52000d7cba67a6226d47aade0fc3130c695fabdd#diff-0974da85661fd17841abb4b00f12139b9bc63d7f563c34b6ffb4ad3671f6c284R43).

## How has this been tested?

- Select a block and use the "Show/hide more settings" choice in the "Options" menu, or use the keyboard shortcut <kbd>Cmd/Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>,</kbd>
- The Options menu should close and a message should be spoken when opening _and_ closing the sidebar

## Screenshots 

show-hide-block-settings-sidebar

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by david-szabo97** [comment]
> Always close the options menu after opening or closing the sidebar

Does this mean it should close the ~sidebar~ options menu when using the shortcut? Tried the shortcut but that doesn't close the ~sidebar~ options menu for me. (OSX: Chrome, Firefox, Safari)

Otherwise, everything else works! 🙇

**Comment by jeyip** [comment]
> Does this mean it should close the sidebar when using the shortcut? Tried the shortcut but that doesn't close the sidebar for me. (OSX: Chrome, Firefox, Safari)

Interesting! It works well for me @david-szabo97. I saw a different oddity though.

> The Options menu should close and a message should be spoken when opening and closing the sidebar

Judging by the source code changed in this PR, the oddity described below is expected. But, to clarify, I only saw a message from the screen reader when opening and closing the sidebar by clicking on the "Show/hide more settings" choice. Using the keyboard shortcuts didn't appear to trigger any messaging.

| Keyboard Shortcut | Show/hide more button |
| ---| --- |
|  |  |

**Review by jeyip — APPROVED** [review]

**Comment by david-szabo97** [comment]
> Does this mean it should close the sidebar when using the shortcut? Tried the shortcut but that doesn't close the sidebar for me. (OSX: Chrome, Firefox, Safari)

>> Interesting! It works well for me @david-szabo97. I saw a different oddity though.

I just realized I totally messed up my comment. Instead of "sidebar", I wanted to say "options menu" 😬 When I use the shortcut, the options menu is never closed.

**Comment by david-szabo97** [comment]
`onClick` isn't called when the shortcut is used. Which makes sense, since the `shortcut` we pass to `MenuItem` is just for visual.

**Comment by creativecoder** [comment]
> I only saw a message from the screen reader when opening and closing the sidebar by clicking on the "Show/hide more settings" choice. Using the keyboard shortcuts didn't appear to trigger any messaging.

That's expected the way this menu currently works, but having visual changes spoken when using keyboard shortcuts seems worth exploring, separately.

**Review by david-szabo97 — APPROVED** [review]

**Comment by youknowriad** [comment]
Hey folks, I think this PR is an a11y regression, the focus when opening the inspector needs to go there, instead, it stays on the toolbar here. I believe that's the main reason for the existence of that button in the first place.

**Comment by youknowriad** [comment]
Actually, scratch that, it seems that "regression" existed before this PR and potentially the revisited tabbing behavior (skipping all blocks except the selected one) make this focus switch unnecessary.

**Pull request merged**
