### PR TITLE
Transform multiple selected blocks to Columns block

### LINKED ISSUE #16504: Add "Transform to Columns" option when multiple blocks are selected.
This could live in the standard block transforms area. Like the "Group" transform, this would create a new block (a Columns block in this case) that would contain the selected blocks. Each block would become its own column. 

columns

### PR DESCRIPTION
**Pull request by ntsekouras**
## Description
Resolves: https://github.com/WordPress/gutenberg/issues/16504

This PR adds the ability to transform multiple selected blocks in a `Columns` block. For now the `Columns` transformation is available from the menu only if selected blocks are `between two and six`. The number `six` is selected as for now this is the current `max` columns allowed by a `Columns` block.

You can create a `Columns` block from any other block, including InnerBlocks themselves. 

## How has this been tested?
Locally for now.
You can test this PR by doing the following:
1. Go to a post/page
2. Create some blocks, even a block with InnerBlocks like a `Group` block.
3. Multi select blocks (between 2-6)
4. Click on transform menu and select `Columns`

## Types of changes
A new function (`createBlocksFromInnerBlocksTemplate`) for creating blocks from `InnerBlocks template` have been exposed to the public API. A version of this function has been used(duplicated) in more than one places to implement the relative functionality.

## Todos left

- [x] Unit tests for `createBlocksFromInnerBlocksTemplate`.
- [x] e2e tests for the transformation to `Columns`.
- [x] Use the new function to appropriate places.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by etoledom** [comment]
Tested inserting columns block on mobile and looks good! 👍 
Thanks for thinking about mobile 😁♥️

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! This is amazing @ntsekouras ! The transformation to column experience feels nice :D.

I manually tested the following flows:

* Selected 1 block. Confirmed, column option is missing.
* Selected 2-6 blocks. Confirmed, column option is available.
* Selected 2-6 blocks, some with inner Columns. Confirmed, column option is available. Nested columns works.

Fantastic job abstracting the repeated `createBlocksFromInnerBlocksTemplate` function. This tidies it up a lot!

---

The only suggestion I have, but is not necessary, would be to add an E2E test for attempting to "columnize" just a single block.

Right now, there are test cases for 2, and more than 6.

Again, totally not a blocker! This is amazing. I love how thorough you are with your PR code changes.

---

Sidenote: TIL that adding a `+` in front of a number `string` transforms it into a `number` (type) 😱 .
Same goes with `-`, but making it negative.

**Comment by ntsekouras** [comment]
Hey @ItsJonQ - thanks so much for your review! 🥇 

>The only suggestion I have, but is not necessary, would be to add an E2E test for attempting to "columnize" just a single block.

Actually the transformation would work with any number of blocks. We limit that only because it doesn't make sense to create `Columns` block with too many... eh columns :).  I deliberately skipped the `one` function because creating `Columns` blocks with a single column is coming soon. There is PR for that.. And after that we should allow `one` as well.

**Comment by mtias** [comment]
This is a cool new interaction, let's make sure to include it in changelogs for 5.6.

**Comment by gziolo** [comment]
`createBlocksFromInnerBlocksTemplate` - this is something that is worth mentioning in the summary of new APIs introduced. Awesome work on this PR 💯

**Comment by tellthemachines** [comment]
Thanks, added to the list in #26108 !

**Pull request merged**
