### PR TITLE
Core Emebds: merge similar strings

### PR DESCRIPTION
**Pull request by yoavf**
## Description
There is plenty of repetition in the core embed's descriptions, which we can merge.

## How has this been tested?
- Manual testing of the block list
- Manual testing of POT file generated via `npm run build`

## Types of changes
String updates

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by ocean90** [comment]
Just like we don't do "Add %" for post type labels we shouldn't do it for these strings either. For example in German we need to know whether the placeholder has one or more words as in "Funny or Die".

**Comment by yoavf** [comment]
> Just like we don't do "Add %" for post type labels we shouldn't do it for these strings either. For example in German we need to know whether the placeholder has one or more words as in "Funny or Die".

Thanks @ocean90 - that escaped me - in this case, the placeholder is only for the specific name of sites/services and that seemed ok to me in the languages I speak.

Do you think there's still some avenue to reduce the number of strings here?

**Comment by aduth** [comment]
What's the current status of this pull request? Can it be closed? @ocean90 , are you able to provide some feedback to the question at https://github.com/WordPress/gutenberg/pull/12713#issuecomment-445541949 ? 

>Just like we don't do "Add %" for post type labels we shouldn't do it for these strings either.

There was a similar conversation today at https://github.com/WordPress/gutenberg/pull/14124#issuecomment-467894245 , though in that instance we don't have the benefit we have here of knowing a hard-coded set of possible values. 

As asked there, I would be curious if you have resources (aside from those mentioned) to share about this particular guideline, or how we might consider to document this in guidelines.

**Comment by aduth** [comment]
Closing as stale without response. Please propose a new pull request if you plan to continue the work here, though it seems the proposed changes may not be viable.

**Pull request closed without merging**
