### PR TITLE
Fix 'Publish sidebar Cancel button not usable through speech recognit…

### PR DESCRIPTION
**Pull request by prashanttholia**
…ion software' issue

Related Issue: #25194

## Description
Fixes the issue of publisher sidebar cancel button not being usable through speech recognition software.

## How has this been tested?
Tested using Speech Recognition Anywhere extension on Chrome browser on Windows machine.

## Types of changes
Bug fix: Fixes the issue of publisher sidebar cancel button not being usable through speech recognition software.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by prashanttholia** [comment]
Ref Issue: https://github.com/WordPress/gutenberg/issues/25194

**Comment by prashanttholia** [comment]
@afercia @allilevine, I have raised this PR related to the issue #25194.

As mentioned in the PR post above, I have only been able to test it using 'Speech Recognition Anywhere' extension on Chrome browser on Windows machine. I request you to let me know about a suitable free software that could be used to test the feature.

Also, I'm not sure whether this fix also required any changes in the React Native files. I also request you to let me know about the same.

Thanks.

**Comment by allilevine** [comment]
👍 I tested with Voice Control and Safari (following the steps in #25194) and saying "Click cancel" closed the Publish panel.

**Review by ZebulanStanphill — APPROVED** [review]
Looks good to merge!

**Comment by afercia** [comment]
@prashanttholia thanks for working on this!

To answer your question, I'm not sure there are good speech recognition software for Windows that are free. Traditionally, the most used one is Dragon but it's commercial software and pretty expensive. 

On Windows 10, there's the built-in "Windows Speech Recognition" tool which can be used for testing, to some extent. Also to consider that different tools often give different results. For example, when testing with Voice Control on macOS and then with Windows Speech Recognition on Windows, I often get different behaviors.

The PR looks good to me, the change is simple, and everything is green. Merging!

**Comment by prashanttholia** [comment]
Thanks @afercia!

I did try testing "Windows Speech Recognition", but it somehow did not work on my machine.

I am glad that the PR is being merged. Thanks to you and @allilevine for providing the opportunity to contribute!

**Pull request merged**
