### PR TITLE
Colors Selector: Add contrast checker

### PR DESCRIPTION
**Pull request by retrofox**
## Description
This PR is an attempt to add the contrast checker to the color selector dropdown. The background-color comes from the `<ColorSelectorIcon />` which may be defined through the `editor-styles-wrapper` CSS class.

## How has this been tested?
Create/Edit a menu nav changing the text color. The contrast checker should appear when the contrast is not appropriate.

## Screenshots 

colors-selector-contrast-checker

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

### CODE REVIEW

**Comment by getdave** [comment]
@retrofox Is this still valid given that colors are removed from Nav?

**Comment by retrofox** [comment]
> @retrofox Is this still valid given that colors are removed from Nav?

I bet you mean to _`background-color` are removed._ 😉 

Yes, I think it's still a valid approach. Pay attention to the animation that I put in the description. The idea is to be able to compare the text color selected by the user with the color defined by the `editor-styles-wrapper` CSS class.
Generally, this color is white but in twenty-twenty it is `#f5efe0`

**Comment by draganescu** [comment]
Hi @retrofox I can't test this beacause `npm run dev` errs, might require a rebase for testing 🙏

**Comment by retrofox** [comment]
> Hi @retrofox I can't test this beacause `npm run dev` errs, might require a rebase for testing 🙏

Hi, there!
We can close this one since the contrast checker has been implemented in the [background-color PR](https://github.com/WordPress/gutenberg/pull/19108).
Sorry and thanks, Andrei.

**Pull request closed without merging**
