### PR TITLE
[eslint-plugin] Added eslint-plugin-import as a dependency

### LINKED ISSUE #28391: [eslint-plugin] Error: ESLint couldn't find the plugin "eslint-plugin-import"
## Description
Hi, after updating `@wordpress/eslint-plugin` to version 8.0.0, I am getting the error `ESLint couldn't find the plugin "eslint-plugin-import".` I don't have this package installed and do not use it. This seems to me like `@wordpress/eslint-plugin` depends on `eslint-plugin-import` but does not have it listed in its dependencies (as confirmed by looking at its `package.json`).

## Step-by-step reproduction instructions
Please do see https://github.com/skaut/skaut-google-drive-gallery/pull/814/checks?check_run_id=1740746218

## Expected behaviour
Linting works...

## Actual behaviour
Eslint crashes with the aforementioned error.

## Device information
- Device: Desktop
- Operating system: Debian testing

Please let me know if additional info is needed.

### PR DESCRIPTION
**Pull request by marekdedic**
## Description
Closes #28391

## How has this been tested?
I have no idea on how to test this as this repo contains multiple NPM packages and I don't know of a way to `npm install` a subdirectory...

## Types of changes
Added an NPM dependency

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
Thank you for opening this PR. I'm sure you will have  to run `npm install` to update the lock file for npm packages to make CI pass.

**Comment by marekdedic** [comment]
Hi @gziolo, thatks for the tip, however I already ran `npm install` in the `packages/eslint-plugin` directory and no update to the lock file was made :shrug:

**Comment by marekdedic** [comment]
And based upon a cursory look, it seems to me that the failed CI has nothing to do with the actual change...

**Comment by gziolo** [comment]
I should clarify that you need to run `npm i` in the root folder. Gutenberg uses monorepo setup that consists of multiple individual npm packages. You install dependencies in one place.

**Comment by gziolo** [comment]
I opened an alternative PR #28545 that contains all the changes I mentioned. Thank you for flagging this issue and opening this PR. I will publish a new version of the package with the fix included later today.

**Comment by marekdedic** [comment]
Hi,
thanks for the tips again, I have never worked with a monorepo before...

And thanks for the actual fix as well :)

**Pull request closed without merging**
