### PR TITLE
Add description for Reusable Blocks

### PR DESCRIPTION
**Pull request by 0aveRyan**
Addresses #8345

## Description
Add description guidance for Reusable Blocks.

## Screenshots
reusable-block-description

## Types of changes
* In-app documentation

### CODE REVIEW

**Comment by 0aveRyan** [comment]
@ZebulanStanphill Definitely open to wordsmithing this! However `instance` is a development concept and I think confusing to an everyday user.

I'd played with `content and formatting changes sync`, `changes will reflect` and `Use again and again`.

I'd like to see `Convert to Regular Block` formatted _somehow_ (or perhaps make a functional link?)... but try to avoid formatting in translatable strings.

**Separate issue**, but the Reusable Block Name textbox and getting Convert to Regular Block into the sidebar would help un-bury these functions.

**Comment by chrisvanpatten** [comment]
> This is a reusable block, which can be shared between multiple pages and posts. When edited, the block will automatically update wherever you have it inserted.

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten Nice! I do wish that <kbd><samp>Convert to Regular Block</samp></kbd> was mentioned, but that is mainly because that option is not quite as discoverable as I would prefer.

>**Separate issue**, but the Reusable Block Name textbox and getting Convert to Regular Block into the sidebar would help un-bury these functions.

Related: #8403

**Comment by chrisvanpatten** [comment]
> I do wish that Convert to Regular Block was mentioned, but that is mainly because that option is not as discoverable as I would prefer.

I considered that, but ultimately I don't think it's really appropriate to treat the descriptions as help docs — it gets unwieldy very quickly. Perhaps that could be explained in a dot tip?

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten A dot tip would help, but I think using Reusable Blocks as templates should become less of a second-class ability. Currently, I do not really use Reusable Blocks for their global instance ability. I only use them for inserting templates like placeholder text that I can then quickly modify. As proposed in #8403, you should be able to choose whether to insert a Reusable Block as a global instance or a template when you insert it, similar to what Oxygen does with its Reusable Parts.

**Comment by chrisvanpatten** [comment]
> As proposed in #8403, you should be able to choose whether to insert a Reusable Block as a global instance or a template when you insert it, similar to what Oxygen does with its Reusable Parts.

I think better to solve that problem over in #8403, rather than in this PR then :)

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten Agreed. I'm happy with your proposed description.

**Comment by 0aveRyan** [comment]
@chrisvanpatten @ZebulanStanphill took a second pass

* The description is right below the "Reusable Block" title, so truncated beginning.
* Remove `you`

screen shot 2018-08-20 at 12 34 32 pm

**Comment by ZebulanStanphill** [comment]
I think it could be even simpler:

`When updated, changes apply everywhere this Block is inserted.`

Also, should "block" be capitalized here or not?

**Comment by 0aveRyan** [comment]
screen shot 2018-08-20 at 1 09 07 pm

**Comment by michelleweber** [comment]
I like the evolution here. I might want to add a few words to be super clear that you can use the block anywhere, not just on the post/page where you create it, and to be a little more active. Maybe something like

> Create content, and save it to add to any post or page. Update the block, and the changes apply everywhere it appears.

**Comment by chrisvanpatten** [comment]
I love that latest revision @michelleweber!

**Comment by michelleweber** [comment]
Woot :)

**Comment by ZebulanStanphill** [comment]
@michelleweber I like your iteration, but I think it should be modified to avoid referencing posts/pages specifically since Reusable Blocks can (of course) be used in custom post types, as well as the future use of blocks in sidebars, footers, headers, and etc. What do you think of this:

"Create content, and save it to reuse across your website. Update the block, and the changes apply everywhere it appears."

**Comment by 0aveRyan** [comment]
```
Create content, and save it to reuse across your site. Update the block, and the changes apply everywhere it's used.
```

**Comment by ZebulanStanphill** [comment]
@0aveRyan You should use `’` instead of `'`. The former is a fancy apostrophe that does not conflict with the typewriter apostrophe and single quotation mark character. That allows you to avoid having to escape the apostrophe, and also being slightly nicer semantically. (It is also recommended to use the direction-specific quotation marks for quotations for the same reason.) The fancy quotation marks are already used in the dot tips:

>Welcome to the wonderful world of blocks! Click the “+” (“Add block”) button to add a new block. There are blocks available for all kind of content: you can insert text, headings, images, lists, and lots more!

>You’ll find more settings for your page and blocks in the sidebar. Click ‘Settings’ to open it.

If you look closely (and depending on how different they look in your font), you will notice that the fancy quotation marks are used there instead of the neutral ones.

(Actually, I just noticed that the dot tips are inconsistently using double quotation marks vs single quotation marks. I have opened an issue for that: #9205.)

See also:
https://en.wikipedia.org/wiki/Apostrophe
https://en.wikipedia.org/wiki/Quotation_mark

**Comment by michelleweber** [comment]
A question: do we think most users make a distinction between "post" and "custom post type"? They're all posts. I've seen this issue crop up in a few places, and I just want to pause to consider it's usefulness for basic instructions and descriptions. I tend to think "post" covers it in cases like this, but I'd like to know if/why I'm wrong so I can avoid similar confusion in the future.

**Comment by chrisvanpatten** [comment]
> A question: do we think most users make a distinction between "post" and "custom post type"? They're all posts. I've seen this issue crop up in a few places, and I just want to pause to consider it's usefulness for basic instructions and descriptions. I tend to think "post" covers it in cases like this, but I'd like to know if/why I'm wrong so I can avoid similar confusion in the future.

I have experienced users who don't understand that "post" also includes "pages" but the confusion doesn't typically extend beyond that. (The term "custom post type" itself is definitely confusing, but I don't think it's used anywhere in Gutenberg anyway.)

**Comment by 0aveRyan** [comment]
@michelleweber @chrisvanpatten I agree the nuance of the distinction isn't deeply important to some users, but avoiding reference to Posts and Pages I think gives these blocks more resiliency for use in WooCommerce, other e-commerce contexts, media publishing and yet-to-be-invented formats 10 years from now.

In news and media publishing, organizations often customize WP with highly specific nomenclature for posts (stories, blogs, longform, slideshows, investigations, projects) there are functions for it in themes like [Largo Project](https://largo.inn.org/).

Also, if these Blocks get used for sidebars, headers or footers down-the-road as is the rough roadmap for the next version that seems like a likely case for every user where they'll be used in something not called a Post or Page.

**Review by noisysocks — APPROVED** [review]
Thanks for tackling this @0aveRyan! Looks good to me 👍 

I would like for us to one day show the icon of the underlying block type and perhaps mention it in the description, but this is a fantastic start that we can iterate on.

**Comment by 0aveRyan** [comment]
@noisysocks agreed. one other idea I had was to allow users to write their own reusable block descriptions (stored in the_excerpt) to encourage more succinct Block Names. Is there a roadmap for reusable blocks?

**Comment by noisysocks** [comment]
> Is there a roadmap for reusable blocks? Should tickets be opened for these?

There's no roadmap per se, though do feel free to open an issue and tag it with the **Reusable Blocks** label.

**Pull request merged**
