### PR TITLE
Display device icon on "preview" and "view" buttons

### PR DESCRIPTION
**Pull request by mtias**
Small clarity improvement in conjunction with #50217.

image

### CODE REVIEW

**Comment by jasmussen** [comment]
I like it:

Screenshot 2023-05-01 at 15 38 34

Hover state shows the metrics:

Screenshot 2023-05-01 at 15 38 48

Resizing works well too:

resizing

I thought it was going to feel weird to see the desktop icon if you scaled down the viewport to mobile, but it's actually feeling fine:

Screenshot 2023-05-01 at 15 39 40

We really need a better disabled state for these buttons, it's weird they suddenly get a background:
Screenshot 2023-05-01 at 15 37 34

That's separate, but it's worth doing. CC: @WordPress/gutenberg-design — seems like a disabled button could be the same style as the ✓ Saved button — white bg, gray text.

One thing worth tinkering with, is the space between the icon and the label, which feels extra large in the mobile device version due to the metrics of the icon:

Screenshot 2023-05-01 at 15 42 47

But even in the desktop state, the spacing looks a bit large:

Screenshot 2023-05-01 at 15 43 16

The spacing apperas to be 8px:
Screenshot 2023-05-01 at 15 43 43

Just making that 4px feels good to me:

Screenshot 2023-05-01 at 15 43 48

**Comment by mtias** [comment]
I don't think we should locally modify the spacing for this button alone, and if we do it for the mobile type only we'd get some layout shift.

**Comment by jasmussen** [comment]
> I don't think we should locally modify the spacing for this button alone, and if we do it for the mobile type only we'd get some layout shift.

I should've been clearer: I was suggesting we modify the default spacing here across all buttons with icons. It feels off across [every variation](https://wordpress.github.io/gutenberg/?path=/story/components-button--default&args=icon:link;variant:primary):

Screenshot 2023-05-01 at 15 49 16

Screenshot 2023-05-01 at 15 49 21

Screenshot 2023-05-01 at 15 49 26

4px may be too small? 6px could be better? I'm also happy to explore this separate if you prefer to keep things focused.

**Comment by mtias** [comment]
Ah, ok :) Yes, let's do that separately

**Review by jasmussen — APPROVED** [review]
Let's try this.

I'll follow up with smaller gap between icons.

**Comment by jameskoster** [comment]
I like the icons, but it feels a bit of a shame to increase the horizontal space occupied by top bar children. Do we need the 'Preview' text, couldn't that be a tooltip?

**Comment by mtias** [comment]
@jameskoster I think that's a next step to consider, but it's a slightly larger change we should combine with the work on document title and a way to display the view link. If we have a final design target there we can move faster.

**Pull request merged**
