### PR TITLE
Add `home` to list of new templates

### LINKED ISSUE #46325: Add `Home` template as an option in the 'Add New' menu
## What problem does this address?

Currently, the `home.html` template is not an option in the 'Add New' menu in the Templates editor section.

image

## What is your proposed solution?

We should add `home.html` as an option to create from the Editor, as this is still a commonly used template in many themes, and is often chosen over the use of `front-page.html`, which is included in the 'Add New' menu.

I'm not sure of the original reason the template wasn't included - I couldn't find any previous discussions.

### PR DESCRIPTION
**Pull request by mikachan**
## What?

Adds 'Home' (home.html) to the list of templates that can be added in the Site editor.

image

## Why?

Closes https://github.com/WordPress/gutenberg/issues/46325.

The Home template is often used in themes, and without it being included in the default list of templates, it needs to be created manually outside of the Editor.

However, I'm not sure if this highlights the confusion around the Front Page and Home templates too much. This is an existing problem, but perhaps listing the templates so close to each other is even more confusing. Still, I think it would be good to allow this template to be added without needing to leave the Editor. It would be great to know what everyone thinks.

## How?

Adds `home` to `DEFAULT_TEMPLATE_SLUGS`, and uses the `postList` icon for the Home icon.

## Testing Instructions

1. Go to the Site editor
2. Click the + to add a new template
3. 'Home' should display in the templates list, under Front Page

### CODE REVIEW

**Review by jffng — APPROVED** [review]
This works as advertised.

I assume it was avoided from the original list because of confusion around the name of this template: https://github.com/WordPress/gutenberg/issues/44524

Regardless of the name change, I don't think it should prevent us from adding it here. 

cc @jameskoster for a gut check and also the icon used.

**Comment by jameskoster** [comment]
I would dearly love to avoid using "Home" as a single-word title to reduce confusion with Front Page. Should we try "Blog home"?

There's also scenarios that can make the application of this template really confusing. Specifically: homepage is set to display latest posts, and Front Page exists. In this case I don't think `home.html` will ever be used? Should there be conditions that define whether this template is surfaced in the add-template menu?

**Comment by mikachan** [comment]
> Should we try "Blog home"?

Yes, I think "Blog home" makes sense. Should we just overwrite the template name here, just for the editor? Or do you think this should be changed in Core first? I can try out overwriting the name in this PR, to see how it feels.

Alternative names could be "Blog Posts" or "Blog Posts Index", as that's how it's described in the [template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/), but "Blog Home" sounds easier to understand.

> Specifically: homepage is set to display latest posts, and Front Page exists. In this case I don't think home.html will ever be used? 

Yeah, that's right, front-page.html always overwrites home.html.

> Should there be conditions that define whether this template is surfaced in the add-template menu?

I like this idea, could it work something like this:

Blank theme:
- add-template menu shows both Blog Home and Front Page

Existing theme with a Blog Home (home.html):
- add-template menu does not show the Front Page template, or
- add-template shows the Front Page template with a note in the description to say, "will overwrite Blog Home template"

Existing theme with a Front Page (front-page.html):
- add-template menu does not show the Blog Home template, or
- add-template menu shows the Blog Home template with a note in the description to say, "will be overwritten by Front Page template"

After reading that through, perhaps we just need to add the overwrite explanations to the template description? If we conditionally show these templates, it makes it more difficult for a user to add them. e.g. it would need to be obvious that Front Page needs to be deleted in order to add a Blog Home template.

Or perhaps instead of the templates being conditionally shown, they're visible but disabled, with a note in the description saying why they're disabled.

**Comment by carolinan** [comment]
I feel that being able to add the template without code is more important.
I would be OK with "Blog Home" if you think that the description is not enough.

In the reading settings, the text for changing the content of the home page is

Your homepage displays:
- Your latest posts
- A static page

So maybe an option could be "Home: Latest posts"

**Comment by mikachan** [comment]
Here are a couple of mockups with some of the options mentioned above:

| Blog Home | Home: Latest posts |
| ---------- | ------------ |
| image | image |

**Comment by jameskoster** [comment]
I quite like "Home: Latest posts".

**Comment by carolinan** [comment]
@paaljoachim You mentioned that working with the front page was confusing, do you have input on a name for the "Home" template?

**Comment by paaljoachim** [comment]
EDIT: This is the short version.
The meaning of the word Home can be confusing. The purpose of the template is to show post previews on the front page or the blog page. Two very different locations. Calling the template Post (Preview) template would be more clear I feel. Or perhaps Latest posts template. A variation of what Carolina suggested: Latest Posts. I would remove the word Home from the Template name and instead have the word Home in the template description.

What I find difficult is the Index template and how that is related to Latest posts template.

---- 

This is the longer reponse.

NB. I appologize for the length of my reply. I just had to....

First of all let's look at the description of the Home Template. 
I will go into the mindset of someone who is not a WordPress geek/nerd like everyone here, me included..:)

"Displays posts on the homepage, or on the Posts page if a static homepage is set."

Who is our audience? Developers? Common users who begins to use Full Site Editing?

Home Template - In it's name it sounds like it is the front page template.

Breaking a part the description (brainstorming the phrases being used.):
"Displays posts on the home page..." --> I thought the Home template would be the full front page template, but here it sounds like it only affects the posts on the home page. But I do not have posts on the front page..... I am confused....

"...or on the Posts page if a static homepage is set." What does that mean? I am again confused.
Ok so the Posts page is my blog page where I have my posts. Even though I might call my blog page news or something else it is still my blog page. I was taught that in WordPress school last week.

A static homepage what is that? What is a dynamic page? 

Rethinking.... So the Home template can be used on the Blog page, but the theme Twenty Twenty Three has a Blog template (Alternative).....Hmmmm.  
I find it strange that I can actually use the Home template on my Blog page.

Looking at the description again.
"Displays posts on the homepage, or on the Posts page if a static homepage is set."

So the Home template will be used on the home page actually front page if I decide to show posts on the front page. If I do not decide to show posts on the front page but on the Blog page called News then the Home template will be seen on the blog page.

So the Home template is actually a Posts preview template that will be assigned to either the front page or the blog page depending on where the blog posts are seen.

Now I got to do a video recording of the above.... As if feels like a play with words.
Reminds me of the sketch... Who's on first. No Who's on second. With Abbot and Costello. 
https://youtu.be/nZ5vspsNS1g

Here is my video:
https://youtu.be/qiQ9jPhfEX0

**Comment by carolinan** [comment]
The problem with calling it Latest Posts is that when someone goes looking for the file, it is still called home.html and that will also be confusing.

**Comment by mikachan** [comment]
> The problem with calling it Latest Posts is that when someone goes looking for the file, it is still called home.html and that will also be confusing.

Yes, as we're unable to change the name of the template, I think we need to keep "home" in the title somewhere so it relates to home.html. I think I still prefer "Home: Latest posts".

Thanks for your insights, @paaljoachim! I agree that how these templates work is confusing, especially when the template names are surfaced in the site editor.

> What I find difficult is the Index template and how that is related to Latest posts template.

The index template is the [default fallback](https://developer.wordpress.org/themes/basics/template-hierarchy/#home-page-display) for all templates, so if a home.html or front-page.html doesn't exist, and the reading settings are set to show the latest posts, then the index.html template is used.

**Comment by paaljoachim** [comment]
Should template names have a specific consistency of something like this?
Home: Latest Posts
Index: Default Posts Fallback
Single: Post
404: Missing page
Etc

I believe we will need to open a new issue where we in general go through Template names. Thinking consistency, language and making these names as logical as possible of what they accomplish. So most users can look at the template names and understand what they do and which template they need to edit.

**Comment by carolinan** [comment]
What about calling it Latests Posts but mentioning home.html in the description?

**Comment by paaljoachim** [comment]
So this part is pretty confusing and blurs the clarity of what the Home and Front Page templates are.

Home template
Screenshot 2023-01-30 at 12 47 24

Front Page Template.
Screenshot 2023-01-30 at 12 50 42

Screenshot 2023-01-30 at 12 50 55

The Front Page template is straight forward meant to display the homepage.
The Home template creates confusion as it does not need to be associated with the home page, but can be associated with the blog page. So really this is the Blog page, Latest posts page template and that should be the title. Adding Home to the template creates confusion in relation to the Front page. Again I need to create a naming issue for the templates.

**Comment by carolinan** [comment]
The template hierarchy limits what can be done. There is no way around that it actually is called home.

**Comment by paaljoachim** [comment]
It is so very important to use template names/titles we see be as logical as possible. How they were used earlier (coding) and how these will be used today (visual UX/UI) is very different.
I made a new issue for template names. https://github.com/WordPress/gutenberg/issues/47551

**Comment by jameskoster** [comment]
I wonder if there's an opportunity for design to explore alternative implementations for this particular template. 

Presented as a template it's confusing, largely because all user interactions center around it behaving like a page. IE it can be your home _page_, or your posts _page_. Consequently, it might be worth trying a design that surfaces it in a more intuitive location, e.g. the Pages list, where it can have a more sensible name based on its application.

It's worth noting that this goes for other templates like `category-recipes`, `tag-pizza`, as well. So if we can come up with a compelling pattern we can apply it in those instances too.

In that sense this feels related to https://github.com/WordPress/gutenberg/issues/44461.

**Comment by phil-sola** [comment]
I would love to see this merged and added to core. I spent way to long this morning trying to understand how to set up the blog posts page in FSE. The posts page defined in the reading settings defaults to index which I would never use for this template. You can't add Home confusingly in the editor so the only way to add it is manually create the html file. I couldn't find this documented anywhere either so complete guesswork. 

It is crucial this can be added via the site editor going forward IMO. I am also very up for being more explicit in the template name as discussed above instead of simply using 'Home' which is always confusing.

**Review by jameskoster — APPROVED** [review]
Perhaps we can merge this now the description has been updated, and update the name separately. The name may even be less of an issue if we can tackle https://github.com/WordPress/gutenberg/issues/48651.

The icon needs some attention, but it's probably ok to tackle that separately too.

**Comment by carolinan** [comment]
I think this needs a rebase for the final two playwright tests to pass?

**Comment by mikachan** [comment]
Thanks for merging this, @carolinan!

**Comment by phil-sola** [comment]
Thanks @carolinan, a great addition! 😀

**Pull request merged**
