### PR TITLE
Fix Navigation Link url escaping

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
## Description

Fix for issue #19632 .

This PR updates the navigation-link component to pass the url through the `escape` function on saving a new link.  Previously, a link such as http://example.com/?s=<> would lead to http://example.com/?s= when used on the front-end.  Now, links saved with the url passed through the escape function will lead to the expected href on the front end.

## How has this been tested?

Tested on local docker environment using links saved on the Navigation block.

### In the editor
**Saved without escape function**
Screen Shot 2020-01-14 at 5 18 50 PM

**Saved with escape function**
Screen Shot 2020-01-14 at 5 18 59 PM

### On the Front-End
**Saved without escape function**
Screen Shot 2020-01-14 at 5 21 48 PM

**Saved with escape function**
Screen Shot 2020-01-14 at 5 22 02 PM

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by WunderBart** [comment]
Can we use native [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) instead of lodash's `escape()`?

A good related issue about it: https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent

**Comment by Addison-Stavlo** [comment]
> Can we use native encodeURI instead of lodash's escape()?

Definitely!  Thanks for linking that issue that is great to know.  I have updated it to now use `encodeURI` instead of `escape`.  Now, on the editor, the link looks a bit better too but still leads to the correct place on the front end.

Screen Shot 2020-01-15 at 1 15 35 PM

**Review by WunderBart — APPROVED** [review]
Looks good! :shipit:

**Comment by noahtallen** [comment]
I'll go ahead and merge this for you since everything is looking good!

**Pull request merged**
