### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by ntwb**
## Description

Update the projects contributors list

Source: https://github.com/WordPress/gutenberg/graphs/contributors

## How Has This Been Tested?

n/a

## Screenshots (jpeg or gifs if applicable):

n/a

## Types of changes

The list is now sorted alphabetically as it makes it easier to merge the list of new contributors
 
## Checklist:
- [ ] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
https://github.com/WordPress/gutenberg/graphs/contributors shows only 100 users. We might create a script to automate this task based on git history.

**Comment by gziolo** [comment]
Quick google search and I found this: http://www.commandlinefu.com/commands/view/4519/list-all-authors-of-a-particular-git-project.

**Comment by ntwb** [comment]
> https://github.com/WordPress/gutenberg/graphs/contributors shows only 100 users. We might create a script to automate this task based on git history.

Thanks. Did. Not. Know. That. 👍 

Further, there's a high chance I accidently deleted some contributors because of this, I'll close this PR and create a new PR with an automated solution, and if needed include a commit that sorts the list alphabetically first to aid in ensuring this is avoided

> Quick google search and I found this: http://www.commandlinefu.com/commands/view/4519/list-all-authors-of-a-particular-git-project.

Unfortunately that command shows the registered Git username rather than a GitHub username:
```
git log ebfa9c324541092694be7bd45ce1112b6d41f059
commit ebfa9c324541092694be7bd45ce1112b6d41f059
Author: Grzegorz (Greg) Ziółkowski <grzegorz@gziolo.pl>
Date:   Tue Nov 21 08:36:04 2017 +0100

    Testing: Fix Eslint issue with trailing spaces
```

It also includes duplicates:
```
git log --format='%aN' | sort -u
...
Grzegorz (Greg) Ziółkowski
Grzegorz Ziolkowski
Grzegorz Ziółkowski
```

**Comment by youknowriad** [comment]
Also, I think this list is not only for "Code" contributions.

**Comment by ntwb** [comment]
> Also, I think this list is not only for "Code" contributions.

Indeed, the non-commit contributions are curated by the team and manually added and any automated solution should ensure these contributor names are never removed from said list 😄

**Pull request closed without merging**
