### PR TITLE
Fix references that should be for Speaker Deck

### LINKED ISSUE #7850: Embeds: "Speaker" should refer to "Speaker Deck"
## Issue Overview

Currently the UI for the "Speaker" block is incorrect. The labels, references and tests should refer to "Speaker Deck" and also https://speakerdeck.com.

Additionally, Speaker Deck is a SAAS service for embedding presentation slides so the current audio icon should be altered to match a similar service e.g. Slideshare.

## Steps to Reproduce
1. Insert a new "Speaker" block and notice that the label and text references are incorrect.

## Expected Behaviour
I expect that the labels and references to should say "Speaker Deck" not "Speaker" and the icon shouldn't be an audio icon.

## Current Behaviour
The labels and references to this service say "Speaker"

## Screenshots / Video
speaker
speaker block

## Additional Info
Gutenberg @ https://github.com/WordPress/gutenberg/commit/c314b15a204ee5e4015f8986919313ba20d0eb53

### PR DESCRIPTION
**Pull request by BronsonQuick**
Fixes #7850.

## Description

Currently the core block for "Speaker Deck" uses references to "Speaker".

## How has this been tested?
I've tested this using `npm run dev` in Chrome.

## Screenshots
insert speakerdeck
speaker-deck-url

speakerdeck-embed

## Types of changes
I've altered the following:
1. References to `Speaker` have been altered to `Speaker Deck`.
2. References to `https://speaker.com/` to `https://speakerdeck.com/`.
3. CSS references to `wp-block-embed-speaker` have been altered to `wp-block-embed-speakerdeck`.
4. References to `wp:core-embed/speaker` have been altered to `wp:core-embed/speakerdeck`.
5. Fixtures filenames have been renamed from `core-embed__speaker*`
 to `core-embed__speakerdeck*`.
6. I changed the icon from `embed-audio` to `embed-post` as the service is similar to Slideshare which has the `embed-post` icon.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by ntwb** [comment]
Can you resolve the conflicts here please @BronsonQuick

**Comment by BronsonQuick** [comment]
@ntwb I think those conflicts should be resolved now

**Review by ntwb — APPROVED** [review]
Thanks @BronsonQuick 👍 👍

**Comment by Soean** [comment]
When you rename a block, it breaks posts with the old block. So should we add a [transformation](https://wordpress.org/gutenberg/handbook/block-api/#transforms-optional)?

**Comment by pento** [comment]
The old block needs to be [deprecated](https://wordpress.org/gutenberg/handbook/block-api/deprecated-blocks/), this PR shouldn't have been merged without it.

@BronsonQuick: Could you please create a new PR with a deprecated version of the old block?

**Comment by ntwb** [comment]
I've just reverted this PR in #8277, will follow up with another PR with the deprecations correctly included.

**Pull request merged**
