### PR TITLE
Link Format: Label with selected text, not full text

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
See https://github.com/WordPress/gutenberg/pull/11063#issuecomment-440291625. Link are being labeled with the full field's content, not just the selected text.

* Only labels with selected text.
* Removes trimming since the text cannot be empty.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by iseulde** [comment]
@ryanwelcher @afercia I don't understand why there's only a label being added with the selected text if the link opens in a new tab. Shouldn't every link contain a label then? If not, maybe links that open in a new tab shouldn't include the selected text as the label. This seems inconsistent to me.

**Comment by afercia** [comment]
`aria-label` _overrides_ the content of a link, i.e. only the `aria-label` value is announced, while the link content is ignored. In the current implementation, when the link opens normally, there's no need to override the link content. Not saying the current solution is ideal 🙂 Honestly, I'd rather use a `screen-reader-text` appended to the link content.

**Comment by iseulde** [comment]
@afercia Cool thanks for the quick reply, that makes sense then.

**Comment by ryanwelcher** [comment]
@afercia @iseulde I agree that the current implementation is not ideal. I was not able to figure out how to inject a span tag with the `screen-reader-text` class using the current API.

**Review by oandregal — APPROVED** [review]
Works as expected.

**Comment by iseulde** [comment]
Thanks @nosolosw!

**Pull request merged**
