### PR TITLE
Updates 'Large header and a paragraph' pattern

### PR DESCRIPTION
**Pull request by enriquesanchez**
Updates contents, style and title of the 'Large header and a paragraph' pattern, also adds a description.

**Before:**
87109553-9c01cc80-c22a-11ea-855c-743edc66005a

**After:**

Screen Shot 2020-07-22 at 18 42 56

### CODE REVIEW

**Comment by kjellr** [comment]
A couple small suggestions: 

We should increase the line height just a little — currently descenders in the first line will bump up against ascenders in the second. Increasing this to `1.2` should retain a similar feel while avoiding this. 

Screen Shot 2020-07-23 at 8 33 09 AM

For the gradient, I'd recommend starting with a lighter version of the same hue, rather than using the purpler variant. That would brighten this up a bit. Here's an example that goes from `#f94848` to `#b31616`.

Screen Shot 2020-07-23 at 8 31 18 AM

That extra padding between the heading and the secondary text is truly unfortunate, but I think that's mostly because of the theme? Even so, would it make sense to remove the second line of text here if we can't enforce the spacing we want? It would be just the title and the button then:

Screen Shot 2020-07-23 at 8 38 13 AM

**Comment by enriquesanchez** [comment]
Thanks @kjellr!

I'll work on these updates you suggest. Unfortunatelt, I have no control over the line-height so I can't do much there :(

**Comment by enriquesanchez** [comment]
Oh, and related to the padding between the main and secondary lines of text, that's only an issue on the Gutenberg Starter theme and Twenty Nineteen. On all the other core default themes (Twenty Twenty, Seventeen, etc.) the padding is not so prominent.

I'd prefer if we kept it since in my opinion makes the pattern more interesting. What do you think?

**Comment by kjellr** [comment]
> I'll work on these updates you suggest. Unfortunately, I have no control over the line-height so I can't do much there :(

We can't adjust the line height on these anymore? 😞 That's weird, because I don't think the line height there seems like the normal line height for h2s. 🤔 

 > On all the other core default themes (Twenty Twenty, Seventeen, etc.) the padding is not so prominent.

I tried it out on Twenty Twenty, and though it looks better [in the editor](https://cloudup.com/iLpg-1DFKIe), it looks awkward [in the front end](https://cloudup.com/i4Z8O54OAGK). It thought it looked weird [in Twenty Seventeen too](https://cloudup.com/iqQ2yVyJCAg). Maybe that's going to be fixed later on in [this core themes ticket](https://core.trac.wordpress.org/ticket/50594), but I think it's probably best to avoid showing awkward spacing bugs in these patterns.

**Comment by enriquesanchez** [comment]
@kjellr 

> I don't think the line height there seems like the normal line height for h2s.

Right, this is a h2 with a custom font-size of 68px.

>I think it's probably best to avoid showing awkward spacing bugs in these patterns.

Fair enough. I'll remove it.

**Comment by kjellr** [comment]
I do see line height styles [in the code here though](https://github.com/WordPress/gutenberg/blob/88f02f717701b7f701165649de32870a73704898/lib/patterns/large-header-paragraph.php#L10): 

`style=\"line-height:1;font-size:68px;color:#fffffa\"`

**Comment by enriquesanchez** [comment]
@kjellr Thanks for all the feedback, here's the updated version:

Screen Shot 2020-07-23 at 13 07 33

**Comment by kjellr** [comment]
Cool, that looks good to me. Once we figure out what's going on with those line height styles (I think we can still define them, for themes that do support the line height control), then this should be all set.

**Comment by ZebulanStanphill** [comment]
I feel like using custom line heights in our patterns is a band-aid solution; shouldn't we just fix the spacing in our themes?

**Review by mapk — APPROVED** [review]
Yep, just tested this and it looks good.

**Comment by kjellr** [comment]
> I feel like using custom line heights in our patterns is a band-aid solution; shouldn't we just fix the spacing in our themes?

The spacing issue noted above and the line height are different issues. The spacing issue is a theme issue, but the line height isn't necessarily — the appropriate line height for a `h2` at the default text size may not be appropriate once we make the text `64px`, like we do here. If we're specifying a font size, it makes sense to define a line height as well. 

We _are_ [defining line heights](https://github.com/WordPress/gutenberg/pull/24142#issuecomment-663154191) in here right now — [they're just too tight](https://github.com/WordPress/gutenberg/pull/24142#issuecomment-662982697). I think those should be stripped out or redefined (I recommend `1.2` or `1.3`) in a later PR.

**Comment by enriquesanchez** [comment]
>We are defining line heights in here right now — they're just too tight. 

@kjellr Ah, I totally missed those! They must've carried over from when I created the pattern and the line-height feature was still available.

Interestingly, they do work! I was under the impression that custom line-heights would be ignored by themes that don't support them.

I'll make a new PR and set them to your suggested values.

**Pull request merged**
