### PR TITLE
Support batch requests in data layer

### PR DESCRIPTION
**Pull request by adamziel**
🚧 **UNDER CONSTRUCTION** 🚧

Data layer support for https://github.com/WordPress/gutenberg/pull/25096

The idea is simple: apiFetch pools related requests, sends them all as one batch, and then resolves the promises using the response of the collective batch request.

To demonstrate the idea, I just added `batchAs: ``${ kind }-${ name }`` ` to actions.js. In reality, this should come from the caller to distinguish between related and unrelated requests:
* Saving the site in the site editor should batch all template-parts updates as it ideally would be an atomic operation.
* Saving one reusable block and then saving another should not be batched as failing to handle one shouldn't cause the other to fail.

Also, `template-parts` controller doesn't support batch requests at the moment so applying this PR will result in errors until it does. This PR is more of a launchpad for discussion than mergeable code.

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
How should we handle when the batch response returns a top-level error? Ie not one where each request has a separate error. This wouldn't be sourced from the batch controller itself, but could be generated by other code.

For me it seems like the actual batching shouldn't happen at the `api-fetch` layer, but in the data layer. That way we could also have a specific action to save entities in a batch and explicitly commit the batch.

Right now the state of that is just in a global variable, but I think it might be able to actually live in the store so we could inspect the state of the batching specifically.

I took a stab at that here: https://github.com/WordPress/gutenberg/compare/master...TimothyBJacobs:try/data-batch-requests It is working for me against `/wp/v2/posts` after enabling `allow_batch` in the base `WP_REST_Posts_Controller`. The global `dispatch` call needs looking at. My whole approach might also be wrong.

**Comment by ntsekouras** [comment]
Hey 👋 ! I took a look at https://github.com/WordPress/gutenberg/pull/25096 (@TimothyBJacobs ) and I wanted to know a bit more about the reasoning of this. If I understand correctly, you created an endpoint to validate the requests and if the input is okay, then you have to make another request to commit the changes (ex update something)?

If that's the case, shouldn't the validation be in the respective endpoint (ex update something)? Also can you point me to where such validation happens? Does it call `prepare_item_for_database` in `WP_REST_Menu_Items_Controller`?

I comment in this PR because I'd like to understand how is connected to Navigation and what are the other use cases for this, both data layer and endpoint). Thanks!

**Comment by TimothyBJacobs** [comment]
> Hey 👋 ! I took a look at #25096 (@TimothyBJacobs ) and I wanted to know a bit more about the reasoning of this. If I understand correctly, you created an endpoint to validate the requests and if the input is okay, then you have to make another request to commit the changes (ex update something)?

No, it is implemented on the server side as one request to the batch endpoint. If `require-all-validate` is passed, then each request is validated in the batch controller, and if each request passes validation, it performs the actual dispatching.

**Comment by adamziel** [comment]
> How should we handle when the batch response returns a top-level error? Ie not one where each request has a separate error. This wouldn't be sourced from the batch controller itself, but could be generated by other code.

@TimothyBJacobs I think it's fair to assume the entire operation failed and so the global error could be used as a failed response for each partial request.

> Right now the state of that is just in a global variable, but I think it might be able to actually live in the store so we could inspect the state of the batching specifically. For me it seems like the actual batching shouldn't happen at the api-fetch layer, but in the data layer.

This is an interesting idea. A clear advantage is that it would prevent mixing batches from multiple registries. A disadvantage is that we'd be batching requests as they are before running the middlewares. I wonder if there is some way to get the best of both worlds, but I like the overall concept of keeping it in the state.

(Side note, I noticed that in your branch the list of batches is a global variable same as in this PR)

> That way we could also have a specific action to save entities in a batch and explicitly commit the batch.

I don't quite agree here. While I agree that some things are easier to reason about when done explicitly, I am also a fan of sensible defaults. For example having to list `if ( batchId ) { addToBatch(); } else { apiFetch(); }` in every place where apiFetch is used seems pretty verbose to me, I fear it would repetitive really quickly. As for explicit committing - I agree it should be possible, I also think most use cases could be covered by some smart auto-commit strategy (maybe 50ms time window?).

> I took a stab at that here: master...TimothyBJacobs:try/data-batch-requests It is working for me against /wp/v2/posts after enabling allow_batch in the base WP_REST_Posts_Controller. The global dispatch call needs looking at. My whole approach might also be wrong.

Nice! Thank you for taking it for a spin! I have some ideas how to connect both approaches - I'll think about it some more and hopefully propose a third PR tomorrow.

**Comment by TimothyBJacobs** [comment]
> A disadvantage is that we'd be batching requests as they are before running all the middlewares

I think this doesn't effect us for the most part. Looking at https://github.com/WordPress/gutenberg/tree/master/packages/api-fetch/src/middlewares, the only one I think we need to account for is the `namespace` middleware. The rest are supposed to operate on the global request or apply to `GET` requests which batching doesn't support.

> (Side note, I noticed that in your branch the list of batches is a global variable same as in this PR)

Yeah they are right now, but since it lives in the `core-data` layer it should be possible to move those to store, right? Do actions triggered by a control get picked up by the reducer?

> For example having to list if ( batchId ) { addToBatch(); } else { apiFetch(); } every time we want to support batching seems pretty verbose to me, I fear it would repetitive really quickly.

That's true, but I think there are only two spots where this would happen in `core-data`. In `saveEntityRecord` and `deleteEntityRecord`, so we might not reach the level where it is annoying I think.

If we are still worried, we could add it as a parameter to an `apiFetch` control that would support trigger `ADD_TO_BATCH` if passed a `batchId`.

>  I also think most use cases could be covered by some smart auto-commit strategy (maybe 50ms time window?). In my opinion saveEditedEntityRecordsAsBatch would ideally be just saveEditedEntityRecords with one extra option (batch: true?)

I think I'm probably not entirely understanding what the `core-data` side of your PR would look like. With an auto-commit strategy, would callers be tracking their dirty records on their own and then calling `saveEditedEntityRecord()` for each record with a `batch` flag?

Or are you saying they would call `saveEditedEntityRecords()` or `saveEditedEntityRecordsAsBatch()` with the signature for specifying what entities to save? If so, the committing part is transparent to the API caller as the `saveEditedEntityRecords()` call triggers a `commitBatch`.

If not, then how does the API caller get informed about the status of an entire batch?

**Comment by adamziel** [comment]
@TimothyBJacobs I explored state-based processing in https://github.com/WordPress/gutenberg/pull/26164 (WIP). I thought that batch processing is a pretty generic concept so there could be a generic state machinery for handling that. Supporting batch API requests would then only be a matter of integrating that with either the entity store or API_FETCH control. What do you think about this direction? also cc @youknowriad

**Comment by TimothyBJacobs** [comment]
That looks like a great approach to me!

I'm still curious about this bit to get an idea of how this will integrate with `core-data`.

> I think I'm probably not entirely understanding what the core-data side of your PR would look like. With an auto-commit strategy, would callers be tracking their dirty records on their own and then calling saveEditedEntityRecord() for each record with a batch flag?

> Or are you saying they would call saveEditedEntityRecords() or saveEditedEntityRecordsAsBatch() with the signature for specifying what entities to save? If so, the committing part is transparent to the API caller as the saveEditedEntityRecords() call triggers a commitBatch.

**Comment by youknowriad** [comment]
I'm mainly interested in the impact this will have on callers, a `batchAs` property on the "query" object doesn't sound so great.

**Comment by TimothyBJacobs** [comment]
> I'm mainly interested in the impact this will have on callers, a `batchAs` property on the "query" object doesn't sound so great.

The REST API won't support GET batch requests in v1, so something to keep in mind, but I don't think we necessarily need to solve in the first go at this.

**Comment by adamziel** [comment]
> I'm mainly interested in the impact this will have on callers, a batchAs property on the "query" object doesn't sound so great.

Just to be strict, that's a `request` or `options` object. But yes, I think we can do better than that. We may not be able to work out the details of a proper core data integration before 9.2 so as @TimothyBJacobs said, this is not necessarily a problem for the first go. For now let's focus on making it work just in the widgets editor.

Also, I'm closing this PR in favor of https://github.com/WordPress/gutenberg/pull/26164 which is based on redux store.

**Pull request closed without merging**
