### PR TITLE
Docs: Fix typo in Tutorial

### PR DESCRIPTION
**Pull request by huzaifaalmesbah**
I fix the small mistake in [Updating edit.js](https://developer.wordpress.org/block-editor/getting-started/tutorial/#updating-edit-js-2)

### CODE REVIEW

**Review by fabiankaegy — CHANGES_REQUESTED** [review]
I don't think this is an enhancement. The text above specifically calls out that there are two steps and then the steps are listed below as two list items.

**Comment by huzaifaalmesbah** [comment]
Thanks for the review @fabiankaegy 
Can we then use an Unordered/Ordered List?

| Unordered | Ordered |
| ----------- | ----------- |
| Huzaifa-20240305144024| Huzaifa-20240305144252|

**Comment by fabiankaegy** [comment]
@huzaifaalmesbah that works for me 👍

**Review by fabiankaegy — APPROVED** [review]

**Comment by huzaifaalmesbah** [comment]
Thanks @fabiankaegy 
I just added the unordered list. Can you review it?

**Pull request merged**
