### PR TITLE
Fix Cover focal point picker.

### PR DESCRIPTION
**Pull request by jasmussen**
In #28114, the explicit `height` property was removed from the cover block.

That caused a bug where content inside the cover would overflow the edges, which was fixed in #28287, which kept the height removed, but added an `overflow` property instead.

While the overflow fixed the problem with overlapping content, the height was still necessary for the focal point picker to work. 

Currently:

Screenshot 2021-01-20 at 11 07 44

After this patch:

Screenshot 2021-01-20 at 11 09 35

I could also remove the overflow rule again, making it a full revert. But the overflow doesn't appear to be causing any issues on its own. Open to suggestions here.

While it's unfortunate we didn't catch the focal point picker issue in the last patch, I don't think fixing that is as urgent as the overflow issue. Still good to get into the next version.

### CODE REVIEW

**Comment by ockham** [comment]
Thanks @jasmussen!

Flagging for @jffng since this is effectively a revert of #28114.

Might be worth adding some e2e coverage for the Focal Point Picker (which has recently seen some other improvements in #28096) in a follow-up PR.

**Comment by mtias** [comment]
Let's get this in and figure out something more solid if needed. We need more coverage of all the possible combinations in the cover. I'm also seeing the matrix alignments being broken:

image

**Comment by jasmussen** [comment]
I removed the overflow as well. It cropped the resize handle.

**Review by mtias — APPROVED** [review]

**Comment by jasmussen** [comment]
The following fix is separate, but would be good to land also: https://github.com/WordPress/gutenberg/pull/28361

**Comment by ockham** [comment]
Cherry-picked to `release/9.8`.

**Pull request merged**
