### PR TITLE
Details Block: Rmove unnecessary comment attributes

### PR DESCRIPTION
**Pull request by t-hamano**
## What?
This PR changes the attributes definition of the summary property so that content is not stored in the comment delimiter.

code-editor

## Why?
My understanding is that the values of attributes should be extracted from the markup as much as possible to reduce the amount of content stored in the database.

## How?
~~Add a deprecation.~~ Add `selector` and `source` to `summary` attribute and updated the existing fixture.

## Testing Instructions
- In the trunk branch, insert a Details block and enter summary text and content.
- When you switch to the code editor, make sure it is saved as a comment, like `{"summary":"Details Summary"}`.
- Switch to this PR branch.
- ~~When the editor is reloaded, confirm that the browser console outputs a log indicating that a block deprecation has been performed.~~ Update the contents of the block.
- Confirm that the comment delimiter for the summary property has disappeared from the HTML markup.
- Then, update and save the contents of the block, reload the browser, and confirm that the block is not broken.

### CODE REVIEW

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for putting this PR together @t-hamano 👍 

For the deprecation to work properly, we'll need to also provide the block supports configuration for the `v0` deprecation. Otherwise, if there was a deprecated version of the block with block support style attributes set, we'd lose that by the time it was migrated.

In addition, there are some further changes to the block fixtures required.

1. The default fixture (i.e. for the latest version) should have the source `core__details.html` updated to remove the summary from the block comment delimiter.
2. There should be a new fixture added to cover this deprecated case e.g. `core__details__summary__deprecated.html`. Essentially, its source HTML file would be the same as the `core__details.html` stands now (with the summary value in the block comment delimiter).

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

I added the `supports` property to deprecated and also added a new fixture. Both the fixture I added (`core__details__deprecated-v0.html`) and the fixture that originally existed (`core__details.html`) have exactly the same result, but this is correct, right?

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for iterating on this one @t-hamano 👍 

The deprecation's supports now match the block's, the fixture tweaks look good, and the fixture tests are all passing.

We might need to rebase this one though before merging.

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw!

I found two things to worry about after merging the latest trunk.

- By #52256, `__experimentalDefaultControls` was added to `block.json`. it seems that the migration will run even if the deprecated supports are not updated, but Should `__experimentalDefaultControls` be added to support?
- Create a Details block in trunk and switch to this PR. I noticed that when I reload the editor, no logs appear in the browser console and no migration takes place. However, when I update the content, the migration takes place. Is this related to the fact that I did not update `save.js`, only `block.json`?

https://github.com/WordPress/gutenberg/assets/54422211/ef18efc4-4744-41ad-94d7-dac424a953ef

**Comment by aaronrobertshaw** [comment]
> By https://github.com/WordPress/gutenberg/pull/52256, __experimentalDefaultControls was added to block.json. it seems that the migration will run even if the deprecated supports are not updated, but Should __experimentalDefaultControls be added to support?

Changes to block supports would only need to trigger a migration if they impact the saved markup for the block. In this case, the support changes are only to control what UI controls are displayed by default. Essentially, `__experimentalDefaultControls` doesn't impact the markup at all and as such doesn't need a deprecation.

This PR is introducing the first deprecation for the Details block. It should reflect the current state of the attributes and supports at the time it lands. This would include the `__experimentalDefaultControls` change made recently. Even though it doesn't impact the markup to omit it, it will reduce confusion when someone comes to add further deprecations in the future. Deprecations are a bit of a nightmare at times as they are without adding to it 😅 

> I noticed that when I reload the editor, no logs appear in the browser console and no migration takes place. However, when I update the content, the migration takes place. Is this related to the fact that I did not update save.js, only block.json?

If I'm following correctly, the question is why doesn't the block migrate without editing it?

My guess would be that the block markup is still valid as it is only the comment delimiter that is changing. This means the block isn't invalidated. 

Otherwise, valid blocks can still trigger a deprecation to run if their `isEliigble` function returns true. You might then be able to use the deprecation's `migrate` function to clear the summary attribute. 

I quickly hacked up something locally but ran out of time to get it working properly. The snippet below does not appear to be updating the block delimiter despite clearing the summary attribute. It also then incorrectly shows the "Write summary" placeholder. 

Unfortunately, I'm out of time this week so might have to leave this one with you.

```diff
diff --git a/packages/block-library/src/details/deprecated.js b/packages/block-library/src/details/deprecated.js
index e64bf11ce16..35181fa1588 100644
--- a/packages/block-library/src/details/deprecated.js
+++ b/packages/block-library/src/details/deprecated.js
@@ -48,6 +48,12 @@ const v0 = {
 			},
 		},
 	},
+	migrate: ( attributes, innerBlocks ) => [
+		{ ...attributes, summary: undefined },
+		innerBlocks,
+	],
+	isEligible: ( attributes, innerBlocks, { blockNode } ) =>
+		!! blockNode.attrs?.summary,
 	save( { attributes } ) {
 		const { showContent } = attributes;
 		const summary = attributes.summary ? attributes.summary : 'Details';

```

Having the summary attribute within the block delimiter doesn't break things. Any new details block, or any existing one that gets updated, will have the attribute cleared from the block delimiter. Perhaps, we should avoid the deprecation altogether?

Some fresh eyes and opinions on this would be welcome cc/ @andrewserong

**Comment by andrewserong** [comment]
Thanks for the ping!

> Having the summary attribute within the block delimiter doesn't break things. Any new details block, or any existing one that gets updated, will have the attribute cleared from the block delimiter. Perhaps, we should avoid the deprecation altogether?

Yes, in this case because the block markup hasn't changed, my understanding is that we wouldn't need a deprecation here. I don't think there's a need for us to migrate old comment markup to the new format — as you mention, we can happily change what gets serialised when the content of the block is manually updated by the user, rather than forcing it via a deprecation.

I like the idea of this PR, though, thanks for working on it @t-hamano! It seems better overall to me to not store a duplicate of the data in the comment delimiter 👍

**Comment by t-hamano** [comment]
Thank you for the detailed explanation, @aaronrobertshaw, @andrewserong!

If I understand correctly, this PR only requires the addition of the attributes `selector` and `source` in `block.json`, correct? I have updated the PR title, description, and code, but if I have misunderstood anything please let me know 🙇

**Review by andrewserong — APPROVED** [review]
Thanks for the updates @t-hamano!

This is testing nicely:

✅ When opening an existing post where `summary` is stored in the comment delimiter, there are no errors or warnings 
✅ After making any edit, the markup is updated to remove the `summary` attribute in the comment
✅ Saving and reloading the editor doesn't result in any errors or warnings

| Initial page load | After making an edit |
| --- | --- |
| image | image |

LGTM! ✨

**Review by aaronrobertshaw — APPROVED** [review]
Appreciate your patience on this one @t-hamano 🙇 

I think we've settled on the right approach to this issue and it's testing well for me.

✅ Deprecated blocks are still valid
✅ Editing blocks updates the block comment delimiter
✅ New blocks omit summary from the comment delimiter as well

🚢

**Comment by t-hamano** [comment]
Thanks for the review, @aaronrobertshaw, @andrewserong!

**Pull request merged**
