### PR TITLE
[WIP] List View: Allow dropping a block by dragging outside the vertical area of the list view

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

🚧 🚧 🚧 WIP: This is still experimental for the moment 🚧 🚧 🚧 

Part of addressing issues including https://github.com/WordPress/gutenberg/issues/43881 and https://github.com/WordPress/gutenberg/issues/32438

Allow a user to more easily drag a block to the top-most or bottom-most positions.

This PR explores seeing if we can allow a drop event to occur for the list view when a block is dragged outside the list view area, but is still within its horizontal position. Note: this PR does _not_ address the issue where you cannot drag a block to be _beneath_ a non-collapsed Group block. For dragging beneath a collapsed Group block there is a potential fix open over in https://github.com/WordPress/gutenberg/pull/49390

## Why?

Currently it is very difficult to drag a block to the top-most or bottom-most positions in the list view. To do so, you need to drop the block _just_ inside either the top block, or the bottom block, otherwise the drop event will not fire.

## How?

* Use the `dragend` event, and construct a fake drop event to fire if the `dragend` event fires within the horizontal area of the list view (determined by the width of the last block that was hovered over).
* Check that `event.dataTransfer.dropEffect` is set and is not `'none'` so that a user who presses `Escape` to cancel the drag event does not accidentally cause the drop event to fire.

## To-do

* [ ] Ensure this code doesn't fire on an insert event

## Testing Instructions

Play around with the list view, dragging blocks to the top-most or bottom-most positions. It should be easier to do now, as dragging anywhere in the vertical plane should respect the position indicated by the blue popover indicator line.

## Screenshots or screencast 

https://user-images.githubusercontent.com/14988353/228440099-de2b1fa4-0163-4433-901b-902faa30c5b2.mp4

### CODE REVIEW

**Comment by talldan** [comment]
Thanks for working on this as it's a problem that really needs solving.

I'm not sure about this solution, as it seems to require some math hacks, and I don't think it's going to work in all situations (like if there's another UI above or below List View, like there very likely will be in browse mode.)

The same bug exists in the editor canvas too (as well as parent blocks like 'Media and Text'), and the code there is really similar to List View. So I think it'd be good to explore if there's any way to solve the problem in both places. Having said that, if it can be solved only in List View, that's ok too, as improving the user experience is what's paramount.

I think the core of the problem is `useDropZone` and the fact that it isn't very flexible. It returns the `ref` that represents the drop zone, which means it's difficult to bind it to a parent element. Consequently `useListViewDropZone` and `useBlockDropZone` have to also return the `ref`:
```js
function ListView() {
    // dropZoneRef can only be used within ListView.
    const { ref: dropZoneRef, target: blockDropTarget } = useListViewDropZone(); 
 ```
  
An alternative to this PR (and quite a simple fix) is to move `useListViewDropZone` outside of `ListView`:
```jsx
const { ref: dropZoneRef, target: blockDropTarget } = useListViewDropZone(); 
<div className="edit-post-editor__list-view-panel-content" ref={ dropZoneRef }>
    <ListView dropTarget={ blockDropTarget } />
</div>
```

I think it would work, though it is a bit unusual passing `dropTarget` into `ListView`. That part could be refined using react context, I think the general idea is still solid. The only drawback is it wouldn't work as easily as a solution in the editor canvas..

Another option is to refactor `useDropZone` so that it can also accept a ref as an argument:
```jsx
function ListView( { dropZone } ) {
    // dropZoneRef can only be used within ListView.
    const { target: blockDropTarget } = useListViewDropZone( { dropZone } ); 
```

That would be a lot of work, but I think it would potentially provide the solution for the editor canvas too.

**Comment by andrewserong** [comment]
Thanks for the feedback @talldan, that's super helpful! I prefer the idea of lifting up where the `dropZoneRef` is attached, and I was mildly concerned about this PR for all the reasons you mention, and that this code can't know where the mouse is when the `dragend` event fires, so it could be very unexpected. One other case to handle that still might be valuable in terms of allowing drag and drop outside of the list view itself, is that for the top-most position, we might want to allow letting go of the mouse button over the tabs, to be a little more forgiving of that small top area. If we can get a ref to the container, and not just the drop target, then perhaps we could add breathing room of, say, `20px` vertically` 🤔. I can have a play with all these options 👍

One thing that I thought might be worthwhile attempting to tackle first, though, is the issue of dragging to all levels of the block hierarchy: https://github.com/WordPress/gutenberg/issues/33678. I know that one likely won't be simple, but once we extend the area where folks can drag at the very bottom of the list, I think it'll become very apparent that in expanded nested blocks, you can't actually drag to the actual bottom of the list. So it might be worth seeing if we can come up with a solution for that first. Again, I'm having fun digging into these granular list view tasks, so happy to try digging in there, too!

**Comment by talldan** [comment]
> I prefer the idea of lifting up where the dropZoneRef is attached

Agree, that definitely seems like the easiest and most sensible option.

> One other case to handle that still might be valuable in terms of allowing drag and drop outside of the list view itself, is that for the top-most position, we might want to allow letting go of the mouse button over the tabs, to be a little more forgiving of that small top area. If we can get a ref to the container, and not just the drop target, then perhaps we could add breathing room of, say, 20px vertically` 🤔. I can have a play with all these options 👍

Yep, adding breathing room might be an easy solution, if design folks are happy with that.

> Again, I'm having fun digging into these granular list view tasks, so happy to try digging in there, too!

Glad you're enjoying it! I don't have many ideas on how to solve https://github.com/WordPress/gutenberg/issues/33678, so it'll be interesting to see what you can come up with.

**Comment by andrewserong** [comment]
Closing out this PR now, as I think I have a decent version working over in #50726, which allows passing a ref to `useDropZone` 🤞

**Pull request closed without merging**
