### PR TITLE
Add space to the Post Schedule date

### LINKED ISSUE #3138: Long date display in another language
## Issue Overview

The date display too long if using Vietnamese language version.

## Steps to Reproduce (for bugs)

1. Install a fresh WordPress with the Vietnamese language package.
2. Install a Gutenberg language.
3. Try to edit any post using Gutenberg editor.

## Expected Behavior

The date should be shorter and keep left spacing in almost screens.

## Current Behavior

screenshot at oct 25 10-05-01

## Possible Solution

Try to override the short version's date. (I mean replace Month with short if possible).

### PR DESCRIPTION
**Pull request by Soean**
## Description
Adds space between Post Schedule label and date
Resolve #3138 

## Screenshots:
**Before:**
before
before_date

**After:**
after
after_date

### CODE REVIEW

**Review by aduth — CHANGES_REQUESTED** [review]
This looks like a good idea, but I think the styling should be applied to children of `components-panel__row` generally, not specific to the schedule toggle.

https://github.com/WordPress/gutenberg/blob/master/components/panel/style.scss

**Comment by Soean** [comment]
@aduth You are right, thats a better idea. I added the styling to `.components-panel__row label` and added the missing labels to post-schedule and post-visibility. I also added a id to the Dropdown component.

**Review by aduth — COMMENTED** [review]
There are some issues with the labeling changes (which I'd also have recommended to create a separate pull request for):

- With component patterns as in React, we don't want to assume that there is a single instance of an element on a page, and since `id` must be globally unique, `'post-visibility-selector'` is not a good ID. For these cases we created the [`withInstanceId` higher-order component](https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-instance-id) to generate unique IDs to use as suffixes.
- Since Dropdown expects the developer to implement `renderToggle` with a button, we don't need it to accept an `id` prop and rather can apply the `id` on the button returned in `renderToggle` (in `PostSchedule` and in `PostVisibility`).

**Comment by Soean** [comment]
I created a separate pull request for the labels: #3317, so this one has to be merged first.
This PR only adds space to the panel row labels and align the post schedule text.

**Review by aduth — APPROVED** [review]
Looks good 👍

**Pull request merged**
