### PR TITLE
Documentation: update install commands and babel config

### PR DESCRIPTION
**Pull request by oandregal**
This PR fixes some problems I ran into when following the [current guide](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/javascript/js-build-setup/). It also promotes the use of `--save-exact` as a good hygiene practice.

- It asked me to install a webpack CLI (so I included it in the install commands):

webcli-required

- It failed to compiled due to incompatible babel packages:

build-fail

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
I'm not quite sure why `--save-exact` solves this issue given that both webpack and `@wordpress/scripts` follow semantic versioning. However if that helps, I'm fine with the changes proposed.

**Comment by nosolosw** [comment]
@gziolo `--save-exact` is not required and can totally be dropped from this PR. It's a personal preference that I thought it was worth promoting as a good practice. I'm fine removing that from the PR if that's controversial.

**Comment by gziolo** [comment]
It might be something about the dependencies included by `@wordpress/scripts`. It's hard to judge based on Gutenberg because there are thousands of dependencies listed. I assume this is going to be no issue as soon as we have the default Webpack config included in the scripts exposed by the package we offer :)

**Comment by nosolosw** [comment]
The root problem seems related to `babel-loader@8` requiring `@babel/plugin-transform-react-jsx` while `babel-loader@7` requires `babel-plugin-transform-jsx`, which is a different thing, apparently. So depending on which version of `babel-loader` gets installed, the other dependencies need to be adjusted.

**Comment by gziolo** [comment]
Do you know what is using Babel 6 specific packages causing babel-loader@7 to be pulled in?

**Comment by nosolosw** [comment]
@gziolo not sure I follow. Here's what I know:

* Installing `babel-loader` will pull the latest version (8). That version requires `@babel/plugin-transform-react-jsx`. 
* If we wanted to use `babel-plugin-transform-react-jsx` we should explicitly install `babel-loader@7`.

I chose to go with the first option because that's what Gutenberg uses.

**Comment by gziolo** [comment]
> * If we wanted to use `babel-plugin-transform-react-jsx` we should explicitly install `babel-loader@7`.

Why would you want to install it in the first place? 

> I chose to go with the first option because that's what Gutenberg uses.

Yes, this is highly expected.

**Review by gziolo — APPROVED** [review]
Let's update for the time being and wait until we can address https://github.com/WordPress/gutenberg/issues/13712 to make it perfect.

**Pull request merged**
