### PR TITLE
Lighter block DOM: Navigation

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Makes the navigation block (and inner blocks) light blocks. The goal is to have the same structure as the front-end.

Especially worth noting is the fact that we can now use the `ul` and `li` tags. This is something that wasn't possible before because the list items couldn't be direct children of `ul`.

Screenshot 2020-03-09 at 15 42 18

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
This is looking pretty good and I don't see any regressions. It may be that there's a slight difference in the editor, but nothing that I'm seeing right now. If there's a regression, I'll create a follow up PR. As noted above, I believe this is a big step in the direction of being able to share more styles between the front-end and editor.

**Comment by jasmussen** [comment]
This caused a small regression.

Before:

Screenshot 2020-03-10 at 12 22 15

After:

Screenshot 2020-03-10 at 12 22 28

It appears this rule is at fault:

Screenshot 2020-03-10 at 12 25 53

The width of the `.wp-block-navigation-link` must be `auto`, or it won't work.

**Comment by ellatrix** [comment]
@jasmussen Strange, for me the inserter icon appeared horizontally. I'll check again.

**Comment by ellatrix** [comment]
@jasmussen I'm seeing this:

Screenshot 2020-03-10 at 12 32 00

**Comment by jasmussen** [comment]
Oohh it may be a TwentyNineteen issue. Let me verify.

**Comment by ellatrix** [comment]
Oooh, sorry, I didn't pull the new commits yet.

**Comment by jasmussen** [comment]
Confirmed 😱 

Thanks for bearing with my bad report here! Though I do suspect that as the DOM gets closer to the frontend (yaaay) we'll see more and more of these things pop up due to themes doing their best to style the old markup.

**Comment by ellatrix** [comment]
Pulled the commits, and it's still fine:

Screenshot 2020-03-10 at 12 34 45

**Comment by jasmussen** [comment]
Yep, it's TwentyNineteen. I'll create a trac ticket when I have a moment.

**Comment by ellatrix** [comment]
@jasmussen Tbh, I think we should attempt to also remove the appender from the editor DOM, and float it behind the last items or something, similar to the sibling inserter (in between inserter). The appender shouldn't be part of the content and take up space. We have a similar problem in the column block where the appender continuously changes the height of the column without any actual content being changed.

**Comment by jasmussen** [comment]
I've no strong opionion there. But would you suggest _not_ creating a trac ticket to fix this in TwentyNineteen?

**Comment by ellatrix** [comment]
@jasmussen Oh, I'm not opposed to patching anything up in the meantime. :)

**Comment by jasmussen** [comment]
Created https://core.trac.wordpress.org/ticket/49613 to track it :)

**Pull request merged**
