### PR TITLE
Chrome: Adding a post format selector with a suggestion

### LINKED ISSUE #1722: Post format needs to be a selector
Right now we infer post formats. If you have multiple blocks, you get the standard post format:

screen shot 2017-07-05 at 13 30 36

If you have only an image, you get an image post format:

screen shot 2017-07-05 at 13 30 52

This is cool, but you also need to explicitly be able to choose it yourself. So it should be a dropdown or selector interface like the visibility one.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #1722

screen shot 2017-08-09 at 11 07 25

Maybe it needs some design 👀

### CODE REVIEW

**Comment by jasmussen** [comment]
I love it! 👍 👍 👍 👍

Works much better than I'd expected it to.

Do we have any control over this list?

screen shot 2017-08-09 at 12 56 00

I.e. can we ensure they're all titlecase? If not behind the scenes then at least visually in the dropdown?

**Comment by youknowriad** [comment]
> Do we have any control over this list?

Yes, this was just a small mistake of mine

**Comment by paaljoachim** [comment]
Having a suggestion below the drop box brings too much importance. I look at it and become confused. It is better that it auto detects what kind of blocks are present and suggests a post format based on it.

**Comment by youknowriad** [comment]
@paaljoachim That was the plan but we can't set it automatically because we can't differentiate whether it's explicitly set by the user or set by a suggestion. (Details on the issue)

**Comment by paaljoachim** [comment]
@youknowriad 
"...we can't differentiate whether it's explicitly set by the user or set by a suggestion."
Does it matter? (I guess it does..:) A suggestion can be set and if the user wants to change it they can. Ok I will let it go.

**Comment by jasmussen** [comment]
@paaljoachim your input is not going on deaf ears. I happen to agree with you: post formats should go away. In fact part of the genesis of blocks as a concept is to provide a better interface than what post formats did. So the post format selector here is strictly a back-compat thing.

**Comment by paaljoachim** [comment]
@jasmussen 
Alrighty..:)

**Comment by youknowriad** [comment]
> A suggestion can be set and if the user wants to change it they can. Ok I will let it go.

@paaljoachim Just to clarify this point. The question is when do you set the suggestion? If we set when we create the post, it will always be "standard", we can set it after the user inserts one block, but what if the user deletes and insert another block, should we update the suggestion, how do we know if it's a suggestion or if the user already updated it?

**Comment by paaljoachim** [comment]
> The question is when do you set the suggestion?

What about starting out with the most used format.
I am guessing that most users will not at all touch it and just leave it as "standard".

What about a check just after the user clicks save or publish and if needed have the post format change to what is most used.

**Comment by youknowriad** [comment]
@paaljoachim We already discussed these in the issue and in yesterday's chat too.

> What about starting out with the most used format.

This is already the case

> What about a check just after the user clicks save or publish and if needed have the post format change to what is most used.

What if the user doesn't want its format to be overridden when he hits "save" how do w know if it's a suggestion or not.

**Comment by youknowriad** [comment]
Ok; should we move on with this, and try improvements separately if needed?

**Comment by jasmussen** [comment]
Yep I think we should move on and everyone should feel free to open tickets and improve further!

**Pull request merged**
