### PR TITLE
Simplify the block selected state

### PR DESCRIPTION
**Pull request by youknowriad**
Related #18667 

Now that there's no hover state, is there any reason to keep the large left border?
This PR removes it.

Capture d’écran 2019-12-10 à 2 06 49 PM

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
Adding the "Needs Accessibility Feedback" label because I vaguely recall there being color contrast reasons for having the strong left border due to the rest of the border not having high enough contrast. It would be good to make sure this change makes sense from an accessibility standpoint.

**Comment by pablohoneyhoney** [comment]
We could explore a better contrast ratio for the existing border instead of an added UI to solve the former.

**Comment by jasmussen** [comment]
While I haven't been a fan of the left border and don't feel like it solved the problem it meant to solve, it seems like the better solution is to explore some of the focus style enhancements being discussed in #18667 and do those together. As an interim step towards that, suspect this will only confuse.

**Comment by youknowriad** [comment]
Thanks all for your feedback, I pushed a commit to use a consistent and darker color for the borders inside the canvas. (I didn't touch the ones outside the canvas).

The good thing with the last commit is that now we can tweak the border color by just changing a single SASS variable.

The problem though is now we do feel inconsistency between the canvas and the rest of UI so the question again is where to draw the line? What is the minimum shippable version? Will we have to do it all at once, how can we do it step by step?

**Comment by youknowriad** [comment]
Capture d’écran 2019-12-11 à 9 19 23 AM

**Comment by jasmussen** [comment]
I don't think this UI change can be done step by step. This is one of those where we need to finalize the visuals we want, and implement that. This definitely removes the left border, that's good, but it's transversal to the explorations in #18667 which are still receiving thoughts and feedback.

**Comment by karmatosed** [comment]
> I don't think this UI change can be done step by step.

Unfortunately, I feel the same. There is however a reason to get rid of the border and 'dark line' as it is very clumsy and not a great indicator as you go into child blocks, for example, the navigation.

On select right now:

image

image

Holistically, bringing the changes in with this also feels right as one.

**Comment by shaunandrews** [comment]
image

What if we change the color of the border just on the block, and leave the others as-is? This helps bump the contrast without needing the overly aggressive thick left-border.

**Comment by mapk** [comment]
I second the comments from Joen. We can't implement this new UI piece-by-piece and will need to finalize the direction on this before making this change. I would rather we hold off on these changes until we have a strong unified direction forward.

**Comment by youknowriad** [comment]
Closing this in favor or #19344

**Pull request closed without merging**
