### PR TITLE
Comments Query Loop block: Rename to Comments (but keep ID)

### PR DESCRIPTION
**Pull request by ockham**
## What?
Rename the Comments Query Loop block to Comments.

## Why?
The block has never really been a _query loop_ (the query can't really be customized, unlike the (post) Query).
And it no longer is just a loop: For parity with its monolithic predecessor block (Post Comments, which is now deprecated and hidden from the inserter), we're now adding Comments Title, Comments Pagination, and Post Comments Form blocks to its default template.

Furthermore, as a user looking for “a block to display my comments”, I probably wouldn’t click on “Comments Query Loop” as my first choice in the inserter.

So in order for this block to convey to the user that it is the "authoritative" block to display comments, I'd like to propose we rename it accordingly.

## How?
Rename the block.

We have another PR (#40506) that would also change the block ID (from `core/comments-query-loop` to `core/comments`). I opted to file a PR for _just_ changing the block name (but not the ID) in order to de-risk this. (I'd still love if we could also change the ID, but this way, we can discuss it separately.)

## Testing Instructions
Verify that the block is now called 'Comments' in the inserter and elsewhere.

### CODE REVIEW

**Comment by ockham** [comment]
Heads-up @adamziel and @gziolo -- I'd like to get this into the RC1 tomorrow if possible 🙂 See PR desc for the rationale.

**Review by michalczaplinski — APPROVED** [review]
Looks good to me! 👍 

- Tested in site editor ✅
- Tested in post editor ✅
- Tested creating the Comments Query Loop block on `trunk` and then switching to this branch. The block is renamed to "Comments" ✅

PS. I've also updated the CODEOWNERS file.

**Comment by michalczaplinski** [comment]
Hmm, looks like the e2e test is broken after all. I'm investigating.

**Comment by michalczaplinski** [comment]
It appears that in the e2e test, for some reason, the block's name is not updated.
The same test failure appears locally for me as in the CI.

The block shows up as **Comments Query Loop** but it should be just **Comments**:

Screenshot 2022-05-02 at 15 47 14

**Comment by ockham** [comment]
> It appears that in the e2e test, for some reason, the block's name is not updated. The same test failure appears locally for me as in the CI.
> 
> The block shows up as **Comments Query Loop** but it should be just **Comments**:
> 
> Screenshot 2022-05-02 at 15 47 14

I checked CI artifacts, but those seemed circumstantial and unrelated to the rename. I re-ran e2e tests, and they passed, so I _think_ we're good here.

**Comment by michalczaplinski** [comment]
That's weird 🤔 Because I saw the same failure happening locally on my machine. 

Could that be because some of the backports were merged into Core in the meantime (between the time I tested and you re-ran the CI)?

**Comment by ockham** [comment]
> That's weird 🤔 Because I saw the same failure happening locally on my machine.
> 
> Could that be because some of the backports were merged into Core in the meantime (between the time I tested and you re-ran the CI)?

Possibly (I did check the artifacts for the CI's e2e test failures _before_ re-running though).
My hunch is that locally, GB picks up blocks (or at least `block.json` settings) from Core if they're already there.
There's a chance that that's also true for CI and that the fact that it's passing now is a false negative. But I think the only way to remediate that would be a backport, so I'm not too worried about it TBH 🙂

**Comment by gziolo** [comment]
It looks like the class name for the block remains `wp-block-comments-query-loop`. The test fixture also uses the old name:

https://github.com/WordPress/gutenberg/blob/trunk/test/integration/fixtures/blocks/core__comments-query-loop.html

**Comment by ockham** [comment]
> It looks like the class name for the block remains `wp-block-comments-query-loop`. The test fixture also uses the old name:
> 
> https://github.com/WordPress/gutenberg/blob/trunk/test/integration/fixtures/blocks/core__comments-query-loop.html

Thanks for flagging @gziolo. FWIW, this PR changed the block name and file/directory names, but not the block ID. So to me, it seems to make sense that the block class name remains `wp-block-comments-query-loop` (and the test fixture also uses `core__comments-query-loop`), since each of them are derived from the ID rather than the name?

Curious to hear your thoughts 🙂 

(FWIW, we're planning to tackle the ID change separately (#40506), or even merge the Comments Query Loop and Post Comments blocks after all (#40521).)

**Comment by gziolo** [comment]
> (FWIW, we're planning to tackle the ID change separately (https://github.com/WordPress/gutenberg/pull/40506), or even merge the Comments Query Loop and Post Comments blocks after all (https://github.com/WordPress/gutenberg/issues/40521).)

Yes, option number 2 would be ideal 👍🏻

**Comment by adamziel** [comment]
I'm removing the `Backport to WP Minor Release` label. This PR changes the JavaScript exports which are a public API – it seems like too much of a change between 6.0.0 and 6.0.1.

**Pull request merged**
