### PR TITLE
Prevent default enter key behaviour in title

### PR DESCRIPTION
**Pull request by ellatrix**
I noticed an odd behaviour when pressing enter in the title: it inserts a space and the caret is moved to the end. I'm not sure if this is intentional.

This PR would ignore enter key presses. Feel free to close if the current behaviour is intended or if it needs a different fix.

### CODE REVIEW

**Comment by youknowriad** [comment]
The behaviour was intended (and is inspired by Calypso). It has been done for this issue https://github.com/WordPress/gutenberg/issues/722

---
That said, it's legitimate to question it. cc @jasmussen

**Comment by aduth** [comment]
Yeah, I think we'll want the replacement still, because this regresses to behavior where pasting a piece of text containing multiple lines will not try to strip newlines.

image

I think it may have been enough to `.trim()` the value before calling `.replace`?

**Comment by iseulde** [comment]
If we still do the replacement, it seems we'll have to fix the selection.

**Comment by aduth** [comment]
What about the selection?

**Comment by iseulde** [comment]
> I noticed an odd behaviour when pressing enter in the title: it inserts a space and the caret is moved to the end. I'm not sure if this is intentional.

**Comment by aduth** [comment]
>I think it may have been enough to `.trim()` the value before calling `.replace`?

**Comment by iseulde** [comment]
@aduth I'm not sure I understand. Do you mean:

```const newTitle = event.target.value.trim().replace( REGEXP_NEWLINES, ' ' );```

That doesn't seem to fix the selection issue.

**Comment by iseulde** [comment]
I changed it so that only the `keydown` event is added. Newlines are still stripped before updating the title to ensure no other input method can add them. I think it's still not ideal though, because pasting some text with newlines will still move the caret to the end.

**Review by nylen — APPROVED** [review]
+1 on preventing Enter keypresses.  It would be nice to fix the selection / caret movement issues too, but I think this can be done in a separate PR.

**Comment by aduth** [comment]
>@aduth I'm not sure I understand. Do you mean:

This is what I meant, yes. I see what you mean now. My suggestion fixed only the case when pressing enter at the end of the title, but not in the middle. I think default prevention is fine here. Just looking out for the case where we paste content, but the compromise seems to cover both well.

**Pull request merged**
