### PR TITLE
Progressive browser rendering for FSE templates - See #24378

### PR DESCRIPTION
**Pull request by aristath**
This PR aims to change the way FSE content gets rendered, in an effort to make it more efficient and performant.
For full details please refer to #24378 

## How has this been tested?
Tested by trying out FSE themes with lots of content

## Types of changes
Added a new `gutenberg_render_the_block_partial()` function. That function extracts some of the logic from `gutenberg_render_the_template()` and does it on a per-block basis, then renders that block.
Inside the `gutenberg_render_the_template()` function, instead of `do_blocks` we're now calling `parse_blocks()` and then call the new `gutenberg_render_the_block_partial()` function for each block.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] ~~My code follows the accessibility standards.~~ 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by mcsf** [comment]
The idea of chunking around blocks to iteratively output content makes sense. That said, currently the risk is for us to forget about the [special provisions that `do_blocks` makes around `wpautop`](https://github.com/WordPress/wordpress-develop/blob/3a19ff15f9013f7acf6951def3937807ea87733f/src/wp-includes/blocks.php#L762-L767). They might seem less pressing now as we get FSE rolling, but we'll need consistent rendering methods across core / `post_content` and FSE / templates, so that we don't introduce breaking changes by accident.

**Comment by aristath** [comment]
> The idea of chunking around blocks to iteratively output content makes sense. That said, currently the risk is for us to forget about the special provisions that do_blocks makes around wpautop. They might seem less pressing now as we get FSE rolling, but we'll need consistent rendering methods across core / post_content and FSE / templates, so that we don't introduce breaking changes by accident.

Good point :+1: 
Added.

**Comment by aristath** [comment]
This PR is outdated and will need to be revisited, a lot of things have changed since it was first submitted.
Drafting it for now so we can revisit later

**Comment by aristath** [comment]
Closing this one as it is no longer applicable. The issue is still semi-valid, but we'll need to come up with a different solution if we want to do it.

**Pull request closed without merging**
