### PR TITLE
Scripts: Allow CSS modules in the build commands

### PR DESCRIPTION
**Pull request by cpiber**
## Description

@wordpress/scripts modified config to allow css modules (and extract them like style.css)

## Checklist:
- [x] My code is tested.

### CODE REVIEW

**Comment by gziolo** [comment]
Hi @cpiber. Thank you for your contribution. Can you provide more details for the proposed change?
- What issue is it trying to solve?
- How it can be tested?
- How it should be documented?

**Comment by cpiber** [comment]
- It allows for using css modules. The webpack plugin css-loader already supports that.
- I'm not sure how you usually set webpack configurations. The changes I made will compile `.*.module.(sa|sc|c)ss` files with css modules enabled. They also extract `style(.module)?.(sc|sa|c)ss` files (so module files as well).
- In the readme there is the "Using CSS" section, possibly mention the use of css-modules there as well.

**Comment by gziolo** [comment]
> In the readme there is the "Using CSS" section, possibly mention the use of css-modules there as well.

That would be a great addition with an example of the file and its content maybe? There is already a section with CSS:
https://github.com/WordPress/gutenberg/tree/trunk/packages/scripts#using-css

I guess once we have documentation. It only needs to be tested and we are good to go. Thank you for your contribution 🙇🏻

**Comment by cpiber** [comment]
To clarify, do you want me to edit the README?

**Comment by gziolo** [comment]
> To clarify, do you want me to edit the README?

Yes, that would be helpful for folks using `wp-scripts`. 

A section `New Feature` in the changelog would also help with discovery:

https://github.com/WordPress/gutenberg/blob/trunk/packages/scripts/CHANGELOG.md

**Comment by gziolo** [comment]
It looks like you merged your branch with the upstream `master` branch. It was renamed to `trunk` so that would explain why there are additional 400+ commits in your PR 😄

**Comment by cpiber** [comment]
I rebased on `trunk`, yes

**Comment by gziolo** [comment]
I'm not sure what went wrong but there should be only your changes listed in this PR. You can try following this documentation and see if it helps:
https://github.com/WordPress/gutenberg/blob/trunk/docs/contributors/code/git-workflow.md#keeping-your-fork-up-to-date

**Comment by cpiber** [comment]
I used `rebase` instead of `merge`, maybe that was a problem? Should I go back to an earlier commit and try with `merge` again?

**Comment by gziolo** [comment]
You can also cherry-pick your commits to a fresh branch if that helps. Whatever makes it work and I can merge your changes 😄

**Comment by cpiber** [comment]
Alright, I went back to the old master and did a merge instead of a rebase, I hope it's okay now

**Review by gziolo — APPROVED** [review]
Thank you for your contribution. This looks good to go 🎉

**Pull request merged**
