### PR TITLE
useRefEffect: Replace undefined with void in callback return type

### PR DESCRIPTION
**Pull request by walbo**
## What?

Updates TypeScript definitions on the `useRefEffect` hook.

## Why?

When using the `useRefEffect` function without having a cleanup function there is a TypeScript error.

Example:
```jsx
const ref = useRefEffect< HTMLInputElement >(
  ( node ) => {
    if ( ! node ) {
      return;
    }

    // Do something
  },
  [ value ]
);
```
will result in `Type 'void' is not assignable to type '() => void'.ts(2345)`

The hook should allow `void` as a return type.

## How?

Update the TypeScript definition to allow void

## Testing Instructions
1. Test the `useRefEffect` without a cleanup function
2. Test the `useRefEffect` with a cleanup function
3. TypeScript should not have any errors.

### CODE REVIEW

**Review by ciampo — COMMENTED** [review]
Thank you for working on this, @walbo !

The changes LGTM, but I'd feel safer if @sarayourfriend (who wrote these types in the first place) also took a look.

Could you add an entry to the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/compose/CHANGELOG.md)?

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
This LGTM and thanks for the fix :grin:  It is not a backwards breaking change but is a good usability fix. Can you add an entry to the compose CHANGELOG.md?

**Comment by ciampo** [comment]
> Can you add an entry to the compose CHANGELOG.md?

Just realised I linked to the wrong changelog — I updated the link in my comment above!

**Comment by sarayourfriend** [comment]
Ah, I'm sorry to have duplicated your comment, Marco.

**Comment by walbo** [comment]
Will add an entry to the changelog 👍

**Review by sarayourfriend — APPROVED** [review]
Thank you @walbo!

**Pull request merged**
