### PR TITLE
Polish G2

### PR DESCRIPTION
**Pull request by jasmussen**
This is a work in progress. 

For the time being, it addresses feedback in https://github.com/WordPress/gutenberg/issues/20575#issuecomment-595459030:

Screenshot 2020-03-06 at 10 01 53

But I will also push some fixes to the plusses appearing, and the alignment of block mover icons.

### CODE REVIEW

**Comment by jasmussen** [comment]
Fixed alignments of chevrons:

Screenshot 2020-03-06 at 10 21 22

**Comment by jasmussen** [comment]
Actually that other issue I meant to fix is addressed. So this PR is ready for review!

**Review by youknowriad — APPROVED** [review]
LGTM 👍 

It would be cool if we had dedicated PRs per bug as it's not easy to know what to test in "polish" PRs :P

**Comment by youknowriad** [comment]
There are some snapshots to update

**Comment by jasmussen** [comment]
Thanks for the review. Noted about the polish PRs — bad habit!

I tried updating the snapshots but got a failure:

```
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at ChildProcessWorker.send (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
    at WorkerPool.send (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/Farm.js:129:10)
    at Farm._enqueue (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/Farm.js:152:10)
    at Farm._push (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/Farm.js:159:12)
    at /Users/joen/GIT/gutenberg/node_modules/jest-worker/build/Farm.js:90:14
    at new Promise (<anonymous>)
    at Farm.doWork (/Users/joen/GIT/gutenberg/node_modules/jest-worker/build/Farm.js:56:12)
```

any insights?

**Comment by youknowriad** [comment]
that's a weird error, I've never seen it.

**Comment by jasmussen** [comment]
Do the snapshots update for you? Or is there a legitimate test failure perhaps?

**Comment by youknowriad** [comment]
I updated the snapshots, let's see it passes.

**Comment by jasmussen** [comment]
Can't get the tests to pass on this one. I even tried squashing so I could force-push and force a re-test.

**Comment by jasmussen** [comment]
Oh weird, a JS Unit test is failing, this one: https://travis-ci.com/WordPress/gutenberg/jobs/295287310

```
FAIL packages/components/src/color-picker/test/index.js
  ColorPicker
    ✕ should render color picker (41ms)
    ✕ should only update input view for draft changes (18ms)
    ✕ should commit changes to all views on blur (19ms)
    ✕ should commit changes to all views on keyDown = UP (17ms)
    ✕ should commit changes to all views on keyDown = DOWN (21ms)
    ✕ should commit changes to all views on keyDown = ENTER (17ms)
```

This seems completely unrelated to this PR. I wonder what it is?

**Comment by youknowriad** [comment]
For some reason, I didn't update all the snapshots previously.

**Pull request merged**
