### PR TITLE
Fix center alignment on the dropdown in the categories block

### LINKED ISSUE #43982: Categories (List) block center alignment is not working with dropdown in editor
### Description

Categories block center alignment setting is not reflecting on editor side.

### Step-by-step reproduction instructions

Activate the Twenty Eleven Theme
Add Categories Block (or "Categories List" block if Gutenberg plugin is activated)
Select the "Display as dropdown" option in the sidebar
Change the alignment to center

### Screenshots, screen recording, code snippet

Here is Screen Recording:[https://share.cleanshot.com/CDO3nlFrsNj3r6TpLJH5](https://share.cleanshot.com/CDO3nlFrsNj3r6TpLJH5)

### Environment info

WordPress : 6.0.1
Twenty Eleven Theme

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by carolinan**
## What?

Add `text-align:center` to the block CSS so that the block can be centered when the "Display as dropdown" option is used.
Fixes https://github.com/WordPress/gutenberg/issues/43982

## Why?

The center alignment was not working in the editor or the front.

## How?

The markup in the editor and front is different, so CSS needed to be added to both style.scss and editor.scss.
The text alignment is limited to when the dropdown option is used, because otherwise, the text inside the list items would be centered, but not the list bullets.

## Testing Instructions
1. In the block editor, add two categories blocks.
2. Center both, and turn on "Display as dropdown" on one of theme.
3. Confirm that both blocks are centered.
4. Save and view the front, confirm that both blocks are centered on the front.

### CODE REVIEW

**Comment by Mamaduka** [comment]
I saw this PR this morning #44004.

I trust your judgment on the preferred method to resolve the issue.

**Comment by carolinan** [comment]
I forgot that there was work being done to the markup and class names in https://github.com/WordPress/gutenberg/pull/43666, marking as blocked for now.

**Comment by carolinan** [comment]
@theminaldiwan I see it now, `[data-align="center"]` is used in the editor,  **only** for classic themes. I will add it back.

**Comment by carolinan** [comment]
After, with Twenty Eleven:
Editor view of Twenty Eleven, dropdown is centered

Front:
Front view of Twenty Eleven, dropdown and list are centered

Twenty Twenty-Three:
Editor view of TT3, dropdown is centered

Front:
Front view of TT3, dropdown is centered

**Comment by carolinan** [comment]
@theminaldiwan I'm sorry it took me so long to get back to this. I would appreciate your help with testing the PR with a classic theme and a block theme. 


Also, I am not sure what the expected design is for the center when the block uses a list. In block themes, the bullets and text are not centered like they are in the Twenty Eleven.

**Review by aristath — APPROVED** [review]
This looks good to me.
It fixes the issue we currently have, where center-aligning this doesn't work.
Different themes can apply different behaviours if they wish to do so, but I think we should have the option working in Core - which this PR does.

**Pull request merged**
