### PR TITLE
Don't add root padding to children of flex and grid layout blocks.

### LINKED ISSUE #50861: Bug on `useRootPaddingAwareAlignments` mode when using `core/columns` block with `alignfull`
### Description

When `useRootPaddingAwareAlignments` mode is enabled (on `theme.json`), root left and right padding will be added to `core/group` blocks with a `constrained` layout, and any nested full-width (`alignfull`) blocks will stretch outside of the parent group itself.

The children of the `alignfull` blocks will also get additional left and right padding to compensate for the negative margin given to the `alignfull` parent block.

However, this causes issues if the `alignfull` block is a `core/columns` block. The `core/column` blocks inside will automatically get additional left and right padding.

This issue also happens on `core/group` block with `row` mode (horizontal flex).

This issue doesn't happen in the Block Editor preview, only on the frontend side.

### Step-by-step reproduction instructions

1. Test using a fresh installation of WordPress 6.2.2 and use the default TwentyTwentyThree theme.
2. Create a new page and insert this block snippet:
```
<!-- wp:columns {"align":"full","backgroundColor":"cyan-bluish-gray"} -->
<div class="wp-block-columns alignfull has-cyan-bluish-gray-background-color has-background"><!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:paragraph {"backgroundColor":"luminous-vivid-amber"} -->
<p class="has-luminous-vivid-amber-background-color has-background">Paragraph on The Left Column</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"50%"} -->
<div class="wp-block-column" style="flex-basis:50%"><!-- wp:paragraph {"backgroundColor":"light-green-cyan"} -->
<p class="has-light-green-cyan-background-color has-background">Paragraph on The Right Column</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```
3. Publish or save, and then view the page on the frontend side.

### Screenshots, screen recording, code snippet

Screen Shot 2023-05-23 at 14 18 53

### Environment info

- WordPress 6.2.2
- TwentyTwentyThree theme
- Gutenberg 15.8.1 (bug occurs with or without Gutenberg plugin)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### LINKED ISSUE #52721: Gallery block: inline padding applied on nested images (`<figure>` tag) when Gallery is full aligned
### Description

With Gutenberg 16.2.1 when I add a Gallery block into post/page content and make the gallery full aligned, the nested `<figure>` tags (for each individual gallery image) has horizontal padding applied.

This happens in block theme that has these `theme.json` settings (among others):
```json
{
	"$schema" : "https://schemas.wp.org/trunk/theme.json",
	"version" : 2,

	"settings" : {
		"useRootPaddingAwareAlignments" : true
	},
	"styles" : {
		"spacing" : {
			"padding"  : {
				"top"    : "0",
				"bottom" : "0",
				"right"  : "4vw",
				"left"   : "4vw"
			}
		}
	}
}
```

Everything is fine on WordPress 6.2.2 without Gutenberg plugin.

### Step-by-step reproduction instructions

1. Use appropriate theme (see description).
2. Add a Gallery block to the post content.
3. Make the Gallery full aligned.
4. Observe gaps in gallery images.

### Screenshots, screen recording, code snippet

gallery block issue

### Environment info

- WordPress 6.2.2
- Gutenberg 16.2.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Fixes #52721 and #50861.

Modifies the root padding rules to not add root padding to children of full width flex and grid layout blocks. 

This change means that there will now be no space between children of full width flex and grid blocks and edges of the window. It might mean adding some extra margin to the parent block if this is not the desired outcome, but that is probably better than having padding on every single child block, which throws off the block spacing.

## Testing Instructions

1. Add a Row block to a post and make it full width;
2. Verify that its children don't have root padding in the editor or in the front end;
3. Activate the Grid experiment in Gutenberg > Experiments;
4. Add a Grid block to a post and make it full width;
5. Verify that its children don't have root padding in the editor or in the front end;
6. Convert the Row to a Group block and uncheck its "Inner blocks use content width" setting;
7. Verify that child blocks now have root padding in both editor and front end.

### CODE REVIEW

**Comment by andrewserong** [comment]
Thanks for putting up this fix! I'm about to wrap up for the day, so just a quick drive-by comment: will we also need to factor in the grid layout type in the chained `:not()` rules?

I can give this PR a proper test tomorrow!

**Comment by tellthemachines** [comment]
> will we also need to factor in the grid layout type in the chained :not() rules?

yes 😄

**Review by andrewserong — APPROVED** [review]
This is testing great for me! While it is potentially a breaking change if there are templates that folks are using that expect these rules (e.g. full width Stack blocks), this change feels like the desired behaviour for how root padding should work, that is: it applies to children of flow and constrained layouts, and not flex or grid layouts 👍

Testing a full-width Row and Stack block, and that switching to flow layout in the Group block still results in root padding being applied correctly:

https://github.com/WordPress/gutenberg/assets/14988353/2840c7d0-77f5-41bc-8eec-284cda062e5c

For Grid or Flex layouts that wish to use the root padding, it's still possible for them to effectively do this via wrapping the blocks in a flow Group block:

https://github.com/WordPress/gutenberg/assets/14988353/d3cbc4bf-0a50-423f-91a9-bfe660316de4

So, IMO this optimises for the more common use case (full width flex or grid is expected to be full width even if root padding is used), while not preventing folks from taking advantage of root padding via a more complex block structure (wrapping in Group if need be).

Looks good to try out in the plugin to me! ✨

**Comment by tellthemachines** [comment]
Thanks for reviewing and testing @andrewserong!

**Comment by dhrumilkumbhani** [comment]
@carolinan I have tested it with the twenty twenty four and.
Planned changes are in progress regarding the spacing of blocks that utilize flex or grid in WordPress 6.4. It's worth noting that the backport of this change has not yet been committed to the WordPress core. Therefore, at this moment, it's crucial to thoroughly test the theme structure and patterns involving nested blocks using the latest active version of Gutenberg and WordPress 6.4.

I have personally conducted tests, and I'm pleased to report that everything is functioning as expected for me.

**Pull request merged**
