### PR TITLE
WIP: make shift+enter work in lists

### LINKED ISSUE #11215: Be able to make line breaks in list block
When making lists, I often break up the content within an item with a line break (Shift+Enter). This helps make the item more readable and is appropriate for items that have longer text. 

Just as we can do in a paragraph block, I'd like to be able to use SHIFT+ENTER to create a line break that doesn't result in a new block.

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
Fixes #11215. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by youknowriad** [comment]
It seems like indent/outdent buttons are not working properly when I have new lines in list items?

**Comment by iseulde** [comment]
@youknowriad Hm, seems to work for me. Maybe it's gone after the rebase? If not, could you provide exact steps?

**Comment by youknowriad** [comment]
nothing special just use this

```html
<!-- wp:list -->
<ul><li>test<br>sdf<br>sdf</li><li>test</li><li>test</li></ul>
<!-- /wp:list -->
```

put the caret in the second list item and click the "indent" button.

**Comment by youknowriad** [comment]
Oh sorry! you're right, it's gone after the rebase.

**Comment by youknowriad** [comment]
Oh sorry! you're right, it's gone after the rebase.

**Comment by youknowriad** [comment]
I think, now that we have this PR. We should update the transform from the paragraph to list to avoid creating multiple list items if we have `<br>` elements in the paragraph block.

**Comment by iseulde** [comment]
@youknowriad If I remember correctly that logic was added by intention. I believe someone asked specifically to have it like this, and I kind of agree that it makes sense. Cc @mcsf.

**Comment by youknowriad** [comment]
Right now if you select three paragraphs, each one with three lines (`<br>`), and convert them to a list it creates a list with 9 items instead of 3, it doesn't feel right to me personally.

**Comment by iseulde** [comment]
@youknowriad Yeah that's true. I think we shouldn't convert on line breaks if multiple paragraphs are selected. If only one is selected, we can create list items from every line. How does that sound?

**Comment by youknowriad** [comment]
I prefer consistency but it's better yes

**Review by youknowriad — APPROVED** [review]
LGTM 👍 Maybe a small e2e test?

**Comment by iseulde** [comment]
Yes, just added it :)

**Comment by mcsf** [comment]
> Yeah that's true. I think we shouldn't convert on line breaks if multiple paragraphs are selected. If only one is selected, we can create list items from every line. How does that sound?

Sounds good to me, @iseulde.

**Comment by iseulde** [comment]
@mcsf Already merged in #13832. :)

**Pull request merged**
