### PR TITLE
Tree Grid: use framer motion for all animations

### PR DESCRIPTION
**Pull request by gwwar**
This PR updates the TreeGrid component to use framer-motion. When children are added/removed or deleted, we can note that these actions should be animated from one state to another with a simple `layout` prop.

This enables behaviors like:

#### Animating on move (existing behavior)

https://user-images.githubusercontent.com/1270189/127549278-2b34d0f4-708b-4783-8f18-7940e7f8e9dd.mp4

#### Animate expand/collapse of list items (new)

https://user-images.githubusercontent.com/1270189/127549830-46bd4452-52f2-4363-b07f-0f67174826e0.mp4

#### Animations of new/removed nodes. ~(new)~ suppressed

~This is more of an unintended side effect but I'll play with this, we'll want to reduce transitions or turn off animation here I think.~ I turned off this interaction

https://user-images.githubusercontent.com/1270189/127550275-5a5158bf-ae68-4ed5-949f-52b8ac5c7f05.mp4

#### TODO:

- [x] Fix exit animation or remove the setting (each item needs a key)
- [x] Don't toggle opacity for initial sidebar toggle (and adding and removing nodes if possible).
- [x] Respects prefers reduce motion by turning off all animation
- [x] Remove the now unneeded leaf.js class
- [x] Performance audit
- [ ] Port or turn off layout when dragging

cc heads up @talldan since I know you're also looking at list view improvements

### CODE REVIEW

**Comment by gwwar** [comment]
To help keep scope down, I think we'll want to tackle drag refactoring in another PR. 

The main blocker I'm seeing at the moment is that typing speed is quite affected with the persistent list view open. Going to profile a bit to see if I spot anything.

**Comment by gwwar** [comment]
I ended up using memo on the ListViewSidebar to avoid the performance hit while typing. Previously I was seeing ~100ms on keypress vs 30-40ms. I haven't noticed any broken functionality so far (most child components appear to be driven from our data stores) but folks are welcome to try and break this branch.

As a reminder, we should memo carefully, but I do think this is a good candidate since it renders often (on every keypress, re-renders with the same props, and is medium sized (on my machine it takes around 50ms to resolve).

I'll focus on tidying up animations next week.

**Comment by jasmussen** [comment]
This is just beautiful, thanks so much for tackling animation with such care! Here's a "before":

before

Here's what I see in this branch:

after

Just lovely. Specifically it becomes very clear here how framer treats the animation as a whole sequence of events where you scrub forwards and backwards on a timeline, as opposed to much CSS animation which is often bluntly toggled off or on. This is especially visible when you expand a node, then quickly collapse the group again before the animation has finished. This is great and really speaks to how animation can help reinforce points of origins and destinations in the user experience, rather than just be decorative. 

It also adheres to the most important rules of thumb I have for animation (many of which I compiled after listening to [this wonderful podcast](https://motionandmeaning.io/)):

- Animations should nearly always be _fast_, so it doesn't make the experience feel slow. 
- Animations should not be blocking: you should never have to wait for an animation to finish in order to do something.
- As a baseline: animations should all respect the "prefers reduced motion". 

If those rules of thumbs are met, I find that there's almost no aspect of an interface that can't benefit from well-done animation. Everything from icons that animate (such as a check drawing itself when you click a checkbox) to live feedback in the canvas when hovering or moving. When done well, animation like this can help reinforces the behavior of elements, can give feedback on success or failure, and ultimately help orient you almost in a way similar to how a focus style can help you find your place.

One question: when I open the panel initially, items fade in. I get the feeling that we get that fade "for free", as it's part of the lifycle of the animation. Is that something we can turn off somewhat easily, though? If we can, that would make it consistent with other panels that open, whose content also doesn't fade in. Fading on its own doesn't reinforce points of origin or destinations of items in the same way as motion does (#33132 is a great example of how replacing a fade with motion helps indicate what's about to happen), so I tend to be a little more sparing with the usage.

Really fantastic work, thank you!

**Comment by gwwar** [comment]
> Is that something we can turn off somewhat easily, though? 

Yes, we can turn it off. It's defined here:

https://github.com/WordPress/gutenberg/pull/33765/files#diff-87d2159ad7cb10761b54a0975e21535c674d6a18b1f4c445182d4a6e09fa8fe8R11-R21

🤔 Normally I'd simply animate height from '0' to 'auto'. One thing I'm running into is that table rows treat the CSS height property as a min-height, which makes animating this a little interesting. I'll play around with this a bit more.

**Comment by jasmussen** [comment]
> 🤔 Normally I'd simply animate height from '0' to 'auto'. One thing I'm running into is that table rows treat the CSS height property as a min-height, which makes animating this a little interesting. I'll play around with this a bit more.

This rings a bell for me for basic CSS animation also, animating from nothing to the intrinsic height. From what I recall the trick I've used in the past was to animate the `max-height` instead of the `height` (keep that at `auto`), and then animate to a `max-height` that's going to be larger than the item will ever get.

**Comment by gwwar** [comment]
Tables are built to take into account it's cell dimensions. Some options that could work:

1.  Animate height on the individual cells (not my first choice since it adds complexity)
2. Temporarily z-index on a layer lower than the parent branch and translate in the row(s)
3. Animate scaleY, (though we'd need to fudge the content say opacity fade in or a placeholder).

I'll circle back to this, after I try and sort out #33717

**Comment by gwwar** [comment]
Okay in https://github.com/WordPress/gutenberg/pull/33765/commits/b5c7b46ccae50cbafcd78034f7b84aaa397090f6 I went ahead and did a few things.

- Removed the animation exit prop since it wasn't firing and didn't look necessary for this interaction.
- Updated ListView so that the mount animation only fires when we toggle the expand. (This removes the fade in on sidebar open + animations when new blocks are inserted when typing). Making sure this happens is a little more complex, since when we toggle close a branch I do want hidden branches to not be rendered in DOM. (If branches are otherwise hidden but present in DOM, avoiding an animation on mount would simply be `initial = { false }`.

Since this component is built with tables, animating height is going to be annoying (since we end up needing to either scale the row or modify height on child cells). This is why I keep the opacity fade in effect for expand. This helps soften things as elements render in, and other existing branches move down.

**Comment by gwwar** [comment]
Drag explorations are getting pretty long here so I'll continue with that in https://github.com/WordPress/gutenberg/pull/34022, and drop the experimental changes on this branch.

**Comment by gwwar** [comment]
🤔  I played around a bit with disabling animations while dragging to avoid the slowdown, it doesn't feel quite right / is a bit tricky to get state right.

**Comment by jasmussen** [comment]
Even if it's still a work in progress, the work you're doing here is amazing. This is what I see:

this

It feels like the current behavior very loyally mimics the in-canvas behavior:

- Collapse into a chip
- Get "pulled out" of the flow

As is also implied in https://github.com/WordPress/gutenberg/pull/33950, this is a bit of a legacy behavior that, longer term, isn't necessarily what we want. That is, collapsing to a chip could still be necessary in the canvas itself when dragging very big items — but especially here in the list view, the value of collapsing to a chip is reduced. Which suggests that the dragging could be more _instant_/live. 

That might also be a mammoth task so I'm not necessarily suggesting that's what it has to be — even what's in this branch now is a _vast_ improvement. Only clarifying so as to not limit your explorations here ✨

**Comment by gwwar** [comment]
closing in favor of https://github.com/WordPress/gutenberg/pull/34022

**Pull request closed without merging**
