### PR TITLE
Update versions in WP for 6.4

### PR DESCRIPTION
**Pull request by annezazu**
Quick update to the Versions in WP doc for 6.4 with beta 1 out in the world.

### CODE REVIEW

**Review by ndiego — APPROVED** [review]
LGTM! 💪

**Comment by alexstine** [comment]
You know its beta time, E2E tests failing for no reason at all. 😆

**Review by aristath — APPROVED** [review]

**Comment by aristath** [comment]
The failing test is not related to this PR.
I'll go ahead and merge it manually 👍

**Comment by annezazu** [comment]
Thank you!

**Pull request merged**
