### PR TITLE
Make help text more in line with other help texts

### PR DESCRIPTION
**Pull request by dimadin**
This PR changes one help text string: it moves "sorry" to the start of the string, and it removes exclamation mark from the end.

### CODE REVIEW

**Comment by kristastevens** [comment]
Hello -- thanks for the copy review ping! Can I see the original and proposed versions of the text?

**Comment by Soean** [comment]
If you click on [files changed](https://github.com/WordPress/gutenberg/pull/11068/files), you see the versions in a diff.

Here they are:
Old: `Previews for this are unavailable in the editor, sorry!`
New: `Sorry, previews for this are unavailable in the editor.`

**Comment by kristastevens** [comment]
Thanks for the GitHub education! 

I'd go with: 

> Sorry, a preview is unavailable in the editor.

**Comment by dimadin** [comment]
Two notes:
- Other similar strings in both WordPress core and Gutenberg start with "Sorry," and end in full stop. This is why I reported this string.
- It might be valuable to know context in which this string shows up: it's in Embed block when user is trying to embed content from a site that is blacklisted from having embed previews (correct me if I'm wrong).

**Comment by gziolo** [comment]
@kristastevens, I agree with @dimadin that it needs to be more specific given that it's directly related to embeds.

**Comment by notnownikki** [comment]
How about:

> Sorry, we cannot preview this embedded content in the editor.

**Comment by kristastevens** [comment]
@gziolo, I think @notnownikki makes a great suggestion: 

> Sorry, we cannot preview this embedded content in the editor.

**Comment by mcsf** [comment]
@dimadin, sounds like we have a winner with that last iteration ("Sorry, we cannot preview this embedded content in the editor."). What's the status of this PR?

**Review by gziolo — APPROVED** [review]
I updated the copy with the latest suggestion 👍

**Review by tofumatt — APPROVED** [review]
I dig it 😄

Restarted the buggy tests and they passed.

**Pull request merged**
