### PR TITLE
GitHub Actions: Build Plugin zip, create release draft, attach zip

### PR DESCRIPTION
**Pull request by ockham**
# Description
First stab at writing a GitHub action to build Gutenberg upon creating a tag that starts with `v`, and creating a draft release with the build attached to it.

Based on [`build-plugin-zip.sh`](https://github.com/WordPress/gutenberg/blob/b44807452232cd681d219e54164c57398ab9064b/bin/build-plugin-zip.sh).

Using https://github.com/actions/create-release and https://github.com/actions/upload-release-asset.

## How has this been tested?

- Make sure you have your own fork of the Gutenberg repo, and that you've added it locally as a remote (E.g. `git remote add ockham git@github.com:ockham/gutenberg.git` if your GH username is `ockham` :slightly_smiling_face: ).
- Check out this PR's branch, and push the contents to your fork's `master` branch (you can reset later):
```
git push ockham add/build-github-action:master
```
- Add a version tag (must start with `v`), e.g. `git tag v9.2.0-rc.1`.
- Push that tag to your fork: `git push --tags ockham`.
- Go to the 'Actions' tab of your fork's GH page (e.g. https://github.com/ockham/gutenberg/actions).
- Locate the action whose description reads "Build Gutenberg and upload to Draft Release", and click on it.
- It should take less than 10 minutes to build the plugin zip. You can watch that page as the action progresses.
- Eventually, a release draft will be created, and the plugin zip will be attached. You'll find it under 'Releases' (e.g. https://github.com/ockham/gutenberg/releases)

(I've used my Gutenberg fork as an example, you can see the relevant action and release drafts from previous runs there.)

## Types of changes
Build tools automation

## TODO

- [ ] Add npm module cache. See e.g. [unit test action](https://github.com/WordPress/gutenberg/blob/95188199c8b8045322d7f75a2666d47ea6504ad2/.github/workflows/unit-test.yml#L21-L32)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

/cc @sirreal @gziolo

### CODE REVIEW

**Comment by gziolo** [comment]
@youknowriad is the best person to share feedback and follow along 😄

**Comment by talldan** [comment]
> I think the only way to test is to merge this, and then create a tag starting in v. Since the action only creates a release draft, that shouldn't be too much of a problem, since we can delete it after.

I think you could probably test it on a fork.

**Comment by youknowriad** [comment]
How is this different from our release script and what benefit do we get compared to it?

**Comment by ockham** [comment]
> > I think the only way to test is to merge this, and then create a tag starting in v. Since the action only creates a release draft, that shouldn't be too much of a problem, since we can delete it after.
> 
> I think you could probably test it on a fork.

Ah, good thinking! I might give that a try :slightly_smiling_face:

**Comment by youknowriad** [comment]
No, I meant compared to our current `./bin/commender.js rc`/`./bin/commender.js stable`, that's a script that bumbs the Gutenberg version in the required files, tag the release, create the zip, uploads the Gutenberg release and changelog and also handle the SVN releasing.

I'm really glad that you're putting effort to try to help them automate things and I'd love to see more automation in flows we didn't explore yet but It does feel like we're already pretty well covered with the release tool. https://github.com/WordPress/gutenberg/blob/master/docs/contributors/release.md

**Comment by ockham** [comment]
Pushing the code from this branch to my fork of the repo, I finally got this to work :tada: 

Did the following locally:

```
git tag v9.3.0-rc.1
git push --tags ockham
```

This triggered the [action](https://github.com/ockham/gutenberg/runs/1255444351?check_suite_focus=true) to build a Gutenberg [zip](https://github.com/ockham/gutenberg/releases/download/untagged-b5af3b43e955452fc63e/gutenberg.zip), create a [Release Draft](https://github.com/ockham/gutenberg/releases/tag/untagged-b5af3b43e955452fc63e), and attach the zip to it in under 10 minutes.

I now have to check if the zip is complete and works.

**Comment by ockham** [comment]
> I now have to check if the zip is complete and works.

The `vendor/` folder (and contents) is missing, seems like the `$vendor_scripts` var isn't set properly.

**Comment by ockham** [comment]
I've worked a bit more on this and tested it on my repo fork (thanks @talldan for the suggestion)! I've updated the PR desc with reproducible testing instructions. This seems to be working quite smoothely now -- please give it a try!

Would we be open to reconsider merging this PR? I think we could still keep the `./bin/commander.js` command for branching/tagging etc, but could offload the actual plugin build to this GH action. Maybe only for the RC at first, and later also for stable versions -- we can add another GH action that uploads the plugin to the WP.org SVN repo upon publishing a stable version (there's some [precedent](https://github.com/10up/action-wordpress-plugin-deploy) for this).

Overall, I hope that eventually we'd end up with a setup where releasing the plugin doesn't require cloning the GB repo into a temporary directory plus the SVN plugin repo onto one's own machine, but to offload all that to GH. I hope that this will help make the release process (feel) more lightweight, and potentially allow us doing more RCs (and possibly nightlies, at some point) to aid with testing on a variety of setups (e.g. big multi-user WP instances) prior to releases.

**Comment by youknowriad** [comment]
> Overall, I hope that eventually we'd end up with a setup where releasing the plugin doesn't require cloning the GB repo into a temporary directory plus the SVN plugin repo onto one's own machine, but to offload all that to GH.

I think that's a great goal but for me it feels like we're recreating the script why not just provide a `-no-interactive` option in `bin/plugin/cli.js` and just run it as a github action?

**Comment by ockham** [comment]
> > Overall, I hope that eventually we'd end up with a setup where releasing the plugin doesn't require cloning the GB repo into a temporary directory plus the SVN plugin repo onto one's own machine, but to offload all that to GH.
> 
> I think that's a great goal but for me it feels like we're recreating the script why not just provide a `-no-interactive` option in `bin/plugin/cli.js` and just run it as a github action?

Thanks Riad!

:thinking: It seemed to make sense to me to have the build plugin action only create the zip and attach it to a _draft_ release, but wait for the user to actually publish -- to give the user a final chance to revise the release. (I'd probably remove the CLI step where the user is supposed to fill in the changelog -- they can do that in the GH release UI instead; mostly so we don't duplicate interactive steps.) I'd then couple the SVN upload to the publishing of the GH release, i.e. when things are 'final'. To the user, that should all feel fairly transparent and consistent: they'll first get a draft release to fill in and publish, and once that's done, they'll automatically get the plugin uploaded to SVN.

Curious to hear your thoughts!

**Comment by ockham** [comment]
> it feels like we're recreating the script why not just provide a `-no-interactive` option in `bin/plugin/cli.js` and just run it as a github action?

One more note here, I think we have somewhat of a separation of concerns already that will apply quite well to what we're doing here:

- The GH action I'm adding in this PR only builds the zip -- it corresponds directly to `build-plugin-zip.sh` (which it invokes) rather than any of the `plugin/cli.js` commands (since it doesn't come with the repo cloning overhead, and doesn't involve any of the branching/tagging.
- The GH action I'm thinking of for when a release is published will correspond to `runSvnRepositoryCheckoutStep` and `runUpdateTrunkContentStep`.
- The remainder of the script will be mostly about the branching/tagging/versioning, up until the point where the newly created tag is pushed to the repo, from where the action will take over.

**Comment by youknowriad** [comment]
For me, I still feel these intermediary steps will just add friction over what we currently have. Meaning, we should click a single "button" to release everything and I shouldn't be asking myself if I should create a tag from master or a tag from a release branch or anything. I can just say "release major", "release patch" and that should be enough.

**Comment by ockham** [comment]
> For me, I still feel these intermediary steps will just add friction over what we currently have. Meaning, we should click a single "button" to release everything and I shouldn't be asking myself if I should create a tag from master or a tag from a release branch or anything. I can just say "release major", "release patch" and that should be enough.

Not sure I'm following :thinking: That part of the script could stay the same, you could continue to `./bin/commander.js rc` and `./bin/commander.js stable`; it's just that once the tag is created and pushed (by that script!), the zip is built by GH rather than locally. One of the benefits would be that the user can then return to work on other things in their locally checked out repo more quickly, rather than to wait for the build to finish.

The goal is definitely not to add friction here :100: 

Hope I've been reading you correctly, please LMK if I haven't!

**Comment by youknowriad** [comment]
> Not sure I'm following 🤔 That part of the script could stay the same, you could continue to ./bin/commander.js rc and ./bin/commander.js stable; it's just that once the tag is created and pushed (by that script!), the zip is built by GH rather than locally. 

There's something I'm missing here, the only places where we create tags is in these commands, we don't do that manually and these commands do need the zip as well for the SVN part. so I'm not really sure it makes sense to separate these two flows?

**Comment by ockham** [comment]
> > Not sure I'm following thinking That part of the script could stay the same, you could continue to ./bin/commander.js rc and ./bin/commander.js stable; it's just that once the tag is created and pushed (by that script!), the zip is built by GH rather than locally.
> 
> There's something I'm missing here, the only places where we create tags is in these commands, we don't do that manually and these commands do need the zip as well for the SVN part. so I'm not really sure it makes sense to separate these two flows?

I think we're _almost_ on the same page:

- The `./bin/commander.js` commands can continue to create the tags and push them to GH. _(We'll remove the calls to building the ZIP and uploading it to SVN.)_
- The newly added tag triggers the GH action that builds the ZIP and creates the release draft.
- Once we press 'publish', another GH action (yet to be written) takes the ZIP asset from the release and uses it to upload those files to SVN.

The separation mostly results from the fact that we're adding the GH release in _draft_ state so the user can revise it prior to publishing. Overall, it seems to make sense to me to do that (it basically replaces the step where the user would otherwise enter the Chagelog on the CLI), and to couple the actual SVN release to the publishing of the GH one, but we can also keep everything in one monolithic flow.

Does that make sense? Have you tried the flow for yourself? (By simply creating a tag on a fork for now, see PR desc.) Maybe it helps illustrate things :blush: 

I can maybe remove the ZIP generation from `release.js` for RCs as part of this PR, and only run the action for RCs, to demonstrate the ultimate idea more closely :thinking:

**Comment by youknowriad** [comment]
> The ./bin/commander.js commands can continue to create the tags and push them to GH. (We'll remove the calls to building the ZIP and uploading it to SVN.)
> The newly added tag triggers the GH action that builds the ZIP and creates the release draft.
> Once we press 'publish', another GH action (yet to be written) takes the ZIP asset from the release and uses it to upload those files to SVN.

- Where is this publish button?
- How do you differentiate between release tags and lerna tags (ignore releases for these), also maybe mobile team has their own tags?

> (it basically replaces the step where the user would otherwise enter the Chagelog on the CLI),

How do you enter the changelog and how does it make its way into changelog.txt file?

> couple the actual SVN release to the publishing of the GH one, but we can also keep everything in one monolithic flow.

How is this coupling a bad thing? I have a hard time thinking of a use-case where you want a stable release on github but not the same one on SVN?

--- 
So this makes a one-step release, into a two-step: instead of running a script (on a github action or locally or triggered by a deploy page somewhere), we run a script locally + wait for github action to finish + enter the changelog on the release page + click a button to actually publish. Isn't that more friction?

I guess the value in the proposal is potentially to have a place where to enter the changelog async? Could this be just a textarea on the deploy page or an argument for the deploy command. In all cases, the changelog is required before the release.

**Comment by youknowriad** [comment]
I wanted to mention that I wrote the release tool as it stands so these are my ideas/principles there which can lead to bias. More opinions here is appreciated @WordPress/gutenberg-core

**Comment by ockham** [comment]
> > The ./bin/commander.js commands can continue to create the tags and push them to GH. (We'll remove the calls to building the ZIP and uploading it to SVN.)
> > The newly added tag triggers the GH action that builds the ZIP and creates the release draft.
> > Once we press 'publish', another GH action (yet to be written) takes the ZIP asset from the release and uses it to upload those files to SVN.
> 
> * Where is this publish button?

At `https://github.com/WordPress/gutenberg/releases/edit/<release>` -- see e.g. https://github.com/WordPress/gutenberg/releases/edit/v9.1.1. That one's already published, so you only get 'Update release' there. If it was in draft state, it'd look like this ([this](https://github.com/ockham/gutenberg/releases/tag/untagged-b097408aeac2b9ff92ff) was created by the GH Action from this PR on my fork):

image

> * How do you differentiate between release tags and lerna tags (ignore releases for these), also maybe mobile team has their own tags?

It's easy to tell the action [only to run for tags that satisfy a certain criterion](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-including-branches-and-tags). I'm using "starts with a `v`) here: https://github.com/WordPress/gutenberg/pull/19626/files#diff-4d14704b6b88fb06db888f96c03a8e9b3a5e07a4ee566d97d4111b2c05210e84R1-R5
 
> > (it basically replaces the step where the user would otherwise enter the Chagelog on the CLI),
> 
> How do you enter the changelog and how does it make its way into changelog.txt file?

Enter it into the release draft as seen in the above sceenshot. I admittedly forgot about changelog.txt. If we need this file updated in the repo and included in the ZIP, we probably have to keep the 'enter changelog' step in the CLI after all :grimacing:

> > couple the actual SVN release to the publishing of the GH one, but we can also keep everything in one monolithic flow.
> 
> How is this coupling a bad thing? I have a hard time thinking of a use-case where you want a stable release on github but not the same one on SVN?

Oh, I agree it's a good thing -- I'm definitely _for_ releasing it too SVN whenever releasing it to GH. My suggestion was merely to have that release draft step in between, and only publish to SVN when that draft is published (again, see above screenshot).

> So this makes a one-step release, into a two-step: instead of running a script (on a github action or locally or triggered by a deploy page somewhere), we run a script locally + wait for github action to finish + enter the changelog on the release page + click a button to actually publish. Isn't that more friction?

Under my original assumption (that we can enter the Changelog into the release draft UI), I think it wouldn't have added friction, as we'd have replaced a CLI prompt with a UI one. Since that might not be viable, then yep, we'd enter an additional step that might not make much sense.

But TBH, in the interest in moving this forward, I don't think it's worth spending too much time on this decision -- we can skip the release draft step to keep the flow _entirely_ identical to now, except for offloading the ZIP building and SVN upload to GH. I was merely thinking that
- it's nice to have a UI to do some final revising right before "pulling the trigger", and even nicer that it's GH's own, and 
- it'd be easier to implement both parts piecemeal (in separate actions and PRs). We can however probably do it all in one go.

> I guess the value in the proposal is potentially to have a place where to enter the changelog async? Could this be just a textarea on the deploy page or an argument for the deploy command. In all cases, the changelog is required before the release.

What deploy page? :thinking: Again, I don't want to block this based on how to enter the changelog -- we can keep it in the CLI for now.

**Comment by ockham** [comment]
The GH Action is currently failing (during the new cache step), apparently because of https://github.com/WordPress/gutenberg/pull/26439#issuecomment-716298398 :thinking:

**Comment by fullofcaffeine** [comment]
This seems to work well 👍🏻 ✅ 

Action output: https://github.com/fullofcaffeine/gutenberg/runs/1330020144
Release: https://github.com/fullofcaffeine/gutenberg/releases/

I can't approve but I'll be following the discussion. It's not entirely clear to me what are the main benefits over the CLI approach, other than moving the UI to a GUI :) but I haven't read all the text yet.

**Comment by bph** [comment]
I have been working on the other end of a similar process with the goal to release a daily Gutenberg 
[Zip form Master](https://gutenbergtimes.com/need-a-zip-from-master/)

Now @ockham,  your PR helps with automating the build process and push it to my fork. Thank you!

**Comment by ockham** [comment]
Superseded by #27488.

**Pull request closed without merging**
