### PR TITLE
Try Site Editor panel metrics

### LINKED ISSUE #51581: Browse Mode: Ellipsis icons misaligned:
## What problem does this address?
The ellipsis icons here are not aligned
Screenshot 2023-06-16 at 14 03 21

## What is your proposed solution?
The list view can probably be made slightly wider so they are aligned.

### PR DESCRIPTION
**Pull request by richtabor**
## What?
General tweaks to adjusting metrics for the Site Editor panels. Was investigating https://github.com/WordPress/gutenberg/issues/51581 and decided to spin up a more holistic proposal that will also close #51581. 

Generally aligns icons a bit better on the right, and ensures MenuItem spacing is equal on both sides. 

## Testing Instructions
1. Open the Site Editor.
2. View updated metrics.

### Before 
before

### After 

after

### CODE REVIEW

**Comment by jameskoster** [comment]
These changes seem reasonable to me. I particularly appreciate the equal left/right padding 😌

Just a couple of small observations... The panel title and site title are ever-so-slightly out of alignment, is it worth finessing that?

Screenshot 2023-06-19 at 14 28 14

When menu items don't have an icon, they seem to hang too far over on the left:

Screenshot 2023-06-19 at 14 29 26

**Comment by richtabor** [comment]
@jameskoster I can give it another run tomorrow, but feel free to push to the branch if you’d like to have at it.

**Review by jameskoster — APPROVED** [review]
I pushed the suggested adjustments. The changes seem worth merging to me. We can continue to polish as needed.

**Comment by jameskoster** [comment]
@richtabor how do you feel about merging this one?

**Comment by jasmussen** [comment]
Restarted the failing tests in case they were flaky.

**Pull request closed without merging**
