### PR TITLE
Add more statuses to default page views

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Adds views for managing Private, Scheduled, and Pending pages. 

## Why?
Drafts and Trash are surfaced, it seems reasonable to include other statuses, they're particularly useful on busier sites. 

## Testing Instructions
1. In the Site editor navigate to Pages > Manage all pages
2. Observe the new view options in the side bar
3. Ensure they all return the pages as expected

| Before | After |
| --- | --- |
| Screenshot 2023-11-15 at 15 20 36 | Screenshot 2023-11-15 at 15 41 30 |

### CODE REVIEW

**Comment by jasmussen** [comment]
Is it possible for these added views to be visible only if there are posts in them? If not, should it be? Perhaps related, have there been explorations in showing a "post count" for either of those filters?

**Comment by jameskoster** [comment]
I don't mind empty views being accessible, it solves a potential "Where have all my drafts gone?!" problem, especially if there's a count like you suggest. That said, last I checked adding counts wasn't trivial, cc @ntsekouras for thoughts on that.

Separately we should design nicer empty (and loading) states. It's on the [todo](https://github.com/WordPress/gutenberg/issues/53233).

**Comment by ntsekouras** [comment]
That's actually related to [this comment:](https://github.com/WordPress/gutenberg/issues/56204#issuecomment-1814525946)

>I agree with Riad and personally I'm not seeing much value to these drafts or trash views. Like Riad mentions, even with a custom created view, the name could be misleading after saving some more changes in the future.

>Maybe we don't need these views at all and only provide the all view, in conjunction with the ability for users to create custom views. For plugins maybe we could provide a way to register a view that users cannot edit at all - a fixed specialized view.

Any thoughts?

Regarding the count, it has some nuances that it would be better to handle a bit later, where we would have done more work/explorations about the proper APIs.

**Comment by jameskoster** [comment]
I left a comment in that issue too, it might be better to close this PR and discuss there. 

Conceptually default views seem fairly practical to me, but I appreciate the UX around editing / saving them is trickier than custom views. So alternatively I'm wondering if the default views (as they appear here) could be installed as custom views when wp is itself installed (or updated). From there they'd behave just like any other custom view, IE can be edited, renamed, deleted, and so on.

**Comment by carolinan** [comment]
I think future (scheduled) are missing?

**Comment by jameskoster** [comment]
Closing for now.

**Pull request closed without merging**
