### PR TITLE
Fix `ToggleGroupControlOption` not passing `ref` to the underlying element

### PR DESCRIPTION
**Pull request by diegohaz**
This PR is a small fix to avoid future issues.

The internal `ToggleGroupControlButton` component doesn't accept a `ref` prop. Instead, it expects to receive `forwardedRef`:
https://github.com/WordPress/gutenberg/blob/17bb52bab18046ee13cf7b4bca5d805b3e8e8557/packages/components/src/toggle-group-control/toggle-group-control-button.tsx#L23

Because of this, passing `ref` to `ToggleGroupControlOption` wouldn't work.

### CODE REVIEW

**Review by ntsekouras — APPROVED** [review]
Thanks for the fix!

**Comment by ciampo** [comment]
Out of curiosity, would using `React.forwardRef` be a cleaner solution instead of having a prop called `forwardedRef`?

**Comment by diegohaz** [comment]
Since this component is not exposed, I'm okay with the `forwardedRef` prop. But we can refactor it so all the logic is inside `ToggleGroupControlOption`. And then delete `ToggleGroupControlButton` to simplify the code.

**Comment by ciampo** [comment]
> Since this component is not exposed, I'm okay with the `forwardedRef` prop. But we can refactor it so all the logic is inside `ToggleGroupControlOption`. And then delete `ToggleGroupControlButton` to simplify the code.

Makes sense.

We should merge this PR to get the fix in the codebase and then open a follow-up PR to merge `ToggleGroupControlButton` into `ToggleGroupControlOption` (let me know if you'd prefer to work on it directly, otherwise I can work on it myself).

**Comment by ciampo** [comment]
> We should merge this PR to get the fix in the codebase and then open a follow-up PR to merge ToggleGroupControlButton into ToggleGroupControlOption 

I will take care of this and open a PR soon 

_Update: Opened #35600_

**Pull request merged**
