### PR TITLE
Remove the list view button from the navigation block

### LINKED ISSUE #47007: Improve accessible text of Open Navigation List View button
As reported in https://github.com/WordPress/gutenberg/issues/46939#issuecomment-1374652632, currently the text of the button in block toolbar which opens the Offcanvas List View for the Nav block is not descriptive enough.

Consider a more descriptive name for the feature and utilise this on the button.

cc @WordPress/gutenberg-design for input here.

### PR DESCRIPTION
**Pull request by draganescu**
## What?

Closes https://github.com/WordPress/gutenberg/issues/47007, https://github.com/WordPress/gutenberg/issues/47008, https://github.com/WordPress/gutenberg/issues/47009 

The "Test a new "off canvas" editor for navigation block using the block inspector and a tree view of the current menu" experiment introduces a button in the navigation block's toolbar to open the settings sidebar.

The goal of the button is to serve as a way for users to discover there is a tree view of their menu in the settings sidebar.

This PR removes it.

## Why?

[Previously](https://github.com/WordPress/gutenberg/issues/42257#issuecomment-1316833855,) the button had another incarnation which was transformed in #46335 to the current state.

The current state has some issues:

- The button is unique to the navigation block and the action opens the settings sidebar. There is a button to open settings.
- It does not function as a sort of shortcut since it should be a toggle.
- Do we want to couple the block to the interface package?
- Do we need to toggle it on and off based on display state of the settings sidebar?
- Do we need to toggle it off if the new tabs of the inspector are set to something other than list?
- We can't even [open the list view directly](https://github.com/WordPress/gutenberg/pull/46907) yet.

## How?

It undoes the elements introduced in  #46335

## Testing Instructions

0. Have the  "Test a new "off canvas" editor for navigation block using the block inspector and a tree view of the current menu" experiment enabled
1. Insert a navigation block
2. Create a menu or select one
3. Notice the block toolbar does not have [this](https://user-images.githubusercontent.com/846565/211553432-ef13192f-0f48-41b9-a525-80fdd9517a0e.png) button

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast 

N/A

### CODE REVIEW

**Comment by jameskoster** [comment]
The reasoning seems solid to me, and I think we can lose the button. At this point it does feel superfluous.

However this change will create a "who moved my cheese?" moment for existing users (and probably require documentation updates). Are there any plans to guide users around once off-canvas navigation graduates from experiment status?

**Comment by carolinan** [comment]
The button was only added in December, in 14.8 correct? I think the potential negative user impact would be low because of the short time?

**Comment by jameskoster** [comment]
In that case ignore me, I thought it had been there much longer.

**Review by scruffian — APPROVED** [review]
LGTM

**Pull request merged**
