### PR TITLE
Cover Block: Allow alt text

### LINKED ISSUE #30505: Cover Block: Allow alt text for images
Cover block markup includes an attribute for alt text, but there's no place to edit this in the block UI. If you attempt to edit this via the block markup, the editor throws an invalid content error. 

Cover images are often decorative (and thus don't technically need alt text), but we can't assume that'll be the case all the time. Gutenberg should allow users to enter alt text here when it's needed. 

## Screenshots: 

Example with default Markup:

```
<!-- wp:cover {"url":"https://cldup.com/y7iKtyPFbw.jpg","id":2651} -->
<div class="wp-block-cover has-background-dim"><img class="wp-block-cover__image-background wp-image-2651" alt="" src="https://cldup.com/y7iKtyPFbw.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->
```

Screen Shot 2021-04-05 at 10 24 13 AM

Example markup with alt text: 

```
<!-- wp:cover {"url":"https://cldup.com/y7iKtyPFbw.jpg","id":2651} -->
<div class="wp-block-cover has-background-dim"><img class="wp-block-cover__image-background wp-image-2651" alt="Photo of mountains" src="https://cldup.com/y7iKtyPFbw.jpg" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","fontSize":"large"} -->
<p class="has-text-align-center has-large-font-size"></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->
```

Screen Shot 2021-04-05 at 10 24 39 AM

### PR DESCRIPTION
**Pull request by Mamaduka**
## Description
Adds setting to provide alt text when image element is used for a Cover block.

I don't think we need deprecation for this feature since we already had an empty alt text attribute for image elements.

Fixes #30505.

## How has this been tested?
1. Create a post.
2. Add Cover block.
3. Select an image.
4. Textarea for the alt text should be visible in the sidebar.

## Screenshots 
CleanShot 2021-07-06 at 20 31 00

## Types of changes
New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
@kjellr, I think PR is ready for testing.

I need to update fixtures for the integration test, but this isn't a blocker for manul tests.

**Comment by Mamaduka** [comment]
I've regenerated fixtures using this [guide](https://github.com/wordpress/gutenberg/blob/HEAD/packages/e2e-tests/fixtures/blocks/README.md#updating-fixtures). After manual review, I think regenerated ones are correct.

**Review by kjellr — COMMENTED** [review]
This works great in my testing. I tried the sample text from the original issue, and also tried adding a few images and manually adding alt text using the new field. The field properly disappears when the block has no image, or when it is using video as media instead. Nice work! 

I'll let someone else review the code, but functionally this seems good to go.

**Comment by Mamaduka** [comment]
Hi, @ntsekouras

I would love to get your opinion if this PR needs deprecation. We already had the `alt` empty attribute in the markup; this PR just adds the ability to change it.

**Review by ntsekouras — COMMENTED** [review]
Thanks for working on this George! 👍 

Code looks good - just rebase to resolve conflicts.

We don't need a deprecation in this case.

**Comment by Mamaduka** [comment]
Thanks for having a look, Nik.

Rebased and resolved conflicts. Waiting for checks to pass 🤞

**Review by ntsekouras — APPROVED** [review]
Thanks! 👍

**Comment by allisonplus** [comment]
@Mamaduka --Do you know if there is there a timeline for when this will be merged into a core release?

**Comment by ntsekouras** [comment]
Hey @allisonplus - since this is an enhancement, it will be included in `5.9`.

**Comment by MaybeThisIsRu** [comment]
Just wanted to drop in and say thanks to everyone for raising and fixing this! :) Waiting for 5.9 now.

**Comment by kerri-hicks** [comment]
This change works great when using default block options, but doesn't add the alt text field if the "Fixed Background" option or "Repeated Background" option is toggled on. See [#30505](https://github.com/WordPress/gutenberg/issues/30505). It looks like there's a PR for a fix pending. [#50990 ](https://github.com/WordPress/gutenberg/pull/50990)

**Pull request merged**
