### PR TITLE
Try toggle instead of dropdown to show stylebook.

### PR DESCRIPTION
**Pull request by tellthemachines**
## What?

Tiny PR to test replacing the dropdown that allows switching to the stylebook in the styles screen with a simple toggle, because a dropdown feels like overkill when there are only two options 😅 

To test, activate a block theme and go to the Styles section in the site editor.

## Screenshots or screencast 

|Before|After|
|-|-|
|Screenshot 2024-12-11 at 2 43 47 pm|Screenshot 2024-12-11 at 2 44 13 pm|

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
LGTM and works well in my testing. 

Makes sense to minimize the code and effort for the user (1 vs 2 clicks).

I'll lean on @jameskoster a bit for final review, as he was involved in the [initial effort](https://github.com/WordPress/gutenberg/pull/65619#issuecomment-2401963293)

**Comment by jasmussen** [comment]
I think this toggle is good, but it's not clear that specifically the _toggle control_ is the right one, and the label "Show Style Book" is a bit long.  One instinct is to use this icon:
Screenshot 2024-12-11 at 08 55 10

This is mainly to make it similar to what's in the in-editor global styles panel now. But I also recognize the icon may not be ideal. Could it be the same type of toggle button, just with a text label that says "Style Book"?

**Comment by jameskoster** [comment]
The toggle control makes it feel like a setting, which doesn't quite capture the nature of this feature. 

I agree that reusing the existing toggle is probably the best approach, given it's familiarity. We can revisit the icon separately if needs be.

**Comment by tellthemachines** [comment]
Thanks for the feedback folks! I've updated to use a button with text in the latest commit:


Screenshot 2024-12-12 at 11 26 05 am


Screenshot 2024-12-12 at 11 26 11 am

**Comment by jameskoster** [comment]
Thanks for the adjustment. I think the idea was actually to use the same button we find in the Styles panel in the Editor, this one:

Screenshot 2024-12-12 at 10 52 15

What do you think?

**Comment by tellthemachines** [comment]
> I think the idea was actually to use the same button we find in the Styles panel in the Editor

I was going off Joen's comment above:

> But I also recognize the icon may not be ideal. Could it be the same type of toggle button, just with a text label that says "Style Book"?

I think that icon looks weird and I never understood why it stands for the style book, but I have a bad relationship with icons in general 😅 

Perhaps we can make it an icon by default and make sure it becomes a a text label if button text labels are enabled.

**Comment by tellthemachines** [comment]
> Perhaps we can make it an icon by default and make sure it becomes a a text label if button text labels are enabled.

Ok I've updated the PR with this!

**Comment by jameskoster** [comment]
Oh sorry, perhaps there's a crossed wire here :D 

I agree the icon isn't the best, and could be revisited. But I also think there's value in maintaining consistency between this styles panel and the one found in the editor. In other words; if we want a text button here, why not in the editor too?

That said if y'all prefer a text button I'm happy to defer, and apologies for the detour.

**Comment by jasmussen** [comment]
I think it's worth reaching consistency here first, supporting Jay's point, and then revisit the icon and behavior.

**Comment by jameskoster** [comment]
We can further discuss the button in https://github.com/WordPress/gutenberg/issues/67980.

**Comment by ramonjd** [comment]
I don't know what the stakes are here, but is it worth pausing this PR until we've reached a point of consistency in https://github.com/WordPress/gutenberg/issues/67980? 

Just my opinion:

Pros of what's presently in trunk:

- the drop down text describes the canvas state

Cons:

- it's currently a binary choice, almost on/off that doesn't warrant two clicks
- it's not aligned with the editor

On the general topic of alignment with the editor, there are efforts to bring revisions to the top-level:

- https://github.com/WordPress/gutenberg/pull/67660
- https://github.com/WordPress/gutenberg/pull/66476

The second PR, I think, proposes to relocate the revisions icon and make a text button in the styles panel in the editor. 

That will change the available realestate in the header as well.

**Comment by tellthemachines** [comment]
> I agree the icon isn't the best, and could be revisited. But I also think there's value in maintaining consistency between this styles panel and the one found in the editor. In other words; if we want a text button here, why not in the editor too?

> I don't know what the stakes are here, but is it worth pausing this PR until we've reached a point of consistency in https://github.com/WordPress/gutenberg/issues/67980?

the latest update in this PR makes the button consistent with the editor one. They are icons by default, and switch to text when the text labels preference is enabled.

Given this provides a UX improvement as it is, I believe we should merge it and then discuss iterating on the icon as a follow-up.

**Pull request merged**
