### PR TITLE
Fix font-family in WP 5.6

### LINKED ISSUE #29177: Noto Serif Font Missing in GB 10.0
## Description

When no editor style is defined, the default styling uses Noto Serif via Google. _However, the font is not included, and no attempt is made to load it_, so the browser falls back to Times New Roman

## Step-by-step reproduction instructions

On a site that uses the default block editor styling, install and activate the Gutenberg plugin, then create a post

## Expected behaviour

The text appears in the Noto Serif typeface as specified in the default stylesheet, or falls back to system fonts

Note that the problem is not that Noto Serif fails to load, it's that it is never attempted. There is no failed request, because it was never requested.

## Actual behaviour

The typeface is specified, but not present. The browser uses the default font instead ( Times New Roman ) of the system font stack

## Screenshots or screen recording (optional)

Screenshot 2021-02-20 at 13 48 11
Screenshot 2021-02-20 at 13 48 45

expected:
Screenshot 2021-03-02 at 13 24 58

actual:
Screenshot 2021-03-02 at 13 24 28

## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 10.0.0
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No, but I reproduced using multiple themes from different vendors

## Device information
- Device: MBP 13" Intel
- Operating system: MacOS 11.2 Big Sur
- Browser: Chrome 88

### PR DESCRIPTION
**Pull request by aristath**
## Description
Fixes #29177

This is an ugly hack to fix classic themes that don't add editor styles and run on a combination of WP 5.6 & Gutenberg 10+
See discussion on #29177 for details.

cc @tomjn 

## How has this been tested?
I created a new empty theme:
Inside wp-content I added a new `empty-theme` folder. Inside that folder I added an empty `inde.php` file and then a `style.css` file with these contents:
```css
/*
Theme Name: Empty
*/
```
Then I went to the editor in WP 5.6 and saw that it had `font-family: Noto Sans` for blocks.
After this PR, the font-family changed to the system defaults.

## Types of changes
Added a `gettext_with_context` filter targeting the font-family string and added a `version_compare` check so it only runs for < 5.6 WP versions.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thank you for fast work on this. 

It's a bit tricky to test, my local environment is on 5.8 nightly, so I can't reproduce the issue without downgrading first. Any shortcuts you know of?

Codewise, would love a sanity check from @gziolo for example.

Question: do we have a plan or idea for how to deprecate this code once it becomes unnecessary? Is there a policy in place for how long to carry this around?

**Comment by aristath** [comment]
> It's a bit tricky to test, my local environment is on 5.8 nightly, so I can't reproduce the issue without downgrading first. Any shortcuts you know of?

Unfortunately no... I use the beta-tester plugin so I'm able to simply roll-back to stable whenever I want by going to Dashboard > Updates

> Question: do we have a plan or idea for how to deprecate this code once it becomes unnecessary? Is there a policy in place for how long to carry this around?

Well... This code is only a temporary fix and shouldn't be necessary for more than a few months. It's safe to assume that people who run the latest Gutenberg version are also using the latest WP version. As far as I know there is no official policy

**Comment by jasmussen** [comment]
> Well... This code is only a temporary fix and shouldn't be necessary for more than a few months. 

👌 — if we then land this PR, we should ticket to remove it after a bit.

**Comment by bantilan** [comment]
Hi @aristath ,

My issue started after I updated to the latest version of Gutenberg, just today.. But prior to that, the last two update turns the font on my Gutenberg editor into "Segoe UI" instead of the original "Noto Serif".

I tried applying the hot fixes on gutenberg plugin, but still got the same "serif" font issue. 

I am using Gutenberg 10.2.1 with your hotfix and cleared wp super cache. Windows 10 Pro and WP 5.7 

I'd check the source and it still using the hard-coded family font style for .editor-styles-wrapper.

image

However, I've noticed that the noto-serif are still preloaded.
`<link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Noto+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">`

Here are the screenshot of the actual font issue:

image

Best Regards,

**Comment by bantilan** [comment]
Hi @aristath,

Also I tried removing the version check code and replacing "Noto Serif" to "serif" only.. still got the same problem.

Here are the JavaScript code triggering the serif font under `window._wpLoadBlockEditor = new Promise`.

https://d.gaming.ph/Kc9Vi5

image

**Comment by youknowriad** [comment]
Should we just close this PR as Gutenberg doesn't support WP < 5.6 anymore  and that the default font is not provided anymore anyway.

**Comment by tomjn** [comment]
As the original reporter, I'm happy for this and the issue to be closed. Thanks for the investigation and the work but upgrading to WordPress 5.7 is imo the canonical fix

**Comment by aristath** [comment]
I agree, closing this one. 👍

**Pull request closed without merging**
