### PR TITLE
Make appender fixed position to avoid jumps in the UI

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Alternative to #36037, which makes the appender fixed position in the top right corner of the nesting container, and to #36602 which simply hides it entirely but only in the site editor.

This variant is based on 36037, but keeps the plus black, and positions it in the bottom right corner. The idea with this one is to make the changes feel smaller — don't redesign the inserter, still keep it towards the end of the nesting container, but just take it out of the flow so it avoids layout shifts.

Post editor demo:

![post editor](https://user-images.githubusercontent.com/1204802/142399629-95f05de7-32ba-4d63-b9d8-1f22f0537330.gif)

Site editor demo:

![site editor](https://user-images.githubusercontent.com/1204802/142400218-1cbb7c11-023d-4107-a169-ad218da2b27a.gif)

## How has this been tested?

Test in the post editor with this demo content, ensure no regressions:

```
<!-- wp:paragraph -->
<p>Empty group, should show the big white full width plus:</p>
<!-- /wp:paragraph -->

<!-- wp:group -->
<div class="wp-block-group"></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with content:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:paragraph -->
<p>Paragraph 1</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Paragraph 2</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with empty paragraph inside, should show plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with single image inside, should show abs positioned plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"color":{"background":"#eaeced"}}} -->
<div class="wp-block-group has-background" style="background-color:#eaeced"><!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>A few buttons:</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button /-->

<!-- wp:button /--></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Many buttons:</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /-->

<!-- wp:button /--></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Empty cover with empty paragraph inside, paragraph should have black plus when selected:</p>
<!-- /wp:paragraph -->

<!-- wp:cover {"overlayColor":"secondary","minHeight":262,"minHeightUnit":"px","isDark":false} -->
<div class="wp-block-cover is-light" style="min-height:262px"><span aria-hidden="true" class="has-secondary-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Another cover:</p>
<!-- /wp:paragraph -->

<!-- wp:cover {"overlayColor":"primary"} -->
<div class="wp-block-cover"><span aria-hidden="true" class="has-primary-background-color has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:spacer {"height":50} -->
<div style="height:50px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Group with Cover inside, should have the plus abs positioned:</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"secondary"} -->
<div class="wp-block-group has-secondary-background-color has-background"><!-- wp:cover {"isDark":false} -->
<div class="wp-block-cover is-light"><span aria-hidden="true" class="has-background-dim-100 wp-block-cover__gradient-background has-background-dim"></span><div class="wp-block-cover__inner-container"></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group -->
```

Test in the site editor as well, with selecting nesting containers.


## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. <!-- Check code: `npm run lint`, Guidelines: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/ -->
- [x] My code follows the accessibility standards. <!-- Guidelines: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/accessibility/ -->
- [x] I've tested my changes with keyboard and screen readers. <!-- Instructions: https://github.com/WordPress/gutenberg/blob/HEAD/docs/contributors/accessibility-testing.md -->
- [x] My code has proper inline documentation. <!-- Guidelines: https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/ -->
- [x] I've included developer documentation if appropriate. <!-- Handbook: https://developer.wordpress.org/block-editor/ -->
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). <!-- React Native mobile Gutenberg guidelines: https://github.com/WordPress/gutenberg/blob/HEAD/docs/contributors/code/native-mobile.md -->

### CODE REVIEW

**Comment by ZebulanStanphill** [comment]
This is definitely my favorite approach of the three. Having the appender appear inside the container makes it a lot clearer that it inserts **into** the block rather than after.

The lack of appender when a single Button block is selected does feel off, but I'm not sure what the solution is there.

I'm noticing a bug with the current implementation, though. The appender is not appearing for Group blocks.
image

It is working fine with the Column and Buttons blocks:
image

I also noticed this issue with the Buttons in-between inserter not acting as expected, but I don't know if that's related to this PR. It does compound with the lack of appender to make inserting Button blocks feel noticeably less ergonomic.
image

If we later go the route of having appenders in the toolbar, perhaps one could be shown in the toolbar like so to provide a clear way of adding block to the parent of the current block:
image

**Comment by jasmussen** [comment]
Thanks for the review!

> I'm noticing a bug with the current implementation, though. The appender is not appearing for Group blocks.

Can you just verify if this isn't the same on trunk, though? Because I seem to recall a behavior where if you only have paragraphs inside a container, the appender isn't shown after either of them, whereas if you have, for example, an Image block inside, then it's shown. Definitely behavior to revisit in its own right, but just for the sake of this PR I think it's best to keep that separate.

> I also noticed this issue with the Buttons in-between inserter not acting as expected, but I don't know if that's related to this PR. It does compound with the lack of appender to make inserting Button blocks feel noticeably less ergonomic.

I've been having a fair amount of problems with the that inbetween inserter lately, and I'm hoping we can get some help to look at it, including #35536. I don't know how this PR would affect it, though, as it's separate markup outside the canvas (popover) and shouldn't be subject to the CSS I've got here. 

I would agree the ergonomics aren't ideal here, and even just making the inserter work before and after the last blocks ([illustrated here](https://github.com/WordPress/gutenberg/pull/36037#issuecomment-971610485)) could help bit.

**Comment by ZebulanStanphill** [comment]
> Thanks for the review!
> 
> > I'm noticing a bug with the current implementation, though. The appender is not appearing for Group blocks.
> 
> Can you just verify if this isn't the same on trunk, though? Because I seem to recall a behavior where if you only have paragraphs inside a container, the appender isn't shown after either of them, whereas if you have, for example, an Image block inside, then it's shown. Definitely behavior to revisit in its own right, but just for the sake of this PR I think it's best to keep that separate.

I specifically put a Heading block as the last block of the Group to see if that fixed the problem, but it didn't. I also just tried an Image block but it still didn't work.

Just tested `trunk` as well. The appender appears as expected when the Group is expected, so it's not a `trunk` issue.

> I would agree the ergonomics aren't ideal here, and even just making the inserter work before and after the last blocks ([illustrated here](https://github.com/WordPress/gutenberg/pull/36037#issuecomment-971610485)) could help bit.

Agreed.

**Comment by shaunandrews** [comment]
Really love the way this one is shaping up; Nice work.

Visually, my only niggle is the placement of the [ + ] button and how it _touches_ the focus outline of the block.

image

To me it feels unintentional, but I know the point is to visually _connect_ the add button to the focused block. I think it would feel better if there was a little space (I used 3px) around the button, and let the existing context (things like the focus outline and block toolbar) tie the button to the container.

image

I think a good companion PR to this one could explore more explanation for _where_ your block is going to be added. Right now, this PR can confuse adding blocks within deeply nested blocks, like a Buttons block within a Group block. Here's an example that uses a 3px blue "insertion guide" to help indicate where the new block will be added:

https://user-images.githubusercontent.com/191598/142495821-025adbc5-52b6-426f-9bcd-e6d1da518012.mp4

**Comment by shaunandrews** [comment]
> I specifically put a Heading block as the last block of the Group to see if that fixed the problem, but it didn't. I also just tried an Image block but it still didn't work.

With just a Paragraph and Heading block, I don't see a [ + ] for the Group — which I believe is intentional. When I add an Image block, then I do see the [ + ] button, which contradicts with your testing. I'm not sure what's going on, but I've tried it with more types of blocks and can reliably get the [ + ] when I expect it.

**Comment by ZebulanStanphill** [comment]
@shaunandrews I'm using https://gutenberg.run for testing. Maybe there's an issue caused by its WP environment being a bit out-of-date? It is running WP 5.7 with Twenty Twenty-One 1.2. Changing the theme to Twenty Twenty or Twenty Nineteen does not fix the issue. I just tested the branch again and I still can't see the appender in a Group:

image

There are no console errors.

Also, in `trunk`, the only block that has special appender behavior is the Paragraph. The appender still appears after Heading blocks. So if you're not seeing the appender in a Group when the last child is a Heading, that's technically a regression.

In the pictures you posted above, the heading is the first block, but whether the appender is shown only depends on what the last child block is.

**Comment by jasmussen** [comment]
I do see the appender after the heading:
Screenshot 2021-11-19 at 09 03 03

I'm investigating a few thigns and will try and address the feedback noted. Whether we're able to land this one or not, I'd like to shepard it along as best I can.

**Comment by jasmussen** [comment]
> Visually, my only niggle is the placement of the [ + ] button and how it touches the focus outline of the block.
Screenshot 2021-11-19 at 09 04 54

I do kind of like that it's _as much on the edge_ as it can be, meaning it covers as little as possible of the content inside. Also that it lines up below. But this is not a strong opinion, and I'd be happy to add a few pixels of spacing if need be. Let me address the other things and I'll come back to this one.

**Comment by jasmussen** [comment]
Alright, I've rebased and fixed an issue with the plus not appearing in some odd cases. Specifically it wasn't working inside navigation, which I've now fixed:
navigation and group

Shown here also the behavior that the appender for the _group_ will only show when the _group_ is selected, not for when content _inside_ is selected. This is based on [feedback here](https://github.com/WordPress/gutenberg/pull/36037#issuecomment-972776036), (and of the 3 commits to this branch, is defined by commits 2 and 3), and is mostly important for the site editor, where without it, you'd have this:



With the change to only show the plus for the selected container, it feels much more contextual:



It essentially leans into the idea that _we have too many plusses_ and we need to remove some of them. That also challenges a bit of muscle memory we've built up.

> To me it feels unintentional, but I know the point is to visually connect the add button to the focused block. I think it would feel better if there was a little space (I used 3px) around the button, and let the existing context (things like the focus outline and block toolbar) tie the button to the container.

I tried this, and despite my previous thought agree that it looks good in many cases. However then I realized that for really small containers, like Navigation, you'd end up with this:

Screenshot 2021-11-19 at 09 37 19

That's more of a critique of this button itself than anything, but it's the reason why I'm leaning towards leaving out that change for now.

Here's the test content:

test content

Here's the site editor:
site editor

I wanted to bring attention to one change to what I've been referring to as the "trailing appender". This is when you have a not-text-block (such as an image) as the last block in a block list. This is the appender I think we should look at removing, separately. In trunk, it sits on the left:

trunk

In this branch it now sits on the right:

this branch

Given the plus that sits inside an empty paragraph was always on the right, I actually think this is a good change. But it's nevertheless a change.

**Review by ellatrix — APPROVED** [review]
Looks good to me. I actually like that there's no space between the block outline and the plus icon.

**Comment by jasmussen** [comment]
Looks like some of the test failures here are legitimate, probably due to the changes to not show the appender on ancestors.

**Comment by jasmussen** [comment]
For those of you subscribed to this thread, I would love for you to give this one a final sanity check so we can hopefully land it. I think it's in a good place, cleans up some things, and helps us avoid the layout shifts. But please take it through the wringer to see if there are any edgecases I might not have caught.

**Comment by youknowriad** [comment]
Give me some minutes, I'll try to review this properly.

**Comment by jasmussen** [comment]
I won't press the button until you've all had a say! Take all the time you need, thank you for looking.

**Comment by youknowriad** [comment]
This is very cool :) 

For me, the only thing that bothered me is the fact that container blocks (group, row, column, cover) don't show the appender when the last block is a paragraph, I think that behavior doesn't make sense anymore with the appender being absolute positioned.

**Comment by youknowriad** [comment]
I also like all the style removals 👏

**Comment by jasmussen** [comment]
> For me, the only thing that bothered me is the fact that container blocks (group, row, column, cover) don't show the appender when the last block is a paragraph, I think that behavior doesn't make sense anymore with the appender being absolute positioned.

@ellatrix I think mentioned this particular type of appender as well. Just to be sure, do you feel like the plus _should_ be shown regardless of content? Or _shouldn't_ be shown?

**Comment by jasmussen** [comment]
(And either way, feel free to push to this branch if you like, I think it migh be beyond my skill to change that)

**Comment by youknowriad** [comment]
For me, it should always be shown (maybe just an exception for the root).

Let's merge this and I can attempt this change separately.

**Comment by jasmussen** [comment]
Sounds good. I wanted to note one side effect with the navigation submenu that I'd like to follow up on separately. When clicking a submenu, the black plus is there to add a submenu item, that works well:
Screenshot 2021-11-19 at 15 25 20

The change to only show this black plus when the _container block_ is selected, though, has the side effect that this plus disappears as soon as you add an item inside:
Screenshot 2021-11-19 at 15 25 24

I actually think this PR is healthy to merge because it shows all these side effects that are important to consider as we improve the situation here inside the component itself, with some more obvious and predictable visibility behaviors perhaps as props. In the mean time, I can whip up a quick fix for the navigation block editor.scss file to surface that black plus, even when a submenu item is selected. 

If you agree, feel free to press the green button and I'll follow up.

**Comment by ZebulanStanphill** [comment]
Just posting to confirm that the appender is now appearing as expected in Group blocks for me, and also that I, too, prefer having the appender touching the block border as it does now.

**Pull request merged**
