### PR TITLE
WIP: Add caption to post featured image

### PR DESCRIPTION
**Pull request by carolinan**
## What?

This is an **experiment** for [#40946. 
](https://github.com/WordPress/gutenberg/issues/40946)

## Why?

The post featured image block does not have support for captions, which makes it inconsistent with the image block.

Many sites have existing image captions stored in the media library. Users who are switching from classic editing to using blocks can not easily reuse this data. This makes it difficult for users who are required to show image credits to switch to using blocks.

## How?

The plan is to try something like the following:
1) Enable the caption for the post featured image block.
2. When placed in the block editor, the caption can be customized per block. If there is a media library caption, there is an option to show that instead of the customized caption text.
3. In the query loop, the caption can be toggled on and off, but it displays the caption from the image post in the database (the caption in the media library). The caption text can not be edited as part of the block since the block is repeated for each post in the loop.
4. In templates, the caption can be toggled on and off but shows a placeholder text. On the front, it displays the caption from the image post in the database.

## Video
Single post featured image with caption:

https://user-images.githubusercontent.com/7422055/221136479-35dc87a4-4c25-43a0-8356-be50bfb539c4.mov

Longer video with more block settings:
https://user-images.githubusercontent.com/7422055/221135017-3e3ed808-ed4e-4708-98b7-f37461fdb1f7.mov

### CODE REVIEW

**Comment by carolinan** [comment]
- Or perhaps there could be an option to select the source, and choose between the description, caption or title from the media library.

**Comment by carolinan** [comment]
The PR is ready for early feedback about the user experience when selecting between the custom caption and media library caption.

**Comment by jasmussen** [comment]
Oh that's an interesting one, thanks for taking a stab. So just to be sure I'm getting this right, not only does this PR enable the caption button for the post featured image block, but it allows you to choose between the caption stored for the media item, or using a custom one, is that right?

This actually surfaces a bit of a disconnect we have with captions, including the one we have for images. There's a caption field in the database, but the caption feature is not connected with it at all. Should it be, in both cases? I.e. when you add a caption, it also saves it for the image? (My instinct is _probably not_, especially since the disconnected version is out there. But I feel like it's an important question to ask!) 

Same unknown around the other fields, title, description, alt text.

Caption and alt text feel like the odd ones out, and almost anachronistic in the block editor world. So approaching it from the opposite end: if we were to rebuild the media library today, from scratch, would we add a field called "Caption"? I'm not suggesting retiring those fields, but would we build such a media library and have it save alt text and captions separately from the block content? Either answer seems like it could inform next steps on this one, and both feel relevant to noodle on for this one. What do you think?

**Comment by carolinan** [comment]
>not only does this PR enable the caption button for the post featured image block, but it allows you to choose between the caption stored for the media item, or using a custom one

Yes that is correct.

------
Image block:
The caption in the media library is used if it exists or if you enter one when you upload the image.
But if you toggle the caption off in the toolbar, and toggle the caption on again, it no longer uses the media library caption but the editable custom caption.
So there is no way to get the media library caption to show again without deleting the image and adding it again.

-----

I think both the caption, alt and title attribute **can be** situational and that they should not be saved to the image data in the media library.
For example you might want a short caption in a gallery block. And you might want to use a longer when the image is used alone.

If you upload an image and its data is imported and saved to the database, or if you add a caption in the media library, then changing the caption in the block editor should not replace the text.

**Comment by richtabor** [comment]
With what we have today, the caption _won't_ be visible the majority of the editing experience — only if you add the Post Featured Image block to the block editor. When we have content editing within the Site Editor, it'll be more front-and-center. 

> When placed in the block editor, the caption can be customized per block. 

I think the caption should be tied to the featured image, not the block (just like the image _is_ the featured image). If I edit the featured image, the post's featured image is updated. Its caption should work the same: if I edit the featured image's caption, it is consistent wherever the post featured image is leveraged. 

Also, I'm cool with making the button a show/hide functionality, rather than an add/remove. I'd say the same for the Image block as well. Having a caption — and whether or not it is visible — should be treated differently. 

> Should it be, in both cases? I.e. when you add a caption, it also saves it for the image? (My instinct is probably not, especially since the disconnected version is out there. But I feel like it's an important question to ask!)

Yea, I agree.

**Comment by richtabor** [comment]
I don't think it's important to indicate it's a "Media Library" caption: 

CleanShot 2023-03-06 at 16 16 37

**Comment by richtabor** [comment]
Noticed an issue with overlay color applied as well: 

CleanShot 2023-03-06 at 16 18 13

**Comment by carolinan** [comment]
The existing caption feature, ignoring this PR, does not save the caption to the image. I believe it is too late to make it save to the image since there are already images placed with custom captions.
I believe we need to keep the features of the different image blocks as close as possible to reduce the risk of confusion. 

"The caption wont be visible... unless you are in the block editor"
I did not understand. Featured images are not usually in the block editor so I would say the opposit. You can't edit the custom caption inside a query loop but you can show the media library caption inside the query.
The label is used to distinguish that it is always the media library caption and you can't customize it. 
The problem that the PR tries to solve is that there is no way for users in countries like Germany to display the image credits which they are required to do. So some type of websites will show it more than others. 

**Edit:** I mentioned that the issue had a discussion about image credit in Germany, but it was actually a discussion in the WordPress Slack channel that referenced the issue. An account is needed to read it: https://wordpress.slack.com/archives/C015GUFFC00/p1672557641127699?thread_ts=1672500070.405439&cid=C015GUFFC00

**Comment by richtabor** [comment]
> The existing caption feature, ignoring this PR, does not save the caption to the image. I believe it is too late to make it save to the image since there are already images placed with custom captions.

Agreed. 

> I did not understand. Featured images are not usually in the block editor so I would say the opposit. You can't edit the custom caption inside a query loop but you can show the media library caption inside the query.

You can't see the actual post's featured image caption in the Site Editor, it's a placeholder. 

Once we have content-editing you will be able to see it. With this PR the only way to actually see your caption, is to use it within the Block Editor, yea?

> I believe we need to keep the features of the different image blocks as close as possible to reduce the risk of confusion.
> The label is used to distinguish that it is always the media library caption and you can't customize it.

Then perhaps we make it work 100% like the image block's caption? Why not make it editable?

**Comment by carolinan** [comment]
> You can't see the actual post's featured image caption in the Site Editor, it's a placeholder.

It depends where in the Site Editor. If it is in the Site Editor and inside a query loop, and the featured image has a  media library caption, the media library caption can be toggled on and off.
If it does not have a media library caption, the option will not show in the toolbar.
It is not customizable, unless you open the image in the media library.

(Forgive my test content I was testing the post excerpt block)
https://user-images.githubusercontent.com/7422055/223979540-5bb60bc1-697b-43cb-b045-f6989aac7eae.mp4


In a post template, without the query loop, it can be toggled on and  off, it will display the media library caption on the front depending on the featured image that is used on that post.

**Comment by carolinan** [comment]
>I believe we need to keep the features of the different image blocks as close as possible to reduce the risk of confusion.
>The label is used to distinguish that it is always the media library caption and you can't customize it.

>Then perhaps we make it work 100% like the image block's caption? Why not make it editable?

I did not understand. Can you be more specific? It is already editable when in the block editor, outside a query.
You have the option to:
- Not display a caption
- Customize the caption for that single instance
- Display the media library caption, which is the same for all copies of the image

Currently without this PR, in the image block, you can't choose to display the media library caption if you have done one of the following:
-Toggled the caption off
-Toggled the caption off and on and added a custom caption

**Comment by richtabor** [comment]
Let's maybe back up a little. 

### Should the caption work the same as other media captions do? 

I think yes. 

That means you can edit the caption via RichText component, if it's turned on — regardless of if it comes from the Media Library caption field or not. 

Example: If I press "Remove caption" then the caption is removed. If I press "Add caption" then I can type in a caption. The toolbar item for caption is always there, not dependent if there's a caption in the Media Library entry. 

### Editing the caption

All that is assuming you _see_ the caption (to edit it like the Image block's caption). 

If you add the post featured image block to a template (likely), you'll see the placeholder caption (as you should). There's no relative content templates; everything's a placeholder.  

placeholder-caption

In Query loop, you can toggle the caption on — but _can't_ edit it. There's actually not a way to edit the caption as-is, unless you go back to the Media Library — probably via WP admin. I would expect that I could click on the caption in this context (when it's not a placeholder) to edit it — same as I can for all other media blocks. 

within-site-editor-query-loop


#### Media Library v. Custom Captions

I don't think we need to separate "Media Library caption" and "Custom caption", but just like the Image block, use the Media Library caption, unless it has been edited. We should push for one-to-one experiences for blocks within the Post and Site Editors, and like-blocks as well. 

CleanShot 2023-03-09 at 12 11 50

**Comment by carolinan** [comment]
Doing that you still can't choose to display the media library caption if you have done one of the following:
-Toggled the caption off
-Toggled the caption off and on and added a custom caption

But do you see a way to edit the caption for individual posts inside a query without saving the caption to the _image_, which I thought we agreed we couldn't do? 
It can't be saved to the _block_ in this case since all the blocks are repeated.

**Comment by carolinan** [comment]
This round I have assumed that with "make _it_ editable" you meant make the media library caption editable and save the updated text as the block's caption attribute. It would have helped me if the suggestion had been more specific.

I spent more hours on this than I would like but I was not able to solve it and make it work exactly like for the other media blocks. 😞 
I tried many different things, the code that I have pushed now was only one of the tries: Know that it is **much much** buggier than the previous commits.

One of the problems is making the media library caption show by default without clicking the caption button.
In the other media blocks, the caption block attribute is updated when the media is selected.
But that does not work for featured image unless you are selecting the image when adding the block. It doesn't work if the image is already assigned.

**Comment by carolinan** [comment]
Closing this **experiment** in favor of a simpler solution.

**Pull request closed without merging**
