### PR TITLE
Build: Make `lerna` a dependency rather than a devDependency

### LINKED ISSUE #6718: Make `lerna` a dependency rather than a devDependency
**Describe the bug**
For context see #6658 .  My plugin (I'm assuming others might as well) has GB/master defined as a devDependency because we use gutenberg in jest unit tests.  However, since the mentioned pull was merged in we're getting [failed builds in travis](https://travis-ci.org/eventespresso/event-espresso-core/jobs/377880482).  Specifically, this is the cause:

```bash
> gutenberg@2.8.0 postinstall /home/travis/build/eventespresso/event-espresso-core/node_modules/gutenberg
> lerna bootstrap --hoist
sh: 1: lerna: not found
```

@aduth and I had a [chat about this in slack](https://wordpress.slack.com/archives/C02QB2JS7/p1526067807000549) and it looks like one resolution would be to move lerna from being a devDependency to being a dependency.

Other solutions could be removing the post-install script, or modifying it so it only runs in the context of Gutenberg itself.

### PR DESCRIPTION
**Pull request by gziolo**
## Description
Closes #6718 raised by @nerrad.

I guess it's a temporary solution until we have all packages published.

In general, you shouldn't need to do it. You can double check looking at package.json files from Babel, Jest or create-react-app.

## How has this been tested?
`npm i` still works.

### CODE REVIEW

**Review by ntwb — APPROVED** [review]

**Comment by nerrad** [comment]
Thanks for doing this, I can confirm it fixes the issue I reported.  I'm curious what this statement means though:

> You can double check looking at package.json files from Babel, Jest or create-react-app

It seems like something that would be handy knowledge to have.

**Comment by ntwb** [comment]
@nerrad Once we have _all the things_ published to https://www.npmjs.com/org/wordpressand working as expected we should be able to remove Lerna from `dependencies` back to `devDependencies` as you will be able to inspect the various `package.json` files and only _require_ the packages you need to require rather than all of Gutenberg as is the case for you right now.

**Comment by gziolo** [comment]
Yes, what @ntwb explained, thanks 🙇

**Comment by nerrad** [comment]
Ahh gotcha, I was already aware of that but didn't realize that's what was being referred to.  Thanks for clarifying 👍

**Pull request merged**
