### PR TITLE
Release: v9.5.1

### PR DESCRIPTION
**Pull request by WunderBart**
Cherry-picked bugfix PRs for a patch release:

- https://github.com/WordPress/gutenberg/pull/27550
- https://github.com/WordPress/gutenberg/pull/27445
- https://github.com/WordPress/gutenberg/pull/27466

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
Actually, this PR is targetting the wrong branch,  it should target release/9.5

**Comment by youknowriad** [comment]
Looks like there's a small package.lock diff that might  be good to fix to get the tests passing

**Comment by WunderBart** [comment]
> Looks like there's a small package.lock diff that might be good to fix to get the tests passing

@youknowriad, this one's actually a bit confusing to me (https://github.com/WordPress/gutenberg/runs/1518139432?check_suite_focus=true) - shouldn't it be making the build via `npm ci`, not `npm install`? This way it wouldn't attempt to update the `package-lock.json`.

**Comment by youknowriad** [comment]
Ideally we don't name temporary branches `release/*` because these are special branches (protected)

**Comment by youknowriad** [comment]
@WunderBart I thought there's a valid reason for this check to not run `npm ci` but it's not important here, I think we should explore that separately. I'm fine merging with this failure.

**Pull request merged**
