### PR TITLE
[RNMobile] Add rounded corners on media placeholder and unsupported blocks

### LINKED ISSUE #999: Refine border-radii on placeholder/unsupported blocks
### Current (no radius)

31B42FB5-9091-41B3-9182-6E59B80C8A56

### Proposed Design (4px)

F1F7B51D-2531-4839-A206-0B48F6CC9D76

### PR DESCRIPTION
**Pull request by maxme**
## Description

Fix https://github.com/wordpress-mobile/gutenberg-mobile/issues/999

I had a look at other places this could be changed, by searching for components with a gray background color:

```sh
$ find . -iname "*native*.*" -exec grep -H background-col {} \; 2> /dev/null | grep "gr[ae]y"
./gutenberg/packages/block-library/src/video/style.native.scss:	background-color: $gray-lighten-30;
./gutenberg/packages/block-library/src/missing/style.native.scss:	background-color: #e9eff3; // grey lighten 30
./gutenberg/packages/block-library/src/image/styles.native.scss:	background-color: $gray-lighten-30;
./gutenberg/packages/block-library/src/image/styles.native.scss:	background-color: $gray-lighten-30;
./gutenberg/packages/block-library/src/more/editor.native.scss:	background-color: $gray-lighten-20;
./gutenberg/packages/block-library/src/nextpage/editor.native.scss:	background-color: $gray-lighten-20;
./gutenberg/packages/components/src/mobile/bottom-sheet/styles.native.scss:	background-color: $light-gray-400;
./gutenberg/packages/components/src/mobile/bottom-sheet/styles.native.scss:	background-color: $light-gray-400;
./gutenberg/packages/components/src/mobile/bottom-sheet/styles.native.scss:	background-color: $light-gray-400;
./gutenberg/packages/block-editor/src/components/block-list/block.native.scss:	background-color: $gray;
./gutenberg/packages/block-editor/src/components/media-placeholder/styles.native.scss:	background-color: $gray-light;
./gutenberg/packages/block-editor/src/components/inserter/style.native.scss:	background-color: $gray-light; //#f3f6f8
./gutenberg/packages/block-editor/src/components/warning/style.native.scss:	background-color: $gray-lighten-30;
```

Then I manually opened these style sheets to check if they were used in some sort of a container, and it seem only one more need to be updated: `block-editor/src/components/warning/`, so I did the change there as well.

Rounded corners were added to the following components:
- `block-editor/src/components/media-placeholder/` - used to display placeholder on image/video blocks
- `block-editor/src/components/warning/` - used to show a warning when a block is not valid.
- `block-library/src/missing/` - used to show a placeholder when the block is not supported.

## How has this been tested?

I tested the changes in the gutenberg-mobile repository.

## Screenshots 

out

With the fix applied:
Screenshot_1563960758

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 

cc @iamthomasbishop  @hypest

### CODE REVIEW

**Comment by maxme** [comment]
Note: I made the heading blocks invalid to make that before/after screenshots.

**Comment by iamthomasbishop** [comment]
Beautiful, thank you! 

Also, side note – and let me know if you'd prefer to tackle in a separate issue: I thought my eyes were playing tricks on me, but the background colors on unsupported vs. placeholders are different 😱

We will be bringing a new color scheme to the editor soon (not sure how quickly because there are other higher priorities) – so this will change to a neutral gray pretty soon – but if in the meantime, can we bring these two in-line with each other? 

IIRC, the placeholder color (`$gray-lighten-30` aka `#E9EFF3`) is the "correct" value. I can create an issue for this if you'd rather tackle separately @maxme. Thanks again!

**Comment by maxme** [comment]
> background colors on unsupported vs. placeholders

Yep, I thought this was done on purpose :) but I agree that felt wrong to me, especially in this screenshot with the 4 "card blocks" in a row.

> in the meantime, can we bring these two in-line with each other?

Yep sure, I'll update it in this PR.

**Comment by maxme** [comment]
I updated the media placeholder background color to `$gray-lighten-30` in e249d24 

Screenshot_1563980032

**Comment by iamthomasbishop** [comment]
Perfect – thank you!

**Comment by etoledom** [comment]
Will review as soon as possible! 🙏

**Review by etoledom — APPROVED** [review]
Looks and works great! 🎉 

Tested on current `gutenberg-mobile:develop`, updating this branch with `gutenberg:rnmobile/master`.

We could retarget this branch to `rnmobile/develop` or simply merge to `master` and get these improvements when we go back to using `master` (hopefully will be soon).

Let me know and I can press the button if you still don't have access 👍

**Comment by maxme** [comment]
@etoledom I tried to switch base branch to `rnmobile/develop`, I didn't realize `master` and `rnmobile/develop` were so divergent. So I propose we keep this in `master` for now or if we really need it, we'll just cherry pick the 2 commits from this PR.

> Let me know and I can press the button if you still don't have access 👍

**Comment by etoledom** [comment]
> So I propose we keep this in master for now or if we really need it, we'll just cherry pick the 2 commits from this PR.

Sounds good to me! Thank you 🎉

**Pull request merged**
