### PR TITLE
Gallery block: Refactor "Settings" panel to use Toolspanel

### LINKED ISSUE #67893: Refactor "Settings" panel of Gallery block to use `ToolsPanel` instead of `PanelBody`
Part of #67813 

Convert the "Settings" panel of the Gallery block to use the `ToolsPanel` instead of `PanelBody`

### PR DESCRIPTION
**Pull request by Mayank-Tripathi32**
part of #67813
resolves #67893
 
## Before 
 
image

## After
image
image

### CODE REVIEW

**Comment by Mayank-Tripathi32** [comment]
Working on fixing unit test

**Comment by fabiankaegy** [comment]
@Mayank-Tripathi32 looks like there is already a PR for this one https://github.com/WordPress/gutenberg/pull/67904

But that one also has the same issue with the unit tests. So feel free to collaborate in case you already have a solution for the tests :)

**Comment by Mayank-Tripathi32** [comment]
> @Mayank-Tripathi32 looks like there is already a PR for this one #67904
> 
> But that one also has the same issue with the unit tests. So feel free to collaborate in case you already have a solution for the tests :)

I tried to figure it out, but most issues occur on mobile, and I'm unsure how to fix them. If you have any resources, I'd be happy to try again.

**Review by t-hamano — COMMENTED** [review]
Thanks for the PR!

I think the unit test failure is based on the fact that `ToolsPanel` and `ToolsPanelItem` are not available in the React Native version. There are two solutions:

1. Split the `Edit` component into a web version and a React native version. That is, create a `edit.native.js` file for the React Native version. Leave the `Edit` component unchanged in the React native version.
2. Render the component conditionally using `Platform.isWeb` or `Platform.isNative`.

I think the _latter_ approach is better for the Gallery block, since the `Platform` is already used for block controls etc.

**Comment by Mayank-Tripathi32** [comment]
i think we can move with #67904 as it seems to have unit tests fixed. Will close this.

**Pull request closed without merging**
