### PR TITLE
Fix/button css specificity

### PR DESCRIPTION
**Pull request by m-e-h**
## Description
Reduces specificity in core button styles to ease clashes with theme styles.
This has been explained in further detail here https://github.com/WordPress/gutenberg/issues/11779#issuecomment-438753222

This takes care of some cases mentioned here https://github.com/WordPress/gutenberg/issues/11677

And attempts to solve https://github.com/WordPress/gutenberg/issues/11998 by giving the Twenty-* themes 1 single button class selector to style `.wp-block-button__link`.
It also strengthens the specificity of the color and background-color classes so they'll override when the user chooses them. 

The button color was added to the parent `.wp-block-button` element so that the link could `inherit` the color whether it be a default button with `$white` text or an outline button with `$dark-gray-700` text.
This drys up the code some and allows for single class selector overrides.

The CSS selectors for the Text Color and Background Color settings have been given more specificity to override `.wp-block-button__link` even with the pseudo-classes `.wp-block-button__link:hover`.

Duplication of the class selector is used here for two reasons:

1. These are utility classes that should be usable anywhere.
2. Less ambiguity than a nested selector. It's obvious by looking what the purpose is.

## How has this been tested?
In depth visual tests were done in browser.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
If the duplicate selectors for the color names are acceptable, I'd also like to apply the same to the font sizes (in a separate PR) so we can partially close #11200.

**Comment by jasmussen** [comment]
As a followup, I fixed the double outline issue in https://github.com/WordPress/gutenberg/pull/12051.

**Comment by m-e-h** [comment]
Thanks for checking this out @jasmussen! 
Sorry for not showing better visuals for testing, ran out of time on Friday but wanted to get this PR submitted.

Twenty Nineteen isn't great for testing this since it's not using the default color methods and options.

Also, while not specifically to blame for the results in your Button Preview screenshot, it's worth noting the influence that the mapped `body` to `editor-styles-wrapper` can have on some theme's Button Previews. https://github.com/WordPress/gutenberg/issues/11997#issuecomment-439727067

Not sure I'd call the "duplicate selector for the purpose of specificity" a hack. It does behave the way it's supposed to according to the W3C https://www.w3.org/TR/selectors-3/#specificity
> Note: Repeated occurrences of the same simple selector are allowed and do increase specificity. 

Though we probably could use a CSS comment here since this rule may be new to some.

I'm not aware of any performance issues with the `:not()` selector. 
I've found using `:not()` to be a perfect choice in a lot of situations. However, I don't think it's a good fit here.
It seems like we're using it here, in lieu of, relying on proper specificity and cascade. This "crutch" gets exposed whenever a theme attempts to style the button without also using `:not()`. This can be seen with the default themes in the WP 5.0 branch. https://github.com/WordPress/gutenberg/issues/11998

**Comment by chrisvanpatten** [comment]
> Might also be worth pulling these style from the style.scss file and creating a proper utility.scss(or other) file to import at the end of the style.scss

YESSSS this would be amazing. Having these classes separated out would be so cool. 

> The double-specificity hack is super clever, but is it too clever? Do we need a CSS comment to explain what is going on? Are we actually making it easier for themers, or are we just pushing the complexity elsewhere? How sure are we that the :not selector is not performant when used judiciously?

I think this is more straightforward, and easier to parse, vs `:not`. That said the pattern isn't common, and I think a code comment is reasonable here.

I think this is a sensible path forward. I don't think it's necessarily the _best_ scenario (that would be Gutenberg generating CSS for color palettes and font sizes so we can ensure correct specificity) but this is definitely a step in the right direction. I think anything we can do to simplify the CSS and reduce specificity to the bare minimum will make things easier for themers to override.

**Review by jasmussen — APPROVED** [review]
This seems to work as intended, and have a lot of thought put into it, plus sanity checks. I trust that it improves the situation, so let's keep moving. But do add a comment about the double-use of the selector as a CSS comment, something a la `// Double the class name to increase specificity` ... something in that vein. Thanks!

**Comment by jasmussen** [comment]
I put it in the 4.5 milestone, which is the release candidate milestone. This is a big one. If you feel unsure about an aspect, let me know and we can move it.

**Comment by aduth** [comment]
>This partially fixes #11677

The phrasing here is going to trigger automated closure of #11677, which I suspect is not intended.

**Comment by chrisvanpatten** [comment]
> then maybe it is a candidate for !important, but I preemptively sense the instinctual disgust that triggers 😉

This is actually a common use of `!important` (for utility classes in OOCSS). I think that would actually be the ideal scenario except that it limits themers who want to tweak Gutenberg's color values while keeping the color names. I'm not sure they _should_ be doing that, but I expect it won't be uncommon.

**Comment by m-e-h** [comment]
I don't disagree @aduth. I think the case could be made for `!important` here. But is it worth the backlash? 

It is making an assumption that what it's overriding will precede it and have no more than two classes or a class and a pseudo-class such as `.wp-block-button__link:hover`. 
I don't know how "fragile" it is though, considering we're in control of the styles it's meant to override and the placement of these styles.

`.has-background.has-pale-pink-background-color` would probably be just as good. 
I guess in theory though, it wouldn't be as scalable in the long term as it would tie the two classes together. Since the class already says the one and only thing it does in it's name, it shouldn't need to be tied to another.

**Comment by aduth** [comment]
>considering we're in control of the styles it's meant to override and the placement of these styles.

Yes, but it makes an assumption that the hypothetical future maintainer is aware of these circumstances should they decide naively to add some specificity to the class selectors these are meant to override.

**Comment by m-e-h** [comment]
> naively to add some specificity to the class selectors these are meant to override.

That's a possibility. 

Would be awesome though if WP could right it's past transgressions and make single class selectors it's norm or even the rule.

I'm going to continue to help however I can to move us in that direction.

I'm not against `!important` here but the 2 class up in specificity does fix where the previous implementation was broken.

**Comment by aduth** [comment]
Can we at least add the explaining comment? https://github.com/WordPress/gutenberg/pull/12005#pullrequestreview-176374862

Otherwise, I'm fine to have this land as-is as an improvement over the current state.

**Comment by youknowriad** [comment]
Added the comment per @aduth's suggestion. Let's continue iterating on this kind of improvements.

**Comment by catehstn** [comment]
test/e2e/specs/links.test.js failed on line 302 on PHP latest. Restarting it.

**Comment by catehstn** [comment]
All tests are passing - @aduth or @youknowriad do you want to merge this?

**Pull request merged**
