### PR TITLE
Cover: Add Background size support

### PR DESCRIPTION
**Pull request by retrofox**
## Description
This PR adds the background-size control section to the Cover block, in the block settings sidebar.

## Demo Video

https://cloudup.com/cLE07dcijeQ

## How has this been tested?

Add a cover block. Set an image background, and play with the background-size options.

Screen Shot 2020-11-13 at 9 26 06 PM

## Background Size options

It supports four size options: `cover`, `contain`, `original`, and `custom`. _Note: please feel free to destroy the icons 😅_

### Cover (default)

Applies `cover` CSS background-size property to the image.

Screen Shot 2020-11-13 at 9 35 54 PM

### Contain

Applies `contain` CSS background-size property to the image.

Screen Shot 2020-11-13 at 9 36 40 PM

### Original

Applies `initial` CSS background-size property to the image.

Screen Shot 2020-11-13 at 9 37 24 PM

### Custom

It opens a secondary panel that allows defining the background-size with value + units, with the `width`, `height`, and `Width & Height` modes.

* `width`: It will apply width size to the image, and `auto` to the height. It keeps doesn't change the image proportion.
* `height`: It will apply height size to the image, and `auto` to the width. It keeps doesn't change the image proportion.
* `Width & Height`: apply width and height values. The image could change its proportions.

width | height | Width & Height
------|--------|----------
Screen Shot 2020-11-13 at 9 38 30 PM | Screen Shot 2020-11-13 at 9 39 57 PM |Screen Shot 2020-11-13 at 9 41 28 PM

The available units are `px` and `%`.

## CSS class and inline styles.

In the editor canvas, the styles are applied using inline styles. On another hand, the styles are applied via CSS classes, less the custom mode, since it uses value + unit notation.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for the PR! This seems like it could be a cool feature, but it also adds a great deal of complexity to a sidebar that is currently complex.

That doesn't mean we can't make it work, but it does mean that it needs a good and solid sidebar component control design before we can move on it. We will get there, but I'll ask your patience because it might not be this week!

CC: @jameskoster @ItsJonQ

**Comment by retrofox** [comment]
> That doesn't mean we can't make it work, but it does mean that it needs a good and solid sidebar component control design before we can move on it

Yeah, agree. I did a pretty-simple buttons group, but the idea is to be able to switch it for another component easily. I tried to get involved with some ideas around this component but not lucky so far.

**Comment by stokesman** [comment]
@retrofox, I'm glad to work on this feature. In case you hadn't see it, I wanted to point out the related concept in #20193. Something like that, while probably a good bit more effort to implement, could sidestep the concern about a complicating the sidebar.  Plenty to work out though even beside the implementation since that concept only seems to detail the "custom" scenario and it's not shown how that might switch from "cover" or "contain".

**Comment by retrofox** [comment]
> @retrofox, I'm glad to work on this feature. In case you hadn't see it, I wanted to point out the related concept in #20193. 

Thanks. Yes, I saw it :-)

> Something like that, while probably a good bit more effort to implement, could sidestep the concern about a complicating the sidebar.

What's not clear to me is the UI. should the block change its inner content with an `Editing background tool`? Providing a `save` button that allows going back to the regular state?

> Plenty to work out though even beside the implementation since that concept only seems to detail the "custom" scenario and it's not shown how that might switch from "cover" or "contain".

we can add a `preview` button to switch quickly between `background edition mode` and `regular mode`

**Comment by stokesman** [comment]
> What's not clear to me is the UI. should the block change its inner content with an `Editing background tool`?

In that issue it is mentioned https://github.com/WordPress/gutenberg/issues/20193#issue-564139202:
> ... would focus just on the background of the block (fading all the layered blocks and their controls away) 

But do they fade away completely? It may be desirable to adjust the background in relation to the inner blocks but because it will vary responsively, perhaps just fading them away completely is better. It does seem clear they should not be selectable though.

> Providing a `save` button that allows going back to the regular state?

I think that's the checkmark here:
block toolbar concept
But it'd probably be better to do like the Image block currently implements for cropping and supply “Apply” and “Cancel” buttons.

BTW, my original comment here was supposed to say “I'm glad to **see** work on this feature”, to express appreciation for your work on this. (And while I would like to work on the implementation I'm not sure when I'll find the time).

**Comment by annezazu** [comment]
This hasn't been worked on in a number of years! I'm going to close it out as a result and encourage you to open a new PR that's in sync with the current codebase at this point. There's some great efforts currently under way to improve background image support too over the last couple of releases if you wanted to get involved there: https://github.com/WordPress/gutenberg/issues/54336

**Pull request closed without merging**
