### PR TITLE
Revert the button block to the previous markup

### LINKED ISSUE #21909: Core themes compatibility with simplified Button block markup
The simplified Button markup introduced in https://github.com/WordPress/gutenberg/pull/21266 appears to require updates in the core themes so that the new buttons match the legacy button styling. In the following themes, if you add some new buttons (select a mix with outline styles), their styling doesn't match how the theme handles legacy buttons. After the fixes in https://github.com/WordPress/gutenberg/pull/21642 and https://github.com/WordPress/gutenberg/pull/21816, the legacy buttons are looking pretty good! Looks like it's now the new markup that needs addressing.

Some of the button styles below are closer than others (e.g. the difference might only be a lack of uppercase or underline, but for others like 2019, the difference is more pronounced). Note that in each of the screenshots under "New buttons", two of the buttons should be rendered with outline styles.

#### Twenty Nineteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Seventeen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Sixteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Fifteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Fourteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Thirteen

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Twelve

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

#### Twenty Eleven

| Legacy buttons | New buttons |
| ------- | ------------- |
| image | image |

I haven't included themes 2010 and 2020 in this list because they're looking pretty good to me so far.

Is this the best place to log this issue for these themes, or should individual tickets be opened separately? (I wasn't sure if there might be individual tracking issues already)

CC: @youknowriad

### LINKED ISSUE #21917: Button block styling broken in editor and on front end due to change in markup
**Describe the bug**
The changes in https://github.com/WordPress/gutenberg/pull/21266 have resulted in button styles being broken in our Genesis child themes designed around the block editor. 

The markup has changed to remove a div wrapper from the button block and is automatically updated when editing a post. As a result, any styles written as `.wp-block-button .wp-block-button__link` will no longer apply because the `.wp-block-button` is moved to the link. New CSS would either need to drop the `.wp-block-button` or be written as `.wp-block-button.wp-block-button__link`.

In some themes, style variations rely upon the .`wp-block-button__link` having the `.wp-block-button` div wrapper for pseudo class styles.

**To reproduce**

1. Install https://github.com/studiopress/genesis-sample/archive/develop.zip with WordPress 5.4. (requires Genesis parent theme - happy to supply directly, if needed.)
2. Activate the theme.
3. Add the content below to the code editor, switch to visual, then save.
4. Activate Gutenberg 7.9.1.
5. Edit and update the page.
6. Note that the markup is updated in the editor and the front end.

The button appearance changes from this:
Screen Shot 2020-04-24 at 2 23 04 PM

to this:
Screen Shot 2020-04-24 at 2 19 57 PM

**Expected behavior**
Markup changes will be backward compatible with existing themes. As we embrace the editor in designs and work to expand usage, changes to markup and classes impact user experience as well as maintenance for theme developers. 

If this were an editor only problem, the issue would be less concerning, but this will impact the front-end of user sites without warning since the markup automatically updates when editing.

**Screenshots**

Additional front-end examples are below.

WordPress 5.4:

Screen Shot 2020-04-22 at 4 47 02 PM

Gutenberg 7.9.1:

Screen Shot 2020-04-22 at 4 47 25 PM

Button variation in 5.4:

Screen Shot 2020-04-24 at 3 06 03 PM

Gutenberg 7.9.1:

Screen Shot 2020-04-24 at 3 04 49 PM

**Editor version (please complete the following information):**

WordPress version: 5.4
Gutenberg plugin: 7.9.1

**Desktop (please complete the following information):**

OS: MacOS
Browser: Chrome
Version: 81

**Related to:**

https://github.com/WordPress/gutenberg/issues/21747
https://github.com/WordPress/gutenberg/pull/21642
https://github.com/WordPress/gutenberg/issues/21707
https://github.com/WordPress/gutenberg/issues/21685
https://github.com/WordPress/gutenberg/issues/21909

**Additional context**
Impacts StudioPress Genesis child themes with specific Gutenberg editor styling and which do not have an automated update process. It has the potential to impact more than 34,000 sites running StudioPress themes and an unknown number of themes sold by other developers which use `.wp-block-button .wp-block-button__link` for styling. 

CC: @youknowriad

### PR DESCRIPTION
**Pull request by youknowriad**
The button markup change in #21266 created some backward compatibility issues for theme authors. Noting that we were aware of these breakage (styling for new buttons on the frontend), but sometimes hard decisions are required. This markup change was specially important for Global styles. But since the Global styles project is not shipped as stable yet, this PR reverts the markup change to give us more time before this potential breaking change. I'd still encourage theme authors to update their styles to only rely on `wp-block-button__link` without requiring the presence of a `wp-button` parent or not which would make the styles work regardless of the chosen markup in the end.

closes #21917
closes #21909

### CODE REVIEW

**Review by jorgefilipecosta — COMMENTED** [review]
It seems on this PR when I apply a predefined color with 2020 the color is not viewable on the editor. The same also happened on master but it does not happen on WordPress 5.4. I wonder if the colors not being applied was a regression from https://github.com/WordPress/gutenberg/pull/21266 that we are keeping?

**Review by jorgefilipecosta — APPROVED** [review]
I verified that the markup of the blocks is the same that we had on 5.4 and I did not found any regression when comparing against master.

**Comment by aduth** [comment]
> It seems on this PR when I apply a predefined color with 2020 the color is not viewable on the editor. The same also happened on master but it does not happen on WordPress 5.4.

While I'm unable to reproduce it on master, I do see the same issue. Interestingly, I think it's a side-effect of the fact that this "fixes" theme styling (#21917, #21909). You can see in the screenshot below that the color from theme styles (from TwentyNineteen) has a higher specificity than the predefined color styling:

image

Like you, I did find that it worked as expected on the front-end. In fact, the changes here help restore theme styles which were not working correctly after #21266, in addition to using the correct predefined color assigned to the button.

As far as interoperability with the specific theme styles I'm seeing, I think this is in a better state than `master`, at least so far as the colors working correctly on the front-end. It would be good if we can get the colors interoperating better with the theme styles in the editor. For the purposes of today's RC release and if Riad has finished for the day, for me it would make sense to merge this with the above as an acknowledged "Known Issue", ideally with a resolution before Wednesday's final release.

**Comment by aduth** [comment]
> While I'm unable to reproduce it on master

It appears this may be theme-dependent. On TwentyTwenty, I see the same problems with predefined colors not taking effect in the editor, both on this branch and on `master`. On TwentyNineteen, predefined colors work correctly on `master` but not in this branch. It seems the difference is how the selectors differ between TwentyNineteen and TwentyTwenty. As seen in the screenshot of my previous comment, the TwentyNineteen themes try to style this by assuming separate elements `.wp-block-button` and `.wp-block-button__link`, hence the remark about the fact that this is expected as a result of "fixing" the markup to respect theme styles.

**Comment by youknowriad** [comment]
@jorgefilipecosta @aduth are you testing with the mu-plugins that disable colors enabled or not? this could have an impact here.

**Comment by aduth** [comment]
@youknowriad I am. But even disabling the behavior of it, the problem persists.

buttons-colors

**Comment by BinaryMoon** [comment]
> I'd still encourage theme authors to update their styles to only rely on wp-block-button__link without requiring the presence of a wp-button parent or not which would make the styles work regardless of the chosen markup in the end.

This is the best thing to do but it doesn't guarantee the styles will work.

In the current structure the modifiers (.is-style-outline) get applied to the wrapper, and not the button itself, so you still have to do some CSS gymnastics to make it work consistently for new and old structures.

**Comment by strarsis** [comment]
Hehe, I just finished refactoring the styles to match the new-old button markup. 😄

**Comment by youknowriad** [comment]
@strarsis that's a good thing because in theory they work on both markups right? and it's a win if it ever becomes new again 😬

**Comment by davouid** [comment]
Will it stay lke that?
I like CSS gymnastic but just to know....

> In the current structure the modifiers (.is-style-outline) get applied to the wrapper, and not the button itself, so you still have to do some CSS gymnastics to make it work consistently for new and old structures.

**Pull request merged**
