### PR TITLE
Adding a sentence on the Button block to the Button component readme

### PR DESCRIPTION
**Pull request by aldavigdis**
## Description

Adds a sentence to the Button component readme to point out differences between it and the Button block.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
I definitely get that this is worth calling out, but I do wonder if this is the best place to note it? The markdown in here doesn't get synced into the handbook, and would only be seen by someone explicitly looking at the block library package code in GitHub.

Would it be better to note it in the documentation for the Button component, or in the block-library package's overall README instead (both are synced over to the handbook), possibly alongside a code comment at the top of the button block file?

**Comment by aldavigdis** [comment]
I think this information needs to be somewhere. Either in the documentation itself or inline somewhere.

Having an agreement on the actual location would be the best course of action and then I would just update the PR.

**Comment by gziolo** [comment]
We can always expose README files for core blocks, the same way we do it for components package. I would land docs for blocks first and then we can replicate logic that exists for components.

**Comment by chrisvanpatten** [comment]
@gziolo I'm just not sure it makes sense to do block-level readmes. We already have block instructions for users in the user docs; what would a block readme accomplish beyond that?

Genuinely asking — I never want to shut down the idea of _more_ documentation, just trying to understand why this would be an advantage over what we have.

@aldavigdis In terms of where to put this documentation I think putting it in the button component readme would make more sense for now, and I'll also note that we need to put a message in the Button Block documentation in the user handbook. Are you open to updating the PR?

**Comment by ajitbohra** [comment]
Not sure if we should have docs for each block +1 to what @chrisvanpatten suggested

**Comment by aldavigdis** [comment]
@chrisvanpatten Yes sir! Will update this week.

**Comment by aldavigdis** [comment]
Better late than never. Squashed and pushed a short paragraph to the Button component readme.

**Review by gziolo — APPROVED** [review]
LGTM 👍

**Pull request merged**
