### PR TITLE
Social Links: Use URLInput

### PR DESCRIPTION
**Pull request by jasmussen**
Address feedback in https://github.com/WordPress/gutenberg/pull/16897#discussion_r353410178.

Something's missing, though, I'm getting `Cannot read property 'value' of undefined`. Could use advice here.

### CODE REVIEW

**Comment by aduth** [comment]
Thanks for jumping on this so quickly. Not immediately obvious to me why you'd be seeing that error. I'll have to take a closer look.

**Comment by aduth** [comment]
The main issue is `URLInput`'s `onChange` returns the next value, not an `event` object.

```diff
diff --git a/packages/block-library/src/social-link/edit.js b/packages/block-library/src/social-link/edit.js
index b6d95585e..ea2a1d7c3 100644
--- a/packages/block-library/src/social-link/edit.js
+++ b/packages/block-library/src/social-link/edit.js
@@ -49,7 +49,7 @@ const SocialLinkEdit = ( { attributes, setAttributes, isSelected } ) => {
 						} } >
 						<URLInput
 							value={ url }
-							onChange={ ( event ) => setAttributes( { url: event.target.value } ) }
+							onChange={ ( nextURL ) => setAttributes( { url: nextURL } ) }
 							placeholder={ __( 'Enter Address' ) }
 						/>
 						<IconButton icon="editor-break" label={ __( 'Apply' ) } type="submit" />
```

I still see another error though, not entirely sure yet whether it's related to this branch.

**Comment by aduth** [comment]
Okay, the other error I was seeing seems to be caused by my LastPass browser extension. I assume it was getting confused that the text input was suddenly disappearing from the page after the updated URL is set.

I pushed up the previously-mentioned fix. I hope you don't mind, but I also lumped in a bit of verbiage tweaking to the CSS guidelines in hopes of clarifying why we target the common components.

Last thing I want to do here is just confirm there's not some behavior of `URLInput` we were trying to avoid by using a custom variation of it.

**Comment by jasmussen** [comment]
Don't mind at all.

No, there's no custom stuff going on, only the tweaked placeholder text, and that appears to work fine. Thank you! I'll undraft this.

**Review by aduth — APPROVED** [review]
`URLInput` does do more stuff than what was previously supported here, mostly around suggestions. I guess maybe it was expected that suggested (local) URLs don't make much sense in the context of Social Media links. That could be true, but it seems like something we could make configurable on URLInput if it's really a problem.

In any case, this moves us in the right direction. 👍

**Comment by jasmussen** [comment]
@mkaz can you give this PR a sanity check and merge if all is right?

Thanks again @aduth

**Comment by mkaz** [comment]
This change looks good, :+1:

Here is the [original switch away from URLInput](https://github.com/WordPress/gutenberg/pull/16897/commits/872ea0bd6fd0340e4875f1491e19c3dd1758417b), unfortunately my commit doesn't include the why of the switch. I do remember the suggestions and placeholder being annoying.

This issue will probably help: https://github.com/WordPress/gutenberg/issues/11852

**Pull request merged**
