### PR TITLE
Normalize some of the single instance interface

### PR DESCRIPTION
**Pull request by jasmussen**
This is a first draft at unifying the look so it's easier to compare.

I broke the controls positioning 😭 help me @iseeulde, you're my only hope!

### CODE REVIEW

**Comment by jasmussen** [comment]
I still have this to-do:

- Update colors of icons, controls
- Block outlines should always be below floated elements
- Polish the captions, I made them worse 😭
- Design a separator block
- Polish the gallery & embed block

Technical to-do's

- Outlines and up/down arrows should appear on hover
- Type switcher should sit next to block and inline level formatting options
- Block formatting controls should be grouped in [switcher] [style] [block level] [inline level] bands, and always be visible — style is for quotes and headings. See also https://github.com/WordPress/gutenberg/issues/198

Some of those technical to-do's are hard because the mockups aren't up to date. I'll work on getting them updated and settled.

**Comment by iseulde** [comment]
I need to adjust the editor padding, which is hardcoded for now. :/ I can adjust this, but I would prefer it we please keep some padding around the editor to capture pointer events (this is not a single instance issue but general). I also see that you added padding on the side of text which is normally not done. It should only have margins set in em or rem.

**Comment by iseulde** [comment]
More specifically `padding: 5em;` is removed from `#editor` and we need that padding both to catch clicks and space for the navigation arrows. With catching clicks I mean trying to set the cursor from next to the editor.

**Comment by jasmussen** [comment]
> More specifically padding: 5em; is removed from #editor and we need that padding both to catch clicks and space for the navigation arrows. With catching clicks I mean trying to set the cursor from next to the editor.

Feel free to commit to this branch — I do remember removing that padding... sorry :(

**Comment by iseulde** [comment]
Cool, will adjust! :) One moment :)

**Comment by iseulde** [comment]
@jasmussen Does this look better? I also set the margins to `1em` (height of one line) which is pretty standard.

**Comment by iseulde** [comment]
Oh wait I messed of the quote

**Comment by iseulde** [comment]
That's better

**Comment by iseulde** [comment]
There's also a `min-height` on paragraphs... Not sure why that is. One line paragraphs are looking odd.

**Comment by iseulde** [comment]
Feel free to tweak! :)

**Comment by jasmussen** [comment]
Thank you for the help. I'll merge this in for now and do more later!

**Comment by iseulde** [comment]
@jasmussen Do you know what the `min-height` is for? Otherwise I'll remove it.

**Comment by jasmussen** [comment]
> Do you know what the min-height is for? Otherwise I'll remove it.

Can't recall. Some prototype-only hack for making something flow right, probably. Feel free to remove.

**Pull request merged**
