### PR TITLE
Improve PagePanels performance

### PR DESCRIPTION
**Pull request by noisysocks**
## What?
Requires https://github.com/WordPress/gutenberg/pull/51281.

Updates the `PagePanels` component added in https://github.com/WordPress/gutenberg/pull/50857 to select the minimal amount of data required. This reduces the number of component remounts and therefore improve typing performance.

## Why?
Gotta go fast.

## How?
Before we used `useEntityRecord` which is convenient but selects the entire record—much more data than we actually need! Using the lower level selectors is better for our use case.

## Testing Instructions
1. Go to _Appearance → Editor → Pages_ and select a page.
1. Open the Page sidebar on right hand side. Test that you can still select content blocks and press _Edit template_.
2. Enable _Highlight component updates_ in React DevTools.
3. Type text into the editor. The sidebar shouldn't update excessively.

## Screenshots

Before: 

https://github.com/WordPress/gutenberg/assets/612155/ffcfbba8-c1da-41c7-aceb-8fec9dc81691

After:

https://github.com/WordPress/gutenberg/assets/612155/ab15fb8e-f83d-496f-84b6-a045709f6a55

### CODE REVIEW

**Comment by Mamaduka** [comment]
@noisysocks, can you rebase this on top of the trunk now that #51281 is merged 🙇

**Comment by noisysocks** [comment]
Done!

**Comment by noisysocks** [comment]
In `trunk`:

```
Typing:
Average time to type character: 38.99ms
Slowest time to type character: 115.23ms
Fastest time to type character: 34.96ms
```

This branch:

```
Typing:
Average time to type character: 36.57ms
Slowest time to type character: 105.15ms
Fastest time to type character: 32.66ms
```

**Review by Mamaduka — APPROVED** [review]
Thanks, @noisysocks!

**Pull request merged**
