### PR TITLE
Fix getEntityRecords to ensure resolution on REST API failure

### PR DESCRIPTION
**Pull request by getdave**
## Description
Currently `getEntityRecords()` (which backs most of the entity selectors - e.g. `getMenus`, `getPages`...etc) will not resolve if the REST API fails. This is (presumably) a known problem and is even documented in code within `getEntityRecord()` (note the singular).

https://github.com/WordPress/gutenberg/blob/9fed001f068c048a0e1b601cc9d94cdee0b22b76/packages/core-data/src/resolvers.js#L107-L112

Unfortunately the same fix is _not_ applied to the sibling `getEntityRecords` (plural!) method 😞 

https://github.com/WordPress/gutenberg/blob/9fed001f068c048a0e1b601cc9d94cdee0b22b76/packages/core-data/src/resolvers.js#L202-L206

This leaves us with calling `isResolving()` or `hasFinishedResolution()` for a given selector resulting in states which never resolve to "done" even though the REST API returned with an error. 

This leaves UI code in limbo as we cannot ascertain whether a given selector has resolved yet. https://github.com/WordPress/gutenberg/issues/36286 is a good example of that happening.

This PR updates the method to mirror the solution in the sibling `getEntityRecord` (note the singular!) method by introducing a `catch` statement to the async flow which ensures the the resolver is marked as resolved.

I have to confess that I don't understand why the `catch` causes the selectors to resolve. I'll keep hunting for this but I'm hoping someone more familiar with this area of the codebase can enlighten me 🙏 

Partially addresses UI portion of https://github.com/WordPress/gutenberg/issues/36286

## How has this been tested?

* Create a **contributor** role user and switch to that user.
* New Post.
* Open Devtools console

Now follow the respective instructions below...

### On Trunk

* Type - `wp.data.select('core').getMenus()`.
* You should see a network request which fails for 403. If it doesn't then it's likely that [the REST API permissions issue](https://github.com/WordPress/gutenberg/issues/36286) was already fixed. In that case you will need to use devtools to block requests to that endpoint in order to simulate a failure network request.
* Now check on the resolving state - `wp.data.select('core').isResolving('getMenus')`. You should see `true` even though the REST request has already returned with an error.
* Now check on the resolved state - `wp.data.select('core').hasFinishedResolution('getMenus')`. You should see `false` even though the REST request has already returned with an error.

### On this PR

* Repeat the steps above except this time you should see that the "resolution" state selectors resolve to a "done" state.
    - `wp.data.select('core').isResolving('getMenus')` - should be `false`.
    - `wp.data.select('core').hasFinishedResolution('getMenus')` - should be `true`.

## Screenshots 

n/a

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by Mamaduka** [comment]
> I have to confess that I don't understand why the catch causes the selectors to resolve. I'll keep hunting for this but I'm hoping someone more familiar with this area of the codebase can enlighten me 🙏

I love finding gems like this in the codebase, and as always, @youknowriad provides a good explanation for it - https://github.com/WordPress/gutenberg/pull/28126/files#r555865669.

**Review by Mamaduka — APPROVED** [review]
Thanks, @getdave.

I tested following your instructions and can confirm this fixes the issue.

After reading Riad's explanations of why the `catch` statement works, I also don't see why we shouldn't apply it to the `getEntityRecords` resolver.

**Comment by talldan** [comment]
> I love finding gems like this in the codebase, and as always, @youknowriad provides a good explanation for it - https://github.com/WordPress/gutenberg/pull/28126/files#r555865669.

Good find. So looks like catching it allows control to return to the caller. Obscure, but you can see why it works. Looks like a good fix.

I gave this a test and when clicking 'Select existing menus' on the placeholder the navigation block has an error:
```console
index.js:67 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at index.js:67
    at renderContent (index.js:138)
    at Dropdown (index.js:113)
    at renderWithHooks (react-dom.development.js:15015)
    at updateFunctionComponent (react-dom.development.js:17386)
    at beginWork (react-dom.development.js:19093)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991)
    at invokeGuardedCallback (react-dom.development.js:4053)
    at beginWork$1 (react-dom.development.js:23994)
```

I think it's good to keep the core-data fix separate from the Nav block fix, so lets merge once tests are passing.

**Comment by talldan** [comment]
Just saw there's https://github.com/WordPress/gutenberg/pull/36355 to fix the nav block error. 👍

**Comment by andrewserong** [comment]
Cherry picked into the Gutenberg 11.9 release in: https://github.com/WordPress/gutenberg/commit/95088c48a3874ef1a20715ae3c30099a84f37bd0

**Pull request merged**
