### PR TITLE
Smaller external link icon.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

The external link icon is a little bit imbalanced in its default state, especially now that it's used as a "View post" link:

before

This PR updates the footprint to be better balanced in the context of other similar icons:

before and after

after

Note that the external link icon is also used in smaller size in some cases, when it's inside text. Because of the smaller footprint, this becomes a little smaller still with this PR:

Screenshot 2023-05-18 at 09 40 23

I'm wondering if we should have a separate icon designed for in-text usage? Alternately we can change the default values from 1em to 1.5em:

Screenshot 2023-05-18 at 09 41 07

## Testing Instructions

Publish a post and observe the view post link after.

### CODE REVIEW

**Comment by jameskoster** [comment]
I wonder if it looks a little small now, in the context of the whole set?

Screenshot 2023-05-18 at 11 22 15

The problem with the current icon seems to be how far the arrow portion pokes out of the 16x16 square. An alternative would be to tweak it's position slightly:

Screenshot 2023-05-18 at 11 33 38<br>

Screenshot 2023-05-18 at 11 37 54<br>

Screenshot 2023-05-18 at 11 36 30

**Comment by jasmussen** [comment]
That may be a better interim fix. Did you scale it down or just move it? And how does it look in context of the document actions on the right? You can try [here](https://www.figma.com/file/PVjCcceB5jEVHX31wgcjPS/6.3-North-Star?type=design&node-id=888%3A61125&t=MKbCvsi6M7dH6dyH-1) as a quick fix.

**Comment by paaljoachim** [comment]
It is a good idea to make it a little smaller. As comparing the external link to the desktop preview icon is an obvious size difference. I do wonder... There is the external link icon in the Post Editor and in the Templates there is the View button. Should the View button in the site editor be switched with the External preview icon?

**Comment by jameskoster** [comment]
I redrew the whole icon based on the metrics in others like `layout`, `drawer`, etc. 

Here's how it looks in the top bar:

Screenshot 2023-05-18 at 13 54 52

And the View menu @paaljoachim mentioned:

Screenshot 2023-05-18 at 13 56 11

**Comment by jasmussen** [comment]
That seems like a safer starting point. Feel free to push to this branch, or open a new that I can green light, happy to close this one in favor of another.

**Comment by jameskoster** [comment]
Pushed 👍

**Comment by jasmussen** [comment]
Thank you. But I can't green check my own 🙈 — but you have my blessing to give this one a green check :)

**Review by jameskoster — APPROVED** [review]
Haha. Approved!

**Review by mirka — APPROVED** [review]
And here's a before/after as it pertains to the `ExternalLink` component:

| Before | After |
|--------|-------|
|ExternalLink component, old icon|ExternalLink component, new icon|

**Comment by richtabor** [comment]
Looks ace.

**Pull request merged**
