### PR TITLE
Remove classic block code used to support WP 4.9

### PR DESCRIPTION
**Pull request by youknowriad**
I'm just following what's written on the comment :) 
It seems this code was committed to Core directly.

### CODE REVIEW

**Review by ZebulanStanphill — APPROVED** [review]
Quickly checked on a WP 5.5 dev environment to make sure the kitchen sink button still appeared and worked as expected on the Classic block. This looks good to go. :+1:

**Comment by Soean** [comment]
I have a similar PR #21004, Andrew added the comment that we can remove the ref in line 262.

**Comment by azaozz** [comment]
Looks good :)

As far as I remember the reason that code wasn't removed at the time was that Gutenberg still supported WP < 5.0.

**Comment by youknowriad** [comment]
@Soean sorry I missed that one. looks like it needs a rebase, so I'm just going to merge this one instead.

**Pull request merged**
