### PR TITLE
Experiment: Make block "synced" status applicable to all controlling blocks

### LINKED ISSUE #43261: Synced blocks: Define them as such in the Inspector
Related to https://github.com/WordPress/gutenberg/issues/42482 and https://github.com/WordPress/gutenberg/issues/32163.

When you select a template part or reusable block, it might be nice to clarify their global / synced nature – and perhaps outline usage – in the Inspector.

### PR DESCRIPTION
**Pull request by getdave**
## What?

Extends and improves visual affordances applied to more types of "synced" blocks:
- Updates blocks determined to be "synced" with appropriate visual affordances.
- Adds a "Synced" indicator to the block's card in the Inspector Controls panel.
- Adds the purple outline to all synced blocks (not just Reusable and TPs).

Closes https://github.com/WordPress/gutenberg/issues/43261.

## Why?

Currently only Reusable blocks and Template parts are given the visual affordances associated with being "synced". However other blocks may also benefit from this including the Navigation block.

This PR explores how that might look.

## How?

Updates the logic determining what constitutes "synced" to be whether or not the block's inner blocks are "controlled". Originally the block type was the determining factor in this.

## Testing Instructions

Try out various types of synced blocks and look out for the purple visual affordances given to these. They include:

- template parts
- reusable blocks
- navigation blocks (only those with an associated Navigation Menu).

## Screenshots or screencast 
Screen Shot 2022-12-08 at 16 34 27

### CODE REVIEW

**Comment by getdave** [comment]
I have a sense that @talldan mentioned that `areInnerBlocksControlled` isn't suitable for doing this kind of checking. I've searched high and low but I can't now find where he said that...

**Comment by scruffian** [comment]
This looks like a great start. I think the outline for the navigation block should always be purple. I can get into positions where the outline is still blue:
Screenshot 2022-12-08 at 17 07 25
Screenshot 2022-12-08 at 17 07 11

**Comment by scruffian** [comment]
cc @glendaviesnz who worked on this originally.

**Comment by ajlende** [comment]
It looks like the purple outline isn't shown when in the post editor, but it is in the site and template part editor. 

@scruffian how else were you able to get the blue outline?

**Comment by scruffian** [comment]
> @scruffian how else were you able to get the blue outline?

it happens when other blocks are selected and I hover the nav block...

**Comment by talldan** [comment]
> I have a sense that @talldan mentioned that areInnerBlocksControlled isn't suitable for doing this kind of checking. I've searched high and low but I can't now find where he said that...

I think this is a good use case for it. I do support using that selector, as it's good to make this feature work dynamically.

Though I think initially the synced block purple color was supposed to only apply to template parts and reusable blocks. @jameskoster might know more about whether it should apply to the navigation block.

**Comment by glendaviesnz** [comment]
> Though I think initially the synced block purple color was supposed to only apply to template parts and reusable blocks. @jameskoster might know more about whether it should apply to the navigation block.

As a bit of background, when I initially implemented this in the list view I showed everything under a template or reusable block as purple as [my thinking was](https://github.com/WordPress/gutenberg/pull/45473#issuecomment-1320998575) that if it was contained within a synced block it was essentially itself synced, ie. a group within a template part is just as 'synced' as the parent template in a way - but @jameskoster wanted to avoid any confusion and just color the template and reusable parents. Adding other blocks like Navigation makes sense to me though as editing its children has the same impact as editing the children of a template or reusable block.

**Comment by jameskoster** [comment]
> but @jameskoster wanted to avoid any confusion and just color the template and reusable parents

Just to clarify: If all the children have purple icons too then there's no way to quickly identify nested synced blocks. Navigation is a perfect example since it's common to find Navigation blocks inside Headers and Footers. We figured the purple tinted background was an adequate indicator that blocks inside the synced parent are inherently synced as well.

**Comment by getdave** [comment]
The motivation here is that Navigation _is_ synced. Its children are often synced with an entity just like Template Part and Reusable blocks.

At the moment it's impossible to easily tell when a Nav block is syncing its children. With this change we'd have clearer visual cues.

Is this pattern exclusive to TPs and RBs?

**Comment by jameskoster** [comment]
> Is this pattern exclusive to TPs and RBs?

No, but there's a nuance to consider before applying it to the Navigation block, see: https://github.com/WordPress/gutenberg/issues/43261#issuecomment-1344280578

**Comment by talldan** [comment]
I mentioned it in #46416 as well, but one thing worth noting about the technical approach is that https://github.com/WordPress/gutenberg/pull/46416 makes the Page List a controlled block. If both this PR and that one were merged, Page List would be shown as synced in the UI.

In some ways that is right. Page List is technically 'synced' to the user's page hierarchy. On the other hand, this isn't something that can be edited or saved in the editor, so it differs from other synced blocks.

**Comment by getdave** [comment]
Following on from discussions in https://github.com/WordPress/gutenberg/issues/43261#issuecomment-1346307486 let's avoid making Nav block one of the "synced" blocks. For that reason let's close this PR out.

That said we could still explore using the status indicator in the inspector controls for template parts and reusable blocks. Let's do that in a followup.

Todo:

- [ ] Explore status indicator for TPs and RBs in a followup.
- [ ] Apply the purple "synced" color to the Nav block (both for any clickthrough overlays applied, but also to the icon and select state in the inspector).

**Comment by getdave** [comment]
> * Apply the purple "synced" color to the Nav block (both for any clickthrough overlays applied, but also to the icon and select state in the inspector).

@glendaviesnz I saw you were working on the colorizing. Do you have any guidance for how you'd prefer I go about the above?

**Comment by glendaviesnz** [comment]
> > * Apply the purple "synced" color to the Nav block (both for any clickthrough overlays applied, but also to the icon and select state in the inspector).
> 
> @glendaviesnz I saw you were working on the colorizing. Do you have any guidance for how you'd prefer I go about the above?

As the existing purple colorizing is based on blocks being `synced` via the [this criteria](https://github.com/WordPress/gutenberg/pull/45473/files#diff-e55a90514728517e51db82d300641d7e654079708945ff7bef781cc4477d4d42R52), and because it states above `let's avoid making Nav block one of the "synced" blocks`, maybe we need a different term to describe why the purple is applied? 

Also, currently the check to see if is a template or reusable block happens in a couple of places, so if we are adding to this list of possible blocks maybe we should add a single selector that does this check? `isColorizedBlock`  - or whatever term we come up with to describe it?

**Comment by getdave** [comment]
> `isColorizedBlock` - or whatever term we come up with to describe it?

Yes I noticed the check was in a few places. We going to need to come up with a term. Perhaps it's `isClickThrough` - as that's what design folks were asking for me to add to the Nav block alongside the colour.

**Comment by glendaviesnz** [comment]
> Yes I noticed the check was in a few places. We going to need to come up with a term. Perhaps it's isClickThrough - as that's what design folks were asking for me to add to the Nav block alongside the colour.

`isClickThrough` doesn't seem to relate to the nature of template and reusable blocks, but I can't think of a meaningful term that covers both - maybe design have some ideas given that they see the purple as representing all 3 types of blocks? ... not that the name is too critical as only in code, so maybe the existing `isSynced` is good enough?

**Pull request closed without merging**
