### PR TITLE
Only show inline boundaries on focus

### PR DESCRIPTION
**Pull request by ellatrix**

### CODE REVIEW

**Comment by jasmussen** [comment]
Testing this, I see no difference in behavior of the inline boundaries. Which I assume is good! So if this is the intended behavior, the change looks tiny so 🚢

**Comment by iseulde** [comment]
@jasmussen Could you test the following in both master and this branch?

Put the cursor in a link, then put it in a different Editable or block.

In master the boundary should still be visible. In this branch it should disappear.

Is this correct?

**Comment by jasmussen** [comment]
This is what I see in the branch:

branch

This is what I see in master:

master

Can't really tell the difference tbh.

**Comment by iseulde** [comment]
> Can't really tell the difference tbh.

So in the top GIF, the link background shows up, then disappears after you put the caret in a different block. In the bottom GIF is stays. The top is the behaviour we want right? Can you see the difference now?

**Comment by jasmussen** [comment]
Ah right! Solid! Ship it!

**Comment by aduth** [comment]
Nice easy fix 👍

**Pull request merged**
