### PR TITLE
wp-env: Make env-cwd option work on Windows

### PR DESCRIPTION
**Pull request by t-hamano**
## What?

This PR fixes an issue where scripts that include the `--env-cwd` option fail when executed on Windows OS. This allows commands such as `lint:php` and `format:php` to work correctly on Windows OS.

## Why?

For example, when you run `lint:php`, the `other:update-packages.php` script is executed before that. When running this script, the following error occurs on Windows OS:

```
npm run lint:php

> gutenberg@17.0.2 prelint:php
> npm run other:update-packages:php


> gutenberg@17.0.2 other:update-packages:php
> wp-env run --env-cwd='wp-content/plugins/gutenberg' cli composer update --no-interaction

i Starting 'composer update --no-interaction' on the cli container.

OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/var/www/html/'wp-content/plugins/gutenberg'") set in config.json failed: no such file or directory: unknown
× Command failed with exit code 126
Command failed with exit code 126
```

Notice that the path includes single quotes (`"/var/www/html/'wp-content/plugins/gutenberg'"`). I don't know the exact cause, but I suspect that single quotes are handled differently in Windows OS.

## How?

I have confirmed that both formats below work on Windows OS. Although I don't have a strong opinion on the format, I chose the first option.

- `"test": "wp-env run --env-cwd=\"wp-content/plugins/gutenberg\" cli composer update --no-interaction"` (escape double quote)
- `"test": "wp-env run --env-cwd=wp-content/plugins/gutenberg cli composer update --no-interaction"` (don't use quote)

## Testing Instructions

I only have a Windows machine, but I would be happy if you could confirm that commands such as `lint:php` and `format:php` work as usual on Linux and MacOS.

### CODE REVIEW

**Comment by ObliviousHarmony** [comment]
> Notice that the path includes single quotes ("/var/www/html/'wp-content/plugins/gutenberg'"). I don't know the exact cause, but I suspect that single quotes are handled differently in Windows OS.

It's because Windows treats single quotes as a literal character instead of a special one. This is normally fine and interpreted by Linux correctly but here it's a problem because `/var/www/html` is prepended for relative `--env-cwd` paths. How would you feel about instead trimming single (and double?) quotes from that option in `wp-env` when concatenation takes place?

**Comment by t-hamano** [comment]
> How would you feel about instead trimming single (and double?) quotes from that option in `wp-env` when concatenation takes place?

Does this mean, for example, removing single quotes on the env package side as shown below? This approach also seems to work on Windows.

```diff
diff --git a/packages/env/lib/cli.js b/packages/env/lib/cli.js
index 1788315b60..df8d1830e7 100644
--- a/packages/env/lib/cli.js
+++ b/packages/env/lib/cli.js
@@ -205,6 +205,7 @@ module.exports = function cli() {
                                default: '.',
                                describe:
                                        "The command's working directory inside of the container. Paths without a leading slash are relative to the WordPress root.",
+                               coerce: ( value ) => value.replace( /'/g, '' ),
                        } );
                        args.positional( 'container', {
                                type: 'string',
```

**Comment by ObliviousHarmony** [comment]
> Does this mean, for example, removing single quotes on the env package side as shown below? This approach also seems to work on Windows.

Looks great @t-hamano. One consideration is that this should only remove single quotes from the beginning and end of the path. Another thought along these lines too is whether or not paths with spaces in them work too.

**Comment by t-hamano** [comment]
> One consideration is that this should only remove single quotes from the beginning and end of the path. Another thought along these lines too is whether or not paths with spaces in them work too.

I changed it to remove the leading and trailing single quotes and spaces. I have confirmed that most commands work on Windows and Linux.

```json
{
  "scripts": {
    "no-quote": "wp-env run tests-wordpress --env-cwd=wp-content/plugins/gutenberg pwd",
    "has-quote": "wp-env run tests-wordpress --env-cwd='wp-content/plugins/gutenberg' pwd",
    "has-escaped-quote": "wp-env run tests-wordpress --env-cwd=\"wp-content/plugins/gutenberg\" pwd",
    "has-quote-inside-with-escaped-quote": "wp-env run tests-wordpress --env-cwd=\"wp-content/plugin's/gutenberg\" pwd"
  }
}
```

There are other scenarios where the results differ depending on the OS. The following command works on Windows, but has syntax errors on Linux.

```json
{
  "scripts": {
    "has-quote-inside": "wp-env run tests-wordpress --env-cwd=wp-content/plugin's/gutenberg pwd"
  }
}
```

On the other hand, a command like the one below works correctly on Linux, but cannot be processed on Windows because an empty string is passed to coerce.

```json
{
  "scripts": {
    "has-space-before": "wp-env run tests-wordpress --env-cwd=' wp content/plugins/gutenberg' pwd",
    "has-space-after": "wp-env run tests-wordpress --env-cwd='wp content/plugins/gutenberg ' pwd"
  }
}
```

**Comment by ObliviousHarmony** [comment]
Thanks for the investigation @t-hamano. On the subject of the failures themselves, are these local terminal syntax errors or remote errors? I'm just curious whether or not the problem is the input being passed _to_ `wp-env` (unfixable) or the way we're handling the input when we give it to Docker (fixable).

**Comment by t-hamano** [comment]
Another approach: I made the trimming of spaces and quotes to be handled just before `spawnCommandDirectly()` is executed. This approach also seems to successfully remove the single quotes and pass the intended path to Docker.

> I'm just curious whether or not the problem is the input being passed to wp-env (unfixable) or the way we're handling the input when we give it to Docker (fixable).

If I understand correctly, this approach is what fixes the latter, right?

**Comment by ObliviousHarmony** [comment]
> This approach also seems to successfully remove the single quotes and pass the intended path to Docker.

Sounds good to me @t-hamano. The duplication of `envCmd` is probably unnecessary though, maybe we can do this transformation above? We can do it before we concatenate for the relative path.

**Comment by t-hamano** [comment]
@ObliviousHarmony

In [b512390](https://github.com/WordPress/gutenberg/pull/56265/commits/b51239091109707a6d9bfafdb8a3d720885a0ff4), I made the transformation to be performed directly at the point where the paths are concatenated. I may not be understanding your intent correctly, but is this correct?

**Review by ObliviousHarmony — APPROVED** [review]
That's perfect @t-hamano. I might suggest a comment explaining what the transformation is for but this works.

Thanks!

**Comment by t-hamano** [comment]
> I might suggest a comment explaining what the transformation is for but this works.

Indeed, I added a comment 👍

**Pull request merged**
