### PR TITLE
Add PHPUnit coverage config and Composer scripts

### PR DESCRIPTION
**Pull request by jaswrks**
## Description
Configures code coverage analysis for PHP. See: https://github.com/WordPress/gutenberg/issues/4796

## Next Actions
- [x] Add a whitelist for code coverage in the `phpunit.xml.dist` file.
- [x] ~~Add new NPM scripts that run code coverage analysis for PHP code.~~
- [x] ~~Document the new NPM scripts.~~

---

- [x] Use Composer for PHP scripts and use codecov.io
  - [x] Find out if codecov.io can generate reports for both JS and PHP in a single project.  
  **Yes**
  - [x] If that's possible, determine what format PHPUnit needs to output for codecov.
  **Clover XML, see [PHP example for codecov](https://github.com/codecov/example-php)**
  - [x] Determine where the output needs to be directed for codecov.  
  **Anything matching `*coverage.xml` in the repo directory, however deep.**
  - [x] Mirror all existing `package.json` scripts that are PHP-specific, now available in `composer.json`, and can be run via `composer run-script`, now the recommended way.
  - [x] Update relevant docs and suggest the use of `composer run-script` instead of `npm run` when it comes to anything PHP-specific.
  - [x] Add additional scripts in `composer.json` that deal with code coverage analysis via PHPUnit.
  - [x] `bin/run-wp-unit-tests.sh` now accepts `--coverage` as an optional argument to trigger coverage analysis in CI builds.
  - [x] Adjust `.travis.yml`. Perform a code coverage analysis & send to codecov.io.

**This was a blocker:**

- [x] Work around bug in the `cli` docker image, see: https://github.com/docker-library/wordpress/issues/279. Run commands in the `cli` docker image as UID `33` explicitly. Changed in `bin/install-docker.sh`. See: https://github.com/WordPress/gutenberg/pull/4797/commits/92ef33abe044b27ff54ebdcfe08c1ce9591305f3 ~ Also opened a separate issue for this in https://github.com/WordPress/gutenberg/issues/4893
- [x] Follow up on https://github.com/WordPress/gutenberg/issues/4893 and determine if the fix I used here will be the right one, before merging. **Looks like it'll work. PR'd by `@aduth` in https://github.com/WordPress/gutenberg/pull/4892**

## How can this be tested?

Note the new PHP [code coverage analysis](https://codecov.io/gh/WordPress/gutenberg/tree/add%2Fphpunit-coverage-config-scripts/lib) at codecov.io.

### Local Testing

This command runs a lint check and unit tests.

```bash
composer run-script test
```

runs a lint check and unit tests with coverage analysis.

```bash
composer run-script test:coverage
```

runs a lint check only.

```bash
composer run-script lint
```

runs a lint check outside docker; i.e., simply calls `/vendor/bin/phpcs`.

```bash
composer run-script phpcs
```

The rest of these run unit tests only, with coverage, no lint check:

```bash
composer run-script test-unit:coverage
```

For more detailed HTML output in `coverage/phpunit/index.html`, run:

```bash
composer run-script test-unit:coverage-html
```

To run the same analysis with a multisite network:

```bash
composer run-script test-unit-multisite:coverage
```

For more detailed HTML output in `coverage/phpunit/multisite/index.html`, run:

```bash
composer run-script test-unit-multisite:coverage-html
```

### CODE REVIEW

**Comment by ntwb** [comment]
A couple of things, I'm wondering if this should be a script in `composer.json`?

Also, what should we do with the generted coverage? Can ''codecov'' support poth PHP and JS in the one set of coverge reports somehow?

**Comment by jaswrks** [comment]
@ntwb Thank you for reviewing.

> ... should be a script in composer.json?

I agree. There's some other PHP-related scripts in [package.json](https://github.com/WordPress/gutenberg/blob/master/package.json#L136) though. Maybe the thinking was that it would be easier to maintain if they're all in the same place.

> Can ''codecov'' support poth PHP and JS in the one set of coverge reports somehow?
> Also, what should we do with the generted coverage?

Looks like they do support PHP. I haven't explored it much further than [this page](https://github.com/codecov/example-php) yet, but from a quick glance it would seem that it depends on PHPUnit and the clover output format.

I find the default text output to be helpful locally. For the CI server, it looks like outputting in the clover format to a `coverage.xml` in the root of the repo might be the way to go.

I'll take a closer look soon.

**Comment by jaswrks** [comment]
I updated the outline above to show recent changes.

- Note the new PHP [code coverage analysis](https://codecov.io/gh/WordPress/gutenberg/tree/add%2Fphpunit-coverage-config-scripts/lib) at codecov.io.

I'd love another pair of eyes on the last item in the list above that I marked as a blocker. I uncovered a problem in the `install-docker.sh` script. See: https://github.com/WordPress/gutenberg/issues/4893. I went ahead and fixed it in this PR so I could get the code coverage analysis to work, but I also opened a separate issue as well.

**Comment by jaswrks** [comment]
I rebased this following Andrew's fix in https://github.com/WordPress/gutenberg/pull/4892.
This is ready for review.

**Comment by ntwb** [comment]
This is looking great, adding PHP coverage to the existing codecov is 👌 

Sadly I can't review it for a few more days, possibly not even until next week

Related: [#WP43067](https://core.trac.wordpress.org/ticket/43067)

**Comment by ntwb** [comment]
Apologies for not following up here @jaswrks, can you resolve the `package.json` conflict and I'll take it all for another test drive please :)

**Comment by jaswrks** [comment]
No worries. Thanks for checking in on this. I resolved conflicts in `package.json`.

***Note:** If you see two different authors (two avatars) in my commits to this branch it's because I changed my email address on GitHub since I started work on this. It might say something like "Jason Caldwell and jaswrks". Both are me and the most recent commit should be marked 'verified'.*

**Comment by danielbachhuber** [comment]
@jaswrks @ntwb Is this PR still relevant or can it be closed? I don't see it as entirely necessary to add `composer` scripts for steps we already have covered in `npm`.

**Comment by jaswrks** [comment]
At the time this was being worked on there was a desire to move all of the PHP-related commands into `composer` for improved clarity and compatibility moving forward. I'm not sure if that sentiment still exists or not. My feeling is this is low priority, but still would be nice to have.

Thoughts?

**Comment by danielbachhuber** [comment]
> My feeling is this is low priority, but still would be nice to have.

I agree. I think it makes more sense to focus on the critical / necessary tasks at this point.

**Pull request closed without merging**
