### PR TITLE
Issue #6001 - remove label in the shortcode block

### PR DESCRIPTION
**Pull request by bobbingwide**
## Description
Removes the Label from inside the shortcode block.
- The icon was wrong anyway ( code-editor rather than shortcode)
- The text label of Shortcode was unnecessary
- It used up space
- It was inconsistent
- Not required now that there's a new visual indicator for block names.

## How Has This Been Tested?
Manually. 

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
I deleted some code.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by danielbachhuber — APPROVED** [review]
👍 Seems reasonable to me but I've flagged for a second review.

**Review by youknowriad — COMMENTED** [review]
Code looks good, just waiting for a design check @karmatosed @jasmussen to approve.

**Comment by afercia** [comment]
If I got it correctly, this PR removes the `<label>` element, if so I'd like to remind once again that any UI control needs to be labeled, especially form fields.

**Comment by danielbachhuber** [comment]
@afercia Can you suggest how the PR should be updated to include the label in the correct manner?

**Comment by afercia** [comment]
@danielbachhuber I need a few minutes to finish something and switch VVV installation. In the meantime, Id suggest everyone to not think just visually. Labels are meant to give UI controls and form fields an `accessible name`. This name is used by assistive technologies and it's required.
You wouldn't every build  form without properly associated `<label>` elements, right?
- screen readaers use labels to announce _what_ the field is about
- speech recognition software use the label to empowe user to voice command `click xyz` to focus,f or example, a form field or click a button
- *visible* text label ebnefit all users

**Comment by youknowriad** [comment]
Good catch @afercia I believe this could be replace with an `aria-label` on the PlainText component. Probably less optimal than a visible label but A good alternative if we want to keep it visually this way.

**Comment by jasmussen** [comment]
Noting that I polished the shortcode block, including the label, in https://github.com/WordPress/gutenberg/pull/5605

I will rebase off whatever happens in this PR, but figured I'd share the work in progress.

**Comment by bobbingwide** [comment]
The outer div for the shortcode block already has an `aria-label` in the same style of the outer `div` for a paragraph block.  At present there's not much difference between these blocks other than what the user types into them.  Ditto for a Heading block.  

Does that mean that the `textarea` field should have the same aria stuff as these blocks.  

Strip away the CSS padding around the text field and visually the blocks are very similar. 
I know nothing at all about a11y other than what I've heard from Graham Armitage.

image

Perhaps I'll learn something at #wcldn on Contributor day. If I don't then my Countdown and CSV blocks, both shown above, will fail the test.

**Comment by afercia** [comment]
The outer div is going to change in https://github.com/WordPress/gutenberg/pull/5709 ad needs an aria-abel because it's focusable, and it will have a proper ARIA role.
Non-editable blocks like the shortcode one are different from editable blocks, as they're made of form fields. Form fields need to be labeled. Basic HTML even before being a11y. See also my previous comment https://github.com/WordPress/gutenberg/pull/6033#issuecomment-380101895

**Comment by danielbachhuber** [comment]
Closing per https://github.com/WordPress/gutenberg/pull/6033#issuecomment-380117303

> The most simple thing in this case is to keep the label. Removing it is definitely an accessibility regression compared to the previous implementation.

**Pull request closed without merging**
