### PR TITLE
Global Styles: Update Block specific CSS label to include additional instructions.

### PR DESCRIPTION
**Pull request by jordesign**
## What?

This PR adds an additional sentence of text to the label for Block specific 'Additional CSS' in the Styles panel (Styles > Block > Paragraph > Additional CSS). 

This sentence provides context and instructions for the formatting of the CSS when it is in this mode (specific to a certain block type).

## Why?
Addresses *part* of https://github.com/WordPress/gutenberg/issues/49531 - providing additional details of how to use the CSS panel in this context.

## How?
Adds an additional bit of information to the label - to guide the user.

## Testing Instructions

1. Open the Site Editor and edit a template
2. Open the styles panel and go to Blocks > Paragraph (or another block) > Additional CSS.

## Screenshots or screencast 

Screen Shot 2023-04-06 at 7 20 06 am

### CODE REVIEW

**Comment by jordesign** [comment]
I'd be willing to expect the *exact* wording of the additional text could be reviewed and improved.

**Comment by annezazu** [comment]
Adding needs copy review as I agree that this could be refined a bit! Thanks for opening either way 💥

**Comment by provenself** [comment]
Sorry—just fixed our Github notification settings, so only seeing this now! Copy looks fine, but if there's any interest, I think we could do a minor tweak:

> Add your own CSS to customize the appearance of the %s block. You do not need to include a CSS selector, only the property and value.

**Comment by kristastevens** [comment]
Hello @jordesign! Can we get the "Needs Copy Review" label removed here? This GH issue keeps popping up in our Slack channel and we've satisfied it. (I tried to figure out how to remove the label myself, but I don't seem to have the option of doing so.) Thanks so much!

**Comment by jordesign** [comment]
@kristastevens  - sure can! Sorry about that.

**Comment by kristastevens** [comment]
No worries at all! Thanks so much, friend!

**Comment by apeatling** [comment]
@jordesign Are you able to rebase this one? If not I can help assuming this is still relevant.

**Comment by jordesign** [comment]
Hey @apeatling have updated this one - as it turns out the structure/location of that string needed to change anyway since I first issued this PR.

Fingers crossed - it should be good to go now.

**Review by apeatling — APPROVED** [review]

**Comment by apeatling** [comment]
Looks good, I'm re-running the tests since they didn't pass and it seems unrelated to this PR.

**Comment by jordesign** [comment]
@apeatling  Looks like it is still failing on some kind of linting error I can't figure out I'm afraid :)
https://github.com/WordPress/gutenberg/actions/runs/6193057817/job/16834334818?pr=49626

**Comment by apeatling** [comment]
Turns out it was the double space in the string causing it to fail. Took a little while to track down. 😅

**Comment by jordesign** [comment]
Awesome - thanks so much for sorting that out :)

**Pull request merged**
