### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by SOFTowaha**
Ref: https://2019.bangkok.wordcamp.org/speaker/syed-omar-faruk-towaha/

## Description

Added my name to this list; 
This is me : https://www.google.com/search?q=towaha
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by nerrad** [comment]
Hi there!

This `CONTRIBUTORS.md` file is a list of contributors specifically to the _Gutenberg_ project.  Can you clarify how you've contributed to this project?  Note: it's not clear from linking to a speaker profile whether or not you spoke on a topic involving Gutenberg or not.

**Comment by SOFTowaha** [comment]
Yeah sure;
I maintain this blog: https://gutendev.com/ ; its all about Gutenberg and I made few plugins too; 
I do give support to the people who feel hard to use the Block Editor; I am currently working on a theme based on Gutenberg in my free time; You can have a peek: http://blocklab.gutendev.com/

**Comment by nerrad** [comment]
While I think it rocks you write on gutenberg and help others with gutenberg, the contributors file is more for _direct_ contributions to the project as opposed to indirect contributions like what you describe.   I'll leave this and will see if someone else will weigh in.

**Comment by nerrad** [comment]
For now I'm going to close this.  As noted, the project does limit the scope of who gets added to this file to those who have made direct contributions to the project.  This in no way diminishes your indirect contributions and they are _much_ appreciated!  Keep up the awesomeness 👍

**Comment by SOFTowaha** [comment]
Hi

Can you be more specific?
What can be treated as a direct contribution?

**Comment by nerrad** [comment]
Direct contributions include things that have artifacts recorded in this repository.  So for instance the beginning of the `CONTRIBUTORS.md` file has this:

```
This list is manually curated to include valuable contributions by volunteers that do not include code, such as user testing, providing feedback, or mockups.
```

Examples of the above would be:

- meaningful testing of  new features and/or bug fixes and recording results on a ticket/issue that was tested.
- contributing meaningful feedback in issues/pulls that help progress that issue/pull.
- contributing design mockups that help towards the implementation of features in pull requests/issues.

Essentially _any_ contribution that is directly measurable via something in this repository.  Admittedly this is still a bit vague (and open to subjective interpretation) so I'm going to highlight that in a future #core-editor meeting in the WordPress Slack as something that maybe could be clarified a bit more.  At issue here is a fine balance because if we open up this file for including names of all who have contributed indirectly, then it essentially loses any meaning because _anybody_ who writes a blog devoted to Gutenberg, or who has helped someone with the new editor, or who has written a plugin/theme implementing/integrating with Gutenberg would be considered _eligible_.

**Comment by paaljoachim** [comment]
Hey @SOFTowaha 

This is what I do. I am not a dev more of a UI person and tester.
This is how I have contributed directly to Gutenberg.
- Suggested features. Most often including wireframes.
- Commented to lots of issues.
- Tested Gutenberg releases on occasion as they are released and gave feedback to them.
- Taken part in discussions during core editor chats.
and there are also likely other things I have done that I can not remember right now. I have contributed to Gutenberg since the very beginning.

Contributors on the list are most often it seems (I might be totally off) Developers who open and follow through with new Pull Requests that bring with it something meaningful contribution to Gutenberg. 

I also run a tutorial site and have written a few things about Gutenberg, but that is outside of the core contribution directly to Gutenberg.

For the last few releases I have not been added to the contributor list, as it seems it is harder to know who contributes to a release here on Github in comparison to the WordPress trac system. (Or so I vaguely remember @earnjam William told me.)

Anyhow. If you want to be added to the list get directly involved in contributing. Relax about being added to the contributors list. I kinda (got to say kinda) let go that I have not been added. As the point is not being added to the list but taking part in a community in improving the new editor in WordPress. That is heck of a cool experience. O there are also lots of good people here to connect with while being involved in various aspects of Gutenberg.

**Comment by SOFTowaha** [comment]
Hello @nerrad  and @paaljoachim ; 

Thank you for the clarification; 
Looking forward to contributing to this repository soon :)

**Pull request closed without merging**
