### PR TITLE
Fix the publishPost test util by preferring keyboard interaction

### PR DESCRIPTION
**Pull request by talldan**
## Description
While working on some end to end tests, I started seeing some failures with the following message:
```
    Node is either not visible or not an HTMLElement

      at ElementHandle._clickablePoint (../../node_modules/puppeteer/lib/JSHandle.js:221:13)
          at runMicrotasks (<anonymous>)
      at ElementHandle.click (../../node_modules/puppeteer/lib/JSHandle.js:282:20)
```

I've narrowed this down to the `publishPost` utility function. My thinking is that because the publish panel is animated, the test attempts to click the button while it's moving and misses the target.

The publish button is actually already focused when the publish panel is opened, so it seems safer to just press 'Enter' instead of trying to click the button. This also makes tests assert that focus is transferred correctly to the publish button when the panel is opened.

Changing this code resulted in my tests passing.

## How has this been tested?
Automated end to end tests should pass.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by draganescu — APPROVED** [review]
LGTM!

**Comment by talldan** [comment]
Thanks for the approval. It looks like the issue is that core tests should use `FORCE_REDUCED_MOTION=true` when running tests to disable animations, so I think rather than changing this function I'll look to implement that.

**Comment by draganescu** [comment]
How did you find this out?

**Comment by talldan** [comment]
I originally noticed that in the travis.yml file, and then tried running a test locally with the puppeteer interactive setting, and animations were disabled. They're not disabled in core e2e-tests when using the interactive setting. I think it'd be good to bring the two more in line so that the utils work consistently.

**Pull request closed without merging**
