### PR TITLE
ItemGroup: Update button focus styles to use `:focus-visible`

### PR DESCRIPTION
**Pull request by mikachan**
## What?

A small follow-up to https://github.com/WordPress/gutenberg/pull/51576, to use `:focus-visible` rather than `:focus` on the `ItemGroup` buttons.

## Why?

Addresses this comment: https://github.com/WordPress/gutenberg/pull/51576#discussion_r1236497651

## Testing Instructions

Navigate around the inserter menus using both a mouse and keyboard. The focus state should only apply when using a keyboard.

### CODE REVIEW

**Review by jasmussen — APPROVED** [review]
Nice one, thank you.

**Comment by ciampo** [comment]
we may have to rebase / merge trunk again to get rid of e2e failures

**Comment by mikachan** [comment]
I've added the 'Backport to Gutenberg RC' label as it would be nice if this was included in 16.1, since it's a follow-up to https://github.com/WordPress/gutenberg/pull/51576, which will be in 16.1 I believe.

**Comment by tellthemachines** [comment]
I just cherry-picked this PR to the release/16.1 branch to get it included in the next release: b909d9022c

**Pull request merged**
