### PR TITLE
Tools: Update the minimum Node.js version to 12

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Starting 2020-05-19 Node.js v10 is in maintenance mode.  In fact, Node.js v12 is now also in maintenance mode since 2020-11-30. Node.js v14 is active LTS, see:
https://github.com/nodejs/Release

I propose we drop support for Node.js v10 and lower in all WordPress packages, given that the dependent packages slowly start to drop support as well. 

 Example:

- `webpack-bundle-analyzer` starting from v4 increased minimum Node.js version to 10.13 (https://github.com/webpack-contrib/webpack-bundle-analyzer/blob/master/CHANGELOG.md#400).
- `wordpress-sources` starting from v2 increased minimum Node.js version to 10.13 (https://github.com/webpack/webpack-sources/releases/tag/v2.0.0).

In practice, it’s more like a recommendation rather than a strict contract as npm will only warn when you install packages that defined `engines` in `package.json` that aren’t satisfied by the current node or npm version declared.

This PR sets the minimum Node.js version recommended to v12 in the following packages that are part of `@wordpress/scripts` family:
- `@wordpress/babel-plugin-import-jsx-pragma`
- `@wordpress/babel-plugin-makepot`
- `@wordpress/babel-preset-default`
- `@wordpress/browserslist-config`
- `@wordpress/create-block`
- `@wordpress/custom-templated-path-webpack-plugin`
- `@wordpress/dependency-extraction-webpack-plugin`
- `@wordpress/e2e-test-utils`
- `@wordpress/e2e-tests`
- `@wordpress/eslint-plugin`
- `@wordpress/jest-console`
- `@wordpress/jest-preset-default`
- `@wordpress/jest-puppeteer-axe`
- `@wordpress/library-export-default-webpack-plugin`
- `@wordpress/npm-package-json-lint-config`
- `@wordpress/postcss-plugins-preset`
- `@wordpress/postcss-themes`
- `@wordpress/prettier-config`
- `@wordpress/scripts`
- `@wordpress/stylelint-config`

_Note:_ For consistency all tooling related packages get a minimum Node.js version set even when some of them are simple enough to ignore that.

## How has this been tested?
The following commands still work:
`npm run build`
`npm run dev`
`npm run lint-js`
`nom run test-unit`

### CODE REVIEW

**Comment by nerrad** [comment]
Just mentioning that I'm in favor of this change (haven't reviewed the code though).

**Comment by gziolo** [comment]
Let's give it a try. The failing e2e test is a known issue that pops up in the main branch as well.

**Comment by mkaz** [comment]
Just reviewing it now, was going to give it my :+1: and the option disappeared.
I don't see it a a concern, and still supporting the previous LTS is good.

**Comment by gziolo** [comment]
Thank you @nerrad and @mkaz for the feedback shared 👍🏻 
I figured out we can do a follow-up or even revert when something goes wrong.

**Pull request merged**
