### PR TITLE
Added a disable state to the trash button

### PR DESCRIPTION
**Pull request by abdel-h**
## Description
Related to issue #15755 
Added a state to the PostTrash component which disable the trash button after the first click so the button can't be clicked twice, the bug is more visible on slower networks.

## How has this been tested?
Using a very slow network. 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ]  I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by gziolo** [comment]
Did you see the comment from @afercia in the referenced issue?

> From an user interface perspective, I'd tend to think multiple clicks on the "Move to trash" button should be prevented. However, for accessibility reasons the button shouldn't be really disabled to avoid focus losses. I'd like to suggest to use the same pattern already used in other places in Gutenberg:

**Comment by devdivdev** [comment]
Hey @gziolo this is my first time doing a PR here, s i'm wondering if  all Travis CI tests should be successful before I can get feedback on the code ?

**Comment by gziolo** [comment]
Can you try to rebase your branch with the latest changes from `master`?

In case you need some help, there is docs:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#keeping-your-fork-up-to-date

It should resolve your issues.

**Comment by gziolo** [comment]
I think something went wrong with the merge, I see unrelated commits included in this patch.

**Comment by devdivdev** [comment]
Yes I just noticed, seems like everything between the first PR and now is here.

**Comment by devdivdev** [comment]
I think you can close this one @gziolo and I'll just create new one with the changes I have made.

**Comment by gziolo** [comment]
Sure thing @devdivdev, let me know when you have another PR ready 👍

**Pull request closed without merging**
