### PR TITLE
Block Editor: Optimize 'Connections' inspector controls

### PR DESCRIPTION
**Pull request by Mamaduka**
## What?
This is similar to #55721.

A micro-optimization for "Connections" inspector controls to avoid calling `useBlockEditingMode` for every block rendered in the editor.

## Why?
This is an effort to minimize unnecessary store subscriptions created per block. See https://github.com/WordPress/gutenberg/pull/54819#issuecomment-1761202859.

P.S. While the feature is hidden behind the experimental flag, I think it's good to ship similar optimizations early.

## How?
I extracted the primary logic into a separate component, only rendered when a block supports `connections` and is selected.

## Testing Instructions
1. Got to `wp-admin/admin.php?page=gutenberg-experiments`
2. Example the "Connections" experiment.
3. Open a post.
4. Insert a paragraph block.
5. The "Connections" inspector panel should be displayed in the sidebar.

### Testing Instructions for Keyboard
Same.

### CODE REVIEW

**Comment by Mamaduka** [comment]
@c4rl0sbr4v0, I couldn't test the controls with the Image block; the panel isn't rendered for it. I can reproduce the same behavior on `trunk', which is worth debugging separately.

**Review by SantosGuillamot — APPROVED** [review]
Thanks a lot for the optimization! I've tested it and everything seems to be working fine for the paragraph 🙂 We are about to refactor the whole "connections" experiment and we must keep this in mind.

**Comment by Mamaduka** [comment]
Thanks for the review, @SantosGuillamot!

**Comment by michalczaplinski** [comment]
Thanks @Mamaduka! The optimization makes sense to me 👍

**Pull request merged**
