### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Updates the documentation for the schemas to match #37269 

- Update URLs to use the new short format
- Remove mention of SchemaStore as a place that needs updating
- Add example for selecting a version
- Add notes about where to find a list supported editors

Note that the version URL in the example will only work once #37269 is merged.

## How has this been tested?

Read through the new docs and check for spelling/grammar and that everything makes sense.

## Types of changes

Documentation

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by mkaz** [comment]
Do you think we should mention editors by name or at least the most popular ones?

How about something like this for the last paragraph:

> For two popular editors, Visual Studio Code requires adding the `$schema` property, but PHPStorm automatically looks up the schema from the SchemaStore.org based on the file name. Some editors require a plugin installed, check your editor's documentation for details. Additionally, [SchemaStore.org](https://www.schemastore.org/) and [JSON Schema](https://json-schema.org/implementations.html#editors) have lists of editors known to have support.

**Comment by ajlende** [comment]
> Do you think we should mention editors by name or at least the most popular ones?

I avoided it because I wasn't sure if endorsing any specific editors was something that should be done in the docs, especially paid or closed source ones like PhpStorm and VSCode.

Technically both VSCode and PhpStorm support the `$schema` property which is why I left it at "Many popular editors recognize...".

VSCode allows setting the schema in settings.json, but it will be overridden by a `$schema` defined in the file.

Intellij IDEA Community (which _should_ work the same as PhpStorm) will automatically look up the schema based on the SchemaStore catalog (so the trunk version), but `$schema` overrides that value if you want a different version, and you can override the `$schema` value in the settings.

If you don't think it's a problem, I can shout out VSCode and PhpStorm if that's what most folks are using.

**Comment by mkaz** [comment]
I don't see it as an endorsement, just recognizing that people are using them, and this is how it's done for those.

**Comment by gziolo** [comment]
That’s a great way to make this README file to play nicely with the `wp/5.8` branch 👌

**Comment by ajlende** [comment]
@mkaz I didn't bother mentioning the auto-setup for PhpStorm because `$schema` still works, the instructions are a bit simpler this way, and it's probably not a bad idea to encourage `$schema` usage since it is supported in multiple editors.

**Review by mkaz — APPROVED** [review]
👍

**Pull request merged**
