### PR TITLE
Update has-text has-icon button spacing

### PR DESCRIPTION
**Pull request by jameskoster**
## What?
Updates the padding applied the `has-text has-icon` buttons. Also reduces the spacing between label + icon, and uses `gap` rather than `margin`.

## Why?
The current spacing feels a but unbalanced. `gap` works better for RTL compared to left/right margin.

## How?
CSS.

## Testing Instructions
Observe equal left/right padding applied to `has-text has-icon` like the View button in the Top Bar.

## Comparison

| Before | After |
| --- | --- |
| Screenshot 2023-05-03 at 09 18 21 | Screenshot 2023-05-03 at 09 26 08 |

Note: The outline in the screenshot above is for illustrative purposes only. Here's how the button actually appears:

button

### CODE REVIEW

**Comment by jasmussen** [comment]
Hah, nice. Is this similar to #50241?

Agreed, gap is nice. The left padding in this case does not look balanced in either before or after, though

Screenshot 2023-05-03 at 11 21 22

I know that's likely partially due to the visible area of the icon, and the built in clearance. But perhaps a grid unit 10 padding left, instead of grid-unit-15?

**Comment by jameskoster** [comment]
Oh yes, pretty similar :)

> I know that's likely partially due to the visible area of the icon, and the built in clearance.

Yes that's it. To get visually correct spacing with _most_ of the core icon set, the spacing on the left should be 4px less than the spacing on the right. We can do that, but there will always be exceptions to the rule that will look strange. I suppose that's the preferred trade-off though. I'll push an update.

**Review by apeatling — APPROVED** [review]
Looks good to me 👍

**Comment by jasmussen** [comment]
Needs a rebase! Thanks Jay.

**Pull request merged**
