### PR TITLE
RN: Add width settings to button block

### PR DESCRIPTION
**Pull request by enejb**
This PR adds a width selection slider to the button block. 

## Description
It does so by using the `UnitControl` component. That is currently being used by the column width selection.

## How has this been tested?
1. Load this PR in the demo app or your flavour of mobile app.
2. Add a buttons block. 
3. Select the settings of a single button.
4. Change the width by dragging the slider. (See screenshot)
5. Notice the width change.

## Screenshots 
Current web implementation (notice the right sidebar, button group 25%,50%,75%,100%) 
Screen Shot 2021-01-25 at 12 13 46 PM

Currently implemented. 
Screen Shot 2021-01-25 at 12 12 00 PM

Based on the `UnitControl` that looks like this in the column settings.
Screen Shot 2021-01-25 at 12 12 19 PM

## Types of changes
This PR add the ability to the mobile UnitControl component to only use a single unit. ? 
Maybe this can be simplified?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@enejb If the web control is a Button group, we should probably use one of the following controls on mobile:

- A list view with the 4 options (of which only 1 can be selected)
- A [picker](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/) (not sure if this is even possible on the Android side?)
- If we keep the slider, I would suggest limiting the slider increments to the same 4 discrete stops — 25, 50, 75, and 100 percent

**Comment by enejb** [comment]
Of the 3 options @iamthomasbishop which one should I explore first? 

> A list view with the 4 options (of which only 1 can be selected) 

Currently on the web non are selected at the beginning and you are also able to not else one of the sizes here as well. 

I suggest we play around with the Picker option and see how that goes. Do you have any suggestions how it would work/look anything that works similar already?

**Comment by iamthomasbishop** [comment]
> Of the 3 options @iamthomasbishop which one should I explore first?

> I suggest we play around with the Picker option and see how that goes

@enejb I was thinking the same, but only if we have an easy path to implementation on Android. It looks like there are some third-party libraries:

- [react-native-picker/picker](https://github.com/react-native-picker/picker)
- [lawnstarter/react-native-picker-select](https://github.com/lawnstarter/react-native-picker-select)

The system-standard on Android for a Select box interaction is a Menu component, which looks like this:

<a href="https://user-images.githubusercontent.com/1200432/105775624-b54f3980-5f2c-11eb-8335-4c4365ed6251.png"></a>

I don't think we're using that system component anywhere, so I'm not sure if we can do that out of the box, but if we can achieve the above, this might be worth exploring first.

## Other approaches

Another option I should've mentioned is placing the option-selection on a nested or secondary sheet — either a sheet that appears _over_ the base sheet or a nested sheet that we transition to. Here are those two approaches visualized:

<a href="https://user-images.githubusercontent.com/1200432/105777202-9aca8f80-5f2f-11eb-85c1-2870f72c0737.jpeg"></a>

The other option — which seems like the simplest option, but definitely not the prettiest — would be a regular list (the first option I mentioned above). 

<a href="https://user-images.githubusercontent.com/1200432/105777008-3f989d00-5f2f-11eb-9405-aab291f9c730.png"></a>

**Comment by enejb** [comment]
@iamthomasbishop I ended up using a SelectControl

This is what it looks like.
Screen Shot 2021-01-25 at 9 41 35 PM
When there is nothing to select.

Screen Shot 2021-01-25 at 9 41 48 PM
When click on Auto you see this selection.

Screen Shot 2021-01-25 at 9 41 40 PM
When you click on 50%.
Notice that the width of the button updates right away as well.

**Comment by iamthomasbishop** [comment]
@enejb I think that component/interaction model should work, but I have a couple of small requests:

- Is it possible to add a checkmark icon to the active item on the ActionSheet/BottomSheet?
- Can we add `Button` to the start of the cell's title label? (i.e. `Button width`, sentence-case)
- Can we apply that same label ⬆️ as a title row on the ActionSheet?

Here's what that'd look like on both platforms:

<a href="https://user-images.githubusercontent.com/1200432/105907326-797aa980-5fea-11eb-901c-04a0b36395e4.png"></a>

**Comment by enejb** [comment]
I am not sure how possible it would be but I can try make the improvements :) and see how it goes. 🤞

**Comment by enejb** [comment]
After a bit of investigation. 
I am able to add a title. See 
Screen Shot 2021-01-26 at 5 36 32 PM

but I am not able to the checkmark as requested. The component used https://reactnative.dev/docs/actionsheetios RN component which doesn't provide a way to pass in the selected state. The underlying iOS component is https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/. 

I am exploring other options now that would allow us to have the something similar to the link/colour picker as the UI. 

As described by option 2.

**Comment by iamthomasbishop** [comment]
> I am not able to the checkmark as requested

Ah, okay. I think at one point we explored extending that library somehow, but we must have either not executed on it or used the BottomSheet instead (this was what we ended up doing for heading levels on the Heading block).

> I am exploring other options now that would allow us to have the something similar to the link/colour picker as the UI.

Ok, sounds good. I think that approach should work well here, probably my preferred method tbh.

**Comment by enejb** [comment]
@iamthomasbishop I continues this work on https://github.com/WordPress/gutenberg/pull/28543 PR.

**Comment by enejb** [comment]
Closing this since it isn't relevant any more.

**Pull request closed without merging**
