### PR TITLE
Fix: Image that is uploaded to an existing gallery does not appear in the edit gallery view

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Fixes: https://github.com/WordPress/gutenberg/issues/9073

While for normal images and other media types we add a logic  that updated the files selected each time the media modal is open, for the gallery case we had an if conditon that excluded it. Probably this if condition was added because for the gallery case the logic we had did not work.

I tried some ways to refresh the images that appear in the edit gallery frame and nothing worked besides rebuilding the frame.

This PR adds a check in the media upload component where each time before openning the media modal, if the type of media modal being shown is a gallery we verify if the value changed (selected images changed) and if yes we rebuild the frame before showing it. If the value did not changed we use the existing frame.

## How has this been tested?
I added a gallery block I select some images from the media library.
After I updaload another image to the gallery using drag & drop and another one using the upload button.
I pressed the edit gallery button and I verified all the images appear correctly (in master the last 2 uploaded images don't appear).
I checked the other media blocks still work as before.

### CODE REVIEW

**Comment by simison** [comment]
We're experiencing this same with our gallery -based Tiled gallery block and I'd expect other blocks adding images (slideshows etc) will have the same bug affecting them.

https://github.com/Automattic/wp-calypso/issues/28959

**Comment by jorgefilipecosta** [comment]
The was rebased and retested it seems ready. Let's try to get it on 5.2 release.

**Review by simison — APPROVED** [review]
I've been testing this with core gallery block as well with Tiled gallery block from Jetpack. 

Tested:
- adding new images by drag-drop
- adding new images via block's upload button
- re-organising images by dragging them in the media modal — and the order persists in media modal when opening it again.
- removing images via media modal

I'm not familiar with media modal code but in general, the code looks good. 👍

**Comment by jorgefilipecosta** [comment]
Thank you for the review @simison 👍

**Pull request merged**
