### PR TITLE
Try to improve block select performance (BlockSwitcher)

### PR DESCRIPTION
**Pull request by ellatrix**
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by ellatrix** [comment]
Surprisingly it improves typing more than select.

```
┌──────────────────┬──────────────────────────────────────────┬─────────────┐
│     (index)      │ 8e0403ee07c6b579853f8df8b7c5ad1856654f17 │    trunk    │
├──────────────────┼──────────────────────────────────────────┼─────────────┤
│       load       │                '8094 ms'                 │ '8575.2 ms' │
│       type       │                '33.49 ms'                │ '37.34 ms'  │
│     minType      │                '23.73 ms'                │ '31.82 ms'  │
│     maxType      │               '290.25 ms'                │ '298.83 ms' │
│      focus       │                '57.98 ms'                │ '60.82 ms'  │
│     minFocus     │                '34.2 ms'                 │ '36.97 ms'  │
│     maxFocus     │               '211.75 ms'                │ '195.06 ms' │
│   inserterOpen   │               '636.41 ms'                │ '684.51 ms' │
│ minInserterOpen  │               '588.39 ms'                │ '626.27 ms' │
│ maxInserterOpen  │                 '855 ms'                 │ '934.19 ms' │
│  inserterHover   │                '23.72 ms'                │ '24.65 ms'  │
│ minInserterHover │                '19.52 ms'                │ '21.44 ms'  │
│ maxInserterHover │                '30.24 ms'                │ '31.11 ms'  │
└──────────────────┴──────────────────────────────────────────┴─────────────┘
```

**Comment by ellatrix** [comment]
@youknowriad Seems to improve typing by 10%, not sure if it's worth doing.

**Comment by youknowriad** [comment]
Are there any downsides to the change? 10% in typing is great.

**Comment by youknowriad** [comment]
Maybe we should run a second time to confirm.

**Comment by ellatrix** [comment]
I re-ran the test. The downside is that we're not disabling the block switcher dropdown if there's no available transform. I think that's fine it we just put a message in the dropdown saying that there's no transforms. The checks for transforms is pretty heavy it seems.

**Comment by youknowriad** [comment]
I also think it's fine. cc @jasmussen for design confirmation there.

**Comment by jasmussen** [comment]
If we're looking at a consistent 10% performance improvement by removing the disabling of that button, we'd need a super good reason not to do it.

In my quick testing, it was very rare to not have a transformation, in most cases there's always at least group or columns available, and as pattern transforms expand. However I did find it for navigation item, and it needs a little visual love:

Screenshot 2021-05-06 at 13 05 48

So I pushed a little polish:

Screenshot 2021-05-06 at 13 12 45

Note that the indentation of the submenu that makes it look like it doesn't align with the block toolbar is a bit of a separate/existing issue.

**Comment by ellatrix** [comment]
The improvement is a bit less now (5%), not sure if it's worth having, but it's still something

```
┌──────────────────┬──────────────────────────────────────────┬─────────────┐
│     (index)      │ c27331e4e9ce611ad0b95b5107132ebd152cf87e │    trunk    │
├──────────────────┼──────────────────────────────────────────┼─────────────┤
│       load       │               '9445.4 ms'                │  '9246 ms'  │
│       type       │                '39.26 ms'                │ '41.31 ms'  │
│     minType      │                '32.3 ms'                 │ '34.42 ms'  │
│     maxType      │               '323.96 ms'                │ '347.26 ms' │
│      focus       │                '65.56 ms'                │ '67.68 ms'  │
│     minFocus     │                '39.75 ms'                │ '42.08 ms'  │
│     maxFocus     │               '207.55 ms'                │ '201.94 ms' │
│   inserterOpen   │               '753.85 ms'                │ '739.52 ms' │
│ minInserterOpen  │                '673.8 ms'                │ '669.03 ms' │
│ maxInserterOpen  │               '1044.76 ms'               │ '980.71 ms' │
│  inserterHover   │                '27.94 ms'                │ '28.84 ms'  │
│ minInserterHover │                '20.95 ms'                │ '23.04 ms'  │
│ maxInserterHover │                '40.56 ms'                │ '39.18 ms'  │
└──────────────────┴──────────────────────────────────────────┴─────────────┘
```

**Comment by youknowriad** [comment]
This is the third round of results, the second one was actually even less. Let's try another time to confirm.

**Comment by youknowriad** [comment]
While I like the change and theoretically we do less things but the numbers are not saying so.

**Comment by ellatrix** [comment]
@youknowriad Yes, it doesn't look much better. Close?

**Comment by youknowriad** [comment]
yep 👍

**Pull request closed without merging**
