### PR TITLE
Remove the experiment option for Block Theme Previews

### PR DESCRIPTION
**Pull request by okmttdhr**
## What?

Remove the flag that was hiding Block Theme Previews behind the experiment option, as we addressed issues in this comment https://github.com/WordPress/gutenberg/pull/50030#issuecomment-1527566673.

Related PRs: https://github.com/WordPress/gutenberg/pull/50030, https://github.com/WordPress/gutenberg/pull/50863

## Why?

Since I assume there's no blocker to remove the flag. Let me know if we have something! 🙏 

I refer to the following issues/feedback that we could work on them to improve the experience after this PR;
<details><summary>☂️ </summary>
<p>

- https://github.com/WordPress/gutenberg/issues/50692
- https://github.com/WordPress/gutenberg/issues/50920
- https://github.com/WordPress/gutenberg/issues/50921
- https://github.com/WordPress/gutenberg/issues/50749
- https://github.com/WordPress/gutenberg/issues/50918
- https://github.com/WordPress/gutenberg/issues/50919
	- #50986
- https://github.com/WordPress/gutenberg/issues/50713
- https://github.com/WordPress/gutenberg/issues/50712
- https://github.com/WordPress/gutenberg/pull/41836
- https://github.com/WordPress/gutenberg/issues/51017

</p>
</details> 

## How?

- Removed a setting field for `gutenberg-theme-previews`
- Removed the condition for the experiment

We will need to stop adding the `Preview` button when https://core.trac.wordpress.org/ticket/58190 lands, as it's written in https://github.com/WordPress/gutenberg/blob/release/15.8/lib/compat/wordpress-6.3/theme-previews.php#L56

### To see Block Theme Previews are working;

- Go to `/wp-admin/themes.php`
- Click the `Live Preview` button on a theme installed

or

- Open the Site Editor and add the following to your URL: ?theme_preview=[themePath] where themePath is the relative path to the theme you want to preview (e.g. twentytwentythree).

### To see that there's no Block Theme Previews option;

- Go to `/wp-admin/admin.php?page=gutenberg-experiments`

## Screenshots or screencast 

Screen Shot 2023-05-26 at 10 40 29

Screen Shot 2023-05-26 at 10 39 44

### CODE REVIEW

**Review by ajlende — APPROVED** [review]
LGTM 👍 

Nothing under the ☂️ seems like a deal breaker to me, but I'll hold off from clicking the merge button in case someone else has a different opinion.

**Comment by okmttdhr** [comment]
Thanks for your review!
I marked this PR as a draft since the GET variable `theme_preview` is something widely used in the WordPress context, and some 3rd parties may have conflicting uses. (e.g. WordPress.com is using `$_GET['theme_preview']` as well).

I'll create follow-up PRs to prevent that.

**Comment by okmttdhr** [comment]
CC: @scruffian @ajlende @draganescu 
I've made two changes before this PR merged.

- https://github.com/WordPress/gutenberg/pull/51221 prevents Block Theme Previews from changing non-theme-preview requests. 
- Also, I submitted https://github.com/WordPress/gutenberg/pull/51312 to change the URL query string name for more safety.

**Comment by scruffian** [comment]
I noticed that the button text for activating the theme has been modified and now doesn't make sense when you're previewing a theme:

Screenshot 2023-06-08 at 09 40 51

It would be good to fix this before we merge this PR.

**Review by scruffian — APPROVED** [review]
Now https://github.com/WordPress/gutenberg/pull/51361 is merged I think we can also bring this in.

**Pull request merged**
