### PR TITLE
Rich Text: Allow to extend format types

### PR DESCRIPTION
**Pull request by mmtr**
## Description
Add a new `richText.registerFormatType` filter to allow developers to extend a format type when it is being registered.

The approach explored here is based on the existing [`blocks.registerBlockType`](https://github.com/WordPress/gutenberg/blob/b612fe8616ce774af2ff1084af2e9af8b3de1de2/packages/blocks/src/api/registration.js#L101) filter.

This will be useful for scenarios where we want a plugin that customizes a default format (i.e. add a class to text using a specific format or show a button for toggling format that currently only supports keyboard shortcuts).

## How has this been tested?
I used the content of [this gist](https://gist.github.com/mmtr/57a352401583ef4b974a54a91b689fa5)  on the [Playground](https://github.com/WordPress/gutenberg/blob/2be9b5b25f2aeb4230838417641852cea525e820/CONTRIBUTING.md#playground) and verified I can see a button for toggling the underline format.

Screen Shot 2019-05-04 at 10 12 22

### CODE REVIEW

**Comment by gziolo** [comment]
It's possible to use `unregisterFormatType` which returns the object with the definition of a given format type and `registerFormatType` to modify an existing format. See this example:

https://github.com/gziolo/gutenberg-times/blob/master/src/index.js#L6-L25

The issue with the filter is that you need to ensure that it is registered before the format gets registered. When using `unregisterFormatType` you flip the requirement, customization needs to happen after the format gets registered.

**Comment by ellatrix** [comment]
@gziolo Is correct. This is why `unregisterFormatType` exists.

**Comment by mmtr** [comment]
> The issue with the filter is that you need to ensure that it is registered before the format gets registered. When using `unregisterFormatType` you flip the requirement, customization needs to happen after the format gets registered.

Do you have any concern in supporting both options? That way we could use `unregisterFormatType` if we have to enqueue a script after the Gutenberg initialization and we could use the filter in scenarios where the scripts are enqueued before the initial set up.

For the latter scenario, right now we have to create a subscriber and wait for the registration (which is what we did in https://github.com/Automattic/wp-calypso/pull/32808):

```js
const unsubscribe = subscribe( () => {
	const underlineFormat = select( 'core/rich-text' ).getFormatType( 'core/underline' );
	if ( ! underlineFormat ) {
		return;
	}
	unsubscribe();
	const underline = unregisterFormatType( 'core/underline' );
	registerFormatType( 'core/underline', {
		...underline,
		// custom settings
 	} );
} );
```

That could be simplified a lot with the filter.

**Comment by mmtr** [comment]
> we could use the filter in scenarios where the scripts are enqueued before the initial set up.

Just realized this shouldn't be the way to load a script that customizes a default format. The script should depend on the `wp-format-library` dependency in order to ensure the formats are registered, making unnecessary to use a subscriber.

Even though, I still see scenarios in which the filter could be helpful, especially when dealing with third-party code. For example, 2 plugins extending the same format: one adding a custom class and the other one changing the icon of the toolbar button. I think that with the current unregister/register approach we would have some race condition and only the last plugin enqueueing the script will prevail, reverting any changes done by the first plugin. With a filter, the 2nd plugin will modify the settings updated by the 1st plugin.

**Comment by aduth** [comment]
As I see it, a filter would largely serve only as consistency given that an equivalent filter exists already for block registration, which otherwise shares an identical signature. The challenges which have been faced with timing and availability of this filter (#9757) are such that it's not a pattern I'd like to see broadly reused.

>I think that with the current unregister/register approach we would have some race condition and only the last plugin enqueueing the script will prevail, reverting any changes done by the first plugin.

As long as both are implemented in a way where they merge with the settings of the format at whatever point in time they extend the block, I don't see why it would ever undo the earlier plugin's modifications, rather than simply extend them further.

**Pull request closed without merging**
