### PR TITLE
Process Block Type: Copy deprecation to a new object instead of mutating when stabilizing supports

### PR DESCRIPTION
**Pull request by andrewserong**
## What?

Follows #63401 and attempts a fix for the issue flagged in https://github.com/WordPress/gutenberg/pull/63401#discussion_r1832394335

When applying block supports stabilization while processing block types, try to avoid mutating the deprecation, in case the passed in object does not support setting keys. This can be the case in some plugins as was flagged in the linked comment, and in the Jetpack plugin (https://github.com/Automattic/jetpack/issues/40055 and https://github.com/Automattic/jetpack/pull/40070).

Thank you to @coder-karen for flagging this issue!

## Why?

As seen in the Jetpack plugin in https://github.com/Automattic/jetpack/pull/40070, some plugins structure their deprecations in such a way that they're _imported_ rather than constructed from ordinary JS objects. I.e. in the Jetpack plugin, it uses a pattern like the following:

```js
import * as deprecatedV1 from './v1';
import * as deprecatedV2 from './v2';
import * as deprecatedV3 from './v3';

export default [ deprecatedV3, deprecatedV2, deprecatedV1 ];
```

Where in each of those files, the keys are exported like so:

```js
export const attributes = {
  ...
};

export const supports = {
  ...
};
```

So, the object for each deprecation is not a regular JS object. Arguably the above approach isn't what's expected from the perspective of Gutenberg's code, but given that plugins are already writing things this way, let's ensure that it's supported, so as not to break plugins and websites!

## How?

For each deprecation, create a new object and expand the keys into the new object. This should ensure that we're updating `supports` in a safe(r) way.

Update the test for stabilizing block supports in the deprecation by calling `Object.freeze( blockSettings.deprecated[ 0 ] );` — this emulates the approach seen in the Jetpack plugin by ensuring that the `deprecated` object's keys cannot be mutated.

## Testing Instructions

1. Ensure that deprecations function as expected and/or follow the testing instructions in https://github.com/WordPress/gutenberg/pull/63401 to ensure that this doesn't cause any regressions
2. Ensure that tests pass, or test the Jetpack plugin in conjunction with this PR, using the Slideshow block.
  * For the latter, create a post and add the Slideshow block. On `trunk` I get a white screen of death with an error message, whereas with this PR, the block displays as expected in the editor.

## Screenshots or screencast 

The following are screenshots from running the Jetpack plugin on a post that includes the Slideshow block from that plugin. (If you're testing Jetpack, you'll need to switch on Jetpack Blocks under Jetpack Plugin Settings > Writing > Composing > Jetpack Blocks.)

| Trunk (WSOD with this error) | This PR |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
Appreciate the quick turnaround on this fix @andrewserong 🚀 

The current approach in this PR appears to solve the primary concern and issue. I wonder if we could make the overall stabilization of supports a little more robust for other plugins?

Could a plugin perhaps create a series of blocks that they registered via JS but use a shared typography supports definition or something that they import into their blocks' config? In other words, if the config objects for individual supports, e.g. typography, color, spacing, border etc., were also immutable the new `stabilizeSupports` function might throw a similar error.

I'm not trying to argue we need to cover every weird and wonderful way these objects might be constructed but maybe tweaking `stabilizeSupports` along with the current fix for deprecation supports would provide a lot more certainty here?

<details>
<summary>Here's a very rough and dirty example of what I mean</summary>

```js
function stabilizeSupports( rawSupports ) {
	if ( ! rawSupports ) {
		return rawSupports;
	}

	const newSupports = {};
	for ( const [ key, value ] of Object.entries( rawSupports ) ) {
		if ( key === 'typography' && typeof value === 'object' && value !== null ) {
			newSupports.typography = Object.fromEntries(
				Object.entries( value ).map( ( [ typographyKey, typographyValue ] ) => [
					TYPOGRAPHY_SUPPORTS_EXPERIMENTAL_TO_STABLE[ typographyKey ] || typographyKey,
					typographyValue,
				] )
			);
		} else {
			newSupports[ key ] = value;
		}
	}

	return newSupports;
}
```
</details>

I don't have a strong opinion on this, so feel free to disregard if you think it is overkill.

**Comment by ramonjd** [comment]
I'll take @aaronrobertshaw's advice on this one. I'm happy to rubber stamp it, but admittedly, I'm not 100% across the scope.

**Comment by andrewserong** [comment]
Thanks for the quick reviews!

> The current approach in this PR appears to solve the primary concern and issue. I wonder if we could make the overall stabilization of supports a little more robust for other plugins?

Good thinking @aaronrobertshaw, I like the code snippet you've provided — overall it feels both safer and more "correct" to me if we're carefully constructing the new object rather than creating it and then swapping out the reference for `typography`.

In practice, I wasn't able to reproduce any issues with the approach before applying that snippet — because we're already creating a fresh object, when `supports.typography` is set, the value for `typography` gets updated to be a fresh reference to a new object so I don't _think_ there's a way for a plugin to set `supports.typography` itself to be immutable in a way that breaks the current state of the function. I played around with a couple of tests and couldn't break it, at any rate.

All that said I have more confidence in your suggestion than what we currently have, and it sets a good example for future changes to that function, so IMO even if it doesn't explicitly fix anything immediate, it's still a good quality change. I've pushed an update in https://github.com/WordPress/gutenberg/pull/66849/commits/3fe635debd496e2a1866d67ac60d9166f79a687f

Let me know if anyone would like any other changes, happy to keep iterating here! My overall hope, aside from fixing the reported bug, is that we can build the block supports stabilization in a way that feels stable and robust, so any and all code quality ideas are very welcome 🙂

**Review by aaronrobertshaw — APPROVED** [review]
I was just about to approve the first iteration when the new commit came through, you're too quick @andrewserong!  ⚡  

I've tested the latest and it's working well for me.

✅ Could replicate the original issue with Jetpack active
✅ This PR resolves the issue
✅ Deprecations still function (block fixture tests are all passing as well)
✅ Stabilization of typography supports tests pass

LGTM 🚢

**Comment by aaronrobertshaw** [comment]
Quick update:

As discussed in https://github.com/WordPress/gutenberg/pull/67729#issuecomment-2553200639, the approach to block support stabilization needs more time so will likely be punted from 6.8. There is a revert PR available (https://github.com/WordPress/gutenberg/pull/68163) and anyone interested in stabilized block supports is advised to follow that for the latest 🙏

**Pull request merged**
