### PR TITLE
Ensure that the return value of apiFetch is always a valid Promise object in Firefox

### LINKED ISSUE #10208: Embed previews broken in firefox, no "embedding..." prompt in chrome
**Describe the bug**

https://github.com/WordPress/gutenberg/pull/9958 changed the behaviour of resolvers, which stopped the "Embedding..." state in Chrome, and broke previews in Firefox.

The `isRequestingEmbedPreview` now always returns `false`.

**To Reproduce**

Embed anything in Firefox, notice the preview is missing. 

**Expected behavior**

Preview should appear, and "Embedding..." notice should appear as it did prior to #9958. `isRequestingEmbedPreview` should return `true` when the request is in progress.

cc: @youknowriad

### LINKED ISSUE #10265: Reusable blocks don't save/load in Firefox
**Describe the bug**
Reusable blocks are not saved or loaded in Firefox.

**To Reproduce**
1. Create a block
2. Click on '...'
3. Select "Add to Reusable blocks"
4. Click Save
5. Publish the post
6. Reload the page

Observe the block warning: "Block has been deleted or is unavailable."

**Expected behaviour**
The reusable block is saved and loaded in the editor.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox

### PR DESCRIPTION
**Pull request by youknowriad**
it looks like window.fetch in firefox don't return an object that is instance of Promise causing some weird issues down the road.

This PR ensures we always return a promise object.

closes #10208
fixes #10265

**Testing instructions**

 - Try embedding a tweet in Firefox, you should see the preview.

### CODE REVIEW

**Review by notnownikki — COMMENTED** [review]
Embeds work! Fetching status works! Thank you <3

I'll leave it up to @aduth for the approval though, I'm not 100% sure of the repercussions of this.

**Comment by youknowriad** [comment]
@aduth I really don't know more about it. maybe some polyfill related thing. Not sure what can I do. All I know is `window.fetch('something') instanceof Promise === false`

**Comment by aduth** [comment]
If I'm known for one thing, it's for my nagging relentlessness in not allowing "I don't know" to pass 😄 

It is an issue related to polyfills. Specifically, the native promise is overridden in Firefox due to [lack of support of a `PromiseRejectionEvent` global](https://github.com/zloirock/core-js/blob/d42976f7af29832cddc04051cb7032057d17ab74/packages/core-js/modules/es.promise.js#L53). Fetch is not polyfilled, however, so there is a mismatch between the promise as returned by fetch and the promise global. You can see this mentioned in comments of [this StackOverflow answer](https://stackoverflow.com/a/28133130), which also explains why the [standard redux middleware for promises](https://github.com/redux-utilities/redux-promise/blob/master/src/index.js) uses a [library which to detect promises by shape](https://www.npmjs.com/package/is-promise), not reference.

So, I think this is more an issue of how we detect things as promises (in our promise middleware) rather than the return value of fetch, which is in-fact a promise.

**Comment by youknowriad** [comment]
> So, I think this is more an issue of how we detect things as promises (in our promise middleware) rather than the return value of fetch, which is in-fact a promise.

That was my original way of fixing the issue, but we do test promises in several places. Should we update them all?

What should we consider a promise: an object with a `.then` function?

I did try to search for the issue elsewhere but failed. You're more skilled then me :)

**Comment by aduth** [comment]
>What should we consider a promise: an object with a `.then` function?

I think this is safest in reality where promises are often polyfilled, even if it is not quite as semantic as testing it against the `Promise` global. It might be a touch better for us than in delegating this to the things which produce promises to normalize (i.e. `apiFetch`).

Ultimately, It's a small difference that I don't care too much one way or the other. My bigger concern was having the understanding of what was causing the issue, so we could at least be well-informed to be able to evaluate the best solution.

**Comment by notnownikki** [comment]
This is affecting more then I thought in firefox. For example, categories and tags don't appear in the document settings without this patch.

**Review by tofumatt — CHANGES_REQUESTED** [review]
Thanks for digging into this @aduth. If the "intuitive" way to check for Promises is problematic, seems like we should be relying on a library (like other projects do) to detect Promises. @aduth mentioned: https://www.npmjs.com/package/is-promise... I think it makes more sense to update our checks to use something like that `is-promise` library. I worry otherwise we'll just run into edge cases like this again.

It might be nice to enforce a rule about it if possible, maybe alert if you are checking for `instanceof Promise` or whatever, but that can happen later; I'm not sure how we test across the repo.

**Review by tofumatt — APPROVED** [review]
This is great and also fixes #10265. 🚢

**Comment by danielbachhuber** [comment]
> This is affecting more then I thought in firefox. For example, categories and tags don't appear in the document settings without this patch.

I think it also impacted #9982

**Pull request merged**
