### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manooweb**
fix typo in withDispatch paragraph

### CODE REVIEW

**Review by Soean — APPROVED** [review]
Thanks, good catch!

**Comment by chrisvanpatten** [comment]
Is this a section of the README which is automatically generated? It's not clear to me looking at the diff…

**Comment by manooweb** [comment]
Directly in the README here https://github.com/WordPress/gutenberg/tree/master/packages/data#withDispatch

The first change : to unnecessary re-renders of **you** component caused replaced by **your** instead

and the second one a double "with" deleted

**Comment by chrisvanpatten** [comment]
@manooweb It looks like your changes start on line 467, but the autogenerated docs start on line 249.

I think you'll need to edit the inline documentation directly here: https://github.com/WordPress/gutenberg/blob/master/packages/data/src/components/with-dispatch/index.js#L51

Then when the docs are compiled, it will update the README automatically.

**Comment by Soean** [comment]
Thanks @chrisvanpatten. Of course, you have to edit it in the source code and then run `npm run docs:build`

**Comment by manooweb** [comment]
Ok. I see :-) I didn't know that this doc was built from code.
I'm doing it code a coming back later :)

**Pull request closed without merging**
