### PR TITLE
PluginPrePublishPanel uses icon property and inherits from registerPlugin

### PR DESCRIPTION
**Pull request by ryanwelcher**
## Description
This PR adds the icon parameter to the PluginPrePublishPanel SlotFill and allows the icon to be inherited via the registerPlugin command.

## Screenshots
pre-publish-panel

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Comment by ryanwelcher** [comment]
Related #13361

**Comment by sarahmonster** [comment]
Note that there are some changes in-progress with the pre-publish panel that may impact this, notably switching it to a modal dialog instead of a sidebar (#15847) and streamlining the content that's shown there (#16127). For a more holistic overview of that work, follow along in #7602 [tracking issue].

Icons were discussed a bit in #14180 as well, where we came to the conclusion that we'd allow them, but only in grayscale format. This is, however, tricky to enforce. In terms of the pre-publish dialog, I'd be inclined to avoid icons altogether, since they have the potential to contribute a lot of visual noise to what we're trying to keep to a more streamlined and focussed experience.

**Comment by youknowriad** [comment]
There's an argument to be made that it allows the user to clearly identify that this is coming from a plugin, not a core feature and which plugin is that.

**Comment by karmatosed** [comment]
> There's an argument to be made that it allows the user to clearly identify that this is coming from a plugin, not a core feature and which plugin is that.

This feels like a solid point to me and one that's useful for someone scanning.

**Comment by ryanwelcher** [comment]
Related #16383

**Comment by gziolo** [comment]
From a technical perspective, this looks good. It needs some testing and approval from the design team.

**Comment by gziolo** [comment]
Can we apply the same set of changes to the post publish panel for consistency?

Screen Shot 2019-08-30 at 14 36 55

I tested with the following code:

```js
( function() {
	var el = wp.element.createElement;
	var Fragment = wp.element.Fragment;
	var __ = wp.i18n.__;
	var registerPlugin = wp.plugins.registerPlugin;
	var PluginPostPublishPanel = wp.editPost.PluginPostPublishPanel;
	var PluginPrePublishPanel = wp.editPost.PluginPrePublishPanel;

	function PanelContent() {
		return el(
			'p',
			{},
			__( 'Here is the panel content!' )
		);
	}

	function MyPublishPanelPlugin() {
		return el(
			Fragment,
			{},
			el(
				PluginPrePublishPanel,
				{
					className: 'my-publish-panel-plugin__pre',
					title: __( 'My pre publish panel' )
				},
				el(
					PanelContent,
					{}
				)
			),
			el(
				PluginPostPublishPanel,
				{
					className: 'my-publish-panel-plugin__post',
					title: __( 'My post publish panel' )
				},
				el(
					PanelContent,
					{}
				)
			)
		);
	}

	registerPlugin( 'my-publish-panel-plugin', {
		icon: 'palmtree',
		render: MyPublishPanelPlugin
	} );
} )();
```

**Comment by ryanwelcher** [comment]
@gziolo Thanks for the reivew on this! 
I did a separate PR for the post publish - #16383

**Comment by ryanwelcher** [comment]
> Icons were discussed a bit in #14180 as well, where we came to the conclusion that we'd allow them, but only in grayscale format.
@sarahmonster I believe that icons that are used in the Document Sidebar are forced to greyscale. At least when using the PluginDocumentSettingPanel SlotFill. Can we do the same here?

**Review by gziolo — APPROVED** [review]
Seeing #16383, let's move forward with this one as soon as there is ✅ from the design team.

**Comment by kjellr** [comment]
> I believe that icons that are used in the Document Sidebar are forced to greyscale. At least when using the PluginDocumentSettingPanel SlotFill. Can we do the same here?

Yeah, assuming that someone's using the standard method inside of a Panel, the icons will be grayscale due to this rule:

https://github.com/WordPress/gutenberg/blob/5774046c216a96d95fcbcfd2903b74f5f69a0611/packages/components/src/panel/style.scss#L120

As long as that's all set, this seems like a solid improvement to me — as noted above, it does help make clear which panels are coming from a plugin.

**Review by mapk — APPROVED** [review]
Yep! I agree with the comments here. The icons help clarify which panels are from specific plugins. A good improvement. LGTM.

**Comment by ryanwelcher** [comment]
Wanted to confirm that custom SVGs are rendered in greyscale.
Edit_Post_‹_gutenberg-dev_test_—_WordPress

**Comment by ryanwelcher** [comment]
@gziolo I've resolved the failures on this PR. I believe that this and #16383 are both ready for merge.

**Pull request merged**
