### PR TITLE
Font Library: Remove WP_Font_Family class that is no longer used.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
Remove `WP_Font_Family` class and its tests.

## Why?
Because it's no longer used after https://github.com/WordPress/gutenberg/pull/57688

## How?
Removing the source code file and its tests.

## Testing Instructions
- Run unit tests
- Use the font library and check everything works as expected.

### CODE REVIEW

**Review by pbking — APPROVED** [review]
The Font Library continues to work as expected.  Unit tests continue to pass.

This change looks good to me.

**Comment by getdave** [comment]
I noticed this PR was merged after I raised the [PHP Sync Tracking Issue for WP 6.5](https://github.com/WordPress/gutenberg/issues/57959) and has changed PHP files that _may_ need backporting to WP Core.

I believe this will be [backported as part of a single backport for the Fonts API](https://github.com/WordPress/gutenberg/issues/57959#issuecomment-1900136925). It's been added to the Tracking Issue.

**Comment by cbravobernal** [comment]
This PR was already in `release/17.6`, it seems that there is no need to backport it. @creativecoder

**Comment by creativecoder** [comment]
Thanks @c4rl0sbr4v0 for checking! We had a number of smaller font library PRs to touch things up in the last week, I wasn't sure which ones made it into the rc or not.

**Pull request merged**
