### PR TITLE
Fix image/cover transform duotone error

### PR DESCRIPTION
**Pull request by ajlende**
## Description

Fixes https://github.com/WordPress/gutenberg/pull/32002#issuecomment-844271164

## How has this been tested?

1. Create image block.
2. Transform image to cover.
3. Transform cover to image.

## Screenshots 

duotone-transform

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by gwwar — APPROVED** [review]
Thanks @ajlende I verified that the transforms now work. This is good to land when checks are green. It looks like folks are manually cancelling builds, so we might want to add this to the 5.8 must have project https://github.com/WordPress/gutenberg/projects/55

**Comment by ajlende** [comment]
Included in #32102

**Comment by ajlende** [comment]
Reopening because the cover -> image transform wasn't fixed in #32102

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
Do you mind rebasing this PR to check the tests (patterns directory php unit failures are expected)

**Pull request merged**
