### PR TITLE
[RNMobile] Update `Podfile.lock` file of Gutenberg demo app

### PR DESCRIPTION
**Pull request by fluiddot**
## Description

https://github.com/WordPress/gutenberg/pull/34886 updated the pod references used in `react-native-editor` which are also used in the Gutenberg demo app, however, we forgot to update the `Podfile.lock` file, for this reason, this PR updates that file.

## How has this been tested?

- Run command `npm ci`.
- Run command `npm run native ios`.
- Observe that the `Podfile.lock` file is not modified.

## Screenshots 
N/A

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by hypest** [comment]
Hmm, when I `npm run native ios` (inside the gutenberg subfolder in a gb-mobile checkout) the changes actually get reverted from `BVLinearGradient (2.5.6-wp-1)` to `BVLinearGradient (2.5.6-wp)`. I also tried the same after deleting `-Rf packages/react-native-editor/ios/Pods/`. Something else I need to do to verify the PR perhaps? 🤔

**Comment by fluiddot** [comment]
> Hmm, when I `npm run native ios` (inside the gutenberg subfolder in a gb-mobile checkout) the changes actually get reverted from `BVLinearGradient (2.5.6-wp-1)` to `BVLinearGradient (2.5.6-wp)`. I also tried the same after deleting `-Rf packages/react-native-editor/ios/Pods/`. Something else I need to do to verify the PR perhaps? 🤔

Oh interesting, have you installed the dependencies by running `npm ci` before installing pods?

**Comment by hypest** [comment]
> Oh interesting, have you installed the dependencies by running npm ci before installing pods?

Aha, I didn't! After I switched a local checkout to this branch, I went straight to the `npm run native ios` step as per the testing instructions. Trying with `npm ci` first I can confirm that the Podfile.lock doesn't get touched ✅

**Review by hypest — APPROVED** [review]
LGTM!

**Comment by fluiddot** [comment]
> > Oh interesting, have you installed the dependencies by running npm ci before installing pods?
> 
> Aha, I didn't! After I switched a local checkout to this branch, I went straight to the `npm run native ios` step as per the testing instructions. Trying with `npm ci` first I can confirm that the Podfile.lock doesn't get touched ✅

Good catch, to be honest, I didn't realize that running `npm ci` was required for this, when I tried it locally it worked only by running `npm run native ios`, but in my case I already have the dependencies installed 😅. Sorry for missing the step, I'll add it to leave the reference.

**Pull request merged**
