### PR TITLE
Block editor: use proper insertion point for drop

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Refresh of #27537. Keeping the other PR as a reference.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by ellatrix** [comment]
For some reason I'm just getting an error in the navigation block when I start dragging. @talldan Any ideas?

**Comment by mtias** [comment]
Nice! I hope we can also develop some logic to consider empty containers (empty column, empty group, empty paragraph) as more clear drop targets. Instead of using a line it should be closer to https://github.com/WordPress/gutenberg/issues/29145

**Review by talldan — APPROVED** [review]
Sorry for not replying to the earlier ping.

I think it'd be great to get this in. 

The appender is also a problem with the current system as it's often conditionally rendered, so I think this has lots of benefits

When testing in nested blocks, I noticed the indicator sometimes flickers. https://github.com/WordPress/gutenberg/pull/30272 seems to resolve that, so it'd be great to get that improvement in as well.

**Comment by ellatrix** [comment]
Let's merge and iterate on the unified insertion point!

**Pull request merged**
