### PR TITLE
WIP: Use inner blocks for lists

### PR DESCRIPTION
**Pull request by dmsnell**
Lists in HTML are more like containers than sequences of paragraphs. How can we make list blocks generic containers?

### CODE REVIEW

**Comment by gziolo** [comment]
There should be some prior work from @ellatrix to bring nested blocks support for the List block. I know that @oandregal worked on the same type of changes to the Query block in https://github.com/WordPress/gutenberg/pull/25892 but he put it on hold because of his involvement in the Global Styles project.

**Comment by ellatrix** [comment]
Quote should be much, much easier than lists.

A list item also needs to support nesting a whole other list after the text:

```html
<ol>
  <li>item 1
    <ol>...</ol>
  </li>
</ol>
```

So there could be a list block and a list item block which can be an inner block of the list block. But then inside the list item block it needs to be possible to append another list block. The contents of this sublist are tied to the parent list item's text.

Similarly when moving a list item up or down, the sublist tied to that list item should move up or down with it.

**Comment by dmsnell** [comment]
> Quote should be much, much easier than lists.

It's on my TODO list to jump over to #25892 and see if there's any way I can help with that one.

> A list item also needs to support nesting a whole other list after the text:

if I understand you properly this is already supported even in this PR (although it's not like the current state of this exploratory PR is something that we could talk about merging). Still, the `list-item` block in conception is a container like the group block and doesn't have any restriction on what you put in it. The difference in your HTML sample is that we would have a `<p>` wrapped around that `item 1` since it would be a paragraph block. For list titles, on the other hand, I have envisioned providing something more akin to the recommendation in the HTML spec providing a `<figure><figcaption>…` construction.

**Comment by georgeh** [comment]
This would make #31733 significantly easier, since it would be transforming one block tree to another instead of parsing HTML.

**Comment by gziolo** [comment]
#39487 added similar functionality. The alternative PR keeps the old and new implementation as it is necessary for the transition period. Let's close this one as a duplicate.

**Pull request closed without merging**
