### PR TITLE
Move the view section of the More Menu to the options panel

### PR DESCRIPTION
**Pull request by youknowriad**
I have found that the Editor modes (fullscreen, top toolbar and spotlight mode) are not options we trigger regularily, in general you choose an option and stick with it for a long time.

So in this PR, I'm moving them to the "options" panel. I feel it's a more logical location for them and it frees up the "More Menu" a little bit.

The concern here could be "discoverability" maybe? The counter-argument is that it's not mandatory for users to change options but if they want to, it's better if it's in a single place.

Thoughts?

Capture d’écran 2019-11-19 à 9 52 53 AM

### CODE REVIEW

**Comment by jasmussen** [comment]
This seems good to me, including your reasoning. 👍 👍

This does highlight that we could give some visual love to the options dialog — there are quite a few horizontal lines that don't seem to add that much value. Not necessarily something to remove in this PR, but something to consider:

Screenshot 2019-11-19 at 10 34 46

To frame it differentlhy — the options dialog could use more or less the same visual layout for separation as exists in the dropdown.

**Review by jasmussen — APPROVED** [review]
Approving from a design POV, might still need a code sanity check.

**Comment by youknowriad** [comment]
> This does highlight that we could give some visual love to the options dialog

My opinion is that it should be full screen modal with two columns :)

**Comment by jasmussen** [comment]
> My opinion is that it should be full screen modal with two columns :)

Hehe I know. I quite disagree with that — to me that changes it to a modal _section_ as opposed to a modal _dialog_. There can be a place for both, but I believe there will always be a need for a _dialog_ interface that shows the context of the parent interface. But this is a separate discussion ;)

**Comment by youknowriad** [comment]
>  I believe there will always be a need for a dialog interface that shows the context of the parent interface. But this is a separate discussion ;)

I changed my mind, I think there's a need for dialogs, but options I'm not certain it's a dialog. In general we have completely separate pages for settings and options.

**Comment by jasmussen** [comment]
> but options I'm not certain it's a dialog

Yep, I can agree with that.

**Pull request merged**
