### PR TITLE
Template Loader: Use `glob` constant instead of numeric value.

### LINKED ISSUE #18876: Templates: PHP warning: glob(): At least one of the passed flags is invalid or not supported on this platform
**Describe the bug**

The calls to `glob()` in `gutenberg_find_template()` pass a value of `1` to the `$flags` parameter. I'm not sure what the intention of this flag is, but it's triggering a PHP warning and it should use one of the predefined `GLOB_*` constants instead of a numeric value.

The PHP warning that's showing up for me when viewing a page that uses full site editing is:

```
glob(): At least one of the passed flags is invalid or not supported on this platform
wp-content/plugins/gutenberg/lib/template-loader.php:151
```

**To reproduce**

1. Enable the Full Site Editing experiment from Gutenberg -> Experiments
2. Create a template from Appearance -> Templates, and give it a slug of `front-page`.
3. Visit your site's front page.

**Expected behavior**

Nice things happen.

**Screenshots**

Error in Query Monitor:

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
- Gutenberg 7.0.0
- PHP 7.3.12

### PR DESCRIPTION
**Pull request by epiqueras**
Fixes #18876

## Description

This PR changes the calls to `glob` in the template loader to use the constant `GLOB_NOSORT` instead of the literal `1` which seems to have been causing issues in certain environments.

## How has this been tested?

It was verified that template loading still works as expected.

## Checklist:

- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by aduth** [comment]
Can you explain what's meant to be accomplished with this flag?

And what was meant to be accomplished with the previous value? (since `GLOB_NOSORT` is `32`, thus a different behavior from what existed previously)

**Comment by epiqueras** [comment]
I thought the constants were 0 indexed and intended to use `GLOB_NOSORT` to be more efficient since we don't need to sort the results here.

**Comment by aduth** [comment]
> intended to use `GLOB_NOSORT` to be more efficient since we don't need to sort the results here.

Does it make a measurable difference?

If I find myself questioning why it exists today, I think it would be a fair assumption that it might catch the attention of future maintainers as well, as to why it needs to exist.

At the very least, if we keep it, can we add an inline comment explaining its purpose for the benefit of those who work with this code in the future?

**Comment by epiqueras** [comment]
I don't think the minimal performance difference warrants the potential for confusion so I've removed them.

**Review by johnbillion — APPROVED** [review]
+1 for removal. The performance benefit here will be negligible.

**Review by aduth — APPROVED** [review]

**Pull request merged**
