### PR TITLE
[RNMobile] Remove devOnly flag from Group block

### PR DESCRIPTION
**Pull request by jbinda**
## Description

Open Group Block for production by removing `devOnly` flag according to [this ticket](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1824)

Please also refer to:
[Related gutenberg-mobile PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1850)

## How has this been tested?

`WordPress iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13367
`WordPress Android` -> https://github.com/wordpress-mobile/WordPress-Android/pull/11231

## Types of changes

New feature (Group block)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

### CODE REVIEW

**Comment by pinarol** [comment]
@jbinda `Related gutenberg-mobile PR` link in the description seems to point this PR again, could you fix that?

**Comment by jbinda** [comment]
Sure, done.

**Review by geriux — APPROVED** [review]
This is working great on https://github.com/wordpress-mobile/WordPress-iOS/pull/13367 👏 

Amazing work! I did some inception tests nesting different blocks and groups within groups and it didn't break 😏🙌 (besides the other suggested test cases that all worked flawlessly too)

Tested **only on iOS**

**Pending Android**

**Comment by jbinda** [comment]
@geriux Thanks for testing and feedback !

**Review by chipsnyder — APPROVED** [review]
Looks great on Android as well https://github.com/wordpress-mobile/WordPress-Android/pull/11231 🚀

**Comment by jbinda** [comment]
Once again thanks for testing, merged ! 🚀

**Pull request merged**
