### PR TITLE
[RNMobile] Add media caption when adding an image or video

### PR DESCRIPTION
**Pull request by fluiddot**
### Related PRs
- [`gutenberg-mobile`](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3046)
- [`WordPress-iOS`](https://github.com/wordpress-mobile/WordPress-iOS/pull/15674)
- [`WordPress-Android`](https://github.com/wordpress-mobile/WordPress-Android/pull/13829)
- [`WordPress-FluxC-Android`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1846)

## Description

This PR addresses the following topics:

### Upload credit/attribution of photos from free photo library

The idea is to upload as the caption of the media item the credit/attribution from photos that we get from the free photo library (Pexels). The changes for this have been applied in the native projects (iOS and Android).

### Include caption of media items when inserting them into a block
This covers the Image and Video block.

## How has this been tested?

<details><summary><strong>Image</strong></summary>

_The following steps are for iOS version but they're very similar on Android._

1. Go to a site.
2. Open a post/page.
3. Tap on `+` button.
4. Tap on `Image` block.
5. Tap on `ADD IMAGE`.
6. Tap on `Free Photo Library`
7. Search any term.
8. Tap one photo.
9. Wait for the item to be uploaded.
10. Check that below the photo the caption field has a value.

</details>

<details><summary><strong>Video</strong></summary>

_The following steps are for iOS version but they're very similar on Android._

**For this flow a site with a premium plan is required.**

1. Go to a site.
2. Go to media screen.
3. Tap on `+` button.
4. Tap on `Choose from My device` button.
5. Tap on video item.
6. Wait for the item to be uploaded.
7. Tap on the uploaded item.
8. Edit the caption and put some text.
2. Open a post/page.
3. Tap on `+` button.
4. Tap on `Video` block.
5. Tap on `ADD VIDEO`.
6. Tap on `WordPress Media Library`
7. Tap on uploaded item.
10. Check that below the video the caption field has the value previously set.

</details>

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jd-alexander** [comment]
Hi @fluiddot since I am reviewing the associated WP Android and FluxC PRs I was thinking to add myself as a reviewer here? Just to verify, do you want me to take a look at these changes as yet? Let me know your thoughts. Thank you.

**Comment by fluiddot** [comment]
> Hi @fluiddot since I am reviewing the associated WP Android and FluxC PRs I was thinking to add myself as a reviewer here? Just to verify, do you want me to take a look at these changes as yet? Let me know your thoughts. Thank you.

👋 @jd-alexander yeah it would be nice if you assign yourself as a reviewer in this PR. I was waiting for the native PRs to be ready because potential changes there might imply to update this part but I'd appreciate feedback here too, thanks!

**Review by jd-alexander — COMMENTED** [review]
Thanks for these changes @fluiddot Things are looking good so far. The only blocker for merging in these changes from an Android point of view is that the caption value is not being propagated on the jetpack and Atomic sites. I started looking into the Jetpack code and I found one of the places see where the value of the caption is being passed via the [Jetpack functions](https://github.com/Automattic/jetpack/blob/26db3e436ccca3e16a62d02d95e792a81f38a1e4/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php) that represent all requests/responses for external media.

I am going to some more diagnostics from the HTTP layer soon to see if I can figure out what's happening.

**Comment by jd-alexander** [comment]
So the results from my checks so far are as follows: 

1. I was able to verify that the caption of the Pexels media item is being uploaded to the site via `https://public-api.wordpress.com/rest/v1.1/sites/{}/external-media-upload/`.  The JSON result does not contain the caption. 

2. Adding the same media item from the WP Media Library results in a caption being shown. So I think the issue may be that endpoint.

**Comment by fluiddot** [comment]
> So the results from my checks so far are as follows:
> 
> 1. I was able to verify that the caption of the Pexels media item is being uploaded to the site via `https://public-api.wordpress.com/rest/v1.1/sites/{}/external-media-upload/`.  The JSON result does not contain the caption.
> 2. Adding the same media item from the WP Media Library results in a caption being shown. So I think the issue may be that endpoint.
> 
> Is this behavior also taking place on iOS?

Yeah that's the issue I spotted while testing and I also have the impression that is related to that endpoint. However it can only be reproduced on sites connected with Jetpack, the same endpoint on WP.com regular sites returns the caption on the JSON result 🤔 .

On iOS this is not happening because it doesn't use the `external-media-upload` endpoint for uploading the image, it uses `media/new`.

I'll keep investigating the issue just in case it's something related to Jetpack, if that's case I'll open an issue there with the insights.

**Comment by jd-alexander** [comment]
> Yeah that's the issue I spotted while testing and I also have the impression that is related to that endpoint. However it can only be reproduced on sites connected with Jetpack, the same endpoint on WP.com regular sites returns the caption on the JSON result 🤔 .

Indeed! I realized this as well. 
> 
> On iOS this is not happening because it doesn't use the `external-media-upload` endpoint for uploading the image, it uses `media/new`.

Makes sense

> 
> I'll keep investigating the issue just in case it's something related to Jetpack, if that's case I'll open an issue there with the insights.

Yes, that's a good idea.

**Comment by youknowriad** [comment]
Doing some cleanup to old PRs. This draft PR seems staled. Is it still relevant, should we close it?

**Comment by fluiddot** [comment]
> Doing some cleanup to old PRs. This draft PR seems staled. Is it still relevant, should we close it?

No, no longer relevant. I'll close it, thanks for the heads up 🙇 !

**Pull request closed without merging**
