### PR TITLE
Enable inheritance in search block.

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Font family, size, and line heights, are not inherited in the Search block. That makes its visual appearance stand out when used inside the navigation block. Here's Empty Theme with a search inside nav. Editor:

before editor

Frontend:

before frontend

The font size discrepancy is less visible in Empty Theme, but can be seen here:

Screenshot 2021-10-18 at 11 35 01

This PR adds inheritance, which also makes the editor more like the frontend:

after editor

Frontend:

after frontend

## How has this been tested?

Here's some test content:

```
<!-- wp:paragraph -->
<p>Button inside:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation -->
<!-- wp:home-link {"label":"Home"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":30315,"url":"http://local-wordpress.local/about/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:search {"label":"Search","showLabel":false,"placeholder":"Search","buttonText":"Search","buttonPosition":"button-inside","buttonUseIcon":true} /-->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Button outside:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation -->
<!-- wp:home-link {"label":"Home"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":30315,"url":"http://local-wordpress.local/about/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:search {"label":"Search","showLabel":false,"placeholder":"Search","buttonText":"Search","buttonUseIcon":true} /-->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Button outside and with label:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation -->
<!-- wp:home-link {"label":"Home"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":30315,"url":"http://local-wordpress.local/about/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:search {"label":"Search","showLabel":false,"placeholder":"Search","buttonText":"Search"} /-->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>With label:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation -->
<!-- wp:home-link {"label":"Home"} /-->

<!-- wp:navigation-link {"label":"About","type":"page","id":30315,"url":"http://local-wordpress.local/about/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:search {"label":"Search","placeholder":"Search","buttonText":"Search"} /-->
<!-- /wp:navigation -->
```

Please test the search block in a variety of situations, including inside the nav block, and in a few themes, and verify that it always feels harmonious to use.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by jasmussen** [comment]
Note that the fake "Space between" thing going on in the above screenshots on the frontend is fixed separately in #35722. This PR would also go well with #35688.

**Comment by MaggieCabrera** [comment]
I agree with this one, though this will affect themes that don't explicitly set a font size for input elements of the search form in particular. On emptytheme, setting the body font size to 30px:

Before | After
--- | ---
Screenshot 2021-10-18 at 13 11 31 | Screenshot 2021-10-18 at 13 11 37

This highlights the need for font control on the theme side for the block. The same block while used on the navigation block will need a very different font size than it will on pages like the search template for example, but I'm not sure we will always want the placeholder and input text to be the same as the body/paragraph font size. At least that's not what I've seen in the designs I've worked with. Generally, the input text is a tad smaller, while the label text is indeed the same as the body/paragraph's. 

But I'd leave that discussion to the designers, as I said before I agree with this as a starting point (the font-family rule is particularly needed) while being aware that it might affect existing themes. From what I've seen on Blockbase themes (Blockbase doesn't explicitly set a font-size for the block at all), the placeholder text goes from 13.333px (apparently defined by the browser) to whatever the body font size is, which is much bigger.

**Comment by jasmussen** [comment]
Excellent catches, thanks for such a great review. I have an idea for handling the case you surface, which I want to try.

**Comment by jasmussen** [comment]
Retrying this one, I actually think what you desribe is what we want: if you set the font size on the body to 30px, so should it be inherited all the way down the line. Navigation already inherits, unless you set otherwise:

Screenshot 2021-10-19 at 12 20 43

I think if it affects themes in a negative way, it should be fixed there. Can you think of any themes that might be affected by this?

**Comment by MaggieCabrera** [comment]
> Retrying this one, I actually think what you desribe is what we want: if you set the font size on the body to 30px, so should it be inherited all the way down the line. Navigation already inherits, unless you set otherwise:
> 
> 
> I think if it affects themes in a negative way, it should be fixed there. Can you think of any themes that might be affected by this?

Yeah, I think I agree with you that this is good to have as a base. Ideally, this would be something we could control via theme.json at the very least because I can see how we wouldn't want it to be the case every single time, but it's definitely better than just allowing the browsers to do whatever they want.

It would affect all Blockbase themes and it will require some CSS while we have the ability to control this directly on the block, but I'm personally ok with that.

Skatepark's search block before and after:

Screenshot 2021-10-19 at 12 25 18
Screenshot 2021-10-19 at 12 25 38

Skatepark's pre footer block pattern also uses the search block:

Screenshot 2021-10-19 at 12 26 17
Screenshot 2021-10-19 at 12 26 31

**Comment by jasmussen** [comment]
Oh, so the search block in blockbase currently doesn't have a font size set?

> Ideally, this would be something we could control via theme.json at the very least because I can see how we wouldn't want it to be the case every single time, but it's definitely better than just allowing the browsers to do whatever they want.

Setting the font size appears to work for me already:

```
			"core/search": {
				"typography": {
					"fontSize": "100px",
					"lineHeight": "10px"
				}
			},
```

Screenshot 2021-10-19 at 12 36 11

I'd be happy to keep this PR paused until blockbase has the needed CSS if that's any help.

Edit: for what it's worth, the "after" images for Skatepark look better to me 😅

**Comment by MaggieCabrera** [comment]
> Oh, so the search block in blockbase currently doesn't have a font size set?
> 

No, it doesn't but I'll open a PR right away for it


> Setting the font size appears to work for me already:
> 
> ```
> 			"core/search": {
> 				"typography": {
> 					"fontSize": "100px",
> 					"lineHeight": "10px"
> 				}
> 			},
> ```

Oh that's great! maybe I was thinking the typography control would affect the label instead, I don't remember what happened when I last tried this

> I'd be happy to keep this PR paused until blockbase has the needed CSS if that's any help.

Nope, don't hold on my account, I'll get it sorted for Blockbase asap. The search block is quite recent and this change will mostly affect block themes mainly so my guess is you could go ahead with this change with few issues

**Review by MaggieCabrera — APPROVED** [review]

**Comment by jasmussen** [comment]
Thanks so much for your thoughtful review!

**Comment by MaggieCabrera** [comment]
> > Setting the font size appears to work for me already:
> > ```
> > 			"core/search": {
> > 				"typography": {
> > 					"fontSize": "100px",
> > 					"lineHeight": "10px"
> > 				}
> > 			},
> > ```
> 

Actually, this doesn't work without this PR active, else it will just pick the browser's styles for the input, since the font-size rule is applied to the .`wp-block-search`, so this PR actually fixes that too, that's why it wasn't working when I first tried it myself. Thank you for fixing it!

**Comment by MaggieCabrera** [comment]
Oh, one more thing before this actually gets merged: right now this works fine with the theme.json rules because it's set to inherit, but it's still more specific than said rules:
Screenshot 2021-10-19 at 13 11 10

with this on theme.json: 
```

"core/search": {
				"typography": {
					"fontSize": "var(--wp--preset--font-size--small)",
					"lineHeight": "var(--wp--custom--body--typography--line-height)"
				}
			},
```

**Comment by jasmussen** [comment]
Excellent sleuthing. I'll dive in again before I merge.

**Comment by jasmussen** [comment]
Alright, I rebased again, and pushed a fix to lower specificity. You might need to checkout trunk, delete this branch, and check out this branch fresh lest the rebase messes with things.

**Comment by jasmussen** [comment]
So the change I made was to simply unscope each of the styles. So instead of `.wp-block-search .wp-block-search__button`, we just target `.wp-block-search__button`. This has the following effect on the styles:

- If you provide no styles, or theme.json configuration, the search block will inherit from its parent.
- If you provide font size or other via theme.json, it will inherit from those instead of the parent.
- If you provide font size in your editor styel targetting `.wp-block-search__input` or even plain `input`, this rule will win over both the parent and the global styles rules.

**Comment by MaggieCabrera** [comment]
> Alright, I rebased again, and pushed a fix to lower specificity. You might need to checkout trunk, delete this branch, and check out this branch fresh lest the rebase messes with things.

Thank you for this. It looks to be working as you mentioned ✅

**Comment by jasmussen** [comment]
The React Native test appears to be consistently failing for reasons unrelated to this PR. I'll leave this one for a bit, then rebase and see if that helps.

**Pull request merged**
