### PR TITLE
Block Library - Template Part: Add padding support to template parts

### PR DESCRIPTION
**Pull request by carolinan**
## Description

Adds support for padding to template parts

Related: https://github.com/WordPress/theme-experiments/issues/223

## How has this been tested?

Tested by manually adding a template part in the site editor and adjusting the padding setting.

<del>Because [I can't see the padding visualizer in the site editor](https://github.com/WordPress/gutenberg/issues/29760), I am not sure the changes to edit/index.js actually does anything 😁 </del> -the spacing visualizer was removed.

## Types of changes

Enhancement

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Review by aristath — APPROVED** [review]

**Comment by carolinan** [comment]
https://github.com/WordPress/gutenberg/pull/29779/commits/5299632edc7aafa5b9acb616eb759e1f3659e0bc removed the style attribute that is no longer needed after the merge of https://github.com/WordPress/gutenberg/pull/30332

**Comment by youknowriad** [comment]
That looks good to me, just want to understand how we should make decisions about which block to support or not. 

 - Should we add it to all blocks?
 - Should we add it to container blocks?

I think we should be clear about that and consistent.

Curious about your thoughts here cc @WordPress/gutenberg-core

**Comment by youknowriad** [comment]
The visualizer was removed from the group block but as written today it can't work for blocks that have a single wrapper element and that contain other blocks. that said, I'm pretty sure template part has the same issue.

**Comment by mtias** [comment]
I think we should restrict it to container blocks for now (Group, Columns, Cover, Template Parts). The UI still needs a bit of polish and could be overwhelming to add to other blocks. That said, as it matures and we polish how we present block attributes (maybe split between Settings and Appearance) it might be fine to add it to more blocks. It could help reduce the need for Spacers, though it's also true that reasoning about padding is harder for users.

**Review by youknowriad — APPROVED** [review]
This PR is ready to go regardless of what blocks should support it :)

**Review by aristath — APPROVED** [review]

**Pull request merged**
