### PR TITLE
wp-env: Add phpMyAdmin support

### PR DESCRIPTION
**Pull request by mcsf**
## What?

Adds phpMyAdmin as an optional service to wp-env.

wp-env-phpmyadmin

## Why?

Makes it easier for developers to inspect their wp-env databases, at very little cost.

## How?

- Adds 2 docker-compose services named `phpmyadmin` and `tests-phpmyadmin`.
- ~Adds a switch to `wp-env start` (`--phpmyadmin`) to opt in to the service.~
- Adds extension points in the form of a `.wp-env.json` environment config key (`phpmyadminPort`) and environment variables (`WP_ENV_PHPMYADMIN_PORT`, `WP_ENV_TESTS_PHPMYADMIN_PORT`).

## Testing Instructions
* Run `WP_ENV_PHPMYADMIN_PORT=9000 npx wp-env start`.
* Open `localhost:9000`.
* Verify that phpMyAdmin is available and correctly connected to the `mysql` database service.

* Repeat, but, instead of passing `WP_ENV_PHPMYADMIN_PORT=9000`, edit your `.wp-env.json` file to add the following key-value pair under `env > development` and just run `npx wp-env start`:

```json
{
	"env": {
		"development": {
			"phpmyadminPort": 9000
```

* Repeat but with the testing environment:
  * Try with `WP_ENV_TESTS_PHPMYADMIN_PORT=9003 npx wp-env start` and check that the `tests-phpmyadmin` is correctly launched.
  * Try adding the config under `env > tests` and check that the `tests-phpmyadmin` is correctly launched.

## Checklist

- [X] Question: Is it worth simplifying by, instead of loading port configuration via the config system, just require the port to be provided in the `start` invocation: `npx wp-env start --phpmyadmin=9000`?
- [X] What's the best way to extend this to the test database?

### CODE REVIEW

**Comment by youknowriad** [comment]
Any reason for this to be an option and not something that comes by default?

**Comment by mcsf** [comment]
> Any reason for this to be an option and not something that comes by default?

I started out by just making it on by default. Seeing the `--xdebug` switch is what prompted me to do add an option. But this option is much cheaper than xdebug: it's just adding a lightweight container.

I suppose the only question for me is this: is there any scenario in which a developer may not want to have the database exposed via phpMyAdmin on their local machine, even though they are using `wp-env` (which is intended for development only)? For instance, if a developer changed the default credentials and is assuming that that is enough to protect the WP instance?

**Comment by youknowriad** [comment]
You know what, what bothers me the most is not the fact that these are options, but the fact that they are CLI flags. We already have a config file `wp-env.json` I think these needs to be config options in the file rather than CLI flags.

**Comment by mcsf** [comment]
> You know what, what bothers me the most is not the fact that these are options, but the fact that they are CLI flags. We already have a config file `wp-env.json` I think these needs to be config options in the file rather than CLI flags.

Right now in this PR you can use the config file to provide ports, but not to enable it. But I think that's a good point. 

So is this the UX you'd like to see?

```json
{
	"$schema": "./schemas/json/wp-env.json",
	"core": "WordPress/WordPress",
	"plugins": [ "." ],
	"env": {
                "development": {
			"phpmyadmin": 9000
		},
```

^ where this config automatically enables the phpMyAdmin service. Correct?

I think that's alright. If I have to look for drawbacks, I would say that the CLI options have the benefit of easier discovery: anyone invoking `wp-env start --help` will see that we support both xdebug and phpMyAdmin. But then again maybe I'm overestimating how many people use `--help`.

**Comment by youknowriad** [comment]
> ^ where this config automatically enables the phpMyAdmin service. Correct?

**Comment by youknowriad** [comment]
>  where this config automatically enables the phpMyAdmin service. Correct?

Yes, although I don't like the env subkeys, I think we should get rid of the test+dev env setup at some point, if you want two environments, you just have two config files and trigger two environments. But this is a separate discussion :) 

> I think that's alright. If I have to look for drawbacks, I would say that the CLI options have the benefit of easier discovery

I value consistency, why CLI args just for these particular configs and not all the other ones.

**Comment by mcsf** [comment]
I've removed the `--phpmyadmin` switch, leaving only config options and environment variables. See the PR description, which I've updated accordingly.

**Comment by mcsf** [comment]
Meanwhile, just to document my own decision:

A single phpMyAdmin Docker image is capable of connecting to multiple database hosts. I considered using that to solve the problem of connecting to both the `wordpress` and the `wordpress-tests` databases. However I found that the UI in phpMyAdmin — at least for someone not used to juggling multiple hosts — could lead to users not understanding where they are. Instead, by setting up two distinct phpMyAdmin services, they are more readily distinguishable, since they are listening on different ports, etc. It also matches the fact wp-env sets up two distinct `mariadb` services, even though a single service could keep two databases.

All in all, it's not a huge difference, but the 2-services approach won.

**Comment by youknowriad** [comment]
This is looking good to me, I'll test it better a bit later.

Also, is it enabled by default on some default port or should we actually have to define the port for it to work?

**Comment by youknowriad** [comment]
Can we add a small changelog entry as well.

**Comment by mcsf** [comment]
> Also, is it enabled by default on some default port or should we actually have to define the port for it to work?

The port has to be explicitly defined to enable the service. I think we need a confident answer to this question before we can just turn it on by default:

>  is there any scenario in which a developer may not want to have the database exposed via phpMyAdmin on their local machine, even though they are using wp-env (which is intended for development only)? For instance, if a developer changed the default credentials and is assuming that that is enough to protect the WP instance

I propose merging this PR with the opt-in behaviour and figuring it out separately.

**Review by youknowriad — APPROVED** [review]
This is very cool. Thanks :)

**Pull request merged**
