### PR TITLE
Build: Upgrade husky package to the latest version

### LINKED ISSUE #31967: Upgrade husky package to the latest version
^^

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #31967
Hi @shivapoudel @talldan, how does this look?
Thanks

### CODE REVIEW

**Comment by shivapoudel** [comment]
@RhnSharma Husky 6.0.0 has a lot of changes. Can you migrate husky denoted in `package.json` to the .husky folder?

**Comment by RhnSharma** [comment]
@shivapoudel Could you please explain what I need to do?

**Comment by shivapoudel** [comment]
Plese see the migration guide for husky here https://typicode.github.io/husky/#/?id=husky-4-to-6-cli

**Comment by RhnSharma** [comment]
@shivapoudel  @talldan I migrated husky to version 6. How does this look?
Thanks

**Comment by gziolo** [comment]
I haven't tested it yet, but it looks like everything is on track.

Can you explain why `.husky/.gitignore` file is necessary?

**Comment by shivapoudel** [comment]
@gziolo Inside the `.husky/_` directory there exists `husky.sh` file which is generated on husky install by default and we just need to push only git hooks inside the `.husky` directory. Most importantly this ignorance is also built by husky so no worries.

@RhnSharma Can you also add `"prepare": "husky install",` in the `package.json` script section so that on npm install git hooks are installed? Seems like missing, my friend :)

**Comment by RhnSharma** [comment]
@shivapoudel I added the prepare script to package.json. Please take a look at it and let me know if this needs any changes.
Thanks

**Comment by shivapoudel** [comment]
@gziolo Each step required for husky migration exists in this PR and looks good on my end 👍

**Review by shivapoudel — APPROVED** [review]
@gziolo @RhnSharma Each step required for husky migration exists and looks good on my end 👍

**Review by gziolo — APPROVED** [review]
I took it for a spin and everything works as expected. Nice work. Thank you!

**Pull request merged**
