### PR TITLE
[Mobile] Enable gallery upload options in production

### PR DESCRIPTION
**Pull request by mkevins**
#### Sibling PRs
* `gutenberg-mobile`: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1855
* `WordPress-Android`: https://github.com/wordpress-mobile/WordPress-Android/pull/11234
* `WordPress-iOS`: https://github.com/wordpress-mobile/WordPress-iOS/pull/13374

## Description
This PR enables gallery block upload options in production (on mobile).

## How has this been tested?
**To test:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610#issuecomment-582782265

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by geriux** [comment]
👋 I've just tested this on **iOS** https://github.com/wordpress-mobile/WordPress-iOS/pull/13374

Used different network speeds in each case.

✅Choose from device (stay in editor) - Successful upload
✅Choose from device (stay in editor) - Failed upload
✅Choose from device (leave the editor) - Successful upload
✅Choose from device (close and re-open the editor with ongoing uploads)
✅Take a photo
❗️Choose from the free photo library [_as noted in the test cases on **iOS** only appends the first picture._]

The PRs are in draft, @mkevins is there more work planned on these? Regarding the free photo library, I guess we are going to work on that on a separate PR right? Let me know so I can approve these ones.

Nice work! 👏

**Comment by mkevins** [comment]
Hi @geriux :wave:  Thanks for testing and reviewing

> The PRs are in draft, @mkevins is there more work planned on these? Regarding the free photo library, I guess we are going to work on that on a separate PR right? Let me know so I can approve these ones.

These were in draft mainly because it wasn't clear early on whether the fixes for the known issues would be added to this, or if they'd require significant changes to the diff. It turned out, no major changes were needed, aside from the parent app PRs which have separate PRs to address those issues.

The free photo library fix here https://github.com/wordpress-mobile/WordPress-iOS/pull/13404 targets the related WordPress-iOS PR noted in the description above.

**Review by chipsnyder — APPROVED** [review]
Looks good! Approved with https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610#issuecomment-582782265

**Review by geriux — APPROVED** [review]
Awesome work!! Tested following https://github.com/wordpress-mobile/gutenberg-mobile/issues/1610#issuecomment-582782265 🚀 

LGTM!

**Pull request merged**
