### PR TITLE
Fix group block placeholder buttons color contrast ratio and improve consistency

### LINKED ISSUE #60206: Block placeholder buttons have insufficient color contrast
### Description

When adding a Group block, the block placeholder shows 4 buttons to choose a variation:
- Group
- Row
- Stack
- Grid

Screenshot 2024-03-26 at 10 34 05

Visually, these four buttons contain only an icon. They don't have borders. As such, the icon must meet the color contrast ratio requirements for text.

The color of the icons is `#cccccc` against a white background color, which results in a contrast ratio of only 1.61:1. 

Worth reminding there are two color contrast requirements:
- Text or images of text: at least 4.51:1. There are exceptions for large text. For normal icon buttons the editor by default uses `#1e1e1e`. The reasons is that icon buttons contain only an icon. As such, the icon acts as the 'text' amd must meet the requirement for text.
- Non-text Contrast: the visual presentation of ueer interface components must have a contrast ratio of at least 3:1. This applies to non-text, for example button borders.

In this specific case the icons are pretty big: 44 by 32 pixels. I'm undecided which contrast requirement these icons should meet and I'd appreciate some thoughts. Cc @joedolson 

Anyways, the current ratio of 1.61:1 is too low.

## Overall design

Looking at the broader picture, I'm not sure the design of the placeholder buttons is ideal in the first place. It's also inconsistent with other blocks. Screenshot to compare with the Columns block:

Screenshot 2024-03-26 at 10 34 05 2

- The Columns buttons use a blue color for both the icons and borders. Historically, WordPress always used blue for intereactive controls.
- The Columns buttons do have borders.
- The Columns buttons are bigger, which helps targeting the button.
- More importantly, the The Columns buttons have some visually associated text. Unfortunately, the text doesn't match the accessible name, which is only revealed via a tooltip.
- Anyways, the visible text meets the contrast ratio requirement, as well as the blue used for the buttons.

Instead:
- The Group buttons use a too light gray.
- They aren't blue. As such they don't follow the pattern used by WordPress since ages.
- They don't have borders.
- They are smaller.
- They don't have visible text.

Overall, I'd like to propose to make the Group buttons (and other similar cases if any) look like the Columns one.

### Step-by-step reproduction instructions

- Add a Group block.
- Add a Columns block.
- Observe the Group block placeholder buttons have an insufficient color contrast ratio.
- Observe the design inconsistencies between the Group and Columns buttons.

### Screenshots, screen recording, code snippet

_No response_

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by afercia**
Fixes https://github.com/WordPress/gutenberg/issues/60206

## What?

WIP

### CODE REVIEW

**Comment by afercia** [comment]
This PR aims to fix a few things for the Group block placeholder with variations:
- FIx the color contrast.
- Add visible text to the variations.
- Make the UI consistent with other similar placeholders with variations e.g. the Columns group.

I was able to reuse the `BlockVariationPicker` block editor component.

Screenshot of this PR current state:

Screenshot 2024-03-27 at 16 37 01

Before continuing work on this PR, I'd like to get soem feedback about the variation icons.

The Group block placeholder uses custom icons that are different from the ones of the block variations.
- Observe the Inserter and the block inspector use the default icons from the variations.
- Observe the Group block placeholder uses custom icons.

While I do realize the custom icons in the placeholder resemble more closely the variations layout, I'm not sure using _two different sets_ of icons in the UI is best for users in the first place. To me, that's confusing bcause the Group, Row, Stack, and Grid are represented with different icons in different places of the UI.

_I'd like these icons to be the same everywhere._ Icons should identify the associated concepts in an unique way.

The default variation icons would look like this in the placeholder, which isn't great:

Screenshot 2024-03-27 at 17 03 16

I see two options:
- Either always use the default icons everywhere, but craft a better version of the,
- Or keep the _two different sets of icons_, which isn't great to me. Anyways the custom icons should be modified to not have a fill color.

Cc @WordPress/gutenberg-design

**Comment by t-hamano** [comment]
I agree with improving the contrast ratio and adding text labels. Personally, I don't have a strong preference as to whether to use the default icon for the group block or a custom icon.

Also, if we follow the column block placeholder style, it should probably look like this:

(Please note that the group block icon is a temporary change and is not ideal!)

placeholder_bordered_icon

Alternatively, we may want to remove the _default_ border on the button itself by changing the button style from `secondary` to `tertiary`.

placeholder_no_border

The style of placeholders seems to have been discussed in [this comment](https://github.com/WordPress/gutenberg/pull/43496#issuecomment-1237725622) as well. @jasmussen may have some knowledge.

**Comment by afercia** [comment]
.I would avoid the `tertiary` variant for buttons as it's inherently not accessible. We'd have to start a separate discussion on that. Tertiary buttons with visible text can't be distinguished from normal text other than by their color, which isn't OK.

**Comment by richtabor** [comment]
@jasmussen has been working on improving these also https://github.com/WordPress/gutenberg/pull/59275

**Comment by t-hamano** [comment]
Due to the merge of #59275, the current look of the Group block has changed since this PR was submitted.

image

To move forward this PR, I would like to suggest replacing the `Placeholder` component with the `__experimentalBlockVariationPicker` component.

This would ensure consistency in layout and code with the Column block, and we should be able to remove [this custom CSS selector](https://github.com/WordPress/gutenberg/blob/91472e583cdc139553405969521f59bd84223823/packages/block-editor/src/components/block-variation-picker/content.scss#L3) as well.

**Comment by afercia** [comment]
I'd be totally in favor of using the `__experimentalBlockVariationPicker` consistently. Tp my understanding, the current Group block placeholdeer is basically a copy of `__experimentalBlockVariationPicker` slightly customized only to use an alternative set of icons instead of the ones provided by the block variations. I see this kind of custom, ad-hoc implementation not beneficial for the project because they introduce inconsistency in the UI and maintenance cost in the long term.

Just noting that also the Query block uses `__experimentalBlockVariationPicker`: Insert the Query Loop block > click 'Start blank'. 

I'd suggest to look at the overall usage of `__experimentalBlockVariationPicker` in these three blocks. Screenshot:

Screenshot 2024-06-18 at 15 43 13

Also noting that https://github.com/WordPress/gutenberg/issues/62373 / https://github.com/WordPress/gutenberg/pull/62412 may further help with avoiding custom implementations related to the button icons position and visible text.

**Comment by afercia** [comment]
The color contrast has been fixed in https://github.com/WordPress/gutenberg/pull/62416
I'll create a new issue to address the pending parts (inconsistency and labeling).

**Pull request closed without merging**
