### PR TITLE
Fix double click to edit text of link

### LINKED ISSUE #59525: Link Control: allow double clicking to edit text of link
### Description

When you have a link inside text (paragraph, list item, etc) placing the cursor inside the link shifts focus to the popup, so your cursor leaves the paragraph text. This is new behavior in version 17.8.0 

**Proposed behavior** : The way it has worked in the past: you click inside of a link and your cursor stays, allowing you to type inside the link without having to press `esc`

### Step-by-step reproduction instructions

1. Activate Gutenberg 17.8.0
2. Hyperlink some text inside of a paragraph block. 
3. Place your cursor somewhere else, then try to place it back inside the link.
4. Note that your cursor is gone and the link is focused

### Screenshots, screen recording, code snippet

_Ignore the weirdness of where the popovers sit on the screen, that's a separate Playground issue that's been reported_

https://github.com/WordPress/gutenberg/assets/6867360/bf5288d3-4be6-49a3-a66e-a5a6f021bc99

### Environment info

- Default theme,(tested in other themes as well)
- Only occurs when 17.8.0 is active

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by getdave**
## What?

Fixes https://github.com/WordPress/gutenberg/issues/59525

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/444434/54d99151-76cc-464f-8c33-35714a7f3b7d

### CODE REVIEW

**Comment by scruffian** [comment]
This makes sense to me and solves the issue. I'd like some more eyes on it though as there could be other considerations I missed.

**Review by alexstine — APPROVED** [review]
Approving the code but can't test the actual interaction.

**Comment by annezazu** [comment]
Testing this via playground and found an odd "link is empty" notice but otherwise this works well for double click to edit:

https://github.com/WordPress/gutenberg/assets/26996883/22d58df6-d9fb-4ee0-856a-2d4528c3522a

The only other point of feedback is that if you click inside a link (UI opens), click another word nearby, then click back again it seems to automatically go to edit rather than showing the UI. I'd expect I'd have to do a proper double click again.

**Comment by bacoords** [comment]
Just tested the branch locally and can replicate the same issue as Anne - 

- When you click back on the link text (i.e. the "double click") it works great
- But if you click once (triggering the popover) and then click anywhere else in the block to text that's not linked, the popup stays and you get the link empty notice. 

I'll also note that I tested the button block which has a similar interaction (you click on linked text and the link popover shows up) but the popover doesn't get focus like it does with the paragraph and heading block. Probably outside the scope of this issue, but the inconsistent behavior could probably be addressed in a separate issue.

**Comment by getdave** [comment]
> I'll also note that I tested the button block which has a similar interaction (you click on linked text and the link popover shows up) but the popover doesn't get focus like it does with the paragraph and heading block. Probably outside the scope of this issue, but the inconsistent behavior could probably be addressed in a separate issue.

The Link UI on other blocks will need to be handled separately as you suggest.

**Comment by getdave** [comment]
Closing in favour of https://github.com/WordPress/gutenberg/pull/59635

**Pull request closed without merging**
