### PR TITLE
[Mobile] - Update initial HTML content

### LINKED ISSUE #41979: Update native app test fixtures to reduce console noise
## What problem does this address?
Some of the [initial HTML test fixtures](https://github.com/WordPress/gutenberg/blob/995cc36102acbb083d166fd3fe6da05b6fc1f869/packages/react-native-editor/src/initial-html.js) for the native unit tests reply upon older block version markup. This results in "block updates" occurring [during test runs](https://github.com/WordPress/gutenberg/blob/995cc36102acbb083d166fd3fe6da05b6fc1f869/packages/react-native-editor/src/test/index.test.js#L197-L198) and while using the Demo editor. These updates are unnecessary. Additionally, we are not testing against the latest versions of some blocks, e.g. Gallery block v1 instead v2. 

## What is your proposed solution?
Update the initial HTML test fixtures to use the latest block mark up to avoid unnecessary block updates. For each outdated block in `initial-html.js`, this could be accomplished replacing the outdated block markup with new markup. The new markup could be generated by inserting a given block into a post, switching to HTML mode, and copying the markup.

### PR DESCRIPTION
**Pull request by geriux**
## What?
This PR updates the initial HTML content we use in the demo app.

## Why?
To keep up to date with the current block formats, like the latest List block changes.

## How?
By opening the app and exporting the transformed HTML content.

## Testing Instructions

- CI should check correctly
- Opening the demo app should show the initial HTML content without any issues.

## Screenshots or screencast 

N/A

### CODE REVIEW

**Review by dcalhoun — APPROVED** [review]
This looks great to me. I verified the Demo editor loads. 

Fixes https://github.com/WordPress/gutenberg/issues/41979. I believe we need to remove the [console log expectation](https://github.com/WordPress/gutenberg/blob/995cc36102acbb083d166fd3fe6da05b6fc1f869/packages/react-native-editor/src/test/index.test.js#L197-L198) referenced in that issue to fix the failing tests.

**Comment by geriux** [comment]
> This looks great to me. I verified the Demo editor loads.
> 
> Fixes #41979. I believe we need to remove the [console log expectation](https://github.com/WordPress/gutenberg/blob/995cc36102acbb083d166fd3fe6da05b6fc1f869/packages/react-native-editor/src/test/index.test.js#L197-L198) referenced in that issue to fix the failing tests.

Nice catch! I've updated the test in https://github.com/WordPress/gutenberg/pull/43612/commits/be8b35d55c24ed7bb961dab9199a0202d493923e

Also thanks for the review and for linking that issue 🙇

**Comment by geriux** [comment]
It looks like there's a constant failure on the Android E2E, I will check it out.

**Comment by dcalhoun** [comment]
> It looks like there's a constant failure on the Android E2E, I will check it out.

@geriux this looks like a Gallery V2 performance issue. If I remove 4 or more _Image_ blocks from the Gallery's initial html, then the tests pass. Otherwise, the Demo app crashes during the test. 😞

**Comment by fluiddot** [comment]
> > It looks like there's a constant failure on the Android E2E, I will check it out.
> 
> @geriux this looks like a Gallery V2 performance issue. If I remove 4 or more _Image_ blocks from the Gallery's initial html, then the tests pass. Otherwise, the Demo app crashes during the test. 😞

I'm also experiencing crashes when opening the demo app with the HTML of [`initial-html.js`](https://github.com/WordPress/gutenberg/blob/be8b35d55c24ed7bb961dab9199a0202d493923e/packages/react-native-editor/src/initial-html.js). I see the blocks being rendered and after around a second the app crashes. I tried removing content like the Gallery block but still crashes. Maybe it's related to my local configuration because I tried using the branch `rnmobile/release_1.81.1` and also crashes 🤔. 

**EDIT 1:** I'm going to test the demo app on a real device to discard that the issue only happens on the simulator.
**EDIT 2:** On a real device I can't reproduce the crash so might be related to the emulator environment 🤔 .

**Comment by geriux** [comment]
> @geriux this looks like a Gallery V2 performance issue. If I remove 4 or more _Image_ blocks from the Gallery's initial html, then the tests pass. Otherwise, the Demo app crashes during the test. 😞

I think it's not related to the Gallery block, but the size of the content. I've deleted other blocks and kept the Gallery block and it worked. 

Since now the List and Gallery blocks use Inner blocks it increased the size of the content and it looks like something is going on with Android 🤔 

So for now to unblock this PR I'll remove some duplicated blocks and maybe we can keep investigating this issue?

**Comment by dcalhoun** [comment]
> I think it's not related to the Gallery block, but the size of the content. I've deleted other blocks and kept the Gallery block and it worked.
> 
> Since now the List and Gallery blocks use Inner blocks it increased the size of the content and it looks like something is going on with Android 🤔

Yikes! This size of post content causing performance issues/crashes is definitely not good. 😞 Hopefully we can prioritize investigating and resolving this. 

> So for now to unblock this PR I'll remove some duplicated blocks and maybe we can keep investigating this issue?

That makes sense to me. 👍🏻

**Comment by geriux** [comment]
> Yikes! This size of post content causing performance issues/crashes is definitely not good. 😞 Hopefully we can prioritize investigating and resolving this.

But this is happening when I run the test though. If I run the demo app as we usually do, it loads correctly without crashing.

**Review by dcalhoun — APPROVED** [review]

**Comment by geriux** [comment]
I've removed all headings (that were used as titles and not for testing the actual `Heading` block) to reduce content. If Android tests pass I'll merge and create a follow-up issue to investigate this problem. I expect we might encounter it when we add more test cases.

**Comment by fluiddot** [comment]
> But this is happening when I run the test though. If I run the demo app as we usually do, it loads correctly without crashing.

During my testing, I experienced the crash also when running the demo app as we usually do. However, only happened when using a simulator, with a real device it worked well. Definitely, this is something we should investigate as a follow-up task, it might be covering unknown critical issues. What do you think about creating a new GitHub issue outlining this problem?

**Comment by geriux** [comment]
> During my testing, I experienced the crash also when running the demo app as we usually do. However, only happened when using a simulator, with a real device it worked well. Definitely, this is something we should investigate as a follow-up task, it might be covering unknown critical issues. What do you think about creating a new GitHub issue outlining this problem?

That's interesting, I tried several times with the simulator and I didn't have any issues.

Yes, I have a draft of the issue. Just waiting for CI to confirm if it solved this by removing some blocks. (It did locally but who knows in CI).

**Comment by fluiddot** [comment]
> That's interesting, I tried several times with the simulator and I didn't have any issues.
> 
> Yes, I have a draft of the issue. Just waiting for CI to confirm if it solved this by removing some blocks. (It did locally but who knows in CI).

If we're experiencing the crash with different content sizes, looks like this might be related to the device. Curiously enough, I couldn't manage to find a reliable stacktrace related to the crash, maybe this is an indication that is a memory pressure issue 🤔 .

**Pull request merged**
