### PR TITLE
Scripts: Clean up the build folder via clean-webpack-plugin

### LINKED ISSUE #23134: Scripts: Clean up the build folder via clean-webpack-plugin
**Is your feature request related to a problem? Please describe.**
Currently, when using a webpack config with multiple entry points and removing one, the old build files for the removed entry point remain in the build folder.

Another case is source maps which are created during the watch task but not used in the production builds.

**Describe the solution you'd like**
The [webpack documentation](https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder
) recommends to use the popular [clean-webpack-plugin](https://www.npmjs.com/package/clean-webpack-plugin) plugin. We'd have to add it as a new dependency and adjust the plugins config to include `new CleanWebpackPlugin()`.

**Describe alternatives you've considered**
Adding a `prebuild` npm script which cleans up the folder.

### PR DESCRIPTION
**Pull request by ocean90**
## Description

Adds [clean-webpack-plugin](https://www.npmjs.com/package/clean-webpack-plugin) as a default plugin to webpack config.

Fixes #23134.

## How has this been tested?
* Create a custom block setup for example with @wordpress/block
* Start the watch command and notice the source map files for CSS files
* Stop the watch command and run the build command
* The source map files should be removed now

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
Good thinking, it’s quite annoying when testing that old files remain in the build folder🙁 I will test tomorrow

**Review by gziolo — APPROVED** [review]
This is great, I really like how it works 💯 

Should we add it for the Gutenberg project as well in a follow-up PR (it uses a different config file for webpack)? :)

**Comment by ocean90** [comment]
> Should we add it for the Gutenberg project as well in a follow-up PR (it uses a different config file for webpack)? :)

Maybe? Currently is uses `pre`-scripts to delete much more than just webpack assets.

https://github.com/WordPress/gutenberg/blob/5ed6b58237d60c99820c2d6f80510a20dc269d32/package.json#L193-L194

**Comment by gziolo** [comment]
> Maybe? Currently is uses pre-scripts to delete much more than just webpack assets.

Both are unrelated to webpack:
- build folders for packages are generated with Babel
- types are generated with TypeScript

Webpack controls the `/build` folder only.

**Pull request merged**
