### PR TITLE
DataViews: Restore focus style in Grid view

### PR DESCRIPTION
**Pull request by t-hamano**
Related to #64209

## What?

This PR restores the outline when the preview button is focused in the grid layout.

image

## Why?

This is because `overflow: hidden` is applied to the `.dataviews-view-grid__media` element that wraps the button.

## How?

According to [this comment](https://github.com/WordPress/gutenberg/pull/64209#discussion_r1703803664), it seems that this is to prevent the preview from going outside the container, but since the button component itself has `overflow: hidden`, I was not able to reproduce the problem in my testing.

Template:
https://github.com/WordPress/gutenberg/blob/f12b78b7c4e830032d7f9a4641df40236644683b/packages/edit-site/src/components/page-templates/style.scss#L14

Page:

https://github.com/WordPress/gutenberg/blob/f12b78b7c4e830032d7f9a4641df40236644683b/packages/edit-site/src/components/post-list/style.scss#L43

Patterns:
https://github.com/WordPress/gutenberg/blob/f12b78b7c4e830032d7f9a4641df40236644683b/packages/edit-site/src/components/page-patterns/style.scss#L27

### Testing Instructions for Keyboard

- Visit the Pages, Templates, and Patterns grid layout.
- Use the tab key to focus the preview button.
- You should see an outline.

### CODE REVIEW

**Comment by jameskoster** [comment]
Shoot, I know you fixed this one before, apologies. 

So the issue occurs on the Patterns and Templates grids. The preview bleeds outside of the container:

Screenshot 2024-08-06 at 13 25 54

**Comment by jameskoster** [comment]
Applying `border-radius` to `.page-templates-preview-field` and `.page-patterns-preview-field` is another way to fix.

**Comment by t-hamano** [comment]
That's strange, I checked the Patterns page in this PR and the preview doesn't bleed outside of the container. Is there a way to confirm that problem?

image

**Comment by jameskoster** [comment]
> Is there a way to confirm that problem?

It's a bit easier to see if you change the site background to a dark color. You'll notice the previews have square corners:

Screenshot 2024-08-06 at 18 13 07

If you zoom in on your screenshot and turn brightness up to maximum you can just about see it :)

**Comment by t-hamano** [comment]
Thank you, I could see the issue with a dark site background color. I used the new standard `$radius-medium` to apply `4px`, which is correct, right?

image

**Comment by jameskoster** [comment]
> I used the new standard $radius-medium to apply 4px, which is correct, right?

This may get revised when we apply the variables across, but for now it's fine :)

**Review by jameskoster — APPROVED** [review]

**Pull request merged**
