### PR TITLE
Revert "Patterns: fix capabilities settings for pattern categories

### PR DESCRIPTION
**Pull request by glendaviesnz**
This reverts commit 5b10d27ec406cbdec84e14408cd350ba9e8c544a.

## What?
Reverts the changes made in #55379 that prevents Author level users from adding pattern categories. 

## Why?
It was thought that Authors should be able to choose from existing categories but not add new ones, and this is probably still the idea, but there are potential issues with modifying the taxonomy capabilities to disallow this, [as mentioned here](https://github.com/WordPress/wordpress-develop/pull/5510#issuecomment-1772921357). The best option is probably to back this out and leave it with authors able to add new pattern categories at this point in the 6.4 release cycle.

## How?
A straight revert of 5b10d27ec406cbdec84e14408cd350ba9e8c544a.

## Testing Instructions
- Log in as a site admin or editor and add a new pattern and assign some new categories and make sure they save and can be viewed as expected in site editor patterns pages and in the post editor inserter patterns tab
- Don't test the Author user as they can't view the categories they add until the [change noted here](https://github.com/WordPress/gutenberg/pull/55532#issuecomment-1773894853) is reimplemented

### CODE REVIEW

**Comment by glendaviesnz** [comment]
If we do revert this we will need to then reimplement [this one change](https://github.com/WordPress/gutenberg/pull/55532/files#diff-fec6390e24332dec4a0c7c74f9f7b9a015ce191e0e6348361ead793ceda3991dL654) in a new PR following that revert to allow author and contributor users to view the user category lists - and this change will need to be backported.

**Comment by hellofromtonya** [comment]
For awareness @SiobhyB, this revert is needed for the npm packages update for 6.4 RC2.

**Review by hellofromtonya — APPROVED** [review]
It's a full revert of 5b10d27ec406cbdec84e14408cd350ba9e8c544a  👍

**Comment by hellofromtonya** [comment]
>If we do revert this we will need to then reimplement [this one change](https://github.com/WordPress/gutenberg/pull/55532/files#diff-fec6390e24332dec4a0c7c74f9f7b9a015ce191e0e6348361ead793ceda3991dL654) in a new PR following that revert to allow author and contributor users to view the user category lists - and this change will need to be backported.

Once this revert is merged, @glendaviesnz notes a follow-up fix is needed for `wp/6.4`.

**Comment by glendaviesnz** [comment]
@hellofromtonya the PR for the fix that needs to be included in 6.4 [is here](https://github.com/WordPress/gutenberg/pull/55553) - I will get one of our team to review it, but may not be until tomorrow, but it is pretty straightforward so feel free to review and merge if you have time.

**Comment by hellofromtonya** [comment]
Thank you @glendaviesnz! Once PR #55553, it can be cherry-picked for `wp/6.4`. I'll give the 6.4 Editor Tech Leads a heads up in that PR.

**Pull request merged**
