### PR TITLE
Added Global Documentation in several php file

### PR DESCRIPTION
**Pull request by shail-mehta**
Added Global Documentation in below files.

- lib/compat/wordpress-6.6/html-api/class-gutenberg-html-decoder-6-6.php
- lib/compat/wordpress-6.7/html-api/class-gutenberg-html-decoder-6-7.php

### CODE REVIEW

**Review by t-hamano — APPROVED** [review]
LGTM!

If you have time, could you also submit a ticket and patch to core?

This method already exists in core, but there is no `@global` comment yet:

https://github.com/t-hamano/wordpress-develop/blob/a3520d2720f6d434b78346dd53cb38ec88c74bcb/src/wp-includes/html-api/class-wp-html-decoder.php#L172-L206

**Comment by shail-mehta** [comment]
@t-hamano I have created ticket with Patch in core.

**Ticket Link**: https://core.trac.wordpress.org/ticket/61968

**Comment by dmsnell** [comment]
Thanks @t-hamano and @shail-mehta 

We need to ensure that we don't modify these files in Gutenberg apart from backporting code from Core otherwise it causes confusion with diverging code, and could lead to missing changes that get wiped out in updates from Core.

**Comment by t-hamano** [comment]
@dmsnell Thanks for letting us know.

I'm wondering why the GitHub Actions to trigger the backport didn't work for this PR.

It certainly seems to have failed:

https://github.com/WordPress/gutenberg/actions/runs/10643611309/job/29507361534

Moreover, it's failing in most other branches, too:

https://github.com/WordPress/gutenberg/actions/workflows/check-backport-changelog.yml

**Comment by dmsnell** [comment]
@t-hamano I'm not familiar with that test, but the HTML API is different than many of the backporting flows as it's code that originates in Core and comes over to Gutenberg. it's not sourced in Gutenberg and then pushed into Core.

I'd love to have patches blocked in Gutenberg as this has been a persistent problem, but I'm not sure how to do that in a way that doesn't block people. perhaps an auto-comment on any PR touching these files that says "Please don't do this; file a Trac ticket in Core and update the source of the code." would help.

Beyond this, _we should not update old branches_ as is done here because it takes the code out of sync. That part of this change _will_ be overwritten, even though it's benign, being only a comment.

The whole process is confusing and so I understand where it seems like it ought to be changed here.

**Comment by t-hamano** [comment]
@dmsnell Thank you for the detailed explanation.

Ideally, we need to submit a core ticket and then backport it from WordPress to Gutenberg after the patch is committed, right?

BTW, I misunderstood. Apparently, [this GitHub Action](https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/check-backport-changelog.yml) should fail when a PR containing changes to PHP files is submitted, to encourage backporting to core. I don't know why I was able to merge this PR, but maybe I missed something.

Either way, I'll be more careful in the future.

**Comment by shail-mehta** [comment]
Thank you for the Detailed Explanation @dmsnell 

 I'll be take care of this in the future.

**Comment by dmsnell** [comment]
> Ideally, we need to submit a core ticket and then backport it from WordPress to Gutenberg after the patch is committed, right?

Yep! The HTML API is developed in Core and ported into Gutenberg so that it can use updates before they are available in the release, and so that Gutenberg code running on older versions of Core can still use the updated features of the HTML API.

> Apparently, [this GitHub Action](https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/check-backport-changelog.yml) should fail when a PR containing changes to PHP files is submitted, to encourage backporting to core.

I'm not sure either, but it looks like that job is focused on changes going the other direction: it's to ensure that when people update PHP code that lives in the Gutenberg repo, that it gets properly ported into Core. If I'm understanding it properly, it would never apply to the HTML API.

> I'll be take care of this in the future.

No big deal if it happens again, @shail-mehta - but I just want to clarify so people understand, and so we can get more eyes on this to prevent it in the future.

**Pull request merged**
