### PR TITLE
add typography options to list component

### PR DESCRIPTION
**Pull request by kirilzh**
## Description
Addresses: #25725

Adds typography controls to the list block.

## Screenshots 
image

## Types of changes
Non-breaking change.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by skorasaurus** [comment]
Thanks for the contribution; I briefly tested the options; (I didn't use a block-based theme that would use theme.json; just used twentytwenty and maxwell themes) and it works as expected. 


The ability for users to access block options like this should be programmatically controlled and that  
should/could be addressed in https://github.com/WordPress/gutenberg/issues/20588

**Comment by paaljoachim** [comment]
The user interface looks good. Thank you for adding the typography panel to the List block, Kiril!

Before:
Screen Shot 2020-10-21 at 11 37 21

After:
Screen Shot 2020-10-21 at 11 39 23

**Comment by ItsJonQ** [comment]
@kirilzh Thanks for adding this 🎉 .

I tested it locally. For some reason, only the custom font size is working for me. The FontSizePicker doesn't allow for me to choose a different size (e.g. "Small").

This may very well be that my local dev environment is messed up and unhappy.

To double check, would someone be able to confirm that the changing the font-size to preset values work? (e.g. Small or Large)

Thanks!

**Review by ItsJonQ — APPROVED** [review]
🚀 from me! Tested locally, and the FontSize controls are working for the List block (as expected).

Thank you @kirilzh !

**Pull request merged**
