### PR TITLE
Convert to blocks: put unhandled HTML in HTML block, correct invalid lists

### LINKED ISSUE #12029: Convert to blocks does not handle invalid lists and HTML without block equivalent
## How to reproduce 

* Create a new post, go to code editor mode, and paste [this content](https://github.com/WordPress/gutenberg/files/1527889/post.html.txt).
* Change to visual mode. The content should be fully renderer in one block - the classic block.
* Check the document stats: it's 10.605 words long.
* Convert it to blocks. [This](https://github.com/WordPress/gutenberg/files/2594485/demo-converted.html.txt) is the resulting content.
* Check the document stats: it's 8.269 words long.

Observe that one of the last sections was entirely gone (anything following the "Una panorámica general de las herramientas"). I expected no content was lost.

Note that the post has some really bad-formatted HTML and I don't expect Gutenberg to fix that.

## Data

| | | |
| --- | --- | --- |
| Original post in classic | [HTML](https://github.com/WordPress/gutenberg/files/2599794/post-classic-editor.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2599776/post-classic-editor.txt) |
| Post converted to blocks 489eb79^1 | [HTML](https://github.com/WordPress/gutenberg/files/2599795/post-gutenberg-converted-before-489eb79.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2599775/post-gutenberg-converted-before-489eb79.txt) | 
| Post converted to blocks at 489eb79 |  [HTML](https://github.com/WordPress/gutenberg/files/2600052/post-gutenberg-converted-at-489eb79.html.txt) | [Visual](https://github.com/WordPress/gutenberg/files/2600050/post-gutenberg-converted-at-489eb79.txt) |

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
Fixes #12029.

> After a quick look at the diffs and pasted content, it seems to me that the problem is (an) unhandled `<dl>` element(s).
>
> Previously we would unwrap the element, then the block normaliser would merge the lines into a paragraph. Not ideal, but the content wasn't lost.
>
> Now we preserve the tag, but there is no handler for `dl`.

Also restores correcting invalid list HTML.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by iseulde** [comment]
@nosolosw How does this look?

**Comment by youknowriad** [comment]
I know @jorgefilipecosta tried something similar recently for the `pre` handling? how is this related? and I know he faced some issues, so pinging for context.

**Comment by iseulde** [comment]
Moving to 4.5, feel free to punt if needed.

**Review by youknowriad — APPROVED** [review]
Tests and code look good to me 👍

**Comment by iseulde** [comment]
Thanks @youknowriad!

**Review by jorgefilipecosta — COMMENTED** [review]
I did an extensive set of tests and everything looked in my tests, and the code looks correct 👍
I tried to understand the relation of this changes with the changes in https://github.com/WordPress/gutenberg/pull/11244 and I think https://github.com/WordPress/gutenberg/pull/11244 is still needed.
What happens now if we call ```wp.blocks.unregisterBlockType('core/preformatted');``` and we paste ```<pre>aaaaa</pre>``` is that we get an HTML block with a pre tag but empty content because when the content arrives at the function that creates the HTML block it was already filtered in accordance with the schema of the code block and the invalid text child was removed.

**Pull request merged**
