### PR TITLE
Social Links: update Facebook's color to match brand guidelines

### PR DESCRIPTION
**Pull request by jeherve**
## What?

This PR updates Facebook's icon color in the Social Links block, to match the brand guidelines defined by Meta.

See the guidelines defined here:
https://about.meta.com/brand/resources/facebook/logo/

## Why?

This change updates the Facebook icon to match other Facebook representations one can find online.

## How?

| **Before** | **After** |
|--------|--------|
| Screenshot 2024-04-03 at 14 57 00 | Screenshot 2024-04-03 at 14 56 34 | 

## Testing Instructions

1. Open the site editor
2. Insert a Social Links block
3. Insert a Facebook icon, and give it a URL.
4. Save your changes.
5. The Facebook icon you see on the frontend should match the icon seen on [this page](https://about.meta.com/brand/resources/facebook/logo/).

### Testing Instructions for Keyboard

No changes here.

## Screenshots or screencast

See above

### CODE REVIEW

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

- WordPress: 6.5
- PHP: 8.3.0-dev
- Server: PHP.wasm
- Database: WP_SQLite_Translator (Server: 5.5 / Client: 3.40.1)
- Browser: Chrome 123.0.0.0
- OS: macOS
- Theme: Twenty Twenty-Four 1.1
- Plugins:
  * Gutenberg 18.1.0-rc.1

**Test Results -**  Changes look fine and working as expected. 

**Demo /  Screencast -** 

| Before | After |
|--------|--------|
| Screenshot 2024-04-03 at 10 26 14 PM | Screenshot 2024-04-03 at 10 27 11 PM |

**Comment by jeherve** [comment]
This issue is still valid. I've just updated it with latest `trunk`.

@talldan As someone who recently worked on the block and its colors in #63049, would you be able to review this PR?

Thank you!

**Review by talldan — APPROVED** [review]
LGTM, thank you!

**Comment by talldan** [comment]
The failing tests for node.js 22 were fixed in #63728. I don't think it's worth rebasing this PR again for such a small change, I'll merge keep an eye on it to make sure it passes in `trunk`.

**Comment by jeherve** [comment]
Thank you!

**Pull request merged**
