### PR TITLE
[Mobile]Update caret position on insert link

### PR DESCRIPTION
**Pull request by pinarol**
## Description
Fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/679 

## How has this been tested?

Steps described in the gutenberg-mobile PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/716

## Types of changes
Whenever we insert/update a link we now put a flag(`needsSelectionUpdate`) inside the change event so that we are able to know we need to update caret position at aztec side.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

### CODE REVIEW

**Review by mzorz — APPROVED** [review]
LGTM :shipit:

**Review by SergioEstevao — APPROVED** [review]
Working great!

**Comment by pinarol** [comment]
hey @mzorz I added this commit, a1e2ab11a85dc1f00638d1278ae86a8cd03bf2b5
could you be able to check again? thanks

**Review by mzorz — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
