### PR TITLE
Babel Preset: Update Babel packages to 7.16 version

### PR DESCRIPTION
**Pull request by gziolo**
## Description

The announcement post from Babel for 7.16.0 release:
https://babeljs.io/blog/2021/10/29/7.16.0.html

This PR contains mostly updates to packages that Babel preset uses. It also includes some enforced changes to the ESLint presets that use now `@babel/eslint-parser` instead of the deprecated `babel-eslint`.

### `@wordpress/babel-preset-default`

 -   The bundled `@babel/core` dependency has been updated from requiring `^7.13.19` to requiring `^7.16.0`.
 -   The bundled `@babel/plugin-transform-react-jsx` dependency has been updated from requiring `^7.12.7` to requiring `^7.16.0
 -   The bundled `@babel/plugin-transform-runtime` dependency has been updated from requiring `^7.13.10` to requiring `^7.16.0`.
 -   The bundled `@babel/preset-env` dependency has been updated from requiring `^7.13.10` to requiring `^7.16.0`.
 -   The bundled `@babel/preset-typescript` dependency has been updated from requiring `^7.13.10` to requiring `^7.16.0`.
 -   The bundled `@babel/runtime` dependency has been updated from requiring `^7.13.10` to requiring `^7.16.0`.
 -   The bundled `browserslist` dependency has been updated from requiring `^4.16.6` to requiring `^4.17.6`.
 -   The bundled `core-js` dependency has been updated from requiring `^3.12.1` to requiring `^3.19.1`.

###  `@wordpress/eslint-plugin`

-   Replaced deprecated `babel-eslint` dependency with `@babel/eslint-parser`.
 -   The bundled `eslint-plugin-import` dependency has been updated from requiring `^2.23.4` to requiring `^2.25.2`.

### `@wordpress/scripts`

- The bundled `browserslist` dependency has been updated from requiring `^4.16.6` to requiring `^4.17.6`.
-   Updated the default ESLint config to work correctly with the latest version of `@wordpress/eslint-plugin`.

## How has this been tested?

I executed the following commands locally:

- `npm run build`
- `npm run dev`
- `npm run lint-js`
- `npm run test-unit`
- `npm run test-e2e`
- `npm run storybook:build`

I also tested Create Block integration with `@wordpress/scripts`:

`./bin/test-create-block.sh`

## Types of changes

Update of the Babel packages.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
@andrewserong and @adamziel - it would be great to land this PR as part of the Gutenberg 11.9 release so we propagate all the changes related to Babel to WordPress core.

We can cherry-pick that later if you don't feel confident landing it today. The changes impact only the runtime code that Babel uses with all WordPress packages.

**Comment by andrewserong** [comment]
Thanks for the ping @gziolo, the RC has already gone out so this will need to be cherry-picked into the release once it lands. Will that be an issue with all the `package-lock.json` changes? (E.g. if other PRs get merged before this one lands, it could potentially be tricky to cherry pick it into the release). 

I've added this PR to the tracking issue for PRs that will need to be cherry picked for 11.9 in #36274

**Comment by andrewserong** [comment]
We're close to releasing GB 11.9, so I've updated the milestone on this PR to GB 12.0 and added the Backport to WP Beta/RC label. Once this lands in GB 12.0, I believe it should still be able to be cherry picked into WP 5.9?

**Comment by gziolo** [comment]
Gutenberg 11.9 is out so let’s give it a try. I don’t expect any issues since there were no CI issues.

**Pull request merged**
