### PR TITLE
Docs: Clarify how to update a dependency for existing packages

### PR DESCRIPTION
**Pull request by gziolo**
## Description
This is a follow-up for #16876 where I added some hints on how to add a new dependency to one of the WordPress packages. This time I add more details for removing and updating dependencies.

It was triggered by the discussion in #16875. I tested it myself when upgrading ESLint and its plugins to the latest version in #16921.

Preview new version of docs here:
https://github.com/WordPress/gutenberg/blob/db23b8c4abeb6c8711060e78cfbab1648ad7f27a/packages/README.md#managing-dependencies

### CODE REVIEW

**Review by ellatrix — APPROVED** [review]

**Comment by ellatrix** [comment]
My biggest problem was that I assumed `npm install` generates a good lock file based on all `package.json` files. This turned out to be false. It would be col if somehow `npm install` resolves everything behind the scenes.

**Comment by gziolo** [comment]
> My biggest problem was that I assumed `npm install` generates a good lock file based on all `package.json` files. This turned out to be false. It would be col if somehow `npm install` resolves everything behind the scenes.

Yes, the issue is that for some reasons `npm install` puts those dependencies inside `node_modules` folder of the package, but we want to hoist them to the root `node_modules` folder.

**Comment by dsifford** [comment]
> but we want to hoist them to the root `node_modules` folder.

Doesn't `lerna bootstrap --hoist` do that?

**Comment by gziolo** [comment]
> > but we want to hoist them to the root `node_modules` folder.
> 
> Doesn't `lerna bootstrap --hoist` do that?

Did you try or do you guess?

**Comment by dsifford** [comment]
> > > but we want to hoist them to the root `node_modules` folder.
> > 
> > Doesn't `lerna bootstrap --hoist` do that?

> Did you try or do you guess?

Both! Recall that's what I did first before talking to you originally about this.

**Comment by gziolo** [comment]
> Both! Recall that's what I did first before talking to you originally about this.

Can you advice how the process should look like with `lerna bootstrap`? Is it significantly better to what I proposed?

**Comment by dsifford** [comment]
I _believe_ it would prevent having to remove and re-add packages when attempting to update a nested dependency. You should in theory just have to update the package.json and bootstrap.

There's not a ton different I suppose than to what you're describing so it might just be easier for everyone to stick with what you wrote since everybody knows the `npm install` command already.

**Review by dsifford — APPROVED** [review]

**Comment by gziolo** [comment]
> I _believe_ it would prevent having to remove and re-add packages when attempting to update a nested dependency. You should in theory just have to update the package.json and bootstrap.

It seems to be a bit easier when I read it :) I merged this PR to have any hints present but I will give it a go and see if I can further refine docs. Thanks!

**Pull request merged**
