### PR TITLE
Fix drop target visibility for last block

### PR DESCRIPTION
**Pull request by talldan**
## Description
When dragging a block to the end of a block list the visibility of the drop target indicator is unreliable. Currently, a class is being used on the BlockListAppender to indicate the drop target, but the BlockListAppender is often hidden when not needed, which results in the drop target not being displayed.

This PR moves responsibility for displaying the drop target to the last block in the list, which should always be present.

Along with #23638 the known issues with the drop target not being displayed should be resolved.

## How has this been tested?
1. Try dragging to the end of a block list
2. Observe that the drop target should appear.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for improving drag and drop. 

I'm not quite sure what to look for, though, I'm seeing this in both this and the master branch:

lastblock

**Comment by ellatrix** [comment]
> This PR moves responsibility for displaying the drop target to the last block in the list, which should always be present.

What if there are no blocks (empty block list or post)?

**Comment by talldan** [comment]
@ellatrix Good point!

@jasmussen I think it's most noticeable in the navigation block when trying to drag a link from a submenu to the parent block. There's some logic for hiding the appender that was added recently, so this is a side-effect of something intentional.

I definitely feel like I've seen something similar happen in the main block list where the appender is not visible, but not sure exactly how to reproduce.

**Comment by talldan** [comment]
Closing this, right now I don't plan on revisiting it.

**Pull request closed without merging**
