### PR TITLE
Try: Fix preview test.

### PR DESCRIPTION
**Pull request by jasmussen**
## What?

Followup to #45074. It wasn't entirely clear to me whether the tests passed or not, but it appears there may have been a hiccup looking at https://github.com/WordPress/gutenberg/pull/45074/files. If the tests pass on this PR, then that's the case.

### CODE REVIEW

**Comment by jasmussen** [comment]
The tests keep failing here, and based on the artifacts I can't tell if it's a problem of the test fix, or the tests themselves. I'd love input here:

[video.webm](https://user-images.githubusercontent.com/1204802/196528094-bc2413e6-18be-44dc-9ffe-28f7f039b9e5.webm)

**Comment by annezazu** [comment]
Alright! Looks like one is failing. cc @ockham and @michalczaplinski can you all help out here to figure out what's going on? Adding to backport once more for now.

**Comment by ramonjd** [comment]
I've merged an alternative PR here: https://github.com/WordPress/gutenberg/pull/45087

I added the backport label to that one. Will remove from this one.

**Comment by jasmussen** [comment]
Thank you!

**Pull request closed without merging**
