### PR TITLE
Import Format API components instead of passing as props

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Refactoring. See https://github.com/WordPress/gutenberg/pull/11488#discussion_r231026187.

## How has this been tested?
Ensure toolbar buttons work, shortcuts work, an the inline image button works. Also ensure that searching for the inline image button works in the inserter.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Comment by gziolo** [comment]
Cool, thanks for working on it. I quickly checked the code and it looks exactly as I would expect. I need to take a closer look before I give 👍

**Comment by iseulde** [comment]
On thing I'm not sure about is naming.

**Comment by mtias** [comment]
The naming of the components?

**Comment by iseulde** [comment]
Yeah, I just prefixed them all with `RichText`. I guess that's fine. :)

**Review by gziolo — APPROVED** [review]
Awesome, tests well. Code looks good, too 👍 

> Why not just `RichTextInserterItem`, as any rich text item in there will be automatically inline?

Yes, true. It's also shorter.

**Pull request merged**
