### PR TITLE
Restrict nonce sent by nonceMiddleware to URLs starting with site_url()

### LINKED ISSUE #13491: API Fetch: Avoid adding nonce if not assured to be requesting a WordPress resource
Related: https://github.com/Automattic/wp-calypso/pull/30332#issuecomment-456758921

There's no reason `@wordpress/api-fetch` can't or shouldn't be used to fetch resources outside of WordPress, as out-of-the-box it serves as a minimal wrapper for the [browser `fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

This still holds true even when configured to use the nonce middleware. If the requested resource can be determined to not be from a WordPress site, the nonce should not be attached.

Implementation-wise, there may be a challenge here in configuring that the nonce middleware should only apply to specific URLs, which could as well be impacted separately by the `createRootURLMiddleware`.

Possible implementations:

- Search the requested path for the presence of `/wp-json/`
   - This is probably too naive, since a site's API root can be re-configured from the default
- Allow as an option to `createNonceMiddleware` a callback which, given a URL or the full request options object, returns `true` or `false` corresponding to whether the nonce should be added
   - This becomes a burden on the consumer to implement
- Allow as an option to `createNonceMiddleware` a hostname string for which the nonces are valid.
   - What about multi-site (or, specifically, sub-directory sites where hostname may be the same across multiple sites in a network)

### PR DESCRIPTION
**Pull request by adamziel**
## Description
Resolves https://github.com/WordPress/gutenberg/issues/13491

This PR:
1) Restricts the nonce to requests sent to URLs starting with `site_url()`
2) Makes the presence of the nonce configurable both globally and on per-request basis

The following core patch is needed to pass the site URL to the middleware:
```diff
diff --git a/src/wp-includes/script-loader.php b/src/wp-includes/script-loader.php
index 8745ea42f6..e65c6b1d47 100644
--- a/src/wp-includes/script-loader.php
+++ b/src/wp-includes/script-loader.php
@@ -293,8 +293,9 @@ function wp_default_packages_inline_scripts( $scripts ) {
                        "\n",
                        array(
                                sprintf(
-                                       'wp.apiFetch.nonceMiddleware = wp.apiFetch.createNonceMiddleware( "%s" );',
-                                       ( wp_installing() && ! is_multisite() ) ? '' : wp_create_nonce( 'wp_rest' )
+                                       'wp.apiFetch.nonceMiddleware = wp.apiFetch.createNonceMiddleware( "%s", { siteUrl: "%s" } );',
+                                       ( wp_installing() && ! is_multisite() ) ? '' : wp_create_nonce( 'wp_rest' ),
+                                       esc_js( site_url() )
                                ),
                                'wp.apiFetch.use( wp.apiFetch.nonceMiddleware );',
                                'wp.apiFetch.use( wp.apiFetch.mediaUploadMiddleware );',
```

What would be the best way to get it in? Create a trac ticket and https://github.com/WordPress/wordpress-develop PR?

## How has this been tested?

1. Make sure all tests pass
1. Test the editor on a multi site
1. Test the editor on a regular site

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by draganescu** [comment]
> What would be the best way to get it in? Create a trac ticket and https://github.com/WordPress/wordpress-develop PR?
Yes !

**Comment by whyisjake** [comment]
Does it make sense to try to get this into the next minor release? (Currently slated for October 29th)

**Comment by TimothyBJacobs** [comment]
How are you feeling about this @adamziel? I ran into another use case. If you are utilizing App Passwords to connect to another WordPress site, using `apiFetch` is very helpful since you are talking to a WP REST API, but you don't want to be attempting nonce authentication.

**Comment by adamziel** [comment]
This PR is now ~2 years old and I moved on to other tasks since then so I'm closing this one. If you could use the changes proposed here, feel free to pick up this PR!

**Pull request closed without merging**
