### PR TITLE
Blocks: Merge paragraph and cover text blocks

### LINKED ISSUE #2448: Consider merging Text and Cover Text
The Cover Text block is super cool. It adds an optional background and text color to the plain paragraph block, as well as a sizing slider, allowing for some really nice expressive layouts. It's so cool, that we should consider merging it with the basic paragraph block. 

Also because as noted in [the design document](https://github.com/WordPress/gutenberg/blob/master/docs/design.md#advanced-settings):

> Don't put anything in the sidebar "Block" tab that is necessary for the basic operation of your block. Your user might dismiss the sidebar for an immersive writing experience. So pick good defaults, and make important actions available in the quick toolbar.

The only purpose of the Cover Text block is to add color and text sizing, and this is done in the sidebar, so it breaks with that design philosophy, making it less useful if a user decides to dismiss the sidebar.

On the other hand if it was part of the paragraph block, it would be exactly that — welcome, but advanced, additions to the basic text block.

As far as I'm concerned, the only blocker for merging the two, is ensuring that there's a "Reset" button next to colors and font sizes, so you can get back to an unstyled paragraph easily.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #2448

**Notes**

 - The paragraph block has Block Alignment Toolbar too but I kept only "wide" and "full" alignments. For me, the "center" block alignment is useless for a paragraph block.
 - I added a "reset" link to font-size range
 - There's no wrapper element (like the cover-text) only a `p`
 - Parsing a `core/cover-text` will result in an invalid `core/paragraph` block. I don't know if we should do more about this, we're still beta right.
 - The editable has a new prop `wrapperClassname` replacing the old `className` prop. It's seemed more logic to me to apply the `className` prop directly to the TinyMCE node.
 - Cover Text is MultiParagraph, Paragraph is not.

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice!

This works amazingly well. I think we should do it.

However I don't think we should include the alignments in this toolbar, I think we should either sacrifice those, or move them to the block inspector. The paragraph block should first and foremost be just that, text, and so this implicitly categorizes the layout alignments as "advanced settings".

Curious what @mtias thinks, but I'm okay with both removing the layout alignments, or moving them to the inspector (like we did with headline).

**Comment by iseulde** [comment]
I like merging these. I've been confused by cover text, for a while, as it was just a paragraph with a centre button. U just discovered now that it has more block settings buried in the inspector.

**Comment by jasmussen** [comment]
Let's move the _layout alignments_ to the sidebar for now, and then get this merged. They are absolutely an advanced aspect of the "text" block, and so the sidebar is the appropriate place for it.

It'll also give some welcome synergy with the heading block:

screen shot 2017-08-22 at 11 48 57

Once moved there, let's merge this and fix any issues that pop up separately.

**Comment by youknowriad** [comment]
@jasmussen do you think I should enable the float left/right alignments too (in the inspector) or keep only wide/full?

**Comment by jasmussen** [comment]
> do you think I should enable the float left/right alignments too (in the inspector) or keep only wide/full?

Unless it looks terrible with the left/right/center, then no reason not to. The reasons you might want to keep them out, is that they require a size that's not "editor width" in order to be meaningful, and we don't have any way of resizing the text block quite yet. I'd also be very careful in exploring too much resizing action yet, as this steps firmly into customization territory and might be best served with a more holistic approach, CC: @melchoyce

**Pull request merged**
