### PR TITLE
Summarize "Available commands" section and refer them it to `scripts` docs

### PR DESCRIPTION
**Pull request by juanmaguitar**
## What?
This PR moves to a subpage the content of the "Available Commands" as this info is not strictly about the `create-block` package (but about the resulting plugin folder created when executing it)_
This PR is part of the solutions required to solve https://github.com/WordPress/gutenberg/issues/45519

## Why?
Because this package is the main tool to create blocks and the learning experience of this package could be improved by separating concepts 

## How?
By moving this section to a subpage at the same level than [External Project Templates](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/packages-create-block-external-template/)

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
👍

**Comment by ramonjd** [comment]
We might need to run `npm run docs:build` on this branch, which I think will update `docs/manifest.json`

**Comment by vcanales** [comment]
Could this be a link to https://github.com/WordPress/gutenberg/tree/HEAD/packages/scripts#available-scripts instead? I'm thinking that if that source is updated, we might end up with out-of-sync docs.

**Review by vcanales — APPROVED** [review]
LGTM! 👍

**Review by bangank36 — COMMENTED** [review]
Noice

**Pull request merged**
