### PR TITLE
Add `i18n` rules from `eslint-plugin-wordpress`

### PR DESCRIPTION
**Pull request by ntwb**
## Description

Adds ESLint `i18n` rules from `eslint-plugin-wordpress`

This PR stems from a Slack conversation between @danielbachhuber and @aduth [here](https://wordpress.slack.com/archives/C02QB2JS7/p1525972170000329)

The `eslint-plugin-wordpress` ESlint config includes the `i18n` [rules from](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/blob/master/lib/configs/rules/i18n.js) `eslint-plugin-wpcalypso` 

In particular, the rule cited in the chat was the `wpcalypso/i18n-ellipsis` rule which is [configured currently](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/blob/master/lib/configs/rules/i18n.js#L16-L17) to `warn`, this can be easily changed to `error`

Any of the other rules included in `plugin:wordpress/i18n` may require tweaks, this `plugin:wordpress/i18n` has had very little real-world WordPress testing.

## How has this been tested?

I've not tested this locally, let's see what Travis CI has to say about it.

## Types of changes

Build Tool Update

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Review by tofumatt — COMMENTED** [review]
It might be handy to test a branch with the failing code locally (or push it to Travis) to make sure it fails.

Probably worth removing the custom rule added in #6692 if it exists elsewhere and we're importing it.

Nice to re-use existing stuff though! 👍🏻

**Comment by gziolo** [comment]
> Missing external, internal dependencies docblocks  wpcalypso/import-docblock
> className should follow CSS namespace guidelines (expected autocomplete)           wpcalypso/jsx-classname-namespace
> combineReducers should be imported from state/utils not redux  wpcalypso/import-no-redux-combine-reducers

All of them should be disabled completely for Gutenberg for the time being or updated to work differently. It should be as follows:
* Missing external, **WordPress,** internal dependencies docblocks - we use also WordPress section
* className should follow CSS namespace guidelines (expected **components-**autocomplete) - we prefix all class names with the module name (top-level folder)
* combineReducers should be imported from state/utils not redux - it is exposed from `@wordpress/date` in our case

**Comment by gziolo** [comment]
> There were no warnings from the `wpcalypso/i18n-ellipsis` rule though /shrug 

I think this is because Calypso uses a different function name as a wrapper for translations: `translate` and as far as I remember those rules depend on it.

**Comment by ntwb** [comment]
Thanks everyone, closing this PR for now, I quickly created this morning to check out any explosions, there was nowhere near what I expected.

I'll create an issue on https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress later for reference.

**Pull request closed without merging**
