### PR TITLE
Cover block: Update the box-sizing attribute

### PR DESCRIPTION
**Pull request by scruffian**
## Description
I think we should add `box-sizing: border-box;` to the cover block. In themes with a fixed post width, the combination of a cover block with 100% width and 16px padding means that the cover block extends outside the bounds of the post content:

Screenshot 2020-09-07 at 13 34 51

Adding `box-sizing: border-box;` tells that block to count the padding as part of the 100% width, and prevents it bleeding out:

Screenshot 2020-09-07 at 13 36 12

In the other themes I tested this doesn't change anything.

## How has this been tested?
Tested with TwentyTwenty and Seedlet thems

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
I'm a `box-sizing: border-box;` fan. To the point that I think it should be the default behavior on the web.

However given that this block has shipped for a while without it, and is relatively well used, what kind of testing can we do to ensure this doesn't regress? And, perhaps a larger question, if the motivation for adding this is the padding behavior which was recently added to Cover, but is on its way to Group, should we add this property to more blocks? Which ones?

**Comment by scruffian** [comment]
I tested this on Twenty Twenty, Twenty Nineteen, Seedlet and Twenty Ten. These lines of CSS didn't make any difference to any of the newer themes, but on Twenty Ten, these lines fixed the display of the block which otherwise was bleeding into the sidebar.

**Review by jasmussen — APPROVED** [review]
Yep, pairing the box model with the padding feature makes for a good predictable heuristic. This needs a good testing in a few themes, but it should work great. Thanks!

**Review by aristath — APPROVED** [review]
LGTM :+1: 
Tested with a few themes, didn't see any issues

**Comment by scruffian** [comment]
Any idea why the tests are failing?

**Comment by jasmussen** [comment]
That specific test keeps failing occasionally. I restarted it.

**Pull request merged**
