### PR TITLE
test: Reduce default Jest log verbosity

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/wordpress-mobile/gutenberg-mobile/pull/6012

## What?

Disable the Jest `verbose` option for native tests.

## Why?

The current approach of enabling the `verbose` option for all test
scripts diverges from the Jest default and the Gutenberg web editor
preset. This better aligns the native tests with the web tests.

The non-verbose output is helpful for comprehending results when 
running many tests at once. 

The `verbose` option remains enabled for "debug" scripts and can
be enabled ad-hoc via the `--verbose` flag. Additionally, the 
verbose output remains the default output when running a single
test file. 

## How?

Remove the `--versbose` flag and `verbose: false` option for all native test
scripts aside from the debug variants, which would benefit from additional
information while debugging.

## Testing Instructions

n/a

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 
| Before | After |
| - | - |
| before | after |

### CODE REVIEW

**Comment by derekblank** [comment]
I would be in favor of this change. 👍

**Comment by fluiddot** [comment]
> Remove the `--versbose` flag and `verbose: false` option for all native test
> scripts aside from the debug variants, which would benefit from additional
> information while debugging.

I noticed we enable the verbose mode in other cases not covered in this PR. I'm wondering if we could also disable it on them. WDYT?

- Mobile e2e tests in Gutenberg: https://github.com/WordPress/gutenberg/blob/1052456a23a5625bf6566118d4a26df37a8b1c2c/packages/react-native-editor/package.json#L107-L109
- [e2e tests in Gutenberg Mobile](https://github.com/wordpress-mobile/gutenberg-mobile/blob/effcd08f6ffeba9c56937315cedbab55d49ce68e/package.json#L83-L88)
- [Jest configuration in Gutenberg Mobile](https://github.com/wordpress-mobile/gutenberg-mobile/blob/effcd08f6ffeba9c56937315cedbab55d49ce68e/jest.config.js#L23)

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Comment by dcalhoun** [comment]
> I noticed we enable the verbose mode in other cases not covered in this PR. I'm wondering if we could also disable it on them. WDYT?

Good point. I addressed this in 129929c6d50c5b3a930f0a4e51028fc44cea3dcc and https://github.com/wordpress-mobile/gutenberg-mobile/pull/6012.

**Review by fluiddot — APPROVED** [review]
> Good point. I addressed this in [129929c](https://github.com/WordPress/gutenberg/commit/129929c6d50c5b3a930f0a4e51028fc44cea3dcc) and [wordpress-mobile/gutenberg-mobile#6012](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6012).

Great, thanks! :shipit:

**Pull request merged**
