### PR TITLE
Polish responsive navigation modal, inherit justifications, fix submenu direction

### LINKED ISSUE #35040: Navigation: Justify items right in vertical navigation
### Description

When in vertical mode, the justify right option in the navigation block doesn't behave as expected.

### Step-by-step reproduction instructions

Create a vertical navigation block, and then try to align the items right. It looks like this:
Screenshot 2021-09-22 at 13 24 37

### Screenshots, screen recording, code snippet

It should look like this:
Screenshot 2021-09-22 at 13 28 06

In addition, the submenus should open to the left:
Screenshot 2021-09-22 at 14 42 08

cc @jasmussen 

### Environment info

_No response_

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by jasmussen**
## Description

Fixes #35040. Fixes and issue where justifications were not inherited in the responsive modal, an issue with hover-opening flickering, and an issue with submenus not opening in the right direction.

This is a big of a big one so could use a great deal of testing in a variety of themes, with a variety of content. Things to look for:

- Submenus at small and wide breakpoints
- Submenu directions they open in based on justification
- Modal as it inherits properties, including justifications

All of that, worth testing with and without responsive navigation toggled on, and with and without a Page List block inside.

## How has this been tested?

You can use this testing content:

```
<!-- wp:paragraph -->
<p>Horizontal, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Subpage","type":"page","id":29873,"url":"http://local-wordpress.local/contact/subpage/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sub subpage","type":"page","id":29875,"url":"http://local-wordpress.local/contact/subpage/sub-subpage/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Subpage","type":"page","id":29873,"url":"http://local-wordpress.local/contact/subpage/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sub subpage","type":"page","id":29875,"url":"http://local-wordpress.local/contact/subpage/sub-subpage/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p><strong>Not responsive</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right"} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right"} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right"} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right"} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->
```

## Screenshots <!-- if applicable -->

Before, editor:
<img width="956" alt="before editor" src="https://user-images.githubusercontent.com/1204802/134483639-7e401fd7-1b2d-4ba1-9656-d280678b632d.png">

Before, frontend:

<img width="937" alt="before frontend" src="https://user-images.githubusercontent.com/1204802/134483658-1cd9149f-28a8-4e0e-8f8d-b5540743aea1.png">

Before, inside the modal, even though justification was set to right:

<img width="449" alt="before modal" src="https://user-images.githubusercontent.com/1204802/134483695-90f91ce1-f6a3-48e6-9a40-8744c0b24c91.png">

After, frontend:

<img width="890" alt="after frontend" src="https://user-images.githubusercontent.com/1204802/134483757-7a51ad43-9d78-4631-b30b-17018557eb71.png">

After, submenus when justified right:

<img width="752" alt="after submenus" src="https://user-images.githubusercontent.com/1204802/134483785-77a140f0-e903-4b26-97ae-a40b2b047565.png">

After, modal:

<img width="577" alt="after modal" src="https://user-images.githubusercontent.com/1204802/134483806-a69e85ac-e0c6-4123-9c92-4d750cbbb418.png">

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. <!-- Check code: `npm run lint`, Guidelines: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/ -->
- [x] My code follows the accessibility standards. <!-- Guidelines: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/accessibility/ -->
- [x] I've tested my changes with keyboard and screen readers. <!-- Instructions: https://github.com/WordPress/gutenberg/blob/HEAD/docs/contributors/accessibility-testing.md -->
- [x] My code has proper inline documentation. <!-- Guidelines: https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/ -->
- [x] I've included developer documentation if appropriate. <!-- Handbook: https://developer.wordpress.org/block-editor/ -->
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). <!-- React Native mobile Gutenberg guidelines: https://github.com/WordPress/gutenberg/blob/HEAD/docs/contributors/code/native-mobile.md -->

### CODE REVIEW

**Comment by vcanales** [comment]
I'm noticing that spacing looks a bit funky with Page List, and subpages, both in TT1 and T19; here's TT1.

|Editor|Frontend|
|--|--|
|Kapture 2021-09-23 at 13 02 01|Kapture 2021-09-23 at 13 05 49|

**Comment by gwwar** [comment]
Nice this fixes justification for the vertical variant! One thing I noticed was that space between was not respected when the menu is set to responsive:

CleanShot 2021-09-23 at 12 58 48

**Comment by jasmussen** [comment]
Thanks a ton for testing, both of you.

Vicente, it appears the spacing issue with the navigation is due to obsolete margin rules applied by TT1, tracked here: https://core.trac.wordpress.org/ticket/53220

You can see here that the gap is the same:
Screenshot 2021-09-24 at 11 14 58

Screenshot 2021-09-24 at 11 15 11

But the main items have a padding applied by the theme, which interferes with it:
Screenshot 2021-09-24 at 11 14 44

The white border around the responsive modal dialog is also from TT1 styling the wrong background color, it appears:
Screenshot 2021-09-24 at 11 18 03
Screenshot 2021-09-24 at 11 18 11

Screenshot 2021-09-24 at 11 18 11

This is also reflected if you choose a different background color:

Screenshot 2021-09-24 at 11 19 49

The white background behind the active menu item is because TT1 also sets the bg color on focus, and in a modal dialog, the first item gets focus as soon as it's opened.

There seems to be a legitimate issue with the spacing of items in the "unfolded" style:

Screenshot 2021-09-24 at 11 24 25

I'll see what I can do here.

About the TT1 issues: it was built to represent the best WordPress had to offer coinciding with a release. Which meant it did the very best it could with the markup and featureset the navigation block had at the time, which has changed a great deal. I will see if I can set aside some time to submit a patch and fix it at the source. But in the mean time, it's possibly best to test with another theme, possibly "Empty Theme" from [this repo](https://github.com/WordPress/theme-experiments).

**Comment by jasmussen** [comment]
Thank you Kerry, great catch. Space between should work in Page List again:
<img width="831" alt="Screenshot 2021-09-24 at 11 40 32" src="https://user-images.githubusercontent.com/1204802/134654004-87196432-3d12-4fce-a54d-cbb110aec991.png">

Here's updated test content in case you need it:

```
<!-- wp:paragraph -->
<p>Horizontal, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Subpage","type":"page","id":29873,"url":"http://local-wordpress.local/contact/subpage/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sub subpage","type":"page","id":29875,"url":"http://local-wordpress.local/contact/subpage/sub-subpage/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Subpage","type":"page","id":29873,"url":"http://local-wordpress.local/contact/subpage/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sub subpage","type":"page","id":29875,"url":"http://local-wordpress.local/contact/subpage/sub-subpage/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p><strong>Not responsive</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"backgroundColor":"purple","itemsJustification":"right"} -->
<!-- wp:page-list {"backgroundColor":"purple","isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, page list:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right"} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Horizontal, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right"} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Vertical, justified right, manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"orientation":"vertical","itemsJustification":"right"} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p><strong>Space Between when responsive</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"space-between","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Page List:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"space-between","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p><strong>Space Between when not responsive</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Manual items:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"space-between"} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:paragraph -->
<p>Page List:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"space-between"} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->
<!-- /wp:navigation -->
```

**Comment by jasmussen** [comment]
Alright, I believe I fixed the issue with bad spacing for menu items. Before:
<img width="302" alt="Screenshot 2021-09-24 at 11 42 28" src="https://user-images.githubusercontent.com/1204802/134658101-138eb0bb-a479-4951-ac89-73aa4834bbf6.png">

After:

![modal](https://user-images.githubusercontent.com/1204802/134658112-60d7ceec-2bbf-48af-b79c-8708b2402dea.gif)

The issue was related to the refactor to use gap, where submenus still partially used margins. The new version uses a combination to space things out correctly.


Here's some test content just for testing all the justifications inside the modal:

```
<!-- wp:paragraph -->
<p>Left:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} /-->
<!-- /wp:navigation-submenu -->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Center:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"center","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} /-->
<!-- /wp:navigation-submenu -->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Right:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} /-->
<!-- /wp:navigation-submenu -->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:paragraph -->
<p>Space between:</p>
<!-- /wp:paragraph -->

<!-- wp:navigation {"itemsJustification":"space-between","isResponsive":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Home","type":"page","id":28543,"url":"http://local-wordpress.local/home/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} /-->
<!-- /wp:navigation-submenu -->

<!-- wp:navigation-link {"label":"Journal","type":"page","id":28540,"url":"http://local-wordpress.local/journal/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-submenu {"label":"Contact","type":"page","id":827,"url":"http://local-wordpress.local/contact/","kind":"post-type","isTopLevelItem":true} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-submenu {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelItem":false} -->
<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->

<!-- wp:navigation-link {"label":"Sample Page","type":"page","id":2,"url":"http://local-wordpress.local/sample-page/","kind":"post-type","isTopLevelLink":false} /-->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation-submenu -->
<!-- /wp:navigation -->
```

**Comment by scruffian** [comment]
Thanks for working on this. I see that now the menu opens to the left if the items are justified right, but the arrows still point to the right:
Screenshot 2021-09-24 at 19 24 42

**Comment by scruffian** [comment]
Also, when using post list and other items in a horizontal menu, it still displays vertically:

Screenshot 2021-09-24 at 19 32 05

The markup for this one is:

```
<!-- wp:navigation {"itemsJustification":"right","isResponsive":true} -->
<!-- wp:page-list {"isNavigationChild":true,"showSubmenuIcon":true,"openSubmenusOnClick":false} /-->

<!-- wp:navigation-link {"label":"Post","type":"post","id":170,"url":"http://localhost:4759/?p=170","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->
```

**Comment by jasmussen** [comment]
Thanks for testing. I'll address the post list. 

Mind if I ticket or look at the arrow changing direction separately? The current behavior is _semi intentional_ in that it mirrors what MacOS does:

Screenshot 2021-09-24 at 20 27 45

— though I agree it's less obvious here, so worth looking at.

**Comment by scruffian** [comment]
> Mind if I ticket or look at the arrow changing direction separately? 

Yeah that makes perfect sense :)

**Comment by gwwar** [comment]
@jasmussen do you mind rebasing with trunk, we're running into the `cb()` issue with some of the test suites, hopefully that should give us a green run.

**Comment by jasmussen** [comment]
Done, thank you for looking!

**Review by gwwar — APPROVED** [review]
Nice work @jasmussen! Giving tentative approval, but feel free to land when we have tests green.

I verified that alignment and space between still work. I did notice some jumping in edit mode when selecting a block with justify right or space between, but I think that's more minor and can be addressed in a different PR.

**Comment by jasmussen** [comment]
Thank you! I'll let this one sit until tomorrow and look at merging it then so I can follow up. In the mean time I would welcome any tests and additional reviews.

**Comment by talldan** [comment]
@jasmussen @gwwar It seems like there was a lot going on here, but absolutely no testing of the navigation editor, and this PR has caused issues with the appearance of items in the navigation editor.

There are quite a number of problems now when we factor in the problems also introduced by https://github.com/WordPress/gutenberg/pull/35026.

In addition to the problem that PR introduced, this one seems to have caused issues with the hover and selected block styles:
Screenshot 2021-09-30 at 12 12 37 pm

The border is cut-off, and there's a lot of general glitching when hovering over items (the whole nav block unexpectedly resizing, different borders showing up).

I understand that the way the editor's styles work right now isn't ideal, but I don't think this is a valid excuse to bypass testing and fixing issues as you encounter them prior to merging. Both the editor and the block are a shared responsibility for those working on this project, and it'd be great to see more sharing of responsibility in the future when contributing.

**Comment by jasmussen** [comment]
Apologies. I included a fix for the hover style in #35234. 

Can you clarify what you are seeing with regards to the nav block resizing, different borders showing up? I'm seeing the following which seems right to me:
glitching

**Comment by talldan** [comment]
Left a video and comment on #35234.

**Comment by gwwar** [comment]
> but absolutely no testing of the navigation editor

Sorry @talldan  I usually remember, but I forgot for this round of testing!

**Pull request merged**
