### PR TITLE
Performance Tests: Improve collection and reporting

### LINKED ISSUE #61411: Add Summaries to Performance Workflow Runs
## What problem does this address?

While reviewing the potential performance impacts of a PR, it is nice to be able to review the results of the automated Performance Tests that are run. You can currently find these results in the logs for the performance run, but finding them are not that intuitive and easy to look over.

## What is your proposed solution?

In the [WP-dev repo](https://github.com/WordPress/wordpress-develop) we display the results of the performance runs to the summary page for that run, which is a bit more convenient.

As an example, here are PRs for basically the same change in both the GB repo and the WP-dev repo:

- [GB PR Performance Test](https://github.com/WordPress/gutenberg/actions/runs/8901584527)
- [WP PR Performance Test](https://github.com/WordPress/wordpress-develop/actions/runs/8907437250)

### PR DESCRIPTION
**Pull request by swissspidy**
## What?

* Collect `Server-Timing` information in performance tests
* Print test results as GitHub Actions summaries for easier overview

See #33645
Fixes #61411

To-do:

* Ideally we'd prepare & reset the environment like core does (disable cron, disable external HTTP requests, flush object cache). But I don't know where to start 🤔  The setup is quite different from core's.

### CODE REVIEW

**Comment by Mamaduka** [comment]
What's the reason for grouping these two in a single PR?

**Comment by swissspidy** [comment]
@Mamaduka I'm trying to port over some of the recent improvements from the WP core tests, having everything in one PR is more manageable for testing.

**Review by joemcgill — COMMENTED** [review]
Nice! [The summary on this PR]((https://github.com/WordPress/gutenberg/actions/runs/8989145786)) already looks pretty good. A couple non-blocking observations:

- It would be nice to map the spec names for each table to a more human readable format that were more descriptive ([example](https://github.com/WordPress/wordpress-develop/actions/runs/8972509093)).
- I would flip columns for `trunk` and the current commit so they are consistent with the before/after format used in other places where we are reporting comparisons.
- Using the full commit hash for the header gets pretty long, possibly truncate to 7 characters, which is [the default length for most short style SHA-1 hashes](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) or go with the generic "before" and "after" like we do elsewhere.

**Comment by swissspidy** [comment]
> * It would be nice to map the spec names for each table to a more human readable format that were more descriptive ([example](https://github.com/WordPress/wordpress-develop/actions/runs/8972509093)).

I think this would require more significant changes . The way the performance reporter is setup, the actual test suite names are not really readable nor unique, nor are the names saved to the result files.

> * I would flip columns for `trunk` and the current commit so they are consistent with the before/after format used in other places where we are reporting comparisons.

This is actually in line with how the data is saved under the hood and presented on the command line when running tests.

See https://github.com/WordPress/gutenberg/actions/runs/8989145786/job/24691572268?pr=61450#step:5:104 for example.

> * Using the full commit hash for the header gets pretty long, possibly truncate to 7 characters, which is [the default length for most short style SHA-1 hashes](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) or go with the generic "before" and "after" like we do elsewhere.

I was thinking about this but this is not guaranteed to be a commit hash. It can also be a branch name or a tag name.

Again, the output is the same on command line as well.

**Comment by youknowriad** [comment]
TIL about the job summaries, really nice and avoid digging into the logs. The discoverability is increased a lot without adding huge distracting comments to the PR.

Now I wonder if there's a way to make this a little bit more visible in the main PR page or something (a link or something).

**Comment by youknowriad** [comment]
@WordPress/gutenberg-core We should look at adding this summary to the Gutenberg job as well.

**Comment by tyxla** [comment]
also cc @jsnajdr who has been looking at reducing performance test noise and we were also discussing surfacing the results to devs in PRs.

**Review by youknowriad — APPROVED** [review]
This is a great improvement. Thanks

**Comment by Mamaduka** [comment]
> Ideally we'd prepare & reset the environment like core does (disable cron, disable external HTTP requests, flush object cache). But I don't know where to start 🤔 The setup is quite different from core's.

Can you share where the core setup handles this?

**Comment by swissspidy** [comment]
> > Ideally we'd prepare & reset the environment like core does (disable cron, disable external HTTP requests, flush object cache). But I don't know where to start 🤔 The setup is quite different from core's.
> 
> Can you share where the core setup handles this?

In test-performance.yml

**Review by desrosj — APPROVED** [review]
Thanks for this, @swissspidy!

For anyone with more ideas about how to use job summaries, [Trac-56150](https://core.trac.wordpress.org/ticket/56150) is an overarching ticket for proposing new ways to utilize this feature in our workflows managed in WordPress/wordpress-develop.

**Pull request merged**
