### PR TITLE
Add missing labels to changelog script, and enhance mapping function.

### PR DESCRIPTION
**Pull request by vcanales**
Changes: 
- Compare labels using lowercase values.
    
    Avoids missing mappings due to capitalization mismatch. eg. at the time
    of this change, the code looked for [Package] Block Editor, but on
    GitHub the label is actually typed [Package] Block editor — PRs labeled
    as such, were being sorted under Various.

- Add site editor label.
- Add commands package label.

### CODE REVIEW

**Comment by alexstine** [comment]
@vcanales Code looks good. Testing instructions?

**Comment by vcanales** [comment]
> @vcanales Code looks good. Testing instructions?

Thanks for taking a look. Running `npm run other:changelog -- --milestone="Gutenberg 16.8"` should output a changelog with only one (1) item under "Various", about a Reverted change. You could then compare that changelog with one created running the same command on `trunk`, which would incorrectly include a couple of correctly labeled PRs under "Various".

**Review by priethor — CHANGES_REQUESTED** [review]
Thanks, @vcanales!

Can you update the tests to check these cases? 🙂  E.g., changing the test fixtures to:
- Include a PR that includes the Command label
- Messing with the casing of some label

**Comment by vcanales** [comment]
@priethor I've added a few more test cases and updated snapshots and fixtures; for the latter, I used the output for `npm run other:changelog -- --milestone="Gutenberg 16.8"` to generate pull the PRs JSON data.

**Comment by vcanales** [comment]
Pinging @priethor; friendly reminder!

**Review by priethor — APPROVED** [review]
LGTM! Thanks, Vicente! 🚀

**Comment by vcanales** [comment]
Backported to Gutenberg 17.2 RC

**Pull request merged**
