### PR TITLE
Update CHANGELOG.md to correct order of items

### PR DESCRIPTION
**Pull request by guarani**
This is a non-code PR that puts the versions in CHANGELOG.md back into chronological order.

### CODE REVIEW

**Review by geriux — APPROVED** [review]
LGTM!

**Comment by gziolo** [comment]
The release script for npm packages is messing up with this CHANGELOG. I'm wondering if removing `## Unreleased` would be enough to ignore it in processing.

**Comment by guarani** [comment]
> The release script for npm packages is messing up with this CHANGELOG. I'm wondering if removing `## Unreleased` would be enough to ignore it in processing.
> 
> According to unit test it should work:
> 
> https://github.com/WordPress/gutenberg/blob/master/bin/plugin/commands/test/common.js
> 
> So you can remove the first several lines and it won't mess up anymore 😃

Thanks for the comment, @gziolo! I'm not sure if I understand, do you propose removing `## Unrelated` from the change log? I had a look at https://github.com/WordPress/gutenberg/tree/master/packages#maintaining-changelogs and it seems like the `## Unreleated` section is still used, so not sure if I misunderstood.

In the meantime I'm going ahead with the merge since this is part of the mobile editor release due today, and from what I understand this won't break anything.

**Comment by gziolo** [comment]
See https://github.com/WordPress/gutenberg/pull/28060 where I propose further changes that might save you hassles in the future :)

Would you like to prevent version bumps in the `package.json` as well?

**Comment by guarani** [comment]
Thanks for the PR! I'll have to ask @geriux if he could respond here, I'll be AFK and haven't looked into this yet.

**Comment by mchowning** [comment]
> Would you like to prevent version bumps in the package.json as well?

I think that's right. I can't think of any reason we would want the package.json on the react-native-* packages to be bumped when there is a web release.

**Comment by gziolo** [comment]
Good, I will find out how we can further exclude RN packages from Lerna publishing process. Those packages are already marked as private but it seems like not enough.

**Comment by mchowning** [comment]
Thanks so much @gziolo ! My understanding is that it's a bug in lerna that the private packages are being impacted by the release process: https://wordpress.slack.com/archives/C02QB2JS7/p1597086591452000?thread_ts=1597085852.449300&cid=C02QB2JS7.

**Comment by gziolo** [comment]
https://www.npmjs.com/package/@lerna/version?activeTab=readme#--no-private

I found something promising - flag that skips private packages when bumping versions. The challenge is that we use `lerna publish` that uses `lerna version` internally. I'm sure we can find a way to make it work if that flag is working as I assumed 😃

**Pull request merged**
