### PR TITLE
[RNMobile] Enable reusable block (preview mode)

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg-mobile` PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3440

## Description

This PR enables the Reusable block to be available for users.

## How has this been tested?

This feature has been tested on previous PRs but we should do a final review, here are the testing instructions of the main related PRs that are already merged:

<details><summary><strong>Present block content (preview mode)</strong></summary>

**PR: https://github.com/WordPress/gutenberg/pull/25265**

This was tested in the following 3 different scenarios:

<details>
<summary><strong>WordPress.com site</strong></summary>

Create a WordPress.com site or use an already created one.
- Create a post in the web version
- Add some blocks and create a Reusable block
- Open the app with metro running (Gutenberg-mobile)
- Add the WordPress.com site
- Edit the previous created post
- Check that the Reusable block is shown
- Tap on it and check that the title of the Reusable blocks is shown

</details>

<details>
<summary><strong>Self-hosted site with Jetpack</strong></summary>

Create a self-hosted site with Jetpack (I used https://jurassic.ninja/create/) or use an already created one.
- Create a post in the web version
- Add some blocks and create a Reusable block
- Open the app with metro running (Gutenberg-mobile)
- Add the self-hosted site
- Edit the previous created post
- Check that the Reusable block is shown
- Tap on it and check that the title of the Reusable blocks is shown

</details>

<details>
<summary><strong>Self-hosted site without Jetpack</strong></summary>

Create a self-hosted site without Jetpack (I created a local one using [this instructions](https://developer.wordpress.org/block-editor/contributors/develop/getting-started/#local-environment)) or use your own.
- Create a post in the web version
- Add some blocks and create a Reusable block
- Open the app with metro running (Gutenberg-mobile)
- Add the self-hosted site
- Edit the previous created post
- Check that the Reusable block is shown
- Tap on it and check that the title of the Reusable blocks is shown

</details>

</details>

<details><summary><strong>Additional improvements for rendering Reusable block</strong></summary>

**PR: https://github.com/WordPress/gutenberg/pull/30966**

**NOTE: Reusable blocks can be managed by navigating to the "Reusable blocks page":**
- WP.com: `https://wordpress.com/types/wp_block/<YOUR_WPCOM_SITE_DOMAIN>`
- Self-hosted: `https://<YOUR_SELF_HOSTED_SITE_DOMAIN>/wp-admin/edit.php?post_type=wp_block`

Here are the steps for creating reusable blocks in the web version:

**Option 1:**
1. Edit a post/page
2. Add some blocks
3. Select multiple blocks
4. Click on options (three dots button)
5. Click on "Add to Reusable blocks" button
6. Input a name for the block
7. Save the post/page

**Option 2:**
1. Navigate to "Reusable blocks page" (referenced above)
2. Click on "Add new reusable block"/"Add new" button
3. Add a title
4. Add some blocks
5. Publish it

### Preview content
1. Create a reusable block and add it to a post/page
2. Edit the post/page in the mobile app
3. Observe that the reusable block is shown
4. Tap on it and observe that the title of the reusable blocks is shown

### Deleted reusable block
1. Create two reusable blocks
2. Add the second reusable block as part of the content of the first one and save it
3. Delete the second reusable block from the "Reusable blocks page" (referenced above)
4. The second reusable block will go to the trashed tab, delete it permanently
5. Add the first reusable block to a post/page
6. Edit the post/page in the mobile app
7. Observe that the reusable block is shown and that no errors are displayed
8. Observe that the second reusable block is not rendered but displays a warning

### Recursive block rendering
1. Create a reusable block
2. Edit the reusable block, add the same reusable block as part of the content and save it
3. Add the reusable block to a post/page
4. Edit the post/page in the mobile app
5. Observe that the reusable block is shown and that no errors are displayed
6. Observe that it displays a warning instead of rendering multiple times the same block

</details>

<details><summary><strong>Add convert to regular blocks action to Reusable block</strong></summary>

**PR: https://github.com/WordPress/gutenberg/pull/31012**

1. Create a reusable block in the web version
2. Add the reusable block to a post/page
3. Edit the post/page in the mobile app
4. Tap on the reusable block
5. Tap on the three dots button to display the block actions menu
6. Tap on "Convert to regular blocks"
7. Observe that the reusable block is converted to regular blocks

### Undo/redo

It's important that we verify that the undo/redo actions work as expected when converting to regular blocks.

1. [Follow the same steps described above for converting to regular blocks]
2. Tap the undo button from the toolbar
3. Observe that the reusable block is displayed again
4. Tap the redo button from the toolbar
5. Observe that the regular blocks are displayed again

</details>

## Screenshots 

iOS|Android
--|--
<video src=https://user-images.githubusercontent.com/14905380/116737440-847e1500-a9f1-11eb-809c-443e532fe4c8.mp4>|<video src=https://user-images.githubusercontent.com/14905380/116738062-42090800-a9f2-11eb-8870-b641c594af4c.mp4>

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
Hi @fluiddot Thanks all the work you have done on the Reusable blocks project. I performed a comprehensive behavior verification session guided by the testing instructions included in the PR and I was successfully able to confirm that the behavior implemented in all the child PRs that are linked work as expected 🚢 . To provide further clarity, below is a breakdown of all the tests I performed and the results of the said tests. 

## Devices
- iPhone 11, iOS 14.4
- Google Pixel 4 XL, Android 11 / API 30

## WP Main App Versions

- WordPress iOS - [develop](https://github.com/wordpress-mobile/WordPress-iOS/commit/42e0e43b6b944eb8150eda8530b439337968ce7e)

- WordPress Android - [develop](https://github.com/wordpress-mobile/WordPress-Android/commit/ff4b4acd71d2bb7010bf2e18111a3253fb187d48)

## Testing

### 1. Present block content (preview mode) - iPhone 11, iOS 14.4
- WordPress.com site ✅
- Self-hosted site with Jetpack ✅
- Self-hosted site without Jetpack ✅

### 2. Additional improvements for rendering Reusable block

#### i. Preview content
- WordPress.com site ✅
- Self-hosted site ✅

#### ii. Deleted reusable block
- WordPress.com site ✅
- Self-hosted site ✅

#### iii. Recursive block rendering
- WordPress.com site ✅
- Self-hosted site ✅

⚠️ *Note*: Even though the tests carried out here were successful I noticed a minor, difference in messaging. On self host sites the warning is "Block has been deleted or is unavailable" and on WordPress.com sites the warning is "Block cannot be rendered inside itself." 

WordPress.com site | Self hosted site 
--------|-------
<kbd></kbd>    |       <kbd></kbd>




### 3. Add convert to regular blocks action to Reusable block

#### i. Convert to reusable blocks to regular blocks
- WordPress.com site ✅
- Self-hosted site ✅

#### ii. Undo/redo of reusable blocks conversion to regular blocks
- WordPress.com site ✅
- Self-hosted site ✅

**Comment by fluiddot** [comment]
Thank you very much @jd-alexander for the extensive review you've done in this PR, I really appreciate it ❤️ !

>⚠️ Note: Even though the tests carried out here were successful I noticed a minor, difference in messaging. On self host sites the warning is "Block has been deleted or is unavailable" and on WordPress.com sites the warning is "Block cannot be rendered inside itself."

Good catch! I've been testing this and looks like on self-hosted the recursive block rendering has some issues. I'll investigate this further and open an issue 👍 .

**Comment by fluiddot** [comment]
I've opened [the issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3457) regarding the problem with recursive block rendering on self-hosted sites. I'm afraid it's worse than I expected because on some cases it could even lead to a crash so I'm going to pause the merge of this PR until I find a solution.

**Comment by jd-alexander** [comment]
> Thank you very much @jd-alexander for the extensive review you've done in this PR, I really appreciate it ❤️ !

Was more than happy to @fluiddot 😄 

> Good catch! I've been testing this and looks like on self-hosted the recursive block rendering has some issues. I'll investigate this further and open an issue 👍 .

> I've opened the issue regarding the problem with recursive block rendering on self-hosted sites. I'm afraid it's worse than I expected because on some cases it could even lead to a crash so I'm going to pause the merge of this PR until I find a solution.

I agree with pausing since some cases lead to a crash. Let me know if you need any help with testing etc, as well. 🙏🏾

**Comment by fluiddot** [comment]
@jd-alexander  I opened this [PR](https://github.com/WordPress/gutenberg/pull/31744) that contains these changes and besides limits the availability of the reusable block to only WP.com sites. The idea is to release this block to the sites we know it works and in the future fix [the issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3457) and enable it to self-hosted sites too.

I'd appreciate it if you could take a look at it and once it's ready I'll close this in favor of that one, thanks 🙇 !

**Comment by fluiddot** [comment]
The reusable block has been enabled in this [PR](https://github.com/WordPress/gutenberg/pull/31744) so we can safely close this one 🎊 .

**Pull request closed without merging**
