### PR TITLE
Add stretch alignment to Column block.

### LINKED ISSUE #52825: Alignment do not work & Spacer gets ignored
### Description

My goal is to create a design where I have on the left top the title and on the left bottom additional info. On the right images.
The height is automatically defined by the images.

I am adding a spacer between the top and the bottom texts but and set it to "fill", however this does not work at expected.
Also, using "space between" on the group does not work. Even if the stack min-height is set to 100%. If the alignment tools do not work within a column, it should not be displayed. Then, however, the column is missing the "space between" feature.

### Step-by-step reproduction instructions

1. Create the design as in the screen recording, or use the block markup
<details><summary>Block Markup</summary>
<p>

```html
<!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"backgroundColor":"neutral-20","layout":{"type":"default"}} -->
<div class="wp-block-group has-neutral-20-background-color has-background" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:group {"style":{"spacing":{"padding":{"right":"clamp(16px,6vw,96px)","left":"clamp(16px,6vw,96px)","top":"var:preset|spacing|v-padding-xl","bottom":"var:preset|spacing|v-padding-xl"}}},"backgroundColor":"neutral-20","layout":{"type":"default"}} -->
<div class="wp-block-group has-neutral-20-background-color has-background" style="padding-top:var(--wp--preset--spacing--v-padding-xl);padding-right:clamp(16px,6vw,96px);padding-bottom:var(--wp--preset--spacing--v-padding-xl);padding-left:clamp(16px,6vw,96px)"><!-- wp:columns {"verticalAlignment":null} -->
<div class="wp-block-columns"><!-- wp:column {"verticalAlignment":"top"} -->
<div class="wp-block-column is-vertically-aligned-top"><!-- wp:group {"align":"wide","style":{"dimensions":{"minHeight":""}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"top","justifyContent":"left"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xs"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:heading {"level":1,"fontSize":"display-sm"} -->
<h1 class="wp-block-heading has-display-sm-font-size">The easiest way to build beautiful websites with Gutenberg</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"heading-6"} -->
<p class="has-heading-6-font-size">Simple and clean templates for Wordpress Gutenberg. <br>With hundreds of patterns, Figma files and everything else digital teams needs.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"primary-90"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-primary-90-background-color has-background wp-element-button">Learn more!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:image {"id":445,"width":56,"aspectRatio":"1","scale":"cover","sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-resized is-style-rounded"><img src="http://prolooks.local/wp-content/uploads/2023/07/image-683x1024.jpeg" alt="" class="wp-image-445" style="aspect-ratio:1;object-fit:cover;width:56px" width="56"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":402,"width":56,"aspectRatio":"1","scale":"cover","sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-resized is-style-rounded"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-IKEX2B0tJJY-unsplash-683x1024.jpg" alt="" class="wp-image-402" style="aspect-ratio:1;object-fit:cover;width:56px" width="56"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":403,"width":56,"aspectRatio":"1","scale":"cover","sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-resized is-style-rounded"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-UlxfzEEN3HU-unsplash-683x1024.jpg" alt="" class="wp-image-403" style="aspect-ratio:1;object-fit:cover;width:56px" width="56"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":401,"width":56,"aspectRatio":"1","scale":"cover","sizeSlug":"large","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-large is-resized is-style-rounded"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-gPVzwSi5mws-unsplash-1024x683.jpg" alt="" class="wp-image-401" style="aspect-ratio:1;object-fit:cover;width:56px" width="56"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1","fontStyle":"normal","fontWeight":"600"}},"fontSize":"heading-3"} -->
<p class="has-heading-3-font-size" style="font-style:normal;font-weight:600;line-height:1">200+</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"paragraph-sm"} -->
<p class="has-paragraph-sm-font-size">happy customers</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1","fontStyle":"normal","fontWeight":"600"}},"fontSize":"heading-3"} -->
<p class="has-heading-3-font-size" style="font-style:normal;font-weight:600;line-height:1">15+</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"paragraph-sm"} -->
<p class="has-paragraph-sm-font-size">years experience</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:gallery {"columns":2,"linkTo":"none"} -->
<figure class="wp-block-gallery has-nested-images columns-2 is-cropped"><!-- wp:image {"id":445,"height":250,"sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://prolooks.local/wp-content/uploads/2023/07/image-683x1024.jpeg" alt="" class="wp-image-445" style="height:250px" height="250"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":403,"height":250,"sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-UlxfzEEN3HU-unsplash-683x1024.jpg" alt="" class="wp-image-403" style="height:250px" height="250"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":402,"height":250,"sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-IKEX2B0tJJY-unsplash-683x1024.jpg" alt="" class="wp-image-402" style="height:250px" height="250"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":401,"height":250,"sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://prolooks.local/wp-content/uploads/2023/07/martin-martz-gPVzwSi5mws-unsplash-1024x683.jpg" alt="" class="wp-image-401" style="height:250px" height="250"/></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
``` 

</p>
</details> 

2. Set spacer to fill
3. Or use the alignment for the 

### Screenshots, screen recording, code snippet


https://github.com/WordPress/gutenberg/assets/17861443/9f8ce825-4aac-4b6b-8ae5-d7404ca32cf7




### Environment info

- WP 6.2.2
- GB 16.2.1
- Custom theme

### Please confirm that you have searched existing issues in the repo.

No

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by tellthemachines**
<!-- Thanks for contributing to Gutenberg! Please follow the Gutenberg Contributing Guidelines:
https://github.com/WordPress/gutenberg/blob/trunk/CONTRIBUTING.md -->

## What?
<!-- In a few words, what is the PR actually doing? -->

Fixes #52825.

Adds a "stretch" option to the Column block vertical alignments, so that blocks inside it can stretch to 100% of its height.

## Testing Instructions
<!-- Please include step by step instructions on how to test this PR. -->
<!-- 1. Open a post or page. -->
<!-- 2. Insert a heading block. -->
<!-- 3. etc. -->

<details>
<summary>Add the following markup to a post</summary>

```html
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull"><!-- wp:column {"verticalAlignment":"stretch"} -->
<div class="wp-block-column is-vertically-aligned-stretch"><!-- wp:group {"align":"wide","style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"top","justifyContent":"left"}} -->
<div class="wp-block-group alignwide" style="min-height:100%"><!-- wp:group {"style":{"layout":{"selfStretch":"fill","flexSize":null}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xs"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:heading {"level":1,"fontSize":"display-sm"} -->
<h1 class="wp-block-heading has-display-sm-font-size">The easiest way to build beautiful websites with Gutenberg</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"heading-6"} -->
<p class="has-heading-6-font-size">Simple and clean templates for Wordpress Gutenberg. <br>With hundreds of patterns, Figma files and everything else digital teams needs.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"primary-90"} -->
<div class="wp-block-button"><a class="wp-block-button__link has-primary-90-background-color has-background wp-element-button">Learn more!</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|xxs"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:image {"id":188,"width":"56px","height":"undefinedpx","aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-full is-resized is-style-rounded"><img src="http://localhost:8888/wp-content/uploads/2023/07/b8737f096d768ee0.gif" alt="" class="wp-image-188" style="aspect-ratio:1;object-fit:cover;width:56px;height:undefinedpx"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":188,"width":"56px","height":"undefinedpx","aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-full is-resized is-style-rounded"><img src="http://localhost:8888/wp-content/uploads/2023/07/b8737f096d768ee0.gif" alt="" class="wp-image-188" style="aspect-ratio:1;object-fit:cover;width:56px;height:undefinedpx"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":188,"width":"56px","height":"undefinedpx","aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-full is-resized is-style-rounded"><img src="http://localhost:8888/wp-content/uploads/2023/07/b8737f096d768ee0.gif" alt="" class="wp-image-188" style="aspect-ratio:1;object-fit:cover;width:56px;height:undefinedpx"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":188,"width":"56px","height":"undefinedpx","aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","className":"is-style-rounded"} -->
<figure class="wp-block-image size-full is-resized is-style-rounded"><img src="http://localhost:8888/wp-content/uploads/2023/07/b8737f096d768ee0.gif" alt="" class="wp-image-188" style="aspect-ratio:1;object-fit:cover;width:56px;height:undefinedpx"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1","fontStyle":"normal","fontWeight":"600"}},"fontSize":"heading-3"} -->
<p class="has-heading-3-font-size" style="font-style:normal;font-weight:600;line-height:1">200+</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"paragraph-sm"} -->
<p class="has-paragraph-sm-font-size">happy customers</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"lineHeight":"1","fontStyle":"normal","fontWeight":"600"}},"fontSize":"heading-3"} -->
<p class="has-heading-3-font-size" style="font-style:normal;font-weight:600;line-height:1">15+</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"paragraph-sm"} -->
<p class="has-paragraph-sm-font-size">years experience</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:gallery {"columns":2,"linkTo":"none"} -->
<figure class="wp-block-gallery has-nested-images columns-2 is-cropped"><!-- wp:image {"id":194,"width":"undefinedpx","height":"250px","sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://localhost:8888/wp-content/uploads/2023/07/tumblr_ef4d6c9edbff0723397fd2bf21103b2d_c3a297fd_1280-1024x768.jpg" alt="" class="wp-image-194" style="width:undefinedpx;height:250px"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":147,"width":"undefinedpx","height":"250px","sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://localhost:8888/wp-content/uploads/2023/06/tumblr_909429fd4a783d8c9eb9a4d9f84e8649_c348b97e_1280-768x1024.jpg" alt="" class="wp-image-147" style="width:undefinedpx;height:250px"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":146,"width":"undefinedpx","height":"250px","sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://localhost:8888/wp-content/uploads/2023/06/tumblr_d2ced18f08f28bd12b5a5d08790a3a0c_6b4f1a61_1280-1024x768.jpg" alt="" class="wp-image-146" style="width:undefinedpx;height:250px"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":63,"width":"undefinedpx","height":"250px","sizeSlug":"large","linkDestination":"none","className":"is-style-default"} -->
<figure class="wp-block-image size-large is-resized is-style-default"><img src="http://localhost:8888/wp-content/uploads/2023/06/PXL_20230428_121033487-1024x768.jpg" alt="" class="wp-image-63" style="width:undefinedpx;height:250px"/></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

Check that  the groups in the left hand column stick to top and bottom of the column, like so:

<img width="1659" alt="Screenshot 2023-08-03 at 4 10 46 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/d67f8ff5-22ad-4112-a2d5-f65db846e550">


### Testing Instructions for Keyboard
<!-- How can you test the changes by using the keyboard only? Please note, this is required for PRs that change the user interface (UI). This ensures the PR can be tested for any possible accessibility regressions. -->

## Screenshots or screencast <!-- if applicable -->

### CODE REVIEW

**Comment by ramonjd** [comment]
This is a great feature. Looks good in editor and frontend.

https://github.com/WordPress/gutenberg/assets/6458278/bbb59f3d-840c-416b-8911-1b7faaf75ff4

**Review by andrewserong — COMMENTED** [review]
Cool idea! Unfortunately, I'm having a bit of trouble testing this out — apologies, I'm sure I'm missing something obvious 😅

I tried the test markup in the PR description, but I'm getting a bunch of block validation errors (I think because I don't have the image files locally).

In the linked issue, there's [an example](https://github.com/WordPress/gutenberg/issues/52825#issuecomment-1664463935) of Heading + Paragraph + Buttons where the idea would be for the Buttons block to be aligned to the bottom, so I thought I'd give that a try. With this PR applied, I'm not too sure how to get it to stretch in the expected way. Here's some test markup:

<details>

<summary>Test markup</summary>

```html
<!-- wp:columns {"verticalAlignment":null,"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">A heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Nunc quis libero nulla. Maecenas pellentesque quam ultrices, sollicitudin mauris in, pretium dui. Nam ut aliquet nibh. Aliquam erat volutpat. Aliquam erat volutpat. Suspendisse gravida magna a faucibus dignissim. Sed at sapien est.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">More info</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">A heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In urna velit, congue non laoreet id, consequat at metus. Etiam lobortis consequat ante, ac feugiat tellus sollicitudin et. Integer vitae tempus tortor, ac rhoncus ante. Donec efficitur pharetra ornare. Nunc quis libero nulla. Maecenas pellentesque quam ultrices, sollicitudin mauris in, pretium dui. Nam ut aliquet nibh. Aliquam erat volutpat. Aliquam erat volutpat. Suspendisse gravida magna a faucibus dignissim. Sed at sapien est.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">More info</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading">A heading</h3>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Another paragraph</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex"}} -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">More info</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

With that markup, I added some background colors to the individual column blocks, and played around with setting each column to `stretch`, but I couldn't quite work out what `stretch` was doing that's different to the default state which uses `flex-grow: 1` (visually, both the default vertical alignment and `stretch` appeared to be the same), or how to get Buttons to stick to the bottom:

https://github.com/WordPress/gutenberg/assets/14988353/8571f956-7534-400b-9801-e2615282ba3c

Is there a particular set of steps you had in mind for what `stretch` unlocks? Happy to do further testing / playing around, of course!

**Comment by tellthemachines** [comment]
Sorry I could have explained that more clearly. In order for this to work, the Column content should be wrapped in a Stack block set to `min-height: 100%`. There's not a huge advantage to doing things this way as opposed to nesting Stacks inside Rows, but some folks prefer using the Columns block as it's easier to add/remove columns I guess.

<details>
<summary>some markup that should work</summary>

```html
<!-- wp:columns {"verticalAlignment":null,"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"verticalAlignment":"stretch","width":"22.22%"} -->
<div class="wp-block-column is-vertically-aligned-stretch" style="flex-basis:22.22%"><!-- wp:group {"style":{"dimensions":{"minHeight":"100%"}},"layout":{"type":"flex","orientation":"vertical","verticalAlignment":"space-between"}} -->
<div class="wp-block-group" style="min-height:100%"><!-- wp:paragraph -->
<p>column 1</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button">button</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"44.45%"} -->
<div class="wp-block-column" style="flex-basis:44.45%"><!-- wp:paragraph -->
<p>column 2</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>text</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

**Review by andrewserong — APPROVED** [review]
Ah, excellent, thanks for the test markup! That's working for me now. I notice that it's also working on `trunk`, though, without the `stretch` option, but just by using the default orientation of the Column block:



That said, I think it's a good idea to include the `stretch` option, because as a user the list of orientation options feels like a complete list of what's available to me, rather than something where I should know to toggle one of the options off.

https://github.com/WordPress/gutenberg/assets/14988353/4ecd1d57-7faf-49d9-b202-d15089e6314b

This is all testing nicely for me, and feels like a good UI improvement to me. LGTM! ✨

**Comment by tellthemachines** [comment]
Thanks for reviewing!

>  I notice that it's also working on trunk, though, without the stretch option, but just by using the default orientation of the Column block

🤔 good point. [This line](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/columns/style.scss#L14) in the block styles is making sure stretch is the default value. Still the control can be helpful to make things clear.

**Pull request merged**
