### PR TITLE
Fix link to wide alignment

### PR DESCRIPTION
**Pull request by ajitbohra**
Fix broken link to theme support `Wide Alignment`

### CODE REVIEW

**Comment by gziolo** [comment]
It look like it won't solve the issue with the broken link in the handbook according to my manual. Here is related PR where we tried to find a solution which works for both GitHub and Handbook: #6161.

Here is the related change added by @pento: 
https://meta.trac.wordpress.org/changeset/7141


```php
print preg_replace( '/(\[.*?\]\((\.\.\/)+.*?)(\.md)?\)/i', '$1)', '[wide alignment](../docs/extensibility/theme-support.md/#wide-alignment)' );

// Outputs [wide alignment](../docs/extensibility/theme-support.md/#wide-alignment)
// Should be [wide alignment](../docs/extensibility/theme-support#wide-alignment)
```

**Comment by ajitbohra** [comment]
yes you are right this will not work we need to update the regex

keeping this open for discussion

**Comment by Soean** [comment]
@ajitbohra Can you retest it the issue? i think it's fixed.

**Comment by ajitbohra** [comment]
@Soean yes it's working as expected :+1:  closing this PR

**Pull request closed without merging**
