### PR TITLE
Spacer: add spacing block supports 

### PR DESCRIPTION
**Pull request by ramonjd**
Related:
- https://github.com/WordPress/gutenberg/issues/43241
- https://github.com/WordPress/gutenberg/issues/43243

## What?

Enabling axial margin support for the spacer block.

## Why?

To create consistency across blocks.

## How?

Adding the relevant block supports in block.json

## Testing Instructions

1. Load the block editor and add a Video block. Add some content or use the example block code below.
2. Confirm that the dimensions control panel is there and the margin control is shown by default.
3. Add margins / axial margins.
4. Save and confirm the styles appear on the frontend. 
5. Test the new support works for the block via theme.json and global styles. See example JSON below.

```json
	"styles": {
		"blocks": {
			"core/spacer": {
				"spacing": {
					"margin": {
						"top": "120px",
						"bottom": "140px"
					}
				}
			}
		}
	}
```

https://user-images.githubusercontent.com/6458278/185367077-9c363974-a6fe-44e1-8583-b908c89f8005.mp4

### CODE REVIEW

**Review by apeatling — COMMENTED** [review]
Everything is working except for the theme.json code. Can you double check that is working for you? The styles did not seem to apply on the front end for me.

**Comment by ramonjd** [comment]
Appears that the individual margin sides at the theme.json block level are a known curiosity: https://github.com/WordPress/gutenberg/pull/43365#issuecomment-1220093440

Given that things work in the editor for block supports, which is the major thrust of these PRs, do folks think it's okay to allow support here and address the universal issue elsewhere?

**Comment by apeatling** [comment]
Yes sounds good

**Review by glendaviesnz — APPROVED** [review]
Worked as advertised for me in editor and front-end. Agree that we should merge this and look at the theme.json issue in follow ups.

**Pull request merged**
