### PR TITLE
Remove user-select:text

### PR DESCRIPTION
**Pull request by ellatrix**
Related #60021
 
## What?

In trunk, if you have a container that is a stack or a grid block with a paragraph within it, it's very hard to select the container even if it has padding... The paragraph automatically steals focus.

It turns out that we had some CSS introduced a long time ago in #43313 to improve multi-selection styles in Safari that was responsible for this buggy behavior. 

In my test, removing this CSS doesn't break the multi-selection, so this is probably not needed anymore.

## Testing Instructions

1- Insert a stack block with some padding
2- Insert a paragraph within it
3- Unselect the blocks by clicking the title
4- Click the "padding" area
5- The stack should be selected and not the paragraph within it.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
This is working great in my testing and fixes the issue.

**Comment by youknowriad** [comment]
@ellatrix looks like there are some failing e2e tests, not sure if it's related. WDYT?

**Comment by getdave** [comment]
Wow this is an obscure bug. Great work on narrowing it down as it directly impacts on features such as Zoom Out and Edit modes.

**Comment by ellatrix** [comment]
@youknowriad I knew that there was would be no functional regression, the question is if we're ok with the visual regression (I assume there is one if @jasmussen added it).

**Comment by jasmussen** [comment]
Well, the question is if it reintroduces the visual artifacting that happens when you select across text blocks in Safari. If the same steps to reproduce the issue, that are outlined in #43313 still apply, then that is a problem, because it's going to be a terrible text editing experience. I can't test now, but one would hope that Safari has improved since then.

**Comment by youknowriad** [comment]
I tested multi selection and I believe I don't see the issue, but you know sometimes I don't really understand what I need to test.

**Comment by youknowriad** [comment]
Screenshot 2024-10-01 at 9 23 26 AM

**Comment by jasmussen** [comment]
Yep, seeing the same in my Safari test. Hopefully that means it's fixed. Worth trying, but let's keep an eye on selecting across blocks in Safari post-merge!

**Comment by draganescu** [comment]
Re re re confirming this is OK :) 

Screenshot 2024-10-01 at 12 14 58

**Comment by youknowriad** [comment]
There's some e2e test failures in this PR but I'm not sure if they are related. They seem to pass locally for me. Any ideas?

**Comment by youknowriad** [comment]
It looks like "shift + arrow" is not working properly in this PR in Firefox, it doesn't cross the boundaries of the list block into a preceding paragraph block.

**Comment by ellatrix** [comment]
@youknowriad @jasmussen the failures are caused by the disabling of text selection introduced in #58169. For some reason that's applied in the post editor too. Either we remove it or we need to find a class combo so that it's not applied in unwanted places.

**Comment by ellatrix** [comment]
Tests should pass now hopefully. So only a few months ago I introduced these Firefox e2e tests. Really glad I did then, or we would have broken it now.

**Comment by youknowriad** [comment]
Highly appreciated help in this PR Ella thanks a lot.

**Comment by youknowriad** [comment]
Seems like it might not have solved all the "stealing focus" issues.

**Comment by ellatrix** [comment]
Fix https://github.com/WordPress/gutenberg/pull/65857

**Pull request merged**
