### PR TITLE
Fix Nav Menu overflow using flex-wrap approach

### LINKED ISSUE #18298: Navigation Menu: handle overflowing Nav Items
Currently when lots of items are added to the navigation menu, the block forces the editor container to widen, which adds a horizontal scrollbar to the entire editor:
Screen Shot 2019-11-06 at 5 47 50 pm

It looks kinda terrible!

Instead, we might consider adding a horizontal scroll container within the block itself.

See the table block for prior art on this.

### PR DESCRIPTION
**Pull request by jasmussen**
Closes https://github.com/WordPress/gutenberg/issues/18298

This PR handles navigation menu overflow by simply allowing wrapping of Nav Items. Please see [the Issue for more context about the decision making process](https://github.com/WordPress/gutenberg/issues/18298) behind this approach.

Screenshot 2019-11-11 at 14 52 46

### Testing

1. Add new Post
2. Add Nav Block
3. Switch Editor to "Code Mode"
4. Copy testing Block (see below) markup
5. Paste into Editor code-view window.
6. Switch back to "Visual" mode.
7. See large Nav with many items.
8. Test it wraps and interacts as expected.

Here's a handy long nav for testing

```
<!-- wp:navigation-menu {"backgroundColorCSSClass":null,"textColorCSSClass":null} -->
<!-- wp:navigation-menu-item {"label":"Sample Page","title":"Sample Page","type":"page","url":"http://localhost:8889/sample-page/"} /-->

<!-- wp:navigation-menu-item {"label":"Test Page!","title":"Test Page!","type":"page","url":"http://localhost:8889/test-page/"} /-->

<!-- wp:navigation-menu-item {"label":"Sample Page","title":"Sample Page","url":"http://localhost:8889/sample-page/"} /-->

<!-- wp:navigation-menu-item {"label":"Sapiente repellendus eius quisquam odio corporis consequuntur","title":"Sapiente repellendus eius quisquam odio corporis consequuntur","url":"http://localhost:8889/sapiente-repellendus-eius-quisquam-odio-corporis-consequuntur/"} /-->

<!-- wp:navigation-menu-item {"label":"Saepe omdddnis commodi veniam dolores tempore est","title":"Saepe omnis commodi veniam dolores tempore est","url":"http://localhost:8889/saepe-omnis-commodi-veniam-dolores-tempore-est/"} /-->

<!-- wp:navigation-menu-item {"label":"Test Page!","title":"Test Page!","url":"http://localhost:8889/test-page/"} /-->

<!-- wp:navigation-menu-item {"label":"Qui ducimus mdddd dolestiae deserunt qui","title":"Qui ducimus molestiae deserunt qui","url":"http://localhost:8889/qui-ducimus-molestiae-deserunt-qui/"} /-->

<!-- wp:navigation-menu-item {"label":"Sapidddddente repellendus eius quisquam odio corporis consequuntur","title":"Sapiente repellendus eius quisquam odio corporis consequuntur","url":"http://localhost:8889/sapiente-repellendus-eius-quisquam-odio-corporis-consequuntur/"} /-->
<!-- /wp:navigation-menu -->

```

### CODE REVIEW

**Comment by jasmussen** [comment]
This is an alternative fix for #18298, CC: @talldan @mtias.

**Comment by getdave** [comment]
My only concern is that the nav could now easily not look like a Nav but rather a "flow" of text.

**Comment by jasmussen** [comment]
> My only concern is that the nav could now easily not look like a Nav but rather a "flow" of text.

I think that's a valid concern, and one that could likely be looked at separately by perhaps defaulting to blue underlined links with some style variations, or perhaps making the items more "menu item-like". Much of this will also be up to the theme, in this screenshot I primarily used the vanilla styles. A theme could do a lot to enhance this.

**Comment by shaunandrews** [comment]
I think wrapping, while a fine mvp solution, is going to cause confusion when dealing with multi-level menus. At some point it will be impossible to tell where you are within the structure of the navigation. Perhaps this isn’t a major concern, but I feel it’s an untenable solution.

**Comment by getdave** [comment]
@jasmussen I just pushed a "fix" to solve 2 things

1. I've flexed the nav items to allow them to occupy a reasonably amount of space based on their content width. This means we have a more "nav like" layout effect with each item clearly distinguishable as an "item".
2. I've taken the Block movers out of the flow to avoid the layout "jump" when the Block is selected. This ensures all items stay on their original line and things don't change place or jump underneath your cursor.

Let me know if you feel this is a good improvement?

See below for before and after. :

### Before

Notice how things change position and the layout jumps. Also, it's not clear that the items are nav items. They look like long lines of paragraph text.

Screen Capture on 2019-11-14 at 14-22-27


### After

Notice less layout reflow. Also items are clearly distinguishable as individual nav items:

Screen Capture on 2019-11-14 at 14-21-45

**Comment by getdave** [comment]
> I think wrapping, while a fine mvp solution

@shaunandrews That's good because https://github.com/WordPress/gutenberg/issues/18298#issuecomment-553868002

> At some point it will be impossible to tell where you are within the structure of the navigation. Perhaps this isn’t a major concern, but I feel it’s an untenable solution.

I think your "mover" proposal will be the best long term solution.

**Comment by getdave** [comment]
I've changed my mind on the UX for this since [this experiment](https://github.com/WordPress/gutenberg/pull/18431#issuecomment-553912460).

I prefer keeping things simple and allowing the items to wrap naturally.

The only change I've kept is to slim down the amount of horizontal space occupied by each Nav item. 

Now looking for confirmation we're good to merge this from a design POV @shaunandrews. Also pinging @jasmussen as the original PR author.

**Comment by draganescu** [comment]
I like how this looks, when there is a multitude of links it resembles a tag cloud :) I wonder what happens with submenus.

**Comment by getdave** [comment]
> ...there is a point where you loose where exactly you are, visually.

An alternative is to force a reasonable set width for each item, thereby ensuring a columular layout which would make it easier to see the submenus. The width would be arbitary and hardcoded though because if you allow flex-box to auto size then you get a lot of jumping when you select an item (due to movers appearing).

I feel like we need to consider the experience in more detail before more coding is done. I will need design support with this...

**Comment by jasmussen** [comment]
> I prefer keeping things simple and allowing the items to wrap naturally.
> The only change I've kept is to slim down the amount of horizontal space occupied by each Nav item.

What other change had you made? Just curious. But I do agree, just keep it simple, we'll revisit in a V2 with an overflow menu anyway. Spacing looks good.

> there is a point where you loose where exactly you are, visually.

It's important to keep in mind here what is the theme and what is the menu, and not only that, what styles should the block provide vs. what should the theme provide. 

The end result is that what the stock menu provides has to, unfortunately, be pretty basic — just links. Otherwise it just creates headaches for themes. 

And right now none of those themes have styled the navigation menu, neither front nor backend. So some of this is a chicken and egg situation. Some of it has to be solved in a more holistic way by improving how themes can opt in or out of "opinionated styles" provided by the block. It's just important we don't do "one-off" design improvements that will effectively end up tecnical debt and themer headaches.

Finally, I think this is an opportunity to revisit the block UI itself, and I have some ideas how to address this. But this also has to happen in a holistic way.

**Comment by getdave** [comment]
e2e tests are suddenly failing. I've rebased as a first step to resolving this.

**Comment by getdave** [comment]
Will be switching back to this soon.

**Comment by getdave** [comment]
@jasmussen Looks like we're good to go on this. Might need a final design review though...

**Comment by jasmussen** [comment]
> Looks like we're good to go on this. Might need a final design review though...

I see the following in this branch:

Screenshot 2019-12-02 at 19 54 48

Here's what's shipping in the plugin:

Screenshot 2019-12-02 at 19 57 45

I think this is a vast improvement, and thoroughly shippable. 

Note: I can't get the menu to work in master though, I'm getting this:

Screenshot 2019-12-02 at 19 57 51

That failure is unrelated to your PR, though, and is possibly an issue on my end. But might want to test master on your end to see if it's broken there for you too, just before you merge. That will make any regressions easier to debug. 

Oh, and I can't approve my own PR, but as a design sanity check, 👍 👍

**Review by getdave — APPROVED** [review]
Following on from [@jasmussen's design review](https://github.com/WordPress/gutenberg/pull/18431#issuecomment-560533289) 👍 I'm going to approve this one on his behalf.

**Pull request merged**
