### PR TITLE
editor: Use a small multiselect buffer zone

### LINKED ISSUE #2646: Drag to select doesn't kick in until the third block
## Expected Behavior
When I start selecting text inside a paragraph block and drag down, into the next block, that block should become selected as well.

## Current Behavior
This doesn't happen until you reach the third block while dragging. If you then drag up again without letting go of the mouse button, you can reduce the selection to two blocks, but you cannot start with just two blocks selected.

select

### PR DESCRIPTION
**Pull request by youknowriad**
fixes #2646 

I'm not sure why this buffer zone exists in the first place, but making it smaller makes it a better experience IMO.

### CODE REVIEW

**Comment by aduth** [comment]
Not sure I feel entirely comfortable reviewing something when we don't know the original intent and therefore the impact of the changes 😄

**Comment by aduth** [comment]
cc @iseulde

**Comment by iseulde** [comment]
I. agree with this change. May need more tweaking. @jasmussen suggested setting it really high. back when it was first added, but I agree it's weird on small blocks.

**Comment by jasmussen** [comment]
Definitely tune it if need be. I did suggest setting it SUPER high, because I feel like it's easier to pull back from up high, than the other way around.

**Pull request merged**
