### PR TITLE
Expand the multi-entity saving panel by default

### PR DESCRIPTION
**Pull request by youknowriad**
Follow up to #26355 

Based on some discussion with @jameskoster and @jasmussen it was decided that this multi-entity saving panel should be expanded by default.

**Testing instructions**

 - Enable an FSE theme
 - Add a site title block to a post
 - Edit the site title
 - Try to publish your post

### CODE REVIEW

**Review by jameskoster — APPROVED** [review]
Working as advertised.

Screenshot 2020-12-02 at 10 30 10

**Comment by youknowriad** [comment]
I just moved ahead and removed the ability to expand the changes entirely. What do you think?

**Comment by jameskoster** [comment]
I think that is a little more tricky. If there are lots of changes in different contexts (template + parts + global styles + content + site data) it may be more convenient to work through them one section at a time, and collapsing may help with that?

No strong opinion here though. Probably fine to remove the collapsibility for now if it's easy to add back. I'll defer to @jasmussen on this :D

**Comment by jasmussen** [comment]
> I think that is a little more tricky. If there are lots of changes in different contexts (template + parts + global styles + content + site data) it may be more convenient to work through them one section at a time, and collapsing may help with that?

On the one hand, I have a semi strong opinion that the entire reason we have a pre-publish panel in the first place is to show exactly this, so if we don't do that, why even have a prepublish dialog. And furthermore, when a panel defaults to open, and doesn't save its state across sessions, it shouldn't need the ability to collapse. 

On the other hand, I recall @mtias expressing, at times, the desire to keep multi entity saving simple, because most of the time and when you are in a site editing context, you know what you're doing. 

In absence of him chiming in, I'd say remove it. And if he chimes in later and disagrees, one round on me 😅 

Screenshot 2020-12-02 at 11 57 01

This double border annoys me, though 😅 — and now I want to eat at Pizza Planet.

**Comment by jasmussen** [comment]
Oh wait just to be clear, it's this blue "hide changes" link that I mean we should remove:

Screenshot 2020-12-02 at 11 59 40

I don't mind keeping these collapsible:

Screenshot 2020-12-02 at 12 00 03

**Comment by youknowriad** [comment]
I removed the double border already :)

**Comment by youknowriad** [comment]
@jasmussen that's what I did already.

**Comment by jasmussen** [comment]
Sigh. One round on me, clearly. You're too fast for me Riad.

**Comment by mtias** [comment]
Yes, please! :)

**Review by mtias — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
Sorry for being late to the party.

> Based on some discussion with @jameskoster and @jasmussen it was decided that this multi-entity saving panel should be expanded by default.

I am on board with this change.  That was sort of the original idea when moving it over from the old modal.

> I just moved ahead and removed the ability to expand the changes entirely. What do you think?

If its open by default, I don't think there is a need for the expand/collapse option.

Pinging @MichaelArestad as he might have some thoughts on this.  IIRC he is the one that convinced us to go with trying the hidden by default expanding panel approach.

**Pull request merged**
