### PR TITLE
Add copilot markers to PR template

### PR DESCRIPTION
**Pull request by priethor**
### <samp>🤖 Generated by Copilot at 0db1c55</samp>

Updated the pull request template to use GitHub Copilot features. This can help create more informative and consistent pull requests.
## Why?

To automatically provide PRs with a GitHub copilot summary (`What`) and detailed description (`How`)
### <samp>🤖 Generated by Copilot at 0db1c55</samp>

* Enable automatic summary and description generation for pull requests ([link](https://github.com/WordPress/gutenberg/pull/50063/files?diff=unified&w=0#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R7-R10),[link](https://github.com/WordPress/gutenberg/pull/50063/files?diff=unified&w=0#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R17-R20))
## Testing Instructions

1. Open a PR
2. Fill the PR description as usual without removing the `copilot:xxx` markers.

## Screenshots or screencast 
This PR description shows how it would look like when opening a PR! 🙂

### CODE REVIEW

**Comment by youknowriad** [comment]
To be completely honest, in my short period testing it. I find it useful to get a starting point but I expected better results. So I'm not entirely sure that we should rely on it too much otherwise we might get lazy and lose a bit of quality in PR descriptions.

**Comment by apeatling** [comment]
Yes I was just going to say a similar thing to Riad. They tend to be a bit matter of fact and don't add a huge amount of value. Maybe a better idea would be to include them in a commented out section to let folks know they can use them if they want?

**Comment by gziolo** [comment]
I’m skeptical but curious about how it will work in practice. Some people started using AI to write these descriptions, so maybe we should give it a try but, at the same time, put more emphasis on „why” section that AI doesn’t know 😀

**Comment by andrewserong** [comment]
Just echoing the other comments, but one of the big limitations of the copilot summary is that it can provide a factual "what" but not explain the real purpose behind a PR, so I tend to find the summaries either difficult to parse, or not quite useful enough. I much prefer reading a human-written summary to understand what the intent of the PR author is.

> Maybe a better idea would be to include them in a commented out section to let folks know they can use them if they want?

Keeping it in the commented out section sounds like a good option, so folks can opt in to using it if they'd like.

**Comment by priethor** [comment]
> Maybe a better idea would be to include them in a commented out section to let folks know they can use them if they want?

Does it work when commented out? I was [trying it](https://github.com/WordPress/gutenberg/pull/50063/commits/07ab05056b10cac99b6c3770c7c56ed7a8a078d3) in this same PR so that it wasn't intrusive for folks not used to it, but the bot didn't kick in.

**Review by gziolo — APPROVED** [review]
I'm approving it in case you want to give it a try. We can revisit it in a few days. It's easy to revert all these changes.

**Comment by apeatling** [comment]
> Does it work when commented out? I was [trying it](https://github.com/WordPress/gutenberg/pull/50063/commits/07ab05056b10cac99b6c3770c7c56ed7a8a078d3) in this same PR so that it wasn't intrusive for folks not used to it, but the bot didn't kick in.

I was thinking more in a commented out section "You can use the following copilot commands if you wish: X, Y, Z", that could then be copied/pasted outside of the commented section if desired. Just a thought.

**Comment by andrewserong** [comment]
> I was thinking more in a commented out section "You can use the following copilot commands if you wish: X, Y, Z", that could then be copied/pasted outside of the commented section if desired. Just a thought.

That's what I was thinking, too.

**Comment by priethor** [comment]
I see now, thanks. That could be good for helping contributors get familiar with copilot, but on the other hand, it makes it more work in general than just typing `copilot:summary` once you know the marker. I think it's better not to add things to the template unless they are direct and simple; if we agree it's better to add instruction rather than the marker, I'd lean towards adding nothing at all 😅

**Comment by apeatling** [comment]
My opinion isn't super strong, so happy to go with consensus. My argument would be that if every PR has Copilot generated content it's probably worse for PR readability at this point. That might change in the future if it gets better.

**Comment by priethor** [comment]
Closing this as GitHub is [ending support for copilot in PRs](https://githubnext.com/copilot-for-prs-sunset).

**Pull request closed without merging**
