### PR TITLE
RichText: Don't update live DOM on composition

### PR DESCRIPTION
**Pull request by ellatrix**
## Description
See #11813 and #11795. This is just an attempt at fixing the issue.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

### CODE REVIEW

**Review by youknowriad — APPROVED** [review]
Approving because it seems to fix the issue https://wordpress.slack.com/archives/C02QB2JS7/p1542286893546800

**Comment by iseulde** [comment]
@torounit Thanks, I'll investigate further!

**Comment by yoavf** [comment]
Tested this by installing Japanese on my mac and setting it up like described [here](https://redcocoon.org/cab/mysoft.html). If not using qwerty, make sure to also change the `Romanji layout` option.

Test:

- In a post add a list block
- Switch to Hiranga in the typing menu
- start tying the characters `nihonn` 
- You should see it converted to `にほん`

**Before:**
screen capture on 2018-11-15 at 15-29-13


**After:**
screen capture on 2018-11-15 at 15-30-44

**Comment by torounit** [comment]
@iseulde 

One character should be deleted, but all characters are deleted.

output

**Comment by iseulde** [comment]
@torounit Does the deletion problem also happen before in 4.2, or was it okay back then? @yoavf Do you see the same problem?

**Comment by youknowriad** [comment]
From the code change, I don't think the deletion bug is an issue with the current PR

**Comment by yoavf** [comment]
＞@yoavf Do you see the same problem?

Works fine for me:

screen capture on 2018-11-15 at 15-45-54

I'm on a mac, using Hiragana. @torounit what are you using?

**Comment by torounit** [comment]
@iseulde 
the deletion problem not happen in 4.2, 4.3 and master.  Only This Branch.


@yoavf 
I'm on a Mojave. using Hiragana.  

This problem does not occur when space or alphabet is mixed.

**Comment by iseulde** [comment]
@torounit It would be good to have the sequence of events, e.g. using the tool shared by @ocean90: https://input-inspector.now.sh/.

**Comment by torounit** [comment]
@iseulde 

https://input-inspector.now.sh/profiles/eP9rFmPp3uTfF3ycQLGB

nice tool !!!

**Comment by torounit** [comment]
on Firefox, the deletion problem not happen.

**Comment by iseulde** [comment]
@torounit To be sure, this is on Mojave and Chrome? Do you use the native IME or something else?

**Comment by torounit** [comment]
@iseulde 166ebd8 dosen't work.

**Comment by atachibana** [comment]
FYI.
Test on Windows 10 Japanese without  `166ebd8`.
The same error of clearing entire block by one hit of BackSpace key occurred on Windows with both Google IME and MS IME.
Edge was OK for both IMEs.

**Environment**
Windows 10 Pro Japanese
Google IME and/or MS-IME
Chrome 70.0.3538.77
Edge 42.17134.1.0

**Comment by iseulde** [comment]
Thanks! @torounit @atachibana Could you test again with 9110d08? :)

**Comment by torounit** [comment]
@iseulde 9110d08  dosen't work. :(

**Comment by iseulde** [comment]
@torounit Thanks! Let me try one more thing. :) Also, why is "Enter" pressed in Chrome but not in Firefox?

**Comment by torounit** [comment]
@iseulde 
"Enter" pressed both browser. but It is not recorded on Firefox.

safari: https://input-inspector.now.sh/profiles/2DDzBa29IEDb7IxmszZ9

**Comment by iseulde** [comment]
@torounit Last try: 4e060d1.

**Comment by torounit** [comment]
@iseulde  it works. in Chrome 70 on Mojave. 👍 
I will try other browser.

**Comment by iseulde** [comment]
@torounit Oh, great!!

**Comment by youknowriad** [comment]
Awesome collaboration work on this PR 👏

**Comment by torounit** [comment]
@iseulde Thanks !
 Works properly on Chome 70 / Firefox 63 / Safari 12 on Mojave.

**Comment by iseulde** [comment]
Cool! Thanks for all the help!

**Comment by waviaei** [comment]
Finally catching up (got caught up with messed up local env on my home MBA...)

- Mojave 10.14.1
- ATOK IME (note: its a 3rd party IME software, not the one default with Mac)
- Chrome 70.0.3538.102
- Safari 12.0.1
- Firefox 63.0.1

4e060d1 - as @torounit mentioned, it seem to have fixed it!
I did 1) type some Japanese, 2) then delete few letters, 3) then typed some more.
With following blocks. IME functioned normal as expected.

- paragraph
- list
- quote
- heading
- preformatted
- code (mixed typing of code and comment out with Japanese text)
- pullquote
- table
- verse
- media and text
- button

For your info, I did test with 9110d08 and it was like this (I had not done through testing on 4.2, so I cannot be sure if worked correctly before, except for paragraph, list and quote).

- paragraph => delete button deleted everything (as per @torounit reported)
- list => seems fixed
- quote => seems fixed
- verse => no issue with input, but unable to delete anything at all
- pull quote => seems ok
- preformatted text => no issue with input, but when you move on to a next block, placeholder text reappears underneath the typed text
- code => seems ok
- button => placeholder text did not disappear when you start typing. Only disappear after you confirm the Japanese character.
- Media and text => text part was same as paragraph.

I think through testing with different blocks might still be needed, but looks good!

Many many thanks @iseulde @torounit !

**Comment by iseulde** [comment]
@waviaei Thanks for the additional testing. It seems the major issues have been fixed. Could you report any remaining issues separately? Thanks!

**Comment by mcsf** [comment]
Nice fix!

**Pull request merged**
