### PR TITLE
Fix Shift+Tab to Block Toolbar

### LINKED ISSUE #51876: Regression in Shift+Tab during writing mode
### Description

In 6.2.2 pressing <kbd>Shift</kbd>+<kbd>Tab</kbd> moves focus to the block toolbar. In trunk, it moves to the editor toolbar.

### Step-by-step reproduction instructions

1. In the Post Editor insert or focus a block and begin typing
2. Press <kbd>Shift</kbd>+<kbd>Tab</kbd>
3. Observe that focus moved to the editor toolbar

## Expected behavior in 6.2.2

https://github.com/WordPress/gutenberg/assets/9000376/ce64f88e-9c89-438b-9327-4997a202d7cd

## Regression in trunk

https://github.com/WordPress/gutenberg/assets/9000376/ca9130f0-c5f8-4316-99c2-7b44a2302039

### Environment info

Chrome on macOS

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by diegohaz**
Fixes #51876
Related to #52196 

After migrating the Toolbar component from Reakit to Ariakit on #51623, we encountered a regression in the <kbd>Shift</kbd>+<kbd>Tab</kbd> behavior for the Block Toolbar. Additional details can be found on #51876.

I'm still not sure why that's happening as I couldn't reproduce it outside of Gutenberg, but it seems that Ariakit v0.2.10 was setting `tabIndex={-1}` to all toolbar items before there was an active item with `tabIndex={0}`, resulting in a few frames with no tabbable elements in the block toolbar. So there wasn't anything to focus on in the block toolbar when pressing <kbd>Shift</kbd>+<kbd>Tab</kbd>. This could be fixed in Gutenberg by forcing the toolbar items to have `tabIndex={0}` on the initial render.

This PR upgrades Ariakit to v0.2.12, which updated this behavior on https://github.com/ariakit/ariakit/pull/2601. Although the change was initially intended to resolve another issue, it appears to fix this problem as well.

## Testing Instructions

1. In the Post Editor insert or focus a block and begin typing
2. Press <kbd>Shift</kbd>+<kbd>Tab</kbd>
3. Observe that focus moved to the block toolbar

### CODE REVIEW

**Review by jeryj — APPROVED** [review]
This resolves it for me! Thanks for fixing this and also adding a test, @diegohaz! 👏🏻

**Review by t-hamano — APPROVED** [review]
Thank you, this PR worked correctly in my environment!

- OS: Windows 11
- Browser: Google Chrome 114.0.5735.199, Firefox 115.0.2

https://github.com/WordPress/gutenberg/assets/54422211/d257ac0f-702b-4bf8-960c-17f3bb0868a2

**Comment by draganescu** [comment]
Thank you @diegohaz 👏🏻 

I wonder why it didn't work for Jerry, me and Aki when upgrading the package? In the same line of thought the upgrading of packages in the Gutenberg repo advises using `lerna add` after removing the package, but `lerna` removed the `add` command.

**Comment by diegohaz** [comment]
> Thank you @diegohaz 👏🏻 
> 
> 
> 
> I wonder why it didn't work for Jerry, me and Aki when upgrading the package? In the same line of thought the upgrading of packages in the Gutenberg repo advises using `lerna add` after removing the package, but `lerna` removed the `add` command.

Yeah! That's quite confusing. I don't have lerna installed globally, so I used `npx lerna add`, which I guess will reuse the local version if it's defined in the dependencies. I also had to restart `npm run dev`.

**Pull request merged**
