### PR TITLE
ESLint Plugin: Fix rule selectors

### PR DESCRIPTION
**Pull request by tfrommen**
## Description

The two (regular expression) selectors of the custom `no-restricted-syntax` rule in `eslint-plugin` are broken.

For example, the first regular expression, `^__|_n|_x$`, is equivalent to the following list of patterns:

* `^__`
* `_n`
* `_x$`

Obviously, what the author had in mind, however, is this list:

* `^__$`
* `^_n$`
* `^_x$`

Because of the broken rule, my call to `__experimentalGetSettings` (imported from `wp.date`/`@wordpress/date`) got flagged; it matches the `^__` pattern/option.

Also, calling the fictional function `foo_x()` would also flag up, as it matches the last pattern/option, `_x$`.

In addition to the above bugs, the two selectors shuold also account for `_nx`, which is currently only tested for the third (i.e., index `2`) argument, which is yet another error. It should be checked for indexes `0`, `1` and `3`, that is: `single`, `plural` and `context` (not `number`).

## How has this been tested?
Run ESLint with the old and with the new rule on this code:

```js
const { __experimentalGetSettings } = wp.date;
const { __, _n, _nx, _x } = wp.i18n;

const foo_x = () => {};

const foo = 'bar';

/**
 * Should NOT flag
 */
__( 'Some text', 'text-domain' );
_n( 'Some text', 'Some texts', 42, 'text-domain' );
_nx( 'Some text', 'Some texts', 42, 'Some context', 'text-domain' );
_x( 'Some text', 'Some context', 'text-domain' );
const settings = __experimentalGetSettings();
foo_x();

/**
 * SHOULD flag
 */
__( foo, 'text-domain' );
_n( foo, 'Some texts', 42, 'text-domain' );
_nx( foo, 'Some texts', 42, 'Some context', 'text-domain' );
_x( foo, 'Some context', 'text-domain' );

_n( 'Some text', foo, 42, 'text-domain' );
_nx( 'Some texts', foo, 42, 'Some context', 'text-domain' );
_x( 'Some text', foo, 'text-domain' );

_nx( 'Some text', 'Some texts', 42, foo, 'text-domain' );
```

## Types of changes
Fix several issues with ESLint rule selectors. Most of them have to do with the regular expressions, one issue is an incorrect argument index.

By the way, I decided to go with `_nx` as new sub-pattern/option, and not make `_n` be `_nx?` or so. Both for cinsistency and better readability.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by tfrommen** [comment]
Ideally, the rule `no-restricted-syntax` would be [moved from the config file](https://github.com/WordPress/gutenberg/blob/562d061e261db89a72e76776fcdd75b7d9440590/packages/eslint-plugin/configs/custom.js#L11-L25) to a separate file, which then should have a test file. Thoughts?

**Comment by gziolo** [comment]
> Ideally, the rule `no-restricted-syntax` would be [moved from the config file](https://github.com/WordPress/gutenberg/blob/562d061e261db89a72e76776fcdd75b7d9440590/packages/eslint-plugin/configs/custom.js#L11-L25) to a separate file, which then should have a test file. Thoughts?

I guess it is never executed inside Gutenberg as we override `no-restricted-syntax`... I agree that this could be extracted to its own rule to fix this issue at the same time.

**Review by swissspidy — APPROVED** [review]

**Review by ntwb — APPROVED** [review]
LGTM 👍 

Added the changelog entry in https://github.com/WordPress/gutenberg/commit/8e93ae347ea109cef0dde990f0620a1faefc32fd

**Review by aduth — APPROVED** [review]
Whoops, I'll take the blame on this one 😄 

Nice fix 👍 

Since there were technically _two_ changes of this pull request, I added another CHANGELOG entry in d3cc463cb7218000e22181345729ba6e6a82d7c2 to account for the `_nx` arguments placement fix.

**Comment by gziolo** [comment]
Should we copy those rules to https://github.com/WordPress/gutenberg/blob/bb24bbef1790b165ca8608d4cee7a5ec6e85c234/.eslintrc.js#L27?

**Comment by aduth** [comment]
@gziolo Oh, that's a good point re: these rules not actually taking effect. As the minimal effort short-term fix, that seems like the best option. I don't have any preference to whether that occurs here, since it's arguably a "separate" fix. I guess it would be fine enough to tackle here.

**Comment by tfrommen** [comment]
Oh well. I just pushed a new commit that now just vanished into Nirvana...

Will do that in another PR then... 😞

**Comment by gziolo** [comment]
I was about to open new PR to handle it, feel free to do it :)

**Pull request merged**
