### PR TITLE
Upgrade Reakit to stable v1.0.0

### PR DESCRIPTION
**Pull request by diegohaz**
## Description

This PR upgrades the `reakit` dependency on `@wordpress/components` to the stable `v1.0.0`.

Two things were fixed that are relevant to us:

1. `onMouseDown` on `ToolbarItem`s no longer prevents drag events from happening.
2. `CompositeItem` is now focused on VoiceOver clicks (<kbd>Control</kbd>+<kbd>Option</kbd>+<kbd>Space</kbd>), so we don't need this piece of code on `AlignmentMatrixControl` anymore.

## How has this been tested?

1. Check toolbars are working properly.
2. Check `AlignmentMatrixControl` introduced on #21091.

### CODE REVIEW

**Review by gziolo — COMMENTED** [review]
Code looks good, it's great to see stable version integrated :)

I guess it's best to leave it to @ItsJonQ to ensure that updated components work as expected. I can try to validate myself tomorrow if he won't be able to take care of it.

**Comment by diegohaz** [comment]
Fixed unit tests. We may want to use [`@testing-library/user-event`](https://github.com/testing-library/user-event) in the future.

@ItsJonQ Also, I remember you tried to use `aria-activedescendant` on `AlignmentMatrixControl` in the first iterations. If it's still needed, it should be working now (by passing `unstable_virtual: true` to `useCompositeState`).

**Comment by gziolo** [comment]
> Fixed unit tests. We may want to use [`@testing-library/user-event`](https://github.com/testing-library/user-event) in the future.

I have too many things going on, but I would be interested in doing an audit of existing RTL tests and updating them according to the guidelines shared by @kentcdodds in https://kentcdodds.com/blog/common-mistakes-with-react-testing-library. This way we will be able to reference this article in the testing guidelines and call it a day. I think it also means we should include the library you mentioned :)

**Review by ItsJonQ — APPROVED** [review]
@diegohaz Looks good to me! 🚀 
Tested it locally with Toolbars and the Alignment controls, and it works as expected

> Also, I remember you tried to use aria-activedescendant on AlignmentMatrixControl in the first iterations. If it's still needed, it should be working now (by passing unstable_virtual: true to useCompositeState).

I briefly tried passing the `unstable_virtual` prop into the `useCompositeState`. I didn't notice a difference, which I suppose is a good thing. I remember it not working previously.

We can test it some more and update it after this is merged 👏

**Pull request merged**
