### PR TITLE
[Block Editor - Inserter]: preload media categories empty check - client side

### PR DESCRIPTION
**Pull request by ntsekouras**
> If we don't make these requests, the media tab would need to wait for the resolution of these calls, making it display afterwards. This can be a jarring experience and we want to avoid it.

> The media inserter tab is implemented for post and site editors.

Right now these requests are preloaded here: https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-6.2/edit-form-blocks.php#L18.

In the back port PR for `6.2` there were suggestions to do this client side: https://github.com/WordPress/wordpress-develop/pull/3894#pullrequestreview-1268540839.

I'm not sure how much we gain doing it here or this is the right approach TBH. I'll need feedback.

The other implementation I was considering was to do the requests in `Editor` and `Site Editor` loading(ex: in `useBlockEditorSettings`) something like this:
```
// We need to check if there is at least one item for each media category before
// opening the inserter, in order to avoid late rendering of the media tab.
useEffect( () => {
	// Loop through categories to check if they have at least one media item.
	inserterMediaCategories?.forEach( ( category ) => {
		// Some sources are external and we don't need to make a request.
		if ( ! category.isExternalResource ) {
			category.fetch( { per_page: 1 } );
		}
	} );
}, [] );
```

...but when this API(setting) becomes stable, there would be no way to update this if that setting changes.

## Testing Instructions
1. Needed requests are made on editor load client side
2. Everything works as before.

### CODE REVIEW

**Comment by Mamaduka** [comment]
The `BlockList` is used in a few other places like Previews. Does it make sense to run the side-effect in those cases where we don't render Inserter?

**Comment by youknowriad** [comment]
> In the back port PR for 6.2 there were suggestions to do this client side: https://github.com/WordPress/wordpress-develop/pull/3894#pullrequestreview-1268540839.

I'm curious about this. If we can preload server-side it seems better no?

**Comment by Mamaduka** [comment]
Server-side preloading comes with the cost of increasing TTFB. I think it mostly depends on how critical the data is.

**Comment by youknowriad** [comment]
TTFB is less critical in the editor (as opposed to frontend) but I can see the point. Seems we should gather all these preloads and have a unique way to perform them client site as well. We now have two of them: media and patterns

**Comment by Mamaduka** [comment]
Maybe we can have something similar to SWR's `preload` helper - https://swr.vercel.app/docs/prefetching.

**Comment by felixarntz** [comment]
@youknowriad Is there no way for us to reasonably anticipate when the user will open the inserter / interact with a UI that needs the media categories (so that we could trigger the API requests early enough to not have a user visible delay)?

The main concern about preloading is that we shouldn't preload something that we don't know for sure is needed. It's fine to preload things that would otherwise be requested on every editor load anyway, but for more specific use-cases I'd say we should be cautious, since every preload adds to TTFB.

**Comment by ntsekouras** [comment]
>Is there no way for us to reasonably anticipate when the user will open the inserter / interact with a UI that needs the media categories (so that we could trigger the API requests early enough to not have a user visible delay)?

Not really. A user can just open the inserter as soon as the editor loads.

**Comment by felixarntz** [comment]
@ntsekouras @youknowriad Taking a step back here, to understand the use-case better: Can you provide some context why we need to know media categories whenever the block inserter is opened? Shouldn't that only be relevant to using blocks that interact with media?

My thinking is: If all I want to do with the inserter is e.g. insert a button block, or maybe I don't even want to use the inserter at all and just write some text, why do the media categories need to be loaded?

**Comment by youknowriad** [comment]
@felixarntz In the new inserter, you can insert "media" directly and these are shown per category in the inserter

**Comment by felixarntz** [comment]
@ntsekouras @youknowriad I just gave this a test to understand the concerns better. Here's my thoughts:
* I see how the "Media" tab appears a split second later after you have opened the inserter. That is certainly not a great user experience, so +1 to fix it.
* However, I would like to know, why does loading the media categories _prevent_ the "Media" tab from showing? I understand that these categories are important to show the content of the "Media" tab, however that is not the default tab, so even if something in that tab content is only populated a split second after opening the inserter, this should go unnoticed by the user.
* There's also the "Openverse" category in the "Media" tab content regardless of whether I have media on my site or not, so I would argue that tab should simply always be displayed unconditionally.

Does that make sense? Can we change the logic to always show the "Media" tab? This means we can just keep issuing these API requests only when the inserter is opened, rather than on page load, without any user-facing implications.

**Comment by ntsekouras** [comment]
@felixarntz   the media tab could be empty if no media in Library and have the Openverse integration disabled with [this setting](https://github.com/WordPress/gutenberg/pull/47404). That would result in the `media` tab disappearing.

Are these three requests for one item per media type so expensive that affect the performance?

Maybe we could add a check about the Openverse setting mentioned above first and do the other requests async client side. That could probably work.. I'll try this out.

**Comment by ntsekouras** [comment]
In my last commit the approach is:
1. If `enableOpenverseMediaCategory` setting is set to `true`(which is the default) show the `media` tab and also init the requests for the media types in library. This ensures that the media tab will be there right after we open the inserter and since it's not the default tab for any editor, it will almost certainly have resolved the requests when a user selects that tab.
2. If `enableOpenverseMediaCategory` is set to false, the `media` tab will wait for the resolution of the requests and will be displayed if there are any available media categories. This is not ideal, but it's less common and it's better than showing the `media` tab where there could be a chance to remove that tab after the requests' resolution.

**Review by youknowriad — APPROVED** [review]
Not perfect but works for me. 

I think @felixarntz's remark is a good one in the sense that if we can accept "empty panels" with some kind of placeholder, we should be able to optimize the inserter a lot.

This doesn't apply only to the inserter, we do have similar UI optimizations for block switcher as well I think.

Anyway, that's more of a UX discussion: is it ok to show empty panels instead of removing the tab entirely.

**Comment by ntsekouras** [comment]
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: 42bba6ec5d

**Comment by felixarntz** [comment]
@ntsekouras @youknowriad Just thinking out loud here, I wonder if (for a future enhancement) we could potentially consider using the overall attachment count for this. Wouldn't having _any_ attachment already satisfy the condition that at least one of the media categories is present, thus satisfy the criteria for showing the tab (together with the Openverse check)?

If so, potentially we could use [`wp_count_posts()`](https://developer.wordpress.org/reference/functions/wp_count_posts/) for the `attachment` post type, which can be used for that purpose. It would still add a (cached) query, but it's a simple query that is already present on several other admin pages on page load. Not saying this is necessarily the right approach, but another one to consider.

**Pull request merged**
