### PR TITLE
Remove Subheading block

### LINKED ISSUE #5475: Pressing Return in the subhead block does not create a new paragraph
Normally, pressing Return in a block creates a new paragraph block below it and moves the caret into it. Not so for the Subhead block (it just adds a line break). Intentional or bug?

### LINKED ISSUE #9308: Remove sub heading
Right now the sub heading has a few issues and isn't really solving many that other blocks don't. The original idea was to literally be a sub title that had a single use. This has now become something people both want in multiple places to use and grown beyond that intent. As we have headings and you can do styling with text, we no longer need this block. It's also not super understood as to the original intent.

I am going to suggest we for now remove this block. I do understand some already use it and the fallback should be a heading block, ideally a lower number than h4 to get size and not have SEO implications (which already are confusing with this block).

### PR DESCRIPTION
**Pull request by ZebulanStanphill**
## Description
Removed the Subheading block.

Fixes #9308 and closes #5475, #8141, #8234, and #8716.

## How has this been tested?
Ran packaged version of my branch and tested it. Subheading blocks became Classic blocks, and there were no apparent errors anywhere.

## Screenshots
image
(Ignore the extra buttons on the Classic block; those are added by Divi.)

## Types of changes
This change is currently entirely file deletions and line removals of everything related to the Subheading (`core/subhead`) block.

## Known issues
Using the <kbd><samp>Convert to Blocks</samp></kbd> option does not convert the content of the Classic blocks to Paragraph blocks. This seems to be due to the HTML comments; removing them makes the conversion work just fine. This same issue is occurring in #8821. It may be desirable to avoid merging both PRs until the solution to this issue is found.

Additionally, I noticed that even after removing the comments, there were still some issues with the conversion to a Paragraph block:
- The `wp-block-subhead` class was not preserved and put in the <samp>Additional CSS Class</samp> field.
- The inline `text-align` attribute on the `<p>` element was not preserved.

These seem to be issues with conversions from the Classic block in general, however. I think this is just another case of #6102. See also: #6878 and #7604.

I am not sure how many of these issues would be considered blockers. The `text-align` issue would be easily fixed by users by just setting the text alignment again, and I am doubtful that the `wp-block-subhead` class is being used enough to be that important about preserving in conversions. The HTML comment issue seems to be the biggest problem.

## Related issues and PRs
- #8821
- #9308

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
Converting to classic feels like a step back for usability. Is there any precedent in Gutenberg for converting a deprecated block to a classic?

This feels like exactly the case that the deprecated handlers are designed to handle.

**Comment by youknowriad** [comment]
I wonder if we should just hide it like we did for the text columns block for now and add a Deprecated call.

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten I don't think the deprecated block system can be used for converting from one block to a new one entirely. I think that is why the Text Columns block was not migrated to the Columns block, instead being removed from the inserter and marked as deprecated until it was removed 2 feature updates later. And speaking of which...

@youknowriad I had forgotten about what happened to the Text Columns block. I will open another PR for just deprecating the Subheading block.

I do wish the deprecated blocks system supported transformations from removed blocks. Is there any particular reason why this was not implemented, or was it simply overlooked?

**Comment by youknowriad** [comment]
> Is there any particular reason why this was not implemented, or was it simply overlooked?

I don't really know, it can be added later if necessary. There's still some improvements to make about how we handle old blocks.

**Comment by ZebulanStanphill** [comment]
I have created a new PR (#9355) to deprecate the Subheading block, rather than remove it.

**Pull request closed without merging**
