### PR TITLE
Migrate site editor feature preferences to interface package

### PR DESCRIPTION
**Pull request by talldan**
## Description
Partly addresses #31965. Related to #31965, #34135 and #34154.

Migrates site editor feature preferences over to the interface package.

As they've never hit core, I've deprecated the `toggleFeature` action and `isFeatureActive` selector and will remove them from a future version.

The way editor settings work in the site editor is slightly different to other editors, I guess it has been augmented for the theme.json.

Typically in other editors the settings are merged with the feature preferences using `useMemo` in the 'Editor' component before being passed into the `EditorProvider`, but the site editor uses a memoized selector to combine the values. This wouldn't work with this refactor, because the values are now in a different store.

The options:
- Use a registry selector. I don't think would be good, because from what I understand registry selectors can't be memoized.
- Follow the approach of other editors and `useMemo` in the Editor component. This is what I've done in this PR, but it's open to feedback. The downside is that the `focusMode` and `fixedToolbar` properties are no longer available when using the selector.
- Migrate from the selector to a `useEditorSettings` hook that combines settings with preferences. This might be the way to go. There's some prior art in the site editor with a `useSetting` hook - https://github.com/WordPress/gutenberg/blob/914f543e1e50d8c65c05a417efbdf539ef0d7a63/packages/edit-site/src/components/editor/utils.js#L101-L112
- Something else. Maybe editor settings should be reconsidered as an immutable object and other mutable values passed to the editor provider separately.

## How has this been tested?
1. Checkout trunk and open the site editor.
2. Set some preferences to a value different to the default (e.g. 'Top toolbar' and 'Spotlight Mode' to active.)
3. Checkout this branch, rebuild and open up the site editor
4. The preferences should be retained from step 2.
5. Try toggling top toolbar and spotlight mode settings to ensure they work.

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by talldan** [comment]
<strike>I've made some changes to the `clickOnMoreMenuItem` end to end test helper, so that it can be used across all the editors. It will require https://github.com/WordPress/gutenberg/pull/34154 to be merged first, as at the moment post editor tests fail in this PR.</strike>

edit: now ready for review.

**Comment by gziolo** [comment]
> Typically in other editors the settings are merged with the feature preferences using useMemo in the 'Editor' component before being passed into the EditorProvider, but the site editor uses a memoized selector to combine the values. This wouldn't work with this refactor, because the values are now in a different store.

@youknowriad should have a good overview of how it should work to pass down all the preferences to the block editor. If it's something different then feel free to ignore my comment 😅

**Comment by youknowriad** [comment]
Feels like "interface" is becoming a package that contain everything that need to be shared across screens. Kind of like a "utils" package. 

The questions I have is:

- Do we want the all the preferences of edit-post to stay in edit-site as well? Are there screen specific preferences?

**Comment by talldan** [comment]
> Feels like "interface" is becoming a package that contain everything that need to be shared across screens. 

Yeah, it's difficult to know where to draw the line on that. I did consider a separate package, but interface seems like a good fit as it already keeps some similar data in its store for controlling active/visible parts of the editor.

There are a few grey areas as part of the overall work, I'm wondering where things like the block manager could live - https://github.com/WordPress/gutenberg/issues/31965#issuecomment-902430158.

> Do we want the all the preferences of edit-post to stay in edit-site as well? Are there screen specific preferences?

At the moment each screen has individual preferences. With this change preferences could be shared across editors like proposed in #24370, but I think there needs to be more progress on that issue to understand exactly what approach should be taken.

**Comment by draganescu** [comment]
As long as the preferences are "interface preferences" (top toolbar, spotlight), and as long as we want to share these preferences between editors for a unified block editor interface experience, moving them to the interface package is good. 

All the block editors will need though the possibility to extend the preferences inherited from the interface package _with their own special preferences_, and also to disable default interface preferences they don't use.

**Comment by talldan** [comment]
Even if the decision is to make a 'preferences' package, it still might be worth going ahead with this. The site editor is the only editor that hasn't had this migration to interface, so going ahead will at least mean there isn't an odd one out situation. A future migration would be easier.

This PR also deprecates the site editor's preferences APIs, which would be good to do earlier so they can be removed.

**Comment by gziolo** [comment]
> Do we want the all the preferences of edit-post to stay in edit-site as well? Are there screen specific preferences?

It all depends on how the UI evolves and what user experience we want to have. We definitely want to have a unified way to store all preferences. The question is where it should be bundled is hard to answer because we still didn't fully define what role `@wordpress/interface` plays. It's still a WP package that gets bundled into other packages (`wp-edit-post`, `wp-edit-site`, etc) into the context of WordPress 😅

One question we should answer soon is whether preferences should be saved per screen (post, site, widgets, ...) as it happens today, or should we also let to store some preferences globally like for the top toolbar or full screen mode.

**Comment by talldan** [comment]
Superceded by #39158

**Pull request closed without merging**
