### PR TITLE
Update lock file format to version 2 (npm 8)

### PR DESCRIPTION
**Pull request by gziolo**
## Description

Related to #36142. Alternative to #37324.

Replaces #28886 (I failed to rebase the old branch from @fluiddot).
Replaces #33892 (I failed to rebase my own branch).

The new lock file format is optimized for monorepos so it would simplify the process of updating dependencies for WordPress packages. More about the new lock file format in https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson.html. More about other changes introduced in npm 7 in https://github.blog/2021-02-02-npm-7-is-now-generally-available/.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

### CODE REVIEW

**Comment by gziolo** [comment]
Current status:

Screen Shot 2021-10-28 at 15 19 57

**Comment by gziolo** [comment]
This branch works locally, you can test it with:

- `nvm use` to switch to Node.js 16 and npm 8
- `npm install`
- `npm run build` works correctly
- `npm run lint-js` works correctly
- `nom run test-unit` reports 4 test failures that need to be further investigated

**Comment by juanmaguitar** [comment]
@gziolo Why is this PR a Draft? And why does it have the label "Status: Blocked"? Is there anything blocking this PR?

**Comment by gziolo** [comment]
> Why is this PR a Draft? And why does it have the label "Status: Blocked"? Is there anything blocking this PR?

It’s not working on Continues Integration. Packages aren’t properly installed from npm. It’s related to outdated package forks used with React Native code. I didn’t have time to look into it closer but it was a blocker for quite some time.

**Comment by fluiddot** [comment]
> > Why is this PR a Draft? And why does it have the label "Status: Blocked"? Is there anything blocking this PR?
> 
> It’s not working on Continues Integration. Packages aren’t properly installed from npm. It’s related to outdated package forks used with React Native code. I didn’t have time to look into it closer but it was a blocker for quite some time.

@gziolo Heads up that I created [the following PR](https://github.com/WordPress/gutenberg/pull/40517) to investigate further the issues caused by React Native dependencies. I spotted a couple of issues (referenced in [this issue](https://github.com/WordPress/gutenberg/issues/40540)), the first one is related to permission issues when checking out the GitHub repository of some of the dependencies. However, after removing them, I identified new issues which don't look related to React Native. You can check the errors in the different PR checks [here](https://github.com/WordPress/gutenberg/pull/40517).

**Comment by gziolo** [comment]
Let's close in favor of https://github.com/WordPress/gutenberg/pull/40517 that is more up to date 😄

**Comment by fluiddot** [comment]
> Let's close in favor of https://github.com/WordPress/gutenberg/pull/40517 that is more up to date 😄

I'd like to note that I created that PR only for testing purposes 😅 , but I'm happy to continue the upgrade there if you prefer.

**Comment by gziolo** [comment]
> > Let's close in favor of #40517 that is more up to date 😄
> 
> I'd like to note that I created that PR only for testing purposes 😅 , but I'm happy to continue the upgrade there if you prefer.

I would have to recreate the branch from scratch anyway because the lock file changes so often 😄

**Pull request closed without merging**
