### PR TITLE
FSE: Add template loader unit tests

### PR DESCRIPTION
**Pull request by ockham**
## Description

Follow up from https://github.com/WordPress/gutenberg/issues/31399#issuecomment-832271121.

The block template resolution algorithm is quite complex, as it has to cover quite a lot of different possible cases resulting from various combinations of
- WP's "old" template hierarchy (including custom page templates, and child themes)
- block templates.

Things become especially complex when there are e.g. "oldschool" PHP templates with higher specificity than the available block templates; or when a parent theme 

For more discussion on this, see https://github.com/WordPress/gutenberg/issues/31399. Examples of previous iterations that sought to refine the algorithms' behavior include #29026, #30599, #31123, and #31336. This PR's goal is to eventually cover all of those cases.

Once we have full coverage of those scenarios, we can consider to refactor the template loader, e.g. akin to https://github.com/WraithKenny/gutenberg/commit/8a70acd76f2c23fece9658166dc37e04ae71a05e.

## How has this been tested?

Verify that CI goes green. Or locally:

```
npm run test-unit-php -- /var/www/html/wp-content/plugins/gutenberg/phpunit/class-template-loader-test.php
```

cc/ @WraithKenny @vdwijngaert @MaggieCabrera @aristath

### CODE REVIEW

**Comment by WraithKenny** [comment]
Just for notes: In reading the related merges and issues, it seems that there are two main concerns, broadly speaking.

The first is that the new (Template CPT/html) system, and the old (php file) system both work at the same time, depending on what is selected as the page template. (This is both the easier one and also the more important bit with regards to regression.)

The second issue is the confusing one (to me), where there can be a cascade of priority between CPT data, html files, and php files, complicated by parent/child overwriting. (I am completely out of the loop with regards to this part.)

Maybe these can be unit tested independently?

**Comment by ockham** [comment]
Okay, I think this should be ready for review now.

**Comment by MaggieCabrera** [comment]
The cases look good to me, I'll try to test this more thoroughly later. Thanks for doing this!

**Comment by ockham** [comment]
Follow-up to simplify the template loader logic: https://github.com/WordPress/gutenberg/pull/31604

**Comment by vdwijngaert** [comment]
Is this related? https://github.com/WordPress/gutenberg/issues/31652

**Comment by ockham** [comment]
> Is this related? #31652

Somewhat, yeah. Thanks for notifying; I'll reply there.

**Comment by ockham** [comment]
I'll go ahead and merge to unblock the two follow-up PRs, #31604 and #31671. #31671 has already been approved and contains a bugfix that I'd like to get in for WP 5.8 (i.e. GB 5.7 RC1). Furthermore, _this_ PR only adds a (passing) unit test, so it's fairly low-risk; it just captures the behavior of the template loader and guards it against regressions.

**Pull request merged**
