### PR TITLE
Block bindings: Change bindings panel title, add description.

### PR DESCRIPTION
**Pull request by cbravobernal**
## What?

Issue related: https://github.com/WordPress/gutenberg/issues/61404

Trying to improve the developer experience by changing the title and adding a description as this comment.
https://github.com/WordPress/gutenberg/issues/61404#issuecomment-2154894396

## Screenshots or screencast 
Screenshot 2024-06-11 at 18 33 27

### CODE REVIEW

**Review by SantosGuillamot — APPROVED** [review]
Code-wise, it looks good to me. And it seems to be working. I'll defer the approval to the people involved in [the original conversation](https://github.com/WordPress/gutenberg/issues/61404#issuecomment-2154266117) to ensure we are aligned in the title and the help text.

**Comment by jasmussen** [comment]
Looks good.

Let's tweak the help text slightly per feedback. It could say, outside of better suggestions: "Connected attributes connected to different sources."

screenshot of suggested text

That would also avoid the typographic widow.

**Comment by cbravobernal** [comment]
> Connected attributes connected to different sources.

Are we repeating the word connected too much in that sentence?

**Comment by jasmussen** [comment]
> Are we repeating the word connected too much in that sentence?

Right, we certainly are. Sorry, I hadn't gotten enough coffee.

The important part here is to avoid the typographic widow. So if we go with the original intent, we either have to add a word, or remove a word, so it fits on one line. The idea here is that on the second line, there should be at least two words.

This can also be addressed by adding `text-wrap: pretty;` to the helper text component, but that's probably best done separately.

**Comment by jasmussen** [comment]
How about this:

"Attributes connected to various sources."
Screenshot 2024-06-12 at 10 27 26

**Comment by cbravobernal** [comment]
> How about this:
> 
> "Attributes connected to various sources." Screenshot 2024-06-12 at 10 27 26

That one looks much better, thanks @jasmussen

**Comment by ellatrix** [comment]
I just cherry-picked this PR to the wp/6.6-beta-3 branch to get it included in the next release: a95c4511f9

**Pull request merged**
