### PR TITLE
Update `package-lock.json` with `eslint-scope` version `3.7.3`

### PR DESCRIPTION
**Pull request by ntwb**
## Description

This PR regenerates the `package-lock.json` file from scratch, notable changes:

• Bumps `eslint-scope` from `3.7.1` to `3.7.3`
• Bumps Babel v7 beta packages from `7.0.0-beta.52` to `7.0.0-beta.53`

Bumping `eslint-scope` to `3.7.3` ensures that the [compromised  `3.7.2` release](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) will not be used.

## Types of changes

Build Tools

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by pento** [comment]
How did you generate the new `package-lock.json`?

**Comment by ntwb** [comment]
> How did you generate the new `package-lock.json`?

I deleted both `package-lock.json` and `node_modules` followed by `npm install`

p.s. `npm audit` fails with 4 warnings for `hoek` due to the same issue `node-sass` has but this time for the `node-gyp` package 😞

**Comment by pento** [comment]
Huh, I was getting weird failures when I did that, but now it seems to have sorted itself out? 🙃

**Review by pento — APPROVED** [review]
:shipit:

**Comment by ntwb** [comment]
> Huh, I was getting weird failures when I did that, but now it seems to have sorted itself out? 🙃

It wouldn't work for me Wednesday either /shrug

**Pull request merged**
