### PR TITLE
Plugin: Remove the experimental Progressive Web Apps (PWA) integration

### PR DESCRIPTION
**Pull request by ellatrix**
## Description

Reverts #33102. I thought this was a cool experiment at the time with the idea to expand the service worker with offline editing capabilities, but this is not a priority at the moment and it's not worth the time to currently maintain without the extra capabilities.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

### CODE REVIEW

**Review by mcsf — APPROVED** [review]
Go for it. :)

**Comment by mcsf** [comment]
@ellatrix: anything blocking the merge here?

**Comment by gziolo** [comment]
I triggered e2e tests again, but the test failures didn't look related to this PR.

**Review by gziolo — APPROVED** [review]

**Comment by ellatrix** [comment]
Just getting the tests to pass. Already rebased it, but some other (flaky?) tests now fail.

**Comment by ocean90** [comment]
Should we try another rebase in case the test was fixed in the meantime?

**Comment by gziolo** [comment]
@ellatrix, can you rebase this one and merge?

**Comment by talldan** [comment]
@ellatrix @gziolo I'm not sure how the autocomplete tests could possibly related to the PWA integration, but they've been failing since this was merged. They were also failing in the last commit on this branch. Seems like a bug might have been introduced here?

It'd be appreciated if you could add a comment about why you'd merge a PR with failing CI, because it leaves those of us in a different timezone very confused and blocked.

**Comment by talldan** [comment]
There's a JS error buried in the test failure that might provide some clues:
```console
Expected mock function not to be called but it was called with:
    ["jQuery.Deferred exception: Cannot read properties of undefined (reading 'data') TypeError: Cannot read properties of undefined (reading 'data')

      at f (../../http:/localhost:8889/wp-admin/js/user-profile.min.js?ver=6.0-alpha-52822:2:195)
      at v (../../http:/localhost:8889/wp-admin/js/user-profile.min.js?ver=6.0-alpha-52822:2:1207)
      at HTMLDocument.<anonymous> (../../http:/localhost:8889/wp-admin/js/user-profile.min.js?ver=6.0-alpha-52822:2:5150)
      at e (../../http:/localhost:8889/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,zxcvbn-async&ver=6.0-alpha-52822:2:30038)
      at t (../../http:/localhost:8889/wp-admin/load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,zxcvbn-async&ver=6.0-alpha-52822:2:30340) "]
          at runMicrotasks (<anonymous>)
```

That's possibly happening when the test creates a user. I couldn't reproduce it locally though.

**Comment by gziolo** [comment]
> It'd be appreciated if you could add a comment about why you'd merge a PR with failing CI, because it leaves those of us in a different timezone very confused and blocked.

This PR only removes code added https://github.com/WordPress/gutenberg/pull/33102. I didn't anticipate it would break anything since no tests were updated in the original PR. Anyway, we can revert it and add back the removed code. It's a very strange issue and should never break any tests.

**Comment by talldan** [comment]
> This PR only removes code added https://github.com/WordPress/gutenberg/pull/33102. I didn't anticipate it would break anything since no tests were updated in the original PR. Anyway, we can revert it and add back the removed code. It's a very strange issue and should never break any tests.

Yeah, I don't get it either. Thanks for putting up a PR for reverting the revert. Lets see what happens with the tests on that one.

**Comment by gziolo** [comment]
> > This PR only removes code added #33102. I didn't anticipate it would break anything since no tests were updated in the original PR. Anyway, we can revert it and add back the removed code. It's a very strange issue and should never break any tests.
> 
> Yeah, I don't get it either. Thanks for putting up a PR for reverting the revert. Lets see what happens with the tests on that one.

Tests pass in the PR. Let's land that one and I will open another PR that attempts to revert this functionality. I'm really curious what type of bug we have in Gutenberg. I hope it's related only to the test setup.

**Comment by gziolo** [comment]
Reverted with https://github.com/WordPress/gutenberg/pull/33102. I will open another PR and try to fix the issue with tests.

**Pull request merged**
