### PR TITLE
Remove the post permalink UI from the post title

### LINKED ISSUE #5494: Improve Permalink UI placement and tab order
Once #5414 is finalized, the placement and tab order of the permalinks UI should be improved for better keyboard accessibility. Right now, the Permalinks UI appears _before_ the post title:

screen shot 2018-03-08 at 09 06 47

Not speaking about its _visual_ placement. Considering its placement in the markup, the tab order is far from ideal and currently forces users to tab backwards from the post title once the permalink UI appears. This applies to all keyboard users. Screen reader users wouldn't have any clue something appeared on the screen.

Ideally, the tab order should be different: post title -> permalink UI.

### PR DESCRIPTION
**Pull request by youknowriad**
closes #5494 

This PR removes the Post Permalink UI from the Post Title as suggested in #5494 
At the same time, it simplifies the DOM and styles for the post title a lot. 

**Notes**

In 2019, you'll notice a bug in the PostTitle (not centered properly) but I believe this is because the editor styles are targetting these internal classNames while ideally they shouldn't.  cc @kjellr 

I tried keeping the old classNames to reduce the scope of the breakage and and added "Needs dev note".

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for this. This is what I see:

Screenshot 2020-03-24 at 11 16 51

I'm very happy to see so much red code. That's good. Removing the permalink UI from the title block is also fine, because:

- Importantly, it addresses #5494
- There is duplicate UI in the sidebar
- Customizing the permalink is sort of an advanced feature
- It was never that discoverable by the title
- The title will become a block eventually

I would have liked to see the permalink UI also be in the pre-publish dialog. But this PR doesn't preclude that from happening.

So high level, 👍 👍 on this.

---

However, there are some issues with the responsive breakpoints:

breakpoints

That's TwentyNineteen, but that theme does not appear to be at fault, as the same issues appear when no editor style is loaded:

vanilla

I have a bit on my plate today, and toddlers to juggle, but if this isn't easy to fix, I can help out maybe tomorrow.

**Comment by youknowriad** [comment]
@jasmussen I'll look at the responsive issues, we might not have the same 2019 styles though as It's always left-aligned for me.

**Comment by jasmussen** [comment]
Yep that left alignment has been fixed in the RC release but not 5.3

**Comment by youknowriad** [comment]
I think I fixed the issue in 4ae1990 
The problem is that we had padding around the canvas but it was only applied to the block list, not the post title. I moved that style to a more englobing selector (and tweaked it to adapt for the removal of the side UI)

**Comment by gziolo** [comment]
> This PR removes the Post Permalink UI from the Post Title as suggested in #5494
> At the same time, it simplifies the DOM and styles for the post title a lot.

It looks like the removed component was never part of the public API, that's good 👍

**Comment by jasmussen** [comment]
The recent change appears to have messed a bit with the full-width styles, which I believe apply negative margin to account for the padding you removed. 

I think it's good to remove that padding, it has to be at some point.

**Review by jasmussen — APPROVED** [review]
This tests well for me. I tested fullwide images in TwentyTwenty and a theme that doesn't load editor styles, and things behave well. I'm loving how much code we can remove. 

TwentyNineteen has an issue with fullwide images, but that appears to be the case beyond this PR. Let's consider creating a trac ticket for it.

**Comment by ellatrix** [comment]
Oh, thanks! This is so much better. 👍

**Pull request merged**
