### PR TITLE
Replace legacy widget icon with its new version

### LINKED ISSUE #32750: Swap the Legacy Widget block icon (with version that matches icon template more closely)
The Legacy Widget block icon stands out from other icons due to it being slightly bigger. I've recreated the icon at the correct scale based on the Design Library icon template:

legacy-widget-icon

This will especially help when seeing lots of icons together in the Inserter:

inserter-legacy-widget

The new icon can be found in the Figma Design Library: https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=5415%3A22557

### PR DESCRIPTION
**Pull request by manooweb**
Fixes https://github.com/WordPress/gutenberg/issues/32750

Simply replace the svg `<path>` tag with the new one exported from Figma
https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?node-id=5415%3A22557

### CODE REVIEW

**Comment by critterverse** [comment]
This looks so much better, thanks @manooweb! The only thing I noticed when testing is that the alignment for this icon is a bit off-center. It looks to be 3px up and 4px left of center (in the block toolbar, block inspector, inserter panel, etc). Here's what I'm seeing with a red icon overlayed to show where the icon appears for other blocks:

legacy-widget-icon

**Comment by manooweb** [comment]
> This looks so much better, thanks @manooweb! The only thing I noticed when testing is that the alignment for this icon is a bit off-center. It looks to be 3px up and 4px left of center (in the block toolbar, block inspector, inserter panel, etc). Here's what I'm seeing with a red icon overlayed to show where the icon appears for other blocks:
> 
> legacy-widget-icon

Yes! You're right. 🤔 It's strange that styles seem not correctly applied for this icon. I'm going to look for that 😉

**Comment by manooweb** [comment]
Sorry I didn't correctly exported the legacy widget icon from Figma. Its margins were missing.
I pushed again and now it should be good.

**Comment by critterverse** [comment]
This looks great 👍 
Let me know if you need any help requesting a code review @manooweb!

**Comment by manooweb** [comment]
> This looks great 👍
> Let me know if you need any help requesting a code review @manooweb!

@critterverse Yes! I have no access on this repository to request one.

**Review by adamziel — APPROVED** [review]

**Pull request merged**
