### PR TITLE
[RNmobile] Fix untranslated text

### LINKED ISSUE #2460: Some strings are not translated since release 1.31
**Describe the bug**
Some Gutenberg strings are not translated. The `gutenberg_native_` strings exist and are correctly translated in `WordPress/src/main/res/values-*/strings.xml`.

Block picker|Image picker
-|-
Screenshot_1593612400 | Screenshot_1593612411

**To Reproduce**
1. Set your device or the app in a non english language.
2. Go to the block editor.
3. Click on "+" to add a new block.
4. Notice the blocks are not translated.

The problem is new since gb-mobile 1.31 (and the monorepo).

**Additional context**

Some info about the process to translate gb-strings:

1. in libs/gutenberg-mobile, yarn genstrings, gets the strings from .native.js files and create a ./bundle/android/strings.xml file (for Android)
2. python tools/merge_strings_xml.py, to merge ./bundle/android/strings.xml with the main strings.xml file
3. We send this to GlotPress.
4. We pull translations before the app release.
5. At runtime, gutenberg-mobile is pulling translations from the main strings.xml file (see here)[https://github.com/wordpress-mobile/WordPress-Android/blob/a15171c130b28acbcbc33cbfd0d4838740954ac9/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java#L179-L247] and generates a map (english source -> translated string).
6. This map is passed from the fragment to the glue code.
7. Glue code passes this map as an initial prop to the Gutenberg component. 

The translations are correctly passed as initial prop.

### PR DESCRIPTION
**Pull request by cameronvoell**
## Description

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2460

## How has this been tested?

To Test Block names in Inserter:

1. Set your device or the app in a non english language.
2. Go to the block editor.
3. Click on "+" to add a new block.
4. Notice the blocks are translated.

To test Media options:

1. Set your device or the app in a non english language.
2. Go to the block editor.
3. Click on "+" and add a new image block.
4. Click the block and notice all bottom sheet menu items are translated

## Screenshots 
Screenshot_20200706-231831_WordPress Beta
Screenshot_20200706-231852_WordPress Beta

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
I've tested this on iOS and while I can see some untranslated strings on the demo app, when using the main WP-iOS app I don't see any untranslated strings. Maybe just an issue with the way we initialize the demo app?

**Review by SergioEstevao — APPROVED** [review]
Approved for iOS running on the main apps.
We probably will need a follow up PR to make sure the demo apps also work correctly.

**Comment by SergioEstevao** [comment]
@cameronvoell for future reference can you add some more detail on the ticket description about "why" the change was needed.

**Comment by hypest** [comment]
I concur with @SergioEstevao's findings that the core demo app doesn't show translations correctly but it's fine to address it seperately.

Tried out [WPAndroid from the editor v1.31.1 release](https://github.com/wordpress-mobile/WordPress-Android/pull/12349) and works fine for me.

One thing to note: this PR here exhibits some Inserter animation jankiness on the core demo app. I experience a small hiccup on Inserter open, on all attempts to open it, with the demo content on a Pixel 2XL physical device. *I don't experience that jankiness though* when testing the commits this PR introduces in isolation on top of [the 1.31.1 release PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2461). So, what I've suggested to @SergioEstevao over chat is to cherry-pick the commits from here directly into the editor release branch to make sure we don't introduce a new issue.

**Review by hypest — APPROVED** [review]
LGTM!

**Pull request merged**
