### PR TITLE
Try updating composer packages

### PR DESCRIPTION
**Pull request by talldan**
## Description
PHP unit tests are failing at the moment, as our docker images now use PHP 8 (https://github.com/docker-library/wordpress/pull/551/files). This PR updates composer packages to those compatible with PHP 8.

### CODE REVIEW

**Comment by getdave** [comment]
I think I saw a similar set of errors where I had to update `composer` _itself_. Not sure what version of Composer runs on CI.

**Comment by talldan** [comment]
Tests seem to be running now 🎉 

I had to update phpunit to v8.5. Not sure if there are any known issues with that.

However there are what look like some legit test failures. Not sure if these snuck in while tests weren't running on CI:
```
There were 3 failures:

1) Theme_JSON_Legacy_Settings_Test::test_legacy_settings_custom_units_can_be_disabled
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'units' => Array (...)
+    'customPadding' => false
 )

/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/abstract-testcase.php:746
/var/www/html/wp-content/plugins/gutenberg/phpunit/class-wp-theme-json-legacy-settings-test.php:94

2) Theme_JSON_Legacy_Settings_Test::test_legacy_settings_custom_units_can_be_enabled
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'units' => Array (...)
+    'customPadding' => false
 )

/var/www/html/wp-content/plugins/gutenberg/vendor/wp-phpunit/wp-phpunit/includes/abstract-testcase.php:746
/var/www/html/wp-content/plugins/gutenberg/phpunit/class-wp-theme-json-legacy-settings-test.php:108

3) Theme_JSON_Legacy_Settings_Test::test_legacy_settings_custom_units_can_be_filtered
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'units' => Array (...)
+    'customPadding' => false
 )
 ```

**Comment by nosolosw** [comment]
Hey, I've landed a fix for the legacy settings failures https://github.com/WordPress/gutenberg/pull/28628 and other minor things https://github.com/WordPress/gutenberg/pull/28629 Rebased this PR with current `master`.

This is how I've tested:

- Nuke everything: `npm run wp-env destroy`. I also removed manually all docker containers and images.
- Run `npm run test-php` => tells composer to install a few things if they aren't already and runs lint & test jobs.

With the latest changes, it shouldn't report any errors.

**Comment by ockham** [comment]
Thanks all! Once we've got PHP unit tests back up again, should we maybe promote them to 'Required' in GitHub Actions?

**Review by oandregal — APPROVED** [review]
This fixes the PHP issues we're having, which are quite disruptive to the workflow, so I'm going to go ahead and merge it. I still see some e2e failures, but they are unrelated to this PR.

**Comment by talldan** [comment]
Great stuff, thanks @nosolosw!

**Pull request merged**
