### PR TITLE
DataViews: Update folders structure

### PR DESCRIPTION
**Pull request by ntsekouras**
## What?
This is just a bit house keeping in DataViews package, where I added some folders to separate a bit the files.

We could do more as we add more and intentionally I didn't suggest many changes right now - just three new folders(filters,views,actions).

### CODE REVIEW

**Review by mcsf — APPROVED** [review]
No opinion, sounds fine to me :)
I'll _approve_ to unlock the merging, but consider anyone else's objections first.

**Comment by oandregal** [comment]
I'm fine with this, though my only objection is that this PR doesn't make backporting fixes for WordPress RC harder. (check that this is going in the gutenberg version that is bundled for WP).

**Comment by oandregal** [comment]
https://github.com/WordPress/gutenberg/pull/56721#discussion_r1412430851 I prefer `layouts` over `views` as a folder name, to be consistent with what we have elsewhere.

**Comment by ntsekouras** [comment]
>though my only objection is that this PR doesn't make backporting fixes for WordPress RC harder

How would this affect the backporting? 🤔

**Comment by oandregal** [comment]
@ntsekouras in situations where two branches have different folder structure. If this PR is part of WP is fine (same folder structure in trunk and `wp/6.5` branch).

**Comment by mcsf** [comment]
> No opinion, sounds fine to me :) I'll _approve_ to unlock the merging, but consider anyone else's objections first.

After discussing this in private, I no longer endorse this. :P But I also don't mean to block.

**Pull request closed without merging**
