### PR TITLE
Block Editor: Implement a responsive grid mode for `InnerBlocks` and a basic grid block that leverages it 2.

### PR DESCRIPTION
**Pull request by epiqueras**
This PR is an alternative to #18600 that implements everything from https://github.com/WordPress/gutenberg/issues/19254#issuecomment-578190112 except for resizable gridlines.

The most important feature which differentiates this from #18600 is:

>A Grid block should allow setting a breakpoint at which its children go from adhering to the grid layout to just rendering sequentially. This is significantly easier for users to manipulate and pick up than dealing with different grid layouts at multiple different breakpoints. Most users will have simple designs with a stacked mobile view, but power users can still achieve complex designs by nesting grids with different breakpoints. We might also need a breakpoint at which a grid item is completely hidden.

### `Editor => Breakpoint`

Screen Shot 2020-02-02 at 5 28 48 PM

### `Editor < Breakpoint`

Screen Shot 2020-02-02 at 5 28 55 PM

### `Front End => Breakpoint`

Screen Shot 2020-02-02 at 5 29 09 PM

### `Front End < Breakpoint`

Screen Shot 2020-02-02 at 5 29 18 PM

### CODE REVIEW

**Comment by epiqueras** [comment]
The lighter DOM seems to have done wonders for this approach, nice work @ellatrix!

**Comment by epiqueras** [comment]
@shaunandrews This is what I meant in https://github.com/WordPress/gutenberg/issues/19254#issuecomment-578190112.

**Comment by epiqueras** [comment]
cc @mtias

**Comment by shaunandrews** [comment]
Been playing with this block for the past day or two, and I see a lot of potential to create some really nice layouts. I've worked up a prototype that walks through the creation and manipulation of multiple Section blocks within the Grid block. This briefly explores the drag-and-drop interactions for creating a new section, resizing and section, and moving a section.

grids i9 - full flow

The empty Grid block shows a, um, _grid_ of squares to represent the rows and columns, and the space between them. The toolbar includes controls for adjusting the number of rows and columns, along with the spacing; Changes to these controls would be reflected with the squares in realtime.

grids i9 toolbar controls

I also wanted to consider how we could use the keyboard for creation of new Sections:

Grids Keyboard Creation

You can [dive into the Figma file](https://www.figma.com/file/urIMcHgHicoTxIb18uZ3BA/Block-Grid?node-id=18%3A1161) to see the full-resolution screens and try the prototype for yourself.

**Comment by epiqueras** [comment]
Beautiful!

**Comment by epiqueras** [comment]
I had a bit of time to make this look a bit more like the new design today:

gif

**Comment by ockham** [comment]
Apologies for the obvious question, but how do I test this? Specifically, which kind of block do I insert into a post to get this Grid layout?

**Comment by ockham** [comment]
Rebased.

**Comment by epiqueras** [comment]
The grid block.

**Comment by paaljoachim** [comment]
Btw here is another Grid issue: https://github.com/WordPress/gutenberg/issues/16271

**Comment by epiqueras** [comment]
Closing this for now.

**Pull request closed without merging**
