### PR TITLE
Social Links: add Bluesky logo

### PR DESCRIPTION
**Pull request by jeherve**
## What?

This introduces a new Social Link icon, for the Bluesky service. The icon was made official a few months ago, in [this post](https://blueskyweb.xyz/blog/12-21-2023-butterfly).

## Why?

Bluesky, despite being a fairly new addition to the social network scene, has quickly become quite popular as an alternative to Twitter. It could be useful for site owners to want to list their Bluesky profile alongside their other social media presences.

## How?

This adds the new icon and service, as well as tests.

## Testing Instructions

1. Go to Posts > Add New
2. Add the Social Links block
3. Within the block, add a new Bluesky block
4. Publish your post
5. View on the frontend.

### Testing Instructions for Keyboard

Same as above, this behavior does not change in this PR.

## Screenshots or screencast

Screenshot 2023-12-20 at 17 58 28
Screenshot 2023-12-20 at 17 57 37

### CODE REVIEW

**Comment by Krisueu** [comment]
Unfortunately the test does not work

The bluesky button is now available for download from the official website

https://blueskyweb.xyz/blog/press-faq

Here is the link : https://drive.google.com/drive/folders/16mlJPfWNnc6jj-3vGZ88SFysIY13GBp0

**Comment by jeherve** [comment]
> Unfortunately the test does not work

I believe you're referring to the "Enforce labels on Pull Request" test? This can only be addressed by folks who have admin access on this repository, I'm afraid, so we'll need to wait until they review this Pull Request.

> The bluesky button is now available for download from the official website

Yes, that's the logo used on this Pull Request.

**Comment by tomfinitely** [comment]
There's a duplicate issue over at https://github.com/Automattic/wp-calypso/issues/87249#issue-2121824911 — I don't know if Gutenberg adding the icon would negate the Calypso issue or not. 

Regardless, since Bluesky is officially open for all, it would make sense to prioritize the addition of their icon in an upcoming release.

**Comment by tomfinitely** [comment]
@ajitbohra seems this merge is being held up by an issue that has no bearing on the icon itself.

**Comment by jeherve** [comment]
Looks like #61372 was open and merged, so this is now unnecessary. I'll close it.

**Pull request closed without merging**
